### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/go-ethereum#1006]
Type `web3` in the console and you get two errors:

* `Error response: shh_version method not available: whisper offline`
* `whisper: Error: Invalid JSON RPC response`

```
> web3
Error response: shh_version method not available: whisper offline
{
  providers: {
    HttpProvider: [Function],
    QtSyncProvider: [Function]
  },
  version: {
    api: '0.3.5',
    client: 'Geth/v0.9.21/darwin/go1.4.2',
    network: '0',
    ethereum: '60',
    whisper: Error: Invalid JSON RPC response
  },
```

**Comment by zelig** [comment]
you need to start `geth` with the `--shh` option to use whisper. Since it is not officially released with frontier, whisper is off by default.

**Comment by JustinDrake** [comment]
So by default we get two errors if we type `web3` in the console? That seems wrong.

**Comment by zelig** [comment]
Yes you are right, this should be handled with friendlier messages

**Comment by zelig** [comment]
sry i dont see a better way for now. will handle it partially in web3.js pretty print
