### ISSUE TITLE
When the miner succeeds, it sometimes locks up geth

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#1008]
I'm running on mulitple nodes, and quite often some of them start locking up, always having "Mined block XXX" as the last thing output.

```
I0516 14:19:00.476564   14838 chain_manager.go:627] imported 1 block(s) (0 queued 0 ignored) in 6.010422ms. #352642 [ae9950b4 / ae9950b4]
I0516 14:19:00.480562   14838 worker.go:227] 🔨  Mined block #352642
```

After which the node locks up.

**Comment by karalabe** [comment]
Though I'm seeing rare lockups without the mined block too. Maybe this is related to my previous issue with the racey channel handling. We should sort that out first and see if it resolves this one.

**Comment by karalabe** [comment]
Possible duplicate of #979, but not sure.

**Comment by obscuren** [comment]
Check if still the case on `0.9.21.1`

**Comment by karalabe** [comment]
I've no idea exactly when, but this issue seems to have been fixed. I'm guessing that it was one of my threading fixes either in eth/peer.go or downloader/peer.go. Anyway, long story short, closing.
