### ISSUE TITLE
Upgraded geth, and lost accounts

### ISSUE THREAD

**Issue by julian1** [ethereum/go-ethereum#1009]
$ aptitude show geth 
    Package: geth                            
    New: yes
    State: installed
    Automatically installed: no
    Version: 9.21.1+509SNAPSHOT20150516111151trusty-0ubuntu1

Previous version was installed about a week ago. 

    > eth.accounts
    [  ]

While a previous account created/key existed with some test-ether

**Comment by veox** [comment]
The key directory has been renamed from `keys` to `keystore`.

**Comment by obscuren** [comment]
Please read https://github.com/ethereum/go-ethereum/releases/tag/v0.9.21.1 section **upgrade**
