### ISSUE TITLE
Implement nuke option

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#1010]
`geth nuke` should `rm -rf $ETH_PATH/blockchain && rm -rf $ETH_PATH/state`

**Comment by zelig** [comment]
i like `nuke` but don't you think `removedb` would be more civil?

**Comment by tgerring** [comment]
Agree with @zelig so implemented in #1033 as `removedb`

**Comment by obscuren** [comment]
WTF. No 🌋!?
