### ISSUE TITLE
Automatic DAG pregeneration for smooth epoch transition

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#1015]
> would be extra nice if user could specify param on CLI for how many blocks before epoch to generate next DAG. i.e. 300 blocks @ 12s ~ 1 hour before next epoch

This is very easy to implement by watching block number instead and generate next DAG when 

```
ethashDir := "~/.ethash"
currentEpoch := currentBlock.Number/30000
if currentBlock.Number % 30000 > X {
  os.Remove(filepath.Join(ethashDir, dagFile(currentEpoch-1)
  makeDAG(currentEpoch+1, ethashDir)
}
```

**Comment by tgerring** [comment]
Here's a bit maths for the console, assuming avgBlockSecs is set by user based on current generation rate, which may be lower than 12:

```
> avgBlockSecs = 7; epoch = 30000; (epoch - eth.blockNumber % epoch) * avgBlockSecs / 3600 + ' hours until epoch ' + (eth.blockNumber - eth.blockNumber % epoch + epoch)
'4.7775 hours until epoch 360000'
```

**Comment by tgerring** [comment]
How should cleanup of old DAGs be handled?

Would it be sufficient to delete last DAG when generating next DAG?

**Comment by zelig** [comment]
yes i always keep 2
