### ISSUE TITLE
getCoinbase method missing

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/go-ethereum#1016]
[The documentation](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcoinbase) documents  `getCoinbase`, which doesn't exist in `geth`:

```
> eth.getCoinbase
undefined
```

**Comment by karalabe** [comment]
Although you are right that the docs are off, I don't really see the value of the function call it it's already maintained in a readable variable.

@frozeman Was there a decision sometime to use only vars for these and not functions any more? If so, could you update the docs throughout? (getMining is off too for example).

**Comment by zelig** [comment]
Here is the full list
```js

> eth.getCoinbase
undefined
> eth.getHashrate
undefined
> eth.getAccounts
undefined
> eth.getMining
undefined
> eth.getBlockNumber
undefined
> eth.getGasPrice
undefined
> net.getPeerCount
undefined
> net.getListening
undefined
```

**Comment by debris** [comment]
You need to update web3.js to version 0.4.x

**Comment by frozeman** [comment]
yes, and we introduced those to make it possible to do all calls in an async way.

**Comment by frozeman** [comment]
all old variables are still working.

**Comment by obscuren** [comment]
@zelig this is now fixed with the web3 update?

**Comment by karalabe** [comment]
Fixed a long time ago. Closing.
