### ISSUE TITLE
Problem with early CTRL-C

### ISSUE THREAD

**Issue by simenfd** [ethereum/go-ethereum#1017]
Notice that I needed to press CTRL-C twice in order to stop the program.  This is a minor issue, on the surface at least.
Running: Linux, latest version

./geth
I0517 01:00:57.120083   21915 backend.go:240] Protocol Version: 60, Network Id: 0
I0517 01:00:57.120160   21915 backend.go:250] Blockchain DB Version: 2
I0517 01:00:57.121665   21915 chain_manager.go:241] Last block (#357407) 989a1d17ec3b09a06f79b480cb406e08582388ea9cf914a545700d48f28973f3 TD=97553607642257
^CI0517 01:00:57.700945   21915 cmd.go:53] Shutting down (interrupt) ... 
I0517 01:00:58.237607   21915 cmd.go:107] Starting Geth/v0.9.21.1/linux/go1.4.2
I0517 01:00:58.237725   21915 server.go:209] Starting Server
I0517 01:00:58.245018   21915 nat.go:95] mapped network port udp:30303 -> 30303 (ethereum discovery) using NAT-PMP(10.0.0.1)
I0517 01:00:58.327692   21915 udp.go:189] Listening, enode://87789dca8fcbaadedc5c1e8e8c451cf7368d2390ed8ebf210cbf360a31660c70656cdc05fa4097cc125d54fe7496dfd7c3d123413e939fc09b8281c28566586d@84.209.106.169:30303
I0517 01:00:58.327858   21915 backend.go:458] Server started
I0517 01:00:58.327957   21915 server.go:349] Listening on [::]:30303
I0517 01:00:58.333623   21915 nat.go:95] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(10.0.0.1)
I0517 01:01:16.046369   21915 downloader.go:145] Block synchronisation started
I0517 01:01:19.670976   21915 chain_manager.go:670] Fork detected @ 978692f5. Reorganising chain from #357407 989a1d17 to eeb4dd9a
I0517 01:01:19.706109   21915 chain_manager.go:627] imported 5 block(s) (0 queued 0 ignored) in 1.376392692s. #357411 [eeb4dd9a / 5230d84e]
I0517 01:01:39.353416   21915 chain_manager.go:627] imported 3 block(s) (0 queued 0 ignored) in 24.08005ms. #357414 [1f2cd5a2 / c1a3513d]
I0517 01:01:40.665003   21915 chain_manager.go:627] imported 1 block(s) (0 queued 0 ignored) in 12.560346ms. #357415 [a427a57b / a427a57b]
I0517 01:01:42.329344   21915 chain_manager.go:627] imported 0 block(s) (0 queued 1 ignored) in 103.436µs. #357415 [a427a57b / a427a57b]
^CI0517 01:01:42.809060   21915 cmd.go:53] Shutting down (interrupt) ... 
I0517 01:01:42.809206   21915 handler.go:119] Stopping ethereum protocol handler...
I0517 01:01:42.809285   21915 handler.go:129] Ethereum protocol handler stopped
I0517 01:01:42.809355   21915 chain_manager.go:495] Chain manager stopped
I0517 01:01:42.809418   21915 transaction_pool.go:271] TX Pool stopped
I0517 01:01:42.809490   21915 backend.go:525] Server stopped
I0517 01:01:42.813133   21915 database.go:125] flushed and closed db: /home/alant/.ethereum/blockchain
I0517 01:01:42.816923   21915 database.go:125] flushed and closed db: /home/alant/.ethereum/state
I0517 01:01:42.817202   21915 database.go:125] flushed and closed db: /home/alant/.ethereum/extra

**Comment by obscuren** [comment]
Did it say something along the lines of `I0517 18:27:25.875730   48417 handler.go:119] Stopping ethereum protocol handler...` ? There's a very good reason why it takes a bit of time.

**Comment by simenfd** [comment]
No,  this is different I think.  If you start ./geth (under linux, might be same problem on other OSes) and press CTRL-C approx. 0.4 seconds after, it will say "Shutting down" (as in the log above)  but nothing will ever happen, until you break again.

Maybe it is because the CTRL-C is triggered before:
I0517 01:00:58.237607 21915 cmd.go:107] Starting Geth/v0.9.21.1/linux/go1.4.2

**Comment by obscuren** [comment]
Please paste a new log where it fails

**Comment by simenfd** [comment]
./geth
I0519 22:09:15.087591   19378 backend.go:240] Protocol Version: 60, Network Id: 0
I0519 22:09:15.087667   19378 backend.go:250] Blockchain DB Version: 2
I0519 22:09:15.089292   19378 chain_manager.go:247] Last block (#387711) f8e932437465f88ca92d1dc061a8db8d36f8f5e4d757f70abcbf96515fff1e2a TD=300695634371879
BREAK HERE
^CI0519 22:09:15.591618   19378 cmd.go:56] Shutting down (interrupt) ... 
I0519 22:09:16.128784   19378 cmd.go:137] Starting Geth/v0.9.22/linux/go1.4.2
I0519 22:09:16.128919   19378 server.go:209] Starting Server
I0519 22:09:16.135869   19378 nat.go:95] mapped network port udp:30303 -> 30303 (ethereum discovery) using NAT-PMP(10.0.0.1)
I0519 22:09:16.208060   19378 udp.go:189] Listening, enode://87789dca8fcbaadedc5c1e8e8c451cf7368d2390ed8ebf210cbf360a31660c70656cdc05fa4097cc125d54fe7496dfd7c3d123413e939fc09b8281c28566586d@84.209.106.169:30303
I0519 22:09:16.208175   19378 backend.go:458] Server started
I0519 22:09:16.208244   19378 server.go:349] Listening on [::]:30303
I0519 22:09:16.215407   19378 nat.go:95] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(10.0.0.1)
I0519 22:09:26.209628   19378 downloader.go:145] Block synchronisation started
I0519 22:09:28.846784   19378 chain_manager.go:645] imported 40 block(s) (0 queued 0 ignored) in 1.636362015s. #387751 [456be08f / d314fc47]
I0519 22:09:36.723237   19378 chain_manager.go:645] imported 2 block(s) (0 queued 0 ignored) in 13.426326ms. #387753 [4ce1be4d / 2bb41ab4]
I0519 22:09:38.138475   19378 chain_manager.go:645] imported 1 block(s) (0 queued 0 ignored) in 10.058413ms. #387754 [3899b47c / 3899b47c]
AND BREAK HERE
^CI0519 22:09:39.172365   19378 cmd.go:56] Shutting down (interrupt) ... 
I0519 22:09:39.172448   19378 handler.go:121] Stopping ethereum protocol handler...
I0519 22:09:39.172479   19378 handler.go:131] Ethereum protocol handler stopped
I0519 22:09:39.172504   19378 chain_manager.go:503] Chain manager stopped
I0519 22:09:39.172535   19378 transaction_pool.go:271] TX Pool stopped
I0519 22:09:39.172570   19378 backend.go:525] Server stopped
I0519 22:09:39.175781   19378 database.go:125] flushed and closed db: /home/alant/.ethereum/blockchain
I0519 22:09:39.221127   19378 database.go:125] flushed and closed db: /home/alant/.ethereum/state
I0519 22:09:39.221611   19378 database.go:125] flushed and closed db: /home/alant/.ethereum/extra
~/golang/src/github.com/ethereum/go-ethereum/cmd/geth (develop ✘)✭ ᐅ

**Comment by simenfd** [comment]
Small issue of course. But something is wrong with the CTRL-C handling here somehow.

**Comment by obscuren** [comment]
This looks fine, no?

**Comment by simenfd** [comment]
Note that the second CTRL-C is 30 seconds after the first, because it didnt "work".  The program just keeps on running until I break again....

**Comment by obscuren** [comment]
Ah I see now, interesting. Thank you

**Comment by fjl** [comment]
We can prevent some of this by putting a lock around startup. I think it behaves like this because `Ethereum.Stop` runs concurrently with `Ethereum.Start`, so some of the service fields are not assigned yet.

**Comment by fjl** [comment]
This should be solved with #1416 (on develop).
