### ISSUE TITLE
multi-contract sources

### ISSUE THREAD

**Issue by iurimatias** [ethereum/go-ethereum#1023]
> source = "contract Owned{} contract Foo is Owned {}"
> web3.eth.compile.solidity(source)
Error response: multi-contract sources are not supported
Invalid JSON RPC response

**Comment by zelig** [comment]
exactly. as it says. what would you like to see @iurimatias ? :)

**Comment by iurimatias** [comment]
@zelig it's a feature request :) It's part of Solidity, and currently works in AlethZero, so why not in geth as well?

**Comment by obscuren** [comment]
It's your solc compiler that requires an update then :-) please run whatever appropriate update command on your system

**Comment by zelig** [comment]
@obscuren no we need to support this for contract dependencies, I am working on it.
