### ISSUE TITLE
p2p/nat: should delete port mappings before adding

### ISSUE THREAD

**Issue by kobigurk** [ethereum/go-ethereum#1024]
I0517 14:40:26.814284   25614 ssdp.go:63] ssdp: got unexpected search target result "urn:schemas-upnp-org:device:WANConnectionDevice:1"
I0517 14:40:26.814310   25614 ssdp.go:63] ssdp: got unexpected search target result "urn:schemas-upnp-org:device:WANConnectionDevice:1"
I0517 14:40:26.814318   25614 ssdp.go:63] ssdp: got unexpected search target result "urn:schemas-upnp-org:device:WANConnectionDevice:1"

**Comment by fjl** [comment]
These messages are not errors. They tell you that the router provided the wrong service (v1) as the result of an SSDP query for v2. The port should get mapped anyway because we also query for v1. Please check whether it actually maps the port and close the issue if it is working.

**Comment by kobigurk** [comment]
Followed your advice - two entries appear, but act weird - deleted after a few seconds. Other entries (like Skype and qBittorrent) aren't deleted.

**Comment by kobigurk** [comment]
You're right that it also reports success : 
I0518 01:44:31.202810   18647 nat.go:95] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-IP1
I0518 01:44:31.211616   18647 nat.go:95] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-IP1

**Comment by fjl** [comment]
If you have some time, it would be nice to get packet captures for this. So the port mapping shows up but gets deleted shortly after?I have a DD-WRT router somewhere, will test later next week.

**Comment by kobigurk** [comment]
I captured geth trying to upnp and skype trying to upnp so you can compare the difference. Would prefer to send them to you directly, as they might contain personal information.

But, looking at those captures it seems that there is one major difference : geth uses a lifetime of 1200 and Skype of 0. Changing the code in "p2p/nat/natupnp.go" to send lifetime 0 makes the entries persistent, just like skype.

**Comment by fjl** [comment]
Thanks. You can send me the traces in Gitter somehow if you want, ‎but the infoabout expiration time should be enough. Will check upnp specs about using 0.If Skype does it, it's probably OK. My guess is that 0 triggers some kind of device default.

**Comment by kobigurk** [comment]
There's another thing I saw - Skype deletes the port forwarding before adding it again. This can be useful if your internal ip changes.

**Comment by fjl** [comment]
Will add code to delete the mapping before adding.
