### ISSUE TITLE
multiple corsdomain's CLI support

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/go-ethereum#1025]
Would it be possible/safe/difficult to add CLI support for multiple corsdomain's (i.e. "--corsdomain http://site1 http://site2")?

**Comment by zelig** [comment]
I believe this is already possible, could you try using a comma.

```
geth --rpc --rpccorsdomain "http://site1, http://site2"
```

**Comment by tgerring** [comment]
I'm not so sure that multiple domains are currently supported. The underlying CORS library _does_ support multiple domains, so it's just a matter of string splitting and loop.

See https://github.com/ethereum/go-ethereum/blob/443d0248436f653bc2d56653dd52b8abbe408f60/rpc/http.go#L39-L48

**Comment by tgerring** [comment]
Fixed in a2598e649de8b41727084749527aa0bc27965856
