### ISSUE TITLE
"Intrinsic gas too low" error breaks subsequent contract creation transactions.

### ISSUE THREAD

**Issue by simondlr** [ethereum/go-ethereum#1026]
Hey.

For a while been trying to figure out why my geth (v0.9.21.1) has been behaving oddly wrt contract creation. I was able to reproduce the problem. When I get "Intrinsic gas too low" error from the console, contract creation doesn't work anymore.

Here is what happens:

1) I send a transaction with a very large contract. It then returns:

```
Error response: Intrinsic gas too low
Invalid JSON RPC response
    at InvalidResponse (<anonymous>:-49900:-8845)
    at send (<anonymous>:-94858:-8845)
    at sendTransaction (<anonymous>:-87064:-8845)
    at <anonymous>:1:1
```

2) Then, trying to send a much, much smaller contract, it returns the address (implying there were no "gas cost" issues). It does not return the extra information usually found when a transaction is fully pushed to pending.

```
I0517 21:21:37.568305   11470 xeth.go:935] Tx(4555727985a25647eb3a6b9e3fb2f87078105d994bfad74ee00122cde32b6c2a) created: e4b9912df349c3ae1982d105e17fc0122da00fd5
'0xe4b9912df349c3ae1982d105e17fc0122da00fd5'
```

3) Then, checking eth.pendingTransactions(), it shows nothing. The transaction doesn't happen, and does not even get included in the tx pool.

4) Any future contract creation transactions don't work (haven't tried normal transactions (ie sending funds)).

When I turn geth off and back on again, and I skip step 1, and go directly to step 2 (using the smaller contract), it works correctly. I get an address back, and when I then do eth.pendingTransactions(), it is in there. I mine and do a getCode, it works and I can interact with the contract.

So: there seems to be a problem related to something breaking or halting, causing any new contract creation transactions to never actually work (even though the console makes it look like everything is fine). I'm unsure what is causing this, and if it could be related to other errors as well.

**Comment by simondlr** [comment]
https://github.com/ethereum/go-ethereum/issues/870 might be related. @ethers?

**Comment by zelig** [comment]
were you not mining by any chance? was it on the olympic testnet?

**Comment by simondlr** [comment]
@zelig It is a private chain.

Mining was turned off when I submitted the transaction (and turned back on to mine it and include it). I don't think it is relevant though. 

There's no transactions in the tx pool when the contract creation fails. There's nothing in eth.pendingTransactions() and even if you try to mine it afterwards, there's no transactions being processed (because there is none).

**Comment by obscuren** [comment]
The gas you supplied in the transaction is < then the intrinsic gas. Set a higher gas limit perhaps? :)

**Comment by simondlr** [comment]
@obscuren I don't think there's any issue with the gas here. It works fine if you don't ever get the "intrinsic gas too low" error. Something breaks when you do get it, after which any successful contract creation transactions don't end up in the tx pool.

Basically, step 2 doesn't work after a previous "intrinsic gas" error in the console. It works perfectly if you start geth and you set the correct gas parameters, but you did not get the "intrinsic gas" error.

It's an issue with what happens afterwards when you get that error, which breaks any attempts at doing successful contract creations.

**Comment by obscuren** [comment]
Ok, clear. Thanks. Will look in to it

**Comment by obscuren** [comment]
Found bug. Working on fix

**Comment by hqxluoyang** [comment]
this error , help me
Error: intrinsic gas too low
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at web3.js:3021:24
    at <anonymous>:1:12
