### ISSUE TITLE
Import function is no faster than redownloading from network

### ISSUE THREAD

**Issue by stephantual** [ethereum/go-ethereum#1041]
Exported from Eth using -I, imported by Aurel using Geth up to block 320K or so: 2h 51 minutes
Regular download from peers = same time.

Same timings regardless of processor/ram/gpu on Eth or Geth - it's *never faster* to import blocks by using an import file rather than just redownloading the chain. 

Since the purpose of the export/import function is to save time, It would be good to have the loading of the block from an import file made considerably faster.

For example, we could have signed chained exports downloadable as torrents. Bitcoin does this very successfully today, saving almost a day of processing to the end users running the full clients.

**Comment by awrelll** [comment]
I agree on exports downloadable as torrents! Great idea! Can we use Swarm ? :trollface:

**Comment by fjl** [comment]
We have addressed the biggest cause of slow imports in #1022. At this point,
making imports faster is identical to either making block processing faster in general
or disabling most of the block validation for certain (maybe signed imports).

Note that the purpose of the import command is not saving on download time.
You can use it to import a non-canon chain, for example.

**Comment by obscuren** [comment]
@awrelll you don't need torrents. It's not the download that's slow (the downloader actually maxes your bandwidth, it does 6MB/s here in a torrent way). The actual block processing takes time. 

One option would be `geth --skip-validation import <file>` but that's terribly dangerous. 

P.S. Regarding swarm [**done**] => https://twitter.com/jeffehh/status/600305943533002752

**Comment by stephantual** [comment]
Thanks guys - clarifies things.
