### ISSUE TITLE
add eth_getReceipt method to the RPC

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#1042]
We need a way to retrieve receipts. Jeff and i came up with the following solution:

Method: `eth_getReceipt`
Param 1: Tx hash, e.g. `['0x12345..']`
Result: 
```js
{
   transactionHash: '0x432423...',
   transactionIndex:  '0x1', // 1
   blockNumber: '0xb', // 11
   blockHash: ‘0x34243653...’,
   cumulativeGasUsed: '0x33bc', // 13244
   gasUsed: '0x4dc', // 1244
   contractAddress: '0x12345678765432567898765432' // or null, if none was created
   logs: [{
       // logs as returned by getFilterLogs, etc.
   }, ...]
}
```

Internally we have to calculate the `gasUsed` through subtracting the previous `cumulativeGasUsed` with the one of the current receipt, e.g. `receipts[1].cumulativeGasUsed - receipts[0].cumulativeGasUsed`

**Comment by obscuren** [comment]
During block processing we need to keep track of additional information:

* gas usage (`receipt[i-1].cumulativeGasUsed - receipt[i].cumulativeGasUsed`)
* block hash
* tx hash
* tx index
* block num

This requires:

1. storing receipts as `[]*receipt` with `receipts-H(block)` as key
2. storing individual `*receipt` with receipt-H(tx)` as key but **only** for the canonical block chain (i.e. when `chainManager.insert` is called.

**Comment by zsfelfoldi** [comment]
https://github.com/ethereum/go-ethereum/pull/1049

**Comment by frozeman** [comment]
@zsfelfoldi is this already implemented according to the specs above?

@obscuren people would love to have the created contract address in here too, as at this point it should be clear.

**Comment by tgerring** [comment]
@frozeman Can you add this method to the JSON RPC wiki?

**Comment by frozeman** [comment]
I would do this after its implemented and tested.

**Comment by tgerring** [comment]
Linked PR current status:

```$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x875912c3a928059bf81416e6358a604f13bb5f6c59d5374348a38e09bb2e397a"],"id":1}' http://127.0.0.1:8545
{
	"id": 1,
	"jsonrpc": "2.0",
	"result": {
		"TransactionHash": "0x875912c3a928059bf81416e6358a604f13bb5f6c59d5374348a38e09bb2e397a",
		"TransactionIndex": "0x0",
		"BlockNumber": "0xa",
		"BlockHash": "0x2889bd97678178467634c8391358a1a7967f48e3b056904cf2ecbf1c43e77dd7",
		"CumulativeGasUsed": "0x5208",
		"GasUsed": "0x15f90",
		"ContractAddress": "0x0000000000000000000000000000000000000000",
		"Logs": null
	}
}
```

**Comment by frozeman** [comment]
I think logs should always be an array (so even an empty array), so that it is the same behaviour as `getBlock`

**Comment by frozeman** [comment]
But looks good so far :+1:

**Comment by nmushegian** [comment]
Are event filters not going to work for frontier launch??

**Comment by frozeman** [comment]
That is fixed and should be closed. And Event filters work since a very long while already ;)
