### ISSUE TITLE
Support for unlocking multiple addresses at startup

### ISSUE THREAD

**Issue by danielnovy** [ethereum/go-ethereum#1045]
Maybe this feature already exists but if it does, it's not clear in the docs or in the command line options. In the real world scenario, I should be able to send transaction from any of my addresses without having to restart the client providing a different address for the "--unlock" option.

**Comment by tgerring** [comment]
https://github.com/ethereum/go-ethereum/blob/46d6470c435735d839d695da31a0823176790efe/cmd/geth/main.go#L364-L378 and https://github.com/ethereum/go-ethereum/blob/46d6470c435735d839d695da31a0823176790efe/cmd/geth/main.go#L386-L396 needs changed to support this.

Perhaps a space-separated list that is exploded and looped through?

**Comment by danielnovy** [comment]
Yes, this should be enough. All the addresses will need to have the same password though.

**Comment by tgerring** [comment]
In unlockAcocunt there's a call to getPassPhrase that actually prompts for the accounts, so you should be able to have different passwords. The ordering will be important though, since otherwise you don't know what account is being unlocked. Maybe it'd be extra clear if we modify line 368 to include the account address in the prompt.

**Comment by tgerring** [comment]
@danielnovy If you want to pull https://github.com/tgerring/go-ethereum/tree/issue1045 and test locally, I'd welcome your feedback. Sample output is below:

```
$ geth --unlock "primary 0xda65665fc30803cb1fb7e6d86691e20b1826dee0" console 
Unlocking account 0xd1ade25ccd3d550a7eb532ac759cac7be09c2719
Passphrase: 
Account '0xd1ade25ccd3d550a7eb532ac759cac7be09c2719' unlocked.
Unlocking account 0xda65665fc30803cb1fb7e6d86691e20b1826dee0
Passphrase: 
Account '0xda65665fc30803cb1fb7e6d86691e20b1826dee0' unlocked.
>
```

**Comment by danielnovy** [comment]
Thanks for your quick feedback, Taylor! I will give it a try and let you know.

**Comment by danielnovy** [comment]
Taylor, worked like a charm! I tested it with both using and not using the "--password" command line option. Thanks again!

**Comment by zelig** [comment]
Hmm I didn't have a chance to review this. 
I think this feature "All the addresses will need to have the same password though. " just wont cut it.
Quite reluctant about this change.

**Comment by danielnovy** [comment]
This demand only exists if we supply the "--password" command line option. As @tgerring pointed out, you could still start the geth in interactive mode and enter different passwords for different addresses. 

Anyway, if we think of the addresses as belonging to a unique account, it does make sense to have the same password for all its addresses. Actually, in a ideal world, we should be able to have as many accounts as we want and each account with as many addresses as we want, each account having just one password for all its addresses, imho.

**Comment by zelig** [comment]
maybe it should but its not how it is now: account = address

**Comment by tgerring** [comment]
@zelig I agree things could be improved, but the associated PR adds 2 things that were not possible before (even if inconsistent when used with some other subset of parameters):

* Multiple account unlock (previously only a single account could be unlocked via CLI)
* Multiple unlock attempts (previously, a single incorrect password would quit fatally)

Both of these are Good Things(tm) even if the `--password` input could be more flexible/efficient
