### ISSUE TITLE
Suggestion: log entry for mined block that is n deep

### ISSUE THREAD

**Issue by carver** [ethereum/go-ethereum#1047]
The issue I'm trying to address is: when running ethminer unattended, it's hard to identify how many blocks are mined through the logs.  There are so many uncles that the "Mined block" line is not a useful signal.  (I'm seeing north of 80% stranded blocks)

My proposed solution is: a log event that conveys: "One of the blocks mined through this geth instance is now 5 blocks deep in the network." (or whatever number seems very likely to stick)

I'm happy to work on a pull request, if a maintainer thinks this could get merged.

**Comment by obscuren** [comment]
Sounds good to me. The miner does now give you an a message whether the block you mined is stale or not https://github.com/ethereum/go-ethereum/blob/develop/miner/worker.go#L230 feel free to add block level deepness

**Comment by carver** [comment]
Cool, thanks for the starting point.  I'll work on it. (slowly, since I'm new to both go and this repo...)

**Comment by carver** [comment]
This feature seems to be working smoothly
