### ISSUE TITLE
`os.Mkdir` called on `Datadir` default regardless of `datadir` config file setting.

### ISSUE THREAD

**Issue by nejucomo** [ethereum/go-ethereum#105]
I found that mkdir was being called on ``~/.ethereum`` even when I specified a nondefault config file ``-conf=/some/other/path.ini`` and that config file has ``datadir = /some/other/datadir``.

Looking at the code I see that ``utils.InitConfig`` calls ``utils.InitDataDir``, in [cmd.go line 106](https://github.com/ethereum/go-ethereum/blob/develop/utils/cmd.go#L106), and this seems like a bug because this will contain the default value.

Later ``main`` calls ``utils.InitDataDir`` directly, in [ethereum.main.go line 34](https://github.com/ethereum/go-ethereum/blob/develop/ethereum/main.go#L34), with the correct value from the config file.

I intend to write a unittest to capture this bug, but I'm new to go and haven't figured out the best way to mock out ``os.Mkdir`` or to create a temporary file system directory for non-mock testing.

**Comment by tgerring** [comment]
Reference #368

**Comment by zelig** [comment]
outdated. new cli works different. see #567 #639
