### ISSUE TITLE
one node has higher total difficulty than all other nodes

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1057]
On stats.ethdev.com Marian's MacBook (84.117.82.122)  total difficulty is always slightly higher than everyone else's.  (Pin it to top by clicking on the left of it, then sort by TD column.)

https://gist.github.com/cubedro/b4d251ede582bb121c57

It doesn't look like a simple issue directly attributed to Macs since "Go Zen Node 2" is also Mac and TD is same as everyone else.  Some library difference?

Note: if this was a discrepancy with some other value, I'd have ignored it, but total difficulty is an integral part of _the_ blockchain.

**Comment by tgerring** [comment]
This isn't really the best place for this issue, since it's not a problem specific to Geth. Pinging @cubedro

**Comment by cubedro** [comment]
Well, where should we place this issue? We had also posted in the channels but didn't get a reply

**Comment by obscuren** [comment]
@cubedro how long did you have this geth chain?

**Comment by cubedro** [comment]
since ~ block 20000, don't remember the previous geth version. I updated geth to 0.9.22, ran it, it reindexed the blockchain, downloaded the blockchain past block 374395 (cause osx cpp eth wouldn't go over this block).

**Comment by obscuren** [comment]
Right. Old chains had this problem once upon a time. This problem is that it can't be corrected unless you re download / catch up again.

**Comment by ethers** [comment]
wondering if this old node starts mining a block successfully, will it cause a chain reorg since it's TD is higher than everyone else's?

example: currentMiner vs oldNode
currentMiner mines block N.  1 second later, oldNode also mines block N.  oldNode gets the reward and causes a chain reorg.

if the main chain is at block B, whenever oldNode finds block B+1 before block B+2 is out, oldNode will always get the reward?  miners have to find B+1 and B+2 to overcome oldNode?

**Comment by ethers** [comment]
or this is a non-issue, because the "totalDifficulty" is local only to oldNode?  is it like oldNode's TD was initialized to 100, whereas everyone else's was initialized to 0 ?

since everyone will add blocks with difficulty d1+d2+d3, everyone's TD is d1+d2+d3; oldNode's TD is d1+d2+d3+100 but no other nodes care about it.

**Comment by obscuren** [comment]
No. Nodes determine the block's TD themselves.

**Comment by ethers** [comment]
Thanks for clarifying; I don't there is any issue at this stage since it's an old node/chain and will close.
