### ISSUE TITLE
Filter returning null

### ISSUE THREAD

**Issue by iamsmartcontractor** [ethereum/go-ethereum#1058]
This is the code i am using :

web3.eth.filter({'fromBlock': "350000",'toBlock':"365700","address" : "0xf70ad082288b3ea5bba602d5dc9d82a715b42e66" , "topics":[null]}).get(function(res) {console.log(res)});

it returns no values no while it should return one transaction.

**Comment by guykileveryone** [comment]
Have you called eth_getFilterChanges(filter_id) ?

**Comment by iamsmartcontractor** [comment]
I am using the web3 API, isn't the eth_getFilterChanges specific to JSON-RPC ?

**Comment by obscuren** [comment]
@iamsmartcontractor never mind he `eth_getFilterChanges`. That's polled for in the background. So a few things:

`0x350000` = `3.473.408`
`0x365700 ` `3.561.216`

As of this writing the current block number range is `400.000`. You're using a range that doesn't exist. Are you sure you didn't just mean `350000`?

**Comment by iamsmartcontractor** [comment]
Ok, then, i need to express the numbers in hexadecimal, correct ? 

I did this tests by the way : 

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_newFilter","params":[{"topics":[],"address":"0xf70ad082288b3ea5bba602d5dc9d82a715b42e66","fromBlock":"0x0","toBlock":"latest"}],"id":4}'  

and i get this response : 

{
	"id": 4,
	"jsonrpc": "2.0",
	"result": "0x8"
}

then i query the filter this way : 

 curl -X POST --data '{"jsonrpc":"2.0","method":"ethgetFilterLogs","params":["0x8"],"id":3}'

and it returns the following while there is a tx at block 352243


{
	"id": 3,
	"jsonrpc": "2.0",
	"result": []
}

**Comment by obscuren** [comment]
it's `eth_getFilterLogs` you forgot an underscore.

**Comment by iamsmartcontractor** [comment]
No, i just forgot to add it here. 
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["0x8"],"id":3}'  
{
	"id": 3,
	"jsonrpc": "2.0",
	"result": []
}

**Comment by iamsmartcontractor** [comment]
Can somebody kindly try this and let me know ? Thanks

**Comment by mtbitcoin** [comment]
May I know what was your workaround ? I am also running into similar issues occasionally with empty logs returned

**Comment by gregbkr** [comment]
Hello, I am getting the same issue on geth135, is there any resolution? Thanks!
    
    curl -X POST --data '{"jsonrpc":"2.0","method":"eth_newFilter","params":[{"topics":[],"address":"0xe5bccf6ee7f37e307347aeb1fc211bbac21de250","fromBlock":"0x0","toB lock":"latest"}],"id":4}' http://127.0.0.1:8545
    curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["0x4"],"id":3}' http://127.0.0.1:8545
    {"id":3,"jsonrpc":"2.0","result":[]}
