### ISSUE TITLE
StateTests/stRecursiveCreate.json TestStateRecursiveCreate panics in core/execution.go

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#1060]
**NOTE: this file passes in go-ethereum develop, but not when using StateTests/stRecursiveCreate.json from latest ethereum/tests develop branch.** 

@CJentzsch added TestStateRecursiveCreate in the file recently

When running TestStateRecursiveCreate we get
```
panic: runtime error: invalid memory address or nil pointer dereference
github.com/ethereum/go-ethereum/core/execution.go:41
```
(full stack trace below)

The odd thing is that it looks like the address is always nil when that function is called, so I don't understand how it was working before.

This test works back at tag v0.8.5-2 so I did a git bisect which tells us:

```
The first bad commit could be any of:
1c872ddf4b1db51847a5d9d020e13d432e847f52
f08e9cbe42dcb067affe0ca1077285ba1b583c95
a7750c929b926d164195fd4f7a7e2b4642c66173
```

It gives those 3 because I had to skip a few due to non-compiling tests, verifying manually gives that the last commit where this test passes is https://github.com/ethereum/go-ethereum/commit/6284604b52e075e454e61f2933cadaaf9ded364b

and the first failing one is https://github.com/ethereum/go-ethereum/commit/a7750c929b926d164195fd4f7a7e2b4642c66173

@obscuren Do you know what went wrong there?

Stack trace: (it keeps looping the same function, so the rest of the trace repeats)
```
> time godep go test -v -run TestStateRecursiveCreate
=== RUN TestStateRecursiveCreate
--- FAIL: TestStateRecursiveCreate (7.66s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5fa09c]

goroutine 9 [running]:
testing.func·006()
	/home/gs/golang/src/testing/testing.go:441 +0x181
github.com/ethereum/go-ethereum/core.(*Execution).Create(0xc22dca4720, 0x7fb84b93bbc0, 0xc232061e80, 0x0, 0x0, 0x0, 0x7fb848528000, 0xe0cb80, 0xc22dca4720)
	/home/gs/go/src/github.com/ethereum/go-ethereum/core/execution.go:41 +0x16c
github.com/ethereum/go-ethereum/tests/helper.(*Env).Create(0xc2080881b0, 0x7fb84b93bbc0, 0xc232061e80, 0xc23206b740, 0x20, 0x20, 0xc23206b760, 0xc23206a560, 0xc23206b5a0, 0x0, ...)
	/home/gs/go/src/github.com/ethereum/go-ethereum/tests/helper/vm.go:132 +0x2dc
github.com/ethereum/go-ethereum/core/vm.(*Vm).Run(0xc231ccf800, 0xc232061e80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/gs/go/src/github.com/ethereum/go-ethereum/core/vm/vm.go:638 +0xe11b
github.com/ethereum/go-ethereum/core.(*Execution).exec(0xc22dca46c0, 0x0, 0xc231cd7a60, 0x20, 0x20, 0x7fb84b93bbc0, 0xc231ccf780, 0x0, 0x0, 0x0, ...)
	/home/gs/go/src/github.com/ethereum/go-ethereum/core/execution.go:92 +0xa6d
github.com/ethereum/go-ethereum/core.(*Execution).Create(0xc22dca46c0, 0x7fb84b93bbc0, 0xc231ccf780, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc22dca46c0)
	/home/gs/go/src/github.com/ethereum/go-ethereum/core/execution.go:40 +0xe5
github.com/ethereum/go-ethereum/tests/helper.(*Env).Create(0xc2080881b0, 0x7fb84b93bbc0, 0xc231ccf780, 0xc231cd7a60, 0x20, 0x20, 0xc231cd7a80, 0xc231cd6880, 0xc231cd78c0, 0x0, ...)
	/home/gs/go/src/github.com/ethereum/go-ethereum/tests/helper/vm.go:132 +0x2dc
github.com/ethereum/go-ethereum/core/vm.(*Vm).Run(0xc231931300, 0xc231ccf780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
```

**Comment by obscuren** [comment]
Assuming this is a create (since it ends up in create) this is the path:

* https://github.com/ethereum/go-ethereum/blob/develop/tests/helper/vm.go#L123 pass `nil` as addr
* https://github.com/ethereum/go-ethereum/blob/develop/tests/helper/vm.go#L92 which passes `nil` as addr to the vm creation. so `execution.address == nil`
This means that when `exec` is called (which happens in `execution.Create`):
* https://github.com/ethereum/go-ethereum/blob/develop/core/execution.go#L58
* which sets `execution.address` to https://github.com/ethereum/go-ethereum/blob/develop/core/execution.go#L65
* which should, after it returned, work in the case of https://github.com/ethereum/go-ethereum/blob/develop/core/execution.go#L41

**Comment by CJentzsch** [comment]
This is the code which gets called: https://github.com/ethereum/cpp-ethereum/blob/develop/test/libethereum/StateTestsFiller/stRecursiveCreateFiller.json#L49

So basically it is a recursive loop, executin CREATE in the init code. And in thei init code we again have a CREATE .... . It should fail after it reaches the 1024 call/create stack limit depth, and just return 0.

**Comment by obscuren** [comment]
I see the bug

**Comment by CJentzsch** [comment]
Interestingly, you did pass the other test in this file, which did the same thing, except of not storing the return value.
