### ISSUE TITLE
request: geth option to mine only when transactions come in

### ISSUE THREAD

**Issue by iurimatias** [ethereum/go-ethereum#1061]
when using geth locally for development purpose the cpu goes off, it would be useful to have an option to tell geth to only mine a block if there pending transactions.

**Comment by karalabe** [comment]
I'm not sure it's worth the complexity. We're already having problems with a feature that people requested where the miner should suspend when the node is syncing and resume afterwards. Tracking transactions too would further complicate the possible scenarios that the miner needs to take into account. But maybe somebody else should weigh in on this. @obscuren ?

**Comment by iurimatias** [comment]
@karalabe you can close this if you wish. I'll take Viktor's suggestion to do a script for this instead.

**Comment by obscuren** [comment]
I'll leave this open. If some kind soul feels like implementing this feel free.

**Comment by zelig** [comment]
@iurimatias may I kindly ask you to publish your solution once you got it working? I'd like to include it in the wiki. Thanks

**Comment by maran** [comment]
Might I suggest a specific label something like `help-needed` or something similar that tags which issues are not a priority for the devs but that are good candidates for willing developers willing to contribute. It makes it easier to them to find possible features to work on.

**Comment by iurimatias** [comment]
@zelig Here is the [solution](https://github.com/iurimatias/embark-framework/blob/master/js/mine.js) I'm using in embark. Unfortunately none of the filters/watchers work if the miner is off (which makes sense), so I end up using a timer.

**Comment by zelig** [comment]
thanks @iurimatias 
we may add a feature helping mining txs on test setup in future
closing this for now

**Comment by mawenpeng** [comment]
@obscuren 
Hi Jeffrey, do you have any example code to implement this?
I tried, but failed. It's stuck there even I sent a transaction in geth console.
Thanks.

**Comment by mawenpeng** [comment]
I meant I changed geth code and compiled myself.

**Comment by princesinha19** [comment]
@zelig Is there is any feature like auto mine when the transaction comes in or if there is a pending transaction?

**Comment by karalabe** [comment]
@princesinha19 If you use `-dev` mode, it works. Auto-mining doesn't make sense in a real network, there are propagation assumptions that assume blocks are arriving at regular intervals.
