### ISSUE TITLE
miner: starting after boot seems to not notify of sync completion

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#1065]
Here's the log as reported by @cjphilpot https://gist.github.com/cjphilpot/4b99f1e6e71d23d32b16

**Comment by cjphilpot** [comment]
Started mine at command line (geth --vmodule=sync=6,downloader=6 --mine console). Same problem.

https://gist.github.com/cjphilpot/84d133d1877fa6e950dc

**Comment by karalabe** [comment]
@cjphilpot Could you verify with latest dev? It seems there was a bug that broke the miner.

**Comment by karalabe** [comment]
I can verify that the old develop indeed contained this bug (reproduced locally) and that the mentioned miner fix indeed resolved it. Closing.
