### ISSUE TITLE
console sometimes not showing results/output

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#1079]
I've seen this multiple times over the last week or so, that I type some command into the console, but rarely no output is displayed. These can be anything really, the two I usually type often are `net` and `web3.fromWei(eth.getBalance(eth.coinbase))`. Usually they work properly, sometime they simply don't output anything. I'm guessing this is some data race. It would be nice to sort out as it's annoying after a while.

**Comment by zelig** [comment]
this is interesting, I am using the console like 24/7 and NEVER encountered this issue. hmm.
Is there any suspicious context for this bug? Like for instance you are running a filter watch or setTimeout or setInterval?

**Comment by karalabe** [comment]
I'll close this for now in the hopes that the referenced PR indeed fixed it. If I notice it again, I'll reopen.
