### ISSUE TITLE
panic on addPeer() if client started with --maxpeers 0

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#1087]
We should be able to start the p2p server with 0 dynamic peers and add static or forced peers. 
But at the moment maxpeers 0 has the effect that the p2p server is not started and therefore adding a peer on the console or script will result in a panic on a non-initialised map.
p2p.Server.AddPeer should check if map is nil or Start the server. 
Maybe a nicer solution is to have an explicit cli option to disable the network and keep maxpeers=0 with its intended semantics: zero dynamic peers.

```
geth --maxpeers 0 js <(echo "admin.addPeer('enode://89d7a76cb0d1b48f51d5e809c267ea9d6657438ad8710386375c7e235f72ccd955410896a21826059ad8cc818d728bbaf51d1802178adcda859afaf5e649f731@92.234.60.25:30301')")
...
panic: assignment to entry in nil map [recovered]
        panic: assignment to entry in nil map
goroutine 110 [running]:
github.com/robertkrimen/otto.func·024()
        /Users/tron/Work/ethereum/go-ethereum/Godeps/_workspace/src/github.com/robertkrimen/otto/error.go:240 +0x5c7
github.com/ethereum/go-ethereum/p2p.(*Server).AddPeer(0xc2080f4000, 0xc20a1cee00)
        /Users/tron/Work/ethereum/go/src/github.com/ethereum/go-ethereum/p2p/server.go:159 +0xb5
github.com/ethereum/go-ethereum/eth.(*Ethereum).AddPeer(0xc208214580, 0xc20a136dcf, 0x9b, 0x0, 0x0)
        /Users/tron/Work/ethereum/go/src/github.com/ethereum/go-ethereum/eth/backend.go:563 +0x16e
main.(*jsre).addPeer(0xc208ab1e60, 0xc2080da840, 0x0, 0x0, 0x5, 0x489d140, 0xc209f74a80, 0xc20a16dde0, 0x1, 0x1, ...)
        /Users/tron/Work/ethereum/go/src/github.com/ethereum/go-ethereum/cmd/geth/admin.go:416 +0x27d
main.*jsre.(main.addPeer)·fm(0xc2080da840, 0x0, 0x0, 0x5, 0x489d140, 0xc209f74a80, 0xc20a16dde0, 0x1, 0x1, 0xc208b76df0, ...)
...
```

**Comment by karalabe** [comment]
There is a big PR coming in with dialler fixes that will most definitely affect maxpeers too. I don't know if this issue is still present in that new code, but I'll try to check it.

**Comment by fjl** [comment]
This has not been addressed. AddPeer will hang indefinitely in the new code because it'll block on two nil channels. We'll fix this after the big PR.

**Comment by zelig** [comment]
@fjl can we please have
* forced peers (non-dynamic, connects irrespective of maxpeers, but non-static = not retried)
* option to switch off discovery (will this happen with `--bootnodes=""` 
* maxpeers=0 should be allowed = 0 dynamic peers this could also mean no discovery
* option to switch off p2p/networking entirely

**Comment by karalabe** [comment]
@zelig 

 * What is your use case for *forced* peers?
 * This will be done, but probably a separate flag. Disabling needs to be done at 3 different conceptual places, the bootnodes are only one. Using the bootnodes flag for this would be very very ambiguous. We'll have this in after the dialer PR.
 * maxpeer == 0 panic is a bug. It will be fixed.
 * Why do you want to switch of p2p?

**Comment by zelig** [comment]
* bzz
* agreed (I just thought i saw it mentioned by @fjl somewhere very recently that you want `--bootnodes=""` to mean this, I cannot find this now)s
* the panic should be fixed but in a way that allows 0 maxpeers (if i allow 0 in eth/backend and still start p2p.server, p2p still stops with a fatal error, so it needs to be allowed there too.
* for testing

**Comment by karalabe** [comment]
Please see PR #1108:

 * Static peers and `addPeer` could cover this for now. Is there a particular reason you would like to omit reconnects?
 * Fixed, `--nodiscover`
 * Fixed, server is always started, so you shouldn't hit uninited state.
 * `--nodiscover`, `--maxpeers=0` and no static peers should get you on your own isolated island.

**Comment by karalabe** [comment]
I'll close this issue as the core problem has been resolved and merged by the previously mentioned PR. But if you, @zelig, feel than the mechanics are not enough for the bzz use case, we can come up with a solution to it a more focused thread/issue :)
