### ISSUE TITLE
Not finding Qt5WebEngine in pkg-config path

### ISSUE THREAD

**Issue by tritonresearch** [ethereum/go-ethereum#1088]
Hi,

I am getting the following error upon installing with brew:

$ brew install ethereum --with-gui
==> Installing ethereum from ethereum/homebrew-ethereum
==> Cloning https://github.com/ethereum/go-ethereum.git
Updating /Library/Caches/Homebrew/ethereum--git
==> Checking out branch master
==> go env
==> go build -v ./src/github.com/ethereum/go-ethereum/cmd/geth
==> go build -v ./src/github.com/ethereum/go-ethereum/cmd/mist
Package Qt5WebEngine was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5WebEngine.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5WebEngine' found
exit status 1

Any ideas how to install this package?

**Comment by fjl** [comment]
Maybe try reinstalling qt5, `brew reinstall qt5`.

**Comment by karalabe** [comment]
Closing as Mist was removed form the repository and hence all Qt (deprecated anyway).
