### ISSUE TITLE
Add support for --eth=false

### ISSUE THREAD

**Issue by d11e9** [ethereum/go-ethereum#1095]
Is it possible to run a node using geth that that does not download (or try to download) the blockchain, and only interacts with the network via `shh`? I'd thought to run a node like so:

```
geth --shh --vmodule=sync=0,downloader=0 js my_shh_application.js
```

... but this still downloads the chain, and incidentally I was unable to receive messages posted by the node in this state (perhaps blocknumber too old or stale?) any thoughts or ideas?

@tgerring suggested the following:

> maybe delete your chain and use `--networkid`

Is there a suggested or best practice for selecting networkid numbers. ie how large can they be, my first thought being a hashed topic as an id, but this doesn't help if there's no convention to prevent (mitigate) network overlaps, that is if Ethereum encourages new networkid for things other than testing.

That being said I believe it is a valid workaround, but would like to have these nodes participate in the **main-net**. I understand that they would not be processing the chain but they would still be contributing to and benifiting from using the larger more robust the **main-net** whisper network.
- Is it possible to run `ssh` only nodes?
- What are the Ethereum devs thoughts on `networkid` conventions?

**Comment by fjl** [comment]
Shh only is not possible at the moment. We don't support this mode of operation officially and it won't work ‎because most (if not all) peer connections will disconnect immediately because of a network id mismatch.                                                                                                                                                                                                                                                                                                                                                                                      ‎

**Comment by d11e9** [comment]
@fjl I understand they would disconnect if they're running on a different networkid - it logical. What are your thoughts on networkid conventions?

**Comment by zelig** [comment]
wonder we should not support this. If people really wanted, they will support it anyway.
All we need to do is to not start the eth protocol, basically add the `--eth=false` option to the CLI.
What are your concerns about this?

**Comment by karalabe** [comment]
@zelig I don't think @fjl was referring to issues with not starting `eth`, but rather that Whisper is although functional it is currently disabled by default so you'll be pretty much out of luck trying to assemble a network and find another lost soul running `shh`.

**Comment by d11e9** [comment]
@karalabe That would be understandable, that there would be _less_ nodes to connect to but it would be infinitely better than running said nodes on their own networkid, and being totally isolated.

:+1: for `--eth=false`

**Comment by jarradh** [comment]
We've added a --noeth https://github.com/status-im/go-ethereum/commit/fb80a04848592c1b26d0dbcc3b189e6f6e1ac92a
