### ISSUE TITLE
Wrong debug output in vm for SUB opcode

### ISSUE THREAD

**Issue by ralph-pichler** [ethereum/go-ethereum#1096]
Using -vmdebug, the sub opcode currently yields output like:
(pc) 844 -o- SUB            (m) 160  (s) 23   (g) 3   (37127) 34050 - 37127 = 3077

self.Printf(" %v - %v", y, x) in vm.go:145 should be replaced by self.Printf(" %v - %v", x, y)

**Comment by obscuren** [comment]
hehe thanks :)
