### ISSUE TITLE
No way to see actual gas usage of transaction

### ISSUE THREAD

**Issue by TalkingAntColony** [ethereum/go-ethereum#1097]
There is currently no way to see how much gas was used by a transaction. eth.getTransaction().gas only returns the gas sent by the sender, not how much was used/refunded. The only way I can think to see gas usage is to carefully monitor account balances before and after a transaction, but this gets hairy when there are many/simultaneous transactions. 

This is an integral feature for dapp owners to determine historical costs. I propose two new and one modified parameter to the transaction object:

gas --> gasSent
gasUsed
gasRefunded

I'm not sure how to implement this, but I think it would involve having miners log gas usage for each transaction after state transition. This would increase the size of the blockchain, so maybe only one of the new parameters can be included, since they can be calculated from each other.

**Comment by obscuren** [comment]
There'll be a `eth_getReceipt` which will output gas used

**Comment by obscuren** [comment]
`eth_getReceipt` has been implemented a while ago.
