### ISSUE TITLE
Synchronisation failed: block downloading cancelled

### ISSUE THREAD

**Issue by avdoshyn** [ethereum/go-ethereum#1104]
I0526 14:39:40.435886    7272 server.go:349] Listening on [::]:30303
I0526 14:39:40.436886    7272 nat.go:95] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-PPP1
> I0526 14:39:50.437458    7272 downloader.go:159] Block synchronisation started
I0526 14:39:55.463745    7272 chain_manager.go:743] INVALID block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0526 14:39:55.463745    7272 chain_manager.go:744] gas used error (44532 / 160116)
I0526 14:39:55.463745    7272 sync.go:73] Block insertion failed: gas used error (44532 / 160116)
I0526 14:39:55.463745    7272 sync.go:122] Synchronisation failed: block downloading cancelled (requested)
I0526 14:40:06.491376    7272 chain_manager.go:743] INVALID block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0526 14:40:06.491376    7272 chain_manager.go:744] gas used error (44532 / 160116)
I0526 14:40:06.491376    7272 sync.go:73] Block insertion failed: gas used error (44532 / 160116)
I0526 14:40:06.491376    7272 sync.go:122] Synchronisation failed: block downloading cancelled (requested)
I0526 14:40:12.957746    7272 chain_manager.go:743] INVALID block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0526 14:40:12.962746    7272 chain_manager.go:744] gas used error (44532 / 160116)
I0526 14:40:12.962746    7272 sync.go:73] Block insertion failed: gas used error (44532 / 160116)
I0526 14:40:12.970746    7272 sync.go:122] Synchronisation failed: block downloading cancelled (requested)
I0526 14:40:29.082668    7272 chain_manager.go:743] INVALID block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0526 14:40:29.083668    7272 chain_manager.go:744] gas used error (44532 / 160116)
I0526 14:40:29.084668    7272 sync.go:73] Block insertion failed: gas used error (44532 / 160116)
I0526 14:40:29.086668    7272 sync.go:122] Synchronisation failed: block downloading cancelled (requested)
I0526 14:40:41.465376    7272 chain_manager.go:743] INVALID block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0526 14:40:41.466376    7272 chain_manager.go:744] gas used error (44532 / 160116)
I0526 14:40:41.498378    7272 sync.go:73] Block insertion failed: gas used error (44532 / 160116)
I0526 14:40:41.517379    7272 sync.go:122] Synchronisation failed: block downloading cancelled (requested)

**Comment by karalabe** [comment]
There was a fork in the network, it's being patched up and a new release pushed today that fixes the issues. If you pull the current develop then it will eventually switch over to the valid chain.

PS: The errors will still remain as long as the invalid chain is phased out as there will be stale peers who try to feed you the invalidated chain.

**Comment by karalabe** [comment]
PPS: The current valid head is at 446891.

**Comment by karalabe** [comment]
Please see https://www.reddit.com/r/ethereum/comments/37bnbv/important_fork_update/
