### ISSUE TITLE
upgradedb on 8951a03db hangs, exiting out of it produces 'bad peer'

### ISSUE THREAD

**Issue by stephantual** [ethereum/go-ethereum#1125]
8951a03db39a2a877ada34c927d78352d465303e 

OSX & nix

Try to restart geth post fork, geth ask to upgradedb

Run upgradedb - in both platforms it imports all blocks by chunks of 2500, displays 'imported 444xxx blocks' (sorry can't remember exact num) and hangs the platform, completely (mouse frozen, etc, both nix and osx), - waited 2 hours just in case but nothing happened. 

Reboot machine, restart geth, getting messages on osx about peer not being registered and on nix about being a 'bad peer'. 

Solution: wipe ./ethereum, reimport everything.

**Comment by karalabe** [comment]
There are some known memory issues that should be fixed today, which may or may not be related.

@fjl Did you also experience this hang? You mentioned something on Skype?

**Comment by Ulysseus** [comment]
Getting same thing imports 446188 blocks and then hangs....

**Comment by cjphilpot** [comment]
I have the same exact thing. Now I am getting the continuous "bad peer" message. I will hold off for tonight's fixes before I do a wipe.

**Comment by obscuren** [comment]
I'm happy to report that https://github.com/ethereum/go-ethereum/pull/1129 solves a lot of memory issues. During import it keeps the memory steady on about 200-220mb instead of 1gb previously.

**Comment by fjl** [comment]
Is anyone still experiencing these issues?

**Comment by cjphilpot** [comment]
After 0.26 came out I had to reset my wireless router (ASUS RT-68U) in order to sync to ethereum. I have had a continuous sync since then. 0.26 has been the best release by far at maintaining network connectivity. Very impressive work!
