### ISSUE TITLE
eth.contract does not appear to work as claimed (or at all?)

### ISSUE THREAD

**Issue by Smithgift** [ethereum/go-ethereum#1126]
A JS API contract object created by eth.contract does not have the .at() method, and using this object as the function it says it is makes it attempt to send a transaction with undefined data.

**Comment by tgerring** [comment]
What version of Geth are you running?

From the console, `admin.nodeInfo().Name` or from CLI `geth version`

**Comment by Smithgift** [comment]
geth version outputs the following:
```
Geth
Version: 0.9.21.1
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2
OS: linux
GOPATH=
GOROOT=/usr/lib/go
```

This is the latest Ubuntu binary from ethereum-dev, by the way.

**Comment by maran** [comment]
This is a very old version (in Ethereum land at least). You can grab a [new release here](https://github.com/ethereum/go-ethereum/releases).

**Comment by Smithgift** [comment]
It appears something had gone wonky with apt-get and I was on the wrong version. Many thanks. Closing for now.
