### ISSUE TITLE
eth_getCode seems broken

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#1131]
`eth_getCode` always returns `0x`, even if there is code at an address. I also got that reported from konstantin.

I can't run the rpc tests because of https://github.com/ethereum/go-ethereum/issues/1130, otherwise i could verify that its really the case.

```
{"jsonrpc":"2.0","method":"eth_getCode","params":["0x1cd9f24705efb8323a18d1931aab5cc16a39d678","latest"],"id":28015}
```

Result:
```
{
	"id": 28015,
	"jsonrpc": "2.0",
	"result": "0x" // <- should contain code on the testnet
}
```

Keeping this as a placeholder (maybe somebody wants already to look into this)

**Comment by obscuren** [comment]
Not broken:

```
> admin.miner.start()
true
> {ffffffffffffffffffffffffffffffffffffff1681526020019081526020016000209081540190819060000155505b505056"
undefined
> eth.sendTransaction({from: eth.accounts[0], data:d, gas: "1000000"})
Please unlock account 18a991c7b2bc05ba2bb364eb6e7238ae3cf09c85.
Passphrase:
Account is now unlocked for this session.
'0x633ac115c55b5e661b5592538f91e193559dcbec'
> admin.miner.stop()
true
> eth.pendingTransactions()
[ ]
> eth.getCode("0x633ac115c55b5e661b5592538f91e193559dcbec")
'0x6000357c0100000000000000000000000000000000000000000000000000000000900480633284fd791461004557806370a0823114610059578063ccb767ae1461006e57005b610053600435602435610082565b60006000f35b6100646004356100f8565b8060005260206000f35b61007c600435602435610136565b60006000f35b60015473ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16146100bc576100f3565b80600060008473ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000209081540190819060000155505b5b5050565b6000600060008373ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205463ffffffff169050610131565b919050565b8063ffffffff16600060003373ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205463ffffffff16106101775761017c565b6101e9565b80600060003373ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002090815403908190600001555080600060008473ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000209081540190819060000155505b505056'
```

**Comment by jesuscript** [comment]
indeed. This works perfectly fine in geth console. However exactly the same steps fail when using web3.

**Comment by alexvandesande** [comment]
Fabian, maybe your blockchain was simply out of sync? This I had the same
problem but turned out that simply I was pinging a very old blockchain. It
has since caught up.

On Wed, May 27, 2015 at 2:25 PM, Konstantin <notifications@github.com>
wrote:

> indeed. This works perfectly fine in geth console. However exactly the
> same steps fail when using web3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/go-ethereum/issues/1131#issuecomment-106004076>
> .
>



-- 

Alex Van de Sande
UX Designer

**Comment by frozeman** [comment]
i will run the rpc test again, once #1130 is fixed for me.

**Comment by frozeman** [comment]
So i'm now on my private chain and i still get `0x` for mined contracts.. and i'm alone so there is for sure no fork :) Will look into this...

**Comment by frozeman** [comment]
It might have to do with changes marek did in web3.js contract creation, will talk to him.

**Comment by frozeman** [comment]
Ok as it seems, the gas was to low, which i provided.

But for some reason it has fired the contract creation log.
I guess what happened is that the log was fired and after the gas run out, so it couldn't store the contract.

Is that intended behaviour @obscuren ?
Or can we somehow fire the logs only, if the code is actually fully running.

This opens the question, whether or not contracts or contract  method which sendMoney, do send money even though the function is running out of gas at some point, not executing the rest of the method??

If thats the case, we should definitely let people know about that behaviour.
