### ISSUE TITLE
"invalid merkle root" on definitely valid block.

### ISSUE THREAD

**Issue by fee1deadbaddcafe** [ethereum/go-ethereum#1136]
I0528 04:02:33.279881   42724 chain_manager.go:753] Bad block #455321 (f91143682f734f87e8353ed72bb9e64e9e4646d3f79407706c4614e63c51b74f)
    I0528 04:02:33.279919   42724 chain_manager.go:754] invalid merkle root. received=9f4837d94a59d6c5c474afe97901fe696b0005d06ceb6b55add58a40cc04af28 got=7646447e9b321f3dafdab4864970b945c362b888ebbf787c428f872765eef08f
    I0528 04:02:33.280006   42724 sync.go:121] Synchronisation failed: block downloading cancelled (requested)
    I0528 04:02:33.280036   42724 miner.go:100] Starting mining operation (CPU=8 TOT=9)
    I0528 04:02:33.280978   42724 worker.go:349] commit new work on block 455321 with 0 txs & 0 uncles
    I0528 04:05:11.311417   42724 chain_manager.go:753] Bad block #455321 (f91143682f734f87e8353ed72bb9e64e9e4646d3f79407706c4614e63c51b74f)
    I0528 04:05:11.311463   42724 chain_manager.go:754] invalid merkle root. received=9f4837d94a59d6c5c474afe97901fe696b0005d06ceb6b55add58a40cc04af28 got=7646447e9b321f3dafdab4864970b945c362b888ebbf787c428f872765eef08f
    I0528 04:05:11.311553   42724 sync.go:121] Synchronisation failed: block downloading cancelled (requested)

Stalls after this with no further progress. Other geth nodes seem to be forging ahead with no problems.

**Comment by obscuren** [comment]
Caused by an earlier crash or failed import. The only thing you can do is either 

1. `geth removedb` and restart
2. `geth upgradedb` and leave it run

**Comment by fee1deadbaddcafe** [comment]
An `upgradedb` failed as well, thinking a previously valid block now had an invalid nonce (the nonce it returned didn't match what another node says it should have been). Seems like the block store is incredibly vulnerable to silent corruption, the node had never been exited uncleanly (and it's under a day old).

**Comment by obscuren** [comment]
What was the error?

**Comment by fee1deadbaddcafe** [comment]
Lost it off the top of my terminal buffer unfortunately, but it was just literally invalid nonce and then a printout of the nonce (which was not the same as the one in the actual block). In hindsight I should have kept the files for analysis, but wasn't really thinking.

**Comment by obscuren** [comment]
That's understandable, don't worry. Please standby for release

**Comment by zelig** [comment]
This should be fixed by now
