### ISSUE TITLE
geth crashes when trying to unlock a non-existing account

### ISSUE THREAD

**Issue by fee1deadbaddcafe** [ethereum/go-ethereum#1139]
panic: runtime error: slice bounds out of range

Replicate with `geth --unlock horse` in latest build.

**Comment by Gustav-Simonsson** [comment]
Fix: https://github.com/ethereum/go-ethereum/pull/1140

**Comment by Gustav-Simonsson** [comment]
@fee1deadbaddcafe thanks for reporting! confirmed.

**Comment by obscuren** [comment]
Merged
