### ISSUE TITLE
"Push" notifications to mining clients when new work is available

### ISSUE THREAD

**Issue by eupraxic** [ethereum/go-ethereum#1144]
Currently, a standalone mining client (e.g. ethminer) must poll geth to check for new work.  The polling interval can be reduced (e.g. ethminer --farm-recheck 200), but this increases the load on the geth server.

If the geth server could notify the mining clients when new work is available, it would reduce the load on the geth server and reduce the amount of time mining clients are hashing on old work.

One possible implementation is to provide a second version of the eth_getWork RPC call which doesn't return until either new work is available or a timeout is reached.

**Comment by obscuren** [comment]
We are currently in the process of integrating IPC which should also allow this :-)

**Comment by eupraxic** [comment]
Sounds good!  I would consider JSON-RPC a form of IPC, but I'll infer from your comment that the new IPC capability will better support two-way communication.  Is there an issue for the IPC integration work?

**Comment by obscuren** [comment]
You can do JSON-RPC over IPC. Do not mistake JSON-RPC for being HTTP only, previously we implemented JSON-RPC over TCP/IP but due to much complaints we switched to HTTP. IPC will allow sending and receiving over the same channel. Kind of like WebSockets but without the overhead of TCP/IP :-)

**Comment by fjl** [comment]
This is actively being worked on. Stay tuned!

**Comment by oliversk** [comment]
Any updates?

**Comment by fjl** [comment]
Status update: push is implemented on develop branch, but not yet for mining work.
