### ISSUE TITLE
JUMPDEST vulnerability

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/go-ethereum#1147]
This test: https://github.com/ethereum/tests/blob/develop/StateTests/stSpecialTest.json#L2 has a transaction which costs only about 80k, but needs about 2GB of RAM and 18s in go.
The reason is the usage of a map to store JUMPDEST positions. In this test the code does 1024 recursive calls to itself. The code looks like: <1024 recursiv calls> STOP JUMPDEST JUMPDEST .... JUMPDEST (having 15k JUMPDESTS opcodes).
Cpp used a set for storing the JUMPDESTs, and needed 1.2 GB of RAM, we fixed it by using a vector of uint64_t instead (https://github.com/ethereum/cpp-ethereum/pull/2032), although this slightly reduces the performance.
This was found by a bug hunter through the bounty program. Gustav knows the details.

**Comment by fjl** [comment]
This is fixed in the linked PR. It still uses a map, but keeps the JUMPDEST
locations around for use in recursive calls. The caching scheme keeps the memory
linear even for more complex scenarios involving multiple contracts.

**Comment by fjl** [comment]
Fun fact: the attack is basically the Ethereum version of the classic XML entity bomb.
