### ISSUE TITLE
Unable to create account out of memory

### ISSUE THREAD

**Issue by d11e9** [ethereum/go-ethereum#1148]
I'm unable to create a new account on my geth ethereum node. Currently running `0.9.26-12b90600` 

    docker run -i -v /var/data/log:/var/log -v /var/data/ethereum:/root/.ethereum --entrypoint="bash" -t "eth.datagotchi.com" -s;
    root@8c53eec8c3d0:/gopath/src/github.com/ethereum/go-ethereum# geth console
    I0529 09:57:26.687584       8 backend.go:256] Protocol Version: 60, Network Id: 0
    I0529 09:57:26.709888       8 backend.go:266] Blockchain DB Version: 3
    I0529 09:57:26.716480       8 chain_manager.go:258] Last block (#470599) ebd641bd97a15645409be82008f73c0556dc9d1ce99f1f0008e3d6304a757102 TD=1056321937704263
    I0529 09:57:37.442859       8 cmd.go:148] Starting Geth/v0.9.26-12b90600/linux/go1.4
    I0529 09:57:37.445648       8 server.go:293] Starting Server
    I0529 09:57:37.830080       8 udp.go:189] Listening, enode://8ea937c680d643d81ebf416d408286213e14e329eeccf55c354d9de4eeb2da60414abb57326104065f67c3628e909c02
    88e682fd5a1f72def85b483cd4933e69@[::]:30303
    I0529 09:57:37.832232       8 backend.go:477] Server started
    I0529 09:57:37.837038       8 server.go:530] Listening on [::]:30303
    > I0529 09:58:07.848655       8 downloader.go:169] Block synchronisation started
    I0529 09:58:51.776429       8 chain_manager.go:662] imported 96 block(s) (0 queued 0 ignored) in 42.9266739s. #470695 [8c1992d3 / a182fae0]
    eth.blockNumber
    470695
    > I0529 09:59:00.968712       8 chain_manager.go:662] imported 2 block(s) (0 queued 91 ignored) in 8.956804855s. #470697 [6e8f55fa / 414dd2cf]
    I0529 09:59:04.445933       8 sync.go:120] Synchronisation failed: empty hash set by peer
    adminI0529 09:59:05.922669       8 chain_manager.go:662] imported 3 block(s) (0 queued 2 ignored) in 4.461028584s. #470700 [c1de585f / 190d2f4a]
    .verboI0529 09:59:08.198802       8 sync.go:120] Synchronisation failed: empty hash set by peer
    sity(1)
    undefined
    > eth.blockNumber
    470704
    > eth.getAccounts()
    undefined
    > eth.coinbase
    '0x0000000000000000000000000000000000000000'
    > admin.newAccount()
    The new account will be encrypted with a passphrase.
    Please enter a passphrase now.
    Passphrase:
    Repeat Passphrase:
    fatal error: runtime: out of memory

Full stack trace: https://gist.github.com/d11e9/431ec8341c9dc4c27fdb

**Comment by Gustav-Simonsson** [comment]
This is a feature, the KDF is currently configured to use 256MB of memory: https://github.com/ethereum/go-ethereum/blob/develop/crypto/key_store_passphrase.go#L88

We may lower this if it's a problem for people, but currently you can simply add more memory to your docker instance and it should work fine.

**Comment by d11e9** [comment]
For anyone else experiencing this same issue. The way I've managed to resolve it is the following:

If geth is unable to create a new account on the console via, due to the overhead of the `scrypt` and the running node combined within the same docker container (or low memory limit environment), then you can run it via the command line, without the overhead of a running node like so:

    $ geth accounts new

And then either restart the node, or run it in a different container and then import it istead.

Worked for me TM

**Comment by d11e9** [comment]
Arg: the above didn't work, in that the node is still unable to then unlock the account when trying to interact with it, meaning you'd have to unlock upfront  `geth --unlock <addr> ` unfortunately this still fails.

**Comment by fjl** [comment]
@d11e9 is this still an issue?

**Comment by fjl** [comment]
The account system has changed significantly since May. We haven't had another report of this, so I am closing this issue for now.

**Comment by d11e9** [comment]
:+1: was resolved
