### ISSUE TITLE
web3.sha3 returns the same hash for all string that are not a hash

### ISSUE THREAD

**Issue by ralph-pichler** [ethereum/go-ethereum#1158]
Different strings returning the same hash:

> web3.sha3('string1')
'0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'
> web3.sha3('string2')
'0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'

If the string is a hash it works:

> web3.sha3('0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470')
'0x10ca3eff73ebec87d2394fc58560afeab86dac7a21f5e402ea0a55e5c8a6758f'

This does not happen when using upstream web3.js, just with the js embedded in geth.

**Comment by debris** [comment]
@obscuren updating to web3.js `0.5.0` will resolve this issue.
