### ISSUE TITLE
Error message on repeatedly issuing the same transaction

### ISSUE THREAD

**Issue by jonathandmoore** [ethereum/go-ethereum#1159]
Geth/v0.9.26/darwin/go1.4.2

I'm running this, whilst also CPU mining:

```bash
#spam.sh
while true; do
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from": "0xe98b5e4afd9ffa4d6c2988ff20703b930377abe6", "to": "0x8ce6bf6687867e0eaf71d46aca6549a7ad9ef7eb", "value": "1000000000000"}], "id":1}' 127.0.0.1:8545
done
```

It generates transactions fine, then after a while it starts generating this error instead. The error repeats until the script is stopped. If the "value:" is changed the script can then be restarted to generate new transactions:
```js
{
	"id": 1,
	"jsonrpc": "2.0",
	"error": {
		"code": -32603,
		"message": "Known transaction (7755170e)"
	}
}
```
I'm not certain if this is a bug or feature.

**Comment by karalabe** [comment]
@frozeman Is this the correct way of posting transactions? I.e. I'm particularly referring to that `id` field. Shouldn't that be unique?

**Comment by frozeman** [comment]
The id field is not taken in consideration right now in the RPC, but should be unique. I thinks thats a feature as long as you have the same tx, with the exact same value in the memo pool, it throws this error.

@obscuren could you clarify?
Didn't we removed that feature in favour of the optional nonce, to overwrite transactions?

**Comment by jonathandmoore** [comment]
@frozeman, thanks. I should really check those specs.  

What stuck me as strange is that I am able to post the transaction a variable number of times, it seems successfully, before the error is reported, then I am unable to post it again. In that case, are there lots of other occasions when the error is unreported, before the error reporting kicks in?  Sorry not to understand as I am testing from a naive perspective here.

**Comment by markrtgh** [comment]
Same issue as  [#1019](https://github.com/ethereum/go-ethereum/issues/1019)
