### ISSUE TITLE
JSON-RPC could desperately do with some new methods for developing autonomous systems.

### ISSUE THREAD

**Issue by fee1deadbaddcafe** [ethereum/go-ethereum#1160]
I've run into some limitations I believe are complete blockers for external system development using the JSON-RPC interface, there are work arounds but they are needlessly complex and fragile.
- no method of creating an account keypair (except from the command line)
- no method unlocking an account keypair (except from the command line)
- no method of notifying an external application of changes such as
  - new block
  - account event

**Comment by bas-vk** [comment]
We are aware of these limitations. Currently the rpc package is refactored in a way that additional interfaces can be added (e.g. full duplex interface with ipc). Next step is to add an additional API which is useful for for DAO's but also for external clients like mist.

What do you mean with "account event"?

**Comment by fee1deadbaddcafe** [comment]
New transaction to an owned account for example would be nice to have notifications of. 

IPC seems like a strange choice over a websocket (early versions of Ethereum used websockets I think, I don't know when that disappeared) where you could extend this to being able to have getWork messages pushed to farming miners rather than being polled. It's standard practice for most exchanges and other services to run daemons in virtual machines or completely isolated hardware, which with IPC would need some sort of middleware in there as well to ferry out notifications.

**Comment by lexansoft** [comment]
Still "no method unlocking an account keypair (except from the command line)" available through JSON-RPC. Any update?

**Comment by fjl** [comment]
All of the things listed in the original issue have been implemented since 2015. Happy to finally close this issue!
