### ISSUE TITLE
Error building geth from source in Debian

### ISSUE THREAD

**Issue by rhkarls** [ethereum/go-ethereum#1162]
Following the Ubuntu instructions the build fails with `make: *** [geth] Error 2`

Seems to be an error with secp256k1. I can build that lib fine from https://github.com/bitcoin/secp256k1

Full logs at: https://gist.github.com/rhkarls/e103cff8a6141a373271

Possibly related: https://github.com/ethereum/go-ethereum/issues/934

Cloned go-ethereum today, so it's fresh. 
I'm on 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u1 x86_64 GNU/Linux

**Comment by karalabe** [comment]
What version of Go are you building with? It looks like a very **very** old bug/limitation (i.e. 4+ years old). Could you please check your installed go version?

Mine is:
```
> go version
go version go1.4.2 linux/amd64
```

**Comment by rhkarls** [comment]
You are right, it's quite old...`go version go1.0.2` - seems to be 3 years old. Didn't think about this, so thanks for spotting it!

 I will hopefully have time later today to try with a newer go version, and will report back when done!

**Comment by karalabe** [comment]
Cheers :)

I got lucky because there were others compile errors too in your logs which failed on completely valid Go syntax so I checked up if those were extensions to the origin Go release :) Closing this, but feel free to reopen if you do encounter build errors.

**Comment by phonikg** [comment]
I can add that the version of go that is installed by default on *most* stable armhf distro's(RasPi, BBB) is either 1.2.1 or 1.3.3 and this same error occurs... upgrade to go 1.4.2 and build completes without error:

#### set environment variables
`export PATH=$HOME/golang/bin:$PATH`
`export GOPATH=$HOME/go`
`mkdir -p $GOPATH`

#### install golang from source
`cd ~`
`git clone https://go.googlesource.com/go golang`
`cd golang && git checkout go1.4.2`
`cd src && ./make.bash`

**Comment by seyuf** [comment]
+1 @phonikg thanks

**Comment by phonikg** [comment]
@seyuf alternately you could upgrade your debian to unstable `sid` to get to 1.4.2 as well

**Comment by seyuf** [comment]
@phonikg thanks for the tip but i do not do well with sid too unstable for me.
I believe my issue was with the fact that i installed golang with apt in addition to the manual with curl and update the bashrc instructions.
In result i had two versions of go the 1.0.2 by default and the 1.4.2 in /usr/local. 
Even after setting an alias to the 1.4.2 the build was still failing. So the uninstalled the apt one and followed your instructions.
Anyway some one should update the install instructions of the repo (do not install golang with apt if you've already installed it manually).
