### ISSUE TITLE
--difficulty CLI feature for private chains

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/go-ethereum#1163]
Would something like a force mining difficulty CLI param be possible for private chains? I'm thinking the CLI param would be something like "--difficulty=1", where the int value represents a constant, potentially low difficulty. The param would only effect local/private chain testnet nodes. The reason for this feature is: I'd like to be able to mine, and test DApp transactions locally without having to tax the hell out of my local GPU's.

**Comment by karalabe** [comment]
There was a different idea to solve what you're looking for, namely to only run the miner when there are transactions pending. I don't know if/how well it has been sorted out, but there was some attempt mentioned here: https://github.com/ethereum/go-ethereum/issues/1061 Maybe it could be of some help to your scenario too?

**Comment by SilentCicero** [comment]
+1

**Comment by nmushegian** [comment]
+1

**Comment by fjl** [comment]
The difficulty is adjusted dynamically by protocol rules. You have a couple of options:

* create a custom genesis block with low difficulty and use it for your test network
* use embark or a similar framework to mine on demand
