### ISSUE TITLE
Whisper filters from rpc cause crash/panic

### ISSUE THREAD

**Issue by d11e9** [ethereum/go-ethereum#1164]
I'm currently doing stuff with `shh`/Whisper. And was able to crash my node simply using `web3.js` to request /send web3 RPC calls from a browser.

```
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x0 pc=0x573f30]
```

Full stack trace in a gist: [https://gist.github.com/d11e9/1ef79a41209cbe15a044](https://gist.github.com/d11e9/1ef79a41209cbe15a044)

**Comment by obscuren** [comment]
Did you run with whisper enabled? `geth --ssh`

**Comment by karalabe** [comment]
If would also be very helpful if you could provide a repro of the function call / program that caused this crash.
