### ISSUE TITLE
blockchain db error: resource temporarily unavailable

### ISSUE THREAD

**Issue by DennisBPeterson** [ethereum/go-ethereum#1168]
Just built geth from source using instructions here:
https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu#building-from-source

Ran "./geth", everything fine. Wasn't sure how to quit so used ctrl-z. Then ran "./geth console" and got error:

Fatal: blockchain db error: resource temporarily unavailable

Further attempts with just "./geth" also give the error, so I'm assuming something is locked due to my ungraceful shutdown. Is this permanently jammed?

./geth -v gives version 0.9.26

Tried geth removedb but didn't fix.

**Comment by DennisBPeterson** [comment]
Rebooting machine fixed it, so I guess this is pretty minor.

**Comment by DennisBPeterson** [comment]
looks like a reboot fixed it

**Comment by fjl** [comment]
You will get this error if you try to run more than one instance of geth with the same data directory because the database is already in use.

**Comment by DennisBPeterson** [comment]
Tested this some more to make sure I wasn't running multiple instances. It seems like ctrl-z doesn't quit shut everything down.

If I start geth, close the terminal killing the process, then open another terminal and start again, no problem.

If I start geth, stop it with ctrl-z, and attempt to restart, I get the error. If I then close the terminal and bring up another, it works again.

(Not that this is a major problem or anything.)

**Comment by karalabe** [comment]
Ctrl+Z doesn't terminate the process, only suspends it. All the database locks are still held.

**Comment by DennisBPeterson** [comment]
Ok thanks, sounds like this issue should just be closed then.

**Comment by rcorbish** [comment]
CTRL-Z pushes the service to suspend
type jobs to see suspended jobs
fg 1  <-- job number ) to unsuspend a job

**Comment by TimonPeng** [comment]
I've had this problem today. This is my solution:

Find the PID of geth process, then kill it.

$ `ps aux | grep 'geth'`
root         712   0.0  3.0 573574112 505984   S    23 616  283:07.70 /Applications/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth --fast --cache 512

`kill -9 712`
