### ISSUE TITLE
geth cannot sync, maybe related to network spamming

### ISSUE THREAD

**Issue by Phistr90** [ethereum/go-ethereum#1170]
My node isnt able to sync any longer, once it was out of sync as I send a bunch of tx with a batch file over the json-rpc server. I stopped the script and restarted it, but it is stucked and doesnt sync.
My other nodes are running smoothly as they were kept on the current state.

EDIT: Same problem on the second rig, lost sync shortly after the new epoche.
EDIT2: No problem in syncing with c++ client, must only be an issue of geth.
Logfile: https://gist.github.com/Phistr90/b49786b56ed4ebd58c03#file-logfile

**Comment by karalabe** [comment]
Is your net connection stable? I'm seeing many hash requests and all block requests timing out.

**Comment by Phistr90** [comment]
yes it is stable, and the c++  client has no problems of syncing

**Comment by karalabe** [comment]
According to the logs,
```
I0602 12:40:20.614560   22001 downloader.go:391] Downloaded hashes (736) in 3.86139649s
```
That is 6.1 kbytes/second bandwidth (when it does indeed finish without timing out). Geth currently has a 5 second timeout for fetching both hashes and blocks. With such a bandwidth, you won't be able to retrieve a batch of 128 blocks within the allotted 5 seconds.

Could you please verify your current bandwidth with speedtest for example against a central European server? I cannot imagine timing out on all connections otherwise.

With regard to C++, I'm not familiar with their codebase and the timeouts they are working with, if any. I'll try and look through our code however to see if there could be some other reason for failing to sync.

**Comment by Phistr90** [comment]
download bandwidth 3.26 mbps

**Comment by karalabe** [comment]
thx

**Comment by karalabe** [comment]
Out of curiosity, if you increase the timeouts in `eth/downloader.go` (`hashTTL` and `blockTTL`) from 5 seconds to maybe half a minute, does that solve your issue?

**Comment by Phistr90** [comment]
I'll try.
btw: I did the same test and let the geth client try to sync meanwhile: 780kbs

**Comment by Phistr90** [comment]
doesnt seem to work either, I 'll upload the log...

**Comment by Phistr90** [comment]
https://gist.github.com/Phistr90/5d21b5808e59201dd7fb

**Comment by Phistr90** [comment]
Out of curiosity, is there a way to kill the current tx pool in geth?
I think the issue might be related to the fact that there are plenty of outgoing tx stucked...

**Comment by karalabe** [comment]
Hmmm, I'm not seeing hash timeouts any more. Checking the current block sizes though, they are 25+KB, which means that geth is pulling 25.6MB when it begins syncing, for which you have originally 5 secs, with the updated code 30 secs to process.

Given your 3.26 mbps downlaod speed, it would take at least 62 seconds to download. Please try pushing the timeouts to 2-3 mins. It's not healthy at such a high value, but it might be worth a shot to debug.

**Comment by Phistr90** [comment]
here is the log with 120s: https://gist.github.com/Phistr90/ff6425c3ef4dddc2b702

**Comment by Phistr90** [comment]
and here one with 180s: https://gist.github.com/Phistr90/06424551035213c5bce1

**Comment by karalabe** [comment]
I'm not seeing this last one reporting timeouts any more. If you tried reducing the `MaxBlockFetch` int the same file from 128 to maybe 16?

**Comment by Phistr90** [comment]
okay finally it loaded 10 new blocks in aprox 10min :S

**Comment by bargst** [comment]
I've got the same issueand set hashTTL and blockTTL to 150s.
Now importing 256 block every ~10min

**Comment by cjphilpot** [comment]
Im having the same issue. "Synchronization failed: No peers available or all peers tried."

**Comment by karalabe** [comment]
People are currently spamming the network with transactions producing enormous block sizes (both in download size as well as processing time). I've discussed this a bit internally and given that there shouldn't be a theoretical block size limit, the downloader will somehow need to figure out/estimate how much data it will need to pull and adjust the number of requested blocks and timeouts accordingly.

If tweaking the parameters works for you guys then I'm happy, but a proper fix will probably require a bit of time ti figure out.

**Comment by Phistr90** [comment]
it stucks again. 15min not a single block imported.

in total: 154 blocks in 30min...- yeah

**Comment by karalabe** [comment]
Just be sure where the bottleneck is... if you have blocks but it takes a lot of time to import, then it's CPU limited. If you don't even get blocks to import, then it's the sync.

You can check if syncing is doing anything via the console:
```
> admin.progress()
{
  pending: 2797,
  cached: 1024
}
```

**Comment by karalabe** [comment]
Can you please run this PR and see if it makes things better?

https://github.com/ethereum/go-ethereum/pull/1176

Also please run with the usual detailed logging for sync and downloader.

**Comment by karalabe** [comment]
Please try with latest develop. The above mentioned fix was merged.

**Comment by cjphilpot** [comment]
Works great for me. I can now download blocks again for the first time since the heavy spamming started.

**Comment by Phistr90** [comment]
Hi, sorry had a lot to do today.

Here is the log, seem to work pretty good :) 
https://gist.github.com/Phistr90/a045ed7efb546064ee75
Thanks

**Comment by pureland** [comment]
> admin.progress()
{
  pending: 18410,
  cached: 486
}
but my cup usage is low
