### ISSUE TITLE
Add a warning to the log when the client is not in sync 

### ISSUE THREAD

**Issue by alexvandesande** [ethereum/go-ethereum#1171]
When the client is still downloading blocks and syncing with the network (which can take a long time sometimes), a lot of things will seem not to work: transactions will be stuck at pending, getCode will keep returning 0, and the user has no feedback on why.

It would be nice if, depending on the latest block timestamp or some other metric, if the current client was significantly out of sync it would output regular warnings to the console.

**Comment by obscuren** [comment]
Are you suggesting centralised metrics @alexvandesande !? :astonished:

If users do stupid things it will sort it self :-)
