### ISSUE TITLE
"Too many files opened"

### ISSUE THREAD

**Issue by stephantual** [ethereum/go-ethereum#1172]
Geth on Buntu was running happily for a couple of days straight when it suddenly started throwing 'too many files opened' around 4am this morning. It subsequently stopped syncing the chain altogether. This could be related to the TX spam testing effort.

**Comment by stephantual** [comment]
ulimit returns = "unlimited"

**Comment by arhuaco** [comment]
My instance is no longer getting new blocks. I pressed Ctrl+d in the console and I got this message:

> unable to open history file: open /home/len/.ethereum/history: too many open files

    $ ulimit -a
    core file size          (blocks, -c) 0
    data seg size           (kbytes, -d) unlimited
    scheduling priority             (-e) 0
    file size               (blocks, -f) unlimited
    pending signals                 (-i) 62901
    max locked memory       (kbytes, -l) 64
    max memory size         (kbytes, -m) unlimited
    open files                      (-n) 1024
    pipe size            (512 bytes, -p) 8
    POSIX message queues     (bytes, -q) 819200
    real-time priority              (-r) 0
    stack size              (kbytes, -s) 8192
    cpu time               (seconds, -t) unlimited
    max user processes              (-u) 62901
    virtual memory          (kbytes, -v) unlimited
    file locks                      (-x) unlimited

**Comment by arhuaco** [comment]
I got this again with 0.9.34. I hadn't seen this in a while.

    I0629 22:03:16.807772   10589 server.go:1775] http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 5ms
    I0629 22:03:16.813182   10589 server.go:1775] http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 5ms
I0629 22:03:16.818503   10589 server.go:1775] http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 5ms
    I0629 22:03:17.808422   10589 server.go:1775] http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 5ms
    F0629 22:03:18.668058   10589 cache.go:45] db write err:open /home/len/.ethereum/state/1930180.ldb: too many open files
    I0629 22:03:18.810028   10589 server.go:1775] http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 5ms

**Comment by stephantual** [comment]
This is a dupe of #1460

**Comment by joeykrug** [comment]
Pasting my comment from #1460:

So I get this too many open files error as well... I'm connected to no peers (mining w/ 1 core solo on a private chain), running in Ubuntu VM on DigitalOcean

F0713 06:59:02.272104 971 cache.go:61] db write err:open /root/.ethereum/state/000066.log: too many open files

Running latest geth btw

**Comment by obscuren** [comment]
It always appears to be an issue on Ubuntu. Has this been encountered on other distros as well?

**Comment by obscuren** [comment]
Could you guys also, after having geth running for a while, run:

`lsof | awk '{print $1}' | uniq -c | sort -rn | head`

**Comment by hellabyte** [comment]
To add to this, I lost network connection overnight and awoke to this issue. Turns out that for whatever reason that my system (Ubuntu 14.04.02) gave birth to over 32000 state files. Thus, honest geth runs into a file handle limit when trying to read all these roughly 2MB ldb files.

**Comment by fjl** [comment]
This should be solved now.
