### ISSUE TITLE
eth/downloader: sometimes the sync keeps fetching blocks like crazy

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#1178]
*This is a note to myself.*

Sometimes the downloader keeps fetching blocks from a peer, for some reason seems not able to insert them and fetches again, again, again:

```
I0603 17:24:10.845401   14848 peer.go:109] [eb2aac31c8d58c3d] fetching 95 blocks
I0603 17:24:10.962171   14848 peer.go:109] [eb2aac31c8d58c3d] fetching 95 blocks
...
I0603 17:24:12.512880   14848 peer.go:109] [eb2aac31c8d58c3d] fetching 95 blocks
```

During this time, the exact number of blocks it's refetching is missing from the cache (max 1024):

```
> admin.progress()
{
  pending: 79176,
  cached: 929
}
```

I don't really know yet what the cause might be, but it seems as if the blocks we're fetching are not the next ones in line into the cache, hence are discarded. But why retry then? And why not try other peers for it?

The problem usually sorts itself out when importing pulls a next batch of blocks, probably that's why we haven't noticed it yet. Should look into this in detail.

**Comment by tcoulter** [comment]
I believe I am getting this issue as well, and my guess is it's what's causing my synchronization issues (or related):

```
I0603 09:49:45.883391   31177 peer.go:109] [4fb85e61a015b089] fetching 128 blocks
I0603 09:49:46.124683   31177 peer.go:109] [4fb85e61a015b089] fetching 128 blocks
I0603 09:49:46.160030   31177 sync.go:102] Attempting synchronisation: e857a716205fe653, 0xecc6b206cdabd231de9410ed5b3459c2cad7b61f2d07b2fc5cd8cd64a966efdc
I0603 09:49:46.160084   31177 sync.go:110] Synchronisation already in progress
I0603 09:49:46.369969   31177 peer.go:109] [4fb85e61a015b089] fetching 128 blocks
I0603 09:49:46.396489   31177 sync.go:102] Attempting synchronisation: 72ebf89c5ebf4535, 0xa500c0c3568e7dedbd2fba1c3af3eed89e0f9f1d991a229c0630f5dc24320918
I0603 09:49:46.396539   31177 sync.go:110] Synchronisation already in progress
I0603 09:49:46.587925   31177 sync.go:102] Attempting synchronisation: 72ebf89c5ebf4535, 0xa500c0c3568e7dedbd2fba1c3af3eed89e0f9f1d991a229c0630f5dc24320918
I0603 09:49:46.588025   31177 sync.go:110] Synchronisation already in progress
I0603 09:49:46.628633   31177 sync.go:102] Attempting synchronisation: f575894c147d4ad4, 0x02f873ae85dcb3cf6b2968b2f17f7023f3f2f37a5ad3b6d89289b405250f6c82
I0603 09:49:46.628757   31177 sync.go:110] Synchronisation already in progress
I0603 09:49:46.642845   31177 api.go:38] eth_getFilterChanges ["0x0"]
I0603 09:49:46.643012   31177 api.go:38] eth_getFilterChanges ["0x1"]
I0603 09:49:46.709563   31177 peer.go:109] [4fb85e61a015b089] fetching 128 blocks
I0603 09:49:46.816694   31177 sync.go:102] Attempting synchronisation: 39f862a604c84469, 0xd9a7721800cdbe244ba6681c0c72b0b7f896df7835fb0482132ee2f46cc4711a
I0603 09:49:46.816765   31177 sync.go:110] Synchronisation already in progress
```
I'm finding that geth might sync for awhile, but eventually gets stuck and stays in the "Synchronisiation already in progress" state, to the point where if I leave it sync'ing overnight the block count doesn't increase, even though my output is like above.

**Comment by karalabe** [comment]
It's not related. Sync already in progress is simply a debug detail, no error there. There was an issue with huge blocks being sent that required a large bandwidth to sync up. You could try pulling latest develop, a fix was merged to solve just that.

**Comment by karalabe** [comment]
Actually, scratch that. Is seems you do have this issue too. However I haven't seen it yet block up the downloader. Maybe try the above mentioned fix. I'll try to sort this out tomorrow.

**Comment by tcoulter** [comment]
Trying that now, thanks!

**Comment by tcoulter** [comment]
I'd say my problem is solved with your recommendation above. I've been syncing for the last 10 minutes and have downloaded more of the chain than I had downloaded all of last night. Thanks a lot for the changes.

**Comment by Ulysseus** [comment]
I seem to be getting the same issue

 1160 chain_manager.go:668] imported 0 block(s) (1 queued 0 ignored) in 130.691µs. #528131 [f066e4e2 / f066e4e2]
I0604 11:39:26.650708    1160 chain_manager.go:668] imported 1 block(s) (0 queued 0 ignored) in 4.324943ms. #528131 [f066e4e2 / f066e4e2]
I0604 11:39:28.160672    1160 chain_manager.go:668] imported 0 block(s) (1 queued 0 ignored) in 127.942µs. #528132 [cabfcdbb / cabfcdbb]
I0604 11:39:31.646559    1160 chain_manager.go:668] imported 0 block(s) (1 queued 0 ignored) in 179.226µs. #528132 [cabfcdbb / cabfcdbb]
I0604 11:39:36.405270    1160 chain_manager.go:668] imported 1 block(s) (0 queued 0 ignored) in 6.629798ms. #528132 [e9df92b0 / e9df92b0]
I0604 11:39:36.650556    1160 chain_manager.go:668] imported 1 block(s) (0 queued 0 ignored) in 4.182475ms. #528132 [cabfcdbb / cabfcdbb]

I am eating data at a terrific rate, down here on the bottom of africa bandwidth is a precious resource!

Burning about 120Mb/hr so > 3Gb a day if I am mining, or 3Gb a day if I am running a node. I have to drop out until this is fixed I can't afford the data.

**Comment by karalabe** [comment]
@Ulysseus I don't really see an error in your logs. You are up to date at the latest chain. Since block propagation is currently set to 100% of your peers, this may be the network burden you are seeing (you receive the same block from all your peers and send it to all). We have a potential protocol update to reduce this traffic a bit, though it's not considered a bug, rather a place for optimizations.

Still, as a full node of the network, your node will be both downloading as well as uploading blocks to other nodes, so there will always be some traffic.

**Comment by Ulysseus** [comment]
But I seem to receive the same block over and over, the data use is extreme, network is fast enough, but the data usage seems out of wack, lets assume a block is 20K then on a 12s block time thats 100Kb per minute 600Kb per hour, I am getting 130Mb per hour, I tried --maxpeers "4" but it just halved the data rate to 60Mb/hr. Looking at the logs it imports block 528132 repeatedly, thats why I posted it, I get the impression thats its imported the same info, instead of doing it just once 130Mb/day is okay but 130Mb/hr is just way to expensive down here. I have chewed through 60 Gb in the last 10 days.

**Comment by karalabe** [comment]
As I wrote in my previous post, blocks are propagated to 100% of your peers, meaning, that a new block crosses every network connection once at least. With your scenario of a 20KB block (note, there are actually 50KB ones too) and 4 peers, that's 80KB/unique-block.

Many times in the network the same block is found by multiple miners, alas with varying difficulty. So if a miner finds a better block soon after a previous miner found the same block, the better one will overwrite the older one. If we assume that this happens 2-3 times for every block, that-s 160-240KB/block.

The average block time currently according to https://stats.ethdev.com/ is 7 seconds, so the above block propagation would amount to 1.35-2.05MB/minute, or 82-123MB/hour. This is without considering block synchronizations that remote peers download from you.

Of course the above numbers are way off, I've just written them up to demonstrate that having such a network traffic can actually be valid and not a bug. With the new proposal I mentioned, block propagation bandwidth should be reduced significantly, without impacting propagation speed. But the exact numbers will probably still be implementation dependent. However, this is a completely separate issue from the one opened in this thread, so let's not diverge further away.

**Comment by Ulysseus** [comment]
Ok I get it thx for the explanation
