### ISSUE TITLE
Shared peer limits???

### ISSUE THREAD

**Issue by samlavery** [ethereum/go-ethereum#1180]
Is it possible to check and limit the number of shared peers a node has with it's other peers?  It's sub-optimal to allow you and your peer to connect to mostly the other nodes.  I'm not where the go code for peer authorization lives, but this could potentially improve propagation times by reducing redundant connections. 

Maybe it already does this in some fashion?

**Comment by fee1deadbaddcafe** [comment]
Allowing peers to know a peers peer would be horrendous for privacy, allowing anybody to map the network and target partitioning attacks.

**Comment by obscuren** [comment]
It won't connect to most other nodes. It has policies in place to make sure the network is wellformed. Please refer to the code if you're interested or the documentation about RLPx and the discovery protocol.

**Comment by samlavery** [comment]
Can you point me to the discovery protocol, or the implementation?  I see how it has policies to make it 'well formed' but they are rather arbitrary and sub-optimal.  It's not an easy problem by any stretch, but there are always efficiencies to be gained.... Maybe I'll try and submit a go PR :)

Mapping the network is actually a trivial problem given the properties explained in the documentation.  You don't need to traverse the network, the network will essentially traverse you with the right signaling.  Security via network obscurity does not work, there are some pretty timely examples in the news right now....

**Comment by fjl** [comment]
The code for 'peer authorisation' lives [here](https://github.com/ethereum/go-ethereum/blob/68898a4d6bd5edf0011197ef0a68f3fe3cfd0d95/p2p/server.go#L503). 
I can tell you that a PR implementing what you have suggested would need to touch a lot of other places and would require wire protocol changes. Feel free to try it.

**Comment by fjl** [comment]
If you want to build something that's actually useful though, please consider making a tool to map the network instead. Could be a nice exercise and you can learn some Go along the way.
