### ISSUE TITLE
Contract event .watch() gets old events. Behavior intended/buggy?

### ISSUE THREAD

**Issue by Smithgift** [ethereum/go-ethereum#1182]
Contracts' events seem to trigger a .watch() callback even if the event happened before .watch() was called. Is this intended behavior? I can live with it if it is, but it seems immediately strange to me.

**Comment by AdvancedStyle** [comment]
+1; this seems like every odd behavior.

**Comment by maran** [comment]
I believe this is intended behaviour. If you want it differently you can specify the `fromBlock` and set it to the current one. See the [documentation here](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter).

**Comment by obscuren** [comment]
This is intended behaviour
