### ISSUE TITLE
if DB is corrupt, is it possible to provide a message indicating so?

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1190]
Run Geth/v0.9.27

https://gist.github.com/ethers/433e9576de90f8f3084a

if DB is corrupt, is it possible to provide a message indicating so (even nicer if it's possible for the msg to suggest what the remedy is)?  instead of the activity shown in the log (which seems to have a loop?)

**Comment by fjl** [comment]
This is hard to do because DB corruption causes arbitrary errors in block validation. These error can also have other causes.
