### ISSUE TITLE
panic: ethash_full_new IO or memory error

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#1194]
https://gist.github.com/rfikki/2e4c8845f6a601bb34c1

Ran into this problem on both Ubuntu virtual machine and now on windows.

**Comment by rfikki** [comment]
Looks similar to https://github.com/ethereum/go-ethereum/issues/1092

**Comment by karalabe** [comment]
How much memory do you have? The error message seem to indicate that you ran out of system memory while generating the sizeable DAG for mining.

**Comment by rfikki** [comment]
Intel I7, - 3630QM CPU, @2.40 GHz
8 GB DDR3 RAM
64 bit operating system

**Comment by rfikki** [comment]
What is the minimum amount of RAM required?

**Comment by karalabe** [comment]
Ah, way less than that :) @Gustav-Simonsson any ideas? You worked with ethash, or am I mistaking?

**Comment by rfikki** [comment]
When it happened on the virtual machine using Ubuntu I thought it might be memory related so I switched to out of the virtual machine and using windows 8.1 running on a gaming machine ASUS 75VW with the above 8gb ram and got the same error. My network connection is faster than most 112.72 Mbps download.

**Comment by rfikki** [comment]
Ok, I tried various ways to get past this. It seems when I waited for all the blocks to be completely caught up with importing and then started mining(generating the DAG). I was able to get past this error.
