### ISSUE TITLE
Synchronizing with the network 

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#1197]
I0607 08:38:59.181816    2920 backend.go:255] Protocol Version: 60, Network Id: 0
I0607 08:38:59.181816    2920 backend.go:265] Blockchain DB Version: 3
I0607 08:38:59.184786    2920 chain_manager.go:246] Last block (#548609) 5af25b4f100c584d776efb255e06c8fa58c1e7dd144f4baec183df581d75baa9 TD=3099704994771761
I0607 08:41:36.266689    2920 cmd.go:148] Starting Geth/v0.9.27/windows/go1.4.2
I0607 08:41:36.266689    2920 server.go:293] Starting Server
I0607 08:41:36.376995    2920 udp.go:189] Listening, enode://8caba47ed1c47fef7b6582fd0e57c0cdfe018936cb65e270e4148c8b0111e360f6a4ff1c17bcf19fce09475e0f1f9a6291084f21998373e55503a8a9b766470a@[::]:30303
I0607 08:41:36.376995    2920 server.go:530] Listening on [::]:30303
I0607 08:41:36.377996    2920 backend.go:472] Server started
I0607 08:41:38.682873    2920 downloader.go:139] Registering peer a979fb575495b8d6
I0607 08:41:38.876152    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:41:39.115782    2920 downloader.go:139] Registering peer 33ea4d84fe742e5b
I0607 08:41:46.378804    2920 sync.go:102] Attempting synchronisation: 33ea4d84fe742e5b, 0x4ab81ed24be4099dc2b2e54750fd50ca5d7d7db99fe7f2db88cc5bd38a9db82e
I0607 08:41:46.378804    2920 downloader.go:170] Block synchronisation started
I0607 08:41:46.378804    2920 downloader.go:219] Synchronizing with the network using: 33ea4d84fe742e5b
I0607 08:41:46.378804    2920 downloader.go:257] Downloading hashes (4ab81ed2) from 33ea4d84fe742e5b
I0607 08:41:46.806700    2920 downloader.go:150] Unregistering peer 33ea4d84fe742e5b
I0607 08:41:47.672495    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:41:51.380666    2920 downloader.go:368] Peer (33ea4d84fe742e5b) didn't respond in time for hash request
I0607 08:41:51.380666    2920 sync.go:113] Removing peer 33ea4d84fe742e5b: timeout
I0607 08:41:56.379007    2920 sync.go:102] Attempting synchronisation: a979fb575495b8d6, 0x2d45329bb5a88d179c85343852cbc48c6656072058f3109918c544f7ae9c854d
I0607 08:41:56.379007    2920 downloader.go:219] Synchronizing with the network using: a979fb575495b8d6
I0607 08:41:56.379007    2920 downloader.go:257] Downloading hashes (2d45329b) from a979fb575495b8d6
I0607 08:42:01.380239    2920 downloader.go:368] Peer (a979fb575495b8d6) didn't respond in time for hash request
I0607 08:42:01.380239    2920 sync.go:113] Removing peer a979fb575495b8d6: timeout
I0607 08:42:01.380239    2920 downloader.go:150] Unregistering peer a979fb575495b8d6
I0607 08:42:09.840440    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:42:12.900568    2920 downloader.go:139] Registering peer 33ea4d84fe742e5b
I0607 08:42:16.378436    2920 sync.go:102] Attempting synchronisation: 33ea4d84fe742e5b, 0x4ab81ed24be4099dc2b2e54750fd50ca5d7d7db99fe7f2db88cc5bd38a9db82e
I0607 08:42:16.378436    2920 downloader.go:219] Synchronizing with the network using: 33ea4d84fe742e5b
I0607 08:42:16.378436    2920 downloader.go:257] Downloading hashes (4ab81ed2) from 33ea4d84fe742e5b
I0607 08:42:17.251684    2920 downloader.go:150] Unregistering peer 33ea4d84fe742e5b
I0607 08:42:21.380211    2920 downloader.go:368] Peer (33ea4d84fe742e5b) didn't respond in time for hash request
I0607 08:42:21.380211    2920 sync.go:113] Removing peer 33ea4d84fe742e5b: timeout
I0607 08:42:24.357167    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:42:40.388776    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:42:46.378195    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:42:46.378195    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:42:46.378195    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:42:51.378574    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:42:51.378574    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:42:51.378574    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:43:07.252279    2920 downloader.go:139] Registering peer 33ea4d84fe742e5b
I0607 08:43:15.445320    2920 downloader.go:150] Unregistering peer 33ea4d84fe742e5b
I0607 08:43:15.948814    2920 downloader.go:139] Registering peer a979fb575495b8d6
I0607 08:43:16.379194    2920 sync.go:102] Attempting synchronisation: a979fb575495b8d6, 0x2d45329bb5a88d179c85343852cbc48c6656072058f3109918c544f7ae9c854d
I0607 08:43:16.379194    2920 downloader.go:219] Synchronizing with the network using: a979fb575495b8d6
I0607 08:43:16.379194    2920 downloader.go:257] Downloading hashes (2d45329b) from a979fb575495b8d6
I0607 08:43:16.503342    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:43:21.379584    2920 downloader.go:368] Peer (a979fb575495b8d6) didn't respond in time for hash request
I0607 08:43:21.379584    2920 sync.go:113] Removing peer a979fb575495b8d6: timeout
I0607 08:43:21.379584    2920 downloader.go:150] Unregistering peer a979fb575495b8d6
I0607 08:43:26.378710    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:43:26.378710    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:43:26.378710    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:43:31.378868    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:43:31.378868    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:43:31.378868    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:43:49.217553    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:43:52.081817    2920 downloader.go:139] Registering peer 33ea4d84fe742e5b
I0607 08:43:56.379227    2920 sync.go:102] Attempting synchronisation: 33ea4d84fe742e5b, 0x4ab81ed24be4099dc2b2e54750fd50ca5d7d7db99fe7f2db88cc5bd38a9db82e
I0607 08:43:56.379227    2920 downloader.go:219] Synchronizing with the network using: 33ea4d84fe742e5b
I0607 08:43:56.379227    2920 downloader.go:257] Downloading hashes (4ab81ed2) from 33ea4d84fe742e5b
I0607 08:43:57.689946    2920 downloader.go:150] Unregistering peer 33ea4d84fe742e5b
I0607 08:44:01.380826    2920 downloader.go:368] Peer (33ea4d84fe742e5b) didn't respond in time for hash request
I0607 08:44:01.380826    2920 sync.go:113] Removing peer 33ea4d84fe742e5b: timeout
I0607 08:44:06.378436    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:44:06.378436    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:44:06.378436    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:44:09.768595    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:44:11.378493    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:44:11.378493    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:44:18.925162    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:44:26.378730    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:44:26.378730    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:44:26.378730    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:44:30.737835    2920 downloader.go:139] Registering peer 33ea4d84fe742e5b
I0607 08:44:31.379064    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:44:31.379064    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:44:31.379064    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:44:36.378983    2920 sync.go:102] Attempting synchronisation: 33ea4d84fe742e5b, 0x4ab81ed24be4099dc2b2e54750fd50ca5d7d7db99fe7f2db88cc5bd38a9db82e
I0607 08:44:36.378983    2920 downloader.go:219] Synchronizing with the network using: 33ea4d84fe742e5b
I0607 08:44:36.378983    2920 downloader.go:257] Downloading hashes (4ab81ed2) from 33ea4d84fe742e5b
I0607 08:44:36.921175    2920 downloader.go:150] Unregistering peer 33ea4d84fe742e5b
I0607 08:44:41.379619    2920 downloader.go:368] Peer (33ea4d84fe742e5b) didn't respond in time for hash request
I0607 08:44:41.379619    2920 sync.go:113] Removing peer 33ea4d84fe742e5b: timeout
I0607 08:44:58.972669    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:45:03.397957    2920 downloader.go:139] Registering peer 33ea4d84fe742e5b
I0607 08:45:06.378169    2920 sync.go:102] Attempting synchronisation: 33ea4d84fe742e5b, 0x4ab81ed24be4099dc2b2e54750fd50ca5d7d7db99fe7f2db88cc5bd38a9db82e
I0607 08:45:06.378169    2920 downloader.go:219] Synchronizing with the network using: 33ea4d84fe742e5b
I0607 08:45:06.378169    2920 downloader.go:257] Downloading hashes (4ab81ed2) from 33ea4d84fe742e5b
I0607 08:45:09.149966    2920 downloader.go:150] Unregistering peer 33ea4d84fe742e5b
I0607 08:45:11.378909    2920 downloader.go:368] Peer (33ea4d84fe742e5b) didn't respond in time for hash request
I0607 08:45:11.378909    2920 sync.go:113] Removing peer 33ea4d84fe742e5b: timeout
I0607 08:45:16.378848    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:45:16.378848    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:45:16.378848    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:45:21.378865    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:45:21.378865    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:45:21.378865    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:45:29.320638    2920 downloader.go:139] Registering peer a979fb575495b8d6
I0607 08:45:36.379731    2920 sync.go:102] Attempting synchronisation: a979fb575495b8d6, 0x2d45329bb5a88d179c85343852cbc48c6656072058f3109918c544f7ae9c854d
I0607 08:45:36.379731    2920 downloader.go:219] Synchronizing with the network using: a979fb575495b8d6
I0607 08:45:36.379731    2920 downloader.go:257] Downloading hashes (2d45329b) from a979fb575495b8d6
I0607 08:45:41.380689    2920 downloader.go:368] Peer (a979fb575495b8d6) didn't respond in time for hash request
I0607 08:45:41.380689    2920 sync.go:113] Removing peer a979fb575495b8d6: timeout
I0607 08:45:41.380689    2920 downloader.go:150] Unregistering peer a979fb575495b8d6
I0607 08:45:59.978001    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:46:06.378624    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:46:06.378624    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:46:06.378624    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:46:11.379613    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:46:11.379613    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:46:11.379613    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:46:29.052710    2920 downloader.go:139] Registering peer 33ea4d84fe742e5b
I0607 08:46:36.378543    2920 sync.go:102] Attempting synchronisation: 33ea4d84fe742e5b, 0x4ab81ed24be4099dc2b2e54750fd50ca5d7d7db99fe7f2db88cc5bd38a9db82e
I0607 08:46:36.378543    2920 downloader.go:219] Synchronizing with the network using: 33ea4d84fe742e5b
I0607 08:46:36.378543    2920 downloader.go:257] Downloading hashes (4ab81ed2) from 33ea4d84fe742e5b
I0607 08:46:36.778566    2920 downloader.go:150] Unregistering peer 33ea4d84fe742e5b
I0607 08:46:37.473221    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:46:41.378732    2920 downloader.go:368] Peer (33ea4d84fe742e5b) didn't respond in time for hash request
I0607 08:46:41.378732    2920 sync.go:113] Removing peer 33ea4d84fe742e5b: timeout
I0607 08:46:46.379753    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:46:46.379753    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:46:46.379753    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:46:51.380354    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:46:51.380354    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:46:51.380354    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:47:07.857091    2920 downloader.go:139] Registering peer a979fb575495b8d6
I0607 08:47:08.337998    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:47:16.379771    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:47:16.379771    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:47:16.379771    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:47:21.381127    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:47:21.381127    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:47:21.381127    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:47:25.030648    2920 downloader.go:139] Registering peer 33ea4d84fe742e5b
I0607 08:47:26.378270    2920 sync.go:102] Attempting synchronisation: 33ea4d84fe742e5b, 0x4ab81ed24be4099dc2b2e54750fd50ca5d7d7db99fe7f2db88cc5bd38a9db82e
I0607 08:47:26.378270    2920 downloader.go:219] Synchronizing with the network using: 33ea4d84fe742e5b
I0607 08:47:26.378270    2920 downloader.go:257] Downloading hashes (4ab81ed2) from 33ea4d84fe742e5b
I0607 08:47:31.379985    2920 downloader.go:368] Peer (33ea4d84fe742e5b) didn't respond in time for hash request
I0607 08:47:31.379985    2920 sync.go:113] Removing peer 33ea4d84fe742e5b: timeout
I0607 08:47:31.379985    2920 downloader.go:150] Unregistering peer 33ea4d84fe742e5b
I0607 08:47:36.378620    2920 sync.go:102] Attempting synchronisation: a979fb575495b8d6, 0x2d45329bb5a88d179c85343852cbc48c6656072058f3109918c544f7ae9c854d
I0607 08:47:36.378620    2920 downloader.go:219] Synchronizing with the network using: a979fb575495b8d6
I0607 08:47:36.378620    2920 downloader.go:257] Downloading hashes (2d45329b) from a979fb575495b8d6
I0607 08:47:38.578466    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:47:41.380116    2920 downloader.go:368] Peer (a979fb575495b8d6) didn't respond in time for hash request
I0607 08:47:41.380116    2920 sync.go:113] Removing peer a979fb575495b8d6: timeout
I0607 08:47:41.380116    2920 downloader.go:150] Unregistering peer a979fb575495b8d6
I0607 08:47:46.378648    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:47:46.378648    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:47:46.378648    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:47:51.380047    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:47:51.380047    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:47:51.380047    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:48:19.020791    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:48:21.419822    2920 downloader.go:139] Registering peer 33ea4d84fe742e5b
I0607 08:48:26.379927    2920 sync.go:102] Attempting synchronisation: 33ea4d84fe742e5b, 0x4ab81ed24be4099dc2b2e54750fd50ca5d7d7db99fe7f2db88cc5bd38a9db82e
I0607 08:48:26.379927    2920 downloader.go:219] Synchronizing with the network using: 33ea4d84fe742e5b
I0607 08:48:26.379927    2920 downloader.go:257] Downloading hashes (4ab81ed2) from 33ea4d84fe742e5b
I0607 08:48:26.692928    2920 downloader.go:150] Unregistering peer 33ea4d84fe742e5b
I0607 08:48:30.839420    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:48:31.380000    2920 downloader.go:368] Peer (33ea4d84fe742e5b) didn't respond in time for hash request
I0607 08:48:31.380000    2920 sync.go:113] Removing peer 33ea4d84fe742e5b: timeout
I0607 08:48:48.936778    2920 downloader.go:139] Registering peer a979fb575495b8d6
I0607 08:48:49.092761    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:48:56.379063    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:48:56.379063    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:48:56.379063    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:48:56.971416    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:49:01.379640    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:49:01.379640    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:49:06.379048    2920 sync.go:102] Attempting synchronisation: a979fb575495b8d6, 0x2d45329bb5a88d179c85343852cbc48c6656072058f3109918c544f7ae9c854d
I0607 08:49:06.379048    2920 downloader.go:219] Synchronizing with the network using: a979fb575495b8d6
I0607 08:49:06.379048    2920 downloader.go:257] Downloading hashes (2d45329b) from a979fb575495b8d6
I0607 08:49:11.380462    2920 downloader.go:368] Peer (a979fb575495b8d6) didn't respond in time for hash request
I0607 08:49:11.380462    2920 sync.go:113] Removing peer a979fb575495b8d6: timeout
I0607 08:49:11.380462    2920 downloader.go:150] Unregistering peer a979fb575495b8d6
I0607 08:49:19.602761    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:49:26.378689    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:49:26.378689    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:49:26.378689    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:49:31.216928    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:49:31.378712    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:49:31.378712    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:49:55.724468    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:49:56.379856    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:49:56.379856    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:49:56.379856    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:50:01.381700    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:50:01.381700    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:50:01.381700    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:50:27.499856    2920 downloader.go:139] Registering peer a979fb575495b8d6
I0607 08:50:27.635863    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:50:35.598177    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:50:36.378044    2920 sync.go:102] Attempting synchronisation: a979fb575495b8d6, 0x2d45329bb5a88d179c85343852cbc48c6656072058f3109918c544f7ae9c854d
I0607 08:50:36.378044    2920 downloader.go:219] Synchronizing with the network using: a979fb575495b8d6
I0607 08:50:36.378044    2920 downloader.go:257] Downloading hashes (2d45329b) from a979fb575495b8d6
I0607 08:50:41.378640    2920 downloader.go:368] Peer (a979fb575495b8d6) didn't respond in time for hash request
I0607 08:50:41.378640    2920 sync.go:113] Removing peer a979fb575495b8d6: timeout
I0607 08:50:41.378640    2920 downloader.go:150] Unregistering peer a979fb575495b8d6
I0607 08:50:58.177298    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:51:06.103465    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:51:38.241373    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:51:46.321171    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:52:08.578095    2920 downloader.go:139] Registering peer a979fb575495b8d6
I0607 08:52:08.730090    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:52:16.378544    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:52:16.378544    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:52:16.378544    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:52:21.379593    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:52:21.379593    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:52:21.379593    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:52:26.378755    2920 sync.go:102] Attempting synchronisation: a979fb575495b8d6, 0x2d45329bb5a88d179c85343852cbc48c6656072058f3109918c544f7ae9c854d
I0607 08:52:26.378755    2920 downloader.go:219] Synchronizing with the network using: a979fb575495b8d6
I0607 08:52:26.378755    2920 downloader.go:257] Downloading hashes (2d45329b) from a979fb575495b8d6
I0607 08:52:31.378875    2920 downloader.go:368] Peer (a979fb575495b8d6) didn't respond in time for hash request
I0607 08:52:31.378875    2920 sync.go:113] Removing peer a979fb575495b8d6: timeout
I0607 08:52:31.378875    2920 downloader.go:150] Unregistering peer a979fb575495b8d6
I0607 08:52:39.238654    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:52:46.378579    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:52:46.378579    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:52:46.378579    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:52:46.639581    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:52:51.379381    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:52:51.379381    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:53:18.734306    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:53:26.378345    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:53:26.378345    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:53:26.378345    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:53:28.707578    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:53:31.380043    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:53:31.380043    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:53:49.129597    2920 downloader.go:139] Registering peer a979fb575495b8d6
I0607 08:53:49.269606    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:53:56.378824    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:53:56.378824    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:53:56.378824    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:53:56.691917    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:54:01.379745    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:54:01.379745    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:54:06.378371    2920 sync.go:102] Attempting synchronisation: a979fb575495b8d6, 0x2d45329bb5a88d179c85343852cbc48c6656072058f3109918c544f7ae9c854d
I0607 08:54:06.378371    2920 downloader.go:219] Synchronizing with the network using: a979fb575495b8d6
I0607 08:54:06.378371    2920 downloader.go:257] Downloading hashes (2d45329b) from a979fb575495b8d6
I0607 08:54:11.378576    2920 downloader.go:368] Peer (a979fb575495b8d6) didn't respond in time for hash request
I0607 08:54:11.378576    2920 sync.go:113] Removing peer a979fb575495b8d6: timeout
I0607 08:54:11.378576    2920 downloader.go:150] Unregistering peer a979fb575495b8d6
I0607 08:54:29.268991    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:54:32.456903    2920 downloader.go:139] Registering peer 33ea4d84fe742e5b
I0607 08:54:36.378394    2920 sync.go:102] Attempting synchronisation: 33ea4d84fe742e5b, 0x4ab81ed24be4099dc2b2e54750fd50ca5d7d7db99fe7f2db88cc5bd38a9db82e
I0607 08:54:36.378394    2920 downloader.go:219] Synchronizing with the network using: 33ea4d84fe742e5b
I0607 08:54:36.378394    2920 downloader.go:257] Downloading hashes (4ab81ed2) from 33ea4d84fe742e5b
I0607 08:54:38.446357    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:54:38.905861    2920 downloader.go:150] Unregistering peer 33ea4d84fe742e5b
I0607 08:54:41.378818    2920 downloader.go:368] Peer (33ea4d84fe742e5b) didn't respond in time for hash request
I0607 08:54:41.378818    2920 sync.go:113] Removing peer 33ea4d84fe742e5b: timeout
I0607 08:54:59.815439    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:55:06.379180    2920 sync.go:102] Attempting synchronisation: de471bccee3d0422, 0x8a9d241d82070ff8b85b7c0046754ae54091ac854aa19691bae8ea2f96905edc
I0607 08:55:06.379180    2920 downloader.go:219] Synchronizing with the network using: de471bccee3d0422
I0607 08:55:06.379180    2920 downloader.go:257] Downloading hashes (8a9d241d) from de471bccee3d0422
I0607 08:55:08.516312    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:55:11.380056    2920 downloader.go:368] Peer (de471bccee3d0422) didn't respond in time for hash request
I0607 08:55:11.380056    2920 sync.go:113] Removing peer de471bccee3d0422: timeout
I0607 08:55:29.544981    2920 downloader.go:139] Registering peer 33ea4d84fe742e5b
I0607 08:55:30.437758    2920 downloader.go:139] Registering peer de471bccee3d0422
I0607 08:55:36.378532    2920 sync.go:102] Attempting synchronisation: 33ea4d84fe742e5b, 0x4ab81ed24be4099dc2b2e54750fd50ca5d7d7db99fe7f2db88cc5bd38a9db82e
I0607 08:55:36.378532    2920 downloader.go:219] Synchronizing with the network using: 33ea4d84fe742e5b
I0607 08:55:36.378532    2920 downloader.go:257] Downloading hashes (4ab81ed2) from 33ea4d84fe742e5b
I0607 08:55:36.675579    2920 downloader.go:150] Unregistering peer 33ea4d84fe742e5b
I0607 08:55:38.746272    2920 downloader.go:150] Unregistering peer de471bccee3d0422
I0607 08:55:41.379450    2920 downloader.go:368] Peer (33ea4d84fe742e5b) didn't respond in time for hash request
I0607 08:55:41.379450    2920 sync.go:113] Removing peer 33ea4d84fe742e5b: timeout

**Comment by MercStills** [comment]
Similar situation for me.  net.peerCount will steadily drop over time as, I'm assuming, peers getting banned for either reaching the timeout threshold or giving bad hash info or whatever else is going on from TX spamming and stress testing.

Restarting my node will get me back in sync but I'll need to restart again within an hour.

**Comment by oliverkx** [comment]
Running geth 0.9.27 as well here. Restarting often. Sometimes restart gets me back on track (that's been pretty rare lately), sometimes it DLs blocks at a steady pace, but always some number of blocks behind what is posted on stats.ethdev - anywhere from 10 to 150, currently about 30. An sometimes it fails to DL anything at all.

I am way out of my league code-wise here, but I imagine that most of the time, the peers I connect to are in the same state of disarray as I am myself, and their "best block" is way behind the overall network's best block.

I am wondering where geth is trying to get its list of peers from. Are those written into the block-chain? i.e. does it pick the miners of the last X blocks on the chain to become its preferred peers?

**Comment by fjl** [comment]
There is an issue in the p2p layer that causes many connections to fail.
We are fixing the issue right now and it will be part of the next geth release.

> I am wondering where geth is trying to get its list of peers from. Are those written into the block-chain? i.e. does it pick the miners of the last X blocks on the chain to become its preferred peers?

https://github.com/ethereum/go-ethereum/wiki/Connecting-to-the-network#how-peers-are-found

**Comment by simondlr** [comment]
@fjl has this been implemented yet?

**Comment by fjl** [comment]
@simondlr The issue that I mentioned was unrelated to #1338 and has been resolved.
