### ISSUE TITLE
Ｉ think I miner the longer chain

### ISSUE THREAD

**Issue by pureland** [ethereum/go-ethereum#1201]
I0608 22:14:18.774305    1493 worker.go:364] � �  Mined 5 blocks back: block #556971
I0608 22:14:53.772312    1493 chain_manager.go:664] imported 1 block(s) (0 queued 0 ignored) in 1.753235ms. #556977 [b436335b / b436335b]
I0608 22:14:59.540384    1493 worker.go:413] commit new work on block 556978 with 0 txs & 0 uncles
I0608 22:14:59.540716    1493 worker.go:364] � �  Mined 5 blocks back: block #556972
I0608 22:15:41.362342    1493 chain_manager.go:664] imported 1 block(s) (0 queued 0 ignored) in 2.201071ms. #556978 [37366338 / 37366338]
I0608 22:15:51.702170    1493 worker.go:413] commit new work on block 556979 with 0 txs & 0 uncles
I0608 22:15:51.702515    1493 worker.go:364] � �  Mined 5 blocks back: block #556973
I0608 22:17:26.730680    1493 chain_manager.go:664] imported 1 block(s) (0 queued 0 ignored) in 1.838818ms. #556979 [7e0b9e6f / 7e0b9e6f]
I0608 22:17:45.377384    1493 worker.go:413] commit new work on block 556980 with 0 txs & 0 uncles
I0608 22:17:45.377569    1493 worker.go:364] � �  Mined 5 blocks back: block #556974
I0608 22:18:38.086967    1493 chain_manager.go:664] imported 1 block(s) (0 queued 0 ignored) in 2.077371ms. #556980 [dff4977a / dff4977a]
I0608 22:18:46.462833    1493 worker.go:413] commit new work on block 556981 with 0 txs & 0 uncles
I0608 22:18:54.923792    1493 chain_manager.go:664] imported 1 block(s) (0 queued 0 ignored) in 2.036891ms. #556981 [9452f9d9 / 9452f9d9]
I0608 22:19:02.953955    1493 worker.go:413] commit new work on block 556982 with 0 txs & 0 uncles
I0608 22:21:56.868680    1493 chain_manager.go:664] imported 1 block(s) (0 queued 0 ignored) in 1.921633ms. #556982 [52acdc64 / 52acdc64]
I0608 22:21:56.869046    1493 worker.go:256] �  Mined block (#556982 / 52acdc64). Wait 5 blocks for confirmation
I0608 22:22:11.713335    1493 worker.go:413] commit new work on block 556983 with 0 txs & 0 uncles
I0608 22:24:39.625873    1493 chain_manager.go:664] imported 1 block(s) (0 queued 0 ignored) in 2.523729ms. #556983 [d44311d2 / d44311d2]
I0608 22:24:54.884603    1493 worker.go:413] commit new work on block 556984 with 0 txs & 0 uncles

**Comment by karalabe** [comment]
Please update to the latest geth develop. This has been fixed.
