### ISSUE TITLE
High load on network

### ISSUE THREAD

**Issue by larspensjo** [ethereum/go-ethereum#1205]
When I am running geth 0.9.27 (Ubuntu), it somehow loads my internet connection very badly.

The total upload and download is small, however. I have 10 MByte/s, and the upload and download are around 100 kByte/s. But using ping I can get response times for over 500 ms. Immediately when I shut geth down, the ping response time goes down to less than 50 ms.

I don't think the problem is new with 0.9.27.

**Comment by fjl** [comment]
geth performs many TCP connection attempts and sends many UDP packets.
I will try to reproduce this. You can help by capturing traffic with wireshark. An ideal capture would be one
where you start capturing before geth and ping are started. Start ping and wait 20 seconds before starting geth, leave it running for a while and stop it again.

**Comment by larspensjo** [comment]
Added wireshark. For the moment, the network load is not a problem, and I can see no effect on ping times. So I don't know if the problem has gone away, or if there is some circumstance where it happens.

When it happens, and I am not at home, one of my sons sometimes play shooter games that depends a lot on ping. If so, they shut down my computer :-(
