### ISSUE TITLE
solc not found, can't set

### ISSUE THREAD

**Issue by step21** [ethereum/go-ethereum#1208]
Althouhg it is now in path, geth doesn't find solc. eth.getCompilers is ''
admin.setSolc doesn't work, exits with "admin.setSolc("/usr/local/bin/solc")
fork/exec /usr/local/bin/solc: cannot allocate memory
false"
Any idea why that could be? When I try to set the solc path on the commandline, there is not error, but it also doesn't work.
This is on Ubuntu 14.04, latest geth 0.9.27 from ppa

**Comment by karalabe** [comment]
Well, to me the error message would seem to indicate that you exhausted your OS memory? Are you sure you have enough?

**Comment by step21** [comment]
Well, as there are no official system requirements posted, how do I know?
This is on a digital ocean node. I agree that it probably would not have enough for mining, but as this node is not mining ... it has currently 1 GB and runs only ssh and geth, no other services apart from what is necessary for the OS.

**Comment by zelig** [comment]
Please try with more memory, then it will work. 
If you think the memory usage is unreasonable, please submit another issue some more info about the platform, OS, memory status, and a stacktrace before you do `admin.setSolc("/usr/local/bin/solc")`.
