### ISSUE TITLE
Additional type field in solidity logs

### ISSUE THREAD

**Issue by debris** [ethereum/go-ethereum#1229]
solidity logs [should have](https://github.com/ethereum/cpp-ethereum/issues/1997#issuecomment-106797597) additional field `type`. [docs](https://github.com/ethereum/wiki/wiki/JSON-RPC#returns-39)

> `type`: STRING - `pending` when the log is pending. `mined` if log is already mined.

**Comment by tgerring** [comment]
Why is this necessary? Can't this be inferred from the blockNumber/blockHash as null?

**Comment by debris** [comment]
> Can't this be inferred from the blockNumber/blockHash as null?

It can. In my opinion it's just cleaner and more readable to have `type` field.
