### ISSUE TITLE
SEC-45 DoS in hash downloader 

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#1231]
The cross-check is not enough to limit a malicious peer from DoSing a node. An attacker can construct a "valid" chain of hashes and keep sending them to a node while caching enough blocks to satisfy cross-checks (which do not fully validate blocks).

This causes the node to eventually run out of memory as it keeps all hashes downloaded from a peer.

Related: https://github.com/ethereum/wiki/wiki/Proposal:-BlockHashesFromNumbers

Related but distinct DoS (affects peer logic/reputation):

When a node is syncing up to a longer chain from an attacker, there is a time window between receiving NewBlockMsg and the point where the downloader decides the peer is bad.

In this window, if the bad peer advertises a block which we do not have the parentHash for, the node will go into synchronization. If the bad peer disconnects, re-connects and repeats the bad block advertising, it will DoS the node and interrupt it indefinitely, preventing it from switching downloading to another peer.

We need to find a way to accept blocks from peers other than the "best" peer based on advertised (but not validated) TD, such that this type of attack is not effective for longer than a short time period.

**Comment by karalabe** [comment]
As mentioned in both the above mentioned proposal and in SE-45 too, the only way to be able to circumvent this attack is to support some mechanism to query hashes/blocks upwards from out current position. There are two issues to be solved here:

 - [ ] Add a mechanism to figure out the common ancestor between our chain and a remote peer's chain. Essentially we require a binary search over out own block chain, querying the remote peer if it has the specific block or not. This can be done cleanly using a new packet, or hackishly by issuing hash requests of length 1. However, I'm not sure the hash request protocol message has all the guarantees that we would need (i.e. return only from the canonical chain) to satisfy this algorithm, so there may be a need for protocol extensions.
 - [ ] Add a mechanism to be able to query some data (block/hash) upwards from a given position/hash. The simplest and most non intrusive extension would be the addition of a new flag to the get hashes message, specifying whether the hashes should be retrieved downwards or upwards the chain.

If we can introduce the necessary changes for upwards chain reconstruction, I don't really see the need either for parallel hash downloads (hashes will load instantly compared to blocks), nor do I see complicating the status messages with chain heights, and the likes and required by the OP linked proposal

**Comment by Gustav-Simonsson** [comment]
@karalabe added a second distinct but related DoS to the description

**Comment by karalabe** [comment]
@Gustav-Simonsson actually, the attack is not that feasible. There is a 30 second connection timeout in the network layer. You cannot connect more often than once per 30 sec, so to execute this attack, you would need to rotate your peer identities.

However, maybe the fix to the first issue would also be a fix to this second. We should probably first roll out the fix and then look at this second issue again.
