### ISSUE TITLE
SEC-46 Sanitise all ethash input

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#1232]
Currently we have two ethash input vulnerabilities:

- [x] Difficulty must be validated to be positive before used for calculations. Currently an attacker can send a block with zero difficulty and ethash.go will panic on divide by zero. See https://github.com/ethereum/ethash/blob/master/ethash.go#L127

- [x] Block number is not validated. If an attacker sends a block number which is outside the supported epochs of ethash, it will trigger an assert, effectively DoSing a node.

**Comment by obscuren** [comment]
see https://github.com/ethereum/go-ethereum/issues/1225

**Comment by Gustav-Simonsson** [comment]
https://github.com/ethereum/go-ethereum/pull/1329
