### ISSUE TITLE
Ctrl+C shutdown hang?

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#1233]
I've been fully in sync and running a node for about 2 hours, then decided to stop geth, and Ctrl+C wouldn't terminate it. After waiting a bit, I've decided to abort it to maybe see where it's stuck. If anyone has some ideas, do share:

https://gist.github.com/karalabe/f2dd24b79dc4ffa8d229

**Comment by joeykrug** [comment]
No ideas, but I can confirm this bug

**Comment by veox** [comment]
Cannot reproduce on current `develop` (4bb9a61049882f427e2742773c69b969849da1c2).

Does this happen after some time (e.g. 2 hours) or always?

**Comment by karalabe** [comment]
Rarely, that's why I attached the abort dump, to have an idea where the goroutines are stuck. It's most probably a rare data race.

**Comment by fjl** [comment]
It does not happen very often. The trace shows that a bunch of network message sends are waiting for their turn. One of the sending goroutines is in `I/O wait` state and would unblock the others when it finished. I suspect that this could be a rare failure where the write deadline is ineffective for some reason.

For reference, most goroutines in the trace are [stuck here](https://github.com/ethereum/go-ethereum/blob/4bb9a61049882f427e2742773c69b969849da1c2/p2p/rlpx.go#L73).

**Comment by jorisbontje** [comment]
geth develop 6f5c615 taking multiple minutes to shut down after Ctrl+C:

```
I0615 12:41:38.385962    2545 chain_manager.go:698] imported 1 block(s) (0 queued 0 ignored) including 75 txs in 167.661748ms. #606203 [b129ea86 / b129ea86]
^CI0615 12:41:44.653669    2545 cmd.go:60] Shutting down (interrupt) ...
I0615 12:45:39.051153    2545 chain_manager.go:526] Chain manager stopped
I0615 12:45:39.051213    2545 handler.go:136] Stopping ethereum protocol handler...
I0615 12:45:39.051234    2545 handler.go:146] Ethereum protocol handler stopped
I0615 12:45:39.051244    2545 transaction_pool.go:108] TX Pool stopped
I0615 12:45:39.051257    2545 backend.go:616] Automatic pregeneration of ethash DAG OFF (ethash dir: /Users/mids/.ethash)
I0615 12:45:39.052013    2545 database.go:78] flushed and closed db: /Users/mids/Library/Ethereum/blockchain
I0615 12:45:39.052514    2545 database.go:78] flushed and closed db: /Users/mids/Library/Ethereum/state
I0615 12:45:39.052676    2545 database.go:78] flushed and closed db: /Users/mids/Library/Ethereum/extra
```

**Comment by fjl** [comment]
The linked PR (part of release 0.9.30) should accelerate shutdown. Please test.

**Comment by joeykrug** [comment]
New version works swell for me!
