### ISSUE TITLE
miner getGasPrice

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1244]
Geth console has miner.setGasPrice()
Seems it would be helpful to also have something like getGasPrice() or a more generic minerInfo().  getExtra() may also be desired.  (If this information is already somewhere, it isn't findable easily.)

**Comment by obscuren** [comment]
This won’t be added to the “old” console. @bas-vk please add this to the new console.

**Comment by fjl** [comment]
@bas-vk ping ;)

**Comment by obscuren** [comment]
@bas-vk please get this added for 1.0.2

**Comment by bas-vk** [comment]
This method was added a long time ago.
