### ISSUE TITLE
getChainSyncStatus returns undefined

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#1247]
```
> admin.getChainSyncStatus()
undefined
```

**Comment by bas-vk** [comment]
This is by design since this call returns data without changing the internal state in geth.
That's why it has been changed (previously known as `admin.progress()`) to a property.

```
> admin.chainSyncStatus
{
  blocksAvailable: 1,
  blocksWaitingForImport: 0,
  estimate: '0',
  importing: 0
}
> 
```

**Comment by obscuren** [comment]
Right. Please get rid of these confusing functions :-)

**Comment by frozeman** [comment]
The function are automatically created in web3 js for each property, to allow using properties asynchronously:
```
> admin.getChainSyncStatus(function(){e, res}{
     console.log(res);
     /* {
     blocksAvailable: 1,
     blocksWaitingForImport: 0,
     estimate: '0',
     importing: 0
     } */
})
```

This is a feature, otherwise you would have lags in interfaces using sync properties (but you could use sync properties in node).

**Comment by frozeman** [comment]
To explain a little more:

Properties use getter and setter functions, which are by nature synchronous, so we had to introduce these additional functions to allow passing callbacks and use properties async.

See all the property docs: https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcoinbase

**Comment by obscuren** [comment]
Ooooh, I see. Thanks :+1:
