### ISSUE TITLE
feature request console: vmdebug output

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1250]
On gitter I asked:
is there a way to see VM output with geth console ?
or do i have to restart geth console with --vmdebug ?
obscuren said: @ethers could you create an issue with "feature request console" and put that in

For more info, I imagine in the geth console, a way to run a transaction and see the VM output: something like sendTransaction but it would print the VM steps, gas costs, etc.

**Comment by ethers** [comment]
Another request: if geth console could require Ctrl-C 2 times, before shutting down.  It's too easy to accidentally shut it down: when typing a wrong command, to clear it, it is easy to press Ctrl-C (out of habit)

**Comment by ethers** [comment]
the suggestion about Ctrl-C was filed again as #1573

**Comment by obscuren** [comment]
The ctrl-c will be in `1.0.2`. Console `<C-c>` is clear line `<C-d>` is quite.

**Comment by fjl** [comment]
This is now available on the develop branch, use `debug.replayTransaction`.

**Comment by obscuren** [comment]
Which will be renamed to `debug.transaction` in https://github.com/ethereum/go-ethereum/pull/2141
