### ISSUE TITLE
.password flag doesn't work in conjunction with --unlock

### ISSUE THREAD

**Issue by tinybike** [ethereum/go-ethereum#1258]
I'm trying to start geth (v 0.9.29) unlocked with a password stored in a plain text file (the file name is `.password`, stored in the data directory):
```
jack@vent:~/.ethereum$ geth --unlock primary --password .password
I0613 17:02:50.629035    5713 backend.go:256] Protocol Version: 60, Network Id: 0
I0613 17:02:50.629088    5713 backend.go:266] Blockchain DB Version: 3
I0613 17:02:50.631455    5713 chain_manager.go:255] Last block (#555185) 629ee3d578d79b57985493fccd02198c5cc504b8358b080ce1e0705682162f92 TD=3087146347010374
I0613 17:02:51.262343    5713 cmd.go:148] Starting Geth/v0.9.29/linux/go1.4.2
I0613 17:02:51.262447    5713 server.go:293] Starting Server
I0613 17:02:52.695901    5713 udp.go:189] Listening, enode://2bd88c5e9d27eb06b299c6895b2417ef926707860862040569fb8833fe10ff6c719c84d5c26d63b8f988c0798f74d3803cdbe37480f5854390e26ebcdb9293a0@[::]:30303
I0613 17:02:52.696284    5713 backend.go:475] Server started
I0613 17:02:52.696271    5713 server.go:530] Listening on [::]:30303
Fatal: Unlock account failed 'Decryption failed: MAC mismatch'
```
I've double-checked that the password is correct.  (Also have tried using a full path, which also doesn't help.)  This bug only appears when using `--password` in conjunction with `--unlock`; either option works fine by itself.

Related: which account does `--password` unlock (if any), if you don't specify an account via the `--unlock` flag?  Does it automatically select the etherbase account?  If so, I think in some cases that will be undesirable behavior.

**Comment by zelig** [comment]
```bash
./geth --datadir /tmp/unlock.test --password <(echo -n '1234') account new
# Address: {0xd8e608ae9f160dd54253ca26e5295dc1dbf75982}
./geth --datadir /tmp/unlock.test --password <(echo -n '1234') --unlock primary js <(echo "console.log(eth.getBalance(eth.accounts[0]));") 2> /tmp/unlock.test.log
# Account '0xd8e608ae9f160dd54253ca26e5295dc1dbf75982' unlocked.
# 0
```

i have a suspicion. you know `echo` puts a new line at the end of its output. So if your password is '1234' that won't match "1234\n". So you need to use `<(echo -n 1234)`. Check maybe your plaintext file had a trailing newline too. Implementation is trivial and always worked. :)

**Comment by tinybike** [comment]
Yep, this fixed it!  Good call.  (My suggestion: make it automatically strip the newline from the end of the password.  Not a bug, though, so closing this issue.)
