### ISSUE TITLE
eth: optimise initial transaction sync

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#1262]
Under normal conditions, most nodes will have the current transactions in their pool.
When a connection starts up, all current transactions are sent in both directions.

We can mimise the amount of transactions sent by tracking which txs where sent by the remote side
and excluding those from the initial sync. If transactions to send were picked randomly, this would
ensure that most transactions would only be sent once.

**Comment by karalabe** [comment]
@fjl This has been done, right?

**Comment by fjl** [comment]
No. Not yet.
