### ISSUE TITLE
SEC-47 Block header mixdigest field not validated

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#1264]
The mixdigest field is not validated. This causes malleability which allows an attacker to include a block as an uncle multiple times by changing the mixdigest.

- [ ] Modify Ethash Verify to return the mixdigest: https://github.com/ethereum/ethash/blob/master/ethash.go#L100
- [ ] Verify that mixdigest in block header is the same as what is returned from Ethash Verify for the block: https://github.com/ethereum/go-ethereum/blob/develop/core/block_processor.go#L266

**Comment by Gustav-Simonsson** [comment]
@CJentzsch Could you add BlockTests for this?

**Comment by Gustav-Simonsson** [comment]
https://github.com/ethereum/go-ethereum/pull/1274

**Comment by CJentzsch** [comment]
new tests in bcInvalidHeaderTest.json and bcUncleHeaderValiditiy.json for correct nonce/mixHash in block header and uncles are pushed.
