### ISSUE TITLE
Geth started as service on rasbperry pi does not appear to be downloading.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/go-ethereum#1268]
I have a Rasbperry PI running geth. As it is inconvenient to physically access the pi, I use ssh to connect to it almost exclusively. Because of this, I can't run geth in the ssh shell (or it would close on disconnect) so I have it run in the background as a systemd service.

geth *seems* to be running in this way, or at least ps claims it is. I don't know what it's doing, because when I SIGTERM it doesn't seem to have downloaded a single block. Attempting to access it via standalone console gives:
```
Fatal: Unable to determine supported api's: dial unix /home/pi/.ethereum/geth.ipc: connection refused
Fatal: Unable to determine supported api's: dial unix /home/pi/.ethereum/geth.ipc: connection refused
```

This is my .service file, by the way.
```
Unit]

Description=Geth Ethereum node

After=network.target

[Service]

Type=simple

ExecStart=/home/pi/go-ethereum/build/bin/geth

User=pi

RemainAfterExit=true

[Install]

WantedBy=multi-user.target
```

**Comment by obscuren** [comment]
@bas-vk

**Comment by Smithgift** [comment]
I have more information.

I tried using the startup script, and left it going (having logged off in the mean time.) When I came back to examine it again via standalone console, it seems that it had not been updating at all. In fact, it seems to be syncing only while the console is open.

I'm trying clearing the blockchain now. Maybe the database got corrupted somehow.
