### ISSUE TITLE
admin.contractInfo.saveInfo() missing.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/go-ethereum#1276]
This function, as described by the wiki in multiple places, does not exist in either the standalone or built-in JS console.

**Comment by zelig** [comment]
@Smithgift Apologies, the docs reflect a state which has not been released yet, please use the old way which does info-extraction, calculate content hash and register it to the contract's address in one step. As in the examples https://github.com/ethereum/go-ethereum/wiki/Contracts-and-Transactions/
```
contenthash = admin.contractInfo.register(sender, contractaddress, contract, filename)
```

This is gonna change from next week to

```
contenthash = admin.contractInfo.saveInfo(contract.info, filename)
admin.contractInfo.register(primaryAccount, address, contenthash)
```
or
 
```
contenthash = bzz.put(contract.info)
admin.contractInfo.register(primaryAccount, address, contenthash)
```

if you wanna use bzz (once it is in), in which case this also deploys the info block to the swarm.

Watch #1272
Closing

**Comment by ethers** [comment]
@Smithgift were you able to get working using `register` ?

**Comment by Smithgift** [comment]
@ethers Almost. I ran into two issues.

#1293 - Short URLs don't work.
#1294 - The results mismatch.

**Comment by ethers** [comment]
@Smithgift Thanks I'll keep an eye (still trying to figure it out).  Also, not sure if you're aware of https://gitter.im/ethereum/go-ethereum in case you have other questions.
