### ISSUE TITLE
Strange behavior downloading block  - (I was on Geth 9.28)

### ISSUE THREAD

**Issue by jmiehau** [ethereum/go-ethereum#1277]
Please watch the behavior of the console regarding block numbers from the last lines of today around 15:53h

Logs:
https://gist.githubusercontent.com/jmiehau/089209d1152643777861/raw/gistfile1.txt

Already I did the upgrade to ethereum-0.9.30-60.yosemite.bottle.161.tar.gz after I saw Jeff post.

Example:
I0616 15:53:29.965269   12859 chain_manager.go:690] imported 0 block(s) (0 queued 1 ignored) including 0 txs in 4.025982ms. #615895 [3643bf04 / 3643bf04]
I0616 15:53:29.968864   12859 chain_manager.go:690] imported 0 block(s) (0 queued 1 ignored) including 0 txs in 3.523238ms. #615895 [3643bf04 / 3643bf04]
I0616 15:57:14.695222   12859 chain_manager.go:690] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 922.391006ms. #1 [c86d770c / c86d770c]
I0616 15:57:16.832778   12859 chain_manager.go:690] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 3.647408ms. #1 [0bf2554b / 0bf2554b]
I0616 15:58:56.014512   12859 chain_manager.go:690] imported 1 block(s) (0 queued 0 ignored) including 55 txs in 5.704417526s. #615874 [8cb2b62e / 8cb2b62e]
I0616 16:01:39.801541   12859 chain_manager.go:690] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 1.009282751s. #24443 [76dd0fee / 76dd0fee]
I0616 16:01:39.806173   12859 chain_manager.go:690] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.532645ms. #24443 [a534f46d / a534f46d]
I0616 16:01:41.644061   12859 chain_manager.go:690] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.108313ms. #24443 [72cfe3de / 72cfe3de]
I0616 16:01:44.943282   12859 chain_manager.go:690] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 3.911892ms. #24443 [47042254 / 47042254]
I0616 16:01:47.378305   12859 chain_manager.go:690] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 3.87261ms. #24443 [cb552ec9 / cb552ec9]
I0616 16:01:53.469707   12859 chain_manager.go:690] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.307504ms. #24443 [81379dea / 81379dea]
I0616 16:02:12.461779   12859 chain_manager.go:690] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 915.262814ms. #30587 [b4c3d3f9 / b4c3d3f9]

**Comment by karalabe** [comment]
I've also noticed this. There isn't any issue in by itself, the weird blocks are not downloaded by your machine but rather are propagated **to** your machine by remote nodes. Whether the propagating node is malicious or not I cannot tell (inclined to believe so because the block numbers are all the same with different hashes).

However, I'll leave this issue open since I think it demonstrates the need to filter out very old propagated blocks even if they could otherwise be imported correctly into the chain. It should be the responsibility of the downloader to pull in large forks and not the propagation. Hopefully I can address this some time tomorrow.

**Comment by karalabe** [comment]
Could you please check on latest develop if this issue still persists? We're now discarding any propagated blocks that are outside some valid range from our chain's head (7 blocks back, 256 (for now) future). If it doesn't, I think we can close this.

**Comment by jmiehau** [comment]
Yes, please find logs from Geth 9.30 https://gist.github.com/jmiehau/22d02903b3ce09d74c50

I think it works well, thank you Péter
