### ISSUE TITLE
Transaction w/ invalid nonce

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#1286]
I0617 15:12:24.450265    9863 backend.go:269] Protocol Version: 60, Network Id: 0
I0617 15:12:24.450590    9863 backend.go:279] Blockchain DB Version: 3
I0617 15:12:24.565654    9863 chain_manager.go:247] Last block (#620351) a129b83702e1cb15b4c8e81f7a294e631727e31ecdd658e95308a6b760db9fde TD=4888363548227635
I0617 15:21:20.003084    9863 cmd.go:148] Starting Geth/v0.9.31/linux/go1.4.2
I0617 15:21:20.431191    9863 server.go:293] Starting Server
I0617 15:21:20.980993    9863 nat.go:95] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-IP1
I0617 15:21:23.801579    9863 udp.go:189] Listening, enode://ff70d47d170247a53c547a3eba4a68c2c3bb2f0c95c010b365cbe118edde2aae7bc18e43e5c3f9c9b6e2224b21f5a3e64960613f1b0eb146664433ba79f39788@76.110.55.144:30303
I0617 15:21:23.801785    9863 backend.go:494] Server started
I0617 15:21:23.801792    9863 server.go:530] Listening on [::]:30303
I0617 15:21:23.802016    9863 nat.go:95] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-IP1
I0617 15:21:23.903328    9863 ipc_unix.go:74] IPC service started (/home/rfikki/.ethereum/geth.ipc)
I0617 15:21:33.802591    9863 downloader.go:246] Block synchronisation started
I0617 15:24:21.985200    9863 chain_manager.go:801] Bad block #620352 (3eaa4356494af93fa37686e058a2bde6089e99b7ac54a064270db8a69898b1ac)
I0617 15:24:21.985248    9863 chain_manager.go:802] Transaction w/ invalid nonce. tx=66966  state=0)
I0617 15:24:21.985357    9863 downloader.go:222] Synchronisation failed: block downloading canceled (requested)
I0617 15:24:34.461475    9863 chain_manager.go:801] Bad block #620352 (3eaa4356494af93fa37686e058a2bde6089e99b7ac54a064270db8a69898b1ac)
I0617 15:24:34.461524    9863 chain_manager.go:802] Transaction w/ invalid nonce. tx=66966  state=0)
I0617 15:24:34.461617    9863 downloader.go:222] Synchronisation failed: block downloading canceled (requested)
I0617 15:24:58.143639    9863 chain_manager.go:801] Bad block #620352 (3eaa4356494af93fa37686e058a2bde6089e99b7ac54a064270db8a69898b1ac)
I0617 15:24:58.143683    9863 chain_manager.go:802] Transaction w/ invalid nonce. tx=66966  state=0)
I0617 15:24:58.143735    9863 downloader.go:222] Synchronisation failed: block downloading canceled (requested)
I0617 15:25:08.735825    9863 chain_manager.go:801] Bad block #620352 (3eaa4356494af93fa37686e058a2bde6089e99b7ac54a064270db8a69898b1ac)
I0617 15:25:08.735871    9863 chain_manager.go:802] Transaction w/ invalid nonce. tx=66966  state=0)

**Comment by obscuren** [comment]
Any previous crashes? Manual resets using `setHead`?

**Comment by rfikki** [comment]
No previous crashes. Tried with admin.setHead option and same error:

I0618 10:21:02.718198    2724 chain_manager.go:801] Bad block #625306 (3ceb5410b74ebac152c6489f0ff3f021ce56cf418a1ddcab59b7598ae706d848)
I0618 10:21:02.718198    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=98354  state=0)
I0618 10:21:02.718198    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:21:10.280630    2724 chain_manager.go:801] Bad block #625306 (3ceb5410b74ebac152c6489f0ff3f021ce56cf418a1ddcab59b7598ae706d848)
I0618 10:21:10.280630    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=98354  state=0)
I0618 10:21:10.280630    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:21:58.845655    2724 chain_manager.go:801] Bad block #625306 (3ceb5410b74ebac152c6489f0ff3f021ce56cf418a1ddcab59b7598ae706d848)
I0618 10:21:58.845655    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=98354  state=0)
I0618 10:21:58.845655    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:22:26.546224    2724 chain_manager.go:801] Bad block #625306 (3ceb5410b74ebac152c6489f0ff3f021ce56cf418a1ddcab59b7598ae706d848)
I0618 10:22:26.546224    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=98354  state=0)
I0618 10:22:26.546224    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:22:53.936799    2724 chain_manager.go:247] Last block (#625300) e0e5fb43b620f425cefe1085a0d9aa3ab4bb6cf8773edb44e9b0a4514f5c7b5b TD=4916044785760483
I0618 10:23:09.936726    2724 chain_manager.go:801] Bad block #625301 (ee4972b5f950e1644437358547e074781b8ecc0ecf8e0e43bb413f5fbba16285)
I0618 10:23:09.936726    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=31277  state=0)
I0618 10:23:09.936726    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:23:24.879585    2724 chain_manager.go:801] Bad block #625301 (ee4972b5f950e1644437358547e074781b8ecc0ecf8e0e43bb413f5fbba16285)
I0618 10:23:24.880585    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=31277  state=0)
I0618 10:23:24.880585    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:23:39.145375    2724 chain_manager.go:801] Bad block #625301 (ee4972b5f950e1644437358547e074781b8ecc0ecf8e0e43bb413f5fbba16285)
I0618 10:23:39.145375    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=31277  state=0)
I0618 10:23:39.145375    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:24:00.468596    2724 chain_manager.go:801] Bad block #625301 (ee4972b5f950e1644437358547e074781b8ecc0ecf8e0e43bb413f5fbba16285)
I0618 10:24:00.468596    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=31277  state=0)
I0618 10:24:00.469596    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:24:27.540877    2724 chain_manager.go:801] Bad block #625301 (ee4972b5f950e1644437358547e074781b8ecc0ecf8e0e43bb413f5fbba16285)
I0618 10:24:27.540877    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=31277  state=0)
I0618 10:24:27.540877    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:24:54.356391    2724 chain_manager.go:801] Bad block #625301 (ee4972b5f950e1644437358547e074781b8ecc0ecf8e0e43bb413f5fbba16285)
I0618 10:24:54.356391    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=31277  state=0)
I0618 10:24:54.356391    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:25:09.683269    2724 chain_manager.go:247] Last block (#625290) 739a1781aa7a6ad77bdaedaf93f6d9e7253261d502f0392485cebca584e07d58 TD=4915999626779478
I0618 10:25:31.755545    2724 chain_manager.go:801] Bad block #625291 (2c5475d5e56cb38d813adf3e14cd1f8ad12a7d6da2562ce8f8cd73393e99b963)
I0618 10:25:31.755545    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=30833  state=0)
I0618 10:25:31.755545    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:25:48.664496    2724 chain_manager.go:801] Bad block #625291 (2c5475d5e56cb38d813adf3e14cd1f8ad12a7d6da2562ce8f8cd73393e99b963)
I0618 10:25:48.664496    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=30833  state=0)
I0618 10:25:48.664496    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:25:55.650895    2724 chain_manager.go:801] Bad block #625291 (2c5475d5e56cb38d813adf3e14cd1f8ad12a7d6da2562ce8f8cd73393e99b963)
I0618 10:25:55.650895    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=30833  state=0)
I0618 10:25:55.650895    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:26:18.455218    2724 chain_manager.go:801] Bad block #625291 (2c5475d5e56cb38d813adf3e14cd1f8ad12a7d6da2562ce8f8cd73393e99b963)
I0618 10:26:18.455218    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=30833  state=0)
I0618 10:26:18.455218    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)
I0618 10:26:36.861278    2724 chain_manager.go:801] Bad block #625291 (2c5475d5e56cb38d813adf3e14cd1f8ad12a7d6da2562ce8f8cd73393e99b963)
I0618 10:26:36.861278    2724 chain_manager.go:802] Transaction w/ invalid nonce. tx=30833  state=0)
I0618 10:26:36.861278    2724 downloader.go:223] Synchronisation failed: block downloading canceled (requested)

**Comment by rfikki** [comment]
No worries, will try to start from scratch....

**Comment by obscuren** [comment]
This happens when you kill geth during importing or when the client crashes. If there's anything you remember that happened prior to this; that would help enormously

**Comment by Phistr90** [comment]
had the same problem yesterday, no client crash ... loaded a backup

**Comment by fjl** [comment]
Should be solved by now.
