### ISSUE TITLE
Genesis mismatch

### ISSUE THREAD

**Issue by bitcoinbrisbane** [ethereum/go-ethereum#1288]
Getting the following exception after a first time git pull and build.

Done building.
Run "build/bin/geth" to launch geth.
xxx@ubuntu:~/go-ethereum$ build/bin/geth
I0618 11:25:53.359598    9502 backend.go:269] Protocol Version: 60, Network Id: 0
I0618 11:25:53.359740    9502 backend.go:279] Blockchain DB Version: 3
Fatal: Genesis mismatch. Maybe different nonce (0 vs 42)? 01a0aa08 / fd4af92a

**Comment by obscuren** [comment]
Did previously run with `--genesisnonce #` ?

**Comment by bitcoinbrisbane** [comment]
No, its a clean install of Ubuntu 14 on a VM.

**Comment by aboynejames** [comment]
a clean install for me too and got this

I0618 14:30:34.592008   15656 backend.go:269] Protocol Version: 60, Network Id: 0
I0618 14:30:34.592058   15656 backend.go:279] Blockchain DB Version: 3
Fatal: Genesis mismatch. Maybe different nonce (0 vs 42)? 01a0aa08 / fd4af92a

**Comment by cjphilpot** [comment]
I get the same thing when I try to start the included version of Mist on the develop branch.

**Comment by obscuren** [comment]
I just restarted geth using a new setup with 

`stygeo@ethdev:~/go/src/github.com/ethereum/go-ethereum/cmd/geth$ geth --datadir /tmp/500`

and doesn't give me this error. What version are you guys on; `develop`, `master`?

**Comment by aboynejames** [comment]
develop  branch

**Comment by obscuren** [comment]
Did you also run `cpp-ethereum`?

**Comment by aboynejames** [comment]
yes, have installed cpp-ethereum by github source and ppa methods.  I m trying it all out to further my understanding on this great project you ve put together.

**Comment by obscuren** [comment]
Right, that's the issue. Please either move the old `.ethereum` folder or specify a different path using `--datadir`. Let me know if that works

**Comment by bitcoinbrisbane** [comment]
I can confirm with --datadir /tmp/500 it fixes that issue.  Now saying Block synchronisation started.. so looking good.

**Comment by obscuren** [comment]
Alright. Closing issue :+1:
