### ISSUE TITLE
contract event.watch() now spams console with "true"s and "false"s. (left-in debug?)

### ISSUE THREAD

**Issue by Smithgift** [ethereum/go-ethereum#1289]
On Geth version 0.9.31, built-in console, using event.watch() will instantly print absurd walls of "true" and "false". My belief is that it is printing "true" for every event the filter accepts, and "false" for *every other* event. My private blockchain has quite a load of old contract events, so the terminal runs out of scrolling history immediately.

See also #1182. It's doing this every event, even those that happened before the callback was made.

**Comment by caktux** [comment]
still seeing this in latest develop, a summary of matched / filtered logs would be a lot more useful. Searched a few filter related files but couldn't find where it's coming from... should be a 12s fix for @obscuren ;)

**Comment by tgerring** [comment]
I've been seeing "false" printed on the console when setting filters from the RPC, so it's not limited to a console-specific issue.

1. Clone https://github.com/tgerring/abi2html-js
1. Open index.html
1. Start geth with provided parameters
1. Click "Start watch" in the upper left
1. Observe console for "false" to be printed

**Comment by fjl** [comment]
Fixed in #1391.
