### ISSUE TITLE
building ethereum with go dep

### ISSUE THREAD

**Issue by prime33** [ethereum/go-ethereum#1291]
I am getting this error. Can someone help me?
![geth-build](https://cloud.githubusercontent.com/assets/5238875/8242604/1676675c-15d6-11e5-8d2a-a6e0f06e0137.png)

Also, for command "git checkout develop && godep go install" to work, do I need to add C:\godev\bin to PATH as well?

**Comment by tgerring** [comment]
Can you provide more information on how you got to this point?

For godep to work, `%GOPATH%\bin` should be added to your %PATH%
