### ISSUE TITLE
contractInfo.get(): content hash mismatch

### ISSUE THREAD

**Issue by Smithgift** [ethereum/go-ethereum#1294]
contractInfo.get() seems to find the info.json on my filesystem just fine. It claims a content hash mismatch, even though the file is what is directly produced by contractInfo.register().

**Comment by zelig** [comment]
yes this is most probably due to the registrars not set up properly. 
But also points to the issue that `admin.getContractInfo()` fails to check for 404 status correctly. So i leave this open.
