### ISSUE TITLE
testeth exit code on blocktest

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#1307]
I have testeth reporing an Invalid test on 
http://pastie.org/10251623

though it says correct phrase:
"block insertion should have failed"

it's return code as if it was incorrect test. (on which block should have passed (given this example))

**Comment by tgerring** [comment]
I'm not clear on what the problem is... maybe you can re-state it?

Running the test, I see the following output and exit code:
```
$ wget -q -O - "$@" http://pastie.org/pastes/10251623/download | ethtest --test BlockTest --stdin
I0623 15:19:39.122618    3771 main.go:72] runTest BlockTest
F0623 15:19:41.417111    3771 main.go:189] Block insertion should have failed
$ echo $?
255
```

The error is generated from https://github.com/ethereum/go-ethereum/blob/develop/tests/block_test_util.go#L260-L261. What result or messages are you expecting?

**Comment by tgerring** [comment]
Pinging @winsvega

**Comment by obscuren** [comment]
Status?

**Comment by winsvega** [comment]
seems to pass now
