### ISSUE TITLE
Running out of space corrupted blockchain DB.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/go-ethereum#1310]
I had left a geth node running on my rasberry pi unattended.At some point it actually ran out of space, and now it says:
```
I0621 22:02:43.192913     510 backend.go:266] Protocol Version: 60, Network Id: 0
I0621 22:02:43.193387     510 backend.go:266] Blockchain DB Version: 3
F0621 22:02:43.236969     510 chain_manager.go:238] Fatal. LastBlock not found. Please run removedb and resync
```
I have a spare copy of the doomed datadir for anyone morbidly curious.

**Comment by Smithgift** [comment]
It looks like this is reported elsewhere. Closing.

**Comment by obscuren** [comment]
PR https://github.com/ethereum/go-ethereum/pull/1305
The other issue https://github.com/ethereum/go-ethereum/issues/1308
