### ISSUE TITLE
--ipcpath seems to be overridden by a different datadir.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/go-ethereum#1311]
Because I ran out of space on my pi's SD card, I am improvising with a flashdrive, which happens to be FAT formatted. While I can set the datadir to use the flashdrive, geth wants to start the ipc thingy on the datadir on flashdrive, which is impossible. Trying --ipcpath to get it to put the .ipc on the flashdrive has so far had no result.

**Comment by tymat** [comment]
See:  https://github.com/ethereum/go-ethereum/blob/f2a2164184a9397d8e6100c370595ccdcd00ca0b/cmd/utils/flags.go#L221

and 

https://github.com/ethereum/go-ethereum/blob/f2a2164184a9397d8e6100c370595ccdcd00ca0b/cmd/utils/flags.go#L424

**Comment by Smithgift** [comment]
I think see see the bug right there. You can't *re*specify the ipc file to be in .ethereum if your datadir is elsewhere, because if you specify the default explicitly it falls through to change-it-to-be-in datadir part. I can work around this for the moment.
