### ISSUE TITLE
SEC-50 RLPx AES CTR keystream reusage

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#1315]
https://github.com/ethereum/devp2p/issues/32  tracks the protocol crypto change needed.

This issue tracks the Go implementation once the RLPx spec is fixed.

**Comment by zelig** [comment]
@Gustav-Simonsson has this been addressed?

**Comment by LaurentMT** [comment]
Hi there.
Any progress made on this issue ? (I'm under the impression that new version of rlpx spec has stalled since last year).
Thanks in advance for any info !
laurent

**Comment by fjl** [comment]
Design work for a new version of rlpx is underway. I have personally not cared much about this flaw because

* The current version has other design problems (not necessarily security related).
* The only significant traffic transported by rlpx today is public ethereum blockchain data.

**Comment by Magicking** [comment]
The « in progress » has been removed but the issue still exists, what needs help in order to advance on this issue ?
