### ISSUE TITLE
SEC-51 Peer NewBlockMsg DoS

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#1319]
The protocol handler adds block hashes to the peer.blockHashes set without any limits: https://github.com/ethereum/go-ethereum/blob/develop/eth/handler.go#L363

A malicious peer can send low-difficulty blocks (to avoid them being validated / processed) continuously, eventually causing OOM.

We need some form of limit here, perhaps a eviction of old hashes.

**Comment by karalabe** [comment]
This one is fixed in the eth/61 PR. I don't want to back-port the fixes as it's not really urgent to get this out the door, so I'm going to move this to the next release milestone.
