### ISSUE TITLE
9.33 commands of the admin module?

### ISSUE THREAD

**Issue by Phistr90** [ethereum/go-ethereum#1325]
Hi, with the new version I cant get the commands from the admin module, like  admin.peers(), admin.unlock(), admin.progress()...
Where are they gone?
I cant find any info in the documentation about it.

**Comment by MercStills** [comment]
looks like admin.peers() is replaced by admin.getpeers() and admin.progress is replaced by admin.getChainSyncStatus().  Not sure about admin.unlock().  

Just type admin in the geth console and you'll get a list of methods, etc.

**Comment by ethers** [comment]
Just saw, haven't tried.  If you use `geth --ipcpath <path to geth.ipc file> attach` and then
`web3.personal` it has unlockAccount...

**Comment by bas-vk** [comment]
This has been changed in the latest version. Basically what has happened is that all the console calls are RPC calls just as the `eth.XXX` calls and can be called from clients like the console (or some other 3rdparty client).  The different console commands are now placed in multiple smaller logically grouped modules.

If you start the console (either with console or attach) you should see a line like this:

```
modules: admin:1.0 db:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 shh:1.0 txpool:1.0 web3:1.0
```

This tells you what modules (and their version) are available. To see what methods/properties are available type in `${module}.` and hit the TAB key twice. In case of the admin module you should see something like:

```
> admin.
admin.addPeer         admin.nodeInfo        admin.importChain     admin.chainSyncStatus admin.datadir         admin.stopRPC         
admin.peers           admin.exportChain     admin.verbosity       admin.setSolc         admin.startRPC        
```
What autocompletion doesn't show you if something is a property or a method. In general everything is a property unless:
1. its needs arguments
2. its changed state in the node

I'm still working on the documentation and hope to finish that today.
To answer your question:

```
admin.peers() -> admin.peers (property)
admin.unlock() -> personal.unlockAccount(${account}, ${password})
admin.progress() -> admin.chainSyncStatus (property)
```

These new methods are exposed through the web3 library which has the side effect of creating getters for properties. In the case of `admin.peers` web3 will add a `admin.getPeers()` method which doesn't work. This is a known issue.

If I have finished the documentation I will post a link and close this issue.

**Comment by bas-vk** [comment]
Documentation can be found [here](https://github.com/ethereum/go-ethereum/wiki/Go-ethereum-management-API's).
