### ISSUE TITLE
geth attach with datadir

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1326]
for consistency with `geth --datadir` can `geth attach` be updated to use `--datadir` instead of `--ipcpath` ?  geth would look for the geth.ipc inside the datadir.

(Or this suggestion doesn't work because there could be multiple ipc files around and they will not be in the datadir?)

**Comment by bas-vk** [comment]
The `attach` subcommand uses ipc by default and looks for the endpoint on the default location. If the geth node was started with a custom `datadir` and/or `ipcpath` you must specify this path. The preferred way is:

`geth attach ipc:/some/path`

For more information (e.g. how to attach over http/rpc) and an explanation about the differences between `console` and `attach` see the wiki: https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console

**Comment by ethers** [comment]
Thanks for the explanation.  So I think this suggestion becomes: remove `--ipcpath` since the syntax for `geth attach` should be `ipc:/some/path` (or rpc:http:...) as you mention in the wiki.

**Comment by bas-vk** [comment]
Currently the flags are not defined on a subcommand but on the geth command. Removing it just for the attach subcommand is therefore not possible. This is known limitation and internally discussed. In the future we are planning to do a more git like approach where arguments are passed behind the subcommand (e.g. `git rebase --continue`). That will allow us to specify only valid flags for a subcommand.

**Comment by ethers** [comment]
Are there some commands that need to use `--ipcpath`  instead of `ipc:/some/path` ?
I thought `ipc:/some/path` could be used everywhere?
If this suggestion doesn't make sense anymore, feel free to close (don't want to bother you about it).  Thanks

**Comment by bas-vk** [comment]
Only the attach command accepts the `ipc:/some/path`, all other commands use the `--ipcpath`. This distinction is because it is also possible to specify a http endpoint with `rpc:http://1.1.1.1:8545`.
