### ISSUE TITLE
Block #33204 error

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#133]
While this isn't an issue related to **Mist** I'll put it here for future reference. Block #33204 fails on go-ethereum (and Py).

Python and Go derive the same "med" state and post state. C++ (@gavofyork)  derives something completely different.

For more details please see https://gist.github.com/obscuren/d33e747d32b7ad33d0ec

**Comment by ktjooho** [comment]
## 추가 수정: TimingMetrics race condition 해소 + OFA bundle depth 기록 누락

커밋: d0e7bd99c (`magpie/accuracy/competitor-tx-analysis`)

### 1. TimingMetrics goroutine race condition 해소

**문제**: `trySendArbInfo`가 `go` goroutine으로 실행되는데, 내부에서 `a.timing` 포인터를 직접 참조. 다음 depth의 SPFA/GSS가 동일 slice에 `append`하면서 concurrent read/write data race 발생 가능.

**수정**:
- `TimingMetrics.Clone()` deep copy 메서드 추가 (nil guard 포함)
- 5개 `go a.trySendArbInfo(...)` 호출부에서 goroutine 시작 **전** `a.timing.Clone()` 수행
- `trySendArbInfo` 내부의 `a.timing` 직접 접근 제거

**변경 파일**:
- `magpie/executor/mev.go` — `Clone()` 메서드 (SpfaDurations/GssDurations/DepthTimings/PathDetails nested slice 완전 deep copy)
- `magpie/searcher/new_arbitrage.go` — 5개 호출부 Clone 적용

### 2. OFA victim SearchSession bundle depth 기록 누락 수정

**문제**: OFA victim (`OnlyMaxProfitForOFA=true`)일 때 `canSendBundle=false`로 candidate 루프 내 send가 없어 SearchSession depthDetails에 bundle이 0개로 기록됨. 실제로는 루프 후 `MergeAndSend`로 bundle이 생성/전송되지만, `mev.SearchDepth`가 goroutine 간 공유되어 depth 값이 오염될 수 있었음.

**수정**:
- `Bundle.SearchDepth` 스냅샷 필드 추가
- `MevManager.CreateBundle` 내부에서 `bundle.SearchDepth = mev.SearchDepth` 일괄 설정 (호출부 누락 방지)
- `upsertFromBundle`에서 `bundle.SearchDepth` 참조로 변경

**변경 파일**:
- `magpie/executor/bundle.go` — `SearchDepth` 필드 추가
- `magpie/executor/mev_manager.go` — `CreateBundle` 내부 일괄 설정, 호출부 개별 설정 제거
- `magpie/collector/searchsession/collector.go` — `bundle.SearchDepth` 참조
