### ISSUE TITLE
geth cannot be explicitly set to use default IPC path with different datadir.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/go-ethereum#1336]
My datadir has to be on another, FAT disk, because I've run out of space. I'd like the ipc file to be in ~/.ethereum so geth attach works by default. Using --ipcpath doesn't work, because geth sees that the ipcpath is the same as the default, and therefore changes it to be in the datadir, and then it breaks.

**Comment by bas-vk** [comment]
Could you try:

`geth attach ipc:/your/path`

See for more information [this](https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console) wiki page.

**Comment by frozeman** [comment]
Fixed in theipcpipelining branch of @bas-vk, will be merged soonish.
