### ISSUE TITLE
Unable to unlock account created with plaintext password in geth

### ISSUE THREAD

**Issue by misled** [ethereum/go-ethereum#1337]
How to reproduce:

1. Create a `pwd` file that consists of the word `test` and an empty line. (The [instructions](https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts) suggest that "The data in the file consists of the raw characters of the password, followed by a single newline.")

2. `geth --password pwd account new`

3. `geth console 2>>log`

4. In the JavaScript console:
`admin.unlock('account-created-in-step-21')`

```
Please enter a passphrase now.
Passphrase: test
Unlock account failed 'Decryption failed: MAC mismatch'
false
```

Note that I've tried using a pwd file without a newline (`echo test > pwd`) and the end result is the same.

Here is the output of `geth version` for reference:

```
Geth
Version: 0.9.31
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2
OS: linux
GOPATH=
GOROOT=/usr/lib/go
```

**Comment by zelig** [comment]
please try it on a newer release, cannot reproduce your issue

**Comment by ktarasz** [comment]
Fatal: Unlock account failed 'Decryption failed: MAC mismatch'
```
Geth
Version: 0.9.38
Protocol Versions: [61 60]
Network Id: 0
Go Version: go1.4.2
OS: linux
GOPATH=
GOROOT=/usr/lib/go
```

Account version:  1 
Account was created in geth (>0.9.32)
