### ISSUE TITLE
Slowly dropping peers/slow propagation

### ISSUE THREAD

**Issue by TalkingAntColony** [ethereum/go-ethereum#1338]
Over time my node will tend towards just a few peers, rarely going over 10, yet maxpeers is set to 50. Eventually it will get stuck on an old block. When my peer count is less than ~10, block propagation gets pretty slow compared to the other nodes on stats. It seems to help if I delete nodekey and the nodes directory then restart geth every now and then (once or twice a day). Not sure if this is specific to me or maybe a Windows issue. You can watch my node struggle on the stats page (DankHash). 

My machine is pretty beefy so i doubt it is the issue: 6-core i7 5930k, 32GB DDR4 RAM, SSD, 90 mbps internet.

Here is a filtered log of a few min while my node was chugging along:

https://gist.github.com/TalkingAntColony/f2371b0e64c5e6117f0a

**Comment by JustinDrake** [comment]
What is your geographical location?

**Comment by TalkingAntColony** [comment]
Northeast US

**Comment by jmiehau** [comment]
Try to connect to my peers manually, I am synchronizing pretty fast today.  https://gist.github.com/jmiehau/fe27e8dbd3ebf74c094e

**Comment by simondlr** [comment]
Almost exactly the same thing happens to me. Connecting from South Africa and suspected it might have to do with geographical distance. It will just stop syncing, and then resync in fits and starts.

**Comment by fjl** [comment]
@TalkingAntColony is this still an issue?
