### ISSUE TITLE
[rpc] Additional `polarity` field in solidity logs

### ISSUE THREAD

**Issue by debris** [ethereum/go-ethereum#1339]
Few days ago Gavin created a [document](https://ethereum.etherpad.mozilla.org/10069?) describing few enhancements in rpc.

**TL;DR**

Logs should have additional `polarity` field.

> polarity: BOOL - either true (the transaction pertaining to this log was mined or arrived as pending compared to the previous notification/notified block) or false (the transaction pertaining to this log was reverted or was deleted compared to the previous notification/notified block).

**Comment by frozeman** [comment]
Very useful field, but i'm against the naming convention. This is not intuitively understandable what this property means.

I would suggest: `status: 'mined'`, `status: 'pending'`

**Comment by frozeman** [comment]
If gav wants a boolean property we could name it `invalidated: true`, which is at least guessable.
