### ISSUE TITLE
eth: reduce transaction propagation packets

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#1343]
Currently transaction propagation runs as soon as a new transaction arrives, sending it out to all peers not known to have the transaction. This however results in a significant network packet overhead: with about 25 peers and the currently mostly idling network this already results in 150-200 inbound transaction packets per second, and 200-300 outbound. This seems a bit wasteful and might cause problems if network usage picks up.

One possible solution I can see is that whenever a transaction is to be distributed, start a timer and wait some small amount of time (50ms), and distribute everything that arrives in the mean time. This should help reduce the network overhead (i.e. wasted bytes / useful bytes) on distributing the transactions and shouldn't introduce any noticeable delays.

![Imgur](http://i.imgur.com/G7ENm6l.png)

**Comment by fjl** [comment]
This is basically #1262.

**Comment by karalabe** [comment]
Don't conpletely agree. The other issue is about not sending duplicate transactions. This one is about collating multiple transactions into a single packet vs the 1 packet / tx we currently do.
