### ISSUE TITLE
Not able to kill Geth process on MAC OS X - Zombie

### ISSUE THREAD

**Issue by jmiehau** [ethereum/go-ethereum#1348]
I am not able to kill the Geth 0.9.32  process on OS X, I forced to exit it on the Monitor Activity but it appears after 5 minutes again..

Even I restarted my computer. My last connection on Geth was yesterday with the console. 

**By the way, if I start Geth by myself on the command console, on the Monitor Activities appear both of them.

I uploaded snapshots. You can see how the CPU Graph goes  up.

![captura de pantalla 2015-06-28 a las 15 05 45](https://cloud.githubusercontent.com/assets/4571693/8396509/3ffd2c20-1da9-11e5-86e3-735c0e3db64b.png)
![captura de pantalla 2015-06-28 a las 15 17 41](https://cloud.githubusercontent.com/assets/4571693/8396510/3ffe0082-1da9-11e5-84fd-20287bb5a470.png)
![captura de pantalla 2015-06-28 a las 15 25 21](https://cloud.githubusercontent.com/assets/4571693/8396521/f434aab0-1da9-11e5-9552-cf429a985b59.png)
** ![captura de pantalla 2015-06-28 a las 15 30 54](https://cloud.githubusercontent.com/assets/4571693/8396534/d170b7b6-1daa-11e5-9654-50af8aa43bce.png)

**Comment by jmiehau** [comment]
I was using Homebrew,  I uninstall the formula with this command:
https://gist.github.com/jmiehau/7a84f295bfcec39bb8e2
`brew rmtree ethereum/ethereum/ethereum`
'brew install ethereum` again, but I continued to have the zombie Geth.

I deleted the Homebrew formula, right now, I builded from source  9.34.1
`make geth`

**Comment by obscuren** [comment]
Geth does not startup by it self unless you've done something that auto-starts if it's down.

Geth takes some time to shut down after pressing ctrl-c.

**Comment by jmiehau** [comment]
Thanks Jeff, I found from where it comes.

`~/Library/LaunchAgents`

![captura de pantalla 2015-07-01 a las 11 00 50](https://cloud.githubusercontent.com/assets/4571693/8451084/995951e8-1fe0-11e5-810c-70e460de889e.png)

**Comment by ohadperry** [comment]
+1, worked for me, thanks
