### ISSUE TITLE
mist.exe crashes on Windows 10 Technical Preview

### ISSUE THREAD

**Issue by erezwanderman** [ethereum/go-ethereum#135]
(Copied from here https://github.com/ethereum/go-build/issues/5)
I managed to get it built.
When I run ethereum.exe it starts fine:
```
C:\Ethereum\go\src\github.com\ethereum\go-ethereum\ethereum>ethereum
Qt: Untested Windows version 6.4 detected!
2014/10/07 02:10:17 [CLI] identity created
2014/10/07 02:10:17 [CHAIN] Last block (#0) 08436a4d33c77e6acf013e586a3333ad152f25d31df8b68749d85046810e1f4b
2014/10/07 02:10:17 [CLI] Starting Ethereum(G)/v0.6.7/windows/go1.3.3
2014/10/07 02:10:17 [REACTOR] started
2014/10/07 02:10:17 [SERV] Ready and accepting connections
2014/10/07 02:10:19 [SERV] Server started
```
But when I run mist.exe it pops a message "mist.exe has stopped working. Windows is checking for a solution to the problem".

The machine is running in VirtualBox and I'm connecting to it through Remote Desktop. Could be a graphics/driver/qt problem. I'll try to run it when connected to the terminal tomorrow.

**Comment by obscuren** [comment]
Mist is now using Qt5.4 which removes the dependency on WebKit (and adds Chromium).

Any volunteers for Qt5.4 on windows? :)
