### ISSUE TITLE
Les:  End-to-end test framework

### ISSUE THREAD

**Issue by jmozah** [ethereum/go-ethereum#13517]
A big end-to-end test framework that starts up a light client on the testnet with an empty datadir, connects to it through RPC and performs a complex test sequence while logging response times and checking responses. This test sequence should include:

- [ ] install a new block filter to follow the syncing process
- [ ] do  some simple requests (like account balance) while syncing to test responsiveness
- [ ] when synced, deploy a contract that generates log messages and also writes to storage
- [ ] after sending transactions, retrieve the transaction pool until it's empty, then check results (retrieve contract code)
- [ ] install a log filter for the contract
- [ ] send transactions to the contract and expect log events from the filter
- [ ] when all transactions have been mined, read the contract storage and check for the expected changes

**Comment by bas-vk** [comment]
Most of these tests are part of the hive RPC test suite that you can find here: https://github.com/karalabe/hive/tree/master/simulators/ethereum/rpc/eth.

Currently I'm adding light clients into the simulation cluster.
