### ISSUE TITLE
SEC-52 block header timestamp int64 overflow

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#1352]
We convert the received block header timestamp to a int64 here: https://github.com/ethereum/go-ethereum/blob/develop/core/block_processor.go#L356

A malicious miner can set a timestamp value that will overflow a int64 into a value that is valid according to consensus rules. This breaks consensus as two different block headers (hashes) would be considered the same by the Go consensus validations.

Converting to a uint type here is enough to avoid this as block times will always be positive integers in UNIX time.

TODO: verify what scalar value size will be accepted here in terms of RLP - we could potentially have a overflow on any uint too.

**Comment by obscuren** [comment]
```
if block.Time > uint64(time.Now().Unix()) {
    return BlockFutureErr
}
```

**Comment by obscuren** [comment]
https://github.com/ethereum/go-ethereum/pull/1241/files#diff-9dc4dfc538cf66079b5ddd793724e148R390

**Comment by Gustav-Simonsson** [comment]
https://github.com/ethereum/go-ethereum/pull/1355

**Comment by Gustav-Simonsson** [comment]
Closing issue, though we should check this with 256 bit ts value casted into uint64
