### ISSUE TITLE
IPC path is not taken into consideration when datadir is specified

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#1364]
Running:
```
geth --networkid 8556 --datadir /Users/frozeman/Library/Ethereum/testChain --shh --ipcpath /Users/frozeman/Library/Ethereum/geth.ipc
```
Starts the IPC on the wrong path:
```
IPC service started (/Users/frozeman/Library/Ethereum/testChain/geth.ipc)
```

Note that it should *not* use the IPC file in `testChain`, but one folder above instead.

I'm on Mac OSX

**Comment by ethers** [comment]
looks similar to (if not duplicate) https://github.com/ethereum/go-ethereum/issues/1336

**Comment by frozeman** [comment]
Fixed in the` ipcpipelining` branch of @bas-vk
