### ISSUE TITLE
shh.post fails

### ISSUE THREAD

**Issue by mike80439** [ethereum/go-ethereum#1374]
http://pastebin.com/RkFwDW0R

[eth-projects] $ geth version
Geth
Version: 0.9.35
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.4.2/libexec

**Comment by linagee** [comment]
I was able to reproduce your error and have come out with a fix. We'll see if the maintainers accept it or not. (It looked like it succeeded, maybe you can compile and confirm? I don't really know how to read whisper, but it "returned true"...?)

https://github.com/ethereum/go-ethereum/pull/1406

**Comment by mike80439** [comment]
I'm unable to get Whisper to work. Two MacBookPro running geth 0.9.36. 
http://pastebin.com/25iMirzj
Both boxes were catching-up the blockchain. One box is on a VPN.

**Comment by linagee** [comment]
mike80439: were you pulling from my repo when you tried?

**Comment by fjl** [comment]
#1406 was closed. The issue should be resolved in web3.js.
