### ISSUE TITLE
Crash with dire message (database corruption?)

### ISSUE THREAD

**Issue by Smithgift** [ethereum/go-ethereum#1375]
I found my RPi geth node had crashed, with the following message (in nohup.out):

```
F0701 18:02:09.156856     507 cache.go:45] db write err:leveldb/table: corruption on data-block (pos=1654436): checksum mismatch, want=0x91980b86 got=0x9782bef7 [file=084313.ldb]
```

At the moment I'm running again (without nohup.out) to see what what will happen.

**Comment by Smithgift** [comment]
The node seems to be spewing a bunch of messages like 
```
I0701 20:56:39.823904   12534 queue.go:142] Hash f758bb10392bc55f2a861f9247e8bb41047abc96e321eac02054e0fd666938e1 already scheduled at index 85975
```
though it hasn't crashed yet.

**Comment by fjl** [comment]
This looks like an actual leveldb corruption happened. The restart should have fixed it (we attempt to repair leveldb corruption from the write-ahead log on startup).

The log messages from queue.go are unrelated.

**Comment by Smithgift** [comment]
Actually, several restarts later, it is still crashing with this message.
