### ISSUE TITLE
Tx dont get included altough gas price higher

### ISSUE THREAD

**Issue by Phistr90** [ethereum/go-ethereum#1376]
Hi folks, my tx dont get included altough the gas price is higher than those from 0x4759966877052299c659d84023a144d244aaf42c included.

Currently n12o is spamming 1m tx with a current gas price of 1.102 Szabo, whereas I try to send 3m gas tx with a gas price of 6.1Szabo.
Tx with low gas costs will get included addtionally to the 1m tx though.
I guess there is something wrong with the default including strategy.

**Comment by Phistr90** [comment]
Actually etherchain.org and the geth clients says that the tx of 0x4759966877052299c659d84023a144d244aaf42c is 3m whereas the netstat monitor says 1m.
Nevertheless the tx should be included because of the higher gas price. Furthermore another user has reported the same problem in the mining community skype channel.

**Comment by obscuren** [comment]
Transactions are currently ordered by nonce and this means that your tx doesn't get included because his is probably lower than yours. Now 1m + 3m exceeds the limit and therefor your tx won't be included.

**Comment by Phistr90** [comment]
okay imo default strategy should be the gas price, otherwise one could block a large amout of tx when there is a low gas price. should be a free market and the tx which pays most should be included. game theoretically the current strategy is not the best decision of the miner. all miners want always increase the utility which in this meaning is maximize the reward and this can be done by ignoring the low gas price tx and including the high gas price tx.

**Comment by Phistr90** [comment]
On top of that as I said above my client says gas used is 3m not 1m. The block explorer etherchain.org says so too. So there is a bug either on netstat and in the client info or in the algo which increases the gas limit becuase it does not increase...

**Comment by obscuren** [comment]
So imagine contract A and contract B. Here's the consumption:

```
A => max 100 gas
B => max 50 gas
```

No we have transactor X and Y.
* X transacts with contract A and sends a transaction with 1M gas;
* Y transacts with contract B and sends a transaction with 3M gas.

As you can see A would consume much more gas than B, yet Y, in your suggestion is favoured. Problematic? Indeed! :-)

You'll never know how much a transaction will cost w/o fully processing it. Pre-processing and checking which **actually** has the highest reward (by `used_gas * price`) is costly and unwanted process.

**Comment by obscuren** [comment]
Additionally; is the current scheme the best? Certainly not, but right now it's not very high on my list of things to do :-) and is certainly not a blocking "issue" for frontier. I hope you agree! :-)

**Comment by sontol** [comment]
I think the other main concern that PhiStr90 highlighted (not in the original post, need to create a separate one?) is the gas limit doesn't seems to increase when the block is obviously full. Is this expected?

**Comment by sontol** [comment]
Besides that, in knapsack problem greedy algorithm can actually yield a pretty good solution (as compared to the nonce method)

**Comment by Phistr90** [comment]
Okay to make it clear: I cannot spam any tx regardless of the gas amount. There is definitely something broken. Other users report the same.

**Comment by obscuren** [comment]
@sontol the gas limit increases just fine. See the white paper and yellow paper for an in-depth explanation and the algorithms.

@Phistr90 Please provide a minimal viable test case for me to reproduce this; only then I can do something about it.

**Comment by obscuren** [comment]
BTW, the current blocks aren't **full**. @sontol not sure if you're saying that the blocks are full.

**Comment by sontol** [comment]
Just do this. Send a tx. See how long before it gets confirmed. If blocks aren't full it should be nearly immediate. I have several tx waiting in hours

**Comment by Phistr90** [comment]
Yep, just like sontol says, a simple tx. eg my bash looks similar to this:

price=`curl --url 192.168.188.55:8545 -X POST --data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":73}'`
#echo $price
priceInt=`echo "$price" | python -c 'import json, sys; print json.load(sys.stdin)["result"]'`
#priceInt= jq -r 'result' <<< "$price"
priceInt2=$(($priceInt))
priceInt3=$(($priceInt2 + 5000001000000))

curl --url 192.168.188.55:8545 -X POST --data "{\"jsonrpc\":\"2.0\",\"method\":\"eth_sendTransaction\",\"params\":[{\"from\": \"YOURADDRESS\",\"to\": \"YOURADDRESS\", \"value\": 1337, \"gas\": 100000, \"gasPrice\": \"$priceInt3\" }],\"id\":1}"
Frist part is just to make sure, we send with a gas price higher than the current.
I send mine from a address with high nonce, but since the blocks arent full as you say these tx should be included.
of course you can use directly the console, but dont know the exact js syntax.

**Comment by obscuren** [comment]
I'm afraid this won't be sufficient. Please give me an example on a private chain like so:

1. Send Tx with X params
2. Send another Tx with Y params
3. I expected A to happen but instead B happened. 

I've also tried as you suggested and tried sending transactions to the network with success (30 minutes ago). They were all included just perfectly fine.

**Comment by Phistr90** [comment]
okay one of the todays commits fixed the problem. at least i can include now low gas tx. 10 min ago i tested, didnt work, then did an update to latest commit and now it works again. maybe something in the rpc code? I saw it was changed today.
Will try to send tx with higher gas consumption as well.

**Comment by obscuren** [comment]
There were a few issues though not with sending transactions (but including them in the tx database)
