### ISSUE TITLE
cmd/geth: SIGINT shutting down taking 45+ minutes

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#1379]
`Geth/v0.9.35-130f3b27/linux/go1.4.2` on a Raspberry Pi2:

After sending a single SIGINT (Ctrl-C) to the `geth` process, it is taking more than 40 minutes (and counting) to actually shut down:

```
I0701 10:13:04.427852     690 chain_manager.go:726] imported 256 block(s) (0 queued 0 ignored) including 218 txs in 3m8.314444619s. #517635 [4f1076af / 35fe9b02]
I0701 10:16:01.821303     690 chain_manager.go:726] imported 256 block(s) (0 queued 0 ignored) including 176 txs in 2m33.578251628s. #517891 [196f8166 / ee13bd9b]
I0701 10:19:29.731968     690 chain_manager.go:726] imported 256 block(s) (0 queued 0 ignored) including 219 txs in 3m4.163784799s. #518147 [bc50fa96 / 7436496e]
I0701 10:22:46.327634     690 chain_manager.go:726] imported 256 block(s) (0 queued 0 ignored) including 291 txs in 3m9.620588621s. #518403 [b9ccafd3 / b42f192f]
^CI0702 08:41:00.413202     690 cmd.go:60] Shutting down (interrupt) ...
```

Still going at 09:36 UTC. Expected that a controlled shutdown would be completed within a reasonable time (ideally a few seconds, at max a minute or 2).

Full logs / stacktrace after sending a SIGQUIT (at the risk of database corruption):
https://gist.github.com/jorisbontje/9751824a2902bc61e68d

**Comment by karalabe** [comment]
I am guessing the culprit is the leveldb compaction running in the background. Those compactions need to finish before we can really do anything, as they are probably blocking some operations. This issue should hopefully be less of an issue with reducing the database size.

**Comment by jorisbontje** [comment]
Not seeing this anymore with frontier blockchain
