### ISSUE TITLE
suggestion: message about low peercount and syncing clock

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1381]
when there is low peercount or 0 peercount, could Geth log a message like "you may need to ntp sync your clock to get more peers" ?  especially when Geth is restarted and stuck at 0 peers, such a message will be a helpful reminder to users.

**Comment by obscuren** [comment]
No. But a wiki page with troubleshooting problem "X" would be awesome though :-)

**Comment by ethers** [comment]
yes was discussed on frontierguide gitter and 1st item on:  https://github.com/ethereum/go-ethereum/wiki/FAQ :)
