### ISSUE TITLE
solc 0.4.10 produces undefined contract.info object

### ISSUE THREAD

**Issue by islandBilly** [ethereum/go-ethereum#13845]
#### System information

Geth version: v1.5.5-stable-ff07d548/linux/go1.7.4
OS & Version: Kali GNU/Linux Rolling 64-bit
Commit hash : (if `develop`)

#### Expected behaviour
eth.compile.solidity(contract) should produce abi codes and other stuff

#### Actual behaviour
it appears to produce bytecodes, but abi is empty and any reference to compiled object says contract is undefined

#### Steps to reproduce the behaviour on the geth javascript console:
1) contract = 'contract mortal { /* Define variable owner of the type address*/ address owner; /* this function is executed at initialization and sets the owner of the contract */ function mortal() { owner = msg.sender; } /* Function to recover the funds on the contract */ function kill() { if (msg.sender == owner) suicide(owner); } } contract greeter is mortal { /* define variable greeting of the type string */ string greeting; /* this runs when the contract is executed */ function greeter(string _greeting) public { greeting = _greeting; } /* main function */ function greet() constant returns (string) { return greeting; } }';

2) contractCompiled = eth.compile.solidity(contract);
this results in the following on the console:

{
  /tmp/geth-compile-solidity101073083:greeter: {
    code: "0x6060604052341561000c57fe5b6040516102f03803806102f0833981016040528051015b5b60008054600160a060020a03191633600160a060020a03161790555b805161005390600190602084019061005b565b505b506100fb565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061009c57805160ff19168380011785556100c9565b828001600101855582156100c9579182015b828111156100c95782518255916020019190600101906100ae565b5b506100d69291506100da565b5090565b6100f891905b808211156100d657600081556001016100e0565b5090565b90565b6101e68061010a6000396000f300606060405263ffffffff60e060020a60003504166341c0e1b5811461002c578063cfae32171461003e575bfe5b341561003457fe5b61003c6100ce565b005b341561004657fe5b61004e610110565b604080516020808252835181830152835191928392908301918501908083838215610094575b80518252602083111561009457601f199092019160209182019101610074565b505050905090810190601f1680156100c05780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b6000543373ffffffffffffffffffffffffffffffffffffffff9081169116141561010d5760005473ffffffffffffffffffffffffffffffffffffffff16ff5b5b565b6101186101a8565b60018054604080516020600284861615610100026000190190941693909304601f8101849004840282018401909252818152929183018282801561019d5780601f106101725761010080835404028352916020019161019d565b820191906000526020600020905b81548152906001019060200180831161018057829003601f168201915b505050505090505b90565b604080516020810190915260008152905600a165627a7a723058202ad808c9cda6a4da56752fea891db877d65c2107f99d4a13bb28e3d7073963a40029",
    info: {
      abiDefinition: [{...}, {...}, {...}],
      compilerOptions: "--combined-json bin,abi,userdoc,devdoc --add-std --optimize",
      compilerVersion: "0.4.10",
      developerDoc: {
        methods: {}
      },
      language: "Solidity",
      languageVersion: "0.4.10",
      source: "contract mortal { /* Define variable owner of the type address*/ address owner; /* this function is executed at initialization and sets the owner of the contract */ function mortal() { owner = msg.sender; } /* Function to recover the funds on the contract */ function kill() { if (msg.sender == owner) suicide(owner); } } contract greeter is mortal { /* define variable greeting of the type string */ string greeting; /* this runs when the contract is executed */ function greeter(string _greeting) public { greeting = _greeting; } /* main function */ function greet() constant returns (string) { return greeting; } }",
      userDoc: {
        methods: {}
      }
    }
  },
  /tmp/geth-compile-solidity101073083:mortal: {
    code: "0x6060604052341561000c57fe5b5b60008054600160a060020a03191633600160a060020a03161790555b5b609c806100386000396000f300606060405263ffffffff60e060020a60003504166341c0e1b581146020575bfe5b3415602757fe5b602d602f565b005b6000543373ffffffffffffffffffffffffffffffffffffffff90811691161415606d5760005473ffffffffffffffffffffffffffffffffffffffff16ff5b5b5600a165627a7a723058205d72b59bff56d9a16e1b2e0e7f2c05fabda372bbce4e586411886847581df7150029",
    info: {
      abiDefinition: [{...}, {...}],
      compilerOptions: "--combined-json bin,abi,userdoc,devdoc --add-std --optimize",
      compilerVersion: "0.4.10",
      developerDoc: {
        methods: {}
      },
      language: "Solidity",
      languageVersion: "0.4.10",
      source: "contract mortal { /* Define variable owner of the type address*/ address owner; /* this function is executed at initialization and sets the owner of the contract */ function mortal() { owner = msg.sender; } /* Function to recover the funds on the contract */ function kill() { if (msg.sender == owner) suicide(owner); } } contract greeter is mortal { /* define variable greeting of the type string */ string greeting; /* this runs when the contract is executed */ function greeter(string _greeting) public { greeting = _greeting; } /* main function */ function greet() constant returns (string) { return greeting; } }",
      userDoc: {
        methods: {}
      }
    }
  }
}

You can see the abi elements are empty. When I try to reference them,
> contractCompiled.greeter.info.abiDefinition
TypeError: Cannot access member 'info' of undefined

Either geth or eth invokes the compiler with the --combined-json option as shown - could that be the problem? How can any of that be changed? The solc team said they recommend using solcjs now instead of the solc binary, but that is said to be orders of magnitude slower, and introduces needless complexity imho.

**Comment by bas-vk** [comment]
In the upcoming release of geth the compile methods are removed, see https://github.com/ethereum/go-ethereum/pull/3740.

What I would recommend is using Remix. Remix is a smart contract IDE that runs in the browser and can be found here http://ethereum.github.io/browser-solidity/#version=soljson-latest.js. Given the greeter contract I assume you are following the greeter tutorial on ethereum.org. The right panel in Remix will generate the web3 snippet that you can use to deploy the contract.

**Comment by islandBilly** [comment]
Thank you, but I just used the greeter as a short of back test when the
Dapp I was working on didn't work. I have produced a design that allows
someone with no knowledge of Solidity to fill in a form and generate a
contract. My design calls for this contract to be deployed and then, again
using a form, have some transactions run against it.
If you birds are really going to remove the ability to programmatically
compile and deploy a contract, then I'll have to take my design to some
other blockchain technology.

**Comment by islandBilly** [comment]
Sorry, I just realized you were referring to the solc binary and not the
solc-js, which I believe is where you would have pointed me if you'd
realized I was a little farther along. I had been a frustrating slog
through the chaotic bits of documentation and tutorial.

Having installed node.js and npm, I am trying to get my page to find the
solc JavaScript object now. 😉

On Mar 30, 2017 4:25 AM, "bas-vk" <notifications@github.com> wrote:

In the upcoming release of geth the compile methods are removed, see #3740
<https://github.com/ethereum/go-ethereum/pull/3740>.

What I would recommend is using Remix. Remix is a smart contract IDE that
runs in the browser and can be found here http://ethereum.github.io/
browser-solidity/#version=soljson-latest.js. Given the greeter contract I
assume you are following the greeter tutorial on ethereum.org. The right
panel in Remix will generate the web3 snippet that you can use to deploy
the contract.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/go-ethereum/issues/13845#issuecomment-290338830>,
or mute the thread

**Comment by bas-vk** [comment]
I was referring that support for compiling smart contracts in geth will be removed in the next version of geth. That means that `eth.compile.solidity` as you mentioned in your description will not work anymore.

Not sure what you are exactly trying to do but you probably want to take a look at the https://github.com/ethereum/solc-bin repo. This repo contains a javascript solidity compiler that was generated from the solidity compiler using empscripten. Remix also uses this version.

**Comment by VoR0220** [comment]
alternatively you could always use the "os" package in Go, and from there run an exec and json unmarshall into a solc object using the solc "combined-json" output.
