### ISSUE TITLE
Unreal big gas consumption for contract deploying

### ISSUE THREAD

**Issue by AlexeyBarsuk** [ethereum/go-ethereum#13846]
#### System information

Geth version: `1.5.9-stable-a07539fb`
OS & Version: OSX El Capitan

#### Expected behaviour

Successful contract bytecode deploying

#### Actual behaviour
When the size of bytecode is ower 48Kb I get an error "The contract code couldn't be stored, please check your gas amount". When i estimate the gas consumption  with Web3Helpers.web3.eth.estimateGas({data: code}) I get great numbers or "targetgaslimit" value if it is manually set;

#### Steps to reproduce the behaviour
Described here http://ethereum.stackexchange.com/questions/13469/unreal-big-gas-consumption-for-contract-deploying

**Comment by fjl** [comment]
Contract code cannot exceed 24576 bytes. See https://github.com/ethereum/EIPs/issues/170 for details.

**Comment by 3esmit** [comment]
You might want to split your contracts into factories.
