### ISSUE TITLE
eth/filters: JSON headers from newHeads sub should include hash

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/go-ethereum#13858]
#### System information

Geth version: `Version: 1.6.0-unstable`
OS & Version: Windows 10
Commit hash : `288700c4d884321b7de7119b596c6e052fa33b27`

#### Expected behaviour

`newHeads` subscription returns blocks with `hash`, `size`, `totalDifficulty`, `transactions`, and `uncles` properties.

#### Actual behaviour

`newHeads` subscription returns blocks that are missing those 4 properties.

#### Steps to reproduce the behaviour

1. Launch geth with `geth --testnet --rpc --rpcport 8545 --ws --wsport 8546 --wsorigins "*" --wsapi "eth,net"`
2. Open a websocket connection.
3. subscribe to new heads with `method: "eth_subscribe"`, params: ["newHeads"]`
4. Wait for new block.
5. Notice that the block received over the subscription is missing the mentioned 4 properties.

**Comment by fjl** [comment]
This is a design decision. The newHeads subscription returns block *headers*. Depending on your needs, you can get the properties by fetching the whole block after getting the notification.

**Comment by fjl** [comment]
Out of curiosity, what do you use `newHeads` for?

**Comment by MicahZoltu** [comment]
The missing `hash` is the problematic bit, though it is unclear why size and difficulty are not included as they aren't exactly large relative to the overall size of the block.  I can see `transactions` and `uncles` being potentially large, though it is mildly annoying that in order to get that I have to do an extra round-trip.

`newHeads` is used to ensure that my client/dApp gets notified about new blocks ASAP.  The other option, of course, is polling.  When a new block arrives the client will then fetch logs for that block and check to see if the block included any transaction that the client previously submitted and are waiting to be mined (this is where transactions list is needed).  Along with that, the client keeps a local chain of blocks that it has seen to deal with disconnects, node outages and re-orgs (this is where the hash is needed).

**Comment by fjl** [comment]
I can see that the missing `hash` is annoying for your use case. Note that you can check the bloom filter on the header to check whether any of your contract's log topics were included in the block.

**Comment by MicahZoltu** [comment]
At the least, the documentation should be updated to not imply that `hash` will be returned.  https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB#newheads

Unfortunately, the bloom filter isn't enough to reliably get logs for a block due to the issue [this EIP](https://github.com/ethereum/EIPs/pull/597) attempts to solve.  Though, with that EIP implemented the missing hash would still be a problem since the hash is necessary to definitively lookup details about a block.

Really, all the `newHeads` subscription is good for at the moment (that I can see) is a trigger indicating "a new block has been mined, fetch if you want".  It is unclear to me what the use-case is that benefits from just the block header?

**Comment by fjl** [comment]
I've read the EIP proposal. I agree that support for block hashes in filters would be nice. 
Thanks for the suggestion. We'll get `hash` added to the header.

**Comment by karalabe** [comment]
Btw, light clients don't have the transactions and uncles available and fetching them may be quite expensive. As such, I think returning only the header is actually the correct behavior.

**Comment by MicahZoltu** [comment]
Yeah, now that I understand the change was made to support light clients it makes more sense.  That being said, I believe that block `hash` is available to light clients, so this could be included?  Technically the `hash` isn't part of the header _or_ the body, so it doesn't seem like it would violate the "header only" bit (it is metadata outside the scope of block contents) by adding it?

**Comment by karalabe** [comment]
Tadding the hash is a perfectly reasonable request. A pr is already under review for it btw.

**Comment by karalabe** [comment]
@MicahZoltu Could you check with latest develop whether it works as you think it should?

**Comment by MicahZoltu** [comment]
Tested it out and I now see the `hash` in subscription updates.  Thanks!

**Comment by Allzz77123** [comment]
> This is a design decision. The newHeads subscription returns block _headers_. Depending on your needs, you can get the properties by fetching the whole block after getting the notification.
> 
> The decision to send headers rather than complete blocks was based on the observation that most uses of the newHeads subscription don't need all the data. In most cases newHeads is used as a 'heartbeat trigger' that initiates other requests.

**Comment by Allzz77123** [comment]
trigger
