### ISSUE TITLE
How to solve the fuse in the windows environment compiler

### ISSUE THREAD

**Issue by duoduosys** [ethereum/go-ethereum#13850]
#### System information

Geth version: `1.6.0`
OS & Version: Windows
Commit hash : (if `develop`)

follow with the "Installation instructions for Windows"
when I took:
C:\Users\xxx\src\github.com\ethereum\go-ethereum> go install -v ./...
the error is :

C:\Users\Administrator\src\github.com\ethereum\go-ethereum>go install -v ./...
github.com/ethereum/go-ethereum/vendor/bazil.org/fuse
"# github.com/ethereum/go-ethereum/vendor/bazil.org/fuse
vendor\bazil.org\fuse\error_std.go:27: undefined: errNoXattr
vendor\bazil.org\fuse\fuse.go:1345: undefined: attr
vendor\bazil.org\fuse\fuse_kernel.go:166: undefined: syscall.O_DIRECTORY
vendor\bazil.org\fuse\fuse_kernel.go:175: undefined: syscall.O_ACCMODE
vendor\bazil.org\fuse\fuse_kernel.go:404: undefined: attr

How to solve the fuse in the windows environment compiler? thank you very much。

**Comment by fjl** [comment]
The workaround is to use `go install -v ./cmd/...`. I have updated the wiki page to reflect that. Sorry for the inconvenience.
