### ISSUE TITLE
Why the weak encryption on wallets?

### ISSUE THREAD

**Issue by williambanks** [ethereum/go-ethereum#13865]
I was examining my wallet in a text editor and noticed that the encryption is listed as AES-128
AES-128-CTR while not exactly broken, is weaker than current recommendations from NIST and would prevent geth from being used in any application that needs certify to current standards.
The current standard is AES-384 or better.

It seems pointless to use the weaker level encryption here and I'm just wondering why not move to something stronger, the impact should be minimal.

https://www.cnss.gov/CNSS/openDoc.cfm?5XLrL7qgAhBGQmbc6LWaIg==

Thanks!

**Comment by fjl** [comment]
That link is not accessible to us. We believe that AES-128 is still suitably strong for the time being.
[NIST SP 800-57 Pt. 1 Rev. 4 (dated Jan 2016)](http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r4.pdf), page 56, lists algorithms of strength 128 as acceptable through and beyond year 2031.

**Comment by williambanks** [comment]
It's ok to have beliefs, but you should support them with better evidence.

I'll try to find a better link for you to review, but the one you're citing is for the protection of unclassified information and is optimized for backwards compatibility with legacy systems.  

What you're failing to understand is that unclassified information doesn't need protection in the first place.  It's meant to prevent snooping by casual observers but...

A large portion of users will be / are on shared hosting instances or "VPS", a lot of information is protected by the strength of the protection around those keys.  As far as I can tell, the jump to AES-384 or stronger which would be suitable for Top-Secret and below, would be trivial to make and this isn't java where the key strength is neutered by Oracle.   So the question is why not?
  
Also why did you unilaterally close the topic, is there a place this is supposed to be brought up? Because it is something important that people need to understand

**Comment by williambanks** [comment]
Here's the correct link...
http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-175B.pdf
