### ISSUE TITLE
why geth take so many cpu sources

### ISSUE THREAD

**Issue by ucwong** [ethereum/go-ethereum#13871]
![image](https://cloud.githubusercontent.com/assets/22344498/24750806/cdee4646-1af9-11e7-973f-98ae2c7af1df.png)

no '--mine' option

**Comment by karalabe** [comment]
I'm guessing because it's importing the chain? Are you syncing? How did you start geth?

**Comment by ucwong** [comment]
@karalabe ... I think I have done already for a long time . Cpus are still keeping high using.

I have never meet this before , util I compile from the latest source code. It seems to do the cpu minning , but I haven't used --mine option.

**Comment by karalabe** [comment]
Please provide some logs, I've no idea what it's doing without actually seeing some output.

**Comment by ucwong** [comment]
@karalabe It is normal

![image](https://cloud.githubusercontent.com/assets/22344498/24792661/8aa827b8-1bb1-11e7-8376-58edefdd555e.png)

**Comment by karalabe** [comment]
How much CPU is it using now? How many peers do you have?

**Comment by obscuren** [comment]
You appear to be mining, which is causing the high CPU usage. Please let us know how you started geth

**Comment by karalabe** [comment]
No, the logs would contain the "commit work bla bla bla" if he were mining.

**Comment by karalabe** [comment]
RTFM, nevermind.

**Comment by obscuren** [comment]
Yes, exactly, and it does :-D

**Comment by ucwong** [comment]
@obscuren start like this geth --rpc --cache=512 --maxpeers 100

**Comment by ucwong** [comment]
@karalabe but I restart with older version , It is ok with low cpu cost

**Comment by ucwong** [comment]
@karalabe cpus nearly 100% used

**Comment by ucwong** [comment]
![image](https://cloud.githubusercontent.com/assets/22344498/24798401/572b66c2-1bc8-11e7-958a-0b54cbb0ddbd.png)

**Comment by karalabe** [comment]
Hmm, do you have a remote miner attached?

**Comment by karalabe** [comment]
Ok, I found the issue. When a remote miner asks for work, it starts the local miner to create the blocks. The new ethash implementation assumed that a thread count of 0 means use all cores, hence why it started mining too, even though only remote work was requested.

This is a strange side effect of the way the miner is designed. I'll fix it in a moment.

**Comment by ucwong** [comment]
@karalabe thank you very much

**Comment by karalabe** [comment]
Could you please verify if this fixes the issue for you? https://github.com/ethereum/go-ethereum/pull/13880

**Comment by karalabe** [comment]
This should be fixed now. Please try latest master.

**Comment by fidenz-chim** [comment]
Faced the same problem and limited the number of threads to 1 by using geth option `--minerthreads 1`. That brought the the CPU !100 from ~370
