### ISSUE TITLE
General request: Make Ropsten checkpointing part of next release

### ISSUE THREAD

**Issue by GriffGreen** [ethereum/go-ethereum#13884]
It is VERY hard to get on the Ropsten Testnet these days

https://www.reddit.com/r/ethereum/comments/63vd1l/these_ropsten_revived_instructions_do_not_seem_to/

https://github.com/ethereum/ropsten/issues/4

If we were able to add checkpointing to the next geth client, that would be incredibly helpful 

Much love,
Griff

P.S. I don't know what I'm talking about

**Comment by holiman** [comment]
>Much love,
>Griff
> P.S. I don't know what I'm talking about

I'll give a :heart: just for the nice tone

**Comment by karalabe** [comment]
@GriffGreen Could you try with Geth 1.6.0? We didn't add any chckpointing ot blacklisting, but we did change to new bootnotes and added a bit of connectivity soup-ups so in theory it should be a bit better now.

**Comment by karalabe** [comment]
Closing this as the new bootnodes and the p2p tweak should help sync correctly. If not, please shout out and I'll reopen.
