### ISSUE TITLE
clean up "Get geth" installation instructions

### ISSUE THREAD

**Issue by brobits** [ethereum/go-ethereum#13888]
the page at: https://github.com/ethereum/go-ethereum/wiki/Getting-Geth has instructions to install geth via:

```bash
bash <(curl https://install-geth.ethereum.org)
```

but the URI `https://install-geth.ethereum.org` appears to be broken.  Can we simply redirect this page to the current install instructions here: https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Mac

**Comment by karalabe** [comment]
https://geth.ethereum.org/install/ :)

**Comment by brobits** [comment]
Yes! These instructions are also wonderful.  A google search for "get geth" points to https://github.com/ethereum/go-ethereum/wiki/Getting-Geth, which is outdated.  I'm suggesting a redirect to more updated instructions for google visitors.
