### ISSUE TITLE
Pause miner while not synch'ed

### ISSUE THREAD

**Issue by o0ragman0o** [ethereum/go-ethereum#1398]
<code>admin.chainSyncStatus</code> returns the known blockchain  synchronisation status including the number of blocks to be imported, e.g, 
<pre>{
  blocksAvailable: 0,
  blocksWaitingForImport: 83,
  estimate: '14m21.854776871s',
  importing: 38
}</pre>

Currently go-ethereum does not inform the miners that the blockchain is out of synch leading to a wastage of electricity.

Can a 'pause mining' instruction be implemented across the clients and miners please?

**Comment by obscuren** [comment]
No, this will not be implemented, this will be highly insecure. This was once implemented and was a big mistake. Humans decide whether they should mine. Not the machine.

**Comment by o0ragman0o** [comment]
Thanks for considering it Jeff.  Could you give a brief explanation of what
kinds of insecurities arose?

**Comment by obscuren** [comment]
A remote can disable your mining by giving you a chain (valid or not) :-)
