### ISSUE TITLE
Genesis block ... :-)

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#1402]
Deploy genesis block & restart the network

FTR this is a task! This is **NOT** an announcement.

# note to self!!!

UNCOMMENT BEFORE FRONTIER

```go
	bc.genesisBlock = bc.GetBlockByNumber(0)
	if bc.genesisBlock == nil {
		// XXX Uncomment me before Frontier
		//return nil, ErrNoGenesis
		genesis, err := WriteTestNetGenesisBlock(bc.stateDb, bc.blockDb, 42)
		if err != nil {
			glog.Fatalln("genisis err", err)
		}
		bc.genesisBlock = genesis
		bc.currentBlock = genesis
	}
```

**Comment by tinybike** [comment]
Do it! >:)

**Comment by tymat** [comment]
Is it happening?

**Comment by d11e9** [comment]
:+1:

**Comment by obscuren** [comment]
Not yet! :-)

**Comment by pompomJuice** [comment]
You give hart attack, I'm not ready!

I still need to spin up some hamsters to power my miners!

**Comment by linagee** [comment]
:+1:

**Comment by rfikki** [comment]
One of these days. Looking forward to an easier way to sync to non private test net.

**Comment by alchemist2014** [comment]
Very soon the Genesis Block will launch, it appears. I'm excited to watch this all play out from the days of reading the Whitepaper.

**Comment by obscuren** [comment]
Thank the spammers, @rfikki :-p

**Comment by 21xhipster** [comment]
Wanna cry :100:

**Comment by Tusk-Bilasimo** [comment]
Show Starter +1

**Comment by obscuren** [comment]
This can now be closed, see #1402 :-)

**Comment by caktux** [comment]
This is #1402 ;) did you mean #1509 ?

**Comment by obscuren** [comment]
haha oops, indeed :-D
