### ISSUE TITLE
No more "standard" interfaces

### ISSUE THREAD

**Issue by nmushegian** [ethereum/go-ethereum#1403]
"Official" namereg is a nuisence. Ok, maybe this one is necessary because the dapp browser is an official project.

But the IBAN asset interface is not general enough to have a chance at being the central asset registry, but also complex enough to be a pain to make your assets conform to. Let standards emerge once people see the best asset contract architectures in the wild.

Are we going to have the developer's personal dapps get first-class support? If no, please don't try to anticipate the best contract system designs, it's almost the same thing.

So the issue is:  Is there an official policy on this? How did you decide to give the go-ahead for IBAN contracts but not a standard voting contract or key management contract, for example? How can I get my *contract* architecture decisions into the core client too?

**Comment by zelig** [comment]
where is the IBAN contract in the core client? The namreg is indeed used natively by the client. If a better system is in place, we are open to switch over. 

I would like to have a round table on DEVCON1 around exactly these topics, i.e., dapp devel best practices, standard interfaces, interface starndards, deployment and development infrastructure, distribution, off-chain info standards, internatspec, testing, etc. 

All this said, is there an issue you are actually reporting? :)

**Comment by linagee** [comment]
This doesn't sound like an issue. :-1:

**Comment by nmushegian** [comment]
https://github.com/ethereum/go-ethereum/blob/acd85fe95f025384885ed09560e32b227d80b26f/jsre/ethereum_js.go#L4270

Looks like opinions about how contracts should be architected in ethereum official code. This is the only remnant I can find right now, but I'm pretty sure I saw more in either web3 or in geth. It doesn't show in github search so maybe it's been removed already ?

> I would like to have a round table on DEVCON1 around exactly these topics, i.e., dapp devel best practices, standard interfaces, interface starndards, deployment and development infrastructure, distribution, off-chain info standards, internatspec, testing, etc.

Great. The issue I'm filing is that I want a policy that is a result of a discussion like this which guides devs that contribute to ether core. I'm concerned about the damage bad contract architecture decisions will cause if they are baked into the client.

**Comment by frozeman** [comment]
+1

I fully agree. These kind of top level stuff should be agreed on in the community and tested in the wild, before made a standard.
We already have IBAN stuff in web3, which i don't see the point for it now.

**Comment by nmushegian** [comment]
bump!  What the heck guys?
https://github.com/ethereum/web3.js/commit/3373b8f660c2cbd47d8f944c76faf6a36709c868

**Comment by julian1** [comment]
Agreed. IBAN should not be a first-class citizen especially when it's apparently subject to change. Please let core standards emerge.

**Comment by obscuren** [comment]
Move this discussion to web3 repo. Go ethereum only makes use of web3 and does not dictate the way forward. These discussions are handled elsewhere.
