### ISSUE TITLE
defaultAccount and coinbase null/undefined after upgrading geth

### ISSUE THREAD

**Issue by scottzer0** [ethereum/go-ethereum#1404]
after upgrading to the geth where account management got some reworkin', i no longer have coinbase or the defaultAccount set.  this affects all sendTxs. 

Mac OS
I upgrade using `brew reinstall ethereum --devel --build-from-source`

**Comment by zelig** [comment]
yes the coinbase needs to be explicitly set from now on. 
Relying on the order of accounts is discouraged (but at least they are correct now reflecting creation date of your keys). The new solution is backward compatible, so you can just use your first account as your coinbase if you used to do nothing.

    geth --etherbase 0x567fe258ab7c7c709034266cc6000832fffa --unlock 0 console 2>> geth.log

let me know if you have issues.

**Comment by scottzer0** [comment]
you have to specify `--etherbase` on startup now?

**Comment by joeykrug** [comment]
How do you set the default account?

**Comment by scottzer0** [comment]
joey, that is how you set it, but it's not okay.

so i get the problem solved here, but i'm either missing the best-practice here (possibly due to just upgrading and carrying and old account over) or the solution is interim.  adding `--etherbase [my account addy]` to my geth startup args isn't going to fly.  i know i'm missing something.  config file?  export and re-import account?  help me out.

**Comment by tinybike** [comment]
Suggestion: if the `--etherbase` flag isn't set, have it default to whichever account is being unlocked.  Requiring users to manually specify `--etherbase` and `--unlock` isn't practical.

**Comment by scottzer0** [comment]
so we now loop through all the accounts and do an eth_sign test to figure out which one has been unlocked by the client and use that.  

please let us know if this is a bad practice (other than a total hacky, hopefully interim fix) and certainly if there's some better way.  it feels like we're missing something here.

jack, you need not also comment after me.

**Comment by zelig** [comment]
ok so with frozen rc2 I fixed that and you do not need to specify etherbase on command line, it will default to the first created account.
Also --etherbase can now take index like `--etherbase 2` to set it to account 2.
