### ISSUE TITLE
Consider eth.resend for removal

### ISSUE THREAD

**Issue by linagee** [ethereum/go-ethereum#1407]
It seems eth.resend example: https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#ethresend just doesn't work anymore because you get an error "not enough gas" instead of going through and having to resend/correct it. (Wasn't able to get the demo shown in wiki running.)

Also, it uses required args in implementation, but optional args in the wiki. (Unless I am misunderstanding how this works...)

Please consider for removal on implementation on wiki. (Or fix up wiki or implementation to be consistent if this still has some limited usage.) Please also consider this issue as low priority, as I'd prefer everyone work on getting Frontier out the door before working on this! (But... wouldn't everyone?)

**Comment by veox** [comment]
I've found that, different from what's said on the wiki, the gas price and amount are not optional.

`eth.resend` throws (with sparce/cryptic traceback) if the "optional" arguments are missing. In addition, `geth` seems to remove the tx anyway from `eth.pendingTransactions` if that happens.
