### ISSUE TITLE
Mined Tx Hash not Unique

### ISSUE THREAD

**Issue by ppratscher** [ethereum/go-ethereum#1408]
I found lots of not unique tx hashes included in different blocks:

> eth.getTransactionFromBlock(27396, 0).hash
'0x3d75888b092b7d9084623cbfcc2056b4f3fae314b0527e7dbb0614c366434c1f'
> eth.getTransactionFromBlock(28942, 1).hash
'0x3d75888b092b7d9084623cbfcc2056b4f3fae314b0527e7dbb0614c366434c1f'

or:
> eth.getBlock(396881).transactions[0]
'0xde3d8863034e0fb5d7111ace4d3fbad6e6cb1250fe560357e4f2913d99d45e95'
> eth.getBlock(376381).transactions[0]
'0xde3d8863034e0fb5d7111ace4d3fbad6e6cb1250fe560357e4f2913d99d45e95'

I guess this should not be the case?! If needed I can provide a full list of affected blocks.

**Comment by karalabe** [comment]
Can you find similar issues in the recent blocks? I.e. north of 560K (more recent is better to debug)?

**Comment by ppratscher** [comment]
jep:

>Tx with hash 0x39f1a5c73ee86bddd23b67a13f983a4a5c6bfaf4dc401aba824f16144b18cc5c is in block 607202 and 607098
>Tx with hash 0x1a409622ef8baeb07e2fb46079526c131d33f8c61be8fba35acfcbba6d5d7c6d is in block 727053 and 747250
>Tx with hash 0xbd8671ce8ca6328a6b7984e537b7db5350c77d8c7a376677a0472a7e338cdb42 is in block 727053 and 746641
>Tx with hash 0x46e24bb2fa9ed7abd2e06064ea0a9cb974aec73c0f80891d39439796a3192f7f is in block 722455 and 727178
>Tx with hash 0xc4ab9741d72b7ea983c41cfa11f6818f6f5d25bfb1fb8b8932c4d40b1d7b6c04 is in block 722451 and 727175
>Tx with hash 0x77c9305235dc542308c371bb9d299907db5269c0e87f4149e4ecfe58d5d2f589 is in block 722076 and 727171
>Tx with hash 0x0dac3c312208c81e914e8e0df56c876f624d576cccae6e7e8fb4700763e1fd40 is in block 713252 and 713773

**Comment by karalabe** [comment]
So, we tracked down the bug. There was an omission in calculating the transaction hashes: the sender wasn't included, so completely different transactions (some contract creation) managed to hash to the same thing.

I'll open a PR with a fix soon. Thanks for reporting it! Btw, although unpleasant, this doesn't have any negative effect on the network of the chain. The transaction hashes are used only as internal IDs. I'll get back to this once it's sorted out :)

**Comment by paulvi** [comment]
So what is unique identifier for transactions,  
if txid (transaction id) can be duplicated? (And it was in the mainnet.)

**Comment by karalabe** [comment]
They cannot and they have not been. It was a bug in an ancient version of geth.
