### ISSUE TITLE
geth wallet import results into duplicate accounts

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#1411]
with `geth` develop 9c3db1b on OSX:

Before wallet import:

```
$ geth account list
Account #0: {ee8eeee345c4431b38a3472ed31fa6e7981785a7}
```

Now importing a test wallet that I used during the EtherCasts presale video:

```
$ geth wallet import /path/to/ethereum-wallet-9a63d185a79129fdab19b58bb631ea36a420544e.json

Passphrase:
Address: {9a63d185a79129fdab19b58bb631ea36a420544e}
```

Checking the list of accounts:
```
$ geth account list
Account #0: {9a63d185a79129fdab19b58bb631ea36a420544e}
Account #1: {9a63d185a79129fdab19b58bb631ea36a420544e}
Account #2: {ee8eeee345c4431b38a3472ed31fa6e7981785a7}
```

Instead of the same `9a63d185a79129fdab19b58bb631ea36a420544e` address to be present as account 0 and 1, I would expect only a single entry for this address.

The `~/Library/Ethereum/keystore` directory has two files for this key:
```
-rw-------   1 user  staff  491 Jul  6 12:46 UTC--2015-07-06T10:46:03.576158588Z--9a63d185a79129fdab19b58bb631ea36a420544e
-rw-------   1 user  staff  491 Jul  6 12:46 UTC--2015-07-06T10:46:04.647007995Z--9a63d185a79129fdab19b58bb631ea36a420544e
```

**Comment by karalabe** [comment]
@zelig, any ideas? I also saw a similar duplication in my datadir.

**Comment by tgerring** [comment]
Possibly related, on recent upgrade, I got an extra account. This is the second time I've observed, especially when they displace the 0th account position

**Comment by zelig** [comment]
will have a look. new to me. is it only wallet import?

**Comment by frozeman** [comment]
**Additionally please consider this:**
I think file or folder names should never contain `/` as this is a path separator character and will only lead to odd problems on some OS!
And the `UTC--` is not necessary as `Z` says that its UTC. I would name it as follows:
`2015-07-08T12-44-25-579996753Z--b1a2b43a7433dd150bb82227ed519cd6b142d382`

**Comment by tgerring** [comment]
We could also remove a lot of the extraneous '-' and go with a still-verbose `20150708T124425Z-b1a2b43a7433dd150bb82227ed519cd6b142d382`. Not sure if naming is still up for discussion

**Comment by frozeman** [comment]
I agree with that one too. And the naming should definitely be changed, having `/` is a no go and will just lead to problems, better we change that before frontier!

**Comment by frozeman** [comment]
@obscuren i find that kind of important before frontier..

**Comment by fjl** [comment]
@frozeman the names start with UTC so they sort after any filename with just hex characters (old keys).
