### ISSUE TITLE
cmd/geth: rename etherbase to coinbase

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1420]
If "etherbase" is really preferred over "coinbase", let's make it consistent everywhere.

The output of `geth attach` uses `coinbase`

Geth
Version: 0.9.35
Git Commit: aa4502060b50733a3a82a0ab575eac0731cdb7ca
Protocol Versions: [61 60]
Network Id: 0
Go Version: go1.4.2

**Comment by obscuren** [comment]
Thanks. @bas-vk

**Comment by zelig** [comment]
coinbase is the name used by RPC/web3.js too unfortunately

**Comment by alexvandesande** [comment]
Yup, some people are already confused about this: https://www.reddit.com/r/ethereum/comments/3cjcz4/to_set_up_gpu_mining_you_need_a_coinbase_account/

**Comment by radster360** [comment]
Yes. I do agree that etherbase is probably the right term, but the nomenclature of "coinbase" so so out there, it will take some time. Someone referred to "etherbase" in one of the Skype group and I had to ask what was "etherbase"? Though maybe the respond from the team might have gotten lost somewhere, but I figured it was so when I used the "coinbase" value in my Geth CLI.

**Comment by tinybike** [comment]
For what it's worth, I prefer the term coinbase, just because people already know what that means.  The less new jargon you can introduce, the better.  (Also, in my opinion, "coinbase" is a lot nicer phonetically than "etherbase"...)

**Comment by obscuren** [comment]
Agreed. The issue I have with coin base is Ethereum doesn't have the concept of a coin like Bitcoin does.

**Comment by zelig** [comment]
etherbase is pretty transparent. for across the board consistency we could allow etherbase in rpc/js (keeping coinbase for backward compatibility).

**Comment by smartsmart123** [comment]
I think coinbase is the standard terminology for block reward transactions.  Might as well keep it that way.

**Comment by fjl** [comment]
So which one should it be, 'etherbase' or 'coinbase'?

**Comment by obscuren** [comment]
I think we'll have to change our own `etherbase` to `coinbase`. It's an adopted term and I'm quite fine going with that.

**Comment by fjl** [comment]
Great.

**Comment by tgerring** [comment]
Quick search for anyone deciding to work on this task:

https://github.com/ethereum/go-ethereum/search?utf8=%E2%9C%93&q=etherbase

**Comment by fjl** [comment]
Not gonna happen for Homestead.

**Comment by dherbst** [comment]
I put PR #15211 up for this.  Looks like one of the travis tests timed out.  Please let me know if you have any feedback on the PR.
