### ISSUE TITLE
Trace  Tx

### ISSUE THREAD

**Issue by lyddream** [ethereum/go-ethereum#14313]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

####  according to https://etherchain.org/tx/0x15598b8f8c34ed6b86f2ee165fa6fc0d0a2ad0ae70164f4695db84bca3633e9c.
we can see that , the TX has some Invoked Transactions。 how to trace the Tx and get the Invoked Transactions via go-ethereum.

#### Tx Example vi getTransaction: {
  "blockHash": "0x981b043471f98f492ef60d545a904f082dad5d47dc31653666eae9ac0e2801b4",
  "blockNumber": "0xb21a1",
  "from": "0x712f44be8516cbad135470abe49c33aac2cc96ab",
  "gas": "0xf4240",
  "gasPrice": "0x4be71addb",
  "hash": "0x793f48907650c61346056cec43b4a4919ce1fe8ac972f92d9c7cd1d2c5ff1b60",
  "input": "0x502a26a10000000000000000000000005674eeb2dab4ac7f6fc099763657abd15adb960b",
  "nonce": "0x22f6",
  "to": "0xd3bea12ad9d9c787ff3990e885d7d06906e53213",
  "transactionIndex": "0x2",
  "value": "0x0",
  "v": "0x1b",
  "r": "0x27f4d5bab4bd6f7b537a8848421606ffc6f03242e8f869f89ee69bbc91a9c408",
  "s": "0x5204d6e5f12834c50753d8c4cb67414ead2eef9cc8f1f822a191002df6dafdb2"
}

Transaction Receipt Example vi getTransactionReceipt: {
  "blockHash": "0x981b043471f98f492ef60d545a904f082dad5d47dc31653666eae9ac0e2801b4",
  "blockNumber": "0xb21a1",
  "contractAddress": null,
  "cumulativeGasUsed": "0x2269e",
  "from": "0x712f44be8516cbad135470abe49c33aac2cc96ab",
  "gasUsed": "0xa9f9",
  "logs": [
  ],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "root": "0xeafac96cca77eabdd3390524e1942bb8a8e43d36b8947d809a6ce63b14897f6a",
  "to": "0xd3bea12ad9d9c787ff3990e885d7d06906e53213",
  "transactionHash": "0x793f48907650c61346056cec43b4a4919ce1fe8ac972f92d9c7cd1d2c5ff1b60",
  "transactionIndex": "0x2"
}

#### Backtrace

````
[backtrace]
````

**Comment by Hasbullah110782** [comment]
Terima kasih thank you saya sudah bisa memperbaikinya.

**Comment by Hasbullah110782** [comment]
Bantu saya memecahkan setiap masalah yg saya alami saudaraku.

Pada tanggal Kam, 12 Apr 2018 22.33, Hasbullah110782 <
notifications@github.com> menulis:

**Comment by Hasbullah110782** [comment]
Saya harap selalu bantu saya memecahkan semua masalah yang saya hadapi..thank you my friend.

**Comment by holiman** [comment]
You can use the tracing functionality: https://github.com/ethereum/go-ethereum/wiki/Tracing:-Introduction
