### ISSUE TITLE
Signing and verifying do not produce correct results

### ISSUE THREAD

**Issue by Xib1uvXi** [ethereum/go-ethereum#14319]
#### System information

Geth Version: 1.5.7-stable
Git Commit: da2a22c384a9b621ec853fe4b1aa651d606cf42b
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.4
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.7.4_2/libexec

#### Expected behaviour
Execute the following on the Geth cli:  
```
const account = '0xfa3da03af4709506b56b26e409d1cdacf9d16fc5';
let sha3Msg = web3.sha3("abc");
let gethMsg = web3.sha3("\x19Ethereum Signed Message:\n" + sha3Msg.length + sha3Msg);
let signature = web3.eth.sign(account, sha3Msg);
let r, v, s;

r = signature.slice(0, 66);
s = '0x' + signature.slice(66, 130);
v = '0x' + signature.slice(130, 132);
v = web3.toDecimal(v);
if (v != 27 && v != 28) v += 27;
```
Expect:  
```
account == auth.verify.call(gethMsg, v, r, s)
```
the gethMsg is right?
```
gethMsg 
let sha3Msg = web3.sha3("abc");
let gethMsg = web3.sha3("\x19Ethereum Signed Message:\n" + sha3Msg.length + sha3Msg);
```

Where "address" is an instance of the contract:
```
contract Auth{
  function test(bytes32 hash, uint8 v, bytes32 r, bytes32 s) constant returns (address) {
      return ecrecover(hash, v, r, s);
  }
}
```

#### Actual behaviour
String returned by verify does NOT match the account which was used for signing the hash

#### Steps to reproduce the behaviour
See above

#### Backtrace

````
None, no exception
````

**Comment by bas-vk** [comment]
This question is asked more often, I will add an example on the wiki.

**Comment by Xib1uvXi** [comment]
Thx!!!! @bas-vk
