### ISSUE TITLE
Contracts never get mined on a private network

### ISSUE THREAD

**Issue by msolima** [ethereum/go-ethereum#14315]
#### System information

Geth
Version: 1.6.0-unstable
Git Commit: cc13d576f07fb6803e09fb42880591a67b8b0ef6
Architecture: amd64
Protocol Versions: [63 62]
Go Version: go1.8
Operating System: linux

#### Expected behaviour
Contract should be mined quickly especially that I set the gas to the highest value

#### Actual behaviour

I'm having an issue where my contracts on my private network **never** get mined.
and then I get `Error: Contract transaction couldn't be found after 50 blocks undefined`

I'm using 
Geth
Version: 1.6.0-unstable
Git Commit: cc13d576f07fb6803e09fb42880591a67b8b0ef6

my genesis block has:

```
"difficulty": "0x400",
"gasLimit": "0x8000000",
```

and this is how am deploying the contract

```
var greeter = SampleContract.new(_greeting,{from:web3.eth.accounts[0], data: code, gas: 4000000}, function(e, contract){
    if(!e) {

        if(!contract.address) {
            console.log("Contract transaction send: TransactionHash: " + contract.transactionHash + " waiting to be mined...");

        } else {
            console.log("Contract mined! Address: " + contract.address);
            console.log(contract);
        }

    }else{
        console.log(e)
    }
})
```

any idea what's happening ? are you guys seeing this issue?

**Comment by karalabe** [comment]
https://github.com/ethereum/go-ethereum/issues/13876#issuecomment-293403877 :)
