### ISSUE TITLE
Dev mode with networking - PR welcome?

### ISSUE THREAD

**Issue by drouillard** [ethereum/go-ethereum#14325]
Hello,

I am trying to create an Ethereum private network that runs across multiple physical hardware like an Intel Edison or a Rasperry PI 3.  The private network would consist of many pieces of physical hardware, so the network does just exist on 1 physical machine.

I have run into the following situation

* In --dev mode they can mine, but they can't communicate because networking is specifically disabled. E.g. maxpeers set to 0, listening turned off

* In 'prod' mode I can get the nodes to discover each other with some work, but I can't get them to mine. I have tried a custom genesis block and set the difficulty, but the generation of the DAG requires too much upfront memory. I can post the stack, but the message says it can't allocate the 2GB of memory needed for the DAG, and that makes sense as the devices don't have that. I also tried computing the DAG on one-machine and sharing the 1GB file, but that also did not seem to work and seems error prone. I also tried increase the swap but that didn't seem to work and is dubious to begin with.

Would you be open to a PR that allowed networking in developer mode, or have other thoughts on how to make this work?  My plan is to allow another flag to be passed in, --dev-networking or similar and then look at that flag to know whether to disable networking when in --dev mode.

Any guidance you can offer would be appreciated. I would take of doing the work but wanted to see if this would be accepted. For now I am going to fork/modify and compile locally.

Thanks.

**Comment by fjl** [comment]
So you basically want a lighter proof of work. --dev mode is the wrong tool for that.

The master branch contains a proof of authority engine that uses less resources and
might be a better fit for a small private network. You'll just need wait a few more days ;)

**Comment by drouillard** [comment]
That works. Thanks.
