### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by RyanF109** [ethereum/go-ethereum#14331]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Build

#### Actual behaviour

/go-ethereum $ make all
build/env.sh go run build/ci.go install
ci.go:174: You have Go version go1.6.2
ci.go:175: go-ethereum requires at least Go version 1.7 and cannot
ci.go:176: be compiled with an earlier version. Please upgrade your Go installation.
exit status 1
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 1

/go-ethereum $ make geth
build/env.sh go run build/ci.go install ./cmd/geth
ci.go:174: You have Go version go1.6.2
ci.go:175: go-ethereum requires at least Go version 1.7 and cannot
ci.go:176: be compiled with an earlier version. Please upgrade your Go installation.
exit status 1
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 1

#### Steps to reproduce the behaviour
See above

#### Backtrace

````
[backtrace]
````

**Comment by lmars** [comment]
@RyanF109 see the error message:

```
ci.go:174: You have Go version go1.6.2
ci.go:175: go-ethereum requires at least Go version 1.7 and cannot
ci.go:176: be compiled with an earlier version. Please upgrade your Go installation.
```

You need to upgrade your Go installation to 1.7 or later.

**Comment by robbinhan** [comment]
@karalabe ok thanks

**Comment by BUNO19** [comment]
> @robbinhan Please use a fresh go-ethereum version. You are hitting an ancient bug.

I have the same error with go1.14, and I got clone from the repository directly. So that supposed to be the lastest version? Would you please tell me how can I fix this?

**Comment by AdB9** [comment]
> > @robbinhan Please use a fresh go-ethereum version. You are hitting an ancient bug.
> 
> I have the same error with go1.14, and I got clone from the repository directly. So that supposed to be the lastest version? Would you please tell me how can I fix this?

I'm facing the same issue, did you find anything ?
