### ISSUE TITLE
block download canceled, geth 1.5.9 would not download blocks

### ISSUE THREAD

**Issue by Kramerr** [ethereum/go-ethereum#14333]
#### System information

Geth version: `geth version` 1.5.9
OS & Version: Windows/Linux/OSX : Windows 10
Commit hash : (if `develop`)

#### Expected behaviour
Syncing blocks

#### Actual behaviour
![untitled](https://cloud.githubusercontent.com/assets/27564927/25064454/99b53bfe-21d0-11e7-9d80-8b71de2c11ff.png)

Cant seem continue syncing pass block 1292880

**Comment by karalabe** [comment]
Please try with our latest release, v1.6.0.

Also please provide some extended logs by running `--vmodule=downloader=5`.

**Comment by karalabe** [comment]
Closing with not enough info. Please provide some more infos if you wish to reopen.
