### ISSUE TITLE
SIP: support for HTTP redirect entries in Swarm Manifests

### ISSUE THREAD

**Issue by homotopycolimit** [ethereum/go-ethereum#14345]
Currently manifest entries are key/value pairs resolving keys to hashes; these hashes are either swarm hashes of files or of further manifests.

Manifests can currently have the empty path as a 'default entry' - a hash that will be loaded when the manifest is addressed on the http api. 
In practice this often means that a manifest might have an empty path entry and an 'index.html' entry that resolve to the same hash. When updating index.html, both of these entries have to be updated in the manifest (they may even be entries in different manifests entirely for example path 'i' might be a branching manifest with entries for 'mages/' and 'ndex.html)

Currently typical manifest entries look like this:
`{"path":"Swarm","hash":"0294e48456a49fe7c02162c83b068075ff9ae6aaafb46439dba32da7de548379","contentType":"application/bzz-manifest+json","status":0}`

**Suggestion:**
I suggest we allow manifest entries of the form:
`{"path":"YAY","target":"Swarm","Type":"HTTP-302-Redirect"}`

The idea is that calling up the 'YAY' path would yield an http 302 redirect response, redirecting the browser to 'Swarm'.

This functionality could be used in future for the 'default entry' of a manifest redirecting to index.html and this functionality is also useful when recursively uploading directories to swarm that contain symlinks. A link on the filesystem could be represented as a redirect in the browser and vice versa.

**Comment by homotopycolimit** [comment]
In addition it might be prudent to disable the 'empty path' entirely but instead allow for a special 'default entry' in the manifest that takes the form of a redirect.

**Comment by lmars** [comment]
This is a good opportunity to model the idea of a "symlink" for both mounted manifests and access via HTTP.

In a Unix filesystem, a symlink is a file with type `S_IFLNK (0120000)` containing a path to another file (either absolute or relative). These files can already be stored in swarm (manifest entries have a `Mode` field which can be set to `S_IFLNK`) and so will work as expected when mounted.

For HTTP, one option is to consult the `Mode` field, and if it is `S_IFLNK` then retrieve the content of the hash and perform a redirect. This however isn't very user friendly so we could also support an explicit manifest field like `HTTPRedirectTo string` which if set then results in a 301 redirect.

Ref #3601.

**Comment by holisticode** [comment]
Not sure I understand the desired behavior here: 301 Redirect usually results in a client side redirect - the complete HTTP request is aborted, resulting in a new one with the target address. 

So if a manifest contains a 301 Redirect, wouldn't this result in other manifest entries for the manifest in question being ignored, thus not resolved? Isn't this rather something for the internal reader, which when hitting a `S_IFLNK` just resolves that entry via the linked hash, instead of resulting in a HTTP Redirect? 

Or is this a feature where a manifest may contain such a `S_IFLNK`, and then on purpose everything else is disregarded, resulting in a real HTTP Redirect?

**Comment by lelikalf** [comment]
type

**Comment by nonsense** [comment]
@homotopycolimit let's continue this conversation at https://github.com/ethersphere/swarm where the Swarm codebase lives from now on.
