### ISSUE TITLE
mobile: avc: denied { read } for name="/" dev="tmpfs" ino=4110 scontext=u:r:untrusted_app

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#14340]
#### System information

Geth version: 1.6.0
OS & Version: android

#### Expected behaviour

no flooding of debug output

#### Actual behaviour

about once every second I see this in logcat
type=1400 audit(0.0:24443): avc: denied { read } for name="/" dev="tmpfs" ino=4110 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:device:s0 tclass=dir permissive=0big

#### Steps to reproduce the behaviour

start in process node on android

----
other than that 1.6.0 is a wonderful release - thanks so much for your work!

**Comment by ligi** [comment]
not yet sure if this is related but it might be. Unfortunately sometimes the syncing also stops and I have to restart the node - here some logs for this:

```
04-22 15:35:37.822  9906  9927 E GoLog   : INFO [04-22|13:35:37] Block synchronisation started 
04-22 15:35:37.850  9906  9927 E GoLog   : INFO [04-22|13:35:37] Mapped network port                      proto=tcp extport=39681 intport=39681 interface="UPNP IGDv2-IP1"
04-22 15:35:39.310  9906  9927 E GoLog   : INFO [04-22|13:35:39] Imported new block headers               count=4 elapsed=1.025s number=57179 hash=e90f30…8e1e3d ignored=0
```
no more syncing from this point on - only the mobile: avc: denied errors at ~1Hz - then restarting the node:

```
04-22 15:40:30.958  9906  9927 E GoLog   : WARN [04-22|13:40:30] Rolled back headers                      count=19 header=57179->57179 fast=0->0 block=0->0
04-22 15:40:30.958  9906  9927 E GoLog   : WARN [04-22|13:40:30] Synchronisation failed, dropping peer    peer=a24ac7c5484ef4ed err="retrieved hash chain is invalid"
04-22 15:40:31.663  9906  9927 E GoLog   : WARN [04-22|13:40:31] Rolled back headers                      count=19 header=57179->57179 fast=0->0 block=0->0
04-22 15:40:31.663  9906  9927 E GoLog   : WARN [04-22|13:40:31] Synchronisation failed, dropping peer    peer=a24ac7c5484ef4ed err="retrieved hash chain is invalid"
04-22 15:40:33.332  9996 10014 E GoLog   : INFO [04-22|13:40:33] Starting peer-to-peer node               instance=GethDroid/v1.6.0-stable/android-amd64/go1.8.1
04-22 15:40:33.332  9996 10014 E GoLog   : INFO [04-22|13:40:33] Allocated cache and file handles         database=/data/user/0/org.ligi.foo/files/.ethereum_rb/GethDroid/lightchaindata cache=16 handles=16
04-22 15:40:33.464  9996 10014 E GoLog   : INFO [04-22|13:40:33] Initialised chain configuration          config="{ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Engine: clique}"
04-22 15:40:33.465  9996 10014 E GoLog   : INFO [04-22|13:40:33] Loaded most recent local header          number=57179 hash=e90f30…8e1e3d td=112668
04-22 15:40:33.465  9996 10014 E GoLog   : INFO [04-22|13:40:33] Starting P2P networking 
04-22 15:40:33.529  9996 10019 E GoLog   : WARN [04-22|13:40:33] Light client mode is an experimental feature 
04-22 15:40:33.529  9996 10019 E GoLog   : INFO [04-22|13:40:33] Stats daemon started 
04-22 15:40:33.529  9996 10019 E GoLog   : INFO [04-22|13:40:33] RLPx listener up                         self="enode://8b2ff91f833e431b04b8497a73b309f172106cf1dc1d1439a5774d2a7c86b2b1eedb040d5449453eaea476468a3830cec22fe99bc50c0cea9d341daa905678f9@[::]:38904?discport=0"
04-22 15:40:35.674  9996 10019 E GoLog   : INFO [04-22|13:40:35] Mapped network port                      proto=tcp extport=38904 intport=38904 interface="UPNP IGDv2-IP1"
04-22 15:40:37.602  9996 10019 E GoLog   : INFO [04-22|13:40:37] Block synchronisation started 
04-22 15:40:39.188  9996 10019 E GoLog   : INFO [04-22|13:40:39] Imported new block headers               count=20 elapsed=1.062s number=57199 hash=43315a…b5e100 ignored=0
```

**Comment by brahbby** [comment]
Did you ever figure this out? I had a local binary working, but not its not working. Is it as simple as a permissions?

**Comment by drewstone** [comment]
Bump, having this same issue.

**Comment by maroney-tm** [comment]
Seems like we just need a more verbose name than "/". Not sure if I'm understanding these docs correctly.

https://source.android.com/security/selinux/device-policy

**Comment by 4h0q** [comment]
I'm encountering the same issue. @drewstone did you find any workaround?

**Comment by drewstone** [comment]
@4h0q use a physical device. I found no emulator-based workaround.

**Comment by khairmuhammad** [comment]
having same issue, anyone can help to resolve the issue.

**Comment by prashantspandey** [comment]
same issue please help

**Comment by MariusVanDerWijden** [comment]
Judging from the error message, it looks like someone (us) is trying to access the `/` directory on device `tmpfs`. It's probably some sub-system trying to cache something. @ligi do you have any idea what this could be?

**Comment by MariusVanDerWijden** [comment]
We have a timeout of 1 second in the following packages:
`scwallet`
`usbwallet`
`txpool` (rejournal)
`miner` (recommit interval)
`p2p` (multiple timeouts)
I would suspect, that one of the wallets are most likely

**Comment by karalabe** [comment]
Android and iOS support dropped via https://github.com/ethereum/go-ethereum/pull/26599.
