### ISSUE TITLE
when a single file is uploaded to swarm, the path entry is missing (Swarm Version 1.6.0-unstable)

### ISSUE THREAD

**Issue by arghyakusumdas** [ethereum/go-ethereum#14342]
#### System information

Swarm version: 1.6.0 unstable
Geth version: `geth version`
OS & Version: Linux
Commit hash : (if `develop`)

#### Steps to reproduce the behaviour
create a file called report6.txt and then upload it to swarm
$ swarm up report6.txt 
e9a91119cbee71eeef72104e9ac3f0958abc730d8f4f1d1564696f7d8a555ceb

Now in browser:
http://localhost:8500/bzzr:/e9a91119cbee71eeef72104e9ac3f0958abc730d8f4f1d1564696f7d8a555ceb?content_type=text/plain
{"entries":[{"hash":"d0b45f687f79df8685119ca7dfb24d12737a5d424f3b1f3ec05372f5a6306950","contentType":"text/plain; charset=utf-8","mode":436,"size":8,"mod_time":"2017-04-17T04:24:53-04:00"}]}
#### Backtrace

````
[backtrace]
````

**Comment by lmars** [comment]
This is expected behaviour. When you upload a single file, that file is then available at the root of the resulting hash:

```
$ echo "data" > file.txt

$ swarm up file.txt
e23b5dc2df754b15890235a4101976f5798a2e9b952a6310f1f66e8df73aba36

$ curl http://localhost:8500/bzz:/e23b5dc2df754b15890235a4101976f5798a2e9b952a6310f1f66e8df73aba36
data
```

If you want the file to be available at a specific path, you currently need to do a recursive upload of a directory containing that file:

```
$ tmpdir="$(mktemp --directory)"

$ echo "data" > "${tmpdir}/file.txt"

$ swarm --recursive up "${tmpdir}"
e85a0ced0f3e4cda0d59e4909a0d03e27516e62908668b4220cd3a27bce01b25

$ curl http://localhost:8500/bzz:/e85a0ced0f3e4cda0d59e4909a0d03e27516e62908668b4220cd3a27bce01b25/file.txt
data
```
