### ISSUE TITLE
eth_subscribe: notifications not supported

### ISSUE THREAD

**Issue by jiebanghan** [ethereum/go-ethereum#14341]
#### System information

Geth version: `geth version`
Geth
Version: 1.5.8-unstable
OS & Version: Windows/Linux/OSX
Linux ubuntu 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Commit hash : (if `develop`)
and run geth with the command below:
`./geth --identity "helloworld"   --ws  --wsaddr 192.168.241.128 --wsport 8545  --rpc  --rpcaddr 192.168.241.128 --rpcport 8545 --rpccorsdomain "*"   --datadir "$basepath/chain" --port "30303"  --rpcapi "db,eth,net,ssh,miner,web3,personal,admin" --networkid 88888 console`
and then 

```
curl 192.168.241.128:8545 -X POST --data '{"id": 1, "method": "eth_subscribe", "params": ["newHeads"]}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"notifications not supported"}}
```
when I　typed command changed the port to 8546:

```
curl 192.168.241.128:8546 -X POST --data '{"id": 1, "method": "eth_subscribe", "params": ["newHeads"]}'
bad method
```

I found from https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB : From version 1.4 geth has experimental support for pub/sub using subscriptions as defined in the JSON-RPC 2.0 specification. This allows clients to wait for events instead of polling for them.

So my geth version is higer than 1.4, So what's the problem?? Thank you.
#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Notifications require a connection oriented network protocol. Port 8545 by default is the HTTP RPC interface. HTTP does not support server push notifications, so subscriptions do not work on it.

Port 8546 by default is the WebSocket interface, which does support notifications, but you need to talk "WebSocket" with it, not plain HTTP that curl uses.

**Comment by jiebanghan** [comment]
thank you a lot.

**Comment by bas-vk** [comment]
As karalabe mentioned, either use websockets (or ipc).

**Comment by kdonthi** [comment]
I told myself I would include a code sample if I figured it out:
```
import json
from websocket import create_connection

ws = create_connection("ws://localhost:8546")
results = []
ws.send(json.dumps({"id":1, "method": "eth_subscribe", "params": ["newHeads"]}))
while True:
	res = ws.recv()
	if res not in results:
		print(res)
		results.append(res)
```

Unfortunately, the EC2 instance I ran it in had some errors with python3, so I think there is probably a much better way to write the persistent connection without the infinitely growing list haha!
