### ISSUE TITLE
A problem about input field of transaction 

### ISSUE THREAD

**Issue by ShawnyXiao** [ethereum/go-ethereum#14354]
When I want to call a method of contract, which would do a write operation, I would send a transaction, which would contain the arguments of method. These arguments would be encoded or hash (using SHA3?) to a HEX string. Then this HEX string will be signed by my private key using ECDSA. Finally a final string will be put in the input field of transaction object. 

Is my understanding correct? If right, as hash process could not be reversed, how could I get the real arguments from transaction?

**Comment by ShawnyXiao** [comment]
I found some input fields could be decoded, but some would be decoded as messy code.

![image](https://cloud.githubusercontent.com/assets/9656978/25219960/d0b843ba-25e2-11e7-810d-c83345bfc434.png)

After this input convert to Ascii, then...

![image](https://cloud.githubusercontent.com/assets/9656978/25219968/d744bc9a-25e2-11e7-98e7-703f1c4ec05f.png)

But this transaction will be decoded as messy code. I can't understand.

![image](https://cloud.githubusercontent.com/assets/9656978/25219862/67934fe2-25e2-11e7-830d-3f7e7154448d.png)

![image](https://cloud.githubusercontent.com/assets/9656978/25219905/97bb93aa-25e2-11e7-85d4-79e1f0b80491.png)

**Comment by bas-vk** [comment]
Transaction payloads are encoded using the ABI spec. Basically the first [4 bytes](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI#function-selector) indicate which function of the contract should be invoked. The remaining bytes are the [arguments](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI#argument-encoding).

To properly decode transaction data you need to have the contract ABI. Web3 has support the ABI spec, not sure if this is exposed in its API. If you want to use go you can take a look at the `github.com/ethereum/go-ethereum/accounts/abi` package.

Also note, users can put whatever they want in the payload. It doesn't have to a valid payload nor does the target has to be a contract.

**Comment by ShawnyXiao** [comment]
I get it. Thank you so much~
