### ISSUE TITLE
Optionally disable hardware wallet support 

### ISSUE THREAD

**Issue by chfast** [ethereum/go-ethereum#14355]
Support for hardware wallets is not always useful and also if it is enabled some weird usb errors are reported. Please add a command line flag to disable it.

**Comment by karalabe** [comment]
Could you please share the weird USB errors?

**Comment by chfast** [comment]
So I noticed two issues.

One is this log `I0407 00:49:44.942492 usb.go:93] handle_events: error: libusb: interrupted [code -10]`. See also: https://github.com/golemfactory/golem/issues/971.

The second issue is related to Ledger Nano S. In general if geth is running in the background Ledger is blocked and not usable by other applications (MyEtherWallet, Ledger Wallet). This happens also in Ledger is no in the mode compatible with geth (no Ethereum app running, or Ethereum application in "browser" mode).

I can do more testing if needed.
