### ISSUE TITLE
Cannot create any working custom genesis file since version 1.6

### ISSUE THREAD

**Issue by AlexandreRoba** [ethereum/go-ethereum#14351]
#### System information
Environment Docker
Geth
Version: 1.6.0-stable
Git Commit: facc47cb5cec97b22c815a0a6118816a98f39876
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.8

Environment Mac
Geth
Version: 1.6.0-stable
Git Commit: facc47cb5cec97b22c815a0a6118816a98f39876
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: darwin
GOPATH=/Users/aroba/golang
GOROOT=/usr/local/opt/go/libexec
#### Actual behaviour
I cannot have any custom genesis block working since version 1.6... This is crazy...

#### Steps to reproduce the behaviour
I create an account using
```bash
geth  --datadir ~/ethdev/ --dev --rpc --rpcaddr 0.0.0.0 account new
```
I copy and paste the newly created account to a custom genesis block in the alloc node here "9b9c31686b5340dba87ed7f97f4b09004a7cf4fa"
```json
{
  "config": {
    "chainId": 15,
    "homesteadBlock": 0,
    "eip155Block": 0,
    "eip158Block": 0
  },
  "gasLimit": "210000",
  "difficulty": "20000",
  "alloc": {
    "9b9c31686b5340dba87ed7f97f4b09004a7cf4fa": {
      "balance": "100000000000"
    }
  }
}
```
Then I init the genesis block using
```bash
geth --datadir ~/ethdev/ --dev init ./genesis.json 
```
I'm getting the following result
```bash
INFO [04-19|15:20:12] Allocated cache and file handles         database=/Users/aroba/ethdev/geth/chaindata cache=128 handles=1024
INFO [04-19|15:20:12] Writing custom genesis block 
INFO [04-19|15:20:12] Successfully wrote genesis state         hash=de1b87…0bd55e
```
then I start the node using
```bash
geth  --datadir ~/ethdev/ --dev console
```
and I'm getting the following
```bash
INFO [04-19|15:21:05] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/darwin-amd64/go1.8.1
INFO [04-19|15:21:05] Allocated cache and file handles         database=/Users/aroba/ethdev/geth/chaindata cache=128 handles=1024
Fatal: Error starting protocol stack: wrong genesis block in database (have de1b8711d15ce488, new e5be92145a301820)
```
I've followed this wiki page when creating the genesis block:
https://github.com/ethereum/go-ethereum/wiki/Private-network

Any help or tips appreciated :)
#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
`--dev` tries to inject its own custom genesis. You can't have both. You either run `--dev` or you run with your own genesis file.

**Comment by AlexandreRoba** [comment]
Indeed My mistake. Thanks for the super fast support :)
