### ISSUE TITLE
Directories specified in .toml config files cannot be specified relative to $HOME

### ISSUE THREAD

**Issue by ethernomad** [ethereum/go-ethereum#14360]
The toml functionality is great

On the command line you can do `--datadir ~/.link-geth`, but this doesn't work when specified in a toml file.

This sort of thing happens: `database=/home/jbrown/link-blockchain/~/.link-geth/geth/chaindata`

**Comment by karalabe** [comment]
Ah yes, this is kind of a known limitation for now. `~` and environment variable expansion are shell specific stuff, so they are expanded by your shell, not geth. The values in the config files are flat strings. We did have a short discussion whether this could be a useful feature to add.

I'll ping @fjl for his feedback.
