### ISSUE TITLE
JSON RPC sendTransaction returns transactionHash but tx not broadcasted

### ISSUE THREAD

**Issue by vogelito** [ethereum/go-ethereum#14361]
#### System information

Geth version:
```
Geth
Version: 1.6.0-stable
Git Commit: facc47cb5cec97b22c815a0a6118816a98f39876
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```
OS & Version: `Ubuntu 14.04.5 LTS`
Commit hash : NA

#### Expected behaviour
Transaction should be broadcasted if `sendTransaction` returns a transaction hash.

#### Actual behaviour
`sendTransaction` returns a transaction hash but transaction is not broadcasted or at least it doesn't end up in the eth blockchain in the future.

#### Steps to reproduce the behaviour
We have a hard time reproducing this behavior but open to try ideas to help debug. We have a single-threaded process that sends many transactions in a while loop. Through this method we send roughly 50 transactions daily but the issue seems to only happen once every 2 weeks.

This is the pseudo code:
```
for (txData in transactions) {
    if (!personal_unlockAccount(account, password, 10)) {
        // alert
        return;
    }
    transactionId = sendTransaction(txData);
    if (!transactionId) {
        // alert
        continue;
    }
    // Mark the tx as successful and record transactionId in DB
}
```

What we see is transactionIds in the database that are not in the blockchain. Here's such a transaction hash returned by geth connected on mainnet:
`0x6aa45ddf908211ebdba65489815ec423ca26648ee5af94d89075866d4da2289f`

We can confirm that geth didn't restart during that time, although suspect that the problem might arise when the sending account is low on funds.

**Comment by holiman** [comment]
Two questions

1. The account `account` - is that also used by any other caller making transactions, in any separate processes, by any chance? 
2. Just to confirm; when the error occurs, the `alert` does not trigger at all ?

So, hypothesing a bit here.. 

This is a fully sequential process, so can't be explained by race conditions. Off the top of my head, I could imagine the following scenario: 

* Transactions 1.. 20 get added in `sendTransaction`.  Added to `pending`. 
* A new block arrives.  
* Transactions 20.. 40 get added in `sendTransaction`.  Added to `pending`. 
* A new block arrives, with higher `gasPrice` than the earlier transactions. Transactions `20..40` get dropped, due to too-low `gasPrice`.
* Transactions 40..60 get added (with better gasPrices). 

If it does _not_ have anything to do with incoming blocks, it should be easy to replicate with an instance on a private net without any peers, by submitting transactions in a loop and then counting `pending`. I'll test it.

**Comment by holiman** [comment]
I ran the following script on a geth-instance: 

```javascript
ids = [];
function getTx(){
	return { from : eth.accounts[0], 
		to:"0x0000000000000000000000000000000000001337", value:1000};
}
function doTest()
{
	for(var i =0; i < 10000; i++){
		personal.unlockAccount(eth.accounts[0],"test",10);
		ids.push(eth.sendTransaction(getTx()))
		if( i % 10 == 0){
			console.log("Pending: "+eth.pendingTransactions.length)
			console.log("Sent: "+ids.length)
		}
	}	
}
```
Still going after 3500+ transactions added.

**Comment by vogelito** [comment]
Thanks for your reply.

1. I confirm that the account `account` is not used anywhere else.
2. Correct, the `alert` doesn't trigger at all.

Your hypothesis got me thinking and realize there's a part of the code that might be at fault here, so I'll extend my pseudo code a bit:

```
balance = eth_getBalance(account, "latest");
total = 0;
for (txData in transactions) {
    if (total + txData.value > balance) {
        // alert that account balance is low
        continue;
    }

    total += txData.value;

    tx = { from: account,
            destination: txData.toAccount,
            value: txData.value,
            gas: dex2hex(21000),
            gasPrice: eth_gasPrice(),
            value: txData.value
        }
    
    if (!personal_unlockAccount(account, password, 10)) {
        // alert unable to unlock account
        return;
    }
    transactionId = sendTransaction(tx);
    if (!transactionId) {
        // alert that some error in sendTransaction happened
        continue;
    }
    // Mark the tx as successful and record transactionId in DB
}
```

I revised the time of the last 3 times we've seen this and can confirm that at all those times, the balance in the account was low and could in fact find *some* tx's not being relayed due to the "low balance" alert.

**Comment by holiman** [comment]
I can see another potential error here. 

* You're using `total` as a javascript number. This has quite bad precision. 

```javascript
>  x = eth.getBalance("0x2a50613a76a4c2c58d052d5ebf3b03ed3227eae9")
1e+24
> a = x - 1000
1e+24
> x.sub(1000)
9.99999999999999999999e+23
> typeof(a)
"number"
> typeof(x)
"object"
```

So if you're keeping a record of the `balance` on the side, you should make sure to use bignums, not number. 

> I revised the time of the last 3 times we've seen this and can confirm that at all those times, the balance in the account was low and could in fact find some tx's not being relayed due to the "low balance" alert.

I'm not sure I follow.. So you're saying that the missing tx:s can be explained as not submitted at all?

**Comment by vogelito** [comment]
> You're using total as a javascript number

Oh, no, sorry, what I posted is pseudocode. We do use bignums on our side and you can assume that all mathematical operations are done on immutable, arbitrary-precision signed decimal numbers.

Regarding the lack of clarity in my last reply, what I meant is that I have *some* evidence that would suggest that this problem happens when the balance of `account` is low. E.g. that it might be the case that if the balance is low, `sendTransaction` returns a tx hash but that tx is never relayed.

**Comment by vogelito** [comment]
So let's say this:
Account balance is 10
A tx cost 0.001
I'm trying to send 10 transactions, each of value 1

I don't think my code takes into consideration the cost of sending a transaction. Could it be the case that:
1. `sendTransaction` is called for 9 tx's
2. Those 9 transactions are relayed and get into a block, but my geth doesn't know about it
2. `sendTransaction` is called one last time for the last tx, returning a hash
3. Before it relays the last tx, it realizes it's invalid and it doesn't even broadcast it

Or something like that? Sorry, i don't know the insides of geth so I'm completely speculating

**Comment by holiman** [comment]
Hm.. 

Sending with too low balance should, if the node detects it, result in no hash:

```
> eth.sendTransaction(getTx2(), eth.accounts[0])
Error: Insufficient funds for gas * price + value
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:1
```

However: 

```
> web3.fromWei(eth.getBalance(eth.accounts[0]),"ether")
1000000
> web3.fromWei(getTx3().value,"ether")
"800000"
> eth.sendTransaction(getTx3())
"0xe6dea67ad5c6e6cf101b66b9cf95867a38e468eb3e8e537cf06373092534e25e"
> eth.sendTransaction(getTx3())
"0x7143fef614420a8336b541e18061da71c76626d87f522d2fd0652d2e03e8db3a"
> eth.sendTransaction(getTx3())
"0x958a603a12837fd12c9dd84d67d3fca918fed7de4227a2f30ffe77952344d2ff"
> eth.sendTransaction(getTx3())
"0x6d19aaa3326e4c8aa2ea9f48448ab28e88c69b20aee52c4bfde30eb5d7528ed5"
> eth.sendTransaction(getTx3())
"0x11eb5bdd7802dd34bf8f88ebfc936095b8b09d1beeb681af70888118391da241"
> eth.sendTransaction(getTx3())
"0x7ade365c9bc9b148b7690ef5c08818aa02468766f27c82f72ef2c1db831aa3d0"
> eth.sendTransaction(getTx3())
"0xa87f1104f7b58c894ffba3f3e6fbeda6034b54534f4bb906a3b0adaf924569cd"
> eth.sendTransaction(getTx3())
"0x6ff02e1e438e046fdf64fd3f0105dfe831c91bc5fbd547e06b7c3eb1e3493452"
> eth.sendTransaction(getTx3())
"0x20d31533b3b4ca7168e6003959a899924d08cd424e10938525eb566ba03b6e3b"
> eth.sendTransaction(getTx3())
"0x7a6ebc5c5f6976b2034ce093f7b35809b8335ec3c921b744f6b8cbb25b4b7347"
> eth.sendTransaction(getTx3())
"0x808bb7cbb74dc21e3cba4c3fa4d495c5d4a68ffd326d3d8980b2cb8aba80b23e"
> eth.sendTransaction(getTx3())
"0xe67f663996224874fc1c6f527fe46d7a9fa18f7ad802772e369fc9d6533e7502"
> eth.sendTransaction(getTx3())
"0xf6b74ef2922e9c1ac4c727b0ac38c1be03412b7e51049cbc1a48019d67cf8c97"
```

Above, I have the balance `1000`, and send as many `800`-ether transactions as I want. These wind up in `pending`, and are broadcast on the network. As soon as the first of these is included into a block, however (and the local node becomes aware of it), the remaining ones will be flagged as out-of-funds, and dropped. 

So what I think is happening is: 

* The transactions are accepted, even though the sum total of them would exceed the balance
* Most transactions are included, but some dropped due to out-of-funds, once a few of them (the bulk?) become accepted. 
* And yes, if you only count `value` and not total cost (including gas), then that might be why your local count differs from the actual `balance`.
You could do something like this: 
```
var tx = eth.getTransaction("0xf6b74ef2922e9c1ac4c727b0ac38c1be03412b7e51049cbc1a48019d67cf8c97")
> var totalValue = tx.value.add(tx.gasPrice*tx.gas)
8.000000019620018e+23
```

**Comment by vogelito** [comment]
Thanks, that must be it. We just added something to take into account transaction costs to our code, which should go into production in the next few days.

I will let you know if we see the problem again.

**Comment by holiman** [comment]
Great, I'll close this for now, please reopen if you find evidence of anything else going on.

**Comment by CockyCat** [comment]
Do you resolved it?

**Comment by seangell** [comment]
Im using Windows 10 64bit, running GETH --fast but give me synchronization failed, dropping peer. If I inquire my ETH balance, it display available ETH but I cant able to transfer the ETH to my other ETH wallet.

**Comment by CryptoAlphaOne** [comment]
how can I sign an etherium transaction using JSON-RPC to call eth_sendRawTransaction Without using web3
