### ISSUE TITLE
Wiki: --unlock command-line flag is comma-separated, not whitespace-separated

### ISSUE THREAD

**Issue by matt-williams** [ethereum/go-ethereum#14370]
#### System information

The --unlock command-line flag is documented as being whitespace-separated.  It is, in fact, comma-separated, and using it whitespace-separated gives an error.

#### Expected behaviour

https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts should say:

> You can do this on the command line with the `--unlock` option which takes a comma separated list of accounts (in hex or index) as argument so you can unlock the accounts programmatically for one session. This is useful if you want to use your account from Dapps via RPC.

> The command line allows you to unlock multiple accounts. In this case the argument to unlock is a comma delimited list of accounts addresses or indexes.

> geth --unlock "0x407d73d8a49eeb85d32cf465507dd71d507100c1,0,5,e470b1a7d2c9c5c6f03bbaa8fa20db6d404a0c32"

#### Actual behaviour

https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts actually says:

> You can do this on the command line with the `--unlock` option which takes a whitespace separated list of accounts (in hex or index) as argument so you can unlock the accounts programmatically for one session. This is useful if you want to use your account from Dapps via RPC.

> The command line allows you to unlock multiple accounts. In this case the argument to unlock is a whitespace delimited list of accounts addresses or indexes.

> geth --unlock "0x407d73d8a49eeb85d32cf465507dd71d507100c1 0 5 e470b1a7d2c9c5c6f03bbaa8fa20db6d404a0c32"

#### Steps to reproduce the behaviour

Read the docs!

Note that I would have submitted a pull request for this, but unfortunately github doesn't support pull requests on wikis - hopefully the above should give an easy fix, though!

**Comment by bas-vk** [comment]
I have updated the docs, thx!

**Comment by mirw** [comment]
Thanks for the fast turn-around!
