### ISSUE TITLE
geth log reports unsigned instead of signed transaction hash

### ISSUE THREAD

**Issue by tinybike** [ethereum/go-ethereum#1438]
The returned value is correct (the signed hash), but the value reported in the log is incorrect.  Here is an example (hat tip: @obscuren) -- note that the txhash entered (that is used successfully with `getTransaction`) does not match the hash reported in the log immediately above it, at the top of the screen:

![bw56tq4zti8cojixit69ho0yc67esl22i_ndaeqa8c4](https://cloud.githubusercontent.com/assets/2637020/8567440/31f1f192-251a-11e5-9d83-afc919b4054f.png)

**Comment by debris** [comment]
I also reproduced the same issue

**Comment by Gustav-Simonsson** [comment]
https://github.com/ethereum/go-ethereum/pull/1468
