### ISSUE TITLE
Clique RPC API reference

### ISSUE THREAD

**Issue by eugene-babichenko** [ethereum/go-ethereum#14383]
I'd like to see a good RPC API reference for the Clique part on the [wiki page](https://github.com/ethereum/wiki/wiki/JSON-RPC)

**Comment by nepalbitcoin** [comment]
Only RPC API? 
We need a better wiki for Clique & puppeth..

**Comment by karalabe** [comment]
I agree with both, will try to put some effort into it!

**Comment by sarbao** [comment]
Good morning all,

    Peter, it is Salvador the guy who asked you about private blockchains. Back again :-) Finally I was able to create my private blockchain,get nodes connected, pre-fund accounts, etc... Have just discovered puppeth which seems to make easier private blockchain creation. Meanwhile you prepare the wiki, is there any page with instructions of doing that on puppeth. I tried following puppeth command guideline but couldn't reach that. Tks vm in advanced again. Best regards, Salvbador

**Comment by karalabe** [comment]
There's no docs currently on puppeth, so I'm afraid the CLI wizard is your
only resource. But if you have some question I'll try to answer them :)

**Comment by sarbao** [comment]
Will do Peter. Tks very much for your kind offer... Give me a call if you travel to Spain someday and I will say thanks with a big beer :-) jejej ( seriously !! )


Keep in touch 


Best regards,

Salvador
