### ISSUE TITLE
Swarm: Need support for multiple geth endpoints (for ENS, SWAP, SWEAR...)

### ISSUE THREAD

**Issue by homotopycolimit** [ethereum/go-ethereum#14386]
Currently swarm is in testing -- we are using ropsten for all blockchain interactions. Interaction with the blockchain happens via the `--ethapi /path/to/geth.ipc` flag.

Once ENS is deployed, we will want to be able to register swarm assets in the ENS on mainnet and we will also want to continue testing components such as SWAP or SWEAR on the testnet. As a result we will need support for multiple geth.ipc endpoints.

Suggestion:
Allow the `--ethapi` flag to be superseded by `--ens-api`, `--swap-api` and `--swear-swindle-api`.

**Comment by homotopycolimit** [comment]
We should also be able to split ENS into multiple endpoints depending on the tld.

so perhaps we should have `--ens-api` or `--ens-eth-api` for .eth domains (presumably mainnet) and also `--ens-test-api` for .test domains from the testnet.

**Comment by zelig** [comment]
I recommend an ens-api flag syntax and interface design.

     -ens-endpoints <default>;test:<test-endpoints>(,<other-test-endpoint>),swarm:<swarm-ens-endpoint>

Endpoints are enode-style urls: 

     <contract-address>:<blockchain-eth-api-url>

ens-endpoints is a semicolon-separated list of 

      (<tld>:)<endpoint>(,<endpoint>)+

When domains are resolved, the registered endpoints are used, top level domains can define their own sequence of ENS registry addresses. The contract address is before the @ sign in the url.
If no tld is given the endpoint is used unless the tld specifies its own endpoint.

**Comment by lmars** [comment]
So I actually recommend using the config file as the primary way to configure these endpoints.

**Comment by homotopycolimit** [comment]
closing this issue.|
we have solved this for ens api and we intend to proceed along these lines for swap when it becomes available.
