### ISSUE TITLE
how to use go-ethereum as ETC wallet

### ISSUE THREAD

**Issue by Yucheng123** [ethereum/go-ethereum#14401]
#### System information
Geth version: 1.6.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)
#### Expected behaviour
with --support-dao-fork flag , Geth can use as ETC wallet 

#### Actual behaviour
--support-dao-for flag was removed

#### Steps to reproduce the behaviour

./geth --oppose-dao-fork --testnet --fast --cache=512 console --rpc --rpcport 8546 --datadir /home/yucheng/etcpool_data/

#### Backtrace

````
./geth --oppose-dao-fork --testnet --fast --cache=512 console --rpc --rpcport 8546 --datadir /home/yucheng/etcpool_data/
````

**Comment by karalabe** [comment]
The two protocols diverged, hence `go-ethereum` does not any more support ETC.

**Comment by Yucheng123** [comment]
Thank you , Has ETC a similar walllet that supports RPC?

**Comment by karalabe** [comment]
Etc was forked off from Geth 1.4 so everything until then should work. I'm
also certain they added their own patches too. Afaik Mist was also forked
and possibly Parity can also do etc. Perhaps check the etc reddit page or
their slack. I'm sure they'll help out.

**Comment by Yucheng123** [comment]
Thank you for your kindness
