### ISSUE TITLE
No accounts created with genesis.json

### ISSUE THREAD

**Issue by RubenBenBen** [ethereum/go-ethereum#14404]
System information

Geth version: 1.6.0
OS & Version: OSX 10.11.6
Commit hash : (if develop)

Expected behaviour

create network with two accounts

Actual behaviour

no accounts are created, just an empty network

Steps to reproduce the behaviour

geth init genesis.json

**Comment by holiman** [comment]
Could you paste the genesis.json here?

**Comment by RubenBenBen** [comment]
its the default file, nothing changed.
{
    "config": {
        "chainId": 15,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "difficulty": "200000000",
    "gasLimit": "2100000",
    "alloc": {
        "7df9a875a174b3bc565e6424a0050ebc1b2d1d82": { "balance": "300000" },
        "f41c74c9ae680c1aa78f42e5647a62f353b7bdde": { "balance": "400000" }
    }
}

**Comment by holiman** [comment]
Works for me.. 
```
INFO [05-02|15:37:51] IPC endpoint opened: /home/martin/tmp/gotest/A/geth.ipc 
INFO [05-02|15:37:51] Mapped network port                      proto=tcp extport=30303 intport=30303 interface="UPNP IGDv2-IP1"
Welcome to the Geth JavaScript console!

instance: Geth/v1.6.1-unstable-a6af56fa/linux-amd64/go1.7.5
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> eth.getBalance("0x7df9a875a174b3bc565e6424a0050ebc1b2d1d82")
300000
> eth.getBalance("0xf41c74c9ae680c1aa78f42e5647a62f353b7bdde")
400000

```

**Comment by holiman** [comment]
This is the script I was using: 
```
GETH=/home/martin/workspace/go-ethereum/build/bin/geth
rm -rf ./A

echo '{
    "config": {
        "chainId": 15,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "difficulty": "200000000",
    "gasLimit": "2100000",
    "alloc": {
        "7df9a875a174b3bc565e6424a0050ebc1b2d1d82": { "balance": "300000" },
        "f41c74c9ae680c1aa78f42e5647a62f353b7bdde": { "balance": "400000" }
    }
}' > genesis.json


$GETH --datadir ./A init genesis.json
$GETH --datadir ./A  --networkid 314 &
sleep 10

$GETH attach ./A/geth.ipc
killall geth
```

**Comment by RubenBenBen** [comment]
ok not sure what I'm doing wrong, here are my steps:
1. geth init genesis.json
I get the following:
WARN [05-02|18:18:07] No etherbase set and no accounts found as default 
INFO [05-02|18:18:07] Allocated cache and file handles         database=/Users/Apple/Library/Ethereum/geth/chaindata cache=128 handles=1024
INFO [05-02|18:18:07] Successfully wrote genesis state         hash=614a31…9df7ba

2.geth --networkid 314 & sleep 10
I get
[4] 5384

[4]+  Stopped                 geth --networkid 314

3.geth console
I get :
WARN [05-02|18:20:16] No etherbase set and no accounts found as default 
INFO [05-02|18:20:16] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/darwin-amd64/go1.8.1
INFO [05-02|18:20:16] Allocated cache and file handles         database=/Users/Apple/Library/Ethereum/geth/chaindata cache=128 handles=1024
INFO [05-02|18:20:16] Initialised chain configuration          config="{ChainID: 15 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Engine: unknown}"
INFO [05-02|18:20:16] Disk storage enabled for ethash caches   dir=/Users/Apple/Library/Ethereum/geth/ethash count=3
INFO [05-02|18:20:16] Disk storage enabled for ethash DAGs     dir=/Users/Apple/.ethash                      count=2
INFO [05-02|18:20:16] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [05-02|18:20:16] Loaded most recent local header          number=0 hash=614a31…9df7ba td=200000000
INFO [05-02|18:20:16] Loaded most recent local full block      number=0 hash=614a31…9df7ba td=200000000
INFO [05-02|18:20:16] Loaded most recent local fast block      number=0 hash=614a31…9df7ba td=200000000
INFO [05-02|18:20:16] Starting P2P networking 
INFO [05-02|18:20:18] RLPx listener up                         self=enode://470445cea150ad24f8558ae3293b43656df4bbbacd16e89355ddd85ce4c6229c93a0d0972eb3a1a8d550a6c68ce873da5b885ddbc31a97b811a4807b0eae0329@[::]:30303
INFO [05-02|18:20:18] IPC endpoint opened: /Users/Apple/Library/Ethereum/geth.ipc 
Welcome to the Geth JavaScript console!

instance: Geth/v1.6.0-stable-facc47cb/darwin-amd64/go1.8.1
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

4. personal
gives me empty list:
{
  listAccounts: null,
  listWallets: null,
  deriveAccount: function(),
  ecRecover: function(),
  getListAccounts: function(callback),
  getListWallets: function(callback),
  importRawKey: function(),
  lockAccount: function(),
  newAccount: function github.com/ethereum/go-ethereum/console.(*bridge).NewAccount-fm(),
  sendTransaction: function(),
  sign: function github.com/ethereum/go-ethereum/console.(*bridge).Sign-fm(),
  unlockAccount: function github.com/ethereum/go-ethereum/console.(*bridge).UnlockAccount-fm()
}

**Comment by RubenBenBen** [comment]
eth.getBalance("0xf41c74c9ae680c1aa78f42e5647a62f353b7bdde")
gives the right values though,
300000
but I can't see the accounts neither here nor in Ethereum Wallet client

**Comment by karalabe** [comment]
The genesis file only specifies that some addresses should be pre-funded. It does not create accounts (which are in reality local private keys that are authorized to spec funds from certain addresses). You can create real account (i.e. local private keys) for yourself via the `personal.newAccount()` console method. You can also do `geth --datadir=/wherever account new` to create a new account for yourself.

**Comment by RubenBenBen** [comment]
ok, so how then I add ether to the account to create smart contract? cause mining doesn't work for me for some reason

**Comment by holiman** [comment]
So first of all, you need access to a keyfile. You place that into `<datadir>/keystore/UTC--xxx.json`. Alternatively, what Peter suggested : `geth --datadir=/wherever account new`, and it will be placed there automatically. 

And then you need to add it to the `alloc`- section, like you have done already with two accounts. So you've successfully prefunded two accounts already, but you've missed the step of making geth aware of how to actually sign/send transactions from the accounts.

**Comment by RubenBenBen** [comment]
Yeah, works like a charm. Thanks guys

**Comment by keejh** [comment]
I don't understand it. Please assist.

1) I execute geth --testnet init CustomGenesis.json
This will create testnet folder and etc.
2) I execute geth --testnet account new
Now I have the account address and update to .json
3) I execute geth --testnet init CustomGenesis.json
Error :(
Fatal: Failed to write genesis block: database already contains an incompatible
genesis block (have 38b1ce7cdce28448, new 8f81f8862f91963b)

Sample json before I add the address.
{
"nonce": "0x0000000000000042",
"timestamp": "0x0",
"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"extraData": "",
"gasLimit": "0x8000000",
"difficulty": "0x400",
"mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"coinbase": "0x0000000000000000000000000000000000000000",
"alloc": {},
"config": {
"chainId": 15,
"homesteadBlock": 0,
"eip155Block": 0,
"eip158Block": 0
}
}

Sample json after I update the address.
{
"nonce": "0x0000000000000042",
"timestamp": "0x0",
"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"extraData": "",
"gasLimit": "0x8000000",
"difficulty": "0x400",
"mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"coinbase": "0x0000000000000000000000000000000000000000",
"alloc": { "211593f6ee72871525221840f3ae607879dbfb25" : { "balance": "1337000000000000000000" } },
"config": {
"chainId": 15,
"homesteadBlock": 0,
"eip155Block": 0,
"eip158Block": 0
}
}

**Comment by gogit** [comment]
@keejh do step 2 before step 1, first create the accounts and then update the genesis file with the account details

**Comment by sshasan** [comment]
@gogit I have done what you said, now I am able to see the added address in mist browser but, still I have 0 ether in the account, although I have updated the genesis.json file with some ether in the alloc section.
