### ISSUE TITLE
geth attach not working

### ISSUE THREAD

**Issue by DSofter** [ethereum/go-ethereum#14410]
#### System information

Geth version: 1.5.9-stable
OS & Version: OSX
Commit hash : a07539fb88db7231d18db918ed7a6a4e32f97450

#### Actual behaviour
```
MacBook-Gro:~ jobs$ geth attach
Fatal: Unable to attach to remote geth: dial unix /Users/jobs/Library/Ethereum/geth.ipc: connect: no such file or directory
```

#### Steps to reproduce the behaviour
Open one console, run `geth --testnet`.
Open another console, run `geth attach`

Sorry if this is a dumb question. But basically I wasn't able to get`geth attach` working.

Also README.md says `you can always attach to an already running Geth instance with geth --attach` which I believe is not true. Thanks!

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
`geth attach /Users/jobs/Library/Ethereum/testnet/geth.ipc`? :)

**Comment by DSofter** [comment]
@karalabe Works like a charm! If anyone could update the README that would be awesome!

**Comment by karalabe** [comment]
Fair point. I'll add it to our next release. It's too late for 1.6.1 now (we're just prepping it).
