### ISSUE TITLE
Blockchain download time

### ISSUE THREAD

**Issue by Gagabits** [ethereum/go-ethereum#1442]
Stephen Tual advises that the download should take from 3-9 hours to complete. Have been running since 1:15 GMT and currently (14:00 GMT) at 619K and crawling. Running on amazon ec2 medium. Load average is steady over 3. Server is 'Caloosahatchee' on the stats page. Have not yet been able to download a complete blockchain.

**Comment by karalabe** [comment]
Downloading the chain is not the issue, is problem is processing it. 3-9 hours is a very optimistic estimate. (i.e. throw a i7+ 4/8 cores at it, and maybe it will achieve that performance). On a moderately powerful computer it will take way more time. As far as I know, a t2.medium is not enough with the test net spam. Maybe if you get through all the junk to the head it will stay in sync, but it will take quite some time to get there. (e.g. on an older core 2 CPU (as far as I know more powerful than t2.medium) it took at least 1-2 days to sync up).

So, this isn't really an issue with geth, but rather the amount of junk we accumulated in the test network. Running full nodes will always be quite computational heavy, but hopefully after Frontier we can release eth/63 and enable light clients to join the network and not require so many resources. Until then however, please have patience :), and maybe throw a buigger instance at it while it finishes up syncing and then reduce it to see how much is just enough to keep in sync :)

**Comment by obscuren** [comment]
Or ask someone you trust to make you a copy of the chain

**Comment by Gagabits** [comment]
A copy would be appreciated. :)

**Comment by Gagabits** [comment]
OK, so I'm now running on an M4 Large. Still creeping along.

**Comment by tgerring** [comment]
Ensure the volume that the datadir resides on has sufficient I/O. Very low default iops can result in disk bottlenecks

**Comment by Gagabits** [comment]
Feel like I'm chasing a dream. Has anyone actually recently (last few days) downloaded the current blockchain start to finish or are we just guessing and suggesting more horsepower and faster disk?

Hope production looks better than this.

**Comment by karalabe** [comment]
I did a full sync about 3 days ago on a Core2 laptop. Took me 2 days (on an
off) + a whole night.

**Comment by tgerring** [comment]
I sync'd the 3 Go Bootnodes listed on stats.ethdev.com and my 13" Macbook Pro all within the last week, all from scratch
