### ISSUE TITLE
Broken link in the description of release

### ISSUE THREAD

**Issue by fzzr-** [ethereum/go-ethereum#14426]
[Release page (v1.6.1)](https://github.com/ethereum/go-ethereum/releases/tag/v1.6.1)

_I think it's missed slash._

- - -

Existing text: 

```markdown
Binaries and mobile libraries are available on our [download page](/geth.ethereum.org/downloads).
```

Binaries and mobile libraries are available on our [download page](https://github.com/ethereum/go-ethereum/blob/v1.6.1/geth.ethereum.org/downloads).

Expected text:

```markdown
Binaries and mobile libraries are available on our [download page](//geth.ethereum.org/downloads)
```

Existing text: Binaries and mobile libraries are available on our [download page](//geth.ethereum.org/downloads).

**Comment by karalabe** [comment]
Thanks for this. Fixed.
