### ISSUE TITLE
How to add peer via solidity contract?

### ISSUE THREAD

**Issue by jiebanghan** [ethereum/go-ethereum#14439]
#### System information

we are clear that in geth console we can add another peer with addpeer command such as

admin.addPeer("enode://41bd7d2fe91b344f0ca4ac89c217d688ef90a3616927acec428adddbc69dd2ac5470a489fd2beb67719cbd481436b98284ef9eac50efa49f55fe33e804818520@10.0.50.91:30303") 
so, my question is that how to add another peer in solidity contract?

**Comment by karalabe** [comment]
You cannot. Contracts run in the VM, a fully sandboxed environment from the world. It might be possible if you modified Geth so it watches a contract and modifies its behavior based on events emitted from the contract, but why would that be a good idea?

**Comment by jiebanghan** [comment]
thank you very much ,I just want to control those peer with smart contract, and in contract I can define the topological relationship of peers. It is my aim here.

**Comment by karalabe** [comment]
There is no way to do it. Also do note, that it would be a dangerous thing: e.g you tell your contract to only connect to peer x, peer x is offline, your node disconnects from the network. No more blocks, no more updates to your contract and you can't tell it to connect to someone else any more.

**Comment by jiebanghan** [comment]
thank you very much for your reply.

**Comment by karalabe** [comment]
Cheers :+1:
