### ISSUE TITLE
Fatal: Error starting protocol stack: Access is denied.

### ISSUE THREAD

**Issue by swathi08** [ethereum/go-ethereum#14438]
#### System information

Geth version: `geth version`: Geth 1.6.0
OS & Version: Windows/Linux/OSX : Windows
Commit hash : (if `develop`)

I am trying to set up private network with multiple nodes.  Node 1 is starting with the below command
geth --identity "TestNode1" --datadir "testnode1" --nodiscover --networkid 1900 –ipcpath “testnode1/geth.ipc” init "genesis.json" console 2 > console1.log

However, when I try to start node 2 with the below, it gives "Fatal: Error starting protocol stack: Access is denied." I tried with --ipcdisable flag as well and the same error persists. Could anyone pls. suggest

geth --identity "TestNode2" --datadir "testnode2" --nodiscover --port "30304" --networkid 1900 --ipcpath “testnode2/geth.ipc” init "genesis.json" console 2 > console2.log

**Comment by swathi08** [comment]
This is resolved

**Comment by iffyok** [comment]
can you please write the solution i am also facing same issue

**Comment by chengling** [comment]
the command add  --ipcdisable  
see the linking https://github.com/ethereum/go-ethereum/issues/1714

**Comment by Dietz76** [comment]
Thank you! 
I changed the port for multiple nodes and I changed the datadir but no one told me about the --ipcdisable.
Worked like a charm, thanks again!

**Comment by vivek-bombatkar** [comment]
Below worked for me,
C:\WINDOWS\system32>geth --networkid 13 --port 60303 --rpc --lightkdf --cache 16 --datadir "C:\ETH\data-private"  --ipcdisable console

**Comment by ericralhan** [comment]
This issue only occurs in windows. On ubuntu, there was no such problem.
Link from @chengling's comments confirms that.

**Comment by stvenyin** [comment]
Thanks a lot

**Comment by ericramos1980** [comment]
Your welcome

**Comment by Anubhavv32** [comment]
> Below worked for me,
> C:\WINDOWS\system32>geth --networkid 13 --port 60303 --rpc --lightkdf --cache 16 --datadir "C:\ETH\data-private" --ipcdisable console

Thanks!

**Comment by ericramos1980** [comment]
C:\WINDOWS\system32>geth --networkid 13 --port 60303 --rpc --lightkdf --cache 16 --datadir "C:\ETH\data-private" --ipcdisable console

**Comment by ReekoD** [comment]
> Below worked for me,
> C:\WINDOWS\system32>geth --networkid 13 --port 60303 --rpc --lightkdf --cache 16 --datadir "C:\ETH\data-private" --ipcdisable console

Thank you ; 
how to tell ethereum wallet to execute this command line when launched via Windows desktop icon "EthereumWallet.lnk" ? 
i mean i don't find any config file to set ethereum wallet launch configuration
