### ISSUE TITLE
Geth: any path passed as argument should be absolute

### ISSUE THREAD

**Issue by fzzr-** [ethereum/go-ethereum#14430]
#### System information

Geth version: 1.6.1-stable
Commit hash : 021c3c281629baf2eae967dc2f0a7532ddfdc1fb
OS & Version: macOS 10.12.4 (16E195)
Go Version: go1.8.1

#### Expected behaviour

Any path should be converted to absolute and should be canonised (resolved if it's symlink).

`~/geth.ipc` - must work.

#### Actual behaviour

`~/geth.ipc` - __not works__

`./geth.ipc` - _works_
`$HOME/geth.ipc` - _works_
`${HOME}/geth.ipc` - _works_

#### Steps to reproduce the behaviour

1. start akasha.app (for example)
1. console `geth attach ipc:~/Library/Ethereum/akasha-alpha/geth.ipc`
1. error: `Fatal: Unable to attach to remote geth: dial unix ~/Library/Ethereum/akasha-alpha/geth.ipc: connect: no such file or directory`

#### Backtrace

_no backtrace_

**Comment by fjl** [comment]
You can leave off the 'ipc:' prefix. `geth attach ~/geth.ipc` works.
