### ISSUE TITLE
get, post requests for getBalance, sendTransaction in private network

### ISSUE THREAD

**Issue by RubenBenBen** [ethereum/go-ethereum#14434]
I've created my private network with two accounts, now want to do some experiments with transactions. I know that there is a way to send eth from one account to another using javascript console, like eth.sendTransaction({from: '0x036a03fc47084741f83938296a1c8ef67f6e34fa', to: '0xa8ade7feab1ece71446bed25fa0cf6745c19c3d5', value: web3.toWei(1, "ether")}). Is there a way to do this via post request? And get account balance with get request? So i can call it from console, or browser?

**Comment by karalabe** [comment]
No, we do not have a RESTful API. If you want to interact from a browser, youáre probably looking for web3.js https://github.com/ethereum/web3.js/
