### ISSUE TITLE
executing commands from an xCode application (ObjC)

### ISSUE THREAD

**Issue by RubenBenBen** [ethereum/go-ethereum#14458]
System information

Geth version: 1.6.0
OS & Version: OSX 10.11.6

I have my private network in EVM, and have an issue connecting it with my application. Is there a way to execute a command (like sending transaction) from let's say iOS/MacOS application in xCode (objC/swift)?

**Comment by karalabe** [comment]
https://github.com/ethereum/go-ethereum/wiki/Mobile:-Introduction
https://github.com/ethereum/go-ethereum/wiki/Mobile:-Account-management

The mobile library can also connect to remote nodes and even start inproc nodes, but I haven't documented those parts yet.

**Comment by RubenBenBen** [comment]
Wow, thanks. Is it for swift only or it can be done via Objective C too?

**Comment by karalabe** [comment]
The underlying library is ObjC, so it should definitely work, alas I'm not familiar with objc, so I can't write the demo snippet codes for it. If you feel like it, I'd gladly add ObjC demo code to the guides too if you can provide it :)

**Comment by RubenBenBen** [comment]
Ok, pbb will do it in the next 3-5 days. Can provide it if you want :D.
Thanks a lot. I guess we can close this issue.

**Comment by karalabe** [comment]
:+1:
