### ISSUE TITLE
Clique can not cancel the signer

### ISSUE THREAD

**Issue by alphaqiu** [ethereum/go-ethereum#14451]
#### System information

Geth version: 1.6.1
OS & Version: Linux

I was set two node for testing poa private network, and I added one signer in per node.
when one node(A) shutdown, another node(B) will not mining. The log said: "Signed recently, must wait for others". But when I started the one just shutdown few minuts ago, nothing to happened, 
The node(B) still waiting. 

I`m trying to invoke web3 api clique.propose(address, false), but nothing to happened.

Please help, how to cancel a signer. thank you.

**Comment by karalabe** [comment]
Any change needs to be proposed by 50%+1 nodes in the network for it to come into effect. For 2 signers, 50%+1 is actually two. You need to have your second signer vote itself out too.

**Comment by alphaqiu** [comment]
@karalabe Oh Thank you for your help. I think I make some mistake on it.

**Comment by minherc** [comment]
@VladisLove1 
ты должен сделать `clique.propose(<address>)` на тех нодах которые прописаны были в генезис как имеющие право подписи и добавить новые адреса
что за адреса можно посмотреть через `clique.getSnapshot()`

ps ты не разбирался как гасить ноды? например из 4 одну погасить как ?
если просто выйти или miner.stop() то процесс майнинга прекращается на оставшихся нодах
