### ISSUE TITLE
Bootnode flag not found in geth 1.5.4 on windows 

### ISSUE THREAD

**Issue by satyamakgec** [ethereum/go-ethereum#14456]
#### System information

Geth version: `1.5.4`
OS & Version: Windows

#### Expected behaviour
according to the documentation after entering the command > bootnode it shoud return 
Fatal: Use -nodekey or -nodekeyhex to specify a private key

#### Actual behaviour
> bootnode
ReferenceError: 'bootnode' is not defined
    at <anonymous>:1:1

none of the bootnode command is working please help me out to solve this issue

**Comment by karalabe** [comment]
Bootnode is not a console command. It is an executable binary shipped with Geth 1.6.0 and upward. It was part of go-ethereum previously too but wasn't bundled into the release packages, you needed to build manually.

If you update to Geth 1.6.1, you should get the `bootnode` binary too.
