### ISSUE TITLE
how to get token transfers txns，has api ?

### ISSUE THREAD

**Issue by 362228416** [ethereum/go-ethereum#14462]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

I want get the token transfers txs, like this: 

https://ropsten.etherscan.io/address/0x3717C8289d9603b7a3337B8EB6b543A7610400EB#tokentxns

but wo can't found the api, help !!

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
If you read through the ERC20 spec https://github.com/ethereum/EIPs/issues/20, you'll find a section called Events. That defines the different events token contracts emit, which you can monitor via contract event logs.
