### ISSUE TITLE
miner: question about timestamp check

### ISSUE THREAD

**Issue by ljhzds** [ethereum/go-ethereum#14466]
#### System information

Geth version: `latest`
OS & Version: Linux

I used go-ethereum to develop my block-chain project.
when there is a timestamp diff of every nodes, the miner cannot commit the transactions.

The error is "this will ensure we're not going off too far in the future?"

Can i just delete these codes below:
https://github.com/ethereum/go-ethereum/blob/master/miner/worker.go

// this will ensure we're not going off too far in the future
	if now := time.Now().Unix(); tstamp > now+1 {
		wait := time.Duration(tstamp-now) * time.Second
		log.Info("Mining too far in the future", "wait", common.PrettyDuration(wait))
		time.Sleep(wait)
	}

#### Backtrace

````
[backtrace]
````

**Comment by fjl** [comment]
Mining requires an accurate clock. Nodes won't process blocks with a timestamp that's too far ahead of the local clock.

**Comment by ljhzds** [comment]
@fjl does that mean all the nodes should be the same time clock?
