### ISSUE TITLE
RPC fromBlock/toBlock no longer defaults to "latest" in geth 1.6.1

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/go-ethereum#14467]
#### System information

Geth version: `1.6.1`
OS & Version: Linux

#### Expected behaviour

According to the documentation of the [eth_newFilter](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter) RPC call, the `fromBlock` and `toBlock` fields default to `"latest"` if left empty. This was working up to geth 1.6.0.

#### Actual behaviour

With geth `1.6.1` a call to the client with empty block fields will produce an error instead of defaulting to `"latest"`.

#### Steps to reproduce the behaviour

Just an example RPC call with the error:

```
curl localhost:29871 -X POST --data '{"jsonrpc": "2.0", "method": "eth_newFilter", "params": [{"fromBlock": "", "address": "0x29d73fd964f1d5a9b2ba668c4ac31c61744a1b21", "topics": ["0xdffbd9ded1c09446f09377de547142dcce7d c541c8b0b028142b1eba7026b9e7"], "toBlock": ""}], "id": 229}'
```

will produce the following error:

```
{"jsonrpc":"2.0","id":229,"error":{"code":-32602,"message":"invalid argument 0: empty hex string"}}
```

**Comment by fjl** [comment]
This is a regression from https://github.com/ethereum/go-ethereum/pull/13886

**Comment by bas-vk** [comment]
From the spec:
> fromBlock: QUANTITY|TAG - (optional, default: "latest") Integer block number, or "latest" for the last mined block or "pending", "earliest" for not yet mined transactions.

> toBlock: QUANTITY|TAG - (optional, default: "latest") Integer block number, or "latest" for the last mined block or "pending", "earliest" for not yet mined transactions.

The problem in your example is that both the from and to block are given an empty string which is an invalid value. If you leave both fields out, or given them the `null` value than it will fallback to the default. I believe this is correct behavior.

**Comment by LefterisJP** [comment]
I always assumed that providing an empty String should be treated the same way as if giving a null value, so it should fallback to default and not raise an error.
