### ISSUE TITLE
Which hex numbers no longer permit zero digit prefix?

### ISSUE THREAD

**Issue by flyswatter** [ethereum/go-ethereum#14477]
Geth recently got strict about hex numbers with leading zero digits after ‘0x’, with the error `invalid argument 0: hex number has leading zero digits after 0x`. 

Can I get a list of parameters that are now more strict than they were before? We’re getting MetaMask users spontaneously reporting each individual parameter, would be nice to fix them all at once.

**Comment by flyswatter** [comment]
Related to https://github.com/MetaMask/metamask-plugin/issues/1429#issuecomment-301631214

**Comment by bas-vk** [comment]
Basically all methods that accept a [quantity](https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding) cannot have leading zero's.

**Comment by flyswatter** [comment]
Okay, thank you. Also, as a client developer (MetaMask), it would be really great to be made aware of pending deprecations and breaking API changes before they're implemented. Is there a place I can subscribe to that newsletter?
