### ISSUE TITLE
maxpeers reached and trusted-nodes.json ignored

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#14472]
#### System information

Geth version: v1.6.1-stable-021c3c28 and v1.6.0-stable-facc47cb
OS & Version: Linux (Ubuntu 16.04) and Windows 10

#### Details
I have two computers running Geth

On both computers I have a static-nodes.json and a trusted-nodes.json file in the datadir and they contain one entry: the other node...

I am under the impression that placing a node into trusted-nodes.json would not count against the maxpeers? However, running Geth with default maxpeers (not specifying --maxpeers, which defaults to 25) results in the systems not connecting to each other when net.peerCount = 25 on one of the nodes.

If I were to restart the node with a peer count of 25 they'll connect to each other just fine. So it appears to me that the trusted-nodes.json is being ignored when default maxpeers is reached?

One node is v1.6.1-stable-021c3c28 and the other is v1.6.0-stable-facc47cb

I can reproduce at any time as one of my nodes is pretty much "public" over 30303 and always has 25 nodes, while the other does not...

This might be related to #3326

#### Expected behaviour
Nodes configured in trusted-nodes.json connect to each other regardless of the number of peers connected

#### Actual behaviour
Nodes configured in trusted-nodes.json only connect if current peer count is less than maxpeers

#### Steps to reproduce the behaviour
configure trusted-nodes.json on two systems
start one system and let it reach maxpeers (without the --maxpeers setting this is 25)
start the other system, they will not connect

**Comment by paulvi** [comment]
Where is documentation about `trusted-nodes.json` ?

Commits like 62fc96620d864291dc56bae5568cbaa44714c19f should go with documentation updates.

**Comment by smartins** [comment]
I'm having the exact problem with the latest geth version. static-nodes.json work just fine (I can stop and restart my nodes and they will connect to each other) but if one of them reaches the maxpeers, then even if my other nodes are on the trusted-nodes.json file, they won't be able to connect.

I have the exact same items on trusted-nodes.json and static-nodes.json.

Any idea if this is a recurring bug or and I missing something?

**Comment by holiman** [comment]
> Where is documentation about trusted-nodes.json ?

Here, it seems: 
https://geth.ethereum.org/docs/interface/peer-to-peer#trusted-nodes
