### ISSUE TITLE
addPeer not create 2 node in --dev envirnment.

### ISSUE THREAD

**Issue by padmaniyogesh** [ethereum/go-ethereum#14471]
#### System information
Windows 10

Geth version: `geth version`: 1.4.11 stable
OS & Version: Windows/Linux/OSX : Windows10
Commit hash : (if `develop`)

#### Expected behaviour
2 node must be peer using addpeer command.

#### Actual behaviour
aftr add addpeer it return true but when run command "net.peerCount" on geth console it return 0.

#### Steps to reproduce the behaviour
1 st node : 
geth --dev --datadir "C:\wallet\multinode\node1" --networkid "1234" --port "30301" --rpcport "8101" --ipcdisable console init "C:\wallet\multinode\node1\genesis.json"

2 st node : 
geth --dev --datadir "C:\wallet\multinode\node2" --networkid "1234" --port "30302" --rpcport "8102" --ipcdisable console init "C:\wallet\multinode\node2\genesis.json"

>
 {46156a24f47c665d70d409ab75f8f4899dea8ab3a1c63e3d9e8ce4d2b66588deba9896@10.190.209.1:30301")
true
> net.peerCount
0

#### Backtrace

````
[backtrace]
````

**Comment by drouillard** [comment]
Networking is disabled in dev mode.

**Comment by fjl** [comment]
@drouillard is right. Dev mode doesn't have networking because the blockchain it creates has no security whatsoever.

**Comment by drouillard** [comment]
For future travelers... 

The way to set up a private network with networking is to use the clique (POA) protocol. See https://blog.ethereum.org/2017/04/14/geth-1-6-puppeth-master/
