### ISSUE TITLE
mobile: Import raw key

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#14481]
As far as I see there are currently 2 ways to import a key:
 * from JSON file via importKey(ByteArray,String,String)
 * from presale JSON file via importPresaleKey(ByteArray,String)

It would be great to be able to import a plain private key (like the ones MyEtherWallet prints on the paper-wallet)

**Comment by romangrechin** [comment]
```
ecdsaKey, err := crypto.ToECDSA(common.Hex2Bytes("3acb54c6a6ce647d8ae0d74907bbd2c67ae285d4e4abe4b578d0403020e2d4e4"))
if err != nil{
	log.Fatal(err)
}
auth := bind.NewKeyedTransactor(ecdsaKey)
```
