### ISSUE TITLE
FromHex() of a single digit number

### ISSUE THREAD

**Issue by philipcmonk** [ethereum/go-ethereum#14488]
#### System information

Geth version: 1.61-stable
OS & Version: Ubuntu 16.04

#### Expected behaviour

`common.HexToAddress("5").Hex()` should give `0x0000000000000000000000000000000000000005'

#### Actual behaviour

Gives `0x0000000000000000000000000000000000000000`

#### Steps to reproduce the behaviour

Run the above code.

#### Notes

Why does this (https://github.com/ethereum/go-ethereum/blob/83721a95/common/bytes.go#L34) check exist?  It seems to have been around ever since `FromHex` was introduced here: https://github.com/ethereum/go-ethereum/commit/ddf17d93acf92ef18b0134f19f22220362e06bad#diff-44721aff1ab930d9103fb9c3355914d1R41

Would there be any issue with just deleting the conditional?

**Comment by philipcmonk** [comment]
Found out why we can't simply eliminate the check:  we can't create an address from an empty byte slice.  I fixed this in #14489 by special-casing the `len(s) == 1` case in `FromHex`.

**Comment by obscuren** [comment]
> Why does this (https://github.com/ethereum/go-ethereum/blob/83721a95/common/bytes.go#L34) check exist?

Because a hex string must be preceded by `0x`, i.e. `len(input) > 1`. 

`FromHex` should not be used to parse numbers, it should only be used to convert hex strings to a byte slice.

If you'd like to parse numbers please use the [`hexutil`](https://godoc.org/github.com/ethereum/go-ethereum/common/hexutil) package.

**Comment by philipcmonk** [comment]
> Because a hex string must be preceded by 0x, i.e. len(input) > 1.

This is incorrect, since the next line of code checks whether it includes a "0x", and deletes it if it does. 
 `FromHex` happily accepts hex addresses without a "0x".  Should that part be removed?

> `FromHex` should not be used to parse numbers, it should only be used to convert hex strings to a byte slice, 

`0x0`-`0xf` are legal addresses, and in the contract we're writing, they're useful addresses as well.  If `FromHex` cannot handle them correctly, then `HexToAddress` should not use it.

> which means they must be even length.

Again, `FromHex` normalizes odd-length addresses by prepending a `0`.  Should that be removed as well?

I submit that "HexToAddress" is misleadingly named, since `HexToAddress("7")` produces the address `0x0`.  I'll create my own function for our project.
