### ISSUE TITLE
Geth 6.2: miner.start() returns null and miner's hash-rate drop down due to the update

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/go-ethereum#14487]
#### System information

Geth version: 1.6.2-unstable 
OS & Version: Linux and OSX

`miner.start()` returns null, it used to return number of processes assigned. Is it normal? `miner.start(num)` num identifies the thread number?

    > miner.stop()
    true
    > miner.start(4)
    null

I have a small private net and there is only one miner. The miner used to work for almost couple of months with 503.7 KH/s (since it has been launched with geth v5.9) but now it works with 103.7 KH/s when I updated geth with 6.2 there is this sudden drop down. 

This change occur for my other nodes where hash-rate is get dramatically slower. When I check `top` geth consumes all the CPU power, I assume miner works with full CPU power.

**[Q]** What might be the reason for miner's hash rate drop down? Could it be related to geth's update on version 6.2? Did anyone faced with similar issue?

**[Q]** This is very inefficient. If the node use much smaller hash-rate why on the background does the CPU consumes all the power?

Please note that, miner's hash-rate is much faster when I use Parity or if I use geth version smaller than 6.0.

Thank you for your valuable time and help.

**Comment by karalabe** [comment]
Previous versions of Geth didn't return the number of threads either, they just logged it (as the current should) and returned `true` (https://github.com/ethereum/go-ethereum/blob/release/1.5/eth/api.go#L141).

The 1.6.x release family features a new Go implementation of ethash, which among others was also converted to use memory mapping (Geth 1.5 and before just loaded the DAG into memory). This might mean that it may take some warmup time to cache the entire DAG. Please let it run for a bit (maybe 10 minutes) and see how the hashrate evolves then. The measurement of the hashrate should also be more precise, but averaged over the last few minutes.

**Comment by avatar-lavventura** [comment]
The miner has been running for few days, but I did not see any update on its hash-rate. For example, it is using 4 full CPU and hash-rate is stuck at around 135.2 KH/s, it was always around 500 KH/s before the update. Please note that I cleaned the `.ethash/`  folder and currently there is only one miner on the system. @karalabe

**Comment by avatar-lavventura** [comment]
Please note that: I observe that on my private chain, after the update, all miners' hash rate drop down around 5 times all together. @karalabe

**Comment by avatar-lavventura** [comment]
Hash-Rate has get back to normal when I revert geth to 5.9. But On version 6.0+ on my blockchain, even I wait for 10 minutes or an hour, hash-rate never get back to normal. Maybe it is a issue related to private network setup. @karalabe

**Comment by eBusinessMan** [comment]
I met the problems above just like u ,have u get the solutions and fix it ?

**Comment by avatar-lavventura** [comment]
No I did not get any solution to fix, I get `geth` revert back to 5.9 version. @eBusinessMan

**Comment by kaansari** [comment]
7/11/17. Installed the latest version of geth and having same issue.  I am not sure what version to go back to.  I will try 5.9.

**Comment by jboilesen** [comment]
Still a serious issue, guys. I was using 1.6.7 and I couldn't mine at all.

miner.start() always returns null.

**Comment by kolkov** [comment]
What do you see when you call this function
eth.getHashrate()?

**Comment by ricott1** [comment]
same problem: minser.start() return null, eth.getHashrate() returns undefined

**Comment by Phil192** [comment]
Seems `eth.getHashrate()` is deprecated right now. Use `eth.hashrate`.

**Comment by noka03** [comment]
Im having the same issue... eth.hashrate returns 0 for me.

**Comment by Xiaoyang-Zhu** [comment]
yeah, even if the latest version of geth v1.89,  the miner.start() return null, but the mining has been started. When I run the eth.hashrate the result is 0

**Comment by csokun** [comment]
I tried a few version of v1.8.x series lastly geth v.1.8.11 `miner.start()` return `null`, block mined but `eth.hashrate` return `0` looking for answer all over, but I found no evident of behaviour change nothing from release note either

**Comment by aerth** [comment]
start with --metrics flag to see hashrate

**Comment by csokun** [comment]
@aerth thanks, I can see `hashrate` with `--metrics`. However, correct me if I am wrong. According to https://github.com/ethereum/go-ethereum/wiki/Metrics-and-Monitoring describe metrics feature as a debugging tool. Doesn't sound like a good idea to start miner node with `--metrics` in order to get report on `hashrate` (e.g if I want to report miner hashrate to eth stats). 

Is there any thread discussing this new behaviour?

**Comment by karalabe** [comment]
Missing hashrate was a regression. It was fixed in the latest stable release. Please update. As for the potential slowdown, we did switch out the C++ ethash code to a Go version a couple years back. CPU mining in general is not feasible, so there's not much point in striving to absolute max out performance. A well-enough performing CPU miner is enough for private/testnets.

**Comment by Renu353** [comment]
web3.miner.start(4) what is the significance of 4 here?

**Comment by avatar-lavventura** [comment]
@Renu353 : `web3.miner.start(<number>)`, is defining number of cores assigned for mining.

**Comment by Renu353** [comment]
Means number of CPU cores assigned for mining right

**Comment by avatar-lavventura** [comment]
@Renu353 : Yes
