### ISSUE TITLE
registrar on 0.9.36

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1448]
Geth
Version: 0.9.36
Git Commit: 423c2f499c2350ae54d02a3151686ebd39fc8c94
Protocol Versions: [61 60]
Network Id: 0
Go Version: go1.4.2

geth running and synced to latest
> eth.blockNumber
839146

> registrar
{
  address: '0x0',
  Changed: function (),
  PrimaryChanged: function (),
  Registrar: function (),
  addr: function (),
  allEvents: function (),
  content: function (),
  disown: function (),
  name: function (),
  owner: function (),
  register: function (),
  reserve: function (),
  setAddress: function (),
  setContent: function (),
  setSubRegistrar: function (),
  subRegistrar: function (),
  transfer: function ()
}
> registrar.address
'0x0'

EXPECTED: registrar to have valid address

also
```
> registrar.addr('HashReg')
'0x'
```

**Comment by zelig** [comment]
yes I am unsure about hardwiring this in the code as it used to be. You can set it simply:

     admin.setGlobalRegistrar("0xc6d9d2cd449a754c494264e1809c50e34d64562b")

**Comment by ethers** [comment]
I checked the address 0xc6d9...  with eth.getCode, and there is code, so I tried it but no success still...

```
> admin.setGlobalRegistrar("0xc6d9d2cd449a754c494264e1809c50e34d64562b")
''
> registrar
{
  address: '0x0',
  Changed: function (),
  PrimaryChanged: function (),
  Registrar: function (),
  addr: function (),
  allEvents: function (),
  content: function (),
  disown: function (),
  name: function (),
  owner: function (),
  register: function (),
  reserve: function (),
  setAddress: function (),
  setContent: function (),
  setSubRegistrar: function (),
  subRegistrar: function (),
  transfer: function ()
}
> registrar.addr("HashReg")
'0x'
```

**Comment by zelig** [comment]
yes its confusing a little i know. You must set the js `registrar` to the correct address to query it:

```js
globalRegistrarAddr = "0xc6d9d2cd449a754c494264e1809c50e34d64562b"
registrar = GlobalRegistrar.at(globalRegistrarAddr);
registrar.addr("HashReg")
```

These will set the addresses internally for the node:
```js
admin.setGlobalRegistrar(globalRegistrarAddr);
admin.setHashReg();
admin.setUrlHint();
```

**Comment by yyhwhp** [comment]
have a problem, ReferenceError: 'GlobalRegistrar' is not defined, why will promt this error?
