### ISSUE TITLE
Bootnode command not found

### ISSUE THREAD

**Issue by terencecnt** [ethereum/go-ethereum#14484]
#### System information

Geth version: 1.6.1
OS & Version: OSX

#### Expected behaviour
Expected bootnode to be installed with ethereum from homebrew

#### Actual behaviour

-bash: bootnode: command not found

**Comment by Ali92hm** [comment]
Yes, I notice that as well. Had to build go-ethereum manually and link the binaries!

**Comment by agarcian** [comment]
@ali92hm  How do you do that?   (build go-ethereum manually and link the binaries)
