### ISSUE TITLE
Fatal: Could not read wallet file: open import: no such file or directory

### ISSUE THREAD

**Issue by rpw98** [ethereum/go-ethereum#14496]
When I run 'geth wallet import my-presale.json' it is always giving the following error:

Fatal: Could not read wallet file: open import: no such file or directory

But the file is there! I got this error after I updated to the latest geth :-( Should've stayed with the old version. It was working fine before I update...

#### System information

Geth version:
Version: 1.6.1-stable
Git Commit: 021c3c281629baf2eae967dc2f0a7532ddfdc1fb
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.8.1/libexec

OS & Version: macOS 10.12.5
Commit hash : (if `develop`)

**Comment by karalabe** [comment]
You don't need `import` there, just `geth wallet my-presale.json``

**Comment by karalabe** [comment]
@bas-vk will take a look if we by any chance accidentally broke this recently.

**Comment by karalabe** [comment]
@rpw98 Thanks for this report, it was an accidental regression while cleaning up the CLI flags. The old behavior was reintroduced and will get release Monday. Until then you can do the same action by omitting the `import` subcommand for Geth 1.6.1.
