### ISSUE TITLE
accounts/abi: Event logging

### ISSUE THREAD

**Issue by VoR0220** [ethereum/go-ethereum#14508]
Be able to unpack variables and read data from an event log. Make this easily compatible with the bindings so that the bind package could bind with the client to read and filter through the logs while getting actual types and values.

**Comment by stevenroose** [comment]
Anyone working on this? Before full ABI support, just being able to access and interpret the arguments of logs would be a great start. I asked a question about that [here](https://ethereum.stackexchange.com/questions/27080/how-to-access-non-indexed-event-arguments-from-go-types-log) on stack exchange.

**Comment by VoR0220** [comment]
Yep. It's almost done. PR is here: https://github.com/ethereum/go-ethereum/pull/14743
