### ISSUE TITLE
Documentation of --bootnodes is outdated

### ISSUE THREAD

**Issue by ripper234** [ethereum/go-ethereum#14503]
--bootnodes is documented [here](https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options) and [here](https://github.com/ethereum/go-ethereum/blob/1c2f6f5597a6815f7ddca6374acb35e1ea1b0407/cmd/faucet/faucet.go) and [here](https://github.com/ethereum/go-ethereum/wiki/Connecting-to-the-network) to use a comma-separated style.

However, in this #3547 it seemed comma-separated bootnodes has gone away and if I'm reading this correctly won't be returning since the issue is closed (the workaround is to use multiple --bootnodes instances).

The documentation should be fixed to represent the different usage.

**Comment by karalabe** [comment]
That was only a bug. AFAIK comma separated bootnodes do work.

**Comment by ripper234** [comment]
Correct. I was testing with an old version of geth (1.3.x), this works now in 1.6.1.
