### ISSUE TITLE
https://github.com/ethereum/go-ethereum/issues/14381

### ISSUE THREAD

**Issue by Rungrot999** [ethereum/go-ethereum#14505]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
Is this a ReIssue ?-)

**Comment by karalabe** [comment]
https://github.com/ethereum/go-ethereum/issues/14381#issuecomment-303676481
