### ISSUE TITLE
Some contract events are not available for notification

### ISSUE THREAD

**Issue by 362228416** [ethereum/go-ethereum#14520]
#### System information

Geth version: `1.6.1`
OS & Version: Linux

#### Expected behaviour

I want to get the contract in all transfer record, through the event monitoring contract, but I don't know why, sometimes events did not inform my application, I use the web3 writing listening

code: 

const contract = web3.eth.contract(abi)
const contractInstance = contract.at(config.contractAddress)
contractInstance.allEvents({fromBlock: 0, toBlock: 'latest'}).watch((error, tx) => {
    console.log(tx)
    // .. save tx
})

help!

#### Actual behaviour

New events can be retrieved shortly after the application is started, but they won't be available for a long time

#### Backtrace

````
[backtrace]
````

**Comment by stiv-yakovenko** [comment]
I observe the same, I can't .get and can't .watch events, but I can see event data in the transaction.
Looks like a ethereum kernel bug, where can I report it?
