### ISSUE TITLE
Fund lost due to strange reason

### ISSUE THREAD

**Issue by DSofter** [ethereum/go-ethereum#14538]
#### System information

Geth version: 1.6.0-stable
OS & Version: OSX

I sent some ETH to my contract wallet and was not able to access it. Basically the contract showed up as grey in Mist.

![image](https://cloud.githubusercontent.com/assets/1687829/26540708/84f491ca-4407-11e7-993b-bdef66927a7a.png)

Any idea how I can recover the fund?

Thank you!

**Comment by karalabe** [comment]
The funds seem to be safe in that contract https://etherscan.io/address/0xdd31d20c5be84b7f68373033de5e7a085b8e5671

I'm unsure what it means if it's grayed out (perhaps you're on a different network in mist, not the mainnet?). Or perhaps you're not synced, and such it only knows it created the contract, but can't find it yet on your local chain? Best ask the Mist people about this. @frozeman @luclu 

Regarding how you can recover the funds, I'm assuming it's a multisig contract (or similar). I'd say that you should be able to interact with the contract with the account you used to create it. Again though, @frozeman @luclu please jump i with details.

**Comment by DSofter** [comment]
@karalabe Thanks for the quick response! I'm on mainnet and pretty sure it's fully synced.

Below is what I see from the `Hello` contract:
![image](https://cloud.githubusercontent.com/assets/1687829/26541260/d7603e26-4409-11e7-8a98-9ca5aae324ad.png)

This is what I see from the `DDD` contract:
![image](https://cloud.githubusercontent.com/assets/1687829/26541272/e6a88f14-4409-11e7-83fe-4e2d813ac3eb.png)

So it seems like something is wrong.

**Comment by holiman** [comment]
It seems you didn't create a contract, but instead sent the funds to a (normal) account. 

https://etherscan.io/address/0xdd31d20c5be84b7f68373033de5e7a085b8e5671
The transaction https://etherscan.io/tx/0x81809c96930d037d3044cbe5abad6e8f52ac09acc5eb051f8fabf197273bb198 shows that you simply sent the ether to `0xDd31D20C5Be84B7F68373033DE5E7a085b8e5671` - no data. 
I have no idea where that address comes from.

**Comment by DSofter** [comment]
@holiman That's very unfortunate. As you can see the address came from the contract wallet:

![image](https://cloud.githubusercontent.com/assets/1687829/26544092/58665360-4415-11e7-92e1-d522ad7e1407.png)

**Comment by DSofter** [comment]
@frozeman @luclu @holiman @karalabe Can anyone help? Thanks so much!

**Comment by alexvandesande** [comment]
@DSofter can you describe the steps involved creating and transferring that wallet? Do you remember if there were two transactions? Did you manually deploy the contract? Did you wait for the wallet to have 12 confirmations?

I just discussed with the team and the only way we can see something like that happening is if you deployed a wallet, immediately sent ether to it, and then there was a chain reorganization in which the wallet did not deploy. It's a very weird case

If that's the case there's a chance of recovering that ether, specially if you didn't make any other transactions with that account: if you use the next nonces to deploy a multisig transaction then there's a chance that you'll be able to deploy a wallet in that contract and recover it.

**Comment by DSofter** [comment]
@alexvandesande Thanks for the response! 

To your point:
> the only way we can see something like that happening is if you deployed a wallet, immediately sent ether to it

I think that's what happened.

I sent another transaction to that contract wallet: https://etherscan.io/address/0xdd31d20c5be84b7f68373033de5e7a085b8e5671

Please let me know what steps I should follow to recover the fund. Appreciate that!

Also I feel like if there's some kind of mechanism to stop people from sending ETH to a contract wallet before it's ready that would be awesome.

**Comment by DSofter** [comment]
@alexvandesande I was trying to reproduce the bug on testnet, and realized that the issue could have been caused by the fact that I somehow managed to create the contract wallet with my main account (0 ETH balance )

**Comment by DSofter** [comment]
@alexvandesande I was trying to reproduce the bug on testnet but was not able to.

I tried to recall what happened and I'm pretty sure I created the `DDD` wallet with my newly set up main account, which has 0 ETH balance. In retrospect that doesn't seem possible but I'm pretty sure that's what happened. Could that be the cause? If so is it possible to reclaim my funds?

**Comment by DSofter** [comment]
@alexvandesande @frozeman @luclu @holiman @karalabe OMG I found out why. The `DDD` wallet (0xdd31d20c5be84b7f68373033de5e7a085b8e5671) was created on TESTNET! 

If I switch to testnet it shows up as a normal wallet:
![image](https://cloud.githubusercontent.com/assets/1687829/26565217/1ef6cc8e-449e-11e7-9146-7b6baca82ffa.png)

Such a stupid mistake. But I have a recommendation: is it possible to make the UI more clear about the distinction between maintest and the testnet. Ideally if I'm on maintest I'm not supposed to see anything on testnet. Does that make sense?

**Comment by DSofter** [comment]
Another thing I'm confused about is that why do we even allow transactions across test and main net? Is it possible to cut them separate?

**Comment by holiman** [comment]
Hm, seems eth is lost- the contract was created at nonce 0, and you're already past that on mainnet :(On May 30, 2017 3:40 AM, DSofter <notifications@github.com> wrote:@alexvandesande @frozeman @luclu @holiman @karalabe OMG I found out why. The DDD wallet (0xdd31d20c5be84b7f68373033de5e7a085b8e5671) was created on TESTNET!
If I switch to testnet it shows up as a normal wallet:

Such a stupid mistake. But I have a recommendation: is it possible to make the UI more clear about the distinction between maintest and the testnet. Ideally if I'm on maintest I'm not supposed to see anything on testnet. Does that make sense?

**Comment by DSofter** [comment]
@holiman Not sure who's the right person to tag, but can we let Mist people know about my proposal:

> But I have a recommendation: is it possible to make the UI more clear about the distinction between maintest and the testnet? Ideally if I'm on mainnet I'm not supposed to see anything from testnet, as opposed to just make it grey. Does that make sense?

**Comment by holiman** [comment]
Yeah @frozeman what do you say ? 
Cc:ing @cdetrio for good measure also...

**Comment by alexvandesande** [comment]
@DSofter yes that would explain it. Mmm now I see what happened. Indeed we are greying out contracts on different networks, but I agree we can do more to prevent these issues on the future. Thanks for the report and I'm sorry about your lost ether.

**Comment by DSofter** [comment]
Mind sending me some ETH for helping come up with this proposal? haha just kidding @alexvandesande
