### ISSUE TITLE
mobile: go.Universe$proxyerror: resource temporarily unavailable

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#14541]
#### System information

Geth version: 1.6.1
OS & Version: Android

I got this trace:

````
go.Universe$proxyerror: resource temporarily unavailable
at org.ethereum.geth.Node.start(Native Method)
at org.walleth.core.GethLightEthereumService$onStartCommand$1.run(GethLightEthereumService.kt:107)
at java.lang.Thread.run(Thread.java:762)
````

To be able to handle this properly it would be good if there is a way to know which resource is  temporarily unavailable.
It happens when starting the node. Got it from a user - never saw it in my tests on a released version before. But I can reproduce it when starting the node in a separate process (tried this when trying to find a way around the sync issues). When starting as a separate proces I always get this exception (interestingly the node and block sync still starts)

**Comment by karalabe** [comment]
Could it be that the leveldb database is already open by another process?

**Comment by karalabe** [comment]
Or perhaps the port you are trying to bind?

**Comment by ligi** [comment]
Not sure - in the experiments I did with the separate process I don't think so as the pattern was:
 * adding process=":foo" to the service in the Manifest -> this error
 * removing it -> no error

For what happened to the user: I can ask him - perhaps status was open at the same time so the port was blocked..

But a nicer error with the cause (e.g. Port is used) would be nice anyway. E.g. for the port case so I can inform the user to close other light-client apps.
