### ISSUE TITLE
Unable to unlock rinkeby account - Error: no key for given address or file

### ISSUE THREAD

**Issue by dotnetspec** [ethereum/go-ethereum#14549]
#### System information
* Operating System: Win 10 32 bit
* Truffle version: v3.2.1
* Ethereum client: Geth 1.6.1-unstable
* node version: v7.9.0
* npm version: 4.6.1

#### Expected behaviour
From the Geth console I expect to be able to unlock my existing metamask rinkeby account:
rinkeby is synced locally

geth --networkid 4 attach

> personal.unlockAccount('0x5...')
Unlock account 0x5...
Passphrase: [entered]
Account 0x5... unlocked

#### Actual behaviour

Error: no key for given address or file
But I am able to correctly retrieve the account balance with:
web3.eth.getBalance('0x5...')

#### Steps to reproduce the behaviour
As for expected behaviour

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Did you import you metamask account into Geth? The address of an account that you type is in merely a "name", it does not contain the private key that can authorize transactions. To unlock an account, you need the associated private key. I'm assuming that if you generated it via metamask, you can download it somehow, which can then be imported into Geth. When you have your key imported, only then can you unlock it.

**Comment by dotnetspec** [comment]
Hi,
Apologies for delay:

I tried it with:
personal.unlockAccount('0x5d...account number','private_key_copied_from_metamask')
still get:
Error: no key for given address or file

**Comment by tailongwang** [comment]
@karalabe Me too
`curl --data '{"method":"personal_unlockAccount","params":["0x*********","",null],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`
`{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"no key for given address or file"}}`

**Comment by bitboyz** [comment]
Recently came across this issue, did anyone figure it out?

**Comment by Ebonsignori** [comment]
I've found that the private key that MetaMask exports is the private key to your main Etherium network wallet.

My workaround was to send ETH and tokens to my MetaMask account and sign anything with front-end JS and MetaMask.
