### ISSUE TITLE
Insufficient funds error showup when sending the entire balance

### ISSUE THREAD

**Issue by jackyxie** [ethereum/go-ethereum#14544]
#### System information

Geth version: `Geth/v1.6.0-stable`
OS & Version: Linux ubuntu 16.04 / go1.8.1

#### Expected behaviour

Set gas = 21001 and gasPrice = 0.000000009, and send entire balance from my address to another address

relative param and value:

string(20) "balance: 10.00000000"
string(15) "value: 9.999811"
string(15) "txfee: 0.000189"
string(10) "gas: 21001"
string(21) "gasPrice: 0.000000009"

#### Actual behaviour
Some address show up "Insufficient funds for gas * price + value"

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
How do you calculate the "entire balance" ? 
Here's my own script to send the entire balance: 
```javascript
function sendAllTx(from, to ){
	gc = new BigNumber(20e9)
	g = new BigNumber(21000)
	b = eth.getBalance(from)
	v = b.sub(gc.mul(g))
	var tx = {from:from, to:to, gasPrice:gc, gas:g, value:v};
	return tx;
}
```

You need to use bignumbers to get the math correct, otherwise you'll leave some dust behind, or you'll fails as above...

**Comment by ligi** [comment]
Your fee calculation is wrong: 21001*9 = 189009

**Comment by holiman** [comment]
Yup. Use `BigNumber` and you should be fine
