### ISSUE TITLE
Double commit new work jobs after mining a block?

### ISSUE THREAD

**Issue by jzencore** [ethereum/go-ethereum#1455]
On the current geth 0.9.36 I'm consistently seeing new work committed twice on same new block immediately following the mining of a previous block, causing the miner to reset work loop twice for the same new block.   Sometimes the double commits are the same, sometimes they differ only in the number of transactions. Are others seeing this behavior, is it a bug or is it a feature?

For example:

I0709 02:59:41.768021   25556 worker.go:293] 🔨  Mined block (#837904 / 04fba687). Wait 5 blocks for confirmation
I0709 02:59:41.970673   25556 worker.go:487] commit new work on block 837905 with 27 txs & 0 uncles. Took 202.617847ms
I0709 02:59:42.109281   25556 worker.go:487] commit new work on block 837905 with 27 txs & 0 uncles. Took 136.876236ms
I0709 02:59:50.314829   25556 chain_manager.go:671] imported 1 block(s) (0 queued 0 ignored) including 45 txs in 214.553523ms. #837905 [a436fb9a / a436fb9a]
I0709 02:59:50.364360   25556 worker.go:487] commit new work on block 837906 with 11 txs & 0 uncles. Took 49.433694ms
I0709 02:59:53.545131   25556 chain_manager.go:671] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 17.423299ms. #837906 [2cd6604f / 2cd6604f]
I0709 02:59:54.939527   25556 worker.go:487] commit new work on block 837907 with 135 txs & 0 uncles. Took 1.394284192s
I0709 03:00:00.337730   25556 worker.go:293] 🔨  Mined block (#837907 / d3c238be). Wait 5 blocks for confirmation
I0709 03:00:00.757117   25556 worker.go:487] commit new work on block 837908 with 65 txs & 0 uncles. Took 419.344846ms
I0709 03:00:01.049974   25556 worker.go:487] commit new work on block 837908 with 65 txs & 0 uncles. Took 291.313109ms

I see the same behavior in 0.9.39 too.

**Comment by fjl** [comment]
Should be resolved in #1780 (likely earlier, given that this is an Olympic issue).
