### ISSUE TITLE
Console errors while initiating transaction in light mode

### ISSUE THREAD

**Issue by JikkuJose** [ethereum/go-ethereum#14556]
##### Geth
Version: 1.6.1-stable
Git Commit: 021c3c281629baf2eae967dc2f0a7532ddfdc1fb
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: darwin
GOPATH=/Users/jikkujose/Go
GOROOT=/usr/local/Cellar/go/1.8.3/libexec

##### Expected behaviour

Tried a transaction via `console` when `geth` was in _light_ mode:
```
> eth.sendTransaction(payload)
```

`payload` is an object of the form: 
```
{
  from: "<address>",
  to: "<address>",
  value: <ethInWei>
}
```
Expected the transaction to go through; the address were well formed, have balances & were unlocked.

##### Actual behaviour
```
Error: no suitable peers available
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
```

##### Steps to reproduce the behaviour

1. Delete chain
2. Resync in light mode
3. Do a transaction

**Comment by karalabe** [comment]
@zsfelfoldi PTAL

**Comment by JikkuJose** [comment]
Any help?

**Comment by JikkuJose** [comment]
Now, when starting the light client itself I am getting the error in log:

`ERROR[<date_stamp>] Failed to retrieve current release       err="Missing trie node <long_hash>`

**Comment by grwlf** [comment]
Same thing here

**Comment by tjerkw** [comment]
So whats the state of the lightmode? I am using lightmode otherwise it change days to sync, and it only downloads around 200 blocks every second, which takes a lot of time

**Comment by Qkyrie** [comment]
same issue here. Disabling lightmode until further updates

**Comment by worldlyjohn** [comment]
any fix yet?  using light mode bc got to the party late and dont want to download 300G to run a full node...

**Comment by JayMaree** [comment]
Same issue
