### ISSUE TITLE
Geth randomly stopped working and blockchain won't download anymore

### ISSUE THREAD

**Issue by spencerross** [ethereum/go-ethereum#14554]
#### System information

Geth version: Geth/v1.6.1-stable-021c3c28/windows-amd64/go1.8.1 (Geth 1.6.1)
OS & Version: Windows 10 
Commit hash : (if `develop`)

#### Expected behaviour
for Geth to run and continue with downloading the blockchain

#### Actual behaviour
(I type geth in cmd and press enter)
INFO [05-30|22:02:24] Starting peer-to-peer node               instance=Geth/v1.6.1-stable-021c3c28/windows-amd64/go1.8.1
INFO [05-30|22:02:24] Allocated cache and file handles         database=C:\\Users\\Spencer\\AppData\\Roaming\\Ethereum\\geth\\chaindata cache=128 handles=1024

(at this point nothing else happens, I've tried running it for upwards of 20 minutes and still nothing comes up) 
#### Steps to reproduce the behaviour
Open cmd
cd to geth path
run geth
(I don't know why this is happening)

#### Backtrace

````
[backtrace]
````

**Comment by rootk1d** [comment]
I have the very same problem. Did you figure out a work around yet?
