### ISSUE TITLE
corruption on data-block on Ubuntu

### ISSUE THREAD

**Issue by paralaks** [ethereum/go-ethereum#14555]
After geth running for about 8 hours and creating files up to 11 GB stopped with error
```
CRIT [05-31|00:00:34] Failed to store number to hash mapping   err="leveldb/table: corruption on data-block (pos=1608386): checksum mismatch, want=0x4cd36cbe got=0x93a05594 [file=169132.ldb]"
geth --syncmode=fast
```
**Ubuntu 16.04, geth 1.6.1-stable-021c3c28:**

**Comment by karalabe** [comment]
Are you sure you didn't run out of disk space? I'd also suggest checking your disk for bad sectors. We've been running more or less the same leveldb codebase forever and corruption always turned out to be caused by a machine crash or power outage until now.

**Comment by paralaks** [comment]
There is more than 300 GB free space. I left the laptop on all night. Ethereum-wallet GUI progress had stopped. Running geth resulted in the same error. Geth version was upgraded with this morning's update. I am running 1.6.2-stable-65979770 now. If it happens again I will check the disk against bad sectors .

**Comment by paralaks** [comment]
Ran badblocks on the partition; no errors were reported.
```
$ sudo badblocks -svn /dev/sdb6 > badblocks-sdb6.txt
.......
Checking for bad blocks in non-destructive read-write mode
From block 0 to 558319615
Checking for bad blocks (non-destructive read-write test)
Testing with random pattern:          done                                                 
Pass completed, 0 bad blocks found. (0/0/0 errors)
```

After about wasted 90 minutes and 8.2 GB download it failed again.

```
CRIT [05-31|23:18:02] Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=1038031): checksum mismatch, want=0xc349b78e got=0x7397866b [file=055429.ldb]"
```

**Comment by derlunz** [comment]
I can confirm this issue on a `Ubuntu 16.04` machine. There I was never able to sync at all.

```
CRIT [07-10|08:10:28] Failed to store number to hash mapping   err="leveldb/table: corruption on data-block (pos=1539325): checksum mismatch, want=0x113ff013 got=0x8f3b6f73 [file=002576.ldb]"
```
I used:
`Geth/v1.6.7-unstable-65f0e905/linux-amd64/go1.8.1` as well as the etherium gui wallet from `LP-PPA-ethereum-ethereum`, which currently uses `Geth/v1.6.6-stable-10a45cb5/linux-amd64/go1.8.3`

**Comment by ByCnck** [comment]
```
WARN [07-17|15:57:06] No etherbase set and no accounts found as default 
INFO [07-17|15:57:06] Starting peer-to-peer node               instance=Geth/v1.6.7-stable-ab5646c5/linux-amd64/go1.8.3
INFO [07-17|15:57:06] Allocated cache and file handles         database=/home/clark/.ethereum/geth/chaindata cache=128 handles=1024
INFO [07-17|15:57:06] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Metropolis: 9223372036854775807 Engine: ethash}"
INFO [07-17|15:57:06] Disk storage enabled for ethash caches   dir=/home/clark/.ethereum/geth/ethash count=3
INFO [07-17|15:57:06] Disk storage enabled for ethash DAGs     dir=/home/clark/.ethash               count=2
INFO [07-17|15:57:06] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [07-17|15:57:06] Loaded most recent local header          number=3917298 hash=b3513c…94c807 td=387746483184405745252
INFO [07-17|15:57:06] Loaded most recent local full block      number=0       hash=d4e567…cb8fa3 td=17179869184
INFO [07-17|15:57:06] Loaded most recent local fast block      number=3885209 hash=ada6be…209ab0 td=361439084828489758909
INFO [07-17|15:57:06] Starting P2P networking 
INFO [07-17|15:57:08] UDP listener up                          self=enode://e0fd5a42fec267723ef5169f47f84ec2eef532809dea28250887b574e0d641b4611579e0a2ecedaa98308facc3e72b76e74d736c37608d0a5f178edf9d9d5912@[::]:30303
INFO [07-17|15:57:08] RLPx listener up                         self=enode://e0fd5a42fec267723ef5169f47f84ec2eef532809dea28250887b574e0d641b4611579e0a2ecedaa98308facc3e72b76e74d736c37608d0a5f178edf9d9d5912@[::]:30303
INFO [07-17|15:57:08] IPC endpoint opened: /home/clark/.ethereum/geth.ipc 
INFO [07-17|15:57:38] Block synchronisation started 
WARN [07-17|15:57:44] Synchronisation failed, retrying         err="block download canceled (requested)"
INFO [07-17|15:58:02] Imported new state entries               count=1 flushed=0 elapsed=23.234ms processed=1 pending=17 retry=0 duplicate=0 unexpected=0
INFO [07-17|15:58:03] Imported new state entries               count=2 flushed=0 elapsed=45.583ms processed=3 pending=49 retry=0 duplicate=0 unexpected=0
INFO [07-17|15:58:03] Imported new block headers               count=0 elapsed=5.371ms  number=3885401 hash=92b6d1…c40dad ignored=192
CRIT [07-17|15:58:03] Failed to store block body               err="leveldb/table: corruption on data-block (pos=1600386): checksum mismatch, want=0xd4ea25a3 got=0x2910405 [file=132322.ldb]"
```

**Comment by andrewbernard** [comment]
Exact same issue. Ubuntu 16.04.3 LTS.

 New Seagate 2TB disk. 1.8 TB disk free. Occurs after about 24 GB downloaded.

`CRIT [09-18|09:39:19] Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=1833730): checksum mismatch, want=0x2b4c2838 got=0x314d7b72 [file=231138.ldb]"`

**Comment by arbach** [comment]
Same here, on both ropsten and main. Ubuntu 16.04 LTS. Let me know if I can post any debug info to help resolve.

**Comment by arbach** [comment]
Same on ubuntu 16.04 LTS

geth    1.7.0-stable-6c6c7b2a

**Comment by bdrehmer** [comment]
4.10.0-33-generic #37~16.04.1-Ubuntu

VERSION:
   1.7.0-stable-6c6c7b2a

CRIT [09-28|22:08:16] Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=14136320): checksum mismatch, want=0x7f8aa0 got=0xc88d3db1 [file=24804752.ldb]"

**Comment by mjpromotions** [comment]
same on opensuse leap 42.3, didnt have this issues before. More than enough disk space available.
Running Eth Wallet 0.9.1
Geth 1.7.1 Stable


`Failed to store header                   err="leveldb/table: corruption on data-block (pos=752625): checksum mismatch, want=0x24fa0185 got=0x5fc73c91 [file=003436.ldb]"`

**Comment by bobbieltd** [comment]
instance: Geth/v1.8.1-stable-1e67410e/linux-amd64/go1.9.4
Ubuntu 16.04

With 4 tries, 3 got this issue and stoped. One is successful.

**Comment by Rhnr** [comment]
Please help, I have the same issue: 
OS: Windows 10
Instance=**Geth/v1.8.1-stable-1e67410e/windows-amd64/go1.9.2**

ERROR[03-03|11:40:46] Section commit failed                    type=bloombits error="leveldb/table: corruption on data-block (pos=5546786): checksum mismatch, want=0xdb03ac4 got=0xcfa466e9 [file=026207.ldb]"
ERROR[03-03|11:40:46] Section processing failed                type=bloombits error="leveldb/table: corruption on data-block (pos=5546786): checksum mismatch, want=0xdb03ac4 got=0xcfa466e9 [file=026207.ldb]"
INFO [03-03|11:41:16] Block synchronisation started
INFO [03-03|11:41:17] Imported new block headers               count=0 elapsed=3.049ms number=2787129 hash=bd6aa8…0d5aa1 ignored=192
CRIT [03-03|11:41:17] Failed to store last fast block's hash   err="leveldb/table: corruption on data-block (pos=5546786): checksum mismatch, want=0xdb03ac4 got=0xcfa466e9 [file=026207.ldb]"

**Comment by emocanu** [comment]
It happens on my computer too:

INFO [03-15|22:44:41] Imported new chain segment               blocks=20   txs=71   mgas=3.382   elapsed=13.147s   mgasps=0.257  number=2435044 hash=86edbf…484cf1 cache=232.21mB
INFO [03-15|22:44:51] Imported new chain segment               blocks=30   txs=97   mgas=3.400   elapsed=10.168s   mgasps=0.334  number=2435074 hash=4506a9…a3227e cache=236.10mB
INFO [03-15|22:44:59] Imported new chain segment               blocks=110  txs=850  mgas=26.902  elapsed=8.000s    mgasps=3.363  number=2435184 hash=8b0949…2e3f23 cache=193.26mB
WARN [03-15|22:45:02] Synchronisation failed, dropping peer    peer=c40379e2f6349d85 err="retrieved hash chain is invalid"
CRIT [03-15|22:45:03] Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=739039): checksum mismatch, want=0xc2b6834b got=0xc7ddc64b [file=560337.ldb]"

Version=1.8.2, OS=Windows 7

If I delete the file 560337.ldb and restart syncing, nothing seems to happend.
Shall I restart syncing from 0?

**Comment by HuangJi** [comment]
Same issue here on Ubuntu 16.04 LTS
instance=Geth/v1.8.10-stable/linux-amd64/go1.9.2

CRIT [06-12|07:20:22] Failed to store last header's hash       err="leveldb/table: corruption on data-block (pos=1079823): checksum mismatch, want=0xaf49877c got=0x487799f1 [file=242636.ldb]"

**Comment by adamschmideg** [comment]
I take the issue is resolved, it seems to have been caused by a disk issue. If the problem persists, please open a new issue with the details.

**Comment by SeraphZA** [comment]
Hi there,

Ubuntu 16.04.6 LTS running Geth "geth-linux-amd64-1.9.15". I have a 512GB SSD formatted in F2FS dedicated to the block store and it fails with the following: "Failed to write block data to ancient store err="the append operation is out-order" after ~12h and 48GB downloaded. This is now the 4th time I have tried to sync the chain. Can anyone advise?

**Comment by lemtree** [comment]
Same issue on Ubuntu 16.04.6 LTS, running geth after 20 hours

INFO [07-30|15:51:21.441] Imported new block headers               count=0    elapsed=21.047ms  number=5761097 hash=13ab83…b9c653 age=2y2mo1d  ignored=384
WARN [07-30|15:51:21.537] Header broke chain ancestry              peer=89ede42ff91757d5 number=5761126 hash=a22bac…cc1d7a
CRIT [07-30|15:51:23.516] Failed to write block data to ancient store err="the append operation is out-order"
