### ISSUE TITLE
Is there still a GPU miner branch? / broken link from Ethereum.org

### ISSUE THREAD

**Issue by JoeArizona** [ethereum/go-ethereum#14550]
Ethereum.org purports to link to a "GPU MIner branch" of Geth. That link is broken, and I don't see any mention of a GPU branch in the main Readme.

The link is on this page: https://www.ethereum.org/ether

(The link is in the **GPU MINING USING THE COMMAND LINE** section, specifically in the **Instructions for Geth** subsection.)

The (broken) link address is: https://github.com/ethereum/go-ethereum/tree/gpu_miner

**Comment by karalabe** [comment]
No, we've removed GPU mining from Geth. https://github.com/ethereum-mining/ethminer seems to be a currently maintained mining project and there's no need to duplicate all the GPU effort from them. Dropping support for us means we can remove a lot of ugly boilerplace and dependencies.
