### ISSUE TITLE
make geth error

### ISSUE THREAD

**Issue by BorilloB** [ethereum/go-ethereum#14560]
#### System information

Geth version: `1.6.2`
OS & Version: Linux Ubuntu 14.04.5 LTS

Hello.
When try to  make geth take error
build/env.sh go run build/ci.go install ./cmd/geth
internal/build/azure.go:23:2: cannot find package "github.com/Azure/azure-storage-go" in any of:
	/usr/lib/go/src/github.com/Azure/azure-storage-go (from $GOROOT)
	/disk/123/go-ethereum-1.6.1/build/_workspace/src/github.com/Azure/azure-storage-go (from $GOPATH)
internal/build/pgp.go:27:2: cannot find package "golang.org/x/crypto/openpgp" in any of:
	/usr/lib/go/src/golang.org/x/crypto/openpgp (from $GOROOT)
	/disk/123/go-ethereum-1.6.1/build/_workspace/src/golang.org/x/crypto/openpgp (from $GOPATH)
make: *** [geth] Error 1

**Comment by karalabe** [comment]
You can build geth either via Go:

```
go install ./cmd/geth
```

Or if you don't have a Go development environment set up and configured via make:

```
make geth
```

**Comment by BorilloB** [comment]
Fixed by upgrade go from 1.5(default in system repository) to 1.8.3.

**Comment by amitchhajer** [comment]
Thanks, upgrading go worked for me too

**Comment by wolfen351** [comment]
this worked for me too - i used this guide on ubuntu:

https://askubuntu.com/questions/720260/updating-golang-on-ubuntu#755392

**Comment by NextZeus** [comment]
centos6.7 go@1.9.2 not work!

**Comment by Ajaysethi136** [comment]
I'm using go 1.9.2 version but getting the following error in Windows 10
build/env.sh go run build/ci.go install
ln: failed to create symbolic link 'go-ethereum/.': File exists
make: *** [Makefile:25: all] Error 1
Can someone plz help.

**Comment by knoxcard** [comment]
go-ethereum$ sudo make geth
[sudo] password for justin:
build/env.sh go run build/ci.go install ./cmd/geth
build/env.sh: 30: exec: go: not found
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 127

**Comment by karalabe** [comment]
@knoxcard You need Go, to build geth.

**Comment by KingsonSingh** [comment]
After running command make geth I am getting this error--
build/env.sh go run build/ci.go install ./cmd/geth
internal/build/azure.go:20:2: cannot find package "context" in any of:
	/home/vaibhav/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/context (vendor tree)
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/vaibhav/go-ethereum/build/_workspace/src/context (from $GOPATH)
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 1

**Comment by ankitagrawal-tech** [comment]
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 1

i am getting this error even though i am using go version 1.14

**Comment by isti4github** [comment]
> @knoxcard You need Go, to build geth.

But why you do not give his how to install go?
