### ISSUE TITLE
registrar owner get names

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1456]
An account can register a name `registrar.setAddress.sendTransaction (name, address, true, {from: primary})` and `registrar.owner(name)` will show the owner's account.

Is there a way an owner can query for the names they have registered?
Something like `registrar.names()` will return the names registered by the user's (default) account ?

(Related, is if there will be a general way to query the names for any account)

**Comment by zelig** [comment]
`regisrtar.addr(name)`

**Comment by ethers** [comment]
To clarify, this issue about if an owner has registered several names, has forgotten some of them, and would like to retrieve them.

`registrar.addr(name)` assumes the owner remembers all the names (the exact strings) they have registered.  In this case, it would be helpful if there's something like `registrar.names()` and a sample output would be `["zelig", "zeligDonation", "zeligContracts"]`

Another example, suppose that one of a dapp developer's account is known, and we would like to query the registrar for possible contracts/dapps/names they've developed.  It would be helpful if there's something like `registrar.names(address)` and a sample output would be `["coolContract", "gameContract", "engineContract" ]`
