### ISSUE TITLE
coudent connect to nod

### ISSUE THREAD

**Issue by stal13** [ethereum/go-ethereum#14572]
#### System information
win7 32
Geth version: `geth version` 1.6.5
OS & Version: Windows/Linux/OSX win 7
Commit hash : (if `develop`)

#### Expected behaviour
hello not sure if this is the right but  cant open my wallet getting this error message.
thanks 

#### Backtrace

````
[backtrace]
````
![untitled](https://cloud.githubusercontent.com/assets/29136358/26709445/23c6496a-4796-11e7-8c9a-3a1fb53d4eed.jpg)

**Comment by karalabe** [comment]
Ping @frozeman @luclu . The above log is perfectly fine, I'm guessing starting Geth takes a bit of time (it may do some database cleanups during startup) and Mist thinks it's not responding.

**Comment by stal13** [comment]
thanks but its still not opening the wallet, it just stuck.i left for few ours but no progress
