### ISSUE TITLE
Eth CLassic Node keeps dropping peer

### ISSUE THREAD

**Issue by jaybrown47** [ethereum/go-ethereum#14579]
#### System information

Geth version: `3.5.0`
OS & Version: Windows 10
Commit hash : (if `develop`)

#### Expected behaviour
Loading node ready for mining

#### Actual behaviour
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd/

C:\>cd/etc

C:\ETC>geth.exe
I0604 20:28:36.990041 cmd/geth/flag.go:649] --------------------------------------------------------------------------------------------------------------
I0604 20:28:36.993044 cmd/geth/flag.go:651] Starting Geth Classic v3.5.0
I0604 20:28:36.995046 cmd/geth/flag.go:652] Geth is configured to use blockchain: Ethereum Classic Mainnet (ETC)
I0604 20:28:36.996047 cmd/geth/flag.go:653] Using chain database at: C:\Users\miner\AppData\Roaming\EthereumClassic\mainnet/chaindata
I0604 20:28:36.997048 cmd/geth/flag.go:655] 4 blockchain upgrades associated with this configuration:
I0604 20:28:36.999050 cmd/geth/flag.go:658]  1150000 Homestead
I0604 20:28:37.000052 cmd/geth/flag.go:658]  1920000 The DAO Hard Fork
I0604 20:28:37.001053 cmd/geth/flag.go:660]          with block 0x94365e3a8c0b35089c1d1195081fe7489b528a84b22199c916180db8b28ade7f
I0604 20:28:37.004057 cmd/geth/flag.go:658]  2500000 GasReprice
I0604 20:28:37.005058 cmd/geth/flag.go:658]  3000000 Diehard
I0604 20:28:37.005058 cmd/geth/flag.go:670] --------------------------------------------------------------------------------------------------------------
I0604 20:28:37.008062 cmd/geth/flag.go:349] WARNING: No etherbase set and no accounts found as default
I0604 20:28:37.011071 ethdb/database.go:63] Allotted 128MB cache and 1024 file handles to C:\Users\miner\AppData\Roaming\EthereumClassic\mainnet\chaindata
I0604 20:28:37.653561 ethdb/database.go:63] Allotted 16MB cache and 16 file handles to C:\Users\miner\AppData\Roaming\EthereumClassic\mainnet\dapp
I0604 20:28:37.664575 eth/backend.go:155] Protocol Versions: [63 62], Network Id: 1, Chain Id: 61
I0604 20:28:37.851808 eth/backend.go:183] Blockchain DB Version: 3
I0604 20:28:37.853810 eth/backend.go:236] Successfully established mainnet genesis block: 0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
I0604 20:28:37.858817 core/blockchain.go:206] Last header: #2425010 [a6a25f3d…] TD=43580024526783277336
I0604 20:28:37.860818 core/blockchain.go:207] Last block: #2425010 [a6a25f3d…] TD=43580024526783277336
I0604 20:28:37.862821 core/blockchain.go:208] Fast block: #2425010 [a6a25f3d…] TD=43580024526783277336
I0604 20:28:37.866827 p2p/server.go:310] Starting Server
I0604 20:28:39.216643 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv2-IP1
I0604 20:28:39.361813 p2p/discover/udp.go:215] Listening, enode://687925d314bf64e6d1d7d39df6066043c38cba9211dfdde6bed34b0fa75668f7f3b97cf62f7e3304f54ac17b0c4a733c839ee372c4359e4e87dd15a04b61c068@94.173.133.127:30303
I0604 20:28:39.374830 p2p/server.go:553] Listening on [::]:30303
I0604 20:28:39.380848 node/node.go:295] IPC endpoint opened: \\.\pipe\geth.ipc
I0604 20:28:39.424018 node/node.go:365] HTTP endpoint opened: http://localhost:8545
I0604 20:28:39.441039 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv2-IP1
I0604 20:28:40.699997 eth/downloader/downloader.go:335] Block synchronisation started
I0604 20:28:45.316386 eth/handler.go:295] Peer e1b3aa7f35a4d63a [eth/63]: timed out fork-check, dropping
I0604 20:28:45.696442 eth/handler.go:295] Peer 8d2d3dc80954e147 [eth/63]: timed out fork-check, dropping
I0604 20:28:46.379998 eth/handler.go:295] Peer 25247652f2594d96 [eth/63]: timed out fork-check, dropping
I0604 20:28:46.527182 eth/handler.go:295] Peer eedc3254216e7908 [eth/63]: timed out fork-check, dropping
I0604 20:28:46.793515 eth/handler.go:295] Peer a5c131edaab1bdb7 [eth/63]: timed out fork-check, dropping
I0604 20:28:46.898645 eth/handler.go:295] Peer 8498abc352aabeb6 [eth/63]: timed out fork-check, dropping
I0604 20:28:47.510408 eth/handler.go:295] Peer 9eea062720bd5b21 [eth/63]: timed out fork-check, dropping
I0604 20:28:47.528432 eth/handler.go:295] Peer 082bd58f5c2401a6 [eth/63]: timed out fork-check, dropping
I0604 20:28:48.045873 eth/handler.go:295] Peer c90adc1a9a0f610b [eth/63]: timed out fork-check, dropping
I0604 20:28:49.291630 eth/handler.go:295] Peer 3f39c72003b5a322 [eth/63]: timed out fork-check, dropping
I0604 20:28:52.682419 eth/handler.go:295] Peer c8503e1cf35c81b5 [eth/63]: timed out fork-check, dropping
I0604 20:28:56.408548 eth/handler.go:295] Peer 3b1398a14b22d214 [eth/63]: timed out fork-check, dropping
I0604 20:28:56.814961 eth/handler.go:295] Peer 0bd6d5895ffc5e2e [eth/63]: timed out fork-check, dropping
I0604 20:29:01.601476 eth/handler.go:295] Peer cd642f0d41d5a155 [eth/63]: timed out fork-check, dropping
I0604 20:29:15.839138 eth/handler.go:295] Peer e598b89853b58dc9 [eth/63]: timed out fork-check, dropping
I0604 20:29:18.402461 eth/handler.go:295] Peer 082bd58f5c2401a6 [eth/63]: timed out fork-check, dropping
I0604 20:29:30.725178 eth/handler.go:295] Peer 9300c680072ecea9 [eth/63]: timed out fork-check, dropping
I0604 20:29:37.807395 eth/handler.go:295] Peer 8be44caddf9ec555 [eth/63]: timed out fork-check, dropping
I0604 20:29:40.262508 eth/handler.go:295] Peer 4de10dd6db13ae2c [eth/63]: timed out fork-check, dropping
I0604 20:29:42.385636 eth/handler.go:295] Peer ece49c5e1f42ee59 [eth/63]: timed out fork-check, dropping
I0604 20:29:42.490048 eth/handler.go:295] Peer 3f39c72003b5a322 [eth/63]: timed out fork-check, dropping
I0604 20:29:42.645934 eth/handler.go:295] Peer 7ea9a1328551e34a [eth/63]: timed out fork-check, dropping
I0604 20:29:46.538934 eth/handler.go:295] Peer 1eec494930d384b3 [eth/63]: timed out fork-check, dropping
I0604 20:29:47.015511 eth/handler.go:295] Peer 4f0617b9f49d77c1 [eth/63]: timed out fork-check, dropping
I0604 20:29:48.547903 eth/handler.go:295] Peer 7d25b82d03691db4 [eth/63]: timed out fork-check, dropping
I0604 20:29:49.945621 eth/handler.go:295] Peer cb64a034f79960e8 [eth/63]: timed out fork-check, dropping
I0604 20:29:51.948546 eth/handler.go:295] Peer 186f0097e9861e2a [eth/63]: timed out fork-check, dropping
I0604 20:29:52.393249 eth/handler.go:295] Peer 8ce8b2b7fc4279e0 [eth/63]: timed out fork-check, dropping
I0604 20:29:57.564962 eth/handler.go:295] Peer e7189cd7e1d6286e [eth/63]: timed out fork-check, dropping
I0604 20:29:58.447480 eth/handler.go:295] Peer b92cadff6c4c0313 [eth/63]: timed out fork-check, dropping
I0604 20:30:00.700910 eth/handler.go:295] Peer c8503e1cf35c81b5 [eth/63]: timed out fork-check, dropping
I0604 20:30:06.916926 eth/handler.go:295] Peer d0f1f19a9d641544 [eth/63]: timed out fork-check, dropping
I0604 20:30:18.697832 eth/handler.go:295] Peer 3efcfeec93f84472 [eth/63]: timed out fork-check, dropping
I0604 20:30:19.191155 eth/handler.go:295] Peer cee7a804a77d9ab6 [eth/63]: timed out fork-check, dropping
I0604 20:30:21.970049 eth/handler.go:295] Peer 11e5e60750f4b938 [eth/63]: timed out fork-check, dropping

#### Steps to reproduce the behaviour
cd/
cd/ETC
geth.exe

#### Backtrace

````
[backtrace]
````

**Comment by obscuren** [comment]
Sorry. We do not support the `ETC` chain. Please open an issue at their repo.
