### ISSUE TITLE
How can I connect Geth to an other node and to an other blockchain ? 

### ISSUE THREAD

**Issue by Nogreedy** [ethereum/go-ethereum#14576]
#### System information

Geth version: 1.6.1
OS & Version: OS & Version: windows 10 (64 bits)   - Linux Mint 18.1 (Xfce - 64 bits)

_______________________________________________________________________

Hello,
I use Geth (with Mist 0.8.10) .... and I appreciate it so much...
I use Geth on my Windows 10 PC (192.168.0.1) and it works very well (blockchain OK and synced)...
but now I have a new Linux PC on my local network (192.168.0.2)... and I'd like to use Geth/Mist also on this new PC (to use MultiSig...) ... but this new PC has a slow HDD and I can't download blockchain on this new PC.
Is there a concrete way to connect this Linux PC to my Windows 10 PC (192.168.0.1) to use only one blockchain (node?) ?
What is the correct CLI command and options (rpc or ipc options???) to use to connect to an other blockchain?
Thanks in advance for your answer.

**Comment by obscuren** [comment]
No, unfortunately there isn't any way to connect one computer to the way you're describing.

Have you tried using the light client on your "slow" machine? You can invoke it with `geth --light --v5disc`.

**Comment by Nogreedy** [comment]
Thanks for your answer. 
I'll try light option as you wrote
