### ISSUE TITLE
fatal error: out of memory

### ISSUE THREAD

**Issue by grankko** [ethereum/go-ethereum#14577]
#### System information

core i5 7600K @ 4.3GHz
16 gb DDR4 @ 2666MHz

Geth version: whatever came bundled with Mist as of 2017-06-01
OS & Version: Windows 10
Commit hash : (if `develop`)

#### Expected behaviour
successful blockchain sync

#### Actual behaviour
memory leak => fatal error: out of memory

#### Steps to reproduce the behaviour

ran geth --fast
same with geth --fast --cache=1024

#### Backtrace

````
[backtrace]
````

[stacktrace](https://gist.github.com/obscuren/f1604ce0557d92510e77ae8e787d9e21)

**Comment by karalabe** [comment]
I think Mist only recently updated to Geth 1.6.5 which fixed the OOM attack from mainnet. Please update and try again.

**Comment by aribornstein** [comment]
I'm running the latest version and having the same issue

**Comment by karalabe** [comment]
@arboreum Please open a new issue and please add logs. There's no information content in your report that would help us diagnose what's happening.
