### ISSUE TITLE
Geth is taking way too long to sync on a mechanical hdd 

### ISSUE THREAD

**Issue by Pac23** [ethereum/go-ethereum#14575]
#### System information

Geth version: `geth version 1.6.4
OS & Version: Windows 7 64 bit Sp1
Commit hash : (if `develop`)

#### Expected behaviour
Full blockchain sync within 24 hours on a 100/100 connection with --fast --cache=2024

#### Actual behaviour
Not yet sync'd after 36 hours.

````

**Comment by Qxiombarg** [comment]
Having similar issues on a Linux system. 

Performance degrades exponentially. Same thing happens if I attempt to import data exported from another system with a synched blockchain.

**Comment by remyroy** [comment]
I believe this is a known issue (#14433). It is actively being worked on with #14460.

**Comment by destinatis** [comment]
Replace magnetic with SSD, problem solved.

**Comment by wtfiwtz** [comment]
Check out this thread: https://github.com/ethereum/go-ethereum/issues/15001
