### ISSUE TITLE
Presale Wallet - Fatal: could not decrypt key with given passphrase

### ISSUE THREAD

**Issue by Qxiombarg** [ethereum/go-ethereum#14574]
I've confirmed my password is correct with pyethrecover. 

I've also tried putting the password in a file and using the --password flag, pasting from clipboard, etc...

#### System information

Geth version: 1.6.5-stable
OS & Version: OSX
Commit hash : (if `develop`)

**Comment by austinmckale** [comment]
Did you ever figure out how to access the wallet ? or what was throwing the error?

**Comment by onepremise** [comment]
Interested as well, I'm still unable to import my presale wallet.

**Comment by 401825317** [comment]
创世块的密码是什么？我好想没有设置。而且我得账号中自动生成了很多账号是怎么回事？生产环境

**Comment by illdeletethis** [comment]
this issue still exists, i am unable to access a presale wallet that i had used years ago

**Comment by DanielsBerlin** [comment]
I had exactly similar problem I but managed to solve it and access my presale ETH
