### ISSUE TITLE
SIGSEGV (segmentation violation) when running geth

### ISSUE THREAD

**Issue by silentsnooc** [ethereum/go-ethereum#14585]
#### System information

Geth version: `1.6.6` (from git Repository - latest hash: 1e9f86b49e523b9e0867abf1499de8fca4c7cd8d)
OS & Version: Linux (Ubuntu)

#### Expected behaviour
Don't crash.

#### Actual behaviour
Crashes sometimes with segfault. The output is much too long so I pasted it here: https://pastebin.com/f1s9akbv

#### Steps to reproduce the behaviour
I can't tell. I setup go-ethereum as explained, created an account and started geth. 

#### Backtrace

See: https://pastebin.com/f1s9akbv

**Comment by theblueskies** [comment]
https://github.com/ethereum/go-ethereum/issues/14552

**Comment by mattrixman** [comment]
I can reliably reproduce this (or something quite similar) without mining.  I just run `geth` and within a half hour it has crashed.  Would additional stack traces be useful?  Should I consider my issue a duplicate as well or open a new one?

**Comment by adamschmideg** [comment]
@mattrixman , @silentsnooc please follow #14552. If you think this is a different issue, please reopen it and describe the differences.
