### ISSUE TITLE
Documentation request: keystore v3 decryption procedure

### ISSUE THREAD

**Issue by eugene-babichenko** [ethereum/go-ethereum#14588]
Hi everyone!

I'd like to see a description of keystore v3 decryption procedure just like it's already done for [v1](https://github.com/ethereum/go-ethereum/wiki/Passphrase-protected-key-store-spec).

**Comment by fjl** [comment]
It's documented here: https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

**Comment by fjl** [comment]
Do you need more details?

**Comment by eugene-babichenko** [comment]
Thank you! I just searched in go-ethereum wiki instead of ethereum.
