### ISSUE TITLE
'fatal error: out of memory' when attempting to sync

### ISSUE THREAD

**Issue by albinowax** [ethereum/go-ethereum#14590]
When trying to sync, geth crashes with 'fatal error: out of memory'. My system has 32gb RAM so this seems pretty strange, and I've replicated it about 5 times. I'm using the following commands:
geth.exe removedb
geth.exe --fast

Please let me know if there's any other information I could provide that would be helpful.

System information

Version: 1.6.5-stable-cf87713d
OS & Version: windows 10

Stack trace:

INFO [06-06|20:21:43] Imported new state entries count=4 elapsed=993.6µs processed=2965170 pending=66944
fatal error: out of memory

runtime stack:
attached
[stracktrace.txt](https://github.com/ethereum/go-ethereum/files/1194297/stracktrace.txt)

**Comment by VFLashM** [comment]
Getting the same (or similar) on Geth/v1.6.5-stable-cf87713d/windows-386/go1.8.3

Windows 10.

```
INFO [06-06|21:11:28] Imported new state entries               count=384  elapsed=23.061ms  processed=148652 pending=52643
INFO [06-06|21:11:29] Imported new state entries               count=384  elapsed=118.342ms processed=149036 pending=53068
INFO [06-06|21:11:29] Imported new state entries               count=384  elapsed=66.182ms  processed=149420 pending=53588
runtime: out of memory: cannot allocate 9109504-byte block (1063845888 in use)
fatal error: out of memory
```
[stack.txt](https://github.com/ethereum/go-ethereum/files/1056684/stack.txt)

**Comment by z3v3** [comment]
Same here (tested on stable and daily builds):
geth-windows-386-1.6.5-cf87713d
geth-windows-386-1.6.6-unstable-1e9f86b4

Win 10
16 GB RAM

[geth-oom.txt](https://github.com/ethereum/go-ethereum/files/1056820/geth-oom.txt)
[geth-oom-unstable.txt](https://github.com/ethereum/go-ethereum/files/1056821/geth-oom-unstable.txt)

**Comment by karthiknvlr** [comment]
While doing sync check whether another process in your computer consumes memory, If so end that process and restart the sync again using --fast command and cache as 1024

**Comment by VFLashM** [comment]
Manually launching x64 version of geth helped.

**Comment by VFLashM** [comment]
Speaking of, using 64-bit version of ethereum wallet after 32-bit one does not help (without user dir wipe). It seems that it caches 32-bit geth and continue to use that.

**Comment by wrmc319** [comment]
I'm running Ubuntu on an AWS platform with lots of memory and a good connection and getting this error consistently anytime I try to bring down the chain. Will try building geth myself but this is definitely annoying.

**Comment by agix** [comment]
Same problem here... I spent three weeks with a t2.medium aws instance and still no way to sync the whole blockchain in fast mode... Out of memory starts after ~3 700 000 block...

**Comment by Inigovd** [comment]
Same problem on Ubuntu DigitalOcean node with 4gb RAM. Running with --cache=1024. Constantly out of memory. Trying to build a payment application with geth but keeps crashing. Very annoying

**Comment by da-kami** [comment]
Same issue here on AWS t2.medium, ubunut 16.04. For me the problem occurs when the state is being built during fast-sync.

**Comment by ttaranov** [comment]
same here: linux-386-1.7.2 (amazon linux, m4.large instance on AWS) with geth --fast --cache=1024

runtime stack:
runtime.throw(0x8959056, 0xd)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/panic.go:605 +0x7c
runtime.largeAlloc(0x10000000, 0xf74f0101, 0x809ae59)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/malloc.go:829 +0xe0
runtime.mallocgc.func1()
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/malloc.go:722 +0x39
runtime.systemstack(0x19f22000)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/asm_386.s:393 +0x5e
runtime.mstart()
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/proc.go:1125

goroutine 61149 [running]:
runtime.systemstack_switch()
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/asm_386.s:347 fp=0x1e94d448 sp=0x1e94d444 pc=0x809d4d0
runtime.mallocgc(0x10000000, 0x884c060, 0x1, 0x6606f960)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/malloc.go:721 +0x67e fp=0x1e94d49c sp=0x1e94d448 pc=0x805b9ae
runtime.makeslice(0x884c060, 0x0, 0x10000000, 0xf549c000, 0x448bc000, 0x4c3a0a01)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/slice.go:54 +0x59 fp=0x1e94d4b0 sp=0x1e94d49c pc=0x808a0a9
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/memdb.New(0x8f74de0, 0x1a2d8bd0, 0x10000000, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/memdb/memdb.go:470 +0xd4 fp=0x1e94d4fc sp=0x1e94d4b0 pc=0x8330ec4
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolGet(0x1a0fe700, 0x226f8, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:90 +0x96 fp=0x1e94d51c sp=0x1e94d4fc pc=0x8354176
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).newMem(0x1a0fe700, 0x226f8, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:147 +0x1bb fp=0x1e94d578 sp=0x1e94d51c pc=0x83545eb
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).rotateMem(0x1a0fe700, 0x226f8, 0x0, 0x1e94d668, 0x186, 0xf9c2fddb)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_write.go:45 +0x6a fp=0x1e94d5a0 sp=0x1e94d578 pc=0x83573da
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).flush.func1(0xeb2e8d00)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_write.go:101 +0x218 fp=0x1e94d5ec sp=0x1e94d5a0 pc=0x8369428

**Comment by AndrewRandall** [comment]
Same here on fully synced blockchain.  Ubuntu 16.04.3 LTS 3GB.

`sudo nohup geth &
`

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xf536e6, 0x16)
	/usr/lib/go-1.9/src/runtime/panic.go:605 +0x95
runtime.sysMap(0xc49f990000, 0x100000, 0xffffffffebd4c000, 0x1935858)
	/usr/lib/go-1.9/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x191bfc0, 0x100000, 0xffffffff00089ab0)
	/usr/lib/go-1.9/src/runtime/malloc.go:470 +0xd7
runtime.(*mheap).grow(0x191bfc0, 0x1, 0x0)
	/usr/lib/go-1.9/src/runtime/mheap.go:887 +0x60
runtime.(*mheap).allocSpanLocked(0x191bfc0, 0x1, 0x1935868, 0x1002029f0)
	/usr/lib/go-1.9/src/runtime/mheap.go:800 +0x334
runtime.(*mheap).alloc_m(0x191bfc0, 0x1, 0x20000000f, 0x1)
	/usr/lib/go-1.9/src/runtime/mheap.go:666 +0x118
runtime.(*mheap).alloc.func1()
	/usr/lib/go-1.9/src/runtime/mheap.go:733 +0x4d
runtime.systemstack(0x7f577c3f8da0)
	/usr/lib/go-1.9/src/runtime/asm_amd64.s:360 +0xab
runtime.(*mheap).alloc(0x191bfc0, 0x1, 0x7f57a801000f, 0x100000000000030)
	/usr/lib/go-1.9/src/runtime/mheap.go:732 +0xa1
runtime.(*mcentral).grow(0x191d6d0, 0x0)
	/usr/lib/go-1.9/src/runtime/mcentral.go:232 +0x94
runtime.(*mcentral).cacheSpan(0x191d6d0, 0x42a967)
	/usr/lib/go-1.9/src/runtime/mcentral.go:106 +0x33a
runtime.(*mcache).refill(0x7f57aafaa000, 0x45dc0f, 0xc49f966500)
	/usr/lib/go-1.9/src/runtime/mcache.go:123 +0xa4
runtime.(*mcache).nextFree.func1()
	/usr/lib/go-1.9/src/runtime/malloc.go:557 +0x32
runtime.systemstack(0xc42001c000)
	/usr/lib/go-1.9/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
	/usr/lib/go-1.9/src/runtime/proc.go:1125

**Comment by ttaranov** [comment]
btw, I fixed my issue by using 64-bit geth distribution and using defaults with launching geth (not using --fast or --cache). I think --cache is the one that causes OOM issues though.

**Comment by scvsh** [comment]
Same here, Scaleway x86-64 Ubuntu Xenial, running with geth console --fast, installed via apt-get.
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xf536e6, 0x16)
	/usr/lib/go-1.9/src/runtime/panic.go:605 +0x95
runtime.sysMap(0xc4fb140000, 0x2000000, 0x2f82f214a4c93f00, 0x1935858)
	/usr/lib/go-1.9/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x191bfc0, 0x2000000, 0x7fd8eb29a178)
	/usr/lib/go-1.9/src/runtime/malloc.go:470 +0xd7
```

**Comment by zzd1990421** [comment]
2 restarts everyday

my command:
geth --datadir /data/geth-data-dir --maxpeers 100 --maxpendpeers 100 --cache 8192 --rpc --rpcapi "admin,eth,personal,net" --rpcaddr "11.255.6.159"

os:
amazon ecs 4CORE 8GB RAM

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xf2284f, 0x16)
        /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc7cbdd0000, 0x10000000, 0x0, 0x1b16438)
        /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x1afcae0, 0x10000000, 0x0)
        /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x1afcae0, 0x8000, 0x0)
        /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x1afcae0, 0x8000, 0x1b16448, 0xc42734f200)
        /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x1afcae0, 0x8000, 0x7f9a06b50101, 0x43913a)
        /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
        /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x1afcae0, 0x8000, 0x7f9a0c010101, 0x7f9a06b5ae70)
        /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x10000000, 0x7f9a06b50101, 0x46ab2e)
        /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
        /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
        /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
        /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/proc.go:1175

**Comment by holiman** [comment]
I'm going to close this. It seems that there are three usual causes, 

- Very old versions, more than a year old .
- Using `--cache 8192` on an `8G` system. That's really playing with fire, since geth will at least consume `--cache` amount of RAM, but actually a bit more
- Exposing `personal` over rpc, on public address. That will lead to attackers trying to bruteforce accounts.
