### ISSUE TITLE
Invalid transaction v,r,s values with geth when reading from of signed MEW RLP transaction

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#14599]
#### System information

Geth version: 1.6.5
OS & Version: Android

#### Expected behaviour

Should be able to read the from field and not throw "Invalid transaction v,r,s values"

#### Actual behaviour

throws "Invalid transaction v,r,s values" when reading from field

#### Steps to reproduce the behaviour

1) generate a signed transaction RLP with MEW ( e.g. 0xf86b80847735940082520894ef5bbb9bba2e1ca69ef81b23a8727d889f3ef0a1880de0b6b3a7640000802ba06fef16c44726a102e6d55a651740636ef8aec6df3ebf009e7b0c1f29e4ac114aa057e7fbc69760b522a78bb568cfc37a58bfdcf6ea86cb8f9b550263f58074b9cc )
2) convert to geth transaction via Geth.newTransactionFromRLP(hex)
3) try to access the from field ( will throw "Invalid transaction v,r,s values")

I can successfully read fields like `value` or `to` 
When generating the RLP with geth like this:

`Geth.newTransactionFromRLP(transactionWithSignature.encodeRLP())`

I can access the `from` field.

Hint from Péter Szilágyi (@karalabe) on gitter: Hmmm, one bet is that the mobile library might be using homestead signatures and mew returning proper eip155

Also as a question on stackoverflow:
https://ethereum.stackexchange.com/questions/17385/invalid-transaction-v-r-s-values-with-geth-when-reading-from-of-signed-mew-rlp-t
Unfortunately it does not get any attention there and there is growing evidence that this is a problem with (the mobile API of) geth

**Comment by bas-vk** [comment]
Péters guess is correct. This method uses the hard coded homestead signer during decoding.
Will create a fix.

**Comment by ligi** [comment]
Thanks so much!
