### ISSUE TITLE
admin.importChain broken

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1459]
Geth
Version: 0.9.39
Git Commit: 5a810758dbe75dce9537d464ac0e5b5385b0e78f
Protocol Versions: [61 60]
Network Id: 0
Go Version: go1.4.2

I ran `admin.exportChain` (it returned true) and noted the `eth.blockNumber` call it N.  I then mined some blocks and noted the `eth.blockNumber` call it Q.  I ran `admin.importChain` it returned true but seems to not have done anything.

OBSERVED
`eth.blockNumber` returns Q.  Restarting geth doesn't help

EXPECTED
`eth.blockNumber` returns N

**Comment by obscuren** [comment]
Did you import while you still had your old chain? Import doesn't delete anything and will skip anything you already have.

**Comment by ethers** [comment]
yes I still had old chain.  So what I then did was moved the blockchain directory.  Running the import then gave invalid nonce:
```
> admin.importChain('/home/user/gethChain.dat')
invalid block 221: block 0 ([253 74 249 42 121 199 252 47 216 191 13 52 47 46 131 46 29 79 72 92 133 185 21 45 32 57 224 59 198 4 253 202]) nonce is invalid (got 42)
    at InvalidResponse (<anonymous>:-59655:-97)
    at send (<anonymous>:-117559:-97)
    at importChain (<anonymous>:-106295:-97)
    at <anonymous>:1:1
```

I stop geth, copy back the blockchain directory, and the chain seems fine.  So something not quite right with importChain?

**Comment by ethers** [comment]
> Import doesn't delete anything and will skip anything you already have.

I updated the wiki:
https://github.com/ethereum/go-ethereum/wiki/Go-ethereum-management-API's#admin_importchain

Please also fix the issue that importChain should return `false` if it does not succeed.
