### ISSUE TITLE
'geth account new' : passwords do not match issue...

### ISSUE THREAD

**Issue by SalvorinFex** [ethereum/go-ethereum#14591]
#### System information

Geth version: `geth version` 1.6.5
OS & Version: Windows 10 64bit Pro
Commit hash : (if `develop`)

#### Expected behavior
Create initial password

#### Actual behavior
Fatal: Passphrases do not match

#### Steps to reproduce the behavior
CMD> geth account new

#### Backtrace

````
[backtrace]
````

I have tried this several times with a password that I have used before, so I know I am typing it in correctly.

**Comment by karthiknvlr** [comment]
Try with both upper and lower case letters, if you still face the same issue you can use this python script to recover your password  [pyethrecover](https://github.com/burjorjee/pyethrecover).
Note -- In Ethereum there is no way to recover are reset your password once it was set !!
