### ISSUE TITLE
Transaction stuck in progress--Unable to locate Transaction entry

### ISSUE THREAD

**Issue by lyddream** [ethereum/go-ethereum#14595]
Please answer these questions before submitting your issue. Thanks!

#### I broadcast a raw Transaction : 0xf86c1f85055ae82600830186a09460d582003e286facaa5ccbc45c846b630593917587038d7ea4c680008025a0ef92fd3749ae12c5ea790781e5103fcbeef3e429e256d1073c2e7d5becd98651a057bc95563f8a23b66d9bada4b42ec022f7b4227f2fdbfaa3d1deb19f87541828
 I get the transaction hash:0xd43289ffaf827a57e7551d0c56cfe643861d674bdcd97a3269a40840edae0358.
Then I query the transaction using eth_getTransactionByHash 
#### System details
Version: 1.6.6-unstable
Go Version: go1.8.3
OS: darwin
uname -v: Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195

**Comment by bas-vk** [comment]
If you got a transaction hash it means the transaction was initially added to the tx pool. There are several reasons why a transaction is dropped from the pool before it is mined. To determine what is happening you can increate the log level. That should log the reason why a transaction is removed from the pool.

`geth --vmodule=core/*=6`

**Comment by karalabe** [comment]
Also `eth_getTransactionByHash` only returns transactions that have been added to the blockchain already. Those pending inclusion cannot be retrieved via this method. You may inspect the transaction pool's content via `txpool.inspect` or `txpool.content`. The former is human readable while the latter is a full data dump.
