### ISSUE TITLE
Light sync mode incompatible with ethminer - eth_submitHashrate does not exist

### ISSUE THREAD

**Issue by ekliptik** [ethereum/go-ethereum#14597]
#### System information

Geth version: 1.6.5
OS & Version: Windows 10 64-bit

#### Expected behaviour

Light mode syncs, ethminer connects and gets to work

#### Actual behaviour

Light mode syncs just fine, but ethminer claims that the eth_submitHashrate does not exist/is not available

Specifically: 

~~~~C:\Users\Your Mom>B:\Downloads\ethminer-0.9.41-genoil-1.0.5-cuda6.5\ethminer.exe -U > log.txt
miner  08:56:28|main  Getting work package...
  X  08:56:28|main  Failed to submit hashrate.
  X  08:56:28|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requested is not available on this server: The method eth_submitHashrate does not exist/is not available

JSON-RPC problem. Probably couldn't connect. Retrying in 1...
miner  08:56:30|main  Getting work package...
  X  08:56:30|main  Failed to submit hashrate.
  X  08:56:30|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requested is not available on this server: The method eth_submitHashrate does not exist/is not available
~~~~

#### Steps to reproduce the behaviour

Happens with any --light compatible version of geth and any version of ethminer, tested on 1.0.x and above

**Comment by DfreakD** [comment]
I have exactly the same problem, did you solve it yet?

**Comment by ekliptik** [comment]
No but I discovered Claymore's miner complains about the same thing when pointed at the local host

**Comment by DfreakD** [comment]
Ok so is there anything else we can try? I'm fairly new to this..

**Comment by ekliptik** [comment]
Probably not. Just use the standard sync modes

**Comment by karalabe** [comment]
A light client does not have the chain's state available locally, rather tries to request it on demand. This means however that mining is pointless, because every transaction you want to process would need to wait arbitrarily long to execute until the client downloads all the needed data to run it.

If you wish to mine, please run a full node (or use a mining pool if you do now wish to run your own node).

**Comment by stevea32** [comment]
so if you want to mine you have to sync the whole chain which never happens
