### ISSUE TITLE
Geth uses 233% of my CPU

### ISSUE THREAD

**Issue by mo0vjke** [ethereum/go-ethereum#14593]
Hi guys.

I'm wondering why my geth client is using so much CPU.

Intel  Xeon E3-1245v2, 32GB DDR3 1600 MHz, SSD, Ubuntu 16.04, Geth v1.6.5

Command line:
nohup ~/ethereum/geth --fast --rpc --rpcapi "db,eth,personal,txpool" --rpcaddr 127.0.0.1 --rpcport 7700 --cache 1024 &

Log file:
INFO [06-07|10:18:01] Imported new chain segment               blocks=1 txs=90  mgas=4.572 elapsed=554.977ms mgasps=8.238  number=3834184 hash=1424cf…fa40ec
INFO [06-07|10:18:06] Imported new chain segment               blocks=1 txs=49  mgas=4.596 elapsed=383.502ms mgasps=11.984 number=3834185 hash=0ff32d…2d2109
INFO [06-07|10:18:29] Imported new chain segment               blocks=1 txs=9   mgas=0.992 elapsed=215.166ms mgasps=4.608  number=3834186 hash=d76388…8b9d93
INFO [06-07|10:18:41] Imported new chain segment               blocks=1 txs=82  mgas=4.530 elapsed=740.437ms mgasps=6.118  number=3834187 hash=812e6f…9e053a
INFO [06-07|10:18:48] Imported new chain segment               blocks=1 txs=2   mgas=0.055 elapsed=11.500ms  mgasps=4.745  number=3834188 hash=de9883…2bbc98
INFO [06-07|10:18:55] Imported new chain segment               blocks=1 txs=36  mgas=1.319 elapsed=121.737ms mgasps=10.836 number=3834189 hash=4e9503…d77f94
INFO [06-07|10:19:16] Imported new chain segment               blocks=1 txs=0   mgas=0.000 elapsed=53.658ms  mgasps=0.000  number=3834190 hash=cc5de2…1d8b36
INFO [06-07|10:19:24] Imported new chain segment               blocks=1 txs=30  mgas=4.699 elapsed=202.917ms mgasps=23.159 number=3834191 hash=73c77b…1c3a03
INFO [06-07|10:20:01] Imported new chain segment               blocks=1 txs=0   mgas=0.000 elapsed=12.272ms  mgasps=0.000  number=3834192 hash=78efbc…5c95e2
INFO [06-07|10:20:05] Imported new chain segment               blocks=1 txs=14  mgas=0.316 elapsed=95.388ms  mgasps=3.311  number=3834193 hash=a67a9e…2935e1
INFO [06-07|10:20:11] Imported new chain segment               blocks=1 txs=39  mgas=4.665 elapsed=82.575ms  mgasps=56.499 number=3834194 hash=41640b…aa5a4d
INFO [06-07|10:20:29] Imported new chain segment               blocks=1 txs=86  mgas=4.623 elapsed=733.260ms mgasps=6.305  number=3834195 hash=fec1af…b6ae43
INFO [06-07|10:20:38] Imported new chain segment               blocks=1 txs=4   mgas=0.084 elapsed=16.099ms  mgasps=5.218  number=3834196 hash=077d5a…eff832
INFO [06-07|10:20:50] Imported new chain segment               blocks=1 txs=1   mgas=0.021 elapsed=7.245ms   mgasps=2.898  number=3834197 hash=da1fcd…d31912
INFO [06-07|10:21:04] Imported new chain segment               blocks=1 txs=10  mgas=0.210 elapsed=39.803ms  mgasps=5.276  number=3834198 hash=aabe64…2e4ffa
INFO [06-07|10:21:18] Imported new chain segment               blocks=1 txs=69  mgas=2.663 elapsed=231.233ms mgasps=11.516 number=3834199 hash=7ac39c…dc2003
INFO [06-07|10:21:21] Imported new chain segment               blocks=1 txs=0   mgas=0.000 elapsed=17.745ms  mgasps=0.000  number=3834200 hash=a831c8…cf0f24
INFO [06-07|10:21:21] Imported new chain segment               blocks=1 txs=21  mgas=0.653 elapsed=41.022ms  mgasps=15.927 number=3834200 hash=39f428…467759
INFO [06-07|10:21:34] Imported new chain segment               blocks=1 txs=1   mgas=0.021 elapsed=18.304ms  mgasps=1.147  number=3834201 hash=653109…fd1b59
INFO [06-07|10:21:35] Imported new chain segment               blocks=1 txs=51  mgas=2.683 elapsed=200.002ms mgasps=13.413 number=3834201 hash=c3319b…441a6c
INFO [06-07|10:21:57] Imported new chain segment               blocks=1 txs=0   mgas=0.000 elapsed=18.563ms  mgasps=0.000  number=3834202 hash=e012ec…3f0db1
INFO [06-07|10:22:30] Imported new chain segment               blocks=1 txs=4   mgas=0.103 elapsed=21.397ms  mgasps=4.791  number=3834203 hash=1bef51…291d2c
INFO [06-07|10:22:34] Imported new chain segment               blocks=1 txs=115 mgas=4.645 elapsed=508.978ms mgasps=9.127  number=3834204 hash=72bddd…f91b80
INFO [06-07|10:23:04] Imported new chain segment               blocks=1 txs=55  mgas=3.312 elapsed=296.279ms mgasps=11.179 number=3834205 hash=ff3126…dd5412

Anyone has the same as me?
Thanks in advance!

**Comment by ligi** [comment]
Yes - syncing the chain is CPU intensive - you might want to think about "--light"

**Comment by mo0vjke** [comment]
I need to resync wallet with light option? or just need to change --fast to --light??
I'm asking because after the changing --fast to --light it doesn't make any changes at CPU load.

**Comment by mo0vjke** [comment]
Hm, i thought it was loaded because of getting new blocks. Now I see, that synchronization has been stuck 300k blocks ago. Thanks, it is getting faster with --light option)

**Comment by karalabe** [comment]
Sync will max out your available resources until it catches up. Light will do it faster, but it will still need to process a lot of stuff.
