### ISSUE TITLE
consensus/clique: choose valid proposal in Prepare()

### ISSUE THREAD

**Issue by markya0616** [ethereum/go-ethereum#14592]
#### System information

Geth version: `1.6.5`
OS & Version: OSX

#### Expected behaviour
In `Prepare()`, we should get valid proposals which are proposed to remove an existing signer or add an non-existing signer, and then choose one from them randomly. If so, we can avoid choosing invalid proposal.

#### Actual behaviour
We choose one proposal in `Prepare()` randomly and put it into `Coinbase` and `Nonce`. If the proposal is invalid, we will waste this vote. Invalid proposal is proposed to remove a non-existing signer or add an existing signer.

**Comment by karalabe** [comment]
Yes, that part was a bit rushed so it currently picks proposals at random. The proper solution is to pick a random proposal out of the meaningful ones (e.g. if someone's added as a signer, no need to keep voiting to add).

**Comment by markya0616** [comment]
OK. I've fired a [PR](https://github.com/ethereum/go-ethereum/pull/14596) to fix this issue. Please help review it.
