### ISSUE TITLE
Private network on single node occasionally fails to process a transaction

### ISSUE THREAD

**Issue by ckeenan** [ethereum/go-ethereum#14594]
#### System information

Geth version: `1.6.6-unstable`
OS & Version: OSX
Commit hash : 6171d01b1195abd7ac75044dcd507d4758d83cde

#### Expected behaviour
For a private network running on a single node, sending a series of transactions from an account with correct nonces which are received by the client without error will eventually be included in a block.

#### Actual behaviour
Occasionally, perhaps 5% of the time, when sending a series of transactions (let's say 5+) on a single-node private network (either clique or ethash), geth will get "stuck" on one transaction and remove the higher-nonced transactions from the mempool. This occurs even though all sent transaction hashes are logged as a "Submitted transaction" by geth. Details about the "stuck" transaction are visible via web3.eth.getTransaction, showing blockNumber as null, blockHash as 0x00.... The response from web3.eth.getTransactionCount for the sender matches the nonce of the stuck transaction. The pending block shows an empty transaction array and the txpool lists no queued or pending transactions. Attempting to resubmit the stuck transaction results in the error: `Error: known transaction: <hash>`. If a different transaction with the same nonce is submitted, it will get processed and the client proceeds as usual.

#### Steps to reproduce the behaviour
Start a single-node private network with an unlocked and well-endowed coinbase. Repeatedly run this js snipped until it hangs "waiting on" a particular hash, then inspect the stuck transaction:
```
n = 30;
nonce = web3.eth.getTransactionCount(web3.eth.coinbase);
received = 0;

hashArray = []
hashMap = {}

for (var i = 0; i < n; i++) {
    txNonce = nonce++;
    hash = web3.eth.sendTransaction({from: web3.eth.coinbase, to: web3.eth.coinbase, value: 1, nonce: txNonce})
    console.log(nonce, hash)
    hashArray.push(hash);
    hashMap[hash] = txNonce;
}

blockFilter = web3.eth.filter('latest')

blockFilter.watch(function(err, log) {
    var receipt = true;
    while (receipt) {
        receipt = web3.eth.getTransactionReceipt(hashArray[received]);
        if (receipt) {
            hash = hashArray[received];
            console.log('seen', hashMap[hash], hash);
            received++;
        }
    }
    console.log('received', received)
    console.log('waiting on', hashArray[received])
    console.log('pending block transactions', web3.eth.getBlock('pending').transactions)
    if (received == hashArray.length) {
        console.log('DONE');
        blockFilter.stopWatching();
    }
})
```

**Comment by bas-vk** [comment]
I tried to reproduce the issue but failed to do so. Could you run geth with the following option:
`geth --vmodule=core/*=6` and dump the log in a gist and post it here when you hit this problem?

**Comment by ckeenan** [comment]
Sure. https://gist.github.com/ckeenan/11be006c0b228503b4e309e87d34fd7b is a full log of running that script 3 times with n=30. The third run, it stops on hash `0xa8d8bbea95a10e82c9e03190ae46e0f4459ced6b9c86771ea943a35ba9e49bcb`

with the following RPC results
```
> web3.eth.getTransaction('0xa8d8bbea95a10e82c9e03190ae46e0f4459ced6b9c86771ea943a35ba9e49bcb')
{ blockHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
  blockNumber: null,
  from: '0x41ad2bc63a2059f9b623533d87fe99887d794847',
  gas: 90000,
  gasPrice: { [String: '18000000000'] s: 1, e: 10, c: [ 18000000000 ] },
  hash: '0xa8d8bbea95a10e82c9e03190ae46e0f4459ced6b9c86771ea943a35ba9e49bcb',
  input: '0x',
  nonce: 855,
  to: '0x41ad2bc63a2059f9b623533d87fe99887d794847',
  transactionIndex: 0,
  value: { [String: '1'] s: 1, e: 0, c: [ 1 ] },
  v: '0x1d4a7',
  r: '0xceb20f788d75fcc3a8eac919e83f5570869b9604000401fc2e5f885321767dc3',
  s: '0x32ee226faac42f9cfa0c0b7b4852ec18ec8517f92049ed09c25d12cbb73ca172' }

> web3.eth.getTransactionCount('0x41ad2bc63a2059f9b623533d87fe99887d794847')
855
```

Also I have been testing previous docker builds and fwiw the latest `stable` tag does not appear have this problem
Here is the output of `geth version` from that build:
```
Geth
Version: 1.6.1-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
```

**Comment by bas-vk** [comment]
Are you sure that you use commit 6171d01? The output of the console doesn't match the output of that commit. Also, which chain id are you using?

Could you run the test again with:
`geth --vmodule=miner/*=6`

and post the output in a gist, together with the hash of the transaction that get stuck?

**Comment by pcardune** [comment]
Did anyone ever figure out what was causing this and how to fix it? I'm seeing something similar with a puppeth-based testnet running on a single machine with geth-1.8 unstable.
