### ISSUE TITLE
Transaction pending issue on local private Network with one only node

### ISSUE THREAD

**Issue by VinZ73** [ethereum/go-ethereum#14600]
#### System information

Geth version: 1.6.1 stable
OS & Version: linux ubuntu amd 64 
Commit hash : (if `develop`)

as i can see this pb seems to be known for more than one year, but still alive.... ;-(
open source ... "hihaaa"   ^^

#### Expected behaviour
mining transaction on a local single private node... by following very simple tutorial 
using remix in a local browser to compile and run "greeter" smart contract 

#### Actual behaviour

local node get the request.. 
transaction appears in the list when  txtpool.status 
but then nothing happens 
transactions remains pending for ever ... 

#### Backtrace

````
[backtrace]
````

**Comment by VinZ73** [comment]
`> admin.nodeInfo
{
  enode: "enode://732b4b98c72356c36f108bd604ec3948f5f729013a4e1ae9e484080bb7718b066f55254a612fcc8f80e71984a533a63cc6926f202482386b56d0e7f538153076@[::]:30303?discport=0",
  id: "732b4b98c72356c36f108bd604ec3948f5f729013a4e1ae9e484080bb7718b066f55254a612fcc8f80e71984a533a63cc6926f202482386b56d0e7f538153076",
  ip: "::",
  listenAddr: "[::]:30303",
  name: "Geth/v1.6.1-stable-021c3c28/linux-amd64/go1.8.1",
  ports: {
    discovery: 0,
    listener: 30303
  },
  protocols: {
    eth: {
      difficulty: 32177548,
      genesis: "0x21e4aa1f90bdc6e6f2ba051e1e0b1312f8bff3dc4c9db1b9080c21cfe3d52303",
      head: "0x0cd03b5d2cc1c6817bff2ab2820060c69e8f11211d87dcbb37ca3dffc97d1a40",
      network: 1
    }
  }
}
> txpool.status
{
  pending: 1,
  queued: 0
}
> 
`

**Comment by bas-vk** [comment]
Can you check that the node is generating blocks?

**Comment by karalabe** [comment]
Perhaps you've set your PoW difficulty in the genesis block so high that your node is actually not able to fins blocks fast enough? 

Also, you did start the miner, right?

**Comment by VinZ73** [comment]
Hi everyone thanks a lot for your post and comments

yes the node is mining, (most of them empty blocks of course ;-)) 

here is my genesis file 

do you know how to reduce PoW difficulty level ? 
what value should be changed ? 

{
  "nonce": "0x0000000000000073",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "difficulty": "0x4000",
  "alloc": {},
  "coinbase": "0x0000000000000000000000000000000000000000",
  "timestamp": "0x00",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0xffffffff",
	"config": {
        	"chainId": 73,
        	"homesteadBlock": 0,
        	"eip155Block": 0,
        	"eip158Block": 0
    		}
}

**Comment by vinayakmali84** [comment]
Any solution for this?
I am also facing same issue as all transactions are in pending state. Mining is on & enough gas amount has been given.
