### ISSUE TITLE
Not Getting Ether for Mining

### ISSUE THREAD

**Issue by liammac001** [ethereum/go-ethereum#14602]
#### System information

Geth version: `1.6.5-stable`
OS & Version: Windows 10

#### Expected behaviour
I'm brand new to mining, so I'm sorry if I'm missing something obvious. I'm using ethminer on my RX 480 to solo mine to a local account I set up through geth. It looks like its working fine, and my GPU sticks to 25 MH/s, but after a day, no matter whether I use the javascript console, Ethereum wallet, or any website, it says I've gotten absolutely nothing. Aren't you supposed to get bits of ethereum over time? Or do you only get any when you mine a whole ether? Because I have absolutely 0 Wei, and it's making me think I'm not actually doing anything.

**Comment by robhaj** [comment]
You only get the 5 ether reward if you actually mine the block. Even with powerful hardware, it could be a very long time or never happen. Alternatively, you can join a mining pool which will pay out smaller amounts more consistently. If anyone in the pool successfully mines a block, the reward is distributed amongst the pool.
