### ISSUE TITLE
Starting P2P networking

### ISSUE THREAD

**Issue by Glafuski** [ethereum/go-ethereum#14601]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Start syncing

#### Actual behaviour

C:\>geth --rpc --cache=4096
INFO [06-08|23:49:08] Starting peer-to-peer node               instance=Geth/v1.
6.5-stable-cf87713d/windows-amd64/go1.8.3
INFO [06-08|23:49:08] Allocated cache and file handles         database=C:\\User
s\\JANI\\AppData\\Roaming\\Ethereum\\geth\\chaindata cache=4096 handles=1024
INFO [06-08|23:49:08] Initialised chain configuration          config="{ChainID:
 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675
000 EIP158: 2675000 Metropolis: 9223372036854775807 Engine: ethash}"
INFO [06-08|23:49:08] Disk storage enabled for ethash caches   dir=C:\\Users\\JA
NI\\AppData\\Roaming\\Ethereum\\geth\\ethash count=3
INFO [06-08|23:49:08] Disk storage enabled for ethash DAGs     dir=C:\\Users\\JA
NI\\AppData\\Ethash                          count=2
INFO [06-08|23:49:08] Initialising Ethereum protocol           versions="[63 62]
" network=1
INFO [06-08|23:49:08] Loaded most recent local header          number=3715314 ha
sh=79ce36.09933f td=267695693965887548076
INFO [06-08|23:49:08] Loaded most recent local full block      number=0       ha
sh=d4e567.cb8fa3 td=17179869184
INFO [06-08|23:49:08] Loaded most recent local fast block      number=3685963 ha
sh=51a0a5.e643db td=256222954731773745764
INFO [06-08|23:49:08] Starting P2P networking

#### Backtrace

````
[backtrace]
````

It just gets stuck at the "Starting P2P networking". How do i fix this? I've Googled from everywhere but i just can't find any anwer to this. I have used "--nat=none" and it works, but syncing blockchain is so slow when using this method :/ i have used over 12 hours just to sync with --fast.

**Comment by tedo0626** [comment]
Same problem any Help???

**Comment by simbro** [comment]
I have the exact same problem - @Glafuski  - did you ever get it working?

**Comment by ahsannawaz11** [comment]
I also have the same problem running with "geth --syncmode "light" --nousb"
