### ISSUE TITLE
Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 1s

### ISSUE THREAD

**Issue by stephantual** [ethereum/go-ethereum#1460]
Ubuntu 15.04 - RC1

Ubuntu is a fresh install, and nothing else but geth is running on it. 

NOT mining (just using a simple node)
Geth started with --rpc --maxpeers "250" console

After around 10 hours, this message appears, and every other operation stops:

I0710 08:25:59.677390    6506 server.go:1775] http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 1s
I0710 08:26:00.677498    6506 server.go:1775] http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 1s
I0710 08:26:01.677705    6506 server.go:1775] http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 1s
I0710 08:26:02.677861    6506 server.go:1775] http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 1s
I0710 08:26:03.677967    6506 server.go:1775] http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 1s
I0710 08:26:04.678100    6506 server.go:1775] http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 1s

Upon exiting (CTRL+C), this pops:

---
goroutine 1050209 [select, 874 minutes]:
github.com/ethereum/go-ethereum/p2p.(*Server).PeerCount(0xc20a132600, 0xc211b24da0)
    /home/vinz/builds/goethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:240 +0x18a
github.com/ethereum/go-ethereum/eth.(*Ethereum).PeerCount(0xc2081da580, 0xc224368240)
    /home/vinz/builds/goethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:522 +0x2f
github.com/ethereum/go-ethereum/xeth.(*XEth).PeerCount(0xc20811e270, 0xc21edfb860)
    /home/vinz/builds/goethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/xeth/xeth.go:414 +0x2b
github.com/ethereum/go-ethereum/rpc/api.(*netApi).PeerCount(0xc20ad523f0, 0xc2096717c0, 0x0, 0x0, 0x0, 0x0)
    /home/vinz/builds/goethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/api/net.go:89 +0x4f
github.com/ethereum/go-ethereum/rpc/api.(*netApi).Execute(0xc20ad523f0, 0xc2096717c0, 0x0, 0x0, 0x0, 0x0)
    /home/vinz/builds/goethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/api/net.go:73 +0xa6
github.com/ethereum/go-ethereum/rpc/api.(*MergedApi).Execute(0xc20af84db0, 0xc2096717c0, 0x0, 0x0, 0x0, 0x0)
    /home/vinz/builds/goethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/api/mergedapi.go:67 +0x35d
github.com/ethereum/go-ethereum/rpc/comms.func·002(0x7f1c2432dee0, 0xc214152a00, 0xc20c6028f0)
    /home/vinz/builds/goethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/comms/http_net.go:152 +0x5a1
net/http.HandlerFunc.ServeHTTP(0xc2092528c0, 0x7f1c2432dee0, 0xc214152a00, 0xc20c6028f0)
    /usr/lib/go/src/net/http/server.go:1265 +0x41
github.com/ethereum/go-ethereum/rpc/comms.func·001(0x7f1c2432dee0, 0xc214152a00, 0xc20c6028f0)
    /home/vinz/builds/goethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/comms/http_net.go:111 +0x223
net/http.HandlerFunc.ServeHTTP(0xc209252960, 0x7f1c2432dee0, 0xc214152a00, 0xc20c6028f0)
    /usr/lib/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208cdfc80, 0x7f1c2432dee0, 0xc214152a00, 0xc20c6028f0)
    /usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20e56e3c0)
    /usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/lib/go/src/net/http/server.go:1751 +0x35e

**Comment by obscuren** [comment]
Are you running geth in a VM?

**Comment by stephantual** [comment]
no, it's running on a core i3 with 8gb ram, new mobo, 4 gpus (it's the mining rig from the tutorial)

**Comment by maran** [comment]
What's the result for `ulimit -n` on the user that runs geth?

**Comment by etherninja** [comment]
ubuntu default is 1024 file descriptors. TCP timeout wait default is 60 seconds opening a new file descriptor on each tcp connect and will linger for 60 seconds. I would expect this issue with a high amount of rcp connects from ethminers, etc. Also, i've noticed that improper kills, not just the one exiting, leaves open descriptors that pile on top each other on each restart until the limit is reached.

**Comment by stephantual** [comment]
@maran 1024

Everything is stock. 

@etherninja : I'm not mining

I've upgraded to RC2, and going to let it run on just ./geth console overnight, and see if it fails again.

**Comment by stephantual** [comment]
12 hours without 'maxpeers 250' and still running... will keep monitoring.

**Comment by obscuren** [comment]
Wow, what? Maxpeer 250?! More is not better. You really should stay at the default unless you have a very good reason to go up or down.

The default, 25, is ideal for most peers.

**Comment by stephantual** [comment]
@obscuren Got it, 25 is ideal, will make sure update my guide. 

However, note that stats.ethdev.com shows EC2 node 3 at 147 peers, which will probably inspire others to try and raise that limit.

I'll keep monitoring.

**Comment by obscuren** [comment]
Hmm, I changed the EC nodes to also use the default. Maybe @cubedro changed this again?

**Comment by stephantual** [comment]
@obscuren - I'll close this if I can run a node for 5 days straight without issues - but the gut feel is that it's 100% linked to maxpeers which was set too high. Maybe cap it to something reasonable in the CLI switches?

**Comment by joeykrug** [comment]
So I get this too many open files error as well... I'm connected to no peers (mining w/ 1 core solo on a private chain), running in Ubuntu VM on DigitalOcean

```F0713 06:59:02.272104     971 cache.go:61] db write err:open /root/.ethereum/state/000066.log: too many open files```

**Comment by homotopycolimit** [comment]
same problem here. 1.0.0 running with:

./build/bin/geth --genesis ~/.ethereum/genesis_block.json --maxpeers=25 console

I get:

I0731 10:16:13.378409    3390 server.go:1775] http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 1s

on ubuntu 14.04, and yes, I was mining.

**Comment by fjl** [comment]
This should be fixed now.
