### ISSUE TITLE
[Privatechain] Mining stop bugs for OSX

### ISSUE THREAD

**Issue by EasonWang01** [ethereum/go-ethereum#14607]
#### System information

Geth version: `geth version 1.6.5-stable`

#### Expected behaviour
start mining.

#### Actual behaviour
It stop here for 1hour.
Setup privatechain works good last month,but after I install ethereum on my new Mac pro,it can't mining now.

(Stop at here for 1hour)
<img width="1179" alt="2017-06-10 9 43 46" src="https://user-images.githubusercontent.com/11001914/27003276-2d7d1a1a-4e26-11e7-9dcb-7743d48d59e5.png">

(Why generate DAG again?)
<img width="1185" alt="2017-06-10 9 44 00" src="https://user-images.githubusercontent.com/11001914/27003297-7e3befb2-4e26-11e7-83a1-a79a61b416c2.png">

 

#### Steps to reproduce the behaviour

Genesis block
```
{
  "config": {
    "chainId": 10849,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "clique": {
      "period": 10,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x593bf9b0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000736608acce913b0c3bcefe07bd04836dc78cda4a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
  }
}
```

#### Backtrace

````
[backtrace]
````

**Comment by EasonWang01** [comment]
Testing on Google GCE with same config works good.Is this a bugs on Mac pro?

<img width="896" alt="2017-06-11 9 13 42" src="https://user-images.githubusercontent.com/11001914/27007445-6229884c-4e86-11e7-8e5b-cb73d04adb42.png">

**Comment by karalabe** [comment]
Please paste a full log. These two snippets aren't really enough to see what's going on.

**Comment by EasonWang01** [comment]
Same on windows 10. geth 1.6.6stable

![asd](https://user-images.githubusercontent.com/11001914/27673547-df628682-5cd3-11e7-9d6b-96521c40fb84.png)

reproduce
```
web3.miner.setEtherbase(web3.eth.accounts[0])

geth --ipcdisable --rpc --rpcport 8104 --datadir "./privatechain/01" --networkid 123 --rpcapi="db,eth,net,web3,personal" --port=30310 console

miner.start(1)
```

stop here for 1hour.

**Comment by EasonWang01** [comment]
If using custom genesis that the problem solved ( --init genesis.json)

which means directly using 

```
geth --ipcdisable --rpc --rpcport 8104 --datadir "./privatechain/01" --networkid 123 --rpcapi="db,eth,net,web3,personal" --port=30310 console

```

Without init genesis first,it will using some default genesis block,then causing the problem above.

**Comment by karalabe** [comment]
Well, if you don't specify a custom genesis file, then if will init your chain with mainnet, which has a huge starting difficulty. You always need to set your own genesis file for a private network.
