### ISSUE TITLE
Wrong rolled back or info

### ISSUE THREAD

**Issue by sonulrk** [ethereum/go-ethereum#14608]
#### System information

Geth version: `1.6.1`
OS & Version: Windows 7 x64
System: Core i5 2400, 16GB, SSD
Net speed: 512kbps

#### Expected behaviour
using geth --fast cache 8192
geth should roll back exactly 2048 blocks during sync failed and dropping peer

#### Actual behaviour
geth roll back 10's of thousand blocks.

#### Steps to reproduce the behaviour
Sometimes happens.

#### Backtrace

>INFO [06-12|07:41:04] Imported new block headers               count=2048 elapsed=356.020ms number=2216689 hash=22c2a0…9ae625 ignored=0
INFO [06-12|07:41:18] Imported new state entries               count=71   elapsed=33.001ms  processed=6253537 pending=39572
INFO [06-12|07:41:28] Imported new state entries               count=62   elapsed=27.001ms  processed=6253599 pending=40564
INFO [06-12|07:41:29] Imported new block receipts              count=175  elapsed=43.002ms  number=2180710 hash=834dd6…ec836d ignored=0
INFO [06-12|07:41:30] Imported new block receipts              count=355  elapsed=77.004ms  number=2181065 hash=f7aeae…e6eb99 ignored=0
>WARN [06-12|07:41:54] Rolled back headers                      count=2048 header=2216689->2214641 fast=2181065->2181065 block=6->6
WARN [06-12|07:41:54] Synchronisation failed, dropping peer    peer=17adb5cee5271064 err="retrieved hash chain is invalid"
>INFO [06-12|07:42:03] Imported new block headers               count=0    elapsed=3.000ms   number=2181257 hash=fffc4e…ee259a ignored=192

**Comment by karalabe** [comment]
Synchronization during fast sync starts from the fast block, not the latest header.

**Comment by karalabe** [comment]
The `fast block` is the latest block which has the header + transaction list + uncle list.

**Comment by karalabe** [comment]
It's debatable that some headers may be downloaded twice now, but headers are quite tiny compared to the overall download a sync takes and the code complexity to start managing both headers and fast blocks simultaneously during sync would just be a lot of brittle code.

**Comment by sonulrk** [comment]
Thanks for your clarification. Actually, geth output is somewhat misleading for new beings like me. I have google a lot to understand the output of geth, but no avail, hence raised a issue here.
