### ISSUE TITLE
[private chain] miner.start 

### ISSUE THREAD

**Issue by leiletea** [ethereum/go-ethereum#14616]
#### System information

Geth version: `1.6.5-stable-cf87713d`
OS & Version: Ubuntu 5.4.0-6ubuntu1~16.04.4
Commit hash : 

#### Expected behaviour
miner.start

#### Actual behaviour
Can not mine

#### Steps to reproduce the behaviour
1、root@ubuntu:/opt# cat ethereum/genesis.json 
{
  "config": {
        "chainId": 0,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
  "alloc"      : {},
  "coinbase"   : "0x0000000000000000000000000000000000000000",
  "difficulty" : "0x1",
  "extraData"  : "",
  "gasLimit"   : "0x2fefd8",
  "nonce"      : "0x0000000000000042",
  "mixhash"    : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp"  : "0x00"
}

2、root@ubuntu:/opt/ethereum# geth --datadir /opt/ethereum init genesis.json
WARN [06-13|16:53:57] No etherbase set and no accounts found as default 
INFO [06-13|16:53:57] Allocated cache and file handles         database=/opt/ethereum/geth/chaindata cache=16 handles=16
INFO [06-13|16:53:57] Writing custom genesis block 
INFO [06-13|16:53:57] Successfully wrote genesis state         database=chaindata                    hash=c626d8…b99ce5
INFO [06-13|16:53:57] Allocated cache and file handles         database=/opt/ethereum/geth/lightchaindata cache=16 handles=16
INFO [06-13|16:53:57] Writing custom genesis block 
INFO [06-13|16:53:57] Successfully wrote genesis state         database=lightchaindata                    hash=c626d8…b99ce5

3、root@ubuntu:/opt/ethereum# geth  --datadir /opt/ethereum --rpc  --networkid 15 console
WARN [06-13|16:53:57] No etherbase set and no accounts found as default 
INFO [06-13|16:53:57] Allocated cache and file handles         database=/opt/ethereum/geth/chaindata cache=16 handles=16
INFO [06-13|16:53:57] Writing custom genesis block 
INFO [06-13|16:53:57] Successfully wrote genesis state         database=chaindata                    hash=c626d8…b99ce5
INFO [06-13|16:53:57] Allocated cache and file handles         database=/opt/ethereum/geth/lightchaindata cache=16 handles=16
INFO [06-13|16:53:57] Writing custom genesis block 
INFO [06-13|16:53:57] Successfully wrote genesis state         database=lightchaindata                    hash=c626d8…b99ce5
root@ubuntu:/opt/ethereum# geth  --datadir /opt/ethereum --rpc  --networkid 15 console
WARN [06-13|16:54:27] No etherbase set and no accounts found as default 
INFO [06-13|16:54:27] Starting peer-to-peer node               instance=Geth/v1.6.5-stable-cf87713d/linux-amd64/go1.8.1
INFO [06-13|16:54:27] Allocated cache and file handles         database=/opt/ethereum/geth/chaindata cache=128 handles=1024
WARN [06-13|16:54:28] Upgrading chain database to use sequential keys 
INFO [06-13|16:54:28] Initialised chain configuration          config="{ChainID: 0 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Metropolis: <nil> Engine: unknown}"
INFO [06-13|16:54:28] Disk storage enabled for ethash caches   dir=/opt/ethereum/geth/ethash count=3
INFO [06-13|16:54:28] Disk storage enabled for ethash DAGs     dir=/root/.ethash             count=2
WARN [06-13|16:54:28] Upgrading db log bloom bins 
INFO [06-13|16:54:28] Bloom-bin upgrade completed              elapsed=1.376ms
INFO [06-13|16:54:28] Initialising Ethereum protocol           versions="[63 62]" network=15
INFO [06-13|16:54:28] Loaded most recent local header          number=0 hash=c626d8…b99ce5 td=1
INFO [06-13|16:54:28] Loaded most recent local full block      number=0 hash=c626d8…b99ce5 td=1
INFO [06-13|16:54:28] Loaded most recent local fast block      number=0 hash=c626d8…b99ce5 td=1
INFO [06-13|16:54:28] Database conversion successful 
INFO [06-13|16:54:28] Starting P2P networking 
INFO [06-13|16:54:30] UDP listener up                          self=enode://5eca5b20ed6b64b84d3ed94c1bd7d895cd33d5e6e3facb5dd7617030c070aa3c99cf556a289e640b16d872a48a383c5e93fe4d5d244cbc9c6585714e0f6b5504@[::]:30303
INFO [06-13|16:54:30] HTTP endpoint opened: http://127.0.0.1:8545 
INFO [06-13|16:54:30] RLPx listener up                         self=enode://5eca5b20ed6b64b84d3ed94c1bd7d895cd33d5e6e3facb5dd7617030c070aa3c99cf556a289e640b16d872a48a383c5e93fe4d5d244cbc9c6585714e0f6b5504@[::]:30303
INFO [06-13|16:54:30] IPC endpoint opened: /opt/ethereum/geth.ipc 
Welcome to the Geth JavaScript console!

instance: Geth/v1.6.5-stable-cf87713d/linux-amd64/go1.8.1
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

4、Execute the following script in the console
> personal.newAccount("123456")
"0x260933a46681f627bb0489e5ffbe60527b2988f8"
> INFO [06-13|16:55:25] New wallet appeared                      url=keystore:///opt/ethereum/keysto… status=Locked
> personal.listAccounts
["0x260933a46681f627bb0489e5ffbe60527b2988f8"]
> miner.setEtherbase(eth.accounts[0])
true
> miner.start(4)
INFO [06-13|16:56:37] Updated mining threads                   threads=4
INFO [06-13|16:56:37] Transaction pool price threshold updated price=18000000000
nullINFO [06-13|16:56:37] Starting mining operation 
INFO [06-13|16:56:37] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=337.229µs

> INFO [06-13|16:56:42] Generating DAG in progress               epoch=0 percentage=0 elapsed=4.548s
INFO [06-13|16:56:47] Generating DAG in progress               epoch=0 percentage=1 elapsed=9.311s
.......................
INFO [06-13|17:04:18] Generating DAG in progress               epoch=0 percentage=98 elapsed=7m40.301s
INFO [06-13|17:04:23] Generating DAG in progress               epoch=0 percentage=99 elapsed=7m44.900s
INFO [06-13|17:04:23] Generated ethash verification cache      epoch=0 elapsed=7m44.922s
INFO [06-13|17:04:29] Generating ethash verification cache     epoch=1 percentage=1  elapsed=4.335s
INFO [06-13|17:04:32] Generating ethash verification cache     epoch=1 percentage=5  elapsed=7.941s
.......................
INFO [06-13|17:07:39] Generating ethash verification cache     epoch=1 percentage=98 elapsed=3m14.041s
Waiting for a long time
INFO [06-13|17:16:36] Generating DAG in progress               epoch=1 percentage=0  elapsed=8m50.835s

Why it will be generated    DAG in progress  again？

Whether there are documents that can guide me to achieve a private chain and normal mining?

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
They are different DAGs. The first one was for epoch 0, which is good for blocks 0-30000. The second one was for epoch 1, which will be switched over to when you reach block 30000. The reason it pre-generates it is that it doesn't "hang" mining when it reaches block 30000, rather the DAG is already available and usable.

You can use `puppeth` to make a nice starting genesis block.
