### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by mathcrypto** [ethereum/go-ethereum#14614]
#### System information

Geth version: `1.5.9 unstable`
OS & Version: OSX version	10.11.6

###Command used to run geth
geth --datadir /Users/amira/Library/Ethereum  --testnet --fast --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303" 2>> /Users/amira/geth.log

### Logs
I0613 09:44:28.934197 p2p/discover/udp.go:227] Listening, enode://82866b8ec2f266d353c5d79163800bb3b5e3125e118758a99a7da385fea962bda4c4e8186b325052e827fa11413b6487fa6714a71ef1359fcb4628098aa36e90@192.168.1.100:30303
I0613 09:44:28.934406 p2p/server.go:608] Listening on [::]:30303
I0613 09:44:28.935374 node/node.go:341] IPC endpoint opened: /Users/amira/Library/Ethereum/testnet/geth.ipc
I0613 09:44:28.936743 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(192.168.2.1)
I0613 09:45:48.937575 eth/downloader/downloader.go:326] Block synchronisation started
panic: runtime error: index out of range

goroutine 4037 [running]:
panic(0x48c4800, 0xc4200120f0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
github.com/ethereum/go-ethereum/core/vm.opBalance(0xc4234bfc78, 0xc424e08900, 0xc4207a6f70, 0xc420a93200, 0xc420a93220, 0x1388, 0x32, 0x61a8, 0xc424e08900, 0xc4207a6f70)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/instructions.go:315 +0x31e
github.com/ethereum/go-ethereum/core/vm.(*Interpreter).Run(0xc424e0b200, 0xc4207a6f70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/interpreter.go:192 +0x503
github.com/ethereum/go-ethereum/core/vm.(*EVM).Create(0xc424e08900, 0x6e6b378, 0xc4201903c0, 0xc420c51c20, 0x59, 0x59, 0x84114, 0xc425a79600, 0x4b4d5c5, 0x4b4d5c4, ...)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/evm.go:258 +0x602
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc4234983f0, 0x4f73b40, 0xc424b5ab40, 0xc425fd47e0, 0xc4234983f0, 0xc424b5ab40, 0xc426001f30, 0x499b3a0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:246 +0x25f
github.com/ethereum/go-ethereum/core.ApplyMessage(0xc424e08900, 0x4f73b40, 0xc424b5ab40, 0xc425fd47e0, 0xc424b5ab40, 0x73b38e8f, 0xc425c9fdc0, 0xd5cb2cf06e7d8f4, 0xcc12c2e4dddbbec, 0x3f6a3766)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:135 +0x5b
github.com/ethereum/go-ethereum/core.ApplyTransaction(0x5032320, 0xc421099000, 0xc425fd47e0, 0xc4210e8870, 0xc425fcc480, 0xc4209f7ef0, 0xc425fd4720, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:104 +0x26d
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc42109e500, 0xc4249de870, 0xc4210e8870, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:77 +0x543
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc421099000, 0xc425c60000, 0x3, 0x800, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:959 +0x147a
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).insertChain(0xc4201d21c0, 0xc425c60000, 0x3, 0x800, 0x50733b0, 0xc420648060, 0xc4259a18c0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:190 +0x51
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).(github.com/ethereum/go-ethereum/eth.insertChain)-fm(0xc425c60000, 0x3, 0x800, 0xd, 0x50733b0, 0x0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:166 +0x48
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processContent(0xc4210e6fc0, 0x4b53060, 0xc4247092d0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1403 +0xe2b
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc4247092d0, 0xc423aaf7a0, 0xc4210e6fc0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:462 +0x57
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:462 +0xce

**Comment by fjl** [comment]
Please try geth 1.6.x.

**Comment by fjl** [comment]
We believe that this issue is fixed in geth 1.6.x, but please provide more log output if possible. It would be nice to know which block number triggered the panic on 1.5.x.

**Comment by mathcrypto** [comment]
i have updated my client go install -v ./cmd/geth and it did not change the version @fjl

**Comment by mathcrypto** [comment]
I0613 09:44:28.778114 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /Users/amira/Library/Ethereum/testnet/geth/chaindata
I0613 09:44:28.836728 ethdb/database.go:176] closed db:/Users/amira/Library/Ethereum/testnet/geth/chaindata
I0613 09:44:28.838753 node/node.go:176] instance: Geth/v1.5.9-unstable-fa999861/darwin/go1.7.5
I0613 09:44:28.838801 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /Users/amira/Library/Ethereum/testnet/geth/chaindata
I0613 09:44:28.906801 core/genesis.go:95] Genesis block already in chain. Writing canonical number
I0613 09:44:28.906849 eth/backend.go:276] Successfully wrote custom genesis block: 41941023680923e0fe4d74a34bdac8141f2540e3ae90623718e47d66d1ca4a2d
I0613 09:44:28.907114 eth/backend.go:187] Protocol Versions: [63 62], Network Id: 3
I0613 09:44:28.907249 eth/backend.go:215] Chain config: {ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10}
I0613 09:44:28.908147 core/blockchain.go:219] Last header: #891894 [0daa1b7a…] TD=621787507991292
I0613 09:44:28.908158 core/blockchain.go:220] Last block: #891894 [0daa1b7a…] TD=621787507991292
I0613 09:44:28.908164 core/blockchain.go:221] Fast block: #891894 [0daa1b7a…] TD=621787507991292
I0613 09:44:28.908633 eth/handler.go:119] blockchain not empty, fast sync disabled
I0613 09:44:28.909354 p2p/server.go:340] Starting Server
I0613 09:44:28.917137 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using NAT-PMP(192.168.2.1)
I0613 09:44:28.934197 p2p/discover/udp.go:227] Listening, enode://82866b8ec2f266d353c5d79163800bb3b5e3125e118758a99a7da385fea962bda4c4e8186b325052e827fa11413b6487fa6714a71ef1359fcb4628098aa36e90@192.168.1.100:30303
I0613 09:44:28.934406 p2p/server.go:608] Listening on [::]:30303
I0613 09:44:28.935374 node/node.go:341] IPC endpoint opened: /Users/amira/Library/Ethereum/testnet/geth.ipc
I0613 09:44:28.936743 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(192.168.2.1)
I0613 09:45:48.937575 eth/downloader/downloader.go:326] Block synchronisation started
panic: runtime error: index out of range

goroutine 4037 [running]:
panic(0x48c4800, 0xc4200120f0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
github.com/ethereum/go-ethereum/core/vm.opBalance(0xc4234bfc78, 0xc424e08900, 0xc4207a6f70, 0xc420a93200, 0xc420a93220, 0x1388, 0x32, 0x61a8, 0xc424e08900, 0xc4207a6f70)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/instructions.go:315 +0x31e
github.com/ethereum/go-ethereum/core/vm.(*Interpreter).Run(0xc424e0b200, 0xc4207a6f70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/interpreter.go:192 +0x503
github.com/ethereum/go-ethereum/core/vm.(*EVM).Create(0xc424e08900, 0x6e6b378, 0xc4201903c0, 0xc420c51c20, 0x59, 0x59, 0x84114, 0xc425a79600, 0x4b4d5c5, 0x4b4d5c4, ...)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/evm.go:258 +0x602
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc4234983f0, 0x4f73b40, 0xc424b5ab40, 0xc425fd47e0, 0xc4234983f0, 0xc424b5ab40, 0xc426001f30, 0x499b3a0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:246 +0x25f
github.com/ethereum/go-ethereum/core.ApplyMessage(0xc424e08900, 0x4f73b40, 0xc424b5ab40, 0xc425fd47e0, 0xc424b5ab40, 0x73b38e8f, 0xc425c9fdc0, 0xd5cb2cf06e7d8f4, 0xcc12c2e4dddbbec, 0x3f6a3766)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:135 +0x5b
github.com/ethereum/go-ethereum/core.ApplyTransaction(0x5032320, 0xc421099000, 0xc425fd47e0, 0xc4210e8870, 0xc425fcc480, 0xc4209f7ef0, 0xc425fd4720, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:104 +0x26d
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc42109e500, 0xc4249de870, 0xc4210e8870, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:77 +0x543
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc421099000, 0xc425c60000, 0x3, 0x800, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:959 +0x147a
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).insertChain(0xc4201d21c0, 0xc425c60000, 0x3, 0x800, 0x50733b0, 0xc420648060, 0xc4259a18c0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:190 +0x51
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).(github.com/ethereum/go-ethereum/eth.insertChain)-fm(0xc425c60000, 0x3, 0x800, 0xd, 0x50733b0, 0x0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:166 +0x48
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processContent(0xc4210e6fc0, 0x4b53060, 0xc4247092d0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1403 +0xe2b
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc4247092d0, 0xc423aaf7a0, 0xc4210e6fc0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:462 +0x57
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:462 +0xce
I0613 10:48:23.388185 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /Users/amira/Library/Ethereum/testnet/geth/chaindata
I0613 10:48:23.445102 ethdb/database.go:176] closed db:/Users/amira/Library/Ethereum/testnet/geth/chaindata
I0613 10:48:23.447190 node/node.go:176] instance: Geth/v1.5.9-unstable-fa999861/darwin/go1.7.5
I0613 10:48:23.447258 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /Users/amira/Library/Ethereum/testnet/geth/chaindata
I0613 10:48:23.517166 core/genesis.go:95] Genesis block already in chain. Writing canonical number
I0613 10:48:23.517317 eth/backend.go:276] Successfully wrote custom genesis block: 41941023680923e0fe4d74a34bdac8141f2540e3ae90623718e47d66d1ca4a2d
I0613 10:48:23.517647 eth/backend.go:187] Protocol Versions: [63 62], Network Id: 3
I0613 10:48:23.517808 eth/backend.go:215] Chain config: {ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10}
I0613 10:48:23.518818 core/blockchain.go:219] Last header: #891894 [0daa1b7a…] TD=621787507991292
I0613 10:48:23.518831 core/blockchain.go:220] Last block: #891894 [0daa1b7a…] TD=621787507991292
I0613 10:48:23.518854 core/blockchain.go:221] Fast block: #891894 [0daa1b7a…] TD=621787507991292
I0613 10:48:23.519246 eth/handler.go:119] blockchain not empty, fast sync disabled
I0613 10:48:23.519934 p2p/server.go:340] Starting Server
I0613 10:48:23.530213 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using NAT-PMP(192.168.2.1)
I0613 10:48:23.540141 p2p/discover/udp.go:227] Listening, enode://82866b8ec2f266d353c5d79163800bb3b5e3125e118758a99a7da385fea962bda4c4e8186b325052e827fa11413b6487fa6714a71ef1359fcb4628098aa36e90@192.168.1.100:30303
I0613 10:48:23.540446 p2p/server.go:608] Listening on [::]:30303
I0613 10:48:23.541300 node/node.go:341] IPC endpoint opened: /Users/amira/Library/Ethereum/testnet/geth.ipc
I0613 10:48:23.544486 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(192.168.2.1)
I0613 10:48:53.542340 eth/downloader/downloader.go:326] Block synchronisation started
panic: runtime error: index out of range

goroutine 1532 [running]:
panic(0x48c4800, 0xc4200120f0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
github.com/ethereum/go-ethereum/core/vm.opBalance(0xc42343d848, 0xc423516900, 0xc4233e7450, 0xc42355a3e0, 0xc42355a400, 0x1388, 0x32, 0x61a8, 0xc423516900, 0xc4233e7450)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/instructions.go:315 +0x31e
github.com/ethereum/go-ethereum/core/vm.(*Interpreter).Run(0xc423519200, 0xc4233e7450, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/interpreter.go:192 +0x503
github.com/ethereum/go-ethereum/core/vm.(*EVM).Create(0xc423516900, 0x6868a08, 0xc4207c9440, 0xc420f874a0, 0x59, 0x59, 0x84114, 0xc420915300, 0x4b4d5c5, 0x4b4d5c4, ...)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/evm.go:258 +0x602
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc420fc5180, 0x4f73b40, 0xc4207079e0, 0xc420690260, 0xc420fc5180, 0xc4207079e0, 0xc4205d5f30, 0x499b3a0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:246 +0x25f
github.com/ethereum/go-ethereum/core.ApplyMessage(0xc423516900, 0x4f73b40, 0xc4207079e0, 0xc420690260, 0xc4207079e0, 0x73b38e8f, 0xc423547140, 0xd5cb2cf06e7d8f4, 0xcc12c2e4dddbbec, 0x3f6a3766)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:135 +0x5b
github.com/ethereum/go-ethereum/core.ApplyTransaction(0x5032320, 0xc4206de000, 0xc420690260, 0xc4210f02d0, 0xc42068e240, 0xc423bbd7a0, 0xc4206901a0, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:104 +0x26d
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc420794050, 0xc4207dad80, 0xc4210f02d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:77 +0x543
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc4206de000, 0xc420aa0000, 0x3, 0x800, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:959 +0x147a
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).insertChain(0xc4200d82a0, 0xc420aa0000, 0x3, 0x800, 0x50733b0, 0xc420f6d1a0, 0xc420aa4240)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:190 +0x51
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).(github.com/ethereum/go-ethereum/eth.insertChain)-fm(0xc420aa0000, 0x3, 0x800, 0xd, 0x50733b0, 0x0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:166 +0x48
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processContent(0xc4210ecfc0, 0x4b53060, 0xc423b4a0b0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1403 +0xe2b
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc423b4a0b0, 0xc420cf6d20, 0xc4210ecfc0)
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:462 +0x57
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/private/tmp/ethereum-20170206-15201-hm0y0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:462 +0xce
I0613 10:49:58.632682 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /Users/amira/Library/Ethereum/testnet/geth/chaindata
I0613 10:49:58.687553 ethdb/database.go:176] closed db:/Users/amira/Library/Ethereum/testnet/geth/chaindata
I0613 10:49:58.689542 node/node.go:176] instance: Geth/v1.5.9-unstable-fa999861/darwin/go1.7.5
I0613 10:49:58.689599 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /Users/amira/Library/Ethereum/testnet/geth/chaindata
I0613 10:49:58.758578 core/genesis.go:95] Genesis block already in chain. Writing canonical number
I0613 10:49:58.758643 eth/backend.go:276] Successfully wrote custom genesis block: 41941023680923e0fe4d74a34bdac8141f2540e3ae90623718e47d66d1ca4a2d
I0613 10:49:58.758990 eth/backend.go:187] Protocol Versions: [63 62], Network Id: 3
I0613 10:49:58.759138 eth/backend.go:215] Chain config: {ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10}
I0613 10:49:58.760203 core/blockchain.go:219] Last header: #891894 [0daa1b7a…] TD=621787507991292
I0613 10:49:58.760215 core/blockchain.go:220] Last block: #891894 [0daa1b7a…] TD=621787507991292
I0613 10:49:58.760221 core/blockchain.go:221] Fast block: #891894 [0daa1b7a…] TD=621787507991292
I0613 10:49:58.760598 eth/handler.go:119] blockchain not empty, fast sync disabled
I0613 10:49:58.761284 p2p/server.go:340] Starting Server
I0613 10:49:58.769138 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using NAT-PMP(192.168.2.1)
I0613 10:49:58.776261 p2p/discover/udp.go:227] Listening, enode://82866b8ec2f266d353c5d79163800bb3b5e3125e118758a99a7da385fea962bda4c4e8186b325052e827fa11413b6487fa6714a71ef1359fcb4628098aa36e90@192.168.1.100:30303
I0613 10:49:58.776398 p2p/server.go:608] Listening on [::]:30303
I0613 10:49:58.777295 node/node.go:341] IPC endpoint opened: /Users/amira/Library/Ethereum/testnet/geth.ipc
I0613 10:49:58.778858 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(192.168.2.1)

**Comment by fjl** [comment]
Thanks. Confirming that this is a known issue with 1.5.x and should be resolved in 1.6.x.

**Comment by karalabe** [comment]
@mathcrypto How did you update your client? If you are using `git`, please ensure you are either on the `master` branch, or on `release/1.6` if you want stable releases only.

**Comment by mathcrypto** [comment]
i am on master @karalabe 
git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.

**Comment by holiman** [comment]
Does `git pull` make any difference ?

**Comment by karalabe** [comment]
What's does `git rev-parse HEAD` say?

**Comment by mathcrypto** [comment]
it returns that it is already up-to-date

**Comment by mathcrypto** [comment]
@karalabe It returns this 061889d4ea13b23d777efbe005210ead8667e869

**Comment by karalabe** [comment]
Are you sure when you start `geth`, you are running the same binary that you've just built? What does `whereis geth` print? Are there mutliple version? If not, does it point inside your `GOPATH`?

**Comment by mathcrypto** [comment]
whereis geth prints no output

**Comment by fjl** [comment]
I think he meant `which geth`. The question is whether there is another (older) copy of geth in your PATH somehow.

**Comment by mathcrypto** [comment]
maybe i should uninstall it and reinstall it again

**Comment by karalabe** [comment]
The only way your issue can happen is if you have geth running from a different path than where you are compiling it. You'll need to find where 1.5.9 **unstable** is coming from.

**Comment by mathcrypto** [comment]
i checked the geth version i got this output $GOPATH/bin/geth version
Geth
Version: 1.6.6-unstable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: darwin
GOPATH=/Users/amira/go
GOROOT=/usr/local/Cellar/go/1.8.3/libexec

**Comment by mathcrypto** [comment]
then i have checked it again after i run the geth and it crashed and it was different with same gopath geth version
Geth
Version: 1.5.9-unstable
Git Commit: fa99986143fe3dec08cdffcff9185e3700719edd
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.5
OS: darwin
GOPATH=/Users/amira/go
GOROOT=/usr/local/Cellar/go/1.7.5/libexec

**Comment by holiman** [comment]
But what does `which geth` give you?

**Comment by mathcrypto** [comment]
/usr/local/bin/geth

**Comment by karalabe** [comment]
There's your problem. `go install` installed it under `
/Users/amira/go/bin/geth`.

**Comment by holiman** [comment]
So, that's probably from some standard installation, at some point (`apt-get install geth` perhaps?) . You should go into the geth repository and do  `make`, and then run `build/bin/geth`

**Comment by kciryt** [comment]
For me, this is not a 1.5 / 1.6 issue.  I have built the binary from source (1.8.0-unstable) and have the error after mining overnight.  I commented with details here https://github.com/ethereum/go-ethereum/issues/3733.
