### ISSUE TITLE
[BUG] Cannot start app, windows 10

### ISSUE THREAD

**Issue by Stoyvo** [ethereum/go-ethereum#14612]
#### System information

OS & Version: Windows
Commit hash : https://github.com/ethereum/mist/releases/tag/v0.8.10
#### Expected behaviour
For wallet to start

#### Actual behaviour
Crashes

#### Steps to reproduce the behaviour
Start wallet

#### Backtrace

Not sure where to get log from... See screenshot.
![image](https://user-images.githubusercontent.com/6148099/27062777-875c4a56-4fbb-11e7-9759-00936cd1ae90.png)

**Comment by Stoyvo** [comment]
WORKAROUND:

1) Remove Ethereum and Ethereum Wallet inside %appdata%.
2) Start Ethereum,
3) Make new wallet
4) Shutdown Ethereum
5) Navigate to Etherem keystore (within %appdata%)
6) Open previous wallets in text editor
7) Make new text file with 0xaddress of wallet to import and paste contents of that wallet.
8) Make sure json key of wallet "Crypto" is lowercase: "crypto"
9) Start Ethereum

Worked for me, hopefully account manager can be patched to handle this.

**Comment by karalabe** [comment]
Would have need nice to have the actual crash log. That part is the middle and contains no relevant data I'm afraid. Happy that you got it working but I cannot imagine why this would fix it. Did you use some really old wallet file?

**Comment by Stoyvo** [comment]
@karalabe Wallet was 456 days old. Still though, should be backwards compatible.

Where would this log be generated? Would be more than happy to provide.

**Comment by Stoyvo** [comment]
Update: I was incorrect about the filename being different. Though the json inside was valid
