### ISSUE TITLE
Getting raw transaction data from blocks

### ISSUE THREAD

**Issue by mshc04** [ethereum/go-ethereum#14618]
Geth version: `1.4.11`
OS & Version: Windows

I am thinking about getting all the data from the blocks which is stored from 1st transaction till date, in my private network.

I came across a method **getrawtransaction(txnHash)** but this method is not available in Geth.
Is there any substitute ? or is the above method available with different name ?

**Comment by obscuren** [comment]
It is, you gotta update your client. 1.4 is about a year old or so :-)

**Comment by mshc04** [comment]
from what geth version did the function add up ? @obscuren 
and can you brief on the use ?
in my case, if the successful txn includes first name and DOB , i want this data ,i.e first name and DOB ,to be fetched from block. can i get it ?
