### ISSUE TITLE
admin.peers is showing blank/null. 

### ISSUE THREAD

**Issue by MajjigaDeepak** [ethereum/go-ethereum#14619]
#### System information

Geth version: `1.8`
OS & Version: Ubuntu
Commit hash : (if `develop`)

#### Expected behaviour
 I am using two ubuntu machines with 14.04(second machine) & 16(First machine)  in AWS. I am trying to form a private network by connecting these two as peers. After admin.addpeer("enode with public IP with port 30303") the result it true and i should see the peers by command admin.peers or net.peerCount.

#### Actual behaviour
But i am getting blank/null in admin.peers or net.peerCount.
The Genesis Block / customgenesis file is same in both the machines.

#### Steps to reproduce the behaviour

1. Make a custom genesis json file in ubuntu16 machine.
2. init it and start console with bootnode along with private IP instead of [ : : ].
3. admin.addPeer(enode with public IP of ubuntu14 machine) ------ result will be true
-------------------------------
1. make same Custom genesis json file in ubuntu 14 machine.
2.init it and start console with same bootnode along with public IP of ubuntu16 machine.
3. admin.addPeer(enode with public IP of ubuntu16 machine) ------ result will be true

but admin.peers will be blank
#### Backtrace
admin.peers will be blank
````
[backtrace]
````

**Comment by bas-vk** [comment]
`admin.addPeer` returns true if the given enode was valid. It isn't an indication if the node was able to connect to the peer.

Could you check that there is no firewall blocking network acccess? I believe AWS blocks by default network traffic on port 30301.

Also, you mention geth 1.8, current major version is 1.6. I assume that is a typo?

**Comment by MajjigaDeepak** [comment]
Thanks for reply.

Both the machines are same security group and i made ports 30303 & 30301 open. the issue is not with firewall i guess.

Steps i followed.

Machine 1:

geth --datadir gen --networkid 19

admin.addPeer("enode://5757246166f3f982a7dd90059bf6a0c8043b73d392fa1ee73bbc5cb84c1c1676c5f495c060e2197ef9b84682ef9b0336dec2a2e46afd411e7a87504c2b569dee@54.168.239.64:30303") 
 ---> true
 
 tried wit port 30301 as well
 
 
 Machine 2:
 
 geth --datadir gen --networkid 19

admin.addPeer("enode://5f7e233fd10477a80550a57568d29614737ed6cd287164d44f847580c94ae1d19491f77b7776493662e2d408eab7a3833f2e1a9653c12c5ef2d4282a04a59c89@52.1.124.159:30303")
 ---> true
 
 tried wit port 30301 as well
 
 
 Still admin.peers is blank. Why these two machines are not getting connected?

Please let me know where i a missing. I followed this project wiki.

**Comment by bas-vk** [comment]
You only need port 30303 if you use the default settings (30301 was a typo). 
Can you telnet from one host to another on port 30303 while geth is running?

**Comment by MajjigaDeepak** [comment]
I could't telnet to port 30303 while geth is running but i am able telnet to other ports except 30303.
Its running on tcp6 and its not starting with 0.0.0.0.



Attaching detailed 

[screenshots.docx](https://github.com/ethereum/go-ethereum/files/1077240/screenshots.docx)

**Comment by MajjigaDeepak** [comment]
Its Fixed. The issue was with outbound rules for 30303.

Thanks a lot for your support.

**Comment by AqeelKazmi** [comment]
I am facing the same problem MajjigaDeepak.. Kindly help in this matter

**Comment by MajjigaDeepak** [comment]
@AqeelKazmi , Please try to ping/telnet  first between machines. if you are running two nodes in same machine maintain different ports.

**Comment by AqeelKazmi** [comment]
we r trying to connect two different machine through private network..
The credentials of machines are:
Machine 1:
IP: 192.168.10.16
Enode://dd83685ad2847e314fc22957ec50c0f377a766227a2f1959403f32973f8a4d150ad6b587aa1e9d8103798442782483ddd6e747cfa80fd1e66e7e31e54ad6a43ed
 

Machine 2:
IP: 192.168.10.3
Enode: //e2a8dfff60cfb2a09101f96bef0c54e22a29a4af034a6fea0d4b662ad2928fb82192ae067ba90172be2272b6ea948fb6f1fc81e74c75076a3c4d2a7cb5acf627

We tried to connect like this:
Machine 1:
admin.addPeer("enode://dd83685ad2847e314fc22957ec50c0f377a766227a2f1959403f32973f8a4d150ad6b587aa1e9d8103798442782483ddd6e747cfa80fd1e66e7e31e54ad6a43ed@192.168.10.3:30303")


Machine 2:
admin.addPeer("encode://e2a8dfff60cfb2a09101f96bef0c54e22a29a4af034a6fea0d4b662ad2928fb82192ae067ba90172be2272b6ea948fb6f1fc81e74c75076a3c4d2a7cb5acf627@192.168.10.16:30303")

It is returning true on both machines and the net.listening is returning true as well. But the peerCount still remained zero.

**Comment by MajjigaDeepak** [comment]
You should add enode of machine 2 in machine 1. Not same enode of same machine in same machine.

**Comment by AqeelKazmi** [comment]
I have also tries this but all in vain...It returns true but peerCount is still zero

**Comment by MajjigaDeepak** [comment]
Possible issues:

use private IP/internal IP instead of Public IP while staring node.
Check Inbound & outbound connections. Try to ping/telnet among machines.
It will return true which means the syntax is correct it doesn't mean machines are connected.

Check with admin.peers command.

**Comment by AqeelKazmi** [comment]
Got it.Problem was with Telnet .It is resolved. But now the issue is that on connected 1st time it gives net.peerCount = 1 on machine 1 but again when i run this command on machine 1 net.peerCount  becomes 0

**Comment by AqeelKazmi** [comment]
@MajjigaDeepak ...I need help

**Comment by MajjigaDeepak** [comment]
check with admin.peers or admin.nodeInfo.  once peer is added using machine 1. you can check in machine 2 with same command admin.peers.

**Comment by AqeelKazmi** [comment]
I have tried all this but now i failed to get peers connected. Yesterday, suddenly 2 peers were connected but  from that time no connection made again. Is there any tutorial regarding this??Plz guide me

**Comment by MajjigaDeepak** [comment]
I followed some of these links.

https://github.com/ethereum/go-ethereum/wiki/Private-network
https://ethereum.stackexchange.com/questions/13547/how-to-set-up-a-private-network-and-connect-peers-in-geth
https://souptacular.gitbooks.io/ethereum-tutorials-and-tips-by-hudson/content/private-chain.html

i also struggled at this point for about a week because ,

Some of the commands are outdated. 
They migrated, depleted some commands.

Finally i tried in two different AWS instances in same security group with same inbound & outbound rules with private IP's and got it.

I believe there is a network issue with your case with some IP's or security rules?

**Comment by AqeelKazmi** [comment]
And one thing that Ping command is successfully executing but telnet generates error
![ping](https://user-images.githubusercontent.com/30657768/29072057-a3bb07ac-7c5f-11e7-95c7-63ca6026907a.png)

**Comment by MajjigaDeepak** [comment]
Please try to telnet to port 22 (SSH) and try to run again.

**Comment by sai-kopparthi** [comment]
@AqeelKazmi mention 
--nodiscover , while you start running your second machine and peers are getting added.

**Comment by Ajit666** [comment]
I'm also having the same issue.

**Comment by PankajKhattar** [comment]
Refer to this
https://github.com/ethereum/go-ethereum/wiki/Setting-up-private-network-or-local-cluster

run admin.nodeInfo check for ip, if its showing ip: "::" Then its not connecting to the static IP.
In that case while adding peer in the enode replace [::] with the <actuall ip address> of the other node

hope it helps

**Comment by sotoncit06** [comment]
Use the same networkid.

1. Start first node on a different port and networkid
geth --datadir "$ethereum_home/youtube1-a" --port 30303 --nodiscover --networkid 1234 console 2 &gt console.log
2. Start second node on a different port but same networkid
geth --datadir "$ethereum_home/youtube1-b" --port 30304 --nodiscover --networkid 1234 console 2 &gt console.log

**Comment by syamrag** [comment]
Geth version: 1.8
OS & Version: Raspberry pi
I am using two raspberry pi and I am trying to form a private network by connecting these two as peers. After admin.addpeer("enode with private IP of the pi with port 30303") the result it true and the admin.peers returns empty. Also tryied placing static-nodes.json file in geth directory. FYI I was able to  see the peers when I tried it on two different laptop. Any specific configuration on raspberry pi that could prevent the peers from connecting.?

**Comment by holiman** [comment]
The admin.addpeers and static list are peers that geth will attempt to peer with. If those peers happen to have the wrong `networkid` or wrong genesis, the peering will fail, and they won't show in the peer list. 
You can debug it using more verbosity in the logs, that should show you why the peering fails.
