### ISSUE TITLE
Does not connect to more than 1-2 peers.

### ISSUE THREAD

**Issue by mantas7776** [ethereum/go-ethereum#14611]
#### System information

Geth version: 1.6.5 stable
OS & Version: Windows
Commit hash :

#### Expected behaviour
Should acquire peers over time.

#### Actual behaviour
Drops to 0 or 1 peers in first few minutes after start and does not connect to more.

#### Log

https://gist.github.com/mantas7776/cffff205a30dd44e2419586eb8427801

**Comment by karalabe** [comment]
Please make sure your router/firewalls allows port 30303 (by default) in and forwards it to your machine. Otherwise it take a lot of time to find peers if only you can connect to others but others cannot connect to you.

**Comment by mantas7776** [comment]
@karalabe `WARN [06-13|10:36:58] Synchronisation failed, retrying         err="receipt download canceled (requested)"
WARN [06-13|10:37:12] Synchronisation failed, retrying         err="block download canceled (requested)"`
This warning appers for me quite often and drops peers. I have seen theres another issue about this, but could this be caused by not forwarding port?

**Comment by chrisfranko** [comment]
I'm seeing this same behaviour on mac expanse nodes that are using 1.6.5

**Comment by navyzet** [comment]
I disabled nat and opened the 30303 port
This did not help me.

**Comment by clueware** [comment]
@navyzet don't disable NAT, forward the 30303 port to the IP of the computer running geth.

**Comment by kaidiren** [comment]
it still exists
