### ISSUE TITLE
Swift: New transaction example

### ISSUE THREAD

**Issue by Blockwallet** [ethereum/go-ethereum#14627]
The swift examples on this page: https://github.com/ethereum/go-ethereum/wiki/Mobile:-Account-management seems outdated, is there a new version?

**Comment by iamkidjoe** [comment]
also needed

**Comment by popaaaandrei** [comment]
@karalabe @eliasnaur let's make a new repo for a Swift API. What do you think?
I already have some code written.

**Comment by Abhishek-NickelFox** [comment]
Also doc/code for Raw Transaction
