### ISSUE TITLE
internal compiler error: Segmentation fault from algorithm.go when installing cmd/geth

### ISSUE THREAD

**Issue by Payden-Pringle** [ethereum/go-ethereum#14632]
#### System information

Geth version: N/A
OS & Version:  4.11.4-1-ARCH Linux
Commit hash : fade09a7fffe7a0095076dd3ff57015ab1e2393e

```
gcc-go 7.1.1-2
```

#### Expected behaviour

Install Geth without error.

#### Actual behaviour

Error occurs due to segmentation fault while installing the geth command from algorithm.go

#### Steps to reproduce the behaviour

git clone http://github.com/ethereum/go-ethereum
cd go-ethereum
make geth

#### Backtrace

````
make geth
build/env.sh go run build/ci.go install ./cmd/geth
>>> /usr/bin/go install -ldflags -X main.gitCommit=fade09a7fffe7a0095076dd3ff57015ab1e2393e -v ./cmd/geth
github.com/ethereum/go-ethereum/consensus/ethash
# github.com/ethereum/go-ethereum/consensus/ethash
consensus/ethash/algorithm.go: In function 'ethash.$nested4':
consensus/ethash/algorithm.go:269:22: internal compiler error: Segmentation fault
    percent := uint32(size / hashBytes / 100)
                      ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
util.go:44: exit status 2
exit status 1
make: *** [Makefile:15: geth] Error 1
````

**Comment by fjl** [comment]
Gccgo is not supported at this time. Please use the gc compiler (`pacman -S go`).
