### ISSUE TITLE
Miner forked with tx queue full

### ISSUE THREAD

**Issue by TalkingAntColony** [ethereum/go-ethereum#1463]
My mining node forked while still connected to 50 peers. I noticed it was was mining on it's own fork. I stopped ethminer but it still didn't sync. I saw a lot of TX queue full messages in the log, such as in the following snippit:

https://gist.github.com/TalkingAntColony/b3e0837e0c422ae9ca43

Geth 0.9.39/Windows on beefy PC

Restarting geth found a bad block and resynced with the network in a few minutes.

**Comment by fjl** [comment]
This is an olympic issue. It is unlikely that tx queue limits will be hit on the live network.
