### ISSUE TITLE
runtime: out of memory: cannot allocate 2164260864-byte block (625999872 in use)

### ISSUE THREAD

**Issue by bilbma** [ethereum/go-ethereum#14633]
![can not alocate memory](https://user-images.githubusercontent.com/4594919/27218183-59525e2e-527d-11e7-9c40-7e55e2f446a7.png)

**Comment by karalabe** [comment]
You will not be able to mine on a 32bit OS (or running a 32bit version of Geth). The ethash mining DAG requires more memory than the 32bit address space allows. Please use a 64bit machine, 64bit OS and 64bit verision of Geth if you wish to mine.
