### ISSUE TITLE
Fatal Error: Corrupted DB

### ISSUE THREAD

**Issue by Ryushia** [ethereum/go-ethereum#14645]
#### System information

Geth version: 1.6.5
OS & Version: Windows 10 1703

#### Course of Events

- changed Core Clock Value by 5Mhz increment
- called -- rpc
- started ethminer-0.9.41-genoil-1.1.7
- Computer Froze --> had to cold restart
- tried calling --rpc --> Error returned:

fatal: error starting protocol stack: leveldb/storage: corrupted or incomplete meta file

So tell me exactly which DB to delete and I'm happy to comply.

**Comment by karalabe** [comment]
Apparently you managed to fry your database. You'll need to delete your entire database `chaindata` and resync.

**Comment by Ryushia** [comment]
Thanks for the answer, Will do
