### ISSUE TITLE
swarm/mobile: expose swarm API

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#14642]
This is the follow-up issue for what was just discussed with some swarm members on the swarm summit in Berlin.
It would be great to expose the swarm API (like done here: https://github.com/ethereum/go-ethereum/tree/master/mobile) to be able to easily use it from android.

Would open the following required APIs/use-cases in the order of importance:
 - get the contract-ABI for contract-addresses (to render user interface and interact with the contract)
 - get the natspec (https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format) to better render the userinterface (not that important in the beginning but for later in the process)
 - read data from swarm - to create a reading content-provider (https://developer.android.com/guide/topics/providers/content-provider-creating.html)
 - write content to swarm (my main use case here to migrate https://github.com/ligi/Satoshiproof to Swarm+ETH)
Also a move to the Rinkeby testnet would be nice

**Comment by veqtor** [comment]
Really need this!

**Comment by justelad** [comment]
closing in favour of https://github.com/ethersphere/go-ethereum/issues/957
