### ISSUE TITLE
geth: command not found after building on Ubuntu

### ISSUE THREAD

**Issue by timcourtney** [ethereum/go-ethereum#14644]
#### System information

Geth version: `geth version`
OS & Version: Ubuntu 17.04

#### Expected behaviour

1. Followed instructions to build on ubuntu from source: https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu.
2. Installed golang, cloned go-ethereum, then `make geth` successfully.

#### Actual behaviour

1. Instructions said to run /build/bin/geth. I typed `cd build/bin` then `geth` and received `geth: command not found`
2. `geth: command not found`

**Comment by lmars** [comment]
You should either run `./build/bin/geth` or, if you change into the `build/bin` directory, run `./geth`.

Just running `geth` does not look in the current directory, it looks for the command in directories which are in the `PATH` environment variable.

See the following for a good explanation:

https://www.cs.purdue.edu/homes/bb/cs348/www-S08/unix_path.html

**Comment by johnsonzhou1234** [comment]
hi timcourtney！
 “geth: command not found after building on Ubuntu #14644” 
how to solve the problem？

**Comment by dinicthis** [comment]
It does not work. I followed instructions, installed all the stuff I was told to install, there is not one file with geth, ethereum or anything related to them whatsoever on my Ubuntu linux buld.

So what was it doing as it scrolled my screen endlessly with text for an hour, only to find that ethereum and geth do not exist, have never existed, and never will exist?

https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu

How many times must I follow the instructions to the letter before it actually works?

**Comment by karalabe** [comment]
https://geth.ethereum.org/install/

**Comment by junkim012** [comment]
old thread but the 'geth' command's executable file is in the directory "ethereum/go-ethereum/build/bin". For the terminal to find this command, you need to manually add this path to your $PATH environment variable. 

for ex) 
$ export PATH = /Users/username/Documents/ethereum/go-ethereum/build/bin:$PATH 
This adds the new directory where the geth command lies to the PATH and now your terminal will be able to find the 'geth' command.
