### ISSUE TITLE
Javascript array sort is broken

### ISSUE THREAD

**Issue by carver** [ethereum/go-ethereum#14649]
#### System information

Geth version: **`1.6.5-stable`**
OS & Version: Linux

#### Expected behaviour
When this javascript is run in geth console:
```
floats = [0.82, 1.22, 0.54];
floats.sort(function (a,b) { console.log('comparing', a, b, a-b); return a-b; });
```

I expect to see these comparisons, and the sorted array:
```
comparing 0.82 1.22 -0.4
comparing 1.22 0.54 0.6799999999999999
comparing 0.82 0.54 0.2799999999999999
[0.54, 0.82, 1.22]
```
(this output is copied from the Chrome console, where it works as expected)

#### Actual behaviour
Instead, I see this modified array that is unsuccessfully sorted:
```
comparing 0.82 1.22 -0.4
comparing 0.54 1.22 -0.6799999999999999
[0.82, 0.54, 1.22]
```

#### Steps to reproduce the behaviour
```
geth &
geth attach
> floats = [0.82, 1.22, 0.54];
> floats.sort(function (a,b) { console.log('comparing', a, b, a-b); return a-b; });
```

**Comment by carver** [comment]
This bug is still present in `v1.8.11`.

```sh
$ geth --dev &
$ geth attach /tmp/geth.ipc 
Welcome to the Geth JavaScript console!

instance: Geth/v1.8.11-stable-dea1ce05/linux-amd64/go1.10
coinbase: 0x2ac1638de404b051cfd1b2a91e83d3c22ac89b57
at block: 0 (Wed, 31 Dec 1969 16:00:00 PST)
 datadir: 
 modules: admin:1.0 clique:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 shh:1.0 txpool:1.0 web3:1.0

> floats = [0.82, 1.22, 0.54];
[0.82, 1.22, 0.54]
> floats.sort(function (a,b) { console.log('comparing', a, b, a-b); return a-b; });
comparing 0.82 1.22 -0.4
comparing 0.54 1.22 -0.6799999999999999
[0.82, 0.54, 1.22]
> 
```

**Comment by holiman** [comment]
Seems related: https://github.com/robertkrimen/otto/issues/266

**Comment by karalabe** [comment]
The OttoVM JavaScript interpreter that the console uses was discontinued, so the bugs aren't getting fixed.   The only way out is for us to replace Otto with a newer codebase https://godoc.org/github.com/dop251/goja
