### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by sjosegarcia** [ethereum/go-ethereum#14651]
#### System information

Geth version: 1.6.4, 1.6.5, and 1.6.6
OS & Version: Windows 10 x64
Commit hash :
#### Expected behaviour
Out of memory

So I have been trying to get get to run for a while.each time  I try to sync the blockchain I get the error. I notice that get runs as a 32+bit process even though I downloaded the 64 bit installer. I have 8 gb of RAM. I have been thinking of doing a pull and compile it on my own to see if I can make some magic.

Any ideas of how I can fix it?

**Comment by karalabe** [comment]
Which installer file did you download? URL appreciated. Also could you paste the output of `geth version`?

**Comment by sjosegarcia** [comment]
Well originally I tried https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.6.5-cf87713d.exe . Then I went to try the unstable release 1.6.6, and also 1.6.4. 

But this is weird, it says I have 1.6.1...
`c:\>geth version
Geth
Version: 1.6.1-stable
Git Commit: 021c3c281629baf2eae967dc2f0a7532ddfdc1fb
Architecture: 386
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: windows
GOPATH=
GOROOT=c:\go

c:\>geth help
NAME:`

**Comment by sjosegarcia** [comment]
I removed the instance of the program, and I am currently downloading the blockchain. Ill let you know if anything comes up.
