### ISSUE TITLE
Transaction pending issue on private: invalid nonce.

### ISSUE THREAD

**Issue by ptarasov** [ethereum/go-ethereum#14658]
#### System information

Geth version: 1.6.5-stable-cf87713d/linux-amd64/go1.8.3
OS & Version: Linux

#### Expected behaviour
Private network: 3 miners + 1 RPC node. RPC is located on LAN (doesn't have a static IP) and there is access to outside through one of the miners. Transactions sending (series of 50-70 txs) from account on RPC node and received without error and will be approved and included in a block.

#### Actual behaviour
After a while there are problems with nonce value and transactions on "pending" status and remains pending for ever. 

[log](https://github.com/ethereum/go-ethereum/files/1087693/geth.txt)

**Comment by holiman** [comment]
How are you submitting transactions - are you using the rpc-methods of the instance which the logfile was collected from ? Or do they come from some peer ?

**Comment by ptarasov** [comment]
I'm using web3js library:
`contract.methodName.sendTransaction(params, { from: account, gas: 1000000 }, function(err, txHash) {...}`
Transactions are sending from the instance which the logfile was collected from.
