### ISSUE TITLE
Problems of: Rolled back headers and Synchronization failed, dropping peer ...

### ISSUE THREAD

**Issue by KevinCollinsBr** [ethereum/go-ethereum#14653]
#### System information

Geth version: 1.6.5 -stable - cf87713d
OS & Version: Linux 16.04.02 LTS - (Virtualized)
Commit hash : (if `develop`)

#### Expected behaviour

I worked on it for a week. I've read many forums about this problem (if it's really a problem), many talk about time synchronization, tried and failed, I even install an NTP, but it did not work ... I've done everything, how to remove Chaindata and Mas remains In the same situation. I need to synchronize this block chain to continue developing my project, but I do not know how.

#### Actual behaviour
INFO [06-19|10:35:55] Block synchronisation started
INFO [06-19|10:36:02] Imported new state entries               count=1 elapsed=273.629ms processed=1 pending=17
INFO [06-19|10:36:04] Imported new state entries               count=2 elapsed=380.823ms processed=3 pending=49
INFO [06-19|10:36:07] Imported new state entries               count=3 elapsed=1.613s    processed=6 pending=97
WARN [06-19|10:36:08] Rolled back headers                      count=191 header=509671->509671 fast=509944->509944 block=0->0
WARN [06-19|10:36:08] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="retrieved hash chain is invalid"
INFO [06-19|10:36:41] Imported new state entries               count=1   elapsed=98.689ms  processed=7 pending=17
INFO [06-19|10:36:42] Imported new state entries               count=2   elapsed=1.972ms   processed=9 pending=49
WARN [06-19|10:36:44] Rolled back headers                      count=71  header=509671->509671 fast=509944->509944 block=0->0
INFO [06-19|10:36:44] Imported new state entries               count=3   elapsed=52.087ms  processed=12 pending=97
WARN [06-19|10:36:44] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="retrieved hash chain is invalid"
INFO [06-19|10:37:07] Imported new state entries               count=1   elapsed=584.129µs processed=13 pending=17
INFO [06-19|10:37:08] Imported new state entries               count=2   elapsed=776.664µs processed=15 pending=49
WARN [06-19|10:37:09] Rolled back headers                      count=86  header=509671->509671 fast=509944->509944 block=0->0
WARN [06-19|10:37:09] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="retrieved hash chain is invalid"
INFO [06-19|10:38:30] Imported new state entries               count=1   elapsed=91.946ms  processed=16 pending=17
INFO [06-19|10:38:32] Imported new state entries               count=2   elapsed=49.004ms  processed=18 pending=49
WARN [06-19|10:38:33] Rolled back headers                      count=198 header=509671->509671 fast=509944->509944 block=0->0
WARN [06-19|10:38:33] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="retrieved hash chain is invalid"
WARN [06-19|10:38:36] Synchronisation failed, dropping peer    peer=e4fa2fcc0ea7a2df err="action from bad peer ignored"
INFO [06-19|10:38:50] Imported new state entries               count=1   elapsed=133.744ms processed=19 pending=17
WARN [06-19|10:38:53] Rolled back headers                      count=191 header=509671->509671 fast=509944->509944 block=0->0
WARN [06-19|10:38:53] Synchronisation failed, dropping peer    peer=b547e3ffbe580515 err="retrieved hash chain is invalid"
INFO [06-19|10:39:01] Imported new state entries               count=1   elapsed=210.007ms processed=20 pending=17
INFO [06-19|10:39:03] Imported new state entries               count=2   elapsed=264.517ms processed=22 pending=49
INFO [06-19|10:39:04] Imported new state entries               count=3   elapsed=435.099ms processed=25 pending=97
WARN [06-19|10:39:04] Rolled back headers                      count=155 header=509671->509671 fast=509944->509944 block=0->0
WARN [06-19|10:39:04] Synchronisation failed, dropping peer    peer=e4fa2fcc0ea7a2df err="retrieved hash chain is invalid"
WARN [06-19|10:39:07] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="action from bad peer ignored"
INFO [06-19|10:39:19] Imported new state entries               count=1   elapsed=1.174ms   processed=26 pending=17
WARN [06-19|10:39:20] Rolled back headers                      count=67  header=509671->509671 fast=509944->509944 block=0->0
WARN [06-19|10:39:20] Synchronisation failed, dropping peer    peer=b547e3ffbe580515 err="retrieved hash chain is invalid"
INFO [06-19|10:39:41] Imported new state entries               count=1   elapsed=45.047ms  processed=27 pending=17
INFO [06-19|10:39:42] Imported new state entries               count=2   elapsed=1.464ms   processed=29 pending=49
WARN [06-19|10:39:44] Rolled back headers                      count=95  header=509671->509671 fast=509944->509944 block=0->0
WARN [06-19|10:39:44] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="retrieved hash chain is invalid"
INFO [06-19|10:40:10] Imported new state entries               count=1   elapsed=22.969ms  processed=30 pending=17
INFO [06-19|10:40:12] Imported new state entries               count=2   elapsed=4.623ms   processed=32 pending=49
INFO [06-19|10:40:13] Imported new state entries               count=3   elapsed=26.253ms  processed=35 pending=97
WARN [06-19|10:40:13] Rolled back headers                      count=191 header=509671->509671 fast=509944->509944 block=0->0
WARN [06-19|10:40:13] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="retrieved hash chain is invalid"
INFO [06-19|10:40:40] Imported new state entries               count=1   elapsed=3.514ms   processed=36 pending=17
INFO [06-19|10:40:41] Imported new state entries               count=2   elapsed=27.859ms  processed=38 pending=49
INFO [06-19|10:40:43] Imported new state entries               count=3   elapsed=5.802ms   processed=41 pending=97
WARN [06-19|10:40:44] Rolled back headers                      count=191 header=509671->509671 fast=509944->509944 block=0->0
WARN [06-19|10:40:44] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="retrieved hash chain is invalid"
INFO [06-19|10:41:21] Imported new state entries               count=1   elapsed=37.939ms  processed=42 pending=17
INFO [06-19|10:41:22] Imported new state entries               count=2   elapsed=20.384ms  processed=44 pending=49
WARN [06-19|10:41:23] Rolled back headers                      count=56  header=509671->509671 fast=509944->509944 block=0->0
WARN [06-19|10:41:23] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="retrieved hash chain is invalid"
INFO [06-19|10:42:30] Imported new state entries               count=1   elapsed=38.899ms  processed=45 pending=17
INFO [06-19|10:42:32] Imported new state entries               count=2   elapsed=83.162ms  processed=47 pending=49
WARN [06-19|10:42:33] Rolled back headers                      count=191 header=509671->509671 fast=509944->509944 block=0->0
WARN [06-19|10:42:33] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="retrieved hash chain is invalid"
INFO [06-19|10:43:09] Imported new state entries               count=1   elapsed=56.788ms  processed=48 pending=17
INFO [06-19|10:43:11] Imported new state entries               count=2   elapsed=1.245ms   processed=50 pending=49
INFO [06-19|10:43:12] Imported new state entries               count=3   elapsed=1.084ms   processed=53 pending=97
WARN [06-19|10:43:12] Rolled back headers                      count=191 header=509671->509671 fast=509944->509944 block=0->0
WARN [06-19|10:43:12] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="retrieved hash chain is invalid"
INFO [06-19|10:43:41] Imported new state entries               count=1   elapsed=57.865ms  processed=54 pending=17
INFO [06-19|10:43:43] Imported new state entries               count=2   elapsed=21.079ms  processed=56 pending=49
WARN [06-19|10:43:45] Rolled back headers                      count=95  header=509671->509671 fast=509944->509944 block=0->0
WARN [06-19|10:43:45] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="retrieved hash chain is invalid"
INFO [06-19|10:44:21] Imported new state entries               count=1   elapsed=1.137ms   processed=57 pending=17
INFO [06-19|10:44:23] Imported new state entries               count=2   elapsed=14.910ms  processed=59 pending=49
WARN [06-19|10:44:24] Rolled back headers                      count=191 header=509671->509671 fast=509944->509944 block=0->0
INFO [06-19|10:44:24] Imported new state entries               count=4   elapsed=65.914ms  processed=63 pending=113
WARN [06-19|10:44:24] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="retrieved hash chain is invalid"
INFO [06-19|10:44:50] Imported new state entries               count=1   elapsed=36.706ms  processed=64 pending=17
INFO [06-19|10:44:52] Imported new state entries               count=2   elapsed=1.499ms   processed=66 pending=49
INFO [06-19|10:44:53] Imported new state entries               count=3   elapsed=18.550ms  processed=69 pending=97

#### Steps to reproduce the behaviour

My virtual machine has 2Gb of RAM, 160Gb HD and 2 cores processing, Internet 10Mb. As for the network is normal, I use two network cards, one in NAT mode and the other in HostOnly for access via SSH through PUttyn.

I used this command to start the Blocks chain: geth --testnet --syncmode=light --rpc --rpcapi db,eth,net,web3,personal --cache=1024  --rpcport 8545 --rpcaddr 127.0.0.1 --rpccorsdomain "*" --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303"

#### Backtrace

````
[backtrace]
````

**Comment by sonulrk** [comment]
Please follow issues #14608, 14626 and #14647 if it helps. If you are sure there is no hardware problem and you are using ssd instead of hdd then my suggestion is use geth in full mode or use parity. I had wasted 20 days on this. Currently geth has some serious bugs but not every body affected every time. I have full faith on the developers that they will come out with a clean build in near future.

**Comment by pebwindkraft** [comment]
I support this point of view, which means, the geth app has currently no deterministic behaviour. I have done 5 different approaches (virtual machines, dedicated machine), all without success, and the comunity generally tells you to restart from scratch (based on opinion, not on knowledge). When reading all the comments, it looks like "slower machines" and small network do not come to sync. They start to sync, but then never reach the last block, and instead loads tons of state entries for a long time. There is no reply I could find as to what this means (state entries and the syncing process), and how long does it take. It only says, it can reach a number between 8 and 10mio. I showed my experience in a comment here:
https://github.com/ethereum/go-ethereum/issues/14571
Looks like you have to have a fast network and QuadCore and +4Gig RAM and SSD, to successfully load/sync ether chaindata. 
Experts to prove me wrong please.
On trust in devs: yes, but on this topic: they usually work with fast machines, and certainly don't feel the issue as such... it would stop them from working. So no, it is not a question of trust. A system which shall move money or virtual values around, being non-deterministic cannot gain much trust...

**Comment by drewstaylor** [comment]
I've been trying to sync 20 days of history for over 7 days now. I have a decently fast machine too; here are my stats:

Intel Core i5-6500 CPU @ 3.20 GHz
500 GB SSD (400 GB available space)
8 GB DDR5 Ram
GeForce GTX 1050 Ti 4GB

I have a backup of chaindata up to 20 days ago, but I seem entirely unable to sync the last 20 days and even less success syncing the entire chain with geth or geth --fast.  If anyone has suggestions about what I can do to sync the chain, please respond.

**Comment by sonulrk** [comment]
Please check your network speed. It should be fast and stable (should be 2 mbps at least). The current version of geth is worked as --fast mode by default. So geth and geth --fast is same. Try using geth --full mode. It will take time about 2 to 3 weeks but **more probably** successfully sync.

**Comment by drewstaylor** [comment]
My network speed is 15 mbps per second on average over ethernet not wireless. During geth sync there are no other computers connected to the network except 2 antminers (they use very little bandwidth). To avoid corruption I can only create regularly timed backups so I don't lose everything when it inevitably crashes.
