### ISSUE TITLE
How to deploy token on GETH? 

### ISSUE THREAD

**Issue by kamilk91** [ethereum/go-ethereum#14654]
#### System information

Geth version: `geth the newest (updated today) version`
OS & Version: Ubuntu
Commit hash : (if `develop`)

#### Expected behaviour
I expect, that machine connect Solidity with GETH, and i will deploy new Smart Token.

#### Actual behaviour
I was using 3 instructions from Internet, but still cant connect Solidity with ETH. Maybe there is another method to deploy smart contract without use admin.setSolc("path/to/solc")? When i type this command in geth console i have response that "setSolc is not a command". 

#### Steps to reproduce the behaviour
Just try use admin.setSolc("path/to/your/solc") in geth console.

**Comment by ligi** [comment]
I think you should ask this question on stackoverflow (https://ethereum.stackexchange.com) instead of opening a issue here.
