### ISSUE TITLE
Geth not showing balance but etherchain.org does, synced up to block 3900000

### ISSUE THREAD

**Issue by Vidicus** [ethereum/go-ethereum#14666]
#### System information

Geth version: v1.6.5
OS & Version: Windows

#### Expected behaviour
Produce accurate balance on accounts.

#### Actual behaviour
Produces 0 balance.

#### Steps to reproduce the behaviour
>eth.accounts[1]
"0xb8318e6622b47c02ba44e30271071841a7eccede"
>eth.getBalance(eth.accounts[1])
0

#### Backtrace
https://etherchain.org/account/0xb8318e6622b47c02ba44e30271071841a7eccede#txreceived

c:\Program Files\Geth>geth.exe console
INFO [06-20|12:21:05] Starting peer-to-peer node               instance=Geth/v1.6.5-stable-cf87713d/windows-amd64/go1.8.3
INFO [06-20|12:21:05] Allocated cache and file handles         database=C:\\Users\\kevin\\AppData\\Roaming\\Ethereum\\geth\\chaindata cache=128 handles=1024
INFO [06-20|12:21:08] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Metropolis: 9223372036854775807 Engine: ethash}"
INFO [06-20|12:21:08] Disk storage enabled for ethash caches   dir=C:\\Users\\kevin\\AppData\\Roaming\\Ethereum\\geth\\ethash count=3
INFO [06-20|12:21:08] Disk storage enabled for ethash DAGs     dir=C:\\Users\\kevin\\AppData\\Ethash                          count=2
INFO [06-20|12:21:08] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [06-20|12:21:09] Loaded most recent local header          number=3901969 hash=711f17…acc61b td=374427115802609642900
INFO [06-20|12:21:09] Loaded most recent local full block      number=0       hash=d4e567…cb8fa3 td=17179869184
INFO [06-20|12:21:09] Loaded most recent local fast block      number=3901848 hash=a31126…3351f8 td=374325303949784574799

**Comment by shlomogoldblatt** [comment]
I have exact same problem. bought some ether for testing purposes, synced the whole chain (one week non stop), still see 0 balance. kind of pissed off already

geth 1.6.5
Windows 64

**Comment by karalabe** [comment]
You are not yet synced. You can see even in the logs that the last full block is 0. Fast sync needs to pull in everything to make it usable, i.e. all the blocks to chain head and all associated state.
