### ISSUE TITLE
eth_getTransactionByHash returns invalid blockHash for unmined transaction

### ISSUE THREAD

**Issue by mcdee** [ethereum/go-ethereum#14661]
#### System information

Version: 1.6.5-stable
Git Commit: cf87713dd42162861b7ed227f79f0638a33571df
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux

#### Expected behaviour

As per https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionbyhash

When running `eth_getTransactionByHash` for a transaction that is unmined it should return a `blockHash` of `null`.

#### Actual behaviour

When running `eth_getTransactionByHash` for a transaction that is unmined it returns a `blockHash` of `"0x0000000000000000000000000000000000000000000000000000000000000000"`.

For example:
```
{
  "blockHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "blockNumber": null,
  "from": "0x388ea662ef2c223ec0b047d41bf3c0f362142ad5",
  "gas": "0x2fefd8",
  "gasPrice": "0x4e3b29200",
  "hash": "0x9d7a5d47e6f72774c5b538105f449f605c837059fbfb9eb57c54ac5bda3df0b4",
  "input": "0x0a0e5c9d000000000000000000000000aca94ef8bd5ffee41947b4585a84bda5a3d3da670000000000000000000000000000000000000000000000000000000000002760",
  "nonce": "0x26",
  "to": "0x821c4bf411461c3ae3c7ecc07328959ab7abf04d",
  "transactionIndex": "0x0",
  "value": "0x38d7ea4c68000",
  "v": "0x1c",
  "r": "0x5c106c32acc453b74f52eafd606cd38fd9a452f74b223fa6b46736f7b6b86c24",
  "s": "0x5e0bdfe83b966b9b381aa2902860273851b3720e025793b42f9aed4515ccd284"
}
```

This has a downstream impact on `ethclient.TransactionByHash` as this function checks the value of `blockHash` to decide whether a transaction is pending or not; at current it always returns `false` even if the transaction is pending.

#### Steps to reproduce the behaviour

  - create a transaction
  - check the `blockHash` value of eth_getTransactionByHash prior to the transaction being mined

**Comment by 0xcaff** [comment]
I'm still experiencing this issue on version 1.6.7-stable-ab5646c5 when using a Proof of Authority private chain with the clique consensus engine.
