### ISSUE TITLE
mobile: incorrect assignment of CallMsg data from byte array

### ISSUE THREAD

**Issue by enuoCM** [ethereum/go-ethereum#14675]
#### System information

Geth version: `1.6.6`
OS & Version: Android 5.1.1/arm64-v8a with geth.aar(make android)
Commit hash : 431cf2a1e453346bcc627ac1fb9df3950a6c3499

#### Expected behaviour
the msg.Data of `func (ec *Client) CallContract(ctx context.Context, msg ethereum.CallMsg, blockNumber *big.Int) ([]byte, error)` of ethclient/ethclient.go should be `[32 150 82 85]`

#### Actual behaviour
msg.Data is not `[32 150 82 85]`. Instead, it's a changeable byte array，such as `[48 122 59 151]`, `[73 78 70 79]`, etc. Sometimes it will be the right value `[32 150 82 85]`

#### Steps to reproduce the behaviour
Constructa an CallMsg on Android:
 ```
 CallMsg callMsg= Geth.newCallMsg();
 byte data = okio.ByteString.decodeHex("20965255").toByteArray();//[32 150 82 85]
 callMsg.setData(data);
 callMsg.set...
```
call it by EthereumClient#callContract(ctx, callMsg, -1)

BTW, on Android 7.1/armeabi-v7a device, it has no such issue. The msg.Data is exactly that passed from Android.

Does anybody happen to know this issue? Tks.

**Comment by enuoCM** [comment]
a simple way to reproduce this issue:
```
CallMsg callMsg= Geth.newCallMsg();
byte data = okio.ByteString.decodeHex("20965255").toByteArray();//[32 150 82 85]
callMsg.setData(data);
```
check `callMsg.getData()`
`callMsg.getData()` and `data ` are different.

**Comment by karalabe** [comment]
Could you try if it works with the archives from Maven Central / Sonatype (or our downloads page https://geth.ethereum.org/downloads/)? This seems to be an issue in the generated bridge code by gomobile. Could it happen that your local gomobile is older and a newer version contains a fix for this already?

**Comment by enuoCM** [comment]
@karalabe The archives from Maven Central(org.ethereum:geth:1.6.5) still has such issue. I cann't download the archive from https://geth.ethereum.org/downloads/ now. I will try them next week.

**Comment by enuoCM** [comment]
@karalabe geth-android-all-1.6.6-10a45cb5.aar from https://geth.ethereum.org/downloads/ has the issue too. And I tried the latest gomobile version([44a54e9](https://github.com/golang/mobile/commit/44a54e9b78442c0a8233ee2d552c61da88e053c3)), it doesn't work either. BTW, my go version is "go1.8.1 linux/amd64" and os is "Ubuntu 14.04.3 LTS".

**Comment by karalabe** [comment]
@eliasnaur This one's an interesting. Seems some data corruption happens while crossing Go->Java on arm64?
