### ISSUE TITLE
Autocomplete in geth console doesn't work

### ISSUE THREAD

**Issue by robert-zaremba** [ethereum/go-ethereum#14678]
#### System information

Geth version: 1.6.5-stable
OS & Version: Linux
Commit hash : docker ethereum/client-go:v1.6.5

#### Expected behaviour
ETH console, after `geth attach` will provide autocomplete

#### Actual behaviour
The autocomplete functionality doesn't work (pressing TAB inserts TAB character).

#### Steps to reproduce the behaviour

1. Build the docker image from the latest from official stable release (ethereum/client-go:v1.6.5)
2. Run the docker: `docker.io/ethereum/client-go`
3. Enter to the docker shell: `docker exec -it your-container-id /bin/sh`
4. Attach to the eth console: `geth attach`
5. Try pressing TAB for autocomplete

**Comment by fjl** [comment]
This is a known issue with docker.

**Comment by robert-zaremba** [comment]
How does related to docker? It shouldn't.

**Comment by fjl** [comment]
I can confirm that auto-complete works almost everywhere else. It specifically does not work with docker exec. I'm suspecting a bug in docker, but feel free to dig deeper.

**Comment by robert-zaremba** [comment]
I don't think it's a bug in docker.
If I install `ethereum-console` with npm (in same docker machine) then 
autocomplete works.

**Comment by karalabe** [comment]
It works on my machine and docker instance

**Comment by karalabe** [comment]
What version of docker are you using? I am

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:17:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:17:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by robert-zaremba** [comment]
```
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-6.gitae7d637.fc25.x86_64
 Go version:      go1.7.4
 Git commit:      ae7d637/1.12.6
 Built:           Mon Jan 30 16:15:28 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-6.gitae7d637.fc25.x86_64
 Go version:      go1.7.4
 Git commit:      ae7d637/1.12.6
 Built:           Mon Jan 30 16:15:28 2017
 OS/Arch:         linux/amd64
```

Do you think the docker version might be a problem here?

**Comment by robert-zaremba** [comment]
BTW: I'm using Fedora 25

**Comment by robert-zaremba** [comment]
I've installed latest `docer-ce` (community edition) and everything works fine.
Thanks for tips and checks!

**Comment by elpaxoudis** [comment]
```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:37:39 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:36:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

With this docker version autocomplete does not work for me.

**Comment by jaydp17** [comment]
It doesn't work with
```sh
$ docker exec -it your-container-name sh
$ geth attach
```

but if you directly open console, it works
```sh
$ docker exec -it your-container-name geth attach
```

**Comment by chech0x** [comment]
it works for me setting TERM enviroment variable with 'linux'

`docker exec -ti your-container-name -e TERM=linux geth attach`

**Comment by WyseNynja** [comment]
I'm seeing this same issue, but the suggested fixes of directly opening the consol and setting TERM do not work for me.

I'm installing geth 1.8.19+build16554+bionic from the PPA
