### ISSUE TITLE
Blockchain fully synced, balance still shows 0

### ISSUE THREAD

**Issue by shlomogoldblatt** [ethereum/go-ethereum#14676]
About a month ago bought some ether to test. Transaction checks out on etherscan. Wallet (both Ethereum and Mist) still show 0 balance. Re-installed a few times, re-downloaded blockchain (took me 1 week), still 0. Why? What can I do to fix this?
Address 0xf794fB00f06FBD673cE3DB5EB0339c1e78dD0c3b

<img width="568" alt="mistwallet" src="https://user-images.githubusercontent.com/29599977/27431418-c508f37a-574c-11e7-826f-dd763cc9ff90.PNG">

**Comment by karalabe** [comment]
Apparently you chain is not fully synced. I'm unsure what "-3398" blocks means in Mist, perhaps take it up with them, but it's definitely not sunced.

**Comment by shlomogoldblatt** [comment]
It means it is short 3398 blocks
