### ISSUE TITLE
Installer won't update $path on Windows 10 Home x64

### ISSUE THREAD

**Issue by gabefair** [ethereum/go-ethereum#14679]
#### System information
Windows 10.0.15063 Home, 64-bit

Geth version: 1.6.5-cf87713d
OS & Version: Windows 10 Home x64

#### Expected behaviour
Installer would update windows path as a part of the installer process.

#### Actual behaviour
Does not update path. 
![image](https://user-images.githubusercontent.com/2096785/27442068-3eb60182-573d-11e7-94bc-d349c1f0a78d.png)
See: https://superuser.com/q/1221772/109803

#### Steps to reproduce the behaviour
Run the installer on the specified system

#### Backtrace
No backtrace

**Comment by fjl** [comment]
It cannot update the path because of an internal limit. Sorry for the inconvenience.

**Comment by gabefair** [comment]
@fjl Can you provide instructions on your wiki on what the path should be so users could manually enter it?

**Comment by guisantos** [comment]
Hi, any update? Im running on the same issue.
Is it supposed to fix the issue or am I doing something wrong?
![image](https://user-images.githubusercontent.com/14335913/31913952-abe4a1b4-b827-11e7-86af-c3c1906a29d7.png)

**Comment by OneOfMany07** [comment]
And still there in 1.8.15
