### ISSUE TITLE
why cannot watch event

### ISSUE THREAD

**Issue by wangweihuazg** [ethereum/go-ethereum#14670]
#### System information

Geth version: `1.6`
OS & Version: Windows
Commit hash : (if `develop`)
I want to call  function from my contract by web3.js ,my contract :+1,and my contract in block 15: 
pragma solidity ^0.4.0;

contract testContract  {
    

    event onGasPrice(string price);
    event onGetGasPrice();
    event onReturn(string price);

    
    function GetGasPriceByEvent() {
        onReturn(msg.sender,"123");
    }

    function GetGasPrice() returns (string  ret){
        return "123";
    }

    function GetWebGasPrice() {
       onGetGasPrice();
    }  
}

my web3.js   code : 
web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
var wwhtest = web3.eth.contract(abi);
var myContr = wwhtest.at("0x5d51e18145c9e6d340427532b14fa19e178bc346");

var exampleEvent = myContr.onReturn({},{fromBlock: 14, toBlock: 16});
var ii = "rt";
ii = myContr.GetGasPrice.call();

let watcher =  function (err, result){
    if (err) {
        console.log(err);
        return;
    }
    console.log(result.args.price);
    ii = result.args.price;
    exampleEvent.stopWatching();
};
exampleEvent.watch(watcher);

myContr.GetGasPriceByEvent.call();

but after call myContr.GetGasPriceByEvent, i print block15, it's header bloom:
Header(69b4e8a132615898cd41dd9b9a4e6cf0716d20853644ed37f372b03a3f87616f):
[
        ParentHash:         93a283ab7e537911218745a0392ca7e910f7e54f730c606c7a783b41606adaf1
        UncleHash:          1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
        Coinbase:           d63d3f0e749993c1bd392ea071d6fb46a40e0479
        Root:               64da31869878bf3222c35340a3aa30026db3e387dd854a17dde1501f6d1deb9f
        TxSha               5b1585efcd1b8c1eac0179c4d6e2d8e98c253b5dddb14629b60099abd2d139b8
        ReceiptSha:         c91338c0f91714c456ae453e109f4eb91f9267b9ce693f58eef7babe261b1c97
        Bloom:              00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        Difficulty:         131072
        Number:             15
        GasLimit:           3187903
        GasUsed:            455610
        Time:               1496974047
        Extra:              ك▒geth▒go1.8.1▒windows
        MixDigest:      52a80b4e51e854e080e1a1f470ac857b49ef5a1aebf489809bc94f71db8fd667
        Nonce:              787e4ee79c1a99fe
]

logbloom data not build ,so  my event watch callback function not called; why

**Comment by stiv-yakovenko** [comment]
I observer the same, looks like a bug in the kernel for me.
