### ISSUE TITLE
How do I launch This Thing?!?

### ISSUE THREAD

**Issue by MotorCityCobra** [ethereum/go-ethereum#14684]
#### System information
I've on Ubuntu 16.04

This connects to mining pools?
Where is the mining pool information entered?
Where is my Ethereum wallet address entered?
If entered on the commandline, how exactly should that be written?
If stored in a config file, what format should the config file be in. Is there an example anywhere?

**Comment by fjl** [comment]
geth doesn't connect to mining pool. It's a full node on the Ethereum network. If you want to mine with a pool, use ethminer.

**Comment by MotorCityCobra** [comment]
Where do I set where the mining is connected to?
How do I launch the mining?
I've pulled up help and seen all the commands but it's not intuitive at all.
