### ISSUE TITLE
Blockchain fully synced, balance still 0

### ISSUE THREAD

**Issue by Danilazz** [ethereum/go-ethereum#14689]
#### System information

Geth version: `0.8.10`
OS & Version: OSX
Commit hash : (if `develop`)

#### Actual behaviour
my wallet is 0xBa3A144B50194554b8F1c0cDeDa6c0ad6ad98885
here the balance is 8 etherium
https://etherscan.io/address/0xba3a144b50194554b8f1c0cdeda6c0ad6ad98885
but in a wallet the balance is 0.
What can I do to fix [this?](http://joxi.ru/l2ZK87zu048gAJ)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Wait for your chain to fully sync. It is obviously not fully synced, I don't know what and where Mist displays this info. You cn check the geth logs to see the block you're at, but i've no idea where Mist puts these either.
