### ISSUE TITLE
Wrong path generated for ipc file (windows 64 bit)

### ISSUE THREAD

**Issue by edocalia** [ethereum/go-ethereum#14696]
#### System information
Geth version: `1.6.6`
OS & Version: Windows 10
Commit hash : (if `develop`)

#### Expected behaviour
Creation of the IPC file in the specified folder

#### Actual behaviour
The IPC path built always includes a "\\.\pipe\" before the path passed as argument. It gives no error, but the file is not created anywhere.
I tried with absolute or relative path, and also eliminating the --ipcpath argument. The path it tries to open is always wrong with the \\.\pipe\ string

#### Steps to reproduce the behaviour
geth --ipcpath whatever\geth.ipc --datadir somedatadir -dev console

#### Backtrace

````
[backtrace]
````
![capture](https://user-images.githubusercontent.com/3370901/27512030-43504d26-5934-11e7-9dbe-b47d40a87e40.JPG)

**Comment by fjl** [comment]
IPC uses named pipes on windows. Pipe names do not correspond to files on disk and must start with \\.pipe
