### ISSUE TITLE
Initial synchonization fails repeatedly

### ISSUE THREAD

**Issue by Outerheaven11** [ethereum/go-ethereum#14691]
#### System information

Geth version: 1.6.6 stable
OS & Version: Windows 10

#### Expected behaviour

Initial synchronization of the blockchain

#### Actual behaviour

Initial synchronization begins and progresses for varying amounts of time until I get one of these errors:

"Synchronisation failed, retrying err="block download canceled (request)" or
"Synchronisation failed, retrying err="header processing canceled (requested)"

and there is no additional progress.  Cancelling the task and restarting produces the same result eventually.  

#### Steps to reproduce the behaviour

Type in "geth --rpc --fast --cache=1024" at command line in Windows

**Comment by DengMins** [comment]
@Outerheaven11 Have you solved this problem?

**Comment by Outerheaven11** [comment]
I never did, sorry.  I ended up using Miningpoolhub and Awesome Miner.
