### ISSUE TITLE
geth does not sync ropsten blockchain

### ISSUE THREAD

**Issue by porfavorite** [ethereum/go-ethereum#14699]
#### System information

Geth version: `1.6.6`
OS & Version: Linux

#### Expected behaviour

geth starts downloading ropsten blockchain

#### Actual behaviour

That's what I get.

```
WARN [06-25|23:43:29] No etherbase set and no accounts found as default 
INFO [06-25|23:43:29] Starting peer-to-peer node               instance=Geth/v1.6.6-stable-10a45cb5/linux-amd64/go1.8.1
INFO [06-25|23:43:29] Allocated cache and file handles         database=/home/osboxes/.ethereum/testnet/geth/lightchaindata cache=1024 handles=1024
INFO [06-25|23:43:29] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Metropolis: 9223372036854775807 Engine: ethash}"
INFO [06-25|23:43:29] Disk storage enabled for ethash caches   dir=/home/osboxes/.ethereum/testnet/geth/ethash count=3
INFO [06-25|23:43:29] Disk storage enabled for ethash DAGs     dir=/home/osboxes/.ethash                       count=2
INFO [06-25|23:43:29] Loaded most recent local header          number=0 hash=419410…ca4a2d td=1048576
INFO [06-25|23:43:29] Starting P2P networking 
INFO [06-25|23:43:31] UDP listener up                          self=enode://d32682c1580d1b21e0413cf9dbd1cfbb520ded24b11148b3d01a1272ba45ac6491cd5c325f8a3d4944bc2b0a70a9df6cb0318ba6d650661a80242c52ea7e93a6@[::]:30303
WARN [06-25|23:43:31] Light client mode is an experimental feature 
INFO [06-25|23:43:31] HTTP endpoint opened: http://127.0.0.1:8545 
INFO [06-25|23:43:31] RLPx listener up                         self=enode://d32682c1580d1b21e0413cf9dbd1cfbb520ded24b11148b3d01a1272ba45ac6491cd5c325f8a3d4944bc2b0a70a9df6cb0318ba6d650661a80242c52ea7e93a6@[::]:30303
INFO [06-25|23:43:31] IPC endpoint opened: /home/osboxes/.ethereum/testnet/geth.ipc 
```
And nothing else. It's just stuck here.

#### Steps to reproduce the behaviour
I run this
`geth --testnet --syncmode=light --rpc --rpcapi db,eth,net,web3,personal --cache=1024  --rpcport 8545 --rpcaddr 127.0.0.1 --rpccorsdomain "*" --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303"`

**Comment by karalabe** [comment]
Please don't specify a bootnode explicitly. That discovery port (30303) is for full nodes, light clients use discovery V5, running on a different port, hence why you're unable to connect to anyone.

Simply running `geth --testnet` started syncing for me in a matter of seconds.

**Comment by gernotpokorny** [comment]
geth --testnet --rpc --rpccorsdomain "null" --syncmode=light

does not sync for me. I restarted multiple times.

**Comment by kwaazaar** [comment]
Same here, no sync. Does it just take a while to get running?
