### ISSUE TITLE
Error in geth.git on ubuntu 17.04

### ISSUE THREAD

**Issue by leder11011** [ethereum/go-ethereum#14695]
#### System information

Geth version: `1.6.7-unstable`
OS & Version: Linux
Commit hash : (if `develop`) 78c04c920d07e65864f781fb5c6e5d77435d7aa0

#### Expected behaviour
do a blockchain sync

#### Actual behaviour
INFO [06-24|18:45:02] Committed new head block                 number=3923567 hash=e22ad6…3ddaa4
ERROR[06-24|18:45:02] Impossible reorg, please file an issue   oldnum=3923567 oldhash=e22ad6…3ddaa4 newnum=3923567 newhash=e22ad6…3ddaa4

#### Steps to reproduce the behaviour
do a blockchain sync

#### Backtrace

````
[backtrace]
````

**Comment by spinteractive** [comment]
I'm getting the same error during sync on Windows Geth:

INFO [06-25|02:01:31] Committed new head block                 number=3926283 hash=f60445…ae84ab
ERROR[06-25|02:01:34] Impossible reorg, please file an issue   oldnum=3926283 oldhash=f60445…ae84ab newnum=3926283 newhash=f60445…ae84ab

can someone advise?

**Comment by kuyote** [comment]
Same issue here, any update? 
ERROR[07-05|15:29:38] Impossible reorg, please file an issue   oldnum=3979943 oldhash=20360f.8458d5 newnum=3979943 newhash=20360f.8458d5
INFO [07-05|15:29:38] Imported new chain segment               blocks=2  txs=2427 mgas=0.615   elapsed=128.100ms mgasps=4.799  number=3980017 hash=a94605.4d5523 ignored=72
WARN [07-05|15:30:00] Synchronisation failed, retrying         err="state data download canceled (requested)"

**Comment by josh-richardson** [comment]
I've had the same issue here on Ubuntu 17.04, Amazon Linux, and CentOS. I've tried using the PPAs and compiling from source on several different hardware configurations, from a laptop class i7 4600U to a VPS with 32GB of RAM and 4 cores.

**Comment by daxorid** [comment]
I am experiencing this exact problem, on Kali-rolling, built from source using go1.8.3 linux/amd64, trying to sync the ropsten chain.
