### ISSUE TITLE
Killed after seconds

### ISSUE THREAD

**Issue by Marow** [ethereum/go-ethereum#14693]
#### System information

Geth version: `Geth/v1.6.5-stable-cf87713d/linux-amd64/go1.8.1`
OS & Version: Linux ubuntu

Everytime when i make "geth" after installing and follow your tutorial, i get kicked out and says "killed" right after normal "Imported new block headers"...

There is no error or anything

**Comment by MitchK** [comment]
Seems like the Linux OOM killer kills your application. 

I usually have this issue when hitting a hard memory limit.

**Comment by Marow** [comment]
So 2GB is not enaugh? I can easily upgrade it. How much is perfect? 4gb? And how much cores?

**Comment by Marow** [comment]
Thank you! 

Works!

Have now 4GB Memory and needs 30GB Storage.

**Comment by MitchK** [comment]
@winsvega by any chance, do you use the ```--cache``` parameter? ```--cache``` does only allocate memory for the cache, as the parameter name says. Geth will always use a little bit more memory than defined in the ```--cache``` parameter. Therefore, setting ```--cache``` too high may result Linux to kill your process.

Another option is to try using a swap file on your system. https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

**Comment by winsvega** [comment]
so having like 8 gb of free ram does not save you from this issue with cache ? even if you use --cache 2048 ?

**Comment by MitchK** [comment]
Hmm that is strange indeed. I was more talking more about if you would set the cache to the same size as your free memory. 

So perhaps swapping or more memory could help.

**Comment by EkremSel** [comment]
Have the same problem. 

Ubuntu 20.10
Geth 1.10.8
16 Ram

I disabled swap. 

This problem persist

**Comment by winsvega** [comment]
This is like 5 year old now. Is it still happening?

**Comment by dev-theuniweb** [comment]
I still have this problem, geth killed after 2 days running.

Server spec
CPU 4 core
RAM 8 GiB
Storage 1000 GiB

Command to start
nohup ./geth --syncmode "fast"  --cache 4096 --datadir "/data/ethdata"  --http=true  --http.addr 127.0.0.1 --http.port  8999  --allow-insecure-unlock  --http.api "web3,eth,net,personal,db,admin"  --http.corsdomain '"*"'  --ws=true --ws.api "web3,eth,net,personal,db,admin" --ws.origins '"*"'  --maxpeers=5000 &
