### ISSUE TITLE
Pending Balance on geth and open-ethereum-pool

### ISSUE THREAD

**Issue by Marow** [ethereum/go-ethereum#14709]
#### System information

Geth version: Version: 1.6.5-stable
OS & Version: Linux Ubuntu 16.04

#### Expected behaviour
Want to payout pending balance to miner

#### Actual behaviour
Nothing. Payout says `No payees that have reached payout threshold`
So pending balance is on the account like 4-5 Hours and doing nothing.

#### Steps to reproduce the behaviour
Starting `./build/bin/open-ethereum-pool payouts.json` to send payouts from my geth account to the miner account.

When i check the Balance in geth, i had 12.91259 there.

So i dont know, why its pending and doesnt change the status or anything.
Sorry if i am wrong here. I find much of these things on google, but open-ethereum-pool closed there issues and now i cannot read if anyone have same problems.

Hope you can help me. Cause geth has the balance but dont payout to miners

**Comment by ligi** [comment]
Sounds more like an issue you should open at  open-ethereum-pool - why do you think this is an issue of geth?

**Comment by Marow** [comment]
I already opened an ask there, but i mean no one can help me... and open-ethereum-pool closed issues :/ 

So you mean, go-ethereum is not the problem? The problem is open-ethereum-pool?
