### ISSUE TITLE
Upgradedb failed or not?

### ISSUE THREAD

**Issue by arifoxs** [ethereum/go-ethereum#14700]
#### System information

Geth version: `1.6.6-stable-10a45cb5`
OS & Version: 3.8.0-44-generic #66~precise1-Ubuntu SMP Tue Jul 15 04:01:04 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
PC :  xeon four cores, 12GB of ram, and WD blue 500GB
#### Expected behaviour
I hope my server can sync, and mine ethereum with CPU mine, I use 

`./geth --datadir data --etherbase 0 --minerthreads=2 --cache=2048 --mine 
`
but i always fail sync,

```
WARN [06-26|07:10:37] Node data write error                    err="state node 6e1378â€¦835548 failed with all peers (9 tries, 9 peers)"
WARN [06-26|07:10:37] Rolled back headers                      count=2048 header=418449->416401 fast=381375->381375 block=0->0
WARN [06-26|07:10:37] Synchronisation failed, retrying         err="state node 6e1378â€¦835548 failed with all peers (9 tries, 9 peers)"

```

I use `cat geth_log | grep WARN`
To view 'WARN' messages only,
#### Actual behaviour

I have seen some issues, one of those issues there is suggesting to run upgradedb or removedb, is it helpful or not?

Https://github.com/ethereum/go-ethereum/issues/3585

But i get the output

> INFO [06-26|08:34:28] Imported new block receipts              count=24   elapsed=9.117ms   number=692032 hash=43e3c8…15839b ignored=0
> INFO [06-26|08:34:30] Imported new block receipts              count=6    elapsed=7.622ms   number=692038 hash=5ff26e…074e52 ignored=0
> INFO [06-26|08:34:30] Imported new block headers               count=0    elapsed=8.160ms   number=697784 hash=10e4e9…dae747 ignored=192
> INFO [06-26|08:34:33] Imported new state entries               count=51   flushed=44  elapsed=2.341ms   processed=393663 pending=1322  retry=4    duplicate=212 unexpected=498
> WARN [06-26|08:34:35] Synchronisation failed, retrying         err="block body download canceled (requested)"
> WARN [06-26|08:35:09] Synchronisation failed, retrying         err="block download canceled (requested)"
> 

Is that okay?
Geth still running

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Sync can take a while. You'll need to wait it out. On an mechanical disk machine it can take a **lot** of time (many hours). Lastly I would not recommend CPU mining on mainnet, it just isn't worth it with all the GPU capacity present on the network.

**Comment by covex-nn** [comment]
@arifoxs I stoped --fast sync twice after i got something like this:

> WARN [08-25|15:01:31] Stalling state sync, dropping peer       peer=0ec8d7a4b0d6f71f
> WARN [08-25|15:01:31] Stalling state sync, dropping peer       peer=bde01afcc608c981
> ... 23 WARNs total about stalling state sync
> WARN [08-25|15:01:37] Stalling state sync, dropping peer       peer=6d97e801159e5268
> WARN [08-25|15:01:37] Stalling state sync, dropping peer       peer=2a6d91d7de60e537
> WARN [08-25|15:01:37] Node data write error                    err="state node d023e6:b6cd3e failed with all peers (1 tries, 1 peers)"

on third time, on 4143053 block, i decided to wait and after 50 minutes sync resumed
