### ISSUE TITLE
Typo in document

### ISSUE THREAD

**Issue by tangyouze** [ethereum/go-ethereum#14702]
In page https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts

There's a line to get accounts with rpc, the last quote ' is not in the correct place

> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1} http://127.0.0.1:8545'

and the following might be correct

> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' http://127.0.0.1:8545

Here's some try

> ➜  ~ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1} http://127.0.0.1:8545'
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
➜  ~ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' http://127.0.0.1:8545
{"jsonrpc":"2.0","id":1,"result":["0x5e168bf1367461a4605e10205b65753cc950d67c","0x2b8270ca2d49b402b42cd9f7dcaec598ee7e2daf"]}

**Comment by karalabe** [comment]
Thanks, fixed!
