### ISSUE TITLE
How and where is the reorg() triggered

### ISSUE THREAD

**Issue by OniReimu** [ethereum/go-ethereum#14705]
#### System information

Geth version: `geth 1.5.9`
OS & Version: Linux/OSX
Commit hash : (if `develop`)

I've posted the same issue on gitter but no response sofar. Soorry for repost the message here again.

In what way geth will trigger the reorg() to reorganize the chain in order to resolve the unexpeced forks? I've lookup the source code in core/blockchain.go - Raw 841 showing the WriteBlock() calling the reorg(), and WriteBlock() is called by InsertChain() in Raw 984 right after the ValidateBlock() and ValidateState(). If the latest incoming block does not satisfy one of the rules then error poping up, WriteBlock() will not run in this case. However, canonical chain reorganization should imply that the latest incoming block shouldn't pass those two validations, shouldn't it? Then How is the reorg() triggered?

To be more extended, if I want to do a 51% attack within my private chain, I have locally tampered some data in the local database and there is only one node I tampered mining. Then other nodes of course rejected the latest block because it is seen as invalid. But as times and mining go, would other nodes automatically change their canonical chain to the chain the node I tampered is mining on sometime in the future?
As currently the chain that the mining node is mining on has been 50+ blocks far beyond from the old canonical chain where other nodes handle. But there is totally no further behaviour to reorganize the canonical chain being seen except for the constantly invalid block error-reminding when other nodes intend to sync.

**Comment by karalabe** [comment]
Nodes will never import a block that fails validation. A 51% attack consists of a 51% of the miners forking off from a block in the past and creating a new chain that eventually beats the "current canonical" chain in total difficulty. A reorg is done only if a block being imported on a side fork leads to a higher total difficulty on that particular fork than the canonical fork. The blocks nonetheless still need to be valid.

**Comment by cryptowhl** [comment]
@karalabe Hi, when chain reorg occurs in Ethereum, the common way is first find common block, insert the block with the more total difficuty, and keep the transaction within the old chain but not within the new chain back to txpool. my question : is it nessasary to offset state change triggered by these tx？ if so, where corresponding source code in go-ethereum?
