### ISSUE TITLE
Port Makefile to make.go

### ISSUE THREAD

**Issue by yenhwash** [ethereum/go-ethereum#14703]
#### System information

Geth version: latest
OS & Version: Windows
Commit hash : (if `develop`)

#### Expected behaviour
Write a make.go for build automation

#### Actual behaviour
We are dependent on gnu make specially on Windows. Why not leverage golang - i.e. port Makefile to make.go

#### Backtrace

````
[backtrace]
````

**Comment by Bo-Ye** [comment]
I think the file you required is already present and it's in the build folder called ci.go, not make.go
You can build the go-ethereum project without Makefile.

You can do as follows:
1. export GOPATH = <project_folder>/go-ethereum/build/_workspace
2. go to <project_folder>/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum
3. run command: go run build/ci.go install ./cmd/geth

Done, ci.go contains some parameters to customise build as well.

**Comment by yenhwash** [comment]
@Bo-Ye What I am proposing is to write make.go which will setup the required environments i.e. get ride of build/env.sh (and move it to make.go) and use build/ci.go as much as possible.

To build go-ethereum:

1) Install Go.
2) cd to the root of the go-ethereum source (where this file is)
3) Run:
   $ go run make.go
4) The compiled binaries should now be in the "build/bin" subdirectory:

**Comment by yenhwash** [comment]
After installing mingw (gcc required to build secp256k1 go binding) - one can build geth and related binaries without using gnu make on windows.
To build go-ethereum on windows:
1) Install Go.
2) Install mingw `choco install mingw` in an administrator command prompt
2) cd to the root of the go-ethereum source
3) Run `go run build\ci.go install`
4) The compiled binaries should now be in the "build\bin" subdirectory

**Comment by yenhwash** [comment]
build\ci.go is good enough to build geth and associated binaries on windows
