### ISSUE TITLE
Geth Mining Death Spiral when internet connectivity is lost

### ISSUE THREAD

**Issue by stephantual** [ethereum/go-ethereum#1471]
Steps: 
- Use Geth to mine (with Ethminers)
- Wait till everything is working nicely
- Pull ethernet for around 1m

Results:
- Geth mine on its own chain. Forever, it never recovers.

Expected results:
- Geth sees the heavier chain 'outside' and switching to mining that main, 'real' chain.

I had raised this before but it's now a real problem so close to Frontier as the work around is restarting the client just in case every hour so that no more than an hour of work can be lost at any given time.

I was able to reproduce this manually (by pulling the aforementioned plug), but also had it happen to me several time when my ISP went down (which happens a lot where I am).

Paste bin: http://pastebin.com/jGb5W5Ry
(my router logs indicate I lost internet at 23:26, which matches the above).

**Comment by Gustav-Simonsson** [comment]
This reminds me of testing in the telecom world, where it's standard to pull the network cable and/or power cables and verify what happens :)

**Comment by conradjohnson** [comment]
Ah... that's why mine keep switching to their own local chain.  Nice find.

**Comment by skithuno** [comment]
I think something similar happened to me with the latest master build. Was mining fine for hours, then I split off into my own chain and it wouldn't sync with the main chain:

I0723 08:18:32.406666    7670 worker.go:503] commit new work on block 969094 with 13 txs & 0 uncles. Took 729.567822ms
I0723 08:18:37.988125    7670 chain_manager.go:678] imported 1 block(s) (0 queued 0 ignored) including 22 txs in 207.966222ms. #969094 [c9daeed9 / c9daeed9]
I0723 08:18:38.036445    7670 worker.go:503] commit new work on block 969095 with 4 txs & 0 uncles. Took 48.122704ms
I0723 08:18:47.655803    7670 chain_manager.go:678] imported 1 block(s) (0 queued 0 ignored) including 22 txs in 156.149062ms. #969094 [432cce1c / 432cce1c]
I0723 08:28:22.053277    7670 remote_agent.go:107] Work was submitted for 86dd7cf4ef20855764def431fdd09725c4210acba69bae5ff11270ca1293d4ef but no pending work found
I0723 08:40:02.670711    7670 worker.go:318] 🔨  Mined block (#969095 / f06f7ec0). Wait 5 blocks for confirmation
I0723 08:40:09.213085    7670 worker.go:503] commit new work on block 969096 with 24 txs & 1 uncles. Took 6.546302469s
I0723 08:40:10.140476    7670 worker.go:503] commit new work on block 969096 with 24 txs & 1 uncles. Took 238.614162ms
I0723 09:17:22.019496    7670 worker.go:318] 🔨  Mined block (#969096 / 34021b91). Wait 5 blocks for confirmation
I0723 09:17:24.302931    7670 worker.go:503] commit new work on block 969097 with 20 txs & 0 uncles. Took 2.283914914s
I0723 09:17:24.512383    7670 worker.go:503] commit new work on block 969097 with 20 txs & 0 uncles. Took 207.400175ms
I0723 09:53:13.040997    7670 worker.go:318] 🔨  Mined block (#969097 / 61ac069e). Wait 5 blocks for confirmation
I0723 09:53:20.788983    7670 worker.go:503] commit new work on block 969098 with 100 txs & 0 uncles. Took 7.748436758s
I0723 09:53:21.224545    7670 worker.go:503] commit new work on block 969098 with 100 txs & 0 uncles. Took 434.462536ms
I0723 10:03:07.416940    7670 remote_agent.go:107] Work was submitted for aaba71797dd081ca682eb03c94714ef29a3b539bc10dabc5749ed3f75dac5d91 but no pending work found

**Comment by awrelll** [comment]
Any updates on this issue ? The spiral got me too :( OUCH!

**Comment by fjl** [comment]
This should be solved by now with the above PR.
