### ISSUE TITLE
initial sync unusably slow

### ISSUE THREAD

**Issue by akosmaroy** [ethereum/go-ethereum#14712]
#### System information

Geth version: `geth version`

```
$ geth version
Geth
Version: 1.6.6-stable
Git Commit: 10a45cb59bd9bc9f717817afc029a57b222e558d
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.8

```

OS & Version: Windows/Linux/OSX

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

```

Commit hash : (if `develop`)

#### Expected behaviour

geth after initial startup should sync in a reasonable timeframe, so that it can be used.

or that one could download a recent snapshot and import it, and then sync the rest.

#### Actual behaviour

geth crashes on a regular basis due to running out of file descriptors. thus the --fast option, which only works with a clean setup, only speeds things up until the first crash. on each start afterwards, sync will be slow.

currently it does cca 1000 blocks / 15 minutes, that is  **the sync speed is cca 4000 blocks / hour**. as I have cca. 300000 blocks left, the remaining sync would take 72 more hours.

 it will also be full of rolled back / failed syncs like this one:

```
WARN [06-27|07:59:24] Rolled back headers                      count=732 header=3648398->3647684 fast=3646096->3646096 block=0->0
WARN [06-27|07:59:24] Synchronisation failed, dropping peer    peer=5ff56dd7517e145f err="retrieved hash chain is invalid"
WARN [06-27|07:59:39] Synchronisation failed, dropping peer    peer=697c8a28c4b39423 err="action from bad peer ignored"
```
and the following:

```
WARN [06-27|08:08:28] Lied about chain head                    peer=d9794b3d00ccee32 reported=2131871 found=2132047
WARN [06-27|08:08:28] Synchronisation failed, dropping peer    peer=d9794b3d00ccee32 err="peer is stalling"
WARN [06-27|08:08:58] Synchronisation failed, retrying         err="block download canceled (requested)"

WARN [06-27|08:09:26] Synchronisation failed, retrying         err="block download canceled (requested)"
WARN [06-27|08:10:07] Synchronisation failed, retrying         err="block download canceled (requested)"

```

re file handles:

```
$ ulimit -n
4096
```
but still at startup I get:

`INFO [06-27|07:53:17] Allocated cache and file handles         database=/home/akos/.ethereum/geth/chaindata cache=1024 handles=1024
`
(note: handles=1024)

also see:

```
$ lsof | awk '{print $1}' | uniq -c | sort -rn | head -n 1
  16170 geth
```

only torrents that appear to offer a recent state are stale and cannot be used. so one can't speed up that way either.

#### Steps to reproduce the behaviour

install geth from the ubuntu PPA and try to start to use it

#### Backtrace

````
n/a
````

**Comment by gtirloni** [comment]
I've seen the same error message but the eth.syncing.currentBlock keeps increasing.

**Comment by pebwindkraft** [comment]
same here, after three days of running:
ulimit -n
--> 1024
lsof | awk '{print $1}' | uniq -c | sort -rn | head -n 1
--> 54988 geth
I summarized a more detailed status here: https://github.com/ethereum/go-ethereum/issues/14571
