### ISSUE TITLE
geth crashes after receiving a ^C

### ISSUE THREAD

**Issue by Biep** [ethereum/go-ethereum#14714]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
I had geth --mine running, and it was importing many gigabytes of block receipts, bloch headers, state entries..
After several hours of running I gave a ^C to stop it.
 
#### What did you expect to see?
 A graceful shutdown.

#### What did you see instead?
^CINFO [06-27|18:00:33] Got interrupt, shutting down... 
INFO [06-27|18:00:33] IPC endpoint closed: /home/biep/.ethereum/geth.ipc 
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 356749 [running]:
sync.(*WaitGroup).Wait(0xc42073c0c8)
	/usr/lib/go-1.8/src/sync/waitgroup.go:133 +0xd8
github.com/ethereum/go-ethereum/core.(*BlockChain).Stop(0xc42073c000)
	/build/ethereum-uBciBG/ethereum-1.6.6+build10111+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:605 +0x6c
github.com/ethereum/go-ethereum/eth.(*Ethereum).Stop(0xc4200636c0, 0xc42015cde0, 0xc42156bf58)
	/build/ethereum-uBciBG/ethereum-1.6.6+build10111+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:391 +0x40
github.com/ethereum/go-ethereum/node.(*Node).Stop(0xc420268000, 0x0, 0x0)
	/build/ethereum-uBciBG/ethereum-1.6.6+build10111+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:502 +0x21c
created by github.com/ethereum/go-ethereum/cmd/utils.StartNode.func1
	/build/ethereum-uBciBG/ethereum-1.6.6+build10111+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:71 +0x147
 
#### System details

Version: 1.6.6-stable
Go Version: go1.8.1
OS: linux
uname -sr: Linux 4.4.0-81-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

**Comment by fjl** [comment]
This is tracked at https://github.com/ethereum/go-ethereum/issues/1816
