### ISSUE TITLE
Please enable network time synchronisation in system settings

### ISSUE THREAD

**Issue by Marow** [ethereum/go-ethereum#14717]
#### System information

Geth version: 1.6.5-stable
OS & Version: Linux Ubuntu 16.04

I get this Error on my geth... 

```
I0627 13:01:40.338572 p2p/discover/ntp.go:58] -------------------------------------------------------------------------------
I0627 13:01:40.338587 p2p/discover/ntp.go:59] System clock seems off by 22.347762561s, which can prevent network connectivity
I0627 13:01:40.338596 p2p/discover/ntp.go:60] Please enable network time synchronisation in system settings
I0627 13:01:40.338601 p2p/discover/ntp.go:61] -------------------------------------------------------------------------------
```

And spamming very much time... how can i fix it?
I find a tutorial for windows but not for Ubuntu with only terminal

**Comment by fjl** [comment]
You can use `timedatectl set-ntp true` to enable NTP on Ubuntu.

**Comment by Marow** [comment]
I tried `timedatectl set-ntp true` but there is doing nothing...

` Network time on: yes
NTP synchronized: no
 RTC in local TZ: no`

**Comment by karalabe** [comment]
If you open up the "Time and Date" settings app (just search for it from the start menu), there will be a radio button to set the time `Automatically from the Internet`. That should do it.

**Comment by Marow** [comment]
I have only Terminal Ubuntu Server.

**Comment by fjl** [comment]
In theory, the `NTP synchronized: no` should change to yes after a while. If that doesn't happen, something is wrong with NTP on the machine.

**Comment by dannywillems** [comment]
I have the same issue. The node has been running for several months and stopped with the message several days ago. I had the same issue when I first ran the node but I didn't remember what was the solution.

**Comment by dannywillems** [comment]
```
sudo apt-get update
sudo apt-get install ntp
sudo service ntp start
```
seems to resolve the issue.

**Comment by karalabe** [comment]
Sweet :) Closing then.

**Comment by dannywillems** [comment]
@karalabe I don't know if it fixes @Marow issue... Maybe it's not the same solution.

**Comment by karalabe** [comment]
Aaah, didn't see that there are two different people with this issue :D

**Comment by rakeshkumar33** [comment]
@karalabe i got same issue in linux 
@marow 
time and date seetings are automatic from internet in my system 
need some help

**Comment by apa7** [comment]
Ubuntu12 can't fix it

**Comment by sourav1547** [comment]
The following commands which is just the combines the two above mentioned approach worked for me
`sudo apt-get update
sudo apt-get install ntp
sudo service ntp start
timedatectl set-ntp true`

*NOTE: You have to wait for few minutes (approximately 3 minutes in my case) for `NTP synchronized: no` to switch to `NTP synchronized: yes`*

**Comment by adamschmideg** [comment]
Seems to be solved, closing again
