### ISSUE TITLE
where does the variable of smart contract store?

### ISSUE THREAD

**Issue by jiebanghan** [ethereum/go-ethereum#14713]
we all know that we can write smart contract with solidity in ethereum such as:

 mapping(bytes32 => bytes32) private  userPasswds ;
    event RecordReturnResult(bool res);

    /// @dev new the pair of user and password to the array here
    function newPair(string user, string password)  returns (bool) {      
        bytes32  sha3_user = sha3(user);
        bytes32  sha3_password = sha3(password);
        bool res = true;
        if (userPasswds[sha3_user] > 0) {
            res = false;
            RecordReturnResult(res);
            return res;
        }           
        else{
            userPasswds[sha3_user] = sha3_password;
            res = true;
            RecordReturnResult(res);
            return res;
        }      
    }
I just want to know where the variable store? the varialbe include

    mapping(bytes32 => bytes32) private  userPasswds ;
    event RecordReturnResult(bool res);bytes32  sha3_user = sha3(user);
    bytes32  sha3_password = sha3(password);
    bool res = true;
are them be stored in block chain or leveldb or other places? thank you.

**Comment by karalabe** [comment]
Solidity storage variables are mapped to hash keys according to http://solidity.readthedocs.io/en/develop/miscellaneous.html#layout-of-state-variables-in-storage. The keys are stored in a Merkle Patricia trie for the specific account (and the main state trie contains all the accounts). To access them you'll need to use https://godoc.org/github.com/ethereum/go-ethereum/core#BlockChain and access the state associated with a block, which will give you the methods to iterate over an account's storage entries.

Note however, that there's no direct information available that can tell you which hash corresponds to which contract field. That depends on a lot of stuff and the Solidity compiler.

**Comment by jiebanghan** [comment]
thank you very much
