### ISSUE TITLE
eth_getTransactionByHash returns ophaned transaction details.

### ISSUE THREAD

**Issue by richiela** [ethereum/go-ethereum#14722]
#### System information

Geth version: 1.6.6
OS & Version:  Ubuntu 16.04
Commit hash : (if `develop`)

#### Expected behaviour
Related to Disappearing transactions #14719
We sit in a loop and call eth_getTransactionByHash to check if a tx has been confirmed or orphan.  We expected to get the transaction info along with blocknumber if confirmed, and a null when orphaned.  There are cases where the tx stays in the "transaction pool" even though a higher nonce has been used.
If eth_getTransactionByHash is called on a hash that is has been orphaned and is never going to confirm, it should return null.

#### Actual behaviour
It returns the tx with null blockheight

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
Could you check if it's present in `txpool.content.pending[<address>]` or `txpool.content.queued[<address>]`

**Comment by richiela** [comment]
It is in neither queue.

**Comment by holiman** [comment]
Thanks, could you also check ` web3.version` ?

**Comment by richiela** [comment]
> web3.version
{
  api: "0.18.1",
  ethereum: "0x3f",
  network: "1",
  node: "Geth/v1.6.6-stable/linux-amd64/go1.8",
  whisper: undefined,
  getEthereum: function(callback),
  getNetwork: function(callback),
  getNode: function(callback),
  getWhisper: function(callback)
}

**Comment by holiman** [comment]
@karalabe PTAL
