### ISSUE TITLE
Invalid nonce provided will still return a transaction ID

### ISSUE THREAD

**Issue by axelay** [ethereum/go-ethereum#14721]
#### System information

Geth version: `Version: 1.6.6-stable`
OS & Version: Ubuntu 16.04.2 LTS

#### Expected behaviour
Passing invalid nonce in the sendTransaction should return false or invalid transaction

#### Actual behaviour
Transaction ID is generated and returned to the caller - yet the transaction will disappear from txpool.content.pending, txpool.content.queued and from getTransaction after a few minutes.

#### Steps to reproduce the behaviour
Send a transaction with a nonce higher than what getTransactionCount(address) returns

**Comment by axelay** [comment]
The reason for this is that I am trying to set the nonce myself instead of letting Geth handle it. And I am trying to cover every case scenario to prevent my counter from going haywire.

**Comment by holiman** [comment]
A higher nonce isn't technically invalid, it's just non-executable for the moment. So it should wind up in the `queued`, as opposed to `pending`.

**Comment by holiman** [comment]
However, the "transaction will disappear from txpool.content.pending, txpool.content.queued and from getTransaction after a few minutes"  sounds like a bug to me.

**Comment by axelay** [comment]
Managed to reproduce it:

> eth.sendTransaction({from: "0x29d1996cc47844fc1d85836d5e1d2c2b3b27fe6b", to: "0x5225b3ab49ea3e96eb08b61bda19b1cee4a82569", value: web3.toWei(0.001, 'ether'), nonce: 10})
"0x5c9824ee7a52a5fb3531016948a9d40259df17168ddb035826fc2ddfd8899803"
> eth.getTransaction("0x5c9824ee7a52a5fb3531016948a9d40259df17168ddb035826fc2ddfd8899803")
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  blockNumber: null,
  from: "0x29d1996cc47844fc1d85836d5e1d2c2b3b27fe6b",
  gas: 90000,
  gasPrice: 21768734821,
  hash: "0x5c9824ee7a52a5fb3531016948a9d40259df17168ddb035826fc2ddfd8899803",
  input: "0x",
  nonce: 10,
  r: "0xf60699ca308f4e1702086046e90074eed2088e661b5c84f4ea63fc291593f800",
  s: "0x34d210040b8f75cd3b20ad03f7b8787739e43faa61972b5a86dc1d6f410c929",
  to: "0x5225b3ab49ea3e96eb08b61bda19b1cee4a82569",
  transactionIndex: 0,
  v: "0x25",
  value: 1000000000000000
}
> txpool.content.queued["0x29d1996cc47844fc1d85836d5e1d2c2b3b27fe6b"]
{
  10: {
    blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
    blockNumber: null,
    from: "0x29d1996cc47844fc1d85836d5e1d2c2b3b27fe6b",
    gas: "0x15f90",
    gasPrice: "0x511848865",
    hash: "0x5c9824ee7a52a5fb3531016948a9d40259df17168ddb035826fc2ddfd8899803",
    input: "0x",
    nonce: "0xa",
    r: "0xf60699ca308f4e1702086046e90074eed2088e661b5c84f4ea63fc291593f800",
    s: "0x34d210040b8f75cd3b20ad03f7b8787739e43faa61972b5a86dc1d6f410c929",
    to: "0x5225b3ab49ea3e96eb08b61bda19b1cee4a82569",
    transactionIndex: "0x0",
    v: "0x25",
    value: "0x38d7ea4c68000"
  }
}
> txpool.content.pending["0x29d1996cc47844fc1d85836d5e1d2c2b3b27fe6b"]
undefined

Then after what appears to be 60s:
> txpool.content.queued["0x29d1996cc47844fc1d85836d5e1d2c2b3b27fe6b"]
undefined
> txpool.content.pending["0x29d1996cc47844fc1d85836d5e1d2c2b3b27fe6b"]
undefined
> eth.getTransaction("0x5c9824ee7a52a5fb3531016948a9d40259df17168ddb035826fc2ddfd8899803")
null

**Comment by holiman** [comment]
THanks. 1 minute is exactly the expiration interval here: 
```
// expirationLoop is a loop that periodically iterates over all accounts with
// queued transactions and drop all that have been inactive for a prolonged amount
// of time.
func (pool *TxPool) expirationLoop() {
	defer pool.wg.Done()

	evict := time.NewTicker(evictionInterval)
	defer evict.Stop()

	for {
		select {
		case <-evict.C:
			pool.mu.Lock()
			for addr := range pool.queue {
				if time.Since(pool.beats[addr]) > pool.config.Lifetime {
					for _, tx := range pool.queue[addr].Flatten() {
						pool.removeTx(tx.Hash())
					}
				}
			}
			pool.mu.Unlock()

		case <-pool.quit:
			return
		}
	}
}
```

**Comment by holiman** [comment]
It appears we only set the heartbeat-time if it's promoted, not if it's passed directly to the `queue`. Only here: https://github.com/ethereum/go-ethereum/blob/master/core/tx_pool.go#L556
