### ISSUE TITLE
Interactive console not available on Ubuntu desktop

### ISSUE THREAD

**Issue by anddero** [ethereum/go-ethereum#14728]
#### System information

Geth version: `1.6.6-stable`
OS & Version: `Linux Ubuntu 16.04.2 LTS`

#### Expected behaviour

`sudo geth --ipcpath "/path/to/blockchain/geth.ipc" --networkid 12345 --datadir "/path/to/blockchain" --nodiscover --maxpeers 2 --rpc --rpcport 8080 --rpccorsdomain * --rpcapi "db,eth,net,web3" --port 30303 --identity "TestNet" console`

Calling the exact same command (above) on three virtual machines via cssh. One of the virtual machines has Ubuntu Desktop (has a GUI), the other two are servers (only console). They all have the same OS version.

Expected to see the same behaviour on the Desktop as on the servers.
This is what I see on the servers:
```
INFO [06-29|15:54:48] IPC endpoint opened: /path/to/blockchain/geth.ipc 
Welcome to the Geth JavaScript console!

instance: Geth/TestNet/v1.6.6-stable-10a45cb5/linux-amd64/go1.8.1
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
```

#### Actual behaviour

This is what I see on the Desktop:
`INFO [06-29|16:21:21] IPC endpoint opened: /path/to/blockchain/geth.ipc`
And that's it. No interactive JavaScript console :(

#### Steps to reproduce the behaviour

Exactly what I described above. The servers and the desktop were all simultaneously configured exactly the same way via cssh.

**Comment by parunach** [comment]
I am using CentOS and seeing similar problems. There is limited documentation, tutorials etc. Due to the product going through changes, many of the older tutorials do not work anymore. All existing tutorials must be updated to work in the current product.
