### ISSUE TITLE
Rewrite the greeter contract tutorial

### ISSUE THREAD

**Issue by parunach** [ethereum/go-ethereum#14738]
The greeter tutorial does not work anymore. This includes multiple changes

- No compiler inside geth console
- Contract parameter changes

It must include what is done outside and inside the console. 
Details on how to start the mining, what parameters the mining depends on, should be included. 
It must include how to change the greeting multiple times and see it come out by using the mining several times.

**Comment by Arachnid** [comment]
Fixed by https://github.com/ethereum/ethereum-org/issues/658
