### ISSUE TITLE
Didn't get ethereum...

### ISSUE THREAD

**Issue by iPredictable** [ethereum/go-ethereum#14741]
Hi, I tried buying some Ethereum via the btc/eth converter and totally got ripped off, I payed 10$ initially to see how it works and it said payment sent, after hours of waiting my account is still empty, I purchased another 10$ worth and still did not get payed.  
Here is proof: https://gyazo.com/bef75d08f3e20dc02bea3b7b7cbb5f9e

**Comment by chrisdbarnett** [comment]
There's a backlog of Ethereum transactions. Also, if it's not appearing on the blockchain - you can check using https://etherscan.io - type in your wallet address in the top right hand corner.

If it's still not sorted in a few hours, it really is an issue between yourself and shapeshift. 
This page is only for issues relating to the Go programming language implementation on Ethereum.
