### ISSUE TITLE
Impossible reorg, please file an issue

### ISSUE THREAD

**Issue by jcollum** [ethereum/go-ethereum#14740]
#### System information

Geth version:  `geth-windows-amd64-1.6.6-10a45cb5.exe`  
OS & Version: Win 10
Commit hash : (if `develop`)

#### Backtrace

````
INFO [07-01|10:16:19] Imported new state entries               count=2    flushed=1   elapsed=5.245ms   processed=249497 pending=11    retry=0   duplicate=0 unexpected=768
INFO [07-01|10:16:19] Imported new state entries               count=1    flushed=11  elapsed=0s        processed=249498 pending=0     retry=0   duplicate=0 unexpected=768
INFO [07-01|10:16:19] Imported new block receipts              count=0    elapsed=500.7µs   number=3958394 hash=fe8c86…8a8bf8 ignored=1
INFO [07-01|10:16:19] Committed new head block                 number=3958394 hash=fe8c86…8a8bf8
INFO [07-01|10:16:19] Imported new chain segment               blocks=3  txs=82   mgas=3.373   elapsed=108.145ms mgasps=31.187 number=3958397 hash=0f4a0a…73190c
ERROR[07-01|10:16:22] Impossible reorg, please file an issue   oldnum=3958417 oldhash=17ce9b…56df50 newnum=3958417 newhash=17ce9b…56df50
````

Just doing what the app told me to do.

**Comment by minessis** [comment]
**System Information**

Name: geth - the go-ethereum command line interface
Version: 1.6.6-stable-10a45cb5
OS: MacOS 10.12.5

**Backtrace**
```
INFO [07-03|21:02:47] Imported new block headers               count=0    elapsed=475.875µs number=3971112 hash=bc49c2…1d2771 ignored=22
INFO [07-03|21:02:47] Imported new state entries               count=5    flushed=0   elapsed=12.208ms  processed=13557745 pending=22    retry=0   duplicate=367 unexpected=2882
INFO [07-03|21:02:47] Imported new state entries               count=5    flushed=0   elapsed=4.171ms   processed=13557750 pending=27    retry=0   duplicate=367 unexpected=2882
INFO [07-03|21:02:47] Imported new state entries               count=5    flushed=20  elapsed=520.832µs processed=13557755 pending=8     retry=0   duplicate=367 unexpected=2882
INFO [07-03|21:02:48] Imported new state entries               count=1    flushed=8   elapsed=118.556µs processed=13557756 pending=0     retry=0   duplicate=367 unexpected=2882
INFO [07-03|21:02:48] Imported new block receipts              count=0    elapsed=78.389µs  number=3970899 hash=9297c1…b12beb ignored=1
INFO [07-03|21:02:48] Committed new head block                 number=3970899 hash=9297c1…b12beb
ERROR[07-03|21:02:48] Impossible reorg, please file an issue   oldnum=3970899 oldhash=9297c1…b12beb newnum=3970899 newhash=9297c1…b12beb
```

**Comment by jeanjluo** [comment]
Geth Version: 1.6.6-stable
Git Commit: 10a45cb59bd9bc9f717817afc029a57b222e558d
OS: MacOS 10.10.5

```
INFO [07-07|10:19:29] Block synchronisation started 
INFO [07-07|10:19:29] Mining aborted due to sync 
INFO [07-07|10:19:29] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=659.09µs  mgasps=0.000 number=758 hash=3d9bc7…59759f
INFO [07-07|10:19:29] Starting mining operation 
INFO [07-07|10:19:29] Commit new mining work                   number=759 txs=0 uncles=0 elapsed=162.866µs
INFO [07-07|10:19:29] Commit new mining work                   number=759 txs=0 uncles=0 elapsed=47.08µs
INFO [07-07|10:19:29] Successfully sealed new block            number=759 hash=3d0257…8ffa63
INFO [07-07|10:19:29] Successfully sealed new block            number=759 hash=3d0257…8ffa63
INFO [07-07|10:19:29] 🔨 mined potential block                  number=759 hash=3d0257…8ffa63
ERROR[07-07|10:19:29] Impossible reorg, please file an issue   oldnum=759 oldhash=3d0257…8ffa63 newnum=759 newhash=3d0257…8ffa63
```

**Comment by clu8** [comment]
Geth version: 1.6.6-stable-10a45cb5
OS: Windows 10 x64

`INFO [07-07|15:55:28] Imported new state entries               count=18   flushed=58  elapsed=11.033ms     processed=7839169 pending=59    retry=0    duplicate=2935 unexpected=10896
INFO [07-07|15:55:28] Imported new state entries               count=1    flushed=12  elapsed=1.004ms      processed=7839170 pending=47    retry=0    duplicate=2935 unexpected=10896
INFO [07-07|15:55:28] Imported new state entries               count=6    flushed=34  elapsed=1.002ms      processed=7839176 pending=15    retry=0    duplicate=2935 unexpected=10896
INFO [07-07|15:55:28] Imported new state entries               count=2    flushed=15  elapsed=0s           processed=7839178 pending=0     retry=0    duplicate=2935 unexpected=10896
INFO [07-07|15:55:34] Imported new block headers               count=0    elapsed=4.011ms      number=3989560 hash=0f712f…460dec ignored=192
INFO [07-07|15:55:34] Imported new block headers               count=5    elapsed=11.031ms     number=3989588 hash=338422…e9bc1f ignored=23
INFO [07-07|15:55:34] Imported new block receipts              count=0    elapsed=0s           number=3989376 hash=56869f…69218d ignored=8
INFO [07-07|15:55:34] Imported new block receipts              count=0    elapsed=0s           number=3989378 hash=85a3f4…91ce74 ignored=2
INFO [07-07|15:55:35] Imported new block receipts              count=0    elapsed=0s           number=3989425 hash=9697e5…7a9036 ignored=47
INFO [07-07|15:55:35] Imported new block receipts              count=0    elapsed=0s           number=3989426 hash=33cc1c…af9999 ignored=1
INFO [07-07|15:55:35] Committed new head block                 number=3989426 hash=33cc1c…af9999
ERROR[07-07|15:55:35] Impossible reorg, please file an issue   oldnum=3989426 oldhash=33cc1c…af9999 newnum=3989426 newhash=33cc1c…af9999
INFO [07-07|15:55:36] Imported new chain segment               blocks=5  txs=11411 mgas=20.040  elapsed=1.643s       mgasps=12.194 number=3989588 hash=338422…e9bc1f ignored=157
INFO [07-07|15:55:36] Fast sync complete, auto disabling
INFO [07-07|15:55:42] Imported new chain segment               blocks=1  txs=96    mgas=6.576   elapsed=210.562ms    mgasps=31.232 number=3989586 hash=f38783…cbb80f
INFO [07-07|15:55:43] Imported new chain segment               blocks=1  txs=54    mgas=6.301   elapsed=149.397ms    mgasps=42.179 number=3989589 hash=f9f5ae…2d3380
INFO [07-07|15:55:51] Imported new chain segment               blocks=1  txs=35    mgas=1.320   elapsed=817.171ms    mgasps=1.616  number=3989590 hash=1d5886…703557
INFO [07-07|15:56:08] Imported new chain segment               blocks=1  txs=34    mgas=1.207   elapsed=302.805ms    mgasps=3.987  number=3989591 hash=d3d91f…3fc21d
INFO [07-07|15:56:14] Imported new chain segment               blocks=1  txs=65    mgas=6.651   elapsed=962.559ms    mgasps=6.910  number=3989592 hash=245c6c…84ad3c
INFO [07-07|15:56:22] Imported new chain segment               blocks=1  txs=46    mgas=6.654   elapsed=562.495ms    mgasps=11.830 number=3989593 hash=1b4376…1a661b
INFO [07-07|15:56:22] Imported new chain segment               blocks=1  txs=25    mgas=6.619   elapsed=148.394ms    mgasps=44.603 number=3989592 hash=0ca318…44be8b`

**Comment by mdealer** [comment]
Geth Version: 1.6.6-stable-10a45cb5
OS: Windows 10 x64
```

INFO [07-08|19:47:30] Imported new state entries               count=131  flushed=188 elapsed=93.561ms  processed=14691889 pending=430   retry=0   duplicate=149 unexpected=2228
INFO [07-08|19:47:30] Imported new state entries               count=101  flushed=215 elapsed=35.522ms  processed=14691990 pending=267   retry=0   duplicate=149 unexpected=2228
INFO [07-08|19:47:30] Imported new state entries               count=52   flushed=172 elapsed=16.512ms  processed=14692042 pending=112   retry=0   duplicate=149 unexpected=2228
INFO [07-08|19:47:30] Imported new state entries               count=17   flushed=99  elapsed=16.509ms  processed=14692059 pending=14    retry=0   duplicate=149 unexpected=2228
INFO [07-08|19:47:31] Imported new state entries               count=1    flushed=14  elapsed=0s        processed=14692060 pending=0     retry=0   duplicate=149 unexpected=2228
INFO [07-08|19:47:31] Imported new block receipts              count=0    elapsed=501.1µs   number=3993967 hash=44f24e…899c58 ignored=1
INFO [07-08|19:47:31] Committed new head block                 number=3993967 hash=44f24e…899c58
INFO [07-08|19:47:32] Imported new chain segment               blocks=10 txs=603  mgas=23.850  elapsed=1.138s    mgasps=20.943 number=3993977 hash=6d3394…93edca
ERROR[07-08|19:47:33] Impossible reorg, please file an issue   oldnum=3994001 oldhash=11865d…5f0d9a newnum=3994001 newhash=11865d…5f0d9a
INFO [07-08|19:47:37] Imported new chain segment               blocks=80 txs=9544 mgas=117.418 elapsed=5.441s    mgasps=21.578 number=3994218 hash=53de6d…8ddecb ignored=161
WARN [07-08|19:47:37] Synchronisation failed, retrying         err="state data download canceled (requested)"
WARN [07-08|19:47:37] Discarded bad propagated block           number=3994219 hash=6b544d…c44ace
```

**Comment by bradlucas** [comment]
Geth Version: 1.6.7-stable
OS: OSX 10.11.1

```
INFO [07-15|23:56:24] Imported new chain segment               blocks=1   txs=0  mgas=0.000  elapsed=9.593ms   mgasps=0.000   number=1308328 hash=e13e95…9598ff
INFO [07-15|23:56:24] Imported new chain segment               blocks=1   txs=0  mgas=0.000  elapsed=5.750ms   mgasps=0.000   number=1308329 hash=204f41…94f376
WARN [07-15|23:56:24] Header broke chain ordering              number=1308329 hash=204f41…94f376 expected=1308330
WARN [07-15|23:56:24] Synchronisation failed, dropping peer    peer=761304837b0a1f52 err="action from bad peer ignored"
INFO [07-15|23:56:27] Imported new chain segment               blocks=1   txs=0  mgas=0.000  elapsed=5.691ms   mgasps=0.000   number=1308330 hash=bdc3fb…22b46d
INFO [07-15|23:57:14] Imported new chain segment               blocks=1   txs=0  mgas=0.000  elapsed=6.595ms   mgasps=0.000   number=1308331 hash=f9b131…4bf355
```

**Comment by GuidoKuitE** [comment]
Same issue
![geth_issue](https://user-images.githubusercontent.com/30213015/28247868-008b6dd8-6a3a-11e7-85e2-d6f2070a0395.png)
, but only have attached screenshot

**Comment by holiman** [comment]
@fjl is this related to your changes in https://github.com/ethereum/go-ethereum/pull/14589 maybe ?
