### ISSUE TITLE
geth 1.6.6 - can't sendTransaction - insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by Pat555** [ethereum/go-ethereum#14745]
Geth version: 1.6.6
OS & Version: OSX

I'm new and just going through the tutorials and couldn't send a simple transaction. I keep getting "Error: insufficient funds for gas * price + value". Please help.

> checkAllBalances()

  eth.accounts[0]: 	0xba2ac05b17cc8e03f4e89beb7f5234bf8a1eda1e 	balance: 3e-13 ether
  eth.accounts[1]: 	0x1f80e2944d89685ca0846ef71a9c6f5f69c19653 	balance: 4e-13 ether
  eth.accounts[2]: 	0x403625438f706376e7b8082da441f8f9e954dad9 	balance: 0 ether
  Total balance: 7e-13 ether
undefined
> eth.sendTransaction({from: '0x1f80e2944d89685ca0846ef71a9c6f5f69c19653', to: '0xba2ac05b17cc8e03f4e89beb7f5234bf8a1eda1e', value: web3.toWei(0.00001, "ether")})
Error: insufficient funds for gas * price + value
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1

>

**Comment by karalabe** [comment]
A plain transaction requires 21000 gas to transfer. That also needs to be coverable by your account. If you don't specify a gas price explicitly geth will take a median one from the last 5-10 blocks, which is probably 5-10gwei. At that price point, the transaction cost would be larger than your total balance.
