### ISSUE TITLE
A compile error of contract

### ISSUE THREAD

**Issue by ucwong** [ethereum/go-ethereum#14742]
![image](https://user-images.githubusercontent.com/22344498/27775821-28f0f89a-5fd8-11e7-935c-911a4d809422.png)

just copy code from official website and deploy a contract. How to fix this error? thank you

**Comment by Bo-Ye** [comment]
Which command did you use to compile?

**Comment by ucwong** [comment]
@Bo-Ye I used mac client , it compile automatically. It is ok when I deploy a token contract, but failed of crowd-sale contract

**Comment by karalabe** [comment]
This seems a Solidity error. Please reach out to the Solidity developers for infos on this (note, it appears that your solc compiler rejects code with unused variables, which might give you a hint to what might be wrong).
