### ISSUE TITLE
invalid argument 0: missing 0x prefix for hex data

### ISSUE THREAD

**Issue by koreaex** [ethereum/go-ethereum#14746]
#### System information

Geth 1.6.5
Ubuntu 14.04.2 LTS 

When I send a transaction, it return error message "invalid argument 0: missing 0x prefix for hex data". However,  `sendTransaction's` arguments just have from, to and value,  which one it say? I refer to https://github.com/ethereum/go-ethereum/issues/14573, I can't find genesis file and be confirm to the issue, so anyone can help me solve it? thanks.

**Comment by fjl** [comment]
#14573 is about genesis file, so it's a different issue. We have a fix for the error message on master branch. It will be in the next release.

**Comment by koreaex** [comment]
@fjl Hi, I upgrade geth to 1.6.6 stable, and still exist the issue.

**Comment by themandalore** [comment]
Did this ever get fixed?

**Comment by karthiyogi** [comment]
i am also facing same issue i am using 1.6.1 and also i tried 1.5.9 and still the same problem while deploying contracts using cakeshop
