### ISSUE TITLE
Failed to store last fast block's hash, corruption on data-block... need new solutions

### ISSUE THREAD

**Issue by iceman3333** [ethereum/go-ethereum#14744]
1.6.6 stable
win 10 - 64 bit
more than 300 gb available on hdd with 8gb ddr3 ram using R9 270 GPU

Been running geth to sync the blockchain for a week and keep getting:

CRIT [07-03|04:18:33] Failed to store last fast block's hash   err="leveldb/table: corruption on data-block (pos=894935): checksum mismatch, want=0xaf4ed986 got=0x64b3af91 [file=022972.ldb]"

It's a different file everytime and I've gotten a couple different corruption errors but they are all the same "corruption on data-block"

Another example of what I get: "CRIT [07-03|05:05:03] Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=520180): checksum mismatch, want=0x8cd77632 got=0xb7375cb4 [file=005001.ldb]"

Steps I've taken:
- manually delete chaindata and tried to resync multiple times
- used removedb and then tried to resync with no positive results
- turned off anti-virus
- defragmented hdd before a brand new install of geth
- switched to wired ethernet connection
- ran geth from cmd prompt and by clicking the geth file installed

Any advice on how to proceed would be greatly appreciated!

**Comment by karalabe** [comment]
Please run a bad sector check on your HDD. It seems something went very wrong with your system.

**Comment by iceman3333** [comment]
Just ran a sector check and everything checked out okay, no errors

**Comment by iceman3333** [comment]
quick update, just tried this morning to removedb and sync again and got this:

WARN [07-03|11:17:29] Rolled back headers                      count=2048 header=198336->196288 fast=189763->189763 block=0->0
WARN [07-03|11:17:29] Synchronisation failed, dropping peer    peer=0da87ac07421d4a4 err="retrieved hash chain is invalid"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x50cc35]

goroutine 13361 [running]:
math/big.(*Int).Cmp(0xc0556f6280, 0x0, 0x172c2c56e60391a7)
        C:/go/src/math/big/int.go:314 +0x35
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc044a43bc0, 0xc0455bd8c0)
        C:/gopath/src/github.com/ethereum/go-ethereum/eth/sync.go:172 +0x157
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
        C:/gopath/src/github.com/ethereum/go-ethereum/eth/sync.go:149 +0x1c9
