### ISSUE TITLE
how to add something in Makefile or ci.go or other place in order to debugging ethereum with delve?

### ISSUE THREAD

**Issue by jiebanghan** [ethereum/go-ethereum#14751]
well ,you know in Makefile it is below:
```
# This Makefile is meant to be used by people that do not usually work
# with Go source code. If you know what GOPATH is then you probably
# don't need to bother with make.

.PHONY: geth android ios geth-cross evm all test clean
.PHONY: geth-linux geth-linux-386 geth-linux-amd64 geth-linux-mips64 geth-linux-mips64le
.PHONY: geth-linux-arm geth-linux-arm-5 geth-linux-arm-6 geth-linux-arm-7 geth-linux-arm64
.PHONY: geth-darwin geth-darwin-386 geth-darwin-amd64
.PHONY: geth-windows geth-windows-386 geth-windows-amd64

GOBIN = build/bin
GO ?= latest

geth:
	build/env.sh go run build/ci.go install ./cmd/geth
	@echo "Done building."
	@echo "Run \"$(GOBIN)/geth\" to launch geth."
```

but I want to add something like 
`go build -gcflags '-N -l'` 
you can also see https://github.com/derekparker/delve/issues/909 for exact condition.
which can be used for debugging with delve. but how could I do it?
by the way, which debugger do you usually use for debugging ethereum? thank you .

**Comment by karalabe** [comment]
Don't use the makefiles. Build geth yourself directly with go: `go build ./cmd/geth`. Then you can add whatever flags you wish. This does require a proper Go workflow set up, but I guess if you want to debug stuff, that should not be an issue.

As for the debugger, we don't use (at least I don't). Geth is running on hundreds of threads at once, there's little that a debugger can aid in. We rely on logs and occasional print statements during debugging.

**Comment by jiebanghan** [comment]
thank you very much.
