### ISSUE TITLE
does not exit on `exit` in light mode

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/go-ethereum#14759]
#### System information
Geth version: 1.6.6-stable
OS & Version: macOS Sierra 10.12.5
Actually the same behaviour is seen on Ubuntu 16.04 and same latest geth version (but Linux executable)

#### Expected behaviour
When typing `exit` in the geth console that I started via `geth --syncmode=light console` I expected geth to quit. Even when trying a graceful shutdown via one time `Ctrl`+`c` it does not quit.

#### Actual behaviour
Instead of quitting, geth seems to hang forever, I can only quit it by doing many `Ctrl`+`c`: This is the last output:

> \>exit
INFO [07-05|19:25:40] IPC endpoint closed: /root/.ethereum/geth.ipc 
INFO [07-05|19:25:40] Blockchain manager stopped 
INFO [07-05|19:25:40] Stopping light Ethereum protocol 
^CINFO [07-05|19:26:55] Got interrupt, shutting down... 
^CWARN [07-05|19:31:01] Already shutting down, interrupt more to panic. times=9

#### Steps to reproduce the behaviour
`geth --syncmode=light console`
Then wait for it to finish syncing and then in the geth console:
`exit`
Now as nothing happens do `Ctrl`+`c` which is also not going to quit it until you forcefully shut it down.

**Comment by veox** [comment]
Can not reproduce on `geth` v1.8.2 - although not using a Mac.

**Comment by karalabe** [comment]
I'm going to close this an ancient. Probably fixed a deadlock a long time ago.
