### ISSUE TITLE
How to import a existing account file when i make a install with GNU/Linux ?

### ISSUE THREAD

**Issue by ZerooCool** [ethereum/go-ethereum#14754]
Hello everybody !
I see this way for a new installation : Install/use Debian 8 or Ubuntu 16.0.4 then execute :

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:ethereum/ethereum
sudo sed 's/jessie/vivid/' -i /etc/apt/sources.list.d/ethereum-ethereum-*.list
sudo apt-get update
sudo apt-get install ethereum ethminer
geth account new
# copy long character sequence within {}, that is your <YOUR_WALLET_ADDRESS>
# if you lose the passphrase, you lose your coins!
sudo apt-get install linux-headers-amd64 build-essential
chmod +x NVIDIA-Linux-x86_64-367.35.run
sudo ./NVIDIA-Linux-x86_64-367.35.run
ethminer -G -F http://yolo.ethclassic.faith:9999/0x<YOUR_WALLET_ADDRESS> --farm-recheck 200
echo done

It's okay ?

But ... How i can import my existing account file ?
I create a account with myetherwallet inline. I have a " secret " file.
I don't now, how i can use it with the terminal.

I have install the file with windows, it's ok with Windows, but, i want test that with GNU/Linux.

Thank you for your help.

**Comment by karalabe** [comment]
If you simply copy your account's key file (the one containing the `{...}` stuff) into your `keystore` folder without your data directory, Geth should automatically pick it up and add it to your list of accounts.
