### ISSUE TITLE
GeneralStateTest `RevertDepthCreateAddressCollision` fails

### ISSUE THREAD

**Issue by pirapira** [ethereum/go-ethereum#14756]
#### System information

Travis: https://travis-ci.org/ethereum/go-ethereum/jobs/249117383#L899
OS & Version: Linux
Commit hash : https://github.com/ethereum/go-ethereum/commit/1864f729cec03dda63a6d7e0e03fb206c7ba6cf1 (on this PR https://github.com/ethereum/go-ethereum/pull/14734)

#### Expected behaviour

The GeneralStateTest `RevertDepthCreateAddressCollision` should succeed and leave no message on the console.

#### Actual behaviour

The console shows
```
 --- FAIL: TestState/stRevertTest/RevertDepthCreateAddressCollision.json (0.00s)

        --- FAIL: TestState/stRevertTest/RevertDepthCreateAddressCollision.json/RevertDepthCreateAddressCollision/EIP150/7 (0.00s)

        	state_test.go:51: post state root mismatch: got d133d39ca6ad1147afe84c8155185fd6e18cfcaecc0282b2bc5678d5252b7412, want 78ba42aa7a64d9d20dfcbbcf3527486f7607bc694724b6d2cf9d34cb7696eee4
```

#### Steps to reproduce the behaviour

To be documented

* [x] running the Travis build (need to try)
* [ ] running the same commands locally (need to try)
* [ ] running only this test locally (need to try)

**Comment by pirapira** [comment]
At least I can see the problem on my Travis account, so I'm ready to tinker https://travis-ci.org/pirapira/go-ethereum/jobs/250352981

**Comment by pirapira** [comment]
@karalabe I told you I was going to assign myself, but I could not.  Sorry.

**Comment by pirapira** [comment]
This is likely because of a [problem](https://github.com/ethereum/cpp-ethereum/issues/4225) in cpp-ethereum.

**Comment by pirapira** [comment]
After fixing https://github.com/ethereum/cpp-ethereum/issues/4225 in the tests, the phenomenon still persists.

**Comment by pirapira** [comment]
I found another [problem](https://github.com/ethereum/cpp-ethereum/issues/4237) in `cpp-ethereum`.  I start feeling stupid about having opened this issue in this repo.

**Comment by fjl** [comment]
Thanks for investigating this issue!

**Comment by pirapira** [comment]
This issue will be kept track in https://github.com/ethereum/tests/issues/223
