### ISSUE TITLE
Web3.eth.sign produces reversed signature?

### ISSUE THREAD

**Issue by TheMalgot** [ethereum/go-ethereum#14761]
#### System information

Geth version: `1.6.6-beta`
OS & Version: Linux Mint
Commit hash : (if `develop`)

#### Expected behaviour

As far as i understand, when i sign a hased message, the resulting signature should look somewhat like this:

`0x1bf6f2191550a94cdf3eb807dfda63076f8b8a6628b4e033190c131e30cb074dc976e707117e71e7328ed19ae4527b3d32ee0c0f11dcf2727ec961b825c1a1b047"`

Note, how at the end, there is no "00", like numerous documentations are saying, but an "1b", which is hexadecimal for 27.

#### Actual behaviour

Instead, i get this `0x1be8918f888057a3604074d2fbbaf8967a6ed28f2dbac76ee6a40cb72dcd56424837eb520d33c51dd0128c994837ab4b7dbcf384096ba1bfcc02e845d1844f946a`

Here, the 1b is at the beginning of the resulting signature. No matter what i sign, the first 2 chars are always 1b or 1c (27 or 28)

#### Steps to reproduce the behaviour

I don't know what causes this behavior. The geth i'm running on my personal machine runs fine. It's a geth version thats running on my university that acts this strange.

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Perhaps it's a modified Geth? What does `geth version` print? If I run the `eth_sign` method locally, it works as expected:

```
> eth.sign(eth.accounts[0], "0x1234")
"0x005e83825ffc97ed2b294728ce2674ed8c7cd446865c7a5ead44f664a94ea888302406a94318dc4e6e38cb5f826d99d58aeb119c260ac906bada0e0a1b651b001b"
> eth.sign(eth.accounts[0], "0x12345689")
"0x1414d586f805ea7cd5bca6c577247635f656b236eeee1caf97ce4cc1688735666142c296fce3d520a1d9d24577ff8c0a5c671f10d35ca7543f31e1439c50cd581b"
```
