### ISSUE TITLE
new account issues

### ISSUE THREAD

**Issue by Haircut211** [ethereum/go-ethereum#14764]
Geth version: `1.6.6`
OS & Version: Windows 10

I am trying to set up a geth account in cmd. I
 installed the software, then got started with c:>geth new account 
enter new password, i didnt see it typing so i closed out. i re-opened cmd to start again and now get this:

C:\>geth new account
INFO [07-05|22:13:10] Starting peer-to-peer node               instance=Geth/v1.6.6-stable-10a45cb5/windows-amd64/go1.8.3
INFO [07-05|22:13:10] Allocated cache and file handles         database="C:\\Users\\Jeremy Thurnau\\AppData\\Roaming\\Ethereum\\geth\\chaindata" cache=128 handles=1024
INFO [07-05|22:13:10] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Metropolis: 9223372036854775807 Engine: ethash}"
INFO [07-05|22:13:10] Disk storage enabled for ethash caches   dir="C:\\Users\\Jeremy Thurnau\\AppData\\Roaming\\Ethereum\\geth\\ethash" count=3
INFO [07-05|22:13:10] Disk storage enabled for ethash DAGs     dir="C:\\Users\\Jeremy Thurnau\\AppData\\Ethash"                          count=2
INFO [07-05|22:13:10] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [07-05|22:13:10] Loaded most recent local header          number=1000336 hash=5534eb…45531d td=7139433242698584643
INFO [07-05|22:13:10] Loaded most recent local full block      number=0       hash=d4e567…cb8fa3 td=17179869184
INFO [07-05|22:13:10] Loaded most recent local fast block      number=990863  hash=763963…4456aa td=7027104783823951583
INFO [07-05|22:13:10] Starting P2P networking
2017/07/05 22:13:12 ssdp: got unexpected search target result "upnp:rootdevice"
2017/07/05 22:13:12 ssdp: got unexpected search target result "uuid:2f402f80-da50-11e1-9b23-00178826d82d"
2017/07/05 22:13:12 ssdp: got unexpected search target result "urn:schemas-upnp-org:device:basic:1"
INFO [07-05|22:13:12] UDP listener up                          self=enode://cef17270ad59533b844d9f8c28dc8a6121e8864c556c3bb7b3944e158ef88f2ea3863f93ca0c41ba7db1a0c4dc9fba62963325098da9eebf9ab3faaa87a611b4@[::]:30303
INFO [07-05|22:13:12] RLPx listener up                         self=enode://cef17270ad59533b844d9f8c28dc8a6121e8864c556c3bb7b3944e158ef88f2ea3863f93ca0c41ba7db1a0c4dc9fba62963325098da9eebf9ab3faaa87a611b4@[::]:30303
INFO [07-05|22:13:12] IPC endpoint opened: \\.\pipe\geth.ipc

I attempted to remove geth and start again. Not sure why this is happening. Instructions on https://www.cryptocompare.com/mining/guides/how-to-mine-ethereum/ 
said if you have to just create a new account and start again but the code was the same before i reinstalled software and after

Thank you all in advance!

**Comment by paulsri** [comment]
same for me, any one?

**Comment by fjl** [comment]
The command to create a new account is `geth account new`.
