### ISSUE TITLE
why can't stop mining?

### ISSUE THREAD

**Issue by jiebanghan** [ethereum/go-ethereum#14768]
#### System information

Geth version: `geth version`
Version: 1.6.6-unstable
Architecture: amd64
OS & Version: Windows/Linux/OSX
win10

#### Expected behaviour
I create a private chain in my PC. After mining for a while, I just want to stop mining

#### Actual behaviour
,so I type "miner.stop()", but it can't stop. the console still show information incessantly.

```
> INFO [07-07|09:42:20] Successfully sealed new block            number=203 hash=c11ed3…0bec95
INFO [07-07|09:42:21] 🔗 block reached canonical chain          number=198 hash=769f09…0fdd3f
INFO [07-07|09:42:21] 🔨 mined potential block                  number=203 hash=c11ed3…0bec95
INFO [07-07|09:42:21] Generating DAG in progress               epoch=1 percentage=72 elapsed=24m35.334s
INFO [07-07|09:42:21] Commit new mining work                   number=204 txs=0 uncles=0 elapsed=0s
> miner.stop()
true
> INFO [07-07|09:42:27] Generating DAG in progress               epoch=1 percentage=73 elapsed=24m40.957s
INFO [07-07|09:42:30] Generating DAG in progress               epoch=1 percentage=74 elapsed=24m43.627s
> miner.stINFO [07-07|09:42:32] Generating DAG in progress               epoch=1 percentage=75 elapsed=24m46.275s
> miner.stop()
true
> INFO [07-07|09:42:36] Generating DAG in progress               epoch=1 percentage=76 elapsed=24m49.595s
INFO [07-07|09:42:39] Generating DAG in progress               epoch=1 percentage=77 elapsed=24m52.717s

> miner.INFO [07-07|09:42:42] Generating DAG in progress               epoch=1 percentage=78 elapsed=24m55.622s
> miner.stop()
true
> INFO [07-07|09:42:45] Generating DAG in progress               epoch=1 percentage=79 elapsed=24m58.961s
INFO [07-07|09:42:48] Generating DAG in progress               epoch=1 percentage=80 elapsed=25m2.255s
INFO [07-07|09:42:52] Generating DAG in progress               epoch=1 percentage=81 elapsed=25m5.542s
```

**Comment by karalabe** [comment]
Currently there's no way to interrupt DAG generation. If you stop the miner during DAG generation, it will finish generating it and then idle out.

**Comment by jiebanghan** [comment]
thank you very much

**Comment by navinthenapster** [comment]
It takes much time to finish the generation. And I am still facing problem in starting the mining still. IT is not committing new block

**Comment by emurmotol** [comment]
> The first time you start mining will take some time as your node will
> need to generate a 1GB dataset for the Proof of Work algorithm. You
> will see “generating DAG” messages in the other console log, which
> took about 8 minutes on my laptop. You can read more about this here:
> 
> https://github.com/ethereum/wiki/wiki/Ethash-DAG

Source:

https://medium.com/@mikesmolenski/getting-started-with-ethereum-4a3841276b6e
