### ISSUE TITLE
Geth is not Syncing? Blocknumber not correct and peerCount 0

### ISSUE THREAD

**Issue by Marow** [ethereum/go-ethereum#14771]
#### System information

Geth version: 1.6.6-stable
OS & Version: Ubuntu

#################

net.peerCount is 0 and eth.blocknumber is not the newest
 How can i make that he recheck all blocks and everything... 

And why is this not correct? was running few days and stopped syncing...

How can i make resync in console 

i'm running geth with "--rpc --mine console"

I also check `timedatectl` and there is 
   
    Local time: Fri 2017-07-07 10:22:19 CEST
    Universal time: Fri 2017-07-07 08:22:19 UTC
    RTC time: n/a
    Time zone: Europe/Berlin (CEST, +0200)
    Network time on: yes
    NTP synchronized: yes
    RTC in local TZ: no

**Comment by Marow** [comment]
I made `geth upgradedb `

and start `geth --rpc --mine --fast` again, now has correct block, but my variance is now 0% :( it was over 110% :(

**Comment by Marow** [comment]
After 30minutes again... net.peerCount = 0...

why? :(

**Comment by GeckoFu** [comment]
Having the same issue here.
