### ISSUE TITLE
How can receive notifications when a transaction is made on address?

### ISSUE THREAD

**Issue by unutoiul** [ethereum/go-ethereum#14772]
How can receive notifications when a transaction is made on address?
when i do RPC 

request:
{
	"jsonrpc":"2.0",
	"method":"eth_getBalance",
	"params":["0x3e1a75b4a8ceac12dab41780919d28ba713138ba","latest"],
	"id":1
}

result:

{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "notifications not supported"
    }
}

**Comment by nkbai** [comment]
there are no notifactions on rpc,
