### ISSUE TITLE
my transaction invoked by contract..?

### ISSUE THREAD

**Issue by kabamaru1234** [ethereum/go-ethereum#14778]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
i wanted to send 0.5 ether to bittrex wallet. i send it and it felt like it stack so I put enter again and finally a send 2 transaction with 0.5 ether each.....

#### Actual behaviour
the ether as I see from blockchain invoked by contract and do not go to a bittrex wallet but two a difference unknown wallet.....I thought it will be a  hacker that stole my ether but after a little research I bellieve it was a mistake in the order to send the ether may i wrote   to: eth.accounts[address]  instead of to: "address"  ........ does anyone knows something about that..? can i take back my ether..? 

0x41B027926C50875A6ceb7aa1B734F9a0F6A91585   this is my address..anyone can see the transaction with a black arrow in the blockchain....

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
In JavaScript, if you take a non-existing index of a list or a map (in your case `eth.accounts[address]`), you get back `undefined`. In Ethereum, the way you deploy a contract is to send a transaction without a recipient being specified. The JavaScript `undefined` pretty much means that the recipient should not be defined, which means you requested a contract deployment.

I'm really sorry, but unfortunately there's no way to revert any transactions in Ethereum.

**Comment by kabamaru1234** [comment]
I honestly thank you very very much for your time to answer me.....it was a good news that i took an answer and I know now......it was my mistakes that drive to this mistake.....that was a lesson to me and I am glad to understand what i did wrong.....thank you again.... 

    Στις 4:55 μ.μ. Δευτέρα, 10 Ιουλίου 2017, ο/η Péter Szilágyi <notifications@github.com> έγραψε:
 

 In JavaScript, if you take a non-existing index of a list or a map (in your case eth.accounts[address]), you get back undefined. In Ethereum, the way you deploy a contract is to send a transaction without a recipient being specified. The JavaScript undefined pretty much means that the recipient should not be defined, which means you requested a contract deployment.I'm really sorry, but unfortunately there's no way to revert any transactions in Ethereum.—
