### ISSUE TITLE
Not enough memory to mine ether on 5Gb linux box

### ISSUE THREAD

**Issue by stiv-yakovenko** [ethereum/go-ethereum#14786]
I have linux box with 5Gb of memory:

    osboxes@osboxes ~/node1 $ free
                  total        used        free      shared  buff/cache   available
    Mem:        5176876      158360     3536464      226748     1482052     4751712

This is my genesis.json:

    {
        "config": {
            "chainId": 15,
            "homesteadBlock": 0,
            "eip155Block": 0,
            "eip158Block": 0
        },
        "difficulty": "2000",
        "gasLimit": "2100000",
        "alloc": {
            "7df9a875a174b3bc565e6424a0050ebc1b2d1d82": { "balance": "300000" },
            "f41c74c9ae680c1aa78f42e5647a62f353b7bdde": { "balance": "400000" }
        }
    }

This is how I initialize it:

    geth --datadir . init genesis.json

And i open console 

    geth --datadir . console

Then I start miner and get this crash:

    ERROR[07-10|15:56:35] Failed to generate mapped ethash dataset epoch=1 err="cannot allocate memory"
    runtime: out of memory: cannot allocate 2164260864-byte block (128057344 in use)
    fatal error: out of memory

How much memory would be enough?

eth version: Version: 1.6.6-stable
OS & Version: Linux

**Comment by karalabe** [comment]
Please make sure you are running the 64 bit version. What does `geth version` print?

**Comment by MIGUELWAXX** [comment]
yes i think?

**Comment by karalabe** [comment]
What does `geth version` print?

**Comment by stiv-yakovenko** [comment]
Yes, the reason was 32bit version. Why don't we put a warning in console to 32bit version to propose user to migrate to 64bit if he starts mining?

**Comment by parth5049** [comment]
Hello stiv-yakovenko,
I am also facing the same issue and could not start the miner process. The same error I get as you mentioned. How do you check whether installed geth version is for 32bit or 64bit? 
My version of geth is 1.7.2 and following is the output of the command `geth version`.
`$ geth version
Geth
Version: 1.7.2-stable
Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
Architecture: 386
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9
`
I am running the node on Ubuntu 16.04 LTS, 4 GB RAM, 4 GB Swap, Intel i3 processor.

**Comment by stiv-yakovenko** [comment]
@parth5049 , Architecture: 386 probably means that you are running 32bit version.

**Comment by parth5049** [comment]
Thanks @stiv-yakovenko for the timely reply,
Yes you are right, actually I installed 32bit OS on 64bit machine. 
Let me install new OS. Thanks a lot.

**Comment by adamschmideg** [comment]
Closing the ticket, since installing the 64bit version solved the problem.
