### ISSUE TITLE
endless geth synchronization

### ISSUE THREAD

**Issue by porfavorite** [ethereum/go-ethereum#14787]
#### System information

Geth version: `1.6.6`
OS & Version: Linux
I'm using HDD.

#### Expected behaviour
Successful synchronization

#### Actual behaviour
Endless "imported new state entries count=..."

#### Steps to reproduce the behaviour
I tried `geth --testnet --fast --cache=1024`
Also tried `geth --testnet --cache=1024`

**Comment by sonulrk** [comment]
Possible duplicate of issue #14647  . Also please refer to these issues #14608 , #14626 , #14653

**Comment by sg552** [comment]
1.  use parity 
2.  make sure your harddisk is SSD.
3. Memory > 4GB at least. 
4. multiple core CPU

**Comment by adamschmideg** [comment]
It's been inactive for quite long and it's about an old version. If the problem still persists with a recent version, please open a new issue.
