### ISSUE TITLE
Geth will not complete sync

### ISSUE THREAD

**Issue by stevea32** [ethereum/go-ethereum#14781]
#### System information

Geth version: Geth/v1.6.6-stable-10a45cb5
OS & Version: Windows 10
I've tried to sync blockchain for about 3 weeks and no matter what I do it does the same thing.
Use removedb then use --fast it'll finish sync. Nope same thing
Use Mist. Nope same thing
Its because you need an SSD. Oh a hard drive will get within 100 blocks but to get all synced up you HAVE to have an SSD. I dont think so.
Start geth then open your wallet. Nope same thing.
I've tried everything I could find on the net to sync the blockchain and nothing has worked. I've gotten only as close to 48 blocks of being synced then all geth does is import new state entries (does that have anything to do with syncing the chain?) and drop peers. The worst part of the whole experience is nobody has an answer for this problem, I have seen so many other people posting the same problem and they never get an answer that fixes the problem. So, I'm beginning to wonder if the chain was designed to only have so many nodes and stop new people from creating new nodes.
A solution will be greatly appreciated or at least someone acknowledges that there is a problem and they are working on a solution.

![image](https://user-images.githubusercontent.com/30041008/28011363-aab4e8f6-6527-11e7-9f13-1e8934cbda00.png)

**Comment by pheuter** [comment]
Running into the same exact issues using **geth 1.6.6-stable-10a45cb5** on Windows 10 with:
`$ geth.exe --syncmode fast`.

It gets 99.99% of the way there relatively easily and then for the remainder 1000 blocks or so just poops out, frequently dropping peers and failing to make any progress.

Any guidance greatly appreciated.

**Comment by wallaceturner** [comment]
yep same, have tried twice on windows and once on linux with
>geth --fast --rpc
it gets almost there then never makes it. `eth_blocknumber` always returns 0x0
@vbuterin ?

**Comment by smalaichami** [comment]
Update your geth to v1.7.2 and run the sync  geth --fast --rpc   this might solve your problem.. 
https://geth.ethereum.org/downloads/

**Comment by wallaceturner** [comment]
@smalaichami I am already running the latest. My recreate is
1) install ubuntu 16.04.3
2) install geth latest v.1.7.2
3) run geth --fast --rpc

**Comment by 3esmit** [comment]
I'm experiencing high sync time, but probably because my internet is slow (2 MB/s) and this makes peers kick me out :(

**Comment by WhiteHatCryptoMiner** [comment]
Hi, we are using hardware ETH NODEs to sync up our miners and wallets. If you would be interested in getting more info, contact me via PM.

**Comment by SkippOtter** [comment]
Having the same issue. 
geth 1.7.3
ubuntu 16.04
command: geth --syncmode="fast" --cache=4096

It's been syncing for almost 2 weeks now, and it gets to within 100 of the highest block in about a day and a half.  It then switches to importing state entries, and imports 70,000,000 or so in a couple more days. Now it is just kinda not doing nything.

eth.syncing shows that the synced blocks are within 100 blocks of the highest block. The numbers will go up as the blockchain goes up, but my synced block will always be ~100 from the highest know. My balance also still shows 0 locally, but I have a balance via lookup on a blockchain explorer, so i know that it has not finished syncing.

We really need an answer to this.

**Comment by theGandalfOfLapland** [comment]
I am also trying to sync in fast mode with 2 different computers. Fresh installs. It loads the blocks in like 10 hours and then gets stuck like 200-100 blocks from total sync.
(Light chain has no peers and will not sync..it was working fine like a month or two ago.)
Closest i got was 49 blocks from heaven. We need help..how can we solve this?

**Comment by theGandalfOfLapland** [comment]
I am using geth 1.7.3.

**Comment by holiman** [comment]
The upcoming 1.9 release will improve the fast sync quite a lot. All the changes are not yet in `master`, but even so, the master is already a hefty improvement (but more is to come). I'm closing this, since the original report is on an ancient version.
