### ISSUE TITLE
account unlocked but unable to make transaction via geth console

### ISSUE THREAD

**Issue by roo2** [ethereum/go-ethereum#14780]
#### System information

Geth/v1.6.6-stable-10a45cb5/linux-amd64/go1.8.1
Geth version: `v1.6.6-stable-10a45cb5`
OS & Version: linux-amd64
Commit hash : `10a45cb5`

#### Expected Behavior
After unlocking my account I am able to make a transaction from an *attached* geth client. However I *AM* able to make transactions via rpc

#### Actual Behavior
I get an error: 

````
Error: could not decrypt key with given passphrase
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
````

#### Steps to reproduce the behaviour

````
> personal.unlockAccount(eth.accounts[2], "thepassword", 150000)
true
> personal.sendTransaction({from:eth.accounts[2], to: eth.accounts[1], value: 20000000})
````

#### Backtrace

````
Error: could not decrypt key with given passphrase
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
````

#### More Info:
I'm running geth with a private testnet and attaching to it using `geth attach`

```bash
geth --datadir .ethereum-test --rpc --rpcapi eth,net,web3,personal --rpccorsdomain http://localhost:3000 \
 --etherbase 0xf3a973e9aa30199d715dda4802c16c182667cbd4 --networkid 123039281 \
 --password .testnet-password \
 --unlock 1febb79b4add1f6d8aa5865c3341df8d94a49382,42b2a971661f385387d5106a6a2be45b312c0c4b,f3a973e9aa30199d715dda4802c16c182667cbd4 
--bootnodes $TESTNET_BOOTNODES js ./scripts/mine.js

# and in another tab
geth attach ipc:.ethereum-test/geth.ipc

```

**I am still able to make transactions with the account via rpc**

I believe [this stackoverflow question](https://ethereum.stackexchange.com/questions/12446/can-unlock-account-but-not-send-transaction) is related, Originally asked 4 months ago

**Comment by MIGUELWAXX** [comment]
multiple platforms

**Comment by karalabe** [comment]
The `personal.sendTransaction` method expects a second argument, the password to ephemerally unlock the account with and send the transaction in one go. If you don't provide a password, this endpoint defaults to the empty password, resulting in your issue.

If you want to use an already unlocked account to send a transaction (instead of the ephemeral unlock-and-send), you can do so with `eth.sendTransaction`.

**Comment by cloud197** [comment]
from the mouth of a thief
