### ISSUE TITLE
QUESTION: GETH node modifications

### ISSUE THREAD

**Issue by Dexaran** [ethereum/go-ethereum#14793]
I'm wondering about is here any way to obtain internal transactions. 

I have read that there is no way to obtain internal transactions without making GETH node modifications:
> Blockchain explorers like etherscan obtain them by running a modified node with an instrumented EVM

Source: https://ethereum.stackexchange.com/questions/3417/how-to-get-contract-internal-transactions

Is it true?

**Comment by karalabe** [comment]
You can run the javascript tracer `debug_traceTransaction` and collect whatever information you need from a transaction's runtime. But you do need to have the state at that point in time, otherwise it's not possible to re-execute the transaction.
