### ISSUE TITLE
Usb / Ledger Support causes mouse to disapear

### ISSUE THREAD

**Issue by smurfy** [ethereum/go-ethereum#14797]
#### System information

Geth version: `1.6.6` (version mist autoupdates)
OS & Version: Windows 10 64bit

#### Expected behaviour
Geth should not interfere with mouse. 

#### Actual behaviour
Mouse cursor disapears, jumps to lower right corner of screen, clicks register but cursor not visible and mouse pos does not change.

#### Steps to reproduce the behaviour
- Mouse: Zelotes 5500 

#### Additional Info
--nousb "fixes" the problem, but since i bought a ledger nano i can't use it with geth.
I'm happy to test tweaked versions of geth
Also i have the problem on two different win10 computers. but with the same mouse models.

**Comment by karalabe** [comment]
Hah, nice :) I've never seen such funky behavior. We only ever try to communicate with USB devices advertising themselves as ledgers though, odd that your mouse is ever touched. Does it do similar strange issues if you plug in a different mouse?

**Comment by smurfy** [comment]
> Hah, nice :) I've never seen such funky behavior.

Yea was quite irritating after a geth autoupdate via mist, mouse acting up :) first i did not realise it was geth.  Switched back to a 1.5.x version till i noticed the --nousb flag in a newer 1.6.x version.

I will do some more tests tonight, found an old microsoft usb mouse i can test with.

> We only ever try to communicate with USB devices advertising themselves as ledgers though

Yea i noticed that in the code, i compared the vid/pid's but they where different to my mouse (as they should be).  Maybe its the scan rate or something. i  try to get a build environment going on the weekend to try different things. (decrease scan rate, write to log for each usb interaction to see what exact command is responsibly)

**Comment by smurfy** [comment]
Update:

Ok its related to the specific mouse, after changing the code, that it only enumerates for ledger vendor id the error does not occur anymore.

```
for _, info := range hid.Enumerate(0x2c97, 0) { // Can't enumerate directly, one valid ID is the 0 wildcard
```

I will do more testings, also with my ledger nano s, if it still works with that change.
I'm not sure if this is a change/fix you guys as the authors like but since its a "ledger_hub", which creates "ledger_wallets" i guess restricting the enumeration to only the ledger vendor id should by ok.

**Comment by rguillome** [comment]
I'd the same strange behaviour with an HP keyboard installed with the standard Keyboard driver. After a while, the keyboard doesn't react to actions (but still powered)

**Comment by smurfy** [comment]
Yay! i'm not alone :)  As i mentioned before, the problem disappeared after changing that it only enumerates for ledger devices.

But it seems that a newer mist version also has the problem. but i did not investigate further, mainly using geth on commandline.

**Comment by rguillome** [comment]
I'd the same strange behaviour with an HP usb keyboard installed with the standard PS/2 compatible drivers. After a while, the keyboard doesn't react to touch pressing but seems still powered (the verrnum lock light still bright).

**Comment by karalabe** [comment]
This should be fixed on latest master a while now.

**Comment by smurfy** [comment]
It seems the problem has been corrected within geth itself. (No problems and my ledger is recognised)

Sadly I still have the problem, because of swarm, started by mist. it still uses 1.6.7 swarm not the 1.7.0 swarm. But this is a mist problem not geth.

**Comment by 92161898515** [comment]
Resolvido
--
Enviado da aplicação Mail.Ru para Android terça-feira, 26 setembro 2017, 06:34da tarde -03:00 de Philipp Andreas  notifications@github.com :
