### ISSUE TITLE
Anything i can do, to get Blocks faster?

### ISSUE THREAD

**Issue by Marow** [ethereum/go-ethereum#14796]
Hi, is there anything, to optimize GETH to get Blocks faster?
Over 200% Variance and dont get a block. 

Others get blocks with 5-50% and i am Mining 12 Hours for nothing...

So i will check if i can make it faster with 100% RAM or any command for geth?

**Comment by yv989c** [comment]
@Marow I always start geth with the --cache 1024 flag, may be it may help you.
`geth --cache 1024`

**Comment by stevea32** [comment]
Were you able to sync completely?If so, how?

**Comment by RichHorrocks** [comment]
Ideally ask questions on https://ethereum.stackexchange.com - it is important to keep issue-trackers clear and for real issues only.
