### ISSUE TITLE
Events not working (for me)

### ISSUE THREAD

**Issue by stiv-yakovenko** [ethereum/go-ethereum#14795]
This is how I run geth 1.6.6-stable on Windows 7:

`C:\Users\steve\AppData\Roaming\Mist\binaries\Geth\unpacked\geth.exe --testnet --fast --ipcpath \\.\pipe\geth.ipc --rpccorsdomain * --rpcport 8545 --rpc`
I have ETH on my account on testnet, account is unlocked.

and this is my contract:

```
pragma solidity ^0.4.0;
contract MainContract{
    event Evt(address indexed _sender,string jsn);
    function deposit(string jsn) returns (int256) {
        Evt(msg.sender, jsn);
    }
}
```

This is my js code, which I run inside browser on page load:

        var abi = [ ... // my abi here
        web3.eth.defaultAccount = '0x6c92C4201bBaFE97011C9EA9144c907Fd16F5089';
        var contract = web3.eth.contract(abi).at("0x6c92C4201bBaFE97011C9EA9144c907Fd16F5089");
        contract.Evt({}).watch(function (error, result) {
            console.log("on watch");
            console.log(arguments);
        });
        contract.Evt({}).get(function (error, result) {
            console.log("on get");
            console.log(arguments);
        });
        contract.deposit('hello there', function (res) {
            console.log("on deposit");
        });

contract.deposit is executed sucessfully, i get tx number and i can see my transaction: 

https://ropsten.etherscan.io/tx/0xf303fa1ae8f52d245f20bcbf63d1c766e486a22b9fafc55819af473ce827a0ef

If I restart my app, 'on get' callback is invoked,but result is always empty array. My second callback 'on watch' is never invoked at all. Why is this? I want to monitor all created events, is it possible? How can I implement this? 

Thanx!

**Comment by illuzen** [comment]
I think you need to put a filter in there {fromBlock:0, toBlock: 'latest'} instead of an empty object. Also, sometimes it takes a while to get events from the entire chain, so maybe don't start at 0. Also Ropsten is unreliable, maybe run your own testnet for these things.
