### ISSUE TITLE
Trying to set up go-ethereum and running in to some road blocks

### ISSUE THREAD

**Issue by rayto** [ethereum/go-ethereum#14805]
#### System information

OS & Version: Ubuntu 16.04 32 bit

This is a noob question (I apologize).

After setting up go and running the hello world program (no problems there) I run:
`go get -d github.com/ethereum/go-ethereum`
in the terminal and it gives me:
`can't load package: package github.com/ethereum: no buildable Go source files in /home/rayto/go/src/github.com/ethereum`
Why is this happening? I have added this line to my profile:
`export PATH=$PATH:/usr/local/go/bin`

Just hoping to understand ethereum classic and hopefully contribute too.

Thanks

**Comment by RichHorrocks** [comment]
Ideally ask questions on https://ethereum.stackexchange.com - it is important to keep issue-trackers clear and for real issues only.
