### ISSUE TITLE
Update wiki documentation with eth.hashrate

### ISSUE THREAD

**Issue by alanbuxton** [ethereum/go-ethereum#14802]
Suggest changing references from 

miner.hashrate 

to

eth.hashrate 

on 

https://github.com/ethereum/go-ethereum/wiki/mining

as according to https://github.com/ethereum/go-ethereum/issues/2591, miner.hashrate has been removed

**Comment by zhoujianwei** [comment]
support

**Comment by Feuda** [comment]
Still

**Comment by fstark** [comment]
Just lost 30 minutes thank to that. What is so difficult in updating a wiki ?

**Comment by adamschmideg** [comment]
@fstark We moved the documentation to [gh-pages](https://github.com/ethereum/go-ethereum/tree/gh-pages). Feel free to open a PR.

**Comment by fjl** [comment]
[Fixed](https://github.com/ethereum/go-ethereum/commit/fedcdbc2dbcc17684d679c9cad747a5cc10ae7c6)
