### ISSUE TITLE
Error starting protocol stack: read input/output error

### ISSUE THREAD

**Issue by porunov** [ethereum/go-ethereum#14803]
#### System information

Geth version: `1.6.7-stable`
OS & Version: Debian GNU/Linux 9

#### Expected behaviour

Run geth

#### Actual behaviour

```
INFO [07-13|20:54:37] Starting peer-to-peer node               instance=Geth/v1.6.7-stable/linux-amd64/go1.8.1
INFO [07-13|20:54:37] Allocated cache and file handles         database=/home/alex/.ethereum/geth/chaindata cache=128 handles=1024
Fatal: Error starting protocol stack: read /home/alex/.ethereum/geth/chaindata/MANIFEST-5686306: input/output error
```

#### Steps to reproduce the behaviour

`geth --rpc console`

**Comment by vvarr10r** [comment]
Did you make any progress with this? I'm operating in the same environment with an external hard drive mounted and formatted to exfat. The chaindata is already on the hdd. I have this problem when the correct symlinks are in place so geth uses the chaindata on the external drive. Geth works when the symlinks aren't present.

**Comment by porunov** [comment]
Unfortunately no. Couldn't fix this issue.

**Comment by owap** [comment]
Having the same error with an NFS mount, despite accounting for different users and permissions

**Comment by lnogue** [comment]
Same problem here, and another thousand problems with this software.

**Comment by partyka1** [comment]
Had similar problem, I wanted to run geth datadir on external exfat disk. For me worked using --ipcpath, so that datadir is on exfat, but ipc is located on local osx drive

**Comment by holiman** [comment]
IPC is a unix socket, it's not certain that symlinks will work. I have successfully run geth on different datadirs using NFS mounts on kubernetes. I'll close this, since original report is from 2017. Feel free to open a new ticket if needed.

**Comment by dudisathyablockchain** [comment]
Some problem while trying to full node sync 

INFO [11-13|09:34:57.413] Bumping default cache on mainnet         provided=1024 updated=4096
WARN [11-13|09:34:57.414] Sanitizing cache to Go's GC limits       provided=4096 updated=2639
INFO [11-13|09:34:57.418] Maximum peer count                       ETH=25 LES=0 total=25
INFO [11-13|09:34:57.418] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [11-13|09:34:57.446] Starting peer-to-peer node               instance=Geth/v1.9.7-stable-a718daa6/linux-amd64/go1.13.4
INFO [11-13|09:34:57.446] Allocated trie memory caches             clean=659.00MiB dirty=659.00MiB
INFO [11-13|09:34:57.446] Allocated cache and file handles         database=/home/.ethereum/geth/chaindata cache=1.29GiB handles=2048
Fatal: Error starting protocol stack: read /home/.ethereum/geth/chaindata/098167.ldb: input/output error

We are using current Geth 1.9.7 stable release and using Ubuntu 18.04 bionic OS.
