### ISSUE TITLE
Missing bootnode executable on MacOS 

### ISSUE THREAD

**Issue by elluminatte** [ethereum/go-ethereum#14811]
#### System information

Geth version: `1.6.6`
OS & Version: macOS Sierra 10.12.5

#### Expected behavior

After installation via Homebrew running "_bootnode_" command in terminal should display 

> Fatal: Use -nodekey or -nodekeyhex to specify a private key

#### Actual behavior

After installation via Homebrew running "bootnode" command in terminal displays

> -bash: bootnode: command not found

Regards, Nikolay

**Comment by agarcian** [comment]
Is there a workaround for this?

**Comment by elluminatte** [comment]
@agarcian 
i've made this change to make it work: https://github.com/elluminatte/go-ethereum/commit/9dbb597226d492085c7412f7ffdee2d5ab63dac1#diff-b67911656ef5d18c4ae36cb6741b7965
Not sure that it's correct decision and that it's still actual, but it helped me

**Comment by adamschmideg** [comment]
This is by design. Most users don't want to run `bootnode` on a Mac. If you need it, you can still build it. Adding `bootnode` to brew would result in 40 MB for all users.
If you have a good use case to include it, please open a ticket.
