### ISSUE TITLE
personal.unlockAccount takes 5+ minutes and times out

### ISSUE THREAD

**Issue by richiela** [ethereum/go-ethereum#14810]
#### System information

Geth version: 1.6.7
OS & Version: Ubuntu 16.04
Commit hash : (if `develop`)

#### Expected behaviour
unlock should take sub second

#### Actual behaviour
personal.unlock takes 5+ minutes 

#### Steps to reproduce the behaviour
I'm not sure how to repro, but opening a bug in hopes of getting more eyes on it.  Our system has 200k+ accounts.  Periodically through out the day, calling personal.unlockAccount times out and then takes minutes to complete.  It usually goes back to "normal" after 15 or so minutes.  During this time, blocks are still coming in, CLI is still responsive, but jsonrpc stops responding.  It almost feels like its rescanning disk for something and tying up the disk.  iotop output shows the process 99% waiting for disk I/O, but i'm only seeing read speeds of 2M/s.  Other geth threads still read from disk.

Here is some custom debug log demonstrating the behavior (desc by date):

Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 45 ms sendDuration 5418 ms	0	2017-07-15 04:56:35.500
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 38 ms sendDuration 7048 ms	0	2017-07-15 04:56:30.030
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 41 ms sendDuration 3892 ms	0	2017-07-15 04:56:22.923
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 39 ms sendDuration 308015 ms	0	2017-07-15 04:56:18.987
Ethereum.Deposit:  Send Failed :System.Net.WebException: The operation has timed out
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 49 ms sendDuration 309255 ms	0	2017-07-15 04:51:10.973
Ethereum.Deposit:  Send Failed :System.Net.WebException: The operation has timed out
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 37 ms sendDuration 310512 ms	0	2017-07-15 04:46:01.670
Ethereum.Deposit:  Send Failed :System.Net.WebException: The operation has timed out
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 40 ms sendDuration 249251 ms	0	2017-07-15 04:40:51.180
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 37 ms sendDuration 0 ms	0	2017-07-15 04:36:41.947
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 40 ms sendDuration 0 ms	0	2017-07-15 04:36:41.913
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 37 ms sendDuration 0 ms	0	2017-07-15 04:36:41.867
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 42 ms sendDuration 0 ms	0	2017-07-15 04:36:41.837
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 40 ms sendDuration 0 ms	0	2017-07-15 04:36:41.773
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 40 ms sendDuration 0 ms	0	2017-07-15 04:36:41.743
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 39 ms sendDuration 0 ms	0	2017-07-15 04:36:41.697
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 40 ms sendDuration 0 ms	0	2017-07-15 04:36:41.650
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 41 ms sendDuration 0 ms	0	2017-07-15 04:36:41.600
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 44 ms sendDuration 0 ms	0	2017-07-15 04:36:41.570
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 48 ms sendDuration 120853 ms	0	2017-07-15 04:36:41.510
Ethereum.Deposit finished block processing 18 addresses to sweep.	0	2017-07-15 04:34:40.617
Ethereum.Deposit starting block processing	0	2017-07-15 04:32:39.430
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 38 ms sendDuration 1300 ms	0	2017-07-15 04:30:33.903
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 38 ms sendDuration 1348 ms	0	2017-07-15 04:30:32.560
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 41 ms sendDuration 1308 ms	0	2017-07-15 04:30:31.153
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 39 ms sendDuration 1266 ms	0	2017-07-15 04:30:29.810
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 37 ms sendDuration 1363 ms	0	2017-07-15 04:30:28.483
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 39 ms sendDuration 1266 ms	0	2017-07-15 04:30:27.077
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 41 ms sendDuration 1268 ms	0	2017-07-15 04:30:25.750
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 39 ms sendDuration 1354 ms	0	2017-07-15 04:30:24.390
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 41 ms sendDuration 1327 ms	0	2017-07-15 04:30:22.937
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 43 ms sendDuration 1364 ms	0	2017-07-15 04:30:21.563
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 38 ms sendDuration 0 ms	0	2017-07-15 04:30:20.140
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 43 ms sendDuration 0 ms	0	2017-07-15 04:30:20.080
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 41 ms sendDuration 0 ms	0	2017-07-15 04:30:20.017
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 40 ms sendDuration 0 ms	0	2017-07-15 04:30:19.970
Ethereum.Deposit: swept 0xredactedaddressaaaaaaaaaaaaaaaaaaaaaaaaa : getBalanceDuration 39 ms sendDuration 0 ms	0	2017-07-15 04:30:19.923
Ethereum.Deposit finished block processing 15 addresses to sweep.	0	2017-07-15 04:30:19.860

#### Backtrace

````
[backtrace]
````

**Comment by richiela** [comment]
During the time of unresponsiveness, lsof reports over 37k file handles open as well.

**Comment by richiela** [comment]
More iotop information

  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
22205 be/4 101001      2.37 M/s    0.00 B/s  0.00 % 96.74 % geth --datadir /wallets/ethcoin --fast --verbosity 3 --rpc --rpcaddr 0.0.0.0 ~ef42f520fbb98 --targetgaslimit 1000000 --cache 1024 --txpool.accountqueue 8192
35313 be/4 101001     26.06 M/s   25.93 M/s  0.00 % 56.14 % geth --datadir /wallets/ethcoin --fast --verbosity 3 --rpc --rpcaddr 0.0.0.0 ~ef42f520fbb98 --targetgaslimit 1000000 --cache 1024 --txpool.accountqueue 8192
59817 be/4 101001    321.70 K/s    0.00 B/s  0.00 %  7.83 % geth --datadir /wallets/ethcoin --fast --verbosity 3 --rpc --rpcaddr 0.0.0.0 ~ef42f520fbb98 --targetgaslimit 1000000 --cache 1024 --txpool.accountqueue 8192


One thread of geth reads @ only 2m/s even though other threads are reading at a much higher rate.  Its like a slow seek that the process is waiting for that locks up the process

**Comment by richiela** [comment]
More data.  Recently, i copied a large amount of new key material into the geth keystore directory  (for ETC though).  On the first RPC call i observed the same behavior; the jsonrpc interface stops responding, and iotop shows 99% wait for disk io even though its only reading at 2M a sec.  Like a full rescan of the accounts directory.  Does geth, at any time, do a full rescan for key material?   if so what triggers it?  This behavior is sporadic.  It may not happen for 24-36 hours, but then lock up 3 times in 24 hours.

**Comment by richiela** [comment]
ok, this bug is tied directly to address generation.  We have over 250k of key material in keystore.  I disabled address generation for a couple hours to fix something else.   As soon as i turned on address generation, the daemon went on that slow scan and hung the daemon.

**Comment by richiela** [comment]
Confirmed, with address generation turned off, daemons runs smoothly with no hiccups.  As soon as we create new addresses, the daemon goes into a weird rescan mode.  Once the daemon is in this state, it stays there indefinitely.  If you restart geth, address generation will work fine for a couple hours until it hits this rescan state.

**Comment by holiman** [comment]
So, every fs event on the keystore folder will trigger the account cache to reload  https://github.com/ethereum/go-ethereum/blob/master/accounts/keystore/watch.go#L103 . 

But it won't do it more often than every 2 seconds https://github.com/ethereum/go-ethereum/blob/master/accounts/keystore/account_cache.go#L39

The `reload` action holds a mutex, which probably explains why no signing can happen during this time (e.g. the `accounts()` method requires the same mutex: https://github.com/ethereum/go-ethereum/blob/master/accounts/keystore/account_cache.go#L88). 

If it's simply the `scan` which takes time, it would be a simple fix to move the `scan` phase outside the mutex-protected area, and only take the mutex when we start meddling with  `ac.all`.

@richiela , how many json-files are we talking about? I'd like to reproduce and do some measurement/experimentation.

**Comment by holiman** [comment]
I tested with 250K account-files, the `scan` operation takes about 45 seconds on my computer (ssd).

**Comment by richiela** [comment]
We have a little over 250k.  Can you try unlocking the accounts on the fs (with and without timeouts) as well?  When I was testing this, if we started geth fresh, i could go into account creation mode, and it would work for a little while before locking up.  Usually between 300-900 accounts.

However, if i started geth, left account creation off, but let the daemon work for a while;  meaning, it was sending transactions, unlocking accounts, reading transactions etc.  I couldn't even create one account without the daemon locking up.

I'm thinking maybe its a combination of using the daemon and the number of json files as well since the behavior wouldn't reproduce on a newly started geth instance without "work" till much later.

**Comment by holiman** [comment]
I can't really unlock them, it's not real accounts, just json-lookalikes. I can imagine that the effects vary wildly, with different caching on the actual disks. I also didn't connect to any peers, and didn't have several thousand chaindata files open, so I can imagine a production scenario where this has a lot worse effect. 

If you're feeling adventurous, please try out the patch. But if you're not feeling adventurous, I'd wait until @fjl or @karalabe give it a :+1:

**Comment by holiman** [comment]
Potential fix: https://github.com/ethereum/go-ethereum/pull/15171
