### ISSUE TITLE
Error using JSON-RPC

### ISSUE THREAD

**Issue by jinglics** [ethereum/go-ethereum#14818]
#### System information

Geth version: 1.6.7
OS & Version: Linux

I update to 1.6.7, my working well node now has error, when I send request RPC
INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised: invalid argument 0: hex string without 0x. 
My parameters are correct with prefix "0x"

**Comment by karalabe** [comment]
Could you please share the RPC call that's failing?

**Comment by jinglics** [comment]
I made a mistake. Now all work. Thanks
