### ISSUE TITLE
private network contract create 

### ISSUE THREAD

**Issue by PHPJourney** [ethereum/go-ethereum#14820]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

in my computer, I am create private chain. then create contract.

wait now, 3 Hours later, still in creation

what question？

**Comment by karthiknvlr** [comment]
Hi @PHPJourney 
Have you started mining in your private chain?

**Comment by PHPJourney** [comment]
@karthiknvlr  yes, iam in private-net?
This question is ok.

**Comment by AdwindOne** [comment]
You can  on  console exec command   miner.start()

**Comment by PHPJourney** [comment]
#AdwindOne me?
yes , i can . before can't syncing complate.

now new question is json-rpc exec command contract for php

i'm trying.

**Comment by RichHorrocks** [comment]
Ideally ask questions on https://ethereum.stackexchange.com - it is important to keep issue-trackers clear and for real issues only.
