### ISSUE TITLE
Geth 'sendTransaction' not working for some transactions while making much transactions in a loop

### ISSUE THREAD

**Issue by himanshuoodles** [ethereum/go-ethereum#14828]
#### System information

Geth version: `1.5.9`
OS & Version: Linux (Ubuntu 14.04)

#### Expected behaviour
We are making 200 transactions in a loop for sending ether from one address to another address, all transaction should execute and return either success or fail.

#### Actual behaviour
Some transactions are not executing i.e. we are not getting any results for those transactions neither success nor fail.

#### Steps to reproduce the behaviour

Make 200 transactions in a loop to send ether from one address to another address
eth.sendTransaction({
                        from: privateWeb3.eth.coinbase,
                        to: result,
                        value: privateWeb3.toWei(2, 'ether')
                    }
check total no of results.
Total no of results will be less than total no. of transactions given

**Comment by karalabe** [comment]
Please update to latest Geth. There have been lots and lots of transaction pool and nonce assignment issues fixed in the past few releases.

**Comment by alanbuxton** [comment]
I am seeing similar behaviour with geth 1.6.7-stable-ab5646c5
