### ISSUE TITLE
Get accounts count

### ISSUE THREAD

**Issue by xallavon** [ethereum/go-ethereum#14822]
Is there a simple way to get the amount of accounts in local keystore via JSONRPC API other than making ```eth_accounts``` request and counting them manually?

**Comment by karalabe** [comment]
Well, any decent library that you request the accounts with should be able to give you back the length of a simple array.

**Comment by xallavon** [comment]
Of course, getting the length of an array is easy. But assuming i have some 100k+ accounts and want to check the exact amount often enough, it doesn't seem reasonable to send all this data each time. That's why I hoped, there's something like ```eth_totalAccounts``` which could give me exactly what I need :)

**Comment by karalabe** [comment]
Well, if you maintain 100K accounts, I guess you also maintain them outside your node ;) Joke's aside, I don't think there's a legitimate reason for adding such a feature. Also, you can always attach with a `console` to a running geth instance, where you could count them on the "server" side.
