### ISSUE TITLE
Whisper Protocol shh io error

### ISSUE THREAD

**Issue by karthiknvlr** [ethereum/go-ethereum#14829]
#### System information

Geth version: `geth version 1.6.5 `
OS & Version: Ubuntu 16.04

When I run 
```terminal
shh.subscribe({type:'asym',pow:12.3,topics:['0x5a4ea131','0x11223344'],key:'9a0497ccb5a12b37e2c7806caec404048f60ff41d6db14cee72d4d1acd4b8fda'})
```

the command in geth console it was producing 
Error: io: read/write on closed pipe
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1

What is this error and how to solve this?

**Comment by karalabe** [comment]
@bas-vk ?

**Comment by karthiknvlr** [comment]
@karalabe  I was trying to send messages between nodes in private blockchain using whisper protocol when I execute```terminal
shh.subscribe({type:'asym',pow:12.3,topics:['0x5a4ea131','0x11223344'],key:'9a0497ccb5a12b37e2c7806caec404048f60ff41d6db14cee72d4d1acd4b8fda'})
```
command it was showing 
Error: io: read/write on closed pipe
at web3.js:3104:20
at web3.js:6191:15
at web3.js:5004:36
at :1:1 this error

**Comment by Fang-Li** [comment]
Also encountered the above problems

**Comment by Fang-Li** [comment]
when i perform “admin.addPeer("enode://d25474361659861e9e651bc728a17e807a3359ca0d344afd544ed0f11a31faecaf4d74b55db53c6670fd624f08d5c79adfc8da5dd4a11b9213db49a3b750845e@52.178.209.125:30379")”

**Comment by Fang-Li** [comment]
geth version 1.6.6
shh version 5

**Comment by gballet** [comment]
@Fang-Li do you still see this issue with geth 1.8+ and whisper v6 ?

**Comment by gballet** [comment]
No answer, closing this issue.
