### ISSUE TITLE
Some transactions are not getting mined in in private ethereum blockchain network of 4 peer nodes 

### ISSUE THREAD

**Issue by himanshuoodles** [ethereum/go-ethereum#14830]
#### System information

Geth version: `1.5.9`
OS & Version: Linux ( Ubuntu - 14.04)

#### Expected behaviour
All transactions should be mined.

#### Actual behaviour
We are getting transactionHash for all transactions but some of those transactions are not getting mined.

#### Steps to reproduce the behaviour
Make 200 transactions in private blockchain of 4 peer nodes connected to each other, note down txHash corresponding to each transaction, later first confirm that all 4 nodes have synced i.e. total no of blockNumber is same for all four peers nodes. Now check all transactions, some of these will return null
as we do "eth.getTransaction(txHash)" i.e those transactions are not mined. 
Why is it like this ?
Please give some solution for this and the reason for this issue, so that we can ensure smooth workng before going live.

**Comment by karalabe** [comment]
Please use Geth 1.6.7. There have been a lot of transaction fixes included in the past releases.

**Comment by mohitsharma18** [comment]
Having the same issue in Geth 1.6.7, any solution please...

**Comment by karalabe** [comment]
Try master :) Again, a ton of fixes have been added. Also please open a new issue if it persists and be more specific that "same issue", so we might debug it. Thanks
