### ISSUE TITLE
Geth >= 1.6.5 Continuously filling up disks

### ISSUE THREAD

**Issue by mikeshultz** [ethereum/go-ethereum#14839]
I'm not even sure this is a bug, but this only seemed to start at version 1.6.5, but I keep continuously filling up disks as large as 128GB in under a week.

#### System information

Earliest version I have running showing the problem: 

Geth
Version: 1.6.5-stable
Git Commit: cf87713dd42162861b7ed227f79f0638a33571df
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

#### Expected behaviour

chaindata to initially sync to ~15GB and slowly grow larger with time.

#### Actual behaviour

chaindata grows until disk full.  Tested with a disk up to 128GB.  

#### Steps to reproduce the behaviour

`geth --syncmode fast`

#### Observations

The only thing I've noticed is more of these messages since this problem started: 

    Jul 08 05:52:46 node0.example.com geth[16077]: INFO [07-07|22:52:46] Imported new chain segment               blocks=1  txs=25  mgas=0.922  elapsed=42.560ms  mgasps=21.663   number=3991664 hash=b72db7…01
    Jul 08 05:52:52 node0.example.com geth[16077]: INFO [07-07|22:52:52] Imported new chain segment               blocks=1  txs=252 mgas=6.002  elapsed=587.628ms mgasps=10.213   number=3991665 hash=b3a85b…be
    Jul 08 05:53:21 node0.example.com geth[16077]: INFO [07-07|22:53:21] Imported new chain segment               blocks=1  txs=48  mgas=1.027  elapsed=72.341ms  mgasps=14.190   number=3991666 hash=5230ad…5e
    Jul 08 05:53:25 node0.example.com geth[16077]: INFO [07-07|22:53:25] Imported new chain segment               blocks=1  txs=60  mgas=1.991  elapsed=77.224ms  mgasps=25.787   number=3991667 hash=409ea9…6b
    Jul 08 05:53:29 node0.example.com geth[16077]: INFO [07-07|22:53:29] Imported new chain segment               blocks=1  txs=225 mgas=6.162  elapsed=524.097ms mgasps=11.757   number=3991668 hash=4a81b9…91
    Jul 08 05:53:39 node0.example.com geth[16077]: INFO [07-07|22:53:39] Imported new chain segment               blocks=1  txs=29  mgas=0.876  elapsed=44.010ms  mgasps=19.915   number=3991669 hash=5ceee4…5f
    Jul 08 05:53:48 node0.example.com geth[16077]: INFO [07-07|22:53:48] Imported new chain segment               blocks=1  txs=6   mgas=0.139  elapsed=12.385ms  mgasps=11.258   number=3991670 hash=ec8a6e…d4
    Jul 08 05:53:52 node0.example.com geth[16077]: INFO [07-07|22:53:52] Imported new chain segment               blocks=1  txs=24  mgas=0.979  elapsed=37.906ms  mgasps=25.822   number=3991671 hash=6fc59c…45

Like I said, maybe this isn't a bug, but what I've been reading suggests storage should not be greater than ~20GB for most nodes, with slow LDB bloat happening over a longer period of time.  Right now, all of my nodes are filling disks in days or at most a week making any kind of reliability almost non-existent.

Let me know if there's more information I can provide.

**Comment by neuhaus** [comment]
I just had the same issue using geth 1.7.3 and `--syncmode fast` after a few days the directory `~/.ethereum/geth/chaindata` was 83GB in size.
