### ISSUE TITLE
vm create error: <nil>

### ISSUE THREAD

**Issue by nmushegian** [ethereum/go-ethereum#1483]
possibly relates to https://github.com/ethereum/go-ethereum/issues/1482

    I0717 01:52:24.386129   57434 state_object.go:206] af1136e5b3cbb87c645a71d947a286fc2733e0d2: #275 10805277050406443525888 (- 0)
    I0717 01:52:24.386141   57434 state_object.go:198] 0c08f3ad98e6718962ae94c40c0bd3a30353d90f: #0 0 (+ 0)
    I0717 01:52:24.386157   57434 state_transition.go:222] VM create err: <nil>

**Comment by fjl** [comment]
This is harmless.
