### ISSUE TITLE
eth_getLogs with address not returning anything

### ISSUE THREAD

**Issue by mbassan** [ethereum/go-ethereum#14837]
If I call the following through CURL:  

{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock":"0x3d940c","toBlock":0x3dcabf,"address":"0xdb0f455d8f252242563c9b550914d15b3f3d7943"}],"id":1}

I always get an empty array for results, even though there is a a transaction in the range:

https://etherscan.io/tx/0x8828a14ec6dfef43fabe54c2bb7a8f720c73e444ba53a33b4f9312c364a0f184

Am I missing something here? Or is this just basic functionality that doesn't work?

I can't get logs for any of my addresses no matter what. I can only pull every single transaction on the chain.

#### System information

Geth version: `1.6.7-stable-ab5646c5`
OS & Version: Ubuntu 14.04

#### Expected behaviour

Should return the transactions for the specified address within the range specified by fromBlock, toBlock.

#### Actual behaviour

Returns an empty array in 'result'. I also tried from block 0 to latest, and tried: (1) with no block parameters, (2) with address as an array, (3) with topics as an empty array.

#### Steps to reproduce the behaviour

Just run the above command through CURL.

#### Backtrace

````
[backtrace]
````

**Comment by EvilJordan** [comment]
@mbassan Did you figure out a solution to this? I'm having the same issue, but on the latest geth.

**Comment by mbassan** [comment]
Sort of. I wrote a custom function that I run through geth - - attach that
returns only the addresses that have a balance. I then check the
transaction using the etherscan api. I then sweep to one address to make
sure that this keeps making sense.
