### ISSUE TITLE
Impossible reorg, please file an issue

### ISSUE THREAD

**Issue by xnox** [ethereum/go-ethereum#14833]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

Run geth to sync blockchain 

#### What did you expect to see?
 
Getting latest block synced

#### What did you see instead?
 
ERROR[07-19|17:23:37] Impossible reorg, please file an issue   oldnum=4044398 oldhash=738a64…a27053 newnum=4044398 newhash=738a64…a27053

#### System details

Version: 1.6.7-stable
Go Version: go1.8.1
OS: linux
uname -sr: Linux 4.4.0-83-generic
LSB Version:	security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

**Comment by xnox** [comment]
ERROR[07-19|17:25:18] Impossible reorg, please file an issue   oldnum=4044523 oldhash=bbbb96…7697d3 newnum=4044523 newhash=bbbb96…7697d3

**Comment by markya0616** [comment]
For this issue, I think we need to add a check before writing blocks.
Please refer my PR, https://github.com/ethereum/go-ethereum/pull/14849

**Comment by thinhlvv** [comment]
I still encountered this issue in [version 1.8.27](https://github.com/ethereum/go-ethereum/releases/tag/v1.8.27) after running 3 weeks. 
It dropped all peers and disconnected from my network. 
My urgent solution is resync the blocks by removing dataset folder (except the keystore)
