### ISSUE TITLE
Transaction underpriced error message

### ISSUE THREAD

**Issue by vogelito** [ethereum/go-ethereum#14838]
#### System information

Geth version:
```Geth
Version: 1.6.7-stable
Git Commit: ab5646c532292b51e319f290afccf6a44f874372
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```
OS & Version: `Ubuntu 14.04.5 LTS, Trusty Tahr`

#### Expected behaviour
Calling `eth.sendTransaction` with a gas price as recommended by `eth.gasPrice` should successfully build and broadcast a transaction to the network.

#### Actual behaviour
Calling `eth.sendTransaction` with a gas price as recommended by `eth.gasPrice` returns the following error (via JSON-RPC): `transaction underpriced`

#### Steps to reproduce the behaviour
Our pseudo code:
```
tx = {
    "from": sending_address,
    "to": destination_address,
    "gas": 0x5208, // 21000,
    "gasPrice": eth_gasPrice(), // use whatever geth recommends
    "value": amount_to_send
};
hash = eth_sendTransaction(tx);
```

We had never seen this issue and we usually keep up with geth releases and had been previously running 1.6.6 without issues. We migrated to `1.6.7` just 3 days ago and we started seeing this issue for the first time yesterday.

This only happens sometimes and we haven't yet found a pattern.

**Comment by vogelito** [comment]
Wondering if this is related to the following commits 48ee7f9de7da0455b80ee09f498dbce54127103a 5e38f7a664aa5401117f1e1705ec97476b19411e 88b4fe7d21bf03bbe01961dc49508bcf4edafb51

**Comment by vogelito** [comment]
We can reproduce this pretty consistently. This happens when our sweeping process goes through all the accounts where users have deposited ETH and we sweep those funds into HW's and CW's. Downgrading to `1.6.6` solved the issue.

I wonder why we didn't see this error when we first migrated to `1.6.7`. But today the process has been failing very very consistently.

**Comment by vogelito** [comment]
Upon further investigation, this happens only when there are many accounts that need sweeping. If we reduce the time between sweeps, we don't seem to see this error as often.

**Comment by akosmaroy** [comment]
I'm getting the same error message, for no reason I can ascertain, using geth 1.6.7:

```
$  geth attach http://localhost:8545
Welcome to the Geth JavaScript console!

instance: Geth/v1.6.7-stable-ab5646c5/linux-amd64/go1.8.1
coinbase: 0xde546d04a80b9c99ec8afad401fe48f7ced35460
at block: 4218640 (Wed, 30 Aug 2017 06:03:02 CEST)
 datadir: /home/geth/.ethereum
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> eth.syncing
false
> web3.fromWei(eth.getBalance(eth.coinbase), "ether")
10.00923938130458291
> personal.unlockAccount(eth.coinbase, "XXX")
true
> eth.sendTransaction({from:eth.coinbase, to:"XXX", value: web3.toWei(10, "ether")})
Error: transaction underpriced
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
> eth.sendTransaction({from:eth.coinbase, to:"XXX", value: web3.toWei(10, "ether"), gas:100000})
Error: transaction underpriced
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
> eth.sendTransaction({from:eth.coinbase, to:"XXX", value: web3.toWei(9.9, "ether"), gas:100000})
Error: transaction underpriced
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
```

why does this simply not work?

**Comment by Manidos** [comment]
Twhe same issue when I'm sending RPC requests to a remote Infura node. It also happens sometimes and I haven't found a pattern.

**Comment by vogelito** [comment]
@akosmaroy do you see the issue if you downgrade to 1.6.6? We downgraded and haven't seen the issue since. Pretty sure it's related to the above commits I referenced above

**Comment by themandalore** [comment]
I'm using the infura ropsten rpc and getting the same error when sending Raw transactions.   Must be an update thing.

**Comment by illya13** [comment]
for `infura` - use `gasPrice` value to be a bit bigger than value returned by `eth_gasPrice`

**Comment by wighawag** [comment]
I get the same issue on ropsten when talking to an infura node. 
I could make the gasPrice higher. I tried by multiplying it by 20 (from 4 gwei to 80 gwei) and it worked but I would like to mimick the gasPrice I am going to use on the mainnet.

I would like to know why it happens and if it will happen the same on the mainnet.

Logically we should be able to set any price we want.

**Comment by wighawag** [comment]
it seems it reject transaction if gasPrice si below the limit configured : https://github.com/ethereum/go-ethereum/blob/c91f7beb53ff1ab0376d9aa5fab5a8de8b04631c/core/tx_pool.go#L557

I think this should only affect miner. a non miner node should accept low gasPrice transaction, no ?

**Comment by win2win** [comment]
Same problem here with Infura and my private geth. 
Version: 1.6.7-stable
Error: insufficient funds for gas * price + value

**Comment by wighawag** [comment]
@win2win insufficient funds error is a different error, it just meanyour account do not have enough ether to cover the cost of the transaction (which is equal to gas*price + value)

the underpriced error is a different thing, geth reject transaction whose gasPrice it consider too low (based on a configired limit) : only the gasPrice is considered here

**Comment by wighawag** [comment]
Anyone? 

Infura nodes that use geth are rejecting all transactions with a gas price lower than 24gwei and it this limit seems to increase.

Note that the gas price return by getGasPrice was 100 gwei last time I checked

I posted an issue on infura but I wonder why non mining node even have that limit. They should just pass the transactions around and let the miners decide.

Is it a recent intentional change?

**Comment by vogelito** [comment]
> I would like to know why it happens and if it will happen the same on the mainnet.

@wighawag yes, my original report is from mainnet

**Comment by vogelito** [comment]
We just updated to 1.7.0 to see if this solves the issue.

**Comment by K-RVA** [comment]
Stop

**Comment by K-RVA** [comment]
Unsubscribe

**Comment by vogelito** [comment]
We haven't seen this issue since upgrading to 1.7.0

**Comment by holiman** [comment]
Thanks, closing

**Comment by eabaid** [comment]
I had the same issue with Infura on the ropsten network. I wasn't providing a gasPrice when I got the "transaction underpriced" error; only gas. Looks like I had to provide all transaction parameters except nonce like below if not managed by geth and if signing the transaction myself. Transaction went through fine right after.

{"jsonrpc":"2.0","id":3,"error":{"code":-32000,"message":"transaction underpriced"}}

`web3.eth.sendTransaction({
    from: from,
    to: to,
    value: value,
    **gasPrice: "20000000000",**
    gas: "21000"
}, function(error, result){
    if(error)
    {	
    }
    else
    {
    }
})`

{"jsonrpc":"2.0","id":3,"result":"0xe47688ed9bc2b9d4f631b0a94b7a40dd83ab884ec1493e3ba9b741da67b3a83b"}

**Comment by illya13** [comment]
started to have this again on `Ropsten`

**Comment by PaulRBerg** [comment]
Still happening on Ropsten using Infura. web3 version`0.20.6`.

```
const genRawTx = async () => {
	const count = await web3.eth.getTransactionCount(ADDRESS);
	const nonce = web3.toHex(count);

	const gasPrice = web3.eth.gasPrice.toNumber() * 1.50;
	console.log('web3.eth.gasPrice.toNumber()',  web3.eth.gasPrice.toNumber());

	return {
		'from': from,
		'nonce': nonce,
		'gasPrice': '0x09184e72a000', // 0x09184e72a000 is 10 quadrillions wei
		'gasLimit': '0x2710', // 0x2710 is 10,000 wei
		'to': to,
		'value': '0x10',
		'data': contract.transfer.getData(to, 10, { from: from }),
		'chainId': '0x03'
	};
};
```

**Comment by robertmagier** [comment]
I am also getting this error on mainnet using 10 gwei.
