### ISSUE TITLE
Android: abi: cannot use slice as type string as argument / 'abi: cannot unmarshal string in to []interface {}'

### ISSUE THREAD

**Issue by andrewnguyen22** [ethereum/go-ethereum#14832]
#### System information

Geth version: `1.6.6`
Mobile: Android

#### Expected behaviour
Successful interaction with a deployed smart contract on the Rinkeby blockchain.

#### Actual behaviour
For setter (on contract):
'abi: cannot use slice as type string as argument'
For getter (on contract):
'abi: cannot unmarshal string in to []interface {}'
#### Steps to reproduce the behaviour
1.) Connect to Rinkeby Testnet via mobile
2.) Create an account via mobile 
3.) Deploy a smart contract via desktop
4.) Try to interact w/ the smart contract via mobile

#### Android Code

```
final String address_string = "0x8607e627604495ae9812c22bb1c98bdcba581978";
String abi = "[{\"constant\":false,\"inputs\":[],\"name\":\"get_s\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"type\":\"function\"},{\"constant\":false,\"inputs\":[{\"name\":\"new_s\",\"type\":\"string\"}],\"name\":\"set_s\",\"outputs\":[],\"payable\":false,\"type\":\"function\"},{\"inputs\":[{\"name\":\"d_s\",\"type\":\"string\"}],\"payable\":false,\"type\":\"constructor\"}]";
Address address = Geth.newAddressFromHex(address_string);
BoundContract contract = Geth.bindContract(address, abi, ec);
CallOpts callOpts = Geth.newCallOpts();
callOpts.setContext(ctx);
callOpts.setGasLimit(31500);
System.out.println("OUTPUT: " + getString(contract, callOpts));

//Setter String to Test Contract
Interfaces params = Geth.newInterfaces(1);
Interface anInterface = Geth.newInterface();
anInterface.setString(teststring);
params.set(0,anInterface);
return contract.transact(opts, "set_s", params);

//Getter String from Test Contract
Interfaces args = Geth.newInterfaces(0);
Interfaces results = Geth.newInterfaces(1);
Interface result = Geth.newInterface();
result.setDefaultString();
results.set(0, result);
contract.call(opts, results, "get_s", args);
String string = results.get(0).getString();
return string;
```

#### Backtrace

````
W/System.err: go.Universe$proxyerror: abi: cannot unmarshal string in to []interface {}
W/System.err:     at org.ethereum.geth.BoundContract.call(Native Method)
W/System.err:     at andrewnguyen.test_geth.MainActivity.getString(MainActivity.java:170)
W/System.err:     at andrewnguyen.test_geth.MainActivity.smart_contract_interaction_get_string(MainActivity.java:157)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
W/System.err:     at android.view.View.performClick(View.java:6213)
W/System.err:     at android.widget.TextView.performClick(TextView.java:11074)
W/System.err:     at android.view.View$PerformClick.run(View.java:23645)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:154)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6692)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
````
#### Contract

```
pragma solidity ^0.4.9;

contract echo {
   string s;

   function echo(string d_s) {
           s = d_s;
   }

   function set_s(string new_s) {
           s = new_s;
   }

   function get_s() returns (string) {
           return s;
    }
}
```
#### ABI Generated From remix.ethereum.org 

`[{"constant":false,"inputs":[],"name":"get_s","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"new_s","type":"string"}],"name":"set_s","outputs":[],"payable":false,"type":"function"},{"inputs":[{"name":"d_s","type":"string"}],"payable":false,"type":"constructor"}]`

**Comment by flypaper0** [comment]
solved?

**Comment by aesopwonder** [comment]
Not yet...

**Comment by Rylo4** [comment]
Some more info I gathered from debugging:
1) I traced the call as follows:
	- mobile/bind.go -> BoundContract.Call()
	- accounts/abi/bind/base.go -> BoundContract.Call()
	- accounts/abi/abi.go -> Pack() and Unpack()
	- accounts/abi/reflect.go -> set()
2) For me, in the set() function in reflect.go, the src argument is a pointer, pointing to a struct and the dst argument is a slice.
3) The error is returned in the account/abi/reflect.go file, because none of the possible cases are fulfilled. The returned error is "abi: cannot unmarshal *big.Int in to []interface {}".
4) The EVM call is executed correctly (for a getter function), as expected (it returns a uint of value 1)

 `msg="sending {\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"eth_call\",\"params\":[{\"data\":\"0x3bc36a2d\",\"from\":\"0x0000000000000000000000000000000000000000\",\"to\":\"0x978d6147f6b2a5088f5b24f79a4f952f7cbc6f56\"},\"latest\"]}"`
 
 `msg="<-readResp: response {\"jsonrpc\":\"2.0\",\"id\":2,\"result\":\"0x0000000000000000000000000000000000000000000000000000000000000001\"}"`

Has anyone already found the specific problem, or a fix?

**Comment by cameronvoell** [comment]
I used this workaround for returning a string from a contract call command:

https://github.com/cameronvoell/go-ethereum/commit/65987efac70c8af7ec9923107d94a9275d21fdd1

**Comment by nthtson** [comment]
Hi @Rylo4  

https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/abi.go#L107

Can you try to replace from "if len(method.Outputs) > 1" to "if len(method.Outputs) >= 1", then rebuild android package again?

**Comment by Rylo4** [comment]
@nthtson Thanks, this fixes the issue in my comment. Does this change have implications for the full version of geth?

**Comment by nthtson** [comment]
@Rylo4 I think it's ok for your purposes now. Anyway, keep an eye on this issue.

FYI, I also reported another issue about Contract ABI   https://github.com/ethereum/go-ethereum/issues/14363#issuecomment-320412358

**Comment by erichin** [comment]
The Geth mobile swift face the same problem
```
abi: cannot unmarshal *big.Int in to []interface {}.
```

**Comment by timoninn** [comment]
Hi @erichin

I have the same problem. Have you solved it ?

**Comment by DHOscar** [comment]
@nthtson @Rylo4 So the problem still exists. At list on iOS version. @nthtson ur comments for the fix might not valid anymore as abi.go implementation changed.

**Comment by erichin** [comment]
@timoninn Nop, but i use to fix it by the way of @nthtson commented on Aug 17. But now the abi.go implementation has changed as @DHOscar say

**Comment by cytl5yy** [comment]
i have the saame problem 
abi: cannot unmarshal *big.Int in to []interface {}.  

is it solved?

**Comment by thomasyuan** [comment]
Same problem here, on iOS, with geth 1.7.2.
If I try to get balance from a contract, the exception is exactly same.
When I try to get the owner of the contract, then the error is  ```abi: cannot unmarshal common.Address in to []interface {}```

Both cases RPC return correctly. 
For getOwner case:
```
msg="sending {\"jsonrpc\":\"2.0\",\"id\":18,\"method\":\"eth_call\",\"params\":[{\"data\":\"0x893d20e8\",\"from\":\"0x0000000000000000000000000000000000000000\",\"to\":\"0x3fe80503073df564fcd29031a1161ef53bfb429d\"},\"latest\"]}"

msg="<-readResp: response {\"jsonrpc\":\"2.0\",\"id\":18,\"result\":\"0x000000000000000000000000ddcaeba5e0feb704b649d36d3d631a060eca6f2f\"}"
```

**Comment by cytl5yy** [comment]
Yes,my  code is  :

    Address address = new Address("0x43ee79e379e7b78d871100ed696e803e7893b644");
    String abiJSON = "[{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_addr","type":"address"}],"name":"getNonce","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"founder","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"version","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"allocateEndBlock","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"},{"name":"_v","type":"uint8"},{"name":"_r","type":"bytes32"},{"name":"_s","type":"bytes32"}],"name":"approveProxy","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_owners","type":"address[]"},{"name":"_values","type":"uint256[]"}],"name":"allocateTokens","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"},{"name":"_extraData","type":"bytes"}],"name":"approveAndCallcode","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"},{"name":"_extraData","type":"bytes"}],"name":"approveAndCall","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"remaining","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"allocateStartBlock","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"},{"name":"_feeUgt","type":"uint256"},{"name":"_v","type":"uint8"},{"name":"_r","type":"bytes32"},{"name":"_s","type":"bytes32"}],"name":"transferProxy","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"payable":false,"stateMutability":"nonpayable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_from","type":"address"},{"indexed":true,"name":"_to","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_owner","type":"address"},{"indexed":true,"name":"_spender","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Approval","type":"event"}]";
    CallOpts opts = Geth.newCallOpts();
    opts.setContext(ctx);
    BoundContract contract = Geth.bindContract(address,abiJSON,client);
    Interfaces results = Geth.newInterfaces(1);
    Interface result = Geth.newInterface();
    result.setDefaultBigInt();
    results.set(0, result);
    Interfaces params = Geth.newInterfaces(1);
    Interface anInterface = Geth.newInterface();
    anInterface.setAddress(new 
    geth.Address("0x62a1056fcf3dbb4305a00b0686e9a96b0b7e4bfa"));
    params.set(0,anInterface);
    contract.call(opts,results,"balanceOf",params);
    BigInt balance = results.get(0).getBigInt();

   The RPC retun correctly:
 {"jsonrpc":"2.0","id":3,"result":"0x000000000000000000000000000000000000000000041e8e57486d2ec0800000"}"
 but the abi error return :  go.Universe$proxyerror: abi: cannot unmarshal *big.Int in to []interface {}

**Comment by OrenZak** [comment]
Same problem Android version
> abi: cannot unmarshal *big.Int in to []interface {}

Any solution ?

**Comment by DHOscar** [comment]
Quickly check the go source code. Compare the original call method implementation in base.go:
`func (c *BoundContract) Call(opts *CallOpts, result interface{}, method string, params ...interface{}) error`
And mobile wrapper in bind.go:
`func (c *BoundContract) Call(opts *CallOpts, out *Interfaces, method string, args *Interfaces) error {
	results := make([]interface{}, len(out.objects))
	copy(results, out.objects)
	if err := c.contract.Call(&opts.opts, &results, method, args.objects...); err != nil {
		return err
	}
	copy(out.objects, results)
	return nil
}`

The input param `result` type for original call method should be `interface{}`. But in the mobile wrapper, we try to use an array/slice. 

So if the smart contract always returjn a signal value, I think we can fix the wrapper implementation to make it work. But for sure this is not the right solution.

**Comment by cytl5yy** [comment]
I modify th go source code  belllow , it can solve the problem ,but  this is not the good solution.
       
        func (c *BoundContract) CallNew(opts *CallOpts, out *Interfaces, method string, args *Interfaces) error {
	// results := make([]interface{}, len(out.objects))
	// copy(results, out.objects)
	if err := c.contract.Call(&opts.opts, out.objects[0], method, args.objects...); err != nil {
		return err
	}
	// copy(out.objects, results)
	return nil
}

**Comment by DHOscar** [comment]
@cytl5yy Totally agreed. I just test it and it works for the signal return value. Not test the array yet. But for sure it should not work for the tuple. 

I would say this is the problem. Although I have no good solution for it.

**Comment by cytl5yy** [comment]
Yes ,signal value is good for this solution,  so if you want to work for single and tuple value ,you must modify  /accounts/abi/method.go souce code.

**Comment by cytl5yy** [comment]
func (abi ABI) Unpack(v interface{}, name string, output []byte) error {
	var method = abi.Methods[name]

	if len(output) == 0 {
		return fmt.Errorf("abi: unmarshalling empty output")
	}

	// make sure the passed value is a pointer
	valueOf := reflect.ValueOf(v)
	if reflect.Ptr != valueOf.Kind() {
		return fmt.Errorf("abi: Unpack(non-pointer %T)", v)
	}

	var (
		value = valueOf.Elem()
		typ   = value.Type()
	)

	// if len(method.Outputs) > 1 {
		switch value.Kind() {
		// struct will match named return values to the struct's field
		// names
		case reflect.Struct:
			for i := 0; i < len(method.Outputs); i++ {
				marshalledValue, err := toGoType(i, method.Outputs[i], output)
				if err != nil {
					return err
				}
				reflectValue := reflect.ValueOf(marshalledValue)

				for j := 0; j < typ.NumField(); j++ {
					field := typ.Field(j)
					// TODO read tags: `abi:"fieldName"`
					if field.Name == strings.ToUpper(method.Outputs[i].Name[:1])+method.Outputs[i].Name[1:] {
						if err := set(value.Field(j), reflectValue, method.Outputs[i]); err != nil {
							return err
						}
					}
				}
			}
		case reflect.Slice:
			if !value.Type().AssignableTo(r_interSlice) {
				return fmt.Errorf("abi: cannot marshal tuple in to slice %T (only []interface{} is supported)", v)
			}

			// if the slice already contains values, set those instead of the interface slice itself.
			if value.Len() > 0 {
				if len(method.Outputs) > value.Len() {
					return fmt.Errorf("abi: cannot marshal in to slices of unequal size (require: %v, got: %v)", len(method.Outputs), value.Len())
				}

				for i := 0; i < len(method.Outputs); i++ {
					marshalledValue, err := toGoType(i, method.Outputs[i], output)
					if err != nil {
						return err
					}
					reflectValue := reflect.ValueOf(marshalledValue)
					if err := set(value.Index(i).Elem(), reflectValue, method.Outputs[i]); err != nil {
						return err
					}
				}
				return nil
			}

			// create a new slice and start appending the unmarshalled
			// values to the new interface slice.
			z := reflect.MakeSlice(typ, 0, len(method.Outputs))
			for i := 0; i < len(method.Outputs); i++ {
				marshalledValue, err := toGoType(i, method.Outputs[i], output)
				if err != nil {
					return err
				}
				z = reflect.Append(z, reflect.ValueOf(marshalledValue))
			}
			value.Set(z)
		default:
			return fmt.Errorf("abi: cannot unmarshal tuple in to %v", typ)
		}

	// } else {
	// 	marshalledValue, err := toGoType(0, method.Outputs[0], output)
	// 	if err != nil {
	// 		return err
	// 	}
	// 	if err := set(value, reflect.ValueOf(marshalledValue), method.Outputs[0]); err != nil {
	// 		return err
	// 	}
	// }

	return nil
}

**Comment by snollidea** [comment]
`go.Universe$proxyerror: `setText` abi: cannot use slice as type string as argument`
Any solution, guys?

**Comment by thomasyuan** [comment]
What I did is cherry-pick the patch from @Orenzak and build from source. That works well.

**Comment by thomasyuan** [comment]
#15415

**Comment by DHOscar** [comment]
Indeed what I did. I think the fix works but CI give problem. Hope @OrenZak will fix it soon. As my project don't need to work with the most current client, I just cherry-pick it.

**Comment by thomasyuan** [comment]
I think that’s CI’s problem, but apparently people don’t care about mobile, even a CLI issse (like attach should ignore —datadir) can have higher priority and get merged quickly.
