### ISSUE TITLE
Swarm index out of range

### ISSUE THREAD

**Issue by BackendButters** [ethereum/go-ethereum#14843]
#### System information

Geth version: `1.6.6`
OS & Version: Ubuntu 17.04

#### Expected behaviour
No crash

#### Actual behaviour
panic: runtime error: index out of range
goroutine 58 [running]:
panic(0x559ab0edf9c0, 0xc4200140b0)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/ethereum/go-ethereum/swarm/network/kademlia.(*KadDb).findBest(0xc42000c2d0, 0x4, 0xc421e3ad88, 0x0, 0x559ab0e93801, 0x5)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/kademlia/kaddb.go:205 +0x1031
github.com/ethereum/go-ethereum/swarm/network/kademlia.(*Kademlia).Suggest(0xc42000e200, 0x0, 0xc421e3ad00, 0x0)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/kademlia/kademlia.go:296 +0xb1
github.com/ethereum/go-ethereum/swarm/network.(*Hive).Start.func1(0xc420070210, 0xc4201fe2c0)
        /go/src/github.com/ethereum/go-ethereum/swarm/network/hive.go:144 +0xc7
created by github.com/ethereum/go-ethereum/swarm/network.(*Hive).Start
        /go/src/github.com/ethereum/go-ethereum/swarm/network/hive.go:177 +0x1c4

#### Steps to reproduce the behaviour
unknown - just happened once

**Comment by nonsense** [comment]
Closing this, as it is no longer relevant. This code has been refactor significantly over the last months.
