### ISSUE TITLE
Whisper V5: disabling Proof of Work ?

### ISSUE THREAD

**Issue by bgrieder** [ethereum/go-ethereum#14853]
I am trying to disable the requirement for PoW in Whisper

This seems to be possible by setting `workTime` to 0 when looking at `envelope.go#Seal` (finish == now) however it will fail the target test at the bottom of the function

```go
func (e *Envelope) Seal(options *MessageParams) error {
	...
	finish := time.Now().Add(time.Duration(options.WorkTime) * time.Second).UnixNano()
	for nonce := uint64(0); time.Now().UnixNano() < finish; {
        ...
        }

        if target > 0 && bestBit < target {
		return fmt.Errorf("failed to reach the PoW target, specified pow time (%d seconds) was insufficient", options.WorkTime)
	}
...
```

Alternatively, I tried setting the `minimumPoW` to zero in but again there is a test in `whisper.go#SetMinimumPoW` which prevents that

```go
// SetMinimumPoW sets the minimal PoW required by this node
func (w *Whisper) SetMinimumPoW(val float64) error {
	if val <= 0.0 {
		return fmt.Errorf("invalid PoW: %f", val)
	}
	w.settings.Store(minPowIdx, val)
	return nil
}
```

How can I disable PoW ?

**Comment by RichHorrocks** [comment]
Ideally ask questions on https://ethereum.stackexchange.com - it is important to keep issue-trackers clear and for real issues only.
