### ISSUE TITLE
Fatal: Error starting protocol stack: leveldb/table: corruption on table (pos=0): too small [file=018186.ldb]

### ISSUE THREAD

**Issue by nolash** [ethereum/go-ethereum#14852]
#### System information

Geth version: 1.6.6 unstable
OS & Version: 4.11.3-1 ARCH

on block 3960482 db suddenly apparently corrupts and geth fails to start. It might have happened in connection with a uncontrolled power down. *The file mentioned in the error doesn't exist on disk*. Can I do anything here, or must I merely resync from scratch?

**Comment by karalabe** [comment]
If the database got corrupted, I'm afraid the only way is to resync. I'd recommend doing it with a develop release from master though, it will net you a database half the size :)
