### ISSUE TITLE
Whisper V5: cannot get 2 light nodes to whisper on Rinkeby

### ISSUE THREAD

**Issue by bgrieder** [ethereum/go-ethereum#14869]
#### System information

Geth version: master
OS & Version: OSX
Commit hash : a602ee90f2c28eadbca8cdc2e143825a4c24ab23

#### Expected behaviour

Node 2 will receive node 1 message on its filter

#### Actual behaviour

Node 2 never receives the message; however if a node posts to itself, the message is caught by the filter and properly received

#### Steps to reproduce the behaviour

I am using go-ethereum as a library and code which is very similar to the one used by the whisper API in `whisper/whisperv5/api.go` in `Post()` and `Messages()`. I can provide code if required

When a node posts to itself the message is picked up by the filter and received. It looks like the message is not propagated by the network between the 2 nodes.

Trying to debug that issue I have a few questions:

 - Is there a restriction on whispering between light nodes ?
 - do I need to do more than registering the whisperv5 service using
        `utils.RegisterShhService(n, &whisperv5.DefaultConfig)` ?
- does the `node.Config` need to hold particular values? for instance can I change the `name` to any client identifier of my choice ?
 - do the "other" nodes on the network refuse to forward a message for which the PoW is below their min PoW ?

Any pointer appreciated. Many thanks for your help

**Comment by bgrieder** [comment]
After further testing the value of the PoW for the message seems to be the key factor, but, please, I would like confirmation that it is actually the case.

Also how do you find the "correct" value to get your message propagated ?

**Comment by froid1911** [comment]
@bgrieder what was your solution? what is the correlt powTarget value?
