### ISSUE TITLE
the 1.6.7 node crash sometime

### ISSUE THREAD

**Issue by ucwong** [ethereum/go-ethereum#14864]
![image](https://user-images.githubusercontent.com/22344498/28610391-c3c9d1b2-721a-11e7-99c3-12fcba1739ac.png)

there seems no exception in the log file

go version 1.8.3
node version 1.6.7

**Comment by karalabe** [comment]
How does it crash then?

**Comment by ucwong** [comment]
@karalabe I have no idea now. Maybe out of memory, I have clean the cache and keep watching
