### ISSUE TITLE
How many Consensus algorithm does ethereum involve?

### ISSUE THREAD

**Issue by jiebanghan** [ethereum/go-ethereum#14871]
hi , I know POW is the Consensus algorithm of ethereum now, and it will be  changed  to POS. But  does ethereum has othre Consensus algorithm besides POW and POS? 
I heard from a man there are other Consensus algorithm in ethereum but I don't know.  thank you .

**Comment by karalabe** [comment]
`go-ethereum` also supports Clique, a PoA scheme https://github.com/ethereum/EIPs/issues/225

**Comment by yutelin** [comment]
We are working on PBFT implementation, Istanbul BFT, for geth as well. 
[ethereum/EIPs#650](https://github.com/ethereum/EIPs/issues/650)

**Comment by jiebanghan** [comment]
thank you very much.

**Comment by ebuchman** [comment]
There's also [ethermint](github.com/tendermint/ethermint), which connects go-ethereum to [tendermint](https://tendermint.com)
