### ISSUE TITLE
Swarm needs better configuration file

### ISSUE THREAD

**Issue by homotopycolimit** [ethereum/go-ethereum#14879]
When swarm is first launched, a configuration file is created at
`/path/to/datadir/swarm/bzz-address/config.json`

### What we have
This config.json contains 
- some variables that a user might want to change such as `DbCapacity` which governs how much disk space swarm will use;
- it contains other variables that nobody would want to change (unless experimenting with very different private swarms, because changing these values would make their client incompatible with all the others) such as  `Branches` and `Hash`; 
- and there are values that are ignore entirely such as `EnsRoot`.

Furthermore, there is no way to update the default values used by the clients because no distinction is made between a client that is using the default values and a client that has explicitly set their values and these values happen to coincide with the defaults.

### What we need
We need a configuration file with the following properties:
- It should be possible to edit the configuration file before starting swarm for the first time (currently not possible)
- All configuration options are documented in situ
- All values are 'commented out' by default.
- A commented-out value implies the client wishes to use the default
- The configuration file should contain only those values that one has reason to change and should not contain options to completely change the internal functioning of the client.
- it should be possible to override any and all options in the configuration file by using a command line flag.
- Variables should be cleanly separated by category - DB stuff, Network stuff, Financial Stuff...

Perhaps it is wise to have separate configuration files for basics such as DBCapacity and Port, and for financials such as Swap.

**Comment by lmars** [comment]
@homotopycolimit I'm in full agreement except for the last point about separate config files, there should just be a single file with multiple sections.

**Comment by fjl** [comment]
Please think about using the format/infrastructure we have for geth configuration.
