### ISSUE TITLE
swarm: more informative 404 pages when URL matches a manifest

### ISSUE THREAD

**Issue by homotopycolimit** [ethereum/go-ethereum#14872]
#### Manifest with / without default entry:

When a manifest is loaded via bzz
`bzz://Hash-or-Name-of-Manifest`
one of two things happen.

1. The manifest contains a 'default entry' (i.e. it contains an entry for the empty path). In this case that entry is loaded
2. The manifest does not contain a default entry. In this case we return a 404.

#### ?list=true

We already have the ability to show the contents of a manifest by appending `?list=true` to the URL.
Thus if we have a manifest at `bzz://mysite.eth/i` containing entries for `ndex.html` and `mages/` then, 
- `bzz:// mysite.eth/i` gives a blank 404
- `bzz:// mysite.eth/i?list=true` returns an html page with links to `ndex.html` and `mages/`

#### suggested changes
When a swarm resource could not be found, we should generate a blank 404, but when we loaded a valid manifest, but did not specify which entry we wanted, then the 404 page should be more helpful - offering links to the manifest entries:

`did you mean index.html?`

**Comment by homotopycolimit** [comment]
Also, when the file not found is a manifest, apparently we return an HTTP 500 error instead of a 404.

**Comment by holisticode** [comment]
Consider a manifest which contains "readme.md" and "readit.md". 
The following behavior has been observed:

* `$hash/` returns `$hash/?list=true`
* `$hash/r`, `$hash/re`, `$hash/rea` return json text with 2 entries: `me.md` and `it.md` (their filename minus the common part `read`)
* `$hash/read` **returns 404 not found** (this is quite unexpected)
* `$hash/readm`returns the `readme.md` file
* `$hash/readi` returns the `readit.md`file

This doesn't suggest consistent behavior, rather that the trie and subtrie traversal and path resolution needs fixing?

**Comment by lmars** [comment]
@holisticode the behaviour you are seeing is why this issue exists, we should be returning a 404 if the path doesn't match a valid file in the tree. The current behaviour is indeed inconsistent.

For your specific `readme.md` and `readit.md` case, the first 3 (i.e. specifying `/read` or any prefix of it) should return a 404 with a useful "did you mean" list containing both files (i.e. the same list as if `/?list=true` was given), and `readm` / `readi` should return the same but just with the single file in the list (i.e. the same as `/readm?list=true` or `/readi?list=true`).

**Comment by holisticode** [comment]
The PR which actually fixes this issue is this one: 
https://github.com/ethereum/go-ethereum/pull/15139
