### ISSUE TITLE
Geth should create a subfolder under ~./ethereum for each chain

### ISSUE THREAD

**Issue by stephantual** [ethereum/go-ethereum#1487]
When a new network id is used, Geth should create a new folder under ./ethereum, because otherwise storing multiple chains would require the use of the --data-dir switch AND the use of the --networkId switch, which is redundant.

Furthermore, it should place the said subfolder in a subfolder of its own, such as ~./ethereum/goethereum/chainhash , otherwise it will conflict with C++ ethereum which also stores all its data under ~./ethereum!!!!

**Comment by nmushegian** [comment]
+1
So the default network ID should be determined from the chain hash.

**Comment by obscuren** [comment]
Hmm, really under `~./ethereum`; are you **sure**? :-P

Perhaps we could place the database in `$ETHEREUM/net_id/{state,blockchain,extra}` and leave the keys in the `$ETHEREUM` folder

**Comment by karalabe** [comment]
Imho the net id is not enough to differentiate between chains. It can get overwritten by a remote peer with the same net id but different and bigger chain. If we want to support such a thing, then we should also add (or only add) the genesis nonce. It's a much better differentiator than network id.

**Comment by Gustav-Simonsson** [comment]
Make that genesis block hash.

**Comment by ebuchman** [comment]
Few outstanding issues here:

1) Will we maintain an active test net? If so, and if it is based on the same genesis block (as it should be, probably), we need something like a network id to differentiate. The chains should definitely be stored in a common folder, (eg $ETHEREUM/main_net, $ETHEREUM/test_net1, etc), but keys can just stay in $ETHEREUM/keys.  

2) What will prevent replay attacks from one chain to another? Eg. If I send a tx on the test net, someone could replay it on main net (assuming they time the nonce right). So what we need is a differentiator in the addresses (like bitcoin - btw, we should also add a checksum!), or for transactions to include the chain_id for the sake of signatures (ie the transaction doesnt need to actually include the chain id, but when you sign it, you rlp encode the chain id in there too before signing). This is what we are doing with tendermint.

3) it would be nice if block's also included the chain_id. For now we can push a client update that will include it in the Extra field, and once its sufficiently adopted push a hardfork to just get it in the block structure. Of course we can probably avoid that by encoding the chain/net id in the addresses like bitcoin

**Comment by karalabe** [comment]
1) Yes, there will be an active test net. And no, it will - I hope - not be based on the same genesis block. The difficulty for the live net started out huge, there's no point in putting such a burden on top of the test network, especially if nobody will GPU mine. I'm guessing it will be kept running by a few CPUs or dev machines. Also it would be very dangerous as I could connect the main chain to the test chain and immediately wipe the entire test network.

2) Keys should never ever be reused between test nets and main nets. I see huge potential security implications, if not other, buggy clients running in the test net which could compromise your live account's security. Modifying the transactions to enforce chain verification would imho require a protocol update, hence would lead to a hard fork. Not something we wan't to do any time soon.

3) I don't really see the benefit of adding the chain ID to the blocks. If the genesis blocks are different between the various live and test networks, there isn't much that can go wrong. No need to complicate things.

**Comment by ebuchman** [comment]
Good points. If the genesis blocks are different then I suppose all is fine. I was thinking they'd be the same re account set but not necessarily difficulty, so yes the hashes will be different. But we can't do that even unless we fix the address scheme or tx signing to avoid the replay attacks, so it will have to be entirely new genesis account set with new keys and like you say, no key should ever be reused across chains.

That being said, I would expect we'd want to checkpoint states of the main chain and start test nets from them, so we can test things from a real state. This will be impossible to do securely unless we deal with addresses, and if we're not doing it then we may be limiting the effectiveness of the test chain (of course its still useful for testing new features, but not in the context of the old state).
