### ISSUE TITLE
Puppeth prefunds accounts unreasonable high

### ISSUE THREAD

**Issue by nopanic** [ethereum/go-ethereum#14888]
#### System information

Geth version: 1.6.7-stable
OS & Version: Ubuntu 17.04

#### Expected behaviour

Prefunded accounts have a reasonable amount of Ether.

#### Actual behaviour

Prefunded accounts have `0x200000000000000000000000000000000000000000000000000000000000000` Wei which is, I think, something around `9.04625697166532776746648320380374280103671755200316906558262375061821325312e+74` Ether. I couldn't find a way to change this through the tool or by restarting puppeth after editing the genesis file by hand.

#### Steps to reproduce the behaviour

1. Create genesis block in puppeth
2. Select Proof-Of-Work
3. Add an account to be prefunded
4. Save genesis file
5. Close puppeth and open genesis file
6. See large prefund amount at the end of the genesis file

**Comment by karalabe** [comment]
What's wrong with having such a high amount?

**Comment by nopanic** [comment]
A self-set amount of ether would allow to create more realistic scenarios.

Thinking about it, you could create those with some initial transactions from one prefunded account. Still, I think it would be nice to specify this during the genesis creation.
