### ISSUE TITLE
SimulatedBackEnd - need to be able to change time.....

### ISSUE THREAD

**Issue by DaveAppleton** [ethereum/go-ethereum#14884]
SimulatedBackEnd is great for testing projects and I would like to release a half-assed testing framework based on it.

I can't see how I could change the time received by `block.timestamp` a.k.a. `now` that the contract receives when it is being executed.

If it is possible without breaking everything, I am prepared to make the changes as long as I can be given a pointer to where to start.

**Comment by fjl** [comment]
You can use http://godoc.org/github.com/ethereum/go-ethereum/core#BlockGen.OffsetTime
