### ISSUE TITLE
web3.fromWei doesn't work with this version. Changing to older version fixed it

### ISSUE THREAD

**Issue by Zied-Guesmi** [ethereum/go-ethereum#14890]
#### System information

Geth version: `geth version`
OS & Version: ubuntu 16.04

#### Expected behaviour
ether amount

#### Actual behaviour
TypeError: web3.fromWei is not a function

#### Steps to reproduce the behaviour
1- install web3: npm i web3
2- let Web3 = require('web3')
3- let web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:8545'))
4- let ether = parseInt(web3.fromWei(eth.getBalance(eth.accounts[0]), 'ether'))

**Comment by karalabe** [comment]
Please open a bug report on the web3 repo. https://github.com/ethereum/web3.js/

**Comment by Zied-Guesmi** [comment]
@maulikvora thanks a lot !!

**Comment by Samyoul** [comment]
@maulikvora Thanks for the updated documentation, it looks like the github repo docs are out of date : https://github.com/ethereum/wiki/wiki/JavaScript-API#web3fromwei
