### ISSUE TITLE
Initialised chain configuration shows Engine unknown- Private node

### ISSUE THREAD

**Issue by rakeshr234** [ethereum/go-ethereum#14896]
#### System information

Geth version: 1.6.7-stable
OS & Version: Linux -Ubuntu-16.04 LTS

#### Actual behaviour
Hi , 
I am new to this platform. I was trying to create a private node for testing purpose. But i am getting error while launching console saying Engine unknown for chain configuration. is this expected. Even i am  not able to add peers also to my nodes. What could be the reason?

sudo geth --datadir data --networkid 15 --ipcdisable --port 30302 --rpcaddr "localhost" --rpcport 8545 console
WARN [08-04|09:43:23] No etherbase set and no accounts found as default
INFO [08-04|09:43:23] Starting peer-to-peer node               instance=Geth/v1.6.7-stable-ab5646c5/linux-amd64/go1.8.1
INFO [08-04|09:43:23] Allocated cache and file handles         database=/home/ubuntu/data/geth/chaindata cache=128 handles=1024
WARN [08-04|09:43:23] Upgrading chain database to use sequential keys
INFO [08-04|09:43:23] **Initialised chain configuration**          config="{ChainID: 15 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Metropolis: <nil> **Engine: unknown**}"
INFO [08-04|09:43:23] Disk storage enabled for ethash caches   dir=/home/ubuntu/data/geth/ethash count=3
INFO [08-04|09:43:23] Disk storage enabled for ethash DAGs     dir=/home/ubuntu/.ethash          count=2
WARN [08-04|09:43:23] Upgrading db log bloom bins
INFO [08-04|09:43:23] Bloom-bin upgrade completed              elapsed=278.352µs
INFO [08-04|09:43:23] Initialising Ethereum protocol           versions="[63 62]" network=15
INFO [08-04|09:43:23] Loaded most recent local header          number=0 hash=fcf2d3…874b60 td=200000000
INFO [08-04|09:43:23] Loaded most recent local full block      number=0 hash=fcf2d3…874b60 td=200000000
INFO [08-04|09:43:23] Loaded most recent local fast block      number=0 hash=fcf2d3…874b60 td=200000000
INFO [08-04|09:43:23] Starting P2P networking
INFO [08-04|09:43:23] Database conversion successful

#### Steps to reproduce the behaviour
1. Install ethereum
2. create a folder "node1"
3. create custom genesis file
4. sudo geth --datadir data --networkid 15 --ipcdisable --port 30302 --rpcaddr "localhost" --rpcport 
 8545 --init genesis.json console

5. sudo geth --datadir data --networkid 15 --ipcdisable --port 30302 --rpcaddr "localhost" --rpcport 8545 console

**Comment by Chandubabuankam** [comment]
Me also facing same issue . Can any one help on this ??
