### ISSUE TITLE
"Bad block #850003" & "gas used error" v0.9.39

### ISSUE THREAD

**Issue by jdqx** [ethereum/go-ethereum#1489]
geth 0.9.39
ubuntu 14.04
```
I0718 14:09:51.223814    5301 chain_manager.go:678] imported 0 block(s) (0 queued 1 ignored) including 0 txs in 2.528793ms. #850002 [69f23a57 / 69f23a57]
I0718 14:10:01.183813    5301 chain_manager.go:794] Bad block #850003 (f1221791fd64d8ffa1a3fdc9ddf9c380855ed0d3c5c97d2f36c54927e9e2b85f)
I0718 14:10:01.183837    5301 chain_manager.go:795] gas used error (1533830 / 1563830)
I0718 14:10:01.183900    5301 downloader.go:253] Synchronisation failed: hash fetching canceled (requested)
```

A sign of local data corruption?

**Comment by kumavis** [comment]
weird! I did not get this error

passed block 850003 sometime this morning on `geth 0.9.39-a75b95b8`

**Comment by obscuren** [comment]
A sign of corruption indeed. Did you kill `geth -9`?

**Comment by jdqx** [comment]
No, but it looks like 'state' ran into the one bad sector on my 1TB hdd. I have since copied state to another partition and symbolically linked it. The error persists. Should I delete some previous blocks? If so, what's the cleanest method?

**Comment by obscuren** [comment]
If your state database wrote to a bad sector on your HDD and you've since copied it over, you'll be out of luck and I'm afraid you'll have to resync. There are currently no tools to delete blocks manually
