### ISSUE TITLE
Go bindings: failed to retrieve account nonce

### ISSUE THREAD

**Issue by sebastianvoss** [ethereum/go-ethereum#14909]
#### System information

Geth version:
Geth
Version: 1.6.7-stable
Git Commit: ab5646c532292b51e319f290afccf6a44f874372
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: darwin
GOPATH=/Users/sebastian/go
GOROOT=/usr/local/Cellar/go/1.8.3/libexec

OS & Version: OSX

#### Issue description

I create [go bindings][1] for my smart contract but have an issue when executing a transaction. It only works when I explicitly specify the `txOpts.Nonce` (see commented line). When I leave the line commented I get this error: 
    
    Failed to execute transaction: failed to retrieve account nonce: json: cannot unmarshal hex number with leading zero digits into Go value of type hexutil.Uint64`

Here is the relevant code:

    txOpts := bind.NewKeyedTransactor(key)

	//txOpts.Nonce = big.NewInt(<nonce>)
	
	tx, err := token.MyContract(txOpts, big.NewInt(1))
	if err != nil {
		log.Fatalf("Failed to execute transaction: %v", err)
	}

The [documentation][2] tells it would retrieve the pending nonce from `txOpts.From` when `txOpts.Nonce` is `nil`.

  [1]: https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts
  [2]: https://godoc.org/github.com/ethereum/go-ethereum/accounts/abi/bind#TransactOpts

**Comment by fjl** [comment]
Which API are you talking to? Is it geth, parity, testrpc?

**Comment by sebastianvoss** [comment]
Thanks for your feedback! It is testrpc.

**Comment by AlecAivazis** [comment]
I'm also encountering this issue when trying to connect to a local instance of `geth` through `localhost:8545`

**Comment by andreiashu** [comment]
Having this issue as well.

**Comment by andreiashu** [comment]
Running testrpc with verbose mode enabled (`testrpc -v`) reveals the potential culprit (note that I replaced the account address with a dummy address):

```
eth_getTransactionCount
   > {
   >   "jsonrpc": "2.0",
   >   "id": 1,
   >   "method": "eth_getTransactionCount",
   >   "params": [
   >     "0x66c8395c515e2fcc24787d4d37d5b194d6f9401d",
   >     "pending"
   >   ],
   >   "external": true
   > }
 <   {
 <     "id": 1,
 <     "jsonrpc": "2.0",
 <     "result": "0x0c"
 <   }
```

At this stage I don't fully understand why, but testrpc gives back `0x0c` as the result for the transactionCount call. This makes the `ethclient.PendingNonceAt()` method fail since it expects an uint64 encoded as hex but `0x0c` actually means `FF, NP, form feed, \f` in hex...
By the way, calls to transaction count method from Truffle return correct data back...

**Comment by seka17** [comment]
Any updates on this issue?
