### ISSUE TITLE
Geth done building but not accessible

### ISSUE THREAD

**Issue by lugyin** [ethereum/go-ethereum#14902]
#### System information

Geth version: Geth version: 1.6.7-stable

#### Expected behaviour

I've followed the steps from the wiki to install geth by using "make geth" command and I received...
"Done Building" 
Run "...build/bin/geth" to launch geth.

I ran the build/bin/geth command and expected to gain access to geth commands

#### Actual behaviour

however, when I typed in any geth command (ex. geth --fast --cache=512 console), the response is "command not found: geth" 

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
If geth is not in your path then this is expected. So either include geth in your path or always specify the path explicitly.

**Comment by lugyin** [comment]
Thanks! I'm a bit new with this so apologies for layman questions...but
I'm assuming I use "sudo nano /etc/paths" and then add the path? If that's correct, what would I actually write to the file (ex. usr/local/bin)?

**Comment by ligi** [comment]
You are welcome. That really depends on your operating-system. Ideally head over with questions like this to stackoverflow or something similar and close this issue - it is important to keep these issue-trackers clean and relevant to the project.
