### ISSUE TITLE
use RPC API personal_sendTransaction lost coin

### ISSUE THREAD

**Issue by wunaigong** [ethereum/go-ethereum#14901]
#### System information
My eth address is 0xf59d63d9ECF47B3533c96076fC1328Bef5b4db8c
I want to sent coin to 0x54164b2811ad4846d3f45601e62fba32b41ae449
Detail:https://etherscan.io/address/0xf59d63d9ecf47b3533c96076fc1328bef5b4db8c

Use RPC API personal_sendTransaction，then coin to send to 0x161621c6bb940e9e77e3f74ab362d2fe701ca53c ， i don't know this address is whos!

who know reason?

**Comment by joaomontenegro** [comment]
Same thing happened to me!! We were hacked!!!

**Comment by wunaigong** [comment]
@joaomontenegro Have you found the solution yet?

**Comment by joaomontenegro** [comment]
There is no solution.... :-( that ether lost forever... Some hacker is having fun with it.

**Comment by immesys** [comment]
What happens is that your RPC API was on a public port. A hacker (bot) was also connected to your API. They cannot do anything with your accounts until you unlock them though, so it waits until you try to do a transaction (unlocking the account) and then it steals your ether. 

You cannot get that ether back, but you should look at properly securing your RPC API

**Comment by wunaigong** [comment]
@joaomontenegro @immesys  Thank you very much. You have solved my problem.
My solution is  change default port and sent coin from to destination address, at once lock my address.
