### ISSUE TITLE
Geth stuck with slow peers can't find fast ones automatically

### ISSUE THREAD

**Issue by skithuno** [ethereum/go-ethereum#1491]
Allot of stress testing this weekend. After starting geth and letting system sync for hours with default peer list, no blocks to download but constantly running 15+ blocks behind stats.ethdev.org . 

Probably the only way to make geth catchup is to manually force a peer connection with one of the fastest peers in the network.

**Comment by fjl** [comment]
It is hard to take any meaningful action on this issue. I am closing this now because 'this weekend' is now more than two months ago.
