### ISSUE TITLE
Geth performance and stability have degraded since the July 9th build

### ISSUE THREAD

**Issue by jzencore** [ethereum/go-ethereum#1492]
Some general observations from running various versions over the last week or so: erratic, anemic peer connection;  difficulty staying in sync;  frequent program panic and/or stalls.  The last reliable update that continues to run reasonably well was the one released on July 9th.

**Comment by obscuren** [comment]
The network of late has really pushed the client to the limit. Funky behaviour really only starts to pop up when you push things to their absolute limit. Issue like you've described will surface. The current situation is by no means realistic (but may become so in the future).

Tests like these help us to prepare, and help orchestrate plans and strategy for the future.. You'll have to bare us :-D

**Comment by jzencore** [comment]
Understood.   What I meant to convey was that the version from July 9th running under the current load and stressors takes a licking and keeps on ticking whereas the the several updates subsequent to the 9th do not.

**Comment by obscuren** [comment]
Do have a commit sha that work better? I'll take a look at exactly what has changes since then

**Comment by jzencore** [comment]
I had used apt-get to fetch the bits, from the apt log, it was:
0.9.39+674SNAPSHOT20150709162107trusty-0ubuntu1

Hope that helps.  Thanks Jeff.

**Comment by fjl** [comment]
This is a very generic issue that is not actionable (except by reverting all changes made since July 9).
Closing this now.
