### ISSUE TITLE
eth/downloader: race in TestFastCriticalRestarts*

### ISSUE THREAD

**Issue by egonelbre** [ethereum/go-ethereum#14936]
While running tests with -race, I got a failure in `TestFastCriticalRestarts`:

```
go test -race -run TestFastCriticalRestarts ./eth/downloader
```

[TestFastCriticalRestarts.txt](https://github.com/ethereum/go-ethereum/files/1205739/TestFastCriticalRestarts.txt)

**Comment by karalabe** [comment]
Fixed on master.
