### ISSUE TITLE
core: race in tests

### ISSUE THREAD

**Issue by egonelbre** [ethereum/go-ethereum#14935]
While running tests with -race, I got a failure in `TestTransactionQueueTimeLimiting` and `TestTransactionJournaling`

```
go test -race -run TestTransactionQueueTimeLimiting ./core
go test -race -run TestTransactionJournaling ./core
```

[TestTransactionJournaling.txt](https://github.com/ethereum/go-ethereum/files/1205732/TestTransactionJournaling.txt)
[TestTransactionQueueTimeLimiting.txt](https://github.com/ethereum/go-ethereum/files/1205733/TestTransactionQueueTimeLimiting.txt)

**Comment by karalabe** [comment]
Should be fixed in https://github.com/ethereum/go-ethereum/pull/14940

**Comment by egonelbre** [comment]
Confirmed, #14940, fixes this.
