### ISSUE TITLE
swarm: races in tests

### ISSUE THREAD

**Issue by egonelbre** [ethereum/go-ethereum#14937]
While running tests with -race, I got a failures in `TestSaveSyncDb` and `TestRandomBrokenData`:

```
go test -race -run TestSaveSyncDb ./swarm/network
go test -race -run TestRandomBrokenData ./swarm/storage
```

[TestSaveSyncDb.txt](https://github.com/ethereum/go-ethereum/files/1205744/TestSaveSyncDb.txt)
[TestRandomBrokenData.txt](https://github.com/ethereum/go-ethereum/files/1205759/TestRandomBrokenData.txt)

TestRandomBrokenData race is flaky.

**Comment by zelig** [comment]
thanks @egonelbre we are fixing these soon

**Comment by nonsense** [comment]
`TestRandomBrokenData` has been fixed.

`TestSaveSyncDb` doesn't exist anymore.
