### ISSUE TITLE
cannot unmarshal hex string without 0x prefix into Go struct field SendTxAr gs.data of type hexutil.Bytes

### ISSUE THREAD

**Issue by karthiyogi** [ethereum/go-ethereum#14947]
#### System information
cannot unmarshal hex string without 0x prefix into Go struct field SendTxAr gs.data of type hexutil.Bytes

Getting this error while trying to deploy contract

Geth version: `1.6.1`
OS & Version: Linux
Commit hash : (if `develop`)

**Comment by karalabe** [comment]
The transaction's data is supposed to be hex encoded. That supposed to have a `0x` prefix. Add it to have a valid encoding and it should work.
