### ISSUE TITLE
Raw transactions not incorporated into blocks

### ISSUE THREAD

**Issue by tinybike** [ethereum/go-ethereum#1494]
Signed transactions I submit using the `eth_sendRawTransaction` RPC are not being incorporated into blocks.  The problem seems to be that raw transactions are not being added to the txpool.  Logging `self.backend.TxPool().GetTransactions()` immediately after `TxPool().Add` is called in [PushTx](https://github.com/ethereum/go-ethereum/blob/98f4c936f25de27dbc90f36f2c1ffd1f23b114e9/xeth/xeth.go#L771) shows an empty txpool:
```
%!(EXTRA types.Transactions=[])
```
The transaction itself looks ok, though:
```
%!(EXTRA *types.Transaction=
    TX(465e4df1372b94f8b5486983dddb9a3d54ea033d4cabd967c15f64423e4106ec)
    Contract: false
    From:     8915c5ccc858f714c85ca4c31b15c7196cbb01f0
    To:       abe47f122a496a732d6c4b38b3ca376d597d75dd
    Nonce:    1338
    GasPrice: 1147602752650
    GasLimit  3135000
    Value:    0
    Data:     0x988445fe00000000000000000000000000000000000000000000000000000000000f69b5
    V:        0x1b
    R:        0x829374c161d106f9cc5aa901f3be878843e48d9f77a7325d22c94c03671f5408
    S:        0x691b4cb4dadf036ba152f3627849661ecf7edf97bc294e25637781133f2e96f4
    Hex:      f88c82053a86010b3274548a832fd61894abe47f122a496a732d6c4b38b3ca376d597d75dd80a4988445fe00000000000000000000000000000000000000000000000000000000000f69b51ba0829374c161d106f9cc5aa901f3be878843e48d9f77a7325d22c94c03671f5408a0691b4cb4dadf036ba152f3627849661ecf7edf97bc294e25637781133f2e96f4
)
```
I'm using Geth/v0.9.39-12bb743b/linux/go1.4.2.

**Comment by tinybike** [comment]
Solved -- thanks @bas-vk!

**Comment by bbva-javiermoreno** [comment]
Hi, I am having this same problem. How was it solved? 

I sign and successfully send a transaction using geth and sendRawTransaction. I get the receipt, but it never gets mined. I am using the same gaslimit and gasprice as in transactions signed in the client and they always get mined immediately.

**Comment by obscuren** [comment]
@bbva-javiermoreno are you sure the nonce, the price, the gas limit, etc are correct?

**Comment by bbva-javiermoreno** [comment]
Nonce was wrong. It is solved now.
