### ISSUE TITLE
Get the base height from other peer

### ISSUE THREAD

**Issue by ShawnyXiao** [ethereum/go-ethereum#14944]
I want to get the height of max block from other peer. How could I achieve that?

From this website [Ethereum Wire Protocol](https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol), I realize some knowledge about how peers comunicate with other peers. But it seems like that peers synchronized by Total Difficulty(TD) & hash of their best block. So I can't get the base height.

So how could I get the base height? Thanks for reading it.

**Comment by karalabe** [comment]
You can request a block header via it's hash using `GetBlockHeaders` https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol#new-model-syncing-pv62.
