### ISSUE TITLE
Inconsistent naming convention for etherbase

### ISSUE THREAD

**Issue by stephantual** [ethereum/go-ethereum#1495]
RC2, latest pull, buntu 15.04 (native)

It's miner.setEtherbase() but it's eth.coinbase, overtime this will lead to issues as applications will become dependent on a specific API

**Comment by karalabe** [comment]
@obscuren Is this something we would like to address? Would probably be useful to do this before the Frontier release

**Comment by keivibi** [comment]
HI, 
I think it's better to remove the term coinbase altogether from everywhere. Use Etherbase instead. Coinbase is a popular bitcoin wallet/exchange and using this name is only contributing to the confusion of new users.

**Comment by zelig** [comment]
duplicate. see https://github.com/ethereum/go-ethereum/issues/1420
use coinbase over etherbase?
