### ISSUE TITLE
Yet again, balance is 0. Tried fast sync, tried syncmode "light" and normal sync - nothing helps. Please help.

### ISSUE THREAD

**Issue by MichaelA2014** [ethereum/go-ethereum#14956]
Hello. 
I recently updated Geth to the latest version and did remove/redownload blockchain data with the following command `"C:\Program Files\Geth\geth.exe" --fast --cache=2048`
After a few days the synch was up to 4000000+ block so I opened the console and checked the balance it was showing 0.
After a google search and read of the `--help ` I tried the following fast command : `geth --syncmode "light" --cache=2048`

At that point geth started syncing really fast and got all the way through. After running the following command I still had 0 balance . The command I use to check balance is `eth.getBalance(eth.coinbase)`

The strange thing I noticed is when I open console the dec 31 1969 date is shown there as follows:
`C:\Program Files\Geth>geth attach
Welcome to the Geth JavaScript console!

instance: Geth/v1.6.7-stable-ab5646c5/windows-amd64/go1.8.3
coinbase: 0x05a5...................................................................
at block: 0 (Wed, 31 Dec 1969 18:00:00 CST)
 datadir: C:\Users\Michael\AppData\Roaming\Ethereum
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txp
ool:1.0 web3:1.0

> eth.getBalance(eth.coinbase)
0
>`

#### System information
Version: 1.6.7-stable
Git Commit: ab5646c532292b51e319f290afccf6a44f874372
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: windows
GOPATH=
GOROOT=c:\go

#### Backtrace

````
[backtrace]
````

**Comment by heyitswither** [comment]
how did you fix it?

**Comment by MichaelA2014** [comment]
I bought an SSD drive and installed GETH to it then let it rip with --fast key until it was synched
