### ISSUE TITLE
Add a comandline option to execute a custom stateTest on geth

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#14965]
With random state test generation we need a support option from the clients to run a custom .json file that is a StateTest. 

The file format is here: 
https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stExample/add11.json

The usage should be like following:
``` ./geth --runfile "/GeneralStateTests/stExample/add11.json" --format "StateTest" ```

the client should return whether the test execution was success or not. 
if it is a failure it should provide information on which fork rule there was an error. 
so then we could debug it more carefully.

**Comment by winsvega** [comment]
With this option we would be able to run a random generated state test and compare go client to the cpp client on a random evm code. that has a potential to discover some untested bugs and consensys issues. 
this will also help @cdetrio with his fuzztest coverage to compare one client to another on fuzzed tests scenarios. Currently fuzztests rely on vm log trace which is not that reliable compared to postState hash

**Comment by fjl** [comment]
This is now implemented on the master branch.

**Comment by cdetrio** [comment]
for the record, was implemented here https://github.com/ethereum/go-ethereum/pull/14998
