### ISSUE TITLE
Can not get the latest geth 1.6.7 stable to display balance. Need help.

### ISSUE THREAD

**Issue by MichaelA2014** [ethereum/go-ethereum#14960]
#### System information
Version: 1.6.7-stable
Git Commit: ab5646c
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: windows
GOPATH=
GOROOT=c:\go

#### Expected behaviour
After fully syncing by running `geth --fast cache=2048` I run `geth attach` and in console run `eth.getBalance(eth.coinbase)` I expect to see balance of 2+ ether. 
`eth.blockNumber`  in console I expect to see the latest synced block.
The date in the console window should be accurate. In my cosole it's showing (Wed, 31 Dec 1969 18:00:00 CST)
#### Actual behaviour
The actual behavior - The balance is show 0.
The "eth.blockNumber" returns 0
In console the date should be accurate. In my consoe I see (Wed, 31 Dec 1969 18:00:00 CST)

#### Steps to reproduce the behaviour
-download the latest geth x64 version from https://geth.ethereum.org/downloads. In my case 1.6.7 stable.
-install it over old version by executing .exe file.
-run in terminal "geth removedb" then "geth --fast --cache=2048"
-After it synced run "geth attach" to open colsole.
-check the balance via "eth.getBalance(eth.coinbase)"
-Check the latest block by "eth.blockNumber"

#### Backtrace

Don't know what backtrace is.
![2017-08-10_10-36-41](https://user-images.githubusercontent.com/15806130/29178816-501d7f76-7db8-11e7-8508-f695dd6e5f72.jpg)

[backtrace]
````
THANK YOU for your time!

**Comment by karalabe** [comment]
Your node is still syncing. You'll need to wait for sync to finish before you'll be able to see your balance.

**Comment by MichaelA2014** [comment]
@karalabe Thank you for reply. 
Is it going to stop the syncing after it's done or will it show some sort of message? How big is the blockchain file currently?
