### ISSUE TITLE
Geth hangs forever

### ISSUE THREAD

**Issue by fogonthedowns** [ethereum/go-ethereum#14961]
#### System information

Geth version: installed from github readme linux instructions 2 days ago. geth -v geth --version not supported.
OS & Version: Ubuntu 17.04
Commit hash : (if `develop`)

#### Expected behaviour
Geth  syncmode fast should complete.

#### Actual behaviour
geth does not complete and hangs about 100 away from completion.

#### Backtrace

````
{
  currentBlock: 4139205,
  highestBlock: 4139330,
  knownStates: 8954798,
  pulledStates: 8945748,
  startingBlock: 2519897
}
> eth.syncing
{
  currentBlock: 4139205,
  highestBlock: 4139330,
  knownStates: 8955462,
  pulledStates: 8946688,
  startingBlock: 2519897
}
INFO [08-10|08:34:20] Imported new state entries               count=46   flushed=30  elapsed=4.829ms   processed=8945748 pending=9050   retry=6    duplicate=12725 unexpected=42765
WARN [08-10|08:34:31] Stalling state sync, dropping peer       peer=4bd39c6445a9e2d3
WARN [08-10|08:34:32] Stalling state sync, dropping peer       peer=9cbe000081e5ae8d
INFO [08-10|08:34:33] Imported new state entries               count=53   flushed=50  elapsed=2.884ms   processed=8945801 pending=9022   retry=2    duplicate=12725 unexpected=42765
WARN [08-10|08:34:44] Stalling state sync, dropping peer       peer=b44d7b0d2c08e548
WARN [08-10|08:34:45] Stalling state sync, dropping peer       peer=754598a35c66d473
INFO [08-10|08:34:52] Imported new state entries               count=2    flushed=2   elapsed=65.967µs  processed=8945803 pending=9020   retry=108  duplicate=12725 unexpected=42765
INFO [08-10|08:34:53] Imported new state entries               count=2    flushed=1   elapsed=282.497µs processed=8945805 pending=9021   retry=106  duplicate=12725 unexpected=42765
WARN [08-10|08:34:56] Stalling state sync, dropping peer       peer=00f1a2d96a44246f
WARN [08-10|08:34:59] Stalling state sync, dropping peer       peer=8373449613bd324d
WARN [08-10|08:35:09] Stalling state sync, dropping peer       peer=1e78a31644e48110
WARN [08-10|08:35:13] Stalling state sync, dropping peer       peer=754598a35c66d473
INFO [08-10|08:35:15] Imported new state entries               count=53   flushed=48  elapsed=1.661ms   processed=8945858 pending=9006   retry=4    duplicate=12725 unexpected=42765
````

**Comment by karalabe** [comment]
Those frequent "stalling" messages are a bit disconcerting. Could you try restarting and see if it picks up speed? There are about 17M state entries to download, at least that many were last time I did a sync a couple days ago.

**Comment by fogonthedowns** [comment]
@karalabe I'm at work now and I'll update you when I'm back at home and can restart. This is the second time I've tried this though. Each time, it stalls with about 100 blocks left. Is it a requirement that I pull all 17M state entries before complete? (using fast)

furthermore, I should note my CPU is about 95%-100% toward the end. Not sure if this helps.

**Comment by fogonthedowns** [comment]
I was on 1.67, I deleted geth from /usr/bin/geth; downloaded go 1.7.3; and built from source pulling from github. 

Its working now.

**Comment by tomtom87** [comment]
@fogonthedowns is this still syncing as of today?

**Comment by emanuele3d** [comment]
Having similar issues. I ran `geth --rpc --fast --cache=4096` and it stalled at least a couple of times over the past four hours - and it is currently stalled with the last three lines showing:

```
INFO [08-24|21:53:16] Imported new block receipts              count=99   elapsed=205ms        number=3854593 hash=f76944…299870 ignored=0
INFO [08-24|21:53:16] Imported new state entries               count=11   flushed=15  elapsed=2ms          processed=4572579 pending=4589  retry=0    duplicate=725 unexpected=4489
INFO [08-24|21:53:16] Imported new state entries               count=3    flushed=4   elapsed=4ms          processed=4572582 pending=4585  retry=0    duplicate=725 unexpected=4489
```

I don't even know how much of the way it is to completion. Is that "pending" field the number of blocks that still need to be imported? Should I stop it and restart it? Should I let it go the whole night? I'm confused.

**Comment by lethalman** [comment]
It's happening to me as well. Just starting a new node from scratch makes it easy to reproduce, it hangs after X blocks. Smells like a deadlock. It hangs also any attached clients.

Restarting geth will restart the syncing without any problem, at least for now.

Using 1.7.1 release here.

**Comment by ramino1** [comment]
#Hello.. i have the same problem and get a lot of:
WARN [12-15|14:07:24] Stalling state sync, dropping peer...
and some:
INFO [12-15|14:07:03] Imported new state entries...
