### ISSUE TITLE
all tests except `go test ./tests/ ` fail

### ISSUE THREAD

**Issue by s-matthew-english** [ethereum/go-ethereum#14971]
#### System information

Geth version: `1.6.7-stable-ab5646c5`
OS & Version: OSX

#### Expected behaviour

Presumably, that the tests pass

#### Actual behaviour

<img width="713" alt="screen shot 2017-08-13 at 8 02 46 pm" src="https://user-images.githubusercontent.com/9053984/29254379-69dcea08-8062-11e7-9bc1-38564340f3c9.png">

<img width="639" alt="screen shot 2017-08-13 at 8 03 13 pm" src="https://user-images.githubusercontent.com/9053984/29254383-775caea2-8062-11e7-80c4-8fc67f23b53a.png">

<img width="651" alt="screen shot 2017-08-13 at 8 03 29 pm" src="https://user-images.githubusercontent.com/9053984/29254385-805a3e3e-8062-11e7-9a59-acae78d81dc3.png">

<img width="725" alt="screen shot 2017-08-13 at 8 03 45 pm" src="https://user-images.githubusercontent.com/9053984/29254388-8d7240ee-8062-11e7-87da-9dce9b8e140d.png">

<img width="684" alt="screen shot 2017-08-13 at 8 04 04 pm" src="https://user-images.githubusercontent.com/9053984/29254391-976e52b8-8062-11e7-9b86-a1babc5b6ba7.png">

#### Steps to reproduce the behaviour

Running the tests as described on [https://github.com/ethereum/go-ethereum/wiki/Developers'-Guide](https://github.com/ethereum/go-ethereum/wiki/Developers'-Guide)

#### Backtrace

...what is a backtrace? 

````
[backtrace]
````

so, please forgive me if this is naive, I'm new to testing go-ethereum but I'm trying to be useful. 

Is it better to write the output in text/code snippets rather than pictures?

**Comment by lmars** [comment]
Are you trying to run a subset of the tests? If so, you should use the `-run` flag, for example:

```
$ go test ./tests -run TestRLP
```

**Comment by fjl** [comment]
`go test <go file>` does not work because it doesn't compile the package. Use `go test ./tests`.

**Comment by s-matthew-english** [comment]
@fjl I guess that works, this was the output: 

<img width="723" alt="screen shot 2017-08-14 at 10 34 46 am" src="https://user-images.githubusercontent.com/9053984/29276334-417d925e-80dc-11e7-96cb-5ede5a703796.png">

What I was doing was trying to execute the examples described here: 

https://github.com/ethereum/go-ethereum/wiki/Testing

@lmars cool, that seems to work
