### ISSUE TITLE
Wallet new stops syncing last blocks (4 days syncing still not completed)

### ISSUE THREAD

**Issue by tomtom87** [ethereum/go-ethereum#14988]
#### System information

Geth version: `geth 1.6.6`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour
Wallet sync of Mac OSX client 

#### Actual behaviour
Cannot finish syncing, forever downloading chain structure and the last 100 blocks.

#### Steps to reproduce the behaviour
1. Install ethereum wallet 0.9.0 on mac osx
2. try to sync
3. wait 3 days with nothing happening
4. slowly loose your sanity 

#### Backtrace

````
[backtrace]
````

**Comment by tomtom87** [comment]
![screen shot 2560-08-17 at 12 36 05 pm](https://user-images.githubusercontent.com/2025975/29397492-c09cb22c-8348-11e7-8869-14b8b4f13274.png)

**Comment by tomtom87** [comment]
https://github.com/ethereum/go-ethereum/issues/14995

**Comment by tomtom87** [comment]
Now get this 

```
WARN [08-21|11:48:26] Stalling state sync, dropping peer       peer=655c0278c317a012
WARN [08-21|11:48:26] Stalling state sync, dropping peer       peer=f26dce0aea871dc8
WARN [08-21|11:48:26] Stalling state sync, dropping peer       peer=0fb49536fda319d3
WARN [08-21|11:48:27] Stalling state sync, dropping peer       peer=ae8de9feee4df4e6
WARN [08-21|11:48:27] Stalling state sync, dropping peer       peer=e7a69c447cb83857
WARN [08-21|11:48:30] Stalling state sync, dropping peer       peer=8e8edc9627fedc6b
WARN [08-21|11:48:32] Stalling state sync, dropping peer       peer=606587b48a16fd10
WARN [08-21|11:48:32] Node data write error                    err="state node 638deb…cf0f09 failed with all peers (4 tries, 4 peers)"
```

**Comment by wtfiwtz** [comment]
See #15001 as it seems to be an issue with the `chain height` being incorrectly determined
