### ISSUE TITLE
Travis CI build fails due to some `hid` library problem but not on all configs

### ISSUE THREAD

**Issue by holisticode** [ethereum/go-ethereum#14984]
#### System information

This happens in the `continuous-integration/travis-ci/pr` for ethereum PRs

#### Expected behaviour

Checks complete

#### Actual behaviour

Checks fail: `--- FAIL: TestCLISwarmUp (38.66s)`
Same test succeeds locally.
But fails only on specific configurations - others complete successfully.

#### Steps to reproduce the behaviour

Check PR
https://github.com/ethereum/go-ethereum/pull/14967:
```
continuous-integration/travis-ci/pr — The Travis CI build failed
https://travis-ci.org/ethereum/go-ethereum/jobs/264784754
```

#### Backtrace

````
https://travis-ci.org/ethereum/go-ethereum/jobs/264784754
````

@karalabe

**Comment by karalabe** [comment]
Yes, I saw this failure. A few people reported it in the wild, but we couldn't repro it, so the CI failure is actually good. I'll look into it next week, seems to be a data race in the OSX USB HID library.

**Comment by karalabe** [comment]
Should be fixed now on master.
