### ISSUE TITLE
geth 1.6.7 OOM after 2 mins in windows-386/go1.8.3

### ISSUE THREAD

**Issue by parti-zanu** [ethereum/go-ethereum#14986]
OS & Version: Win7 x86 /4G RAM
Node version: geth v1.6.7-stable-ab5646c5
Number of blocks synchronized: 3929048

_output and trace attached_

**geth.exe --fast --verbosity 5 --trace trace.txt --debug**

INFO [08-16|23:39:22|core/blockchain.go:817] Imported new block receipts count=136 elapsed=1.641s number=3929944 hash=a496c1…ac6073 ignored=268
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> NEIGHBORS/v4 addr=68.74.117.233:1027 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> NEIGHBORS/v4 addr=68.74.117.233:1027 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:523] << FINDNODE/v4 addr=68.74.117.233:1027 err=nil
TRACE[08-16|23:39:22|eth/downloader/peer.go:284] Peer throughput measurements updated peer=35e1e3de3198ebab hps=113.068 bps=15.748 rps=17.100 sps=0.015 miss=0 rtt=3.183730018s
TRACE[08-16|23:39:22|eth/downloader/downloader.go:1025] Delivered new batch of data peer=35e1e3de3198ebab type=receipts count=91
TRACE[08-16|23:39:22|eth/downloader/downloader.go:1112] Requesting new batch of data peer=35e1e3de3198ebab type=receipts count=136 from=3935583
DEBUG[08-16|23:39:22|eth/peer.go:227] Fetching batch of receipts id=35e1e3de3198ebab conn=inbound count=136
TRACE[08-16|23:39:22|eth/downloader/downloader.go:1023] Requested data not delivered peer=d6bb338e2298066b type=receipts
TRACE[08-16|23:39:22|p2p/server.go:663] Accepted connection addr=85.166.201.223:61120
DEBUG[08-16|23:39:22|eth/handler.go:441] Verified to be on the same side of the DAO fork id=98b6db261b42f2f6 conn=inbound
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> NEIGHBORS/v4 addr=189.38.159.244:30399 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> NEIGHBORS/v4 addr=189.38.159.244:30399 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:523] << FINDNODE/v4 addr=189.38.159.244:30399 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> PONG/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:523] << PING/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:22|p2p/dial.go:324] Dial error task="dyndial bf2c0b834800b88f 77.172.117.67:30303" err="dial tcp 77.172.117.67:30303: i/o timeout"
TRACE[08-16|23:39:22|p2p/server.go:528] Dial task done task="dyndial bf2c0b834800b88f 77.172.117.67:30303"
TRACE[08-16|23:39:22|p2p/server.go:481] New dial task task="dyndial ff435e4f00bf6feb 101.100.143.143:30303"
DEBUG[08-16|23:39:22|p2p/server.go:548] Adding p2p peer id=1afc596771a7a0c1 name=Geth/v1.6.6-stable-1... addr=85.166.201.223:61120 peers=16
TRACE[08-16|23:39:22|p2p/peer.go:299] Starting protocol eth/63 id=1afc596771a7a0c1 conn=inbound
DEBUG[08-16|23:39:22|eth/handler.go:249] Ethereum peer connected id=1afc596771a7a0c1 conn=inbound name=Geth/v1.6.6-stable-10a45cb5/darwin-amd64/go1.8.3
TRACE[08-16|23:39:22|eth/downloader/downloader.go:276] Registering sync peer peer=1afc596771a7a0c1
DEBUG[08-16|23:39:22|eth/peer.go:207] Fetching batch of headers id=1afc596771a7a0c1 conn=inbound count=1 fromnum=1920000 skip=0 reverse=false
TRACE[08-16|23:39:22|eth/downloader/downloader.go:1112] Requesting new batch of data peer=1afc596771a7a0c1 type=receipts count=2 from=3936282
DEBUG[08-16|23:39:22|eth/peer.go:227] Fetching batch of receipts id=1afc596771a7a0c1 conn=inbound count=2
TRACE[08-16|23:39:22|p2p/dial.go:324] Dial error task="dyndial bb0b87c356eb578d 93.234.160.49:30303" err="dial tcp 93.234.160.49:30303: i/o timeout"
TRACE[08-16|23:39:22|p2p/server.go:528] Dial task done task="dyndial bb0b87c356eb578d 93.234.160.49:30303"
TRACE[08-16|23:39:22|p2p/server.go:481] New dial task task="dyndial e597b8c9ef35e082 62.158.130.54:30303"
TRACE[08-16|23:39:22|eth/downloader/peer.go:284] Peer throughput measurements updated peer=b080b181af782451 hps=131.803 bps=72.631 rps=39.809 sps=0.000 miss=0 rtt=1.57780081s
TRACE[08-16|23:39:22|eth/downloader/downloader.go:1025] Delivered new batch of data peer=b080b181af782451 type=receipts count=89
TRACE[08-16|23:39:22|eth/downloader/downloader.go:1112] Requesting new batch of data peer=b080b181af782451 type=receipts count=167 from=3934813
DEBUG[08-16|23:39:22|eth/peer.go:227] Fetching batch of receipts id=b080b181af782451 conn=inbound count=167
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> PONG/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:523] << PING/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:22|p2p/dial.go:324] Dial error task="dyndial 32c8a6f3811d2b24 186.23.84.95:30303" err="dial tcp 186.23.84.95:30303: connectex: No connection could be made because the target machine actively refused it."
TRACE[08-16|23:39:22|p2p/server.go:528] Dial task done task="dyndial 32c8a6f3811d2b24 186.23.84.95:30303"
TRACE[08-16|23:39:22|p2p/server.go:481] New dial task task="discovery lookup"
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> FINDNODE/v4 addr=80.7.1.171:1127 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> FINDNODE/v4 addr=84.165.48.34:61033 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> FINDNODE/v4 addr=5.44.121.127:30303 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> PONG/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:523] << PING/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:22|eth/downloader/peer.go:284] Peer throughput measurements updated peer=5f21a4a1474a3cbc hps=214.679 bps=60.382 rps=42.492 sps=0.000 miss=0 rtt=1.987193562s
TRACE[08-16|23:39:22|eth/downloader/downloader.go:1025] Delivered new batch of data peer=5f21a4a1474a3cbc type=receipts count=67
TRACE[08-16|23:39:22|p2p/discover/udp.go:523] << NEIGHBORS/v4 addr=5.44.121.127:30303 err=nil
TRACE[08-16|23:39:22|eth/downloader/downloader.go:1112] Requesting new batch of data peer=5f21a4a1474a3cbc type=receipts count=189 from=3934100
DEBUG[08-16|23:39:22|eth/peer.go:227] Fetching batch of receipts id=5f21a4a1474a3cbc conn=inbound count=189
TRACE[08-16|23:39:22|p2p/discover/udp.go:523] << NEIGHBORS/v4 addr=5.44.121.127:30303 err=nil
TRACE[08-16|23:39:22|p2p/discover/table.go:471] Starting bonding ping/pong id=acfb84f4fb44cc62 known=true failcount=1 age=1h32m24.8496s
TRACE[08-16|23:39:22|p2p/discover/table.go:471] Starting bonding ping/pong id=a608482b451a7482 known=true failcount=1 age=15h32m20.8516s
TRACE[08-16|23:39:22|p2p/discover/table.go:471] Starting bonding ping/pong id=8e2eb24bbdc7982e known=true failcount=0 age=24h17m14.8536s
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> PING/v4 addr=216.201.219.206:30303 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> PING/v4 addr=178.33.32.216:30303 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> PING/v4 addr=117.89.57.8:30303 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:468] >> PING/v4 addr=120.27.252.209:30303 err=nil
TRACE[08-16|23:39:22|p2p/discover/udp.go:523] << PONG/v4 addr=178.33.32.216:30303 err=nil
TRACE[08-16|23:39:23|eth/downloader/peer.go:284] Peer throughput measurements updated peer=8d3ea2ebd47f2ba8 hps=113.234 bps=23.710 rps=17.342 sps=0.032 miss=0 rtt=4.498527738s
TRACE[08-16|23:39:23|eth/downloader/downloader.go:1025] Delivered new batch of data peer=8d3ea2ebd47f2ba8 type=receipts count=95
TRACE[08-16|23:39:23|eth/downloader/downloader.go:1023] Requested data not delivered peer=2302daf1bc887170 type=receipts
TRACE[08-16|23:39:23|eth/downloader/downloader.go:1112] Requesting new batch of data peer=8d3ea2ebd47f2ba8 type=receipts count=89 from=3935007
DEBUG[08-16|23:39:23|eth/peer.go:227] Fetching batch of receipts id=8d3ea2ebd47f2ba8 conn=inbound count=89
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << PONG/v4 addr=120.27.252.209:30303 err=nil
DEBUG[08-16|23:39:23|eth/handler.go:441] Verified to be on the same side of the DAO fork id=1afc596771a7a0c1 conn=inbound
TRACE[08-16|23:39:23|p2p/discover/table.go:280] Bumping findnode failure counter id=ebc1b92e64c8dd4a failcount=1
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> FINDNODE/v4 addr=73.61.83.173:30399 err=nil
TRACE[08-16|23:39:23|p2p/discover/table.go:280] Bumping findnode failure counter id=886c025ecec4c95c failcount=1
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> FINDNODE/v4 addr=78.107.166.112:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> PING/v4 addr=178.33.32.216:30303 err=nil
TRACE[08-16|23:39:23|eth/downloader/peer.go:284] Peer throughput measurements updated peer=1afc596771a7a0c1 hps=104.960 bps=18.368 rps=11.068 sps=0.009 miss=0 rtt=2.956557016s
TRACE[08-16|23:39:23|eth/downloader/downloader.go:1025] Delivered new batch of data peer=1afc596771a7a0c1 type=receipts count=2
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << NEIGHBORS/v4 addr=78.107.166.112:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << NEIGHBORS/v4 addr=78.107.166.112:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/table.go:471] Starting bonding ping/pong id=70133e4f91dc3dee known=true failcount=1 age=24h9m38.3656s
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> PING/v4 addr=40.121.221.116:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/table.go:471] Starting bonding ping/pong id=885f4d36852df98b known=false failcount=0 age=417476h39m23.3666s
TRACE[08-16|23:39:23|p2p/discover/table.go:471] Starting bonding ping/pong id=0a30b2345675dc14 known=true failcount=0 age=24h2m30.3666s
TRACE[08-16|23:39:23|p2p/discover/table.go:471] Starting bonding ping/pong id=012496a6973bcd65 known=true failcount=1 age=11h37m7.3676s
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> PING/v4 addr=73.106.93.129:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> PING/v4 addr=108.51.241.214:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> PING/v4 addr=88.99.166.217:30303 err=nil
TRACE[08-16|23:39:23|p2p/server.go:663] Accepted connection addr=147.135.243.250:55525
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << PONG/v4 addr=178.33.32.216:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << PONG/v4 addr=88.99.166.217:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> PONG/v4 addr=88.99.166.217:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << PING/v4 addr=88.99.166.217:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> PING/v4 addr=178.33.32.216:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << NEIGHBORS/v4 addr=73.61.83.173:30399 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << NEIGHBORS/v4 addr=73.61.83.173:30399 err=nil
TRACE[08-16|23:39:23|p2p/discover/table.go:471] Starting bonding ping/pong id=3e4a731adfd6bd74 known=true failcount=1 age=11h22m11.4176s
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> PING/v4 addr=109.155.228.154:30303 err=nil
DEBUG[08-16|23:39:23|p2p/server.go:548] Adding p2p peer id=d85b97c19c8f0903 name=Geth/v1.6.6-stable-1... addr=147.135.243.250:55525 peers=17
TRACE[08-16|23:39:23|p2p/peer.go:299] Starting protocol eth/63 id=d85b97c19c8f0903 conn=inbound
DEBUG[08-16|23:39:23|eth/handler.go:249] Ethereum peer connected id=d85b97c19c8f0903 conn=inbound name=Geth/v1.6.6-stable-10a45cb5/windows-amd64/go1.8.3
TRACE[08-16|23:39:23|eth/downloader/downloader.go:276] Registering sync peer peer=d85b97c19c8f0903
DEBUG[08-16|23:39:23|eth/peer.go:207] Fetching batch of headers id=d85b97c19c8f0903 conn=inbound count=1 fromnum=1920000 skip=0 reverse=false
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << PONG/v4 addr=178.33.32.216:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> PONG/v4 addr=185.107.83.10:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << PING/v4 addr=185.107.83.10:30303 err=nil
DEBUG[08-16|23:39:23|eth/handler.go:441] Verified to be on the same side of the DAO fork id=d85b97c19c8f0903 conn=inbound
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << PONG/v4 addr=108.51.241.214:30303 err=nil
TRACE[08-16|23:39:23|eth/downloader/peer.go:284] Peer throughput measurements updated peer=b080b181af782451 hps=131.803 bps=72.631 rps=45.303 sps=0.000 miss=0 rtt=1.526620729s
TRACE[08-16|23:39:23|eth/downloader/downloader.go:1025] Delivered new batch of data peer=b080b181af782451 type=receipts count=101
TRACE[08-16|23:39:23|eth/downloader/downloader.go:1112] Requesting new batch of data peer=b080b181af782451 type=receipts count=66 from=3935454
DEBUG[08-16|23:39:23|eth/peer.go:227] Fetching batch of receipts id=b080b181af782451 conn=inbound count=66
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> PING/v4 addr=178.33.32.216:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> PONG/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << PING/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << PONG/v4 addr=178.33.32.216:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> FINDNODE/v4 addr=54.198.102.178:1045 err=nil
DEBUG[08-16|23:39:23|eth/fetcher/fetcher.go:332] Peer discarded announcement peer=35e1e3de3198ebab number=4166439 hash=d6bcc4…19cda1 distance=4166439
TRACE[08-16|23:39:23|eth/downloader/peer.go:284] Peer throughput measurements updated peer=35e1e3de3198ebab hps=113.068 bps=15.748 rps=20.864 sps=0.015 miss=0 rtt=3.035257016s
TRACE[08-16|23:39:23|eth/downloader/downloader.go:1025] Delivered new batch of data peer=35e1e3de3198ebab type=receipts count=93
TRACE[08-16|23:39:23|eth/downloader/downloader.go:1112] Requesting new batch of data peer=35e1e3de3198ebab type=receipts count=43 from=3936302
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> PONG/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:523] << PING/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> PING/v4 addr=178.33.32.216:30303 err=nil
TRACE[08-16|23:39:23|p2p/discover/udp.go:468] >> FINDNODE/v4 addr=194.153.22.76:30303 err=nil
DEBUG[08-16|23:39:23|eth/fetcher/fetcher.go:612] Discarded propagated block, too far away peer=dee6474df94cd49c number=4166439 hash=d6bcc4…19cda1 distance=4166439
DEBUG[08-16|23:39:23|eth/fetcher/fetcher.go:332] Peer discarded announcement peer=dee6474df94cd49c number=4166439 hash=d6bcc4…19cda1 distance=4166439
DEBUG[08-16|23:39:23|eth/peer.go:227] Fetching batch of receipts id=35e1e3de3198ebab conn=inbound count=43
TRACE[08-16|23:39:24|p2p/discover/udp.go:523] << PONG/v4 addr=178.33.32.216:30303 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> FINDNODE/v4 addr=68.5.78.202:30303 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> PONG/v4 addr=50.203.154.218:30399 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:523] << PING/v4 addr=50.203.154.218:30399 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> PING/v4 addr=178.33.32.216:30303 err=nil
DEBUG[08-16|23:39:24|eth/handler.go:297] Ethereum message handling failed id=95c71f602420df48 conn=inbound err="write tcp 192.168.1.2:30303->89.205.125.158:12354: wsasend: An existing connection was forcibly closed by the remote host."
DEBUG[08-16|23:39:24|eth/handler.go:188] Removing Ethereum peer peer=95c71f602420df48
TRACE[08-16|23:39:24|eth/downloader/downloader.go:297] Unregistering sync peer peer=95c71f602420df48
TRACE[08-16|23:39:24|eth/downloader/peer.go:284] Peer throughput measurements updated peer=d208b5afdf2d359d hps=89.690 bps=13.593 rps=11.270 sps=0.000 miss=0 rtt=4.01566716s
TRACE[08-16|23:39:24|p2p/peer.go:306] Protocol eth/63 failed id=95c71f602420df48 conn=inbound err="write tcp 192.168.1.2:30303->89.205.125.158:12354: wsasend: An existing connection was forcibly closed by the remote host."
DEBUG[08-16|23:39:24|p2p/server.go:559] Removing p2p peer id=95c71f602420df48 conn=inbound duration=29.543s peers=16 req=false err="write tcp 192.168.1.2:30303->89.205.125.158:12354: wsasend: An existing connection was forcibly closed by the remote host."
TRACE[08-16|23:39:24|eth/downloader/downloader.go:1025] Delivered new batch of data peer=d208b5afdf2d359d type=receipts count=100
DEBUG[08-16|23:39:24|accounts/keystore/account_cache.go:227] Reloaded keystore contents accounts=0
TRACE[08-16|23:39:24|p2p/discover/udp.go:523] << PONG/v4 addr=178.33.32.216:30303 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> NEIGHBORS/v4 addr=121.161.229.243:1115 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> NEIGHBORS/v4 addr=121.161.229.243:1115 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:523] << FINDNODE/v4 addr=121.161.229.243:1115 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> PONG/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:523] << PING/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:24|eth/downloader/peer.go:284] Peer throughput measurements updated peer=dee6474df94cd49c hps=101.078 bps=14.585 rps=9.552 sps=0.055 miss=0 rtt=6.380926296s
TRACE[08-16|23:39:24|eth/downloader/downloader.go:1025] Delivered new batch of data peer=dee6474df94cd49c type=receipts count=89
TRACE[08-16|23:39:24|eth/downloader/downloader.go:1112] Requesting new batch of data peer=d85b97c19c8f0903 type=receipts count=2 from=3932394
DEBUG[08-16|23:39:24|eth/peer.go:227] Fetching batch of receipts id=d85b97c19c8f0903 conn=inbound count=2
TRACE[08-16|23:39:24|eth/downloader/downloader.go:1112] Requesting new batch of data peer=b080b181af782451 type=bodies count=2 from=3932989
DEBUG[08-16|23:39:24|eth/peer.go:214] Fetching batch of block bodies id=b080b181af782451 conn=inbound count=2
TRACE[08-16|23:39:24|p2p/discover/table.go:280] Bumping findnode failure counter id=502a2e92874046cb failcount=1
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> FINDNODE/v4 addr=178.84.95.10:30303 err=nil
TRACE[08-16|23:39:24|eth/fetcher/fetcher.go:250] Filtering bodies txs=2 uncles=2
TRACE[08-16|23:39:24|eth/downloader/peer.go:284] Peer throughput measurements updated peer=b080b181af782451 hps=131.803 bps=72.631 rps=51.005 sps=0.000 miss=0 rtt=1.438458656s
TRACE[08-16|23:39:24|eth/downloader/downloader.go:1025] Delivered new batch of data peer=b080b181af782451 type=receipts count=66
TRACE[08-16|23:39:24|eth/downloader/peer.go:284] Peer throughput measurements updated peer=b080b181af782451 hps=131.803 bps=67.409 rps=51.005 sps=0.000 miss=0 rtt=1.30441279s
TRACE[08-16|23:39:24|eth/downloader/downloader.go:1025] Delivered new batch of data peer=b080b181af782451 type=bodies count=2:2
TRACE[08-16|23:39:24|p2p/discover/udp.go:523] << NEIGHBORS/v4 addr=178.84.95.10:30303 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:523] << NEIGHBORS/v4 addr=178.84.95.10:30303 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> PING/v4 addr=178.33.32.216:30303 err=nil
TRACE[08-16|23:39:24|p2p/discover/table.go:471] Starting bonding ping/pong id=b60535ff309223dd known=true failcount=1 age=7h21m19.3416s
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> PING/v4 addr=83.183.110.251:30303 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> NEIGHBORS/v4 addr=73.72.77.23:30399 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> NEIGHBORS/v4 addr=73.72.77.23:30399 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:523] << FINDNODE/v4 addr=73.72.77.23:30399 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:523] << PONG/v4 addr=178.33.32.216:30303 err=nil
DEBUG[08-16|23:39:24|eth/downloader/downloader.go:1527] Recalculated downloader QoS values rtt=10.576355545s confidence=0.947 ttl=33.513350952s
TRACE[08-16|23:39:24|p2p/discover/table.go:280] Bumping findnode failure counter id=1ad6414f2ff7b744 failcount=1
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> FINDNODE/v4 addr=195.206.61.219:19941 err=nil
TRACE[08-16|23:39:24|p2p/discover/table.go:280] Bumping findnode failure counter id=567bd12499ec2829 failcount=1
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> PONG/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:523] << PING/v4 addr=77.172.117.67:30303 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:523] << NEIGHBORS/v4 addr=195.206.61.219:19941 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:468] >> FINDNODE/v4 addr=64.228.82.254:30399 err=nil
TRACE[08-16|23:39:24|p2p/discover/udp.go:523] << NEIGHBORS/v4 addr=195.206.61.219:19941 err=nil
runtime: out of memory: cannot allocate 65536-byte block (1072955392 in use)
fatal error: out of memory
[output.zip](https://github.com/ethereum/go-ethereum/files/1229493/output.zip)
[trace.zip](https://github.com/ethereum/go-ethereum/files/1229494/trace.zip)

**Comment by almindor** [comment]
Any news on this? I have at least twurlo users who got geth OOM error when trying to sign/send a tx using Etherwall. Geth crashes and the TX never makes it out (see linked issue for logs)

**Comment by obscuren** [comment]
If you’re running 1.6 you want to update. See if that resolves your issues.

**Comment by almindor** [comment]
I've had it reported with v1.7.2, see attached issue for geth logs (includes versions)

**Comment by adamschmideg** [comment]
@parti-zanu this problem occurred a long time ago; if it still persists, please, open a new issue.
