### ISSUE TITLE
No one can sync for 4 days, nodes disconnect

### ISSUE THREAD

**Issue by tomtom87** [ethereum/go-ethereum#14995]
#### System information

Geth version: `1.6.6`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour
Sync ethereum osx wallet or command line `geth --fast` to the mainnet

#### Actual behaviour
4 days of disconnection and not able to sync. closest it has got is the last 100 blocks, never can finish.
takes up all my cpu and same for all my offices machines, some people had to sync to myetherewallet just to get their money out.

On using `geth --fast` for the past 24 hours, the following errors continually appear after around 3 hours of operation.

![screen shot 2560-08-18 at 7 15 59 am](https://user-images.githubusercontent.com/2025975/29440107-66543638-83ec-11e7-86d6-8d2f38ed740b.png)

#### Steps to reproduce the behaviour
1. Download the ethereum wallet app
2. Use it

#### Backtrace

````
INFO [08-18|07:41:16] Imported new state entries               count=2    flushed=0 elapsed=6.651s    processed=277 pending=361  retry=10 duplicate=0 unexpected=0
INFO [08-18|07:41:21] Imported new state entries               count=2    flushed=0 elapsed=5.688s    processed=279 pending=393  retry=8  duplicate=0 unexpected=0
WARN [08-18|07:41:21] Stalling state sync, dropping peer       peer=004649d039699907
WARN [08-18|07:41:21] Stalling state sync, dropping peer       peer=d478537f376e7ba9
WARN [08-18|07:41:21] Stalling state sync, dropping peer       peer=69fe04acb2e3a4c5
WARN [08-18|07:41:21] Stalling state sync, dropping peer       peer=90488e244f9462de
WARN [08-18|07:41:22] Stalling state sync, dropping peer       peer=49f95d5818beed30
WARN [08-18|07:41:22] Stalling state sync, dropping peer       peer=231d449de36ce433
WARN [08-18|07:41:22] Stalling state sync, dropping peer       peer=d9b09696b5eaa25c
WARN [08-18|07:41:22] Stalling state sync, dropping peer       peer=90a6e567d3bef0a8
WARN [08-18|07:41:22] Stalling state sync, dropping peer       peer=79afd3322ab9c0b8
````

**Comment by tomtom87** [comment]
Now get this error after using `--fast --cache=1024` as suggested here

```
WARN [08-21|11:48:26] Stalling state sync, dropping peer       peer=655c0278c317a012
WARN [08-21|11:48:26] Stalling state sync, dropping peer       peer=f26dce0aea871dc8
WARN [08-21|11:48:26] Stalling state sync, dropping peer       peer=0fb49536fda319d3
WARN [08-21|11:48:27] Stalling state sync, dropping peer       peer=ae8de9feee4df4e6
WARN [08-21|11:48:27] Stalling state sync, dropping peer       peer=e7a69c447cb83857
WARN [08-21|11:48:30] Stalling state sync, dropping peer       peer=8e8edc9627fedc6b
WARN [08-21|11:48:32] Stalling state sync, dropping peer       peer=606587b48a16fd10
WARN [08-21|11:48:32] Node data write error                    err="state node 638deb…cf0f09 failed with all peers (4 tries, 4 peers)"
```

**Comment by csillag** [comment]
Isn't this a duplicate of #14988? If not, what is the difference?

**Comment by tomtom87** [comment]
@csillag this is running direct in CLI with `geth` other is using the wallet app, was told to post here by mist team

**Comment by pheuter** [comment]
Running into the same exact issues using **geth 1.6.6-stable-10a45cb5** on Windows 10 with:
`$ geth.exe --syncmode fast`.

It gets 99.99% of the way there relatively easily and then for the remainder 1000 blocks or so just poops out, frequently dropping peers and failing to make any progress.

Any guidance greatly appreciated.

**Comment by tomtom87** [comment]
@pheuter yeh I am also getting this issue on mac and linux, I am even unable to create a working private net since monday this week. 

No idea what to do but I am sure this is effecting everyone - I have seen countless issues recently on these repos reporting the same.

Waiting for a official update to this, apparently some big changes are coming in october for smart contracts - i dunno if people will wait that long though

**Comment by pheuter** [comment]
@tomtom87 what _did_ end up working for me is running the latest [ethereum/client-go](https://hub.docker.com/r/ethereum/client-go/) Docker image.

**Comment by tomtom87** [comment]
@pheuter ok I will try this today thanks for that

**Comment by tomtom87** [comment]
Ok to fix this you have to do the following:
1. Get a SSD 
2. Use the docker image from [ethereum/client-go](https://hub.docker.com/r/ethereum/client-go/) 
3. Continually start and restart the client until you loose all hope it will ever work, if it gets stuck at 99% thats normal.
4. After about 2 days of this, around about this point a miracle will happen and the client will crash randomly
5. When you open it again after this crash, magically you will have sync. This took me a total of 48 hours continuous sync on a MacBook Pro.

**Comment by csillag** [comment]
> After about 2 days of this, around about this point a miracle will happen and the client will crash randomly

I wouldn't really consider this a reliably solution. Would you?

**Comment by tomtom87** [comment]
Not even for a minute. And we put our hard earned coins into it... Wait till you try deploying a contract mate. 48 hours now nonstop and it got 500 confirmations on etherscan.... 

This software really is PoS.. literally ;)  More ethereum grows more growin pains. And not one word from support... nice

**Comment by wtfiwtz** [comment]
See #15001 - possibly due to `chain height` being incorrect
