### ISSUE TITLE
Access Issues Running in Docker

### ISSUE THREAD

**Issue by mcqj** [ethereum/go-ethereum#14994]
#### System information

Geth version: 1.6.7-stable
OS & Version: OSX 10.12.6 / Docker 17.06 / Alpine Linux 3.5.2

#### Expected behaviour
Curl commands executed outside the container produce the same result as curl commands inside the container.

#### Actual behaviour
Some commands behave the same but not all commands.

#### Steps to reproduce the behaviour
- Start a private ethereum n/w inside docker with ports mapped to the host. Start mining.
- Attach to the shell in the container
- issue a curl command
- Detach and issue the same curl command
- compare results

#### Example 1

````
$ docker exec -it fc91cee71783 /bin/ash
/go # curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":["0x1b3f349a7186ea1abab08ffd04bd9cf2ee6fb13e"]}
/go
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":["0x1b3f349a7186ea1abab08ffd04bd9cf2ee6fb13e"]}
````
Observe that the result is the same in both cases.

#### Example 2

````
$ docker exec -it fc91cee71783 /bin/ash
/go # curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x1b3f349a7186ea1abab08ffd04bd9cf2ee6fb13e","late
st"],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":"0x2052a187ee9ea900000"}
/go 
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x1b3f349a7186ea1afd04bd9cf2ee6fb13e","latest"],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":"0x0"}
````
Observe that the result when outside the container returns a balance of zero while inside the container the correct balance is returned.

**Comment by holiman** [comment]
My guess is the two geth's are on different blocks. Check what `eth.getBlockNumber` gets from each.

**Comment by mcqj** [comment]
There is only one geth - I'm posting to it over http. I'm posting from two
different places - inside and outside the container.
