### ISSUE TITLE
How to use Geth on ios

### ISSUE THREAD

**Issue by dtco-kimi** [ethereum/go-ethereum#14997]
I'm new to Ethereum. I'm trying to use Geth to implement a wallet-like SDK on ios with Objective-C. I found all the classes in Geth for ios library init with a GoSeqRef object. However, the GoSeqRef object is initialized with 'id' type. I totally have no idea what kind of object I should pass in. I can't find any sample code in Objective-C on the Internet. I don't know how to start....
Anyone can help? Any help is appreciated.

Besides, the wiki says "In-process Ethereum, Whisper and Swarm peer-to-peer node". Do I have to run a node on my mobile devices? We are running a private chain so any interaction with the chain on the mobile devices have to pass through our API server. Therefore, we don't want/need to run a node on the device. We only need to get an address, create a raw transaction and encode ABI functions/parameters.

Thanks!

**Comment by karalabe** [comment]
Use these for starters:

 * https://github.com/ethereum/go-ethereum/wiki/Mobile:-Introduction
 * https://github.com/ethereum/go-ethereum/wiki/Mobile:-Account-management

**Comment by dtco-kimi** [comment]
@karalabe , Thanks for your reply. 

I have read these before. It's all about Swift.... I still don't know to start with Obj-C. How to init  GoSeqRef object as I mentioned. All classes in Geth.objc.h are not allowed to use init and have to use initWithRef. I have no idea what I should pass to initWithRef.

**Comment by dtco-kimi** [comment]
@karalabe , Sorry, my mistake...

I didn't found FOUNDATION_EXPORT functions.  I know how to start now...
One more question, if I have a private key, how do I get the address from the private key? Functions almost  are 'new' something like, NewNode, NewKeyStores or NewAddress not start from existing ones.

Thanks.

**Comment by yaleidev** [comment]
@dtco-kimi  hi,are you solved?

**Comment by yaleidev** [comment]
@dtco-kimi  sames problems

**Comment by KimiWu123** [comment]
No, it doesn't fulfill my requests. So, I changed to web3.js to finish my job.

**Comment by yaleidev** [comment]
do you know export my private key on iOS or Android

**Comment by KimiWu123** [comment]
I didn't get your point. Export private keys to where? to what kind of format?? On Android, you can use Web3j. On iOS, that depends on your requirements. I choice Web3js, but it's more complex to use for Objective-C.

**Comment by yaleidev** [comment]
yeah,i was used Geth created ios wallet.but i don't how to use Geth export wallet private key save myself to anywhere. Does Geth have such a method？

**Comment by yaleidev** [comment]
@KimiWu123 
Only Web3js has export wallet private key  function?

**Comment by yaleidev** [comment]
@KimiWu123 
the ios client was uesed SWIFT language.
android used java.

**Comment by KimiWu123** [comment]
@yaleidev , I have no idea how to use Geth. The links in Karalabe's post is clear. If you still don't know how to use, you can new another issue to ask. But in my memory (I'm not sure), if you are using Geth, you have to run a node on your mobile, right?

**Comment by lizan2017** [comment]
i dont really understand , how does these processes work? I am using geth for swift and building an offline wallet. I am confused about the processes, can anyone please explain it briefly to me.

**Comment by lizan2017** [comment]
I did manage to create an account and store it in a keystore. Now, I have to access the balance and use transactions using block hashes.

**Comment by CodingJonas** [comment]
Did someone find some additional ressources which explain how to work with iOS?
The 2 links mentioned by karalabe are helpful, but miss information as for example how to connect to a specific blockchain.
