### ISSUE TITLE
sync problem. zero confirmation. black screen

### ISSUE THREAD

**Issue by heavenone** [ethereum/go-ethereum#14991]
Hello. big problem here. i week ago i opend my geth, wasnt synced. i sent my eth to another adress and they remaind unconfirmed until now. then i realised, it wasnt synced and wanted to let it sync. didnt work. tried for 4 days now. even deletet blockchain and synced from the start again. i takes so much disc usage that often the screen turns black and i have to reboot the pc. how can i get my unconfirmed eth out of there or in which way i can sync my geth wallet. please please help.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by tomtom87** [comment]
got the same problem, since 4 days ago cannot sync my wallet and now got ETH stuck on the network

**Comment by PersonaOnTheRun** [comment]
This thread is on mac but the geth commands are the same. [Link](https://ethereum.stackexchange.com/questions/1897/how-to-delete-or-reset-the-blockchain-in-geth-osx)
