### ISSUE TITLE
BytesToAddress doc is invalid

### ISSUE THREAD

**Issue by odeke-em** [ethereum/go-ethereum#15004]
This bug is just a request for us to update the documentation for BytesToAddress. Currently it says 
https://github.com/ethereum/go-ethereum/blob/bf1e2631281e1e439533f2abcf1e99a7b2f9552a/common/types.go#L201-L207

it promises to panic when len(b) > len(a) ie AddressLength. However, as we see in the code above, it actually offsets AddressLength from the end of b when that condition matches.

Could we perhaps update this?
I noticed this while working on the tests for @tendermint libraries

PS: here is a test to visualize the responses and check that we don't regress if that comment is retained https://gist.github.com/odeke-em/6f7daa88ac72f83fdfa2e6f5c9ff7a97 or inlined in code
```go
package address_test

import (
	"bytes"
	"testing"

	"github.com/ethereum/go-ethereum/common"
)

func TestBytestoAddress(t *testing.T) {
	tests := [...]struct {
		b         []byte
		wantPanic bool
	}{
		0: {
			b: bytes.Join([][]byte{
				[]byte("foo"),
				bytes.Repeat([]byte("a"), common.AddressLength/2),
				bytes.Repeat([]byte("z"), common.AddressLength/2),
				[]byte("b"),
			}, []byte("")),
			wantPanic: true,
		},
		1: {
			b: []byte("ethereum"),
		},
	}

	for i, tt := range tests {
		addr, res := runBytestoAddress(tt.b)
		gotPanic := res != nil
		if tt.wantPanic != gotPanic {
			t.Errorf("#%d gotPanic=(%v) wantPanic=(%v)", i, gotPanic, tt.wantPanic)
		}
		t.Logf("#%d=>\naddr=%q\nb   =%q\naddLen=%d commonLen=%d", i, addr, tt.b, len(addr), common.AddressLength)
	}
}

func runBytestoAddress(b []byte) (addr common.Address, err interface{}) {
	defer func() {
		err = recover()
	}()

	addr = common.BytesToAddress(b)
	return addr, err
}
```

**Comment by lmars** [comment]
It looks like the code was changed to not panic in https://github.com/ethereum/go-ethereum/commit/91b0b14845750c81466880f5f877fe3fcbd03b09 but the comment was not updated, I think the comment just needs to be updated to match the behaviour of the code.

**Comment by odeke-em** [comment]
Thank you @lmars for the recommendation and @fjl for the fix.
PS: This was an update courtesy of your friends from @tendermint, /cc @ebuchman @jaekwon.
