### ISSUE TITLE
Your account has been flagged.

### ISSUE THREAD

**Issue by jooboo** [ethereum/go-ethereum#15005]
Please help.
I did the following:
To request funds, simply create a GitHub Gist with your Ethereum address pasted into the contents (the file name doesn't matter), copy paste the gists URL into the above input box and fire away! You can track the current pending requests below the input field to see how much you have to wait until your turn come
I put the address in:
https://www.rinkeby.io/  cripto faucet
Then I got the answer that there is no such user (although I regained github-gist) and after that I was on github "Your account has been flagged"
So please explain to me whether I'm doing something wrong and you can unblock my github account.
Thanks

**Comment by ligi** [comment]
Very strange - just tried it for your gist and it worked fine:
![selection_143](https://user-images.githubusercontent.com/111600/29578911-4f153f16-8771-11e7-9418-e455c114f7c5.png)

**Comment by karalabe** [comment]
GitHub contacted us a few weeks ago that a lot of people are creating new/empty accounts only to use the Rinkeby faucet and their system is occasionally deleting those as invalid ones (or duplicate accounts). I don't think there's much we can do apart from implementing Google/Twitter signing for the faucet.

I'd also suggest sending an email to GitHub to clear up that it's a valid account and not a throwaway.

**Comment by DevCollinB** [comment]
hrm
