### ISSUE TITLE
Nodes on the same machine can't see each others via bootnode using discv5 protocol [Private chain]

### ISSUE THREAD

**Issue by Nigui** [ethereum/go-ethereum#15003]
#### System information

Geth version: `geth 1.6.7-stable-ab5646c5`
OS & Version:Linux

#### Expected behaviour

Two Geth instances on the same computer, connected to the same bootnode, using discovery v5 protocol, must be paired automatically.

#### Actual behaviour

Two Geth instances on the same computer, connected to the same bootnode, using discovery v5 protocol, does not pair automatically.

#### Steps to reproduce the behaviour

***On the same computer :***
* Start a bootnode from command line `bootnode -v5 -addr ":30301" [...] `
* Start the first geth node in its own datadir `geth  --datadir node1 -- port 30310 [...] --v5disc --bootnodesv5 "enode://boot_key@ip:30301?discport:30302" console"`
* Start the second geth node `geth  --datadir node2 -- port 30320 [...] --v5disc --bootnodesv5 "enode://boot_key@ip:30301?discport:30302" console"`

***In any geth console :***
```javascript
> admin.peers
[ ]
```

#### Backtrace

When I set verbosity of geth on 9, I can see the following log outputs

````
DEBUG[08-18|16:00:52] invalid neighbour (10.33.44.69) from 6b44f758e3d06707@10.33.44.69:30350: is self 
TRACE[08-18|16:00:52]                                          msg="<<< (2) neighborsPacket from 6b44f758e3d06707@10.33.44.69:30350: known -> known (ok)"
DEBUG[08-18|16:00:52] invalid neighbour (10.33.44.69) from 19a67ce07aa2ec7d@10.33.44.69:30311: is self 
TRACE[08-18|16:00:52]                                          msg="<<< (2) neighborsPacket from 19a67ce07aa2ec7d@10.33.44.69:30311: known -> known (ok)"
````
*FYI* : 
* ***10.33.44.69*** is the IP of my machine on my local network
* ***19a67ce07aa2ec7d*** is the node key of the geth instance on which I set the verbosity
* ***6b44f758e3d06707*** is the node key of my bootnode

***Possible error*** :

[this line](https://github.com/ethereum/go-ethereum/blob/357732a8404c9fe4d02f041d20a0d05381a3e6d1/p2p/discv5/net.go#L742) checks whether the neighbour has the same ip address than himself. If it's true, then it returns an error `[...] is self`.

**Comment by Tarmadol2115** [comment]
Do you find the solution? Have same problems.
