### ISSUE TITLE
Does Ethereum Wallet (geth) need to write 800 GB of data to sync finally? #414

### ISSUE THREAD

**Issue by plasticbomb1986** [ethereum/go-ethereum#15010]
#### System information

ETH Wallet version: `0.9.0`
OS & Version: Windows 10 64bit

#### Actual behaviour
"I opened it 2 weeks ago to create an address, and then i did closed it, now i did opened it again to receive some eth, it happened in the night about 1oclock, since it is still syncing and since than geth have wrote 400GB on the c drive (an SSD with 25GB free space) and it doin it by 25-145MB/s speed.
Does it neccessery to write 800GB data or there is some kind of a problem with it on my Win10PC?

During this geth is only receiving a few kb/sec from network."

i have sent this on the meteor-dapp-wallet/issue page, from there i was redirected here. since i wrote this, i had moved the folder with mklink to a 500GB SSD but it is still hair-raising how much it have to wrote to actually sync. Since then i got 2 TB more wrote to my ssd and got 20-25 GB more actual data.

**Comment by tomtom87** [comment]
I cant sync either and my disk is under 800gb, do we have to ensure we have that much freespace to get the chain now? can anyone confirm

**Comment by PersonaOnTheRun** [comment]
This might not be the optimal solution, but it is an easy work around by using Geth to fast sync. Essentially you will use Geth to quickly sync your blockchain, and then you can go back to using the ETH wallet app.

First downlaod [Geth](https://geth.ethereum.org/downloads/) .Geth stands for go-ethereum

Once its installed opend cmd (click start or hit windows button and type cmd) and type

`geth --fast`

and hit enter. if you are unfamiliar with comand line interface, what the above line essentially does is launch geth with the --fast flag. This will basically allow you to quickly download the blockchain in a significantly smaller size. 

A full description of --fast is 

> "This flag enables fast syncing through state downloads rather than downloading the full block data. This will also reduce the size of your blockchain dramatically. NOTE: --fast can only be run if you are syncing your blockchain from scratch and only the first time you download the blockchain for security reasons."


more info [here](https://github.com/ethereum/homestead-guide/blob/master/source/network/connecting-to-the-network.rst#using-geth)

**Comment by plasticbomb1986** [comment]
And after the first download, it does nothing at all, so after that it is still continue to write like hell for almost no data.

**Comment by DimaLg** [comment]
Same problem on hdd: https://github.com/ethereum/go-ethereum/issues/14895

**Comment by plasticbomb1986** [comment]
Again did synced: Had 38000 block at start i had 4.69TB write on my ssd, at finish i got 5.94TB. Started at 14:00 finish 01:00.

**Comment by tomtom87** [comment]
yeh I got a 120gb drive and its using 80gb just for ethereum. 

Pretty nice architecture

**Comment by HimanshuK18** [comment]
Why exactly the wallet needs to download all the chain (blocks)... as we only using the wallet .... not creating a node ?
