### ISSUE TITLE
Does Geth for ios support ABI function encoding?

### ISSUE THREAD

**Issue by dtco-kimi** [ethereum/go-ethereum#15015]
I'm developing a wallet-like library on ios. I'd like to encoding ABI functions/parameters and pass as a data in transaction field to create a raw transaction. However, I couldn't find API to do this. Does Geth for ios support this? 
It would be nice if sample code is available.

Thanks.

**Comment by karalabe** [comment]
I haven't yet written the abigen code generator for iOS yet.

**Comment by dtco-kimi** [comment]
Thanks for your reply! :)

**Comment by RenanSouza2** [comment]
Any updates on this. I am trying to deploy a contract through geth and it encodes correctly but inserts the params twice in the "data" field (I'm pretty sure I'm messing something up)
