### ISSUE TITLE
--autodag requires CPU mining to be ON

### ISSUE THREAD

**Issue by stephantual** [ethereum/go-ethereum#1501]
ubuntu 15.04 / geth RC2 latest

--autodag requires CPU mining to be ON

If you use --autodag and do not start CPU mining, the dag is never generated. 
Expected behaviour: geth with --autodag detects there is no dag, and creates it, without cpu mining to have to be on.

**Comment by stephantual** [comment]
Note that autodag won't work with ethminers calling the RPC server either - and even with --no-precompute, the ethminers still try to generate the dag

**Comment by hrhristov** [comment]
Is this still an issue? I do not understand why it is suggested in https://blog.ethereum.org/2015/08/04/the-thawing-frontier/
Aren't the defaults (ethminer generates the dag, geth does not) safer until this is fixed?

**Comment by stephantual** [comment]
This appears fixed (i had a dag #2 file in my ethhash folder 3 days before the epoch switch)  - but before you close I'd like to give it another look over at block 60k.

**Comment by kbkaiser** [comment]
I tried both --autodag ano --no-precompute on an AMD GPU geth with ethminer, and had to stop using both or ethminer would hang during DAG installation.

**Comment by zelig** [comment]
I think this works as expected, closing
