### ISSUE TITLE
Start mining is grayed out

### ISSUE THREAD

**Issue by Intoit82** [ethereum/go-ethereum#15027]
System information
=============
Geth version: 1.6.6
OS & Version: Windows 7
Ethereum wallet version 0.9.0
==============

Hi, 
I have a competently synced wallet working on Rinkeby test network.
![image](https://user-images.githubusercontent.com/30686909/29624935-0c281ec2-8833-11e7-8094-462d95e8766e.png)

For some reason I am unable to mine using the wallet UI nor the geth command line.

Using geth I am getting the following error:
"Block sealing failed  err=unauthorized"

My coinbase account is unlocked...
I've used the following command: personal.unlockAccount(eth.coinbase,"xxxx",0);
(with 0 parameter - so timing is not an issue)

Another strange thing is that I am not seeing the red UI box on the top which should state "TEST-NET"
![image](https://user-images.githubusercontent.com/30686909/29625004-35836b46-8833-11e7-985c-c74733eb939c.png)

By running clique I am getting:
> clique.getSnapshot()
{
  hash: "0x2a7c1112084a10353dcdffd33e9cde3c9a456dcdaa532a90e94bf75d7e1255a5",
  number: 766112,
  recents: {
    766111: "0x7ffc57839b00206d1ad20c69a1981b489f772031",
    766112: "0xb279182d99e65703f0076e4812653aab85fca0f0"
  },
  signers: {
    0x42eb768f2244c8811c63729a21a3569731535f06: {},
    0x7ffc57839b00206d1ad20c69a1981b489f772031: {},
    0xb279182d99e65703f0076e4812653aab85fca0f0: {}
  },
  tally: {},
  votes: []
}

I've also tried to remove the blockchain and reSynced it.

Please help

**Comment by karalabe** [comment]
Rinkeby is running a Proof-of-Authority consensus engine. Only authorized signers are allowed to mint new blocks. If you need ether for testing, please request from the faucet https://faucet.rinkeby.io/.

As for the UI, please open an issue on the Mist repository.
