### ISSUE TITLE
Syncing Not working

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#15020]
#### System information

Geth version: `geth 1.6.7`
OS & Version: OSX
Commit hash : (if `develop`)

####To sync the blocks

#### Steps to reproduce the behaviour

![screenshot_1503394872](https://user-images.githubusercontent.com/29792642/29559308-6023db8e-874c-11e7-8a63-8f5986ef07dd.png)

**Comment by tomtom87** [comment]
Yes this is all anyone is getting for past weeks and no response yet still waiting

**Comment by Cu4rach4** [comment]
you want to mine on android? what is your idea?

**Comment by huynh268** [comment]
Does anyone solve this issue?

**Comment by adamschmideg** [comment]
It's an old issue with little details. If you think, the problem persists, please open a new issue, include logs and the steps to reproduce it.
