### ISSUE TITLE
How is Proof-of-Stake in Now?

### ISSUE THREAD

**Issue by Yuka-kkk** [ethereum/go-ethereum#15023]
May I have a question that how is Proof-of-Stake appears in ethereum?
Is that perfectly equipped? Or not, how much does it now?
I'd like to know which release version is the one without Proof-of-Stake
that I can see differences from the latest version.
If you would tell me where have changed, I'd really appreciate.
Thank you

**Comment by ligi** [comment]
I would suggest that you use StackOverflow for questions like these - the issue tracker should be kept clean for actual issues with go-ethereum. Please head over to ethereum.stackexchange.com

**Comment by karalabe** [comment]
POS is not implemented yet. It's a research protocol.
