### ISSUE TITLE
Ether dropped from 15 to 0 after executing geth removedb

### ISSUE THREAD

**Issue by avinashkadaba** [ethereum/go-ethereum#15026]
#### System information

Geth version: latest version
OS & Version: Windows
Commit hash : 

#### Expected behaviour
ethereum.getBalance should show 15 ether

#### Actual behaviour
ethereum.getBalance should shows 0 ether

#### Steps to reproduce the behaviour
do mining for ether
verify balance using getBalance to see you mined ether
try to open ethereum wallet where ether balance shows up
But unable to send a transaction saying "gas limit reached"
I thought this was because it had synced fully as suggested by blogs so i executed "geth removedb"
After this i am trying to do getbalance my ether shows 0.

What should i do to get back my ether balance. The keystore folder is intact, i havent touched that and also remember my passphrase.

Pls Help!

#### Backtrace

````
[backtrace]
````

**Comment by avinashkadaba** [comment]
If you help me solve this I will ensure I give you .5 ether

**Comment by karalabe** [comment]
Were you in sync in the first place? If not, you were probably mining on an empty chain, hence the 15 ETH only ever existed on your machine, not on the network. Check you address on https://etherscan.io/ to verify that indeed you have the balance you think you had.

**Comment by avinashkadaba** [comment]
Ok thanks may be thats true what you said. But how to make sure i get to the fully sync state.

Also the ethereum wallet showed me 15 and when i tried to transfer it gave me "gas exceeded" message.

Can you tell me if the ethereum wallet also could show the ether without me actually having it?

**Comment by bas-vk** [comment]
The simplest way to sync with mainnet is to start geth without additional argument. By default geth will sync with mainnet. You can verify that you are on the mainnet by comparing blocks from your own chain with blocks from etherscan as karalabe suggested. Sync progress can be seen with mist (and probably other DApp's like wallets) or from the geth console with `eth.syncing`.

An ethereum wallet will retrieve account balances from an Ethereum node. If that node uses its own chain with balances on your accounts it will show them to you.
