### ISSUE TITLE
Bad documentation on whisper

### ISSUE THREAD

**Issue by chesnokovilya** [ethereum/go-ethereum#15036]
#### System information

Geth version:  1.6.7
OS & Version: Ubuntu 16.04
Commit hash : (if `develop`)

#### Expected behaviour
posting from https://github.com/ethereum/go-ethereum/wiki/Whisper-Usage
https://github.com/ethereum/go-ethereum/wiki/Whisper-v5-RPC-API

shh.post({type: 'asym', ttl: 7, topic: '0x07678231', powTarget: 2.01, powTime: 2, payload: '0x68656c6c6f', key: '0x048229fb947363cf13bb9f9532e124f08840cd6287ecae6b537cda2947ec2b23dbdc3a07bdf7cd2bfb288c25c4d0d0461d91c719da736a22b7bebbcf912298d1e6'})

curl -X POST --data '{"jsonrpc":"2.0","method":"shh_post","params":[{
  pubKey: 'b874f3bbaf031214a567485b703a025cec27d26b2c4457d6b139e56ad8734cea',
  ttl: 7,
  topic: '0x07678231',
  powTarget: 2.01,
  powTime: 2,
  payload: '0x68656c6c6f'
  }],"id":1}'

This will result in error:

Error: specify either a symetric or a asymmetric key
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1

Or json error  {"jsonrpc":"2.0","error":{"code":-32600,"message":"invalid character 'p' looking for beginning of object key string"}}

**Comment by bas-vk** [comment]
> `curl -X POST --data '{"jsonrpc":"2.0","method":"shh_post","params":[{
pubKey: 'b874f3bbaf031214a567485b703a025cec27d26b2c4457d6b139e56ad8734cea',
ttl: 7,
topic: '0x07678231',
powTarget: 2.01,
powTime: 2,
payload: '0x68656c6c6f'
}],"id":1}'`

Field names in `params[0]` should be enclosed with quotes. Also `pubKey` isn't valid.

> `Or json error {"jsonrpc":"2.0","error":{"code":-32600,"message":"invalid character 'p' looking for beginning of object key string"}}`

That means the request is invalid and probably not properly quoted.

[Here](https://gist.github.com/bas-vk/0961a9c945b3761eee7bfc4f70db75a9) is an example of a whisper chat application that I created a couple of months ago.

**Comment by RamVarma89** [comment]
Even i have been facing a similar issue:

```
curl -XPOST "localhost:8549" --header "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"shh_subscribe","params":["messages", {topics: ['0x63686174'],symKeyID: '0x22826470cece5b1427a08ee09d8590aa3c1e78600bf4253a3fbf0b9039f13992',sig: '0x048229fb947363cf13bb9f9532e124f08840cd6287ecae6b537cda2947ec2b23dbdc3a07bdf7cd2bfb288c25c4d0d0461d91c719da736a22b7bebbcf912298d1e6',pow: 12.3}],"id":1}'
```
I get the error:
` {"jsonrpc":"2.0","error":{"code":-32600,"message":"invalid character 't' looking for beginning of object key string"}} `

**Comment by gballet** [comment]
This issue has been created several time, and this one regards v5 which is about to be discontinued. Issue #17120 will be tracking the v6 version, which you are encouraged to switch to.

**Comment by avatar-lavventura** [comment]
Please consider to add following issued that I asked on [ethereum.stackexchange.com](ethereum.stackexchange.com) and solved. Hope these will help.

Please also have a look at ([How to send 1-N signalling or broadcast messages on Whisper?](https://ethereum.stackexchange.com/a/52932/4575)), which might help you. I asked the questioned and wrote the tutorial code section on the answer, please feel free to use it.

Also this could be helpful if It could also be added to documentation which was missing. ([Whisper: How could we print received messages that are actually stored in the memory when geth was closed or shh.newMessageFilter() is not activated?](https://ethereum.stackexchange.com/a/52222/4575)) . Again I asked the question and answered it.
