### ISSUE TITLE
Invalid receipt array RLP

### ISSUE THREAD

**Issue by mi2zha** [ethereum/go-ethereum#15031]
#### System information

Geth version: 1.7.0-unstable
OS & Version: OSX

curl http://localhost:8545 -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x9e09e1b8ed525feff415d5ad80a5fa5c2bcf35561f4b1a084c4534a29e8626ad"],"id":1}'

ERROR[08-24|19:48:19] Invalid receipt array RLP                hash=0eddaf…a8a375 err="rlp: input string too long for bool, decoding into ([]*types.ReceiptForStorage)[0](struct { PostState []uint8; Failed bool; CumulativeGasUsed *big.Int; Bloom types.Bloom; TxHash common.Hash; ContractAddress common.Address; Logs []*types.LogForStorage; GasUsed *big.Int }).Failed"
ERROR[08-24|19:48:19] Receipt refereced missing                number=4194205 hash=0eddaf…a8a375 index=71
ERROR[08-24|19:48:19] goroutine 35 [running]:
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func1(0xc4208a35a0, 0x5199520, 0xc422c060f0)
	/Users/guowenbin/work/Go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:135 +0x11e
panic(0x4a0ef80, 0x5269f10)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicTransactionPoolAPI).GetTransactionReceipt(0xc4255b1860, 0xef5f52edb8e1099e, 0x5cfaa580add515f4, 0x81a4b1f5635cf2b, 0xad26869ea234454c, 0x0, 0x0, 0x0)
	/Users/guowenbin/work/Go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:994 +0x1d5
reflect.Value.call(0xc4255b7980, 0xc4200870c0, 0x13, 0x4b3c5ed, 0x4, 0xc422c02240, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc4255b7980, 0xc4200870c0, 0x13, 0xc422c02240, 0x2, 0x2, 0x1, 0x1, 0x1)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc4208a35a0, 0x5194960, 0xc422c08200, 0x5199520, 0xc422c060f0, 0xc422c0a240, 0xc422c06160, 0x0, 0x49fb540)
	/Users/guowenbin/work/Go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:311 +0x758
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc4208a35a0, 0x5194960, 0xc422c08200, 0x5199520, 0xc422c060f0, 0xc422c0a240)
	/Users/guowenbin/work/Go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:333 +0x1ba
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest(0xc4208a35a0, 0x5199520, 0xc422c060f0, 0x442de01, 0x1, 0x0, 0x0)
	/Users/guowenbin/work/Go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:194 +0x3e1
github.com/ethereum/go-ethereum/rpc.(*Server).ServeSingleRequest(0xc4208a35a0, 0x5199520, 0xc422c060f0, 0x1)
	/Users/guowenbin/work/Go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:225 +0x4e
github.com/ethereum/go-ethereum/rpc.(*Server).ServeHTTP(0xc4208a35a0, 0x51936e0, 0xc4207d6000, 0xc4204d8100)
	/Users/guowenbin/work/Go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:161 +0x36c
github.com/ethereum/go-ethereum/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x51936e0, 0xc4207d6000, 0xc4204d8100)
	/Users/guowenbin/work/Go/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rs/cors/cors.go:190 +0xe9
net/http.HandlerFunc.ServeHTTP(0xc420b4c2e0, 0x51936e0, 0xc4207d6000, 0xc4204d8100)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.serverHandler.ServeHTTP(0xc42085e160, 0x51936e0, 0xc4207d6000, 0xc4204d8100)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc422c04000, 0x5194960, 0xc422c08000)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce

**Comment by holiman** [comment]
Looks like a regression, due to this: 
https://github.com/ethereum/go-ethereum/pull/15014/files#diff-cf3bf12023ca997cd6b43322a70ea69dR183

**Comment by mi2zha** [comment]
@fjl 
 When can you fix it？ thank u
