### ISSUE TITLE
New Management API for miner.setEtherbase

### ISSUE THREAD

**Issue by gogit** [ethereum/go-ethereum#15046]
#### System information

Geth version: all
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

Create a new management API for miner.setEtherbase and add it to the list of APIs
https://github.com/ethereum/go-ethereum/wiki/Management-APIs

This would enable switching between multiple accounts and starting/stopping the miners to fund each
account for automated testing on private networks.

#### Actual behaviour

N/A

#### Steps to reproduce the behaviour

N/A

#### Backtrace

N/A

**Comment by holiman** [comment]
The `miner.setEtherbase` already exists. These appear to be the existing methods: 

  * getHashrate
  * setEtherbase
  * setExtra
  * setGasPrice
  * start
  * stop

So I'll just update the wiki, and close this ticket.
