### ISSUE TITLE
Rinkeby faucet error

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#15044]
I think the screenshot describes it best:
![selection_144](https://user-images.githubusercontent.com/111600/29741081-16dc7a36-8a66-11e7-8fc3-dea6c3bb5a1f.png)

**Comment by danielvaughn** [comment]
I'm having the same issue, and have tried it with multiple machines. When I choose an amount/timespan from the button dropdown, I can see an error in my console:

WebSocket connection to 'wss://faucet.rinkeby.io/api' failed: Error during WebSocket handshake: Unexpected response code: 502

**Comment by idiotcard** [comment]
no drip from faucet for 15 +days - multiple accounts that I made just for this reason - no rinkeby test ethers

**Comment by ligi** [comment]
For the record - I got my last rinkeby test-eth ~3 days ago: https://rinkeby.etherscan.io/tx/0x14cb2ea77e72351cb264fd5eb754b57c89108da5cc8b3eaea57a1511d6da3de3

**Comment by karalabe** [comment]
I've seen a few weird errors lately, I've restarted the faucet and seems to semi-work now, apart from the light client txpool not propagating the top transaction.

The error you mentioned here seems to be a DNS lookup error (UDP, port 53). Azure isn't the solidest of hosting platforms to be honest. I don't think there's much I can do about this error (nor have I ever seen it until now). I'll close this issue and blame on Azure for now.

As for the websocket error, I'll try to implement a different handling to ensure one slow socket doesn't affect others. Hopefully that will help solve responsiveness issues.

**Comment by ligi** [comment]
Thanks - could drink from the faucet again. Also not really surprised about the problems with Azure ;-)

**Comment by idiotcard** [comment]
Can't get ether. The only source of public test ether does not work and has not worked for weeks on end.

**Comment by idiotcard** [comment]
Check your captcha settings.

**Comment by danielvaughn** [comment]
I just tried it again and it's working for me. @idiotcard was correct in that it hadn't been working for weeks. fwiw I am on OSX/Firefox 54.0.1. Hopefully that helps you.

**Comment by karalabe** [comment]
@idiotcard People are constantly successfully getting funds from the faucet https://rinkeby.etherscan.io/address/0x31b98d14007bdee637298086988a0bbd31184523

**Comment by karalabe** [comment]
@danielvaughn it was not working during last weekend, not weeks

**Comment by danielvaughn** [comment]
@karalabe ah yeah, I misspoke. What I should have said was that at some point a few weeks ago I tried and had the same issue I had this previous weekend. Perhaps it's an intermittent issue. Anyways, it's working for me, thanks!

**Comment by idiotcard** [comment]
Thanks. I was finally able to get a response from the faucet on Mac/Safari. Though another account of mine got banned in the process.
