### ISSUE TITLE
Swift: Module 'Geth' has no member named 'run'

### ISSUE THREAD

**Issue by claykohut** [ethereum/go-ethereum#15048]
I'm trying to run a geth instance with Swift but seeing this issue -- does anyone know what the problem could be?

![screen shot 2017-08-27 at 11 45 26 am](https://user-images.githubusercontent.com/3993332/29751573-4f9bd044-8b1d-11e7-8f32-9591e996e4f8.png)

Thanks!

**Comment by jaramburu** [comment]
@claykohut did you ever find a solution to this?
