### ISSUE TITLE
GetTransactionReceipt return null after a while

### ISSUE THREAD

**Issue by Karimai** [ethereum/go-ethereum#15043]
#### System information

Geth version: `geth 1.6.5-stable-cf87713d`
OS & Version: Windows 
Commit hash : (if `develop`)

#### Expected behaviour

we use the following code in MineAndGetReceiptAsync without start or stop mining. 

```
public static async Task<TransactionReceipt> MineAndGetReceiptAsync(string transactionHash)
{
            var receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(transactionHash);
	while (receipt == null)
	{
		Thread.Sleep(4000);
		receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(transactionHash);
	}

       return receipt;
}
```
it is work fine for small number of contracts. If the number of contracts increase, the GetTransactionReceipt return null after a some minutes of starting the program. When I check the number of opened sockets I see there are more than 10000 TIME_AWAIT half opened socked by port 8545. I don't know how can I revise and debug it. I have tried a lot to increase the time, but nothing changed and I got stuck in the same situation sooner or later.

**Comment by bas-vk** [comment]
The number of (deployed?) contracts should have no relation with receipts suddenly missing. It should like something is overwhelmed within the system if you put load on it.

Is `web3` a .NET library?

To test if this is a problem within geth or your code base you could open a console by attaching to geth and try to retrieve the receipt from the console.

```
geth attach [optional endpoint]
> eth.getTransactionReceipt('<your tx hash>')
```

If that returns the receipt than there is something wrong in your code. If you got null the transaction might not be processed. Try to retrieve it with `eth.getTransaction('<your tx hash>')`. If that returns the transaction than and block number/hash are null it means that it is not processed. There can be several reasons for it, e.g. transaction is queued. If the result contains a block number and hash and `eth.getTransactionReceipt` is still not giving the receipt than there might be something wrong inside geth.
