### ISSUE TITLE
runtime: garbage collector found invalid heap pointer

### ISSUE THREAD

**Issue by keo** [ethereum/go-ethereum#1504]
A few days ago geth died with "runtime: garbage collector found invalid heap pointer"

Here's the log: https://gist.github.com/keo/9c9405baf8fe75d793f6

**Comment by karalabe** [comment]
What system are you running on? Specifically, OS, kernel, Go version, 32/64 bit, etc. There was a bug at a certain point in the Go runtime/GC, might be good to figure out if it's the same issue or not.

**Comment by keo** [comment]
Here's the system info:

OS: Ubuntu 14.04.2
Kernel: Linux ethnode 3.13.0-52-generic #85-Ubuntu SMP Wed Apr 29 16:44:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
golang: 2:1.4.2+3trusty-0ubuntu1

**Comment by karalabe** [comment]
I am betting it is the same bug. [Some GC fixes](https://github.com/golang/go/commit/6d1ebeb5271a06cd55f55a84e95709e2f4805bcc) regarding this have been done after Go 1.4.2, but as far as I know they will only land in Go 1.5. Also not sure if they only affect 32 bit or 64 bit systems too.

I will leave this issue open for now, but I don't think there's much we can do here other than wait for Go 1.5 and hope it won't occur again. Given that you're the first to report it, maybe it's really just that rare. Please do send in further crash dumps to this thread if you see.

**Comment by karalabe** [comment]
We've pushes a small race fix into geth 1-2 days ago. That could have been the cause for the invalid pointer issue. Could yo upull the latest develop and run that and see if this issue crops up again? Thanks :)

**Comment by karalabe** [comment]
I take it that the issue was fixed :) Please reopen if not.
