### ISSUE TITLE
getBalance always 0

### ISSUE THREAD

**Issue by nodevar** [ethereum/go-ethereum#15055]
#### System information

Geth version: `Geth/v1.7.0-unstable/linux-amd64/go1.8.3`
OS & Version: OSX, latest docker

So i cant check balance of any wallets via the console or any other api. I Think i miss something here but cant figure out what it is. I Think somehow the chain is not in sync..

i start geth with the --light option, do i need --fast? Since this is taking forever to sync, can somebody confirm?

> web3.fromWei(web3.eth.getBalance('0xb794f5ea0ba39494ce839613fffba74279579268'),'ether').toString(10)
"0"
> 
Etherscan shows that there should be a balance: https://etherscan.io/address/0xb794f5ea0ba39494ce839613fffba74279579268 

Eth.syncing reports false, what i think means we are in Sync:
> eth.syncing
false
>
Block Number returns 0:
> eth.blockNumber
0
The Last block returns 0:
> web3.eth.getBlock(web3.eth.blockNumber)
{
  difficulty: 17179869184,
  extraData: "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
  gasLimit: 5000,
  gasUsed: 0,
  hash: "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000042",
  number: 0,
  parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 540,
  stateRoot: "0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544",
  timestamp: 0,
  totalDifficulty: 17179869184,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
>

**Comment by nodevar** [comment]
This can be closed. This is gone after starting with --fast.

**Comment by Devqon** [comment]
But why isn't it working with `--light`? I don't want to sync a node, can this work with the `--light` flag?
