### ISSUE TITLE
Question: What is the 0x4 recipient of a call?

### ISSUE THREAD

**Issue by enriquefynn** [ethereum/go-ethereum#15056]
Since this is a question I omitted the specs part.
I'm logging the Call function in core/vm/evm.go at this point [evm.go#L179](https://github.com/ethereum/go-ethereum/blob/master/core/vm/evm.go#L179)
I get multiple addresses sending to 0000000000000000000000000000000000000004.
I couldn't find this documented anywhere as a feature.

For example in block 101368, there were 2 transactions from 6b211fdc0d944a84bba8534d631fad9262ba80b8, to 0000000000000000000000000000000000000004
But in https://etherscan.io I see conflicting data for this address. 

An excerpt of the log is here: https://pastebin.com/jiWDh8rW
Is formatted as block, from, to, amount.
Thanks

**Comment by holiman** [comment]
The address `0000000000000000000000000000000000000004` is a 'precompile' called `identity` - it sends back whatever you sent into it. Historically, solidity used it as a way to copy data from one segment of memory to another, but afaik it's not used (that way) any more. 

See the [Yellow paper](http://gavwood.com/Paper.pdf) for more info about precompiles.
