### ISSUE TITLE
OSX Mist sync

### ISSUE THREAD

**Issue by mkc73** [ethereum/go-ethereum#15059]
New to EThereum.

MIST hangs on syncing. Seems to be a common problem,especially over the last week with no official responses. I can see downloading blocks for a blockchain, but what exactly is the blockchain structure and why does it grow whilst downloading (at about the same rate as it is downloaded) ?
After staring at the counters for four days I thought it would be nice to know.

**Comment by bas-vk** [comment]
Could you post a screenshot of the synchronisation window and post the mist version that you are using?

**Comment by alfkors** [comment]
@bas-vk apparently multiple versions of geth on different OS's have been affected by this issue for several months now. See #14571 #14647

**Comment by tjerkw** [comment]
Is the blockchain grower quicker than people can download it? I though dowloading the blockchain using --fast would actually be fast.

**Comment by alfkors** [comment]
@tjerkw No. The issues I linked describe the behavior in great detail.

**Comment by karalabe** [comment]
It's downloading the state trie. Its size is not known in advance, since it's a big tree, which is expanded as you go along. Last time I synced it was 17M nodes large. I'll try a resync in a few hours to see where it's at now.

**Comment by mkc73** [comment]
Many thanks. Searches for blockchain structure gave no info. State trie gives eg:
https://ethereum.stackexchange.com/questions/15317/how-ethereum-transaction-tree-is-formed
