### ISSUE TITLE
geth crashes with signal SIGBUS: bus error code=0x2

### ISSUE THREAD

**Issue by SinghalB** [ethereum/go-ethereum#15051]
#### System information

Geth version: `geth version`
Geth
Version: 1.7.0-unstable
Git Commit: ebf41d16a04420a3eba082cc0a1783c93caa1f86
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.8

OS & Version: Ubuntu 14.04.5 LTS (Linux Kernel: 4.4.0-42-generic)

#### Expected behaviour
Should just work.

#### Actual behaviour
unexpected fault address 0x7f10dab0e000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f10dab0e000 pc=0x46109b]

#### Steps to reproduce the behaviour
./build/bin/geth --datadir "/dev/shm/data1" --ethash.dagdir "/dev/shm/ethash" init /root/privGenesis.json
./build/bin/geth --datadir "/dev/shm/data1" --ethash.dagdir "/dev/shm/ethash"  --rpc console
> personal.newAccount()
> personal.unlockAccount(eth.accounts[0])
> miner.start()
INFO [08-28|12:07:14] Generating DAG in progress               epoch=1 percentage=91 elapsed=2m15.065s
unexpected fault address 0x7f10dab0e000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f10dab0e000 pc=0x46109b]

#### Backtrace

````
goroutine 405 [running]:
runtime.throw(0xf48d1b, 0x5)
        /usr/lib/go-1.8/src/runtime/panic.go:596 +0x95 fp=0xc424507e48 sp=0xc424507e28
runtime.sigpanic()
        /usr/lib/go-1.8/src/runtime/signal_unix.go:287 +0xf4 fp=0xc424507e98 sp=0xc424507e48
runtime.memmove(0x7f10dab0dfc8, 0xc4266d3b40, 0x40)
        /usr/lib/go-1.8/src/runtime/memmove_amd64.s:191 +0x67b fp=0xc424507ea0 sp=0xc424507e98
github.com/ethereum/go-ethereum/consensus/ethash.generateDataset.func2(0xc421888080, 0x407fff80, 0x4, 0xc428324000, 0x407f30, 0x407f30, 0x0, 0x7f10ab800008, 0x407fff80, 0x407fff80, ...)
        /root/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:275 +0x1f4 fp=0xc424507f58 sp=0xc424507ea0
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc424507f60 sp=0xc424507f58
created by github.com/ethereum/go-ethereum/consensus/ethash.generateDataset
        /root/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:281 +0x3ad

````

**Comment by holiman** [comment]
So, the `/dev/shm` is a memory-backed virtual folder? How much did you allocate for it when you mounted it? 

I tried your example (without using `/dev/shm`), it the `ethash.dagdir` quickly filled `1.8G`.

**Comment by SinghalB** [comment]
@holiman 

Yes, around `2GB` was allocated for `/dev/shm` and ethhash.dagdir took up all of the space.
I re-tried with `4GB` `/dev/shm` and it worked fine.

Thanks a lot, closing the issue!

**Comment by Jacodelange** [comment]
I still have this issue, my folder is not a memory-backed virtual folder. Just a normal folder I created in the home directory, there is still 50gb available. After a while it still crashes even after creating a swap area as other people suggested

**Comment by NIVJAIN** [comment]
I have the same issue on private eth network, mine a normal folder as well and no swap. around 19 gig still available.

**Comment by bigfoot31** [comment]
for future visitors, check if memory as well as file storage is totally used up.
