### ISSUE TITLE
Why can't receipt.poststate make up for the failure of [out of gas]

### ISSUE THREAD

**Issue by mi2zha** [ethereum/go-ethereum#15052]
#### System information

Geth version: `1.7.0-unstable`
OS & Version: OSX
Commit hash : (if `develop`)

How do I get out of gas？

Eth_getTransactionReceipt is not available or missing

thank u

**Comment by holiman** [comment]
This is a bit vague. Are you getting a message saying that the RPC-method is missing? Could you provide some logs about how you invoke it and what you're seeing?

**Comment by bas-vk** [comment]
It is `eth_getTransactionReceipt`. E.g.:
```
echo '{"id": 1, "jsonrpc": "2.0", "method": "eth_getTransactionReceipt", "params": ["0x123e5dba54c4b5b2de220d9cf199f2639f7e768c4e7829fdff0b8d015703242f"]}' | nc -U ~/.ethereum/geth.ipc
```

If you had the name correct (start with lower case) ensure that you don't start geth with a set of custom RPC modules enabled and forgot to enable the `eth` module.

Second, are you interested in out of gas or if a transaction was successful executed?

**Comment by mi2zha** [comment]
sorry，I didn't make it clear

Does the result of eth_getTransactionReceipt fail to return tx failure or successful status?

**Comment by fjl** [comment]
Transaction status will be added in the upcoming Byzantium hard fork. It's described in ethereum/EIPs#658, which is implemented on go-ethereum but not acirve yet.
