### ISSUE TITLE
sync slow after geth new account

### ISSUE THREAD

**Issue by ecservice** [ethereum/go-ethereum#15057]
#### System information

Geth version: `1.6.7
OS & Version: Windows 10 Pro
Fiber 1G connection (1000M)
Commit hash : (if `develop`)

#### Expected behaviour
after command geth new account
The sync was fast
After 30 gb of data download has become very slow
Eth.syncing show
currentBlock: 4028057,
  highestBlock: 4212721,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 4008950
But it now updates the blocks very slowly
Which are the normal times for synchronization
my connection is from 1000M

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
Your connection is probably not the choke-point. After you made an initial fast-sync (to block `4008950`), it will later switch to block-by-block import, basically acting like a full-sync after `4008950`. So it's expected to be slower at that point. 

And for next time, please provide some data/logs about the import process, so it's possible to see if what you're experiencing as 'slow' is within the expected bounds, or if it's actually some bug here.
