### ISSUE TITLE
data loss: windows geth compilation instructions in wiki

### ISSUE THREAD

**Issue by slate0** [ethereum/go-ethereum#15050]
#### System information

Geth version: NA
OS & Version: Windows 10 64-bit
Commit hash : NA

In the "Installation instructions for Windows" Wiki page located at: https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows

There is a line of instructions with the following setx command:
C:\Users\xxx> setx Path "%Path%"

On my system, this resulted in the following warning message: 
WARNING: The data being saved is truncated to 1024 characters.

Upon checking my Environment variables using the Windows GUI and the registry, as well as by typing "path" at the command prompt, I can see that the path does indeed appear to be truncated as it ends in the middle of a directory name.

This web site shows a solution to recovering from this problem: 
https://superuser.com/questions/812754/how-to-recover-from-path-being-truncated-to-1024-characters-by-setx

Needless to say, this kind of data loss could mess up a system if the user is not paying attention.

There may be a switch for setx to get around the 1024 limitation, I will get back here if I find a solution.

In the meantime, I believe the instructions should note this to prevent damage.

**Comment by holiman** [comment]
Thanks, I've updated the wiki: https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows  .
