### ISSUE TITLE
Faucet problem 

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#15064]
I am having a problem with the faucet again. But the error is a bit different so I am not reopening the old issue (https://github.com/ethereum/go-ethereum/issues/15044) -  but creating a new one. 
You do not see an error in the webpage - it just does not work. But when opening the browser-console you see this:

```
recaptcha__de.js:379 Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at submit (https://faucet.rinkeby.io/:101:12)
    at ar.n.Ae (https://www.gstatic.com/recaptcha/api2/r20170829114530/recaptcha__de.js:379:453)
    at Jn.<anonymous> (https://www.gstatic.com/recaptcha/api2/r20170829114530/recaptcha__de.js:207:358)
    at Qe (https://www.gstatic.com/recaptcha/api2/r20170829114530/recaptcha__de.js:44:263)
    at Me (https://www.gstatic.com/recaptcha/api2/r20170829114530/recaptcha__de.js:45:209)
    at https://www.gstatic.com/recaptcha/api2/r20170829114530/recaptcha__de.js:42:196

```
Perhaps this is also the error the other users that commented in https://github.com/ethereum/go-ethereum/issues/15044 had ..

PS:  currently I am in a bit restricted event-wifi (also seeing SSH does not work from here) - perhaps this is the reason for the problem. But I think at least the error should surface to users.
EDIT: after using another wifi (tethering via phone) it worked - so it might have been the restricted wifi - but still think a error message surfacing to the users would be great.

**Comment by dwking2000** [comment]
I had issues with the faucet working using Chrome. I finally got it to work when I noticed that Chome was blocking 'unsafe scripts' without much warning - I did not get any obvious alert, just a little icon in the URL field next to the favorite icon. If you see this in Chrome, click to unblock and let the 'unsafe script' run (assuming you are all right with that). I'm guessing the unsafe script has something to do with the Re-Captcha and Chrome security settings.

**Comment by rico345100** [comment]
SAME HERE

**Comment by Ramarti** [comment]
<img width="565" alt="captura de pantalla 2018-10-04 a las 10 56 01" src="https://user-images.githubusercontent.com/2632384/46463555-6b267500-c7c4-11e8-8e90-813e481d87e8.png">

**Comment by karalabe** [comment]
Closing this, faucet errors are usually light client issues since we're always running latest master on it to dog-food. We're fixing as soon as they occur.
