### ISSUE TITLE
Blocks contain most of transactions that were not present in the mempool

### ISSUE THREAD

**Issue by LogvinovLeon** [ethereum/go-ethereum#15074]
#### System information

Geth
Version: 1.6.0-unstable
Git Commit: f3579f6460ed90a29cca77ffcbcd8047427b686b
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.8/libexec
#### Expected behaviour
Current block time is around 20s and network propagation time is ~2 seconds.
I have a good internet connectivity, so I'll expect, that my mempool will contain ~90% of transactions seen in the blocks, that arrive.
I'm also watching for pending events.

#### Actual behaviour
After running the tests I received:
Transactions: 174
Transactions that were in the mempool before: 16
Pending events: 12

#### Steps to reproduce the behaviour
I created a repro branch: https://github.com/0xProject/0x.js/tree/geth-repro
If you go, install the deps, run geth locally and run the tests it'll start watching and print the debug output with stats.

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Could you please run with latest master? There have been a lot of modifications in the transaction pool over the last months.

**Comment by LogvinovLeon** [comment]
I was running geth node on my local machine. When I tried deploying geth under a static IP adress - it solved the issue.
