### ISSUE TITLE
miner.start(1) hangs forever

### ISSUE THREAD

**Issue by MtGParley** [ethereum/go-ethereum#15087]
#### System information

Geth version: `1.6.7`
OS & Version: /OSX
Commit hash : (if `develop`)

#### Expected behaviour
To say that its mining and for eth.blockNumber to increase

#### Actual behaviour
Mining does not increase blockNumber

#### Steps to reproduce the behaviour

I have two MacBooks and I get the exact same behavior on both of them. 
Create genesis file: 
{
    "config": {
        "chainId": 15,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "difficulty": "20",
    "gasLimit": "2100000",
    "alloc": {
        "7df9a875a174b3bc565e6424a0050ebc1b2d1d82": { "balance": "300000" },
        "f41c74c9ae680c1aa78f42e5647a62f353b7bdde": { "balance": "400000" }
    }
}

geth --datadir "/Users/myName/mydir" init "/Users/myName/ethereum/genesis.json"
geth --datadir "/Users/myName/mydir" --networkid 15 console

personal.newAccount()
... wait for DAG to generate
miner.start(1)
eth.mining is true
mining does not occur
admin.nodeInfo shows:
{
  enode: "enode://a73e5db95c1710a6f2fcc9f55c3b738b03b223087573052a8ea5edb951a957460cd29ef9d2bc7dc8ba0e399adae11bc40cc397eca8e1b1c6b6aee9ca735a878d@[::]:30303",
  id: "a73e5db95c1710a6f2fcc9f55c3b738b03b223087573052a8ea5edb951a957460cd29ef9d2bc7dc8ba0e399adae11bc40cc397eca8e1b1c6b6aee9ca735a878d",
  ip: "::",
  listenAddr: "[::]:30303",
  name: "Geth/v1.6.7-stable-ab5646c5/darwin-amd64/go1.9",
  ports: {
    discovery: 30303,
    listener: 30303
  },
  protocols: {
    eth: {
      difficulty: 17179869184,
      genesis: "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
      head: "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
      network: 15
    }
  }
}

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Could you please post your genesis block here?

`eth.getBlock(0)`

**Comment by nkbai** [comment]
may be geth is generating dag data

**Comment by MtGParley** [comment]
It seems to fully generate two DAGs. Takes 5 min each, but i still cant mine. Ive tried deleting the dags and genesis folder several times, but no luck

**Comment by MtGParley** [comment]
> eth.getBlock(0)
{
  difficulty: 17179869184,
  extraData: "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
  gasLimit: 5000,
  gasUsed: 0,
  hash: "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000042",
  number: 0,
  parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 540,
  stateRoot: "0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544",
  timestamp: 0,
  totalDifficulty: 17179869184,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}

**Comment by karalabe** [comment]
@MtGParley This is the genesis block of the mainnet https://etherscan.io/block/0. That would explain why you can't mine on it, since it's very hard from the get go.

**Comment by karalabe** [comment]
My best guess at this point is that you already had mainnet initialized in your datadir. Then when you did `geth --datadir "/Users/myName/mydir" init "/Users/myName/ethereum/genesis.json"`, it displayed an error about the conflict and that it refused to overwrite the old chain. You probably silently ignored this error and kept using the mainnet chain nonetheless.
