### ISSUE TITLE
UPnP can allocate public 30303 port to only 1 ethereum node

### ISSUE THREAD

**Issue by redmouth** [ethereum/go-ethereum#15082]
If there are multiple ethereum nodes behind same NAT,  the NAT's UPnP services can only allocate 30303 port to one node.   What NAT traversal protocol do other nodes use?

#### System information
Geth version: 1.6.7
OS & Version: Ubuntu 16.04

**Comment by RichHorrocks** [comment]
Hi there. Ideally ask technical questions on https://ethereum.stackexchange.com - as far as possible it's important to keep issue-trackers clear and for real issues only.
