### ISSUE TITLE
Error: missing trie node

### ISSUE THREAD

**Issue by mi2zha** [ethereum/go-ethereum#15088]
#### System information

Geth version: `1.7.0-unstable`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour
debug.traceTransaction("0x1c884fc6013349ce8572778f25220a4799d0bc5b4bc7df24791dc5df27c7a2f0")
{
  failed: false,
  gas: 21000,
  returnValue: "",
  structLogs: []
}
#### Actual behaviour
debug.traceTransaction("0x1c884fc6013349ce8572778f25220a4799d0bc5b4bc7df24791dc5df27c7a2f0")
Error: missing trie node 7ccfa92e987117524e8026c86d3af46c13b365adf0810876198277e1cf94af3c (path )
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
You can only trace blocks that you have the state for. If you fast synced recently, this transaction is probably too old to trace locally without an archive node.

**Comment by mi2zha** [comment]
oh,thank u
how do you archive all nodes, I'm not using fast sync

**Comment by karalabe** [comment]
Geth by default uses fast sync. You can run with `--synmode=full`, but it will produce a gigantic database and will take many days to crunch through every block.

**Comment by mi2zha** [comment]
thank you very much

**Comment by dmenin** [comment]
@karalabe simply starting geth with `syncmode=full` didnt work for me.
Do I have to sync from the start? (I.e. delete all the data and start again?)

thanks

**Comment by AyushyaChitransh** [comment]
I faced this error even after I used `geth --synmode=full`. Geth version v1.8.10 What could be possible cause for this? Is there any way for me to resolve this?

**Comment by KursLabIgor** [comment]
Guys.  Same for syncmode="full" gcmode="archive" 
debug.traceBlockByNumber("0x1000")
[]
why ?

**Comment by yinchonging** [comment]
Same for me syncmode="full" gcmode="archive"
why ?
why ?
why ?
