### ISSUE TITLE
How to make a "fork" chain of mainnet of ethereum?

### ISSUE THREAD

**Issue by sakamoto1255** [ethereum/go-ethereum#15080]
Hi.
I would like to know how to make a fork chain of ethereum network.
First, I won't use an snapshot of ether mainnet.
I would just know the code of 
1. The code that includes ethereum mainnet&testnet chain id&port
2. The code that includes ethereum chain's data dir(where it saves ethereum blockchain)
3. and the api of ethereum mainnet

Also I would like to know "What ethereum's network id do"

Thanks

**Comment by bas-vk** [comment]
If you don't want to use a snapshot and keep current properties than there is no reason to create a fork. Just start a [private network](https://github.com/ethereum/go-ethereum/wiki/Private-network).

1. They are scattered in the code base, the `params` and `cmd/utils` package are good places to start.
2. `ethdb` package, but you can change the default location with the `--datadir` flag.
3. most of it is in `internal/ethapi`

> Also I would like to know "What ethereum's network id do"

Clients only connect to each other when they talk the same protocol version and network id.
