### ISSUE TITLE
backend: simulatedbackend panics on out of gas

### ISSUE THREAD

**Issue by GoldenDave** [ethereum/go-ethereum#15099]
#### System information

Geth version: `1.7.0-unstable-d70536b5`
OS & Version: OSX
Commit hash : `d70536b5` 

#### Expected behaviour
Using Simulated Backend - should return an error

#### Actual behaviour
Using Simulated Backend - a transaction that runs out of gas causes a panic

#### Steps to reproduce the behaviour
Send transaction designed to run out of gas - can give access to gitlab repo if needed

#### Backtrace

````
[backtrace]
````

**Comment by bas-vk** [comment]
This is by design. `SimulatedBackend` will panic when an invalid transaction is passed where invalid also means could not be executed.

**Comment by GoldenDave** [comment]
So a command that throws an exception is ok but out of gas is not?

**Comment by bas-vk** [comment]
It is designed for unit testing contracts. It receives valid transactions and after executing the state is checked to see if the contract worked as intended. If you explain your use case maybe the are other solutions.
