### ISSUE TITLE
Ethereum Wallet " Downloading Chain structure " 

### ISSUE THREAD

**Issue by xSadik** [ethereum/go-ethereum#15093]
#### System information

Geth version: `geth version` 1.6.7
OS & Version: Windows/Linux/OSX  //// Windows 10 64 bits

Keeps downloading chain structure now its at 
Downloading block 4,240,544 of 4,240,700, 
Downloading Chain structure 11,040,000 of 11,059,120

I need help

**Comment by karalabe** [comment]
Mist's UI is misleading. Not "downloading K of N". rather it should be "downloading K of currently known minimum N". The node does not know in advance how many trie nodes it needs to pull. It's around 20M currently btw.
