### ISSUE TITLE
eth.resend returns: "Error: Transaction not found

### ISSUE THREAD

**Issue by skulstadv** [ethereum/go-ethereum#15096]
#### System information

Geth version: Version: 1.6.7-stable
OS & Version:Ubuntu 16.04.3 , 4.10.0-33-generic

#### Expected behaviour

Trying to resend the first txn in pending transactions with the following code:
eth.resend(eth.pendingTransactions[0], web3.toWei(30, 'gwei'))

This has worked flawlessly until today. Network is really crammed, might be a contributing reason?
The pending txns list doesnt work properly either, but even when it returns the correct pending txns it doesn't work to resend the txn.

#### Actual behaviour

Error: Transaction "some random hash" not found
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1

The "some random hash" in the error is not the same as the txn in pendingTransactions[0]. It is not found in the mempool nor previous blocks; To clarify, it returns "Error: Transaction x not found", where x is some hash. This hash remains the same after restarts of geth.

#### Steps to reproduce the behaviour

Resend a pending txn **WITH DATA**

Seems to be related to problem described here:
https://ethereum.stackexchange.com/questions/16269/geth-transactions-stuck-in-pending-resend-fails

**Comment by bas-vk** [comment]
> The pending txns list doesnt work properly either

Could you explain what the problem is?

**Comment by skulstadv** [comment]
Calling eth.pendingTransactions after sending a txn will return the txn. Sometimes (and this seems correlated to high ethereum network load / high amount of pending txns) no txns is returned even though they were sent very recently. They will maybe show up again in 5 minutes, but this behaviour is very inconsistent in my experience.

**Comment by bas-vk** [comment]
Your analysis is correct. This is unfortunately a relic from the RPC interface. Transactions that are send to the node use the `data` field. Responses use the `input` field. I will add this to the rpc docs.

But it doesn't explain why it worked previously.

**Comment by skulstadv** [comment]
> But it doesn't explain why it worked previously.

My issue description was misleading. It seems I only used resend with transactions containing no data earlier, that's why it worked. So the error was on my part.
