### ISSUE TITLE
Segmentation fault in hid on OSX

### ISSUE THREAD

**Issue by adisbladis** [ethereum/go-ethereum#15100]
#### System information

Geth version: 1.6.7
OS & Version: OSX

#### Steps to reproduce the behaviour
Built from source with nix (nix-shell -p go-ethereum against nixpkgs master), tried to run `geth -h`

#### Backtrace (including dtrace)
https://gist.github.com/adisbladis/2327dce7963e0092437267fcdee51f6b

**Comment by karalabe** [comment]
Could you try with master please? There have been some fixes with regard to OSX usb enumerations.

**Comment by adisbladis** [comment]
@karalabe Tried building from master (latest commit https://github.com/ethereum/go-ethereum/commit/c4d21bc8e548d909d5b2940cb00d3d068f5697ec) and got the same results: https://gist.github.com/adisbladis/8534f3a59835db39925ab73724a2ea2a

**Comment by adisbladis** [comment]
This problem comes from running the build in a sandbox and the build not being able to find `IOKit` and `libobjc`.

**Comment by hepengfei** [comment]
Crash on MacOS with go 1.11.1, the same problem.
When using --nousb, it will be OK.
So  there are still a problem at here.

---

SIGILL: illegal instruction
PC=0x7fff4a287a52 m=12 sigcode=1

goroutine 0 [idle]:
runtime: unknown pc 0x7fff4a287a52
stack: frame={sp:0x70000ed8c690, fp:0x0} stack=[0x70000ed0d2b0,0x70000ed8ceb0)
000070000ed8c590:  00007fff749b19b0  0000000006409090
000070000ed8c5a0:  000070000ed8c5c0  00007fff748cbce7
000070000ed8c5b0:  0000000000000000  0000000000000000
000070000ed8c5c0:  000070000ed8c660  00007fff748cc246
000070000ed8c5d0:  000070000ed8c608  000000001f08000c
000070000ed8c5e0:  fffffffffffffffb  0000000000000000
000070000ed8c5f0:  0000000000000000  00007fff749b19b0
000070000ed8c600:  0000000000000000  0000000000000000
000070000ed8c610:  0000000000000000  0000000000000000
000070000ed8c620:  0000000000000000  0000000000000000
000070000ed8c630:  0000000000000000  0000000000000000
000070000ed8c640:  0000000000000000  0000000000000000
000070000ed8c650:  000000000650ab50  0000000000000000
000070000ed8c660:  000070000ed8c680  00007fff7493d6bb
000070000ed8c670:  000000000650ab50  0000000000000000
000070000ed8c680:  000070000ed8c6b0  00007fff4a287a52
000070000ed8c690: <ffffffffff810f80  0000000006409090
000070000ed8c6a0:  0000000000000000  000000000000010f
000070000ed8c6b0:  000070000ed8c700  00007fff47951796
000070000ed8c6c0:  9cb086869c7000bb  00000000057da7a0
000070000ed8c6d0:  ffffffffffffffff  0000000006403e00
000070000ed8c6e0:  00000000a7baadb1  0000000000000007
000070000ed8c6f0:  0000000000000000  0000000006408c80
000070000ed8c700:  000070000ed8c760  00007fff4781f494
000070000ed8c710:  00007fff9f4018e0  0000000006403df0
000070000ed8c720:  0000000000000000  0000000000000000
000070000ed8c730:  0000000000000000  0000000006400ca0
000070000ed8c740:  0000000000000001  000000c000194b40
000070000ed8c750:  000000c00045a000  0000000000000000
000070000ed8c760:  000070000ed8c7a0  00007fff4a28cf4c
000070000ed8c770:  0000000000000000  00007fff9f449fa8
000070000ed8c780:  0000000000000001  000000c000194b40
runtime: unknown pc 0x7fff4a287a52
stack: frame={sp:0x70000ed8c690, fp:0x0} stack=[0x70000ed0d2b0,0x70000ed8ceb0)
000070000ed8c590:  00007fff749b19b0  0000000006409090
000070000ed8c5a0:  000070000ed8c5c0  00007fff748cbce7
000070000ed8c5b0:  0000000000000000  0000000000000000
000070000ed8c5c0:  000070000ed8c660  00007fff748cc246
000070000ed8c5d0:  000070000ed8c608  000000001f08000c
000070000ed8c5e0:  fffffffffffffffb  0000000000000000
000070000ed8c5f0:  0000000000000000  00007fff749b19b0
000070000ed8c600:  0000000000000000  0000000000000000
000070000ed8c610:  0000000000000000  0000000000000000
000070000ed8c620:  0000000000000000  0000000000000000
000070000ed8c630:  0000000000000000  0000000000000000
000070000ed8c640:  0000000000000000  0000000000000000
000070000ed8c650:  000000000650ab50  0000000000000000
000070000ed8c660:  000070000ed8c680  00007fff7493d6bb
000070000ed8c670:  000000000650ab50  0000000000000000
000070000ed8c680:  000070000ed8c6b0  00007fff4a287a52
000070000ed8c690: <ffffffffff810f80  0000000006409090
000070000ed8c6a0:  0000000000000000  000000000000010f
000070000ed8c6b0:  000070000ed8c700  00007fff47951796
000070000ed8c6c0:  9cb086869c7000bb  00000000057da7a0
000070000ed8c6d0:  ffffffffffffffff  0000000006403e00
000070000ed8c6e0:  00000000a7baadb1  0000000000000007
000070000ed8c6f0:  0000000000000000  0000000006408c80
000070000ed8c700:  000070000ed8c760  00007fff4781f494
000070000ed8c710:  00007fff9f4018e0  0000000006403df0
000070000ed8c720:  0000000000000000  0000000000000000
000070000ed8c730:  0000000000000000  0000000006400ca0
000070000ed8c740:  0000000000000001  000000c000194b40
000070000ed8c750:  000000c00045a000  0000000000000000
000070000ed8c760:  000070000ed8c7a0  00007fff4a28cf4c
000070000ed8c770:  0000000000000000  00007fff9f449fa8
000070000ed8c780:  0000000000000001  000000c000194b40

goroutine 54 [syscall]:
runtime.cgocall(0x49d3ea0, 0xc000459bb0, 0x77c8600)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/cgocall.go:128 +0x5e fp=0xc000459b78 sp=0xc000459b40 pc=0x40049de
vendor/github.com/karalabe/hid._Cfunc_hid_enumerate(0xc000002c97, 0x0)
	_cgo_gotypes.go:250 +0x4e fp=0xc000459bb0 sp=0xc000459b78 pc=0x45904ce
vendor/github.com/karalabe/hid.Enumerate(0xc000002c97, 0x0, 0x0, 0x0)
	vendor/github.com/karalabe/hid/hid_enabled.go:70 +0x64 fp=0xc000459c90 sp=0xc000459bb0 pc=0x4590a44
github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).refreshWallets(0xc0001dca00)
	github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:138 +0xcf fp=0xc000459fb0 sp=0xc000459c90 pc=0x45c9f3f
github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).updater(0xc0001dca00)
	github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:227 +0x4c fp=0xc000459fd8 sp=0xc000459fb0 pc=0x45cb5ac
runtime.goexit()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000459fe0 sp=0xc000459fd8 pc=0x405e581
created by github.com/ethereum/go-ethereum/accounts/usbwallet.(*Hub).Subscribe
	github.com/ethereum/go-ethereum/accounts/usbwallet/hub.go:213 +0x123

**Comment by fjl** [comment]
@adisbladis Sorry, it's been a while since you have reported this issue. Did you see this issue while **running** geth in the nix sandbox or just when **built** in the sandbox and then running it outside of it?

**Comment by fjl** [comment]
Related issues in hidapi:

* https://github.com/signal11/hidapi/issues/205
* https://github.com/signal11/hidapi/issues/337

**Comment by adisbladis** [comment]
@fjl While running (outside the sandbox).

**Comment by adisbladis** [comment]
Fyi this is the applied fix for the nix package: https://github.com/nixos/nixpkgs/commit/ec331755d349494b543fcedca01951ac60994bbf#diff-cea64a6ad3360f7afc6c798acdfcb00fR26

**Comment by adamschmideg** [comment]
It's fixed on the NixOS side

**Comment by adisbladis** [comment]
@adamschmideg To be clear this was never really an issue on the Nix side of things. 
Iirc the problem is some insufficient runtime checks in https://github.com/karalabe/hid.
