### ISSUE TITLE
the change this morning

### ISSUE THREAD

**Issue by jackpot1136** [ethereum/go-ethereum#15116]
#### System information
I AM THE REASON THEY CHANGED EVERYTHING UP THIS MORNING.You are completely right about any work should be rewarded because for rhe simple reason like your friend I don't know too much about computers or mining, but I'm learning. Two days ago I finally figured out a how to mine better through getting my miner to focus on the important things where he's more efficient. I understand that their ass is hurting because of the 31 million that they lost on sunday noon, but that doesn't give them the right to strip me of all of my hardworked earnings. Because the stole from me of all of my hard earned money this morning and I havent even figured out how to transfer into my wallet yet.  Ive been up day and night working and teaching myself about coputers mining and everything that goes along with it so that I can provide for my family. And these moterfuckers wanna hack into my computer and strip me of months of hard work besause two days ago a few of my sections of mining for that day didn't equal up. Now because of me talking shit this morning doesn't mean they have the right to STEAL my proof of work.I understand about taking those sections from two days ago,out but to strip me of everything is bullshit. It is because of us (people mining)why they are growing for them to turn on us like we're the bad guys and rob us for everything is bullshit. I'm talking abouth Geth and the wonderful staff for niche\hash Miner Legacy, and Etherbase. I want my hard earned money back mother fuckers. I understand am ok with you taking part of it out from two days ago but the rest of it is proof of hard earned work and i deserve to get paid for it. YOU GUYS ARE NO BETTER THAN THE guy/girl that GOT THAT 31 MILLION ON SUNDAY. I WANT MY MONEY BACK.
Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by fjl** [comment]
We cannot help you with this issue. This issue tracker is for software issues with geth.
