### ISSUE TITLE
Windows 10 - PATH error

### ISSUE THREAD

**Issue by banasiakadam60** [ethereum/go-ethereum#15118]
#### System information

Geth version: `1.6.5-cf87713d`
OS & Version: Windows 10

#### Expected behaviour
During installation `geth` location should be added to the `PATH`

#### Actual behaviour
It fails with error: `AddToPath: original length 117 > 1024` (or simmilar)
But can be added manually

#### Steps to reproduce the behaviour
Try to install geth on Windows 10 with many entries in `PATH`

#### Backtrace

https://user-images.githubusercontent.com/1128665/29494875-5af5264e-8568-11e7-84cb-65b3dfd0ba0c.jpg

**Comment by bas-vk** [comment]
That is a known limitation of NSIS. This check was added because in the past we had problems where the installer would corrupt the existing PATH. Will check if there is a solution.

**Comment by freakabcd** [comment]
Default NSIS_MAX_STRLEN is 1024. You'll need to build it yourself with a higher limit or use an existing special build with 8192 as the limit from here [NSIS Special Builds](http://nsis.sourceforge.net/Special_Builds)

**Comment by MarinAngelo** [comment]
OK, but as I am definitely not able to fix this by my self, what is the effect? Does this mean that geth does not work correctely?

**Comment by fjl** [comment]
It just means that the geth installation directory is not listed in PATH. You might care about this if you expect to be able to open cmd.exe and type `geth`. If geth is not in PATH, you would need to type the full path to the installation or add it to PATH yourself.

**Comment by MarinAngelo** [comment]
OK, thanks!

**Comment by 1095080020** [comment]
interesting
