### ISSUE TITLE
Ledger Nano S account not showing in `account list`

### ISSUE THREAD

**Issue by mcdee** [ethereum/go-ethereum#15128]
#### System information

Geth
Version: 1.7.0-unstable
Git Commit: d70536b5d4e8580a39a9887ce58c4a21c74344ee
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: linux

#### Expected behaviour

`geth account list` should show a Ledger Nano S account

#### Actual behaviour

`geth account list` does not show any Ledger Nano S information

#### Steps to reproduce the behaviour

Run `geth account list`.

Note that the Ledger is set up and working correctly.  If I run `geth console` and then `eth.accounts` in the console it shows the Ledger Nano S' account.

**Comment by Falsetto286** [comment]
Need you help guys.

MY main wallet adress is not showing in MEW/my crypto/ledger live. It is like it has never existed on my ledger allthough I have been using it for the past 2 years. I tried different derivation paths but it still doesn't show up.

Hope you guys can help me out or all my eth will be lost in nirvana......
