### ISSUE TITLE
Some transactions are not getting mined in in private ethereum blockchain.

### ISSUE THREAD

**Issue by mohitsharma18** [ethereum/go-ethereum#15136]
#### System information

Geth version: 1.6.7
OS & Version: Linux ( Ubuntu - 16.04)

#### Expected behaviour
All transactions should be mined.

#### Actual behaviour
We are getting transactionHash for all transactions but some of those transactions are not getting mined.

#### Steps to reproduce the behaviour
Make 50+ transactions in private blockchain,note down txHash corresponding to each transaction, Now check all transactions, some of these will return null, as we do "eth.getTransaction(txHash)" i.e those transactions are not mined.
Why is it like this ?
Please give some solution for this and the reason for this issue, so that we can ensure smooth working before going live.
Is there any issue of gasPrice??

**Comment by karalabe** [comment]
Please try running the master branch. We've fixed an ugly issue in the transaction pool last week.

**Comment by kocho** [comment]
I had a similar problem on a privateNet (geth was dropping transactions from pending pool) and can confirm that by upgrading geth to the masterBranch the transaction pool is working much better.

**Comment by karalabe** [comment]
Please upgrade to Geth 1.7.0. This issue should be solved.
