### ISSUE TITLE
Repair database when files are broken

### ISSUE THREAD

**Issue by porky11** [ethereum/go-ethereum#15130]
#### System information

Geth version: `1.6.7-stable`
OS & Version: Arch Linux (Antergos)

Some database files are broken after my pc froze.
Only the last few files are broken, all other files are intact.
Can I repair the database without deleting everything?
Can I remove only the broken part of the database?

````
INFO [09-12|00:52:57] Starting peer-to-peer node               instance=Geth/v1.6.7-stable-ab5646c5/linux-amd64/go1.8.3
INFO [09-12|00:52:57] Allocated cache and file handles         database=/home/porky11/.ethereum/geth/chaindata cache=128 handles=1024
Fatal: Error starting protocol stack: open /home/porky11/.ethereum/geth/chaindata/498461.ldb: no such device or address
````

**Comment by fjl** [comment]
The .ldb files cannot be repaired, sorry.
