### ISSUE TITLE
Single miner collecting all transactions while other miners only generate empty blocks.

### ISSUE THREAD

**Issue by ynatdata61** [ethereum/go-ethereum#15132]
#### System information

Geth version: `geth version`
1.6.7
OS & Version: Windows/Linux/OSX
Linux
Commit hash : (if `develop`)

#### Expected behaviour
I was trying to measure transaction processing time under different network configurations on a private ethereum blockchain (we have 10 miners and 10 clients implemented on Openstack vms, each of them is manually connected with all other peers), but encountered something unexpected. 

We managed to send transactions at around 25 tps for about 30 min with the default block size. As transactions are issued periodically, we expect them to be uniformly distributed among blocks, and block sizes to be roughly the same. 

#### Actual behaviour
The result was a bit shocking: we received several blocks with ~5000 transactions in them, and between two big blocks there are always several empty blocks. 

I then tried to limit the block size by setting the gasLimit tag, but after that there were more invalid transactions. 

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
A few ideas:

  * Please try the experiment again with the master branch. We've found and fixed a fairly ugly bug that mostly appears during mining and causes transactions to go missing (if multiple blocks are mined at the same time).
 * Geth has a transaction pool limit of 4K executable and 1K non executable transactions. These are enough for the main network, but if you're doing benchmarks, I'd roughly guess you'd need to bump these limits as 5K transacitions in a single block means the pool gets empty after a single block. So perhaps what you've been seeing is only the transaction originator keeping all transactions, and others just emptying their pool and not having anything left to include.
