### ISSUE TITLE
Mist stuck at 99%

### ISSUE THREAD

**Issue by Kjos** [ethereum/go-ethereum#15144]
#### System information

Geth version: 0.9.0
OS & Version: Ubuntu
Commit hash : 

#### Expected behaviour

I expect the full blockchain to download succesfully.

#### Actual behaviour

Stuck at 99%. Last few percentages also take much longer.

#### Steps to reproduce the behaviour

I removed the chainfile once. Don't know if that matters.
Using the Mist Wallet, not from commandline.
The error in the backtrace below pops ups for a lot of lines in the node log and keeps going.

I checked NTP server is running; I restarted it once too after update.

I've successfully downloaded the entire chain before this. Then switched to testnet. Testnet chain didn't download at all (very few peers too, 1/2). I deleted the chain thinking it might've solved that, but didn't affect it. Then I switched back to live chain, and now it's still stuck at 99%.

#### Backtrace

````
INFO [09-13|17:27:19] Imported new state entries               count=384  flushed=396 elapsed=9.431ms    processed=15256993 pending=20261 retry=0    duplicate=2261 unexpected=6615
INFO [09-13|17:27:20] Imported new state entries               count=384  flushed=510 elapsed=6.172ms    processed=15257377 pending=19807 retry=2    duplicate=2261 unexpected=6615
INFO [09-13|17:27:20] Imported new state entries               count=384  flushed=422 elapsed=6.413ms    processed=15257761 pending=19542 retry=0    duplicate=2261 unexpected=6615
INFO [09-13|17:27:20] Imported new state entries               count=384  flushed=306 elapsed=11.255ms   processed=15258145 pending=19581 retry=2    duplicate=2261 unexpected=6615
INFO [09-13|17:27:20] Imported new state entries               count=384  flushed=342 elapsed=7.597ms    processed=15258529 pending=19487 retry=0    duplicate=2261 unexpected=6615
INFO [09-13|17:27:20] Imported new state entries               count=384  flushed=492 elapsed=5.165ms    processed=15258913 pending=19086 retry=2    duplicate=2261 unexpected=6615
INFO [09-13|17:27:21] Imported new state entries               count=384  flushed=313 elapsed=9.543ms    processed=15259297 pending=19048 retry=2    duplicate=2261 unexpected=6615
INFO [09-13|17:27:21] Imported new state entries               count=384  flushed=444 elapsed=6.895ms    processed=15259681 pending=18787 retry=0    duplicate=2261 unexpected=6615
INFO [09-13|17:27:21] Imported new state entries               count=306  flushed=170 elapsed=10.002ms   processed=15259987 pending=18935 retry=0    duplicate=2261 unexpected=6615
INFO [09-13|17:27:21] Imported new state entries               count=384  flushed=467 elapsed=5.186ms    processed=15260371 pending=18576 retry=2    duplicate=2261 unexpected=6615
````

**Comment by Kjos** [comment]
Update: It has gone through eventually, but was stuck for very long.

**Comment by karalabe** [comment]
It's not stuck, it just has to download an enormous trie. Mist's UI is not the best to highlight what's happening in the background.

**Comment by karalabe** [comment]
We're trying to come up with a different way to sync the trie, hopefully that wil help it go a ton faster. Hang in there in the mean time :)

**Comment by Kjos** [comment]
Okay, good to hear. Sorry for the post, I assumed it was an issue. Keep up the good work :)
