### ISSUE TITLE
--ipcpath is ignore in favor of default path

### ISSUE THREAD

**Issue by julian1** [ethereum/go-ethereum#15151]
#### System information
$ geth version
Geth
Version: 1.6.7-stable
Git Commit: ab5646c532292b51e319f290afccf6a44f874372
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.7

#### Expected behaviour

start one instance of geth with explicit --datadir
start another instance geth and specify the ipc file path (and|or the --datadir)
geth attaches successfully
 

#### Actual behaviour

geth uses the default ipc path, and fails to connect

#### Steps to reproduce the behaviour
```
me@geth-test:~$ 
me@geth-test:~$ ls /home/me/data/geth.ipc 
/home/me/data/geth.ipc
me@geth-test:~$ geth --ipcpath /home/me/data/geth.ipc  attach
Fatal: Unable to attach to remote geth: dial unix /home/me/.ethereum/geth.ipc: connect: no such file or directory
```

**Comment by fjl** [comment]
`geth attach /home/me/data/geth.ipc` will work. `--ipcpath` is where the socket will be *created*. I agree it's confusing.

**Comment by julian1** [comment]
@fjl Ok thanks. Perhaps renaming the flag --setipcpath would be clearer? Feel free to close the issue.
