### ISSUE TITLE
Andoird sendTransaction go.Universe$proxyerror: invalid sender

### ISSUE THREAD

**Issue by cytl5yy** [ethereum/go-ethereum#15150]
I use the Geth fo android ,i want to sendTransaction by my geth node ,the node has started by called node.start()  .    my  sendTransaction function :
  

           private void sendTransaction() {
             try {
            String root = Environment.getExternalStorageDirectory().getPath() + "/ethereum/keystore";
            KeyStore keyStore = new KeyStore(root,
                    Geth.StandardScryptN, Geth.StandardScryptP);
            Accounts accounts = keyStore.getAccounts();
            if (accounts.size() >= 2) {
                account1 = accounts.get(0);
                account2 = accounts.get(1);
            }
            Log.i(TAG, "Account1: " + account1.getAddress().getHex()); //Sender
            Log.i(TAG, "Account2: " + account2.getAddress().getHex()); //Receiver
            BigInt value = Geth.newBigInt(1);
            BigInt gasLimit = Geth.newBigInt(0);
            BigInt gasPrice = Geth.newBigInt(0);
            long nonce = client.getPendingNonceAt(ctx, account1.getAddress()); // 1. Blocks the Thread if used? Syncing maybe?
            Log.i(TAG, "Nonce used:" + nonce);
            org.ethereum.geth.Transaction transaction = Geth.newTransaction(nonce, account2.getAddress(), value, gasLimit, gasPrice, null);

            keyStore.unlock(account1, "123456");
            transaction = keyStore.signTx(account1, transaction, new BigInt(1)); // 2. Why BigInt needed?

            Log.i(TAG, "Cost: " + transaction.getCost());
            Log.i(TAG, "GasPrice: " + transaction.getGasPrice());
            Log.i(TAG, "Gas: " + transaction.getGas());
            Log.i(TAG, "Nonce: " + transaction.getNonce());
            Log.i(TAG, "Value: " + transaction.getValue());
            Log.i(TAG, "Sig-Hash Hex: " + transaction.getSigHash().getHex());
            Log.i(TAG, "Hash Hex: " + transaction.getHash().getHex());
            Log.i(TAG, "To: " + transaction.getTo().getHex());
            Log.i(TAG, "Sender: " + transaction.getFrom(new BigInt(1)).getHex()); // 3. Produces the Error-Output.

            client.sendTransaction(ctx, transaction);
        } catch (Throwable e) {
            e.printStackTrace();
        }

    } 
    
 it's  show  go.Universe$proxyerror: invalid sender  . what's the problem?   how can i sendTransaction in light node for android.

**Comment by Mikekeke** [comment]
@cytl5yy Hi. Did you managed to solve this problem? I'm facing exact same issue.

**Comment by TheRealDannz0r** [comment]
@Mikekeke @cytl5yy Did anyone of you manage to solve this issue? Calling the contract in another way through `keyStore.signTxPassphrase(account, pass, tx, networkID)`.

**Comment by Mikekeke** [comment]
@TheRealDannz0r I didn't. Project now abandoned, so I don't have any new useful info about this

**Comment by TheRealDannz0r** [comment]
@Mikekeke Thanks for getting back at me and sorry to hear. It looks like it is *supposed* to be quite straight-forward, judging by https://github.com/ethereum/go-ethereum/wiki/Mobile:-Account-management. Not sure why signing is such a big fuzz. Seems like #15069 still has this issue as well.

**Comment by TheRealDannz0r** [comment]
@Mikekeke The problem is gone now with the latest update (1.8.8), released a few days ago. There is another problem, though, with transaction costs, error: `go.Universe$proxyerror: insufficient funds for gas * price + value`. Funds are definitely there.

**Comment by Mikekeke** [comment]
@TheRealDannz0r I rememver, I found this while was searching for answers: https://github.com/ethmobile/ethdroid
Looks like a working wrapper. May be you'll manage to dig something out there
