### ISSUE TITLE
Build fails on Alpine Linux ppc64le with go 1.9

### ISSUE THREAD

**Issue by rgdoliveira** [ethereum/go-ethereum#15160]
#### System information

Geth version: 1.7.0
Go version: 1.9
OS & Version: Alpine Linux 3.6 
Architecture: ppc64le

#### Actual behaviour
Package build fails on Alpine Linux (musl) with error:

github.com/ethereum/go-ethereum/node
github.com/ethereum/go-ethereum/whisper/whisperv5
github.com/ethereum/go-ethereum/core
github.com/ethereum/go-ethereum/eth/downloader
compile: invalid offset for DS form load/store 00056 (/home/rdutra/repos/aports/community/geth/src/go-ethereum-1.7.0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/statesync.go:452)	MOVD	R0, "".~r2+33(FP)
github.com/ethereum/go-ethereum/eth/filters
github.com/ethereum/go-ethereum/light
util.go:44: exit status 2
exit status 1

With go 1.8.3 I am able to build the package fine.

#### Steps to reproduce the behaviour
- Clone go-ethereum repository in an Alpine ppc64le
- run `make` (with go 1.9 installed)

**Comment by laboger** [comment]
I can see the PPC64.rules for Zero are not checking alignment in the cases when they should be. I can create a fix.

**Comment by laboger** [comment]
Please note this is not specific to Alpine, that is just the first place where it was found.

**Comment by laboger** [comment]
Can you open a golang issue for this?

**Comment by rgdoliveira** [comment]
@laboger Sure, I just opened it at: https://github.com/golang/go/issues/21947

**Comment by fjl** [comment]
We can't do anything about this.

**Comment by harsha544** [comment]
@laboger @rgdoliveira I believe this is addressed in [go1.9.2-ppc64le](https://github.com/golang/go/issues/21947) was any testing done to confirm go-ethereum works on ppc64le ?

**Comment by laboger** [comment]
The fix for this went into go 1.9.2. This was a regression in golang 1.9, not specific to Alpine. The bug did not exist in go 1.8.

commit 0ab99b396df9fc45c5cf1ac412da4f1848c3462c
Author: Lynn Boger <laboger@linux.vnet.ibm.com>
Date:   Tue Sep 19 17:36:57 2017 -0400

    [release-branch.go1.9] cmd/compile: fix regression in PPC64.rules move zero
    
    When a MOVDstorezero (8 bytes) is used the offset field
    in the instruction must be a multiple of 4. This situation
    had been corrected in the rules for other types of stores
    but not for the zero case.
    
    This also removes some of the special MOVDstorezero cases since
    they can be handled by the general LowerZero case.
    
    Updates made to the ssa test for lowering zero moves to
    include cases where the target is not aligned to at least 4.
    
    Fixes #21947
    
    Change-Id: I7cceceb1be4898c77cd3b5e78b58dce0a7e28edd
    Reviewed-on: https://go-review.googlesource.com/64970
    Run-TryBot: Lynn Boger <laboger@linux.vnet.ibm.com>
    TryBot-Result: Gobot Gobot <gobot@golang.org>
    Reviewed-by: Carlos Eduardo Seo <cseo@linux.vnet.ibm.com>
    Reviewed-by: Cherry Zhang <cherryyz@google.com>
    Reviewed-on: https://go-review.googlesource.com/70978
    Run-TryBot: Russ Cox <rsc@golang.org>
