### ISSUE TITLE
How to change the difficulty and the gasprice

### ISSUE THREAD

**Issue by saltegg1986** [ethereum/go-ethereum#15168]
I want to change the difficulty of the mining, in order to make the block generation faster.

also, I want to change gasprice to 0.

Please help me about the details of source code,thank you.

#### Backtrace

````
[backtrace]
````

**Comment by mexskican** [comment]
You can set the difficulty in your genesis Block, and change the gas price when sending your transactions.
Setting the gasprice to zero can be a little bit tricky, since the gas price is also a way to prevent infinite loops and such.

**Comment by saltegg1986** [comment]
Thank you very much for your answer.
I have set the difficulty in my genesis block,. At the beginning, the time of the block generation is short, but after a while, the time will turn longer. So is there a way to save the time of thg block generation.

**Comment by RichHorrocks** [comment]
Ideally ask questions on https://ethereum.stackexchange.com - it is important to keep issue-trackers clear and for real issues only.

Note that you can only set the _starting_ difficulty in the genesis block. To set a static difficulty requires a change to the code.

**Comment by 9607835** [comment]
@saltegg1986 
> Thank you very much for your answer.
> I have set the difficulty in my genesis block,. At the beginning, the time of the block generation is short, but after a while, the time will turn longer. So is there a way to save the time of thg block generation.

for geth version 1.8.13: `sed -i 's/return CalcDifficulty(chain.Config(), time, parent)/return big.NewInt(2)/' /go/go-ethereum/consensus/ethash/consensus.go`

this will permanently fix the difficulty to a constant, just change `2` to whatever you desire.
