### ISSUE TITLE
go sending GET_BLOCKS when clearly it has advanced chain

### ISSUE THREAD

**Issue by romanman** [ethereum/go-ethereum#1517]
```
17:37:44.061 [net]  To: 	ip68-110-70-120.ph.ph.cox.net/68.110.70.120:30303 	Send: 	[HELLO p2pVersion=4 clientId=Ethereum(J)/v0.9.5/Dev/Windows/Java capabilities=[eth:60] peerPort=30303 peerId=42fc0169955cba739d51a12637149626a7852955138852593169f5189a464dc990b916b3850302617d61a65598158cb317cda34517137c16fd0bf2b5cab6c77b]
17:37:44.067 [net]  From: 	ip68-110-70-120.ph.ph.cox.net/68.110.70.120:30303 	Recv: 	[HELLO p2pVersion=4 clientId=Geth/MichelsonMorley/v0.9.39-adc7ab0d/linux/go1.4.2 capabilities=[eth:61 eth:60 shh:2] peerPort=0 peerId=c9bd41bc3c6ce895de13037716000ca4e7605ba5c4dd3f19fc6c02e0252e729a1263581cf0f345aef40307efa81cec1c93d9473dbf9c5fa0187589003ee3182b]
17:37:44.077 [net]  To: 	ip68-110-70-120.ph.ph.cox.net/68.110.70.120:30303 	Send: 	[STATUS protocolVersion=60 networkId=0 totalDifficulty=020000 bestHash=fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca genesisHash=fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca]
17:37:44.313 [net]  From: 	ip68-110-70-120.ph.ph.cox.net/68.110.70.120:30303 	Recv: 	[STATUS protocolVersion=60 networkId=0 totalDifficulty=24a69e9c545017 bestHash=6c79bfad4a54335117e4c2f5c7aef826bdd12471578666d683c0b112e193116d genesisHash=fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca]
```

```
17:37:46.478 [net]  From: 	ip68-110-70-120.ph.ph.cox.net/68.110.70.120:30303 	Recv: 	[GET_BLOCKS 01ac4ea74d416aa01a25f5c11a51f3864280129a2ea7eb650ddf0008563de759...01ac4ea74d416aa01a25f5c11a51f3864280129a2ea7eb650ddf0008563de759] (1)
```

go sending GET_BLOCKS when clearly it has advanced chain
not a bug but maybe can be improved , @obscuren : what do you think ?

**Comment by karalabe** [comment]
One guess would be that you possibly announced a block with the said hash to the geth node, and since geth found it unknown, it tried to retrieve it. Could this be the case?

**Comment by romanman** [comment]
@karalabe : nop sorry , didn't send any block at all.

**Comment by karalabe** [comment]
Wasn't referring to blocks, but rather block announcements: the `NewBlockHashes` message from the wire spec https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol#ethereum-sub-protocol

**Comment by fjl** [comment]
@karalabe ethereumj doesn't implement `NewBlockHashes` yet.

**Comment by romanman** [comment]
@fjl :: can you explain a bit please ?

**Comment by fjl** [comment]
I closed this issue because it happened with an Olympic peer running a very old version of geth and the blockchain sync code has changed significantly. While there is no commit specifically addressing this particular GH issue, it is very unlikely that we will be doing any debugging with geth v0.9.39 to figure out what it was that caused this message to be sent.
