### ISSUE TITLE
Geth does not sync to Byzantium in light syncmode

### ISSUE THREAD

**Issue by dstreppa** [ethereum/go-ethereum#15174]
#### System information

Geth version: `Geth/v1.7.0-stable-6c6c7b2a/linux-arm/go1.7.4`
OS & Version: Raspbian Jessie
Commit hash : (if `develop`)

#### Expected behaviour
I am trying to sync my geth nodes in `light` mode to Byzantium, but without result. I did the same in `fast` and "normal" mode and I had no problems (not on Raspbian, on Ubuntu 16.04).

#### Actual behaviour
<pre>
pi@smartpi:~ $ geth --testnet --syncmode light --rpc --rpcport 8545 --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "eth,net,web3" console
WARN [09-20|09:41:07] No etherbase set and no accounts found as default 
INFO [09-20|09:41:07] Starting peer-to-peer node               instance=Geth/v1.7.0-stable-6c6c7b2a/linux-arm/go1.7.4
INFO [09-20|09:41:07] Allocated cache and file handles         database=/home/pi/.ethereum/testnet/geth/lightchaindata cache=128 handles=1024
INFO [09-20|09:41:12] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Engine: ethash}"
INFO [09-20|09:41:12] Disk storage enabled for ethash caches   dir=/home/pi/.ethereum/testnet/geth/ethash count=3
INFO [09-20|09:41:12] Disk storage enabled for ethash DAGs     dir=/home/pi/.ethash                       count=2
INFO [09-20|09:41:12] Added trusted CHT for ropsten testnet 
INFO [09-20|09:41:12] Loaded most recent local header          number=1698879 hash=e647d8…33e300 td=2219844550310073
INFO [09-20|09:41:12] Starting P2P networking 
INFO [09-20|09:41:16] UDP listener up                          self=enode://5ef57ecbc07e5c4218ebb95193a9b1ab957dbd5994f9bebf4aae20d99068018ef1136a555f8cbefa9ddbc4b459525a807ca8a644523962cf51b07ef98990aa15@[::]:30303
WARN [09-20|09:41:16] Light client mode is an experimental feature 
INFO [09-20|09:41:16] RLPx listener up                         self=enode://5ef57ecbc07e5c4218ebb95193a9b1ab957dbd5994f9bebf4aae20d99068018ef1136a555f8cbefa9ddbc4b459525a807ca8a644523962cf51b07ef98990aa15@[::]:30303
ERROR[09-20|09:41:16] Failed to retrieve current release       err="can't fetch trie key 5380c7b7ae81a58eb98d9c78de4a1fd7fd9535fc953ed2be602daaa41767312a: no suitable peers available"
INFO [09-20|09:41:16] IPC endpoint opened: /home/pi/.ethereum/testnet/geth.ipc 
INFO [09-20|09:41:16] HTTP endpoint opened: http://0.0.0.0:8545 
Welcome to the Geth JavaScript console!

instance: Geth/v1.7.0-stable-6c6c7b2a/linux-arm/go1.7.4
 modules: admin:1.0 debug:1.0 eth:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

#...after a lot of time (~1h)
> net.peerCount
0
#...after another lot of time (~1h)
> INFO [09-20|10:03:13] Block synchronisation started 
INFO [09-20|10:03:14] Imported new block headers               count=0 elapsed=98.765ms number=1699071 hash=999f9e…ea11f9 ignored=192
INFO [09-20|10:03:15] Imported new block headers               count=0 elapsed=92.418ms number=1699263 hash=143fed…838a59 ignored=192
INFO [09-20|10:03:15] Imported new block headers               count=0 elapsed=105.107ms number=1699455 hash=f95284…e50809 ignored=192
INFO [09-20|10:03:16] Imported new block headers               count=0 elapsed=97.551ms  number=1699647 hash=af0195…6502d7 ignored=192
INFO [09-20|10:03:17] Imported new block headers               count=0 elapsed=92.750ms  number=1699839 hash=8a4715…f88649 ignored=192
WARN [09-20|10:03:17] Rolled back headers                      count=160 header=1698879->1698879 fast=0->0 block=0->0
WARN [09-20|10:03:17] Synchronisation failed, dropping peer    peer=00ae60771d9815da err="retrieved hash chain is invalid"
INFO [09-20|10:05:27] Imported new block headers               count=0   elapsed=96.529ms  number=1699071 hash=999f9e…ea11f9 ignored=192
INFO [09-20|10:05:27] Imported new block headers               count=0   elapsed=102.277ms number=1699263 hash=143fed…838a59 ignored=192
INFO [09-20|10:05:28] Imported new block headers               count=0   elapsed=94.570ms  number=1699455 hash=f95284…e50809 ignored=192
INFO [09-20|10:05:28] Imported new block headers               count=0   elapsed=95.965ms  number=1699647 hash=af0195…6502d7 ignored=192
INFO [09-20|10:05:28] Imported new block headers               count=0   elapsed=88.746ms  number=1699839 hash=8a4715…f88649 ignored=192
WARN [09-20|10:05:29] Rolled back headers                      count=160 header=1698879->1698879 fast=0->0 block=0->0
WARN [09-20|10:05:29] Synchronisation failed, dropping peer    peer=e71ba996b923e475 err="retrieved hash chain is invalid"

> net.peerCount
0

</pre>

#### Steps to reproduce the behaviour
Start a geth client in `light` mode before the block `1700000` on Ropsten and try to sync the node to the last block.

#### Backtrace

````
[backtrace]
````

**Comment by dstreppa** [comment]
I think the problem is due to the fact that the found peers are always running geth 1.6.x, as in the example below:
<pre>
> admin.peers
[{
    caps: ["eth/62", "eth/63", "les/1"],
    id: "ceb6160d1c651a833702e117677ee9eb5d24ba9a311feaf0aa2ef7d9bb3b9628741e5f636d30eaa4680dce535017242bdf321b24085e4ed18151aff28463f3cd",
    name: "Geth/v1.6.5-stable-cf87713d/linux-arm/go1.8.3",
    network: {
      localAddress: "195.176.65.228:46846",
      remoteAddress: "80.108.195.55:30303"
    },
    protocols: {
      les: {
        difficulty: 1933593126368367,
        head: "e9773c6ee1d81c9893190a7092244f267b4e0f15aeb08fab6ac31b26b87cc9bb",
        version: 1
      }
    }
}]
</pre>

**Comment by dstreppa** [comment]
Friday geth started to find light peers, now it works.
<pre>
...
{
    caps: ["eth/62", "eth/63", "les/1", "shh/5"],
    id: "b2e71ac32168cc263a507125d11e0d34e1d530cbe8c9ae81c8bc76d01c94616d4beec41160885577222ac547fcc5f03db31c55e1a56c4351d5f47a6ec62a41cc",
    name: "Geth/v1.7.0-stable/linux-amd64/go1.9",
    network: {
      localAddress: "195.176.65.217:41888",
      remoteAddress: "51.15.218.125:30303"
    },
    protocols: {
      les: {
        difficulty: 211358845068,
        head: "148a9dced4b3612df256de22586f3e1e339f1fac4b2a93eb180315f6af5dbbbb",
        version: 1
      }
    }
}, {
    caps: ["eth/62", "eth/63", "les/1"],
    id: "e0a1c578e6ad39e68ea5327a24c07a5f1b99602c7a41968861f4517f4233009854cbdff95bd0b9f659848525211c3ee99d640d8cfde41615585b467601c1db7a",
    name: "Geth/v1.7.0-stable-6c6c7b2a/linux-amd64/go1.9",
    network: {
      localAddress: "195.176.65.217:36912",
      remoteAddress: "52.208.46.161:30311"
    },
    protocols: {
      les: {
        difficulty: 2834117325842971,
        head: "4d43ed52cef6dc065fb71090f6e8e7f8e1de7dfd45b34574a4667293c36e5522",
        version: 1
      }
    }
},
...
</pre>

**Comment by karalabe** [comment]
Thanks for the confirm that it works, closing. Btw, it may have been light client bootnode issues. We'll try to set up a few more light bootnodes to ensure it doesn't happen again.

**Comment by nikita-fuchs** [comment]
Issue seems to persist, running geth in lightmode will not sync, admin.peers returns nothing. Could anyone please provide boot nodes for light syncing ? Running 1.7.2. btw.

**Comment by hynese** [comment]
Upgraded an old VM from v1.7.1 to v1.7.3 and I couldn't sync in `"light"` mode.

Re-synced using `--syncmode="fast"` mode instead.
