### ISSUE TITLE
eth_getBlockTransactionCountByHash returns null

### ISSUE THREAD

**Issue by tsikov** [ethereum/go-ethereum#15178]
#### System information

Geth version: `Geth/v1.6.5-stable-cf87713d/darwin-amd64/go1.8.3`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour

To get the number of transactions as [per documentation](https://github.com/ethereum/wiki/blob/master/JSON-RPC.md#eth_getblocktransactioncountbyhash)

#### Actual behaviour

I am getting `null` instead of a hexadecimal string for the `result`:

#### Steps to reproduce the behaviour

```
curl -X POST http://localhost:8545 --data '{"jsonrpc":"2.0","method":"eth_getBlockTransactionCountByHash","params":["0xb903239f8543d04b5dc1ba6579132b143087c68db1b2168786408fcbce568238"],"id":1}' 
```
produces:

```
{"jsonrpc":"2.0","id":1,"result":null}
```

I also tried with the infura.io service and got the exact same result.

#### Backtrace

N/A

**Comment by bas-vk** [comment]
Where did you got `0xb903239f8543d04b5dc1ba6579132b143087c68db1b2168786408fcbce568238` from and on which network? It doesn't seem to be a valid block on ropsten nor mainnet. If it isn't a valid block geth cannot determine the transaction count and returns `null`.

**Comment by tsikov** [comment]
@bas-vk Whoops... this hash is straight from the documentation. However if you substitute it with a real one (e.g. `0xeff0e1a88aa19ec53e5e1f9b3a4ea3dd897f037cc36c786712b93f0a197eb79c ` found [here](https://etherscan.io/block/4297758)) it still doesn't work:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockTransactionCountByHash","params":["0xeff0e1a88aa19ec53e5e1f9b3a4ea3dd897f037cc36c786712b93f0a197eb79c"],"id":65}' http://localhost:8545
```

result:

```
{"jsonrpc":"2.0","id":65,"result":null}
```

**Comment by bas-vk** [comment]
I believe that you either mix up networks or your node isn't synced yet.

Infura:

```
> curl --data '{"jsonrpc":"2.0","id":1,"method":"eth_getBlockTransactionCountByHash","params":["0xeff0e1a88aa19ec53e5e1f9b3a4ea3dd897f037cc36c786712b93f0a197eb79c"]}' https://mainnet.infura.io
{"jsonrpc":"2.0","id":1,"result":"0xac"}
```

Local node:
```
> curl --data '{"jsonrpc":"2.0","id":1,"method":"eth_getBlockTransactionCountByHash","params":["0xeff0e1a88aa19ec53e5e1f9b3a4ea3dd897f037cc36c786712b93f0a197eb79c"]}' localhost:8545
{"jsonrpc":"2.0","id":1,"result":"0xac"}
```

The block with the hash you pointed is block number 4297758 which is fairly recent. Ensure that your node has synced beyond that block number. If not geth will return null.

**Comment by tsikov** [comment]
It seems to be working now. I guess you are right. Thanks!
