### ISSUE TITLE
Is there a way to dump Geth metrics in a csv file

### ISSUE THREAD

**Issue by SinghalB** [ethereum/go-ethereum#15173]
Geth monitor plots metrics exposed by Geth on a terminal but I want to dump Geth metrics (all or some of them) in a file for further programmatical processing.

For example, instead of getting an aggregated output as shown below, I need a time series output for each metric.
<pre>
> debug.metrics(true).eth.db.chaindata.user.reads
{
  AvgRate01Min: 58352658.845165044,
  AvgRate05Min: 42789394.99537952,
  AvgRate15Min: 22764439.80511231,
  MeanRate: 2213178.435842236,
  Overall: 28113856922
}
</pre>
go-ethereum wiki on github mentions raw metrics value can be retrieved using an optional flag, but the page doesn't mention which flag and how.

**Comment by bas-vk** [comment]
You can use the RPC interface with the `debug` module enabled.

The IPC interface has the debug module enabled by default. Retrieving this data from the command line can be done using netcat and jq can be using for filtering.
```
echo '{"id": 0, "jsonrprc": "2.0", "method": "debug_metrics", "params": [true]}' | nc -U ~/.ethereum/geth.ipc  | jq -S .result.eth.db.chaindata.user.reads
```

The http and ws interface don't have the debug module enabled by default. But you can enable them with the rpcapi and wsapi flags. Be carefull that exposing the debug module of an RPC interface that can be accessed by non trusted parties have security implications.

**Comment by RichHorrocks** [comment]
For future reference, ideally ask questions on https://ethereum.stackexchange.com - it is important to keep issue trackers clear and for real issues only.

**Comment by SinghalB** [comment]
@bas-vk Thanks a lot for replying and closing the issue.

@RichHorrocks I did ask the question on StackExchange earlier but no one replied.
https://ethereum.stackexchange.com/questions/26416/is-there-a-way-to-dump-geth-metrics-in-a-csv-file
