### ISSUE TITLE
eth_getBlockByNumber error

### ISSUE THREAD

**Issue by i3bitcoin** [ethereum/go-ethereum#15179]
Geth Version: Megara (v1.7.0)
Command ~/geth --rpc --rpcapi "db,eth,personal,txpool" --cache 1024 --syncmode=light

I get error when use eth_getBlockByNumber method after installation of new geth version.

Also there is an error on the geth startup
ERROR[09-21|08:50:54] Failed to retrieve current release       err="can't fetch trie key d490d37cf0a07a9953182944ba98ae65d44e5d00ccfcb229512f177f84fac30d: no suitable peers available"

Any idea?

**Comment by bas-vk** [comment]
> I get error when use eth_getBlockByNumber method after installation of new geth version.

Which error did you get? Something along the lines of `could not find suitable peers`? And it worked with geth 1.6.x? Also, could you verify that your light node is connect to a light server (from the console `admin.peers.length`)?

**Comment by i3bitcoin** [comment]
INFO [09-21|08:51:56] Starting peer-to-peer node               instance=Geth/v1.7.0-stable/linux-amd64/go1.8
INFO [09-21|08:51:56] Allocated cache and file handles         database=/root/.ethereum/geth/lightchaindata cache=1024 handles=1024
INFO [09-21|08:51:56] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 9223372036854775807 Engine: ethash}"
INFO [09-21|08:51:56] Disk storage enabled for ethash caches   dir=/root/.ethereum/geth/ethash count=3
INFO [09-21|08:51:56] Disk storage enabled for ethash DAGs     dir=/root/.ethash               count=2
INFO [09-21|08:51:56] Added trusted CHT for mainnet 
INFO [09-21|08:51:56] Loaded most recent local header          number=4297451 hash=1d9455…270b2c td=986944575165499725499
INFO [09-21|08:51:56] Starting P2P networking 
INFO [09-21|08:51:58] UDP listener up                          self=enode://16af794e6ab1ae81308b4af3df37f716bfdadfd6c82f22b7ab74e9342741a3b5f310403fbf1d2bf3c17b39a3fadf3381f0394426201ec204b560bbd7f18cf95a@[::]:30303
WARN [09-21|08:51:58] Light client mode is an experimental feature 
INFO [09-21|08:51:58] RLPx listener up                         self=enode://16af794e6ab1ae81308b4af3df37f716bfdadfd6c82f22b7ab74e9342741a3b5f310403fbf1d2bf3c17b39a3fadf3381f0394426201ec204b560bbd7f18cf95a@[::]:30303
INFO [09-21|08:51:58] IPC endpoint opened: /root/.ethereum/geth.ipc 
ERROR[09-21|08:51:58] Failed to retrieve current release       err="can't fetch trie key d490d37cf0a07a9953182944ba98ae65d44e5d00ccfcb229512f177f84fac30d: no suitable peers available"
INFO [09-21|08:52:02] Block synchronisation started 
INFO [09-21|08:52:03] Imported new block headers               count=25 elapsed=98.333ms number=4297476 hash=d53cac…929ecd ignored=0
INFO [09-21|08:53:08] Imported new block headers               count=1  elapsed=5.413ms  number=4297477 hash=e70223…5282d4 ignored=0
INFO [09-21|08:53:51] Imported new block headers               count=1  elapsed=3.738ms  number=4297478 hash=c7bb4e…fc94f4 ignored=0
INFO [09-21|08:54:19] Imported new block headers               count=1  elapsed=4.951ms  number=4297479 hash=2f69cb…dd7397 ignored=0

admin.peers.length
5


Yes, it worked fine before my last update.

**Comment by i3bitcoin** [comment]
I've just checked eth_getBlockByHash and it works fine.

**Comment by i3bitcoin** [comment]
Okay, I've just realized, that eth_getBlockByNumber needs HEX value in input, strange, but dec value worked fine for me in the previous update.
