### ISSUE TITLE
Geth TestNet Syncing Issue after Hard-Fork

### ISSUE THREAD

**Issue by farhankhwaja** [ethereum/go-ethereum#15177]
#### System information

Geth version: `1.7.0-stable`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
The blocks should be syncing at the same rate as the blocks are being generated (if i am not wrong).

#### Actual behaviour
The geth client is not able to sync and reach the latest block number on the testNet. Currently, its the blockNumber is at 1702011.
```
{
  currentBlock: 1702011,
  highestBlock: 1711644,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 1699999
}
```
I have been running geth testnet for a good 3 months now and was learning about things by performing my own experiments. But, after the hard-fork as asked, I updated the geth client and since, then the syncing has been extremely slow.

Can anyone help me with this or point me to right place.

**Comment by arbach** [comment]
geth build number ?

**Comment by farhankhwaja** [comment]
Found the issue for this. my geth starting script had a --bootnode option used which was making the syncing slow. As i removed this option and the sync started happening at a good speed.

**Comment by farhankhwaja** [comment]
Found the issue for this. my geth starting script had a --bootnode option used which was making the syncing slow. As i removed this option and the sync started happening at a good speed.

**Comment by farhankhwaja** [comment]
Also, had another question. I have a mainnet running on an old version of geth i.e. 1.6. Should i update the MainNet geth to 1.7.0?? and before doingt his do i need to take a back-up of chaindata of the current running geth client

**Comment by fjl** [comment]
@farhankhwaja you can upgrade to 1.7.0, but please note that there is no way to downgrade back to 1.6.0 in case of a problem.
