### ISSUE TITLE
(False ?) Virus signature in blockchain db files downloaded via geth

### ISSUE THREAD

**Issue by George3d6** [ethereum/go-ethereum#15189]
Yesterday I was procrastinating and ended up running:
`sudo clamscan --recursive --infected --exclude-dir='^/sys|^/dev' /  > clam.out`
(Basically scanning all my machine for infected files using clamav)

To my surprise it found a shit ton of ldb files which contained a signature for this virus:
`Geth Win.Trojan.Anaphylaxis-1`

I'm not sure if it's "normal" for the blockchain to contain virus signatures and I assume it's just a false positive introduced to fuck with people.

I downloaded the whole thing about 1~1.5 months ago when I was messing a bit with eth, so I can't exactly reproduce the steps that lead to this.

I'd be curios to know how someone could actually end up having these kind of "corrupted" files and whether or not this is a widespread phenomenon ? Any literature on the subject would be interesting to read, I thought I sort of knew how the etherium block chain worked but apparently not. The only semi-related topics on the subject I was able to find are old (earliest are from 2016) and don't go into much detail, they simply 

Either way, I'm reporting this as a "bug" with the client but since I don't understand it's root it may well not be a bug with geth and it may well not be a bug at all... In which case I'm all the more curios about how this is possible.

(Alternatively this could be a problem with the viruse signature db I have for clamav, in which case I may be in the wrong place)

#### System information

Geth version: 1.7.0-stable-6c6c7b2a
OS & Version: 4.12.13-1-ARCH #1 SMP PREEMPT Fri Sep 15 06:36:43 UTC 2017 x86_64 GNU/Linux

#### Expected behaviour

Download blockchain db files without a virus signature.

#### Actual behaviour

Downloaded blockchain db files with a virus signature.

#### Steps to reproduce the behaviour

I don't know, however, looking at my .histfile which goes quite a while back, these are all the commands I get when I grep for geth:

```
sudo pacman -S geth
geth
geth --datadir /home/trom/.ethereum
geth --datadir ~/.ethereum
geth --datadir ~/.ethereum
geth --datadir ~/.ethereum
geth account new
geth --mine --minerthreads=3
geth --mine --minerthreads=3
geth --mine --minerthreads=3 --fast
```

#### Backtrace

 I don't have a backtrace. It didn't crash.

**Comment by karalabe** [comment]
I think someone way back in 2015 inserted a virus binary as a transaction data content. It's totally harmless (just a data blob), but some virus scanners picked it up back then. Perhaps clamsv is decompressing the Snappy encoded database blocks and finding this binary inside?

**Comment by holiman** [comment]
Any sufficiently large blob of data will yield false positives on signature-based AV. It's not a bug.
