### ISSUE TITLE
Problem syncing since 1700000

### ISSUE THREAD

**Issue by jsdavis28** [ethereum/go-ethereum#15185]
#### System information

Geth version: 1.7.0
OS & Version: Ubuntu 17.04
Commit hash : (if `develop`)

#### Expected behaviour

Use Geth in terminal after running Ethereum Wallet (0.9.0) without needing to rewind Testnet to 1699999. 

#### Actual behaviour

It seems like Geth stops working in Ethereum Wallet, which is preventing a full sync; but the interesting thing is every time I run Geth from the command line after I close Ethereum Wallet, I keep getting the following error message: 

WARN [09-22|13:11:19] Rewinding chain to upgrade configuration err="mismatching Byzantium fork block in database (have <nil>, want 1700000, rewindto 1699999)"

Any ideas on what configuration error is occurring and how I can fix this?

**Comment by wtfiwtz** [comment]
See this: https://github.com/ethereum/go-ethereum/issues/15001... might be related

**Comment by karalabe** [comment]
Make sure you have an up-to-date Ethereum Wallet and the Geth contains within it is also 1.7.0. Ropsten was forked over to Byzantium on block 1.7M, and only Geth 1.7.0 supports it.
