### ISSUE TITLE
debug.storageRangeAt returns wrong value

### ISSUE THREAD

**Issue by yann300** [ethereum/go-ethereum#15196]
#### System information

Geth version: 1.7
OS & Version: Linux

#### Expected behaviour

debug.storageRangeAt ( .. ) to return '0x80' for a slot value 

#### Actual behaviour

debug.storageRangeAt ( .. ) return '0x8180' for a slot value (the value should be 0x80)

#### Steps to reproduce the behaviour

contract test {
uint v = 128
}
and call debug.storageRangeAt ( .. )
note that getStorageAt retrieve the right value.
could be that a rlp.decode() is missing somewhere.

**Comment by bas-vk** [comment]
I will look into it. Is there a description how this method should work since it isn't yet documented afaik.

**Comment by yann300** [comment]
i m afraid there is no doc... the most accurate info would be there : https://github.com/ethereum/go-ethereum/pull/3407 ...
