### ISSUE TITLE
How to get ethereum public key

### ISSUE THREAD

**Issue by chengwenxi** [ethereum/go-ethereum#15194]
Can I somehow get the public key of an ethereum account knowing just the corresponding ethereum address (e.g. 0x8be7a6246ac1c73c09ea62ef69d33836434de391)?

**Comment by karalabe** [comment]
You cannot. The address is derived from the public key via Keccak256 hashing. There's no way to obtain the preimage of the hash.

**Comment by chengwenxi** [comment]
@karalabe thanks, but if the ethereum don't know other's public key, how can it verify the signed transaction。

**Comment by karalabe** [comment]
Every transaction is digitally signed. The signature contains enough data to derive the public key, and from the public key, the address.

**Comment by chengwenxi** [comment]
@Arachnid Do you mean that the ethereum don't store public keys, I can only get the public key from a signature?

**Comment by karalabe** [comment]
Yup

**Comment by chengwenxi** [comment]
I’m truly grateful for your help
