### ISSUE TITLE
rinkeby-faucet: Mixed Content Error

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#15199]
I can currently not use the rinkeby faucet - error here:

```
(index):109 Mixed Content: The page at 'https://faucet.rinkeby.io/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://faucet.rinkeby.io/api'. This request has been blocked; this endpoint must be available over WSS.
reconnect @ (index):109
faucet.rinkeby.io/:109 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at reconnect (https://faucet.rinkeby.io/:109:15)
(index):101 WebSocket is already in CLOSING or CLOSED state.
```

**Comment by karalabe** [comment]
The websocket tries to connect on both http and https, since a user using puppeth might not have https in front. Hence why it might report an error. Nonetheless, it should try and succeed on https afterwards.

**Comment by ligi** [comment]
It is not working unfortunately - just tried it again - now also seeing this in the browser-console:
`
(index):107 WebSocket connection to 'wss://faucet.rinkeby.io/api' failed: Error during WebSocket handshake: Unexpected response code: 502`

**Comment by karalabe** [comment]
I've restarted the entire machine (restarting the faucet docker container wasn't enough) and now it seems to work. No idea what could have happened, occasionally docker seems to go belly up on me.

**Comment by ligi** [comment]
Thanks - that worked.
