### ISSUE TITLE
Make geth felt in error

### ISSUE THREAD

**Issue by cotil** [ethereum/go-ethereum#15193]
#### System information

Geth version: last one
OS & Version: Linux sur raspberry

need help for the installation of geth.
caution: i'm a newbie

#### i@raspberrypi:~/bin/go-ethereum $ make geth

build/env.sh go run build/ci.go install ./cmd/geth
build/_workspace/src/github.com/ethereum/go-ethereum/internal/build/azure.go:23:2: cannot find package "github.com/Azure/azure-storage-go" in any of:
	/usr/lib/go/src/pkg/github.com/Azure/azure-storage-go (from $GOROOT)
	/home/pi/bin/go-ethereum/build/_workspace/src/github.com/Azure/azure-storage-go (from $GOPATH)
build/_workspace/src/github.com/ethereum/go-ethereum/internal/build/pgp.go:27:2: cannot find package "golang.org/x/crypto/openpgp" in any of:
	/usr/lib/go/src/pkg/golang.org/x/crypto/openpgp (from $GOROOT)
	/home/pi/bin/go-ethereum/build/_workspace/src/golang.org/x/crypto/openpgp (from $GOPATH)
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 1

**Comment by karalabe** [comment]
Make sure you have Go 1.7 or later installed.

**Comment by cotil** [comment]
hello I've go 1.9

**Comment by cotil** [comment]
and i have tested it with "hello world", everything is ok....

**Comment by cotil** [comment]
someone can help me?

**Comment by karalabe** [comment]
What does `go version` and `go env` print?

**Comment by cotil** [comment]
go version: go version go1.3.3 linux/arm
go env:
GOARCH="arm"
GOBIN=""
GOCHAR="5"
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_arm"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"


does it mean I do not have de last version of GO?
I have downlaoded this one ;   go1.9.linux-armv6l.tar.gz   from googlesource
Have you another source?
does it mean I do not have de last version of GO?
I have downlaoded this one ;   go1.9.linux-armv6l.tar.gz   from googlesource

**Comment by cotil** [comment]
here is the source: https://storage.googleapis.com/golang/go1.9.linux-armv6l.tar.gz

**Comment by karalabe** [comment]
Your rpi probably has a Go version installed from it's package manager. You'll need to get rid of that. You can build and install Go from source afterwards. You'll need to put the freshly build Go `bin` folder into your PATH.

Alternatively, you should be able to download pre-built ARM binaries from our downloads page: https://geth.ethereum.org/downloads/

**Comment by cotil** [comment]
Ok thanks!
I'm gonna try :)

**Comment by cotil** [comment]
Done:

pi@raspberrypi:~/bin $ ls
geth-linux-arm64-1.7.0-6c6c7b2a         go
geth-linux-arm64-1.7.0-6c6c7b2a.tar.gz  go1.9.linux-armv6l.tar.gz

But no command work
i@raspberrypi:~ $ geth account new
bash: geth : commande introuvable


What have I missed? :)

**Comment by mitucsaki** [comment]
Try changing your directory. There is no symbolic link for geth. I had the same issue. Run from this directory:

> cd /path-to/go-ethereum/build/bin
> ./geth account new

**Comment by zerozheng** [comment]
i think this project is remove. got 404 when visit `github.com/Azure/azure-storage-go`.

**Comment by ykeisuke** [comment]
I think too.

On terminal:

```
$ govendor -version
v1.0.9

$ go version
go version go1.9.3 darwin/amd64

$ echo $GOPATH
/Users/keisuke/git/go

$ govendor sync -v
fetch "github.com/Azure/azure-storage-go"
# cd .; git clone https://github.com/Azure/azure-storage-go /Users/keisuke/git/go/.cache/govendor/github.com/Azure/azure-storage-go
Cloning into '/Users/keisuke/git/go/.cache/govendor/github.com/Azure/azure-storage-go'...
remote: Repository not found.
fatal: repository 'https://github.com/Azure/azure-storage-go/' not found
Error: Remotes failed for:
	Failed for "github.com/Azure/azure-storage-go" (failed to clone repo): exit status 128
```


When open repository using browser:

https://github.com/Azure/azure-storage-go/
![2018-06-20 16 20 02](https://user-images.githubusercontent.com/3081092/41643337-d7c00112-74a5-11e8-8927-e4b4defefc29.png)

**Comment by karalabe** [comment]
Fixed on master.

**Comment by ykeisuke** [comment]
Thank you!
