### ISSUE TITLE
make geth give wrong instruction how to run geth

### ISSUE THREAD

**Issue by plavcik** [ethereum/go-ethereum#15202]
$ make geth

on git version

finishes with 

github.com/ethereum/go-ethereum/cmd/geth
Done building.
Run "/build/bin/geth" to launch geth.

Please fix the path to 
./build/bin/geth
or
build/bin/geth

thank you

**Comment by karalabe** [comment]
Seems to work for me:

```
/work/src/github.com/ethereum/go-ethereum$ make geth
[...]
Done building.
Run "/work/src/github.com/ethereum/go-ethereum/build/bin/geth" to launch geth.
```

**Comment by plavcik** [comment]
in that case, it's probably platform specific, I'm on OpenBSD 6.1 amd64 and the full path created is missing the `pwd` part, so I'm getting only the path from currenet directory not from the root

I'm on latest git version, which give me 1.7.1-unstable-2b4a5f26

**Comment by bas-vk** [comment]
Could you try it with `gmake` instead of `make`?

**Comment by plavcik** [comment]
after git fetch

gmake geth
build/env.sh go run build/ci.go install ./cmd/geth
>>> /usr/local/go/bin/go install -ldflags -X main.gitCommit=2b4a5f2677fdf0d8a34a2d19fddc203b973dfe02 -v ./cmd/geth
cmd/geth/monitorcmd.go:31:2: cannot find package "github.com/gizak/termui" in any of:
 
: 
: 
util.go:44: exit status 1
exit status 1
gmake: *** [Makefile:15: geth] Error 1


make geth
build/env.sh go run build/ci.go install ./cmd/geth
>>> /usr/local/go/bin/go install -ldflags -X main.gitCommit=2b4a5f2677fdf0d8a34a2d19fddc203b973dfe02 -v ./cmd/geth
Done building.
Run "/build/bin/geth" to launch geth.

./build/bin/geth -h
   1.7.1-unstable-2b4a5f26
