### ISSUE TITLE
Ledger Nano S Not Working With Geth 1.7.x On OS/X

### ISSUE THREAD

**Issue by bokkypoobah** [ethereum/go-ethereum#15201]
#### System information

Geth version: 1.7.0-stable
OS & Version: OSX 10.12.6
Commit hash : 6c6c7b2af3efdad4d2f64f70f3a724af434bbcd2

#### Expected behaviour
Geth is able to list the Ledger Nano S accounts

#### Actual behaviour
Geth is unable to list the Ledger Nano S accounts

#### Steps to reproduce the behaviour
Run `geth console`, connect Ledger Nano S and enter PIN. Run `eth.accounts`

The same problem occurs with `geth` 1.7.1 develop.

The message `New wallet appeared                      url=ledger://IOService:/AppleACPIPl… status="Ethereum app v1.0.8 online"` does not show up in the console for 1.7.x but shows up in 1.6.x .

Retested with `geth` 1.6.1, 1.6.6 and 1.6.7 and the accounts show up.

Tested with MyEtherWallet with the Ledger Nano S in browser mode and the accounts are listed.

#### Backtrace

````
[backtrace]
````

**Comment by ncsolar** [comment]
I have the same problem with the Trezor in OSX 10.12.6 and Geth 1.7

**Comment by oddmarthon-lende** [comment]
I have the same problem with the Ledger OSX 10.12.6 and Geth 1.7

**Comment by acote88** [comment]
Also having the same issue, both on OSX 10.12.6 and 10.13 (High Sierra). Tried to rebuild go-ethereum with the following PR which is supposed to address some issues with Ledger https://github.com/ethereum/go-ethereum/pull/15161 but still doesn't work. I can see under go-ethereum/accounts/usbwallet/hub.go where it uses hidapi to enumerate devices, that it can find the Ledger Nano S but info.Interface returns -1 (error opening device). Tested that it works fine with geth 1.6.7.

**Comment by acote88** [comment]
Should also mention that the Ledger Nano S device works fine with the Ledger Chrome, with Parity and with the ledgerco nodejs package.

**Comment by karalabe** [comment]
We've been doing some polishes to the OSX USB library, and apparently borked something. It will be fixed in the next release, just need to get access to a macOS machine to test.

**Comment by RobertKohut** [comment]
@karalabe I have also run into this issue with the Ledger Nano S on Windows. After debugging the source, I found that this block of code does not append the ledger to the list of devices.

accounts/usbwallet/hub.go:
`for _, info := range hid.Enumerate(hub.vendorID, 0) {
	for _, id := range hub.productIDs {
		if info.ProductID == id && info.Interface == 0 {
			devices = append(devices, info)
			break
		}
	}
}`

info.Interface always returns -1 for all of the HIDs.

I changed this to:
`if info.ProductID == id && info.VendorID == hub.vendorID`

Now the Ledger Nano S successfully shows up in my account list!

**Comment by mexskican** [comment]
@karalabe I create a PR to fix this bug.

By the way the PR #15161 is fixing another bug.

**Comment by karalabe** [comment]
@RobertKohut Thanks for debugging this. This interface check was added for Trezor as it advertises 2 endpoints, one being a debug that won't connect. It was meant to filter that out. I'll need to check how the Trezor behaves on Windows and OSX to ensure we don't break that when fixing the Ledger.

**Comment by karalabe** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/15232.
