### ISSUE TITLE
How to synchronize full blocks

### ISSUE THREAD

**Issue by mi2zha** [ethereum/go-ethereum#15203]
#### System information

Geth version: `geth version`
OS & Version: OSX
Commit hash : (if `develop`)

The default is fast mode？
How to synchronize full blocks？

````
[backtrace]
````

**Comment by karalabe** [comment]
You can run with `--syncmode=full` but that will take a very long time and will consume 200-300GB of disk space at the end of it all.

**Comment by mi2zha** [comment]
@karalabe thank u

**Comment by karalabe** [comment]
:+1:
