### ISSUE TITLE
Not getting blocks with an existing height with geth (probably future uncles)

### ISSUE THREAD

**Issue by uohoo** [ethereum/go-ethereum#15209]
#### System information

Geth version: 1.7.0-stable-6c6c7b2a
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
I'm using websockets to suscribe the event newHeads: {"id": 1, "method": "eth_subscribe", "params": ["newHeads", {}]}'
In the especifications is said that the subscription can emit multiple headers on the same height but many times duplicated blocks (blocks with an height that already exists) are not obtained.

#### Actual behaviour
I'm getting all new blocks appended to the blockchain but new blocks that already have an existing height (blocks that will be probably attatched as uncles) are not received.

#### Steps to reproduce the behaviour
I followed https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB to create a subscription for newHeads that fires a notification each time a new header is appended to the chain.

I also tried polling using **eth_getFilterChanges** and **eth_newBlockFilter** and I'm getting same results, many blocks missing when the height block already exists.

Am I missing something? 
Thank you!!

**Comment by uohoo** [comment]
Then, how could I get all blocks mined? Is it possible to get it by API?

**Comment by uohoo** [comment]
Is there a solution using the RPC-API for getting all new blocks mined?

**Comment by bas-vk** [comment]
Could you explain what you are trying to accomplish?

**Comment by uohoo** [comment]
I already tried the option explained in the link and I have the same problem.
I would like to get all blocks mined by the network and not only blocks that moves the chain forward. Is it possible somehow?
