### ISSUE TITLE
WARN [09-26|20:10:13] Synchronisation failed, dropping peer    peer=9edaf7a938de9fb9 err="retrieved hash chain is invalid"

### ISSUE THREAD

**Issue by mi2zha** [ethereum/go-ethereum#15205]
#### System information

Geth version: `go version go1.9 linux/amd64`
OS & Version:  Linux
Commit hash : (if `develop`)

 /mnt/go/src/github.com/ethereum/go-ethereum/build/bin/geth --syncmode full --datadir /mnt/work/blockcoin/data/eth --rpc --rpcport 8545 --rpccorsdomain * --rpcapi eth,net,web3,debug,personal,miner

#### Actual behaviour

INFO [09-26|20:09:41] Imported new chain segment               blocks=2048 txs=0 mgas=0.000 elapsed=3.167s    mgasps=0.000 number=39424 hash=c79021…bee7ae
WARN [09-26|20:09:41] Skipping deep transaction reorg          depth=2048
INFO [09-26|20:09:44] Imported new chain segment               blocks=2048 txs=0 mgas=0.000 elapsed=2.814s    mgasps=0.000 number=41472 hash=f83aeb…315655
WARN [09-26|20:09:44] Skipping deep transaction reorg          depth=2048
INFO [09-26|20:09:47] Imported new chain segment               blocks=2048 txs=0 mgas=0.000 elapsed=2.943s    mgasps=0.000 number=43520 hash=b15b88…1606a4
WARN [09-26|20:09:47] Skipping deep transaction reorg          depth=2048
INFO [09-26|20:09:50] Imported new chain segment               blocks=2048 txs=0 mgas=0.000 elapsed=2.951s    mgasps=0.000 number=45568 hash=0fca46…4137f2
WARN [09-26|20:09:50] Skipping deep transaction reorg          depth=2048
ERROR[09-26|20:09:52]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Metropolis: 9223372036854775807 Engine: ethash}

Number: 46402
Hash: 0x249ea54eada07708b29d7c424b8466dec9f1d98067b0be1b89c7ee660cca858d

Error: out of gas
##############################

WARN [09-26|20:09:52] Synchronisation failed, dropping peer    peer=38ef3b1bf915d558 err="retrieved hash chain is invalid"
ERROR[09-26|20:10:13]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Metropolis: 9223372036854775807 Engine: ethash}

#### Backtrace

````
[backtrace]
````

**Comment by mi2zha** [comment]
supplementary information：

Geth
Version: 1.7.0-unstable
Git Commit: dcce41ed469ef610723d4dae26325ace74a4293d
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=/mnt/go
GOROOT=/usr/local/go

**Comment by tina1998612** [comment]
I had the same issue and fixed it after deleting everything in `~/Library/Ethereum/testnet/geth/chaindata`
Hope this helps!
