### ISSUE TITLE
[RPC] subscribe error: notifications not supported

### ISSUE THREAD

**Issue by maiiz** [ethereum/go-ethereum#15219]
#### System information

Version: 1.7.1-unstable
Git Commit: 5705ad004e01054c6aac173348b74c1097b40ff1
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux

#### Expected behaviour

i run the rpc test
```
go-ethereum/rpc/client_example_test.go
```

#### Actual behaviour

```
subscribe error: notifications not supported
```

#### Steps to reproduce the behaviour

```
go test
```

**Comment by bas-vk** [comment]
I don't what is/was causing this but the latest commit runs fine locally.
Please try it again with the latest source.
