### ISSUE TITLE
Geth 1.7.0 - got eth.blockNumber but not getting eth.syncing

### ISSUE THREAD

**Issue by abl1234** [ethereum/go-ethereum#15215]
Hi all

I am getting a reply on the eth.blockNumber but no longer getting reply on eth.syncing - I read in earlier post that once you get the importing chain segment every 14 seconds you are synced !! is this true?

thanks in advance

Welcome to the Geth JavaScript console!

instance: Geth/v1.7.0-stable-6c6c7b2a/linux-amd64/go1.9
coinbase: 0x9ca8c0cf47576208c5b017d9a560ed33d84f2267
at block: 4319261 (Thu, 28 Sep 2017 15:23:21 IST)
 datadir: /home/qb78846/.ethereum
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> 
> eth.blockNumber
4319261

> eth.syncing
false
> eth.blockNumber
4319295
> 

INFO [09-28|15:22:26] Imported new chain segment               blocks=1  txs=144  mgas=6.184  elapsed=300.339ms mgasps=20.591  number=4319258 hash=918a2f…f4303f
INFO [09-28|15:23:15] Imported new chain segment               blocks=1  txs=78   mgas=6.690  elapsed=247.792ms mgasps=26.998  number=4319259 hash=8b5c60…e30fd8
INFO [09-28|15:23:22] Imported new chain segment               blocks=1  txs=119  mgas=6.665  elapsed=270.203ms mgasps=24.668  number=4319260 hash=c9aa65…d34226
INFO [09-28|15:23:23] Imported new chain segment               blocks=1  txs=135  mgas=6.699  elapsed=325.189ms mgasps=20.600  number=4319260 hash=a4d113…f88899
INFO [09-28|15:23:34] Imported new chain segment               blocks=1  txs=45   mgas=4.678  elapsed=76.211ms  mgasps=61.380  number=4319261 hash=9945e0…171550
^CINFO [09-28|15:24:48] Got interrupt, shutting down... 
INFO [09-28|15:24:48] IPC endpoint closed: /home/qb78846/.ethereum/geth.ipc 
INFO [09-28|15:24:48] Blockchain manager stopped 
INFO [09-28|15:24:48] Stopping Ethereum protocol 
INFO [09-28|15:24:48] Ethereum protocol stopped 
INFO [09-28|15:24:48] Transaction pool stopped 
INFO [09-28|15:24:48] Database closed                          database=/home/qb78846/.ethereum/geth/chaindata
qb78846@qb78846-ThinkPad-X1-Carbon-4th ~ $ geth
INFO [09-28|15:25:11] Starting peer-to-peer node               instance=Geth/v1.7.0-stable-6c6c7b2a/linux-amd64/go1.9
INFO [09-28|15:25:11] Allocated cache and file handles         database=/home/qb78846/.ethereum/geth/chaindata cache=128 handles=1024
INFO [09-28|15:25:12] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 9223372036854775807 Engine: ethash}"
INFO [09-28|15:25:12] Disk storage enabled for ethash caches   dir=/home/qb78846/.ethereum/geth/ethash count=3
INFO [09-28|15:25:12] Disk storage enabled for ethash DAGs     dir=/home/qb78846/.ethash               count=2
INFO [09-28|15:25:12] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [09-28|15:25:12] Loaded most recent local header          number=4319260 hash=a4d113…f88899 td=1049400459973166684060
INFO [09-28|15:25:12] Loaded most recent local full block      number=4319261 hash=9945e0…171550 td=1049403369564691654014
INFO [09-28|15:25:12] Loaded most recent local fast block      number=4319260 hash=a4d113…f88899 td=1049400459973166684060
INFO [09-28|15:25:12] Loaded local transaction journal         transactions=0 dropped=0
INFO [09-28|15:25:12] Regenerated local transaction journal    transactions=0 accounts=0
WARN [09-28|15:25:12] Blockchain not empty, fast sync disabled 
INFO [09-28|15:25:12] Starting P2P networking 
INFO [09-28|15:25:14] Mapped network port                      proto=udp extport=30303 intport=30303 interface="UPNP IGDv1-IP1"
INFO [09-28|15:25:14] UDP listener up                          self=enode://c0c728478ad4a85c8771d25750e8c0cc8a41a9c70ac00ebc1b4ac8a0209aafb094f3750c2d2878dc97559fdb314cce236df45323862bab2bc7417a8a14a57b3b@192.168.0.16:30303
INFO [09-28|15:25:14] RLPx listener up                         self=enode://c0c728478ad4a85c8771d25750e8c0cc8a41a9c70ac00ebc1b4ac8a0209aafb094f3750c2d2878dc97559fdb314cce236df45323862bab2bc7417a8a14a57b3b@192.168.0.16:30303
INFO [09-28|15:25:14] IPC endpoint opened: /home/qb78846/.ethereum/geth.ipc 
INFO [09-28|15:25:14] Mapped network port                      proto=tcp extport=30303 intport=30303 interface="UPNP IGDv1-IP1"
INFO [09-28|15:30:54] Block synchronisation started 
INFO [09-28|15:31:22] Imported new chain segment               blocks=2 txs=228 mgas=13.293 elapsed=1.898s mgasps=7.000 number=4319263 hash=eb10ed…4f9170
INFO [09-28|15:31:25] Imported new chain segment               blocks=4 txs=416 mgas=20.605 elapsed=2.610s mgasps=7.894 number=4319267 hash=b541e1…de1224
INFO [09-28|15:31:30] Imported new chain segment               blocks=7 txs=736 mgas=33.587 elapsed=2.784s mgasps=12.064 number=4319274 hash=9d73e6…c55717
INFO [09-28|15:31:31] Imported new chain segment               blocks=1 txs=115 mgas=6.685  elapsed=774.229ms mgasps=8.634  number=4319275 hash=e3fcfa…9bb495
WARN [09-28|15:31:32] Head headers broke chain ordering        peer=01681ce954219901 index=0 requested=4319082 received=4319276
WARN [09-28|15:31:32] Synchronisation failed, dropping peer    peer=01681ce954219901 err="retrieved hash chain is invalid"
INFO [09-28|15:31:32] Imported new chain segment               blocks=1 txs=103 mgas=6.707  elapsed=352.836ms mgasps=19.007 number=4319276 hash=82a2f2…83377f
WARN [09-28|15:36:58] Synchronisation failed, dropping peer    peer=d897b67c2f6151c1 err="retrieved hash chain is invalid"
INFO [09-28|15:41:13] Imported new chain segment               blocks=6 txs=713 mgas=39.902 elapsed=8.123s    mgasps=4.912  number=4319282 hash=57b4c2…346a1f
INFO [09-28|15:41:21] Imported new chain segment               blocks=5 txs=864 mgas=31.111 elapsed=8.319s    mgasps=3.740  number=4319287 hash=b69c32…9eb6c5
INFO [09-28|15:41:26] Imported new chain segment               blocks=5 txs=467 mgas=31.539 elapsed=5.219s    mgasps=6.043  number=4319292 hash=dc73e1…16eb15
INFO [09-28|15:41:49] Imported new chain segment               blocks=1 txs=73  mgas=1.572  elapsed=232.453ms mgasps=6.761  number=4319293 hash=98abb6…87f234
INFO [09-28|15:42:31] Imported new chain segment               blocks=1 txs=40  mgas=2.307  elapsed=172.454ms mgasps=13.380 number=4319294 hash=e7e270…0fb4c3
INFO [09-28|15:42:41] Imported new chain segment               blocks=1 txs=42  mgas=1.187  elapsed=245.080ms mgasps=4.844  number=4319295 hash=051111…1cc44b

**Comment by bas-vk** [comment]
The fragment that you posted indicates that you did get a reply on `eth.syncing`, but it turned false. That is a good thing because you get either `false` which is an indication that your node has caught up with the chain, or a bunch of numbers indications how the synchronisation process is progressing. In the log that you posted you can see that your node is imported blocks one at a time which is usually also a good indication that your node has caught up with the chain and only imports new created blocks.

So everything is fine.

**Comment by abl1234** [comment]
thanks a lot for your help - im closing the ticket now .
best regards
A
