### ISSUE TITLE
Add chaindata and keystore directory management [Feature Request]

### ISSUE THREAD

**Issue by partsoven** [ethereum/go-ethereum#15217]
#### System information

Geth version: 1.70
OS & Version: Ubuntu 16.04

It would be great to have an easy way to change where the ethereum data chain is stored. You could prompt during installation, and also allow changing from within the app. I am running a modest cpu and the OS is on a flash drive. The flash drive is small, so I have a big external drive for my chaindata.

**Comment by bas-vk** [comment]
That is already possible. There are 2 options that you can take a look at.
1. `--datadir`, this specifies where geth will store chain data and the keystore (default inside the datadir)
2. `--keystore`, if you want to store your keys somewhere else you can use this flag to specify a custom location

**Comment by partsoven** [comment]
@bas-vk I know its possible through GETH but would be nice to see as a config in the GUI as well.

**Comment by karalabe** [comment]
You should open a ticket on the Mist repo. Geth is purely a command line
client.
