### ISSUE TITLE
help

### ISSUE THREAD

**Issue by vxnxn** [ethereum/go-ethereum#15218]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````
I'm not a coder! Etherscan.io says I have a contract worth money but I can't access it! Pls help pls email me 11001100xn@gmail.com

**Comment by bas-vk** [comment]
You don't have to be a coder. Probably the best option for you is to run Mist. Mist allows you to make transactions in a more user friendly way. You can find the latest release of Mist here https://github.com/ethereum/mist/releases.

**Comment by holiman** [comment]
If you want help, try the gitter-channel https://gitter.im/ethereum/go-ethereum. There are other channels aswell where people can help out.
