### ISSUE TITLE
JSON RPC - Unable to use Integer values

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#15228]
#### System information

Geth version: `1.7.0`
OS & Version: `Linux 64bit`

This is two part because I don't know if this is a bug or a feature request, or both...

First, when passing an integer string to Geth it does not understand that it is an integer unless it is in Hex. Parity works just fine:

#### Expected behaviour (Parity)
```
Input:
{
    "method":  "eth_getBlockTransactionCountByNumber",
    "params":  [
                   "4000000"
               ],
    "id":  0,
    "jsonrpc":  "2.0"
}

Output:
0x45
```

#### Actual behaviour (Geth)
```
Input:
{
    "method":  "eth_getBlockTransactionCountByNumber",
    "params":  [
                   "4000000"
               ],
    "id":  0,
    "jsonrpc":  "2.0"
}

Output:
WARNING: @{code=-32602; message=invalid argument 0: hex string without 0x prefix}
```

Additionally, if someone were to pass a raw integer as params[0] the error message would be incorrect. I think that not accepting a raw integer is by design (as both Geth and Parity reject it), but the error message is not accurate.

#### Example
```
Input:
{
    "method":  "eth_getBlockTransactionCountByNumber",
    "params":  [
                   4000000
               ],
    "id":  0,
    "jsonrpc":  "2.0"
}

Output:
WARNING: @{code=-32602; message=invalid argument 0: hex string without 0x prefix}
```

Parity also does not like an Integer being passed but the error message is more accurate:
```
WARNING: @{code=-32602; message=Invalid params: invalid type: integer `4000000`, expected a block number or 'latest', 'earliest' or 'pending
'.}
```

**Comment by bas-vk** [comment]
As you can see [here](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblocktransactioncountbynumber) `eth_getblocktransactioncountbynumber` expects a quantity or "earliest", "latest" or "pending" as argument. Quantities are always hex encoded strings, prefixed with `0x`. If parity accepts quanties without the `0x` prefix that is against the official spec. Geth used to be more relaxed but we decided to follow the spec more closely to prevent people running into these kind of issues.

**Comment by MysticRyuujin** [comment]
I see, yes, it does say "HEX String - an integer block number"

Ok, I can accept that as being to standard then.
