### ISSUE TITLE
[iOS] Unable to join Rinkeby. GethNode always defaults to Homestead

### ISSUE THREAD

**Issue by ronaldmannak** [ethereum/go-ethereum#15229]
#### System information

Geth version: `iGeth/v1.7.0-stable/darwin-arm64/go1.7.1`
OS & Version: iOS

#### Expected behaviour
When GethNodeConfig is set to network ID 4, Node will join the Rinkeby network.

#### Actual behaviour
Node will always join Homestead (id 1), no matter what id is passed to the ```setEthereumNetworkID``` method, as can be seen by the EthereumClient logs below.

````
INFO [10-03|00:52:55] Starting peer-to-peer node               instance=iGeth/v1.7.0-stable/darwin-arm64/go1.7.1
INFO [10-03|00:52:55] Allocated cache and file handles         database=/var/mobile/Containers/Data/Application/57A72FE9-C958-46F6-909B-C66200EF6573/Documents/iGeth/lightchaindata cache=16 handles=16
INFO [10-03|00:52:55] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 9223372036854775807 Engine: ethash}"
````

#### Steps to reproduce the behaviour

````
let config = GethNewNodeConfig()!
config.setEthereumNetworkID(4) // Rinkeby
var error: NSError?
gethNode = GethNewNode(NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first!, config, &error)
guard error == nil else { print(error!.localizedDescription) }
        
do {
    try gethNode.start()
    gethClient = try gethNode.getEthereumClient()
} catch { print(error) }
````

The code above will produce the log quoted above.

**Comment by ronaldmannak** [comment]
iOS version 11.0.1

**Comment by ligi** [comment]
Have you tried setting the genesis?

**Comment by karalabe** [comment]
The network ID is a networking related option, that can be used to separate multiple physical networks from one another. The chain id is a blockchain related option. It's a bit of a legacy that we have both of them, usually they are the same and should be set to the same, alas both. You'll need to set the genesis to Rinkeby if you want to joint that.

**Comment by ronaldmannak** [comment]
^^ Thanks both of you.

For future reference, this is the correct way of joining Rinkeby in Swift:

````
// Create node configuration
let config = GethNewNodeConfig()!
config.setEthereumNetworkID(4) // Doesn't matter, but best to set it to 4, Rinkeby
config.setEthereumGenesis(GethRinkebyGenesis()) // get Rinkeby genesis block

// Create node in Rinkeby directory so we can change networks on the fly if needed
var error: NSError?
gethNode = GethNewNode(NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first! + "/" + "Rinkeby", config, &error)

// Start node
try! gethNode.start()
gethClient = try! gethNode.getEthereumClient()
````
