### ISSUE TITLE
sar -q runq-sz > 2 should always be < 2

### ISSUE THREAD

**Issue by zbuckholz** [ethereum/go-ethereum#15223]
#### System information

Geth version: `geth version`
geth-linux-amd64-1.7.0-6c6c7b2a/geth version
Geth
Version: 1.7.0-stable
Git Commit: 6c6c7b2af3efdad4d2f64f70f3a724af434bbcd2
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.4
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Amazon Linux
Linux x.x.x.x 4.9.43-17.39.amzn1.x86_64 #1 SMP Fri Sep 15 23:39:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Commit hash : (if `develop`)

#### Expected behaviour

sar -q should always show runq-sz < 2 anything > 2 shows system processes (geth) stuck waiting for something and causing backup.

#### Actual behaviour

02:10:01 PM   runq-sz  plist-sz   ldavg-1   ldavg-5  ldavg-15
02:20:01 PM         2       142      3.38      3.46      3.02
02:30:01 PM         4       142      4.19      3.72      3.31
02:40:01 PM         3       142      3.62      3.71      3.53
02:50:01 PM         1       142      3.76      3.76      3.65
03:00:01 PM         0       142      0.70      1.52      2.54
03:10:01 PM         2       142      2.64      2.25      2.35
03:20:01 PM         5       142      3.53      2.98      2.62
03:30:01 PM         4       141      3.23      2.95      2.70
03:40:01 PM         0       142      0.68      1.36      2.02
03:50:01 PM         2       142      0.81      0.90      1.44
Average:            2       142      2.65      2.66      2.72

#### Steps to reproduce the behaviour

yum -y install sysstat
bake for an hour while running geth initial import
sar -q

CPU is idle because it's waiting for something to do, geth is blocking while waiting. 

top - 15:55:37 up  2:22,  4 users,  load average: 0.81, 0.73, 1.17
Tasks: 119 total,   1 running, 118 sleeping,   0 stopped,   0 zombie
Cpu(s):  6.4%us,  0.7%sy,  0.0%ni, 92.8%id,  0.1%wa,  0.0%hi,  0.1%si,  0.0%st
Mem:  62882944k total, 28947816k used, 33935128k free,   157912k buffers
Swap:        0k total,        0k used,        0k free, 26499960k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                     
 5784 root      20   0 5644m 1.0g  84m S 29.9  1.7 287:08.44 geth        

What other information can I provide to help find cause?

Thanks

#### Backtrace

````
[backtrace]
````

**Comment by bas-vk** [comment]
> bake for an hour while running geth initial import

With initial import you mean that geth is catching up with the chain through a network sync? Or do you load the chain from a file with `geth import <dump>`? Currently syncing from scratch over the network will take much longer than 1 hour in my experience. 

The first way to determine what geth is doing is to check the logs. If you don't see any import activity you could check if geth is connected with the network and syncing. From the shell `geth attach -exec admin.peers` dumps a list of peers that geth is connected to. And `geth attach -exec eth.syncing` shows if geth is currently importing blocks/state.

If you don't now where to look for copy the last 20 lines of the log together with the output of the above commands in a gist and link it here.
