### ISSUE TITLE
[iOS] syncProgress always throws a 'nilError' exception

### ISSUE THREAD

**Issue by ronaldmannak** [ethereum/go-ethereum#15230]
#### System information

Geth version: `iGeth/v1.7.0-stable/darwin-arm64/go1.7.1`
OS & Version: iOS 11.0.1

#### Expected behaviour
Expecting syncProgress(context) method of GethEthereumClient to return a new GethSyncProgress instance.

#### Actual behaviour
The syncProgress method consistently throws a 'nilError' exception

#### Steps to reproduce the behaviour

````
let config = GethNewNodeConfig()!
config.setEthereumNetworkID(1) // Homestead Main Network
var error: NSError?
let gethNode = try! GethNewNode(NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first!, config, &error)
try! gethNode.start()
let gethClient = try! gethNode.getEthereumClient()
````

After a pause...

````
do {
    let progress = try gethClient.syncProgress(GethNewContext())
} catch {
    print(error) // "nilError"
}
````

**Comment by 92161898515** [comment]
👍

**Comment by ronaldmannak** [comment]
It turns out you shouldn't try to catch the exception, but just check if syncProgress returns nil, like so:

````
let progress = try? gethEthereumClient.syncProgress(GethNewContext())
````

Instead of ````- (GethSyncProgress*)syncProgress:(GethContext*)ctx error:(NSError**)error;```` which will be translated in Swift as ````func syncProgress(ctx: GethContext) throws -> GethSyncProgress````, the correct declaration should be: 

````
- (nullable GethSyncProgress*)syncProgress:(GethContext*)ctx;
````

which will be translated into swift as ````func syncProgress(ctx: GethContext) -> GethSyncProgress?````
