### ISSUE TITLE
swarm apis add support for ens resolver

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#15238]
the http api server should support a resolver 
Any domain or path, it would return the hash not the content

we could implement it as a separate url scheme.

    bzzh://swarm.eth/optional/path/to/asset

the functionality should be supported by rpc too

**Comment by lmars** [comment]
I think a query param makes sense, I don't think this warrants being its own "protocol".

**Comment by zelig** [comment]
sorry @lmars everyone else voted bzzh :)

**Comment by lmars** [comment]
Ha ok, seems like I missed the vote, but I still question whether a varied response (i.e. either return the content or the hash) is worthy of being a completely separate "protocol".

Whatever we choose, I think we should be consistent (for example we already request a varied "list" response with a query parameter `list=true`, should that instead be `bzzl://`?).

**Comment by homotopycolimit** [comment]
I suggest we should we close this issue here since we now have bzz-hash scheme implemented.
We can continue to discuss on ethersphere issue 580.
