### ISSUE TITLE
How to...

### ISSUE THREAD

**Issue by dinkeltje** [ethereum/go-ethereum#15239]
Hello world, 

I got some problem... 

Few months ago, i had a ethereum wallet + few ethereums on it. 
But then i reset my laptop and now i deleted also all passwords and files... 

Is there any change to get back my wallet and the eth i have on it? 

This is the only thing i see now. 
<img width="572" alt="schermafbeelding 2017-10-03 om 23 08 03" src="https://user-images.githubusercontent.com/19479418/31149773-5f33d5d8-a891-11e7-91ad-b3ee9c1133a3.png">

**Comment by RichHorrocks** [comment]
Ideally ask technical questions on https://ethereum.stackexchange.com - it's important to keep issue trackers clear and for real issues only.

(You'll probably find that this question has been asked before on Stack Exchange.)

**Comment by dinkeltje** [comment]
Thanks a lot!

**Comment by ligi** [comment]
@dinkeltje ideally close the issue and follow the advice of @RichHorrocks
