### ISSUE TITLE
[iOS] GethKeyStore `newAccount` throws because of `mkdir` error

### ISSUE THREAD

**Issue by svdo** [ethereum/go-ethereum#15245]
#### System information

Geth version: 1.7.1-unstable.11080 via CocoaPods
OS & Version: iOS

#### Expected behaviour
I have an iOS app that creates a `GethKeyStore` on initial launch. I then create a new account, which works fine. I then relaunch the app. The key store is recreated using the same parameters as before. Again, I create a new account. I expect it to work, just like the first time.

#### Actual behaviour
On iPhone Simulator, it does in fact work. However, on a physical phone, I get the following error message:

`Action:  Rejected(message: "mkdir /var/mobile/Containers/Data/Application/71AE95D3-F86F-4789-9C10-030ADDDB580D: operation not permitted")`

The directory itself is correct, it is the directory of my application. It is the same one as was used for the first (successful) account creation. Is this maybe because you're not allowed to create anything inside `/var/mobile/Containers/Data/Application` because that's outside of the sandbox?

#### Steps to reproduce the behaviour
1. Create a key store:
   ```
               let documentsDirectory = NSSearchPathForDirectoriesInDomains(.documentDirectory,
                                                                            .userDomainMask,
                                                                            true)[0]
               let keyStore = GethKeyStore(path: documentsDirectory + "/main.keystore",
                                       scryptN: GethStandardScryptN / 4,
                                       scryptP: GethStandardScryptP)
   ```

2. Create a new account:
   ```
                   do {
                       let gethAccount = try gethKeyStore.newAccount(p)
                   } catch let e {
                       // handle exception
                   }
   ```

3. Note that no exception is thrown. Also, when inspecting the app container, it can be verified that the account is indeed created in the folder `main.keystore`.

4. Restart the app
5. Again cause the key store to be created, and call the `newAccount` function.
6. Note that this time an exception is thrown.

#### Backtrace
N/A

P.S. On a side note: where is the best place to talk to people about Geth iOS framework? I'm not getting a lot of response in Gitter (ethereum/light-client)...

**Comment by ronaldmannak** [comment]
@svdo I'm not able to reproduce your error. I've tried using 1.7.0 and 1.7.1 and don't see the error message you described.

I've used your code with added password and renamed keystore to gethKeyStore to make the code run. I've also checked using my own code below, which also works as advertised.

````
let dir = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first! + "/main.keystore"
let keystore = GethNewKeyStore(dir, GethStandardScryptN, GethStandardScryptP)
do {
    let account = try keystore?.newAccount("test")
} catch {
    print(error)
}
````

**Comment by svdo** [comment]
I'll try with 1.7.1 today and post an update.

**Comment by svdo** [comment]
I just tried again with Geth 1.7.1, and it still fails (both on my iPhone 6 and an iPhone SE). Just to double-check, @ronaldmannak, does this match your test?

- Physical phone, not iOS simulator
- iOS 11.0.1
- Geth 1.7.1 via CocoaPods (not downloaded directly or something)
- Test scenario: first time it succeeds, then re-rerun the app from Xcode and retry, only then it fails

**Comment by ronaldmannak** [comment]
I'm running iOS 11.0.2 but it's otherwise the same setup. If you're able to share your project, I'd be happy to look at it.

**Comment by svdo** [comment]
I found the issue. It is in my own code, not in Geth. Problem was that I was persisting the absolute path to the keystore between launches of my app. Apparently, starting with iOS 8 this path changes every time, must be a sandbox security thing I guess. Thanks a bunch for trying to reproduce this on your end!
