### ISSUE TITLE
Intermittent JSON RPC

### ISSUE THREAD

**Issue by vogelito** [ethereum/go-ethereum#15243]
#### System information

Geth version: (this spans two versions of geth 1.7.0 and 1.7.1, see below for more background)
```
Geth
Version: 1.7.1-stable
Git Commit: 05101641455a754936acc5ddff92f35f5e33181c
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```
OS & Version: Linux

#### Expected behaviour
JSON RPC should respond to requests

#### Actual behaviour
**While running 1.7.0**:
At 19:16 UTC on October 4th, 2017, we started getting erratic responses from geth's JSON RPC. It basically just failed to respond. We were able to consistently reproduce by calling `eth_getBalance` for random addresses in a loop: geth was intermittent at responding.

Roughly at 19:46 UTC on October 4th, 2017 the problems subsided and geth's jsonRPC started acting normally again. We didn't see any problems until....

At 01:20 UTC on October 5th, 2017 we **updated to geth 1.7.1**. Immediately after updating we started seeing erratic behavior from geth's JSON RPC while under normal operations. We have been unable to pinpoint what is exactly the problem, but downgrading to 1.7.0 seems to have helped.

#### Steps to reproduce the behaviour
Uncertain at this point.

#### Backtrace

````
[backtrace]
````

**Comment by vogelito** [comment]
We just added logic to retry when there are errors and sleep in between retries. This seems to ahve really helped, but still worth mentioning the problem.

**Comment by axelay** [comment]
I can confirm we have also seen erratic behaviour after upgrading directly to 1.7.1 (we were using the version prior to 1.7.0). Nothing that can be repeated constantly but we have had transactions sent that didn't give transaction ID and when that's the case, the code should display the error that occured. We had a few "authentication needed: password or unlock" - but before you tell me that the account needs to be unlocked, the code has not changed and we only saw this error since the upgrade to 1.7.1.
Some other times we simply had no error, leading me to believe the script ended abruptly.

Nothing in the geth logs for any of these occurrences.

**Comment by holiman** [comment]
Would be interesting to know more about the error. I'd expect there to be a json rpc error response, containing more details about the error. 
Can you check if you are logging error-messages returned by the API, @vogelito ?

**Comment by karalabe** [comment]
Perhaps the node was overloaded disk wise? 1.7.x does a database upgrade that can be quite heavy, especially if done under a production server that also hammers the disk.

**Comment by axelay** [comment]
We had the "deduplicating database entries" running at the same time - could it be related?

**Comment by karalabe** [comment]
That is very heavy on the disk, yes.

**Comment by axelay** [comment]
Ok that would explain our issue - however @vogelito was running 1.7.0 for a while so his situation is different. Ours is running fine at the moment but will keep an eye on things. Thanks

**Comment by jyap808** [comment]
Can confirm seeing lots of issues with account unlock and failing RPC with 1.7.1.

1.7.0 working without issues.

**Comment by karalabe** [comment]
1.7.1 contains just a handful of bugfixes, none whatsoever touches account handling. Could you please provide some additional infos on what "failing" consists of?

**Comment by jyap808** [comment]
Similar to what is reported above.

1.7.1 is considered unusable with the RPC issues. /me represents one of the larger exchanges.

Is this commit sufficient to back port?
https://github.com/ethereum/go-ethereum/commit/7514e8a24d3dc332e58be4b26f893aff8c24a9e7

**Comment by karalabe** [comment]
You'll need the gas estimation fix https://github.com/ethereum/go-ethereum/pull/15030 and the log filter fix https://github.com/ethereum/go-ethereum/pull/15195 too at least.

That being said, I'm really missing what might happen, would really appreciate actual logs or detailed behavior. Saying "similar to above" doesn't really help us debug the issue.

**Comment by karalabe** [comment]
@vogelito I've written the following test script to try and hit the error, but the RPC (at least on the IPC channel) seems to be responding properly on the latest code:

```go
package main

import (
	"context"
	"fmt"
	"math/rand"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	client, err := ethclient.Dial("/work/temp/mainnet/geth.ipc")
	if err != nil {
		panic(err)
	}
	for i := 0; ; i++ {
		var addr common.Address
		for j := 0; j < common.AddressLength; j++ {
			addr[j] = byte(rand.Int())
		}
		if balance, err := client.BalanceAt(context.Background(), addr, nil); err != nil {
			panic(err)
		} else {
			fmt.Println(i, addr.Hex(), balance)
		}
	}
}
```

Stopped it after 200.000 random account balance retrievals.

**Comment by karalabe** [comment]
Executed the same test on both HTTP RPC and WebSocket RPC, both functioned properly until I terminated them after 100K iterations.

**Comment by karalabe** [comment]
Next test, open an HTTP, WS and IPC connection simultaneously, and on the three connections, concurrently from 64 threads hammer the node with requests. Still no failure, node replies to everything:

```go
package main

import (
	"context"
	"fmt"
	"math/rand"
	"runtime"
	"sync"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
)

const threads = 64

func main() {
	runtime.GOMAXPROCS(threads)

	// Dial in on all known RPC interfaces
	ipc, err := ethclient.Dial("/work/temp/mainnet/geth.ipc")
	if err != nil {
		panic(err)
	}
	http, err := ethclient.Dial("http://localhost:8545")
	if err != nil {
		panic(err)
	}
	ws, err := ethclient.Dial("ws://localhost:8546")
	if err != nil {
		panic(err)
	}
	clients := []*ethclient.Client{ipc, http, ws}

	// Hammer all the interfaces concurrently on a ton of threads
	var pend sync.WaitGroup
	for t := 0; t < threads; t++ {
		pend.Add(1)

		go func(index int) {
			defer pend.Done()

			for i := 0; i < 100000/threads; i++ {
				var addr common.Address
				for j := 0; j < common.AddressLength; j++ {
					addr[j] = byte(rand.Int())
				}
				if balance, err := clients[rand.Intn(len(clients))].BalanceAt(context.Background(), addr, nil); err != nil {
					panic(err)
				} else {
					fmt.Printf("Thread %2d, request %4d: %s -> %d\n", index, i, addr.Hex(), balance)
				}
			}
		}(t)
	}
	pend.Wait()
}
```

**Comment by vogelito** [comment]
@holiman apologies for the late reply. It's been a hectic day.

We log all responses from geth but this time there are no errors being returned by the JSON RPC - it just fails to respond and drops the connection. I can confirm that I had been running 1.7.0 for days (so we had already done the db upgrade) without issues and **we first saw the error while still on 1.7.0**. Upgrading to 1.7.1 seems to have made it worse so we returned to 1.7.0 and the problem went away.

For the past 12 hours we have been running 1.7.1 again and have not seen the error once.

Looking at our disk latency graphs, I can confirm that these errors are 100% correlated with disk latency issues and unusually high outbound network traffic. The only thing we are running on this box is geth.

<img width="1153" alt="screen shot 2017-10-05 at 11 18 21 pm" src="https://user-images.githubusercontent.com/1325863/31263333-2eb2d84a-aa27-11e7-8846-08fa2708e653.png">

Digging through the geth logs I don't see anything unusual around the times of the high latency... 

@karalabe - I can no longer reproduce the connection drops.

**Comment by vogelito** [comment]
Here are my disk latency graphs for:

past month (you can see the db upgrade on the 17th):
<img width="573" alt="screen shot 2017-10-05 at 11 49 49 pm" src="https://user-images.githubusercontent.com/1325863/31263472-0b811458-aa28-11e7-9c5c-30e9ca321d18.png">

Past week:
<img width="577" alt="screen shot 2017-10-05 at 11 50 05 pm" src="https://user-images.githubusercontent.com/1325863/31263485-21231afe-aa28-11e7-9027-713b8d0a0a8d.png">

Past 2 days:
<img width="572" alt="screen shot 2017-10-05 at 11 50 16 pm" src="https://user-images.githubusercontent.com/1325863/31263492-29d5a70c-aa28-11e7-9f55-ea9d5ffa4804.png">

Past 24 hours:
<img width="578" alt="screen shot 2017-10-05 at 11 50 29 pm" src="https://user-images.githubusercontent.com/1325863/31263497-30661b92-aa28-11e7-85fe-34b300b566da.png">

We're still working on our data collection/monitoring infrastructure, but the data points are currently getting interpolated so they lose resolution as we increase the time windows.

**Comment by holiman** [comment]
Those who are having problems; do you have massive number of wallet/accounts? I'm curious if this is related to https://github.com/ethereum/go-ethereum/issues/14810

**Comment by vogelito** [comment]
What is massive? We have in the low hundreds of thousands.

**Comment by holiman** [comment]
Yeah, that's pretty massive. Could it be that you were creating new accounts when you ran into these issues? (either through the RPC or by placing new files within the `keystore`) .

The issues may be timeouts on the socket connections. I still think there should be some caller-side exception telling you what occurred though, but not a json rpc error message.

**Comment by axelay** [comment]
We do also log all the responses coming out of Geth and that's how I got the few errors about the unlocking of accounts. However, in some instances, we received nothing from Geth at all. As @vogelito mentioned, it looks as though the connection was simply dropped.

It all happened on the 4th starting at roughly 13:50 UTC - right after the upgrade to 1.7.1 - so disk usage was high due to the database migration. However, this fact is inconsistent with Daniel's issue as he was on 1.7.0 and had done the DB upgrade on the 17th of September.

I am happy to report that we have had no issues at all for at least 36 hours now.

**Comment by axelay** [comment]
As far as we are concerned, we have about 30K accounts on our system - don't think that's considered massive.

**Comment by vogelito** [comment]
The problem repeated this morning at 8:19AM local time (see graphs below).
I can confirm that no new accounts were being created.
Attaching graphs. I'm beginning to think it's actually a CPU issue.

<img width="569" alt="screen shot 2017-10-06 at 10 08 57 am" src="https://user-images.githubusercontent.com/1325863/31284624-bae67e14-aa7e-11e7-8c04-4955c1f60789.png">
<img width="568" alt="screen shot 2017-10-06 at 10 08 46 am" src="https://user-images.githubusercontent.com/1325863/31284626-bae7ab0e-aa7e-11e7-884c-def3eeb08247.png">
<img width="562" alt="screen shot 2017-10-06 at 10 08 32 am" src="https://user-images.githubusercontent.com/1325863/31284623-bae6674e-aa7e-11e7-8d1b-93e67544fbf6.png">
<img width="567" alt="screen shot 2017-10-06 at 10 08 19 am" src="https://user-images.githubusercontent.com/1325863/31284625-bae6f5ce-aa7e-11e7-880a-fba073848d6c.png">
<img width="574" alt="screen shot 2017-10-06 at 10 08 06 am" src="https://user-images.githubusercontent.com/1325863/31284627-baefe378-aa7e-11e7-96f6-a73daf0b50f3.png">
<img width="570" alt="screen shot 2017-10-06 at 10 07 42 am" src="https://user-images.githubusercontent.com/1325863/31284628-baf1ca6c-aa7e-11e7-8d63-f9fab8cb40b1.png">

The geth log at the time we started noticing errors only shows `Imported new chain segment` and  `Submitted transaction` messages in no unusual manner.

**Comment by vogelito** [comment]
We *just* upgraded to 1.7.2 and we're seeing an important spike of intermittency with the JSON RPC. CPU and load increased importantly and matches time of upgrade:

<img width="574" alt="screen shot 2017-10-14 at 8 36 26 am" src="https://user-images.githubusercontent.com/1325863/31576152-e1f675bc-b0ba-11e7-9c13-954e394e9102.png">

**Comment by vogelito** [comment]
Is there peering preference for same version nodes? Our bytes sent metric has 200x'ed since updating the node (we updated very soon after geth release).

<img width="571" alt="screen shot 2017-10-14 at 8 40 33 am" src="https://user-images.githubusercontent.com/1325863/31576180-7552d95e-b0bb-11e7-972d-c7c2a2df9d3d.png">

This could explain why last time downgrading to 1.7.0 seems to have helped. Once we went back to 1.7.1 there were probably enough nodes that ours wasn't particularly overloaded.

**Comment by vogelito** [comment]
Just FYI - 1.7.x seems to be a lot more CPU intensive. The spike in CPU matches exactly our upgrade to 1.7.0

<img width="576" alt="screen shot 2017-10-14 at 8 47 21 am" src="https://user-images.githubusercontent.com/1325863/31576249-6ed431b2-b0bc-11e7-8f33-5d8c4f7ffe7e.png">

**Comment by Gerryrulz** [comment]
Not as pretty as @vogelito but I think it speaks for itself. Server was down about 30s time to stop and start the new compiled code.
![geth - 3 hours](https://user-images.githubusercontent.com/6663671/31579514-ee3027a4-b12f-11e7-9ad9-351dcc7d5b47.png)
![geth - 1 hour](https://user-images.githubusercontent.com/6663671/31579513-ee16587e-b12f-11e7-9b64-b2898a7d029f.png)

**Comment by axelay** [comment]
Not as pretty as @vogelito but I think it speaks for itself. Server was down about 30s time to stop and start the new compiled code.
![geth - 3 hours](https://user-images.githubusercontent.com/6663671/31579514-ee3027a4-b12f-11e7-9ad9-351dcc7d5b47.png)
![geth - 1 hour](https://user-images.githubusercontent.com/6663671/31579513-ee16587e-b12f-11e7-9b64-b2898a7d029f.png)

**Comment by holiman** [comment]
What `cache` option are you using? 

It takes a while before the cache "gets warm". And larger cache means that it takes longer before it reaches it's maximum 'warmth', where it probably was right before you switched off the node. 

Please let us know how it looks after some time has passed; a few hours, or a day or so.

**Comment by axelay** [comment]
--cache 3072
And yes, it has now settled back down and is running smoothly.

**Comment by vogelito** [comment]
`--cache 1024`

CPU/load seems much higher in `1.7.x`

Last 2 months CPU/load:
<img width="578" alt="screen shot 2017-10-14 at 10 26 17 pm" src="https://user-images.githubusercontent.com/1325863/31583885-95ad4f88-b168-11e7-8f0a-40aed0be122d.png">

Disk latency seems much better (the spike is the upgrade):
<img width="571" alt="screen shot 2017-10-15 at 5 22 11 am" src="https://user-images.githubusercontent.com/1325863/31583895-d5e00cd0-b168-11e7-964b-4986f7094635.png">

To compare with the graphs above, this is the last hour graph for CPU/load (still on `1.7.2`):
<img width="559" alt="screen shot 2017-10-15 at 5 24 01 am" src="https://user-images.githubusercontent.com/1325863/31583913-31327da2-b169-11e7-91bf-b2d06756ddaa.png">

**Comment by vogelito** [comment]
We're no longer seeing this issue, so closing.
