### ISSUE TITLE
[iOS] GethBigInt integer overflow does not throw an exception.

### ISSUE THREAD

**Issue by ronaldmannak** [ethereum/go-ethereum#15244]
#### System information

Geth version: `iGeth/v1.7.0-stable/darwin-arm64/go1.7.1`
OS & Version: iOS

#### Expected behaviour

When fetching balances of addresses, getBalanceAt() returns a GethBigInt. I expect to receive the balance in WEI when invoking getInt64() on the GethBigInt instance. In case an integer overflow occurs, I expect getInt64() to either throw an exception of to return nil. 

Alternatively, I can imagine a custom integer class that's big enough to store large amounts in WEI, or the amounts being returned as a double in ETH or GWEI for example.

#### Actual behaviour

For small wallets, the right amount will be returned. For larger amounts (like the 21.7 ETH in the example above), an integer overflow occurs and instead of 21734488100000000000 (WEI), the getInt64() method returns 3287744026290448384 (WEI) without throwing an exception or returning a nil, to indicate that an integer overflow occurred.

#### Steps to reproduce the behaviour
````
// Create node configuration
let config = GethNewNodeConfig()!
config.setEthereumNetworkID(4) // Doesn't matter, but best to set it to 4, Rinkeby
config.setEthereumGenesis(GethRinkebyGenesis()) // get Rinkeby genesis block

// Create node in Rinkeby directory so we can change networks on the fly if needed
var error: NSError?
let gethNode = GethNewNode(NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first! + "/" + "Rinkeby", config, &error)

// Start node
try! gethNode.start()
gethClient = try! gethNode.getEthereumClient()

// Find balance of testnet ETH address with 21.7344881 ETH.
var error: NSError?
let address = GethNewAddressFromHex("0xb81Df5747f39bfD5ce9410F1Be9B02851B0cbd6E", &error)
let balance = try! gethClient.getBalanceAt(GethNewContext(), account: address!, number: 0)
print("Balance: \(balance.getInt64())") // "Balance: 3287744026290448384" Expected: 21734488100000000000 (Wei)
````

**Comment by karalabe** [comment]
Yep, you are correct. The API was built analogous to Go's [`big.Int.Int64`](https://golang.org/pkg/math/big/#Int.Int64), however I missed adding the [`big.Int.IsInt64`](https://golang.org/pkg/math/big/#Int.IsInt64) counterpart method.

That being said, perhaps it's cleaner to return an error (exception) from `getInt64` rather then adding another method here. Will think about this a bit, thanks for the report!

**Comment by ronaldmannak** [comment]
Thanks Péter. Do I understand correctly that the original Go version also returns an Int64? The very existence of the getInt64() method is slightly confusing. The correct way of using GethBigInt (at least for Swift/ObjC) would be to never use getInt64(), and instead use the string() method. 

The returned string can then either be manipulated directly (that wouldn't be my preferred way) or convert the string into a custom Uint256 or BigInt type and generate. 

Is there any reason the getInt64() method should be kept in GethBigInt? Even if the method would throw an exception, integer overflows will happen regularly and only those with really good unit tests would catch it. It might make sense to simply remove the method or at least make it internal if it's needed internally. (Just a thought)

Relevant Twitter discussion [here](https://twitter.com/chriseidhof/status/915956523033088000)

**Comment by ronaldmannak** [comment]
Related, GethNewBigInt also takes an Int64 as parameter.

````
/**
 * NewBigInt allocates and returns a new BigInt set to x.
 */
FOUNDATION_EXPORT GethBigInt* GethNewBigInt(int64_t x);
````

Which, again, is unsafe. The only correct way to set a GethBigInt (using [BigInt](https://github.com/attaswift/BigInt)) that I'm aware of is to set GethBigInt to 0 initially and then set the stringValue:

````
let reallyBigNumber = "21734488100000000000"
guard let bigInt = BigInt(reallyBigNumber), let gethBigInt = GethNewBigInt(0) else { return }
// bigInt = 21734488100000000000, gethBitInt = 0
gethBigInt.setString(bigInt.description, base: 10)
// bigInt = 21734488100000000000, gethBitInt = 21734488100000000000
````

It works, but it cumbersome. To prevent people from using GethNewBigInt with an Int64, it would make sense to either make the method private, or change it in:

````
FOUNDATION_EXPORT GethBigInt* GethNewBigInt(NSString *x);
````
