### ISSUE TITLE
Is there a passphrase support for Trezor?

### ISSUE THREAD

**Issue by ncsolar** [ethereum/go-ethereum#15256]
#### System information

Geth version: v1.7.1
OS & Version: OSX

#### Expected behaviour
To be able to enter passphrase for Trezor hardware wallet

#### Actual behaviour
I can't find the command to enter the passphrase when prompted by the Trezor after entering the pin number

#### Steps to reproduce the behaviour
Run personal.listWallets
Run personal.openWallet("trezor: url")
Enter pin number

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Currently there's no support for the passphrase as I wasn't aware it's actually a commonly used feature. I'll try to find the time to implement it.

**Comment by ncsolar** [comment]
Hi, thanks for the hard work!

**Comment by nikhil93uf** [comment]
Thanks for all the work you've put in @karalabe! Is there any update on this? Passphrases on Trezor are quite useful

**Comment by lelikalf** [comment]
type

**Comment by adamschmideg** [comment]
Password support added in https://github.com/ethereum/go-ethereum/pull/16503.
