### ISSUE TITLE
Questions about state tree pruning

### ISSUE THREAD

**Issue by thpun** [ethereum/go-ethereum#15253]
In current `geth`, how long (in terms of blocks) will a state tree node put into the death row before being pruned? Does this vary among different sync mode? And can we configure it?

Besides state trees are pruned, will blocks/ transactions/ transaction receipts be 'pruned' after certain period of time? Or do they persist unless i re-sync the client?

**Comment by RichHorrocks** [comment]
Ideally ask technical questions on https://ethereum.stackexchange.com - it's important to keep issue trackers clear and for real issues only.

**Comment by thpun** [comment]
Ok. Asking in https://ethereum.stackexchange.com/questions/27903/questions-about-state-tree-pruning
