### ISSUE TITLE
Shh_post invalid id result

### ISSUE THREAD

**Issue by hacktar** [ethereum/go-ethereum#15258]
#### System information

Geth version: `<= 1.7.1 `
OS & Version: Windows/Linux/OSX

#### Expected behaviour
shh.post a message

#### Actual behaviour
shh.post message with symkey receive invalid id result

#### Steps to reproduce the behaviour
Request:
````
{
	"jsonrpc": "2.0",
	"id": 22,
	"method": "shh_post",
	"params": [{
		"symKeyId": "6d328fba5e63f59d27e56fe5a37aa6862b8da0571b4443340c0d12c6bf0430ec",
		"ttl": 20,
		"sig": "0x0478205537d216a03419e06c9fc060cec833b85db56736298007315a268743def3c32c96ae3ad053af4ce1687a413815d80528b71d6132c6dba2eeea732013ed89",
		"topic": "0xb60cbc19",
		"payload": "0x73656e642073796d6d6574726963616c6c7920656e637279707465642c207369676e6564206d65737361676520286e6f646531202d3e206e6f64653129",
		"powTime": 3,
		"powTarget": 0.1
	}]
}
````
Result:
````
{
	"jsonrpc": "2.0",
	"id": 22,
	"error": {
		"code": -32000,
		"message": "invalid id"
	}
}
````
#### Comments

````
Which id? 
Could we have a working example with symkey, even for unencrypted message?
````

**Comment by nkbai** [comment]
this error means geth cannot find private key to encrypt your message.

**Comment by nkbai** [comment]
var identities = [];
var subscription = null;

Promise.all([
    web3.shh.newSymKey().then((id) => {identities.push(id);}),
    web3.shh.newKeyPair().then((id) => {identities.push(id);})]

).then(() => {

    // will receive also its own message send, below
    subscription = shh.subscribe("messages", {
        symKeyID: identities[0],
        topics: ['0xffaadd11']
    }).on('data', console.log);

}).then(() => {
   shh.post({
        symKeyID: identities[0], // encrypts using the sym key ID
        sig: identities[1], // signs the message using the keyPair ID
        ttl: 10,
        topic: '0xffaadd11',
        payload: '0xffffffdddddd1122',
        powTime: 3,
        powTarget: 0.5
    })
});

**Comment by REPTILEHAUS** [comment]
Hitting this error too, any luck resolving it ?
