### ISSUE TITLE
A docker tutorial to help beginners

### ISSUE THREAD

**Issue by gregbkr** [ethereum/go-ethereum#15262]
Hello Ethereum team,

Not sure who to contact, but if it can help the community, here is a step by step github [guide](https://github.com/gregbkr/geth-truffle-docker) and [blog](https://greg.satoshi.tech/deploy-your-first-smart-contract-with-this-base-ethereum-truffle-setup/) on how to use Geth+Truffle in docker, and how to deploy and interact with few easy smart contracts (greeter, metacoin, counter). 

I am maintaining it for the Geneva Dev [meetup](https://www.meetup.com/Geneva-DevChain-UserGroup/) team, where we on-board new comers every months. 

Feel free to close this issue.

Thank you for any feedback and very good week!
Keep up the good/awesome work! 
Greg.

**Comment by RichHorrocks** [comment]
Hi there. It'd probably be better to post updates like this on one of the Reddit boards, as they get more exposure that the issue tracker.

- https://www.reddit.com/r/ethereum

- https://www.reddit.com/r/ethdev/

- Maybe even https://www.reddit.com/r/ethtrader
