### ISSUE TITLE
Sync System Clock

### ISSUE THREAD

**Issue by Giusepp3** [ethereum/go-ethereum#15260]
<img width="1280" alt="schermata 2017-10-07 alle 16 11 48" src="https://user-images.githubusercontent.com/3754641/31308646-8299cfaa-ab7a-11e7-8ac7-310b8b17726d.png">
#### System information

Geth version: `1.7.1`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour

It says me to sync the system clock... but it is already settled to auto update!

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
@evertonfraga ?

**Comment by evertonfraga** [comment]
That was an `os-timesync` package issue, and now it's up for review: https://github.com/ethereum/mist/pull/3146

**Comment by Giusepp3** [comment]
okok thanks

Giuseppe Ferrara

**Comment by sensware** [comment]
I recommend changing the message to include the command line to sync time 
`sudo ntpdate -u time.apple.com`

**Comment by bas-vk** [comment]
A fix is merged in the mist repo.
