### ISSUE TITLE
Etherite fork

### ISSUE THREAD

**Issue by sayyesman** [ethereum/go-ethereum#15268]
# FEATURE REQUEST

Please add support for the Etherite fork, so us miners get a chance to have an opportunity for a fair split.

https://www.reddit.com/r/Etherite/comments/75bttb/what_is_etherite_and_how_to_help_out/

Thanks!

**Comment by karalabe** [comment]
As with previous forks, our policy is that we do not have the capacity to maintain different version of our codebase for different use cases. Given the open source nature of Ethereum and go-ethereum, anyone is free to create their own version of the code and the network to their pleasing. However anyone wishing to fork off into their own ruleset should also assume the responsibility of maintaining their project.

**Comment by wjcloud** [comment]
@karalabe I think he said it right.
