### ISSUE TITLE
Unale to locate transaction history

### ISSUE THREAD

**Issue by Jigsonly** [ethereum/go-ethereum#15276]
Hi,
I have sent Mcaps to an address with Transaction ID 0x43a9aeec4b3d516270262caab6a3a5abdc98423f9cf6de07251cbaf1b3d408fb
when i see the explorer, it says "Sorry, We are unable to locate the Transaction entry"

what can be done and what happened to this transaction. Kindly suggest me how to recover it as I have sent from exchange, when it will be credited in destination address
![screenshot-2017-10-11 ethereum transaction 0x43a9aeec4b3d516270262caab6a3a5abdc98423f9cf6de07251cbaf1b3d408fb](https://user-images.githubusercontent.com/32705457/31439421-b3023858-aea9-11e7-9ee6-f2ebb9f5102b.png)

**Comment by RichHorrocks** [comment]
The transaction is now showing up on Etherscan - please check again.

Also note the disclaimer at the bottom of the page. It's likely the transaction hadn't yet reached them. (I'm unsure how congested the network is today... )

(I'd suggest closing this issue, unless you have further queries.)

**Comment by karalabe** [comment]
https://etherscan.io/tx/0x43a9aeec4b3d516270262caab6a3a5abdc98423f9cf6de07251cbaf1b3d408fb
