### ISSUE TITLE
I have some question about light sync?

### ISSUE THREAD

**Issue by cytl5yy** [ethereum/go-ethereum#15273]
if my mobile node is light node ,i can only sync data from the light node  ,can't sync data from full node?  who can tell me a accurate answer.  thanks!

**Comment by kelsos** [comment]
By default a full node doesn't serve light clients, you need to explicitly enable the light server mode when you start geth with the following option:
```  
--lightserv value                  Maximum percentage of time allowed for serving LES requests (0-90) (default: 0)
```

**Comment by cytl5yy** [comment]
thanks, another problem , the light sync mode , does the client download the account information synchronously（state sync）?  if not ，when i want to check balance for account，i need to get it from other full node？

**Comment by RichHorrocks** [comment]
Ideally ask technical questions on https://ethereum.stackexchange.com - it's important to keep issue trackers clear and for real issues only.

(This question has certainly been asked before on Stack Exchange.)
