### ISSUE TITLE
Fresh data-dir, personal.newAccount, no coinbase?

### ISSUE THREAD

**Issue by linagee** [ethereum/go-ethereum#1527]
I'm running geth 1.0.0+696SNAPSHOT20150725202935trusty-0ubuntu1 on Ubuntu 14.04
I'm using a fresh data-dir, tried miner.start(), it said "Cannot start mining without etherbase address", so I did personal.newAccount("blah"). Then I typed eth.coinbase and it returns nothing.
If I make a new account from the command line using geth account new (?), eth.coinbase is populated the next time I run geth.
Should we be populating eth.coinbase after personal.newAccount("blah") on the first address created?

**Comment by bas-vk** [comment]
This is fixed in #1533
