### ISSUE TITLE
the withdraw thats over due

### ISSUE THREAD

**Issue by jackpot1136** [ethereum/go-ethereum#15279]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Steps to reproduce the behaviour
Hey Boss,
   Sorry to bother you again but this is that special head case that just can't get that damn withdraw to go through. I appreciate all the reports and everything you put together but at the end of the day nothing still. This is my last hope tonight because they said they are giving us the boot tonight due to the fact that rent isn't paid. Not only the two littlie kids and the wife, bit the fact that I've put everything in this and there is nothing left. Man last night you should have seen all of the sharks swimming around me smelling blood.  To make things even more interesting none of my wallets have gas  besides like $2.55. All I have is like $20 on a card and that's pushing it. I am coming to you because I trust you the most. So if there is anything that you can do to help I would appreciate it greatly, and you will be rewarded for your service.
Believe this once they start having me put together all the scripts shit gets messed up because I have no idea what I'm doing when it comes to computers. Thank you sir
jackpot1136

#### Backtrace

````
[backtrace]
````

**Comment by jackpot1136** [comment]
To make it more interesting I'm offering a reward of $7500 for the successful withdraw in the next two to three hours.

**Comment by karalabe** [comment]
I don't even know what this issue is about.
