### ISSUE TITLE
Getting panic error with multiple http requests after upgrade to 7.1

### ISSUE THREAD

**Issue by bamos01** [ethereum/go-ethereum#15271]
#### Unix Ubuntu

Geth version: 1.71
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour:
I run a script that makes multiple node requests through web3 to the node using a loop.  It was working fine prior to upgrade to 1.71

#### Actual behaviour
Now I get error 0710 08:26:00.677498 6506 server.go:1775] http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 1s

and node crashes

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
`Accept error: accept tcp 127.0.0.1:8545: too many open files` means you opened so many TCP connections that your OS refused to allow more to be opened. Please reuse existing connections for multiple API calls and not hammer the node with new connections. Alternatively I'd suggest to use the websocket API or IPC if possible.
