### ISSUE TITLE
If you have a second can you take a look at my withdraw script please

### ISSUE THREAD

**Issue by jackpot1136** [ethereum/go-ethereum#15286]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
Sounds more like a question for: https://ethereum.stackexchange.com

**Comment by karalabe** [comment]
This issue doens't have any content?! @jackpot1136 If you need some help, please provide information. This is a bug tracker, not a support system, we don't know what your issue is, especially if you don't even tell us anything.
