### ISSUE TITLE
Replacement transactions don't broadcast

### ISSUE THREAD

**Issue by sdrobs** [ethereum/go-ethereum#15289]
#### System information

Geth version: `1.7.0 (also tested on 1.7.1 stable and 1.6.6)`
OS & Version: Linux (Ubuntu 14.04)

#### Expected behaviour

1. Send a transaction to a remote address with correct nonce n, and gas price p.
2. Overwrite this transaction by sending a new transaction with same nonce n and gas price p * 1.25
3. Original transaction should be overwritten.

#### Actual behaviour

1. Send a transaction to a remote address with correct nonce n, and gas price p.
2. Overwrite this transaction by sending a new transaction with same nonce n and gas price p * 1.25
3. We are shown a transaction hash from step 2, but it is never broadcasted. The transaction from step 1 remains the only visible transaction remotely. There is no change even after waiting a few minutes.

#### Steps to reproduce the behaviour
1. Open Geth console (Geth attach)
2. Send a transaction that won't be processed quickly. It should broadcast as expected: eth.sendTransaction({to:"0xDEADBEEF",from:"0x0xCAFEBABE",gas: 250000, gasPrice: web3.toWei(3, 'gwei')})
3. Attempt to overwrite it:
eth.sendTransaction({to:"0xDEADBEEF",from:"0x0xCAFEBABE",gas: 250000, gasPrice: web3.toWei(5, 'gwei'), nonce: <the nonce of the txn from step 2>})
4. You will be shown a txn hash from step 3, but it does not broadcast.

Worth noting that restarting Geth will correctly broadcast the replacement after it reloads the pending transactions.

**Comment by karalabe** [comment]
Huh, this is odd, I'll look into it, thanks for reporting!

**Comment by sdrobs** [comment]
Are you able to repro on your end? A project I'm working on heavily relies on fast transaction overwrites, so I'd be interested if you had any workarounds for the time being.
