### ISSUE TITLE
Error: The method eth_compileSolidity does not exist/is not available Help!!!

### ISSUE THREAD

**Issue by Jasurisak** [ethereum/go-ethereum#15281]
I am using wallet.ethereum.org to test a smart contract, and getting this Error: The method eth_compileSolidity does not exist/is not available. Please help how can I fix it?

**Comment by EasonWang01** [comment]
It has been removed https://github.com/ethereum/go-ethereum/issues/3793

**Comment by karalabe** [comment]
https://remix.ethereum.org

**Comment by daprezjer** [comment]
@EasonWang01 @karalabe , to be sure, are you saying that wallet.ethereum.org doesn't work anymore, and that people should use remix instead?  If so, what's the sense of leaving that functionality up and confusing people?  If not, is there something else we should be doing in our contracts to get them to work on wallet.ethereum.org?

**Comment by odapplications** [comment]
+1 for using wallet.etherum.org not enough functionality within the remix

within the wallet you have the option to click within fields and change the text and wording.
