### ISSUE TITLE
Block sealing failed, when consensus engine is configed to clique.

### ISSUE THREAD

**Issue by shiqinfeng1** [ethereum/go-ethereum#15282]
#### System information

Geth version: `1.6.0-stable`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour
the signer  mine block well after  `miner.start()` . when the  signer  account is lock for timeout, I unlock it manually, the signer should mine block again.

#### Actual behaviour

print  error log :
```
WARN [10-12|14:30:41] Block sealing failed                     err="authentication needed: password or unlock"
```
and the signer not mine block after unlock account again.

#### Steps to reproduce the behaviour
1.  unlock signer: personal.unlockAccount(eth.coinbase)
1.  miner.start()
1.  wait account to lock
1.  unlock  signer again
1.  not to be continue to mine...

#### Backtrace

````
INFO [10-12|14:30:37] Commit new mining work                   number=134 txs=0 uncles=0 elapsed=290.3µs
INFO [10-12|14:30:37] Signed recently, must wait for others
INFO [10-12|14:30:39] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=1.014ms   mgasps=0.000 number=134 hash=f22c1a…40aced
INFO [10-12|14:30:39] Commit new mining work                   number=135 txs=0 uncles=0 elapsed=369.335µs
INFO [10-12|14:30:39] 🔗 block reached canonical chain          number=129 hash=45e5c9…a4ba7b
WARN [10-12|14:30:41] Block sealing failed                     err="authentication needed: password or unlock"

> personal.unlockAccount(eth.coinbase,"",99999)
true
> eth.blockNumber
134
> eth.blockNumber
134
````

**Comment by trtg** [comment]
Adding on to this- the same or similar issue takes place when attempting to add a new signer to an existing chain/setup. After a clique.propose("0x55175..",true) on the existing signers and then attempting to the following on the new signer
`
personal.unlockAccount(eth.coinbase,"",99999)
miner.start()
`
the new signer and old one just stall with \:
`
Signed recently, must wait for others
`

**Comment by payadav** [comment]
Does anyone have a solution to this problem ?
We are using Geth1.7.3-stable-4bb3c89d ver, we have configured two PoA nodes with two signer accounts one on each node. Both the signers must sign a transaction to store it in Blockchain. 

The problem i am facing is with the miners are stopped when geth instances are started, 
**WARN [01-22|19:07:12] Block sealing failed                     err="authentication needed: password or unlock"** 

Even if i am trying to unlock the accounts 
personal.unlockAccount(eth.coinbase.....) -> return true
miner.start() -> return null 
Miners are not started.

Sometimes personal.unlockAccount(eth.coinbase.....) command is killing the Geth instance.

Could this be a problem with memory ?

Or any suggestion is highly appreciated.

**Comment by Kaisle** [comment]
Bump

**Comment by jmahhh** [comment]
Have you tried using the `-unlock` and `--password` flags in the `geth` startup cmd?

**Comment by shiqinfeng1** [comment]
this problem is resolved， thanks。

**Comment by trtg** [comment]
Resolved how? Is there a PR that fixed it?

**Comment by shiqinfeng1** [comment]
I mean when miner is locked， you must stop mining and start again after unlock  miner， or  use the -unlock parameter。

**Comment by pachaibalaji** [comment]
@shiqinfeng1 Yes, it does solve the error, but any idea why does it happen in this way?

**Comment by Gelassen** [comment]
It is not the single issue of Clique consensus algorithm. Among those which stay open, here  is one I faced personally: 
https://github.com/ethereum/go-ethereum/issues/18402
