### ISSUE TITLE
ETH & ETC sync method

### ISSUE THREAD

**Issue by wjcloud** [ethereum/go-ethereum#15295]
I'd like to know the difference between Ethereum and Ethereum Classic's network.
Basically they use same network id and same port number. 
However they do not sync their transactions and blocks, I think peers do not find each other.
If they recognize and drop each other, how do they drop? Is there a specific code?

**Comment by RichHorrocks** [comment]
Ideally ask technical questions on https://ethereum.stackexchange.com - it's important to keep issue trackers clear and for real issues only.

**Comment by wjcloud** [comment]
@RichHorrocks Not bad. But I'd like to hear the answer from geth developers

**Comment by RichHorrocks** [comment]
(The answer is probably (implicitly) covered by responses to previous questions on SE. For example: https://ethereum.stackexchange.com/questions/17051/how-to-select-a-network-id-or-is-there-a-list-of-network-ids)

The network IDs may be the same, but the _chain_ IDs are different. The main Ethereum chain is `1`, Ethereum Classic is `61`, Expanse is `2`. (The Expanse network also has a network ID of `1`.)

Chain IDs were added in[ EIP-155](https://github.com/ethereum/eips/issues/155) (I think) to prevent replay attacks across chains.

The networks also use different hard-coded boot nodes, used when client nodes initially bootstrap into the network, so really there should be no reason why the networks would overlap, unless you explicitly add a node from another network using the `--bootnodes` flag, or similar.  See [here](https://github.com/ethereum/go-ethereum/blob/79b11121a7e4beef0d0297894289200b9842c36c/params/bootnodes.go#L23) for the main network's config.

Someone more familiar with the code might want to comment further, but you can track down ID mismatches - and potentially where blocks/transactions are dropped - by poking around at `ErrInvalidChainId`.

**Comment by karalabe** [comment]
There is a DAO challenge after a successful eth protocol handshake. The two forks have well defined header extra-data sections for 10 blocks following the fork. Geth challenges the remote node for these blocks and disconnects if they mismatch.

**Comment by wjcloud** [comment]
@karalabe  I wonder why didn't they change network id instead of implementing another node vaildation LOL.

**Comment by karalabe** [comment]
@wjcloud Network ID is not reliable, anyone could fake it. Back then there was no notion of chain ID either. The DAO challenge was a quick and dirty solution that cleanly separated the two forks without favoring either of them.
