### ISSUE TITLE
[MacOS] Trezor not recognized when plugged in to USB

### ISSUE THREAD

**Issue by ronaldmannak** [ethereum/go-ethereum#15296]
#### System information

Geth version: geth-darwin-amd64-1.7.1-05101641
OS & Version: OSX

#### Expected behaviour
When Trezor hardware wallet is plugged in the USB, Geth will print ````WARN [08-10|11:55:19] New wallet appeared, failed to open url=trezor://0003:0007:00 err="trezor: pin needed"````, as described in PR #14885.

````> personal.listWallets```` should list the available Trezor wallets, like:

````
INFO [08-10|12:07:35] USB wallet discovered new account   url=trezor://0003:0007:00 address=0x7Bf042272737121236dcBC078A218646C94730f4 path=m/44'/60'/0'/0/0 balance=88999999999876 nonce=4
INFO [08-10|12:07:35] USB wallet discovered new account   url=trezor://0003:0007:00 address=0x89B613B665E9EA122EB1D54f3B54195160cAB8fb path=m/44'/60'/0'/0/1 balance=124            nonce=0
INFO [08-10|12:07:35] USB wallet discovered new account   url=trezor://0003:0007:00 address=0x6742064c46Ccc179C877Ea8782b5d5Fe5b033378 path=m/44'/60'/0'/0/2 balance=0              nonce=0
...
````

#### Actual behaviour

- The warning ````New Wallet Appeared```` message is not shown when a Trezor is plugged in the USB port
- ````> personal.listWallets```` only lists wallets available on disk, not the Trezor wallet.

#### Steps to reproduce the behaviour

- Start geth with ````geth````. Geth will start in Homestead with ChainID 1
- Start console ````geth console```` in a different terminal window
- Attach Trezor. 
- Run ````> personal.listWallets```` commands

**Comment by ronaldmannak** [comment]
I wrote a quick MacOS to check the USB connectivity. My app receives the USB notifications when a Trezor is attached to the Mac, which suggests the Trezor and not MacOS are not the issue.

````
USBDevice(id: xxxx, vendorId: 21324, productId: 1, name: "TREZOR", deviceInterfacePtrPtr: Optional(0x0000618000101b20), plugInInterfacePtrPtr: Optional(0x0000618000101b10))
{
    device = "USBDeviceSwift.USBDevice(id: xxxx, vendorId: 21324, productId: 1, name: \"TREZOR\", deviceInterfacePtrPtr: Optional(0x0000618000101b20), plugInInterfacePtrPtr: Optional(0x0000618000101b10))";
}
````

**Comment by woodydeck** [comment]
I think it is just broken in OSX. I can't get it to work with 1.8 geth. It just hangs when you enter the PIN. WARN [12-26|20:19:25] Failed to open wallet                    url=trezor://IOService:/AppleACPIPl… err="trezor: pin needed"
491639

Also, there's no documentation easily found. It would help if it told you how it maps number for number to the numpad.
