### ISSUE TITLE
zero balance

### ISSUE THREAD

**Issue by deathtech69** [ethereum/go-ethereum#15292]
#### System information

Geth version: `geth version` latest
OS & Version: Windows/Linux/OSX windows 8.1
Commit hash : (if `develop`)

#### Expected behaviour
My balanced shown

#### Actual behaviour
no balance

#### Steps to reproduce the behaviour
I can run the commands to show eth.syncing and it will return false, its been sycned for a good while now, but i can never get a balance no matter what I do. 

eth.getBlock('latest') shows zero for block number, but i read this is normal if you do a fast sync which i did.

I'm on the public network not testnet. and have currently 7 peers.

i'm using a SSD drive, and using 6gigs of cache allocated for geth as it starts.

> web3.eth.syncing
false

i've redownloaded the block chain numerious times and started over. i'm at my wits end.. any one have an idea on what i can try?

EDIT:

right when i was about to post this most of my peers stalled for an uknown reason, seems i still have 1 or 2 connected..

WARN [10-13|10:08:46] Stalling state sync, dropping peer       peer=a81dc0139490705b
WARN [10-13|10:08:46] Stalling state sync, dropping peer       peer=92691c47b22a6e9b
WARN [10-13|10:08:46] Stalling state sync, dropping peer       peer=7cbf9e0182ef3417
WARN [10-13|10:08:46] Stalling state sync, dropping peer       peer=a7ad568c6238a20a
WARN [10-13|10:08:47] Stalling state sync, dropping peer       peer=886c0cbad3f730db
WARN [10-13|10:08:48] Stalling state sync, dropping peer       peer=6b5d4b150677e54a
WARN [10-13|10:08:48] Stalling state sync, dropping peer       peer=6a55ec58bd70dd64
WARN [10-13|10:08:51] Stalling state sync, dropping peer       peer=cde125fedfc278c1
WARN [10-13|10:08:52] Stalling state sync, dropping peer       peer=b8f5fcafd3621cf4
WARN [10-13|10:08:53] Stalling state sync, dropping peer       peer=58429adc4d91188c
WARN [10-13|10:08:53] Stalling state sync, dropping peer       peer=939d6eb3242ba273
WARN [10-13|10:08:59] Stalling state sync, dropping peer       peer=4b1e924178dc4bda
WARN [10-13|10:08:59] Stalling state sync, dropping peer       peer=7cbf9e0182ef3417
WARN [10-13|10:09:13] Stalling state sync, dropping peer       peer=f34b3156bcf72f17
WARN [10-13|10:09:15] Stalling state sync, dropping peer       peer=7cbf9e0182ef3417
WARN [10-13|10:09:30] Stalling state sync, dropping peer       peer=7cbf9e0182ef3417
WARN [10-13|10:09:37] Stalling state sync, dropping peer       peer=ea526f63c429d8bf
WARN [10-13|10:09:46] Stalling state sync, dropping peer       peer=7cbf9e0182ef3417
WARN [10-13|10:09:51] Stalling state sync, dropping peer       peer=f34b3156bcf72f17
INFO [10-13|10:09:56] Imported new state entries               count=989  elapsed=2.005ms   processed=8019865 pending
690 retry=2006 duplicate=785 unexpected=2287
WARN [10-13|10:10:11] Stalling state sync, dropping peer       peer=7cbf9e0182ef3417
WARN [10-13|10:10:26] Stalling state sync, dropping peer       peer=46b6e27be5f6e3ba
WARN [10-13|10:10:32] Stalling state sync, dropping peer       peer=ea526f63c429d8bf
WARN [10-13|10:10:57] Stalling state sync, dropping peer       peer=ea526f63c429d8bf
WARN [10-13|10:11:04] Stalling state sync, dropping peer       peer=f34b3156bcf72f17
WARN [10-13|10:11:06] Stalling state sync, dropping peer       peer=5607018a2c07c3e1

ANother EDIT:

I stopped it and started again, and now it start to resync but is stuck on this status with no update:

> web3.eth.syncing
{
  currentBlock: 4362250,
  highestBlock: 4362471,
  knownStates: 156487,
  pulledStates: 126346,
  startingBlock: 4362250

i constantly get imports in the console however:

6 retry=180 duplicate=261 unexpected=913
INFO [10-13|10:18:54] Imported new state entries               count=659  elapsed=2.001ms  processed=222545 pending=342
1 retry=0   duplicate=261 unexpected=913
INFO [10-13|10:18:55] Imported new state entries               count=949  elapsed=2.004ms  processed=223494 pending=358
6 retry=2   duplicate=261 unexpected=913

#### Backtrace

````
[backtrace]
````

**Comment by lethalman** [comment]
Is eth.blockNumber showing the latest block? If not, you are still downloading states ecc., even if syncing is false. You are in sync when eth.blockNumber is truly the latest block of the chain.
That's my understanding at least.

**Comment by 0z4ck** [comment]
I think I have the same problem. Did you find out the solution ?

**Comment by deathtech69** [comment]
I gave up on geth and used parity instead. :(

Plus side I really like parity.
