### ISSUE TITLE
invalid header on mined block: GasLimit check failed

### ISSUE THREAD

**Issue by nmushegian** [ethereum/go-ethereum#1530]
worker.go:281] Invalid header on mined block: GasLimit check failed for block 5000 (5000 > 0)

Trying to mine a new private chain.

**Comment by tgerring** [comment]
My guess is that you're working off develop HEAD. If so, this is pertinent: https://www.reddit.com/r/ethereum/comments/3ejtr3/repo_update_goethereum_develop_branch_will_become/
