### ISSUE TITLE
Wiki: Command Line Options Outdated

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#15304]
The Wiki's Command Line Options are outdated. The last update was nearly a year ago.

I don't know how to submit a pull request to a Wiki otherwise I would...I even went so far as to clone the repo, clone the wiki, and edit the page in my repo but I can't figure out how to submit a pull request 😫

It's a simple copy/paste job either way 😄

**Comment by RichHorrocks** [comment]
I'd done something similar in the past, and had the same problems as you. I think I concluded that only the wiki creators had edit privileges :-\

**Comment by MysticRyuujin** [comment]
@fjl I noticed that you recently updated the wiki :)

Also, the "Troubleshooting" page on the Wiki appears to be totally busted
