### ISSUE TITLE
Synchronisation failed, dropping peer 

### ISSUE THREAD

**Issue by ButSoft** [ethereum/go-ethereum#15303]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
I run command:  geth --rinkeby 
#### What did you expect to see?
WARN [10-15|22:35:09] Synchronisation failed, dropping peer    peer=343149e4feefa15d err="retrieved hash chain is invalid"
ERROR[10-15|22:35:19] 
########## BAD BLOCK #########
Chain config: {ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: true EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 9223372036854775807 Engine: clique}
Number: 1035301
Hash: 0x9e673f84fa096626d50440cbb7c71ec891fd42993be3d99f87c826b43842c592
	receipt{med=a95f1fbd2fa6589acd708d187dfefab5944c64f5eb8eec1c32eb 
......
 
#### System details
Version: 1.7.0-stable
Go Version: go1.9
OS: linux
uname -sr: Linux 4.4.0-96-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by ligi** [comment]
You need to run 1.7.2: https://github.com/ethereum/go-ethereum/releases/tag/v1.7.2 or at minimum 1.7.1 for Byzantium
