### ISSUE TITLE
Section processing failed  error="chain reorged during section processing"

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#15301]
#### System information

Geth version: `geth 1.7.2-stable'
OS & Version: Windows server 2016 standard x64
Commit hash : (if `develop`)

#### Expected behaviour
Receiving error messages during full sync: chain reorged during section processing,
I didn't received this message when I run geth 1.7.1

#### Actual behaviour
ERROR[10-15|08:49:56] Section processing failed                type=bloombits error="chain reorged during section processing"

**Comment by philejmath** [comment]
same issue on the Mac 1.7.2

**Comment by photonxp** [comment]
Could this issue be due to the hard-fork of blockchain?

**Comment by akudo7** [comment]
Any update so far?
Can we ignore this message?
Any information appreciate.

**Comment by zhaodehua1988** [comment]
Can we ignore this message?

**Comment by adamschmideg** [comment]
Closing as duplicate of #17227 and it contains more information
