### ISSUE TITLE
rollback command is missing from 1.7.2

### ISSUE THREAD

**Issue by RaghavSood** [ethereum/go-ethereum#15319]
#### System information

Geth version: 1.7.2-stable
OS & Version: Ubuntu Xenial
Commit hash : 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9

#### Expected behaviour

`geth rollback n` roll backs the blockchain to block n and resyncs

#### Actual behaviour

`geth rollback n` has no effect, and geth just keeps syncing from where it was.

#### Steps to reproduce the behaviour

Install via official PPA, sync to some block, try rolling back to a previous block

#### Backtrace

None

**Comment by dartkinselok** [comment]
+1
