### ISSUE TITLE
Cuda error

### ISSUE THREAD

**Issue by samhkarmy** [ethereum/go-ethereum#15317]
Hey everyone, I'm running a GTX 670 with 4gb of memory(I know it isn't that amazing). Everytime I go to start the program, it loads everything then goes to 
CUDA error - cannot allocate big buffer for DAG. 
GPU 0 failed
GPU 0, CUDA error 11- cannot write bufer for dag
GPU 0 failed
WATCHDOG: GPU error, you need to restart miner : (

Any help would be greatly appreciated

**Comment by RichHorrocks** [comment]
This gets asked fairly often on ethereum.stackexchange.com, so that might be a better place to ask.

I'd suspect that even though you have enough memory, you'll need to adjust the page size/virtual memory to be able to accommodate the DAG (which is now over 2GB).

**Comment by karalabe** [comment]
Go ethereum does not contain a GPU miner, so you'll need to ask your question on whatever repository you are using to mine.
