### ISSUE TITLE
GPU issue - Adapter 0 not peaking

### ISSUE THREAD

**Issue by jeroenn13** [ethereum/go-ethereum#1531]
When I mine or benchmark with ethminer it seems one of my cards are not running 100%. The core stays 501 Mhz while the other card is peaking. How do I get adapter 0 mining at its peak?

ethermining@ubuntu:~$ aticonfig --adapter=all --odgc
Adapter 0 - AMD Radeon R9 200 Series

                          Core (MHz)    Memory (MHz)

         Current Clocks :    501           1500

         Current Peak :    1180           1800

         Configurable Peak Range : [300-1500]     [150-2000]

         GPU load :    100%
Adapter 1 - AMD Radeon R9 200 Series

                            Core (MHz)    Memory (MHz)

       Current Clocks :    1180           1800

         Current Peak :    1180           1800

          Configurable Peak Range : [300-1500]     [150-2000]

             GPU load :    96%

Adapter 0 - MSI R9 280x 280x twin frozr
Adapter 1 - R9 280x sapphire

**Comment by obscuren** [comment]
This would be an issue for the C++ team. Ethminer is included in the C++ suit.
