### ISSUE TITLE
Health check api

### ISSUE THREAD

**Issue by johnluan** [ethereum/go-ethereum#15318]
Hi Guys,

Didn't find anywhere to ask questions, so I raised an issue here to ask. 
If it is not appropriate, please close it.

I am running testnet at one server for almost 2 months for testing purpose, But during this period, it crashed a few times, like stop syncing, threw strange errors.  
My question here is that is there a health check api to let user know if the API is alive?
I plan to do a load balance, but don't know which API is good to call as health check function.

I noticed, we have  eth_syncing, is it good enough to use as health check?

Or I have to check admin_peers, to see how many peers connected?

Thanks.

**Comment by RichHorrocks** [comment]
A good place to ask technical questions - like this one - would be the Stack Exchange board (https://ethereum.stackexchange.com). For anything that's more open-ended or subjective, Reddit is often a better forum (https://reddit.com/r/ethereum).

**Comment by karalabe** [comment]
You could always retrieve the `'latest'` block via `eth_getBlockByNumber`. If the API responds and the block is recent based on its timestamp, it should be good to go.

**Comment by johnluan** [comment]
Thank you @karalabe , that is a good idea.
