### ISSUE TITLE
AVG antivirus flag it as infested by a malware: "FileRepMalware"

### ISSUE THREAD

**Issue by vrolland** [ethereum/go-ethereum#15310]
Hello guys,

#### System information
Geth version: 1.7.2
OS & Version: Windows 10
AVG antivirus Free edition : 17.7.3032

#### Expected behaviour
Windows installer should not be blocked by my antivirus. (link from https://geth.ethereum.org/downloads/ => https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.7.2-1db4ecdc.exe

#### Actual behaviour
AVG antivirus flag it as infested by a malware: "FileRepMalware"

#### Steps to reproduce the behaviour
Download Geth installer for windows on https://geth.ethereum.org/downloads/ => https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.7.2-1db4ecdc.exe on WIndows 10 with AVG Free edition

Best,

**Comment by karalabe** [comment]
AVG detects a ton of false positives generally in P2P networking programs (it flags bittorrent the same way). Not much we can do other than someone reporting to AVG that their detector is crappy. No antivirus from virus total detects is as malicious: https://www.virustotal.com/#/url/4d7669b0cb6f9b2b92474c35e02dfffe2bc476e84ee48526408498361d015275/detection

**Comment by vrolland** [comment]
Thank you for you quick answer!

**Comment by kevinyoungus** [comment]
I was thinking to buy AVG VPN service but little confused about this service. I read a blog regarding detailed analysis of this VPN but not satisfied. Can anyone suggest me?
[https://www.vpnranks.com/vpn-reviews/avg-vpn/](https://www.vpnranks.com/vpn-reviews/avg-vpn/)
