### ISSUE TITLE
Too high CPU load

### ISSUE THREAD

**Issue by johankitelman** [ethereum/go-ethereum#15328]
#### System information

Geth version:
 ```
Version: 1.7.3-unstable
Git Commit: e5c19b6f98b788e6b8e7b092507a44b3808c10b8
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
Operating System: linux
```
OS & Version: Ubuntu 16.04 LTS

#### Problematics

After update of the Geth it've worked few days in normal state. But yesterday we've noticed that it overloads CPU >150-200%. Miner options disabled, sync finished (eth_syncing results in false, height of blocks +- like on etherscan). Here is all flags that we're using at the running Geth:
```
geth --verbosity 1 --port 30303 --syncmode "full" --identity "mercatox" --datadir "/home/ethereum/node/chain" --nousb --ipcdisable --rpc --rpcport 8540 --rpcapi "eth,personal,admin,debug,net,rpc,txpool"
```

I've tried to rebuild Geth few times, use 1.7.2, 1.7.1, 1.7.3 versions - no effect. Any solutions? Thanks in advance!

**Comment by karalabe** [comment]
Please create a CPU profile via `debug.cpuProfile("geth.cpu", 60)` and send the resulting file to us to see what your node is spending its time on.

**Comment by academ1c** [comment]
Instance: Geth/v1.7.2-stable-1db4ecdc/linux-amd64/go1.9

[geth.cpu.txt](https://github.com/ethereum/go-ethereum/files/1471501/geth.cpu.txt)

**Comment by areebmajeed** [comment]
I've geth taking 300% too :)

**Comment by bibodeng** [comment]
same problem

**Comment by gillbates** [comment]
same problem here ...
<img width="612" alt="screen shot 2018-08-23 at 21 12 38" src="https://user-images.githubusercontent.com/783547/44527416-4e087c00-a719-11e8-97cf-31a111834a03.png">
