### ISSUE TITLE
0.5 ETH question) Getting BAD BLOCK error: invalid transaction v, r, s values

### ISSUE THREAD

**Issue by wjcloud** [ethereum/go-ethereum#15325]
########## BAD BLOCK #########
Chain config: {ChainID: 1 NewChainID: 7 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 ATField: 4370000 Thirdimpact: 4670000 Engine: ethash}

Number: 4348376
Hash: 0x8efd74ba4cdd9d107bcb8abf6b71eb6d11ca34fe3574584423f1262667928656

Error: invalid transaction v, r, s values
##############################

WARN [10-18|13:36:44] Synchronisation failed, dropping peer    peer=71285812c2bc8d6e err="retrieved hash chain is invalid'

-------------------------------------------------------------------------------------------------------------------

So I've changed chain_id value for fun.
When nodes are mining, it would be ok.
However when It sync with original chain, It get stucks with these error.
I wonder how geth verifies chainid inside block.
Any ideas?

**Comment by wjcloud** [comment]
I will give 0.5 ETH whom answers the question. It is urgent!

**Comment by jengy** [comment]
view it on GitHub<https://github.com/ethereum/go-ethereum/issues/15325#issuecomment-337466921>

发件人: WJ Cloud [mailto:notifications@github.com]
发送时间: 2017年10月18日 13:49
收件人: ethereum/go-ethereum <go-ethereum@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [ethereum/go-ethereum] 0.5 ETH question) Getting BAD BLOCK error: invalid transaction v, r, s values (#15325)


I will give 0.5 ETH whom answers the question. It is urgent!

**Comment by karalabe** [comment]
Every transaction in a block is verified when importing the block. I guess you messed up your block validation rules.

**Comment by wjcloud** [comment]
@karalabe Nono I mean when I modify geth's chainid and sync with it, I get an error, which geth verified block's chainid.

**Comment by jengy** [comment]
view it on GitHub<https://github.com/ethereum/go-ethereum/issues/15325#issuecomment-337489191>

发件人: WJ Cloud [mailto:notifications@github.com]
发送时间: 2017年10月18日 15:48
收件人: ethereum/go-ethereum <go-ethereum@noreply.github.com>
抄送: Zhang Shaojun <sj_zhang@msn.com>; Comment <comment@noreply.github.com>
主题: Re: [ethereum/go-ethereum] 0.5 ETH question) Getting BAD BLOCK error: invalid transaction v, r, s values (#15325)


@karalabe<https://github.com/karalabe> Nono I mean when I modify geth's chainid and sync with it, I get an error, which geth verified block's chainid.

**Comment by wjcloud** [comment]
So I want to know which code is verifying the block's chainid?

**Comment by wjcloud** [comment]
@karalabe  And could you please leave your eth address? I will send you rewards.

**Comment by wjcloud** [comment]
Also I would prefer opening this issue. Thank you.

**Comment by wjcloud** [comment]
We have solved this! See twitter.com/opcahf for advance!
