### ISSUE TITLE
Ethereum units in web3.js file

### ISSUE THREAD

**Issue by moeinzed** [ethereum/go-ethereum#15322]
Hi 
I changed a unit to another name in `internal/jsre/deps/web3.js`, but when i compile and run it, that unit still there!
What should i do?

**Comment by karalabe** [comment]
The contents of web3.j needs to be embedded into the Go source files. Within the `internal/jsre/deps` do `go generate`.

**Comment by zhaobisheng** [comment]
How should I embed the modified web3.js into the source code?
I can not encode same with original.
thanks!
