### ISSUE TITLE
iOS - Lite - syncProgress is nil.

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#15327]
#### System information

Geth Version: iGeth/v1.7.2-stable/darwin-amd64/go1.9
OS & Version: iOS 11.0 Simulator

#### Expected behaviour

Expecting syncProgress(context) method of GethEthereumClient to return a new GethSyncProgress instance.

#### Actual behaviour

The syncProgress is nil. It returns syncProgress sometimes after some app restarts.

#### Steps to reproduce the behaviour

First I start Node:

```
fileprivate func startNode() throws {
    var error: NSError?
    let bootNodes = GethNewEnodesEmpty()
    bootNodes?.append(GethNewEnode(Constants.Ethereum.enodeRawUrl, &error))

    let genesisPath = Bundle.main.path(forResource: "rinkeby", ofType: "json")
    let genesis = try! String(contentsOfFile: genesisPath!, encoding: String.Encoding.utf8)

    let config = GethNewNodeConfig()
    config?.setBootstrapNodes(bootNodes)
    config?.setEthereumGenesis(genesis)
    config?.setEthereumNetworkID(4)

    let datadir = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]
    ethereumNode = GethNewNode(datadir, config, &error)

    try ethereumNode.start()

    if let error = error {
        throw EthereumError.nodeStartFailed(error: error)
    }
}
```

Then try to check sync progress:

```
fileprivate func startSync() throws {
    if let syncProgress = try? self.ethereumNode.getEthereumClient().syncProgress(self.ethereumContext) {
        self.isSyncMode = true // Can't reach this!! :/
    } else if self.isSyncMode {
        self.isSyncMode = false
    }
}
```

**Comment by ligi** [comment]
On android this is the same - syncProgress is null when the sync has not yet started. Unfortunately often it takes a long time for the sync to start.

**Comment by ronaldmannak** [comment]
As a temporary solution, it's perhaps best to wrap syncProgress in a Swift Enum that is set to .unknown at the start or assume syncProgress is unknown at the start. If you happen to catch a non nil syncProgress later, you can update the enum. Alternatively, compare the last block number Geth returns to a known Ethereum stats site.

Ultimately, it would make sense to have Geth return an enum and support a delegate callback.
