### ISSUE TITLE
PPA installs *1.6.7-stable-ab5646c5* -- Instead of latest (1.7.2)

### ISSUE THREAD

**Issue by zach-is-my-name** [ethereum/go-ethereum#15332]
Sorry I'm confused, prompted to download latest release here: https://ethereum.github.io/go-ethereum/downloads/ 

yet when running the commands to install from Ubuntu package manager, geth --v reveals version 1.67 stable

Am I missing something? 
I'm fearful of running any version less than the hotfix (1.7.2)

#### System information

OS & Version: Ubuntu 16.10

**Comment by karalabe** [comment]
Ubuntu Yakkety was deprecated by Canonical, and PPAs refuse to accept new packages for it. Please update your distribution to Ubuntu Zesty.

**Comment by zach-is-my-name** [comment]
Did as you said, reinstalled, still 1.67

```
zmg@acer:~$ sudo apt-get install ethereum
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.8.0-58 linux-headers-4.8.0-58-generic
  linux-image-4.8.0-58-generic linux-image-extra-4.8.0-58-generic
  linux-signed-image-4.8.0-58-generic
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  ethereum
1 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Need to get 1,540 B of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ethereum/ethereum/ubuntu zesty/main amd64 ethereum amd64 1.7.2+build11187+zesty [1,540 B]
Fetched 1,540 B in 0s (8,176 B/s)    
(Reading database ... 256840 files and directories currently installed.)
Preparing to unpack .../ethereum_1.7.2+build11187+zesty_amd64.deb ...
Unpacking ethereum (1.7.2+build11187+zesty) over (1.6.7+build10273+yakkety) ...
Setting up ethereum (1.7.2+build11187+zesty) ...
zmg@acer:~$ geth version
Geth
Version: 1.6.7-stable
Git Commit: ab5646c532292b51e319f290afccf6a44f874372
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.8

```

**Comment by zach-is-my-name** [comment]
Did as you said, reinstalled, still 1.67

zmg@acer:~$ sudo apt-get install ethereum
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.8.0-58 linux-headers-4.8.0-58-generic
  linux-image-4.8.0-58-generic linux-image-extra-4.8.0-58-generic
  linux-signed-image-4.8.0-58-generic
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  ethereum
1 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Need to get 1,540 B of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ethereum/ethereum/ubuntu zesty/main
amd64 ethereum amd64 1.7.2+build11187+zesty [1,540 B]
Fetched 1,540 B in 0s (8,176 B/s)
(Reading database ... 256840 files and directories currently installed.)
Preparing to unpack .../ethereum_1.7.2+build11187+zesty_amd64.deb ...
Unpacking ethereum (1.7.2+build11187+zesty) over (1.6.7+build10273+yakkety) ...
Setting up ethereum (1.7.2+build11187+zesty) ...
zmg@acer:~$ geth version
Geth
Version: 1.6.7-stable
Git Commit: ab5646c532292b51e319f290afccf6a44f874372
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.8
