### ISSUE TITLE
Commit hash missing from Geth version in Docker builds

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#15346]
In our [Dockerfile](https://github.com/ethereum/go-ethereum/blob/master/Dockerfile), `make geth` does not inject the commit hash into Geth's version string because the `.git` repository is ignored via [.dockerignore](https://github.com/ethereum/go-ethereum/blob/master/.dockerignore).

Would help to figure out which files from `.git` should be forwarded into the docker build process to re-enable the commit hashes in the version string. A good starter is [`build.LocalEnv`](https://github.com/ethereum/go-ethereum/blob/master/internal/build/env.go#L83), which tries to pull the commit hash from git.

You can also read the discussion in https://github.com/ethereum/go-ethereum/pull/15351 for the proposal of a good solution (the PR itself wasn't suitable).

**Comment by asasmoyo** [comment]
Hello! I would like to start my contribution to Ethereum. If no one working on this, I would like to take it :)
