### ISSUE TITLE
log when leveldb compaction happens?

### ISSUE THREAD

**Issue by cdetrio** [ethereum/go-ethereum#15347]
Sometimes leveldb starts compacting its internal chaindata index. This can cause temporary slowdowns, but it is not logged to the terminal when compaction starts and finishes. Logging when compaction is happening will help users diagnose whether a slowdown is due to leveldb compaction or to something else.

**Comment by samlavery** [comment]
It's always compacting, I don't think it's ever not compacting actually, according to an instance i've been profiling of 1.7.3.

**Comment by karalabe** [comment]
True, perhaps a better metric would be to display some infos when the compaction is causing database writes and reads to be suspended? AFAIK leveldb starts delaying writes, and if enough of them queue up then it puts them on hold altogether. Unsure btw if this is something we can measure from the outside, but it would be an interesting project, perhaps in collaboration with upstream leveldb.

**Comment by rjl493456442** [comment]
I think i can help it. Not sure we can measure the compaction statistic which causes w/r suspended.

**Comment by rjl493456442** [comment]
Actually, there is no API in goleveldb when can retrieve the write paused statistic directly. Although we can obtain integral statistic of table compaction via `GetProperty` API, but it is not enough. Negotiate with upstream is necessary.

**Comment by lazyGoose** [comment]
Anyone working on this? I'd like to take it over.

**Comment by cdetrio** [comment]
@lazyGoose please do.

Here's some profiling by @ledgerwatch https://medium.com/@akhounov/how-to-speed-up-ethereum-in-the-face-of-crypto-kitties-7a9c901d98e9

> If we now move further down, we will see the database compaction appearing. Most probably it is running on the background, but it might still have an effect by locking the database for the readers...

**Comment by cdetrio** [comment]
There's this  https://github.com/syndtr/goleveldb/issues/181

**Comment by rjl493456442** [comment]
@cdetrio Actually i'm working on it and wait @syndtr accept my PR i'll working on the rest :)

**Comment by kishansagathiya** [comment]
Don't see any activity on this. Anyone working on it? Can I start with this?

**Comment by rjl493456442** [comment]
@kishansagathiya I already pushed a PR, just waiting review.
