### ISSUE TITLE
Include all executables in docker container

### ISSUE THREAD

**Issue by courajs** [ethereum/go-ethereum#15352]
Currently [only `geth`](https://github.com/ethereum/go-ethereum/blob/479aa61f11724560c63a7b56084259552892819d/Dockerfile#L13) is included in the `ethereum/client-go` image. The main reason I want to use the docker image is to play around and learn, without cluttering up my local machine. So, it would be great if the other executables were available:
- `abigen`
- `evm`
- `rlpdump`
- `swarm`
- `puppeth`

**Comment by karalabe** [comment]
It might be debatable whether we should introduce an "alltools" version of the docker image, but most people only ever need the main `geth` binary, and adding an extra 150MB for everyone to download that most will never it's a viable path.

@Arachnid Opinions?

**Comment by lmars** [comment]
I would personally like to see an `alltools` image (I currently build my own) :+1:.

**Comment by karalabe** [comment]
We now have 

 * `ethereum/client-go:alltools-latest`
 * `ethereum/client-go:alltools-stable` (will only be available after the next release)

As well as

 * `ethereum/client-go:alltools-v{version}` (will only be available after the next release)
 * `ethereum/client-go:alltools-release-{branch}` (will only be available after the next release)

:tada:

**Comment by courajs** [comment]
Awesome! Thanks @karalabe!
