### ISSUE TITLE
Geth No Longer Plays Nice With Mist (Not fully synced, failed transactions)

### ISSUE THREAD

**Issue by sbass301** [ethereum/go-ethereum#15350]
#### System information
Geth version: `1.7.2`
OS & Version: Windows 10

When running with geth, mist (v0.9.2) does not fully sync and is not able to place transactions on the chain.  Even though mist says it's synced, when trying to transfer ETH, mist says "0 of 12 Confirmations" forever.  I am suspecting geth, since using "parity --geth" as the ethereum client fixes the problem.

 I first tried the following actions, which did not fix the issue:
Clearing the chain cache and re syncing
Using the beta light sync
Explicitly launching geth before mist

I finally solved the issue by launching the latest parity geth client before starting mist:
c:\program files\parity\parity\parity.exe --geth

Then when I started mist, I noticed that there were a couple more thousand blocks that weren't synced, even though I had just closed geth/mist that said it was synced. After syncing, mist started, and everything worked great. In fact, a whole handful of test transactions that I had previously tried all suddenly went through. It was like winning on the slots. ;)

**Comment by DurandalFuture** [comment]
Can anyone help as to how to do this on a Mac?

**Comment by karalabe** [comment]
Please provide some logs. I have no idea what Mist is doing, but I can tell you what Geth is doing if you send me the logs.
