### ISSUE TITLE
`eth_getLogs` doesn't return pending logs

### ISSUE THREAD

**Issue by LogvinovLeon** [ethereum/go-ethereum#15359]
#### System information

Geth version: Geth/v1.7.1-unstable/linux-amd64/go1.9
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Geth should return all logs from transactions in the pending block

#### Actual behaviour
Geth returns an empty array of logs

#### Steps to reproduce the behaviour
* Run geth node
* Check that the pending block exist and contains transactions
` http http://54.215.190.250:8545 jsonrpc=2.0 id=1 method=eth_getBlockByNumber params:='["pending", true]'`
* Fetch all the logs from the pending block
`http http://54.215.190.250:8545 jsonrpc=2.0 id=1 method=eth_getLogs params:='[{"fromBlock": "pending", "toBlock": "pending"}]'`

#### Backtrace

````
[backtrace]
````

**Comment by 0xAnarz** [comment]
https://ethereum.stackexchange.com/questions/88167/pending-transactions-logs-issue

This can be directly related to the issue.
