### ISSUE TITLE
Go Failing on StateTest

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#1535]
Test:
https://github.com/ethereum/tests/commit/e0b800e3981e3f436a6bcdd9cb3266778b54221c

Output:
I0727 17:33:54.749919   13860 main.go:67] runTest StateTests
F0727 17:33:54.754724   13860 main.go:184] randomStatetest2: Post state root error. Expected 4a6e5e51ebb2fc8d2bff38da7653e00f745c8cb626b4f2d1d6e783cf5900f747, got 19cf4c2d1e51b64210c6fe4b0094f8e592a5ac333234495a948f6a3c694453e3

**Comment by Gustav-Simonsson** [comment]
CPP: https://gist.github.com/Gustav-Simonsson/a285806ddab0a1134fd1
Go: https://gist.github.com/Gustav-Simonsson/227a757d410c90242653

Looks like cpp is only popping 3 stack items for EXTCODECOPY whereas Go pops 4. Looks like a bug in cpp. I'm git bisecting to see if this used to work in cpp.

**Comment by Gustav-Simonsson** [comment]
This commit introduced the bug in cpp: https://github.com/ethereum/cpp-ethereum/commit/d8eb362d32f63b250d385d02d92e5ead30ee8488

It now misses a break; statement at https://github.com/ethereum/cpp-ethereum/blob/develop/libevm/VM.cpp#L394 which causes it fall-through to the GASPRICE op which pops no items but pushes one back on stack.
