### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by gguoss** [ethereum/go-ethereum#15363]
excute follow command:
``` bash
docker build -t ethereum .
```
Step 1 : FROM golang:1.9-alpine as builder
Error parsing reference: "golang:1.9-alpine as builder" is not a valid repository/tag

**Comment by karalabe** [comment]
You'll need to update your docker. They introduced multi-stage builds in the Docker 17.05 (may) release this year, and a month or so ago we've switched over to it to reduce the final sine of our binaries.
