### ISSUE TITLE
SSD too small to store the blockchain : Create a second datadir ?

### ISSUE THREAD

**Issue by Sovxx** [ethereum/go-ethereum#15368]
#### System information

Geth version: 1.7.2
OS & Version: Linux

### Issue

Many regular users have a computer with a rather small SSD and a large HDD.
For them, there are only 2 choices :
- use the speed of the SSD and quickly run out of storage space
- or use the space of HDD but basically never sync because it is too slow.
Which is not really great !

### Suggested enhancement :

In addition the existing --datadir parameter, add these 2 optional parameters :
--datadir_maxsize : max size in Gb of the main folder, typically on the SSD, storing the settings and the recent blocks of the blockchain
--data2dir : the second folder for storing the most of the blockchain

**Comment by karalabe** [comment]
Hmm, an alternative would be to split the database between the stuff that's immutable and (almost) never changes such as blocks, transactions, receipts, bloom filters. And have a separate database for the state, which gets updated like crazy. This could have a potential benefit of rotating the state database from time to time, thus doing a somewhat guerrilla state pruning.
