### ISSUE TITLE
synchronize Error: invalid gas used (remote: 2312570 local: 2313424)

### ISSUE THREAD

**Issue by wcw84** [ethereum/go-ethereum#15369]
#### System information
$ geth version
Geth
Version: 1.7.2-stable
Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9

#### Expected behaviour
synchronize as usual

#### Actual behaviour
Errors appeared as below:
Number: 4373337
Hash: 0x6e9bb1dfe6db737331f0be4fbc0a4cb8bfa6cf8c208188b0dfff294330a59a27
	receipt{status=1 cgas=21634 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000008000000000000000000004000000000000000000000000000000000000000000000000800000000000000000000000010000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000004000000004000000000000000000000000000000000000002000008000000002000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000 logs=[log: 44197a4c44d6a059297caf6be4f7e172bd56caaf [ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 00000000000000000000000087cce63ec1185ba097ff7de553ff176d7e88fdb3 0000000000000000000000003ad4e5b89eccd7c610187e244c89836acffd48eb] 000000000000000000000000000000000000000000000000000000e8d4a51000 23d650a6a034071c2d16e37655889084dffbcbf32425ea3b98e9c20bf036d1d8 0 6e9bb1dfe6db737331f0be4fbc0a4cb8bfa6cf8c208188b0dfff294330a59a27 0]}
[...]
	receipt{status=1 cgas=2313424 bloom=00000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000800000000000000000000000000004000000000002000400000000000000000000080000000000000000000000000000000000000000000000000002000000040000000000000000000000000000000000 logs=[log: ffe8196bc259e8dedc544d935786aa4709ec3e64 [ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 00000000000000000000000013a8b6434bd5cef0924814f7414482529b51df2a 000000000000000000000000dfe17e79e1286d69c26f547a3943f78ecea51700] 0000000000000000000000000000000000000000000000074346d0ab86f58000 a0ba7f5b4e5552a638d7f61acca4bcfa810fa2d87c1d14c4499bd74f56a70bda 24 6e9bb1dfe6db737331f0be4fbc0a4cb8bfa6cf8c208188b0dfff294330a59a27 20]}

Error: invalid gas used (remote: 2312570 local: 2313424)
##############################
 
WARN [10-24|21:25:20] Synchronisation failed, dropping peer    peer=9a9959ea634f9bf0 err="retrieved hash chain is invalid"
WARN [10-24|21:27:26] Synchronisation failed, dropping peer    peer=679be20bb3c357d5 err="retrieved hash chain is invalid"
ERROR[10-24|21:28:31] 
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Engine: ethash}

I have attached the full log below, which just repeated again and again in the console.
[sync_error_log.txt](https://github.com/ethereum/go-ethereum/files/1413487/sync_error_log.txt)

#### Steps to reproduce the behaviour
power was suddenly off, and then re-start up the machine and resync.

How to fix this problem? 
Thanks in advanced!

**Comment by Apteryks** [comment]
I have a similar issue. I'm trying to (fast) synchronize with a long running node. I've initialized the chain with the correct genesis file (the initial hash block matches), but messages such as those appear: 

````
INFO [11-23|17:24:22] Imported new chain segment               blocks=2 txs=0 mgas=0.000 elapsed=5.319ms   mgasps=0.000 number=2  hash=911fcf…2ad
 ERROR[11-23|17:24:22]
 ########## BAD BLOCK #########
 Chain config: {ChainID: 4226 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: <nil> Engine: unknown}
 Number: 3
 Hash: 0x670b430a4c06317052bb4f233fcf8b6a30edc624eab0842e1c0803830f68a572
         receipt{med=95c1dabce50cffb9119ca331537b09e4c8f08ee0be83110ca8277271636e8202 cgas=628764 bloom=000000000000000000000000000000000000000000
 Error: invalid gas used (remote: 596764 local: 628764)
 ##############################
  
 WARN [11-23|17:24:22] Synchronisation failed, dropping peer    peer=9426f30384348faa err="retrieved hash chain is invalid"
````

The "main" node (the one with the most data) is running geth v1.6.7-stable-ab5646c5 while on my local node which is attempting to sync with it geth is at v1.7.2-stable-1db4ecdc.

**Comment by Apteryks** [comment]
I downgraded geth to 1.6.7 to match the "main" node in my setup, and the problem can be reproduced there as well (although the output is different):

````
INFO [11-24|11:20:07] Imported new state entries               count=1   flushed=0 elapsed=57.736µs  processed=731 pending=3    retry=0 duplicate=0 unexpected=0
INFO [11-24|11:20:07] Imported new state entries               count=2   flushed=1 elapsed=75.395µs  processed=733 pending=3    retry=0 duplicate=0 unexpected=0
INFO [11-24|11:20:07] Imported new state entries               count=1   flushed=0 elapsed=116.502µs processed=734 pending=19   retry=0 duplicate=0 unexpected=0
INFO [11-24|11:20:07] Imported new state entries               count=16  flushed=0 elapsed=1.357ms   processed=750 pending=275  retry=0 duplicate=0 unexpected=0
WARN [11-24|11:20:08] Rolled back headers                      count=19  header=143->143 fast=143->143 block=143->143
WARN [11-24|11:20:08] Synchronisation failed, dropping peer    peer=963201a1c83d7f03 err="retrieved hash chain is invalid"
````

And when using v1.8.0-unstable-e4c9fd29 (current master):
````
ERROR[11-24|11:27:49] 
########## BAD BLOCK #########
Chain config: {ChainID: 4226 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: <nil> Engine: unknown}

Number: 3
Hash: 0x670b430a4c06317052bb4f233fcf8b6a30edc624eab0842e1c0803830f68a572
        receipt{med=95c1dabce50cffb9119ca331537b09e4c8f08ee0be83110ca8277271636e8202 cgas=628764 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}


Error: invalid gas used (remote: 596764 local: 628764)
##############################
 
WARN [11-24|11:27:49] Synchronisation failed, dropping peer    peer=9426f30384348faa err="retrieved hash chain is invalid"
````

**Comment by sirnicolas21** [comment]
testnet using Geth/v1.8.17-stable-8bbe7207/linux-amd64/go1.10.4

> WARN [10-14|14:38:10.227] Synchronisation failed, dropping peer    peer=4e011cb2992bd7b5 err="retrieved hash chain is invalid"
> ERROR[10-14|14:38:13.851]
> ########## BAD BLOCK #########
> Chain config: {ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: 4230000 Engine: ethash}
> 
> Number: 4230605
> Hash: 0xc358b4fb016f7cc1402619f292c92a5e58a473ef5243db00d3c59b3b9b7cb827
>         &{[] 1 60243 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [243 187 199 168 18 53 24 162 161 122 18 30 241 202 87 117 210 112 10 247 80 65 63 8 98 78 43 143 75 51 120 200] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 60243}
>         &{[] 0 153689 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [205 31 96 111 85 175 162 202 210 169 226 164 102 126 135 165 45 205 210 23 78 177 238 138 177 76 232 114 203 28 106 246] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 93446}
>         &{[] 1 185665 [0 0 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 64 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 64 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 64 0 0 0 0 16 0 0 0 0 0 0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 128 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 16 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0] [0xc4bfbba6e0] [127 175 213 21 150 119 110 228 118 3 60 172 45 89 45 249 114 166 212 79 223 206 105 216 193 190 185 108 148 104 143 238] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 31976}
>         &{[] 1 317762 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 128 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 1 0 0 0 0 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 64 0 0 0 0 0 0 0 8 0 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0xc4bfbba790] [193 118 237 232 11 168 152 215 174 49 200 226 140 27 229 100 98 140 20 106 46 196 151 138 136 28 243 90 101 178 207 190] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 132097}
>         &{[] 1 432988 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [65 184 124 212 255 156 56 213 135 163 4 1 230 84 75 252 87 209 95 107 216 211 112 193 119 227 168 197 168 235 53 24] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 115226}
>         &{[] 1 3797796 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [137 53 238 224 99 215 190 236 15 19 116 48 105 76 84 104 8 4 228 21 123 72 103 200 106 96 186 45 138 219 144 221] [217 68 120 246 210 48 240 235 117 71 107 60 25 146 168 239 232 200 62 180] 3364808}
>         &{[] 1 4876783 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 128 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 64 0 0 0 0 0 0 0 64 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 16 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 16 0 0 0 0 0 0 0 0] [0xc4bfbba840 0xc4bfbba8f0 0xc4bfbba9a0 0xc4bfbbaa50 0xc4bfbbab00 0xc4bfbbabb0] [42 165 108 37 209 185 235 46 111 53 119 188 70 11 113 224 247 0 164 66 244 10 225 239 8 234 119 123 184 91 16 3] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 1078987}
>         &{[] 1 4909284 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [64 102 137 163 145 206 68 107 188 35 153 102 69 165 46 119 236 121 241 41 100 120 220 136 116 171 253 222 247 3 165 237] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 32501}
>         &{[] 1 4941785 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [52 168 27 149 154 244 138 87 128 56 245 235 223 171 48 77 51 229 21 255 35 68 120 21 36 80 208 246 112 165 150 116] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 32501}
>         &{[] 1 5667425 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [205 245 110 97 206 127 179 8 134 118 29 180 183 26 120 121 244 131 179 162 172 227 35 118 4 58 19 201 114 249 36 136] [115 47 135 223 214 146 147 51 237 108 106 77 221 108 160 214 90 129 153 66] 725640}
>         &{[] 1 6393065 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [144 254 199 153 45 248 166 174 111 179 17 54 71 68 106 103 97 162 6 130 191 216 197 48 124 234 4 201 215 87 79 160] [236 127 99 24 118 12 179 102 145 217 227 47 118 25 35 1 112 192 37 118] 725640}
>         &{[] 1 7118705 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [112 218 237 87 32 95 178 182 33 254 232 25 194 2 134 97 14 240 126 54 58 160 217 241 68 150 55 101 101 128 253 120] [10 247 225 6 97 59 64 186 157 217 252 254 43 218 83 161 206 132 171 102] 725640}
>         &{[] 1 7844345 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [198 94 75 1 208 84 63 27 141 91 120 255 74 169 105 163 204 21 136 105 47 182 50 220 80 12 54 54 139 46 169 116] [183 10 22 125 156 25 202 241 158 8 229 179 30 40 242 89 107 55 226 48] 725640}
>         &{[] 1 7905119 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 16 0 0 0 0 0 0 0 0 0 0 0 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0xc4bfbbac60] [67 71 60 194 150 45 196 195 176 102 178 235 3 111 114 209 79 154 145 30 43 244 118 163 66 235 83 219 29 195 247 128] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 60774}
>         &{[] 1 7937070 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 128 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 16 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0] [0xc4bfbbad10] [176 217 18 113 36 204 231 38 3 6 49 196 206 224 167 140 39 195 108 1 77 109 173 219 55 94 204 151 17 2 206 199] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 31951}
> 
> 
> Error: invalid gas used (remote: 7649670 local: 7937070)
> ##############################

**Comment by holiman** [comment]
For first reporter, `0x6e9bb1dfe6db737331f0be4fbc0a4cb8bfa6cf8c208188b0dfff294330a59a27` is indeed a canon block. However: 

> power was suddenly off, and then re-start up the machine and resync. 

Might have caused corruption, since power-off breaks things pretty badly, doesn't even allow the OS to fsync the files. 

For @Apteryks , please file a separate ticket if it remains, and incude the genesis used in the 'long' chain. 

For the @sirnicolas21  case, `0xc358b4fb016f7cc1402619f292c92a5e58a473ef5243db00d3c59b3b9b7cb827` is indeed _not_ a canonical block, so it's probably miined by a misconfigured node.
