### ISSUE TITLE
Get your own transactions iOS swift

### ISSUE THREAD

**Issue by flypaper0** [ethereum/go-ethereum#15361]
Geth version: `Geth (1.7.2)`
OS & Version: iOS

Hello, guys. I'm trying go get self transactions, but all I could make of was just go over blocks in a loop.

```
func getTransactions(address: String, startBlockNumber: Int64, endBlockNumber: Int64) -> [GethTransaction] {
    
    var transactions = [GethTransaction]()
    for blockNumber in startBlockNumber...endBlockNumber {
      let block = try! ethereumClient.getBlockByNumber(ethereumContext, number: blockNumber)
      let blockTransactions = block.getTransactions()!
      
      for index in 0...blockTransactions.size()  {
        guard let transaction = try? blockTransactions.get(index) else {
          continue
        }
        
        let from = try? ethereumClient.getTransactionSender(ethereumContext, tx: transaction, blockhash: block.getHash(), index: index)
        let to = transaction.getTo()
        
        if to?.getHex() == address || from?.getHex() == address {
          transactions.append(transaction)
        }
      }
    }
    return transactions
  }
```

I looked for information and maybe FiltedLogs or BloomFilter can help me. Please tell me how to use them to solve my problem?

**Comment by ligi** [comment]
Having the same problem on Android - unfortunately this seems to be a design decision and regarding a go-ethereum dev @obscuren is very passionate about this - really hoped to be able to convince him at DevCon3 to change his mind there - but he was mentioning on twitter he is not coming :-( 
A question and the info about the passionate choice at min 45:20 here: https://www.youtube.com/watch?v=cSpTyVWrXMg
