### ISSUE TITLE
Ethereum handshake failed err=EOF in Ropsten

### ISSUE THREAD

**Issue by er3es** [ethereum/go-ethereum#15370]
#### System information

Geth version: `geth 1.7.2-stable`
OS & Version: Linux

#### Expected behaviour
Connect to peers in the ropsten testnet.

#### Actual behaviour

 It seems that I cannot connect to the peers. I was fully synced yesterday but today I get the following

> DEBUG[10-25|10:23:19] Adding p2p peer                          id=6ce05930c72abc63 name=Parity/v1.8.0-unstab...                                              addr=13.84.180.240:30303 peers=1
> TRACE[10-25|10:23:19] Dial task done                           task="staticdial 6ce05930c72abc63 13.84.180.240:30303"
> TRACE[10-25|10:23:19] New dial task                            task="wait for dial hist expire (12.410515547s)"
> TRACE[10-25|10:23:19] Starting protocol eth/63                 id=6ce05930c72abc63 conn=staticdial
> DEBUG[10-25|10:23:19] Ethereum peer connected                  id=6ce05930c72abc63 conn=staticdial name=Parity/v1.8.0-unstable-9196c72-20170918/x86_64-linux-gnu/rustc1.20.0
> DEBUG[10-25|10:23:19] Ethereum handshake failed                id=6ce05930c72abc63 conn=staticdial err=EOF
> DEBUG[10-25|10:23:19] Removing p2p peer                        id=6ce05930c72abc63 conn=staticdial duration=10.060ms  peers=0 req=false err=EOF
> DEBUG[10-25|10:23:28] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
> 

#### Steps to reproduce the behaviour

`geth --testnet --syncmode full --nodiscover --verbosity 6`

and then

`admin.addPeer('enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303')
admin.addPeer('enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303')`

#### Backtrace

````
[backtrace]
````

**Comment by shmakins** [comment]
I've got the same problem
Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9

**Comment by MitchK** [comment]
Same issue here. 
```
DEBUG[11-29|17:43:57] Adding static node                       node=enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303
DEBUG[11-29|17:43:58] Adding p2p peer                          id=6ce05930c72abc63 name=Parity/v1.8.0-unstab... addr=13.84.180.240:30303 peers=1
DEBUG[11-29|17:43:58] Ethereum peer connected                  id=6ce05930c72abc63 conn=staticdial name=Parity/v1.8.0-unstable-9196c72-20170918/x86_64-linux-gnu/rustc1.20.0
DEBUG[11-29|17:43:58] Ethereum handshake failed                id=6ce05930c72abc63 conn=staticdial err=EOF
DEBUG[11-29|17:43:58] Removing p2p peer                        id=6ce05930c72abc63 conn=staticdial duration=44.125ms peers=0 req=false err=EOF
DEBUG[11-29|17:43:58] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
```

**Comment by shaolinwu** [comment]
hi guys,

I solved this issue by adding this option '--nodiscover' before entering geth console, then i am able to add the peer smoothly. It seems '--nodiscover' is the key point in private cluster configuration.

**Comment by debasish-raychawdhuri** [comment]
'--nodiscover' did not fix the problem, even though node discovery was stopped
