### ISSUE TITLE
Add a linter build job on travis

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#15372]
Currently we don't run many linters on CI, only `go vet`. That is useful to be run on all build jobs, as each different Go version has its own `go vet` (and quirks), so it's good to have all of them test our code.

However, if we introduce new linters to our CI (such as reenabling https://github.com/ethereum/go-ethereum/issues/15371), it doesn't make sense to have these run for all build steps as it would just slow down everything. Instead, we should add a simple linter job on travis whose sole purpose is to run the linters and exit. 

This build job is a good starting point to address this https://github.com/ethereum/go-ethereum/blob/master/.travis.yml#L30

**Comment by danmelton** [comment]
Working through this, PR coming.

**Comment by karalabe** [comment]
Fixed via https://github.com/ethereum/go-ethereum/pull/15416.
