### ISSUE TITLE
Transaction created by non-miner node is not mined

### ISSUE THREAD

**Issue by gaoxiangxyz** [ethereum/go-ethereum#15388]
I create a private chain, and setup two node, one is miner and the other one is not.
Block sync between two nodes is fine.
But transactions sent by non-miner node are always in pending statues and return null when using eth.getTransaction(hash) on miner node. 

#### System information

Geth version:   
When create the private chain: geth v1.7.0
Now :` Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9`
OS & Version: Windows

#### Expected behaviour
All transactions are mined.

#### Actual behaviour
Only transactions created by miner node are mined. 

**miner node:**
`geth  --networkid 12345 --datadir d:\ethereum\private --cache 512 --rpc --rpcport 18545 --rpcapi net,eth,web3,shh,personal --rpccorsdomain "http://localhost:8000,http://remix.ethereum.org" --mine --minerthreads 2`

**non-miner node:**
`geth --networkid 12345 --datadir D:\deploy\geth\data\private --cache 512 --rpc --rpcapi net,eth,web3,shh,personal --bootnodes enode://c0ad2f6260c4248c95e8377e34166777be74241757ccb2d0d1e8d1daae20ce1586b46b7225f6279ed76453224f56aff237fa9a8168104d948ca6e600652e1cea@192.168.10.232:30303`

**genesis.json:**
```
{
  "config": {
        "chainId": 12345,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
  "alloc"      : {
		"2448519d61b2f9a86ca77819061fdda5316a495c": {"balance": "100000000000000000000"},
		"3f81fe640621b3eda6681a0a1a03f20e1c72b9ef": {"balance": "111111111111111"}
	},
  "coinbase"   : "0x0000000000000000000000000000000000000000",
  "difficulty" : "0x20000",
  "extraData"  : "",
  "gasLimit"   : "0x2fefd8",
  "nonce"      : "0x0012006700002542",
  "mixhash"    : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```

**Comment by karalabe** [comment]
Please check the gas fees you are providing by your non-miner node, and the minimum fees accepted by the miner.

**Comment by gaoxiangxyz** [comment]
@karalabe how to check the minimum fees accepted by the miner？

**Comment by gaoxiangxyz** [comment]
@karalabe I set --gasprice 5000000 to miner node, and try sendTransaction again with default gasPrice  18000000000, but it still does not work.

`> eth.sendTransaction({from:eth.accounts[0],to:eth.accounts[1],value:1000000000}`

``> eth.getTransaction("0x9adee419df9628c671f6e5b043551ab3da52a46c57f87d908e003033
a18bb4b6")
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000
",
  blockNumber: null,
  from: "0xf472ea4aa875432f8b5b01bc890b73afe8a9d8c8",
  gas: 90000,
  gasPrice: 18000000000,
  hash: "0x9adee419df9628c671f6e5b043551ab3da52a46c57f87d908e003033a18bb4b6",
  input: "0x",
  nonce: 22,
  r: "0xe8a7abcc46327229891c646797a6bea7ba0696f8e056b63b4030bf37e9f82c16",
  s: "0x570288dbd8b29f64b1002c3cd235b7ad21246ed075ddf7f540bb5db9583f47c4",
  to: "0x69af1aa6473111e5bb0b7132dfa0aad32362d170",
  transactionIndex: 0,
  v: "0x6095",
  value: 1000000000
}

**Comment by karalabe** [comment]
Check `txpool.inspect` in your sender node. I'm guessing you have a lot of old transactions piled up that prevent new ones from being accepted (transactions can only ever execute in order of creation, unless the nonce is explicitly set to a different value).

**Comment by gaoxiangxyz** [comment]
@karalabe I tried to change nonce, still not mined, but transactions which set the nonce are all in the queued.
> txpool.inspect
{
  pending: {
    0xf472EA4Aa875432f8b5B01BC890B73AfE8a9D8C8: {
      19: "0x69Af1Aa6473111e5Bb0b7132dfA0Aad32362d170: 100000000 wei + 90000 ×
1 gas",
      20: "0x69Af1Aa6473111e5Bb0b7132dfA0Aad32362d170: 10000000000000000 wei + 9
0000 × 18000000000 gas",
      21: "0x69Af1Aa6473111e5Bb0b7132dfA0Aad32362d170: 1000000000 wei + 90000 ×
 18000000000 gas",
      22: "0x69Af1Aa6473111e5Bb0b7132dfA0Aad32362d170: 1000000000 wei + 90000 ×
 18000000000 gas"
    }
  },
  queued: {
    0xf472EA4Aa875432f8b5B01BC890B73AfE8a9D8C8: {
      12345: "0x69Af1Aa6473111e5Bb0b7132dfA0Aad32362d170: 1000000000 wei + 90000
 × 18000000000 gas",
      1234678905: "0x69Af1Aa6473111e5Bb0b7132dfA0Aad32362d170: 1000000000 wei +
90000 × 18000000000 gas",
      23456: "0x69Af1Aa6473111e5Bb0b7132dfA0Aad32362d170: 100000 wei + 90000 ×
18000000000 gas"
    }
  }
}

**Comment by karalabe** [comment]
So, you have nonce 19 blocking all the transactions, and that nonce has a gas price of 1 wei, so it will never get mined. You need to submit a new transaction with a high gas price but nonce 19. Alternatively you can also flush out all your transactions by stopping your node and deleting the `transactions.rlp` file from your data directory and then restart your node.

**Comment by gaoxiangxyz** [comment]
@karalabe thanks, it solved. Just curious, will the transaction with gas price of 1 wei be mined if I change minder setting to gasprice 1?

**Comment by karalabe** [comment]
Yes it will be, but transactions only ever get broadcast once, so you'd need to set the miner's price to 1 wei first, and only then make the cheap transaction.

**Comment by gaoxiangxyz** [comment]
@karalabe Does it means the old 1 wei gas transaction will never be mined ?

**Comment by karalabe** [comment]
It depends on a few factors. If the miner's fee is X, anything below X will be discarded. As such, even if you lower the price, the transaction was already thrown out by the miner, so the only way to process it, is if the miner gets the transaction back somehow. In a large network, this can happen since nodes come and go and shuffle transactions between each other. In a small private network where connections are stabe, it might happen that it's never rebroadcast. If you restart your node though it should push it out again.

**Comment by karalabe** [comment]
Of course only 1 transaction per nonce. So if your account already has a transaction processed (i.e. included in the blockchain) with a given nonce, it won't be accepted, irrelevant of price.

**Comment by gaoxiangxyz** [comment]
@karalabe Thank you very much.

**Comment by karalabe** [comment]
Cheers :)
