### ISSUE TITLE
PATH not updated

### ISSUE THREAD

**Issue by MarinAngelo** [ethereum/go-ethereum#15381]
#### System information

Geth version: 1.7.2
OS & Version: Windows
Commit hash : (if `develop`)

#### Expected behaviour
Installation without error msg

#### Actual behaviour
Message: "PATH not updated, original length 1331 > 1024"
As Mist and Ether Wallet do not work as well, I wunder if there is a correlation

#### Steps to reproduce the behaviour
Deinstalled and Reinstalled

#### Backtrace

````
[backtrace]
````

**Comment by fjl** [comment]
This is a known issue with the windows installer. See https://github.com/ethereum/go-ethereum/issues/15118
