### ISSUE TITLE
make geth

### ISSUE THREAD

**Issue by narikatel** [ethereum/go-ethereum#15383]
#### System information
OS & Version: Centos

########
[etherium@CentOS-65-64-minimal go-ethereum]$ make geth
build/env.sh go run build/ci.go install ./cmd/geth
util.go:86: git tag -l --points-at HEAD: exit status 129
error: unknown option `points-at'
usage: git tag [-a|-s|-u <key-id>] [-f] [-m <msg>|-F <file>] <tagname> [<head>]
   or: git tag -d <tagname>...
   or: git tag -l [-n[<num>]] [<pattern>]
   or: git tag -v <tagname>...

    -l                    list tag names
    -n[<n>]               print <n> lines of each tag message
    -d                    delete tags
    -v                    verify tags

Tag creation options
    -a                    annotated tag, needs a message
    -m <msg>              message for the tag
    -F <FILE>             message in a file
    -s                    annotated and GPG-signed tag
    -u <key-id>           use another key to sign the tag
    -f, --force           replace the tag if exists

Tag listing options
    --contains <commit>   print only tags that contain the commit

exit status 1
make: *** [geth] Ошибка 1

help guys install the node

**Comment by narikatel** [comment]
Upgrade git solved a problem

**Comment by yin94087** [comment]
what version of git did you upgraded to?
i am trying to do "make geth" on CentOS 6.9
