### ISSUE TITLE
make geth failed

### ISSUE THREAD

**Issue by solocshaw** [ethereum/go-ethereum#1538]
When running `make geth` I get the following error:

    build/env.sh go install -v -ldflags '-X main.gitCommit 98f4c936f25de27dbc90f36f2c1ffd1f23b114e9'     ./cmd/geth
    build/env.sh: line 32: exec: go: not found
    make: *** [geth] Error 127

Building on OS X Yosemite 10.10.5.

**Comment by fjl** [comment]
Stupid question: do you have Go installed (with Homebrew or otherwise)?

**Comment by solocshaw** [comment]
Well, thought I did since it was in `brew list`. Reinstalling fixed the issue. Thanks.
