### ISSUE TITLE
Visual Studio 2015 : - Decentralized ASP.Net Web Application Deployment Error

### ISSUE THREAD

**Issue by raiajithkumarr** [ethereum/go-ethereum#15395]
![whiledeploying](https://user-images.githubusercontent.com/22548964/32131298-54dfba44-bbc8-11e7-875e-f9b8328a695f.png)
Hi Team,
I tried to create sample Solidity -  Decentralized ASP.Net Web Application 
Compilation

 done successfully but while deploying as per ReadMe.html i got attached error.
could you please help me.

**Comment by karalabe** [comment]
I'm not really sure what or how you're trying to accomplish. If you are using some third party client library, you'll need to take up any issues with them. We do not do `ASP.Net` in this repo.
