### ISSUE TITLE
panic: interface conversion: interface is nil, not error / bloombits.(*MatcherSession).Error(...)

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#15394]
#### System information

Geth version: `geth version`
v1.7.3-unstable-0095531a/windows-amd64/go1.9"

OS & Version: Windows/Linux/OSX
Windows
Commit hash : (if `develop`)
v1.7.3-unstable-0095531a/windows-amd64/go1.9"

#### behaviour
This error occurs when opening mist after you already have a local geth client running. The geth client crashes with this error.

INFO [10-27|13:10:04] Imported new chain segment               blocks=1  txs=45   mgas=1.905   elapsed=646.666ms mgasps=2.946  number=4440691 hash=54da60â€¦779484
INFO [10-27|13:10:16] Imported new chain segment               blocks=1  txs=128  mgas=6.672   elapsed=492.994ms mgasps=13.534 number=4440692 hash=573b27â€¦b7d7fb
ERROR[10-27|13:10:23] Invalid receipt array RLP                hash=ac223aâ€¦55bdb8 err="rlp: input string too short for types.Bloom, decoding into ([]*types.ReceiptForStorage)[0](types.receiptStorageRLP).Bloom"
ERROR[10-27|13:10:23] Invalid receipt array RLP                hash=ac223aâ€¦55bdb8 err="rlp: input string too short for types.Bloom, decoding into ([]*types.ReceiptForStorage)[0](types.receiptStorageRLP).Bloom"
ERROR[10-27|13:10:23] Invalid receipt array RLP                hash=59c31aâ€¦88b988 err="rlp: input string too short for types.Bloom, decoding into ([]*types.ReceiptForStorage)[0](types.receiptStorageRLP).Bloom"
ERROR[10-27|13:10:23] Invalid receipt array RLP                hash=59c31aâ€¦88b988 err="rlp: input string too short for types.Bloom, decoding into ([]*types.ReceiptForStorage)[0](types.receiptStorageRLP).Bloom"
ERROR[10-27|13:10:23] Invalid receipt array RLP                hash=2c0eb7â€¦3f83a6 err="rlp: input string too short for types.Bloom, decoding into ([]*types.ReceiptForStorage)[0](types.receiptStorageRLP).Bloom"
ERROR[10-27|13:10:23] Invalid receipt array RLP                hash=2c0eb7â€¦3f83a6 err="rlp: input string too short for types.Bloom, decoding into ([]*types.ReceiptForStorage)[0](types.receiptStorageRLP).Bloom"
ERROR[10-27|13:10:23] Invalid receipt array RLP                hash=c970e9â€¦501d49 err="rlp: input string too short for types.Bloom, decoding into ([]*types.ReceiptForStorage)[0](types.receiptStorageRLP).Bloom"
ERROR[10-27|13:10:23] Invalid receipt array RLP                hash=c970e9â€¦501d49 err="rlp: input string too short for types.Bloom, decoding into ([]*types.ReceiptForStorage)[0](types.receiptStorageRLP).Bloom"
panic: interface conversion: interface is nil, not error

goroutine 500121 [running]:
github.com/ethereum/go-ethereum/core/bloombits.(*MatcherSession).Error(...)
	C:/gopath/src/github.com/ethereum/go-ethereum/core/bloombits/matcher.go:537
github.com/ethereum/go-ethereum/eth/filters.(*Filter).indexedLogs(0xc082bb0fc0, 0x15f40a0, 0xc05099ed50, 0x43bfff, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/gopath/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:154 +0x552
github.com/ethereum/go-ethereum/eth/filters.(*Filter).Logs(0xc082bb0fc0, 0x15f40a0, 0xc05099ed50, 0xffffffffffffffff, 0xc099adefe0, 0x1, 0x1, 0x0)
	C:/gopath/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:121 +0x377
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).GetFilterLogs(0xc048f7ca50, 0x15f40a0, 0xc05099ed50, 0xc042831590, 0x22, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/gopath/src/github.com/ethereum/go-ethereum/eth/filters/api.go:384 +0x20e
reflect.Value.call(0xc045ceca80, 0xc047bd4338, 0x13, 0xf19d7d, 0x4, 0xc054c29aa0, 0x3, 0x4, 0xc043de2bf8, 0xc054c29aa0, ...)
	C:/go/src/reflect/value.go:434 +0x90d
reflect.Value.Call(0xc045ceca80, 0xc047bd4338, 0x13, 0xc054c29aa0, 0x3, 0x4, 0x1, 0x1, 0x19)
	C:/go/src/reflect/value.go:302 +0xab
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc0478dc6e0, 0x15f40a0, 0xc05099ed50, 0x15f8c40, 0xc0b01bed20, 0xc052fafec0, 0xc0b6fd08c0, 0xc08e5a96a0, 0x81cc2a)
	C:/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:311 +0x6d5
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc0478dc6e0, 0x15f40a0, 0xc05099ed50, 0x15f8c40, 0xc0b01bed20, 0xc052fafec0)
	C:/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:333 +0x1c1
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func2(0xc07a426ff0, 0xc0478dc6e0, 0xc07819a260, 0x15f8c40, 0xc0b01bed20, 0xc0940521e0, 0x1, 0x1, 0xc0858bbe00)
	C:/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:206 +0xb4
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
	C:/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:201 +0x2b2

**Comment by karalabe** [comment]
This is fixed in latest master. Thanks for the notification!
