### ISSUE TITLE
testnet and rinkeby not syncing successfully

### ISSUE THREAD

**Issue by jordaniac89** [ethereum/go-ethereum#15392]
#### System information

Geth version: `1.7.2-stable`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour
For either testnet or rinkeby to sync successfully.

#### Actual behaviour
Both freeze at different points with different issues. 

testnet:
Will sync correctly for a while (last attempt got up to block 207998). But eventually throws `retrieved ancestor is invalid` and will stop syncing, only throwing that error every minute or so.

rinkeby:
Will also sync correctly for a while, but will evenutally get to this line: `INFO [10-27|09:19:17] Imported new state entries   count=0    elapsed=736.526µs processed=473175 pending=1  retry=1   duplicate=0 unexpected=384` and will then stick on that line (current attempt is about 25 mins stuck).

#### Steps to reproduce the behaviour
Sync 
testnet with `geth --rpcapi personal,db,db,eth,net,web3 --rpc --testnet` 
rinkeby with ` geth --rpcapi personal,db,db,eth,net,web3 --rpc --networkid 4 --datadir="rinkeby"`

I have tried deleting my chaindata for both networks, reinstalling geth and upgrading to the newest stable version, and even removing my whole Ethereum directory and letting geth rebuild it, all to no avail.

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
For rinkeby, please use `--rinkeby` to sync.
