### ISSUE TITLE
Not ether balance showing

### ISSUE THREAD

**Issue by KillariousMaximillion** [ethereum/go-ethereum#15399]
#### System information

Geth version: `1.7.2`
OS & Version: Windows

#### Expected behaviour
see my balance in my wallet for 0x502a0b0d1aa1e231e2644b061f8c30526fff61f7

#### Actual behaviour
shows 0 balance

#### Steps to reproduce the behaviour
geth --verbosity 5 console --unlock "0x502a0b0d1aA1E231e2644b061f8c30526FfF61f7" 2>> c:\Temp\gethlog.txt

web3.eth.getBalance('0x502a0b0d1aa1e231e2644b061f8c30526fff61f7')

#### Backtrace/History of what happened
Geth 1.6.1 was getting errors with blockchain

tried geth removedb and geth to refresh the blockchain

same issue gets to about the same node errors pop up

removed the physical blockchain directory and reran geth

same issue gets to about the same node errors pop up

downloaded geth 1.7.2 ran geth

got error with blockchain something wierd I can't remember anymore tried removing the blockchain directory ran again always get errors 

remove the geth directory and ran geth again

this time the whole block chain synced up 

but when I look at my balance after logging into my wallet it is 0

I don't know what to do, I have some ether in there since yesterday I am trying to use.

Thanks for any help

**Comment by smalaichami** [comment]
It looks like that you have removed your keystore directory as well along with your geth. 
If you have your keystore files/private keys stored anywhere, then you can retrieve the balance..

**Comment by KillariousMaximillion** [comment]
my ethereum directory still has my keystore files, I just removed the geth directory within the ethereum directory, the only data in there is chaindata directory, ethash directory, nodes directoryu and LOCK, nodekey, and Transactions.rlp, thinking am sure thats all that was in there before I deleted that directory as well.

is there a command I will need to run to load my keystore up again?  it is stored in my ethereum\keystore directory.

Thanks

**Comment by KillariousMaximillion** [comment]
Also if I do geth account list is does show the account for that keystore.

**Comment by KillariousMaximillion** [comment]
more info here is etherscan showing I have some ether in there:
https://etherscan.io/address/0x502a0b0d1aa1e231e2644b061f8c30526fff61f7

happened on block 4447813 and my blockchain is at number=4455600 so would think I would be able to access my account and see my balance. 

what am I missing?

**Comment by karalabe** [comment]
You need to wait until your node fully syncs before you will be able to see your balance. Fast sync doens't process individual blocks, rather it downloads the final state directly. But until it does that, your node is non-operable.

**Comment by KillariousMaximillion** [comment]
Yup, thanks for the help guys, my eth balance finally shows this morning after letting it run all night.

**Comment by smalaichami** [comment]
Very good.. the full sync was required for the balance to appear in your wallet..
