### ISSUE TITLE
libsec256k1 errors

### ISSUE THREAD

**Issue by enriquefynn** [ethereum/go-ethereum#1539]
Hi, When trying to compile geth I get the errors: http://pastebin.ca/3079052

**Comment by karalabe** [comment]
Are you sure you are using a fresh enough Go installation? Please update to 1.4.2 or later (1.5 is planned for release in a few days).

Please check your Go version with `go version`

**Comment by enriquefynn** [comment]
That was the problem, everything working now, thanks.
