### ISSUE TITLE
Android: i have keystore,how can get my privatekey

### ISSUE THREAD

**Issue by broctagonios** [ethereum/go-ethereum#15407]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by RichHorrocks** [comment]
Ideally ask technical questions on https://ethereum.stackexchange.com so the issue tracker can be used to track actual issues.

The following threads may be of use (though none are specific to Java, which I'm assuming is what you're coding in, given you're on Android):

- [How do I get the raw private key from my Mist keystore file?](https://ethereum.stackexchange.com/questions/3720/how-do-i-get-the-raw-private-key-from-my-mist-keystore-file?noredirect=1&lq=1)

- [Location of public and private keys of Ethereum account](https://ethereum.stackexchange.com/questions/15494/location-of-public-and-private-keys-of-ethereum-account?noredirect=1&lq=1)

You might also want to look at:

- https://web3j.io/ - Ethereum Java and Android integration library - might have some wallet code in there that will help.

- [ethereumj](https://github.com/ethereum/ethereumj) - Again, have a poke around a the wallet/account code.

**Comment by ligi** [comment]
Feel free to send me the link to the question after you asked on  https://ethereum.stackexchange.com - will answer it then - I do not want to answer it here to not encourage using this issue-tracker for questions.
