### ISSUE TITLE
This project is technically and ethically not fit for github

### ISSUE THREAD

**Issue by o5j5vg55bv5hv5j5f8799f9** [ethereum/go-ethereum#15405]
https://www.reddit.com/r/ethereumfraud/comments/6bgvqv/faq_what_exactly_is_the_fraud_in_ethereum/

This repo should be removed and everyone who contributed to this project should be reported to authorities and arrested immediately.

Also should be reported to Github since it's very clear this project is only meant to mislead and hurt people and has 0 technical or intellectual value with virtually every expert in crypto, including even Nick Szabo, in consensus against this obvious malicious project.

How is this still allowed to continue after doing every single unethical thing including literally [attacking other networks without permission](https://github.com/seedOnTheForestFloor/Report-WHG-To-Authorities)? Unbelievable.

**Comment by obscuren** [comment]
🤤
