### ISSUE TITLE
Error: transaction underpriced

### ISSUE THREAD

**Issue by forenbuddy** [ethereum/go-ethereum#15413]
#### System information

Geth version: 1.7.2-stable-1db4ecdc
OS & Version: Linux Debian Jessie

#### Expected behaviour

send the ether

#### Actual behaviour

erroring out

#### Steps to reproduce the behaviour

I want to send some Ethers, but constantly get an error. Sender and receiver are of course set.

```

> web3.fromWei(eth.getBalance(eth.coinbase))

4.9xxxxxxxxxxxxxx

> amount = web3.toWei(1, "ether")

"1000000000000000000"

> personal.unlockAccount(sender, "secretPassword")

true

> eth.sendTransaction({from:sender, to:receiver, value: amount})

Error: transaction underpriced
at web3.js:3143:20
at web3.js:6347:15
at web3.js:5081:36
at :1:1
```

What exactly do I have to do to send this Ether?

**Comment by holiman** [comment]
Very odd. What's the command used to start the node ?

**Comment by karalabe** [comment]
Please set the gasPrice field. I'm assuming it defaults to 0.
