### ISSUE TITLE
Is the contract data encrypted inside the contract store if I use owner modifer  ?

### ISSUE THREAD

**Issue by sivachaitanya** [ethereum/go-ethereum#15411]
So I was going through the solidity documentation and find that having Owner access modifier on top of a function prevents the data access to that particular user, Was wondering if the data is encrypted inside the contract storage such that any node having the data cannot read it ?

**Comment by rmercer93** [comment]
no, this just means people other than the set owner can't access the information/function through other contract calls.  If someone were to inspect the blockchain in another way (eg query the state, read the stuff at the contract address, or find the transactions that originally sent whatever information you're trying to hide to the contract, etc) they'd be able to read/determine everything stored. it is not encrypted! (unless you encrypt offline and send encrypted data blobs, of course :D)

**Comment by sivachaitanya** [comment]
So, youre basically saying when change the state on my contract with storing the data internally, the transaction is written to the block merkle tree, but some user with my contract address can read through the Merkle tree get the storage key associated with my contract at leaf node and able to read the data from there ? But I think although they can read it, they cant rewrite it because they cannot rewrite the previous hashes associated with it ? correct ?
