### ISSUE TITLE
(feature request) geth --testnet attach

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/go-ethereum#15412]
```
geth --testnet attach

Fatal: Unable to attach to remote geth: 
            dial unix ~/.ethereum/geth.ipc: connect: connection refused
```

what about making 

    geth --testnet attach

synonymous to

    geth attach ~/.ethereum/testnet/geth.ipc

---

Geth version: v1.7.1-stable-05101641 Linux

**Comment by peturgq** [comment]
This is not entire clear to me, @drandreaskrueger can elaborate deeper?

**Comment by drandreaskrueger** [comment]
Oh sorry.

Just a tiny feature suggestion.

Right now, when I run 

    geth --testnet attach

it fails.

Because the geth.ipc file is in a different path, and because that command behaves identical to 

    geth attach

(which expects the geth.ipc file in the default place)

**Comment by sorin** [comment]
Okay here's my first attempt at a contribution https://github.com/ethereum/go-ethereum/pull/15597

**Comment by kkamperschroer** [comment]
Hello. I believe this issue can now be closed since https://github.com/ethereum/go-ethereum/pull/15597 has been merged, which added this functionality.
