### ISSUE TITLE
Error in unlinked_binary or Error: User contains unresolved libraries. You must deploy and link the following libraries before you can deploy a new version of User:

### ISSUE THREAD

**Issue by poperechnyi1** [ethereum/go-ethereum#15414]
Hello! I read about [mappings](https://solidity.readthedocs.io/en/develop/types.html#mappings) and I tried use IterableMapping. And I followed example [iterable_mapping](https://github.com/ethereum/dapp-bin/blob/master/library/iterable_mapping.sol).

#### System information

OS & Version: Windows 10

#### Expected behaviour
Expected result after commands `truffle compile` and `truffle migrate` contract will migrate

#### Actual behaviour
Actural result I have error in binary code: ` "unlinked_binary": "0x6060604052341561000f57600080fd5b5b6103478061001f6000396000f300606060405263ffffffff60e060020a6000350416631d834a1b811461002f578063853255cc1461005a575b600080fd5b341561003a57600080fd5b61004860043560243561007f565b60405190815260200160405180910390f35b341561006557600080fd5b610048610110565b60405190815260200160405180910390f35b600073__IterableMapping_______________________637e5236456000858560006040516020015260405160e060020a63ffffffff861602815260048101939093526024830191909152604482015260640160206040518083038186803b15156100e957600080fd5b6102c65a03f415156100fa57600080fd5b5050506040518051505060025490505b92915050565b60008060008073__IterableMapping_______________________63a21ab7166000806040516020015260405160e060020a63ffffffff8416028152600481019190915260240160206040518083038186803b151561016e57600080fd5b6102c65a03f4151561017f57600080fd5b50505060405180519350505b73__IterableMapping_______________________63c8fccc6960008560006040516020015260405160e060020a63ffffffff85160281526004810192909252602482015260440160206040518083038186803b15156101ea57600080fd5b6102c65a03f415156101fb57600080fd5b50505060405180519050156103145773__IterableMapping_______________________6375a3e8e860008560006040516040015260405160e060020a63ffffffff851602815260048101929092526024820152604401604080518083038186803b151561026857600080fd5b6102c65a03f4151561027957600080fd5b505050604051805190602001805190509150915080840193505b73__IterableMapping_______________________6388d0443760008560006040516020015260405160e060020a63ffffffff85160281526004810192909252602482015260440160206040518083038186803b15156102f257600080fd5b6102c65a03f4151561030357600080fd5b50505060405180519050925061018b565b5b505050905600a165627a7a7230582007e859ad90557930a0b17bf217193ef40e157f6492404defbb3b33f19b99edbe0029",`

#### Steps to reproduce the behaviour
1. Compile this [ example](https://github.com/ethereum/dapp-bin/blob/master/library/iterable_mapping.sol)

#### Backtrace

````
[backtrace]
````

**Comment by RichHorrocks** [comment]
Hi there. I think this would be better posted as an issue under one of the other Ethereum repos, probably [`ethereum/solidity`](https://github.com/ethereum/solidity). (This issue tracker is for the Ethereum Go client.)

They'll be able to tell you if it's a) a genuine problem with Solidity/the compiler, b) just a technical issue with how you're using it, c) perhaps even a Truffle issue.

**Comment by poperechnyi1** [comment]
I solved this problem in migration file shoul commnet or delete some rows:

```
var User = artifacts.require("./User.sol");
//var itMapsLib = artifacts.require("./itMapsLib.sol");

module.exports = function(deployer) {
  deployer.deploy(User);
  //deployer.deploy(itMapsLib);

};
```
When execute command `truffle compile` and `truffle migrate` should include only contract file for deploy, not library or patterns from which they are inherited.

**Comment by holiman** [comment]
This ticket belongs either in [Solidity](https://github.com/ethereum/solidity) or [truffle](https://github.com/trufflesuite/truffle).
