### ISSUE TITLE
Can't prefund an account

### ISSUE THREAD

**Issue by magicliang** [ethereum/go-ethereum#15422]
#### System information

Geth version: `1.7.3-unstable`
OS & Version: Linux (CentOS 6.6)
Commit hash : ea5f2da39ad198e58107a79214419e31988c5e5a

#### Expected behaviour

```bash
geth --datadir=./datadir --password ./password.txt account new > account1.txt
````
>cat account1.txt
>Address: {9676b21fd03dbd2e1ae84e1e8a9072cb295306b7}

The  genesis.json is:
```json
{

	"config"     : {
                 "chainID": 1024,
                 "homesteadBlock": 0,
                 "eip155Block": 0,
                 "eip158Block": 0
	 },
        "alloc": {
            "0x9676b21fd03dbd2e1ae84e1e8a9072cb295306b7": { "balance": "0x1337000000000000000000" }
        },
	"coinbase"   : "0x0000000000000000000000000000000000000000",
	"difficulty" : "0x4000",
	"extraData"  : "0x6666",
	"gasLimit"   : "0x222222222222",
	"nonce"      : "0xdeadbeefdeadbeef",
	"mixhash"    : "0x0000000000000000000000000000000000000000000000000000000000000001",
	"parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000001",
	"timestamp"  : "0x00"
}
```

```bash
geth --identity "Ehtereum1" --rpc --rpcport "8545" --datadir datadir --port "30303" --nodiscover --rpccorsdomain "*" --networkid 1900 --verbosity 6 console
```

In the console, " eth.getBalance(eth.accounts[0])" should return 0x1337000000000000000000

#### Actual behaviour

In the console, " eth.getBalance(eth.accounts[0])" should return 0

#### Steps to reproduce the behaviour

Just follow the steps I describe above.

I think I understood the json and account correctly, and  there is no error printed during console bootstrap.

I also  tried set 0x9676b21fd03dbd2e1ae84e1e8a9072cb295306b7 as the coinbase. Nothing  changes.

**Comment by magicliang** [comment]
My bad, I skipped the init command and directly use console command. Even the  console is  bootstrapped, the account is not initialized.

**Comment by holiman** [comment]
So to recap: does this mean that it works as expected when you do `init` ? If so, please close the ticket.
