### ISSUE TITLE
Sending transactions in rinkeby not showing in etherscan

### ISSUE THREAD

**Issue by jordaniac89** [ethereum/go-ethereum#15420]
#### System information

Geth version: `1.7.2-stable`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour
Submitted transactions show up in etherscan for sender, receiver, and by txid.

#### Actual behaviour
Quite erratic. I get an acknowledgement in the logs that the TX has been sent: 
`INFO [11-03|15:46:38] Submitted transaction                    fullhash=0xf1adc980e6c720e0d7a13b9680ab43d6e76a78bbe682c1151d04238694eb771b recipient=0x55b0D36c3a605f8420eBf51B56b9561C84554B36`

At one point, I wasn't getting the acknowledgement, but noticed I got an error "The replacement transaction is undervalued". So I bumped up the gas. Now, I get the TX acknowledgement (above), but never see it logged in etherscan with the sender or receiver. I also notice that the transaction will be pending for around 30 minutes before it eventually vanishes (I'm assuming it gets rejected). I don't know of any way to see the logs of what happened to the tx, so I'm in the dark.

#### Steps to reproduce the behaviour
Send a party-to-party TX using geth and check etherscan for the result.

#### Backtrace

````
[backtrace]
````

**Comment by jordaniac89** [comment]
So, I think it might have actually been a problem with Etherscan. It appears that my transactions are visible and correct now.

**Comment by karalabe** [comment]
There was a bug with propagating replacement transactions in Geth 1.7.2 and below. Master already fixes it and some nodes on Rinkeby already run it, so transactions propagate correctly, but etherscan probably runs latest stable that might cause it to miss replacement transactions until they actually get included in a block.

**Comment by ligi** [comment]
Problem seems to have escalated - rinkeby.etherscan is not 503ing for me :-( 
![selection_187](https://user-images.githubusercontent.com/111600/32420024-77004824-c252-11e7-9aa0-f3a93a1432e5.png)

**Comment by jordaniac89** [comment]
Is there a fix? The issue now is that I send a transaction, according to etherscan the transaction sits in a pending state (right now I'm at around 30 minutes stuck in pending), then when I try to submit another transaction, it appears that my nonce hasn't been incremented, so it's treated as a replacement transaction, and unfortunately, I have no visibility under the hood as to what's going on.

**Comment by karalabe** [comment]
You can build latest master to get a properly propagating version. As to your transaction being stuck, please check `txpool.inspect` to see what your account seems to be doing. Usually it's either a nonce gap or a seriously underpriced transaction that blocks things.

**Comment by holiman** [comment]
This is the fix: https://github.com/ethereum/go-ethereum/pull/15343 .I'll close this, please reopen if the issue still occurrs.
