### ISSUE TITLE
"nonce too low" error is unreliable, as is mass trx creation in general

### ISSUE THREAD

**Issue by nmushegian** [ethereum/go-ethereum#1542]
Sometimes, when I send a transaction with a too-low nonce, it will go into the pending trx pool and immediately be rejected, while other times I'll be given an error right away (in the sendTrx callback).

If it doesn't given an error, I have to wait to see that the trxid is not in pending or in the chain to call it an error. But this condition seems to occasionally occur even for valid transactions submitted earlier, which then go on to make it into the chain. I'm the only node on my network so I don't know where else they could be getting buffered.

I am having a lot of difficulty writing reliable code for "try to deploy this, if it fails do this, if it succeeds do this" in a way that works when you run 1000 at once on one client.

**Comment by nmushegian** [comment]
Does the nonce have to be strictly incrementing? I tried a basic strictly-increasing no-collisions manual nonce strategy and those transactions were silently rejected

**Comment by tgerring** [comment]
> Does the nonce have to be strictly incrementing?

Yes, strictly incrementing is the current strategy. The number of transactions == nonce

**Comment by fjl** [comment]
The master issue for this is now #1662.
