### ISSUE TITLE
Classic noDapps lang supporting?

### ISSUE THREAD

**Issue by Nurgl** [ethereum/go-ethereum#15436]
Greetings to all SWARM developers)
I accidentally found this project, then the last two months experimented with SWARM and the source code) All this is a terrific idea!
To my opinion, there is a problem with the transition to the Dapps Web application.
At this stage of SWARM and Ethereum development, many people do not realize how to apply all this correctly. It will take a while for web developers to dive into Dapps and figure out their own way to make decentralized websites.
The project needs support for a dynamic web language, such as PHP.
I believe it is possible to be done. Since a node can broadcast HTML content, it shall be able to translate the code and process it with an interpreter which is/would be installed on each node of the network.
I could be wrong since upcoming issue of security, performance or whatever else ....
It seems to me that such projects lack of a transition period\stage. In this case, the transition phase would let time-proven web engines and CMS deployed over the network.

**Comment by karalabe** [comment]
Please take this idea to the swarm gitter channel (https://gitter.im/ethereum/swarm). This issue tracker is for tracking and discussing bugs, general chat should be done on other forums :)
