### ISSUE TITLE
Useless option is still in the document.

### ISSUE THREAD

**Issue by magicliang** [ethereum/go-ethereum#15431]
#### System information

Geth version: `Version: 1.7.3-unstable`
OS & Version: /Linux
Commit hash : ea5f2da39ad198e58107a79214419e31988c5e5a

The official document(https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options) is still showing options like this:

  --gpomin value       Minimum suggested gas price (default: "20000000000")
  --gpomax value       Maximum suggested gas price (default: "500000000000")

But geth --help lists no these options. And adding these 2 options will cause error.
If they are removed, they should be also removed in document, otherwise it will mislead users.

**Comment by darkmorpher** [comment]
Related #15304
