### ISSUE TITLE
Spelling mistake in Gas Price Oracle Wiki

### ISSUE THREAD

**Issue by Andromelus** [ethereum/go-ethereum#15432]
There is a spelling mistake in the Gas Price Oracle wiki page.

Currently:

> The base price is a moving value that is adjusted from block to block, up if **if** was lower than the lowest acceptable price, down otherwise. Note that there is a slight amount of randomness added to the correction factors so that your client will not behave absolutely predictable on the market.

Should be changed to : 
> The base price is a moving value that is adjusted from block to block, up if **it** was lower than the lowest acceptable price, down otherwise. Note that there is a slight amount of randomness added to the correction factors so that your client will not behave absolutely predictable on the market.

Page: https://github.com/ethereum/go-ethereum/wiki/Gas-Price-Oracle

**Comment by karalabe** [comment]
Fixed, thanks!
