### ISSUE TITLE
Faucet issue

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#15439]
There seems to be a problem with the rinkeby faucet currently:

![selection_191](https://user-images.githubusercontent.com/111600/32567943-d5915f56-c48a-11e7-80c6-997d66e04002.png)

**Comment by karalabe** [comment]
The chain split, like last time (needs a tiny fix). Poked one of the signers and everything's pushed through now.

**Comment by ligi** [comment]
Thanks - that was fast - <10 min from issue to closing it !
