### ISSUE TITLE
FreeBSD build

### ISSUE THREAD

**Issue by jeromer** [ethereum/go-ethereum#15434]
Hi there,

Do you plan to provide a FreeBSD (64bits) build on https://geth.ethereum.org/downloads/ in the future ?

Building from the git repo works fine, but downloading a release tarball is easier.

:)

**Comment by karalabe** [comment]
Our builds are pushed out from CI servers. I'm unaware of any CI services providing FreeBSD, but if you can point us to one, we might add it.

**Comment by jeromer** [comment]
Can't you just instruct a CI service to cross compile the go binary for FreeBSD ? (just asking)

**Comment by karalabe** [comment]
The `secp256k1` crypto library we use is implemented in C. As such, we need a C cross compiler to build the FreeBSD binaries. I'm unaware of any such cross compiling toolkit being bundled into mainstream linux distros, and we definitely don't want to maintain our own.

If there is some package out there bundled into Ubuntu, I can add it to `xgo` and enable cross compilation.

**Comment by jeromer** [comment]
I found no CI service providing FreeBSD as a base VM. And for cross-compiling we need to build a specific GCC which can cross compile for FreeBSD which you do not want to maintain (which I understand ;)).
