### ISSUE TITLE
geth --datadir

### ISSUE THREAD

**Issue by chinthukdeepu** [ethereum/go-ethereum#15433]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by RichHorrocks** [comment]
Hi there. What's the issue you're seeing..?

**Comment by smalaichami** [comment]
Looks like that this was wrongly submitted... suggest closure..

**Comment by arjunkapur95** [comment]
Yeah i believe this is wrongly submitted
