### ISSUE TITLE
accounts/keystore: add GetKey()?

### ISSUE THREAD

**Issue by mcdee** [ethereum/go-ethereum#15449]
Would it be possible to add a GetKey() method to the keystore to return a key (if available) for a given account?  Was thinking that signature would be:

    func (ks *KeyStore) GetKey (a accounts.Account, passphrase string) (*ecdsa.PrivateKey, error)

At current it is possible to obtain the private key from the keystore but requires jumping through hoops to do so (running `Export()` then manually parsing and decrypting the result).

Happy to build a PR if you are happy for it to be added.

**Comment by CrisESC93** [comment]
Hello @mcdee 
Sorry for the question but how to decrypt the private key "manually"?

**Comment by mcdee** [comment]
@CrisESC93 https://github.com/wealdtech/ethereal/blob/master/cmd/accountkeys.go provides an example.
