### ISSUE TITLE
Dropping peers

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#15455]
Hi there,

#### System information

Geth version: `geth version` 1.7.3
OS & Version: Windows/Linux/OSX    Windows
Commit hash : (if `develop`) geth-alltools-windows-amd64-1.7.3-unstable-febfea7a

#### Expected behaviour
proper syncing

#### Actual behaviour
INFO [11-10|03:49:46] Block synchronisation started 
WARN [11-10|03:49:58] Synchronisation failed, retrying         err="block body download canceled (requested)"
WARN [11-10|03:52:27] Empty head header set                    peer=154082af96349c7a
WARN [11-10|03:52:27] Synchronisation failed, dropping peer    peer=154082af96349c7a err="empty header set by peer"

#### Steps to reproduce the behaviour
Run latest develop geth on windows

#### Backtrace

````
[backtrace]
````

**Comment by Sangatdas** [comment]
How did you solve the issue?
