### ISSUE TITLE
"replacement transaction underpriced" conflicts with private blockchain with 0 gas cost

### ISSUE THREAD

**Issue by vexorian** [ethereum/go-ethereum#15469]
Hello, so I am trying to tweak geth so that it sets up a blockchain without gas costs. It works just fine by tweaking the command line parameters and the genesis block. The only issue is that we also use offline signing so we have to pick the nonce on our own.

After a geth upgrade, we started to get "Replacement transaction underpriced" at times. What I understand is that a safeguard was added to geth so that it rejects transactions that have the same nonce as a previous transaction that has failed and it doesn't have enough gas cost. But when there's no gas cost in the network we can't just increase the gas cost to ensure that this transaction goes through. I wonder if this safeguard can be disabled when the gas cost is 0?

#### System information

Geth version: 1.7.2
OS & Version: Ubuntu 16.04

**Comment by sachabest** [comment]
Same - with gasPrice = 0 on a private network, I cannot submit any new transactions from an account on a given node. This is a largely breaking change - is there a solution/workaround?

**Comment by karysto** [comment]
Having this issue as well for a private POA network, it halts transaction creation for the node. This is a breaking change, is there a solution someone has found in the meantime? I found that deleting the `transactions.rlp` file worked, but then the transaction has to be created again by the user.

**Comment by mawenpeng** [comment]
1.8.3 has the same issues.

**Comment by mawenpeng** [comment]
Searched on web, they say increasing gasPrice by 10% will work.

**Comment by holiman** [comment]
Yes, 10% rings a bell. The replacement transaction needs to be better. How can a node determine which (out of two) transactions to use, if they are equally 'good'? 
From the original description, it sounds like you are erroneously reusing nonces, thus creating "replacement transactions". That seems to be the core issue, not that you cannot reliably replace transactions in 0-cost chains. 
Changing that is not just a matter of coding -- how would it even work? What would be the logic determining what transaction is 'better' ?
