### ISSUE TITLE
geth android how to send transaction,there is error message and code

### ISSUE THREAD

**Issue by xinshuhao** [ethereum/go-ethereum#15463]
W/System.err: go.Universe$proxyerror: insufficient funds for gas * price + value

Log.i(TAG,"Start Transaction");
                KeyStore keyStore = new KeyStore(UrlBean.keyUrl,
                        Geth.LightScryptN, Geth.LightScryptP);
                Context ctx1=BaseApplication.getGethContext();
                Accounts accounts = keyStore.getAccounts();
                Account account1=null;
                Account account2=null;
                if(accounts.size() >= 2){
                    try {
                        account2 = accounts.get(0);
                        account1 = accounts.get(1);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                }
                Log.i(TAG, "Account1: " + account1.getAddress().getHex()); //Sender
                Log.i(TAG, "Account2: " + account2.getAddress().getHex()); //Receiver

                BigInt value = Geth.newBigInt(10);
                BigInt gasLimit = Geth.newBigInt(50);
                BigInt gasPrice = Geth.newBigInt(100);
                String testData = "Hello World";
                byte[] data = testData.getBytes();

                long nonce = 0; // 1. Blocks the Thread if used? Syncing maybe?
                try {
                    nonce = BaseApplication.getEc().getPendingNonceAt(ctx1, account1.getAddress());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                //long nonce = 0x00;
                Log.i(TAG, "Nonce used:" + nonce);
                Transaction transaction = Geth.newTransaction(nonce, account2.getAddress(), value, gasLimit, gasPrice, data);

                try {
                    keyStore.timedUnlock(account1, "123456",1000);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                try {
                    transaction = keyStore.signTx(account1, transaction, new BigInt(0)); // 2. Why BigInt needed?
                } catch (Exception e) {
                    e.printStackTrace();
                }

                Log.i(TAG, "Cost: " + transaction.getCost());
                Log.i(TAG, "GasPrice: " + transaction.getGasPrice());
                Log.i(TAG, "Gas: " + transaction.getGas());
                Log.i(TAG, "Nonce: " + transaction.getNonce());
                Log.i(TAG, "Value: " + transaction.getValue());
                Log.i(TAG, "Sig-Hash Hex: " + transaction.getSigHash().getHex());
                Log.i(TAG, "Hash Hex: " + transaction.getHash().getHex());
                Log.i(TAG, "Data-Length: " + transaction.getData().length);
                Log.i(TAG, "To: " + transaction.getTo().getHex());
                Log.i(TAG, "Sender: " + transaction.getSigHash().getHex()); // 3. Produces the Error-Output.

                try {
                    BaseApplication.getEc().sendTransaction(ctx1, transaction);
                } catch (Exception e) {
                    e.printStackTrace();
                }

**Comment by ligi** [comment]
Please ask questions on StackOverflow
that said - the BigInt you pass is the chainId - but I have to pass null there currently as when  passing the chainId I also get this error: 
https://github.com/walleth/walleth/issues/57
