### ISSUE TITLE
panic: runtime error: growslice: cap out of range

### ISSUE THREAD

**Issue by IsaacJT** [ethereum/go-ethereum#15462]
#### System information

Geth version: `1.7.2`
OS & Version: Linux (Gentoo AMD64)
Commit hash : 1db4ecdc

#### Expected behaviour

Geth updates the blockchain on first start.

#### Actual behaviour

Geth crashes with a stacktrace during update

#### Steps to reproduce the behaviour

Ran the following command: `./geth --fast --cache=2048`

#### Backtrace

````
INFO [11-12|12:53:21] Imported new block headers               count=0    elapsed=12.895ms  number=1596 hash=f3a659…138925 ignored=384
INFO [11-12|12:53:21] Imported new block receipts              count=35   elapsed=811.568µs bytes=7161   number=1247 hash=63d553…7d080f ignored=0
INFO [11-12|12:53:22] Imported new block receipts              count=349  elapsed=5.491ms   bytes=50649  number=1596 hash=f3a659…138925 ignored=0
INFO [11-12|12:53:22] Imported new block headers               count=0    elapsed=54.263ms  number=3644 hash=50cb51…fd74f2 ignored=2048
panic: runtime error: growslice: cap out of range

goroutine 9272 [running]:
github.com/ethereum/go-ethereum/rlp.(*encbuf).encodeString(0xc42029e3c0, 0xc45370efc0, 0xffffff3bb85b73f8, 0xffffff3bb85b73f8)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:208 +0x1d5
github.com/ethereum/go-ethereum/rlp.writeByteArray(0xea4da0, 0xc45370efc0, 0x191, 0xc42029e3c0, 0xea4da0, 0xc45370efc0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:457 +0xe2
github.com/ethereum/go-ethereum/rlp.makeStructWriter.func1(0xf03ea0, 0xc45370efc0, 0x199, 0xc42029e3c0, 0xc45370efc0, 0x199)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:537 +0x173
github.com/ethereum/go-ethereum/rlp.makePtrWriter.func4(0xe46a60, 0xc45370efc0, 0x16, 0xc42029e3c0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:580 +0xe6
github.com/ethereum/go-ethereum/rlp.(*encbuf).encode(0xc42029e3c0, 0xe46a60, 0xc45370efc0, 0xea38a0, 0xc42029e3c0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:188 +0xe6
github.com/ethereum/go-ethereum/rlp.Encode(0x7f996c279030, 0xc457528540, 0xe46a60, 0xc45370efc0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:89 +0x103
github.com/ethereum/go-ethereum/core/types.rlpHash(0xe46a60, 0xc45370efc0, 0xc447a48ea8, 0x40ade6, 0xc4478c2ea0, 0xf310ae)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/types/block.go:126 +0xbf
github.com/ethereum/go-ethereum/core/types.(*Header).Hash(0xc45370efc0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/types/block.go:102 +0x62
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).verifyHeaderWorker(0xc4200a4300, 0x182ce60, 0xc4204ee780, 0xc4449f0000, 0x800, 0x2980, 0xc455bd8800, 0x800, 0x800, 0x696, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:156 +0x2ca
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).VerifyHeaders.func1(0xc45022d6e0, 0xc444fd0000, 0x800, 0x800, 0xc4200a4300, 0x182ce60, 0xc4204ee780, 0xc4449f0000, 0x800, 0x2980, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:116 +0xff
created by github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).VerifyHeaders
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/consensus.go:114 +0x2d8

````

**Comment by rapidddenis** [comment]
Geth: 1.8.20
Linux: Ubuntu 18.04.1
Commit hash: 24d727b6

`
INFO [12-12|20:20:15.093] Importing heavy sidechain segment        blocks=2048 start=2335456 end=2337503
INFO [12-12|20:20:23.156] Imported new chain segment               blocks=113  txs=1010 mgas=65.689 elapsed=8.062s mgasps=8.147 number=2335568 hash=c3225b…f4e6e5 age=2y2mo3w cache=3.39mB
INFO [12-12|20:20:31.205] Imported new chain segment               blocks=195  txs=920  mgas=134.839 elapsed=8.048s mgasps=16.753 number=2335763 hash=1c9818…84765b age=2y2mo3w cache=3.99mB
INFO [12-12|20:20:39.227] Imported new chain segment               blocks=180  txs=1013 mgas=132.563 elapsed=8.021s mgasps=16.525 number=2335943 hash=30dd7f…c2b0d3 age=2y2mo3w cache=5.12mB
INFO [12-12|20:20:47.301] Imported new chain segment               blocks=200  txs=1620 mgas=152.012 elapsed=8.074s mgasps=18.827 number=2336143 hash=e55dc1…2a14c6 age=2y2mo3w cache=6.59mB
panic: runtime error: growslice: cap out of range

goroutine 986 [running]:
github.com/ethereum/go-ethereum/rlp.(*encbuf).encodeString(0xc0ffb788c0, 0x4100c1025e78e0, 0x2c000000000020, 0x58000000000020)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:207 +0x1a2
github.com/ethereum/go-ethereum/rlp.writeBytes(0xe9a5c0, 0xc11d786700, 0x97, 0xc0ffb788c0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:441 +0x6b
github.com/ethereum/go-ethereum/rlp.writeInterface(0xe82d40, 0xc114fa4f50, 0x94, 0xc0ffb788c0, 0xe82d40, 0xc114fa4f50)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:504 +0x127
github.com/ethereum/go-ethereum/rlp.makeSliceWriter.func1(0xe06680, 0xc114fa4ea0, 0x91, 0xc0ffb788c0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:518 +0xea
github.com/ethereum/go-ethereum/rlp.(*encbuf).encode(0xc0ffb788c0, 0xe06680, 0xc114fa4ea0, 0xc0a8d910f8, 0xc114fa4ea0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:187 +0x13b
github.com/ethereum/go-ethereum/rlp.Encode(0x11e4200, 0xc0ffb788c0, 0xe06680, 0xc114fa4ea0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:84 +0x191
github.com/ethereum/go-ethereum/trie.(*fullNode).EncodeRLP(0xc0f8a35180, 0x11e4200, 0xc0ffb788c0, 0x7f9f041911e8, 0xc0f8a35180)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/node.go:65 +0xe9
github.com/ethereum/go-ethereum/rlp.writeEncoder(0xec4500, 0xc0f8a35180, 0x16, 0xc0ffb788c0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:472 +0x91
github.com/ethereum/go-ethereum/rlp.(*encbuf).encode(0xc0ffb788c0, 0xec4500, 0xc0f8a35180, 0xf15400, 0xc0ffb788c0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:187 +0x13b
github.com/ethereum/go-ethereum/rlp.Encode(0x11e42e0, 0xc0aea3e000, 0xec4500, 0xc0f8a35180, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rlp/encode.go:89 +0xf5
github.com/ethereum/go-ethereum/trie.(*hasher).store(0xc0aea3e000, 0x11ecb80, 0xc0f8a35180, 0x0, 0x11ecb00, 0xc0f8a35180, 0x11ecb80, 0xc0f8a352c0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/hasher.go:173 +0xc2
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc0aea3e000, 0x11ecb80, 0xc0f8a75040, 0x0, 0x11eeb00, 0x11eea40, 0xc11d786200, 0x11ecb80, 0xc0faaa9b80, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/hasher.go:98 +0x181
github.com/ethereum/go-ethereum/trie.(*hasher).hashChildren(0xc0aea3e000, 0x11ecb80, 0xc0f8a75180, 0x0, 0x11ecb01, 0x11eea40, 0xc11d7957a0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/hasher.go:148 +0x18d
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc0aea3e000, 0x11ecb80, 0xc0f8a75180, 0x0, 0xc0a8d91700, 0x11eea40, 0xc11d795bc0, 0x11ecb80, 0xc0f8d6b400, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/hasher.go:94 +0x119
github.com/ethereum/go-ethereum/trie.(*hasher).hashChildren(0xc0aea3e000, 0x11ecb80, 0xc0f8a64780, 0x0, 0x428d01, 0xc1087e8f68, 0xc1168a88e8, 0x0, 0x14, 0x6b382f013966034)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/hasher.go:148 +0x18d
github.com/ethereum/go-ethereum/trie.(*hasher).hash(0xc0aea3e000, 0x11ecb80, 0xc0f8a64780, 0x0, 0x7f9f0bb95401, 0x0, 0xc0a8d919c0, 0x422208, 0x30, 0xf467a0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/hasher.go:94 +0x119
github.com/ethereum/go-ethereum/trie.(*Trie).hashRoot(0xc0fcbf2640, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:473 +0xd9
github.com/ethereum/go-ethereum/trie.(*Trie).Hash(0xc0fcbf2640, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/trie.go:447 +0x58
github.com/ethereum/go-ethereum/trie.(*SecureTrie).Hash(0xc0fcbf2640, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/trie/secure_trie.go:161 +0x3a
github.com/ethereum/go-ethereum/core/state.(*StateDB).IntermediateRoot(0xc0b9e89110, 0xc0bc44aa00, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state/statedb.go:603 +0x58
github.com/ethereum/go-ethereum/core.ApplyTransaction(0x1b02de0, 0x11e77c0, 0xc04ed7e000, 0x0, 0xc1267fee70, 0xc0b9e89110, 0xc0ab1a2b40, 0xc0b3ab8360, 0xc0a8d97170, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state_processor.go:108 +0x7ad
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc0a1bad1a0, 0xc0b3ab8510, 0xc0b9e89110, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state_processor.go:71 +0x425
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc04ed7e000, 0xc0bc39c800, 0x800, 0x900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1200 +0xae3
github.com/ethereum/go-ethereum/core.(*BlockChain).insertSidechain(0xc04ed7e000, 0xc0a60736e0, 0xc0000b15b0, 0xc0000b1501, 0x9, 0x9, 0xc0b6b9d6f0, 0x9, 0x9, 0xc0b6125860, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1369 +0x1a3f
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc04ed7e000, 0xc0b5698640, 0x9, 0x9, 0xf7eac9d4c121da01, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1139 +0x2e15
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc04ed7e000, 0xc0b5698640, 0x9, 0x9, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1088 +0xb89
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc0b4c00000, 0xc0b56985f0, 0x9, 0x9, 0x9, 0xc0b50cacc0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1490 +0x40e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc0b4c00000, 0x0, 0xc0b5846798)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1464 +0x79
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent-fm(0x8, 0x1028320)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:479 +0x2a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc0b4c00000, 0xc0b4c0bb60, 0xc0001f9720)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0x59
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0xaf
`
Also there are bunch of other errors: 
`
panic: runtime error: slice bounds out of range
panic: runtime error: invalid memory address or nil pointer dereference
fatal error: index out of range
fatal error: fault [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x6d12e3]
`

**Comment by karalabe** [comment]
The first issue was fixed, the second is different, please open a new issue.
