### ISSUE TITLE
Conflicting package name in Ubuntu PPA

### ISSUE THREAD

**Issue by israelfaria** [ethereum/go-ethereum#15468]
Hi,
The ethereum PPA is currently building from source package "ethereum" a package named "swarm". This package name is already taken by [another tool](https://packages.ubuntu.com/artful/swarm). This is causing all sorts of mixups with my apt. For instance if I don't mark swarm as manually installed everytime I do an apt-get update it will overwrite ethereum's swarm by the one on main repository. Of course this can be fixed on a variety of ways but I felt like bringing this to upstream to see if we call agree on a package rename to avoid all this.

The only workaround I have been able to pull is to use ethereum-unstable for now.

#### System information
OS & Version: Ubuntu 17.10 (Artful)

**Comment by lmars** [comment]
This is a duplicate of https://github.com/ethereum/go-ethereum/issues/3457.

**Comment by israelfaria** [comment]
Indeed. Thank you for pointing it out. Closing this one. Going to keep tabs on #3457!
