### ISSUE TITLE
Impossible reorg after fast sync of Rinkeby

### ISSUE THREAD

**Issue by ralph-pichler** [ethereum/go-ethereum#15471]
#### System information

Geth version: 1.7.3-unstable
OS & Version: OSX
Commit hash : 836314c055bebed671a392a0cf8202e57efceb41

#### Expected behaviour

Fast-syncing with Rinkeby should work

#### Actual behaviour

It did a fast sync to #1117685. Afterwards the console starts forever printing messages like
ERROR[11-13|16:34:29] Impossible reorg, please file an issue   oldnum=1117505 oldhash=d44286…dff14e newnum=1117505 newhash=d44286…dff14e
ERROR[11-13|16:34:29] Impossible reorg, please file an issue   oldnum=1117513 oldhash=63fdc3…3db293 newnum=1117513 newhash=63fdc3…3db293
ERROR[11-13|16:34:29] Impossible reorg, please file an issue   oldnum=1117515 oldhash=a86cff…3b44ab newnum=1117515 newhash=a86cff…3b44ab
ERROR[11-13|16:34:29] Impossible reorg, please file an issue   oldnum=1117517 oldhash=908861…776b15 newnum=1117517 newhash=908861…776b15
ERROR[11-13|16:34:29] Impossible reorg, please file an issue   oldnum=1117523 oldhash=3aea7e…f5f2f2 newnum=1117523 newhash=3aea7e…f5f2f2
ERROR[11-13|16:34:29] Impossible reorg, please file an issue   oldnum=1117552 oldhash=aaf223…45e2c4 newnum=1117552 newhash=aaf223…45e2c4

#### Steps to reproduce the behaviour

Initialise the datadir with the command from rinkeby.io:
geth --datadir=$HOME/.rinkeby init rinkeby.json

Start geth with the command from rinkeby.io (full node section):
geth --networkid=4 --datadir=$HOME/.rinkeby --cache=512 --ethstats='yournode:Respect my authoritah!@stats.rinkeby.io' --bootnodes=enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303

Wait for fast sync to finish. Afterwards the messages appear.

**Comment by ralph-pichler** [comment]
After an hour it finally continued to sync and everything is working properly now.
I'm still keeping the issue open for now since it explicitly said "please file an issue"

**Comment by holiman** [comment]
Can confirm the exact same thing, after the fast sync, every single block reported as "impossible reorg"
Examples:
```
ERROR[01-16|12:35:34] Impossible reorg, please file an issue   oldnum=404123 oldhash=a067b7…d9b982 newnum=404123 newhash=a067b7…d9b982
ERROR[01-16|12:35:35] Impossible reorg, please file an issue   oldnum=404162 oldhash=d7dd73…8bdc98 newnum=404162 newhash=d7dd73…8bdc98
ERROR[01-16|12:35:35] Impossible reorg, please file an issue   oldnum=404165 oldhash=a28af1…ece097 newnum=404165 newhash=a28af1…ece097
ERROR[01-16|12:35:35] Impossible reorg, please file an issue   oldnum=404168 oldhash=e15ad7…6f001a newnum=404168 newhash=e15ad7…6f001a
ERROR[01-16|12:35:35] Impossible reorg, please file an issue   oldnum=404172 oldhash=4ea2f8…8ed37f newnum=404172 newhash=4ea2f8…8ed37f
ERROR[01-16|12:35:35] Impossible reorg, please file an issue   oldnum=404174 oldhash=db6085…fe8cb6 newnum=404174 newhash=db6085…fe8cb6
ERROR[01-16|12:35:35] Impossible reorg, please file an issue   oldnum=404177 oldhash=0331f7…f4a00c newnum=404177 newhash=0331f7…f4a00c
ERROR[01-16|12:35:35] Impossible reorg, please file an issue   oldnum=404183 oldhash=386e28…b9bc9a newnum=404183 newhash=386e28…b9bc9a
ERROR[01-16|12:35:35] Impossible reorg, please file an issue   oldnum=404195 oldhash=969e2d…1fdec3 newnum=404195 newhash=969e2d…1fdec3
ERROR[01-16|12:35:35] Impossible reorg, please file an issue   oldnum=404201 oldhash=805e87…4c053a newnum=404201 newhash=805e87…4c053a
```
