### ISSUE TITLE
Unable to send ETH in new version of Mist

### ISSUE THREAD

**Issue by SphereBean** [ethereum/go-ethereum#15478]
Since I downloaded the new Mist version 9.2, I cannot send ETH from my wallet to any destination.

Thanks

**Comment by karalabe** [comment]
Unless you provide any more information, I've no idea what to do with this. Please open a ticket on the Mist repo, or provide Geth logs so I can see what might be wrong.

**Comment by SphereBean** [comment]
Hi,

How to I access the Geth logs?

Thanks,

Jeff
