### ISSUE TITLE
cmd/puppeth: Added proposed Sealer doesn't sync

### ISSUE THREAD

**Issue by corpetty** [ethereum/go-ethereum#15474]
When proposing a new Sealer amongst a set of clique authorities, attempting to deploy said approved sealer fails the initial chain sync.  

#### System information

Geth version: 1.7.3-unstable
OS & Version: Ubuntu 16.10

#### Expected behaviour
Deploy new Sealer using Puppeth, and have it sync and start to commit blocks

#### Actual behaviour
The newly deployed Sealer will start attempting to mine before chain sync is complete, and thus create a fork.

#### Steps to reproduce the behaviour
- Call `clique.propose("0x...", true)` on all current Sealers of private network
- Deploy new Sealer with "0x..." private file using Puppeth

**Comment by karalabe** [comment]
AFAIK the new miner will indeed create a single-block-fork, but when it starts syncing, it will abort mining until it finishes. Are you seeing constant mining activity during sync?

**Comment by corpetty** [comment]
I am seeing constant mining.  It does not attempt to sync after it initiates mining.

**Comment by corpetty** [comment]
FYI, re-deploying a few networks to test this.  I'll have more to update soon. 

Deploying one with pre-defined auth nodes sync fine, but manually voting to add an auth, then attempting to get that node to sync has yet to work properly.  I don't believe this is a puppeth problem.

**Comment by karalabe** [comment]
On Rinkeby we've started with 3 signers and we're currently at 6, so it should kind of work. Any more details to debug?

**Comment by corpetty** [comment]
I think this can be closed now, no @karalabe ?

**Comment by adamschmideg** [comment]
Ok, closing it
