### ISSUE TITLE
Geth should have a parameter to specify which network to connect to

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/go-ethereum#15485]
Hi there,

There is too much confusion regarding on which testnet the node is running when using the parameter: --testnet as there is no clear name. Ropsten, Kovan, Rinkbey are some of the testnets which are good for the testing. Ethereum & Mist wallet does not show you the name of the test net easily.

People are switching to Parity because of issue! Check:
[Ethereum Parity fast sync for Ropsten testnet](http://www.ziggify.com/blog/ethereum-parity-fast-setup-ropsten-testnet/)
And:
[How To Sync Entire Ethereum Client in 2-3 hours for Testnets & Mainnet](https://www.blockchain-council.org/blockchain/how-to-sync-entire-ethereum-client-in-2-3-hours-for-testnet-mainnet-parity/)

.
.
.
**# As example:**
Bellow is just an example that happen because Geth does not has a way to specify which test network to connect to:
#### Expected behaviour
Connecting to Ropsten

#### Actual behaviour
Connected to some old deprecated obsolete network nodes that is different from nodes used at ropsten.io! (This seems to happen after the fork done because of the hack on Ropsten)

#### Steps to reproduce the behaviour
If you are now trying to sync using the following command:
geth --testnet --syncmode "fast" --rpc --mine --minerthreads 1 --rpcapi db,eth,net,web3,personal --cache=1024  --rpcport 8545 --rpcaddr 127.0.0.1 --rpccorsdomain "*" --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303"

#### Suggestion to Prevent this issue:
Just like Parity, provide a parameter to select the desired network (Ropsten, Kovan, Rinkbey or anyother).

**Comment by karalabe** [comment]
`geth` -> mainnet
`geth --testnet` -> Ropsten
`geth --rinkeby` -> Rinkeby

**Comment by Muhammad-Altabba** [comment]
Thanks,
But still now geth --testnet could connect you to the Ropsten or to another deprecated obsolete network nodes that seems not to be updated after the fork. Many people are suffering and some just stopped using Geth on there machines. This is documented on many places over the internet (stackoverflow and medium) and I referenced 2 articles of them in my post. Where people are switching to Parity network after several sync fails? Who to stop the pain without several sync tries and without Parity?

**Comment by shreyaspatil221** [comment]
Error using following command -
geth --testnet --syncmode "fast" --rpc --mine --minerthreads 1 --rpcapi db,eth,net,web3,personal --cache=1024 --rpcport 8545 --rpcaddr 127.0.0.1 --rpccorsdomain "*" --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303"

Error : etherbase missing: etherbase must be explicitly mentioned

**Comment by milkeg** [comment]
Could Geth also have a flag for Kovan?
```geth --kovan -> Kovan```

**Comment by nei-oliveiraneto** [comment]
@shreyaspatil221 You should not pass the flag `--mine` without first setting up an account.
I usually open a JS interpreter from which I can control my geth node with `geth attach ~/path/to/datadir/geth.ipc`, then I set up an account, maybe from a privatekey, maybe create a new one.

To specify a data dir you have to pass `--datadir=~/acme/data5` as an argument to geth.

**Comment by holiman** [comment]
@milkeg geth doesn't support kovan (nobody has implemented the kovan engine in geth). 
@shreyaspatil221 you need to specify the mining reward address for mining
@Muhammad-Altabba @karalabe already answered the original question, so I'll close this
