### ISSUE TITLE
Add menu icons to the dashboard

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#15486]
@kurkomisi The dashboard menu is way too empty, please integrate [Font Awesome](http://fontawesome.io/icons/) and add the following icons to the menus:

 * http://fontawesome.io/icon/home/
 * http://fontawesome.io/icon/link/
 * http://fontawesome.io/icon/credit-card/
 * http://fontawesome.io/icon/globe/
 * http://fontawesome.io/icon/tachometer/
 * http://fontawesome.io/icon/list/

![Menu](https://i.imgur.com/edbdNOm.png)

**Comment by kurkomisi** [comment]
Done.
