### ISSUE TITLE
swarm: Create private storage and metrics API

### ISSUE THREAD

**Issue by holisticode** [ethereum/go-ethereum#15481]
For swarm, it would be good to be able to collect stats and metrics on a node concerning storage (chunks, local DB, etc.) and chequebook properties (consumed and delivered services, service peers, balances, cheques, etc.).

The documentation for this new API will be maintained at: https://github.com/ethersphere/swarm/wiki/Storage-and-metrics-API

**Comment by karalabe** [comment]
Take a look at how we collect various system metrics currently via `go-metrics` in our code. I think you can fairly trivially add any metric you wish to collect to that subsystem.

**Comment by holisticode** [comment]
This is a high level ticket which encompasses several issues.

* A general swarm metrics system for network testing and observability has been implemented with ticket https://github.com/ethersphere/go-ethereum/issues/183, using the `go-ethereum` metrics code
* p2p accounting metrics have been implemented with PR https://github.com/ethersphere/go-ethereum/issues/845 and https://github.com/ethersphere/go-ethereum/issues/1005
* There is an open ticket to document the p2p accounting metrics, which are user facing, here https://github.com/ethersphere/go-ethereum/issues/1036

For these reasons it is best to close this high level ticket. For further needs about metrics new tickets can be created
