### ISSUE TITLE
Disallow `--lightserv` in light mode

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#15492]
Currently Geth seems happy to accept `--lightserv` in combination with `--light`/`--syncmode=light`. This doesn't really make any sense. Let's forbid it!

We should expand these https://github.com/ethereum/go-ethereum/blob/master/cmd/utils/flags.go#L958 with an exclusivity check between `--lightserv`, `--light` and `--syncmode=light`.

**Comment by zigguratt** [comment]
I totally agree! :)

**Comment by MysticRyuujin** [comment]
I assume that means we should add:
`checkExclusive(ctx, LightModeFlag, LightServFlag)`

But I don't know how to define a checkExclusive on SyncModeFlag's value?

**Comment by karalabe** [comment]
That's the question needs solving, yes :)

**Comment by tsarpaul** [comment]
Hi, I made a solution with interface{} as you suggested in Mystic's commit.
Just waiting for a pull request to be merged on the CLI package for convenience:
https://github.com/urfave/cli/pull/685
