### ISSUE TITLE
invalid merkle root

### ISSUE THREAD

**Issue by gaoxiangxyz** [ethereum/go-ethereum#15504]
#### System information

Geth version: `1.7.2`
OS & Version: Windows

#### Expected behaviour
Sync data

#### Actual behaviour
Get below error when sync to around 40k block:
```
ERROR[11-17|15:35:11]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EI
P155: 0 EIP158: 0 Byzantium: 0 Engine: ethash}

Number: 41437
Hash: 0xb66a993f7addbc628a225ae6e878dca39a5c12d15d54680d50dbe4e487a3c96b


Error: invalid merkle root (remote: e992a0b20f5ea31a385347ccd5c50499be50936ce968
930fb660ec0a21d823e2 local: 5a45c2ec34a66f41f4803d0bfa4b089faea650f2c41035e8319e
ddb9f1b15fc9)
##############################

WARN [11-17|15:35:11] Synchronisation failed, dropping peer    peer=ad19e4657d1d
9467 err="retrieved hash chain is invalid"
INFO [11-17|15:35:11] Fast sync complete, auto disabling
```

The chain is a private chain. I have tried to remove db and re-init genesis file. But it is same. First 40k blocks are fine.

**Comment by karalabe** [comment]
Did you create this private chain using a Byzantium enabled Geth? Seems that 1.7.2 simply considers that particular block to have an invalid transaction in it.

Btw, you are using the same ChainID as mainnet, which means every transaction you sign on your private network will be replayable on the main network.

**Comment by gaoxiangxyz** [comment]
@karalabe 
We set 0 to byzantiumBlock in genesis file. Is it a bug?
What is the down side if transaction will be replayable on the main network?

Genesis file:
```
{
    "config": {
        "chainId": 1,
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "ethash": { 
            "params": {
			}
        }
    },
    "nonce": "66",
    "difficulty": "1584382",
    "extraData": "0x416c657820516909093730303030300a416e62616e67205a68750...",
    "gasLimit": "1000000",
    "alloc": {
        "0x1fd413ca423ff472ab7e44683e9b86a1b7afa524": { "balance": "700000000000000000000000" },
        "0x849e9549720f171be5cf027e0049ac843ff97eee": { "balance": "20000000000000000000000" },
        "0xe897dde41d6e343d2645044421be9b71800535ab": { "balance": "50000000000000000000000" },
        "0x141a16d67034315563bf29f2543c84ed9579bac1": { "balance": "500000000000000000000000" },
        "0x725c97856893c6fe2fbd7ffbb0fffe334c3a7545": { "balance": "500000000000000000000000" },
        "0x1a070230e4632dfe1cf7cb1d9c6214abed69c10f": { "balance": "1000000000000000000000000" },
        "0x18dd1da3e5ed33234f028f277428778d784847b8": { "balance": "1000000000000000000000000" },
        "0x212d7058aeb9dcb9d7ece2e738990dc7d8616c5e": { "balance": "50000000000000000000000" },
        ...
}

```

**Comment by gaoxiangxyz** [comment]
The bad block number changes after geth restart, but it is always around 40k

**Comment by karalabe** [comment]
But what version of Geth did you use to generate the existing blocks?

**Comment by karalabe** [comment]
> What is the down side if transaction will be replayable on the main network?

You execute a transaction in your own network, and that transaction becomes valid on mainnet, so if you have ether in an account on mainnet with the same key, the transaction will be able to move funds.

**Comment by gaoxiangxyz** [comment]
@karalabe Sorry, it is my mistake, the geth used to generate the existing blocks modify the block reward account.

> You execute a transaction in your own network, and that transaction becomes valid on mainnet, so if you have ether in an account on mainnet with the same key, the transaction will be able to move funds.

If I modify the ListenAddr, DiscoveryV5Addr of p2p config, will it still happen?

**Comment by upers** [comment]
I have same problem in my private POA net.
I got error:
---------------------------------ERROR--------------------------------------
Error: invalid merkle root
########## BAD BLOCK #########
Chain config: {ChainID: 452 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: clique}

Number: 1626771
Hash: 0x53e5c4ded722ddbe00dbd8c153aa3b64741d15b5d731f5ffe745b2e1bca2d259
----------------------------------------------------------------------------------------
I fixed this by restarting all nodes and adding peers manually through the get.ipc.

But in 10 hours  all my nodes stopped synchronizing and accordingly ceased to create blocks.
And there no error messages in log, only: "Signed recently, must wait for others."
I have 5 nodes.
I added peers manually, it didn't work.
Geth version: 1.8.3-stable.
Go version: go1.10.1
OS: ubuntu 16.04
Genesis file:
{
  "config": {
    "chainId": 452,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "byzantiumBlock": 4,
    "clique": {
      "period": 3,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x5ac632c4",
  "extraData": "0x00000000000000000000000000000000000000000000000000000000000000002368c95eb9ea3578a20d6887ccb40773499b93d5c67be939661d2559acfb059fc1737a2ceaaed4ae0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "2368c95eb9ea3578a20d6887ccb40773499b93d5": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    },
    "c67be939661d2559acfb059fc1737a2ceaaed4ae": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}

**Comment by liwei00wade** [comment]
@upers 
do you resolve  the problem ?

**Comment by upers** [comment]
@liwei00wade 
POA network has not been restored.
But was detected reason why it was happen.
My network was produce one block each 3 second (This parameter was set up in genesis.json), it is unacceptable. POA network can produce one block in 5 second or more.
As for now my POA network produce one block in 7 seconds and work fine more then 5 month.
We have 5 nodes that are able to vote on producing blocks.

**Comment by immartian** [comment]
I'd suggest Ethereum team provide some detail dissections of data structure to block storage, which can greatly help debug any errors in the future.

**Comment by upers** [comment]
> @upers
> do you resolve the problem ?

period property should be more then 5 second and this case won't happen If we talk about restoring, it wasn't solved

**Comment by shivam201312** [comment]
Hi @upers @liwei00wade @gaoxiangxyz @karalabe  .
i am new to blockchain .
I have already running instance of etherum blockchain. i have two task : 
1) Create node/ mine the etherum blockchain
2) Move etherum blockchain from one aws instance to another.
When i am trying to mine blockchain.it is giving me above reported error .
Question :
1) Any suggestion how you have solved above error ?
2) Best way to move blockchain from one instance to another instance ?
