### ISSUE TITLE
Make trace errors more user friendly

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#15500]
If we try to trace a transaction for which we don't have the state any more (e.g. via `debug.traceTransaction("0xb44ab4e708611c6cd2125bdedc013e922e876a6e1d45750541f258b14ae57c48")` on Rinkeby with a recently synced node), Geth returns an error along the lines of `missing trie node 2361beabb6dd28f9d58136dd5648cfdc7336975ca6c86038c799a880d64de65d (path )`. While this is perfectly valid, it may not be the most helpful message to a user. We should catch missing trie node errors in the tracers and convert them into `required historical state unavailable`.

**Comment by manicprogrammer** [comment]
I'll be glad to take this one. Seems simple enough and I am always interested in making tracing and error messages more digestible and actionable. I will take more time than is needed to fulfill so that I can use the opportunity to dig through and learn the system.

**Comment by karalabe** [comment]
Sure! I don't think this task will take much, but feel free to familiarize yourself with the tracing stuff. I'm doing some rewrites btw, so things might change in the near future.

**Comment by manicprogrammer** [comment]
I made the small change(s) that are needed. And need to run a small test. There are some things in code that do not need a unit test and this is arguably one of them so unless someone specifically wants that overheard I'll not create a unit test for this specific item.
