### ISSUE TITLE
geth.exe

### ISSUE THREAD

**Issue by bipradas2** [ethereum/go-ethereum#15515]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
Please give more information or close this issue. Also note you might want to ask questions on https://ethereum.stackexchange.com/ - this is an issue tracker for issues
