### ISSUE TITLE
GETH 'account new' address generation has become very slow

### ISSUE THREAD

**Issue by ethought** [ethereum/go-ethereum#15511]
Hi there,

Address generation on our production system has become very very slow all of a sudden.

New addresses are taking at least 60 seconds to generate.

Current keystore has around 55000 json keys.

Any ideas on why this is happening and how to fix it?

#### System information

Geth version: 1.7.2
OS & Version: Debian 8.9
RAM: 128GB

**Comment by holiman** [comment]
With no previous files in keystore: 

```bash
#time yes | build/bin/geth --datadir ~/tmp/account_gen account  new
Your new account is locked with a password. Please give a password. Do not forget this password.
!! Unsupported terminal, password will be echoed.
Passphrase: 
Repeat passphrase: 
Address: {793d9fe4d8c2d41150a060509095c6e71de517f7}

real	0m0.751s
user	0m0.736s
sys	0m0.016s
```

With 55K accounts: 

```

#time yes | build/bin/geth --datadir ~/tmp/account_gen account  new
Your new account is locked with a password. Please give a password. Do not forget this password.
!! Unsupported terminal, password will be echoed.
Passphrase: 
Repeat passphrase: 
Address: {9f76905f7dca6725efba11a4951f12e93a89c445}

real	0m46.258s
user	0m48.400s
sys	0m1.656s

```

On commit `7a045af05b93c323f63c7af41423ded701ce3890` (with 55k accounts)

```
#time yes | build/bin/geth --datadir ~/tmp/account_gen account  new
Your new account is locked with a password. Please give a password. Do not forget this password.
!! Unsupported terminal, password will be echoed.
Passphrase: 
Repeat passphrase: 
Address: {f42b6664fb7b6a7d672a379c5cf479b5b1763043}

real	0m2.528s
user	0m2.412s
sys	0m0.436s

```

On commit `88b1db728826efd499ea407579f41e8b683d6b53` (with 55k accounts):

```
#time yes | build/bin/geth --datadir ~/tmp/account_gen account  new
Your new account is locked with a password. Please give a password. Do not forget this password.
!! Unsupported terminal, password will be echoed.
Passphrase: 
Repeat passphrase: 
Address: {b3d522cbff4c47cfeee5252e29729b52ada68b3a}

real	0m46.971s
user	0m49.480s
sys	0m1.524s

```

So yes, it's definitely related to https://github.com/ethereum/go-ethereum/pull/15171 :/

**Comment by holiman** [comment]
This is the culprit: https://github.com/ethereum/go-ethereum/pull/15171/files#diff-1dc4ca031a26e626f6d2ad579973e410R223

**Comment by ethought** [comment]
Any ETA on when this will be fixed in master or binaries? Thanks

**Comment by holiman** [comment]
We have a release coming up very soon, I'll try to get a fix in for that, but no promises

**Comment by ethought** [comment]
Would very much appreciate if you could get this into the next release. Currently our exchange is not able to produce addresses fast enough for demand.

**Comment by karalabe** [comment]
@ethought It will be part of the next release. Doing final reviews and merges on the fix now. Will release in the morning (it's a bit late today).

**Comment by ethought** [comment]
@karalabe Thank you very much!!
