### ISSUE TITLE
cmd/puppeth: main page/custom text for dashboard

### ISSUE THREAD

**Issue by holgerd77** [ethereum/go-ethereum#15519]
Puppeth is now used for live test networks and the dashboard is deployed on the web, e.g. http://network.giveth.io/.

It would be nice, to have the possibility to customize the dashboard a bit, e.g. to write some introductory text about the specific test deployment, usage instructions, additional notes,...

This could e.g. be done by adding another app type for the dashboard "Main page" and ask the user for some short texts (introduction, usage, about,...) and then add this to a pre-formatted main page (just as a first idea, might not necessarily be the optimal way).

**Comment by karalabe** [comment]
A side "idea" for this is to have the ethstats "message" (`This page does not represent the entire state of the ethereum network - listing a node on this page is a voluntary process.`) customizable.
