### ISSUE TITLE
Faucet problem

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#15518]
![selection_195](https://user-images.githubusercontent.com/111600/32984281-87c4b194-cc71-11e7-9d35-97c8e1df4caa.png)

**Comment by karalabe** [comment]
Seems to be working now. I think the faucet just lost all its LES peers for a moment. Although tbh I've seen that the faucet has only 1 peer lately since LES/2. That might be a different issue that needs figuring out.

**Comment by ligi** [comment]
Like that the faucet is testing LES ;-) 
Closing this as it gone for now - will reopen when I see it again
