### ISSUE TITLE
How to execute deployed contract by mobile geth API?

### ISSUE THREAD

**Issue by fromageblanc** [ethereum/go-ethereum#15524]
Hello.
I am a Japanese developer working on Ethereum.
I am looking for a tutorial.
How to execute deployed contract (based on ERC 20) by mobile geth?
Please tell me where the sample code is located.

#### System information
geth version : iGeth/v1.7.2-stable/darwin-arm64/go1.9
Xcode 9 / Swift 4.0

thanks.

**Comment by RichHorrocks** [comment]
Ideally ask technical questions on https://ethereum.stackexchange.com - it's important to keep issue trackers clear and for real issues only.

For recommendations on tutorials, Reddit might actually be a better place to ask: https://www.reddit.com/r/ethdev/

**Comment by karalabe** [comment]
Some modifications ended up in the ABI package that broke some things I believe. I'll try to get the `abigen` code generator up and runnign again for Java in the 1.8.0 release and also write up the documentation for it.

**Comment by ligi** [comment]
In the meantime - if it is just about ERC-20 transactions you can also easily craft them yourself like this: https://github.com/walleth/kethereum/blob/master/functions/src/main/java/org/kethereum/functions/TransactionFun.kt#L17

**Comment by macteo** [comment]
Based on the environment I think the goal was to use swift, not Java. Does abigen support swift or objective-c?

**Comment by ligi** [comment]
I think this issue can be closed. For further questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
