### ISSUE TITLE
bootnode is not working i have check the logs with verbosity 9 its shows ping pong but it dropped peers 

### ISSUE THREAD

**Issue by marfintack** [ethereum/go-ethereum#15534]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Please provide additional details on what you see, and what you expect to see. "not working" isn't something we can help you with.

**Comment by marfintack** [comment]
As described in documentation i first generate key for bootnode then start
it and it shows listening on udp by showing url.
Then on other node i had specified that address with server ip and port in
--bootnodes flag and the bootnode is showing ping,pong but its not
connecting when i execute admin.peers it shows empty.

**Comment by karalabe** [comment]
The `bootnode` is not a full node. That one is just a UDP based peer discovery aid. They are just used to find other nodes in the network.

Note, for mainnet and Rinkeby, we use full nodes as bootnodes to help with connectivity, but the `bootnode` command itself is not a full fleged node.

**Comment by marfintack** [comment]
I am saying the same thing it is not connecting me with other nodes. I did
things as required in documentation but its not working.

**Comment by marfintack** [comment]
Its not the mainnet or test its private network where i want to discover
and connect with other nodes that are on same network with their networkid.

**Comment by seemywingz** [comment]
+1

**Comment by brianantonelli** [comment]
I'm also having the same issue with docker compose.. Supplying `--bootnodes enode://foo@1.2.3.4:30303` doesnt automatically peer during start. Running the same encode through `admin.addPeer()` works flawlessly. Am I missing something?
