### ISSUE TITLE
Set puppeth ssh deployment key

### ISSUE THREAD

**Issue by karysto** [ethereum/go-ethereum#15532]
After using Puppeth for the past few months, I've ran into this issue a few times when I want to deploy to several remote hosts. Puppeth is hardcoded to use the user's default ssh private key `id_rsa`, which forces users like myself to rename ssh keys temporarily so that Puppeth will detect the key and deploy to the host.
 
A possible solution might be to have another prompt step during the deploy option where you could input an ssh key name and have Puppeth use that key instead when sshing into the remote host.

Hardcoded private key file line:
https://github.com/ethereum/go-ethereum/blob/master/cmd/puppeth/ssh.go#L74

#### System information
Geth version: 1.7.2-stable
OS & Version: Ubuntu 16.04

**Comment by karalabe** [comment]
Yes, @holiman also requested that we add a feature to chose the SSH keys if multiple ones are present. I think this would be a good change :)

**Comment by lgalabru** [comment]
Hello there!
What's the status on this? 
Instead of asking for the ssh key, is there a way to rely on the .ssh/config, and just use the key matching with the remote server's address?
Amazing work, thanks!
