### ISSUE TITLE
Geth attach is not showing my balance

### ISSUE THREAD

**Issue by aaressinfomedia** [ethereum/go-ethereum#15535]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.7.2`
OS & Version: Windows

#### Expected behaviour
after executing "geth attach" command it gives me the default coinbase account and show my balance . and should communicate with my node

#### Actual behaviour
when fire the geth attach command it gives me an coinbase account and shows me the block no as 0 and time as 31-dec-1970 IST. also it shows my coinbase account as 0 

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
You need to wait until you node finishes syncing.

**Comment by aaressinfomedia** [comment]
@karalabe 
as you said i put my server on syncing but after a long time it just stopped syncing the blocks.the only last 200-300 blocks are remained but it taking a huge time to complete sync
