### ISSUE TITLE
Windows archives on download page are v1.3.3

### ISSUE THREAD

**Issue by jackvreeken** [ethereum/go-ethereum#15531]
(Also commented on a possibly related [Mist issue](https://github.com/ethereum/mist/issues/3292))

The 32-bit and 64-bit archives (v1.7.1, v1.7.2 and v.1.7.3) on the [Geth download page for Windows](https://geth.ethereum.org/downloads/) seems to download version v1.3.3 instead (at least that is what `geth --version`  shows). I am not sure where Mist is downloading the node from, but when I remove it and let Mist download it, I end up with the same version. My guess is that it is downloading from the same location, and that some people (myself included) have unknowingly ended up on the wrong side of the Byzantium chain split.

Downloading the Linux binary archive of Geth (64-bit) does give me the right version. So there is probably something wrong with the Windows build/packing/distribution service of Geth. I have not tested the Windows installers.

Note: I was tipped off by long lasting insane disk usage of geth.exe in Task Manager when syncing (and long sync times). I remember this being an issue in the past, which made me check what was going on.

**Comment by karalabe** [comment]
Are you sure you are running the correct version of Geth? Noone reported issues about this, Mist is using these bundles itself too, and 1.3.3 would not even sync Homestead, not to mention Tangerine, Spurious and Byzantium hardforks. Someone would have already reported it otherwise. Perhaps double check at your end?

**Comment by jackvreeken** [comment]
Yes, I think there is something wrong with my system then. Just tested on a different Windows PC (which I couldn't these past few days), and here it seems to download it fine. I will check tonight if by any chance I have an old geth.exe somewhere on my PATH, because I did not check for that.

**Comment by karalabe** [comment]
:) Glad to hear it. Closing then :)
