### ISSUE TITLE
Faucet: insufficent funds

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#15546]
![faucet_problem_3](https://user-images.githubusercontent.com/111600/33176160-15c3a884-d02c-11e7-9faf-e87d855c71ef.png)

**Comment by karalabe** [comment]
I looked through the logs. The faucet didn't have an upstream connection at that particular time, so I'm guessing it assumed it has 0 ether available.

```
WARN [11-23|13:52:06] Failed to update faucet state            block=1292753 hash=7b1433…a3098b err="can't fetch trie key 8484452e4f0c1a9f115c52b4ac78a0de2f1b0ab1a4aae8390426ac71e03f8779: no suitable peers available"
```

**Comment by karalabe** [comment]
Yes, that seems to be the issue. I just saw the same error when for a bit the number of peers dropped to 0.

**Comment by karalabe** [comment]
Will need to debug this, this only started happening since the switchover to les2

**Comment by ligi** [comment]
Thanks for the follow-up - good test for LES2 ;-)

**Comment by wbt** [comment]
This same issue is recurring now.
