### ISSUE TITLE
The model of emission and de-emission of a coin as in Novacoin.

### ISSUE THREAD

**Issue by Foxcool** [ethereum/go-ethereum#15544]
The model of emission and de-emission of a coin as in Novacoin.

Vitalik Buterin mentioned the idea of de-emission coins through the destruction of the commission. Idea's great. Immediately recalled the economic model in Novacoin. In addition to the fact that the commission is being destroyed, but not going to POS miners, the current emission size is affected by the PoS complexity.
When little money is burned in the economy, the coin holders do not invest them in the work of contracts, distributed applications and organizations, and the minibuses. This increases the difficulty by lowering the reward (the percentage of the output that the unit is catching). Thus, the total money supply arrives more slowly or even decreases or stays in one place.

When coins begin to be used in a real economy, they can not mine. The complexity decreases and the emission increases.

Thus, it is possible to ensure minimum or maximum inflation, depending on the state of the domestic economy. You can think through and configure the rules for changing such parameters.

Also from Novacoin you can take the principles of mining for an eccolator society. PoS mining is available to everyone even with small outlets. Everyone has a chance to catch the block, although it depends on the size of the exit. The size of the award can be limited from above.

**Comment by karalabe** [comment]
Perhaps another forum would be a better place for this post? This is a bug tracker for go-ethereum, so it's unlikely you'll get any feedback or even comments here. If you'd like to discuss protocol improvements, directions, please open an issue on the EIP repo https://github.com/ethereum/EIPs. Alternatively feel free to discuss on Reddit, Twitter, Medium. Closing here as it's out of scope.
