### ISSUE TITLE
geth syncing keeps falling behind

### ISSUE THREAD

**Issue by kiahmed** [ethereum/go-ethereum#15554]
Hi ,
I am running geth node on a pretty robust server with lots of disk space, memory and processor (screenshot attached). Once geth fully syncs and I connect mist wallet to it it shows the latest blocks and number of peers all that. Next time I try to connect it shows at 6000-8000 blocks behind and need to wait and dont get the latest txs. Right now, it would never catch up with the latest blocks. There is not error/warning in geth console. How can I keep geth syching upto date? Its running 24*7*365
I remember it happened with way early version of geth too almost a year ago..so definitely its not related to this particular version.
![capture](https://user-images.githubusercontent.com/28849607/33234097-ca2a5c6e-d1ee-11e7-97c9-40f46bcf6168.PNG)
![geth](https://user-images.githubusercontent.com/28849607/33234100-d2ffad6c-d1ee-11e7-84ff-b863505e8dc5.PNG)

#### System information
Geth
Version: 1.7.2-stable
Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: windows
GOPATH=
GOROOT=c:\go
#### Expected behaviour
once fully snitched, it should be able to keep up with latest blocks

#### Actual behaviour
synching keeps falling 6000-8000 block behind.

#### Steps to reproduce the behaviour
let geth run and connect mist/eth wallet to it. Once it shows blocks are fully synced, in next hours/days it falls way behind on its own? 

#### Backtrace

````
[backtrace]
````

**Comment by MitchK** [comment]
We also have the same issue here: https://github.com/ethereum/go-ethereum/issues/15267

**Comment by AFDudley** [comment]
https://github.com/ethereum/go-ethereum/issues/15602
https://github.com/ethereum/go-ethereum/issues/15664
https://github.com/ethereum/go-ethereum/issues/15681
All appear to be the same issue.

**Comment by HugoPoi** [comment]
Geth get stuck and being very slow to sync 1 minute for a block after a fast sync. See logs
```
INFO [01-02|21:11:08] Imported new chain segment               blocks=1 txs=130 mgas=5.224 elapsed=1m28.520s mgasps=0.059 number=4590436 hash=932055…e8f55b
INFO [01-02|21:11:09] Imported new chain segment               blocks=1 txs=1   mgas=0.021 elapsed=488.803ms mgasps=0.043 number=4590437 hash=bb8b52…cd6bdd
INFO [01-02|21:11:17] Imported new chain segment               blocks=1 txs=4   mgas=0.204 elapsed=8.520s    mgasps=0.024 number=4590438 hash=a974fb…098550
INFO [01-02|21:12:06] Imported new chain segment               blocks=1 txs=81  mgas=2.707 elapsed=48.988s   mgasps=0.055 number=4590439 hash=419676…16823d
```
I 'm currently using `Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9.2`. Nothing appear in logs with verbosity 3.

**Comment by whardier** [comment]
I have two xeon systems with fast arrays that have fallen behind.. doesn't appear to be an I/O issue based on conversations with friends throughout my area that are having issues.

I run these machines at an ISP and also have a system at my home office with gigabit Internet suffering from the same issue.

Can't actively contribute to Ethereum like this.  For users that use the keychain and geth node for transactions they are SOL unless they use a public node.

My options (I do database research):

geth --rpc --ws --wsorigins=*

Version:

(Ubuntu) 1.7.3-stable-4bb3c89d

**Comment by gernotpokorny** [comment]
same problem. My node is always behind.

**Comment by kiahmed** [comment]
running a geth node is almost impossible..like Charles said..not an eth hater but their vm needs performance and syncing definitely doesnt work

**Comment by mihaifm** [comment]
Same here, full node is always behind ~100 blocks. Ubuntu 17, geth 1.8.3

**Comment by GeeeCoin** [comment]
Geth fails to stay in sync...as soon as it syncs.

#### System information

Geth version: `1.8.6`
OS & Version: Ubuntu 16.04
Hardware: AWS t.medium 4GB 2 core 1TB SSD

#### Expected behaviour

Geth remains synced to network.

#### Actual behaviour

As soon as sync is complete, i.e., `eth.syncing == false`, synchronization fails. Checking the log reveals multiple peers being dropped:

```
[04-23|18:52:21] Synchronisation failed, retrying         err="block download canceled (requested)"
Apr 23 18:52:39 ip-xxx-xx-xx-xx geth[21609]: WARN [04-23|18:52:39] Synchronisation failed, dropping peer"
```

"Synchronisation failed, dropping peer" occurs up to 8 times before my client begins to import new chain segments again. The `eth.syncing.highestBlock` fails to update its value during the resync process.

#### Steps to reproduce the behaviour

Run geth. Intermittent.

**Comment by GeeeCoin** [comment]
****downgrading to v1.8.3 solves the issue**

**Comment by ndelvalle** [comment]
I have the same problem, any news on how to solve this?
```
Version: 1.8.13-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: darwin
```

**Comment by BeOleg** [comment]
This is a legit issue 👍

**Comment by holiman** [comment]
Please open a new issue if this persists. The original report was 1.7.2 on windows, and since then we have 
- implemented ancients (smaller database footprint)
- implemented in-memory pruning, 
- improved leveldb compaction problems 

... And many other improvements.

**Comment by BeOleg** [comment]
Hi there.
For me, this persists on Ubuntu.

Would love your feedback.
