### ISSUE TITLE
genesis block??

### ISSUE THREAD

**Issue by RoboMantis** [ethereum/go-ethereum#1555]
I followed the instructions from these two links
https://www.ethereum.org/cli
https://blog.ethereum.org/2015/07/27/final-steps/
-----------------------------------
and the second link said use this config link
https://forum.ethereum.org/discussion/2114/where-are-my-config-files-go-and-cpp
, but
 ~/Library/Ethereum (contains the chain)
~/Library/Ethereum/keystore (contains your keys)
~/.ethash (contains the DAG when mining)
did nothing.

--------------------------------------------
anyway this was the error I got when trying to do the genesis_block

freefavors: ~ $ ls
Applications  Backup  Documents  README.md  Web  caches  genesis_block.json  get-pip.py  mk_genesis_block.py
freefavors: ~ $   
freefavors: ~ $ geth --genesis /home/freefavors/genesis_block.json console     
I0730 20:32:09.475217    1855 flags.go:378] WARNING: No etherbase set and no accounts found as default
I0730 20:32:09.484625    1855 backend.go:289] Protocol Versions: [61 60], Network Id: 1
Fatal: unexpected end of JSON input

**Comment by bas-vk** [comment]
Could you post the exact command you used to create the genesis file and dump the contents of the file in a gist and post a link here?

**Comment by karalabe** [comment]
The correct command to generate the genesis block is:

`python mk_genesis_block.py --extradata 0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa > genesis_block.json`

Please make sure this is what you used.

**Comment by fjl** [comment]
The genesis block that made the Frontier network is baked into geth as of v1.0.1.

**Comment by RoboMantis** [comment]
I figured out how to do it!! Thanks, I made some kind of mistake so I whiped the vm and started over no problem. I'm not even sure what I did wrong to begin with I think I had mutiple coppies and it got confused...

**Comment by bitcoinicon** [comment]
@karalabe hey thanks for you answer.
I tried that and got this error>>> python: can't open file 'mk_genesis_block.py': [Errno 2] No such file or directory

Could you possibly help me with this as I used  >>> geth --rpc --rpccorsdomain "localhost" --genesis "genesis_block.json"

But I dont think this is loading the correct chain.
