### ISSUE TITLE
F-Secure antivirus started to consider "uninstall.exe" file malicious.

### ISSUE THREAD

**Issue by johnerfx** [ethereum/go-ethereum#15560]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: geth-windows-amd64-1.7.3-4bb3c89d.exe - installation file
OS & Version: Windows 10
Commit hash : 4bb3c89d?

#### Expected behaviour

Files installed from "geth-windows-amd64-1.7.3-4bb3c89d.exe" should be recognized **safe** by antivirus software. 

#### Actual behaviour
F-Secure antivirus started considering "uninstall.exe" file **malicious** after installing from **"geth-windows-amd64-1.7.3-4bb3c89d.exe"** file. I think previous versions would behave the same.
False positive??
Below is a Windows Event viewer log of the incident:

```
Log Name:      Application
Source:        FSecure-FSecure Application-F-Secure Anti-Virus
Date:          27.11.2017 08:19:34
Event ID:      207
Task Category: None
Level:         Critical
Keywords:      
User:          SYSTEM
Computer:      ********
Description:
Malicious code found in file C:\Program Files\Geth\uninstall.exe. 
Infection: Gen:Variant.Ursu.14047 
Action: The file was quarantined. 

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="FSecure-FSecure Application-F-Secure Anti-Virus" Guid="**********" />
    <EventID>207</EventID>
    <Version>0</Version>
    <Level>1</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2017-11-27T07:19:34.413481800Z" />
    <EventRecordID>6891</EventRecordID>
    <Correlation />
    <Execution ProcessID="4100" ThreadID="4568" />
    <Channel>Application</Channel>
    <Computer>***********</Computer>
    <Security UserID="*******" />
  </System>
  <EventData>
    <Data Name="MessageText">Malicious code found in file C:\Program Files\Geth\uninstall.exe. 
Infection: Gen:Variant.Ursu.14047 
Action: The file was quarantined. 
</Data>
    <Data Name="TrapTimestamp">1511767174</Data>
    <Data Name="TrapId">207</Data>
    <Data Name="TrapNumber">3</Data>
    <Data Name="Severity">5</Data>
    <Data Name="HostName">********</Data>
    <Data Name="UserName">***********</Data>
    <Data Name="ProductOID">1.3.6.1.4.1.2213.12</Data>
    <Data Name="ProductName">F-Secure Anti-Virus</Data>
    <Data Name="ParamCount">3</Data>
    <Data Name="Param">C:\Program Files\Geth\uninstall.exe</Data>
    <Data Name="Param">Gen:Variant.Ursu.14047</Data>
    <Data Name="Param">
    </Data>
  </EventData>
</Event>
```

#### Steps to reproduce the behaviour

Install **F-Secure antivirus** and run it.
Install **geth-windows-amd64-1.7.3-4bb3c89d.exe**.
Antivirus should detect installad uninstall.exe file as malicious(if not scan Geth folder location manually).
F-Secure online scannger might detect it too, but didn't check this:
https://www.f-secure.com/en/web/home_global/online-scanner

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Some antivirus software consistently flag P2P projects as viruses. Up until now all of them were false positivies. My suggestion is to try and upload any flagged files to https://www.virustotal.com/#/home/upload to have it scanned by 60+ different antivirus. Until now geth always came back clean.

**Comment by markmunozoz** [comment]
I am having the same issue and @karalabe the site you recommend gets 6 of the checks to come back as positive.
https://www.virustotal.com/#/file/aa95f8f9f4308827bfb5bd27e55762f78b5f370695c1954eef9462ec007864e0/detection

**Comment by johnerfx** [comment]
Looks like **geth-windows-amd64-1.8.2-b8b9f7f4.exe** does not have this problem so keeping software up to date fixes this :)
