### ISSUE TITLE
eth.getCoinbase() and eth.getAccounts() do not work

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/go-ethereum#1556]
They both return `undefined`, but I have accounts and a coinbase.

**Comment by bas-vk** [comment]
These are asynchronous versions of the getters for `eth.accounts` and `eth.coinbase`. If you want to use these asynchronous versions you must supply a callback:
```
> eth.coinbase
> eth.getCoinbase(function(err, cb) { console.log(err, cb); })
```

```
> eth.acounts
> eth.getAccounts(function(err, accounts) { console.log(err, accounts); })
```
