### ISSUE TITLE
Indexed inputs are not a part of log.Data

### ISSUE THREAD

**Issue by dshulyak** [ethereum/go-ethereum#15567]
I have simple token contract written on top of ERC20Basic with the following event
```
event Transfer(address indexed from, address indexed to, uint256 value);
```
then i am unpacking this event into
```
type TransferEvent struct {
	From  common.Address
	To    common.Address
	Value *big.Int
}
```
and it fails with

```
2017/11/28 13:34:28 abi: cannot marshal in to go type: length insufficient 32 require 96
```

#### System information

Geth version:
Geth
Version: 1.8.0-unstable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux

Commit hash : 0f7fbb85d6e939510a3e3bb6493a9a332ddfd8e8

**Comment by jrcfcc** [comment]
how do you resolve this problem?
