### ISSUE TITLE
I want to get the internal transaction through the RPC API. How can I get it?

### ISSUE THREAD

**Issue by liuxun1977** [ethereum/go-ethereum#15569]
https://etherscan.io/tx/0xee8d89a71ef42d2c5c7d54019c491137eb5cdaf93651f54c3ade95bc82a913ec。

**Comment by karalabe** [comment]
We do not track internal transactions. We're currently working on adding fancy tracing support for Geth along with a lot of pre-built tracers that will be able to generate the call stack for you, but only for blocks that you have the state for.

For legacy blocks that we don't retain the state any more (i.e. fast sync), there's no consensus information to retrieve the internal calls from.

**Comment by liuxun1977** [comment]
@karalabe   How does the exchange complete the contract account and token recharge?

**Comment by wcw84** [comment]
@karalabe I have found the [debug_tracetransaction](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_tracetransaction), but still don't know how to track the internal transaction, is there any more details about it?

**Comment by fxer** [comment]
Is it possible to connect to an existing geth service on a remote server to access `debug.NewPrivateDebugAPI.TraceTransaction`, similar to how the `ethclient.Dial()` command connect to a remote geth instance?

**Comment by adamschmideg** [comment]
Inactive for more than a year
