### ISSUE TITLE
eth.getBalance includes balance of `0x00`

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/go-ethereum#1557]
I have been mining with

```
> eth.coinbase
'0xc07526a4a9c0294b8fe2f404b43ca2b1f7a26b47'
```

and yet `eth.getBalance()` includes the balance of `0x00`. I've rebuilt from source, deleted `~/Library/Ethereum`, did `geth account new` before resynching, resynched, and the problem still persists.

**Comment by bas-vk** [comment]
`eth.getBalance` requires the account as an argument. Try this: `eth.getBalance(eth.coinbase)`. If no argument is given the balance of the 0x00 is returned. Apparently someone is mining without setting the etherbase.

**Comment by JustinDrake** [comment]
For some reason `eth.getBalance` is showing the `0x00` account balance even though my accounts do not include the `0x00` address. I've tried `geth removedb` and resynching but the problem persists.

**Comment by obscuren** [comment]
When no argument is given, the default value of an empty address is used for `getBalance`, which is `0x0000...00`. We need to put some validation on the function.

**Comment by karalabe** [comment]
Latest develop has this fixed. Don't know which commit solved it but closing. Please reopen if somehow unresolved for you.
