### ISSUE TITLE
mobile: AAR without debug-symbols

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#15572]
Was talking to @karalabe at DevCon3 - removing the debug symbols for special AAR variants might be an option to get the FileSize down. Currently the AAR for geth is quite big. And some stores like the upcoming Android-Go - No: not the language - A project for low-end/emerging countries devices that google announced this Google-IO: https://www.androidauthority.com/android-go-773037
I think stripping the debug symbols might just be a flag - the bigger question is how to separate the 2 APK variants - with and without debug symbols.

**Comment by adamschmideg** [comment]
We create two binaries for Android, the snapshot and the stable release. An idea would be to remove debug symbols from the stable release and keep them in the snapshots.

**Comment by adamschmideg** [comment]
Another problem is the stable build doesn't get pushed to Maven Central. We haven't found the cause yet.

**Comment by karalabe** [comment]
Android and iOS support dropped via https://github.com/ethereum/go-ethereum/pull/26599.
