### ISSUE TITLE
puppeth rejecting addresses allowed to seal (PoA)

### ISSUE THREAD

**Issue by nickops** [ethereum/go-ethereum#15573]
Hi. I am creating a private network using the PoA protocol. Puppeth asks me which addresses are allowed to seal. If I place a single address, my network works and the sealer node generates blocks correctly. But if I put 2, 3, or more addresses allowed to seal, my network does not generate blocks.

I see that these addresses (allowed to seal) are saved in the 'extraData' parameter of the genesis block, I have some doubts:

1. Is the maximum size of the 'extraData' parameter 32-byte long?
2. If I define a single address allowed to seal in the Genesis File, can I later add more sealing nodes (with additional addresses not defined in the GF) using puppeth?
3. What could be the reason that I'm unable to make my sealing nodes generate blocks if I define more than one address allowed to seal in my genesis block?

**Comment by easmith** [comment]
In order for the blocks to be sealed, n/2 +1 sealer should work on your network.
