### ISSUE TITLE
puppeth: Named volume "bootnode:/root/.ethereum:rw" is used in service "bootnode" but no declaration was found in the volumes section.

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/go-ethereum#15581]
#### Steps to reproduce the behaviour
```
puppeth --network chainpublic

...

Where should data be stored on the remote machine?
> bootnode

Which TCP/UDP port to listen on? (default = 30303)
> 30310

How many peers to allow connecting? (default = 512)
> 
How many light peers to allow connecting? (default = 256)
> 

What should the node be called on the stats page?
> bootnode
Named volume "bootnode:/root/.ethereum:rw" is used in service "bootnode" but no declaration was found in the volumes section.
ERROR[11-29|11:40:34] Failed to deploy Ethereum node container err="Process exited with status 1"
```

I have actually used `localhost` as the target machine, but I guess that is fine, no?

The above error might also be a leftover from a previous attempt?  

I have already killed the docker containers with

```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q) -f
```
but perhaps that was not enough?

What are the steps to fully clean a machine from a (partial) puppeth attempt?
(idea: `puppeth clean ip.address.of.machine` to have everything removed)

#### System information

Geth version: 1.7.3 stable
OS & Version: Linux

**Comment by drandreaskrueger** [comment]
Oh no (slap my forehead) ...

I suggest you add that as example:

```
Where should data be stored on the remote machine (e.g. ~/bootnode) ?
```

**Comment by holiman** [comment]
I think the problem is that you specifu a `hostname` which does not resolve, somewhere earlier. Then when it tries to scp the files into `foobar@bootnode:/root/ethereum` it fails. Would have worked with  `foobar@bootnode.addres.that.resolves:/root/ethereum`
