### ISSUE TITLE
Why using Mutex in lightFetcher, peerHasBlock(), les/fetcher.go?

### ISSUE THREAD

**Issue by OniReimu** [ethereum/go-ethereum#15584]
#### System information

Geth version: `geth 1.6.7`
OS & Version: Windows/Linux/OSX

#### Expected behaviour
From my own setting, every time a light client receiving an announce message from a light server and try to invoke `InsertHeaderChain()` in `light/lightchain.go`, now it will try to fetch info of this certain header from the light server. And the info received will be entered into a pre-defined verification function. Only passing ones will be inserted, not otherwise. 

#### Actual behaviour
The function got stuck at right after the `f.lock.Lock()` in `peerHasBlock()` in `les/fetcher.go`, no more actions will be conducted afterwards, which contributes to the fact that a light node cannot sync with light servers whenever they starts from the same height. The process just gets stuck and the other actions have to wait in the execqueue, and infinite loop. Thus even `> exit` fails unless I Ctrl+C 10 times to force exit.

#### Workaround
I replaced the 
```
f.lock.Lock()
defer f.lock.Unlock()
```
with 
```
f.reqMu.RLock()
defer f.reqMu.RUnlock()
```
And all good thus they are all reading processes.

#### Confusion

- What is the point that you guys use Mutex here rather than RWMutex?

- Is it good to use RWMutex in here?

- What does it mean by the comment related to the definition of Mutex locker of lightFetcher? It actually shows`lock       sync.Mutex // qwerqwerqwe`

**Comment by fjl** [comment]
@zsfelfoldi please look
