### ISSUE TITLE
personal.newAccount('passphrase') not working

### ISSUE THREAD

**Issue by enriquefynn** [ethereum/go-ethereum#1558]
I have a running geth instance running, accepting rpc calls, I do:
personal.newAccount('passphrase')
it doesn't create an account and returns an error:
```
read unix /home/fynn/.ethereum/geth.ipc: i/o timeout
    at InvalidResponse (<anonymous>:-60926:-28)
    at send (<anonymous>:-124886:-28)
    at newAccount (<anonymous>:-113803:-28)
    at <anonymous>:1:1
```
In --verbosity 5 there's no mention to this command.
However, running `geth account new` makes a new account

**Comment by karalabe** [comment]
Are you sure you're running a recent version of geth? `geth version`

How did you start geth?

**Comment by enriquefynn** [comment]
both 1.0.0 and the develop branch.

**Comment by karalabe** [comment]
How did you start geth, how did you connect to it?

**Comment by enriquefynn** [comment]
I ran geth with --rpc and in other process I did `geth attach`, and executed the command from there.

**Comment by karalabe** [comment]
Can you paste me the `geth attach` output?

I.e. this part
```
instance: Geth/v1.0.0/linux/devel +da87cf5 Mon Jul 27 04:07:23 2015 +0000
 datadir: XXX
coinbase: XXX
at block: 12248 (2015-07-31 21:00:10)
 modules: admin:1.0 db:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 shh:1.0 txpool:1.0 web3:1.0
```

**Comment by enriquefynn** [comment]
instance: Geth/v1.0.0/freebsd/go1.4.2
datadir: XXX
coinbase: XXX
at block: 17617 (2015-08-01 17:38:41)
modules: admin:1.0 db:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 shh:1.0 txpool:1.0 web3:1.0

**Comment by zelig** [comment]
@enriquefynn @bas-vk  Has this been resolved?

**Comment by obscuren** [comment]
Please re open the issue if the problem persist

**Comment by miohtama** [comment]
instance: Geth/v1.5.0-unstable/linux/go1.5.1

I attached via JSON-RPC (HTTP) and it says `newAccount` is not available. However this error message is confusing and does not state why it is not available.

**Comment by bas-vk** [comment]
This is a general error message. The node cannot distinct between using an invalid rpc method or one that isn't exposed over a particular interface.
