### ISSUE TITLE
Travis-CI TestFastCriticalRestartsFail63 on OSX fails consistently

### ISSUE THREAD

**Issue by manicprogrammer** [ethereum/go-ethereum#15594]
#### System information

Geth version: 1.9
OS & Version: OSX
Commit hash : most/all

#### Expected behavior
Travis-CI PR build test with coverage job on OSX should pass

#### Actual behaviour
Travis-CI PR build job 4 which is coverage on OSX continually fails on 
TestFastCriticalRestartsFail63 and either seems to be accepted as a false failure,
or an insignificant failure.  

This should be resolved to either have the test pass or this specific test made conditional for
the platform or...

#### Steps to reproduce the behaviour
Look at the PR builds...
https://travis-ci.org/ethereum/go-ethereum/pull_requests

**Comment by fjl** [comment]
This should be fixed in #15337 which was merged 1h ago.

**Comment by manicprogrammer** [comment]
sweet awesome!
