### ISSUE TITLE
Geth tests failing for JSON files- random randomStatetest645.json, randomStatetest644.json

### ISSUE THREAD

**Issue by ror-shubham** [ethereum/go-ethereum#15598]
When running `go test `, there are some failures in `TestState` . All the failures are from JSON files- randomStatetest644.json and randomStatetest645.json
[TestResults.pdf](https://github.com/ethereum/go-ethereum/files/1523596/TestResults-TestState_in_state_testGo.pdf)

#### System information

Geth version: `1.7.3-stable`
Go version: `go1.8.3`
OS & Version: `Ubuntu 16.04.3 LTS`

**Comment by holiman** [comment]
Yes, hence these tests are commented out, https://github.com/ethereum/go-ethereum/blob/master/tests/state_test.go#L42 , with reference to #15119
