### ISSUE TITLE
Geth default keystore JSON format slow to unlock on embedded devices

### ISSUE THREAD

**Issue by gusgorman402** [ethereum/go-ethereum#15599]
#### System information

Geth version: `geth 1.8.0-unstable`
OS & Version: Linux OpenWrt (800MHz CPU 64MB RAM 1GB SWAP)

#### Expected behaviour
Unlocking JSON keystore file (created by Geth binary)  takes 1-2 seconds

#### Actual behaviour
Unlocking encrypted JSON file, created by Geth, takes 10-15 minutes

However; Using keys created by MyEtherWallet takes the normal 1-2 second unlock time. I am having to convert my keys to the format MyEtherWallet uses. In my embedded environment, the Geth binary prefers the keystore JSON format of MyEtherWallet, not the default that Geth executable creates.

#### Steps to reproduce the behaviour
Using "geth account new" also is also taking longer than usual. Must have a low RAM environment

#### Backtrace

````
[backtrace]
````

**Comment by gusgorman402** [comment]
Geth created keystores have an "n" value of 262144 in the scrypt/kdfparams. Is this the cost value? It is set to 1024 in MEW keystores. Does this have anything to do with it? Cost values? I don't know much about encryption algorithms

**Comment by gusgorman402** [comment]
Solved. I edit the keystore_passphrase.go file and lower the StandardScryptN value for a low resource environment N=1024 P=1  R=8

**Comment by holiman** [comment]
There's also the 'lightkdf' option for this purpose
