### ISSUE TITLE
Synching is behind etherscan.io

### ISSUE THREAD

**Issue by 360disrupt** [ethereum/go-ethereum#15602]
Geth version: `1.7.3` recently installed with homebrew
OS & Version: `Mac OSC Sierra High`

#### Expected behaviour
Synching to the same block nr as ethercan.io

#### Actual behaviour
Always ~1000 blocks behind.

#### Steps

I run a local geth node: 
`
geth --ws --wsport=8546 --wsorigins="*" --rpc --rpcapi="personal,eth,network,web3" --rpcport=8545 --syncmode="fast" --networkid=1`

and connect with 

`new Web3(new Web3.providers.WebsocketProvider('ws://127.0.0.1:8546')) //ws://localhost:8546`

In my console (where geth is running) I see that the block nr (number) is always behind the number shown on etherscan.io e.g. `INFO [12-03|16:28:13] Imported new chain segment               blocks=10  txs=1194 mgas=58.072  elapsed=8.359s    mgasps=6.947  number=4668153 hash=976c4d…1e1efd` and etherscan had block: `4668992` => `914` blocks delta

I believe it is the same bug as: https://github.com/ethereum/mist/issues/2564

`self.web3.eth.getBlockNumber` gives me no errors but `0`as the result for the block nr. Which is probably because it hasn't synched completely.

PS: Can I listen to events and subscribe to them with the fast option?

**Comment by holiman** [comment]
> PS: Can I listen to events and subscribe to them with the fast option?

Yes

**Comment by jambtt** [comment]
Experiencing same issue. Geth v1.7.3 is always ~ -100 blocks from a full sync. Never completes. Fairly recent issue.

**Comment by holiman** [comment]
We've improved the speeds quite a lot of latest master (upcoming 1.9 release) compared to the reported version `1.7.3`. Closing this
