### ISSUE TITLE
Trojan:Win32/Tilken.B!cl found in installer in 1.7.3

### ISSUE THREAD

**Issue by goedzo** [ethereum/go-ethereum#15600]
After downloading the windows executable from https://geth.ethereum.org/downloads/ Windows Defender killed the file (after installation) by telling me there is a trojan inside. See image for it's message:
![trojan](https://user-images.githubusercontent.com/23582713/33514151-e600b518-d74e-11e7-917c-3526a1516afa.png)
Now I am unsure if this is a false positive (I really hope) or a serious issue. In anyway I just wanted to let you guys know this is here.

This is what the "more" link shows:
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Tilken.B!cl

**Comment by johnerfx** [comment]
#15560 might be the same issue.

**Comment by holiman** [comment]
Could you check the md5-sum and/or signature on the file `geth-windows-amd64-1.7.3-4bb3c89d.exe`?

**Comment by holiman** [comment]
See https://github.com/ethereum/mist/issues/3338#issuecomment-348761083, may be related (false positive). I'll try to look into the cause for Windows Defender detection.

**Comment by goedzo** [comment]
@holiman md5-sum seems to be correct, so looks like a false positive to me. Think it is related that a 32bit deinstaller is part of the 64bit installer under windows 10.
