### ISSUE TITLE
Tuple unpacking for static array overflows

### ISSUE THREAD

**Issue by dshulyak** [ethereum/go-ethereum#15617]
Offset computation for tuple unpack is not correct, both for method and event methods.

Let's say we have a function defined as 
```
  function emit(string msg, uint256 value) constant public returns(string, uint256[2], string) {
    return (msg, [value, value], msg);
  }

```

If I will send something like - `emit("hello", 6)`, i will expect following result `(hello, [6,6], hello)`.
Instead client will fail with error:
`
2017/12/06 15:31:47 abi: cannot marshal in to go type: length insufficient 256 require 140737488355365
`

commit: `afb8154eab2961996b321ac3fe5a21602e3b1aff`

**Comment by VoR0220** [comment]
Just a clarifier. There are no offsets for static arrays. They read in place because they can be defined from the ABI. Dynamic arrays, structs with dynamic components, strings and dynamic byte arrays all have offsets. But not static types.

**Comment by dshulyak** [comment]
yes, there is no confusion about it, this is an error message from a call to toGoType function. Problem is the same in event and method decoders
