### ISSUE TITLE
Rebroadcasted transaction ID

### ISSUE THREAD

**Issue by khelle** [ethereum/go-ethereum#15622]
Hi there,
I noticed that when I try to send the transaction via `eth_sendTransaction` method and it fails to get to blockchain at first try, it is rebroadcasted but with different txid. Is it possible to set Geth to keep the TXID constant for pending transactions?

**Comment by holiman** [comment]
No, it is not. A `txid` is the hash of the transaction, and will only change if one of the fields change (e.g. value, or gas, or gasprice). It's not possible to keep a txid, since it's inherently tied to the transaction data.
