### ISSUE TITLE
Feature: dedicated peer slots for light clients

### ISSUE THREAD

**Issue by veox** [ethereum/go-ethereum#15624]
`Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9`

I've recently spun up a node with the sole intent to serve light clients. In the [systemd service file](https://gist.github.com/veox/b4c2c121bf39e8c9e88026526cab4fc7), I've indicated:

`--maxpeers 150 --lightserv 90 --lightpeers 135`

~~Of course,~~ This doesn't do what I'd like. My peer list is 85 "light" clients and 65 "regular" ones. I'd like it to be 135/15, respectively.

It "would be nice" to have an option to limit "regular" peers; alternatively, it "would be nice" to be able to reserve peer slots specifically for "light" clients.

**Comment by veox** [comment]
This doesn't seem particularly difficult, so maybe I could even implement this myself, even if X times slower than someone more knowledgeable in Go and the `go-ethereum` codebase.

What would be a reasonable approach and option name?

* Limit "regular" peers with `--maxfullpeers`? Or name it `--fullpeers`?
* Rework `--lightpeers` to mean "dedicated light client slots"?

**Comment by ligi** [comment]
> I've recently spun up a node with the sole intent to serve light clients.
:heart: :+1: :fireworks: :tada: :balloon: :100: :1st_place_medal:

**Comment by veox** [comment]
> My peer list is 85 "light" clients and 65 "regular" ones.

To clarify: this is 5-15 after node reboot.

I've noticed that after a few days of continuous operation at the limit of the system's CPU load capacity, the numbers gravitate towards: less "regular" peers, more light ones.

At some point, though, the node experiences some failure and stops syncing (while still having both types of peers). I'll see what running at increased verbosity gets me.

**Comment by lmars** [comment]
I'm having a similar issue whereby I am running a light server but I actually get too many light clients (see https://github.com/ethereum/go-ethereum/issues/15689), which means I end up with only light peers and no full peers to get new blocks from.

**Comment by veox** [comment]
From https://github.com/ethereum/go-ethereum/issues/15689#issuecomment-357632586, `--lightpeers` is planned to mean "dedicated light peer connection slots".

Closing this, as it's now a duplicate (sort of).
