### ISSUE TITLE
BAD BLOCK 4692143 - Error: unknown ancestor

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#15627]
#### System information

Geth version: `geth version`
Develop version: v1.8.0-unstable-6e613cf3/windows-amd64/go1.9"

OS & Version: Windows/Linux/OSX
Windows
Commit hash : (if `develop`)
v1.8.0-unstable-6e613cf3
#### Expected behaviour
No error, after this my sync seems  to lag behind.

#### Actual behaviour
INFO [12-07|11:58:07] Imported new chain segment               blocks=1  txs=107  mgas=6.718   elapsed=1.234s    mgasps=5.440  number=4692140 hash=a1d6e6â€¦262f95
INFO [12-07|11:58:08] Imported new chain segment               blocks=1  txs=84   mgas=6.722   elapsed=1.308s    mgasps=5.139  number=4692141 hash=db3ea5â€¦5dfd0b
INFO [12-07|11:58:10] Imported new chain segment               blocks=1  txs=93   mgas=6.544   elapsed=1.224s    mgasps=5.344  number=4692142 hash=7b0e39â€¦39fc9c
WARN [12-07|12:00:59] Head headers broke chain ordering        peer=4f40105e9e158763 index=0 requested=4691950 received=4692156
WARN [12-07|12:00:59] Synchronisation failed, dropping peer    peer=4f40105e9e158763 err="retrieved hash chain is invalid"
WARN [12-07|12:12:33] message loop                             peer=07c19cd71b302379 err=EOF
ERROR[12-07|12:15:33] 
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Engine: ethash}

Number: 4692143
Hash: 0x7ceab1b1f3f11f93456f3e025fb3ce73823b0835eba2e4690f302d438dc9578c

Error: unknown ancestor
##############################
 
WARN [12-07|12:15:33] Synchronisation failed, dropping peer    peer=4657f82f3f9239a3 err="retrieved hash chain is invalid"
INFO [12-07|12:15:49] Imported new chain segment               blocks=15 txs=2803 mgas=100.038 elapsed=8.171s    mgasps=12.242 number=4692156 hash=86b77fâ€¦4dfd2f ignored=11
INFO [12-07|12:15:49] Imported new chain segment               blocks=1  txs=125  mgas=6.712   elapsed=345.003ms mgasps=19.454 number=4692146 hash=96560eâ€¦5b2285
INFO [12-07|12:15:49] Imported new chain segment               blocks=1  txs=109  mgas=6.535   elapsed=251.998ms mgasps=25.934 number=4692148 hash=16aa9bâ€¦f0f244
INFO [12-07|12:15:58] Imported new chain segment               blocks=15 txs=1273 mgas=100.587 elapsed=8.512s    mgasps=11.817 number=4692171 hash=d1cf9câ€¦789d40
INFO [12-07|12:16:06] Imported new chain segment               blocks=18 txs=1981 mgas=120.630 elapsed=8.095s    mgasps=14.900 number=4692189 hash=304d69â€¦d2a1c7
INFO [12-07|12:16:13] Imported new chain segment               blocks=21 txs=2112 mgas=138.003 elapsed=7.071s    mgasps=19.517 number=4692210 hash=85559dâ€¦778fdc
WARN [12-07|12:16:13] Synchronisation failed, retrying         err="block body download canceled (requested)"
INFO [12-07|12:16:13] Imported new chain segment               blocks=1  txs=59   mgas=6.720   elapsed=150.998ms mgasps=44.506 number=4692156 hash=aa2b37â€¦6ff52e
INFO [12-07|12:16:13] Imported new chain segment               blocks=1  txs=104  mgas=6.719   elapsed=256.000ms mgasps=26.246 number=4692152 hash=7fa9e1â€¦8c0d61
WARN [12-07|12:24:27] message loop                             peer=d6e09c7f26b060cd err=EOF
WARN [12-07|12:26:08] message loop                             peer=50ff0779644d9cbc err=EOF
INFO [12-07|12:27:11] Imported new chain segment               blocks=2  txs=224  mgas=13.471  elapsed=766.21ms  mgasps=17.581 number=4692212 hash=93f12dâ€¦649ef2
INFO [12-07|12:27:12] Imported new chain segment               blocks=4  txs=329  mgas=26.528  elapsed=1.144s    mgasps=23.169 number=4692216 hash=4d8ea5â€¦9c9fd5
INFO [12-07|12:27:32] Imported new chain segment               blocks=24 txs=2280 mgas=160.888 elapsed=8.238s    mgasps=19.528 number=4692240 hash=e8669dâ€¦24bb52
INFO [12-07|12:27:37] Imported new chain segment               blocks=19 txs=1909 mgas=126.310 elapsed=5.174s    mgasps=24.409 number=4692259 hash=ea2f28â€¦f6fc00
INFO [12-07|12:27:50] Imported new chain segment               blocks=1  txs=89   mgas=6.342   elapsed=193.999ms mgasps=32.690 number=4692260 hash=b357e7â€¦475584
INFO [12-07|12:27:52] Imported new chain segment               blocks=1  txs=155  mgas=6.639   elapsed=504ms     mgasps=13.173 number=4692261 hash=d1ab21â€¦e99608
INFO [12-07|12:28:19] Imported new chain segment               blocks=1  txs=83   mgas=6.735   elapsed=301.680ms mgasps=22.324 number=4692262 hash=5beba9â€¦9d9a9a
INFO [12-07|12:28:20] Imported new chain segment               blocks=1  txs=158  mgas=6.634   elapsed=429.504ms mgasps=15.447 number=4692261 hash=bf2e99â€¦381c12
INFO [12-07|12:28:28] Imported new chain segment               blocks=1  txs=130  mgas=6.740   elapsed=428.126ms mgasps=15.742 number=4692263 hash=3312b7â€¦4daaf7

#### Backtrace

````
[backtrace]
````

**Comment by rfikki** [comment]
Ok, sync did finally manage to catch up. If the above is of no concern, please close.

**Comment by revskill10** [comment]
@rfikki I got same problem, what to do ? Just wait ?
