### ISSUE TITLE
Faucet: zlib invalid header

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#15635]
![selection_199](https://user-images.githubusercontent.com/111600/33797733-6c97d084-dd0d-11e7-8ef4-a5274a5e8903.png)

**Comment by ligi** [comment]
getting this for all twitter use cases now - working fine for google-plus - cannot really test facebook.

**Comment by Phistr90** [comment]
can confirm twitter is broken. Cant test the other.

**Comment by ligi** [comment]
can confirm it works again. thanks for the fix @karalabe

**Comment by karalabe** [comment]
:+1:

**Comment by arjdesign** [comment]
I am also having same issue as of today. Can you please send me 15 ethers in this address: 0x7779423611c7A961a2B8c9d299eF1d07d7A6720a

**Comment by tangtuozhou** [comment]
would you  please send me 10 ethers in this address: 0x2dd5de5c1f17c670f4ab7bfd16ee21f23f0028ae

**Comment by ligi** [comment]
did you get this zlib error?

**Comment by tangtuozhou** [comment]
when i apply ,there is a fail,no ethereum address found to fund,so could
you send me 10 if you have thanks!

add:0x2dd5de5c1f17c670f4ab7bfd16ee21f23f0028ae


[image: image.png]

**Comment by ligi** [comment]
what URL did you use?

**Comment by tangtuozhou** [comment]
facebook
https://www.facebook.com/yutang.zhou.39/posts/471226160628670

**Comment by tangtuozhou** [comment]
apply web site: http://faucet.goerli.mudit.blog/

**Comment by ligi** [comment]
your facebook post is not public - when the faucet cannot read the post it cannot send to your address.

**Comment by tangtuozhou** [comment]
Ok, try it. Thanks!

**Comment by tangtuozhou** [comment]
Twitter ok, Facebook can’t. Anyway, thank you!
