### ISSUE TITLE
Very low peer count, yet getting "too many peers" error.

### ISSUE THREAD

**Issue by simondlr** [ethereum/go-ethereum#1563]
Successfully synced with launch. Turned it off, and when I turned it back on this morning, it doesn't sync, or syncs in fits & starts (very unreliably at least). Looking at the debug, I keep seeing this.

"dyn dial conn 33538128d0e816bf 77.53.40.242:30303 failed proto handshake: Too many peers"

I receive this even when I have zero peers connected. It never goes higher than 4 - 6 even if I set maxpeers to say 50.

Is this error because "other" peers aren't allowing me to connect? Or is my own node that's spitting that out? Are other peers kicking me off?

What's happening here?

**Comment by simondlr** [comment]
Since it is checking both trusted connection & peer count, unsure what's the issue. Perhaps it is the former, not the latter. 

```
case !c.is(trustedConn|staticDialedConn) && len(peers) >= srv.MaxPeers:
```

**Comment by karalabe** [comment]
Too many peers is the error messages sent back by the remote side. I.e. the remote node is telling you that it is full and thus not accepting you.

**Comment by simondlr** [comment]
Thanks @karalabe. That's helpful.

It started syncing again. This happened similarly in the testnets, but thought with a fuller network it will be less of an issue.

I am connected to a lot more peers now. I suspect it will happen again. It sometimes just struggles to get synced and connected to peers, and I have no idea why. Is there perhaps some issue with the network wanting to connect my peer (besides being full)? Or is there something I can do that will fix this issue? Or help connecting more properly the network?

**Comment by karalabe** [comment]
I'd think it's not really a fault at your end, or at any other place either imho. We should add a node removal strategy to ensure new joiners can quickly get a slot into the network. We just need to figure out a way that doesn't introduce DOS vulnerabilities with malicious nodes piling up on an unsuspecting node. It will be addressed eventually, but may take a bit depending on the seriousness of the issue. Maybe @fjl can make a mental note that this might become an issue eventually so we could start thinking about this scenario.

**Comment by simondlr** [comment]
Thanks @karalabe. Sitting with the same issues right now. Once it gets into the peer groups, it syncs predictable, but it just struggles sometimes to get "in" so to speak. An hour can go by and it still has poor peer connections (no syncing). And sometimes when I start geth, it connects immediately and starts syncing.

**Comment by dooglus** [comment]
@simondlr Since it is checking both trusted connection & peer count, unsure what's the issue. Perhaps it is the former, not the latter.

    case !c.is(trustedConn|staticDialedConn) && len(peers) >= srv.MaxPeers:

Well, it's both, right? That's an "and"... The issue is that the remote host is already full AND it doesn't trust us. I guess if it trusted us (whatever that means) it would allow us to connect even though it was 'full'.

**Comment by fjl** [comment]
About the 'trusted' thing: the p2p subsystem has an undocumented feature (configured by a JSON file) that allows adding node IDs to the list of trusted peers, which can always connect (as you have seen in the snippet above). I honestly don't know whether anyone uses this feature. 

About this issue: as @karalabe pointed out, we are working on adding a disconnect strategy that should improve the speed of getting onto the network.

**Comment by dooglus** [comment]
I was eventually able to get some peers recently by asking in the #ethereum IRC channel and being given a admin.addPeer('enode://...') command. It took a while after that, but eventually I was connected to 10-15 peers. It seems that the bootstrap code wasn't finding any non-full peers for me.

How is the "--maxpeers" thing meant to work? Suppose there are 100 peers, each with --maxpeers=25. Each will eventually connect to 25% of the nodes, leaving all 100 nodes "full" and unavailable for new peers to connect to. Bitcoin has the concept of "incoming" and "outgoing" connections. Each peer will only attempt to make a certain number (8 by default) of outgoing connections, leaving the rest of its 'maxpeers' allocation available for other peers to connect to. Is there any similar scheme in ethereum that attempts to ensure it's always possible for new nodes to find non-full peers?

**Comment by fjl** [comment]
For geth, the ratio is 50%. If you specify `--maxpeers 25`, it will make 12 connections and leave the rest of the slots for inbound connections.

**Comment by dooglus** [comment]
@fjl That's good to know. I am no longer having trouble finding peers, even if I go a few days without running geth at all. But I did find it very hard to get started and had to resort to begging for peer addresses on IRC before I was able to find a single working peer. I guess the bootstrapping mechanism needs some work.

**Comment by phiferd** [comment]
Sorry to comment on such an old issue, but I don't see any other mention of the "node removal strategy".  I was just wondering if that ever happened.  We're running a private chain and this is an issue.  Here's a 1hr sample of the errors (where background.log is the geth output with verbosity=6), during which no peers were successfully added: 

```
$ grep failed background.log | sed 's/.*://g' | sed 's/- .*//g' | sort | uniq -c | sort -r -n
  15485  use of closed network connection
   2654  not found
   1940  Too many peers
    979  Genesis block mismatch
    650  EOF
    249  Useless peer
     37  i/o timeout
     37  An existing connection was forcibly closed by the remote host.
     18  expected handshake, got 6
      9  shutting down
      2  NetworkId mismatch
```

I believe "not found" is when the node was not found in the local DB, so that's actually a count of new peers that were attempted.  You can see the large majority of new peers have too many peers, and many of the others are just not from our network.  Not sure why there are so many "use of closed network connection".

**Comment by QingYun** [comment]
Could not start a private chain of two nodes. Tried to let node2 addPeer(node1), but node1 just kept saying "too many peers" and rejecting handshakes from node2 even though I could see that node1's peerCount was 0. Both of them were started with `--maxpeers 100`
