### ISSUE TITLE
Geth suddenly lost account information from Ledger Nano S

### ISSUE THREAD

**Issue by op9** [ethereum/go-ethereum#15639]
Hi there,

I was about to transfer my out mined ETH-s to a Ledger Nano S (FW: 1.3.1).
Geth was able to see the accounts on the Ledger, so I used it.
Because this was my very first transaction, I started with a small amount of 0.05ETH.
> eth.sendTransaction({from:eth.coinbase, to:eth.accounts[1], value: web3.toWei(0.05, "ether")})

It worked as I expected.
So I wanted to send all my ETHs:
> eth.sendTransaction({from:eth.coinbase, to:eth.accounts[1], value: web3.toWei(12.95, "ether")})
Error: insufficient funds for gas * price + value
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

So I have reduced the amount:
> eth.sendTransaction({from:eth.coinbase, to:eth.accounts[1], value: web3.toWei(12.92, "ether")})
"0x0d0c739f63274585282640f69fc1167fbb2acf229e9e54caff3433e52fe00131"

Then I checked on etherscan:
https://etherscan.io/tx/0x0d0c739f63274585282640f69fc1167fbb2acf229e9e54caff3433e52fe00131

And I could see, that something bad is happening, because at the "to" field wasn't my address, instead it was about to create a contract.

Between these 2 transactions was 12 minutes, but I pressed buttons on Ledger to not go into "sleep" mode (vires in numeris) and I stayed inside the Ethereum app (1.0.21), as you can see also on the log I attached.
I even tried now to wait till this message, and geth was able to see the adresses.

Bonus question: how can I get my ETHs back?

#### System information

Geth version: `1.7.3-stable-4bb3c89d`
OS & Version: Windows 10

#### Expected behaviour
able to see the connected ledger as 12 minutes earlier and get a valid address from "eth.accounts[1]"

#### Actual behaviour
without any warning it couldn't read the address from Ledger, that lead to an "undefined" value, and that created a contract

#### Steps to reproduce the behaviour
I tried to make a new transaction again with a higher value to cause this error message:
"Error: insufficient funds for gas * price + value"
But the accounts was still there, so I don't know how to reproduce again.

#### Backtrace

[geth-attach.txt](https://github.com/ethereum/go-ethereum/files/1545061/geth-attach.txt)
[geth-cmd.txt](https://github.com/ethereum/go-ethereum/files/1545062/geth-cmd.txt)

**Comment by holiman** [comment]
First of all, the ether is lost. I'm sorry for your loss. 

Secondly, judging from the logs, it looks strange that the `eth.accounts[1]` suddenly disappeared, since there's no mention of the USB getting dropped. When the first tx is made, the wallet 'discovered' two new accounts (which are ledger accounts 1 and 2). Could there be a bug there, @karalabe? I'll assign this to you to look into. 

For anyone else reading this; it would have been avoidable if the `to`-address had been saved in a variable, instead of relying on `eth.accounts[1]`. This would also have been avoided if we have 'sign-what-you-see', instead of 'submit-then-sign'.

**Comment by op9** [comment]
Thank you for your comment!

I also thought, that maybe the new discovered accounts, or the change at the balance field caused something.

I don't get this yet:
> This would also have been avoided if we have 'sign-what-you-see', instead of 'submit-then-sign'.

First: the last quote is not 'sign-then-submit'? Because we unlock the account (sign) and make the sendTransaction (submit).
Second: geth is able to 'sign-what-you-see', and I should have been using it? Or geth can only 'sign-then-submit', and it would be good to change to 'sign-what-you-see'.

**Comment by op9** [comment]
Any update on this one?
Or I was the only one who faced this issue?

**Comment by holiman** [comment]
We added a check for the underlying error: https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1390  
Fixed two years ago: https://github.com/ethereum/go-ethereum/pull/16108

**Comment by karalabe** [comment]
Sorry again for this loss, but unfortunately there's nothing else we can do. There are no known issues with accounts disappearing temporarily that might explain what happened to you.
