### ISSUE TITLE
All neighbors invalid in light mode

### ISSUE THREAD

**Issue by ajthemacboy** [ethereum/go-ethereum#15642]
#### System information

Geth version: 1.7.2 and 1.7.3, others untested
OS & Version: Windows 10 build 16299.98

#### Expected behaviour
`geth --light` or `geth --syncmode light` would behave as expected

#### Actual behaviour
I run geth like this: `".\geth\geth.exe" --light --datadir ".\geth\data" --verbosity 5`. The client is never able to connect to any peers. Without the verbosity flag, the client stops printing entirely, but with it the client shows a lot of errors. 

I have both geth fully allowed in Windows firewall on all networks and protocols. I also tried `--v5disc` since the issues seem to be with peer discovery but that didn't do anything. My issue seems similar to #15266. 

Here is the log with verbosity 4: https://gist.github.com/ajthemacboy/23e5e4b0a07fcc00089301d001795996
And here is another one with verbosity 5: https://gist.github.com/ajthemacboy/a948fa59dc30a0569440bc13d6983f85

**Comment by HSY229** [comment]
#15266

**Comment by adibas03** [comment]
+1

**Comment by azavalla** [comment]
+1 for version `1.8.27-stable-4bcc0a37`
