### ISSUE TITLE
Suggestion: reduce the number of files required to run a full node

### ISSUE THREAD

**Issue by destenson** [ethereum/go-ethereum#15643]
Hi,

#### System information

Geth version: any
OS & Version: Windows 10, NTFS

#### Expected behaviour

It's been a known issue for a long time that the performance of some popular filesystems (particularly Microsoft brand, but I'm sure there are others) degrades significantly when there are too many files contained in a folder. To ensure good performance when using such filesystems, geth should not rely on having tens of thousands of files in the same directory. A performance increase would be noticeable if it stored the blockchain using fewer files.

#### Actual behaviour

I'm downloading the entire blockchain for the first time in a long time. It's near block 4,000,000, and the chaindata folder contains almost 30,000 ~2MB files. I've noticed it can take a very long time shutting down, and it spends all that time on disk I/O. With that many files in the directory, it's no surprise that I/O gets backed up.

**Comment by ncaew** [comment]
I think the Suggestion is good. Too many little files on disk cause bad performance on my pc ( ubuntu, ext4).

**Comment by destenson** [comment]
I made a fix to this today & it seems to sync _dramatically_ faster. Once it's finished & I verify I didn't break anything, I'll submit a PR.

**Comment by holiman** [comment]
Closing this issue, see discussion in the PR

**Comment by adamschmideg** [comment]
Related #15704
