### ISSUE TITLE
Currently impossible to get Rinkeby ETH: zlib issue w/ Rinkeby test-net faucet.

### ISSUE THREAD

**Issue by antsankov** [ethereum/go-ethereum#15645]
I'm trying to get testnet Eth, I create the [tweet](https://twitter.com/antsankov/status/939984059975028737), and paste it into the frontend. And I get this weird error zlib: invalid header. Not noticing anything in the JS console.
<img width="1440" alt="screen shot 2017-12-10 at 5 25 04 pm" src="https://user-images.githubusercontent.com/2533512/33810287-e04da328-ddd0-11e7-91ab-c43e16ad2391.png">
<img width="1440" alt="screen shot 2017-12-10 at 5 25 10 pm" src="https://user-images.githubusercontent.com/2533512/33810288-e2ba8c70-ddd0-11e7-9ef2-3ba90b3dbefe.png">

**Comment by ligi** [comment]
Duplicate of: https://github.com/ethereum/go-ethereum/issues/15635
Workaround: use google-plus (maybe also facebook works - but I don't want to create one account there) - the problem seems to only appear with twitter

**Comment by karalabe** [comment]
Twitter rolled out an update and apparently also updated their HTTP compression/encoding. I'll need to make a faucet update to more gracefully handle whatever Twitter hit it with.

**Comment by almindor** [comment]
As a side note where did the github option go? Any other options for us non-social networkers?

**Comment by ligi** [comment]
> As a side note where did the github option go? 

@karalabe told me that github asked to remove this option

**Comment by antsankov** [comment]
What about pastebin?

**Comment by elliotthill** [comment]
Same problem, and would rather not have to make a public post via social network - some of us are trying to keep up the illusion we are not nerds.

Can we not just use a recaptcha?
