### ISSUE TITLE
ETH from Ledger nano S to Bittrex money stuck its been several days no help from hitbtc

### ISSUE THREAD

**Issue by chekaracanada** [ethereum/go-ethereum#15653]
https://etherscan.io/tx/0xa3f99d65fd09e2792d563538836379fd53a5c7aa7465a92a33c80e79b38876a9

Ive been waiting for a help from hitbtc but seems they are not care .I have my money stuck almost for a week and no help No idea what to do now , it looks like i lost this 54 bucks

Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by chekaracanada** [comment]
The money is missing , i have red balance in my Ledger nano S 
and i've tried to send  out eth , it say you have insufficient funds  with  a minus in front of it 
Which means the money never roll back to my Ledger ?

**Comment by chekaracanada** [comment]
I do not know what to do now ?
it is so annoying

**Comment by ligi** [comment]
Can you elaborate why this is a problem with the geth software?  Looks like the contract execution failed for out of gas:
> Warning! Error encountered during contract execution [Out of gas] 
Not sure where the connection to geth is - please ask on https://ethereum.stackexchange.com/

**Comment by chekaracanada** [comment]
I did ask there but still no help.
The money has gone , that's it.

**Comment by holiman** [comment]
No money is gone. 
Your account (presumably): 
https://etherscan.io/address/0xc131cf1b8fbfe81161c65e960f14051d10b2f019

You tried to send `0.11...` eth in https://etherscan.io/tx/0xa3f99d65fd09e2792d563538836379fd53a5c7aa7465a92a33c80e79b38876a9, but it failed (out of gas), and was thus reverted back to your account. 

Then you got some more ether from nanopool (0.06 ether), and eventually sent off `0.15...` ether in https://etherscan.io/tx/0xa65791f19a98d639594c8d0cdf0456f9e0f64ed53bb3fa039240e13cf6616111 , on Dec-08-2017 02:47:08 AM +UTC. 

As @ligi points out, this has nothing to do with go-ethereum, though. I'll close this ticket.
