### ISSUE TITLE
ULC: first step

### ISSUE THREAD

**Issue by JekaMas** [ethereum/go-ethereum#15657]
The issue is from https://gist.github.com/zsfelfoldi/7da2b802824569d2d159d5d06eeda14c (@zsfelfoldi ). A part of Status.im and Ethereum collaboration.

I've done 4 out of 6 points. The rest 2 should be done by @b00ris.

Here:
- adding the ultra light client option
Add an extra option for light client mode where the user can specify a text/json ULC config file that contains a list of trusted server enodes and N out of M parameters (which may depend on how many servers we are connected to, there may be 5 servers listed but we can still accept 2 out of 3 connected).
Here are some pointers to implementing the ULC mode. Just take a look at the relevant code, then feel free to ping me whenever you have questions (I guess it will happen a few times, I tried to document the most important parts but some of the code is still a bit messy, which I apologize for in advance).

- requesting signed headers
Now the client will only accept signed announcements so we can accept the corresponding headers without PoW check.

- switching off header PoW validation:

- modifying the server pool to always try to connect to trusted nodes:

**Comment by b00ris** [comment]
I plan to make PR with other points at monday.

**Comment by b00ris** [comment]
Should be closed(https://github.com/ethereum/go-ethereum/pull/16904)

**Comment by b00ris** [comment]
@zsfelfoldi @karalabe Could you close the issue?

**Comment by b00ris** [comment]
@zsfelfoldi @karalabe up

**Comment by adamschmideg** [comment]
Fixed by #16904
