### ISSUE TITLE
Geth cross compile error: ...secp256k1: build constraints exclude all Go files in $GOPATH/src/github.com/ethereum/go-ethereum/crypto/secp256k1

### ISSUE THREAD

**Issue by smcduck** [ethereum/go-ethereum#15662]
#### System information

Geth version: `1.7.3-stable` https://github.com/ethereum/go-ethereum/archive/v1.7.3.zip
OS & Version: OSX 10.13.1
Go Version: go1.9.2 darwin/amd64

#### Expected behaviour
Executable binary generated.

#### Actual behaviour
build error:
`go build github.com/ethereum/go-ethereum/crypto/secp256k1: build constraints exclude all Go files in $GOPATH/src/github.com/ethereum/go-ethereum/crypto/secp256k1`

#### Steps to reproduce the behaviour
cd cmd/geth source code dir and run
`env GOOS=linux arch=amd64 go build`

**Comment by cypherhat** [comment]
I am also experiencing this as well - cross compiling to Linux or Windows

## System information
Geth version: `git checkout tags/v1.7.3`
OS & Version: OSX 10.12.6
Go Version: go1.9.2 darwin/amd64

```
$ GOOS=windows GOARCH=amd64 go build -o vault-ethereum.exe
go build github.com/ethereum/go-ethereum/crypto/secp256k1: build constraints exclude all Go files in /Users/immutability/develop/go/src/github.com/ethereum/go-ethereum/crypto/secp256k1
```

```
$ GOOS=linux GOARCH=amd64 go build -o vault-ethereum
go build github.com/ethereum/go-ethereum/crypto/secp256k1: build constraints exclude all Go files in /Users/immutability/develop/go/src/github.com/ethereum/go-ethereum/crypto/secp256k1
```

**Comment by cypherhat** [comment]
Found this.

https://github.com/ethereum/go-ethereum/wiki/Cross-compiling-Ethereum

**Comment by jingyan** [comment]
we encountered this issue on mac. but we didn't use cross platform compilation. 

We change env variable cgo from 0 to 1 and fixed this issue.

**Comment by EnchanterIO** [comment]
@cypherhat what command did u exactly execute to get it working with xgo?

**Comment by cypherhat** [comment]
I don't cross compile. Which is a pain... I build for Linux in Linux - Darwin in Darwin... but if you can provide a solution, please post it.

**Comment by EnchanterIO** [comment]
I see. I wasn't compiling go-ethereum but a project using some of its libraries. Especially this troublemaker: **ethereum/go-ethereum/crypto/secp256k1/libsecp256k1**

I was able to compile Linux version from Mac with xgo:

```go
xgo --deps=https://gmplib.org/download/gmp/gmp-6.0.0a.tar.bz2 --targets=linux/amd64 ./cmd/leth
```

**Comment by cypherhat** [comment]
Cool. I haven't used `xgo`. This is nice.

**Comment by gballet** [comment]
@smcduck I am trying with 1.8.23 and go 1.11.1, and I can't reproduce the problem. Could you please try again with something more recent and tell us is the problem is still here?
