### ISSUE TITLE
Can't run "geth" on windows. Command not found.

### ISSUE THREAD

**Issue by mr-e-** [ethereum/go-ethereum#1566]
I followed the instructions to install geth on windows through chocolately. But afterwards (even after rebooting) when I open the command line and type "geth" I get an error that says "command not found"

**Comment by maran** [comment]
This is not a problem with geth but with the chocolatey scripts. In the future [here would probably a better place for it](https://github.com/tgerring/ethereum-chocolatey).

There should be a `geth-stable.bat` file on your dashboard, starting that should run geth. You can also start it directly from the installed folder.

**Comment by obscuren** [comment]
Please file an issue at the above link.

**Comment by mr-e-** [comment]
I believe this issue lies with your setup documentation since following the instructions do not work.

**Comment by 0xorial** [comment]
Same problem. Please update install instruction.

**Comment by AlennGK** [comment]
Add PATH in Windows, or make link to defined PATH in Windows like I did.

**Comment by kashifdev21** [comment]
Please follow the following steps after the installation then you will be able to run the "geth" command successfully.

1. Go to Control Panel
2. Select the System
3. Select Advance System Settings
4. In the open window of Advance System Setting click the Environment Variable button
5. In Environment Variable Window Select the Path Variable and press Edit Button
6. Then Just simply Copy the path of your Geth Installation directory like below and Save
"C:\Program Files (x86)\Geth\"

Now go to command Prompt you will be able to find  the "geth" Command

**Comment by SalemNabeelSalem** [comment]
@kashifdev21 .. Good It's working
