### ISSUE TITLE
Does not compile for Windows

### ISSUE THREAD

**Issue by mxplusb** [ethereum/go-ethereum#15669]
#### System information

Geth version: 1.7.3
OS & Version: Windows 10
Commit hash : 4bb3c89d44e372e6a9ab85a8be0c9345265c763a

#### Expected behaviour

`make geth-windows` compiles for Windows.

#### Actual behaviour

```bash
$ make geth-windows-amd64
build/env.sh go run build/ci.go xgo -- --go=latest --targets=windows/amd64 -v ./cmd/geth
: not foundh: 2: build/env.sh:
build/env.sh: 3: set: Illegal option -
Makefile:140: recipe for target 'geth-windows-amd64' failed
make: *** [geth-windows-amd64] Error 2
```

#### Steps to reproduce the behaviour

`make geth-windows-amd64`

**Comment by karalabe** [comment]
`make geth`.

The `geth-windows-amd64` target is `xgo` based cross compilation. That only works from under linux.

**Comment by mxplusb** [comment]
@karalabe I ran `make geth-windows` in Linux.
