### ISSUE TITLE
Console history seems to be missing for custom datadirs

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#15672]
If I run a node in a custom data directory via `geth --datadir=... console`, the console history seems to get lost after a restart. This is probably a trivial thing caused by not passing datadir to the proper place.

**Comment by RichardH92** [comment]
@karalabe Can I look into this and try to fix?

**Comment by karalabe** [comment]
Sure!

**Comment by enriquefynn** [comment]
I can't reproduce this.
How is this restart done?

**Comment by original-brownbear** [comment]
@karalabe @enriquefynn same here, can't reproduce this.

**Comment by karalabe** [comment]
Repro:

```
$ geth --testnet --datadir=/work/ethereum/ropsten --cache=2048 console

> eth.blockNumber
0
<Ctrl+D>

$ geth --testnet --datadir=/work/ethereum/ropsten --cache=2048 console
> <up arrow, no history>
```

**Comment by original-brownbear** [comment]
@karalabe gave this a go in https://github.com/ethereum/go-ethereum/pull/15700 (the trick in reproducing this is using the `--testnet` btw, this doesn't happen on the normal net)
