### ISSUE TITLE
Wiki: show --genesis

### ISSUE THREAD

**Issue by linagee** [ethereum/go-ethereum#1567]
The wiki page here: https://github.com/ethereum/go-ethereum/wiki/Connecting-to-the-network
Should include at least a reference to the --genesis block syntax.

(The frontier-guide pulls from this.)

**Comment by obscuren** [comment]
Volunteering? :+1:

**Comment by fjl** [comment]
Added: https://github.com/ethereum/go-ethereum/wiki/Connecting-to-the-network/_compare/dd669a0c1cb463fac0b8162d1c8c64703583981c...7e180638378ce4d62c7df3d000011cb974bfdaf6
