### ISSUE TITLE
LES/GetProofs behaviour doesn't match the spec

### ISSUE THREAD

**Issue by gsalgado** [ethereum/go-ethereum#15678]
If I'm reading https://github.com/ethereum/go-ethereum/blob/master/les/odr_requests.go#L183 and
https://github.com/ethereum/go-ethereum/blob/master/les/handler.go#L700-L713 right, I believe the
description of [GetProofs in the wiki](https://github.com/zsfelfoldi/go-ethereum/wiki/Light-Ethereum-Subprotocol-%28LES%29) is wrong. It currently reads:

    GetProofs [+0x08, reqID: P, [ [blockhash: B_32, key: B_32, key2: B_32, fromLevel: P], ...]]
    [...] each proving the value of index key from the state trie of the given block (if key2 is
    empty), or the storage value of index key2 from the storage trie referenced in the account at
    key. [...]

But I believe it should instead read

    [...] each proving the value of index key2 from the state trie of the given block (if key is
    empty), or the storage value of index key2 from the storage trie referenced in the account at
    key. [...]

**Comment by prad38** [comment]
Dont ail mee

**Comment by lihailei2016** [comment]
兄弟你很6
