### ISSUE TITLE
"invalid byte" error why try to import key from Linux on Windows.

### ISSUE THREAD

**Issue by OneOfMany07** [ethereum/go-ethereum#15680]
Tried to import my recently created account from my Ubuntu host to my Windows 10 host (both using current released version of Geth) and hit an error after spending the effort to get the file transferred.  Tried to follow directions here https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts but it doesn't say how to export the keystore, only import it.  Feels like the docs are lacking there.

#### System information

Geth version: 1.7.3-stable
OS & Version: Ubuntu 17.10 -> Windows 10

#### Expected behaviour
Able to import keystore from Ubuntu client on Windows 10 client

#### Actual behaviour
Get error...

"Fatal: Failed to load the private key: encoding/hex: invalid byte: U+007B '{'"

#### Steps to reproduce the behaviour
Copy your ~/.ethereum/keystore/UTC--* file from your Linux host to the Windows host.

**Comment by karalabe** [comment]
You should just copy your key file into your keystore folder on Windows. Importing a key means pulling in a raw un-encrypted private key. Here you have a proper key file that you just need to copy.

**Comment by OneOfMany07** [comment]
Aha!  That makes more sense.  I didn't understand why I had to copy this
file if I know my passphrase and address.

Again, might be good to have someone, that can, update the documentation a
little to clarify that.  Maybe mention the two possible ways to
import/shift/copy the account into multiple clients.

**Comment by karalabe** [comment]
:+1:
