### ISSUE TITLE
Memory leak/crash.

### ISSUE THREAD

**Issue by oeneme** [ethereum/go-ethereum#15688]
https://imgur.com/a/ikqOH
Geth version: v1.7.3
OS & Version: Ubuntu 16.04.3 & Debian 9.3
(and as i result i can only run it for about an hour at a time)

**Comment by huckphin** [comment]
Hi @oeneme 

Can you post a stack trace of what you are seeing?
Also, what are the command line flags that you are passing to `geth`?

**Comment by oeneme** [comment]
It never frees memory.

Hi @huckphin 

I've used several commands:
geth
geth --syncmode fast --cache 128
geth --syncmode fast --cache 4096
etc.

Here is a paste from the terminal after the computer runs out of memory and the program crashes:

goroutine 16029 [select]:
github.com/ethereum/go-ethereum/p2p.(*Peer).pingLoop(0xc422e7fbc0)
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:235 +0x182
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:190 +0x117

goroutine 21198 [chan receive]:
github.com/ethereum/go-ethereum/p2p/discover.(*udp).ping(0xc420097650, 0xf803173f0097c834, 0x5845cde007b12813, 0xf91677c91a28e62, 0xf8f3b8f13686c0e2, 0xd1b597c9f997a2b1, 0xd9bde763938357d6, 0x6764d600f868ea45, 0xb475fa2869994821, 0xc5012ab590, ...)
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/udp.go:279 +0x267
github.com/ethereum/go-ethereum/p2p/discover.(*Table).ping(0xc422658000, 0xf803173f0097c834, 0x5845cde007b12813, 0xf91677c91a28e62, 0xf8f3b8f13686c0e2, 0xd1b597c9f997a2b1, 0xd9bde763938357d6, 0x6764d600f868ea45, 0xb475fa2869994821, 0xc5012ab590, ...)
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:533 +0xd3
github.com/ethereum/go-ethereum/p2p/discover.(*Table).pingpong(0xc422658000, 0xc5153f7800, 0x3173f0097c83400, 0x45cde007b12813f8, 0x91677c91a28e6258, 0xf3b8f13686c0e20f, 0xb597c9f997a2b1f8, 0xbde763938357d6d1, 0x64d600f868ea45d9, 0x75fa286999482167, ...)
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:513 +0xb5
github.com/ethereum/go-ethereum/p2p/discover.(*Table).bond(0xc422658000, 0x3173f0097c83400, 0x45cde007b12813f8, 0x91677c91a28e6258, 0xf3b8f13686c0e20f, 0xb597c9f997a2b1f8, 0xbde763938357d6d1, 0x64d600f868ea45d9, 0x75fa286999482167, 0xc422666fb4, ...)
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:485 +0x6b5
github.com/ethereum/go-ethereum/p2p/discover.(*Table).bondall.func1(0xc422658000, 0xc501240ae0, 0xc514acfb80)
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:430 +0xdb
created by github.com/ethereum/go-ethereum/p2p/discover.(*Table).bondall
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/discover/table.go:429 +0x9a

goroutine 21088 [runnable]:
internal/poll.runtime_pollWait(0x7f0dee1858b0, 0x72, 0x0)
	/usr/lib/go-1.9/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc512e72b98, 0x72, 0xffffffffffffff00, 0x1850720, 0x1849580)
	/usr/lib/go-1.9/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc512e72b98, 0xc50e1dc500, 0x325, 0x34d)
	/usr/lib/go-1.9/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc512e72b80, 0xc50e1dc5b3, 0x325, 0x34d, 0x0, 0x0, 0x0)
	/usr/lib/go-1.9/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc512e72b80, 0xc50e1dc5b3, 0x325, 0x34d, 0x0, 0x0, 0x0)
	/usr/lib/go-1.9/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc4fcd47c18, 0xc50e1dc5b3, 0x325, 0x34d, 0x0, 0x0, 0x0)
	/usr/lib/go-1.9/src/net/net.go:176 +0x6d
io.ReadAtLeast(0x7f0dee0520f0, 0xc4fcd47c18, 0xc50e1dc5b3, 0x325, 0x34d, 0x325, 0x480, 0xc4201d6d01, 0xc50e1dc480)
	/usr/lib/go-1.9/src/io/io.go:309 +0x86
io.ReadFull(0x7f0dee0520f0, 0xc4fcd47c18, 0xc50e1dc5b3, 0x325, 0x34d, 0xc50e1dc480, 0x133, 0x480)
	/usr/lib/go-1.9/src/io/io.go:327 +0x58
github.com/ethereum/go-ethereum/p2p.readHandshakeMsg(0x184bee0, 0xc458c31ba0, 0x133, 0xc4203b5470, 0x7f0dee0520f0, 0xc4fcd47c18, 0xc442b257e0, 0x484100, 0x10, 0xc442b25778, ...)
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:499 +0x3bc
github.com/ethereum/go-ethereum/p2p.receiverEncHandshake(0x7f0dee0520c0, 0xc4fcd47c18, 0xc4203b5470, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:352 +0xee
github.com/ethereum/go-ethereum/p2p.(*rlpx).doEncHandshake(0xc50077ee70, 0xc4203b5470, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:178 +0x3ae
github.com/ethereum/go-ethereum/p2p.(*Server).SetupConn(0xc4200ac900, 0x185ebe0, 0xc4fcd47c18, 0x4, 0x0)
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:713 +0x1c7
github.com/ethereum/go-ethereum/p2p.(*Server).listenLoop.func1(0xc4200ac900, 0x185ebe0, 0xc4fcd47c18, 0xc4216fe9c0)
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:692 +0x51
created by github.com/ethereum/go-ethereum/p2p.(*Server).listenLoop
	/build/ethereum-ZSPmrv/ethereum-1.7.3+build11486+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:691 +0x42f

**Comment by karalabe** [comment]
There is a known memory issue during sync. We haven't yet been able to pinpoint where the danglig references comes from. Bonus point to whoever has a hint.

**Comment by gurglespuge** [comment]
I am having the same issue with version : Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9
any suggestions, what version can I drop down to ?

**Comment by TUTUBIG** [comment]
so do i  geth/v1.8.2-stable

**Comment by dream0329** [comment]
the same

**Comment by adamschmideg** [comment]
Probably the same as #18139
