### ISSUE TITLE
whisper: TestSimulation fails when existing node running

### ISSUE THREAD

**Issue by nolash** [ethereum/go-ethereum#15685]
#### System information

Geth version: `1.8.0-unstable`
OS & Version: Linux 4.13.7-1-ARCH
Commit hash : (if `c6069a627c42c21fc02d0770d39db9a9be45b180`)

#### Expected behaviour

Test should pass

#### Actual behaviour

If node is already running, `p2p.Server.Start()` fails because port is taken.

#### Steps to reproduce the behaviour

`go test -v -cpu 4 ./whisper/whisperv5/ -run Simulation`

#### Backtrace

````
=== RUN   TestSimulation
--- FAIL: TestSimulation (0.00s)
	peer_test.go:159: failed to start server 0.

````

**Comment by original-brownbear** [comment]
Gave this a shot in #15687 :)
