### ISSUE TITLE
geth 1.7.3 is never syncronized...

### ISSUE THREAD

**Issue by freeyssu** [ethereum/go-ethereum#15681]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: 1.7.3
OS & Version: both of Windows and Linux
Commit hash : N/A

Hi guys.

I begined geth syncing with --fast option from 5days ago But syncing is never ended.
Threre are few "imported new block reciept" however so many "imported new state entries" logs.
I tried not only on both of Windows and Linux but also geth 1.7.0 ~ 1.7.3.
Is it only problem to just me?

**Comment by KainniaK** [comment]
There are bugs in 1.7.3, light mode stopped working for me, completely.

**Comment by nixxholas** [comment]
Upvote

**Comment by SergeyZYX** [comment]
Run in the same problem here.  Start syncing on my notebook with win-10, leave it running for 2days! No luck. Then I run geth on linux server and it synched in just 1 night! So I copied the blockchain folder from linux to windows (40Gb+) and here we go. Pretty easy one!

**Comment by ETHMOONBASE** [comment]
Yep, -fast - cache 2014,

downloaded 4.75m blocks then after that it slows down exponentially, bloats to take over all available system memory and eventually the process must be ended because the computer is bricked.

**Comment by starzou** [comment]
+1
