### ISSUE TITLE
blockchain synced twice in same database

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#15694]
```
ethereum/client-go               latest                  5234912bb212        2 days ago          37.1MB
```

- created docker container with:

```
 docker run -it -p 30303:30303 -v /ethereum_wallet:/root/.ethereum ethereum/client-go console
```

- destroyed docker container and moved ```/ethereum_wallet``` to ```/home/ethereum_wallet``` permissions preserved.

- created new docker container:

```
 docker run -it -p 30303:30303 -v /home/ethereum_wallet:/root/.ethereum ethereum/client-go console
```

now it's resyncing ? 

```
> eth.syncing
{
  currentBlock: 944726,
  highestBlock: 4751283,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 532141
}
>
```

And the directory size seems really wrong:

```
43G     total
➜  chaindata pwd
/home/ethereum_wallet/geth/chaindata
➜  chaindata

```

This is not working as I intended if its syncing the block chain twice, is that the case? how do I delete one of the two copies if yes? Also why is it syncing it again if yes?

**Comment by cloudkitsch** [comment]
I checked to see if my wallet is still available and it is but I'm just not sure if it's syncing a second copy of the blockchain now or if this is the normal size

**Comment by cloudkitsch** [comment]
Really all I was hoping to accomplish with this project was: 

`- create a wallet
- seed the wallet (create a minimal number of transactions) 
- back-up the private key 

Are there not any good wallet apps for windows or something besides this that's less tedious that actually works? I understand coinbase is an option however I don't want to use them, I want my own it sort of negates the purpose if somebody else has my private key IMHO.
