### ISSUE TITLE
Failed to close database too many open files

### ISSUE THREAD

**Issue by abraham1901** [ethereum/go-ethereum#15697]
Hi,

#### System information

Geth version: Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
OS & Version: Ununtu 16.04
Repo: ppa http://ppa.launchpad.net/ethereum/ethereum/ubuntu 
Package: 1.7.3+build11486+xenial

#### Actual behaviour
geth --rinkeby
After ctrl+C always files limit:
ERROR[12-18|12:44:29] Failed to close database                 database=/home/eth/.ethereum/rinkeby/geth/chaindata err="open /home/eth/.ethereum/rinkeby/geth/chaindata/160748.ldb: too many open files"

I'm cannot change system limit, because it's hardcoded:
flag.go:
        if limit > 2048 { // cap database file descriptors even if more is available
                limit = 2048
        }

Why?

**Comment by hekeli** [comment]
Yeah this is crazy, why is there a hardcoded 2048 limit?? I have 24000 .ldb files that it's trying to open.

Developers hello!
