### ISSUE TITLE
How long do I need to sit here starring at "Looking for peers..." in light mode? 

### ISSUE THREAD

**Issue by KainniaK** [ethereum/go-ethereum#15695]
Seriously, I would like to make a payment. I am very sorry I don't have a big enough hard drive to run Ethereum Wallet in full or fast mode. I am sorry, I wish it was different. I wish my internet was  faster. I wish a lot of things. But right now I would like to make a payment using Ethereum, I don't want to be sorry about that.  Opening up Ethereum Wallet is a gamble right now, if I do it at the correct time during the day I might connect with one peer long enough to actually make a transaction.

Come one, please fix this!!!!! I need Ethereum Wallet to be reliable enough!!!!

**Comment by lmars** [comment]
@KainniaK have you considered using [MetaMask](https://metamask.io/) or [MyEtherWallet](https://www.myetherwallet.com/), both of which store your keys locally but support connecting to public Ethereum gateways like [Infura](https://infura.io/) to send signed transactions?

Also, I think we should keep issues on GitHub for bugs in the go-ethereum code, whereas what you are reporting is more a community issue (see my comment [here](https://github.com/ethereum/go-ethereum/issues/15454#issuecomment-352216741)).

**Comment by KainniaK** [comment]
Will these allow me so see my accounts even when I am offline? Also how safe is it to have my brower mixed with Ethereum? I don't trust browsers to much.

**Comment by ligi** [comment]
> Will these allow me so see my accounts even when I am offline? Also how safe is it to have my brower mixed with Ethereum? I don't trust browsers to much.

maybe WALLETH is an option for you - http://walleth.org

you can see your accounts when you are offline and no need to trust browsers (I understand your feeling there). It also does not need that good of an internet-connection as a full-node needs.
