### ISSUE TITLE
insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by got3nks** [ethereum/go-ethereum#15709]
```
Geth
Version: 1.4.11-stable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.6
```

We have an address with a balance of 0.02138 ETH
```
> addr='0x....';
> eth.getBalance(addr);
21380000000000000
```
Using gasPrice = 30 Gwei, gas = 21000, we expect 0.00063 ETH in transaction fee, so we try to send 0.02075 ETH.

```
    [gasPrice] => 0x6fc23ac00
    [gas] => 0x5208
    [value] => 0x49b803db16e000
    [to] => 0x..
    [from] => 0x..

```
Failing with 'insufficient funds for gas * price + value'. Why?

**Comment by karalabe** [comment]
We do not support Geth 1.4.11 any more, it's tens of releases old. There have been a very large number of fixes with regard to pretty much everything in Geth, so there's little point to try and debug an old version.

**Comment by got3nks** [comment]
This is the version we are currently running:

instance=Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9.2
