### ISSUE TITLE
why some transactions pending over and over again?

### ISSUE THREAD

**Issue by wcw84** [ethereum/go-ethereum#15719]
Hi all,
I found some transactions to a contract are always in the status of pending, and after (maybe, about )half an hour, the transaction will append to the top of queue, and the "Age" start from "1 min ago":
https://etherscan.io/address/0x69508230dfa8c4211fd0c419ff6590f25cd25f0a

I have two screen shots, you can see that:
![image](https://user-images.githubusercontent.com/7152596/34214891-bb2d212a-e5de-11e7-90db-a057b8da0dfd.png)
I took the image above more early, and the next image about half an hour(I not sure the exact time) later:
![image](https://user-images.githubusercontent.com/7152596/34214940-d45e5268-e5de-11e7-94e5-001e1301be21.png)
take the txHash "0xacf8aa67da3213..." for example, in the first image, it was between the hash "0x7dabd74ae25cc9..." and "0xcba723e49689a2...", and then later, in the second image, it was in another position, it seems have been pull out and push back the queue again.
Other transactions in the image have the similar problem.
I not sure whether I should ask this question here, if anyone can me what happened or where to ask this question, I will very appreciate that.

Thanks in advanced.

**Comment by peterkristel** [comment]
Whats yous ite?

**Comment by karalabe** [comment]
This is some etherscan quirk. I've also seen it, but it doesn't originate from go-ethereum We don't maintain the age of transactions as all.

My guess is that etherscan periodically resubmits the transactions it knows about and the times are from when it last did a resubmit.

**Comment by wcw84** [comment]
@peterkristel what is ite? I dont know what you mean

**Comment by wcw84** [comment]
@kaneshin Thanks. I think you are right. I check from https://www.etherchain.org/tx/25d6789e40e87ae04f74e22f9daac1d72ab4c841a921246bc4758d78b2e1292f
the "age" is 2 hours ago, this age seems the right one, but not 11mins from https://etherscan.io/tx/0x25d6789e40e87ae04f74e22f9daac1d72ab4c841a921246bc4758d78b2e1292f
