### ISSUE TITLE
abi.tupleUnpack() fails to match event (or method?) parameters with underscores

### ISSUE THREAD

**Issue by shoenseiwaso** [ethereum/go-ethereum#15710]
It's fairly common to see underscores in event and method names in Solidity smart contracts. For example:
https://github.com/kinfoundation/kin-token/blob/master/contracts/ERC20.sol

However, abi.tupleUnpack() will fail to match against these when populating struct members.
https://github.com/ethereum/go-ethereum/blob/dec8bba9d4c5fcb3dd7e51f0f794b3e895c7f52d/accounts/abi/method.go#L113

**Comment by shoenseiwaso** [comment]
More specifically, I think it only relates to parameters where the underscore is the *first* character, because it's therefore not visible beyond that package in Go. So the `TODO` note in line 112 in `method.go` about adding tags wouldn't help. 

I'm planning on submitting a pull request to fix this in the next few weeks, but happy not to if someone else is already working on a fix.

**Comment by holiman** [comment]
> therefore not visible beyond that package in Go

Ah, nice catch..

**Comment by shoenseiwaso** [comment]
Agreed it requires some thought on the best approach. Two ideas:

1. Remove the underscore (and any other following non-alpha chars) and uppercase the first alpha char in the identifier. Good for the typical case where it’s just a single underscore then an alpha char, and indentifier name collisions within that context are unlikely. Would require handling of collisions should they happen, and cases of only non-alpha chars (‘_123’, etc.)

2. Preface the identifier with an uppercase ‘A’. Would need to handle collisions, although I haven’t seen this pattern (e.g., identifiers already named ‘A_abc’). For the typical case of just a single underscore followed by alpha chars, I think this option isn’t as nice. 

Other ideas?

**Comment by holiman** [comment]
I agree about option 2, using a prefix. If we remove things, we lose the ability to unpack->pack->unpack, which is always a good test for any coder/decoder pipeline.  

The prefix solution needs to be added both into pack and unpack when dealing with structs. Note, I'm doing a refactor on the abi package (https://github.com/ethereum/go-ethereum/pull/15731), so it'll have to be added into the `arguments.go`. I can follow up with a PR once that's merged (feel free to beat me to it:))

**Comment by holiman** [comment]
Note: if we add prefixes, we should _always_ add prefixes, imo. Not only when there's an underscore. Otherwise there will be quirks in the one-in-a-million case when someone has a field called `A_foobar`.

**Comment by shoenseiwaso** [comment]
All makes sense. If I get some time over the upcoming "holidays" I'll see if I can put together a PR. But don't wait for me if you get to it first since you're already moving at speed with the refactor of ABI.

**Comment by karalabe** [comment]
I've hit this same issue today. I opened a PR to fix unmarshaling such outputs into structs via abigen: https://github.com/ethereum/go-ethereum/pull/15766 . I'd assume a similar approach is enough to fix even unmarshaling too and input marshaling.
