### ISSUE TITLE
 insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by got3nks** [ethereum/go-ethereum#15728]
```
Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.2
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

We have an address with a balance of 0.02138 ETH
```
> addr='0x....';
> eth.getBalance(addr);
21380000000000000
```
Using gasPrice = 30 Gwei, gas = 21000, we expect 0.00063 ETH in transaction fee, so we try to send 0.02075 ETH.

```
    [gasPrice] => 0x6fc23ac00
    [gas] => 0x5208
    [value] => 0x49b803db16e000
    [to] => 0x..
    [from] => 0x..

```
Failing with 'insufficient funds for gas * price + value'. Why?

**Comment by karalabe** [comment]
Can you post the command you are using to send the transaction?

**Comment by got3nks** [comment]
After

**Comment by philoctetes409bc** [comment]
send does not automatically calculate / deduct the cost you have to do that yourself. so this will happen when you try to send the full value of your wallet, but don't leave enough to cover the gas price cost.

**Comment by got3nks** [comment]
If you read the OP, I'm deducting the cost of gas.

**Comment by got3nks** [comment]
@karalabe this issue is only getting worse as the blockchain is getting more bloated.

**Comment by EnchanterIO** [comment]
I have the same problem but maybe I am just doing something in a wrong way (trying to send my first transaction in my private network):

> Geth
> Version: 1.8.2-unstable
> Architecture: amd64
> Protocol Versions: [63 62]
> Network Id: 1
> Go Version: go1.8.3
> Operating System: linux
> GOPATH=/root/go/
> GOROOT=/usr/lib/go-1.8

Running node as: 

`geth --datadir node1/  --port 30311 bla bla --gasprice '1' --targetgaslimit 94000000`

`eth.getBalance(eth.coinbase);`
2014
`eth.gasPrice`
1
`eth.sendTransaction({'from':eth.coinbase, 'to':'0x581aadb31a2155becf8db3f6eecba6d2a5d55c55', 'value':web3.toWei(0x5, 'ether'), gas: 0x1})`

**Error: insufficient funds for gas * price + value**

(i tried to already change the gas for a higher value but without success). Any idea?
