### ISSUE TITLE
When in the console, Ctrl+C should clear the current line, not exit the program

### ISSUE THREAD

**Issue by drupalnomad** [ethereum/go-ethereum#1573]
In Bash Ctrl+C clears the current line, so I am familiar with that, but in Geth when I do this it exits the console and I loose my JS state.

Ideally it would work the same as Bash.

Ctrl+D should exit Geth console

**Comment by obscuren** [comment]
Agreed, however, **only** in interactive mode (e.g. `console`, `attach`)

**Comment by zelig** [comment]
fixed in https://github.com/ethereum/go-ethereum/pull/1658/commits

**Comment by jtremback** [comment]
Kind of odd, since most command line programs do close with Ctrl+C... python, node, etc etc. 

Whatever though, I'm glad I know it's Ctrl+D now (although I don't remember using anything that closes with Ctrl+D recently)

**Comment by drupalnomad** [comment]
Bash closes with Ctrl+D
