### ISSUE TITLE
Latest lock: 0,syncing...

### ISSUE THREAD

**Issue by AndroidSXK** [ethereum/go-ethereum#15736]
I am using geth1.7.3 for Android ,but however ,it never requests the Internet.It always displaying :
     My address:[::]:51953
     My protocols:[les]
      Latest lock: 0,syncing...

I am just a pure Android developer,I don't know Go Language，who can help me？My God！

**Comment by wenxinleong** [comment]
Same here I tried both geth1.7.3 and development release 1.8.0 having the same issue... any comment?

**Comment by wenxinleong** [comment]
Same here I tried both geth1.7.3 and development release 1.8.0 having the same issue... any comment?

**Comment by huynh268** [comment]
Has anyone solved this issue yet? @AndroidSXK @wenxinleong

**Comment by wenxinleong** [comment]
@huynh268 no

**Comment by adamschmideg** [comment]
Sorry, we dropped the ball on this. If you still have this problem, please open a new issue with more details (source code of the app, logs, etc).
