### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by cloudkitsch** [ethereum/go-ethereum#15733]
```
> eth.syncing
{
  currentBlock: 4771832,
  highestBlock: 4771973,
  knownStates: 2950917,
  pulledStates: 2944570,
  startingBlock: 4719461
}
```
tried
- resync from scratch (geth --syncmode "fast" --cache 1024 with geth-linux-amd64-1.7.3-4bb3c89d.tar.gz
- still cant see balance
- still cant send eth
- block containing relevant transaction is already synced, and private key is available, why doesn't it work given that?

please consider shutting down the project or marking as defunct if it isn't worth anybody's time.

**Comment by karalabe** [comment]
I've told you already, you need to wait until it finishes syncing. It doesn't sync block by block, it downloads the state at the last block. There are 57M state entries. You have to wait it out.

> please consider shutting down the project or marking as defunct if it isn't worth anybody's time.
Please consider getting a life, cheers.

**Comment by cloudkitsch** [comment]
Alright man that actually wasnt too clear but I can see thats what its doing now, I can see  processed=3405809, makes sense, sorry to be so annoying

**Comment by cloudkitsch** [comment]
just if you wouldn't mind helping me understand, the thing that is taking so long here is that it has to download 50M instances of the struct declared in this file? https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L52

if its not that then what data is it actually downloading?

**Comment by holiman** [comment]
No, that's not it. It downloads the 'state'. The 'state' is the full information about all accounts  (balances, code, nonce etc) in ethereum. The 57M things are chunks of state.

**Comment by cloudkitsch** [comment]
ok so this is not measurable then?

**Comment by cloudkitsch** [comment]
haha good one guys, 0.0001% of 50M xD so wheres the torrent for all this?

**Comment by cloudkitsch** [comment]
after the very long and painful sync process, its working ^_____^ ty
