### ISSUE TITLE
Unable to attach

### ISSUE THREAD

**Issue by dpisarewski** [ethereum/go-ethereum#15746]
#### System information

Geth version: `1.8.0-unstable-9d187f02`
OS & Version: Windows

When I try to attach to the running local node, I get an unexpected error message:

```
PS C:\Users\mutexin> geth attach
Fatal: Unable to attach to remote geth: no known transport for URL scheme "c"
PS C:\Users\mutexin> geth attach --datadir "D:\Programs\Ethereum"
Fatal: Unable to attach to remote geth: no known transport for URL scheme "d"
```

**Comment by wcw84** [comment]
I think you should:
geth attach http://host:port
or
geth attach /xxxx/geth.ipc 
xxxx is your datadir path

**Comment by sarbogast** [comment]
I'm getting the same error in the stable release of Geth 1.8, but only on Windows. On MacOS everything seems to be fine.

**Comment by sarbogast** [comment]
Apparently on Windows we now have to specify the IPC path, and it was not necessary in Geth 1.7.3:
`geth attach ipc:\\.\pipe\geth.ipc`

**Comment by oragious** [comment]
geth attach ipc:\\.\pipe\geth.ipc

This solution works for Win10 and v1.8.0-stable

**Comment by sarbogast** [comment]
It does. But once again an undocumented change, and a discrepancy between Windows and other platform. As an online instructor trying to keep my cours material up-to-date, these things are a PITA

**Comment by FrozenKiwi** [comment]
Quick Q - where do you find the IPC file?  I'm running geth without installing it (just unzipped the folder)

**Comment by FrozenKiwi** [comment]
never mind - just run the command in the same folder as the other instance and it seems to work

**Comment by tomw1808** [comment]
Is that expected behavior or will that be reverted to auto-discover the pipe on windows? I couldn't find anything in the changelogs, did I miss it?

**Comment by paulvi** [comment]
BTW, with Git Bash (for Windows) it is also possible to connect as

`./geth attach ipc:\\\\.\\pipe\\geth.ipc`

![image](https://user-images.githubusercontent.com/1614482/37808976-2c767e20-2e88-11e8-8cde-82031c1952dc.png)

**Comment by philipmatty** [comment]
Hi, specifying port worked for me. I had two nodes running in different ports and below attach command worked

geth attach http://localhost:8545
geth attach http://localhost:8547

**Comment by nukec** [comment]
confirmed geth attach ipc:\\.\pipe\geth.ipc works

**Comment by FirstBlockChain** [comment]
Hi Team,

I am using windows 32 bit GoEth.
Receiving below issue please help out.

![capture](https://user-images.githubusercontent.com/39359113/40155300-90fbd2a2-59b0-11e8-8eae-c7003e7de1b7.PNG)

Regards,
Ravi Shankar .L

**Comment by paulvi** [comment]
@FirstBlockChain This is not Q&A, go to https://ethereum.stackexchange.com/
For a new bug report or on stackexchange , specify used version, and the way you launched.

At first glance, you may have missed "\" before "."
Seen  
``geth attach ipc:\.\pipe\geth.ipc``


Should be   
`geth attach ipc:\\.\pipe\geth.ipc`

**Comment by 3esmit** [comment]
Can this be made by default in windows? `geth attach ipc:\\.\pipe\geth.ipc`

**Comment by uhuhh** [comment]
Same error with this conditions:
- Win7 @ x32
- mintty 2.8.5
Only works with 
./geth attach ipc:\\\\.\\pipe\\geth.ipc

**Comment by unicornyang** [comment]
can you give me 2 enthereum in the testnet..it's hard to get them

**Comment by unicornyang** [comment]
can you give me 2 enthereum in the testnet..it's hard to get them ..my wallet address is：0x341453f0026b436b6f506626f74191e2461bbe16

**Comment by unicornyang** [comment]
can you give me 2 enthereum in the testnet..it's hard to get them in china.my wallet address is：0x341453f0026b436b6f506626f74191e2461bbe16

**Comment by davoodmood** [comment]
how can i find my ipc path on windows?

**Comment by karalabe** [comment]
It always was `geth attach ipc:\\.\pipe\geth.ipc`, never a plain path. @davoodmood use the one mentioned previously. Geth also prints the path on startup.

**Comment by gumb0** [comment]
@karalabe Why not make it default on windows?

**Comment by karalabe** [comment]
Hmmm, it isn't? Then it should definitely be changed.

**Comment by Rbchi** [comment]
when we use : geth attach ipc:\\.\pipe\geth.ipc ,we need to keep our startnode.cmd or  geth --networkid 123 --dev --datadir data1 --rpc --rpcaddr 192.168.1.5 --rpc port 8545 --port 30303 running.

**Comment by Aristophanes888** [comment]
> Apparently on Windows we now have to specify the IPC path, and it was not necessary in Geth 1.7.3:
> `geth attach ipc:\\.\pipe\geth.ipc`

This is not working for me on Windows 10. I get the error "Fatal: Unable to attach to remote geth: Timed out waiting for pipe '\\.\pipe\geth.ipc' to come available"

**Comment by Hanafubuki** [comment]
After a long time I found out how to solve this. 

First initialize your geth like this (if you want to use rinkeby):
geth --rinkeby --rpc --rpcapi="personal,eth,network,web3,net" --ipcpath "\\.\pipe\geth.ipc"

And then open the console with the command:
geth attach ipc:\\.\pipe\geth.ipc

**Comment by KobbyRainworth** [comment]
> After a long time I found out how to solve this.
> 
> First initialize your geth like this (if you want to use rinkeby):
> geth --rinkeby --rpc --rpcapi="personal,eth,network,web3,net" --ipcpath "\.\pipe\geth.ipc"
> 
> And then open the console with the command:
> geth attach ipc:\.\pipe\geth.ipc

still not helping

**Comment by KobbyRainworth** [comment]
Tried all the above but got "unable to attach to remote geth: Access is denied."
What else can i do about this?

**Comment by nikhilupadhyay170** [comment]
> I think you should:
> geth attach http://host:port
> or
> geth attach /xxxx/geth.ipc
> xxxx is your datadir path

thanks, men it works for me...
