### ISSUE TITLE
Geth will not install on Centos 6

### ISSUE THREAD

**Issue by it-werxdotca** [ethereum/go-ethereum#15743]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `latest stable`
OS & Version: Centos 6
Commit hash : (if `develop`)

#### Expected behaviour
Install

#### Actual behaviour
Error during make

#### Steps to reproduce the behaviour
Updated Glibc 2.14

#### Backtrace

````
[backtrace]
````
cmd/compile/internal/gc.typecheck(0xc420ad4f80, 0x2, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:201 +0x782 fp=0xc421f6ad58 sp=0xc421f6abc8 pc=0xa3ef22
cmd/compile/internal/gc.typecheck1(0xc420ad5080, 0x2, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:569 +0x33d3 fp=0xc421f6bb98 sp=0xc421f6ad58 pc=0xa42833
cmd/compile/internal/gc.typecheck(0xc420ad5080, 0x2, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:201 +0x782 fp=0xc421f6bd28 sp=0xc421f6bb98 pc=0xa3ef22
cmd/compile/internal/gc.typecheck1(0xc420ad5180, 0x2, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:569 +0x33d3 fp=0xc421f6cb68 sp=0xc421f6bd28 pc=0xa42833
cmd/compile/internal/gc.typecheck(0xc420ad5180, 0x2, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:201 +0x782 fp=0xc421f6ccf8 sp=0xc421f6cb68 pc=0xa3ef22
...additional frames elided...
util.go:45: exit status 2
exit status 1
make: *** [geth] Error 1

**Comment by karalabe** [comment]
This is an issue with the Go compiler on 32 bit platforms. It's being tracked upstream and hopefully be fully fixed for Go 1.10 https://github.com/golang/go/issues/23222.

**Comment by karalabe** [comment]
We've merged a workaround on latest master.
