### ISSUE TITLE
High disk usage macOS Sierra

### ISSUE THREAD

**Issue by supercoffee** [ethereum/go-ethereum#15742]
I'm seeing over 900GB of disk writes after running geth for a few hours.  Network usage for the same time period is only 240MB. Where are all these writes coming from?

I really don't want to wear out my SSD. 

#### System information

Geth version:
```
Geth
Version: 1.7.3-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.2
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.9.2/libexec
```
OS & Version: OSX 10.12.6
Commit hash : N/A

#### Expected behaviour
Light amounts of data written to disk

#### Actual behaviour
Over 900 GB of disk writes after ~4 hours of running

#### Steps to reproduce the behaviour
Run macOS client in as system daemon
[Plists for geth + ethminer config](https://gist.github.com/supercoffee/40ef81c8a5be72c647c299eeb9aac97f)

#### Screenshot
<img width="943" alt="screen shot 2017-12-22 at 11 13 40 pm" src="https://user-images.githubusercontent.com/3880240/34317899-29ec81c4-e76e-11e7-848a-54689570ddbb.png">

<img width="943" alt="screen shot 2017-12-22 at 11 18 53 pm" src="https://user-images.githubusercontent.com/3880240/34317911-ae09bec2-e76e-11e7-88bb-4692cef1d0be.png">

**Comment by shbli** [comment]
Is it only happening on Mac OS Sierra?

**Comment by supercoffee** [comment]
I will try running it on Windows.  Stand by..
