### ISSUE TITLE
windows go build, and even the precomple freezes in win 7

### ISSUE THREAD

**Issue by olalawal** [ethereum/go-ethereum#1575]
C:\Windows\system32>geth
I0802 18:48:22.041382 6440 flags.go:383] WARNING: No etherbase set and no acc
ounts found as default
I0802 18:48:22.042382 6440 database.go:74] Alloted 16MB cache to C:\Users\ola
wal\AppData\Roaming\Ethereum\blockchain
I0802 18:48:22.048382 6440 database.go:74] Alloted 16MB cache to C:\Users\ola
wal\AppData\Roaming\Ethereum\state
I0802 18:48:22.056383 6440 database.go:74] Alloted 16MB cache to C:\Users\ola
wal\AppData\Roaming\Ethereum\extra
I0802 18:48:22.061383 6440 backend.go:290] Protocol Versions: [61 60], Networ
k Id: 1
I0802 18:48:22.062383 6440 backend.go:319] Blockchain DB Version: 3
I0802 18:48:22.062383 6440 chain_manager.go:232] Last block (#0) d4e56740f876
aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3 TD=17179869184
I0802 18:48:22.068384 6440 cmd.go:122] Starting Geth/v1.0.0/windows/go1.4.2
I0802 18:48:22.068384 6440 server.go:311] Starting Server

seems to hang there and nothing happens , I can do stuff like create accounts etc but the server wont start

**Comment by obscuren** [comment]
Could you run with `geth --vmodule=peer=6,server=6` for a while and dump the contents in a [gist](https://gist.github.com)?

**Comment by olalawal** [comment]
where do the contents go? when I run it with those arguments it still hangs is log file generated somewhere ?

**Comment by fjl** [comment]
The log is written to the console. You can redirect it to a file by running `geth 2>log.txt`.

**Comment by tgerring** [comment]
@olalawal Are you having issues with the latest version (1.2.2)?

I am building on Windows and not having problems
