### ISSUE TITLE
create "light" node

### ISSUE THREAD

**Issue by jontis** [ethereum/go-ethereum#15760]
I'm having problems syncing "light" and suspect it is because there are too few peers running light.
I have dedicated a server at home to hold a "fast" copy of the ethereum blockchain.
Can I use this as a server that broadcasts a "light" version of the blockchain and how please?

**Comment by ligi** [comment]
Please keep the issue tracker clean and ask questions e.g. on https://ethereum.stackexchange.com and the keyword for googling is "--lightserv"
