### ISSUE TITLE
apt-get update fails

### ISSUE THREAD

**Issue by titscrypto** [ethereum/go-ethereum#15763]
Hello,

I've thied to install geth on new clean debian machine, to do so I've done following:

sudo add-apt-repository ppa:ethereum/ethereum
sudo apt-get update

In responce I've got 

Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.cloud.google.com/ap
t cloud-sdk-stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3746C208A7317B0F
W: The repository 'http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.cloud.google.com/ap
t google-compute-engine-stretch-stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3746C208A7317B0F
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.cloud.google.com/ap
t google-cloud-packages-archive-keyring-stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3746C208A7317B0F
W: Failed to fetch http://packages.cloud.google.com/apt/dists/cloud-sdk-stretch/InRelease  The following signatures couldn't be verified because the public key is not availabl
e: NO_PUBKEY 3746C208A7317B0F
W: Failed to fetch http://packages.cloud.google.com/apt/dists/google-compute-engine-stretch-stable/InRelease  The following signatures couldn't be verified because the public 
key is not available: NO_PUBKEY 3746C208A7317B0F
W: Failed to fetch http://packages.cloud.google.com/apt/dists/google-cloud-packages-archive-keyring-stretch/InRelease  The following signatures couldn't be verified because th
e public key is not available: NO_PUBKEY 3746C208A7317B0F
E: Failed to fetch http://ppa.launchpad.net/ethereum/ethereum/ubuntu/dists/bionic/main/binary-amd64/Packages  404  Not Found
W: Some index files failed to download. They have been ignored, or old ones used instead.

there is some strange 'bionic' dist that i do not see here:
http://ppa.launchpad.net/ethereum/ethereum/ubuntu/dists/

Am I doing something wrong?

**Comment by karalabe** [comment]
Bionic is the new Ubuntu release, scheduled for April, 2018. I'm not really sure is Launchpad already supports building binaries for it though.

**Comment by karalabe** [comment]
Although I'm not sure it's wise to enable it, even if it somehow works. If the distro is not yet released, it means it may change quite a lot, so it could happen that a build launchpad does won't work after based packages get updated from underneath (ok, this won't happen for Geth because we statically link everything, but it still doesn't feel quite right to ship packages for unreleased distros).

**Comment by gardner** [comment]
Just in case anyone is trying to reproduce this. I'm getting this as well. Here's the Dockerfile:

```
FROM debian:stretch
LABEL version="0.0.1"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:ethereum/ethereum && \
    apt-get update && \
    apt-get install -y ethereum

EXPOSE 8545

CMD geth --rinkeby --rpc --rpcaddr 0.0.0.0
```

command to build it:

`docker build . -t gardner/ethereum`


Error message:

```
Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
Setting up packagekit-tools (1.1.5-2) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Processing triggers for sgml-base (1.29) ...
Processing triggers for ca-certificates (20161130+nmu1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Processing triggers for dbus (1.10.24-0+deb9u1) ...
Processing triggers for systemd (232-25+deb9u1) ...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 252, in add_ppa_signing_key
    tmp_keyring, tmp_secret_keyring, signing_key_fingerprint, tmp_keyring_dir):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 181, in _recv_key
    "--recv", signing_key_fingerprint,
  File "/usr/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'gpg'

Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Ign:3 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic InRelease
Hit:4 http://deb.debian.org/debian stretch-updates InRelease
Hit:5 http://deb.debian.org/debian stretch Release
Ign:7 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic Release
Ign:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
Ign:9 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main all Packages
Ign:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
Ign:9 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main all Packages
Ign:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
Ign:9 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main all Packages
Ign:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
Ign:9 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main all Packages
Ign:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
Ign:9 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main all Packages
Err:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
  404  Not Found
Ign:9 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main all Packages
Reading package lists...
W: The repository 'http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/ethereum/ethereum/ubuntu/dists/bionic/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update &&     apt-get install -y software-properties-common &&     add-apt-repository -y ppa:ethereum/ethereum &&     apt-get update &&     apt-get install -y ethereum' returned a non-zero code: 100
```

Seems like the ppa wants a full system. I will use the static binary instead for docker.

**Comment by karalabe** [comment]
I've added bionic builds to our PPAs. Unstable ones have been pushed already, stable ones will come with the next release (couple days).

**Comment by nyetwurk** [comment]
Where are the damn pubkeys? I don't have time for docker silliness.
```
Err:6 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1C52189C923F6CA9
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1C52189C923F6CA9
```

**Comment by nyetwurk** [comment]
Even worse, on debian add-apt-repository adds focal, and not anything remotely useful.

**Comment by nyetwurk** [comment]
```
sudo gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 1C52189C923F6CA9
```
did not help

**Comment by Gelassen** [comment]
> Just in case anyone is trying to reproduce this. I'm getting this as well. Here's the Dockerfile:
> 
> ```
> FROM debian:stretch
> LABEL version="0.0.1"
> 
> ENV DEBIAN_FRONTEND=noninteractive
> 
> RUN apt-get update && \
>     apt-get install -y software-properties-common && \
>     add-apt-repository -y ppa:ethereum/ethereum && \
>     apt-get update && \
>     apt-get install -y ethereum
> 
> EXPOSE 8545
> 
> CMD geth --rinkeby --rpc --rpcaddr 0.0.0.0
> ```
> 
> command to build it:
> 
> `docker build . -t gardner/ethereum`
> 
> Error message:
> 
> ```
> Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
> Setting up packagekit-tools (1.1.5-2) ...
> Processing triggers for libc-bin (2.24-11+deb9u1) ...
> Processing triggers for sgml-base (1.29) ...
> Processing triggers for ca-certificates (20161130+nmu1) ...
> Updating certificates in /etc/ssl/certs...
> 0 added, 0 removed; done.
> Running hooks in /etc/ca-certificates/update.d...
> done.
> Processing triggers for dbus (1.10.24-0+deb9u1) ...
> Processing triggers for systemd (232-25+deb9u1) ...
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
>     func(**kwargs)
>   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
>     return apsk.add_ppa_signing_key()
>   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 252, in add_ppa_signing_key
>     tmp_keyring, tmp_secret_keyring, signing_key_fingerprint, tmp_keyring_dir):
>   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 181, in _recv_key
>     "--recv", signing_key_fingerprint,
>   File "/usr/lib/python3.5/subprocess.py", line 247, in call
>     with Popen(*popenargs, **kwargs) as p:
>   File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> FileNotFoundError: [Errno 2] No such file or directory: 'gpg'
> 
> Hit:1 http://security.debian.org stretch/updates InRelease
> Ign:2 http://deb.debian.org/debian stretch InRelease
> Ign:3 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic InRelease
> Hit:4 http://deb.debian.org/debian stretch-updates InRelease
> Hit:5 http://deb.debian.org/debian stretch Release
> Ign:7 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic Release
> Ign:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
> Ign:9 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main all Packages
> Ign:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
> Ign:9 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main all Packages
> Ign:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
> Ign:9 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main all Packages
> Ign:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
> Ign:9 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main all Packages
> Ign:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
> Ign:9 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main all Packages
> Err:8 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
>   404  Not Found
> Ign:9 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main all Packages
> Reading package lists...
> W: The repository 'http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic Release' does not have a Release file.
> E: Failed to fetch http://ppa.launchpad.net/ethereum/ethereum/ubuntu/dists/bionic/main/binary-amd64/Packages  404  Not Found
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> The command '/bin/sh -c apt-get update &&     apt-get install -y software-properties-common &&     add-apt-repository -y ppa:ethereum/ethereum &&     apt-get update &&     apt-get install -y ethereum' returned a non-zero code: 100
> ```
> 
> Seems like the ppa wants a full system. I will use the static binary instead for docker.
Did you find a solution for this issue? I have faced with it too. 
```
FROM ubuntu:22.04
LABEL description="Container to setup and startup a private ethereum chain"
WORKDIR /opt/eth 
COPY ./blockchain/package.json /opt/eth
COPY ./blockchain/start_nodes.sh /opt/eth
COPY ./infrastructure/chain /opt/eth
# Install necessary software, sudo might not be required
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:ethereum/ethereum && \
    apt-get update && \
    apt-get install -y ethereum && \
    npm install
```
ends with error:
```
#0 59.60 Hit:5 https://ppa.launchpadcontent.net/ethereum/ethereum/ubuntu jammy InRelease
#0 59.83 Reading package lists...
#0 60.62 Reading package lists...
#0 61.34 Building dependency tree...
#0 61.49 Reading state information...
#0 61.67 The following additional packages will be installed:
#0 61.68   abigen bootnode clef evm geth rlpdump
#0 61.70 The following NEW packages will be installed:
#0 61.70   abigen bootnode clef ethereum evm geth rlpdump
#0 61.71 0 upgraded, 7 newly installed, 0 to remove and 4 not upgraded.
#0 61.71 Need to get 42.2 MB of archives.
#0 61.71 After this operation, 138 MB of additional disk space will be used.
#0 61.71 Do you want to continue? [Y/n] Abort.
------
failed to solve: process "/bin/sh -c apt-get update &&     apt-get install -y software-properties-common &&     add-apt-repository -y ppa:ethereum/ethereum &&     apt-get update &&     apt-get install ethereum &&     npm install" did not complete successfully: exit code: 1
```

**Comment by gardner** [comment]
This can happen when the container host runs out of space. Try: `docker system prune` then build again.
