### ISSUE TITLE
Configurable miner strategies for adjusting block gas limit

### ISSUE THREAD

**Issue by zsfelfoldi** [ethereum/go-ethereum#1576]
Selectable strategies:
- "no interference" (miner does not adjust the gas limit)
- fixed target value
- 2/3 block utilization strategy
- adjusting for uncle count target

**Comment by veox** [comment]
I've taken a cursory look and it seems that the latticework for "pluggable" gas limit strategy is there.

The "2/3 full" strategy with symmetric rise and fall is currently implemented as a default (and the only one provided?..).

Is anyone still working on this?

**Comment by fjl** [comment]
@veox nobody is working on this at the moment
