### ISSUE TITLE
FD limit is set to 2048 -- 1024 for DB handles and the rest for networking and other uses

### ISSUE THREAD

**Issue by mkqaimari** [ethereum/go-ethereum#15771]
https://github.com/ethereum/go-ethereum/blob/9d187f02389ba12493112c7feb15a83f44e3a3ff/cmd/utils/flags.go#L724

2048 should become a parameter so we can create more file handles and network sockets as we need to open more sockets to accept more connections.

**Comment by ryanschneider** [comment]
Agreed, this would be a helpful flag, IMO this request is also a "good first issue" candidate.

In the meantime you can give geth more file handles for network sockets via `prlimit`, e.g. something like:

```
# define $GETH_PID somehow (`pgrep geth`, etc.)
prlimit -p $GETH_PID --nofile=4096:4096
# confirm 
cat /proc/${GETH_PID}/limits
```

If you do this a couple seconds after `geth` starts, it'll continue to use half of the original 2048 handles for leveldb, while the rest added via `prlimit` are available for socket connections.

**Comment by subhodi** [comment]
Is there any research on why the limit is set to 2048?
Is it because of security, resource or any other limitations?
