### ISSUE TITLE
Management or JSON-RPC API Enhancement: determine the current sync mode

### ISSUE THREAD

**Issue by jpitts** [ethereum/go-ethereum#15780]
**Background**

geth CLI users as well as dapp browsers depending on geth may wish to get more feedback during the initial download / synchronization.

**Enhancement**

Add the ability to determine the current type or mode of synchronization to the Management or JSON-RPC API.

Additionally, add a synchronization status code and message. Status codes could include 'syncing' or 'error'. The status code and message would act as a pair. This pair should be expected to change once the underlying condition has changed.

Possible approach using the Management API:

> &gt; admin.downloaderStatus

Result:
> {
>    syncMode: 'fast',
>    syncStatus: 'error'.
>    syncMessage: 'Something just went wrong',
>    startingBlock: 0,
>    currentBlock: 0,
>    highestBlock: 0,    
> }

Possible approach using JSON-RPC:

> &gt; eth.syncing

Result:

> {
>    syncMode: 'fast',
>    syncStatus: 'error'.
>    syncMessage: 'Something just went wrong',
>    startingBlock: 0,
>    currentBlock: 0,
>    highestBlock: 0
> }

**References**

[Management APIs](https://github.com/ethereum/go-ethereum/wiki/Management-APIs)

[JSON-RPC API: eth_syncing](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_syncing)

[Ethereum_Wallet_Syncing_Problems](https://theethereum.wiki/w/index.php/Ethereum_Wallet_Syncing_Problems)

**Comment by evertonfraga** [comment]
Adding my 2 wei:

As the wallet uses `--syncmode fast`, having only `currentBlock` and `highestBlock` is not enough. As the >50M state entries take significant time to sync, this API method could also return some data about state entry download progress — or an overall sync %.

**Comment by skitzofrenicdev** [comment]
:family_man_man_girl_boy::bikini::mother_christmas:

**Comment by lelikalf** [comment]
type

**Comment by holiman** [comment]
Adding error message doesn't really make sense, geth continuously connects/disconects with peers, and if a problem occur it will reinitiate sync with other peers. 
Differentiating between the modes "doing fast-sync" and "caught up to head, now doing block-by-block import" (which is what full-sync does from genesis) is already possible: when fast-sync is still catching up, it will also output the number of states downloaded.

**Comment by holiman** [comment]
> As the >50M state entries take significant time to sync, this API method could also return some data about state entry download progress — or an overall sync %.

It's closer to `300M` now. The problem is that it's not really possible to know in advance how many state entries there are :( . Hardcoding it will become wrong. It might be possible to guesstimate it based on trie density, but it's flaky
