### ISSUE TITLE
Low peers: UDP use of closed network connection

### ISSUE THREAD

**Issue by TalkingAntColony** [ethereum/go-ethereum#1579]
Not sure if this is a separate issue from other low peer problems but here it is. I can't get more than ~3 peers now. Deleting nodekey, the nodes dir, or trying various flags hasn't helped. I was often maintaining 20-50 nodes during olympic.

Here is a log with lots of "use of closed network connection" alerts:

https://gist.github.com/TalkingAntColony/eade156c0bd0b84f6823

Here is my current startup flags:

geth --genesis genesis_block.json --rpc --rpcaddr localhost --rpcport "8545" --nat extip:71.225.210.78 --maxpeers "100" console 2>C:\Ethereum\geth_log.txt

Platform is Windows 8.1, high performance machine, high speed internet.

**Comment by kwentzell** [comment]
Same problem for me. I'm on a DSL connection in Miami, and although I initially connect to around 200-1000 peers, it stalls some time between a few minutes to an hour later, and I'm sitting mining the same block that never changes. I've tried things like --maxpeers "32" and --maxpendpeers "1", but these options don't seem to be respected in any regard.

Are there any recommended options to resolve this issue?

**Comment by fjl** [comment]
geth 1.0.2 has been released and contains the linked pull request. Please check whether this issue still occurs with geth 1.0.2.

**Comment by TalkingAntColony** [comment]
I updated. Still having low peers. Node restart yields a few dozen, then a
slow trickle down to a just a few over a few days.

**Comment by kwentzell** [comment]
The bug still exists for me, however the problem of the chain being out of sync with many inbound connections has been resolved. It used to stall when my outbound connections would go to around 1, but now the chain stays synced with 0, with around 100 inbound connections. This is after running 1.0.2 for about 36 hours, where it used to stall with 1.0.1 around an hour.

In other words, it looks like this is now a non issue if port forwarding is configured properly. The lack of outbound connections still raises an eyebrow though.

**Comment by fjl** [comment]
Sorry, my comment was a bit too early (1.0.2 did not contain the fix).
Geth 1.1.0 was released today. Please upgrade and report whether the
 situation has improved.

**Comment by kwentzell** [comment]
Heh, turns out I was already running the 1.1.0 branch and my 1.0.2 comment was incorrect. I was actually on 1.1.0. Sorry for the confusion.

**Comment by fjl** [comment]
In that case, do you still see these messages containing "use of closed network connection" when running with --verbosity=6 or --vmodule=udp=6?

**Comment by kwentzell** [comment]
I still see the messages upon start. It's pretty weird because I have no outbound rules set for my connection, UDP or TCP. It is running on a VM, but it has its own logical interface and not using goofy NAT through my machine.

Is there a specific way to turn on logging properly so I can submit a log? I tried --logfile /path/to/log.txt but to no avail, it creates the file but never appends text. I even gave everyone all permissions and made sure the file handle was closed.

**Comment by obscuren** [comment]
@fjl status?

**Comment by TalkingAntColony** [comment]
Still having mild peer issues, and I still see lots of "UDP send failed: use of closed network connection." At startup I'll get in the high teens but settle down around 10 peers, although maxpeers is 100. Occasionally I'll get down to just a few peers although in 1.1.3 it seems to be better.

Log here:
https://dl.dropboxusercontent.com/u/17385569/geth_log.txt

**Comment by fjl** [comment]
Thanks! Now that's a helpful log!

```
I0917 20:02:51.924850    6432 udp.go:477] Read error: WSARecvFrom udp [::]:30303: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
I0917 20:02:52.201205    6432 table.go:233] Bumping failures for 24a1021245c29b69: 1
I0917 20:02:52.201205    6432 udp.go:429] >>> 52.11.253.230:30303 discover.findnode
I0917 20:02:52.201205    6432 udp.go:431] UDP send failed: use of closed network connection
```

**Comment by TalkingAntColony** [comment]
@fjl I tried your latest commit above and am still having peer issues. See log:

https://gist.github.com/anonymous/f03843bc9c5b60bd02b9

**Comment by fjl** [comment]
In that log, the original issue where discovery stopped working is no longer present.

But here's another observation:
The log covers 145 seconds of execution. Within that time, there were 8 distinct cases where a block you received had a future timestamp. The error is a bit cryptic but tells more or less exactly what is going on:

```
I0126 21:08:41.151871    3260 fetcher.go:771] Peer c9bd41bc3c6ce895: block #910165 [45f51785…] import failed: block time is in the future: BlockFutureErr, 1453860569 > 1453860551
```

What this means is that the block was received at 21:08:41, but had a timestamp of 21:09:29 (1453860569 unix time, your time zone seems to be UTC-4:00) which is not within to allowed maximum of 30s difference.

To make a long story very short, it looks like your clock is off by a minute.

**Comment by TalkingAntColony** [comment]
Good catch! I synced the clock and now am stable at 40 peers, the most my node has seen since before frontier. I can provide a full log upon request if you would like to check one last time before closing this issue.
