### ISSUE TITLE
When I input"miner.start()"on my geth javascript， the mining work of my computer stays at  one percent and doesn't go on,why?

### ISSUE THREAD

**Issue by liulanghouzi** [ethereum/go-ethereum#15798]
I try to build a private chain on my computer (ubuntu) to test the geth. the version of my geth is the lastest one. However, when I open the geth javascript and start to mine after creating a account,  the mining work of my computer stays at  one percent and doesn't go on,why?
the codes are shown as follows:
1. Installing geth from PPA
sudo apt-get install software-properties-common
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt-get update
sudo apt-get install ethereum
2. Creating the genesis.json
The concent of genesis,json is shown as follows:
{
 "alloc": {},
 "config": {
   "chainID": 72,
   "homesteadBlock": 0,
   "eip155Block": 0,
   "eip158Block": 0
 },
 "nonce": "0x0000000000000000",
 "difficulty": "0x4000",
 "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
 "coinbase": "0x0000000000000000000000000000000000000000",
 "timestamp": "0x00",
 "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
 "extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
 "gasLimit": "0xffffffff"
}
geth init genesis.json
3. Opening the geth javascript
geth --networkid=5 console
4. Mining
personal.newAccount("12")
miner,start()
....
Then, after a long time , the ming work of my computer is still staying at one percent.
Who can tell me the reason and how to resolve this problem ?thanks
````

**Comment by liulanghouzi** [comment]
Notely, I run  this program on my virtual machine and the operate system is ubuntu 14.04

**Comment by karalabe** [comment]
Are you synced with the network? The miner is stopped if there's a synchronization in progress.

**Comment by liulanghouzi** [comment]
The blockchian is private and used for testing.  Should I synchronize with the network? I am a tiro and not very familiar with the geth. Did you mean that there is someone who have created the same genesis.json with mine  and I need to synchronize with him ? Or I should create a new genesis.json which is different from others? @karalabe

**Comment by karalabe** [comment]
What logs do you see?

**Comment by liulanghouzi** [comment]
INFO [01-03|03:50:20] Starting peer-to-peer node               instance=Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9
INFO [01-03|03:50:20] Allocated cache and file handles         database=/home/siguanlin/.ethereum/geth/chaindata cache=128 handles=1024
INFO [01-03|03:50:20] Initialised chain configuration          config="{ChainID: 50 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: <nil> Engine: unknown}"
INFO [01-03|03:50:20] Disk storage enabled for ethash caches   dir=/home/siguanlin/.ethereum/geth/ethash count=3
INFO [01-03|03:50:20] Disk storage enabled for ethash DAGs     dir=/home/siguanlin/.ethash               count=2
INFO [01-03|03:50:20] Initialising Ethereum protocol           versions="[63 62]" network=5
INFO [01-03|03:50:20] Loaded most recent local header          number=0 hash=f9e16e…23c5f3 td=256
INFO [01-03|03:50:20] Loaded most recent local full block      number=0 hash=f9e16e…23c5f3 td=256
INFO [01-03|03:50:20] Loaded most recent local fast block      number=0 hash=f9e16e…23c5f3 td=256
INFO [01-03|03:50:20] Loaded local transaction journal         transactions=0 dropped=0
INFO [01-03|03:50:20] Regenerated local transaction journal    transactions=0 accounts=0
INFO [01-03|03:50:20] Starting P2P networking 
INFO [01-03|03:50:22] UDP listener up                          self=enode://e312cd3c672cb02e9d296fca0be7684c11ee1a171e5db88913209e0f5bd900852bac7bbd9e718ea0141742dfd47e67b0d186fc1813ae2866f78f9af3f6d04765@[::]:30303
INFO [01-03|03:50:22] RLPx listener up                         self=enode://e312cd3c672cb02e9d296fca0be7684c11ee1a171e5db88913209e0f5bd900852bac7bbd9e718ea0141742dfd47e67b0d186fc1813ae2866f78f9af3f6d04765@[::]:30303
INFO [01-03|03:50:22] IPC endpoint opened: /home/siguanlin/.ethereum/geth.ipc 
Welcome to the Geth JavaScript console!

instance: Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9
coinbase: 0x6d5a55f8ae906724531a150da13d4722d903f9fc
at block: 0 (Wed, 31 Dec 1969 16:00:00 PST)
 datadir: /home/siguanlin/.ethereum
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
@karalabe

**Comment by karalabe** [comment]
Ok, but what does it print after you start mining?

**Comment by liulanghouzi** [comment]
> miner.start()
INFO [01-03|03:55:06] Updated mining threads                   threads=0
INFO [01-03|03:55:06] Transaction pool price threshold updated price=18000000000
null
> INFO [01-03|03:55:06] Starting mining operation 
INFO [01-03|03:55:06] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=254.431µs
@karalabe 
Then, the mining work will stay in this status and does't go on. I really don't know why. Is it because my virtual machine's memory is too small?

**Comment by coolmagic** [comment]
@liulanghouzi Did you get this started? I am having same issue

**Comment by yifon** [comment]
Same issue

**Comment by iluysperry** [comment]
Same issue - Centos7 in Google Cloud with geth  1.8.5

**Comment by iluysperry** [comment]
[root@eth sperry]# geth --datadir /root/sperry --networkid 33 --nodiscover --maxpeers 0 console
INFO [04-21|19:39:05] Maximum peer count                       ETH=0 LES=0 total=0
INFO [04-21|19:39:05] Starting peer-to-peer node               instance=Geth/v1.8.5-unstable-b15eb665/linux-amd64/go1.10.1
INFO [04-21|19:39:05] Allocated cache and file handles         database=/root/sperry/geth/chaindata cache=768 handles=512
INFO [04-21|19:39:05] Initialised chain configuration          config="{ChainID: 33 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: <nil> Constantinople: <nil> Engine: unknown}"
INFO [04-21|19:39:05] Disk storage enabled for ethash caches   dir=/root/sperry/geth/ethash count=3
INFO [04-21|19:39:05] Disk storage enabled for ethash DAGs     dir=/root/.ethash            count=2
INFO [04-21|19:39:05] Initialising Ethereum protocol           versions="[63 62]" network=33
INFO [04-21|19:39:05] Loaded most recent local header          number=0 hash=614a31…9df7ba td=200000000
INFO [04-21|19:39:05] Loaded most recent local full block      number=0 hash=614a31…9df7ba td=200000000
INFO [04-21|19:39:05] Loaded most recent local fast block      number=0 hash=614a31…9df7ba td=200000000
INFO [04-21|19:39:05] Loaded local transaction journal         transactions=0 dropped=0
INFO [04-21|19:39:05] Regenerated local transaction journal    transactions=0 accounts=0
INFO [04-21|19:39:05] Starting P2P networking
INFO [04-21|19:39:05] RLPx listener up                         self="enode://4446b9ecc1aec82b78dec7edb67c80eb688416e6720e604f696aa1ac0a4e0ce4cba519346171ee112e14db124fb3b2acabb5393d2e80d7763684daac5627126a@[::]:30303?discport=0"
INFO [04-21|19:39:05] IPC endpoint opened                      url=/root/sperry/geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/v1.8.5-unstable-b15eb665/linux-amd64/go1.10.1
INFO [04-21|19:39:05] Etherbase automatically configured       address=0x40394AbB8E41D67d4bE597D9FE451d1bBda7E92d
coinbase: 0x40394abb8e41d67d4be597d9fe451d1bbda7e92d
at block: 0 (Thu, 01 Jan 1970 00:00:00 UTC)
 datadir: /root/sperry
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> miner.start()
INFO [04-21|19:40:02] Updated mining threads                   threads=0
INFO [04-21|19:40:02] Transaction pool price threshold updated price=18000000000
INFO [04-21|19:40:02] Starting mining operation
null
> INFO [04-21|19:40:02] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=272.583µs

**Comment by VladisLove1** [comment]
in the brackets you should probably specify amount of cores involved in mining process. Like miner.start(1) to start mining with 1 core, miner.start(n) to start mining with n cores

**Comment by Rainshyabc** [comment]
> > miner.start()
> > INFO [01-03|03:55:06] Updated mining threads                   threads=0
> > INFO [01-03|03:55:06] Transaction pool price threshold updated price=18000000000
> > null
> > INFO [01-03|03:55:06] Starting mining operation
> > INFO [01-03|03:55:06] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=254.431µs
> > @karalabe
> > Then, the mining work will stay in this status and does't go on. I really don't know why. Is it because my virtual machine's memory is too small?

Hi, Do you have fix this problem, I have the same issue now.

**Comment by fjl** [comment]
Fixed in https://github.com/ethereum/go-ethereum/pull/17492
