### ISSUE TITLE
ln: failed to create symbolic link 'go-ethereum/.': File exists, make: *** [Makefile:25: all] Error 1 when I execute make all using Windows 10, plz help

### ISSUE THREAD

**Issue by Ajaysethi136** [ethereum/go-ethereum#15805]

**Comment by SriniKS** [comment]
I am getting the same error when I do a makeall - can someone help?

**Comment by SriniKS** [comment]
![image](https://user-images.githubusercontent.com/30432156/34837344-7fbca536-f720-11e7-820f-8cf91759dbe4.png)

**Comment by hunjixin** [comment]
The same happens on powershell

**Comment by ztkmkoo** [comment]
@SriniKS @OliviaSong 
Hi.. Any solution yet?

**Comment by FrankSzendzielarz** [comment]
I can't actually repro this exactly, though I am not sure why make is being run if the go install can be used. The docs here are incorrect https://geth.ethereum.org/install-and-build/Installing-Geth#build-it-from-source-code
 Make on windows is giving other errors though, though not if using WSL.
This looks like multiple issues, though it looks like primarily with the docs.

**Comment by adamschmideg** [comment]
To be fixed by #20116
