### ISSUE TITLE
keep Generating ethash verification cache  never stop!!!

### ISSUE THREAD

**Issue by MarkWh1te** [ethereum/go-ethereum#15809]
NFO [01-04|23:11:01] Generating ethash verification cache     epoch=95 percentage=42 elapsed=52h58m50.125
it has been more than two day, any one has solution?
os: ubuntu 16.04
verson:    1.7.3-stable-4bb3c89d

**Comment by karalabe** [comment]
What machine are you running this on? Is your CPU saturated?

**Comment by byroncoetsee** [comment]
Same thing happening to me.
OSX latest
Using only 2 threads (although have tried with all) so no, CPU isn't saturated (if I understand you correctly).

**Comment by GuimG** [comment]
Getting same error after minning a block! Any idea of what it is?
