### ISSUE TITLE
Same derived address with any password when importing presale wallet?

### ISSUE THREAD

**Issue by simondlr** [ethereum/go-ethereum#1580]
Hi. Having issues importing my presale wallet.

On OSX. No matter what password I put in (via interactive or through a file), it always generates the same derived address: 9cce34f7ab185c7aba1b7c8140d620b4bda941d6.

Is this normal?

**Comment by jerfelix** [comment]
Any progress on this issue?  I am seeing the same thing, on a Windows installation.

Fatal: Could not create the account: decrypted addr not equal to expected addr %
!(EXTRA string=9cce34f7ab185c7aba1b7c8140d620b4bda941d6, string= <my wallet address>)

**Comment by tgerring** [comment]
Could you please supply the commands you're using to import the wallet? Since this has not been reported in the issue, devs can't really reproduce it.

**Comment by simondlr** [comment]
geth import wallet presale_wallet.json

passphrase: <enter passphrase here>

---

Turns out I was entering the wrong password each time, but it was difficult to debug, because I wasn't if my password was incorrect, or whether there was an issue with importing it. It still seems like a bug for the derived address to be the same each time in the output even when entering the wrong passwords. When I entered the right password, it worked.

**Comment by tgerring** [comment]
So the issue seems to be a confusing error message as best I can tell?

First step would be to figure out why `9cce34f7ab185c7aba1b7c8140d620b4bda941d6 ` is always printed on wrong password, and then perhaps improving the error message to be more clear.

**Comment by jerfelix** [comment]
C:\ProgramData\chocolatey\lib\geth-stable\tools\geth.exe wallet import C:\ProgramData\chocolatey\lib\geth-stable\ethereum-wallet-LONGHEXSTRING.json

Fatal: Could not create the account: decrypted addr not equal to expected addr %
!(EXTRA string=9cce34f7ab185c7aba1b7c8140d620b4bda941d6, string=LONGHEXSTRING)

As Simondlr said, above, maybe it just always reports the same error when the wrong password is entered - and I am interpreting the message wrong?
