### ISSUE TITLE
Unable to compile geth code by executing make geth command in MINGW64, Bash: Make command Not found in Windows 10

### ISSUE THREAD

**Issue by Ajaysethi136** [ethereum/go-ethereum#15803]
Hi Team,

I have installed go language. I cloned the ethereum code repo in my local but when i try to compile the geth code by executing "make geth or make all" in Windows 10, it thrown an error stating make command not found, i downloaded MinGW also but still getting the same error.

Could you please suggest how can i proceed.

Regards,
Ajay
Emaild: ajaysethi136@gmail.com

**Comment by timtait** [comment]
It sounds like you're missing make in your PATH, install the mingw devkit -
 https://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe

and add the bin folder from that install to your PATH.
