### ISSUE TITLE
Use non-privileged user in Dockerfile

### ISSUE THREAD

**Issue by Doctor-love** [ethereum/go-ethereum#15816]
Currently, the Dockerfile used to build the official Docker images runs geth as root.
This is not required as far as I can tell from my usage and not a good practice security wise.

I suggest using the Dockerfile directive "USER" or switching to a low privileged user using gosu.

**Comment by alexkohler** [comment]
Wouldn't the package management (i.e. `apk add`) still require root permissions?

**Comment by Doctor-love** [comment]
Privileges could be dropped after the package installation and setup has been completed

**Comment by bclermont** [comment]
This issue had been """"""""""""""fixed"""""""""""""" in the [worst possible way](https://github.com/ethereum/go-ethereum/pull/16052#issuecomment-383351569) issue should be reopen

**Comment by bclermont** [comment]
https://github.com/ethereum/go-ethereum/pull/16052#issuecomment-383567275

this task should be reopen
