### ISSUE TITLE
[Clique PoA]sync failed with error:"Discarded bad propagated block"

### ISSUE THREAD

**Issue by leo-xinwang** [ethereum/go-ethereum#15817]
#### System information

Geth version: `1.8.0-unstable`
OS & Version: OSX
Commit hash : 1c2378b926b4ae96ae42a4e802058a2fcd42c87b

#### Expected behaviour
Start node one using: 
geth --datadir ~/.ethereum/poa init poa.json
geth --datadir ~/.ethereum/poa --unlock 0xxxx --mine --rpcaddr 127.0.0.1 --rpcapi eth,net,web3,personal  console

Start node two using: 
geth --datadir ~/.ethereum/poa1 init poa.json
geth --datadir ~/.ethereum/poa1 --port 30304 console --unlock 0xxxx

On node one type:
admin.addPeer("enode://xxx")
clique.propose("0xxxx", true)

On node two start mining:
miner.start()

Expect node one print out:
INFO [01-05|xx:xx:xx] Signed recently, must wait for others
INFO [01-05|xx:xx:xx] Imported new chain segment               blocks=1  txs=0 mgas=0.000 elapsed=539.557µs mgasps=0.000 number=21 hash=4680a4…ec6a25

#### Actual behaviour
INFO [01-05|xx:xx:xx] Signed recently, must wait for others
WARN [01-05|xx:xx:xx] Discarded bad propagated block           number=15 hash=b2f244…b5a265

#### Steps to reproduce the behaviour
Initiate the genesis with only node one's account

**Comment by leo-xinwang** [comment]
If node2 is started without --unlock 0xxxx, and execute personal.unlockAccount('0xxxx') on node 2 after mining is activated, the issue will not be reproduced.

**Comment by leo-xinwang** [comment]
After several tests, the root cause is that main node start from zero will have fast sync set. Then if secondary node starts to produce new block, the main node will sync with error. The work around is to start main node twice, then the fast sync is disabled. Sync between peers will be OK.

**Comment by Magicking** [comment]
I encountered the same issue at first sync between multiples nodes already in the `extraData` sealer list, workarounds:
 - Restarting a sealer node
or
 - Adding random sleep between launch of nodes

Tested with 3 nodes sealers on the same machine (same clock if that matters).

**Comment by smalaichami** [comment]
--syncmode "full"   does the trick... 
Run your nodes with above param, everything will work like a charm..

**Comment by holiman** [comment]
Yes, it's a problem on a brand new networks, the nodes aren't sure if they should start mining from scratch or do a fast-sync against a peer. By default, a node tries to fast-sync.
I'm not sure if this ticket contains anything that needs to be fixed...?

**Comment by adamschmideg** [comment]
The original issue seems to be addressed and there hasn't been any activity here for a long time.

**Comment by cyberiums** [comment]
Is there a solution to start a new network?
