### ISSUE TITLE
how can i run go-ethereum,/cmd/geth/main.go run fail,show many undefined error 

### ISSUE THREAD

**Issue by yujianFresh** [ethereum/go-ethereum#15814]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by fjl** [comment]
Use `make` to build geth, then run `./build/bin/geth`.
