### ISSUE TITLE
GETH stop 

### ISSUE THREAD

**Issue by boolee4web** [ethereum/go-ethereum#15818]
I have a hard disk problem on a 150 GB VPS server that was not well connected to the system. I got an error report:

CRIT [01-05 | 12: 44: 33] Failed to store last fast block's hash err = "write /home/xyz/.ethereum/geth/chaindata/137457.log: no space left on device"

I added a new disk, how is it best to continue the process?

Run ETH sync for first time and started with command   . /geth --fast --cache = 512

**Comment by MRANASSPRO** [comment]
Did you solve the problem. I am getting the same error after running 
`geth --rinkeby --syncmode "fast" --rpc --rpcapi db,eth,net,web3,personal --cache=1024  --rpcport 8545 --rpcaddr 127.0.0.1 --rpccorsdomain "*`
