### ISSUE TITLE
geth syncing stuck at 99% from last 2 days

### ISSUE THREAD

**Issue by SanjaySaluth** [ethereum/go-ethereum#15822]
Hi ,

I have been using geth to sync blockchain from past one week and struggling with it. Tried everything network settings and all, but it stuck on 99% always.I have 60GB of RAM but no help.
#### System information

Geth version: `v1.7.3-stable`
OS & Version: Linux Centos 

#### Expected behavior

Synchronization completed
#### Actual behaviour

Stuck on 99% and not going forward
Imported new stage entries in loop

#### Steps to reproduce the behavior
I have used these
geth --syncmode "fast" --cache=15360
geth --syncmode "fast" --cache=4096

Please check, Need help.

**Comment by suyash515** [comment]
I am having the same problem since the last 10 days.

**System Information**
Geth version: v1.7.3-stable
OS: Ubuntu 16.04.3 LTS (Xenial)

More specifically, the node is never fully synchronised, and it always lags behind the last 200-1000 blocks. I have already tried the following solutions without any success:
1. Deleted the database and restarted the sync
2. Increased the cache from 1024 to 4096
3. Increased the number of peers from 100 to 200
In terms of disk space, everything seems to be ok - I have 160GB free disk space, no its definitely not a disk space issue.

**Comment by colorprint** [comment]
It seems I have the same issue on Windows 10

**Comment by 10a7** [comment]
I have this issue nearly every time I attempt a fresh sync of a geth node. It's a known problem and I have yet to find anyone that actually knows exactly why this is occurring, or how to fix it in a way that isn't just "try again." Issue #15001 is the best resource for this so far.

**Comment by suspended** [comment]
Same problem on Ubuntu 16.04 - deleted my chain data folder to sync again to no avail

**Comment by SidHarder** [comment]
I am experiencing the same issue. My project is at a standstill until I can get a node synced.  I have been trying now for a couple of weeks now.

**Comment by 10a7** [comment]
@SidHarder If you don’t need anything specific to the Geth API, try running Parity in `--geth` compatibility mode. This is the “workaround” I have.

I have been attempting to sync geth on SSD-backed VPS instances with multiple cores and over 8GB of RAM (and 4GB of swap). Fast sync will complete, pivot, and then blocks will trickle in at a rate of one every 20 seconds or so (while blocks are generated ~15 sec on average). Peer count doesn’t matter, disk IO doesn’t appear to matter (I’m below the allotted IOPS for the instance), however geth is always using 100% of a single core during this process.

**Comment by SidHarder** [comment]
Thank you.  I started up a new Parity node and we'll see how it goes.

**Comment by cculianu** [comment]
> I am experiencing the same issue. My project is at a standstill until I can get a node synced. I have been trying now for a couple of weeks now.

This is sad.  Are the developers even trying to tune their stuff?

> Thank you.  I started up a new Parity node and we'll see how it goes.

Yeah -- the solution is to not even use geth.  Great job guys!

Please, please, please -- developers!  Figure out what's wrong fundamentally with your program's architecture and take steps to resolve it!  Too many of these issues out there.  The problem isn't THEM...

**Comment by holiman** [comment]
From the original report: importing state entries in a loop. Well, there is no loop. There are just a lot of state entries, upwards of 50 M. It takes a lot of time to download. There is an error if you _don't_ see it importing state entries. Be patient. Provide logs.

**Comment by cculianu** [comment]
>  Be patient. Provide logs.

Just honestly -- are you proud of the performance of this software and/or do you see nothing wrong?  Do you think it's the best it can possibly be? Or is there room for improvement?

**Comment by holiman** [comment]
@cculianu this is an issue tracker. You have provided zero useful input, only generate noise and accusations. Please find some other outlet for your feelings

**Comment by 10a7** [comment]
It appears to be due to I/O. To test, I spun up a VM using 20 cores of a Xeon v5 with 40GB RAM, and a SATA SSD, then also attempted the same VM on the same hardware with 4 cores and 8GB RAM. System resources were mostly blocked on I/O access in either case, so the sync issues don't appear to scale too much with any hardware other than I/O.

The VPS I am attempting to run geth on is a 4GB RAM, 2x Xeon E5-2650v4, with 60G SSD over NAS and 20G on the system drive.

I have noted there are supposed to be improvements in 1.8.0 (unstable) on how much it thrashes disk. This appears to accelerate syncing on my local (NVMe-backed) laptops, the SATA SSD lab box I spun up the VM on, and the VPS, however the VPS is still trailing about ~1000 blocks behind mainnet, with "imported new chain segment" happening every 8-30(!) seconds, importing a single block at a time. Geth uses anywhere between 50-150% CPU for itself all the time. It is worthwhile to try 1.8.0 and see if you also see any sync improvement.

**Comment by cculianu** [comment]
Hi 10a7,

Wow thanks for the useful tips. I'm going to try out 1.8.0 unstable and see if it differs.

Jeez -- that's some impressive hardware you are trying it on.  I don't have quite that impressive a setup.  I was hoping if I tried it on a better server instance or something it would work better.  Not hopeful in that regard.

But the 1.8.0 recommendation gives me something to try at least.  If I find any improvement I'll write back here.

**Comment by 10a7** [comment]
@cculianu It doesn't seem to matter how fast the processor is as long as your disk is crazy fast. Yes, geth still requires a lot of resources compared to parity but disk speed seems to be the only obvious way to stop falling out of sync.

**Comment by lnaie** [comment]
eth devs, look at the alarming number of issues related to gets/wallet syncing you have here on windows. wishing you to start building software that works, noobs! :)

**Comment by cculianu** [comment]
Update: no luck yet. 1.8.0 unstable same issues.  I am giving up. :(

I may try cpp-ethereum next -- maybe the fact that they used C++ forced them to think about performance more, dunno.

I realize Ethereum is a very heavy blockchain protocol -- but this really seems suspiciously like also a poor implementation to me.

Hope you guys figure out the performance issues. Keeping my fingers crossed...

**Comment by BeOleg** [comment]
Same issue here.
Any updates?

After a week:
eth_syncing output:
```
jsonrpc":"2.0","id":1,"result":{"currentBlock":"0x547225","highestBlock":"0x5472d4","knownStates":"0x34d8d58","pulledStates":"0x34d8d57","startingBlock":"0x4bdbb4"}}
```

eth_blockNumber output:
```
{"jsonrpc":"2.0","id":1,"result":"0x0"}
```

**Comment by ToasT-KIWI** [comment]
I am lagging by 100 blocks. I have 16gb RAM but it is only being utilised by 50%

**Comment by thomaswollburg** [comment]
We have a .10 node running fine with 8GB of RAM - set that up 3 weeks back or so - and a .11 node hanging at 99% for days. restarted the whole sync yesterday, got to 80% in no time but then it really slowed down and eth.blockNumber is stuck at 0 :(

**Comment by sg552** [comment]
try 24GB  RAM.

**Comment by thomaswollburg** [comment]
We switched to Parity. Synced after a couple of hours. All functionality that e need works now. If one really needs a SSD or 24GB of RAM then the system requirements should state that loud and clear. Adding more hardware to a system is not bugfixing. If anybody has a link to the actual system requirements feel free to answer with a link.

**Comment by kodmanyagha** [comment]
geth needs 24g ram but parity not needed. I think geth developers must deeply look to the code again. My server has 8g ram and running parity no problem. When I switch to geth it never synchronize. Lots of people has same problem.

**Comment by sg552** [comment]
Thanks to @thomaswollburg , I switched to Parity. 

Parity give us a clear message that : you must have SSD hard disk. I think this is the key.  (SSD is the key, but not the Memory ). In fact 2G 1CPU seems enough for  Parity , and SSD is about 200+GB .

**Comment by fjl** [comment]
The subject of this issue is "geth is too slow". There is no single change we can make to solve this issue. What we have done is to provide incremental performance improvements release after release. 
If you feel like you know how to implement this better, please help out with geth development :)
