### ISSUE TITLE
Massive difference between eth.gasPrice and ethgasstation

### ISSUE THREAD

**Issue by vogelito** [ethereum/go-ethereum#15825]
Hi there,

Why is there currently such a massive difference between what's reported in ethgasstation and what's being returned by eth.gasPrice?

```
> web3.fromWei(eth.gasPrice, "gwei")
103.51187
```

<img width="331" alt="screen shot 2018-01-06 at 11 17 23 am" src="https://user-images.githubusercontent.com/1325863/34642615-3895ebd2-f2d3-11e7-8bea-f9fbe39e9942.png">

**Comment by ligi** [comment]
Both use different methods of calculating this value. Please keep this issue tracker clean and for issues with go-ethereum only - for questions like this please use: https://ethereum.stackexchange.com - please close this issue - thanks!

**Comment by karalabe** [comment]
Geth looks at the median of the last N (don't remember the exact number) blocks. Could you perhaps say which block number/range you saw this at? It might happen that we're not averaging enough blocks and it's a bit more sensitive to immediate conditions than ideal.

**Comment by ligi** [comment]
Also see: https://github.com/ethereum/go-ethereum/pull/15828/files

**Comment by vogelito** [comment]
Thanks @ligi - that pull request seems very relevant. I hope it goes into the mainnet soon or the gas estimation algorithm in geth is changed. 

@karalabe - this is continuing to happen. I've now restarted geth with `--gpopercentile 20` and my gas estimates went from 120GWei to 12GWei.
