### ISSUE TITLE
knownStates and pulledStates start from 0 after restart geth in fast mode

### ISSUE THREAD

**Issue by gaoxiangxyz** [ethereum/go-ethereum#15829]
#### System information

Geth version: `1.7.3`
OS & Version: Windows, OSX

#### Expected behaviour
knownStates and pulledStates start from last states after restart.

#### Actual behaviour
knownStates and pulledStates start from 0 after restart. And all knownStates and pulledStates synced before lost.

#### Steps to reproduce the behaviour
start geth in fast mode and sync several days, eth.syncing is as below
```
eth.syncing
{
  currentBlock: 4862763,
  highestBlock: 4862866,
  knownStates: 57384051,
  pulledStates: 57382304,
  startingBlock: 4862489
}
```
after restart the eth.syning is as below
```
eth.syncing
{
  currentBlock: 48xxxxx,
  highestBlock: 48xxxxx,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 4862763
}
```

And another question is the disk usage is 166GB at around 4.0 million block number  in full mode, but it is only 47GB in fast mode when currentBlock is 4862763 and pulledStates is 57382304. Is it normal ?

**Comment by johnsneakers** [comment]
same problem,  when i restart knownStates=0 and then  slow incr by time.  currenctBlock stop incr

**Comment by veox** [comment]
Regarding disk usage: yes, "full archive" mode keeps all historic states, so it's normal for it to take more than a "fast" sync (that only keeps historic states for blocks _after_ the sync).

You may want to read https://github.com/ethereum/go-ethereum/issues/15649#issuecomment-357105157 for insights on the state counters during long syncs.
