### ISSUE TITLE
Geth stops its sync for hours

### ISSUE THREAD

**Issue by vogelito** [ethereum/go-ethereum#15824]
#### System information

Geth version:
```
Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```
OS & Version: `Ubuntu 16.04.3 LTS`

#### Expected behaviour

geth should remain in sync with the network.

#### Actual behaviour

My geth instance gets randomly stuck at certain blocks for hours and then randomly starts sync'ing again.

This is causing major problems with transaction propagation in the node.

At the time of writing geth hasn't restarted in over 8 days but we started seeing this problem less than 24 hours ago.

I have 6 hours worth of logs in `debug.verbosity(4)` where the node is alive and outputting stuff but not sync'ing. Since yesterday my node constantly gets in this state.

```
2018-01-06 06:35:19.021313500 INFO [01-06|06:35:19] Imported new chain segment               blocks=1  txs=226  mgas=7.999  elapsed=1.047s    mgasps=7.636   number=4862139 hash=f5fbc1…6ba255
.... Many hours pass of DEBUG output I will attach and then:
2018-01-06 15:54:51.202876500 INFO [01-06|15:54:51] Imported new chain segment               blocks=2  txs=1269 mgas=15.991 elapsed=4.896s    mgasps=3.266   number=4862140 hash=d6e0aa…938a41 ignore
d=3
```

When it's in this state I have run `net.peerCount` to see if it's a peering issue, but the node seems to consistently have 25 peers (the default max).

Also, this node is sitting in a pretty big CPU/RAM machine and neither CPU nor RAM seem to be the issue. It's all pretty quiet in that box (can provide graphs/specs if requested)

#### Steps to reproduce the behavior

Unfortunately this is happening pretty randomly

[ether.log](https://github.com/ethereum/go-ethereum/files/1609046/ether.log)

**Comment by vogelito** [comment]
Attaching CPU/load/RAM/Network traffic info over the last 2 weeks for completeness.

<img width="581" alt="screen shot 2018-01-06 at 11 02 24 am" src="https://user-images.githubusercontent.com/1325863/34642492-29a7557c-f2d1-11e7-8890-ea284e4b9c6b.png">
<img width="583" alt="screen shot 2018-01-06 at 11 02 12 am" src="https://user-images.githubusercontent.com/1325863/34642493-29ca5ec8-f2d1-11e7-91de-2435644a4c3e.png">
<img width="575" alt="screen shot 2018-01-06 at 11 02 05 am" src="https://user-images.githubusercontent.com/1325863/34642494-29db3bda-f2d1-11e7-82c9-e313b891a931.png">
<img width="578" alt="screen shot 2018-01-06 at 11 01 54 am" src="https://user-images.githubusercontent.com/1325863/34642495-29ef04e4-f2d1-11e7-8a2c-e6178f9a0645.png">

**Comment by holiman** [comment]
Thanks for the info! When it's in this state, behind but not obviously syncing, could you get a stack trace via the debug rpc api? Then we could easily see what the threads are doing...

**Comment by holiman** [comment]
I think it's debug_stacks

**Comment by holiman** [comment]
Really useful log btw, contain a lot of interesting data. We're analysing it

**Comment by vogelito** [comment]
Thanks @holiman - I'm glad the log is helpful.

I don't have the `debug` module enabled over HTTP so I will call `debug.stacks()` on the console and attach the output.

**Comment by HARSHVDARJI** [comment]
i have same proble... did you get solution ? @vogelito

**Comment by alicenew** [comment]
same here - can't get synced since last week - Geth/v1.7.3-stable/windows-amd64/go1.9.2. Node is running 24/7 and most of time (like 90% or more) about 50 blocks behind the chain. Occasionally, it gets synced but then stucks again.

**Comment by vogelito** [comment]
Please take a stack dump for the geth team.

My solution was to wait and be patient.

I haven’t seen geth get stuck again, but I had to restart my geth to resolve the gas miscalculation problem.

**Comment by vogelito** [comment]
Hi, this is happening right now. Attaching output of `debug.stacks()`

let me know if you want anything else
[2018.01.08_debug_stacks.log](https://github.com/ethereum/go-ethereum/files/1612469/2018.01.08_debug_stacks.log)

**Comment by vogelito** [comment]
Currently in my instance:
```
ether-mainnet:/home/ubuntu# cat /opt/ethereum-node/log/main/current | tai64nlocal | grep Imported | tail -1
2018-01-08 16:49:31.606171500 INFO [01-08|16:49:31] Imported new chain segment               blocks=1 txs=211  mgas=7.995  elapsed=575.833ms mgasps=13.885  number=4875410 hash=5917be…2d459c
ether-mainnet:/home/ubuntu# date
Mon Jan  8 17:46:47 UTC 2018
```

So roughly an hour without any blocks.

**Comment by vogelito** [comment]
Some more things that might be useful:

```javascript
> eth.syncing
{
  currentBlock: 4875410,
  highestBlock: 4875412,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 4875381
}
```

```javascript
> admin.peers
[{
    caps: ["eth/62", "eth/63"],
    id: "1b6734f27402c8db79062de5c1de3996787701703a020b7a8c5f446a23b6a6ec54cf9f0d776cf45ecedc2be79b3eee56d6ea15a367d7bd9eab554b7a13cad26f",
    name: "Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "162.239.101.246:51899"
    },
    protocols: {
      eth: {
        difficulty: 1.6704707859670111e+21,
        head: "0x8d300cf2ca2b598bab67d8d071606f2a7ce381d8c3169dff4a6fe90e8027aec2",
        version: 63
      }
    }
}, {
    caps: ["les/1"],
    id: "320ac8bc98c60bd141e719f133a63b2179693b3a8df4e2086f8dc6a9200adddd0cca07fb2c37e8aab677c34323ccc6dafb35f031b375fc0a8277e47b695be1a5",
    name: "Geth/v1.7.2-stable-1db4ecdc/linux-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "192.231.86.238:52132"
    },
    protocols: {
      les: {
        difficulty: 1.9954597710013252e+21,
        head: "431fe3ef05cb0399f900d1af11528e65010ef113e9272a536ab0c5025752c754",
        version: 1
      }
    }
}, {
    caps: ["les/1"],
    id: "3b274fc94efadbb14a5624e2f87c3321a4dae221cd5e874251cd0a300c31a8f960529d5ef2de26f5e8f4c595638b654792b3cbbf26a3b3f86ed8117b6480bb79",
    name: "Geth/v1.7.2-stable-1db4ecdc/darwin-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:59056",
      remoteAddress: "24.118.33.211:30303"
    },
    protocols: {
      les: {
        difficulty: 1.9970889341007154e+21,
        head: "673c50502df3ab1fc375da5864aec229119c9d75950ce30f5ec33d001a81e241",
        version: 1
      }
    }
}, {
    caps: ["eth/62", "eth/63", "par/1", "par/2", "pip/1"],
    id: "44d8b0a0821378735ad6a44989f8e0f05258439664cf9b530f5bddab178b2afe7d54aba5f936f2292e4c76c61f74c5bba9b8e2d3b938b8c55f27492e84bffffa",
    name: "Parity/v1.7.8-stable-d5fcf3b-20171025/x86_64-windows-msvc/rustc1.20.0",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "87.254.173.133:60448"
    },
    protocols: {
      eth: {
        difficulty: 1.7604713310366906e+21,
        head: "0x826e824409ccb3344d9af419c7c6d4dc583dc1cdac98203e25ad062117969643",
        version: 63
      }
    }
}, {
    caps: ["les/1"],
    id: "52cbda0f65d446db4dcbf11534be5d091557339c8fc45c3399071c27aa43ea184d519e8a52422dc44c86b24ad3a279cc644ee1d2716ec58957b38ff83b9f43a1",
    name: "Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "31.10.149.205:11425"
    },
    protocols: {
      les: {
        difficulty: 1.997046108244604e+21,
        head: "7c9b4989d8fc828aea35d08cc4926d1228febf616c533f0d4fcb4bff8f865934",
        version: 1
      }
    }
}, {
    caps: ["les/1"],
    id: "61e6312c8b3532c7c72496468c187b25753258ab2d26599127c130a5653173dc8c56b4a2ff9edcc624fde64418d2adf2bb8beeef9d9e274235c4804f3d7028a3",
    name: "Geth/v1.7.2-stable-1db4ecdc/freebsd-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "178.38.128.89:27348"
    },
    protocols: {
      les: {
        difficulty: 1.699655802068835e+21,
        head: "44a3e836bc398f76a837faf29e947f1b64176ef458c0460b9c010f8ad10c2a43",
        version: 1
      }
    }
}, {
    caps: ["eth/63"],
    id: "74d0df1c2c4b7afa35bc44e14d4b29c8564a7d017c868a7966db4604a26965aa63e57b7923af95e8337c5e4d4f1ee4d43432f0d24b654e91b6a0335f1f636307",
    name: "Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "162.224.216.232:61510"
    },
    protocols: {
      eth: {
        difficulty: 17179869184,
        head: "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
        version: 63
      }
    }
}, {
    caps: ["eth/62", "eth/63", "par/1", "par/2", "pip/1"],
    id: "7ee2d224d982c78c4157ab73aff2d97cf3f6e15ad92cf7f18e213e5dca03e260ab2d76132293e51c79e11535a65ed3a6be25d43d1843a93260d2088bcd6dfe02",
    name: "Parity/v1.7.8-stable-d5fcf3b-20171025/x86_64-windows-msvc/rustc1.20.0",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "98.226.155.145:12727"
    },
    protocols: {
      eth: {
        difficulty: 1.9642058593748446e+21,
        head: "0x20483030247554b21a673288f42dd4457d30fc1702fe7e24e42241d362636158",
        version: 63
      }
    }
}, {
    caps: ["les/1", "les/2"],
    id: "8cd6f5ba14c70b4a31f57cd9bafba28fed94368d60b526a87f31456f7194c25071bdbc177e8a533e51565724baf5e53c3b35b201155fe1a8349aa280eccabb85",
    name: "Geth/v1.7.3-stable-4bb3c89d/windows-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:56560",
      remoteAddress: "142.161.95.139:30303"
    },
    protocols: {
      les: {
        difficulty: 1.9915511548759108e+21,
        head: "889e7aeded8cd3067c153840403eeedbf9e0413358f2e241a72675ad6c2224a9",
        version: 2
      }
    }
}, {
    caps: ["les/1"],
    id: "9a23c9c72dcde32ea2812ab171781e1314ec402764cd0f2d870cc198d15eefe20384bc4ed54e07e92979f05c84d8aaa6ed3f046d60d898ec12df10343d2582bf",
    name: "Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "188.24.104.50:51173"
    },
    protocols: {
      les: {
        difficulty: 1.7930442736858704e+21,
        head: "2b3f0d09d58a46f21250b608d2b0308a83ab455f561fdbb579ea63ea748c98ea",
        version: 1
      }
    }
}, {
    caps: ["les/1", "les/2"],
    id: "abef24227db7f290388f007458b6b9a8035901dd5b6f1c357e6fbd18239d411e09734de1d09e97efe02eb59a51bf1ad551c90bf2786ba647f2eda03a9a8b0241",
    name: "Geth/v1.8.0-unstable-a139041d/windows-amd64/go1.9.2",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "67.168.179.191:16569"
    },
    protocols: {
      les: {
        difficulty: 1.992267500685382e+21,
        head: "4c3f3c0010cc12d700184c3637a98516f6e3ed9d3f631ebf12364fe9b498ff6f",
        version: 2
      }
    }
}, {
    caps: ["les/1", "les/2"],
    id: "b2143655660dd46686c3b23076ac1b83ea8b3a3700b6b5dc8cfa05673c2ee64b4191e7635f93f3a3b1970768ae5c0f8ce5688eca098994c9b667741afd627549",
    name: "Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9.2",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "31.192.159.48:33468"
    },
    protocols: {
      les: {
        difficulty: 1.992595585026646e+21,
        head: "bb0ed7b18516cd174c61f39eb9d87fd50f5180eb7ad143a19b798c5b638641f7",
        version: 2
      }
    }
}, {
    caps: ["eth/62", "eth/63"],
    id: "b2ea1c88c5d6eb996e69a2ed1d7a11199eb7563ea97eadce07d196c54a15675418467bd0b7539ef5a427e0be93fc9cadb16bc26e058e3da2ad7b090674ccfa08",
    name: "Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "185.19.22.69:21128"
    },
    protocols: {
      eth: {
        difficulty: 1.9700601481344485e+21,
        head: "0xb13e4de88c0cf9895b4d880c69284c4c9133e7335bcd0352799767436b2f6401",
        version: 63
      }
    }
}, {
    caps: ["eth/62", "eth/63"],
    id: "c54335c58477feb922da2cfbd062766f5e3e01c850642fcbd480ed07445721eeb47ba6c6d81e76a6135ef28856022f5c21e771d1fa046af0f3a8a85ffb71ea97",
    name: "Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "47.92.78.173:58472"
    },
    protocols: {
      eth: {
        difficulty: 1.9978870531299114e+21,
        head: "0x6ed3444ae718e5f6190491f4b18a77a5ba7e12ba547dd726a2df2f888dcd59a9",
        version: 63
      }
    }
}, {
    caps: ["les/1", "les/2"],
    id: "c56a90786ee0645ca8e6c34ec531d72385bb8b9efd4199c6dbd86ba302484842db65c644b71c182df8ce409efbc98f5749a0abee508969944afa560ed7db95ee",
    name: "Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "140.119.164.158:42574"
    },
    protocols: {
      les: {
        difficulty: 1.9904742085343762e+21,
        head: "371b69b1ec6b67ee4d48d64269d50ec77d384ea209654c4f8f42b704fb6a575c",
        version: 2
      }
    }
}, {
    caps: ["les/1", "les/2"],
    id: "d0c21a4faeaf1e18907816dde7094f1abb1f81a9f5420713c3d3b4e50dfeb49de8a119656c1ec8541455f1eb56c032beb290707fddfebffd8d078e79f8f87f17",
    name: "Geth/v1.7.3-stable-4bb3c89d/windows-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "67.170.54.201:55709"
    },
    protocols: {
      les: {
        difficulty: 1.9912114844499745e+21,
        head: "94851e55691c8709d1318637e611d893b83bca21e9a6fb90f35d69a95b4df77d",
        version: 2
      }
    }
}, {
    caps: ["les/1"],
    id: "e4049456f84da00cfe6f0c1a8a93b14e1aa5a0f2bf1e12ef845755e8bee7f5def83853e7350c36fa1e7c0e6854e492eb1553a52164dde00d6dea4417ee775e61",
    name: "Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:34948",
      remoteAddress: "81.233.239.107:30303"
    },
    protocols: {
      les: {
        difficulty: 1.9909177847835722e+21,
        head: "d063992c5c99afd52f7a847c07d9547c07bda35f602db45a07e183619d3759b3",
        version: 1
      }
    }
}, {
    caps: ["les/1", "les/2"],
    id: "e6ecd3cb562b9eb02eb4d826a7bed2223a921cea82cc6b405c403f5f62e5306d0775fc2c241d10ce97ade394c857aa913fa93c49f206fd97312ff5f7fc46a8c1",
    name: "Geth/v1.7.3-stable-4bb3c89d/windows-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "136.63.99.27:55817"
    },
    protocols: {
      les: {
        difficulty: 1.990866327061041e+21,
        head: "fe1ec99174be79337e450986c70a4ddf2c454af8b323f2564158babde047ff9e",
        version: 2
      }
    }
}, {
    caps: ["eth/62", "eth/63", "par/1", "par/2", "pip/1"],
    id: "e8c37dfee2315446a06f11bc45caa7833ab97df9e93942a716efb05ec80be59422a33505b1d4f123deca28febdb95749dcc648f6ff4983a41beed9b43385b8e7",
    name: "Parity/v1.8.3-beta-b49c44a-20171114/x86_64-windows-msvc/rustc1.20.0",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "95.56.14.180:57894"
    },
    protocols: {
      eth: {
        difficulty: 73614652824579090000,
        head: "0x652ec1a74b38020706784793ca01db757fbeaa14d2a898daff59b17984d3f074",
        version: 63
      }
    }
}, {
    caps: ["les/1"],
    id: "e8e555c56d2ce78ad6f7a70d2f71a31b5426276919eff2a4efa1c131d89fec95f8b4ebd025a21534c112eec731fa7e3bcec9eaba2939a22993b674e4df93b1f3",
    name: "Geth/v1.7.2-stable-1db4ecdc/linux-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "24.26.250.52:46650"
    },
    protocols: {
      les: {
        difficulty: 1.9941398758194364e+21,
        head: "f3c3b5c74ad25b6b34efa876c83425573f3b0443365045d359c7d4b04c99d32c",
        version: 1
      }
    }
}, {
    caps: ["les/1", "les/2"],
    id: "ea687c73f4c05a0c7e2548397fa09a9ef80a91cb5e3617fe603a8f9712f0dd46515f3fd8bf50542770f740e00b958fd721f8ad2aa13a069db6fbb0c3625e061a",
    name: "Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "192.241.140.22:46754"
    },
    protocols: {
      les: {
        difficulty: 1.9911519249824295e+21,
        head: "c8c6fac9baa6b0703ed30d1381d62abff898bfefaadd7b941b0542cfc4611ff4",
        version: 2
      }
    }
}, {
    caps: ["les/1"],
    id: "f470d7798820d3e79f46b136f093e776d90ff376d9944d1f35a28a482aac714b2d62609a267270b49adc70515d695f6f9633d02463c93b20027577de4fb4d283",
    name: "Geth/v1.7.2-stable-1db4ecdc/darwin-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "92.108.225.241:64161"
    },
    protocols: {
      les: {
        difficulty: 1.996369168754866e+21,
        head: "1504907b44de396fb7d09b3c00570e45b2b4e7a5e7232fe79a733f23725b8d84",
        version: 1
      }
    }
}, {
    caps: ["eth/62", "eth/63"],
    id: "f834509b38e29901f31ae5c1e19f4c519f9cff3fc7bfdf3a1889bcb6be730b9245a7bdd638721a08e292a7f4983bcb81db388bd43a2ba069f3b1c820c72cb089",
    name: "Geth/v1.7.3-stable-4bb3c89d/darwin-amd64/go1.9.2",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "104.254.92.62:58482"
    },
    protocols: {
      eth: {
        difficulty: 699401933406697300000,
        head: "0x4ac7189ae1e47cdba876f7742d61dc563fb603f65ab48e175898e1475c5d77ea",
        version: 63
      }
    }
}, {
    caps: ["les/1", "les/2"],
    id: "f87a2175e9226ea77ef475ff48cdb50148ebaa9070805814161958680604df1043d6de96f6acc994302ea78010559a37a37ae65d0fa65eeadf42f97d97ea10b6",
    name: "Geth/v1.7.3-stable/linux-amd64/go1.9.2",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "195.113.232.60:35784"
    },
    protocols: {
      les: {
        difficulty: 1.9963417310597643e+21,
        head: "4e9d90f176ac886d1b4020be8486e8259e3c019f442a530780929b3b5aaafa4d",
        version: 2
      }
    }
}, {
    caps: ["les/1"],
    id: "ff7c13a888a84c607a9a30e968c08a10732112e5edbf4bae5e2eb6177109c3f818c9450646826fab0fd89bdf1e0238240edb9be2d7b8866f33f285770e141701",
    name: "Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9",
    network: {
      localAddress: "172.31.44.153:30303",
      remoteAddress: "65.128.78.66:60831"
    },
    protocols: {
      les: {
        difficulty: 1.9964043642493524e+21,
        head: "947df8af715b099140b28b17c6a072a802557ec382f4f5b154d842ebda45b2bc",
        version: 1
      }
    }
}]
```

**Comment by vogelito** [comment]
And I start geth with:
```
/home/ubuntu/geth/current/geth --rpc --rpcapi "debug,personal,eth,web3" --targetgaslimit 1000000 --cache 1024 --lightserv 20 --gpopercentile 30
```

**Comment by vogelito** [comment]
My node is now caught up. However, for some reason it's broadcasting the transactions in the `eth.pendingTransactions` queue at a very slow rate of about 1 tx/block

**Comment by alicenew** [comment]
for me it was more or less resolved by doubling cache size, node managed to get synced and stays in sync most of time. Sometimes it stuck for awhile with "dropping peer err=timeout" or "err=retrieved hash chain is invalid" (but those I consider to be peer issues or isn't it?) then it manage to get synced pretty quickly.
Memory and disk consumption is above 80% most of the time.

**Comment by vogelito** [comment]
Thanks @alicenew - what's your cache size set to now?

**Comment by axelay** [comment]
Geth just hung for about 5 minutes - here is the debug.stacks() output: [geth.log](https://github.com/ethereum/go-ethereum/files/1618749/geth.log)

**Comment by vogelito** [comment]
Hi,

This is becoming a pretty big issue for us. Is there any more info we can provide to help you debug? We would really appreciate your help with it.

Once the node gets into this mode it sort of refuses to broadcast transactions and I have to rebroadcast them all with a script.

**Comment by holiman** [comment]
It's on my priority list hopefully for tomorrow. Been sick for the entire week. Those stacks should help a lot

**Comment by holiman** [comment]
It's on my priority list hopefully for tomorrow. Been sick for the entire week. Those stacks should help a lot

**Comment by holiman** [comment]
It's on my priority list hopefully for tomorrow. Been sick for the entire week. Those stacks should help a lot

**Comment by holiman** [comment]
It's on my priority list hopefully for tomorrow. Been sick for the entire week. Those stacks should help a lot

**Comment by vogelito** [comment]
Thank you so much @holiman - really appreciate it and hope you get better soon.

**Comment by axelay** [comment]
I am adding one more log - currently stuck at block 4892652
[geth1.log](https://github.com/ethereum/go-ethereum/files/1624215/geth1.log)

Holiman Kenobi, you're our only hope!

**Comment by macgherl57** [comment]
Running like this: geth --maxpeers 60 --lightserv 50 --ligthpeers 35 --cache 2048
Sort of same problem here; tried to mitigate it in several ways, but IMHO it's mostly a net problem...
My question though: why does it download some latest blocks twice?
Look here for block number=489316: downloaded twice with different hashes. Is this normal behavior?
Looking forward to knowing if this behavior of randomly stalling the sync can be eliminated some how.
Thanks all!

Jan 12 02:33:32 gethservice[14605]: INFO [01-12|02:33:32] Imported new chain segment               blocks=1 txs=218  mgas=7.988  elapsed=1.568s          mgasps=5.093  number=4893614 hash=0a4fbf…6031d8
Jan 12 02:34:40  gethservice[14605]: INFO [01-12|02:34:40] Imported new chain segment               blocks=1 txs=305  mgas=7.990  elapsed=2.442s          mgasps=3.271  number=4893615 hash=64a176…02162e
Jan 12 02:34:55  gethservice[14605]: INFO [01-12|02:34:55] Imported new chain segment               blocks=1 txs=317  mgas=7.977  elapsed=2.846s          mgasps=2.802  number=4893616 hash=005ae6…afe8bd
Jan 12 02:35:04  gethservice[14605]: INFO [01-12|02:35:04] Imported new chain segment               blocks=1 txs=354  mgas=7.987  elapsed=2.888s          mgasps=2.765  number=4893617 hash=410ed9…8415e0
Jan 12 02:35:29  gethservice[14605]: INFO [01-12|02:35:29] Imported new chain segment               blocks=1 txs=324  mgas=7.912  elapsed=2.572s          mgasps=3.075  number=4893616 hash=ea7e1d…33b68f
Jan 12 02:35:36  gethservice[14605]: INFO [01-12|02:35:36] Imported new chain segment               blocks=1 txs=297  mgas=7.988  elapsed=2.396s          mgasps=3.334  number=4893618 hash=f853e2…e95206
Jan 12 02:35:48  gethservice[14605]: INFO [01-12|02:35:48] Imported new chain segment               blocks=1 txs=352  mgas=7.992  elapsed=3.180s          mgasps=2.513  number=4893619 hash=64bc90…30448b

**Comment by holiman** [comment]
I've done a first analysis of (some of ) the raw data, but not yet looked into possible causes: https://gist.github.com/holiman/5ec5d518c0ebe602872e37bd5775f0ef

**Comment by holiman** [comment]
As an experiment, could you try _not_ running `--lightserv`, and see if that makes any difference?

**Comment by lmars** [comment]
This sounds very much like the issue I reported in https://github.com/ethereum/go-ethereum/issues/15689 (i.e. sometimes I have only light peers and cannot download any blocks).

**Comment by holiman** [comment]
Oh indeed! Setting lightpeers is at the cost of full peers. But @vogelito is not setting that particular flag, though...(?)

**Comment by holiman** [comment]
Iirc, it defaults to 20, so running geth like @vogelito does effectively halves the allowed number of full peers

**Comment by lmars** [comment]
@holiman yes, the default `--lightpeers` value is 20 (see [here](https://github.com/ethereum/go-ethereum/blob/master/cmd/utils/flags.go#L179-L183)).

**Comment by vogelito** [comment]
remove the `lightserve` option. Just let me know if that’s what you want me to do.

@axelay are you running geth with that flag on?

**Comment by axelay** [comment]
No we are not

**Comment by holiman** [comment]
Yes, @vogelito, please remove that and see if it works better

**Comment by vogelito** [comment]
I'm sorry, I didn't do something very scientific here... I changed my startup parameters from:
```
/home/ubuntu/geth/current/geth --rpc --rpcapi "debug,personal,eth,web3" --targetgaslimit 1000000 --cache 1024 --lightserv 20 --gpopercentile 30
```

to
```
/home/ubuntu/geth/current/geth --rpc --rpcapi "debug,personal,eth,web3" --targetgaslimit 1000000 --cache 2048 --gpopercentile 30 --maxpeers 75
```

I've noticed two things:
1. outbound traffic went from 0.077MiB/s to 6.987MiB/s
2. Sync is excruciatingly slow and my node is really falling behind

I saw my node getting stuck after sync'ing block 4897181 so I took another `debug.stacks()` (attached [2018.01.12_geth.log](https://github.com/ethereum/go-ethereum/files/1626937/2018.01.12_geth.log)). Here's the log for timing reference (~10 mins between blocks):
```
2018-01-12 17:31:46.449453500 INFO [01-12|17:31:46] Imported new chain segment               blocks=1 txs=260  mgas=7.997  elapsed=981.924ms mgasps=8.144  number=4897181 hash=5f7af8…0d45a2
2018-01-12 17:42:32.184639500 INFO [01-12|17:42:32] Imported new chain segment               blocks=2 txs=645  mgas=15.992 elapsed=10.875s   mgasps=1.470  number=4897183 hash=ed48cd…0de87d
```

**Comment by vogelito** [comment]
Attaching network bandwidth graphs.

Last hour:
<img width="534" alt="screen shot 2018-01-12 at 11 47 33 am" src="https://user-images.githubusercontent.com/1325863/34888107-810ec9c8-f78e-11e7-8b55-fd5b3312c95b.png">

Last 4 hours:
<img width="533" alt="screen shot 2018-01-12 at 11 48 44 am" src="https://user-images.githubusercontent.com/1325863/34888128-957d042e-f78e-11e7-94d6-3c9701b0caef.png">

JSONRPC responses are also incredibly slow.

**Comment by vogelito** [comment]
I have gone back to `--maxpeers 25` and added a list of previously known peers and everything is back to normal (geth sync'ing quickly, caught up, and RPC response times back to normal).

Bandwidth is still a bit higher but not enough to cause other issues:
<img width="537" alt="screen shot 2018-01-12 at 12 03 43 pm" src="https://user-images.githubusercontent.com/1325863/34888653-b5502b1c-f790-11e7-9646-c1926024e372.png">

**Comment by holiman** [comment]
Good to hear. 75 peers may be pushing it :) if it keeps working stable, please close this ticket (otherwise I'll do it in a few days)

**Comment by vogelito** [comment]
I'm now tracking the difference between geth's block height and parity's block height across two nodes and added realtime alerting if block heights differ by more than 15 blocks. Attaching graphs.

Also attaching updated bandwidth graphs. Outbound bandwidth is still much higher than before the last restart, but the node's mainly in sync.

<img width="593" alt="screen shot 2018-01-13 at 2 44 24 pm" src="https://user-images.githubusercontent.com/1325863/34909919-b1b9e2f0-f870-11e7-94ce-90711d542ab2.png">

<img width="588" alt="screen shot 2018-01-13 at 2 47 02 pm" src="https://user-images.githubusercontent.com/1325863/34909918-b1a510fa-f870-11e7-86bc-164958327c0d.png">

**Comment by axelay** [comment]
Just a note to let you know I have dropped my max connections from 50 to 25 and it seems to have helped a little. Will carry on monitoring but hopefully it's now a bit more stable.

**Comment by holiman** [comment]
@vogelito, I took at look at the list of peers you pasted above. If I remove the `les`-only peers you listed, these ones were the only ones which could potentially supply you with actual data, and they were at these block numbers: 

```
4691934, (old)
4747669, (Dec-17)
0, (still syncing)
4858352, (Jan 05)
4861361, (Jan 06)
4875656, (Jan 08)
2427426, (old)
4163249, (old)
```

So you really only had _one_ useful peer, at block `4875656, (Jan 08)`, but it's hard to say if it was at head, or if it also was trailing a few hours behind. So it's not really a wonder that you were starved for blocks.

**Comment by vogelito** [comment]
I thought I was doing the community a service by running a light server but never expected i’d get into that situation... thanks for looking @holiman. So far no issues since Wednesday. Let’s see what’s in store this week!

**Comment by Adesso** [comment]
Great debug info @vogelito My problem seem to have gotten better after lowering my staggering 85 peer goal... I'am now humbly sitting and waiting for my node to sync with 12

**Comment by vogelito** [comment]
I can report that I have not seen this problem since i decreased maxpeers and stopped being a light server
