### ISSUE TITLE
abigen->go code doesn't include imports

### ISSUE THREAD

**Issue by RaghavSood** [ethereum/go-ethereum#15827]
#### System information

Geth version: `1.7.3`
OS & Version: OSX
Commit hash : from ppa

#### Expected behaviour

`abigen --abi token.abi --pkg main --type Token --out token.go` (from [this](https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts) tutorial) produces go code that's ready to be used

#### Actual behaviour

The code is correct, but is missing the following imports for a basic erc20 binding:

```
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/common"
```
#### Steps to reproduce the behaviour

Try to follow the tutorial

**Comment by karalabe** [comment]
`abigen` uses the local Go project structure (GOPATH, go-ethereum) to derive the imports automatically. If your environment isn't set up for Go development and/or the go-ethereum repository isn't inside it, we can't automatically resolve the imports (there are other imports too needed); and Go fails compilation for extra imports, so we can't just add everything we think may be useful in there.

Internally `abigen` uses `goimports` to resolve the imports.
