### ISSUE TITLE
Transaction pool DoS attack possible?

### ISSUE THREAD

**Issue by MitchK** [ethereum/go-ethereum#15820]
I was looking through the Ethereum Go code of the transaction pool and looking at the pool limits.

https://github.com/ethereum/go-ethereum/blob/9619a610248e9630968ba1d9be8e214b645c9c55/core/tx_pool.go#L135-L138

AccountQueue is usually set to 64, GlobalQueue is set to 1024. That means that from one account, there can only be 64 non-executable transactions at the same time in the pool. The 65th will be discarded. Is that correct?

Is the behavior the same with GlobalQueue? Meaning, that if the pool size is already 1024, the 1025th will be discarded as well?

What if I create (more than) 1024 / 64 = 16 accounts and spam the Ethereum network(s) with 64 non-executable transactions each. Won't this block other users for a period of time and make their transactions not be confirmed, or even worse, discarded?

**Comment by footloosejava** [comment]
How are you going to make sure that your transactions are not executable? Won't you still have to pay the gas?

**Comment by 7flash** [comment]
I guess newcoming transactions would just bubble up not-executed transactions from slots and and take their place.
