### ISSUE TITLE
Could not decrypt auth message

### ISSUE THREAD

**Issue by mkalinin** [ethereum/go-ethereum#1582]
I'm trying to connect to `go` peer built from `release/1.0.0` branch and facing with next messages in its log
```
I0803 13:29:44.296875   20685 server.go:571] Accepted conn 95.189.187.138:50277
I0803 13:29:44.350515   20685 server.go:595] inbound conn 95.189.187.138:50277 faild enc handshake: could not decrypt auth message (ecies: invalid message)
```

I also found same messages related to other connections. It doesn't look like a rare case.
The problem is that everything worked well with this peer a couple of days ago and nothing was changed on my side since that time. I tried to reset `NodeId` values on both sides but it happens again and again.

Do you have any ideas about these messages? Should I look for the reason on my side?

**Comment by fjl** [comment]
There are two likely explanations for this message:
    * The RLPx handshake was encrypted with the wrong recipient key.
This will definitely happen when the node key is changed because other nodes in the discovery network
still have the old key in their tables.

**Comment by romanman** [comment]
@fjl : Felix, we had very strange behavior there 
like once for a while the same ids/keys wont 
work on go, it is happening like 1/20 connections
totally unpredictable, I am thinking on some race
condition but not sure it is on our side

**Comment by mkalinin** [comment]
Guys, more info for you
```
I0804 03:47:05.611642   25910 server.go:595] inbound conn 83.134.173.146:54645 faild enc handshake: could not decrypt auth message (ecies: invalid message)
I0804 03:49:45.736612   25910 server.go:595] inbound conn 178.19.221.38:53396 faild enc handshake: could not decrypt auth message (ecies: invalid message)
I0804 03:54:28.689087   25910 server.go:595] inbound conn 88.212.206.70:34513 faild enc handshake: could not decrypt auth message (ecies: invalid message)
```
These are some other peers faced with the same error. If you take a look at timestamps you will see that this case is not so rare.
