### ISSUE TITLE
If I know a node's rpcaddr and port, does that mean I'm controlling this node?

### ISSUE THREAD

**Issue by dream960727** [ethereum/go-ethereum#15831]
--rpccorsdomain seems to be used only when web3.js is used by browsers, with no effect on tools like `geth attach`, `josnrpc `and `web3.py`.
Can I do some settings, only accept the specified ip `web3` or `geth attach` command?

**Comment by karalabe** [comment]
It's not advisable to have an open RPC port. Whilst we tried to limit the API namespaces callable by default, users may change that, or some attacker might find some funky API call that might not cause damage in itself, but may be an annoyance (e.g. trace transactions, hitting the CPU).

Our recommendation is to use RPC to talk to the node via your own programs only (or trusted programs) and if you want to expose public functionality over the internet, you should put your own APIs in front which you can control for authentication and rate limiting.

**Comment by dream960727** [comment]
If I set `rpcaddr `to `127.0.0.1`, I can solve the problem. But if I had to use it remotely, using` geth attach` or `web3.py`, how to forbid others to use the same method to access my node? Does Ethereum have such a function, or do I have to write a program myself?

**Comment by lmars** [comment]
@dream960727 have you considered using an SSH tunnel to your remote node? For example:

```
ssh -L 8545:127.0.0.1:8545 user@example.com
```

This would forward your local port 8545 to the local 8545 port on the remote node, without exposing it externally.
