### ISSUE TITLE
geth crash: out of memory

### ISSUE THREAD

**Issue by johnsneakers** [ethereum/go-ethereum#15839]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version:Version: 1.8.0-unstable
OS & Version: CentOs
Commit hash : (if `develop`)

#### Backtrace

````
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x100555a, 0x16)
        /go/src/runtime/panic.go:605 +0x95
runtime.sysMap(0xc5e4d40000, 0x20000000, 0xcbc133aba0463100, 0x1cf3d38)
        /go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x1cda4a0, 0x20000000, 0x7fb1ac13e010)
        /go/src/runtime/malloc.go:470 +0xd7
runtime.(*mheap).grow(0x1cda4a0, 0x10000, 0x0)
        /go/src/runtime/mheap.go:887 +0x60
runtime.(*mheap).allocSpanLocked(0x1cda4a0, 0x10000, 0x1cf3d48, 0xc446e76780)
        /go/src/runtime/mheap.go:800 +0x334
runtime.(*mheap).alloc_m(0x1cda4a0, 0x10000, 0x7fb1d67f0101, 0x7fb1d67fbdd8)
        /go/src/runtime/mheap.go:666 +0x118
runtime.(*mheap).alloc.func1()
        /go/src/runtime/mheap.go:733 +0x4d
runtime.systemstack(0x7fb1d67fbdd0)
        /go/src/runtime/asm_amd64.s:360 +0xab
runtime.(*mheap).alloc(0x1cda4a0, 0x10000, 0xc447010101, 0x7fb1ac4d9720)
        /go/src/runtime/mheap.go:732 +0xa1
runtime.largeAlloc(0x20000000, 0x7fb1d67f0101, 0x46d28e)
        /go/src/runtime/malloc.go:827 +0x98
runtime.mallocgc.func1()
        /go/src/runtime/malloc.go:722 +0x46
runtime.systemstack(0xc42001f300)
        /go/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
        /go/src/runtime/proc.go:1135

goroutine 881949 [running]:
runtime.systemstack_switch()

````

**Comment by johnsneakers** [comment]
total        used        free      shared  buff/cache   available
Mem:           7.8G        6.6G         58M        3.3M        1.2G        1.1G
Swap:          255M         26M        229M

memory info

**Comment by GoodMirek** [comment]
@johnsneakers I cannot find what command line you used to run `geth`. With 8GB RAM you should not set `--cache` to more than 2048. Furthermore, there is a known memory leak bug #15428 causing Out Of Memory issues during initial fast sync. Workaround is just to restart `geth`.

**Comment by dbblackdiamond** [comment]
I am having the same issue with Geth 1.8.9, where, if I let Geth run for a few days, it will crash with an "out of memory" error. My Ubutun Xenial server is configured with 8GB of RAM and 32GB of swap. The command line to start Geth is the following: `go-ethereum/build/bin/geth --nodiscover --cache=2048 --rpc --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "db,eth,net,web3,personal,debug,txpool" js ./ethereum/mine_pending.js `

i used to run Geth 1.6.x with the same command and never had an issue with it running out of memory. I have actually tripled the swap space on this server to accommodate the "out of memory" issue and it is still there.

**Comment by sivachaitanya** [comment]
How did you solved this guys ?

**Comment by GoodMirek** [comment]
With a wrapper script, which restarts geth upon failure. In another case by
switching to parity.
-- 

Mirek Svoboda

**Comment by holiman** [comment]
` --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "db,eth,net,web3,personal,debug,txpool"` -- recipe for failure. Remote hosts on the internet will discover this node, and attempt password bruteforce, which will lead to OOM issues. 
I don't know if that was the case with the original reporter, @johnsneakers , please reopen if that was not the case.
