### ISSUE TITLE
Ethereum blockchains not synchronized on 3 differents computers

### ISSUE THREAD

**Issue by Acacia-Jeff** [ethereum/go-ethereum#15848]
Hello,

I have an issue with Geth, I want to compile and deploy a smart contract, and in order to do that, I have added ether to my wallet.
We can verify the transaction here : https://etherscan.io/tx/0x0b3247c2c1d1f26411486ad3ee4fd47e2a8b71de56af0b0fe6759586dd18f6b5
where we can see the transaction is in the 4 679 731th block

Here, we can verify the amount of ether in the wallet : https://etherscan.io/address/0x704e2b488674afa69069a165d3c8a80a27c30d6f which is 0,075 ether.

Then,

I have built a virtual machine with an vanilla Ubuntu, install geth (v1.7.0-stable-6c6c7b2a) and try to sync from the 10-29-2017 to the 12-20-2017.
I launch geth with : geth console

In my research, I have found two commands which can determine the progress of the sync :

var sync = web3.eth.syncing;sync;
give : 
{
  currentBlock: 1144835,
  highestBlock: 1720228,
  knownStates: 33418,
  pulledStates: 25707,
  startingBlock: 1144067
}

eth.getBlock("latest").number
give :
0

I used the following command to check how many ether an account have :
web3.fromWei(eth.getBalance("0x704e2b488674aFa69069A165D3C8a80A27C30D6f"), "ether")
give : 
0

So in two month, I'm not sync, and my geth don't know how many ether I have on my account.
I have apparently sync to the 1 144 835th block, and the transaction is in the 4 679 731th block, so I think it's normal, but in two months ?
Do I have to wait 8 months to start using Geth ? It's not acceptable.

So I have built a second virtual machine on 12-29-2017 with the same vanilla Ubuntu, install geth (1.7.3-stable-4bb3c89d) and try to sync.
The difference with the first : I launch with the fast syncmode : geth --fast --cache=1024 console.

Now, the commands
var sync = web3.eth.syncing;sync;
give :
{
  currentBlock: 3872910,
  highestBlock: 4884396,
  knownStates: 3180,
  pulledStates: 2379,
  startingBlock: 3865878
}

eth.getBlock("latest").number
give :
0

and
web3.fromWei(eth.getBalance("0x704e2b488674aFa69069A165D3C8a80A27C30D6f"), "ether")
give : 
0

So in 12 days, I have sync 4x more, but in the 4 last days, I have the message :
WARN [01-10|01:01:40] Rolled back headers                      count=2048 header=3894230->3892182 fast=3872910->3872910 block=0->0
every time and it doesn't sync more.

So I tried a third time on my personal computer, a windows 8.1, install geth (1.7.3-stable-4bb3c89d) and try to sync from the 01-07-2018
with command line : geth.exe --syncmode "full" console

Now, the commands

var sync = web3.eth.syncing;sync;
give :
{
  currentBlock: 4881711,
  highestBlock: 4884507,
  knownStates: 34771,
  pulledStates: 26470,
  startingBlock: 4880214
}

eth.getBlock("latest").number
give :
0

and
web3.fromWei(eth.getBalance("0x704e2b488674aFa69069A165D3C8a80A27C30D6f"), "ether")
give : 
0

So I have reached the targeted block (4 679 731) in one day, but geth always states that I have 0 ether in my account ?

My question is : how can I sync so I can start to work with SmartContract ?

When I search on the web, the only anwser I can read is to wait.
I don't want to read this anwser anymore, or tell me a real method that can show me the real progress.

**Comment by pratgen** [comment]
Same problem here.
sync is not happening for few days.
This is a real issue with me.
here is the output of the 
geth   --testnet --verbosity=6 console 2>> geth.log

Welcome to the Geth JavaScript console!

instance: Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9
coinbase: 0xcb2806ef4eeb21d5ca1ac63f3d2b90aec98c7506
at block: 2353297 (Wed, 10 Jan 2018 16:44:23 IST)
 datadir: /home/pratik/.ethereum/testnet
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

[gethtrace.txt](https://github.com/ethereum/go-ethereum/files/1618958/gethtrace.txt)

**Comment by RichHorrocks** [comment]
Hi there. This is likely an issue with either your hardware (e.g. if you're using an HDD), or with the flags you used with Geth (e.g. if you haven't set the `--cache` size or used `--syncmode fast`).

This isn't really an issue that needs to be tracked on the official bug/issue tracker. It's more of a technical question. I'd recommend joining [Ethereum's Stack Exchange](https://ethereum.stackexchange.com/) site, which has various questions/answers on how to speed up the syncing process. (e.g. "[Help with very slow mist sync](https://ethereum.stackexchange.com/questions/603/help-with-very-slow-mist-sync)")

**Comment by cculianu** [comment]
It's an issue with geth.  Good software works.  Bad software requires various workarounds.

**Comment by pratgen** [comment]
@RichHorrocks 
It is tough to believe that something that was working perfectly well on same hardware and software suddenly stops syncing.
Even you may see the log I attached, there is no information about any kind of error.
Please look into the log and kindly suggest some troubleshooting.
I have already search many StackOverflow posts and did lot of R&D, including but not limited to check local time, different options of running geth.

Look forward to your kind guidance based on the log I have attached.
It mostly looks like a bug.

**Comment by lnaie** [comment]
it's a god damn abomination software. 5 days of trying to sync and still 97% done showing zero balance. cannot do any operation on that wallet.

**Comment by Zumili** [comment]
Same problem here, trying to use geth on a fresh ubuntu 16.04 system and it is still synching even if the last block is reachend. How big does the database gets after a full fast sync?
This is the command I used:
./geth --syncmode fast --cache 1024

**Comment by Black2018NEW** [comment]
Hello, had the same problem.
Secure your keys (keystore folder and json)
Uninstall Wallet and Geth

Download Geth 1.7.3
Start geth 1.7.3

Download ethereum Wallet 0.9.1.
Start ethereum Wallet 0.9.1.

Wait until everything is synchronized. This time it should work

Have fun.
If it helped, spend to:
0x5563620df19a37fa34dcb17597032666429b1e7e

**Comment by Acacia-Jeff** [comment]
Hello,

Glad to see I am not the only one who have that problem.

@Black2018NEW I don't think that can change anything, as you can see, I already have the 1.7.3 version.

Anyway, I know we can copy the all blockchain in the "Chaindata" folder, so does anyone have it so I can copy it in my folder ?
We can give a FTP access for it in private message, thanks in advance, that could really help me.

**Comment by Black2018NEW** [comment]
Hello, when I had all the data, I moved my etherum to a portal. And then deleted all blockchain so that my hard disk has room again.
I also had the problem with the 200 blocks. Then I used the 0.9.1 instead of Wallet 0.9.3.
The block then went down to 64 and eventually even on sync.

I forgot to mention that I deleted the database, the Chaindata.
I even deleted the folder. This was then set up in Wallet Folder 0.9.1.

**Comment by jsdavis28** [comment]
I am having the same problem, as well. I have two machines that were running Geth without any problems and now none of them have been syncing for the past 2-3 weeks. I've completely un-installed and reinstalled Geth and it simply fails to sync. This is not a hardware or configuration problem, as nothing was changed. I've also installed Geth on an Ubuntu VPS and it has the same problem, as well.

**Comment by ciputraaja** [comment]
http://vy.tc/egClY97

Pada tanggal 30 Jan 2018 01.40, "J Scott Davis" <notifications@github.com>
menulis:

**Comment by fjl** [comment]
Sorry, closing this because the report isn't actionable. There is no single bug in geth that causes sync failures. We are aware that sync may sometimes fail for networking reasons. Numerous issues related to sync were fixed in 2018.
