### ISSUE TITLE
From:     [invalid sender: invalid sig]     what error ,

### ISSUE THREAD

**Issue by hqxluoyang** [ethereum/go-ethereum#15846]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Please open an issue with your actual question.

**Comment by hqxluoyang** [comment]
thanks you
