### ISSUE TITLE
Transaction Fee without Transaction

### ISSUE THREAD

**Issue by 0HaanSolo0** [ethereum/go-ethereum#15852]
Hi there,

please do not laugh about me because of my issue. I am new at the euthereum univers and may have a noob issue which is actually just because I do not understand how the system works.

Today I wanted to buy me a cryptokittie (yep sorry, I know cause of guys like me the network is slow). Because I wanted to buy the cat, I downloaded Metamask and put some Ether in it.

My transaction to buy some kittes were not realized at the end, but still I had to pay a fee.
(I put the information out of ethereumscan at the end of this mail)

My question now is: is it normal that I have to pay a fee (gas) even if the transaction never was done? For what am I paying? Who gets the money I paid?

What does the error code "out of gas" means?

 May all of this questions sound silly for you, but you would raelly help me if you could me explain why this happend... 
Everyone startet to learn at one point ;)

0x92c0e9ee27f9a3541480fd21290727d143bd4485bc75311d32db9947b2cb68a6 | 4886613 | 1 hr 14 mins ago | 0x532d9907702385bfc78b26950a530a744939e572 | OUT | CryptoKittiesSalesAuction | 0.005 Ether | 0.0015
-- | -- | -- | -- | -- | -- | -- | --
0xca107025c45c18bb535f0acdbd6fd6e2fb4e88222699b04a8ca7e62941564467 | 4886611 | 1 hr 15 mins ago | 0x532d9907702385bfc78b26950a530a744939e572 | OUT | CryptoKittiesSalesAuction | 0.004991612654392 Ether | 0.00119
0x11e288182a29ee5349c7a5a2ea899878558c013660bf2e1049102734376e7c27 | 4886604 | 1 hr 17 mins ago | 0x532d9907702385bfc78b26950a530a744939e572 | OUT | CryptoKittiesSalesAuction | 0.004716441028148 Ether | 0.0025
0xe57082bd88b11c79b217c5b1380174c5cd1d1b37ed313819605ef4c4f1604fed | 4886602 | 1 hr 17 mins ago | 0x532d9907702385bfc78b26950a530a744939e572 | OUT | CryptoKittiesSalesAuction | 0.00471688622537 Ether | 0.0025

**Comment by ligi** [comment]
Hey, it would be great if we could keep this issue tracker clean and only for issues. I suggest asking this question on https://ethereum.stackexchange.com and close this issue

**Comment by karalabe** [comment]
@0HaanSolo0 In Ethereum, every transaction has a gas allowance set by the user. This is the amount of computation you are willing to pay for to the miner. The miners get your transaction and start processing it.

If your allowance was enough to cover the costs of your requested operation (e.g. buy a crypto kitty), the transaction is successful and the modified state is stored in the blockchain. If however your transaction requires more resources than you allotted (your gas allowance), there's a problem.

The miner doesn't know in advance how much resources your transaction will consume in the end, so it starts executing it, taking your word that whatever you specified is enough. If it's not, there's no telling how much more would be needed (e.g. imagine an infinite loop never terminating), so the transaction cannot be executed and must be reverted. However, the miner nonetheless did already expend the computational resources for running your transaction until it ran out of allowance, so someone needs to cover those costs.

This is also a protection against spam. If miners would discard transactions that run out of gas without making the user pay for it, malicious users could spam the miners by simply submitting heavy transactions that can never succeed (e.g. infinite loop), causing miners to waste resources without the users ever being penalized. 

So, if your transaction ran out of gas, it means whatever operation you called needed more computational resources than you allowed it to use. Any effect the transaction might have had was rolled back, but you were charged nonetheless for "wasting" the miner's time.
