### ISSUE TITLE
eh_estimate gas returns 0 for normal transactions

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#1585]
When sending a query to `eth_estimate` gas, it returns `0` for a normal transaction:
```
{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x343c98e2b6e49bc0fed722c2a269f3814ddd1533","to":"0x990ccf8a0de58091c028d6ff76bb235ee67c1c39", "value":"0x3e8"}],"id":13080}
```

Response
```
{
	"id": 13080,
	"jsonrpc": "2.0",
	"result": "0x0"
}
```

**Comment by obscuren** [comment]
This is a duplicate. Issue has been addressed on develop. Please check 1.0.1 milestone, it's already included for the schedules release.
