### ISSUE TITLE
systemctl problem

### ISSUE THREAD

**Issue by freshonline** [ethereum/go-ethereum#15851]
Work:
[Unit]
Description=Geth Ethereum node
After=network.target

[Service]
Type=simple
EnvironmentFile=-/etc/default/geth
ExecStart=/usr/bin/geth $GETH_ENABLE_RPC $GETH_CACHE $GETH_MAXPEERS
User=ethereumuser
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
========================
Don't work:
 [Unit]
Description=Geth Ethereum node
After=network.target

[Service]
Type=simple
EnvironmentFile=-/etc/default/geth
ExecStart=/usr/bin/geth
User=ethereumuser
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
=======================
Don't work:
 [Unit]
Description=Geth Ethereum node
After=network.target

[Service]
Type=simple
EnvironmentFile=-/etc/default/geth
ExecStart=/usr/bin/geth --syncmode "fast"
User=ethereumuser
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
==========================
Why? I need service with '--syncmode "fast"'

**Comment by lmars** [comment]
@freshonline it would be very useful if you could clarify what you mean when you say it doesn't work (i.e. does `systemctl start` return an error of some sort, are there errors in `journalctl` etc.).

**Comment by GoodMirek** [comment]
> I need service with '--syncmode "fast"'

I doubt you really need the `--syncmode "fast"` switch, as it is default for quite a long time already. If you insist, try instead:
`ExecStart=/usr/bin/geth "--syncmode fast"`

More info [here](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines).
