### ISSUE TITLE
geth showing zero balance

### ISSUE THREAD

**Issue by jorgesc** [ethereum/go-ethereum#15855]
#### System information

Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.2
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go

#### Expected behaviour

Geth shows my current balance as shown here:
https://etherscan.io/address/0xffe7d35bdbf9d0098600d04bcc5d258c25f8a4ea

#### Actual behaviour

Geth shows zero instead

#### Steps to reproduce the behaviour

`$geth --cache 4096 console`

Wait a few hours until sync

> eth.syncing
  false

> eth.coinbase
0xffe7d35bdbf9d0098600d04bcc5d258c25f8a4ea

> eth.getBalance(eth.coinbase)
0

#### Backtrace

````
[backtrace]
````

**Comment by RichHorrocks** [comment]
Hi there. Ideally ask technical questions on https://ethereum.stackexchange.com - it's important to keep issue trackers clear and for real issues only. (Similar questions to yours have been asked in the past on Stack Exchange, so it will likely already be answered there.)

**Comment by rritoch** [comment]
This question has been asked many times, yet still no answer because its a BUG! I'm tempted to fix the bug myself and use it to take over etherum's network! Thousands of people have this bug, including me but I can see the transaction!

Short answer, switch to light mode, light mode works, full mode is BROKEN!

**Comment by holiman** [comment]
Could you also check what blocknumber your node is at? eth.getBlock("latest")

**Comment by holiman** [comment]
(since this can either be a bug that it reports as not syncing erroneously, or that there's some other error)

**Comment by rritoch** [comment]
Block number is being listed as zero but that isn't the bug because I already have the transaction in cache. When I eth.getBlock(#) of a deposit transaction into my account the transaction shows.  So while the syncing may be broken, that isn't the cause of this!
