### ISSUE TITLE
CPU miner doesn't start in "light" mode

### ISSUE THREAD

**Issue by julien-regnault** [ethereum/go-ethereum#15860]
Hi,

Can't start CPU miner in light mode using this command:
./geth --mine --syncmode "light" --cache 1024 

Here is the log:

> INFO [01-11|19:28:48] Starting peer-to-peer node               instance=Geth/v1.8.0-unstable-83d16574/linux-amd64/go1.7.4
> INFO [01-11|19:28:48] Allocated cache and file handles         database=/root/.ethereum/geth/lightchaindata cache=1024 handles=1024
> INFO [01-11|19:28:48] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Engine: ethash}"
> INFO [01-11|19:28:48] Disk storage enabled for ethash caches   dir=/root/.ethereum/geth/ethash count=3
> INFO [01-11|19:28:48] Disk storage enabled for ethash DAGs     dir=/root/.ethash               count=2
> INFO [01-11|19:28:48] Added trusted checkpoint                 chain name="ETH mainnet"
> INFO [01-11|19:28:48] Loaded most recent local header          number=4893062 hash=7017f3…4483af td=2033194604220009882200
> INFO [01-11|19:28:48] Starting P2P networking
> INFO [01-11|19:28:50] UDP listener up                          self=enode://8e8fc781116940df5a710d065de695cde5778954019d95d5bba13fa423fb11392bfee091b49cc8f0a9b8e0cfe9b913c3a0c3216ef4555ef6031d3da1fdde396e@[::]:30303
> WARN [01-11|19:28:50] Light client mode is an experimental feature
> Fatal: ethereum service not running: unknown service

#### System information

Geth version: `1.8.0-unstable`
OS & Version: Linux Debian

#### Expected behaviour
I should be able to start mining in light syncmade (using lightchaindata db)

#### Actual behaviour
Crash : Fatal: ethereum service not running: unknown service

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
A light client cannot mine. It does not have the necessary state data locally on top of which to run the transactions. That being said, geth should most certainly not crash, rather report a proper error message for this.

**Comment by julien-regnault** [comment]
thanks, that makes sense. But I agree, a message saying that mining is incompatible with the light syncmode option would be great.
