### ISSUE TITLE
Node synchronization cannot be completed.

### ISSUE THREAD

**Issue by aaron315** [ethereum/go-ethereum#15875]
Hi there,

Node synchronization cannot be completed.

#### System information

Geth version: `1.7.3-stable-4bb3c89d`
OS & Version: Linux
Commit hash : (if `develop`)

i run geth use this command:
 ./geth --networkid 3 --rpc --rpcaddr 10.3.11.100   --cache 1024 --rpcapi db,eth,net,web3,personal

i use curl check sync status:
curl http://10.3.11.100:8545 -X    POST       --header 'content-type: application/json' --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
output 
"params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":{"currentBlock":"0x4a719d","highestBlock":"0x4a71fa","knownStates":"0x1","pulledStates":"0x0","startingBlock":"0x4a719d"}}

currentBlock is 0x4a719d It's been two days，The synchronization of nodes cannot be completed.
So how do we solve this?

THX.

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
Whu do you use networkid 3?? That's not mainnet

**Comment by aaron315** [comment]
Networkid 3 is for  testnet

**Comment by holiman** [comment]
What's the hash of e.g. block 2 in your chain?

**Comment by aaron315** [comment]
`web3.eth.getBlock(2)`
`AttributeDict({'difficulty': 17163096064,
 'extraData': '0x476574682f76312e302e302d30636463373634372f6c696e75782f676f312e34',
 'gasLimit': 5000,
 'gasUsed': 0,
 'hash': '0xb495a1d7e6663152ae92708da4843337b958146015a2802f4193a410044698c9',
 'logsBloom': '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
 'miner': '0xdd2f1e6e498202e86d8f5442af596580a4f03c2c',
 'mixHash': '0x2f0790c5aa31ab94195e1f6443d645af5b75c46c04fbf9911711198a0ce8fdda',
 'nonce': '0xb853fa261a86aa9e',
 'number': 2,
 'parentHash': '0x88e96d4537bea4d9c05d12549907b32561d3bf31f45aae734cdc119f13406cb6',
 'receiptsRoot': '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
 'sha3Uncles': '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
 'size': 544,
 'stateRoot': '0x4943d941637411107494da9ec8bc04359d731bfd08b72b4d0edcbd4cd2ecb341',
 'timestamp': 1438270017,
 'totalDifficulty': 51514445824,
 'transactions': [],
 'transactionsRoot': '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
 'uncles': []})`

**Comment by Magicking** [comment]
In order to use the Ropsten Testnet, you have to use the --testnet flag, --rinkeby pour Rinkeby.

**Comment by aaron315** [comment]
@Magicking thx
use --testnet is ok
