### ISSUE TITLE
could not decrypt key with given passphrase

### ISSUE THREAD

**Issue by xuefengyang** [ethereum/go-ethereum#15876]
Hi there,

I Call personal_signAndSendTransaction method by RPC.
return follow error:
“could not decrypt key with given passphrase”.
I want to know 
The two parameters used by the function passphrase must be the same one?
person.newAccount ()
personal_sendTransaction

#### System information
Geth version: `1.7.3`
OS & Version:Linux

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Well, yes. When creating a new account, you encrypt your private key with a password. In order to access that account, you need to decrypt it with the original password you use to encrypt it with.

**Comment by chrc** [comment]
Same issue with: instance=Geth/v1.8.22-stable-7fa3509e/linux-amd64/go1.10.4

`Failed account unlock attempt            address=0x679fcd4F9d01601B15479977826F9763B71FFFFF err="could not decrypt key with given passphrase"`

**Comment by holiman** [comment]
@chrc You need to provide more context. 

* Are you saying that you are unable to unlock with the password?
* Are you saying that that line of text appears in your logs? 

If it's the latter, someone is trying to bruteforce unlock your account, to steal your funds. Don't expose RPC on the internet, and definitely not with the `personal` API namespace enabled.

**Comment by mech12** [comment]
> Same issue with: instance=Geth/v1.8.22-stable-7fa3509e/linux-amd64/go1.10.4
> 
> `Failed account unlock attempt address=0x679fcd4F9d01601B15479977826F9763B71FFFFF err="could not decrypt key with given passphrase"`

I also faced this error.

**Comment by 401825317** [comment]
创世块的初始密码是什么呢？我给忘记了

**Comment by wbt** [comment]
I encountered a [similar error](https://github.com/ethereum/go-ethereum/issues/19905) when trying to unlock an account using the command-line flag for doing so on a mining/sealing node, in Geth 1.9.1.  This cross-link is provided for reference.
