### ISSUE TITLE
chaindata is 450Gb

### ISSUE THREAD

**Issue by 97zgxgw** [ethereum/go-ethereum#15872]
1.7.3
Ubunta.
Is it normal, when chaindata is 450Gb ?

**Comment by veox** [comment]
Are you syncing in "full" mode? Then yes, that's pretty normal.

**Comment by 97zgxgw** [comment]
If i use in not "full" node it is secure ?

**Comment by tedder** [comment]
I was using `--syncmode fast` and it filled the drive.

**Comment by tedder** [comment]
Related to #15797.

**Comment by veox** [comment]
@tedder `geth` switches to `--syncmode full` after completing a `--syncmode fast` run.

There's a log message to that effect on a previously-synced node that's being started again with `--syncmode fast`.

**Comment by veox** [comment]
Suggest closing issue as "works as expected".

**Comment by 42force** [comment]
with this chaindata, can you use seagate external harddrive?
