### ISSUE TITLE
Log missing in geth v1.7.0 but coming in v1.7.2

### ISSUE THREAD

**Issue by anks003** [ethereum/go-ethereum#15871]
Hi,

I am sending the same payload to two different geth nodes one running 1.7.2 and other 1.7.0. The payload is 
```json
{"jsonrpc":"2.0","id":2,"method":"eth_getLogs","params":[{"fromBlock":"0x254A31","toBlock":"0x254A6E","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",null,null],"address":"0x583cbbb8a8443b38abcc0c956bece47340ea1367"}]}
```
#### Actual behaviour and steps to reproduce

Version `1.7.2` The log is missing, I am testing on **ropsten infura** [https://ropsten.infura.io](https://ropsten.infura.io/)
Version `1.7.0` Running a private node, I can see the log as well as we can check from the log API of [ropsten etherscan](https://ropsten.etherscan.io) with the ENDPOINT 

`https://ropsten.etherscan.io/api?module=logs&action=getLogs
&fromBlock=2443825
&toBlock=2443886
&address=0x583cbbb8a8443b38abcc0c956bece47340ea1367
&topic0=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef`

Is it happening due to difference in versions? But from my understanding the logs should be consistent. What can be the cause of log not being present on one node and one more observation I made is that i am able to see the transaction receipt.

#### System information

Geth version: `1.7.2` and `1.7.0`
OS & Version: Linux
Commit hash : (if `develop`)

**Comment by karalabe** [comment]
Please use 1.7.3. There was a log filtering bug in 1.7.2.

**Comment by anks003** [comment]
Hi @karalabe If you have some time can you please explain what was the bug ? What was the behavior due to which logs couldn't be retrieved/stored ? Thanks.

**Comment by anks003** [comment]
Are you referring to this ? https://github.com/ethereum/go-ethereum/pull/15489

**Comment by karalabe** [comment]
Yes

**Comment by anks003** [comment]
@karalabe thanks a lot ! Can you please shed some light on this https://github.com/ethereum/go-ethereum/issues/15866 ?
