### ISSUE TITLE
Geth is horribly slow -- You guys need to reevaluate some stuff.

### ISSUE THREAD

**Issue by cculianu** [ethereum/go-ethereum#15874]
Hi guys,

I don't know who maintains geth but I'm just saying you guys ought to be ashamed of yourselves.

I'm been developing software for 20+ years.  Never before have I seen a project this bad that is also the default flagship client for a 100+ billion dollar enterprise.  

It's the default official full node client for the #2 cryptocurrency.

It also sucks really bad.

It stalls randomly, eats up GB of memory as if they were tic-tacs, and is an all-around abomination.

What the fuck are you guys doing?  Fix your shit.  Performance tune.  Figure out why it can deadlock and fix it!

I shouldn't have to restart it every couple of hours on a chain sync because it's stalled.  Only to see it happily continue downloading blocks after a restart.

I shouldn't see it zip up to 8GB memory usage for no reason, only to drop back down to 900MB, then to zip up to 2.5 GB for hours.

What the fuck is going on?

If I were you I'd be ashamed of myself.

FIX YOUR CRAP!

**Comment by holiman** [comment]
This is not a bug report, just a rant. If you're a sw developer, you should know the importance of good bug reports.

**Comment by cculianu** [comment]
At this point -- all one can say is your performance problems are a bug.

**Comment by iamalwaysuncomfortable** [comment]
Although his diction is, erm, uncouth, cculianu tells some truths. A billion+ dollars do you have, but geth doth run like a dirty rag. Maybe some people should you hire, to create better documentation, log messages, and probe behavior undesired.

**Comment by ardeearam** [comment]
Unfortunately, this still holds true. Yes, it is an open source project, and yes software developers can contribute. But damn, geth needs attention like a baby.

If this is the best we can come up with for the 2nd most capitalized cryptocurrency, then the future is a bit bleak.

**Comment by iamalwaysuncomfortable** [comment]
Better it has gotten, but some things are still a little rotten. If you would like specific advice, I can type up something detailed and nice.

**Comment by josephholsten** [comment]
@iamalwaysuncomfortable Yes, please.

**Comment by plakat3** [comment]
I don't know what is better, but I have a feeling that all this is handled by a slow kids.
It is a shame that after so many complaints no one from developers of this s t even bothers atleast to post a comment. I start to think that all this is a big scam.
Here is why:
Geth can never get synchronized with the blockchain . All that it throws at some point is 
" Database compacting, degraded performance"
And it stays there forever. 

Sorry to say such a thing but I have to: this crap sucks!@

**Comment by drewstaylor** [comment]
@cculiano I experienced similar problems with geth which is why I switched to parity
