### ISSUE TITLE
invalid pipe address

### ISSUE THREAD

**Issue by enancial** [ethereum/go-ethereum#15877]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Not much context to go with. Please open a new ticket with enough einfo for us to understand and repro your problem.
