### ISSUE TITLE
Cannot sync - Ubuntu 16.04

### ISSUE THREAD

**Issue by kaziqta** [ethereum/go-ethereum#15882]
Linode  - 4CPU + 8GB ram

./geth --fast --cache=2048

WARN [01-13|23:43:24] Stalling state sync, dropping peer       peer=0bdf36a06ef498f7
WARN [01-13|23:43:24] Stalling state sync, dropping peer       peer=a421d7bda43252c1
WARN [01-13|23:43:26] Stalling state sync, dropping peer       peer=d13bd7a1c5210d5e
WARN [01-13|23:43:27] Stalling state sync, dropping peer       peer=dc5ad195e2f13c07
WARN [01-13|23:43:27] Stalling state sync, dropping peer       peer=0de61627415c4ddf
WARN [01-13|23:43:27] Stalling state sync, dropping peer       peer=a8616e4170f5a8b7
WARN [01-13|23:43:27] Stalling state sync, dropping peer       peer=7cdc7f102f6df80f
WARN [01-13|23:43:29] Stalling state sync, dropping peer       peer=a84058868db1f064
WARN [01-13|23:43:29] Stalling state sync, dropping peer       peer=a39d59c03aeed686
WARN [01-13|23:43:29] Stalling state sync, dropping peer       peer=94ff93f9532e127b
WARN [01-13|23:43:29] Stalling state sync, dropping peer       peer=1de5c613cdb44058
WARN [01-13|23:43:30] Stalling state sync, dropping peer       peer=d22946e7aa6b99e7
WARN [01-13|23:43:31] Stalling state sync, dropping peer       peer=11238274e0f72c17
WARN [01-13|23:43:31] Stalling state sync, dropping peer       peer=9e291b5e216338d7
WARN [01-13|23:43:31] Stalling state sync, dropping peer       peer=440e937c4bc14a13
WARN [01-13|23:43:32] Stalling state sync, dropping peer       peer=aca971919837e4a4
WARN [01-13|23:43:32] Stalling state sync, dropping peer       peer=5130203b4b7d8a43
WARN [01-13|23:43:32] Stalling state sync, dropping peer       peer=9f4cf690c72c5078
WARN [01-13|23:43:35] Stalling state sync, dropping peer       peer=c23ba59d21046de6
WARN [01-13|23:43:36] Stalling state sync, dropping peer       peer=6d2c6eb9ef5ae884
WARN [01-13|23:43:36] Stalling state sync, dropping peer       peer=a39d59c03aeed686
WARN [01-13|23:43:40] Stalling state sync, dropping peer       peer=5c9dab99888454d5
WARN [01-13|23:43:42] Stalling state sync, dropping peer       peer=aca971919837e4a4
WARN [01-13|23:43:43] Stalling state sync, dropping peer       peer=fe125cc099a544a2
WARN [01-13|23:43:46] Stalling state sync, dropping peer       peer=58b4af8bad9ec7bb
WARN [01-13|23:43:46] Stalling state sync, dropping peer       peer=46a42b87114744ba

**Comment by Adesso** [comment]
Root Server - 8CPU + 32GB RAM using _geth 1.7.3-stable_

`geth  --cache=2048 --maxpeers 84 --rpc --rpccorsdomain localhost console 2>&1 | tee /tmp/eth.log
`

> WARN [01-28|22:54:14] Rolled back headers                      count=2048 header=4701756->4699708 fast=4678406->4678406 block=0->0
> WARN [01-28|22:54:17] Synchronisation failed, retrying         err="receipt download canceled (requested)"
> WARN [01-28|22:55:02] Stalling state sync, dropping peer       peer=9cdb352e1333b541
> WARN [01-28|22:55:19] Stalling state sync, dropping peer       peer=2b5e9e506c7d17f9
> WARN [01-28|22:56:40] Stalling state sync, dropping peer       peer=7ae3e5f4c0e4b88c
> WARN [01-28|22:57:05] Stalling state sync, dropping peer       peer=7defc821ca9e393c
> WARN [01-28|22:57:26] Stalling state sync, dropping peer       peer=0a67932271c16842
> WARN [01-28|22:57:27] Stalling state sync, dropping peer       peer=0a3558c45e175111
> WARN [01-28|22:57:40] Stalling state sync, dropping peer       peer=31cff2ffc8427aa2
> WARN [01-28|22:57:58] Stalling state sync, dropping peer       peer=7ac775b5569e39ff
> WARN [01-28|22:57:59] Stalling state sync, dropping peer       peer=7e9473986fc87c17
> WARN [01-28|22:58:41] Stalling state sync, dropping peer       peer=404880ff1b007673

**Comment by Adesso** [comment]
Turns out it is too many peers that make a mess.
#15824
