### ISSUE TITLE
how to preload js with other libs.

### ISSUE THREAD

**Issue by leochan007** [ethereum/go-ethereum#15888]
i need to load abi from a local json file.
-----------

var fs=require("fs");
var path=require("path");

var build=fs.readFileSync(path.join(process.cwd(), "../build/contracts/Demo.json"), "utf-8");

----------
Error: Cannot find module 'fs'
    at s (web3.js:1:160)
    at s (web3.js:1:122

**Comment by lmars** [comment]
Have you tried using the `--preload` flag to `geth attach`?
