### ISSUE TITLE
sync failed

### ISSUE THREAD

**Issue by wcw84** [ethereum/go-ethereum#15898]
Hi all,

#### System information
$ geth version
Geth
Version: 1.7.2-stable
Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9

OS & Version: Ubuntu 14, 4cores and 8G memory

Recently my geth failed to synchronize frequently, below is a fragment of the log:

> WARN [01-16|11:25:08] Head headers broke chain ordering        peer=52c78ead0f5fc602 index=0 requested=4915718 received=4915914
WARN [01-16|11:25:08] Synchronisation failed, dropping peer    peer=52c78ead0f5fc602 err="retrieved hash chain is invalid"
WARN [01-16|11:26:26] Synchronisation failed, retrying         err="block body download canceled (requested)"
WARN [01-16|11:26:50] Head headers broke chain ordering        peer=0002af38d08fdff0 index=0 requested=4915718 received=4915922
WARN [01-16|11:26:50] Synchronisation failed, dropping peer    peer=0002af38d08fdff0 err="retrieved hash chain is invalid"
WARN [01-16|11:27:35] Synchronisation failed, retrying         err="block body download canceled (requested)"
WARN [01-16|11:28:14] Synchronisation failed, retrying         err="block download canceled (requested)"
INFO [01-16|11:28:51] Imported new chain segment               blocks=2 txs=374  mgas=15.937 elapsed=9.589s    mgasps=1.662 number=4915912 hash=60ded5…d9eb27
INFO [01-16|11:28:55] Imported new chain segment               blocks=1 txs=276  mgas=7.956  elapsed=4.210s    mgasps=1.890 number=4915913 hash=6a5a3c…91678d
INFO [01-16|11:29:04] Imported new chain segment               blocks=2 txs=573  mgas=15.966 elapsed=8.858s    mgasps=1.802 number=4915915 hash=5d9e42…bda27b ignored=1
INFO [01-16|11:29:15] Imported new chain segment               blocks=4 txs=1079 mgas=31.953 elapsed=10.956s   mgasps=2.916 number=4915919 hash=eb3b4f…96015c
INFO [01-16|11:29:24] Imported new chain segment               blocks=3 txs=721  mgas=23.964 elapsed=9.047s    mgasps=2.649 number=4915922 hash=2e1646…3a892f
INFO [01-16|11:29:33] Imported new chain segment               blocks=2 txs=589  mgas=15.980 elapsed=8.644s    mgasps=1.849 number=4915924 hash=7c7f04…9e4b41
INFO [01-16|11:29:42] Imported new chain segment               blocks=3 txs=514  mgas=23.965 elapsed=9.489s    mgasps=2.525 number=4915927 hash=1aa7fe…c15514
INFO [01-16|11:29:53] Imported new chain segment               blocks=4 txs=652  mgas=31.963 elapsed=10.925s   mgasps=2.925 number=4915931 hash=90f080…884450
INFO [01-16|11:29:57] Imported new chain segment               blocks=1 txs=266  mgas=8.003  elapsed=3.927s    mgasps=2.038 number=4915932 hash=e19db9…d63631
INFO [01-16|11:29:59] Imported new chain segment               blocks=1 txs=247  mgas=8.000  elapsed=1.448s    mgasps=5.524 number=4915931 hash=8f6277…55a36e
WARN [01-16|11:34:38] Synchronisation failed, retrying         err="block body download canceled (requested)"
WARN [01-16|11:36:16] Synchronisation failed, retrying         err="block header download canceled (requested)"
WARN [01-16|11:36:22] Synchronisation failed, retrying         err="block download canceled (requested)"

And if i restart the geth, it will run smoothly for a while(half an hour or even longer), but then the same problem happen.
It seems that the network is stuck?  This bring me a lot of problem. Because my transactions are sent to this geth, and if this geth can't update to lately, the transactions will failed
Any help will be appreciated.

**Comment by Black2018NEW** [comment]
Hello, had the same problem.
Secure your keys (keystore folder and json)
Uninstall Wallet and Geth

Download Geth 1.7.3
Start geth 1.7.3

Download ethereum Wallet 0.9.1.
Start ethereum Wallet 0.9.1.

Wait until everything is synchronized. This time it should work

Have fun.
If it helped, spend to:
0x5563620df19a37fa34dcb17597032666429b1e7e

**Comment by hieunguyena6** [comment]
**_kkkkkkkkkkkk_**
