### ISSUE TITLE
eth.getBalance with "pending" flag not working correctly.

### ISSUE THREAD

**Issue by vogelito** [ethereum/go-ethereum#15892]
#### System information

Geth version:
```
Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```
OS & Version: Linux

#### Expected behaviour
`eth.getBalance(addressHexString, "pending")` is supposed to return the balance of `addressHexString` for the currently mined block (including pending transactions).

#### Actual behaviour
`eth.getBalance(addressHexString, "pending")` is not taking into account pending transactions in my node.

#### Steps to reproduce the behaviour
This is in my node, right now:
```
> eth.getBalance("0x3f5b715c30073534c52a1c9bab37cbcbbbb29f1e", "latest")
13387970000000000000
> eth.getBalance("0x3f5b715c30073534c52a1c9bab37cbcbbbb29f1e", "pending")
13387970000000000000
> tx = eth.getTransaction("0x695371618dd9bf1a44fe903f29601a019f58b7052962483851986b8a51d056b1")
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  blockNumber: null,
  from: "0x3f5b715c30073534c52a1c9bab37cbcbbbb29f1e",
  gas: 21000,
  gasPrice: 5000000000,
  hash: "0x695371618dd9bf1a44fe903f29601a019f58b7052962483851986b8a51d056b1",
  input: "0x",
  nonce: 0,
  r: "0xe07bbe912926f396d3c4d3d930010ce20c4c48ecd7ccd3a5f77de5d7ce96ea91",
  s: "0x537b5595a136bcde6a9e9a6d61da13e51762901225aea7a4f2dd8d04b8d8a83",
  to: "0x29d5527caa78f1946a409fa6acaf14a0a4a0274b",
  transactionIndex: 0,
  v: "0x25",
  value: 13387865000000000000
}
> tx.gas*tx.gasPrice+tx.value*1
13387970000000000000
```

I would've expected `eth.getBalance("0x3f5b715c30073534c52a1c9bab37cbcbbbb29f1e", "pending")` to return 0.

**Comment by holiman** [comment]
> I would've expected eth.getBalance("0x3f5b715c30073534c52a1c9bab37cbcbbbb29f1e", "pending") to return 0.

Not sure that's a valid expectation. You would like `pending` to mean "the state which would occur if we executed every single transaction that is currently pending". I think it means "the pending-state", which is a block cobbled together containing _some_ of the pending transactions, according to tx-inclusion logic. If you were mining, that's the block you would be mining right now. 

So it does not include all pending transactions, only a subset. @karalabe correct me if I'm wrong.

**Comment by vogelito** [comment]
Thanks @holiman - if that's the case, then I completely misunderstood the documentation.

Calling with the `pending` flag on my node is extremely slow, so I expected it to be doing some computation.

**Comment by vogelito** [comment]
Looking through our codebase and this would explain many of our problems!

Looking to make changes now.

**Comment by tinchou** [comment]
I was looking for some details about the `pending` flag and ended up here. @holiman sorry if this is not the right place to ask, but how does a **non-miner** node respond to requests with the `pending` flag?

**Comment by vogelito** [comment]
Closing this issue.
