### ISSUE TITLE
Question: Parsing event data.

### ISSUE THREAD

**Issue by m1ome** [ethereum/go-ethereum#15895]
Hello, 

I have a couple of questions.
Let's say i have smart-contract with event labeled `Transfer`. 

With definition
```
[{"name": "test", "type": "event", "inputs":[{"indexed": true,"name": "_from","type": "address"},{"indexed": true,"name": "_to","type": "address"},{"indexed": false,"name": "_value","type": "uint256"}]}]
```

How can i parse all this stuff into `go structure`? 
My testing script:

```go
func fetchLogs(client *ethclient.Client, fromBlock, toBlock *big.Int) {
	ensABI, err := abi.JSON(strings.NewReader(ENSTEmporaryHashRegistryABI))
	if err != nil {
		panic(err)
	}

	eventTopicId := ensABI.Events["Transfer"].Id()
	q := ethereum.FilterQuery{
		FromBlock: fromBlock,
		ToBlock:   toBlock,
		Addresses: []common.Address{ENSContractAddress},
		Topics:    [][]common.Hash{[]common.Hash{eventTopicId}},
	}

	ctx, _ := context.WithTimeout(context.Background(), rpcTimeout)
	vmlogs, err := client.FilterLogs(ctx, q)
	if err != nil {
		panic(err)
	}

	for _, log := range vmlogs {
		// Here i should do binding data to structure, but how?
	}
}
```

**Comment by Magicking** [comment]
You can use Unpack from https://godoc.org/github.com/ethereum/go-ethereum/accounts/abi#Arguments.Unpack
```
// It should look something like that for this example
	type TransferEvt struct {
		From	common.Address
		To		common.Address
		Value	*bit.Int
	}
// [...]
	for _, log := range vmlogs {
		var e TransferEvt
		ensABI.Unpack(&e, "Transfer", log.Data)
		// Do stuff with e
	}
}
```
See: https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/unpack_test.go
Soon: https://github.com/ethereum/go-ethereum/pull/15832

**Comment by jdkanani** [comment]
@Magicking It only parses `log.Data` not topics. Shouldn't abi should expose a method which does both?

**Comment by patelvasu** [comment]
(**abi: cannot marshal in to go type: length insufficient 96 require 128**)  I have found this error after call  ABI.Unpack()

**Comment by RodrigoBuendia** [comment]
Je, je

El 28 dic. 2018 5:55, "vasudev" <notifications@github.com> escribió:

(*abi: cannot marshal in to go type: length insufficient 96 require 128*) I
have found this error after call ABI.Unpack()

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/go-ethereum/issues/15895#issuecomment-450289911>,
or mute the thread

**Comment by adamschmideg** [comment]
The original question has been answered. If you think, there's still a problem to be solved, please open a new issue.
