### ISSUE TITLE
Ether Balance Not Showing after syncing transaction block

### ISSUE THREAD

**Issue by tedkimzikto** [ethereum/go-ethereum#15891]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version:   1.7.3-stable-4bb3c89d
OS & Version: Ubuntu
Commit hash : (if `develop`)

#### Expected behaviour

https://etherscan.io/address/0x0bf7e287bfbd669bbff824e945c782a3d142bad3

#### Actual behaviour

When I run 

> web3.eth.getBalance('0x0bf7e287bfbd669bbff824e945c782a3d142bad3')
0

It's showing I do have balance. It's block is 4714234

And I'm on 

> eth.syncing
{
  currentBlock: 4912861,
  highestBlock: 4913013,
  knownStates: 10536,
  pulledStates: 10535,
  startingBlock: 4912861
}

geth --fast --cache=2048 has been running more than two days, it has almost reached the end of block( usually couple hundreds left, but I guess that's normal).

Is my node still not synced?

**Comment by lnaie** [comment]
Yap, I'm running the god damn wallet in full node for 4 days now and balance is 0. It's not supposed to be 0. 
Slow, slow, slow.

**Comment by tedkimzikto** [comment]
I really don't get it. 

My transaction block is on 4714234
```

> eth.syncing
{
  currentBlock: 4914984,
  highestBlock: 4915079,
  knownStates: 181336,
  pulledStates: 166426,
  startingBlock: 4914910
}


```
It has way passed my transaction block but it's still not showing the balance? I don't think it will never going to be fully synced because new blocks will be generated.

I should have the balance already. Anyone can help?

**Comment by tedkimzikto** [comment]
I will move the issue to stackexchange. Sorry for spamming.
