### ISSUE TITLE
geth --dev location

### ISSUE THREAD

**Issue by chriscrutt** [ethereum/go-ethereum#15899]
Hello.

I had a few questions and concerns with running `geth --dev`. I'm currently on a OS X system running Sierra.

First, I notice that the Main Network is located at `/Users/username/Library/Ethereum`, along with the Rinkeby testnet files and Robsten, but the Solo Network is nowhere to be seen (even though Mist says the keystore files are there). (I figured this using Mist). I always would just use the Solo Network from the Mist Browser, not Geth in the terminal.

I didn't know about the `--dev` flag (I was still learning) for Geth and was experimenting with my own genesis block creation, using `--datadir` and etc. Thus I wanted to find where the Solo Network given by Mist was located, so I could run `geth` with `--datadir` to it.

After realizing I could use `--dev`, I found `geth.ipc` was here:

    /var/folders/xm/c0_qbn4s5lnfh4n7rs9g32m80000gn/T/geth.ipc
I then also realized, that wasn't the Mist Solo Network, because I was given this:

    WARN [01-15|21:21:10] No etherbase set and no accounts found as default 
I further discovered that if I stop geth and rerun `geth --dev`, it makes another keystone file, and another, and another. So in other words whenever I run `geth --dev`, it makes a whole new blockchain, instead of using the one already created.

To make matters worse, when I look inside all the keystore folders, they're empty, unless I create an account or start mining using the JS console.

Issue:
1. too dang hard to find Solo Network Folder and etc/is located in a weird spot `/var/folders/xm/c0_qbn4s5lnfh4n7rs9g32m80000gn/T/`
2. `geth --dev` won't automatically use your Solo Network, just creates another
3. if `geth --dev` is suppose to create another Solo Network every time, why/shouldn't there be a flag for Mist's Solo Network or etc?
4. Solo Network folder (auto created by Mist) is called `ethereum_dev_mode`, while others created by `geth --dev` are named things such as: `go-ethereum-keystore138651549`

**Comment by karalabe** [comment]
1. If you don't specify anything, it uses an emphemeral datadir (i.e. it gets deleted afterwards, most of the data is in-memory only). If you want to persist the `--dev` mode chain, please specify `--datadir` explicitly.

2. See above, please use `--datadir`.

3. No idea what Mist's solo network is.

4. `ethereum_dev_mode` was a legacy mode the `--dev` flag operated. Unsure why this would be hard coded into Mist though.

**Comment by DiptanshuMalviya** [comment]
geth --dev not working 

This is showing : Fatal: Error starting protocol stack: Access is denied.
Expected showing is : Welcome to the Geth JavaScript console 
What should i do?

**Comment by holiman** [comment]
Original questions are answered, @DiptanshuMalviya please file a new ticket (with more info) if you are still having problem.
