### ISSUE TITLE
Gap in BLOCK_HASHES messages

### ISSUE THREAD

**Issue by mkalinin** [ethereum/go-ethereum#1589]
Guys it seems that `go` peer produces gaps in responses to `GET_BLOCK_HASHES` message

Let me show you an example.
Assume we have following blocks
```
N.   hash=fe36bdcd1bc8f0c4488e0cdefede865e52fcd563d0c3e887b4ef85a4e8f694e5  parentHash=175da96b4e05be9657242023cdc97d85e9f716dddce786bb489e644c0926ce59
N+1. hash=03eacf6c9792ae9674c0b3cd1b37a4e799c3d19c055e65f3bbe2aee2d773ca08  parentHash=fe36bdcd1bc8f0c4488e0cdefede865e52fcd563d0c3e887b4ef85a4e8f694e5
```
We send a message to get `BLOCK_HASHES` for blocks in interval `[K; N]`
```
16:15:26 [net]  To:   ec2-54-197-80-137.compute-1.amazonaws.com/54.197.80.137:30305   Send:   
[GET_BLOCK_HASHES bestHash=03eacf6c9792ae9674c0b3cd1b37a4e799c3d19c055e65f3bbe2aee2d773ca08 maxBlocks=10000]
```
And expect that first hash in response will be a hash of block number `N`
But first hash in response is a hash of block number `N-1`

```
16:15:26 [net]  From:   ec2-54-197-80-137.compute-1.amazonaws.com/54.197.80.137:30305   
Recv:   175da96b4e05be9657242023cdc97d85e9f716dddce786bb489e644c0926ce59
...
```

is there correct behavior on our side?

Thanks in advance

**Comment by mkalinin** [comment]
hey @karalabe 
could you, please, bring some light here?

**Comment by karalabe** [comment]
This is very strange. I'll look into it.

**Comment by karalabe** [comment]
Can you provide me a bigger log? Are you sure it's not an answer to an older request? The code seems ok to me: https://github.com/ethereum/go-ethereum/blob/develop/eth/handler.go#L248, also a lot of tests have been added (pending PR) and they all pass: https://github.com/ethereum/go-ethereum/pull/1380/files#diff-a1e6daf50a903ab780250b2ef8f183a6R22.

**Comment by karalabe** [comment]
Just as a follow up, I saw that we haven't used that function in a long while (since switching over to eth/61), so maybe I actually broke something in it. Will investigate, but probably will only have a clear answer tomorrow.

**Comment by karalabe** [comment]
Maybe this is the issue? https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/net/eth/BlockHashesMessage.java#L38 (i.e. you iterate from 1 instead of 0)?

**Comment by mkalinin** [comment]
oh, that was it! closing the issue
thank you so much for the help! :+1:

**Comment by karalabe** [comment]
You're very welcome :)
