### ISSUE TITLE
"panic: runtime error: index out of range" with 1.8.0-unstable

### ISSUE THREAD

**Issue by okayplanet** [ethereum/go-ethereum#15901]
#### System information

Geth
Version: 1.8.0-unstable
Git Commit: 3f40b22dac9cb36fdf2baacf4789a52adbb611fd
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.8

#### Expected behaviour
Reliable mining without crash when using :
`geth --networkid "3" --cache "1024" --port "30303" --rpc \
--rpcaddr "127.0.0.1" --rpcport "8545" \
--rpcapi "admin,db,eth,debug,miner,shh,txpool,net,web3,personal" \
--rpccorsdomain "*" --verbosity 3 --mine --testnet --fast console
`
#### Actual behaviour
After 9 hours or so, geth crashes with "panic: runtime error: index out of range"

#### Steps to reproduce the behaviour
Run geth as mentioned above and wait.

#### Backtrace

[geth_mining_crash.txt](https://github.com/ethereum/go-ethereum/files/1635673/geth_mining_crash.txt)

**Comment by karalabe** [comment]
This seems to be a bug in Go's GC. Quite a few Geth and Go releases have been done since then. Please use a recent version of Geth and Go.

**Comment by adamschmideg** [comment]
I'm closing this issue. If you think the problem persists with the most recent version of Geth / Go, please open a new issue for that.

**Comment by holiman** [comment]
This is built with go 1.8, and the stack trace indicates that it's an issue with the go garbage collector. Please reopen if it happens again with more recent software.
