### ISSUE TITLE
need to stop and restart miner when first start failed

### ISSUE THREAD

**Issue by dongsam** [ethereum/go-ethereum#15909]
#### System information

Geth version: `geth 1.7.3`
OS & Version: OSX High Sierra
Commit hash : not yet

#### Expected behaviour

on the geth console,

1. miner.start() without unlock
2. mining not start with warning
- `WARN [01-17|21:53:20] Block sealing failed err="authentication needed: password or unlock"`
3. personal.unlockAccount(eth.coinbase) and input Passphrase
4. mining.start() again
5. mining start successfully

#### Actual behaviour

1. miner.start() without unlock
2. mining not start with warning
- `WARN [01-17|21:53:20] Block sealing failed err="authentication needed: password or unlock"`
3. personal.unlockAccount(eth.coinbase) and input Passphrase
4. mining.start() again
5. nothing changed, still not start mining 
6. for the start mining, mining.stop() and mining.start() 

#### Steps to reproduce the behaviour

I think if change code of `Start` and `Stop` of `miner/miner.go` about atomic section, It can solve this problem and we can start without stop, and restart

could I fix this?

**Comment by Kaisle** [comment]
Bump
