### ISSUE TITLE
Ethereum version upgrade problem

### ISSUE THREAD

**Issue by gjp1230** [ethereum/go-ethereum#15906]
ethereum old version:1.4.2
ethereum new version:1.7.3-stable

After the version is upgraded，genesis.json added config part，
Does this result in an inability to connect to a node that uses the old version of the creator block?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of the real issues. So please close this issue. Thanks!
