### ISSUE TITLE
Transfer question 

### ISSUE THREAD

**Issue by mymixing** [ethereum/go-ethereum#15908]
Hi, I have a question for you.
I want to send the erc20 transaction using rpcapi eth_sendTransaction,
But I don't know how to generate the eth_sendTransaction parameter data?
How can I solve the problem?
I don't want to use token.Transfer for this transaction because I don't want to store the keystore locally.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of the real issues. So please close this issue. Thanks!

**Comment by mymixing** [comment]
ok,thanks
