### ISSUE TITLE
No access to geth wallet after new sync

### ISSUE THREAD

**Issue by Sunl0unger** [ethereum/go-ethereum#15912]
Hi there, 

I've created my wallet with geth and started mining. A few months later after reinstalling WinOS I started a fresh geth sync but now the geth does not seem to be able to communicate and I cannot make any transactions. If I use my keystore file, would I be able to access my wallet with Mist? What would you recommend to do to regain access to my wallet?

Thanks

**Comment by RichHorrocks** [comment]
We'd need to see the Geth logs to be able to determine why it's failing to communicate.

Note that Mist also requires a synced chain - it uses Geth in the background.

If you're struggling to sync, for whatever reason, and would like to get immediate access to your account, I'd recommend using MyEtherWallet. (https://www.myetherwallet.com) If you're worried about using their online page, then the wallet can be run offline instead. (https://myetherwallet.github.io/knowledge-base/offline/running-myetherwallet-locally.html)
