### ISSUE TITLE
How to configure the auto generated developer account's balance by the command: ./geth --datadir="./neural-test-data" --dev init genesis.json?

### ISSUE THREAD

**Issue by cylof22** [ethereum/go-ethereum#15918]
Hi All,

How to configure the genesis.json file to define the balance of the auto generated developer account?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of the real issues. So please close this issue. Thanks!
