### ISSUE TITLE
Wrong gas consumed for delegated calls

### ISSUE THREAD

**Issue by denisgranha** [ethereum/go-ethereum#15911]
I'm not running any node, I'm performing transactions against a Gnosis Multisig in the Rinkeby Network with Metamask 3.13.4
Basically what I found is that need to send more gas in the transaction than what is actually consumed, if I send a more accurate amount of gas to perform the transaction it will throw an out of gas

The transactions are the following:
1. Create the Gnosis Multisig through https://wallet.gnosis.pm and metamask in Kovan
e.g: https://rinkeby.etherscan.io/tx/0xa7ec07b916f3846c7b6484b4f44c91887ee1953ad88ecdbf6f2b2c70fb052e7e

2. Add multisig owner with accurate gas amount 240k gas: https://rinkeby.etherscan.io/tx/0x1a19f2fdad80aad642d04525db7ee77b773b6ff61e82e15eade346a4cc336a3c

3. Add multisig owner with high gas amount 1M: https://rinkeby.etherscan.io/tx/0xea1c0fda7dc7cb995941902b612bdf5f61997597ec9335af2725c7f13558c22a

You can see that the add owner transaction consumes around 222k gas in the third transaction but it consumes 197k in the second one.
What we have here is that the related delegated call is not executed in the transaction with the lower gas, with Kovan (Parity) had the same behaviour (same amount of gas) but with the difference that [Kovan throws and out of gas in ether scan](https://kovan.etherscan.io/tx/0x3a7ddd5ed7bae3c2ad8343e42e0d32b0cf1759cfc3c6d946d6cd21c31ae41160) but [Rinkeby don't](https://rinkeby.etherscan.io/tx/0x1a19f2fdad80aad642d04525db7ee77b773b6ff61e82e15eade346a4cc336a3c)

I have two concerns:
1. Why if the transaction with the higher gas consumes 222k gas at the end and sending 240k doesn't get a full execution.
2. Why if the delegated call fails the main transaction doesn't have any out of gas? One of both Geth or [Parity has an incorrect behaviour](https://github.com/paritytech/parity/issues/7602)

For reference:

This is the main function https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol#L189

That does a delegated call against the same Multisig Contract [in this line](https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol#L233) against the [add owner function](https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol#L122)

**Comment by holiman** [comment]
It's not a "delegated call", there's no such thing. There exists something called `DELEGATECALL`, but the gnosis multisig just uses call:s. 

The reasons for contracts to behave subtly different depending on the gas supplied can be tricky to determine without going deep into either the source code or actually stepping through the execution op by op. A `SSTORE` which sets something to `0` will have a "runtime cost" of 20K gas, but 15K will be returned after the call is done, so if those things are happening, then the  supplied gas must be larger than the gas that will eventually be actually used (deducted). 

An inner call (a call from a contract) can go OOG without the outer, envelope call, going  OOG. 

I suggest you try to debug this in remix, or ask gnosis about what the problem can be. This is not an issue in go-ethereum.

**Comment by holiman** [comment]
So it appears that it is the inner call, `txn.destination.call.value(txn.value)(txn.data)` that fails. Are you sure it's _truly_ failing due to OOG, and not because of any of the conditions: `ownerDoesNotExist(owner)`, `validRequirement(owners.length + 1, required)`. I'm asking because I'm not 100% certain myself on how reliable the parity trace error causes are; if they distinguish between these diferent errors: OOG / Invalid op / invalid jump / REVERT .

**Comment by denisgranha** [comment]
Yes, It's the exact same operation, with the same account signing the transaction. One fails and the other don't, the only change is the gas amount

**Comment by AlexeyAkhunov** [comment]
There is no mystery here :) When Solidity compiles the call() statement (have a look into the opcodes with solc --opcodes), it calculates the gas budget for the inner call as the current remaining gas - 34710. 34710 is a "magic number", which include allowance for callGas (700) + callVeryLow (3, to pay for SUB) + callValueTransferGas (9000) + callNewAccountGas (25000, in case the destination address does not exist and needs creating).

Therefore, if you send tx with 240'000 gas, the budget for the inner call will be at most 205290, which is less than 223k that you require.

**Comment by denisgranha** [comment]
Good morning @AlexeyAkhunov ! Thanks for getting involved

So, the inner call costs 34710 more, but this value is not payed at the end?
Why don't include that in the estimateGas function?

The problem is that with this inner calls, estimateGas function is useless

We want to estimate all the operations in https://wallet.gnosis.pm/

**Comment by Georgi87** [comment]
At the time the .call operation is executed the remaining gas - 34710 is used to execute the addOwner operation. This amount is not sufficient if we only send the actually used gas amount, because this doesn't take the 34710 gas into account. We have to set the gas amount like this: gas costs used until .call operation + gas costs used for .call operation + 34710. Until the estimateGas function is fixed, one can only assume a high amount of gas to make sure it will actually process. Fortunately revert doesn't consume the remaining gas anymore.
