### ISSUE TITLE
Geth v1.7.2 not connecting to ropsten

### ISSUE THREAD

**Issue by royitaqi** [ethereum/go-ethereum#15915]
Hi there,

Posted the question on [StackExchange](https://ethereum.stackexchange.com/questions/36636/geth-v1-7-2-not-connecting-to-peers-on-ropsten), but thought I should report it here, too.

#### System information

Geth version: 1.7.2-stable
OS & Version: Ubuntu 16.04.3 LTS
Commit hash : 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9

#### Expected behaviour

Run `/home/MYUSER/.config/Ethereum Wallet/binaries/Geth/unpacked/geth --verbosity 5 console --testnet --datadir=/home/MYUSER/.ropsten --port 30304 --syncmode fast --cache 1024 --rpc --rpcapi="web3,eth,net,personal" --rpcaddr "localhost" --rpcport 8546`. Waited for 10 minutes. Expect geth to sync with ropsten.

Details:

Expect to see log about connecting to peers and start syncing.
Run `eth.syncing` and expect to see syncing progress.
Run `admin.peers` and expect to see peers.

#### Actual behaviour

See log of trying to connect to `52.169.14.227` and `13.84.180.240` but see `i/o timeout` and `connection refused`.
Run `eth.syncing` and see `false`.
Run `admin.peers` and see `[]`.

#### Steps to reproduce the behaviour

Install Ethereum Wallet. Start geth using the aforementioned command.

#### Backtrace

Not sure what "backtrace" this is. I posted some logs in the StackExchange question (see link above).

#### Notes

The data directory `/home/MYUSER/.ropsten` is a new directory. Basically syncing from scratch.
Checked my firewall and router NAT, 30303 and 30304 are both allowed for TCP and UDP.

**Comment by mjdillon** [comment]
It would appear that the bootnodes are overloaded/down.

**Comment by royitaqi** [comment]
Hi @mjdillon , thank you for the comment. So is there anything I can do? Or I should just wait?

**Comment by royitaqi** [comment]
Actually, can anyone confirm that the above bootnodes of ropsten are **down or not**?

Also, could someone give me a list of nodes that they know are working? I am not familiar with geth but I assume I can use those working nodes as bootnodes?

**Comment by mjdillon** [comment]
ethernodes.org is really good for tracking nodes on the mainnet, and they
also do ropsten.

https://www.ethernodes.org/network/2/nodes

**Comment by royitaqi** [comment]
Thank yo so much again, this time for the tool, @mjdillon .   So can I assume that in the page you link to these are active node, one in each row, even though the page says "Blocks"?   And with that assumption my next step would be to restart my geth and use a few of those as bootnode?

**Comment by royitaqi** [comment]
Tried to use `admin.addPeer()` to add a few nodes from the page @mjdillon gave. They are either `i/o timeout` or `connection refused`. One of them showed something like `genesis block mismatch - 0cd786a2425d16f1 (!= 41941023680923e0)`. Wondering why it's so hard to get onto `ropsten`.

**Comment by royitaqi** [comment]
Installed Geth 1.7.3-stable-4bb3c89d from PPA and still the same. Running out of things to try here.

**Comment by royitaqi** [comment]
Problem seemed to be solved now. Credit goes to @mjdillon (and me for fixing the last bit :)). So the last piece missing was that @mjdillon 's link points to network ID `2`, while I was trying to connect `ropsten` which is `3`. So after I go to `ropsten`'s [node page](https://ethernodes.org/network/3/nodes) I find a node which finally start to feed me blocks.

Running Geth 1.7.3-stable-4bb3c89d from PPA. Didn't check back on Geth 1.7.2.

**Comment by tvance929** [comment]
Thank you so much!  This was what I needed too... just had to find a good enode!
