### ISSUE TITLE
Wrong reward received for Uncles!

### ISSUE THREAD

**Issue by federicoon** [ethereum/go-ethereum#1591]
As announced on the forum: 

> The successful PoW miner of the winning block receives:
> - A static block reward for the 'winning' block, consisting of exactly 5.0 Ether

> [...]

> Uncles included in a block formed by the successful PoW miner receive:
> - 7/8 of the static block reward

Thus miners who found an Uncle should get 7/8 of 5.0 Ether = 4.375 Ether
In fact we only received 3.75 Ether per Uncle, so we're missing 0.625 Ether per Uncle!

**Comment by obscuren** [comment]
No. The uncle reward formula is `(U_n + 8 - B_n) * R / 8`

So:
uncle 0 == 4.375
uncle 1 == 3.75

Here's an example

```
U_0 = (5 + 8 - 6) * 5 / 8 == 4.375
U_1 = (4 + 8 - 6) * 5 / 8 == 3.75
```

**Comment by federicoon** [comment]
Thank you. Then the announcement was not stated correctly.
Anyway, what does B_n stand for? I see R is the static reward and U_n the uncle rank, but can't figure out what B_n represents.

**Comment by obscuren** [comment]
Block number :)

**Comment by federicoon** [comment]
Sorry, I'm still missing something... my understanding was U_n is a relative order, i. e. the n-th uncle for some block, so the n count resets after a new block is mined and added to the chain. Am I wrong then?
The block number is an absolute value instead (over 30k right now), so I don't understand how that formula can work. I'm confused...

**Comment by obscuren** [comment]
It's not count. It's number. Uncle number (block number); not inclusion count.

**Comment by federicoon** [comment]
I see, thank you. Can you please point me to some detailed documentation on how uncles are included? I still can't see how you ensure there are enough uncles so that U_n + 8 - B_n > 0 at any time.

**Comment by Gustav-Simonsson** [comment]
@federicoon See yellow paper section 11.3 equation 144: gavwood.com/paper.pdf

**Comment by federicoon** [comment]
Ommer? What the heck does that mean? Is it the same as uncle?

**Comment by perl5577** [comment]
I not undestand equation 143 .

What Bu ?

How many for reward ommer ?
