### ISSUE TITLE
Node crash every time after mining 5-6 day

### ISSUE THREAD

**Issue by dksuper** [ethereum/go-ethereum#15916]
Node crash every time after mining 5-6 day

#### System information

Geth version: v1.6.7-stable
Go version: go1.8.3
OS & Version: ubuntu 14.04
Commit hash : (if `develop`)

#### Steps to reproduce the behaviour

miner.start(1)

#### Backtrace

INFO [01-17|11:22:15] Commit new mining work                   number=659999 txs=1 uncles=0 elapsed=5.308ms
INFO [01-17|11:22:22] Imported new chain segment               blocks=1   txs=1 mgas=0.357 elapsed=11.426ms   mgasps=31.252  number=659999 hash=ea331a…1e5581
INFO [01-17|11:22:22] Commit new mining work                   number=660000 txs=0 uncles=0 elapsed=380.673µs
unexpected fault address 0x7f53105cf308
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f53105cf308 pc=0x461137]

goroutine 9455990 [running]:
runtime.throw(0xeae513, 0x5)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc42004a9f0 sp=0xc42004a9d0
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc42004aa40 sp=0xc42004a9f0
runtime.memmove(0xc462dc6900, 0x7f53105cf308, 0x40)
        /usr/local/go/src/runtime/memmove_amd64.s:184 +0x657 fp=0xc42004aa48 sp=0xc42004aa40
github.com/ethereum/go-ethereum/consensus/ethash.hashimoto(0xc42004ad78, 0x20, 0x20, 0x780966dfbd8a6be2, 0x4a7fff80, 0xc422655b00, 0xc42004ac48, 0x40b944, 0xd3aba0, 0xc42136c780, ...)
        /home/ubuntu/library/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:312 +0x36e fp=0xc42004abe0 sp=0xc42004aa48
github.com/ethereum/go-ethereum/consensus/ethash.hashimotoFull(0x7f5310540008, 0x129fffe0, 0x129fffe0, 0xc42004ad78, 0x20, 0x20, 0x780966dfbd8a6be2, 0xc422655a80, 0x20, 0x20, ...)
        /home/ubuntu/library/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:355 +0xbe fp=0xc42004ac58 sp=0xc42004abe0

**Comment by karalabe** [comment]
Please update to latest Geth (1.7.3). There are further fixes coming in 1.8.0 too to the miner code, but it's not yet merged to master.

**Comment by dksuper** [comment]
Hi Karalabe,
Thank you for your reply. It seems like issue [#15917](https://github.com/ethereum/go-ethereum/issues/15917) with 1.7.3-stable still has the same problem as I do. So should I update to latest Geth (1.7.3) then or should I wait for 1.8.0 ?

**Comment by dksuper** [comment]
Hi @karalabe ,
Thank you for your reply. It seems like issue [#15917](https://github.com/ethereum/go-ethereum/issues/15917) with 1.7.3-stable still has the same problem as I do. So should I update to latest Geth (1.7.3) then or should I wait for 1.8.0 ?

**Comment by karalabe** [comment]
The master branch now contains a fix for the ethash issue.

**Comment by karalabe** [comment]
Closing this issue, but feel free to reopen if using the latest mater still reproduces crashes for you.

**Comment by dksuper** [comment]
Hi @karalabe ,
According to your suggest , I upgraded my node to master branch version; the node has been mining more than 70000 blocks so far and it is still working now which means this issue has been sloved! Thank you.
