### ISSUE TITLE
gasPrice field of log in Javascript tracer

### ISSUE THREAD

**Issue by vsaraph** [ethereum/go-ethereum#15929]
I am using geth version 1.7.3-stable on OS X.

I've come across what I believe to be a minor bug in the transaction tracer ([debug.traceTransaction](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_tracetransaction) in Management API).

This concerns the `gasPrice` field of the `log` object in the Javascript tracer. While the gas price is accurately described in the documentation as the cost (in Wei) per unit gas, I believe that the tracer actually stores a _gas cost_ in the `gasPrice` field. This is what I observed when running the Javascript tracer and accessing the `gasPrice` field. Furthermore, I believe the intent was for `gasPrice` to actually be gas cost, since the default tracer returns a `gasCost` field per instruction (and not a gas price). So fixing this would merely require renaming the `gasPrice` field to `gasCost`, and updating the description in the documentation accordingly.

Recreating this bug is pretty straightforward; just run the Javascript tracer given below, and compare the output to gas cost values in the yellow paper or in [this spreadsheet](https://docs.google.com/spreadsheets/d/1n6mRqkBz3iWcOlRem_mO09GtSKEKrAsfO7Frgx18pNU/edit#gid=0).

`{data: [],
    step: function(log) {
        opstr = log.op.toString();
        this.data.push([opstr, log.gasPrice]);
    },
    result: function() {return this.data; }
}`

**Comment by karalabe** [comment]
The JavaScript traces the completely reworked in Geth 1.8.0. Please try the master branch to see an updated behavior and API (and yes, this was also fixed, it indeed was the wrong field).

**Comment by karalabe** [comment]
E.g. Our most complex tracer to date (call tracer): https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/internal/tracers/call_tracer.js
