### ISSUE TITLE
The calling to the const member function of the new instanced smart contract always emits a error message: no contract code at address.

### ISSUE THREAD

**Issue by cylof22** [ethereum/go-ethereum#15924]
After instancing my own smart contract by NewSmartContract(address, ethClient), calling the const member function will see the error message: no contract code at address. I just following the example of the section 'Deploying contracts to Ethereum' in the wiki 'Native DApps: Go bindings to Ethereum contracts'. Is it a regression? My local version is 1.7.

**Comment by cylof22** [comment]
@fjl I have seen your blog about the stable go API Since Geth 1.4. Can you double check the API for this problem.

**Comment by karalabe** [comment]
Did you wait for the transaction to be mined?

**Comment by cylof22** [comment]
I launched the ethereum private network by geth --dev --datadir='My data directory'. The log information shows that the transaction is mined. I also call another function bind.WaitMined to make sure the transaction is mined.
