### ISSUE TITLE
geth attach does not support --datadir

### ISSUE THREAD

**Issue by witten** [ethereum/go-ethereum#1593]
In one terminal, I run:
```
geth --networkid 1234 --genesis gen.json --datadir ~/.ethereum_testnet console
```

In another terminal, I run:
```
geth --datadir ~/.ethereum_testnet attach
```

And get the following error:
```
Fatal: Unable to attach to geth node - dial unix /home/me/.ethereum/geth.ipc: connection refused
```

I expect geth to look in ~/.ethereum_testnet for the ipc file, not ~/.ethereum

My version:
```
Geth
Version: 1.0.1
Protocol Versions: [61 60]
Network Id: 1
Go Version: go1.4.2
OS: linux
GOPATH=
GOROOT=/usr/lib/go
```

**Comment by obscuren** [comment]
`geth attach ipc://datadir`

**Comment by rocksmani** [comment]
Hi all, having the same issue here. I am unable to execute this cmd and getting the same error as mentioned above.

**Comment by bas-vk** [comment]
As mentioned, `geth attach` accepts an endpoint descriptor. If not given it tries to connect to the default endpoint. If you use a custom datadir the ipc endpoint is located within that datadir.

```
geth attach ipc:<my-datadir>/geth.ipc
```

If you started the node with `--testnet` geth uses an implicit custom datadir. To attach to the testnet node try this:

```
geth attach ipc:$HOME/.ethereum/testnet/geth.ipc
```

**Comment by rocksmani** [comment]
Hi 
 
Thank you for your inputs. 
 
Will you be available for quick chat ? I am very new to this, would need some help
 
Regards
Manish
 
Date: Mon, 25 Apr 2016 04:40:46 -0700

**Comment by bas-vk** [comment]
Join https://gitter.im/ethereum/go-ethereum and ask your question there.
Or send me a private gitter message if you prefer that.

**Comment by rocksmani** [comment]
I am done with that cmd, I ran this way “geth
chains/devtest/geth.ipc attach” seemed working. Its running for long, unable to execute the rest commands..
 
This is what I did:



I’ve 2 nodes though trying to
use 1. Logged on to the box 1, ran “sh seed-blockchain.sh”


Opened another putty for the
same box 1, ran ““geth chains/devtest/geth.ipc attach”


 Correct me if I’m making any mistake here 
Date: Tue, 26 Apr 2016 03:06:24 -0700

**Comment by bas-vk** [comment]
Please post the geth version, the commands that you used and describe what you are trying to accomplish.
