### ISSUE TITLE
'No contract code at given address' happens when calling the auto generated DeployToken function.

### ISSUE THREAD

**Issue by cylof22** [ethereum/go-ethereum#15930]
The returned err is nil, and the given address is also ok. How calling any member function will see the 'No contract code at given address'. The geth version is 1.7.

**Comment by vedev9** [comment]
Same thing here. I use abigen to generate the files, deploy a contract into my SimulatedBackend (without errors) but when i call a function it gives me that error. 
One thing i noticed is that if there are no imports it works... 

Solc: 0.4.21+commit.dfe3193c.Linux.g++

**Comment by natemurthy** [comment]
I'm observing something similar following the example on

https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts

First I noticed that the `token.go` provided by @karalabe breaks on `master@1da3302`:

```
./token.go:121:30: not enough arguments in call to bind.NewBoundContract
	have (common.Address, abi.ABI, bind.ContractCaller, bind.ContractTransactor)
	want (common.Address, abi.ABI, bind.ContractCaller, bind.ContractTransactor, bind.ContractFilterer)
```

So I generated my own Go bindings using `abigen` and using that I run the snippet (borrowed from the link above):

```go
package main

import (
	"fmt"
	"log"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	// Create an IPC based RPC connection to a remote node
	conn, err := ethclient.Dial("/Users/nate/Library/Ethereum/geth.ipc")
	if err != nil {
		log.Fatalf("Failed to connect to the Ethereum client: %v", err)
	}
	// Instantiate the contract and display its name
	token, err := NewToken(common.HexToAddress("0x21e6fc92f93c8a1bb41e2be64b4e1f88a54d3576"), conn)
	if err != nil {
		log.Fatalf("Failed to instantiate a Token contract: %v", err)
	}
	name, err := token.Name(nil)
	if err != nil {
		log.Fatalf("Failed to retrieve token name: %v", err)
	}
	fmt.Println("Token name:", name)
}
```

which results in:

```
$ go run snippet.go token.go                                   
2018/05/01 23:31:36 Failed to retrieve token name: no contract code at given address
exit status 1
```

The address is the "foundation's Unicorn token contract deployed to testnet" (not entirely sure what that means yet). My immediate question, then, is what address should I use and how do I load this contract into that address?

**Comment by fabdarice** [comment]
My solution was to do 
`auth.GasLimit = 1000000`

**Comment by ansermino** [comment]
Any progress on this? Has anyone identified where the problem is?

**Comment by yekai1003** [comment]
```
pragma solidity^0.5.0;

contract pdbank {
    address public  owner;
    mapping(address=>uint256) public balances;
    uint256 public totalAmount;
    string public bankName;
    constructor(string memory _bankName) public  {
        owner = msg.sender;
        bankName = _bankName;
    }
    function deposit() public payable {
        //do nothing
        totalAmount += msg.value;
        balances[msg.sender] += msg.value;
    }
    function withdraw(uint256 _amount) public payable {
        if(balances[msg.sender] > _amount) {
            balances[msg.sender]  -=  _amount;  
            msg.sender.transfer(_amount);
            totalAmount -= _amount;
        }
    }
}
```
`
func DeployPdbank() (common.Address, error) {
	var contractaddr common.Address
	auth, err := MakeAuth("0x70c53a4c94ccce9ce56effbfcb89b221f986cd41", "123")
	if err != nil {
		fmt.Println("failed to makeAuth", err)
		return contractaddr, err
	}
	auth.GasLimit = 300000
	auth.GasPrice = 100
	fmt.Printf("%+v,,,%s\n", auth, auth.From.Hex())
	contractaddr, tcs, pb, err := contracts.DeployPdbank(auth, testclient, "niaofei")
	if err != nil {
		fmt.Println("failed to deloy ", err)
		return contractaddr, err
	}

	fmt.Println(tcs.ChainId(), tcs.Hash().Hex(), tcs.Nonce())
	fmt.Println(contractaddr.Hex())
	time.Sleep(time.Second * 14)

	fmt.Println(pb.BankName(nil))
	return contractaddr, err
}
`
I  have  get the same  problem!  Why?

**Comment by karysto** [comment]
I'm encountering this error as well (on a private network), but only when I try binding immediately after confirming I have the transaction hash containing the local contract, otherwise if I wait a bit, it works. Could this be a race condition between how the state and chain data is updated?

**Comment by sahirug** [comment]
> I'm encountering this error as well (on a private network), but only when I try binding immediately after confirming I have the transaction hash containing the local contract, otherwise if I wait a bit, it works. Could this be a race condition between how the state and chain data is updated?

How do you "wait a bit"? I am running into this issue as well. Im using private Ethereum network made in Docker

**Comment by yekai1003** [comment]
You can get eth.Transaction by hash.The status signed the contract has deployed sucessed!

**Comment by csplawn918** [comment]
Please help me understand what you meant by that you can get each
transaction by hash do you mean I can
Receive public balance

**Comment by yekai1003** [comment]
> Please help me understand what you meant by that you can get each transaction by hash do you mean I can Receive public balance

When you deploy a contract, you can get the transaction hash, which can help you query the success of the transaction.This error is usually caused by the failure of contract deployment.You can use eth.getTranaction("hash") on the geth console!

**Comment by jjjachyty** [comment]
i test on nodejs with web3 can use it,why go client has this error?

**Comment by jjjachyty** [comment]
i found this bug maybe geth & go-client & solidity version inconsistency
use solidity 4.x replace 5.x just fine

**Comment by holiman** [comment]
These are probably different issues. 
1. The original concern was about contract deployment -- the error might be that while the tx was accepted, it has not yet been mined at the time the user tries to call the contract. 
2. For @natemurthy , it might be that 1) your node is not synced, or 2) the address is on a testnet (but you are on mainnet) -- please verify that the contract actually exist.

**Comment by karalabe** [comment]
@cylof22 The original issue seems to be that the contract was not yet mined. After deploying, you need to wait until it's actually included on the chain by a miner.

@natemurthy The second issue refers to attaching to an already deployed contract. Please make sure that the Geth instance you are connecting to is on the correct network and is synced.

@yekai1003 Sleeping 14 seconds is a bit of a shot in the dark. You need to track the transaction and wait until it's mined. Contract deployment will return the hash, just track when it's included.

@karysto Same as first, you need to wait until the transaction is mined. If you're in dev mode, it should be fast, but there's still some tiny time window when it's not yet mined. If you are on a non-instamining chain, you need o track the transaction when it's mined before you can interact with it.

**Comment by satb** [comment]
I ran into the same issue of " no contract code at given address". I crossed checked that the transaction and the contract exist and there are several blocks after the block that included the contract creation transaction. I am running a private version of geth. I have the whole setup ready and can provide any details required.

**Comment by regnull** [comment]
I think the problem is still there. @fabdarice had the right answer. In my experience, if the gas limit is too low while deploying the contract, it will be still deployed, and I will be able to call the contract functions that update the state. I can see the transaction included in a block, and I can get back the transaction details. However, when I call a function to return a value, I get "no contract code at given address" error. Increasing the gas limit solves this problem. 

If I look at the transaction details, I can see the difference in gas and cost, the data seems to be the same.

I'm running this on a private blockchain, configured like so: https://github.com/regnull/eth-bc

This is the contract: https://github.com/regnull/ubchain/blob/master/contracts/key_registry.sol

"no contract code at given address" happens when the gas limit is 30000

The error goes away if I increase the gas limit to 1000000

 $solc --version
solc, the solidity compiler commandline interface
Version: 0.8.11+commit.d7f03943.Darwin.appleclang


 $abigen --version
abigen version 1.10.15-stable

 $go version
go version go1.17.5 darwin/amd64

**Comment by wxl2578** [comment]
The problem I have is that the contract address is the main network, and the client is connected to the test network, for example:
Mainnet usdt: 0xdac17f958d2ee523a2206206994597c13d831ec7
Rinkeby usdt: 0x740B06779562fDC9E10a8E3553D7cBCb5DEBA836

If the client is connected to Rinkeby and the usdt contract address uses 0xdac17f958d2ee523a2206206994597c13d831ec7, an error will occur.

**Comment by deitch** [comment]
I too am running into this. primarily with the `SimulatedBackend`. it looks like it deploys but I cannot call any fns on the deployed contract.

**Comment by deitch** [comment]
And, yes, I made sure to call `backend.Commit()`

**Comment by deitch** [comment]
I also stepped through code manually, called `backend.BlockChain().Transactions()`, and walked through each tx. It definitely is there, but when it looks in the statedb, nothing is there at the given address. ChainID issues maybe? 🤷‍♂️

**Comment by jim380** [comment]
ran into this issue with the `SimulatedBackend` today also.

**Comment by deitch** [comment]
I feel less alone now 😃

**Comment by jim380** [comment]
It works perfectly fine with a simple, generic changeOwner/getOwner contract. I wonder why that is. @deitch what tool did you use to generate the abi and bin files?

**Comment by deitch** [comment]
I am pretty sure it was all via `abigen`, as in `abigen --sol=./contract.sol --pkg=somepkg --out=somepkg/contract.go`. But it is possible that I pulled it off of an already-deployed contract on the chain. I can try both ways and see.

A few questions:

1. @jim380 do you mind posting some of your sample code with the `changeOwner`/`getOwner`, both the contract and the go code? I would like to try it.
2. Would it matter? Would the generated abi and bin files not be the same?
3. Is there any way to walk it through, debug what it is doing?

**Comment by jim380** [comment]
```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.7.0 <0.9.0;

contract Owner {

    address private owner;
    
    event OwnerSet(address indexed oldOwner, address indexed newOwner);
    
    modifier isOwner() {
        require(msg.sender == owner, "Caller is not owner");
        _;
    }
    
    constructor() {
        owner = msg.sender; 
        emit OwnerSet(address(0), owner);
    }

    function changeOwner(address newOwner) public isOwner {
        emit OwnerSet(owner, newOwner);
        owner = newOwner;
    }

    function getOwner() external view returns (address) {
        return owner;
    }
}
```

This is the dummy code I tried. Works just fine. My suspicion is that there's something wrong with the abi and bin file we generated before generating the actual bindings. @deitch

**Comment by jim380** [comment]
@deitch you are EE from Columbia too? EE Columbia SEAS '17 here. Small world.

**Comment by deitch** [comment]
Really small world! I assume you found me on LinkedIn? Send an invite?

**Comment by jim380** [comment]
> Really small world! I assume you found me on LinkedIn? Send an invite?

nah. Just staked your github profile a bit.

**Comment by jim380** [comment]
ok something is up for sure. If I try to look up the hash the deploy tx spits out, it's not there!

**Comment by deitch** [comment]
@jim380 did you have a comment to the effect of:

> If I try to look up the hash the deploy tx spits out, it's not there!

I cannot find it, but that was exactly the issue I had.

**Comment by jim380** [comment]
> 

The deploy tx was actually in the DB. Earlier when I was testing things out, I accidentally had the print below `backend.Commit()`. Once I corrected that, it was indeed in the lookup. And also as expected, the contract code was an empty slice, which explains the 'No contract code at given address' error. I'm still trying to figure out why that is.

**Comment by deitch** [comment]
Let me know if I can help somehow.

**Comment by jim380** [comment]
To provide some closure on this, I believe the root cause is still gas. The contract I was trying to deploy is admittedly very heavy, so it'd run out of gas during deployment, This was not obvious with the Geth chain simulator. It'd appear to the signer that the deploy tx was committed in the simulator, but in actuality it wasn't. Which explains why when you later try to call methods on it and you will get "no contract code at given address".

I was able to come to this conclusion after swapping out the simulator with Hardhat's local network as the backend, which gives much richer context in console.

**Comment by deitch** [comment]
@jim380 would it still be an issue with the `SimulatedBackend`? If so, wouldn't the following (taken from the sample [here](https://goethereumbook.org/smart-contract-deploy/)) refuse to return an address or instance, or return an error?

```go
address, tx, instance, err := store.DeployStore(auth, client, input)
```

Maybe this is all just issues with returning errors?

**Comment by jim380** [comment]
@deitch I've figured it out. The issue was the abi bindings. I was using solc to generate the abi and bytecode files and in the generated files it included all contracts (including imported ones ) and libraries. This is precisely why the size of the generated bytecode was so large. I also tried Remix and Hardhat to get the abi and bin files. They work but requires some tweaking.

What's the exact command you used to generate the bindings? Here is mine (which is probably incorrect btw):
```bash
$ solcjs --abi --output-dir abigen_files --include-path node_modules/ --base-path contracts/ xxx.sol
$ solcjs --bin --output-dir abigen_files --include-path node_modules/ --base-path contracts/ xxx.sol
```

**Comment by deitch** [comment]
I have `solc` in my path, so I usually just use `abigen`. Sometimes, if working against a contract already on a public chain (mainnet or testnet), I can just copy the code.

I think you are saying that the size of the bytecode was unusually large, which meant it needed more gas to deploy, hence it failed and no contract code was found?

That does bring me back to my previous question. Wouldn't that show up in `Deploy*()`? Shouldn't it? Either way, is there some way in go-ethereum to check back (especially after run-in `.Commit()` when using `SimulatedBackend`) to the chain and see what happened with the `Deploy*()` call?

Ideally, the `Deploy*()` should work or report an error (even if just "not enough gas"), and we should be able to check what happened to a deployment.

**Comment by danielmbirochi** [comment]
I'm using the SimulatedBackend too, and got the same problem. The contract deployment run out of gas, hence it failed and no error is returned by the SimulatedBackend instance. So just set a higher gas limit and it will be able to call contract functions.

**Comment by jingzhaoou** [comment]
I ran into the same "no contract code at given address" error. From the ganache console, I saw errors 
```
eth_sendRawTransaction

  Transaction: 0x92d598789b97f83db9d780d054a5a33528835711be49ae3c14a338572b68aee9
  Contract created: 0xe2327f464413f324144ce3a7367067a3b4be3efe
  Gas usage: 300000
  Block number: 23
  Block time: Fri May 13 2022 10:54:13 GMT-0700 (Pacific Daylight Time)
  Runtime error: out of gas
```
I resolved the issue by increasing the gas limit. However, I would like a way to detect this from geth. The Golang code was not throwing any error. 
```
	address, tx, instance, err := mycontract.DeployContract(auth, client, input)
	if err != nil {
		log.Fatal(err)
	}
```
I don't think I have access to the console logs in a production environment. I appreciate your help.

**Comment by jingzhaoou** [comment]
I found a way to check if a contract is deployed successfully. Following my above sample code
```
	receipt, err := client.TransactionReceipt(context.Background(), tx.Hash())
	if err != nil {
		log.Fatal(err)
	}
	status := receipt.Status
	fmt.Printf("Receipt status: %d\n", status)
	if status != 1 {
		log.Fatalf("Deploy deployment failed for contract: %s\n", address.Hex())
	}
```

**Comment by wonderfulLand** [comment]
我遇到了同样的问题，楼上是个大神，解决了我一下午的问题。very 3Q much!!!

**Comment by deitch** [comment]
@jingzhaoou props to you, and thank you. I was able to use a variant on your example - after running `client.Commit()` of course - and see that the contract deployment had failed. Unfortunately, it doesn't say why. I am using a gasLimit of 2000000, and setting gas price via `SuggestGasPrice()`. Any attempt to increase it, of course, runs up against the `gas limit reached`.

Thanks to you, I now know _that_ the contract deployment has failed, but I still do not know _why_.
