### ISSUE TITLE
about build geth

### ISSUE THREAD

**Issue by madman1990** [ethereum/go-ethereum#15939]
when build error as 
D:\GoWork\src>go build github.com\ethereum\go-ethereum\cmd\geth
# github.com/ethereum/go-ethereum/crypto/secp256k1
cc1.exe: error: too many filenames given.  Type cc1.exe --help for usage
cc1.exe: fatal error: Files/gcc/include: No such file or directory
 Thanks in advance!

**Comment by karalabe** [comment]
Seems you don't have a valid `gcc` installation on your Windows box.

**Comment by DaleEMoore** [comment]
This:
cc1.exe: fatal error: Files/gcc/include: No such file or directory
makes me think that MinGW-64's frail error-wrought installation methodology did not give you a valid command line.

I wonder if there's anyone that knows what improvements could be made to this MinGW-64's installation to get the proper path contained within quotes.
