### ISSUE TITLE
geth monitor throws a fatal error while starting

### ISSUE THREAD

**Issue by pepihasenfuss** [ethereum/go-ethereum#15933]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

iMac-2012:Ethereum_geth_FP test$ ./geth monitor --attach "/Users/test/Ethereum_geth_FP/Ethereum_fresh/geth.ipc" --refresh 10 --rows 5
Fatal: Metric pattern trie/cachemiss resolved to unexpected type: string
 
#### What did you expect to see?

Monitor values and updates
 
#### What did you see instead?
 fatal error 

#### System details

Version: 1.8.0-unstable
Go Version: go1.9.2
OS: darwin
uname -v: Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1114

**Comment by nonsense** [comment]
@pepihasenfuss this should now be resolved if you build from `master`.

**Comment by adamschmideg** [comment]
@pepihasenfuss I take this issue is resolved. If not, please, open a new issue.
