### ISSUE TITLE
Sync delay between ether scan and my geth instance around 5 hours

### ISSUE THREAD

**Issue by arialix** [ethereum/go-ethereum#15932]
Hi there,
I follow sync 4-5 days and I see big delay between etherscan and my node status.
My last line is:
INFO [01-21|11:14:52] Imported new chain segment               blocks=2 txs=427 mgas=11.331 elapsed=58.490s  mgasps=0.194 number=4944709 hash=fe4694…01d917

But the last block in ehtersan is 'LAST BLOCK 4946058'
Difference is 1349 blocks.
How I can make faster this sync to actual block without remove all db and sync with fast?

my actual geth command:
geth --rpc --rpcaddr "127.0.0.1" --cache "512" --maxpeers 100 --rpcapi "personal,eth,net,web3" console

I check with cache 2048, but result is the same

Is something wrong with geth?

#### System information

Geth version: `Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9`
OS & Version: Linux Ubuntu 16.04

**Comment by arialix** [comment]
Now delay is in 7 hours..

**Comment by veox** [comment]
Try leaving `maxpeers` at the default (25).

**Comment by arialix** [comment]
It was default(25), but when delay was in 5h, I check with different parameters for resolve. Now I return to 25. I will wait if tomorrow delay will be less. Thanks veox for trying to help!

**Comment by arialix** [comment]
Today delay is 8 hrs 7 mins ... increasing...
Any ideas?

**Comment by pepihasenfuss** [comment]
I experienced similar delays while the blockchain grows. Due to massive input/output calls to the drive, I expect the geth node to sync only on large enough SSDs. One of my geth nodes grew to 280 GBs during the past months. I'm running geth on Mac OS.

**Comment by karalabe** [comment]
@arialix Your node cannot keep up with the network load. If you are running on an HDD, forget keeping in sync. Geth 1.8.0 will ship a lot of improvements, but I don't think HDDs will ever be viable for running full nodes.

**Comment by arialix** [comment]
Hello, 
I use Linode server with additional storage volumes. I read in description of server and storage, all are on SSD. I will try to migrate chaindata from additional storage to local on server and let you know.
Thanks for assist

**Comment by arialix** [comment]
My chain database moved from additional storage volumes to local on the server, and now delay is going down fast!

Note for all users: Do not use additional storage on Linode for chain database!

Thanks all about check disc sugestion!
