### ISSUE TITLE
error in building geth

### ISSUE THREAD

**Issue by AkashSarda** [ethereum/go-ethereum#15949]
Hi there,
I added some comments in the source code in core/types/transactions.go
Now I tried to build geth by "make geth", but it says the following:
#### Backtrace
![image](https://user-images.githubusercontent.com/14893293/35264750-eaff1780-0043-11e8-978d-d0f0b6e5f0f2.png)
I will be obliged for an answer!

**Comment by karalabe** [comment]
You code seems out of date, or at least partially. Please check which commit you're on, also make sure you don't have multiple go-ethereum codebases in your GOPATH that might conflict with each other.

**Comment by rakeshkumar33** [comment]
make geth runs fine 
build/bin/geth throws an error 
![screenshot from 2018-02-12 16-35-17](https://user-images.githubusercontent.com/19429428/36094435-408e9b8c-1014-11e8-9619-0e12e34bd758.png)

Fatal: Error starting protocol stack: datadir already used by another process

**Comment by karalabe** [comment]
You seem to already have a geth process running using the same data directory.

**Comment by rakeshkumar33** [comment]
How should I stop that

**Comment by rakeshkumar33** [comment]
I didnt find any geth process running
I tried install through ppa -ddnt worked 
So I cloned git and installed go 
I m running geth for first tme. And I got that 
Also any reference you could suggest me

**Comment by crazyyi** [comment]
I upgrade my go version from 1.9 to 1.10 and then ethereum can be installed.

**Comment by adamschmideg** [comment]
I take this issue is resolved. If I'm mistaken and the problem persists, please, open a new issue.

**Comment by henrytirla** [comment]
> How should I stop that

on mac os 
ps -- look for the geth process pid
kill -9 <PID>
