### ISSUE TITLE
Transaction tracer: gasCost of CALL opcode seems very high

### ISSUE THREAD

**Issue by vsaraph** [ethereum/go-ethereum#15945]
I am using geth version 1.8.0 on OS X.
(commit 02aeb3d76652a4c0451e5c3734e6881aefe46249)

It seems to me like there's something off with the gas cost of `CALL` instructions as calculated by the tracer. Consider the following snippet from the trace of transaction [0xe5c0b9656aba44735008202d975dd4f9ca07db5e7b2ec4611d63237fd45974b0](https://etherscan.io/tx/0xe5c0b9656aba44735008202d975dd4f9ca07db5e7b2ec4611d63237fd45974b0):

...
{u'pc': 3134, u'depth': 1, u'gasCost': 1, u'gas': 1952713, u'op': u'JUMPDEST'}
{u'pc': 3135, u'depth': 1, u'gasCost': 3, u'gas': 1952712, u'op': u'PUSH2'}
{u'pc': 3138, u'depth': 1, u'gasCost': 2, u'gas': 1952709, u'op': u'GAS'}
{u'pc': 3139, u'depth': 1, u'gasCost': 3, u'gas': 1952707, u'op': u'SUB'}
**{u'pc': 3140, u'depth': 1, u'gasCost': 1922204, u'gas': 1952704, u'op': u'CALL'}**
{u'pc': 0, u'depth': 2, u'gasCost': 3, u'gas': 1921504, u'op': u'PUSH1'}
{u'pc': 2, u'depth': 2, u'gasCost': 3, u'gas': 1921501, u'op': u'PUSH1'}
{u'pc': 4, u'depth': 2, u'gasCost': 12, u'gas': 1921498, u'op': u'MSTORE'}
{u'pc': 5, u'depth': 2, u'gasCost': 2, u'gas': 1921486, u'op': u'CALLDATASIZE'}
{u'pc': 6, u'depth': 2, u'gasCost': 3, u'gas': 1921484, u'op': u'ISZERO'}
...

The cost of `CALL` (bolded above) above seems far too high to me. With every other instruction, the `gas` field of the next instruction is equal to `gas - gasCost` of the current instruction, but this is clearly not true for the `CALL` above, or for any other `CALL` I looked at.

I also noticed that`CALL`'s `gasCost` seems to always be 700 more than the next entry's `gas`. Note that 700 gas is the base cost for a `CALL` instruction, according to the yellow paper.

I didn't use a custom Javascript tracer, just the default tracer, with storage, memory, and stack all disabled.

Am I misinterpreting the output for the `CALL` opcode, or is something actually wrong here? I have not yet looked at the output for the related `CALLCODE` and `DELEGATECALL` opcodes, but they might also have a similar issue.

**Comment by LogvinovLeon** [comment]
I'm hitting the same issue. I was able to fix it for me by checking if gas cost is unreasonably high and taking it as a difference between consecutive gas fields, but that's a hack.

**Comment by holiman** [comment]
```
{u'pc': 3138, u'depth': 1, u'gasCost': 2, u'gas': 1952709, u'op': u'GAS'}
{u'pc': 3139, u'depth': 1, u'gasCost': 3, u'gas': 1952707, u'op': u'SUB'}
{u'pc': 3140, u'depth': 1, u'gasCost': 1922204, u'gas': 1952704, u'op': u'CALL'}
```
The `gas` in `call( gas...)` is the entire gas available. So at that point in time, as far as the evm is aware, you're sending all gas -- the cost is thus all gas. Then some goes away (create account is 25K gas, and probably some other things get removed).

**Comment by karalabe** [comment]
If you are interested in the gas **used**, that can only be calculated when the call returns. In the case of opcode traces, it's up to you to calculate it. Geth also has a `callTracer` that can do it for you.
