### ISSUE TITLE
Transactions in large numbers are not being broadcasted

### ISSUE THREAD

**Issue by khelle** [ethereum/go-ethereum#15940]
Hi, I have a problem with geth not dealing properly with a bigger number of transactions queue. When I try to queue bulk number of transactions - lets say 100 of them - with high gasPrice - around 30 of them appears on blockchain almost immediately. Ther leftover 70 are visible in "eth.pendingTransactions" queue but they do not seem to be broadcasted. It seems I need to wait about hour for them to be rebroadcasted by geth automatically. If I manually call eth.resend() on any of it it appears on blockchain almost immediately. Why is that? How can I change this behaviour so geth would automatically rebroadcast transactions more frequently than what seems to be 1 hour gap? Is it event configurable or documented?

**Comment by karalabe** [comment]
What order are you sending the transactions to you node?

**Comment by khelle** [comment]
@karalabe I dont understand your question. If you ask if these 30 tx processes immediately are the first ones I queue - then yes.
