### ISSUE TITLE
Document the APIs

### ISSUE THREAD

**Issue by winteraz** [ethereum/go-ethereum#15955]
I'm trying to create raw transactions using the go-ethereum lib but all the APIs are undocumented which makes it really hard to figure out how to use it. For example [NewEIP155Signer](https://godoc.org/github.com/ethereum/go-ethereum/core/types#NewEIP155Signer) requires a chainId of *big.Int ... how am I supposed to know what is this and what value to give it? I stumbled this issuing trying to create a raw transaction.

**Comment by karalabe** [comment]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md#list-of-chain-ids

**Comment by kishansagathiya** [comment]
Is this issue still relevant ? Can I take it as my first issue for geth?
