### ISSUE TITLE
I get a wrong transactionCount

### ISSUE THREAD

**Issue by mimitc123** [ethereum/go-ethereum#15951]
Before I submit a deal, I use the eth. GetTramsactionCount (" XXX, "" pedding"), the value of the query is 1733, transaction submission after I get the nonce is 1734, and then I use eth getTramsactionCount (" XXX, "" pedding"), query the value is 1733, is this why？

**Comment by karalabe** [comment]
The pending state only contains the next block's worth of transactions. It does **not** execute **all** available transactions. If you want to submit many transactions from a single account, it's probably better to manage the nonces yourself.

**Comment by mimitc123** [comment]
how to do?
