### ISSUE TITLE
AWS abuse report for port scanning

### ISSUE THREAD

**Issue by MitchK** [ethereum/go-ethereum#15957]
Hi,

We run Ethereum on an AWS machines in a productive setup and have received an abuse report from AWS regarding port scanning. The concerning port is ```30303/UDP```.

```
Abuse type*: port-scanning
Source IPs (comma separated)*: xxxx.xxx.xxx.xxx, ec2-xxx-xxx-xxx-xxx.eu-west-1.compute.amazonaws.com
Destination IPs:xxx.xxx.xxx.xxx
Destination ports and protocols (e.g. 22/TCP): 30303/UDP
Destination URLs (space separated): 
Abuse date (yyyy-mm-dd)*: 2018-01-15
Abuse time, 24-hr format (hh:mm)*: 15:37
Time zone*: -0800
The host clock is synchronized by NTP: 
Logs (4KB max)*: Jan 15 15:37:19    WAN     xxxx.xxx.xxx.xxx:62190
ec2-xxx-xxx-xxx-xxx.eu-west-1.compute.amazonaws.com     10.0.0.2:30303    UDP

Jan 15 15:37:18    WAN     xxxx.xxx.xxx.xxx:62190
ec2-xxx-xxx-xxx-xxx.eu-west-1.compute.amazonaws.com     10.0.0.2:30303    UDP
Comments (4KB max): xxxxxxx
Custom tracking number (optional):
```

Is this something that Ethereum does and how to turn it off?

**Comment by ivica7** [comment]
I had a similar problem at a different hoster -> https://ethereum.stackexchange.com/questions/6386/how-to-prevent-being-blacklisted-for-running-an-ethereum-client/9945#9945  The only reliable way to solve this with geth was to use the firewall to block sending to private network addresses. In parity there is ``--allow-ips public``, but afaik there is nothing similar in geth. Maybe it would be a good thing to add such a flag to geth too.

**Comment by fjl** [comment]
This was fixed a few releases ago. We don't send UDP packets to private network addresses anymore.
