### ISSUE TITLE
RPC: add personal_signTransaction: [tx, pw]

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#15953]
> we need the personal_signTransaction: [tx, pw] function in geth in order to allow infura connection. The node is un-usable on a ordinary computer and the storage to large. SO its not really an options for Mist anymore

> We want to add signing with the current geth for now, and for that we need the above function asap :smiley:
otherwise we would need to unlock, sign and lock, which causes a security risk, as the node is vulnerable for a few sec.

> eth_signTransaction exists, but we needpersonal_signTransaction, which accepts a pw as second param

via @frozeman

**Comment by holiman** [comment]
I agree about this
