### ISSUE TITLE
[Question] Tries

### ISSUE THREAD

**Issue by sontuphan** [ethereum/go-ethereum#15966]
Hi there,

It's not an issue, I just want to ask you a question about trie.
I try to get dive into trie, the detail is state trie. But I can find where folder stores it.
If you have some knowledge about that, please let me know, I literally appreciate it. Thank you.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of the real issues. So please close this issue. Thanks!
