### ISSUE TITLE
Nonce gap closed but tx's stay in txpool.pending

### ISSUE THREAD

**Issue by Shenno** [ethereum/go-ethereum#15973]
Hi all,

Doing some experiments (manually managing nonces) with web3j and geth (Rinkeby) when I noticed the following:
Given the next valid nonce is 3, then:
- Submit a transaction with nonce 3 => Mined successfully 
- Submit a transaction with nonce 5 => Tx is in txpool.pending
- Submit a transaction with nonce 4 => Mined successfully
If I understand correctly, the tx with nonce 5 should be picked up automatically because the nonce gap was closed, yet this transaction stays in txpool.pending.

Not 100% sure this is expected behavior.

Thanks!

#### System information

Geth version: 1.7.3-stable on Ubuntu 16.04

**Comment by holiman** [comment]
Hm, what actually _should_ happen: 

1. Submit a transaction with nonce 3 => Mined successfully
2. Submit a transaction with nonce 5 => Tx is in **txpool.queued**
3. Submit a transaction with nonce 4 => 4 should go into `pending`, 5 should be bumped from `queued` into `pending`, and both should be mined successfully.

**Comment by Shenno** [comment]
Thanks @holiman for the quick answer.
Our transaction with a higher nonce goes to **txpool.pending**
We are running the light client, could this be the cause?
