### ISSUE TITLE
build error for go-duktape.v3 with go1.9beta2  on linux

### ISSUE THREAD

**Issue by luoiefly** [ethereum/go-ethereum#15970]
Hi there,

[luoie@iZ2ze8cv2xzahguq7l3lveZ go-duktape.v3]$ 
[luoie@iZ2ze8cv2xzahguq7l3lveZ go-duktape.v3]$ go  version
go version go1.9beta2 linux/amd64
[luoie@iZ2ze8cv2xzahguq7l3lveZ go-duktape.v3]$ go build
# _/home/luoie/blockchain/ethfun/vendor/gopkg.in/olebedev/go-duktape.v3
./duktape.go:132: constant 18446744073709551615 overflows int64
[luoie@iZ2ze8cv2xzahguq7l3lveZ go-duktape.v3]$

**Comment by holiman** [comment]
This is due to a compiler error in Go 1.9.0 and 1.9.1, update to `1.9.2` instead. See https://github.com/golang/go/issues/21708

**Comment by Philipp2406** [comment]
I am running Go 1.9.2 and get the following:

`github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3
# github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3
In file included from vendor/gopkg.in/olebedev/go-duktape.v3/api.go:7:0:
vendor/gopkg.in/olebedev/go-duktape.v3/api.go: In function ‘_duk_error’:
vendor/gopkg.in/olebedev/go-duktape.v3/duktape.h:510:127: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  (duk_error_raw((ctx), (duk_errcode_t) (err_code), (const char *) (DUK_FILE_MACRO), (duk_int_t) (DUK_LINE_MACRO), __VA_ARGS__), (duk_ret_t) 0)
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
vendor/gopkg.in/olebedev/go-duktape.v3/api.go:153:2: note: in expansion of macro ‘duk_error’
  duk_error(ctx, err_code, "%s", str);
  ^~~~~~~~~
`

**Comment by karalabe** [comment]
Yeah, annoying but it's just a warning.
