### ISSUE TITLE
IPC Moved on windows?

### ISSUE THREAD

**Issue by d11e9** [ethereum/go-ethereum#1597]
When updating from v1.0.0 Frontier to v1.0.1 Thawing, I can no longer connect via ipc. Is the file now created in a different location other than $datadir/geth.ipc`

    $ geth.exe --datadir ./eth --ipcapi "eth,personal" --ipcpath './eth/geth.ipc'
    ...
    $ Fatal: Error string IPC: Invalid pipe address '$datadir\geth.ipc'.

When not providing `ipcpath`:
    
    $ geth.exe --datadir ./eth --ipcapi "eth,personal"
    ...
    $ I0806 11:14:42.633121   16872 ipc_windows.go:696] IPC service started (\\.\pipe\geth.ipc)

    $ geth.exe attach ipc:$datadir/geth.ipc
    ...
    $ Fatal: Unable to attach to geth node - Invalid pipe address  '$datadir\geth.ipc'.

Where is it? its not in `$datapath/geth.ipc`, but when do the following it works.

    $ geth.exe attach ipc:\\.\pipe\geth.ipc
    instance: Geth/v1.0.1/windows/go1.4.2
    datadir: eth
    coinbase: null
    at block: 0 (1970-01-01 00:00:00)
    modules: admin:1.0 db:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 shh:1.0 txpool:1.0 web3:1.0
    >

Where is the `geth.ipc` file on a windows filesystem, relative to `$datadir`?

**Comment by d11e9** [comment]
Wow: 

    web3.setProvider( new web3.providers.IpcProvider( '\\\\.\\pipe\\geth.ipc' ) )
                                                        ^^^^^

Works now, but I'd like to understand where this file is, I can't find it.

**Comment by fjl** [comment]
It is a named pipe. There is no file.

![](http://1.bp.blogspot.com/_0cx5gWLKLDM/SxLg3VA7-QI/AAAAAAAAA7g/OIplqzGwkR0/s1600/there-is-no-spoon-matrix.JPG)

**Comment by fjl** [comment]
See [Wikipedia](https://en.wikipedia.org/wiki/Named_pipe#In_Windows) for more information.

**Comment by d11e9** [comment]
haha thanks :O
