### ISSUE TITLE
expose Solidity compilation error message

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#1598]
when compiling solidity code, `web3.eth.compile.solidity(source)` doesn't expose the error message; instead it only returns:
```
{"id":4,"jsonrpc":"2.0","error":{"code":-32603,"message":"solc error: exit status 1"}}
```

For development purposes it would be most useful to also return the actual error message from `stderr`; as they are returned when calling the compiler from the CLI:
```
$ solc app/contracts/simple_storage.sol
app/contracts/simple_storage.sol:12:17: Parser error: Expected primary expression.
    storedData =* 2;
                ^
```

**Comment by tgerring** [comment]
+1

**Comment by obscuren** [comment]
@zelig please look in to this

**Comment by zelig** [comment]
fixed in https://github.com/ethereum/go-ethereum/commit/79b644c7a35bbc835b7e78ddf8a31c37e69b0784
