### ISSUE TITLE
can't see trezor testnet account(m/44/1/0/0) in geth

### ISSUE THREAD

**Issue by leochan007** [ethereum/go-ethereum#15986]
when using "personal.listWallets" in geth console,
only can see the FIRST mainet account (m/44/60/0/0) , actually there is plenty of account in m/44/60/0/0 and m/44/1/0/0.

and can't open wallet with URL shown for account 1.

OS: mac os.

**Comment by karalabe** [comment]
We only auto-derive accounts from the canonical derivation path. If you want to derive from a different path, you'd need to manually call `personal.deriveAccount(wallet, path, persistent)`, where `persistent` is a boolean flag specifying whether the account should from now on be listed in `eth.accounts`, or whether to just derive, return and forget.

**Comment by leochan007** [comment]
@karalabe thx for your advice. but what does wallet and path look like?  
wallet -> 0x aaaaa (pub address)?
path . -> . ???  i am not sure.
it seems that the url in listWallets is quite complex.


when i execute these commands in geth console:
personal.deriveAccount("0x2AC91344e9F023954Dfe88eFD5F7770dB85eAbA3", "m/44'/1'/0'/0/0", true)
Error: protocol scheme missing
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

> personal.deriveAccount("0x2AC91344e9F023954Dfe88eFD5F7770dB85eAbA3", "trezor://14110000,0/m/44'/1'/0'/0/0", true)
Error: protocol scheme missing
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

> personal.deriveAccount("0x2AC91344e9F023954Dfe88eFD5F7770dB85eAbA3", "trezor://m/44'/1'/0'/0/0", true)
Error: protocol scheme missing
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

**Comment by leochan007** [comment]
@karalabe thx for your help. it works now!
