### ISSUE TITLE
why i got this?

### ISSUE THREAD

**Issue by GopherJ** [ethereum/go-ethereum#15981]
Your account has been flagged.
Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.

thanks for your help!

**Comment by veox** [comment]
Where are you getting this? How is this related to `go-ethereum`?..

**Comment by GopherJ** [comment]
Sorry, It's beacause of `github`, which shows I should post an issue here, but It has been solved by github.

thanks.

**Comment by ligi** [comment]
if it is solved - can you please close this issue here to keep things clean.
Would also really love to see a screenshot with the message that an issue here should be created out of curiosity.

**Comment by GopherJ** [comment]
I didn't take a screenshot...

**Comment by WalterBoles** [comment]
0xce999cb9ecb6e090faf0bfd03f810d6c8e589474

**Comment by ligi** [comment]
@GopherJ too bad - thanks for closing the reply anyway
@WalterBoles ?

**Comment by WalterBoles** [comment]
I’ve tried just send a couple if it works I’ll lets you know thatnks

**Comment by WalterBoles** [comment]
O well thanks for trying

**Comment by WalterBoles** [comment]
Yes it did thanks

**Comment by WalterBoles** [comment]
Thanks what do I owe you

**Comment by zixuan75** [comment]
I solved with contacting GitHub.
I got a email and it is unflagged.
Now it is completely gone:
![screenshot-2018-2-6 build software better together](https://user-images.githubusercontent.com/33987311/35877459-5053b80c-0b43-11e8-92de-435dd067bfdf.png)
Good.

**Comment by zixuan75** [comment]
I've opened an nonsentical pull request that has been closed. Then have a red icon:
> Your account has been flagged.
> Because of that, your profile is hidden from the public. If you believe this is a mistake, contact > support to have your account status reviewed.
If I contact the GitHub, then it is gone.

**Comment by zixuan75** [comment]
@GopherJ Are you solved this problem with contacting GitHub?

**Comment by zixuan75** [comment]
Last time I do not close pull requests. On a few days, I see this red icon and I can't close it.
If I contacted GitHub, then it is gone.
I think when I received a email, then it should be gone. When I contacted GitHub but I don't received my email, it is gone.

**Comment by zixuan75** [comment]
So what is the problem we should solve?
