### ISSUE TITLE
why the return eth.getTransactionCount decrease

### ISSUE THREAD

**Issue by wcw84** [ethereum/go-ethereum#15994]
Hi there,

#### System information
Geth
Version: 1.7.2-stable
Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9

I am trying to send about 50 transactions from one account to other accounts sequentially, i have set nonce to "web3.eth.getTransactionCount(myaddress, 'pending') in every transaction before call sendTransaction.
My test in ropsten net is fairly well, but got error in main net:
_Error: Returned error: replacement transaction underpriced_
And I also notice that in the geth console, the return of getTransactionCount just dropped, i guest that maybe the problem.
![image](https://user-images.githubusercontent.com/7152596/35569998-ca99d9ba-0608-11e8-96d4-b8f6ff7b6ef6.png)
And now, at this time I am writing this issue, the largest nonce is 629 in a pending transaction in etherscan([here](https://etherscan.io/tx/0x7e2348db85a288989fa99c496c4ec74ccfeff04d8c3469d45bb05cce5c303bf8)),
![image](https://user-images.githubusercontent.com/7152596/35570848-531786fa-060b-11e8-943e-4d7c3ff6781a.png)

 but the largest nonce in my geth node(which i am sure is update to the newest) is 592:
_> eth.getTransactionCount('0x2592a20db4c16c89b08e301792953911c4751d7f', 'pending')
592_

I just don't know how to explain this, and not sure if this is a bug, especially the same run fairly well in ropsten testnet.
Any help will be very appreciated.

**Comment by wcw84** [comment]
@karalabe Thanks. Do you means that call getTrsansactionCount once before send all my transactions, and then ++myNonce after each sendTransaction?

**Comment by WalterBoles** [comment]
How’s that

**Comment by WalterBoles** [comment]
Are they in my account

**Comment by WalterBoles** [comment]
Just make sure that he’s good for it

**Comment by WalterBoles** [comment]
So I getting notifications across the hole blockchain that where I got in the right before th split fork
