### ISSUE TITLE
How to force a fixed difficulty?

### ISSUE THREAD

**Issue by soloist624** [ethereum/go-ethereum#15998]
Hi there,

there are some suggestions on forums to make difficulty fixed by modifying function ```calcDifficultyHomestead```located in ```\core\blockValidator.go``` and build the source code again. but in current source there is no sign of the function (and some other functions) in the file.

so, what to do now?
thanks inadvance

#### System information

Geth version: `1.7.3`
OS & Version: Windows

**Comment by RichHorrocks** [comment]
[Note that this isn't an issue for the issue tracker - you'd be best to ask this on [Stack Exchange](https://ethereum.stackexchange.com).]

We're not in Homestead anymore. And the code has been moved around. 

You want `calcDifficultyByzantium()` in [`consensus.go`](https://github.com/ethereum/go-ethereum/blob/924065e19d08cc7e6af0b3a5b5b1ef3785b79bd4/consensus/ethash/consensus.go#L304
).

**Comment by soloist624** [comment]
thanks for your fast response and sorry if I asked my question in an irrelevant place

I modified ```calcDifficulty()``` , ```calcDifficultyByzantium()``` , ```calcDifficultyHomestead()``` and ```calcDifficultyFrontier()``` to return ```big1``` . now difficulty grows far slower but still grows (after mining about 1400 ether difficulty is about 260). how to complitely fix it?


I have a separate problem, too:
I have set gasPrice to zero using ```miner.setGasPrice(0)``` in geth console but still command ```eth.gasPrice``` returns diffault 18000000000 value so I have no way to send ether in my ethereum wallet gui with total cost of sent ether.


what's different between ```miner.setGasPrice(0)``` and ```eth.gasPrice``` and what should I do?

**Comment by zscole** [comment]
Interested in finding an answer to this as well.

**Comment by rakibgalib** [comment]
@soloist624 did you find the solution? i am also trying to completely static difficulty increment

**Comment by prashantprabhakar** [comment]
I can confirm. Have changed the difficulty in
```
func (ethash *Ethash) CalcDifficulty(chain consensus.ChainReader, time uint64, parent *types.Header) *big.Int {
	return big.NewInt(1)
}
```
Still difficulty is constantlt increasing. To be 200% sure I added  `return big.NewInt(1) ` at end of all these functions 
> calcDifficultyByzantium
> calcDifficultyHomestead
> calcDifficultyFrontier

But still difficulty is not a constant value.
