### ISSUE TITLE
Mac Brew Installation is flawed.

### ISSUE THREAD

**Issue by UncleRic** [ethereum/go-ethereum#15999]
The following is what I've received when attempting to install Ethereum on my MacBook Pro:

==> Cloning https://github.com/ethereum/go-ethereum.git
Cloning into '/Users/Ric/Library/Caches/Homebrew/ethereum--git'...
remote: Counting objects: 2474, done.
remote: Compressing objects: 100% (2183/2183), done.
remote: Total 2474 (delta 314), reused 1485 (delta 165), pack-reused 0
Receiving objects: 100% (2474/2474), 8.39 MiB | 914.00 KiB/s, done.
Resolving deltas: 100% (314/314), done.
Note: checking out '4bb3c89d44e372e6a9ab85a8be0c9345265c763a'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

==> Checking out tag v1.7.3
==> go env
==> make all
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum/ethereum.rb:49:in `plist'
Please report this to the ethereum/ethereum tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum/ethereum.rb:49:in `plist'
Please report this to the ethereum/ethereum tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum/ethereum.rb:49:in `plist'
Please report this to the ethereum/ethereum tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum/ethereum.rb:49:in `plist'
Please report this to the ethereum/ethereum tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum/ethereum.rb:49:in `plist'
Please report this to the ethereum/ethereum tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum/ethereum.rb:49:in `plist'
Please report this to the ethereum/ethereum tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum/ethereum.rb:49:in `plist'
Please report this to the ethereum/ethereum tap!

**Comment by fjl** [comment]
The warning is fixed now. Note that you can also use the `geth` formula from homebrew-core.
