### ISSUE TITLE
geth --testnet account new creates address with invalid checksum

### ISSUE THREAD

**Issue by quantumproducer** [ethereum/go-ethereum#15991]
#### System information

Geth version: 1.7.2-stable
OS & Version: OSX

#### Expected behaviour

Creating a testnet account gives a valid address with a valid checksum.

#### Actual behaviour

geth --testnet account new returned d060fa165f3ff5f506c5391aa07bc57599d053c7 . truffle compalins this is an invalid address. Checking on block explorer shows  
https://ropsten.etherscan.io/address/0xd060fa165f3ff5f506c5391aa07bc57599d053c7  -- -- different capitlization and a valid checksum. 0xd060fa165F3FF5f506C5391AA07BC57599d053C7

**Comment by nkashy1** [comment]
I have run into this, as well. It is related to [EIP 55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md).

Although the EIP was accepted (*when* was it accepted, though?), `geth` itself doesn't seem to generate public keys conforming to the format of that proposal.

**Quick and dirty solution to your problem:** Run any addresses returned by `geth --testnet account new` through the Javascript `toChecksumAddress` implementation given in the EIP.
