### ISSUE TITLE
Deploy contracts on main net without full blockchain sync

### ISSUE THREAD

**Issue by jaumevn** [ethereum/go-ethereum#16005]
Hello, I have successfully deployed a few smart contracts on the rinkeby testnet using truffle and geth, all good. Now I'm trying to deploy the smart contracts on the main net, but can't sync the blockchain, it always freezes on the last ~100 blocks. Is there any way to make it fully sync so I can deploy my contracts? It is necessary to have the hole blockchain updated to deploy smart contracts, isn't it?

I've tries almost all methods described here in many issues about sync fail.

Thanks.

#### System information

Geth version: `geth 1.7.3`
OS & Version: OSX

#### Expected behaviour
Fully sync

#### Actual behaviour
Freezes on the last blocks.

**Comment by rafaelosirs** [comment]
the only appears way is deploy with myetherwallet in the contract tab and do it copiyng and pasting the byte code of your smart contract
