### ISSUE TITLE
Running geth 2 times

### ISSUE THREAD

**Issue by Marow** [ethereum/go-ethereum#16019]
Hi, i want to run geth at 2 times with 2 Wallets.

But when i already running geth on first and will start it on 2. I get this Error

`Fatal: Could not open database: resource temporarily unavailable`

**Comment by RichHorrocks** [comment]
You can't run more than one Geth instance that points to the same resources in the background.

See [this](https://ethereum.stackexchange.com/questions/2116/fatal-could-not-open-database-resource-temporarily-unavailable) previous Stack Exchange thread. (And [this](https://ethereum.stackexchange.com/questions/9108/geth-testnet-errorcould-not-open-database) one.)

**Comment by karalabe** [comment]
You need to point the two instances to different `--datadir`s and also different `--port`s.
