### ISSUE TITLE
Fatal: extra db err: leveldb/storage: corrupted or incomplete CURRENT file

### ISSUE THREAD

**Issue by actuallymentor** [ethereum/go-ethereum#1601]
What I did:

Download geth 1.0.1
Put gets in the chocolatey\geth-stable\tools folder

What happened:

Geth/eth pair mining setup worked fine for a while
Computer crashed (full freeze, no BSOD)
Upon restart trying to run geth any way gives a "Fatal: extra db err: leveldb/storage: corrupted or incomplete CURRENT file"

The contents of the CURRENT files in C:\Users\Mentor\AppData\Roaming\Ethereum\* is: "0000 0000 0000 0000 0000 0000 0000 0000"

EDIT: OS Windows 8.1, AMD r9 290, git bash console, previous crashes without repercussions occurred when geth+eth mining.

**Comment by fjl** [comment]
Your database is corrupted. You can fix this issue by removing the databases and syncing again.

**Comment by fjl** [comment]
Just delete the `blockchain`, `state` and `extra` folders in your datadir.

**Comment by actuallymentor** [comment]
Issue solved.

May I suggest adding this to the error? Or make deleting these folders part of the 'geth recover' protocol?

**Comment by fjl** [comment]
`geth recover` can recover some errors, but not this kind. We can't really detect this. It doesn't happen very often.

**Comment by stbregeon** [comment]
Hi,
may you say me where are  the blockchain, state and extra folders ? what are the directories ? 
tanks

**Comment by bas-vk** [comment]
The exact location is OS dependent and can be overwritten if you specify a custom datadir. You can see where the default location is with `geth -h` and check the default value for the datadir flag.

Keep in mind that this datadir directory also contains the keystore for mainnet and testnet. If you want to keep these keys don't delete the keystore sub-directories (each net has its own keystore).

The safest way to delete data and keep keys is to run `geth removedb`. This asks you what to remove but leaves the keystore intact.

**Comment by stbregeon** [comment]
ok 
i will be care
tanks a lot

**Comment by ijunaid8989** [comment]
@actuallymentor hello, out of interest how you resolved that issue?

**Comment by actuallymentor** [comment]
@ijunaid8989 please see @fjl's answer.

**Comment by ijunaid8989** [comment]
@actuallymentor Actually, I am not using `geth`, I am using the only leveldb and my manifest and LDB files are corrupt.
