### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by tatami01** [ethereum/go-ethereum#16016]
Hi there,
why i balance 0 when i have followed the water drop with this address whether this address has not been registered or how
0xae341c6E1661390F035a431Bf20b80440f08E0d3

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of the real issues. So please close this issue. Thanks!

PS: also please try to put more detail in your question - this way I think nobody can answer it - not even on stackexchange
