### ISSUE TITLE
Better sync progress report 

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/go-ethereum#16021]
It would be really awesome if we could have a better stateTrie syncing estimation. That splits into two needs:
1. Persist the number of imported entries 
1. Rough estimation of total entries (at least from the account trie)

This issue suggests the implementation of the first bullet.

#### System information

Geth version: `all versions`
OS & Version: `All OSes`
Commit hash : `-`

#### Expected behaviour

```
> eth.syncing.pulledStates
resulting in: savedStates + statesSyncedInThisSession
```

#### Actual behaviour

It currently resets the `pulledStates` to those synced in the current sync session.

```
> eth.syncing
{
  currentBlock: 5025380,
  highestBlock: 5035893,
  knownStates: 8085,
  pulledStates: 646,
  startingBlock: 5025259
}
```

**Comment by jeffywu** [comment]
Also would like to add another feature, currently impossible to tell if the fast sync has been disabled or not. I've sync'd all the block headers and transaction receipts but the state sync is still running. I'm sure lots of people are having this problem. When geth crashes its starts all over again, not sure what's happening but having a better report would make it a lot easier to figure out.

Is there any way to expose the "mode" flag set on the NewProtocolHandler? I think that might help.
https://github.com/ethereum/go-ethereum/blob/master/eth/handler.go#L117

**Comment by karalabe** [comment]
@jeffallen It doesn't start over, it continues where it left off, but it doesn't maintain a counter across restarts.
