### ISSUE TITLE
[1.8.0] Fast sync gets disabled when mining is started

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#16027]
If the node is started with mining enabled (e.g. puppeth signers), fast sync is apparently semi-immediately disabled. As long as the running sync is not interrupted this is not a problem, but the first reorg will actually drop everything down to block 0. This needs to be fixed before the 1.8.0 release.

**Comment by zixuan75** [comment]
`go-ethereum`

**Comment by Il8118lI** [comment]
Go eth
