### ISSUE TITLE
Geth 1.0.1 "fd usage" message in console isn't suppressed by admin.verbosity(0)

### ISSUE THREAD

**Issue by klmoney** [ethereum/go-ethereum#1602]
The new "fd usage" message won't turn off even when verbosity is set to 0. Seems like maybe it should be.

**Comment by obscuren** [comment]
We require this for a particular bug. It will be removed once caught. Sorry for the inconvenience :)

**Comment by klmoney** [comment]
Thanks for the clarification @obscuren.
