### ISSUE TITLE
geth fast sync stop at 99%

### ISSUE THREAD

**Issue by jackoelv** [ethereum/go-ethereum#16028]
geth --fast
> eth.syncing
{
  currentBlock: 5039722,
  highestBlock: 5039934,
  knownStates: 2033906,
  pulledStates: 2024105,
  startingBlock: 4974957
}

It stoped here for a long time .

the console like this:
INFO [02-06|16:39:00] Imported new state entries               count=1152 elapsed=4.069ms   processed=2226387 pending=15076 retry=2   duplicate=1042 unexpected=1578
INFO [02-06|16:39:02] Imported new state entries               count=2304 elapsed=9.031ms   processed=2228691 pending=13864 retry=2   duplicate=1042 unexpected=1578
INFO [02-06|16:39:05] Imported new state entries               count=2304 elapsed=9.679ms   processed=2230995 pending=12219 retry=2   duplicate=1042 unexpected=1578
INFO [02-06|16:39:06] Imported new state entries               count=1152 elapsed=4.678ms   processed=2232147 pending=13296 retry=2   duplicate=1042 unexpected=1578
INFO [02-06|16:39:08] Imported new state entries               count=1536 elapsed=9.296ms   processed=2233683 pending=13575 retry=2   duplicate=1042 unexpected=1578
INFO [02-06|16:39:10] Imported new state entries               count=2304 elapsed=11.538ms  processed=2235987 pending=12008 retry=0   duplicate=1042 unexpected=1578
INFO [02-06|16:39:12] Imported new state entries               count=1536 elapsed=7.849ms   processed=2237523 pending=12503 retry=2   duplicate=1042 unexpected=1578
INFO [02-06|16:39:14] Imported new state entries               count=1152 elapsed=6.800ms   processed=2238675 pending=13497 retry=2   duplicate=1042 unexpected=1578
INFO [02-06|16:39:16] Imported new state entries               count=2304 elapsed=10.636ms  processed=2240979 pending=12056 retry=2   duplicate=1042 unexpected=1578

Cound u help me? what happened here? How to solve the problem, thanks much.

geth on mac version:

Geth/v1.7.3-stable/darwin-amd64/go1.9.2

**Comment by jackoelv** [comment]
That is the solution, I just need waiting until it finish, right?


karalabe commented 2 days ago:

That's not an issue. That is how it works. The state trie currently is 70+M entries. You need to wait it out until all of those are downloaded.
--

**Comment by tntzho** [comment]
The same here. I used geth to sync blocks start before 3 weeks. At present,still not finish.
os:ubuntu 16.04 amd64
geth:1.7.3-stable-4bb3c89d
go:1.9.2

**Comment by larcai** [comment]
+1

**Comment by holiman** [comment]
There are issues in the current release which may cause sync to 'lock up' in certain conditions. This should now be fixed on master, and in the upcoming release. 

I'll close this as (we believe) it's fixed. Please report issues if you find them with the current master, or when we've released 1.8.0.
