### ISSUE TITLE
SIGBUS: bus error code=0x2 in consensus/ethash.generateDataset.func2

### ISSUE THREAD

**Issue by 9607835** [ethereum/go-ethereum#16033]
It used to at least startup but fail to mine (I noticed all the CPU time was being spent waiting for IO).... then I deleted the ~/.ethash directory (located in AppData in windows/cygwin fyi) and started over.
Now when I run a second instance of geth on a different data directory I get a SIGBUS error, everytime reliably.  However if the DAG has finished generating then I am able to start a second instance (not that it matters since the first instance is already using 99% of the CPU waiting for IO at that point...)

I don't have any fancy drive setup like fuse zfs-fuse encfs etc...
no errors in /var/log/{messages,secure,...}

#### System information

Geth version:
  Geth
  Version: 1.8.0-unstable
  Git Commit: b06e20bc7c498adef658b58f10f5c729b46d84f9
  Architecture: amd64
  Protocol Versions: [63 62]
  Network Id: 1
  Go Version: go1.8.3
  Operating System: linux
  GOPATH=
  GOROOT=/usr/lib/golang

OS & Version: Linux

#### Expected behaviour

continue without error after starting second instance since there should be no communication between the two instances (the bootnode server is not running)

#### Actual behaviour

unexpected fault address 0x7f6ae2b50288
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f6ae2b50288 pc=0x4706ac]

goroutine 142 [running]:
runtime.throw(0x101593a, 0x5)
        /usr/lib/golang/src/runtime/panic.go:596 +0x95 fp=0xc420c7ce48 sp=0xc420c7ce28
runtime.sigpanic()
        /usr/lib/golang/src/runtime/signal_unix.go:287 +0xf4 fp=0xc420c7ce98 sp=0xc420c7ce48
runtime.memmove(0x7f6ae2b50288, 0xc423e8cd40, 0x40)
        /usr/lib/golang/src/runtime/memmove_amd64.s:188 +0x66c fp=0xc420c7cea0 sp=0xc420c7ce98
github.com/ethereum/go-ethereum/consensus/ethash.generateDataset.func2(0xc424288060, 0x3ffff880, 0x1, 0xc422600000, 0x3fffb0, 0x3fffb0, 0x0, 0x7f6ae0000008, 0x3ffff880, 0x3ffff880, ...)
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:275 +0x1f4 fp=0xc420c7cf58 sp=0xc420c7cea0
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420c7cf60 sp=0xc420c7cf58
created by github.com/ethereum/go-ethereum/consensus/ethash.generateDataset
        /root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:281 +0x3ad

#### Steps to reproduce the behavior

(I haven't installed bootnode yet so that wasn't running on this linux machine)

cd ~/ethereum
mkdir ~/ethereum/ethereum1;
geth --datadir="ethereum1" init genesis.json;
nice geth --cache=64 --networkid=435343 --datadir="ethereum1" -verbosity 3 --port 30302 --rpcport 8102 --rpcaddr "0.0.0.0" --rpccorsdomain "..." --ipcdisable --bootnodes "`cat boot.url`" --etherbase="0xc8164a7b5e194509412939961f858a2f966b0007" --minerthreads=1 --mine console 2>ethereum1.log;

[open second terminal]
cd ~/ethereum
mkdir ~/ethereum/ethereum2;
geth --datadir="ethereum2" init genesis.json;
nice geth --cache=64 --networkid=435343 --datadir="ethereum2" -verbosity 3 --port 30303 --rpcport 8103 --rpcaddr "0.0.0.0" --rpccorsdomain "..." --ipcdisable --bootnodes "`cat boot.url`" --etherbase="0xc8164a7b5e194509412939961f858a2f966b0007" --minerthreads=1 --mine console 2>ethereum2.log;

#### Backtrace

[ethereum1.log](https://github.com/ethereum/go-ethereum/files/1704695/ethereum1.log)

**Comment by karalabe** [comment]
Mining requires a 1+GB dataset to be generated on disk. If you start to Geth instances of the same machine, enabling both to mine, they will try to use the same file, overwriting each other's stuff. Geth does have a configuration to put the `--ethash.dataset` on a different folder for one of the instances, but why would you want to run 2 miners on a single host?
