### ISSUE TITLE
RPC http Connection Refused

### ISSUE THREAD

**Issue by 9607835** [ethereum/go-ethereum#16034]
#### System information

Geth version: 
  Geth
  Version: 1.7.3-stable
  Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
  Architecture: amd64
  Protocol Versions: [63 62]
  Network Id: 1
  Go Version: go1.9
  Operating System: windows
  GOPATH=
  GOROOT=c:\go

Geth version for machine with the wallet program which shouldn't be used either way: 
  Geth
  Version: 1.7.3-stable
  Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
  Architecture: amd64
  Protocol Versions: [63 62]
  Network Id: 1
  Go Version: go1.9
  Operating System: windows
  GOPATH=
  GOROOT=c:\go

OS & Version: Windows

#### Expected behaviour

Accept connections from wallet.

#### Actual behaviour

ssh pipe reports: channel 2: open failed: connect failed: Connection refused
So obviously the wallet is correctly trying to connect, however, geth is NOT listening on the rpc port...
There are no networking errors from geth.
However there is a single instance of:
ERROR[...] Failed to generate mapped ethash dataset epoch=1 err="open C:\\cygwin\\home\\FU\\AppData\\Ethash\\full-R23-290decd9548b62a8.4606018198686923411: Access is denied."

#### Steps to reproduce the behaviour

$ geth --cache=64 --networkid=435343 --datadir="ethereum1" -verbosity 3 --port 30302 --rpcport 8102 --rpcaddr "0.0.0.0" --rpccorsdomain "..." --ipcdisable --bootnodes "`cat boot.url`" --etherbase="0xc8164a7b5e194509412939961f858a2f966b0007" --minerthreads=1 --mine console 2>ethereum1.log;

[from remote computer]
#also tried localhost:8102
$ ssh -i ....pem user@serverwithgeth.com -N -L 8102:127.0.0.1:8102
$ ./Ethereum\ Wallet.exe --rpc "http://localhost:8102"
[... blah blah ...]
[...] [ERROR] ClientBinaryManager - Sanity check failed for Geth Error: Unable to find "1.7.2" in Geth output
[... downloading new geth binary??? unexpected behavior to say the least ...]

[this is the point where I get this output from the ssh pipe from before]
channel 2: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused

**Comment by lmars** [comment]
I believe you need to set the `--rpc` flag to enable the HTTP RPC interface.

**Comment by holiman** [comment]
> I believe you need to set the --rpc flag to enable the HTTP RPC interface.

Correct.
