### ISSUE TITLE
Geth some questions. Very much need help for begginer!

### ISSUE THREAD

**Issue by pryan1check** [ethereum/go-ethereum#16030]
I learned about GETH a few days ago. I need Geth to create wallets of etherum and make transactions with these wallets (I use geth instead of third-party api to create some programs related to eth). I very much hope that you will help me understand the following:

 1. What are the minimum system requirements for geth? (for creating accounts, making transactions)
 2. Is it necessary to synchronize a blockchain for creating accounts, making transactions?
 3. If not, how does it work? How to make an account and transaction without synchronization?
 4. How do I know if the synchronization is complete?
 5. Will errors occur when synchronizing the blockchain if you accidentally disable geth? (server shutdown or geth process termination)
 6. If so, how can I check for errors in the synchronized blockchain?
 7. Are there any alternatives that have web3 access?
8. I have a server running with geth --fast --cache = 2048.   
 System: cpu amd athlon II x2 220, 4 GB ram, 500 gb hdd 5400 rpm, OS ubuntu 16.04 x64. 
 With such parameters, ram is loaded to 100%, + 1GB swap file of 4 GB. I tried to change the parameter --cache to 128, 256, 512, 1024 and even to 16 MB, but ram always get 100% loaded. Blockchain is synchronized for 6 days already, blockNumber still 0. 
 **Is this normal?** 

> *P.S. Sorry for my english, this is not my native language.*
> *P.P.S. If you know the answer to at least one question, please answer me.*

#### System information

Geth version: `1.7.3`
OS & Version: ubuntu 16.04 x64

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by RichHorrocks** [comment]
(Agree with ligi. For reference, this question has already been asked on Stack Exchange, [here](https://ethereum.stackexchange.com/questions/38801/geth-some-questions-need-help-for-begginer).)
