### ISSUE TITLE
geth stoped for a long time

### ISSUE THREAD

**Issue by jackoelv** [ethereum/go-ethereum#16031]
Hi there,

Bug reports:
geth seems stopping for hours, nothing to do.

when I typed eth.syncing, hours later, it always show the same number on the screen like this:

> eth.syncing
{
  currentBlock: 5045156,
  highestBlock: 5045303,
  knownStates: 18402705,
  pulledStates: 18395633,
  startingBlock: 5044100
}

hours later,

same number as it.

geth stopped here for a long time,why?

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: Geth/v1.7.3-stable/darwin-amd64/go1.9.2
OS & Version: Macos High Sierra 10.13.3 (17D47)
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ldanicel** [comment]
I ran across something similar... geth stopped synching the same way as above but I could still post transactions through it while this was happening.

I went frenzy into ^C^C^C to stop it and upon restart it recovered just fine.

The last ^C produced a stacktrace which I'm attaching here as geth.log.

Thanks
[geth.log](https://github.com/ethereum/go-ethereum/files/1709205/geth.log)

**Comment by jackoelv** [comment]
ok, when several days later, it gets work.
fast syncing finished last night.

INFO [02-09|01:33:48] Imported new block receipts              count=1    elapsed=2.992ms   bytes=52868    number=5052442 hash=4744c0…6bccd5 ignored=0
INFO [02-09|01:33:48] Committed new head block                 number=5052442 hash=4744c0…6bccd5
INFO [02-09|01:33:50] Fast sync complete, auto disabling 
 
so, just need more time, days, be patient.
thanks a lot.
