### ISSUE TITLE
I need help to find what happened with this transaction

### ISSUE THREAD

**Issue by ashishranas** [ethereum/go-ethereum#16032]
Hi there,

I transferred my ETH from bitbns to Kucoin wallet,. While though the Transaction # got generated, it never got broadcasted to ETH network. 

https://etherscan.io/tx/0xae3820152a0f9c05b6fe549ced9515c4649546f27f0d9cad3d81cf325d3a1b85

I have also tried tracing the transaction, but seems have no luck. 
https://etherscan.io/vmtrace?txhash=0xae3820152a0f9c05b6fe549ced9515c4649546f27f0d9cad3d81cf325d3a1b85

Please advice, thanks!
----------------------
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
