### ISSUE TITLE
Freshly restarted geth hung randomly

### ISSUE THREAD

**Issue by ldanicel** [ethereum/go-ethereum#16049]
Geth was started like this:

geth --cache 4096 --rpc --rpcaddr 0.0.0.0 --rpccorsdomain chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn,chrome-extension://nlbmnnijcnlegkjjpcfjclmcfggfefdm,https://myeth.mydomain.com --ws --wsaddr 0.0.0.0 --wsport 8547 --wsorigins '*'

It was already in sync with the main eth network.

Geth stopped synching ( new tokens and eth balances were not showing up ) but I could still post transactions through it while this was happening.

I went frenzy into ^C^C^C to stop it and upon restart it recovered just fine - synched the few blocks up to the latest block.

The last ^C produced a stacktrace which I'm attaching here as geth.log.

Thanks
geth.log

Version: 1.7.3-stable-4bb3c89d
OS: Debian stretch kernel 4.9.0-5-amd64
[geth.log](https://github.com/ethereum/go-ethereum/files/1711221/geth.log)

**Comment by karalabe** [comment]
Unfortunately this was only the end of the stack trace, the top is the interesting part. Leveldb sometimes does a compaction round which can take a few minutes depending on how much data you allow it to cache before writing to disk (4GB is quite a lot). My best guess is that compaction hit and it would have recovered eventually on its own.

If this happens again, try waiting 5-10 mins to see if it revives. Not saying that this is a "nice feature", just that it would be useful to know if its leveldb or something else.
