### ISSUE TITLE
unstopable growing difficulty

### ISSUE THREAD

**Issue by soloist624** [ethereum/go-ethereum#16041]
Hi there,

I have modified ```calcDifficulty()``` , ```calcDifficultyByzantium()``` , ```calcDifficultyHomestead()``` and ```calcDifficultyFrontier()``` to return big1 . now difficulty grows far slower but still grows (after mining about 1400 ether difficulty is about 260). how to complitely fix it?

I have a separate problem, too:
I have set gasPrice to zero using miner.setGasPrice(0) in geth console but still command eth.gasPrice returns diffault 18000000000 value so I have no way to send ether in my ethereum wallet gui with total cost of sent ether.

what's different between miner.setGasPrice(0) and eth.gasPrice and what should I do?

**Comment by karalabe** [comment]
If you want an easy chain, use a PoA one, not PoW. Then you don't have to care about difficulties and whatnot. If you only need to run on a single machine you can use `geth --dev`. This uses ephemeral datadirs and accounts, but you can make them persistent via specifying `--datadir /path/to/your/data`.

`eth.gasPrice` is a suggestion based on the past transaction prices. If all the transactions you made were prices like that, it won't suggest anything lower. Send a bunch of 0 prices transactions manually and it should pick it up. Though take case, Geth by default rejects forwarding 0 priced transactions to prevent DoS attacks.

**Comment by soloist624** [comment]
I should use network in usual way (as others use) because an instance is going to run somewhere else by somebody other than me, so I should modify source code

**Comment by karalabe** [comment]
You can still run a PoA chain instead of PoW. Just add to your `config` field in the genesis json:

```
"clique": {
	"period": 15
}
```

**Comment by soloist624** [comment]
sorry but I can't get the point
I'm complitely new to this field

**Comment by adolfdsilva** [comment]
@soloist624 ... I think you want to setup a private network... Read [here](http://blog.enuma.io/update/2017/08/29/proof-of-authority-ethereum-networks.html)...

**Comment by xindebug** [comment]
@karalabe how to run a PoA cha in without gascost ?
