### ISSUE TITLE
"fdtrack.go:109] fd usage" can not be silenced 

### ISSUE THREAD

**Issue by blackout24** [ethereum/go-ethereum#1605]
Hello,

I'm running 'Geth/v1.0.1-82ef26f6/linux/go1.4.2' and with 1.0.1 the output is populated with:
I0806 21:30:01.130594    3067 fdtrack.go:109] fd usage 106/4096, tracked 91 [ipc:1 leveldb:55 p2p:34 rpc:1]

messages even if I set verbosity to 1. With 1.0.0 I didn't see these messages at all.

Regards

**Comment by 21xhipster** [comment]
The same even with verbosity 0. Both Ubuntu and OS X

**Comment by blackout24** [comment]
0 dosn't even exist as an argument.
https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#adminverbosity

1 is silent -> 6 is detail.

**Comment by tgerring** [comment]
This is a diagnostic message only and will be removed from Geth soon.

@obscuren @fjl Any timeline on updating this message?

**Comment by obscuren** [comment]
Will be removed in `1.0.2`

**Comment by tgerring** [comment]
Duplicate of #1605
