### ISSUE TITLE
Blocks syncing extremely slowly. and yes... I already used --fast and increased cache

### ISSUE THREAD

**Issue by jcklpe** [ethereum/go-ethereum#16058]
#### System information

Geth version: `1.6.6`   (I downloaded using Mist etc and started using the CLI after mist kept stalling)
OS & Version: Windows
Commit hash : (if `develop`)

Speedtest results:

Up: 94
Down: 91
ping: 22

**Comment by ligi** [comment]
Why are you using such an old geth version?

**Comment by brianweber13** [comment]
having similar issues on geth 1.8.1 on fedora 27.... any other related issues?

I've left geth syncing for days. I tried fast for a while, then full, then light, then full again. eth.blockNumber is always 0, and my accounts show a balance of zero even though I can see my correct, non-zero balances on etherchain.org

**Comment by danmerino** [comment]
@brianweber13 I made a ticket for this specifically. https://github.com/ethereum/go-ethereum/issues/16147

**Comment by holiman** [comment]
Please check my comment here: https://github.com/ethereum/go-ethereum/issues/16053#issuecomment-365524053 , and provide some more data to make it possible to determine the cause for this.
