### ISSUE TITLE
Geth taking ages to sync on m5.4xlarge EC2 - sustainable?

### ISSUE THREAD

**Issue by hynese** [ethereum/go-ethereum#16064]
#### System information

Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux (Ubuntu 16.04)
GOPATH=
GOROOT=/usr/lib/go-1.9

#### Expected behaviour
Sync in reasonable amount of time
On an Amazon `m5.4xlarge` instance

#### Actual behaviour
Still syncing after about 6 hours...
```
> eth.syncing
{
  currentBlock: 5071336,
  highestBlock: 5071572,
  knownStates: 60220021,
  pulledStates: 60199988,
  startingBlock: 0
}
>
```
```
> eth.blockNumber
0
> 
```

60 million `pulledStates`, really?

#### Steps to reproduce the behaviour
Download latest version of geth
`geth --syncmode "fast" console 2>>~/geth.log`

**Comment by karalabe** [comment]
There are about 72-75M states.

**Comment by karalabe** [comment]
Just checked the instance types we've used during testing v1.8.0, it's `m4.2xlarge`. Geth 1.8 should be able to fast sync under 3 hours on that instance. At this point I would recommend against using 1.7.3, there are various known bugs that have been fixed already, and we're wrapping up the release of 1.8.0 anyway.

**Comment by hynese** [comment]
My `m5.4xlarge` did sync after several hours.

I sometimes wonder if there is a way to get some ETA reporting?

`1.8.0` looks awesome. Amazing work.

Looks like we now need bandwidth, IOPs and CPU power? i.e. my Macbook Pro (only 50GB of free space...) on my home broadband (17MB) won't really do it anymore?

I used to store the geth db on an external magnetic HD... A long time ago, alas...
