### ISSUE TITLE
Cost not updated at client side in flow control LES Protocol

### ISSUE THREAD

**Issue by OniReimu** [ethereum/go-ethereum#16067]
#### System information

Geth version: `geth 1.6.7`
OS & Version: Windows/Linux/OSX

#### Expected behaviour
1) fcCosts synced at both server and client.

2) bv sent back from server to client when sending SendTxMsg from client to server, in order to set BLE to this real bv.

#### Actual behaviour
1) It seems like the fcCosts at client side does not update via the GotReply message sent from server side. Note that GotReply only manipulate the buf stuffs but nothing to do with the fcCosts at client side.

2) In les/handler.go - handleMsg(), receiving a SendTxMsg does not involve a response sending back to client, which means client is not able to get the real bv.

#### More
1) The fcCosts should not only be updated when every handshaking during which server side calls les/server.go - getCurrentlist() and sends to client, but also being updated every time client receives GotReply() sent from server, otherwise every time client manages to send a request invoked no matter from - GetRequestCost() in light/txrelay.go  or les/odr.go, client always get the old costs. Unless the protocol does define as what it is, only the non-initial handshakes will update the fcCosts at client side while client disconnects and logs in again. 
Also from les/peers.go,  all sendRequest including SendTx have not involved the "cost" in the sending function even if some of them have this cost as a parameter. **It indicates that there seems no connection between the fcCosts at client and server side**. Then it turns out to be a weird issue, why do we need to have the fcCosts at client side? You keep it, but not use it when sending request, and no update when GotReply. Is that trivial? 

2) I am not pretty sure about the behaviour of receiving a SendTxMsg in les/handler.go. Server still calculates the real cost and updates its local fcCosts without sending any info back to client, contributing to client knowing nothing about the status of this request, and having nothing to do with its local bufEstimate. Would it matter if it is in this case?

**Comment by ligi** [comment]
Can you try with geth 1.7.3 ?

**Comment by karalabe** [comment]
I'd suggest going with master, not 1.7.3. We're wrapping up the release, so even 1.7.3 is mostly irrelevant now.

**Comment by OniReimu** [comment]
@ligi Ehh...our project forks from 1.6.7 and make lots of customization on each module. A couple of works are needed if we move to the latest version. But anyway, if master or 1.7.3 has solved the issue I will try to figure it out and add the release based on 1.6.7. If issues still exist, I will let you guys know, thx.

**Comment by ligi** [comment]
@OniReimu : great - closing this issue then - feel free to reopen if you still have the problem on master

**Comment by OniReimu** [comment]
@ligi ucot Australia, a very new IoT project with blockchain.
