### ISSUE TITLE
Light mode - cannot deploy contract (Error: no suitable peers available)

### ISSUE THREAD

**Issue by fabdarice** [ethereum/go-ethereum#16077]
Geth version: v1.8.0-unstable-8d32c4b9
OS & Version: OSX
Truffle Version : 4.0.6

#### Expected behaviour
Successfully deploying a contract into Ropsten network

#### Actual behaviour
Using truffle migrate, it currently fails to deploy any contract : Error: no suitable peers available

#### Steps to reproduce the behaviour
1) Install geth from master
2) run geth with light mode (build/bin/geth --testnet --rpc --rpcapi db,eth,net,web3,personal --syncmode=light --cache=1024 --rpcport 8545 --rpcaddr 127.0.0.1 --rpccorsdomain '*' --ipcpath ~/Library/Ethereum/geth.ipc)
3) truffle migrate --reset

#### Backtrace
````
Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: no suitable peers available
````

**Comment by ligi** [comment]
was just talking to @zsfelfoldi  - this should work - might just have been a lack of ropsten lightservers - he just started one - can you try again? Also can you try with rinkeby if it is not working?

**Comment by fabdarice** [comment]
@ligi @zsfelfoldi indeed, I don't see the 'Error no suitable peers available', however, it now get stuck at 'Replacing Migrations..' in truffle. Can't seem to deploy any contract in light mode still.

**Comment by prographo** [comment]
Same, right now.

**Comment by karalabe** [comment]
The issue here is that you don't currently have peers, so you can't really do anything until you get peers. We're always working on improving this situation, but at the end of the day, to do stuff with les, you need servers connected.
