### ISSUE TITLE
setInterval does not return a handle

### ISSUE THREAD

**Issue by brandoncurtis** [ethereum/go-ethereum#16078]
#### System information

Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.2
Operating System: linux (Ubuntu 16.04 x64)

#### Expected behaviour

```
> var handle = setInterval(function() {console.log("hello world\n");}, 10000);
```

`setInterval` should return a handle that can be used in `clearInterval`.

#### Actual behaviour

```
> var handle = setInterval(function() {console.log("hello world\n");}, 10000);
undefined
> handle
{}
```

#### Issues also dealing with `setInterval`

#1082, #1083, #1811, #1999,

**Comment by karalabe** [comment]
What would you like to do?

The console is not a full fledged JavaScript interpreter, rather a limited one based on `ottovm`. The `setInterval` and `setTimeout` methods were not supported by it and were added retrospectively by us. Although we could keep patching it, do you really need to use the console for such advanced features?

**Comment by brandoncurtis** [comment]
I think that's a compelling argument for documenting it and leaving it unfixed.  I wasn't familiar with the history of the console and its basis in `ottovm`.
