### ISSUE TITLE
Change excessive gas-limit error to be more user friendly

### ISSUE THREAD

**Issue by linagee** [ethereum/go-ethereum#1607]
Can someone please make this a friendlier error and/or explain to the user what this is and how to fix it? (even a simple: "are you missing the 'gas' variable?")

https://pay.reddit.com/r/ethereum/comments/3g3cx2/question_on_how_to_assign_gasprice_for_a/ctuhpif

("Exceeds block gas limit" error, adding "gas:" fixes it)

**Comment by abrkn** [comment]
It would be helpful to mention the block gas limit in the error message.

**Comment by frozeman** [comment]
The error is very clear (as the default 90 000 gas) exceeded the current 40 000.

Though we could definitely do better on the default gas price see #1609

**Comment by frozeman** [comment]
The new error is even less understandable:
```
GasLimit error. Max 90000, transaction would take it to 5000
```

What is this supposed to mean?
