### ISSUE TITLE
Windows: Wordwrap on Geth client breaks command line

### ISSUE THREAD

**Issue by jwhelan72** [ethereum/go-ethereum#1608]
The Windows Geth client has some major issues:

1) Word wrap at the right edge of the window breaks the command line
2) Cursor keys and insert/delete do not function at all

Geth for windows is essentially unusable for initiating transactions.

**Comment by fjl** [comment]
Which console do you use? (cmd, powershell, cygwin terminal etc.)

**Comment by jwhelan72** [comment]
CMD.

**Comment by Quiark** [comment]
I use Powershell inside ConEmu. Backspacing a character makes the input line jump 1 character to the right.

**Comment by obscuren** [comment]
I confirm this. I've the same issue

**Comment by fjl** [comment]
Will fix it.

**Comment by jwhelan72** [comment]
Any ETA on a fix?

**Comment by Loll3yz** [comment]
Experiencing the same problems right now

**Comment by fjl** [comment]
I'll try to get to it tomorrow (found no time for it‎ on the weekend).

**Comment by fjl** [comment]
The fix for command line editing is now available on the develop branch.

**Comment by jwhelan72** [comment]
Very cool.  Do you know if that is reflected in the automated Windows build?

**Comment by tgerring** [comment]
The builds look up-to-date: https://build.ethdev.com/builders/Windows%20Go%20develop%20branch

**Comment by Loll3yz** [comment]
Still having a problem with the word wrap in geth console, its cutting the start of the command off as I paste it in.

**Comment by jwhelan72** [comment]
I can confirm the following:

1) the cursor keys work
2) the insert/delete keys work
3) word wrap no longer breaks the command line

I do notice that after every command is issued the following error appears whenever a subsuquent command is entered: "The pipe is now closed".  This requires exiting out of Geth and restarting.  For whatever reason the connection to the attached console window does not seem to persist between commands.

**Comment by tgerring** [comment]
@jwhelan72 This may be addressed in https://github.com/ethereum/go-ethereum/pull/1652

**Comment by fjl** [comment]
Note that you can press Ctrl+D with empty input to exit the console.

**Comment by fjl** [comment]
@Loll3yz can you give me some steps to reproduce this? when you paste a long string into the console, it will be displayed on one line without wrapping. you should still be able to go to the beginning of the input using the cursor keys or `ctrl+a`.

**Comment by Loll3yz** [comment]
Yeah sure

1. geth console
2. Paste personal.unlockAccount("x0myaddress", "mypassword") 
3. When I paste and press enter immediately it cuts off the start of personal.unlock & returns error
4. When I paste but then use the cursors to check its its there and press enter its cuts off the password and returns an error.

Maybe Im just doing something wrong but this is the error I get.
![ethcmdline](https://cloud.githubusercontent.com/assets/13685722/9292068/70f654e8-43db-11e5-8743-ccfc2404901e.png)

**Comment by tgerring** [comment]
Accounts do not begin with "x0" but rather "0x". This is a standard convention for hexadecimal notation

**Comment by Loll3yz** [comment]
Oops, That was a typo. I'm still getting the same response though.  "Decryption Failed MAC Mismatch?"

**Comment by tgerring** [comment]
@jwhelan72 Is the original issue resolved? If so, feel free to close the issue :)
