### ISSUE TITLE
still no eth_listTransactions?

### ISSUE THREAD

**Issue by bonesoul** [ethereum/go-ethereum#16081]
https://github.com/ethereum/go-ethereum/issues/1897

you are still considering a suitable implementation for this - since 2 years?

**Comment by karalabe** [comment]
Not really. The only way to produce such a list is to reexecute all transactions (i.e. do a full sync). That's more and more unrealistic unless you have an insane hardware to throw at it. As Ethereum grows, this gets harder and harder to the point where I don't think anyone would be willing to do it.

You could always write a custom transaction tracer, or perhaps use the `callTracer` that's included in v1.8.0 to gather the infos you need. The proper alternative was always to use contracts and events (which are part of consensus, so they are available of fast sync nodes and light clients too).

**Comment by jdneidig** [comment]
Get the eth_listTransaction T-shirt :-)
https://simbachain.com/community/join-our-community/
