### ISSUE TITLE
whisperv6: bloom filter is not changed after user filter was unscubscribed

### ISSUE THREAD

**Issue by dshulyak** [ethereum/go-ethereum#16086]
What do you think about adding another ticker to `w.update` that will periodically rebuild bloom filter from currently "live" filters?

#### Expected behaviour
Bloom filter is changed at least periodically to reflect the current state of topics used by consumers filters.

#### Actual behaviour
Bloom filter is not updated when Unscubscribe is called. Which means that the node will be consuming unnecessary traffic, and the only way to get rid of it would be a restart of the whisper or re-create bloom filter from scratch.

#### Steps to reproduce the behaviour
See attached unit test.

**Comment by dshulyak** [comment]
@gluk @gballet

**Comment by gballet** [comment]
@dshulyak which attached unit test ?

**Comment by dshulyak** [comment]
@gballet this https://github.com/ethereum/go-ethereum/pull/16087 , it was referenced right after issue summary

**Comment by dshulyak** [comment]
I guess part of the problem is that even if bloom filter will be updated locally - how to notify a peer that filter should be completely changed and not just added to already known

**Comment by dshulyak** [comment]
@gballet please take a look at https://github.com/ethereum/go-ethereum/pull/16116 , imo it is suitable solution for described problem

**Comment by gballet** [comment]
Closing this issue as #16116 has been closed too
