### ISSUE TITLE
Improve default gasLimit

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#1609]
We should not use 90 000 gas as an arbitrary default gas, but rather estimate it internally before and add an extra 20 000?

This needs a fix for #1590 before

**Comment by fjl** [comment]
Please provide more detail on this one. Is this related to the gas price used when estimating gas usage?

**Comment by obscuren** [comment]
We shall not estimate internally (through running the contract) because it doesn't come free.

**Comment by fjl** [comment]
Ahh, it becomes clearer when looking at the linked issue.

**Comment by frozeman** [comment]
Estimation of gas price should only happen when i send a transaction, before you actually send it. So steps:

1. i send using eth.sendTransaction(...) and don't provide a gas amount.
2. you take that transaction and run it through the call/estiamteGas mechanism and get the used gas amount
3. you use this estimate + 20 000 gas as default

**Comment by frozeman** [comment]
Its very important that `eth_estimateGas` has no gas limit or other restrictions, as the sole purpose of this function is to estimate.

Its necessary for the wallet that we fix that asp, so i can give good estimates of required fees for their actions.

C

**Comment by maran** [comment]
:+1: 

I actually ran into this myself yesterday, the default gas was not enough to sent my transactions but it took me a few minutes to figure out this was the reason nothing happened.

**Comment by m-vdb** [comment]
Hi guys, I ran into this for the last couple of day. One of my contract methods takes way too much of gas (I need to figure out why) but in the meantime I'd like to raise the limit "artificially" (i'm on a private test network). Any idea if it's feasible?
