### ISSUE TITLE
Retain `--gcmode` setting across client restarts

### ISSUE THREAD

**Issue by konradkonrad** [ethereum/go-ethereum#16091]
#### System information

Geth version: `1.8.0-stable`
OS & Version: all

#### Expected behaviour
If a chain is synced in archive mode, i.e. `--gcmode archive`, once, this setting should be kept across client restarts, unless explicitly disabled.

#### Actual behaviour
The default value, `--gcmode full` takes precedence over the previous setting unless `--gcmode archive` is explicitly set on each consecutive restart.

**Comment by yxliang01** [comment]
Hmm. I think this suggestion makes sense. Think that this should be re-opened.
