### ISSUE TITLE
abigen doesn't add required "github.com/ethereum/go-ethereum/accounts/abi/bind" import to go output

### ISSUE THREAD

**Issue by coreyog** [ethereum/go-ethereum#16093]
#### System information

Geth version:
```
Geth
Version: 1.8.0-stable
Git Commit: 5f54075760748ae7f249bf735565924ea885c477
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.4
Operating System: linux
GOPATH=/home/corey/src/goprojects
GOROOT=/usr/local/go
```
OS & Version: Linux Mint 18.3 x64

#### Expected behaviour

Code generated by abigen should not require modification in order to build.

#### Actual behaviour

Code generated by abigen assumes that `"github.com/ethereum/go-ethereum/accounts/abi/bind"` is imported but it is not.

#### Steps to reproduce the behaviour

Use abigen. I ran `abigen -sol mycontract.sol -pkg mycontract -out mycontract.go` on two of my contracts. Both completed successfully except for the missing import.

#### Backtrace

Build error:
````
# cogburn/myproject/mycontract
mycontract/mycontract.go:45:12: undefined: bind
````

**Comment by karalabe** [comment]
You need to have go-ethereum in your GOPATH since the necessary packages are picked up automatically via `goimports`.

**Comment by coreyog** [comment]
I did but it must have still been 1.7.x instead of 1.8. I've run `go get -u`, rerun abigen, and see that it works.
