### ISSUE TITLE
fatal error: concurrent map read and map write. Raspberry pi 3 Model B

### ISSUE THREAD

**Issue by agatsoh** [ethereum/go-ethereum#16094]
I get the error while using  the light client feature of the latest geth 1.8.0 unstable release from the latest master inside the raspberry pi.

#### System information

Geth version: 
```
pi@raspberrypi:~ $ geth version
Geth
Version: 1.8.0-unstable
Git Commit: 0544a43c1332871405b260432db4bfe6a591feee
Architecture: arm
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.4
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

```
OS & Version: RASPBIAN STRETCH WITH DESKTOP OS

#### Actual behaviour
https://gist.github.com/agatsoh/96f45d7a27dd816c32c22ca02581eb4e

#### Steps to reproduce the behaviour
The raspberry pi needs to be installed with the RASPBIAN STRETCH WITH DESKTOP OS.
Install virtualenv virtualenvwrapper.

Install the go language. Go to https://golang.org/dl/ from there we need to download the armv6l version. On the raspberry pi

`wget https://dl.google.com/go/go1.9.4.linux-armv6l.tar.gz`

`sudo tar -C /usr/local -xzf go1.9.4.linux-armv6l.tar.gz`

Write below line in .bashrc and then do a source .bashrc

`export PATH=$PATH:/usr/local/go/bin`

Clone geth repository and then` make geth`

#### Backtrace
The stacktrace that I got can be found in this gist.

https://gist.github.com/agatsoh/96f45d7a27dd816c32c22ca02581eb4e

**Comment by karalabe** [comment]
Dang, thanks!
