### ISSUE TITLE
eth.sendTransaction generates dead contract instead of raising error

### ISSUE THREAD

**Issue by legkodymov** [ethereum/go-ethereum#16106]
In my script:
`eth.sendTransaction('0xFROM_ADDRESS',  null, amount)`
Instead of raising error, have sent all amount to hell. Here is what generated instead of doing transaction:
https://etherscan.io/tx/0x581b23337d023d40879e10cd94a138889b324c88e60158682febd3e19c1c27a5
Creating a contract (especially dead one) for sendTransaction is unacceptable, and should be solved somehow to more reasonable action.
Logging of my script is extensive, so I tracked every detail of this action. Here is piece of code executed:

    winston.log('info', "ETHSend: ", f, t, v);
    web3.eth.sendTransaction({from: f, to: t, value: web3.toWei(v, "ether")},
        function(err, result) {
            if (err) {
                winston.log('info', "ETHSend error: ", err, result);
                callback(null);
                return;
            }
            winston.log('info', "eth.sendTransaction: ", err, result);
            session.txids.push({Currency: 'ETH', Amount: v,
                CryptoAddress: t, TxId: result});
            callback(null);
        });

By the way, would some day be hardfork, so I recover my funds?

I've lost 56 ETH total, check following TxHashes:
0xaa2e6cc49535df058bcbd5ad153ff732b7540532a741dc0072822ea255b93748
0x1871d172e87c974eccbaf4844a3c6748480192420e91074a82d05b74383d08cf
0x2536d92cca7239c529413abe68b8a962bf35ab2c74c361f5974d117cf5b764f7
0xe92704ec8689ac0ad459a057f340e9a6177447f441346139d5c881d314a8e481
![zero_eth](https://user-images.githubusercontent.com/1641133/36278662-e68064bc-12ad-11e8-8af3-ad2eeb203bad.png)

instance=Geth/v1.7.2-stable-1db4ecdc/linux-amd64/go1.9

**Comment by holiman** [comment]
I'm sorry this happened to you, but it's an inherent feature of Ethereum transactions that there are two types of transactions: 

* Normal transactions: contains a `to` address
* Contract-create transactions: does not contain a `to`-address. 

So if you submit a transaction which does not contain a `to`, that is the result. So I would guess that the `t` is either `undefined` or `null` -- which you should see in your logs.

**Comment by legkodymov** [comment]
@holiman , thank you for fix!
Are there any chances (hardforks) when such funds will be recovered? I found number of people stuck in the same situation.
For example, this TxHash 0x7614ee2f5deede9748a8c19f092100369a7fc5c59bae8e1938b50c779eb7afa0
