### ISSUE TITLE
Cannot make on Go 1.10 due to dependency in vendor, simple update needed

### ISSUE THREAD

**Issue by RobinJayaswal** [ethereum/go-ethereum#16118]
OS & Version: OSX
Go: 1.10

`make geth` when building from source fails with following output (this also causes `brew install ethereum` to fail):

```
==> make all
...
# github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51: cannot use refZero (type int) as type *_Ctype_struct___CFAllocator in argument to func literal
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:165: cannot use refZero (type int) as type *_Ctype_struct___CFAllocator in argument to func literal
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:166: cannot use refZero (type int) as type *_Ctype_struct___CFAllocator in argument to func literal
...
util.go:45: exit status 2
exit status 1
make: *** [all] Error 1
```

Looking in the notify directory, this issue was fixed by the author in [this commit](https://github.com/rjeczalik/notify/commit/a05584dd1874c3036b598249f4f1f0f49fc5bf4e).

Short term I fixed this by just replacing `refZero` with `nil` in my local source code and got it to compile successfully. But this dependency needs to be updated on master branch ASAP, as no one with latest GO version is able to brew install right now (see [this issue](https://github.com/ethereum/homebrew-ethereum/issues/149) and [this one](https://github.com/ethereum/homebrew-ethereum/issues/148) on the ethereum-homebrew repo.)

**Comment by Samson101112** [comment]
Hi. Could you please tell me how to install with following your process?

**Comment by greenstevester** [comment]
+1 same issue here. I ended up doing:
brew uninstall go
installing the https://golang.org/doc/install?download=go1.10.darwin-amd64.pkg  ... which worked

**Comment by postables** [comment]
similar issue with go-1.9

```
# github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3
vendor/gopkg.in/olebedev/go-duktape.v3/duktape.go:132: constant 18446744073709551615 overflows int64
util.go:45: exit status 2
exit status 1
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 1

```

**Comment by RobinJayaswal** [comment]
@Samson101112 you should just need to run `make geth` inside the directory. You can now run `build/bin/geth` to start your node.

https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Mac#building-from-source

**Comment by Hofi2010** [comment]
The above fix worked for me on OSX 10.13.2 and go 1.10. Thanks!!!

**Comment by Samson101112** [comment]
@RobinJayaswal  Thank you, but this is the result.

`go-ethereum shun$ make geth
build/env.sh go run build/ci.go install ./cmd/geth
>>> /usr/local/Cellar/go/1.10/libexec/bin/go install -ldflags -X main.gitCommit=9fd76e33af367752160ab0e33d1097e1e9aff6e4 -s -v ./cmd/geth
accounts/keystore/watch.go:25:2:
vendor/github.com/rjeczalik/notify/watcher_fsevents_go1.10.go:1:2: expected 'package', found 'EOF'
util.go:45: exit status 1
exit status 1
make: *** [geth] Error 1`

**Comment by karalabe** [comment]
Should be fixed on master.

**Comment by facundomedica** [comment]
Did you update the vendor.json file? I had to `govendor fetch github.com/rjeczalik/notify` to fix the error. (So I could run `go install ./cmd/abigen`)

**Comment by karalabe** [comment]
@facundomedica Are you sure you're on the latest code?

**Comment by karalabe** [comment]
https://github.com/ethereum/go-ethereum/pull/16115

**Comment by facundomedica** [comment]
@karalabe I ran `go get github.com/ethereum/go-ethereum`

**Comment by karalabe** [comment]
If you already had it locally, it won't update it.

`go get -u github.com/ethereum/go-ethereum/...` should

**Comment by facundomedica** [comment]
You are right, I uninstalled and installed it again and it worked. I didn't know that a `brew install ...` downloaded it already. Thanks!
