### ISSUE TITLE
mobile/android: attach javadoc

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#16127]
it would be great if the aar could ship with javadoc. Otherwise the barrier to entry is quite high and scares away some developers:
https://gitter.im/ethereum/go-ethereum?at=5a89d60d0202dc012e50e631

@karalabe mentioned some time back that there is a problem upstream - is this still the case?

Anyway - opening this issue to keep track, gather info and ideas and give devs the option to put weight on this issue via thumbsup emoji

**Comment by holiman** [comment]
Comment from Peter:

> Maven central rejects our packages (we probably have an issue open for this). When we try to ship stable, maven rejects our signatures with bad gateway. We've tried to fix this, but no luck sof ar. We have one try per stable release, and no clue what the error is.

**Comment by ligi** [comment]
seems @MariusVanDerWijden has good news here - and I would love to shut down the stale bot here anyway - hence this comment
