### ISSUE TITLE
geth console: eth.getBlock by hash not returning anything

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#1613]
with `geth 1.0.1`

via web3.js:
`web3.eth.getBlock(web3.eth.getBlock('latest').hash)` returns a block okay.

via `geth console`:

`web3.eth.getBlock(web3.eth.getBlock('latest').hash)` returns nothing
`web3.eth.getBlock(web3.eth.getBlock('latest').number)` works as expected.

expected is that the `console` also returns a block by hash.

**Comment by obscuren** [comment]
This fix was applied on the master branch during `1.0.0`. Due to a force push this was lost. I'll fix this on develop

**Comment by jorisbontje** [comment]
Seems fixed in `1.1.1`
