### ISSUE TITLE
HTTPVirtualHosts defined in config file get overridden by RPCVirtualHosts flag

### ISSUE THREAD

**Issue by ekryski** [ethereum/go-ethereum#16138]
This really threw me for a loop and took me a while to track down.

#### System information

Geth version: `v1.8.0` and `v1.8.1`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

You should be able to set `HTTPVirtualHosts` in your config file without setting the `--rpcvhosts` flag and it should use the virtual hosts defined in the config file.

#### Actual behaviour

Since `RPCVirtualHosts` is `localhost` by default ([as seen here](https://github.com/ethereum/go-ethereum/blob/master/cmd/utils/flags.go#L400-L403)) any virtual hosts defined in the config file are always overridden by `localhost` [here](https://github.com/ethereum/go-ethereum/blob/master/cmd/utils/flags.go#L699)

#### Steps to reproduce the behaviour

In your config file define `HTTPVirtualHosts = ["*"]` and run geth without the `--rpcvhosts` flag. You won't be able to hit your geth node over RPC from anywhere except localhost and you will see this in your logs:

```
INFO [02-20|02:29:38] HTTP endpoint opened                     url=http://0.0.0.0:8545 cors=* vhosts=localhost
INFO [02-20|02:29:38] IPC endpoint opened                      url=/home/ethereum/data/geth.ipc
```

**Comment by karalabe** [comment]
Nice catch, will look into it.
