### ISSUE TITLE
LES: block sync sometimes starts from block 0

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#16130]
sometime LES sync does not start from the checkpoint but from block 0.

@zsfelfoldi AFAIR you mentioned in the chat once that you have an idea what the reason there is (some timeout when I remember correctly)  - would be great to fix this as this makes syncing a very long endeavour .

**Comment by w7788129** [comment]
全部看不懂

**Comment by karalabe** [comment]
As far as I know this was a fallback behavior if the LES servers you attach to don't have the CHT starting point (i.e. they are out of sync or on a different side chain). However, I think we wanted to force servers to have the proper CHT, so I think this should already be fixed, but someone pls confirm.

CC @zsfelfoldi @rjl493456442

**Comment by fjl** [comment]
Fixed in Geth v1.9.6
