### ISSUE TITLE
Geth evicts all peers, does not attempt to add new peers

### ISSUE THREAD

**Issue by DaveWK** [ethereum/go-ethereum#16145]
#### System information

Geth version: 1.8.0
OS & Version: Linux (RHEL variant)

#### Expected behaviour

Geth should attempt to get more peers if it drops all the peers. 

#### Actual behaviour

Will eventually state  
`Synchronisation failed, dropping peer peer=xxxxx err="retrieved hash chain is invalid"`
for each peer at some point and evict every peer from it's loop. It then will spin with  "Regenerated local transaction journal transactions=0 accounts=0" and not have any peers, leaving blockchain stuck at whatever value.

#### Steps to reproduce the behaviour

Leave a node on for a couple days in AWS and it will enter this state. Can be fixed by restarting node, but the logic should be smart enough to start adding new peers and refresh blacklist if it gets down to 0 peers.

**Comment by karalabe** [comment]
That's an odd one. It most definitely should not do that. If it happens again, could you do a `debug.vmodule("downloader=5")` let it run for a while and then copy paste the logs here?

**Comment by upers** [comment]
Geth version: 1.8.4
OS: Ubuntu 16.04
I have the same problems. Only after reboot node start sync.
Logs:
Synchronisation failed, dropping peer    peer=c75bbe644a9e4908 err=timeout
Synchronisation failed, dropping peer    peer=c718dac93fc9db1b err=timeout
Synchronisation failed, retrying         err="block header download canceled (requested)"
Synchronisation failed, retrying         err="block download canceled (requested)"
[04-21|05:39:36] Synchronisation failed, retrying         err="block header download canceled (requested)"
Failed to unregister sync peer           peer=1c551df83c9ec5e5 err="peer is not registered"
Imported new chain segment               blocks=1  txs=190  mgas=7.977   elapsed=4.830s    mgasps=1.651   number=5478302 hash=f4ce5c…366
Regenerated local transaction journal    transactions=0 accounts=0
Regenerated local transaction journal    transactions=0 accounts=0
Regenerated local transaction journal    transactions=0 accounts=0

**Comment by DaveWK** [comment]
Closing; this seems to have been fixed sometime before 1.8.8
