### ISSUE TITLE
Gracefully recover missing block number

### ISSUE THREAD

**Issue by kenshyx** [ethereum/go-ethereum#16140]
#### System information

Geth version: `v1.8.1-stable`
OS & Version: Linux Mint 18.1
Commit hash : (if `develop`)

#### Expected behaviour
Starts geth daemon.

#### Actual behaviour
Logs error: `Fatal: Error starting protocol stack: missing block number for head header hash` and process exits with code `1`.

#### Steps to reproduce the behaviour
It seems that this happens when closing(forced) the daemon during a db write.

#### Backtrace

````
[backtrace]
````

**Comment by rosmo01** [comment]
I have the same behaviour after geth crashing incessantly after upgrading from 1.8.0-1.8.1[https://github.com/ethereum/go-ethereum/issues/16173](url)

**Comment by jordimorris** [comment]
same issue here with geth 1.8.2

**Comment by DeRain** [comment]
Did anyone solve this?

**Comment by tanhuiya** [comment]
same issue here with geth 1.8.6

**Comment by adamschmideg** [comment]
Can anyone with issue provide a stack trace?

**Comment by CamposBruno** [comment]
I get the same error when almost finishing full sync

Using Geth Version 1.9.3-stable
And go : go1.12.9.linux.amd64

<pre>
INFO [09-11|03:45:53.635] Imported new block headers               count=1    elapsed=5.737ms      number=8526160 hash=895afb…3fe6e3
INFO [09-11|03:45:54.777] Imported new state entries               count=1152 elapsed=7.497ms      processed=136478888 pending=15668 retry=0    duplicate=11455 unexpected=194705
INFO [09-11|03:45:55.473] Imported new state entries               count=1152 elapsed=5.237ms      processed=136480040 pending=16892 retry=0    duplicate=11455 unexpected=194705
2019/09/11 03:45:55 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 5ms
2019/09/11 03:45:55 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 10ms
2019/09/11 03:45:55 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 20ms
2019/09/11 03:45:55 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 5ms
2019/09/11 03:45:55 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 10ms
2019/09/11 03:45:55 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 20ms
2019/09/11 03:45:56 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 40ms
2019/09/11 03:45:56 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 80ms
2019/09/11 03:45:56 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 160ms
2019/09/11 03:45:56 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 320ms
2019/09/11 03:45:56 http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 640ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1b8 pc=0x84d1a41]

goroutine 479884 [running]:
github.com/ethereum/go-ethereum/core.(*HeaderChain).SetCurrentHeader(0xaffbc20, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/headerchain.go:460 +0xf1
github.com/ethereum/go-ethereum/core.(*BlockChain).Rollback(0x105a0000, 0x3774e000, 0x800, 0x800)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:881 +0x24b
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processHeaders.func1(0x261b7ec8, 0x106bc000)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1374 +0x189
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processHeaders(0x106bc000, 0x821951, 0x0, 0x821843, 0x0, 0x4e7944a0, 0x8e2b7d0, 0xae58440)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1393 +0x1179
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func6(0x4, 0x8c40924)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:517 +0x49
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0x106bc000, 0x4cb0d980, 0x5b7f9620)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:534 +0x46
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:534 +0x8c
INFO [09-11|03:51:27.022] Maximum peer count                       ETH=50 LES=0 total=50
INFO [09-11|03:51:27.023] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [09-11|03:51:27.025] Starting peer-to-peer node               instance=Geth/GMCNODE/v1.9.3-stable-cfbb969d/linux-386/go1.12.9
INFO [09-11|03:51:27.025] Allocated trie memory caches             clean=128.00MiB dirty=128.00MiB
INFO [09-11|03:51:27.025] Allocated cache and file handles         database=/home/centos/NODES/ethmainnet/geth/chaindata cache=256.00MiB handles=2048
INFO [09-11|03:51:29.848] Opened ancient database                  database=/home/centos/NODES/ethmainnet/geth/chaindata/ancient
Fatal: Error starting protocol stack: missing block number for head header hash
</pre>

**Comment by holiman** [comment]
@CamposBruno what happened in your case is that geth used too many file descriptors (in linux, both 'files' and 'sockets' are, basically, files). When that happens, all bets are off, since the underlying data structures won't be able to save data, which most likely leads to database corruption. 


This _should_ not happen, and it's good if we can figure out why that happened. For starters, what OS are you using? Are you running any other 'heavy' things on the side, e.g. another node? 
Could you please file a _new_ ticket with the info above and the new info?
