### ISSUE TITLE
leveldb/table corrupted, then dropping peers and failing to sync.

### ISSUE THREAD

**Issue by kciryt** [ethereum/go-ethereum#16148]
#### System information

Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.2
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

#### Expected behaviour
Sync

#### Actual behaviour
Not syncing, and dropping peers due to invalid hashchain.

#### Steps to reproduce the behaviour
Unsure if the issue is reproducible to a reliable certainty.  But I pressed Ctrl+C while in the console, and after being unable to kill geth with kill -HUP, and -INT, I used kill -9.  The received the error: 

```CRIT [02-20|20:18:58] Failed to store block total difficulty err="leveldb/table: corruption on data-block (pos=207183): checksum mismatch, want=0xa1787c60 got=0x2327cc80 [file=149623.ldb]"```

Afterwards, I deleted the file in question 149623.ldb and now am getting the following issues with my peers:
```
WARN [02-20|20:40:20] Synchronisation failed, dropping peer peer=9097f897caa6997e err="retrieved hash chain is invalid"
INFO [02-20|20:40:32] Imported new chain segment blocks=4 txs=39 mgas=5.276 elapsed=9.189s mgasps=0.574 number=2590712 hash=f466b5…2b40b5
ERROR[02-20|20:40:44]
#### BAD BLOCK

Chain config: {ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Engine: ethash}

Number: 2590716
Hash: 0x6cb2c18886e6764810bcd495ffa14ce16cbe0b3733a0c9d0b99058e9554b7f39

Error: nonce too high
#

WARN [02-20|20:40:44] Synchronisation failed, dropping peer peer=e80276aabb7682a4 err="retrieved hash chain is invalid"
```

**Comment by karalabe** [comment]
Why would you delete a file from the database? Anyway, seems either that your disk is failing (which caused the corruption in the first place), or perhaps a power outage / OS crash caused the database to fail mid write. I'm voting for the disk failing though, please run a bad sector check.

All in all with the database file deleted, your only option now is to sync from scratch.

**Comment by kciryt** [comment]
Others have done this on past tickets with varying degrees of success.  Also, I didn't realize the software would have trouble recovering.  Would the ```kill -9``` not be responsible for the initial corruption?

**Comment by karalabe** [comment]
Everyone doing such a thing will end up with bad blocks eventually, when they try to access data they just deleted. Never delete individual files from the database.

Geth does try to recover from various problems, as long as the database is available. Not sure whether `kill -9` was the culprit of something else, but if leveldb reports its datafiles as corrupted, there's not much geth can do, since leveldb doesn't even allow geth to touch any data any more.
