### ISSUE TITLE
Transactions are not being included, while blocks are being mined successfully in a private chain

### ISSUE THREAD

**Issue by lbrep** [ethereum/go-ethereum#16150]
I have started two nodes with same genesis.json on same machine in a same directory. 
#### System information

Geth
Version: 1.8.1-stable
Git Commit: 1e67410e88d2685bc54611a7c9f75c327b553ccc
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.4
Operating System: linux

#### Expected behaviour
The nodes should include the pending/queued transactions in the blocks that are going to be mined next.

#### Actual behaviour
The transactions are not propagated to the other node. and the transactions are not included in the next mining block. the blocks are mining successfully. (as the difficulty level is set very low). But the transaction are lying in the queue. and are never mined. 
`txpool.status `shows the following:

```
{
  pending: 0,
  queued: 5
}
```
And when I call the eth.getTransaction("0x5aded5..."), The block number field is null.

Also `txpool.status` on the second node shows

```
{
      pending: 0,
      queued: 0
    }
```

#### Steps to reproduce the behaviour
1. start first node in a different data directory 
`./geth --datadir ./chaindata/ --port 30303 --networkid 15525 --rpc --rpcport 8545--rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "web3,eth,personal,net" console
`
2. and then the second node (ran this command on same machine in same directory):

` ./geth --datadir ./chaindata2/ --port 30304 --networkid 15525 --rpc --rpcport 8546 --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "web3,eth,personal,net" console 

`
PLESE NOTE THAT THE PORT, RPC PORT , AND DATA DIRECTORY ARE DIFFERENT IN THE TWO

3. Then, found the node id of the second one by admin.nodeInfo and added it as a peer in the other console with admin.addpeer
`admin.addPeer("enode://f583bdf4e0e56818b920041a0588ba415352fa155935f04fbe287f2e2d111047a2f7e7b15c156d160b2afbbdde46081cf6aa6a73dbdbefddb99a8ebb01e03de3@127.0.0.1:30303")
4.```
 eth.sendTransaction({from:"39408873c54f3d8efe67c43532ac3b3b5db7fb7f", to: "11f53eb1649af91da0af06d84700a33919febe9e",value: "250",gasPrice:20 , gas: 21000, nonce: 150 )});
`
Transaction is created succesfully.
But txpool.status shows the following:

{
  pending: 0,
  queued: 5
}
And when I call the eth.getTransaction("0x5aded5..."), The block number field is null.

Also txpool.status on the second node shows

{
      pending: 0,
      queued: 0
    }
However the blocks are succesfully synchronized, and the mining is successfully done. For Information : Here is my genesis.json

{
   "config": {
      "chainId": 1994,
      "homesteadBlock": 0,
      "eip155Block": 0,
      "eip158Block": 0,
      "byzantiumBlock": 0
   },
   "difficulty": "4",   // PLEASE NOTE !!!
   "gasLimit": "2000000",
   "alloc": {
      "39408873c54f5b8efe67c4353d4c3b3b5db7fb7f": {
          "balance": "100000000000000000000000"
      },
      "ae13d41d66af2d380c7af6d825ab557eb271ffff": {
          "balance": "120000000000000000000000"
      }
   }
}
```


Why transactions are not included in the blocks? I have tried with geth 1.7, also ..same problem.

**Comment by karalabe** [comment]
```
{
  pending: 0,
  queued: 5
}
```

Means that there are no executable transactions. The queued part means that there are some transactions, but those are not currently executable, most probably because there is a nonce gap blocking them.

You can inspect the queued transactions in detail via `txpool.inspect`.
