### ISSUE TITLE
--testnet or --dev

### ISSUE THREAD

**Issue by freshonline** [ethereum/go-ethereum#16167]
I need privat blockchain for testing smart contracts. Why no --testnet or --dev?
This reopen - https://github.com/ethereum/go-ethereum/issues/16137

**Comment by karalabe** [comment]
* `--testnet` means the official Ropsten test network
 * `--rinkeby` means the official Rinkeby test network
 * `--dev` means an ephemeral in-memory local chain

Just don't use any of these. You can make a private network using

```
geth --datadir=/path/to/my/data init genesis.json
geth --datadir=/path/to/my/data
```

That's all you need.
