### ISSUE TITLE
[Feature Request] Allow setting a timeout for ContractSession

### ISSUE THREAD

**Issue by libreoscar** [ethereum/go-ethereum#16169]
go-ethereum version: 1.8

Current the generated FooSession struct for a contract Foo uses completely pre-set call and transact options. However, a reasonable deadline of the context of a call/transact can only be decided at the call time.

It would be great if it allows setting a timeout explicit in a FooSession, which is used to calculate the deadline (by adding `time.Now()`) each time when sending an RPC request.

**Comment by VoR0220** [comment]
Why not implement that as a superset construct over the bound contract package?

**Comment by libreoscar** [comment]
That would work of course. But I think given that timeout is a very commonly used option, it is worth native support.
