### ISSUE TITLE
geth fatal error : failed to create protocol stack : Access Denied

### ISSUE THREAD

**Issue by pavanyalamanchi** [ethereum/go-ethereum#16161]
C:\Program Files\Geth\geth-testnet-demo>geth --identity "MyTestNode" --datadir "./data" --testnet --fast
Fatal: Failed to create the protocol stack: mkdir C:\Program Files\Geth\geth-testnet-demo\data: Access is denied.

**Comment by karalabe** [comment]
> Access is denied.

Check your permissions or put your data directory in a folder you have write access to.
