### ISSUE TITLE
Crash - panic: gas pool pushed above uint64

### ISSUE THREAD

**Issue by zincoshine** [ethereum/go-ethereum#16160]
I have had this crash thrice in the past 24 hours.

#### System information

Geth version: `1.8.1`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Sync should complete normally

#### Actual behaviour
Sync crashes on Ropsten with the following error

```
INFO [02-22|01:47:01] Imported new chain segment               blocks=1   txs=15   mgas=3.324   elapsed=108.376ms mgasps=30.668  number=2699390 hash=7e3850…be6e9d cache=65.40mB
panic: gas pool pushed above uint64

```#### Steps to reproduce the behaviour
Run geth under testnet

#### Backtrace
This is the error dump
```
goroutine 555458 [running]:
github.com/ethereum/go-ethereum/core.(*GasPool).AddGas(0xc4847e3ad0, 0x75da968, 0x0)
	/build/ethereum-Fzpoys/ethereum-1.8.1+build12537+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/gaspool.go:31 +0x6a
github.com/ethereum/go-ethereum/core.(*StateTransition).refundGas(0xc44d2ff810)
	/build/ethereum-Fzpoys/ethereum-1.8.1+build12537+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:270 +0x1e2
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc44d2ff810, 0x1879a80, 0xc46d8253e0, 0xc4847e3ad0, 0xc44d2ff810, 0xc46d8253e0, 0xc46d8253e0, 0xf6ece0)
	/build/ethereum-Fzpoys/ethereum-1.8.1+build12537+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:248 +0x58c
github.com/ethereum/go-ethereum/core.ApplyMessage(0xc4583cd500, 0x1879a80, 0xc46d8253e0, 0xc4847e3ad0, 0xc4583cd500, 0xc447149a40, 0xc46fc566c0, 0x0, 0x0, 0x0, ...)
	/build/ethereum-Fzpoys/ethereum-1.8.1+build12537+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:132 +0x5b
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicBlockChainAPI).doCall(0xc4239b7130, 0x1874f80, 0xc46d825320, 0x0, 0x0, 0x0, 0xc472e30c80, 0x0, 0x0, 0x0, ...)
	/build/ethereum-Fzpoys/ethereum-1.8.1+build12537+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:669 +0x651
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicBlockChainAPI).Call(0xc4239b7130, 0x1874fc0, 0xc46ae86690, 0x0, 0x0, 0x0, 0xc472e30c80, 0x0, 0x0, 0x0, ...)
	/build/ethereum-Fzpoys/ethereum-1.8.1+build12537+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:679 +0xba
reflect.Value.call(0xc423c86680, 0xc423e725f8, 0x13, 0xf979ab, 0x4, 0xc46d8252c0, 0x4, 0x4, 0x1446e2c616210437, 0xc46d8252c0, ...)
	/usr/lib/go-1.9/src/reflect/value.go:434 +0x905
reflect.Value.Call(0xc423c86680, 0xc423e725f8, 0x13, 0xc46d8252c0, 0x4, 0x4, 0x2, 0x2, 0xc441be2d98)
	/usr/lib/go-1.9/src/reflect/value.go:302 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc423e9cfe0, 0x1874fc0, 0xc46ae86690, 0x1879ce0, 0xc44d5db400, 0xc46d825260, 0xc426448380, 0x0, 0x83ad23)
	/build/ethereum-Fzpoys/ethereum-1.8.1+build12537+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:311 +0x6ce
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc423e9cfe0, 0x1874fc0, 0xc46ae86690, 0x1879ce0, 0xc44d5db400, 0xc46d825260)
	/build/ethereum-Fzpoys/ethereum-1.8.1+build12537+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:333 +0x1ba
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func2(0xc4244a6710, 0xc423e9cfe0, 0xc479d315c0, 0x1879ce0, 0xc44d5db400, 0xc43eb61c98, 0x1, 0x1, 0x0)
	/build/ethereum-Fzpoys/ethereum-1.8.1+build12537+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:206 +0xad
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
	/build/ethereum-Fzpoys/ethereum-1.8.1+build12537+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:201 +0x2ab
```````

**Comment by karalabe** [comment]
Apparently you did a contract call via RPC with some insanely high gas allowance?

**Comment by codehakase** [comment]
This appears to be an RPC call that failed
