### ISSUE TITLE
secp256k1 :  fatal error: 'gmp.h' file not found

### ISSUE THREAD

**Issue by utocat** [ethereum/go-ethereum#1617]
# github.com/ethereum/go-ethereum/crypto/secp256k1
In file included from crypto/secp256k1/secp256.go:36:
In file included from ././secp256k1/src/secp256k1.c:12:
In file included from ././secp256k1/src/num_impl.h:14:
In file included from ././secp256k1/src/num.h:17:
././secp256k1/src/num_gmp.h:10:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^
1 error generated.

**Comment by Gustav-Simonsson** [comment]
```bash
sudo apt-get install libgmp3-dev
```

**Comment by utocat** [comment]
thanks, it works now
