### ISSUE TITLE
The never ending and escalating geth memory corruption.

### ISSUE THREAD

**Issue by rosmo01** [ethereum/go-ethereum#16173]
#### System information

Geth version: `1.7.2-1.8.1`
OS & Version: Windows 10 - 512 GB RAM, 3x2TB Samsung Evo 850 pro
Commit hash : (if `develop`)

#### Expected behaviour

Geth to access and use memory without crashing.

#### Actual behaviour

INFO [02-23|04:44:37] Imported new chain segment               blocks=13 txs=1457 mgas=79.030  elapsed=9.504s  mgasps=8.315  number=5139434 hash=40d911…eb0bbf cache=73.91mB
INFO [02-23|04:44:43] Imported new chain segment               blocks=7  txs=846  mgas=55.864  elapsed=6.859s  mgasps=8.144  number=5139441 hash=83bd38…ba8b33 cache=76.89mB
fatal error: out of memory
runtime: out of memory: cannot allocate 131072-byte block (34350235648 in use)
fatal error: out of memory
runtime: out of memory: cannot allocate 131072-byte block (34350235648 in use)
fatal error: out of memory
fatal error: out of memory

runtime stack:
runtime.throw(0xf32a19, 0xd)
        C:/go/src/runtime/panic.go:605 +0x9c
runtime.largeAlloc(0x1a000, 0xc0675e0100, 0x3)
        C:/go/src/runtime/malloc.go:829 +0x11b
runtime.mallocgc.func1()
        C:/go/src/runtime/malloc.go:722 +0x4d
runtime.systemstack(0xc4cd691538)
        C:/go/src/runtime/asm_amd64.s:344 +0x7e
runtime.mstart()
        C:/go/src/runtime/proc.go:1135

#### Steps to reproduce the behaviour

Run geth and wait, or update to 1.8.1

#### Backtrace

To top if off now geth will NOT initiate as I get this exception: "missing block number for head header hash"!!

This is getting out of hand!

````
[backtrace]
````

**Comment by karalabe** [comment]
What parameters are you starting Geth with? How much system ram do you have?

**Comment by rosmo01** [comment]
I forgot to paste the description:

For as long as I can remember the geth on Windows simply crashes, and takes Ethereum wallet GUI with it.

Running geth in console mode and then starting the GUI will prevent this and also truly show what is going on.

After the last update to 1.8.1 the crash of geth has gotten absolutely bonkers as it will crash after just a few minutes!

This is not a system/hardware issue as I’m running on 512 GB RAM, 3x2TB Samsung Evo 850 pro.

I have set up geth to use 32gb cache, and clearly see that the crash happens long BEFORE utilizing the 32GB.

I have tried to roll-back to 1.8.0 which crashed only sporadically, but the 1.8.1 update seems to have corrupted and made the memory corruption absolutely insane.

This problem has been going on for years and there are so many articles/reports/tickets on this gone unanswered and without any ownership from development so I wonder why we should bother running a full node anymore as the blockchain is becoming a TB monster fast.

**Comment by karalabe** [comment]
There was a memory issue that people were reporting, but that should be fixed in 1.8.0. The 1.8.1 update is a very tiny one that just fixes a couple issues, so there can't be any different between the two. Out of curiosity, are you building Geth yourself, or using pre-build binaries? Which Go version are you using?

Could you paste a bit more of the crash logs? I'm curious which part of the code is allocating that's causing the crash.

**Comment by rosmo01** [comment]
I download the archives.
Versions 1.7.2-1.8.1 and have tested up to latest 1.8.2 unstable
[geth-1.8.1-console1.log](https://github.com/ethereum/go-ethereum/files/1751383/geth-1.8.1-console1.log)

**Comment by karalabe** [comment]
Apparently, this is a limitation of Go 1.9 https://github.com/golang/go/issues/23922#issuecomment-366730706 on Windows.

We already have a PR to build with Go 1.10, but it still needs some libs to be released by an upstream project. I'll split it up and merge only the Windows upgrades so you could try it.

**Comment by karalabe** [comment]
Oh wow, no:

> I believe the same is true of 1.10.

Damn. Ok, then please set `--cache` to about 13GB max (Go likes to double it with it's default GC) and that should be a lame solution for now. I didn't know about these limits in Go.

**Comment by karalabe** [comment]
The fix is promised to land in Go 1.11 only, which is scheduled for August only.

**Comment by rosmo01** [comment]
OK - IC - well thanks for your time. Setting the cache to 13GB  - how is that going to help when this problem occurs with default RAM utilization (meaning using no cache parameters)?

I have incrementally increased the cache setting from 2048, so I know this is not working.

Is this the official "resolution" to this problem to wait until August? There is a deluge coming in now on this problem.......

I'm definitely leaving this project for good if the above is the case as this is just unacceptable and hope Parity will continue to deliver stability..

**Comment by karalabe** [comment]
Geth 1.7.x had memory issues, those have been fixed with 1.8.0. Running with a cache of 2GB should most definitely not crash. If it does, please report it.

**Comment by adamschmideg** [comment]
@karalabe I understand the original issue has been fixed, so I'm closing this.

**Comment by adamschmideg** [comment]
@ekryski If you still have a problem, please, report it with the actual version number. I'm closing this issue that refers to an earlier version and probably different setup.
