### ISSUE TITLE
IPC unreliable on Windows

### ISSUE THREAD

**Issue by Quiark** [ethereum/go-ethereum#1618]
I downloaded this build 
`Geth-Win64-20150807124011--dcb23bc`

run `geth` 
and one more `geth attach`

Now after a while of inactivity, I start getting 
```javascript
> admin
{
  chainSyncStatus: Error: The handle is invalid.,
  datadir: Error: The handle is invalid.,
  nodeInfo: Error: The handle is invalid.,
  peers: Error: The handle is invalid.,
  addPeer: function (),
  exportChain: function (),

```

or
`pendingTransactions: Error: Cannot access member 'constructor' of null,`

or other errors. Quitting the attached geth and restarting it works for a small while.

And the in-console input also doesn't work very well, people are complaining about this on the IRC

**Comment by jwhelan72** [comment]
Problems with the in-console input are severe and are detailed here: https://github.com/ethereum/go-ethereum/issues/1608

**Comment by fjl** [comment]
Now that #1642 is merged on develop, command line editing should work again.

**Comment by fjl** [comment]
The fix has been released.
