### ISSUE TITLE
i check in geth Attach "eth.getBalance(eth.coinbase) 90. but i check in MyEtherWallet stil "0"

### ISSUE THREAD

**Issue by Akhimlee** [ethereum/go-ethereum#16185]
Hi there,

help me brother, i have 90 eth in geth console i check. but i check in myEtherwallet still 0. someone teach me please

#### System information

Geth version: `Geth/v1.8.2`
OS & Version: Windows 10 64bit

**Comment by Jehova0710** [comment]
Hi…. Then???

**Comment by Akhimlee** [comment]
@Jehova0710  
can you teach me how to get my balance in MIST wallet visible in MyEtherWallet? What should I do ? im done sync using "geth --fast"

**Comment by RichHorrocks** [comment]
Hi there. Ideally ask technical questions on https://ethereum.stackexchange.com - it's important to keep issue trackers clear and for real issues only.

**Comment by karalabe** [comment]
Check your balance on https://etherscan.io/ . That's most probably your true balance on mainnet. 

Did you by any chance start Mist and just started mining on the empty chain? Or perhaps you're on a test network?

**Comment by Akhimlee** [comment]
@karalabe i new in solo mining, i hope i can explore how to solo mining, i have chaindata in my folder, how to true mining, and get ETH ? im using GPU, can you teach me brother  ? please !!!

**Comment by karalabe** [comment]
For general questions, please ask at https://ethereum.stackexchange.com/ and https://www.reddit.com/r/EtherMining/
