### ISSUE TITLE
The APIs provided by admin namespace are incomplete ?

### ISSUE THREAD

**Issue by IcyLemon** [ethereum/go-ethereum#16182]
Hi
My environment is:
Geth version: `1.7.3-stable`
OS & Version: CentOS 7.2 64

geth client node started normally as follows:
`./geth --rpc --rpccorsdomain "*" --datadir "/usr/blockchain/data" --port "34567" --rpcapi "personal,db,eth,net,web3,miner,admin" --networkid 100000 console`

Now I tried to execute the following geth console commands using HTTP-RPC:
`admin.sleepBlocks(1)`

My HTTP-RPC command is:
`curl -X POST -H 'content-type: application/json' -d '{"method": "admin_sleepBlocks", "params": [1], "id":75}' 127.0.0.1:8545`

The above command was executed, the error occurred:
{"jsonrpc":"2.0","id":75,"error":{"code":-32601,"message":"**The method admin_sleepBlocks does not exist/is not available**"}}

But other admin command was executed normally by HTTP-RPC, e.g. admin_peers:
`curl -X POST -H 'content-type: application/json' -d '{"method": "admin_peers", "params": [], "id":75}' 127.0.0.1:8545`
response:
{"jsonrpc":"2.0","id":75,"result":[]}

So the HTTP-RPC APIs provided by admin namespace are incomplete compared to geth client console?

Thanks a lot.

**Comment by karalabe** [comment]
The sleepBlocks is just a hack for the console. It's not a real API. You can use subscriptions for chain head events to get the same thing with a proper and reliable api.
