### ISSUE TITLE
[LES] `eth_getTransactionReceipt` api inconsistency wrt `contractAddress`

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/go-ethereum#16199]
#### System information

Geth version: 1.8.1 (all)
OS & Version: all
Commit hash: -

#### Expected behaviour

While using `syncmode light` it was expected the `get_transactionReceipt` method would return the same data as `syncmode fast/full`. However, `contractAddress` returns `null`, causing disruption of Dapps. 

UIs shouldn't have to worry about dealing with mode-specific behavior. Ideally, they would just rely on the same API.

In Mist we've circumvented that by intercepting the RPC method and [applying the necessary measures](https://github.com/ethereum/mist/blob/develop/modules/ipc/methods/eth_getTransactionReceipt.js#L39-L57). 

#### Actual behaviour

`contractAddress` always returns `null` while running with `syncmode light`.

#### Steps to reproduce the behaviour

Run `eth_getTransactionReceipt` with a tx hash of a created contract.

#### Backtrace

````
none
````

**Comment by karalabe** [comment]
This should already be fixed on master. Please try it out and reopen if not.
