### ISSUE TITLE
how to get the data from debug.metrics

### ISSUE THREAD

**Issue by jackz-jones** [ethereum/go-ethereum#16194]
Hello,everyone
         My DAPP need to monitor the geth . And how to get the datas from debug.metrics?

#### System information

Geth version: 1.7.3
OS & Version: OSX10.13.3

**Comment by Jehova0710** [comment]
U not send me nothing, and not payme nothing... what is the problem??? I don’t have anything 

Enviado desde mi iPhone

**Comment by jackz-jones** [comment]
the problem is that I don't know how interact with debug.metrics.The web3.js does not provide debug API
