### ISSUE TITLE
Puppeth - allow to switch between ssh keys for remote servers

### ISSUE THREAD

**Issue by REPTILEHAUS** [ethereum/go-ethereum#16196]
Currently I can only deploy  changes if my ssh key is named **id_rsa** - Id like to be able to specify or choose from a list of keys in my **$HOME/.ssh** directory. 

Is this possible ?

As a workaround I changed the name of my ssh key to **id_rsa** but when trying to authenticate with the remote host i get the warning, even though i can ssh to the remote host using **ssh user@ipaddress** - docker CE and docker-compose are both installed on the server

```
ERROR[02-26|15:43:34] Server not ready for puppeth             err="ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain"
```

additionally.. I am running puppeth on an instance with domain **main.example.com** i am trying to setup an Ethstats network component on **stats.example.com** - trying to connect using the above fails, however using the remote servers **user@ipaddress** in lieu of the servers domain (**stats.example.com**) actually starts to generate the docker containers, not sure whats going on here.

**Comment by chainsulting** [comment]
Are you able to login via ssh to your node ?

ssh username@IP
ex. ssh ubuntu@10.122.0.5
