### ISSUE TITLE
Compatibility with Wasm

### ISSUE THREAD

**Issue by jamesray1** [ethereum/go-ethereum#16192]
Just flagging this in case it hasn't been raised: golang/go#18892. It's important to keep track of compatibility with Wasm as Rust and C++ are both compatible, while Go isn't, so Parity and cppethereum seem likely to become faster than Go-Ethereum when they run Wasm.

**Comment by fjl** [comment]
I don't fully understand the purpose of this issue. Go can compile to WASM, and WASM code can be run from a Go program by executing a virtual machine. Ergo, Go and WASM are compatible.

**Comment by goldbock** [comment]
@fjl that's indeed the way it should work except that go-ethereum seems to use several libraries that are not compatible with wasm. 

See for example this https://github.com/ethereum/go-ethereum/issues/23972
