### ISSUE TITLE
Invalid number of arguments to Solidity function

### ISSUE THREAD

**Issue by lzj3823** [ethereum/go-ethereum#16201]
main code ：`<script src="/lib/web3.js"></script>
{
		"constant": false,
		"inputs": [
			{
				"name": "_order",
				"type": "bytes32"
			},
			{
				"name": "stockCode",
				"type": "bytes10"
			},
			{
				"name": "stockAccount",
				"type": "bytes10"
			},
			{
				"name": "amount",
				"type": "uint16"
			}
		],
		"name": "entrustBuy",
		"outputs": [
			{
				"name": "result",
				"type": "bool"
			}
		],
		"payable": true,
		"stateMutability": "payable",
		"type": "function"
	}
           var MyContract = web3.eth.contract(storageAbi);
	    var myContractInstance = MyContract.at(storageCodeAddress);
      myContractInstance.entrustBuy({_order:'10303', stockCode:'180208' ,stockAccount:'00044856', amount:10, from:moneyaddress},function (error, result) {
		  if (!error){
		  	 console.log(result);
		  }else{
		  	console.log(error);
		  }
		  console.log("callback==");
		   
		  
		});

and run ,has error:  Invalid number of arguments to Solidity function?why

`

**Comment by karalabe** [comment]
As far as I know, the arguments are a flat list, not a struct.
