### ISSUE TITLE
util.go:45: exit status 1 exit status 1 Makefile:15: recipe for target 'geth' failed make: *** [geth] Error 1

### ISSUE THREAD

**Issue by boorac** [ethereum/go-ethereum#16204]
#### System information

OS & Version: Ubuntu 16.04
Commit hash : tags/v1.7.3

#### Expected behavior

Should be able to compile geth tags/v1.7.3.

#### Actual behavior

Compilation fails.

#### Steps to reproduce the behaviour
```
git clone git@github.com:ethereum/go-ethereum.git;
cd go-ethereum;
git checkout tags/v1.7.3; # checkout 1.7.3
# gvm use go1.9.4 --default; # install a version of go that 1.7.3 is happy with.
make geth;
```

#### Backtrace

````
make geth
build/env.sh go run build/ci.go install ./cmd/geth
>>> /home/user/.gvm/gos/go1.9.4/bin/go install -v ./cmd/geth
github.com/ethereum/go-ethereum/crypto/secp256k1
go build github.com/ethereum/go-ethereum/crypto/secp256k1: build constraints exclude all Go files in /home/user/Sources/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/crypto/secp256k1
util.go:45: exit status 1
exit status 1
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 1

````

**Comment by boorac** [comment]
If deemed not necessary to fix an issue with an older version, I needed the version because of a migration bug with truffle and geth 1.8.1 which was solved in truffle 4.07. yesterday.

https://github.com/trufflesuite/truffle/issues/721#issuecomment-366754953

So I guess this can be closed?

**Comment by karalabe** [comment]
If Geth 1.8.1 builds correctly, then I guess there's not much to do. We won't backport fixes. Thanks for the followup!

**Comment by Jagdish0886** [comment]
how was this fixed, can you please help me?

**Comment by trocca** [comment]
I have go 1.11.4 and still get the same error...

**Comment by YongilChoi** [comment]
On Ubuntu: 

choi@GITSERVER:~/go/src/github.com/ethereum/newversion/go-ethereum$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/choi/go/bin"
GOCACHE="/home/choi/.cache/go-build"
GOENV="/home/choi/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/choi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build191391551=/tmp/go-build -gno-record-gcc-switches"



====================Error message ==========================
Failed to cross compile package: exit status 2.
util.go:45: exit status 1
exit status 1
Makefile:138: recipe for target 'geth-windows-386' failed
make: *** [geth-windows-386] Error 1

**Comment by cdljsj** [comment]
Got similar issue with command: make geth-linux-386
