### ISSUE TITLE
rpc api eth_getwork always return same header

### ISSUE THREAD

**Issue by fatrat1117** [ethereum/go-ethereum#16211]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth
Version: 1.8.1-stable
Git Commit: 1e67410e88d2685bc54611a7c9f75c327b553ccc
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.2
Operating System: windows
GOPATH=
GOROOT=c:\go

#### Expected behaviour
eth_getwork returns different header every 15 seconds

#### Actual behaviour
request:
{"jsonrpc":"2.0","method":"eth_getWork","params":[],"id":71}
response:
{
    "jsonrpc": "2.0",
    "id": 71,
    "result": [
        "0x081e94b27c19e28b1f17c60bf02753df1f3598ef9651420bc128f43917568225",
        "0x0000000000000000000000000000000000000000000000000000000000000000",
        "0x0000000040080100200400801002004008010020040080100200400801002004"
    ]
}
header is always same unless restart geth, seed is always 0.
#### Steps to reproduce the behaviour
run geth --rpc
send {"jsonrpc":"2.0","method":"eth_getWork","params":[],"id":71} to http://localhost:8545

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Did you wait for your node to be in sync with the network?

**Comment by fatrat1117** [comment]
How long should I wait normally? I run geth and leave it run for a whole night, the next day morning I call rpc API then I get this issue.

**Comment by fatrat1117** [comment]
how to  check the sync process is done in the console or log?

**Comment by Julek** [comment]
Hi there!

I have a similar problem running on linux with geth version 1.8.2-stable-b8b9f7f4.
The second and third element of the result array fatrat1117 received are identical to mine.

I'm running geth using:
geth --datadir <data directory> --rpc --mine --minerthreads=1 --etherbase <myetherbase>

To try and debug the issue, I ran a few RPC calls:
- eth_mining returns true.
- eth_hashrate return 0.
- eth_blockNumber returns 0
- eth_syncing returns {"currentBlock":"0x505b3b","highestBlock":"0x505b7c","knownStates":"0x2834d27","pulledStates":"0x2833ce9","startingBlock":"0x5011ee"}

The last result surprised me as the specification says that currentBlock should have the same value as blockNumber returns. After a few minutes, syncing starts returning false. eth_getWork still has the exact same return. In particular the shape of the return value doesn't even satisfy the spec as the array contains only 3 elements.

**Comment by Julek** [comment]
Hey there!

As an answer to your question fatrat1117, running this command in console should do the trick:
eth.syncing.highestBlock - eth.syncing.currentBlock

It computes the distance of the most recent block you've synced with the highest block in the block chain your client is aware of, which should be 0 when you're fully synced. In my case, this bug seems to be caused by the fact that it's pretty much impossible to sync with the ethereum network anymore using geth.

Thanks,

Jules
