### ISSUE TITLE
404 on launchpad's repo

### ISSUE THREAD

**Issue by barrystyle** [ethereum/go-ethereum#16225]
As per installation doc; apt-get update results in:

W: Failed to fetch http://ppa.launchpad.net/ethereum/ethereum/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

Bit of a worry, seem to recall it being like this 2+ years ago.
Went with cpp-ethereum but y'know..

**Comment by karalabe** [comment]
We're only providing Ubuntu packages via the PPA, not debian ones.  The PPA is at https://launchpad.net/~ethereum/+archive/ubuntu/ethereum.
