### ISSUE TITLE
Please deploy registrar

### ISSUE THREAD

**Issue by linagee** [ethereum/go-ethereum#1622]
Registrar takes 800,000 gas for the code. We're past a million and I have successfully deployed locally with no problems. (0x5564886ca2c518d1964e5fcea4f423b41db9f561)

https://github.com/ethereum/go-ethereum/blob/develop/common/registrar/contracts.go#L162
https://github.com/ethereum/go-ethereum/blob/develop/common/registrar/registrar.go#L61

**Comment by tgerring** [comment]
This isn't specifically a Go issue and isn't quite clear what the problem is, only that you want the devs to bless some specific namereg. Please reopen if there is an actionable problem with the geth client.
