### ISSUE TITLE
Impossible set Solc

### ISSUE THREAD

**Issue by CodersBrothers** [ethereum/go-ethereum#1623]
```
# geth version

Geth
Version: 1.0.1
Git Commit: 82ef26f6007986debd6ce082f57050f0c7e36006
Protocol Versions: [61 60]
Network Id: 1
Go Version: go1.4.2
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.4.2/libexec
```

```
# which solc

/usr/local/bin/solc
```

In geth console
```
admin.setSolc("/usr/local/bin/solc")
```

```
signal: illegal instruction
    at InvalidResponse (<anonymous>:-60926:-37)
    at send (<anonymous>:-124886:-37)
    at setSolc (<anonymous>:-113803:-37)
    at <anonymous>:1:1
```

**Comment by hynese** [comment]
+1

**Comment by bas-vk** [comment]
What happens when you run solc from the commandline?

`/usr/local/bin/solc --version`

**Comment by CodersBrothers** [comment]
Some weird! Return
```
Illegal instuction: 4
```

**Comment by karalabe** [comment]
What's your CPU architecture?

**Comment by CodersBrothers** [comment]
Darwin MacBook-Pro-de-gaza.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

**Comment by maran** [comment]
How old is your Macbook? Use "About this mac" if you are unsure. (from the top left Apple icon)

**Comment by CodersBrothers** [comment]
Maybe 2007. Macbook Pro Core 2 Duo. 2.4GHz
OS: OS X Yosemite

**Comment by karalabe** [comment]
Hmm, maybe solc was build with a higher SSE support? Anyone from the cpp or solc team could maybe answer this?

**Comment by zelig** [comment]
This is a solc+platform problem. 
If your solc is working, setting it works too, both in console and command line. 
Closing the issue

**Comment by hynese** [comment]
If I may reopen this case, the solution is to build ethereum with clang enabled.

I am on a MacBook Yosemite (latest consumer release).

Here are my notes:

`brew update`

`brew upgrade`

`brew install llvm --HEAD --with-clang`

`brew uninstall cpp-ethereum` #uninstall the existing cpp-ethereum

`brew tap ethereum/ethereum`

`brew install cpp-ethereum --with-evmjit`
`brew linkapps cpp-ethereum`

#test:
`which solc`
#should return a valid path


#Now run geth:
`geth console 2>>geth.log`

`eth.getCompilers()`
#Should return:
`['Solidity' ]`
