### ISSUE TITLE
Error docker geth image on RPi3 ARMv7 

### ISSUE THREAD

**Issue by stasbar** [ethereum/go-ethereum#16249]
Hello.
I would like to start geth in docker on my Raspberry Pi 3.
I'm using go-client from https://hub.docker.com/r/ethereum/client-go/ and It's working fine on my mac, but It's throwing error on my Raspberry Pi 3:

`$ docker pull ethereum/client-go`
Using default tag: latest
latest: Pulling from ethereum/client-go
Digest: sha256:561f2f96a8283a4262e26f6bbb917212900e0aba591b17e38d6ae4c7331bbccd
Status: Image is up to date for ethereum/client-go:latest

`$ docker run -it --rm ethereum/client-go`
standard_init_linux.go:195: exec user process caused "exec format error"

`uname -a`  Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
`docker --version` Docker version 18.02.0-ce, build fc4de44

**Comment by karalabe** [comment]
The docker images are build for amd64 architectures. They won't run on an ARM CPU. You can download a pre-built binary from your website for the arm builds: https://geth.ethereum.org/downloads/

**Comment by ffaerber** [comment]
@stasbar i created a multiarch(armv7,armv8,amd64) go-ethereum docker image pipeline.
https://github.com/ffaerber/go-ethereum
i use this on scaleway(armv8) never tested on Rpi3(armv7) but should work.
try `docker pull ffaerber/go-ethereum`
