### ISSUE TITLE
wget https://ethereum.github.io/go-ethereum/downloads/$(uname -m)/latest/ arch dependent image

### ISSUE THREAD

**Issue by stasbar** [ethereum/go-ethereum#16258]
Hi there,
I'm building Dockerfile that will download and run precompiled geth from https://ethereum.github.io/go-ethereum/downloads/ 
But I want to run this image on different CPU architectures, so each time I need to download arch-specific geth image from https://ethereum.github.io/go-ethereum/downloads/

My current Dockerfile (working great on ARMv7 RPi3)
```yaml
FROM ubuntu:latest

# Install wget
RUN	apt-get update \
    && apt-get install -y wget \
    && rm -rf /var/lib/apt/lists/*

#Download geth and copy into /usr/local/bin
RUN    mkdir gethDownload \
    && wget -qO- https://gethstore.blob.core.windows.net/builds/geth-linux-arm7-1.8.1-1e67410e.tar.gz \
    | tar xvz -C gethDownload --strip-components 1 \
    && cd gethDownload \
    && mkdir -p /usr/local/bin \
    && mv geth /usr/local/bin/ \
    && cd .. \
    && rm -r gethDownload

EXPOSE 8545 8546 30303 30303/udp 30304/udp

ENTRYPOINT ["geth"]
```
but I would like to make it more generic. 
Is there any way to download latest stable version for my arch ?
Something like `wget "https://ethereum.github.io/go-ethereum/downloads/$(uname -m)/latest/"`
Yes, I know, it's easy to say, but just wondering if there is way to achieve it other way than hardcoding urls.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
