### ISSUE TITLE
Some nodes are unable to get past #55512

### ISSUE THREAD

**Issue by drupalnomad** [ethereum/go-ethereum#1625]
```
I0809 05:37:53.545691   28852 downloader.go:278] Block synchronisation started
I0809 05:37:55.224961   28852 chain_manager.go:662] imported 0 block(s) (0 queued 1 ignored) including 0 txs in 1.193437195s. #55511 [8b62537e / 8b62537e]
I0809 05:37:55.235382   28852 chain_manager.go:778] Bad block #55512 (dfd8f1d1424d65f623c6bad670580155fc1f6d4cc488e67fe0cbaf1fdbf84afb)
I0809 05:37:55.235433   28852 chain_manager.go:779] gas used error (221000 / 142596)
I0809 05:37:55.235564   28852 downloader.go:254] Synchronisation failed: block downloading canceled (requested)
```

Weirdly most of the network doesn't have a problem with the exact same block. (same hash)
https://etherchain.org/block/55512

geth recover does not work either:
`panic: runtime error: index out of range`

**Comment by rfikki** [comment]
I can confirm I am having the same issue.

**Comment by drupalnomad** [comment]
There were several nodes stuck at #55511 and #55512 on the stats page.

**Comment by obscuren** [comment]
@rfikki still got your chain?

**Comment by drupalnomad** [comment]
switched from develop to 1.0.1 and it fixed it. This is strange because the nodes on the stats page that were stuck were on 1.0.1

**Comment by drupalnomad** [comment]
Is my chain still of use to you ?

**Comment by obscuren** [comment]
Ok, `develop` (unstable) branch seems to be broken. `master` still good

**Comment by obscuren** [comment]
Did you run with `--jitvm` ?

**Comment by drupalnomad** [comment]
No, but it seemed to happen just as I published a contract.

**Comment by rfikki** [comment]
Yes, still have my chain.

**Comment by obscuren** [comment]
Latest develop does no longer have the JIT enabled default (and shouldn't have).

I'll continue to investigate

**Comment by CrConstantin** [comment]
Same problem with other blocks too, like #65512 :

15184 chain_manager.go:774] Bad block #65512 (d98dda89b36bbfa8cd9e64a1c0b853832740d67e6113fac4f0e093cc724ae786)
15184 chain_manager.go:775] Transaction w/ invalid nonce. tx=188  state=0)
15184 downloader.go:254] Synchronisation failed: hash fetching canceled (requested)

I am using latest version as of today "Version: 1.0.1", updated with "apt-get upgrade".

I had to "geth removedb", then delete ".ethereum/dapp" and ".ethereum/chaindata", then start geth from block zero.

**Comment by obscuren** [comment]
@CrConstantin that's correct. You had the misfortune you were using a bad `develop` commit (can't stress enough that `develop` should not be used for production stuff) and upgraded your database.

@drupalnomad if you update now (using latest `develop`) and remove your database you should be good to go (migration should now work, too)

**Comment by sirhill** [comment]
I had this problem using the raspberry pi arch linux image. I did like croqaz and it saves me a lot of time. I am still discovering ethereum, but I will probably redo a more recent image for the raspberry pi (seems to be over 6/7 month old).
