### ISSUE TITLE
a feedback about the cheat and fraud of etc eth on twitter

### ISSUE THREAD

**Issue by sinoory** [ethereum/go-ethereum#16257]
Hi eth:
this is not a code bug, but a feedback about the cheat and fraud of etc eth on twitter.
I really don't know where to tell you eth or etc , twitter frozend, email can't send out,
official forum registry always failure,  so finally i come here.
All the detail is in the cheat.jpg attachment file(but upload failed). 
i past the text part here:
![Uploading cheat.jpg…]()

eth and etc is two great project. 
as i can't find the etc email, hope you can kindly cc to etc too, thanks.

A few days ago on Twitter to search for the etheric classic, found an account, it is concerned, look at the news every day. About 5 o'clock this afternoon, find out of a message, as shown below (screenshot after the event):

Earlier in the message there are a few words that the eth is to open a little test time, if you go to the address https://etherscanio.github.io/etherscan.io.html and send 3 eth ,it will be returned to you 30 eth. At the time I thought it was an official classic Ethernet Twitter, i did not think too much, send three eth to the account:

but i did not receive the back of the transfer, it is estimated fooled. Back to Twitter, I saw part of the msg about x10 eth deleted, but some people curse:

I also Twitter Leave a message Asked:

but my account was frozen after some time. . .

I am very surprised, why official etc Twitter have such a thing?

I do not know the loss can recover? Are there more people fooled? etc to leave more people a bad impression?

We are expecting a reply!

if any feadback, you can send email to sinoory@126.com or sinoorytwo@gmail.com, 
or ask with email to get the cheat.jpg to see more detail ,3xs!

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by sinoory** [comment]
ok, can you also kindly supply the valid email of eth or etc? i think the cheating on twitter maybe is a critical bug to the eth and etc ecosystem

**Comment by ligi** [comment]
not sure what you mean ..

**Comment by sinoory** [comment]
you can read the cheat.jpg for more detail infomation.
![cheat](https://user-images.githubusercontent.com/13250194/37006228-5efc6bee-2112-11e8-9887-cb0b864f4f8c.jpg)
i found the info@ethereum.org email on the officail website https://www.ethereum.org/ ,
but email send failed as said not a valid address

**Comment by ligi** [comment]
I am sorry you got scammed. This scam-pattern is very typical and unfortunately happening a lot recently. Unfortunately mailing the Ethereum foundation will not really help you. It is the same as when you would try to mail Tim Berners Lee after you where falling for some Nigerian King spam.

>  i did not think too much, send three eth to the account

this is the main problem - please think and verify before you send ETH around.

> i found the info@ethereum.org email on the officail website https://www.ethereum.org/ ,
but email send failed as said not a valid address

OK - this is really a problem and I will try to contact people that this gets sorted out. But even after it did - I do not think writing a mail there will get you your ETH back. I think this is just gone and I hope it at least teached you an important lesson.

**Comment by sinoory** [comment]
okay，i learned a lesson in few mins by almost a few month salary. thank you reply at the same time
