### ISSUE TITLE
go version check fails for go >= 1.10

### ISSUE THREAD

**Issue by girafi** [ethereum/go-ethereum#16252]
With the current version of go installed (1.10), the "make geth" commands fails with the message that go version must be at least 1.7

#### System information
Geth version: 1.7.3
OS & Version: OSX High Sierra

#### Expected behaviour
version 1.10 and above should be supported

#### Actual behaviour
make aborts

**Comment by karalabe** [comment]
This is fixed for the 1.8 series.
