### ISSUE TITLE
change the md5 checksum from geth 1.8.2, it is not downloaded automatically ethereum wallet

### ISSUE THREAD

**Issue by 3ASlanec** [ethereum/go-ethereum#16266]
Всем привет,обратите внимание, что это трекер ошибок, зарезервированный для отчетов об ошибках и запросов функций.Для общих вопросов, пожалуйста, используйте канал gitter или обмен стека Ethereum на https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by rojarsmith** [comment]
Kayspersky detect the virus on the geth 1.8.2 exe file.

**Comment by 3ASlanec** [comment]
Yes, found the worm. In previous versions not found. While I will not download.

**Comment by karalabe** [comment]
The checksum mismatch was Mist not updating the checksums and still using the ones for 1.8.1 https://github.com/ethereum/mist/issues/3730

As for the Worm, https://www.virustotal.com/#/file/d0245d3c6b909d0ac8bdf5a1f195bbc85dc805a904ce18452afcf3f267898ae3/detection seems to indicate it is a false positive. I've submitted it to Kaspersky to be reanalyzed.

**Comment by karalabe** [comment]
Kaspersky reports it clean with today's virus database.

**Comment by 3ASlanec** [comment]
good news, everything checked.
