### ISSUE TITLE
getBalance shows 0 from ropsten

### ISSUE THREAD

**Issue by arnabsinha4u** [ethereum/go-ethereum#16260]
Hi there,

Even after complete sync of ropsten, I consistently get balance zero

#### System information

Geth
Version: 1.8.2-unstable
Git Commit: 66cd41af1e3827f9f834ca6ea98d6964d2388f77
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/golang

#### Expected behaviour
Show the actual value which is visible via the ropsten website should be visible from web3.eth.getBalance('0x781c22ec9c5a7f860b127c90c207e817e7f8b520')

#### Actual behaviour
web3.eth.getBalance('0x781c22ec9c5a7f860b127c90c207e817e7f8b520') gives output 0

#### Backtrace

````
[backtrace]
````

**Comment by Afe95** [comment]
Are you attaching to the right network?

**Comment by arnabsinha4u** [comment]
Yes, attaching to the right network... double checked that.

**Comment by TTroia** [comment]
me too!and my contract has disappeared, too
