### ISSUE TITLE
connect to main network of ethereum in my codes using web3.js

### ISSUE THREAD

**Issue by mxito3** [ethereum/go-ethereum#16276]
do you know how to call functions of contract in main network of ethereum in my codes using web3.js?i want to connect to it then transfer my own coin.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
