### ISSUE TITLE
Fatal: Error starting protocol stack: sync /root/.ethereum/geth/chaindata: invalid argument

### ISSUE THREAD

**Issue by madlink** [ethereum/go-ethereum#16278]
I'm trying to run a full node on windows and it keeps failing to start when i set the volumen.

The volumen is correctly set and, i can see the folders geth and keystore getting created by the container.

#### System information

Geth version: `1.8.3`
OS & Version: Windows 10

#### Actual behaviour

```
INFO [03-07|18:32:27] Maximum peer count                       ETH=25 LES=0 total=25
INFO [03-07|18:32:27] Starting peer-to-peer node               instance=Geth/v1.8.3-unstable-3ec1b9a9/linux-amd64/go1.9.4
INFO [03-07|18:32:27] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=768 handles=1024
Fatal: Error starting protocol stack: sync /root/.ethereum/geth/chaindata: invalid argument
```

#### Steps to reproduce the behaviour
```
docker run -it --name ethereum -v C:/Users/Miner/Documents/EthNode/node-data:/root/.ethereum -p 30303:30303 -p 8545:8545 -p 8546:8546 ethereum/client-go:latest --ws --rpc --rpcaddr "0.0.0.0" --wsaddr "0.0.0.0"
```
Any ideas on how to fix it?

**Comment by Greatsamps** [comment]
I am having exactly the same problem

**Comment by amansur** [comment]
I have this problem as well when trying to mount a volume. If I don't mount a volume, it starts fine.

**Comment by slavitch** [comment]
As am I on v1.8.11-stable

INFO [06-27|18:03:05] Maximum peer count                       ETH=25 LES=0 total=25
INFO [06-27|18:03:05] Starting peer-to-peer node               instance=Geth/miner/v1.8.11-stable-dea1ce05/linux-amd64/go1.10.3
INFO [06-27|18:03:05] Allocated cache and file handles         database=/etc/testnet/miner/geth/chaindata cache=128 handles=1024
Fatal: Error starting protocol stack: sync /etc/testnet/miner/geth/chaindata: invalid argument
Fatal: Error starting protocol stack: sync /etc/testnet/miner/geth/chaindata: invalid argument

**Comment by bizlevel** [comment]
Anyone resolve it?

**Comment by vedhavyas** [comment]
Apologies for that.
I got the following error while starting up the geth docker image with shared volume.
```
Fatal: Error starting protocol stack: sync /etc/testnet/miner/geth/chaindata: invalid argument
Fatal: Error starting protocol stack: sync /etc/testnet/miner/geth/chaindata: invalid argument
```

My docker client and server versions were different. Installing the client and server of the same version(18.06.0-ce in my case) fixed the issue.

**Comment by slavitch** [comment]
This has nothing to do with Windows. I'm running using Ubuntu 16.05 hosts on Kubernetes.

**Comment by holiman** [comment]
My hunch is that it has to do with file permissions on the underlying os. What are the file permissions on the mounted volumes that you're trying to use inside the container?

**Comment by holiman** [comment]
For the original report:
`C:/Users/Miner/Documents/EthNode/node-data` is mounted as `/root/.ethereum`. 
Please report the permissions on `C:/Users/Miner/Documents/EthNode/node-data` , and do a `docker inspect` the running container.

**Comment by FrankSzendzielarz** [comment]
Confirmed as reproducible with v1.8.3 but fixed in docker image :latest at time of writing. Also note on Windows, Linux geth  in the docker container will attempt to bind an IPC endpoint into the volume. A workaround is --ipcdisable eg:


 docker run -it --name ethereum -v C:/Users/<user>/Documents/EthNode/node-data:/root/.ethereum -p 30303
:30303 -p 8545:8545 -p 8546:8546 ethereum/client-go:v1.8.3 --ws --rpc --rpcaddr "0.0.0.0" --wsaddr "0.0.0.0" --ipcdisable
