### ISSUE TITLE
Transaction having low gasPrice makes all the other transactions hang on the pending state.

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/go-ethereum#16284]
I have a small private network that has a proof-of-authority engine created via `geth-clique` using `Geth Version: 1.8.3-unstable`, currently there are three signer nodes and two other non-signer nodes (lets call them `peer-A` and `peer-B`). `peer-A` and `peer-B` are connected to three signer nodes.

First, I sent a transaction with very low `gasPrice` such as 200, on `peer-A` as shown below.

    eth.sendTransaction({from:eth.accounts[0], to:eth.accounts[1], value: web3.toWei(0,0000, "ether"), gasPrice: 200})

Later when I sent more transactions on `peer-A` even with greater `gasPrice`, all of those transactions will remain on the pending state. As I understand submitted transactions work as FIFO queue and my upcoming transactions are stuck 
since the first send transaction with very low `gasPrice` locks others.

Example: (First `peer-A` and `peer-B` sent a Tx with low `gasPrice` and later their other Tx with high gasPrice stuck on their pending state.)
[![enter image description here][1]][1]

I have fix this situation by cleaning my `chaindata` on `peer-A`, which also cleans all pending transactions: `rm -rf private/geth`, and later I send my transactions with larger `gasPrice`. I assume this was a very inefficient solution for networks has a large chain.

So all sent transactions are provided as FIFO queue? Why not they selected based on which has the highest `gasPrice`? 

Please note that I have tried: 

    eth.resend(eth.pendingTransactions[0], web3.toWei(1000, 'gwei'))

but faced with following error:

 `Error: intrinsic gas too low` or `Error: replacement transaction underpriced error.`

**[Q]** How could I solve this problem, how could I remove the pending transaction on the system which has a low gasPrice or reject them or update their `gasPrice` value and `resend()` them? 

  [1]: https://i.stack.imgur.com/JHptu.png

**Comment by karalabe** [comment]
Every account and transaction in Ethereum has a nonce. At any given time, only the transaction with the correct nonce can be executed. If you submit a transaction with a low gas price, that will block all subsequent transactions since they are not executable nonce wise, only the next nonce is executable.

You don't need to clear your chain data folder, pending transactions are not stored there. There's a `transactions.rlp` file which saves the local transactions. However, that's also unneeded, you could just resubmit the same transaction with a higher gas price. Not sure why that doesn't work for you though, I'll try to repro it on Rinkeby.

**Comment by karalabe** [comment]
Ok, found the issue.

`eth.resend` takes 3 parameters

 * The transaction to resend
 * The new gas price 
 * The new gas limit

Normally the gas limit is optional, however a refactor long ago broke it, so if it was not specified, resend tried to set it to 0, causing the intrinsic gas too low. You can solve it currently by explicitly specifying the gas limit too. I'll open a fix that makes it optional again.

**Comment by avatar-lavventura** [comment]
Thanks @karalabe . Doing following solved it:
`eth.resend(eth.pendingTransactions[0], web3.toWei(20, 'gwei'), 2000000)`

But after cleaning `transactions.rlp`, it did not the remove pending transactions :
`rm eblocPOA/private/geth/transactions.rlp`

**Comment by karalabe** [comment]
The transactions.rlp is only updated every hour + node start/shutdown. You'd need to stop your node, delete that file and restart.
