### ISSUE TITLE
ropsten network problem

### ISSUE THREAD

**Issue by freshonline** [ethereum/go-ethereum#16288]
my balance was reset:
https://ropsten.etherscan.io/address/0xC1320531dF2612B85e6FEDFd4d6358ed711bbe66
--mine flag do not work.
I ordered coins for a new address here:
http://faucet.ropsten.be:3001/
balance zero
https://ropsten.etherscan.io/tx/0xc043883245f480bedf5cb40e9b122417cdff6e5c575c03a20ce21db5817b0589
https://ropsten.etherscan.io/address/0x00376bad29311f3f15fcfbace1930b16a4f1a7ff
geth 1.8.2

**Comment by freshonline** [comment]
I remove all old accounts end created new:
```
/usr/bin/geth --rpc --networkid 3 --rpcapi db,eth,web3,net,admin,miner,personal --fast --cache 1024 --maxpeers 25 --datadir /home/testnet/.ethereum --keystore /home/testnet/.ethereum/keystore --nousb --mine --minerthreads 1 --unlock 0xd97147e5663e83adeb103c84de3ee1a6d19e54fa --password /home/testnet/pass
```
https://ropsten.etherscan.io/address/d97147e5663e83adeb103c84de3ee1a6d19e54fa
New problem. I can not understand this.
It breaks every time.

**Comment by karalabe** [comment]
If you want to run Rospten, run with `geth --testnet`.
