### ISSUE TITLE
geth console special character/encoding problem

### ISSUE THREAD

**Issue by philsmd** [ethereum/go-ethereum#16286]
#### System information

Geth version: `1.7.2`
OS & Version: Windows 10
Commit hash : release version downloaded by Mist (1db4ecdc)

#### Expected behaviour

Copy pasting text into the geth console should leave the copied text unmodified and should not strip any characters.

#### Actual behaviour

Special characters (non-ascii) will be ignored/stripped by the geth console (it seems that this has to do with certain keyboard languages, but it works outside of the geth console) and this could result that passwords are set incorrectly. Even unlocking accounts with passwords including special characters might fail even if it shouldn't, see also https://github.com/ethereum/mist/issues/3513#issuecomment-370180696 (search for "Let's talk about problem number 2:" within that post to fast forward to problem number 2 within that post)

#### Steps to reproduce the behaviour

0. this was tested/confirmed under windows, but it could be that it has nothing to do with the OS (but the main reason could be the differences between certain keyboard languages) 
1. download/run geth (it seems that a lot/all versions are affected, but this needs to be confirmed/tested)
2. set your keyboard language to e.g. English US, my default one (I also tested with German keyboard language)
3. run "geth console" (without quotes)
4. try to paste non-ASCII characters into the console or password prompt (e.g. the character with hex value 0xd3, i.e. Ó)
5. the special characters will be ignored, which could be very dangerous because passwords might be set incorrectly and unlocking (for instance if the user just wants to see if the password is correct) might fail even if the password specified was correct

Note: I want to emphasize that the copy pasting only fails to work within geth, other tools and the same terminal (cmd) are able to get the whole input including special characters

Confirmation video (also see screenshots from https://github.com/ethereum/mist/issues/3513#issuecomment-370180696); this is a screen record to show what is happening:

![ethereum_geth_console_special_characters](https://user-images.githubusercontent.com/921533/37151987-05a54904-22d8-11e8-83cb-a47777494df7.gif)

Note: before I started geth.exe the copy pasting of all characters worked (even with my default English US keyboard layout), but it failed within the geth console... it suddently started working when changing to the English United States International keyboard layout... it seems to be geth related because it works outside geth with each and every keyboard layout.
It is needless to say that this same behaviour can be observed with any other geth commands and also with the password prompts (which is very dangerous! and the main reason that I've discovered this problem, see https://github.com/ethereum/mist/issues/3513) etc. I decided to paste the character as a command (or let's say directly within the geth console, without using the password prompt etc) because it makes it more clear what is going on because this way we can see which characters are actually pasted and which ones are ignored 

What is the effect of this problem:

1. the user could unintentionally set a password that s/he doesn't want to set (personal.newAccount ()), the password could be very different depending on how many special characters s/he used, it could even be empty in the worse case even if the user wanted to set a very difficult password with many special characters
2. the user can't unlock this newly created keystore files with the correct password (if it includes special characters) whenever s/he tries to use 3rd party tools (which accept the special chars)
3. the user might not be able to unlock keyfiles generated by 3rd party tools (if they accepted the special characters but geth fails to accept them)
4. other commands (besides the password cmd) might be affected the same way and could also lead to strange/unintended outcomes
.... etc

CC: @evertonfraga, @karalabe, @holiman

**Comment by holiman** [comment]
Geth uses https://github.com/peterh/liner under the hood. I'm curious if how the little app here https://github.com/peterh/liner#getting-started would behave on your system.

**Comment by philsmd** [comment]
Hey @holiman, thanks for your fast reply and the hint about liner.

I tested the code from https://github.com/peterh/liner#getting-started now. I compiled it with GOOS=windows GOARCH=amd64 go build -o peterh_liner.exe peterh_liner.go

This test shows that liner alone is not affected by this problem. Maybe geth is using some special modes etc, but the little app does allow posting special characters.
I have a screenshot to proof this for you. BTW: it doesn't matter which keyboard layout I set, the peterh liner little app test always work (similar to the pasting directly within cmd), but it fails when I paste in geth.

![liner_test](https://user-images.githubusercontent.com/921533/37159275-b3c97856-22ed-11e8-9e08-313a28a07994.jpg)

As you can see the keyboard layout in the screenshot above is my default one which failed with geth. With the little liner app I have no problems pasting special chars

**Comment by holiman** [comment]
Thanks for checking!

**Comment by philsmd** [comment]
I decided that this problem is significant and risky enough (it could mean a lot of trouble for many users, because I guess a lot also users of geth on windows with non-international keyboard layouts) so that I dedicated quite a lot of time today to troubleshoot this problem.
The following is a little bit of a story telling, please forgive me:
I decided to try if I can compile geth entirely on windows (without cross-compilation and without running the pre-compiled binaries) for the sake of being able to make modification to the golang source files etc.
I actually managed to compile the whole geth on windows without many problems with these instructions: https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows#compiling-geth-with-tools-from-chocolatey ( I think this guide is pretty good, except that I think after the "cd src\github.com\ethereum\go-ethereum" command the prompt in the guide should be "C:\Users\xxx\src\github.com\ethereum\go-ethereum>" already. Furthermore, the guide should tell you where the geth binaries are: they are located in %USERPROFILE%\bin\geth for instance)

After seeing that also the newly compiled geth binaries fails @ encoding, I inserted the example code from liner: https://github.com/peterh/liner#getting-started into the geth source code at a very early stage where geth is still initializing (I think I inserted it after this line https://github.com/ethereum/go-ethereum/blob/1488fdaf19cebdb79478bd4949b99d3f0d053419/console/prompter.go#L82).
The outcome: a total surprise! even if I inserted the code at the beginning of geth it still didn't work. no special characters pasted/allowed.
My idea now was to compile the little liner standalone app (https://github.com/peterh/liner#getting-started) without any geth code, just to make sure that it still works (I compiled it within the go-ethereum directory. on windows directly).
Again a surprise: now the little liner app also didn't work anymore!

I tried to see if the old liner exe file I compiled (see previous posts) still worked, or if it was some terminal/keyboard language problem. I moved to the other geth directory and run it. Surprise again: it worked perfectly!
First, I thought it was the cross-compilation, because I compiled the old liner exe file with a linux (my usual/preferred os). next idea: try to compile the liner app again within this changed directory.
Now comes the funny part:
I got the error that I can't compile the little liner app and that I need to "go get" the perterh liner app source code! WTH? I just compiled it without any problems. It told me that I have to "go get github.com/peterh/liner", why didn't it tell me previously that I had to do so!?

Now I of course realized pretty quickly what was going on, geth ships it own source files of the peterh liner app see: https://github.com/ethereum/go-ethereum/tree/master/vendor/github.com/peterh/liner
That explains why the first version was able to compile without the "go get" and why the first version was still misbehaving while the newer version directly downloaded from https:github.com/peterh/liner was working perfectly fine and I had to "go get" it.

Funny coincidence that I was going through this changing-directory-decides-if--it-fails-or-succeeds mess, right?

Anyway, putting the newer source code of liner (from github.com/peterh/liner) within the vendor/github.com/peterh/liner/ directory of geth made the geth binary working (with special character support) again for me! Success

I also took some time, just for fun now, to locate the commit that fixed the problem in liner (this is the first version that works for me):

https://github.com/peterh/liner/commit/161ea9c37d6d4e97afe7f8f9cde7e647d49bd091

(it's currently the latest commit in liner and the commit message talks about fixing problems with surrogate pairs etc. It's actually funny that this problem was fixed just 21 days ago in the liner repository. I think we should use the latest versions of liner if no problems are detected within geth during testing with the newest liner version)

There is one **big problem** now that you shouldn't ignore. There are potentially many accounts now out there that can only be unlocked with specific versions of geth who ignore the special characters etc. The problem is similar to this one https://github.com/ethereum/go-ethereum/pull/2371. You can't just fix the problem, but you also need to make sure that the old accounts still can be unlocked. One possibility would be to test unlocking also with the "stripped special character" version of the password if the typed password (with special chars) did not work. I think this needs to be done on each and every supported platforum even if the problem seems to be windows-specific, because it could happen that a user created the file with geth on windows and later on tries to unlock it with geth on linux/mac. I would also suggest to show some warnings and hints for instance when geth detects that the password did only work with the modified password and also that geth tells the user (it should explain why) it also tries with a modification because of this bug etc!

I hope you appreciate this contribution / troubleshooting. It was actually a lot of messing around and trying to figure out wth is going on with this liner lib. If also just some people have less problems with passwords/encoding in the future because of this "research"/fixing it was definitely worth it. I even tried to test the encryption/decryption with password recovery tools just to make sure that with the newer liner version also the whole set of bytes of the password is the expected  one (UTF 8 encoded password with all special characters), it worked with all my tests now!

BTW: I just found out that this problem was actually already mentioned (and people were struggling with it) in other issues (a little bit hidden therefore I didn't find this post beforehand) and I think the root cause is exactly the same (namely the old liner code!): see https://github.com/ethereum/mist/issues/3176#issuecomment-349403728

What we can learn from this: it often makes sense to update the included/imported libs, because there could be a lot of problems that were fixed with newer versions of them.

Can you guys please suggest how you plan to properly fix this? liner update + code which also tries the modified password (at least for several future versions of geth) cc: @karalabe, @holiman

**Comment by holiman** [comment]
Thanks for the investigation!

We do update the 'vendored' libraries from time to time -- and I guess updating 'liner' would be good. IIUC, the TLDR is "Copy-pasting geth console in windows may have dropped certain special characters".

Also, if I'm reading it right, this does not concern accounts that have been created through Mist.

**Comment by philsmd** [comment]
yeah exactly.
but what if newer versions of geth suddently start accepting the special characters that the user have typed/pasted ? the stored/remembered password does not work anymore !
that's a huge problem and you can unfortunately only fix it by trying both version of the password when unlocking accounts

**Comment by philsmd** [comment]
are there any updates here ?

I find the thought quite disturbing that dozens (maybe much, much more) of users could potentially create accounts with geth each and every day that are generated with a different password compared to the password the user set. This is horrible and this should be address pretty quickly.
I mean this isn't a rare situation at all. At least all windows binary (and the master source code) are affected by this bug. This problem kind of affects every windows user if they didn't set an international keyboard layout (i.e. only the English United States International layout seems to be an exception for some reason, which might be only used by very few users) and used non-ASCII characters within their password.

As already mentioned, this problem also leads to other problems like the user can't use this keystore file with 3rd party tools like mycrypto/myetherwallet (because they don't mangle the password input in the same way the geth-liner-combination does) and you also can't use mist UI etc if the key was generated with geth beforehand (because the password, when we look at this specific bug, only gets screwed-up by the geth-liner combo).

I think there is absolutely no plausible reason to wait until even more (hundreds/thousands?) of keystore files are generated "incorrectly" (with wrong password)... I reported the problem about 3 months ago and it seems the users noticed some strange behaviour even much, much earlier (though nobody seemed to identify the main cause before I opened this issue). Why risk that even more keystore files are incorrectly generated ? This should be escalated and handled very responsible and by considering all aspects of the changes (like I already mentioned: what if the keystore file was generated with the mangled password, but in upcomming versions geth uses the "correct" password input? both versions of the password - mangled/raw - must be tested, on each and every platform).

You might have more numbers/stats available than I have, but my guess is that there are a lot of windows geth downloads and also a lot of users that do not use ASCII characters at all (their keyboard is non-english, uses non-latin characters in general !!!) and/or a lot of users try to set a difficult password with special characters/umlauts etc... all these cases lead to a INCORRECT keystore file, I you know that this happens since about 3 months and did nothing against it! This is a horrible fact and I find it very careless of you to not address problems like this with highest priority and uttermost diligence.

I mean ... the exact problem was already carefully analyzed and reported and even the reason/fix was already proposed by me (i.e. update liner + test for mangled password) ... the only thing missing is the code that checks both versions of the password to not risk that all old/affected keystore files are completely useless (and to not risk that not only they don't work with 3th party software, but also do not work anymore with newer versions of geth... if the fix is not handling these special cases/keystore files).

I think somebody needs to escalate this problem if nothing happens within the next few days/weeks. Maybe we should at least let the ethereum twitter and reddit community ask what they think of this bug and how this was (not) addressed within a timely manner.

Finally, I just want to make sure that nobody gets this/me wrong: I'm not trying to blame somebody for this problem or accuse somebody of something... but thinking about hundreds/thousands of keystore files that are completely wrongly generated and the devs ignoring it for months makes me a little bit alerted and frustrated. I see no reason why devs do this to their users (maybe they just forget/ignored the issue, but I think it's horrible enough that it can't be simply ignored !).
cheers

**Comment by holiman** [comment]
Gotcha, we're on it. 

It's a very peculiar circumstance where someone would get bitten by this, and the wallet could always be recovered again using the same setup as where it was first set, so as the path forward was a bit unclear, it slipped under the pile of things to do. 

We could add a 'canonicalizer', if a password fails and the 'canonical' version of the password is different from the password, we can attempt that too.

**Comment by holiman** [comment]
I've asked @kurkomisi try to repro this on a similar system. He will post the specifics, it seems we'll need to investigate further about what exactly is causing this issue, because while UTF-16 surrogate-pairs are dropped, characters such as `Ó` works fine.

**Comment by philsmd** [comment]
I'm not sure what you mean by it works with  _Ó_ . The screencast above clearly shows that there is a problem also with that specific character on the system(s) I tested with.
As I already mentioned here the character is encoded to 0xc393 in utf8: https://github.com/ethereum/mist/issues/3513#issuecomment-370945588 , the same character utf-16 encoded might be different again. I'm pretty sure it uses 2 or more bytes for that character and this is the reason why the bug may trigger. Well, encoding is difficult and therefore it might need some more investigation.
I also want to emphasize that the system(s) I tested with are not using any strange (non default) settings or any strange language or keyboard settings (it's a normal windows system, the only thing I added later on was the additional german and international keyboard layouts because I wanted to see what happens with these settings).

**Comment by holiman** [comment]
Yeah I didn't mean there was no issue, just saying that we failed to reproduce it on a windows 10 with geth 1.7.2 and US (Eng) keyboard. So we'll likely need to dig further.

**Comment by holiman** [comment]
So, regarding the case you linked above, where a user thought he had used `FußRoDah`, but managed to unlock it with `FusRoDah`. If you believe that that was caused by this bug, then that means that the character `ß` was replaced by `s`, which does not appear to be the case in this bug. 

As I've understood this bug report (and I'm asking for confirmation here because we haven't been able to reproduce it). 

* Characters above `127` are dropped. 

Could you please, on your system, with the old `liner`, check what happens to the string `FußRoDah`? If the character is dropped, then that linked case is not caused by this issue. And it also means that the solution for this issue is much simpler, if it involves only dropping all non-ascii characters from the password and attempt again.

**Comment by philsmd** [comment]
Hey @holiman, first of all, thanks for your effort in troubleshooting this.

I think the FusRoDah vs FußRoDah example is a little bit confusing indeed. As far as I understand, the user said that 0xAccountA with password FusRoDah (which is a **complete independent** account) does work without problems, while the account 0xAccountA with password FußRoDah does not work (but again account 0xAccountA and 0xAccountB are not related at all, you can not make any conclusion if either of them works, because there is no dependency, not even when we look at encoding or character codes etc). I think that the user just mentioned both cases, because as far as I know within German writings you sometimes (need to) replace the Eszett (sharp s) character, because some documents/forms do not allow special characters (in these specific cases I think ß is replaced by two s or something like this), but this is not really something we need to worry about here.
Basically, the example just showed that it works with a charset from [a-zA-Z] but doesn't work with special characters.

... but I also need to admit that now reading the post again carefully, the reporter said that it never worked  for them, not even without the sharp s character. I didn't yet test the esszett example myself, I will of course do it as soon as possible because this might be somehow related here (or also completely independent and maybe the other post is not related with this issue at all. we will see).

I agree that the solution might be easy, but you still need to somehow deal with old keystore files.
Since the liner patch (https://github.com/peterh/liner/commit/161ea9c37d6d4e97afe7f8f9cde7e647d49bd091) worked for my system, I guess that we need to cover all cases where basically these bytes from the ALT key event (as far as I understood this event is misused and also triggers when the alt key is NOT pressed) were ignored in previous versions of liner.

I'm not sure why you can't reproduce it. I do not think that it has something to do with 0x7f, but with characters that are at least > 0xff or > 0xffff (utf-16 for instance?, I'm not yet sure what the first character is that is ignored by older versions of liner, but I will test this too).

Stay tuned...

**Comment by philsmd** [comment]
This must be a joke.

Are you serious ? Why was this issue closed ?

We've discussed in depth within the above posts that you can't just update the dependencies and do as if the wrong-password bug with special characters was never a thing and that this bug never existed.

This is similar to the bug here https://github.com/ethereum/go-ethereum/pull/2371 where the fix was also completely wrong, if you look at the user experience... That old fix for instance (also) made it even worse, because now the users can't even test with the old password (with wrongly added newline characters in that specific case).

Why are people even wondering why threads like this with user claiming that geth/mist set the "wrong password" https://github.com/ethereum/mist/issues/3513 are that long and very confusing/weird if you are that reluctant to fix the problem properly and address all points that were raised above ?

This is not how you fix issues, you should know better. You are risking to lock people out of their wallets and making it even more annoying to understand what the real password (versus the incorrectly used password set by geth) is.

cc @holiman , @evertonfraga

**Comment by holiman** [comment]
We decided that the right approach would be to update the liner to behave correctly going forward. That said, it's true that there might be corner-cases where people are using a wallet with a 'corrupt' password. 

However, this bug has nothing whatesoever to do with anyone who has set password via Mist: this concerns only this case:

* Users on Windows who are copy-pasting passwords directly into the geth console
  * and, it seems, also has some strange locale/ and or/ keybooard settings

So it's probably better to use the correct liner, and maybe provide an additional binary, e.g. `mirror`. 

Suggestion: The `mirror` binary could use the old liner, and basically do
`` 
This the echoing liner-tester. Any input you paste will be echoed back in hexadecimal form 
> 
``` 
The user could then copy-paste his password, and see what the corresponding hexdata is. He could then store that (binary) data into a password file, and use for unlock. 

Such a binary could also help us discover more information about this corruption, and eventually add the required rules/manglings to adjust for this quirk internally within geth/clef. 

How does that approach sound?

**Comment by philsmd** [comment]
I mean that would be a first start, but it doesn't really solve the problem and is also not really user friendly and very practical.
How are users notified that they need to use the "mirror" binary ? Kind of nobody would use it at the end. They will just freak out why there password stopped working and they will try to use some online wallet (maybe even a scam site) instead. 

The main problem is that there might be a considerable large amount of windows users affected by this problem that for instance used password managers to generate the password with special characters etc and that won't even think about trying to test their password anytime soon ("hodlers" ?). They might try to unlock their account in a couple of months/years and won't get any hint why the password is not working anymore (yeah, I saw that you are planning to add a line within the changelog about this, but who reads the changelog anyway ?) There must be at least some kind of warning if the password does not work within the console itself and when the raw input/password meets the pre-requisit for this bug: windows user/special ALT characters

**Comment by philsmd** [comment]
Please reopen this github issue. The problem is **not** fixed. The patch made the problem even worse for the users affected.
