### ISSUE TITLE
import a account to key store using Json file  of key when connect to main networ!

### ISSUE THREAD

**Issue by mxito3** [ethereum/go-ethereum#16297]
how to import a account to key store using Json file  of key when connect to main network!

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
