### ISSUE TITLE
geth hangs after 5-10min

### ISSUE THREAD

**Issue by mattiasghodsian** [ethereum/go-ethereum#16292]
Hi,

I am having some trouble with geth, It hangs when syncing and i have to restart the sync every 5-10 min.

`
geth --fast --cache=2024
`

![Terminal](https://i.imgur.com/tqFoWXE.png)
![Terminal](https://imgur.com/jVlLZ4I.png)

i also deleted the .ethereum folder in my home dir a few times, made no difference . I also let it run witout doing anything and it hang on the same block for 1h

#### System information

Geth version: v1.8.2-stable-b8b9f7f4/linux-amd64/go1.9.4 (installed with ppa)
OS & Version: Ubuntu 16.04.4 LTS
Ram: 12GB
Disk: 3TB

#### Expected behaviour
Sync without hang

**Comment by karalabe** [comment]
You need an SSD currently to run a full node. An HDD won't be able to take the load, not even the sync load in its current form.

**Comment by emelbardis** [comment]
Geth, Mist and Ethereum Wallet have been doing this to me for 3 or 4 months now. 1TB NVMe SSD with 16 GB RAM and 18GB Swap on a quad core Fedora 27 laptop. It's driving me crazy... I've wiped and reloaded my OS a few times and everything still fails

**Comment by mattiasghodsian** [comment]
@karalabe ill get and SSD and get back to you.

**Comment by mattiasghodsian** [comment]
@karalabe
I am running with a lower --cache and it seems to working now, but ill wait this one out and then get an SSD if i get the same problem again.
