### ISSUE TITLE
API Calls Returning Incorrect Results

### ISSUE THREAD

**Issue by the-jackalope** [ethereum/go-ethereum#16295]
Hi there,

#### Problem and steps to reproduce

I'm having some trouble with the `ethclient.Client` not returning correct results from the network. When I try the same calls using `curl` I get the expected results.

**Ex. 1: Querying balance from an address**
In go-ethereum:
```go
apiKey := "..."
conn, err := ethclient.Dial("https://mainnet.infura.io/" + apiKey)
out, err := conn.BalanceAt(context.Background(), common.StringToAddress("0xCdA03Cb85BA0e2bCBF6C7CaB1eA10203F6c30495"), nil)

fmt.Println(out.String()) // prints "0"
```
Error handling is omitted for simplicity, but none of these methods error out. I'm not sure if it is worth mentioning that I am running this in a server goroutine, but since I haven't seen that listed as an issue anywhere I'm assuming it is not.

The result is incorrect as I can see from etherscan.io that the account has ether. Furthermore, when performing the query using JSON RPC:
```bash
$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xCdA03Cb85BA0e2bCBF6C7CaB1eA10203F6c30495", "latest"],"id":1}' https://mainnet.infura.io/$API_KEY

{"jsonrpc":"2.0","id":1,"result":"0x28d3cfae09e00"}
```
I receive the correct result.

**Ex. 1: Making a contract call**
I'm using the [EOS contract](https://etherscan.io/token/EOS#readContract) as an example:
```go
eosAddr := common.StringToAddress("0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0")
conn, err := ethclient.Dial("https://mainnet.infura.io/" + apiKey)
parsedBytes, err := abi.JSON(strings.NewReader(tokenABI))
contract := bind.NewBoundContract(eosAddr, parsedBytes, conn, nil, nil)

ret := new([32]byte)
err := contract.Call(nil, ret, "symbol")
// err message: "no contract code at given address"
```

Whereas with the JSON RPC:
```bash
$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0", "method":"eth_call", "params":[{"to": "0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0", "data": "0x95d89b410000000000000000000000000000000000000000000000000000000000000000"}, "latest"], "id":1}' https://mainnet.infura.io/$API_KEY

{"jsonrpc":"2.0","id":1,"result":"0x454f530000000000000000000000000000000000000000000000000000000000"}
```

Again, the RPC returns the correct answer. When I use the geth API I seem to either receive no error, or incorrect error messages (seeing as a contract definitely exists at the address). Any results returned seem to be incorrect compared to the RPC. I'd love to know if I'm using the API incorrectly, or to help get to the bottom of this. Many thanks!

#### System information

Geth version: `1.8.2-stable`
OS & Version: macOS High Sierra 10.13.13

**Comment by karalabe** [comment]
Used `common.HexToAddress` instead of `common.StringToAddress`. The latter just interprets your string as an address whereas the former actually converts a hex. Not sure why the latter even exists tbh.

**Comment by the-jackalope** [comment]
Oh my goodness that worked like magic! Thanks for the help, really appreciate it. I was scratching my head over here. I'll close this issue.

**Comment by Phil192** [comment]
My problem is similar so i'm asking same question:
`var result interface{}

	cli := eth.NewClient()
	hst, err := os.Open(eth.HumanStandardTokenPath)
	if err != nil {
		log.Errorln(err)
		return
	}
	abIface, err := abi.JSON(hst)
	if err != nil {
		log.Errorln(err)
		return
	}
	PTO := cm.HexToAddress("0xd1ac5e0b722765cbd56285c4965adb4052bb363f")
	contract := bind.NewBoundContract(
		PTO,
		abIface,
		cli,
		nil, nil,
		)

	owner := cm.HexToAddress("0x6ed945867ac5dc998e8c6aae4e437225345a6302")
	err = contract.Call(nil, result, "balanceOf", owner)
	fmt.Println(result, err) //no contract code at given address`
