### ISSUE TITLE
NewBlocks subscription

### ISSUE THREAD

**Issue by asymmetric** [ethereum/go-ethereum#16299]
Hi there,

I am trying to use the `rpc` package to implement a subscription service that would react to new blocks being mined, and I bumped into [this test](https://github.com/ethereum/go-ethereum/blob/1488fdaf19cebdb79478bd4949b99d3f0d053419/rpc/client_example_test.go#L69), which uses the `newBlocks` method.

Although this method is mentioned in different places, it doesn't seem to be implemented, netiher according to the [wiki entry](https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB#supported-subscriptions), nor to the code - in fact, it seems to have been removed in 47ff8130124b479f1f051312eed50c33f0a38e6f.

#### System information

Geth version: `geth master`
OS & Version: Linux
Commit hash : 1488fdaf19cebdb79478bd4949b99d3f0d053419

#### Expected behaviour

    >> {"jsonrpc":"2.0","id":1,"method":"eth_subscribe","params":["newBlocks"]}
    << a block number

#### Actual behaviour

    >> {"jsonrpc":"2.0","id":1,"method":"eth_subscribe","params":["newBlocks"]}
    << The method newBlocks_newBlocks does not exist/is not available

(**Note**: The error message seems to have a problem as well, note the repetition)
#### Steps to reproduce the behaviour

https://github.com/ethereum/go-ethereum/blob/1488fdaf19cebdb79478bd4949b99d3f0d053419/rpc/client_example_test.go#L69

**Comment by asymmetric** [comment]
Right after posting this, I found [this issue](https://github.com/ethereum/go-ethereum/pull/2984), which seems to hint at `newHeads` being a replacement for `newBlocks`.

Should the test be updated?

**Comment by karalabe** [comment]
Definitely, feel free to open a PR to update the test :)
