### ISSUE TITLE
Geth --exec attach giving bad responses [windows]

### ISSUE THREAD

**Issue by actuallymentor** [ethereum/go-ethereum#1629]
Often I receive only a partial response, other times a response that is not the return value of the query. See screenshot for exact situation.

In screenshot I execute a getBalance(), but get a partial address returned.

![c__windows_system32_cmd exe - 2015-08-09 08_36_26](https://cloud.githubusercontent.com/assets/9071382/9153839/f75d487a-3e72-11e5-9a06-764d0284c72d.png)

**Comment by bas-vk** [comment]
On the right image you did get a valid response for the `getBalance` call. The result of `eth.getBalance` is the balance in wei hex encoded. If you decode the response and convert it to ethers you get a balance of 10 which is probably the balance at that time.

Could you try the following: `geth --exec "web3.fromWei(eth.getBalance(eth.coinbase), 'ether')" attach`

**Comment by actuallymentor** [comment]
Here you go, no conversion happening...


![start - 2015-08-12 09_44_02](https://cloud.githubusercontent.com/assets/9071382/9218904/e12ff974-40d6-11e5-9c02-fe4858c1850d.png)

**Comment by bas-vk** [comment]
Sorry my bad, if you use the `--exec` option the last RPC response is returned which is not parsed by web3. It this case its the hex encoded balance in wei which seems to be correct (I get the same balance on my node for this account). 

@obscuren, I suggest we change this behavior and return the result just as the console would log it. Agreed?

**Comment by fjl** [comment]
I agree (though wasn't asked) because it's very confusing.

**Comment by obscuren** [comment]
@bas-vk agreed

Was there a reason we use raw return? I remember there was a conversation about this a little while ago.
