### ISSUE TITLE
Send raw transaction return "rlp: input string too long for common.Address, decoding into (types.Transaction)(types.txdata).Recipient"

### ISSUE THREAD

**Issue by acinmavi** [ethereum/go-ethereum#16290]
I have set this raw transaction via ropsten network, that i think it's valid . But when sign and send raw transaction , go ethereum can't decode it using rlp and return "rlp: input string too long for common.Address, decoding into (types.Transaction)(types.txdata).Recipient"
Here are my request and response :

final String sender = "0x70a8968683e799f3f478d98ad1b8313fac020e66";
final String receiver = "0xa66c3de8076e231d57a578d163a126dc975670f7"; 
final BigInteger privateKeySender = new BigInteger("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
final BigInteger amount = new BigInteger("299939344000000000");
final String comment = "xxxxx";
final long gasLimit = 200000L;

2018-03-09 15:43:36:946  INFO - XHttpClient [main] - start to http post, uri: http://xxxxxxx:8545 , headers [Content-Type: application/json] , body {"id":910068480022153828,"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xF88A01847735940083030D40AA307861363663336465383037366532333164353761353738643136336131323664633937353637306637880429993E8548A000884249545F434F52453DA04BB291FCCEBD9AA65C833AA82F99219CA92AF81BF0BDA5276E7DBE27979FB4E5A049D6FE7D3B7585906043FFC5EE245D366383CD751B19ACAAD9B0BECD815083DB"]} , timeout 60000,
2018-03-09 15:43:37:114  INFO - XHttpClients [main] - finish http request ,response status HTTP/1.1 200 OK , body {"jsonrpc":"2.0","id":910068480022153828,"error":{"code":-32000,"message":"rlp: input string too long for common.Address, decoding into (types.Transaction)(types.txdata).Recipient"}}

Anyone please help to find out what could the problem be?

**Comment by holiman** [comment]
The rlp data is 
```
$ ./rlpdump -hex 0xF88A01847735940083030D40AA307861363663336465383037366532333164353761353738643136336131323664633937353637306637880429993E8548A000884249545F434F52453DA04BB291FCCEBD9AA65C833AA82F99219CA92AF81BF0BDA5276E7DBE27979FB4E5A049D6FE7D3B7585906043FFC5EE245D366383CD751B19ACAAD9B0BECD815083DB
[
  01,
  77359400,
  030d40,
  "0xa66c3de8076e231d57a578d163a126dc975670f7",
  0429993e8548a000,
  "BIT_CORE",
  "=",
  4bb291fccebd9aa65c833aa82f99219ca92af81bf0bda5276e7dbe27979fb4e5,
  49d6fe7d3b7585906043ffc5ee245d366383cd751b19acaad9b0becd815083db,
]
```

which corresponsd to
```
type txdata struct {
	AccountNonce uint64          `json:"nonce"    gencodec:"required"`
	Price        *big.Int        `json:"gasPrice" gencodec:"required"`
	GasLimit     uint64          `json:"gas"      gencodec:"required"`
	Recipient    *common.Address `json:"to"       rlp:"nil"` // nil means contract creation
	Amount       *big.Int        `json:"value"    gencodec:"required"`
	Payload      []byte          `json:"input"    gencodec:"required"`

	// Signature values
	V *big.Int `json:"v" gencodec:"required"`
	R *big.Int `json:"r" gencodec:"required"`
	S *big.Int `json:"s" gencodec:"required"`

	// This is only used when marshaling to JSON.
	Hash *common.Hash `json:"hash" rlp:"-"`
}
```
Here's a random transaction I took from the network:
```
$ ./rlpdump -hex 0xf86b0484b2d05e0082520894e3b9b23682410a0a4fba28a1664548cdff11344a880de0b6b3a76400008026a085ff1ccb9d65ce94a80244cb82fa988367aef3515bc87aeba65cd3d85a638fc8a03b6aa7094ed92338c0367c16b35311e1bca2927a3628cafaaebf10eebccb0d10
[
  04,
  b2d05e00,
  5208,
  e3b9b23682410a0a4fba28a1664548cdff11344a,
  0de0b6b3a7640000,
  "",
  "&",
  85ff1ccb9d65ce94a80244cb82fa988367aef3515bc87aeba65cd3d85a638fc8,
  3b6aa7094ed92338c0367c16b35311e1bca2927a3628cafaaebf10eebccb0d10,
]
```
For some reason, whatever you used to sign it converted the recipient to string, not a sequence of bytes (4th field). What did you use to generate it?

**Comment by acinmavi** [comment]
Thank you very much for your fast response , I try to implement by using ethereumj , as example in this [link](https://techblog.bozho.net/send-ethereum-transactions-java/) .
`final Transaction tx = new Transaction(
                nonce,
                ByteUtil.bigIntegerToBytes(gasPrice),
                ByteUtil.longToBytesNoLeadZeroes(gasLimit),
                to.getBytes(StandardCharsets.UTF_8),
                ByteUtil.bigIntegerToBytes(amount),
                comment.getBytes(StandardCharsets.UTF_8),
                networkID);
        tx.sign(ECKey.fromPrivate(fromKey));`
I try to convert receiver address to byte using String.getBytes(StandardCharsets.UTF_8). And after sign I will push via rpc api.

**Comment by acinmavi** [comment]
Funny thing is , when I change function to get byte[] from String :
`to.getBytes(StandardCharsets.UTF_8)===>` Hex.decode(removePrefix(to)),`
result when send transaction is change :
2018-03-09 17:49:11:857  INFO - XHttpClient [main] - start to http post, uri: http://163.44.167.66:8545 , headers [Content-Type: application/json] , body {"id":910131687428459192,"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xF87401847735940083030D4094A66C3DE8076E231D57A578D163A126DC975670F7880429993E8548A000884249545F434F52453DA089383754259BC95C57B0A7C7336685FBA815D68D9A9CFDC92672623514127D37A00F5E0AB39560816731E571EA4EAF6579D8365F96097FC14F0B2289121305CF8E"]} , timeout 60000, 
2018-03-09 17:49:12:041  INFO - XHttpClients [main] - finish http request ,response status HTTP/1.1 200 OK , body {"jsonrpc":"2.0","id":910131687428459192,"error":{"code":-32000,"message":"invalid sender"}}
And dump rlp seem correct receiver address, but something still wrong. What is wrong with my request ?

**Comment by holiman** [comment]
You're closer:

```
./rlpdump -hex 0xF87401847735940083030D4094A66C3DE8076E231D57A578D163A126DC975670F7880429993E8548A000884249545F434F52453DA089383754259BC95C57B0A7C7336685FBA815D68D9A9CFDC92672623514127D37A00F5E0AB39560816731E571EA4EAF6579D8365F96097FC14F0B2289121305CF8E
[
  01,
  77359400,
  030d40,
  a66c3de8076e231d57a578d163a126dc975670f7,
  0429993e8548a000,
  "BIT_CORE",
  "=",
  89383754259bc95c57b0a7c7336685fba815d68d9a9cfdc92672623514127d37,
  0f5e0ab39560816731e571ea4eaf6579d8365f96097fc14f0b2289121305cf8e,
]
```

Geth doesn't seem to think that it's a valid signature : https://github.com/ethereum/go-ethereum/blob/d43ffdbf6a406839bbf54bdf76f5574345abdd57/core/tx_pool.go#L573 . I would guess that there's something wrong with the r,s,v. For reference, here's a tx from ropsten that I took from etherscan:

```
[
  01,
  02540be400,
  5208,
  ff2b5d4114190bb6447dbae098096fd274029535,
  98a71ab9c1e4e000,
  "",
  1b,
  881b372012946b0efa518cc850b0436afb87b48e3209ff524bf3815948ab9552,
  3798e450d426c63491e35ee5e7be345928818ed879af0ac7d7843ac3b6eda0ed,
]
```

**Comment by karalabe** [comment]
Make sure the chain ID is correct. If it's not, that might explain the signature rejection.

**Comment by daithi-coombes** [comment]
I'm reporting the same issue. Am working on a fork of Geth, so maybe issue is here?
```
Geth Version: 1.8.23-beta
Go Version: 1.13.6
```

Here's the code I'm using:
```
	stableTokenAddress := common.HexToAddress("0x5c7197e1147ebf98658a2a8bc3d32bebf1692829")
	tokenInstance, err := contracts.NewStabletoken(stableTokenAddress, client)
	ks := keystore.NewKeyStore(
		"/path/to/keystore",
		keystore.LightScryptN,
		keystore.LightScryptP)

	// get unlocked account
	var account accounts.Account
	for _, acc := range ks.Accounts() {
		if acc.Address.String() == address.String() {
			account, err = ks.Find(acc)
			if err != nil {
				return false, err
			}
		}
	}
	_ := ks.Unlock(account, "********")

	txOpts, _ := bind.NewKeyStoreTransactor(ks, account)
	session := &contracts.StabletokenSession{
		Contract: tokenInstance,
		CallOpts: bind.CallOpts{
			Pending: true,
			From:    address,
		},
		TransactOpts: *txOpts,
	}

	tx, err := session.Approve(address, amount)
	if err != nil {
		log.Fatal(err)
		return false, err
	}
```
Returning:
```
rlp: input string too short for common.Address, decoding into (types.Transaction)(types.txdata).Recipient
```
No tx's being sent, that I can tell of.

**Comment by ArakelTheDragon** [comment]
Hi guys! I don't know if this is the correct place to ask, but I am facing a similar problem, I tried the typedef structure suggested, but I can not seem to solve this issue, can someone please have a look:
[code]
Type 'START' to begin the transaction.
Starting transaction...
Nonce: 0x62
Payload: {"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0x62","0x09184e72a000","0x2710","0xffc4f8Bde970D87f324AefB584961DDB0fbb4F00","0x0","0x095ea7b3000000000000000000000000AEA49Be813E1D013bb01ed76BcDf6978823298B20000000000000000000000000000000000000000000000000000000000000001"],"id":1}
Response: {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"typed transaction too short"}}
[/code]
