### ISSUE TITLE
why delegatecall cost all gas

### ISSUE THREAD

**Issue by kklook** [ethereum/go-ethereum#16300]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.82`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
**I call delegatecall in fail function at proxy contract, but after tractTransaction i found  delegatecall cost all gas like this:**

{
      depth: 1,
      gas: 3978385,
      gasCost: 3968431,
      memory: ["4ef65c3b00000000000000000000000000000000000000000000000000000000", "0000303900000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000000000000000000000000000000000000000000000"],
      op: "DELEGATECALL",
      pc: 57,
      stack: ["00000000000000000000000080ec7db71f93c1b3a345079bd14775102290c1a9", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000024", "0000000000000000000000000000000000000000000000000000000000000040", "00000000000000000000000080ec7db71f93c1b3a345079bd14775102290c1a9", "00000000000000000000000000000000000000000000000000000000003c8d84"],
      storage: {}
  }, 

**fail function :**
 function() public {
    address target = 0x80ec7db71f93c1b3a345079bd14775102290c1a9;

    assembly {
      calldatacopy(0x0, 0x0, calldatasize)
      let success := delegatecall(sub(gas, 2000000), target, 0x0, calldatasize, 0, 0)
      let retSz := returndatasize
      returndatacopy(0, 0, retSz)
      switch success
      case 0 {
        revert(0, retSz)
      }
      default {
        return(0, retSz)
      }
    }

**the function i called:**
    function setUint(uint t) {
        i = t;
    }

#### Backtrace

````
[backtrace]
````

**Comment by veox** [comment]
This is not a `go-ethereum` issue. Try on the [Solidity issue tracker](https://github.com/ethereum/solidity/issues).

Suggest closing as invalid.
