### ISSUE TITLE
wallet import should allow to import a specific presale account only once

### ISSUE THREAD

**Issue by philsmd** [ethereum/go-ethereum#16302]
#### System information

Geth version: 1.8.2
OS & Version: Windows/Linux/OSX
Commit hash : b8b9f7f4476a30a0aaf6077daade6ae77f969960

#### Expected behaviour

The wallet import command should only import new accounts if they are not already present.

#### Actual behaviour

The wallet import command does create multiple UTC files and therefore multiple accounts even if the presale account was already imported beforehand.

#### Steps to reproduce the behaviour

run "geth import wallet presale.json" multiple times and you will see something like this (file list under the keystore directory):

![ethereum_wallet_import_problem](https://user-images.githubusercontent.com/921533/37279738-f2bc6c16-25eb-11e8-83b8-ad58dbaef064.jpg)

**Comment by holiman** [comment]
I'm not sure that's really desired behaviour. What if a user had already imported his presale account, but has forgotten the password, and wants to reimport?

In that case, there would be two alternatives, both of which are error-prone

1. Geth deletes the old json-file (danger!)
2. Geth tells the user to delete the old json-file. Also dangerous.

A third alternative would be a much more complicated flow, where the user is prompted about what to do -- but that doesn't work well as an API, only in CLI usage.

**Comment by philsmd** [comment]
I do not agree.
If the user provides the password while importing the pre-sale wallet file, geth can easily find out if the other wallets match exactly (same address + same password for instance). Geth could even try to quickly unlock and lock all the other matching accounts with the same ethaddr and see if the present accounts are valid and can be unlocked with that password.
geth should definitely warn the user if s/he tries to import the same wallet again and again and if it tries to import exactly the same file it should tell the user that the account wasn't imported because the exact same wallet is already present:

this is what I currently see, if I run personal.listAccounts:
```
["0xf9438b7121a15fd127ec0d8a72ee2b3e8da04a5a", "0xf9438b7121a15fd127ec0d8a72ee2b3e8da04a5a", "0xf9438b7121a15fd127ec0d8a72ee2b3e8da04a5a", "0xf9438b7121a15fd127ec0d8a72ee2b3e8da04a5a", "0xf9438b7121a15fd127ec0d8a72ee2b3e8da04a5a", "0xf9438b7121a15fd127ec0d8a72ee2b3e8da04a5a", "0xf9438b7121a15fd127ec0d8a72ee2b3e8da04a5a", "0xf9438b7121a15fd127ec0d8a72ee2b3e8da04a5a", "0xf9438b7121a15fd127ec0d8a72ee2b3e8da04a5a", "0xf9438b7121a15fd127ec0d8a72ee2b3e8da04a5a", "0xf9438b7121a15fd127ec0d8a72ee2b3e8da04a5a", "0xf9438b7121a15fd127ec0d8a72ee2b3e8da04a5a", "0xf9438b7121a15fd127ec0d8a72ee2b3e8da04a5a"]
```

I think it's not a good idea to have and list the same account multiple times.

**Comment by karalabe** [comment]
Hmmm, Geth should have deduplicated any accounts before listing. This seems like a different issue. Wasn't the original behavior that duplicated accounts get merged together @fjl?

**Comment by philsmd** [comment]
I do not fully agree. For a user it is kind of the same problem: s/he tried to add an existing wallet flie and geth didn't warn that this account was already present.
Of course, for a geth dev this could mean that there are actually various parts in code where this needs to be tested: not only shouldn't there be multiple UTC files for the identical address (and using the same password, private key etc), but also the API calls shouldn't display the "duplicated" accounts multiple times.

Furthermore, I just realized that you couldn't really work with these accounts at all: this happens when I run personal.unlockAccount ():
```
Error: multiple keys match address
```

and I'm completely blocked now. I can't do anything and the warning doesn't really guide me on how to fix this (of course, I myself know that I need to manually move some of those files such that no more duplicates are within the keystore folder)
