### ISSUE TITLE
Unable to Unlock or Update accounts

### ISSUE THREAD

**Issue by dustrider** [ethereum/go-ethereum#1630]
Having this issue on two separate brand new installs, one manual one docker.
Docker - Geth/v0.9.39/linux/go1.4.2
Manual - Geth/v1.0.1/linux/go1.4.2

in both cases I can create a personal account as per the wiki but when trying to unlock the account I get:
could not decode, invalid type on field passphrase: not a string
    at InvalidResponse (<anonymous>:-59655:-69)
    at send (<anonymous>:-117559:-69)
    at unlockAccount (<anonymous>:-106295:-69)
    at <anonymous>:1:1

Where do I even start?

**Comment by karalabe** [comment]
I'm betting you haven't supplied a password to unlock the account (https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#personalunlockaccount).

**Comment by dustrider** [comment]
mea culpa, 

thanks for taking the time to correct me.
