### ISSUE TITLE
How to run the geth client in the background ?

### ISSUE THREAD

**Issue by IcyLemon** [ethereum/go-ethereum#16307]
Hi,
I know the geth client is started in the console as follows(I use private network):
`./geth --identity ... --networkid 100000 console`

The problem is that once the console is closed, the geth process is terminated too. This isn't what i wanted, what i hope is that the geth can run in the background such as Tomcat, Nginx, etc.

Does anyone have a good idea?
Thank a lot.

**Comment by karalabe** [comment]
Put it into the background like any other Linux process: `nohup ./geth --identity ... --networkid 100000 &`

**Comment by karalabe** [comment]
Note, you need to omit the console, because `nohup` closes the input stream and the console terminates if its input it closed.

**Comment by IcyLemon** [comment]
@karalabe 
Yes, I tried to use nohup at first, but it didn't work, According to your advice, I omitted the parameter  console, worked fine.
Many thanks!

**Comment by DottoreM** [comment]
Apologies for bringing this back up, but i need this a starting point. 

How can I now go *back* to it? All linux solutions i found so far have not allowed me to interact with the node. 
Why?
>I want to see the interaction occuring and 
>I want to shut down geth gracefully

**Comment by karalabe** [comment]
You can start geth in the background via `nohup geth [all your params]`.
You can attach to it via a console via `geth attach geth.ipc-path-in-your-datadir`.
You can gracefully terminate geth by sending the first process a sigint `kill -SIGINT first-geth-pid`.

**Comment by DottoreM** [comment]
understood, but how can  go back to the process before killing it? if I attach to geth, I will not see the original start with contracts submitted etc

**Comment by holiman** [comment]
Use `screen` or `tmux`. `screen` starts a new bash session, there you can start geth. Then hit `ctrl-d` to detach, and now you can even log out from the server if you want. Later on, you can do `screen -ls` to view screen sessions, and `screen -r xxx` to resume one of them. 
`tmux` is a bit newer and shinier than `screen`, YMMV

**Comment by DottoreM** [comment]
thanks everyone

**Comment by asymmetric** [comment]
How come `nohup` is necessary rather than just `geth &`?

**Comment by jthak052** [comment]
@karalabe  How to do the same on windows server? geth stops working once the Server is restarted or the Command line closes down

**Comment by bap2pecs** [comment]
If you want to run a node yourself, using `systemd` is likely a better idea
