### ISSUE TITLE
Unable to send P2P message 

### ISSUE THREAD

**Issue by Satavim** [ethereum/go-ethereum#16316]
Hi,

I am unable to send a p2p message in a network of 3 nodes. using the shh client to post as below.
shh.post({
  symKeyID: '288bce491f3620ca73b36d3023d75043630e3b5c61d60426612f2f1e23892444',//data,
  topic: '0x99123abc' ,
  payload: web3.utils.toHex(req.body),
  ttl: 1000,
  priority: 1000,
  powTime: 10,
  powTarget: 0.5,
 targetPeer:'724c8ad15a40850f26b42d41d0c8b330b2c7507890e3c9eedfe1115c6340757b75e4c3e54fc6b1e6175993d71df863d7ceeff16b3883b55ace8f58227d2eeea0'
})

It could identify its peer but the peer which is subscribed to the message didnot receive it.
Subscribed as below:
shh.subscribe("messages", {
        symKeyID: 'dbccea31ff4acd7a1510b86e3243697830b2bbd97639ddf2a5c8e0c50b80495c',//data,
        topics: ['0x99123abc']
    }

**Comment by gballet** [comment]
@Satavim what is the configuration of your 3 nodes?

**Comment by gballet** [comment]
Closing this issue for lack of input.
