### ISSUE TITLE
Large integer literals get silently truncated

### ISSUE THREAD

**Issue by witten** [ethereum/go-ethereum#1632]
In geth:
```
> 29714174079724412745887019504253973571029824035614949642323418802670541573197
2.9714174079724414e+76
```

And then if I paste that result into ipython:
```
In [1]: int(2.9714174079724414e+76)
Out[1]: 29714174079724414182345292595171428140511169245030622933092435559513436717056L
```

The numbers start out the same, but then notice how they start diverging. I imagine that has something to do with this issue: https://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin

This is a problem because it makes it difficult to send large integer literals to contracts.

```
$ apt-cache show geth | grep Version
Version: 1.0.1+46trusty-0ubuntu1
```

**Comment by fjl** [comment]
This is a known issue with JavaScript in general. All JavaScript numbers are 64bit floats. Maybe the designers of JS thought that this would simplify things.

web3.js solves this problem using bignumber.js. Please check [the wiki page about web3.js](https://github.com/ethereum/wiki/wiki/JavaScript-API#a-note-on-big-numbers-in-web3js) for more information.
