### ISSUE TITLE
sendTransaction called, but not broadcasted to other node, on android

### ISSUE THREAD

**Issue by danialj** [ethereum/go-ethereum#16323]
Geth version: `1.8.2 stable`
OS & Version: OSX/Android

Commit hash : (if `develop`)

#### Expected behaviour
when called sendTransaction, the transaction will broadcast to other node.

#### Actual behaviour
but actual, when call sendTransaction look well, but not broadcast the transaction to other node.

#### Steps to reproduce the behaviour
step 1:
i changed only networkID and chainID on source code to build my private chain via geth, and run geth on my macbook well.

step 2:
i was generated geth.aar via "make android", and imported it to my android project. i can syncing block  chain and get balance and create account on android pad. but when i call sendTransaction, the function is looks processed well, and returned, but my transaction not broadcast to other node.

my send transaction code sample:
public boolean sendResource(String outAccount, String recAccount, String amount, String pass){
        try{
            BigDecimal bdamount=new BigDecimal(amount);
            bdamount=CConvert.toWei(bdamount, CConvert.Unit.ETHER);
            BigInt xamount=new BigInt(Long.parseLong(bdamount.toBigInteger().toString()));

            CAccount acc=this.mAccounts.get(outAccount);
            Account eaccFrom=acc.ethAccount;

            Address eaddrFrom=acc.ethAddress;
            Address eaddrTo=Geth.newAddressFromHex(recAccount);

            Common.log("send resource to: "+eaddrTo.getHex());

            long nonce=this.getNewNonce();  //the getNewNonce function return transaction count on lastest block
            String sdata="er";
            byte[] bdata=sdata.getBytes();

            long gasLimit=210000;
            long xprice=10;
            BigInt gasPrice=new BigInt(xprice);

            Transaction trans=Geth.newTransaction(nonce,eaddrTo,xamount,gasLimit,gasPrice,bdata);

            Transaction signed=this.ethKeyStore.signTxPassphrase(eaccFrom,pass,trans,this.chainID);

            this.ethClient.sendTransaction(this.ethContext,signed);  //in debug, this function look like called well
            Hash h=trans.getHash();
            String sh=h.getHex();

            Common.log("send resource hash:"+sh);

            h=trans.getSigHash();
            sh=h.getHex();
            Common.log("send resource hash2:"+sh);

            return true;  //at last this function return true
        }
        catch (Exception err){
            Common.log("send resource error", err);
            return false;
        }
    }

by the way:
i run a server node and a light node on my macbook. 
the server node is full node, and it can process all command on console well.
the light node on mac is ok, all command on console can be process well.
only my android pad node, can syncing data, can get balance, can create account, can receive ether from other node, but can't send ether to another.

#### Backtrace
bellow was logs in android studio:

![image](https://user-images.githubusercontent.com/34347415/37487646-22de801c-28cd-11e8-84a9-fdc614af290b.png)

````
[backtrace]
````

**Comment by ligi** [comment]
> i changed only networkID and chainID on source code to build my private chain via geth, and run geth on my macbook well.

do you serve light clients with this node? The android client is a light node and so you need a light server to serve it.

**Comment by danialj** [comment]
@ligi 

> do you serve light clients with this node? The android client is a light node and so you need a light server to serve it.

i run the geth as server on mac like this:
geth --lightserv 90 console

and i run the light node on mac like this:
geth --port=30305 --bootnodesv5=enode://8014d559b7f50df266185ff275bbe78aca2b614982a1dc2e65cf2647eba35ff945370177730b52ec50f407a43ef733c646733469fea0dd1cda422543088a1397@127.0.0.1:3100 --light

and on android, i start the geth client use bootnodes point to 192.168.0.109(the server ip) too. the node on android can syncing data, create account, get balance, receive ether from server and light node, but can't send transaction to server or light node.

**Comment by ligi** [comment]
and when you submit a transaction with the light node on the mac it works?

**Comment by danialj** [comment]
@ligi 

i send ether from light node on mac to server node, is ok. and i send ether from light node on mac to android node, is ok.
but send ether from android to server node and light node on mac, all fail.

**Comment by danialj** [comment]
@ligi 

i add trace log on source code.
step 1: changed les/peer.go as bellow:
![image](https://user-images.githubusercontent.com/34347415/37808849-90a38056-2e87-11e8-85aa-b5d35585f04d.png)

step 2: changed les/handler.go 's handleMsg function as bellow:
![image](https://user-images.githubusercontent.com/34347415/37808958-1d024f46-2e88-11e8-8d28-5b2f0cf959a2.png)

when i send ether from android node to light node on mac, the server node log as bellow:
![image](https://user-images.githubusercontent.com/34347415/37809121-b51a800a-2e88-11e8-9e8b-8be854337e4f.png)


and the android node log as bellow:
![image](https://user-images.githubusercontent.com/34347415/37809161-e5048f4a-2e88-11e8-848d-dc48f6887966.png)

looks like the transaction is processed by server and all is well. but in fact, the transaction don't be processed.

help me please...

**Comment by songjiekunpwc** [comment]
@danialj any luck? i encounter the same issue.

**Comment by nuliknol** [comment]
@danialj  , I have got the same issue. The offending code is this;

```
670         if atomic.LoadUint32(&pm.acceptTxs) == 0 {
671             log.Info("breaking")
672             break
673         }
```
for some reason pm.acceptTxs is not set to 1, which means, the node is not ready to process transaction, even when the blocks are synced. This is on 1.8.12
