### ISSUE TITLE
Why does the private network connect to the public network when starting?

### ISSUE THREAD

**Issue by IcyLemon** [ethereum/go-ethereum#16338]
I found a strange problem and confused me.

I want to create a private network, the gensis file(my-gensis.json) is as follows:
```
{
  "config": {
        "chainId": 15,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "coinbase" : "0x0000000000000000000000000000000000000000",
    ......
}
```
here, the chainId is 15.

First, I initialized successfully as follows:
`./geth init my-gensis.json --datadir data`

Then I tried to start the geth as follows:
`./geth --rpc --rpcport 8545 --datadir data --port 30001 --rpcapi personal,db,eth,miner,net,web3 --networkid 100000 --nodiscover console`

The startup log is as follows:
```
WARN [03-19|15:56:35] No etherbase set and no accounts found as default 
INFO [03-19|15:56:35] Starting peer-to-peer node               instance=Geth/centos-dev-125-1/v1.7.3-stable/linux-amd64/go1.8.3
INFO [03-19|15:56:35] Allocated cache and file handles         database=/home/work/.ethereum/geth/chaindata cache=128 handles=1024
**INFO [03-19|15:56:35] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Engine: ethash}"**
```
Note the bold context: ChainId is 1, not 15 defined in my gensis file! Other parameters were also inconsistent with the definition in the my-gensis.json file. It seemed that the private network connected to the public network?

I checked over and over and was sure that the data dir, gensis file, command line were all ok. 

Who encountered this and resolved?

Thanks a lot.

**Comment by holiman** [comment]
That looks very odd. Additionally, `database=/home/work/.ethereum/geth/chaindata` shows that it totally ignored your `--datadir`. 
Running your comand locally, it works for me:
```
[user@work bin]$ ./geth --rpc --rpcport 8545 --datadir data --port 30001 --rpcapi personal,db,eth,miner,net,web3 --networkid 100000 --nodiscover console
INFO [03-19|09:32:56] Maximum peer count                       ETH=25 LES=0 total=25
INFO [03-19|09:32:56] Starting peer-to-peer node               instance=Geth/v1.8.3-unstable-6494f4e8/linux-amd64/go1.10
INFO [03-19|09:32:56] Allocated cache and file handles         database=/home/user/go/src/github.com/ethereum/go-ethereum/build/bin/data/geth/chaindata cache=768 handles=512
```
Could you try with a more recent release and see if you get the same problem?

**Comment by IcyLemon** [comment]
@holiman 
I use geth geth-linux-amd64-1.7.3 in Centos 7.2 64.

I found the reason and thought that this is possibly a bug of geth: **this problem is related to the path**

My directory structure of the geth is as follows:
```
geth-linux-amd64-1.7.3/
    -- geth
    -- my-gensis.json
    -- node-1/
        -- data
```
 Firstly, initialized successfully as follows:
`./geth init my-gensis.json --datadir ./node-1/data`

When I started the geth in the geth-linux-amd64-1.7.3 folder as follows:
```
cd geth-linux-amd64-1.7.3
./geth --rpc  --datadir ./node-1/data  --rpcapi eth,miner,net,web3  --networkid 15125 console
```
The problem I described before occurred: It connected to chainId 1.

But when I entered into node-1 folder and start the geth as follows:
```
cd geth-linux-amd64-1.7.3/node-1
../geth --rpc  --datadir ./data  --rpcapi db,eth,miner,net,web3  --networkid 15125 console
```
It worked fine!

On the other hand, I found that there must be a subdirectory such as data under the node-1. If the structure is as follows:
```
geth-linux-amd64-1.7.3/
    -- geth
    -- my-gensis.json
    -- node-1/
```
it doesn't work(always connect to chainId 1) no matter where you start the geth.

I don't know if this is a bug, but it is very weird for me.

**Comment by karalabe** [comment]
Put the `--datadir` before `init`.

**Comment by IcyLemon** [comment]
@karalabe 
Put before and after were both tried,  and the result is the same.

**Comment by karalabe** [comment]
Oh, I misunderstood the issue, my apologies.
