### ISSUE TITLE
setup in go path and go version

### ISSUE THREAD

**Issue by BALAMURUGANS15** [ethereum/go-ethereum#16331]
Hi frnds,
  i have problem for setup in go path and go version for this project, please anyone help me

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
