### ISSUE TITLE
puppeth: Add option to enable RPC for miner node

### ISSUE THREAD

**Issue by nileshtrivedi** [ethereum/go-ethereum#16348]
When I deploy a miner node via puppeth, because RPC is not enabled, I am unable to propose a new miner - either by `clique.propose(address, authorized)` via the console (IPC endpoint is inside the container) or by `clique_propose` via RPC).

It would be nice to have a prompt in the wizard which enables RPC while deploying a node.

From what I can see, this requires a change in the Dockerfile here: https://github.com/ethereum/go-ethereum/blob/master/cmd/puppeth/module_node.go#L45 and a change in the wizard and nodeInfos structure.

**Comment by karalabe** [comment]
You can do that by SSHing into your remote machine, attaching it via docker and opening a console.

```
ssh [...]
docker exec -it yournetwork_sealnode_1 /bin/sh
geth console
```

I know it's not nice, just a doable workaround for now

**Comment by karalabe** [comment]
All in all I don't think exposing RPC is the good approach, since that would be a security issue. A much better approach would be to allow puppeth to open some form of a console tunnelind through SSH and docker and IPC under the hood.

**Comment by nileshtrivedi** [comment]
@karalabe Thanks. Agree about security issues with enabling RPC on the sealnode. It does seem like a good idea to separate RPC in general and mining nodes.

When I run `geth console` in a Docker-attached terminal, I get this message:
`Fatal: Error starting protocol stack: datadir already used by another process`

If I stop the container or tear down the container, mining will stop. I'm not sure if `clique.propose` will work in that case.

**Comment by adamschmideg** [comment]
@nileshtrivedi I understand the issue can be considered as resolved. If I'm mistaken, please, reopen it.
