### ISSUE TITLE
dumpconfig ignores StaticNodes

### ISSUE THREAD

**Issue by shazow** [ethereum/go-ethereum#16346]
#### System information

Geth version: 1.8.3-unstable (built from master)
OS & Version: Linux,
Commit hash : fe6cf00f480aa6347b8d55079cbe6c473482ea27

#### Expected behaviour

After adding some nodes to `geth/static-nodes.json`, I would expect `geth dumpconfig` to include those nodes.

I have confirmed that the static nodes _are_ being respected (ie. the node does connect to said nodes with --nodiscover). It's just that dumpconfig seems to ignore them.

#### Actual behaviour

```console
$ geth dumpconfig
[Node.P2P]
...
StaticNodes = []
TrustedNodes = []
...
```

#### Steps to reproduce the behaviour

1. Write some geth/static-nodes.json
2. Run `geth dumpconfig | grep StaticNodes`
3. :cry:

**Comment by zouguangxian** [comment]
I've fixed it. please refer to #17889.

**Comment by fjl** [comment]
My problem with this is that you'll have them set twice if you maintain static-nodes.json and then add them to the TOML config later. I think the current way is OK. static-nodes.json and trusted-nodes.json existed long before we had config file support. Now that config file is supported, the only reason why we keep them around is for backward compatibility.
