### ISSUE TITLE
Flags SyncMode cannot be combined with LightServ in geth v1.8.2

### ISSUE THREAD

**Issue by rkeene** [ethereum/go-ethereum#16345]
See comment here:  https://github.com/ethereum/go-ethereum/pull/15514#issuecomment-374257744

#### System information

Geth version: v1.8.2
OS & Version: All

#### Expected behaviour
`geth --syncmode=full --lightserv=80` should work

#### Actual behaviour
`geth --syncmode=full --lightserv=80` produces an error indicating that --syncmode and --lightserv cannot be combined

#### Steps to reproduce the behaviour
Run: `geth --syncmode=full --lightserv=80`

There appears to be an issue with the `checkExclusive` function with respect to string arguments -- they're not really used in the way the comment described above that function suggests they might, this leads to a bug combining --syncmode=full and --lightserv, when it is intended to prevent --syncmode=light and --lightserv from being combined.

**Comment by fxer** [comment]
I just ran into this updating our systemd script which specifically defined `--syncmode "fast"`. Since that is the geth default I was able to just remove the line from all our systemd units to get around it, but not ideal

**Comment by RaghavSood** [comment]
`--syncmode=full` and `--lightserv` also produce the same error in 1.8.10

**Comment by karalabe** [comment]
Fixed a while back by https://github.com/ethereum/go-ethereum/pull/17803.
