### ISSUE TITLE
Clique[PoA] Puppeth genesis generation adds a lot of random accounts

### ISSUE THREAD

**Issue by REPTILEHAUS** [ethereum/go-ethereum#16358]
Im not sure if this is a bug or not but Puppeth dumps a list of  addresses that seem to end with 1byte of incremental hex characters. 

Seems to happen when you set Clique and 1 signer account, worth noting is that accounts you pre-allocate funds to appear at the end of these and from initial testing with and without these accounts it doesn't seem to make a difference. 

Do we need these ? Id like to write my own genesis.json generator so just curious if these are totally necessary.

```
        "0000000000000000000000000000000000000004": {
            "balance": "0x1"
        },
        "0000000000000000000000000000000000000005": {
            "balance": "0x1"
        },
        "0000000000000000000000000000000000000006": {
            "balance": "0x1"
        },
        "0000000000000000000000000000000000000007": {
            "balance": "0x1"
        },
        "0000000000000000000000000000000000000008": {
            "balance": "0x1"
        },
        .....

        "00000000000000000000000000000000000000ad": {
            "balance": "0x1"
        },
        "00000000000000000000000000000000000000ae": {
            "balance": "0x1"
        },
        "00000000000000000000000000000000000000af": {
            "balance": "0x1"
        },
        "00000000000000000000000000000000000000b0": {
            "balance": "0x1"
        },

        ....
        "00000000000000000000000000000000000000fd": {
            "balance": "0x1"
        },
        "00000000000000000000000000000000000000fe": {
            "balance": "0x1"
        },
        "00000000000000000000000000000000000000ff": {
            "balance": "0x1"
        },

.....
accounts with pre-allocated funds appear next
```

**Comment by karalabe** [comment]
These are for the precompiled contracts. Ethereum defines that any account/contract touched that is left with a 0 balance, 0 nonce and no storage gets deleted. If we don't specify a balance for these account, the first time you interact with them, the nodes will delete them from state and they will be unavailable from that point onward.
