### ISSUE TITLE
https://geth.ethereum.org/downloads/ Impossible to download from China, Brasil over https://gethstore.blob.core.windows.net/builds?restype=container&comp=list

### ISSUE THREAD

**Issue by paulvi** [ethereum/go-ethereum#16361]
https://geth.ethereum.org/downloads/
Impossible to download from China now

![image](https://user-images.githubusercontent.com/1614482/37757695-d06db8f4-2de8-11e8-9301-3f9c53261a37.png)

there is about 1-2 minute waiting before failure message

![image](https://user-images.githubusercontent.com/1614482/37757809-296823c2-2de9-11e8-9bcc-7876826fccf9.png)

Is there alternative or direct URL for e.g. Windows zip?

This is possibly issue for https://github.com/ethereum/ethereum-org

**Comment by philsmd** [comment]
Did you try with your noscript browser extension turned off (or configured with exceptions for the scripts requested by ethereum.org etc)?

**Comment by paulvi** [comment]
Well, NoScript sets to block request to Google services like gstatic, that are no available anyways.

Yes, I tried with NoScript disabled as well. 

The problem is the request to https://gethstore.blob.core.windows.net/builds?restype=container&comp=list

**Comment by evertonfraga** [comment]
It times out quite often from Brazil — note that we do not have "the great firewall" around here.

**Comment by gruvin** [comment]
Lo and behold, it's happen to me today, 2020-06-29 NZT.  ¯\_(ツ)_/¯
