### ISSUE TITLE
'constant 18446744073709551615 overflows int64' when execute `go install ./cmd/...`

### ISSUE THREAD

**Issue by Kavin-Cao** [ethereum/go-ethereum#16368]
when I executed `go install ./cmd/...` in the go-ethereum src root dir, it failed!
log infomation:
```
# github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3
..\vendor\gopkg.in\olebedev\go-duktape.v3\duktape.go:133[C:\Users\CAOLIB~1\AppData\Local\Temp\go-build679865802\github.com\ethereum\go-ethereum\vendor\gopkg.in\olebedev\go-duktape.v3\_obj\duktape.cgo1.go:164:35]: constant 18446744073709551615 overflows int64
```
#### System information

Geth version: `1.8.3`
OS & Version: Windows 10 amd64
GOARCH=amd64
GOBIN=
GOEXE=.exe
GOHOSTARCH=amd64
GOHOSTOS=windows
GOOS=windows
GOPATH=C:\Users\Caolibao-VM\Desktop\dev\Go\gopath
GORACE=
GOROOT=C:\Users\Caolibao-VM\Desktop\dev\Go\go1.9.1
GOTOOLDIR=C:\Users\Caolibao-VM\Desktop\dev\Go\go1.9.1\pkg\tool\windows_amd64
GCCGO=gccgo
CC=gcc
GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\CAOLIB~1\AppData\Local\Temp\go-build038749335=/tmp/go-build -gno-record-gcc-switches
CXX=g++
CGO_ENABLED=1
CGO_CFLAGS=-g -O2
CGO_CPPFLAGS=
CGO_CXXFLAGS=-g -O2
CGO_FFLAGS=-g -O2
CGO_LDFLAGS=-g -O2
PKG_CONFIG=pkg-config
#### Backtrace

````
[backtrace]
````

**Comment by philsmd** [comment]
You should use the search function before opening a new issue: https://github.com/ethereum/go-ethereum/issues?q=18446744073709551615

solution: https://github.com/ethereum/go-ethereum/issues/16120#issuecomment-366621696 (also see https://github.com/ethereum/go-ethereum/issues/16334#issuecomment-374125634)

**Comment by Kavin-Cao** [comment]
OK,Thank you @philsmd , Now I upgrade go version, so that issue had been  resolved
