### ISSUE TITLE
mobile: add second constructor: BigInt(String)

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#16364]
currently you need to do `BigInt(0).apply { setString(val,base) }` to e.g. transfer more than 9.2ETH which is not that intuitive

follow-up from #16337

**Comment by sempiecampos** [comment]
I am having the same issue, BigInt.setString(String "String", int base) does  not work.  I get Attempt to invoke virtual method 'void org.ethereum.geth.BigInt.setString(java.lang.String, long)' on a null object reference, I also tried setBytes and the same exception is thrown;

Suggestion add new constructors or add Interface to include Token.decimals

**Comment by sempiecampos** [comment]
I found the following works 
String wei = Convert.toWei(ammount, Convert.Unit.ETHER).toString();
            BigInt tt = new BigInt(0);
            tt.setString(wei,10);

but a string constructor is on the wish-list

**Comment by adamschmideg** [comment]
Inactive for a year
