### ISSUE TITLE
deploy a smart contract in non interactive mode

### ISSUE THREAD

**Issue by mascom8** [ethereum/go-ethereum#16365]
Hi there,

I would like to automate the deployment of a smart contract (given an existing 'foo.sol' file) using only Bash, solc, Geth, and curl. 

I saw that I need to use the eth_sendTransaction RPC command but how to format properly the data field inside for at least embedding the contract bytecode ?

What to retrieve from the .bin / .abi files?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
