### ISSUE TITLE
geth console: calling methods on contracts fails enigmatically

### ISSUE THREAD

**Issue by thinred** [ethereum/go-ethereum#1636]
Hi,
when I call any method that I have to pay for, I get this:

    > f.add(5)
    could not decode, from not valid, is required
        at <unknown>
        at <unknown>
        at <unknown>
        at <unknown>
        at add (<anonymous>:-93875:-23)
        at <anonymous>:1:1

It is caused by the fact that I don't have eth.defaultAccount set:

    > eth.defaultAccount = eth.accounts[1]
    '0xABC'
    > f.add(5)
    Please unlock account ABC.
    Passphrase: 
    Account is now unlocked for this session.
    '0xabc42'

Still, the message is rather weird, and does not point to the problem at all.

Cheers,
Tomasz

**Comment by obscuren** [comment]
The underlaying code does not know what you're attempting at all. It's rather stupid; it only knows you're trying to send a transaction of sorts and you haven't supplied a valid sender (e.g. you don't specify one). 

Another way going about this is by calling like `f.add(5, {from: eth.accounts[1]})`

**Comment by thinred** [comment]
Yes, this is precisely what I found out, but still, the message is grammatically confusing If it would be something like "could not decode `from'" or "`from' is not provided" it would at least point to the problem. Only after your comment I realized that "from" in the console refers to the sender...

And I'm not the only one who finds it confusing: 
https://forum.ethereum.org/discussion/2640/exceeds-block-gas-limit-at-invalidresponse-60926-189
https://forum.ethereum.org/discussion/2459/cant-execute-my-contract
https://gist.github.com/TOMOAKI12345/1ba1b58e0877a6fdd261

Thank you for the fast response,
Tomasz

**Comment by obscuren** [comment]
Indeed. We can certainly improve on the error messages. Thank you for the suggestion!
