### ISSUE TITLE
rpc call "personal_signAndSendTransaction" sending tokens but losing ether 3 hours later

### ISSUE THREAD

**Issue by jingfei05** [ethereum/go-ethereum#16373]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version` 
> Version: 1.8.1-stable

OS & Version: Windows/Linux/OSX
Linux
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

Go Version: go1.9.4

Commit hash : (if `develop`)
Git Commit: 1e67410e88d2685bc54611a7c9f75c327b553ccc

#### Expected behaviour
1. Geth connect to testnet Ropsten and all addresses, contract, and transactions are on Ropsten.
2. sending tokens to my wallet address using following RPC call.
**RPC call:** personal_signAndSendTransaction
Token Transaction received by the destination account.                       OK
if we use the same json data but using eth_SendTransaction would send the token as well but the difference is that all ether in the sending address will be sent out to the same address.  Please see the solidity contract code in backtrace. I have gone thru the code many times already can see anything wrong with it. It's quite standard contract.

#### Actual behaviour
The expected token transactions was sent but three hours later, three ether transactions occurred and a total of 3x0.19958 ethers were take away from the address: 0x2f6e4dd0286aacdbfa88db0e92cc7a1c89709175.
All ethers sent to a unknown address:
0xbc3edbdfe92dfe06bc005d499b2a35649baec237 

0x7c6121679ddeae6aa42759acbf4a8032560438440f69a1103d983e3110c90941 | 2882698 | 8 hrs 58 mins ago | 0x2f6e4dd0286aacdbfa88db0e92cc7a1c89709175 | OUT | 0xbc3edbdfe92dfe06bc005d499b2a35649baec237 | 0.19958 Ether | 0.00042
-- | -- | -- | -- | -- | -- | -- | --
0x342b729dbf7763aff4d606cf4f2f99e10dda6910a876136753bd27975e13ad8b | 2882698 | 8 hrs 58 mins ago | 0x2f6e4dd0286aacdbfa88db0e92cc7a1c89709175 | OUT | 0xbc3edbdfe92dfe06bc005d499b2a35649baec237 | 0.19958 Ether | 0.00042
0x38fde4291f48fac9bcf42a79570f04b7841f2cb58a01d8148e9dbf13e434c08f | 2882698 | 8 hrs 58 mins ago | 0x2f6e4dd0286aacdbfa88db0e92cc7a1c89709175 | OUT | 0xbc3edbdfe92dfe06bc005d499b2a35649baec237 | 0.19958 Ether | 0.00042
#### Steps to reproduce the behaviour
{
	"jsonrpc":"2.0",
	"method":"personal_signAndSendTransaction",
	"params":[
		{
			"from": "0x2f6e4dd0286aacdbfa88db0e92cc7a1c89709175",
			"to": "0x567527C374602B9d206DDfaf001dECA3F595b7b5",
			"gasLimit" : "0xcc40",
			"value": "0x0",
			"data": "0xa9059cbb0000000000000000000000005fec1b24b198ecf5feb9e44ec79314594225c85300000000000000000000000000000000000000000000021e27c1806e59a40000"		
		},
			"bitontop123"
	],
	"id":1
}

TxHash:
0xb6f795f717fd5f95c2c4157802c9946e68c6c2caa61a83aee280d20f634e3646 
TxReceipt Status:   Success
Block Height:          2881961 (3846 block confirmations)
TimeStamp:            11 hrs 59 mins ago (Mar-22-2018 05:15:55 AM +UTC)
From:                     0x2f6e4dd0286aacdbfa88db0e92cc7a1c89709175
To:                         Contract 0x567527c374602b9d206ddfaf001deca3f595b7b5  
Token Transfer:      10,001 ERC20 (TESTOKEN)  from 0x2f6e4dd0286aacdbfa88db0e92cc7a1c89709175to  0x5fec1b24b198ecf5feb9e44ec79314594225c853
Value:                     0 Ether ($0.00) 
Gas Limit:               90000 
Gas Used By Txn:   38036 
Gas Price:               0.00000002 Ether (20 Gwei) 
Actual Tx Cost/Fee:              0.00076072 Ether ($0.000000) 
Nonce:                   1436 
InputData:              Function: transfer(address _to, uint256 _value) ***
                               MethodID: 0xa9059cbb
                               [0]:  0000000000000000000000005fec1b24b198ecf5feb9e44ec79314594225c853
                               [1]:  00000000000000000000000000000000000000000000021e27c1806e59a40000
===================================================================
#### Backtrace
pragma solidity ^0.4.16;

interface tokenRecipient { function receiveApproval(address _from, uint256 _value, address _token, bytes _extraData) public; }

contract AIBETHToken {
    // Public variables of the token
    string public name;
    string public symbol;
    uint8 public decimals = 18;
    // 18 decimals is the strongly suggested default, avoid changing it
    uint256 public totalSupply;

    address public coinOwner;
    uint256 public receivedMoney;
    mapping (address => uint256) public pendingWithdrawals;

    // This creates an array with all balances
    mapping (address => uint256) public balanceOf;
    mapping (address => mapping (address => uint256)) public allowance;

    // This generates a public event on the blockchain that will notify clients
    event Transfer(address indexed from, address indexed to, uint256 value);

    // This notifies clients about the amount burnt
    event Burn(address indexed from, uint256 value);

    /**
     * Constructor function
     *
     * Initializes contract with initial supply tokens to the creator of the contract
     */
    function AIBETHToken(
        uint256 initialSupply,
        string tokenName,
        string tokenSymbol
    ) public payable {
        totalSupply = initialSupply * 10 ** uint256(decimals);  // Update total supply with the decimal amount
        balanceOf[msg.sender] = totalSupply;                // Give the creator all initial tokens
        name = tokenName;                                   // Set the name for display purposes
        symbol = tokenSymbol;                               // Set the symbol for display purposes
    }

    /**
     * Internal transfer, only can be called by this contract
     */
    function _transfer(address _from, address _to, uint _value) internal {
        // Prevent transfer to 0x0 address. Use burn() instead
        require(_to != 0x0);
        // Check if the sender has enough
        require(balanceOf[_from] >= _value);
        // Check for overflows
        require(balanceOf[_to] + _value > balanceOf[_to]);
        // Save this for an assertion in the future
        uint previousBalances = balanceOf[_from] + balanceOf[_to];
        // Subtract from the sender
        balanceOf[_from] -= _value;
        // Add the same to the recipient
        balanceOf[_to] += _value;
        Transfer(_from, _to, _value);
        // Asserts are used to use static analysis to find bugs in your code. They should never fail
        assert(balanceOf[_from] + balanceOf[_to] == previousBalances);
    }

    /**
     * Transfer tokens
     *
     * Send `_value` tokens to `_to` from your account
     *
     * @param _to The address of the recipient
     * @param _value the amount to send
     */
    function transfer(address _to, uint256 _value) public {
        _transfer(msg.sender, _to, _value);
    }

    /**
     * Transfer tokens from other address
     *
     * Send `_value` tokens to `_to` on behalf of `_from`
     *
     * @param _from The address of the sender
     * @param _to The address of the recipient
     * @param _value the amount to send
     */
    function transferFrom(address _from, address _to, uint256 _value) public returns (bool success) {
        require(_value <= allowance[_from][msg.sender]);     // Check allowance
        allowance[_from][msg.sender] -= _value;
        _transfer(_from, _to, _value);
        return true;
    }

    /**
     * Set allowance for other address
     *
     * Allows `_spender` to spend no more than `_value` tokens on your behalf
     *
     * @param _spender The address authorized to spend
     * @param _value the max amount they can spend
     */
    function approve(address _spender, uint256 _value) public
        returns (bool success) {
        allowance[msg.sender][_spender] = _value;
        return true;
    }

    /**
     * Set allowance for other address and notify
     *
     * Allows `_spender` to spend no more than `_value` tokens on your behalf, and then ping the contract about it
     *
     * @param _spender The address authorized to spend
     * @param _value the max amount they can spend
     * @param _extraData some extra information to send to the approved contract
     */
    function approveAndCall(address _spender, uint256 _value, bytes _extraData)
        public
        returns (bool success) {
        tokenRecipient spender = tokenRecipient(_spender);
        if (approve(_spender, _value)) {
            spender.receiveApproval(msg.sender, _value, this, _extraData);
            return true;
        }
    }

    /**
     * Destroy tokens
     *
     * Remove `_value` tokens from the system irreversibly
     *
     * @param _value the amount of money to burn
     */
    function burn(uint256 _value) public returns (bool success) {
        require(balanceOf[msg.sender] >= _value);   // Check if the sender has enough
        balanceOf[msg.sender] -= _value;            // Subtract from the sender
        totalSupply -= _value;                      // Updates totalSupply
        Burn(msg.sender, _value);
        return true;
    }

    /**
     * Destroy tokens from other account
     *
     * Remove `_value` tokens from the system irreversibly on behalf of `_from`.
     *
     * @param _from the address of the sender
     * @param _value the amount of money to burn
     */
    function burnFrom(address _from, uint256 _value) public returns (bool success) {
        require(balanceOf[_from] >= _value);                // Check if the targeted balance is enough
        require(_value <= allowance[_from][msg.sender]);    // Check allowance
        balanceOf[_from] -= _value;                         // Subtract from the targeted balance
        allowance[_from][msg.sender] -= _value;             // Subtract from the sender's allowance
        totalSupply -= _value;                              // Update totalSupply
        Burn(_from, _value);
        return true;
    }

    function sendReceivedMoneyToOwner() public payable returns (bool) {

        if (msg.value > receivedMoney) {
            pendingWithdrawals[coinOwner] += msg.value;
            coinOwner = msg.sender;
            receivedMoney = msg.value;
            return true;
        }
        else {
            return false;
        }
    }

    function withdraw() public {
        uint amount = pendingWithdrawals[msg.sender];
        // Remember to zero the pending refund before

        // sending to prevent re-entrancy attacks
        pendingWithdrawals[msg.sender] = 0;

        //msg.sender.transfer(amount);
        if(!msg.sender.send(amount))
        {
            revert();  //throw;  BUT throw is deprecated!
        }
    }
}
````
[backtrace]
````

**Comment by karalabe** [comment]
My guess is that you exposed your node to the public internet and unlocked your account. There are bots actively searching for unlocked accounts and try to empty them. They probably don't bother differentiating between testnet clients and mainnet ones.

The same account holds mainnet funds too 0xbc3edbdfe92dfe06bc005d499b2a35649baec237 .

**Comment by jingfei05** [comment]
Thanks for the providing suggestion on this issue.  When i am using the eth_sendTransactions, i did unlock the account but forgot to lock it because it's just a testnet so no access restrictions to the geth node.  It seems the bot has been in action to monitoring my testing node and always ready to take ether away because the account is unlocked in a certain period. I did do a test that after an unlock, the account will be locked again after a time period but not sure how long.

However, according to the following description of personal_sendTransaction as following:
```
The transaction is the same argument as for eth_sendTransaction and contains the from address. If the passphrase can be used to decrypt the private key belogging to tx.from the transaction is verified, signed and send onto the network. The account is not unlocked globally in the node and cannot be used in other RPC calls.
```
The personal_sendTransaction command is not globally unlock the account, so it's not making sense that the bot can take ether from the address 3 hours later.  It is possible that the bot has a chance to take the ether because the personal_sendTransaction RPC call is not atomic. Three hours later, this is kind of insane, so i am wondering if it's related to the bot, then does that mean there is security flaw in this personal_sendTransaction RPC call? Of course, normal geth node is not opening access for this command.

**Comment by karalabe** [comment]
If you unlocked your account, a malicious user can sign transactions in advance with it, and keep those signed transactions privately. When your account gets funded, the attacker can publish the hidden-but-already-signed transactions to take the funds off.

**Comment by jingfei05** [comment]
I see. Thanks for the explanation.
