### ISSUE TITLE
Make fails? no Idea why

### ISSUE THREAD

**Issue by Logic6497** [ethereum/go-ethereum#16378]
vendor/gopkg.in/olebedev/go-duktape.v3/duktape.go:133: constant 18446744073709551615 overflows int64
util.go:45: exit status 2
exit status 1
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 1

This is on linux Trying to do the make command

**Comment by Logic6497** [comment]
I fixed that issue Now I have this 


github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/comparer

**Comment by Logic6497** [comment]
when I try Make geth it says this
logic@logic-MS-7851:~/open-ethereumclassic-pool$ make geth
make: *** No rule to make target 'geth'.  Stop.
logic@logic-MS-7851:~/open-ethereumclassic-pool$
Before I was just trying make

**Comment by Asad97akay** [comment]
when I try Make geth it says this
/open-ethereumclassic-pool$ make geth
make: *** No rule to make target 'geth'. Stop.
/open-ethereumclassic-pool$
Before I was just trying make

Im having the same issue can you please help ?
