### ISSUE TITLE
Installation Instructions for Ubuntu ERROR

### ISSUE THREAD

**Issue by linuxhsj** [ethereum/go-ethereum#16375]
`linux@ubuntu:~$ sudo add-apt-repository -y ppa:ethereum/ethereum
Cannot add PPA: 'ppa:~ethereum/ubuntu/ethereum'.
ERROR: '~ethereum' user or team does not exist.
linux@ubuntu:~$ 
linux@ubuntu:~$ 
`

**Comment by linuxhsj** [comment]
`linux@ubuntu:~/Documents/geth$ git clone https://github.com/ethereum/go-ethereum
Cloning into 'go-ethereum'...
fatal: unable to access 'https://github.com/ethereum/go-ethereum/': Could not resolve host: github.com
`

**Comment by linuxhsj** [comment]
Refer to the following link to install geth unsuccessful
https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu

Can you give a correct installation guidance on ubuntu 16.4? Thanks in advance.

**Comment by linuxhsj** [comment]
@bts @shazow @fjl @fjl @sauliusgrigaitis @caktux

**Comment by karalabe** [comment]
This is  bit more updated instruction https://ethereum.github.io/go-ethereum/install/

> Could not resolve host: github.com

That seems to be a very very bad looking error. Are you behind some very restricted firewall?

**Comment by thomasmodeneis** [comment]
It really seems like you are blocked to reach github. 
`Could not resolve host: github.com`
Are you able to ping it?
```
➜  ~ ping github.com
PING github.com (192.30.253.113) 56(84) bytes of data.
64 bytes from lb-192-30-253-113-iad.github.com (192.30.253.113): icmp_seq=1 ttl=54 time=111 ms
64 bytes from lb-192-30-253-113-iad.github.com (192.30.253.113): icmp_seq=2 ttl=54 time=112 ms
```
