### ISSUE TITLE
Bootnode not syncing with any clients or showing any output

### ISSUE THREAD

**Issue by REPTILEHAUS** [ethereum/go-ethereum#16379]
I'm trying to use the Bootnode feature of geth but nodes are not found. I see the desired output is ping/pong on the bootnode instance with the other connecting machines.

Im using AWS EC2 instances, using Clique, 1 bootnode, 1 standard, 3 signers (all separate machines). At first I came across this error with verbosity at 6:
```
DEBUG[03-23|10:18:59] Couldn't add port mapping                proto=tcp extport=30303 intport=30303 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"
```
I managed to suppress it by adding the --nat flag with the instance public IP address but still no nodes are connecting.

I tried to connect to the bootnode server via netcat and it shows that the port is open
but no other information:
```
root@server:~# nc -u -vvv 56.51.85.249 30310
    aws-blah-blah.compute.amazonaws.com [56.51.85.249] 30310 (?) open
```

Similarly netstat shows that the bootnode server is accessible, but via IPv6:
```
udp6       0      0 [::]:30310              [::]:*                              3456/bootnode  
```

Any ideas where I'm going wrong with this ? using Geth 1.8.1 and go1.9.2 

# instance 1
```
geth --datadir ~/testnet/data --bootnodes="enode://33cc19e8c71a6b3f7da49615bac9785da08825071d2c5c1bf6680d8a10c2de91ff746dd64735e2e7462938308d09b7a716f822610b598b045e29f33791fbb899@56.51.85.249:30301" --nodiscover --networkid 47891 console --rpc --rpcapi admin,db,eth,debug,miner,net,txpool,personal,web3 --rpcport "8545" --rpcaddr "0.0.0.0" --rpccorsdomain "*" --nat "extip:36.241.43.9" 
```

# bootnode
```
bootnode --verbosity 9 --nodekey bootnode.key 
    INFO [03-23|10:44:05] UDP listener up                          self=enode://33cc19e8c71a6b3f7da49615bac9785da08825071d2c5c1bf6680d8a10c2de91ff746dd64735e2e7462938308d09b7a716f822610b598b045e29f33791fbb899@[::]:30301
```

# instance 2
```
geth --datadir ~/testnet/data --bootnodes="enode://33cc19e8c71a6b3f7da49615bac9785da08825071d2c5c1bf6680d8a10c2de91ff746dd64735e2e7462938308d09b7a716f822610b598b045e29f33791fbb899@56.51.85.249:30301" --nodiscover --network
```

and the genesis is pretty basic:
```
{
  "config": {
    "chainId": 47891,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "byzantiumBlock": 4,
    "clique": {
      "period": 1,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x5ab3a18c",
  "extraData": "0x00000000000000000000000000000000000000000000000000000000000000003f82f2f04af76178d2e4434a5ce92a71d14444ea9661daf430790f424b5e5c192915bbf531c30bff2914be90b2a00f66a5b0789c2cee5836df1f1c0300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
      .... Address info ....
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```

Update: still not working but i set one of the nodes to use these flags --verbosity 9 --v5disc --bootnodesv5  and get the error 
```
msg="--- (0) pongTimeout for e7cc19e8c71a6b3f@56.51.85.249:30301 verifyinit -> unknown (ok)"
```

**Comment by anirudhkabi** [comment]
Hi,

I have faced similar issue. There are two things you need to change.
1. You seem to have been using your public IPs to communicate among the EC2 instances. Use private IPs. They would mostly be in in same subnet (private address space) and they can ping each other. Also make sure your security group for all the instances runnining nodes/sealers/miners is same or atleast allow connections on required ports... say 30300-10 open for UDP and rpc ports used to be open for TCP connections
2. start your bootnode on your private IP and not [::]. Use command
bootnode --verbosity 9 --nodekey bootnode.key --addr 'privateip:port'

It has worked for me with geth 1.8.12.. Shoudl work for you

**Comment by jonassunandar** [comment]
Hey I have a similar issue. Can you please post your solution for this problem? Thanks in advance!

**Comment by istiaque010** [comment]
> 
It is private IP but how can I make it using public IP? Because I have to connect it from different places and different machines.
