### ISSUE TITLE
request: Transfer all funds

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/go-ethereum#1637]
There should be a way to transfer all funds in an account to a new address without having to manually compute the gas necessary for the transfer. Right now the only other way is to start high and keep inching down until the client accepts a transfer.

**Comment by obscuren** [comment]
A regular transaction is always `21000` gas. Default gas is set to `90000`, that should be enough. Are you trying something different perhaps?

**Comment by aakilfernandes** [comment]
Nope, had no idea the transaction was constant. Assumed it was like bitcoin where it depends on the transaction size. I still think a 'send all funds' would be nice.

**Comment by JustinDrake** [comment]
21000 gas, but what's the gas price?

**Comment by lapause** [comment]
+1 I think this feature could be more generic, i.e. an *eth.sendTransactionIncludingFees()* method that would automatically substract gasPrice * gasLimit from the given amount.

**Comment by karalabe** [comment]
```
var gas   = 21000;
var price = web3.toWei(50, "shannon");
var total = eth.getBalance(FROM_ACCOUNT)

eth.sendTransaction({from: FROM_ACCOUNT, to: TO_ACCOUNT, gasPrice: price, gas: gas, value: total - gas * price});
```

;)

**Comment by lapause** [comment]
Not saying it's not possible now ;-) Just that the feature could deserve a helper method or wrapper.

**Comment by karalabe** [comment]
Hopefully our next point of focus will be reworking the APIs to make the more developer friendly and extended :)

**Comment by obscuren** [comment]
@lapause don't get me wrong but I don't believe that adding such functionality is our responsibility. See the console as node.js and any additional functionality should be coded up in a library. This is one of the reasons why we have the `loadScript` method. Community developed `eQuery` :-D

**Comment by lapause** [comment]
@obscuren Rethinking of it, you're totally right!

**Comment by karalabe** [comment]
Ok, so then Ima close this thread down if we all agreed on how to do it ;)
