### ISSUE TITLE
Rootkits can infect kernel RNG and cause attacker previsibility in key generation?

### ISSUE THREAD

**Issue by 3esmit** [ethereum/go-ethereum#16372]
I am researching regarding security of key generation, while I imagine geth use a safe random generation source as kernel RNG.

I figured out that this is an point of rootkit attack, where could replace the RNG with predicatable values. 
This attack is not only high impact but also "invisible". To attack the affected accounts the attacker dont need to connect with victim computers, it can just run the tampered-RNG itself and figure out the keys.
Even computers airgapped, if infected with a tampered-RGN, will generate previsible RNG. 

Kernel RNG is suppoused to have a buffer of entropy based on sensors inputs, but geth might not notice that it had been tampered.

A way to mitigate this would be geth accepting an application seed at key generation, and mix with the kernel RNG, meaning that both sources need to be tampered to predict RNG.

**Comment by 3esmit** [comment]
Keys generated in servers and virtual envoirements are really random?

So in example of an exchange that generates keys in their server for user depositing funds might not be so random, because the kernel RNG relay on sensors that are not usually available in servers. How they would create not predictable keys in their servers?

**Comment by ligi** [comment]
I think this issue is not really go-ethereum specific but more a general thought on security that perhaps should be discussed in another place and not this issue tracker for a specific implementation. 
Generating keys on servers sounds like a bad idea IMHO anyway. Thought getting rid of servers like this was the plan ..-)

**Comment by 3esmit** [comment]
@ligi Agreed that we are trying to remove servers, I'm totally about it, however some services still use this practice (exchanges), and this should be pointed out if they already don't know.

But in case of personal computers, geth should suggest to also use another source of entropy (such as a random drawing in the screen). I imagine a scenario where a hardware company, such smart phone or laptop company, start using some tampered kernel in the o.s. and their users arent aware of it, and get invisibly attacked. 

For sure a targeted rootkit could also affect application layer, but solely tampering RNG right now would affect all application relaying sole on it. 
If geth suggest the use of application defined entropy + internal (kernel) entropy than a rootkit would have to target specifically the application. 
This geth suggestion also make clearer that RNG dont work well on server/virtual env. 
If not suggested, at least should be documented somewhere.

**Comment by ligi** [comment]
> @ligi Agreed that we are trying to remove servers, I'm totally about it, however some services still use this practice (exchanges)

IMHO we should not use these services and push the movement towards decentralized exchanges.

> But in case of personal computers, geth should suggest to also use another source of entropy (such as a random drawing in the screen). 

I do not think this is responsibility of go-etherum. This is already done by operating systems like the linux kernel entropy pool. I think this is a good place to do it and better separation of concerns than doing it in go-ethereum. I do not see the security benefit in doing it also in the application layer.
