### ISSUE TITLE
error:insufficient funds for gas * price + value .And    geth client  can get balance but web3j getBalace is 0 

### ISSUE THREAD

**Issue by huangqhgit** [ethereum/go-ethereum#16386]

**Comment by huangqhgit** [comment]
web3.ethGetBalance().send().getBalance  is 0  i dont know why?

**Comment by huangqhgit** [comment]
and  SmartContract.deploy()  has the error: insufficient funds for gas * price + value

**Comment by ligi** [comment]
I think you need to give more details - with so little details it is hard to figure out what exactly the problem is and if it is a problem with go-ethereum at all ..

**Comment by huangqhgit** [comment]
i find the  problem! because i start geth client on local,but i start geth use Rinkeby (web3j document said),thanks ~
