### ISSUE TITLE
Invoke a pre-initialized python console

### ISSUE THREAD

**Issue by carver** [ethereum/go-ethereum#16382]
@karalabe mentioned interest in invoking a python console via geth. I think this would be sweet too, and wanted to track it here.  cc @pipermerriam

What do you guys think of this as a rough goal?
```sh
$ geth pyconsole

Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

Connecting with...
w3 = Web3(IPCProvider('/home/hacker/.ethereum/geth.ipc'))

In [1]: w3.version.node
Out[1]: 'Geth/v1.8.2-stable-b8b9f7f4/linux-amd64/go1.9.4'

In [2]: 
```

**Comment by karalabe** [comment]
Not necessarily via geth btw, I'm completely fine with `pyconsole ws://localhost:8545` too.

**Comment by karalabe** [comment]
The interesting catch is how to expose non standard methods. E.g. we have admin, debug, whatnot APIs. For the external js console too we were thinking about making an API descriptor endpoint that could return all the extra methods the node supports and then client libs can generate callable wrappers on the fly.

**Comment by carver** [comment]
> Not necessarily via geth btw

One thing I kind of like about invoking from geth is that it's natural to reuse configuration parameters that people are familiar with from geth. A couple examples:

1. A custom IPC file location:
```sh
$ geth --datadir /mnt/ssd/.ethereum/ pyconsole
Connecting with...
w3 = Web3(IPCProvider('/mnt/ssd/.ethereum/geth.ipc'))

In [1]:
```

2. `geth --dev` requires a custom IPC location and a fixup for the long `extraData` field
```sh
$ geth --dev pyconsole
Connecting with...
w3 = Web3(IPCProvider('/tmp/geth.ipc'))
w3.middleware_stack.inject(geth_poa_middleware, layer=0)

In [1]:
```

---

> For the external js console too we were thinking about making an API descriptor endpoint that could return all the extra methods the node supports and then client libs can generate callable wrappers on the fly.

That's really interesting. We describe some of the endpoints using ABI-like definitions here: https://github.com/ethereum/web3.py/blob/master/web3/utils/rpc_abi.py#L29-L50 . A descriptor like that would be the cleanest way for us to automatically support new endpoints. Without any type definitions, it would be awkward|impossible to do type conversions to python native types.

Even without setting that up though, `geth` is a big enough target that we already support some custom endpoints. We could manually add all the custom endpoints that geth has, and enable them when invoked via `pyconsole`. Of course that would good tiresome if you plan to continue adding many new custom endpoints. :)

**Comment by Ruethairat** [comment]
ในวันที่ ส. 24 มี.ค. 2018 00:08 น. Jason Carver <notifications@github.com>
เขียนว่า:

**Comment by carver** [comment]
After sleeping on it, it occurred to me that a natural solution would be a simple alias. So this command:

```sh
geth --datadir /home/hacker/.ethereum/ pyconsole
```

would simply invoke this shell command:

```sh
pyconsole /home/hacker/.ethereum/geth.ipc
```

(Some alternate names for `pyconsole`: `ethpy`, `pyeth`, `web3py`. Anyway, the name is not really a critical part of this issue.)

That gives us a clean geth integration, and a more general all-node console.

**Comment by pipermerriam** [comment]
Assuming `pyconsole` was a nice easy-to-install stand-alone bash script or something it could also allow us to remove the code from trinity.
