### ISSUE TITLE
Geth dumpconfig in Windows PowerShell with Incompatible File Encoding

### ISSUE THREAD

**Issue by msagansk** [ethereum/go-ethereum#16383]
#### System information

Geth version: 1.8.2-stable-b8b9f7f4
OS & Version: Windows 10

#### Expected behaviour

Should be able to dumpconfig in PowerShell and immediately run geth after with that config file.

#### Actual behaviour

PS C:\Ethereum> geth --datadir "C:\Ethereum" --lightserv 25 --identity Mearix dumpconfig > config.toml
INFO [03-22|20:25:11] Maximum peer count                       ETH=25 LES=100 total=125
PS C:\Ethereum> geth --config config.toml
Fatal: config.toml, line 1: invalid TOML syntax
PS C:\Ethereum>

#### Reason

PowerShell defaults to outputting text files in UCS-2 LE BOM. If I change the encoding of the file to ANSI or UTF-8 geth works fine. But from a user experience point of view, geth should be able to read many different text file encoding formats out of the box.

**Comment by holiman** [comment]
Possible fix, add `dumpconfig conf.toml` and have geth write to the file, or `dumpconfig - ` to write to `stdout`

**Comment by karalabe** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/18327. `dumpconfig` now accepts an optional filename parameter into which to dump the config on platforms where piping is problematic.
