### ISSUE TITLE
How to get the ETH address all assets

### ISSUE THREAD

**Issue by blockChainB** [ethereum/go-ethereum#16389]
i know call eth.getBalance("address") function to get eth balance, but How to get the ETH address all assets,other tokens

**Comment by karalabe** [comment]
You can't. A token is just a random contract living in the blockchain, whose storage bits are interpreted as you having a balance. I can create an arbitrary contract and it's purely user interpretation as to what the data storage means.

In theory we could track for example all contracts that implement the ERC20 interface and list those as tokens, but that would only be a subset, and it would list a ton of junk.

It's up to users to track interesting contracts either manually, or perhaps via some automated tool and whitelisted token lists.
