### ISSUE TITLE
High CPU usage When I call the method 'signTxPassphrase'

### ISSUE THREAD

**Issue by Musk66** [ethereum/go-ethereum#16384]
Geth version:1.8.2
OS:iOS 11.0
When I call the method 'signTxPassphrase', it use high CPU.And I call it continuously, my computer memory will be used a multiple of two. to 300(first)->600(second).

**Comment by ligi** [comment]
So you are on mobile when I am reading this correctly? Do you use Geth.LightScryptN, Geth.LightScryptP?

**Comment by Musk66** [comment]
@ligi Yes,I use Geth.LightScryptN, Geth.LightScryptP to create keystore

**Comment by Musk66** [comment]
@ligi I read the API annotation again,I see how to modify.Thank you!
