### ISSUE TITLE
Forget solo account password

### ISSUE THREAD

**Issue by lipangit** [ethereum/go-ethereum#16391]
Hello I forget my solo account password, But I can not delete solo account password, I delete every where about account, I can not find any keystore in my cumputer, 

and I have delete the main net account , but I can not delete the solo net account, can you help me 
![image](https://user-images.githubusercontent.com/2038071/37913753-358a1694-3148-11e8-962b-e93fb02c5911.png)

**Comment by philsmd** [comment]
if no account is present, geth will create an automatic account for the solo network.
The password is the empty string (zero-length password). Just hit the enter key whenever you are asked for the password.

**Comment by karalabe** [comment]
As @philsmd mentioned, if you're running `--dev`, the password is empty, but it's an ephemeral datadir anyway, so a restart will wipe everything.
