### ISSUE TITLE
Go fails with exception when running state test.

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#1639]
Go fails with exception 
I0811 11:55:19.160355    8176 main.go:67] runTest StateTests
F0811 11:55:19.165600    8176 main.go:184] randomStatetest: (26e38ffb) balance failed. Expected 0x023523858d976ebf, got 8042382364137 => 159064375972290774

on test
https://github.com/ethereum/tests/blob/develop/StateTests/RandomTests/st201507281036GO.json

**Comment by obscuren** [comment]
And you are sure this is a go fail?

**Comment by Gustav-Simonsson** [comment]
@winsvega CPP fails on that test for me, when changing to the values cpp expects, Go also passes: https://github.com/Gustav-Simonsson/go-ethereum/commit/624a0967c8bc8dceceadb9c7affe0ce6e8ebbacb

**Comment by obscuren** [comment]
What was the issue?
