### ISSUE TITLE
bootnode not work for finding peers

### ISSUE THREAD

**Issue by gravin** [ethereum/go-ethereum#16403]
i firstly created one bootnode
bootnode --genkey=./data/boot.key
nohup bootnode --nodekey=./data/boot.key >>boot.log 2>&1 &

then created another 2 geth node, and use admin.addPeer() to add bootnode ecode as their peer, 
but found it doesnt work. they still cant find each other.

**Comment by karalabe** [comment]
`addPeer` tries to connect to full nodes. A bootnode is not a full node.

You'd need to start geth with `--bootnode=[...]`.

**Comment by gravin** [comment]
it works ,but always need to change start shell by editing the node url
also found although the local network is fine, but  cant connect through internet
