### ISSUE TITLE
Unable to unlock account in Geth JS Console. Error: The method personal_unlockAccount does not exist/is not available

### ISSUE THREAD

**Issue by ltfschoen** [ethereum/go-ethereum#16407]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version` - Geth/v1.8.2-stable/darwin-amd64/go1.10
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour

I expect to be able to by able to use Geth JS Console to unlock the account that I imported into Geth on the Ropsten network  

#### Actual behaviour

I used Geth to connect to Ropsten so I can deploy a smart contract to it using an account that I imported.

In the Geth JS Console when I run the following after importing an account the following appears:

```
> eth.accounts
["0xcdea3bfc82cbe46b8a7a8a648eda0969f145468b"]
```

But when I try to unlock it before deploying a smart contract to Ropsten, it shows the following error after I enter my passphrase `Error: The method personal_unlockAccount does not exist/is not available`:

```
personal.unlockAccount(eth.accounts[0])
```
Unlock account 0xcdea3bfc82cbe46b8a7a8a648eda0969f145468b
Passphrase: 
Error: The method personal_unlockAccount does not exist/is not available
```

#### Steps to reproduce the behaviour

I was trying to deploy a smart contract by connecting Truffle to Geth. Below are the steps I followed to encounter the error `Error: The method personal_unlockAccount does not exist/is not available`. I was using Geth/v1.8.2-stable/darwin-amd64/go1.10, Truffle v4.0.6 (core: 4.0.6), Solidity v0.4.19 (solc-js)

* Add to truffle.js file:

```
ropsten: {
  network_id: 3,
  host: "localhost",
  port: 8545,
  gas: 2900000
}
```

* Open Terminal Window 1

* reference: https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts
* reference: https://ether.direct/2017/08/15/how-to-deploy-a-truffle-contract-to-ropsten/
* reference: https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options
* in metamask click "..." icon next to account that want to use with
ropsten (i.e. 0xcdeA3bfc82CBe46B8a7A8A648eDA0969F145468b)
* choose "Export Private Key"
* choose "Save As File" (i.e. "MetaMask RopTest1 Private Key.csv")

```
touch "/Users/Ls/Downloads/MetaMask RopTest1 Password";
chmod 700 "/Users/Ls/Downloads/MetaMask RopTest1 Password";
cat > "/Users/Ls/Downloads/MetaMask RopTest1 Password";
> (((ENTER PASSWORD: testtest, then PRESS CTRL+D to exit)))

geth --testnet --networkid=3 account import \
  --password="/Users/Ls/Downloads/MetaMask RopTest1 Password" \
  "/Users/Ls/Downloads/MetaMask RopTest1 Private Key.csv"
```

* show Ropsten testnet account list

```
geth --testnet --networkid=3 account list

geth --testnet --networkid=3 \
  --rpc \ --rpcaddr="localhost" \ --rpcport=8545 \ --rpcapi="db,eth,net,web3,admin,personal"
```

* Open Terminal Window 2

```
geth attach http://127.0.0.1:8545

> personal.unlockAccount(eth.accounts[1])
Unlock account 0xcdea3bfc82cbe46b8a7a8a648eda0969f145468b
Passphrase: 
Error: The method personal_unlockAccount does not exist/is not available
```

* Open Terminal Window 3

```
$ truffle migrate  --network ropsten
Using network 'development'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: authentication needed: password or unlock
```

#### Backtrace

N/A

**Comment by ltfschoen** [comment]
Note: I found an alternative way to deploy it by following this guide, but it would be good to know what I did wrong using Geth: 
https://medium.com/swlh/deploy-smart-contracts-on-ropsten-testnet-through-ethereum-remix-233cd1494b4b

**Comment by Cygnusfear** [comment]
@ltfschoen 
This could've resulted from Geth not being launched with the correct `--rpcapi` flags, if you add `personal` as such `--rpcapi db,eth,net,web3,personal` you should be able to use the `personal` namespace when attaching to geth.

**Comment by BeOleg** [comment]
https://github.com/ethereum/go-ethereum/issues/19422

**Comment by holiman** [comment]
@Cygnusfear answered this correctly, closing
