### ISSUE TITLE
tracing:callTracer not showing nested trace info

### ISSUE THREAD

**Issue by hughsvision** [ethereum/go-ethereum#16408]
I read this wiki:<br>
[Tracing:-Introduction](https://github.com/ethereum/go-ethereum/wiki/Tracing:-Introduction)

```
Although the raw opcode traces we've generated above have their use, this basic way of tracing is problematic in the real world. Having an individual log entry for every single opcode is too low level for most use cases, and will require developers to create additional tools to post-process the traces. Additionally, a full opcode trace can easily go into the hundreds of megabytes, making them very resource intensive to get out of the node and process externally.

To avoid all of the previously mentioned issues, go-ethereum supports running custom JavaScript tracers within the Ethereum node, which have full access to the EVM stack, memory and contract storage. This permits developers to only gather the data they need, and do any processing at the data. Please see the next section for our custom in-node tracers.
```

But I failed to find the **next section for our custom in-node tracers**.

I want something like [parity tracer](https://etherscan.io/vmtrace?txhash=0x1ad00328f8ed6563f966e5f7af8686b54afd7cf2c4a5ffd74ddecb173a28068a&type=parity). Will Geth support it?

**Comment by hupengbuaa** [comment]
Update:<br>
I finally found in [geth 1.8 iceberg](https://blog.ethereum.org/2018/02/14/geth-1-8-iceberg%C2%B9/), showing the use of callTracer. <br>
When performing `debug.traceTransaction(txid,{tracer:"callTracer"})`, it returns nice output:<br>
![](http://7xih5d.com1.z0.glb.clouddn.com/ethereum/evm/part-reverted-internal-call2.jpg)
But it doesn't show deeper/nested call trace, `calls:[{...}]`<br>
Can anyone have idea about it?

**Comment by riordant** [comment]
see https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_traceTransaction

**Comment by Eric-Showers** [comment]
I have run into this issue as well. Have you found a solution yet? I will read through the _callTracer_ source code tomorrow to see what I can find.

**Comment by Eric-Showers** [comment]
Here's a good example [transaction](https://etherscan.io/tx/0x298d439128e4becf7b47d639fb213002de988f0ea029a047918e7309239efe9a) 

If you look at the [parity raw trace](https://etherscan.io/vmtrace?txhash=0x298d439128e4becf7b47d639fb213002de988f0ea029a047918e7309239efe9a&type=parity#raw) you can see that it labels each action with `traceAddress` such that the first `call` action is given

`traceAddress: [0]` 

and subsequent subtraces are labeled

`traceAddress: [0, 0]` and `traceAddress: [0, 1]`

Geth's callTracer however produces the following trace where the subtraces are missing:

>{
  calls: [{
      calls: [{...}, {...}],
      from: "0xd48b633045af65ff636f3c6edd744748351e020d",
      gas: "0xc8a4",
      gasUsed: "0x418d",
      input: "0xf2c7d331...",
      output: "0x",
      to: "0x5a1dbff1a772bc35f53c77509b4dc1624c65e6ec",
      type: "CALL",
      value: "0x470de4df820000"
  }],
  from: "0x8bcc49d93007629991f278120bf79ac0f8a49de8",
  gas: "0x2a6ce",
  gasUsed: "0x225e6",
  input: "0x724fcd4c...",
  output: "0x0000000000000000000000000000000000000000000000000000000000000000",
  time: "289.871973ms",
  to: "0xd48b633045af65ff636f3c6edd744748351e020d",
  type: "CALL",
  value: "0x1bc16d674ec80000"
}

**Comment by karalabe** [comment]
The JavaScript console truncates fields when they are deeper than 2-3 nesting. If you execute the trace from outside, you'll get a full correct dump.

**Comment by Eric-Showers** [comment]
Thanks Peter! I had not tried tracing from the RPC interface before. This solves the issue for me 👍 

It would be helpful to have some more documentation on Geth's tracers to explain subtleties like this (I have only found the [tracing: intro](https://github.com/ethereum/go-ethereum/wiki/Tracing:-Introduction) doc). I am happy to write it out myself but I am not available to do so at the moment. 

If you think that would be helpful then let me know here and I'll work on it in a few weeks from now.

@hupengbuaa it's been a while, can we close this issue?
