### ISSUE TITLE
geth --identity invalid memory address

### ISSUE THREAD

**Issue by githubityu** [ethereum/go-ethereum#16405]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xab4b70]

goroutine 87 [running]:
github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc4201a65c0)
        /build/ethereum-s2a8_D/ethereum-1.8.2+build12774+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:434 +0x330
created by github.com/ethereum/go-ethereum/eth/filters.NewEventSystem
        /build/ethereum-s2a8_D/ethereum-1.8.2+build12774+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:113 +0x104

**Comment by karalabe** [comment]
How did you start geth?

**Comment by dgaviola** [comment]
I'm having the same issue. I'm starting it with the following command:

```
nohup geth --testnet --fast --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303" --cache=1024 --rpc --rpcport "8545" --rpcaddr 10.240.0.7 --rpccorsdomain "*" --nat "any" --rpcapi eth,web3,personal,net &
```

**Comment by dgaviola** [comment]
Not sure what happened, but after some time it started to work
