### ISSUE TITLE
--nodiscover not work 

### ISSUE THREAD

**Issue by gravin** [ethereum/go-ethereum#16409]
geth --datadir G:\sw\Geth\data\remote --networkid 99 --nodiscover --verbosity 5 --fast --bootnodes "enode://28da9010aade761f98d0f44f1a77d176f33b81b2adf70bb0c033e1a1d09309a56a5344dfc2e10252abb7f6fc95411a30b672ea3daaecdfa3347546320e9fb44c@XX.XX.XX.XX:30301" console >>remote.log 2>>&1

i already specify the boot node to find peers, but the log still shows it tried to connect to irrelevant address 

TRACE[03-29|10:25:38] Failed RLPx handshake                    addr=167.99.10.76:44336    conn=inbound err="read tcp 192.168.2.238:30303->167.99.10.76:44336: i/o timeout"
TRACE[03-29|10:25:38] Setting up connection failed             id=0000000000000000 err="read tcp 192.168.2.238:30303->167.99.10.76:44336: i/o timeout"
TRACE[03-29|10:25:39] Failed RLPx handshake                    addr=74.56.208.183:59351   conn=inbound err=EOF
TRACE[03-29|10:25:39] Setting up connection failed             id=0000000000000000 err=EOF
TRACE[03-29|10:25:39] Accepted connection                      addr=74.56.208.183:59408
DEBUG[03-29|10:25:40] FS scan times                            list=0s set=0s diff=0s
TRACE[03-29|10:25:41] Accepted connection                      addr=94.130.141.231:51153
TRACE[03-29|10:25:41] Failed RLPx handshake                    addr=94.130.141.231:51153  conn=inbound err="ecies: invalid message"
TRACE[03-29|10:25:41] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[03-29|10:25:42] Accepted connection                      addr=54.250.190.5:56598
TRACE[03-29|10:25:42] Failed RLPx handshake                    addr=54.250.190.5:56598    conn=inbound err="ecies: invalid message"
TRACE[03-29|10:25:42] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
DEBUG[03-29|10:25:43] FS scan times                            list=0s set=0s diff=0s
TRACE[03-29|10:25:44] Failed RLPx handshake                    addr=74.56.208.183:59408   conn=inbound err=EOF
TRACE[03-29|10:25:44] Setting up connection failed             id=0000000000000000 err=EOF
DEBUG[03-29|10:25:46] FS scan times                            list=0s set=0s diff=0s
DEBUG[03-29|10:25:49] FS scan times                            list=0s set=0s diff=0s
DEBUG[03-29|10:25:50] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[03-29|10:25:52] FS scan times                            list=0s set=0s diff=0s
DEBUG[03-29|10:25:55] FS scan times                            list=0s set=0s diff=0s
TRACE[03-29|10:25:56] Accepted connection                      addr=13.250.220.4:37204
TRACE[03-29|10:25:56] Failed RLPx handshake                    addr=13.250.220.4:37204    conn=inbound err="ecies: invalid message"
TRACE[03-29|10:25:56] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
DEBUG[03-29|10:25:58] FS scan times                            list=0s set=0s diff=0s
DEBUG[03-29|10:26:01] FS scan times                            list=0s set=0s diff=0s
TRACE[03-29|10:26:01] Accepted connection                      addr=222.224.168.165:48350
TRACE[03-29|10:26:01] Failed RLPx handshake                    addr=222.224.168.165:48350 conn=inbound err="ecies: invalid message"
TRACE[03-29|10:26:01] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
DEBUG[03-29|10:26:04] FS scan times                            list=0s set=0s diff=0s
TRACE[03-29|10:26:05] Accepted connection                      addr=159.89.157.189:36712
DEBUG[03-29|10:26:07] FS scan times                            list=0s set=0s diff=0s

**Comment by xinwo** [comment]
same problem here

**Comment by sivachaitanya** [comment]
same problem here, how did you solve this ?

**Comment by holiman** [comment]
The logs say ` conn=inbound` -- it's other clients connecting to you, not the other way around iiuc. If you really want no comms, try `--nodiscover --maxpeers 0` or `maxpeers 2` to allow for a couple of outgoing connections.

**Comment by sivachaitanya** [comment]
@holiman I tried with the command with no luck, as you can see the max peers are 0 and node set to no discover -> nohup geth --rpc --nodiscover --rpcport "8545" --rpccorsdomain "*"  --rpc --rpcaddr "10.0.18.4" --datadir ./datadir --port "30306" --rpcapi "db,eth,net,web3,personal,miner,admin"  --ws --wsaddr "10.0.18.4" --wsorigins "*" --networkid 145510 --verbosity 5 --maxpeers 0 --preload './minewhenneeded.js' &

Log at verbosity 4 - 
TRACE[09-05|09:15:32.447] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:36.006] Accepted connection                      addr=40.76.204.166:1920
TRACE[09-05|09:15:36.007] Failed RLPx handshake                    addr=40.76.204.166:1920    conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:36.008] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:36.695] Accepted connection                      addr=34.207.206.183:43710
TRACE[09-05|09:15:36.696] Failed RLPx handshake                    addr=34.207.206.183:43710  conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:36.696] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:37.868] Accepted connection                      addr=45.77.140.210:35254
TRACE[09-05|09:15:38.136] Accepted connection                      addr=128.1.134.156:54144
TRACE[09-05|09:15:38.138] Failed RLPx handshake                    addr=128.1.134.156:54144   conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:38.138] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
DEBUG[09-05|09:15:38.436] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
TRACE[09-05|09:15:38.627] Accepted connection                      addr=18.214.247.53:28961
TRACE[09-05|09:15:38.628] Failed RLPx handshake                    addr=18.214.247.53:28961   conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:38.629] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:38.646] Accepted connection                      addr=47.52.134.236:51584
TRACE[09-05|09:15:38.648] Failed RLPx handshake                    addr=47.52.134.236:51584   conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:38.648] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:39.370] Accepted connection                      addr=178.62.18.146:44840
TRACE[09-05|09:15:39.372] Failed RLPx handshake                    addr=178.62.18.146:44840   conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:39.372] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:39.487] Accepted connection                      addr=218.223.86.124:55332
TRACE[09-05|09:15:39.506] Failed RLPx handshake                    addr=218.223.86.124:55332  conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:39.506] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:39.773] Accepted connection                      addr=27.154.56.206:51280
TRACE[09-05|09:15:39.774] Failed RLPx handshake                    addr=27.154.56.206:51280   conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:39.774] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:41.898] Accepted connection                      addr=13.57.127.174:40394
TRACE[09-05|09:15:41.899] Failed RLPx handshake                    addr=13.57.127.174:40394   conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:41.899] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:42.841] Failed RLPx handshake                    addr=45.77.140.210:35254   conn=inbound err=EOF
TRACE[09-05|09:15:42.841] Setting up connection failed             id=0000000000000000 err=EOF
TRACE[09-05|09:15:43.109] Accepted connection                      addr=50.238.6.114:37106
TRACE[09-05|09:15:43.114] Failed RLPx handshake                    addr=50.238.6.114:37106    conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:43.114] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:43.132] Accepted connection                      addr=150.109.100.120:44146
TRACE[09-05|09:15:43.133] Failed RLPx handshake                    addr=150.109.100.120:44146 conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:43.133] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:44.167] Accepted connection                      addr=171.88.20.177:36712
TRACE[09-05|09:15:44.169] Failed RLPx handshake                    addr=171.88.20.177:36712   conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:44.169] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:44.283] Accepted connection                      addr=52.204.129.111:63393
TRACE[09-05|09:15:44.284] Failed RLPx handshake                    addr=52.204.129.111:63393  conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:44.284] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:44.456] Accepted connection                      addr=138.197.135.30:34980
TRACE[09-05|09:15:44.457] Failed RLPx handshake                    addr=138.197.135.30:34980  conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:44.457] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:44.643] Accepted connection                      addr=113.119.109.54:58386
TRACE[09-05|09:15:44.645] Failed RLPx handshake                    addr=113.119.109.54:58386  conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:44.645] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:45.175] Accepted connection                      addr=13.125.194.141:21857
TRACE[09-05|09:15:45.175] Failed RLPx handshake                    addr=13.125.194.141:21857  conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:45.176] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:45.984] Accepted connection                      addr=141.55.229.170:39868
TRACE[09-05|09:15:46.333] Accepted connection                      addr=43.245.223.53:46808
TRACE[09-05|09:15:46.383] Accepted connection                      addr=35.227.87.41:6642
TRACE[09-05|09:15:46.385] Failed RLPx handshake                    addr=35.227.87.41:6642     conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:46.385] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:46.438] Accepted connection                      addr=52.221.241.214:54612
TRACE[09-05|09:15:46.451] Failed RLPx handshake                    addr=52.221.241.214:54612  conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:46.451] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:46.783] Accepted connection                      addr=138.197.143.33:58960
TRACE[09-05|09:15:46.787] Failed RLPx handshake                    addr=138.197.143.33:58960  conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:46.787] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:49.669] Accepted connection                      addr=27.110.27.236:55667
TRACE[09-05|09:15:49.671] Failed RLPx handshake                    addr=27.110.27.236:55667   conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:49.671] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:50.860] Failed RLPx handshake                    addr=141.55.229.170:39868  conn=inbound err=EOF
TRACE[09-05|09:15:50.860] Setting up connection failed             id=0000000000000000 err=EOF
TRACE[09-05|09:15:51.102] Failed RLPx handshake                    addr=43.245.223.53:46808   conn=inbound err=EOF
TRACE[09-05|09:15:51.103] Setting up connection failed             id=0000000000000000 err=EOF
TRACE[09-05|09:15:51.298] Accepted connection                      addr=46.101.153.165:47282
TRACE[09-05|09:15:51.301] Failed RLPx handshake                    addr=46.101.153.165:47282  conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:51.301] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:51.611] Accepted connection                      addr=77.234.64.171:48024
TRACE[09-05|09:15:51.613] Failed RLPx handshake                    addr=77.234.64.171:48024   conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:51.613] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:51.677] Accepted connection                      addr=119.253.64.38:47226
TRACE[09-05|09:15:51.679] Failed RLPx handshake                    addr=119.253.64.38:47226   conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:51.679] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:52.003] Accepted connection                      addr=195.29.45.126:50606
TRACE[09-05|09:15:52.004] Failed RLPx handshake                    addr=195.29.45.126:50606   conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:52.004] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:52.255] Accepted connection                      addr=46.101.153.165:47598
TRACE[09-05|09:15:52.255] Accepted connection                      addr=46.101.153.165:47606
TRACE[09-05|09:15:52.257] Failed RLPx handshake                    addr=46.101.153.165:47606  conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:52.257] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|09:15:52.258] Failed RLPx handshake                    addr=46.101.153.165:47598  conn=inbound err="ecies: invalid message"
TRACE[09-05|09:15:52.258] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"

**Comment by sivachaitanya** [comment]
@holiman @karalabe -   ofcourse the --nodiscover is irrelevant here because of #15358

**Comment by ardalanrazavi** [comment]
I have the same issue :/ Any resolution for this.

**Comment by sivachaitanya** [comment]
@ardalanrazavi  check issue #15358 there is resolution suggested there where you modify the udp.go file for encodePacket and deceodePacket functions

**Comment by adamschmideg** [comment]
Inactive for a year
