### ISSUE TITLE
[Proposal] Hardfork and slightly changes of the mining algorythm to stay ASIC resistant

### ISSUE THREAD

**Issue by krtschmr** [ethereum/go-ethereum#16416]
*poison the well*, written in the whitepaper of Ethereum.

Ethereum has been one of the most profitable coins to mine using GPUs. IceAge laimed this inherently and was removed in the last *network update*.

Even tho we had ASIC rumors out of china last year, the recent hashrate runup during the last 4 months while the price is constantly declining, makes Ethereum Mining unprofitable. Small home miners , with regular electricity costs of 0.20$ or more, are forced to turnoff their GPUs and mining rigs, as they can't even make a tiny profit.

Screenshots of Gigahash Miners hit the the surface. While many supsect that these are just MXM GPUs on a PCB (which is just a big GPU Rig, not an ASIC) the rumors of Bitmain produced tons of memory for their upcoming F3 Ethereum ASIC are getting stronger and stronger.

**ASICs would affect market drastically and could even render GPUs obsolete, due to their comparative ineffectiveness.**

We recently saw what happens when Bitmain is *attacking* a coin/network with ASICs. They can (as beeing a monopoly producer) predict hashrates and control the income of their own pockets with individual pricing., depending on market. They do nothing else then first mine into their own wallets, then simply advertise small (very small) batches which gives first-batch-owners a high yield, but then released 15 fold the amount of miners under the table. The Antminer D3+ became, even with cheap electricity, a doorstopper - or for colder regions of this earth, a room heater. It won't yield any profits anymore and with 0.12$ electricity, you still make a dail loss of a dollar (of course related to the crypto price).

Ethereum contributes too much good value to humanity as we can carelessly watch how ASICs are taking over. Crypto belongs to the people, not into the hands of some (chinese or not) businessman.

#### Expected behaviour
Hardfork (network upgrade) to make current ASICs obsolete, slightlyt changing the DaggerHashimoto Algorythm

#### Actual behaviour
ASIC enter the network

#### Backlog

Ethereum will switch to PoS, however, this is still in the future, meanwhile the ASIC take over.

**Comment by holiman** [comment]
This repo is go-ethereum, an ethereum client. So if you want to discuss overall changes to the ethereum specification, here is a better place to start: https://github.com/ethereum/EIPs/issues/958
