### ISSUE TITLE
uint64(len(pool.all)) not equal ( pending's txList len + queue's txList len) ?

### ISSUE THREAD

**Issue by robbinhan** [ethereum/go-ethereum#16412]
#### System information

Geth version: `geth 1.8.2 unstable`
OS & Version: Linux
Commit hash : 478143d69a13103a6809ef41a64b25db8c2438ee

#### Expected behaviour

I think pending map txList length plus queue map txList length equal to all map tx length 

#### Actual behaviour
![image](https://user-images.githubusercontent.com/241873/38123492-e3c165a6-340d-11e8-9495-c6eeed7963bf.png)
pending len is 0,queue len is 4522, but pool.all len is 5120

![image](https://user-images.githubusercontent.com/241873/38123523-0b7e1a8a-340e-11e8-9b91-036ff6f980d0.png)

#### Steps to reproduce the behaviour
I'm doing benchmark, this issue occur when pressure is high. I don't know does it ok?

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
It shouldn't be. That's indicative of a bug somewhere. Could you give some more details about the scenario? Is it mainnet or during benchmark? If benchmark, could you show us how you do it? Would be great if we can reproduce it

**Comment by robbinhan** [comment]
Thanks for your help.

It's not on mainnet, but on private network.

I write a golang script for bechmark. Here is code:

[link to gist](https://gist.github.com/robbinhan/9655c5ca7619e9924bc973201c4cfc71)

I used one account transfer 1 wei to another account 1000 times in one second

**Comment by karalabe** [comment]
Could you try with latest master? There was a bug fixed with tx scheduling in the last release.

**Comment by robbinhan** [comment]
@karalabe OK, I will try it
