### ISSUE TITLE
Block number is always zero with fast syncmode

### ISSUE THREAD

**Issue by giacomolicari** [ethereum/go-ethereum#16411]
Hi there,
After being running a mainnet Geth node for a couple of months, I get a block number which value is always zero when I execute eth_blockNumber rest RPC call.

#### System information
Version: 1.8.1-stable
Git Commit: 1e67410e88d2685bc54611a7c9f75c327b553ccc
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.4
Operating System: linux

#### Expected behaviour
After being running for a couple of months, executing RPC calls to my mainnet Geth node falls into a block number which value is always zero.
I would expect to get the current block number.

#### Actual behaviour
I run geth with the following parameters:

/usr/local/bin/geth --datadir /blockchains/ethereum/mainnet --syncmode fast --cache 2048 --port 30304 --rpc --rpcaddr 0.0.0.0 --rpcport 8645 --ws --wsport=8547

On the syslog I get:
Mar 29 07:35:25 localhost geth[5706]: INFO [03-29|07:35:25] Imported new block headers               count=1    elapsed=10.102ms  number=5341766 hash=33117b…015f6c ignored=

seems like there's an issue on the REST RPC eth_blockNumber method:

curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}' http://localhost:8645
{"jsonrpc":"2.0","id":83,"result":"0x0"}

#### Steps to reproduce the behaviour
Geth command:
/usr/local/bin/geth --datadir /blockchains/ethereum/mainnet --syncmode fast --cache 2048 --port 30304 --rpc --rpcaddr 0.0.0.0 --rpcport 8645 --ws --wsport=8547

Execute eth_blockNumber RPC call:
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}' http://localhost:8645
{"jsonrpc":"2.0","id":83,"result":"0x0"}

**Comment by elie222** [comment]
> A: As explained above, you are not stuck, just finished with the block download phase, waiting for the state download phase to complete too. This latter phase nowadays take a lot longer than just getting the blocks.

So how long does a fast sync actually take nowadays? A day, a week, a month?

We've had nodes fall behind and never being able to catch. Our only solution was to start a fast sync again from scratch. Any recommendations to work around this issue?

Also noted here:
https://medium.com/cryptokitties/why-does-our-database-fall-out-of-sync-c86b1eefa6d

**Comment by lrettig** [comment]
Is there any way to get a sense of the progress of the state download phase? How many state entries are there today? Am I waiting for the `processed` count to reach a certain point?

**Comment by mtahani** [comment]
I installed geth and waited for integrated blockchain (mode fast)
when run eth.syncing return false
I installed Mist and integrated with geth
I can get Balance from Account to Mist but return zero eth.getBalance command in geth console
what????

**Comment by karalabe** [comment]
Mist fell back to Infura while Geth was syncing.

**Comment by L-F-Escobar** [comment]
@karalabe thanks for the awesome explanations!
