### ISSUE TITLE
What is chainID doing?I can't understand this parameter

### ISSUE THREAD

**Issue by Musk66** [ethereum/go-ethereum#16418]
Can anyone tell me what the chainID is ？ I understand it inaccurately.Thanks!

**Comment by RichHorrocks** [comment]
Hi there. Please only use the issue tracker for questions about potential bugs or feature requests. For technical questions the Ethereum Stack Exchange site is better suited.

There are numerous previous questions on this topic on SE. This one is perhaps the best fit: https://ethereum.stackexchange.com/questions/37533/what-is-a-chainid-in-ethereum-how-is-it-different-than-networkid-and-how-is-it

**Comment by Musk66** [comment]
@RichHorrocks Thanks.

**Comment by bitfede** [comment]
Anybody knows why in this specific library they use a value of `v: '0x1c'` ? https://github.com/ethereumjs/ethereumjs-tx/blob/master/docs/classes/transaction.md#v

I could not find any chainID with the value of 28 ( https://github.com/ethereum-lists/chains/tree/master/_data/chains ) .. and if I put values like 1 the code throws me an error.

Any idea on this? Thanks!
