### ISSUE TITLE
Light client and wallet creation on smart device

### ISSUE THREAD

**Issue by dannzor** [ethereum/go-ethereum#16420]
Hi there,

I'm trying to connect an android device to my private network (LAN) using the light (les) protocol. I have managed to do the basic of syncing blocks (https://github.com/ethereum/go-ethereum/wiki/Mobile-Clients:-Libraries-and-Inproc-Ethereum-Nodes) but now I am trying to create a wallet and invoke a smart contract deployed on the private blockchain. I am using the examples from https://medium.com/kin-contributors/web3j-vs-geth-code-comparison-9a228509a70b. I have managed to show the balance of the android device but there are two issues:

1. Even when it is synchronized (i.e `admin.peers` show my device after using `admin.addPeer("enode://ID@localip:port")`, the balance is not updated despite sending some ETH. 
2. If I close the android client and open it again, the program will no longer show the balance. Instead, when debugging, there is an exception `go.Universe$proxyerror: can't fetch trie keys <..hash..>: no suitable peers available`. This happens **only** after I have added the mobile peer once and synched it, else debugging shows no problem. (This means that the light client cannot interact with the blockchain without throwing this exception.)

![lightclientwalletissue](https://user-images.githubusercontent.com/35889839/38163097-ce8f7470-3520-11e8-9ff0-ccaa35ce9c29.png)

Geth version: `1.8.3-stable`
OS & Version: macOS High Sierra 10.13.4

#### Expected behaviour
While connected to a private blockchain be able to create a wallet on a mobile device, return its balance and be able to once again have the opportunity to see the balance (after subsequently adding it as a peer).

#### Actual behaviour
Device is connected to the private blockchain but jumps into an exception instead of showing wallet balance information. Note: public address of the android client is shown without any problem.

#### Steps to reproduce the behaviour
1. Configure private blockchain
2. Create wallet:

```java
            final String keyStorePath = getFilesDir() + "./key";
            final String passphrase = "github";
            KeyStore keyStore = Geth.newKeyStore(keyStorePath, Geth.LightScryptN, Geth.LightScryptP);
            Account account = keyStore.newAccount(passphrase);

            Accounts accounts = keyStore.getAccounts();
            Account firstAccount = accounts.get(0);
            String publicAddress = firstAccount.getAddress().getHex();

            Context context = Geth.newContext();
            Address address = Geth.newAddressFromHex(publicAddress);
            BigInt balance = ethereumClient.getBalanceAt(context, address, -1); //goes to exception after stepping past this line
            textbox.append("ETH balance: " + balance);
```
3. Add android client as a peer
4. Restart the android application
5. Observe that the balance is no longer shown and that the application jumps into an exception

#### Misc error messages
`E/GoLog: WARN [03-31|14:43:44] Stats server unreachable                 err="websocket.Dial ws://<computer_local_ip>:<number_2>/api: unexpected EOF"`
`W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)`

```
E/GoLog: INFO [03-31|14:54:07] Imported new block headers               count=0    elapsed=9.393ms   number=1984 hash=8444da…840491 ignored=192
E/GoLog: INFO [03-31|14:54:07] Imported new block headers               count=0    elapsed=14.847ms  number=2176 hash=19d0ee…092f4a ignored=192
E/GoLog: INFO [03-31|14:54:07] Imported new block headers               count=0    elapsed=9.463ms   number=2368 hash=64e7d1…10b25a ignored=192
E/GoLog: INFO [03-31|14:54:07] Imported new block headers               count=0    elapsed=9.306ms   number=2560 hash=e7077e…366c61 ignored=192
E/GoLog: INFO [03-31|14:54:07] Imported new block headers               count=64   elapsed=184.656ms number=2752 hash=4705bf…2934a0 ignored=128
E/GoLog: ERROR[03-31|14:54:07] Non contiguous header insert             number=2771 hash=289b65…96cd1e parent=a9010c…eb600b prevnumber=2770 prevhash=f3d601…e4fc24
E/GoLog: WARN [03-31|14:54:07] Rolled back headers                      count=64   header=2752->2688 fast=0->0 block=0->0
E/GoLog: WARN [03-31|14:54:07] Synchronisation failed, dropping peer    peer=43cf4de1eef55fae err="retrieved hash chain is invalid"
```

Thanks,
Mobile blockchain enthusiast

**Comment by ligi** [comment]
Thanks for the detailed report! Combining this with the information you gave on gitter: https://gitter.im/ethereum/light-client?at=5abc861327c509a774b5d9df
The following question arises: do you have a node being a light client server "--lightserv" in your private network setup?

**Comment by dannzor** [comment]
Yes, I forgot to add that, my additional flags are:

`geth --datadir <path> --networkid <number_1> --port <number_2>  --maxpeers 10 --rpc --rpcport <number_3> --targetgaslimit <very_high_number> -gasprice <high_number> --lightserv 50 --rpcaddr <computer_local_ip> --rpcapi personal,db,eth,net,web3 console`

**Comment by ligi** [comment]
Ah thanks - kindly invite @zsfelfoldi to have a look

**Comment by dannzor** [comment]
It seems like this error/issue arises from the command `ec.getBalanceAt(context, address, -1)` and `ec.getBlockByNumber(ctx, -1)`, where the culprit is the latest block (-1). Curious if @karalabe managed to get his example from above to work by looking at the last one *and* be able to restart the application without problem. For me, it only works when I change index to 0 (genesis?) but then I have difficulties to actually access the last information (last mined block).

**Comment by ligi** [comment]
What I am doing there: using subscribeNewHead and then and then pass block.number there - does this work for you?

**Comment by dannzor** [comment]
Would you mind showing me what you mean by a code example?

**Comment by ligi** [comment]
sure
```
 ethereumNode.ethereumClient.subscribeNewHead(ethereumContext, object : NewHeadHandler {
                        override fun onNewHead(header: Header) {
                            val balance = ethereumNode.ethereumClient.getBalanceAt(ethereumContext, gethAddress, header.number)
                        }

                        override fun onError(msg: String?) {}

                    }, 16)
```

**Comment by ligi** [comment]
not sure what you mean

**Comment by dannzor** [comment]
Not sure where in your android app this code snippet should be placed to update continuously. Will it show the balance once or will it be updated as you transfer ETH to your mobile wallet?
