### ISSUE TITLE
geth --fast return : out of memory :can not allocate block

### ISSUE THREAD

**Issue by anyouuu** [ethereum/go-ethereum#16421]
Please answer these questions before submitting your issue. Thanks!

#### System details

Version: 1.8.2-stable
Go Version: go1.9.4
OS: linux
uname -sr: Linux 4.13.0-37-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

**Comment by RichHorrocks** [comment]
Hi there. We'll need some more information to get any further on this.
How much memory does your system have? How is the OOM condition manifesting itself? (Panics, core dumps, etc.?) 
Please include the relevant syslogs or console output.

**Comment by 401825317** [comment]
@RichHorrocks 
16G RAM
20 minutes OOM once.
