### ISSUE TITLE
How connect to my geth from Remix? IPC is always \\\.\\pipe\\geth.ipc

### ISSUE THREAD

**Issue by ImmersaRatio** [ethereum/go-ethereum#16428]
I am trying to develop smart contract & dapp with Window 10.

I made my own accounts in local testnet in geth.

And I'd like to make smart contracts and deploy them on the Remix.

so I need to approach to my geth from Remix.

I switch environment option from Javascript Vm/Injected Wev3 to Web3 provider!

then it required "Web3 Provider Endpoint".

Default was http://localhost:8545. (it doesn't work)

I heard that 8545 is RPC port, and localhost is IPC.

when I run my geth, I can check my RPC port.

<< HTTP endpoint opened url = hrrp://0.0.0.0:9797 >>

However, I can't know my geth IP

it is always indicated like below

<< IPC endpoint opened url= \\\.\\pipe\\geth.ipc

I can't refer my IP

How can I control my geth on Remix?

Not possible to connect to the Web3 provider. Make sure the provider is running and a connection is open (via IPC or RPC).

**Comment by suspended** [comment]
What command are you using to run geth?

**Comment by ImmersaRatio** [comment]
I am using these


geth --networkid 7979 --nodiscover --port "30303" --datadir \Users\Doo\Desktop\data_testnet --rpc --rpcaddr "0.0.0.0" --rpcport 9797 --rpccorsdomain "*" --rpcapi "admin,db,eth,debug,miner,net,personal,web3" --nat "any" console


geth --dev --networkid 2525 --nodiscover --port 3030 --datadir \Users\Doo\Desktop\data_testnet --rpc --rpcaddr 125.191.63.110 --rpcport "8552" --rpcapi "admin,db,eth,debug,miner,net,shh,,txpool,personal,web3" console


geth --networkid 7979 --nodiscover --maxpeers 0 --datadir \Users\Doo\Desktop\data_testnet --mine --minerthreads 1 --rpc --rpcaddr "0.0.0.0" --rpcport 9797 --rpccorsdomain "*" --rpcapi "admin,db,eth,debug,miner,net,personal,web3" --unlock 0,1 --password \Users\Doo\Desktop\data_testnet\passwd --verbosity 6 console


geth --networkid 7979 --nodiscover --maxpeers 0 --datadir \Users\Doo\Desktop\data_testnet --mine --minerthreads 1 --rpc --rpcaddr "0.0.0.0" --rpcport 9797 --rpccorsdomain "*" --rpcapi "admin,db,eth,debug,miner,net,personal,web3" --unlock 0,1 --password pass0 --verbosity 6 console

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
