### ISSUE TITLE
HD Wallet implementation

### ISSUE THREAD

**Issue by sumitsahu28** [ethereum/go-ethereum#16429]
Could not find a way to generate multiple private key from a master key having derivation path for it's child keys

**Comment by RichHorrocks** [comment]
Hi there. Please keep the issue tracker clear so it can be used to track real issues and feature requests.

For technical questions, Stack Exchange is better: https://ethereum.stackexchange.com/
(This previous question would be a good place to start: https://ethereum.stackexchange.com/questions/1094/what-hierarchical-deterministic-hd-wallets-are-available-for-ethereum)

**Comment by ligi** [comment]
@RichHorrocks Was also thinking this is a "question only" at first and about to close it - but we could also see this as a feature request ;-)
Not sure though if this feature should be in scope of go-ethereum though ..
That said some of the work towards this is coming via https://github.com/ethereum/go-ethereum/pull/15925 by @Arachnid

**Comment by RichHorrocks** [comment]
@ligi - Aha, good point. When I read it I wasn't thinking in the scope of the Geth toolset (rather, "Tell me where to find an HD wallet implementation") - I like the potential feature request better. :-)
