### ISSUE TITLE
Fatal: Failed to create the protocol stack: mkdir <HOME>: The system cannot find the path specified.

### ISSUE THREAD

**Issue by cyberyarek** [ethereum/go-ethereum#16437]
If you are on Windows and happen to have an environment variable HOME to set to something else than the default then geth will give you the above error.

The solution is to create $HOME\AppData and $HOME\AppData\Roaming folders.

Good luck.

**Comment by cyberyarek** [comment]
Technically this is an error on Windows: geth should use USERPROFILE instead of HOME.

**Comment by fjl** [comment]
Related PR: https://github.com/ethereum/go-ethereum/pull/17786
