### ISSUE TITLE
Implement eth_getReward RPC call

### ISSUE THREAD

**Issue by ppratscher** [ethereum/go-ethereum#1644]
Currently there is no way to query the block reward for a given address and block. If one want's to know how much reward he got out of the block the individual rewards (miner, tx fees & uncles) have to be calculated manually which is cumbersome and error prone.

It would be good to have the following api call:
eth_getReward(address, block)

It should return the amount of Wei rewarded to this address from the block or 0 if the address received 0 rewards.

**Comment by obscuren** [comment]
I do not see why this needs to be implemented on the node's side. This can easily be solved by iterating over the transactions and receipts and do a `gasUsed * price`

**Comment by ppratscher** [comment]
yes, that is simple, but the uncle reward calculation is much more difficult. also if the uncle reward and/or block reward is changed one would need to update the client side code. I think it would be better this would be implemented in the node itself to ensure clients use correct values.

**Comment by obscuren** [comment]
I disagree. You are saying "implement feature X from library Y because X might change". 

Also uncles are the easy to calculate. 

Also the values won't change for the foreseeable future, if ever.
