### ISSUE TITLE
debug_traceTransaction — JavaScript-based tracing (missing `log` fields)

### ISSUE THREAD

**Issue by alexprut** [ethereum/go-ethereum#16448]
The `JavaScript-based tracing` option functionality within the `debug_traceTransaction` call is not behaving as expected and as documented in https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_tracetransaction.

#### System information

Geth version: `Geth/v1.8.3-stable-329ac18e/linux-amd64/go1.10`
OS & Version: Linux

#### Expected behaviour

When using the `JavaScript-based tracing` option in the `rpc` call most of the `log` fields of the `step` function are `undefined`. More precisely the only fields visible are:
* `op`: Object, an OpCode object representing the current opcode
* `contract`: 
* `memory`: Object, a structure representing the contract's memory space
* `stack`: array[big.Int], the EVM execution stack

Instead the missing and `undefined` fields are:
* `pc`: Number, the current program counter
* `gas`: Number, the amount of gas remaining
* `gasPrice`: Number, the cost in wei of each unit of gas
* `depth`: The execution depth
* `account`: The address of the account executing the current operation
* `err`: If an error occured, information about the error

If using the `debug_traceTransaction` method without the `JavaScript-based tracing` it is behaving as expected.

#### Steps to reproduce the behaviour
The `JavaScript-based tracing` code used is:
```
{
   logs: [],
   extractStack: function (stack, op) {
       var extract = [];
       for (var i = 0; i < stack.length(); i++) {
           extract.push(stack.peek(i));
       }
       return extract;
   },
   step: function (log, db) {
       this.logs.push({
           op: log.op.toString(),
           stack: this.extractStack(log.stack),
           depth: log.depth,
           error: log.err
       });
   },
   fault: function() {},
   result: function () {
       return {structLogs: this.logs};
   }
}
```

The raw `rpc` call with the `JavaScript-based tracing` option:
```
curl --data '{"jssonrpc":"2.0","method":"debug_traceTransaction", "id": 1, "params":["0x24856e50b82728948a9b1b55907d4c2d13c22b1999eba32eb3f131d92a0fd8ca", {"disableMemory": true, "disableStorage": true, "tracer": "{logs: [],extractStack: function (stack, op) {var extract = [];for (var i = 0; i < stack.length(); i++) {extract.push(stack.peek(i));}return extract;},step: function (log, db) {this.logs.push({op: log.op.toString(),stack: this.extractStack(log.stack),depth: log.depth,error: log.err});},fault: function() {},result: function () {return {structLogs: this.logs};}}"}]}' -H "Content-Type: application/json" -X POST  localhost:8545
```

The raw `rpc` call without the `JavaScript-based tracing` option:
```
curl --data '{"jssonrpc":"2.0","method":"debug_traceTransaction", "id": 1, "params":["0x24856e50b82728948a9b1b55907d4c2d13c22b1999eba32eb3f131d92a0fd8ca", {"disableMemory": true, "disableStorage": true}]}' -H "Content-Type: application/json" -X POST  eth-localhost:8545
```

#### Backtrace
Output of the `rpc` call: `debug_traceTransaction` (with options: `disableStorage`, `disableMemory`, `JavaScript-based tracing`)
https://gist.github.com/alexprut/509e3f46dd302acd738dc3a89bc3588b

Output of the `rpc` call: `debug_traceTransaction` (with options: `disableStorage`, `disableMemory`)
https://gist.github.com/alexprut/002979fdb58e9bc9bcae348744ae61d7

**Comment by holiman** [comment]
I'm not sure that the docs are up to date -- I know @karalabe has been working on writing new documentation, and I don't know if that is released... ?

**Comment by holiman** [comment]
Based on https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/tracer.go#L443 , try `log.getDepth()` instead. IIRC, Peter changed the accessors to be functions, which made everything quite a lot faster.

**Comment by alexprut** [comment]
Thanks @holiman it works 👍 
How can I update the docs?
 
The new documentation should be updated as follows:
* `log.pc` → `log.getPC()`
* `log.gas` → `log.getGas()`
* `log.gasPrice` → `log.getCost()`
* `log.depth` → `log.getDepth()`
* `log.err` → `log.getError()`

There is another smaller issue:
The `stack` values returned with the `JavaScript-based tracing` option are represented as `Integer String` instead of a `Hexadecimal String`.

Example:
https://gist.github.com/alexprut/509e3f46dd302acd738dc3a89bc3588b#file-traces-js-txt-L15
https://gist.github.com/alexprut/002979fdb58e9bc9bcae348744ae61d7#file-traces-txt-L26

`"96"` and `"0000000000000000000000000000000000000000000000000000000000000060"` is the same value but represented with different encoding.

**Comment by samadsidd** [comment]
@alexprut 
How can i get the account as mentioned in the docs
log.account is undefined
