### ISSUE TITLE
no suitable peers available in light mode

### ISSUE THREAD

**Issue by shipunyc** [ethereum/go-ethereum#16441]
I ran geth in light mode:

go-ethereum/build/bin/geth --ws --wsaddr "127.0.0.1" --wsport "8546" --wsorigins="*" --wsapi="db,eth,net,web3,personal,web3"  --light console 2> ./eth.log

Then, when I do eth.getBalance, it's always:

Error: no suitable peers available
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

-----------------------------------------

Geth version: 1.8.4-unstable
OS & Version: linux
Commit hash : 5909482fb55095b58ff3f9d8207a4daa69defe26

**Comment by shipunyc** [comment]
I tried: 

--syncmode "light"


It's the same.

**Comment by MeadeRobert** [comment]
I'm having the same problem. Anybody have a solution?

**Comment by shipunyc** [comment]
I think it's just that you need to wait.

The syncing takes about 20 minutes.

**Comment by shipunyc** [comment]
This time I tried for 3 days. Still can't connect to any peers.

Having a working light wallet please... Am I asking too much?

**Comment by n0pn0pn0p** [comment]
maybe you should --fast when you run geth.
This means fast sync, but do not download the whole block.

**Comment by karalabe** [comment]
If you're not connected to a light server, data retrievals won't work. The only solution is to wait until a server serves you.

**Comment by joeytwiddle** [comment]
Although light sometimes worked without opening the ports to the public, I did eventually get this error. When I opened the ports, the error went away.

Specifically I opened port 30303 TCP and also port 30303 UDP for node discovery.

**Comment by asafd11** [comment]
light stop working

**Comment by meena-erian** [comment]
I'm facing the same problem. Did anybody find any solution? Does deleting the node and starting over with the syncing solve the problem?

**Comment by qraxiss** [comment]
```
INFO [02-19|16:49:39.947] Looking for peers                        peercount=2 tried=2  static=0
INFO [02-19|16:49:49.962] Looking for peers                        peercount=2 tried=5  static=0
INFO [02-19|16:50:00.933] Looking for peers                        peercount=2 tried=7  static=0
INFO [02-19|16:50:10.951] Looking for peers                        peercount=2 tried=2  static=0
INFO [02-19|16:50:21.117] Looking for peers                        peercount=2 tried=1  static=0
INFO [02-19|16:50:31.948] Looking for peers                        peercount=2 tried=9  static=0
INFO [02-19|16:50:42.000] Looking for peers                        peercount=2 tried=2  static=0
INFO [02-19|16:50:53.022] Looking for peers                        peercount=2 tried=7  static=0
INFO [02-19|16:51:05.008] Looking for peers                        peercount=2 tried=4  static=0
INFO [02-19|16:51:15.060] Looking for peers                        peercount=2 tried=5  static=0
INFO [02-19|16:51:25.067] Looking for peers                        peercount=2 tried=4  static=0
INFO [02-19|16:51:35.152] Looking for peers                        peercount=2 tried=5  static=0
INFO [02-19|16:51:47.088] Looking for peers                        peercount=2 tried=5  static=0
INFO [02-19|16:51:57.105] Looking for peers                        peercount=2 tried=5  static=0
INFO [02-19|16:52:07.179] Looking for peers                        peercount=2 tried=4  static=0
INFO [02-19|16:52:18.124] Looking for peers                        peercount=2 tried=2  static=0
INFO [02-19|16:52:29.128] Looking for peers                        peercount=2 tried=6  static=0
INFO [02-19|16:52:39.250] Looking for peers                        peercount=2 tried=6  static=0
INFO [02-19|16:52:51.113] Looking for peers                        peercount=2 tried=5  static=0
```

Any solitions? I have same problem. And my logs just saying `Looking for peers`
