### ISSUE TITLE
Release 1.8.3 mostly missing from Ubuntu PPA

### ISSUE THREAD

**Issue by veox** [ethereum/go-ethereum#16447]
(issue template doesn't apply)

It seems that the "Geth CI" build job [failed for anything but Trusty](https://launchpad.net/~ethereum/+archive/ubuntu/ethereum).

**Comment by fjl** [comment]
We're aware of this issue but can't fix it until 1.8.4 comes along. Resolving this issue requires changes to travis.yml. The changes are on the master branch but we cannot re-run the 'tag build' that was supposed to push 1.8.3 to launchpad with those changes.
