### ISSUE TITLE
geth eth_sendTransaction: txid returned successfully but not broadcast

### ISSUE THREAD

**Issue by CockyCat** [ethereum/go-ethereum#16463]
Hi ,
I use eth_sendTransaction to send a transaction that can successfully return txid, but querying this txid via https://etherscan.io/ is not found at all, the amount has not changed, there is no broadcast at all. I was plagued by this problem for a long time.

Detail:

![111](https://user-images.githubusercontent.com/4004100/38466987-55c907d2-3b64-11e8-8002-ab062031f76c.png)
![22](https://user-images.githubusercontent.com/4004100/38466993-75450200-3b64-11e8-8c2d-007f30b8a41c.png)

#### System information

Geth version: ` 1.8.1-stable-1e67410e`
OS & Version: Ubuntu 6.04
Commit hash : (if `develop`)

#### Expected behaviour
Can be broadcasted on the entire network

#### Actual behaviour
Not broadcast to the entire network

#### Steps to reproduce the behaviour
1、Curl request
2、Return txid
3、Txid cannot be found in the block browser
#### Backtrace

````
[backtrace]
````

**Comment by CockyCat** [comment]
???

**Comment by qq601432505** [comment]
I have encountered the same situation as you. Is there a way to solve it?

**Comment by Jackpot1135** [comment]
Looks like the blocks finally synced now IAM trying to open up the gates.

**Comment by CockyCat** [comment]
No, guys.   it's still unresolve.

**Comment by mrsantran** [comment]
Same issue on light mode

**Comment by zsabbasi** [comment]
We need a resolution fast, any ideas anyone. None of our Geth transactions are working on Rinkeby from any of the clients. Tx are being lost even though we get the TX Ids from eth.sendTransaction command. Never had this before. 1.7 or 1.8 same problem.

**Comment by pearsonbee** [comment]
same problem, what is the result of this issue?
