### ISSUE TITLE
Fatal Error:Not enough storage is available

### ISSUE THREAD

**Issue by NeyrMa** [ethereum/go-ethereum#16462]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version` 1.8.3
OS & Version: Windows
Commit hash : (if `develop`)

#### Expected behaviour
when I run "startnode.cmd", it should set up a private eth dataset.

#### Actual behaviour
I came up to this error:
ERROR[04-08|11:59:43] Failed to generate mapped ethash dataset epoch=0 err="MapViewOfFile: Not enough storage is available to process this command."
runtime: out of memory: cannot allocate 2147483648-byte block (2822389760 in use)
fatal error: out of memory

#### Steps to reproduce the behaviour
startnode.cmd:geth --networkid 4224 --mine --minerthreads 2 --datadir "." --nodiscover --rpc --rpcport "8545" --port "30303" --rpccorsdomain "*" --nat "any" --rpcapi eth,web3,personal,net --unlock 0 --password ./password.sec

#### Backtrace

````
[backtrace]
````

**Comment by RichHorrocks** [comment]
Hi there. 

> runtime: out of memory: cannot allocate 2147483648-byte block (2822389760 in use)
> fatal error: out of memory

The error message is saying you don't have enough memory (RAM) available. The 2147483648 bytes are required when generating the DAG needed for mining. Either upgrade the memory on this machine, or don't use it as a mining node.

**Comment by chimdyke82** [comment]
I have similar issue. I have had to upgrade my RAM from $GB to 20GB.......issue remains. Any suggestions?

**Comment by SalvinKajar** [comment]
This issue is because you may have installed 32 bit geth installer by mistake, due to which it can only access 2 GB of physical memory and it will find some of the blocks already occupied. So uninstall geth and reinstall the 64 bit version. This solves the problem.
