### ISSUE TITLE
could you recommend computer hardware configuration for a node?

### ISSUE THREAD

**Issue by gravin** [ethereum/go-ethereum#16465]
i used 8G RAM with 200GB HHD, it take days to sync with the mainnet.
how could i make it much faster?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
