### ISSUE TITLE
Can i broadcast a transaction by my other geth-core ?

### ISSUE THREAD

**Issue by xuzhiping7** [ethereum/go-ethereum#16466]
Hello ,

I have serveral geth-core running on different regions cloud-server, one running on my local computer.

I don't know why my geth-core(local computer) can't keep up the newest block , it always delay about 10w block. but my geth-core on cloud-server is sync the newest block.

Sometime i want to send a transaction from my local computer , it will return the tips about balance not enought (the balance had not sync to the newest block ).

So, how can i broadcast the transaction by my other cloud-server using json-rpc ? i don't want to send my keystore  to my cloud-server .

Thx.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by ligi** [comment]
Thanks for asking over there - here the link: https://ethereum.stackexchange.com/questions/45129/can-i-broadcast-a-transaction-by-my-other-geth-core
