### ISSUE TITLE
How to Decoding transaction input data

### ISSUE THREAD

**Issue by githubityu** [ethereum/go-ethereum#16469]
https://www.queryoverflow.gdn/query/decoding-transaction-input-data-with-web3j-java-29_31351.html

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
