### ISSUE TITLE
contract.new() doesn't work

### ISSUE THREAD

**Issue by gustavkkk** [ethereum/go-ethereum#16473]
contract.new() doesn't work
I tried almost any tutorial, but nothing works when i tried contract.new().
I already unlocked the account.
#### System information
Geth version: geth/xenial,now 1.8.2+build12774+xenial amd64 [installed]
                      geth-unstable/xenial 1.8.4+build13066+xenial amd64
OS & Version: Ubuntu16.04 64bit

#### ERROR REPORT
> mycontract = eth.contract(abi); 
> contract_instance = mycontract.new({data: compiled, gas: eth.estimateGas({data: compiled}), from: eth.coinbase}, function(e, contract){
             if(!e){
               if(!contract.address){
                  console.log("Contract transaction send: Transaction Hash: "+contract.transactionHash+" waiting to be mined...");
               }else{
                  console.log("Contract mined! Address: "+contract.address);
                  console.log(contract);
               }
             }else{
               console.log(e)
             }
             })
TypeError: 'filter' is not a function
    at web3.js:2830:12
    at web3.js:3001:21
    at <anonymous>:1:21
###################
> contract_instance = mycontract.at(contract_addr)
TypeError: 'filter' is not a function
    at web3.js:2849:5
    at web3.js:3060:5
    at <anonymous>:1:21
###################

How should I solve this? Thanks in advance

**Comment by jfblockchain** [comment]
Instead of "eth.contract(abi);" try using "web3.eth.contract(abi);" ?

**Comment by RobinBobin** [comment]
Hi there!

As stated [here](https://github.com/trufflesuite/truffle-artifactor/issues/9), your abi needs to be a Javascript Array rather than a string.

**Comment by Explainaur** [comment]
@RobinBobin bro you are right

**Comment by adamschmideg** [comment]
The issues seems to be solved
