### ISSUE TITLE
why i keep getting invalid neighbour/Bad packet from error messages when connecting to ropsten or rinkley??

### ISSUE THREAD

**Issue by gravin** [ethereum/go-ethereum#16472]
error message:

DEBUG[04-10|11:17:12] invalid neighbour (87.161.186.34) from 03e13ab322f8e318@61.239.42.115:30303: metadata mismatch: got {87.161.186.34 49153 30303 36e9bbe2469f2666120c6be5acd6eb4dd56c051bef06b2db2b30a26a49049498f5d15d7c848bdc91a8bab8ad4137af73201ec6f83a71994ca827b39b14beadd3}, want enode://36e9bbe2469f2666120c6be5acd6eb4dd56c051bef06b2db2b30a26a49049498f5d15d7c848bdc91a8bab8ad4137af73201ec6f83a71994ca827b39b14beadd3@87.161.186.34:49153 
DEBUG[04-10|11:17:12] invalid neighbour (69.148.5.18) from 5667205824894d46@72.52.132.217:30303: metadata mismatch: got {69.148.5.18 36360 36360 781580d39059847ba9f1d5cca6f089c00cf63a16ef9eeffc0d3a3db8957097c63231b3e73572249524261aa745abbd5ab5f39862bada1715f983f7370d0075f8}, want enode://781580d39059847ba9f1d5cca6f089c00cf63a16ef9eeffc0d3a3db8957097c63231b3e73572249524261aa745abbd5ab5f39862bada1715f983f7370d0075f8@69.148.5.18:30303?discport=36360 
DEBUG[04-10|11:17:12] invalid neighbour (13.90.215.238) from 67f74fd9d02ec458@173.212.209.171:30303: low port 
DEBUG[04-10|11:17:13] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[04-10|11:17:13] Dial timeout                             lesaddr=86013e02e16728ca742c059b3837706b0d2420f2a8aa38ccf3fc2b13bdf54716370d08598bd461649066966e4e4c752c12aecbfaf3d0021dc6c9d673e6c79b3f@174.138.66.154:30303
DEBUG[04-10|11:17:13] invalid neighbour (172.17.0.1) from 1ce4bc883dbd3ce3@193.169.244.188:30303: LAN address from WAN host 
DEBUG[04-10|11:17:13] Bad packet from 47.94.236.241:30305: bad prefix 
DEBUG[04-10|11:17:15] invalid neighbour (87.161.186.34) from 03e13ab322f8e318@61.239.42.115:30303: metadata mismatch: got {87.161.186.34 49153 30303 36e9bbe2469f2666120c6be5acd6eb4dd56c051bef06b2db2b30a26a49049498f5d15d7c848bdc91a8bab8ad4137af73201ec6f83a71994ca827b39b14beadd3}, want enode://36e9bbe2469f2666120c6be5acd6eb4dd56c051bef06b2db2b30a26a49049498f5d15d7c848bdc91a8bab8ad4137af73201ec6f83a71994ca827b39b14beadd3@87.161.186.34:49153 
DEBUG[04-10|11:17:15] invalid neighbour (87.161.186.34) from 03e13ab322f8e318@61.239.42.115:30303: metadata mismatch: got {87.161.186.34 49153 30303 36e9bbe2469f2666120c6be5acd6eb4dd56c051bef06b2db2b30a26a49049498f5d15d7c848bdc91a8bab8ad4137af73201ec6f83a71994ca827b39b14beadd3}, want enode://36e9bbe2469f2666120c6be5acd6eb4dd56c051bef06b2db2b30a26a49049498f5d15d7c848bdc91a8bab8ad4137af73201ec6f83a71994ca827b39b14beadd3@87.161.186.34:49153 
DEBUG[04-10|11:17:15] invalid neighbour (69.148.5.18) from 5667205824894d46@72.52.132.217:30303: metadata mismatch: got {69.148.5.18 36360 36360 781580d39059847ba9f1d5cca6f089c00cf63a16ef9eeffc0d3a3db8957097c63231b3e73572249524261aa745abbd5ab5f39862bada1715f983f7370d0075f8}, want enode://781580d39059847ba9f1d5cca6f089c00cf63a16ef9eeffc0d3a3db8957097c63231b3e73572249524261aa745abbd5ab5f39862bada1715f983f7370d0075f8@69.148.5.18:30303?discport=36360 
DEBUG[04-10|11:17:15] invalid neighbour (87.161.186.34) from 03e13ab322f8e318@61.239.42.115:30303: metadata mismatch: got {87.161.186.34 49153 30303 36e9bbe2469f2666120c6be5acd6eb4dd56c051bef06b2db2b30a26a49049498f5d15d7c848bdc91a8bab8ad4137af73201ec6f83a71994ca827b39b14beadd3}, want enode://36e9bbe2469f2666120c6be5acd6eb4dd56c051bef06b2db2b30a26a49049498f5d15d7c848bdc91a8bab8ad4137af73201ec6f83a71994ca827b39b14beadd3@87.161.186.34:49153 
DEBUG[04-10|11:17:15] invalid neighbour (99.231.26.40) from 0d0c9bd08d0ad49f@116.42.21.109:30303: metadata mismatch: got {99.231.26.40 40746 40746 523e45d6d33ba775dd98bb4528f8621f5d71ccf4a84a36b341fc999b410c15e4d9be610c0b4970ea529f36f3ff4a59682424164a995b02c11378d9fd8b51368d}, want enode://523e45d6d33ba775dd98bb4528f8621f5d71ccf4a84a36b341fc999b410c15e4d9be610c0b4970ea529f36f3ff4a59682424164a995b02c11378d9fd8b51368d@99.231.26.40:30303?discport=40746 
DEBUG[04-10|11:17:16] Dial timeout                             lesaddr=058797032eb4a2b2068c2ee2f86b674599c14571c2422bd71bdfb4afe89faf15803e1afc481aa80c3a59839f6bda9d07e17a717dc7a2a2d75f4153d3c99918cf@35.198.145.125:30313

and due to i used --light option, is there any restrictions on this option? can i deploy and call contract ?

**Comment by dinu88** [comment]
same issue here, any thoughts?
