### ISSUE TITLE
Missing trie node when reading contract data on fast sync node at specific block

### ISSUE THREAD

**Issue by Deams51** [ethereum/go-ethereum#16471]
#### System information
Geth version: v1.8.3-stable-329ac18e/linux-amd64/go1.10
OS & Version: Ubuntu 16.04.3 LTS

#### Expected behavior
Attempting to read token decimal from a valid contract at address "0x99ea4db9ee77acd40b119bd1dc4e33e1c070b80d" on specific block number via web3 should not fail.

#### Actual behavior
Instead, recently the node started to return 
`Error: Returned error: missing trie node b03d68ac51042467d7637d4ef9e1c52370abc410f263166965cb1e280b1f6d17 (path )`

#### Additional information
The node has been online for 9 weeks without an issue, and just suddenly started failing.
Restarting the node seemed to have pushed back the sync 100k blocks, and the error still persists.

##### Example web3 call returning an error: 
`tokenContract.methods.decimals().call(null, blockNumber)`
where blockNumber is the current block number. 
##### Example web3 call **not** returning an error: 
`tokenContract.methods.decimals().call()`

**Comment by karalabe** [comment]
Are you sure you're not trying to access blocks older than 128? Geth 1.8.0 introduces state an initial state pruning, so anything older than that will be deleted.

**Comment by Deams51** [comment]
Thanks @karalabe I missed this part of the release note.
Closing the issue.

**Comment by Deams51** [comment]
@karalabe launching a new node from scratch in fast with `--gcmode=archive` still produce the same issue.

**Comment by Deams51** [comment]
Alright, so if I understand it right, the only way to make it happen is to run a full archive node which is taking roughly 3weeks for some people to sync. Would appreciate if someone can confirm. :)

**Comment by holiman** [comment]
No, I don't think that is quite true. For `call`, that might be the case, but if you use `traceTransaction`, it's possible to tell geth to replay the necessary blocks from a previous pruning-point, until you get the desired state. This is a very intensive operation, though. @karalabe do we have any docs on how that works?
