### ISSUE TITLE
eth_pendingTransactions returns differently formatted data than found in eth_getBlockByNumber 

### ISSUE THREAD

**Issue by wildbunny** [ethereum/go-ethereum#1648]
eth_pendingTransactions returns:

{"To": "0x70fd7d3388a4ec1b1d93d8af95079b1d450457c4","From": "0xbf6e563a4f152fe548b5aa781e67bd8b0408490c","Nonce": "9","Value": "560000000000000000","Data": "0x00000301000703010080d1f86fe0","GasLimit": "90000","GasPrice": "1197496750083"}

whereas eth_getBlockByNumber returns:

{
    blockHash: '0x5f25538aa0020aead93c6d4e9a56639b7a6f41d6650a64f20681082dc0c67d63',
    blockNumber: 408,
    from: '0x70fd7d3388a4ec1b1d93d8af95079b1d450457c4',
    gas: 90000,
    gasPrice: '1109254023733',
    hash: '0x048e0736f2e43bba6da3e3a9f123b83ea4f2588ad3b6054deda33513a658c8d2',
    input: '0x',
    nonce: 4,
    to: '0xbf6e563a4f152fe548b5aa781e67bd8b0408490c',
    transactionIndex: 0,
    value: '500000000000000000'}

So the fields are named differently due to caps, and input and data refer to the same thing under different names.

**Comment by obscuren** [comment]
`eth_pendingTransactions` is not part of the official RPC spec. If anything the method it self should be removed.
