### ISSUE TITLE
Can I get a one-to-many(many-to-many) transaction method?

### ISSUE THREAD

**Issue by J-Liu** [ethereum/go-ethereum#16483]
Hi all,

I'm sorry that I know this is not a `develop` issue, technically.  But I do wanna get some authoritative answer, or help will be wonderful.

As we know, geth send eth by `sendTransaction`, it has `from` `to` and `amount`, it is an one-to-one transaction.
Can I get a way of one-to-many(many-to-many) transaction like `sendmany` in bitcoin-core?  As bitcoin-core can draw bitcoin form all address in the local wallet automatically, it is actually a many-to-many transaction.
Just for saving miner-fee when I have huge transactions.

Thanks.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
