### ISSUE TITLE
Abi.bind should use EIP155Signer (not HomesteadSigner) for new transactions.

### ISSUE THREAD

**Issue by libreoscar** [ethereum/go-ethereum#16484]
Currently, Abi.bind is [hardcoded to use HomesteadSigner](https://github.com/ethereum/go-ethereum/blob/2e247705cd27e919e806f29ff2adcd57c163b1ac/accounts/abi/bind/base.go#L237). Should not we use the newer EIP155Signer for new txs?

**Comment by karalabe** [comment]
Indeed, we should.

**Comment by jwasinger** [comment]
@karalabe if no one is currently working on this, I would like to make an attempt at a fix.

**Comment by Hasbullah110782** [comment]
IM sorry my friends
