### ISSUE TITLE
when call keystore.EncryptKey need used 250MB memory ?

### ISSUE THREAD

**Issue by janke99** [ethereum/go-ethereum#16493]
Hi ,
     I'm trying to develop a library for Android& iOS by gomobile, i find when i call keystore.EncryptKey it will use about 250MB memory , is there any problem for it ? how can i do it ,thank you!

example:
keyjson, err := keystore.EncryptKey(key, password, keystore.StandardScryptN, keystore.StandardScryptP)

**Comment by ligi** [comment]
you must use LightScryptN,LightScryptP and not StandardScryptN,StandardScryptP on mobile

**Comment by karalabe** [comment]
Please see https://github.com/ethereum/go-ethereum/wiki/Mobile:-Account-management#encrypted-keystores .
