### ISSUE TITLE
Unexpected identifier error when importing wallet

### ISSUE THREAD

**Issue by birdpizza** [ethereum/go-ethereum#1650]
I've successfully set up an account. As a next step I tried importing my pre-sale wallet using the console command form...

geth wallet import /Users/myPCusername/Documents/xxxx/Ethereum/ethereum-wallet-longstringoflettersandnumbers.json

This gave me the following error:
(anonymous): Line 1:6 Unexpected identifier (and 1 more errors)

I'm not an experienced programmer at all, and I am not sure what this meant. Suggestions appreciated - thanks.

**Comment by obscuren** [comment]
Just so I understand you correctly; do you execute `geth wallet import /Users/myPCusername/Documents/xxxx/Ethereum/ethereum-wallet-longstringoflettersandnumbers.json` from your OS shell command line or do you execute this from `geth console` command line?

**Comment by birdpizza** [comment]
...the geth console command line...

**Comment by tgerring** [comment]
You wouldn't want to call geth from inside geth. Instead, call it from your command line.
