### ISSUE TITLE
cmd/geth: Ctrl-C in combination with js causes unclean shutdown

### ISSUE THREAD

**Issue by rustyx** [ethereum/go-ethereum#16506]
#### System information

Geth version: **1.8.3-stable**
OS & Version: **Windows 10 x64**

#### Expected behaviour

Clean shutdown when pressing Ctrl-C while a script is running.

#### Actual behaviour

Unclean shutdown.

#### Steps to reproduce the behaviour

1. Create a file `test.js` with the following contents:
`eth.filter("latest", function() {});`
2. Start `geth js test.js`
3. Once started, press `Ctrl+C`.
4. Geth is killed instead of gracefully shutting down.

**Comment by rustyx** [comment]
Excellent! Thanks for nothing.

**Comment by fjl** [comment]
Sorry, that bot can be over-eager sometimes.

**Comment by holiman** [comment]
Fwiw, I cannot repro this on linux on master (works as it should)

**Comment by rustyx** [comment]
Just tested with 1.8.27 on Windows, the issue is still there. With `geth --preload test.js` all is fine, but with `geth js test.js` Ctrl-C causes immediate termination/unclean shutdown.
