### ISSUE TITLE
geth in private network, Out of Memory even after using up 8 GB RAM + 100 GB swapfile

### ISSUE THREAD

**Issue by lbrep** [ethereum/go-ethereum#16501]
Geth version: `1.7.3-stable-4bb3c89d`
OS & Version: Linux - Ubuntu 16.04 
Network : `Private network`
No. of Peers `none`,
Geth Command used to start: `/geth --datadir ./cdata2/ --port 30304 --networkid 19114 --rpc --rpcport 8546 --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "web3,eth,personal,net" console`

**ISSUE STATEMENT:**
 It was running fine until the block height  reached around 2,81,000. But now suddenly the memory usage of my server instance has shooted up TOO High and the geth process gets killed immediately after the 8GB RAM is exhausted.

To resolve this I created a 100GB swapfile on the server. But even all 100GB got exhausted within minutes and then again the process was killed, saying "out of memory".

This also happens even when mining is stopped. The rate at which RAM is exhausted is as high as 100mb/sec.

**Comment by ekryski** [comment]
You should try upgrading to v1.8.3. There were a bunch of memory improvements in 1.8.0.

**Comment by lbrep** [comment]
@karalabe , Can you kindly suggest me a way out, what could be the possible reason behind this? This occurs even when no JSON-RPC calls are being made to the running instance of geth.

**Comment by ligi** [comment]
@lbrep you should listen to @ekryski - he made a valid point - why do you stick to such an old version and do not try with a recent version?

**Comment by lbrep** [comment]
@ligi , @ekryski , Thanks for a quick response.  I have already tried with `geth` version `1.8.3` but the issue persists. Can you help me get some insight into what could have triggered this behaviour?

**Comment by ligi** [comment]
Thanks for trying 1.8.3 - unfortunate it persisted - perhaps @fjl can chip in as he is doing some work on analyzing/optimizing memory footprint. 
But somehow this sounds like a serious bug/leak then - to get to the bottom of this it would be great to have access to the chain - is this possible by any chance?

**Comment by lbrep** [comment]
yes, of course. can we be on some private messaging for this?

**Comment by lbrep** [comment]
@ligi , Yes how would you like to connect to the chain? with  --networkid flag you can, I can share the IP address, networkid and port number through email? is that fine?  I am avoiding posting it publically as I am a bit skeptical about the possible security concerns arising out of this. Do you still want me to post the details here or email is fine? Meanwhile, I have emailed you. Kindly respond if/when you receive.

**Comment by tcc-king** [comment]
@ligi, the problem occurs only when I open port 8546 on the network.  Can it be a denial of service attack?

**Comment by ajayatgit** [comment]
@lbrep I will recommend in general try to have `--nodiscovery` flag while running geth in private network.
This may have nothing to do with your problem, but at time by chance other people may also run geth with same network id.

**Comment by fjl** [comment]
@lbrep are you memory issues resolved after closing the port?

**Comment by lbrep** [comment]
@fjl , Though the issue was resolved by closing the port (` --rpcaddress flag 127.0.01`),  what is the best strategy to avoid DDoS attacks if I need to open the port ?

**Comment by ovcharovvladimir** [comment]
running 1.8.16 geth with --testnet and get the same issue, out of memory after bunch of rpc request kind of getballance

**Comment by ovcharovvladimir** [comment]
any suggestions? Can anybody define the most stable eth client?

**Comment by holiman** [comment]
Most likely it's internet attackers trying to bruteforce your password via calling `unlock`. Don't leave RPC open to the internet by exposing it on `0.0.0.0` and if you do, don't enable `personal`. 

A stack trace from the crash would show if this was indeed the case.

**Comment by ovcharovvladimir** [comment]
Thanks a lot, I have just found that! Which EIP describes this bug? As I understand anti-brute-force mechanism cannot get in time with the array in memory overloaded it?

**Comment by holiman** [comment]
There's no bug -- decrypting (or attempting to) a keystore file is very heavy on memory.
