### ISSUE TITLE
how to uninstall geth or update geth version to the latest one?

### ISSUE THREAD

**Issue by yifon** [ethereum/go-ethereum#16505]
how to uninstall geth or update geth version to the latest one?

I always hit the crash problem when running miner.start(), now my geth version is 1.7.2, I want to try the version upgrade.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
