### ISSUE TITLE
geth --syncmode 'light' : Not sync chain data

### ISSUE THREAD

**Issue by mrsantran** [ethereum/go-ethereum#16504]
Hi there,

geth --syncmode 'light' : Not sync chain data

#### System information

Geth version: `geth 1.8.4`
OS & Version: OSX

#### Command

> geth --syncmode="light" --rpcapi "eth,net,web3,personal" --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --datadir /Volumes/DATA2/ETH/data --keystore /Volumes/DATA2/ETH/keystore --ws --wsorigins='*' --wsapi "eth,net,web3,personal" --etherbase=0x1b52494bb29b0904c5eC9271F9a909d2E4a11BC3 --cache=1024

![screen shot 2018-04-15 at 3 54 14 pm](https://user-images.githubusercontent.com/21286108/38776710-88c6cc76-40c5-11e8-8422-9716bdcf17cf.png)

**Comment by karalabe** [comment]
I've just tried it and it found a peer in about half a minute. You probably want to leave it running for a while, since the light servers are mostly full, so it might take a bit until you find an empty slot. It should happen eventually though.
