### ISSUE TITLE
Don't silently accept RPC requests directed to IP address

### ISSUE THREAD

**Issue by lionello** [ethereum/go-ethereum#16507]
I was surprised to discover that `--rpcvhosts` does not prevent connection by IP address. I could connect with `http://127.0.0.1:8545` even though `--rpcvhosts` defaults to `localhost`.

This line seems to suggest that this behavior was intentional: https://github.com/ethereum/go-ethereum/blob/e9b5e22ad121ef2251d1c72526c0994c03d2caf0/rpc/http.go#L234

## Actual:
RPC requests directed to host's IP address, with `Host` header set, are always accepted, even when `--rpcvhosts` explicitly mentions which host names to serve.

## Expected:
The `Host` header of all RPC requests should be checked against the `--rpcvhosts` or `HTTPVirtualHosts` settings, regardless of whether it's an IP address or host name.

**Comment by holiman** [comment]
The `rpcvhosts` setting is in place to prevent dns rebinding attacks. Raw ip addresses are not subject to DNS rebinding attacks, hence it is allowed. 
If we were to change that behaviour, it would mean that all users everywhere would run into problems attaching to their nodes. 

Can you explain why you would want this behaviour to change? I do not see any drawbacks with it being the way it is, but perhaps I'm overlooking something.

**Comment by lionello** [comment]
@holiman  I hadn't noticed that this feature was only for preventing DNS-rebinding attacks. I found it useful to prevent robots from connecting to RPC on nodes that are found through the usual Ethereum network peer discovery.

**Comment by holiman** [comment]
Sorry for not answering until now, I didn't notice your response. 
So, the `rpcvhosts` is not the correct protection mechanism against an attacker which can create fully custom arbitrary requests. It is solely meant to prevent attacks originating from your own browser, where the attacker (a webpage) has certain restrictions about what types of requests can be made. 

If an attacker has your ip, and you are allowing network traffic over the port, then it's a bit futile to rely on rpcvhosts as a protection mechanism: the only thing preventing the attacker from interacting with your node is that he doesn't know the correct name to use. 

However, if you have a public DNS, then a simple RDNS lookup would yield it, and the attacker could also try to bruteforce names. I'm not even sure that we don't leak it ourselves in certain circumstance, e.g. if we supply origin headers in the responses and the same origin is used as the vhost. 

So it's kind of solving the wrong problem and giving people a false sense of security. A better approach is to simply not allow internet access ot the port(s).
