### ISSUE TITLE
geth --syncmode 'light' : Not broadcast transactions

### ISSUE THREAD

**Issue by mrsantran** [ethereum/go-ethereum#16510]
Hi there,

geth --syncmode 'light' : Not broadcast transactions

When i crean transaction. geth return tx hash but not broadcast transactions.
Sync work good
transactions in pending list
Sometime geth sync and broadcast one transaction, and then not.

System information
Geth version: geth 1.8.4
OS & Version: OSX

Command

> geth --syncmode="light" --rpcapi "eth,net,web3,personal" --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "" --datadir /Volumes/DATA2/ETH/data --keystore /Volumes/DATA2/ETH/keystore --ws --wsorigins='' --wsapi "eth,net,web3,personal" --etherbase=0x1b52494bb29b0904c5eC9271F9a909d2E4a11BC3 --cache=1024

![screen shot 2018-04-16 at 10 20 05 pm](https://user-images.githubusercontent.com/21286108/38818461-924dab70-41c4-11e8-9050-afd763ee35f3.png)

**Comment by veox** [comment]
Need more info:

How do you determine that the transaction is not broadcast?

Is this the only pending transaction from the `from` account?

Are you sure the `nonce` is correct?

How do you construct the transaction? (`geth console`, external RPC submission, etc.?)
