### ISSUE TITLE
Solidity compilation with bytecode optimization

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#1653]
The command line solidity compiler `solc` has the option to enable bytecode optimization:

```
$ solc --help
Allowed options:
  --optimize arg (=0)                   Optimize bytecode
  --optimize-runs arg (=200)            Estimated number of contract runs for optimizer.
```

Enabling this makes quite a difference; saving 50% construction cost on a typical MinHeap data structure contract:
```
$ solc --gas --optimize=0 contracts/heap.sol

======= MinHeap =======
Gas estimation:
construction:
   20493 + 369400 = 389893
```

Now with optimization:

```
$ solc --gas --optimize=1 contracts/heap.sol

======= MinHeap =======
Gas estimation:
construction:
   20298 + 173600 = 193898
```

Could optimization be enabled by default on the `web3.eth.compile.solidity` call?

**Comment by tgerring** [comment]
I think this belongs in the web3 repository. Issue was reated as ethereum/web3.js#258

**Comment by zelig** [comment]
@jorisbontje Yes, it will be. Is there a usecase for not wanting optimised code (i.e., do we need to introduce extra agrs to this method, or a most sophisticated config option)?

**Comment by fjl** [comment]
Geth (on the develop branch) now passes `--optimize` to solc (#1786, #1806).
