### ISSUE TITLE
Can't connect to my node via hostname

### ISSUE THREAD

**Issue by bruxo00** [ethereum/go-ethereum#16535]
#### System information

Geth version: 1.8.4-stable-2423ae01
OS & Version: Linux (Ubuntu 16.04)

#### Expected behaviour

RPC accepting connections that are made via hostname.

#### Actual behaviour

RPC doesn't accept any connections that are made trough a hostname.

#### Steps to reproduce the behaviour

I'm using this command:

`command=/usr/bin/geth --fast --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain * --rpcapi admin,db,eth,debug,net,txpool,personal,web3`

If I try to connect via direct IP address, everything works just fine. If I try to use a hostname that is pointed directly to the IP address, it simply doesn't work, even though any other application works just fine. On web3js, it shows this error:

> Failed to load: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://example.com' is therefore not allowed access. The response had HTTP status code 403.

**Comment by karalabe** [comment]
You need to epxlicitly tell Geth with hostnames it should serve RPC requests on via `--rpcvhosts=my.domain`. By default it only allows "localhost". This is to prevent DNS rebind attacks https://github.com/ethereum/go-ethereum/pull/15962
