### ISSUE TITLE
mkalloc.go:37:2: cannot find package "github.com/ethereum/go-ethereum/core" in any of:

### ISSUE THREAD

**Issue by Deekor** [ethereum/go-ethereum#16547]
I'm trying to premine some ETH on my private network with the `Alloc` field of my genesis block. When trying to run the `mkalloc.go` tool (`go run mkalloc.go genesis.json`) I get this error:

    mkalloc.go:37:2: cannot find package "github.com/ethereum/go-ethereum/core" in any of:
    	/usr/local/Cellar/go/1.10/libexec/src/github.com/ethereum/go-ethereum/core (from $GOROOT)
    	/Users/Deekor/go/src/github.com/ethereum/go-ethereum/core (from $GOPATH)
    mkalloc.go:38:2: cannot find package "github.com/ethereum/go-ethereum/rlp" in any of:
    	/usr/local/Cellar/go/1.10/libexec/src/github.com/ethereum/go-ethereum/rlp (from $GOROOT)
    	/Users/Deekor/go/src/github.com/ethereum/go-ethereum/rlp (from $GOPATH)ce

**Comment by holiman** [comment]
This looks like a build-error, not a runtime error. I suspect you have not done a `go get github.com/ethereum/go-ethereum` to place it in your `$GOPATH`...?

**Comment by karalabe** [comment]
If you want to run custom tools that generate code, you need to have a proper GOPATH set up and the sources checked out via `go get` or `git clone`.
