### ISSUE TITLE
did i really connect the peer use 'geth --bootnodes enode://pubkey1@ip1:port1'?

### ISSUE THREAD

**Issue by mxito3** [ethereum/go-ethereum#16548]
it makes me find other nodes.
i want to know whether the node 'enode://pubkey1@ip1:port1' become to one of my peers!

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
