### ISSUE TITLE
Geth 1.8.4 sync interruption

### ISSUE THREAD

**Issue by yurij-volokhov** [ethereum/go-ethereum#16545]
Hi there,

#### System information

VM: 4 CPUs, 8GB RAM, 250GB SSD
Geth version: 1.8.4
OS & Version: Ubuntu 17.10

#### Expected behaviour

I tried to sync a new node with params:
`geth --port 30603 --rpc --rpcapi personal,eth,web3,admin,net console`

#### Actual behaviour

Synchronization and communication with the network as a whole was interrupted on average every hour without any messages. I defined this by the absence of new messages from geth and the value of eth.syncing did not change. I stopped the work of the node using `exit` in the console and saw a message likes that
`ERROR[04-22|16:50:18] Failed to unregister sync peer           peer=4b771b99ec882b02 err="peer is not registered"`
then repeated repetition of this:
`INFO [04-22|15:05:25] IPC closed
err="accept unix /home/ethereum/.ethereum/geth.ipc: use of closed network connection"`

![eth](https://user-images.githubusercontent.com/7753677/39097635-bcf73d80-4667-11e8-8bfb-80b964e2e358.PNG)

**Comment by reductionista** [comment]
This is a duplicate of [Issue #16539](https://github.com/ethereum/go-ethereum/issues/16539)

**Comment by yurij-volokhov** [comment]
OK, but it's not clear for me.

I'd solved my problem rolling back to v1.8.3
