### ISSUE TITLE
geth version still shows 1.8.2 after update to 1.8.6 on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by mark-ops** [ethereum/go-ethereum#16553]
# geth version
Geth
Version: 1.8.2-stable
Git Commit: b8b9f7f4476a30a0aaf6077daade6ae77f969960
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9

# apt policy ethereum
ethereum:
  Installed: 1.8.6+build13246+xenial
  Candidate: 1.8.6+build13246+xenial
  Version table:
 *** 1.8.6+build13246+xenial 500
        500 http://ppa.launchpad.net/ethereum/ethereum/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by karalabe** [comment]
Make sure you are running the PPA version. My guess is that you might have installed a local version of Geth somewhere. What does `whereis geth` print?

**Comment by kingjerod** [comment]
You need to install `geth` through apt, not `ethereum`. For whatever reason updating `ethereum` does not update `geth`.

**Comment by kingjerod** [comment]
What is strange is when you run `apt-get install ethereum`, it does print out an updated geth version. It just doesn't seem to actually update it.

**Comment by karalabe** [comment]
Please make sure you are actually running the geth apt is installing and not your own copy from somewhere. You can check it via `whereis geth`.

**Comment by karalabe** [comment]
`apt-get install ethereum` doens't update it, you need `apt-get update ethereum` afaik.

**Comment by veox** [comment]
@karalabe That would be `apt-get upgrade ethereum`.

**Comment by mark-ops** [comment]
`apt install` will upgrade if an upgrade is available.  `apt install ethereum` does upgrade the ethereum package, but as mentioned, does not upgrade geth.

**Comment by karalabe** [comment]
For the third time, what does `whereis geth` print?
