### ISSUE TITLE
Possible memory leak in 1.8.6

### ISSUE THREAD

**Issue by kingjerod** [ethereum/go-ethereum#16557]
#### System information

Geth version: `1.8.6-stable`
OS & Version: Linux (Ubuntu 16.04)
Server: AWS m5.large (2 vCPU 8 gigs of ram, 300 GB SSD)

#### Expected behaviour
Geth to run for a very long time and not consume 7 gigs of memory

#### Actual behaviour
After running for 3 hours (synced up) memory is maxed out and server is almost unresponsive. For a bit I couldn't even run top because there wasn't enough memory. 

#### Steps to reproduce the behaviour
Run geth on AWS m5.large with this command:
`geth --syncmode fast --ws --wsapi web3,net,rpc,admin,eth --wsport 5000 --wsaddr 0.0.0.0 --wsorigins * --cache 4096 --rpc --rpcaddr 0.0.0.0 --rpcport 5001 --rpcapi web3,net,rpc,admin,eth`

No commands were sent to geth during this time, it was just allowed to sync up. This is the only thing running on this server. I have it running in supervisor and have noticed geth is restarted frequently, I think this time I just caught it while memory was maxed out. 

Screenshot of top:
![maxmemory](https://user-images.githubusercontent.com/2287252/39205230-f6dac57e-47ae-11e8-95e7-5a820fc32666.png)

Edit:
Been running for 50 minutes now and memory is up to 6 GB. Chain is still fully synced. Last log statements:
```
INFO [04-24|18:49:36] Imported new chain segment               blocks=1  txs=234  mgas=7.981   elapsed=263.386ms mgasps=30.302  number=5498918 hash=b3daa2…14b319 cache=173.56mB
INFO [04-24|18:49:55] Imported new chain segment               blocks=1  txs=161  mgas=8.000   elapsed=989.497ms mgasps=8.085   number=5498919 hash=439249…dc9ff0 cache=173.85mB
INFO [04-24|18:50:00] Imported new chain segment               blocks=1  txs=106  mgas=7.845   elapsed=184.399ms mgasps=42.546  number=5498920 hash=3855a8…a37254 cache=173.49mB
INFO [04-24|18:50:09] Imported new chain segment               blocks=1  txs=141  mgas=7.980   elapsed=567.333ms mgasps=14.067  number=5498921 hash=57f93d…ee08f7 cache=173.61mB
INFO [04-24|18:50:57] Imported new chain segment               blocks=1  txs=190  mgas=7.818   elapsed=522.828ms mgasps=14.954  number=5498922 hash=b6d606…5d3c39 cache=173.66mB
```

**Comment by fjl** [comment]
`--cache 4096` leads to high memory usage. Please reduce your cache amount (maybe use `--cache 512`) and report whether memory usage is more reasonable.

**Comment by karalabe** [comment]
Hi there! Go's garbage collector only runs when it accumulated twice as much memory as it left active after the previous run. If you run with a cache of 4GB, you will always have at least 4GB of memory used, since the database allocates it for caches. However, that means Go will start garbage collection when it reaches 8GB-ish. My suggestion is to try running with 1 (default) or 2GB cache allowance for larger servers.

**Comment by kingjerod** [comment]
Great, thanks guys!
