### ISSUE TITLE
rpc (https) using self-signed certificates

### ISSUE THREAD

**Issue by tamama** [ethereum/go-ethereum#16554]
Hi there,

#### System information

Geth version:  1.8.2-stable
Architecture:  amd64
Protocol Versions: [63 62]
Go Version: go1.10
OS & Version: Centos-7

#### Expected behaviour

server-side:
geth --syncmode=light --rpcaddr "172.21.1.231" --rpc --rpcvhosts="london-node-231.tamama.london"

client-side:
geth attach https://london-node-231.tamama.london:28546

Expected behavior : Geth console should show up.

#### Actual behaviour

[root@london-node-231 ~]# geth attach https://london-node-231.tamama.london:28546
Fatal: Failed to start the JavaScript console: api modules: Post https://london-node-231.tamama.london:28546: x509: certificate signed by unknown authority

**Comment by holiman** [comment]
Well, are you using a proper cert? I don't get the same error when I connect to via a properly signed TLS connection:
```
[user@work go-ethereum]$ build/bin/geth attach https://github.com/ethereum/go-ethereum/issues/16554
Fatal: Failed to start the JavaScript console: api modules: 422 Unprocessable Entity <!DOCTYPE html>
<html>
```

**Comment by ligi** [comment]
Any reason you are not using let's encrypt?

**Comment by fjl** [comment]
Geth uses the system-wide list of trusted root certificates. If you want to use encrypted connections with your own infrastructure, you'll have to add your root certificate to that list.

**Comment by tamama** [comment]
> Any reason you are not using [letsencrypt](https://letsencrypt.org)?

I want to run this (private Ethereum) in a totally private network, and I don't want to use letsencrypt since I would then need to register the DNS publicly.

**Comment by tamama** [comment]
> Geth uses the system-wide list of trusted root certificates. If you want to use encrypted connections with your own infrastructure, you'll have to add your root certificate to that list.

How can I do this?

**Comment by dylanpoe** [comment]
> > Geth uses the system-wide list of trusted root certificates. If you want to use encrypted connections with your own infrastructure, you'll have to add your root certificate to that list.
> 
> How can I do this?

Same questions

**Comment by Himanshu-Pandey** [comment]
> > > Geth uses the system-wide list of trusted root certificates. If you want to use encrypted connections with your own infrastructure, you'll have to add your root certificate to that list.
> > 
> > 
> > How can I do this?
> 
> Same questions

Same question

**Comment by holiman** [comment]
Some docs: https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html
