### ISSUE TITLE
how to read and decode these *.ldb files ?

### ISSUE THREAD

**Issue by IEEE756** [ethereum/go-ethereum#16563]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.8.4-stable`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour
I used `geth --datadir "/Users/lirenfu/scrapy/blockchain" --fast --cache=1024 --maxpeers 100` to do a Block synchronisation ,  and get some *.ldb files , How could i read and decode it .
![snip20180425_39](https://user-images.githubusercontent.com/11880504/39237493-47062872-48ae-11e8-9793-84646844adf8.png)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Those are leveldb database files. You'll need a leveldb client to read them. Though they are still organized in a very specific way for go-ethereum, so the only truly meaningful way is to use go-ethereum as a library from Go to access the database directly.

**Comment by IEEE756** [comment]
very thanks , I will try it
