### ISSUE TITLE
Bind geth to a specific network interface

### ISSUE THREAD

**Issue by Protected** [ethereum/go-ethereum#16567]
I don't know Go, but looking at p2p/server.go it looks like geth is hardcoded to listen on all interfaces (I also looked around and asked around and nothing made me believe otherwise). Would it be possible to add a command line parameter to tell it to listen on a specific interface? An --addr for --port, much like --rpcaddr does for --rpcport?

**Comment by karalabe** [comment]
I think it could be a valuable addition. @fjl?

**Comment by raulk** [comment]
@karalabe would this be a _good first issue_ for someone (me)?

**Comment by LukeWheeldon** [comment]
This would be very practical, also standard. Could this be reopened? Thank you.
