### ISSUE TITLE
The private chain runs out of question, and the original data is lost.

### ISSUE THREAD

**Issue by jypjyp521** [ethereum/go-ethereum#16560]
#### System information
Geth version: 1.7.0-unstable
OS & Version: Linux
#### Backtrace

INFO [04-24|07:49:39] Successfully sealed new block number=89796 hash=fd15f0…4be0ad
INFO [04-24|07:49:39] ?? block reached canonical chain number=89791 hash=4b9de5…1c342a
INFO [04-24|07:49:39] ?? mined potential block number=89796 hash=fd15f0…4be0ad
INFO [04-24|07:49:39] Commit new mining work number=89797 txs=0 uncles=0 elapsed=1.101ms
INFO [04-24|07:50:00] Successfully sealed new block number=89797 hash=c73a76…9230c7
INFO [04-24|07:50:00] ?? block reached canonical chain number=89792 hash=9fcd10…f9c54a
INFO [04-24|07:50:00] ?? mined potential block number=89797 hash=c73a76…9230c7
ERROR[04-24|07:50:00] Failed to create mining context err="missing trie node d939b90f77e005bd6b043b2da0b918ce1d3f0509f864fd28c6da3da6efa093d2 (path )"

...skipping 40 lines
INFO [04-24|12:24:22] Starting peer-to-peer node instance=Geth/v1.7.0-unstable-f4841ff4/linux-amd64/go1.8.1
INFO [04-24|12:24:22] Allocated cache and file handles database=/root/gethPravite2/geth/chaindata cache=128 handles=1024
INFO [04-24|12:24:22] Initialised chain configuration config="{ChainID: 10 Homestead: 0 DAO: DAOSupport: false EIP150: EIP155: 0 EIP158: 0 Metropolis: Engine: unk
nown}"
INFO [04-24|12:24:22] Disk storage enabled for ethash caches dir=/root/gethPravite2/geth/ethash count=3
INFO [04-24|12:24:22] Disk storage enabled for ethash DAGs dir=/root/.ethash count=2
INFO [04-24|12:24:22] Initialising Ethereum protocol versions="[63 62]" network=371
INFO [04-24|12:24:22] Loaded most recent local header number=0 hash=5e1fc7…d790e0 td=131072
INFO [04-24|12:24:22] Loaded most recent local full block number=0 hash=5e1fc7…d790e0 td=131072
INFO [04-24|12:24:22] Loaded most recent local fast block number=0 hash=5e1fc7…d790e0 td=131072
INFO [04-24|12:24:22] Starting P2P networking
INFO [04-24|12:24:24] UDP listener up self=enode://ff17b5c5219c78454b16eb54e7ce5e5616f386b4437864ff8066b7abcb44c2e682ba8029a1c6ea17d406e024870667a2694e5fa6cf5acd9a7
b1f23585b79b639@[::]:3001
INFO [04-24|12:24:24] RLPx listener up self=enode://ff17b5c5219c78454b16eb54e7ce5e5616f386b4437864ff8066b7abcb44c2e682ba8029a1c6ea17d406e024870667a2694e5fa6cf5acd9a7
b1f23585b79b639@[::]:3001
INFO [04-24|12:24:24] IPC endpoint opened: /root/gethPravite2/geth.ipc
INFO [04-24|14:02:13] Starting peer-to-peer node instance=Geth/v1.7.0-unstable-f4841ff4/linux-amd64/go1.8.1
INFO [04-24|14:02:13] Allocated cache and file handles database=/root/gethPravite2/geth/chaindata cache=128 handles=1024
INFO [04-24|14:02:13] Initialised chain configuration config="{ChainID: 10 Homestead: 0 DAO: DAOSupport: false EIP150: EIP155: 0 EIP158: 0 Metropolis: Engine: unk
nown}"
INFO [04-24|14:02:13] Disk storage enabled for ethash caches dir=/root/gethPravite2/geth/ethash count=3
INFO [04-24|14:02:13] Disk storage enabled for ethash DAGs dir=/root/.ethash count=2
INFO [04-24|14:02:13] Initialising Ethereum protocol versions="[63 62]" network=371
[backtrace]
````

**Comment by ligi** [comment]
Why do you use such an old geth version? Can you try the latest stable release?
