### ISSUE TITLE
Contract works in the realitime compiler, but not when running locally (using web3 and solc)

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/go-ethereum#1657]
Contract below.

Run `Lotto.addBuyer(10,10)` then `Lotto.getBuyerAddrs()`. Works in the realtiem compiler but not locally. Not exactly sure where to submit this issue. Sorry if this is the wrong place.

    contract Lotto {
        uint blocksPerRound=6800;
    
        struct Buyer{
            address addr;
            uint amount;
        }
  
        struct Round {
            address[] buyerAddrs;
            mapping(address=>Buyer) buyers;
        }
  
        mapping(uint => Round) rounds;

        function getRoundIndex() constant returns (uint){
            return block.number/blocksPerRound;
        }

        function getBuyerAddrs() constant returns (address[]){
            return rounds[getRoundIndex()].buyerAddrs;
        }

   
    function addBuyer(address buyerAddr,uint buyerAmount) constant returns(address[]){

        var roundIndex = getRoundIndex();
        var buyerExists = false;
        var buyerIndex = 0;
        var buyersLength = rounds[roundIndex].buyerAddrs.length;
        
        rounds[roundIndex].buyerAddrs.length++;
        rounds[roundIndex].buyerAddrs[buyersLength]=buyerAddr;
        
        return rounds[roundIndex].buyerAddrs;

        //rounds[roundIndex].buyers[buyerAddr] = Buyer(buyerAddr,buyerAmount);
    
    }

        function getBuyersLength() constant returns(uint){
            return rounds[getRoundIndex()].buyerAddrs.length;
        }
  
    }

**Comment by obscuren** [comment]
What goes wrong?

**Comment by maran** [comment]
I think you are trying to compile locally with an old solc version. What does `solc --version` give you?

**Comment by aakilfernandes** [comment]
Solc is

    solc, the solidity compiler commandline interface
    Version: 0.1.1-ac9911c1/Release-Darwin/clang/JIT

I ran `homebrew update` and reinstalled `ethereum-cpp`

**Comment by aakilfernandes** [comment]
@obscuren `getBuyerAddrs` always returns an empty array locally, returns the correct address array in the realitme compiler

**Comment by aakilfernandes** [comment]
So it looks like there is a bug in the contract, and the realtime compiler is actually the one thats too forgiving (solc is accurate). I removed the `constant` from `addBuyer` and got the desired results.

So it looks like the bug is with the realtime compiler. Not sure where (if) issues for that go, so I'll keep this open until one of the devs decide where it gos.

**Comment by tgerring** [comment]
@aakilfernandes solc is written by the C++ team over at https://github.com/ethereum/cpp-ethereum. Closing issue... if there's something specific to Geth, please reopen
