### ISSUE TITLE
Javascript error on rinkeby.etherscan

### ISSUE THREAD

**Issue by uluhonolulu** [ethereum/go-ethereum#16570]
I'm trying to track information on my token published to the rinkeby network. I'm getting a javascript error on the follwing line:
```
    if (totaltxns != null) {
        window.parent.document.getElementById('totaltxns').innerText = totaltxns; 
    }
```
(`window.parent.document.getElementById('totaltxns')` is undefined or null). I think it's because of this error that all fields are empty or zeroes. The "Token Holders" tab is loading forever.

The URL is https://rinkeby.etherscan.io/token/0x3c030e9ba171bf03154bc8d9c9105b44dcec69ba?a=

**Comment by uluhonolulu** [comment]
On the main site, this value is wrapped into a span: `<span id="totaltxns">585</span>`, but not on the rinkeby version.

**Comment by mtbitcoin** [comment]
Thanks for the heads up. Issue should be resolved now
