### ISSUE TITLE
Success status and REVERT opcode

### ISSUE THREAD

**Issue by xuhcc** [ethereum/go-ethereum#16582]
I have found interesting transaction on Rinkeby chain:

https://rinkeby.etherscan.io/tx/0x9d0f5ae03a1708f85858764d631a89ef373f92f759f4a6b773675ad02a8e6700

The transaction receipt indicates successful execution, while geth trace contains REVERT opcode. How it could be?

#### System information

Geth version: 1.8.4
OS & Version: Linux

**Comment by karalabe** [comment]
Yeah, so the error originates from the tracer which used some funky legacy code to dispose of deleted objects, not the consensus code. Swapping it out to the proper consensus function call makes everything run smoothly.

Sorry for the messup, I'll have to ping @mtbitcoin to re-trace after this is merged/released.
