### ISSUE TITLE
err will not been returned

### ISSUE THREAD

**Issue by nabice** [ethereum/go-ethereum#16587]
https://github.com/ethereum/go-ethereum/blob/cfe8f5fd948954ccedd975b6630e455a4e5653db/cmd/swarm/config.go#L139
Here we define err as a local var

https://github.com/ethereum/go-ethereum/blob/cfe8f5fd948954ccedd975b6630e455a4e5653db/cmd/swarm/config.go#L151
Here we expect err as a func block var, but it is actually a local one. So err will never been returned in line 154.

**Comment by stefanmendoza** [comment]
@nabice new to Go, so bear with me...

We declare the method locally within the function here:
https://github.com/ethereum/go-ethereum/blob/cfe8f5fd948954ccedd975b6630e455a4e5653db/cmd/swarm/config.go#L131
so any of these three lines will override the err, correct?
https://github.com/ethereum/go-ethereum/blob/cfe8f5fd948954ccedd975b6630e455a4e5653db/cmd/swarm/config.go#L139
https://github.com/ethereum/go-ethereum/blob/cfe8f5fd948954ccedd975b6630e455a4e5653db/cmd/swarm/config.go#L148
https://github.com/ethereum/go-ethereum/blob/cfe8f5fd948954ccedd975b6630e455a4e5653db/cmd/swarm/config.go#L151
So the method will either fail fast here:
https://github.com/ethereum/go-ethereum/blob/cfe8f5fd948954ccedd975b6630e455a4e5653db/cmd/swarm/config.go#L141
or return one of three things:
- `nil` for the error
-  a new `error` assuming `tomlSettings.NewDecoder(f).Decode(&config)` is non-nil (which could also be used to create a new error if it has a line number for more context)

Does that seem correct?

**Comment by nabice** [comment]
@stefanmendoza 
Notice in line 139, the define token makes `err` a inner block local var. It is not the var to be returned for the last line of this func.

**Comment by stefanmendoza** [comment]
@nabice ah, I see what you mean now. Makes sense! Still trying to get use to the two assignment operators. Coming from Java, this is very different. 😅

**Comment by nabice** [comment]
@stefanmendoza Sorry for my poor English.

**Comment by nonsense** [comment]
@nabice thank you for noting this. It has been fixed on `master`.
