### ISSUE TITLE
I think I find a bug when I read source code of feed.go in package event.

### ISSUE THREAD

**Issue by jameszo** [ethereum/go-ethereum#16580]
The line 172 to 174 in feed.go of package event which are codes of method Send(value interface{}):

    if index >= 0 && index < len(cases) {
	    cases = f.sendCases[:len(cases)-1]
    }

I think it`s not right, and should be like this:

    index = cases.find(recv.Interface())
    cases = cases.delete(index)

So that the cases left are the chans which will be TrySend again.

This a doubt when I read the code. Please tell me why if what I thought is wrong. Thanks!

**Comment by ryanschneider** [comment]
Possibly related to the `promoteTx` failures referenced in #16673?  

Could this lead to a `Send` call never getting the `<-sendLock` at [feed.go:133](https://github.com/ethereum/go-ethereum/blob/master/event/feed.go#L133) ?  I don't see an obvious way it could lead to that but I admit I haven't fully grokked what the feed code is doing reflection in `Send`.

**Comment by fjl** [comment]
I've tried to make it less confusing in https://github.com/ethereum/go-ethereum/pull/16680. @jameszo Please look at that PR and see if it makes sense to you. I'm not convinced there is a bug here.

**Comment by fjl** [comment]
@ryanschneider I don't think `sendLock` can be messed up like that because it is independent of the select on the actual subscription channels.

**Comment by jameszo** [comment]
@fjl Ah,I get it! Thank you so much!
