### ISSUE TITLE
copydb fails on ropsten chain

### ISSUE THREAD

**Issue by fxer** [ethereum/go-ethereum#16591]
#### System information

Geth version: 1.8.6
OS & Version: Ubuntu 16.04 LTS

#### Expected behaviour
geth creates a pruned (no state data) copy of the ropsten blockchain

#### Actual behaviour
geth aborts with error `err="retrieved hash chain is invalid"`

#### Steps to reproduce the behaviour
`$ geth --datadir=/mnt/chaindata/newchain copydb --cache=2048 /mnt/chaindata/geth/chaindata/`

Like many others I've found issue #15797 and used it to keep my storage requirements for full nodes down.

Copy-and-pasting the command above onto my `mainnet` nodes it works perfectly (well, geth crashes several times during the whole process and has to be restarted but does eventually complete, however that is another ticket). But on my `ropsten` nodes the `copydb` command won't even begin.

#### Backtrace

````
$ geth --datadir=/mnt/chaindata/newchain copydb --cache=2048 /mnt/chaindata/geth/chaindata/
INFO [04-27|22:02:01] Maximum peer count                       ETH=25 LES=0 total=25
INFO [04-27|22:02:01] Allocated cache and file handles         database=/mnt/chaindata/newchain/geth/chaindata cache=1536 handles=1024
INFO [04-27|22:02:01] Disk storage enabled for ethash caches   dir=/mnt/chaindata/newchain/geth/ethash count=3
INFO [04-27|22:02:01] Disk storage enabled for ethash DAGs     dir=/home/coinnode/.ethash              count=2
INFO [04-27|22:02:01] Loaded most recent local header          number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [04-27|22:02:01] Loaded most recent local full block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [04-27|22:02:01] Loaded most recent local fast block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [04-27|22:02:01] Allocated cache and file handles         database=/mnt/chaindata/geth/chaindata/         cache=2048 handles=256
INFO [04-27|22:02:01] Block synchronisation started 
WARN [04-27|22:02:02] Synchronisation failed, dropping peer    peer=local err="retrieved hash chain is invalid"
WARN [04-27|22:02:02] Downloader wants to drop peer, but peerdrop-function is not set peer=local
retrieved hash chain is invalid
````

**Comment by karalabe** [comment]
You need to specify `--testnet` too. Without it, geth initializes the mainnet, and then tries to sync ropsten on top, which fails miserably.

**Comment by fxer** [comment]
Thanks! That was the winner, I was adding `--testnet` in the wrong place and it also didn't like when I included `--networkid 3`

Success with:
`$ geth --datadir=/mnt/chaindata/newchain copydb --cache=2048 --testnet /mnt/chaindata/geth/chaindata/`
