### ISSUE TITLE
Tracer accessed out of bound stack

### ISSUE THREAD

**Issue by linuxion** [ethereum/go-ethereum#16599]
#### System information

Geth version: 1.8.4-unstable
OS & Version: Ubuntu 16.04
Commit hash : 6cdfb9a3

#### Expected behaviour
Run without `out of bound memory` error.

#### Actual behaviour
Get a lot of errors of this type.
````
WARN [04-28|20:00:17] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0
WARN [04-28|20:00:19] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0
WARN [04-28|20:00:19] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0
WARN [04-28|20:00:33] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0
WARN [04-28|20:00:33] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0
WARN [04-28|20:00:46] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0
WARN [04-28|20:01:09] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0
WARN [04-28|20:01:09] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0
````
#### Steps to reproduce the behaviour
Run geth in archive mode OR trace `0xc0f77f2f18e90bcfc5e3074e8faab3b925058474c6683d98f5313673c909c99f` transaction, for example.

#### Backtrace

````
WARN [04-28|16:08:55] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0
WARN [04-28|16:08:59] Tracer accessed out of bound stack       size=0 index=1
WARN [04-28|16:08:59] Tracer accessed out of bound stack       size=0 index=3
WARN [04-28|16:08:59] Tracer accessed out of bound stack       size=0 index=4
WARN [04-28|16:08:59] Tracer accessed out of bound stack       size=0 index=5
WARN [04-28|16:08:59] Tracer accessed out of bound stack       size=0 index=6
WARN [04-28|16:08:59] Tracer accessed out of bound stack       size=0 index=2
WARN [04-28|16:09:07] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0]
````

#### Thoughts  
[slice](https://github.com/ethereum/go-ethereum/blob/a5c0bbb4f4c321c355637ef57fff807857128c6b/eth/tracers/tracer.go#L95) and [getUint](https://github.com/ethereum/go-ethereum/blob/a5c0bbb4f4c321c355637ef57fff807857128c6b/eth/tracers/tracer.go#L106) functions throwing the error only affect the memory, but [peek](https://github.com/ethereum/go-ethereum/blob/a5c0bbb4f4c321c355637ef57fff807857128c6b/eth/tracers/tracer.go#L149) affects the stack. 

@karalabe, can this error be the cause of incorrect output by the tracer?

Thank you!

**Comment by karalabe** [comment]
I've seen these "errors". They're not really errors, rather some contracts explicitly do invalid operations (e.g. try to access memory area that doesn't exist). When the tracer is running, it tries to "gather" the infos from potentially invalid parameters, and just tells you it's not possible. The contracts will probably throw in the next step when the EVM refuses the accesses too.

I may be wrong of course, but I did see many contracts try to break consensus with nasty params, so I'd chalk it up for those unless you explicitly know the contract/transaction is ok. In that case, please provide more details.
