### ISSUE TITLE
Request ether via https://faucet.rinkeby.io/ does not work on Chrome

### ISSUE THREAD

**Issue by bladexxv** [ethereum/go-ethereum#16600]
Hi,

Request ether via `https://faucet.rinkeby.io/ `does not work on Chrome, but works fine in Safari.

#### System information

OS & Version: Mac, Chrome(version 65).

#### Expected behaviour

Requesting ether using Google+/Twitter URL should transfer ether.

#### Actual behaviour

Clicking "Give me ether" does not prompt any message, and the webpage of https://faucet.rinkeby.io/  is different from Safari.

#### Steps to reproduce the behaviour
<img width="1252" alt="chrome-ether-rinkeby" src="https://user-images.githubusercontent.com/24198670/39402752-25112dc6-4b9b-11e8-9fc7-f696711ecc75.png">
Open Chrome, input https://faucet.rinkeby.io/, and copy URL, and then click "give me ther".

**Comment by karalabe** [comment]
Refresh, apparently it didn't load all the CSS/JS files. It works well for me under Chrome. (`Ctrl + R`)

**Comment by gked** [comment]
I am also experiencing the same issue. I can repro on FF, Chrome and Edge.
It is throwing some web sockets errors. Can you look into this? I can't proceed with my development without it. Or is there a web api that I can call into to get rinkeby test tokens?

![capture](https://user-images.githubusercontent.com/12704474/50369974-18eb2980-0553-11e9-9ba6-2c02064e1960.PNG)

**Comment by EugeneNaloiko** [comment]
Same for me here. In Firefox Captcha was requested, in Chrome - not. Just no action after I press get ETH.
As well: "WebSocket connection to 'wss://faucet.rinkeby.io/api' failed: Error during WebSocket handshake: Unexpected response code: 521"
