### ISSUE TITLE
segfault on Windows

### ISSUE THREAD

**Issue by Quiark** [ethereum/go-ethereum#1660]
Version: `   /v1.0.1/windows/go1.4.2`
What I did: nothing, just let it run in the background for around 2 days, computer was sleeping a few times in between. Also ran a VirtualBox VM but I don't think I ran out of memory.

Started using:
`.\geth.exe --rpc --rpcaddr="localhost" --rpcport="8545" --rpccorsdomain="http://localhost:3000" --verbosity=3 --datadir "..\geth_data" --genesis "..\genesis.json" console`

Output / stacktrace:
http://hastebin.com/pupozejoro.avrasm

**Comment by fjl** [comment]
A preliminary analysis of the backtrace indicates that this is caused by a race involving concurrent calls to `nodeDB.querySeeds` (which is not safe for concurrent use).

**Comment by Quiark** [comment]
Another instance?  
http://hastebin.com/likiloyera.avrasm
