### ISSUE TITLE
Segmentation Fault(SIGSEGV) when starting Geth

### ISSUE THREAD

**Issue by AyushG3112** [ethereum/go-ethereum#16606]
Geth version: 1.8.6-stable
OS & Version: Ubuntu 16.04.2

#### Expected behaviour
Geth should start syncing the blockchain.

#### Actual behaviour
Geth crashes with segmentation violation

#### Steps to reproduce the behaviour
No specific steps. Simply starting Geth.

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa6faab]

goroutine 83 [running]:
github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc420662940)
	/build/ethereum-LEwR9U/ethereum-1.8.6+build13246+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:434 +0x2eb
created by github.com/ethereum/go-ethereum/eth/filters.NewEventSystem
	/build/ethereum-LEwR9U/ethereum-1.8.6+build13246+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:113 +0x104
````

**Comment by joeysino** [comment]
@AyushG3112 Yes we are also using AWS. It seems to happen with either `--rpc` or with `--ws`.

**Comment by joeysino** [comment]
Oh I see my mistake. `--rpcaddr` should get the local machine's IP address, not the remote machine's IP address. (That is for the firewall!)

So that's why it exploded when I changed IP address.

**Comment by AyushG3112** [comment]
@joeysino So what I've been able to diagnose, the private IP of your AWS instance is assigned to your instance, so you can bind to it. The Public and Elastic IP are allocated to the AWS NATs which forward your requests, so if you try binding to it, it crashes.

Same thing happened with our other nodes, they were not able to start servers at the Public or Elastic IP

**Comment by joeysino** [comment]
Yes that's right. AWS instances have multiple IPs, internal and external, and for this binding we need to use the internal one. (Which can be found from `ifconfig`.)

So I think we solved our problem at least. But perhaps geth could **provide a better error message** when the IP cannot be bound to.

**Comment by AyushG3112** [comment]
@holiman Yes. On binding to a non-available IP, Geth is throwing SIGSEGV, removing the IP or changing it to an available one works perfectly. Can reproduce multiple times.
