### ISSUE TITLE
'--syncmode "fast"' after removedb running almost 3 days and take about 79Gb

### ISSUE THREAD

**Issue by drakmail** [ethereum/go-ethereum#16614]
#### System information

Geth version: `1.8.3-stable`
OS & Version: `Ubuntu 16.04.4`
Commit hash : `329ac18ef617d0238f71637bffe78f028b0f13f7`

#### Expected behaviour

Seems that chaindata must be about 68-72Gb (according to https://etherscan.io/chart2/chaindatasizefast)

#### Actual behaviour

I'm synced to 5533382 block and already have about 79Gb of chaindata

#### Steps to reproduce the behaviour

Perform removedb and run geth with following params:

```bash
./geth --nousb --syncmode "fast" --cache 2048 --rpc --rpcapi personal,web3,eth,net
```

```bash
du -h ~/.ethereum/
16M     /home/eth/.ethereum/geth/nodes
78G     /home/eth/.ethereum/geth/chaindata
233M    /home/eth/.ethereum/geth/ethash
79G     /home/eth/.ethereum/geth
1.8M    /home/eth/.ethereum/keystore
79G     /home/eth/.ethereum/
```

**Comment by quasisamurai** [comment]
Mate, my geth is syncing about 35 days till start. Now i have about 158million pulled states and it is not ended yet. :hankey: 
So I started it on 3 PCs, and state is almost the same.
Dunno how to get actual livenet.

**Comment by Othman21** [comment]
Total number of state entries are around 175M at the moment and continually increasing ...
[https://gitter.im/ethereum/go-ethereum?at=5afd82bc1cfca775e1178f38](url)
