### ISSUE TITLE
Light sync doesn't connect to higher version peers

### ISSUE THREAD

**Issue by WernerderChamp** [ethereum/go-ethereum#16612]
I'm using Ethereum Wallet in Light Mode.

As Ethereum Wallet doesn't seem to update geth every time, every time when there is a new version, light mode does not find any peers, even after waiting for hours.

As soon as I update geth and run it in console it works again and is synced within minutes

#### System information

Geth version: `1.8.0/1.8.2/1.8.4` (stable build)
OS & Version: Windows

**Comment by dobdob** [comment]
Thanks for the tip. I was using the default geth (1.8.2) with the current 0.10.0 Ethereum Wallet in light mode and could never find any peers. Stated geth 1.8.6 manually in light mode and now I can find peers.

**Comment by jstefanop** [comment]
Can confirm the same issue is present on Mac .10 wallet.

**Comment by b-f-** [comment]
Similar issue here. Updated geth 1.8.3 to 1.8.7 (win 10/x64/zip), start light node with:
-syncmode light --cache=1024 console 3>> d:\geth_log.txt

What happens is, the node syncs ok. Exit, restart geth: no syncing ever occurs (left it running for 6h). After changing parameters to 
-syncmode light --cache=1024 --port "[non-default-port]"
geth seems to start working fine again. 
Storj uses port 30303 also. But restarting the machine and exiting storj did not solve the above issue. This could imply that the console 3>> command is somehow related to the problem.
