### ISSUE TITLE
Build error [geth] error 127

### ISSUE THREAD

**Issue by SocialDigitalBank** [ethereum/go-ethereum#16613]
Hello.

I have some problem building geth.
I am using UBUNTU and Golang 1.10

make geth
build/env.sh go run build/ci.go install ./cmd/geth
make: build/env.sh: No such file or directory make
Makefile:15: recipe for target 'geth' failed
make: *** [geth] error 127

How can i solve this?

any help?

**Comment by karalabe** [comment]
Are you sure you have a properly checked out repo? The error seems to indicate that you either have missing files, or are in some wrong folder.

**Comment by BrikiMichael** [comment]
you just need to install go 

1. cd ~
    wget https://dl.google.com/go/go1.9.3.linux-amd64.tar.gz
2. sudo tar -C /usr/local -xzf go1.9.3.linux-amd64.tar.gz

after that add go to path env 

1. export PATH=$PATH:/usr/local/go/bin

close and terminal and reopen it , verify that go is added by 

1.which go
2.go version

for more detail check this : https://medium.com/cybermiles/running-a-quick-ethereum-private-network-for-experimentation-and-testing-6b1c23605bce

**Comment by adamschmideg** [comment]
No response from the reporter. I assume it was solved by one of the comments. Closing it.

**Comment by maritbtbei** [comment]
I have the same problem. I am on Ubuntu 18. what should I do?

**Comment by karalabe** [comment]
You can't have the same problem because that file doesn't exist any more. Please open a new issue and don't spam "me too" on old ones.
