### ISSUE TITLE
Document `trusted-nodes.json` or remove it

### ISSUE THREAD

**Issue by paulvi** [ethereum/go-ethereum#16646]
Where is documentation about `trusted-nodes.json` ? ref #14472

- [ ] Commits like 62fc96620d864291dc56bae5568cbaa44714c19f should go with documentation updates.

Both resources below do not mention about trusted-nodes:  

- https://github.com/ethereum/homestead-guide/blob/master/source/network/connecting-to-the-network.rst#static-nodes-trusted-nodes-and-boot-nodes
- https://github.com/ethereum/go-ethereum/wiki/Connecting-to-the-network

**Comment by RichHorrocks** [comment]
From [here](https://github.com/ethereum/go-ethereum/blob/5490437942967638bcc6198035315f6811febaa8/p2p/server.go#L91):

```
	// Trusted nodes are used as pre-configured connections which are always
	// allowed to connect, even above the peer limit.
	TrustedNodes []*discover.Node
```

There are various questions about Trusted Nodes on Stack Exchange ([example](https://ethereum.stackexchange.com/questions/6821/how-does-ethereum-client-select-which-peers-to-synchronise-with/6922#6922), another [example](https://ethereum.stackexchange.com/questions/2478/what-is-the-difference-between-a-static-node-and-a-trusted-node)).

**Comment by paulvi** [comment]
Thank you Richard.

No it is clear, that this is undocumented feature, that one needs to read code

https://github.com/ethereum/go-ethereum/blob/5490437942967638bcc6198035315f6811febaa8/p2p/server.go#L93

What is place for geth Documentation ?

BTW, command line help should references this feature (or simple math will not work for unaware users)

```
NETWORKING OPTIONS:
...
  --maxpeers value      Maximum number of network peers (network disabled if set to 0) (default: 25)
```

**Comment by MysticRyuujin** [comment]
I think this should get a bump

**Comment by adamschmideg** [comment]
We may not need this feature anymore. We're going to ask around if users rely on trusted nodes.

**Comment by MysticRyuujin** [comment]
I'm just one guy and I may or may not be using it correctly, but I assign my local nodes to each other. Especially during a re-sync, in the hopes that my nodes are used for the majority of the bandwidth vs going over the internet. When I have SSD 10Gb nodes sitting on the same LAN I'd prefer them to sync from each other initially and during catch up periods (downtime).

**Comment by holiman** [comment]
The documentation is here:
https://geth.ethereum.org/docs/interface/peer-to-peer#trusted-nodes

It was added in #22190 , which should have auto-closed this issue, but I'll just close it now instead
