### ISSUE TITLE
how to create defaultGenesisBlock  by myself

### ISSUE THREAD

**Issue by zhuimengshaonian66** [ethereum/go-ethereum#16642]
hello everyone,now i am studying go-ethereum i dont konw how to create defaultGenesisBlock  by myself(https://github.com/ethereum/go-ethereum/blob/release/1.3.3/core/default_genesis.go)
`::`
const defaultGenesisBlock = "H4sIAAAJbogA/5S9267gSHOl9y59PRd5Pszb5BEYQJi5sQEbgt/d3+Kukv0nyf1zWlKruro3i8yMjFgrMmLFf/7zP//X/xzrn//+j/m/zL/8Fdw//+2f+T/2/h/j//yP/+P/vv6L8Pdf8q/af/zH/xr//Pf//Me74nK1M+2Zrd

so someone can give a idea how to create a defaultGenesisBlock   to create GenesisBlock

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
