### ISSUE TITLE
can't find peers when run --syncmode "light" 

### ISSUE THREAD

**Issue by mxito3** [ethereum/go-ethereum#16649]
after i run --syncmode "light" ,it takes some time to sync.but the second time i start geth use geth --syncmode "light",it can't find peers.

**Comment by mxito3** [comment]
"enode://44d4335bcfd4fce27d6d53bccf4f694668bfab9b8c0ad6bdd1120a34a84f369ba1bc819efc7fab25e582433be1fff57a7c7b0a2bff4b99fd5e31ab3258863259@[::]:30303?discport=0"

**Comment by veox** [comment]
This is known, and has been reported many times. It's not a code issue, but more of a social one: there is no incentive to run `lightserv` nodes, so it is done on a volunteer basis.

The simplest course of action is to wait.

An (experimental, paid) alternative is to use the [`vipnode`](https://vipnode.shazow.net/) service.

-----

Suggest closing issue as not actionable.

**Comment by arhuaco** [comment]
What is the easiest way to run a -lightserv node if have at most 30GB of SSD?
