### ISSUE TITLE
The coinbase is suspected as a hack.

### ISSUE THREAD

**Issue by SeongJongJeon** [ethereum/go-ethereum#16643]
Hi there,

My node is mining.
but the coinbase address(0x7097f41f1c1847d52407c629d0e0ae0fdd24fd58) is automatically changed in the middle.

miner.setEtherbase(eth.accounts[0]) is not set

#### System information
Geth version: `1.7.3 or 1.8.6`
OS & Version: Ubuntu 16.04.4 LTS
Commit hash : develop`

#### Steps to reproduce the behaviour
1. Run geth
nohup geth --datadir /sdata/ether/.ethereum \
--ethash.dagdir /sdata/ether/.ethash \
--etherbase '0x7a64ca9836b18fadaa52b2cbca3ca7d71edb6cd4' \
--unlock '0x7a64ca9836b18fadaa52b2cbca3ca7d71edb6cd4' \
--password /sdata/ether/account_pwd.txt \
--cache 4096 \
--verbosity 4 \
--mine --minerthreads=1 \
--rpc --rpcapi personal,db,eth,net,web3,miner,net,txpool \
--rpcport 6703 \
--port 6704 \
--rpcaddr 0.0.0.0 \
--rpccorsdomain '*' > /data/logs/geth/ether.log 2>&1 & echo $! > /sdata/ether/geth.pid

2. Connect to geth
geth attach ipc:/sdata/ether/.ethereum/geth.ipc

3. Check coinbase
> eth.coinbase
result (the coinbase address is automatically changed in the middle) : 0x7097f41f1c1847d52407c629d0e0ae0fdd24fd58

**Comment by karalabe** [comment]
You're exposing your node with full functionality to the internet. You are essentially asking random people from the internet to mess around with your node. Please never ever ever open the RPC interface generically to everyone.

**Comment by SeongJongJeon** [comment]
@karalabe 
Thank you for your advice.
I changed rpcaddr to localhost.
Probably it was attacked by opening it as a whole.
