### ISSUE TITLE
Personal API stopped working

### ISSUE THREAD

**Issue by juliavi** [ethereum/go-ethereum#16647]
#### System information

Geth version: `1.8.2`
OS & Version: Linux

#### Expected behaviour
I've enabled the Personal api, but I'm still getting the follwoing error
`The method personal_newAccount does not exist/is not available`
`The method personal_unlockAccount does not exist/is not available`

I ran geth this way -
`geth --rinkeby --rpc --rpcaddr 0.0.0.0 --rpcport 8545 –-rpcapi="eth,net,web3,admin,personal"`

#### Actual behaviour

The methods should work. 

#### Steps to reproduce the behaviour
`geth --rinkeby --rpc --rpcaddr 0.0.0.0 --rpcport 8545 –-rpcapi="eth,net,web3,admin,personal"`

and then run 
`newAccount` or `unlockAccount`

**Comment by rjl493456442** [comment]
`personal` namespace APIs are not opened to HTTP rpc, you can only invoke them via IPC.
The command can look like: `geth attach geth.ipc`

**Comment by karalabe** [comment]
@rjl493456442 If you specify `–-rpcapi="eth,net,web3,admin,personal"`, then it should open the personal namespace too.

**Comment by karalabe** [comment]
Hmm, wait... that first dash in `–-rpcapi` is wrong. @juliavi Are you sure you have `--` in there and not some weird character?

**Comment by Shahrudinov** [comment]
same error(
/usr/bin/geth --rinkeby --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain * --rpcapi="admin,db,eth,net,shh,txpool,personal,web3" --fast
