### ISSUE TITLE
Transactions from chain reorganisations should go back into the tx pool

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#1664]
This is a also question, as i'm not sure if go does that already, but i had a discussion with Arkady and Gustav and was not sure.

If we have chain re-orgs and a block gets discarded/stalled due to a better chain, do we put the transactions from those block(s) back into the pool, as long as they weren't mined already in the new chain as well?

If not this could loose transactions, and puts the burden of resending transactions to the user, which is IMO the wrong approach.

Once submitted the node should make sure its keep as long in the pool until its mined at some point.

**Comment by frozeman** [comment]
@obscuren isn't this now solved?

**Comment by fjl** [comment]
Being implemented in #1669.
