### ISSUE TITLE
SimulateBackend AdjustTime is not adjusting time at all, or either in unexpected ways.

### ISSUE THREAD

**Issue by bonedaddy** [ethereum/go-ethereum#16655]
While using SimulateBackend I attempted to roll forward the time of the simulated blockchain using `AdjustTime(604800 *time.Second)` which should roll forward time by a week. Checking the returned error value shows that it is nil, however from all my testing it appears that time does not actually roll forward, and local system time is used. Attempting to call functions which should work after time is rolled forward, do not work. 

go version: `go1.10.11 linux/amd64`

Using the lates go-ethereum version.

**Comment by dimchansky** [comment]
I had the similar issue, until I've added `Commit` after `AdjustTime`. Before making transaction in the distant future, adjust time and commit, and only then make transactions, like:
```
	if err := backend.AdjustTime(72 * time.Hours); err != nil {
		panic(err)
	}
	backend.Commit()

	// now make transactions "after 72 hours"
```

**Comment by karalabe** [comment]
I myself would forbid time adjustments on non-empty blocks.

**Comment by bonedaddy** [comment]
@ligi I meant smart contract functions that require block timestamps to be past a certain point.
