### ISSUE TITLE
[Question] Where are all milestone listed? 

### ISSUE THREAD

**Issue by paulvi** [ethereum/go-ethereum#16664]
For recent releases there are links for milestones, e.g.

1.8.4 https://github.com/ethereum/go-ethereum/milestone/68
1.8.7 https://github.com/ethereum/go-ethereum/milestone/65

But https://github.com/ethereum/go-ethereum/milestone is Not Found page.

Is there a page to see all releases listed?

Also where is a place to check what versions of geth are related to Homestead or Metropolis (vByzantium) etc ?

**Comment by ligi** [comment]
Find the releases here: https://github.com/ethereum/go-ethereum/releases

**Comment by paulvi** [comment]
Yes, indeed https://github.com/ethereum/go-ethereum/milestones?state=closed has all

But which versions correspond to ,say, Homestead?

Homestead should be a range of version, isn't it?
