### ISSUE TITLE
There is a bug that when input a parameter 2^255 to geth , it will change to 0x800000000000016c889a28c160ce0422bb9138ff1d4e4827 wrongly.  

### ISSUE THREAD

**Issue by RoodyChan** [ethereum/go-ethereum#16662]
**when i input a parameter like Math.pow(2,4) to geth , it will change to 2^4=16 correctly.** 
token.batchTransfer([user2,user3],Math.pow(2,4),{from:user1})

![1](https://user-images.githubusercontent.com/29420758/39557880-3e9fb686-4e7a-11e8-9440-9cc65d2876d4.jpg)
![2](https://user-images.githubusercontent.com/29420758/39557881-3ed9e996-4e7a-11e8-9004-4095dc5aa9e4.jpg)

**but when i input a parameter like Math.pow(2,255) to geth , it will change to 0x800000000000016c889a28c160ce0422bb9138ff1d4e4827  wrongly insteaf of 
0x8000000000000000000000000000000000000000000000** 
token.batchTransfer([user2,user3],Math.pow(2,255),{from:user1})

![3](https://user-images.githubusercontent.com/29420758/39557895-4de561e0-4e7a-11e8-89a3-c5375c635bd5.jpg)
![4](https://user-images.githubusercontent.com/29420758/39557897-4e341ca4-4e7a-11e8-8fd8-e0004d526b8d.jpg)

**Comment by RoodyChan** [comment]
in addition,  when i input a parameter 57896044618658097711785492504343953926634992332820282019728792003956564819968
(2 ^ 255) to geth , it will change to 0x800000000000016c889a28c160ce0422bb9138ff1d4e4827 wrongly insteaf of
0x8000000000000000000000000000000000000000000000

![7](https://user-images.githubusercontent.com/29420758/39564420-b5bcc1a4-4ea3-11e8-9b09-1bd2f97df6a9.png)
![8](https://user-images.githubusercontent.com/29420758/39564421-b5f66f76-4ea3-11e8-8d71-406a7a5a350b.png)

**Comment by karalabe** [comment]
The console is a JavaScript console. JavaScrips uses float-s to represent numbers. The number you're trying to represent cannot be done via floats, it overflows and loses precision. You'll need to use a big number library that can work with arbitrary precision integers.

**Comment by RoodyChan** [comment]
Thank you very much!
when i use the following way to represent numbers,then it works!
> var value = web3.toBigNumber('578960446186580977117854925043439539266349923328202820197
28792003956564819968');
