### ISSUE TITLE
High CPU usage ~50% (i.e. 2 cores out of 4) in Firefox, when opening https://www.rinkeby.io

### ISSUE THREAD

**Issue by paulvi** [ethereum/go-ethereum#16677]
High CPU usage ~50% (i.e. 2 cores out of 4) in Firefox, when opening https://www.rinkeby.io

Chrome is OK

![image](https://user-images.githubusercontent.com/1614482/39618917-612a44f2-4fb8-11e8-8a6a-8d7c41bf1359.png)

The site sources are definitely not from this repository, please point to.

**Comment by karalabe** [comment]
Unfortunately the ethstats client is a monster, as it has a crazy amount of traffic (every update from every node is streamed out to the web clients). There's not much to do about it really, it annoys me too. Try not to keep it open too much :D

**Comment by paulvi** [comment]
Are the sources at this non-active https://github.com/cubedro/eth-netstats repository ?

**Comment by karalabe** [comment]
I have a custom fork that includes some fixes I made that were never upstreamed due to the project being abandoned https://github.com/puppeth/eth-netstats
