### ISSUE TITLE
Rinkeby faucet down again

### ISSUE THREAD

**Issue by wbt** [ethereum/go-ethereum#16672]
Like in Issue #16600, I am not getting the Rinkeby faucet to work, though I did observe yesterday's recovery from https://github.com/ethereum/go-ethereum/issues/16602.  I am on Windows 10 and observe the issue in Firefox, Chrome, and Brave browsers where there seems to be a brief flash of network communication with google.com/ReCAPTCHA when clicking on the amount / time period, but then nothing.  In Opera and Edge, I got a ReCaptcha or two (Google doesn't think bicycles count as vehicles, apparently) to solve, but nothing happened after.  The lack of network statistics suggests the faucet node may be offline? Screenshot:

![image](https://user-images.githubusercontent.com/563406/39597902-dc64eef8-4ee4-11e8-845d-a0342a664297.png)

Note that all tests were done with a URL in the box as requested, and refreshing the page one or several times and/or waiting several minutes past when the page reported being fully loaded didn't work.

**Comment by karalabe** [comment]
Seems to work now. Not sure what might have gone wrong.

**Comment by AyushyaChitransh** [comment]
Faucet is down again. Looking at console, I can see some error messages:

`WebSocket connection to 'wss://faucet.rinkeby.io/api' failed: Error during WebSocket handshake: Unexpected response code: 503`

**Comment by csplawn918** [comment]
bitcoin:13Y5tFAxPSBbm7qmxvFsp1xYnBRoUSVz15?amount=0.0005

**Comment by karalabe** [comment]
Temporarily available at https://faucet.rinkeby.net/

See https://twitter.com/peter_szilagyi/status/1106475845709979648
