### ISSUE TITLE
--txpool.lifetime don't work

### ISSUE THREAD

**Issue by akwei** [ethereum/go-ethereum#16685]
I use this to start Geth
./geth --testnet --cache 4096 --rpc --rpcapi "eth,web3,personal,net,miner,admin,txpool" --txpool.lifetime 0h1m0s --datadir ./testnet --ipcpath ./testnet/geth.ipc

But --txpool.lifetime 0h1m0s dose not work.  I saw non-executable transactions in txpool.queued after 10 minutes.

I use 1.8.4-stable version. 
Git Commit: 2423ae01e0d2f853512eb2b46954b5ad0754a897

Please help me.
Thanks

**Comment by akwei** [comment]
Ok . I understand the mistake. txpool.queued is not non-executable transactions queue

**Comment by cody588** [comment]
so how can I clean the transactions in txpool.queued ? thank you

**Comment by poctek** [comment]
@cody588 delete your `transactions.rlp` which is located by default in the folder `.ethereum/geth`

**Comment by akwei** [comment]
Do not delete transactions.rlp manually. Just gave txpool.lifetime an appropriate period (like 1h0m0s ),then at this time,the transactions not pending will be cleared automatically.

**Comment by maroodb** [comment]
it didn't work for me I tried "0h0m3s"

**Comment by maroodb** [comment]
any help ?
