### ISSUE TITLE
There is no official documentation about geth requirements

### ISSUE THREAD

**Issue by luarx** [ethereum/go-ethereum#16681]
#### System information

Geth version: 1.8.6
OS & Version: Linux

#### Expected behaviour
I want to see an official hardware requirements document to have a full node in a machine.
(I think that requirements will be different if someone wants a full or a light node).
I would be useful if this document contains:
- CPU
- RAM
- IOPS
- Network
- Disk space
- Geth execution parameters for each type of hardware configuration.
- Is it compatible with a cloud environment? (AWS/Azure/Google...)
- Specific configurations for each clould enviornment

#### Actual behaviour
**There is no official documentation about different hardware configurations** (I haven't seen it). I have to ask for it in geth forums.
For this reason, I don't know if a slow sync is because a bad hardware configuration or a real Geth bug.

**Comment by luarx** [comment]
Do we have any update on that?

**Comment by luarx** [comment]
:(

**Comment by adamschmideg** [comment]
Some possible sources of information:
- https://dappnode.io
- https://infura.io
- https://etherscan.io

**Comment by zjiekai** [comment]
I used `i3.2xlarge` after reading <https://blog.ethereum.org/2019/07/10/geth-v1-9-0/>

**Comment by verheesj** [comment]
[Ethereum Hardware Requirements](https://ethereum.org/en/developers/docs/nodes-and-clients/#hardware)

**Comment by MariusVanDerWijden** [comment]
@muddlebee I think the hardware requirements are better suited for the website than for the readme
closing in favor of https://github.com/ethereum/go-ethereum/issues/20260
