### ISSUE TITLE
Mobile (android) - My mobile-node don't connect with my private node 

### ISSUE THREAD

**Issue by ArthurTavaresBezerra** [ethereum/go-ethereum#16689]
Geth version: `Geth 1.8.2`
OS & Version: Android 27

#### Expected behaviour
I expect that my node on android connect with my node on Mac OSX. Actually, I have to see in admin.peers on my node using geth.
  
#### Actual behaviour
Nothing happened;
I don't get balance of another account of another node.
The node no syncing 

#### Steps to reproduce the behaviour

            Enode enode = new Enode("enode://66a19741686a0f845e8ebf5f29ae85bbfe04d5f62819918acdb8f5ff427de04fc93d6417419df26e7810d8cbef8d026c27cba769d316d73023c91141afae443f" +
                    "@192.168.15.6:30303");
            Enodes enodes = new Enodes();
            enodes.append(enode);

            KeyStore keyStore = new KeyStore(getFilesDir() + "/keystore2", 0l,0l);
            Account mainAccount = keyStore.newAccount("a1");

            NodeConfig nodeConfig = new NodeConfig();
            nodeConfig.setEthereumNetworkID(1114); //Your Private Network-ID
            nodeConfig.setWhisperEnabled(true); // Your Node Settings
            nodeConfig.setEthereumEnabled(true);
            nodeConfig.setBootstrapNodes(enodes);

            String genesis ="{" +
                            "    \"config\": {" +
                            "     \"chainId\": 15," +
                            "     \"homesteadBlock\": 0," +
                            "     \"eip155Block\": 0," +
                            "     \"eip158Block\": 0" +
                            "    }," +
                            "    \"nonce\": \"0x0000000000000042\"," +
                            "    \"timestamp\": \"0x0\"," +
                            "    \"parentHash\": \"0x0000000000000000000000000000000000000000000000000000000000000000\"," +
                            "    \"gasLimit\": \"0x8000000\"," +
                            "    \"difficulty\": \"0x400\"," +
                            "    \"mixhash\": \"0x0000000000000000000000000000000000000000000000000000000000000000\"," +
                            "    \"coinbase\": \"" + mainAccount.getAddress().getHex() + "\"," +
                            "    \"alloc\": {" +
                            "     \"" + mainAccount.getAddress().getHex() + "\": {\"balance\": \"0x1337000000000000000000\"}" +
                            "    }" +
                            "}";
            nodeConfig.setEthereumGenesis(genesis);
            Node node = Geth.newNode(dataDir, nodeConfig); //Your Datadirectory
            node.start(); // Check Android Logs if node starts correctly

            NewHeadHandler handler = new NewHeadHandler() {
                @Override
                public void onError(String error) {
                }

                @Override
                public void onNewHead(final Header header) {
                    MainActivity.this.runOnUiThread(new Runnable() {
                        public void run() {
                            mTextMessage2.append("#" + header.getNumber() + ": " + header.getHash().getHex().substring(0, 10) + "…\n");
                        }
                    });
                }
            };

            Context ctx = Geth.newContext();
            EthereumClient ec = node.getEthereumClient();
            ec.subscribeNewHead(ctx, handler, 16);

#### Backtrace
Nothing happens
````

**Comment by intizarabe** [comment]
All connection and email problems were caused by virus resolved after
factory install. I am really confused on bitcoin and ethereum block
matters, it is not easy to understand such complicated matter. Sorry for
off topic

**Comment by ArthurTavaresBezerra** [comment]
I guess that you don't get (understand) my issue.
My Issue is that my node in android don't connect with my private network ( nodes on my pc ). 
Just it.

**Comment by TheRealDannz0r** [comment]
You need to manually add your android device (enode://mobile_enode@localIP:generatedPort). It does not connect automatically (yet at least).

If this doesn't work, please tell me what kind of steps you have taken.

**Comment by ArthurTavaresBezerra** [comment]
I believe that I already to do it, I'm using the code below that it add a node in nodeConfig .

How to do it manually ? 


   Enode enode = new Enode("enode://66a19741686a0f845e8ebf5f29ae85bbfe04d5f62819918acdb8f5ff427de04fc93d6417419df26e7810d8cbef8d026c27cba769d316d73023c91141afae443f" +
                "@192.168.15.6:30303");
        Enodes enodes = new Enodes();
        enodes.append(enode);
        nodeConfig.setBootstrapNodes(enodes);

**Comment by ArthurTavaresBezerra** [comment]
I undestand, but in my testes, I did it. On my geth in MacOs, i executed "addPeer("enode://id@ip:port")". 
The same way that Im doing whit my others node in MacOs and PC. 

So, based on your answer, I understood that I have to connect in two way, in my android with  "nodeConfig.setBootstrapNodes(enodes)" and my Geth node on MacOs with "addPeer("enode://id@ip:port") ?

**Comment by jebek29** [comment]
Ok

**Comment by ArthurTavaresBezerra** [comment]
@TheRealDannz0r, about answer of 10 days ago,  I need to execute AddPeer in my node "Server" ? 

But I have a private net, therefore, im using a bootnode and after Im starting my nodes referencing my bootnode, therefore, I don't have the "server node" ?

Do you could show me your function or code that you execute on your "server" ?

**Comment by TheRealDannz0r** [comment]
@ArthurTavaresBezerra The code to 'start' my server is just `geth --datadir <path> --networkid <id> --port 30303 --maxpeers 10 --rpc --rpcport <port> --lightserv 90 --rpcaddr 0.0.0.0 [all] --rpcapi personal,db,eth,net,web3 console`. Then I use the code above to add and such.

I don't use bootnodes so I cannot help you with that.

**Comment by ArthurTavaresBezerra** [comment]
Thanks, but all of your examples is like I do. I did that.

**Comment by mizo2go** [comment]
hello guys, i have the same problem which is i can't connect my android node to my private node on pc although i've followed all the steps. On android i use bootstrap node with my pc node url and on my pc i use the command admin.addPeer("my android node url")  which then outputs true but when i type admin.peers i have an empty array []. Any help please? Thanks in advance :)

**Comment by mizo2go** [comment]
> hello guys, i have the same problem which is i can't connect my android node to my private node on pc although i've followed all the steps. On android i use bootstrap node with my pc node url and on my pc i use the command admin.addPeer("my android node url") which then outputs true but when i type admin.peers i have an empty array []. There's one issue that i want to mention but i'm not sure if this what's causing the problem which is the android enode url doesn't have an ip address, it looks like this:
> "enode://c645656c05aaf56e340ed139f743f91441003953e3387b2681061396df1766e17feeb3c7012e7d036ddc65b0766cf731d29feca92ac9f3a5713b3bde042cd25b@[::]:58471?discport=0"
> Any help please? Thanks in advance :)

It's working now, i wasn't using the right command to start my geth node on pc, it was missing: `--rpcaddr 0.0.0.0 --rpccorsdomain "*" --nat extip<my ip>`
