### ISSUE TITLE
private chain mining stuck in Submitted transaction

### ISSUE THREAD

**Issue by guoxingx** [ethereum/go-ethereum#16684]
I run a private chain in single core vps with docker, it works fine util transaction submit.

it's not about the difficulty, few second for mining a new empty block, cpu usage almost 100%;
but when transaction submitted, mining stucked for about 10 minutes, cpu usage less than 5%;
use web3.py interface.

![https://i.stack.imgur.com/Svjxk.png](https://i.stack.imgur.com/Svjxk.png)

#### System information

Geth version: `docker image ethereum/client-go   latest`
OS & Version: ubuntu16.04 1cpu 2g ram
web3.py version: 4.2.0

#### Expected behaviour
mining normally, seconds for a new block

#### Actual behaviour
stuck in `Submitted transaction                    fullhash=0x...`

#### Steps to reproduce the behaviour
run private chain in single core vps with docker, web3.py, start mining, send transaction.

what is the problem? does this means it's impossible to run a private chain and mining in a single core vps?

**Comment by karalabe** [comment]
That's a bit funky. Do you have the code that you ran? Might help repro the issue.

There should most definitely be no issues in running a private chain on tiny machines.

**Comment by rustyx** [comment]
What's the output of `txpool.inspect`?
