### ISSUE TITLE
debug_traceBlockByHash returns error

### ISSUE THREAD

**Issue by JacobDenver007** [ethereum/go-ethereum#16693]
I used this  debug_traceBlockByHash but returned error, the block number is 916647:
![image](https://user-images.githubusercontent.com/29848184/39702255-b9e0cea6-5236-11e8-906c-cadf028ac4ac.png)

However, debug_traceTransaction is fine

**Comment by karalabe** [comment]
Hmm, I'll need to reassemble a chain for myself to look into this closer.

**Comment by CruiseMan** [comment]
Also mentioned here `insufficient balance to pay for gas` https://ethereum.stackexchange.com/questions/52186/debug-tracetransaction-returns-insufficient-balance-to-pay-for-gas

**Comment by CruiseMan** [comment]
@holiman What do you mean by `wrong gasprices` ?.

**Comment by Eric-Showers** [comment]
Hi just encountered this error while tracing block 916647 as well.

Request:
{ "jsonrpc": "2.0", "method": "debug_traceBlockByNumber", "params": [ "0xDFCA7", { "tracer": "callTracer" } ], "id": 74 }
Response:
{ "jsonrpc": "2.0", "id": 74, "error": { "code": -32000, "message": "insufficient balance to pay for gas" } }

What is most interesting however, is that of the 3 transactions in this block Geth is still able to trace two of them properly. The following two tx hashes return a normal response from debug_traceTransaction:
0x44e4f29f592e42cd1a104dc7347c02c78ac7a66be6e42005d2ad32f7b4f63218
0x4a5718d38238e2674208b0f0b95a6016ffe2b3002d11b464eaffefad79cf1c08

Here is the problematic tx in the block:
Request:
{ "jsonrpc": "2.0", "method": "debug_traceTransaction", "params": [ "0xca879fcf2d0146fc4e214ed5d9747a2743b6a586b4f1de1541e52c2fe6be5bad", { "tracer": "callTracer" } ], "id": 74 }
Response:
{ "jsonrpc": "2.0", "id": 74, "error": { "code": -32000, "message": "tracing failed: insufficient balance to pay for gas" } }

**Comment by Eric-Showers** [comment]
This is also being discussed in #17590
