### ISSUE TITLE
txpool not synced on private chain?

### ISSUE THREAD

**Issue by rustyx** [ethereum/go-ethereum#16695]
#### System information

Geth version: `v1.8.3-stable-329ac18e/windows-amd64/go1.10`
OS & Version: Windows 10 x64

#### Expected behaviour

I have a local test setup with a private PoA chain (Clique) consisting of 3 Geth nodes, of which 2 are miners and 1 non-miner.

I noticed that even though the nodes are connected, pending transactions are never synchronized with other nodes.

Consequently, on a non-miner, submitted transactions never make it to the blocks.

#### Actual behaviour

Transaction should be synced with a miner, which should seal them into a block.

#### Steps to reproduce the behaviour

Node1:
`geth --identity node1 --datadir node1/ --syncmode full --port 30304 --rpc --rpcport 8545 --bootnodes "enode://c0f96309ca5918bd0de1b69a0f062a590c7877681d7d69a370f3174cc3f137f200e024e86482ed3718c074a4d70488e09b7ff154dc5210ee0e890773646a25d8@127.0.0.1:30304" --nat none --networkid 2640 --gasprice 1 -unlock 0xe148888d6a894101a39b84da4d5f24c97f0ba3bd --password node1/password.txt --mine console`

Node2:
`geth --identity node2 --datadir node2/ --syncmode full --port 30305 --rpc --rpcport 8555 --ipcdisable --bootnodes "enode://c0f96309ca5918bd0de1b69a0f062a590c7877681d7d69a370f3174cc3f137f200e024e86482ed3718c074a4d70488e09b7ff154dc5210ee0e890773646a25d8@127.0.0.1:30304" --nat none --networkid 2640 --gasprice 1 -unlock 0x9d6189a2082a9df61d432cf384cb1f606cea1528 --password node2/password.txt --mine console`

Node3:
`geth --identity node3 --datadir node3/ --syncmode full --port 30306 --rpc --rpcport 8556 --ipcdisable --bootnodes "enode://c0f96309ca5918bd0de1b69a0f062a590c7877681d7d69a370f3174cc3f137f200e024e86482ed3718c074a4d70488e09b7ff154dc5210ee0e890773646a25d8@127.0.0.1:30304" --nat none --networkid 2640 --gasprice 1 -unlock 0xd134a62fb3d349c8ba2991dfba48e091544a8a13 --password node3/password.txt console`

On Node3 submit a transaction:

    > personal.sendTransaction({from:'0xd134a62fb3d349c8ba2991dfba48e091544a8a13', to:'0xE0ca7d355F0CC6C1EECDA7Ce081353b7D87Aa1d7', value: 1},'redacted')

It remains in "pending" state forever:

    > txpool.inspect
    {
      pending: {
        0xD134A62fB3D349c8ba2991dFbA48E091544A8a13: {
          0: "0xE0ca7d355F0CC6C1EECDA7Ce081353b7D87Aa1d7: 1 wei + 90000 gas × 0 wei"
        }
      },
      queued: {}
    }

Meanwhile, empty blocks keep on coming in:

```
INFO [05-07|14:31:42] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=0s      mgasps=NaN   number=2375 hash=8271c9…543b5e cache=0.00B
INFO [05-07|14:31:47] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=0s      mgasps=NaN   number=2376 hash=9442d8…b5b467 cache=0.00B
INFO [05-07|14:31:52] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=0s      mgasps=NaN   number=2377 hash=611ee5…02ba2e cache=0.00B
```

**Comment by karalabe** [comment]
You specified a gas price of 0. Those transactions don't get propagated through the network.

**Comment by rustyx** [comment]
I live, I learn.

Thanks, it is working now.
