### ISSUE TITLE
In windows10, geth can not run normally.

### ISSUE THREAD

**Issue by G-zhanghao** [ethereum/go-ethereum#16704]
INFO [05-08|10:02:49] Loaded local transaction journal         transactions=0 dropped=0
INFO [05-08|10:02:49] Regenerated local transaction journal    transactions=0 accounts=0
INFO [05-08|10:02:49] Starting P2P networking 

Program block here.

**Comment by G-zhanghao** [comment]
block at this （p2p/server.go）
go nat.Map(srv.NAT, srv.quit, "udp", realaddr.Port, realaddr.Port, "ethereum discovery")

**Comment by adamschmideg** [comment]
Can you give more information please, such as logs, the command line parameters you're using, your Geth version.

**Comment by adamschmideg** [comment]
I'm closing this as we have not enough information. Please reopen it if you can provide us with more details (logs, command line parameters, etc)
