### ISSUE TITLE
Error while install the go-ethereum on centOS 7

### ISSUE THREAD

**Issue by don2ccc** [ethereum/go-ethereum#16707]
Hi there,

While try install the 1.8 version geth on CentOS 7, it blocks me at below error:

```
build/env.sh go run build/ci.go install ./cmd/geth
>>> /root/golang/go/bin/go install -ldflags -X
main.gitCommit=d2fe83dc5c0b32dfbe45e77817478e06f928ff8a -v ./cmd/geth
github.com/ethereum/go-ethereum/crypto/secp256k1
# github.com/ethereum/go-ethereum/crypto/secp256k1
In file included from ././libsecp256k1/src/secp256k1.c:9:0,
                 from crypto/secp256k1/secp256.go:29:
././libsecp256k1/src/util.h:14:20: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
                    ^
compilation terminated.
```

gcc, g++ installed. 

Any suggestions?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
