### ISSUE TITLE
How to get the balance in sealer.go

### ISSUE THREAD

**Issue by JsxddXJ** [ethereum/go-ethereum#16705]
I want to revise the target in sealer.go according to the value of balance. However, I don't know how to get the balance in sealer.go . My teacher said that just a few codes would be added but I don't know. I hope  someone could tell me . Thank you!

**Comment by karalabe** [comment]
You could extend the `ChainReader` with a method to retrieve the StateDB. Then you'd have access to everything you need.

**Comment by JsxddXJ** [comment]
Could you tell me how to operate concretely ? Because I just start to learn GO, I am not familiar with it. However, I have to submit my task in a few days . If you could help me, I will thanks a lot .
