### ISSUE TITLE
eth_submitHashrate rpc issue

### ISSUE THREAD

**Issue by Root-man** [ethereum/go-ethereum#1671]
Hello,
Recent changes (#1596 and #2740 from cpp-ethereum) were supposed to allow ethminer to send its hashrate to geth. However, using ethminer 0.9.41 and geth build from go-ethereum/developer connection miner-geth cannot be established since each rpc submitHashrate will fail because "could not decode, invalid type on field hash: not a string". As I understand function
```
func (args *SubmitHashRateArgs) UnmarshalJSON(b []byte) (err error) {
```
from rpc/api/eth_args.go is supposed to handle this rpc. I'm not a go programmer myself, and I cannot fix this.

**Comment by LefterisJP** [comment]
Same issue as the one in ethminer: https://github.com/ethereum/cpp-ethereum/issues/2842

Explanation of what happened can be seen [here](https://github.com/ethereum/cpp-ethereum/issues/2842#issuecomment-131766970)

**Comment by FinalHash** [comment]
Yeah can we fix this. I have no clue if i am mining properly here. Also, seems like ethminer is not controlling the fan speed properly. When can we get this.

**Comment by obscuren** [comment]
@FinalHash open an issue for that separately on the C++ / ethminer. Your request will get lost here. 

AFAIK this has been addressed and fixed on the C++ side. I'm closing this issue

**Comment by LefterisJP** [comment]
As long as GO follows the [spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_submithashrate) to the function this issue can be closed. If not please make necessary changes. Note, it returns `true` and not `null` and also note the order of parameters.

**Comment by obscuren** [comment]
@LefterisJP Yes, it implements the modified spec and returns true or false depending on succession

**Comment by LefterisJP** [comment]
Great. Should be working then. Will test it myself soon.
