### ISSUE TITLE
[question/feature request] How to disable/select EVM?

### ISSUE THREAD

**Issue by paulvi** [ethereum/go-ethereum#16714]
How to disable/select EVM?

`geth help` has only one EVM-related option:

```
VIRTUAL MACHINE OPTIONS:
  --vmdebug  Record information useful for VM and contract debugging
```

**Comment by paulvi** [comment]
OK, how to disable it e.g. in private network?

**Comment by karalabe** [comment]
I don't understand what you want to do.

The EVM is the Ethereum Virtual Machine, that's the thing that is running all the contract codes. You can't disable it. That **is** Ethereum.

**Comment by paulvi** [comment]
For private network if there are no contracts, it is just overhead that requires some memory, start-up time and CPU usage.

I perfectly understand that for mainnet it is highly undesirable when specific node could opt-out of executing EVM code. But in context of private network it may be just distraction (I cannot think yet of a case when it is undesirable )

Anyways, I thought to raise a ticket, to see if more people would be interested and could vote such option.

Also before there were other than Solidity languages, hopefully will be others.

**Comment by karalabe** [comment]
The EVM doesn't run if there's no code associated with the recipient of a transaction. 

As for Solidity, all languages compile down to EVM bytecode and that's what is executed. You can have arbitrary higher level languages all run by the same EVM.
