### ISSUE TITLE
Why I Can't mine on remix using my private network?

### ISSUE THREAD

**Issue by Ashley07** [ethereum/go-ethereum#16724]
Hi there,

Screen shot : https://imgur.com/a/gRPeJz0

I've created a private network all fine but when I attache and miner.start(1); the kh/s show in Mist but I keep waiting and no ether got mine not a single one!!!

https://codeshare.io/GqxZ3Z this is the code of the first command line where I start geth

https://codeshare.io/2pgZYX this is the second terminal where I start mining command

thanks guys

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by Ashley07** [comment]
Please help if you can on this link: https://ethereum.stackexchange.com/q/48050/39465
