### ISSUE TITLE
My SmartContract can not store my array of struct but I can store only uint32 in my private node

### ISSUE THREAD

**Issue by ArthurTavaresBezerra** [ethereum/go-ethereum#16723]
My SmartContract can not store my array of struct but I can store only uint32.

Im using a private node on my Mac, I code and test my smart contract in remix.ethrereum.org and get success in everything but when execute in my private node on my Mac just the data isn't stored. 

I have read about it and see that the blockchain only store data until 32 bytes but I did several tests with uint32 and bytes32 and I get success only uint32. 

But I need to store my array of structs or at least bytes64 because of Id of my processes. 

My SmartContract below.

pragma solidity ^0.4.23;
 
contract Votacao {
   
    struct Voto { 
        uint uf;
        uint cmun;
        string idCandidato;
        uint256 voteCount; 
    } 
    
    struct Candidato {
        string id; 
        uint uf;
        uint cmun;
        uint256 voteCount;
    }
    
    struct BU {
        string id;
        Voto[] votos;
    }
     
    Candidato[] public candidatos ;
    mapping(string => BU) bus; 

    function vote(string pidBu, string pidCandidato, uint puf, uint pcmun, uint256 pvoteCount) public  {

        if (strIsEmpty(bus[pidBu].id)){
            bus[pidBu].id = pidBu;
        }
        
        bool isJaFoiVotado = false;
        for (uint i = 0; i < bus[pidBu].votos.length; i++) {
            if (strCompare(bus[pidBu].votos[i].idCandidato,pidCandidato) == 0) {
                if (bus[pidBu].votos[i].uf == puf && bus[pidBu].votos[i].cmun == pcmun) {
                    isJaFoiVotado = true;
                    break;
                }
            }
        }
        
        require(!isJaFoiVotado, "Apenas um voto é permitido.");
        
        bus[pidBu].votos.push(Voto({uf:puf, cmun:pcmun, idCandidato:pidCandidato, voteCount:pvoteCount}));

        bool isCandidatoInserido = false;
        for (uint j = 0; j < candidatos.length; j++) {
            if (strCompare(candidatos[j].id,pidCandidato) == 0 && candidatos[j].uf == puf && candidatos[j].cmun == pcmun)
            {
                candidatos[j].voteCount += pvoteCount;
                isCandidatoInserido = true;
            }
        }
        
        if (!isCandidatoInserido) {
            candidatos.push(Candidato({id:pidCandidato, uf:puf, cmun:pcmun, voteCount:pvoteCount }));
        }
    }
  
    function getTotalVotosPorCandidato(string pidCandidato, uint puf, uint pcmun) public view returns (uint256 total, uint256 count)
    {
        for (uint j = 0; j < candidatos.length; j++) {
            if (strCompare(candidatos[j].id, pidCandidato) == 0 && candidatos[j].uf == puf && candidatos[j].cmun == pcmun)
            {
                total = candidatos[j].voteCount;
            }
        }
    } 
  
    function getTotalCandidatos() public view returns (uint256 total)
    {
        return candidatos.length;
    }
    
    function strCompare(string _a, string _b) internal pure returns (int) {
        bytes memory a = bytes(_a);
        bytes memory b = bytes(_b);
        uint minLength = a.length;
        if (b.length < minLength) minLength = b.length;
        for (uint i = 0; i < minLength; i ++)
            if (a[i] < b[i])
                return -1;
            else if (a[i] > b[i])
        return 1;
        if (a.length < b.length)
            return -1;
        else if (a.length > b.length)
            return 1;
        else
            return 0;
    }
     
    function strIsEmpty(string _a) internal pure returns (bool) {
        bytes memory a = bytes(_a);
        return (a.length == 0); 
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////Basics tests 
    function inc() public returns (uint) {
        Candidato memory candidato = Candidato("c1",1,1,1);
        candidatos.push(candidato);
        return candidatos.length;
    }

    function get() public view returns (uint) { 
        return candidatos.length;
    }

}

Geth version: `1.8.4`
OS & Version:OSX
Commit hash : 

#### Expected behaviour
Only store data.

#### Actual behaviour
No stored data

#### Steps to reproduce the behaviour
After deploy smartContract exec vote ("b","c",1,2,3) and exec getTotalCandidatos() 
or inc() and get()

#### Backtrace
nothing wrong
````
[backtrace]
````

**Comment by karalabe** [comment]
@Arachnid Could you skim this issue to see if it's a bug in the Solidity code or whether it's something we do internally?
