### ISSUE TITLE
Faucet offline: context deadline exceeded

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#16721]
happens without user interaction - just open the site:

![selection_049](https://user-images.githubusercontent.com/111600/39863189-3ed30da2-5446-11e8-9c5b-139924fc6c61.png)

**Comment by karalabe** [comment]
I've restarted the faucet, seems to work-ish now, but it has trouble finding a stable server list.

**Comment by bhandarikaran** [comment]
I'm also facing the same issue.

**Comment by Anik25** [comment]
I am facing the same problem. Tried different browsers from different devices.

**Comment by pikejun** [comment]
Sept Fri 21 same  "Faucet offline: context deadline exceeded"
