### ISSUE TITLE
when  I use eth_sign generate signer, then I cerate transactions WithSignature,but final I sendRawTransactions answer "insufficient funds for gas * price + value"

### ISSUE THREAD

**Issue by qq940043871** [ethereum/go-ethereum#16747]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.8.3`
OS & Version: Windows
Commit hash : (if `develop`)

#### Expected behaviour
send_rawTransaciton success

#### Actual behaviour
insufficient funds for gas * price + value

#### Steps to reproduce the behaviour
first:create transaction
second:get eth_sign 
        r = new(big.Int).SetBytes(sig[:32])
	s = new(big.Int).SetBytes(sig[32:64])
	v = new(big.Int).SetBytes([]byte{sig[64] + 27})
thres: send_rawTransaciton:
        answer "insufficient funds for gas * price + value"

when i use rlpdump,i can,t get the correct fromAddr

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
cab you please add the raw transaction here?

**Comment by qq940043871** [comment]
1. create private network from genesis
```javascript
{
  "config": {
        "chainId": 10,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
  "alloc"      : {},
  "coinbase"   : "0x0000000000000000000000000000000000000000",
  "difficulty" : "0x02000",
  "extraData"  : "",
  "gasLimit"   : "0x2fefd8",
  "nonce"      : "0x0000000000000042",
  "mixhash"    : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp"  : "0x00"
}

```
2. start geth from config.toml console
```
# Note: this config doesn't contain the genesis block.

[Eth]
NetworkId = 2018
SyncMode = "full"
LightPeers = 100
DatabaseCache = 768
GasPrice = 18000000000
EnablePreimageRecording = false

[Eth.Ethash]
CacheDir = "ethash"
CachesInMem = 2
CachesOnDisk = 3
DatasetDir = "D://walletPeer//ETH//Geth//.ethash"
DatasetsInMem = 1
DatasetsOnDisk = 2
PowMode = 0

[Eth.TxPool]
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Shh]
MaxMessageSize = 1048576
MinimumAcceptedPOW = 2e-01

[Node]
DataDir = "D://walletPeer//ETH//Geth//gethblock"
IPCPath = "geth.ipc"
HTTPHost = "localhost"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["db", "eth", "net", "web3", "personal", "admin", "miner"]
WSPort = 8080
WSModules = ["net", "web3", "eth", "shh"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = true
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false

[Dashboard]
Host = "localhost"
Port = 8080
Refresh = 5000000000

```
3. personal.newAddress('haswhere');
```java
String fromAddr ="0x6a81822d75a827fee418e8bae563f8da7d3d6fcf";
	String toAddr = "0x899bf23c235ffa1daaa735cc5443b2a7ef068973";
```
4. four: miner.start(2) generate 5 block

5. five: I # programming use web3j of java
```java
@Test
	public void createRawTx() throws Exception {
		BigInteger value = Convert.toWei("1", Convert.Unit.ETHER).toBigInteger();
		BigInteger nonce = web3j.ethGetTransactionCount(fromAddr, DefaultBlockParameterName.PENDING).send().getTransactionCount();
		Transaction tx = Transaction.createEtherTransaction(fromAddr,nonce, BigInteger.valueOf(1800000000), BigInteger.valueOf(1000000), toAddr, value);
		// 7.创建交易并转化为16进制
		RawTransaction rawTransaction = RawTransaction.createEtherTransaction(nonce, BigInteger.valueOf(1800000000), BigInteger.valueOf(1000000), toAddr, value);
		byte[] encoded = TransactionEncoder.encode(rawTransaction);
		String hex = Numeric.toHexString(encoded);
		System.out.println("hex:" + hex);
	}
```
```java
@Test
	public void eth_sign() throws Exception {
		String hex ="0xe980846b49d200830f424094899bf23c235ffa1daaa735cc5443b2a7ef068973880de0b6b3a764000080";
		boolean unlock = admin.personalUnlockAccount(fromAddr, "haswhere").send().accountUnlocked();
		System.out.println("Hash.sha3String(hex):"+Hash.sha3String(hex));
		EthSign ethSign = web3j.ethSign(fromAddr, Hash.sha3String(hex)).send();
		String signatureData = ethSign.getSignature();
		System.out.println("signatureData:"+signatureData);
		byte[] signByte = Numeric.hexStringToByteArray(signatureData);
		BigInteger R = Numeric.toBigInt(signByte, 0, 32);
		BigInteger S = Numeric.toBigInt(signByte, 32, 32);
		BigInteger V = Numeric.toBigInt(signByte, 64, 1);
		RlpList rlpList = RlpDecoder.decode(Numeric.hexStringToByteArray(hex));
		RlpList rlpValues = (RlpList) rlpList.getValues().get(0);
		List<RlpType> values = rlpValues.getValues();
		System.out.println("values.size:"+values.size());
		if (signatureData != null) {
			values.add(RlpString.create(V));
			values.add(RlpString.create(Bytes.trimLeadingZeroes(R.toByteArray())));
			values.add(RlpString.create(Bytes.trimLeadingZeroes(S.toByteArray())));
		}
		String signTx = Numeric.toHexString(RlpEncoder.encode(new RlpList(values)));
		System.out.println("signTx:"+signTx);
	}
```

    @Test
    	public void eth_sendRawTx() throws Exception {
    		String signData="0xf86c80846b49d200830f424094899bf23c235ffa1daaa735cc5443b2a7ef068973880de0b6b3a7640000801ca0bd5fda7f57b6392752045b0b37dc51ea7643de9edc71de80912e267897aab8a1a0423b972540992ab40189340f3fe1b99cea3c23d9727649150fdd604efa030246";
    		EthSendTransaction ethSendTransaction = web3j.ethSendRawTransaction(signData).send();
    		if(ethSendTransaction.hasError()){
    			System.out.println(ethSendTransaction.getError().getMessage());
    		}else{
    			System.out.println(ethSendTransaction.getTransactionHash());
    		}
    	}

6. Above result is # "insufficient funds for gas * price + value":but when use the eth_sendTx(),is works well.
    @Test
    	public void eth_sendTx() throws Exception {
    		boolean unlock = admin.personalUnlockAccount(fromAddr, "haswhere").send().accountUnlocked();
    		BigInteger value = Convert.toWei("1", Convert.Unit.ETHER).toBigInteger();
    		BigInteger nonce = web3j.ethGetTransactionCount(fromAddr, DefaultBlockParameterName.PENDING).sendAsync().get().getTransactionCount();
    		Transaction transaction = Transaction.createEtherTransaction(fromAddr, nonce, BigInteger.valueOf(1800000000), BigInteger.valueOf(1000000), toAddr, value);
    		EthSendTransaction ethSendTransaction = web3j.ethSendTransaction(transaction).send();
    		if(ethSendTransaction.hasError()){
    			System.out.println(ethSendTransaction.getError().getMessage());
    		}else{
    			System.out.println(ethSendTransaction.getTransactionHash());
    		}
    	}
7. now I don't know What caused the problem? is web3j or eth_sign,eth_sendRawTx is different from eth_sendTx

Thankyou very much!

**Comment by qq940043871** [comment]
8.the # constructor of RawTransaction and Transaction
```java
 public Transaction(String from, BigInteger nonce, BigInteger gasPrice, BigInteger gasLimit,
                       String to, BigInteger value, String data) {
        this.from = from;
        this.to = to;
        this.gas = gasLimit;
        this.gasPrice = gasPrice;
        this.value = value;

        if (data != null) {
            this.data = Numeric.prependHexPrefix(data);
        }

        this.nonce = nonce;
    }

 private RawTransaction(BigInteger nonce, BigInteger gasPrice, BigInteger gasLimit, String to,
                           BigInteger value, String data) {
        this.nonce = nonce;
        this.gasPrice = gasPrice;
        this.gasLimit = gasLimit;
        this.to = to;
        this.value = value;

        if (data != null) {
            this.data = Numeric.cleanHexPrefix(data);
        }
    }
```

**Comment by karalabe** [comment]
Why did you modify the signature?

```
v = new(big.Int).SetBytes([]byte{sig[64] + 27})
```

**Comment by qq940043871** [comment]
I don't change the code, it is the code  /src/github.com/ethereum/go-ethereum/core/types/transaction_signing.go    func recoverPlain(sighash common.Hash, R, S, Vb *big.Int, homestead bool) (common.Address, error) {}

**Comment by qq940043871** [comment]
I change the geth code:fmt.Printf("%v\n", tx)
the correct tx:
`&{{0 0x13047dc0 1000000 0x12f9e540 0x13047d90 [] 0x13047ef0 0x13047ec0 0x13047ed0 <nil>} {{} <nil>} {{} <nil>} {{} 
<nil>}}9572a2b721c3a6ed1d5edfcebdb6ddd0164608bbf76c26a3111421c728cea75d7a2c8d29654401e90e5287c667428a6d1268e5cf67f4cd31123025b16d3e570001
f97a214da52ede8f5632a29f03e81b640dac16c240cc60e701ce0e5fb616b918`

the wrong tx:
`&{{0 0x12f92370 1000000 0x12fda200 0x12f92390 [] 0x12f923a0 0x12f923f0 0x12f92410 <nil>} {{} <nil>} {{} 110} {{} <nil>}}bd5fda7f57b6392752045b0b37dc51ea7643de9edc71de80912e267897aab8a1423b972540992ab40189340f3fe1b99cea3c23d9727649150fdd604efa03024601
64ef875f722486f943a36d8f164231fe8ae2126d3afc5dcc46fc9416bceed1da`

**Comment by qq940043871** [comment]
thank you , @karalabe @ligi

**Comment by bsvfans** [comment]
Hello, I am very interested in this, is this method successfully implemented?
