### ISSUE TITLE
go 1.10 util.go:45: exit status 1 

### ISSUE THREAD

**Issue by quanjin9099** [ethereum/go-ethereum#16742]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.5.1804 (Core) 
Release:        7.5.1804
Codename:       Core

go version go1.10 linux/amd64

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

yum update -y && yum install git wget bzip2 vim gcc-c++ ntp epel-release nodejs cmake -y
wget https://dl.google.com/go/go1.10.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.10.linux-amd64.tar.gz
echo 'export GOROOT=/usr/local/go' >> /etc/profile  
echo 'export PATH=$PATH:$GOROOT/bin' >> /etc/profile  
echo 'export GOPATH=/root/go' >> /etc/profile
echo 'export PATH=$PATH:$GOPATH/bin' >> /etc/profile
source /etc/profile

git clone https://github.com/ethereum/go-ethereum.git  
cd go-ethereum  

[root@iZ2ze3fdhfs9lqpauz494zZ go-ethereum]# make geth

build/env.sh go run build/ci.go install ./cmd/geth
>>> /usr/local/go/bin/go install -ldflags -X main.gitCommit=f6bc65fc681177b190522c92887979690f9ceefa -v ./cmd/geth
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
util.go:45: exit status 1
exit status 1
make: *** [geth] Error 1

**Comment by Jagdish0886** [comment]
I got the same error any solution please?

**Comment by Jagdish0886** [comment]
installation of gcc has solved the problem

**Comment by gballet** [comment]
I confirm @Jagdish0886 's diagnostic,the problem is that you didn't install `gcc`. For reference, this is the `Dockerfile` that I used to build `geth` with your configuration:

```
FROM centos

RUN yum install -y wget git make gcc && wget https://dl.google.com/go/go1.12.6.linux-amd64.tar.gz
RUN tar xfz go1.12.6.linux-amd64.tar.gz -C /usr/local
RUN echo 'export GOROOT=/usr/local/go' >> /etc/profile
RUN echo 'export PATH=$PATH:$GOROOT/bin' >> /etc/profile
RUN echo 'export GOPATH=/root/go' >> /etc/profile
RUN echo 'export PATH=$PATH:$GOPATH/bin' >> /etc/profile

CMD bash
```
