### ISSUE TITLE
cmd/abigen: support for generating ObjC/Swift bindings

### ISSUE THREAD

**Issue by sunlijun** [ethereum/go-ethereum#16748]
abigen does not support Swift/ObjC at this time. It would be nice
to add support for it in https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/template.go

**Comment by gballet** [comment]
Yeah the template is missing. I had a PR to remove any mention to this so that users don't get confused but it won't be merged. The "easiest" way out is to write the objc template, and for that we need someone with a mac. @fjl :D ?

**Comment by holiman** [comment]
I think this feature is not top priority. If someone submits a PR to address it, we'll see, but in the meantime let's let this ticket rest.
