### ISSUE TITLE
gas calc error?

### ISSUE THREAD

**Issue by jjnetcn** [ethereum/go-ethereum#16763]
i send two transactions:
https://etherscan.io/tx/0x77c5a32108ed81ae9362747c672f72a66aa5e29bf3316f754e4da420589904a8
https://etherscan.io/tx/0xd913e13174fa3aa210385956b167a9bd93018287d9eda21647dd14a748719f33
the second transactions same as the one except the gas limit change from 40700 to 40800.

the second success but the first failed of 'out of gas',
in the fact, the gas in this transactions if fix value 25734,  why first emit out of gas?
i try many times, if set gas limit > 40800 will success, and < 40700 it fails.
when success, all the actual gas is 25734.

**Comment by rjl493456442** [comment]
@jjnetcn I trace the two transactions you given by `gethTracer`,  the reason for the used gas is 25734 of the second transaction is **there is a sstore refund after the transaction execution**. The refund gas is 15000.

Just out of curiosity, what is the estimated gas number?

**Comment by jjnetcn** [comment]
thanks， where is the tool gethTracer?

**Comment by rjl493456442** [comment]
Here is the relative [link](https://etherscan.io/vmtrace?txhash=0xd913e13174fa3aa210385956b167a9bd93018287d9eda21647dd14a748719f33). It has been integrated in the etherscan.

**Comment by jjnetcn** [comment]
根据这个链接， 我看了一下gas的计算方式，  显示刚开始17736， 最后经过了496步结束之后还有66，
这里跟参数里面的gas总量40800和使用的25734是如何一个对应关系？ 那个15000的返还是怎么得到的， 多谢。

**Comment by rjl493456442** [comment]
Because we will prepay some gas before execution https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L193 and refund the gas if your contract state is cleaned. https://github.com/ethereum/go-ethereum/blob/master/core/vm/gas_table.go#L132
