### ISSUE TITLE
[Android] Transaction call resulting in lack of gas error ("insufficient funds for [..]")

### ISSUE THREAD

**Issue by therealdannzor** [ethereum/go-ethereum#16762]
Hi there,

With an Android client, I'm trying to send a transaction call to a (payable) contract to manipulate a **private blockchain** (light mode enabled). Ordinary calls to get information works as intended but it in this case when gas is involved, it just does not work. I have been struggling with this specific part for a week now, with many tries.

Also, somewhat related is that I for a month or so back managed to make a call that consumed gas (and thus I thought I had this issue resolved), but seems I cannot manage to replicate that. Unsure if it is a version thing or not. As of now, none of my transactions consume any gas. 

**Note 1)**: not trying to transfer funds between accounts
**Note 2)**: calling the function from the geth server works without any issue

#### System information

Geth version: `1.8.8-stable`
Server OS & Version: `macOS High Sierra 10.13.4`
Client device & OS: `Galaxy S6, OS: 7.0`
Android Studio version: `3.1.2`
Network: `LAN`

#### Expected behaviour
A successful transaction, gas consumed for changing the temporary state of the blockchain, and to observe a token created at the address in question (public address of android device).

#### Actual behaviour
`go.Universe$proxyerror: insufficient funds for gas * price + value`

#### Steps to reproduce the behaviour
1. Continuation of my previous issue #16420 (Wallet creation) with the same flags (and the standard procedure of starting private chain, adding light peer, and mining)
```
geth --datadir <path> --networkid <number_1> --port <number_2> --maxpeers 10 --rpcaddr 0.0.0.0 --rpc --rpcport <number_3> --targetgaslimit <very_high_number> -gasprice <high_number> --lightserv 50  --rpcapi personal,db,eth,net,web3 console
```

2. The standard mintable token function I'm attempting to call, after deploying it to the blockchain and subsequently adding the ABI and the contract address to my mobile application
```
    function pureSecretMint(string _str) public payable {
        MintableToken.mint(msg.sender, 1);
    }
```

3. When calling the function through `boundContract.transact(..)`, observe the error

![180520_txfailgas](https://user-images.githubusercontent.com/35889839/40276762-bcee77c0-5c12-11e8-950c-67ab3b21a95f.png)

#### Backtrace

````
E/GoLog: INFO [05-20|08:01:14] Imported new block headers               count=1  elapsed=124.996ms number=905 hash=5d2e4d…f46b75 ignored=0
W/System.err: go.Universe$proxyerror: insufficient funds for gas * price + value
W/System.err: at org.ethereum.geth.BoundContract.transact(Native Method)
W/System.err: at com.example.gitdannzor.lightclient.MainActivity$1.onNewHead(MainActivity.java:208) 
E/GoLog: INFO [05-20|08:01:17] Imported new block headers               count=1  elapsed=30.723ms  number=906 hash=7cd0a2…139e39 ignored=0
````

**An observation that confirms that there is enough balance**

The price seems to have increased however from what I set it to be. Then I guess the binary search algorithm works for finding a price.
```
D/Android:: tx.getGasPrice(): 18000000000, tx.getGas(): 70000000, tx.getCost(): 1260000000000000000
balance = {BigInt@5384} = 6400000000000000000000
```
Despite not a being value transaction, I have also confirmed that `tx.getValue(): 0`. Thus, in theory we can conclude that
```
gas * price + value < balance
``` 
#### Different attempts to solve the problem
1) Omit setting `DEFAULT_GAS_PRICE` and `DEFAULT_GAS_LIMIT` at all (and hope it calculates suitable gas by itself), but then I received the error `go.Universe$proxyerror: failed to estimate gas needed: gas required exceeds allowance or always failing transaction`. Discussed this issue briefly with @mcdee.

2) Set `DEFAULT_GAS_PRICE.setString("0", 10)`, resulting in a new error `Known transaction (abc123)`.

3) Just omit setting `DEFAULT_GAS_PRICE`. Same error as original thread start.

4) Adjusting the `DEFAULT_GAS_PRICE`, from 1 to *large number* in varying steps and sizes. Still same error.

5) Create new blockchains with varying gas prices and target gas limits. Same error.

6) Making sure that the chain ID is the same as the network ID (and not zero), as well as instead of `chainId` explicitly write `chainID` in the genesis. Same error.

7) Try other ways of signing the transaction (https://github.com/ethereum/go-ethereum/wiki/Mobile:-Account-management) from section "Signing on Android (Java)" and unlocking the account in varying ways (temporarily/permanent unlocks). Same error.

8) Naively tried with a `callOpts`, instead of `transactOpts`, and as a parameter used a string `{from: pubaddr, gas: 2500000}`, emulating the web3. Of course failed due to incorrect amount of parameters.

9) Try to fill the account with a significant balance (> 10,000 ETH), just to see if the error message goes away. 

10) For science, I tried to both alter the file **../core/tx_pool.go** and compile the library with `make android` to see if it was a mismatch with the `Cmp` function (which can return -1,0, or 1 depending on max{x,y}). It skips that error but instead shows `Known transaction`.

**Comment by TheRealDannz0r** [comment]
I find point 10) above very strange, that it still returns the very same error despite having the below code snippet commented out. AFAIK, I don't see it anywhere else in the go-ethereum library.

```
	// Transactor should have enough funds to cover the costs
	// cost == V + GP * GL
	if pool.currentState.GetBalance(from).Cmp(tx.Cost()) < 0 {
		return ErrInsufficientFunds
	}
```

**Comment by therealdannzor** [comment]
Still an issue on `1.8.11-SNAPSHOT`.

**Comment by mizo2go** [comment]
hi @therealdannzor , i have the same problem. Have you found the solution for it? Thanks in advance :)

**Comment by therealdannzor** [comment]
Hi @mizo2go, it's been a while since I touched this project but before authorising the transaction with _setSigner_ I added something like
```
long nonceTransaction = ec.getNonceAt(Geth.newContext(), firstAccount.getAddress(), -1);
transactOpts.setNonce(nonceTransaction);
```
Haven't worked with the new Geth versions within this domain since my last post.

**Comment by holiman** [comment]
One thing you can do, if you're recompiling anyway, is to modify the error message to spit out more detailed information. Instead of `ErrInsufficientFunds`, make it 
```golang
return fmt.Errorf("Insufficient balance, cost: %v, balance %v", tx.Cost(), currentState.GetBalance(from))
```
or something to that effect. 

Since this issue is rather old (sorry about not answering sooner), I'll close this for now. Feel free to open a new issue if this seems to still be happening
