### ISSUE TITLE
I think i found the reason why 'insufficient funds for gas * price + value'

### ISSUE THREAD

**Issue by qq940043871** [ethereum/go-ethereum#16761]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth 1.8.3`
OS & Version: Windows
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by qq940043871** [comment]
1. when  eth_sign **the signdata is  msg := fmt.Sprintf("\x19Ethereum Signed Message:\n%d%s",** len(data), data)
```go
func (s *PublicTransactionPoolAPI) Sign(addr common.Address, data hexutil.Bytes) (hexutil.Bytes, error) {
	// Look up the wallet containing the requested signer
	account := accounts.Account{Address: addr}
	wallet, err := s.b.AccountManager().Find(account)
	if err != nil {
		return nil, err
	}
	// Sign the requested hash with the wallet
	signature, err := wallet.SignHash(account, signHash(data))
	if err == nil {
		signature[64] += 27 // Transform V from 0/1 to 27/28 according to the yellow paper
	}
	return signature, err
}
```

```go
func signHash(data []byte) []byte {
	msg := fmt.Sprintf("\x19Ethereum Signed Message:\n%d%s", len(data), data)
	return crypto.Keccak256([]byte(msg))
}
```

2. but when  send_rawTransaciton----src/core/types/transaciton_signing.go,**the signdata is only the tx**
```go
func (hs HomesteadSigner) Sender(tx *Transaction) (common.Address, error) {
	return recoverPlain(hs.Hash(tx), tx.data.R, tx.data.S, tx.data.V, true)
}
```

```go
// Hash returns the hash to be signed by the sender.
// It does not uniquely identify the transaction.
func (fs FrontierSigner) Hash(tx *Transaction) common.Hash {
	fmt.Printf("Hash:")
	fmt.Printf("%+v\n", tx)
	return rlpHash([]interface{}{
		tx.data.AccountNonce,
		tx.data.Price,
		tx.data.GasLimit,
		tx.data.Recipient,
		tx.data.Amount,
		tx.data.Payload,
	})
}
```

3. because the signdata is different,so geth can't recover the corrent address through 
````go
func recoverPlain(sighash common.Hash, R, S, Vb *big.Int, homestead bool) (common.Address, error) {
	if Vb.BitLen() > 8 {
		return common.Address{}, ErrInvalidSig
	}
	V := byte(Vb.Uint64() - 27)
	//edit by zf 2018-05-19
	//V := byte(Vb.Uint64())
	if !crypto.ValidateSignatureValues(V, R, S, homestead) {
		return common.Address{}, ErrInvalidSig
	}
	// encode the snature in uncompressed format
	r, s := R.Bytes(), S.Bytes()
	sig := make([]byte, 65)
	copy(sig[32-len(r):32], r)
	copy(sig[64-len(s):64], s)
	sig[64] = V

	fmt.Print("sighash:")
	fmt.Printf("%x\n", sighash)

	fmt.Print("sig:")
	fmt.Printf("%x\n", sig)

	// recover the public key from the snature
	pub, err := crypto.Ecrecover(sighash[:], sig)
	if err != nil {
		return common.Address{}, err
	}
	if len(pub) == 0 || pub[0] != 4 {
		return common.Address{}, errors.New("invalid public key")
	}
	var addr common.Address
	copy(addr[:], crypto.Keccak256(pub[1:])[12:])
	fmt.Printf("%x\n", addr)
	return addr, nil
}
````

4. I need help，please，thank you

**Comment by ligi** [comment]
I think you are mixing up a lot of things here - e.g. using "Ethereum Signed Message:" should not be used for transactions. Also I am not really sure what exactly you want to do. E.g. why you are doing EIP155 signing by hand. Please let us know what exactly is your goal

**Comment by qq940043871** [comment]
**I want to create a transaction, then sign it, and finally broadcast it.** 
I want the cold and the hot wallet to separate, the cold wallet to keep the private key and signature, the hot wallet to create the transaction and the broadcast transaction.

**Comment by karalabe** [comment]
There are separate methods for signing  arbitrary data `eth_sign` and signing a transactions `eth_signTransaction`. Signing arbitrary data can be dangerous, hence why it dumps that junk in front. If you want to sign transactions, please use the correct API calls.
