### ISSUE TITLE
[feature request] getTransactionsOfAccount

### ISSUE THREAD

**Issue by paulvi** [ethereum/go-ethereum#16765]
Please implement (experimental) feature go get all transactions for an account.

Currently there is **getBalance** https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getbalance  
and **getTransactionCount** https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactioncount  
But to get full list of transaction for an account, one needs to read blocks one by one **getBlockByNumber**, and list and filter.
Traversing through blockchain is slow, but making filtering client-side is even slower and creates a lot of unneeded serialization into JSON, socket communication etc.

Experimental means that this API is subject to change,  
especially when becoming API for all ethereum clients, not only for `geth`

Other idea is having a generic way to add any filter to be executing server side.  
That is instead of having specific API, extend API with string having JS function for filtering
"`function (transaction){ if  (transaction.from = "someaddress" || transaction.to == "someaddress"} 
{ return true } else { return false} }`"

If such feature request should never be raised against geth, please point to exact place.

**Comment by karalabe** [comment]
How would you gather internal transactions with a fast synced node? This is the blocker issue.

**Comment by paulvi** [comment]
I don't really know what is "internal transactions with a fast synced node".  
I guess in fast synch mode not all transaction are physically present locally.
That would mean that regardless whether to read just one transaction by hash/txid 
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionbyhash or via this new proposed API, it will not be there, so it seems that is not really related.

If it is known (from state of storage) that fast synch mode was used, then user/application should do full synch before.
A request to get one transaction or a list of them, should fail quickly or return was is present with some warnings, but again this is matter of interaction style.  
For example, return JSON result may have range of blocks that are present and were scanned.

This issue is about convenient way to check account history.
 
The challenge I thought was that this request may be running for long time (several minutes from my tests),
so maybe there should be way to set timeout or some progress updates to let user/app know that the request is still executing. But I think it should be done after initial API itself.

There is expectation that when running within blockchain engine, the request will execute much much faster,
e.g. 10s for 1GB of data versus 10-30s for ~100MB I saw.  
If the smaller blockchain (or last blocks) can be within memory, it will super fast.

**Comment by ifastchain** [comment]
this is really needed feature

**Comment by paulvi** [comment]
Please vote +1 :+1:  on the 1st post above

**Comment by paulvi** [comment]
up, don't close. This is feature request

**Comment by DeRain** [comment]
Hi all. Any updates on that?

**Comment by karalabe** [comment]
There's no way to index internal transactions without executing all the blocks one by one.
