### ISSUE TITLE
Can't sync nor connect to any node

### ISSUE THREAD

**Issue by CryptoSiD** [ethereum/go-ethereum#1676]
I'm running geth at home and it sync fine, but on my friend computer it won't connect to any peer
I tryed adding all the node from the second post on this page
https://forum.ethereum.org/discussion/2188/cannot-connect-to-any-peers

Still won't sync
I need help!

**Comment by tgerring** [comment]
The bootnodes sometimes are full. We're working on expanding the limits and improve the churn rate of peers. Are you able to connect with the following console comment?
`admin.addPeer("enode://1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d89d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082@52.74.57.123:30303"`

**Comment by CryptoSiD** [comment]
yes was missing the last )
but it's syncing !!!
thanks a lot:)

**Comment by CryptoSiD** [comment]
seems like everyone i restart geth i have to readd the peer?

**Comment by tgerring** [comment]
Geth remembers your set of peers when shutdown so it can use them again on startup.

**Comment by jadaking** [comment]
i 'm CryptoSiD's buddy realy thank for your help,it was an hell issue!! :)

**Comment by CryptoSiD** [comment]
peer wont stay
how can i stop geth cleanly?

**Comment by sigwo** [comment]
@CryptoSiD are you getting errors like:
```I0817 14:43:23.907292   15178 chain_manager.go:774] Bad block #1 (88e96d4537bea4d9c05d12549907b32561d3bf31f45aae734cdc119f13406cb6)
I0817 14:43:23.908256   15178 chain_manager.go:775] Block's parent unknown d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
I0817 14:43:23.909991   15178 downloader.go:254] Synchronisation failed: hash fetching canceled (requested)
```
I created the genesis block and started with `geth --genesis genesis_block.json` and seems to write fine. What else can I check? Is there a way to force ipv4 address to listen? I only see geth listening on ipv6 ('::').

**Comment by zznww** [comment]
I have a same problem not able to sync and have no peer. The moment I added the peer suggested by @tgerring, it appeared to be working but very soon it stopped with error msg "Synchronisation failed: no peers to keep download active" and then I find the added peer gone! 

The weird thing is that the geth process only listens on ipv6 port same problem as @sigwo, which I believe might be the main culprit.

any help about it?

**Comment by CryptoSiD** [comment]
create a static-nodes.json file in the .ethereum folder (appdata\roaming\ethereum for windows)
add this in the file

[
"enode://f4642fa65af50cfdea8fa7414a5def7bb7991478b768e296f5e4a54e8b995de102e0ceae2e826f293c481b5325f89be6d207b003382e18a8ecba66fbaf6416c0@33.4.2.1:30303",
"enode://123d37ae8e215b1ec6c9cb94cc8881a88457d6c6f0a7db13cf62a7b38a1e69852ad385c5a62135c81a635531885015db02012bc87c4dec2a501980bd1cc42a0a@50.103.117.68:30303",
"enode://190ff5006dcecf96cebe6746cfd15d610cbfb32a666884c8dd546eae67bc1b589029f0c8ad389ee7c77f27cd93c7a5f454efa57ec3fee4d661c1e3dc44a5997f@24.251.161.112:30303",
"enode://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@52.16.188.185:30303",
"enode://e54dfed083740840240c5b418fc4b381e23fb7b558e5e1f6ab7aceba49e6134a7b4ced0411596b0dc6ccc90fafac730df7bb1493610f29b051240c4d32fa5d8a@144.132.21.240:30303",
"enode://548be394ae76f92224d8581d0e22167aefd6d2f06c0d42f40080c96bd96b75b3aec0171209ba0a42a16290a70dd3966292b9f9135f376b1d523e4973d9b8cda8@79.98.29.154:30303",
"enode://4fb85e61a015b089e4f73c69919469813118f20c22d22aac2104dc302c550607e1ba0a1270b6c98b3d864e0efbe59dbb51522f4295215df33001e9520be823cf@183.128.203.92:30303",
"enode://262167eb28c7ce1b2fca87bf8be22d983f0fad66a1cdffd43d51d0d52f4987ecae99a0588ffba5192a94de0ff564693e99cd204186098ba18233945f723568ca@50.136.197.236:30303",
"enode://3768597a9cb82e7e23909ac9f632ef7bd65b669543f79ebe8440e23af5ef42883a3b0ec7f34eaf0db3db5b09eff62bcffaf91eaa7c1fa6fd1bebd172d2efeef2@115.187.251.154:30303",
"enode://01cb5466bcd1683134b23a1ed1ec47c1d84d50520341b4f41c831986c72c6c55a913826d8d5e85031c0f09aae59bdd6f1ef4d4bf3f763bcea015b57fc3c0a6a8@94.75.205.12:30303",
"enode://7743dea431dbe80c31e74672048c44dd55d22cb72b486c1342bded5a8c92970e45681de775c7bfefe608ed6163ecb905829fafe9b845df32fa15fbabf4ff5fbb@46.5.254.14:30303",
"enode://15d9edb3b956e7d0fcf682b8833a0e62371b1eafb76d573d2d48ffa440a5cc67e94e0c6e8cb70fee60606d44ee94d8e87ea5c15bee8e4f8bca3060a0112d9dd5@162.213.238.72:30305",
"enode://e097a8579f848ec0f2fe8034d9b55677adec8d676a9dadb46a85c16738b312be487d949c4f30831ce56002c92fa048636bb8290b74d45f5b4f5503e6137ce2f4@58.232.222.26:30303",
"enode://03e7493fa6b81273fbb6e30a5c93b0596e4bc0765948a05918c41403eae5e3b2f80dc6788daf63c07aaf43eaaef929abf575f2a506f2f61b91648c55997aa365@24.251.161.112:30303",
"enode://4af64bc8778697076cb3bba9c615d06f28edc2920f019617e52606af905336705a9b6a897db46c7273792b38775cd754d3ee9db8e2710a2b0863639502e1b01e@45.55.229.64:30303",
"enode://ee265bfc88073e87760cc3ccc0d6ab43f966edfdd307bf0285afe4c60dfc4f9770ece08606ae7b28f34f486faaef412b8878e27b144f7db113f34355ce9cc8b8@94.3.70.42:30303",
"enode://1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d89d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082@52.74.57.123:30303",
"enode://69bfa214a36e0e4d9fe3437e2cd5450143133d46bb28cfdfe65b9215dafee080c7ac9b275638945d77806f2bfaebedd35b922b70fe1baab0e91165cfabbc5299@45.55.35.24:30303",
"enode://c0b9169d2114ac11cd577783170151e20ea7f68d31117182e66e3848474621500e91638f935ac6b87f788a1e186d365ace2f687caa3d9e51ea26c8c892b1940b@37.48.87.120:30303",
"enode://ebd81524f0a1f7222b5516dc04a5f13d75677a018e52ad6450632a01a832b80af0e932b6f87fc4ab48bef57dbfcba34217d68f76d01519034f4a82d283cbe4bb@193.192.36.230:30303",
"enode://de471bccee3d042261d52e9bff31458daecc406142b401d4cd848f677479f73104b9fdeb090af9583d3391b7f10cb2ba9e26865dd5fca4fcdc0fb1e3b723c786@54.94.239.50:30303",
"enode://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@52.16.188.185:30303",
"enode://3fd15690b0dd1c1a4d09d9c3d01acda35b83c0f1e0d9255fe22af594a1d21398562a85e300bc22b4dfd66dd1420affd40f887e1d7e7358f6ae727e1f2b81707c@84.200.16.126:30303",
"enode://571f60f1c559342d2b8221ab21b4181d1c833aecb9ae7f4a2a10218c1528ea607d7646a4857eaeab92555f0d9b51d112a053f905c698f2fffa5c05ef1a631ddf@139.162.14.216:30303",
"enode://bb4da110416c3231c35bfc5346a9137d5f9da6bd963b5156e4a41c2dbf809fc0bef0f90d0c1b5c7209a66e9b96b6ac65b7c1d15ca5f2b2176904a4646a236b4e@192.99.151.12:30303",
"enode://e2a5f423ec742dbde38bbe100163c6df0b5e2f8b8e65001496cf4416069c9f9d76abbd3db80b6dccdc2a3f9520e4f486403f754d69ade3c465e2ed3f728c32a0@177.32.208.206:30303",
"enode://e2ec0a405cc6c57602d6ae7c4bf1afebfe58385e7ee92e6a472c7393759bc33d2f395dde34421d267ffddf0debd9503f7ead82a9e4752cf098d08e1245aef25d@146.0.32.101:30303",
"enode://059ee65fa7fc1705522bce24290bd841283dc7a850a74cdd644ca163abeb03ca59c4e3dc09d282362a4e8931bc3306d4cd4c7de1abc701ae0a9dec5c41c2ad84@66.85.79.195:30303"
]

**Comment by zznww** [comment]
thank you @CryptoSiD 
I managed to find it was the ntp issue. after dong ntpdate, it's working! and it is fully reachable by ipv4 though the netstat result shows geth only listens on ipv6

**Comment by AdamLowery** [comment]
@CryptoSiD Thanks, i created the static-nodes.json file and it has started. finally. What are the downsides of having a static static-nodes.json file. how do i make a dynamic one? if possible.

**Comment by stvenyin** [comment]
solidity contract found
Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: authentication needed: password or unlock
    at Object.InvalidResponse (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/errors.js:38:16)
    at /opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:86:36
    at /opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/truffle-migrate/index.js:225:11
    at XMLHttpRequest.request.onreadystatechange (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by stvenyin** [comment]
when i Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: authentication needed: password or unlock
    at Object.InvalidResponse (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/errors.js:38:16)
    at /opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:86:36
    at /opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/truffle-migrate/index.js:225:11
    at XMLHttpRequest.request.onreadystatechange (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
happen Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: authentication needed: password or unlock
    at Object.InvalidResponse (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/errors.js:38:16)
    at /opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:86:36
    at /opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/truffle-migrate/index.js:225:11
    at XMLHttpRequest.request.onreadystatechange (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/opt/sfware/nodejs/node-v7.4.0-linux-x64/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

how do solve it
my truffle config
require('babel-register')

module.exports = {
    networks: {
        development: {
            host: "localhost",
            port: 8545,
            network_id: "*" // match any network
        },
        live: {
            host: "localhost", // Random IP for example purposes (do not use)
            port: 8189,
            network_id: 3999,      // Ethereum public network
            // optional config values
            gas:1000000
            // gasPrice
            // from - default address to use for any transaction Truffle makes during migrations
        }
    }
}
