### ISSUE TITLE
Ethereum client gets a hash but TX never makes it onto blockchain or pendingTransactions list

### ISSUE THREAD

**Issue by jonisjon** [ethereum/go-ethereum#1677]
We have seen this problem occur many times (and apparently other exchanges as well). Basically if you send enough transactions in a row somewhere between 25-50% of the transactions will never make it onto the blockchain or into pending transactions despite getting a hash. The transactions effectively disappear and the client never errors.

This is running linux/geth enviornment currently

**Comment by tgerring** [comment]
Duplicate of #1662
