### ISSUE TITLE
[Feature Request] Add account ETH changes to getTransactionReceipt

### ISSUE THREAD

**Issue by junderw** [ethereum/go-ethereum#16778]
Currently getTransactionReceipt returns:

```javascript
{
  blockHash: "0x...",
  blockNumber: 11111111,
  contractAddress: null,
  cumulativeGasUsed: 1111111,
  from: "0x...",
  gasUsed: 1111111,
  logs: [{
      address: "0x...",
      blockHash: "0x...",
      blockNumber: 11111111,
      data: "0x...",
      logIndex: 11,
      removed: false,
      topics: ["0x..."],
      transactionHash: "0x...",
      transactionIndex: 11
  }],
  logsBloom: "0x...",
  status: "0x1",
  to: "0x...",
  transactionHash: "0x...",
  transactionIndex: 11
}
```

I would propose adding a new key to the object called `ethAccountsAffected` with an array of objects, the objects have an address, and an amount with a minus sign before it when subtracted.

This way we could look at a transaction and know exactly how certain addresses were affected in their ETH balance by the results of a smart contract.

I apologize if someone has already proposed this, and if the data key of the logs is in a format that reliably tells this info, I would still like to ask that this data is duplicated in a more easy to handle format such as I explained above.

**Comment by karalabe** [comment]
The issue here is that a node can only collect this data if it executed the transaction itself. If the node fast / warp / light synced, it doesn't have access to these infos.

**Comment by junderw** [comment]
> The issue here is that a node can only collect this data if it executed the transaction itself.

This would be sufficient for my use case, any transaction not executed by my node (due to fast sync etc) can just return null or 'missing' or something along those lines.
