### ISSUE TITLE
deprecated `--ipcapi` flag?

### ISSUE THREAD

**Issue by isLishude** [ethereum/go-ethereum#16786]
#### System information

Geth version: 1.8.9
OS & Version: Linux

#### Expected behaviour
`--ipcapi`  flag doesn't work,was it deprecated?

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Should still work. How are you running geth? Are you sure you didn't mess up a flag before this one, which would cause flags to not be interpreted any more?

**Comment by isLishude** [comment]
@karalabe I run this on mine `geth --datadir data --rpc --ipcapi "eth,web3"` and responses the error:`Incorrect Usage. flag provided but not defined: -ipcapi`

**Comment by karalabe** [comment]
Aaah, wait. There never was an `ipcapi` path. All APIs are exposed on IPC.

**Comment by isLishude** [comment]
https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

The page has not `--ipcapi` flag either

**Comment by karalabe** [comment]
But why do you need it?

**Comment by isLishude** [comment]
er... I wanna close `mining` and no way to start mining

**Comment by karalabe** [comment]
But all APIs are reachable via IPC, you don't need to explicitly expose any of them.

**Comment by isLishude** [comment]
All right, so that's that.

**Comment by Dabaitu2** [comment]
Sorry for referring this closed issue back, but I found that there's a wiki page that still mentions the directive --ipcapi, which is located at [https://github.com/ethereum/go-ethereum/wiki/Management-APIs](https://github.com/ethereum/go-ethereum/wiki/Management-APIs), may be we need take a few moment to update this page?
