### ISSUE TITLE
what does mean signer's key JSON?

### ISSUE THREAD

**Issue by offsidezzz** [ethereum/go-ethereum#16780]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information
Geth version: 1.8.8-stable-2688dab4
OS & Version: ubuntu 

I'm currently created private ethereum network using puppeth, when I created a sealer/ miner, appear this question **"Please paste the signer's key JSON:"**

whats that is mean? and where I can get signer's key JSON?

thank you guys

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
