### ISSUE TITLE
Call with block number parameter will always return the same timestamp.

### ISSUE THREAD

**Issue by Georgi87** [ethereum/go-ethereum#1678]
I have a function call which returns an array with a timestamp at pos. 0. If I call this functino with different block numbers always the same timestamp is returned. However the other data in the array changes as expected.
```
function getShareDistribution(uint market_maker_hash) returns (uint[64]) {
    uint8 outcome_count = Events[MarketMakers[market_maker_hash].event_hash].outcome_count;
    uint[64] memory share_distribution;
    share_distribution[0] = block.timestamp;
    for(uint8 l=1; l<=outcome_count; l++) {
      share_distribution[l] = MarketMakers[market_maker_hash].shares[l];
    }
    return share_distribution;
  }
```

**Comment by tgerring** [comment]
Can you provide some more details? It sounds like the question is about Solidity, not the Go client.

**Comment by zelig** [comment]
best to submit this question 
* on the solidity and web3 skype channel 
* web3.js gitter room https://gitter.im/ethereum/web3.js
* or #dappdevs IRC

**Comment by LianaHus** [comment]
It seems there is a bug in timestamp code. There would be PR soon.

**Comment by Georgi87** [comment]
I checked it again. It seems that it is not fixed yet at least in the stable version.

**Comment by LianaHus** [comment]
what value you've got?

**Comment by Georgi87** [comment]
It always returns the same value of the latest block
