### ISSUE TITLE
web3.js can not listen event on geth

### ISSUE THREAD

**Issue by KeepChen** [ethereum/go-ethereum#16787]
Hi @obscuren,I encountered a problem [here](https://github.com/ethereum/web3.js/issues/1653)

#### System information

Geth version: 1.8.8-stable-2688dab4
OS & Version: Ubuntu 16.04 x64

Hope to answer, thank you very much!

**Comment by karalabe** [comment]
Are you sure your flags are correct? `--unlock "my address" --password "my password"`

 * `"my address"` should be a single address or a comma separated list of addresses
 * `"my password"` should be a path to a single file in your hard drive

**Comment by KeepChen** [comment]
This is command:
`geth --datadir /var/disk/gethDataDir/ --rpc --rpcapi db,eth,net,personal,web3 --ws --wsapi db,eth,net,personal,web3 --wsorigins=* --unlock "0x97cc6d32fbe7063bf7540**********" --password "/var/geth/password.conf"`
"my address" is my coinbase address(`geth attach ws://localhost:8546`)

**Comment by KeepChen** [comment]
@karalabe 
This is my geth startup log.

![start geth](http://d2tscn30gsvvic.cloudfront.net/notice/98fb962fca42842119b38f727d5044f1.png "geth log")

It can be seen that it can successfully start and unlock account.

**Comment by KeepChen** [comment]
After many failed attempts, I gave up using the geth command line to unlock the account. At the moment I need to unlock the account and use the web3.js method to unlock it manually.
`web3.eth.personal.unlockAccount(address, password, untilTime)`
