### ISSUE TITLE
Feature request: Getting block header via rpc

### ISSUE THREAD

**Issue by Phistr90** [ethereum/go-ethereum#1679]
Hi,

I figured out that with the current rpc call method eth_getBlockByNumber it is not possible to get all information needed for a block header.
There is no triehash(receipts).

For a project I need to get the block header of the pending block via rpc in order to validate the header hash later by a third party.

Would be nice if you could implement this feature.

Thanks Philipp

**Comment by obscuren** [comment]
This is a reasonable request and quite trivial to implement. Since we already have the `T(B_txs)` I think it's fair to say we add `T(B_rs)` as well.

**Comment by Phistr90** [comment]
Would be really nice if you guys could take care of it in the next days. Officially approved by your master Jeff :D

**Comment by karalabe** [comment]
Added in #1742.
