### ISSUE TITLE
Geth node sync always behind

### ISSUE THREAD

**Issue by kandrejevs** [ethereum/go-ethereum#16796]
#### System information

Geth version:  1.8.8-stable-2688dab4
OS & Version: Ubuntu Server 16.04, 2 cores, 8GB of RAM, 170GB SSD storage (aws c5.large)

#### Expected behaviour

Geth should be able to sync with network

#### Actual behaviour

Geth node is always couple hundred blocks behind and is not able to be fully in sync, after 40 hours I get:

```
> eth.syncing
{
  currentBlock: 5667131,
  highestBlock: 5667209,
  knownStates: 111239860,
  pulledStates: 111225435,
  startingBlock: 5664481
}
```

Previosly Geth was crashing due out of memory, I increased swap to 20GB, node is stable now, but falls behind. 

#### Steps to reproduce the behaviour

Launch geth node with these params:

```
geth --syncmode "fast" --cache=2048 --maxpeers=128 --metrics --rpc --rpcapi "db,eth,net,web3,personal,web3" --rpcaddr "0.0.0.0" --rpcport 8545 --rpcvhosts "geth.domain.com"
```

**Comment by ddwrtmenace** [comment]
@karalabe Will it eventually become impossible to sync with a SSD too?

**Comment by deckarep** [comment]
@karalabe - great detailed answer that is useful for helping people understand intricacies of running a node.

Question: is there any known metrics on what it takes to time wise to bootstrap a full node with full history back to the genesis block? Hours? Days? Months? Just looking for ballpark as hardware and environment are all huge variables.  Also what is the success rate of getting into a full synced state? Is 100% reliable and just a factor of time or do people find that they regularly have problems trying to sync fully?

**Comment by kandrejevs** [comment]
@Rohithzr you have to use i3.large instance on aws to be able to sync. the problem is that EBS have large latency and that is the reason why it fails to sync. i3 have nvme drives, that have smaller latency.

geth is a really terrible piece of software if you have to pay 130$ a month in order to be even able to run node on the cloud.

**Comment by Rohithzr** [comment]
@kandrejevs I am using external EBS volumes for geth which gives me NVME drives on the C5, so is there any other specific reason to go for i3?

**Comment by kandrejevs** [comment]
@Rohithzr only c5d instanes use nvme's, ebs gp2 is general purpose ssd with higher latency than nvme.

for me i3 instances sync relatively fast, I think less than 8 hours, c5 took almost a week

**Comment by Rohithzr** [comment]
@kandrejevs you are correct, but scaling the instances this way would mean wasting the 15 gig ram and once the eth blockchain size passes 475 GiG then I will have to scale it to the i3.xlarge with 30 GiG ram, and pay double. These volumes cannot be resized and hence give less control on it.

**Comment by kandrejevs** [comment]
8GB of RAM is too little anyway, I often experienced random crashes because of that, had to add an additional 20GB swap file to ensure the system is somewhat stable. I did run geth through supervisor so it is always running, those random crashes due memory outage even corrupted local database twice and had to restore from AMI. I would say 15GB is bare minimum anyway, so I would not worry about 15GB of RAM.

about scaling- well that is the sad reality about blockchain and geth and nothing you can do about it. it is what it is- a really expensive to run software that brings little if none value at the current state.

the only alternative is to run geth on light mode and rely on external peers only, but due low number of peers, the system is not stable at all and you can get outages for hours or even days where your node is not able to find any peers and is pretty much useless. i3 is your best bet on aws to run geth somewhat stable and reliable if it is mission critical.

**Comment by Rohithzr** [comment]
@kandrejevs thanks for your inputs, i would still experiment in some ways and maybe a cluster would provide more reliability  or maybe something else. If nothing then I will probably go for i3, and yeah mine runs on supervisor too and is giving me 70 to 80% reliability, so i guess ill see what the future holds.

**Comment by juergenhoetzel** [comment]
I was able to increase performance significantly by increasing the number of database handlers (open files cache): [Add new command line option --database-handles (#16796)](https://github.com/ethereum/go-ethereum/pull/17597)

**Comment by Rohithzr** [comment]
@juergenhoetzel so i currently am getting good enough reliability after I scaled the server to r5-large (2GiG, 16GiG), increased the cache. So does this option help me in someway?

**Comment by juergenhoetzel** [comment]
> @juergenhoetzel so i currently am getting good enough reliability after I scaled the server to r5-large (2GiG, 16GiG), increased the cache. So does this option help me in someway?
@Rohithzr 
If your load is I/O bound you will  benefit because it will reduce the number of `open/close` syscalls and thus gives the system more time to do actual `read/write` I/O.

**Comment by adamschmideg** [comment]
@kandrejevs I understand your original issue was answered. If I'm wrong, please, reopen this issue.

**Comment by Rohithzr** [comment]
@adamschmideg nope, I am good. my node is been in sync for months without issue.

**Comment by vietthang207** [comment]
Thanks u guys for the helps! I've wonder if there is a way to check state syncing status (i.e. how many states did I've downloaded, and how many left)

**Comment by mishell-trickster** [comment]
@vietthang207
`geth attach`
`eth.syncing`

This give you a status of blocks and states.

**Comment by Lizard-King101** [comment]
so what about when the node is not syncing but also ~30k blocks behind??
