### ISSUE TITLE
Unable to access wallet using ethereum/client-go and --keystore *if* the wallet is a symbolic link

### ISSUE THREAD

**Issue by DazWilkin** [ethereum/go-ethereum#16793]
#### System information

Geth version: ```instance=Geth/v1.8.9-unstable-415969f5/linux-amd64/go1.10.2```

OS & Version: Linux

#### Summary

It appears (!) that symbolic links to wallets are treated differently (incorrectly). The reason this is an issue is that, when trying to run Ethereum on Kubernetes, it would be useful to represent wallet file(s) using Kubernetes Secrets|ConfigMaps. Secrets|ConfigMaps present encapsulated files as symbolic links. This is how I uncovered this issue. The repro works without Kubernetes, using Docker and flipping between underlying and symbolic links to a wallet.

#### Expected behaviour
Using Console, I expect ```personal``` to list my wallet

#### Actual behaviour
If the file in /keystore is a symbolic link to a wallet, it does not work:

```
personal
{
  listAccounts: [],
  listWallets: [],
...
}
```
if the single file in /keystore is the original file (backing the symbolic link), it works:

```
personal
{
  listAccounts: ["0x3df6..."],
  listWallets: [{
      accounts: [{...}],
      status: "Locked",
      url: "keystore:///keystore/UTC--2018-00-00T00-00-00.000000000Z--3df6..."
  }],
```

#### Steps to reproduce the behaviour

```
ls $PWD/keystore
UTC--2018-00-00T00-00-00.000000000Z--3df6...

mkdir $PWD/lnkeystore
ln -s $PWD/keystore/UTC--2018-00-00T00-00-00.000000000Z--3df6... $PWD/lnkeystore

ls $PWD/lnkeystore
UTC--2018-00-00T00-00-00.000000000Z--3df6...
```

Node-1: Works with `$PWD/keystore`
```
docker run \
--rm \
--interactive \
--net=host \
--tty \
--volume=$PWD/keystore:/keystore \
ethereum/client-go \
  --rinkeby \
  --keystore=/keystore  \
  --rpc \
  --rpcaddr=0.0.0.0 \
  --rpcapi="db,eth,net,personal,web3"
```

Node-1: Doesn't work with `$PWD/lnkeystore`
```
docker run \
--rm \
--interactive \
--net=host \
--tty \
--volume=$PWD/lnkeystore:/keystore \
ethereum/client-go \
  --rinkeby \
  --keystore=/keystore  \
  --rpc \
  --rpcaddr=0.0.0.0 \
  --rpcapi="db,eth,net,personal,web3"
```

Node-2: Console
```
docker run \
--rm \
--interactive \
--tty \
ethereum/client-go \
  attach http://localhost:8545 \
  console
```

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Ping @fjl @holiman

**Comment by DazWilkin** [comment]
I have a workaround while this issue is repro'd/resolved:

I am able to use a Kubernetes [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) to copy the wallet file(s) out of the [Secret](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets)|ConfigMap (`/keystore`) into an [emptyDir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) volume (`/cache`) *before* the Ethereum node starts.

Then, when the Ethereum node starts, it is configured with `--keystore` to the copy and it works :-(

It would be preferable to access the wallet(s) directly (through symbolic links) but this hack permits me to continue working. Medium post "[Ethereum on Google Cloud Platform](https://medium.com/google-cloud/ethereum-on-google-cloud-platform-8f10c82493ca)" (feedback always welcome)

**Comment by rawfalafel** [comment]
hey @DazWilkin, can you try the fix in #17256 if you're still using the above workaround?

**Comment by DazWilkin** [comment]
I will try this today!

**Comment by DazWilkin** [comment]
Yes, this appears to work for me. Thank you!
