### ISSUE TITLE
Fatal Issue: When the address is invalid, Ethereum will automatically change the address and then conduct the transaction

### ISSUE THREAD

**Issue by CockyCat** [ethereum/go-ethereum#16808]
0x03747f06215b44e4918831da019b27f53e483599f is an invalid address, but when the transaction is initiated with this invalid address, Ethereum will automatically remove the third bit from 0 to **0x3747f06215b44e4918831da019b27f53e483599f**. At this time, this address is just a valid address, so transfer is made. 

If it is an invalid address, Ethereum should reject the transaction.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by motafa1320** [comment]
0x2158C40347b80Fd05d096de23bAd8Ec4B2A453F7

**Comment by bonney92** [comment]
I am at Huobi-the leading global digital asset exchange waiting for you. Come and register!
https://www.huobi.br.com/en-us/topic/invited/?invite_code=6wee3

**Comment by karalabe** [comment]
@CockyCat Do you have any logs for us, or how you initiated the call that succeeded? I'm fairly sure go-ethereum does **not** accept invalid transactions, so a higher level library might have truncated the data already before passing it to geth.

**Comment by motafa1320** [comment]
Is it possible for you to transfer one erthereum to my wallet:
0xe062C83117bD141F6E92c5B79325a12d78A97568

**Comment by motafa1320** [comment]
mr karalabe
can you help me?
davoud vakili

**Comment by motafa1320** [comment]
i can not transfer my fund  to the  etherbloc why so personal metamask doing thid work with me.
thanks
davoud vakili

**Comment by adamschmideg** [comment]
@CockyCat closing this issue since there hasn't been any activity on it. If the problem persists, please, reopen the issue and provide logs.
