### ISSUE TITLE
High virtual memory usage in private network

### ISSUE THREAD

**Issue by arthurk** [ethereum/go-ethereum#16811]
Hi,

geth shows a  high virtual memory usage (520GB) in private networks with very few blocks. This happens with `geth --dev` and the same when setting up a new private network with clique and a period > 0.

The below screenshot shows the memory usage after just one block.

![gethhighmem](https://user-images.githubusercontent.com/23406/40569019-aae88b90-607e-11e8-9556-715120405a25.png)

#### System information

Geth version: 1.8.8
OS & Version: macOS 10.13.2

#### Expected behaviour

The virtual memory usage should be low.

#### Actual behaviour

The virtual memory usage is high (520GB).

#### Steps to reproduce the behaviour

1.  Run `geth --dev`
2. Check virtual memory usage

**Comment by karalabe** [comment]
The actual memory usage is 550MB. That seems fine. I don't think virtual memory number is really relevant. Maybe I'm mistaking. @fjl?

**Comment by arthurk** [comment]
I was just surprised that it reports 520GB virtual size, it is unusual for a process
