### ISSUE TITLE
geth Docker build on Windows fails: build/env.sh: Command not found

### ISSUE THREAD

**Issue by rustyx** [ethereum/go-ethereum#16828]
Due to [`.gitattributes`](https://github.com/ethereum/go-ethereum/blob/master/.gitattributes) which forces autocrlf for text files (`* text=auto`), the checkout on Windows is done with CRLF line endings, which breaks Docker builds:

```
Step 4/9 : RUN cd /go-ethereum && make geth
 ---> Running in 30c5201981ca
build/env.sh go run build/ci.go install ./cmd/geth
make: build/env.sh: Command not found
make: *** [Makefile:15: geth] Error 127
The command '/bin/sh -c cd /go-ethereum && make geth' returned a non-zero code: 2
```

Suggesting to remove `.gitattributes`, since there is no workaround (no override possibility for `.gitattributes`).

**Comment by davidstoneham** [comment]
@rustyx what's the solution for getting this to work on windows. Updating the makefile from a Linux machine?

**Comment by rustyx** [comment]
Bump!

**Comment by karalabe** [comment]
Not much we can do about it IMHO. Windows expects lines to be `CRLF` ended. You can't push that into a Linux environment. The problem and some solutions are described here https://willi.am/blog/2016/08/11/docker-for-windows-dealing-with-windows-line-endings/ too.

**Comment by rustyx** [comment]
`* text=auto` is very dangerous, it mangles files, you should not use it. Better to specify exactly what extensions are text, and what mode they should use, e.g. `.sh text=lf`, `.bat text=crlf`. We dropped ethereum support, so I don't need this anymore, but please make a note of it.
