### ISSUE TITLE
geth(1.5.5) attach command doesn't work

### ISSUE THREAD

**Issue by propassionist** [ethereum/go-ethereum#16830]
#### System information

Geth version: `geth version 1.5.5`
OS & Version: OSX

I set my Geth environment on my Mac Pro. and try to follow my book which is about block chain with ethereum. present step is to execute this command to make run geth in the background,

"nohup geth --networkid 4649 --nodiscover —-maxpeers 0 --datadir users/taiyoonyoon/data_testnet/ --mine —-minerthreads 1 --rpc 2 >> /users/taiyoonyoon/data_testnet/geth.log &" 

and then execute next command,

"geth attach rpc:http://localhost:8545"

but I cannot access to my local server, getting this error message continuously,

"Fatal: Failed to start the JavaScript console: api modules: Post http://localhost:8545: dial tcp [::1]:8545: getsockopt: connection refused"

I don't know why.. I have tried to solve this error for two or three days, but there were no answers...

please tell me why I get this error..

thanks,

cf) the reason why i installed geth version 1.5.5 is that the book deals with 1.5.5 codes.

**Comment by karalabe** [comment]
Please use a fresh Geth version. It should be the same. The benefits outweigh any inconsistencies.

> getsockopt: connection refused

This ^ means that you don't have the post opened. Please make sure you run your serving node with `--rpc`.

**Comment by propassionist** [comment]
thx, I checked my problem, but whenever I did my nohup command(upper one), it stopped immediately, leaving this message.

-----------------------------------------------------------------------------------------------
Taiyoonui-MacBook-Pro:data_testnet taiyoonyoon$ nohup geth --networkid 4655 --nodiscover --maxpeers 0 -datadir /users/taiyoonyoon/data_testnet --mine  --minerthreads 1 --rpc 2>> /users/taiyoonyoon/data_testnet/geth.log &
[2] 2777
Taiyoonui-MacBook-Pro:data_testnet taiyoonyoon$ 

[2]+  Stopped                 nohup geth --networkid 4655 --nodiscover --maxpeers 0 -datadir /users/taiyoonyoon/data_testnet --mine --minerthreads 1 --rpc 2>> /users/taiyoonyoon/data_testnet/geth.log
--------------------------------------------------------------------------------------------

like that..
what is the problem?? is there a problem in Mac OS nohup command?
can anybody tell me why??

**Comment by karalabe** [comment]
What logs does geth print into that particular file you specified?

**Comment by propassionist** [comment]
hm,,, there are no prints.. in the log.. anything
and as you recommended before, I've upgraded geth, newest version(1.8.10) in my Mac, but the result is same.
(no logs at all)

**Comment by karalabe** [comment]
Does it print anything if you run it outside of `nohup`?

**Comment by propassionist** [comment]
ah, now I can get some result, these are my command executing steps, and last one is log contents..

---------------------------------------------------------------------------------------------------
Taiyoonui-MacBook-Pro:~ taiyoonyoon$ ps -eaf | grep geth
  501  5130  5123   0  5:04PM ttys000    0:00.01 grep geth
Taiyoonui-MacBook-Pro:~ taiyoonyoon$ nohup geth --networkid 4649 --nodiscover —-maxpeers 0 --datadir /users/taiyoonyoon/data_testnet/ --mine —-minerthreads 1 --rpc 2 >> /users/taiyoonyoon/data_testnet/geth.log &
[1] 5131
Taiyoonui-MacBook-Pro:~ taiyoonyoon$ 

[1]+  Stopped                 nohup geth --networkid 4649 --nodiscover —-maxpeers 0 --datadir /users/taiyoonyoon/data_testnet/ --mine —-minerthreads 1 --rpc 2 >> /users/taiyoonyoon/data_testnet/geth.log
Taiyoonui-MacBook-Pro:~ taiyoonyoon$ cd data_testnet
Taiyoonui-MacBook-Pro:data_testnet taiyoonyoon$ tail -100f geth.log
INFO [05-31|17:03:35] Maximum peer count                       ETH=25 LES=0 total=25
INFO [05-31|17:03:35] Starting peer-to-peer node               instance=Geth/v1.8.10-stable/darwin-amd64/go1.10.2
INFO [05-31|17:03:35] Allocated cache and file handles         database=/Users/taiyoonyoon/Library/Ethereum/geth/chaindata cache=768 handles=128
INFO [05-31|17:03:35] Writing default main-net genesis block 
INFO [05-31|17:03:35] Persisted trie from memory database      nodes=12356 size=2.34mB time=36.461137ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [05-31|17:03:35] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: <nil> Engine: ethash}"
INFO [05-31|17:03:35] Disk storage enabled for ethash caches   dir=/Users/taiyoonyoon/Library/Ethereum/geth/ethash count=3
INFO [05-31|17:03:35] Disk storage enabled for ethash DAGs     dir=/Users/taiyoonyoon/.ethash                      count=2
INFO [05-31|17:03:35] Initialising Ethereum protocol           versions="[63 62]" network=4649
INFO [05-31|17:03:35] Loaded most recent local header          number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [05-31|17:03:35] Loaded most recent local full block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [05-31|17:03:35] Loaded most recent local fast block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [05-31|17:03:35] Regenerated local transaction journal    transactions=0 accounts=0
INFO [05-31|17:03:35] Starting P2P networking 
INFO [05-31|17:03:35] RLPx listener up                         self="enode://38eece0afe770c3758ed574fcf193e96a7cac86628fc907c73d76631d702bc831bd0ca00bbfe3f72ba1ba40188e4120cb861392de8e8776989dc00e513160282@[::]:30303?discport=0"
INFO [05-31|17:03:35] IPC endpoint opened                      url=/Users/taiyoonyoon/Library/Ethereum/geth.ipc

**Comment by propassionist** [comment]
I found my reason..!!
thanks for all..!!

cf) my problem was the input of the upper command "nohup~ &", I don't know why, but while I was typing "--", it changed to "—-", first one was longer than next one.
I found this reason, by typing same command one by one, not copy & paste from my copied one, which is including longer bar, "—", and executing well.

**Comment by Ko-donghyun** [comment]
I have same issue at 
`Geth version: geth version 1.8.11`
`OS & Version: OS 10.12.1`.

When I type below command
`nohup ./geth --networkid 4649 --nodiscover --maxpeers 0 --datadir ./data_testnet/ --mine --minerthreads 1 --rpc --rpcaddr "0.0.0.0" --rpcport 8545 --rpccorsdomain "*" --rpcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --unlock 0 --password ./data_testnet/passwd --verbosity 6 2>> ./data_testnet/geth.log &`

It just responses below message.
`[1]+  Stopped                 nohup ./geth --networkid 4649 --nodiscover --maxpeers 0 --datadir ./data_testnet/ --mine --minerthreads 1 --rpc --rpcaddr "0.0.0.0" --rpcport 3000 --rpccorsdomain "*" --rpcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --unlock 0 --password ./data_testnet/passwd --verbosity 6 2>> ./data_testnet/geth.log`

Is this my own problem?
