### ISSUE TITLE
the balance in my own Ethereum Private BlockChain was lost

### ISSUE THREAD

**Issue by sakulove** [ethereum/go-ethereum#16845]
I made a ethereun private block chain and opened rpc service it works well at first,but after a while,when i unlock a wallet by json-rpc,the balance in this wallet will be sent to two other address,it's wired.I just sent one transaction,i tried some solutions , reinstall geth rebuild my chain,but can't solve this problem.

**Comment by ligi** [comment]
Is the RPC publicly accessible?

**Comment by karalabe** [comment]
There are bots actively scanning Ethereum networks for open RPC ports and unlocked accounts. IF tey find one, they move the balance. Please don't ever open your RPC port publicly to the internet.
