### ISSUE TITLE
txHash.Str undefined (type common.Hash has no field or method Str)

### ISSUE THREAD

**Issue by kivutar** [ethereum/go-ethereum#16841]
Geth version: `master`
OS & Version: Linux/OSX (Travis)
Commit hash : 38c7eb0

This error happens while running my CI, during the `go get` of the dependencies of my package, or during `go test`.

The travis file is quite simple. Relevant parts:

```
before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo
  - go get github.com/ethereum/go-ethereum
  - go get github.com/miguelmota/go-solidity-sha3
  - go get -t -v ./...
  - go generate ./...

script:
  - go test -v -race ./...
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 19 $GO_FILES
  - golint -set_exit_status $(go list ./...)
```

The error looks similar to https://stackoverflow.com/questions/28907976/type-has-not-field-or-method-read-but-it-does

**Comment by karalabe** [comment]
`common.Hash` does **not** have such a method.

**Comment by kivutar** [comment]
...anymore.
