### ISSUE TITLE
eth_getTransactionCount(address,'pending') does not take into account the pending transactions

### ISSUE THREAD

**Issue by MalayTripathi** [ethereum/go-ethereum#16844]
Hi Team,

I am using an application that moves Ether from a "from" address to a "to" address as specified in the parameter of the API call. The application is a NodeJS app connected to a remote node (my own geth node). The issue is that when I issue successive transactions from same "from" address, it does not take the pending transactions into account and shows the same nonce.

So I get the error known transaction found or replacement transaction underpriced.

Note: This setup worked fine with a previous version of geth 1.8.x

#### System information

Geth version: 1.8.9-stable
OS & Version: Ubuntu 16.04
Commit hash: None

#### Expected behaviour

For an address say X, if a transaction from X to Y for a value Z with Nonce 2 is pending, eth_getTransactionCount(X, 'pending') should return 3

#### Actual behaviour

For an address say X, if a transaction from X to Y for a value Z with Nonce 2 is pending, eth_getTransactionCount(X, 'pending') returns 2 until that tx is mined.

#### Steps to reproduce the behaviour

For an address X, Console the output of eth_getTransactionCount(X, 'pending') and then do a transaction from that address X. Console the out of eth_getTransactionCount(X, 'pending') immediately after the transaction.

#### Backtrace

No Backtrace.

**Comment by karalabe** [comment]
This was fixed a long time ago to return the nonce from the txpool.
