### ISSUE TITLE
Geth 1.8.9 stopped responding

### ISSUE THREAD

**Issue by vogelito** [ethereum/go-ethereum#16840]
#### System information

Geth version:
```
Geth
Version: 1.8.9-stable
Git Commit: ff9b14617e73c07dfa028bc477fe86c1e04d80c5
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```
OS & Version: Linux

#### Expected behaviour
Node should continue operating

#### Actual behaviour
Node became unresponsive

#### Steps to reproduce the behaviour
Unsure. 1.8.9 ran for roughly 24 hours and then it became unresponsive to RPC calls. Log contains some more information.

#### Backtrace
[Log pastebin](https://pastebin.com/DJ5MR26J)

**Comment by holiman** [comment]
Great that you caught the trace. Very interesting, the trace suggests there's a lock contention in the tx_pool. Thanks!

**Comment by karalabe** [comment]
This was a bit unfortunate timing. The bug which (apparently) caused this lockup was already present on master for the entire week last week while you were running the memory tests. I've pushed a fix onto master, will release a hotfix shortly. I really hope this (https://github.com/ethereum/go-ethereum/pull/16843) was the issue.
