### ISSUE TITLE
How to run Ethereum node forever

### ISSUE THREAD

**Issue by HrishikeshFC** [ethereum/go-ethereum#16856]
I want to run my **Private Ethereum Node continuously**, even if it stops in between,it should get started automatically. Like **forever npm in node** which ensures that a given script runs continuously. so is there any tool which can be used to monitor the Ethereum node, and should start the node automatically if it stops.

**Comment by RichHorrocks** [comment]
Hi there. Please keep the issue tracker clear for real issues and feature requests.

For technical questions, either Stack Exchange (https://ethereum.stackexchange.com/) or Reddit (https://www.reddit.com/r/ethereum and https://www.reddit.com/r/ethdev/) are better places to ask.

**Comment by HrishikeshFC** [comment]
Okay, Thanks.
