### ISSUE TITLE
requirements to Set up Ethereum Node

### ISSUE THREAD

**Issue by DMNV** [ethereum/go-ethereum#16854]
Hi all,

I need to setup public Ethereum node, so I want to know what are the requirements ?
 - setup node in Microsoft Azure or other server?
 - what are the
 a.	VM cloud, with 500GB hard disk ?
 b.	A container is a possibility (Docker, windows container) ?
 c.	Processor?
 d.	RAM?
or other requirements.

thank you....

**Comment by RichHorrocks** [comment]
Hi there. Please keep the issue tracker clear for real issues and feature requests.

For technical questions, either Stack Exchange (https://ethereum.stackexchange.com/) or Reddit (https://www.reddit.com/r/ethereum and https://www.reddit.com/r/ethdev/) are better places to ask.
