### ISSUE TITLE
puppeth failed on deploy puppeth on ubuntu16.06 virtualmachine built with vmware workstaion

### ISSUE THREAD

**Issue by albertjone** [ethereum/go-ethereum#16864]
Hi there,

i was trying to build a private blockchain network with puppeth on ubuntu16 virtualmachine built with VMware Workstation 14. when i try to add a ethstats, it failed.Below are the picture for more detailed information.

#### System information

Geth version: `1.8.8-stable-2688dab4`
OS & Version: Ubuntu16.06
Commit hash : (if `develop`)

#### Expected behaviour

Ethstats service health check is ok and  I could connect to ethstats service.

#### Actual behaviour
WARN [06-02|15:50:10] Ethstats service seems unreachable       server=stats.guan.network port=80 err="dial tcp: i/o timeout"

#### Steps to reproduce the behaviour
Which server do you want to interact with?
 1. Connect another server
> 1

Please enter remote server's address:
> guan.network	

The authenticity of host 'guan.network:22 (192.168.0.31:22)' can't be established.
SSH key fingerprint is 77:56:ee:a1:e4:61:0f:ed:58:3f:e5:1b:cc:fa:e0:e9 [MD5]
Are you sure you want to continue connecting (yes/no)? yes

Which port should ethstats listen on? (default = 80)
> 

Allow sharing the port with other services (y/n)? (default = yes)
> 
INFO [06-02|15:48:33] Deploying nginx reverse-proxy            server=guan.network port=80
Building nginx
Step 1/1 : FROM jwilder/nginx-proxy
 ---> e143a63bea4b
Successfully built e143a63bea4b
Successfully tagged guan/nginx:latest
Creating guan_nginx_1

Proxy deployed, which domain to assign? (default = guan.network)
> stats.guan.network

What should be the secret password for the API? (must not be empty)
> guan
Found orphan containers (guan_nginx_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Building ethstats
Step 1/2 : FROM puppeth/ethstats:latest
 ---> fb62abe59cb2
Step 2/2 : RUN echo 'module.exports = {trusted: ["192.168.0.31"], banned: [], reserved: ["yournode"]};' > lib/utils/config.js
 ---> Running in 40b3dddfe5bd
Removing intermediate container 40b3dddfe5bd
 ---> 36f2ac4c6001
Successfully built 36f2ac4c6001
Successfully tagged guan/ethstats:latest
Creating guan_ethstats_1
INFO [06-02|15:50:09] Starting remote server health-check      server=guan.network
WARN [06-02|15:50:10] Ethstats service seems unreachable       server=stats.guan.network port=80 err="dial tcp: i/o timeout"
+--------------+--------------+----------+-----------------------+--------------------+
|    SERVER    |   ADDRESS    | SERVICE  |        CONFIG         |       VALUE        |
+--------------+--------------+----------+-----------------------+--------------------+
| guan.network | 192.168.0.31 | ethstats | Banned addresses      | []                 |
|              |              |          | Login secret          | guan               |
|              |              |          | Website address       | stats.guan.network |
|              |              |          | Website listener port | 80                 |
|              |              |          | --------------------- | ------------------ |
|              |              | nginx    | Shared listener port  | 80                 |
+--------------+--------------+----------+-----------------------+--------------------+

My /etc/hosts
127.0.0.1	localhost
127.0.1.1	mrrobot-virtual-machine
192.168.0.31    guan.network
192.168.0.32    guan.boot
192.168.0.33    guan.miner1
192.168.0.34    guan.miner2
192.168.0.35    guan.miner3
192.168.0.36    guan.dashboard

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

My genesis:
Please specify a network name to administer (no spaces or hyphens, please)
> guan

Sweet, you can set this via --network=guan next time!

INFO [06-02|15:45:27] Administering Ethereum network           name=guan
WARN [06-02|15:45:27] No previous configurations found         path=/home/mrrobot/.puppeth/guan

What would you like to do? (default = stats)
 1. Show network stats
 2. Configure new genesis
 3. Track new remote server
 4. Deploy network components
> 2

Which consensus engine to use? (default = clique)
 1. Ethash - proof-of-work
 2. Clique - proof-of-authority
> 1

Which accounts should be pre-funded? (advisable at least one)
> 0x4382393bc7f1f1841250850b3bdf67c229f5f82a
> 0x

Specify your chain/network ID if you want an explicit one (default = random)
> 4554
INFO [06-02|15:47:01] Configured new genesis block 

#### Backtrace

````
[backtrace]
````

**Comment by albertjone** [comment]
there are picture in this [url](https://stackoverflow.com/questions/50655225/blockchain-puppeth-add-ethstats-node-failed).

**Comment by jsvisa** [comment]
Seems you are not set a DNS record of *stats.guan.network*, set it to the */etc/hosts* and try again.
