### ISSUE TITLE
Proof of authority and mining

### ISSUE THREAD

**Issue by ArnaudLhutereau** [ethereum/go-ethereum#16885]
Hi,

I try to make a private PoA blockchain and I have some questions about it.
Only sealers can validate transactions when they "seal a block", so they must to mine continuously ?
If there is no transaction, sealers still mine blocks?
And what about the difficulty, will she still be the same for the first block and for the 1000000 block?

Thank you

**Comment by hadv** [comment]
@ArnaudLhutereau If you want to ask questions, it'd better to join and ask on gitter instead of creating a new issue like this :)
