### ISSUE TITLE
Bootnodes are very unreliable

### ISSUE THREAD

**Issue by REPTILEHAUS** [ethereum/go-ethereum#16888]
Does anyone else have issues with bootnodes ?

I have deployed 2 bootnodes, 6 signing nodes and 2 standard nodes.

My nodes rarely find each other via them or do with difficulty/time and usually i have to opt for the using ```addPeer``` or ```static-nodes.json``` to get them talking to each other.

its not a networking issue as i can locate and connect using netcat ```nc -nv -u ipaddress 30301``` and my aws security group is open to receiving UDP packets on port 30301 (even tried TCP for the hell of it)

From what i see to get a reliable operating network you need each node and signer to be able to discover more than 1 other node, so far when any node actually manages to discover another it seems to only add 1 peer maximum (even though i have 2 bootnodes). 

Im guessing this is a fault of the go-ethereum core for the bootnode, i saw elsewhere that you guys operate full nodes as bootnodes for the rinkeby network, perhaps this is the best option ? [after testing this method i can confirm better reliability]

Can anyone offer more insight into how to operate the correct ratio of bootnodes to ensure a sufficient level of connectivity/discoverability.

**Comment by Swader** [comment]
Can confirm that nodes have been less reliable as of late via the Puppeth approach. [This approach](https://bitfalls.com/2018/03/25/run-private-ethereum-blockchain/) still works OK.

**Comment by REPTILEHAUS** [comment]
Is that a shameless plug for your blog 😂

I dont see anything about bootnodes in your article, did i miss something ? 

Also I did not deploy via puppeth each instance was setup/compiled individually on each server using only a shared genesis
