### ISSUE TITLE
Cant listen events in GETH

### ISSUE THREAD

**Issue by freezepro** [ethereum/go-ethereum#16906]
I  managed to connect to local parity node with following code, but same code doesn't work with GETH node. Issue with parity is that it's not syncronizing fast. 
Tried other versions(such as contract.events.MyEvent, getPastEvents), nothing works with GETH. 

source code: 

const Web3 = require('web3'); var web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:8545'));

var MyContract = web3.eth.contract(abi); var contractInstance = MyContract.at('0xFFF...');

var events = contractInstance.Transfer({},{fromBlock: 3900000, toBlock: 'latest'});

var i = 0; events.watch(function (error, result) { console.log(i++ + ": " + JSON.stringify(result));

fs.appendFileSync("eosregister.txt", i++ + ": " + JSON.stringify(result) + ' \r\n');
});

**Comment by RuslanMirov** [comment]
I have the same issue!
