### ISSUE TITLE
Puppeth: Dockerfile Parse Error deploying sealer to network

### ISSUE THREAD

**Issue by Swader** [ethereum/go-ethereum#16905]
When using Puppeth to deploy two sealer nodes to two different VMs on my subnet (Vagrant machines) one of which already holds a bootnode (successfully deployed), Puppeth fails to build a sealnode with the message `Dockerfile Parse Error` and the content:

```
Dockerfile parse error line 13: unknown instruction: "9A958F419E038F49D088A581006C298FACAF8B4667C61B23AACD33574062F05FBE034913BB27B2D8F3E1A2EA61CC1DE78DBAC876A536FA8F583ACE14B7AB6A5A@192.168.10.10:30303
```

This indicates that there's an interpolation error in the Dockerfile somewhere where the enode address of the bootnode is being given to Docker as a command, rather than escaped. I don't know how to find out which Dockerfile to check to fix this and send a PR.

I should note that up until recently (updated Virtualbox and Vagrant, and the [base box](http://www.sitepoint.com/quick-tip-get-homestead-vagrant-vm-running/)) this same process worked fine, as described in this tutorial that is soon coming out on SitePoint.com: [draft](https://gist.github.com/Swader/621c4fed3ea11c74a37983db95e476bb).

#### System information

Geth version: 1.8.10-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.2
Operating System: darwin

#### Expected behaviour

Sealnode gets deployed as usual. No errors from Docker.

#### Actual behaviour

Error from Docker:

```
Dockerfile parse error line 13: unknown instruction: "9A958F419E038F49D088A581006C298FACAF8B4667C61B23AACD33574062F05FBE034913BB27B2D8F3E1A2EA61CC1DE78DBAC876A536FA8F583ACE14B7AB6A5A@192.168.10.10:30303
```

#### Steps to reproduce the behaviour

Follow the steps from [this tutorial](https://gist.github.com/Swader/621c4fed3ea11c74a37983db95e476bb).

**Comment by Swader** [comment]
Having compiled the tools locally and disabled the cleanup operation post-deploy, I was able to retrieve the generated Dockerfile. It is indeed invalid due to an unsilenced warning being inserted before the enode address:

```
FROM ethereum/client-go:latest

ADD genesis.json /genesis.json

        ADD signer.json /signer.json
        ADD signer.pass /signer.pass

RUN \
  echo 'geth --cache 512 init /genesis.json' > geth.sh && \
        echo 'mkdir -p /root/.ethereum/keystore/ && cp /signer.json /root/.ethereum/keystore/' >> geth.sh && \
        echo $'geth --networkid 60945 --cache 512 --port 30301 --maxpeers 50  --ethstats \'sealone:tns@192.168.10.10:8081\' --bootnodes enode://WARN [06-06|08:02:04] Sanitizing cache to Go's GC limits       provided=1024 updated=664
"14de96bf34c0c7952b580729e7a41019e88ce2f1a55797ed723390d104aa83088c1521b84e7a5325adf16974b75a3e77b7deb34b027576ae461adca1832bcbc2@192.168.10.10:30303  --unlock 0 --password /signer.pass --mine --targetgaslimit 4700000 --gasprice 18000000000' >> geth.sh

ENTRYPOINT ["/bin/sh", "geth.sh"]
```

**Comment by karalabe** [comment]
Ah damn it, thanks for catching this.

**Comment by Christopher-Hayes** [comment]
This is a relief. First time using Puppeth, thought I was doing something wrong lol. Couldn't figure anything out until local compiling as well. Any ideas on how to fix this in the meantime? For now, I've hardcoded my bootnodes into the module_node.go file.

**Comment by Swader** [comment]
You can comment this line in `module_go`:

```
defer client.Run("rm -rf " + workdir)
```

This will keep the Dockerfile in place on the remote machine, letting you manually run it after you correct the bootnode address in the file. That way you can still dynamically generate the sealer nodes but you have manual step to actual run them.

I'm trying to figure out at which point this warning crops up so I can fix the problem but I'm not as familiar with go as I'd want to be so it's too easy to want to resort to simple string stripping which would be a hack. Hope to have more insight soon.

**Comment by Christopher-Hayes** [comment]
It looks like commit #16800 is causing the problem. I don't know Go, so I'm not sure how to resolve this. For now, removing the log warning on line 200 allows the sealers to correctly deploy.

**Comment by Swader** [comment]
@Christopher-Hayes this fix didn't do it for me because I'd need to rebuild the geth in destination servers too it seems. Currently easier to remove deletion or strip the string in the Puppeth implementation.

**Comment by Swader** [comment]
Days later, I couldn't get through dependency hell and find out where this first occurs. If I debug `w.conf.bootnodes` at L86 of `wizard_intro.go`, it'll produce an empty array. If I check in `wizard_node.go` right after the `deployNode` function opens, the error is already there in bootnodes. It's as if somewhere in between it tries to read bootnodes specifically and gets that warning as output, prepending the bootnode address with it, and I'm at a loss as to where this happens. I think I'll have to throw in the towel and defer to @karalabe

**Comment by Swader** [comment]
Disabling the logger with `DiscardHandler` in `module_node.go` on line 221 also does not help, but that's where this problem occurs. In fact, it's the line which executes `docker exec %s_%s_1 geth --exec admin.nodeInfo.id attach` that produces this result in the terminal. If you test this directly where the node is running, it appears in the output of the terminal:

<img width="878" alt="screenshot 2018-06-16 15 16 23" src="https://user-images.githubusercontent.com/1430603/41498882-44020b44-7178-11e8-9134-09d9ba1927a7.png">

This is why the disabling of the logger had no effect, since the warning occurs where geth is running, not where it's launched from.

I'll get to the bottom of this and solve it without string stripping if it kills me.

**Comment by Swader** [comment]
Got it.
This was a fun exploration of Go and Geth in general.

**Comment by athenawisdoms** [comment]
Is there an earlier version of ethereum that we can compile from that will avoid this problem 

> Dockerfile parse error line 13: unknown instruction: ...
