### ISSUE TITLE
json web3_sha3 appears not to be working

### ISSUE THREAD

**Issue by Gagabits** [ethereum/go-ethereum#1691]
{"method": "web3_sha3", "jsonrpc": "2.0", "params": ["hello"]}

... yields:

{u'id': None, u'jsonrpc': u'2.0', u'result': u'0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'}

... which is the sha3 of an empty string.

Maybe I'm calling it incorrectly?

**Comment by obscuren** [comment]
try `{"method":"web3_sha3", "params":["0x68656c6c6f"]}`.

The RPC expects hex at all times

**Comment by Gagabits** [comment]
Ohhhhh! Thanks!

**Comment by tgerring** [comment]
Indeed as @obscuren mentioned, you must send hex, as the RPC knows nothing about the encoding of the data, i.e. ASCII. Just to demo:

"hello"
```
$ curl -X POST --data '{"method": "web3_sha3", "jsonrpc": "2.0", "params": ["hello"]}' http://127.0.01:8545
{"id":null,"jsonrpc":"2.0","result":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"}
```

Empty string (same)
```
$ curl -X POST --data '{"method": "web3_sha3", "jsonrpc": "2.0", "params": [""]}' http://127.0.01:8545
{"id":null,"jsonrpc":"2.0","result":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"}
```

"hello" ASCII encoded to hex:
```
$ curl -X POST --data '{"method": "web3_sha3", "jsonrpc": "2.0", "params": ["0x68656c6c6f"]}' http://127.0.01:8545
{"id":null,"jsonrpc":"2.0","result":"0x1c8aff950685c2ed4bc3174f3472287b56d9517b9c948127319a09a7a36deac8"}
```
