### ISSUE TITLE
listsinceblock rpc

### ISSUE THREAD

**Issue by Akira-Taniguchi** [ethereum/go-ethereum#16911]
I want to get all transactions infomation relation of owne's accounts.

if there was an equivalent to bitcoind's listsinceblock command, which lists all transactions relevant to the given account, since a particular block.

so I'm happy.

**Comment by RichHorrocks** [comment]
Please keep the issue tracker clear for actual issues.

The best places to ask questions like yours are Stack Exchange (https://ethereum.stackexchange.com), Reddit (https://www.reddit.com/r/ethdev/), or Gitter (https://gitter.im/ethereum/home).
