### ISSUE TITLE
how does geth cmd deploy two dependency contract?

### ISSUE THREAD

**Issue by huzhengkui** [ethereum/go-ethereum#16913]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
1 contract A and contract B can deploy successfully
2  A can call the function of B 

#### Actual behaviour
A call function of B failed

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
This question is not really relevant to Geth, rather it's a general Ethereum related question. You can deploy them sequentially, and then initialize the first with the second's address. For more, please ask on the stack exchange.
