### ISSUE TITLE
Geth not able to sync, `pong timeout` when using --verbosity 9

### ISSUE THREAD

**Issue by postables** [ethereum/go-ethereum#16918]
I'm unable to sync my geth nodes anymore, continuously getting this error

```
TRACE[06-06|22:16:37] <-net.queryReq 
TRACE[06-06|22:16:37] <-net.timeout 
TRACE[06-06|22:16:37]                                          msg="--- (2) pongTimeout for a24ac7c5484ef4ed@....:30303: verifyinit -> unknown (ok)"
TRACE[06-06|22:16:37] <-net.timeout 
TRACE[06-06|22:16:37]                                          msg="--- (1) pongTimeout for 343149e4feefa15d@.....:30303: verifyinit -> unknown (ok)"
TRACE[06-06|22:16:37] <-net.timeout 
TRACE[06-06|22:16:37]                                          msg="--- (0) pongTimeout for b6b28890b0067436@.....:30303: verifyinit -> unknown (ok)"
TRACE[06-06|22:16:37] <-net.refreshDone                        table size=0
```

**Comment by karalabe** [comment]
That shouldn't be an issue, it only means a remote peer is unreachable. There are many such peers who for example are firewalled.

**Comment by postables** [comment]
Well I'm getting this for every single peer my node can connect to. I have made 10000% sure I allowed ports 30303 UDP, and I tried 30303 TCP as well. Also tried port forwarding directly to my node which didn't work. What kind of information/files/logs do I need to provide to get this debugged?

**Comment by postables** [comment]
It looks like surricata on my firewall was catching geth traffic and banning it.
