### ISSUE TITLE
How can I add some log into geth code so I can get all the internal txs while syncing

### ISSUE THREAD

**Issue by JacobDenver007** [ethereum/go-ethereum#16916]
Hi there,
Now I need to get all the history internal transactions, but using debug trace cost too much time, I came up with an idea that I can add some log into your code, so that I do not need to open vmdebug while starting geth, and I can also analyze all the Internal Transactions by log.
Here is an example, code path is go-ethereum/core/vm/evm.go, and I add these logs in the function Call:

![image](https://user-images.githubusercontent.com/29848184/41075867-45349b96-6a41-11e8-9e1c-5a50484d3088.png)

I add the logs into Call,CallCode and Create functions, but I have a problem about SELFDESTRUCT actions,where can I add my logs to get SELFDESTRUCT actions,thanks very much

**Comment by karalabe** [comment]
You could hack it into https://github.com/ethereum/go-ethereum/blob/master/core/vm/instructions.go#L796.
