### ISSUE TITLE
[Puppeth] Unable to open puppeth when multiple remote servers are added to puppeth config

### ISSUE THREAD

**Issue by Swader** [ethereum/go-ethereum#16938]
#### System information

Geth version: 1.8.10-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.2
Operating System: darwin

#### Expected behaviour

After asking for SSH passwords, Puppeth should connect to both servers for health check.

#### Actual behaviour

After asking for both SSH passwords at once, Puppeth seems to consider one of its own questions as the answer to the other, erroring out on any input provided, barring access. Inputting a correct password is considered incorrect. If only one server is added, everything works fine. If both servers are removed from the config file and re-added after running, all runs fine until the next time Puppeth is closed and relaunched.

#### Steps to reproduce the behaviour

Add 2 remote servers to Puppeth, close and re-open Puppeth.

![screenshot 2018-06-10 15 46 35](https://user-images.githubusercontent.com/1430603/41202203-ed33b53a-6cc5-11e8-8f43-81c9ed30ce70.png)

**Comment by karalabe** [comment]
Whooops, indeed i didn't think about this concurrency issue when I made the servers concurrently health checked. Will need to ponder about it a bit. Maybe we could make dialing sequential and only the health checks concurrent. Or perhaps we should add some "locking" to access the io functionality.
