### ISSUE TITLE
gasLimit gets really high on private chain. Return value should be BigNumber

### ISSUE THREAD

**Issue by Georgi87** [ethereum/go-ethereum#1693]
Running my local geth network, I get a really high gaslimit for a block at block 6000+:

gasLimit: 1.2485082395495132e+73

This value is returned in when calling eth.getBlock('latest')

**Comment by fjl** [comment]
What version are you running, from develop?
What does the RPC API return?

**Comment by fjl** [comment]
I'm guessing that this is a web3.js issue.
