### ISSUE TITLE
[CLIQUE] Call to non existing smart contract freezes the blockchain

### ISSUE THREAD

**Issue by obale** [ethereum/go-ethereum#16948]
Starting from geth version `v1.8.4` I am experiencing blockchain (sealing) freeze after calling a non existing smart contract. Tested also with the latest version, `v1.8.10`.

#### System information

Geth version: >= `Geth/v1.8.4-stable/linux-amd64/go1.10.2`
OS & Version: Linux (containerized version of geth based on alpine:3.7 docker image)

#### Expected behaviour

Blockchain continues generating new blocks according to the protocol. Previous version, i.e. `v1.8.3` and lower, work without issue.

#### Actual behaviour

Blockchain freezes completely, i.e. does not generate new blocks. No further interactions are possible, e.g. Nonce queries fail too.

#### Steps to reproduce the behaviour

1. Start a private blockchain with Proof of Authority (clique) as consensus algorithm. The genesis block contains the following config part:

```json
  "config": {
    "chainId": 15,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "byzantiumBlock": 4,
    "clique": {
      "period": 1,
      "epoch": 30000
    }
  },
```

The testing blockchain consisted of 3 sealers and 1 read-only node.

2. Execute a smart contract call on a smart contract address that does not exists, e.g. by keeping

#### Log output sealer 1

```
INFO [06-11|18:48:20] 🔗 block reached canonical chain          number=16 hash=4eac49…012746
INFO [06-11|18:48:21] Successfully sealed new block            number=22 hash=b1dc61…8b0a5d
INFO [06-11|18:48:21] 🔨 mined potential block                  number=22 hash=b1dc61…8b0a5d
INFO [06-11|18:48:21] Commit new mining work                   number=23 txs=1 uncles=0 elapsed=2.863ms
INFO [06-11|18:48:21] Signed recently, must wait for others
INFO [06-11|18:48:22] Imported new chain segment               blocks=1 txs=1 mgas=0.029 elapsed=1.255ms   mgasps=22.759 number=23 hash=22f503…c80294 cache=1.10kB
ERROR[06-11|18:48:22] Failed to create mining context          err="missing trie node 2c21abc3f5139f91fc87c43684cc0bc8a119020d40c4bec0ebdf6a8efb74e430 (path )"
ERROR[06-11|18:48:22] Failed to reset txpool state             err="missing trie node 2c21abc3f5139f91fc87c43684cc0bc8a119020d40c4bec0ebdf6a8efb74e430 (path )"
INFO [06-11|18:48:22] Imported new chain segment               blocks=1 txs=1 mgas=0.029 elapsed=2.634ms   mgasps=10.842 number=23 hash=87e47c…4f9c45 cache=1.54kB
```

#### Log output sealer 2

```
INFO [06-11|18:48:20] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=241.015µs mgasps=0.000 number=21 hash=1974b9…022587 cache=0.00B
INFO [06-11|18:48:20] Commit new mining work                   number=22 txs=0 uncles=0 elapsed=134.909µs
INFO [06-11|18:48:21] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=949.229µs mgasps=0.000 number=22 hash=b1dc61…8b0a5d cache=0.00B
INFO [06-11|18:48:21] Commit new mining work                   number=23 txs=1 uncles=0 elapsed=545.254µs
INFO [06-11|18:48:21] 🔗 block reached canonical chain          number=17 hash=e7ef9d…fda0c1
INFO [06-11|18:48:22] Successfully sealed new block            number=23 hash=22f503…c80294
INFO [06-11|18:48:22] 🔨 mined potential block                  number=23 hash=22f503…c80294
ERROR[06-11|18:48:22] Failed to reset txpool state             err="missing trie node 2c21abc3f5139f91fc87c43684cc0bc8a119020d40c4bec0ebdf6a8efb74e430 (path )"
ERROR[06-11|18:48:22] Failed to create mining context          err="missing trie node 2c21abc3f5139f91fc87c43684cc0bc8a119020d40c4bec0ebdf6a8efb74e430 (path )"
INFO [06-11|18:48:22] Imported new chain segment               blocks=1 txs=1 mgas=0.029 elapsed=2.513ms   mgasps=11.367 number=23 hash=87e47c…4f9c45 cache=1.54kB 
```

#### Log output sealer 3

```
INFO [06-11|18:48:20] Successfully sealed new block            number=21 hash=1974b9…022587
INFO [06-11|18:48:20] 🔨 mined potential block                  number=21 hash=1974b9…022587
INFO [06-11|18:48:20] Commit new mining work                   number=22 txs=0 uncles=0 elapsed=1.695ms
INFO [06-11|18:48:20] Signed recently, must wait for others
INFO [06-11|18:48:21] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=257.557µs mgasps=0.000 number=22 hash=b1dc61…8b0a5d cache=0.00B
INFO [06-11|18:48:21] Commit new mining work                   number=23 txs=1 uncles=0 elapsed=492.28µs
INFO [06-11|18:48:22] Imported new chain segment               blocks=1 txs=1 mgas=0.029 elapsed=936.894µs mgasps=30.492 number=23 hash=22f503…c80294 cache=1.10kB
ERROR[06-11|18:48:22] Failed to create mining context          err="missing trie node 2c21abc3f5139f91fc87c43684cc0bc8a119020d40c4bec0ebdf6a8efb74e430 (path )"
ERROR[06-11|18:48:22] Failed to reset txpool state             err="missing trie node 2c21abc3f5139f91fc87c43684cc0bc8a119020d40c4bec0ebdf6a8efb74e430 (path )"
INFO [06-11|18:48:22] Successfully sealed new block            number=23 hash=87e47c…4f9c45
INFO [06-11|18:48:22] 🔗 block reached canonical chain          number=18 hash=637201…e0cf8d
INFO [06-11|18:48:22] 🔨 mined potential block                  number=23 hash=87e47c…4f9c45
```

**Comment by karalabe** [comment]
Could you give an example of a contract call that you tried to execute? I've tried doing calls in `--dev` (which is itself a PoA network), but it seems to have worked just fine.

**Comment by holiman** [comment]
A stack trace would be useful too. If ordinary RPC queries like nonce check fails, it's indicative of a deadlock imo. Hitting ctrl-c nine times should do it, in case `debug.stacks()` is unavailable.

**Comment by obale** [comment]
@karalabe I can't share the specific code, but it is a rather simple call that adds a new struct to a mapping. It is strictly an internal call, i.e. does not call out to any other smart contract.

It basically takes the input parameters and stores them in a struct. This struct is then added to a mapping with a keccak256 hash as identifier. 

Maybe some important details:
- The created struct stores the `block.timestamp` value
- At the end of the function call an event is emitted
- An assert statement is used to assure that the newly created struct does not exists in the mapping

**Comment by obale** [comment]
@holiman I have attached the output of the `debug.stacks()` call.

[geth_sealer_debug_stacks.txt](https://github.com/ethereum/go-ethereum/files/2094815/geth_sealer_debug_stacks.txt)

**Comment by obale** [comment]
The problem persists with the latest version `Geth/v1.8.13-stable/linux-amd64/go1.10.3`

**Comment by vdamle** [comment]
On both `Geth/v1.8.12-stable` and `Geth/v1.8.13-stable`, I am seeing the same behavior in a 4 node Clique (POA) network, albeit when *deploying* a `simple storage` contract. The same error message is displayed in the log and the nodes stall soon after. It definitely appears that Clique/POA is broken. Is there any additional diagnostic I could provide?

**Comment by vdamle** [comment]
@obale  @karalabe - After some experimenting, I found the following:

* After setting `"eip158Block": 0` in `genesis.json` and re-creating the chain, I can submit transactions and invoke `set()` on a simple storage contract successfully; no longer see the error and stalling chain.
* However, `get()` continued to fail with `Error: Couldn't decode uint256 from ABI: 0x` error from web3/solidity. To resolve this I had to change `"homesteadBlock": 0` in `genesis.json`. Ref: @karalabe 's recommendation in #3653

Both of the above require re-create of the chain? Is there no other way out?

**Comment by obale** [comment]
@vdamle thank you for the insight. I can confirm that adding `"eip158Block": 0` and `"homesteadBlock": 0`  to the genesis block solves this specific issue. Tested with `Geth/v1.8.13-stable/linux-amd64/go1.10.3`. 

I would have to do more testing to assure that there are no side-effects.

**Comment by vdamle** [comment]
One more datapoint. When I tried migrating/upgrading a chain on `Geth/v1.7.3-stable-4bb3c89d` to  `Geth/v1.8.13-stable-225171a4`:

* new contracts can be deployed on `Geth/v1.8.13` after migration
* web3 "set" transactions can be executed without errors on contracts that were deployed on `1.7.3`
* web3 "get" transactions fail with `Error: Couldn't decode uint256 from ABI: 0x`. Unfortunately, this requires the change to set `homesteadBlock: 0`

Is there any way to "update" genesis config before/after migration (rolling or otherwise) without having to lose chain data?
