### ISSUE TITLE
eth_pendingTransactions takes a long time to complete

### ISSUE THREAD

**Issue by vogelito** [ethereum/go-ethereum#16940]
#### System information

Geth version:
```
# /home/ubuntu/geth/current/geth version
Geth
Version: 1.8.10-stable
Git Commit: eae63c511ceafab14b92e274c1b18bf1700e2d3d
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

#### Expected behaviour
RPC calls shouldn't take too long (not sure what would be acceptable, but 10+ seconds seems to be in the realm of unacceptable)

#### Actual behaviour
eth_pendingTransactions consistenly takes over 10 seconds to complete

#### Steps to reproduce the behaviour
In our case, just launch node and make the rpc call:
```shell
$ time curl -X POST localhost:8545 -d '{"jsonrpc":"2.0","method":"eth_pendingTransactions","params":[ ],"id":1}' -H 'Content-Type: application/json' 
{"jsonrpc":"2.0","id":1,"result":[]}

real    0m11.187s
user    0m0.004s
sys    0m0.000s
```

**Comment by karalabe** [comment]
Whoah, that's insane. How many accounts do you maintain?

**Comment by vogelito** [comment]
We have over 200,000 in this particular node:
```
> eth.accounts.length
213273
```

**Comment by karalabe** [comment]
That explains it. Opened a PR to address the issue https://github.com/ethereum/go-ethereum/pull/16958.

**Comment by vogelito** [comment]
Just reporting back. The latest release dramatically improves this. Thanks.

```shell
$ time curl -X POST localhost:8545 -d '{"jsonrpc":"2.0","method":"eth_pendingTransactions","params":[ ],"id":1}' -H 'Content-Type: application/json' 
{"jsonrpc":"2.0","id":1,"result":[]}

real	0m0.468s
user	0m0.008s
sys	0m0.000s
```
