### ISSUE TITLE
how to take a short time to fast sync all blockchain data

### ISSUE THREAD

**Issue by chenzww** [ethereum/go-ethereum#16952]
I used the follow command to fast sync blockchain data.
$ geth --cache 1024 --maxpeers 300 --fast

I found fast sync will auto been disabled when blockchain's size arrive about 96GB. Then, the  increase in blockchain size becomes very slow(about 1GB/day). It may take 2~3 months to sync.  It there a really way to fast sync all blockchain data? 

#### System information

Geth version: `geth 1.8.10-stable`
OS & Version: macOS 10.13.5

**Comment by rexxxxyyy** [comment]
I got the same situation.

About 90GB data synchronization in front is completed in a few hours, and the data files will not increase in a few days. I don't think the synchronization can never be done.
 I developed a smart contract. Is there any other way to use it?

System information:
Geth version: geth 1.8.10-stable
OS:Centent OS 7
300GB SSD
