### ISSUE TITLE
Docker run go-ethereum Error: socket hang up

### ISSUE THREAD

**Issue by webprokopenko** [ethereum/go-ethereum#16956]
Hi there,
I'm just run commnad 
docker run -it -p 8545:8545 -p 30303:30303 ethereum/client-go --rpc --rpcapi db,eth,net,web3,personal --rpcaddr "127.0.0.1" --syncmode "fast" --rpccorsdomain "*" --bootnodes "enode://94c15d1b9e2fe7ce56e458b9a3b672ef11894ddedd0c6f247e0f1d3487f52b66208fb4aeb8179fce6e3a749ea93ed147c37976d67af557508d199d9594c35f09@192.81.208.223:30303,enode://865a63255b3bb68023b6bffd5095118fcc13e79dcf014fe4e47e065c350c7cc72af2e53eff895f11ba1bbb6a2b33271c1116ee870f266618eadfc2e78aa7349c@52.176.100.77:30303,enode://30b7ab30a01c124a6cceca36863ece12c4f5fa68e3ba9b0b51407ccc002eeed3b3102d20a88f1c1d3c3154e2449317b8ef95090e77b312d5cc39354f86d5d606@52.176.7.10:30303,enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303"

After run docker I try to connect to ETH on port 8545 and get Error message: 
Error: socket hang up

In local machine geth-client run good. In docker I get error.
Please help.

**Comment by karalabe** [comment]
`--rpcaddr "127.0.0.1"` means you can only access it from the same OS the process is running on (i.e. form within docker). You'd need to allow all interfaces to access geth within docker and limit it to localhost on your host machine.

**Comment by webprokopenko** [comment]
Thank you. You can tell me how i can do allow interfaces to access geth within docker in OSx?

**Comment by webprokopenko** [comment]
sdf
