### ISSUE TITLE
eth_submitHashrate problem 

### ISSUE THREAD

**Issue by CryptoSiD** [ethereum/go-ethereum#1695]
I'm running the last ethminer.exe from ethereum++ 0.9.41 and its complaining:
  X  15:47:52|main  Failed to submit hashrate.
  X  15:47:52|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented

look like the eth_submitHarate have been implemented into geth: https://github.com/ethereum/go-ethereum/pull/1675

but the last geth from https://github.com/ethereum/go-ethereum/releases (for windows) don't support this call

can someone compile the last source and add it to the releases page?

P.s I'm running geth 1.0.1.1

**Comment by fjl** [comment]
The releases page is updated whenever we release a new version.
Geth 1.0.2 includes the hashrate API and will be released very soon.

**Comment by CryptoSiD** [comment]
But it's mining anyway even if this error is spamming in ethminer right?

**Comment by CryptoSiD** [comment]
since the new ethminer (from ethereum 0.9.41) try to submit this "eth_submitHashrate" and it's been released I think the geth supporting this call should be released also

**Comment by fjl** [comment]
It should mine. Please report if it doesn't.

**Comment by CryptoSiD** [comment]
I don't know how to verify if it really does mine, unless I get a block I can't confirm it's really mining

**Comment by fjl** [comment]
Can you paste some logs? Does it show "searching for solution" or a similar message?

**Comment by CryptoSiD** [comment]
C:\Users\sid\Desktop>"C:\Program Files\Ethereum 0.9.41\Release\ethminer.exe" -t
1 -G -F http://192.168.1.10:8545
Found suitable OpenCL device [GeForce GTX 750 Ti] with 2147483648 bytes of GPU m
emory
miner  15:57:55|main  Getting work package...
  X  15:57:55|main  Failed to submit hashrate.
  X  15:57:55|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:57:55|main  Grabbing DAG for #356e5a2cÔÇª
  i  15:57:56|<unknown>  Loading full DAG of seedhash: #b903bd76ÔÇª
miner  15:57:56|main  Got work package:
miner  15:57:56|main    Header-hash: 224a5d9c6e304bdee1e23afe80308112596491c83be
20ee116ce69875bed49fc
miner  15:57:56|main    Seedhash: 356e5a2cc1eba076e650ac7473fccc37952b46bc2e419a
200cec0c451dce2336
miner  15:57:56|main    Target: 00000000003f98eb328039d1353905271dc4fbd9e55cafe3
6fe2653185e1c03a
  i  15:57:56|gpuminer0  workLoop 0 #00000000ÔÇª #356e5a2cÔÇª
  i  15:57:56|gpuminer0  Initialising miner...
miner  15:57:56|main  Mining on PoWhash #224a5d9cÔÇª : 0 H/s = 0 hashes / 0.5 s
  X  15:57:56|main  Failed to submit hashrate.
  X  15:57:56|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
Using platform: NVIDIA CUDA
  i  15:57:57|<unknown>  Full DAG loaded
Using device: GeForce GTX 750 Ti(OpenCL 1.2 CUDA)
Printing program log
 
 
Creating one big buffer for the DAG
Loading single big chunk kernels
Mapping one big chunk.
miner  15:57:57|main  Mining on PoWhash #224a5d9cÔÇª : 0 H/s = 0 hashes / 0.676
s
  X  15:57:57|main  Failed to submit hashrate.
  X  15:57:57|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
Creating buffer for header.
Creating mining buffer 0
Creating mining buffer 1
miner  15:57:58|main  Mining on PoWhash #224a5d9cÔÇª : 0 H/s = 0 hashes / 0.518
s
  X  15:57:58|main  Failed to submit hashrate.
  X  15:57:58|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:57:58|main  Mining on PoWhash #224a5d9cÔÇª : 1883991 H/s = 1835008 has
hes / 0.974 s
  X  15:57:59|main  Failed to submit hashrate.
  X  15:57:59|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:57:59|main  Got work package:
miner  15:57:59|main    Header-hash: e3f292a9fc0ad7267afd74bcf38491c569e9659f684
fac08bc41c3fb13e190b8
miner  15:57:59|main    Seedhash: 356e5a2cc1eba076e650ac7473fccc37952b46bc2e419a
200cec0c451dce2336
miner  15:57:59|main    Target: 00000000003f90f9135de0aa5781a74a157d04d165957ce2
79539c5dcba4064e
  i  15:58:00|gpuminer0  workLoop 1 #356e5a2cÔÇª #356e5a2cÔÇª
miner  15:58:00|main  Mining on PoWhash #e3f292a9ÔÇª : 1048576 H/s = 524288 hash
es / 0.5 s
  X  15:58:00|main  Failed to submit hashrate.
  X  15:58:00|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:58:01|main  Mining on PoWhash #e3f292a9ÔÇª : 1842840 H/s = 2097152 has
hes / 1.138 s
  X  15:58:01|main  Failed to submit hashrate.
  X  15:58:01|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:58:03|main  Mining on PoWhash #e3f292a9ÔÇª : 1907132 H/s = 2883584 has
hes / 1.512 s
  X  15:58:03|main  Failed to submit hashrate.
  X  15:58:03|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:58:04|main  Got work package:
miner  15:58:04|main    Header-hash: 78cb585ae8fc56af6c96512ad53a69dda1196116d1e
628192c5d4ad960393f66
miner  15:58:04|main    Seedhash: 356e5a2cc1eba076e650ac7473fccc37952b46bc2e419a
200cec0c451dce2336
miner  15:58:04|main    Target: 00000000003f98ec30e3fad9836047452351e0ebfc147770
e509ece18fc8c60a
  i  15:58:05|gpuminer0  workLoop 1 #356e5a2cÔÇª #356e5a2cÔÇª
miner  15:58:05|main  Mining on PoWhash #78cb585aÔÇª : 1048576 H/s = 524288 hash
es / 0.5 s
  X  15:58:05|main  Failed to submit hashrate.
  X  15:58:06|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:58:07|main  Mining on PoWhash #78cb585aÔÇª : 1877822 H/s = 2621440 has
hes / 1.396 s
  X  15:58:07|main  Failed to submit hashrate.
  X  15:58:07|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:58:08|main  Mining on PoWhash #78cb585aÔÇª : 1887059 H/s = 3145728 has
hes / 1.667 s
  X  15:58:09|main  Failed to submit hashrate.
  X  15:58:09|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:58:10|main  Mining on PoWhash #78cb585aÔÇª : 1882917 H/s = 2359296 has
hes / 1.253 s
  X  15:58:10|main  Failed to submit hashrate.
  X  15:58:10|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:58:11|main  Mining on PoWhash #78cb585aÔÇª : 1884572 H/s = 2621440 has
hes / 1.391 s
  X  15:58:11|main  Failed to submit hashrate.
  X  15:58:11|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:58:12|main  Mining on PoWhash #78cb585aÔÇª : 1885928 H/s = 2621440 has
hes / 1.39 s
  X  15:58:13|main  Failed to submit hashrate.
  X  15:58:13|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:58:14|main  Mining on PoWhash #78cb585aÔÇª : 1884798 H/s = 3145728 has
hes / 1.669 s
  X  15:58:14|main  Failed to submit hashrate.
  X  15:58:14|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:58:15|main  Mining on PoWhash #78cb585aÔÇª : 1885928 H/s = 2359296 has
hes / 1.251 s
  X  15:58:15|main  Failed to submit hashrate.
  X  15:58:15|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:58:16|main  Mining on PoWhash #78cb585aÔÇª : 1882542 H/s = 2097152 has
hes / 1.114 s
  X  15:58:17|main  Failed to submit hashrate.
  X  15:58:17|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:58:18|main  Mining on PoWhash #78cb585aÔÇª : 1884959 H/s = 3670016 has
hes / 1.947 s
  X  15:58:35|main  Failed to submit hashrate.
  X  15:58:35|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented
 
 
miner  15:58:36|main  Got work package:
miner  15:58:36|main    Header-hash: 23a535702c9c02e20021747f06f8ffc5c61a93c1b5a
182c4350bf11f88ce1d1c
miner  15:58:36|main    Seedhash: 356e5a2cc1eba076e650ac7473fccc37952b46bc2e419a
200cec0c451dce2336
miner  15:58:36|main    Target: 00000000003f90fa11a1c5984df58b65580e89e3e7937f56
48d36728dc088d72
  i  15:58:37|gpuminer0  workLoop 1 #356e5a2cÔÇª #356e5a2cÔÇª
miner  15:58:37|main  Mining on PoWhash #23a53570ÔÇª : 1048576 H/s = 524288 hash
es / 0.5 s
  X  15:58:37|main  Failed to submit hashrate.
  X  15:58:37|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented

**Comment by fjl** [comment]
Looks like it's mining.

**Comment by CryptoSiD** [comment]
cool thanks, when is 1.0.2 due for release?

**Comment by fjl** [comment]
I think today or tomorrow.

**Comment by CryptoSiD** [comment]
got 1 block so i can confirm it's mining!

**Comment by billprescott** [comment]
I am still having this issue

X 15:47:52|main Failed to submit hashrate.
X 15:47:52|main Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32601 : METHOD_NOT_FOUND: The method being requ
ested is not available on this server: eth_submitHashrate method not implemented

Using ppa.. have updated but still have this issue.. Has it been released?

**Comment by zelig** [comment]
This is now in the coming release 1.1.0. 
See https://www.reddit.com/r/ethereum/comments/3hv0lg/geth_releases/
