### ISSUE TITLE
`geth --rinkeby` showing incorrect `highestBlock`

### ISSUE THREAD

**Issue by ryana** [ethereum/go-ethereum#16950]
Hi.

I may be fundamentally misunderstanding some part of how geth works, but when I try to sync up a full archival node for Rinkeby, it's trying to pull way more blocks than it should be. It's saying the highestBlock for rinkeby is 3922099 when it should be closer to 2.4M. Is there some kind of reorganization that'll happen locally once the sync is complete? If so, is there a way for the client to know that and display it in `web.admin`? I'm running the same command for mainnet in parallel, and the `highestBlock` for mainnet is correct.

#### System information

```
$ geth version
Geth
Version: 1.8.10-stable
Git Commit: eae63c511ceafab14b92e274c1b18bf1700e2d3d
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```

#### Expected behaviour

When I run the following command, I expect the `highestBlock` to be ~= 2.4M

`geth --maxpeers 25 --syncmode full --rinkeby --gcmode archive --nousb --cache 4096 --port 30304 --datadir /mnt/md0/usr/ethereum-rinkeby/`

#### Actual behaviour

`hightestBlock` is over 3.9M. I cannot figure out what network it's syncing off of. No chains on testnet.etherscan.io have that # of blocks.

```
> web3.eth
{
  accounts: [],
  blockNumber: 2454424,
  coinbase: undefined,
  compile: {
    lll: function(),
    serpent: function(),
    solidity: function()
  },
  defaultAccount: undefined,
  defaultBlock: "latest",
  gasPrice: 53157240237,
  hashrate: 0,
  mining: false,
  pendingTransactions: [],
  protocolVersion: "0x3f",
  syncing: {
    currentBlock: 2454424,
    highestBlock: 3922099,
    knownStates: 0,
    pulledStates: 0,
    startingBlock: 53760
  },
 // ...
```

```
> web3.admin
{
  datadir: "/mnt/md0/usr/ethereum-rinkeby",
  nodeInfo: {
    // ...
    protocols: {
      eth: {
        config: {...},
        difficulty: 76062631199078330000,
        genesis: "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
        head: "0xe54cce1b4ad26b449d03fdec7e9180a938cd368e9b6ca7142d03d7b6876144fb",
        network: 4
      }
    }
  // ...
```

#### Steps to reproduce the behaviour

Run:

`geth --maxpeers 25 --syncmode full --rinkeby --gcmode archive --nousb --cache 4096 --port 30304 --datadir /mnt/md0/usr/ethereum-rinkeby/`

#### Backtrace

N/A

**Comment by skitzofrenicdev** [comment]
11¹ up q
