### ISSUE TITLE
Docker run go-ethereum return Error: socket hang up

### ISSUE THREAD

**Issue by webprokopenko** [ethereum/go-ethereum#16960]
Hi there,
I'm just run command docker run -it -p 8505:8505 ethereum/client-go --rpc --rpcapi db,eth,net,web3,personal --syncmode "fast"
After I try to connect to rpc on port 8505 and I get error Error: socket hang up

**Comment by karalabe** [comment]
It's port 8545, not 8505. And you probably need `--rpcaddr "0.0.0.0"`.
