### ISSUE TITLE
geth console history is not using datadir

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1696]
Geth 1.0.1

history file should be placed in the datadir (instead of the default OS ethereum directory.  history file is alone in being placed in OS dir instead of datadir). Prior report #1273

**Comment by zelig** [comment]
I tried on both linux and mac, and the console history is correctly written in datadir

**Comment by ethers** [comment]
I'm on commit 8f09242  and the history file is being written to ~/.ethereum instead of the datadir...

Geth
Version: 1.1.0
Protocol Versions: [62 61]
Network Id: 1
Go Version: go1.4.2
OS: linux

**Comment by maran** [comment]
I've tried to replicate it but for me if I select a different `datadir` also changes the history file. It looks like [the code is correct here](https://github.com/ethereum/go-ethereum/blob/master/cmd/geth/js.go#L436).

You are sure your `datadir` is not actually set to `~/.ethereum`?

**Comment by ethers** [comment]
Yes I double-checked datadir is correct.  Does geth use config.rlp ?  config.rlp is another file that is being written to ~/.ethereum

**Comment by fjl** [comment]
config.rlp is from cpp-ethereum
