### ISSUE TITLE
how to change a private eth blockchain to public eth blockchain on my pc.

### ISSUE THREAD

**Issue by weiweiloong** [ethereum/go-ethereum#16965]
go-ethereum 
how to change a private eth blockchain to public eth blockchain on my pc.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
