### ISSUE TITLE
Docker run go-ethereum return Error socket hang up

### ISSUE THREAD

**Issue by webprokopenko** [ethereum/go-ethereum#16961]
Hi there,
I'm just run command docker run -it -p 8545:8545 ethereum/client-go --rpc --rpcapi --rpcaddr "0.0.0.0" db,eth,net,web3,personal --syncmode "fast" --rpccorsdomain "*" 
After I try to connect to rpc on port 8545 and I get error Error: socket hang up

**Comment by epheph** [comment]
@webprokopenko your options are out of order.
```--rpcapi --rpcaddr "0.0.0.0" db,eth,net,web3,personal```
should be
```--rpc --rpcaddr "0.0.0.0" --rpcapi db,eth,net,web3,personal```

The rpcapi list must have been interpretted as a positional argument and geth didn't complain. I wonder if that is a bug or if there's a good reason for it?

**Comment by webprokopenko** [comment]
Thanks! It works!!!!!

**Comment by joeytwiddle** [comment]
For others experiencing this error, make sure your RPC ports are not open to the public.

If they are open to the public, you may find your RPC port getting spammed by attackers hoping to withdraw your funds. This spamming can cause you to lose your connection, resulting in the "socket hang up" error.
