### ISSUE TITLE
[CLIQUE] (Any) Contract deployment exceeds block gas limit

### ISSUE THREAD

**Issue by kyriediculous** [ethereum/go-ethereum#16973]
Hi there,

I'm encountering issues trying to deploy contracts onto a newly started Clique chain. The testing or migration works fine on testrpc-sc or ganache, trying to deploy on a clique chain returns block gas limit exception, even on just migrate.sol.

Sending normal ethereum transactions in geth console works... 

I've tried adding gasLimit to truffle config, I've tried default settings for genesis.json, nearly everything.

I've followed this guide: https://hackernoon.com/setup-your-own-private-proof-of-authority-ethereum-network-with-geth-9a0a3750cda8

```
osboxes@osboxes:~/blockchain-programmable-incentives$ truffle test --network clique
Using network 'clique'.

Error: exceeds block gas limit

```

This is my genesis file:
```
{
  "config": {
    "chainId": 999,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "byzantiumBlock": 4,
    "clique": {
      "period": 10,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x5b213529",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000bba513f6e464e9f7d0c08125621e92598b1c28d60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "bba513f6e464e9f7d0c08125621e92598b1c28d6": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```

Starting bootnode:
`devnet$ bootnode -nodekey boot.key -verbosity 9 -addr :30310`

Starting node1:
`geth --datadir node1/ --syncmode 'full' --port 30311 --rpc --rpcaddr 'localhost' --rpcport 8501 --rpcapi 'personal,db,eth,net,web3,txpool,miner' --bootnodes 'enode://cfb21bfd52f947041e020dfac76e51b6c466254053335b1e46107c0bbb1235e654a2fe10a2a23042437120d4233c3475d87e69db308c507c61f98bdc40d07720@127.0.0.1:30301' --networkid 999 --gasprice '1' --unlock '0xbba513f6e464e9f7d0c08125621e92598b1c28d6' --password node1/password.txt --mine`

#### Steps to reproduce the behaviour
1. chain : https://github.com/kyriediculous/clique-test
2. dapp: https://github.com/kyriediculous/blockchain-programmable-incentives

#### Backtrace
```
Error: exceeds block gas limit
    at Object.InvalidResponse (/home/osboxes/.nvm/versions/node/v8.11.2/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /home/osboxes/.nvm/versions/node/v8.11.2/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /home/osboxes/.nvm/versions/node/v8.11.2/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /home/osboxes/.nvm/versions/node/v8.11.2/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/home/osboxes/.nvm/versions/node/v8.11.2/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/osboxes/.nvm/versions/node/v8.11.2/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/home/osboxes/.nvm/versions/node/v8.11.2/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/home/osboxes/.nvm/versions/node/v8.11.2/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/home/osboxes/.nvm/versions/node/v8.11.2/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

# Additional details

Geth
Version: 1.8.9-stable
Git Commit: ff9b14617e73c07dfa028bc477fe86c1e04d80c5
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=/home/osboxes
GOROOT=/usr/local/go

**Comment by karalabe** [comment]
How much gas does your contract deploy cost? Looking [at your configs](https://github.com/kyriediculous/blockchain-programmable-incentives/blob/master/truffle.js), Truffle allows 69B gas for a block, whereas your genesis block starts out with a 4.7M limit. My hunch is that your code requires a bit more gas than 4.7M, causing it to be rejected.

**Comment by kyriediculous** [comment]
Yeah sorry, those is the config file I comitted to github but I've played around with the settings in there.

I've managed to start a single node Clique network succesfully and deploy my contracts so I will be trying to find out where I went wrong. Shouldn't be an issue with Geth I think. 

I'll be back to update !

**Comment by kyriediculous** [comment]
I removed all the parameters from my trufflef config files, it takes no gas or gasLimit options.

Then I increased the gasLimit in my genesis block as you mentioned , now I got two running nodes with gasPrice '0' working correctly. Contracts have been deployed and I can call them using truffle console.

Thansk for your time !

**Comment by KwahuNashoba** [comment]
Hey @kyriediculous, what is the gasLimit you ended up with in genesis block? I tried changing it and it simply will not work. The `web3.eth.getBlock("pending").gasLimit` returns 5003 regardless of what I do and I'm not even able to send ethers via web3 geth console. Reports the same Error: exceeds block gas limit when I try it
