### ISSUE TITLE
100% CPU - Discovery V5 - discv5#querySeeds - rand reader

### ISSUE THREAD

**Issue by bgrieder** [ethereum/go-ethereum#16982]
Hi,

I am using geth as a library (version: 1.8.8) and running nodes on a (private) Clique network.

Whether running these nodes on my MBP OSX (High Sierra) or on Ubuntu VMs, I get 100 % CPU load, even after the network is synced.

Profiling for 120 seconds on OSX, I see that this linked to the call to `rand` reader in `querySeeds`, see this (compressed) SVG  file below [geth.cpu.svg.zip](https://github.com/ethereum/go-ethereum/files/2101983/geth.cpu.svg.zip)

This problem is also clearly visible on the CPU load of the Linux VMs where the entropy daemon `haveged` is under heavy load

<img width="301" alt="image" src="https://user-images.githubusercontent.com/797684/41408463-1382a3c6-6fd3-11e8-9bfa-eb441e5c8d21.png">

Any idea where this is coming from and what I can do about it ?

b.

**Comment by bgrieder** [comment]
Digging a bit in this

The infinite `for` loop in `discv5#loop()` does a select on channel `refreshDone`

```go
		case <-refreshDone:
			log.Trace("<-net.refreshDone", "table size", net.tab.count)
			if net.tab.count != 0 {
                           ...
			} else {
				refreshDone = make(chan struct{})
				net.refresh(refreshDone)
			}
```
The table being empty `net.refresh()` is called which in turns calls `querySeeds`

```go

func (net *Network) refresh(done chan<- struct{}) {
	var seeds []*Node
	if net.db != nil {
		seeds = net.db.querySeeds(seedCount, seedMaxAge)
	}
	if len(seeds) == 0 {
		seeds = net.nursery
	}
	if len(seeds) == 0 {
		log.Trace("no seed nodes found")
		close(done)
		return
	}
...
```

Since no seeds are found, the channel `refreshDone` is close and the loop in `discv5#loop()` spins continuously at maximum CPU.

Being on a private network with a limited numbers of nodes "bootstrapped" with a list in static-nodes.json, the node is unlikely to find any seed and this loop will run at max CPU continuously.

1. Apart for deactivating discovery V5 - which I would like to avoid  - what other options do I have ?
2. More generally, having this loop run continuously without a timer to spin the wheel a bit between runs, seems pretty harsh .. or did I miss something ?

**Comment by zsfelfoldi** [comment]
Thanks for the detailed bug report! I'll try to fix it soon.

**Comment by zsfelfoldi** [comment]
The infinite loop is fixed in https://github.com/ethereum/go-ethereum/pull/16994
Note: discv5 still won't work if there are no seed nodes. You can specify your nodes as v5 bootnodes with the --bootnodesv5 option.
