### ISSUE TITLE
return address.balance returns strange value

### ISSUE THREAD

**Issue by danfinlay** [ethereum/go-ethereum#16999]
Originally opened [at remix](https://github.com/ethereum/solidity/issues/2325)
Then [at MetaMask](https://github.com/MetaMask/metamask-extension/issues/2999#issuecomment-397395577)
Then [here at Geth](https://github.com/ethereum/go-ethereum/issues/14989) (but I think mis-represented, so prematurely closed).

Solidity:
```
pragma solidity ^0.4.11;

contract Test {
  function balanceOfEther(address user) public constant returns (uint256) { return user.balance; } 
}
```

Returns unusual balances when requested from Geth via an eth_call.

For any address, returns:

```
{"jsonrpc":"2.0","id":570283474,"result":"0xfffffffffffffffffffffffffffffffffffffffffffffffffdeb17cb73b0ffff"}
```

**Comment by radek1st** [comment]
I've hit the exactly same issue on Rinkeby for `balance` of normal accounts. I also noticed that for deployed contracts `balance` returns the correct value.

**Comment by holiman** [comment]
We've discussed this; the better solution is to make `gasPrice` zero instead of putting an arbitrarily large lump of money on the sender.

**Comment by holiman** [comment]
I just looked at the code. I'm not sure it's actually geth that sets the balance. We take the arguments, and default to zero: 
```golang
	value := new(big.Int)
	if args.Value != nil {
		value = args.Value.ToInt()
	}
```
Are we sure this isn't some middleware (javascript) adding it?
