### ISSUE TITLE
P2P Encryption

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#170]
Nodes that already know a prior node's ID (by way of either a past session or a trusted intermediary), should be guaranteed that a connection to the same network endpoint is indeed this node. i.e. Make impossible a MitM attack.

Simple *DH key exchange cannot do this.

Following Hello, initial period of handshake involves _either_ ECDH key exchange (if the connecting endpoint doesn't know the node ID) _or_ ECIES encrypted key delivery (if the connecting endpoint knows the node ID). Either way, the connecting node begins the post-Hello handshake.

A. New packets:
- PresentKey (sent by connecting node; key is encrypted by recipients NodeID).
- TODO Alex: ECDHExchange packets 

B. Following the key delivery/exchange, ALL information, including message size and magic number runs through an (AES?) encrypted filter.

**Comment by fjl** [comment]
This is now #240.
