### ISSUE TITLE
geth --dev  not working

### ISSUE THREAD

**Issue by DiptanshuMalviya** [ethereum/go-ethereum#17009]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows
Commit hash : (if `develop`)

#### Expected behaviour
Welcome to the geth JavaScript Console !
instance:
coinbase:
at block:

#### Actual behaviour
Fatal: Error starting protocol stack: Access is denied.

#### Steps to reproduce the behaviour
1) geth --identity "Mytestnode" --datadir "./data" --testnet
2) geth --dev console 
 
#### Backtrace

````
[backtrace]
````

**Comment by mdranger** [comment]
First, you started the GETH to connect to the testnet with "--testnet" and data saved in ./data.
Then, you started another GETH with --dev with default config. 
If you just want to start dev, 
Try:
geth --identity "Mytestnode" --datadir "./data" --dev
Then attach to it with:
geth attach ./data/geth.ipc

**Comment by DiptanshuMalviya** [comment]
Namaste  Sir,

          My name is Diptanshu, I am from INDIA. I want some mentor to help to learn this progrraming each and everything. I just want personal help from you. Please Can u help me. If yes sir if you using please give your whatsapp number.
I hope you will help me 

Thank you

**Comment by adamschmideg** [comment]
The question seems to be answered by https://github.com/ethereum/go-ethereum/issues/17009#issuecomment-398013033 If you think otherwise, you may want to head over to https://ethereum.stackexchange.com
