### ISSUE TITLE
Can't ping bootnode

### ISSUE THREAD

**Issue by MichaelJFlynn** [ethereum/go-ethereum#17000]
Hi there,

I am unable to ping Ethereum Foundation's bootnodes, specifically the ones at

```
"enode://3f1d12044546b76342d59d4a05532c14b85aa669704bfe1f864fe079415aa2c02d743e03218e57a33fb94523adb54032871a6c51b2cc5514cb7c7e35b3ed0a99@13.93.211.84:30303",  // US-WEST
```

and

```
"enode://979b7fa28feeb35a4741660a16076f1943202cb72b6af70d327f053e248bab9ba81760f39d0701ef1d8f89cc1fbd2cacba0710a12cd5314d5e0c9021aa3637f9@5.1.83.226:30303", // DE
```

#### Expected behaviour

When I run a bootnode on my local machine using the command:

./bootnode -nodekey <mykey> -addr :30301 &

I get a response to my implementation's pings. The following is debug output from my Ethereum implementation of the full handshake:

```
sending (Ping 3 (EP 52.4.20.183 30302 30302) (EP 127.0.0.1 30301 30301) 1529094670.59)
received message[ ('127.0.0.1', 30301) ]:
 Verified message hash.
 Verified signature.
 received Pong
 (Pong (EP 127.0.0.1 30302 30302) <echo hash> 1529094688)
received message[ ('127.0.0.1', 30301) ]:
 Verified message hash.
 Verified signature.
 received Ping
  sending Pong response: (Pong (EP 127.0.0.1 30301 30301) <echo hash> 1529094728.61)
sending (Pong (EP 127.0.0.1 30301 30301) <echo hash> 1529094728.61)
```

#### Actual behaviour

When I ping either of the Foundation bootnodes I get no response:

```
Discovery status: 0 peers / 25 min peers / 0 connecting
sending (Ping 3 (EP 52.4.20.183 30302 30302) (EP 13.93.211.84 30303 30303) 1529095141.09)
<no response>
Discovery status: 0 peers / 25 min peers / 0 connecting
sending (Ping 3 (EP 52.4.20.183 30302 30302) (EP 13.93.211.84 30303 30303) 1529095146.09)
<no response>
Discovery status: 0 peers / 25 min peers / 0 connecting
sending (Ping 3 (EP 52.4.20.183 30302 30302) (EP 13.93.211.84 30303 30303) 1529095151.1)
<no response>
```

```
Discovery status: 0 peers / 25 min peers / 0 connecting
sending (Ping 3 (EP 52.4.20.183 30302 30302) (EP 5.1.83.226 30303 30303) 1529095321.1)
<no response>
Discovery status: 0 peers / 25 min peers / 0 connecting
sending (Ping 3 (EP 52.4.20.183 30302 30302) (EP 5.1.83.226 30303 30303) 1529095326.11)
<no response>
Discovery status: 0 peers / 25 min peers / 0 connecting
sending (Ping 3 (EP 52.4.20.183 30302 30302) (EP 5.1.83.226 30303 30303) 1529095331.11)
<no response>
```

For reference, to wrap a packet my implementation first "packs" the packet where a ping might go from:

```
(Ping 3 (EP 52.4.20.183 30302 30302) (EP 5.1.83.226 30303 30303) 1529095717.39)
```

to

```
['\x03', ['4\x04\x14\xb7', 'v^', 'v^'], ['\x05\x01S\xe2', 'v_', 'v_'], '[$&%', []]
```

I then RLP encode the list and append the ping `packet_type` which is 1 to the front:

```
'\x01\xdf\x03\xcb\x844\x04\x14\xb7\x82v^\x82v^\xcb\x84\x05\x01S\xe2\x82v_\x82v_\x84[$&%\xc0'
```

I then do a keccak256 signature and append that:

```
"$\xca\xe4\x9f\xdb\x07\x95_\x0c$\x156%\xd7sP\x9c\x9f}\xeb\xd1\x8cXh\x05\xb5\xf8\xda\x8d\x07\xd9y\x9b\xe7\xd5\xbf+@\xf1\xb93 \x82\x95_\x8c\x83+,\x8c\xddM\xb2\xbf\xc9\xe4\x19\xc1Y\xdancnY4\xb3''\x00\xcf\xa0\x98\x10y\xd5\x88.\xb4\xfd\xe8\xc9\xca\x957V1?\xaf\xb9Y\xfe6\x87\x8f\x8b;\x01\x01\xdf\x03\xcb\x844\x04\x14\xb7\x82v^\x82v^\xcb\x84\x05\x01S\xe2\x82v_\x82v_\x84[$&%\xc0"
```

This then gets sent over UDP. I was able to get a response from the bootnodes until a few months ago. What changed?

**Comment by MichaelJFlynn** [comment]
It could be that my node is blacklisted for some reason, for example because it would turn on and then turn off often, being a "bad citizen" or something. Is that possible?

**Comment by FrankSzendzielarz** [comment]
I see the same issue. Tested c++ and go bootnodes at these mainnet addresses  https://github.com/ethereum/go-ethereum/blob/master/params/bootnodes.go and no response. Testnet addresses work.

**Comment by MichaelJFlynn** [comment]
I'm glad I'm not the only one experiencing this. If the bootnodes moved then this should be reflected at

https://github.com/ethereum/go-ethereum/blob/master/params/bootnodes.go

Hopefully this issue will get some attention because if that is the case it is a relatively easy fix.

**Comment by FrankSzendzielarz** [comment]
I am not sure where such cross platform issues should be addressed. This is not a geth issue, but a c++ and geth mainnet problem. At least, as far as I can see. There is of course the possibility we are somehow both blacklisted, if such a blacklist exists.

**Comment by egalano** [comment]
Running a TCP connection check against these two bootnodes failed:
```
"enode://3f1d12044546b76342d59d4a05532c14b85aa669704bfe1f864fe079415aa2c02d743e03218e57a33fb94523adb54032871a6c51b2cc5514cb7c7e35b3ed0a99@13.93.211.84:30303",  // US-WEST
"enode://78de8a0916848093c73790ead81d1928bec737d565119932b98c6b100d944b7a95e94f847f689fc723399d2e31129d182f7ef3863f2b4c820abbf3ab2722344d@191.235.84.50:30303", // BR
```

Either this list is out of date, or we need to verify the availability of these two nodes.
