### ISSUE TITLE
Can the tokens symbol be the same？？

### ISSUE THREAD

**Issue by shishi614** [ethereum/go-ethereum#17012]
For example, if there is already an ETC token, can I still create code with the symbol ETC?
thanks

**Comment by RaghavSood** [comment]
Yes.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
