### ISSUE TITLE
Survey for developers

### ISSUE THREAD

**Issue by shubhamtbc** [ethereum/go-ethereum#17015]
1.What more features/add-ons does your development platform should have?

2.What extra tools,web service do you use to develop or deploy a dapp?

3.What are the major issues/problems you face while working on truffle or embark to develop or test your dapp?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
