### ISSUE TITLE
Synchronization does not end, does not show balances.

### ISSUE THREAD

**Issue by sviridenkovalera** [ethereum/go-ethereum#17018]
Hi there!

#### System information

Geth version: `Geth/v1.8.11-stable-dea1ce05/linux-amd64/go1.10`
OS & Version: Linux
Commit hash : dea1ce05

Params
/home/ethereumd/geth --fast --cache=2096  --rpc --rpcapi  "utils,db,eth,net,web3,personal"  2>> /home/ethereumd/geth.log

Result: 
![image](https://user-images.githubusercontent.com/4464523/41534307-be70ae28-7306-11e8-970b-5194d23c070f.png)

Why does display block at 0 and not display balance of addresses?

**Comment by ligi** [comment]
> Why does display block at 0 and not display balance of addresses?

this will be the case as long as knownStates > pulledStates

details here: https://github.com/ethereum/go-ethereum/issues/16937#issuecomment-396177891
