### ISSUE TITLE
As soon as I unlock an address, the balance becomes 0.

### ISSUE THREAD

**Issue by ffan0811** [ethereum/go-ethereum#17013]
#### System information

Geth version: `1.8.2`
OS & Version: Linux

It might be helpful to figure out the problem.
Its based on POA Private Network.
Im using Mist wallet Client and -rpc myserverip:rpcport.
I set "balance": "0x200000000000000000000000000000000000000000000000000000000000000" of allocation to two addresses through genesis block.

#### Expected behaviour
Warning : I'm pretty new to this industry, sorry in advance if my explanation is not good enough.

So, I'd like to move some ETH from an address which i made in the geth to another address which also i made in the geth.

What I did is, 

Created a new account by commanding
>personal.newAccount()

Let's say its eth.accounts[0]

I was told I was received 10,000ETH (for testing) from my co worker.
so, When I checked the balance by commanding
>eth.getBalance(eth.accounts[0])

console said 1e+22 which means i was successfully received the coins.

As I wrote above, I wanted to move some ETH from the eth.accounts[0] to another address, so I unlocked the address by commanding
>personal.unlockAccount(eth.accounts[0])

AND! Before I was gonna send ETH to another address, I checked the balance of the eth.accounts[0] again and It said I have 0 ETH?!

#### Steps to reproduce the behaviour
I've tried to move ETH between geth and mist
I've tried to move ETH between geth and geth
I've tried to move ETH through another server with WSL.

this same thing keeps happening to me. Ive been trying for a few days to figure out whats going on.
Please help me!!

**Comment by ligi** [comment]
Most likely your RPC port is open and as soon as you unlock an account the funds get send. There are bots out there doing this. Please do not unlock your account when the RPC port is exposed
