### ISSUE TITLE
How can I sync geth from certain height

### ISSUE THREAD

**Issue by JacobDenver007** [ethereum/go-ethereum#17035]
Hello,
I now want to get debug_trace info from a certain height.
For example, my node's best block is 5100000, but now I want to sync from 5000000, how can I do that,thanks a lot

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
