### ISSUE TITLE
Can you try compressing broadcast packets that generate blocks to increase TPS.

### ISSUE THREAD

**Issue by gantleman** [ethereum/go-ethereum#17039]
Detailed transaction information is available in the packet that generated the block.
And with these detailed transaction information, the node was already obtained from the transaction information broadcast.
So no detailed transaction information is needed in the broadcast of the generated block.
In the broadcast of the generated block, as long as there is a transaction hash, the verification requirement can be satisfied.
If the broadcast transaction data of the generated block is compressed,
Then it will greatly increase the number of transactions within the generated block.
If there is only a transactional hash within the broadcast,
1M size packets can hold 50,000 transaction hash,
Can increase current TPS by 500 times.

**Comment by karalabe** [comment]
The block is not limited in storage size in Ethereum. If doesn't matter how much data you transfer along with a block, the limit is always the amount of gas that transactions can consume in total.

The gas limit itself is limited by transaction processing performance, which is mostly limited by disk IO currently. Until there are better data models, better storage handling etc, reducing network bandwidth requirements won't help scale.
