### ISSUE TITLE
Feature request: RPC listsinceblock equivalent needed

### ISSUE THREAD

**Issue by wildbunny** [ethereum/go-ethereum#1703]
At the moment, searching for customer's deposits entails looping over each individual block's transactions, checking to see if the 'to' parameter = the deposit account. This will scale very badly in performance terms as transaction frequency increases.

It would be great if there was an equivalent to bitcoind's listsinceblock command, which lists all transactions relevant to the given account, since a particular block.

**Comment by maran** [comment]
Just my two cents but wouldn't it make more sense to actually use Ethereum's contract capabilities to build something smarter? I think you might be trying to Bitcoin logic on a system that can do way more. Using a contract with emits logs on deposits would make your use-case much easier most likely.

**Comment by wildbunny** [comment]
Listing transactions that belong to you is a pretty fundamental requirement which really should be part of the client IMO

**Comment by maran** [comment]
The official stance is that if you want this behaviour your contract should support it using LOGn events. @obscuren explains it in more depth here in #1740.

**Comment by wildbunny** [comment]
Isn't this stance forgetting the common user, who is not a dapp developer and just wants to know who they've sent/received ether to/from?

Indeed, I am an exchange owner who doesn't have any contracts - I just need to know what deposits have been made and what transactions I have sent; this is currently highly inefficient because I have to parse the blockchain myself.

**Comment by maran** [comment]
The problem for the common user will be sorted soon with the release of the wallet software. This will create wallet contracts for you and implement easy transaction tracking.

[Have you considered using this system?](https://github.com/ethereum/wiki/wiki/ICAP:-Inter-exchange-Client-Address-Protocol)

**Comment by wildbunny** [comment]
I had briefly glanced at that before, but dismissed it as it looked like a future proposal. In any case, I still don't see an efficient way to list all IBAN transactions addressed to a particular account via RPC? Unless I missed it :)

**Comment by maran** [comment]
That's not really my forté I just see this being listed every time the word exchange pops-up. 

You are of course free to write any contract that fits you ;)

**Comment by wildbunny** [comment]
Not totally sure I see the need to pay ether, or indeed run a distributed application in order to know what transactions are destined for my account? That seems like a pretty fundamental requirement that any API should provide to me.

**Comment by maran** [comment]
I think the general idea is that you don't let people pay to an account but into a contract. That contract sends out log events for each incoming transaction so it's easily to follow in your own systems. This has the added benefit that you can make sure that you have sufficient access control to withdraw money out of your contract. 

Just trying to help, if you want to argue your point I suggest contacting @obscuren since I think he is pretty avidly against building such RPC methods.

**Comment by obscuren** [comment]
Ethereum offers you a platform in which you can address such needs as you described. Extend the functionality of the ethereum network to suit your needs.

If you require he above functionality I suggest you set up some block filter and do as you described. An "address watch list" might be added in the future.

**Comment by wildbunny** [comment]
Not sure how a block filter helps? I need to know about transactions destined for an account. Blocks are pretty regular, so polling isn't a problem.

**Comment by almindor** [comment]
Maybe I'm missing something but I can't imagine 1000s of people requesting transaction history from the blockchain via contracts for these 2 reasons:

1. Too many requests on "peak" times once the usercount goes really high. Don't forget the chain has limited computing power?
2. Don't you have to pay gas each time? Wouldn't that mean that you pay for just listing your transaction history?? That's unacceptable I think.

Maybe I don't understand some aspect of this, if that's the case then I'm sorry for mixing things up.

**Comment by fjl** [comment]
> 1. Too many requests on "peak" times once the usercount goes really
> high. Don't forget the chain has limited computing power? 2. Don't you
> have to pay gas each time? Wouldn't that mean that you pay for just
> listing your transaction history?? That's unacceptable I think.

If you send transactions through a wallet contract that fires log
events, you can read them using the eth_getFilterLogs RPC call. 

In general, keep in mind that you can interact with all data stored in
the blockchain locally, there is no cost or delay involved.

**Comment by apa7** [comment]
Yep, this API is necessary
