### ISSUE TITLE
Node JSON-RPC does not return an information about transactions for some blocks.

### ISSUE THREAD

**Issue by alexey-belous** [ethereum/go-ethereum#17049]
Hi,

I've faced up with following issue: the `eth_getBlockByNumber` request returns empty transactions array for genesis block.

#### System information

Geth
Version: 1.8.10-stable
Git Commit: eae63c511ceafab14b92e274c1b18bf1700e2d3d
Architecture: amd64
Protocol Versions: [63 62]
Go Version: go1.10.1
Operating System: linux

#### Expected behaviour
API returns an information about block with its transactions. According to [etherscan.io](https://etherscan.io/block/0) there must be 8893 transactions.

#### Actual behaviour
API returns an information about block but the transactions array is empty.

#### Steps to reproduce the behaviour
```sh
curl http://localhost:8545 -X POST -H "Content-Type:application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x0", false],"id":1}'
```

**Please note**, that this request to the for another blocks (e.g. for 38e9c5) works fine.

Thanks for any help.

**Comment by karalabe** [comment]
The genesis block doesn't contain transactions. Etherscan is "faking" those to list the initial token holders included in the block. I guess it was simpler for them to inject some fake transactions than to introduce a new class of ether sources.

**Comment by alexey-belous** [comment]
@karalabe, thanks for your help.
