### ISSUE TITLE
What is the block number of synchronization between two nodes？

### ISSUE THREAD

**Issue by IcyLemon** [ethereum/go-ethereum#17047]
Hi,
Suppose I have 2 geth nodes,  after these two nodes run independently for a period of time, suppose the block number of one of them is 10 and another is 5. 

If I invoke "admin.addPeer()" in one of the nodes, after the synchronization,  What is the block number of them, 10, or 15(10+5)?

I test this and found that the result is always the largest of the two numbers, which is 10. If this is true, all of the blocks(5) of another node with smaller block number will be discarded?

Am I right?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by IcyLemon** [comment]
@ligi I got it, Thanks.
