### ISSUE TITLE
miner.hashrate reporting negative value

### ISSUE THREAD

**Issue by sammy007** [ethereum/go-ethereum#1704]
Performed some eth_submitHashrate calls:

    > miner.hashrate
    -3692669456213735000

**Comment by fjl** [comment]
Please provide a sequence of RPC calls that reproduce this problem.

**Comment by sammy007** [comment]
I was wrong, it seems I used wrong input data.

**Comment by vanch** [comment]
@sammy007 I have negative value from time to time. Also, hashrate is way too high for my HW.
`eth.hashrate
2724613526390221000
`
What did you done wrong?

**Comment by sammy007** [comment]
Oh it was long ago, I am not going to even try to reproduce it again.
