### ISSUE TITLE
travis-ci: No output has been received in the last ... The build has been terminated

### ISSUE THREAD

**Issue by cocoahuke** [ethereum/go-ethereum#17059]
https://travis-ci.org/ethereum/go-ethereum/jobs/395633091

```
ok  	github.com/ethereum/go-ethereum/swarm/bmt	2.025s	coverage: 77.3% of statements
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

Does someone know how to fix this ? I need some clues

**Comment by karalabe** [comment]
Apparently swarm tests hung. cc @zelig @gbalint @nonsense

**Comment by gbalint** [comment]
@karalabe Sorry, this is a flakiness in the FUSE tests which already seemed to be solved, but it seems it is still not stable enough. I submitted a PR to disable these tests: https://github.com/ethereum/go-ethereum/pull/17072

**Comment by cocoahuke** [comment]
That problem is solved! Thanks
