### ISSUE TITLE
debug.traceBlock and debug.traceBlockFromFile doesn't accept string hex rlp

### ISSUE THREAD

**Issue by zilm13** [ethereum/go-ethereum#17061]
#### System information

Geth version: 1.8.12
OS & Version: OSX
Commit hash : https://github.com/ethereum/go-ethereum/tree/eaff89291ce998ba4bf9b9816ca8a15c8b85f440

#### Expected behaviour
`debug.traceBlock("0xblock_rlp")` executed in console or using appropriate RPC method should output block's trace. Same when using `debug.traceBlockFromFile`

#### Actual behaviour
when using rlp string with `0x`
```
msg="<-readResp: response {\"jsonrpc\":\"2.0\",\"id\":5,\"error\":{\"code\":-32602,\"message\":\"invalid argument 0: illegal base64 data at input byte 26452\"}}"
Error: invalid argument 0: illegal base64 data at input byte 26452
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```

when using rlp string without `0x`
```
TRACE[06-23|21:45:38.601063|rpc/client.go:555]                                                           msg="<-readResp: response {\"jsonrpc\":\"2.0\",\"id\":6,\"error\":{\"code\":-32000,\"message\":\"could not decode block: rlp: expected input list for types.extblock\"}}"
Error: could not decode block: rlp: expected input list for types.extblock
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```
#### Steps to reproduce the behaviour
Get rlp of any block in console:
```
> debug.getBlockRlp(1)
```
Copy rlp and run
```
debug.traceBlock("0xblock_rlp")
```
#### Additional info
Actually it really expects input in `base64` and if I convert somehow byte data to `base64`, it works well, but it's unusable.

**Comment by fjl** [comment]
This is expected behavior. I don't understand why you say this is unusable, just convert to base64.

**Comment by newtoncx** [comment]
I think it would be good to make an update to the docs.
https://geth.ethereum.org/docs/rpc/ns-debug#debug_traceblock
As OP mentioned, the example shows `0xblock_rlp` which certainly suggests that the block should be in hex. This confused me greatly and I'm sure I won't be the last.
