### ISSUE TITLE
first call to eth_getWork results in a response with empty result

### ISSUE THREAD

**Issue by sammy007** [ethereum/go-ethereum#1706]
After geth started and eth_getWork performed I got the following response:
<code>{"id":73,"jsonrpc":"2.0","result":["","",""]}</code>

I guess this is a reason why ethminer starting to generate DAG sometimes when it shouldn't.

Update: <code>Grabbing DAG for #00000000…</code> after node restart, so yes, at least 1 miner will start generating invalid DAG.

**Comment by sammy007** [comment]
https://github.com/ethereum/cpp-ethereum/issues/2902#issuecomment-134546503

Any status update? That's weird to restart live daemon by blocking port on firewall, then heating up geth and opening port again.

**Comment by Gustav-Simonsson** [comment]
https://github.com/ethereum/go-ethereum/pull/1724

**Comment by sammy007** [comment]
Also, when node is in sync, first response to eth_getWork will be empty anyway.

**Comment by karalabe** [comment]
Hopefully solved by https://github.com/ethereum/go-ethereum/pull/1724, if not, please reopen.

**Comment by sammy007** [comment]
Could you merge this fix to master?

**Comment by karalabe** [comment]
It will be included in the next release. Don't have an exact date bug should be soon enough. Master only receives critical hotfixes out of release schedule. In the mean time, if you really need it, try switching to develop. It is stable and contains quite a few fixes not yet landed in master.
