### ISSUE TITLE
Execution contract results in accounts balance of zero in the POA private network

### ISSUE THREAD

**Issue by matrixpool** [ethereum/go-ethereum#17062]
I encountered some problems in the POA private network, there is only one miner node throughout the network.
My operated steps：
step 1
> eth.getBalance(eth.accounts[2])
0
> eth.getBalance(eth.accounts[1])
10000000000000000000
> eth.getBalance(eth.accounts[0])
2415000000000000

step 2
> eth.sendTransaction({from:eth.accounts[1], to:eth.accounts[0], value: web3.toWei(5, "ether")})
"0x1016df8017baa359d1df90560ac0f9c39350efd9d12c453a4a98a6d92efc242b"

> eth.getBalance(eth.accounts[1])
4997585000000000000
> eth.getBalance(eth.accounts[0])
5004830000000000000

step 3
> lcl.transfer("0xe0fbcf6a385fb078e03fbb43fa8eff669fc015f8", 100000000000, {from:eth.accounts[0]})
Error: insufficient funds for gas * price + value
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at web3.js:4137:16
    at apply (<native code>)
    at web3.js:4223:16
    at <anonymous>:1:1
> eth.getBalance(eth.accounts[1])
0
> eth.getBalance(eth.accounts[2])
0
> eth.getBalance(eth.accounts[0])
4536000000000000

> eth.getBalance("0xcBC36160755f92B007733678B201Eb932c88468A")
5.98631070650737899999999999999995e+51
> eth.gasPrice
115000000000

contract address = "0xcBC36160755f92B007733678B201Eb932c88468A"

I have the following questions：
1) Why is eth.accounts[0] not enough gas? 
2) After executing lcl.transfer, why eth.accounts[0] balance is zero and eth.accounts[1] balance redcued 5ETH?
3) Why gas changed from initial 18Gwei to 115Gwei?
In this case, geth often crashes.

The current environment is as follows:
OS:
CentOS Linux release 7.5.1804 (Core) 

Geth
Version: 1.8.6-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/golang

genesis.conf
{
  "config": {
    "chainId": 33,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "byzantiumBlock": 4,
    "clique": {
      "period": 5,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x5aa62682",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f606a91f7e929bc14794c26a9c6da9dba1b503cf0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "0000000000000000000000000000000000000000": {
      "balance": "0x1"
    },
...
}

Part of the contract code:

    function _transfer(address _from, address _to, uint256 _value) internal {
        require(_from != address(0));
        require(_to != address(0));
        require(balances[_from] >= _value);
        require(balances[_to] + _value >= balances[_to]);

        uint256 previousBalance = safeAdd(balances[_from], balances[_to]);
        balances[_from] = safeSub(balances[_from], _value);
        balances[_to] = safeAdd(balances[_to], _value);
        assert(previousBalance == safeAdd(balances[_from], balances[_to]));

        if(_from.balance < 1*10**18){
            _from.transfer(10*10**18);
        }

        if(_to.balance < 1*10**18){
            _to.transfer(10*10**18);
        }

        Transfer(_from, _to, _value);
    }

    function transfer(address _to, uint256 _value) public returns (bool success){
        require(!frozenAccount[msg.sender]);
        _transfer(msg.sender, _to, _value);

        return true;
    }

**Comment by karalabe** [comment]
There is a lot of code missing from your example here for us to see what's happening. Could you share the code you are calling so we might try to reproduce this ourselves?

**Comment by matrixpool** [comment]
@karalabe is your email peterke@gmail.com？

**Comment by karalabe** [comment]
peter@ethereum.org is probably better for this.

**Comment by juztin** [comment]
I'm glad I'm not the only one pulling my hair out over this one.

```shell
% geth version
Geth
Version: 1.8.13-stable
Git Commit: 225171a4bfcc16bd12a1906b1e0d43d0b18c353b
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

We've been battling this for the last couple weeks, trying to figure out whats causing this _(is it Truffle, Geth, ... ?)_.  
We've had this occur on 3 different private dev nodes. One was running pure Geth on a Ubuntu machine, the other two are running within Docker containers with slightly different configurations. All three are single node instances _(they're just for dev testing)_.

Here's the most recent `genesis.json`:

```json
{
  "config": {
        "chainId": 11,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
  "coinbase"   : "0x0000000000000000000000000000000000000000",
  "difficulty" : "0x100",
  "gasLimit"   : "0x8000000",
  "mixhash"    : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "nonce"      : "0x0000000000000042",
  "parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp"  : "0x0",
  "alloc": {
    "0f87efeb409193a392270585ff7cb070859223fd": { "balance": "9999000000000000000000" }
  }
}
```

Here's the Geth arguments within the container:

```shell
geth \
    --datadir /data/blockchain \
    --networkid 10 \
    --nat any \
    --nodiscover \
    --rpc \
    --rpcaddr 0.0.0.0 \
    --rpcapi web3,eth,personal,miner,net,txpool \
    --rpccorsdomain="*" \
    --ws \
    --wsaddr 0.0.0.0 \
    --metrics \
    --preload /usr/local/bin/miner.js \
    --gcmode archive \
    --password /data/password console
```

And finally, here's the `miner.js` script:

```javascript
var mining_threads = 1
var txBlock = 0

function checkWork() {
  if (eth.getBlock("pending").transactions.length > 0) {
      txBlock = eth.getBlock("pending").number
      if (eth.mining) {
        return;
      }
      console.log("  Transactions pending. Mining...");
      miner.start(mining_threads)
      while (eth.getBlock("latest").number < txBlock + 12) {
        if (eth.getBlock("pending").transactions.length > 0) txBlock = eth.getBlock("pending").number;
      }
      console.log("  12 confirmations achieved; mining stopped.");
      miner.stop();
  }
  else {
    miner.stop();
  }
}

eth.filter("latest", function(err, block) { checkWork(); });
eth.filter("pending", function(err, block) { checkWork(); });

checkWork();
```

We don't use the main account created by Geth (`0f87efeb409193a392270585ff7cb070859223fd`) for anything other than transffering funds. Instead we create additional accounts from either `web3js` or `mist` and transfer funds from the main account to the utility accounts. Usually we can deploy the first round of contracts from one of these accounts just fine. After interacting with the contracts, and attempting to deploy new versions of them is when we start to experience the above issue.

For example:
 - Create new account `0xaa...`
 - Unlock `0xaa...`
 - Deploy contract
 - Test against contract _(call functions, etc.)_
 - Deploy new version of contract from `0xaa...`
 - Gas estimation succeeds, but Truffle/Web3js freeze/fail to ever get an address back
 - Funds for account `0xaa..` drop to zero
 - Adding any amount of funds to `0xaa...` will be zero'd out once another deploy attempt is made

**Comment by karalabe** [comment]
@juztin You are exposing you entire node to the entire internet, and unlocking your account so the entire world can do transactions with your accounts. People are actively scanning for unlocked nodes/accounts and are doing transaction. NEVER expose your node to the internet.

**Comment by juztin** [comment]
Hey @karalabe, it's just an internal private node for testing _(not an exposed/production node at all)_. The only time we're seeing the funds vanish is during the invocation of a transaction.

**Comment by matrixpool** [comment]
it should be a cyber attack against ethereum

**Comment by dwalintukan** [comment]
I have noticed this as well. I start with the correct amount credited to the account as shown in the genesis json and then after I execute a contract deployment the account balance is zero now. Not sure if they are directly related but it seems that way.

**Comment by dwalintukan** [comment]
@juztin Did you ever figure out why this was happening? I am wondering if this is a possible bug or if this was actually a cyber attack.
