### ISSUE TITLE
Whisper: How could we print received messages that are actually stored in the memory when geth was closed or shh.newMessageFilter() is not activated?

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/go-ethereum#17065]
Geth version: `1.8.0-unstable`
OS & Version: Linux

-----------

[Whisper Protocol][1] is not well documented related to its usage. I believe this issue will help other users who might face with similar problem.

Each sent message has time-to-live in seconds (`ttl`), that is defined by the sender. For more detail please see [Whisper v5 RPC API => shh_post][2]. `Whisper Protocol` keeps received messages in the memory until messages' `time-to-live` time is over, when `geth` was closed or `shh.newMessageFilter()` is not activated.

**=>** How could we access and print those received messages that are actually stored in the memory?

------ 

[Whisper v5 RPC API][3]:

> shh_getFilterMessages
> 
> Retrieve messages that match the filter criteria and are received
> between the last time this function was called and now. 

- But there is no `getFilterMessages()` method with the latest `shh`. [Please see][4].

------------

On this [solution][5]; we can use same key pairs after `geth` is restarted.  But the issue after `geth` is restarted and later when we run `shh.newMessageFilter()`; it does not retrieve/return any message that was sent while `geth` was closed.

**[Q]** How could we obtain/filter messages that sent when `geth` was closed or `shh.newMessageFilter()` is not activated?. When we run `web3.shh.newMessageFilter()`, it only retrieves/filters messages right after it start running and it does not filter/print any message before it starts running. 

**Example Scenario:**

**=>** On the receiver node I closed `geth` and from the sender node, I have sent multiple messages into receiver node. Later, when I reopened `geth` on the receiver node, `shh.info.memory` verifies that there are received messages in memory, but I was not able to retrieve/filter those messages using `web3.shh.newMessageFilter()`. 

    > shh.info.memory
    780

--------

**Here is some logs:**

**Creating `web3.shh.newMessageFilter()`:**

    > kId=shh.addPrivateKey('0x8de0b39f3a4a109f27bb06a92dab680d58e8f029eaca61da6be7115981a2ed11')
    "439bfd6aa63a81b404ba20e4fc250e11c326d72ad9943c72dc445f476638989d"

    > filter=web3.shh.newMessageFilter(
    ...         {privateKeyID:kId},
    ...         function(err, res) {console.log(web3.toUtf8(res.payload))});
    {
      callbacks: [function(err, res)],
      filterId: "a0b4194651c9143d977c2fa4848ab681b414720364461b4096fb17588d84ae78",
      formatter: null,
      getLogsCallbacks: [],
      implementation: {
        getLogs: function(),
        newFilter: function(),
        poll: function(),
        uninstallFilter: function()
      },
      options: {
        privateKeyID: "439bfd6aa63a81b404ba20e4fc250e11c326d72ad9943c72dc445f476638989d"
      },
      pollFilters: [],
      requestManager: {
        polls: {
          82f08d2d7fe974a69acdadcfac39f788575d337eed9577969b617ae28462e597: {
            data: {...},
            id: "82f08d2d7fe974a69acdadcfac39f788575d337eed9577969b617ae28462e597",
            callback: function(error, messages),
            uninstall: function()
          },
          a0b4194651c9143d977c2fa4848ab681b414720364461b4096fb17588d84ae78: {
            data: {...},
            id: "a0b4194651c9143d977c2fa4848ab681b414720364461b4096fb17588d84ae78",
            callback: function(error, messages),
            uninstall: function()
          }
        },
        provider: {
          newAccount: function(),
          openWallet: function(),
          send: function github.com/ethereum/go-ethereum/console.(*bridge).Send-fm(),
          sendAsync: function github.com/ethereum/go-ethereum/console.(*bridge).Send-fm(),
          sign: function(),
          unlockAccount: function()
        },
        timeout: {},
        poll: function(),
        reset: function(keepIsSyncing),
        send: function(data),
        sendAsync: function(data, callback),
        sendBatch: function(data, callback),
        setProvider: function(p),
        startPolling: function(data, pollId, callback, uninstall),
        stopPolling: function(pollId)
      },
      get: function(callback),
      stopWatching: function(callback),
      watch: function(callback)
    }

------------

I can see `shh_getFilterMessages` under `filter.requestManager.polls` but I cannot call it.

    > filter.requestManager.polls
    {
      82f08d2d7fe974a69acdadcfac39f788575d337eed9577969b617ae28462e597: {
        data: {
          method: "shh_getFilterMessages",
          params: ["82f08d2d7fe974a69acdadcfac39f788575d337eed9577969b617ae28462e597"]
        },
        id: "82f08d2d7fe974a69acdadcfac39f788575d337eed9577969b617ae28462e597",
        callback: function(error, messages),
        uninstall: function()
      },
      a0b4194651c9143d977c2fa4848ab681b414720364461b4096fb17588d84ae78: {
        data: {
          method: "shh_getFilterMessages",
          params: ["a0b4194651c9143d977c2fa4848ab681b414720364461b4096fb17588d84ae78"]
        },
        id: "a0b4194651c9143d977c2fa4848ab681b414720364461b4096fb17588d84ae78",
        callback: function(error, messages),
        uninstall: function()
      }
    }

    > a.requestManager.polls.82f08d2d7fe974a69acdadcfac39f788575d337eed9577969b617ae28462e597
    (anonymous): Line 1:23 Unexpected token ILLEGAL

  [1]: https://github.com/ethereum/wiki/wiki/Whisper
  [2]: https://github.com/ethereum/go-ethereum/wiki/Whisper-v5-RPC-API#shh_post
  [3]: https://github.com/ethereum/go-ethereum/wiki/Whisper-v5-RPC-API#shh_getfiltermessages
  [4]: https://github.com/ethereum/go-ethereum/issues/16013
  [5]: https://ethereum.stackexchange.com/a/51856/4575

**Comment by gballet** [comment]
This is a multi-dimensional question, here's my best take at it:

  * Most of these messages stored in memory are not intended for you; so listing all the messages make no sense and doesn't justify providing a specific function for this;
  * `newMessageFilter`, like filters for other modules, doesn't work in the console at this stage; there are talks to replace the interpreter to make this possible, but the decision process is still ongoing;
  * A simple way to recover the messages is to connect `wnode` to your geth instance, with the proper key. Or simply to write a `node` app that will get the messages for you.

**Comment by gballet** [comment]
No further work can be done until a new interpreter comes into geth, closing this issue.
