### ISSUE TITLE
Whisper RPC: fails to subscribe with a partial topic

### ISSUE THREAD

**Issue by evgen-povt** [ethereum/go-ethereum#17073]
#### System information
**Geth version:** 
Version: 1.8.12-unstable
Git Commit: 78e03595aff47b5c608896b3d07dca84ec3b6638
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.2
Operating System: linux

**OS & Version:**
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1047-aws x86_64)

#### Expected behaviour
shh_subscribe handles partial topics correclty

#### Actual behaviour
shh_subscribe returns error on receiving partial topic

```
{"jsonrpc":"2.0","id":2,"method":"shh_subscribe","params":["messages",{"topics":["0x332211"],"symKeyID":"65f17a19d311f19d8ae860a76387426f12e82e7ef52879e43312a46ddd3d6f52"}]}
{"jsonrpc":"2.0","id":2,"error":{"code":-32602,"message":"invalid argument 1: hex string has length 6, want 8 for Topic"}}

```
#### Steps to reproduce the behaviour
1. Create a symmetric key
2. Try to call a method shh_subscribe with a topic less than a 4 bytes in length

**Comment by gballet** [comment]
@evgen-povt that rings a bell, I thought this issue had been closed months ago. I'll check it again after devcon.

**Comment by holiman** [comment]
Whisper is no longer part of go-ethereum, it lives on https://github.com/ethereum/whisper
