### ISSUE TITLE
Balance not good after TX 

### ISSUE THREAD

**Issue by perl5577** [ethereum/go-ethereum#1707]
>current  = eth.getBalance('0xfc16bdee46d266b9a18f96e95c6dc3f601b29b61',0xc08a)
'724923307844075364'
> previous = eth.getBalance('0xfc16bdee46d266b9a18f96e95c6dc3f601b29b61',0xc089)
'3750000000000000000'
> delta = current -previous
-3025076692155924500
> tx = eth.getTransaction('0xcc9ed557319aad8a28a658dd3811238c81b4174e061d38851a28c67b8caed7c0')
{
  blockHash: '0xe08cee2c9578a8f481c8b55a5b8164c255ea54f4519e44d4a4c1e4cdd5cb44c8',
  blockNumber: 49290,
  from: '0xfc16bdee46d266b9a18f96e95c6dc3f601b29b61',
  gas: 90000,
  gasPrice: '1160313351653',
  hash: '0xcc9ed557319aad8a28a658dd3811238c81b4174e061d38851a28c67b8caed7c0',
  input: '0x454e544432524d4247',
  nonce: 0,
  to: '0x2910543af39aba0cd09dbb2d50200b3e800a63d2',
  transactionIndex: 0,
  value: '3000000000000000000'
}
> fee = (tx.gas * tx.gasPrice)
104428201648770000

account:'0xfc16bdee46d266b9a18f96e95c6dc3f601b29b61
Send   3 ETH with tx in block 49290

balance_49289 - balance_49290  !=  tx.value +(  tx.gas * tx.gasPrice )
79351509492845364  Wei error 

Difference Is payload ?

**Comment by perl5577** [comment]
in block  49290  "gasUsed":"0x546c"
"0x546c *  tx.gasPrice  , I have the good fee :)

for the block 49290 is easy understand gas used per TX .
If block as more TX ?

**Comment by karalabe** [comment]
https://etherchain.org/tx/0xcc9ed557319aad8a28a658dd3811238c81b4174e061d38851a28c67b8caed7c0

You set a gas price of `1.160313351653 Szabo`. That's about 20-23 times the normal gas price. So you just wasted a whole lot of ether to run the transaction (~24.366 Finney).

So, pre transaction you had 3750 Finney, post transaction you had ~725 Finney. The diff spent on the transaction is hence ~25 Finney, right the amount calculated above with the huge gas price :P

**Comment by perl5577** [comment]
Is not my question :) 

What methode for know amount gas used ? 
I have need at for compute reward from block .
