### ISSUE TITLE
Need help getting my Clo pool going.   Geth is running but I can't see stats for the pool

### ISSUE THREAD

**Issue by ericwilsondc** [ethereum/go-ethereum#17081]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ericwilsondc** [comment]
[Unit]
Description=Callisto for Pool
After=network-online.target

[Service]
ExecStart=/usr/local/bin/geth --callisto --cache=1024 --rpc --extradata "Mined by awesomeminers.com" --ethstats "awesomeminers.com:Callist$
User=airric00

[Install]
WantedBy=multi-user.target

**Comment by ericwilsondc** [comment]
"poolFee": 1.0,
                "poolFeeAddress": "",
                "donate": true,
                "depth": 120,
                "immatureDepth": 20,
                "keepTxFees": false,
                "interval": "10m",
                "daemon": "http://127.0.0.1:8545",
                "timeout": "10s"
        },

        "payouts": {
                "enabled": true,
                "requirePeers": 1,
                "interval": "120m",
                "daemon": "http://127.0.0.1:8545",
                "timeout": "10s",
                "address": "0x0",
                "gas": "21000",
                "gasPrice": "50000000000",
                "autoGas": true,
                "threshold": 500000000,
                "bgsave": false,
                "concurrentTx": 10
        },

        "newrelicEnabled": false,
        "newrelicName": "MyEtherProxy",
        "newrelicKey": "SECRET_KEY",
        "newrelicVerbose": false
}

**Comment by ericwilsondc** [comment]
[Unit]
Description=Etherpool
After=callisto.target

[Service]
Type=simple
ExecStart=/home/airric00/open-callisto-pool/build/bin/open-callisto-pool /home/airric00/open-callisto-pool/config.json

[Install]
WantedBy=multi-user.target

**Comment by ericwilsondc** [comment]
# Default server configuration
# nginx example

upstream api {
    server 127.0.0.1:8080;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    /home/airric00/www;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to displaying a 404.
            try_files $uri $uri/ =404;
    }

    location /api {
            proxy_pass http://api;
    }

}

**Comment by ericwilsondc** [comment]
This is where I get the error.... So guessing nginx isn't setup correctly.   I bought a domain called awesomeminers.com on godaddy.  Currently this is only set to run on my server on my network 192.168.86.64.     How do I configure this correctly to run?

airric00@unbuntu:~/open-callisto-pool$ sudo service nginx restart
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.

**Comment by karalabe** [comment]
This issue tracker is for go-ethereum only. We can't help you set up third party systems built on top and configure your servers for you. Perhaps ask on https://ethereum.stackexchange.com/, maybe someone did similar things as you're trying and they might try to help.
