### ISSUE TITLE
The JSON RPC does not specify camelCasing.

### ISSUE THREAD

**Issue by cozylife** [ethereum/go-ethereum#1708]
The [documentation](https://github.com/ethereum/go-ethereum/wiki/Go-ethereum-management-API's) suggests that method names are meant to be lower-case snake cased strings. However, Geth will throw a "method not implemented" error when using a method such as "personal_newaccount" instead only working with "personal_newAccount."

Please update the documentation to instruct developers in your naming conventions.

**Comment by karalabe** [comment]
The wiki pages you linked in contains the entire reference of all implemented functions, correctly capitalized. Where does it suggest that everything should be lower cased?

**Comment by zelig** [comment]
RPC method names are a mix. the module (namespace) used in the javascript api is prefixed to the actual method name which itself if camelcased.

So the pattern is: 
* RPC: `<module>_<method_within_module>`, eg., `personal_newAccount`
* JS: `<module>.<method_within_module>`, eg., `personal.newAccount`

**Comment by cozylife** [comment]
Look at the [h3 text](https://github.com/ethereum/go-ethereum/wiki/Go-ethereum-management-API's#personal_newaccount) for the section. The heading suggests that the method is `personal_newaccount` and not `personal_newAccount`.

**Comment by karalabe** [comment]
Indeed, somebody was a bit sloppy during documenting (or didn't realize the casing mattered). Thanks a lot for pointing it out. I've updated the (hopefully) entire page with the correctly cased versions. If you still spot some inconsistencies, please shout out :)
