### ISSUE TITLE
miner.start<> but  <anoymous> :Line 1:13 Unexpected token

### ISSUE THREAD

**Issue by lihuawei321** [ethereum/go-ethereum#17091]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Please provide more infos. There's nothing in your report that can help us diagnose anything.
