### ISSUE TITLE
create public ethereum node

### ISSUE THREAD

**Issue by DMNV** [ethereum/go-ethereum#17095]
Hi there,
I just want know ,
If I use this command for create public ethereum node, 
please tell me is there is any changes to be done this cmd line
use azure VM,

`geth --identity "Four.Exchange.Node" --rpc --rpcport 8080 --rpcaddr "127.0.0.1" --rpccorsdomain "*" --datadir four.exchange.node --port 30303 --nodiscover --rpcapi db,eth,net,web3,personal,txpool --networkid 1 console`

**Comment by karalabe** [comment]
Please ask questions at http://ethereum.stackexchange.com, this forum is reserved for issues with the codebase.
