### ISSUE TITLE
smart contract front End web page showing some error so input did not store in backend 

### ISSUE THREAD

**Issue by karikalanCyberForza** [ethereum/go-ethereum#17094]
Hello Everyone,
-> I have created smart contract front end web page for the purpose of whatever input if i gave front web page it has to  store to backend level.
-> I have used three files such as index.html,main.css (fron End) and Blockchain.sol(backend) 
-> I got some errors in Front Web page using Ctrl+shift+I keys, and mentioned below clearly and shared screen shot also
![screenshot from 2018-06-27 19-06-44](https://user-images.githubusercontent.com/30066024/42015891-d82041d6-7ac6-11e8-8398-64c87159279c.png)

**Comment by karalabe** [comment]
Seems pretty clear to me: "Failed to load resource: web3.min.js". Not sure what you're trying to do or where you're getting your docs from, but I'd suggest reading up a bit on how the whole DApp ecosystem works, you seem to be missing a few concepts at the moment.
