### ISSUE TITLE
crypto/bn256/google/curve.go missing a Go 1.11 patch

### ISSUE THREAD

**Issue by FiloSottile** [ethereum/go-ethereum#17104]
Hi folks, your copy of golang.org/x/crypto/bn256 is affected by golang/go#25199 as it's missing https://go-review.googlesource.com/c/crypto/+/110695

It will crash on 1.11 (and is relying on undefined behavior before that).

I also noticed a potentially broken use of ModInverse in `crypto/secp256k1/curve.go`, but didn't verify if it's actually reachable.

https://github.com/ethereum/go-ethereum/blob/ba975dc0931b9f2962b2f163675772458ed339fd/crypto/secp256k1/curve.go#L99

**Comment by karalabe** [comment]
Thank you very much for the heads up, investigating.
