### ISSUE TITLE
Rpc api  SendTransaction EOF error 

### ISSUE THREAD

**Issue by blue-bird1** [ethereum/go-ethereum#17110]
#### System information

Geth version: 
Geth
Version: 1.8.12-unstable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.4
Operating System: linux

#### Expected behaviour
get Transaction hash

#### Actual behaviour
{Post http://127.0.0.1:8545/: EOF}

#### Steps to reproduce the behaviour
I use [api calli](https://github.com/FactomProject/EthereumAPI/blob/master/EthereumAPI.go)  PersonalSendTransaction
send a Transaction

Get 

geth: INFO [07-01|21:28:20.686|internal/ethapi/api.go:1192]      Submitted transaction                    fullhash=0x0490e34e0114b1bd045643be698e3a27a9ba0fd8693d640e064a6f0d69964f42 recipient=0xbc841ffc675E30D98615e93a853d2289888c7d72

go::Post http://127.0.0.1:8545/: EOF

#### Backtrace

````
[backtrace]
````

**Comment by blue-bird1** [comment]
geth run arg ` geth --rpc --rpcapi personal,db,eth,net,web3,debug --datadir ./ --fast --cache=2048 --debug --maxpeers 500
`

in console not error 
`> personal.sendTransaction(tx, "password")
"0xe8900c0402601dd82a63715a90fabd98154a93b8c9e47bfb2da58ef2d9786ad1"
`

**Comment by ocoderr** [comment]
same problem

**Comment by dselyuzhitskiy** [comment]
We had the same problem: geth v1.8.13 using github.com/ethereum/go-ethereum/rpc

**Comment by millennium-falcon42** [comment]
same problem.

**Comment by holiman** [comment]
I don't even understand what the problem is. 
```
geth: INFO [07-01|21:28:20.686|internal/ethapi/api.go:1192] Submitted transaction fullhash=0x0490e34e0114b1bd045643be698e3a27a9ba0fd8693d640e064a6f0d69964f42 recipient=0xbc841ffc675E30D98615e93a853d2289888c7d72
```
It was successfully transmitted? 

For @millennium-falcon42 , please provide details about version, and output from what the problem is.

**Comment by millennium-falcon42** [comment]
the problem is because of golang http connection timeout.

**Comment by adamschmideg** [comment]
It's unclear what the problem is and if it's related to http connection timeout. If any of you who chimed in, still experience this problem, please open a new issue with details (version, log).
