### ISSUE TITLE
Change port & ipc path per chain

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#17112]
@karalabe Now it is impossible to run multiple chains for default unless we change their open port & ipc path manually ( For example running geth with mainnet & ropsten ), I think it will be great when we also change the default RPC port & ipc path for test networks ( Bitcoin has a different RPC port for the test networks and it is possible to run multiple networks at the same time. )

**Comment by karalabe** [comment]
I think that would just confuse people. What would happen with private networks? What would happen with multiple private networks? Yes, if you want to run multiple chains you need to supply an explicit `--port` parameter, but I think that's kind of expected.

As for IPC, afaik that's different for mainnet and testnet (placed in a different data directory).

**Comment by MariusVanDerWijden** [comment]
Changing the default ports for test networks would just unnecessarily confuse all third party tools that have the default ports hardcoded in (something you shouldn't do btw!)
The OP is ghost, so I'll close this issue, feel free to reopen
