### ISSUE TITLE
Download page doesn't work well

### ISSUE THREAD

**Issue by flibustier** [ethereum/go-ethereum#17119]
Hello,
The [download page](https://ethereum.github.io/go-ethereum/downloads/) doesn't seem to work :
![image](https://user-images.githubusercontent.com/9994935/42231906-260aba28-7eed-11e8-969d-6c97f188373d.png)
The modal doesn't stop and an error appears after a while

**Comment by karalabe** [comment]
Seems to be working for me now. Perhaps it was a connectivity or Azure blobstore issue?

**Comment by flibustier** [comment]
It's still not working on 2 different computers with 2 different browsers, "Failed to load releases!"

**Comment by karalabe** [comment]
Could you please check any error message in your browser's JavaScript console? Perhaps some firewall is blocking your access?

**Comment by flibustier** [comment]
The JS console said 
```
XML parsing failure: no element found
Location: https://gethstore.blob.core.windows.net/builds?restype=container&comp=list
Line 1, Column 239584 :
```
Indeed, I cannot reach [this link](https://gethstore.blob.core.windows.net/builds?restype=container&comp=list) with my current network, I try with a proxy and it works, even the download page!
Sorry for this non general issue, it's our network releated
Thanks very much for your help!

**Comment by leafcutterant** [comment]
Request for re-open.

I have this issue from Tor. I get "Failed to load releases!", then it keeps spinning/loading indefinitely. The latest release is visible, but I can't click on it because of the dark filter screen or whatever its name is.

**Comment by karalabe** [comment]
Please check your firewall or anything else blocking network requests. The download page has not been changed for 2 years now and every time someone says it doesn't work, it turns out that their own corporate or whatnot firewall is blocking requests to Azure.
