### ISSUE TITLE
Private Chain, Ether gets sent to 3 random addresses

### ISSUE THREAD

**Issue by trakout** [ethereum/go-ethereum#17127]
Hi there,

#### System information

Geth version: `1.8.10-stable`
OS & Version: `Ubuntu 16.04.4 LTS (xenial)`
Git Commit: `eae63c511ceafab14b92e274c1b18bf1700e2d3d`

#### Expected behaviour
Sending from coinbase address results in a successful transfer of ETH from coinbase to the target recipient address.

#### Actual behaviour
Sending from coinbase address results in large amounts of ETH being sent to seemingly random addresses -- in most cases, the intended target recipient address does not receive anything.

We noticed that there are 3 recipient addresses that ETH goes to. We do not control these addresses, and are not sure where they come from:
1) `0x8652328B96Ff12B20de5fDc67b67812E2b64e2A6`
2) `0x7097f41F1C1847D52407C629d0E0ae0fDD24fd58`
3) `0x6e4Cc3e76765bdc711cc7b5CbfC5bBFe473B192E`

#### Steps to reproduce the behaviour
Installed using PPA: 
https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu

`geth account new`
`geth init /path/to/genesis.json`

genesis JSON:
```
{
   "config": {
       "chainId": 15,
       "homesteadBlock": 0,
       "eip155Block": 0,
       "eip158Block": 0,
       "ByzantiumBlock": 0
   },
   "difficulty": "0x400",
   "gasLimit": "30000000",
   "alloc": {
       "{removed}":
        { "balance": "100000000000000000000000000" }    
   }
}
```

Geth Startup Command:
`geth --mine --ws --wsaddr "0.0.0.0" --wsport 2626 --wsorigin "*" --targetgaslimit 30000000 --rpcvhosts '*' --config token-config.toml`

Command used to send (after unlocking):
`eth.sendTransaction({from:eth.coinbase, to:"0xFF...FF", value: web3.toWei(26, "ether")})`

#### Backtrace

````
NFO [07-04|15:26:37] Submitted transaction                    fullhash=0xe3dff14810d5db09b00bd07822ec04d842ba885fe7d68acb2457a2ece224c59d recipient=0x8652328B96Ff12B20de5fDc67b67812E2b64e2A6
INFO [07-04|15:26:37] Submitted transaction                    fullhash=0x928f304f18b1bb43ce86b151a3fd2830288467a4d3aeb88c6a82cad4aee8d1fd recipient=0x6e4Cc3e76765bdc711cc7b5CbfC5bBFe473B192E
INFO [07-04|15:26:38] Submitted transaction                    fullhash=0x258f1e9576792fed5571c6424d8c3fb7e681df0af3a17dd6fa1bcb88d2720c1a recipient=0x7097f41F1C1847D52407C629d0E0ae0fDD24fd58
INFO [07-04|15:26:38] Submitted transaction                    fullhash=0xaef83cd5d6f9cf0115a80c16d9a7ebf5b51a8a80ee4600150fa6c4e0582f7d5c recipient=0x8652328B96Ff12B20de5fDc67b67812E2b64e2A6
INFO [07-04|15:26:39] Submitted transaction                    fullhash=0xb8811cae0c08b0cfc8f3aca48b1469309b19ced375c4fe426f28918b0ef7d36f recipient=0x7097f41F1C1847D52407C629d0E0ae0fDD24fd58
INFO [07-04|15:26:39] Submitted transaction                    fullhash=0x00f4def981aef66fe538f1812d1a070cdd8d048a6a746edf9179418dc156e22e recipient=0x8652328B96Ff12B20de5fDc67b67812E2b64e2A6
INFO [07-04|15:26:39] Submitted transaction                    fullhash=0x483b76b6fe4dea4e28d16008680bd03e1202971f1d4c210f9ea3bfc974ee4d5f recipient=0x7097f41F1C1847D52407C629d0E0ae0fDD24fd58
INFO [07-04|15:26:40] Submitted transaction                    fullhash=0xb36f3bad7ed54355d1bec64f052401e20375fe8be11ee7e2424856058ecdd06b recipient=0x8652328B96Ff12B20de5fDc67b67812E2b64e2A6
INFO [07-04|15:26:40] Submitted transaction                    fullhash=0x3689d9c6dc07342f58f4265d223b2f62c3eec7eef98b715feefac6aca9b366d0 recipient=0x7097f41F1C1847D52407C629d0E0ae0fDD24fd58
INFO [07-04|15:26:41] Submitted transaction                    fullhash=0x69f52567e8f1248fcc07034bd3364d0df241a9f14235ee5d412be5e88959e9c9 recipient=0x8652328B96Ff12B20de5fDc67b67812E2b64e2A6
INFO [07-04|15:26:41] Submitted transaction                    fullhash=0x72901c5d91e6fa7405dedb2c298d73e7cd13dcddc29148a0620b037402eea433 recipient=0x6e4Cc3e76765bdc711cc7b5CbfC5bBFe473B192E
INFO [07-04|15:26:41] Submitted transaction                    fullhash=0x63acfb41277a25ecb71bdb16e926141f1bc896776b90582c7e4866541c55b2a7 recipient=0x7097f41F1C1847D52407C629d0E0ae0fDD24fd58
INFO [07-04|15:26:41] Submitted transaction
````

#### Misc Notes
- Mystery addresses 1-3 have balances on the public mainnet (https://etherscan.io/txs?a=0x7097f41F1C1847D52407C629d0E0ae0fDD24fd58) as well as Ropsten (https://ropsten.etherscan.io/address/0x7097f41F1C1847D52407C629d0E0ae0fDD24fd58)
- It appears that this user of an alt-coin based on Geth (running Ubuntu) has the same issue (with the same addresses!): https://forum.musicoin.org/topic/9034/lost-money/7
- Another alt-coin (based off Ethereum) with balances at the same addresses (all three): https://explorer.ellaism.org/account/0x8652328b96ff12b20de5fdc67b67812e2b64e2a6

**Comment by flgh** [comment]
Hackers have been probing for insecure open WS or JsonRPC on all tcp ports for some time, they try to transfer to their addresses as soon as you unlock an account.
Is your WS port firewalled ?

**Comment by voratham** [comment]
@flgh  How to fix this except from config firewall,  because i don't have to enable websocket from geth cli

```bash
> geth --rpc --rpcaddr "0.0.0.0" --rpcport 8959 --rpcapi "web3,personal,debug" --rpccorsdomain "*" --nodiscover
```

**Comment by Agus** [comment]
Same is happening to me! And same addresses, so the hacker thing makes sense. Should start taking care about this also for development I guess...

**Comment by aerth** [comment]
@voratham Never expose `personal`, `debug`, or  `admin` over 0.0.0.0, typically all you need is `web3,eth,net`. Also never `--unlock` when hosting a public RPC!! Otherwise you are asking for it.

**Comment by mkhraisha** [comment]
How would i unlock an account if i dont expose `personal`, `debug, or `admin` in this scenario? i dont want to expose is over a public rpc but i want to unlock an account to use, is there a specific thing i should do?

**Comment by mahjiang** [comment]
Can any Ethereum devs provide any insight here?

**Comment by mkhraisha** [comment]
If you have an exposed -rpc address with `personal` `debug or `admin` then they will have an avenue of attack. I ended up putting them behind a firewall and only allowing specific addresses access to it

**Comment by holiman** [comment]
It has already been explained, several times. If you

* Expose RPC to the world, and
* Use `unlock`,

Then hackers will create a huge number of valid transactions, for a large number of nonces. It doesn't matter if you have zero balance right now, once you put some ether on that account they will use those presigned transactions to drain it.

I'm on a personal mission to nuke `personal.unlock` from orbit, with [Clef](https://github.com/ethereum/go-ethereum/tree/master/cmd/clef) (still work in progress)

**Comment by Austindgkffg** [comment]
[/](url)
