### ISSUE TITLE
wrong transaction occurred 

### ISSUE THREAD

**Issue by SinghDavinder94** [ethereum/go-ethereum#17123]
Hello  Everyone
I make a transaction using eth_sendTransaction  method and it returned a transaction hash that I save in db.But when I checked the transaction  then it is not broadcasted and also when I check the address from which I have to sent ether then I see a another transaction hash there in which the amount and recipient address are totaly diff from which I actually give to eth_sendTransaction method.

**Comment by karalabe** [comment]
Please make sure you are not running a node with an RPC address openly accessible from the internet. People are actively scanning for Ethereum nodes to sweep.

**Comment by SinghDavinder94** [comment]
Can you please help me more on this issue. The method eth_sendTransactions give me hash in response is 0x27fac67a2a375c3c434510a4f9aea1464ca9a7232625918538d49b22e897d4a6   and when I see in address transaction history    0xbf2aae6c4400e954a04d8ff9ac05cbff28cd4744306c422839503420aa283f70  is listed in my transaction which I never make.My address is 0xf54a955e0b5f8897d652a6d945270ebfefae6e53.

**Comment by karalabe** [comment]
There is nothing we can do. You opened up your node for public internet access (I guess via `--rpcaddr=0.0.0.0`), permitting anyone from the internet to interact with your node. Beside that, you also unlocked your account (I guess via `personal.unlockAccount`) for anyone to transact with. Someone from the internet was attached to your machine, waiting for you to unlock. When you did, they sweeped all your funds.

That recipient address seems to be doing this for months now https://etherscan.io/address/0x957cd4ff9b3894fc78b5134a8dc72b032ffbc464

**Comment by hadv** [comment]
@SinghDavinder94 if you unlock your account on a node with RPC enable then other people can send transaction. It's very dangerous. Never unlock your account, you should use sign transaction for more security.

**Comment by SinghDavinder94** [comment]
thanks @karalabe and @hadv  for your help.
I me not able to send transaction via sign method ...can you please help me by describing the steps required with params to send transaction via sign method.

**Comment by hadv** [comment]
I dont go into the exactly code but the steps should be

1. create transaction
2. sign the tnx with your private key
3. send raw tnx

hope this help ! :)

**Comment by SinghDavinder94** [comment]
thanks @hadv

**Comment by karalabe** [comment]
`personal.sendTransactions` doesn't unlock the account, rather signs it in memory and submits it. Always use that instead of `unlockAccount`. And never ever ever expose your RPC to the internet.
