### ISSUE TITLE
Unable to get traces for specific transactions on rinkeby

### ISSUE THREAD

**Issue by ghostbuster91** [ethereum/go-ethereum#17126]
Hello,
Geth is unable to return traces for some specific transactions when using `callTracer`
Log shows:

`ERROR[07-04|12:18:10] write tcp x.y.z:8547->x.y.w:55004: i/o timeout`
#### System information

Geth version: `1.8.11`
OS & Version: Linux e028f4037342 4.14.48-coreos-r2 #1 SMP Thu Jun 14 08:23:03 UTC 2018 x86_64 Linux
Launched with following paramters:
```
--ws --wsaddr 0.0.0.0 --wsport 8545 --wsapi eth,web3,debug,admin --datadir /storage --cache=4096 --syncmode=full --gcmode=archive --rpcport 8547 --rpcapi eth,web3,debug,admin --verbosity 3 --port 30323 --rinkeby
```
#### Expected behaviour

Geth returns traces for given transactions

#### Actual behaviour
Geth is unable to return traces for following transactions:
- 0xb921d686008793592d0dc6a7b3aa85ff411fc654779da3d2af94b5e74c326012
```
{"id":"1","jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xb921d686008793592d0dc6a7b3aa85ff411fc654779da3d2af94b5e74c326012",{"timeout":"2m","tracer":"callTracer"}]}
```
- 0xe6bae5ab359286a6c6b2eefe6cd39a2848c64be910b510f43164b28313c74016
```
{"id":"1","jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xe6bae5ab359286a6c6b2eefe6cd39a2848c64be910b510f43164b28313c74016",{"timeout":"5m","tracer":"callTracer"}]}
```
- 0x77404dd12185d577d7fe2329c84a8f72aa0d76fe175d93e4513bab83724fa79a
```
{"id":"1","jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x77404dd12185d577d7fe2329c84a8f72aa0d76fe175d93e4513bab83724fa79a",{"timeout":"5m","tracer":"callTracer"}]}
```
- 0x504112e8f3e6fe01f7faa3fca66a24a266a4143b52333498c548c241f6880fc8
```
{"id":"1","jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x504112e8f3e6fe01f7faa3fca66a24a266a4143b52333498c548c241f6880fc8",{"timeout":"5m","tracer":"callTracer"}]}
```
- 0xa20db1a5477951a9723005fce7d08fb08ccd1e5865ddc9dcd6622a699c1c46bb
```
{"id":"1","jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xa20db1a5477951a9723005fce7d08fb08ccd1e5865ddc9dcd6622a699c1c46bb",{"timeout":"5m","tracer":"callTracer"}]}
```
- 0xfab8c710e23b7075e61270939ac6a1af8ba5d097f1fd32c85a34457cf0660b41
```
{"id":"1","jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xfab8c710e23b7075e61270939ac6a1af8ba5d097f1fd32c85a34457cf0660b41",{"timeout":"5m","tracer":"callTracer"}]}
```
- 0xb03dd7ffdfa2cf2309891e21fdfb8293880b5f1c9a45ec603937e8fb2cda277d
```
{"id":"1","jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xb03dd7ffdfa2cf2309891e21fdfb8293880b5f1c9a45ec603937e8fb2cda277d",{"timeout":"5m","tracer":"callTracer"}]}
```
#### Steps to reproduce the behaviour

Just ask geth for traces, e.g. use curl:
```
curl --data '{"id":"94273b84-d3be-4e36-b914-79805634061b","jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xb03dd7ffdfa2cf2309891e21fdfb8293880b5f1c9a45ec603937e8fb2cda277d",{"timeout":"5m","tracer":"callTracer"}]}'  -H 'Content-Type: application/json' -X POST GETH_HTTP_ADDRESS
```
It gives:
```
curl: (52) Empty reply from server
```

#### Backtrace

`ERROR[07-04|12:18:10] write tcp x.y.z:8547->x.y.w:55004: i/o timeout`

**Comment by svechinsky** [comment]
I'm experiencing the same issue with a ropsten node, any ideas on this?

**Comment by svechinsky** [comment]
Solved it!
For those who stumble in here, the solution is to extend http write timeout as per https://github.com/ethereum/go-ethereum/pull/17240
