### ISSUE TITLE
How to send 1-N signalling messages on Whisper?

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/go-ethereum#17120]
- geth version: 1.8.0-unstable

[From Whisper wiki][1]:

> Low-latency, 1-1 or 1-N signalling messages.

[Shh.post(self, message:)][2]

> Creates a whisper message and injects it into the network for
> distribution.

**Example usage of `web3.shh.post`, for more details please see this [answer][3]:**

    web3.shh.post({
      pubKey: 'PUBLIC_KEY_OF_THE_RECEIVER',
      ttl: 3600,
      topic: '0x07678231',
      powTarget: 2.01,
      powTime: 2,
      payload: web3.fromAscii("Hello there!")
      });

----

When I remove `pubKey` from `web3.shh.post` as arguments; it says: `Error: specify either a symmetric or an asymmetric key`. [Whisper overview][4] is out of date. It gives following example as use case which does not work:
    

> `shh.post({ "topic": t, "payload": p });` No signature, no encryption: Anonymous broadcast; a bit like an anonymous subject-filtered twitter feed.

 

**[Q]** Since `web3.shh.post()`requires us to provide single public key of the receiver; is it possible to send 1-N message using `whisper protocol`? If yes, how? If no, please update the `Whisper wiki`.

Asked also here: https://ethereum.stackexchange.com/q/52218/4575

  [1]: https://github.com/ethereum/wiki/wiki/Whisper
  [2]: http://web3py.readthedocs.io/en/stable/web3.shh.html#web3.shh.Shh.post
  [3]: https://ethereum.stackexchange.com/a/51856/4575
  [4]: https://github.com/ethereum/wiki/wiki/Whisper-Overview#basic-operation

**Comment by karalabe** [comment]
@gballet

**Comment by gballet** [comment]
I will update the documentation for v6. @avatar-lavventura given the error message that you displayed, it seems that you are using v6, so I will use this issue as a tracker.

**Comment by avatar-lavventura** [comment]
Thanks @gballet ; the documentation was incomplete on some part. I did some research how to solve issues that I have faced.

Please also have a look at ([How to send 1-N signalling or broadcast messages on Whisper?](https://ethereum.stackexchange.com/a/52932/4575)), which might help you. I asked the questioned and wrote the tutorial code section on the answer, please feel free to use it.

Also this could be helpful if It could be added to documentation which is missing ([Whisper: How could we print received messages that are actually stored in the memory when geth was closed or shh.newMessageFilter() is not activated?](https://ethereum.stackexchange.com/a/52222/4575)) . Again I asked the question and answered it.

**Comment by gballet** [comment]
@avatar-lavventura looking a bit closer into this issue, I realize that this is not a problem of the go-ethereum documentation: the links that you are referring to are both for Python and the ethereum global wiki (this is the Go implementation). I have to see if I can edit the general wiki, in the mean time the reference is [here](https://github.com/ethereum/go-ethereum/wiki/Whisper)

**Comment by gballet** [comment]
@avatar-lavventura looking a bit closer into this issue, I realize that this is not a problem of the go-ethereum documentation: the links that you are referring to are both for Python and the ethereum global wiki (this is the Go implementation). I have to see if I can edit the general wiki, in the mean time the reference is [here](https://github.com/ethereum/go-ethereum/wiki/Whisper);

**Comment by avatar-lavventura** [comment]
I have lost on the documentations and could not able to send a message from a node to another. If there would be an example it would be very helpful.

-------

This is as far as I came but each node only sends message to itself and other nodes don't see it, could you have a look? For example when node-1 sends a message it won't show up on node-2 such that node-2's `web3.shh.info{memory}` returns 0 which I assume that it never catches the message.

**On Node-1 geth-client:**


    generatedSymKey=shh.generateSymKeyFromPassword("hello");    
    symKey=shh.getSymKey(generatedSymKey)    
    kId=shh.addSymKey(symKey) //ex: "d5212e736703afbb21246e8acd192e4345ea910398544d765ed6b49f0ec524b5"
    filter = web3.shh.newMessageFilter(
            {symKeyID:kId, topic: '0x07678231'}, 
            function(err, res) {console.log(web3.toUtf8(res.payload))});

**On Node-2 geth-client:**


    generatedSymKey=shh.generateSymKeyFromPassword("hello")    
    symKey=shh.getSymKey(generatedSymKey)    
    kId=shh.addSymKey(symKey) //ex: "c4c4cecf6ad9499c2386b8ce6416f44684e042e491726b38315646c0b4afadc6"
    filter = web3.shh.newMessageFilter(
            {symKeyID:kId, topic: '0x07678231'}, 
            function(err, res) {console.log(web3.toUtf8(res.payload))});

-----

Than, **node-1** sends message to the network, where only node-1 receives it but node-2 does not.

Following code is run on node-1 geth-client:

**node-1's `symKeyID` is given:**

    web3.shh.post({
      symKeyID: 'd5212e736703afbb21246e8acd192e4345ea910398544d765ed6b49f0ec524b5', //symKeyID of the node-1
      ttl: 10,
      topic: '0x07678231',
      powTarget: 2.01,
      powTime: 2,
      payload: web3.fromAscii("Hello there!")
      });
