### ISSUE TITLE
Go test fails for windows environment

### ISSUE THREAD

**Issue by akx20000a** [ethereum/go-ethereum#17141]
#### System information

Geth version: `geth 1.8.13`
OS & Version: Windows
Commit hash : v1.8.13

#### Actual behaviour

Testing go test on windows environment fails on windows environment including Appveyor CI build.

I think it is related to https://github.com/ethereum/go-ethereum/pull/17041 PR with swarm POC3 release.

Build result: https://ci.appveyor.com/project/ethereum/go-ethereum/build/master.7006/job/tocjijjprtmv4tac

@fjl @karalabe @zsfelfoldi @gbalint

**Comment by nonsense** [comment]
This has been fixed as part of b3711af by @janos
