### ISSUE TITLE
 'eth.getBalance' and 'client.BalanceAt' balances do not match in rinkeby

### ISSUE THREAD

**Issue by littlegirlpppp** [ethereum/go-ethereum#17143]
Hello:
 'eth.getBalance' and 'client.BalanceAt' balances do not match in rinkeby

#### System information
Geth version: `geth 1.8.11-stable`
OS & Version: OSX

this is my geth "geth --rinkeby  --syncmode=fast  --ethstats='sunbo:Respect my authoritah!@stats.rinkeby.io'  --datadir testNet  --port 28000 --rpc --rpcaddr 192.168.50.86 --rpcport 8545 --rpcapi 'db,net,eth,web3' --rpccorsdomain '*' console 2>> test.log"

>  eth.getBalance("0x4076a5f13fe75e9658035b52c09026344de9e03d")
18649108320000000000
 eth.syncing
false

But when I got it in golang, it was like this

    func (eth*Ethereum)GetBalance(address string) (float64,error) {
	balance, err := eth.client.BalanceAt(context.Background(),common.HexToAddress(address),nil)
	if err != nil {
      return  0,err
	} else {
		
		balanceV := float64(balance.Int64()) * math.Pow(10, -18)
		return balanceV,nil
	}
    }
![image](https://user-images.githubusercontent.com/9802301/42416918-a44005ba-82ad-11e8-9cc6-a10c17d7e57b.png)
So I don't know why the results are different

**Comment by karalabe** [comment]
A `float64` has limited precision. Please only ever work with `big.Int` numbers when handling balances.
