### ISSUE TITLE
`make test' fails for releases

### ISSUE THREAD

**Issue by introom** [ethereum/go-ethereum#17158]
running make test fails, 
cf. [https://github.com/ethereum/go-ethereum/blob/master/Makefile#L37](link)
it tests all packages.

checking .travis.yml, I find this,
cf. [https://github.com/ethereum/go-ethereum/blob/master/.travis.yml#L15](url)

but the $TEST_PACKAGES is missing, so I dunno what the packages are.

**Comment by ligi** [comment]
can you provide the output of `make test`?

**Comment by introom** [comment]
hi, the traceback is here,
https://bpaste.net/show/4d5b1f4e55ce

Though depending on the version, make tests fails for different reasons.


I wonder what's the $TEST_PACKAGES in the .travis.yml. As we are developing a forked version, that variable helps to make the test more targeted.

**Comment by ligi** [comment]
seems TEST_PACKAGES is not used in our ci setup - can just be used to speed up the tests - see: https://github.com/ethereum/go-ethereum/commit/2e247705cd27e919e806f29ff2adcd57c163b1ac

the tests should pass. But there where some flaky ones after the big swarm merge AFAIR. But they need to be fixed.

**Comment by ligi** [comment]
Can we close this issue? Not really actionable.

**Comment by introom** [comment]
yeah. sure
