### ISSUE TITLE
Any objection to having evm disasm use hex for addresses?

### ISSUE THREAD

**Issue by GoldenDave** [ethereum/go-ethereum#17157]
Hi there,

It may be the purist in me but 
```
000000: PUSH1 0x60
000002: PUSH1 0x40
000004: MSTORE
000005: CALLVALUE
000006: ISZERO
000007: PUSH3 0x000010
000011: JUMPI
000012: PUSH1 0x00
000014: DUP1
000015: REVERT
000016: JUMPDEST
000017: PUSH1 0x40
000019: MLOAD
000020: PUSH1 0x20
000022: DUP1
```
would look so much better as 
```
000000: PUSH1 0x60
000002: PUSH1 0x40
000004: MSTORE
000005: CALLVALUE
000006: ISZERO
000007: PUSH3 0x000010
00000B: JUMPI
00000C: PUSH1 0x00
00000E: DUP1
00000F: REVERT
000010: JUMPDEST
000011: PUSH1 0x40
000013: MLOAD
000014: PUSH1 0x20
000016: DUP1
```

If evm.PrintDisassembled isn't used anywhere else, any objection to making it hex or at least having a hex address option?

If OK - I will do it and submit it.

**Comment by veox** [comment]
It not being hex has been a point of annoyance every time I've had to "disassemble something real quick".

Not sure if there are third-party tools that already rely on the line numbers being in decimal, though.

**Comment by DaveAppleton** [comment]
Never mind. It is easy to build your own based on it.
I have created a version that uses it and extends it.
http://github.com/akombalabs/myDasm
