### ISSUE TITLE
abiGen crashes when on tuples

### ISSUE THREAD

**Issue by StoyanD** [ethereum/go-ethereum#17152]
When creating wrappers using abiGen, it crashes when you have nested struct's in your code. This occurs when abiGen tries to [unmarshal json](https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/bind.go#L54) and the supported types don't match a [tuple](https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/type.go#L116) Leading to a runtime crash. 

#### Expected behaviour
abiGen should not crash on tuples, or it should ignore them since in solidity no **public** function can take tuples as parameters or return them as output.

#### Actual behaviour
abiGen crashes on perfectly valid abi from the solc compiler

#### Steps to reproduce the behaviour
run ``abigen --sol Nested.sol --pkg main --out nested.go``

On this file Nested.sol: 
```
pragma solidity ^0.4.24;

contract Nested {

    Parent public parent;
    struct Parent {
        uint a;
        Child child;
    }

    struct Child {
        uint b;
    }

}
```

#### Backtrace
````
Failed to generate ABI binding: unsupported arg type: tuple
````

**Comment by EnchanterIO** [comment]
I run into this issue today and it was for several reasons. For people debuggin make sure you: 

- don't return a struct from a smart contract's method 'returns' statement
- don't define an event with a struct in a smart contract

You can see specifically (what I realised an hour later...) what's the exact problem by reading the generated ABI:

`"type": "tuple"` and check the surroundings for the exact name of method/event.

**Comment by outprog** [comment]
Same issue, because not support `"type": "tulpe"`.
https://github.com/ethereum/go-ethereum/issues/17642

**Comment by gballet** [comment]
The merge of #18406 should fix this issue. Please re-open it in case it doesn't work

**Comment by rjl493456442** [comment]
@gballet for the abigen, we still need some modifications to make it work. I'll open another PR to fix it.

**Comment by gballet** [comment]
@rjl493456442 ok, reopening then. Let me know.

**Comment by fabioberger** [comment]
I just tried using #18406 to use abigen with contracts using ABIV2 and it did not work. @rjl493456442 are you still working on the missing modifications?

**Comment by rjl493456442** [comment]
@fabioberger Please try this PR https://github.com/ethereum/go-ethereum/pull/18491. Feel sorry for the confusion, this PR only supports encode/decode tuple arguments, but #18491 supports tuple style golang binding generation.

And any feedback is appreciated for #18491 if there is any issue.
