### ISSUE TITLE
Build on FreeBSD with go < 1.5

### ISSUE THREAD

**Issue by kisscool** [ethereum/go-ethereum#1715]
In order to build geth on FreeBSD with a golang version < 1.5, you need to be aware of the following bug about the cgo detection of CLANG : https://github.com/golang/go/issues/10453

It means you need to tell explicitly to cgo that you are using CLANG with the following command : 

    CC=clang make geth

This particularity should probably be documented somewhere in the wiki or the README until go 1.5 is more widely available.

Tested with : 
* geth 1.0.2 (rev a0303ff4bdc17fba10baea4ce9ff250e5923efa2)
* FreeBSD 10.2-RELEASE

**Comment by karalabe** [comment]
@fjl Maybe you could add some FreeBSD detection to the make script to automatically define CC?

**Comment by fjl** [comment]
Go 1.5 has been released and is available in the freebsd ports tree.
Since the bug is fixed in 1.5, I don't think this warrants adding a work-around.

**Comment by fjl** [comment]
@kisscool We don't have installation instructions for FreeBSD on the wiki. Would be nice if someone wrote them, though...

**Comment by kisscool** [comment]
I quickly added basic installation instructions here : https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-FreeBSD
