### ISSUE TITLE
what‘s reason produce this problem: when i copy keystore files to windows10  mist wallet dir；

### ISSUE THREAD

**Issue by weiweiloong** [ethereum/go-ethereum#17165]
what‘s reason produce this problem: when i copy keystore files to windows10  mist wallet dir；
1、the balance appear several Minutes after i installed the mist wallet；
 windows10 instll Ethereum-Wallet-installer-0-11-0.exe today,

2、eth.getBalance("0xef8a6d106715c7dc7f1953dbab6e95772d39ee34") return 0；
centos7  instll  geth-linux-amd64-1.8.12-37685930.tar.gz

**Comment by weiweiloong** [comment]
> eth.getBalance("0x870deaf15358a5db3e5ecadbf4bdae1aa0578f20")
0
> eth.blockNumber
0
> eth.syncing
{
  currentBlock: 5950068,
  highestBlock: 5950150,
  knownStates: 106845868,
  pulledStates: 106836403,
  startingBlock: 5949803
}
>

**Comment by karalabe** [comment]
Geth is still syncing, so it cannot show you the balance per my previous reply to your post. The reason the new Mist **can** show it to you, is because it's defaulting to Infura while the underlying node is syncing.
