### ISSUE TITLE
Use RLP method on iOS

### ISSUE THREAD

**Issue by daiyangyang945** [ethereum/go-ethereum#17172]
There is no any RLP method which can process strings in Geth.framework.But I could find and use it by Go.

**Comment by ligi** [comment]
Can you elaborate on what exactly your use-case is?

**Comment by daiyangyang945** [comment]
Our app want to use RLP to protect our information that will post to the server.Something like user information,transaction information,these will interact between server and client.

**Comment by ligi** [comment]
> Our app want to use RLP to protect our information that will post to the server.

hm - I do not see how RLP can protect any information. RLP is just a serialisation format ..

**Comment by daiyangyang945** [comment]
Yes,this what we want.We will encrypt datas in app first,secondly use RLP to process datas,and then post to the server.

**Comment by ligi** [comment]
But then why exactly you want to use RLP?

**Comment by daiyangyang945** [comment]
Actually I don't want.But my leader asked me to do this.

**Comment by ligi** [comment]
don't follow (such) leaders ;-)

**Comment by FrankSzendzielarz** [comment]
Sure he doesn't mean rlpx?

Sent from my Windows Phone
________________________________

**Comment by ligi** [comment]
I think only he or his leader can answer - I am not sure and have the feeling a lot of things are lost in translation. But we should not blindly implement things without really understanding use-cases and needs.

**Comment by FrankSzendzielarz** [comment]
Correct. My question was addressed to him. Apologies if it went to you. Rlpx as a secure transport would make sense. Rlp doesn't.

Sent from my Windows Phone
________________________________

**Comment by ligi** [comment]
ACK - but RLPx does not really fit this:

> There is no any RLP method which can process strings in Geth.framework.

we will really need more info from the OP

**Comment by FrankSzendzielarz** [comment]
Yeah. OP feel free to refer Dear Leader here😉

Sent from my Windows Phone
________________________________

**Comment by daiyangyang945** [comment]
emmmm
I implemented it on iOS.
[https://github.com/daiyangyang945/RLP-iOS](url)
