### ISSUE TITLE
Txpool is constantly growing

### ISSUE THREAD

**Issue by korjavin** [ethereum/go-ethereum#17179]
#### System information

Linux

Commit tag v5.4.3

#### Expected behaviour
txpool should be in some limits 

#### Actual behaviour
txpool is growning up until node restarted

#### Steps to reproduce the behaviour
Start, wait, check txpool.status

![image](https://user-images.githubusercontent.com/148765/42760476-e0c3f61e-890a-11e8-901f-ece84005f9ee.png)

**Comment by karalabe** [comment]
We don't have v5.4.3.
