### ISSUE TITLE
Geth syncing always left 100k blocks behind

### ISSUE THREAD

**Issue by mcb345** [ethereum/go-ethereum#17177]
#### System information

Geth version: `geth 1.8.12`
OS & Version: Linux

#### Expected behaviour
Geth synced successfully

#### Actual behaviour
Geth always left behind around 100k blocks

#### Steps to reproduce the behaviour
nohup geth --cache 4096

I had ran the syncing for a week or so, I thought It needed some times to fully synced to the net, but I think there is some issue on my setup

NB : I ran with `--cache 1536` before (as I only have 4GB ram), it crashed and finally I added 12GB swap and ran with `--cache 4096`, but doesnt seem to be working too

Anyone here encounter same issue ?

**Comment by karalabe** [comment]
Syncing an ethereum node is **disk io** intensive. It can only ever sync to an SSD even now, adding swap will just further increase disk IO insanely. Please don't ever add swap to a machine tbh, it just doesn't make sense, it won't crash an app, but runtime will be insanely slow.

Are you doing a fast sync or a full sync by any chance? SSD or HDD?

**Comment by mcb345** [comment]
@karalabe I am running on ec2 instance with an SSD. The reason I am adding swap is, previously the Geth keeps crashing every few days (or even hour) and the error was out of memory. After I added the swap the crashes stops but now I cant sync to the latest block. 

NB : I am doing full sync not fast sync

**Comment by cngotom** [comment]
You can check your ssd monitor to see whether they reach the bottleneck.

**Comment by cngotom** [comment]
trace eth.syncing.highestBlock - eth.syncing.currentBlock in console to see the speed difference between sync and new block producing.

**Comment by mcb345** [comment]
Redownload the chain from 0 did the trick , 

Step to reproduce : 

- Backup keystore

- Delete all .ethereum folder

- Run geth
