### ISSUE TITLE
Fatal: Error starting protocol stack: sync /mnt/ethereum/geth/chaindata: invalid argument

### ISSUE THREAD

**Issue by bizlevel** [ethereum/go-ethereum#17180]
Hi i got Debian 9 and latest geth.
And i mount CIFS drive to /mnt/ethereum - and will use for blockchain.

I have several geth node, all is fine work (except, time to time block is not high)

And i got this error when node start:
```
Jul 16 17:11:01 node-ethereum geth[21989]: WARN [07-16|17:11:01.105] Sanitizing cache to Go's GC limits       provided=2048 updated=1286
Jul 16 17:11:01 node-ethereum geth[21989]: INFO [07-16|17:11:01.106] Maximum peer count                       ETH=25 LES=0 total=25
Jul 16 17:11:01 node-ethereum geth[21989]: INFO [07-16|17:11:01.122] Starting peer-to-peer node               instance=Geth/v1.8.12-stable/linux-amd64/go1.10.3
Jul 16 17:11:01 node-ethereum geth[21989]: INFO [07-16|17:11:01.122] Allocated cache and file handles         database=/mnt/ethereum/geth/chaindata cache=964 handles=512
Jul 16 17:11:01 node-ethereum geth[21989]: Fatal: Error starting protocol stack: sync /mnt/ethereum/geth/chaindata: invalid argument
Jul 16 17:11:01 node-ethereum systemd[1]: geth.service: Main process exited, code=exited, status=1/FAILURE
```

geth create some files and fails.

```
root@node-ethereum /mnt # tree ethereum
ethereum
├── geth
│   ├── chaindata
│   │   ├── CURRENT
│   │   ├── LOCK
│   │   └── LOG
│   ├── LOCK
│   └── nodekey
└── keystore
```
What additional run to check details ?
Can geth work with SAMBA/CIFS/NFS disks ?

Thanks.

**Comment by bizlevel** [comment]
Found similar - https://github.com/ethereum/go-ethereum/issues/16278

**Comment by karalabe** [comment]
In all honesty I wouldn't do that. Syncinc go-ethereum is already disk IO bound. If you're going to stream all the disk access through the network, I don't think you'll get a usable performance. That said, I would expect it to work, but it's not a use case we test for.

You'd probably need to also either disable the IPC endpoint, or move it to your local machine. Unix sockets need filesystem support, so that will most definitely not work on a remote datadir.

**Comment by bizlevel** [comment]
My variants - it is clear debian 9 host + nfs (hetzner + StorageBox)  NOT BLOCK DEVICES, no ALC/rights on this volume.
And yes, i think, only iSCSI can work with remote variants.
