### ISSUE TITLE
admin.setSolc not exist

### ISSUE THREAD

**Issue by yujianFresh** [ethereum/go-ethereum#17186]
Hi there,

i found this method in your wiki,but i can't found in ethereum node.it retutn that the method doesn't exist.

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Geth does not have an API to build smart contracts with. Use http://remix.ethereum.org/, install `solc` directly on your machine, or use Truffle/Embark or some other development environment for Solidity.
