### ISSUE TITLE
Disconnects both trusted and static nodes as "useless peers"

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/go-ethereum#17181]
#### System information

Geth version: `1.8.12`
OS & Version: OSX

#### Expected behaviour

I have a fully synced geth node and a trinity node running locally.  The trinity node is in both the trusted and static nodes list.  geth regularly drops the trinity node as a useless peer.

#### Actual behaviour

I expect trusted nodes and static nodes to be treated in such a way that they are allowed to remain connected even if they are determined to be useless.

#### Steps to reproduce the behaviour

Can provide if needed.  I suspect it isn't.

Here are the logs I'm seeing

```
DEBUG[07-16|09:49:25.415] Removing p2p peer                        id=7b8fb3e32de9aa5d conn=trusted-inbound duration=15.010s peers=0 req=false err="useless peer"
```

and 

```
DEBUG[07-16|09:49:49.025] Removing p2p peer                        id=7b8fb3e32de9aa5d conn=trusted-staticdial duration=15.007s peers=0 req=false err="useless peer"
```

**Comment by shazow** [comment]
Running into this also, on `geth 1.8.15` on Linux, using a fully sync'ed geth node and a geth node in light client mode.

**Comment by shazow** [comment]
Actually I take mine back, I had to remove `--syncmode fast` from my full node which was conflicting with `--lightserv 60`. Seems to work now.

**Comment by hermanjunge** [comment]
I just debugged a similar issue a couple weeks ago and it was a protocol problem. One machine was able to speak `les` but not `eth/62` not `eth/63`. We solved it by removing the `--light` command line option in one. Hope that helps.
