### ISSUE TITLE
Negative Block Number returns incorrect error message

### ISSUE THREAD

**Issue by ChaiBapchya** [ethereum/go-ethereum#17193]
#### System information

Geth version: `Geth/v1.8.12-unstable-598f786a/linux-amd64/go1.10.3`
OS & Version:Linux

#### Expected behaviour
When you search for a negative block number, it should return an error stating that 

```
"Can't search for negative block-number. Only non-negative blockNumbers expected"
```

#### Actual behaviour
When `blockNumber<0`
`eth.getBlock(i, true);` 
returns 
```
Error: invalid argument 0: hex string without 0x prefix
        at web3.js:3143:20
        at web3.js:6347:15
        at web3.js:5081:36
        at getTransactionsByAccount (/root/files/js/getTransactionsByAccount.js:16:18)
        at <anonymous>:1:43
```

#### Steps to reproduce the behaviour
In a geth console,
`eth.getBlock(-1, true);`
In place of -1 any negative number can be tried

**Comment by ligi** [comment]
I think the current error message is correct. It expects a 0x prefixed hex an tells you this.
