### ISSUE TITLE
Block Syncing Freezes Intermittently

### ISSUE THREAD

**Issue by jakecraige** [ethereum/go-ethereum#17199]
#### System information

Geth version: At least `1.8.7`, `1.8.11` and `1.8.12`
Archive Node: Database is 1.2 TB+
OS & Version: Linux

#### Expected behaviour
Consistently syncing blocks as they are propagated around the network without long delays

#### Actual behaviour
Syncing seems freeze for periods of time and then eventually recover as can be seen on this graph of block heights. The top two are running 1.8.11 and the bottom two 1.8.12. The logs below are from the one in yellow.

1hr period for detail which matches log further down. Time zone is Pacific
![screen shot 2018-07-18 at 9 24 11 am](https://user-images.githubusercontent.com/3799709/42894687-5c99020e-8a6c-11e8-91b9-78ffef9b41e4.png)

24hours
![screen shot 2018-07-18 at 12 43 19 pm](https://user-images.githubusercontent.com/3799709/42903966-424968e6-8a88-11e8-8113-90afc54f75ff.png)

The first time we saw this sort of thing was on 2018-05-15 with 1.8.7 but it wasn't too bad. In the past few weeks this has become more regular and problematic.

#### Steps to reproduce the behaviour

This is intermittent, sometimes it happens sometimes it doesn't. No method I'm aware of to reproduce. Last night (July 17-18) was particularly bad and we saw large periods of times like in the graph.

#### Logs

I've done a brief analysis on the logs and noticed a massive spike in the "Fetching batch of block bodies" log message when this is happening. Here's a screenshot of counts of that specific message. 

![screen shot 2018-07-18 at 9 30 02 am](https://user-images.githubusercontent.com/3799709/42895002-5695425e-8a6d-11e8-9a62-9057f76338f1.png)

Here's a sample of the logs during this period. Time zone is UTC:
https://gist.github.com/jakecraige/34c2aa32a46b90406d1482a2f196c16b#file-geth-csv

Any guidance here would be helpful.

**Comment by SvenMeyer** [comment]
likely same issue as #16825 ... nice graphs though ;-)

**Comment by jakecraige** [comment]
Closing as we haven't seen this issue in quite awhile now 👍
