### ISSUE TITLE
Can not use `←` & `→` keys in geth console

### ISSUE THREAD

**Issue by isLishude** [ethereum/go-ethereum#17194]
#### System information

Geth version: 1.8.12
OS & Version: Ubuntu 18.04
Commit hash : (if `develop`)

#### Expected behaviour

input `←` should left shift of cursor

#### Actual behaviour

but outputs ^[[A^[[B^[[C^[[D

#### Backtrace

````
[backtrace]
````

**Comment by RaghavSood** [comment]
This sounds more like a terminal issue. Arrow keys work fine for me in the console. Make sure your terminal/ssh connection is set up correctly to allow navigation via arrow keys.

**Comment by isLishude** [comment]
But I use Docker…
