### ISSUE TITLE
geth node does not promote transactions from "queued" to "pending"

### ISSUE THREAD

**Issue by poctek** [ethereum/go-ethereum#17209]
Several days ago I submitted ~13k transactions to the node. All those transactions were sitting in the `queued` txpool section:

```
> txpool.status
{
  pending: 0,
  queued: 12833
}
```

Today I changed the entrypoint script with txpool enhancements and now I have the following:

```
> txpool.status

{
  pending: 49285,
  queued: 13277
}
```

All my transactions are transfer transactions to the same address and look like this one:

```
9999: "0xe2Ee1ac57B2E5564522b2dE064A47b3f98B0e9c9: 0 wei + 100000 gas × 2000000000 wei"
```

None of my transactions are in the `pending` section. Is it OK? Is there a way to make the promotion manually?

Here's my geth startup command:

```
geth --rpc --rpcaddr 0.0.0.0 \
--rpccorsdomain "*" \
--rpcport 6588 \
--rpcapi "eth,net,web3,txpool" \
--maxpeers "125" \
--cache "8192" \
 --txpool.globalslots 4294967295 \
--txpool.accountqueue 429496729 \
--txpool.globalqueue 4294967295 \
--txpool.accountslots 429496729 \
--txpool.lifetime "72h0m0s" \
--trie-cache-gens "1024" \
--gasprice "5000000000"
```

#### System information

```
Geth version:  Geth/v1.8.12-stable/linux-amd64/go1.10.3
OS & Version: Linux
Base image from the docker hub with custom entrypoint
```

#### Expected behaviour
Transactions should be pending, not queued

#### Actual behaviour
All my local transactions are queued, even though in the pedning list there're some transactions with lower gas price

#### Steps to reproduce the behaviour
I can provide `transactions.rlp` file with the queued transactions

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Make sure there is no gap in the nonces. The account you send form has a very specific nonce that the first transaction should have. If your transaction has a higher nonce, it cannot be executed.

**Comment by poctek** [comment]
@karalabe double-checked: it turned out that I considered initial nonce to be 1 instead of 0. Sending one transaction to my address filled the gap and the transactions started the propagation. Thanks for your help!
