### ISSUE TITLE
error: TypeError: 'deleteAccount' is not a function

### ISSUE THREAD

**Issue by cozylife** [ethereum/go-ethereum#1720]
When I run the following code through the console, I get `error: TypeError: 'deleteAccount' is not a function`.

`personal.deleteAccount("0x02da8a309e708914af3d8485897653221b5d001d", "mypass")`

**Comment by karalabe** [comment]
Hmm, as far as I know, we do not want to support programmatic deletion of accounts. It is not supported from `geth accounts` either and I'm curios as to why it was even included in the API docs. My take is that is was a mistake to document such a feature but I'll ask around and see what others have to say. The idea generally is that deleting an account is a very very dangerous operation, so we don't want to open ourselves up to malicious/buggy scripts or user inattention.

**Comment by bas-vk** [comment]
@karalabe is right. This function should not be there.

**Comment by karalabe** [comment]
Deleted from the wiki, traces will be removed from the API too via https://github.com/ethereum/go-ethereum/pull/1722.
