### ISSUE TITLE
Error: no suitable peers available

### ISSUE THREAD

**Issue by mscherer82** [ethereum/go-ethereum#17211]
When I try to deploy I got `Error: no suitable peers available`. `net.peerCount` says 2. Node is synced and keeps syncing when new blocks arrive.

#### System information

Geth version: `1.8.12`
OS & Version: Linux

**Comment by nicszerman** [comment]
+1

**Comment by zachbellay** [comment]
Same issue on Raspberry Pi when entering `eth.getBalance(eth.accounts[0])` on geth Javascript console:
```
Error: no suitable peers available
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```

**Comment by nicszerman** [comment]
Restarting without using the argument `--light` fixed it for me.

**Comment by githubcyc** [comment]
u may add peer for light node. --> [node list ](https://gist.github.com/rfikki/e2a8c47f4460668557b1e3ec8bae9c11)

**Comment by AyushyaChitransh** [comment]
Calling following API is giving me this error:
```
web3.eth.getCode("0x0....123")
```

Is there a way to get this API working? Do I need to add peers to my client?

**Comment by ankita-p17** [comment]
Facing this now : 
geth --rinkeby --rpc --syncmode "light" --rpcport 8543 --rpcaddr 127.0.0.1 --rpccorsdomain "*" --port "35555" --rpcapi "eth,net,web3,personal,miner,admin"
- geth 1.9.0
Started geth an hour back still no peers found 
Error: no suitable peers available
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

**Comment by karalabe** [comment]
The original issue is fairly old and a lot of work went into les, so I'd close this issue. As for Rinkeby, it probably could help to check port forwarding.

**Comment by wafcio** [comment]
I have found solution which works in mu case https://gist.github.com/rfikki/e2a8c47f4460668557b1e3ec8bae9c11
