### ISSUE TITLE
Geth light mode never stops

### ISSUE THREAD

**Issue by ishanSrt** [ethereum/go-ethereum#17215]
on macos Mojave here, go version 1.10.3 and the command `geth --syncmode "light" --cache <cache_size>` never stops. Even when it has got the block that was mined like 2s ago which I see over here https://etherscan.io/blocks

**Comment by ishanSrt** [comment]
if I stop it with keyboard interrupt and try to use the Geth command it goes back to syncing and this time it also seems to be downloading receipts with headers

**Comment by ishanSrt** [comment]
Number vs time at the bottom left corner

<img width="1440" alt="screenshot 2018-07-20 at 10 59 58 pm" src="https://user-images.githubusercontent.com/29859362/43016553-c826e60c-8c70-11e8-97ec-70679d63f97f.png">

**Comment by ishanSrt** [comment]
GMT +5:30

**Comment by karalabe** [comment]
I don't understand what the problem is. Geth is a network node, syncing to the Ethereum network. It was not meant to stop, it's meant to be running and pulling blocks as they are produced.

**Comment by ishanSrt** [comment]
@karalabe but the fast node doesn't behave that way! It actually stops so I thought there was some problem with my light node.
