### ISSUE TITLE
I can't get the msg.sender

### ISSUE THREAD

**Issue by kay07** [ethereum/go-ethereum#17228]
I have two contract ,which is a and b.I want to use b to get the msgsender in the a contract.

`pragma solidity ^0.4.24;
contract a{
    function getmsgsender()public view returns(address){
        address a=msg.sender;
        return a;
    }
}`
`pragma solidity ^0.4.24;
contract ERC721Interface {
  function getmsgsender() public view returns (address);
 }
contract b {
  ERC721Interface public nonFungibleRegistry;
    constructor(address _nonFungibleRegistry) public {
    nonFungibleRegistry = ERC721Interface(_nonFungibleRegistry);
  }
  function get()public view returns (address){
      return nonFungibleRegistry.getmsgsender();
  }
}`
In the remix, I  use get() function can get the msg.sender which is the address of contract b, but in the  geth ,I can get nothing , why?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
