### ISSUE TITLE
Restarting Geth loses all transactions?

### ISSUE THREAD

**Issue by DottoreM** [ethereum/go-ethereum#17232]
Hi there,

I am using the below commands to a private network.

`geth --datadir c:\\blockchain init c:\\genesis.json`

`geth –-identity "blockdb" –-rpc -–rpcport "9040" --rpccorsdomain "*" –-rpcapi "db,eth,net,web3" –-datadir "c:\\blockchain" –-port "30303" –-nodiscover –-networkid 76543 console`

When I close the CMD (effectively shutting off the node) and restart it again, using the same line of code 

`geth –-identity "blockdb" –-rpc -–rpcport "9040" --rpccorsdomain "*" –-rpcapi "db,eth,net,web3" –-datadir "c:\\blockchain" –-port "30303" –-nodiscover –-networkid 76543 console`

I am keeping all wallets i create but all the Ether and transactions are reset to 0.

I have already [asked ](https://ethereum.stackexchange.com/questions/54756/ethereum-deployment-problems )in the stack exchange community, came across a [similar ](https://ethereum.stackexchange.com/questions/39922/ethereum-private-chain-resets-back-to-block-0-when-restarted) question but did not solve the issue.  I have more than 130 blocks (that might be empty). Now I am asking here because I came across this [question ](https://stackoverflow.com/questions/48827797/ethereum-private-chain-resets-back-to-block-0-when-restarted) and I noticed the following comment: 

> Thanks everyone just figured out the issue. Problem is with the geth 1.8 Iceberg version it resets the blockchain everytime u close the console I downgraded to 1.7.3 stable and the issue is solved :) Do not use the 1.8 geth version yet – Saliya Perera Feb 17 at 2:01

So, is there really an issue with Geth Versions 1.8????

**Comment by liwei00wade** [comment]
@karalabe karalabe
how to resync that part ? 

which command ?

**Comment by taoxinyi** [comment]
@karalabe  Is there a way to force geth to push the data to disk immediately whenever a new block is created?
