### ISSUE TITLE
Failed to build Solidity contract - "...MintableToken.sol" not found: File not found.

### ISSUE THREAD

**Issue by zulhfreelancer** [ethereum/go-ethereum#17238]
#### System information

Geth version: 1.8.12-stable
OS & Version: OSX 10.12.6

#### Expected behaviour

Able to run `abigen` command and get _ABCtoken.go_ file.

#### Actual behaviour

When I ran `abigen --sol=ABCtoken.sol --pkg=main --out=ABCtoken.go` command, I got the following error:

```
Failed to build Solidity contract: solc: exit status 1
ABCtoken.sol:3:1: Error: Source "openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol" not found: File not found.
import "openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol";
^---------------------------------------------------------------------^
```

#### Steps to reproduce the behaviour

1) Init a Truffle project.

2) Create a new contract. Name the file as _ABCtoken.sol_.

```
pragma solidity ^0.4.23;

import "openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol";

contract ABCtoken is MintableToken {
  string public constant name = "ABCtoken";
  string public constant symbol = "ABC";
  uint8 public constant decimals = 18;

  constructor() public {
    // make the deployer rich
    balances[msg.sender] = 1000 * 1 ether;
  }
}
```

3) Run `yarn add openzeppelin-solidity` command.

4) Run `truffle compile` and make sure you see no errors.

5) `cd` into `contracts` folder.

6) Run `abigen --sol=ABCtoken.sol --pkg=main --out=ABCtoken.go`.

I'm not sure this is go-ethereum abigen problem or [openzeppelin-solidity](https://www.npmjs.com/package/openzeppelin-solidity) problem. 😕

**Comment by RaghavSood** [comment]
If you've already compiled the contract, why not use `--abi ABCtoken.abi` instead of sol?

**Comment by discountry** [comment]
Make sure you've runed:
```
truffle init
npm install zeppelin-solidity
```
you need that package to import `.sol` files. This is not a bug for etheruem.

Please check carefully next time.

**Comment by zulhfreelancer** [comment]
I tried with many options. The problem persists.

| Installation Command                  | Path inside ABCtoken.sol                                                  | ABIGEN Result | Truffle Compile Result |
|---------------------------------------|---------------------------------------------------------------------------|---------------|------------------------|
| `$ yarn add zeppelin-solidity`        | `import "zeppelin-solidity/contracts/token/ERC20/MintableToken.sol";`     | Failed        | Passed                 |
| `$ npm install zeppelin-solidity`     | `import "zeppelin-solidity/contracts/token/ERC20/MintableToken.sol";`     | Failed        | Passed                 |
| `$ yarn add openzeppelin-solidity`    | `import "openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol";` | Failed        | Passed                 |
| `$ npm install openzeppelin-solidity` | `import "openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol";` | Failed        | Passed                 |
