### ISSUE TITLE
how use jsonrpc invoking self-build （local）contract

### ISSUE THREAD

**Issue by LeeGG** [ethereum/go-ethereum#17242]
As it said in title

I have ever seen  https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI
but not at all clear

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
