### ISSUE TITLE
geth displays input on one line on Linux

### ISSUE THREAD

**Issue by tom-seddon** [ethereum/go-ethereum#1725]
geth for Linux displays input on one line, rather than printing it over several lines. This makes it difficult to review the input (both current and previous lines), and impossible to copy lengthy command lines from the terminal scroll buffer.

Is this configurable somewhere? Or is there something else that influences whether you get this behaviour?

Thanks,

--Tom

**Comment by maran** [comment]
Hey Tom,

Could you give me a command that you are trying to run so I can replicate it locally?

**Comment by tom-seddon** [comment]
Sure:

    abi=[{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"type":"function"},{"inputs":[{"name":"initialValue","type":"uint256"}],"type":"constructor"}]

Thanks,

--Tom

**Comment by maran** [comment]
Ok so just to clarify, you are not talking about the output that geth is generating but that you would like to input things over multiple lines, is this correct?

Have you considered using something like `build/bin/geth --exec  'loadScript("test.js")' attach` as documented [here](https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console). Would that solve your issues?

**Comment by tom-seddon** [comment]
Thanks. Yes, it's the input I type in. geth shows it all on one line, with horizontal scrolling. Try running geth and holding down the 'a' key - it all gets printed on one line. Then try doing the same in bash or zsh - the input goes over multiple lines.

I do have some code in scripts, but I seem to end up with a lot of these long command lines when working in the REPL trying stuff out and experimenting and/or when I'm having problems. In this sort of situation I like to be able to review previous input lines, and copy and paste bits out of old ones, so being able to see the whole thing is very useful.

--Tom

**Comment by fjl** [comment]
Multi-line command line editing is hard to implement. The line reader that we use doesn't support it and probably never will. We will keep this in mind for the future, in case we switch to a different library.
