### ISSUE TITLE
function miner.start() return null

### ISSUE THREAD

**Issue by hellochueng** [ethereum/go-ethereum#17275]
Geth version: go-ethereum-1.7.2
OS & Version:  centos 7

#### Expected behaviour
miner.start()
return false or true

but return null

----------------------------------------------------------------------------------------------------------------

my genens.json is:
{
"config": {
"chainId": 10,
"homesteadBlock": 0,
"eip155Block": 0,
"eip158Block": 0
},
"alloc" : {},
"coinbase" : "0x0000000000000000000000000000000000000000",
"difficulty" : "0x02000000",
"extraData" : "",
"gasLimit" : "0x2fefd8",
"nonce" : "0x0000000000000042",
"mixhash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
"parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
"timestamp" : "0x00"
}
----------------------------------------------------------------------------------------------------------------

and the result don't have any failed result, after i init :

----------------------------------------------------------------------------------------------------------------
WARN [07-30|14:15:19] No etherbase set and no accounts found as default
INFO [07-30|14:15:19] Allocated cache and file handles database=/root/eth2/geth/chaindata cache=16 handles=16
INFO [07-30|14:15:19] Writing custom genesis block
INFO [07-30|14:15:19] Successfully wrote genesis state database=chaindata hash=bf2891…ad1419
INFO [07-30|14:15:19] Allocated cache and file handles database=/root/eth2/geth/lightchaindata cache=16 handles=16
INFO [07-30|14:15:19] Writing custom genesis block
INFO [07-30|14:15:19] Successfully wrote genesis state database=lightchaindata hash=bf2891…ad1419
----------------------------------------------------------------------------------------------------------------

but when i use geth to connect my chainnode and use miner.start() to start mining,the result show null

----------------------------------------------------------------------------------------------------------------
eth.accounts
[]
personal.newAccount("123456")
"0xb3d3dda3f47c1da6aa1449f0bff666a61984ab2d"
eth.coinbase
"0xb3d3dda3f47c1da6aa1449f0bff666a61984ab2d"
miner.setEtherbase(personal.listAccounts[0])
true
miner.start()
null
eth.blockNumber
0
miner.stop()
true
miner.start()
null
eth.getBalance(eth.coinbase)
0
----------------------------------------------------------------------------------------------------------------

the starting log follow:

----------------------------------------------------------------------------------------------------------------

INFO [07-30|14:21:45] RLPx listener up                         self=enode://ed56d448e39c429a2                                    65f11ad89218affef17766b404717e322b07a9a1ac98f4d014604a55a9d78a73537e5fe2f56290922388e5faea0fc                                    23e6cf558c7e36e4cb@[::]:30303
INFO [07-30|14:21:45] IPC endpoint opened: /root/eth2/geth.ipc
INFO [07-30|14:23:23] Updated mining threads                   threads=0
INFO [07-30|14:23:23] Transaction pool price threshold updated price=18000000000
INFO [07-30|14:23:23] Starting mining operation
INFO [07-30|14:23:23] Commit new mining work                   number=1 txs=0 uncles=0 elapse                                    d=129.74µs
INFO [07-30|14:24:56] Updated mining threads                   threads=0
INFO [07-30|14:24:56] Transaction pool price threshold updated price=18000000000
INFO [07-30|14:24:56] Starting mining operation
INFO [07-30|14:24:56] Commit new mining work                   number=1 txs=0 uncles=0 elapse                                    d=266.626µs

----------------------------------------------------------------------------------------------------------------

i  wait mining  for a long time,the account balance still is 0

i cant wait it,so i find help there

(somebody say is due to no transaction to commit,so is cant mining,but when i init a chainnode and new a account, there is no Balance on the new Account,and i can't to commit Transaction,so i interrupt in this)

[backtrace]

**Comment by karalabe** [comment]
My hunch is that your starting difficulty is too high (`"difficulty" : "0x02000000"`). Either reduce that to something two orders of magnitude smaller, or consider running a PoA chain if it's a single node.
