### ISSUE TITLE
Geth 1.8.12 seems to ignore --targetgaslimit when using "geth console" to start the client

### ISSUE THREAD

**Issue by VictorRemmerswaal** [ethereum/go-ethereum#17287]
Hi, I think I've found an issue starting geth using "geth console" and --targetgaslimit

#### System information

Geth version: Geth/v1.8.12-stable-37685930/windows-amd64/go1.10.3
OS & Version: Windows

#### Expected behaviour
The geth node votes to increase the block gas limit when the targetgaslimit is set higher than the current limit using --targetgaslimit

#### Actual behaviour
The geth node votes to decrease the block gas limit

#### Steps to reproduce the behaviour
1. Have a private blockchain with a starting gaslimit higher than the default.
2. Start geth using "geth console ..... --targetgaslimit <higher than it currently is>"
3. Repeatedly check the gas limit using eth.getBlock('latest').gasLimit
4. See the gas limit decrease.

**Comment by karalabe** [comment]
Please make sure your flags are correct. You probably mistyped something, or a flag has a long dash instead of short (osx copy paste issue).
