### ISSUE TITLE
Swarm: Manifest is malformed: invalid character '\u0089' looking for beginning of value

### ISSUE THREAD

**Issue by kyriediculous** [ethereum/go-ethereum#17283]
Hi,

I'm trying to use swarm in a private network and wanted to showcase it in my presentation by directly  resolving hashes in the browser. When I go to `http://localhost:8500` in the browser I get the swarm web page correctly. When I enter a hash I get an error.
`Manifest is malformed: invalid character '\u0089' looking for beginning of value`

**I can succesfully add and resolve files from the swarm in my Electron app through the same URI.**

I also get CORS errors in the browser despite setting `-corsdomain '*'` , any ideas on this? Works fine in electron which I suppose sets origin to null or something. 

Geth version: latest
OS & Version: Windows

#### Expected behaviour
Expect to retrieve a file through it's swarm hash when surfing to http://localhost:8500/bzz:/<swarmHash>

Expect no CORS issues after setting corsdomain to a wildcard.

#### Actual behaviour
Getting error: Manifest is malformed: invalid character '\u0089' looking for beginning of value
Getting CORS errors in browser.

Console warning: 
`WARN [07-31|16:23:50] loadManifestTrie error: Manifest 2ee7f8df is malformed: invalid character '\u0089' looking for beginning of value`

#### Steps to reproduce the behaviour
Private 1 node swarm, not connected to a blockchain started with following command:
`swarm --bzzaccount 0429ea2bf410a6d815cf5314dce0240f2363167a --datadir swarm/ --keystore swarm/keystore --bzzport 8500 -corsdomain '*'`

#### Console Log

````
λ swarm --bzzaccount 0429ea2bf410a6d815cf5314dce0240f2363167a --datadir swarm/ --keystore swarm/keystore --bzzport 8500 -corsdomain '*'
INFO [07-30|17:30:01] Maximum peer count                       ETH=25 LES=0 total=25
Unlocking swarm account 0x0429eA2bF410A6D815cF5314dce0240f2363167a [1/3]
Passphrase:
INFO [07-30|17:30:05] Starting peer-to-peer node               instance=swarm/v1.8.11-stable-dea1ce05/windows-amd64/go1.10.2
INFO [07-30|17:30:05] Starting P2P networking
INFO [07-30|17:30:07] Mapped network port                      proto=udp extport=30399 intport=30399 interface="UPNP IGDv1-IP1"
INFO [07-30|17:30:07] UDP listener up                          self=enode://dee0fd293f0b6ef1ed94b89d06f679d6c82fcb4b495f538e8fe0ccc5ed2b0fdbd3e27c35506cbae644d47ad4b1431ddbcd748e5061622e47dbf944e50ba0ac2e@81.242.180.35:30399
WARN [07-30|17:30:07] Starting Swarm service
INFO [07-30|17:30:07] RLPx listener up                         self=enode://dee0fd293f0b6ef1ed94b89d06f679d6c82fcb4b495f538e8fe0ccc5ed2b0fdbd3e27c35506cbae644d47ad4b1431ddbcd748e5061622e47dbf944e50ba0ac2e@81.242.180.35:30399
INFO [07-30|17:30:07] loaded kaddb with 0 nodes from C:\Users\N.vergauwen\Documents\swarm\swarm\swarm\bzz-0429ea2bf410a6d815cf5314dce0240f2363167a\bzz-peers.json
INFO [07-30|17:30:07] Swarm network started on bzz address: 5374a744d533c2131f49796a4c19f647e78d9cf8df0ed56e724c0379b06f2f4b
INFO [07-30|17:30:07] Swarm http proxy started on 127.0.0.1:8500
INFO [07-30|17:30:07] IPC endpoint opened                      url=\\\\.\\pipe\\bzzd.ipc

INFO [07-30|17:30:07] Mapped network port                      proto=tcp extport=30399 intport=30399 interface="UPNP IGDv1-IP1"
WARN [07-30|17:30:20] System clock seems off by -38.509471367s, which can prevent network connectivity
WARN [07-30|17:30:20] Please enable network time synchronisation in system settings.

````

**Comment by kyriediculous** [comment]
Works when using http://localhost:8500/bzzr:/<swarmHash> 

I did not see anything regarding bzzr: in the docs. **The docs only mention bzz-resource and bzz, neither of those work.**. Seems like the docs need updating.

When using bzzr however I get a file download, I expected the file to just resolve in the browser like IPFS Browser would.

**Comment by holisticode** [comment]
What version of swarm are you using, or how did you install swarm? We don't even have `bzzr:/` anymore. It should be `bzz`, `bzz-resource` etc. Which points to the fact that you may be running an outdated version of the code (the documentation is correct in this respect)

**Comment by kyriediculous** [comment]
@holisticode Sorry, I assumed the  windows .exe would be the latest version. 
Apologies!

Geth
Version: 1.8.11-stable
Git Commit: dea1ce052a10cd7d401a5c04f83f371a06fe293c
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.2
Operating System: windows
GOPATH=C:\Users\N.vergauwen\go
GOROOT=C:\Go\

λ swarm version
Swarm
Version: 1.8.11-stable
Git Commit: dea1ce052a10cd7d401a5c04f83f371a06fe293c
Network Id: 0
Go Version: go1.10.2
OS: windows
GOPATH=C:\Users\N.vergauwen\go
GOROOT=C:\Go\

**Comment by homotopycolimit** [comment]
where did you get that .exe? If it is from our downloads page, I'd hope it's the newest (version 0.3.1 we're calling it - it was released alongside geth 1.8.13)

**Comment by kyriediculous** [comment]
@homotopycolimit the official website : https://geth.ethereum.org/downloads/

I'll try a clean install !

**Comment by homotopycolimit** [comment]
try swarm.ethereum.org 
i.e. https://swarm-gateways.net/bzz:/theswarm.eth/downloads/

**Comment by kyriediculous** [comment]
Okay thanks ! 

I really thought this was the latest version since https://github.com/MaiaVictor/swarm-js still uses bzzr:/ as well, altough it doesn't seem like an active repo anymore.

Not that the bzzr:/ is a thorn in my eye, the CORS issue is however.

```
  // String -> String -> String
  const rawUrl = swarmUrl => hash =>
`${swarmUrl}/bzzr:/${hash}`
```

**Comment by homotopycolimit** [comment]
ah yes. I think swarm-js is not maintained. @MaiaVictor ?

**Comment by kyriediculous** [comment]
Ah too bad, I'll just have to maintain a fork then.

By the way some additional info
My collegue just installed geth 1.8.13 
Geth was installed , swarm was not included in the exe build.

**Comment by homotopycolimit** [comment]
Windows builds of swarm: https://swarm-gateways.net/bzz:/theswarm.eth/downloads/#dl_stable_windows

**Comment by kyriediculous** [comment]
Yep it works now, CORS setting too. Thanks! 

Both javascript libraries mentioned in the documents are outdated by the way.

**Comment by homotopycolimit** [comment]
> Changing bzzr: to bzz: works

you should change bzzr to bzz-raw and bzzi to bzz-immutable.

> but not sure if there are any other breaking changes

there are... but I don't know them all off hand.
