### ISSUE TITLE
eth_getLogs not work in geth version 1.8.13

### ISSUE THREAD

**Issue by nkbai** [ethereum/go-ethereum#17289]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.8.13`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour
eth_getLogs get the contract event i want

#### Actual behaviour
always return emtpy logs, but if I switch back to 1.8.2 ,the same code gets the logs i want

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Please send us the code that you use to retrieve the logs. It's important for us to be able to repro.
