### ISSUE TITLE
geth client: can't sync to the network, no peers

### ISSUE THREAD

**Issue by immoshe** [ethereum/go-ethereum#1729]
Hi,

I need some help in connecting to the network.
I've installed geth (latest version 1.1.0) on windows , created an account and running it.
when running geth, I see that net.listening is 1 but no nodes (net.peercount is zero). I don't see any transaction.

Any idea what am i missing ? what do I need to get nodes and conect to the network?

Attached screenshot.
![screenshot 2015-08-26 19 46 28](https://cloud.githubusercontent.com/assets/13987125/9504197/eb3a0496-4c43-11e5-9d1a-9ad9852cb485.png)

Thanks for any help
Moshe

**Comment by karalabe** [comment]
Are you sure the windows or some third party firewall isn't blocking it?

**Comment by fjl** [comment]
The genesis hash looks wrong in that screenshot. Did you generate the genesis block yourself?

**Comment by immoshe** [comment]
Yes. I generate it by myself. Can I download it from any other place ?
BTW, I ran with firewall off and it still not connected.

**Comment by immoshe** [comment]
I download it now from here: https://forum.ethereum.org/discussion/comment/10499/#Comment_10499
and I'm connected now.

Thanks for your help
Moshe
