### ISSUE TITLE
eth.sendTransaction from eth.coinbase makes multiple transactions and decrease the eth.coinbase balance

### ISSUE THREAD

**Issue by marcosmartinez7** [ethereum/go-ethereum#17294]
#### System information

Geth version: 1.8.12-stable
OS & Version: Ubuntu 16.04

#### Expected behaviour

One transaction is submitted when i send ether from coinbase to another address

#### Actual behaviour

Multiple transactions are submitted, the coinbase balance is decreased from a huge initial balance to almost 0.0026 ether

#### Steps to reproduce the behaviour

Im working on a distributed application using Ethereum, the go-ethereum implementation (Geth).

On a Digital Ocean droplet (Ubuntu 16.04) i have installed geth.

I have created a structure like this:

    devnet$ tree -L 2
    .
    ├── accounts.txt
    ├── boot.key
    ├── genesis.json
    ├── node1
    │   ├── geth
    │   ├── keystore
    │   └── password.txt
    

I have:

- One bootnode/discovery node
- One Seal/full node

The seal node is initialized this way:

    geth --datadir node1/ init genesis.json

Then the bootnode:

    devnet$ bootnode -nodekey boot.key -verbosity 9 -addr :30310
    INFO [02-07|22:44:09] UDP listener up                          self=enode://3ec4fef2d726c2c01f16f0a0030f15dd5a81e274067af2b2157cafbf76aa79fa9c0be52c6664e80cc5b08162ede53279bd70ee10d024fe86613b0b09e1106c40@[::]:30310

And after the bootnode is listening, i run geth on the node1: 

    geth --datadir node1/ --syncmode 'full' --port 30311 --rpc --rpcaddr 'localhost' --rpcport 8501 --rpcapi 'personal,db,eth,net,web3,txpool,miner' --bootnodes 'enode://3ec4fef2d726c2c01f16f0a0030f15dd5a81e274067af2b2157cafbf76aa79fa9c0be52c6664e80cc5b08162ede53279bd70ee10d024fe86613b0b09e1106c40@127.0.0.1:30310' --networkid 1515 --gasprice '1' -unlock '0x87366ef81db496edd0ea2055ca605e8686eec1e6' --password node1/password.txt --mine

Note: this are examples, the real ip, bootnode "enode" value and account arent those. 

On this private ethereum network i have deployed a ERC20 contract, with a basic Transfer function, so, i wanted to invoke that function from Metamask, using some random address.

For that, i needed to get some ETH in my account, so i have connected to the geth console and transfer some ether from the eth.coinbase to that addres:

    eth.sendTransaction({from:eth.coinbase, to:"0xf17f52151ebef6c7334fad080c5704d77216b732", value: web3.toWei(10, "ether")})

After that, I discovered that some transactions that I had no way to identify,  i mean, it was only a transaction to send ether from one account to another, why that result in multiple transactions submitted?

Here is a screenshot of the situation:

![loop](https://user-images.githubusercontent.com/14795944/43497509-ec333f22-9518-11e8-985d-69f6f2850e77.png)

  [1]: https://i.stack.imgur.com/qnucY.png

Also, every one of those transactions is decreasing the eth.coinbase balance (eth.coinbase == the address that deploys the contract), so i started with a huge amount of Ether on that account and after some of those "ghost" transactions the balance of eth.coinbase was like 0.0026 Ether..

So, i have 2 questions

1. Is there any scenario that could decrease the contract owner address/coinbase balance? 
2. Any ideas of why those transactions appear?

**Comment by Saurabh1402** [comment]
as per the screenshot you are send ether to '0xedff...' but in the node log i dont see any recipient for the transaction as '0xedff....'. Please send the screenshot for the same timestamp.

**Comment by marcosmartinez7** [comment]
Seems like this is caused by some bots https://github.com/ethereum/go-ethereum/issues/16691

**Comment by marcosmartinez7** [comment]
As a solution for this, my idea was to create:

1. bootnode
2. one miner node with an unlocked accounts and without rpc accessing
3. one standard node: this node will be receive all my rpc calls

i have sent transactions to the standard node, expecting that the transaction will be broadcasted to the miner node but it didnt happend

i think this is related with this issue: https://github.com/ethereum/go-ethereum/issues/2769

can you help me with the setup for accomplish this? is the idea wrong? 

thxs

**Comment by marcosmartinez7** [comment]
Any ideas of how i can expose the RPC interface of my network if i have unlocked accounts? 

is there any workarround for having one node that allows RPC connections from all internet?
