### ISSUE TITLE
Geth attach is not working for windows ( ipc path )

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#17298]
Command `geth.exe attach` doesn't work with windows,

only adding `ipc:\\.\pipe\geth.ipc` will work properly

Any ideas @karalabe ??

**Comment by VEmidio** [comment]
.\geth.exe attach ipc:\\.\pipe\geth.ipc

**Comment by VEmidio** [comment]
.\geth.exe attach ipc\\.\pipe\geth.ipc

**Comment by holiman** [comment]
Seems solved

**Comment by cosmicbubble69** [comment]
Fatal: Unable to attach to remote geth: Timed out waiting for pipe '\\.\pipe\geth.ipc' on windows

**Comment by sceriz** [comment]
> Fatal: Unable to attach to remote geth: Timed out waiting for pipe '\.\pipe\geth.ipc' on windows
`geth attach \\.\pipe\geth.ipc` ended up working for me
