### ISSUE TITLE
Private Networking commands missing - geth Invalid command: "init"

### ISSUE THREAD

**Issue by 9607835** [ethereum/go-ethereum#17304]
https://github.com/ethereum/go-ethereum/wiki/Private-network
states to use `geth init` as do all other tutorials, and it works perfectly in previous versions.

https://github.com/ethereumproject/go-ethereum/wiki/Command-Line-Options
makes no mention of init

and `geth init genesis.json` results in

    Invalid command: "init". [...]

Geth
Version: source
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Go OS: linux
Go Arch: amd64
Machine ID: DEADBABEBEEFCAFE
GOPATH=
GOROOT=/usr/local/go
commit: 16eaf2b158ca28b0b4aa48cfb400a7cf8ed70234

#### Expected behaviour
init should be an available command, or should not be mentioned in the documentation

#### Actual behaviour
it isn't an available command even though it's in the documentation

#### Steps to reproduce the behaviour
geth init genesis.json

**Comment by karalabe** [comment]
Hmm, it does seem to work for me:

```
geth --datadir=/tmp/test init genesis.json 
INFO [08-02|10:29:03.721] Maximum peer count                       ETH=25 LES=0 total=25
INFO [08-02|10:29:03.790] Allocated cache and file handles         database=/tmp/test/geth/chaindata cache=16 handles=16
INFO [08-02|10:29:03.804] Writing custom genesis block 
INFO [08-02|10:29:03.805] Persisted trie from memory database      nodes=6 size=870.00B time=90.388µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [08-02|10:29:03.805] Successfully wrote genesis state         database=chaindata                hash=aeba38…9aab92
INFO [08-02|10:29:03.805] Allocated cache and file handles         database=/tmp/test/geth/lightchaindata cache=16 handles=16
INFO [08-02|10:29:03.823] Writing custom genesis block 
INFO [08-02|10:29:03.824] Persisted trie from memory database      nodes=6 size=870.00B time=57.655µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [08-02|10:29:03.824] Successfully wrote genesis state         database=lightchaindata                hash=aeba38…9aab92
```

**Comment by 9607835** [comment]
@karalabe which version?

this version works perfect:
> $ geth version
> Geth
> Version: 1.7.3-stable
> Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
> Architecture: amd64
> Protocol Versions: [63 62]
> Network Id: 1
> Go Version: go1.9
> Operating System: windows
> GOPATH=
> GOROOT=c:\go`

yet this version doesn't have init:
> $ geth version
> Geth
> Version: source
> Protocol Versions: [63 62]
> Network Id: 1
> Go Version: go1.10.3
> Go OS: linux
> Go Arch: amd64
> Machine ID: e845e5aa
> GOPATH=
> GOROOT=/usr/local/go




I don't think it matters, but I'm doing it from a docker build script:

> [...]
> Step 4/13 : RUN go get -v github.com/ethereumproject/go-ethereum/...
>  ---> Running in ee89de808fa3
> github.com/ethereumproject/go-ethereum (download)
> github.com/ethereumproject/go-ethereum/vendor/github.com/boltdb/bolt
> github.com/ethereumproject/go-ethereum/vendor/github.com/denisbrodbeck/machineid
> github.com/ethereumproject/go-ethereum/common
> github.com/ethereumproject/go-ethereum/crypto/randentropy
> github.com/ethereumproject/go-ethereum/crypto/secp256k1
> github.com/ethereumproject/go-ethereum/crypto/ecies
> [...]
> Removing intermediate container ee89de808fa3
>  ---> 9ae8b9cf73ca
> Step 5/13 : RUN go install github.com/ethereumproject/go-ethereum/cmd/...
>  ---> Running in 55ceaa9d31d5
> Removing intermediate container 55ceaa9d31d5
>  ---> 6149344455eb
> Step 6/13 : FROM alpine:latest
>  ---> 11cd0b38bc3c
> Step 7/13 : RUN apk add --no-cache ca-certificates
>  ---> Running in 9f04ae31a38b
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
> (1/1) Installing ca-certificates (20171114-r3)
> Executing busybox-1.28.4-r0.trigger
> Executing ca-certificates-20171114-r3.trigger
> OK: 5 MiB in 14 packages
> Removing intermediate container 9f04ae31a38b
>  ---> e36d87f9c5e8
> Step 8/13 : COPY --from=builder /go/bin/geth /usr/local/bin/
>  ---> 877726290426
> Step 9/13 : RUN mkdir /ethereum
>  ---> Running in 33d6f09a67f5
> Removing intermediate container 33d6f09a67f5
>  ---> 9a7ac6838afe
> Step 10/13 : RUN geth version
>  ---> Running in b57aa77765ee
> Geth
> Version: source
> Protocol Versions: [63 62]
> Network Id: 1
> Go Version: go1.10.3
> Go OS: linux
> Go Arch: amd64
> Machine ID: b57aa777
> GOPATH=
> GOROOT=/usr/local/go
> Removing intermediate container b57aa77765ee
>  ---> 043d408c94d8
> Step 11/13 : RUN geth --datadir="/ethereum" init /go-ethereum/genesis.json
>  ---> Running in f0091b7c682b
> Invalid command: "init". Please find `geth` usage below.
> NAME:
>    geth - the go-ethereum command line interface
> 
> USAGE:
>    geth [options] <command> [command options] [arguments...]
> 
> VERSION:
>    source
> [...]

**Comment by karalabe** [comment]
Your URLs are ethereum classic, not this project. If you want Ethereum,
please fix your sources. If you want ETC, you'll need to debug your issue
with them.
