### ISSUE TITLE
nil pointer error

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [ethereum/go-ethereum#17306]
We check whether `client` is nil at line 88, but before this ,we use it at line 85.

https://github.com/ethereum/go-ethereum/blob/16eaf2b158ca28b0b4aa48cfb400a7cf8ed70234/cmd/puppeth/wizard_netstats.go#L88
https://github.com/ethereum/go-ethereum/blob/16eaf2b158ca28b0b4aa48cfb400a7cf8ed70234/cmd/puppeth/wizard_netstats.go#L85

**Comment by 360CodeSafe** [comment]
More issue:
https://github.com/ethereum/go-ethereum/blob/16eaf2b158ca28b0b4aa48cfb400a7cf8ed70234/core/tx_pool.go#L400

**Comment by karalabe** [comment]
Thanks for these. The first issue is fixed by https://github.com/ethereum/go-ethereum/pull/17412.
