### ISSUE TITLE
ethereum-swam clobbers file in another deb package without noting conflict in deb control

### ISSUE THREAD

**Issue by kortschak** [ethereum/go-ethereum#17305]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `0.3.1+build14601+xenial`
OS & Version: Linux/OSX Ubuntu

#### Expected behaviour

Clean upgrade without clobbering another package's files.

#### Actual behaviour

```
(Reading database ... 649384 files and directories currently installed.)
Preparing to unpack .../ethereum-swarm_0.3.1+build14601+xenial_amd64.deb ...
Unpacking ethereum-swarm (0.3.1+build14601+xenial) ...
dpkg: error processing archive /var/cache/apt/archives/ethereum-swarm_0.3.1+build14601+xenial_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/swarm', which is also in package swarm 2.1.6-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/ethereum-swarm_0.3.1+build14601+xenial_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

#### Steps to reproduce the behaviour

1. Have Ubuntu swarm package installed.
2. Have ppa.launchpad.net/ethereum ethereum package installed.
3. Attempt to apt upgrade system.

#### Backtrace

````
Not relevant.
````

**Comment by kortschak** [comment]
Removing ethereum and swarm with `apt-get remove`, then making a decision about which you want and installing that is safer. This issue is not about the fact that the ethereum-swarm deb should note the conflict (or even move the bin to somewhere else that does not conflict given that swarm has existed previously).

**Comment by nonsense** [comment]
@kortschak previously `swarm` package was being installed as part of `ethereum`, but it has nothing to do with `ethereum`. You are right that we should add it as a conflict to `ethereum-swarm`.

The safest thing to do now is to `apt-get purge swarm`, provided you are actually not using the `swarm - robust and fast clustering method for amplicon-based studies` package.

Additional discussion at: https://github.com/ethereum/go-ethereum/issues/17295

**Comment by kortschak** [comment]
Unfortunately, as a bioinformatician, so swarm is something I might actually use. Fortunately, I don't.
