### ISSUE TITLE
Enable 0 gasprice transaction to be mined by other node

### ISSUE THREAD

**Issue by eosclassicteam** [ethereum/go-ethereum#17316]
Currently go-ethereum blocks 0 gasprice transaction to be saved on txpool and it is different compared with parity node.

( Here is my edit to enable 0 gasprice transactions to be sended and mined by pool node on other chain when the block is empty https://github.com/eosclassic/eosclassic/commit/90af9e7a6a6e9d8d5b998f7cdaabb8e391336cb5 )

I would like to suggest enabling 0 gasprice transaction to be accepted by default, we can mine the low fee transaction when the block is empty enough.

**Comment by holiman** [comment]
I'm against enabling zero-price txs. I'd prefer to close this ticket with 'works as expected'

**Comment by karalabe** [comment]
0 gas price transactions would result in network DoS attacks since it's free to inject arbitrary transactions and propagate them through the network. We will not support them.
