### ISSUE TITLE
Flag for option to choose web3 1.0 beta or 0.20 state

### ISSUE THREAD

**Issue by pierreneter** [ethereum/go-ethereum#17330]
#### System information

Geth version: 1.8.13
OS & Version: macOS
Commit hash: 

#### Expected behaviour

Default is stable 0.20 web3, switch to beta with:

```
geth --web3version=beta
```

#### Actual behaviour

Can't switch to web3 beta.

#### Steps to reproduce the behaviour

N/A

**Comment by karalabe** [comment]
If you'd like to use web3 1.0, please do so from outside of Geth. That version is not compatible with the way the console works in general (blocking calls) and isn't really useful as such. The console is meant as an easy way to quickly check things or call some methods. It's not meant as a full on dapp environment.
