### ISSUE TITLE
Add batch tx processing ability.Verify signature once,process many.

### ISSUE THREAD

**Issue by james-ray** [ethereum/go-ethereum#17331]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Now We can use the sendTransaction&sendRawTransaction to send Message to the peer.
Should we have the `sendTransactions` or `sendRawTransactions`,for which we should create a new transaction type(now we tentatively call it IntergratedTx)  thus a IntergratedTx can include more than one normal tx thus the peer will verify the signature just once to increase the throughput?

#### Backtrace

````
[backtrace]
````

**Comment by james-ray** [comment]
still return multiple txHashes, for example,if a user request 10 txs,first 5 passed verification,last 5 failed because of not enough fund, just return him a result array, first 5 has txHash,last 5 each has fail reason.

**Comment by karalabe** [comment]
I don't really see how this would work. Consensus wise, each transaction must be signed. It doesn't matter how you transmit the transactions, at the end of the day only the individual signatures count, not some collating signature. As such, I don't really see what the advantage would be. I however do see it as a DoS attack if we don't verify the individual signatures.

**Comment by james-ray** [comment]
@karalabe I mean,the new intergratedTx type has a member txs [] *Transaction . So we can intergrate n transaction in one request,it can save network transmition and geth only needs to verify the signature once for the n txs.

**Comment by karalabe** [comment]
That requires a hard fork, doesn't it?

**Comment by james-ray** [comment]
Yeah,I believe so.  Our scenario is: we use ethermint as an abci app to implement ethereum function with tendermint doing the consensus. We can reach approximately 3 or 4 seconds a block (under 1500 threads sending transactions, only 4 consensus nodes.If adding consensus node, the performance will decline)  So we are wondering how we can pack more txs in one block to improve the performance.

Maybe we can add the code as a feature branch?

A most easy way is : just send n txs in a request, some nodes implement a new grpc interface to handle the request. Still one tx with one signature, the only advantage is saving the network transfering.

Still I think the scenario depends on different business logic , that is : is there any nesissaritiy an account needs to quickly send out lots of transactions? That is a bit like a batch processing scenario.
