### ISSUE TITLE
Access debug_traceTransaction via ethclient.go

### ISSUE THREAD

**Issue by jmooo** [ethereum/go-ethereum#17341]
Now that geth has convenient tracing functions like [debug_traceTransaction](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_tracetransaction) is it possible to access those via [ethclient.go](https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go)?

I believe that is what tickets like #15569 are looking for

**Comment by karalabe** [comment]
No, and I don't think there will be. Tracing is a very client specific custom debugging thing. It's not really something that you'd expect to be available when connecting to a random node. It would be just a lot of effort to try to maintain Go APIs above the various tracers. You can do a raw RPC query and process the results yourself if you have a unique use case that needs it.

**Comment by ductrinhhuu** [comment]
@karalabe so do we have any method to call debug_traceTransaction from go?
