### ISSUE TITLE
why rlpdump output wrong nonce?

### ISSUE THREAD

**Issue by passionofvc** [ethereum/go-ethereum#17344]
Hi there,
rlpdump  print incorrect 0 nonce.

#### System information
rlpdump compile from master 
build from [make all]

#### Expected behaviour
 "30"

#### Actual behaviour
 "0"

#### Steps to reproduce the behaviour
```
$ rlpdump  -hex 0xf85930850df8475800830f42408088767f8e6d9fb88800801ca01236ebcc583029f7726a581b14deda4d86093fc1ed9f76fc04e8e5350b57290da04a9c51f53942b5f16f8ab1270c0c4d4522f15d84a922bbf030c789dfee5d1cb9
[
  "0",               //this wrong nonce,does it should be"30"
  0df8475800,
  0f4240,
  "",
  767f8e6d9fb88800,
  "",
  1c,
  1236ebcc583029f7726a581b14deda4d86093fc1ed9f76fc04e8e5350b57290d,
  4a9c51f53942b5f16f8ab1270c0c4d4522f15d84a922bbf030c789dfee5d1cb9,
]
```
same thing print by ethereumjs-tx
```

const EthereumTx = require('ethereumjs-tx');
 const raw = '0xf85930850df8475800830f42408088767f8e6d9fb88800801ca01236ebcc583029f7726a581b14deda4d86093fc1ed9f76fc04e8e5350b57290da04a9c51f53942b5f16f8ab1270c0c4d4522f15d84a922bbf030c789dfee5d1cb9';
 var tx = new EthereumTx(raw);
 console.log(tx.nonce)
 console.log(tx.gasPrice)
 console.log(tx.gasLimit)
 console.log(tx.value)
 console.log(tx.getSenderAddress().toString('hex'))

<Buffer 30>
<Buffer 0d f8 47 58 00>
<Buffer 0f 42 40>
<Buffer 76 7f 8e 6d 9f b8 88 00>

```

**Comment by ligi** [comment]
I can confirm - just decoded with KEthereum - the nonce (and hence the first RLPElement in the RLPList) should be 0x30. Also getting 0 with rlpdump

**Comment by holiman** [comment]
It's not wrong, just unintuitive. 
It returns the ASCII string `"0"`. The character `0x30` is `"0"`.

**Comment by holiman** [comment]
Here's the culprit: https://github.com/ethereum/go-ethereum/blob/master/cmd/rlpdump/main.go#L104

**Comment by holiman** [comment]
And here's how to get around it: 
```
$ ./rlpdump  -hex 0xf85930850df8475800830f42408088767f8e6d9fb88800801ca01236ebcc583029f7726a581b14deda4d86093fc1ed9f76fc04e8e5350b57290da04a9c51f53942b5f16f8ab1270c0c4d4522f15d84a922bbf030c789dfee5d1cb9 -noascii
[
  30,
  0df8475800,
  0f4240,
  "",
  767f8e6d9fb88800,
  "",
  1c,
  1236ebcc583029f7726a581b14deda4d86093fc1ed9f76fc04e8e5350b57290d,
  4a9c51f53942b5f16f8ab1270c0c4d4522f15d84a922bbf030c789dfee5d1cb9,
]
```
I'll close this, but please reopen if you think this behaviour should change.

**Comment by ligi** [comment]
ouch - good catch - yea the "" should have been the indicator - but was also not seeing this ..
perhaps inverting the default would be a way to prevent this UX issue - so people have to activate ascii - then this should not be an issue anymore

**Comment by holiman** [comment]
I didn't see it either, not until I stepped through the code in the debugger :) I wouldn't mind defaulting to non-ascii personally
