### ISSUE TITLE
`eth_sendRawTransaction` timeout

### ISSUE THREAD

**Issue by kazaff** [ethereum/go-ethereum#17359]
Hi there,

When I call the `eth_sendRawTransaction` RPC method, it returned timeout frequently(Sometimes the caller waits for several minutes...).

I have no idea, please help me.

**Comment by karalabe** [comment]
You'd need to provide a lot more information, preferably a way for us to reproduce the issue.

**Comment by kazaff** [comment]
@karalabe Thanks and sorry for the less detail~
The truth is that i DO NOT know what information i need to post to explain this issue.
Sometimes the RPC call is very fast and sometimes not, I had doubted the configuration or network at the very started, but both seem nothing wrong.

Today this issue was disappeared suddenly, like it suddenly happened in few days ago~~
And i do nothing work yet, so sad.
