### ISSUE TITLE
Password with Empty " " string no longer works

### ISSUE THREAD

**Issue by jonisjon** [ethereum/go-ethereum#1736]
Originally this issue came up in 1.0.2 and then was fixed - it has once again broke again in the newest version of 1.1.0 - as many accounts have already been created with an empty password those accounts cannot be accessed what-so-ever until the issue is fixed again.

**Comment by maran** [comment]
I believe #1739 should fix this. Feel free to try it and report back.

**Comment by karalabe** [comment]
I'll consider this issue solved using latest develop then. If not, please reopen it.
