### ISSUE TITLE
My account has been flagged by @ethereum

### ISSUE THREAD

**Issue by losesw** [ethereum/go-ethereum#17377]
Hi there,

My account has been flagged by @ethereum, but I don't know what I did wrong.

The following is the operation record before I was flagged:

1. I found a typographical error when viewing the wiki of Etherum's JSON-RPC interface (URL: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newpendingtransactionfilter).

2. By looking at revisions I found that Nathapon8899 changed "edit mode" to cause this error (Nathapon8899's home page has become 404).

3. I restored "edit mode" and the page is displayed normally.

4. My account has been flaggedby @ethereum.

The above process can be viewed through revisions. (https://github.com/ethereum/wiki/wiki/JSON-RPC/_history)

If my behavior violates the @ethereum agreement, please let me know and I will apologize for it.

Thanks.

**Comment by karalabe** [comment]
No idea really, I'd guess it's some automated GitHub bot detector. We surely don't have anyone policing the wikis, not do we really have a means to influence user statuses. Perhaps reach out to GitHub support and ask them if something's wrong.
