### ISSUE TITLE
wallet 0.11.1 overrides geth 1.8.13

### ISSUE THREAD

**Issue by smartwombat** [ethereum/go-ethereum#17372]
#### System information

Geth version: 1.8.13
OS & Version: windows 10 v1803 build 17134,165

#### Expected behaviour
If geth is already installed an in the OS path, the wallet shoudl use it and not install its own version.

#### Actual behaviour
Installing Windows 64 bit wallet 0.11.1 uses its own geth installation unpacked from archive.

#### Steps to reproduce the behaviour
Install wallet Windows 64 bit 0.11.1
note C:\Users\PAul Maskens\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked geth.exe filesize 37,503KB

Install geth 1.8.13
note path length error message on install
Add C:\Program Files\Geth to system path
note  filesize 38.372KB

Copy geth.exe from C:\Program Files\Geth to C:\Users\PAul Maskens\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked.

Click on wallet icon in start menu.
1) delay before window appears
2) spinning blue circle after window appears
3) when displaying content, the geth.exe file has been overwritten

#### attempted migigations
1) replace geth.exe 1.8.11 with a link to geth.exe 1.8.13
Fails, results is both a link geth.exe and program file geth.exe exist in the ...\unpacked folder.

2) replace geth.exe 1.8.11 with geth.exe 1.8.13, make read-only
Fails, ...\unpacked\geth.exe is overwritten with 1.8.11

3) delete archive and copy geth.exe 1.8.13
Fails, ..\binaries\Geth\archive.zip is recreated, ...\unpacked\geth.exe is overwritten

**Comment by ligi** [comment]
I think this issue is better filed in the mist project

**Comment by smartwombat** [comment]
Filed there also.
Found hard-coded version test according to error message from Mist.
