### ISSUE TITLE
Geth Full Node CPU Usage >100% + dropping peer

### ISSUE THREAD

**Issue by jordimorris** [ethereum/go-ethereum#17378]
Hi there,

geth as Full Node is running with a CPU usage over 100%. It can barely keep up with the synchronisation and as soon as it catches up then dropping peers occur. The node tends to be behind the latest block or barely holds synchronisation for a while.  

This issue is very similar to the one experimented in summer 2016 where the network was constantly under successful attacks and it was a nightmare to keep up the node updated. 

#### System information

Geth version: v1.8.13-stable
OS & Version: OSX High Sierra
CPU Core i7@2.7GHz + Turboboost

#### Expected behaviour
Geth syncs up with the network
Geth to use less than 80% of CPU
After a peer is dropped geth finds others and doesn't stop sync up

#### Actual behaviour

When is not sync up I understand it takes higher CPU usage to process all the blocks. 
As soon as it's sync up it gets in trouble with peers, sync failed, dropped peer and head headers broke chain. 
Geth node tends to be slightly behind the latest block. 
Geth node drops peers and it takes long time to resume synchronisation again

Sync Failed:
Synchronisation failed, retrying         err="block download canceled (requested)"
WARN [08-11|14:31:05.526] Synchronisation failed, retrying         err="block download canceled (requested)"
WARN [08-11|14:31:36.637] Synchronisation failed, dropping peer    peer=02e8dea482d9528f err=timeout

#### Steps to reproduce the behaviour
geth --rpc --cache=2058

**Comment by jordimorris** [comment]
It is back to normal:

WARN [08-11|15:42:42.105] Synchronisation failed, dropping peer    peer=3c81f6064e6399a6 err=timeout
INFO [08-11|15:42:47.076] Imported new chain segment               blocks=1  txs=89   mgas=7.979  elapsed=177.537ms mgasps=44.941 number=6128532 hash=cb54ef…24a119 cache=535.15mB

Eventually, when there's a dropping peer event, geth doesn't stop syncing and just keeps up importing segments and processing blocks. In recent days this wasn't happening and the node got stuck every time geth was synced. 

On a side note, also I experienced that Metamask wasn't even broadcasting some of the transactions, independently of the Gas price. 

**Conclusion:**

CPU usage is back to 20-80%, occasionally >100% 
drop peer user and not finding peers has stopped, geth is sync up all the time

**Comment by jordimorris** [comment]
it is back to slow performance and dropping peers.

searching into github there are plenty of issues opened under the same circumstances. 

Why is this a recurring issue? I understand ethereum network is under attack constantly but why the same problem comes over ?

**Comment by liuhuanhui** [comment]
Buddy, my side is also 8 core 16g centos configuration, start synchronization and rpc, cpu takes up more than 80%, may I solve it?

**Comment by liuhuanhui** [comment]
The same question

**Comment by technologiespro** [comment]
The same question

**Comment by jordimorris** [comment]
The issue occurred frequently and gave up after finding no solution to this topic.


Alternative:
Mounted a dAppNode and now I can run parity, rinkeby, kovan and geth with 0% impact on the laptop I'm working with and connecting through a VPN.

Highly recommended !

**Comment by holiman** [comment]
The original ticket was for ` v1.8.13-stable`. We did a bunch of improvements for 1.9 (see https://blog.ethereum.org/2019/07/10/geth-v1-9-0/ ), and have been steadily improving geth since. 
As this ticket is pretty stale, I think it's better to discuss how geth currently works (or not) ina new ticket.
