### ISSUE TITLE
Makefile:17: recipe for target 'geth' failed

### ISSUE THREAD

**Issue by unmesh2892** [ethereum/go-ethereum#17373]
Hi,

I am having issues with installing meth on my Rasberry Pi.
#### System information

This is my complete log:
build/env.sh go install -v -ldflags '-X main.gitCommit c541b38fb36587d23c60f5e2f2b9b3c8700ec489' ./cmd/geth
github.com/codegangsta/cli
github.com/ethereum/go-ethereum/rlp
github.com/ethereum/go-ethereum/crypto/ecies
github.com/ethereum/go-ethereum/crypto/sha3
github.com/ethereum/go-ethereum/crypto/randentropy
github.com/ethereum/go-ethereum/crypto/secp256k1
github.com/pborman/uuid
golang.org/x/crypto/pbkdf2
golang.org/x/crypto/ripemd160
golang.org/x/crypto/scrypt
github.com/ethereum/go-ethereum/common
github.com/ethereum/go-ethereum/logger/glog
github.com/ethereum/go-ethereum/params
github.com/hashicorp/golang-lru
github.com/rcrowley/go-metrics
github.com/syndtr/goleveldb/leveldb/util
github.com/syndtr/goleveldb/leveldb/cache
github.com/syndtr/goleveldb/leveldb/comparer
github.com/syndtr/goleveldb/leveldb/storage
github.com/ethereum/go-ethereum/logger
github.com/syndtr/goleveldb/leveldb/filter
github.com/syndtr/goleveldb/leveldb/opt
github.com/syndtr/gosnappy/snappy
gopkg.in/karalabe/cookiejar.v2/collections/prque
github.com/syndtr/goleveldb/leveldb/errors
github.com/syndtr/goleveldb/leveldb/iterator
github.com/syndtr/goleveldb/leveldb/journal
github.com/ethereum/go-ethereum/event
github.com/syndtr/goleveldb/leveldb/memdb
github.com/syndtr/goleveldb/leveldb/table
gopkg.in/fatih/set.v0
github.com/huin/goupnp/httpu
github.com/huin/goupnp/scpd
github.com/ethereum/go-ethereum/metrics
github.com/huin/goupnp/soap
github.com/syndtr/goleveldb/leveldb
github.com/huin/goupnp/ssdp
golang.org/x/net/html/atom
golang.org/x/net/html
golang.org/x/text/transform
golang.org/x/text/encoding
golang.org/x/text/encoding/internal/identifier
golang.org/x/text/encoding/internal
golang.org/x/text/encoding/charmap
golang.org/x/text/encoding/japanese
golang.org/x/text/encoding/korean
github.com/ethereum/go-ethereum/ethdb
golang.org/x/text/encoding/simplifiedchinese
golang.org/x/text/encoding/traditionalchinese
golang.org/x/text/encoding/unicode
github.com/jackpal/go-nat-pmp
github.com/ethereum/go-ethereum/event/filter
github.com/robertkrimen/otto/file
github.com/robertkrimen/otto/token
github.com/robertkrimen/otto/ast
github.com/robertkrimen/otto/dbg
github.com/robertkrimen/otto/parser
# github.com/ethereum/go-ethereum/crypto/secp256k1
malformed DWARF TagVariable entry
github.com/robertkrimen/otto/registry
github.com/ethereum/go-ethereum/rpc/shared
github.com/rs/cors
github.com/ethereum/go-ethereum/rpc/codec
github.com/peterh/liner
github.com/mattn/go-isatty
github.com/shiena/ansicolor
github.com/fatih/color
github.com/mattn/go-runewidth
github.com/nsf/termbox-go
github.com/robertkrimen/otto
golang.org/x/net/html/charset
github.com/gizak/termui
github.com/huin/goupnp
github.com/huin/goupnp/dcps/internetgateway1
github.com/huin/goupnp/dcps/internetgateway2
github.com/ethereum/go-ethereum/p2p/nat
github.com/ethereum/go-ethereum/jsre
Makefile:17: recipe for target 'geth' failed
make: *** [geth] Error 2

Could anyone help as what the issue is?

**Comment by jsvisa** [comment]
@unmesh2892 Which go version are you using?

**Comment by jsvisa** [comment]
Sorry, I’m meaning the Golang version

unmesh2892 <notifications@github.com> 于2018年8月10日周五 上午10:06写道：

**Comment by unmesh2892** [comment]
GO version 1.4

**Comment by karalabe** [comment]
Please use Go 1.9 or above.

**Comment by AdB9** [comment]
I'm using Go 1.10.1, still facing the same error.

**Comment by MariusVanDerWijden** [comment]
Please use Go 1.13 or above! We updated the required version in v.1.9.15
https://github.com/ethereum/go-ethereum/releases/tag/v1.9.15
