### ISSUE TITLE
Ledger HD Derivation Path No Longer Valid

### ISSUE THREAD

**Issue by reedwind** [ethereum/go-ethereum#17387]
The [derivation path](https://github.com/ethereum/go-ethereum/blob/ef0edc6e32d98d2fca54076f38cb317f43704900/accounts/hd.go#L40) currently specified for Ledger devices is no longer valid since the latest Ledger clients are now [BIP 44 compliant](https://github.com/LedgerHQ/ledger-live-desktop/blob/0c03b66b31d5f78fabbf395cb757b0bcc798e4fd/src/helpers/derivations.js#L28). This means as of a month ago funds on Ledger's new client are no longer accessible to go-ethereum.

To fix the [custom derivation](https://github.com/ethereum/go-ethereum/blob/ef0edc6e32d98d2fca54076f38cb317f43704900/accounts/hd.go#L40) can be removed along with it's [check](https://github.com/ethereum/go-ethereum/blob/021d6fbbbbdfe295dbb3619f8ec3fc8662c1e26a/cmd/geth/main.go#L313) which will finally put Ledger devices back into compatibility with all other BIP 44 standard wallets.

**Comment by karalabe** [comment]
Well great, and what happens with funds on old devices?

**Comment by reedwind** [comment]
When users update to the new ledger software the old accounts show up as legacy accounts giving them an opportunity to move them onto the correct supported path. For those using go-ethereum exclusively simply hide the legacy derivation path behind a flag, but users should be encouraged to move their funds to the supported paths going forward.
