### ISSUE TITLE
How to upgrade geth version , without data disappear?

### ISSUE THREAD

**Issue by dksuper** [ethereum/go-ethereum#17396]
Hi there,

Recently , I want chage my 1.8.7 version geth node , to latest version , but the main point is that I want keep the all blockchain history , so the question is how to upgrade geth version , without data disappear?

#### System information

Geth version: `1.8.7`
OS & Version: ubuntu

**Comment by bizlevel** [comment]
Just rewrite binary file, i do it several times.
stop service, update binary, restart service, done!)

**Comment by dksuper** [comment]
@bizlevel Thank you for reply! 
But i have several question:
1. should I change the genesis.json , when the version that have different fromat genesis.json ? 
2. does it have any effect when you rewrite binary file?

**Comment by bizlevel** [comment]
1 no
2 i hope))

**Comment by karalabe** [comment]
@dksuper We have't changed the genesis format in 3 years, so no worries there. You should be able to upgrade without any issues, just cleanly shut down the previous instance, update and restart it.

**Comment by dksuper** [comment]
@karalabe OK I got it, thanks a lot :)!
