### ISSUE TITLE
Dangerous to Run Public Txpool API?

### ISSUE THREAD

**Issue by mykolasmith** [ethereum/go-ethereum#17391]
Hi,

We would like to use the txpool API in order to check pending status of orders submitted through our Geth cluster. I have a couple of questions about txpool:

1) Are there any inherent dangers of running a public Geth node w/ the txpool RPC API enabled?
2) If we submit a transaction to a node and txpool is enabled, does information about that transaction become instantly available to that node? What about other nodes? How long would it take before other nodes became aware of the transaction?
3) Is there any performance overhead to having the txpool API enabled (other than I/O when querying), or does it simply allow access to existing data structures already present in Geth?

I searched and couldn't find detailed documentation about the Txpool. Please feel free to drop any links that might be helpful in gaining a deeper understanding of this feature. Thanks!

**Comment by karalabe** [comment]
The `txpool` API is only an accessor to the local transaction pool within your Geth instance. Submitting a transaction does not change whether you enable this API or not, it's just an exploratory endpoint

In theory there are no dangers of exposing this API. In practice the Geth APIs are not throttled or rate limited, so open RPC access can most probably DOS the node simply by constantly requesting data with high IO or CPU overhead.

Any particular reason though you'd like to expose it publicly?

**Comment by mykolasmith** [comment]
@karalabe We expose it publicly to service our Dapp (airswap.io) frontend, which needs to query nodes for pending transaction status, transaction history, balances, etc. Thanks for answering my questions!
