### ISSUE TITLE
QUESTION: How config node for Fullest and Fast sync blockchain to memory 512G (NO SSD)

### ISSUE THREAD

**Issue by bizlevel** [ethereum/go-ethereum#17395]
Sync it is Pain! Ни в обном блокчейне нет таких болей!)
If i have a lot memory, and i can use for RAM disk and it is a Best IO.
How to configure node to get maximum performance for:
CPU 32 core 2x E5-26XX
MEM 512Gb (for today whole blockchain is no more than 200Gb)
NET 1000Mb (how many connections need to get full bandwidth?)

How fast it will be?
Any one have any tests for sync with different host configuration?

**Comment by drakmail** [comment]
Use tmpfs if you use linux - just mount it to geth folder

**Comment by bizlevel** [comment]
Yes, i know it. But need optimized config for this.  Because no cache, need fulest speed, etc.
