### ISSUE TITLE
Get transaction hash

### ISSUE THREAD

**Issue by KaushikTechcronus** [ethereum/go-ethereum#17398]
Hello,

I signed transaction successfully using Geth.aar library.

Now I want to generate transaction hash using Geth.aar.

Please help who knows answer.

Thanks.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

That said - please post your stackoverflow link here afterwards so I can answer the question

**Comment by ligi** [comment]
Answered on Etherscan - happy coding!

**Comment by KaushikTechcronus** [comment]
Hello,
I commented on your answer.
Please review it and help me further to send transaction.
Thanks.

**Comment by ligi** [comment]
seen and answered - let's just continue there ;-)

**Comment by KaushikTechcronus** [comment]
Hello,
Thank you so much ligi. With your help my transaction is working perfectly
Thanks.

**Comment by KaushikTechcronus** [comment]
Hello ligi,
Please find below question.
https://bitcoin.stackexchange.com/questions/81815/generate-litecoin-address
Thanks.

**Comment by ligi** [comment]
Sorry - but this is out of scope - I do not use bitcoin/litecoin

**Comment by KaushikTechcronus** [comment]
Okay thanks.
