### ISSUE TITLE
Unable to retrieve outgoing contracts Ether Send Txs via API (feature)

### ISSUE THREAD

**Issue by mtbitcoin** [ethereum/go-ethereum#1740]
There does not appear to be a straight forward way to get Ether send "txs" from a contract.  For example the contract http://etherscan.io/address/0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae has disbursed ETH payments but tracking the outgoing disbursements are tricky.

There are also similar request for this functionality https://www.reddit.com/r/ethereum/comments/3ih313/understanding_payments_sent_by_invoked_contracts/

Would be helpful if perhaps https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt could be expanded to also include an array of transactions/calls from the contract. For example
from, to, value in a contractTx array

**Comment by maran** [comment]
There are some discussions still on-going on this topic. The preferred way that is available right now is that the contracts themselves use the LOG functionality to keep track of outgoing transactions. I understand that this might not be a solution for you right now. We might have a better solution for this in the future.

**Comment by obscuren** [comment]
This is not something that will change anytime soon (if at all). Add functionality to ethereum by programming the contract rather they expansion of the protocol or client them self. 

As @maran already correctly stated is that you could/should use the `LOGn` opcode (`event`s in solidity) to store certain events about your program's state or actions.

Ethereum only stores that which is part of the conensus protocol and no additional "user info". It's all up to the contract to store (and pay for!) any additional information it wishes to store and thus making it part of the consensus protocol (all clients must agree on the data and events).
