### ISSUE TITLE
--verbosity 0 not respected

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/go-ethereum#1741]
Keep getting messages like 

    I0828 10:35:35.761173    4126 fdtrack.go:109] fd usage 60/256, tracked 46 [ipc:1 leveldb:31 p2p:13 rpc:1]

 every couple seconds in my geth terminal even with `--verbosity 0`

    > geth version
    Geth
    Version: 1.0.2
    Protocol Versions: [61 60]
    Network Id: 1
    Go Version: go1.5
    OS: darwin
    GOPATH=
    GOROOT=/usr/local/Cellar/go/1.5/libexec

    >system_profiler SPSoftwareDataType
    Software:

     System Software Overview:

      System Version: OS X 10.10.4 (14E46)
      Kernel Version: Darwin 14.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Aakil’s Mac mini
      User Name: Aakil Fernandes (aakilfernandes)
      Secure Virtual Memory: Enabled
      Time since boot: 1 day2:54

**Comment by fjl** [comment]
The message has been removed in geth 1.1.0.

**Comment by aakilfernandes** [comment]
Upgrading now. Will see if it fixes. Thanks

**Comment by aakilfernandes** [comment]
Confirmed 🙏
