### ISSUE TITLE
" Fatal : failed to read genesis file: open genesis.json: The system cannot find the file specified. "

### ISSUE THREAD

**Issue by joohyeung** [ethereum/go-ethereum#17418]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`    1.8
OS & Version: Windows/Linux/OSX    windows10
Commit hash : (if `develop`)

#### Actual behaviour
![geensis](https://user-images.githubusercontent.com/41462311/44217719-164a8300-a1b3-11e8-8582-30e3737c02eb.png)

I created a "genesis.json" file and I want to create a Genesis block from it.
The "genesis.json" file is also placed in the directory 
where the information will be stored when the idler is running.

but When I wrote the code

" Fatal : failed to read genesis file: open genesis.json: The system cannot find the file specified. "

This error has occurred

Please tell me how to fix the error.

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
The path isn't within the datadir, it's relative to where you're starting geth from, it's a plain path from your working directory. Or give it a full path if that's easier to you.

**Comment by prographo** [comment]
He's just going off your documentation. https://www.ethereum.org/cli
