### ISSUE TITLE
Geth 1.8 abigen, events not being emitted

### ISSUE THREAD

**Issue by kc1116** [ethereum/go-ethereum#17433]
Hi, I have been running geth on my local machine and consuming contract events with abigen generated code. Everything was working fine for a few days up until today. Today no matter how many times I restart Geth, remove the datadir or anything none of the contract events are ever being emitted. This is weird because I havent changed anything in the smart contract. Just starting and stopping geth.

#### System information

Version: 1.8.13-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: darwin

#### Expected behaviour
Transfer from standard ERC 20 token contract, should emit event

#### Actual behaviour
No events emitted at all

Here my event subscription code
````
sub, err := t.Subscriber.PropsClient.Token.WatchTransfer(watchOps, sink, []common.Address{}, []common.Address{})
	if err != nil {
		return err
	}

	//err = t.CheckRecover(currentBlock)
	//if err != nil {
	//	return err
	//}

	go t.MonitorBlockNumbers(currentBlock)

	for {
		select {
		case err := <-sub.Err():
			if err != nil {
				logger.Error(fmt.Errorf("error on transfer event subscriber (%v)", err)).Log()
				t.Restart(currentBlock)
				return nil
			}
		case transfer := <-sink:
			t.PublishTransfer(transfer)
			t.Subscriber.BlockNumberMonitor <- transfer.Raw.BlockNumber
		}
	}
````

**Comment by karalabe** [comment]
Thanks for this report. We did some changes in the log filtering in the 1.8.13 release. We might have broken something. Will try to repro it.

**Comment by karalabe** [comment]
I've tried to repro it direclty via Geth, but that seems to work:

```go
package main

import (
	"context"
	"fmt"
	"math/big"

	ethereum "github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	client, err := ethclient.Dial("/home/karalabe/.ethereum/rinkeby/geth.ipc")
	if err != nil {
		panic(err)
	}
	defer client.Close()

	sink := make(chan types.Log, 16)

	sub, err := client.SubscribeFilterLogs(context.Background(), ethereum.FilterQuery{
		Addresses: []common.Address{common.HexToAddress("0x1539d8ac016df238f55abcbc25c22c3489fd157c")},
	}, sink)
	if err != nil {
		panic(err)
	}
	defer sub.Unsubscribe()

	fmt.Println("Filtering logs...")
	for log := range sink {
		fmt.Printf("%+v\n", log)
	}
}
```

Are you running this on the testnet perhaps? Could you share any code so I might repro?

**Comment by karalabe** [comment]
Are you sure `t.Subscriber.PropsClient.Token.WatchTransfer(watchOps, sink, []common.Address{}, []common.Address{})` is correct?

The last two arguments are empty, which would kind of maybe tell me that they won't match anything? What happens if you replace those with nil?
