### ISSUE TITLE
Can't create new keystore

### ISSUE THREAD

**Issue by emurmotol** [ethereum/go-ethereum#17445]
#### System information

Geth version: `1.8.13-stable`
Go version: `go1.10.3 linux/amd64`
OS & Version: ubuntu 18

#### Expected behaviour

No errors

#### Actual behaviour

Having an error:
```
duplicate symbol _cgoexp_ef3077570de2_secp256k1GoPanicIllegal (types 1 and 1) in gitlab.com/user/repo/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1 and /home/user/.cache/go-build/15/15c2f967f5c3267ed79b0de9e7be648b53651650777cc018df1d3b47bc595506-d(_go_.o)
```

#### Steps to reproduce the behaviour

Code:
```
...

ks := keystore.NewPlaintextKeyStore("/home/user/workspace/src/gitlab.com/user/repo/keystore")
account, err := ks.NewAccount("secret")

...
```

**Comment by karalabe** [comment]
Which version of Go?

**Comment by emurmotol** [comment]
@karalabe I updated the description.

I got it working now anyways. Just delete go-ethereum/ethereum package and re-run `dep ensure`

Thanks.
