### ISSUE TITLE
Block sealing failed when I use my genesis.json

### ISSUE THREAD

**Issue by pedromazala** [ethereum/go-ethereum#17443]
#### System information

Geth version: `Geth/v1.8.13-stable-225171a4/linux-amd64/go1.10.3`
OS & Version: linux-amd64/go1.10.3
Commit hash : (if `develop`)

#### Expected behaviour
It should starts miner after run `miner.start(5)` on my console

#### Actual behaviour
The minering process does not init. It prints a log like `WARN [MM-DD|HH:II:SS] Block sealing failed                     err=unauthorized`.

#### Steps to reproduce the behaviour

- Genesis file:
```
{
  "config": {
    "chainId": 500,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "byzantiumBlock": 4,
    "clique": {
      "period": 15,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x5a8efd25",
  "extraData": "0x00000000000000000000000000000000000000000000000000000000000000003590aca93338b0721966a8d0c96ebf2c4c87c5448cc5a1a0802db41db826c2fcb72423744338dcb00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "3590aca93338b0721966a8d0c96ebf2c4c87c544": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    },
    "8cc5a1a0802db41db826c2fcb72423744338dcb0": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```

- Creating node
```
docker run -it --rm --entrypoint sh --name geth -p 8545:8545 ethereum/client-go:stable
#inside container
geth init genesis.json
geth account new
geth --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain '*' --rpcapi personal,admin,db,eth,net,web3,miner,shh,txpool,debug --gasprice 0 --targetgaslimit 9999999
```

- Creating console
```
docker exec -it geth geth attach http://127.0.0.1:8545
personal.unlockAccount(eth.accounts[0])
miner.start(5)
```

#### Backtrace

````
INFO [08-19|01:07:40.894] Maximum peer count                       ETH=25 LES=0 total=25
INFO [08-19|01:07:40.911] Starting peer-to-peer node               instance=Geth/v1.8.13-stable-225171a4/linux-amd64/go1.10.3
INFO [08-19|01:07:40.912] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=768 handles=1024
INFO [08-19|01:07:40.972] Initialised chain configuration          config="{ChainID: 500 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: clique}"
INFO [08-19|01:07:40.972] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [08-19|01:07:40.982] Loaded most recent local header          number=0 hash=62f584…23ba54 td=1
INFO [08-19|01:07:40.982] Loaded most recent local full block      number=0 hash=62f584…23ba54 td=1
INFO [08-19|01:07:40.983] Loaded most recent local fast block      number=0 hash=62f584…23ba54 td=1
INFO [08-19|01:07:40.987] Loaded local transaction journal         transactions=0 dropped=0
INFO [08-19|01:07:40.991] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-19|01:07:40.997] Starting P2P networking 
INFO [08-19|01:07:43.195] UDP listener up                          self=enode://d9b44e3c40d11128db8413fc7929716a10cda60121e84d73b3a99542e6f60dfe9726ee9910271de11f54bf7684ce33f5e19e430f0e3d9e6c49a95bbc968945ce@[::]:30303
INFO [08-19|01:07:43.208] RLPx listener up                         self=enode://d9b44e3c40d11128db8413fc7929716a10cda60121e84d73b3a99542e6f60dfe9726ee9910271de11f54bf7684ce33f5e19e430f0e3d9e6c49a95bbc968945ce@[::]:30303
INFO [08-19|01:07:43.217] IPC endpoint opened                      url=/root/.ethereum/geth.ipc
INFO [08-19|01:07:43.219] HTTP endpoint opened                     url=http://0.0.0.0:8545      cors=* vhosts=localhost
WARN [08-19|01:07:43.220] ------------------------------------------------------------------- 
WARN [08-19|01:07:43.220] Referring to accounts by order in the keystore folder is dangerous! 
WARN [08-19|01:07:43.220] This functionality is deprecated and will be removed in the future! 
WARN [08-19|01:07:43.221] Please use explicit addresses! (can search via `geth account list`) 
WARN [08-19|01:07:43.221] ------------------------------------------------------------------- 
Unlocking account 1 | Attempt 1/3
Passphrase: 
INFO [08-19|01:07:48.047] Unlocked account                         address=0x2D54E56e885A900d2DA21f59e54720594FF4A48a

INFO [08-19|01:08:06.465] Etherbase automatically configured       address=0x55288d8cDA578efdf3FA95779CD20f023f175D3F
INFO [08-19|01:08:17.852] Transaction pool price threshold updated price=0
INFO [08-19|01:08:17.852] Starting mining operation 
INFO [08-19|01:08:17.853] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=255.7µs
WARN [08-19|01:08:17.853] Block sealing failed                     err=unauthorized

INFO [08-19|01:10:17.235] Transaction pool price threshold updated price=0
INFO [08-19|01:10:17.235] Starting mining operation 
INFO [08-19|01:10:17.236] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=504.9µs
WARN [08-19|01:10:17.236] Block sealing failed                     err=unauthorized
^CINFO [08-19|01:17:54.189] Got interrupt, shutting down... 
INFO [08-19|01:17:54.189] HTTP endpoint closed                     url=http://0.0.0.0:8545
INFO [08-19|01:17:54.225] IPC endpoint closed                      endpoint=/root/.ethereum/geth.ipc
INFO [08-19|01:17:54.225] Blockchain manager stopped 
INFO [08-19|01:17:54.225] Stopping Ethereum protocol 
INFO [08-19|01:17:54.225] Ethereum protocol stopped 
INFO [08-19|01:17:54.227] Transaction pool stopped 
INFO [08-19|01:17:54.250] Database closed                          database=/root/.ethereum/geth/chaindata
````

**Comment by nambrot** [comment]
Have you ever resolved this issue? What was the cause?

**Comment by vdamle** [comment]
`err=unauthorized` in a `clique/poa` consensus setup indicates that the member is not a Signer (because it does not have enough votes) and cannot cut blocks. You can check the current signer list on any member of the chain by running `clique.getSigners()` in geth. To make a node a signer, other members in the chain need to vote for it: `clique.propose(<node_id>, true)`. Once the member is voted in, you will no longer see the `err=unauthorized` error.

**Comment by nelaturuk** [comment]
I have setup a POA network with Clique consensus on azure. Due to some issue all the signer vms got deleted and we have no more signers and only normal geth nodes.

So i tried updating the geth nodes to signers. clique propose doesnt seem to work anyway i try.

Is there any procedure I have to follow in this kind of situation ? I see the same error mentioned above.

I have 3 nodes which are all geth nodes. And connected. I want to make all 3 of them signers.

Thank you.

**Comment by vdamle** [comment]
@nelaturuk  A node needs to be a signer to propose other signers. If you have lost all your signers, I guess the only option is to re-create the chain

**Comment by tomw1808** [comment]
Apologies upfront for potentially spamming a follow-up question on an already closed ticket, but I went through all of SO, all the issues here and that one person here from 2018 is the most related situation to my problem.

In my case, I'd like to do a dev-clone of a production environment without giving out the production signer keys.

I have access to a full chain. It's then like not having access to the signer keys anymore and needing the chain-data to migrate somehow to new signers.

Is there really absolutely no way to start an existing Clique chain with different signers without the original set of private keys? Is there potentially something I can do to prepare the export on the production environment? Maybe a one-liner chain-export and then re-import the chain, but without having access to the new keys on the production system or the production keys on the dev system?

I am trying to wrap my head around that for at least 2 days now, any help would be appreciated @vdamle @karalabe .

**Comment by tomw1808** [comment]
Really appreciate you getting back to me, the workflow is quite helpful. I will try to script that somehow - we're doing dev environments on demand from production (think of what vercel is doing as preview environments). Geth is the final boss to get that done. 

I had so much hope that re-initializing the data directory with a new genesis.json with new extraData will override the voting mechanism since the chain is offline and geth can happily modify any block data. 

Just theoretically, by going one level lower and actually writing new block data, how many blocks would someone need to add so that geth thinks everything is in order? Would that even work or would that just fall over because its not validating in the chain?

**Comment by tomw1808** [comment]
In case someone else comes across this post, a few things that might bring you forward...

My biggest concern was that rotating miners in geth is potentially not scriptable (or very hard). However geth has a scripting functionality via the JavaScript console. That means, as soon as geth is started, its possible to attach and load a script.

The script we wrote could look something like this: 

```
const newSigners = ["0x4d4cdf0e5a2dc72f74eaf8bacb82025998d5193c", "0x9fd7590558bf1fe9e8e607cea006093b68fc52d5"]

for (let round = 0; round <= 16; round++) {
    for (const signer of clique.getSigners()) {
        miner.stop()
        miner.setEtherbase(signer);
        miner.start(1) //will work or fail, who cares, do it 16 times and the miners should be rotated
        for (let waiter = 0; waiter < 10000000; waiter++) {
            //ugly way of waiting a second or so because I did not find a way to do async/await or for the mining thread to start
        }

        for(const newSigner of newSigners) {
            clique.propose(newSigner, true);
        }
        clique.propose(signer, newSigners.includes(signer)); //false for old signers
        
    }
}
```

As soon as geth started normally (unlocking all accounts etc), its possible to do a `geth attach --exec "loadScript('theScript.js')" /your/datadir/geth.ipc`

FWIW, we have a [public repo](https://github.com/Morpher-io/private-network-geth-poa-clique-explorers/blob/feature/migrate-container/config/migrateSigners.js) using essentially this plus some AWS scripts between production and dev, but the script above is the main part. The main entry is a [migrate-container in the docker-compose.yml](https://github.com/Morpher-io/private-network-geth-poa-clique-explorers/blob/feature/migrate-container/docker-compose.yml) file.

Might help someone. 

If there are any suggestions to make it better, of course, any help is appreciated.
