### ISSUE TITLE
Failed to reset txpool state

### ISSUE THREAD

**Issue by ucwong** [ethereum/go-ethereum#17441]
![image](https://user-images.githubusercontent.com/22344498/44298813-b374fb00-a31c-11e8-9b7b-9d28b157ba0c.png)

**Comment by rjl493456442** [comment]
Could you please provide your geth version?

**Comment by ucwong** [comment]
@rjl493456442 Geth/v1.8.14-unstable-5656565a/linux-amd64/go1.9.5

**Comment by flefevre** [comment]
hello, I have the same problem

my geth version:
b50ecb6c8e09 | Geth/v1.8.14-unstable-5e1d9f14/linux-amd64/go1.10.3





` [36mminer_1      | [0m ERROR[08-22|15:10:30.310] Failed to reset txpool state             err="missing trie node 677f76bfe10a562cb13f5d8c1dc75e17ca4c69ab33ceda3a34058373649cc665 (path )"`

**Comment by rjl493456442** [comment]
@ucwong @flefevre Thanks for the bug report! I am trying to debug it, it seems like a corner case which is hard to debug. 
Could you please provide more log information in the upper and lower range of the error log? Just want to find more detail.

**Comment by flefevre** [comment]
Quick question, you have modified noly clique.go and i was using more ethash, should it also be modified?

**Comment by karalabe** [comment]
The PR isn't about Clique, it just needed a unique hash for clique blocks too. We already have those for ethash in the miner.

**Comment by vdamle** [comment]
FYI @rjl493456442 - I patched diffs in this PR on top of `v1.8.14-stable` and I still see the error on a new node that is added to join a 3-node chain that was migrated from `v1.7.3-stable -> v1.8.14-stable`.

[geth18-added-node.log](https://github.com/ethereum/go-ethereum/files/2315021/geth18-added-node.log)

**Comment by karalabe** [comment]
@vdamle This seems to be an unrelated issue. Could you share your chain (first 1K blocks) so I might try an import locally and dissect what goes wrong?

**Comment by vdamle** [comment]
Thanks, @karalabe. I have attached a backup of blocks `0-999`. Also, here is the genesis config for reference:
```
        "config": {
          "homesteadBlock": 1,
          "byzantiumBlock": 0,
          "eip150Block": 0,
          "eip155Block": 0,
          "clique": {
            "period": 5,
            "epoch": 30000
          },
          "chainId": 2923884564
        }
```

[backup.gz](https://github.com/ethereum/go-ethereum/files/2315161/backup.gz)

**Comment by vdamle** [comment]
@karalabe - did you get a chance to look at this? After a few experiments, I am sure that this is related to the chain not being initialized with `eip158Block` (the chains we have are fairly new, so they block number hasn't crossed the hard fork limit specified in the code ~2.5 million). When I start a chain with `eip158Block: n`, the chain continues to work without errors after migrating to `1.8.14`. In lieu of changing genesis block and re-creating chain, I attempted to migrate to a forked version of `1.8.14` to force the hard fork to `EIP158` with the following patch (this would force newer blocks produced after migration to be mined with EIP158 behavior):

```
+++ b/params/config.go
@@ -40,7 +40,7 @@ var (
                EIP150Block:         big.NewInt(2463000),
                EIP150Hash:          common.HexToHash("0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0"),
                EIP155Block:         big.NewInt(2675000),
-               EIP158Block:         big.NewInt(2675000),
+               EIP158Block:         big.NewInt(30),
                ByzantiumBlock:      big.NewInt(4370000),
                ConstantinopleBlock: nil,
                Ethash:              new(EthashConfig),
```

The nodes *seem* to work ok but I wanted to check if the above tweak would cause issues for blocks which are in the range [30, m] where `m` is the actual block number which is mined with `EIP158` setting. Let me know your thoughts.

**Comment by ernesto-usal** [comment]
@vdamle I have the same problem running a network with one node with 1.8.14. But after modifying ```EIP158Block``` param in config.go as you did, and using the modified version of geth, I still have the same ```Failed to reset txpool state``` when I try to submit a transaction. 
Initially the node was working perfectly, but after ~60 000 blocks (difficult to determine exactly when), it started with the error.
