### ISSUE TITLE
"Unexpected rpc token" error

### ISSUE THREAD

**Issue by joohyeung** [ethereum/go-ethereum#17442]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version` .13
OS & Version: Windows/Linux/OSX window 10
Commit hash : (if `develop`)

#### Expected behaviour

Using geth to operate the mist in the developer environment

#### Actual behaviour

" Unexpected rpc token "  error
![asdqdqdqdqdqd](https://user-images.githubusercontent.com/41462311/44301914-66177e80-a35a-11e8-81f9-351d86aaac27.png)

" 식 또는 문에서 예기치 않은 'rpc' 토큰 입니다 " that means " unexpected rpc token"
" 연산자는 변수 또는 속성에서만 동작합니다" that means  "Operators work only with variables or properties" 

plz help!!

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Please open an issue at the Mist repo, this is an error raised by Mist, not by go-ethereum.
