### ISSUE TITLE
Expose securely your network question

### ISSUE THREAD

**Issue by marcosmartinez7** [ethereum/go-ethereum#17456]
Im implementing a ethereum PoA network using go-ethereum

I have deployed a ERC20 Token on the network, and the idea is that the network **must be accessed from any wallet on the internet** (i.e metamask, myetherwallet, etc)

The idea for this network is: 

- Having N full nodes that are able to seal blocks (the nodes has the unlocked accounts)
- Deploy a smart contract that is a ERC20 Token
- Having one node that expose the network **in order to be accessed from any origin**, for example, Metamask, MyEtherWallet, a mobile app with a wallet, etc. The idea is that **anybody can hit the ERC20 Token** if they have the appropiate client. 

In order to achive that, i create 2 full nodes that are in charge of sealing the blocks. 

I run those nodes like this:

    geth --datadir sealer1/  --syncmode 'full' --port 30351 --rpc --rpcaddr 'localhost' --rpcport 8502 --rpcapi='admin,personal,db,eth,net,web3,txpool,miner' --networkid 20 --gasprice '1' -unlock 'someaccount' --password s2/password.txt --mine

As you can see, there are some important things about those nodes:

1. Unlocks the accounts
2. Are only accessed from localhost (note the rpcaddres)
3. Those nodes are miners

If i expose a node like that to the internet (enabling RPC access from any origin) any hacker could send the ether to another account, so, i create a third node, a standard node, that doesnt expose rpc apis but allows connections on port 8545 (in order to be hitted from metamask, myetherwallet, etc) 

I run the node with this command:

    geth --datadir standard1/ --syncmode 'full' --port 30352 --rpc --rpcport 8545--rpccorsdomain '*' --rpcaddr 'SERVER_PUBLIC_IP' --networkid 20 --gasprice '1'  

as you can see this node:

1. Doesnt unlock account
2. Allow rpc accesing from any origin
3. Doesnt expose rpc apis like personal, admin, etc

My questions are:

- is this aproach secure? 
- Is there another way to allow anyone in the world to use Metamask to hit my smartcontract without open the RPC access on the standard node?

**Comment by marcosmartinez7** [comment]
Here is the stackoverflow discussion, i would **really** apreciate any help

https://ethereum.stackexchange.com/questions/57026/expose-securely-your-network-to-make-possible-anyone-can-hit-your-smart-contract/

**Comment by cloud197** [comment]
sounds like relentless efforts to being pricks

**Comment by cloud197** [comment]
*unrelentless pricks

**Comment by cloud197** [comment]
your shity humanity is evident in realtime. trust
