### ISSUE TITLE
Makefile:15: recipe for target 'geth' failed

### ISSUE THREAD

**Issue by huty323** [ethereum/go-ethereum#17462]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information
OS & Version: Ubutun16.04
go version:1.7.3
####Error
build/env.sh go run build/ci.go install ./cmd/geth
# github.com/ethereum/go-ethereum/vendor/github.com/Azure/azure-pipeline-go/pipeline
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:49: r.GetBody undefined (type Request has no field or method GetBody)
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:58: undefined: http.NoBody
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:59: r.GetBody undefined (type Request has no field or method GetBody)
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:60: undefined: http.NoBody
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:95: undefined: http.NoBody
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:107: undefined: http.NoBody
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 2

**Comment by karalabe** [comment]
We require at least Go 1.8.0 to build, please update your Go installation.
