### ISSUE TITLE
API call to determine if node is synchronised

### ISSUE THREAD

**Issue by smartwombat** [ethereum/go-ethereum#17485]
Geth version: 1.8.13
OS & Version: Windows 10

#### Expected behaviour
An API call to unambiguously give the state of a node.

#### Actual behaviour
It seems impossible to accurately infer the state of a node.
Particularly during startup.

#### Steps to reproduce the behaviour
Start geth from the command window, and observe the output:

`INFO [08-22|17:06:15.962] Starting peer-to-peer node               instance=Geth/v1.8.13-stable-225171a4/windows-amd64/go1.10.3
INFO [08-22|17:06:15.962] Allocated cache and file handles         database="C:\\Users\\<username>\\AppData\\Roaming\\Ethereum\\testnet\\geth\\chaindata" cache=3072 handles=1024
INFO [08-22|17:06:44.516] Persisted trie from memory database      nodes=355 size=51.89kB time=976.8µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [08-22|17:06:44.516] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: <nil> Engine: ethash}"
INFO [08-22|17:06:44.516] Disk storage enabled for ethash caches   dir="C:\\Users\\<username>\\AppData\\Roaming\\Ethereum\\testnet\\geth\\ethash" count=3
INFO [08-22|17:06:44.516] Disk storage enabled for ethash DAGs     dir="C:\\Users\\<username>\\AppData\\Ethash"                                   count=2
INFO [08-22|17:06:44.517] Initialising Ethereum protocol           versions="[63 62]" network=3
INFO [08-22|17:06:44.518] Loaded most recent local header          number=3889943 hash=e32173…3e8244 td=9609800456533734
INFO [08-22|17:06:44.518] Loaded most recent local full block      number=0       hash=419410…ca4a2d td=1048576
INFO [08-22|17:06:44.518] Loaded most recent local fast block      number=3889865 hash=f9def2…985cab td=9608646423438931
INFO [08-22|17:06:44.519] Loaded local transaction journal         transactions=0 dropped=0
INFO [08-22|17:06:44.521] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-22|17:06:44.522] Starting P2P networking 
INFO [08-22|17:06:46.677] UDP listener up                          self=enode://eb1d447460ccfda62c7e9fa3a2b77d2b94a6cca9848f955fd3e2e6ad428a36f28147593bae501e8c18026e6520a86d921ee477d15ddf9f81efe5b482ece4f74e@[::]:30303
INFO [08-22|17:06:46.677] RLPx listener up                         self=enode://eb1d447460ccfda62c7e9fa3a2b77d2b94a6cca9848f955fd3e2e6ad428a36f28147593bae501e8c18026e6520a86d921ee477d15ddf9f81efe5b482ece4f74e@[::]:30303
INFO [08-22|17:06:46.679] IPC endpoint opened                      url=\\\\.\\pipe\\geth.ipc
INFO [08-22|17:06:46.783] Etherbase automatically configured       address=0xf79e8bA649dAa6B42dD6D0BB33B6584484F21A1a`

At this point:
Connect from another command window with geth attach ipc:\\.\pipe\geth.ipc and try seemingly relevant API calls...
`net.listening returns true
net.peerCount returns 3
eth.syncing returns false`

The API seems to only give reasonable results a few minutes later after geth reports:
`INFO [08-22|17:17:16.679] Block synchronisation started `
At which point eth.syncing statrs returning sensible values.

**How, from a client application using the API, can I reliably find out what state the node is in ?**
Particularly during the (variable duration) startup phase before block syncing starts ?

**Comment by karalabe** [comment]
A crude way would be to retrieve the latest block and see it's timestamp.

**Comment by smartwombat** [comment]
Yeah, rather crude but it may be the only way.

I've been comparing geth and Parity nodes.  It seems that Parity nodes will connect to far more peers than geth, but does that matter ?

I found that running geth on two different computers they each connected to only one peer, each a different peer, and for about 18 minutes one did not update eth.blockNumber wehreas the other node was incrementing.

That implies that the _quality_ of peers varies, and while they can be online and responding to the protocol there is no guarantee that any node is up to date.

I appreciate that consensus takes time to spread through the nodes, but 18 minutes ?

If a node is that far away from consensus, and it's the only peer node (geth seems to suck at peer connections) then can my node safely be used to create Ether sending transactions ?
