### ISSUE TITLE
Proposal: Paginated Filter Queries

### ISSUE THREAD

**Issue by mslipper** [ethereum/go-ethereum#17487]
# Proposal: Paginated Log Queries

Currently, RPC endpoints that support filtering logs by topic and block number return all matched logs in a single request. When a non-streaming client requests those logs (i.e., any HTTP client expecting a JSON-RPC response), they are buffered in memory before being marshalled. This leads to memory exhaustion errors when the number of matched logs is very large. Consider the following RPC query, for example:

```bash
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock": 1, "toBlock": "latest"}],"id":73}'
```

When you send this request to a live Geth node (which I have, accidentally), the request will block and the node will steadily use more memory until it crashes.

This issue exists for the following RPC methods:

- `eth_getLogs`
- `eth_getFilterLogs`
- `eth_getFilterChanges`

To solve this problem, I'd like to propose adding pagination to the above methods. Below, see my proposal for how we could implement it.

> Note: This _will_ be a breaking change, so I thought this issue could be used for discussion before submitting a formal EIP.

## Paginated Response Schema

The above three RPC methods all share the same response, represented in the codebase by the `Log` struct in `core/types`. The response, in JSON, looks like this:

```json
{
  "id":1,
  "jsonrpc":"2.0",
  "result": [{
    "logIndex": "0x1", // 1
    "blockNumber":"0x1b4", // 436
    "blockHash": "0x8216c5785ac562ff41e2dcfdf5785ac562ff41e2dcfdf829c5a142f1fccd7d",
    "transactionHash":  "0xdf829c5a142f1fccd7d8216c5785ac562ff41e2dcfdf5785ac562ff41e2dcf",
    "transactionIndex": "0x0", // 0
    "address": "0x16c5785ac562ff41e2dcfdf829c5a142f1fccd7d",
    "data":"0x0000000000000000000000000000000000000000000000000000000000000000",
    "topics": ["0x59ebeb90bc63057b6515673c3ecf9438e5058bca0f92585014eced636878c9a5"]
    },{
      ...
    }]
}
```

Logs are ordered based on their ascending block number. I propose wrapping the result in a 'cursor' object as follows:

```json
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "cursorStartBlock": "0x1",
    "cursorEndBlock": "0x64",
    "cursorNextBlock": "0x65",
    "logs": [
      {
        "logIndex": "0x1",
        "blockNumber": "0x64",
        "blockHash": "0x8216c5785ac562ff41e2dcfdf5785ac562ff41e2dcfdf829c5a142f1fccd7d",
        "transactionHash": "0xdf829c5a142f1fccd7d8216c5785ac562ff41e2dcfdf5785ac562ff41e2dcf",
        "transactionIndex": "0x0",
        "address": "0x16c5785ac562ff41e2dcfdf829c5a142f1fccd7d",
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "topics": [
          "0x59ebeb90bc63057b6515673c3ecf9438e5058bca0f92585014eced636878c9a5"
        ]
      }
    ]
  }
}
```

The cursor is defined as a view of logs in some constant number of blocks. When the latest block is reached, `cursorNextBlock` will be `null`. `cursorStartBlock` and `cursorEndBlock` represent the start and end blocks (inclusively) in the _cursor_, not the filter that created the cursor. All numeric values in the cursor will be returned as hex.

I think paginating by blocks is cleaner than simply paginating by offsets for the following reasons:

- The RPC API is already allows filtering based on block numbers.
- Returning a window of blocks simplifies 'inner loop' logic in clients that want to consume large lists of transactions. For example, to iterate through all transactions in the chain the following pseudocode would suffice:

```
var id = eth.newFilter(fromBlock: 0, toBlock: 'latest')
while (res.cursorNextBlock != null) {
  res = eth.getFilterLogs(id: id)
  // do something with res.logs
}
```

It also _appears_ simpler to implement given the existing filter backend and event system - see the 'Implementation Details' section for my research here.

## Requesting Specific Pages

To request the next page in the cursor, I propose modifying the following RPC endpoints as follows:

### `eth_getFilterChanges`

Modify the request payload to be an object with the following schema:

```json
{
	"filterId": "0x16",
	"cursorStartBlock": "0x65
}
```

For filters created with `eth_newBlockFilter` or `eth_newPendingTransactionFilter`, the `cursorStartBlock` parameter will be ignored.

If `cursorStartBlock` is omitted, is defaults to the filter's `startBlock` parameter. If `cursorStartBlock` is less than the filter's `fromBlock` parameter or larger than its `toBlock` parameter, an error is returned.

### `eth_getFilterLogs`

See `eth_getFilterChanges`.

### `eth_getLogs`

Modify the request payload to support an additional `cursorStartBlock` field. If `cursorStartBlock` is omitted, is defaults to the `fromBlock` parameter. If `cursorStartBlock` is less than the `fromBlock` parameter or larger than the `toBlock` parameter, an error is returned.

It probably doesn't make sense to paginate datasets when the a client knows the number of blocks they want to query beforehand - i.e., `toBlock` is not `latest`. In cases like this, we can enforce a maximum difference between `fromBlock` and `toBlock` to only return a single page of results.

## Implementation Details

The current log filtration system is handled by two subsystems: `filters.EventSystem`, and `filters.Backend`. `EventSystem` handles filters that are explcitly installed/uninstalled by wrapping an instance of `Backend` in an event loop. `Backend` is used directly by `eth_getLogs`. Both `Backend` and `EventSystem` already support queries between two block numbers. Thus, to support cursors at the API level it should be straightforward to modify the RPC event handlers to call the filter system with modified start and end blocks based on the provided cursor. This avoids having to modify additional code within Geth that relies upon the filter system. 

Note that we will need to manage an additional pointer in the mapping of active filters to IDs that represents the last block number read for `eth_getFilterChanges`.

cc @karalabe - we talked about this today. What do you think, particularly about the proposal to modify the API layer rather than refactoring the event system?

**Comment by holiman** [comment]
Cc @zsfelfoldi
