### ISSUE TITLE
Unable to initialise private chain with coins

### ISSUE THREAD

**Issue by leeadh** [ethereum/go-ethereum#17482]
Dear all, 

I am trying to run my private chain. I initialised the genesis file

[{
    "nonce": "0x0000000000000042",
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "difficulty": "0x4000",
    "alloc": {},
    "coinbase": "0x0000000000000000000000000000000000000000",
    "timestamp": "0x00",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "Custem Ethereum Genesis Block",
    "gasLimit": "0xffffffff"
}
](

And  then did 

geth init genesis.json --datadir eth-data --networkid 123 --nodiscover --maxpeers 0 console and create my address. 

I then exit, when back to genesis and then changed the gensis file to as below

[{
    "nonce": "0x0000000000000042",
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "difficulty": "0x4000",
    "alloc": {
    "xxxxx": {
        "balance": "10000000000000000000"
   		}
   	},
    "coinbase": "0x0000000000000000000000000000000000000000",
    "timestamp": "0x00",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "Custem Ethereum Genesis Block",
    "gasLimit": "0xffffffff"
}](url)

I then 

rm -rf chaindata dapp history nodekey
and reinit the gensis by doing 

[geth init genesis.json --datadir eth-data --networkid 123 --nodiscover --maxpeers 0 console and create my address. ]

However, I cant see any ethers in my account. any idea whats going on

**Comment by QasidLabeed** [comment]
You should use

rm -rf geth
And then try reinit
