### ISSUE TITLE
Ethereum Anchoring

### ISSUE THREAD

**Issue by ayushkaul95** [ethereum/go-ethereum#17499]
This is a feature request for introducing Private blockchain anchoring. Also it'll be great to know any implementations for this in the current version (if any).

**Comment by karalabe** [comment]
I'm not even sure what anchoring means. Geth however does not have any built in support to link two chains together.

**Comment by ayushkaul95** [comment]
In a very hand wavy explanation, Anchoring is the method in which block hashes of private blockchain are stored on the the public blockchain. This can enable transparency in a private blockchain.

**Comment by princesinha19** [comment]
Actually Anchoring means:-
The block hashes of a private chain are periodically written into a public chain. For this purpose, not all block hashes have to be transmitted; for example, a daily match is sufficient. In the case of a manipulation within the private chain, it is possible to know which blocks can be trusted and when a manipulation has occurred. The only transmitted information is the block number and the associated block hash.

**Comment by karalabe** [comment]
Geth doesn't have such a functionality and there are no plans to add it. You can easily create a bridge though that can pass transactions or whatnot back and forth between two chains. I've written up a sample a while back (i.e. it may not fully work as is currently) https://gist.github.com/karalabe/cad11a9905bc7d4cd9eda8049b61856d
