### ISSUE TITLE
can't mining

### ISSUE THREAD

**Issue by JoyCood** [ethereum/go-ethereum#17497]
the issues same with [**this**](https://github.com/ethereum/go-ethereum/issues/16543#issue-316560298), but i got the latest geth version:

> 192:test knight$ geth version
Geth
Version: 1.8.13-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: darwin
GOPATH=
GOROOT=/usr/local/go

system:
`macOS sierra 10.12`

start geth with this command:
`geth --datadir node5 --rpc  --rpccorsdomain "*" --networkid=2018  --rpccorsdomain "*" --cache 2048 console`

**Comment by karalabe** [comment]
Please don't just refer to an old closed issue. If you see something wrong, please provide as much details as you can so we might investigate.

**Comment by smartBoy88** [comment]
the problem has solved by wait half of day after `miner.start()` command run. thanks you.

**Comment by JoyCood** [comment]
@karalabe the problem has solved by wait half of day after `miner.start()` command run. thanks you.

**Comment by karalabe** [comment]
Then your difficulty is probably way too large. Consider reducing it in the genesis block.
