### ISSUE TITLE
Truffle tests don't run successfully on local geth chain

### ISSUE THREAD

**Issue by ABBDVD** [ethereum/go-ethereum#17495]
Some truffle tests (for example MetaCoin 
![image](https://user-images.githubusercontent.com/7634156/44409313-70a46480-a562-11e8-9f09-992bad6ebb63.png)
that run successfully in truffle develop (and ganache-cli) fail if run on geth, producing different results than expected.

#### System information

Geth version: `1.8.12-stable`
OS & Version: Windows 10 version 1803

#### Expected behaviour
Truffle tests should run generally the same way on geth as in truffle develop and ganache-cli unless there are obvious differences in the setup (for example available funds on the accounts) that have effect.

#### Actual behaviour
Some Truffle tests fail by producing different results than expected. In the case of MetaCoin after substituting the call with a transaction to result in a transaction that's traceable, the trace shows that the call to the ConvertLib contract succeeds and also returns the correct value of 20'000. It then stops at 

#### Steps to reproduce the behaviour
Note: For all geth commands use the data "--datadir" option to not work on the default datadir and prevent loosing any data.
Setup truffle Metacoin:
1. create an empty directory
2. call ```truffle unbox Metacoin``` in the empty directory
3. For Windows you might have to delete truffle.js
4. adjust truffle-config.js (respectively truffle.js) to use geth by adding the following config:
```module.exports = {
  networks: {
    geth: {
      host: 'localhost',
      port: 8545,
      gas: 6000000
      network_id: '*',
    },
  },
};
 ```
5. (Optionally) replace the call in line 21 ```return meta.getBalanceInEth.call(accounts[0]);``` of metacoin.js in the test directory with sendTransaction ```return meta.getBalanceInEth.sendTransaction(accounts[0]);``` to allow for looking at the trace. The test will of course fail after the call though as the transaction doesn't return a value as expected, but the transaction / respectively trace of it should still be by itself be correct.

Setup local geth chain with preloaded accounts and run tests:
1. (Optionally) ```geth removedb``` to have a clean datadir to allow setting an own genesis block.
2. ```geth init geth_genesis.txt``` (see attached [geth_genesis.txt](https://github.com/ethereum/go-ethereum/files/2313686/geth_genesis.txt) file)
3. ```geth --vmdebug --networkid 1234 --port 11111 --rpc --rpcapi web3,eth,personal,miner,net,txpool,debug --fakepow --debug console```
4. In the geth console ```web3.personal.unlockAccount(web3.personal.listAccounts[0], "", 0)```
(or unlock accounts with rpc using for example web3.py)
5. In the geth console ```miner.start()```
6. In the Metacoin directory: ```truffle test --network geth```
7. stop the geth miner after the truffle tests are done: ```miner.stop()```
 
Debugging:
- Find the transaction with the input that starts with `0x7bd703e8` as that's the 4 byte signature of the getBalanceInETH(address)  function which is called in the failed test (if call is replaced by sendTransaction). This should in that case be the second last transaction and can be checked easiest with ```web3.eth.getBlock(###, true)``` where ### is the number of the block with the second last transaction.
- The receipt shows interestingly that all gas is used. The trace which can be printed with ```web3.debug.traceTransaction``` clearly shows that at the end of the trace there should still be gas left.
- The trace also shows that the last operation is RETURNDATASIZE which is not a valid return operator that should end a trace.
Here are receipt, block info about the transaction and the trace [transaction_info.txt](https://github.com/ethereum/go-ethereum/files/2314009/transaction_info.txt)

One possibility regarding incomplete traces could be that the Returndata instructions are not handled correctly yet since their introduction.

**Comment by ritzdorf** [comment]
I see the same problem on 
Geth version: `1.8.13-stable`
OS & Version: Archlinux

The returned trace simply ends with `RETURNDATASIZE` which seems very strange.

**Comment by ABBDVD** [comment]
The tests pass the way you suggest, but not if I try it analog on a local non --dev chain as described above.
I can most likely use your way as a workaround for my purposes, but I still wonder why  it wouldn't work with the own genesis block. Any ideas?

**Comment by cgewecke** [comment]
@ABBDVD Actually Truffle has a recently opened [issue](https://github.com/trufflesuite/truffle/issues/1241) that seems relevant to this question. If you have a chance could you check that out and see if anything jumps out at you?

**Comment by cgewecke** [comment]
The dev chain genesis block at go-ethereum is around [here](https://github.com/ethereum/go-ethereum/blob/461291882edce0ac4a28f64c4e8725b7f57cbeae/core/genesis.go#L338) . . .

**Comment by ABBDVD** [comment]
As the problem actually happens also for calls and not only a transaction it would appear that it can't be the same issue as with the status field in the transaction receipt.

**Comment by Tusharsb** [comment]
I found one (related?) problem.

After diagnosing with `truffle debug` I found that [this line in MintableCrowdsale contract](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.12.0/contracts/crowdsale/emission/MintedCrowdsale.sol#L26) fails on `geth` while it runs perfect on `ganache-cli`.
