### ISSUE TITLE
Docker image uses Alpine, should be Ubuntu

### ISSUE THREAD

**Issue by psteckler** [ethereum/go-ethereum#17503]
#### System information

Host system is Linux Mint 18.1 x64.

#### Expected behaviour

I'm writing a Dockerfile that uses `ethereum/client-go` as the base image. That's supposed to be running Ubuntu.

#### Actual behaviour

```
Welcome to Alpine Linux 3.8
Kernel \r on an \m (\l)
```

#### Steps to reproduce the behaviour

Dockerfile:

```
FROM ethereum/client-go
RUN cat /etc/issue
```

Run:
```
docker build - < Dockerfile
```

NB: If I use `ethereum/client-go:alpine`, I also get an Alpine-based system.

**Comment by lmars** [comment]
@psteckler the geth Docker images _are_ Alpine based (see [here](https://github.com/ethereum/go-ethereum/blob/master/Dockerfile#L10)), if you want an Ubuntu based geth image you'll probably need to build your own.

**Comment by psteckler** [comment]
@lmars Then the documentation at https://github.com/ethereum/go-ethereum/wiki/Running-in-Docker is wrong. There it claims there are two versions.

**Comment by mryellow** [comment]
> if you want an Ubuntu based geth image you'll probably need to build your own.

Documentation incorrectly states that the default is a Ubuntu based image.

Appears `alltools-latest` tag is the one which should be default.

**Comment by mryellow** [comment]
```
FROM ethereum/client-go:alltools-stable
RUN cat /etc/issue
```

```
Welcome to Alpine Linux 3.9
Kernel \r on an \m (\l)
```

Although larger the `alltools` images are also Alpine.

Documentation is wrong or missing images need to be produced?

**Comment by adamschmideg** [comment]
All Docker images are based on Alpine. The linked documentation is outdated (as it says now in the header). If you want to create an Ubuntu-based Geth image, refer to https://geth.ethereum.org/docs/install-and-build/installing-geth#install-on-ubuntu-via-ppas
