### ISSUE TITLE
we need a function can get blockNumber in ethclient package

### ISSUE THREAD

**Issue by iazkaban** [ethereum/go-ethereum#17507]
Hi there,

we need a function what can get blockNumber in ethclient package.

we need to get the highest blockNumber ,but function syncProcess is not work every time.

**Comment by xlk3099** [comment]
@iazkaban , ethClient is a wrapper of `rpc.Client`, you can write your own ethClient easily. 

To get the latest blockNumber, you can write something like
```
type Client struct {
	*rpc.Client
}

func (ec *Client) GetLatestBlockNumber(ctx context.Context) (uint64, error) {
	var resp string
	if err := ec.CallContext(ctx, &resp, "eth_blockNumber"); err != nil {
		return 0, err
	}
	return helper.ParseUint(resp)
}
```
