### ISSUE TITLE
Invalid Merkle Root on valid block in private PoA network

### ISSUE THREAD

**Issue by davidstoneham** [ethereum/go-ethereum#17513]
Geth version: `1.13 stable`
OS & Version: All

Valid blocks are being marked as invalid due to an `invalid merkle root` error. These blocks are valid and after adding some logging I can confirm the reason for failure is that it is comparing the Merkle hash at the previous block and not at the current block.
I.e. if I log the Merkle hash on each new block the block that cases the error shows the same local merkle root of the previously validated block. 

Stopping and restarting geth will cause the same issue but on a different block, it will validate the previously invalidated block and fail on a new block.

`INFO [08-26|15:43:05.277] DS::ValidateState::Check merkle root     remote=2eb223…aab415 local=2eb223…aab415`
`INFO [08-26|15:43:05.278] DS::ValidateState::Check merkle root     remote=d8c6cd…490885 local=2eb223…aab415`
`ERROR[08-26|15:43:05.278]`
`########## BAD BLOCK #########`
`Number: 100462`
`Error: invalid merkle root (remote: d8c6cd9e1b331ef9f0be2252f3578b71a4821bd5a9b0b16c3042150663490885 local: 2eb223a198fb2308929bd092a2af4825e8d6d5b2fa97eeb8ef7ccaf47aaab415)`
`##############################`

**Comment by FricWang** [comment]
How did you solve this problem? If you have the solution, share with me please.

**Comment by liwei00wade** [comment]
@FricWang 
How did you solve this problem? If you have the solution, share with me please.

**Comment by taoxinyi** [comment]
Same problem here when using POA.

**Comment by davidstoneham** [comment]
My particular issue was the result of a personal code change causing the merkle tree to become invalid
