### ISSUE TITLE
mining on private network is not working

### ISSUE THREAD

**Issue by gftea** [ethereum/go-ethereum#17518]
Mining not started after issuing miner.start() on private network
after trace "Commit new mining work" seen, nothing happened.
Same issue with 1.8.13-stable

#### System information
Geth version:  1.8.14-stable
OS & Version: OSX

#### Expected behaviour
mining should start after issuing miner.start()

#### Actual behaviour
mining not started

#### Steps to reproduce the behaviour
$ geth --networkid 16344 --datadir ./node01/ --identity node01 --ipcpath ./node01/geth.ipc --rpc  --nodiscover console
INFO [08-26|21:12:07.153] Maximum peer count                       ETH=25 LES=0 total=25
INFO [08-26|21:12:07.298] Starting peer-to-peer node               instance=Geth/node01/v1.8.14-stable/darwin-amd64/go1.10.3
INFO [08-26|21:12:07.299] Allocated cache and file handles         database=/Users/chensimon/Develop/blockchain/network131/node01/geth/chaindata cache=768 handles=128
INFO [08-26|21:12:07.375] Initialised chain configuration          config="{ChainID: 16344 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: <nil> Constantinople: <nil> Engine: unknown}"
INFO [08-26|21:12:07.375] Disk storage enabled for ethash caches   dir=/Users/chensimon/Develop/blockchain/network131/node01/geth/ethash count=3
INFO [08-26|21:12:07.375] Disk storage enabled for ethash DAGs     dir=/Users/chensimon/.ethash                                          count=2
INFO [08-26|21:12:07.375] Initialising Ethereum protocol           versions="[63 62]" network=16344
INFO [08-26|21:12:07.377] Loaded most recent local header          number=0 hash=382d92…9f5c9e td=32
INFO [08-26|21:12:07.377] Loaded most recent local full block      number=0 hash=382d92…9f5c9e td=32
INFO [08-26|21:12:07.377] Loaded most recent local fast block      number=0 hash=382d92…9f5c9e td=32
INFO [08-26|21:12:07.378] Loaded local transaction journal         transactions=0 dropped=0
INFO [08-26|21:12:07.378] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-26|21:12:07.379] Starting P2P networking 
INFO [08-26|21:12:07.379] RLPx listener up                         self="enode://c159ccd278111d7bd2f5d20b7faf3843614c9596e1bc3f62809ea194b222c774be65fd3a2dc22339a8f4c6e2f8bfca1d29302994b07cfdd746a756158d579515@[::]:30303?discport=0"
INFO [08-26|21:12:07.383] IPC endpoint opened                      url=node01/geth.ipc
INFO [08-26|21:12:07.384] HTTP endpoint opened                     url=http://127.0.0.1:8545 cors= vhosts=localhost
Welcome to the Geth JavaScript console!

instance: Geth/node01/v1.8.14-stable/darwin-amd64/go1.10.3
INFO [08-26|21:12:07.515] Etherbase automatically configured       address=0xE78eb1b57e90c0C2bCD4dcC55C08e227F3115Ee9
coinbase: 0xe78eb1b57e90c0c2bcd4dcc55c08e227f3115ee9
at block: 0 (Thu, 01 Jan 1970 01:00:00 CET)
 datadir: /Users/chensimon/Develop/blockchain/network131/node01
 modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> INFO [08-26|21:12:07.535] Mapped network port                      proto=tcp extport=30303 intport=30303 interface=NAT-PMP(192.168.199.1)

> miner.start(2)
INFO [08-26|21:12:13.283] Updated mining threads                   threads=2
INFO [08-26|21:12:13.284] Transaction pool price threshold updated price=18000000000
null
> INFO [08-26|21:12:13.284] Commit new mining work                   number=1 uncles=0 txs=0 gas=0 fees=0 elapsed=247.063µs

> admin.nodeInfo
{
  enode: "enode://c159ccd278111d7bd2f5d20b7faf3843614c9596e1bc3f62809ea194b222c774be65fd3a2dc22339a8f4c6e2f8bfca1d29302994b07cfdd746a756158d579515@[::]:30303?discport=0",
  id: "c159ccd278111d7bd2f5d20b7faf3843614c9596e1bc3f62809ea194b222c774be65fd3a2dc22339a8f4c6e2f8bfca1d29302994b07cfdd746a756158d579515",
  ip: "::",
  listenAddr: "[::]:30303",
  name: "Geth/node01/v1.8.14-stable/darwin-amd64/go1.10.3",
  ports: {
    discovery: 0,
    listener: 30303
  },
  protocols: {
    eth: {
      config: {
        chainId: 16344,
        eip150Hash: "0x0000000000000000000000000000000000000000000000000000000000000000",
        eip155Block: 0,
        eip158Block: 0,
        homesteadBlock: 0
      },
      difficulty: 32,
      genesis: "0x382d924d446348a2a26f8dd0ea02f62abcee4a5bbd543186d06942497c9f5c9e",
      head: "0x382d924d446348a2a26f8dd0ea02f62abcee4a5bbd543186d06942497c9f5c9e",
      network: 16344
    }
  }
}

**Comment by karalabe** [comment]
What difficulty did you set in your genesis block. Typically people don't pay attention and select one that is way too high for simple CPU mining. You can also check whether you indeed have 2 cores saturated when you start mining with `2` or not?

**Comment by gftea** [comment]
in genesis block 
> difficulty: 32
no single block is mined.
I also tried also miner.start(), miner.start(1), the same.

**Comment by gftea** [comment]
meanwhile, my macOS has 4GB RAM.
and if using miner.start(), it shows threads=0
> miner.start()
INFO [08-27|10:45:01.907] Updated mining threads                   threads=0

**Comment by karalabe** [comment]
Could you please paste the genesis block so I could take a look?

**Comment by gftea** [comment]
> eth.getBlock(0)
{
  difficulty: 32,
  extraData: "0x",
  gasLimit: 8388608,
  gasUsed: 0,
  hash: "0x382d924d446348a2a26f8dd0ea02f62abcee4a5bbd543186d06942497c9f5c9e",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 0,
  parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 504,
  stateRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  timestamp: 0,
  totalDifficulty: 32,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}

**Comment by rjl493456442** [comment]
@gftea I guess you didn't specify the consensus engine type since the log 
`INFO [08-26|21:12:07.375] Initialised chain configuration config="{ChainID: 16344 Homestead: 0 DAO: DAOSupport: false EIP150: EIP155: 0 EIP158: 0 Byzantium: Constantinople: Engine: unknown}"`

Could please take a look at your genesis file?

**Comment by gftea** [comment]
@rjl493456442 I run the same geth version on Windows, and without Engine type specified, mining is working. but of course it runs on a different laptop which is 8GB RAM, intel i7 CPU, see below


INFO [08-28|10:22:05.089] Initialised chain configuration          config="{ChainID: 8570 Homestead:
port: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: <nil> Constantinople: <nil> Engine: unknown}
INFO [08-28|10:22:05.104] Disk storage enabled for ethash caches   dir=C:\\Users\\ekaiqch\\develop\\n
geth\\ethash count=3
INFO [08-28|10:22:05.110] Disk storage enabled for ethash DAGs     dir=C:\\Users\\ekaiqch\\AppData\\E
             count=2
INFO [08-28|10:22:05.117] Initialising Ethereum protocol           versions="[63 62]" network=8570
INFO [08-28|10:22:05.123] Loaded most recent local header          number=606 hash=4bdb51.986226 td=9
INFO [08-28|10:22:05.128] Loaded most recent local full block      number=612 hash=6970d7.44a4d3 td=9
INFO [08-28|10:22:05.134] Loaded most recent local fast block      number=548 hash=82a0fc.f7767f td=8
INFO [08-28|10:22:05.139] Loaded local transaction journal         transactions=0 dropped=0
INFO [08-28|10:22:05.149] Regenerated local transaction journal    transactions=0 accounts=0
WARN [08-28|10:22:05.154] Blockchain not empty, fast sync disabled
INFO [08-28|10:22:05.158] Starting P2P networking
INFO [08-28|10:22:07.341] UDP listener up                          self=enode://2952896ff90bf969d968a
c55e2aaefde06229f6daad9f86b58e254317fad5b8f3220daa233a309cef44adf78fbed92bd3e7f72a0f1f4e@0.0.0.0:8081
INFO [08-28|10:22:07.357] RLPx listener up                         self=enode://2952896ff90bf969d968a
c55e2aaefde06229f6daad9f86b58e254317fad5b8f3220daa233a309cef44adf78fbed92bd3e7f72a0f1f4e@0.0.0.0:8081
INFO [08-28|10:22:07.359] IPC endpoint opened                      url=\\\\.\\pipe\\.\\node2\\geth.ip
INFO [08-28|10:22:07.380] HTTP endpoint opened                     url=http://127.0.0.1:8547
lhost
INFO [08-28|10:22:58.430] Etherbase automatically configured       address=0x5CF9e8A6Fe0cc235efFa1ed0
INFO [08-28|10:38:51.114] Updated mining threads                   threads=2
INFO [08-28|10:38:51.119] Transaction pool price threshold updated price=18000000000
INFO [08-28|10:38:51.127] Starting mining operation
INFO [08-28|10:38:51.133] Commit new mining work                   number=613 txs=0 uncles=0 elapsed=
INFO [08-28|10:42:15.039] Successfully sealed new block            number=613 hash=524a47.5d4679
INFO [08-28|10:42:19.404] ?? mined potential block                  number=613 hash=524a47.5d4679
INFO [08-28|10:42:19.409] Commit new mining work                   number=614 txs=0 uncles=0 elapsed=
INFO [08-28|10:42:22.112] Successfully sealed new block            number=614 hash=ac4563.1099f1
INFO [08-28|10:42:22.160] ?? mined potential block                  number=614 hash=ac4563.1099f1

**Comment by logrusorgru** [comment]
@stale, I want kill you!
