### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by spursy** [ethereum/go-ethereum#17528]
**When I sync node, I am always encounter the followed issue:** 
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xf6483c, 0x16)
        /usr/local/go/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc475d30000, 0x10000000, 0x0, 0x1b9a818)
        /usr/local/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x1b80e00, 0x10000000, 0x7fd22800f4b0)
        /usr/local/go/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x1b80e00, 0x8000, 0x0)

```

**When I check hard disk used：**

```
root@VM-0-16-ubuntu:/home/ubuntu# df -k
Filesystem     1K-blocks     Used Available Use% Mounted on
udev              939292        0    939292   0% /dev
tmpfs             191716    19840    171876  11% /run
/dev/vda1       51474024 33399332  15768608  68% /
tmpfs             958568       48    958520   1% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
tmpfs             958568        0    958568   0% /sys/fs/cgroup
tmpfs                100        0       100   0% /run/lxcfs/controllers
tmpfs             191716        0    191716   0% /run/user/500

```

**My hard disk is 500G, My RAM is 2G， My cpu is double core**

**Comment by ligi** [comment]
"out of memory" is not referring to the hard disk - but to the RAM. 2GB is really very little. Can you elaborate what you want to do with the node?

**Comment by drunken005** [comment]
@ligi I had the same problem, and I was running on an amazon server, configuration information: 
OS: ubuntu 16.4
RAM: 32G
CPU: 8 core
DISK: 50G SSD
geth: 1.8.14-stable

run:
geth --testnet  --syncmode=fast --rpc --rpcport 8698  --rpccorsdomain "*" --rpcapi _db,eth,net,web3,personal

After synchronization to the latest fast, memory continues to grow, after 100% process interrupt

**Comment by drunken005** [comment]
@karalabe  please

**Comment by deepakkumbhar46** [comment]
Any update on this issue?

**Comment by kkachniarz220** [comment]
bump
