### ISSUE TITLE
how to detect which consensus algorithm is driving the chain?

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/go-ethereum#17535]
My [chainhammer](https://gitlab.com/electronDLT/chainhammer) would like to automatically detect to which type of client (geth, quorum, parity, ...) it is connected, and which type of consensus (PoW, Aura, Clique, IBFT, raft, etc.) is running.

Right now, my heuristics is a rather [ugly sequence of different calls](https://gitlab.com/electronDLT/chainhammer/blob/5d3494ec0810e283cddc5881600099a15b0f1609/clienttype.py#L71-125).

Two questions:

1. how to best distinguish "geth PoW" from "geth PoA" and then specifically "geth Clique" ?
1. what about adding one more call to the web3 specification which answers *all that in one go*? 

(Where would be the right place to post such an issue? Sorry, I do know that this is geth, and my question is more general. forgive me please - and where do you send me instead of here? Thanks).

**Comment by karalabe** [comment]
If you request `admin.nodeInfo` from Geth, you'll get some protocol details too, and `eth` and `les` contains the chain configs:

E.g.

```
admin.nodeInfo.protocols.eth.config
{
  byzantiumBlock: 1035301,
  chainId: 4,
  clique: {
    epoch: 30000,
    period: 15
  },
  daoForkSupport: true,
  eip150Block: 2,
  eip150Hash: "0x9b095b36c15eaf13044373aef8ee0bd3a382a5abb92e402afa44b8249c3a90e9",
  eip155Block: 3,
  eip158Block: 3,
  homesteadBlock: 1
}
```

This will either contain a `clique` field or an `ethash` field.
