### ISSUE TITLE
The variable fetchHeader and hashes in the function literal is the same variable used by the loop.

### ISSUE THREAD

**Issue by etying** [ethereum/go-ethereum#17534]
refer to:https://golang.org/doc/articles/race_detector.html#Race_on_loop_counter

https://github.com/ethereum/go-ethereum/blob/63352bf4247f05d8ef255ff8c63290225c3bc671/eth/fetcher/fetcher.go#L388

**Comment by etying** [comment]
fetchHeader, hashes := f.fetching[hashes[0]].fetchHeader, hashes
				go func(fetchHeader headerRequesterFn, hashes []common.Hash) {
					if f.fetchingHook != nil {
						f.fetchingHook(hashes)
					}
					for _, hash := range hashes {
						headerFetchMeter.Mark(1)
						fetchHeader(hash) // Suboptimal, but protocol doesn't allow batch header retrievals
					}
				}(fetchHeader, hashes)

**Comment by karalabe** [comment]
```go
// Create a closure of the fetch and schedule in on a new thread
fetchHeader, hashes := f.fetching[hashes[0]].fetchHeader, hashes
```

It creates a closure to shadow the loop variables into local ones that can be used inside.
