### ISSUE TITLE
Ropsten won't sync in geth

### ISSUE THREAD

**Issue by smartwombat** [ethereum/go-ethereum#17539]
Geth version: 1.8.13
OS & Version: Windows 10

#### Expected behaviour
Well it seems obvious, I expect geth to synchronise.

#### Actual behaviour
Repeated errors "Head headers broke chain ordering" each followed by several hours when no new chain segments are imported, in some cases over 6 hours.

#### Steps to reproduce the behaviour
**geth --testnet 2>>geth.log**

It could be there is just a bad peer, and blacklisting it could make synchronisation succeed.
I notice that it's always the same peer when it fails.

```
  | WARN [08-27\|09:45:00.382] Head headers broke chain ordering        peer=**6332792c4a00e3e4** index=0 requested=3918572 received=3918768
-- | --
  | WARN [08-28\|04:52:09.041] Head headers broke chain ordering        peer=**6332792c4a00e3e4** index=0 requested=3923599 received=3923812
-- | --
  | WARN [08-28\|11:08:40.897] Head headers broke chain ordering        peer=**6332792c4a00e3e4** index=0 requested=3925339 received=3925547
-- | --
```
And after each failure it takes several hours for synchronisation to continue.

I know that Ropsten is a test network, but if that smaller chain can't be synchronised, then how reliable will the mainnnet be ?

In contrast a Parity node has been maintaining sync on Ropsten since last week with no issues.

**Comment by caesarchad** [comment]
Tried to reproduce your error
![_20180829160026](https://user-images.githubusercontent.com/17776934/44774031-aa99ea00-aba4-11e8-805f-7f66fa06140c.png)

**Comment by smartwombat** [comment]
I'm thinking that it's related to the peers I can connect to.
From behind a corporate firewall, with port 30303 not open.
All I can connect to is the shared peer addresses that are communicated from other nodes.
And it's not going well, I seem to get poor quality peers.

`INFO [08-28|14:16:43.220] Block synchronisation started 
INFO [08-28|14:16:44.984] Imported new chain segment               blocks=2 txs=41 mgas=7.709 elapsed=675.654ms mgasps=11.410 number=3925533 hash=408486…d664d0 cache=264.64kB
INFO [08-28|14:16:45.832] Imported new chain segment               blocks=14 txs=251 mgas=36.582 elapsed=847.091ms mgasps=43.186 number=3925547 hash=c45044…87fe90 cache=1.77mB
INFO [08-28|14:16:53.849] Imported new chain segment               blocks=116 txs=1885 mgas=353.217 elapsed=8.011s    mgasps=44.087 number=3925663 hash=685c1f…bda9e3 cache=14.14mB
INFO [08-28|14:16:58.578] Imported new chain segment               blocks=125 txs=2340 mgas=266.090 elapsed=4.729s    mgasps=56.261 number=3925788 hash=9ea967…b8018a cache=16.77mB
INFO [08-28|14:17:06.637] Imported new chain segment               blocks=283 txs=4083 mgas=572.158 elapsed=8.050s    mgasps=71.072 number=3926071 hash=bf321a…4028d5 cache=18.88mB
INFO [08-28|14:17:14.497] Imported new chain segment               blocks=314 txs=4646 mgas=561.178 elapsed=7.859s    mgasps=71.405 number=3926385 hash=734a37…2dbeac cache=23.86mB
INFO [08-28|15:15:56.715] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-28|16:15:56.731] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-28|17:15:56.745] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-28|18:15:56.781] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-28|19:15:56.923] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-28|20:15:57.008] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-28|21:15:57.060] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-28|22:15:57.095] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-28|23:15:57.120] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|00:15:57.140] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|01:15:57.157] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|02:15:57.175] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|03:15:57.198] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|04:15:57.344] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|05:15:57.429] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|06:15:57.489] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|07:15:57.519] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|08:15:57.545] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|08:18:25.717] Imported new chain segment               blocks=2   txs=28   mgas=3.499   elapsed=118.214ms mgasps=29.601 number=3926387 hash=be7dd6…2cbd0e cache=23.88mB
INFO [08-29|08:18:28.451] Imported new chain segment               blocks=9   txs=112  mgas=15.087  elapsed=2.412s    mgasps=6.253  number=3926396 hash=cf8934…917d47 cache=23.90mB
INFO [08-29|08:18:34.977] Imported new chain segment               blocks=112 txs=2216 mgas=249.366 elapsed=6.522s    mgasps=38.230 number=3926508 hash=01e59e…d89945 cache=26.67mB
INFO [08-29|08:18:43.002] Imported new chain segment               blocks=121 txs=1639 mgas=231.606 elapsed=8.003s    mgasps=28.940 number=3926629 hash=257776…824044 cache=27.04mB
INFO [08-29|08:18:51.073] Imported new chain segment               blocks=213 txs=3144 mgas=353.351 elapsed=8.070s    mgasps=43.785 number=3926842 hash=ab3b1f…1837da cache=29.54mB
INFO [08-29|08:18:59.078] Imported new chain segment               blocks=319 txs=6011 mgas=599.495 elapsed=8.005s    mgasps=74.883 number=3927161 hash=723f63…80850f cache=32.07mB
INFO [08-29|08:19:07.097] Imported new chain segment               blocks=272 txs=6037 mgas=591.732 elapsed=8.018s    mgasps=73.793 number=3927433 hash=cc6093…5b43b1 cache=35.42mB
INFO [08-29|08:19:14.031] Imported new chain segment               blocks=234 txs=4035 mgas=571.337 elapsed=6.933s    mgasps=82.404 number=3927667 hash=7090b7…eeced3 cache=36.11mB
INFO [08-29|08:19:22.068] Imported new chain segment               blocks=156 txs=1851 mgas=470.453 elapsed=8.002s    mgasps=58.785 number=3927823 hash=ddc5db…c62f4d cache=38.83mB
INFO [08-29|08:19:30.210] Imported new chain segment               blocks=349 txs=4628 mgas=1004.620 elapsed=8.141s    mgasps=123.390 number=3928172 hash=1e5828…d0dc66 cache=39.73mB
INFO [08-29|08:19:38.227] Imported new chain segment               blocks=383 txs=6123 mgas=871.975  elapsed=8.016s    mgasps=108.767 number=3928555 hash=614035…4a0049 cache=43.34mB
INFO [08-29|08:19:46.246] Imported new chain segment               blocks=350 txs=4699 mgas=546.063  elapsed=8.019s    mgasps=68.095  number=3928905 hash=c7be7f…b71fc4 cache=45.67mB
INFO [08-29|08:19:54.276] Imported new chain segment               blocks=387 txs=4182 mgas=500.223  elapsed=8.030s    mgasps=62.291  number=3929292 hash=7f4ee9…a21119 cache=45.83mB
INFO [08-29|08:20:02.653] Imported new chain segment               blocks=265 txs=3723 mgas=432.423  elapsed=8.376s    mgasps=51.620  number=3929557 hash=a7c987…d55263 cache=50.18mB
INFO [08-29|08:20:07.825] Imported new chain segment               blocks=158 txs=2980 mgas=280.934  elapsed=5.171s    mgasps=54.321  number=3929715 hash=fd3d93…9233dc cache=52.64mB
INFO [08-29|08:20:15.913] Imported new chain segment               blocks=215 txs=3133 mgas=397.691  elapsed=8.050s    mgasps=49.397  number=3929930 hash=978090…6e393b cache=54.75mB
INFO [08-29|08:20:23.948] Imported new chain segment               blocks=259 txs=4050 mgas=488.194  elapsed=8.035s    mgasps=60.757  number=3930189 hash=7da983…67e4c7 cache=55.24mB
INFO [08-29|08:20:31.995] Imported new chain segment               blocks=264 txs=3741 mgas=599.190  elapsed=8.046s    mgasps=74.465  number=3930453 hash=670319…1f5566 cache=57.78mB
INFO [08-29|08:20:39.997] Imported new chain segment               blocks=293 txs=4133 mgas=858.018  elapsed=8.001s    mgasps=107.228 number=3930746 hash=66d400…71d903 cache=62.05mB
INFO [08-29|08:20:45.742] Imported new chain segment               blocks=175 txs=2696 mgas=417.455  elapsed=5.744s    mgasps=72.667  number=3930921 hash=f4a0c2…ad26f2 cache=66.59mB
INFO [08-29|09:15:57.564] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|10:15:57.583] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|11:15:57.596] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|12:15:57.610] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|13:15:57.753] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-29|14:15:57.844] Regenerated local transaction journal    transactions=0 accounts=0
`

If this is indicative of the issues we will face on the mainnet, and the issues our customers will face if they try to run their own nodes, commercially it's not going to be a success.

**Comment by smartwombat** [comment]
Seems that the issue may be caused by a bad peer.
This week it has synchronised.
