### ISSUE TITLE
v1.8.14  Same height , get-work return difficulty target  is not the same

### ISSUE THREAD

**Issue by xianxiongwang** [ethereum/go-ethereum#17544]
Same height , get-work return difficulty target  is not the same.

#### System information

Geth version: `v1.8.14`
OS & Version: Linux 
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
It can happen if a small reorg happens (e.g. you receive a sibling to your current head and reorg it).

**Comment by karalabe** [comment]
But please provide some details logs so we can investigate if you think this is a problem

**Comment by xianxiongwang** [comment]
@karalabe  [a small reorg happens] ,Does it happen at old version ?
