### ISSUE TITLE
About how to back up data related to the wallet on the node server

### ISSUE THREAD

**Issue by liuhuanhui** [ethereum/go-ethereum#17543]

**Comment by caesarchad** [comment]
Node server usually do not store any data related to the wallet.
A wallet is actually a private key managing tool.
Do you mean the chain data ?

**Comment by caesarchad** [comment]
1. I  really do not think this is related to go-ethereum. 
2. newAccount will generate key store files, which are quite small. You can just backup these files seperately.

**Comment by liuhuanhui** [comment]
OK @caesarchad
