### ISSUE TITLE
Wrong unpack result for negative BigNumber

### ISSUE THREAD

**Issue by favadi** [ethereum/go-ethereum#17551]
#### System information

Geth version: unrelated
OS & Version: Windows/Linux/OSX
Commit hash : 62e94895da80838ec694b4ba19eeac80c9dc88c1

#### Expected behaviour

`int256` should be unpacked to correct `*big.Int` value.

#### Actual behaviour

Negative `int256` output is unpackaged `*big.Int` to positive `*big.Int` value.

#### Steps to reproduce the behaviour

```go
package balance

import (
	"bytes"
	"encoding/hex"
	"math/big"
	"testing"

	"github.com/ethereum/go-ethereum/accounts/abi"
)

func TestInt256Unpack(t *testing.T) {
	const method = "aTestMethod"
	const output = "ffffffffffffffffffffffffffffffffffffffffffffffec6dc439894e200000"
	const abiJSON = `[{
  "constant":true,
  "inputs":[
  ],
  "name":"aTestMethod",
  "outputs":[
    {
      "name":"",
      "type":"int256"
    }
  ],
  "payable":false,
  "stateMutability":"view",
  "type":"function"
}]`

	var ret = big.NewInt(0)
	outputBytes, err := hex.DecodeString(output)
	if err != nil {
		t.Fatal()
	}
	pricingABI, err := abi.JSON(bytes.NewReader([]byte(abiJSON)))
	if err != nil {
		t.Fatal(err)
	}

	if err = pricingABI.Unpack(&ret, method, outputBytes); err != nil {
		t.Fatal(err)
	}
	if ret.Sign() != -1 {
		t.Errorf("result should be negative, got: %s", ret.String())
	}
}
```

output: `115792089237316195423570985008687907853269984665640564039096558636546392064000`

Web3.js unpackaged the correct value.

```js
    const web3 = new Web3()
    console.log(
      web3.eth.abi.decodeParameter(
        'int256',
        '0xffffffffffffffffffffffffffffffffffffffffffffffec6dc439894e200000'
      )
    )
```

output: `-361025371366737575936`

**Comment by cyberliem** [comment]
This is due to the fact that bigInt.SetBytes as used [here](https://github.com/ethereum/go-ethereum/blob/62e94895da80838ec694b4ba19eeac80c9dc88c1/accounts/abi/unpack.go#L48) assume that the byte array represent positive number. Byte array to negative Big number is currently unsupported by math/big. Consider using custom arithmetic logic instead.

**Comment by karalabe** [comment]
Well, big.Int might not have a way to set a negative byte array, but we should most definitely be able to handle that case by explicitly pre/post processing the number.

**Comment by favadi** [comment]
I created #17583 to fix the wrong int256 unpack value.

**Comment by favadi** [comment]
As https://github.com/ethereum/go-ethereum/pull/17583 is merged, the issue is fixed.
