### ISSUE TITLE
Synchronisation failed, dropping peer    peer=9e76987ac684f8ad err=timeout

### ISSUE THREAD

**Issue by qings2329** [ethereum/go-ethereum#17569]
#### System information
Geth version: `1.8.15-stable-89451f7c`
OS & Version: Linux  Ubuntu 16.04.4 LTS

In log, there are a lot of "Synchronisation failed, dropping peer" message . My eth node syncs data very slowly, is hard to catch up with main net blocks. How to fix this ?

Some of log :

INFO [09-03|01:52:17.103] Imported new chain segment               blocks=17 txs=958  mgas=112.742 elapsed=9.081s    mgasps=12.414  number=6259586 hash=47029b…2e2e6e cache=536.36mB
INFO [09-03|01:52:24.096] Imported new chain segment               blocks=21 txs=1740 mgas=147.494 elapsed=6.993s    mgasps=21.091  number=6259607 hash=05881a…d15a4d cache=535.78mB
INFO [09-03|01:52:32.555] Imported new chain segment               blocks=10 txs=1020 mgas=66.433  elapsed=8.457s    mgasps=7.855   number=6259617 hash=c62d1f…6c7e49 cache=536.25mB
INFO [09-03|01:52:40.964] Imported new chain segment               blocks=28 txs=1927 mgas=155.006 elapsed=8.408s    mgasps=18.435  number=6259645 hash=c6b928…4f8ec8 cache=534.73mB
INFO [09-03|01:52:43.517] Imported new chain segment               blocks=9  txs=542  mgas=45.037  elapsed=2.553s    mgasps=17.640  number=6259654 hash=650977…6692c3 cache=533.38mB
INFO [09-03|01:52:51.685] Imported new chain segment               blocks=16 txs=1165 mgas=101.154 elapsed=8.166s    mgasps=12.387  number=6259670 hash=1dc746…fb288c cache=534.52mB
INFO [09-03|01:52:57.656] Imported new chain segment               blocks=25 txs=2234 mgas=142.704 elapsed=5.970s    mgasps=23.900  number=6259695 hash=26d9ed…d775b5 cache=535.82mB
INFO [09-03|01:53:03.357] Imported new chain segment               blocks=13 txs=1222 mgas=93.600  elapsed=5.700s    mgasps=16.421  number=6259708 hash=238f6a…bfef04 cache=536.07mB
WARN [09-03|01:53:13.472] Synchronisation failed, dropping peer    peer=73f80f432715009c err=timeout
WARN [09-03|01:54:25.355] Synchronisation failed, dropping peer    peer=41aa5896891b7af3 err=timeout
WARN [09-03|01:54:33.487] Synchronisation failed, dropping peer    peer=93891ff70e28ffeb err=timeout
WARN [09-03|01:54:43.086] Synchronisation failed, dropping peer    peer=2f48d8fadd6e958a err=timeout
WARN [09-03|01:54:50.083] Synchronisation failed, dropping peer    peer=2523968115d15c9e err=timeout
WARN [09-03|01:54:58.656] Synchronisation failed, dropping peer    peer=14a17a4feaf53248 err=timeout
WARN [09-03|01:55:42.601] Synchronisation failed, dropping peer    peer=713197792909aaca err=timeout
WARN [09-03|01:55:50.583] Synchronisation failed, dropping peer    peer=6a9fcd24294d4780 err=timeout
WARN [09-03|01:57:38.542] Synchronisation failed, dropping peer    peer=2baac1ac869b5398 err=timeout
WARN [09-03|01:57:45.278] Synchronisation failed, dropping peer    peer=f5a455ec2c5f7bf7 err=timeout
WARN [09-03|01:59:37.264] Synchronisation failed, dropping peer    peer=c0c24f9efecbf08b err=timeout
WARN [09-03|02:00:09.466] Synchronisation failed, dropping peer    peer=0e798a7bc5d81184 err=timeout
WARN [09-03|02:00:35.940] Synchronisation failed, dropping peer    peer=1b08e1d13cf1d3b0 err=timeout

**Comment by pkafei** [comment]
I'm also experiencing synchronization issues with the Geth Ropsten. When I start `geth`, geth hangs at `HTTP endpoint opened`.  Also `eth.syncing` in the console returns `false`.

Here is the command I enter in the cli
```
geth console --testnet --syncmode "fast" --rpc --rpcapi eth,net,web3 --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303"
```

### System
Geth version: 1.8.14
OS version: Mac High Sierra 10.13.6

**Comment by sivachaitanya** [comment]
timeout was happening for me on private network when all the cpu cores geth filled up

**Comment by ca42** [comment]
I am getting these warnings on main net as well.  I wrote a script that checks the output of  geth --exec "eth.syncing" attach /<path_to>/geth.ipc every few seconds.  The output from the script is telling me that geth is out-of-sync more often than when I get the WARN messages, though I'm still a little new with geth so I'm not sure that the check I'm doing is valid.  Basically, I would expect "eth.syncing" to be "false" unless I see the WARN message.  At first I thought I need more resources as I'm using an AWS instance, but I see there are other people with this issue (it could still be resource-related though).  Hopefully someone has some insight.

**System**
Geth Version: 1.8.15-stable
OS version: Ubuntu 16.04.5 LTS
AWS instance types: t2.medium and t3.medium
