### ISSUE TITLE
Geth using 100% CPU even on starting with 1 miner thread

### ISSUE THREAD

**Issue by sivachaitanya** [ethereum/go-ethereum#17575]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth
Version: 1.8.16-unstable
Git Commit: 62e94895da80838ec694b4ba19eeac80c9dc88c1
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.3
Operating System: linux
GOPATH=$HOME/go
GOROOT=/usr/local/go

System config - 8vCPU, 16GB RAM, 30 GB SDD

minewhenneeded.js script - 
var mining_threads = 1

    function checkWork() {
        if (eth.getBlock("pending").transactions.length > 0) {
            if (eth.mining) return;
            console.log("== Pending transactions! Mining...");
            miner.start(mining_threads);
        } else {
            miner.stop();
            console.log("== No transactions! Mining stopped.");
        }
    }
    console.log("checkWork() is defined");
    eth.filter("latest", function(err, block) { checkWork(); });
    eth.filter("pending", function(err, block) { checkWork(); });

    checkWork();

#### Expected behaviour
I have launched geth with command ->  geth --mine --minerthreads 1  --rpc --rpcport "8545" --rpccorsdomain "*"  --rpc --rpcaddr "10.0.18.4" --datadir ./datadir --port "30306" --rpcapi "db,eth,net,web3,personal,miner,admin"  --ws --wsaddr "10.0.18.4" --wsorigins "*" --networkid 39923 --nat "any" js  './minewhenneeded.js' and submitted some transactions after deploying a smart contract which should only use 1 cpu core as geth launched with to use 1 mining thread for any number of transactions

#### Actual behaviour
At the launch for a while it uses 1 thread and gradually it uses all the cpu cores at 100% even after I submitted the transactions

#### Steps to reproduce the behaviour
1. Start any private network
2. Launch the geth with the command and the minewhenneeded.js script that I have provided
3. Make a few transactions on any simple smart contract

#### Backtrace
Na

**Comment by rjl493456442** [comment]
For your js script:

```
var mining_threads = 1

function checkWork() {
	if (parseInt(txpool.status.pending) > 0) {
		if (eth.mining){
			miner.stop();
			return;
		}
		console.log("== Pending transactions! Mining...");
		miner.start(mining_threads);
	} else {
		miner.stop();
		console.log("== No transactions! Mining stopped.");
	}
}

eth.filter("latest", function(err, block) { checkWork(); });
eth.filter("pending", function(err, block) { checkWork(); });

checkWork();
```

It is a little bit weird. `if(eth.mining)`, should it return directly? Why should we stop the mining?

**Comment by sivachaitanya** [comment]
yeah please ignore the js script, even if we dont preload the script the cpu core usage spikes to 100%, can you help me resolve it ?

**Comment by sivachaitanya** [comment]
anyway caught the issue because of giving the fast sync flag, if I remove that all good, cheers !

**Comment by sivachaitanya** [comment]
Actually I thought passing the fast syncmode flag was causing the all cpu cores usage, I removed passing the js script file and now my command is like - nohup geth --mine --minerthreads=1  --rpc --rpcport "8545" --rpccorsdomain "*"  --rpc --rpcaddr "10.0.18.4" --datadir ./datadir --port "30306" --rpcapi "db,eth,net,web3,personal,miner,admin"  --ws --wsaddr "10.0.18.4" --wsorigins "*" --networkid 39923  &  and still I'm facing high cpu usage

**Comment by sivachaitanya** [comment]
@rjl493456442  I have updated the actual js script which I'm passing when launching the geth. Even without it I'm having the high cpu usage @karalabe

**Comment by sivachaitanya** [comment]
This is the log while the cpu cores are 100% used, clearly my private net is getting connection requests from public nodes that are hardcoded in the client code maybe - 

TRACE[09-05|07:02:49.206] Accepted connection                      addr=110.79.11.29:47446
TRACE[09-05|07:02:49.207] Failed RLPx handshake                    addr=110.79.11.29:47446    conn=inbound err="ecies: invalid message"
TRACE[09-05|07:02:49.207] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|07:02:50.014] Accepted connection                      addr=52.87.208.2:49112
TRACE[09-05|07:02:50.033] Failed RLPx handshake                    addr=52.87.208.2:49112     conn=inbound err="ecies: invalid message"
TRACE[09-05|07:02:50.033] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|07:02:50.073] Accepted connection                      addr=130.192.157.165:52224
TRACE[09-05|07:02:50.074] Failed RLPx handshake                    addr=130.192.157.165:52224 conn=inbound err="ecies: invalid message"
TRACE[09-05|07:02:50.074] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|07:02:51.525] Accepted connection                      addr=54.191.170.9:50010
TRACE[09-05|07:02:51.526] Failed RLPx handshake                    addr=54.191.170.9:50010    conn=inbound err="ecies: invalid message"
TRACE[09-05|07:02:51.526] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|07:02:51.946] Accepted connection                      addr=40.83.72.16:55758
TRACE[09-05|07:02:51.946] Failed RLPx handshake                    addr=40.83.72.16:55758     conn=inbound err="ecies: invalid message"
TRACE[09-05|07:02:51.946] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|07:02:52.248] Accepted connection                      addr=208.54.240.134:59162
TRACE[09-05|07:02:52.248] Failed RLPx handshake                    addr=208.54.240.134:59162  conn=inbound err="ecies: invalid message"
TRACE[09-05|07:02:52.248] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|07:02:52.933] Accepted connection                      addr=54.93.218.190:59466
TRACE[09-05|07:02:52.953] Failed RLPx handshake                    addr=54.93.218.190:59466   conn=inbound err="ecies: invalid message"
TRACE[09-05|07:02:52.953] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|07:02:53.013] Accepted connection                      addr=101.86.117.240:48948
TRACE[09-05|07:02:53.014] Failed RLPx handshake                    addr=101.86.117.240:48948  conn=inbound err="ecies: invalid message"
TRACE[09-05|07:02:53.014] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|07:02:53.577] Accepted connection                      addr=178.170.102.139:34585
TRACE[09-05|07:02:53.578] Failed RLPx handshake                    addr=178.170.102.139:34585 conn=inbound err="ecies: invalid message"
TRACE[09-05|07:02:53.578] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|07:02:54.987] Accepted connection                      addr=148.251.10.100:52538
TRACE[09-05|07:02:54.988] Failed RLPx handshake                    addr=148.251.10.100:52538  conn=inbound err="ecies: invalid message"
TRACE[09-05|07:02:54.988] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|07:02:55.724] Accepted connection                      addr=86.57.162.8:42338
TRACE[09-05|07:02:55.959] Accepted connection                      addr=138.197.186.92:60622
TRACE[09-05|07:02:55.960] Failed RLPx handshake                    addr=138.197.186.92:60622  conn=inbound err="ecies: invalid message"
TRACE[09-05|07:02:55.960] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|07:02:56.894] Accepted connection                      addr=165.227.9.111:52118
TRACE[09-05|07:02:56.894] Failed RLPx handshake                    addr=165.227.9.111:52118   conn=inbound err="ecies: invalid message"
TRACE[09-05|07:02:56.895] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|07:02:57.538] Accepted connection                      addr=198.50.175.75:52512
TRACE[09-05|07:02:58.172] Accepted connection                      addr=168.61.190.208:1216
TRACE[09-05|07:02:58.173] Failed RLPx handshake                    addr=168.61.190.208:1216   conn=inbound err="ecies: invalid message"
TRACE[09-05|07:02:58.173] Setting up connection failed             id=0000000000000000 err="ecies: invalid message"
TRACE[09-05|07:03:00.651] Failed RLPx handshake                    addr=86.57.162.8:42338     conn=inbound err=EOF
TRACE[09-05|07:03:00.651] Setting up connection failed             id=0000000000000000 err=EOF


Can you guys help me how can I avoid alien nodes making any connections to my private network

**Comment by sivachaitanya** [comment]
#15358

**Comment by sivachaitanya** [comment]
#15358 this is related to my issue

**Comment by sivachaitanya** [comment]
closing because the hack shared in issue 15358 worked
