### ISSUE TITLE
Cannot sync rinkeby network (fatal error: runtime: out of memory)

### ISSUE THREAD

**Issue by samaujs** [ethereum/go-ethereum#17577]
Hi,

I have problem syncing Rinkeby testnet since 9 Aug 2018 and encountered the same out of memory problem. It has worked previously.  I have tried couple of times and realised that it always fail around the same spot (refer to details below).  Please assist. Thank you.

#### System information
Geth Version: 1.8.15-stable
OS & Version: Ubuntu 16.04.5 LTS (GNU/Linux 4.14.20-041420-generic x86_64)
Git Commit: 89451f7
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
Running Ubuntu 16.04.5 LTS (GNU/Linux 4.14.20-041420-generic x86_64) on AWS T2.medium instance with 128GB

#### Expected behaviour
It should sync but fails around the same block header 2867865 and always rollback to block header 2837951.

#### Actual behaviour
INFO [09-04|04:06:44.440] Initialising Ethereum protocol versions="[63 62]" network=4
WARN [09-04|04:06:44.448] Head state missing, repairing chain number=2867862 hash=1e6e59…0a36ff
INFO [09-04|04:07:08.704] Rewound blockchain to past state number=2837951 hash=635371…0df25a
INFO [09-04|04:07:08.715] Loaded most recent local header number=**2867865** hash=6fb6b1…b8cde5 td=5382446
INFO [09-04|04:07:08.716] Loaded most recent local full block number=**2837951** hash=635371…0df25a td=5338101
INFO [09-04|04:07:08.716] Loaded most recent local fast block number=2867865 hash=6fb6b1…b8cde5 td=5382446
INFO [09-04|04:07:08.716] Loaded local transaction journal transactions=0 dropped=0
INFO [09-04|04:07:08.716] Regenerated local transaction journal transactions=0 accounts=0
WARN [09-04|04:07:08.716] Blockchain not empty, fast sync disabled
...

#### Steps to reproduce the behaviour
geth --rinkeby --rpc --rpcport "8545" --rpccorsdomain "*" --rpcapi="personal,eth,network,web3,net" --ipcpath "~/.ethereum/geth.ipc"

**Comment by holiman** [comment]
Please provide actual stack trace from the crash. I suspect it's the fact that you expose `personal` over internet, and people try  to unlock you nodes.
