### ISSUE TITLE
Why we can't send ether to ethereum address 0x1 via smart contracts

### ISSUE THREAD

**Issue by ChandraNakka** [ethereum/go-ethereum#17572]
With this below solidity code I have tried to send ether to ethereum wallet address **0x1** via smart contract and it becomes failed. But, when I try to send ether to address **0x1** directly from my wallet it becomes success.

    pragma solidity ^0.4.24;
    
    contract Transfer {
        
        constructor () public payable {
            // Deploy contract with 1000 wei for testing purpose
            require(msg.value == 1000);
        }
        
        function done() public {
            address(0).transfer(1); // Transaction success
        }
        
        function fail() public {
            address(1).transfer(1); // Transaction failed
        }
        
        function send(address account) public {
            account.transfer(1); // Transaction success (except 0x1)
        }
        
    }

> Why we can't send ether to address **0x1** via contracts ?

**REFERENCE:**

1. Sending ether directly from my wallet is success
https://ropsten.etherscan.io/tx/0x1fdc3a9d03e23b0838c23b00ff99739b775bf4dd7b5b7f2fa38043056f731cdc

2. done() function is success
https://ropsten.etherscan.io/tx/0xd319c40fcf50bd8188ae039ce9d41830ab795e0f92d611b16efde0bfa1ee82cd

3. fail() function is failed
https://ropsten.etherscan.io/tx/0x0c98eafa0e608cfa66777f1c77267ce9bdf81c6476bdefe2a7615158d17b59ad

**Comment by holiman** [comment]
It is because `0x1` is a precompile, namely the `ecRecover` precompile. The cost for ecRecover is `3000` gas, which a `transfer` afaik does not cover.

**Comment by holiman** [comment]
As you can see from https://ropsten.etherscan.io/tx/0x1fdc3a9d03e23b0838c23b00ff99739b775bf4dd7b5b7f2fa38043056f731cdc , it used `24000` gas, as opposed to `21000` which a send of value to a 'normal' account would cost.

**Comment by smalaichami** [comment]
Yes..normal transaction costs less.  You would have to try with higher gaslimit for contract transactions.

**Comment by ChandraNakka** [comment]
@smalaichami sir, please checkout failed transaction. I have used 3,000,000 gas limit.

**Comment by holiman** [comment]
> I have used 3,000,000 gas limit. 

Yes, on the outer transaction. The solidity-construct `transfer` does a `CALL` under the hood, and that `CALL` only has enough gas for outputting a log. It does not forward all gas, to prevent re-entrancy problems. `transfer` also handles error-conditions, so that if the `CALL` (transfer of ether) is unsuccessfull, it throws.

**Comment by holiman** [comment]
See https://solidity.readthedocs.io/en/v0.4.21/security-considerations.html?highlight=transfer . The receiver has `2300` gas available, but would need `3000` to not go OOG.

**Comment by ChandraNakka** [comment]
@holiman thanks a lot for your detailed explanation
