### ISSUE TITLE
why orphan block?

### ISSUE THREAD

**Issue by 200787128** [ethereum/go-ethereum#17570]
why  block lost ?
this node all miner block  are orphan block

geth log

INFO [09-03|01:27:27.320] 🔨 mined potential block                  number=6259651 hash=a68b83…112307
INFO [09-03|01:27:27.322] Commit new mining work                   number=6259652 sealhash=3ee3da…d9e517 uncles=0 txs=0    gas=0       fees=0              elapsed=535.766µs
INFO [09-03|01:27:27.323] Commit new mining work                   number=6259652 sealhash=22fa87…773eec uncles=0 txs=1    gas=21000   fees=0.000714       elapsed=1.226ms
INFO [09-03|01:27:35.360] Commit new mining work                   number=6259652 sealhash=9a97d0…3acfa5 uncles=0 txs=6    gas=195175  fees=0.00511044     elapsed=13.177ms
INFO [09-03|01:27:35.941] Generating DAG in progress               epoch=208 percentage=0 elapsed=6.150s
INFO [09-03|01:27:36.945] Imported new chain segment               blocks=1  txs=91   mgas=7.988   elapsed=1.611s    mgasps=4.959  number=6259651 hash=66b050…84686d cache=267.57mB
INFO [09-03|01:27:36.947] Commit new mining work                   number=6259652 sealhash=137f84…227f8c uncles=1 txs=6    gas=195175  fees=0.00511044     elapsed=1.717ms
INFO [09-03|01:27:42.439] Generating DAG in progress               epoch=208 percentage=1 elapsed=12.648s
INFO [09-03|01:27:43.401] Commit new mining work                   number=6259652 sealhash=2d3cf2…74d735 uncles=1 txs=16   gas=516780  fees=0.01424143859  elapsed=42.244ms
INFO [09-03|01:27:48.200] Generating DAG in progress               epoch=208 percentage=2 elapsed=18.408s
INFO [09-03|01:27:50.504] Imported new chain segment               blocks=1  txs=92   mgas=7.998   elapsed=1.238s    mgasps=6.460  number=6259652 hash=8a9592…453183 cache=267.78mB
INFO [09-03|01:27:50.507] Commit new mining work                   number=6259653 sealhash=c757c8…90ddc1 uncles=0 txs=0    gas=0       fees=0              elapsed=838.311µs
INFO [09-03|01:27:50.559] Commit new mining work                   number=6259653 sealhash=59093c…0d2ca1 uncles=0 txs=23   gas=809455  fees=0.02261997459  elapsed=53.065ms
INFO [09-03|01:27:50.565] Commit new mining work                   number=6259653 sealhash=e82104…702da3 uncles=1 txs=23   gas=809455  fees=0.02261997459  elapsed=4.709ms
INFO [09-03|01:27:51.732] Imported new chain segment               blocks=1  txs=125  mgas=5.760   elapsed=259.388ms mgasps=22.206 number=6259652 hash=945ba3…ba84cc cache=267.87mB
INFO [09-03|01:27:51.746] Commit new mining work                   number=6259653 sealhash=d4d264…0e9b05 uncles=2 txs=0    gas=0       fees=0              elapsed=561.494µs
INFO [09-03|01:27:51.768] Commit new mining work                   number=6259653 sealhash=12c801…73bd75 uncles=2 txs=24   gas=830455  fees=0.02333397459  elapsed=21.974ms
INFO [09-03|01:27:54.451] Generating DAG in progress               epoch=208 percentage=3 elapsed=24.660s
INFO [09-03|01:27:59.797] Commit new mining work                   number=6259653 sealhash=19d02d…34df0a uncles=2 txs=29   gas=983343  fees=0.02904318459  elapsed=43.996ms
INFO [09-03|01:28:00.882] Generating DAG in progress               epoch=208 percentage=4 elapsed=31.091s
INFO [09-03|01:28:07.161] Generating DAG in progress               epoch=208 percentage=5 elapsed=37.370s
INFO [09-03|01:28:08.147] Commit new mining work                   number=6259653 sealhash=1f0a4c…4b28c2 uncles=2 txs=40   gas=1371093 fees=0.04068854409  elapsed=362.426ms
INFO [09-03|01:28:14.862] Imported new chain segment               blocks=1  txs=63   mgas=1.921   elapsed=373.930ms mgasps=5.137  number=6259653 hash=38e28e…4ef512 cache=267.43mB
INFO [09-03|01:28:14.863] Commit new mining work                   number=6259654 sealhash=fa6b30…5cb97f uncles=2 txs=0    gas=0       fees=0              elapsed=1.264ms
INFO [09-03|01:28:14.893] Commit new mining work                   number=6259654 sealhash=d6b3e0…67d7fb uncles=2 txs=13   gas=595186  fees=0.014080995    elapsed=31.070ms
INFO [09-03|01:28:15.701] Generating DAG in progress               epoch=208 percentage=6 elapsed=45.909s
INFO [09-03|01:28:21.644] Generating DAG in progress               epoch=208 percentage=7 elapsed=51.853s
INFO [09-03|01:28:21.787] Imported new chain segment               blocks=1  txs=11   mgas=0.553   elapsed=70.884ms  mgasps=7.804  number=6259654 hash=650977…6692c3 cache=266.67mB
INFO [09-03|01:28:21.852] Commit new mining work                   number=6259655 sealhash=1781ea…f15f50 uncles=1 txs=0    gas=0       fees=0              elapsed=545.961µs
INFO [09-03|01:28:21.928] Commit new mining work                   number=6259655 sealhash=4c5983…238b14 uncles=1 txs=12   gas=441235  fees=0.01439137971  elapsed=77.197ms
INFO [09-03|01:28:27.707] Generating DAG in progress               epoch=208 percentage=8 elapsed=57.916s
INFO [09-03|01:28:29.882] Commit new mining work                   number=6259655 sealhash=fa55e1…9f75bf uncles=1 txs=18   gas=642174  fees=0.02041541634  elapsed=27.760ms
INFO [09-03|01:28:32.854] Imported new chain segment               blocks=1  txs=140  mgas=7.978   elapsed=1.521s    mgasps=5.245  number=6259655 hash=624fc1…31ce5f cache=267.60mB
INFO [09-03|01:28:32.886] Commit new mining work                   number=6259656 sealhash=6f2997…3d0803 uncles=1 txs=0    gas=0       fees=0              elapsed=1.276ms
INFO [09-03|01:28:33.202] Commit new mining work                   number=6259656 sealhash=21076b…e65ffb uncles=1 txs=9    gas=474462  fees=0.01659910478  elapsed=316.865ms
INFO [09-03|01:28:33.731] Imported new chain segment               blocks=1  txs=244  mgas=7.984   elapsed=877.514ms mgasps=9.099  number=6259655 hash=66f792…2feb79 cache=267.86mB
INFO [09-03|01:28:33.753] Commit new mining work                   number=6259656 sealhash=80b017…9e8eeb uncles=2 txs=0    gas=0       fees=0              elapsed=909.514µs
INFO [09-03|01:28:33.775] Commit new mining work                   number=6259656 sealhash=fa232f…646937 uncles=2 txs=9    gas=474260  fees=0.01659064904  elapsed=22.937ms
INFO [09-03|01:28:34.534] Generating DAG in progress               epoch=208 percentage=9 elapsed=1m4.742s
INFO [09-03|01:28:36.290] Imported new chain segment               blocks=1  txs=51   mgas=7.985   elapsed=947.209ms mgasps=8.430  number=6259656 hash=d67cb0…c4ed44 cache=268.08mB
INFO [09-03|01:28:36.307] Commit new mining work                   number=6259657 sealhash=d404b9…135adf uncles=2 txs=0    gas=0       fees=0              elapsed=1.197ms
INFO [09-03|01:28:36.356] Commit new mining work                   number=6259657 sealhash=9e9310…229475 uncles=2 txs=2    gas=55148   fees=0.001702733503 elapsed=50.240ms
INFO [09-03|01:28:40.654] Generating DAG in progress               epoch=208 percentage=10 elapsed=1m10.862s
INFO [09-03|01:28:40.995] Imported new chain segment               blocks=1  txs=54   mgas=7.978   elapsed=808.191ms mgasps=9.872  number=6259657 hash=dce8f5…8a8497 cache=267.52mB
INFO [09-03|01:28:40.998] Commit new mining work                   number=6259658 sealhash=18e44b…0d9e5d uncles=0 txs=0    gas=0       fees=0              elapsed=755.251µs
INFO [09-03|01:28:41.036] Commit new mining work                   number=6259658 sealhash=a17839…9b6b43 uncles=0 txs=9    gas=349635  fees=0.009918517469 elapsed=39.001ms
INFO [09-03|01:28:42.496] Imported new chain segment               blocks=1  txs=57   mgas=7.985   elapsed=533.255ms mgasps=14.974 number=6259657 hash=8b824a…b4f229 cache=267.65mB
INFO [09-03|01:28:42.498] Commit new mining work                   number=6259658 sealhash=705ead…81dd1a uncles=1 txs=9    gas=349635  fees=0.009918517469 elapsed=2.316ms
INFO [09-03|01:28:46.776] Generating DAG in progress               epoch=208 percentage=11 elapsed=1m16.985s
INFO [09-03|01:28:49.035] Commit new mining work                   number=6259658 sealhash=42a67a…79cc4e uncles=1 txs=15   gas=537692  fees=0.0216382517   elapsed=18.491ms
INFO [09-03|01:28:50.353] Imported new chain segment               blocks=1  txs=7    mgas=0.250   elapsed=69.319ms  mgasps=3.612  number=6259658 hash=6cd35f…cdeb80 cache=266.81mB
INFO [09-03|01:28:50.500] 😱 block lost                             number=6259651 hash=a68b83…112307

Geth version: `1.8.15`
OS & Version: Linux
Commit hash : (if `develop`)

**Comment by rjl493456442** [comment]
Could you please check the peer number for your geth node?  It seems that your geth node is not well connected to the p2p network since there are about 60K pending transactions while your node cannot fill the block every time.

If the block you mine can't be passed to other miner nodes through the p2p network within 7 blocks, then your block may become an orphan block.

**Comment by 200787128** [comment]
The number of nodes is 50 +, no block out of the case of synchronous data are OK, only when the block out of the time like this. How do I check if the node is filled with OK?

**Comment by 200787128** [comment]
This problem occurs in geth versions 1.8.14 and 1.8.15, but 1.8.11-1.8.13 is OK, the same device, the same environment

**Comment by rjl493456442** [comment]
It is because the warning log is added in the v1.8.15. In the previous version, maybe your node lost the reward silently.

**Comment by 200787128** [comment]
No, the 1.8.15 test was block loss every time, but 1.8.11 is now running without block loss. I recorded result, target while I was running Verify block, and I'm sure 1.8.11 didn't lose blocks. I record every time I put out the blocks.。Unless it's synchronized to the uncle bolck.

**Comment by 200787128** [comment]
1.8.14 test  block lost 2block 1.8.15 test block lost 4 block Now I dare not test.
