### ISSUE TITLE
bootnode -writeaddress is not working

### ISSUE THREAD

**Issue by kinfkong** [ethereum/go-ethereum#17579]
When I run command:
`/usr/local/bin/bootnode -genkey /tmp/tmp.txt -writeaddress`
The -writeaddress is not working (no address output).
I view the code:
there is a `return` statement in the switch branch when -genkey is provided.
That is wrong.
See the following code line:
https://github.com/ethereum/go-ethereum/blob/6a33954731658667056466bf7573ed1c397f4750/cmd/bootnode/main.go#L72

**Comment by kinfkong** [comment]
join

**Comment by dherbst** [comment]
I added the above PR #20110 that should fix this issue.

**Comment by dherbst** [comment]
@fjl thanks for merging!   Please consider closing this issue if there is no other work to be done.
