### ISSUE TITLE
ERROR write tcp 172.33.71.22:8000->213.202.242.16:60234: i/o timeout

### ISSUE THREAD

**Issue by wangchaozhong** [ethereum/go-ethereum#17584]
System information
Geth version: 1.8.15-stable-89451f7c
OS & Version: Linux Ubuntu 16.04.4 LTS

ERROR[09-05|01:40:43.976] write tcp 172.33.71.22:8000->213.202.242.16:60234: i/o timeout

Please tell me the solution   
thanks

**Comment by sivachaitanya** [comment]
yeah I used to have the same problem, how is your cpu usage while geth is running ?, This happened to me when all my 8 cores of cpu are filled up 100%

**Comment by wangchaozhong** [comment]
@sivachaitanya   My solution is to switch ports. --port 8001  --rpcport 8003

**Comment by fangvv** [comment]
@wangchaozhong Did you solve this problem? And did this problem happen again?

**Comment by karalabe** [comment]
Based on the error message `write tcp 172.33.71.22:8000->213.202.242.16:60234: i/o timeout`, Geth is actually timing out writing to your client. Apparently your client is not reading the response.
