### ISSUE TITLE
Rinkeby Faucet offline: context deadline exceeded

### ISSUE THREAD

**Issue by andrewnguyen22** [ethereum/go-ethereum#17596]
Faucet offline again, @karalabe maybe restart?

![screen shot 2018-09-06 at 8 42 09 am](https://user-images.githubusercontent.com/18633790/45158034-cd358f80-b1b0-11e8-9385-2fd6f73c98a7.png)

**Comment by zelic91** [comment]
Same here

**Comment by ligi** [comment]
Sorry for the probelm. Please post your addresses - I can play manual faucet again. 
Unfortunately there was a problem with rinkeby - some details here: https://blog.infura.io/rinkeby-consensus-post-mortem-4abbcace0539
Unfortunately the faucet did not yet recover from the problem and @karalabe who knows how to solve it is in holiday/transit. When he is back we will increase this bus-factor of 1 to >=2
Also I hope one outcome of ETHBerlin will be that we get a second/backup faucet - see: https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/8
Sorry again and please post your addresses and how much rinkeby eth you need and I will give you some from my stash.

**Comment by andrewnguyen22** [comment]
I figured it had something to do with the recent problems. Thanks for the offer but I have plenty of rinkeby eth for now. Just thought I would bring this issue up with the devs

**Comment by zelic91** [comment]
Hi @ligi, 

could you please give me 3 ethers to this address: `0x2dfccea1325e3ced75cf25ca2b2f415552bfe2fb`?

Thank you.

**Comment by puneetkumar10** [comment]
Hi @zelic91 ,
transferred ethers to 0x2dfccea1325e3ced75cf25ca2b2f415552bfe2fb , post here if you need few more.

**Comment by dujki12** [comment]
Hi,

could you please give me 18.75 ethers to this address: 0x14391953AdDd7a5F94B6EAd4e2727eaf5304D00A?

Thank you.

**Comment by PudiccaA** [comment]
Hi,

Could you please give me 18.75 ethers to this address:
0x5C491907D8078F697089297eF1550338F7410043

Thank you!

**Comment by ligi** [comment]
@dujki12  @PudiccaA : you both have your rinkeby eth now
@puneetkumar10 : thanks for bridging the gap - was busy with ETHBerlin

**Comment by puneetkumar10** [comment]
@ligi no prob, it feels great to help community members.
@PudiccaA ethers transferred.

**Comment by PudiccaA** [comment]
@ligi @puneetkumar10 Thank you very much! Was learning and testing out some smart contracts.

**Comment by MKhere** [comment]
Hi,

Could you please give 15 ethers ASAP to this address:
0x3222f8e765c3e0671E2d059b0c14a3936Ce1F419

Thank you!

**Comment by puneetkumar10** [comment]
@MKhere ethers transferred to 0x3222f8e765c3e0671E2d059b0c14a3936Ce1F419

**Comment by MKhere** [comment]
@puneetkumar10 
many thanks!

**Comment by Maxcutex** [comment]
@puneetkumar10  could you please give 18.75 ethers to this address so i can use : 0x8a2BA66377C2Bb43c06939dDA72b2ac5B78bFD1c

**Comment by ligi** [comment]
faucet is back online - thanks to @karalabe

**Comment by dujki12** [comment]
@ligi thanks :)

**Comment by vanicci** [comment]
Hi @puneetkumar10 & @ligi,

I'm still seeing **"Faucet Offline: context deadline exceeded"** in https://www.rinkeby.io/#faucet

Could you please give 18.75 ethers to this address so i can use for education purposes? 
0x904340f7F151E166489801f1b3b433eb6678d7A9 

Thank you in advance.

**Comment by shubhamoy** [comment]
Could anyone please send 5 ethers to 0x297380a389748c14b99c58961b3d6604c0bc9e23 

TIA

**Comment by ligi** [comment]
@vanicci @shubhamoy the faucet is back online

**Comment by toorajhelmi** [comment]
Can somebody donate dome ETH to my account pls? 0xc998ac75d5e5f171e358cb2f9aeb9738a92027d50

**Comment by pradyot-09** [comment]
could anybody please send 3 ethers to 0xaD05278e8BbF4E0dA9DE773132189F0171B689Fe, I have to demonstrate a project tomorrow deploying my contract on rinkeby testnet  and unfortunately faucet is offline.

Thank you!

**Comment by puneetkumar10** [comment]
> could anybody please send 3 ethers to 0xaD05278e8BbF4E0dA9DE773132189F0171B689Fe, I have to demonstrate a project tomorrow deploying my contract on rinkeby testnet and unfortunately faucet is offline.
> 
> Thank you!

Done! Good Luck for demonstration.

**Comment by pradyot-09** [comment]
> > could anybody please send 3 ethers to 0xaD05278e8BbF4E0dA9DE773132189F0171B689Fe, I have to demonstrate a project tomorrow deploying my contract on rinkeby testnet and unfortunately faucet is offline.
> > Thank you!
> 
> Done! Good Luck for demonstration.

you saved me! thanks.

**Comment by nishant-khanorkar** [comment]
Can anyone please send 12 ethers to 0xAccF0024D56f75d9f8Bc490a86f3EC06e2B14e50
It's urgent..

**Comment by GemVaultCoin** [comment]
Please send me 10ETH to 0x6e617119909b5a03dc381c16eb68846f6cb458c1

**Comment by ligi** [comment]
@nishant-khanorkar  @GemVaultCoin funds send

https://rinkeby.etherscan.io/tx/0x20eb8561f0e89c04c73b900b5538e9ea3e864fa1f1930ca8382693840f84d73e
https://rinkeby.etherscan.io/tx/0xf8d9c524726715966b24d4dde9fc422aa18d95c2e6ccc585cc5206bc24350c8e

**Comment by latticegold** [comment]
hi, faucet is giving this same error for me.  can anyone please send 10 eth to  0x1F0fE5a31483F7c096CE1A1ED07aDC088Ec147B5 ? thanks

**Comment by richfolsom** [comment]
I'm getting the same error can anyone please send 3 eth to 
0x33A90008f89E0D0f6eA8488F31f9Af5445C51A3c  ? Thanks!

**Comment by ligi** [comment]
@richfolsom https://rinkeby.etherscan.io/tx/0xc68ae184632a48c7ec53d0b581d0b38cd5f00bb376d7c82d2f255fabd4d2ac77

@latticegold https://rinkeby.etherscan.io/tx/0xa18add0cc7ac0aa8bc926e4af3971a0ada46718bef5b7a909a33f856175db077

**Comment by puneetkumar10** [comment]
> Same here,
> Can anyone please send 3 eth to
> 0xa7a7a34d1cd1888036261cc6d30b7dcde2b83382 thanks in advance :)

Transferred.

**Comment by KarmaGut** [comment]
I'm getting the same issue in https://faucet.rinkeby.io/.Could you please send me 3 eth to 0xa1260A5c42A211652C3cbe5d12A592754EB0D477. Thanks a lot~

**Comment by akshaysrivastav** [comment]
I'm still seeing "Faucet Offline: context deadline exceeded" in https://www.rinkeby.io/#faucet

Could you please give 18.75 ethers to this address so i can use for education purposes?
0xf4388f88eb639ef8eaf305a7a6f343c0955d3f06

Thank you in advance.

**Comment by karalabe** [comment]
We've reworked the internals of the Rinkeby faucet. It should be able to handle a much larger load form now on without constantly hammering LES (causing the deadline exceeded and sync issues). Should be ok now for everyone. Please take a look.

**Comment by hudsonsantos** [comment]
Hi, please send 10 eth to 0xf7613d84290b1330be5c946f4e2b221521b57656? Thank you.

**Comment by ligi** [comment]
@hudsonsantos isn't the faucet working for you?

**Comment by hudsonsantos** [comment]
I'm trying to accomplish through the site: http://www.rinkeby-faucet.com/
but I get the message: Too many requests, please try again later.

**Comment by ligi** [comment]
this is the wrong url (how did you stumble over this one?) - this is the correct url: https://faucet.rinkeby.io/

**Comment by hudsonsantos** [comment]
of a course I'm doing blockchain.
I'm doing something wrong. In this new URL, you are giving me the following message:
URL does not link to supported services.
My andress is :
0xf7613d84290b1330be5c946f4e2b221521b57656

I get service with:
geth --rinkeby --rpc --rpcapi="eth,net,web3,personal,txpool" --syncmode=light

**Comment by hudsonsantos** [comment]
Hi, I posted in my facebook the andress of my account. after that, I solicited  the site   give me ether for 8 hours.
The ether here is running.
In geth attach, eth.getBalance ("0xf7613d84290b1330be5c946f4e2b221521b57656") is
0

**Comment by sammyl720** [comment]
can some one send me rinkeby ether 0x9B39a53168A019eD1E8ff67A1b138f14006220DF . The rinkeby faucet seems to be offline https://faucet.rinkeby.io/ . Would appreciate it. Thanks

**Comment by LiJu21** [comment]
could you please send me some ethers 0x9c80757bF80a728C2B68903f18e7F757109F858A. The rinkeby faucet is offline. Thank you so much

**Comment by dmrschmidt** [comment]
I'll just queue in here as well, asking for a kind rinkeby donation: 0xB54E19B57a0F98a7A0E9A5262209aabBE9fe1516. Tried different sources, but to no avail and that faucet is down for a day now it seems. Appreciate it

**Comment by klahaeck** [comment]
18.75 ETH here please 0x2187a4CDD5D4923c95ef9ca1Ee1c62B95CcFb9d4

thank you!

**Comment by zjw2021** [comment]
Could someome please send be 18.75 ETH, the Rineby Faucet appears to be offline, Thanks! 0x555C51855117827C904a2CCB5861826d35543659

**Comment by 90hacker** [comment]
Could someome please send be 18.75 ETH, the Rineby Faucet appears to be offline, Thanks!
0x9bB69e4dDDA0a1865FEC3ba828787E6f886750F7

**Comment by PsychoNarc** [comment]
Hi, can anyone please send 18.5 test ethers?? Rinkeby Faucet appears to be offline. Thanks a bunch.
0x795f08DFC6a95210100f8ba49B4f8eb124f9654C

**Comment by ntb19132** [comment]
Hi, Can anyone please send 18.5 test ethers?? Rinkeby Faucet appears to be offline. Thanks 
0x0c30020E0f2eb6A99Da22945F9215c9e1FB7F2fc
