### ISSUE TITLE
rinkeby has not generated new block for a few hours

### ISSUE THREAD

**Issue by hippokylejan** [ethereum/go-ethereum#17593]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth v1.8.5`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
rinkeby testnet should generate new blocks per 10 seconds generally

#### Actual behaviour
rinkey testnet has not generated new block for a few hours

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
Thanks, we're aware. It's running again, but a hotfix will be made. For now, 1.8.13 is a safe bet to use. A clique-specific consensus error was introduced in 1.8.14
