### ISSUE TITLE
traceBlock aborts if a sender can't afford gas

### ISSUE THREAD

**Issue by emile** [ethereum/go-ethereum#17590]
The trace results from all other transactions in a block are currently discarded if any fail with an "insufficient balance to pay for gas" error. It should be possible to trace all non-failing transactions in a block using traceBlock, even if some of them fail the state transition precheck.

#### System information

Geth version: 1.8.15-stable
OS & Version: Linux

#### Expected behaviour
```
[{result: {failed: false, ...}},
 {result: {failed: false, ...}},
 {result: {failed: true, ...}}]
```
or 
```
 [{result: {failed: false, ...}},
  {result: {failed: false, ...}},
  {error: "tracing failed: insufficient balance to pay for gas"}]
``` 
#### Actual behaviour
```
Error: insufficient balance to pay for gas
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```
#### Steps to reproduce the behaviour
debug.traceBlockByNumber("0xDFCA7")
debug.traceBlockByNumber("0x1777C0")
debug.traceBlockByNumber("0x19D845")
debug.traceBlockByNumber("0x282C18")

**Comment by firewicca** [comment]
##your welcome 🙏 #15358

**Comment by bem7** [comment]
I also just bumped into this issue, specifically for blocks 916647 and 1693765. However, according to Etherscan, no transactions in these had errors. 

I'm also using `debug.traceBlockByNumber`.

**Comment by Eric-Showers** [comment]
Hi just encountered this error while tracing block `916647` as well.

Request:
`{
	"jsonrpc": "2.0",
	"method": "debug_traceBlockByNumber",
	"params": [
		"0xDFCA7",
		{
			"tracer": "callTracer"
		}
	],
	"id": 74
}`
Response:
`{
  "jsonrpc": "2.0",
  "id": 74,
  "error": {
    "code": -32000,
    "message": "insufficient balance to pay for gas"
  }
}`

What is most interesting however, is that of the 3 transactions in this block Geth is still able to trace two of them properly. The following two tx hashes return a normal response from `debug_traceTransaction`:
`0x44e4f29f592e42cd1a104dc7347c02c78ac7a66be6e42005d2ad32f7b4f63218`
`0x4a5718d38238e2674208b0f0b95a6016ffe2b3002d11b464eaffefad79cf1c08`

Here is the problematic tx in the block:
Request:
`{
	"jsonrpc": "2.0",
	"method": "debug_traceTransaction",
	"params": [
		"0xca879fcf2d0146fc4e214ed5d9747a2743b6a586b4f1de1541e52c2fe6be5bad",
		{
			"tracer": "callTracer"
		}
	],
	"id": 74
}`
Response:
`{
  "jsonrpc": "2.0",
  "id": 74,
  "error": {
    "code": -32000,
    "message": "tracing failed: insufficient balance to pay for gas"
  }
}`

**Comment by Eric-Showers** [comment]
As far as I understand, performing a trace of any of those three transactions requires tracing the entire block anyways. So how come Geth only returns an error when tracing the problematic tx or explicitly tracing the whole block?
