### ISSUE TITLE
Miner, successfully found new new block, need broadcast message to peers, and wait to be chosen to add block into chain

### ISSUE THREAD

**Issue by quangtran8588** [ethereum/go-ethereum#17609]
Hi there,

I'm currently working on research on Ethereum. I'm a new one in this field. I need to implement a new feature which is miner will be chosen to add new block into chain when it's found. In order to do this, when miner successfully guess a nonce, it needs to broadcast a message to all peers in the network. PoW is implemented in the consensus/ethash/sealer.go, and the broadcast method is declared in eth/handler.go.
**-consensus/ethash/sealer.go:**

    search:
	for {
		select {
		case <-abort:
			// Mining terminated, update stats and abort
			logger.Trace("Ethash nonce search aborted", "attempts", nonce-seed)
			ethash.hashrate.Mark(attempts)
			break search

		default:
			// We don't have to update hash rate on every nonce, so update after after 2^X nonces
			attempts++
			if (attempts % (1 << 15)) == 0 {
				ethash.hashrate.Mark(attempts)
				attempts = 0
			}
			// Compute the PoW value of this nonce
			digest, result := hashimotoFull(dataset.dataset, hash, nonce)
			if new(big.Int).SetBytes(result).Cmp(target) <= 0 {
				// Correct nonce found, create a new header with it
				header = types.CopyHeader(header)
				header.Nonce = types.EncodeNonce(nonce)
				header.MixDigest = common.BytesToHash(digest)

				// Seal and return a block (if still needed)
                                // I will add few lines of code to postpone sealing task to send broadcast message  
                                // to peers, and wait until miner be chosen to add block into chain. Otherwise,
                                // it will be discarded.  
				select {
				case found <- block.WithSeal(header):
					logger.Trace("Ethash nonce found and reported", "attempts", nonce-seed, "nonce", nonce)
				case <-abort:
					logger.Trace("Ethash nonce found but discarded", "attempts", nonce-seed, "nonce", nonce)
				}
				break search
			}
			nonce++
		}
	}
	// Datasets are unmapped in a finalizer. Ensure that the dataset stays live
	// during sealing so it's not unmapped while being read.
	runtime.KeepAlive(dataset)

I tried to "import github.com/ethereum/go-ethereum/eth" in the sealer.go file to call a function which is implemented in handler.go, but it always gave me an error "import cycle not allowed". Is there anyway to do this?

**Comment by hadv** [comment]
I think that it's not a right place to ask these kind of question. You can open question on http://ethereum.stackexchange.com/ instead.

**Comment by karalabe** [comment]
Recently mined blocks are already broadcast into the network immediately when they are found. You can find that code piece and extend it to broadcast any other metadata you might need.
