### ISSUE TITLE
Rinkeby faucet tapped out?

### ISSUE THREAD

**Issue by wbt** [ethereum/go-ethereum#17608]
FYI: Visiting https://faucet.rinkeby.io/, the top of the page periodically displays "Faucet offline: context deadline exceeded." Screenshot:

![image](https://user-images.githubusercontent.com/563406/45242011-82a13980-b2bc-11e8-8af6-fc1dc251357d.png)

Attempting to use the faucet causes another copy of the alert to be added to it.

Past faucet references supporting this as a reasonable place to file issues: #15645, #16025

**Comment by ligi** [comment]
Thanks for reporting - faucet is back online - thanks to @karalabe

**Comment by wbt** [comment]
Issue recurring, FYI.  Thanks for the prior fix!

**Comment by karalabe** [comment]
Yes, light client is utterly unusable. Until that's fixed, the faucet will be offline.
