### ISSUE TITLE
p2p, why return known state?

### ISSUE THREAD

**Issue by shanhuhai5739** [ethereum/go-ethereum#17600]
Hi there,
p2p, why return known state?
https://github.com/ethereum/go-ethereum/blob/master/p2p/discv5/net.go#L952

```
	remoteverifywait = &nodeState{
		name: "remoteverifywait",
		enter: func(net *Network, n *Node) {
			net.timedEvent(respTimeout, n, pingTimeout)
		},
		handle: func(net *Network, n *Node, ev nodeEvent, pkt *ingressPacket) (*nodeState, error) {
			switch ev {
			case pingPacket:
				net.handlePing(n, pkt)
				return remoteverifywait, nil
			case pingTimeout:
				return known, nil
			default:
				return remoteverifywait, errInvalidEvent
			}
		},
	}
```

**Comment by shanhuhai5739** [comment]
I think, it should be unknown state if handle pingTimeout

**Comment by shanhuhai5739** [comment]
hello anybody here?

**Comment by fjl** [comment]
It returns to known state because the other side had a chance to ping, but didn't use it. We will remove p2p/discv5 code soon, no need to worry about this code :)

**Comment by HAOYUatHZ** [comment]
> It returns to known state because the other side had a chance to ping, but didn't use it. We will remove p2p/discv5 code soon, no need to worry about this code :)

`but didn't use it.`  what does `it` refer to?
am i correct that a normal peer will not ping, even if it has a chance, so we won't run into the consequent known state?
