### ISSUE TITLE
eth.hashrate always returns 0

### ISSUE THREAD

**Issue by jerryji** [ethereum/go-ethereum#17601]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: 1.8.15-stable
OS & Version: Linux (Ubuntu 18.04 64-bit)
Commit hash : (if `develop`)

#### Expected behaviour
eth.hashrate returns some non-zero value

#### Actual behaviour
eth.hashrate always returns zero on my Intel Core i7-7500U laptop (512G SSD PCIe)

$ geth --testnet --port 30303 --mine --minerthreads=4 --cache=2048

> net.peerCount
22
> eth.hashrate
0
> eth.getBlock("latest").difficulty
6042033910
> eth.blockNumber
3990598
> eth.getBalance(eth.coinbase)
0

#### Steps to reproduce the behaviour
miner.stop()
miner.start(4)
eth.hashrate

while geth has been eating 95% CPU for hours

#### Backtrace
N.A.

#### Note
Found this StackOverflow question https://ethereum.stackexchange.com/questions/51220/cpu-mining-on-testnet-using-geth-on-ubuntu-eth-hashrate-0 but it doesn't really help much

**Comment by jerryji** [comment]
Thanks @csokun , --metrics does the trick (isn't much, but at least not zero :) 

> eth.hashrate
182016
> eth.getBlock("latest").difficulty
10529606815

**Comment by QasidLabeed** [comment]
Same thing happens with me while running a private network using Flags. 
Mine got solved upon restarting the network.
 
1.I removed the datadir for each of the node.
2. Reinitialized genesis block for each node
3. Started each node.

Now eth.hashrate is showing some values instead of zero.

**Comment by susannaK** [comment]
> 1.I removed the datadir for each of the node.
> 2. Reinitialized genesis block for each node
> 3. Started each node.

I'm having the same issue & want to try your fix without accidentally destroying or deleting my accounts. 
Would you mind sharing exactly how you did #1 and #2?
