### ISSUE TITLE
Bloom filter false positive rate w/ ERC-20/721 topics.

### ISSUE THREAD

**Issue by ryanschneider** [ethereum/go-ethereum#17613]
#### System information

Geth version: `1.8.13`
OS & Version: Linux

#### Expected behaviour

The bloom filters should have a relatively low, but typically non-zero, false positive rate.

Also, geth should expose metrics on per-query and aggregate bloom filter false positive rates.

#### Actual behaviour

As mentioned in #17610, I was surprised to see that this query:

```json
{
  "method":"eth_getLogs","id":1,"jsonrpc":"2.0", 
  "params":[{
    "fromBlock":"0x1","toBlock":"latest",
    "topics":[ 
      "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
      "0x0000000000000000000000009035e9004a4f1e88c296be507c5cea8f99ff8a63", 
      "0x0000000000000000000000004be0cd2553356b4abb8b6a1882325dabc8d3013d"
    ],
    "address":"0x09d8b66c48424324b25754a873e290cae5dca439"
  }]
}
```

Leads to 547 blocks matching the bloom filter, even though only receipts in 6 blocks actually matched the 3 topics for that address.

My suspicion is that the recent uptick of ERC-20 events has made the bloom filters less effective, but I honestly don't know what a baseline false positive rate for the filters should be either.  Since the bloom filter is part of the consensus headers I'm in no way implying they should be changed, but it is possible there's a regression around hit rates which is why I wanted to raise it.

From a recent off-chain indexing scan I did, there are 119,478,594 `0xddf252..` (`Transfer`) events in the chain now, so perhaps I'm just thinking about the false positive rate wrong, it's really `541:119,478,594`, not `541:6`.

This paper looks promising for determining the expected FP rate, but I haven't fully read it yet or tried plugging in any of the numbers:

http://cglab.ca/~morin/publications/ds/bloom-submitted.pdf

And there is a caveat:

> We give an exact formula for the false-positive rate of Bloom filters. Unfortunately, this formula is not anywhere near closed form, but could be useful for small values of k, n and m.

As mentioned above, I think a good first step might be to add metrics around the actual false positive rates and attempt to compare those with derived expected rates.

#### Steps to reproduce the behaviour

I recorded the number of blocks scanned via this patch:

```diff
diff --git a/eth/filters/filter.go b/eth/filters/filter.go
index 071613ad7..eb942dced 100644
--- a/eth/filters/filter.go
+++ b/eth/filters/filter.go
@@ -19,7 +19,9 @@ package filters
 import (
        "context"
        "errors"
+       "github.com/ethereum/go-ethereum/log"
        "math/big"
+       "sync/atomic"

        "github.com/ethereum/go-ethereum/common"
        "github.com/ethereum/go-ethereum/core"
@@ -59,6 +61,8 @@ type Filter struct {
        begin, end int64       // Range interval if filtering multiple blocks

        matcher *bloombits.Matcher
+
+       blockCount int64
 }

 // NewRangeFilter creates a new filter which uses a bloom filter on blocks to
@@ -160,6 +164,8 @@ func (f *Filter) Logs(ctx context.Context) ([]*types.Log, error) {
        }
        rest, err := f.unindexedLogs(ctx, end)
        logs = append(logs, rest...)
+
+       log.Info("filter complete", "blocks", f.blockCount)
        return logs, err
 }

@@ -245,6 +251,7 @@ func (f *Filter) blockLogs(ctx context.Context, header *types.Header) (logs []*t
 // match the filter criteria. This function is called when the bloom filter signals a potential match.
 func (f *Filter) checkMatches(ctx context.Context, header *types.Header) (logs []*types.Log, err error) {
        // Get the logs of the block
+       atomic.AddInt64(&f.blockCount, 1)
        logsList, err := f.backend.GetLogs(ctx, header.Hash())
        if err != nil {
                return nil, err
```

**Comment by tueric** [comment]
According to https://hur.st/bloomfilter/?n=500&p=&m=2048&k=3 , there will be a **1 in 7 chance of a false positive** in a block bloom filter. 

![image](https://user-images.githubusercontent.com/6364934/45391958-62d28400-b5e2-11e8-90ee-0f18381d580b.png)


**n=500** because that's around how many logs are in a block according to tests. 
**m=2048** because thats 256 bytes (2048 bits), the length of the keccak-256 hash function.
**k=3** because 3 bits of the bloom filter, which should be equivalent to using 3 hash functions in more "traditional" bloom filters. (yellowpaper.io, pg. 5)

**Comment by ryanschneider** [comment]
FYI the 500 number that @tueric is referring to is from a recent off-chain indexing we've done, here's some graphs of the same data showing that most recent blocks have around 500 events in them:

![logsperblock](https://user-images.githubusercontent.com/53520/45393300-2b62d800-b5e0-11e8-83f8-4e215edaeb2b.png)

And the cumulative count of all blocks over time:

![cumulativelogs](https://user-images.githubusercontent.com/53520/45393307-3158b900-b5e0-11e8-85ed-d42beb34368d.png)

So if every block with 500 events in it (which has been more or less the case since block 4m) really does have roughly a 1 in 7 chance of being a false positive for the bloom filter, then we would expect my query above to have roughly `~2.5million * 1/7 = 350,000` false positives, but as shown with my patch it only had 541, so something (thankfully!) must be keeping the false positive rate down.

Thinking about it another way, the fact this query only had 541 false positives, and that blocks have been pretty steadily around 500 events per block starting around block 4m, means that the FP rate was closer to `541 / 2,500,000 = 0.0002164`, so actually very good, or I might be recording the performance of the bloom filter at the wrong spot.
