### ISSUE TITLE
Question about Discard functions

### ISSUE THREAD

**Issue by af913337456** [ethereum/go-ethereum#17629]
Discard is in tx_ist.go, i dont understand why use heap.pop to get the tx for abandon. heap.pop will take the last one from heap which gasPrice is bigger than the smallest, and the Discard function 
 is to find the underpriced transactions and remove it, it should use 'head := []*types.Transaction(*l.items)[0]' for each loop, Isn't it?

```go
// Discard finds a number of most underpriced transactions, removes them from the
// priced list and returns them for further removal from the entire pool.
func (l *txPricedList) Discard(count int, local *accountSet) types.Transactions {
	drop := make(types.Transactions, 0, count) // Remote underpriced transactions to drop
	save := make(types.Transactions, 0, 64)    // Local underpriced transactions to keep
	for len(*l.items) > 0 && count > 0 {
		// Discard stale transactions if found during cleanup
		tx := heap.Pop(l.items).(*types.Transaction)  
		if l.all.Get(tx.Hash()) == nil {
			l.stales--
			continue
		}
		// Non stale transaction found, discard unless local
		if local.containsTx(tx) {   
			save = append(save, tx)
		} else {    
			drop = append(drop, tx)
			count-- 
		}
	}
	for _, tx := range save {
		heap.Push(l.items, tx)
	}
	return drop
}

```

**Comment by af913337456** [comment]
According to the code，in the heap，the price at the front is the lowest

**Comment by af913337456** [comment]
@karalabe

**Comment by karalabe** [comment]
https://golang.org/pkg/container/heap/#Pop

> Pop removes the minimum element (according to Less) from the heap and returns it. The complexity is O(log(n)) where n = h.Len(). It is equivalent to Remove(h, 0).

**Comment by af913337456** [comment]
@karalabe 牛皮
