### ISSUE TITLE
hex address for EVM disassembly

### ISSUE THREAD

**Issue by liangdzou** [ethereum/go-ethereum#17627]
#### System information

evm version 1.8.14-unstable-6d1e292e

#### Expected behaviour

I would like the address to be hex since the jump instruction uses hex address. Otherwise, I have to calculate the hex address myself to read the asm.

#### Actual behaviour

```
000225: SWAP1
000226: SSTORE
000227: POP
000228: PUSH1 0x01
000230: ADD
000231: PUSH1 0xb5
000233: JUMP
```

It is hard to find the location of the jump(0xb5).

#### Steps to reproduce the behaviour

evm disasm *.bin

#### Backtrace

n/a

**Comment by gballet** [comment]
@liangdzou could you provide an example of the dump you would like to see, as opposed to what you currently see? It would make things clearer. Thanks.

**Comment by liangdzou** [comment]
```
000225: SWAP1
000226: SSTORE
000227: POP
000228: PUSH1 0x01
000230: ADD
000231: PUSH1 0xb5
000233: JUMP
```
It is hard to know where is the `0xb5`. I think it is reasonable to show the location of code `000181` at the beginning at the line as `0x0000b5`, i.e. the code should be better show as.
```
0x0000e1: SWAP1
0x0000e2: SSTORE
0x0000e3: POP
0x0000e4: PUSH1 0x01
0x0000e5: ADD
0x0000e6: PUSH1 0xb5
0x0000e7: JUMP
```
