### ISSUE TITLE
Clef: Incorrect File Permissions For secrets.dat 

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#17634]
Ref NCC-EF-Clef-001

The file permissions for secrets.dat should be set to `400` (instead of `700` ) in initializeSecrets() . The file permissions for secrets.dat should be ‘ANDed’ with `377` (instead of `077` )in checkFile() to maintain consistency.

**Comment by YaoZengzeng** [comment]
This issue is quiet straightforward, let me fix it 😄
