### ISSUE TITLE
Clef: implement secure backup

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#17630]
## Encryption of Clef Backup is Insufficient

Ref: NCC-EF-Clef-002 

An attacker able to compromise a user’s device has full access to Clef’s encrypted back up.
Clef stores a number of information on disk, in order to be able to recover from a restart.
This information is encrypted by keys derived from a single seed, which is in turn stored in
cleartext on disk under a `secrets.dat` file.
Because of this, a device not protected with disk encryption that gets physically breached
would leak all information stored under Clef’s encrypted backup.
Furthermore, a device that gets remotely breached would also compromise a dormant Clef
application.

### Recommendation: 
Enforce usage of a passphrase to start the Clef command-line interface. Use the same passphrase mechanism as the keystore to protect the secrets.dat file.

----
Comment/todo

The current setup trusts the device it's on a bit too much, and a user trying to backup the files `secrets.dat` needs to manually encrypt the file. TODO: Encrypt the master seed with a password, that needs to be fed into `clef` at startup.

**Comment by YaoZengzeng** [comment]
@holiman I'll try to fix this issue, give me some time , thanks 😂

**Comment by holiman** [comment]
If you do, please base it off of https://github.com/holiman/go-ethereum/tree/clefchanges_2 . However, I'm not sure how to best fix it -- what format to store the seed in. 

The flow would be 

* Init: create seed. get password. Encrypt seed with password into container. 
* Normal: decrypt container to get seed. 

So the raw seed should never hit the disk, only the encrypted seed.

**Comment by YaoZengzeng** [comment]
@holiman The work flow you mentioned above is the same as what I thought.

For the encrypt stuff, from my general thought, maybe we could reuse the code in `account/keystore` which is used to protect the account's private key. 

And we can use this mechanism to protect the `master seed` as well.

For this condition, the `master seed` is the `private key` and we store what in the `keystore` to `secrets.dat`.

WDYT?

**Comment by holiman** [comment]
I definitely think we can use a similar schema, but I don't think we should make the actual file ambiguous. It should clearly fail if the keystore tries to open it 'as a keystore file', and vice versa. So it shouldn't have 'address'. Perhaps a more generalized form, which could be used to store arbitrary `data`, and instead of `address` have a `descriptor` which can be used to describe what the data pertains to (which we can set to e..g `"descriptor" : "clef_masterseed"`

**Comment by YaoZengzeng** [comment]
Yes, the `keystore` is not very fit for us and may result some misleading.

So in the PR referenced above, I extract something we need from `keystore` to reach our goal.

And the code looks a bit redundant, maybe we could refactor `keystore` and make it more general in the future.

**Comment by hbbmt** [comment]
https://get.cryptobrowser.site/265959
MAKE MONEY
WORK %1000
