### ISSUE TITLE
unsupported arg type: tuple

### ISSUE THREAD

**Issue by outprog** [ethereum/go-ethereum#17642]
`"type": "tuple"`  in ABI, accounts/abi.go `JSON` parse is not work. It's return like this:

```
panic: unsupported arg type: tuple
```

How could I parse ABI include type of tuple ?

**Comment by jlevison** [comment]
#18033  was closed by #18051, but it says that support for tuple is not implemented - should abi.JSON support tuple or not?

**Comment by outprog** [comment]
Closed by https://github.com/ethereum/go-ethereum/pull/18406

**Comment by liyu1016** [comment]
如何解决用web3j生成java类时的错误信息， Unsupported type encountered: tuple

**Comment by outprog** [comment]
> 如何解决用web3j生成java类时的错误信息， Unsupported type encountered: tuple

有可能 web3j 还没有支持 tuple。这个支持 golang 也等了很久。
