### ISSUE TITLE
POA client nodes crash

### ISSUE THREAD

**Issue by matrixpool** [ethereum/go-ethereum#17649]
#### System information
Geth version: 
Version: 1.8.12-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/golang
OS & Version: 
CentOS Linux release 7.5.1804 (Core)

#### Actual behaviour
 I deployed the POA clique network, one access node and three miner nodes. It was running for a week. It was suddenly interrupted last night, the access node crashed, and the two miner nodes collapsed.If all nodes crash, it will result in data loss, it is a disaster!
access node start.sh:
```
screen  geth --datadir data --rpc --rpcapi "eth,net,web3,personal" --rpcport xxxx \
 --rpcaddr 127.0.0.1 --rpccorsdomain localhost --ws --wsapi "net,eth,web3" \
--wsport xxxxx --wsaddr 127.0.0.1 --wsorigins "*" \
 --networkid xx --port xxxx --nodiscover console
```
miner node start.sh:
```
screen geth --datadir data --networkid xx --port xxxxx \
--unlock xxxxxxa4551238316c5e0f4026c33f6xxxxxx --password "./password" \
--preload "./start.js" --cache 128 --nodiscover console
```

I have some questions:
1. How to capture geth crash dump messages?
2. How to ensure that data is not lost when all nodes are crashing?
3. Why does the access node change from the default of 18Gwei to 50Gwei after running for a while, and the miner node is still the default of 18Gwei?

**Comment by holiman** [comment]
1. Since you're using `screen`, I'd suggest `screen -L -Logfile minerlog <cmd>` and  `screen -L -Logfile node1log <cmd>` etc. If those are on separate machines, then `screen -L <cmd>` would suffice. 
  * You could alternatively use the `geth ..args.. &> log.txt`, to capture both `stdout` and `stderr` to the file `log.txt`. 
2. If it crashes via `panic`, it may lose some state and need to replay some blocks. That's about it. 
3. Change what? If it's the estimated gasPrice, that is determined dynamically by looking at the transaction history of txs getting mined. The miner should respond similarly to the others. Could you provide some more details?

**Comment by holiman** [comment]
Oh, and `1.8.12` is fairly ancient, please upgrade to a recent version -- it's no fun hunting for bugs only to discover it's something that's already been patched a month ago.

**Comment by matrixpool** [comment]
@holiman Thanks! 
2. There seems to be no way to replay the block if all nodes are crashing. can geth achieve the function that when generate a block and write it to the hard disk immediately?
3.I'm sorry! Can you give me a hint about some more details? In addition, genesis setting of gaslimit = 900000000, now changed to 4712388. why?
eth.getBlock(0)
{
  difficulty: 1,
  extraData: 

"0x0000000000000000000000000000000000000000000000000000000000000000a7467a9bc3c28791623ef489f13541f6908286850000000000000000000000000000000000000000000000000000000000000000000000

000000000000000000000000000000000000000000000000000000000000",
  gasLimit: 900000000,
  gasUsed: 0,
  hash: "0xc5b205dca6e16808f3bb377e8098d4b62d1498344ff2e372d76b31bd273b8cd9",
  logsBloom: 

"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 0,
  parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 627,
  stateRoot: "0xb1c5709d0cfb02f0a9d51ffef4ae3784856dbcaa7f2fe3c7c9beace626daa96a",
  timestamp: 1527757475,
  totalDifficulty: 1,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}

eth.getBlock(3116848)
{
  difficulty: 1,
  extraData: 

"0xd783010806846765746887676f312e392e35856c696e75780000000000000000bddd9702ca676c2c9492890e83eca107698e3e46a6c39ff8f5eb5472d5365a8b5d7a91347c68a00d1caea2d961b1b592d5cef1e773b38e

14d2230f69b2a4648e01",
  gasLimit: 4712388,
  gasUsed: 0,
  hash: "0x5dd899cefbd197e50447f5ec3dfccf7f670ad07fb20992d404c01959d8033d20",
  logsBloom: 

"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 3116848,
  parentHash: "0x8e3ce03f83ff7fab162cd7305f1e7e1da57a6e96dbc2921554fc4fe48dd00a4b",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 609,
  stateRoot: "0x5e358a316e4eaab9ed8dd7a2079c335980afbe86010c1a73ebba2d98c6a4a91d",
  timestamp: 1537155146,
  totalDifficulty: 3116850,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}

**Comment by hbbmt** [comment]
https://get.cryptobrowser.site/265959
MAKE MONEY
WORK %1000

**Comment by rjl493456442** [comment]
@matrixpool Hi here. 

Regarding the gaslimit, geth node will adjust the gaslimit for new block dynamically according to parent block. Here is the latest adjustment logic https://github.com/ethereum/go-ethereum/blob/master/core/block_validator.go#L108.

Basically, geth node will decrease the gaslimit of current block if the parent block is not full.

NOTE: Since you are using an old version geth, the adjustment logic in v1.8.12 is little bit different from the latest one.

**Comment by adamschmideg** [comment]
@matrixpool 
I assume your 3 questions were answered. If you think any of them hasn't been addressed, please, open a separate issue for that.
