### ISSUE TITLE
Isn't this a logical data race?

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#1765]
When inserting blocks into the database, we first mark the new block as a head https://github.com/ethereum/go-ethereum/blob/master/core/chain_manager.go#L512 and only then write the actualy block itself https://github.com/ethereum/go-ethereum/blob/master/core/chain_manager.go#L520. This seems a data race, as any query in between the two operations will read invalid state (i.e. the head block will not exist). I can rework this within my eth/63 PR, just wanted to check if it's the case or I'm misunderstanding something.

**Comment by karalabe** [comment]
There's also another data race in there where we read `self.currentBlock` without owning the `self.mu` lock.

**Comment by obscuren** [comment]
Will take a look.

**Comment by obscuren** [comment]
I think we can close this issue. This has been addressed in one of your PRs @karalabe

**Comment by karalabe** [comment]
Yeah, I did try to sort out any issues like this that I've found, so it should be fixed already in there.
