### ISSUE TITLE
LOST WALLET

### ISSUE THREAD

**Issue by MARTYPAUL** [ethereum/go-ethereum#17666]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by MARTYPAUL** [comment]
I had tokens in MetaMask. Then they were gone. used the 12 words. That didn't work. After three weeks MetaMask kept saying they are lost cant help. I kept looking every where. I have my address. using the address, i found the coins on ertherscan. Now every one says I still can notget them. Please see all the attached. Thank you. martypaul1943@gmail.com
![123](https://user-images.githubusercontent.com/35767205/45486597-b26f9780-b729-11e8-8ee3-dbe995e79353.png)
![capture](https://user-images.githubusercontent.com/35767205/45486607-bd2a2c80-b729-11e8-98ef-116fe8937467.PNG)
![tokens](https://user-images.githubusercontent.com/35767205/45486618-c61afe00-b729-11e8-8ce4-9e17da475a5a.PNG)
![123](https://user-images.githubusercontent.com/35767205/45486634-daf79180-b729-11e8-9f0e-8893ff3dfe90.png)
![words](https://user-images.githubusercontent.com/35767205/45486644-e480f980-b729-11e8-8f54-8a595147408e.PNG)
![words](https://user-images.githubusercontent.com/35767205/45486657-ecd93480-b729-11e8-8dc8-5fc0b9da76cc.PNG)
![capture](https://user-images.githubusercontent.com/35767205/45486669-f793c980-b729-11e8-8146-28dd51586e8f.PNG)

**Comment by MARTYPAUL** [comment]
Can any one help me?

**Comment by holiman** [comment]
I have removed the images from the post above. It appeared like those images contained information that would enable anyone from obtaining funds from that account, if there's anything left. 

Try to formulate more precisely what has happened, without disclosing secret information.
