### ISSUE TITLE
private network windows tries to connect to external

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [ethereum/go-ethereum#1766]
Hi, I tried to run my private network for testing but it tries to connect to external. I took tutorial from here: https://github.com/ethereum/go-ethereum/wiki/Setting-up-private-network-or-local-cluster 
geth version :1.1.0
logs:
D:\eth>geth --datadir="1" --networkid 909 --verbosity 6 --ipcdisable --port 30302 --rpcport 8102 --genesis genesis.json
I0903 17:50:45.464613    4840 flags.go:410] WARNING: No etherbase set and no accounts found as default
I0903 17:50:45.465613    4840 database.go:73] Alloted 16MB cache to 1\chaindata
I0903 17:50:45.495615    4840 database.go:73] Alloted 16MB cache to 1\dapp
I0903 17:50:45.500615    4840 backend.go:291] Protocol Versions: [62 61], Network Id: 909
I0903 17:50:45.500615    4840 statedb.go:251] (+) 123f681646d4a755815f9cb19e1acc8565a0c2a1
I0903 17:50:45.500615    4840 state_object.go:199] 123f681646d4a755815f9cb19e1acc8565a0c2a1: #0 999999999999999999999 (+ 999999999999999999999)
I0903 17:50:45.500615    4840 statedb.go:251] (+) 123f681646d4a755815f9cb19e1acc8565a0c2a2
I0903 17:50:45.501615    4840 state_object.go:199] 123f681646d4a755815f9cb19e1acc8565a0c2a2: #0 9999999999999999999999 (+ 9999999999999999999999)
I0903 17:50:45.501615    4840 statedb.go:251] (+) 123f681646d4a755815f9cb19e1acc8565a0c2a3
I0903 17:50:45.501615    4840 state_object.go:199] 123f681646d4a755815f9cb19e1acc8565a0c2a3: #0 99999999999999999999999 (+ 99999999999999999999999)
I0903 17:50:45.501615    4840 genesis.go:88] Genesis block already in chain. Writing canonical number
I0903 17:50:45.502615    4840 backend.go:303] Successfully wrote genesis block. New genesis hash = 17fd5d8edc3cfd8f906a149b5975cd8ed691c94d935b022eaea
1d8de92e84c60
I0903 17:50:45.502615    4840 backend.go:328] Blockchain DB Version: 3
I0903 17:50:45.502615    4840 chain_manager.go:237] Last block (#0) 17fd5d8edc3cfd8f906a149b5975cd8ed691c94d935b022eaea1d8de92e84c60 TD=1024
I0903 17:50:45.502615    4840 statedb.go:251] (+) 0000000000000000000000000000000000000000
I0903 17:50:45.503615    4840 state_object.go:231] 0000000000000000000000000000000000000000: gas (+ 134086657)
I0903 17:50:45.506615    4840 cmd.go:125] Starting Geth/v1.1.0/windows/go1.4.2
I0903 17:50:45.507615    4840 server.go:311] Starting Server
I0903 17:50:47.566733    4840 nat.go:109] network port udp:30302 could not be mapped: no UPnP or NAT-PMP router discovered
I0903 17:50:47.604735    4840 udp.go:207] Listening, enode://01dc3b7c023ea2d0eb27a82c1b2b8f4dadd42f433f6af4200607c08be97a173ce07aab43be9b0936fcec255b3
16ad08a4ae12f7f27c49a04788c8a24ef09222e@0.0.0.0:30302
I0903 17:50:47.605735    4840 backend.go:557] Server started
I0903 17:50:47.605735    4840 server.go:552] Listening on [::]:30302
I0903 17:50:47.605735    4840 server.go:431] new task: discovery bootstrap
I0903 17:50:47.605735    4840 nat.go:109] network port tcp:30302 could not be mapped: no UPnP or NAT-PMP router discovered
I0903 17:50:47.606735    4840 database.go:185] failed to retrieve node a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d
8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c: leveldb: not found
I0903 17:50:47.606735    4840 table.go:377] Bonding a979fb575495b8d6: known=false, fails=0
I0903 17:50:47.606735    4840 database.go:185] failed to retrieve node de471bccee3d042261d52e9bff31458daecc406142b401d4cd848f677479f73104b9fdeb090af95
83d3391b7f10cb2ba9e26865dd5fca4fcdc0fb1e3b723c786: leveldb: not found
I0903 17:50:47.606735    4840 database.go:185] failed to retrieve node 979b7fa28feeb35a4741660a16076f1943202cb72b6af70d327f053e248bab9ba81760f39d0701e
f1d8f89cc1fbd2cacba0710a12cd5314d5e0c9021aa3637f9: leveldb: not found
I0903 17:50:47.606735    4840 database.go:185] failed to retrieve node 1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d8
9d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082: leveldb: not found
I0903 17:50:47.607735    4840 table.go:377] Bonding de471bccee3d0422: known=false, fails=0
I0903 17:50:47.607735    4840 udp.go:429] >>> 52.16.188.185:30303 discover.ping
I0903 17:50:47.607735    4840 table.go:377] Bonding 979b7fa28feeb35a: known=false, fails=0
I0903 17:50:47.608735    4840 table.go:377] Bonding 1118980bf48b0a36: known=false, fails=0
I0903 17:50:47.609735    4840 udp.go:429] >>> 54.94.239.50:30303 discover.ping
I0903 17:50:47.609735    4840 udp.go:429] >>> 5.1.83.226:30303 discover.ping
I0903 17:50:47.609735    4840 udp.go:429] >>> 52.74.57.123:30303 discover.ping
I0903 17:50:48.109764    4840 server.go:465] <-taskdone: discovery bootstrap
I0903 17:50:48.109764    4840 server.go:431] new task: discovery lookup
I0903 17:50:48.110764    4840 database.go:185] failed to retrieve node a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d
8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c: leveldb: not found
I0903 17:50:48.110764    4840 table.go:377] Bonding a979fb575495b8d6: known=false, fails=0
I0903 17:50:48.110764    4840 database.go:185] failed to retrieve node de471bccee3d042261d52e9bff31458daecc406142b401d4cd848f677479f73104b9fdeb090af95
83d3391b7f10cb2ba9e26865dd5fca4fcdc0fb1e3b723c786: leveldb: not found
I0903 17:50:48.110764    4840 database.go:185] failed to retrieve node 979b7fa28feeb35a4741660a16076f1943202cb72b6af70d327f053e248bab9ba81760f39d0701e
f1d8f89cc1fbd2cacba0710a12cd5314d5e0c9021aa3637f9: leveldb: not found
I0903 17:50:48.111764    4840 table.go:377] Bonding 979b7fa28feeb35a: known=false, fails=0
I0903 17:50:48.111764    4840 udp.go:429] >>> 52.16.188.185:30303 discover.ping
I0903 17:50:48.111764    4840 table.go:377] Bonding de471bccee3d0422: known=false, fails=0
I0903 17:50:48.110764    4840 database.go:185] failed to retrieve node 1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d8
9d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082: leveldb: not found
I0903 17:50:48.112764    4840 udp.go:429] >>> 5.1.83.226:30303 discover.ping
I0903 17:50:48.112764    4840 table.go:377] Bonding 1118980bf48b0a36: known=false, fails=0
I0903 17:50:48.112764    4840 udp.go:429] >>> 54.94.239.50:30303 discover.ping
I0903 17:50:48.113764    4840 udp.go:429] >>> 52.74.57.123:30303 discover.ping
I0903 17:50:48.613793    4840 server.go:465] <-taskdone: discovery lookup
I0903 17:50:48.613793    4840 server.go:431] new task: discovery lookup
I0903 17:50:50.682911    4840 cmd.go:134] Got interrupt, shutting down...
I0903 17:50:50.682911    4840 server.go:449] <-quit: spinning down
I0903 17:50:50.682911    4840 nat.go:105] deleting port mapping: udp 30302 -> 30302 (ethereum discovery) using UPnP or NAT-PMP
I0903 17:50:50.682911    4840 server.go:580] Read error: AcceptEx tcp [::]:30302: use of closed network connection
I0903 17:50:50.682911    4840 nat.go:105] deleting port mapping: tcp 30302 -> 30302 (ethereum p2p) using UPnP or NAT-PMP
I0903 17:50:50.683911    4840 udp.go:477] Read error: WSARecvFrom udp 0.0.0.0:30302: use of closed network connection
I0903 17:50:50.683911    4840 server.go:513] ignoring 1 pending tasks at spindown
I0903 17:50:50.684911    4840 chain_manager.go:459] Chain manager stopped
I0903 17:50:50.684911    4840 handler.go:164] Stopping ethereum protocol handler...
I0903 17:50:50.685911    4840 handler.go:174] Ethereum protocol handler stopped
I0903 17:50:50.685911    4840 transaction_pool.go:138] Transaction pool stopped
I0903 17:50:50.685911    4840 backend.go:686] Automatic pregeneration of ethash DAG OFF (ethash dir: C:\Users\v\AppData\Ethash)
I0903 17:50:50.686911    4840 database.go:167] flushed and closed db: 1\chaindata
I0903 17:50:50.686911    4840 database.go:167] flushed and closed db: 1\dapp

**Comment by fjl** [comment]
If you only want to connect to peers manually (with `admin.addPeer` in the console), run with `--nodiscover`. That flag turns off peer discovery and prevents geth from trying to find peers for your network id on the internet.

If you want you private network to set itself up automatically, use `--bootnodes`. Start one node first with `--bootnodes=none`, note done the `enode://...` URL that it prints and start all other nodes with `--bootnodes "<that url>". Please be aware that discovery is 'contagious', that is, if one of the nodes has a different bootnode (even on a previous startup) it will discover the rest of the world pretty quickly and you're back to square one. Start with an empty datadir on all nodes to prevent this.
