### ISSUE TITLE
How to retrieve data from ethereum for local application?

### ISSUE THREAD

**Issue by bh4rtp** [ethereum/go-ethereum#17676]
Hi,
I have a question about data synchronization between ethereum and local application. The local application is centralized. So I prefer to use golang to retrieve data from ethereum blockchain network. And then write it to local PostgreSQL database. Finally the local application can do analysis of the data.
Could you please suggest me a good solution. Thank you in advance.

Allen Chen

**Comment by karalabe** [comment]
You can use the `ethclient` package to access remote/local/in-process Ethereum nodes from Go. As for the rest, please ask on stack exchange on how people do it in general, let's keep this issue tracker dedicated for issues. https://ethereum.stackexchange.com/
