### ISSUE TITLE
SOCKS5 proxy support for geth

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#17686]

**Comment by peer2peer** [comment]
Any solutions or workaround? 
My peer cannot access Internet directly but only can via a socks5 proxy.
Now I run a Geth node and add one peer of another existing ethereum node on Internet by addPeer, how to make it work?

**Comment by SjonHortensius** [comment]
this is a duplicate of #1855

**Comment by tantrev** [comment]
This would be super useful for adding [Nym](https://nymtech.net/) support to Geth.

**Comment by htjain** [comment]
+1

**Comment by holiman** [comment]
Duplicate of https://github.com/ethereum/go-ethereum/issues/1855
