### ISSUE TITLE
exec: "gcc": executable file not found in %PATH%

### ISSUE THREAD

**Issue by dovancao** [ethereum/go-ethereum#17680]
Hi there,

I tried to install swarm in Window 10 but I always got this error. How do i solve it?

![screenshot_1](https://user-images.githubusercontent.com/36324165/45605698-1fa46500-ba69-11e8-90ed-ecdbf567f1c2.png)

I installed these package
```
golang
mingw
```
I also set Enviroment
Variable name: MINGW_HOME
Variable value: C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin

Thank you for your help!

**Comment by hbbmt** [comment]
https://get.cryptobrowser.site/265959
MAKE MONEY
WORK %1000

**Comment by fjl** [comment]
If the mingw installer didn't modify PATH, you might have to add the MINGW_HOME directory to PATH yourself.
