### ISSUE TITLE
Compilation issues on OSX high Sierra - Known bug, info provided

### ISSUE THREAD

**Issue by REPTILEHAUS** [ethereum/go-ethereum#17688]
Compilation issues on OSX high Sierra related to a security issue allowing arbitrary code execution in one of the vendor packages, namely ```github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify```

make all results in:

```
# github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51:216: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:165:47: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCStringNoCopy
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:166:225: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
```
More information on this issue can be found here 
https://tip.golang.org/doc/go1.10#cgo
https://github.com/rjeczalik/notify/issues/158

**Comment by fjl** [comment]
Not sure which version you are building, but this is fixed on master branch,

**Comment by debragail** [comment]
I have this issue as well

vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51:216: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:165:47: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCStringNoCopy
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:166:225: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
util.go:45: exit status 2
exit status 1
make: *** [geth] Error 1
