### ISSUE TITLE
Console crash

### ISSUE THREAD

**Issue by hectorchu** [ethereum/go-ethereum#1768]
Type a character.
Then go to beginning of line, and press Tab.

panic: runtime error: slice bounds out of range

goroutine 82 [running]:
main.apiWordCompleter(0xc820610660, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /build/ethereum-4YKfh9/ethereum-1.1.2+55trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/geth/js.go:140 +0x1f5
github.com/peterh/liner.(*State).tabComplete(0xc820137320, 0xc820917b88, 0x2, 0x20, 0xc820628390, 0x1, 0x2, 0x0, 0x0, 0x0, ...)
        /build/ethereum-4YKfh9/ethereum-1.1.2+55trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github
.com/peterh/liner/line.go:248 +0x165
github.com/peterh/liner.(*State).Prompt(0xc820137320, 0xe21830, 0x2, 0x0, 0x0, 0x0, 0x0)
        /build/ethereum-4YKfh9/ethereum-1.1.2+55trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github
.com/peterh/liner/line.go:678 +0x2b01
main.(*jsre).interactive.func1(0xc8205e3d40, 0xc820212700, 0xc8205e3ce0)
        /build/ethereum-4YKfh9/ethereum-1.1.2+55trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/geth/js.go:379 +0xba
created by main.(*jsre).interactive
        /build/ethereum-4YKfh9/ethereum-1.1.2+55trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/geth/js.go:390 +0x9c

**Comment by karalabe** [comment]
@bas-vk Are you familiar with that part? Maybe it's the code completion failing for being invoked on some nil/empty slice?

**Comment by bas-vk** [comment]
will take a look at it this weekend

**Comment by zelig** [comment]
fixed in #1774
