### ISSUE TITLE
Error: mining not ready

### ISSUE THREAD

**Issue by nanom1t** [ethereum/go-ethereum#17693]
Hi,

I've faced with strange error with Geth:
```
> eth.getWork()
Error: mining not ready
    at web3.js:3119:20
    at web3.js:6086:15
    at web3.js:5050:36
    at <anonymous>:1:1
```
Can anyone help with this?

Thanks

**Comment by karalabe** [comment]
You need to start mining. Either pass in `--mine` when you start your node, or on the condeols `miner.start(0)` (start it without CPU enabled).

**Comment by duyk16** [comment]
> 
> 
> @karalabe Thank you for the response. I don't want start mining on my server, because it has not enough computing power for mining. I'm trying to use this node for [mining pool](https://github.com/sammy007/open-ethereum-pool).

adding ``--minerthreads 0`` if u dont want to use your sever for mining

**Comment by karalabe** [comment]
`--mine` only starts the next block creation, but it does not enable CPU mining. You can then send remote requests to it.
