### ISSUE TITLE
SendRawTransaction() sometimes returns an empty response.

### ISSUE THREAD

**Issue by CMajeri** [ethereum/go-ethereum#17694]
Hello,

Sometimes, when sending a raw transaction via our geth node, the call will hang for a very long time, and will end up returning nothing (`web3.js: Error: Invalid JSON RPC response: ""`), but the transaction will end up being propagated to the network (I suspect a connection timeout is the reason why the call returns empty).

The node is a fast sync node with gcmode=archive, the rpc endpoint is active:
```
/usr/bin/geth --rpc --rpcport "8545" --rpcaddr "0.0.0.0" --rpccorsdomain "*" --rpcapi "eth,web3,net" --gcmode=archive --rpcvhosts=* --vmodule "rpc/*=5,internal/*=5"
```

There's no evidence of a delay in the logs, it just shows "Transaction submitted" after a while.

At first glance in the code, I don't understand where the delay comes from, as the call simply seems to add the Tx to a pool and enqueue the propagation.

Could this be due to syncing issues do to my node being slightly behind a times? Would a full node help?

Thanks.

#### System information

Geth version: `1.8.13-stable`
OS & Version: Linux
Commit hash : 225171a4bfcc16bd12a1906b1e0d43d0b18c353b

#### Expected behaviour
SendRawTx(tx) returns the transaction hash

#### Actual behaviour
SendRawTx(tx) returns empty

#### Steps to reproduce the behaviour
I can't actually reproduce this. It just happens sometimes.

**Comment by CMajeri** [comment]
I'll try that right away, thanks.

**Comment by holiman** [comment]
This is quite old, and there's a suggested fix, so I'm closing this.
