### ISSUE TITLE
eth.compile with solidity 0.1.2

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1770]
Name: "Geth/v1.1.2-58766921/linux/go1.4.2"

cannot compile the simple sample (from Frontier guide) using solc 0.1.2

```
> eth.getCompilers()
["Solidity"]

> source
"contract test { function multiply(uint a) returns(uint d) { return a * 7; } }"

> eth.compile.solidity(source)
solc error: missing code output
    at InvalidResponse (<anonymous>:-81076:-29)
    at send (<anonymous>:-154580:-29)
    at solidity (<anonymous>:-131712:-29)
    at <anonymous>:1:1
```

**Comment by ethers** [comment]
hi @zelig I think this is affecting quite a lot of people and not sure why it's "only" an "enhancement" ?  (if it helps, here's the PR that fixed pyethapp for 0.1.2: https://github.com/ethereum/pyethereum/pull/285)

**Comment by zelig** [comment]
@ethers just about to submit a PR to fix

**Comment by ethers** [comment]
thanks @zelig :)

**Comment by christianlundkvist** [comment]
Yeah agree with @ethers that this is important. This issue is currently blocking for me.

**Comment by ethers** [comment]
#1786 merged but still
"solc: exit status 1
option '--optimize' does not take any arguments"
https://github.com/ethereum/go-ethereum/pull/1786#discussion_r39335819

snip off the `=1` seems to work

**Comment by obscuren** [comment]
Issue has been addressed and fixed

**Comment by iurimatias** [comment]
which geth version can one find this fix?

**Comment by fjl** [comment]
On the develop branch. It will be in the next official release (no date yet).

**Comment by iurimatias** [comment]
is this change backwards compatibility? will it still work for users using solc 0.1.1?

**Comment by fjl** [comment]
yes

**Comment by lisardo** [comment]
is there a workaround for this bug now?

**Comment by iurimatias** [comment]
@lisardo downgrade to 0.1.1 and it will work.

**Comment by someone235** [comment]
I'm at the "develop" branch and I still have this problem.

**Comment by iurimatias** [comment]
@someone235 try the latest embark 1.0.2
