### ISSUE TITLE
After timeout error, geth breaks down.

### ISSUE THREAD

**Issue by eggoa** [ethereum/go-ethereum#17716]
After "ERROR[09-20|13:33:35.796] write tcp 172.31.42.157:8003->213.202.242.16:14532: i/o timeout" error, geth breaks down.

Is there anything wrong with this ip?

error:

ERROR[09-20|13:32:10.152] write tcp 172.31.42.157:8003->213.202.242.16:35212: i/o timeout
  i/o timeout

fatal error: runtime: out of memory
runtime stack:
runtime.throw(0xf6b887, 0x16)
/usr/local/go/src/runtime/panic.go:619 +0x81
runtime.sysMap(0xc798cd0000, 0x10000000, 0x0, 0x1ba1b78)
/usr/local/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x1b880c0, 0x10000000, 0x7f1c70501cf0)
/usr/local/go/src/runtime/malloc.go:470 +0xd4

**Comment by sivachaitanya** [comment]
I guess there are nodes attempting to make connections to your geth, make sure you set your firewall to only allow certain ips to connect to 8545

**Comment by gballet** [comment]
@eggoa Please provide the steps to reproduce this, in particular please specify if like @sivachaitanya said your firewall isn't blocking connections.
