### ISSUE TITLE
ethstats report module often crash

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#17713]
```
Failed to decode stats server message    err="read tcp 172.31.17.180:54448->104.24.108.8:443: read: connection reset by peer
```

Or something like this

```
Failed to decode stats server message    err=EOF
Transaction stats report failed          err="tls: use of closed connection
```

**Comment by eosclassicteam** [comment]
@karalabe I've checked with stats server but it is working well with parity 😂

**Comment by gballet** [comment]
@ghost could you please copy/paste the config that you used, as well as the machine's config ? We don't have enough information to process this issue any further.
