### ISSUE TITLE
Geth nodes are pretty unstable while processing more than 200+ transactions per block

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#17711]
For detail, they are being slow while fetching blocks more than 200tps

Any improvements or milestone planned on this??

This is a very well-known issue for node operators and we need to fix it asap

**Comment by sivachaitanya** [comment]
did you achieve 200 tps on  a private net ?

**Comment by eosclassicteam** [comment]
@sivachaitanya Yes but in this case I am complaining about **200 tx per block**

**Comment by MariusVanDerWijden** [comment]
This issue became pretty stale by now.
Please recheck with the newest version.
Since the OP is ghost, I'll close this issue. Please reopen a new one if this issue still persists
