### ISSUE TITLE
Strange values on import genesis.json

### ISSUE THREAD

**Issue by romanman** [ethereum/go-ethereum#1772]
I am trying to import that values:

```
 "nonce": "0000000000000042",
  "difficulty": "020000",
  "mixhash": "0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0000000000000000000000000000000000000000",
  "timestamp": "00",
  "parentHash": "0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
  "gasLimit": "0x1388"
```

but go decides it is : 

```
 "nonce": "0000000000000022",
  "difficulty": "2000",
```

any ideas ?

**Comment by maran** [comment]
Try using hex notation such as `0x0000000000000042` and `0x020000`

**Comment by romanman** [comment]
@maran : thanks Maran , will check it 
I was thinking in that direction but 
you know `0x0...22` is not `42`

**Comment by bas-vk** [comment]
Go uses the `big.Int` and the [SetString](https://golang.org/src/math/big/int.go?s=8978:9034#L362) method. When the given base is 0 (in this case) this function tries to determine the base from the first character(s). For input `0000000000000042` it assumes that the input is in base8 (octal) which is 22 in hex.

Solution would be to supply the correct value in octal of just prefix it with `0x` if you want to have it in hex format.

**Comment by romanman** [comment]
@bas-vk : yeah sounds reasonable :+1:
