### ISSUE TITLE
Rinkeby faucet not working

### ISSUE THREAD

**Issue by Ramarti** [ethereum/go-ethereum#17721]
Hello there!

Visiting https://faucet.rinkeby.io/

This happens:
<img width="815" alt="captura de pantalla 2018-09-20 a las 17 45 24" src="https://user-images.githubusercontent.com/2632384/45830255-0a476900-bcfd-11e8-807c-020e9000d66d.png">

Previously the message was about not finding peers.

Cheers!

**Comment by ligi** [comment]
thanks for reporting 
duplicate of #17596

**Comment by alexandrabelzon** [comment]
This is the most recent issue regarding the faucet and I couldn't find any further info.
Is the faucet still down? It seems to be stuck with new requests being added but none being processed. There's no error message though.
