### ISSUE TITLE
 cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal

### ISSUE THREAD

**Issue by lishuo5263** [ethereum/go-ethereum#17751]
Hi there,
  When  I Clone go-ehtereum ,and I Check out v1.67 Stable Version, I Want to make Geth by source,Then I have something Wrong with Envirment,here is my MacOS & Golang info.

#### System information
OS & Version: macOS High Sierra 10.13.6
GoLang Version :1.11

Here is Error Detail , And I problem as same as [https://github.com/ethereum/go-ethereum/issues/17688](url) , I fllow this direction try solve this problem ,but useless

![Uploading WechatIMG2.jpeg…]()

**Comment by lishuo5263** [comment]
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/Versions/A/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/Versions/A/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.
# github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51:216: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:162:47: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCStringNoCopy
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:163:225: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
util.go:44: exit status 2
exit status 1
make: *** [geth] Error 1
localhost:go-ethereum lisandro$ go version
go version go1.11 darwin/amd64

**Comment by hiroki-money** [comment]
+1

**Comment by iannovic** [comment]
+1

**Comment by fjl** [comment]
You cannot compile geth v1.6.7 on with Go 1.11. Please upgrade to geth v1.8.16.

**Comment by MasashiSalvador57f** [comment]
+1
