### ISSUE TITLE
can't use geth node from browser web3.js due to CORS 

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [ethereum/go-ethereum#1775]
I tried :
geth --datadir="1"  --networkid 1 --verbosity 4 --autodag --ipcdisable --port 30302  --solc "C:\Program Files\Ethereum 0.9.41\Release\solc.exe" --genesis genesis.json --bootnodes=none --rpcport 8102 --rpcaddr "127.0.0.1" --rpccorsdomain "http://127.0.0.1:8102"  console
is not working.

but --rpccorsdomain "*" works fine...

**Comment by obscuren** [comment]
Could you be slightly more specific when you say "it doesn't work"? What exactly doesn't work?

**Comment by vitaliy-kuzmich** [comment]
firefox does not get any data from node, in the firefox console says can't execute CORS

**Comment by karalabe** [comment]
Your CORS domain is the origin domain your website runs on. Currently your `127.0.0.1.8102` would suggest you try to access geth from a web server running on your local machine, but looking at your `--rpcport` option, I see that you've assigned geth that port. So your CORS configs esentially mean that geth allows itself only to talk to itself :P 

if you are running a website from `example.com`, then you need to set *that* as the `--rpccorsdomain`.

**Comment by vitaliy-kuzmich** [comment]
ok, then please tell me what should I write? https://drive.google.com/file/d/0BxVQGS7mU5d0SkRfVFlpdzNEQk0/view when it uses that address in requests? I put * when make that screenshot. but I open it for everyone(

**Comment by vitaliy-kuzmich** [comment]
but how is it possible to predict out port from browser? because it opens random...

**Comment by vitaliy-kuzmich** [comment]
thank you --rpccorsdomain "localhost:80" works now from html file.

**Comment by hongsw** [comment]
`
geth --rpc --rpccorsdomain "http://localhost:8080"  
`
worked for me

**Comment by keltanas** [comment]
`geth --rpc --rpccorsdomain "*"`

**Comment by Yooooomi** [comment]
`--rpccorsdomain "*"` didn't work for me. I'm using `--rpccorsdomain=*`
Note the `=` and no quotes

**Comment by mbsaberi** [comment]
I've installed Apache/PHP to talk to Geth (Using localhost:8545 as the JSON-RPC server).  
Is using `--rpccorsdomain` recommended or even required while using Geth only on a local machine like this?

**Comment by TheoThug** [comment]
> I've installed Apache/PHP to talk to Geth (Using localhost:8545 as the JSON-RPC server).
> Is using `--rpccorsdomain` recommended or even required while using Geth only on a local machine like this?

No. You don't need to set an rpccorsdomain if you're running your app locally.
