### ISSUE TITLE
Pulling stable docker version

### ISSUE THREAD

**Issue by nickluijtgaarden** [ethereum/go-ethereum#17769]
Hello!

How can I pull the geth 1.8.16 stable version from docker?

Currently, if i pull the ethereum/client-go image, I receive the unstable 1.8.17 version:

`docker pull ethereum/client-go`

Thanks!

**Comment by wuxiangzhou2010** [comment]
Please use with a version tag:

 `docker pull ethereum/client-go:v1.8.16`
