### ISSUE TITLE
Whisper payload encoding differences vs Parity

### ISSUE THREAD

**Issue by arnetheduck** [ethereum/go-ethereum#17761]
Comparing the whisper payloads of Geth and Parity, there seems to be a few differences - generally, geth payload follows https://eips.ethereum.org/EIPS/eip-627

https://github.com/paritytech/parity-ethereum/blob/cc963d42a06bcae2480cec657fa4b55a829fdaa6/whisper/src/rpc/payload.rs#L147

* Parity adds a payload version field, geth does not
* Parity puts padding length in bits 7-6, geth in 1-0
* Parity puts signature flag in bit 5, geth in bit 2 (same as above)

Further, the documentation states that AES nonce comes before message, whereas code seems to put it after instead - after is consistent with geth.
https://github.com/paritytech/parity-ethereum/blob/cc963d42a06bcae2480cec657fa4b55a829fdaa6/whisper/src/rpc/payload.rs#L34
https://github.com/paritytech/parity-ethereum/blob/cc963d42a06bcae2480cec657fa4b55a829fdaa6/whisper/src/rpc/crypto.rs#L82

go-ethereum:
https://github.com/ethereum/go-ethereum/blob/d3441ebb563439bac0837d70591f92e2c6080303/whisper/whisperv6/message.go#L300

**Comment by arnetheduck** [comment]
Also filed under https://github.com/paritytech/parity-ethereum/issues/9652

**Comment by gballet** [comment]
As already answered on gitter and https://github.com/paritytech/parity-ethereum/issues/9652#issuecomment-424637532 EIP-627 is the reference. I will work on a PR to bring Parity up to spec after devcon.
