### ISSUE TITLE
Geth keeps crashing in full or fast mode after adding keystore files

### ISSUE THREAD

**Issue by Bitbladesupport** [ethereum/go-ethereum#17787]
Hi there,

8cores 16gb Ram 400gb SSD newest Ubuntu 18
Geth version: `newest master branch`
OS & Version: Ubuntu 18

#### Expected behaviour
After Adding keystore files it shouldn't crash

#### Actual behaviour
crashes after 20-35minutes

#### Steps to reproduce the behaviour
add keystore files to the keystore folder and start geth:
geth --syncmode "fast" --rpc --rpcaddr 173.212.220.23 --rpcport 8555 --rpcapi="eth,net,web3,personal,txpool" --maxpeers 80 --cache 12000

Logfile: (to big for upload)
https://1drv.ms/u/s!An38OVIiD8ijhY0M3sptxIhQUcTx1g

**Comment by Bitbladesupport** [comment]
TRACE[09-29|13:58:22.770] >> PONG/v4                               addr=27.122.242.71:25333             err=nil
TRACE[09-29|13:58:22.771] >> PING/v4                               addr=27.122.242.71:25333             err=nil
TRACE[09-29|13:58:22.771] << PING/v4                               addr=27.122.242.71:25333             err=nil
TRACE[09-29|13:58:22.771] >> NEIGHBORS/v4                          addr=106.2.3.41:30303                err=nil
TRACE[09-29|13:58:22.772] >> NEIGHBORS/v4                          addr=106.2.3.41:30303                err=nil
TRACE[09-29|13:58:22.772] << FINDNODE/v4                           addr=106.2.3.41:30303                err=nil
TRACE[09-29|13:58:22.772] >> NEIGHBORS/v4                          addr=59.8.130.169:50505              err=nil
TRACE[09-29|13:58:22.773] >> NEIGHBORS/v4                          addr=59.8.130.169:50505              err=nil
TRACE[09-29|13:58:22.773] << FINDNODE/v4                           addr=59.8.130.169:50505              err=nil
TRACE[09-29|13:58:22.773] >> NEIGHBORS/v4                          addr=46.101.128.49:30303             err=nil
TRACE[09-29|13:58:22.774] >> NEIGHBORS/v4                          addr=46.101.128.49:30303             err=nil
TRACE[09-29|13:58:22.774] << FINDNODE/v4                           addr=46.101.128.49:30303             err=nil
TRACE[09-29|13:58:22.775] << NEIGHBORS/v4                          addr=149.28.50.115:30303             err=nil
TRACE[09-29|13:58:22.775] << NEIGHBORS/v4                          addr=149.28.50.115:30303             err=nil
DEBUG[09-29|13:58:22.792] Peer discarded announcement              peer=e34da8c4d30d1de8 number=6421103 hash=b195a9912349 distance=6421103
DEBUG[09-29|13:58:22.514] Recalculated downloader QoS values       rtt=4.748114212s  confidence=1.000 ttl=14.24435688s
TRACE[09-29|13:58:22.547] >> FINDNODE/v4                           addr=149.28.50.115:30303             err=nil
TRACE[09-29|13:58:22.797] >> PING/v4                               addr=18.219.79.33:30303              err=nil
TRACE[09-29|13:58:22.577] Accepted connection                      addr=52.158.236.194:57644
TRACE[09-29|13:58:22.798] >> FINDNODE/v4                           addr=158.69.66.245:30303             err=nil
TRACE[09-29|13:58:22.802] Skipping dial candidate                  id=a77a937adc95b352 addr=51.15.225.32:30303              err="recently dialed"
TRACE[09-29|13:58:22.803] Skipping dial candidate                  id=1016aadceab6709a addr=35.196.21.215:20303             err="recently dialed"
TRACE[09-29|13:58:22.803] Skipping dial candidate                  id=158f8aab45f6d19c addr=13.75.154.138:30303             err="already connected"
TRACE[09-29|13:58:22.803] Skipping dial candidate                  id=873b05dfc7927881 addr=138.68.158.158:30303            err="recently dialed"
TRACE[09-29|13:58:22.803] Skipping dial candidate                  id=6db053d305f431b7 addr=167.99.190.26:30303             err="already connected"
TRACE[09-29|13:58:22.803] Skipping dial candidate                  id=1184f5091d6eb5a9 addr=207.148.15.103:30303            err="recently dialed"
TRACE[09-29|13:58:22.803] New dial task                            task="dyndial 6b4ee12717043855 107.155.2.153:30303"
TRACE[09-29|13:58:22.805] Rejected peer before protocol handshake  id=761083f9322e27ef addr=52.158.236.194:57644            conn=inbound err="too many peers"
TRACE[09-29|13:58:22.805] Setting up connection failed             id=761083f9322e27ef err="too many peers"
DEBUG[09-29|13:58:22.811] Peer discarded announcement              peer=2ffef2652d57ea6d number=6421103 hash=b195a9912349 distance=6421103
DEBUG[09-29|13:58:22.859] Discarded propagated block, too far away peer=77a602ec84946a71 number=6421103 hash=b195a9912349 distance=6421103
DEBUG[09-29|13:58:22.865] Peer discarded announcement              peer=f327759f917fba8e number=6421103 hash=b195a9912349 distance=6421103
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xf6b8ac, 0x16)
/usr/lib/go-1.10/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc8728d0000, 0x10000000, 0xc4b0d61500, 0x1ba80d8)
/usr/lib/go-1.10/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x1b8e6c0, 0x10000000, 0x41c2f1)

**Comment by adamschmideg** [comment]
@Bitbladesupport does the problem persist or did lowering the cache setting solve it?
