### ISSUE TITLE
https://github.com/ethereum/wiki/wiki/JSON-RPC

### ISSUE THREAD

**Issue by uppercaveman** [ethereum/go-ethereum#17792]
![image](https://user-images.githubusercontent.com/4667056/46255033-dae9e680-c4ca-11e8-9c60-ac9c1e37aa1d.png)

Have you been attacked?

eth_getBalance -> sero_getBalance

where is "sero_getBalance" ?

**Comment by ligi** [comment]
Thanks for reporting @veox already fixed this: https://github.com/ethereum/wiki/wiki/JSON-RPC/_compare/fc2f5106365cc2209504645745b8ef31e7617741...00b8bab735f7b0a1be5b3b468340a3f978ce48b5
