### ISSUE TITLE
Is this a bug or a feature?

### ISSUE THREAD

**Issue by Xeenych** [ethereum/go-ethereum#17794]
Hi, this code throws an exception "Bad jump destination". Is it intended?

Code is:
0x600556735b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b

00 PUSH1 05
01 JUMP
02 PUSH20 5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b

You can see that "5b5b5b..." is JUMPDEST JUMPDEST JUMPDEST ....

Looks like geth parses contract's code only once. Should it reparse code at each jump?

**Comment by holiman** [comment]
You can't jump into a data section. No unwrapping of that kind is allowed in the EVM
