### ISSUE TITLE
FreeBSD installation instructions

### ISSUE THREAD

**Issue by 0mp** [ethereum/go-ethereum#17817]
The [wiki page](https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-FreeBSD) does not mention that it is possible to just install go-ethereum on FreeBSD with just

    pkg install go-ethereum

**Comment by gballet** [comment]
I just synced my ports to make sure, and the ports version is fairly oudated (v1.8.14). I have seen that [you updated it to 1.8.16](https://github.com/freebsd/freebsd-ports/commit/094cda59bbdeaea51c139299cc390f5724b9bbfe) but it doesn't seem to have made the release yet.

I'm checking that the method works and I'll update the page.

**Comment by gballet** [comment]
Wow, the binary version is even older, 1.8.9 !

**Comment by gballet** [comment]
@0mp updated, please re-open the issue if you feel something is missing.

**Comment by 0mp** [comment]
Thanks a lot!

BTW, there's no need to suggest the user to compile from ports to get the latest version. All they have to do is to switch to the *latest* branch from the *quarterly* branch in [pkg.conf(5)][1]. Then you'll be able to to install the latest version of a given program that is available in FreeBSD ports.

[1]: https://www.freebsd.org/cgi/man.cgi?pkg.conf
