### ISSUE TITLE
Clef signer to have trigger OnApproveSignData after a sign data request is approved

### ISSUE THREAD

**Issue by chikeichan** [ethereum/go-ethereum#17824]
Currently, when the signer approved a `account_signTransaction` transaction, an `OnApproveTx` method is triggered, of which the UI can then use to track past transactions. 

We would want similar behavior when user approve a sign data request, so that the UI can track past `account_sign` transaction as well. 

cc @holiman

**Comment by holiman** [comment]
Not sure this is needed, and if so, we can add later
