### ISSUE TITLE
Clef `addpw` should not take password via command line 

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#17829]
... but instead ask for the password, so it doesn't wind up in the bash history

**Comment by johnsBeharry** [comment]
@holiman, started working on this but there's a little issue I'd like clarified.

`clef addpw <address> <password>` is described as:
> The addpw command stores a password for a given address (keyfile). If you invoke it with only one parameter, it will remove any stored credential for that address (keyfile)

That would translate to the following behaviors:

```gherkin
Scenario: Add new credential
  Given I run "clef addpw 0x0000000000000000000000000000000000000000 abc"
  When I check the credentials file
  Then I see "0x0000000000000000000000000000000000000000"

Scenario: Remove credential
  Given I run "clef addpw 0x0000000000000000000000000000000000000000"
  When I check the credentials file
  Then I do not see "0x0000000000000000000000000000000000000000"
```

**The problem:**
1. Dropping the `<password>` arg for the prompt to fulfill this issue's requirements would conflict with the described "Remove credential" behavior.
2. "Remove credential" behavior is not yet implemented (or I just couldn't get it to work 😅).

**Proposed solution**
1. `addpw` is single purpose, update the description
2. Add a new `removepw` command to handle "Remove credential"

**Comment by holiman** [comment]
I agree. Perhaps change it to 'setpw`, since it can be used to change password as well as add one.

**Comment by adamschmideg** [comment]
Merged
