### ISSUE TITLE
Recommit option is ignored

### ISSUE THREAD

**Issue by Atrides** [ethereum/go-ethereum#17821]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.8.16`
OS & Version: Linux

#### Expected behaviour
Geth started with "geth --mine --miner.threads 1 --miner.recommit 15s"
But all blocks have interval 3 sec, which is by default in code, the same results for RPC - "new" blocks every 3 seconds
```

INFO [10-03|09:21:50.442] Commit new mining work                   number=6444365 sealhash=e39271?a335d9 uncles=0 txs=198 gas=7992285 fees=0.2241367567 elapsed=205.658ms
INFO [10-03|09:21:53.387] Commit new mining work                   number=6444365 sealhash=ac4851?6a234e uncles=0 txs=199 gas=7984416 fees=0.2256201377 elapsed=150.590ms
INFO [10-03|09:21:56.430] Commit new mining work                   number=6444365 sealhash=917c63?05c9ee uncles=0 txs=199 gas=7999878 fees=0.2293853324 elapsed=194.119ms
INFO [10-03|09:21:59.483] Commit new mining work                   number=6444365 sealhash=4b7929?7769d5 uncles=0 txs=200 gas=7982685 fees=0.2300963058 elapsed=246.323ms
INFO [10-03|09:22:02.413] Commit new mining work                   number=6444365 sealhash=8e5c62?1e4b2e uncles=0 txs=201 gas=7995559 fees=0.2399664459 elapsed=176.432ms
INFO [10-03|09:22:05.564] Commit new mining work                   number=6444365 sealhash=62fcd3?bfc3d6 uncles=0 txs=207 gas=7993651 fees=0.2434076438 elapsed=327.310ms
INFO [10-03|09:22:08.409] Commit new mining work                   number=6444365 sealhash=d85801?5fe338 uncles=0 txs=206 gas=7997517 fees=0.254790819  elapsed=172.870ms

```

**Comment by rjl493456442** [comment]
@Atrides Sorry I can reproduce the issue. Could you please double check the command args? I have the hunch that there are some incorrect command line args specified  so that the recommit doesn't be resolved

**Comment by rjl493456442** [comment]
Any feedback on this issue?

**Comment by adamschmideg** [comment]
No response from the original reporter
