### ISSUE TITLE
Rpc eth_call returns 0x000 and eth.call returns correct value

### ISSUE THREAD

**Issue by d11e9** [ethereum/go-ethereum#1782]
Related issue: https://github.com/ethereum/web3.js/issues/314 with some more details.

Given a contract as in the linked issue, rpc server responds with all `0x0000...` to the following request:

    {
      "jsonrpc": "2.0",
      "method": "eth_call",
      "params": [
        {
          "to": "0xa614801e000fce6b9b9e9ba83ec18d3f71174883",
          "data": "0x3c6bb436"
        },
        "latest"
      ],
      "id": 24
    }

While calling directly on the console, like so:

    eth.call({to: "0xa614801e000fce6b9b9e9ba83ec18d3f71174883", data: "0x3c6bb436"})

Returns the correct value (ie: not `0x0000...`).

**Comment by obscuren** [comment]
`eth.call` does a `eth_call`. I'm sure web3.js does some black magic. @frozeman can probably help you out.

**Comment by frozeman** [comment]
@debris could you look at this?

**Comment by frozeman** [comment]
hm, actually this should just work, could you run it in a browser and see in the network tab, what web3.js actually sends? It might be that he right pad something here, but i believe no.

**Comment by d11e9** [comment]
@frozeman web3 sends the jsonrpc posted above. To clarify `eth.call(...)` when run in `geth console` returns the correct value. But when jsonrpc is sent from the clientside via web3.js rpc (`geth`) responds with `0x0000...`

**Comment by frozeman** [comment]
the version of web3 in the console is normally older than when you link it yourself. web3 was updated, could you please try develop and see if you now get 0x000.. in the console as well?

Normally web3 is not changing the output, besides transforming it into readable values.

But maybe there is a regression somewhere.

**Comment by d11e9** [comment]
Must be, I guess I can try use the bundled (older version) and confirm the regression at least.

**Comment by obscuren** [comment]
Closing this issues as it appears to be a `web3` issue
