### ISSUE TITLE
Need more chain event or API

### ISSUE THREAD

**Issue by ysqi** [ethereum/go-ethereum#17822]
hi all,
     I have a plan to write all block to relational database, but I am disappointed that I can't get more detailed data without changing the source code of go-ethereum.

Here's why：
1. LevelDB does not support multi-process access
2. go-ethereum only support subscribe little event (ChainEvent、ChainHeadEvent、ChainSideEvent、RemovedLogsEvent)

I want get more detail information about process new block:
- [x]  Block Data 
- [x]  Transaction
- [x]  Logs
- [ ]   Recipes  (Used to record transaction execution results)
- [ ]   State Journal  （Used to track balance change details）
- [ ]   Exec Tx return value ( Used to record transaction execution output) . However, this data was directly abandoned except for the deployment of new contracts.

What I want  to ask is :
1. Do you support this feature?  I am happy to implement them and push request if it is possible.
2. Do you have any better solutions to get the data? 

thanks all.

**Comment by fjl** [comment]
The best way is to subscribe to chain head events, then fetching the remaining data through other API calls when there is a new block.

**Comment by ysqi** [comment]
thanks, I think the best way is use debug_tracBlock api。
