### ISSUE TITLE
Geth console contract interaction is different when compared with Remix IDE

### ISSUE THREAD

**Issue by diego-lima** [ethereum/go-ethereum#17833]
# Geth console (or solc compiler, can't tell) bug
I found evidences of a problem that lies somewhere between the solc compiler or geth console. I don't know which one is actually the source of this bug. 

The bug is (apparently): I can't add too many attributes to a Solidity struct inside a contract when using geth console + solc compiler.

I had no problem testing my contract inside Remix IDE, but couldn't get it to work using solc+geth console.

I had a list(array) of structs, and two functions: the first would put new data to array, the second would return all data contained inside the array.

In Remix IDE, I could put new data and see it using the listing function. But compiling the same contract using solc and testing the same functions using geth console only got me some empty arrays (like `[[],[],[]]`).

Below reads:

## 1. Explanation

Suppose there are three pieces of information I want to store: `bytes32 food`, `uint weight` and `address owner`.

I wrote contracts for storing some structs with these attributes, with functions for putting new data, and listing all data. But I couldn't have a struct with all 3 attributes working together. This means:
* `food` and `owner` worked
* `food` and `weight` worked
* `weight` and `owner` worked

But all three together did not work:

* `food`, `weight`, `owner`

For each situation, I had a `put` function, to store new data in an array, and `list` function, to retrieve all data.

I compiled and deployed using both Remix IDE and solc compiler (with geth console). It always worked on Remix, but it only worked on solc+geth when I only had 2 attributes.

## 1. Reproducing

This is an example contract. It defines a `Bowl` structure, which holds text, integer and address attributes.
It has a `bowlArray` for storing `Bowl`s, and functions to store and retrieve `Bowls.`

```js
pragma solidity ^0.4.23;
contract Kitchen {
    struct Bowl {
        bytes32 food;
        address owner;
        uint weight;
    }

    Bowl[] bowlArray;
    
    function put(bytes32 _food, uint _weight) public returns (uint){
        return bowlArray.push(
            Bowl({food: _food, weight: _weight, owner:msg.sender})
        ) - 1;
    }
        
    function listBowls() public view returns (bytes32[], uint[], address[]) {
        uint[] memory weights = new uint[](bowlArray.length);
        bytes32[] memory foods = new bytes32[](bowlArray.length);
        address[] memory owners = new address[](bowlArray.length);

        for (uint i = 0; i < bowlArray.length; i++){
            weights[i] = bowlArray[i].weight;
            foods[i] = bowlArray[i].food;
            owners[i] = bowlArray[i].owner;
        }

        return (foods, weights, owners);
    }
}  
```

So, I can successfully:

1. Compile and deploy this contract via Remix IDE
2. Call `put` function to store new data
3. Call `listBowls` function to retrieve stored data and actually see all stored data

I was hoping to achieve the same results in **geth console**:

```js
// var contract = the deployed contract
contract.put("beans", 12);
// wait a few moments for transaction to be mined...
contract.listBowls()
// this should read something like [[foods], [weights], [owners]]
// > [["0x6265616e73000000000000000000000000000000000000000000000000000000"], [12], ["0x8b1223141c073f698411d34ad1725dafbef1933d"]]
```

But what I actually get is

```js
> [[],[],[]]
```

BUT, if I change the `Bowl` structure to have only two fields, whatever they may be, it works. In the below example, I removed the `weight` attribute from the `Bowl` structure:

```js
pragma solidity ^0.4.23;

contract Kitchen {
    struct Bowl {
        bytes32 food;
        address owner;
    }

    Bowl[] bowlArray;
    
    function put(bytes32 _text) public returns (uint){
        return bowlArray.push(
            Bowl({food:_text, owner:msg.sender})
        ) - 1;
    }
        
    function listBowls() public view returns (bytes32[], address[]) {
        bytes32[] memory foods = new bytes32[](bowlArray.length);
        address[] memory owners = new address[](bowlArray.length);

        for (uint i = 0; i < bowlArray.length; i++){
            foods[i] = bowlArray[i].food;
            owners[i] = bowlArray[i].owner;
        }

        return (foods, owners);
    }
}  
```

So, in the geth console:

```js
// var contract = the deployed contract
contract.put("beans");
// wait a few moments for transaction to be mined...
contract.listBowls()
// this should read something like [[foods], [owners]]
// > [["0x6265616e73000000000000000000000000000000000000000000000000000000"], ["0x8b1223141c073f698411d34ad1725dafbef1933d"]]
```

And the result I get:

```js
> [["0x6265616e73000000000000000000000000000000000000000000000000000000"], ["0x8b1223141c073f698411d34ad1725dafbef1933d"]]
```

I also tried with only `food` and `weight` attributes, and it also worked both in Remix and geth console.

Anytime I had 3 different attributes, it stopped working in geth console, but continued to work as expected in Remix.

Am I missing something?

## 3. System information

Geth version: `1.8.12-stable-37685930`
Solc version: `0.4.24+commit.e67f0147.Linux.g++`
OS & Version: `Ubuntu 18.04.1 LTS`

**Comment by gballet** [comment]
I'm suspecting this is related to https://github.com/ethereum/go-ethereum/issues/14649

I have a fix in the pipe, will get back to this when it's deployed.

**Comment by diego-lima** [comment]
@gballet , I ran into another bug, which I soon found it to be related to `solc`, not `geth`.

I was having trouble calling state-changing functions on my contracts.

I solved my issue downgrading the `solc` version. I described my process on [StackExchange](https://ethereum.stackexchange.com/q/72070/46481).

Do you think this bug could be related to the one described in this page?

**Comment by gballet** [comment]
These doesn't seem related, no. This one seems to be a JS interpreter issue.
