### ISSUE TITLE
core: improve test coverage

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#1783]
Issue to track coverage of core packages and subsequent tests & cleanup

Core packages code not covered by https://github.com/ethereum/tests

This list includes functions not used by consensus-critical code but used by e.g. RPC API - please cross out those once verified that they cannot affect consensus.

Also it exposes some unused code and parts of code that cannot be reached in current use, e.g. some internal RLP decoding error clauses which cannot happen unless there is DB corruption or some other internal bug that can't really be triggered by a valid test scenario.

core/types/block.go:
- [ ] `NewBlock` when there are no txs.
- [ ] `(b *Block)` ValidateFields (used by eth/handler.go when a block message is received)

core/types/block.go:
- [ ] `(self *Receipt) Logs()`
- [ ] `(self *Receipt) RlpEncode()` when RLP encoding fails
- [ ] `(self *Receipts) RlpEncode()`

core/types/transaction.go:
- [x] `IsContractAddr` (unused, removing)
- [ ] `NewContractCreation` (not consensus protocol, coverage should be added in xeth as it's used by APIs)
- [x] `NewTransaction` (not used by consensus protocol. covered by core/types and eth/handler tests)
- [x] `(tx *Transaction) Cost` not used by consensus protocol, covered by core unit tests.
- [ ] `(tx *Transaction) publicKey()` when public key _after_ recovery is invalid.
- [ ] `(tx *Transaction) WithSignature` not used by consensus protocol. partly covered by core unit tests but needs test for when crypto.Sign fails.
- [ ] `(tx *Transaction) SignECDSA` same as above

core/state/managed_state.go: no coverage except for constructor
core/state/state_object.go:
- [x] `(self *StateObject) Reset()` unused, removing
- [ ] `NewStateObjectFromBytes` error on RLP decoding
- [ ] `(c *StateObject) setAddr` error on RLP decoding
- [x] `(c *StateObject) GetInstr` unused, removing
- [x] `(self *StateObject) Set` unused, removing
- [x] `(c *StateObject) N()` unused, removing
- [x] `(c *StateObject) Init()` unused, removing
- [x] `(c *StateObject) Code()` used by xeth
- [x] `(self *StateObject) SetInitCode` unused, removing
- [x] `(self *StateObject) EachStorage` used by VM debug printing
- [x] `(c *StateObject) RlpDecode` unused, removing

core/state/statedb.go:
- [x] `(self *StateDB) HasAccount` not used by consensus protocol. used by tx pool and tests
- [ ] `(self *StateDB) GetNonce` if stateObject == nil
- [ ] `(self *StateDB) GetState` if stateObject == nil
- [ ] `(self *StateDB) IsDeleted` if stateObject == nil
- [x] `(self *StateDB) SetCode` not used by consensus protocol, used when first writing genesis block before connecting to network.
- [ ] `(self *StateDB) Delete` if stateObject == nil
- [x] `(s *StateDB) Cmp` unused, removing
- [x] `(s *StateDB) Trie()` unused, removing
- [x] `(s *StateDB) Reset()` unused, removing

core/vm/context.go:
- [ ] `(self *Context) SetCode` used in VM but seems to not be tracked due to interface?

core/vm/errors.go:
- [x] `StackErr` unused, removing
- [x] `(self StackError) Error()` unused, removing
- [x] `IsStackErr` unused, removing

core/vm/memory.go:
- [ ] `(m *Memory) Set if size > uint64(len(m.store))`
- [ ] `(self *Memory) Get    if len(self.store) <= offset (no-op return)`
- [ ] `(self *Memory) GetPtr if len(self.store) <= offset (no-op return)`
- [x] `(m *Memory) Data()` not used by consensus protocol, used by debugging code

core/vm/stack.go:
- [x] `(st *stack) Data()` not used by consensus protocol, used by debugging code

core/vm/vm.go:
- [x] `case SSTORE:` stack underflow, new test added to cover this
- [x] `(self *Vm) Env()` used by VirtualMachine interface 

core/block_cache.go : 0 coverage

core/block_processor.go:
- [ ] `(self *BlockProcessor) ChainManager()`
- [x] `(self *BlockProcessor) ApplyTransactions` if transientProcess. always set to false when used by consensus protocol. only true when called from miner worker.
- [x] `(sm *BlockProcessor) RetryProcess` Not used by consensus protocol. Used by RPC API for debugging.
- [ ] `(sm *BlockProcessor) Process` if sm.bc.HasBlock(block.Hash())
- [ ] `(sm *BlockProcessor) GetBlockReceipts` not used by consensus protocol. used by RPC API and gas price oracle.
- [ ] `(sm *BlockProcessor) GetLogs` not used by consensus protocol. used by RPC API, tests.
- [ ] `ValidateHeader` if uncle ts is too big - **NEEDS CONSENSUS TEST**

core/canary.go:: 0 coverage

core/chain_manager.go:
- [x] `NewChainManager` writing of genesis block. used when starting sync from scratch. well verified but would be nice to cover by unit test. not really part of consensus protocol.
- [ ] `NewChainManager` if bc.setLastState() failed
- [x] `NewChainManager` if bad block hash was found. **indirectly tested through consensus test, but we should definitely add a unit test for bad blocks in general.** unit test: https://github.com/ethereum/go-ethereum/pull/1803
- [x] `(bc *ChainManager) SetHead` covered by bad hashes unit test above
- [x] `(self *ChainManager) GasLimit()`
- [x] `(self *ChainManager) LastBlockHash()`
- [ ] `(self *ChainManager) Status()`
- [x] `(bc *ChainManager) recover()` will be removed by https://github.com/ethereum/go-ethereum/pull/1756
- [x] `(bc *ChainManager) setLastState()` if last block was not found
- [x] `(bc *ChainManager) Reset()` will be removed by https://github.com/ethereum/go-ethereum/pull/1756
- [ ] `(bc *ChainManager) removeBlock`
- [ ] `(bc *ChainManager) ResetWithGenesisBlock`
- [x] `(self *ChainManager) Export` : https://github.com/ethereum/go-ethereum/pull/1809
- [x] `(self *ChainManager) ExportN`
- [ ] `(bc *ChainManager) insert` if error when writing head
- [ ] `(bc *ChainManager) insert` if error when writing checkpoint
- [ ] `(bc *ChainManager) Genesis()`
- [ ] `(self *ChainManager) GetBlockHashesFromHash`
- [ ] `(self *ChainManager) GetUnclesInChain`
- [ ] `(bc *ChainManager) Stop()`
- [ ] `(self *ChainManager) procFutureBlocks()`
- [ ] `(self *ChainManager) WriteBlock` if error when merging chains
- [ ] `(self *ChainManager) WriteBlock` if error when writing block to db
- [ ] `(self *ChainManager) InsertChain` if interrupt during chain processing
- [ ] `(self *ChainManager) InsertChain` if bad hash found
- [ ] `(self *ChainManager) InsertChain` if block processing returns a "known block" error
- [ ] `(self *ChainManager) InsertChain` if block processing finds block is not-too-far-in-future and adds block to futureBlocks queue
- [ ] `(self *ChainManager) InsertChain` if block processing returns "parent error" and parent is among future queued blocks
- [ ] `(self *ChainManager) InsertChain` if writing block to db gives error
- [ ] `(self *ChainManager) InsertChain` if status is "SplitStatTy"
- [ ] `(self *ChainManager) diff` if if oldBlock.NumberU64() > newBlock.NumberU64()
- [ ] `(self *ChainManager) diff` if oldBlock == nil
- [ ] `(self *ChainManager) diff` if newBlock == nil
- [ ] `(self *ChainManager) diff` if oldBlock == nil in construction of new chain
- [ ] `(self *ChainManager) diff` if newBlock == nil in construction of new chain
- [ ] `(self *ChainManager) merge` if call to diff function failed
- [ ] `(self *ChainManager) update()` if quit chan matches in select
- [x] `verifyNonces` if length of blocks is less than number of workers - covered by unit tests
- [x] `verifyNonces` if quit chan matches in select - covered by unit tests

core/chain_util.go:
- [x] `CalcDifficulty` `if periodCount.Cmp(common.Big1) > 0` (though covered by core package tests which uses the common difficulty tests. However, in those tests, `if diff.Cmp(params.MinimumDifficulty) < 0` is not covered.
- [ ] `GetBlockByHash` if RLP decoding of block fails
- [ ] `GetBlockByNumber` if hash retrieved from number is empty
- [ ] `WriteCanonNumber` if writing to DB failed
- [ ] `WriteHead`       if writing to DB failed
- [ ] `WriteBlock`      if writing to DB failed

core/default_genesis.go: 0 coverage
core/genesis.go: 0 coverage

core/error.go:
- [ ] `IsUncleErr`
- [ ] `IsValidationErr`
- [ ] `IsBlockNonceErr`
- [ ] `IsTDError`

core/state_transition.go:
- [ ] `(self *StateTransition) To()` if `self.msg` or `self.msg.To()` is empty
- [ ] `(self *StateTransition) BuyGas()` if `self.From()` returns error

core/transaction_pool.go: 18% coverage, not really in scope of consensus tests

core/transaction_util.go: 
- [ ] `PutTransactions` if RLP encoding of tx fails
- [ ] `PutTransactions` batch write
- [ ] `PutReceipts` if RLP encoding of tx fails
- [ ] `PutReceipts` batch write
- [ ] `GetReceipt`
- [ ] `GetBlockReceipts` if RLP decoding fails
- [ ] `PutBlockReceipts` if RLP encoding fails
- [ ] `PutBlockReceipts` if DB write fails

core/vm_env.go:
- [ ] `(self *VMEnv) Origin()`
- [ ] `(self *VMEnv) Difficulty()`
- [ ] `(self *VMEnv) GasLimit()` 
- [ ] `(self *VMEnv) Value()`
- [ ] `(self *VMEnv) SetVmType`
- [ ] `(self *VMEnv) GetHash`
- [ ] `(self *VMEnv) Transfer`
- [ ] `(self *VMEnv) CallCode`
- [ ] `(self *VMEnv) StructLogs()`
- [ ] `(self *VMEnv) AddStructLog`

**Comment by fjl** [comment]
This is outdated. Many functions referenced here don't exist anymore.
