### ISSUE TITLE
retrieved hash chain is invalid

### ISSUE THREAD

**Issue by DengMins** [ethereum/go-ethereum#17847]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

Geth version: `geth  1.8.15-stable`
OS & Version: Ubuntu 5.4.0-6ubuntu1~16.04.4

Please tell me what's wrong with the synchronization block. I tried the updated version, but I didn't solve   

![r1 a3i5 qb2a7 70w lo7](https://user-images.githubusercontent.com/20965425/46512167-1a2a8580-c885-11e8-9cee-50867ab4c070.png)

**Comment by zhang6321615** [comment]
You can try to delete the database once and resynchronize the block.

**Comment by DengMins** [comment]
I tried. It's not valid.

**Comment by DengMins** [comment]
> You can try to delete the database once and resynchronize the block.

I tried. It's not valid.

**Comment by holiman** [comment]
Should be fixed as of today: https://github.com/ethereum/go-ethereum/pull/17839

**Comment by DengMins** [comment]
Yes, it has merged, I updated, but it seems that there are more problems.
![image](https://user-images.githubusercontent.com/20965425/46525161-76a99700-c8bd-11e8-9bd3-b1399f142b54.png)

**Comment by DengMins** [comment]
@holiman  Yes, it has merged, I updated, but it seems that there are more problems.

![image](https://user-images.githubusercontent.com/20965425/46525327-db64f180-c8bd-11e8-8237-da09745ad138.png)
