### ISSUE TITLE
How to add a new opcode in evm that solidity compiles correctly？

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#17842]
I'm trying to verify the nonce that produced through ethash in contract, so that I can verify the memory of a computer. but the problem is that the ethash algorithm must have a cache of 16M at least to verify,  
while it is inefficient through contract to implement it, so I'm try to add a new opcode or modify an existing opcode like opdifficulty to complete the same function, but the problem is that when I compile the new contract which my new opcode in, it throw erros `Error: Different number of arguments in return statement than in returns declaration. return block.difficulty(....)`
so what can i do to add a new opcode or modify an existing opcode which new parameter or return type?

Or is there any other method that can verify the ethash's nonce?
Or is there any other method that can verify a computer's memory?

**Comment by MariusVanDerWijden** [comment]
Why would you want to verify the memory of a computer through a contract?
Use something like memtest https://www.memtest86.com/ to check your memory.
I don't think ethash verification should be attempted from within a contract as it is verified by the executing machine already.
I'll close this issue, please reopen if I missed something
