### ISSUE TITLE
Synchronisation failed, dropping peer, ROPSTEN network stop syncing on block 4169999

### ISSUE THREAD

**Issue by UmSergDev** [ethereum/go-ethereum#17848]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

Geth version: Geth/v1.8.16-stable-477eb093/darwin-amd64/go1.11
OS & Version: Mac OS Mojave
Commit hash : ROPSTEN network stop syncing!

#### Actual behaviour
Welcome to the Geth JavaScript console!

instance: Geth/v1.8.16-stable-477eb093/darwin-amd64/go1.11
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> web3.eth.syncing
{
  currentBlock: 4169999,
  highestBlock: 4174845,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 4169999
}

#### Steps to reproduce the behaviour

geth --datadir /mydatadir --testnet --rpc --syncmode "full" --rpcapi "web3,personal,admin,debug,db,net,eth,miner,rpc,txpool" --rpccorsdomain "*" --rpcaddr 127.0.0.1 --rpcport 8545 console

#### Backtrace

ERROR[10-05|11:11:31.773] 
########## BAD BLOCK #########
Chain config: {ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: <nil> Engine: ethash}

Number: 4170000
Hash: 0x82668407fd4e81d7a42627150d2c94e1cdd3fcaa887c2b3783db8c3a6e81947d

Error: invalid mix digest
##############################
 
WARN [10-05|11:11:31.773] Synchronisation failed, dropping peer    peer=9c854be9dc0b2e79 err="retrieved hash

**Comment by brunokenj** [comment]
Hi, can you share some valid node with Ropsten? I tried sometimes but I'm connecting in another node of testnet highestBlock: 3418716. 

I tried this nodes but still invalid.
admin.addPeer('enode://94c15d1b9e2fe7ce56e458b9a3b672ef11894ddedd0c6f247e0f1d3487f52b66208fb4aeb8179fce6e3a749ea93ed147c37976d67af557508d199d9594c35f09@192.81.208.223:30303')
admin.addPeer('enode://6332792c4a00e3e4ee0926ed89e0d27ef985424d97b6a45bf0f23e51f0dcb5e66b875777506458aea7af6f9e4ffb69f43f3778ee73c81ed9d34c51c4b16b0b0f@52.232.243.152:30303')

My geth.

VERSION:
   1.8.16-stable-477eb093

geth --testnet attach

> eth.syncing
{
  currentBlock: 3418706,
  highestBlock: 3418716,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 3418706
}


peers: [{
      caps: ["eth/62", "eth/63", "par/1", "par/2", "par/3", "pip/1"],
      id: "36af4d9f8785ee1bc3d8c04eb76bbb705a8b08fc044ef4ffb416808ab3680e18c69e0bda10e25b79920d8e582f8ec65918a223d81efc3330565fc899ae5ecdf9",
      name: "Parity-Ethereum/v2.0.6-stable-549e202-20180919/x86_64-linux-gnu/rustc1.29.0",
      network: {
        inbound: false,
        localAddress: "172.31.20.196:47694",
        remoteAddress: "35.174.48.76:30303",
        static: false,
        trusted: false
      },
      protocols: {
        eth: {...}
      }
  }, {
      caps: ["eth/62", "eth/63"],
      id: "566009e2787aaabe68012dd63bad920a2eb32b0dedea7b0596635fe3e687a1a0971322a436725d7de93c2bf9005499e9cc898c824cdd40ba5d7e579a54afd40c",
      name: "Geth/v1.8.16-stable-477eb093/linux-amd64/go1.10.1",
      network: {
        inbound: false,
        localAddress: "172.31.20.196:39256",
        remoteAddress: "35.178.193.227:30303",
        static: false,
        trusted: false
      },
      protocols: {
        eth: {...}
      }
  }, {
      caps: ["eth/63"],
      id: "744316f39e9cb1e5e7013e802731d1e9362a51f6e1030781953b98aae088ce0651f0add5954516c519758a813e705bed127fa933c0d3c0ab970e8ccfab5a2706",
      name: "Geth/v1.8.16-stable-477eb093/linux-amd64/go1.10",
      network: {
        inbound: false,
        localAddress: "172.31.20.196:39522",
        remoteAddress: "47.75.156.101:30303",
        static: false,
        trusted: false
      },
      protocols: {
        eth: {...}
      }
  }],
