### ISSUE TITLE
disasm is missing. Please install go-ethereum and make sure disasm is in the path.

### ISSUE THREAD

**Issue by goyalvartul** [ethereum/go-ethereum#17855]
#### Actual behaviour: Oyente file is not working, while installing manually disasm.

artul:oyente-benchmarks-aaec10f vartul.goyal$ python oyente.py /Users/vartul.goyal/tools/go-ethereum/contracts/chequebook/contract/chequebook.sol

**Comment by gballet** [comment]
@goyalvartul could you please explain how you get to this point and why you think it's a geth problem?

**Comment by gballet** [comment]
No response from PR creator, closing.
