### ISSUE TITLE
404 Not Found Error when adding repository

### ISSUE THREAD

**Issue by Tesla-Nikola-2012** [ethereum/go-ethereum#17859]
Issue attempting to add the repository to download the ethereum software.  It seems like a server might be down maybe? Note the "404 Not Found" error below.  Below is the output:

sudo add-apt-repository -y ppa:ethereum/ethereum

Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]   
Hit:3 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic InRelease       
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]    
Get:5 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB] 
Ign:6 http://ppa.launchpad.net/ethereum/ethereum-qt/ubuntu bionic InRelease    
Hit:7 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease    
Err:8 http://ppa.launchpad.net/ethereum/ethereum-qt/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/ethereum/ethereum-qt/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by f4rm0r** [comment]
I also have the same problem, commenting so I will get notifications.
