### ISSUE TITLE
CPU and MEM high!!! 

### ISSUE THREAD

**Issue by ronnierry** [ethereum/go-ethereum#17861]
#### start 
root      8469     1 99 12:37 pts/0    08:22:42 ./geth --datadir ./mainnet --rpc --rpcaddr 0.0.0.0 --rpcport 8081 --identity ethereum ipc --rpcapi web3,eth,net,personal,db,admin

#### problem
![image](https://user-images.githubusercontent.com/30022256/46593644-4d2c7d80-cb00-11e8-9088-1964c7167667.png)

#### System information

Geth version: 
![image](https://user-images.githubusercontent.com/30022256/46593657-62a1a780-cb00-11e8-867f-7ada2fd7f9aa.png)

Version: Linux
![image](https://user-images.githubusercontent.com/30022256/46593679-8533c080-cb00-11e8-98ab-8849c62231a8.png)

Commit hash : (if `develop`)

#### log
![image](https://user-images.githubusercontent.com/30022256/46593703-b3b19b80-cb00-11e8-8517-dba2361c93e3.png)

#### Backtrace

````
[backtrace]
````

**Comment by hapsody** [comment]
Same issue here.

Server
AWS t3.medium(64bit - ubuntu 16.04, 2core, 4GB Ram, 8GB Swap memory)
version : 1.8.1-stable, 1.8.16-stable
fast and light syncmode both.

geth --rinkeby --rpc --rpcaddr "0.0.0.0" --rpcvhosts=* --rpcport "8545" --rpccorsdomain "neojuneELB-1439772252.ap-northeast-2.elb.amazonaws.com" --rpcapi "eth,net,web3,personal,admin" --syncmode "light" --cache "64"

It also have been occurred. I used --cache flag and setting swap memory but it didn't work.
what am i suppose to do?

**Comment by karalabe** [comment]
@ronnierry Geth on mainnet will want to use by default (latest release at least) 4GB of RAM for caching + will probably consume more, maybe 6-7. As for the slow blocks, do you have SSD or HDD? Regarding high CPU use, I saw that you have your RPC open to the public internet, so you might have random remote machines trying to brute force your accounts (causing high memory and CPU use), never expose RPC to the internet.

@hapsody You ran Geth with 64MB of cache allowace, that's unusable on mainnet. Mainnet nowadays needs a lot of memory. Also don't bother with Swap, that just kills performance altogether.
