### ISSUE TITLE
how to use HSM to protect POA private key ?

### ISSUE THREAD

**Issue by liwei00wade** [ethereum/go-ethereum#17888]
how to use HSM to protect POA private key ?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
