### ISSUE TITLE
Unmarshal null result in rpc client should be avoid

### ISSUE THREAD

**Issue by NeoCN** [ethereum/go-ethereum#17893]
When use golang rpc client to call rpc api, the response is unmarshalled to the following struct first
https://github.com/ethereum/go-ethereum/blob/f951e23fb5ad2f7017f314a95287bc0506a67d05/rpc/client.go#L80-L89
With `Result  json.RawMessage`, when unmarshal json response with  null result like 
```json
{"jsonrpc":"2.0","id":1,"result":null}
```
after unmarshalled to the `jsonrpcMessage` struct, the `Result` filed is requal to `json.RawMessage([]byte("null"))`, not empty byte slice, and then go to the following process logic
https://github.com/ethereum/go-ethereum/blob/f951e23fb5ad2f7017f314a95287bc0506a67d05/rpc/client.go#L307-L317
The following code 
```golang
case len(resp.Result) == 0:
	return ErrNoResult
```
will never triggered and `err`/`resp.Error` are both nil,  so the default switch will be called
```golang
default: 
 	return json.Unmarshal(resp.Result, &result) 
```
and `resp.Result` is `[]byte("null")`, this will cause unmarshal error like `missing required field 'cumulativeGasUsed' for Receipt` which is misleading. 

In my opinion, when `{"jsonrpc":"2.0","id":1,"result":null}` rpc response is returned, the `ErrNoResult` error or some other predefined error  should be returned, not unmarshal error.  Unmarshal null result should be avoid !

My previous PR https://github.com/ethereum/go-ethereum/pull/17779

**Comment by fjl** [comment]
In #17779, you wrote: 

> use rcp client to get transaction receipt on the mainnet node, but, the tx hash is not existed,
> then, I got the error missing required field 'cumulativeGasUsed' for  
> Receipt which is a misleading error message returned by json.Unmarshal

`rpc.Client` handles `{"jsonrpc": "2.0", "id": 1, "result": null}` correctly. The error `ErrNoResult` is for cases where "result" field is **missing** (example: `{"jsonrpc": "2.0", "id": 1}`). 

Are you using the ethclient package to get the transaction receipt? ethclient handles null correctly by unmarshaling into `**types.Receipt`: 

```go
    var r *types.Receipt                                                                                      
    err := ec.c.CallContext(ctx, &r, "eth_getTransactionReceipt", txHash)                                     
    if err == nil && r == nil {                                                                                 
          // receipt not found
    }                                                                                                         
```

**Comment by NeoCN** [comment]
@fjl Thanks for your reply.  Yes, I am using  the ethclient package to get the transaction receipt. 
> ethclient handles null result by unmarshaling into `**types.Receipt`
this is the key information I missed~ Thanks.
