### ISSUE TITLE
EH syncing is ??

### ISSUE THREAD

**Issue by GusevVasily** [ethereum/go-ethereum#17890]
Good evening. Like synchronization was successful, but I can not understand why the command eth_syncing gives that still synchronized. Put parameter cache=4096, syncmode=full.

#### System information

Geth version: `1.8.17-stable`
OS & Version: Ubuntu 16.04.05

![screenshot_74](https://user-images.githubusercontent.com/21026700/46756509-55d3ae00-ccd0-11e8-9d3a-3f43532d608b.png)

**Comment by ligi** [comment]
It is not really clear what you are asking - you will need to provide more information

**Comment by GusevVasily** [comment]
Hello, @ligi 

Put on loading the blockchain, with the parameter cache=4096
Passed couple of days, I look, in the console of number of blocks which are the last. And it is dokachivaet once again a new, more fresh. That is, the blockchain is synchronized and it works to find new blocks. Check the condition of the team at_syncing - produces output similar to this: current_block is approximately equal to the same number of units that issued any sites with information OK bitcoin. A height_block is slightly larger than current, which is the wrong number of blocks. And my program can't get information from some get commands, because team etn_syncing gives such information that the blockchain is still downloading. Something like that...

Screenshots:
![screenshot_108](https://user-images.githubusercontent.com/21026700/47152748-33e8b580-d2e6-11e8-971b-d6556d22d2f0.png)
![screenshot_106](https://user-images.githubusercontent.com/21026700/47152752-364b0f80-d2e6-11e8-90e9-c9e365c7e089.png)
![screenshot_104](https://user-images.githubusercontent.com/21026700/47152756-3b0fc380-d2e6-11e8-920c-492d7666f734.png)
![screenshot_107](https://user-images.githubusercontent.com/21026700/47152759-3d721d80-d2e6-11e8-83b4-c8748c0063e1.png)

**Comment by GusevVasily** [comment]
And the situation with eth classic (ETC) is much better, there the command etn)syncing gives that the blockchain is synchronized. What could be the problem? Binary geth was downloaded, not the compiled...

**Comment by GusevVasily** [comment]
@ligi ?

**Comment by ligi** [comment]
Still not really sure what your problem is - perhaps it is just lost in translation. 
Do you use a SSD on this computer?

**Comment by GusevVasily** [comment]
@ligi 
No, I have HDD.
In the configuration I set the parameter 'cache=4096'and' sync mode=full'.
The ethereum-classic blockchain has been downloaded and is working. But with the usual, some problems. It shows in the api method 'eth_syncing' that the blockchain has not synchronized.
And I guess because of that, I don't see the transactions I sent to the generated wallets...

Screenshot from console:
![screenshot_152](https://user-images.githubusercontent.com/21026700/47562307-c3b1e380-d926-11e8-8c18-2234a32fad87.png)

====================

![screenshot_151](https://user-images.githubusercontent.com/21026700/47562310-c57ba700-d926-11e8-81dc-d13ff31c8de4.png)

====================

![screenshot_153](https://user-images.githubusercontent.com/21026700/47562342-d62c1d00-d926-11e8-81b3-9bcb29f367e7.png)

**Comment by ligi** [comment]
AFAIK it is currently not feasible to sync with an HDD and you need to use a SSD. A HDD is just too slow. 
Perhaps an action item here is that an warning/error is thrown when a user tries to sync with a HDD

**Comment by GusevVasily** [comment]
@ligi 
I don't have that much space on an SSD. Synchronization running in 'fast', in the console writes that shakes the block, check it against the number in 'etherscan.io', it was the last. And RPC api gives 'current Block' less by 100-200 than 'heightBlock'
