### ISSUE TITLE
Geth is broken on ropsten chain ( 1.8.17 )

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#17906]
#### System information

Geth version: `geth 1.8.17`
OS & Version: `Ubuntu 16.04`

#### Expected behaviour

Geth should sync on latest block

#### Actual behaviour

```
> eth.syncing
{
  currentBlock: 4230614,
  highestBlock: 4231263,
  knownStates: 58578162,
  pulledStates: 58578162,
  startingBlock: 4229999
}
```

```
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]: ERROR[10-13|19:38:06.801]
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]: ########## BAD BLOCK #########
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]: Chain config: {ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: 4230000 Engine: ethash}
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]: Number: 4230605
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]: Hash: 0xc358b4fb016f7cc1402619f292c92a5e58a473ef5243db00d3c59b3b9b7cb827
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 60243 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 0 153689 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 185665 [0 0 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 64 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 64 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 64 0 0 0 0 16 0 0 0 0 0 0 0 0 0 0
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 317762 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 128 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 4 0 0
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 432988 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 3797796 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 4876783 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 128 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 4909284 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 4941785 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 5667425 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 6393065 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 7118705 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 7844345 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 7905119 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 16
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:         &{[] 1 7937070 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 128 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]: Error: invalid gas used (remote: 7649670 local: 7937070)
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]: ##############################
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]:
Oct 13 19:38:06 ip-172-31-26-136 geth[28278]: WARN [10-13|19:38:06.801] Synchronisation failed, dropping peer    peer=c65b753536948650 err="retrieved hash chain is invalid"
```

#### Steps to reproduce the behaviour

Monitor the status of `eth_syncing` on a ropsten node after the Constantinople block 4230000.

**Comment by eosclassicteam** [comment]
Raw block query from parity & geth 

https://gist.github.com/veox/f274e3170e8677c7c318bc46b586be06

https://gist.github.com/eosclassicteam/4dcf3eb5726e9df8901da317da47d2cf

**Comment by MrLuit** [comment]
Made a little tool to compare Geth / Parity blocks on Ropsten: https://luit.me/eth-block-compare/

Seems like Geth isn't including transactions for some reason :confused:

**Comment by nicksavers** [comment]
Split seems to have happened in 4230605 indeed

The Parity block was on timestamp `1539451591`
The Geth block was on timestamp `1539456509` (over 1,5 hours later)

My conclusion would be that one transaction in the Parity block, wasn't acceptable in the Geth... and Parity had more mining power. 

One way to solve this would be to
- export block 4230605 from Parity into RLP
- run a memory and gas cost trace of both [Parity](https://wiki.parity.io/JSONRPC-trace-module#trace_block) and [Geth](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_traceblock) on this block
- do a diff compare between output logs
- figure out which transaction caused the issue and at which opcode it forks
- identify the bug and fix the respective client
- announce which client to update and start mining

If another one occurs, rinse repeat.

**Comment by sirnicolas21** [comment]
same issue here .... same block

**Comment by Maigre** [comment]
Same issue here, but at block **4238641**
geth 1.8.17-stable // Ubuntu 18.04

Where is the best place to be kept informed on this bug progress (new releases, etc..) ?
I ended up here because there is nothing on ethresear.ch and not much on /r/ethereum ...

Best,

**Comment by nicksavers** [comment]
@Maigre Block **4238641** also has [a conflict](https://gist.github.com/nicksavers/4c600155f4cf42b7d9905399dbc900f0). 

The thing is that if you did a fast-sync of Geth >1.8.17 _after the fork_ at block **4230605**, it would have probably skipped the check on that block and assume it's correct based on proof of work.... then break on **4238641**. Similarly, if you start fast-sync now, you'll skip fully verifying that block... etc. (explanation [here](https://github.com/ethereum/go-ethereum/issues/17883#issuecomment-428488082))

Now the issue has been found and can be reproduced ([test case here](https://gist.github.com/holiman/c87fc7cdba83086316df7a8b1a247fa6)). 

The cause was apparently an implementation detail of [EIP-1283](https://eips.ethereum.org/EIPS/eip-1283). Parity kept track of the refund inside each call, but defined it 'unsigned', which made it impossible to become negative (source in [Gitter chat](https://gitter.im/ethereum/AllCoreDevs?at=5bc3c1db64cfc273f9c93fcc)).

The solution discussed as of this moment is to use the interpretation of Geth. Parity has already solved the issue on their side with an update (https://github.com/paritytech/parity-ethereum/pull/9746). Miners will start mining on the Geth Constantinople chain on Ropsten to make sure it becomes the canonical chain. The Parity update should be able to follow it. If another conflict arises, it will be dealt with at that time.

Progress should be posted on [notes](https://notes.ethereum.org/s/SJE9O2ksQ), but it's a little bit behind on the latest information.

**Comment by Maigre** [comment]
Ok thanks, yes i was fast-syncing (it's default right ?) after the 4230605 fork.

I tried to re-launch geth with the enodes specified in the notes (i took the last 2 geth enodes),
to force the use of the geth chain but nothing seems to move. Should i reset and resync from scratch with those enodes ?

```
geth console --datadir '~/ethereum/testnet' --testnet --bootnodes enode://053d2f57829e5785d10697fa6c5333e4d98cc564dbadd87805fd4fedeb09cbcb642306e3a73bd4191b27f821fb442fcf964317d6a520b29651e7dd09d1beb0ec@79.98.29.154:30303,enode://561570ba6c2f297026e14af3e6a555759430a7f8a6d556ff157e804a31908ec8e1f73cc231163fa7281227f3b46f3f0fb3ea93f61fb1a95c90350efcbccfb419@34.236.254.125:30303
```
Or i should just wait that everything settle down ?
maybe my attempts to sync during fork-times are not helping :/

**Comment by MrLuit** [comment]
Turned out to be a Parity issue which forked the chain: https://twitter.com/lrettig/status/1051624092388986885

**Comment by Maigre** [comment]
I do also get this error as soon as i start miner thread:
everything is properly synced, but once `miner.start(1)` i got
```
ERROR[10-17|08:28:26.895] 
########## BAD BLOCK #########
Chain config: {ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: 4230000 Engine: ethash}

Number: 4230000
Hash: 0x250d0cc0497e72815b2bcb1efa95ebd0fc0e1a0811e8f4bfc9fb6b91b00deb75


Error: invalid difficulty: have 14784344571, want 14784343547
##############################
```

**Comment by holiman** [comment]
Closign this since afaik the ropsten constantinople issues have been fixed.
