### ISSUE TITLE
Mounting geth.ipc on Docker container

### ISSUE THREAD

**Issue by elim0322** [ethereum/go-ethereum#17907]
Hi team,

I'm trying to connect to `geth.ipc` on local host from a Docker container and I can't seem to connect to it. I'm submitting an issue here as it may be a bug or a feature and none of my colleagues seem to know the answer.

I have the below Python script (`test_ipc.py`) Dockerized:
```python
from web3 import Web3

web3 = Web3(Web3.IPCProvider("/Ethereum/geth.ipc"))
print(f'IPC connected: {web3.isConnected()}')
```

and running the following returns `IPC connected: False True True`:
```
docker run --network=host --mount type=bind,source=$HOME/Library/Ethereum,target=/Ethereum container1
```

I've asked the same question with no success:
https://ethereum.stackexchange.com/questions/60378
https://stackoverflow.com/questions/52715141

#### System information

Geth version: `1.8.14-stable`
OS & Version: OSX

#### Expected behaviour
`docker run ...` returns `IPC connected: True True True`

#### Actual behaviour
`docker run ...` returns `IPC connected: False True True`

#### Steps to reproduce the behaviour
Here is the Dockerfile:
```
FROM python:3.6-alpine
RUN apk add --no-cache gcc musl-dev
RUN pip install --upgrade pip && pip install web3
RUN mkdir /Ethereum
COPY test_ipc.py .
CMD ["python", "test_ipc.py"]
```

To build and run Docker:
```
docker build -t container1 .
docker run --mount type=bind,source=$HOME/Library/Ethereum,target=/Ethereum container1
```

**Comment by karalabe** [comment]
This seems to be a known issue in docker on macos: https://github.com/docker/for-mac/issues/483. Apparently you cannot share a unix socket betwen host-guest across macos-linux.
