### ISSUE TITLE
Ropsten Fork and eth_syncing results

### ISSUE THREAD

**Issue by ryanschneider** [ethereum/go-ethereum#17905]
#### System information

Geth version: `1.8.17`
OS & Version: Linux

#### Expected behaviour

`eth_syncing` should be `false` when a ropsten node is on the constantinople canonical head. 

#### Actual behaviour

The nodes routinely consider themselves to be syncing even though they appear to be on the canonical head.

```
> eth.syncing
{
  currentBlock: 4230133,
  highestBlock: 4230732,
  knownStates: 57056208,
  pulledStates: 57056208,
  startingBlock: 4229984
}
```

My theory is that `highestBlock` value is coming from a non-Constantinople node.  Is it possible that geth isn't rejecting the pre-fork chains when calculating `highestBlock`?
 
#### Steps to reproduce the behaviour

Monitor the status of `eth_syncing` on a ropsten node after the Constantinople block 4230000.

**Comment by postables** [comment]
I manage a large scale mining farm, from what I've read on Reddit people need to mine with geth? That's about all I can determine. If this is still an issue I can take down a few machines and put them over onto ropsten temporarily

**Comment by MrLuit** [comment]
This is actually because of a chain split between Geth and Parity :confused:

Related to #17906

**Comment by ryanschneider** [comment]
Ok, here's what I *think* happened, please correct me if wrong:

- The difference in `sstore` implementation led to two different chains.
- The majority of peers seem to be parity at the moment, but there are a couple geth peers
- So, my geth node kept choosing a parity peer when trying to sync
- Which led to the blocks being rejected during downloading
- However, since this is a consensus bug and not an explicit fork, there's no way for geth to know which `highestBlock` value is valid before downloading and verifying, so it has to report the highestBlock seen over all.

**Comment by MrLuit** [comment]
Turned out to be a Parity issue which forked the chain: https://twitter.com/lrettig/status/1051624092388986885
