### ISSUE TITLE
LES Status Message Always Reports `serveStateSince = 0`

### ISSUE THREAD

**Issue by EBGToo** [ethereum/go-ethereum#17900]
The LES Status message provided by a full or archival Geth node should include a valid `serveStateSince` optional parameter.  

The LES handshake protocol includes an exchange of status messages.   The Light Client receives a status message that includes information about the Geth node.  That received status message ought to represent the capabilities of the Geth node.  In particular, a non-archival node reports `serveStateSince` as block 0 - even though it can serve state only through, perhaps, the last thousand blocks.

A Light Client issuing a GetProofs message expects a valid result - a proof of the account state, including the account.  If the Geth node reports having state since 0 but only has state since 6,500,000 then the Light Client doesn't get a proof but instead gets RLP `[]`.

Note.  A related issues arrises: how should a Geth node serving light clients handle the Geth node purging history?  Options: a) boot all light clients (because they think the node is serving from X but now the node is serving from Y with Y > X) or b) don't purge until older light clients (using X) have dropped off.

#### System information

Geth version: 1.8.17-stable
OS & Version: OSX

#### Actual behaviour

When connecting to a non-archival Geth node:

````
ETH: LES: Recv: [ LES,          Status ] <=  35.193.192.189
ETH: LES: StatusMessage:
ETH: LES:     ProtocolVersion: 2
ETH: LES:     NetworkId      : 1
ETH: LES:     HeadNum        : 6501892
ETH: LES:     HeadHash       : 0x2d842eb36b62ee5e22d6296b951540d510ef54e71a731574da8534879df2faee
ETH: LES:     HeadTd         : 7180216660737580096962
ETH: LES:     GenesisHash    : 0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
ETH: LES:     ServeHeaders   : Yes
ETH: LES:     ServeChainSince: 0
ETH: LES:     ServeStateSince: 0
ETH: LES:     TxRelay        : Yes
ETH: LES:     FlowControl/BL : 300000000
ETH: LES:     FlowControl/MRR: 50000
ETH: LES:     FlowControl/MRC:
ETH: LES:         Request : 0 (Status)
````
#### Expected behaviour

The `ServeStateSince` (and likely `ServeChainSince`) should reflect the capabilities of the Node supporting the LES client.

**Comment by EBGToo** [comment]
Any expected date for addressing this?

**Comment by fjl** [comment]
@zsfelfoldi !!!

**Comment by zsfelfoldi** [comment]
@EBGToo Implementing this feature was postponed exactly because of the issue you mentioned. How to handle continous pruning has not been figured out yet but maybe this is the right time.
Now I think that specifying this as an absolute block number was probably a mistake but since it was never used for anything we can just as well change the spec. Since servers are either archive (keeping all state history, at least from a certain point) or automatically pruning (always having the last 128 states available for example, like Geth does) I think the spec should also allow specifying a relative value.
We could add an optional `serveStateRel` field. A client could assume that the state for block N is available if `serveStateSince` is specified AND `N >= serveStateSince` AND (`serveStateRel` is not specified OR `N >= currentHead - serveStateRel`). This would be easy to implement and could be released in the next Geth version (which will also bump LES protocol version to 3 so it is a good time to add something like this to the spec).

**Comment by EBGToo** [comment]
Thanks.

So essentially `serveState = max (serveStateSince, currentHead - N)`  (if N is provided)  

I think there is a race condition that clients would need to deal with... client expects blocks from X and makes a request for X, in the mean time, node moves on (current - N > X).  Maybe this 'race window' is minimized if client assumes N/2 is available (for example).  

In practice will the node's serveSince move block-by-block (as current block increments by one) or will it jump, like by N.  Specifically if N is 256, node guarantees `currentHead - 256` but it will actually provide `currentHead - 512` (or 511) and then 'jump' to `currentHead - 256` when purged?

Where can I find the 'LESv3' specification?

**Comment by zsfelfoldi** [comment]
If we allow automatic pruning on the server side (and this is the purpose of the proposed method) then the client should be prepared for that. Realistically the clients will be interested in new states most of the time, and if not, then they are going to need an archive server anyway. As you wrote, assuming a bit less on the client side is a safe strategy.
Providing more than what was announced in the handshake is always allowed of course so you can still use the relative method if you are not pruning block by block. Alternatively, the protocol allows explicit parameter changes is the Announce messages so if you only prune rarely then you can send a new value of `serveStateSince` at any time. This is also not implemented yet on the receiving end (it is ignored currently) but I will add it together with the other changes.
The LES/3 spec is still under construction, the new version is not officially released yet, it only exists in a PR: https://github.com/ethereum/go-ethereum/pull/19329

**Comment by zsfelfoldi** [comment]
Availability announcements relative to current head are now supported by LES/3 which is already on Geth master branch so this issue is resolved.
