### ISSUE TITLE
Automatization of addPeer

### ISSUE THREAD

**Issue by marcosmartinez7** [ethereum/go-ethereum#17917]
Hi,

this is more like a question than an issue, but i couldt find anything in the documentation about this. 

I have a private PoA network with 3 geth nodes, i connect them using addPeer and create p2p network, each node is connected with the rest of them

Now i want to create a bigger network, with 20 nodes, so i need to connect to the geth console and invoke the addPeer 20 x 20 = 400 times .. 

obviously this is unstable. 

I know there is an option to do this automatically, connecting the nodes to discovery/bootnodes, but i cant use a bootnode. Why? because bootnodes dont filter connections from the outside, so any hacker/malicious user could try to connect to my bootnode. 

See this related issue: https://github.com/ethereum/go-ethereum/issues/16057

So, what i have in mind to research is:

1.  Maybe i can create a bash script that connects to geth console and executes the addPeer too many times as nodes present but i want to know if there is any better approach
2. Maybe there is a way to add firewall rules to the bootnode , something like "only allow connections to the bootnode from the IPs of the 20 geth nodes". I dont know if this is possible without affecting the discovery protocol

Any thoughts about this scenario?

**Comment by fjl** [comment]
You can filter based on IP using the `--netrestrict` command line flag. It accepts a list of IP masks. Example: `geth --netrestrict 192.168.0.1/24` will ensure geth only accepts LAN connections.

**Comment by marcosmartinez7** [comment]
The netrestrict is an option for sealers or standard nodes, not for bootnodes rigth? The problem i am facing is people connecting to my bootnode

**Comment by fjl** [comment]
`--netrestrict` is supported by cmd/geth and cmd/bootnode. Please try the option and see whether it fixes your issues.

**Comment by marcosmartinez7** [comment]
hmm, if i understand the docs right, that works for a network and a mask, but if you have a distributed environment, where each node is on different networks, that wouldnt work.

Maybe creating a VPC would be an option for using --netrestrict
