### ISSUE TITLE
"missing block number for head header hash" after nil pointer panic

### ISSUE THREAD

**Issue by TheJeon** [ethereum/go-ethereum#17922]
Hello,

after experiencing a crash after a panic, geth won't startup correctly anymore, exiting with the message "Fatal: Error starting protocol stack: missing block number for head header hash". That all happened during fast sync, so it wasn't fully synced yet.

#### System information

Geth version: v1.8.17-stable-8bbe7207/windows-amd64/go1.11.1
OS & Version: Windows 10
Command line arguments: --cache 4096 --datadir "E:\tmp\CC\Ethereum" --nousb --identity Jeon --syncmode fast

#### Expected behaviour
Not corrupting the database and therefor ability to startup correctly or recover from a crash.

#### Actual behaviour
Not being able to read some data, causing the whole database to be useless apparently and forcing me to do a new fast sync I guess.

#### Log
Here is a screenshot from what happened, hoping that it helps someone to implement a fix.
![grafik](https://user-images.githubusercontent.com/7153691/47010364-10cfd180-d13f-11e8-9008-905b9cdc741a.png)

**Comment by NEJAMUL37** [comment]
My name :- nejamul Hoque 
C/o:- kisholoy community center 
Chewk bazar, Chittagong, Bangladesh
Postel code :- 4203
Connected number within Telegram apps id:-  +8801706848037
Whatapps id :-+8801825044068
https://www.facebook.com/nejamul.hoque.3950

https://www.linkedin.com/in/nejamul-hoque-45404a12a

www.Twitter.com/@nejamulHoque4
