### ISSUE TITLE
Crosscompiling Go-Ethereum from AMD64 to ARM7 fails

### ISSUE THREAD

**Issue by TwinbrotherPro** [ethereum/go-ethereum#17929]
Hi there,

#### System information

Geth version: `1.8.17`
OS & Version: Cross-compiling on Linux Amd64 for Linux ARM-7
Commit hash : (if `develop`)

#### Expected behaviour

I am currently trying to cross-compile some go-ethereum packages for a Linux ARM-7 device. I am using xgo and die instructions supplied at  https://github.com/ethereum/go-ethereum/wiki/Cross-compiling-Ethereum . 

#### Actual behaviour

My Source code compiles for every distribution except die ARM-7 architecture. When cross-compiling for ARM-7 I get the following error:

```
/tmp/cccYZQi3.s: Assembler messages:
/tmp/cccYZQi3.s:427: Error: thumb conditional instruction should be in IT block -- `movcc r1,#0'
 /tmp/cccYZQi3.s:428: Error: thumb conditional instruction should be in IT block -- `movcs r1,#-1'
/tmp/cccYZQi3.s:755: Error: thumb conditional instruction should be in IT block -- `movcc r1,#0'
/tmp/cccYZQi3.s:756: Error: thumb conditional instruction should be in IT block -- `movcs r1,#-1'
```

I attached the whole log file of the xgo docker container [geth-arm7.log](https://github.com/ethereum/go-ethereum/files/2486311/geth-arm7.log). Sadly the error occurs in a subprocess so I could not scrap it.

#### Steps to reproduce the behaviour

I am cross-compiling with the following statement:

`$ xgo --deps=https://gmplib.org/download/gmp/gmp-6.0.0a.tar.bz2 --targets=linux/arm-7 ./src/github.com/ethereum/go-ethereum/cmd/geth/`

May someone wants to reproduce this error and check whether it is working on his system? 

What am I doing differently then the command in the Makefile?

`geth-linux-arm-7:
	build/env.sh go run build/ci.go xgo -- --go=$(GO) --targets=linux/arm-7 -v ./cmd/geth`

I would be glad if someone could help me out here :)

@karalabe I can open this issue at https://github.com/karalabe/xgo/issues if you prefer.

**Comment by gballet** [comment]
What kind of arch are you compiling for? I'm surprised that ti's trying to compile for thumb when arm-v7 are usually more powerful machines.

For starters, I would look at the cross-compilation toolchain that you use. `arm-linux-gnueabihf-` vs. `arm-linux-gnueabi-` ?

**Comment by TwinbrotherPro** [comment]
> What kind of arch are you compiling for? I'm surprised that ti's trying to compile for thumb when arm-v7 are usually more powerful machines.
> 
> For starters, I would look at the cross-compilation toolchain that you use. `arm-linux-gnueabihf-` vs. `arm-linux-gnueabi-` ?

Regarding my logs it is arm-linux-gnueabihf. I do not exactly know what is happening there because I am just using the xgo docker container, which is also used by the Makescript in the repo.

So my question is whether someone may try to reproduce this or tell me that it is working on his machine ^^

**Comment by gballet** [comment]
My question is to find out what toolchain is installed on your system so that I can try to reproduce the issue

**Comment by TwinbrotherPro** [comment]
I fixed this by cross-compiling with xgo without the supplied binaries.

`geth-linux-arm-7: xgo --targets=linux/arm-7 ./src/github.com/ethereum/go-ethereum/cmd/geth/`

As noone else has this issue this thread can be closed. Thanks for your help @gballet
