### ISSUE TITLE
Can't start JSON RPC API webserver to handle client requests over http.

### ISSUE THREAD

**Issue by edmlbox** [ethereum/go-ethereum#17923]
#### System information

Geth version: `'Geth/v1.8.17-stable-8bbe7207/linux-amd64/go1.10.1
OS & Version: ubuntu

#### Expected behaviour
The startRPC administrative method starts an HTTP based JSON RPC API webserver to handle client requests. 
https://github.com/ethereum/go-ethereum/wiki/Management-APIs#admin_startrpc
#### Actual behaviour

How to start  JSON RPC on node over http request [as this docs say](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#admin_startrpc)?  When I send a  post request to the running server it returns:   **{message: 'HTTP RPC already running on 0.0.0.0:8545'}**, when I stop the server, than how can I send the HTTP request to start it, if it is not running?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
