### ISSUE TITLE
CONSENSUS ISSUE? mining blocks on the main chain and reward goes to another miner.

### ISSUE THREAD

**Issue by dante990** [ethereum/go-ethereum#1794]
Hello,
I noticed this issue where in my geth console i see that i mined a block but when i verify etherechain.org it seems another miner got it and it even has a different hash. 

 935 worker.go:322] 🔨  Mined block (#217129 / f6984bc9) in my console  and ether chain says the miner was nanopool  and displays wrong hash: 0xffd14cda96ce51d7cdd52e8bbcfe1a0a8818a7351703c52b784f2ccedbeda0f4

 935 worker.go:322] 🔨  Mined block (#217033 / 6ec36dd2). in my console and ether chain says the miner was coiontron and displays the wrong hash : 
Hash: 0x4f9d13f047737be00993a480261f59373d54713b94ddf553f473c1e390fc96f7

935 worker.go:322] 🔨  Mined block (#217024 / 2399c9b9). n my console and ether chain says the miner was coiontron and displays the wrong hash : 
Hash: 0xf39886d870e79072857b364221ec63e07ee1a922c734a4ab2c0237f7a1d2d644

... and so on, i can paste them all day. 

Why are the other miners stealing my blocks ? Is this a consensus  issue ?
Please fix this!! I'm wasting my time and energy and others get the blocks...

Blockchain DB Version: 3
Geth/v1.1.3/linux/go1.5

**Comment by fjl** [comment]
Mining a block unfortunately doesn't mean that the block ends up in the canonical chain. 
There is nothing we (or you) can do about that.
