### ISSUE TITLE
Import private key

### ISSUE THREAD

**Issue by gasparyanyur** [ethereum/go-ethereum#17958]
Hi there,

#### System information

Geth version: `1.8.17-stable`
OS & Version: Ubuntu 18

#### Expected behaviour
Need to make watch only wallet

#### Actual behaviour
I have a system where users can generate addresses and recieve ETH. So every user need to have separate address. So I need to integrate HD wallet (watch-only) where users can gerneate addresses, where I can check transactions and balances. 
So I have used `ethereumjs-wallet` to generate wallet and took from there `xpriv` key and I have tried to import into `geth`  which stored in my local machine (cold-storage)

#### Steps to reproduce the behaviour
```
const hdkey = require('ethereumjs-wallet/hdkey');
const bip39 = require('bip39');
var seed = bip39.mnemonicToSeed('my_mnemonic_phrase', 'my_password');
var chain = hdkey.fromMasterSeed(seed);
var xPrivate = chain.privateExtendedKey();
```
I have created file `file_to_path.txt` which contains my `xpriv` key.

Than I have tried to import into `geth` by the command

`geth account import file_to_path.txt`

#### Backtrace

````
WARN [10-22|14:53:16.486] Sanitizing cache to Go's GC limits       provided=1024 updated=664
Fatal: Failed to load the private key: encoding/hex: invalid byte: U+0078 'x'

````

**Comment by holiman** [comment]
The `account import` command calls [`LoadECDSA`](https://github.com/ethereum/go-ethereum/blob/master/crypto/crypto.go#L159) which calls `hex.DecodeString(string(buf))` on the buffer. That one does not like `0x` prefix, but wants unprefixed hexdata. 

Sounds very dangerous if you're building a centralilzed system where you can access other users wallets, I hope that's not what you're aiming to do.

**Comment by gasparyanyur** [comment]
@holiman thank you for reply. Actually I want to build decentralized system. So I have a system where users can generate address by one click than recieve coins (`ETH`,`BTC`,`LTC`) and get bonuses. So to have a security system I built a watch-only wallet for `BTC`,`LTC `-(in my local machine I installed `Electrum-BTC` and `Electrum-LTC` , than have took from there `xpub` key and in my online service I am genereting addresses for users). But on `ETH `there is no way to make concept look like this. Can you give me a good solution for the Ethereum? How can I make watch only wallet which will generate addreses for users, check transactions and balances but no one could send from there. 
Thanks!
