### ISSUE TITLE
SEGMENT VIOLATION - Crashing

### ISSUE THREAD

**Issue by GHF2014** [ethereum/go-ethereum#17967]
Mon Oct 22 12:57:11 :Listener created :0.0.0.0 port 35350
Mon Oct 22 12:57:11 :Can't create listening sock on host * port 35350 (bind)
Mon Oct 22 12:57:11 :psyBNC2.3.2-7-cBtITLdDMSNpE started (PID :22022)
Mon Oct 22 12:57:11 :SSL initialized
Mon Oct 22 12:57:11 :Loading all Users..
Mon Oct 22 12:57:11 :No Users found.
Tue Oct 23 23:58:18 :connect from xxx.xxx.xxxx (my host)
Tue Oct 23 23:58:28 :Program Context : src/p_blowfish.c/InitializeBlowfish Line 423
Tue Oct 23 23:58:28 :SEGMENT VIOLATION - Crashing

Debian 9 (Stretch)
Lastest psyBNC version

Each time I start my process, I try to connect and that crashes the process.

**Comment by karalabe** [comment]
Wrong project.
