### ISSUE TITLE
Watch-only wallet

### ISSUE THREAD

**Issue by gasparyanyur** [ethereum/go-ethereum#17964]
I want to build decentralized system. So I have a system where users can generate address by one click than recieve coins (ETH,BTC,LTC) and get bonuses. So to have a security system I built a watch-only wallet for BTC,LTC -(in my local machine I installed Electrum-BTC and Electrum-LTC , than have took from there xpub key and in my online service I am genereting addresses for users). But on ETH there is no way to make concept look like this. Can you give me a good solution for the Ethereum? How can I make watch only wallet which will generate addreses for users, check transactions and balances but no one could send from there.
Thanks!

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by ligi** [comment]
PS: if you have an android device - you can use [WallETH](https://walleth.org) in watch only mode.
