### ISSUE TITLE
Mobile sync mode should be configurable

### ISSUE THREAD

**Issue by ashishb** [ethereum/go-ethereum#17979]
#### System information

Geth version: `1.8.17`
OS & Version: Android
Commit hash 

#### Expected behaviour
Mobile sync mode is hardcoded to LightSync at https://github.com/ethereum/go-ethereum/blob/68109336405a36e3c3fdcab6a87e8bc024a44a49/mobile/geth.go#L160

#### Actual behaviour
It should default to LightSync but should be configurable via `NodeConfig`

#### Steps to reproduce the behaviour
`make android`. Run Geth on Android

#### Backtrace
Not applicable

**Comment by ashishb** [comment]
I can send a diff to fix this.

**Comment by ligi** [comment]
Why would you have another sync mode on mobile? Can you elaborate on your use-case?

**Comment by ashishb** [comment]
If an app developer really wants to run a `full` or a `fast` node, they should have the ability to configure that without recompiling Geth from scratch.

**Comment by holiman** [comment]
A modern high-end android device might be able to fast-sync, so I agree that it seems unnecessary to stop that

**Comment by fjl** [comment]
We do not want to support non-light sync modes on mobile because supporting full sync requires us to depend on all the full node code. While the mobile framework does include all that code right now, it will be removed in the future.
