### ISSUE TITLE
Provide security wallet

### ISSUE THREAD

**Issue by gasparyanyur** [ethereum/go-ethereum#17977]
Hi there,

I have a service where users can buy my product. Besides paying by card, I want to be able to allow users to pay in ETH. I think that it will correctly generate addresses for each user so that it is possible to follow the balance.On the sever I have run geth, and users get their addresses via the rpc request. But if someone is hacked server, he can withdraw all amounts. How can I can I provide secure wallet?

Any suggestions would be much appreciated.

**Comment by holiman** [comment]
>  But if someone is hacked server, he can withdraw all amounts. How can I can I provide secure wallet?

You shouldn't have the actual keys on the server, just a list of addresses. The actual adresses could be generated based off a seed, on an offline machine. On the offline machine, you just export a batch of addresses and feed into whatever system you have in place to assign addresses to users.
