### ISSUE TITLE
Mining false When node is mining.

### ISSUE THREAD

**Issue by edmlbox** [ethereum/go-ethereum#17985]
Geth version: Geth/v1.8.17-stable-8bbe7207/linux-amd64/go1.10.1

OS & Version: Ubuntu

#### Actual behaviour
eth_mining false
eth_hashrate 0x5a23

Why geth returns minig false when eth_hashrate 0x5a23???

**Comment by MartinDawson** [comment]
Works for me. Same Geth on Ubuntu 1.18.10
