### ISSUE TITLE
fetcher: TestOverlappingAnnouncements61 sometimes fails

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#1798]
I'm guessing it's some weird data race or timeout in the test code. Would be nice to sort it out when I have time. Opened this issue as a memo.

https://travis-ci.org/ethereum/go-ethereum/builds/79860756

**Comment by fjl** [comment]
Haven't seen it fail for a long time.

**Comment by karalabe** [comment]
I think I still see it occasionally, but if it's not too bothersome, we might as well leave this closed.
