### ISSUE TITLE
--accept Disclaimer of Liabilites and Warranties  || fails as docker container

### ISSUE THREAD

**Issue by altsheets** [ethereum/go-ethereum#1799]
--accept Disclaimer of Liabilites and Warranties  

or geth fails to run in docker container

**Comment by linagee** [comment]
If I understand you correctly (and you're making it hard to understand), make sure the datadir being passed here exists. (That is, if your docker container accepts the legalese.)
https://github.com/ethereum/go-ethereum/blob/v1.1.3/cmd/utils/cmd.go#L101

**Comment by altsheets** [comment]
Thx a lot, linagee.

> If I understand you correctly  
You probably have: I need to skip the human intervention.

> and you're making it hard to understand  
... but doesn't it feel great to have it figured out?  
:-)

Will study embark-framework . Probably there are more useful ideas there.

Thx a 10^6 !
