### ISSUE TITLE
Dependency no longer exists

### ISSUE THREAD

**Issue by roshanr95** [ethereum/go-ethereum#18009]
`node/node.go` contains a dependency `github.com/prometheus/prometheus/util/flock` which no longer exists upstream.

Should it be pulled into `go-ethereum` instead of existing only in `vendor`?

**Comment by Skyge** [comment]
I also find this question, so I get here for some idea.

**Comment by RaghavSood** [comment]
This is breaking some setups using `go mod`.

I'm happy to fork the original flock package or move it into go-ethereum and make a PR if needed.

@fjl Looks like you were the original author of #15000 which added this, let me know if you'd like me to make one replacing that dependency

**Comment by karalabe** [comment]
Fixed.
