### ISSUE TITLE
Whisper: Cannot send peer-to-peer message using targetPeer (peer ID)

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/go-ethereum#18003]
I have follow following [answer](https://github.com/ethereum/go-ethereum/issues/17545#issuecomment-430580437) and I can send 1-N whisper message. Now, I want to send peer-to-peer message using `shh.post()`.

On [shh.post][1] documentations, it is recommended to use `targetPeer` for peer-to-peer message. 

> `targetPeer` - String (optional): Optional peer ID (for peer-to-peer
> message only).

But using `targetPeer` assigned as `admin.nodeInfo.id` or `admin.nodeInfo.enode` of the receiver node; I was not able to send peer-to-peer message.

=> What is `targetPeer` (peer ID) stands for? Is `targetPeer` (peer ID) stands for `admin.nodeInfo.id` or `admin.nodeInfo.enode` or something else?

  [1]: https://web3py.readthedocs.io/en/stable/web3.shh.html#web3.shh.Shh.post

**Comment by gballet** [comment]
It is indeed be the `enode` of your target peer. See https://github.com/ethereum/go-ethereum/blob/master/whisper/whisperv6/api.go#L294. This being said, we don't recommend sending a message to only one peer as it makes the whole point of darkness moot.

**Comment by avatar-lavventura** [comment]
@gbalint: Sorry for a late comment. So `enode-id` would be use, which is obtained from `eth.admin` section. I have tried it but I wasn't able to send the message. 

Since this issue is open I was using public-key of the receiver. which works fine.

```
web3.geth.shh.post({"powTarget": 2.5, "powTime": 2, "ttl": 60, "payload":
                    payloads[0], "topic": topic, "pubKey": receiver_pub,})
```

But public key of the receiver is much longer than the `enode-id` and might be change over time if key pairs are updated.
