### ISSUE TITLE
Can't mine a single block in dev mode, block nonce is invalid

### ISSUE THREAD

**Issue by sammy007** [ethereum/go-ethereum#1800]
I'm using develop branch with <code>--dev</code> flag for testing some stuff. I tried to mine a block and got <code>Invalid header on mined block: Block's nonce is invalid (= 87c18193f4178a36)</code>. Any idea why? I stuck on 1st block. I have valid 0x000 DAG generated by ethminer.

Work submitted:

    ["0x38a3bd09e7a407f4","0xb3651603548fd4bd5df8941f070c242377b353681f15325a61dcfcdb5c86a9fb","0x2184c3a4d835a2578007edd2e0cf8c5ca07a4db759f5bb83bc4941e0023a74ef"]

**Comment by karalabe** [comment]
The DAGs are different from the main network. They use a reduced test DAG that requires much less memory and is generated instantaneously. I'm guessing ethminer expects the real DAG while `geth --dev` works with a false DAG.Could you try using the CPU miner in geth for dev mode?
