### ISSUE TITLE
LESv2 Documentation for RLP encoding of SendTx is Wrong

### ISSUE THREAD

**Issue by EBGToo** [ethereum/go-ethereum#18006]
The LESv2 documentation for the `SendTx` RLP encoding appears to be wrong.  The documentation (https://github.com/zsfelfoldi/go-ethereum/wiki/Light-Ethereum-Subprotocol-%28LES%29) says `SendTx [+0x0c, txdata_1, txdata_2, ...]` but if that is sent on the wire one is detached  as a 'useless peer'  (which is the typical response to an unexpected RLP encoding).  One must, in fact, send `SendTx [+0x0c, [txdata_1, txdata_2, ...]]` to not be disconnected.

Here one is disconnected:
```
ETH: LES: Send: [ LES,          SendTx ]
ETH: SEND: L  2: [
ETH: SEND:   I  1: 0x1c
ETH: SEND:   L  9: [
ETH: SEND:     I  1: 0x11
ETH: SEND:     I  5: 0x012a05f200
ETH: SEND:     I  2: 0x5208
ETH: SEND:     I 20: 0xb0f225defec7625c6b5e43126bdde398bd90ef62
ETH: SEND:     I  7: 0x2386f26fc10000
ETH: SEND:     I  0: 0x
ETH: SEND:     I  1: 0x26
ETH: SEND:     I 32: 0x72082d0e03e18c2c97721557d1fe482c959fb814a5066f66a98e5d324bbc6eca
ETH: SEND:     I 32: 0x2837c88bebbc484ca4377ef29ce3b58ac5f06c33e74857739ebef31d73f9eebd
ETH: SEND:   ]
ETH: SEND: ]
ETH: LES: Recv: [ P2P,      Disconnect ] (Useless Peer)
ETH: LES: Conn: [ TCP @   2,     <=|=> ] (Disconnect : Useless Peer) - SELECT
```
Here one is not disconnected:

```
ETH: LES: Send: [ LES,          SendTx ]
ETH: SEND: L  2: [
ETH: SEND:   I  1: 0x1c
ETH: SEND:   L  1: [
ETH: SEND:     L  9: [
ETH: SEND:       I  1: 0x11
ETH: SEND:       I  5: 0x012a05f200
ETH: SEND:       I  2: 0x5208
ETH: SEND:       I 20: 0xb0f225defec7625c6b5e43126bdde398bd90ef62
ETH: SEND:       I  7: 0x0cd6e786547800
ETH: SEND:       I  0: 0x
ETH: SEND:       I  1: 0x26
ETH: SEND:       I 32: 0x4ba3e7a62d96eaa96857b8da3bbb79e58dc5a163a65b69a558db8d945fd2cd72
ETH: SEND:       I 32: 0x56e552702d57131332878f7803d77008a553a9ca541cae8ac1cb31a1fb901b75
ETH: SEND:     ]
ETH: SEND:   ]
ETH: SEND: ]
```

#### System information

Geth version: release/1.8
OS & Version: OSX
Commit hash :

**Comment by fjl** [comment]
Support for SendTx was removed in https://github.com/ethereum/go-ethereum/commit/5515f364ae1673c1bf5569c089b5853c90ea1655. I'm unsure if this is a spec violation because the spec clearly states that all les/1 messages remain valid.

**Comment by fjl** [comment]
@zsfelfoldi is in favor of removing the messages from the spec. This makes the issue go away I guess.
