### ISSUE TITLE
Sealnode Bootstrap URL invalid  

### ISSUE THREAD

**Issue by maikolporras** [ethereum/go-ethereum#18001]
Hi,

I'm trying to setup a private network with puppeth. I'm able to deploy Ethstats and Bootnode, but at the end of the Sealer deploy it appears as offline.

Taking a look to the docker images, is showed as restarting and looking the logs I found this error:

Bootstrap URL invalid                    enode=enode://10879e4654276bdfbf6e8f07a2fff55e6315a95fedaedbeb2119b6a3c1fdcd75@192.168.10.10:30303 err="invalid node ID (wrong length, want 128 hex chars)"

#### System information

Geth version: 1.8.14-stable
OS & Version: OSX

#### Expected behaviour
Sealnode image should run.

#### Actual behaviour
Sealnode image stuck in restarting

#### Steps to reproduce the behaviour
Create a geth account
Run puppeth
Add a tracked machine
Deploy Ethstat on the machine created previously
Deploy Bootnode on the machine created previously
Deploy a Sealer node on the machine created previously using the created account

**Comment by mzzovko** [comment]
+1

**Comment by mzzovko** [comment]
Little bit more info, this only happens if I deploy sealnode from localhost, if I use puppeth from some other server, it works as expected.

**Comment by modolee** [comment]
I had the same problem when I used v1.8.16.
But, it was fixed in v1.8.17.
You can find what was the problem in below pull request.
https://github.com/ethereum/go-ethereum/pull/17802

**Comment by maikolporras** [comment]
@modolee you're right, is not happening in 1.8.17. Thanks.

**Comment by Bitmaudit** [comment]
I've this error:
 Fatal: Error starting protocol stack: bad bootstrap node "enode://c7c7c4905b29c81a36907937261c2b2523b48e60dbef489ac329aedbc5d19910921f84603d3255621b0928d8262327dff0855ce95f66bb88a2a401d0884d1c80@[::]:30301": invalid IP (multicast/unspecified)

the file Dockerfile was specific another (different enode, the right!):

enode://0df98758a40a58db0ec6c4db14f9241dcf3fec37b0bdb08720de369da0ea1631a3f55717135518a9dea25c8854554f4ccddb33c8d5402130fcbca76fe8d74249@5.189.165.78:30301

the error report an enode used in yhe past! how do fix?
