### ISSUE TITLE
Swarm: BootNodes entry in config file not working as documented

### ISSUE THREAD

**Issue by d10r** [ethereum/go-ethereum#18004]
https://swarm-guide.readthedocs.io/en/latest/configuration.html claims that parameter `BootNodes` is supported in config file.

If setting that, I get the following err message on starting swarm:
```
Fatal: unable to configure swarm: config.toml, line 21: field 'BootNodes' is not defined in api.Config, check github.com/ethereum/go-ethereum/swarm/api/config.go for available fields
```
The mentioned file (which unfortunately can't be copy'n pasted into a browser address bar) https://github.com/ethereum/go-ethereum/blob/master/swarm/api/config.go does indeed not mention a BootNode parameter.

Using swarm 0.3.6-unstable

**Comment by nonsense** [comment]
@d10r let's address this at https://github.com/ethersphere/swarm as the Swarm codebase lives there from now on. I can see that @homotopycolimit and @adamschmideg already triaged this issue.
