### ISSUE TITLE
transaction appears in txpool but not in eth_newPendingTransactionFilter

### ISSUE THREAD

**Issue by bl4ck5un** [ethereum/go-ethereum#18016]
#### System information

Geth version: `1.8.17-stable-8bbe7207`
OS & Version: Linux

#### Expected behaviour

I was under the impression that `eth_newPendingTransactionFilter` captures pending transactions as they go to the `txpool`.

#### Actual behaviour

Some pending transactions appear in `txpool` without registering at `eth_newPendingTransactionFilter`.

#### Steps to reproduce the behaviour

1. connect to a full node using `web3.js` (I also tried `web3py` and the Rust version) and start listening for a `eth_newPendingTransactionFilter`. 
2. Send test transactions to the full node.
3. check that those transactions appear in the `txpool` by calling `txpool.inspect`
4. wait for them to shown up in the filter, which would not happen

**Comment by jurijbajzelj** [comment]
I have the exact same problem with detection of pending events (`Transfer` events of ERC-20 token). Nothing gets returned, even though I see transaction in txpool.

```python
event_filter = self.__instance.events.Transfer.createFilter(
    fromBlock='pending',
    toBlock='pending'
)
events = event_filter.get_all_entries()
```

**Comment by fjl** [comment]
The original issue should be fixed in recent releases. We rewrote transaction pool event handling in June 2019. Should this still be an issue, please reopen.

**Comment by fjl** [comment]
@jurijbajzelj Your issue is unrelated to the transaction pool. Please note that pending log filtering does not check all pooled transactions and only filters logs in the pending state.
