### ISSUE TITLE
Puppeth fails to deploy ethstats

### ISSUE THREAD

**Issue by timp999** [ethereum/go-ethereum#18011]
Hi folks, any help appreciated with this one

#### System information

Geth version:
Geth
Version: 1.8.18-unstable
Git Commit: 3e1cfbae934f72c94c00e515ca872997530eede8
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10

OS & Version: Ubuntu 18.04
Commit hash :3e1cfbae934f72c94c00e515ca872997530eede8

#### Expected behaviour
Ethstats node deployed to server

#### Actual behaviour
Error

-d and --timeout cannot be combined.
ERROR[10-31|18:36:33.060] Failed to deploy ethstats container      err="Process exited with status 1"

#### Steps to reproduce the behaviour
What would you like to do? (default = stats)
 1. Show network stats
 2. Manage existing genesis
 3. Manage tracked machines
 4. Deploy network components
> 4

What would you like to deploy? (recommended order)
 1. Ethstats  - Network monitoring tool
 2. Bootnode  - Entry point of the network
 3. Sealer    - Full node minting new blocks
 4. Explorer  - Chain analysis webservice (ethash only)
 5. Wallet    - Browser wallet for quick sends
 6. Faucet    - Crypto faucet to give away funds
 7. Dashboard - Website listing above web-services
> 1

Which server do you want to interact with?
 1. xxxx.xxxx.xxxx.azure.com
 2. xxxx.xxxx.xxxx.azure.com:22
 3. xxxx.xxxx.xxxx.azure.com
 4. xxxx.xxxx.xxxx.azure.com
 5. xxxx.xxxx.xxxx.azure.com
 6. xxxx.xxxx.xxxx.azure.com
 7. Connect another server
> 1

Which port should ethstats listen on? (default = 80)
> 

Allow sharing the port with other services (y/n)? (default = yes)
> n

What should be the secret password for the API? (must not be empty)
> xx

#### Backtrace
-d and --timeout cannot be combined.
ERROR[10-31|18:36:33.060] Failed to deploy ethstats container      err="Process exited with status 1"
[backtrace]
````

**Comment by karalabe** [comment]
You have a faulty version of docker compose. They released some weird limitation that they backtracked a couple months later. https://github.com/docker/compose/pull/5565
