### ISSUE TITLE
Spoofing of totalDifficulty variable

### ISSUE THREAD

**Issue by boorac** [ethereum/go-ethereum#18010]
Apologies in advance as this is not a bug report but rather a protocol question - I have been unable to get an answer for this using other usual channels so I'm out of ideas.

Péter Szilágyi, in his talk in Taipei, claims that totalDifficulty can be spoofed:

https://www.youtube.com/watch?time_continue=575&v=qJA6J0mP73w

How is that possible? Can the variable only be verified if all block headers are downloaded from the spoofed chain and would that produce a fraud proof?

For completion, the same question on Stack Exchange:
https://ethereum.stackexchange.com/questions/60860/spoofing-of-totaldifficulty-variable

@karalabe - maybe jump straight to the source :)

**Comment by holiman** [comment]
The issue is explained on that stack exchange post. TLDR; yes, you can spoof TD. But it will be detected during the import phase.
