### ISSUE TITLE
geth +Mist+web3j get erc20 token faile

### ISSUE THREAD

**Issue by fishmc** [ethereum/go-ethereum#18023]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/
Commit hash : (if `develop`)

#### Expected behaviour

Added custom tokens that show up with correct but not their name, amount in the wallet.I can get the accounts list.(on ethereum)success show up on infura,but in geth (on main ethereum )

#### Actual behaviour
I can run on my geth get accounts list,but i can't get the token message. 

geth version:clientVersion Geth/LeoNode1/v1.8.17-omnibus-unstable-05a648e2/linux-amd64/go1.10.1
token address:0xaa89fe0278c5d7778a89d0aa9d77e46f758c580b

RUN MY GETH
GethLocation: "http://192.168.52.130:8486",
root@leo-virtual-machine:~/go/src/token# go run main1.go
2018/11/02 17:42:11 Connected to Geth at: http://192.168.52.130:8486
2018/11/02 17:42:11 Failed to get decimals from contract: 0xaA89fE0278C5d7778a89d0aa9D77e46F758c580b 
RUN INFURA
root@leo-virtual-machine:~/go/src/token# go run main1.go
2018/11/02 17:43:17 Connected to Geth at: https://mainnet.infura.io/v3/411f02cdf63346b5bd24f29d4661c339
LMC

#### Backtrace

````
[backtrace]
````

**Comment by gballet** [comment]
@fishmc could you tell us if geth has synced, how you run `geth` and what is the content of `main1.go` ?
