### ISSUE TITLE
Websocket Event Watching: missing re-play of re-included blocks

### ISSUE THREAD

**Issue by calebrate** [ethereum/go-ethereum#18029]
#### System information
Geth version: `v1.8.17`
OS & Versions: Windows, Linux

#### Actual behaviour
Assume blocks coming in in the following order:

```
1.   NR 1
2.   NR 2A PARENT 1
3.   NR 2B PARENT 1
4.   NR 3  PARENT 2A
```

We are subscribed to an event. There is an event log is in Block 2A, our subscription fires in step 2.
In step 3, our event gets marked as removed, which is the last state we get for that event even tough block 2A is re-included in the chain in step 4.

#### Expected behaviour
Events from Blocks which are rolled back should be marked as removed. However when that block is re-included into the longest chain, it should be re-fired again (maybe with a removed:false property).

**Comment by calebrate** [comment]
This is linked to https://github.com/ethereum/go-ethereum/issues/18026

**Comment by karalabe** [comment]
This should already been fixed in https://github.com/ethereum/go-ethereum/pull/18322. Please open a new issue if it's not.
