### ISSUE TITLE
request for documetation to execute clique api calls from javascript/python/go languages outside geth console

### ISSUE THREAD

**Issue by bsrv** [ethereum/go-ethereum#18025]
I am a newbie to ethereum working on the ethereum platform.
In my work, it is required to execute clique.proposal,clique.getsigners from outside geth console, i searched for examples but did not find any, to execute it from outside geth console, the web3 api is not having api calls to clique functions
so i need some help and documentation for executing  clique API  calls in go/python/javascript

**Comment by karalabe** [comment]
The console is just a fancy wrapper around the JSON RPC calls. If you need to do `clique.getSigners`, you can send a low level request directly from the outside via HTTP, IPC or WebSockets containing something like  `{"jsonrpc":"2.0","method":"clique_getSigners","params":[],"id":1}`

**Comment by bsrv** [comment]
thank you  Karalabe
