### ISSUE TITLE
 CallOpts missing setter "From" in Android

### ISSUE THREAD

**Issue by sempiecampos** [ethereum/go-ethereum#18034]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.8.17`
OS & Version: Android 8.0
Commit hash : (if `develop`)

#### Expected behaviour
As per CallOpts this object should have the ability to set the following values, Context,Pending and From. Base.go has CallOpts defined as
```
 // CallOpts is the collection of options to fine tune a contract call request.
type CallOpts struct {
	Pending bool           // Whether to operate on the pending state or the last known one
	From    common.Address // Optional the sender address, otherwise the first account is used

	Context context.Context // Network context to support cancellation and timeouts (nil = no timeout)
}
```

#### Actual behaviour

missing setter for FROM and this is causing  issues  on android, as certain calls require "FROM" to be set inside the CallOpts in order to get a proper response from eVM. 

as a sidenote the .toString also does no print the populated data inside CallOpts

**Comment by fjl** [comment]
Whoa, we totally forgot about this one. Fixed in #20721!
