### ISSUE TITLE
Unable to attach Geth to local node

### ISSUE THREAD

**Issue by Aristophanes888** [ethereum/go-ethereum#18030]
I'm on Windows 10 running Geth version 1.8.17. I get the following error when I use the "geth attach" command in the console:

>Fatal: Unable to attach to remote geth: no known transport for URL scheme "c"

I've searched for other users coming across this problem, and one fix that worked for some was manually specifying the IPC path with this command:

>geth attach ipc:\.\pipe\geth.ipc

However when I try this the console throws up this error:

>Fatal: Unable to attach to remote geth: Timed out waiting for pipe '\.\pipe\geth.ipc' to come available

Any ideas?

**Comment by fishmc** [comment]
--rpc "'.\pipe\geth.ipc"?

**Comment by Yanzal** [comment]
try 'geth attach ipc:\\.\pipe\geth.ipc'

**Comment by adamschmideg** [comment]
See #20722
