### ISSUE TITLE
abi.ABI issues with function overloading

### ISSUE THREAD

**Issue by mewwts** [ethereum/go-ethereum#18045]
#### System information

Geth version: `1.8.17`
OS & Version: Linux

#### Expected behaviour
All methods defined in ABI-json should be in abi.ABI.Methods

#### Actual behaviour
If function overloading is used in the contract, the abi will only hold one of the methods that are overloaded. This is because abi.ABI.Methods is a map from name to Method object. When functions are overloaded the name is the same for multiple methods and hence there can only be one Method with the same name.

#### Steps to reproduce the behaviour
Parse for instance the DAI contract which has two `approve` functions https://etherscan.io/address/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359#code

I'd be happy to take a stab at a fix, but if people rely on the key of the map for method-name then fixing it in a backwards-compatible way will be awkward.

**Comment by MartinDawson** [comment]
I could also have a go at fixing it if you want.

Relevant files seem to be abi.go, abi_test.go.

**Comment by mewwts** [comment]
Hey @MartinDawson,

Currently methods and events are stored in maps:
https://github.com/ethereum/go-ethereum/blob/1212c7b844e3ef13cbb5476b088eae27782535b4/accounts/abi/abi.go#L29-L33

This means that the lines in UnmarshalJSON below will overwrite any record of a previous method or event in the map. 

https://github.com/ethereum/go-ethereum/blob/1212c7b844e3ef13cbb5476b088eae27782535b4/accounts/abi/abi.go#L118-L130

If not too much code relies on using the key of the maps as the name of the method/event, one could modify it by adding a postfix. Another solution would be to replace the maps with slices, which could contain methods with duplicate names.

However, as golang itself does not support function overloading, how to generate the bounded golang struct of the contract is unclear as well. You could postfix the name by number of input parameters, but that also seems a bit weird

Think it's wise to have a bit of a discussion here before we jump to implementation.

**Comment by mewwts** [comment]
Related: https://github.com/ethereum/go-ethereum/pull/17099

**Comment by gballet** [comment]
Fixed with https://github.com/ethereum/go-ethereum/pull/17099
