### ISSUE TITLE
I have some question about worker？

### ISSUE THREAD

**Issue by liuhonghui** [ethereum/go-ethereum#18043]
I can't understand the code in miner/worker.go.

```
func (w *worker) commit(uncles []*types.Header, interval func(), update bool, start time.Time) error {
	// Deep copy receipts here to avoid interaction between different tasks.
	receipts := make([]*types.Receipt, len(w.current.receipts))
	for i, l := range w.current.receipts {
		receipts[i] = new(types.Receipt)
		*receipts[i] = *l
	} 
     // *** why use state.copy? ***
 	s := w.current.state.Copy()
	block, err := w.engine.Finalize(w.chain, w.current.header, s, w.current.txs, uncles, w.current.receipts)
	if err != nil {
		return err
	}
...
```

In this function, state has a operation copy.And it will execute Engine.Finalize with state.copy().I think this copy is useless.Who can talk me the effect about this code？Thanks very much.

**Comment by rjl493456442** [comment]
Currently, the miner will generate a new mining work in the same round when some events trigger. for example, we will generate an empty work first and then generate a full work with all transactions included based on the empty state, but in the `engine.Finalize` function, consensus engine will do some finalization(miner reward, uncle reward, etc). In order to keep the state clean we create a copy here. 
So that when we receive a new uncle, we can apply it to current state with lowest recreation cost.

**Comment by liuhonghui** [comment]
> Currently, the miner will generate a new mining work in the same round when some events trigger. for example, we will generate an empty work first and then generate a full work with all transactions included based on the empty state, but in the `engine.Finalize` function, consensus engine will do some finalization(miner reward, uncle reward, etc). In order to keep the state clean we create a copy here.
> So that when we receive a new uncle, we can apply it to the current state(and recreate a new work) with lowest recreation cost.
But I am still a bit confused. In the `commitNewWork` function, there is a line of code that 'err := w.makeCurrent(parent, header)'. In the `makeCurrent` function, state is `w.chain.StateAt(parent.Root())`, and `w.current.state` will be change.So that every time a new work comes, it will create a state. I can not understand the effect of copy.
And what is the meaning about the last sentence? Is it meaning that `state.copy()` only takes effect in the uncle block? Thanks a lot.

**Comment by rjl493456442** [comment]
First, there are two ways in which miner can generate work: a) apply new change(new uncle) to current state and b) re-create a state every once in a while.
For the former, the new change is directly applied to the current state, which is the meaning of the state.copy, for the latter is to recreate the state.
