### ISSUE TITLE
Potential inconsistency of "go-evm" and other implementations

### ISSUE THREAD

**Issue by ireneGP** [ethereum/go-ethereum#18040]
Hello,

- Go EVM version: evm version 1.8.18-unstable-68109336
- Aleth EVM version: aleth-vm 1.5.0-alpha.5-2+commit.ec558b26.dirty 
- Operating system: Ubuntu 18.04
- Fully synchronized: NA
- Network: NA
- Restarted: NA

Please see the stack trace of `evm` and `aleth-vm`:

````
➜  bin git:(master) ✗ ./evm --debug --code 3330 --json run
{"pc":0,"op":51,"gas":"0x2540be400","gasCost":"0x2","memory":"0x","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"CALLER","error":""}

{"pc":1,"op":48,"gas":"0x2540be3fe","gasCost":"0x2","memory":"0x","memSize":0,"stack":["0x73656e646572"],"depth":1,"refund":0,"opName":"ADDRESS","error":""}

{"pc":2,"op":0,"gas":"0x2540be3fc","gasCost":"0x0","memory":"0x","memSize":0,"stack":["0x73656e646572","0x7265636569766572"],"depth":1,"refund":0,"opName":"STOP","error":""}

{"output":"","gasUsed":"0x4","time":117840}
#### LOGS ####
````

````
➜  aleth-vm git:(master) ✗ ./aleth-vm trace --code 3330 --log-verbosity 20
[
   {
      "depth" : "0",
      "gas" : "9223372036854775807",
      "gasCost" : "2",
      "memory" : [],
      "pc" : "0",
      "stack" : [],
      "storage" : {}
   },
   {
      "depth" : "0",
      "gas" : "9223372036854775805",
      "gasCost" : "2",
      "pc" : "1",
      "stack" : [ "0x45" ]
   },
   {
      "depth" : "0",
      "gas" : "9223372036854775803",
      "gasCost" : "0",
      "pc" : "2",
      "stack" : [ "0x45", "0x1122334455667788991011121314151617181920" ]
   }
]
````

The stack behavior seems inconsistent. Does this make any sense? Thanks.

**Comment by ireneGP** [comment]
Ah, I see. 😅 You are right, have a good weekend! @joshua-mir

**Comment by holiman** [comment]
I think the item being dupped is ascii String 'sender' which go evm uses for sender if not otherwise specified. It needs to default to something... And that's what origin places onto the stack

**Comment by holiman** [comment]
( @ireneGP I don't think the stack step before the last is what you posted)

**Comment by ireneGP** [comment]
Hi @holiman  . It is, I execute both VM with this bytecode samples:

https://etherscan.io/address/0x2a0c0DBEcC7E4D658f48E01e3fA353F44050c208#code

**Comment by ireneGP** [comment]
@holiman  I am still confused with this. Since both VM executes the same opcode `DUP2`, why `go-evm` needs to push a `sender` onto the stack?

**Comment by holiman** [comment]
On mobile here, but I wonder if pc=52 really is dup2. Check ascii version of 73656e646572.

**Comment by ireneGP** [comment]
@holiman  You are right, I know the issue here. So the stack at the current `pc` represents stack status before executing the current opcode. When `pc==51` the opcode is `CALLER`. No wonder why `sender` is pushed on to the stack. Sorry for the trouble this may cause.
