### ISSUE TITLE
Is go-ole/go-ole being used for anything?

### ISSUE THREAD

**Issue by reijin90** [ethereum/go-ethereum#18055]
Hi!

I went through the vendors list in this repo and noticed that `go-ole/go-ole` doesn't seem to have any references in the actual code. I'm probably missing something, but if not: Why is it still part of this repo? Legacy reasons?

**Comment by fjl** [comment]
It looks like this is a transitive dependency of the dashboard code. The dependency chain is 

- `github.com/ethereum/go-ethereum/dashboard`
- `github.com/elastic/gosigar`
- `github.com/StackExchange/wmi`
- `github.com/go-ole/go-ole`
