### ISSUE TITLE
PPA upgrades dev to master: dev version number < master version number

### ISSUE THREAD

**Issue by Phistr90** [ethereum/go-ethereum#1805]
Hi,

although I have added the dev repo, it upgrades to the newest master release instead of using the dev package.
Most likely this is because the verion number of the master release > dev release.

Would be nice if you could fix this, since a lot useful commits are not included in the master release yet.

**Comment by obscuren** [comment]
With the coming of the next release this won't be a problem any longer. I'll keep this open until it has been released
