### ISSUE TITLE
bootnode -writeaddress returns wrong length result

### ISSUE THREAD

**Issue by DrSuiunbek** [ethereum/go-ethereum#18053]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.8.17-stable`
OS & Version: Ubuntu 18.04.1 LTS
Commit hash : (if `develop`)

#### Expected behaviour
128 character long hex string, e.g. 30768fef0421bde58197e827057b52d60f9f511dce9330b22f625188b0668c4b75e239b32dfec9e368b6fbf7a9bf9bef48baac904644032b67f95a3097ba09e5

#### Actual behaviour
64 character long hex string, e.g.
c253ff272f89524b28fa24d89d89bafd6dd3654f2515a5ceb099fa103aedd6b3

#### Steps to reproduce the behaviour
bootnode -genkey node.key
bootnode -nodekey node.key -writeaddress

#### Backtrace

````
[backtrace]
````

**Comment by DrSuiunbek** [comment]
System information
Geth version: 1.8.17-stable
OS & Version: Ubuntu 18.04.1 LTS

Expected behaviour
128 character long hex string, e.g. 30768fef0421bde58197e827057b52d60f9f511dce9330b22f625188b0668c4b75e239b32dfec9e368b6fbf7a9bf9bef48baac904644032b67f95a3097ba09e5

Actual behaviour
64 character long hex string, e.g.
c253ff272f89524b28fa24d89d89bafd6dd3654f2515a5ceb099fa103aedd6b3

Steps to reproduce the behaviour
bootnode -genkey node.key
bootnode -nodekey node.key -writeaddress

**Comment by dsarosi** [comment]
I observe the same bug when using version `1.8.17-stable-8bbe7207`.

**Comment by hadv** [comment]
fix by https://github.com/ethereum/go-ethereum/commit/75060ef96ec38b0c6ca4dba4f4543e594025507f on master already

**Comment by karalabe** [comment]
Closing as fixed on master. Will ship in at the beginning of next week.
