### ISSUE TITLE
Transactions not being mined on private net

### ISSUE THREAD

**Issue by MANOJKUMARCH** [ethereum/go-ethereum#18062]
Hi There,

I am running a geth node and tried to perform a load testing by giving multiple transactions (1000 tx) from front end.

As the application is not crypto related and need the blocks to be mined faster, the console.go file is tweaked so that the block difficulty is always set to 1. Our case is not a crypto oriented and hence we have made the minimum gas price as 1. 

Please check and help me on it.

More details as below

#### System information

Geth
Version: 1.8.18-unstable
Git Commit: 3e1cfbae934f72c94c00e515ca872997530eede8
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.1
Operating System: linux

#### Expected behaviour

Expected behavior is  for the tx to get mined.

#### Actual behaviour

I am able to push in 1000 Tx, from front end, all the transactions are only sending 1 wei from account1 to account2. I increased nonce for the tx correctly and so there is no issue and all 1000 tx are created successfully. 

**I see the tx are struck in pending when viewed with web3.txpool**

#### Steps to reproduce the behaviour

Below is the Nethereum code used to create the 1000 tx. All the tx are created but waiting in pending queue.

				for (int i = 0; i < 1000; i++)
				{
                    string data = "Test string";	
					var gasPrice = 10+i;
					var privateKey = "XXXXXXXXXXXXXXX";
					var senderAddress = "0xa5a85c234bca3D4BF29f7Bd7AD7D458dea8Ea8E9";
					var receiveAddress = "0x1b55195c2610f7c0069cb89db1b3e973ff447a49";
					
					var txCount = await web3.Eth.Transactions.GetTransactionCount.SendRequestAsync(senderAddress);
                    var nonce = txCount.Value+i;
					var value = 1;
					var encoded = Web3.OfflineTransactionSigner.SignTransaction(privateKey, receiveAddress, value, nonce, gasPrice, 100000, data.ToHexUTF8());

					Debug.WriteLine(Web3.OfflineTransactionSigner.GetSenderAddress(encoded));
					Debug.WriteLine(encoded);
					
					var txId = await web3.Eth.Transactions.SendRawTransaction.SendRequestAsync("0x" + encoded);
					var receipt = await web3.Eth.Transactions.GetTransactionByHash.SendRequestAsync(txId);
}

PS: When I worked with 10 tx for the same above code, it worked fine and the tx are mined immediately.

**Comment by MANOJKUMARCH** [comment]
Further to my finding above, I see that the first few transactions are put in a block and the block is in pending status.

 eth.getBlock("pending")
{
  difficulty: 1,
  extraData: "0xd883010811846765746888676f312e31312e31856c696e7578",
  gasLimit: 800000000000000000,
  gasUsed: 128040,
  hash: null,
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: null,
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: null,
  number: 1541,
  parentHash: "0xb602d6fe55a55a9388c32e6fdcd4c079468a3667e32555fc4cc910e3ae766854",
  receiptsRoot: "0xac2027bd72f8f4004c0aa514086a2cbd5044fc7f14c2f1d6934737f5a2273bf3",
  sha3Uncles: "0x67203d2f0d4d83868e8475ccf5ded2e6247810d350f9ef87b41b0491bbdda302",
  size: 1697,
  stateRoot: "0x1565d885413b3cd7fb6f9602c57fe670f24ed235b61881cfa5bab4b3dbf87db4",
  timestamp: 1542115038,
  totalDifficulty: 0,
  transactions: ["0x59e38e01b92e26b8d516d9d1c6bf458602e0d36d7ca5c599378824125da0c84c", "0x84af10458416825e253bee2c873f4c88da35c1bb2439844cd9979212fe096317", "0x9af86a0fff0a34ec7e245313d6ae166cac3ae9553cc06649bae4b5b1228a4065", "0xaf2d0084aa4af18b6ea45521ede897fed598c5d7d0ccfd31c840788ec3cb9ff0", "0xa05358e63721e9f2bc888a842be1f3df3923e163152f6efe4f029c6914c5d47f", "0xfab31956fbdefd6154462712cef852d3e820f1dedd876528c9326438bb1249cd"],
  transactionsRoot: "0x19c43d0ede30bba91611ee2373c4dc257cd7bee06767c0ec8be5b504c64194ff",
  uncles: ["0xc98327b0f1835f371943ffbbbcddeefefcc75cb71d0e89ef63eef8ad9fe638e7"]
}
>

This block is not being mined as another block with same block number is mined with 0 transactions. 

I think, as the starting transactions are not mined, all the remaining tx are in pending in web3.txpool. 
Can someone help on why this is happening and why is the block going to pending status.

**Comment by hello2mao** [comment]
I have the same problem, see #18082.  -_-

**Comment by karalabe** [comment]
So, the `ethash` miner in Geth works by creating an empty block, starting mining and then in the background creating a replacement block with transactions too. This is to reduce the opportunity cost for miner of including transactions. However in your case, if you hard coded a difficulty of 1, the initial empty block is mined so fast, that you will never make the non-empty block.

Your options are either to modify the miner too to disable the path that does the empty block assembly, or alternatively to use `clique` instead of `ethash` where you can set a block time of 1 second. You probably don't want to go lower than that because if propagation + processing takes more than the block time, your network might fall apart.
