### ISSUE TITLE
Unable to Sync a Geth Full / Archive Node on Windows 10 64-Bit: Crashes With Exception 0xc0000005

### ISSUE THREAD

**Issue by ymonye** [ethereum/go-ethereum#18068]
#### System information

Geth version: 1.8.17-stable-8bbe7207
OS & Version: Windows 10 64-Bit
CPU: i9-7980XE
Memory: 128GB DDR4 SDRAM
Storage: Intel DC P4600 4TB PCIe NVMe SSD

#### Expected behaviour

Geth is able to sync a full / archive node on a Windows 10 64-Bit machine under a Standard User account (non-admin), with a 4TB NVMe SSD & Gigabit internet connection. Admin privileges were enabled for geth.exe.

#### Actual behaviour

Geth crashes multiple times after several days of syncing. Attempt 1 crashed around ETH mainnet block 5118645. Attempt 2 crashed atround ETH mainnet block 3996915.

Enabling --verbosity 5 reveals the following exception:

Exception 0xc0000005 0x8 0xc0000a17c8 0xc0000a17c8
PC=0xc0000a17c8

![image](https://user-images.githubusercontent.com/13838584/48245562-6eabae00-e3b9-11e8-9b7c-d49cce7c3014.png)

#### Steps to reproduce the behaviour

geth --syncmode=full --gcmode=archive --cache=43581 --maxpeers=25000 --datadir="B:\Chains\Ethereum\Geth\Mainnet"

**Comment by gballet** [comment]
@ymonye could we please get the full stack trace?

**Comment by ymonye** [comment]
@gballet, it was pointed out to me by a handful of folks in Discord, including @karalabe, that there's a good chance my problems were due to a corrupt SSD. I've just received my replacement SSD today and will update this thread once I'm able to get Geth updated & setup again.

**Comment by adamschmideg** [comment]
Since we haven't heard back from you, I assume the new SSD fixed your problem, so I'm closing this ticket.

**Comment by ymonye** [comment]
> Since we haven't heard back from you, I assume the new SSD fixed your problem, so I'm closing this ticket.

All good. Sync confirmed working properly on Geth v1.9.0. Full archive node synced in 7days & 19hrs.
