### ISSUE TITLE
can not restart geth after first close when the first has err

### ISSUE THREAD

**Issue by MccoolFrank** [ethereum/go-ethereum#18074]
a@aa:~/suyuan$ geth  --rpc  --rpccorsdomain "*" --datadir mydata --port 3                                                                                        0303 --rpcapi "db,eth,net,web3,personal,web3" --gasprice 22000000000 --networkid                                                                                         1234  --rpcaddr a.b.c.d --rpcport 8545  console
INFO [11-11|00:27:46.402] Maximum peer count                       ETH=25 LES=0                                                                                         total=25
INFO [11-11|00:27:46.403] Starting peer-to-peer node               instance=Geth                                                                                        /v1.8.17-stable-8bbe7207/linux-amd64/go1.10
INFO [11-11|00:27:46.403] Allocated cache and file handles         database=/hom                                                                                        e/a/suyuan/mydata/geth/chaindata cache=768 handles=512
INFO [11-11|00:27:46.429] Initialised chain configuration          config="{Chai                                                                                        nID: 10 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158                                                                                        : 0 Byzantium: <nil> Constantinople: <nil> Engine: unknown}"
INFO [11-11|00:27:46.430] Disk storage enabled for ethash caches   dir=/home/a/s                                                                                        uyuan/mydata/geth/ethash count=3
INFO [11-11|00:27:46.430] Disk storage enabled for ethash DAGs     dir=/home/a/.                                                                                        ethash                   count=2
INFO [11-11|00:27:46.430] Initialising Ethereum protocol           versions="[63                                                                                         62]" network=1234
INFO [11-11|00:27:46.431] Loaded most recent local header          number=75287                                                                                         hash=a65e16…ff7f35 td=315426406005 age=54m11s
INFO [11-11|00:27:46.431] Loaded most recent local full block      number=75287                                                                                         hash=a65e16…ff7f35 td=315426406005 age=54m11s
INFO [11-11|00:27:46.431] Loaded most recent local fast block      number=75287                                                                                         hash=a65e16…ff7f35 td=315426406005 age=54m11s
INFO [11-11|00:27:46.470] Setting new local account                address=0xf98                                                                                        E8f5fD4497E82986E80ebbA7E5043AEDFEb16

my geth stop here ,I have tried many times

**Comment by holiman** [comment]
This is obviously some private network, chainid `10` and networkid `1234`. You say `geth stop`, but I assume you mean it simply didn't progress? I assume that's because it doesn't find any peers on that private network. Too few details to say much more.
