### ISSUE TITLE
What is the ip 213.202.242.16 for?

### ISSUE THREAD

**Issue by fangvv** [ethereum/go-ethereum#18077]
We have a private ethereum of version v1.8.17-stable-8bbe7207.

After my geth connects to this ip and has a timeout, the geth breaks down, and I can't transfer ethers in this system.

The geth always has the following output:

ERROR[09-05|01:40:43.976] write tcp XXXX:YY->213.202.242.16:ZZZ: i/o timeout

I found there is already some issues about this ip, #17584 

Can anyone tell me if this is a hacker?

**Comment by fangvv** [comment]
![_20181111103559](https://user-images.githubusercontent.com/1792468/48308352-9a878900-e59d-11e8-8e84-d9b8dc18ed24.jpg)

**Comment by fangvv** [comment]
This problem was solved by drop all packets of 213.202.242.16 by using iptables. I still want to know what happens to this ip and our private chain.

**Comment by fishmc** [comment]
i have same question...

**Comment by fangvv** [comment]
@fishmc How did you solve this problem?

**Comment by fishmc** [comment]
i chage port number,but next time same question will be happend again

**Comment by holiman** [comment]
> Can anyone tell me if this is a hacker? 

Yes, most likely. It was someone from the internet who attached to your RPC service. Don't expose that publically.
