### ISSUE TITLE
Whisper: PoW calculation different from EIP-627

### ISSUE THREAD

**Issue by kdeme** [ethereum/go-ethereum#18070]
I believe there are some differences in the Whisper PoW calculation in go-ethereum compared to what is written in [EIP-627](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-627.md). I'm not sure if this is intended or not but I couldn't find any more information on why these differences are there, hence the creation of this issue.

1. RLP-encoded envelope size versus sum of sizes of the individual envelope fields:
The EIP-627 mentions: `where size is the size of the full RLP-encoded envelope.`
The go-ethereum code seems to not use the RLP-encoded envelope size: https://github.com/ethereum/go-ethereum/blob/8711e2b6366109912057e8fb20add325a1051a4e/whisper/whisperv6/envelope.go#L54
Which is used in `calculatePow`: https://github.com/ethereum/go-ethereum/blob/8711e2b6366109912057e8fb20add325a1051a4e/whisper/whisperv6/envelope.go#L139
While this will probably not create a huge difference in size, it can still be different.

2. PoW Hash:
The EIP-627 has following line of code:
`fn pow_hash(envelope, env_nonce) = sha3(short_rlp(envelope) ++ env_nonce)`
But the code written in `calculatePow` and also in `Seal` does something else: there is a sha3 (keccak) digest done first on the `short_rlp` of the envelope, and then again on the resulting hash + the `env_nonce` (with some zeroes in between I guess?).
Why this difference? The `++` in the EIP does just mean append right?

I realize the EIP-627 specification is still in draft, but I would like to clear this out as without a correct PoW calculation, different implementations will not be able to properly work together (especially with different PoW hashing).

**Comment by kdeme** [comment]
ping @gballet

**Comment by xiaods** [comment]
interesting topic

**Comment by gballet** [comment]
Fixed with https://github.com/ethereum/go-ethereum/pull/19330

**Comment by gballet** [comment]
Thanks for catching that @kdeme

**Comment by kdeme** [comment]
Thanks, but my second point remains still valid: Why is there a `Keccak256()` done twice?

**Comment by gballet** [comment]
@kdeme thanks for pointing this out; I investigated and the double Keccak256 is a leftover from v5. v6 is updated with https://github.com/ethereum/go-ethereum/pull/19753
