### ISSUE TITLE
Puppeth: No ethstats server configured

### ISSUE THREAD

**Issue by zulhfreelancer** [ethereum/go-ethereum#18086]
#### System information

Geth version: 1.8.18
OS & Version: Linux
Commit hash : 1ff152f3a43e4adf030ac61eb5d8da345554fc5a

#### Expected behaviour

Able to install Ethstats in node server from controller server without any issues.

#### Actual behaviour

Due to [recent change in Docker Compose to container naming convention](https://docs.docker.com/release-notes/docker-compose/#1230-2018-10-30), the controller server now can't reach the Ethstats container running in node server.

![docker-compose](https://user-images.githubusercontent.com/3416976/48353982-948fc600-e6cb-11e8-87f8-a629daf3d86e.png)

[Docker inspect logs](https://pastebin.com/raw/k6cH7CC9)

Notice the `mypoa_ethstats_1_536797135bd7` instead of `mypoa_ethstats_1`.

#### Steps to reproduce the behaviour

Assuming you have created the genesis file using Puppeth in the controller server,

1. Install Docker Compose `1.23.1, build b02f1306` in the node server
2. From controller server, launch Puppeth
3. After entering network name, choose `4. Deploy network components`
4. Choose `1. Ethstats  - Network monitoring tool`
5. Choose `1. Connect another server`
6. Enter the IP address of the node server
7. Enter `8080` for the port
8. Enter `n` for `Allow sharing the port with other services`
9. Enter random string i.e. `secret` for `What should be the secret password for the API?`
10. You should see something like this:

```
+---------------+---------------+---------+--------+-------+
|    SERVER     |    ADDRESS    | SERVICE | CONFIG | VALUE |
+---------------+---------------+---------+--------+-------+
| xx.xxx.xx.xxx | xx.xxx.xx.xxx |         |        |       |
+---------------+---------------+---------+--------+-------+
```

[Example outputs](https://pastebin.com/raw/jrrtTpkL)

#### Additional Information

![discord](https://user-images.githubusercontent.com/3416976/48354426-af166f00-e6cc-11e8-8191-6959fe040e59.png)

I've raised this to Peter via Discord channel and he is now aware of this bug in Puppeth. He suggests to downgrade Puppeth to a version of Docker Compose prior to 1.23.0.

**Comment by zulhfreelancer** [comment]
I can confirm that I've no issues after downgrading to Docker Compose 1.22.0 version.

This is my oneliner script to remove and reinstall Docker Compose version 1.22.0:

```
sudo \rm -f /usr/local/bin/docker-compose && sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose && docker-compose --version
```

**Comment by karalabe** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/18281.
