### ISSUE TITLE
The contract transfer amount is incorrect

### ISSUE THREAD

**Issue by ViolainOt** [ethereum/go-ethereum#18096]
Execute the command：
contract.transfer(eth.accounts[0],9999999999999999000)

debug log:
```
msg="sending {\"jsonrpc\":\"3.0\",\"id\":196,\"method\":\"eth_sendTransaction\",\"params\":[{\"data\":\"0xa9059cbb000000000000008c324faaaa57e311b94a827be43bd5e9f8d79f000000000000000000000000000000000000000000000000008ac7230489e80000\",\"from\":\"0x8c324faaaa57e311b94a827be43bd5e9f8d79f00\",\"to\":\"0xa6d9531eb4756544795f19ab2d70272364e1aef6\"}]}"
```
Balance is `8ac7230489e80000`,should be `8AC7230489E7FC18`

**Comment by holiman** [comment]
```
>>> 0x8ac7230489e80000
10000000000000000000
>>> 0x8AC7230489E7FC18
9999999999999999000
```
Can confirm. However, 'contract.transfer' is not natively a `geth` thing, so I'm not sure where the error is. Could you provide some more info about how/where you're executing this, and versions etc.

**Comment by ViolainOt** [comment]
Using this contract  https://theethereum.wiki/w/index.php/ERC20_Token_Standard,the decimals set 18, The latest geth  c41e1bd1e

**Comment by holiman** [comment]
Try it in a browser, or any js console:
```
> 9999999999999999000
10000000000000000000
```
Javascript is quirky that way. You should use `BigNumber` to handle large numbers with accuracy. 
Example:
```
new BigNumber("9999999999999999000")
```
