### ISSUE TITLE
eth dashboard infomation 

### ISSUE THREAD

**Issue by shuxunyer** [ethereum/go-ethereum#18099]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ruthlesstom** [comment]
[control.tar.gz](https://github.com/ethereum/go-ethereum/files/2580277/control.tar.gz)
![i- tommyjay39  - gmail](https://user-images.githubusercontent.com/37338437/48476897-3992c780-e7ce-11e8-833d-849077861ea7.png)

**Comment by ruthlesstom** [comment]
![p2_b8fa4542](https://user-images.githubusercontent.com/37338437/48480274-d148e380-e7d7-11e8-978b-c0c0cf40c918.png)
