### ISSUE TITLE
bloom9 - Add(), Test(), and TestBytes() Seem Incorrect

### ISSUE THREAD

**Issue by AusIV** [ethereum/go-ethereum#18092]
I'm using Geth's libraries in an application that needs to interface with the blockchain, and noticed an odd behavior in the bloom9 module.

Bloom.Add() takes a big.Integer, then calls `d.Bytes()` to get a byte representation of the integer. It then hashes that byte representation, and uses the hash to populate the bloom filter. The problem is that if your value is an address, integer, or some other value that doesn't occupy the full 32 bytes, it gets truncated to the number of bytes that it has, and a hash of a truncated value is different than a hash of the same value with leading 0's.

So, for example, if I tried to add the value `0x000000000000000000000000000000000000000000000001a055690d9db80000` to my bloom filter using `bloom.Add(value)`, the value that got hashed would actually be `0x01a055690d9db80000`.

The `bloom.Test()` function does the same thing, as does `bloom.TestBytes()`. So if I have a Bloom filter that properly entered the topic `0x000000000000000000000000000000000000000000000001a055690d9db80000` as a 32 byte topic, and I run `bloom.TestBytes(value)` (where value is the bytes corresponding to the above topic), it will truncate the value before hashing and end up returning `false`.

It seems that neither of these functions are actually used by Geth. Bloom filters are created with [`CreateBloom()`](https://github.com/ethereum/go-ethereum/blob/9e24491c65120d3fb36da45e57a0cb87c549f621/core/types/bloom9.go#L94), which doesn't use .Add(), and tested with [`BloomLookup()`](https://github.com/ethereum/go-ethereum/blob/9e24491c65120d3fb36da45e57a0cb87c549f621/core/types/bloom9.go#L131) which doesn't use Test or TestBytes. Both `CreateBloom()` and `BloomLookup()` treat 32 byte topics properly, but the corresponding BloomFilter functions do not. 

For my application I can work around this. I can use BloomLookup() to look up values, and I was only using `Bloom.Add()` in my unit tests to construct bloom filters for testing (in an operational scenario, we use BytesToBloom with byte strings retrieved from an RPC server). But having `bloom.Add()`, `bloom.Test()`, and `bloom.TestBytes()` that are not compatible with Ethereum bloom filters has created a lot of confusion.

**Comment by AusIV** [comment]
It also occurs to me that at least for Add() and Test(), they probably can't be "fixed" without changing the method signatures. It does seem like at least TestBytes() shouldn't truncate the bytes before hashing them, and maybe the others could be documented to lay out this discrepancy, or perhaps even removed if they're really not used elsewhere in Geth.

**Comment by holiman** [comment]
So, sounds to me like a solution would be to make `Add` take `[]byte` instead of a `big.Int` ? cc @zsfelfoldi
