### ISSUE TITLE
--rpcaddr and --wsaddr should support netmasks

### ISSUE THREAD

**Issue by dimroc** [ethereum/go-ethereum#18117]
Hi there,

It would be fantastic from an ops perspective to have a feature that limits RPC and WS to IPs that adhere to a netmask. This would allow devops to restrict calls to internal ip addresses as defined by https://en.wikipedia.org/wiki/Private_network and [RFC 1918](https://tools.ietf.org/html/rfc1918):

* `10.0.0.0/8`
* `172.16.0.0/12`
* `192.168.0.0/16`

Usage: `geth --rpc ---rpcaddr "10.0.0.0/8"`

#### System information

Geth version: `1.8.18`
OS & Version: Windows/Linux/OSX

#### Expected behaviour

```
---rpcaddr "10.0.0.0/8"
```

only allows IPs adhering to the mask to make JSON-RPC calls.

#### Actual behaviour

Errors out with:

```
Fatal: Error starting protocol stack: listen tcp: lookup 10.0.0.0/8: no such host
```

#### Steps to reproduce the behaviour

```
geth --rpc --rpcaddr "10.0.0.0/8" --testnet
geth --ws --wsaddr "10.0.0.0/8" --testnet
```

**Comment by karalabe** [comment]
These are not the source addresses that are allowed to connect. The address is the network interface inside your own machine that you want to listen on.

**Comment by gballet** [comment]
@dimroc this would be redundant with what a packet filter like bpf does. What would be the advantage of implementing this in geth?

**Comment by dimroc** [comment]
@gballet It would be. Just thought it would ease deployment on a node you want to restrict to internal ips.

Currently, the purpose of this field seems to be to constrain connecting ips to either localhost or all (0.0.0.0). Rather than having a whole netmask, we could compromise by adding a third option that only limits it to internal ips as defined by RFC 1918.

Far easier operationally to configure than managing your own BPF, but I understand if this is something you don't want to include in `go-ethereum`.

**Comment by fjl** [comment]
- If you use `--rpcaddr 127.0.0.1`, nobody outside of localhost will be able to connect.
- If you use `--rpcaddr 10.0.0.1`, nobody outside your local network will be able to connect.

**Comment by holiman** [comment]
Use `iptables` or whatever the firewall the distro is bundled with.

**Comment by dimroc** [comment]
@fjl Just to clarify, what you've listed is the ask. Right now the only legal options for `--rpcaddr` are
* 0.0.0.0
* localhost

Yes, all of this can be done with a firewall. But so could everything to do with the current implementation of `rpcaddr/wsaddr`. It exists for ease of security and use, which is what this request wants to build on.

**Comment by lelikalf** [comment]
type

**Comment by holiman** [comment]
> But so could everything to do with the current implementation of rpcaddr/wsaddr. It exists for ease of security and use, which is what this request wants to build on.

No, the `rpcaddr` specifies which interface we should listen to. It's not about security, it's simply impossible to open an rpc service unless we know what interface to use.
