### ISSUE TITLE
Own blockchain based on Ethereum

### ISSUE THREAD

**Issue by axmadjon** [ethereum/go-ethereum#18125]
Hi everybody and developers ethereum

I have one simple task, which I think how can I do this, please help me, I will be very happy to everyone.

I need to create a blockchain that saves user queues and product information,
there will be no account in it and any data about the cryptocurrency,
there will only be a user's queue history and possibly product information.

help please can i use ethereum solution in my project or will it be impossible to do better from scratch

thank you all

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
