### ISSUE TITLE
Separating chain data from state data

### ISSUE THREAD

**Issue by Helios-vmg** [ethereum/go-ethereum#18123]
First off, let me see if I understand how Geth syncing works:
1. Assume that the node is synced up to height n.
2. Fetch the next block from the network.
3. Transition the state from state[n] to state[n+1].
4. If not in archive gcmode, prune superseded state information.
5. Now the node is synced up to height n+1.

It would seem that to sync Geth only needs the state that resulted from the last block, plus information from previous blocks, such as hashes. That's the information that's going to require the most IOps from the storage device, while the old state information is only needed to replay old transactions and such. It's also the case that this old state information comprises the vast majority of the size of the blockchain (since a full node uses around 150 GiB, while an archive node uses well over a terabyte). If this information was physically separate (as in, in a different directory) from the data Geth actually needs to sync, the cost of a full node could be significantly reduced. For example, someone could create a symlink so that .ethereum/geth/olddata points to a directory in a regular HDD. One way to implement this could be by modifying the prune behavior so that it moves data out of chaindata and into this other directory.

**Comment by rjl493456442** [comment]
PTAL https://github.com/ethereum/go-ethereum/pull/17814

**Comment by Helios-vmg** [comment]
Thanks. I've subscribed to that PR, as it seems extremely relevant.

**Comment by holiman** [comment]
This is now implemented in `master`, and is slated for release in 1.9 .
