### ISSUE TITLE
ipc: use shared folder

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#1812]
Since the IPC is a standardised (or becoming) we should store this in a shared folder so that both `eth` and `geth` can benefit from the same location.

Shared FDs should go to `~/.ethereum/shared`. The FD should be renamed from `geth.ipc` to simply `ipc`.

**Comment by obscuren** [comment]
What are we currently using for `windows`?

**Comment by bas-vk** [comment]
The default on Windows is `\\.\pipe\geth.ipc`. We can change that to `\\.\pipe\ethereum`. I would suggest to use `${datadir}/shared/ethereum.sock` as the default name for the unix socket endpoint. According to [FHS](http://www.pathname.com/fhs/pub/fhs-2.3.html) we should place them in `/var/run`. But this requires root permissions.

**Comment by frozeman** [comment]
Why not the `/tmp/` folder anymore?
Because on macosx, the Ethereum folder is in `~/Library/Ethereum` and cpp is in `~/Library/Application Support/Ethereum` So we would still have a different folder.

**Comment by frozeman** [comment]
@obscuren can you please comment?

**Comment by fjl** [comment]
From #2317 
> I think ~/.web3/node.socket could be a good, implementation-neutral location for the socket file. On Windows it would be \.pipe\web3\node or a similar name.

**Comment by frozeman** [comment]
I would not like to use `.web3` or `pipe/web3/`, As this is specific to and ethereum node..
