### ISSUE TITLE
Questions about Puppeth and its cluster components

### ISSUE THREAD

**Issue by zulhfreelancer** [ethereum/go-ethereum#18122]
Hi,

I tried my best to get help from the community inside Go Ethereum Discord channel, Gitter channel and Ethereum StackExchange. Unfortunately, I receive zero answer about my questions here.

I'm running Puppeth to create and manage my PoA private blockchain cluster. This cluster has 4 servers; 1 controller server and 3 node servers. The Puppeth components can be found in the bottom section.

#### System Information

Geth version: 1.8.18
OS & Version: Linux, Ubuntu 16

#### Nodes Information

[View on Pastebin](https://pastebin.com/raw/mdSiYnuJ)

Here are my questions:

1. If I accidentally run `docker rm -f the_sealer_node` in my node server, will it delete the datadir volume?

2. My bootnode now supports 256 light nodes. Each sealernode has 3 seats for light nodes. From what Péter Szilágyi explained to me, the Faucet service is relying on the light nodes.

![image](https://user-images.githubusercontent.com/3416976/48645653-4529fc80-ea21-11e8-8ca7-5844185099da.png)

Unfortunately, the Faucet app shows `Faucet offline` message and I've no idea why I get this error. How do I fix it?

3. Where does controller node stores all the information about my nodes and other components? In which folder? Or, it fetches everything via SSH everytime after I enter the network name?

4. Here is the diagram of my current PoA private blockchain setup:

![image](https://user-images.githubusercontent.com/3416976/48645777-9803b400-ea21-11e8-9919-62202d241096.png)

All the nodes inside my cluster are talking to each other via 30303 port. When I want to talk to them, I'm using a Geth light client via HTTP JSON RPC port 8545. This Geth light client run on my localhost.

Only the Geth light client here opens HTTP JSON RPC. All my nodes in the cluster doesn't open HTTP JSON RPC port. They only open 30303 port.

All nodes in my cluster and my Geth light client node shared the same _genesis.json_ file. The `enode` address of all the nodes in the cluster are keep private and has not leaked to public yet.

So my question here is, what possible could go wrong with this setup in terms of security?

Could someone (a bad guy) do anything bad to my private blockchain cluster if I keep the 30303 port open to public?

Could they guess the content of the _genesis.json_ file and the `enode` addresses?

5. Take a look at my Ethstats component UI below:

![image](https://user-images.githubusercontent.com/3416976/48645914-16605600-ea22-11e8-80f8-af052fc71484.png)

Why the colors sometimes change between red, orange and green? What does it mean for each color?

6. Is it normal that sometimes the nodes show 0 peers or lower than what it should be? I noticed that my nodes somestimes show 0 and 1. I'm expecting 3 because I have 3 sealnodes running.

7. Does Puppeth team has any plan to produce two (2) versions of genesis file? One for Geth and another one for Parity?

8. Will all the Puppeth components will auto-restart and discover each other again after the hosts/Ubuntu server get rebooted?

9. Just curious, why the Explorer component doesn't work for PoA?

10. How do I put `static-nodes.json` file inside the sealnodes? I know [how to do it](https://github.com/ethereum/go-ethereum/wiki/Connecting-to-the-network#static-nodes) without using Puppeth. Any pointers? Seems like the files inside the sealnode's datadir are protected and I can't simply write a new file inside it.

🙏🏼 I do really appreciate all the detailed answers. Please also share with me links to related resources about my questions here (if any).

Thank you.

**Comment by collincusce** [comment]
I tossed up a new clique network using puppeth today and am seeing this as well. Faucet Offline error. Also block times were set to 5 but they seem to average around 14. From what I can tell, my genesis is configured properly, with a period of 5 and an epoc of 3000 on clique, plus I'm getting errors when I try to toss up a explorer saying it only works for ethhash (as it should). That said, I haven't dove deeper.

These are the exact instructions I followed... and I wrote the article too. :-P

https://medium.com/@collin.cusce/using-puppeth-to-manually-create-an-ethereum-proof-of-authority-clique-network-on-aws-ae0d7c906cce

My article was on Ubuntu 16.04 and go-eth release 1.8.12 .

Recent install is Ubuntu 18.04 and go-eth release 1.8.18.

![screenshot from 2018-11-21 16-31-32](https://user-images.githubusercontent.com/6778681/48869389-02627e80-edab-11e8-8cad-a438fc2f2518.png)

![screenshot from 2018-11-21 16-34-41](https://user-images.githubusercontent.com/6778681/48869487-66854280-edab-11e8-8ddb-7dd1ba91967b.png)

[setup_healthcheck.txt](https://github.com/ethereum/go-ethereum/files/2605855/setup_healthcheck.txt)

[pinecone.txt](https://github.com/ethereum/go-ethereum/files/2605859/pinecone.txt)

About to head home for vacation until monday, but let me know if you need anything else.

**Comment by zulhfreelancer** [comment]
I posted the Fauce Offline problem into a new issue [here](https://github.com/ethereum/go-ethereum/issues/18257) for better tracking.

I'm still keen to know the answers for my questions above.

**Comment by karalabe** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/18281. The issue was a regression at https://github.com/karalabe/go-ethereum/commit/30cd5c18549f645002aedb4c00e5bab683cb0835#diff-ff207ab75e75547b60446dd050e7e8dbR259.
