### ISSUE TITLE
Blocks are higher number of count compared with Ropsten Etherscan

### ISSUE THREAD

**Issue by tnkannan** [ethereum/go-ethereum#18133]
Hello,

We are facing an issue in our geth Ropsten testnet server.

The block number of a transaction confirmed on Ropsten Etherscan and our geth server is different.

Our Geth server block number is ahead of Ropsten Etherscan blocks.

Thanks,
Kannan TN

#### System information
Geth version: 1.7.2-stable-1db4ecdc
OS & Version: Linux Ubuntu 6.4
Commit hash : (if `develop`)

**Comment by karalabe** [comment]
Ropsten was transitions over to Constantinople. You are on the old chain if you are using Geth 1.7.2 (we did 19 releases since then). Please update to 1.8.18.
