### ISSUE TITLE
Light client: sendTransaction "no suitable peer available"

### ISSUE THREAD

**Issue by aghamir** [ethereum/go-ethereum#18135]
#### System information

Geth version: `1.8.18 and 1.8.19-unstable`
OS & Version: Linux

#### Expected behaviour
Geth `personal.sendTransaction` works without error.

#### Actual behaviour
Geth got synced, but `sendTransaction` return `err="no suitable peer available"`(In both stable and unstable version).

#### Steps to reproduce the behaviour
1- Run geth with light mode
2- Use `personal.sendTransaction`

**Comment by ligi** [comment]
You might want to look into [vipnode](https://vipnode.org/)

**Comment by JayMaree** [comment]
I have the same issue. No solution? I run v1.8.23

**Comment by zsfelfoldi** [comment]
We had a transaction sending issue recently that has been fixed. If it does not work now then the issue might be actually that there are no suitable peers available at the moment. Insufficient available service is being addressed currently in multiple ways (higher performance servers, prioritization and incentivization).
