### ISSUE TITLE
 geth highestBlock always lowwer eth.io 5-8blocks

### ISSUE THREAD

**Issue by fishmc** [ethereum/go-ethereum#18138]
Hi there,

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
clientVersion : Geth/LeoNode1/v1.8.19-unstable-51e2e78d/linux-amd64/go1.11.2

![image](https://user-images.githubusercontent.com/4209839/48750618-f1d2db00-ecba-11e8-9697-ec8d5a89a4b1.png)

**Comment by mrFranklin** [comment]
the reason is: the geth node which you connect to synced a little slower, you can change a faster geth node, or let the node connect to other faster nodes to sync latest blocks.
