### ISSUE TITLE
Getting different sealed hash values in two nodes in private network.

### ISSUE THREAD

**Issue by venu1666** [ethereum/go-ethereum#18132]
![node2](https://user-images.githubusercontent.com/40895991/48704120-cbaa2e00-ec1b-11e8-8ba6-442975dd47a9.PNG)

![node1](https://user-images.githubusercontent.com/40895991/48704207-f85e4580-ec1b-11e8-99e7-aaee5b88b881.PNG)

In two nodes getting different sealed hash values.When transaction has been done  on 8629 block both nodes  are producing different sealed hashes.Can someone explain me about this problem.
                              Thank you in advance

**Comment by karalabe** [comment]
If you are mining with different addresses, then the block header will naturally be different, so it's hash will be different too.

**Comment by venu1666** [comment]
yes  i am mining with two different addresses but according to proof of work only one node has to seal the block but here why two nodes are sealing the same block,is it running correctly or is  there any error?

**Comment by holiman** [comment]
only one node _has_ to seal each block, but it's a distributed consensus. Both operate without coordinating with the other, so both produces blocks . 
See https://eips.ethereum.org/EIPS/eip-225 for a detailed explanation of Clique consensus engine
