### ISSUE TITLE
geth syncing full.I can get blockNumber,but eth.syncing currentBlock not change

### ISSUE THREAD

**Issue by fishmc** [ethereum/go-ethereum#18131]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour

 modules: admin:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> eth.syncing
{
  currentBlock: 6706489,
  highestBlock: 6732083,
  knownStates: 244765853,
  pulledStates: 244765853,
  startingBlock: 6702728
}
> eth.blockNumber
6706489

#### Backtrace

````
[backtrace]
````

**Comment by rraallvv** [comment]
Does eth_blockNumber return a value different than zero?

**Comment by rraallvv** [comment]
By the way could you please post your current number of `knownStates`, mine is:

    > eth.blockNumber
    0
    > eth.syncing
    {
      currentBlock: 6812937,
      highestBlock: 6813041,
      knownStates: 254110444,
      pulledStates: 254105307,
      startingBlock: 6812739
    }

**Comment by fishmc** [comment]
> ，请你发布你当前的号码`knownStates`，我的是：

是的，不返回零了

**Comment by adamschmideg** [comment]
This is an old issue with little information. not even OS and version specified. If the problem persists with a more recent version of Geth, please open a new ticket with more information (version, OS, command line args, logs).
