### ISSUE TITLE
eth_submitWork RPC without wallet

### ISSUE THREAD

**Issue by oliverw** [ethereum/go-ethereum#18137]
Short question: Is the eth_submitWork RPC supported in a scenario where the geth instance handling the RPC does not own the wallet associated with the block reward output address? Phrased differently, can you submit blocks on behalf of another wallet controlled by another geth instance?

**Comment by rjl493456442** [comment]
Sure, geth instance only cares about whether there is a coinbase address, not about whether the address is controlled.
