### ISSUE TITLE
[Feature] Flush trie cache before a hard fork

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#18153]
We're doing in-memory GC. It might be useful to explicitly write out a snapshot of the state before reaching a hard fork block, so in case of consensus errors, we don't need to reimport potentially an hour's worth of blocks, rather ca start fro the problematic block.

This feature is more about damage control during problematic hard forks.

**Comment by MysticRyuujin** [comment]
Is there a command to force a flush before restarting a node? I run with a large cache and when I restart Geth I lose about 4,000 blocks. Should I just stop using a large cache or can I execute something to prior to the shutdown to avoid such a loss?

**Comment by karalabe** [comment]
@MysticRyuujin Just shut Geth down gracefully. It flushes its cache before terminating.

**Comment by MysticRyuujin** [comment]
So, what does gracefully mean to you? I ask because I had previously opened an issue a long time ago about Geth not gracefully exiting on SIGTERM which you fixed and if I remember correctly included all graceful exit signals? Does the `reboot` command on an Ubuntu server not send a graceful exit signal? I assume it is does...

**Comment by holiman** [comment]
@MysticRyuujin are you running it through e.g. docker? Docker typically gives it some time to shut down, but after some timeout (an insufficient timeout) it hard-kills it anyway. So if it's docker, you will need to increase that timeout. 

A `ctrl-c` typically shuts it down gracefully, and that's a sigterm, no?

**Comment by MysticRyuujin** [comment]
I run it as a service using supervisor, which caused my original problem asking for Geth to support SIGTERM haha. After Peter fixed the SIGTERM issue, I didn't have any problems with shutdown after that. But it's been quite a while since I ran a node.

**Comment by devrandom** [comment]
Well, it's not good that there's no flushing on an ongoing basis.  I also see a loss of many blocks if for any reason `geth` dies ungracefully.

That said, I think ongoing flushing deserves a separate issue.

**Comment by Heph789** [comment]
Does this still need work? I'd love to give it a try if someone could give me further direction on how to solve this issue.
