### ISSUE TITLE
[whisper] no feedback that the message reached the connected peer

### ISSUE THREAD

**Issue by dshulyak** [ethereum/go-ethereum#18159]
One of our use cases is to use whisper for public broadcast communication. We are running it on mobile, where unpredictable network connection is a common thing. In a situation when client sends a message and network connection is lost it will have no feedback that message will never reach the network.

In case when two clients are having private conversation it is easy to tolerate this lack of feedback. For example by sending delivery confirmations. However in case of public broadcast communication lack of any feedback on the whisper level leads to really poor experience.

#### System information

Geth version: 1.8.18
OS & Version: any

#### Actual behavior

To provide a concrete example of this issue:  Alice connected to two nodes X an Y. Alice loses her network connection to nodes X and Y, but devp2p will know about it only after 30 seconds (current write/read socket deadline). After 30 seconds passes Alice notices that it has no connections at all, and it stops all communication. But all messages that were written during 30 seconds window now in unknown state.

#### Expected behavior

It would be nice to get a better guarantee that messages at least reached closest peers. The way it can be done is to introduce separate whisper p2p message code - confirmationCode. This code will be sent as a response to messagesCode. The response itself would be a hash built from the rlp encoded list of envelopes.

On the side of the sender we will wait for described response, and notify the client that the envelope "reached the network".

I fully understand that it doesn't provide strict guarantee, but given the use case it improves guarantee that the public message will be seen by more people. And can be improved further by using set of known nodes.

#### Steps to reproduce the behavior

To reproduce create two whisper nodes A and B.
A would be a sender, and B receiver.
Start sending messages from node A, and block traffic between this two nodes, for example by dropping all packets with iptables.

@gballet what is your opinion about this use case?

**Comment by gballet** [comment]
Traffic is already a problem in Whisper, adding a new message type isn't going to help. Whisper is more like IP than it is like TCP and encumbering the protocol with traffic control features is a departure from its "simple, secure" philosophy. For those two reasons, I'm not so keen on the approach, which could be implemented at a higher level.

One question though: could you not achieve the same thing by keeping the messages for the 30 seconds that it takes devp2p to disconnect? If you don't get a disconnect afterwards, then you know that they have made it to the network. Let me know that you think.

**Comment by gballet** [comment]
@dshulyak I am closing the issue. If you feel my counter-argument is weak, please reopen it as I'm happy to discuss the matter further.
