### ISSUE TITLE
[p2p] [feature] Add bandwidth limiting

### ISSUE THREAD

**Issue by dshulyak** [ethereum/go-ethereum#18160]
Current devp2p connections are not rate limited. This might be important for home users and especially important for mobile devices. We want to prevent les/whisper from accidentally eating all available mobile traffic.

I am considering to wrap all connections that are created in p2p.Server with a single token based rate limiter. And allow to reconfigure this rate limiter without p2p.Server restart. 

@fjl what do you think about it?

cc @ligi as you are building mobile wallet with LES

**Comment by ligi** [comment]
I love the idea of consuming less bandwidth - not sure how feasible this is though. Hope @fjl can chime in. Also cc @gballet for the whisper side of things.

**Comment by gballet** [comment]
it makes sense to do that with mobile. In the case of libp2p, that could be implemented as a plugin if it doesn't already exist.

One thing that isn't clear to me: do you want to have per-connection limits or global limits?

**Comment by adamschmideg** [comment]
Not many people chimed in showing an interest.

**Comment by karalabe** [comment]
Btw, we're not against this feature in general, just it's not really an obvious thing. There are also new protocols being rolled out to reduce the tx bandwidth + maybe a new sync algo that might help. All in all it might be worthwhile to pursue optimizing the protocols more than limiting them.
