### ISSUE TITLE
eth_getTransactionReceipt should initialize status to unknown

### ISSUE THREAD

**Issue by elv-gilles** [ethereum/go-ethereum#18163]
From the code (master), the `Status` of a [Receipt](https://github.com/ethereum/go-ethereum/blob/master/core/types/receipt.go) can take a value `ReceiptStatusFailed` (0) or `ReceiptStatusSuccessful` (1).

Unfortunately the status field is not always provided therefore making impossible to distinguish between 'unknown' and 'failed'.

It seems it would make sense to add a `ReceiptStatusUnknown` (0xFF) and initialize the status as unknown before decoding / unmarshalling (don't know the implication for the rest of the code though).

**Comment by karalabe** [comment]
The status field was introduced in Byzantium. All receipts before that will have this field missing (or meaningless). After Byzantium, all receipts should have this set correctly. Are you seeing incorrect values somewhere?

**Comment by elv-gilles** [comment]
@karalabe 
thanks for the answer: that's good to know. 

I'm dealing with private chains though so in my case one had the status field set and the other one missing...

**Comment by codebazz** [comment]
@karalabe How can I get status field in my already running private geth node?

**Comment by apa7** [comment]
> @karalabe How can I get status field in my already running private geth node?

I also get the status undefine of getReciept Data under privateNet.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by gballet** [comment]
@sharif2008 if your network is already running, you need to fork your network to support Byzantium features.

@elv-gilles if you feel your answer has not been fully addressed, let us know.
