### ISSUE TITLE
I have connected two notes using bootnode in ethereum private blockchain but mining is not started why?

### ISSUE THREAD

**Issue by SabarishT** [ethereum/go-ethereum#18170]
I have generated the enode from Bootnode in Ethereum private network and i connected three individual nodes using that enode through Bootnode, and i have checked whether that nodes are connected or not with my current node using the command "admin.peers"
![screenshot2](https://user-images.githubusercontent.com/29983995/48945925-0c72b180-ef52-11e8-856e-ad1adcb03fd8.PNG)

those three nodes are conected successfully

then i start the mining using the command miner.start() Geth not started 
![screenshot1](https://user-images.githubusercontent.com/29983995/48945945-22807200-ef52-11e8-9276-153ddb0fd1ef.PNG)

As of my observations i am getting the line constantly, 
Line => "Regenerated local transaction journal transactions=0 accounts=0" 
for every one hour as we can see in the above screenshot But even single block is not created
I have created following simple genesis.json for above nodes. 

{
    "config": {
        "chainId": 1015
    },
    "difficulty": "0x400",
    "gasLimit": "0x8000000",
    "alloc": {
        "ef2df6e0a312875ca7e35d8d3579cf66df558193": {
            "balance": "30000000000000000000000000000"
        }
    }
}

Question : Why is mining not started, How to start mining? please give me some suggestions and guide me if i am wrong

**Comment by karalabe** [comment]
Specify the number of threads to start mining with if you want CPU mining (e.g. `miner.start(1)`). By default `miner.start()` just starts preparing tasks for remote miners, but doesn't CPU mine.

**Comment by SabarishT** [comment]
I have tried with
> miner.start(1)
command also the same issue arising

**Comment by karalabe** [comment]
Please paste the logs you're seeing.

**Comment by SabarishT** [comment]
![screenshot3](https://user-images.githubusercontent.com/29983995/49081490-0d1a8900-f26d-11e8-8cba-ec73887381be.PNG)

**Comment by SabarishT** [comment]
Ok thanks i will update. Could you please tell me is there any problem with older versions regarding multi node connection using boot node concept .

**Comment by freshner** [comment]
Thanks for replying. Setup of the software have successfully downloaded but
it is not installing either on my laptop or my computer.

**Comment by rajajwaliya** [comment]
can you help me in "how to connect two nodes using bootnode in ethereum private blockchain  ??"

**Comment by adamschmideg** [comment]
I understand the original problem was fixed by Geth 1.8.18. If you experience a new problem, please open a separate issue for it.
