### ISSUE TITLE
When i run ”make geth“ .  return it

### ISSUE THREAD

**Issue by yuanbi** [ethereum/go-ethereum#18174]
When i run “make geth ”. 
return it

version 1.3.3

build/env.sh go install -v  ./cmd/geth
github.com/ethereum/go-ethereum/common/natspec
# github.com/ethereum/go-ethereum/common/natspec
common/natspec/natspec.go:164:25: undefined: natspecJS
Makefile:17: recipe for target 'geth' failed
make: *** [geth] Error 2

**Comment by karalabe** [comment]
Version 1.3.3? That's possibly 50-100 releases old. Please update and build a modern version of Geth.

**Comment by ishaan-kesari** [comment]
Hello Peter,
I am a javascript developer.I liked this Project a lot. Could you please
brief me about how i can start contributing to this project.

Thanks,
Ishaan
linkedin.com/in/ishaankesari
