### ISSUE TITLE
Sync speed message improvement

### ISSUE THREAD

**Issue by destenson** [ethereum/go-ethereum#18176]
I've been playing with geth's code this weekend in attempt to speed up syncing & found that ```mgasps``` just didn't do it for me to rate the sync speed.

Since there are ~13s/block and a maximum of 8Mgas/block, that number can be converted into a speed relative to the maximum targeted speed of the blockchain in Mgas/s.

It's an easy change and I've already done so. See #18177.

**Comment by holiman** [comment]
I'll close this ticket, let's continue the discussion in the PR. No nede to have two places for it IMO
