### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 0mkara** [ethereum/go-ethereum#1818]
#### OS :
Fedora 20 || Linux mount-kailash 3.19.8-100.fc20.x86_64 #1 SMP Tue May 12 17:08:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

#### Go version :
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

#### Error description :
I followed go-ethereum installation instruction and did the following things -
> git clone go-ethereum.git
> make
> build/bin/geth

Then I am getting this error.
###### Error log : http://fpaste.org/269002/59583314/raw/

**Comment by tgerring** [comment]
Looks like it might be a bug with Fedora: https://stackoverflow.com/questions/26575662/user-current-not-implemented-on-linux-amd64-with-fresh-golang-on-fedora

I don't see anywhere that the Go version is mentioned above? If you're on 1.4, you may want to try upgrading to 1.5 first and see if that resolves anything

**Comment by 0mkara** [comment]
I was on the IRC with this problem. I was suggested to change DefaultDataDir() to return my current dir where the files reside. That solved the problem. Just issued a bug report for things to resolve permanently. :+1:

**Comment by Gustav-Simonsson** [comment]
Looks like it should work with Go 1.5: https://bugzilla.redhat.com/show_bug.cgi?id=1135152#c12

Meanwhile if someone else runs into this on Fedora you can hack this by changing this function: https://github.com/ethereum/go-ethereum/blob/master/common/path.go#L102 to:
```Go
func DefaultDataDir() string {
	return "/home/user/.ethereum"
}
````
To set the directory.

**Comment by karalabe** [comment]
It's simply sloppy coding. The data dir func simply ignores a possible error, which results in a panic on Android too. It was a bad decision to ignore it just because it *should* work. I'll open a PR tomorrow or Monday.

**Comment by 0mkara** [comment]
Seems this is a known golang bug.
http://stackoverflow.com/questions/26575662/user-current-not-implemented-on-linux-amd64-with-fresh-golang-on-fedora

**Comment by fjl** [comment]
I added "show stopper" because it doesn't start at all if this error occurs. This is also an issue on android.
We should update the code to print a proper error if the home directory cannot be detected.

**Comment by obscuren** [comment]
Understood, but it's not a show stopper. If all major target platform would suffer from the same behavior it'd be classified as show stopper. At the moment there are no android users and hardly any fedora users (does not mean it shouldn't get fixed).

**Comment by 0mkara** [comment]
Just returning the current path is working for me. Hope it will be a easy fix. It is definitely the golang bug as [this bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1135152) says.
