### ISSUE TITLE
Performance: disable EvictNS

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#18181]
See https://github.com/syndtr/goleveldb/issues/245 

Profiling done while importing blocks during a full sync, somewhere around the 4M -range. 
![profile002](https://user-images.githubusercontent.com/142290/49008933-6d2b0580-f16f-11e8-8869-a15f6c1788c2.gif)

EvictNS responsible for `10.28s` , which is more than double the time spent on `keccakF1600`

**Comment by karalabe** [comment]
Can we build a version with this thing disabled and just run a benchmark against master? Would be a nice data point (you can nuke 08/09 for it).

**Comment by holiman** [comment]
Yes, I thought so too, but figured that if I wait a couple of days, maybe I don't have to mess with leveldb myself...

**Comment by holiman** [comment]
Leveldb updated to not use EvictNS by default now, building new images... Should be up pretty soon. WIll post charts here

**Comment by holiman** [comment]
It's runing now. During the first `4M` blocks or so , the `experimental` build with eviction disabled was actually slower: 
![leveldb_4m](https://user-images.githubusercontent.com/142290/49080669-ad0fec80-f244-11e8-9a55-572ccc99f8cd.png)
Somewhere around `4.17M`, the experimental caught up with master and went ahead: 
![leveldb_4m](https://user-images.githubusercontent.com/142290/49080695-bef18f80-f244-11e8-9228-ab61205b8ec2.png)

The section of blocks before `4M` are rather un-interesting, although there are lots of hardforks there, it's not until after `4M` that the really heavy stuff kicks in.

**Comment by holiman** [comment]
Here's the segment between around 4M to 4.8M. At the end of that section, it's about one hour ahead. 
![foo3](https://user-images.githubusercontent.com/142290/49137029-983a6400-f2eb-11e8-8338-445c05f59cc9.png)

**Comment by karalabe** [comment]
Unsure about the gains here. `mon08` is ever slightly more performant than `mon09` (if you run master on both).

**Comment by holiman** [comment]
Are you sure? I think I rebuilt them both as `i3` machines after we concluded that the new `m5d` were not equal. But maybe I'm confusing them with the `06`/`07` machines
