### ISSUE TITLE
in ethereum when i do transaction gas use is 21000  but i want to do the transaction as gas used 0

### ISSUE THREAD

**Issue by rushabh098** [ethereum/go-ethereum#18180]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
The cost of a plain transaction is 21000 gas. You can set the gas price (i.e. how much you want to pay for a unit of execution), but it will still consume 21000 units of execution to do the value transfer.

**Comment by rushabh098** [comment]
i want to pay gas used to be  0 @karalabe

**Comment by rushabh098** [comment]
i want to do gas used to be 0 @karalabe

**Comment by holiman** [comment]
No transaction can ever be executed with `0` gas. You can most definitely sign such a transaction, even using geth, but in order to execute such a transaction you will need to fork Ethereum into another blockchain.
