### ISSUE TITLE
POA  account  genesis.json account 

### ISSUE THREAD

**Issue by liwei00wade** [ethereum/go-ethereum#18195]
Is it  to include the contract in the genesis placing the bytecode as a “constructor” in the “accounts” field like so:

"0x0000000000000000000000000000000000000005": { "balance": "1", "constructor" : "0x..." }

**Comment by holiman** [comment]
No, geth does not support `constructor`. It does support `code`, though, so you can place the runtime code there instead, plus `storage`, so you can produce the exact same results anyway (since all a constructor does is create storage slots and return runtime bytecode)

**Comment by liwei00wade** [comment]
Could you send me an example or some document about it.
