### ISSUE TITLE
uint256 library performance

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#18191]
This is a placeholder ticket for some info about the attempt to replace `big.Int` with [`uint256`](https://github.com/holiman/uint256/)
The latest run, a full sync, did not show much promise. Even though the math operations are (oftentimes) orders of magnitude faster, the actual difference in time from `0` to `6.5M` was roughly `1.5h`. 
The most notable difference was mallocs going down by 15-20% . 
![uint256_vs_master](https://user-images.githubusercontent.com/142290/49114011-60a1cc80-f297-11e8-849c-93ce253b1aed.png)

**Comment by MariusVanDerWijden** [comment]
Uint256 library was merged in #20787 this issue can be closed
