### ISSUE TITLE
Delete old states

### ISSUE THREAD

**Issue by markya0616** [ethereum/go-ethereum#18190]
The chain data keeps growing, but most old state data is meaningless for us. Is there a way to delete old states and make a snapshot at a certain block?

#### Expected behaviour
A rpc call to delete old states and make a snapshot, or geth only keeps the latest blocks states.

**Comment by karalabe** [comment]
https://ethereum-magicians.org/t/ethereum-1-dot-x-a-half-baked-roadmap-for-mainnet-improvements/1995
