### ISSUE TITLE
rlp encode different time.Time but get same value

### ISSUE THREAD

**Issue by friends110110** [ethereum/go-ethereum#18207]
```
func () hash() (hash common.Hash) {
	newHash := sha3.NewKeccak256()
        timer := time.Now()
	rlp.Encode(newHash, []interface{}{
		timer

	})
	newHash.Sum(hash[:0])
	return hash
}

```

I invoke twice function hash ,but return the same value.
If changer timer to timer.String, they return different value.
Is there ethereum rlp has some bugs?

**Comment by karalabe** [comment]
`rlp` only encodes primitive data types or public fields of structs. A [`time.Time`](https://golang.org/pkg/time/#Time) struct only contains private fields, so you will end up encoding an empty slice for all invocations, hence the same hash.
