### ISSUE TITLE
[Feature] Travis cron jobs to do nightly light syncs

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#18200]
Although we're running quite a number of full nodes, the dev team isn't really hammering the light client as much as we should. A possible starting point would be to create 3 Travis nightly cron jobs that just spin up Geth instances and try to sync to mainnet, Rospten and Rinkeby with a 5 minute timeout. The idea would be to detect sync issues and anomalies during development, not half an hour before release when I do some sanity test runs.

**Comment by pratiksinghchauhan** [comment]
I would like to take this up and would request slight mentor-ship initially.

**Comment by MartinDawson** [comment]
I'd like to take this issue.

**Comment by Meshugah** [comment]
Do you have any further input on how this could be tackled? @MartinDawson

**Comment by jack17529** [comment]
@karalabe is this issue still active or this should be closed?

**Comment by ligi** [comment]
should be on the monitoring and not travis
