### ISSUE TITLE
go.Universe$proxyerror: open /proc/sys/kernel/hostname: permission denied

### ISSUE THREAD

**Issue by DaisyJin1** [ethereum/go-ethereum#18212]
I use the Geth fo android ,i want to init getBalance of a account;

describe:
it's wrong in "  ec= new EthereumClient(Constant.SEVICE_IP);"
wrong in phone which is android 8.0(API26),howerer android 7.0(API26) is ok.
Log show that:Exception e.toString()="go.Universe$proxyerror: open /proc/sys/kernel/hostname: permission denied"

* I want to know which permission I missed. please tell me what's wrong

lib:
implementation(name: 'geth-android-all-1.8.13-225171a4', ext: 'aar')
code:
AndroidMainifest:
```
1.android.permission.INTERNET
2.android.permission.WRITE_EXTERNAL_STORAGE
3.android.permission.READ_EXTERNAL_STORAGE
```
```java
   public static final String SEVICE_IP ="wss://mainnet.infura.io/ws";
 private String getBalance(Address address) throws Exception {
        ec= new EthereumClient(Constant.SEVICE_IP);
        BigInt bigInt = ec.getBalanceAt(Geth.newContext(), address, -1);
        Log.d("getBalance", bigInt.string());
        return bigInt.toString();
    }
```

**Comment by holiman** [comment]
So can we close this or should something change within geth?
