### ISSUE TITLE
Puppeth ceased working for new Clique chain deployment from 1.8.12 (works) to 1.8.13+ (broken)

### ISSUE THREAD

**Issue by collincusce** [ethereum/go-ethereum#18214]
I tossed up a new clique network using puppeth several times over the past few weeks and am seeing issues. Faucet Offline error. Also block times were set to 5 but they seem to average around 14 and there is hashpower being registered in ethstats. From what I can tell, my genesis is configured properly, with a period of 5 and an epoc of 3000 on clique, plus I'm getting errors when I try to toss up a explorer saying it only works for ethhash (as it should). 

These are the exact instructions I followed... and I wrote the article too. :-P

https://medium.com/@collin.cusce/using-puppeth-to-manually-create-an-ethereum-proof-of-authority-clique-network-on-aws-ae0d7c906cce

My article was on Ubuntu 16.04 and go-eth release 1.8.12.

Recent install is Ubuntu 18.04 and go-eth release 1.8.18.

My team has stepped through these instructions from 1.8.18 (broken, Ubuntu 16.04/18.04) down to 1.8.12 (operational, Ubuntu 16.04/18.04) and found that deploying a clique network breaks using my instructions from 1.8.12 to 1.8.13. 

I have looked at my instructions, as have a few other colleagues, and we are unable to see anything specific in my instructions which may be incorrect... but that possibility isn't out of the question. 

The more likely answer is that there's a breaking change between 1.8.12 and 1.8.13 that prevents puppeth from launching clique networks properly. 

![screenshot from 2018-11-21 16-31-32](https://user-images.githubusercontent.com/6778681/48869389-02627e80-edab-11e8-8cad-a438fc2f2518.png)

![screenshot from 2018-11-21 16-34-41](https://user-images.githubusercontent.com/6778681/48869487-66854280-edab-11e8-8ddb-7dd1ba91967b.png)

[setup_healthcheck.txt](https://github.com/ethereum/go-ethereum/files/2605855/setup_healthcheck.txt)

[pinecone.txt](https://github.com/ethereum/go-ethereum/files/2605859/pinecone.txt)

_Originally posted by @collincusce in https://github.com/ethereum/go-ethereum/issue_comments#issuecomment-440818925_

**Comment by collincusce** [comment]
So I chatted up my team. The problem was specifically puppeth. You can still use 1.8.18 geth nodes, but the puppeth deployments wouldn't work correctly past 1.8.12.

@karalabe :-)

**Comment by karalabe** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/18281. The issue was a regression at https://github.com/karalabe/go-ethereum/commit/30cd5c18549f645002aedb4c00e5bab683cb0835#diff-ff207ab75e75547b60446dd050e7e8dbR259.
