### ISSUE TITLE
ethereum log remould multiple files?

### ISSUE THREAD

**Issue by friends110110** [ethereum/go-ethereum#18232]
When I deploy ethereum using `geth` , the log file will be large day by day . So  how to code the log to meet the requirements:  seperate one file to multiple files by single file capacity limit or time (different day different file ).
Just  Like java springboot log4j2 framework?

**Comment by karalabe** [comment]
Geth does not have fancy log rotation logic. That's up to an external program (e.g. docker can do that). We believe in separation of concerns. It's hard for us to cater for all log rotation logic, whereas it's trivial to add your own log capture and rotator in front.

TL;DR If you want to rotate logs, add an appropriate application in front.
