### ISSUE TITLE
eth.namereg and registries

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1823]
Should `eth.namereg` be removed?
https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethnamereg

How does it fit with:
https://github.com/ethereum/go-ethereum/wiki/Contracts-and-Transactions/dfd59aa80ebe50218161140feccbad1f87d71c22

Too many registries is not helpful and only causes confusion.

**Comment by ethers** [comment]
https://www.reddit.com/r/ethereum/comments/3wp5hn/etherchainorg_is_now_linked_to_the_official_name/

**Comment by poshest** [comment]
I'm completely confused about name registries.  I was following this https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial#register-a-name-for-your-coin but it seems like namereg functions don't return anything meaningful. Nor do they return errors or any useful information.  Am I just using namereg wrong? Or was it a half-baked idea that's still yet to be deleted?
