### ISSUE TITLE
hello everyone is it possible to do transaction with 0 gas used

### ISSUE THREAD

**Issue by rushabh098** [ethereum/go-ethereum#18234]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
This is an issue tracker. We already replied https://github.com/ethereum/go-ethereum/issues/18180. Please don't open further duplicate issues.

We're maintaining go-ethereum. If you want to fork it and invent your own rules, nobody's stopping you, but don't expect us to do the work for you.
