### ISSUE TITLE
Get gorountine error when server write message to client.

### ISSUE THREAD

**Issue by kwan1988** [ethereum/go-ethereum#18238]
Hi there,

I have a filter to monitor the new block event, also have a http server for my application to call.
I got this message when i run the application after 6 hour.

#### System information

Geth version: `ethereum-1.8.17+build15807+xenial`
OS & Version: Linux Ubuntu 16 64bit
Commit hash : testnet 
Node Location : USA

#### Expected behaviour
NA

#### Actual behaviour
NA

#### Steps to reproduce the behaviour
NA

#### Backtrace
[geth.log](https://github.com/ethereum/go-ethereum/files/2642214/geth.log)

**Comment by holiman** [comment]
The log shows the tail end of a stack trace, and then the boot up of a new instance. I'm afraid that any relevant info in a stack trace is the head part, which is missing. Closing this, since there's not much we can do without more info

**Comment by holiman** [comment]
Ps. Sorry about not responding on this sooner!
