### ISSUE TITLE
build/env.sh: 30: exec: go: not found

### ISSUE THREAD

**Issue by spursy** [ethereum/go-ethereum#18248]
**I have use ubuntu 16, I have use the laste go-ethereum code.**

**My go version is:**
<img width="432" alt="2018-12-05 3 21 19" src="https://user-images.githubusercontent.com/11460991/49497124-8e43d280-f8a2-11e8-92c1-aea3a4e383c5.png">

**But I still get issues, when make geth:**
<img width="530" alt="2018-12-05 3 30 23" src="https://user-images.githubusercontent.com/11460991/49497237-e4187a80-f8a2-11e8-9535-c1742d2a4a66.png">

**Comment by karalabe** [comment]
Why do you use `sudo`?

**Comment by spursy** [comment]
if I do not use sudo, i do not have permission create files.

**Comment by fjl** [comment]
It looks like sudo is changing your PATH. You don't need to build with sudo though, just build it in your home directory and move 'build/bin/geth' to some other directory with sudo.
