### ISSUE TITLE
go1.11 can not compile ethereum 1.8

### ISSUE THREAD

**Issue by KnoooW** [ethereum/go-ethereum#18241]
the go version
```
$go version
go version go1.11.2 linux/amd64

```

the compiled source version
```
$git branch
* (HEAD detached at origin/release/1.8)
  master
```

and the error message
```
$make all
build/env.sh go run build/ci.go install
go tool cgo: exit status 2
flag provided but not defined: -V
usage: cgo -- [compiler options] file.go ...
  -debug-define
    	print relevant #defines

```

**Comment by sea51930** [comment]
#18241

**Comment by KnoooW** [comment]
> Could you please check the exact commit you're on? Go 1.11 introduced some breaking changes, so you need to have a fairly recent checkout.
```

commit 9cc0209ef1393ae472aed93335c6915cf3269f21 (HEAD, origin/release-branch.go1.11)
Author: Ian Lance Taylor <iant@golang.org>
Date:   Tue Nov 27 15:40:39 2018 -0800
```

**Comment by elsanosi** [comment]
$GOCACHE=off make all

**Comment by KnoooW** [comment]
> $GOCACHE=off make all

Same Error, Not solved

**Comment by elsanosi** [comment]
which OS?

**Comment by KnoooW** [comment]
> which OS?

centos7

**Comment by elsanosi** [comment]
Did you try:
go get -d github.com/ethereum/go-ethereum
go install github.com/ethereum/go-ethereum/cmd/geth

Otherwise, remove GO, Golang completely, and reinstall, reboot, then make all again its cache off.

**Comment by karalabe** [comment]
@KnoooW I was curious about the go-ethereum commit.

**Comment by KnoooW** [comment]
> @KnoooW I was curious about the go-ethereum commit.

commit dae82f098570e15d44584f0d7f350713f4774727 (HEAD, tag: v1.8.19, origin/release/1.8)
Author: Péter Szilágyi <peterke@gmail.com>
Date:   Wed Nov 28 14:42:37 2018 +0200

    params, swarm: release Geth v1.8.19 and Swarm v0.3.7

**Comment by KnoooW** [comment]
> Did you try:
> go get -d github.com/ethereum/go-ethereum
> go install github.com/ethereum/go-ethereum/cmd/geth
> 
> Otherwise, remove GO, Golang completely, and reinstall, reboot, then make all again its cache off.

I can build the same go-geth branch with go1.9, the problem is go 1.11 can not compile it.

**Comment by karalabe** [comment]
You might want to open an issue upstream for the Go project. I've seen some reports that incorrect Go installations might cause this. Not sure what to make of it really, apparently Go is calling the C compiler with some bad flags. There's not really anything we can do about that.
