### ISSUE TITLE
Geth does not see keystore

### ISSUE THREAD

**Issue by nikitasius** [ethereum/go-ethereum#18247]
#### System information

Geth version: `geth-linux-amd64-1.8.19-dae82f09`
OS & Version: `Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux`

#### Expected behaviour
geth list accounts well

#### Actual behaviour
geth list accounts when:
* run as  `./geth --keystore "/usr/local/eth/wallets" --testnet console --rpc admin,eth,miner,personal,web3`
* type `eth.accounts`

geth **DOES NOT** list accounts when:
* run as  `./geth --testnet console --rpc admin,eth,miner,personal,web3 --keystore "/usr/local/eth/wallets"`
* type `eth.accounts` i have `[]` output and geth points to *default keystore.

#### Steps to reproduce the behaviour
run as  `./geth --testnet console --rpc admin,eth,miner,personal,web3 --keystore "/usr/local/eth/wallets"` and type `eth.accounts`

*it points to default keystore, because when i seen it, i created a new account via `geth.ipc` and i got a new address file in a default keystore.

**Comment by holiman** [comment]
Can you try again but place 'console' last?

**Comment by karalabe** [comment]
`--rpcapi` if you want to specify the namespaces to expose

**Comment by holiman** [comment]
the `--keystore` is a global flag, if you place it _after_ the `console` command it's interepreted as a `local` flag, which causes it to be ignored. As @karalabe pointed out, the proper test would be 

* `./geth --keystore "/usr/local/eth/wallets" --testnet --rpcapi admin,eth,miner,personal,web3 console`
* `./geth --testnet --rpcapi admin,eth,miner,personal,web3 --keystore "/usr/local/eth/wallets" console`

Closing this, please reopen if I misunderstood something and there's some bug I missed
