### ISSUE TITLE
Banner on the console

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#18243]
Print a banner on the console with general information. If `--dev` was specified, add "welcome to power user mode".

**Comment by MartinDawson** [comment]
Can you please provide some more details on what this banner should contain and look like? Thanks!

**Comment by holiman** [comment]
Let's collect some ideas here... 

- If user is in dev-mode, it should print out some info about what this mode even means (e..g all keys are ephemeral). 
- If user is using insecure configurations, it should warn about that
- It might print out some info about where to file tickets

**Comment by lelikalf** [comment]
type

**Comment by lhendre** [comment]
It could also list any important config options that arent already displayed or are defaulted in, the warning for insecure configurations could include details, additionally it could include the licensing information which is the GNU Lesser General Public License v3.0 I believe.

**Comment by nathanio** [comment]
I would personally find this feature very useful, and I would be more than happy to implement it if someone wants to assign me!

**Comment by adamschmideg** [comment]
@nathanio that's good news. Please be aware it's not thoroughly specified, so part of the job is to figure it out :)

**Comment by nathanio** [comment]
Hey, just a quick question. One issue I've noticed is that the console gets filled up so quickly when dev mode is run that it can be difficult to read the banner. Should I make it so that the user has to press a key when they run `--dev` to confirm? The console would just show the banner in the meantime, giving the user a chance to read it.

**Comment by adamschmideg** [comment]
I'm asking around in the team

**Comment by ligi** [comment]
> Should I make it so that the user has to press a key when they run --dev to confirm?

please don't. This can break current setups and if things are headless might cause some WTFs, broken workflows and wasted time. *Maybe* a sleep after the banner - but then we need another flag to disable this.

**Comment by nathanio** [comment]
> > Should I make it so that the user has to press a key when they run --dev to confirm?
> 
> please don't. This can break current setups and if things are headless might cause some WTFs, broken workflows and wasted time. _Maybe_ a sleep after the banner - but then we need another flag to disable this.

Yes, this was my exact concern. And you are completely right about having the option to disable the sleep/prompt. A better option might be having the banners disabled by default, and then the users that need them could manually enable them.

**Comment by solrac97gr** [comment]
Hi, What is the status of this Issue? someone is already working in this?

**Comment by s1na** [comment]
@solrac97gr It's open for taking if someone wants to work on it. I've had it on my backlog for a year and kind of forgot about it

**Comment by solrac97gr** [comment]
forking and starting to work in this) if you have some suggestion for start?
