### ISSUE TITLE
Randomly returns higher balance

### ISSUE THREAD

**Issue by karek314** [ethereum/go-ethereum#1824]
Randomly returns higher balance

**Comment by obscuren** [comment]
can you provide a test case?

**Comment by karek314** [comment]
https://www.dropbox.com/sh/8vjabn67r9rgtly/AACFQfbgRedJDKMvBlsskDJ_a?dl=0

This charts represent data collected from geth node which is mining, collected once per 60s. sometimes you can notice peaks higher than balance.

**Comment by obscuren** [comment]
As I suspected. Mining a block does not necessarily mean it will make it in to the canonical chain.

You're seeing a local snapshot of the chain and it does not necessarily represents the current canonical version of it. At times local forks happen (fast block times).

**Comment by karek314** [comment]
This is weird behavior anyway, i didn't experienced this in older geth versions, also cpp version works fine.
