### ISSUE TITLE
Faucet Offline

### ISSUE THREAD

**Issue by zulhfreelancer** [ethereum/go-ethereum#18257]
### System information

Geth version: 1.8.18-stable
OS & Version: OSX
Commit hash: N/A

### Expected behaviour

Faucet is up and running.

### Actual behaviour

![f](https://user-images.githubusercontent.com/3416976/49663935-387e4e80-fa8b-11e8-8345-bec24d3320c1.jpg)

### Steps to reproduce the behaviour

Starter file:

```
#!/bin/bash

faucet \
    --account.json=./account.json \
    --account.pass=./account.pass \
    --faucet.amount=1 \
    --faucet.minutes=5 \
    --faucet.name=MyFaucet \
    --faucet.tiers=3 \
    --genesis=./genesis.json \
    --network=42 \
    --noauth \
    --bootnodes=enode://xxx@xx.xxx.xx.xx:30304 \
    --loglevel=6
```

Files structure:

```
$ tree .
├── account.json
├── account.pass
├── genesis.json
└── starter.sh
```

### Backtrace

[View logs on PasteBin](https://pastebin.com/raw/aAX9PHRQ)

### Additional notes

1. I started to get this Faucet Offline error in my Puppeth private blockchain network (using Clique PoA). I tried to reproduce this using the official Docker image (`ethereum/client-go:alltools-latest`) and without Docker image using bash command above, they all failed with the same message on front-end.

2. The full node (30304) is running, actively signing blocks and in sync with other nodes. So, I don't think this error was caused by my sealnode. This sealnode is standalone Geth node and it supports light clients.

3. I tried version  1.8.19 too and the problem is still there.

Is this a bug or I just missed something?

**Comment by karalabe** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/18281. The issue was a regression at https://github.com/karalabe/go-ethereum/commit/30cd5c18549f645002aedb4c00e5bab683cb0835#diff-ff207ab75e75547b60446dd050e7e8dbR259.

**Comment by devdattakhoche** [comment]
![image](https://user-images.githubusercontent.com/49261633/144462934-4acbf4e6-1c0b-4f17-aabf-fa334b486a6c.png)

Can we repoen this issue, it doesn't seem to be fixed ?
https://faucet.rinkeby.io/

When I visit this link , it says  `Faucet Offline`.

PS: Am I only the one facing this ?

**Comment by kernerdev** [comment]
> ![image](https://user-images.githubusercontent.com/49261633/144462934-4acbf4e6-1c0b-4f17-aabf-fa334b486a6c.png)
> 
> Can we repoen this issue, it doesn't seem to be fixed ? https://faucet.rinkeby.io/
> 
> When I visit this link , it says `Faucet Offline`.
> 
> PS: Am I only the one facing this ?

I also got the same error.

**Comment by baikeh** [comment]
> > ![image](https://user-images.githubusercontent.com/49261633/144462934-4acbf4e6-1c0b-4f17-aabf-fa334b486a6c.png)
> > Can we repoen this issue, it doesn't seem to be fixed ? https://faucet.rinkeby.io/
> > When I visit this link , it says `Faucet Offline`.
> > PS: Am I only the one facing this ?
> 
> I also got the same error.

Me too

**Comment by duktig-dev** [comment]
# Me too
**Faucet offline**

**Comment by kadetigor** [comment]
I have same issue as well

**Comment by ahrumnoh** [comment]
me, too . the same error

**Comment by duktig-dev** [comment]
I think something wrong with Socket server connection.

**Comment by alirasheedmd** [comment]
I am also facing the same issue.

**Comment by guruprasadv22** [comment]
Same

**Comment by guruprasadv22** [comment]
https://faucet.paradigm.xyz/

**Comment by Agboweroh** [comment]
facing same issue

**Comment by devdattakhoche** [comment]
@karalabe  can we please reopen this, issue, it seems many are facing this ??

**Comment by alimify** [comment]
Facing same issue...

**Comment by ligi** [comment]
You can claim Rinkeby Ether from: https://fauceth.komputing.org/

**Comment by devdattakhoche** [comment]
@ligi  thanks!! Worked!
