### ISSUE TITLE
Bootnode not returning enode URL when run

### ISSUE THREAD

**Issue by moda20** [ethereum/go-ethereum#18252]
#### System information

Geth version: `1.8.19-stable`
OS & Version: OSX HS 10.13.6. Ubuntu 18 LTS 

#### Expected behaviour

Run the boot node and display the enode url

`INFO [02-07|22:44:09] UDP listener up 
self=enode://3ec4fef2d726c2c01f16f0a0030f15dd5a81e274067af2b2157cafbf76aa79fa9c0be52c6664e80cc5b08162ede53279bd70ee10d024fe86613b0b09e1106c40@[::]:30310`

#### Actual behaviour

doesn't display the bootnode enode URL and displays this : `INFO [12-05|11:53:34.678] New local node record  seq=1 id=azeadad ip=<nil> udp=0 tcp =0

`

#### Steps to reproduce the behaviour

`bootnode --genkey boot.key`
`bootnode --nodekey boot.key`

**Comment by Yanzal** [comment]
I have had this problem before, I have found a temporary solution but it should be fixed.
    1) Open the boot.key file with a text editor
    2) Copy the nodekey
    3) then insert 
`bootnode --nodekeyhex <nodekey> -writeaddress`

https://ethereum.stackexchange.com/questions/28970/how-to-produce-enode-from-node-key

**Comment by awantoch** [comment]
For some reason, I'm not getting output by default anymore on geth 1.8.27-stable. Curious as to why the behavior seems to have regressed.

Here's a one-liner version of the above comment for convenience:

`bootnode --nodekeyhex $(cat boot.key) -writeaddress`

Geth
Version: 1.8.27-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.12.4
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.12.4/libexec
