### ISSUE TITLE
statedb.Copy()  fatal error

### ISSUE THREAD

**Issue by bglmmz** [ethereum/go-ethereum#18250]
OS & Version: Linux
go-ethereum Version: 1.8.16 and later

> 	for addr := range self.stateObjectsDirty {
		if _, exist := state.stateObjects[addr]; !exist {
			state.stateObjects[addr] = self.stateObjects[addr].deepCopy(state)
			state.stateObjectsDirty[addr] = struct{}{}
		}
	}

[backtrace]
fatal error: concurrent map iteration and map write

goroutine 78 [running]:
runtime.throw(0x1020394, 0x26)
        /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0000c8e50 sp=0xc0000c8e20 pc=0x441cf2
runtime.mapiternext(0xc0000c91a8)
        /usr/local/go/src/runtime/map.go:790 +0x525 fp=0xc0000c8ed8 sp=0xc0000c8e50 pc=0x424535
zzz-go/core/state.(*StateDB).Copy(0xc0002e9260, 0x0)
        /home/xxx/yyy/zzz-go/build/_workspace/src/zzz-go/core/state/statedb.go:527 +0x506 fp=0xc0000c9278 sp=0xc0000c8ed8 pc=0x896a46

**Comment by fjl** [comment]
Please paste more of the stack trace so we can see where the map iteration is triggered.
