### ISSUE TITLE
Synchronisation failed, dropping peer    peer=c7e7675577416d6b err="action from bad peer ignored"

### ISSUE THREAD

**Issue by spursy** [ethereum/go-ethereum#18265]
**My geth version is:**
```
Geth
Version: 1.8.19-stable
Git Commit: dae82f098570e15d44584f0d7f350713f4774727
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
```
**My system is ubuntu:16.04**

**I am syncing ropsten net point,  Now I have synced at 3391825 blocks.**, But i have the folloed issue:

```
Dec 10 03:07:30 ip-172-16-16-37 geth[14031]: INFO [12-10|03:07:30.232] Loaded most recent local full block      number=0       hash=419410…ca4a2d td=1048576          age=49y7mo
Dec 10 03:07:30 ip-172-16-16-37 geth[14031]: INFO [12-10|03:07:30.232] Loaded most recent local fast block      number=3467716 hash=819f85…668f46 td=8637163251970414 age=5mo3w2
Dec 10 03:07:30 ip-172-16-16-37 geth[14031]: INFO [12-10|03:07:30.233] Loaded local transaction journal         transactions=0 dropped=0
Dec 10 03:07:30 ip-172-16-16-37 geth[14031]: INFO [12-10|03:07:30.233] Regenerated local transaction journal    transactions=0 accounts=0
Dec 10 03:07:30 ip-172-16-16-37 geth[14031]: INFO [12-10|03:07:30.248] New local node record                    seq=5 id=6569c74f7056a4f8 ip=127.0.0.1 udp=30303 tcp=30303
Dec 10 03:07:30 ip-172-16-16-37 geth[14031]: INFO [12-10|03:07:30.250] IPC endpoint opened                      url=/data/.ethereum/geth.ipc
Dec 10 03:07:30 ip-172-16-16-37 geth[14031]: INFO [12-10|03:07:30.251] HTTP endpoint opened                     url=http://127.0.0.1:3001    cors= vhosts=localhost
Dec 10 03:07:30 ip-172-16-16-37 geth[14031]: INFO [12-10|03:07:30.251] Started P2P networking                   self=enode://9b629823f7a451326acbcbcfb80bf0cfd438e65731a15365761
Dec 10 03:10:40 ip-172-16-16-37 geth[14031]: INFO [12-10|03:10:40.251] Block synchronisation started
Dec 10 03:10:56 ip-172-16-16-37 geth[14031]: WARN [12-10|03:10:56.063] Synchronisation failed, dropping peer    peer=c7e7675577416d6b err="action from bad peer ignored"
```

**Comment by lepidotteri** [comment]
yes, this has been very, very frequent recently to the point that geth will just keep logging warnings about ignoring actions from bad peers, at other times it will just hang at: "New local node record" right after starting it up

**Comment by mohammadasimiqball** [comment]
I am facing the same issue. As soon as i run geth, it runs for a few minutes and then crashes and i see similar messages in my log file followed by:
> WARN [02-26|11:10:50.779] Synchronisation failed, dropping peer    peer=c7e7675577416d6b err="action from bad peer ignored"
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x0 pc=0x516295]
> 
> goroutine 1595 [running]:
> math/big.(*Int).Cmp(0xc056bb7860, 0x0, 0x522ae9f829763683)
> 	C:/go/src/math/big/int.go:319 +0x35
> github.com/ethereum/go-ethereum/core.(*BlockChain).insertSidechain(0xc0117e8000, 0xc0730816e0, 0xc00006f4e0, 0xc00006f401, 0x1, 0x1, 0xc069992308, 0x1, 0x1, 0xc06ec821e0, ...)
> 	C:/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1333 +0x10b9
> github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc0117e8000, 0xc04a782420, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> 	C:/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1139 +0x2e1c
> github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc0117e8000, 0xc04a782420, 0x1, 0x1, 0x0, 0x0, 0x0)
> 	C:/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1088 +0xb90
> github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc0806e1ba0, 0xc04a782418, 0x1, 0x1, 0x1, 0x1163400)
> 	C:/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1490 +0x415
> github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc0806e1ba0, 0x0, 0xc0773bff98)
> 	C:/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1464 +0x80
> github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent-fm(0x8, 0x13c4fb0)
> 	C:/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:479 +0x31
> github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc0806e1ba0, 0xc02c8ba900, 0xc04dc5f150)
> 	C:/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0x60
> created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
> 	C:/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0xb6

**Comment by krtschmr** [comment]
tried installing ETH Node today

started with `geth.exe --testnet` 

getting 

    peer=c7e7675577416d6b err="action from bad peer ignored"

i think, no Ethereum for me

**Comment by tsujp** [comment]
I'm also getting this error with `geth --testnet`

```
WARN [08-21|07:26:00.282] Synchronisation failed, dropping peer    peer=c7e7675577416d6b err="action from bad peer ignored"
```

**Comment by osiztechnologies** [comment]
I'm also getting this error from Geth-1.9.5 version package.

Synchronisation failed, dropping peer    peer=c7e7675577416d6b err="action from bad peer ignored"

Kindly give solution for this issue

**Comment by OliveIT** [comment]
Same here!
`Synchronisation failed, dropping peer    peer=c7e7675577416d6b err="action from bad peer ignored"`

**Comment by holiman** [comment]
It's not easy to sync ropsten -- it's an ancient testnet with not a lot of nodes on it -- it's heavily unreliable. The errorr message simply tells you why we dropped the peer, and could e.g. happen if the peer disconnected as we were trying to send it a request. Closing this as it's not really an actionable item or indicative of a fault in geth.

**Comment by lixiaodong** [comment]
Is there have a stable testnet on ETH ?
