### ISSUE TITLE
Low efficiency with multiple workers 

### ISSUE THREAD

**Issue by karek314** [ethereum/go-ethereum#1826]
While running pool i need to lower getwork target for smaller hashrate, due that POW verification is slow. With 150 workers it starts getting slower, and it creates more stale shares.

I0920 22:16:07.186713   26582 worker.go:282] Invalid header on mined block: Block's nonce is invalid (= f460f5dea5bd35df)
I0920 22:16:07.335001   26582 worker.go:282] Invalid header on mined block: Block's nonce is invalid (= c652bafc93e22129)
etc...

Would be great to allow all threads process verification allocated dynamically. I have done this in python, and works much more efficient than here. But it's obvious that while running pool i need firstly point shares to geth and later check if getwork target has not been modified.

**Comment by obscuren** [comment]
You are assuming that more workers is faster. This assumption is false. Limit the amount of workers to your CPU and you should be good (it does this for you by default). 

This is not an issue.

**Comment by karek314** [comment]
I didnt check geth code, but i believe there must be something to improve, i have noticed that it works much faster with cpp ethereum, but unfortunately cpp version has other more serious bugs.
