### ISSUE TITLE
Transaction pool DoS attack

### ISSUE THREAD

**Issue by hadg** [ethereum/go-ethereum#18288]
#### System information

Geth version: `1.8.19-stable`
OS & Version: OSX

#### Expected behaviour
Nodes should not accept transactions with low GAS prices by default.

#### Actual behaviour
The node can accept any number of transactions with a gas price of 0 through RPC.

#### Steps to reproduce the behaviour
1. Create nodes with

````
{
    "config": {
        "chainId": 15,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "difficulty": "2000",
    "gasLimit": "2100000",
    "alloc": {
        "7df9a875a174b3bc565e6424a0050ebc1b2d1d82": { "balance": "300000" },
        "b0d74e9f9Ba20eEa9429649563bc745261e02De7": { "balance": "400000000" }
    }
}
````
2. Boot node

````
geth --datadir ./data --networkid 15 --rpc --verity 6 --nodiscover console
````

3. Send a lot of transaction with a gas price of 0 to the node RPC through a script
````
const Web3 = require('web3');
const Tx = require('ethereumjs-tx');
const web3 = new Web3(new Web3.providers.HttpProvider('http://127.0.0.1:8545'));

const GAS_PRICE = 1;
const GAS_LIMIT = 2100000;
let myAddress = '0xb0d74e9f9Ba20eEa9429649563bc745261e02De7';
let toAddress = '0xb346442ebd889F0639eea0ADC5e031c40da32A22';
web3.eth.getBalance(myAddress).then(d=>{
    console.log(web3.utils.fromWei(d));
})
let test = async function() {
    let count = await web3.eth.getTransactionCount(myAddress);
    let batch = new web3.BatchRequest();
    for(let i = count; i < count + 1; i++){
        let rawTransaction = {
            "from": myAddress,
            "nonce": "0x" + i.toString(16),
            "gasPrice": web3.utils.toHex(GAS_PRICE),
            "gasLimit": web3.utils.toHex(GAS_LIMIT),
            "to": toAddress,
            "value": "0x0",
            "data": "0x0",
            "chainId": 15
        };
        let privKey = new Buffer('private key', 'hex');
        let tx = new Tx(rawTransaction);
        tx.sign(privKey);
        let serializedTx = tx.serialize();
        console.log(`Attempting to send signed tx:  ${serializedTx.toString('hex')}`);
        batch.add(web3.eth.sendSignedTransaction.request('0x' + serializedTx.toString('hex'),(err,data)=>{
            if(err){
                console.log(err)
            }else{
                console.log('success')
            }
        }))
    }
    batch.execute();
}
test();
````
#### Backtrace

I added 11,000 transactions through the script. During the process of adding, the geth process consumes a lot of cpu resources, and when I restart the node, the geth needs to spend a lot of time to reload the transactions in the transaction pool from the hard disk.

![image](https://user-images.githubusercontent.com/4592450/49845189-a8c8ff00-fe00-11e8-84ef-3df5f490f134.png)
![image](https://user-images.githubusercontent.com/4592450/49845232-d9109d80-fe00-11e8-8717-4b39af519b5d.png)

**Comment by holiman** [comment]
It considers txs added through rpc to be 'locals', that you (node operator) want to treat without the normal caps and rules.

Use '--nolocals' to disable special treatment of locals. 

As it is,. works as designed
