### ISSUE TITLE
Transactions pool halts network

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#18280]
Im running a lot of load tests on a private eth network running clique PoS. I'm trying to find the happy medium where I can push through very high volume of transactions. Network setup consists of 2 local nodes, 6 remote nodes (1 gateway, 5 signers) and 3 second block time.

Currently doing 500 txn from 2 nodes, from 2 accounts every 2 seconds locally on my PC to my cloud network of 6 servers (1 Gateway, 5 signers) ends up with a bottle neck of transactions ~2000 which the nodes try desperately  to process but it just keeps mounting on them.

an alternative test was running 500 unique accounts, each doing 1 txn and running this every 2-3 seconds which sees a lot of missed nonce errors. I have extended the txpool setting using the following flags but im wondering is there anything else I can do to improve the throughput including editing geths source code, mainly just wondering if you guys could tell me something i havent already spotted either as a flag or in the go source which might be able to help me out:

```geth --datadir=/datadir --syncmode 'full' --cache=2048 --targetgaslimit "20000000" --gasprice "1000000000" --txpool.globalslots 65536 --txpool.accountqueue 1024 --txpool.globalqueue 16384--verbosity 3 --pprof --pprofport 6060 console```

**Comment by MariusVanDerWijden** [comment]
Yep that has something to do with the way we handle local transaction in the transaction pool. 
We made a feature request which might be worked on in the future. 
See https://github.com/ethereum/go-ethereum/issues/21174
We also recently added some improvements which speed up the process a bit, see https://github.com/ethereum/go-ethereum/pull/21232
