### ISSUE TITLE
Contract deployment results in 0x

### ISSUE THREAD

**Issue by miladmostavi** [ethereum/go-ethereum#1829]
I think I've found a bug (struggled a lot with it before I figured what was causing my deploy scripts to suddenly fail). The solc --combined-json produces a different hex than solc --bin. The latest release version geth (Version: 1.1.3) fails to create the contract if the combined-json version is used in sendTransaction data.

**Comment by obscuren** [comment]
Could you provide some additional information. Could you create an example for us test?

**Comment by miladmostavi** [comment]
It seems this is more of a solc problem:

https://github.com/ethereum/solidity/commit/09f1f1e5955fc358697b49542c6c8eb42496ef10#diff-9f5c1afb3e488e90c0c39502afee1e3cL567
