### ISSUE TITLE
Constant v1.8.20 fails to build on Debian Stretch

### ISSUE THREAD

**Issue by jmcph4** [ethereum/go-ethereum#18316]
The [official build instructions](https://geth.ethereum.org/install/#building-without-a-go-workflow) fail when using both `make geth` and `make all`.

#### System information

Geth version: Constant v1.8.20
OS & Version: Debian 9 "Stretch"

    $ uname --all
    Linux devlaptop 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

    $ go version
    go version go1.7.4 linux/amd64

#### Expected behaviour
From the [official build instructions](https://geth.ethereum.org/install/#building-without-a-go-workflow):
> This will create a `geth` (or `geth.exe` on Windows) executable file in the `go-ethereum/build/bin` folder that you can move wherever you want to run from. The binary is standalone and doesn't require any additional files.

#### Actual behaviour
    build/env.sh go run build/ci.go install
    # github.com/ethereum/go-ethereum/vendor/github.com/Azure/azure-pipeline-go/pipeline
    vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:49: r.GetBody undefined (type Request has no field or method GetBody)
    vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:58: undefined: http.NoBody
    vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:59: r.GetBody undefined (type Request has no field or method GetBody)
    vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:60: undefined: http.NoBody
    vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:95: undefined: http.NoBody
    vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:107: undefined: http.NoBody
    Makefile:25: recipe for target 'all' failed
    make: *** [all] Error 2

#### Steps to reproduce the behaviour
    $ git clone https://github.com/ethereum/go-ethereum.git
    $ cd go-ethereum
    go-ethereum$ git reset --hard v1.8.20
    go-ethereum$ make all

**Comment by nonsense** [comment]
@jmcph4 looks like you are running a very old unsupported version of Go. Please update to the latest Go 1.11.4 (only Go 1.10 and Go 1.11 are supported versions of the language). Our test suite is checking both of these.

I have also updated the installation instructions.

**Comment by subhasisbanik** [comment]
As per the documentation here,
https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu

it is mentioned to use Go 1.7
https://github.com/ethereum/go-ethereum/wiki/Installing-Go#ubuntu-1404

**Comment by nonsense** [comment]
@subhasisbanik documentation has been updated. As a general rule-of-thumb always use an up-to-date version of Go, and check the actual versions used in the CI test suite in Travis at https://travis-ci.org/ethereum/go-ethereum

PPA currently is broken, I believe we have a thread opened with them to fix it. @fjl knows more about this, but expect it to work soon.

**Comment by nonsense** [comment]
Closing this as documentation has been updated and it is clear why the build process didn't work with outdated version of Go. Feel free to re-open if you still have problems.
