### ISSUE TITLE
Feature Request: API call for replaying a Tx and returning vmtrace data

### ISSUE THREAD

**Issue by mtbitcoin** [ethereum/go-ethereum#1832]
As per gitter chat.. Introduce 2 new API calls (eth_debugSendTransaction and eth_debugCall)  for replaying a TX and returning the associated vmtrace data). Both applying on some transient or other temporary state

**Comment by obscuren** [comment]
While I do not directly oppose to the feature request, why not try mix or eth js' VM?

**Comment by mtbitcoin** [comment]
closing this issue as it is addressed in https://github.com/ethereum/go-ethereum/pull/2156
