### ISSUE TITLE
Mining with 0 mining threads

### ISSUE THREAD

**Issue by toffick** [ethereum/go-ethereum#18328]
Hi. I create my own mining pool with geth. For getting of work i use RPC method getWork. Before getting work i start miner with `miner.start(0)`, first geth generates DAG files and after i can take a new work. But Geth miner in this working threads configuration about once every 2 seconds writes in console `Commit new mining work` and `getWork` received to me new work asset(new POW-hash), but it useless for me, cause it receives me new mining work that overwriting the already valid work for current block round.

How can i stop generating a new mining job for current block round?

**Comment by JKKGBE** [comment]
Have you figured out what this is for or how to stop it?
