### ISSUE TITLE
Ethereum port on Private network is not responding or listening

### ISSUE THREAD

**Issue by Jagdish0886** [ethereum/go-ethereum#18339]
Hello,
I have installed go-ethereum, go lang on AWS EC2 instance.
Private network is created, I have crated 4 personal accounts.
On mining new block, 2 blocks are added to the blockchain, and some balance to my first account.
However, while trying to connect to the Ethereum network from MetaMask, it keeps clocking/loading.

From the MetaMask logs, I found the port on Ethereum network is not responding.
On further troubleshooting, even the CURL command for this server and port http://server-name:30303 gives error as:

_curl: (52) Empty reply from server_

However, CURL works well with other websites like google. I have verified firewall and confirmed ports are listening on the server, and I am able to telnet from outside the network over the port 30303. It means there is some misconfiguration or issue while doing go-ethereum setup, can you please guide me how to overcome this. What I am missing here, what I need to do to fix this.

Regards,
Jagdish

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
