### ISSUE TITLE
client.SendTransaction(context.Background(), signedTx) doesn't work when broadcasting to the mainnet on infura?

### ISSUE THREAD

**Issue by woshidama323** [ethereum/go-ethereum#18332]
Hi experts , i have a question when using err = client.SendTransaction(context.Background(), signedTx)
I mean, I have created the signed transaction successfully 
it seems that this method dosen’t work now when broadcasting a transaction to the main net since i can’t find the transaction info by using its hash on etherscan.io
I have tried for many times ,but still get nothing
so, do you know any clue about this problem ? thanks.
I have asked the infura team for this question ,seems it is not caused by infura

OS & Version: Linux

#### Expected behaviour
The transaction should be showed on the mainnet 

#### Actual behaviour
Cannot find anything on mainnet

#### Steps to reproduce the behaviour
"github.com/ethereum/go-ethereum/ethclient"
client.SendTransaction(context.Background(), signedTx)

Actually, It works on ropsten net .but failed on mainnet. no any errors out during executing

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by woshidama323** [comment]
OK, I understand, thanks for your reply. could you help to tell where i can find any active chat group for such problem like telegram or gitter channel? thanks
