### ISSUE TITLE
Why does the enode nodeId information not support the domain name?

### ISSUE THREAD

**Issue by zjsunzone** [ethereum/go-ethereum#18340]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by FrankSzendzielarz** [comment]
The main reason is privacy.
Other reasons might include DNS attack vectors.
https://ethereum.stackexchange.com/questions/37445/is-it-possible-to-use-domain-names-in-place-of-ip-addresses-for-peer-nodes-stat

**Comment by easeev** [comment]
Guys @karalabe @FrankSzendzielarz @fjl,

1. Could you please elaborate on how IP is more private than a domain name? Both are just plaintext identifiers.
2. Is it really that hard to add hostname resolution to IP similar to what [Parity does](https://github.com/paritytech/parity-ethereum/blob/master/parity/helpers.rs#L185)? Will be very helpful to operate Geth nodes in modern environments (e.g. cloud).

**Comment by karalabe** [comment]
1. It's not more private. It's more secure, because taking over an IP is a
lot harder than a domain. That said, as long as the public key is
mandatory, I don't see too big of a danger.

2. No, it's 1 line of code.

**Comment by easeev** [comment]
Thanks @karalabe!

Could you review and merge https://github.com/ethereum/go-ethereum/pull/18524 then?
