### ISSUE TITLE
LESv2 (Get)TxStatus not exposed in public Go API

### ISSUE THREAD

**Issue by GlenDC** [ethereum/go-ethereum#18366]
While using the Go LESv2 API, using the [*LesAPIBackend](https://godoc.org/github.com/ethereum/go-ethereum/les#LesApiBackend), I noticed that the function to get the Transaction status, `GetTxStatus->TxStatus` (as described in https://github.com/zsfelfoldi/go-ethereum/wiki/Light-Ethereum-Subprotocol-%28LES%29#transaction-relaying-and-status-retrieval), does not seem to be exposed in that Backend. This is weird, and I wonder why. Is this is intended or it just a matter of priorities and do you require some help with this? [Getting a Block (LESv1)](https://godoc.org/github.com/ethereum/go-ethereum/les#LesApiBackend.GetBlock) is exposed in that API backend for example.

The only place where I found support for the `GetTxStatusMsg` and `TxStatusMsg` is in low level protocol definitions, as well as in the handler/peer code. So seems that it should be easy enough to extend the support as to also include an easy to call method, similar to the `GetBlock` functionality.

Is calling this method already supported and easy, but do I look for it in the wrong place? Is it not supported for a good reason? Or is it just one of those things that nobody got around in doing so? Would love to help with this, as I do really would like to use that functionality.

#### System information

Geth version: N/A
OS & Version: N/A
Commit hash : de4265fa028f2b0eb96a21e295028e0d19426adb

**Comment by fjl** [comment]
The transaction status is exposed through GetTransaction on the API backend.
