### ISSUE TITLE
eth.getBlockNumber how can i use it

### ISSUE THREAD

**Issue by jiyilanzhou** [ethereum/go-ethereum#18368]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version:  Linux
Commit hash : (if `develop`)

#### Expected behaviour
```
{
  difficulty: 17171480576,
  extraData: "0x476574682f76312e302e302f6c696e75782f676f312e342e32",
  gasLimit: 5000,
  gasUsed: 0,
  hash: "0x88e96d4537bea4d9c05d12549907b32561d3bf31f45aae734cdc119f13406cb6",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x05a56e2d52c817161883f50c441c3228cfe54d9f",
  mixHash: "0x969b900de27b6ac6a67742365dd65f55a0526c41fd18e1b16f1a1215c2e66f59",
  nonce: "0x539bd4979fef1ec4",
  number: 1,
  parentHash: "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 537,
  stateRoot: "0xd67e4d450343046425ae4271474353857ab860dbc0a1dde64b41b5cd3a532bf3",
  timestamp: 1438269988,
  totalDifficulty: 34351349760,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
 ```
#### Actual behaviour
```
eth.getBlockNumber("1")
undefined
eth.getBlockNumber("0x1")
undefined
eth.getBlockNumber
function
```
#### Steps to reproduce the behaviour

enter console,use eth.getBlockNumber api

#### Backtrace

````
[backtrace]
````

**Comment by hadv** [comment]
you can use `eth.getBlock(1)` or `getBlock("latest")`

**Comment by jiyilanzhou** [comment]
Since this method cannot be used, what is the significance of his existence

**Comment by hadv** [comment]
you need to use as callback function like below

```
eth.getBlockNumber(function(err, num) { if (err === null) {console.log(num)}})
```

**Comment by jiyilanzhou** [comment]
It  probably is web3 for nodejs, i really can't figure out how to use this method on the console

**Comment by smalaichami** [comment]
eth.getBlockNumber is not a function in web3 but you can try this in (1)geth attach or (2)geth console 

> eth.getBlock("latest").number
 
https://github.com/ethereum/web3.js/blob/develop/dist/web3.js

**Comment by hadv** [comment]
> It probably is web3 for nodejs, i really can't figure out how to use this method on the console

I can run it on the geth console. FYI

**Comment by wangjunbao2018** [comment]
It seems there are two ways to archive this purpose:

1.  eth.getBlockNumber

```
eth.getBlockNumber(function(err, num){ console.log(num)})
```

2. eth.getBlock

```
eth.getBlock("pending").number   or   eth.getBlock("latest").number
```

**Comment by karalabe** [comment]
According to the [JSON RPC spec](https://github.com/ethereum/wiki/wiki/JSON-RPC), the function is called `eth.blockNumber`, not `eth.getBlockNumber`.

**Comment by jiyilanzhou** [comment]
> According to the [JSON RPC spec](https://github.com/ethereum/wiki/wiki/JSON-RPC), the function is called `eth.blockNumber`, not `eth.getBlockNumber`.

![20190103162804](https://user-images.githubusercontent.com/16730964/50629094-243c4d00-0f76-11e9-94ff-1170a4fad835.png)

The generation of this function  because of this getter property,when i remove getter,
i can't find it in console. which may  cause problems?

**Comment by holiman** [comment]
>  he want to ask why eth.getBlockNumber is still existed

It's some callbacky way of getting the block number
```
> eth.getBlockNumber( console.log )
null 0
```
