### ISSUE TITLE
Fatal: Failed to start the JavaScript console: api modules: context deadline exceeded

### ISSUE THREAD

**Issue by imrandurani** [ethereum/go-ethereum#18361]
Hi there,

I am trying to attach a console to a running geth on local machine but each time it says "context deadline exceeded".

#### I have tried all these but same error:

*geth attach /path/to/ipc/geth.ipc*

*geth attch http://localhost:8545*

*geth attach http://127.0.0.1/8545*

#### The rpc parameters that I tried to execute geth are:

* --rpc --rpcaddr "localhost" --rpcport "8545" --rpccorsdomain "*"

* --rpc --rpcaddr "127.0.0.1" --rpcport "8545" --rpccorsdomain "*"

* --rpc --rpcaddr "0.0.0.0" --rpcport "8545" --rpccorsdomain "*"

Any prompt help would be appreciated.

Thanks

#### System information

Geth version: `geth version 1.8.20`
OS & Version: Linux , Ubuntu 16.04 LTS

#### Expected behaviour

Should attach the additional console to the ipc.

#### Actual behaviour

Fatal: Failed to start the JavaScript console: api modules: context deadline exceeded

**Comment by chenwei767** [comment]
sudo geth attch http://localhost:8545  should work

**Comment by ErikParso** [comment]
Where was a problém ?

**Comment by charuraj88** [comment]
Fatal: Failed to start the JavaScript console: api modules: context deadline exceeded

**Comment by charuraj88** [comment]
i got error please help me i am not able to connect geth attach

**Comment by BourneNeo** [comment]
same error here, why this issue closed?
