### ISSUE TITLE
unable to connect a server using rpc call in geth

### ISSUE THREAD

**Issue by BharathKumarTalupula** [ethereum/go-ethereum#18375]
Hi there,

I'm trying to connect a myprivatenetwork which was running on server using rpc call in geth and retrive the data of my myprivatenetwork and i used the below calls but it was not working and 
 
command - $ geth --datadir "/desktop/gethServer/" --networkid 1234 --datadir "/desktop/gethServer/" --rpc --rpcport "8549" --rpcaddr "myserveripaddr" --rpccorsdomain "foldername:password@myserveripaddr"

Error : Error starting protocol stack: listen tcp 183.82.104.246:8549: bind: The requested address is not valid in its context.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

![rpc-error](https://user-images.githubusercontent.com/43064317/50556270-e385cf00-0cfc-11e9-8277-2fedaac8320e.JPG)

**Comment by karalabe** [comment]
Doing a quick Google search reveals that the error means you're trying to listen on an IP address that your machine does not have.

When you configure your listener, it's not a remote IP you have to specify, rather it is the local interface / endpoint that should accept the connections. It will accept any connection from any remote address that uses that network interface (i.e. physical or virtual card). Please make sure you don't allow all the internet in, it results in nasty attacks.
