### ISSUE TITLE
make other platform binaries available in the releases

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#1837]
Currently we supply packages for Ubuntu, OSX and Windows, and also direct binaries for Windows and Linux ARM. We should add imho binaries for all platform we support. It doesn't really cost us anything, but it could sort out issues for people not able to access the packages directly. Most importantly we should ad linux-amd64.

**Comment by tgerring** [comment]
Currently, we don't produce a geth binary for OS X, it's only available in brew. The Mac develop build link in the README points to the old QT-based Mist and needs to be fixed when the binaries are available separately. This is also requested by Mist team

**Comment by fjl** [comment]
Done
