### ISSUE TITLE
local txpool pending txs not broadcast to remote nodes

### ISSUE THREAD

**Issue by scorpio1858** [ethereum/go-ethereum#18382]
i am on a private testnet and run four mining nodes, while local txpool has lots of pending txs, these txs are not broadcast to other nodes, anyone know the reason? thanks

#### System information

Geth version: 1.8.15
OS & Version: Linux

#### Expected behaviour

after transactions are sent, they should be broadcasted to other nodes in the network

#### Actual behaviour

most transactions are never broadcasted to the network, by checking txpool.status i can see local txpool has 5919 pending txs and 0 queued txs, while remote node has 0 pending txs and 72 queued txs

#### Steps to reproduce the behaviour

1. calling eth_sendtransaction at a rate of 500 per sec to the local node
2. check txpool.status on each node

**Comment by holiman** [comment]
Sorry, this is a bit stale now. Since `1.8.15`, a lot has happened. Please reopen if this persists.
