### ISSUE TITLE
Panic issue when the options related with light node are on. (panic: runtime error: index out of range)

### ISSUE THREAD

**Issue by vitkoo09** [ethereum/go-ethereum#18385]
**Geth version: v1.8.20
OS & Version: Linux - CentOS 7**

#### Expected behaviour
**Geth daemon should be operated stably with peer related options.**

#### Actual behaviour
**While the geth daemon is syncing as full node, suddenly it is shut down with below error messages.**

panic: runtime error: index out of range

goroutine 7381 [running]:
github.com/ethereum/go-ethereum/common/prque.(*sstack).Swap(0xc00e340280, 0x0, 0xffffffffffffffff)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/common/prque/sstack.go:95 +0x1ef
container/heap.Pop(0x11f1340, 0xc00e340280, 0x6e9801, 0xc02365f930)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/container/heap/heap.go:64 +0x64
github.com/ethereum/go-ethereum/common/prque.(*Prque).PopItem(0xc00e2f4040, 0xc00e2ec420, 0xc053872cb0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/common/prque/prque.go:33 +0x3a
github.com/ethereum/go-ethereum/les.(*freeClientPool).connect(0xc00e2fe310, 0xc053872cb0, 0xd, 0xc033088120, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/les/freeclient.go:115 +0x32f
github.com/ethereum/go-ethereum/les.(*ProtocolManager).handle(0xc00b72e620, 0xc06a5e6210, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/les/handler.go:269 +0xa3b
github.com/ethereum/go-ethereum/les.(*ProtocolManager).runPeer(0xc00b72e620, 0x2, 0xc06a14e8a0, 0x11e7f80, 0xc056bc0a20, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/les/handler.go:223 +0x223
github.com/ethereum/go-ethereum/les.(*lesCommons).makeProtocols.func1(0xc06a14e8a0, 0x11e7f80, 0xc056bc0a20, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/les/commons.go:64 +0x55
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc056bc0a20, 0xc06a14e8a0, 0x11e7f80, 0xc056bc0a20)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/peer.go:361 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/peer.go:360 +0x1fb

#### Steps to reproduce the behaviour
Start geth with below options.
/home/eth/geth-v1.8.20/geth --maxpeers 110 --lightserv 70 --lightpeers 0

After then, with in a day, (sometimes with in 5 minutes) the geth daemon is shut down.
The propose of '--lightpeers 0' is that I don't want to attach unknown light node to my full node.
So, I set --lightpeers as 0, and I added my light node information at ~/.ethereum/geth/trusted-nodes.json.
This issue was generated regardless of the existence of 'trusted-nodes.json' file.
The geth daemon was operated well with those options using geth-**v1.8.11**.
However, this issue was came up on both of v1.8.19 and v1.8.20.
I didn't check at the versions from v1.8.12 to v1.8.18.

If I add '--nodiscover' option and add peers using 'admin.addPeer', then the geth daemon is not dead.

Please check this issue as soon as possible.
I should apply v1.8.20 before Constantinople hard fork.

**Comment by holiman** [comment]
@zsfelfoldi any progress on this?

**Comment by holiman** [comment]
@zsfelfoldi please close if fixed

**Comment by zsfelfoldi** [comment]
Fixed
