### ISSUE TITLE
Error - Incorrect HMAC (Need equivalent decryption implementation in javascript)

### ISSUE THREAD

**Issue by manish1635** [ethereum/go-ethereum#18381]
Hi - is there any equivalent implementation in javascript?

My requirement is to encrypt a message by using go language and decrypt this on node js/javascript side.
For the moment, I am using “go-ethereum/crypto/ecies/ecies.go” for encryption and a node package “ecies-parity” for decryption but getting error “Incorrect MAC”.

Encryption : (Go)

var privateKey ="54422e4b3278da00c4cc14b31cbbd1a8e047927735be2d1752ac134b7d9a2fef"
prk1, err := HexToECDSA(privateKey)
if err != nil {
	fmt.Println(err)
	os.Exit(1)
}
var pk2 *ecdsa.PublicKey
pk2 = prk1.Public().(*ecdsa.PublicKey)
ct, err := ecies.Encrypt(rand.Reader, ecies.ImportECDSAPublic(pk2), []byte("hello"), nil, nil)
if err != nil {
	return shim.Error(fmt.Sprintf("Unable to parse certificate %s", err))
}
fmt.Println(ct)
Getting output as byte array:
[4 193 121 113 131 2 85 24 76 223 71 147 19 57 191 250 232 218 155 44 177 23 95 111 64 33 251 231 179 36 226 30 178 131 66 160 71 2 113 6 114 136 106 65 193 85 146 223 207 83 170 111 244 129 67 121 19 163 175 8 197 123 192 2 60 80 48 28 241 11 128 12 164 51 112 193 246 18 103 220 72 137 225 175 78 112 241 174 254 89 226 40 234 137 236 217 250 123 199 67 95 36 117 171 124 113 50 240 108 30 168 84 129 173 39 49 130 164]

For Decryption: (Node.js)
const ecies = require("ecies-parity");
var EC = require('elliptic').ec;
var goBytes="4 193 121 113 131 2 85 24 76 223 71 147 19 57 191 250 232 218 155 44 177 23 95 111 64 33 251 231 179 36 226 30 178 131 66 160 71 2 113 6 114 136 106 65 193 85 146 223 207 83 170 111 244 129 67 121 19 163 175 8 197 123 192 2 60 80 48 28 241 11 128 12 164 51 112 193 246 18 103 220 72 137 225 175 78 112 241 174 254 89 226 40 234 137 236 217 250 123 199 67 95 36 117 171 124 113 50 240 108 30 168 84 129 173 39 49 130 164";
var bytes =[];
var forLoop=goBytes.split(" ")
for (var i = 0; i < forLoop.length; ++i)
{
bytes.push(forLoop[i]);
}
var privateKeyA = Buffer.from("54422e4b3278da00c4cc14b31cbbd1a8e047927735be2d1752ac134b7d9a2fef","hex");
var ec = new EC('secp256k1');
var pk = ec.keyFromPrivate(privateKeyA, 'hex');
ecies.decrypt(pk.getPrivate().toBuffer(), Buffer.from(bytes)).then(function(plaintext) {
console.log("Message to part A:", plaintext.toString());
});

**Comment by manish1635** [comment]
Hi - is there any equivalent implementation in javascript?

My requirement is to encrypt a message by using go language and decrypt this on node js/javascript side. 
For the moment, I am using “go-ethereum/crypto/ecies/ecies.go” for encryption and a node package “ecies-parity” for decryption but getting error “Incorrect MAC”. 

Encryption : (Go)

	var privateKey ="54422e4b3278da00c4cc14b31cbbd1a8e047927735be2d1752ac134b7d9a2fef"
	prk1, err := HexToECDSA(privateKey)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	var pk2 *ecdsa.PublicKey
	pk2 = prk1.Public().(*ecdsa.PublicKey)
	ct, err := ecies.Encrypt(rand.Reader, ecies.ImportECDSAPublic(pk2), []byte("hello"), nil, nil)
	if err != nil {
		return shim.Error(fmt.Sprintf("Unable to parse certificate %s", err))
	}
	fmt.Println(ct)


Getting output as byte array:
[4 193 121 113 131 2 85 24 76 223 71 147 19 57 191 250 232 218 155 44 177 23 95 111 64 33 251 231 179 36 226 30 178 131 66 160 71 2 113 6 114 136 106 65 193 85 146 223 207 83 170 111 244 129 67 121 19 163 175 8 197 123 192 2 60 80 48 28 241 11 128 12 164 51 112 193 246 18 103 220 72 137 225 175 78 112 241 174 254 89 226 40 234 137 236 217 250 123 199 67 95 36 117 171 124 113 50 240 108 30 168 84 129 173 39 49 130 164]

For Decryption: (Node.js)
const ecies = require("ecies-parity");
var EC = require('elliptic').ec;
var goBytes="4 193 121 113 131 2 85 24 76 223 71 147 19 57 191 250 232 218 155 44 177 23 95 111 64 33 251 231 179 36 226 30 178 131 66 160 71 2 113 6 114 136 106 65 193 85 146 223 207 83 170 111 244 129 67 121 19 163 175 8 197 123 192 2 60 80 48 28 241 11 128 12 164 51 112 193 246 18 103 220 72 137 225 175 78 112 241 174 254 89 226 40 234 137 236 217 250 123 199 67 95 36 117 171 124 113 50 240 108 30 168 84 129 173 39 49 130 164";
  var bytes =[];
  var forLoop=goBytes.split(" ")
  for (var i = 0; i < forLoop.length; ++i)
{
bytes.push(forLoop[i]);
}
var privateKeyA = Buffer.from("54422e4b3278da00c4cc14b31cbbd1a8e047927735be2d1752ac134b7d9a2fef","hex");
var ec = new EC('secp256k1');
var pk = ec.keyFromPrivate(privateKeyA, 'hex');
ecies.decrypt(pk.getPrivate().toBuffer(), Buffer.from(bytes)).then(function(plaintext) {
  console.log("Message to part A:", plaintext.toString());
});

**Comment by lmars** [comment]
`ecies-parity` uses shared MAC data of two zero bytes [here](https://github.com/sigp/ecies-parity/blob/master/index.js#L33) (which is [the same as parity-crypto](https://github.com/paritytech/parity-common/blob/master/parity-crypto/src/lib.rs#L42)), so to produce an equivalent MAC using `crypto/ecies` you also need to use the same shared data (i.e. the last argument to `ecies.Encrypt`).

See an example here:

https://gist.github.com/lmars/f92c3fdad2620903388656e8726602fd

**Comment by manish1635** [comment]
It worked perfectly!!! 

Yes, I was missing shared MAC data of two zero bytes. Thank you very much Lewis for your help. 

Now, I can use this library to implement data privacy in chaincode. It looks possible by using this library that data can be encrypted in chaincode with the public key and decrypted on the client side. 
However, I still have a doubt regarding the uses of random numbers. I read somewhere to avoid using the generation of random numbers in chaincode (Hyperledger Fabric). And, libraries are using “crypto/rand” or “math/rand” to achieve cryptography. Do you have any idea about this?

**Comment by lmars** [comment]
It looks like the encoded key pair is `secp256r1`, not `secp256k1`? How did you generate them?

Also, given this is not an issue with go-ethereum code, it's probably worth closing this and asking for help on http://ethereum.stackexchange.com.

**Comment by manish1635** [comment]
Yes, every key pair shared by me here is secp256r1 and generated by Hyperledger Fabric CA during user registration. For your information, if I do decryption on the go-lang side it works well with same private key(PEM formatted)? Is go-ethereum library most suited for secp256k1? 
if you want, I have no issue to close this issue. Please suggest.

**Comment by manish1635** [comment]
Yes, I have to find another JavaScript library/solution for decryption in which key is using secp256r1 curve.  Any information about such javascript library will be highly appreciable.

I am very much clear now. Therefore, we can close this issue.
Thanks again for your great and quick support Lewis. 👍
