### ISSUE TITLE
Can't get the correct balance of a token after I restart geth node within docker

### ISSUE THREAD

**Issue by wangjunbao2018** [ethereum/go-ethereum#18383]
Hi there,

I use docker to build a private network, and then I  issue a token and I can get the balance correctly.  however,  after I stop it then restart the geth node, I can't get the right balance of the token I issued before.  but if I build the private network without docker, it works well.  What's the problem?  anyone know the reason? really thanks.

#### System information

Go version: go1.11.4
Geth version: 1.9.0-unstable
OS & Version: Windows/Linux/OSX
Docker version : 18.06.0-ce
Docker-compose version:  1.22.0   

#### Expected behaviour

After I restart the node by docker(run docker stop node &  docker start node), the balance should be equals that before I do like this. 
#### Actual behaviour

Actually, I got  `{"jsonrpc":"2.0","id":0,"result":"0x"}` .

#### Steps to reproduce the behaviour

1. use docker-compose to build a private network
  
  ```
  datadir="/root/.ethereum"
  
   geth --identity "testNode" --rpc --rpcaddr "0.0.0.0" --rpcport "8545" --rpccorsdomain "*" --datadir 
  $datadir --port "30303" --nodiscover --rpcapi "personal,db,eth,net,web3" --networkid 100 init 
   genesis.json

   geth --identity "testNode" --rpc --rpcaddr "0.0.0.0" --rpcport "8545" --rpccorsdomain "*" --datadir $datadir --port "30303" --nodiscover --rpcapi "personal,db,eth,net,web3,admin,txpool,miner" --networkid 100
  ```

2. issue a token and query the balance

  I use Java code to issued a token, but any other way works well

3.  restart geth node and query the balance 

  Then I run the command `docker stop miner & . docker start miner`.  when It works well, I query the balance , I got `{"jsonrpc":"2.0","id":0,"result":"0x"}`.

  Please notice that,  before I restart , I wait for a long time, and after it restarted, I still can get the transaction and transactionReceipt by the hash I issued the token, it looks the same as before.

**Comment by karalabe** [comment]
Could you check the latest block before and after the restart (`eth.getBlock('latest')`)? I have a hunch that you're not terminating Geth gracefully, causing any state kept in memory only to be lost. The receipts are written to disk immediately however, so that might explain why you can still retrieve them.

**Comment by wangjunbao2018** [comment]
> Could you check the latest block before and after the restart (`eth.getBlock('latest')`)? I have a hunch that you're not terminating Geth gracefully, causing any state kept in memory only to be lost. The receipts are written to disk immediately however, so that might explain why you can still retrieve them.

Thx.  Actually, I checked the latest block before and after I restart it. The block heights aren't the same.  It looks like this:

![image](https://user-images.githubusercontent.com/42427383/50636363-bbae9980-0f90-11e9-8b5b-b0785ebb0cba.png)

What's more,  I found that  after a while after I restart the node,  the height increases and when it's  greater than the block height I issued token, I can successfully get the balance again.  For this pic, before I restart , the height I got by `eth.getBlock('latest')` is  8147, but after restart, I got 6610.

And though there are more than 1000 new block mined, if restart, It looks all the new blocks are missing. why is this happened?

**Comment by karalabe** [comment]
> I have a hunch that you're not terminating Geth gracefully, causing any state kept in memory only to be lost.

Please shut Geth down properly, don't kill it. Murdering it will cause any state only stored in memory to be lost.

**Comment by karalabe** [comment]
One more hint. If you are running Geth within docker, docker will only forward termination signals to process #1. Geth must run with PID 1 to support graceful shutdowns. We had to rework puppeth a while back for this exact reason, to ensure that signals propagate properly.

If you need to run multiple commands in your docker instance (i.e. a script), you can have the last command be geth, started via `exec`. This ensures that geth replaces the script (i.e. retians PID 1) and correctly receives interrupts.

**Comment by qzmer1104** [comment]
how to gracefully shutdown???

**Comment by preston-evans98** [comment]
> how to gracefully shutdown???

Geth shuts down gracefully in response to a SIGINT or SIGTERM (see  #16131). If Geth is running on the host directly (not inside Docker) it's safe to shutdown with Ctrl-c.

If you're running Geth in a Docker container you need to either 
1. Make sure Geth has PID 1 **OR**
1. Make sure that the process with PID 1 forwards SIGINT and SIGTERM **AND**
1. Make sure that the process with PID 1 waits for Geth to terminate before terminating itself

If you do either 1 or both 2 and 3, then you can gracefully terminate Geth with `docker kill --signal=SIGINT {container_name}`

**Comment by qzmer1104** [comment]
> > how to gracefully shutdown???
> 
> Geth shuts down gracefully in response to a SIGINT or SIGTERM (see #16131). If Geth is running on the host directly (not inside Docker) it's safe to shutdown with Ctrl-c.
> 
> If you're running Geth in a Docker container you need to either
> 
> 1. Make sure Geth has PID 1 **OR**
> 2. Make sure that the process with PID 1 forwards SIGINT and SIGTERM **AND**
> 3. Make sure that the process with PID 1 waits for Geth to terminate before terminating itself
> 
> If you do either 1 or both 2 and 3, then you can gracefully terminate Geth with `docker kill --signal=SIGINT {container_name}`

emmm, if not in docker。just centos 7

**Comment by azvast** [comment]
I installed geth in ubuntu20.04 and ran this command to host geth light mode rpc.
`geth --syncmode light`

![image](https://github.com/ethereum/go-ethereum/assets/83703580/6316de29-f28d-4611-b883-929b7dbc6a8a)

But I can't use the rpc.
```
curl --data '{"jsonrpc":"2.0","method":"eth_getBalance", "params": ["0x9b1d35635cc34752ca54713bb99d38614f63c955", "latest"], "id":2}' -H "Content-Type: application/json" localhost:8551
```
I get `missing token` as a result.

**Comment by JeffWScott** [comment]
I also get this missing token response when trying to hit 8551 on localhost
