### ISSUE TITLE
Ethereum synchronization is no longer in progress. I need help

### ISSUE THREAD

**Issue by AhnSungHyeon** [ethereum/go-ethereum#18397]
Hello.

The Ethereum node I have is not syncing.

The version of geth I have is as follows.

Version : v1.8.20-stable-24d727b6

Enter "eth.syncing" in the geth console.

eth.syncing { CurrentBlock: 7005604, highestBlock: 7024283, kownStates: 264827558, pulsedStates: 264827558, startingBlock: 7023250 }

The "currentBlock" value is less than the "startingBlock" value. I think this problem has caused the synchronization to stop.

Is it right?

Is there a solution?

What is the cause?

**Comment by karalabe** [comment]
Please copy-paste exactly what `eth.syncing` prints out. Your dump is definitely not from the API, it contains typos.

**Comment by glesaint** [comment]
Hello, @karalabe  in case it's related, here's a similar issue we're having.
The highest block won't go higher than 3660662 which is the block before the HF if I understand?
The output below is what we got after clearing chaindata and trying to sync again.

```
Welcome to the Geth JavaScript console!
instance: Geth/v1.8.20-stable-24d727b6/linux-amd64/go1.10.4
coinbase: ( edited )
at block: 0 (Wed, 12 Apr 2017 14:59:06 UTC)
 datadir: ( edited )
 modules: admin:1.0 clique:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> eth.syncing
{
  currentBlock: 1065346,
  highestBlock: 3660662,
  knownStates: 3087641,
  pulledStates: 3035631,
  startingBlock: 0
}
> net.peerCount
10
```
