### ISSUE TITLE
whisper: flaky v5 test

### ISSUE THREAD

**Issue by nolash** [ethereum/go-ethereum#18420]
@gballet This test has been flaking on Travis for nearly a year to my reckoning:

```
?       github.com/ethereum/go-ethereum/whisper/shhclient    [no test files]
--- FAIL: TestSimulation (12.28s)
    peer_test.go:196: Test was not complete: timeout 10 seconds.
FAIL
```

https://travis-ci.org/ethereum/go-ethereum/jobs/477291221

I briefly ran this by @gluk256 and he said this belongs to `v5` which by now perhaps is obsolete. If so, maybe the test is obsolete too, and should be skipped?

**Comment by gballet** [comment]
Funny, I've never seen this one fail in travis. I'll have a look into it thanks. I don't want to remove a test, but we should remove v5 altogether. I will warn again and remove it.

**Comment by nolash** [comment]
Ok. However please keep in mind that `pss` uses `v5` as _library_ (not the network, so the sim is not relevant for this). Our `v6` port would have to be done prior to removing it.

**Comment by gballet** [comment]
I am aware, which is why I requested your review in #18432. Please review it when you get a chance.

**Comment by gballet** [comment]
If you believe that my fix isn't going to work, we can also remove everything but what you need, but I would prefer not having dangling bits of code.

**Comment by nonsense** [comment]
FYI this is still failing on `master` occasionally.

**Comment by gballet** [comment]
Whisper v5 has been removed on March the 1st, closing.
