### ISSUE TITLE
eth_getTransactionReceipt returns null on v1.8.20

### ISSUE THREAD

**Issue by romever** [ethereum/go-ethereum#18423]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.8.20-stable-24d727b6`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
`eth_getTransactionReceipt` returns right data when transaction has been mined

#### Actual behaviour
`eth_getTransactionReceipt` retuns null when transaction has been mined

I have 3 geth nodes for our app and they have been normal. Recently I upgraded all nodes  to the latest version v1.8.20.Sometimes one of the nodes jsonrpc method`eth_getTransactionReceipt` returns null when transaction has been mined,but other nodes were normal.When the error has been occurred,geth log is normal.Then I restarted geth node,it retuns to normal.
I think it is a bug on v1.8.20.Please check it out.

tks.

**Comment by karalabe** [comment]
Please provide more information and ideally a way for us to repro it. Saying a method call doesn't work is very very little to go on. Could you perhaps write a small js script that monitors a contract and triggers the missing logs?

**Comment by xiaods** [comment]
@romever please upgrade the node to latest version, it don't reproduce on new version node.

**Comment by romever** [comment]
@xiaods When I reindex the data and upgraded the node,the problem had dispeared.tks
