### ISSUE TITLE
Can't import preexisting private key

### ISSUE THREAD

**Issue by deisikoin** [ethereum/go-ethereum#18435]
Can't import preexisting private key into my Ethereum Wallet using geth account import "my_keyfile". I do everything correctly in geth as geth shows this new account (geth account list), but it still doesn't show up in Ethereum Wallet

Accounts created in the wallet are listed by geth too, so it is not a path issue (they are all in the same directory)

I'm using Ethereum Wallet 0.11.1 on Windows 7

**Comment by karalabe** [comment]
Perhaps the wallet is not checking after startup the accounts Geth has made available since? Did you try perhaps restarting the wallet?

**Comment by deisikoin** [comment]
Indeed, I restarted the wallet. Actually, I didn't mean that the account should appear in the running instance of it

**Comment by ligi** [comment]
>  do everything correctly in geth as geth shows this new account (geth account list), but it still doesn't show up in Ethereum Wallet

I think this issue should be opened in ethereum wallet then - cc @evertonfraga

**Comment by holiman** [comment]
This is not a geth issue, closing
