### ISSUE TITLE
light: submitting tx to light client connected to single light server causes disconnection

### ISSUE THREAD

**Issue by flgh** [ethereum/go-ethereum#18437]
#### System information
Geth
Version: 1.8.20-stable
Git Commit: 24d727b6d6e2c0cde222fa12155c4a6db5caaf2e
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.2
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

2 clients: 1 full node connected to mainnet, light client connected only to the full node.
Same geth version on the light and full.

#### Expected behaviour
Submitted transactions are propagated from the light client to the full node.

#### Actual behaviour
Transactions are not always propagated from the light client to the full node, when it fails, it looks like every time the light client reconnects to the full node it downloads the headers and then is disconnected when trying to submit the pending tx (empty admin.peers, tx pending in txpool.status on the light client)

Every time the light client reconnects, the following message is printed on the console of the full node and the client is disconnected:
ERROR[01-11|17:35:57.760] Request came too early                   id=xxx conn=trusted-inbound recharge=1.714s
ERROR[01-11|17:36:03.014] Request came too early                   id=xxx conn=trusted-inbound recharge=2.859s

A restart of the light client and resubmit of the tx gets it through, but submiting a new tx some time after, the same disconnection an "Request came too early" behavior is observed on the full node, prompting another restart of the light client.

#### Steps to reproduce the behaviour
Running a light node (--nodiscover --netrestrict xxx.xx.xxx.xx/32 --maxpeers 1 --port 30305 --syncmode light) connected to a full node (--lightserv 8 --lightpeers 18 --maxpeers 48), so only one peer on the light client.

Send some tx from an account on the light client.

####
"Request came too early" message is also triggered from some 
other publicly connected light clients.

**Comment by veox** [comment]
Error comes from here:

https://github.com/ethereum/go-ethereum/blob/30cd5c18549f645002aedb4c00e5bab683cb0835/les/handler.go#L344-L353

How big are the transactions you're submitting?..

**Comment by flgh** [comment]
About 1 out of 3 sent tx triggers the disconnection, 

detailed logs from the full node:
DEBUG[01-13|03:18:09.712] Announcing block to peers                number=7057027 hash=cc5afc…a8be26 td=8697255149581654484737 reorg=0
ERROR[01-13|03:18:09.876] Request came too early                   id=xxx conn=trusted-inbound recharge=135.876ms
DEBUG[01-13|03:18:09.876] Light Ethereum message handling failed   id=xxx conn=trusted-inbound err="Request rejected - "
DEBUG[01-13|03:18:09.888] Removing p2p peer                        id=xxx conn=trusted-inbound duration=15h7m25.186s peers=46 req=false err="useless peer"
DEBUG[01-13|03:18:09.890] Adding p2p peer                          name=Geth/v1.8.20-stable-...                                                   addr=yyy:42612  peers=47

**Comment by flgh** [comment]
@veox

These are pretty simple tx submitted (either value transfers or ERC-20 token transfers (136 bytes in data field) ) with json-rpc:
eth_estimateGas of the data followed by personal_sendTransaction

Once the tx is in the txpool of the light node, every reconnection of the light node triggers an immediate disconnection after headers have been downloaded.

**Comment by holiman** [comment]
This now seems fixed. The `request came too early` is now within `accept` (not `reject`, called e.g. here:https://github.com/ethereum/go-ethereum/blob/master/les/handler.go#L1048 . If it returns false, it will not disconnect the client, just ignore the message. 
cc @zsfelfoldi am I correct ?
