### ISSUE TITLE
GETH SYNCS - Then slows down and lags behind [Server info & Geth config attached]

### ISSUE THREAD

**Issue by mishul** [ethereum/go-ethereum#18438]
Geth server Info: 
6 cpus, 18gb mem
SSD: 450 GB (42%used)

Geth Config is below. Our node originally syncs all the way, then slows down and lags behind.. we have to restart it to pickup pace but then yet again it slows down. So we have been upgrading our server one after the other to hopefully resolve this issue... We are supporting an exchange so need the node to be upto sync continously. We need eth_blocknumber to be working so cannot use --fast mode. Are these specs enough? Does something need to be changed in config? WHAT EXACTLY DO WE NEED TO MAKE THIS GETH NODE RUN & STAY IN SYNC?? 

Thanks for your help!

Eth config
MaxPeers = 100
NoDiscovery = false
BootstrapNodes = ["enode://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@52.16.188.185:30303", "enode://3f1d12044546b76342d59d4a05532c14b85aa669704bfe1f864fe079415aa2c02d743e03218e57a33fb94523adb54032871a6c51b2cc5514cb7c7e35b3ed0a99@13.93.211.84:30303", "enode://78de8a0916848093c73790ead81d1928bec737d565119932b98c6b100d944b7a95e94f847f689fc723399d2e31129d182f7ef3863f2b4c820abbf3ab2722344d@191.235.84.50:30303", "enode://158f8aab45f6d19c6cbf4a089c2670541a8da11978a2f90dbf6a502a4a3bab80d288afdbeb7ec0ef6d92de563767f3b1ea9e8e334ca711e9f8e2df5a0385e8e6@13.75.154.138:30303", "enode://1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d89d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082@52.74.57.123:30303", "enode://979b7fa28feeb35a4741660a16076f1943202cb72b6af70d327f053e248bab9ba81760f39d0701ef1d8f89cc1fbd2cacba0710a12cd5314d5e0c9021aa3637f9@5.1.83.226:30303"]
BootstrapNodesV5 = ["enode://06051a5573c81934c9554ef2898eb13b33a34b94cf36b202b69fde139ca17a85051979867720d4bdae4323d4943ddf9aeeb6643633aa656e0be843659795007a@35.177.226.168:30303", "enode://0cc5f5ffb5d9098c8b8c62325f3797f56509bff942704687b6530992ac706e2cb946b90a34f1f19548cd3c7baccbcaea354531e5983c7d1bc0dee16ce4b6440b@40.118.3.223:30304", "enode://1c7a64d76c0334b0418c004af2f67c50e36a3be60b5e4790bdac0439d21603469a85fad36f2473c9a80eb043ae60936df905fa28f1ff614c3e5dc34f15dcd2dc@40.118.3.223:30306", "enode://85c85d7143ae8bb96924f2b54f1b3e70d8c4d367af305325d30a61385a432f247d2c75c45c6b4a60335060d072d7f5b35dd1d4c45f76941f62a4f83b6e75daaf@40.118.3.223:30307"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Dashboard]
Host = "localhost"
Port = 8080
Refresh = 5000000000

**Comment by xiaods** [comment]
yes, the full mode is very slow, you only pay patience to waiting the syncing.  by the way, the disk space should be keep 1T is satisfy.

**Comment by holiman** [comment]
>  We need eth_blocknumber to be working so cannot use --fast mode 

Sounds like a misconception. After the initial sync, which _should_ be done in a couple of hours (as opposed to 100+ hours of full sync), the node behaves like a full-synced node, importing block by block. 

The specs look ok. Could you please provide some logs from the slow blocks? 
From experience, I would suspect that the SSD has been worn out. I've had to replace an SSD which had degraded to usb-drive speeds (20M/s). Replacing it bumped the SSD speeds with a factor of `20`, IIRC.  See https://askubuntu.com/questions/87035/how-to-check-hard-disk-performance . 

> this is not issue, it should be close asap.

I agree, but we can keep it open a bit longer. A 6-cpu / 18G system should not have any problems keeping in sync.

**Comment by xiaods** [comment]
@holiman agree

**Comment by mishul** [comment]
@holiman I see what you mean by 'initial syncing'. After a while, our block_number is no longer null. My understanding is when 'initial syncing' is done, block_number changes from null. However, block_number is never the latest block. It matches the current block which we are syncing, which right now is still behind the latest block. Will this become an issue when new transactions come in and our block_number still isn't at the latest block?
