### ISSUE TITLE
Mobile: support pending logs

### ISSUE THREAD

**Issue by timoninn** [ethereum/go-ethereum#18449]
Currently in mobile clients there is possibility to filter logs specifying only "earliest" and "latest" blocks when using EthereumClient.filterLogs or EthereumClient.subscribeFilterLogs. This can be done using the setFrom/ToBlock methods of FilterQuery with BigInt input, specifying "earliest" as zero and "latest" as null.

But we can't filter logs specifying "pending" block. Is support of this feature planned ?

**Comment by ligi** [comment]
can you elaborate what your use-case for pending blocks is?
