### ISSUE TITLE
Linux Geth Mining: Stuck at Commit New Mining Work in private blockchain Offline

### ISSUE THREAD

**Issue by ChristianQ7** [ethereum/go-ethereum#18446]
#### System information

Geth Version: 1.8.20-stable
Git Commit: 24d727b6d6e2c0cde222fa12155c4a6db5caaf2e
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.2
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.11.2.linux.amd64

#### Expected behaviour
When I run miner.start(1), it can start to commit new mining work constantly.

#### Actual behaviour
It was stuck at the first step forever.
![image](https://user-images.githubusercontent.com/46620095/51162224-66e41a80-18d0-11e9-89d1-05b33d6009e8.png)

#### Steps to reproduce the behaviour
` ./geth --datadir /home/dx/geth/privatechain init /home/dx/geth/privatechain/genesis.json`
`./geth --datadir /home/dx/geth/privatechain --nodiscover --maxpeers 0 --metrics --networkid 110 console`
`
> eth.accounts[0]
"0xacabab362bb65cfc9235f786a799cf15aba79c5f"
> personal.unlockAccount("0xacabab362bb65cfc9235f786a799cf15aba79c5f")
Unlock account 0xacabab362bb65cfc9235f786a799cf15aba79c5f
Passphrase: 
true
> miner.setEtherbase(eth.accounts[0])
true
> miner.start(1)
INFO [01-15|21:18:17.236] Updated mining threads                   threads=1
INFO [01-15|21:18:17.236] Transaction pool price threshold updated price=1000000000
null
> INFO [01-15|21:18:17.237] Commit new mining work                   number=1 sealhash=868ada…a8f498 uncles=0 txs=0 gas=0 fees=0 elapsed=342.669?s
`

### Genesis.json
`{
    "config": {
        "chainId": 110,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "alloc"      : {},
    "coinbase"   : "0x0000000000000000000000000000000000000000",
    "difficulty" : "0x4",
    "extraData"  : "",
    "gasLimit"   : "210000",
    "nonce"      : "0x0000000000000042",
    "mixhash"    : "0x0000000000000000000000000000000000000000000000000000000000000000",
    "parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
    "timestamp"  : "0x00"
}`

#### Issue
To tackle this issue, I have regenerated DAG but it had no effect. I also ran this command on the other ubuntu offline and succeeded in starting new mining work. So, I thought it could be attributed to the low memory. I expanded virtual memory to 7.8GB requested from hard disk, but it failed either, even though `eth.mining` is true.

**Comment by karalabe** [comment]
What kind of machine are you running the miner on?

**Comment by p0onage** [comment]
Hi @karalabe I am also having this issue, the machine I am running the Go Ethereum client on is an Azure Linux VM (A1_v2) with 2 GB Ram and 30BiB standard HDD disks

**Comment by p0onage** [comment]
I've upgraded the server to a  Standard_DS1_v2

It's managed to mine the first block now but it's just so slow! been running for hours and nothing.

I've found the total difficulty is very high. The hash rate is 57533
the total difficulty is 34351349760
and the difficulty is 17171480576

what could be causing this? I've got another machine same spec running with the same genesis block on a different network id and that is working fine?

**Comment by karalabe** [comment]
@p0onage Are you sure you have the same genesis block? What does `eth.getBlock(0)` print?

**Comment by p0onage** [comment]
Found that the custom genesis file didn't generate the expected genesis block and the default Ethereum genesis block was created with much high difficulty. 

https://github.com/ethereum/go-ethereum/issues/15087

**Comment by holiman** [comment]
Initial reporter had difficulty `0x4`, which is not supported. Second reporter seems to have had mismatched genesis:es. Closing this
