### ISSUE TITLE
Historical state missing despite archive mode

### ISSUE THREAD

**Issue by jupibes** [ethereum/go-ethereum#18441]
Hi there,
Now i have fully syncing ETH core, but some blocks is missing state information.
Is there any option to resync missing information(states) or roll-back chaindata to some blocks?

#### System information

Geth version: `v1.8.20`
OS & Version:Linux

#### Expected behaviour
All transactions have state information

#### Actual behaviour
Some transaction is missing state information
1) Transaction from block 6800010 
debug.traceTransaction("0xdef6179b9bd9d88f32421b75de7cfbf8f0958d8a6e2a1d2cd3d1342466101fde")
{ failed: false,
2) Transaction from block 6803365
debug.traceTransaction("0x8434f473062d13576edd8ca03aea3c873357a3153849b5274d4ecf2544c49b56")
Error: required historical state unavailable
3) Transaction from block 7040010
debug.traceTransaction("0x5bd0584a3d9b443fb6a2539e744012f68fbb4ae7b41788fbf431d82fa05b1042")
{ failed: false,

#### Steps to reproduce the behaviour
1. Run geth with following geth -gcmode archive --syncmode full
2. Wait for the sync to complete (eth.syncing false)
3. Check state with debug.TraceTransaction

**Comment by wjmelements** [comment]
I am seeing the same issue.

I am running geth 1.8.22 with
```
nohup geth --syncmode "full" --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*"  --rpcapi eth,web3,net,debug --ws --wsapi eth,web3,net,debug 2>> ~/log/geth`date +%Y-%j` &
```

**Comment by sourav1547** [comment]
Even I have observed the same issue. I am using geth version 1.9.0-unstable-35853518
I have synced up a node in gcmode --archive. 
Missing transaction hash 0x6c929e1c3d860ee225d7f3a7addf9e3f740603d243260536dfa2f3cf02b51de4

**Comment by holiman** [comment]
@wjmelements A full node doesn't have all state, it does in-memory pruning. However, it _can_ find a good point before the block you're requesting, and process through the blocks and thus restore the state. 

@jupibes and @sourav1547 a `gcmode=archive` should have all state, so that's very odd. @sourav1547 could you provide some more info about your setup -- what error message do you get when you do what?

**Comment by sourav1547** [comment]
I am trying to fetch the debug trace of the transaction with following hash and I get the error mentioned.
 > `debug.traceTransaction("0x6c929e1c3d860ee225d7f3a7addf9e3f740603d243260536dfa2f3cf02b51de4")`
Error: required historical state unavailable (reexec=128)
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

I used the following command to run the geth node. 
`geth --syncmode full --gcmode archive --cache=4096 --rpc --rpcport 21000 --rpcapi "eth,web3,debug,admin"`

OS: Ubuntu 16.04
Geth version: 1.9.0-unstable-35853518

**Comment by holiman** [comment]
Thanks, and what's the output of 
`eth.getBlock("latest")` and `eth.syncing` ?

**Comment by sourav1547** [comment]
Output of eth.getBlock("latest")

`
 difficulty: 2013132411859604,
  extraData: "0x505059452d65746865726d696e652d6575312d36",
  gasLimit: 8000000,
  gasUsed: 7890857,
  hash: "0x3735cce792eae8ff29f3092c2165a3e06132cc895d437e69db37a6cb66496f35",
  logsBloom: "0x6c02b6c10a7c049410f3840b0024883062a412ac94460d182640e281807ec06041c1188008442740843c222cac20025002504418648d02319d1db09c54306417416281c2a250047b7800840ce249bcf74d50049c0b0a9946903507ed46d4a240222f8a0242612e61e2341c0934ca3e435412b0c01d475046004505100c25c0c0022989234892513205000510b600b07041284900119b01608829241630650b6143a200416d42148141040c112c61f8542c0a0324dbd3044a800b04e81c61abd020981eca990f508128042539462832406845401b210a040c084330038306731102121805084a338a1aa0c0a12010a34d912dc422191121114c7813540476d302",
  miner: "0xea674fdde714fd979de3edf0f56aa9716b898ec8",
  mixHash: "0x709ad0127cfe5953a24f82a59f05d22e560142cb66ab9f303858fb4c1ecb62e6",
  nonce: "0x802a180fa1cc6278",
  number: 7943627,
  parentHash: "0x03356910136e86a181321cad1a7bfd35c5f015653f7391e3c06eb6dbd1db4adb",
  receiptsRoot: "0x90e81a8780e0d6ce1c01a7d69fdbfc6ea2e8ccfddc2efa26249b3abd1cfef5c5",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 23568,
  stateRoot: "0xd21b2430571a46ce9a667c112ca7e9320c6b1f1150d8b9c653cbfc333761457a",
  timestamp: 1560338446,
  totalDifficulty: 1.05768889957533554128e+22,
  transactions: [.....]
`
I synced the blockchain till 7943627. Once synced, I restarted the geth with `--maxpeers 0 ` to avoid further syncing. I am running geth in `--gcmode archive` for the entire time.

**Comment by holiman** [comment]
> I synced the blockchain till 7943627.

What was the exact command used?

**Comment by holiman** [comment]
If it was indeed `geth --syncmode full --gcmode archive --cache=4096 --rpc --rpcport 21000 --rpcapi "eth,web3,debug,admin"`, then I'm at a loss to explain this...

**Comment by karalabe** [comment]
I think there's not enough information to keep this issue alive. The Geth versions reporting fault here are quite old and we've put a lot of work into the database since 1.9.0. I'm not saying there isn't a legit issue, but at this point in time it just does not make sense to try and figure out what went wrong 1+ year ago. If anything like this still persists on a recent version of Geth, please open a new issue.
