### ISSUE TITLE
all: move sub-protocol implementations into a top level package

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#1845]
Currently we have `eth` and `whisper`. With `bzz` and `les` coming, we should move these into a top level package, otherwise the namespace is getting annoyingly littered. Also we should decide whether we want to go with the short protocol code naming (e.g. shh) vs. the descriptive names (e.g. whisper). Maybe the code-name is better, otherwise the "light" will either be too ambiguous, or too long.

**Comment by zelig** [comment]
we already renamed swarm and whisper, eth could be renamed ethereum.
But i dont support moving them under a toplevel package.
@karalabe can we close this?

**Comment by fjl** [comment]
I think we're happy with the current names.
