### ISSUE TITLE
Panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by Zebbedie** [ethereum/go-ethereum#1846]
Using geth version 1.2.0 on linux mint cinnamon.

$ geth wallet import <filename of json encrypted wallet>
$ password
After entering password error  Panic: runtime error: slice bounds out of range error reported on std output.

This looks like program code not handling a stack situation properly.
Cheers
Vince

**Comment by karalabe** [comment]
Please provide a dump of the panic. Without that, we cannot really trace where the issue came from.

**Comment by zelig** [comment]
closing due to lack of evidence :)

**Comment by yuandi0823** [comment]
Win10 64  same questions
Geth
Version: 1.6.7-stable
Git Commit: ab5646c532292b51e319f290afccf6a44f874372
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: windows
GOPATH=D:\Work\VM\GOPATH
GOROOT=D:\Work\VM\Go
------------------------------------------------------------------------------------------------------------------

Passphrase:
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/ethereum/go-ethereum/accounts/keystore.decryptPreSaleKey(0xc042401800, 0x1ea, 0x3ea, 0xc0421309a0, 0x0, 0xbe18a9, 0xc0421eb360, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/presale.go:61 +0x631
github.com/ethereum/go-ethereum/accounts/keystore.importPreSaleKey(0x148ad20, 0xc042429d20, 0xc042401800, 0x1ea, 0x3ea, 0xc0421309a0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/presale.go:36 +0xa9
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).ImportPreSaleKey(0xc04224c1e0, 0xc042401800, 0x1ea, 0x3ea, 0xc0421309a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:478 +0xc2
main.importWallet(0xc042436000, 0xe92567, 0x8)
        C:/gopath/src/github.com/ethereum/go-ethereum/cmd/geth/accountcmd.go:339 +0x27c
github.com/ethereum/go-ethereum/cmd/utils.MigrateFlags.func1(0xc042436000, 0x0, 0xc042436000)
        C:/gopath/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1131 +0xca
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xd3f1c0, 0xc0424027e0, 0xc042436000, 0xc042223300, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:485 +0xdb
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xe8f32f, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xed07f2, 0x1e, 0x0, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/command.go:193 +0xb79
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).RunAsSubcommand(0xc0420371e0, 0xc04221fcc0, 0x0, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:374 +0xad3
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.Command.startApp(0xe8fbb7, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xed232b, 0x1f, 0x0, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/command.go:280 +0x82b
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xe8fbb7, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xed232b, 0x1f, 0x0, ...)
        C:/gopath/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/command.go:79 +0x14ce
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc042036d00, 0xc042014200, 0x8, 0x8, 0x0, 0x0)
        C:/gopath/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:250 +0x7d7
main.main()
        C:/gopath/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:192 +0x5c
