### ISSUE TITLE
Can't use rpc http api when using docker image

### ISSUE THREAD

**Issue by senzacionale** [ethereum/go-ethereum#18463]
Hello,

I'm trying to setup a ethereum (with docker) on personal dedicated server, then use it in same server from another container. But RPC api seems not available. Thank's.

#### System information

docker run -it -name eth-node -p 8545:8545 -p 30303:30303 -v /data/ethereum:/root/.ethereum ethereum/client-go --rpc --rpcaddr "0.0.0.0"

#### Expected behaviour

RPC HTTP interface available on http://eth-node:8545

INFO [01-16|17:51:58.063] HTTP endpoint opened                     url=http://0.0.0.0:8545      cors= vhosts=localhost

#### Actual behaviour

No RPC HTTP interface on http://eth-node:8545

````
[backtrace]
````

**Comment by lmars** [comment]
Do you get an error when trying to connect?

**Comment by senzacionale** [comment]
timeout

**Comment by mawenpeng** [comment]
You may need to check your firewall rules.

**Comment by mawenpeng** [comment]
How about http://localhost:8545 or http://127.0.0.1:8545?

**Comment by senzacionale** [comment]
There is no firewall so this is not firewall issue. Docker containers can not communicate between each other via localhost or 127.0.0.1

**Comment by nonsense** [comment]
@senzacionale you can specify `--rpcvhosts "eth-node"` and then target `eth-node:8545`.

**Comment by lmars** [comment]
@senzacionale it would be useful to paste the commands you are running and the exact errors you are seeing, I suspect this is an issue with your Docker setup, rather than a problem with geth.

Here is an example of running geth in one Docker container and connecting to it from another:

```
$ docker network create geth-test
7cf52ca08ee0e6749dc3b0889cf5bfcc8c0197011d1e57bcda863e689e07bb57

$ docker run --network geth-test --name eth-node ethereum/client-go --rpc --rpcaddr "0.0.0.0" --rpcvhosts "eth-node"
...
INFO [01-17|12:53:37.918] HTTP endpoint opened                     url=http://0.0.0.0:8545      cors= vhosts=eth-node
```

```
$ docker run -it --network geth-test ethereum/client-go attach http://eth-node:8545
WARN [01-17|13:01:21.090] Sanitizing cache to Go's GC limits       provided=1024 updated=666
Welcome to the Geth JavaScript console!

instance: Geth/v1.8.22-unstable-34f11e75/linux-amd64/go1.11.4
 modules: eth:1.0 net:1.0 rpc:1.0 web3:1.0

> net.version
"1"
```

**Comment by xiaods** [comment]
please consider my repo for the reference.
https://github.com/xiaods/ethereum-client-k8s-setup

**Comment by senzacionale** [comment]
Yes it helps me a lot. Now I am testing it.

**Comment by ligi** [comment]
please let us know how the test went

**Comment by senzacionale** [comment]
Hello. I think problem is solved. Thank you for your support

**Comment by chinqi** [comment]
@senzacionale, Hi, how did you solved that problem?
