### ISSUE TITLE
accounts/abi.Unpack method no longer accepts empty interface as destination

### ISSUE THREAD

**Issue by i-norden** [ethereum/go-ethereum#18480]
#### System information

Geth version: 1.21
OS & Version: macOS Mojave v10.14.2
Commit hash : 7ca40306af9da68a0d31439117246de8247f99d6

#### Expected behaviour
Prior to the 1.21 release, one could pass a pointer to an empty interface (v) to the abi.Unpack(v interface{}, data []byte) method in order to unpack values returned from contract method calls without needing to know the type of the returned values beforehand. This was a rather convenient "feature" as a developer that wants to work with contracts in a dynamic and generic manner. 

#### Actual behaviour
Post 1.21 release (post commit 7ca40306af9da68a0d31439117246de8247f99d6 ) doing so now throws errors in the accounts/abi.Reflect package as it is attempting to [call](https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/reflect.go#L75) reflect.Value.Type on a zero [Value](https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/argument.go#L109)

#### Steps to reproduce the behaviour
This error is thrown when attempting to unpack contract method results into an empty interface [here](https://github.com/vulcanize/vulcanizedb/blob/master/pkg/omni/shared/poller/poller.go#L148) using the FetchContractData method defined [here](https://github.com/vulcanize/vulcanizedb/blob/master/pkg/geth/contract.go#L32) which calls the abi.Unpack [method](https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/abi.go#L75).

[Master branch](https://github.com/vulcanize/vulcanizedb) of vulcanizeDB is working using geth 1.18, the [updated branch](https://github.com/vulcanize/vulcanizedb/tree/updates) using geth 1.21 fails to pass [tests](https://travis-ci.org/vulcanize/vulcanizedb/builds/481464708?utm_source=github_status&utm_medium=notification) with the below errors.

It should be noted that some of the line numbers in the below stack trace are offset due to vulcanizeDB currently using a modified version of the Geth abi package that includes the updates [here](https://github.com/ethereum/go-ethereum/pull/18440), but these additional methods are not involved in this error.

#### Backtrace

````
/usr/local/go/src/runtime/panic.go:513 +0x1b9
      reflect.Value.Type(0x0, 0x0, 0x0, 0xc0003ee120, 0x0)
      	/usr/local/go/src/reflect/value.go:1743 +0x16c
      github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/accounts/abi.set(0x0, 0x0, 0x0, 0x457aba0, 0xc0004688c0, 0x91, 0x0, 0x0)
      	/Users/iannorden/go/src/github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/accounts/abi/reflect.go:75 +0x5a
      github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/accounts/abi.set(0x45139a0, 0xc0004104b0, 0x194, 0x457aba0, 0xc0004688c0, 0x91, 0x403e273, 0x45139a0)
      	/Users/iannorden/go/src/github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/accounts/abi/reflect.go:78 +0x4ef
      github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/accounts/abi.unpack(0xc0002f07e0, 0x44d92e0, 0xc0004104b0, 0x457aba0, 0xc0004688c0, 0x16, 0x457aba0)
      	/Users/iannorden/go/src/github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/accounts/abi/argument.go:124 +0xc72
      github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/accounts/abi.Arguments.unpackAtomic(0xc0002c4900, 0x1, 0x4, 0x44d92e0, 0xc0004104b0, 0x457aba0, 0xc0004688c0, 0x1, 0x1)
      	/Users/iannorden/go/src/github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/accounts/abi/argument.go:205 +0x44b
      github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/accounts/abi.Arguments.Unpack(0xc0002c4900, 0x1, 0x4, 0x44d92e0, 0xc0004104b0, 0xc0004688a0, 0x20, 0x20, 0xc000402500, 0x24)
      	/Users/iannorden/go/src/github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/accounts/abi/argument.go:102 +0x187
      github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/accounts/abi.ABI.Unpack(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0002e4c60, ...)
      	/Users/iannorden/go/src/github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/accounts/abi/abi.go:85 +0x2fa
      github.com/vulcanize/vulcanizedb/pkg/geth.(*BlockChain).FetchContractData(0xc000178230, 0x45e4afa, 0x735, 0x45d89be, 0x2a, 0xc000424648, 0x8, 0xc000410460, 0x1, 0x1, ...)
      	/Users/iannorden/go/src/github.com/vulcanize/vulcanizedb/pkg/geth/contract.go:50 +0x2da
      github.com/vulcanize/vulcanizedb/pkg/omni/shared/poller.(*poller).pollSingleArgAt(0xc0000e6ea0, 0xc000424648, 0x8, 0x1, 0xc000277540, 0x1, 0x1, 0xc0002775e0, 0x1, 0x1, ...)
      	/Users/iannorden/go/src/github.com/vulcanize/vulcanizedb/pkg/omni/shared/poller/poller.go:148 +0x424
      github.com/vulcanize/vulcanizedb/pkg/omni/shared/poller.(*poller).PollContractAt(0xc0000e6ea0, 0x45c5e8b, 0xc, 0x45d89be, 0x2a, 0x0, 0x0, 0x699eef, 0x699ef0, 0x45e4afa, ...)
      	/Users/iannorden/go/src/github.com/vulcanize/vulcanizedb/pkg/omni/shared/poller/poller.go:72 +0x2dd
      github.com/vulcanize/vulcanizedb/pkg/omni/shared/poller.(*poller).PollContract(0xc0000e6ea0, 0x45c5e8b, 0xc, 0x45d89be, 0x2a, 0x0, 0x0, 0x699eef, 0x699ef0, 0x45e4afa, ...)
      	/Users/iannorden/go/src/github.com/vulcanize/vulcanizedb/pkg/omni/shared/poller/poller.go:57 +0x8a
      github.com/vulcanize/vulcanizedb/pkg/omni/shared/poller_test.glob..func2.3.2.4()
      	/Users/iannorden/go/src/github.com/vulcanize/vulcanizedb/pkg/omni/shared/poller/poller_test.go:221 +0x385
      github.com/vulcanize/vulcanizedb/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc0000a7ec0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
      	/Users/iannorden/go/src/github.com/vulcanize/vulcanizedb/pkg/omni/shared/poller/poller_suite_test.go:30 +0x63
      testing.tRunner(0xc0000ee400, 0x45ee758)
      	/usr/local/go/src/testing/testing.go:827 +0xbf
      created by testing.(*T).Run
      	/usr/local/go/src/testing/testing.go:878 +0x35c
````

#### Questions
Was this an intended effect of these changes to the abi package or is this an unwanted side effect?  
In lieu of these changes is there or should there be a way to unpack method results into an empty interface?

Thanks!

**Comment by rjl493456442** [comment]
Hi, the original version(before commit `7ca4030`) should allow interface as the unpack destination for **single return value** while not for **tuple return value**.  I guess in your case the contract return should be single value.

I have a PR #18490 to allow interface as the destination for single value, could you please have a try ?

**Comment by i-norden** [comment]
I gave the changes in PR [#18490](https://github.com/ethereum/go-ethereum/pull/18490) a try and it has resolved the issue! Thank you!
