### ISSUE TITLE
No working of ethereum full node synchronize.

### ISSUE THREAD

**Issue by AkashiHidaka** [ethereum/go-ethereum#18483]
#### System information
Geth version: `v1.8.20-stable-24d727b6`
OS & Version: Ubuntu 16.04 system
Commit hash : Mainet
#### Expected behaviour
Ethereum full node synchronize.
#### Actual behaviour
It isn't synchronize in 7080000 block step. geth process run , but no synchronize the blocks.
![image](https://user-images.githubusercontent.com/44053447/51451972-f0816580-1d72-11e9-91bb-a0bd08bfc6d0.png)
Now high block values is 7101900 and it isn't work of recently data.

#### Steps to reproduce the behaviour

I stopped and again run the geth service and it is same.

#### Backtrace
I don't know the way.
I think it is occur by Constantinople Hard Fork.
````
[backtrace]
````
I need quickly fix of this problem.

**Comment by DavidEdwards** [comment]
> Geth version: `v1.8.20-stable-24d727b6`

Update your version. 1.8.20 is the Constantinople release, but that was delayed until February. You need to update to 1.8.21 or [one of the other options mentioned here](https://github.com/ethereum/go-ethereum/releases/tag/v1.8.21).

**Comment by uttamrabadiya** [comment]
> > Geth version: `v1.8.20-stable-24d727b6`
> 
> Update your version. 1.8.20 is the Constantinople release, but that was delayed until February. You need to update to 1.8.21 or [one of the other options mentioned here](https://github.com/ethereum/go-ethereum/releases/tag/v1.8.21).

I have same issue, I just updated version to 1.8.21 but now block synchronization is not even starting anymore.

**Comment by uttamrabadiya** [comment]
> > Geth version: `v1.8.20-stable-24d727b6`
> 
> Update your version. 1.8.20 is the Constantinople release, but that was delayed until February. You need to update to 1.8.21 or [one of the other options mentioned here](https://github.com/ethereum/go-ethereum/releases/tag/v1.8.21).

Error fixed, Thank you!

**Comment by DavidEdwards** [comment]
That depends how you installed it.

If you used apt, you could try using `apt-get install --only-upgrade geth`.

**Comment by AkashiHidaka** [comment]
Done it , but still no changed the version.
![image](https://user-images.githubusercontent.com/44053447/51484934-c0b87900-1dd7-11e9-9ad3-ade250daa399.png)

**Comment by AkashiHidaka** [comment]
I updated "v1.8.21-stable-9dc5d1a9" version and synchronize speed is very slow and anytime the current number again reset and resynchronizing.
![image](https://user-images.githubusercontent.com/44053447/51573817-d1efab80-1ee5-11e9-860c-650402cf74e5.png)

**Comment by kazaff** [comment]
![image](https://user-images.githubusercontent.com/801787/51586290-8bb34000-1f17-11e9-9d72-ed2b49a26d5f.png)
same to u~
what i need to do?

**Comment by AkashiHidaka** [comment]
I know the some errors.
In geth service sometime stopped and again start the blocks.
