### ISSUE TITLE
How can i find logs if i have selfdestruct the contract

### ISSUE THREAD

**Issue by zhangyaocheng** [ethereum/go-ethereum#18494]
I have a question in write my first contract. It is that, if i use `selfdestruct` in my contract, how can find my logs which were generated when use this contract? 

Or, there are any method i can use to find those logs?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
