### ISSUE TITLE
geth runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by antechdemo** [ethereum/go-ethereum#18501]
![ethcrop](https://user-images.githubusercontent.com/36949551/51584923-6fa2a500-1efd-11e9-8a63-1709977691d6.png)

After this warning its Synchronisation failed.

![ethcroptest](https://user-images.githubusercontent.com/36949551/51585348-091e8680-1eff-11e9-85da-b69dc9410ec9.png)

**Comment by mavericklin** [comment]
same issue, I am using POA with 2 sealers. It happens when there is a transaction on the chain, for the chain without transactions(only empty blocks), it will not happen.

**Comment by holiman** [comment]
So the crash is fixed on master, and the `Failed accounts unlock attempt`, which is reported as a `WARN`, is a WARNING that someone tried to `unlock` an account on your node. 

Judging by your question, I assume it wasn't you. So someone else on the internet is hammering your node trying to bruteforce your passwords. Please don't expose your rpc ports against the internet.
