### ISSUE TITLE
CallTracer displays incorrect transaction information

### ISSUE THREAD

**Issue by LucasGmm** [ethereum/go-ethereum#18514]
When debugging.traceTransaction gets internal transfer information, I have a lot of problems with very large values in CallTracer, such as txid = '0x0e6525f5df542f48c24329bde6903e2e45f9afdf3e2b28802c6dd20d6e4bd1f6', I am looking for it.
Https://etherscan.io/tx/0x0e6525f5df542f48c24329bde6903e2e45f9afdf3e2b28802c6dd20d6e4bd1f6 but did not show such a transfer, but debug.traceTransaction has a large amount of transfer

![image](https://user-images.githubusercontent.com/40879103/51674233-13c64200-200b-11e9-80aa-8d62372973e5.png)

This is very troublesome for me, which leads me to have no way to carry out the analysis. I hope that everyone will give me some help because I am very much looking forward to the development of the Ethereum community.

**Comment by holiman** [comment]
Please try out the functionality from https://github.com/ethereum/go-ethereum/pull/17914 . 
Should be a matter of doing
```
> debug.standardTraceBlockToFile("0x995d48328ff5ce7ecc122d39bd3fe2c536e180cac1a71213d019655f3b15d5be", {txHash:"0x0e6525f5df542f48c24329bde6903e2e45f9afdf3e2b28802c6dd20d6e4bd1f6", disableMemory:true})
```
If you then provide the output, I'm sure we can figure out what's amiss with the call tracer.
