### ISSUE TITLE
Wrong gas estimation by eth_estimateGas 

### ISSUE THREAD

**Issue by ZumZoom** [ethereum/go-ethereum#18519]
#### System information

Geth version: 1.8.21
OS & Version: Ubuntu 18.04.1

#### Expected behaviour

`eth_estimateGas` should return enough gas to execute transaction.

#### Actual behaviour

`eth_estimateGas` returns not enough gas to execute transaction.

#### Steps to reproduce the behaviour

Call `eth_estimateGas` on fallback function of a [simple contract](https://ropsten.etherscan.io/address/0x2926d1c444ef19486881e7bcb72960bb62c5dcc6#code) compiled by Solidity 0.4.25.

`eth_estimateGas` estimates required gas as 22370.

However function requires 23104 gas to execute successfully.

Also I think it's worth noting that `eth_estimateGas` works correctly with the same contract compiled by Solidity 0.5.3 which can be found [here](https://ropsten.etherscan.io/address/0x48df4b3fddfc1d9ca57769c7ccf9444ed22905a1#code).

It returns 23137 gas which is exactly what is required for the execution.

**Comment by wjmelements** [comment]
[Here](https://www.diffchecker.com/mRK5oD9v) is the bytecode diff

**Comment by karalabe** [comment]
Thanks for the repro, will look into it, just need to sync a node.

**Comment by jmooo** [comment]
This looks similar to what I'm hitting with both Geth and Parity, I posted to a [Parity ticket](https://github.com/paritytech/parity-ethereum/issues/10147#issuecomment-460875799) a week ago. From the comments about Solidity possibly being the issue, my examples below used:

-  BeerCoin, Solidity v0.3.5, Success
-  USDCoin, Solidity v0.4.24, Failed

cross posting parity ticket because it has test commands:

> I've been running into this on Parity v2.2.8, and Geth v1.8.22 and it seems to fail when `to` is set to certain contracts but not others? For example:
> 
> BeerCoin: https://etherscan.io/address/0x74c1e4b8cae59269ec1d85d3d4f324396048f4ac
> parity:
> ```
> curl -H "Content-Type: application/json" --request POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"to":"0x74c1e4b8cae59269ec1d85d3d4f324396048f4ac","data":"0xa9059cbb0000000000000000000000007cb57b5a97eabe94205c07890be4c1ad31e486a80000000000000000000000000000000000000000000000000000000000000001"}],"id":34}' http://localhost:8889
> {"jsonrpc":"2.0","result":"0x1f159","id":34}
> ```
> geth:
> ```
> curl -H "Content-Type: application/json" --request POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"to":"0x74c1e4b8cae59269ec1d85d3d4f324396048f4ac","data":"0xa9059cbb0000000000000000000000007cb57b5a97eabe94205c07890be4c1ad31e486a80000000000000000000000000000000000000000000000000000000000000001"}],"id":34}' http://localhost:8889
> {"jsonrpc":"2.0","id":34,"result":"0x1f159"}
> ```
> 
> USDCoin: https://etherscan.io/address/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
> parity:
> ```
> curl -H "Content-Type: application/json" --request POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"to":"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48","data":"0xa9059cbb0000000000000000000000007cb57b5a97eabe94205c07890be4c1ad31e486a80000000000000000000000000000000000000000000000000000000000000001"}],"id":34}' http://localhost:8889
> {"jsonrpc":"2.0","error":{"code":-32016,"message":"The execution failed due to an exception."},"id":34}
> ```
> geth:
> ```
> curl -H "Content-Type: application/json" --request POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"to":"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48","data":"0xa9059cbb0000000000000000000000007cb57b5a97eabe94205c07890be4c1ad31e486a80000000000000000000000000000000000000000000000000000000000000001"}],"id":34}' http://localhost:8889
> {"jsonrpc":"2.0","id":34,"error":{"code":-32000,"message":"gas required exceeds allowance or always failing transaction"}}
> ```
> 
> Unfortunately even running parity with `--logging rpc=trace` doesn't give much more information:
> ```
> 2019-02-06 01:38:24 UTC jsonrpc-eventloop-2 TRACE rpc  Request: {"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"to":"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48","data":"0xa9059cbb0000000000000000000000007cb57b5a97eabe94205c07890be4c1ad31e486a80000000000000000000000000000000000000000000000000000000000000001"}],"id":34}.
> 2019-02-06 01:38:24 UTC jsonrpc-eventloop-2 DEBUG rpc  [Some(Num(34))] Took 130ms
> 2019-02-06 01:38:24 UTC jsonrpc-eventloop-2 DEBUG rpc  Response: {"jsonrpc":"2.0","error":{"code":-32016,"message":"The execution failed due to an exception."},"id":34}.
> ```

**Comment by ZumZoom** [comment]
@jmooo I do not think that this is relevant. The problem is that call to `estimateGas` produces not enough gas for call to succeed. In the issue that you've linked call to `estimateGas` produces expected result of "always failing transaction".

Surely it is bad that neither geth nor parity still do not provide you any exception information but at least they both do work correctly in those examples. Not the case here.

**Comment by k06a** [comment]
But it is still the case if no-one fixed it.

**Comment by holiman** [comment]
Previously, parity used `0x00...0` as `from` if not explicitly set by caller, whereas geth used whatever backend coinbase it could find. So there would be differences in execution when `from` was not specified. 

Nowadays, geth also uses `0x00` address as `from`, but also sets the gasPrice to zero -- to not cause failures due to the zero-account not having enough funds.

**Comment by karalabe** [comment]
I can repro this:

A call to the old contract: https://ropsten.etherscan.io/tx/0x824fdac2a133a4a575f581acf7185fe67db837c0acec3dce5f9c29e7b481542c

A call to the new contract: https://ropsten.etherscan.io/tx/0x08161e0c09542d508453ec8fa217318179e325bc1e0fd20d93bb80cf3f1afcb7

Both used internal gas estimation former failed, latter succeeded.

**Comment by karalabe** [comment]
I think the gas estimation is ok.

If we look at the failing tx's opcodes: https://ropsten.etherscan.io/vmtrace?txhash=0x824fdac2a133a4a575f581acf7185fe67db837c0acec3dce5f9c29e7b481542c, the OOG is in an internal call, but the outer call continues, so this means Solidity explicitly swallowed the internal failure. From Geth's perspective, the (outer) call succeeded.

Actually, even Etherscan says that even though there were internal failures, the transaction itself succeeded.

**Comment by karalabe** [comment]
So this means that between Solidity 4 and Solidity 5, they've added an implicit check so that if an internal call fails and it's not explicitly ignored, it will implicitly propagate the failure.

All in all works as expected. Gas estimation can only ever take the outermost call into account, since internal ones could always be attacked by malicious contracts. It's up to the contract itself to handle internal failures in however it sees fit.

**Comment by ZumZoom** [comment]
Just to confirm https://ropsten.etherscan.io/address/0xc85ffab92af69815ecb0085873009bc0d4532ae1
Adding explicit require results in correct estimation.
