### ISSUE TITLE
geth copydb panic

### ISSUE THREAD

**Issue by huangyg11** [ethereum/go-ethereum#18525]
#### System information

Geth version: 1.8.21-stable
OS & Version: Linux
Commit hash : 9dc5d1a915ac0e0bd8429d6ac41df50eec91de5f

#### Expected behaviour

copy db start normally

#### Actual behaviour

throw panic in line eth/downloader/statesync.go:313. 

I have debug it, and find `s.d.dropPeer` is nil. 

There exists two problems
- why dropPeer is nil
- why will it timeout even copy db from local dir.

I further trace it down, and find when copydb started, it get the head of number 7123380, while in geth console with command `eth.blocknumber`, I get 7123313. So when it want to fetch sate trie for block 7123380, it get a nil state, trigering the timeout case.

As a workround, I modify the function head in eth/downloader/fakepeer.go:47 to return a fix head, and now the copydb start without problem.

```
func (p *FakePeer) Head() (common.Hash, *big.Int) {
	bytes, _ := hexutil.Decode("0x0aa3dd35777cdffd591d18f6c54bd9910524d4353c13df49c639ca21ccc9881c")
	return common.BytesToHash(bytes), big.NewInt(int64(7123313))

}
```

#### Backtrace

````
runtime error: invalid memory address or nil pointer dereference in line eth/downloader/statesync.go:313
````

**Comment by holiman** [comment]
Interesting. If you start geth regularly, or e.g. with `--maxpeers 0 --nodiscover`, could you provide the first few lines of log output, where it tells you about your sync progress? (latest block, latest full block etc)

**Comment by huangyg11** [comment]
Unfortunately, I have synced the node to the latest block last night. And invoke copydb again, it works normally this time. Can't reproduce it with the chaindata dir changed.

**Comment by huangyg11** [comment]
The problem appeared again.

`geth --datadir=/data/new --maxpeers 0 --nodiscover console`

> INFO [02-26|16:40:17.157] Maximum peer count                       ETH=0 LES=0 total=0
> INFO [02-26|16:40:17.158] Starting peer-to-peer node               instance=Geth/v1.8.23-stable-c9427004/linux-amd64/go1.10.4
> INFO [02-26|16:40:17.158] Allocated cache and file handles         database=/data/new/geth/chaindata cache=512 handles=32767
> INFO [02-26|16:40:18.182] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000  ConstantinopleFix: 7280000 Engine: ethash}"
> INFO [02-26|16:40:18.182] Disk storage enabled for ethash caches   dir=/data/new/geth/ethash count=3
> INFO [02-26|16:40:18.182] Disk storage enabled for ethash DAGs     dir=/root/.ethash         count=2
> INFO [02-26|16:40:18.182] Initialising Ethereum protocol           versions="[63 62]" network=1
> WARN [02-26|16:40:18.235] Head state missing, repairing chain      number=7264790 hash=dbcb9d…12762f
> INFO [02-26|16:40:18.235] Rewound blockchain to past state         number=7264789 hash=da3b77…360516
> INFO [02-26|16:40:18.235] Loaded most recent local header          number=7264790 hash=dbcb9d…12762f td=9249857915655605657403 age=1d2h39m
> INFO [02-26|16:40:18.235] Loaded most recent local full block      number=7264789 hash=da3b77…360516 td=9249854846983481846690 age=1d2h40m
> INFO [02-26|16:40:18.235] Loaded most recent local fast block      number=7264790 hash=dbcb9d…12762f td=9249857915655605657403 age=1d2h39m
> INFO [02-26|16:40:18.236] Loaded local transaction journal         transactions=0 dropped=0
> INFO [02-26|16:40:18.236] Regenerated local transaction journal    transactions=0 accounts=0
> WARN [02-26|16:40:18.236] Blockchain not empty, fast sync disabled
> INFO [02-26|16:40:18.250] New local node record                    seq=3 id=f92b899c67eb3fe3 ip=127.0.0.1 udp=0 tcp=30303
> INFO [02-26|16:40:18.250] Started P2P networking                   
> INFO [02-26|16:40:18.251] IPC endpoint opened                      url=/data/new/geth.ipc

it says head state missing(7264790) and rewound to past state(7264789), but it seems not persist the rewounding result. So if i exit and run again, it output the same result(missing 7264790 and rewounding to 7264789  again).

If I run copy db in this state, the copydb think the local peer head is 7264790, and try to get the state(7264790) which is missing, triggering the nil exception


`geth --datadir=/data/new2 --verbosity=5  copydb --cache=1024 /data/new/geth/chaindata/`

> DEBUG[02-26|16:44:22.691] Sanitizing Go's GC trigger               percent=100
> INFO [02-26|16:44:22.692] Maximum peer count                       ETH=25 LES=0 total=25
> DEBUG[02-26|16:44:22.692] FS scan times                            list=38.963µs set=849ns diff=1.084µs
> TRACE[02-26|16:44:22.692] Started watching keystore folder         path=/data/new2/keystore
> INFO [02-26|16:44:22.693] Allocated cache and file handles         database=/data/new2/geth/chaindata cache=512 handles=32767
> INFO [02-26|16:44:22.707] Disk storage enabled for ethash caches   dir=/data/new2/geth/ethash count=3
> INFO [02-26|16:44:22.707] Disk storage enabled for ethash DAGs     dir=/root/.ethash          count=2
> INFO [02-26|16:44:22.770] Loaded most recent local header          number=0 hash=d4e567…cb8fa3 td=17179869184 age=49y10mo1w
> INFO [02-26|16:44:22.770] Loaded most recent local full block      number=0 hash=d4e567…cb8fa3 td=17179869184 age=49y10mo1w
> INFO [02-26|16:44:22.770] Loaded most recent local fast block      number=0 hash=d4e567…cb8fa3 td=17179869184 age=49y10mo1w
> INFO [02-26|16:44:22.770] Allocated cache and file handles         database=/data/new/geth/chaindata/ cache=1024 handles=256
> DEBUG[02-26|16:44:22.770] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
> TRACE[02-26|16:44:23.721] Registering sync peer                    peer=local
> INFO [02-26|16:44:23.721] Block synchronisation started
> DEBUG[02-26|16:44:23.721] Synchronising with the network           peer=local eth=63 head=dbcb9d…12762f td=9249857915655605657403 mode=fast
> DEBUG[02-26|16:44:23.721] Retrieving remote chain height           peer=local
> DEBUG[02-26|16:44:23.721] Remote head header identified            peer=local number=7264790 hash=dbcb9d…12762f
> DEBUG[02-26|16:44:23.721] Looking for common ancestor              peer=local local=0 remote=7264790
> TRACE[02-26|16:44:23.721] Span searching for common ancestor       peer=local count=12 from=7264613 skip=15
> TRACE[02-26|16:44:23.722] Binary searching for common ancestor     peer=local start=0 end=7264790
> DEBUG[02-26|16:44:23.725] Found common ancestor                    peer=local number=0       hash=000000…000000
> DEBUG[02-26|16:44:23.725] Downloading block bodies                 origin=1
> DEBUG[02-26|16:44:23.725] Downloading transaction receipts         origin=1
> TRACE[02-26|16:44:23.725] Requesting new batch of data             peer=local type=state count=1
> DEBUG[02-26|16:44:23.725] Directing header downloads               peer=local origin=1
> TRACE[02-26|16:44:23.725] Received node data response              peer=local count=0  dropped=false timeout=true
> WARN [02-26|16:44:23.726] Stalling state sync, dropping peer       peer=local
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa53b07]
> 
> goroutine 40 [running]:
> github.com/ethereum/go-ethereum/eth/downloader.(*stateSync).loop(0xc420316c40, 0x0, 0x0)
>         /build/ethereum-fWxIHg/ethereum-1.8.23+build17682+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/statesync.go:313 +0x627
> github.com/ethereum/go-ethereum/eth/downloader.(*stateSync).run(0xc420316c40)
>         /build/ethereum-fWxIHg/ethereum-1.8.23+build17682+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/statesync.go:255 +0x2b
> created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).runStateSync
>         /build/ethereum-fWxIHg/ethereum-1.8.23+build17682+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/statesync.go:106 +0x10c

**Comment by huangyg11** [comment]
my workround is tweak Head() in fakepeer.go to return fix header ( given by cmd arg ). 

`geth --datadir=/data/new2  copydb --cache=1024 /data/new/geth/chaindata/ 7264789`  works
