### ISSUE TITLE
Blockchain fully synced, balance still shows 0 

### ISSUE THREAD

**Issue by uuacar** [ethereum/go-ethereum#18522]
Hi there,

We do see following issues related to this scenario:

[https://github.com/ethereum/go-ethereum/issues/14676](url)
[https://github.com/ethereum/go-ethereum/issues/14689](url)
[https://github.com/ethereum/go-ethereum/issues/18507](url)
[https://github.com/ethereum/go-ethereum/issues/16282](url)

However, we couldnot figure out why the balance of our account still shows 0. Our local geth node seems to be synched %99 percent (84 blocks difference). We do see the transaction in the local geth node but the balance still shows zero. 

Your comments will be appreciated, thanks. 

#### System information

Geth version: `1.8.21-stable-9dc5d1a9`
OS & Version: Windows

#### Expected behaviour

> eth.getBalance('0x80c752a410c23d34c12806bae68165721205e1f3')
Above function should return 0.001 

#### Actual behaviour

Local Synch Status of Rinkeby Testnet.

> eth.syncing
{
  currentBlock: 3751470,
  highestBlock: 3751554,
  knownStates: 29371245,
  pulledStates: 29367955,
  startingBlock: 0
}

Our transaction is visible on geth.

```json
`> eth.getTransactionFromBlock('3748773', 1)
{
  blockHash: "0x610035ef62e6fffc646bc6be9c12d211c50929af9f87193980bc7209b0f0cb51
",
  blockNumber: 3748773,
  from: "0x08d13d527a19fc5203d2ce2e57c59036d6cafb6e",
  gas: 21000,
  gasPrice: 6000000000,
  hash: "0xfdac6aa23c65c8742eb303c0d85bcdd3018c40da1e234c59f1fb8b4f57b418d6",
  input: "0x",
  nonce: 22,
  r: "0x2bfb158db42ddf880be56d1330a6a67f41baa5fd1c45d69e19bbfbb40b46b4ca",
  s: "0x54823ab0feb27528fcf7fb8a631c4337835f48e15cf4a1ef49a1aaf0e1da7745",
  to: "**0x80c752a410c23d34c12806bae68165721205e1f3**",
  transactionIndex: 1,
  v: "0x2b",
  value: **1000000000000000**
}`
```

However getBalance returns 0.

`> eth.getBalance('0x80c752a410c23d34c12806bae68165721205e1f3')
> 0   `

Last Block returns 0. 

`> eth.getBlock("latest").number
0
`
#### Steps to reproduce the behaviour

1. Start local geth node with following command
 `geth --rinkeby --rpc --rpcaddr "127.0.0.1" --datadir "c/test" console 2>> geth-personal.log`
2. personal.newAccount()
3. eth.accounts
`> eth.accounts
["**0x80c752a410c23d34c12806bae68165721205e1f3**", "0xe073ddffdb30439b696cf54ec2e1a7
42d8ea1195"]`
4. Transfer 0.001 ETH to **0x80c752a410c23d34c12806bae68165721205e1f3**
5. Check Block Number (3748773) received in local geth node
6. eth.getTransactionFromBlock('3748773', 1)  We do see the transaction on local geth. 
7. eth.getBalance('0x80c752a410c23d34c12806bae68165721205e1f3') returns 0.

Ugur ACAR 
Blockchain Architect

**Comment by holiman** [comment]
` %99 percent ` synced, in the case of a fast-synced, is not a correct estimate. What you're seeing is that all blocks up to the so called pivot point has been downloaded (the pivot point is at least 64 blocks behind head, and the head moves forward). Downloading all blocks is fairly quick, what takes time is downloading all the state entries. That's a much longer running job, and until you have the complete state, you will not get accurate information out of the client.  

You need to wait until the sync is 100% complete, or at least until the fast-sync is complete up to the pivot point: after that it will import the remaining (hundred or so) blocks that came after the pivot point.

**Comment by uuacar** [comment]
Thanks for the comment, after two days synch process was completed with 100%. Now we can see the balance. 

regards
Ugur

**Comment by liuhuanhui** [comment]
#19652
