### ISSUE TITLE
Use different default port for RPC

### ISSUE THREAD

**Issue by WeMeetAgain** [ethereum/go-ethereum#186]
Currently, RPC defaults to port 8080, which is a widely used port for alternate/non-root web servers.
Ethereum should choose a different port as the default.
some relevant examples:
bitcoind - 8332
btcd - 8334
namecoin - 8336
bitmessage - 8444

**Comment by tgerring** [comment]
@obscuren Any opinion on this? We can roll this change into PR #263

**Comment by tgerring** [comment]
Default port is now 8545 with change merged into develop branch.
