### ISSUE TITLE
geth account update fail

### ISSUE THREAD

**Issue by chervol** [ethereum/go-ethereum#1860]
Can't update three old Olympic keys pending for reward. They are encrypted with aes-128-cbc still and have trailing line break in password. Neither providing proper password file nor entering password manually (adding '\n') does not work with geth, while it works in console mode with unlockAccount().
After hardcoding password and recompiling geth it reports that the account is unlocked and prompts for new password, takes it, but does not generate fresh key file.  Suggestions?

**Comment by karalabe** [comment]
I'd just create a new account and move the funds over there, then you can drop the Olympic addresses altogether. AFAIK, there's no upgrade mechanism to convert an old key into a new one, and I'm not sure it's really worth it.

**Comment by zelig** [comment]
closing as no further complaint consider OP solved the issue some way or other
