### ISSUE TITLE
can't install geth on windows using chocolatey

### ISSUE THREAD

**Issue by ellisonch** [ethereum/go-ethereum#1874]
I have chocolatey 0.9.9.10 (just installed in order to install geth).  When I follow the instructions on https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows and run ```choco install geth-latest```, i get the following log:

```
choco install geth-latest

Installing the following packages:
geth-latest
By installing you accept licenses for the packages.
geth-latest not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - geth-latest
``` 

I get the same error if I try to install geth-stable.  The mentioned .log says the same thing as the console output.

Let me know if you need any more info.

**Comment by tgerring** [comment]
Because the Chocolatey package maintainers have not approved this package, you must explicitly specify a version when installing, for example:

`choco install geth-latest -version 1.1.1.0`

**Comment by ellisonch** [comment]
Thanks!  It works.  It might be helpful to mention this in the instructions.
