### ISSUE TITLE
Geth would not close!!!

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#1882]
Cannot get the Geth to shutdown as I usually do. Tried control-c, tried exit command, tried control-d.
I had to shut it down by killing the process. Waited a long time could not be more patient.

 Geth/v1.2.2/windows/go1.4.2

I1006 12:53:46.182983    2860 cmd.go:140] Already shutting down, please be patient.
I1006 12:53:46.182983    2860 cmd.go:141] Interrupt 9 more times to induce panic.
I1006 12:53:46.758987    2860 cmd.go:140] Already shutting down, please be patient.
I1006 12:53:46.758987    2860 cmd.go:141] Interrupt 8 more times to induce panic.
I1006 12:53:50.794556    2860

**Comment by fjl** [comment]
If it happens again, please press control+c until it exits and capture the output.

**Comment by rfikki** [comment]
Will do. Thanks.

**Comment by obscuren** [comment]
Closing in favour of https://github.com/ethereum/go-ethereum/issues/1892
