### ISSUE TITLE
Allow geth to run as a daemon

### ISSUE THREAD

**Issue by tgerring** [ethereum/go-ethereum#1893]
> service will install / un-install, start / stop, and run a program as a service (daemon). Currently supports Windows XP+, Linux/(systemd | Upstart | SysV), and OSX/Launchd.

https://github.com/kardianos/service

**Comment by bas-vk** [comment]
Question, for user interaction we have plans to integrate a GUI confirmation window. Some (maybe all) of these libs require the GUI go-routine to be the main go-routine (at least go-qml requires this on OSX). Does this lib have similar requirements?

**Comment by tgerring** [comment]
I haven't seen anything that talks about any restrictions about running on main thread. It seems that the main functionality provided by this code is integration into the various service managers for major platforms, with a simple Start() and Stop() method needing to be defined.

**Comment by oliversk** [comment]
This is a neat idea. Right now every time a sever experiences a disconnect geth will stop working, a restart is then required. As a service you could allow geth to check itself (whether its running correctly) and when its not working restart itself automatically

**Comment by simonjanin** [comment]
@oliversk  +1 This would be particularly useful for my Raspberry Pi full node running geth. Geth just crashes or disconnects sometimes. So this would solve it neatly.
When we switch to PoS, this will be all the more relevant.

**Comment by actuallymentor** [comment]
@tgerring Could you elaborate a little on that repo? As a non go programmer the readme tells me nothing on how to implement.

@simonjanin I run into this exact issue (also on a pi), getting geth started as an auto-restarting service is a nightmare.

**Comment by simon66** [comment]
Whats the status on this issue? Does anyone know if it's been fixed?
