### ISSUE TITLE
how to import an account with keystore file and password?

### ISSUE THREAD

**Issue by jjzjx118** [ethereum/go-ethereum#18948]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.9.0`
OS & Version: iOS

#### Expected behaviour
I need to import an account(GethAccount) with a given keystorefile(not encryped) and password.

#### Actual behaviour
I didn't find any method to achieve that

please help me.  the most similar metho is 
`- (GethAccount*)importKey:(NSData*)keyJSON passphrase:(NSString*)passphrase newPassphrase:(NSString*)newPassphrase error:(NSError**)error;`

but I don't know how to make a keyJSON , I think it's not the origin keystore file.  the NSData shuold came frome the below method:
`- (NSData*)exportKey:(GethAccount*)account passphrase:(NSString*)passphrase newPassphrase:(NSString*)newPassphrase error:(NSError**)error;`

but I don't have an exist GethAccount . 

So it's there a way to achieve my purpose？

**Comment by holiman** [comment]
There's really no such thing as an un-encrypted keystore file. 
A keystore file, in 'ethereum' nomenclature is a `json` file (so not encrypted at envelope-level) which contains the private key in an encrypted format, and the encryption parameters varies a bit. 

If that is what you have, it should just be a matter of dropping the file into the keystore folder, which I think is

- Mac: ~/Library/Ethereum/keystore
- Linux: ~/.ethereum/keystore
- Windows: %APPDATA%\Ethereum/keystore
