### ISSUE TITLE
How do i know status of geth sync process ?

### ISSUE THREAD

**Issue by CruiseMan** [ethereum/go-ethereum#18946]
Can some one explain or direct to resource where i can learn more about `geth` sync output log status. Looking at this screen hard to tell at what block its currently, and what exactly goin on ?. Please. Can we make output more verbose and simple to read ?.
<img width="1909" alt="screenshot 2019-01-26 15 01 04" src="https://user-images.githubusercontent.com/15807643/51793806-6161bc80-217b-11e9-9f3c-2553c0308e05.png">

**Comment by ielashi** [comment]
You can monitor the syncing progress by running `geth attach`, then running `eth.syncing`. See https://ethereum.stackexchange.com/questions/11233/how-to-check-my-sync-status-on-geth-1-5-5-raspberry-pi-3

**Comment by xiaods** [comment]
@ielashi 's comments is correct answer.
