### ISSUE TITLE
Memory leak due to big.Int(rlp encode/decode)

### ISSUE THREAD

**Issue by bishaoqing** [ethereum/go-ethereum#18954]
Geth version: 1.8.9
OS & Version: Windows + Linux

Hello, I build a private block-chain in my AWS server,and change some codes to enable a large number of txs, but i find that memory kept growing, it was 30 MB at the beginning, but after 30 mins, it grown to 15 GB, and then crushed.

Here is my flame graph of the heap(Because of the word limit,i save the flame graph in pastebin)
[https://pastebin.com/UjmWZ8K1](url)

1st, paste the url into the browser
2nd, save all the codes as an SVG file
3rd, open the SVG file in any browser

And then, you will see the flame graph about the mem leak i met

**Comment by hadv** [comment]
Yeah, I have the same problem on private chain with 10 thousand tnx https://github.com/ethereum/go-ethereum/issues/17450#issuecomment-457842978

**Comment by bishaoqing** [comment]
@hadv i found it could be caused by the 'blockCache'(blockchain.go), it seems something hold the references of the big.Int objects (or say txs) and causes the memory assigned to them cann't be freed,and i guess it's because of block caching,and then i change the code below:
`const (
	bodyCacheLimit      = 256
	blockCacheLimit     = 256
	receiptsCacheLimit  = 32
	maxFutureBlocks     = 256
	maxTimeFutureBlocks = 30
	badBlockLimit       = 10
	triesInMemory       = 128

	// BlockChainVersion ensures that an incompatible database forces a resync from scratch.
	BlockChainVersion = 3
)`

to

`const (
	bodyCacheLimit      = 1
	blockCacheLimit     = 1
	receiptsCacheLimit  = 1
	maxFutureBlocks     = 1
	maxTimeFutureBlocks = 1
	badBlockLimit       = 1
	triesInMemory       = 1

	// BlockChainVersion ensures that an incompatible database forces a resync from scratch.
	BlockChainVersion = 3
)`

And then i run geth again, after about 1 hour,memory up to  4GB and don't increase any more.

**Comment by hadv** [comment]
yeah, if we reduce cache then i might be better. But it seems that there's goroutine leak on feed.Send() event

https://github.com/ethereum/go-ethereum/issues/17450#issuecomment-458388801

**Comment by fjl** [comment]
Closing this because it's not related to RLP decoding. It's just the memory profile showing that big.Ints were allocated during decoding.
