### ISSUE TITLE
golang.org/x/crypto/sha3 dependency broken when importing geth via Go modules

### ISSUE THREAD

**Issue by brynbellomy** [ethereum/go-ethereum#18958]
#### System information

Geth version: 1.8.21
OS & Version: Ubuntu 18.04.  Doesn't matter though, it's a dependency issue.
Commit hash : 9dc5d1a915ac0e0bd8429d6ac41df50eec91de5f

#### Expected behaviour

Geth compiles in a project that uses Go modules.

#### Actual behaviour

Geth prevents the entire project from compiling.  The compiler complains that `sha3.NewLegacyKeccak512` does not exist.

#### Steps to reproduce the behaviour

1. I try to import Geth into another project so I don't have to reimplement Ethereum just to use some of the built-in helpers for smart contract communication, etc.
2. Go adds geth 1.8.21 to my `go.mod`.
3. Geth fails to compile because of the new golang.org/x/crypto/sha3 dependency.  It complains that `sha3.NewLegacyKeccak512` does not exist.

#### Backtrace

It's not a runtime issue.

**Comment by karalabe** [comment]
Please use a new version of `golang.org/x/crypto/sha3`, which has the mentioned `NewLegacyKeccak512` method.
