### ISSUE TITLE
Spelling mistake in ReadMe

### ISSUE THREAD

**Issue by Justbeingjustin** [ethereum/go-ethereum#18965]
The word 'entrypoint' should actually be 'entry point'.

Currently:

| Command    | Description |
|:----------:|-------------|
| `swarm`    | Swarm daemon and tools. This is the entrypoint for the Swarm network. `swarm --help` for command line options and subcommands. See [Swarm README](https://github.com/ethereum/go-ethereum/tree/master/swarm) for more information. |

Needs to be:

| Command    | Description |
|:----------:|-------------|
| `swarm`    | Swarm daemon and tools. This is the entry point for the Swarm network. `swarm --help` for command line options and subcommands. See [Swarm README](https://github.com/ethereum/go-ethereum/tree/master/swarm) for more information. |

**Comment by ligi** [comment]
thanks!

**Comment by Justbeingjustin** [comment]
@ligi that was fast.
