### ISSUE TITLE
Why block with txs interrupt the empty block

### ISSUE THREAD

**Issue by friends110110** [ethereum/go-ethereum#18960]
When I watch the file work.go ,the method commitNewWork, fragments 
```
if !noempty {
			// Create an empty block based on temporary copied state for sealing in advance without waiting block
			// execution finished.
			w.commit(uncles, nil, false, tstart)
		}

	// Fill the block with all available pending transactions.
	pending, err := w.eth.TxPool().Pending()
	if err != nil {
		log.Error("Failed to fetch pending transactions", "err", err)
		return
	}
	// Short circuit if there is no available pending transactions
	if len(pending) == 0 {
		w.updateSnapshot()
		return
	}
	// Split the pending transactions into locals and remotes
	localTxs, remoteTxs := make(map[common.Address]types.Transactions), pending
	for _, account := range w.eth.TxPool().Locals() {
		if txs := remoteTxs[account]; len(txs) > 0 {
			delete(remoteTxs, account)
			localTxs[account] = txs
		}
	}
	if len(localTxs) > 0 {
		txs := types.NewTransactionsByPriceAndNonce(w.current.signer, localTxs)
		if w.commitTransactions(txs, w.coinbase, interrupt) {
			return
		}
	}
	if len(remoteTxs) > 0 {
		txs := types.NewTransactionsByPriceAndNonce(w.current.signer, remoteTxs)
		if w.commitTransactions(txs, w.coinbase, interrupt) {
			return
		}
	}
	w.commit(uncles, w.fullTaskHook, true, tstart)
```

Why block with txs interrupt the empty block?
in my opinion,  commit the block with txs first,  commit empty if no block with txs,
so the code should be transfer to the **defer** , and the empty could not interrupt the block with txs when same block num .
```
emptyFun := func() {
		if !noempty {
			// Create an empty block based on temporary copied state for sealing in advance without waiting block
			// execution finished.
			w.commit(uncles, nil, false, tstart)
		}
	}
defer emptyFun()

```

**Comment by rjl493456442** [comment]
I guess your question is: **Why is it necessary to submit an empty block first in commitNewWork?**

In order to submit a new mining work, geth has to (1) create empty block (2) fetch a batch of pending transactions from txpool and apply them. While the step(2) normally could take 100ms or 200ms in the mainnet. In order to save this part of time, we submit an empty block first. 

If miner finds a right nonce during this time, the geth node will broadcast an empty block (the probability of this event is small, but it is also an optimized way to improve mining efficiency). Otherwise the geth node will swap the empty block with a full block and notify all miners to update the mining task.

**Comment by friends110110** [comment]
@rjl493456442 thank your, your main reason is save the time(100ms or 200ms) and keep the benefits. 
When we transform the consensus to pbft or others, if the empty block is generated and be broadcasted  in 10ms or less time, then the block with txs(100ms or 200ms) will never interrupt the empty block, so it will never consume the txs which in txpool pending ?

**Comment by rjl493456442** [comment]
Yes. Once the geth node broadcasts the empty block, the local node will also receive a `NewHeadEvent` and drop the current full block(could be a semi-finished full block) silently.

If you want to customize the codebase, you can disable the empty block mechanism, it should be easy.

**Comment by rjl493456442** [comment]
Oh, I think you are talking about the **chain fork**.

Yes, in the ethereum, both of the consensus engine **ethash** and **clique** are not instant finalized. They are allowed to have several blocks with the same block height. Some blocks will become canonical blocks while the other will become uncle blocks.

If you are using some BFT based consensus algorithm, probably you have to do some changes.
