### ISSUE TITLE
Synchronization of Test Networks

### ISSUE THREAD

**Issue by abc114437** [ethereum/go-ethereum#18961]
![image](https://user-images.githubusercontent.com/22112598/51897738-5eb8ce80-23ea-11e9-8da0-11182b61156c.png)
When synchronization occurs, there will always be failures, resulting in dozens of blocks different from the high block every day, which can not be synchronized every day.

windows,   geth version:1.8.2

**Comment by ligi** [comment]
please use the latest geth version. Testnets like rinkeby and ropsten had the constantinople hardfork - and I am pretty sure this is the problem here.

**Comment by jonnyhsy** [comment]
What I'm seeing is "Synchronisation failed, dropping peer    peer=56483dbe3073c572 err="retrieved hash chain is invalid"", with my geth version `Geth/v1.8.22-stable-7fa3509e/linux-amd64/go1.10.4` on rinkeby

**Comment by pooleja** [comment]
Confirmed I am seeing this on Ropsten as well.  It seems to halt the entire sync.  I have multiple nodes that are hitting this.
VERSION:
   1.8.22-stable-7fa3509e

```
Feb 04 23:22:04 ip-10-0-79-182 geth[1073]: INFO [02-04|23:22:04.059] Imported new state entries               count=330  elapsed=2.254ms   processed=66761907 pending=0     retry=0   duplicate=0 unexpected=0
Feb 04 23:22:04 ip-10-0-79-182 geth[1073]: INFO [02-04|23:22:04.059] Imported new block receipts              count=0    elapsed=42.212µs  number=4956185 hash=fed90b…adef71 age=3h10m49s  size=0.00B    ignored=1
Feb 04 23:22:04 ip-10-0-79-182 geth[1073]: INFO [02-04|23:22:04.059] Committed new head block                 number=4956185 hash=fed90b…adef71
Feb 04 23:22:04 ip-10-0-79-182 geth[1073]: WARN [02-04|23:22:04.062] Rolled back headers                      count=2    header=4956250->4956248 fast=4956185->4956185 block=4956185->4956185
Feb 04 23:22:04 ip-10-0-79-182 geth[1073]: WARN [02-04|23:22:04.063] Synchronisation failed, dropping peer    peer=a051b87c7195c2c1 err="retrieved hash chain is invalid"
```

**Comment by pooleja** [comment]
Confirmed I am seeing this on Ropsten as well.  It seems to halt the entire sync.  I have multiple nodes that are hitting this.
VERSION:
   1.8.22-stable-7fa3509e

```
Feb 04 23:22:04 ip-10-0-79-XXX geth[1073]: INFO [02-04|23:22:04.059] Imported new state entries               count=330  elapsed=2.254ms   processed=66761907 pending=0     retry=0   duplicate=0 unexpected=0
Feb 04 23:22:04 ip-10-0-79-XXX geth[1073]: INFO [02-04|23:22:04.059] Imported new block receipts              count=0    elapsed=42.212µs  number=4956185 hash=fed90b…adef71 age=3h10m49s  size=0.00B    ignored=1
Feb 04 23:22:04 ip-10-0-79-XXX geth[1073]: INFO [02-04|23:22:04.059] Committed new head block                 number=4956185 hash=fed90b…adef71
Feb 04 23:22:04 ip-10-0-79-XXX geth[1073]: WARN [02-04|23:22:04.062] Rolled back headers                      count=2    header=4956250->4956248 fast=4956185->4956185 block=4956185->4956185
Feb 04 23:22:04 ip-10-0-79-XXX geth[1073]: WARN [02-04|23:22:04.063] Synchronisation failed, dropping peer    peer=a051b87c7195c2c1 err="retrieved hash chain is invalid"
```

**Comment by alexkvak** [comment]
@ligi we've checked — it's reproducing on new 1.8.22-stable-7fa3509e version

**Comment by ligi** [comment]
Is the sync stopping for you at this point? I also saw such messages once (`Synchronisation failed, dropping peer`) - but then sync completed with other peers - think the reason was just some bad peers. That said - currently just running a goerli node - and not seeing it there.
