### ISSUE TITLE
eth_estimateGas fails if provided with gas between minimum and required

### ISSUE THREAD

**Issue by spalladino** [ethereum/go-ethereum#18973]
#### System information

```
> web3.eth.getNodeInfo()
'Geth/v1.8.21-stable-9dc5d1a9/linux-amd64/go1.10.4' (on Rinkeby)
```

#### Expected behaviour

Running `estimateGas` with a transaction for deploying a contract (I used ERC721 as an example) should return a value independent of the `gas` parameter provided.

#### Actual behaviour

`estimateGas` fails if a `gas` parameter is added to the call with a value between 21K and the gas required.

#### Steps to reproduce the behaviour

All the calls below work fine if run on Parity.

<details>
<pre>
const data = '0x608060405234801561001057600080fd5b50613b05806100206000396000f3fe608060405260043610610180576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806301ffc9a71461018557806306fdde03146101f7578063081812fc14610287578063095ea7b31461030257806318160ddd1461035d57806323b872dd146103885780632f745c59146104035780633f4ba83a1461047257806342842e0e1461048957806346fbf68e146105045780634cd88b761461056d5780634f6ccce7146106cc57806350bb4e7f1461071b5780635c975abb146108255780636352211e146108545780636ef8d66d146108cf57806370a08231146108e65780638129fc1c1461094b57806382dc1ec4146109625780638456cb59146109b357806395d89b41146109ca578063983b2d5614610a5a5780639865027514610aab578063a22cb46514610ac2578063aa271e1a14610b1f578063b88d4fde14610b88578063c4d66de814610c9a578063c87b56dd14610ceb578063d94cc0e014610d9f578063e985e9c514611026575b600080fd5b34801561019157600080fd5b506101dd600480360360208110156101a857600080fd5b8101908080357bffffffffffffffffffffffffffffffffffffffffffffffffffffffff191690602001909291905050506110af565b604051808215151515815260200191505060405180910390f35b34801561020357600080fd5b5061020c611117565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561024c578082015181840152602081019050610231565b50505050905090810190601f1680156102795780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34801561029357600080fd5b506102c0600480360360208110156102aa57600080fd5b81019080803590602001909291905050506111b9565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561030e57600080fd5b5061035b6004803603604081101561032557600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291908035906020019092919050505061120a565b005b34801561036957600080fd5b50610372611235565b6040518082815260200191505060405180910390f35b34801561039457600080fd5b50610401600480360360608110156103ab57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190505050611242565b005b34801561040f57600080fd5b5061045c6004803603604081101561042657600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291908035906020019092919050505061126f565b6040518082815260200191505060405180910390f35b34801561047e57600080fd5b506104876112e6565b005b34801561049557600080fd5b50610502600480360360608110156104ac57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190505050611397565b005b34801561051057600080fd5b506105536004803603602081101561052757600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291905050506113b8565b604051808215151515815260200191505060405180910390f35b34801561057957600080fd5b506106ca6004803603604081101561059057600080fd5b81019080803590602001906401000000008111156105ad57600080fd5b8201836020820111156105bf57600080fd5b803590602001918460018302840111640100000000831117156105e157600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f8201169050808301925050505050505091929192908035906020019064010000000081111561064457600080fd5b82018360208201111561065657600080fd5b8035906020019184600183028401116401000000008311171561067857600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f8201169050808301925050505050505091929192905050506113d6565b005b3480156106d857600080fd5b50610705600480360360208110156106ef57600080fd5b810190808035906020019092919050505061157a565b6040518082815260200191505060405180910390f35b34801561072757600080fd5b5061080b6004803603606081101561073e57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001909291908035906020019064010000000081111561078557600080fd5b82018360208201111561079757600080fd5b803590602001918460018302840111640100000000831117156107b957600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f8201169050808301925050505050505091929192905050506115b2565b604051808215151515815260200191505060405180910390f35b34801561083157600080fd5b5061083a6115e7565b604051808215151515815260200191505060405180910390f35b34801561086057600080fd5b5061088d6004803603602081101561087757600080fd5b81019080803590602001909291905050506115ff565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b3480156108db57600080fd5b506108e461167d565b005b3480156108f257600080fd5b506109356004803603602081101561090957600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611688565b6040518082815260200191505060405180910390f35b34801561095757600080fd5b5061096061170c565b005b34801561096e57600080fd5b506109b16004803603602081101561098557600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611880565b005b3480156109bf57600080fd5b506109c86118a0565b005b3480156109d657600080fd5b506109df611952565b6040518080602001828103825283818151815260200191508051906020019080838360005b83811015610a1f578082015181840152602081019050610a04565b50505050905090810190601f168015610a4c5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b348015610a6657600080fd5b50610aa960048036036020811015610a7d57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291905050506119f4565b005b348015610ab757600080fd5b50610ac0611a14565b005b348015610ace57600080fd5b50610b1d60048036036040811015610ae557600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803515159060200190929190505050611a1f565b005b348015610b2b57600080fd5b50610b6e60048036036020811015610b4257600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611a4a565b604051808215151515815260200191505060405180910390f35b348015610b9457600080fd5b50610c9860048036036080811015610bab57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff1690602001909291908035906020019092919080359060200190640100000000811115610c1257600080fd5b820183602082011115610c2457600080fd5b80359060200191846001830284011164010000000083111715610c4657600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290505050611a68565b005b348015610ca657600080fd5b50610ce960048036036020811015610cbd57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611a90565b005b348015610cf757600080fd5b50610d2460048036036020811015610d0e57600080fd5b8101908080359060200190929190505050611be2565b6040518080602001828103825283818151815260200191508051906020019080838360005b83811015610d64578082015181840152602081019050610d49565b50505050905090810190601f168015610d915780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b348015610dab57600080fd5b5061102460048036036080811015610dc257600080fd5b8101908080359060200190640100000000811115610ddf57600080fd5b820183602082011115610df157600080fd5b80359060200191846001830284011164010000000083111715610e1357600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f82011690508083019250505050505050919291929080359060200190640100000000811115610e7657600080fd5b820183602082011115610e8857600080fd5b80359060200191846001830284011164010000000083111715610eaa57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f82011690508083019250505050505050919291929080359060200190640100000000811115610f0d57600080fd5b820183602082011115610f1f57600080fd5b80359060200191846020830284011164010000000083111715610f4157600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f82011690508083019250505050505050919291929080359060200190640100000000811115610fa157600080fd5b820183602082011115610fb357600080fd5b80359060200191846020830284011164010000000083111715610fd557600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f820116905080830192505050505050509192919290505050611cab565b005b34801561103257600080fd5b506110956004803603604081101561104957600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611e98565b604051808215151515815260200191505060405180910390f35b600060336000837bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19167bffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916815260200190815260200160002060009054906101000a900460ff169050919050565b606060d28054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156111af5780601f10611184576101008083540402835291602001916111af565b820191906000526020600020905b81548152906001019060200180831161119257829003601f168201915b5050505050905090565b60006111c482611f2c565b15156111cf57600080fd5b6067600083815260200190815260200160002060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff169050919050565b61019f60009054906101000a900460ff1615151561122757600080fd5b6112318282611f9e565b5050565b6000609e80549050905090565b61019f60009054906101000a900460ff1615151561125f57600080fd5b61126a8383836120e3565b505050565b600061127a83611688565b8210151561128757600080fd5b609c60008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020828154811015156112d357fe5b9060005260206000200154905092915050565b6112ef336113b8565b15156112fa57600080fd5b61019f60009054906101000a900460ff16151561131657600080fd5b600061019f60006101000a81548160ff0219169083151502179055507f5db9ee0a495bf2e6ff9c91a7834c1ba4fdd244a5e8aa4e537bd38aeae4b073aa33604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390a1565b6113b38383836020604051908101604052806000815250611a68565b505050565b60006113cf8261016c61210890919063ffffffff16565b9050919050565b600060019054906101000a900460ff16806113f557506113f461219c565b5b8061140c57506000809054906101000a900460ff16155b15156114a6576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e8152602001807f436f6e747261637420696e7374616e63652068617320616c726561647920626581526020017f656e20696e697469616c697a656400000000000000000000000000000000000081525060400191505060405180910390fd5b60008060019054906101000a900460ff1690506001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055506114f66121ad565b151561150157600080fd5b8260d29080519060200190611517929190613a08565b508160d3908051906020019061152e929190613a08565b5061155b635b5e139f7c0100000000000000000000000000000000000000000000000000000000026121e0565b80600060016101000a81548160ff021916908315150217905550505050565b6000611584611235565b8210151561159157600080fd5b609e828154811015156115a057fe5b90600052602060002001549050919050565b60006115bd33611a4a565b15156115c857600080fd5b6115d2848461229e565b6115dc83836122bf565b600190509392505050565b600061019f60009054906101000a900460ff16905090565b6000806066600084815260200190815260200160002060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff169050600073ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff161415151561167457600080fd5b80915050919050565b611686336122ff565b565b60008073ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff16141515156116c557600080fd5b606860008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020549050919050565b600060019054906101000a900460ff168061172b575061172a61219c565b5b8061174257506000809054906101000a900460ff16155b15156117dc576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e8152602001807f436f6e747261637420696e7374616e63652068617320616c726561647920626581526020017f656e20696e697469616c697a656400000000000000000000000000000000000081525060400191505060405180910390fd5b60008060019054906101000a900460ff1690506001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff02191690831515021790555061182c6121ad565b151561183757600080fd5b61186363780e9d637c0100000000000000000000000000000000000000000000000000000000026121e0565b80600060016101000a81548160ff02191690831515021790555050565b611889336113b8565b151561189457600080fd5b61189d8161235a565b50565b6118a9336113b8565b15156118b457600080fd5b61019f60009054906101000a900460ff161515156118d157600080fd5b600161019f60006101000a81548160ff0219169083151502179055507f62e78cea01bee320cd4e420270b5ea74000d11b0c9f74754ebdbfc544b05a25833604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390a1565b606060d38054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156119ea5780601f106119bf576101008083540402835291602001916119ea565b820191906000526020600020905b8154815290600101906020018083116119cd57829003601f168201915b5050505050905090565b6119fd33611a4a565b1515611a0857600080fd5b611a11816123b5565b50565b611a1d33612410565b565b61019f60009054906101000a900460ff16151515611a3c57600080fd5b611a46828261246b565b5050565b6000611a618261010761210890919063ffffffff16565b9050919050565b611a73848484611242565b611a7f848484846125a7565b1515611a8a57600080fd5b50505050565b600060019054906101000a900460ff1680611aaf5750611aae61219c565b5b80611ac657506000809054906101000a900460ff16155b1515611b60576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e8152602001807f436f6e747261637420696e7374616e63652068617320616c726561647920626581526020017f656e20696e697469616c697a656400000000000000000000000000000000000081525060400191505060405180910390fd5b60008060019054906101000a900460ff1690506001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff021916908315150217905550611bb06121ad565b1515611bbb57600080fd5b611bc4826127ca565b80600060016101000a81548160ff0219169083151502179055505050565b6060611bed82611f2c565b1515611bf857600080fd5b60d460008381526020019081526020016000208054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015611c9f5780601f10611c7457610100808354040283529160200191611c9f565b820191906000526020600020905b815481529060010190602001808311611c8257829003601f168201915b50505050509050919050565b600060019054906101000a900460ff1680611cca5750611cc961219c565b5b80611ce157506000809054906101000a900460ff16155b1515611d7b576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e8152602001807f436f6e747261637420696e7374616e63652068617320616c726561647920626581526020017f656e20696e697469616c697a656400000000000000000000000000000000000081525060400191505060405180910390fd5b60008060019054906101000a900460ff1690506001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff021916908315150217905550611dcb612925565b611dd361170c565b611ddd85856113d6565b611de630612a8e565b611def30612410565b611df830611a90565b611e01306122ff565b60008090505b8351811015611e3b57611e308482815181101515611e2157fe5b906020019060200201516123b5565b806001019050611e07565b5060008090505b8251811015611e7657611e6b8382815181101515611e5c57fe5b9060200190602002015161235a565b806001019050611e42565b5080600060016101000a81548160ff0219169083151502179055505050505050565b6000606960008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900460ff16905092915050565b6000806066600084815260200190815260200160002060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff169050600073ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff161415915050919050565b6000611fa9826115ff565b90508073ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff1614151515611fe657600080fd5b8073ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16148061202657506120258133611e98565b5b151561203157600080fd5b826067600084815260200190815260200160002060006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550818373ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff167f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b92560405160405180910390a4505050565b6120ed3382612bf3565b15156120f857600080fd5b612103838383612c88565b505050565b60008073ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff161415151561214557600080fd5b8260000160008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900460ff16905092915050565b600080303b90506000811491505090565b60006121db6380ac58cd7c0100000000000000000000000000000000000000000000000000000000026110af565b905090565b63ffffffff7c010000000000000000000000000000000000000000000000000000000002817bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19161415151561223157600080fd5b600160336000837bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19167bffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916815260200190815260200160002060006101000a81548160ff02191690831515021790555050565b6122a88282612cac565b6122b28282612e45565b6122bb81612f0c565b5050565b6122c882611f2c565b15156122d357600080fd5b8060d4600084815260200190815260200160002090805190602001906122fa929190613a08565b505050565b6123148161016c612f5890919063ffffffff16565b8073ffffffffffffffffffffffffffffffffffffffff167fcd265ebaf09df2871cc7bd4133404a235ba12eff2041bb89d9c714a2621c7c7e60405160405180910390a250565b61236f8161016c61300790919063ffffffff16565b8073ffffffffffffffffffffffffffffffffffffffff167f6719d08c1888103bea251a4ed56406bd0c3e69723c8a1686e017e7bbe159b6f860405160405180910390a250565b6123ca8161010761300790919063ffffffff16565b8073ffffffffffffffffffffffffffffffffffffffff167f6ae172837ea30b801fbfcdd4108aa1d5bf8ff775444fd70256b44e6bf3dfc3f660405160405180910390a250565b61242581610107612f5890919063ffffffff16565b8073ffffffffffffffffffffffffffffffffffffffff167fe94479a9f7e1952cc78f2d6baab678adc1b772d936c6583def489e524cb6669260405160405180910390a250565b3373ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff16141515156124a657600080fd5b80606960003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff0219169083151502179055508173ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff167f17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c3183604051808215151515815260200191505060405180910390a35050565b60006125c88473ffffffffffffffffffffffffffffffffffffffff166130b7565b15156125d757600190506127c2565b60008473ffffffffffffffffffffffffffffffffffffffff1663150b7a02338887876040518563ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200183815260200180602001828103825283818151815260200191508051906020019080838360005b838110156126ce5780820151818401526020810190506126b3565b50505050905090810190601f1680156126fb5780820380516001836020036101000a031916815260200191505b5095505050505050602060405180830381600087803b15801561271d57600080fd5b505af1158015612731573d6000803e3d6000fd5b505050506040513d602081101561274757600080fd5b8101908080519060200190929190505050905063150b7a027c0100000000000000000000000000000000000000000000000000000000027bffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916817bffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916149150505b949350505050565b600060019054906101000a900460ff16806127e957506127e861219c565b5b8061280057506000809054906101000a900460ff16155b151561289a576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e8152602001807f436f6e747261637420696e7374616e63652068617320616c726561647920626581526020017f656e20696e697469616c697a656400000000000000000000000000000000000081525060400191505060405180910390fd5b60008060019054906101000a900460ff1690506001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055506128eb826130ca565b600061019f60006101000a81548160ff02191690831515021790555080600060016101000a81548160ff0219169083151502179055505050565b600060019054906101000a900460ff1680612944575061294361219c565b5b8061295b57506000809054906101000a900460ff16155b15156129f5576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e8152602001807f436f6e747261637420696e7374616e63652068617320616c726561647920626581526020017f656e20696e697469616c697a656400000000000000000000000000000000000081525060400191505060405180910390fd5b60008060019054906101000a900460ff1690506001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff021916908315150217905550612a45613219565b612a716380ac58cd7c0100000000000000000000000000000000000000000000000000000000026121e0565b80600060016101000a81548160ff02191690831515021790555050565b600060019054906101000a900460ff1680612aad5750612aac61219c565b5b80612ac457506000809054906101000a900460ff16155b1515612b5e576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e8152602001807f436f6e747261637420696e7374616e63652068617320616c726561647920626581526020017f656e20696e697469616c697a656400000000000000000000000000000000000081525060400191505060405180910390fd5b60008060019054906101000a900460ff1690506001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff021916908315150217905550612bae6121ad565b1515612bb957600080fd5b612bc161337a565b1515612bcc57600080fd5b612bd5826133ad565b80600060016101000a81548160ff0219169083151502179055505050565b600080612bff836115ff565b90508073ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff161480612c6e57508373ffffffffffffffffffffffffffffffffffffffff16612c56846111b9565b73ffffffffffffffffffffffffffffffffffffffff16145b80612c7f5750612c7e8185611e98565b5b91505092915050565b612c938383836134fc565b612c9d8382613761565b612ca78282612e45565b505050565b600073ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff1614151515612ce857600080fd5b612cf181611f2c565b151515612cfd57600080fd5b816066600083815260200190815260200160002060006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550612da26001606860008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205461390590919063ffffffff16565b606860008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002081905550808273ffffffffffffffffffffffffffffffffffffffff16600073ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef60405160405180910390a45050565b609c60008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002080549050609d600083815260200190815260200160002081905550609c60008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208190806001815401808255809150509060018203906000526020600020016000909192909190915055505050565b609e80549050609f600083815260200190815260200160002081905550609e81908060018154018082558091505090600182039060005260206000200160009091929091909150555050565b600073ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff1614151515612f9457600080fd5b612f9e8282612108565b1515612fa957600080fd5b60008260000160008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff0219169083151502179055505050565b600073ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff161415151561304357600080fd5b61304d8282612108565b15151561305957600080fd5b60018260000160008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff0219169083151502179055505050565b600080823b905060008111915050919050565b600060019054906101000a900460ff16806130e957506130e861219c565b5b8061310057506000809054906101000a900460ff16155b151561319a576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e8152602001807f436f6e747261637420696e7374616e63652068617320616c726561647920626581526020017f656e20696e697469616c697a656400000000000000000000000000000000000081525060400191505060405180910390fd5b60008060019054906101000a900460ff1690506001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055506131eb826113b8565b15156131fb576131fa8261235a565b5b80600060016101000a81548160ff0219169083151502179055505050565b600060019054906101000a900460ff1680613238575061323761219c565b5b8061324f57506000809054906101000a900460ff16155b15156132e9576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e8152602001807f436f6e747261637420696e7374616e63652068617320616c726561647920626581526020017f656e20696e697469616c697a656400000000000000000000000000000000000081525060400191505060405180910390fd5b60008060019054906101000a900460ff1690506001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff02191690831515021790555061335d6301ffc9a77c0100000000000000000000000000000000000000000000000000000000026121e0565b80600060016101000a81548160ff02191690831515021790555050565b60006133a8635b5e139f7c0100000000000000000000000000000000000000000000000000000000026110af565b905090565b600060019054906101000a900460ff16806133cc57506133cb61219c565b5b806133e357506000809054906101000a900460ff16155b151561347d576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e8152602001807f436f6e747261637420696e7374616e63652068617320616c726561647920626581526020017f656e20696e697469616c697a656400000000000000000000000000000000000081525060400191505060405180910390fd5b60008060019054906101000a900460ff1690506001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055506134ce82611a4a565b15156134de576134dd826123b5565b5b80600060016101000a81548160ff0219169083151502179055505050565b8273ffffffffffffffffffffffffffffffffffffffff1661351c826115ff565b73ffffffffffffffffffffffffffffffffffffffff1614151561353e57600080fd5b600073ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff161415151561357a57600080fd5b61358381613926565b6135d66001606860008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020546139e690919063ffffffff16565b606860008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208190555061366c6001606860008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205461390590919063ffffffff16565b606860008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002081905550816066600083815260200190815260200160002060006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550808273ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef60405160405180910390a4505050565b60006137b96001609c60008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020805490506139e690919063ffffffff16565b90506000609d600084815260200190815260200160002054905081811415156138ac576000609c60008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208381548110151561382a57fe5b9060005260206000200154905080609c60008773ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208381548110151561388457fe5b906000526020600020018190555081609d600083815260200190815260200160002081905550505b609c60008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208054809190600190036138fe9190613a88565b5050505050565b600080828401905083811015151561391c57600080fd5b8091505092915050565b600073ffffffffffffffffffffffffffffffffffffffff166067600083815260200190815260200160002060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff161415156139e35760006067600083815260200190815260200160002060006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505b50565b60008282111515156139f757600080fd5b600082840390508091505092915050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f10613a4957805160ff1916838001178555613a77565b82800160010185558215613a77579182015b82811115613a76578251825591602001919060010190613a5b565b5b509050613a849190613ab4565b5090565b815481835581811115613aaf57818360005260206000209182019101613aae9190613ab4565b5b505050565b613ad691905b80821115613ad2576000816000905550600101613aba565b5090565b9056fea165627a7a7230582061286f563cb28bda0c0a4461684b58d7e03b13a7eb2736bb4b841da5ff2c7e3b0029';
</pre>
</details>

```
> web3.eth.estimateGas({ data, gas: 20099 })
4025025
> web3.eth.estimateGas({ data, gas: 4025025 })
4025025
> web3.eth.estimateGas({ data, gas: 1e10 })
4025025
> web3.eth.estimateGas({ data, gas: 0 })
4025025
> web3.eth.estimateGas({ data })
4025025
> web3.eth.estimateGas({ data, gas: 21000 })
Error: Returned error: gas required exceeds allowance or always failing transaction
> web3.eth.estimateGas({ data, gas: 4025024 })
Error: Returned error: gas required exceeds allowance or always failing transaction
```

**Comment by karalabe** [comment]
This is working as intended. You can use the gas parameter to specify an alternative upper bound vs. the default pending block gas limit. Estimating gas consumption is an attack vector if there's no upper limit.

**Comment by spalladino** [comment]
Thanks for the info @karalabe! I was not aware of that semantic for the gas parameter (my bad for not RTFM). Still, it feels like the estimate working with gas values under 21k is indeed a bug.
