### ISSUE TITLE
Mapping State variable state not changed from web3 js but working on remix

### ISSUE THREAD

**Issue by mandritac** [ethereum/go-ethereum#18982]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.7.3-stable`
OS & Version: Ubuntu 16.04.3 LTS
Commit hash : (if `develop`)

#### Expected behaviour
I have a contract code where I have declared a state variable as below - 
    mapping(uint256 => PO) poMap; 

This value doesn't set when I am trying to send a transaction from web3 js api but working when the same transaction is submitted from Remix. SSTORE opcode fails check the debug logs.

#### Actual behaviour
The state variable value should change even when using web3 js

#### Steps to reproduce the behaviour
Run the contract from remix and using web3 js (0.20.6) in node js program to confirm the difference in behavior. Also attaching the contract code and debug traces.
[Files.zip](https://github.com/ethereum/go-ethereum/files/2824271/Files.zip)

#### Backtrace

````
[backtrace]
````

**Comment by mandritac** [comment]
One strange thing observed if I remove bool exists field from the struct then it is working from web3js program also. Else the transaction is failing.

**Comment by ligi** [comment]
I am pretty sure this is the wrong repository for this issue. But also not sure where to redirect - either remix or web3.js - perhaps @yann300 knows
