### ISSUE TITLE
Event Subscription Error: leveldb: not found

### ISSUE THREAD

**Issue by pooleja** [ethereum/go-ethereum#19009]
After upgrading to the latest release, I am seeing a failure to listen to events.  This is being reproduced on Ropsten.  This happens only if I start listening for a long scan (e.g. starting filter from block 0)

Pointing to infura as web3 provider does note see this issue.

#### System information

Geth version: `geth version`
```
Geth
Version: 1.8.22-stable
Git Commit: 7fa3509e2eaf1a4ebc12344590e5699406690f15
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
```
OS & Version: Windows/Linux/OSX
Ubuntu Linux

#### Expected behaviour
Even subscriptions should handle callbacks without and errors.

#### Actual behaviour
Callback handler in web3 gets called with error parameter:

```
Error: Node error: {"code":-32000,"message":"leveldb: not found"}
    at Function.validate (/app/node_modules/web3-providers/dist/web3-providers.cjs.js:67:18)
    at /app/node_modules/web3-providers/dist/web3-providers.cjs.js:495:57
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

#### Steps to reproduce the behaviour
I have a simple subscription for a contract deployed in ropsten.  Starting to listen triggers this behavior.

```
    contractInst.events.MyTestEvent(
      {
        filter: {},
        fromBlock: 0
      },
      async (error, params) => {
        if (error) {
          console.log(error)
          logger.error(`ERROR during callback: ${error}`)
          process.exit(-1)
        }
```
#### Logs
I see this in the logs if it fails:
```
ERROR[02-06|19:55:23.551] write tcp 10.0.18.XXX:8546->10.0.29.XXX:60806: write: broken pipe
```

**Comment by xiaods** [comment]
maybe caused by the contract, so cloud you please some sample testing to help me to investigate the environment, i can have try deeply on source code to find the potential bug.

**Comment by jleeh** [comment]
I'm seeing this issue as well. Tried updating Geth to the latest stable version of `1.8.23` which didn't fix it. @pooleja What flags are you using to start geth locally?

When going through the source code, it seems that this error is thrown when leveldb cannot find a key in it's db. So to me this seems like a genuine issue rather than configuration. This is where the error is defined:
https://github.com/syndtr/goleveldb/blob/master/leveldb/errors/errors.go#L20

**Comment by jleeh** [comment]
Ok, this was a simple fix. I just removed the existing Geth db locally, restarted it and it was fine. No idea on the causation of the issue.

**Comment by offerm** [comment]
I face the same problem. Using a private chain. 
What exactly did you remove? @jleeh

**Comment by zulhfreelancer** [comment]
@offerm I think he ran `geth removedb` command.

**Comment by bellaj** [comment]
I've got the same issue without running `removedb`
This issue showed up after Ia previous one (in geth 1.8.23-stable running as a single node)

> ERROR[07-08|10:36:18.001] Section processing failed                type=bloombits error="chain reorged during section processing"

I think they are connected

**Comment by karalabe** [comment]
This should definitely be caused by a crash, which lead to a database corruption. Not much we can do, but please open a new issue if it happens again and you have more information.
