### ISSUE TITLE
eth.getUncle returns 0 for totalDifficulty

### ISSUE THREAD

**Issue by Har01d** [ethereum/go-ethereum#19024]
From documentation:

`totalDifficulty - String: Integer of the total difficulty of the chain until this block.`

When running with latest geth

`eth.getUncle(1000015, 0)`

it outputs

```
{
  difficulty: 12555442155599,
  …
  hash: "0xf0a53dfdd6c2f2a661e718ef29092de60d81d45f84044bec7bf4b36630b2bc08",
  …
  number: 1000013,
  parentHash: "0xb397a22bb95bf14753ec174f02f99df3f0bdf70d1851cdff813ebf745f5aeb55",
  …
  totalDifficulty: 0,
  … 
}
```

**Comment by xiaods** [comment]
i guess this is default behavior. because the uncle is not regular chain block. it can't count from earlier block. only correct block chain's block can get totalDifficulty.  

if you run web3.eth.getBlock(1000015), it will return correctly totalDifficulty value.

**Comment by karalabe** [comment]
We don't maintain the total difficulties for non canonical blocks. We should probably not return that field at all.
