### ISSUE TITLE
Eth - UPNP Device Not Found

### ISSUE THREAD

**Issue by rodriglporto** [ethereum/go-ethereum#1902]
Hi

I've been using Eth for around 1.5 months and it was working beautifully... Two days ago I turned off my computer and when I turned it on again, I couldn't connect anymore nor sync the blockchain. I've got a wallet with some ether on and I can't send my ethers to another wallet, since I can't connect to the network anymore...

This is the error I receive when I start eth:

i  00:45:43|p2p  UPnP device not found.
Node ID: enode://f156d05db713b7203af1864543ef53cc4e2c28fab0387a40f1d6f9a13ffa5b62fb493d7cd80ea23ca5d27d7e9eeef0c47f923080987132b8c287dd9e1f120c74@0.0.0.0:0

Some more log errors:

N C 00:00:48|p2p Connection refused to node ##5374c1bf… @ tcp://92.51.165.126:30300 ( No connection could be made because the target machine actively refused it )
N C 00:00:49|p2p Connection refused to node ##979b7fa2… @ tcp://5.1.83.226:30303 ( A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond )
N C 00:00:49|p2p Connection refused to node ##7f25d3ea… @ tcp://54.207.93.166:30303 ( A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond )

I'm using Windows 10. Right now I just made a new test. I've setup Geth, created a new account and all and it works fine. So it's something specifically on Eth.

Can you help me?

Cheers!

Rodrigo.

**Comment by fjl** [comment]
We cannot help you with eth issues, this is the geth issue tracker.
Good to hear that at least geth seems to work.

Please reopen this issue at http://github.com/ethereum/webthree-umbrella/issues
