### ISSUE TITLE
Feature request: Pooling of Streams in /rlp/decode.go

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum/go-ethereum#19036]
Hello guys, 
I've written some scripts that read all blocks of the blockchain and applies some filters. However I've noticed that the performance of web3.eth.getBlock is sub optimal since each call allocates new memory for NewStream.decode() in rlp/decode.go. There are already some TODO's there: https://github.com/ethereum/go-ethereum/blob/27e3f968194e2723279b60f71c79d4da9fc7577f/rlp/decode.go#L129 . 
I would be happy to contribute code, however I do not know how to best pool streams. 
Keep up the good work!

**Comment by fjl** [comment]
added in https://github.com/ethereum/go-ethereum/pull/19044
