### ISSUE TITLE
Geth walllet Import - panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by rodriglporto** [ethereum/go-ethereum#1904]
Hello Guys!

Is it possible to import a JSON wallet from ETH to a GETH wallet? Or transfer funds?

Unfortunately my ETH is not connecting to the network anymore and I can't figure out why (I have another issue opened)... So I at least don't want to lose my ether that I have in the ETH wallet.

So, when I try to import my ETH wallet to GETH, I receive an error. Details below:

geth wallet import "c612f160-ff77-7494-f38b-1141551cea11.json"

Passphrase: <I type my password here>
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/ethereum/go-ethereum/crypto.decryptPreSaleKey(0xc08208b680, 0x27f, 0x47f, 0xc0820f71c0, 0xc, 0xc0820f6f50, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/crypto/crypto.go:250 +0x85f
github.com/ethereum/go-ethereum/crypto.ImportPreSaleKey(0x1b34f18, 0xc0820f6f50, 0xc08208b680, 0x27f, 0x47f, 0xc0820f71c0, 0xc, 0x1, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/crypto/crypto.go:229 +0x7e
github.com/ethereum/go-ethereum/accounts.(*Manager).ImportPreSaleKey(0xc082067ce0, 0xc08208b680, 0x27f, 0x47f, 0xc0820f71c0, 0xc, 0x0, 0x0, 0x0, 0x0, ...)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/accounts/account_manager.go:230 +0xd5
main.importWallet(0xc08209ac40)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:689 +0x2f6
github.com/codegangsta/cli.Command.Run(0xda87d0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe7f330, 0x1e, 0x0, ...)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:118 +0x1052
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc0821500f0, 0xc08209aa80, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:270 +0xc38
github.com/codegangsta/cli.Command.startApp(0xdb7e90, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe2b7b0, 0x17, 0x107c290, ...)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:176 +0x386
github.com/codegangsta/cli.Command.Run(0xdb7e90, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe2b7b0, 0x17, 0x107c290, ...)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:45 +0x14fc
github.com/codegangsta/cli.(*App).Run(0xc082150000, 0xc0820042c0, 0x4, 0x4, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:177 +0xdfd
main.main()
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:359 +0x87

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [chan receive]:
github.com/ethereum/go-ethereum/logger/glog.(*loggingT).flushDaemon(0x1478e80)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:897 +0x7f
created by github.com/ethereum/go-ethereum/logger/glog.init┬╖1
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:428 +0x7e

goroutine 7 [select]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/logger/sys.go:81 +0x6d8
created by github.com/ethereum/go-ethereum/logger.init┬╖1
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/logger/sys.go:60 +0x2c

goroutine 9 [syscall]:
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:21 +0x26
created by os/signal.init┬╖1
        c:/go/src/os/signal/signal_unix.go:27 +0x3c

I'm using WINDOWS 10.

Tks!

Rodrigo.

**Comment by obscuren** [comment]
I might be mistaken but I don't think `eth` produces standard JSON wallets. Maybe @gavofyork could chime in, he's in charge of cpp-ethereum which produces `eth`

**Comment by rodriglporto** [comment]
Yes, actually @obscuren, you are right. After some more reading I realized this as well. Anyway, I was able to to fix my other problem with my AlethZero... I've downloaded the new version and was able to connect to the network, update my blockchain and my wallet funds. So, this issue can be closed :).

Tks anyway! Cheers!
