### ISSUE TITLE
clef: bundle 4byte api

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#19048]
Clef currently comes with a 4bytedb json file 'side by side'. This should be changed, 

* The file should be updated with the most recent dump from 4bytedb.org, 
* The file should be bundled as a resource, just like our tracers and other javascript files, using https://github.com/kevinburke/go-bindata/ 

 That will make the `clef` binary standalone, and the `--4bytedb` CLI switch would not be required anymore.

**Comment by ligi** [comment]
4bytedb.org does not exist - maybe you mean https://www.4byte.directory
Another option is: https://github.com/ethereum-lists/4bytes - also contains some things like the peepeth API signatures that are not on the 4byte.directory

**Comment by holiman** [comment]
I meant the second, which I thought was an aggregate of the first. It isn't?

**Comment by ligi** [comment]
the second one is not only an aggregation of the first. The 4byte.directory is one source of import for the second one. But there are some additions (e.g. the peepeth ABI - the source of peepeth contract is not open so it does not get picked up by the 4byte.directory) 
That said most content is currently coming from the 4byte.directory

**Comment by holiman** [comment]
Below are the collisions so far, on the list from ethereum lists. Hardly makes sense to code in extra handling of that in clef. I'm currently making a little tool which can help generated the bindata from the lists.  

sig `776d1a01`
 - unvest(uint256,uint256,uint256,uint256,uint256,bool)
 - setTarget(address)

sig `0900f010`
 - AcoraidaMonicaWantsToKeepALogOfTheWinner(address)
 - upgrade(address)

sig `aaaaaad1`
 - yycU4()
 - uYZeB()

sig `04d742dc`
 - startSale(uint256,uint256,uint256)
 - adminResetRank()

sig `025313a2`
 - getACLRole5999294130779334338()
 - proxyOwner()

sig `00000000`
 - get_block_hash_257335279069929(uint256)
 - blockHashAskewLimitary(uint256)
 - blockHashAmarilloNonspontaneously(uint256)
 - blockHashAmphithyronVersify(uint256)
 - overdiffusingness(bytes,uint256,uint256,uint256,uint256)
 - blockHashAddendsInexpansible(uint256)
 - left_branch_block(uint32)

sig `000000c7`
 - withdrawByAdmin_Unau(uint256[])
 - lend_during(uint256,uint256,uint64,uint32)

sig `80dfa34a`
 - saveBatch(string)
 - peepeth_postBatch_8082255437(string)

sig `0000006e`
 - bright_peace(bytes32,bytes)
 - display_allow(uint256,uint256,uint256,uint32)

sig `3bb2dead`
 - initialFundsReleaseNumerator()
 - resolveAddressLight(address)

**Comment by ligi** [comment]
I can add some more to black.lst (https://github.com/ethereum-lists/4bytes/blob/master/black.lst) - and remove them from the 4byte directory.

I would say:

sig `776d1a01`

* setTarget(address)

sig `0900f010`

* AcoraidaMonicaWantsToKeepALogOfTheWinner(address)

sig `aaaaaad1`

* yycU4()
* uYZeB()

sig `04d742dc`

* adminResetRank()

sig `025313a2`

* getACLRole5999294130779334338()

sig `00000000`

* get_block_hash_257335279069929(uint256)
* blockHashAskewLimitary(uint256)
* blockHashAmarilloNonspontaneously(uint256)
* blockHashAmphithyronVersify(uint256)
* overdiffusingness(bytes,uint256,uint256,uint256,uint256)
* blockHashAddendsInexpansible(uint256)
* left_branch_block(uint32)

sig `000000c7`

* withdrawByAdmin_Unau(uint256[])

sig `80dfa34a`

* peepeth_postBatch_8082255437(string)

sig `0000006e`

* display_allow(uint256,uint256,uint256,uint32)

sig `3bb2dead`

* initialFundsReleaseNumerator()

**Comment by ligi** [comment]
cared for the collisions via https://github.com/ethereum-lists/4bytes/commit/5a1441a7de0c6bc4974d900dcf9695923fdec085

**Comment by Gb2real** [comment]
Bundle 4byte thank u n god bless you
