### ISSUE TITLE
`eth.getTransaction("txHash")`  returns  null  with  geth light mode  in mainnet

### ISSUE THREAD

**Issue by wangjunbao2018** [ethereum/go-ethereum#19063]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

I  use geth 1.8.21 and synced the block data in light mode.  Then I  search block and transaction in geth console.  However, I got the right block, but  when I  search the transaction by `eth.getTransaction("txHash")` which is from `transactions` list. I got  `null`.  Anyone who met this case? why it happened? 

#### System information

Geth version: `1.8.21-stable`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

` eth.getTransaction("0x736d4a2e625544ceff964ad1808823c9c7436478c625ef9da73650d6f9744258")`  get the right tx infomation.  

#### Actual behaviour

```
> eth.getTransaction("0x736d4a2e625544ceff964ad1808823c9c7436478c625ef9da73650d6f9744258")
null
```

BTW,  I am sure the block I use is confirmed.  and  `getBalance`, `getBlock` api work fine.

**Comment by zsfelfoldi** [comment]
Get transaction by hash is not supported yet but it will soon be. The necessary messages are already implemented in the protocol but the API part is not done yet. When this is done it will be announced in the release notes of Geth.

**Comment by holiman** [comment]
Clarification: this happens because _light_ mode does not contain the full blocks, only headers. And thus also no mapping of `hash -> block` . A `fast` or `full` handles this fine, but light mode has to reach out and fetch the data from the LES server.

**Comment by wangjunbao2018** [comment]
> Get transaction by hash is not supported yet but it will soon be. The necessary messages are already implemented in the protocol but the API part is not done yet. When this is done it will be announced in the release notes of Geth. Also I will reference this issue in the PR so you can test it before it is released if you want.

Thx.  But testnet rinkeby is already implemented this feature. right?  for Rinkeby,  `eth.getTransaction("txHash")` can get right  transaction info. but  `eth.getTransactionReceipt("txHash")` can't. what's the different between the implements of mainnet and testnet?

**Comment by wangjunbao2018** [comment]
> Clarification: this happens because _light_ mode does not contain the full blocks, only headers. And thus also no mapping of `hash -> block` . A `fast` or `full` handles this fine, but light mode has to reach out and fetch the data from the LES server.

Thx. I see. I will just  learn the document about LES server.
