### ISSUE TITLE
Geth crashes, “missing trie node”, rlp: expected List

### ISSUE THREAD

**Issue by pawelsome** [ethereum/go-ethereum#19070]
Hi,
I am struggling with failing geth with my Dapp. I got an error like this:

Web3

```
UnhandledPromiseRejectionWarning: Error: Returned error: missing trie node 3b78b9f0a935d03af6f70ac4173f718e46b62573d4363ff5839f41a6df4f2429 (path 020f06020608)
Geth:
```

```
INFO [02-07|06:51:18.668] Imported new chain segment               blocks=1 txs=247 mgas=7.993  elapsed=145.425ms mgasps=54.961  number=7186894 hash=bfbcdcâ€¦0a5b69 age=1m12s cache=268.00mB
panic: node 93e9e8033c6f4bdc391443e9d3446e41e41c175e0e2e353924b40b74d41d2933: decode error: rlp: expected List 
goroutine 56011323 [running]:
github.com/ethereum/go-ethereum/trie.mustDecodeNode(0xc66da87ba0, 0x20, 0x20, 0xc4bd8300e0, 0x68, 0x68, 0x3ed6, 0x0, 0x0)
/build/ethereum-fSsX30/ethereum-
```
It happens randomly at least once a month, and i have to do resync every time.

What may cause this problem?

I need a stable solution.

I use Geth 1.8.22.

**Comment by karalabe** [comment]
We've found and fixed a data race in our trie node read cache. We're not sure whether that was the culprit or not, but it's definitely a possible source of error. It's not yet on master, but will hopefully be soon.

**Comment by karalabe** [comment]
Closing this as potentially fixed. Please reopen if you still see it with v1.8.23.
