### ISSUE TITLE
Fatal: Error starting RPC: listen tcp xx.xx.xx.xx:xxxx: bind: cannot assign requested address

### ISSUE THREAD

**Issue by c-cex** [ethereum/go-ethereum#1909]
Linux Debian x64. I'v compiled geth, started it this way:

su -m ethuser -c '/eth/geth -rpc -rpcaddr=xx.xx.xx.xx -rpcport=xxxx'

And got this error:

1016 23:22:31.272868   28300 http.go:96] Can't listen on xx.xx.xx.xx:xxxx: listen tcp xx.xx.xx.xx:xxxx: bind: cannot assign requested address
Fatal: Error starting RPC: listen tcp xx.xx.xx.xx:xxxx: bind: cannot assign requested address

I tried different ports - same error.

**Comment by fjl** [comment]
If you specify a listening address, one of the network interfaces on the machine must have that address.

**Comment by fjl** [comment]
Would be good to know what you are trying to do.

**Comment by c-cex** [comment]
I'm trying to specify IP address of my server from where only I want to be able to access wallet's RPC

**Comment by fjl** [comment]
Things you can do:

- Use the firewall (iptables, etc.) to limit access to a certain source IP range. 
- Run geth with --rpcaddr=127.0.0.1 (the default) and put a proxy such as nginx in front of it. Configure IP-based access control with nginx or use SSL with client certificates. I'd recommend the latter if you want access via the Internet.

**Comment by c-cex** [comment]
Then feature request!
-rpcallowip= like bitcoin has!

**Comment by mohitsharma18** [comment]
I am facing the same error while providing public IP in --rpcaddr, please help

**Comment by holiman** [comment]
> If you specify a listening address, one of the network interfaces on the machine must have that address.

Is that really an address on your interface?

**Comment by mohitsharma18** [comment]
yes @holiman,

my node-js application is running on that address, but when I start geth with it, it throws the error, also port is open for the IP
