### ISSUE TITLE
Synchronization failure

### ISSUE THREAD

**Issue by larspensjo** [ethereum/go-ethereum#1910]
I am using the geth 1.2.2 packaged with the Windows Ethereum wallet, and noticed synchronization started "quick", but then slowed down, failing to catch up. Starting geth manually, I get a log file as follows:

    I1017 12:01:27.142035    3368 downloader.go:275] Block synchronisation started
    I1017 12:01:29.238483    3368 chain_manager.go:722] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 1.2704586s. #395895 [8628e733 / 8628e733]
    I1017 12:01:29.753824    3368 chain_manager.go:722] imported 126 block(s) (0 queued 0 ignored) including 196 txs in 515.3406ms. #396021 [2abbe528 /90dd35d1]
    I1017 12:01:30.503320    3368 chain_manager.go:722] imported 256 block(s) (0 queued 0 ignored) including 251 txs in 748.4954ms. #396277 [f72c9a75 /f3d0ee7d]
    I1017 12:01:31.286839    3368 chain_manager.go:722] imported 256 block(s) (0 queued 0 ignored) including 304 txs in 782.5183ms. #396533 [a88e3601 /f4bc4f5a]
    I1017 12:01:33.879559    3368 chain_manager.go:722] imported 256 block(s) (0 queued 0 ignored) including 908 txs in 2.5927198s. #396789 [d46496d9 /ab0b08b0]
    I1017 12:01:34.207776    3368 chain_manager.go:722] imported 111 block(s) (17 queued 0 ignored) including 118 txs in 327.2159ms. #396917 [44d231bf / e838f398]
    I1017 12:01:34.333858    3368 chain_manager.go:722] imported 0 block(s) (256 queued 0 ignored) including 0 txs in 126.0824ms. #397173 [14974fb8 / 87fefebb]
    I1017 12:01:34.389895    3368 chain_manager.go:722] imported 0 block(s) (118 queued 0 ignored) including 0 txs in 55.0364ms. #397291 [4b8cd0b7 / 4ba73fb6]
    I1017 12:01:34.914465    3368 chain_manager.go:846] Bad block #397036 (66a5304ac7bbc38281f9bf3194d2cde669121c5e6859db54e2d89de408dccde7)
    I1017 12:01:34.914465    3368 chain_manager.go:847] Block's parent unknown 7c6bbd78c1f131dc21d82db2d822a8561cc9f3779090f9fff073245b2f85bccd
    I1017 12:01:38.025904    3368 chain_manager.go:722] imported 0 block(s) (1 queued 0 ignored) including 0 txs in 5.0033ms. #396901 [b94f31c6 / b94f31c6]
    I1017 12:01:38.165770    3368 chain_manager.go:722] imported 0 block(s) (2 queued 0 ignored) including 0 txs in 5.003ms. #396903 [3ec6a133 / bcfd4878]
    I1017 12:01:38.308132    3368 chain_manager.go:722] imported 0 block(s) (4 queued 0 ignored) including 0 txs in 6.0064ms. #396907 [65293931 / 0fc6255e]
    I1017 12:01:38.460492    3368 chain_manager.go:722] imported 0 block(s) (8 queued 0 ignored) including 0 txs in 11.007ms. #396915 [c4d36def / 95b74d94]
    I1017 12:01:38.619493    3368 chain_manager.go:722] imported 0 block(s) (16 queued 0 ignored) including 0 txs in 15.0099ms. #396931 [a5f2c083 / 9f202cbc]
    I1017 12:01:38.789532    3368 chain_manager.go:722] imported 0 block(s) (32 queued 0 ignored) including 0 txs in 25.0162ms. #396963 [9ddd6bcc / a3137077]
    I1017 12:01:39.131256    3368 chain_manager.go:722] imported 0 block(s) (64 queued 0 ignored) including 0 txs in 34.0225ms. #397027 [3bce2fd3 / 109d06b3]
    I1017 12:01:39.600650    3368 chain_manager.go:722] imported 0 block(s) (128 queued 0 ignored) including 0 txs in 66.0435ms. #397155 [2ec27d5f / b9957ea5]
    I1017 12:01:39.802783    3368 chain_manager.go:722] imported 0 block(s) (128 queued 0 ignored) including 0 txs in 64.0412ms. #397283 [3381ff8a / 3738e714]
    I1017 12:01:39.887841    3368 chain_manager.go:722] imported 0 block(s) (9 queued 0 ignored) including 0 txs in 6.0046ms. #397292 [891e1bb7 / 1c1629bb]
    I1017 12:01:39.904852    3368 chain_manager.go:846] Bad block #397037 (d669cde13421af8b75c6170de0f030b296570b966f460995d3b6504eedf9f754)
    I1017 12:01:39.904852    3368 chain_manager.go:847] Block's parent unknown 66a5304ac7bbc38281f9bf3194d2cde669121c5e6859db54e2d89de408dccde7
    I1017 12:01:44.903094    3368 chain_manager.go:846] Bad block #397037 (d669cde13421af8b75c6170de0f030b296570b966f460995d3b6504eedf9f754)
    I1017 12:01:44.929110    3368 chain_manager.go:847] Block's parent unknown 66a5304ac7bbc38281f9bf3194d2cde669121c5e6859db54e2d89de408dccde7
    I1017 12:01:47.982774    3368 chain_manager.go:722] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 6.0049ms. #396901 [b94f31c6 / b94f31c6]
    I1017 12:01:48.175087    3368 chain_manager.go:722] imported 0 block(s) (2 queued 0 ignored) including 0 txs in 6.0022ms. #396903 [3ec6a133 / bcfd4878]
    I1017 12:01:48.324990    3368 chain_manager.go:722] imported 0 block(s) (4 queued 0 ignored) including 0 txs in 6.8396ms. #396907 [65293931 / 0fc6255e]
    I1017 12:01:48.472170    3368 chain_manager.go:722] imported 0 block(s) (8 queued 0 ignored) including 0 txs in 9.0066ms. #396915 [c4d36def / 95b74d94]
    I1017 12:01:48.629568    3368 chain_manager.go:722] imported 0 block(s) (16 queued 0 ignored) including 0 txs in 14.0099ms. #396931 [a5f2c083 / 9f202cbc]
    I1017 12:01:48.808459    3368 chain_manager.go:722] imported 0 block(s) (32 queued 0 ignored) including 0 txs in 25.0163ms. #396963 [9ddd6bcc / a3137077]
    I1017 12:01:49.031696    3368 chain_manager.go:722] imported 0 block(s) (64 queued 0 ignored) including 0 txs in 31.0202ms. #397027 [3bce2fd3 / 109d06b3]
    I1017 12:01:49.397939    3368 chain_manager.go:722] imported 0 block(s) (128 queued 0 ignored) including 0 txs in 74.047ms. #397155 [2ec27d5f / b9957ea5]
    I1017 12:01:49.690133    3368 chain_manager.go:722] imported 0 block(s) (128 queued 0 ignored) including 0 txs in 70.0464ms. #397283 [3381ff8a / 3738e714]
    I1017 12:01:49.793202    3368 chain_manager.go:722] imported 0 block(s) (10 queued 0 ignored) including 0 txs in 10.0048ms. #397293 [891e1bb7 / a1b67d2c]
    I1017 12:01:49.904320    3368 chain_manager.go:846] Bad block #397038 (fa080342c11dcd6ce0918454b8933406318454b77114c0932d58033b330bade1)
    I1017 12:01:49.905320    3368 chain_manager.go:847] Block's parent unknown d669cde13421af8b75c6170de0f030b296570b966f460995d3b6504eedf9f754

So I did a ```geth removedb```, and restarted. But after 300,000 blocks something, the synchronization started to fail again.

**Comment by obscuren** [comment]
Could you check and make sure your system time is synchronized correctly

**Comment by larspensjo** [comment]
Thanks, that was spot on and fixed my problems!

I dual boot between Linux and Windows, and for some reason Windows usually get the time wrong by two hours when coming from a Linux session.

**Comment by obscuren** [comment]
Got the exact same issue on my Windows machine. Happy it fixed your issue :+1:
