### ISSUE TITLE
geth 1.2.2 ARM account unlock memory utilization

### ISSUE THREAD

**Issue by datajerk** [ethereum/go-ethereum#1911]
Hi, with every version of geth I've tested on ARM I've noticed that memory utilization averages about 130M except when unlocking an account.  Memory then balloons to 600+.  Since unlocking is async a 2nd unlock call will crash geth.  This memory is held onto for about 5 minutes.

**Comment by Gustav-Simonsson** [comment]
This is technically a feature, the KDF used for key encryption by default in geth (scrypt) requires 256MB of memory. We may consider reducing this and/or making it configurable to make unlocking easier on ARM and embedded devices. Meanwhile you should be able to generate a key with eth which uses PBKDF2 by default and then unlock it in geth. It requires far less memory to decrypt.

**Comment by datajerk** [comment]
Thanks, can you provide a bit of detail on how to generate keys with eth that work with geth?  I've tried ethkey 0.9.41 and 1.0.0 with no luck.  The new bare option seem to be what I need, but in both versions the option is not recognized.  Thanks.

Is there a patch I can apply to geth for the reduced memory foot print?

Thanks again.

**Comment by datajerk** [comment]
Default eth keys appear to be scrypt as well.

```
{
    "crypto" : {
        "cipher" : "aes-128-ctr",
        "cipherparams" : {
            "iv" : "72b66a6cca3ce4a1d2f1d2dd5acf444d"
        },
        "ciphertext" : "a241f127c3defbc1eae72d1069a1857ebc4de5a828e5f9d31a60266239c030de",
        "kdf" : "scrypt",
        "kdfparams" : {
            "dklen" : 32,
            "n" : 262144,
            "p" : 1,
            "r" : 8,
            "salt" : "436dc70ef997d9ae188c9515baf9186b82f46361534b2d7abf7b2dc8ad2b38a8"
        },
        "mac" : "1d82855d5e5d047681872c60f76b3d7d94ca65bb4bf27e3eecde50698fad67b0"
    },
    "id" : "a94d2714-e48b-3b1b-7f1f-20020a252434",
    "version" : 3
}
```

**Comment by Gustav-Simonsson** [comment]
@datajerk OK it seems eth is now also generating keys with Scrypt KDF by default. This should be compatible with geth as both are based on the same spec: https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

We tested compatibility cross Go, CPP and Python for this spec awhile back, but it looks like some minor incompatibility is not present. Probably just some encoding, I'll look into it and see if we need to patch it up.

Meanwhile, you can modify this value (each decrement should halve the memory usage of Scrypt): https://github.com/ethereum/go-ethereum/blob/master/crypto/key_store_passphrase.go#L49

Setting it to e.g. 12 should bring down memory usage to 4MB.

**Comment by datajerk** [comment]
@Gustav-Simonsson this appears to be working.  I'll do more testing.  Thank you very much!  Oh, on a 1GHz ARM new account went from 36.5 seconds to 1.5.  Unlocks were taking 44 seconds, now almost instant.  What are the impacts of this setting?  What am I giving up for speed?  I can speculate.

Thanks again.

**Comment by Gustav-Simonsson** [comment]
@datajerk It configures the KDF used (Scrypt) to use less memory. This weakens the KDF which is not a problem unless weak passwords are used. If strong enough passwords are used you can configure it even lower to avoid it's overhead entirely.

If password protection of keys is not needed, one can also use the plaintext keystore by changing `NewKeyStorePassphrase` to `NewKeyStorePlain` in this line: https://github.com/ethereum/go-ethereum/blob/master/cmd/utils/flags.go#L543

The reason we haven't exposed this as a cmd line flag has been to avoid users accidentally storing unencrypted private keys and because the main usage of the keystore has been as a user wallet.

I think with a plaintext keystore it may still ask one to unlock accounts, but any password can be entered as it will not be used.

**Comment by datajerk** [comment]
@Gustav-Simonsson I've completed all my testing.  Everything passed.  A huge thanks to you.  I consider this matter closed.  Thanks again.

**Comment by wildfjre** [comment]
https://github.com/ethereum/go-ethereum/pull/1940
