### ISSUE TITLE
more context in "authentication needed: password or unlock"

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#19125]
follow up from: https://twitter.com/bitfalls/status/1097397754131816448

I do not think:

> Or assume accounts[0] or eth.coinbase is the address I want to unlock when providing pass file without --unlock flag.

is an option.
But perhaps we can improve the error-message. Maybe we can add - `did you forgot to add "--unlock ADDRESS" flag`

**Comment by Swader** [comment]
Thanks for posting this.

So another approach would be being able to specify address-password pairs in the password file, doing away with the `--unlock` flag altogether:

```
0x345768767453453453:mypassw0rd
```

But as @ligi says, just the "did you forget" addon would also have saved a lot of time. Actually even just stating `authentication needed: --password or --unlock` would make it clear those are flags, reducing ambiguity (which, admittedly, stemmed from me being a newbie).
