### ISSUE TITLE
Fix data folder on Windows.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/go-ethereum#19130]
I'm not sure if anyone will see my comment on a closed PR, so opening this issue to make sure it gets some eyeballs.  I believe the merged PR, as written, will result in incorrect behavior on Windows:
https://github.com/ethereum/go-ethereum/commit/f7f6a46029c23d2c1b5a5293d470becbdb4e3366#r32371755

**Comment by fjl** [comment]
Thank you! Let's discuss on the commit instead.
