### ISSUE TITLE
How is it possible to pay 2,100 Ether ($309,267) for a transaction fee?

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/go-ethereum#19134]
Here is the [transaction details][1] that has transaction fee for
**2,100 Ether ($309,267.00)** only for sending 0.1 Ether. 

There is no fairness for users, hence accidentally adding a zero might cause them to lose thousands of money.

[![enter image description here][2]][2]

------------

**[Q]** How and why is this possible? Why Ethereum does not provide any protection mechanism for paying very high transaction fees and why there is no limit for that?

Since it is a mistake done by the user, why Ethereum does not provide any payback/refund mechanism?
 

  [1]: https://etherscan.io/tx/0x1f73b43dc9c48cc131a931fac7095de9e5eba0c5184ec0c5c5f1f32efa2a6bab
  [2]: https://i.stack.imgur.com/PKmQ2.png

**Comment by ligi** [comment]
this is the wrong repository for this discussion. Go-ethereum is one implementation - to change what you want it would need to be an EIP that gets adopted.
So I suggest either:
https://github.com/ethereum/EIPs
or
https://ethereum-magicians.org/

**Comment by ligi** [comment]
PS: I opened a topic about this on ETHMagicians: https://ethereum-magicians.org/t/eip-to-cap-the-eth-spend-on-gas-in-one-tx/2686
