### ISSUE TITLE
[swarm] content types bug

### ISSUE THREAD

**Issue by andrewheadricke** [ethereum/go-ethereum#19150]
#### System information
Swarm version: 0.3.11
OS & Version: Linux Ubuntu

#### Expected behaviour
View uploaded swarm website correctly

#### Actual behaviour
Website does not display content correctly.  It looks like swarm is parsing the manifest incorrectly when trying to serve up the content.  For example, my site includes the html/css bootstrap directory, but swarm is serving everything in that directory as an unrelated image.

However if I access the very same swarm addressed content (same hash) via swarm-gateway or `eth.show` then it renders fine. So i'm not sure what version of swarm they are running but I would guess an older version that doesn't have this issue.

#### Steps to reproduce the behaviour
Create a website with several directories with different content types,  like js, html, img, css. You can use the `bzz-list` method to visually see how different swarm providers are interpreting the same manifest differently.

Just as an aside, i THINK the first time I accessed the content via my local swarm node it served correctly, then all subsequent attempts result in the bug, so perhaps its a cache issue.

**Comment by xiaods** [comment]
hi @andrewheadricke , your environment is parity client, it should be issue on another git repo:https://github.com/paritytech/parity-ethereum , please have a check. thanks a lot

**Comment by andrewheadricke** [comment]
No, the bug is in swarm.  I will remove the parity client reference.

**Comment by xiaods** [comment]
@andrewheadricke ok. got it.

**Comment by nonsense** [comment]
@andrewheadricke let's address this at https://github.com/ethersphere/swarm as the Swarm codebase lives there from now on.

**Comment by nonsense** [comment]
https://github.com/ethersphere/swarm/issues/1406
