### ISSUE TITLE
core: re-write hard dependency from the block chain on the block processor

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#1916]
The current approach to block and state processing is done in two stages.

1. Pass block to block chain

    a. pass the block to a block processor [2]
    b. check errors and bail if erroneous
    c. persist block & receipts to database; all state information is lost / unknown

2. Validate block

    a. validate header
    b. validate block's miner nonce
    c. process transactions and validate receipts
    d. persist state data

These separated stages makes it rather difficult to add different kind of block validators. Changing to a simpler model where validators are used rather than processors (technically the block chain is the processor) it will become much easier to implement private chains and different block validators.

The block chain and block processor are more or less intertwined with one another which doesn't allow for arbitrary validators to be set. The `BlockProcessor` takes care of saving state information to the database while the `BlockChain` takes care of saving block (header + body), receipts & logs to the database. This approach is weird because we are having persistency in two different layers.

1. The block chain should take care of all synchronisation of state, block and receipts and should use validator functions to make sure that blocks-to-be-processed pass all consensus tests. 
2. Add said validator functions that:
    
    i. Validates block, header and block receipts
    ii. Attempts to transition from previous state `X` to next state `Y` and pass handles to any to-yet-to-persist data.

- [x] Split out validator & processor
    - [x] Move `log` event firing to the `BlockChain`
    - [x] Remove `db` and `evmux` from `BlockValidator`
- [x] Remove `batch.Write` from `BlockProcessor`
- [x] Update all test
- [x] Remove unneeded mutex

**Comment by Gustav-Simonsson** [comment]
From gitter: It makes sense to split block (header) validation into three main parts:
* Validation of all block header fields except PoW and fields requiring tx processing (e.g. state root). This is very cheap.
* Validation of PoW. Somewhat expensive.
* Validation of fields requiring tx processing. Cost depends on number of txs and associated contract code. Can range from very cheap to expensive.

<img width="1482" alt="screen shot 2015-10-19 at 18 29 37" src="https://cloud.githubusercontent.com/assets/293096/10633621/4bffe90c-77ec-11e5-8107-b8c1bef213fe.png">
