### ISSUE TITLE
cmd/geth: add note about backing up the keystore

### ISSUE THREAD

**Issue by marko-avlijas** [ethereum/go-ethereum#19165]
I have created a new account, backed up address and passphrase, mined for a few months and now when I want to spend my eth I can't access it.

Why? Because I had no idea I there is something called keystore and I need to back it up.

And this hasn't improved at all. Geth is still actively losing users money!
Look at the output of newest geth I could install: 1.8.23-stable-c9427004

```
geth account new
INFO [02-25|13:19:00.805] Maximum peer count                       ETH=25 LES=0 total=25
Your new account is locked with a password. Please give a password. Do not forget this password.
Passphrase: 
Repeat passphrase: 
Address: {70f795db0a6198163df9c42192a8673ad705e929}
```
It mentions the passphrase and the address. There are no messages about keystore.

That's because keystore is not important at all and can be recreated if you know the address and the passphrase, right? Right?

Wrong! When it's time to spend your money it's headache time when you understand you lost your eth. Because you really need the keystore which isn't mentioned anywhere.

How about adding this to the message?

```
To backup this wallet you need to backup:
* X
* Y 
* Z

To read more about backing up and restoring your account please visit:
https://github.com/ethereum/go-ethereum/wiki/whatever.

```

**Comment by fjl** [comment]
We're going to add an additional message in geth 1.9.0.

**Comment by karalabe** [comment]
This is fixed by https://github.com/ethereum/go-ethereum/pull/19432 (merge pending green CI), `geth account new` will print:

```
Your new key was generated

Public address of the key:   0xdc1F7E2bC71F6FF4400B22f58c8ee723b70D7f81
Path of the secret key file: /tmp/asdasads/keystore/UTC--2019-05-07T11-46-12.643850732Z--dc1f7e2bc71f6ff4400b22f58c8ee723b70d7f81

- You can share your public address with anyone. Others need it to interact with you.
- You must NEVER share the secret key with anyone! The key controls access to your funds!
- You must BACKUP your key file! Without the key, it's impossible to access account funds!
- You must REMEMBER your password! Without the password, it's impossible to decrypt the key!
```
