### ISSUE TITLE
Failed to raise file descriptor allowance: invalid argument

### ISSUE THREAD

**Issue by MoMannn** [ethereum/go-ethereum#19173]
#### System information

Geth version: 1.8.23-stable
OS & Version: OSX

#### Expected behaviour

Running light node.

#### Actual behaviour

```
INFO [02-26|22:38:39.409] Maximum peer count                       ETH=0 LES=100 total=25
Fatal: Failed to raise file descriptor allowance: invalid argument
``` 

#### Steps to reproduce the behaviour

I was running a light node on ropsten without problems but I started getting sync errors, so I updated the client and the error above started poping up, I tried to remove lightdata but the error still persists.

**Comment by lhendre** [comment]
So the individual error is being thrown in common/fdlimit/fdlimit_unix in the raise function.  It looks like from there something is going wrong with the syscall, https://golang.org/pkg/syscall/.  Maybe $GOOS or $GOARCH got set incorrectly as that is tied to syscall?

**Comment by shoenseiwaso** [comment]
We hit the same issue. Note that it manifests itself immediately after `geth` starts, so there's no opportunity to use `ulimit` to see what kinds of limits are set. 1.8.22 appears to be unaffected.

**Comment by lhendre** [comment]
#19177 Looks like it could be related?

**Comment by karalabe** [comment]
This is an issue in Go 1.12. We've added a workaround on master. IF you build with Go 1.11.5 the `invalid argument` will go away.

**Comment by MoMannn** [comment]
@karalabe It is a pain in the ass manually fixing since I'm otherwise installing trough brew. Any timeline on official update?

**Comment by tadanderson** [comment]
@karalabe I have the same Q as @MoMannn ?

**Comment by njwest** [comment]
+1 for a timeline for a fix for this

@MoMannn & anyone else using golang thru homebrew: If you are using Homebrew, you can use `brew info go` and `brew switch go x.x.x` to roll back to an older version of Go

**Comment by karalabe** [comment]
We'll push out a stable release to fix this on Monday.

**Comment by tadanderson** [comment]
@karalabe Thank you for the heads up, and all the hard work you are doing.  Really appreciated!!!!!

**Comment by dwalintukan** [comment]
Is this always going to persist on version 1.8.23? Reason I am asking is I hard forked from this version so currently going to use this one.

**Comment by karalabe** [comment]
Yes, you need a fixed code to handle Go 1.12+'s changed behavior.

**Comment by dwalintukan** [comment]
Hm ok, guess I might have to update the nodes. Thanks.

**Comment by magus777** [comment]
Still happening on go version go1.18.3 darwin/amd64
