### ISSUE TITLE
Geth syncing issue in private network using clique PoA with insta-mining

### ISSUE THREAD

**Issue by matthieu-merlyn** [ethereum/go-ethereum#19178]
#### System information

Geth version: `1.8.23-stable`
OS & Version: `Ubuntu 18.04.2 TLS`

#### Expected behaviour
I have two separate machines with one node running on each machine. The node on machine 1 has mined 6909 blocks in PoA insta-mining mode (block period 0 in genesis config). 

I started a node on machine 2 and used `admin.addPeer` to connect node 1, after which I expected node 2 to start syncing. 

#### Actual behaviour
Output of `admin.peers` confirms that the peers are connected, and both nodes are using the same genesis block. 

Output of `eth.syncing`shows that my second node knows about the blocks on my first node :
```
{
currentBlock: 4859,
highestBlock: 6909,
knownStates: 45954,
pulledStates: 45954,
startingBlock: 6844
}
```

The syncing process however does not actually start. 

#### Steps to reproduce the behaviour

1. Start node 1 on machine 1 with unlocked account in PoA insta-mine mode. 
2. Start node 2 on machine 2. 
3. Add node 1 as peer in node 2 console.

#### Backtrace
I've created a new chain on machine 1 with a fixed 3 second blocktime instead of insta-mining, leaving all other config options intact. When starting a node on machine 2 and adding machine 1 as a peer the syncing process starts immediately.

**Comment by rjl493456442** [comment]
From your `eth.syncing` output, the syncing actually already started and still undergoing.

What do you mean `the syncing process however does not actually start.`?

**Comment by matthieu-merlyn** [comment]
I'm sorry, should've been more clear on that. The syncing process does indeed start but always goes into error right away:

```
Node data write error               err="state node c84891...25d151 failed with all peers (1 tries, 1 peers)
...
Synchronisation failed, retrying    err="state node c84891...25d151 failed with all peers (1 tries, 1 peers)
```

I gave it some time to see whether it would somehow change and restarted both nodes on and off, but both to no avail. Also, given the small size of the chain the entire sync should only take a couple of minutes I guess, but `eth.blocknumber` on node 2 always remains 0.

**Comment by steventranjs** [comment]
I encountered the same problem too

**Comment by bennylam** [comment]
Hi all,
I also encountered this problem for two nodes sync. Sync on 2nd node started but alway showing "state node ... failed with all peers  (1 tries, 1 peers)" error message.
What is the solution or fix on this problem?
Thanks

**Comment by zhzitri** [comment]
> I'm sorry, should've been more clear on that. The syncing process does indeed start but always goes into error right away:
> 
> ```
> Node data write error               err="state node c84891...25d151 failed with all peers (1 tries, 1 peers)
> ...
> Synchronisation failed, retrying    err="state node c84891...25d151 failed with all peers (1 tries, 1 peers)
> ```
> 
> I gave it some time to see whether it would somehow change and restarted both nodes on and off, but both to no avail. Also, given the small size of the chain the entire sync should only take a couple of minutes I guess, but `eth.blocknumber` on node 2 always remains 0.

Try to get your sealers to mine.
The syncing process should work right after mining.

**Comment by karalabe** [comment]
There might be a couple issues here, but the general use case of insta-mining in a private network is not something we'd like to support. Insta mining allows you two cornercases that can never happen on any other network: blocks could arrive blazigly frequently (thousands per second), or they could have large pauses, never mining a block. The former would need very special handling in the sync code, because we assume thhat the chain doesn't move too fast. The latter could cause sync not to trigger properly.

All in all, the insta-mining was meant for a single node dev mode, mostly for running unit/integration tests through truffle or other tools without having to wait for mining. I'll close this PR as something we don't want to support, but if you do see issues in non-insta-mining network, please open a new issue with all the details you have.
