### ISSUE TITLE
Why is my geth using ipv6 to listen

### ISSUE THREAD

**Issue by caiyaonan** [ethereum/go-ethereum#19174]
Geth version: `geth v1.8.23`
OS & Version: CentOS 7

Why is my geth using ipv6 to listen to rpcport and port? There is no way to specify ipv4, my system has closed ipv6.
![image](https://user-images.githubusercontent.com/9747682/53461391-5d2b0680-3a7b-11e9-946c-50715005e65d.png)

**Comment by ImLixp** [comment]
Geth both listen to ipv4 and ipv6.

**Comment by fjl** [comment]
Closing because @ImLixp answer is correct. Geth listens on both IPv4 and IPv6.

**Comment by colourful-land** [comment]
It confused me before, too. To verify IPv4 works, find another computer and connect with `nc` or `telnet` through the IP address of the geth host. But next time @caiyaonan  please copy and paste text instead of pictures. Pictures are not searchable from Google.
