### ISSUE TITLE
Chaindata corrupted due to file descriptor issues on OS/X?

### ISSUE THREAD

**Issue by bokkypoobah** [ethereum/go-ethereum#19177]
#### System information

Geth version: 1.8.23-stable
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour

geth node syncs to mainnet

#### Actual behaviour

Originally fast synced with pre 1.8.23 , with raised file descriptor limits to get around a "too many open files" error, using the command `sudo launchctl limit maxfiles 1000000 1000000`.

I installed 1.8.23 a few days ago, and geth syncing always resulted in 

    BAD BLOCK
    Number: 7260000
    Hash: 0xb4f9639ba930069b84efc6149fbe84315f8b5bf2d12de3efa541bb21e9de3af7
    Error: invalid mix digest

I executed 'removedb' and restarted a fast synced. This kept failing. I have now executed `sudo launchctl limit maxfiles 1000000 1000000` and the syncing is progressing as expected.

Other error messages when the chaindata got corrupted in the past:

    INFO [02-25|16:59:43.097] Block synchronisation started
    WARN [02-25|17:00:16.767] Rolled back headers                      count=160 header=7259455->7259455 fast=0->0 block=0->0
    WARN [02-25|17:00:16.769] Synchronisation failed, dropping peer    peer=31e5e7c0ae800d8f err="retrieved hash chain is invalid"
    WARN [02-25|17:00:17.365] Synchronisation failed, dropping peer    peer=e0f7a02a46d7c52a err="action from bad peer ignored"
    WARN [02-25|17:00:43.594] Rolled back headers                      count=160 header=7259455->7259455 fast=0->0 block=0->0
    WARN [02-25|17:00:43.594] Synchronisation failed, dropping peer    peer=31e5e7c0ae800d8f err="retrieved hash chain is invalid"
    WARN [02-25|17:00:54.654] Rolled back headers                      count=160 header=7259455->7259455 fast=0->0 block=0->0

#### Steps to reproduce the behaviour

Fast sync on OS/X without raising the file descriptor limit

**Comment by bokkypoobah** [comment]
My syncing, with the raised file descriptor limits, degraded after many hours.

The following screen shows the first "rolling back header":
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/17121975/53526994-d2f5a780-3b39-11e9-8a68-a65c50700440.png">

The following screen shows the totally degraded state:
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/17121975/53526872-785c4b80-3b39-11e9-82f4-825a5458b33a.png">

Full geth log - 
[geth.tar.gz](https://github.com/ethereum/go-ethereum/files/2912562/geth.tar.gz)

**Comment by holiman** [comment]
This ticket is a bit old -- we have reworked the file descriptor handling quite a bit since, and there were some additional quirks regarding OSX filesystem that we have navigated around. Please file a new ticket if the error persists. 

To clarify: if geth believes there are more file descriptors available than the OS actually supports, the chaindata _will_ become corrupt, because leveldb will be unable to flush data to disk. So that is expected. 

So the root cause was a mismatch between what geth thought was available and what was actually available, and that has been fixed.
