### ISSUE TITLE
geth process getting killed. (possible oom?)

### ISSUE THREAD

**Issue by inDane** [ethereum/go-ethereum#19181]
#### System information

Geth version: `geth-linux-amd64-1.8.23-c9427004`
OS & Version: Linux 4.15.18-11

#### Expected behaviour
Not Crashing.

#### Actual behaviour
`INFO [02-28|08:58:39.667] Imported new chain segment               blocks=1 txs=154 mgas=7.980 elapsed=3.032s    mgasps=2.631   number=7277903 hash=130511��fb3b85 cache=267.30mB`
`INFO [02-28|08:58:42.405] Imported new chain segment               blocks=1 txs=180 mgas=7.966  elapsed=2.717s    mgasps=2.931   number=7277904 hash=c4397d��890461 cache=267.42mB`
`INFO [02-28|09:00:27.575] Imported new chain segment               blocks=1 txs=215 mgas=7.997  elapsed=4.439s    mgasps=1.801   number=7277905 hash=876d7b��5d9e7b age=1m48s     cache=267.45mB`
`Killed`

#### Steps to reproduce the behaviour
Start geth
`./geth/geth --cache 512 --maxpeers 60 --lightserv 30 --lightpeers 30 --nousb`
and wait 2 days.

My container for geth has got 8GB RAM and yet, geth gets killed because it is demanding more.

Let me know if you need more info and how I can provide it.

Cheers

**Comment by inDane** [comment]
it didnt get killed after constantinople-block... I've got no idea if this is just a coincidence...

**Comment by BBSee** [comment]
I GOT The same “killed” too when I use command ` sudo geth --http --http.addr 0.0.0.0 --http.api personal,eth,net,web3 --http.port 9009  --http.corsdomain '*'  --ws   --ws.addr 0.0.0.0 --ws.port 9008 --ws.api eth,net,web3 --ws.origins '*'` ，nothing else appears in the log console，and then geth  exited abnormally

**Comment by Code0x2** [comment]
same this is still happening to me in 1.9.25

**Comment by ligi** [comment]
@BBSee  you cannot run geth with 4GB of RAM
@Code0x2 can you provide more information about your OS, Hardware, geth version and CLI arguments (ideally in a new issue?)

**Comment by karalabe** [comment]
@BBSee Geth be default uses a fairly large cache (4gb). We try to sanitize it if your machine doens't have a lot of ram, you might still run out on mainnet. I'd personally say a machine with at least 8GB is needed, even that might be a bit on the lo side for a proper full node.

**Comment by karalabe** [comment]
@Code0x2 Please do open a new issue with your detials.

**Comment by taylorjdawson** [comment]
If this occurs for anyone else where all it says is "Killed" this is the OS terminating the process and you can see why by running: `dmesg`. This was my output:
```
[49280.1954282] Out of memory: Killed process 35083 (geth) total-vm:5842944kB, ...
[49281.196482] oom_reaper: reaped process 35083 (geth), ...
```
So definitely a lack of RAM, hope that helps!

**Comment by edwardsky** [comment]
same this is still happening to me in 1.9.25 on ubuntu
/var/log/syslog.1:Jan 28 17:03:32 ethnode kernel: [496339.222751] Out of memory: Killed process 951 (geth) total-vm:13982592kB, anon-rss:9901568kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:22536kB oom_score_adj:0

**Comment by rebasewtf** [comment]
could be a swap issue. 

I am getting the same thing with 32GB Ram

```
Feb  1 08:07:20 localhost kernel: [18023.512326] 1522 pages in swap cache
Feb  1 08:07:20 localhost kernel: [18023.512327] Swap cache stats: add 604932, delete 603479, find 99627/212126
Feb  1 08:07:20 localhost kernel: [18023.512328] Free swap  = 0kB
Feb  1 08:07:20 localhost kernel: [18023.512328] Total swap = 524284kB
```

**Comment by cyrusadkisson** [comment]
This is still happening and I have 8 GB of ram. fast sync

`[272157.031359] [  39469]  1000 39469  1711669  1088459  9228288        0             0 geth
[272157.031361] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=geth,pid=39469,uid=1000
[272157.031405] Out of memory: Killed process 39469 (geth) total-vm:6846676kB, anon-rss:4353836kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:9012kB oom_score_adj:0
[272157.175183] oom_reaper: reaped process 39469 (geth), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB`

**Comment by holiman** [comment]
@cyrusadkisson what's the exact version and command line?

**Comment by cyrusadkisson** [comment]
1.9.25 e7872729 
geth --syncmode fast console

Runs for a while, then "killed". I'm currently around block 7.1M.

**Comment by cyrusadkisson** [comment]
Still crashing ("killed") with

`geth --syncmode fast --datadir /media/cyrus/WD\ red\ 500\ GB/ethereum --cache 2048 --maxpeers 60 --light.serve 30 --light.maxpeers 30 --nousb`

and bizarrely showing an incorrect cache value (I guess? hard to tell which cache param is which) 

`INFO [02-26|17:15:00.471] Allocated cache and file handles         database="/media/cyrus/WD red 500 GB/ethereum/geth/chaindata" cache=1024.00MiB handles=524288`

Are there other command line params I should try? Should I switch to the dev branch? Should I downgrade to 1.9.24 release (is it safe)?
