### ISSUE TITLE
Geth with light mode stuc syncron at block 7,280,000

### ISSUE THREAD

**Issue by dhabitafx** [ethereum/go-ethereum#19195]
i use light mode more than 6 months  , but now is stuc syncon on hardfork block , i dont know what is happend , anyone can help?,

**Comment by AusIV** [comment]
What version of Geth are you running? If less than 1.8.23, it didn't apply the constantinople fork at 7,280,000, and probably considers the post-constantinople blocks to be invalid.

**Comment by dhabitafx** [comment]
solved , after update to 1.8.23 , 
im forgot to update :)

**Comment by ligi** [comment]
great! closing this issue then
