### ISSUE TITLE
goroutine memory leak 

### ISSUE THREAD

**Issue by hadv** [ethereum/go-ethereum#19192]
Thank you for your information @marcosmartinez7 

By the way, I still can reproduce the issue on 1.8.20 & 1.8.21 with 16GB of RAM by sending 10 thousands of tnx (2000 txs/block sealing & txpool always fill up with ~10,000 txs)

And one thing very strange is mining node with public RPC endpoint don't have the issue on the same computing configuration. So I think there's must be memory leak somewhere.

**mining**
![image](https://user-images.githubusercontent.com/941411/51849466-5dd45e00-2352-11e9-8d1e-bde459ffb98e.png)

**un-mining** (**memory leak**)

![image](https://user-images.githubusercontent.com/941411/51849572-9411dd80-2352-11e9-83ba-3feb5f194b8c.png)

_Originally posted by @hadv in https://github.com/ethereum/go-ethereum/issues/17450#issuecomment-458196386_

cc: @karalabe @fjl 
goroutine leak on unmining RPC node

![image](https://user-images.githubusercontent.com/941411/51881076-5d68b100-23ac-11e9-97ca-115fa89a807f.png)

mining node (no leak)

![image](https://user-images.githubusercontent.com/941411/51881086-6a85a000-23ac-11e9-94d1-89f61040936a.png)

_Originally posted by @hadv in https://github.com/ethereum/go-ethereum/issues/17450#issuecomment-458388801_

@holiman hope this will help

https://drive.google.com/open?id=1xK6F95bmLsleuvM9qMQaH2Y7K9Gk2ZFD

_Originally posted by @hadv in https://github.com/ethereum/go-ethereum/issues/17450#issuecomment-458860709_

I don't know yet.. However, there appears to be ~10K routines spawned by `promoteExecutables`, that are waiting on the lock in `feed.go`. One is busy in the loop. 

I think an underlying problem is that a better model for the transaction handling would be to use active objects (one thread/routine) which receives data, instead of each sender spawning it's own goroutine (https://github.com/ethereum/go-ethereum/blob/master/core/tx_pool.go#L1000) . Btw, @hadv , I don't know what code you're running, but the line numbers from your stack does not match up with what's on master now. 

I'm not sure if there are any simple solutions to this ticket, since IMO it would probably require a non-trivial rewrite of tx pool internals.

_Originally posted by @holiman in https://github.com/ethereum/go-ethereum/issues/17450#issuecomment-458877573_

**Comment by ryanschneider** [comment]
Also possibly related: https://github.com/ethereum/go-ethereum/issues/14669#issuecomment-383406707

**Comment by hadv** [comment]
@ryanschneider right, I encountered that problem also on private network when sending up dozen thousands of tnx heavily
