### ISSUE TITLE
the method net_version does not exist/is not available

### ISSUE THREAD

**Issue by yinhaibo** [ethereum/go-ethereum#19194]
Hi, I using current master branch code to catch up with Constantinople, but more error is coming....

#### System information

Geth version: 
Geth
Version: 1.9.0-unstable
Git Commit: 729bf365b5f17325be9107b63b233da54100eec6
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.4
Operating System: linux
GOPATH=/data/gopath
GOROOT=/data/go

OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
I can using MetaMask to query my balance, and develop my smart contract.
The first problem is cannot query value from a smart contract.
My node has keep on current block, the contract has deploy before 30days.
And I want to back v3 database, but it cannot, while I using v1.8.23 or v1.8.22, the error is coming:
Fatal: Error starting protocol stack: database version is v4, Geth 1.8.23-stable only supports v3

#### Actual behaviour
MetaMask cannot connect to my node by RPC.

#### Steps to reproduce the behaviour
Using current master branch, open rpc port like this:
/data/go-ethereum/build/bin/geth --datadir=/data/.ethereum/ --rpc --rpcaddr 0.0.0.0 --rpcapi=eth,net.web3.debug --rpccorsdomain=* --ws --wsorigins=* --syncmode=full --gcmode=archive --cache 40960 --maxpeers 120

#### Backtrace

````
[backtrace]
````

**Comment by yinhaibo** [comment]
The main problem is geth boot arguments error:
--rpcapi=eth,net.web3.debug
There is a dot, not a comma!
--rpcapi=eth,net,web3,debug

**Comment by yinhaibo** [comment]
The problem is my fault.
1.9.0-unstabled version have other problem, in other issue: 
[#19186](https://github.com/ethereum/go-ethereum/issues/19186)

**Comment by qasimraheem** [comment]
hi, i am using stable geth. 

`geth version                                                                                                                             
Geth
Version: 1.10.7-stable
Architecture: amd64
Go Version: go1.16.6
Operating System: darwin
GOPATH=
GOROOT=go`

i am having issues with calling the eth_protocolVersion :
postman error ==> "error": {
        "code": -32601,
        "message": "the method eth_protocolVersion does not exist/is not available"
    }

i attached the geth console and printed all eth functions, where i am getting "protocolVersion: undefined"
i tried with building the geth of current master branch, getting the same issues.

INIT genesis file by :
geth --identity "dappslab" --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api txpool,admin,eth,net,web3,personal --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --ws.api txpool,admin,eth,net,web3,personal --graphql --graphql.corsdomain "*" --datadir /Users/$(whoami)/DappsChain/node1 --port 30303 --networkid 13936 init /Users/$(whoami)/DappsChain/Genesis.json

running geth by :
geth --identity "dappslab" --syncmode full --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api miner,txpool,admin,eth,net,web3,personal --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --ws.api miner,txpool,admin,eth,net,web3,personal --graphql --graphql.corsdomain "*" --datadir /Users/$(whoami)/DappsChain/node1 --port 30303 console

am i doing this wrong or the geth have bug or removed this function?
