### ISSUE TITLE
Cant't miner,when I use miner.start(1) ,it will stop at somewhere.

### ISSUE THREAD

**Issue by 1412904892** [ethereum/go-ethereum#19209]
> miner.start(1)
INFO [03-05|10:04:00.969] Updated mining threads                   threads=1
INFO [03-05|10:04:00.996] Transaction pool price threshold updated price=1000000000
null
> INFO [03-05|10:04:01.286] Commit new mining work                   number=1 sealhash=1c9b0b…852b4c uncles=0 txs=0 gas=0 fees=0 elapsed=277.606ms

After this ,it will print nothing anymore

**Comment by rjl493456442** [comment]
Which consensus algorithm do you use, `Ethash` Or `Clique`? For the `ethash`, please check the init `difficulty` to make sure your machine can beat it :).

**Comment by 1412904892** [comment]
My genesis.json like this:
{
  "config": {
        "chainId": 12,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
  "alloc": {},
  "coinbase"   : "0x0000000000000000000000000000000000000000",
  "difficulty" : "0x20000",
  "extraData"  : "",
  "gasLimit"   : "0x2fefd8",
  "nonce"      : "0x0000000000000042",
  "mixhash"    : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp"  : "0x00"
}
Where I can see which consensus algorithm I use?

**Comment by 1412904892** [comment]
> Which consensus algorithm do you use, `Ethash` Or `Clique`? For the `ethash`, please check the init `difficulty` to make sure your machine can beat it :).

***********************************************
My genesis.json like this:
{
"config": {
"chainId": 12,
"homesteadBlock": 0,
"eip155Block": 0,
"eip158Block": 0
},
"alloc": {},
"coinbase" : "0x0000000000000000000000000000000000000000",
"difficulty" : "0x20000",
"extraData" : "",
"gasLimit" : "0x2fefd8",
"nonce" : "0x0000000000000042",
"mixhash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
"parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
"timestamp" : "0x00"
}
Where I can see which consensus algorithm I use?

**Comment by 1412904892** [comment]
> Which consensus algorithm do you use, `Ethash` Or `Clique`? For the `ethash`, please check the init `difficulty` to make sure your machine can beat it :).

Ethash I used

**Comment by jiten-balla** [comment]
Can you add logs that would be help you out...

**Comment by relaxbao** [comment]
maybe it just needs a little time 
I have encountered this problem,  I changed a new computer , and it started to mining . but i don't know why .

**Comment by adamschmideg** [comment]
We have no logs, so it's difficult to investigate it further. If the problem persists, please open a new issue and attach logs and the command line switches used.
