### ISSUE TITLE
Question: How do you launch GETH using Docker AND get logs

### ISSUE THREAD

**Issue by hito** [ethereum/go-ethereum#19219]
Is it possible to launch GETH using Docker and get logs? Using `& 2>logs` doesn't work.

**Comment by holiman** [comment]
A couple of alternatives, I guess,  `docker logs` being the simplest? 

Otherwise, you can run something like `docker -it -v /my/folder:/logs run ethereum/go-client --entrypoint /bin/bash` and enter the docker bash console, and then `geth ... > /logs/log.txt`.
