### ISSUE TITLE
[Geth PrivateNet] The block height becomes zero after restart.

### ISSUE THREAD

**Issue by apa7** [ethereum/go-ethereum#19217]
The start command as follow:
`geth --datadir /home/eth/privnet/data1 --rpcport 8545 --rpccorsdomain * --rpcapi admin,debug,eth,miner,net,personal,shh,txpool,web3 --rpc --rpcaddr 192.168.12.1 --txpool.accountqueue 200 --dev --dev.period 15`

**Comment by karalabe** [comment]
Did you restart Geth gracefully? It needs to flush it's in-memory state to disk. Otherwise it will revert to the first block that has the full state available. Any logs?
