### ISSUE TITLE
dev.period fails for multiple transactions

### ISSUE THREAD

**Issue by princesinha19** [ethereum/go-ethereum#19221]
**System information**

Geth version: 

> Geth
> Version: 1.8.17-stable
> Git Commit: 8bbe72075e4e16442c4e28d999edee12e294329e
> Architecture: amd64
> Protocol Versions: [63 62]
> Network Id: 1
> Go Version: go1.10
> Operating System: linux
> GOPATH=
> GOROOT=/usr/lib/go-1.10

OS & Version: Linux Ubuntu 16.04

**Expected behaviour**

Should auto mine in case of multiple transactions also

**Actual behaviour**

Not work for multiple transaction some time. It works for single transaction.

**Steps to reproduce the behaviour**

`-dev.period value  Block period to use in developer mode (0 = mine only if transaction pending) (default: 0)`

I used this command in my geth and auto mines the transaction. When I do one transaction like transfer then it works fine but when I do multiple transactions at once means bulk transfer sequentially then it fails in some cases. I need to manually start miner.start(1) at some point.

Please help me with this problem. Also it will be better if anyone can suggest me better approach to do auto mine the transactions.

**Comment by karalabe** [comment]
Please provide some logs, hard to see what happens otherwise. Ideally a repro would be even better.

**Comment by princesinha19** [comment]
@karalabe thanks for your quick response.
I am attaching a snapshot of my geth console.
![geth log](https://user-images.githubusercontent.com/28489437/53879267-05207100-4034-11e9-9b26-592421d42cb2.png)

Steps:-
I am working on a private ethereum network. I called a bulk transfer function. Ideally, all the transfer should happen means all the transaction should be mined automatically because in my geth command I attached `-dev.period 0`. 
You can see for some transaction it works fine but when a particular transaction is submitted it got stuck then, I called miner.start(1) manually then it mined the transaction.

**Comment by princesinha19** [comment]
@karalabe did you used some script for this?
or can you point me to file, where this code for auto mining is placed?
