### ISSUE TITLE
Fatal: Failed to raise file descriptor allowance: invalid argument

### ISSUE THREAD

**Issue by MicahImani** [ethereum/go-ethereum#19225]
I am trying to set up a private ethereum blockchain and deploy with a Solidity Smart contract following this sites instructions: https://hackernoon.com/set-up-a-private-ethereum-blockchain-and-deploy-your-first-solidity-smart-contract-on-the-caa8334c343d

When I run the geth command, I get: 

Micahs-Air:project3 micahimanihall$ geth
INFO [03-06|08:59:41.383] Maximum peer count                       ETH=25 LES=0 total=25
Fatal: Failed to raise file descriptor allowance: invalid argument
Micahs-Air:project3 micahimanihall$ 

#### System information

Geth version: Micahs-Air:project3 micahimanihall$ geth version
Geth
Version: 1.8.22-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.12
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.12/libexec
OS & Version: macOS Mojave 10.14.3
Commit hash : (if `develop`)

#### Expected behaviour
To run a successful private ethereum blockchain. 

#### Actual behaviour
When I run the geth command from the downloaded zip I get:
Last login: Wed Mar  6 07:31:17 on ttys002
Micahs-MacBook-Air:~ micahimanihall$ /Users/micahimanihall/Downloads/geth-alltools-darwin-amd64-1.8.23-c9427004/geth ; exit;
INFO [03-06|09:03:47.270] Maximum peer count                       ETH=25 LES=0 total=25
INFO [03-06|09:03:47.284] Starting peer-to-peer node               instance=Geth/v1.8.23-stable-c9427004/darwin-amd64/go1.11.5
INFO [03-06|09:03:47.284] Allocated cache and file handles         database=/Users/micahimanihall/Library/Ethereum/geth/chaindata cache=512 handles=5120
INFO [03-06|09:03:47.341] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000  ConstantinopleFix: 7280000 Engine: ethash}"
INFO [03-06|09:03:47.341] Disk storage enabled for ethash caches   dir=/Users/micahimanihall/Library/Ethereum/geth/ethash count=3
INFO [03-06|09:03:47.341] Disk storage enabled for ethash DAGs     dir=/Users/micahimanihall/.ethash                      count=2
INFO [03-06|09:03:47.344] Initialising Ethereum protocol           versions="[63 62]" network=1
Fatal: Error starting protocol stack: database version is v4, Geth 1.8.23-stable only supports v3
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

[backtrace]
````

**Comment by fjl** [comment]
This is a known issue with Go 1.12. It is fixed on the master branch, please use it until geth 1.9 is released with a fix for this issue.
