### ISSUE TITLE
where is  the sha3.NewKeccak256()?   

### ISSUE THREAD

**Issue by cancerts** [ethereum/go-ethereum#19241]
import ("github.com/ethereum/go-ethereum/crypto/sha3")

**Comment by holiman** [comment]
It's gone, use `sha3.NewLegacyKeccak256` from golang/x instead

**Comment by holiman** [comment]
To be clear: `"golang.org/x/crypto/sha3"`

**Comment by cancerts** [comment]
ok, thanks ,done

**Comment by theaidem** [comment]
Also, for now we should use the `sha3.NewLegacyKeccak256()` method
