### ISSUE TITLE
About the size of  a externally owned account and contract accounts

### ISSUE THREAD

**Issue by spritehigh** [ethereum/go-ethereum#19253]
Hi Ethereum Team:
    I have a qustion about the sieze of a  externally owned account and contract account,Could you tell me or tell me how to caculate it. It is so important to me!
    Thanks a lot
    Best Wishes to Ethereum team.

**Comment by holiman** [comment]
This is an issue tracker, so I'm gong to close this. There has been some analysis done on this, see https://medium.com/@akhounov/recent-data-on-turbo-geth-performance-f7fb28b06a65 for example
