### ISSUE TITLE
Synchronisation failed, dropping peer valid and Impossible reorg

### ISSUE THREAD

**Issue by UfukAntep** [ethereum/go-ethereum#19258]
Hi there,

I'm working on a project called [Rubykube Workbench](https://github.com/rubykube/workbench). But the "ethereum/client-go:Stable" container gives error.

#### System information

Geth version: `1.8.23-stable-c9427004` (docker container)
OS & Version: Ubuntu 14.04 (Hyper - V)
Project-Commit : (RubyKube Workbench - 658c806`)

#### Expected behaviour

![image](https://user-images.githubusercontent.com/28463089/54201377-8a959c80-44de-11e9-85d5-aaff9e6e4810.png)

#### Actual behaviour
It doesn't look ethereum here. (0)

![image](https://user-images.githubusercontent.com/28463089/54201037-c67c3200-44dd-11e9-9d27-0da8b94f107d.png)

ethereum/client-go:Stable log
![image](https://user-images.githubusercontent.com/28463089/54200967-93d23980-44dd-11e9-8b71-a5f11015055e.png)

Thank You :)

**Comment by karalabe** [comment]
Managed to trace down the issue, will be fixed by #19544.

**Comment by karalabe** [comment]
Fixed on master.
