### ISSUE TITLE
copydb panic because it can't retrieve the state tree in `current height - 64` block

### ISSUE THREAD

**Issue by huangyg11** [ethereum/go-ethereum#19266]
The behavior of copydb ( or fast sync) is to sync state tree in the block of `current height - 64`, but it seems geth don't persist state tree in the block of `current height - 64` before exist (it only persist `current height`, `current height - 1`, `current height - 127`) . So copydb will panic.

If I panic in copydb, I have to start geth and wait it syncing another 64 blocks and exist. Then invoke copydb again, it will work normally.

**Comment by fjl** [comment]
This needs a fix in eth/downloader because copydb uses it to "fast sync" into the local database.

**Comment by holiman** [comment]
I've trie to repro this, switching the pivot point back and forth. Everything seems to work, although I agree it _should_ fail. However, I don't see why it would `panic`, so it would be good to see the stack trace of such a panic. 

(yeah I know it's an old issue, sorry for not picking it up sooner)

**Comment by karalabe** [comment]
The command was dropped on master. We have (manual) state pruning shipped, which is better and faster.
