### ISSUE TITLE
Contract code not matching what's on the blockchain

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1926]
code in the following doesn't match the blockchain: https://github.com/ethereum/go-ethereum/wiki/Contracts-and-Transactions#contract-info-metadata

**Comment by Gustav-Simonsson** [comment]
Could you please elaborate on what exactly is not matching?

**Comment by obscuren** [comment]
I just want to be sure; but the code that's compiled by solidity is **never** stored in its entirety in the state. Only the part that is returned by initial run of the CREATE operation.

**Comment by ethers** [comment]
It looks like this whole section of the wiki https://github.com/ethereum/go-ethereum/wiki/Contracts-and-Transactions#contract-info-metadata is supposed to help verify that the deployed contract is what's on http://dapphub.com

```
source = "contract test {
   /// @notice Will multiply `a` by 7.
   function multiply(uint a) returns(uint d) {
       return a * 7;
   }
}"
contract = eth.compile.solidity(source).test
MyContract = eth.contract(contract.info.abiDefinition)
contenthash = admin.saveInfo(contract.info, "~/dapps/shared/contracts/test/info.json")
MyContract.new({from: primary, data: contract.code}, function(error, contract){
  if(!error && contract.address) {
    admin.register(primary, contract.address, contenthash)
    // put it up on your favourite oldworld site:
    admin.registerUrl(contentHash, "http://dapphub.com/test/info.json")
  }
});
```

Otherwise what is the purpose of all the steps above (compiling, getting the contenthash, registering the contenthash with the deployed contract's address, registering the contenthash with the url)?  Thanks

**Comment by tgerring** [comment]
Bytecode stored in the blockchain will depend on the specific version of solidity and options passed to it, for example, enabling optimization

**Comment by ethers** [comment]
Still not clear what the purpose of https://github.com/ethereum/go-ethereum/wiki/Contracts-and-Transactions#contract-info-metadata  is.

Geth runs `eth.compile.solidity` so it can/does lookup the version of solidity and is the one that passes it options; and all that info is supposed to be in `contract.info` ?

**Comment by tymat** [comment]
If your contract has constructor parameters it will add that as part of the code.  You need to make sure that you are checking against the same version of Solidity that the contract was deployed with.
