### ISSUE TITLE
How to connect 2 evm over the internet(i.e 2 different servers) using geth

### ISSUE THREAD

**Issue by PradneshShinde** [ethereum/go-ethereum#19268]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
Use `addPeer`, or the methods listed here: https://github.com/ethereum/go-ethereum/wiki/Connecting-to-the-network
