### ISSUE TITLE
Unable to connect to Rinkeby web interface

### ISSUE THREAD

**Issue by wbt** [ethereum/go-ethereum#19272]
FYI, attempts to access https://faucet.rinkeby.io/ and https://www.rinkeby.io/ are now returning 
>ERR_CONNECTION_REFUSED:  
This site can’t be reached. 
faucet.rinkeby.io refused to connect.

Other sites are loading fine, so I don't think it's my Internet connection.

**Comment by karalabe** [comment]
Please use https://rinkeby.net temporarily.

**Comment by karalabe** [comment]
io domain back up
