### ISSUE TITLE
panic: interface conversion: interface {} is nil, not *types.Block

### ISSUE THREAD

**Issue by Swader** [ethereum/go-ethereum#19286]
#### System information

Geth version: `1.8.23`
OS & Version: Ubuntu 18.04.2

#### Expected behaviour

After weeks of being in sync, if the full node is offline for a few days due to a power outage, it should be able to catch up and become in sync again.

#### Actual behaviour

```bash
INFO [03-18|07:31:09.725] Disk storage enabled for ethash caches   dir=/home/ethereum/.ethereum/geth/ethash count=3
INFO [03-18|07:31:09.725] Disk storage enabled for ethash DAGs     dir=/home/ethereum/.ethash               count=2
INFO [03-18|07:31:09.787] Initialising Ethereum protocol           versions="[63 62]" network=1
WARN [03-18|07:31:10.802] Head block missing, resetting chain      hash=5414aa…aaf1f5
WARN [03-18|07:31:10.802] Rewinding blockchain                     target=0
panic: interface conversion: interface {} is nil, not *types.Block

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core.(*BlockChain).CurrentBlock(...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:359
github.com/ethereum/go-ethereum/core.(*BlockChain).SetHead(0x40195d4000, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:302 +0x8a0
```

#### Steps to reproduce the behaviour

- Full sync a mainnet node
- Pull the plug
- Wait a few days
- Reset the node

#### Other info

This is part of my [Ethereum on ARM experiment](https://www.reddit.com/r/ethereum/comments/alnmxn/ethereum_on_arm_geth_and_parity_clients_update/). It took a week to fully sync, so starting from 0 is obviously not an acceptable solution, not when there's a chance of this so easily happening again.

I have the full 171GB in chaindata, so all my data is still there from the full sync from before.

This issue has also been posted in [StackExchange](https://ethereum.stackexchange.com/q/68453/31497).

**Comment by holiman** [comment]
```golang
	if currentBlock := bc.CurrentBlock(); currentBlock != nil && currentHeader.Number.Uint64() < currentBlock.NumberU64() {
		bc.currentBlock.Store(bc.GetBlock(currentHeader.Hash(), currentHeader.Number.Uint64()))
}
```
and 
```golang
// CurrentBlock retrieves the current head block of the canonical chain. The
// block is retrieved from the blockchain's internal cache.
func (bc *BlockChain) CurrentBlock() *types.Block {
	return bc.currentBlock.Load().(*types.Block)
}
```

So the calling code expects that `GetCurrentBlock` can return `nil`, however, internally it will blow up on the type conversion. 

Here's some possible ways to solve it: 

- Either store a `nil` block interface at init
- Or do a `nil`-check in `CurrentBlock` before conversion
- Or fix `Reset` to work differently

**Comment by fjl** [comment]
Best way to fix would be not calling `Reset` in `loadLastState`. `Reset` is API that can be used after the BlockChain is already created but `loadLastState` runs in the constructor and some things like current block pointer aren't set up yet.

**Comment by Swader** [comment]
Any fix branch I can test on?

**Comment by holiman** [comment]
Sorry, not yet, it's in my backlog.

**Comment by holiman** [comment]
PR is up for testing: https://github.com/ethereum/go-ethereum/pull/19352 . However, a word of caution

> t took a week to fully sync, so starting from 0 is obviously not an acceptable solution, not when there's a chance of this so easily happening again.

The fix _will_ reset from `0`, since the fix only handles the `panic`. It might be possible to salvage your data, but please not that the PR does _not_ attempt to do so.
