### ISSUE TITLE
eth address

### ISSUE THREAD

**Issue by CooperLee123** [ethereum/go-ethereum#19281]
hello, why my wallet on web shows main account, the default is the account of the index 0,but
why I  geth account new , there is not main account, and the address is equal with each other,
I want to create 100 new address, and when an address received the eth coins, can auto-move the main address or a constant address, but it can't cost gas.  because I found when I have to many addresses, and others send coins to the addresses, I found that it is difficult to administrate, and transfer to one address, it will cost much gas, for exmaple, 50000 * 0.0005 ETH/per = 25 ETH/per. Thank you

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by csplawn918** [comment]
I do apologize that was a complete mistake
