### ISSUE TITLE
Geth installed on CentOS 7 dirty Memory

### ISSUE THREAD

**Issue by Ghost7K** [ethereum/go-ethereum#19293]
Hi there,

we are currently running a few nodes and tried to setup geth on centos7, we was able to install it and to start it, but now geth is in sync we only get dirty cache and not clean cache, means the cli shows us: 

```
INFO [03-12|18:12:51.827] Imported new chain segment               blocks=2 txs=101 mgas=7.230  elapsed=28.694s   mgasps=0.252 number=7356510 hash=75f987…b3d083 age=1h35m33s dirty=79.85MiB
```
We don't know why this is happening.
Please advice

Commands used for Geth installation:

$ sudo yum -y update
$ sudo yum -y install golang
$ sudo yum -y install gmp-devel
$ sudo yum -y install git
$ git clone https://github.com/ethereum/go-ethereum
$ cd go-ethereum/
$ make geth
$ ls -al build/bin/geth

start of geth:

./geth --syncmode "fast" --rpc --rpcaddr 127.0.0.1 --rpcport 9999 --rpcapi="db,eth,net,web3,personal,txpool" --maxpeers 8000 --cache 28000 --keystore /home/keystoresy

**Comment by holiman** [comment]
This is not an error, the `dirty`, is just a count of the size of the dirty-cache, an internal struct. It's an `INFO` message, so no error here :)
