### ISSUE TITLE
Why not use ecdsa Sign

### ISSUE THREAD

**Issue by needkane** [ethereum/go-ethereum#19298]
https://github.com/ethereum/go-ethereum/blob/fb458280d1b0b90156745202677dabbc74187697/crypto/signature_cgo.go#L60

Why use secp256k1?
use prv.Sign (ecdsa Sign) is different with secp256k1?

**Comment by fjl** [comment]
we use secp256k1 library because Ethereum signatures are compatible with Bitcoin. The Go standard library routine for signing is not compatible with the Bitcoin format.
