### ISSUE TITLE
Update Homebrew 'ethereum' package to v1.8.23

### ISSUE THREAD

**Issue by rachhunter** [ethereum/go-ethereum#19295]
Please update go-ethereum on Homebrew to the latest v1.8.23 (currently v1.8.22), so Mac users have easy access to it. Thanks.

**Comment by fjl** [comment]
our Homebrew tap was updated in https://github.com/ethereum/homebrew-ethereum/commit/a2ea7c5168dc93f1a233e5a281555d908ae68585

**Comment by ligi** [comment]
seems to not yet be propagated upstream - nothing we can do about it

**Comment by rachhunter** [comment]
On Homebrew https://formulae.brew.sh/formula/ethereum#default the current available package for Ethereum is v1.8.22 and that's what is downloading from there (the stable version of it). When I run "brew outdated" it doesn't show that there is a later version of ethereum available. Who sorts this out so that v1.8.23 will actually come down the Homebrew tap?

**Comment by rachhunter** [comment]
Ok, I think it hasn't updated because the Homebrew tap is directly linked to this file https://github.com/Homebrew/homebrew-core/blob/master/Formula/ethereum.rb and it still references v1.8.22. Who can update that please?

**Comment by karalabe** [comment]
Please use our own tap https://github.com/ethereum/homebrew-ethereum. Upstream Homebrew is not reliably pulling releases from us, we don't bother with them.
