### ISSUE TITLE
Handling all unhandled errors found through static analysis?

### ISSUE THREAD

**Issue by SamuelMarks** [ethereum/go-ethereum#19297]
A question goes along with #19296, using [automated static analysis tools](https://github.com/mre/awesome-static-analysis#go) one can find a multitude of linting issues and probable bugs.

To highlight a large example, there are 1776 [`!`](https://en.wikipedia.org/wiki/United_States_Declaration_of_Independence) unhandled errors. Many are simple ones like:
https://github.com/ethereum/go-ethereum/blob/fa87929a2fbed11c614d57d43cd64ced15ba80b8/cmd/swarm/access_test.go#L79

Which could be replaced with:
```go
defer func(){
	if err := os.RemoveAll(dataFilename); err != nil {
		panic(err)
	}
}()
```

Outside of tests however, it gets a little more complicated:
https://github.com/ethereum/go-ethereum/blob/245f3146c26698193c4b479e7bc5825b058c444a/rpc/json.go#L223:L228

Would need to change its signature/prototype and all its uses, to guarantee error handling or propogation at every turn.

Uncomfortable with changing that many files without asking permission, because it would impact basically all open PRs.

Thoughts?

**Comment by fjl** [comment]
There are many places where errors are ignored because these errors don't matter in most cases or because it cannot be handled appropriately. A good example is closing a network connection: closing can fail but there is no good way to handle the error.

We would appreciate code changes for places where the error does matter, but AFAIK we handle the ones that matter already.

**Comment by SjonHortensius** [comment]
although these sort of errors are not fixable it might be interesting to output them using `log.Debug`. They might come in handy as context for other issues and static-analysis tools will consider them handled

**Comment by SamuelMarks** [comment]
I would actually still be keen on making all these changes, so that all errors are properly handled.

Just don't want to dedicate the time just to have the PR rejected.

**Comment by fjl** [comment]
Closing this because I stand by my original assessment: there is no way we're ever going to handle every single possible error.
