### ISSUE TITLE
exit does not take an argument and process.exit is unavailable

### ISSUE THREAD

**Issue by jakubgs** [ethereum/go-ethereum#19300]
I'm trying to automate checking if my wallet is unlocked. To do that I'm using the `--exec` option in `console` mode:
```javascript
personal.listWallets[0].status == "Unlocked"
```
The thing is, I can't just get the `stdout`, so I wanted to return `0` or `1` from the `geth` process depending on whether the wallet is unlocked. But it turns out that:

1. The `exit` command does not take an argument.
2. I cannot use the `process.exit` method usually available in NodeJS.

So my question is. How can I change `geth` exit status depending on result of my JS script?

**Comment by karalabe** [comment]
The Geth console is running a strange JavaScript interpreter that's fairly old, unmaintained, not fully up to latest specs, etc. It's good for small interactivity, but not really for production dependence on. You're better off calling the APIs directly over IPC and react yourself externally.

**Comment by jakubgs** [comment]
I see. Thanks for the explanation. I'll close this then.
