### ISSUE TITLE
debug_traceTransaction execution timeout with JS tracers despite long timeout parameter

### ISSUE THREAD

**Issue by tsutsu** [ethereum/go-ethereum#19311]
#### System information

Geth version: `1.9.0-unstable`
OS & Version: macOS 10.14.3, Ubuntu 18.04.2 LTS (occurs on both)
Commit hash : `358535188852bd9d8e351ccbb0d1fa608284a77b`

#### Expected behaviour

`debug_traceTransaction` should execute for at least as long as the timeout specified in the call.

#### Actual behaviour

Even with a very long timeout, and the HTTP RPC server read/write/idle timeouts increased, the RPC response to the traceTransaction call will be `{"error":"execution timeout"}`.

This only occurs when using a JS tracer (e.g. `callTracer`), not when using the default `StructLogger` tracer.

#### Steps to reproduce the behaviour

This works:

```bash
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x217bd9900e5c8945a011b1967d81397a730c53d04fd06d5974400186b1546245", {"disableStorage":true,"disableMemory":true,"disableStack":true,"fullStorage":false,"timeout":"100s"}],"id":1}' "${ETHEREUM_NODE}"
```

...but this fails:

```bash
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x217bd9900e5c8945a011b1967d81397a730c53d04fd06d5974400186b1546245", {"tracer": "callTracer", "timeout": "500s"}],"id":1}' "${ETHEREUM_NODE}"
```

**Comment by tsutsu** [comment]
After looking at the code, it's clear why the `StructLogger` tracer is unaffected—the logic allowing the context to stop the tracer only occurs for JS tracers (https://github.com/ethereum/go-ethereum/blob/master/eth/api_tracer.go#L745-L750)

Also, playing with things a bit, it seems that it's not actually the context deadline being exceeded, but rather a context cancellation being triggered by... something. That is, the failure in JS tracing still occurs if this line:

```go
deadlineCtx, cancel := context.WithTimeout(ctx, timeout)
```

is replaced by

```go
deadlineCtx, cancel := context.WithCancel(ctx)
```

**Comment by tsutsu** [comment]
Other maybe-helpful info: when tracing a block of transactions with `debug_traceBlock`, the tracer gets cancelled for some random—but deterministic—subset of the transactions. If I repeatedly `debug_traceBlock` the same block, it will take different amounts of time to trace (cold vs. warm caches, state rebuilt vs. not) but the same txs will error, whether the complete trace takes 25s or 2s.

**Comment by tsutsu** [comment]
I have a feeling this is related to the race condition described in #19186.

**Comment by kwix** [comment]
I am currently experiencing the same issue. Timeout seems to be completely ignored when using a javascript tracer. 

Geth version: v1.9.0-unstable-6e401792
OS: Debian
Node is running in full archive mode.

**Comment by karalabe** [comment]
I've tried but can't really reproduce this. Alas, I don't have an archive node to run that specific old transaction. Does latest master still exhibit this behavior? Can you reproduce it on a test network?

**Comment by kwix** [comment]
Did some quick tests and it seems it does not reproduce anymore on 1.9.0 stable.

**Comment by Eric-Showers** [comment]
I am experiencing a similar issue with `debug_subscribe` on 1.9.0

Geth version: v1.9.0-stable-52f24617 (archive)
OS: Ubuntu 18.04.2

Similar to OP, the execution timeout issues occurs when using the JS `callTracer` but not with the default StructLogger tracer.

Example payloads:
request
```
{"id": 1, "method": "debug_subscribe", "params": ["traceChain", "0x1e8484", "0x1e8485", {"tracer": "callTracer", "timeout": "150s"}]}
```
response
```
[
  {
    "block": "0x1e8485",
    "hash": "0xd99ad9a1142e57fbd0aea432bd76ef46c0af1ef71d80b6986b945fce95ce9d34",
    "traces": [
      {
        "result": {
          "type": "CALL",
          "from": "0x32be343b94f860124dc4fee278fdcbd38c102d88",
          "to": "0x17d294f910c9891ee648575b1caff2d59bcf2c1d",
          "value": "0x2709e7eab420d7000",
          "gas": "0x4c40d",
          "gasUsed": "0x0",
          "input": "0x",
          "output": "0x",
          "time": "11.389\u00b5s"
        }
      },
      {
        "result": {
          "type": "CALL",
          "from": "0x32be343b94f860124dc4fee278fdcbd38c102d88",
          "to": "0x06c69f734a0240cb31678412f04eb0ce8f39258b",
          "value": "0x2b5c0282441c70000",
          "gas": "0x4c40d",
          "gasUsed": "0x0",
          "input": "0x",
          "output": "0x",
          "time": "10.085\u00b5s"
        }
      },
      {
        "error": "execution timeout"
      },
      null,null,null,null,null,null,null,null
    ]
  }
]
```
I have not been able to reproduce this with `debug_traceTransaction` or `debug_traceBlock`. I am assuming that `debug_subscribe` is related - but let me know if this belongs elsewhere.

**Comment by Eric-Showers** [comment]
Might be important to add that my archive node is still completing it's initial sync. I expect it to complete by tomorrow, then I will return to this issue.

**Comment by tehnetaholic** [comment]
I am also affected by this issue

**Comment by liamaharon** [comment]
this is affecting me on v1.9.9. would be great if it was fixed

**Comment by bulgakovk** [comment]
I'm experiencing the same behaviour using `debug_traceBlockByHash` - one of the transactions doesn't a have stack trace in a produced array of traces. However, direct tracing the transaction (with `debug_traceTransaction`) gives expected and correct response (1.9.13 archive node)

**Comment by holiman** [comment]
@bulgakovk that sounds like something very different. Can you file a new ticket with more details about that?

**Comment by karalabe** [comment]
Looking at the debug_subscribe issue, that seems to work as expected, just your node was super overloaded if you are archive syncing. The first 2 tx that successfully did trace took 10-10 seconds. Those were plain value transfers that don't even do any EVM execution. If that took 10 secs, it probably means leveldb was compacting and preventing database reads.

**Comment by karalabe** [comment]
@liamaharon Pls open a new issue with some details. The above ones were solved or false issues, so if you still have some problems, that's unrelated and we'd need some more infos.
