### ISSUE TITLE
cannot find package "github.com/ethereum/go-ethereum/crypto/sha3"

### ISSUE THREAD

**Issue by zulhfreelancer** [ethereum/go-ethereum#19320]
#### System information

Geth version: 1.8.23 (stable)
OS & Version: OSX
Commit hash: N/A

#### Expected behaviour

Running `go get github.com/ethereum/go-ethereum/crypto/sha3` should be no problem.

#### Actual behaviour

```
go get github.com/ethereum/go-ethereum/crypto/sha3

package github.com/ethereum/go-ethereum/crypto/sha3: cannot find package "github.com/ethereum/go-ethereum/crypto/sha3" in any of:
	/usr/local/opt/go/libexec/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOROOT)
	/Users/zulhilmi/go/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOPATH)
```

#### Steps to reproduce the behaviour

1. `cd` into a Go project inside your `$GOPATH`
2. Run `go get github.com/ethereum/go-ethereum github.com/ethereum/go-ethereum/crypto/sha3`

#### Backtrace

```
go get github.com/ethereum/go-ethereum \
github.com/ethereum/go-ethereum/common \
github.com/ethereum/go-ethereum/common/hexutil \
github.com/ethereum/go-ethereum/core/types \
github.com/ethereum/go-ethereum/crypto/sha3 \
github.com/ethereum/go-ethereum/rlp \
github.com/ethereum/go-ethereum/rpc

package github.com/ethereum/go-ethereum/crypto/sha3: cannot find package "github.com/ethereum/go-ethereum/crypto/sha3" in any of:
	/usr/local/opt/go/libexec/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOROOT)
	/Users/zulhilmi/go/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOPATH)
```

#### Notes

Downgrading to Geth [v1.8.20](https://github.com/ethereum/go-ethereum/releases/tag/v1.8.20) (24d727b) seems like solve the problem.

**Comment by karalabe** [comment]
We've upstreamed Keccak256 into Go's crypto library `golang.org/x/crypto/sha3` so there's no need to host a fork in this repo. We're using the upstream ourselves too.

**Comment by denuoweb** [comment]
> We've upstreamed Keccak256 into Go's crypto library `golang.org/x/crypto/sha3` so there's no need to host a fork in this repo. We're using the upstream ourselves too.

So how to fix the issue?

**Comment by karalabe** [comment]
Import `golang.org/x/crypto/sha3` in your own code.

**Comment by denuoweb** [comment]
Not my code. A package I use for smart contracts now is broken

**Comment by karalabe** [comment]
Ask them to fix their code and vendor dependencies next time to avoid upstream changes breaking things..

**Comment by gpankaj** [comment]
I also hit this issue, with 1.15.5 (on Mac) I ran "go get" and reran application, everything ran fine. Please not i ran "go get" without any arguments from GOROOT/src/<github.com>/<userid>/<repo_name>/

**Comment by bobtista** [comment]
This code is still in https://goethereumbook.org/wallet-generate/ so I ended up here too - I think it's safe to replace the import with "golang.org/x/crypto/sha3" and use hash := sha3.New256()
