### ISSUE TITLE
Clique:  Additional RPC Method to Rank Misbehaving Signers

### ISSUE THREAD

**Issue by jwasinger** [ethereum/go-ethereum#19321]
Hi @karalabe wanted to get your feedback on an idea I had:

For clique, we can rank signers by how many blocks they fail to sign and return a suggestion for signers that can be voted out.

~I think a good heuristic for assessing misbehavior could be the count of the difficulty that a given signer has contributed during the current epoch.~  see the suggestion below.

**Comment by jwasinger** [comment]
> I think a good heuristic for assessing misbehavior could be the count of the difficulty that a given signer has contributed during the current epoch.

Edge case to consider is a signer that was recently voted in (and will be 'misbehaving' according to this metric).  I think instead we can measure a ratio of `difficulty that was contributed / difficulty that could have been contributed since the establishment of the signer (if it was voted in this epoch)`

**Comment by fjl** [comment]
@karalabe Doesn't like the idea too much because the information is already there and can be retrieved with existing APIs. We all agree it'd be more convenient to have it in the node though.

**Comment by jwasinger** [comment]
That's a fair point.

**Comment by karalabe** [comment]
@holiman Added a `clique_status` method a while back that helps detect bad signers.
