### ISSUE TITLE
Brew tap ethereum/ethereum fails

### ISSUE THREAD

**Issue by pdyraga** [ethereum/go-ethereum#19335]
#### System information

Geth version: `N/A`
OS & Version: OSX
Commit hash : `N/A`

#### Expected behaviour

I expect `brew tap ethereum/ethereum` to be executed successfully. 

#### Actual behaviour
```
$ brew tap ethereum/ethereum
==> Tapping ethereum/ethereum
Cloning into '/usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 9 (delta 2), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
Error: Aleth (formerly cpp-ethereum) has been removed from Homebrew. Please install binary releases from https://github.com/ethereum/aleth/releases.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum/cpp-ethereum.rb
exit
Error: Cannot tap ethereum/ethereum: invalid syntax in tap!
```

#### Steps to reproduce the behaviour

Execute `brew upgrade && brew tap ethereum/ethereum`

Might be related to the PR merged yesterday: https://github.com/ethereum/homebrew-ethereum/pull/222

**Comment by ligi** [comment]
https://github.com/ethereum/go-ethereum/issues/19173 might be connected

**Comment by karalabe** [comment]
@ligi Nope `Error: Cannot tap ethereum/ethereum: invalid syntax in tap!`

**Comment by ligi** [comment]
OK - just thought as brew seems to be broken currently due to #19173 this might be related

**Comment by nonsense** [comment]
Submitted a PR with a fix, just a side note in case someone tries to reproduce this - `brew upgrade && brew tap ethereum/ethereum` was not enough for me, since I already had the repo cloned. I had to manually remove it from `/usr/local/Homebrew/Library/Taps/` in order to trigger the failure.

**Comment by axic** [comment]
Merged the fix in homebrew.

**Comment by nonsense** [comment]
@pdyraga could you please check if the problem is solved now, and close the issue if this is the case :)

**Comment by pdyraga** [comment]
Yes, I can confirm the problem is solved. Thank you.

**Comment by alfonsocv12** [comment]
Thanks for the fix
