### ISSUE TITLE
Downloading file from Swarm times out

### ISSUE THREAD

**Issue by folex** [ethereum/go-ethereum#19334]
#### System information

Swarm: both `edge` Docker container and https://swarm-gateways.net/bzz:/

#### Expected behaviour

File is downloaded.

#### Actual behaviour

Downloading hangs, and eventually times out.

#### Steps to reproduce the behaviour
There are two problematic files:
1. https://swarm-gateways.net/bzz:/f290584708603673fe1da3b70a942a7830ece6552815f9350ab8173e99473b53
2. https://swarm-gateways.net/bzz:/3c4f07d3d5919c13e080b560283a2405151559d5aacd53c5b394b2d6738ebc0e/ 

Or in command line:
```bash
wget https://swarm-gateways.net/bzz:/f290584708603673fe1da3b70a942a7830ece6552815f9350ab8173e99473b53
``` 
```bash
wget https://swarm-gateways.net/bzz:/3c4f07d3d5919c13e080b560283a2405151559d5aacd53c5b394b2d6738ebc0e/
```

The first one always hangs on 1024/1787 KB, the second one stopped downloading at all.

#### Additional info
This started to happen with another file on 25 Mar around 15:00 GMT. Before that, the first file was downloading just fine.

**Comment by nonsense** [comment]
@folex it is not clear which version of Swarm you are using. Also Swarm currently does not provide guarantees over your content through the https://swarm-gateways.net gateway.

Please talk to us at the Gitter channel `ethereum/swarm` or open a new issue at https://github.com/ethersphere/swarm if you still have issues with uploading/downloading content.
