### ISSUE TITLE
personal_lockAccount

### ISSUE THREAD

**Issue by tymat** [ethereum/go-ethereum#1935]
personal_unlockAccount can take a 3rd parameter to set a timeout for account unlocking which is nice but being able to lock accounts at any time should be available to users.

**Comment by obscuren** [comment]
:+1:

**Comment by skydogch** [comment]
:+1:

**Comment by obscuren** [comment]
@bas-vk please get this integrated in the new RPC stack.

**Comment by grizscom** [comment]
+1 for request

**Comment by bas-vk** [comment]
It will be part of the new rpc implementation.

**Comment by mnoster** [comment]
yess
