### ISSUE TITLE
install with brew for mac not up to date (installs 1.8.22 & no devel tag)

### ISSUE THREAD

**Issue by spolrot** [ethereum/go-ethereum#19356]
Two issues:
1) `brew install ethereum` installs 1.8.22 and not 1.8.23 (expected behavior)
2) `brew install ethereum -devel` gives 
`Error: No devel block is defined for ethereum`

Attached: my ethereum.rb file, downloaded with `brew tap ethereum/ethereum`
[ethereum.rb.txt](https://github.com/ethereum/go-ethereum/files/3026485/ethereum.rb.txt)

#### System information

Geth version: irrelevant
OS & Version: OSX
Commit hash : irrelevant

#### Expected behaviour
1) `brew install ethereum` installs 1.8.23
2) `brew install ethereum -devel` installs 1.9.0

#### Actual behaviour
1) `brew install ethereum` installs 1.8.22
2) `brew install ethereum -devel` gives `Error: No devel block is defined for ethereum`

#### Steps to reproduce the behaviour
type the commands

**Comment by ligi** [comment]
related: #19295

**Comment by karalabe** [comment]
Please use out own brew tap https://github.com/ethereum/homebrew-ethereum. Upstream is apparently hot pulling/updating releases properly, so we don't rely on them.
