### ISSUE TITLE
Will you accept a high quality PR to implement EIP615?

### ISSUE THREAD

**Issue by bmann** [ethereum/go-ethereum#19354]
We have a grant reviewer who would like to ensure that we have a good chance of having code accepted.

If we get funded to build a high quality [EIP615 Static Jumps & Subroutines](https://eips.ethereum.org/EIPS/eip-615) implementation, will you accept a PR to add it to your client?

@expede from our team is a VM expert and will be the one supporting the implementation.

**Comment by holiman** [comment]
That's hard to say in advance. We're always open to high quality PRs, but, 

- That EIP will be require very extensive changes, 
- That EIP is still not fully specified, 

If the EIP is accepted for hard fork inclusion, then we'll be glad if someone does the work for us -- but if it isn't, then I don't think we'll want to maintain it within geth, if it's only going to be used for private networks. Just my 5c

**Comment by bmann** [comment]
@holiman thanks. Yes, I mean if it is included for the hard fork.
