### ISSUE TITLE
Documentation Request: Geth to Solc Mapping

### ISSUE THREAD

**Issue by karysto** [ethereum/go-ethereum#19365]
This is more a documentation request, but I think it would be very helpful as a developer community if we had a mapping of solc to geth compatibility. Right now we're in the dark about what's known to work and what isn't, and it causes a lot of frustration for developers such as myself who want to upgrade between Geth and Solc versions and maintain secure and up-to-date software.

I've searched and asked on Gitter, Discord, the Ethereum Stack Exchange, and I can't seem to find documentation on this anywhere. Are there initiatives in the works to get a mapping like this published to Github?

**Comment by karalabe** [comment]
Hmmm, could you explain a bit? Solc is just an EVM compiler. We can run any valid EVM code. In theory, everything should work.

**Comment by karysto** [comment]
@karalabe I think you're right if we assume that everyone is using the most up-to-date version of Geth and Solc, where the newest opcodes are available in both. I'm thinking about use cases where users are either using older versions of Geth and newer versions of solc where the newest opcodes do not exist, and so compiled contracts will be compiled correctly by solc but the generated ABI code will fail at run-time when they hit Geth, if that makes sense.

**Comment by hectopod** [comment]
A simple example would be that we compile a smart contract on our local machine with a newer version of Solc and deploy it on a remote machine with an older Geth version.

**Comment by fjl** [comment]
You can configure solc to compile to a specific EVM hard-fork target. See this section of the Solidity documentation: https://solidity.readthedocs.io/en/latest/using-the-compiler.html#target-options
