### ISSUE TITLE
swarm: implement NAT piercing

### ISSUE THREAD

**Issue by attila-lendvai** [ethereum/go-ethereum#19363]
Many nodes will be behind [NAT](https://en.wikipedia.org/wiki/Network_address_translation), and it would be nice to be able to connect to them by [piercing through the NAT](https://en.wikipedia.org/wiki/NAT_traversal).

# ipfs
ipfs is using [libp2p](https://libp2p.io/).

* [go libp2p status](https://github.com/ipfs/go-ipfs/issues/57#issuecomment-382943598) (2018-04)

# tor
* [ticket for NAT piercing](https://trac.torproject.org/projects/tor/ticket/4960)
* [tech report](https://research.torproject.org/techreports/tor-nat-plan-2012-08-22.pdf)

**Comment by karalabe** [comment]
We already have support for UPnP. I know of one place where Ubuntu firewall blocks it, but generally it kind of works. Anything in particular you are referring to with this issue?

**Comment by attila-lendvai** [comment]
@karalabe this is about dealing with network setups where UPnP is not available, and/or making the network code simpler at the same time by using something like libp2p.

i created this ticket based on a discussion with @zelig , maybe he can chime in.

**Comment by zelig** [comment]
libp2p  issues https://github.com/ethereum/go-ethereum/pulls?utf8=%E2%9C%93&q=is%3Apr++label%3Aarea%3Alibp2p+

The question is how much bang for the buck.
i would not put this too high  priority

**Comment by nonsense** [comment]
Let's continue this discussion at `ethersphere/swarm` because this is opened in the context of Swarm, and doesn't refer to a known bug/issue with Geth.
