### ISSUE TITLE
core/vm: EIP-1344 - CHAINID opcode

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#19368]
hot candidate for the next HF:

https://github.com/ethereum/EIPs/pull/1344
Discussions at https://ethereum-magicians.org/t/add-chain-id-opcode-for-replay-protection-when-handling-signed-messages-in-contracts/1131

**Comment by fjl** [comment]
EIP-1344 is still in last call status. We will follow allcoredevs decision to implement or not implement.

**Comment by karalabe** [comment]
This is on master.
