### ISSUE TITLE
handler.go has invalid import

### ISSUE THREAD

**Issue by debragail** [ethereum/go-ethereum#19388]
handler.go has invalid import.

"github.com/ethereum/go-ethereum/log" returns 404

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
https://github.com/ethereum/go-ethereum/tree/master/log
