### ISSUE TITLE
The block number is always at 4139095 when use rinkeby network.  

### ISSUE THREAD

**Issue by spursy** [ethereum/go-ethereum#19382]
My geth version is 1.8.18-unstable, My block number is alway at 4139095.

When I check logs, I found my sync node always resync block chain data:

<img width="1318" alt="屏幕快照 2019-04-03 上午11 01 31" src="https://user-images.githubusercontent.com/11460991/55450290-2bb8d400-5601-11e9-873a-8e1d082f3fdd.png">

**Comment by karalabe** [comment]
Please provide some more logs.
