### ISSUE TITLE
Geth full sync error: bad block 53145

### ISSUE THREAD

**Issue by MiaZmy1221** [ethereum/go-ethereum#19407]
#### System information

Geth version: `1.9.0-unstable`
OS & Version: Ubuntu 16.04
Commit hash : c79dc39175a0a4335b5612da7aba394d0e30edf6

#### Expected behaviour
Sync smoothly.

#### Actual behaviour
Bad block error.
![image](https://user-images.githubusercontent.com/44105172/55670692-995d3e00-5855-11e9-947b-60f36319283b.png)

**Comment by MiaZmy1221** [comment]
./geth --syncmode "full" --cache 2048 --datadir "/data/.ethereum" 2>> test.log

**Comment by karalabe** [comment]
Where did you get that Geth build from? Our repository does not contain commit `c79dc39175a0a4335b5612da7aba394d0e30edf6`

I.e. https://github.com/ethereum/go-ethereum/commit/c79dc39175a0a4335b5612da7aba394d0e30edf6 -> 404

**Comment by MiaZmy1221** [comment]
Thank you for your response. I found that this bug had nothing to do with your official version of go-ethereum. I will close this issue. Thank you again.
