### ISSUE TITLE
dev.periods fails to process some/multiple transactions

### ISSUE THREAD

**Issue by princesinha19** [ethereum/go-ethereum#19404]
**System information**

```
Geth version:
Geth
Version: 1.8.17-stable
Git Commit: 8bbe720
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
OS & Version: Linux Ubuntu 16.04
```
#### Expected behaviour

Should auto mine in case of multiple transactions also

#### Actual behavior

Not work for multiple transaction some time. It works for single transaction.

#### Steps to reproduce the behaviour

`-dev.period value Block period to use in developer mode (0 = mine only if transaction pending) (default: 0)`

I used this command in my geth and auto mines the transaction. When I do one transaction like transfer then it works fine but when I do multiple transactions at once means bulk transfer sequentially then it fails in some cases. I need to manually start miner.start(1) at some point.

If you are using some scripts then please point me to that script or code.

**Comment by holiman** [comment]
I tried reproing this, using this little js script
```javascript

function reload(){
    loadScript("multitx.js")
}

function tx(){
    return { "from": eth.accounts[0],
        "to": "0xdddddddddddddddddddddddddddddddddddddddd",
        "value": 1,
    }
}

function batch(){
    for(var i = 0 ; i < 1000 ; i++){
        eth.sendTransaction(tx())
    }
}
```
And then starting geth with `build/bin/geth --dev console`, and calling `loadScript("multitx.js")`. Invoking the `batch()` a couple of times, and then checking `eth.getTransactionCount(eth.accounts[0])` shows that all txs have been mined. 

Please provide more info about how to reproduce this -- what type of "bulk transfer" are you using?

**Comment by princesinha19** [comment]
@holiman Thanks for your reply.
I am sending concurrent transactions with 10 or more transactions in a row. These all are erc20 token transfer. Like https://multisender.app/#/.
I solved this issue by making a tweak in this script https://ethereum.stackexchange.com/questions/3151/how-to-make-miner-to-mine-only-when-there-are-pending-transactions.

**Comment by holiman** [comment]
How do you send 'concurrent transactions in a row'? Do you first generate and later send, or use sendTransaction() - like my script?

**Comment by princesinha19** [comment]
No, first I create an array for transactions to be mined. which consists of recipient and amount to transfer.
Then, I call **myContract.methods.transfer(to, amount).send()** to send token to the recipient with for loop.

**Comment by holiman** [comment]
From `geth`'s perspective, a transaction is a single signed transaction from an EOA. It may, in the case of ERC20 multi-send, cause several internal calls which causes ERC20 token movements, but as far as geth knows, it's still just a transaction. 

So, with that in mind, could you elaborate on

- Are you doing several _transactions_ or having problem with single transactions (containing multiple ERC20-sends)?
- What do you mean by "fails in some cases". Do you see any error message, either in the geth console or in the jsonrpc response message? Are the _transactions_ failing or the internal ERC20-transfers failing? 
- Is the for-loop an on-chain for-loop within `myContract` or are you also looping on the javascript side?

**Comment by princesinha19** [comment]
> Are you doing several transactions or having problem with single transactions (containing multiple ERC20-sends)?

**When doing multiple transactions.**

> What do you mean by "fails in some cases". Do you see any error message, either in the geth console or in the jsonrpc response message? Are the transactions failing or the internal ERC20-transfers failing?

**I didn't got any error messages. When transaction got submitted then, geth doesn't get mine that submitted the transaction. It remains in pending transactions. I could check that by eth.pendingTransactions.**

> Is the for-loop an on-chain for-loop within myContract or are you also looping on the javascript side?

**I am using it javascript side.**

can you point me to the code of dev-periods?

**Comment by holiman** [comment]
I modified my script
```javascript

function reload(){
    loadScript("multitx.js")
}

function tx(){
    return { "from": eth.accounts[0],
        "to": "0xdddddddddddddddddddddddddddddddddddddddd",
        "value": 1,
    }
}

function logPending(){
    console.log("pending: #" + eth.pendingTransactions.length)
}
function batch(){
    for(var i = 0 ; i < 500 ; i++){
        eth.sendTransaction(tx())
    }
    logPending()
    setTimeout(logPending, 1000)
}
```

example output:
```
> batch()
pending: #2
undefined
> pending: #0
```
Checking eth.pendingTransactions _immediately_ after submitting the transactions shows that they wind up in `pending` a short while before they are included. I am unable to otherwise reproduce the error.

Here is where clique decides not to mine a block; https://github.com/ethereum/go-ethereum/blob/master/consensus/clique/clique.go#L583 
Here is where clique is woken up for new transactions: https://github.com/ethereum/go-ethereum/blob/master/miner/worker.go#L472

**Comment by holiman** [comment]
You should not need to use any such script. It should "just work" with `--dev`, without having to resort to any javascript-magic like that.

**Comment by karalabe** [comment]
In `--dev` mode, Geth automatically starts and stops the miner. If you have an extra script that also messes with the miner, it might very well be a race that causes the hang. @princesinha19 could you try without any script, just simply Geth in `--dev` mode?

**Comment by princesinha19** [comment]
yes, right @holiman. I think we should improve --dev.period so, that bulk transfer of ERC20 can succeed.

**Comment by holiman** [comment]
Great. So can you help me reproduce the error you're getting? If you show me the exact scripts and invocations, we can go from there

**Comment by princesinha19** [comment]
I am creating an erc20 token using openzeppline.
```
await myContract.deploy({
	data: '0x' + bytecode,
	arguments: [tokenName, tokenSymbol, amount]
}).send({
	from: wallet.walletAddress,
	gas: 2120000
}).on('receipt', (receipt) => {});
```

Then I am using for loop for multiple transactions.
```
for(i=0; i<array.length;i++){
myContract.methods.transfer(toWallet, amount).send({
    from: wallet.walletAddress
}).then(async (result) => {
     console.log(result)
});
};
```
Let array length to be 20. Then it mines 2-3 transactions and get stopped with pending transaction. Then I need to manually start the mining to mine the transactions.

**Comment by holiman** [comment]
I tried reproing this with a bash script, to get some more paralellism in
```bash
account=$(curl -X POST  -H "Content-Type: application/json"  --data '{"jsonrpc":"2.0","method":"eth_coinbase","params":[],"id":1}' http://localhost:8545 | jq .result)

for i in {1..64}; do
        data="{\"jsonrpc\":\"2.0\",\"method\":\"eth_sendTransaction\",\"params\":[{\"from\": $account, \"to\": $account, \"value\":\"0x1\"}],\"id\":$i}"
        curl -X POST   -H "Content-Type: application/json" --data "$data" http://localhost:8545 &
done

sleep 3
curl -X POST  -H "Content-Type: application/json"  --data '{"jsonrpc":"2.0","method":"eth_pendingTransactions","params":[],"id":1}' http://localhost:8545 | jq .result
curl -X POST  -H "Content-Type: application/json"  --data "{\"jsonrpc\":\"2.0\",\"method\":\"eth_getTransactionCount\",\"params\":[$account,\"latest\"],\"id\":1}" http://localhost:8545 | jq .result
```
Running geth with `build/bin/geth --dev --rpc`. I get _zero_ drops, against master. If larger numbers of transactions are used, they will be dropped, since a too-far-off nonce gap will cause drops -- but those would not be present in `pending` later. 

Could you try running geth with `--verbosity 6` and paste the logs after you hit the error?

**Comment by princesinha19** [comment]
Okay @holiman. I will try and let you know.
