### ISSUE TITLE
rpc: server cancels contexts too early

### ISSUE THREAD

**Issue by samczsun** [ethereum/go-ethereum#19409]
#### System information

```Geth
Version: 1.9.0-unstable
Git Commit: 083b900c1f42d2859d951e2a954e3214f6836165
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.12.1
Operating System: linux
GOPATH=
GOROOT=/snap/go/3417
```
I'm running a patched version with some extra RPC functionality but this bug exists in master as well.

#### Expected behaviour
RPC calls such as `eth_call` should return the correct data

#### Actual behaviour
`eth_call` is inconsistent, sometimes returning an empty response.

#### Steps to reproduce the behaviour
Here's a request which fetches the number of owners on the [Foundation MultiSig](https://etherscan.io/address/0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae#code). I would expect this call to return `0x07`, every time.
However, when making this request to a node running geth v1.9.0, the result is occasionally empty. Give it a try!
```curl 127.0.0.1:8545 -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae","to":"0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae","data":"0x4123cb6b"},"latest"],"id":1}'```

This problem was introduced in #18471 (cc @fjl) and is caused by the server cancelling the context associated with the request before the request is actually finished.

When a request is received, `serveSingleRequest` is called:
https://github.com/ethereum/go-ethereum/blob/bca140b73dc107676c912d87f6fe9c352d5fd0d8/rpc/server.go#L94-L116

`serveSingleRequest` calls `handleMsg`:
https://github.com/ethereum/go-ethereum/blob/bca140b73dc107676c912d87f6fe9c352d5fd0d8/rpc/handler.go#L134-L148

`handleMsg` in turn calls `startCallProc`, which launches a goroutine:
https://github.com/ethereum/go-ethereum/blob/bca140b73dc107676c912d87f6fe9c352d5fd0d8/rpc/handler.go#L220-L228

At this time, control flow is returned to `serveSingleRequest`, where the `defer` on line 102 runs. This defer causes the handler to cancel the context before waiting for requests to finish:
https://github.com/ethereum/go-ethereum/blob/bca140b73dc107676c912d87f6fe9c352d5fd0d8/rpc/handler.go#L154

Most RPC calls don't care about this context, but some such as `eth_call` do:
https://github.com/ethereum/go-ethereum/blob/bca140b73dc107676c912d87f6fe9c352d5fd0d8/internal/ethapi/api.go#L735-L740

When the context is cancelled, the EVM is stopped and execution is aborted resulting in an empty response.

**Comment by karalabe** [comment]
Fixed on master.
