### ISSUE TITLE
Throttling in propagating pending transactions to sealer nodes ?

### ISSUE THREAD

**Issue by puneet-khushwani-bits** [ethereum/go-ethereum#19419]
Hi,

#### System information

We have setup a private network of **POA** Geth with 3 Sealer Nodes (**SN**) & 2 nodes (**WN**) which is being used by the application to submit transactions & fetch data. We have set block generation time as 3 seconds.

Geth version: `1.8.23-stable`
OS & Machine details: CentOs 7 (4 core 16 GB RAM)

Geth command to start SN

geth  --nodiscover --networkid 2000 --datadir /my_folder/node_u --keystore /my_folder/keystore --mine --unlock 0x* --password /my_folder/pwfile  --port 30301 --miner.gastarget 150000000 --miner.gaslimit 150000000 --miner.gasprice 0x3B9ACA00 --txpool.accountslots 2048 --txpool.globalslots 50000 --txpool.accountqueue 100000 --txpool.globalqueue 20480000

Geth command to start WN

geth  --nodiscover --networkid 2000 --datadir /my_folder/node_u --keystore /my_folder/keystore  --port 30301 --rpc --rpcvhosts "*" --rpcaddr myhostname  --rpcapi eth,net,web3,personal,txpool --rpcport 8541 --ws --wsapi eth,net,web3,personal,txpool --wsaddr myhostname  --wsport 8551 --wsorigins "*"  --txpool.accountslots 2048 --txpool.globalslots 50000 --txpool.accountqueue 100000 --txpool.globalqueue 20480000

#### Experiment

We are submitting transactions at a rate of ~300 per second on WN for ~ 1 hour.

#### Expected behaviour

As miner.gaslimit & miner.gastarget are enough to accommodate ~1300 transactions in a block,  we were expecting blocks being mined with ~ 900 transactions in each block

#### Actual behaviour

After a few initial seconds we observe blocks being mined with ~ 400 transactions in each block. After that the number of transactions making into these blocks drastically decreases to ~ 60 .

The number of pending transactions (as seen from txpool.status) on WN were gradually increasing and went up to ~100,000 after which we stopped the submission script.

However on the sealer nodes this number wasn't going above ~ 60. This we think was the reason for blocks mining only ~20 transactions.

NOTE : Please note that on none of the machines CPU utilization is going above 50%. Memory utilization is also  fine

####

In cases where rate of incoming transactions is high ~1000 per second, do we have some throttling in place which (within a few minutes) results in reducing the rate of propagation of pending transactions from WN to SN's ?

While finding solutions to this, we managed to figure out a couple of workarounds to restore this propagation rate.

1. Restarting WN.
2. On WN, remove any one of SN enode entry via admin.peers and add it back again via admin.addPeer.
3. This scenario used to work when we had WN on  geth v1.7.3

Can we get help with better solution(s) to our problem.

**Comment by karalabe** [comment]
Could you try your test scenario with a build from the master branch and see how that performs? We've added a few optimizations around transaction signature recoveries. We may need more, but would be nice to know how they compare to the stable release.

**Comment by holiman** [comment]
I'd echo what Peter said, we reworked tx pool things quite a lot in 1.9. Transactions were basically piling up goroutines, and I can imagine that would have an even worse effect on the sealer node, which not only needs to shuffle txs through the pool, but also regenerated state for mining and compete with the mining threads for state. 

So, please check if this is still an issue on 1.9, otherwise I'll let the bot close this in a couple of weeks.
