### ISSUE TITLE
flag provided but not defined: -rpccorsdomain

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#19415]
After upgrade to `1.8.24-stable-4e13a09c` it no longer starts with the error message:

```
Fatal: Error starting protocol stack: leveldb/storage: corrupted or incomplete CURRENT file
flag provided but not defined: -rpccorsdomain
flag provided but not defined: -rpccorsdomain
flag provided but not defined: -rpccorsdomain
flag provided but not defined: -rpccorsdomain
```

I use:
`--rpccorsdomain "*"`

**Comment by raugfer** [comment]
Same is happening with `--rpcvhosts`

`flag provided but not defined: -rpcvhosts`

**Comment by MysticRyuujin** [comment]
It seems that my Fatal error is unrelated lol

**Comment by jmcnevin** [comment]
This looks like the problem commit: https://github.com/ethereum/go-ethereum/commit/e872ba7a9e8123a4010198ee8dfaada9f71fa24a

**Comment by c0deright** [comment]
Same here. Broke my geth node running with `--rpcvhosts`.

**Comment by karalabe** [comment]
Fixed and building a new release now.

**Comment by c0deright** [comment]
If some on Ubuntu is looking for the 1.8.23 release:

http://ppa.launchpad.net/ethereum/ethereum/ubuntu/pool/main/e/ethereum/
