### ISSUE TITLE
flag provided but not defined: -rpccorsdomain . how to upgrade to 1.8.25

### ISSUE THREAD

**Issue by MetalRock** [ethereum/go-ethereum#19421]
I saw was released 1.8.25 with fix.
But when i trying to do:
apt-get install --only-upgrade geth

Reading package lists... Done
Building dependency tree       
Reading state information... Done
geth is already the newest version (1.8.24+build18410+xenial).
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.

why i can't upgrade?

**Comment by karalabe** [comment]
Did you do an `apt-get update` first to pull in the new packages from the PPA?

**Comment by MetalRock** [comment]
Of course I did update .

**Comment by karalabe** [comment]
The binaries are on PPA https://launchpad.net/~ethereum/+archive/ubuntu/ethereum/+packages, not sure what might the issue be here.
