### ISSUE TITLE
Served eth_getBlockByNumber ? context canceled? what is going on?

### ISSUE THREAD

**Issue by hunter1861** [ethereum/go-ethereum#19428]
WARN [04-10|05:33:03.071] Served eth_getBlockByNumber              conn=127.0.0.1:46600 reqid=1 t=262.386μs err="context canceled"

**Comment by ligi** [comment]
sounds related to #19409

**Comment by OliverBui** [comment]
I have same issue for `light` node after upgrade node to latest version

**Comment by rjl493456442** [comment]
@OliverBui #19430 is an urgent fix for this. But I'm not sure whether it is an elegant solution. Have to ask the review from @fjl.

**Comment by OliverBui** [comment]
@rjl493456442 thanks, I will follow up this issue.
