### ISSUE TITLE
{'code': -32000, 'message': 'account unlock with HTTP access is forbidden'}

### ISSUE THREAD

**Issue by BeOleg** [ethereum/go-ethereum#19422]
Hi there,

We started getting this error when trying to unlock the wallet few days ago.
I was wondering if it is introduced by one of the last commits and how do we get past it. 

#### System information

Geth version: latest from docker (client go)
OS & Version: Linux

#### Expected behaviour
Unlock should work if the presonal module is included in RPC server.

#### Actual behaviour

Unlock does not work

#### Steps to reproduce the behaviour
Try to unlock the wallet via HTTP

#### Backtrace

````
{'code': -32000, 'message': 'account unlock with HTTP access is forbidden'}
````

**Comment by holiman** [comment]
Yes, this is because of https://github.com/ethereum/go-ethereum/pull/17037 . If you _really_ want to enable unlock, despite having HTTP exposed on the server and thus being susceptible to attackers making transactions on your behalf, then you can use `allow-insecure-unlock` to bypass this protection.

**Comment by BeOleg** [comment]
How to do it? in the toml config file?

**Comment by holiman** [comment]
Our new alternative is https://geth.ethereum.org/clef/Overview

**Comment by BeOleg** [comment]
@holiman is `allow-insecure-unlock` defined within the `eth_conf.toml` file?

**Comment by BeOleg** [comment]
@holiman by googling this you can see it is not documented

**Comment by BeOleg** [comment]
Found the answer, had to read the code https://github.com/ethereum/go-ethereum/pull/17037/files#diff-cb9d33469f8611afc502fe58402158a2R92

Better docs would help ppl like me to save time.

Thanks for your work on this project.

**Comment by holiman** [comment]
Well, I did provide the command line switch in my first response... Anyway, it's a command line switch we want to discourage, because it's more often than not a dangerous way to solve a usecase, and there are other, better, ways.

**Comment by imprakrut** [comment]
When you run/sync a Geth node, add this `--allow-insecure-unlock` to the command

**Comment by nerkn** [comment]
we cant install rpc without http, but also we cant use unlock with http. very clever.
