### ISSUE TITLE
JSON-RPC serve examples don't work

### ISSUE THREAD

**Issue by dbabits** [ethereum/go-ethereum#1942]
Trying as documented, none of the curl commands work. 

1) All return the same error, some examples:
```
docker run -it -p 8545:8545 -p 30303:30303 ethereum/client-go --rpc

[ec2-user@ip-172-31-38-111 bank.js]$ curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' http://127.0.0.1:30303                                                                                         
curl: (52) Empty reply from server

[ec2-user@ip-172-31-38-111 bank.js]$ curl -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":1}' http://127.0.0.1:8545                                                                                                 
curl: (52) Empty reply from server
```
2) Separate issue: all curl commands in the documentation are missing the urls (which I added above)

**Comment by dbabits** [comment]
I suspect it is because geth prompts you to type 'y' to a disclaimer, and insided a docker container there's nobody to type anything.
I did not see in geth help any option to avoid this prompt - is this true?

**Comment by obscuren** [comment]
You can do a `mkdir -p $HOME/.ethereum/keystore`

**Comment by dbabits** [comment]
@obscuren,
Thanks for the reply, but could you clarify:
I'm executing the documented docker command and it doesn't work(see original post)
Do you suggest the documentation is wrong, or the docker image has a bug, or it's a bug in geth and rpc server is broken?
Where exactly do you suggest to put that mkdir command-in the Dockerfile?

**Comment by obscuren** [comment]
You'll have to excuse me, my knowledge on docker is extremely limited. What you can do in order to bypass the disclaimer problem is by creating the directory I mentioned above.

**Comment by dbabits** [comment]
Can anybody else help with this? All I'm trying to do is copy-paste documented commands, and they don't work.
thanks.

**Comment by tymat** [comment]
@caktux can probably help with this.  Basically you need to create the $HOME/.ethereum/keystore directory inside your docker container.  You won't be able to do anything with RPC or IPC until you agree to the license which you are prompted to accept when you start geth for the first time.  The workaround is to create the keystore folder which bypasses this check.

**Comment by caktux** [comment]
Running the container with `-it` allows you to type `y` at the disclaimer; bypassing the disclaimer right from the Dockerfile wouldn't be very responsible, but you can add that `mkdir` in a local version. The documented commands have been updated, they were missing `--rpcaddr "0.0.0.0"`, since geth listens on localhost by default, the RPC commands would have only worked from within the container. You should also replace that `0.0.0.0` with your host IP for better security.

**Comment by dbabits** [comment]
@caktux, Thank you, this worked. 
Wrt the disclaimer and having to type 'y' - I need to be able to deploy many containers in an automated fashion, using docker orchestration tools,  interactive input wouldn't be an option. How do you propose this should work?

**Comment by tymat** [comment]
@dbabits   You can use docker commit to take a snapshot of your container after you've acknowledged the license and use that to do your mass deployments.

**Comment by fjl** [comment]
@obscuren is there any way we can get rid of this interactive disclaimer thing? Maybe after the Homestead release?

**Comment by obscuren** [comment]
@fjl yes. We can remove it in 1.4 including develop

**Comment by dbabits** [comment]
@caktux, do you know where I can find solc compiler?
And, I think it belongs in that docker image, otherwise the documented eth_compileSolidity RPC call doesn't work. (same probably true of other compilers)
I want to build a full image where all geth functions would be usable. 
Thanks.

**Comment by tymat** [comment]
solc and lll are part of [webthree-umbrella](https://github.com/ethereum/webthree-umbrella)

**Comment by dbabits** [comment]
Thanks!  I'm utterly lost in the multitude of links and sites. 

In particular, what is the difference between [gavofyork.gitbooks.io](https://gavofyork.gitbooks.io/turboethereum/content/index.html) vs [ethereum.gitbooks.io](https://ethereum.gitbooks.io/frontier-guide/content/) ?

"The umbrella project for all of C++ Web Three implementation" vs "Go ethereum: Official golang implementation of the Ethereum protocol"

**Comment by tymat** [comment]
I am not sure about the gavofyork link but that might be Gavin's fork of the official documentation.  Have you tried comparing the diffs between the two versions?

**Comment by fjl** [comment]
The disclaimer has been removed in geth 1.3.2.
