### ISSUE TITLE
Failure calling eth_estimateGas on master branch

### ISSUE THREAD

**Issue by dannieb** [ethereum/go-ethereum#19429]
Hi there,

We're on the current master branch and we're seeing issues when calling to get the gas estimate of a transaction.

#### System information

Geth
Version: 1.9.0-unstable
Git Commit: 22e1d2ce034a8674327e1cf6c01aff3fca403f71
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10

#### Steps to reproduce the behaviour
1. Using python3 and the web3 python package version 4.8.2
2. web3.eth.estimateGas(transaction)

Throws an exception.  

Geth logs show:
Served eth_estimateGas                   conn=10.10.44.245:36482 reqid=2 t=192.47µs err="context canceled"

**Comment by rjl493456442** [comment]
This issue is related to #19409

**Comment by karalabe** [comment]
Fixed on master.
