### ISSUE TITLE
try send coins - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Master-01** [ethereum/go-ethereum#19434]
Hellow!

#### System information
Geth version: v1.8.25 (console)
OS & Version: Windows 7 (latest updates)
Run command: bin\geth.exe --syncmode="light" --datadir="walletdir" --rpc --rpccorsdomain="https://wallet.ethereum.org"
--unlock="* * mywallet * * " --password="* * myfile password * *"

#### Issue
I runned latest geth.exe and unlock my wallet, then I go to the page at "https://wallet.ethereum.org/" and I see my coins there, I click "SEND" there and put address where to transfer my coins and the amount, after which I get an error in the geth console:

#### Console 
`panic: runtime error: invalid memory address or nil pointer dereference`
`[signal 0xc0000005 code = 0x0 addr = 0x0 pc = 0xb38c57]`
`goroutine 32 [running]:`
`github.com/ethereum/go-ethereum/les.(*peer).GetRequestCost(0xc0002d2160, 0xc, 0x1, 0x0)
        C: /gopath/src/github.com/ethereum/go-ethereum/les/peer.go: 166 + 0xa7`
`github.com/ethereum/go-ethereum/les.(*LesTxRelay).send.func1(0x158fea0, 0xc0002d2160, 0xc026561d01)
        C: /gopath/src/github.com/ethereum/go-ethereum/les/txrelay.go: 121 + 0x55`
`github.com/ethereum/go-ethereum/les.(*requestDistributor).nextRequest(0xc0001920f0, 0x0, 0x0, 0x0, 0x0)
        C: /gopath/src/github.com/ethereum/go-ethereum/les/distributor.go: 195 + 0x2b8`
`github.com/ethereum/go-ethereum/les.(*requestDistributor).loop(0xc0001920f0)
        C: /gopath/src/github.com/ethereum/go-ethereum/les/distributor.go: 129 + 0x86`
`created by github.com/ethereum/go-ethereum/les.newRequestDistributor
        C: /gopath/src/github.com/ethereum/go-ethereum/les/distributor.go: 80 + 0x100`

And geth terminated!

**_What to do? How to transfer my coins from my wallet?_**

**Comment by karalabe** [comment]
We're releasing a hotfix for this in a couple of hours.

**Comment by rs-blashyrkh** [comment]
Same bug with 1.8.23, it began 1-2 days ago. Upgrade to 1.8.25 didn't help. Sync mode is "light" too.

**Comment by karalabe** [comment]
This issue has been fixed in https://github.com/ethereum/go-ethereum/pull/19437, and just shipped in [Geth v1.8.26](https://github.com/ethereum/go-ethereum/releases/tag/v1.8.26). Please allow half an hour or so for the binaries to be built and pushed out. Sorry for any inconvenience.
