### ISSUE TITLE
geth.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

### ISSUE THREAD

**Issue by MetalRock** [ethereum/go-ethereum#19435]
After upgrade to 1.8.25, geth working 15-20 minutes and throwing this

Apr 10 10:46:12 Ubuntu-1604-xenial-64-minimal geth[1769]:         /build/ethereum-40AXyQ/ethereum-1.8.25+build18425+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/les/txrelay.go:121 +0x4e
Apr 10 10:46:12 Ubuntu-1604-xenial-64-minimal geth[1769]: github.com/ethereum/go-ethereum/les.(*requestDistributor).nextRequest(0xc420204960, 0x0, 0x0, 0x0, 0x0)
Apr 10 10:46:12 Ubuntu-1604-xenial-64-minimal geth[1769]:         /build/ethereum-40AXyQ/ethereum-1.8.25+build18425+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/les/distributor.go:195 +0x296
Apr 10 10:46:12 Ubuntu-1604-xenial-64-minimal geth[1769]: github.com/ethereum/go-ethereum/les.(*requestDistributor).loop(0xc420204960)
Apr 10 10:46:12 Ubuntu-1604-xenial-64-minimal geth[1769]:         /build/ethereum-40AXyQ/ethereum-1.8.25+build18425+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/les/distributor.go:129 +0x7f
Apr 10 10:46:12 Ubuntu-1604-xenial-64-minimal geth[1769]: created by github.com/ethereum/go-ethereum/les.newRequestDistributor
Apr 10 10:46:12 Ubuntu-1604-xenial-64-minimal geth[1769]:         /build/ethereum-40AXyQ/ethereum-1.8.25+build18425+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/les/distributor.go:80 +0x10b
Apr 10 10:46:12 Ubuntu-1604-xenial-64-minimal systemd[1]: geth.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 10 10:46:12 Ubuntu-1604-xenial-64-minimal systemd[1]: geth.service: Unit entered failed state.
Apr 10 10:46:12 Ubuntu-1604-xenial-64-minimal systemd[1]: geth.service: Failed with result 'exit-code'.

this how i start it 
`geth --lightpeers 250 --syncmode "light" --rpc  --rpccorsdomain "*" --rpcaddr 0.0.0.0 --rpcport 8080 --port 30303 --rpcapi db,eth,net,web3,personal --wsaddr 0.0.0.0 --ws --wsorigins "*" --wsport "8445" --cache 4096 --maxpeers 250`

who can explain what is wrong?

**Comment by karalabe** [comment]
This issue has been fixed in https://github.com/ethereum/go-ethereum/pull/19437, and just shipped in [Geth v1.8.26](https://github.com/ethereum/go-ethereum/releases/tag/v1.8.26). Please allow half an hour or so for the binaries to be built and pushed out. Sorry for any inconvenience.
