### ISSUE TITLE
eth.getBalance(eth.accounts[1])  return zero

### ISSUE THREAD

**Issue by henry0504** [ethereum/go-ethereum#19448]
Hi there,

Basic private network transaction  account[0]  to account[1]，why cannot success？ account[1] balance still return zero .

thx!

#### System information

Geth version: `geth version`
Geth
Version: 1.8.26-stable
Git Commit: cdae1c59abc32f85debfa29577fbf1ed036ebf73
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.5
Operating System: windows
GOPATH=
GOROOT=C:\go

OS & Version: Windows

Commit hash : (if `develop`)

#### Actual behaviour

> eth.getBalance(eth.accounts[1])
0
> eth.getBalance(eth.accounts[0])
55000000000000000000

> amount=web3.toWei(0.98)
"980000000000000000"

> personal.unlockAccount(eth.accounts[0])
Unlock account 0xd4c763bab31bff1af0755834ae82f14f55f1a44c
Passphrase:
true

> eth.sendTransaction({from:eth.accounts[0],to:eth.accounts[1],value:amount})
"0x132d793f3a942f4c91e2ecf760e93392ff255661d78d71bc209251ec3b27c550"

> eth.getBalance(eth.accounts[1])
0

**Comment by ruopuzi** [comment]
You have to check if this tx was packed into block successful, please check it with:

`eth.getTransactionReceipt("0x132d793f3a942f4c91e2ecf760e93392ff255661d78d71bc209251ec3b27c550")`

check the `status` field in the returned result.

**Comment by henry0504** [comment]
> eth.getTransactionReceipt("0x132d793f3a942f4c91e2ecf760e93392ff255661d78d71bc209251ec3b27c550")
null

how  to pack  tx into  block?  thx

**Comment by henry0504** [comment]
> You have to check if this tx was packed into block successful, please check it with:
> 
> `eth.getTransactionReceipt("0x132d793f3a942f4c91e2ecf760e93392ff255661d78d71bc209251ec3b27c550")`
> 
> check the `status` field in the returned result.

eth.getTransactionReceipt("0x132d793f3a942f4c91e2ecf760e93392ff255661d78d71bc209251ec3b27c550")
null

how to pack tx into block? thx

**Comment by salanfe** [comment]
eth.getTransactionReceipt is null when well the receipt does not exists. A receipt is created when a transaction gets MINED.

so either your sendTransaction failed and your transaction never reached any blockchain. That can be checked with eth.getTransactionByHash.

But most likely you need to wait for the transaction to be mined.

you can pull eth.getTransactionReceipt until it does not return null anymore. Or wait for upcoming blocks and look for your transaction.

**Comment by holiman** [comment]
This has been correctly answered, closing
