### ISSUE TITLE
Sending a transaction using Local Light client panics and stops the local node.

### ISSUE THREAD

**Issue by Chemavb** [ethereum/go-ethereum#19451]
Hi, I have the following error after using a local light client node to send a transaction programmatically.

#### System information

Geth version: 1.8.25-stable
OS & Version: Linux, Ubuntu 18.04

#### Expected behaviour
Sending a transaction using a light client should send the transaction without error.

#### Actual behaviour
It seems that it attempts to send the transaction but instantly after that the client panics and transaction is never sent (I try to search it in etherscan and it can't be located).

#### Steps to reproduce the behaviour
I try to send a transaction programmatically using web3 contracts API but the client panics giving the following error shown in Backtrace section. After that, execution of the client node is terminated.

#### Backtrace
INFO [04-11|19:22:41.784] Submitted transaction                    fullhash=0x83b108d012790f20f983becdf5a529d2d993cb843c4c2fdb8e5bf2b5659d11e2 recipient="< contract address to receive the transaction >"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb105c0]

goroutine 69 [running]:
github.com/ethereum/go-ethereum/les.(*peer).GetRequestCost(0xc428d66630, 0xc, 0x1, 0x0)
	/build/ethereum-3tTh57/ethereum-1.8.25+build18425+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/les/peer.go:166 +0xa0
github.com/ethereum/go-ethereum/les.(*LesTxRelay).send.func1(0x11134e0, 0xc428d66630, 0xc42033fd01)
	/build/ethereum-3tTh57/ethereum-1.8.25+build18425+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/les/txrelay.go:121 +0x4e
github.com/ethereum/go-ethereum/les.(*requestDistributor).nextRequest(0xc42021a5a0, 0x0, 0x0, 0x0, 0x0)
	/build/ethereum-3tTh57/ethereum-1.8.25+build18425+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/les/distributor.go:195 +0x296
github.com/ethereum/go-ethereum/les.(*requestDistributor).loop(0xc42021a5a0)
	/build/ethereum-3tTh57/ethereum-1.8.25+build18425+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/les/distributor.go:129 +0x7f
created by github.com/ethereum/go-ethereum/les.newRequestDistributor
	/build/ethereum-3tTh57/ethereum-1.8.25+build18425+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/les/distributor.go:80 +0x10b

**Comment by karalabe** [comment]
This was fixed in v1.8.26. Please update.
