### ISSUE TITLE
Transactions are generated but not published once node is not in full sync

### ISSUE THREAD

**Issue by BeOleg** [ethereum/go-ethereum#19455]
#### System information

Geth version: `latest from docker`
OS & Version: Linux

#### Expected behaviour
A transaction should not be published if node is behind

#### Actual behaviour
A transaction is generated, returned to the client, but is not published on the network

#### Steps to reproduce the behaviour
Try to publish transactions with an unsynced/not fully synced geth node

For example, this is a tx we have sent to a client
https://n.exchange/order/OSBHZ0/
https://etherscan.io/tx/0xf0b3f99a382478b49a8b5195054970dcf9b834dedad7bd1c81a41e3cafa32692

As you can see it is 'not found' on ether scan.

To make matters worse, once the node comes to full sync and/or is restarted by the devops administrator, sometimes the transaction is published to the network and sometimes it remains stuck.

This resulted, in our case, in several cases of sending coins to customers several times, which was not very pleasant.

**Comment by JayMaree** [comment]
Even while the node is fully synced :(

**Comment by holiman** [comment]
@BeOleg if you use an unsynched node, are you supplying nonce and gasprice yourself? Otherwise it may use the wrong nonce and isn't accepted by network

**Comment by JayMaree** [comment]
> @BeOleg if you use an unsynched node, are you supplying nonce and gasprice yourself? Otherwise it may use the wrong nonce and isn't accepted by network

How can I validate/change this? We use the `eth.sendTransaction` command and set a fixed gasprise.

**Comment by holiman** [comment]
Look at the tx, check against etherscan if the nonce is correct. Should be whatever the last outgoing tx nonce is, plus one

**Comment by JayMaree** [comment]
> Look at the tx, check against etherscan if the nonce is correct. Should be whatever the last outgoing tx nonce is, plus one

That's the problem. Etherscan cannot find the tx.

**Comment by holiman** [comment]
Look at the tx, check the sender account on etherscan. The tx is in the node, as you say, you have it locally. eth_getTransaction

**Comment by JayMaree** [comment]
No. The sendTransaction gives me a txid. When I run the eth.getTransaction command it does not give me any details (nor etherscan). In fact, getTransactions gives me a null.

**Comment by holiman** [comment]
Then it probably immediately drops it for some reason. Any server logs?

**Comment by holiman** [comment]
Or check pending

**Comment by JayMaree** [comment]
> Or check pending

```
> txpool.status
{
  pending: 0,
  queued: 0
}
> txpool.content
{
  pending: {},
  queued: {}
}
```

The `geth/nodes/LOG` file does not contain usefull errors. It seems the peer list is empty for about 15 minutes now. I restarted the geth process.

**Comment by BeOleg** [comment]
@holiman any updates on the above?

**Comment by holiman** [comment]
We need more info. When a tx is submitted, there's some text in the server logs. It may say why it's being dropped (which it shouldn't). I mean the standard out from the geth node.

**Comment by holiman** [comment]
An unsynched node is not capable of providing correct nonces. So it will likely send it to peers, but it will be dropped by network. I need logs or txs to verify if that's the case

**Comment by BeOleg** [comment]
Ok, how should I post our entire node's log, and is it even safe to do so.

**Comment by BeOleg** [comment]
Also, what is the log path for the log you are looking for? @holiman

**Comment by BeOleg** [comment]
In the meanwhile, I am sharing my `eth_config.toml`, I have just tried to publish a tx and whilst the node returned a tx, id, it is not visible on the blockchain, `eth_syncing` is `False`.
```
[Eth]
NetworkId = 1
SyncMode = "fast"
NoPruning = false
LightBandwidthIn = 1000
LightBandwidthOut = 5000
LightPeers = 100
OnlyAnnounce = false
DatabaseCache = 512
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
MinerGasFloor = 8000000
MinerGasCeil = 8000000
MinerGasPrice = 1000000000
MinerRecommit = 3000000000
MinerNoverify = false
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Ethash]
CacheDir = "ethash"
CachesInMem = 2
CachesOnDisk = 3
DatasetDir = "/root/.ethash"
DatasetsInMem = 1
DatasetsOnDisk = 2
PowMode = 0

[Eth.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Shh]
MaxMessageSize = 1048576
MinimumAcceptedPOW = 2e-01
RestrictConnectionBetweenLightClients = true

[Node]
DataDir = "/root/.ethereum"
omitempty = ""
IPCPath = "geth.ipc"
HTTPPort = 9090
# HTTPHost = 0.0.0.0
# GraphQLPort = 8547
HTTPVirtualHosts = ["0.0.0.0"]
HTTPModules = ["net", "web3", "eth", "shh", "personal"]
WSPort = 8546
WSModules = ["net", "web3", "eth", "shh"]
InsecureUnlockAllowed = true

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
BootstrapNodes = ["enode://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@52.16.188.185:30303", "enode://3f1d12044546b76342d59d4a05532c14b85aa669704bfe1f864fe079415aa2c02d743e03218e57a33fb94523adb54032871a6c51b2cc5514cb7c7e35b3ed0a99@13.93.211.84:30303", "enode://78de8a0916848093c73790ead81d1928bec737d565119932b98c6b100d944b7a95e94f847f689fc723399d2e31129d182f7ef3863f2b4c820abbf3ab2722344d@191.235.84.50:30303", "enode://158f8aab45f6d19c6cbf4a089c2670541a8da11978a2f90dbf6a502a4a3bab80d288afdbeb7ec0ef6d92de563767f3b1ea9e8e334ca711e9f8e2df5a0385e8e6@13.75.154.138:30303", "enode://1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d89d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082@52.74.57.123:30303", "enode://979b7fa28feeb35a4741660a16076f1943202cb72b6af70d327f053e248bab9ba81760f39d0701ef1d8f89cc1fbd2cacba0710a12cd5314d5e0c9021aa3637f9@5.1.83.226:30303"]
BootstrapNodesV5 = ["enode://06051a5573c81934c9554ef2898eb13b33a34b94cf36b202b69fde139ca17a85051979867720d4bdae4323d4943ddf9aeeb6643633aa656e0be843659795007a@35.177.226.168:30303", "enode://0cc5f5ffb5d9098c8b8c62325f3797f56509bff942704687b6530992ac706e2cb946b90a34f1f19548cd3c7baccbcaea354531e5983c7d1bc0dee16ce4b6440b@40.118.3.223:30304", "enode://1c7a64d76c0334b0418c004af2f67c50e36a3be60b5e4790bdac0439d21603469a85fad36f2473c9a80eb043ae60936df905fa28f1ff614c3e5dc34f15dcd2dc@40.118.3.223:30306", "enode://85c85d7143ae8bb96924f2b54f1b3e70d8c4d367af305325d30a61385a432f247d2c75c45c6b4a60335060d072d7f5b35dd1d4c45f76941f62a4f83b6e75daaf@40.118.3.223:30307"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Dashboard]
Host = "localhost"
Port = 8080
Refresh = 5000000000
```

**Comment by holiman** [comment]
Log should contain nothing secret, however, the full thing isn't needed. Re path: no particular path. It's the standard output from the geth process.

**Comment by BeOleg** [comment]
Ok docker logs then.... sec

**Comment by BeOleg** [comment]
Here is a log example for a failed TX

```
{"log":"INFO [04-18|21:28:53.828] Submitted transaction                    fullhash=0xd5168d6a09e497cf66424f4215997c30a17d336314b5cf06d1a9ba940fff0774 recipient=0xc46135930cd34D5DA336490a09EB03a0a7cDAa6e\n","stream":"stderr","time":"2019-04-18T21:28:53.829315395Z"}
```

The transaction is submitted but it goes to stderr for some reason, mhm

**Comment by BeOleg** [comment]
Any updates on this @holiman this issue keeps happening

**Comment by karalabe** [comment]
So, in Ethereum, every transaction has a nonce. It's a sequentially incrementing number from 0 (per account). In order for the network to accept a transaction, the nonce needs to be exactly the next one for your account. Now, if the node you are sending the transaction from is not synced, then the node cannot guess the correct nonce, so you need yo supply it yourself.

Te debug this issue, we need to see which exact transaction you sent, how did you supply the nonce, the gas price? We need all the details, not just the logs.

Now, even if you supply the correct nonce and gas price and details, you still need to ensure you have a live connectivity to the network. You'd need to ensure `admin.peers` has a consistent number of peers.

Btw, you can also try to use a light client, which is lighter, syncs faster, etc.
