### ISSUE TITLE
log overflowed with BAD block on goerli nodes (Error: recently signed)

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#19467]
this is an issue emerged from conversations on the goerli gitter channel: https://gitter.im/goerli/testnet?at=5cb44c0720fbe911eebae793

seems the solution could be to just not display this case as an error:

> That was a weird design decision to display an error. As long as your client keeps syncing it's totally expected behaviour

**Comment by karalabe** [comment]
It's a consensus error. A signer is creating invalid blocks. Fix the signer, fix the issue :P
