### ISSUE TITLE
Failed to start smart card hub

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#19469]
Hi there,

#### System information

Geth version: INFO [04-16|08:07:09.253] Maximum peer count                       ETH=25 LES=0 total=25
**WARN [04-16|08:07:09.290] Failed to start smart card hub, disabling: dial unix /run/pcscd/pcscd.comm: connect: A socket operation encountered a dead network.** 
INFO [04-16|08:07:09.302] Starting peer-to-peer node               instance="Geth/GETH DA ROCK DEVELOP RINKEBY/v1.9.0-unstable-85b6823d/windows-amd64/go1.12.3"
INFO [04-16|08:07:09.302] Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
INFO [04-16|08:07:09.303] Allocated cache and file handles         database=C:\\projects\\ethereum_develop_rinkeby\\testnet_data\\geth\\chaindata cache=512.00MiB handles=8192
INFO [04-16|08:07:14.265] Persisted trie from memory database      nodes=355 size=50.69KiB time=1.9949ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [04-16|08:07:14.272] Initialised chain configuration          config="{ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: true EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1035301 Constantinople: 3660663  ConstantinopleFix: 4321234 Engine: clique}"
INFO [04-16|08:07:14.277] Initialising Ethereum protocol           versions="[63 62]" network=4 dbversion=4
WARN [04-16|08:07:14.277] Upgrade blockchain database version      from=4 to=5
INFO [04-16|08:07:14.343] Loaded most recent local header          number=4141829 hash=6bc096â€¦c99b3e td=7626392 age=1w6d11h
INFO [04-16|08:07:14.343] Loaded most recent local full block      number=4141829 hash=6bc096â€¦c99b3e td=7626392 age=1w6d11h
INFO [04-16|08:07:14.343] Loaded most recent local fast block      number=4141829 hash=6bc096â€¦c99b3e td=7626392 age=1w6d11h
INFO [04-16|08:07:14.350] Loaded local transaction journal         transactions=0 dropped=0
INFO [04-16|08:07:14.351] Regenerated local transaction journal    transactions=0 accounts=0
INFO [04-16|08:07:14.419] New local node record                    seq=15 id=5c149de27d17962b ip=127.0.0.1 udp=30303 tcp=30303

OS & Version: Windows
Commit hash : 
v1.9.0-unstable-85b6823d

#### Expected behaviour

no error
#### Actual behaviour
**WARN [04-16|08:07:09.290] Failed to start smart card hub, disabling: dial unix /run/pcscd/pcscd.comm: connect: A socket operation encountered a dead network.**

**Comment by liuhuanhui** [comment]
me too

**Comment by darkcandy** [comment]
same here

**Comment by gballet** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/19439, waiting for the merge.

**Comment by gballet** [comment]
#19439 has been merged, closing. Reopen an issue if the problem perists.
