### ISSUE TITLE
How big is the ethereum main net data? 

### ISSUE THREAD

**Issue by mxito3** [ethereum/go-ethereum#19477]
I want to sync data of ethereum main network. I want to know how big is the ethereum main net data?  I have 500G SSD,Is it enough for that?

**Comment by sdfgsdfgd** [comment]
A year ago when I was active that was more than enough. It should still be more than enough. Looking forward to opinion of another brother

**Comment by karalabe** [comment]
Current stable Geth uses about 177GB on a fresh fast sync. The next release will only need 131GB, but it will still take a few weeks until that's out.
