### ISSUE TITLE
Mebank

### ISSUE THREAD

**Issue by Srichon-Boontharikwong** [ethereum/go-ethereum#19474]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)
[Specification.]
#### Expected behaviour
[Wallet autosave]

#### Actual behavior
[66853827319@srichon.net ]

#### Steps to reproduce the [behaviour]

Of transactions. 
#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
really unclear what you want
