### ISSUE TITLE
Documentation skips a bunch of steps Issue

### ISSUE THREAD

**Issue by wbdeedcoin** [ethereum/go-ethereum#19482]
The documentation goes from 0 to 100 real quick.

> Assuming you have a valid Go development environment set up, godep installed and the go-ethereum repository checked out correctly, you can build the generator with:

This setup should be covered first.

**Comment by adamschmideg** [comment]
Hm, I should really write this

**Comment by MariusVanDerWijden** [comment]
@wbdeedcoin The current documentation has some more steps do achieve this: https://geth.ethereum.org/docs/install-and-build/installing-geth#build-go-ethereum-from-source-code
I'll close this issue now, please feel free to reopen the issue if you think there should be more documentation than that!
