### ISSUE TITLE
Inconsistent Result for Web3 Constant Method Call

### ISSUE THREAD

**Issue by geekybcresearcher** [ethereum/go-ethereum#19488]
Hi All,

Deployed a local private Ethereum environment. While trying to invoke a constant method of a solidity contract getting inconsistent results. Sometimes the result is returned and mostly not.

When I tried to fetch the data from geth command line was able to successfully list down the results every time.

In the Nodejs code below created a loop of 20 iterations to fetch the asset price. Sometimes 10-15 times the result is returned correctly and many a times in none of the iterations result is found rather it says 0.

> **Contract**

    pragma solidity ^0.4.9;
    
    contract Asset {
    
        address public owner;
        struct Asset {
            string title;
            string description;
            uint  assetTime;
            uint price;
        }
    
        Asset[] public  assets;
    
        event LogAssetAdded(address indexed fromAddress, string description);
    
        // add asset
        function addAsset(string  description1, string title1, uint price1,uint assetTime1) 
          returns (uint, string, string, uint, uint) {
            uint assetID = assets.length++;
            Asset o = assets[assetID];
    
            o.description = description1;
            o.assetTime=assetTime1;
            o.title = title1;
            o.price = price1;
            
            LogAssetAdded(msg.sender, description1);
            
            return (assetID, assets[assetID].description, assets[assetID].title, assets[assetID].price, 
              assets[assetID].assetTime);
        }
    
        //return the  number of assets 
        function assetCount() public constant returns(uint) {
            uint assetCount =assets.length;
            return(assetCount);
        }
        
        function getAssetPrice(uint assetID) public constant returns(uint) {
            return assets[assetID].price;
        }
        
        function getDefAssetPrice() public constant returns(uint) {
            return assets[assets.length-1].price;
        }
        
        function getDefAssetTitle() public constant returns(string) {
            return assets[assets.length-1].title;
        }
        
        function getDefAssetTime() public constant returns(uint) {
            return assets[assets.length-1].assetTime;
        }
    }

> **NodeJs Client Code**

    const rpcURL = 'http://localhost:9081'
    var Web3 = require('web3');
    var web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:9081"));
    
    const fs = require("fs");
    
    let abi ='<<Apply ABI>>';
    
    let bytecode = '<<Apply Bytecode >>'
    let gasEstimate = web3.eth.estimateGas({data: bytecode});
    
    let assetContract = web3.eth.contract(JSON.parse(abi));
    const account = '<<Provide from account>>';
    
    var contractAddress = '<<Provide Contract Address>>';
    
    var ctr1 = 0;
    var contract = assetContract.at(contractAddress);
    
    // Method to create asset
    function addAsset(){
    	contract.addAsset.sendTransaction("Asset Description", " Asset Title", 41202, 41203, {from: account, gas: 400000} 
    	, function(err, result){
    		if(err){
    			console.log('Error '+ err);    
    		}
    		else{
    			console.log('Transaction Hash: '+ result);
    			getAssetPrice();
    		}
    	});
    }
    
    // Method to fetch asset price
    function getAssetPrice(){  
    	for(var i=0;i<20;i++){
    	  contract.getAssetPrice(0, (error, result) => {
    		if (!error && result>0) {
    			ctr1++;
    			console.log(ctr1 +": getAssetPrice: "+ result);
    		}
    		if (!error){
    			 console.log("Error occurred: "+ error);
    		}
    	});
    }
    
    addAsset();
    //getAssetPrice()

> **Dependencies**

    "web3": "^0.19",
    "solc": "^0.4.9"

> **Geth Version**

     v1.9.0 windows-amd64, go1.10.3
> ** OS**
     Windows 10 64 bit
> **Geth Instance Command**

    geth --mine --minerthreads=1 --datadir D:/Ethereum/env-II/data/node1 --networkid 4224 --nodiscover --rpc --rpcport "9081" --port "30301" --rpccorsdomain "*" --nat "any" --rpcapi eth,web3,personal,net,miner --unlock 0 --password "D:/Ethereum/env-II/pwd.txt"  --rpcaddr 0.0.0.0 --verbosity 2 console

> **Geth command line result**

    > var assetContractRef = eth.contract('<<Contract abi>>');
    > var assetContract = assetContractRef.at('<<Contract address>>')
    > assetContract.getAssetPrice(1);
    > 41202

> **Result on invoking with Call**

    contract.getAssetPrice.call(0, (error, result) => {});
    
    Faced same result i.e. inconsistent output.

> **Note**

I have tried this implementation, with Web3 1.0.0-beta.52 as well with a bit modified nodejs code i.e. specific to the web3 1.0.0 signatures, but have faced the same inconsistent results. If required could share that version of Nodejs code as well.

Based on the results seems there is some issue with the geth instance itself

**Comment by holiman** [comment]
Could you provide the logs from `geth` when it serves the requests from node? It might say something about internal errors while serving the request(s)

**Comment by geekybcresearcher** [comment]
As asked PFA the logs. Here are two of the newly added transaction hashes which I created to add asset.

Tx 1: 0xbb8d9d4f472504d36d7dc8adbcb5ddbed77aa767baecce4586d715482117e648
Tx 2: 0x0e5978e648175ccfad9ef25c838e883235f37ed61883211b1b637e77e6b49b4a

[https://github.com/geekybcresearcher/ethereum-research/blob/master/00.log](url)

**Comment by holiman** [comment]
As far as I can tell, the server logs show that the contract creation fails : ` err="contract creation code storage out of gas"`. I don't see (in the nodejs code) where you actually create the contract? Are you sure that `contractAddress` is correct?

**Comment by geekybcresearcher** [comment]
The asset contract was deployed earlier itself. Possibly this particular error you saw was for another contract which I was testing. Required asset contract is definitely deployed as I have the address for the same, secondly addAsset is working as shared with you the transaction hashes. Also when I query directly from geth using the same contract address am able to list the data. To me it seems some issue with RPC connection implementation. Is there is any issue going on in this regard?

Below I have listed the transaction receipt details for the same. Hope this gives that clarity. Do let me know if you want me to again deploy the contract, perform these steps and then share the logs.

> **Transaction Receipt 1**

```
eth.getTransactionReceipt('0xbb8d9d4f472504d36d7dc8adbcb5ddbed77aa767baecce4586d715482117e648')
{
  blockHash: "0x78e68f145ca17a96d003679e392236d59d08779f58187c1c90d86516ab03aa38",
  blockNumber: 218207,
  contractAddress: null,
  cumulativeGasUsed: 68548,
  from: "0x46a6eaccf314e2e8a744d7ce480b28de2b3b0839",
  gasUsed: 68548,
  logs: [{
      address: "0x9169da02ea5574ad21629d9c2192e9798b26bed6",
      blockHash: "0x78e68f145ca17a96d003679e392236d59d08779f58187c1c90d86516ab03aa38",
      blockNumber: 218207,
      data: "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000124e6577204173736574204465736320312e330000000000000000000000000000",
      logIndex: 0,
      removed: false,
      topics: ["0x14626520695bdd66fe8470cb35cb8e19b265581efa59e0d0e5d8085291536fdc", "0x00000000000000000000000046a6eaccf314e2e8a744d7ce480b28de2b3b0839"],
      transactionHash: "0xbb8d9d4f472504d36d7dc8adbcb5ddbed77aa767baecce4586d715482117e648",
      transactionIndex: 0
  }],
  logsBloom: "0x00000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000002000000000000000000000020000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000040000000000000000000000000000000000000000000000000100000000000000",
  root: "0x2d3410aedd91178906c6ba08f645a645edcf0af17b35df7783845060276298d0",
  to: "0x9169da02ea5574ad21629d9c2192e9798b26bed6",
  transactionHash: "0xbb8d9d4f472504d36d7dc8adbcb5ddbed77aa767baecce4586d715482117e648",
  transactionIndex: 0
}
```

> **Transaction Receipt 2**

```
eth.getTransactionReceipt('0x0e5978e648175ccfad9ef25c838e883235f37ed61883211b1b637e77e6b49b4a')
{
  blockHash: "0xc207c78e67a7bcc658da600447e389d19a4b8c545dcf6b6ec5c3e94e5c6f399a",
  blockNumber: 218208,
  contractAddress: null,
  cumulativeGasUsed: 68548,
  from: "0x46a6eaccf314e2e8a744d7ce480b28de2b3b0839",
  gasUsed: 68548,
  logs: [{
      address: "0x9169da02ea5574ad21629d9c2192e9798b26bed6",
      blockHash: "0xc207c78e67a7bcc658da600447e389d19a4b8c545dcf6b6ec5c3e94e5c6f399a",
      blockNumber: 218208,
      data: "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000124e6577204173736574204465736320312e330000000000000000000000000000",
      logIndex: 0,
      removed: false,
      topics: ["0x14626520695bdd66fe8470cb35cb8e19b265581efa59e0d0e5d8085291536fdc", "0x00000000000000000000000046a6eaccf314e2e8a744d7ce480b28de2b3b0839"],
      transactionHash: "0x0e5978e648175ccfad9ef25c838e883235f37ed61883211b1b637e77e6b49b4a",
      transactionIndex: 0
  }],
  logsBloom: "0x00000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000002000000000000000000000020000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000040000000000000000000000000000000000000000000000000100000000000000",
  root: "0x4e7d84600466f75bc6aff14f965ec79d7b9e74cfde8238a3c2e213ec02451a07",
  to: "0x9169da02ea5574ad21629d9c2192e9798b26bed6",
  transactionHash: "0x0e5978e648175ccfad9ef25c838e883235f37ed61883211b1b637e77e6b49b4a",
  transactionIndex: 0
}
```

**Comment by holiman** [comment]
There's something odd here: 
```javascript
		if (!error && result>0) {
			ctr1++;
			console.log(ctr1 +": getAssetPrice: "+ result);
		}
		if (!error){
			 console.log("Error occurred: "+ error);
		}
```
Both those clauses have `!error`, the second one seems to be wrong. 
All in all, I think this is a bit too far away from geth to know if it's actually geth doing something wrong, or it it's in your javacsript code, or in some middleware library. 

I'll close this, since it's fairly old, but if you still have problems of this kind, please file a new ticket, and please remove as much middleware as possible.
