### ISSUE TITLE
Cannot establish virtual private network with two local peer nodes

### ISSUE THREAD

**Issue by scscgit** [ethereum/go-ethereum#19494]
After googling and trying dozens of combinations, I can't find a single proper configuration to locally run two instances starting from an empty blockchain that successfully add each other as peers in order to communicate. I must be missing something, yet I also found several other issues while I was looking for workarounds.

There's an example on stackexchange as a reference:
[https://ethereum.stackexchange.com/questions/7033/how-to-connect-to-geth-from-two-local-machines-ethereum](https://ethereum.stackexchange.com/questions/7033/how-to-connect-to-geth-from-two-local-machines-ethereum)

#### Steps to reproduce the behaviour

1. When starting non-dev instances with different port without ipcdisable, console acknowledges my ports, yet it still says Error starting protocol stack: Access is denied:

- `geth --datadir test1 --networkid 1234 --port 30301 --rpcport 8101 console init genesis.json`
- `geth --datadir test2 --networkid 1234 --port 30302 --rpcport 8102 console init genesis.json`
My genesis.json content:
```
{
  "config": {
    "chainId": 21315,
    "homesteadBlock": 0,
    "eip155Block": 0,
    "eip158Block": 0
  },
  "nonce"      : "0xd0deadbeefcafe0b",
  "coinbase"   : "0x0000000000000000000000000000000000000001",
  "difficulty" : "0x20000",
  "extraData"  : "",
  "gasLimit"   : "0x8000000",
  "mixhash"    : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp"  : "0x00",
  "alloc": {
    "0xbeea43afdb09ff6156cbeb61949ed60bb09cba80": {
      "balance": "1000000000000"
    }
  }
}
```
Logs are provided at the end of this page under Backtrace.

---
2. When starting the second node with `--ipcdisable`, using addPeer just says Dropping unsynced node during fast sync:

- Side sending command (using either the provided IP, or 127.0.0.1): `admin.addPeer("enode://c617e97b8632fdb0d10bb05908868d5414c53380a933439356dce9ee200aafe270209a00a071547deaaf828405125b4ecb510b4058018fd582924ddc6b904f5d@177.177.177.177:30301?discport=0")`
true
WARN [04-24|18:26:17.702] Dropping unsynced node during fast sync  id=06086cd2ebc50711 conn=staticdial addr=177.177.177.177:30301 type=Geth/v1.8.27-stable-4bcc0a37/windows-amd64/go1.11.5

- Receiving side:
TRACE[04-24|18:26:17.717] Protocol eth/63 failed                   id=35c6930e732c2080 conn=inbound err="unsynced node cannot serve fast sync"
DEBUG[04-24|18:26:17.722] Removing p2p peer                        id=35c6930e732c2080 conn=inbound duration=97.095ms peers=0 req=true err="useless peer"

3. I experienced multiple other during other attempts, some of which are:
- I can't connect two remote --dev instances on LAN, probably because their genesis block is always different
- I can't change parameters of --dev (like --port) as they are completely ignored, which makes local instances block each other - Error starting protocol stack: Access is denied. (I can only do so with ipcdisable, but they then also can't add each other as peers, whichever IP I use, and differ in genesis block)
- I can't connect two non-dev peers run from datadirs, which are copies of the same datadir generated by --dev run, as it says err="is self"
- I can't start mining on a non-dev network, which seems to be an old issue based on some github posts. Miner start only says Commit new mining work, yet the head doesn't change. I tried to make a transaction, but my genesis.json pre-allocated wallet doesn't contain any balance.

4. Additionally, I can't even use my Docker Toolbox (non-pro Windows):
```
@SET PATH=%CD%
@SET PATH=%PATH:C:=/c/%
@SET PATH=%PATH:\=/%
docker run --rm -v "%PATH%":/local -p 8545:8545 -p 30303:30303 ethereum/client-go --dev console --networkid=21315 --datadir /local/node2 init /local/genesis.json
```
because it says `Failed to start smart card hub, disabling: dial unix /run/pcscd/pcscd.comm: connect: no such file or directory`, for which I also found a related GitHub issue.

#### System information

Geth version: 1.8.27-stable (also tried some older ones, including 1.7.3-stable)
OS & Version: Windows 10

#### Expected behaviour

- Anyone who googles for an example of geth private virtual blockchain network should be able to locally run two nodes as peers, and any related errors should provide information as how to solve the issues.
- Peers should be able to connect to a blockchain with genesis block, or it should be described that a first block needs to be mined.
- Nodes running as -dev should support configuration, at least related to blocking ports and genesis block.

#### Actual behaviour

1. Fatal: Error starting protocol stack: Access is denied.
2. Dropping unsynced node during fast sync
etc.

#### Backtrace

C:\Software\Geth>geth --datadir test1 --networkid 1234 --port 30301 --rpcport 8101 console init genesis.json
INFO [04-24|18:00:36.280] Maximum peer count                       ETH=25 LES=0 total=25
INFO [04-24|18:00:36.306] Starting peer-to-peer node               instance=Geth/v1.8.27-stable-4bcc0a37/windows-amd64/go1.11.5
INFO [04-24|18:00:36.311] Allocated cache and file handles         database=C:\\Software\\Geth\\test1\\geth\\chaindata cache=512 handles=8192
INFO [04-24|18:00:36.556] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000  ConstantinopleFix: 7280000 Engine: ethash}"
INFO [04-24|18:00:36.568] Disk storage enabled for ethash caches   dir=C:\\Software\\Geth\\test1\\geth\\ethash count=3
INFO [04-24|18:00:36.572] Disk storage enabled for ethash DAGs     dir=C:\\Users\\Steve\\AppData\\Ethash       count=2
INFO [04-24|18:00:36.576] Initialising Ethereum protocol           versions="[63 62]" network=1234
INFO [04-24|18:00:36.624] Loaded most recent local header          number=0 hash=d4e567…cb8fa3 td=17179869184 age=50y1w3d
INFO [04-24|18:00:36.629] Loaded most recent local full block      number=0 hash=d4e567…cb8fa3 td=17179869184 age=50y1w3d
INFO [04-24|18:00:36.634] Loaded most recent local fast block      number=0 hash=d4e567…cb8fa3 td=17179869184 age=50y1w3d
INFO [04-24|18:00:36.639] Loaded local transaction journal         transactions=0 dropped=0
INFO [04-24|18:00:36.642] Regenerated local transaction journal    transactions=0 accounts=0
INFO [04-24|18:00:36.891] New local node record                    seq=7 id=09cea2cacba83d1c ip=127.0.0.1 udp=30301 tcp=30301
INFO [04-24|18:00:36.897] Started P2P networking                   self=enode://534f65091f843d628ea4ba1750ef60a916d297bc4e2a48eb51051cf5979314eae6af59ca45ca87a6f1a22ec2cdc62cf47b874fcf02ecaae1f4d1c9852564ca43@127.0.0.1:30301
INFO [04-24|18:00:36.899] IPC endpoint opened                      url=\\\\.\\pipe\\geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/v1.8.27-stable-4bcc0a37/windows-amd64/go1.11.5
 modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

\> admin.nodeInfo
{
  enode: "enode://534f65091f843d628ea4ba1750ef60a916d297bc4e2a48eb51051cf5979314eae6af59ca45ca87a6f1a22ec2cdc62cf47b874fcf02ecaae1f4d1c9852564ca43@127.0.0.1:30301",
  enr: "0xf896b840ad0c38fbc1b730f928f61f166e352f7a4494c13eed193066107f84f0b7c22f1f59fea2b42fff332242b27132fa1172b1d0357f206af60bb1e8c5e36882a4ef510783636170c6c5836574683f826964827634826970847f00000189736563703235366b31a103534f65091f843d628ea4ba1750ef60a916d297bc4e2a48eb51051cf5979314ea8374637082765d8375647082765d",
  id: "09cea2cacba83d1cf7fcddfbab8ffea9f2b8ec187904a38325cf8589699dfaa7",
  ip: "127.0.0.1",
  listenAddr: "[::]:30301",
  name: "Geth/v1.8.27-stable-4bcc0a37/windows-amd64/go1.11.5",
  ports: {
    discovery: 30301,
    listener: 30301
  },
  protocols: {
    eth: {
      config: {
        byzantiumBlock: 4370000,
        chainId: 1,
        constantinopleBlock: 7280000,
        daoForkBlock: 1920000,
        daoForkSupport: true,
        eip150Block: 2463000,
        eip150Hash: "0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0",
        eip155Block: 2675000,
        eip158Block: 2675000,
        ethash: {},
        homesteadBlock: 1150000,
        petersburgBlock: 7280000
      },
      difficulty: 17179869184,
      genesis: "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
      head: "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
      network: 1234
    }
  }
}
>

C:\Software\Geth>geth --datadir test2 --networkid=1234 --port 30302 --rpcport 8102 console init genesis.json
INFO [04-24|18:00:11.326] Maximum peer count                       ETH=25 LES=0 total=25
INFO [04-24|18:00:11.346] Starting peer-to-peer node               instance=Geth/v1.8.27-stable-4bcc0a37/windows-amd64/go1.11.5
INFO [04-24|18:00:11.351] Allocated cache and file handles         database=C:\\Software\\Geth\\test2\\geth\\chaindata cache=512 handles=8192
INFO [04-24|18:00:11.706] Initialised chain configuration          config="{ChainID: 21315 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: <nil> Constantinople: <nil>  ConstantinopleFix: <nil> Engine: unknown}"
INFO [04-24|18:00:11.716] Disk storage enabled for ethash caches   dir=C:\\Software\\Geth\\test2\\geth\\ethash count=3
INFO [04-24|18:00:11.722] Disk storage enabled for ethash DAGs     dir=C:\\Users\\Steve\\AppData\\Ethash       count=2
INFO [04-24|18:00:11.727] Initialising Ethereum protocol           versions="[63 62]" network=1234
INFO [04-24|18:00:11.781] Loaded most recent local header          number=0 hash=26ff09…67b64d td=131072 age=50y1w3d
INFO [04-24|18:00:11.786] Loaded most recent local full block      number=0 hash=26ff09…67b64d td=131072 age=50y1w3d
INFO [04-24|18:00:11.789] Loaded most recent local fast block      number=0 hash=26ff09…67b64d td=131072 age=50y1w3d
INFO [04-24|18:00:11.793] Loaded local transaction journal         transactions=0 dropped=0
INFO [04-24|18:00:11.796] Regenerated local transaction journal    transactions=0 accounts=0
INFO [04-24|18:00:12.042] New local node record                    seq=2 id=0a36ff0c428dc218 ip=127.0.0.1 udp=30302 tcp=30302
INFO [04-24|18:00:12.048] Started P2P networking                   self=enode://8e569d64ffca339382fd66e39aed0eee6d10a1ede8e4544917e5fd01278a6d236c7647bf6acdbb7c63b21e2cce16e047b9c1ae211686c833b233ad31002b45fe@127.0.0.1:30302
INFO [04-24|18:00:12.050] Blockchain manager stopped
INFO [04-24|18:00:12.061] Stopping Ethereum protocol
INFO [04-24|18:00:12.064] Ethereum protocol stopped
INFO [04-24|18:00:12.067] Transaction pool stopped
INFO [04-24|18:00:12.070] Database closed                          database=C:\\Software\\Geth\\test2\\geth\\chaindata
INFO [04-24|18:00:14.246] Mapped network port                      proto=udp extport=30302 intport=30302 interface="UPNP IGDv1-IP1"
INFO [04-24|18:00:14.284] Mapped network port                      proto=tcp extport=30302 intport=30302 interface="UPNP IGDv1-IP1"
Fatal: Error starting protocol stack: Access is denied.

**Comment by karalabe** [comment]
You mixed up two commands.

`geth --datadir test1 --networkid 1234 --port 30301 --rpcport 8101 console init genesis.json`

Here you started a console, the `init genesis.json` is ignored (it's just command line arguments that are never consumed). You need to init the chain first, then start it.

```
$ geth --datadir test1 init genesis.json
$ geth --datadir test1 --networkid 1234 --port 30301 --rpcport 8101 console
```

In your case, you started 2 mainnet nodes, and Geth was disconnecting each other during sync because both are missing recent blocks from mainnet and are considered unsuitable to sync from. If you properly initialize your nodes, they will stay connected.

(please make sure there's no error printed by init. If a chain already exist in a datadir, init will not overwrite it).

**Comment by scscgit** [comment]
Thank you very much, I was able to make it work by running init first as you instructed. I also had to fix another issue of mining not starting by deleting an old generated AppData\Ethash directory and letting DAG get re-generated. I hope this post will help others when they google a similar issue, as all other examples were outdated, but in my opinion the documentation (including --help page) should be more explicit here. There are still other parts of the issue remaining in case other people have different needs (e.g. --dev params can't be changed), but my use-case is solved.

**Comment by panoskor** [comment]
Can you help my i try to connect 2 nodes and i cant. This message pops out 
Dropping unsynced node during fast sync  id=bf4446fbf8a1a0cd conn=inbound addr=83.212.74.223:52004 type=Geth/v1.8.27-stable-4bcc0a37/linux-amd64/go1.10.4

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi everyone, I have the last 3 days come across quite the same `Smart Card` error : 
* here is a detailed description of the work I did, with technical and versioning details, before getting the `Smart Card error` : https://github.com/Jean-Baptiste-Lasselle/ethereum-test.git
* Thank you all for giving feed back here, I'll try all of your suggestions, and will feed back, on https://github.com/Jean-Baptiste-Lasselle/ethereum-test.git

**Comment by karalabe** [comment]
This issue was solved a long time ago. The two comments later are unrelated and only warning either way. Please open a fresh issue if you thin there's something wrong.
