### ISSUE TITLE
Head state missing, repairing chain

### ISSUE THREAD

**Issue by BeOleg** [ethereum/go-ethereum#19504]
```
root@nexwallet-eth3:/mnt/STORAGE/WALLETS# cat /var/lib/docker/containers/23406ad9bc38a5b9ab3c8e342295c91f2550d3b5c16f00d681f181aed9721c0d/23406ad9bc38a5b9ab3c8e342295c91f2550d3b5c16f00d681f181aed9721c0d-json.log | grep 'Head state missing'

{"log":"WARN [04-24|12:13:48.884] Head state missing, repairing chain      number=7623347 hash=b6c254…3a0dad\n","stream":"stderr","time":"2019-04-24T12:13:48.885446409Z"}

{"log":"WARN [04-25|19:19:10.008] Head state missing, repairing chain      number=7638271 hash=c73676…151eb8\n","stream":"stderr","time":"2019-04-25T19:19:10.008881355Z"}

{"log":"WARN [04-26|08:52:25.125] Head state missing, repairing chain      number=7641791 hash=c263d9…dfbe79\n","stream":"stderr","time":"2019-04-26T08:52:25.125447127Z"}

{"log":"WARN [04-28|09:21:28.698] Head state missing, repairing chain      number=7655058 hash=f11663…507ae5\n","stream":"stderr","time":"2019-04-28T09:21:28.698886159Z"}
```

I have found this in our logs.
I suspect that this happens dues to planned restart (using docker-compose, official geth image from dockerhub), or due to crashes (not sure why, where can I find more verbose info?).

I suspect that this causes:
1. Our node to fall behind.
2. Our node to generate transactions which are not properly published.

All as described in https://github.com/ethereum/go-ethereum/issues/19455

I would appreciate any assistance

**Comment by rjl493456442** [comment]
Now geth will maintain lots of **trie nodes** in the memory the GC them. So geth does not flush all generated tries into disk but periodically persists.

When geth receives stop (or ctrl+c), it will flush the necessary trie nodes in memory into the disk, but this process takes a certain amount of time. I guess the docker forcibly stop the process without waiting the flush finished.

So when the node restarts, a few trie nodes are missing and repairing starts.

You can increase the docker stop-timeout to fix it. `--stop-timeout  180`

**Comment by jayboy-mabushi** [comment]
@BeOleg did you get a solution for this issue?

**Comment by jayboy-mabushi** [comment]
@fjl is there a fix for this? my node is not starting pulling it new data it is stuck at this error. 

![image](https://user-images.githubusercontent.com/60149478/127776154-3ec657f7-eb8c-422f-a9bf-86fbe73fc561.png)

**Comment by GrinderBrad** [comment]
@jayboy-mabushi I ran into the same problem just now. Any updates on your side?

**Comment by jayboy-mabushi** [comment]
@GrinderBrad nope I just resynced deleted everything

**Comment by cryptobrokering** [comment]
Also have the same problem. 

@jayboy-mabushi You mean you had to start the whole syncing process again from scratch?

**Comment by GrinderBrad** [comment]
For me helped 

- update to geth 1.10.6
- adding `--snapshot=false --syncmode=fast`

No re-sync needed.

P.S. Be careful if you run geth in docker. When you exiting geth process it takes some time. Make sure to add `--time=180` to docker stop command when you need to stop it. Otherwise you'll lose some blocks and re-sycning might take 2-5 hours.

**Comment by camilodotto** [comment]
Same problem here... we are using docker-compose and running 'docker-compose down' to stop and remove containers... the solution we found is to exec 'pkill geth' on the geth container before 'docker-compose down'. This way geth stops gracefully and the problem does not occur anymore.
