### ISSUE TITLE
action from bad peer ignored

### ISSUE THREAD

**Issue by 401825317** [ethereum/go-ethereum#19503]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version` 1.8.9
OS & Version: Windows/Linux/OSX  linux
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]

########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: <nil> Engine: ethash}

Number: 7280000
Hash: 0xeddb0590e1095fbe51205a51a297daef7259e229af0432214ae6cb2c1f750750


Error: invalid difficulty: have 2957101900364072, want 2958201410943272
##############################

````

**Comment by karalabe** [comment]
Please upgrade your node. Ethereum mainnet was upgraded to the Constantinople and St. Petersburg hard forks since the 1.8.9 release.
