### ISSUE TITLE
Unlock Account error

### ISSUE THREAD

**Issue by northeusunshine** [ethereum/go-ethereum#19507]
Hi there,

I start a eth node with the command:
geth --networkid 123456 --rpc --rpcport "8545" --rpccorsdomain "*" --datadir ./enode1/data --port "2001" --rpcaddr "192.168.43.107" --rpcapi "admin,db,eth,miner,web3,net,personal,txpool"

when I attached the geth node in console and try to unlock a account, there is an error:
> personal.unlockAccount(web3.eth.accounts[0],"**********")
Error: account unlock with HTTP access is forbidden

Please help how to fix it.
Thanks

**Comment by etardz** [comment]
https://geth.ethereum.org/downloads/ you can download geth direct and then add it to the build folder and then run the command... if I'm not mistaken

**Comment by rjl493456442** [comment]
@northeusunshine The unlock operation is unsafe if the node is exposed to external. We add this protection in https://github.com/ethereum/go-ethereum/pull/17037. If you want to unlock forcibly, please add the `--allow-insecure-unlock`.

**Comment by northeusunshine** [comment]
It works using flag --allow-insecure-unlock.
so what the safe method to unlock an account.

### meanwhile, i have another two questions:
### first one:
when I restart node by:"geth --networkid 123456 --rpc --rpcport "8546" --rpccorsdomain "*" --datadir ./enode2/data --port "2002" --rpcaddr "0.0.0.0" --rpcapi "admin,db,eth,miner,web3,net,personal,txpool" --"allow-insecure-unlock" --unlock '0x4c6cbd2b8428f3ea8257a325258c03b9e9daaf64' --password password2.txt"

**an error occurs as below:**
WARN [04-29|02:10:18.311] Sanitizing cache to Go's GC limits       provided=1024 updated=612
INFO [04-29|02:10:18.313] Maximum peer count                       ETH=25 LES=0 total=25
INFO [04-29|02:10:18.314] Starting peer-to-peer node               instance=Geth/v1.8.27-stable-4bcc0a37/linux-amd64/go1.11.9
INFO [04-29|02:10:18.314] Allocated cache and file handles         database=/root/eth/enode1/data/geth/chaindata cache=306 handles=2048
INFO [04-29|02:10:18.333] Initialised chain configuration          config="{ChainID: 123456 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: 5  ConstantinopleFix: <nil> Engine: clique}"
INFO [04-29|02:10:18.334] Initialising Ethereum protocol           versions="[63 62]" network=123456
Fatal: Error starting protocol stack: database version is v6, Geth 1.8.27-stable only supports v3

### second one:
I set up a private chain with two nodes, both are set to be sealer when creating the chain by puppeth tool.
I also add the peers to each other and let the two nodes start mining, however, when send a transation, both of them have the status info "Signed recently, must wait for others".
What shall I do to fix it.

Thanks a lot!

**Comment by holiman** [comment]
> so what the safe method to unlock an account?

There exists no safe method to unlock an account. Unlocking an account means "let anybody do anything with this account". However, there exists more secure ways to perform transactions

- With geth: `personal_sendTransaction` and supply the password in the call. That means the account is not unlocked for other callers. 
- With geth/clef: start `clef`, start `geth --signer`, and then supply the password when `clef` asks for confirmation. Clef is a new binary that comes with geth, and if you build from source `make all` it will be available in `build/bin/clef`. 
- If you're on a test-network and the account has no value on mainnet, then you can use `allow-insecure-unlock`.

**Comment by holiman** [comment]
Sorry, missed the other questions. 

> Fatal: Error starting protocol stack: database version is v6, Geth 1.8.27-stable only supports v3

Yes, you have used the `1.9` (latest master) to create the database, and then tried to go back to `1.8.xx`. We're doing a version upgrade, so they're not compatible, and you cannot go back from 1.9 to 1.8. 
 
Regarding the clique error, have the two signers found eachother? How is the clique authorization round configured?
