### ISSUE TITLE
Chocolatey powershell cannot find desktop location if it is at a different location.

### ISSUE THREAD

**Issue by juanfranblanco** [ethereum/go-ethereum#1950]
I cannot find the script to do a pull request, this is the fix

<pre>
$packageName    = 'geth-stable'
$url = 'https://github.com/ethereum/go-ethereum/releases/download/1.2.1/Geth-Win64-20151001092742-1.2.1-9666db2.zip'

$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"
</pre>

**_$desktop = [environment]::GetFolderPath("Desktop")
$shortcutFile = Join-Path  $desktop "$packageName.bat"**_

<pre>
# Download and extract package
Install-ChocolateyZipPackage "$packageName" "$url" "$toolsDir"
# Prevent shim from being created in bin directory
"shimgen ignore" | Set-Content "$(Join-Path $toolsDir 'geth.exe.ignore')" -Encoding ASCII

#$batContent = "$toolsDir\geth.exe console 2> $toolsDir\geth.log"
$batContent = "$toolsDir\geth.exe console"

"$batContent"| Set-Content $shortcutFile -Encoding ASCII
</pre>

**Comment by karalabe** [comment]
@tgerring If I remember you wrote the chocolatey scripts. Could you maybe take a look at this?

**Comment by tgerring** [comment]
Source repo should be listed on Chocolatey page, but here it is for convenience: https://github.com/tgerring/ethereum-chocolatey

Note that I no longer have access to my Windows computer to do Chocolatey builds. Instead, we should try to get the latest Windows build steps working see https://github.com/ethereum/go-ethereum/issues/1776)
