### ISSUE TITLE
I am confused about Pure/View function

### ISSUE THREAD

**Issue by IamChuancey** [ethereum/go-ethereum#19509]
So in testnets like Ropsten or Kovan,I have tested that if I remove the modifier `pure`or `view`,the function won't work even if the transaction is good, nothing output.
![image](https://user-images.githubusercontent.com/29730996/56886443-a27eab00-6aa1-11e9-9c28-e453c8bf70d8.png)
BTW.I can guarantee that the function is no mistake in implement. but if I put the modifier on, the function works well.
So, is there a mechanism you designed? please answer me, thank you!

**Comment by holiman** [comment]
This is not related to go-ethereum, and I'm not up to speed with how `pure`/`view` is interpreted and handled by Solidity. Please reach out at [the solidity repo](https://github.com/ethereum/solidity) instead

**Comment by ericramos1980** [comment]
Thank you
