### ISSUE TITLE
Error : new BigNumber() not a base 16 number

### ISSUE THREAD

**Issue by Rashmiub** [ethereum/go-ethereum#19516]
Hi there,

getting this error while interacting with smart contract.
Commands:
storage.set.sendTransaction("hello",{from : eth.accounts[0] ,gas : 1000000 } )
storage.get.call () 

Output
Error : new BigNumber() not a base 16 number

**Comment by ligi** [comment]
this does not look like a bug with geth - please head over to https://ethereum.stackexchange.com
