### ISSUE TITLE
About issuing token on private ethereum chain(POA)

### ISSUE THREAD

**Issue by northeusunshine** [ethereum/go-ethereum#19528]
Hi there,

I'm trying to create a private POA ETH chain and issue my own token on it.

I have questions about how to make the whole system work.
The question is that after I have a private chain and before set up smart contract to issue token, how can I dig out all the coins in advance?

Besides, how to set the total coin number of private chain?

Thanks

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
