### ISSUE TITLE
Rinkeby faucet down

### ISSUE THREAD

**Issue by aaronArinder** [ethereum/go-ethereum#19520]
Rinkeby faucet seems to be down. Getting:

```
WebSocket connection to 'wss://faucet.rinkeby.io/api' failed: Error during WebSocket handshake: Unexpected response code: 503
```

Checked out [https://faucet.rinkeby.net/](https://faucet.rinkeby.net/), but it's being redirected to `.io`. So, I'm guessing all the [domain stuff](https://twitter.com/peter_szilagyi/status/1106475845709979648) was sorted out. I'm sure this is all known, but I didn't see an open issue for it.

Thanks!

**Comment by karalabe** [comment]
Was fixed, thanks for reporting it.

**Comment by aaronArinder** [comment]
Sweet, thanks!
