### ISSUE TITLE
while ErrInsufficientBalance error occured in contract process, but return zero gas is ok?

### ISSUE THREAD

**Issue by hunjixin** [ethereum/go-ethereum#19549]
```
  if vmerr != nil {
		log.Debug("VM returned with error", "err", vmerr)
		// The only possible consensus-error would be if there wasn't
		// sufficient balance to make the transfer happen. The first
		// balance transfer may never fail.
		if vmerr == vm.ErrInsufficientBalance {
			return nil, 0, false, vmerr
		}
	}
```

Hackers can send such transactions with impunity, which can lead to erroneous transactions, this may lead to security risks

**Comment by holiman** [comment]
It's a common go-lang thing, when there are return values like `ret1, ret2, ret2, err` -- if the `err` is non-nil, then all other return values are ignored. 
All callers that call something which return error as the last retval should always check the error first.
