### ISSUE TITLE
How to promote transactions by rules?

### ISSUE THREAD

**Issue by qwlv** [ethereum/go-ethereum#19542]
I want to promote transactions from queued to pending according to rules that there is only one special type transaction in the block.How to achieve it? 
I find function `func (m *txSortedMap) Ready(start uint64) types.Transactions ` will remove transactions not  promoted.Then I save these transactions  not  promoted and add a channel to notify when to promote them.But the whole program will be blocked after doing this.
I would  appreciate it if you can give me some advice. Thanks.

**Comment by karalabe** [comment]
You misunderstand the pending / queued pools. The pending pool contains all transactions that are actually executable. The queue is a st of transactions that cannot be executed, usually because there's a nonce gap and a previous transaction needs to execute first.
