### ISSUE TITLE
Some geth peers disconnect randomly, in private chin?

### ISSUE THREAD

**Issue by jianwei20** [ethereum/go-ethereum#19541]
#### System information

Geth version: `v 1.6.7`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour

Hundreds of nodes connect in private chin.

#### Actual behaviour

Some geth peers disconnect randomly, in private chin.

#### Steps to reproduce the behaviour

I would like to build a private chain with hundreds of nodes.I Use static-nodes.json to connect each others. When I start each nodes synchronously, there are some nodes disconnect from my private chain randomly. The number of connecting nodes always change

This is command starting geth 
```
../build/bin/geth --networkid 2234 --port 30303 --rpcport 8545 --datadir "data1/node1" --nodiscover --maxpeers 100 --rpc --rpccorsdomain "*" --rpcapi "eth,net,web3,debug" --bft --allow-empty --num-validators 100 --node-num 0
``` 
I Use static-nodes.json to connect each others like below.
```
"enode://e76ebac548ee2d5fc79f3e1ab8d7b17214966c6ab369dd980c76fb9fe96521af4d4f79cd4ade59f05d58744e1ffda3ad5b5ee6684ac8c7c52f07acca965f3601@10.0.1.171:30303?discport=0"...... and so on.
```
This command is for number of peer connect. 
```
../build/bin/geth --exec 'admin.peers.length ' attach ipc:./data1/node1/geth.ipc
```
```
INFO [05-08|16:46:30] Ethereum message handling failed         id=4ac60e3de59bcef8 conn=staticdial err=EOF
INFO [05-08|16:46:30] Removing Ethereum peer                   peer=4ac60e3de59bcef8
INFO [05-08|16:46:30] err:                                     LOG15_ERROR=                                                   LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO [05-08|16:46:30] Ethereum message handling failed         id=73a8a9eb5497477b conn=inbound    err=EOF
INFO [05-08|16:46:30] Removing Ethereum peer                   peer=73a8a9eb5497477b
INFO [05-08|16:46:30] err:                                     LOG15_ERROR=                                                   LOG15_ERROR="Normalized odd number of arguments by adding nil"
```

**Comment by jianwei20** [comment]
#### This is my geth version running
Geth
Version: 1.6.7-unstable
Git Commit: bd4699a05df4dc9c956ac65fe19d1cb15cd8fdb2
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.6
Operating System: linux
GOPATH=/home/ubuntu/go
GOROOT=/usr/local/go
#### My happen like figure
<img width="899" alt="螢幕快照 2019-05-13 下午3 18 40" src="https://user-images.githubusercontent.com/18433369/57602653-5435d580-7592-11e9-9933-9c8a6f905c9f.png">
In my experiment, I run 80 EC2 with geth to run bft consensus, so the number of each node should connect 79 geth. 
I found that some nodes seems disconnect randomly.
This is command starting geth 
##### geth 01 
```
../build/bin/geth --networkid 2234 --port 30303 --rpcport 8545 --datadir "data1/node1" --nodiscover --maxpeers 80 --rpc --rpccorsdomain "*" --rpcapi "eth,net,web3,debug" --bft --allow-empty --num-validators 80 --node-num 0
``` 
##### geth 02
```
../build/bin/geth --networkid 2234 --port 30304 --rpcport 8546 --datadir "data1/node1" --nodiscover --maxpeers 80 --rpc --rpccorsdomain "*" --rpcapi "eth,net,web3,debug" --bft --allow-empty --num-validators 80 --node-num 0
``` 
and so on

**Comment by karalabe** [comment]
We have made 33 releases since that version. We cannot support 2 year old releases. Please update to the latest code and see what happens.
