### ISSUE TITLE
Rinkeby faucet offline

### ISSUE THREAD

**Issue by wbt** [ethereum/go-ethereum#19553]
### Steps to reproduce the behaviour
1. Visit faucet.rinkeby.io. 
2. See:
![image](https://user-images.githubusercontent.com/563406/57532071-f04cac00-7308-11e9-9713-aaa63091204e.png)

The issue report seems to be similar to #18257 (which was reported on a private network) and a different error than #17596.

**Comment by karalabe** [comment]
The light clients is having some issues on finding peers fast on Rinkeby, at least with the faucet's config. I've restarted it and took an hour for it to sync back up, that's when it was offline. Now it's working.

We need to roll out a new discovery protocol + les fixes to stabilize it, it's ongoing effort.
