### ISSUE TITLE
geth stopped importing blocks

### ISSUE THREAD

**Issue by karek314** [ethereum/go-ethereum#1956]
Geth while mining under ~ 150 workers, stopped importing new blocks, there wasn't any error, it was just keep mining on old block. After restarting geth synced correctly to latest block. Im not sure if it's related to previous report with local fork stuck.

Geth/v1.3.0-dev-57ab1473/linux/go1.5

**Comment by datajerk** [comment]
I have same problem with 1.3.1.  I had to create a small script to monitor block stall to kill and restart geth.

**Comment by trappist** [comment]
@datajerk I would love to see this script.
