### ISSUE TITLE
getBlock web3 command for Geth to return header in light mode

### ISSUE THREAD

**Issue by sidhujag** [ethereum/go-ethereum#19574]
Hi Guys,

I assume geth --light mode downloads all the headers of blocks which have the roots (transaction, storage, receipt) needed for SPV clients to do verifications. I tried using web3 to grab blocks from geth and it tries to connect to peers to download blocks, is it possible to return the header in place of a block or have a getBlockHeader command which is not dependent on peers? (once you download a header it should be available).

**Comment by rjl493456442** [comment]
I'm curious how you will use the merkle roots in the header? Now we have some RPC like `eth_getTransactionByHash` or `eth_getTransactionReceipt` which will do merkle proof in light client internally. Do you want to do a similar thing in your project?

**Comment by sidhujag** [comment]
@rjl493456442 I've scanned the repo, you do have the EthereumClient which exposes https://github.com/ethereum/go-ethereum/blob/6fc84946203929143c51010e0a10d9fa61fb9b92/mobile/ethclient.go#L64 the header function but no RPC or clique handler.

I'm running a light client alongside my protocol, a trustless bridge between two chains. Here is the data I need I can show you via unit test:

https://github.com/syscoin/syscoin/blob/dev-4.x/src/test/syscoin_asset_tests.cpp#L407

You can see I use the tx root and receipt root of the header:

https://github.com/syscoin/syscoin/blob/dev-4.x/src/services/assetconsensus.cpp#L65

I need the receipt to check the status field, and the tx to get from, to and abi data of the burn function call from eth contract.

I push roots from local client thru rpc to my protocol and use it in my conensus check above. 

Thus I thought it'd be nice to be able to tap into getting the header since light clients already have it.

Hopefully that makes sense.

**Comment by sidhujag** [comment]
works as expected, tx!
