### ISSUE TITLE
"Mining work not ready" error in response for eth_getWork always when using IPC

### ISSUE THREAD

**Issue by sammy007** [ethereum/go-ethereum#1957]
I wanna get work from geth using IPC. And response for "eth_getWork" command is always an error <code>mining work not ready</code>. I am on develop branch.

Here is a code I am running https://gist.github.com/sammy007/51a03eafbcfd421ac67e

**Comment by bolaum** [comment]
I was having the exact same problem with 1.3.6. I tried the [develop](https://github.com/ethereum/go-ethereum/tree/develop) branch today and it worked.

**Comment by sammy007** [comment]
I know that @obscuren fixed it because I remember he posted a patch for me on gitter. I lost this patch and also interest in using IPC.
