### ISSUE TITLE
Error: Connection refused or URL couldn't be resolved: http://X.X.X.2:3000

### ISSUE THREAD

**Issue by dnzhnshn** [ethereum/go-ethereum#19589]
I'm trying to connect to the ethereum node through node js. I'm using a Docker network. The command which I used is this:

> this connection geth command:
- [ ] geth --testnet  --datadir /testchain/geth/chaindata  --cache 8196 --rpcport 3000 --rpcaddr 192.168.3.2 --rpccorsdomain "*" --rpcapi "eth,net,personal,web3,db,txpool" --port 35355

> --rpcaddr 192.168.3.2 this my node.js api ip.they are all in the same docker network.

I'm trying connect ethereum node  with this ip X.X.X.2:3000 
My ethereum node's ip is X.X.X.3:8545

Why am I getting this error: 
Error: Connection refused or URL couldn't be resolved: http://X.X.X.2:3000

**Comment by mrFranklin** [comment]
the `--rpcaddr` flag is the address of your ethereum node
the `--rpcport` flag is  the rpc port of your ethereum node
so modify the geth command to:
```
geth --testnet --datadir /testchain/geth/chaindata --cache 8196 `--rpcport 8545 --rpcaddr X.X.X.3 --rpccorsdomain "*" --rpcapi "eth,net,personal,web3,db,txpool" --port 35355
```

then conntect it like this: (using web3 for example)
```
const web3 = new Web3('http://X.X.X.3:8545');
```

**Comment by pcanwar** [comment]
@mrFranklin thanks just for the update 

geth --datadir /testchain/geth/chaindata --syncmode "full"  --cache 4098 --port 30303 --http --http.port 8545 --http.addr X.X.X.3 --http.corsdomain "*"
