### ISSUE TITLE
Setting gasLimit and account balances for DEV mode

### ISSUE THREAD

**Issue by konstantinzolotarev** [ethereum/go-ethereum#19581]
Hello !
It's more like a question rather than bug. 
Is there any way to set account balance of `gasLimit` for geth DEV mode ?

I'm trying to start geth for local testing using `geth --dev` and did find any way to set `gasLimit` or account balances or `networkID` for this chain.

**Comment by karalabe** [comment]
Dev mode is really meant to be a quick and dirty way to ephemerally test something and then discard the chain. If you want more control, you can create your own Clique genesis json (`puppeth` can help) and set the period to 0 for insta-mining.

**Comment by konstantinzolotarev** [comment]
Great. Thank you !
