### ISSUE TITLE
Permission Needed for -" Cyber Security Network based on ethereum, bitcoin and hybrid DAGs"

### ISSUE THREAD

**Issue by cyberiums** [ethereum/go-ethereum#19595]
Hi there,

How to get permission for opening https://github.com/cyberiums/cyberium under MIT?
I am using ethereum and some other libs and want to keep my work open sourced.

Please help.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by fjl** [comment]
go-ethereum is licensed GPLv3 which is an 'open source' license. You cannot change the license.
