### ISSUE TITLE
Connecting nodes / Importing blockchain on private network

### ISSUE THREAD

**Issue by Ryanmtate** [ethereum/go-ethereum#1959]
Hello,

I am trying to import an exported blockchain file from one node to another on a private network, but seem to be getting the following error whenever I try to use admin.importChain(blockchain.bin) =>

invalid block 1186: nonce for #0 [bcb42fdb01684bd348c98f6bb79751f064fd2f88e77dc1fd0022a2bef11f70da…] is invalid (got 66)
    at InvalidResponse (<anonymous>:-81662:-24)
    at send (<anonymous>:-156322:-24)
    at importChain (<anonymous>:-133322:-24)
    at <anonymous>:1:1

//

Additionally, when starting the nodes with non-default datadir, networkid, gensis parameters and using the admin.addPeer('enode://...'), the peers do not seem to connect or sync blockchains...

Looking for a more clear explanation of how to import blockchain binary data from one private network node to another, and have those nodes sync.

Also, I noticed admin.chainSyncStatus seems to be deprecated in the JavaScript console.. is this correct?

Thanks for the help in advance.

Best,

Ryan

**Comment by karalabe** [comment]
Could you by any chance provide the blockchain data you're trying to import and the exact steps you took to create it/try to import it and also the CLI flags you ran the nodes with?

The `admin.chainSyncStatus` command was elevated into the official RPC spec at `eth.syncing` https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_syncing.

**Comment by Ryanmtate** [comment]
Hi, Thanks Karalabe!

I am going to close this...

I decided against setting up a private network and decided to fallback to using the --testnet flag. The issue of syncing blockchains between nodes for a private network I thought might add another communications layer complexity or security vulnerability...

However, my steps for going about blockchain exportation was through using the IPC socket via a node.js application:

The admin.exportChain('./blockchain.bin') method was used to export the chain; 

From their the nodes fetched the file from an http endpoint => /api/blockchain/export;

The exported blockchain file was then imported using the Ethereum JS console command admin.importChain('./blockchain.bin');

The block would throw the error at block number where the exported blockchain file ended; throwing invalid block.

If someone is looking for help on this later they might try geth export <file> 0 (n-1 block number)

But I have not tested this.

Thanks!
