### ISSUE TITLE
ethGetTransactionCount with 'pending' reaches out to network peers

### ISSUE THREAD

**Issue by sidhujag** [ethereum/go-ethereum#19601]
Im running geth in light mode.

I was trying to get my tx count locally via 'pending'. This looks like it reaches into the mempool to find out if your local node has pending transactions. How come it needs to reach out to peers? I get sometimes get a 'no peer available' error on requests sometimes. Does this not work locally or does it try to get pending status from other peers as well for some type of confidence measure?

**Comment by karalabe** [comment]
When you create a transaction via a light client, the node doesn't know when your transaction was included, nor does it know if the transaction was dropped or not from remote nodes. It will scan incoming blocks and try to detect inclusion, but the only way to see if remote nodes still maintain it or dropped it is to ask them. It can give you a hint as to whether your transaction is underpriced or similar issues.
