### ISSUE TITLE
Very Slow State Sync on 1.9 Master

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#19619]
I've been testing out the Geth 1.9 from master and it took my nodes over 3 days (maybe 4?) to actually sync all of the states.

I was chatting with @karalabe about it on Twitter and I've just now got back to my PC to open this ticket. I did a `grep "05-20|0[12]"` against the logs so as to give an hour worth of log data during the middle of the slow sync process.

I ran 2 nodes at the same time and both nodes displayed the same behavior. The node stats are:
https://www.intel.com/content/www/us/en/products/boards-kits/nuc/kits/nuc5i7ryh.html

The data drive was an SSD and was a 256GB Samsung 840 EVO. My internet speed is 100Mb/100Mb and there is/was a static PAT and open incoming firewall rules in place.

#### System information

Geth version:
```
Geth
Version: 1.9.0-unstable
Git Commit: 97d3615612a49488d02807944696d001b88f9e0d
Git Commit Date: 20190517
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.12
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.12
```
OS & Version: `Ubuntu 18.04.2`

I run with the following interesting flags:
```
--datadir /data/ethereum
--nousb
--lightserv 100
--lightpeers 75
--maxpeers 100
--nat extip:$(curl -s ipinfo.io/ip)
--shh
--rpc
--ws
--graphql 
```

[05-20-1am-2am.log](https://github.com/ethereum/go-ethereum/files/3212324/05-20-1am-2am.log)

**Comment by karalabe** [comment]
Your Geth version dump is 1.8.27 :P

**Comment by karalabe** [comment]
That said, I'm not sure what the light server's performance hit on initial sync is. Neither am I aware how Whisper influences things. If you indeed ran 1.9 (and not 1.8.27 as you wrote above), could you try again with default parameters, without extra services?

We used the default 50 peers, light server disabled, whisper disabled in our experiments.

**Comment by MysticRyuujin** [comment]
Oh, my bad, I had the ppt geth installed too and I didn't do ./geth 😄  fixed above.

**Comment by MysticRyuujin** [comment]
Well, it's been 24 hours...

```
> eth.syncing
{
  currentBlock: 7829323,
  highestBlock: 7829392,
  knownStates: 155300226,
  pulledStates: 155273957,
  startingBlock: 0
}
```

Do you want the same logs?

**Comment by MysticRyuujin** [comment]
I'm going to attempt to sync from scratch with the latest release (1.8.27) and see how long that takes for a reference point...

**Comment by MysticRyuujin** [comment]
Well, I'm guessing that this is just something to do with my nodes and/or environment because 1.8.27-stable after ~36 hours of syncing is basically at the same place 1.9 was after 24 hours...

```
{
  currentBlock: 7842850,
  highestBlock: 7842915,
  knownStates: 155794393,
  pulledStates: 155794392,
  startingBlock: 0
}
```

**Comment by lrgeoemtry** [comment]
Im subscribed to this repo,
I almost get triggered everytime you commit Mr. Wright ;P
