### ISSUE TITLE
SimulatedBackend does not implement TransactionByHash method

### ISSUE THREAD

**Issue by favadi** [ethereum/go-ethereum#19622]
#### System information

Geth version: develop
OS & Version: irrelevant
Commit hash : 2cd6059e51e823012f756112e6e9b2d2920bab74

#### Expected behaviour

`SimulatedBackend`  should have `TransactionByHash` method like `ethclient.Client`.

#### Actual behaviour

`SimulatedBackend` does not implement `TransactionByHash` method.

**Comment by holiman** [comment]
It's here: https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/backends/simulated.go#L171 
If it's not working, please file a new ticket
