### ISSUE TITLE
Memo: Background freezer reimport

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#19625]
Reindexing all the transactions from the freezer takes a very long time. There's no need to hang the node in the mean time, we can do it in the background.

Optionally, we should also have a flag that controls the timespan in which we're willing to index transactions (backfill or delete in the background). This has the potential of shaving off 1h worth of reindexing + 20GB worth of database size.

**Comment by holiman** [comment]
Why has this been moved, aren't we already doing this? I think we can close this... ?
