### ISSUE TITLE
Error in function call

### ISSUE THREAD

**Issue by eatablewonderful** [ethereum/go-ethereum#19620]
#### System information

Geth version: `geth version`1.7.3
OS & Version: deployed on heroku

#### Actual behaviour
when I try to pass my private key into bind.NewTransactor() function i get error as 
invalid character 'a' looking for beginning of value
private key is passed as string variable
'a' is first character in my private key

private key passed as specified
https://godoc.org/github.com/ethereum/go-ethereum/accounts/abi/bind#NewKeyedTransactor

**Comment by karalabe** [comment]
I don't think that's where your error is originating from. The parameter is not a string and neither a byte slice, rather an already parsed private key. There's no way that method can error (at all), and neither can it return parsing errors as it doesn't do any parsing whatsoever. Please check your surrounding code, your code fails before or after this method, but not inside this.

**Comment by karalabe** [comment]
Ah, we saw now that you linked to NewKeyedTransactor but your mentioned NewTransactor in the text. So, the key that `NewTransactor` expects is **not** a raw private key, rather a [JSON keyfile](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition).
