### ISSUE TITLE
Different block hash on PoA networks when there are multiple miners

### ISSUE THREAD

**Issue by kigawas** [ethereum/go-ethereum#19621]
Say you have a private PoA network deployed on kubernetes
1. There are 3 miners and 2 non mining nodes
2. 3 miners started with one signer address defined in `genesis.json`
3. Kubernetes will start the nodes almost simultaneously
4. When mining, there come concurrent blocks and different blockchains

#### System information

Geth version: `Geth/v1.8.27-stable-4bcc0a37/linux-amd64/go1.11.9`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
All nodes should share the same blockchain

#### Actual behaviour
Some miner nodes have different blockchain

#### Steps to reproduce the behaviour
1. Deploy a PoA network on kubernetes via helm. The official helm chart is based on PoW but I forked and updated the configuration to PoA at [here](https://github.com/kigawas/charts/tree/master/stable/ethereum)

2. After everything running up, check the ethstats page like:

![Screenshot from 2019-05-24 17-17-53](https://user-images.githubusercontent.com/4182346/58313204-f8980180-7e47-11e9-82c3-e967826e931d.png)

3. You can find some miner's block has some different hashes

#### Backtrace
Not apply

**Comment by karalabe** [comment]
Are you using the same address for multiple miners? If yes, that's a bad idea, because they will race for each other, and every block will have the same weights. In Clique, all signers are meant to have their own keys.

**Comment by kigawas** [comment]
Thanks for your reply. If multiple miners on same address will race, what about two addresses?

Correct me if I'm wrong, I couldn't see difference between 2 miners on 1 address and 2 miners on 2 addresses

**Comment by karalabe** [comment]
In Clique PoA, block difficulties depend on mining order. If you have a single authorized signer, all blocks will have the exact same difficulty. However if you are mining with multiple instances of the same signer, you will have competing chains with the exact same difficulty, so the network will have a very hard time to pick one from the many competing chains.
