### ISSUE TITLE
txPool: validateTx, wrong signature returns ErrInsufficientFunds

### ISSUE THREAD

**Issue by salanfe** [ethereum/go-ethereum#19637]
https://github.com/ethereum/go-ethereum/blob/86e77900c53ebce3309099a39cbca38eb4d62fdf/core/tx_pool.go#L634

I was playing with signature on my local PoA network and got the error `insufficient funds for gas * price + value` when sending a transaction with an invalid signature. Shouldn't we get `invalid sender` (for example) instead ? I think I am getting `insufficient funds for gas * price + value` because the `ecRecover` still returns a valid `from` address. However, because the signature is invalid, this address is not the one of my account (which has like 2 trillion ethers). Therefore this unknown account has no ether and `getBalance()` returns zero which triggers the error.

here is a code sample to reproduce the error
```go
signer := types.NewEIP155Signer(big.NewInt(6464))

// dummy transaction data
nonce := uint64(0)
to := common.HexToAddress("0x4592d8f8d7b001e72cb26a73e4fa1806a51ac79e") // dummy recipient address
gasPrice := big.NewInt(1)
gasLimit := uint64(23000)

// create 2 different transactions
tx1 := types.NewTransaction(nonce, to, nil, gasLimit, gasPrice, []byte{})
tx2 := types.NewTransaction(nonce, to, nil, gasLimit, gasPrice, []byte("hello"))

// hash and sign transaction 1
hashTx1 := signer.Hash(tx1)
sigTx1, _ := crypto.Sign(hashTx1.Bytes(), privateKey) // account owns 2 trillion+ ethers

// inject signature of transaction 1 into transaction 2
signedTx, _ := tx2.WithSignature(signer, sigTx1)

// send transaction to node. Returns error insufficient funds for gas * price + value
if err := client.SendTransaction(context.Background(), signedTx); err != nil {
	log.Fatalln(err) // insufficient funds for gas * price + value
}
```

this is my current geth version: `Geth/miner1/v1.8.27-stable-4bcc0a37/linux-amd64/go1.11.9`

However, I believe this is unlikely to come across this behaviour as the common workflow is to use

```go
signedTx, _ := types.SignTx(tx, signer, privateKey)
```
for signing transaction which prevents messing around with the transaction payload and its signature.

**Comment by ligi** [comment]
I guess the reason is that "from" is not part of the RLP that get's signed - but from is recovered from the signature. So it is not clear if the signature is invalid - but an address is recovered that just does not have funds.

**Comment by salanfe** [comment]
You are right. We would need a 10th field on the transaction that holds the `from`. Signing the hash of this transaction: 
- from
- nonce
- to
- gas
- gasPrice
- value
- data
- v = chainID
- r = 0
- s = 0

It's surprising that there is no way to match the signature against the transaction payload, so that we are left checking the balance of the recovered account to verify the validity of the transaction (just went through the yellow paper, Appendix F, and to make I didn't missed anything).

Do you have any idea (or doc/links) why this was designed as such ? Is it because the collision risk with another `from` is so low that we considered it safe ? thx

**Comment by karalabe** [comment]
There was no reason to add 20 more extra bytes per transaction. On mainnet that currently would total to 20B * 460M tx = 9.2GB of redundant data.

**Comment by salanfe** [comment]
thank you +1
