### ISSUE TITLE
Get receipts by block number

### ISSUE THREAD

**Issue by ramilexe** [ethereum/go-ethereum#19634]
Why you did not add RPC method `GetReceipts` by block number or block hash?
It is internally stored by block hash.

**Comment by hadv** [comment]
I think you can do it with `FilterLogs`

**Comment by ramilexe** [comment]
Hi @hadv 
I don't need logs, I need receipts (`gasUsed` field).

**Comment by ligi** [comment]
is perhaps using graphql an option until this is implemented?

**Comment by holiman** [comment]
For old RPC, it's intrinsically a lot of work. Receipts are stored in batches of 4096, so iterating ove block numbers to deliver the partial results will be a bad experience. 
This may be a better fit to put into the GraphQL api, if it does not already have support for that.

**Comment by adamschmideg** [comment]
This is a valid question / request. You may be interested in the GraphQL which supports this.

**Comment by karalabe** [comment]
Maybe try GraphQL? :))

**Comment by ramilexe** [comment]
Implemented new RPC API `eth_getBlockReceipts ` in PR #19721
@karalabe @holiman please review :)

**Comment by sm1thbr3n** [comment]
Re: [ethereum/go-ethereum] RPC method GetReceipts by block number or block hash 551203

**Comment by adamschmideg** [comment]
This is how you can [get gasUsed with GraphQL](https://ethql-alpha.infura.io/graphql?query=%7B%0A%20%20block(number%3A%205000000)%20%7B%0A%20%20%20%20hash%0A%20%20%20%20gasUsed%0A%20%20%7D%0A%7D)

**Comment by richmanrich** [comment]
https://github.com/corpetty/py-etherscan-api

**Comment by kkeolmusae** [comment]
https://github.com/ethereum/go-ethereum/releases/tag/v1.13.0

Support eth_getBlockReceipts RPC API call now.
