### ISSUE TITLE
"Chunk [index?] found but could not be accessed: leveldb: not found, [index?]" when i doing swarm db migration

### ISSUE THREAD

**Issue by OmarHung** [ethereum/go-ethereum#19648]
#### System information

Version: 0.4.0-stable
Git Commit: c3b317a4fc5e59da87b2bd2b858c038cfb4ba07a
Go Version: go1.11.5
OS: linux

#### Expected behaviour
Swarm DB migration
https://github.com/ethereum/go-ethereum/blob/master/swarm/docs/migration-v0.3-to-v0.4.md

#### Steps to reproduce the behaviour
I had updated swarm v0.3 to v0.4. 
When I trying to run Swarm,  the swarm refuses to start and reports me to do db migration.
So I did this command:
````
$ swarm --verbosity 5 db export .ethereum/swarm/bzz-a8a75fcfa45273cdfe27c24d87ab9c41b199d9b7/chunks djstorage/swarmexport.tar 1bf9f5ae58719120e76c546b50eb573c65cb2952c8e977351cf1c13239f8dfaa
````
But I got this and swarm stopped db export：
````
TRACE[05-30|06:58:44.760] checking if database scheme is legacy    schema name=halloween 
CRIT [05-30|06:58:45.042] Chunk 0000018d92029660945b0f1883c14def16c7b4f81c57d8b3232c243a9c0ab3bb0b found but could not be accessed: leveldb: not found, 06030000000000000000
````

**Comment by acud** [comment]
this error is not breaking the export process. you would still get a valid tarball export which you can then import to the new localstore format. it does, however, infers that there was an index corruption in your database before starting the export process. if you've seen some process `panic` output during the export - that's a completely different story, but my assumption is that you have a tarball with all of the accessible chunks in your local store right where you expect it to be.

**Comment by nonsense** [comment]
Closing this, because the Swarm codebase now lives under `ethersphere/swarm`. Let's continue the discussion over at the new repo.
