### ISSUE TITLE
Add support for Debian

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#19643]
I'd like to install Geth on Debian with PPA

**Comment by adamschmideg** [comment]
Implementing this would require a lot of infrastructure work. I assume users who would use it are Linux power users who can build Geth, so it wouldn't bring much value.

**Comment by fjl** [comment]
A technical perspective on this issue: we use Launchpad to maintain the PPA for Ubuntu. Setting that up took a lot of time. We'd be happy to switch to https://openbuildservice.org/  which supports Debian, SUSE, etc. but everyone is really busy at the moment.
