### ISSUE TITLE
Trading has been at txpool

### ISSUE THREAD

**Issue by keienWang** [ethereum/go-ethereum#19658]
I have a private ethereum of version v1.7.3
Problem scenario
  I have two nodes,The first normal mining，The second only synchronizes the data of another node, not mining，When I use an account transfer (nonce=0) that has never been traded and submitted to the not mining node, the trade will remain in txpool.But there is no such transaction in the txpool of the first node.I use the account in the node that is mining to send another transaction, so that it will be executed. 
The issue 
When nonce=0, I want to know why the same account initiated the transaction without mining the node why not broadcast the transaction, but always exists with txpool

The txpool of the node being mined

![微信图片_20190604145438](https://user-images.githubusercontent.com/42377006/58857924-eedc8c80-86d8-11e9-938c-0a637839bb41.png)

Txpool of a node that has not been mined but is synchronizing

![微信图片_20190604145429](https://user-images.githubusercontent.com/42377006/58857968-10d60f00-86d9-11e9-918c-4adf145b54ba.png)

The account that executed the transaction submits the transaction to the unmined node (nonce!=0), and its transaction will be executed, but when nonce = 0, it will not be executed unless the transaction is submitted to the mining node.

Can anyone tell me why？

**Comment by karalabe** [comment]
Are you sure the two nodes are connected? What does `admin.peer` say? Also, miners can set their own gas prices to accept transactions, make sure your price is above the miner's allowance.

**Comment by keienWang** [comment]
> Are you sure the two nodes are connected? What does `admin.peer` say? Also, miners can set their own gas prices to accept transactions, make sure your price is above the miner's allowance.

I am sure they are connecting, because the second node is synchronizing the data of the first node, my gas is set to be large, there will be this problem, of course, I tested v1.8.15 and later, this problem has been solved I will slowly go back and look at where the problem is, thank you for your answer.

**Comment by keienWang** [comment]
> Are you sure the two nodes are connected? What does `admin.peer` say? Also, miners can set their own gas prices to accept transactions, make sure your price is above the miner's allowance.

Hello，I found that my problem was solved in this submission（e8f229b82ef99213f8f84b8a71f752b236024494）, but I still don't understand it. 
Problem ：
Two nodes, the first node is mining, the second node is connected to the first node, the data is synchronized, and the second node is not mined. I have an account with balance, this account has never been initiated. After trading (nonce = 0), use it to connect to the second node to initiate a transaction, gaslimit and gasprice are enough, then the transaction is always in the txpool of the second node, and the first node in the txpool There is no.

I checked a lot of information, there is no such information, I hope you can help me.  thanks

**Comment by karalabe** [comment]
1.7.3 is an ancient release that we cannot support. If new releases solve your problem, then please use a new one. We won't have time to go back 2 years in time and try to figure out what some issue was.
