### ISSUE TITLE
Failed to verify smartcard daemon path

### ISSUE THREAD

**Issue by busgo** [ethereum/go-ethereum#19654]
sudo ./geth  --identity "go-busgo" --datadir "./chain" --rpc 
INFO [06-02|11:39:59.684] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [06-02|11:39:59.685] Maximum peer count                       ETH=50 LES=0 total=50
ERROR[06-02|11:39:59.685] Failed to verify smartcard daemon path   path=/var/run/pcscd/pcscd.comm err="stat /var/run/pcscd/pcscd.comm: no such file or directory"
WARN [06-02|11:39:59.696] Found deprecated node list file /Users/apple/Desktop/wp/up/go-ethereum/build/bin/chain/static-nodes.json, please use the TOML config file instead. 
INFO [06-02|11:39:59.703] Starting peer-to-peer node               instance=Geth/go-busgo/v1.9.0-unstable-7a22da98-20190531/darwin-amd64/go1.10
INFO [06-02|11:39:59.703] Allocated trie memory caches             clean=1024.00MiB dirty=1024.00MiB

not sync block

**Comment by ligi** [comment]
I am pretty sure "not sync block" is unrelated to "Failed to verify smartcard daemon path"
I guess "Failed to verify smartcard daemon path" should just be an warning or even info - not an error. Not the first time people thought it is the reason for their sync problem

**Comment by gballet** [comment]
yeah, but it still catches an issue on my side. I'll make a PR for this. We would need more info for "not sync block" though.

**Comment by gballet** [comment]
Removing smart-card label as a fix for the smartcard warning has just been merged.

**Comment by busgo** [comment]
good resolve !

> 是的，但它仍然引起了我的一个问题。我会为此做一个公关。我们需要更多关于“不同步块”的信息。



> 我很确定“不同步块”与“无法验证智能卡守护程序路径”无关
> 我猜“无法验证智能卡守护程序路径”应该只是一个警告甚至是信息 - 而不是错误。这不是第一次人们认为这是他们同步问题的原因
 good idea
