### ISSUE TITLE
Miner address resolving error on the private POA ethereum network

### ISSUE THREAD

**Issue by northeusunshine** [ethereum/go-ethereum#19656]
Hi there,

I found the miner address in POA network is all zero number and try to get the address using ecrecover function in module "ethereumjs-utils". 
However after running the code, I got wrong result, the miner address resolved is not the one which signed the block. 

Please help.many thanks.

#### System information
Geth version: 
`
built from source code
Version: 1.8.27-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.12.4
Operating System: linux
GOPATH=/root/goworks
GOROOT=/usr/local/go
`
OS & Version: Linux
Chain Info:
`
Private POA chain ID:123456
The chain only has one node.
The coinbase address is 0x3c46b43e683b5addd7e66b3d1d958854ffb58361
`

#### Expected behaviour
The miner address is node address which sign the block.

#### Actual behaviour
The miner address calculated is `0x9a1da187d501ea796599dd0e2c9de52b1b1a3794`, it's incorrect address, it should be `0x3c46b43e683b5addd7e66b3d1d958854ffb58361`

#### Steps to reproduce the behaviour
step 1: Start the sealer node and mine
step 2: write miner address resolving code, like below:
```
const Web3 = require('web3');
const utils = require('ethereumjs-util');
const BlockHeader = require('ethereumjs-block/header');
const web3 = new Web3('http://localhost:8545');
const main = async () => {
const block = await web3.eth.getBlock(7);
const dataBuff = utils.toBuffer(block.extraData);
const sig = utils.fromRpcSig(dataBuff.slice(dataBuff.length - 65, dataBuff.length));
block.extraData = '0x' + utils.toBuffer(block.extraData).slice(0, dataBuff.length - 65).toString('hex');
console.log("got extraData = ",block.extraData);
const headerHash = new BlockHeader({
    parentHash: utils.toBuffer(block.parentHash),
    uncleHash: utils.toBuffer(block.sha3Uncles),
    coinbase: utils.toBuffer(block.miner),
    stateRoot: utils.toBuffer(block.stateRoot),
    transactionsTrie: utils.toBuffer(block.transactionsRoot),
    receiptTrie: utils.toBuffer(block.receiptsRoot),
    bloom: utils.toBuffer(block.logsBloom),
    difficulty: utils.toBuffer(block.difficulty),
    number: utils.toBuffer(block.number),
    gasLimit: utils.toBuffer(block.gasLimit),
    gasUsed: utils.toBuffer(block.gasUsed),
    timestamp: utils.toBuffer(block.timestamp),
    extraData: utils.toBuffer(block.extraData),
    mixHash: utils.toBuffer(block.mixHash),
    nonce: utils.toBuffer(block.nonce)
});
const pub = utils.ecrecover(headerHash.hash(), sig.v, sig.r, sig.s);
const address = utils.addHexPrefix(utils.pubToAddress(pub).toString('hex'));
console.log("miner address result:",address) ;
};
main();
```
step3： run the code in node，got the result：
```
extraData =  0xd88301081b846765746888676f312e31312e39856c696e757800000000000000
miner address result: 0x9a1da187d501ea796599dd0e2c9de52b1b1a3794
```
**The 7th block info**
```
> eth.getBlock(7)
{
  difficulty: 2,
  extraData: "0xd88301081b846765746888676f312e31312e39856c696e757800000000000000dd7dbfb525694a880603c92ed9326e2fdd37907ae2d2528b8bb9dc1ae11c605d03868c1644186b84ba300ec8f53681eb479ee2438ebad4f0f77e44a4725c55f401",
  gasLimit: 4732212,
  gasUsed: 0,
  hash: "0x6c9587d64ca2446bd7a6fd9d595e0bdf8af5b9627e7f32455c0f4fb4925ef7ce",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 7,
  parentHash: "0x9e72501d25bb1809b44568c4ec69ebdee92a22d9b05aaf104b5726992b19aba1",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 606,
  stateRoot: "0xf899500a3ff238853d1c23b73f799135770c1ba16e970f4feff385b7ab777c92",
  timestamp: 1559202842,
  totalDifficulty: 15,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
```

**Comment by northeusunshine** [comment]
@APshenkin I read and also  refer to your post [https://github.com/ethereum/go-ethereum/issues/17454#issue-352290530](url), still can not find where is the problem.
Could you help me how to fix it?
Thanks a lot!

**Comment by APshenkin** [comment]
@northeusunshine I think that you can ask POA developers about this. Miner address retrieving depends on it's consensus and mining algorithm

**Comment by karalabe** [comment]
Could you paste the block's RLP for us? That way we can check what our Go code does.

**Comment by holiman** [comment]
I suspect the `v` needs either `+27` or `-27`, depending on what it is now. Clique does not use the `27/28` ethereum-v-style

**Comment by holiman** [comment]
So try
```
const pub = utils.ecrecover(headerHash.hash(), sig.v+28, sig.r, sig.s);
```

**Comment by northeusunshine** [comment]
when it run at `const pub = utils.ecrecover(headerHash.hash(), sig.v+27, sig.r, sig.s)`, 
an error says `(node:30875) UnhandledPromiseRejectionWarning: Error: Invalid signature v value
    at Object.exports.ecrecover (/root/sw/token/node_modules/ethereumjs-util/dist/index.js:326:15)
    at main (repl:27:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:30875) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30875) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
and the `sig.v` is 27 from print message.
I also tried sig.v-27, the same error occured.

**Comment by northeusunshine** [comment]
@karalabe I have no idea about how to print block's RLP, please provide some guidance,thanks.

**Comment by northeusunshine** [comment]
@holiman After try, for `const pub = utils.ecrecover(headerHash.hash(), sig.v+28, sig.r, sig.s);`, the result is same.

**Comment by holiman** [comment]
@northeusunshine could you try just printing out so we know what `sig.v` actually is?

**Comment by northeusunshine** [comment]
I run the codes below to print sig.v, sig.r and sig.s:

```
const pub = utils.ecrecover(headerHash.hash(), sig.v, sig.r, sig.s);
console.log(sig.v);
console.log(sig.r);
console.log(sig.s);
```

The print info:
```
28
<Buffer 14 f5 e4 36 b9 66 b6 0f 59 67 5d 7f d8 98 a6 34 6c 01 13 fc 79 7e 5e 17 d4 ce 03 b9 4e d8 e1 78>
<Buffer 59 a5 cb 3b fd bc a2 25 1b 75 f6 86 b6 ac df 59 ec b9 ad 7c 94 9e 0b 98 c1 7c 01 c0 90 0c 6f f3>
```

The parsed miner address is not correct:
```
Calculated miner address :  
0x73f3e81040f6cf00665900f705640318b613dbe1

Actual miner address: 
> eth.accounts
["0xdbdff03e23f5bc61f546aa429300f9d269b0d797"]
```

Thanks.

**Comment by holiman** [comment]
This is not related to geth, and it's becoming pretty state. I hope you eventually solved it, but as it's really not a geth-related issue, we're closing this
