### ISSUE TITLE
consider using gqlgen

### ISSUE THREAD

**Issue by gracenoah** [ethereum/go-ethereum#19651]
I noticed that you guys are starting to do some graphql stuff and that you are using graph-gophers. I want to just make sure you are aware of the existence of gqlgen and you've considered it before you invest too much into graph-gophers. I strongly believe that gqlgen is significantly better. Check out their feature comparison: https://gqlgen.com/feature-comparison/ The main reason why I like it, though is the separation between models and resolvers.

If you still choose to stick with graph-gophers, that's fine, but when I was initially searching for a graphql library, I didn't find gqlgen until I had already written a lot of code for graph-gophers and the result is that our codebase would have been much cleaner if I knew about it earlier. Feel free to close this issue if you've already considered gqlgen.

**Comment by adamschmideg** [comment]
Thank you for pointing it out.

**Comment by holiman** [comment]
cc @Arachnid

**Comment by Arachnid** [comment]
I'm happy to consider a PR to migrate it over, but given it's mostly already implemented, I'm not keen to do a big rewrite myself.

**Comment by gballet** [comment]
Agreed. @gracenoah thank you very much for bringing this library to our attention. Right now, our graphql module does the job so we will keep it as is, following the principle that "if it ain't broken, don't fix it". If feature requests come from the community or if someone else writes that PR we'll definitely consider the switch. At the moment, though, it's not the squeakiest wheel so we'll leave it as is.
