### ISSUE TITLE
Synchronous completion getBalacnce 0 

### ISSUE THREAD

**Issue by liuhuanhui** [ethereum/go-ethereum#19652]
after updated,I can't getBalacnce rightly . always return 0 by eth.getBalance,and eth.blockNumber also is 0
![image](https://user-images.githubusercontent.com/10370625/58743310-7ddf6f80-8461-11e9-829c-16836ce0cd99.png)
![image](https://user-images.githubusercontent.com/10370625/58756245-db89bf80-8526-11e9-9160-ce064b363667.png)

and I don't know how to resolver this problem

System information
Geth version: 1.8
OS & Version: centos
Commit hash : (if develop)

Expected behaviour
by getBalance method ,I can get the right balance!

Actual behaviour
return the balance is 0

Steps to reproduce the behaviour

#19324 
#19013
#18522

**Comment by liuhuanhui** [comment]
#19013

**Comment by liuhuanhui** [comment]
![image](https://user-images.githubusercontent.com/10370625/58756239-c44ad200-8526-11e9-9fc0-7118d3acdb35.png)

**Comment by hadv** [comment]
it seem you run fast sync mode and I saw that your code current block is still behind the highest block.

That might be the issue if fast sync, node can never sync to highest block

**Comment by liuhuanhui** [comment]
I use default sync mode, So how do I solve it? Do I need to change to full mode?

**Comment by hadv** [comment]
> I use default sync mode, So how do I solve it? Do I need to change to full mode?

default mode is full mode then the problem is your node is still behind the tipping point, so the getBalance will return 0

**Comment by liuhuanhui** [comment]
> > 我使用默认同步模式，那么我该如何解决呢？我需要更改为完整模式吗？
> 
> 默认模式是完全模式然后问题是你的节点仍然在临界点后面（同步还没有完成），所以getBalance将返回0

Isn't the default mode fast?
I saw that my current block number was the same as the latest one, and the balance was still zero.
I've removed the nodes and reused full mode synchronization

**Comment by liuhuanhui** [comment]
> > I use default sync mode, So how do I solve it? Do I need to change to full mode?
> 
> default mode is full mode then the problem is your node is still behind the tipping point (sync was not completed yet) , so the getBalance will return 0

Isn't the default mode fast?
I saw that my current block number was the same as the latest one, and the balance was still zero.
I've removed the nodes and reused full mode synchronization

**Comment by holiman** [comment]
Default mode is `fast`. Perhaps un-intuitively, because `fast` also results in a so called 'full node', a node which has the full block history and (current) state. 
The `mode=full` means it will execute block by block from genesis, and is not recommended, since it takes quite some time. 

@liuhuanhui your node is still syncing. You need to wait until it finishes downloading state, at which point it will be a couple of days/weeks behind the current tip, and then it will block-by-block import the remaining distance.  

This is not an error, just how things work.

**Comment by liuhuanhui** [comment]
> Default mode is `fast`. Perhaps un-intuitively, because `fast` also results in a so called 'full node', a node which has the full block history and (current) state.
> The `mode=full` means it will execute block by block from genesis, and is not recommended, since it takes quite some time.
> 
> @liuhuanhui your node is still syncing. You need to wait until it finishes downloading state, at which point it will be a couple of days/weeks behind the current tip, and then it will block-by-block import the remaining distance.
> 
> This is not an error, just how things work.

If I first specified sync mode full, and now I change to sync mode fast, is that OK? Will it affect the future use?

**Comment by holiman** [comment]
It cannot switch from full to fast, so it will ignore your change and continue full. And vice versa, it won't switch over to full-sync in the middle of a fast-sync

**Comment by liuhuanhui** [comment]
> 它无法从完全切换到快速，因此它将忽略您的更改并继续完整。反之亦然，它不会在快速同步过程中切换到全同步

I resynchronized, and now more than 10 days, I still query the balance of 0, web3. eth. getBlockNumber () is also 0, which makes me desperate.

**Comment by liuhuanhui** [comment]
> It cannot switch from full to fast, so it will ignore your change and continue full. And vice versa, it won't switch over to full-sync in the middle of a fast-sync

I resynchronized, and now more than 10 days, I still query the balance of 0, web3. eth. getBlockNumber () is also 0, which makes me desperate.

**Comment by mtahani** [comment]
I installed geth and waited for integrated blockchain (mode fast)
when run eth.syncing return false
I installed Mist and integrated with geth
I can get Balance from Account to Mist but return zero eth.getBalance command in geth console
what????

**Comment by liuhuanhui** [comment]
> I installed geth and waited for integrated blockchain (mode fast)
> when run eth.syncing return false
> I installed Mist and integrated with geth
> I can get Balance from Account to Mist but return zero eth.getBalance command in geth console
> what????
> ![image](https://user-images.githubusercontent.com/5221970/63241613-9cd3ed80-c269-11e9-809a-11cb5d441930.png)
> 
> ![image](https://user-images.githubusercontent.com/5221970/63241576-72823000-c269-11e9-8ab5-584276a532bd.png)

pending import status
