### ISSUE TITLE
Namehash for empty domain does not equal 0x0

### ISSUE THREAD

**Issue by mortelli** [ethereum/go-ethereum#19696]
Hello,

I've decided to open a question issue here since I have got no reply from the go-ethereum gitter or discord.

It is my understanding that the namehash for the empty string domain should result in the `0x00000000000000000000000000000000` hash.

However, when calling the `ens.EnsNode` function (`ethereum/go-ethereum/contracts/ens/ens.go:103`) with `""` as input, the output is a different hash.

Is this a bug, or expected behavior? If the latter is the case, why? 

#### System information
Geth
Version: 1.9.0-unstable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.2
Operating System: linux

#### Expected behaviour
`fmt.Printf("%v", ens.EnsNode(""))` → `[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]`

#### Actual behaviour
`fmt.Printf("%v", ens.EnsNode(""))` → `[136 212 132 58 243 2 194 9 50 134 137 140 211 76 186 122 71 28 60 220 228 199 133 20 252 151 28 60 106 83 137 30]`

**Comment by holiman** [comment]
> It is my understanding that the namehash for the empty string domain should result in the 0x00000000000000000000000000000000 hash.

I don't know how that could be. @Arachnid does that seem correct to you?

**Comment by holiman** [comment]
Also, the `ens.go` was removed by https://github.com/ethereum/go-ethereum/pull/15808 -- not sure if that was intentional or by mistake. @fjl ?

**Comment by holiman** [comment]
Sorry, it was dropped by https://github.com/ethereum/go-ethereum/pull/19661

**Comment by holiman** [comment]
The swarm-team was maintaining this, it's now been moved out from go-ethereum. Please file a ticket with https://github.com/ethersphere/swarm instead

**Comment by mortelli** [comment]
Thank you @holiman, I will do that.
