### ISSUE TITLE
Geth database version question

### ISSUE THREAD

**Issue by northeusunshine** [ethereum/go-ethereum#19693]
Hi there,

I found geth built from the latest master branch(git clone https://github.com/ethereum/go-ethereum.git, then compile source code by "make all" command) uses new database version different from Geth & Tools 1.8.27(latest stable excutable version now).

First I use  Geth & Tools 1.8.27(latest stable excutable version now), set up a clique eth node.
then I switch version to the one built from latest source code.

when I start the node again, I got error as below:
```
[root@localhost test]# geth --networkid 123456 --rpc --rpcport "8545" --rpccorsdomain "*" --datadir ./enode1/data --syncmode 'full' --port "2001" --rpcaddr "0.0.0.0" --rpcapi "admin,db,eth,miner,web3,net,personal,txpool"
INFO [05-28|10:50:12.097] Maximum peer count                       ETH=25 LES=0 total=25
INFO [05-28|10:50:12.189] Starting peer-to-peer node               instance=Geth/v1.8.27-stable-4bcc0a37/linux-amd64/go1.11.9
INFO [05-28|10:50:12.189] Allocated cache and file handles         database=/root/download/eth5/enode1/data/geth/chaindata cache=512 handles=2048
INFO [05-28|10:50:12.223] Initialised chain configuration          config="{ChainID: 123456 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: 5  ConstantinopleFix: <nil> Engine: clique}"
INFO [05-28|10:50:12.223] Initialising Ethereum protocol           versions="[63 62]" network=123456
Fatal: Error starting protocol stack: database version is v6, Geth 1.8.27-stable only supports v3
```
I think there should be an version compatible problem, so how to fix the problem when switching geth version.
Many thanks.

**Comment by rjl493456442** [comment]
Please always use the newer geth version since we don't support database degradation.

**Comment by karalabe** [comment]
Whenever we make a minor version bump (e.g. from 1.8.x to 1.9.0) you can expect incompatible breaking changes that will prevent going back down. There's no way to make old versions aware of new data formats. If you want to use 18.27, you need to only use that. Once you update, there'd no going back down.

**Comment by dexterity2k16** [comment]
Hi @karalabe , I downgraded geth to 1.8.27 and started on rinkeby with the same database of 1.9.0 and it worked fine. But starting on mainnet with the same dataset giving me this error.
Is there any work around for downgrading and using the same synced dataset?
