### ISSUE TITLE
Cannot send transaction within the SimulatedBackend: (receives "invalid transaction v, r, s values")

### ISSUE THREAD

**Issue by ssi91** [ethereum/go-ethereum#19699]
Hi there,

I've got an issue with testing on the simulated backend.
For instance if build and run following example (https://github.com/miguelmota/ethereum-development-with-go-book/blob/master/code/client_simulated.go) it falls  with following error:

`invalid transaction: invalid transaction v, r, s values`

#### System information

Geth version: `1.9.0-unstable`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour

Sent ETH to an address

#### Actual behaviour

`invalid transaction: invalid transaction v, r, s values`

#### Steps to reproduce the behaviour

Run the example above

#### Backtrace

````
panic: invalid transaction: invalid transaction v, r, s values

goroutine 1 [running]:
github.com/ethereum/go-ethereum/accounts/abi/bind/backends.(*SimulatedBackend).SendTransaction(0xc00002e680, 0x4628d80, 0xc0000240a8, 0xc0000da630, 0x0, 0x0)
	/Users/ssi/go/src/github.com/ethereum/go-ethereum/accounts/abi/bind/backends/simulated.go:321 +0x611
main.main()
	/Users/ssi/cryptoda_token/sbc.go:60 +0x5c8
exit status 2
````
`sbc.go` is the script above

**Comment by karalabe** [comment]
The simulated backend uses `1337` as the chain id, The code you linked to sets the chain id to 1. That might explain the reason for bad signatures.

**Comment by ssi91** [comment]
@karalabe Thank you for answer. I've tried to run it with `clientID` `1337` and got the same error.

**Comment by sm1thbr3n** [comment]
You should have received a copy of the GNUPL Lesser General Public License
Sign Tx implements usb wallet driver sending the transaction to the Ledger and..  d doesn't support signing this transaction  Please update to v1.0.3 at least" w version[O],...  p2psim provides a command-line client for a simulation HTTP API.

**Comment by holiman** [comment]
@ssi91 if it's all for testing, and nothing private, could you provide the rlp-data of the bad transaction (with chainid 1337)?

**Comment by karalabe** [comment]
Found the issue, will open a PR in a moment.

**Comment by karalabe** [comment]
@ssi91 So, the issue was that the simulated backend had the homestead signature scheme hard coded instead of EIP155 (the chainID one). Now I fixed that. It should still accept Homestead signatures (with a nil chain ID), but also non-nil chain IDs. Note, you still need to use 1337 for the ID (we forcefully use something that's incompatible with mainnet to avoid accidents).

**Comment by ssi91** [comment]
@karalabe It's working now with the sample and `chainID` `1337`. Thank you!

**Comment by Yazanalsharif** [comment]
hello guys how this issue resolved because the same error happened with me now

**Comment by ssi91** [comment]
> hello guys how this issue resolved because the same error happened with me now


@Yazanalsharif for my case it has been working since @karalabe fixed this. See above :)

**Comment by Yazanalsharif** [comment]
hello @karalabe 
can you help me please 
i created my private network with geth 
and i use this command to start geth :

`geth --rpc --rpcapi="personal,eth,web3,net,miner" --datadir=./privateNetworkEthereum --nodiscover --allow-insecure-unlock`

and  in another terminal i attach the geth with this command 
`geth --rpc --rpcapi="personal,eth,web3,net,miner" --datadir=./privateNetworkEthereum --nodiscover --allow-insecure-unlock`

after that i mined some ethereum and i unlocked my account 

so the problem is i can't sendTransaction between the accounts 


and when i trying  deploy my smart contract in geth it's display this error 

`invalid transaction: invalid transaction v, r, s values`

**Comment by prashantprabhakar** [comment]
+1. Having same issues with private-net setup. Although, I forked code 10 days ago and did some miner changes; like setting constant difficulty for test purposes.

`func (ethash *Ethash) CalcDifficulty(chain consensus.ChainReader, time uint64, parent *types.Header) *big.Int {
    //return CalcDifficulty(chain.Config(), time, parent)
    // @prashnt: Fixed difficulty to constant to save resources 
	return big.NewInt(10)
 }`

I can send ETH; but the deployment of contract gives error `invalid transaction: invalid transaction v, r, s values` .

Example of genesis file used:

`{
    "config": {
        "chainId": 34357,
        "homesteadBlock": 1,
        "eip150Block": 2,
        "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "eip155Block": 3,
        "eip158Block": 3,
        "byzantiumBlock": 4
        },
      "alloc": {
        "795035babd301bc30c6d01bcfa50bef8b32972b5": {"balance": "2000000000000000000000000"}
      },
      "coinbase"   : "0x0000000000000000000000000000000000000000",
      "difficulty" : "0x20000",
      "extraData"  : "",
      "gasLimit"   : "0xA7D8C0",
      "nonce"      : "0x0000000000000042",
      "mixhash"    : "0x0000000000000000000000000000000000000000000000000000000000000000",
      "parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
      "timestamp"  : "0x00"
    }
    
    `

**Comment by nuliknol** [comment]
having the same issue, and I think it is possibly related to config of the blocks:

`INFO [06-07|19:53:38.670] Initialised chain configuration          config="{ChainID: 1234 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 1 EIP155: 1 EIP158: 1 Byzantium: 1 Constantinople: 1 Petersburg: 1 Istanbul: 1, Muir Glacier: 1, Berlin: 1, London: 100000000000, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: <nil>, Engine: ethash}`

**Comment by nuliknol** [comment]
> having the same issue, and I think it is possibly related to config of the blocks:
> 
> `INFO [06-07|19:53:38.670] Initialised chain configuration config="{ChainID: 1234 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 1 EIP155: 1 EIP158: 1 Byzantium: 1 Constantinople: 1 Petersburg: 1 Istanbul: 1, Muir Glacier: 1, Berlin: 1, London: 100000000000, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: <nil>, Engine: ethash}`

solved it. I had an error in genesis.json file, so berlin block had the same number as london but they must be consecutive. didn't notice the 'Fatal' error during creation of genesis block.
