### ISSUE TITLE
accounts/keystore/keystore_test.go tmpKeyStore function can not use new as function name

### ISSUE THREAD

**Issue by likeaixi** [ethereum/go-ethereum#19707]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.9.0-unstable`
OS & Version: MacOS 10.14.4 (18E226)
Commit hash : (if `develop`)

#### Actual behaviour
accounts/keystore/keystore_test.go
tmpKeyStore function use  new as function name, but it is not allowed.

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
I don't understand.. Are you saying that the compilation fails due to this line?
https://github.com/ethereum/go-ethereum/blob/master/accounts/keystore/keystore_test.go#L382

 Could you provide the logs? I agree though, it doesn't look nice to use a keyword like that

**Comment by holiman** [comment]
Fixed by #19731
