### ISSUE TITLE
eth_getFilterLogs and eth_getFilterChanges returns empty value for blockHash

### ISSUE THREAD

**Issue by tymat** [ethereum/go-ethereum#1971]
eth_getFilterLogs and eth_getFilterChanges returns empty blockHash

```
{"address"=>"0xec12a25d07023e2aa8d0be611f9d0a2381b851f2", "topics"=>["0xdf50c7bb3b25f812aedef81bc334454040e7b27e27de95a79451d663013b7e17", "0x000000000000000000000000385acafdb80b71ae001f1dbd0d65e62ec2fff055", "0x00000000000000000000000000000000000000000000000000000000563bf5a2"], "data"=>"0x", "blockNumber"=>"0x1dc0", "logIndex"=>"0x0", "blockHash"=>"0x0000000000000000000000000000000000000000000000000000000000000000", "transactionHash"=>"0x0be3fb7459f9c485aa90897d81a20eeb75b3f46e4e8291daadad2ab877ffdbdf", "transactionIndex"=>"0x0"}
```

**Version**
```
Geth
Version: 1.3.0-dev
Git Commit: c841e39476777d0be14f04fc3a1c69f51df84933
Protocol Versions: [63 62 61]
Network Id: 473
Go Version: go1.5
OS: darwin
GOPATH=/Users/aeufemio/projects/gocode
GOROOT=/usr/local/go
```

**Comment by bas-vk** [comment]
Thx for the report.

On https://github.com/ethereum/go-ethereum/blob/master/miner/worker.go#L616 the default blockhash is set and never updated.

@obscuren, @fjl, any thoughs how we can solve this? We probably need to repair the existing state since none of the logs contain the BlockHash.

**Comment by obscuren** [comment]
@bas-vk this would only matter if you're mining. @tymat is this the case?

**Comment by tymat** [comment]
@obscuren     Yes, this is happening on my private test net.  Have not tried in main net yet.

**Comment by obscuren** [comment]
@tymat ok, yes @bas-vk that's indeed the issue. We should think about this since normally the logs are creating during processing which the miner completely skips. We must change the recording.
