### ISSUE TITLE
Help to fix bloombits chain reorged during section processing

### ISSUE THREAD

**Issue by fgnm** [ethereum/go-ethereum#19711]
#### System information

Geth version: `v1.9.0`
OS & Version: Linux
Commit hash : `ebbf3dfa`

#### Expected behaviour
No errors

#### Actual behaviour
An error appears running geth:
`
Section processing failed                type=bloombits error="chain reorged during section processing"
`

#### What's the problem?
I have a private blockchian, somehow during a transaction happens a fork somewhere that I'm not able to identify, I've discovered that:
`Block #8190 -> Block #8191 -> Block #8192 -> Block #8193 -> ... good chain`
bad fork ` .. Block #8190 -> Block #8191 -> null `

Now, how can I delete the fork? is this error something danger?
Thank you

**Comment by karalabe** [comment]
This is supposedly fixed on master.
