### ISSUE TITLE
The log package doesn't support GOOS=nacl GOARCH=amd64p32

### ISSUE THREAD

**Issue by zulhfreelancer** [ethereum/go-ethereum#19719]
#### System information

Geth version: 1.8.27
OS & Version: https://play.golang.org
Commit hash: N/A

#### Expected behaviour

Able to use `github.com/ethereum/go-ethereum/log` in https://play.golang.org site.

#### Actual behaviour

Got the following errors:

```
# github.com/ethereum/go-ethereum/log
../gopath496381130/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:12:29: undefined: syslog.Priority
../gopath496381130/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:13:13: undefined: syslog.New
../gopath496381130/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:19:50: undefined: syslog.Priority
../gopath496381130/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:20:13: undefined: syslog.Dial
../gopath496381130/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:24:39: undefined: syslog.Writer
../gopath496381130/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:51:40: undefined: syslog.Priority
../gopath496381130/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:55:61: undefined: syslog.Priority
```

#### Steps to reproduce the behaviour

```
dev:~ $ GO111MODULE=on GOOS=nacl GOARCH=amd64p32 go install github.com/ethereum/go-ethereum/log
go: finding github.com/ethereum/go-ethereum v1.8.27
go: downloading github.com/ethereum/go-ethereum v1.8.27
go: extracting github.com/ethereum/go-ethereum v1.8.27
go: finding github.com/go-stack/stack v1.8.0
go: downloading github.com/go-stack/stack v1.8.0
go: extracting github.com/go-stack/stack v1.8.0
# github.com/ethereum/go-ethereum/log
pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:12:29: undefined: syslog.Priority
pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:13:13: undefined: syslog.New
pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:19:50: undefined: syslog.Priority
pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:20:13: undefined: syslog.Dial
pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:24:39: undefined: syslog.Writer
pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:51:40: undefined: syslog.Priority
pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/log/syslog.go:55:61: undefined: syslog.Priority
```

#### Other Information

- Example Play: https://play.golang.org/p/BuJWq6L4Mx2
- This is issue was confirmed by Go contributor in https://github.com/golang/go/issues/31944#issuecomment-502172450

**Comment by holiman** [comment]
This is a good first issue for people that know their way around go, not a good first issue for someone who just wants to help out and doesn't really know go in depth.

**Comment by gballet** [comment]
@holiman @karalabe I did a quick test by adding `+build !nacl` in `log/syslog.go`, just to check what the other problems were. One of them is that `ethash` needs `mmap`, which is not supported in NaCl. A quick search yielded [this golang issue](https://github.com/golang/go/issues/16975):

>With nacl support being removed in 1.14 (#30439), this seems unlikely to be implemented. Closing here.

I think we should close this issue, it makes no sense to perform so much groundwork for something that will not be available in a year.

**Comment by gballet** [comment]
After discussing with the rest of the team, we will indeed be closing this issue for the reason outlined above as the costs clearly outweigh the benefits.
