### ISSUE TITLE
Error: Section processing failed chain reorged during section processing in geth

### ISSUE THREAD

**Issue by surabhiv** [ethereum/go-ethereum#19720]
when i am run geth it gives me error ERROR[06-15|06:43:39.368] Section processing failed                type=bloombits error="chain reorged during section processing". please provide solution how to resolve this.

![image](https://user-images.githubusercontent.com/24150492/59548209-4dbbc480-8f69-11e9-89f5-9ccd6fdb03b5.png)

**Comment by karalabe** [comment]
This is supposedly fixed on master.
