### ISSUE TITLE
[Feature] Support i2p

### ISSUE THREAD

**Issue by ghbjklhv** [ethereum/go-ethereum#19729]
**Objective**: Implement and Support i2p in Ethereum
**Description**: Explore the possibility of using the Ethereum network over i2p.
**Why?**: Many reasons, mainly for privacy and security but also to support decentralized communications. 
**Related Projects**:

- https://kovri.io/

________________________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75653130-feature-support-i2p)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75653130)](https://www.bountysource.com/issues/75653130-feature-support-i2p)

**Comment by karalabe** [comment]
Hey! Anonymous routing is not a bad idea in itself, but we definitely don't have the capacity nor sanity to reimplement I2P ourselves. Given that it's a Java project and it's not even as stable as Tor, I don't see this ever happening.

We might consider integrating tor itself, did some work towards that in https://github.com/ipsn/go-libtor, but even that is far out and needs serious cross platform work.
