### ISSUE TITLE
TravisCI: do not run build if lint command failed

### ISSUE THREAD

**Issue by ramilexe** [ethereum/go-ethereum#19722]
Hi, I suggest to not run all build commands if `lint` was failed.

![image](https://user-images.githubusercontent.com/1008882/59571002-c4aba700-90a8-11e9-9db5-7a2c6670b768.png)

**Comment by karalabe** [comment]
[Mind dump: We could do this via multi stage builds with a sentinel + fast_finish like in https://travis-ci.org/coala/coala-bears/builds/393940805 ]

**Comment by Meshugah** [comment]
Hey! Could I work on this? Could you give me some pointers on getting started if so?

**Comment by karalabe** [comment]
Sure. Take a peek at the commit in https://travis-ci.org/coala/coala-bears/builds/393940805, that enabled it for some random OSS project. We'd need something similar, just for the lint task. Check our current travis file on how we do the linting.

**Comment by tylerferrara** [comment]
Specifying the same stage name for multiple jobs will create a parallel build stage. https://github.com/travis-ci/travis-ci/issues/8295
