### ISSUE TITLE
Address memory consumption

### ISSUE THREAD

**Issue by sammy007** [ethereum/go-ethereum#1973]
After update daemon heated up to 470Mb in 2 days. Previously I noticed only 300+ max.

**Comment by fjl** [comment]
Note to self: could be the new trie cache.

**Comment by obscuren** [comment]
Removed the specific milestone. This is an ongoing effort.

**Comment by sammy007** [comment]
@obscuren 1.4 is much more greedy for memory than 1.3.6 now, 600 vs 300 Mb after equal amount of time after start. I use it for getWork.

**Comment by fjl** [comment]
Most memory in geth is consumed by

* pooled transactions
* per-peer lists of 'known' block/tx hashes
* the downloader queue
