### ISSUE TITLE
web3.eth.filter is not working on sever and it working fine on my geth console in ubantu 

### ISSUE THREAD

**Issue by AmrataRajput** [ethereum/go-ethereum#19739]
error: web3js.eth.filter is not a function
![image](https://user-images.githubusercontent.com/47444071/59772454-690c3400-92c9-11e9-86bf-53ec7ede5efe.png)

**Comment by ssi91** [comment]
It looks like you have different versions of web3js. Check it.
According to [this issue](https://github.com/ethereum/web3.js/issues/983) `web3js.eth.filter` the method was deprecated and deleted in web3js 1.0.

**Comment by AmrataRajput** [comment]
if the filter method is delete i also try the subscription method for but its also give the error of no level db found please provide me solution for this

**Comment by gballet** [comment]
@AmrataRajput the `geth` console is using an older API because our interpreter is fairly old. There is a new API for web3 (1.0) please have a look at [their documentation](https://web3js.readthedocs.io/en/1.0/web3-eth.html)
