### ISSUE TITLE
Block processing fails on ARM64

### ISSUE THREAD

**Issue by diglos** [ethereum/go-ethereum#19754]
#### System information

Geth version: 1.9.0-unstable
OS & Version: Linux/ARM64
Commits hash : cf47ee53 / 6f806293

#### Expected behaviour

Blockchain fast sync from scratch

#### Actual behaviour

During the sync, at the final stage, "BAD BLOCK and invalid gas used" messages start to show. Finally, it seems to finish the process ("Fast sync complete" shows up) but the gas errors appears again and the sync process enters in a BAD BLOCK loop.

#### Steps to reproduce the behaviour

I tried a fast sync with the following geth versions:

1.8.27
1.9.0-unstable (2 attempts with commits 6f806293 and cf47ee53)

With the same result, a BAD BLOCK loop

#### Backtrace

Attach find the log from the first "invalid gas" error:
```
16:04:33 ethnode-eb1bc592 geth[11109]: ########## BAD BLOCK #########
16:04:33 ethnode-eb1bc592 geth[11109]: Error: invalid gas used (remote: 7960974 local: 7892404)
```
To Fast sync complete message:
```
21:58:12 ethnode-eb1bc592 geth[11109]: INFO [06-17|21:58:12.039] Fast sync complete, auto disabling
```
And finally, the BAD BLOCK loop:
```
22:01:58 ethnode-eb1bc592 geth[11109]: ########## BAD BLOCK #########
22:01:58 ethnode-eb1bc592 geth[11109]: Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000  ConstantinopleFix: 7280000 Engine: ethash}
22:01:58 ethnode-eb1bc592 geth[11109]: Number: 7978479
....
22:01:58 ethnode-eb1bc592 geth[11109]: Error: invalid gas used (remote: 4269913 local: 4201343)
```
Please let me know if you need any additional info or action from my side.

[syslog-geth1.9-sync-bad-block-error.txt](https://github.com/ethereum/go-ethereum/files/3324436/syslog-geth1.9-sync-bad-block-error.txt)

**Comment by holiman** [comment]
In block `7978479`, you're getting some erros. The first appear to be tx index `67`, 
Correct (canon) values: 
`gas : 94636  cumulative: 2969681`
Your values: 
`gas: 26066 cumulative: 2901111  `

So it's off by `68570 gas`. Tx hash is `0x495cae92d697a5b715fbc37bc25c4f809cae0f08fcbedcaf05165a241651b379`

This is odd, but points towards a corrupted database. Could you please do a test on your SSD to see if it is in any way corrupted? It happes with old SSDs that they degrade, which can cause issues like this.

**Comment by diglos** [comment]
Sure. The disk is a Samsung EVO (1 year old). I did lots of syncs and tests so I think a hardware problem is possible, yes. I'll let you know the result.

Thanks for the prompt reply.

**Comment by diglos** [comment]
Hi,
It doesn't seem to be a disk problem. I ran badblocks -v /dev/nvme0n1 and smartctl -a /dev/nvme0n1 (see attached logs). However, apparently, disk tests are quite limited for NVMe disks.  Can you point me to other tools for performing a NVMe disk check in Linux?

Thanks!

[badblocks.txt](https://github.com/ethereum/go-ethereum/files/3324782/badblocks.txt)
[smartmontools.txt](https://github.com/ethereum/go-ethereum/files/3324783/smartmontools.txt)

**Comment by diglos** [comment]
Hi,
I purchased another NVMe drive (I was planning to, as I have 2 ARM boards now). I will do another fast sync and get back to you with more feedback. Additionally, Bruno Skvorc from blockandmortar.io is going to do some tests with the same hardware in the coming days as well.

**Comment by diglos** [comment]
Hi,

A quick note just to give you some feedback on this.

This time (new SSD), the sync is still ongoing (10 days of syncing). At this moment:

- Total size is 168GB
- State entries: 373M

But, I already noticed “invalid gas” messages with the following pattern: a BAD BLOCK error, a “gas mismatch” message and then Geth rolls back headers. Is this an expected behaviour or is there something wrong?

Regards.

**Comment by diglos** [comment]
Hi,

After several syncs with a new NVMe SSD disk (Samsung EVO 970 Plus 500 GB) and 2 different ARM boards the issue is still there.

It follows the same pattern. The sync process seems to be fine until the final state entries import (over the last 3-4 Million) :

A “**Committed new head block**” message shows up followed by “**Deallocated fast sync bloom**”. and a “**BAD BLOCK**” message

```
Jul  3 18:57:52 ethnode-91f787ed geth[2353]: INFO [07-03|18:57:52.135] Committed new head block                 number=8080049 hash=1ce5c4�~@�54f4ac
Jul  3 18:57:52 ethnode-91f787ed geth[2353]: INFO [07-03|18:57:52.171] Deallocated fast sync bloom              items=349445071 errorrate=0.006
Jul  3 18:57:57 ethnode-91f787ed geth[2353]: ERROR[07-03|18:57:57.241]
Jul  3 18:57:57 ethnode-91f787ed geth[2353]: ########## BAD BLOCK #########
Jul  3 18:57:57 ethnode-91f787ed geth[2353]: Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000  ConstantinopleFix: 7280000 Engine: ethash}
Jul  3 18:57:57 ethnode-91f787ed geth[2353]: Number: 8080050
```

A "**gas mismatch**" message:

`Jul  3 18:57:57 ethnode-91f787ed geth[2353]: Error: invalid gas used (remote: 7980151 local: 7878301)`

And Geth rolls back headers:

`Jul  3 18:58:08 ethnode-91f787ed geth[2353]: WARN [07-03|18:58:08.068] Rolled back headers                      count=2048 header=8080168->8078120 fast=8080049->8078120 block=8080049->8078120`

These cycle repeats lots of times (**BAD BLOCK error, gas mismatch and roll back headers**) until Fast sync is disabled and the sync process seems to end.

Several minutes later, a definite BAD BLOCK message appears and the sync stucks.  

I tried to remove the Go colletactor cap, compile Geth again and raise the cache to 2 or even 3 GB but the higher the cache value, the lower the performance of the sync process.

I tried the opposite, as well, as it turns out that devices with 4GB (like this) seems to have problems (Issue #19837, now closed) and ran a sync with 256 MB of cache. Same result.

It seems to me that, for some reason, Geth tries to end the sync process (by committing new head block)  before all state entries are imported (maybe 3M-4M) and gas errors start to show.

**Comment by karalabe** [comment]
Wondering if there's some issue caused by ARM itself. There were some compiler fixes in Go 1.12.7 released about two weeks ago. Could you try with 1.9.1 stable and report what happens?

**Comment by diglos** [comment]
Sure, I'll let you know the result as soon as possible.

**Comment by diglos** [comment]
In the meantime, attach find a chunk of the loop error with verbosity 4 for your consideration.

[get-sync-bad-block-verbosity4.txt](https://github.com/ethereum/go-ethereum/files/3427037/get-sync-bad-block-verbosity4.txt)

**Comment by diglos** [comment]
Hi,

I tried a couple of times and I'm afraid the result is the same. Attached find a log with the first gas error with verbosity 5 (after first "Committed new head block" message".
[geth-error-20190805.txt](https://github.com/ethereum/go-ethereum/files/3466647/geth-error-20190805.txt)

**Comment by diglos** [comment]
In the meanwhile, I compiled Geth 1.9.1 with Go 1.10 and started another sync to discard a Go ARM regression.

**Comment by HeikoLotz** [comment]
> In the meanwhile, I compiled Geth 1.9.1 with Go 1.10 and started another sync to discard a Go ARM regression.

Any news?

**Comment by diglos** [comment]
Not yet, I estimate 2-3 days left.

**Comment by diglos** [comment]
It worked. Seems that @karalabe was right and it is a Go for ARM thing. I'm packaging Geth 1.9.1 compiled with Go 1.10. Let me know if you want to close the issue or you need further info in order to find out what causes this with Go > 1.10.

**Comment by holiman** [comment]
Thanks for all your work @diglos ! @karalabe is there anything we need to do, or are the official ARM-releases already done with a good go-version?

**Comment by karalabe** [comment]
We need to find what the failure is. Go 1.10 is ancient, we need to report the ARM issue upstream and get it fixed. Not sure how to repro. @diglos Does syncing Goerli also produce this issue? That I might try to repro on my phone perhaps.

**Comment by diglos** [comment]
I will try with Goerli and report back.

**Comment by diglos** [comment]
Hi. Yes, it happens on Goerli as well but take into account that this is ARM64. I guess it may be reproduced on a Raspberry Pi 3 or 4 with a 64 bits image.

**Comment by karalabe** [comment]
Hey all, Go 1.12.9 was just released on Friday, which has a `big.Int` fix included for ARM64 (https://github.com/golang/go/issues/32940). This might actually have been the issue triggering the bad blocks. Would it be too much to ask of you to rebuild Geth with Go 1.12.9 and try a Goerli sync and see if you can still reproduce the bad blocks?

**Comment by diglos** [comment]
Absolutely, I will try as soon as I can (I'm away from home) and report back. Thanks Peter.

**Comment by diglos** [comment]
Yes, it worked with 1.12.9. Would you mind to leave this open until I am able to complete a mainnet fast sync?

Thanks!

**Comment by diglos** [comment]
Hi,
sorry for the delay. It works, I'm closing the issue.
Thanks!
