### ISSUE TITLE
Unable to call other contract function

### ISSUE THREAD

**Issue by princesinha19** [ethereum/go-ethereum#19752]
Actually, I  have written a smart contract in which I want to call other smart contracts (ERC20) function but I am not able to do that. 
Geth doesn't allow to call other contracts function.

#### System information

Geth version: 1.8.27-stable
OS & Version: Linux

#### Expected behaviour
It should allow calling other contract function using low-level call.

#### Actual behaviour
It doesn't allow to call other contract function.

#### My Geth Config
```
 "config": {
        "chainId": 13,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "eip160Block": 0,
        "byzantiumBlock": 0
   }
```

**Comment by karalabe** [comment]
What's failing? Show us some code, some logs. Without that we can't help find your bug.

Also you probably want to enable Constantinople and Petersburg forks, newer Solidity depends on features introduced in those.

**Comment by princesinha19** [comment]
```
ERC20 contract = ERC20(0xE7Cf373bc6dbda42ABCadEE138e8155EE05679d9);
uint256 r = contract.totalSupply();
return r;
```
This is the smart contract function which I am calling. It gives me VM revert error. If do you want something more in detail. Please let me know.

> Also you probably want to enable Constantinople and Petersburg forks, newer Solidity depends on features introduced in those.

If would be very helpful, If you can point me to the doc about how to configure these?

**Comment by fjl** [comment]
We need more information about how you call the contract exactly. Are you using the RPC API?

**Comment by holiman** [comment]
.. and what about geth logs? what is the exact error message? the fork definitions goes into the genesis you are using for your network

**Comment by karalabe** [comment]
Could you create a full repro for us? I.e.

 * Chain config you're using for your chain.
 * The transactions hat you use to deploy the contract(s).
 * The transaction that's failing.

The goal is to allow us to reproduce exactly what you're seeing.

**Comment by princesinha19** [comment]
> Chain config you're using for your chain.

Tysm @karalabe. This is the chain config, which I am using.
```
{
    "config": {
        "chainId": 13,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "eip160Block": 0,
        "byzantiumBlock": 0
    },
    "difficulty": "0",
    "gasLimit": "2100000",
    "alloc": {
    }
}

```

> The transactions that you use to deploy the contract(s).

I am deploying the contract through remix. I am using the below contract.
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/crowdsale/Crowdsale.sol

### Steps to Deploy crowdsale contract:-
1. When I deployed ERC20 Contract on geth, I received the contract address.
2. Then, I passed the ERC20 contract address as input in the constructor of crowdsale contract. I also passed the rate and wallet where I need to withdraw the ethers from the contract.

### Steps to Reproduce:-

1. Do step 1 and 2 of (Steps to Deploy crowdsale contract). You will receive the contract address.
2. Then transfer some Ether to Crowdsale Contract address.

You will get an error log:-
```
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x41378189f6c49471ed3b214388e15486afed8bb067d0bff6614555e435f04315",
  "blockNumber": 18,
  "contractAddress": null,
  "cumulativeGasUsed": 51011,
  "from": "0xcc8a6a72f088b278157ecc68fa8813da266f4033",
  "gasUsed": 51011,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x7e289abe5f5d0b8e3f06470f70016afadf80f90d",
  "transactionHash": "0xfd8d96d22b95acf8e0c67ed4896d4312feb2783a1b68faaf0c6aca653b50f158",
  "transactionIndex": 0
}
    at /home/node_modules/web3-core-method/src/index.js:364:46
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Sometimes, I get the error **SafeERC20: low-level call failed.**

### Geth Logs
```
> INFO [06-25|18:11:52.428] Submitted transaction                    fullhash=0xfd8d96d22b95acf8e0c67ed4896d4312feb2783a1b68faaf0c6aca653b50f158 recipient=0x7E289aBe5F5D0b8e3F06470f70016AFaDF80F90d
== Pending transactions! Mining...
INFO [06-25|18:11:52.523] Updated mining threads                   threads=1
INFO [06-25|18:11:52.523] Transaction pool price threshold updated price=1000000000
INFO [06-25|18:11:52.524] Commit new mining work                   number=18 sealhash=a392cc…fe6dcd uncles=0 txs=0 gas=0       fees=0           elapsed=154.605µs
INFO [06-25|18:11:52.524] Commit new mining work                   number=18 sealhash=c10ed7…961f1f uncles=0 txs=1 gas=51011   fees=5.1011e-05  elapsed=653.797µs
INFO [06-25|18:11:53.813] Successfully sealed new block            number=18 sealhash=c10ed7…961f1f hash=413781…f04315 elapsed=1.288s
INFO [06-25|18:11:53.813] 🔗 block reached canonical chain          number=11 hash=67bd3a…e15bba
INFO [06-25|18:11:53.813] 🔨 mined potential block                  number=18 hash=413781…f04315
INFO [06-25|18:11:53.813] Commit new mining work                   number=19 sealhash=b24397…3a3e08 uncles=0 txs=0 gas=0       fees=0           elapsed=135.112µs
== No transactions! Mining stopped.
INFO [06-25|18:12:50.314] Regenerated local transaction journal    transactions=0 accounts=0
> INFO [06-25|18:14:46.683] New local node record                    seq=191 id=e84495c10e7d3839 ip=203.192.248.140 udp=30303 tcp=30303

```

**Comment by holiman** [comment]
Remix probably builds it for `Constantinople`/`ConstantinopleFix`, which e.g. has shift operations, which are not availalbl on your chain. That would cause invalid operation, and thus revert. You need to compile with appropriate target (byzantium).

**Comment by princesinha19** [comment]
Thanks, @holiman.
> You need to compile with appropriate target (byzantium).

Which target should I choose? Should I use truffle?

**Comment by holiman** [comment]
> Or should I add Constantinople/ConstantinopleFix in my chain config?

Yes, I'd recommend keeping it with mainnet, that way most tools like remix/solidity will "just work"

**Comment by princesinha19** [comment]
> Yes, I'd recommend keeping it with mainnet, that way most tools like remix/solidity will "just work"

@holiman But, I want to use in private ethereum network. So, It will be very helpful if you can point me to the documentation, where I can see how to write configs for `Constantinople/ConstantinopleFix`.

**Comment by holiman** [comment]
See https://solidity.readthedocs.io/en/v0.5.9/using-the-compiler.html?highlight=byzantium#target-options for how to target for a particular evm-version. Your config above is set to use `Byzantium`

**Comment by princesinha19** [comment]
Yes, thank you so much @holiman. I will look into the documentation.

bdw, my Geth log for configs:-
```
NFO [06-25|12:03:32.358] Maximum peer count                       ETH=25 LES=0 total=25
INFO [06-25|12:03:32.359] Starting peer-to-peer node               instance=Geth/v1.8.27-stable-4bcc0a37/linux-amd64/go1.10.4
INFO [06-25|12:03:32.359] Allocated cache and file handles         database=/home/prince/.ethereum/geth/chaindata cache=512 handles=2048
INFO [06-25|12:03:32.380] Writing default main-net genesis block 
INFO [06-25|12:03:32.646] Persisted trie from memory database      nodes=12356 size=1.88mB time=62.147895ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [06-25|12:03:32.646] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000  ConstantinopleFix: 7280000 Engine: ethash}"
INFO [06-25|12:03:32.646] Disk storage enabled for ethash caches   dir=/home/prince/.ethereum/geth/ethash count=3
INFO [06-25|12:03:32.646] Disk storage enabled for ethash DAGs     dir=/home/prince/.ethash               count=2
```

**Comment by princesinha19** [comment]
And when I initialized the` Constantinople/ConstantinopleFix` in my config.
```
"config": {
        "chainId": 13,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "eip160Block": 0,
        "byzantiumBlock": 0,
        "Constantinople": 0,
        "ConstantinopleFix": 0
    }
```
Then, I am getting below error in geth.

```
ERROR[06-25|18:45:24.786] 
########## BAD BLOCK #########
Chain config: {ChainID: 13 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: <nil>  ConstantinopleFix: <nil> Engine: unknown}

Number: 1
Hash: 0x717830d768bab0e54052385740cd966788e831f0683c6f8cf346e42423e546cb


Error: invalid merkle root (remote: dfb77b3da906b7b0361f0f4e4b3e9869f39de79c4a8c285753c86546b0b0c459 local: 67e24a61e663ee9847ce0ac529bb4474faa7e920efd0cd0866c4d4d74abc6831)
##############################
 
WARN [06-25|18:45:24.786] Synchronisation failed, dropping peer    peer=ede02941510f673a err="retrieved hash chain is invalid"


```

**Comment by karalabe** [comment]
You can't retrospectively change the rules of the chain (i.e. blocks created without Petersburg won't import with it). You need to restart a fresh chain if you want to enable everything in block 0, or you need to enable it in a later block.

Also, note that your error message reports that you only enabled Homestead, nothing afterwards: `Chain config: {ChainID: 13 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: <nil>  ConstantinopleFix: <nil> Engine: unknown}
`

Also, `ConstantinopleFix` is called `Petersburg` in the config file. It was an unfortunate oversight to output it in a different name in the log. Will fix.

**Comment by princesinha19** [comment]
> You can't retrospectively change the rules of the chain (i.e. blocks created without Petersburg won't import with it). You need to restart a fresh chain if you want to enable everything in block 0, or you need to enable it in a later block.

Thanks, @karalabe for your answer. But, before changing the rule, I ran geth removedb so, that it can enable everything from block 0.

**Comment by adamschmideg** [comment]
Could you change the rules and start a fresh chain? Can we consider this issue resolved?

**Comment by princesinha19** [comment]
> Could you change the rules and start a fresh chain? Can we consider this issue resolved?

@adamschmideg, yes I did the installation of the fresh chain but the issue is same.

**Comment by holiman** [comment]
> Also, ConstantinopleFix is called Petersburg in the config file. It was an unfortunate oversight to output it in a different name in the log. Will fix.

Actually, it's `petersburgBlock` iirc

**Comment by karalabe** [comment]
Also `constantinopleBlock`.

**Comment by adamschmideg** [comment]
This seems to be not an issue with go-ethereum but with using it. We'd like to keep the issue tracker clean. The best place to get advise on this is https://ethereum.stackexchange.com/ A related question is https://ethereum.stackexchange.com/questions/67794/how-to-setup-constantinople-fork-for-private-ethereum-chain.
