### ISSUE TITLE
Android: abi: cannot use slice as type array as argument

### ISSUE THREAD

**Issue by sempiecampos** [ethereum/go-ethereum#19759]
#### System information

Geth version: 1.8.23
OS & Version: Android

#### Expected behaviour

For setter (on ethereumClient ):
Need to set a bytes32 input .
Called  
paramAddress.setBinary(byte[32]);

#### Actual behaviour
when calling paramAddress.setBinary(byte[32]); 
geth reports back that the array cannot be used for the contract call 

#### Steps to reproduce the behaviour
1. Try to call a contract the requires a single input type of Bytes32 and Single output type 
2. exectue contact call, boundContract.call(opts, results, "isBiometricCompleted", params);

#### Android Code
            String InfuraURL = Utils.getApiKey();
            EthereumClient ethereumClient = Geth.newEthereumClient(InfuraURL);
            BoundContract boundContract;
            Address contractAddress;

            byte[] shabyteArray = new byte[32];
            shabyteArray = Utils.hexStr2ByteArray(sha);

            ABI = Constants.getRisenAbi();
            contractAddress = Geth.newAddressFromHex(Constants.getRisenContractAddress());
            boundContract = Geth.bindContract(contractAddress, ABI, ethereumClient);

            Interface param = Geth.newInterface();
            param.setBinary(shabyteArray);
            Interfaces params = Geth.newInterfaces(1);
            params.set(0, paramAddress);

            Interface rx = Geth.newInterface();
            rx.setDefaultBools();
            Interfaces results = Geth.newInterfaces(1);
            results.set(0, balanceResult);

            CallOpts opts = Geth.newCallOpts();
            opts.setContext(Geth.newContext());
            boundContract.call(opts, results, "isBiometricCompleted", params);
            boolean response = balanceResult.getBool();

#### Contract ABI 

{"constant":true,"inputs":[{"name":"sha","type":"bytes32"}],"name":"isBiometricCompleted","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"}

#### Backtrace

System.out: go.Universe$proxyerror: abi: cannot use slice as type array as argument
````
[backtrace]
````

**Comment by rjl493456442** [comment]
Could you please try this PR https://github.com/ethereum/go-ethereum/pull/19180? Probably the issue is fixed.

1: Generate andrioid package via `gomobile bind --target android --javapkg org.ethereum -v github.com/ethereum/go-ethereum/mobile`
2: Import the package to your android project.

**Comment by sempiecampos** [comment]
@rjl493456442 
I generated the package and imported as requested but I still got the same error:
go.Universe$proxyerror: abi: cannot use slice as type array as argument
