### ISSUE TITLE
vdf

### ISSUE THREAD

**Issue by yyyyyp** [ethereum/go-ethereum#19756]
Can you talk about the progress of VDF

**Comment by yyyyyp** [comment]
Specifically, what VDF algorithm do you want to implement

**Comment by yyyyyp** [comment]
Can we see the  source  code of VDF

**Comment by gballet** [comment]
@yyyyyp this is the wrong channel to ask, the VDF is an Eth2 construct and geth is a Eth1 client. We recommend that you as the question on ethresear.ch
