### ISSUE TITLE
How to get an RPC error code?

### ISSUE THREAD

**Issue by mushketyk** [ethereum/go-ethereum#19766]
#### System information

Geth version: 1.8.27
OS & Version: Go package

I would like to get an error code returned by JSON RPC API. The error code is provided in the `rpc.jsonError` struct:

```go
type jsonError struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
```

And it is returned by the `CallContext` function in `rpc/client.go`: 

```go

func (c *Client) CallContext(ctx context.Context, result interface{}, method string, args ...interface{}) error {
	msg, err := c.newMessage(method, args...)
	
        ...

	switch resp, err := op.wait(ctx); {
	case err != nil:
		return err
	case resp.Error != nil:
		return resp.Error // <------- HERE
	case len(resp.Result) == 0:
		return ErrNoResult
	default:
		return json.Unmarshal(resp.Result, &result)
	}
}
```

But this method can also return errors of other types.

To get an error code I would need to do something like this:

```go
err := c.rpc.CallContext(...)
if e != nil {

    switch v := e.(type) {
        case *rpc.jsonError:
        // JSON RPC error. I can get an error code from
        default:
        // Not a JSON RPC error 
    }
}
```

Unfortunately, `jsonError` type is not exported.

Is there another way to get an error code?
Would it make sense to export the `jsonError` type?

**Comment by karalabe** [comment]
Unfortunately the Ethereum JSON RPC spec doesn't cover error codes at all. As such, we haven't been paying much attention to the code itself, since they are probably not used extensively/meaningfully. That said, I think it might make sense to allow casting to our original types back (i.e. to make that public). Ping @fjl for some input?

**Comment by mushketyk** [comment]
@karalabe 

> Unfortunately the Ethereum JSON RPC spec doesn't cover error codes at all

It seems that JSON RPC 2.0 [defines error codes](https://www.jsonrpc.org/specification) and from what I see Geth returns an error object with an error code from this range.

**Comment by adamschmideg** [comment]
Right now it's always the same error is returned. We plan to have an EIP later on to define different error codes for different scenarios.

**Comment by marknguyen85** [comment]
> #### System information
> Geth version: 1.8.27
> OS & Version: Go package
> 
> I would like to get an error code returned by JSON RPC API. The error code is provided in the `rpc.jsonError` struct:
> 
> ```go
> type jsonError struct {
> 	Code    int         `json:"code"`
> 	Message string      `json:"message"`
> 	Data    interface{} `json:"data,omitempty"`
> }
> ```
> 
> And it is returned by the `CallContext` function in `rpc/client.go`:
> 
> ```go
> func (c *Client) CallContext(ctx context.Context, result interface{}, method string, args ...interface{}) error {
> 	msg, err := c.newMessage(method, args...)
> 	
>         ...
> 
> 	switch resp, err := op.wait(ctx); {
> 	case err != nil:
> 		return err
> 	case resp.Error != nil:
> 		return resp.Error // <------- HERE
> 	case len(resp.Result) == 0:
> 		return ErrNoResult
> 	default:
> 		return json.Unmarshal(resp.Result, &result)
> 	}
> }
> ```
> 
> But this method can also return errors of other types.
> 
> To get an error code I would need to do something like this:
> 
> ```go
> err := c.rpc.CallContext(...)
> if e != nil {
> 
>     switch v := e.(type) {
>         case *rpc.jsonError:
>         // JSON RPC error. I can get an error code from
>         default:
>         // Not a JSON RPC error 
>     }
> }
> ```
> 
> Unfortunately, `jsonError` type is not exported.
> 
> Is there another way to get an error code?
> Would it make sense to export the `jsonError` type?

```
err = c.rpc..Call(nil, method)
if err != nil {
	var jsonErr = err.(rpc.Error)
        // and you can use jsonErr.ErrorCode() to get error code
}
```
