### ISSUE TITLE
Transaction getting stuck in the queue

### ISSUE THREAD

**Issue by princesinha19** [ethereum/go-ethereum#19767]
Transaction getting stuck in the queue when doing the transaction from Metamask.
It is working fine with ganache but with geth, it gets stuck in the queue.

#### System information

Geth version: 1.8.27-stable
OS & Version: Linux

#### Expected behaviour
The transaction should be mined and complete.

#### Actual behaviour
Transaction submitted and stuck in the queue.

#### Steps to reproduce the behaviour
1. Connect your **localhost** network with metamask
2. Create a wallet from the metamask interface
3. Import One existing wallet.
4. Transfer some ether from imported wallet to created wallet (It will succeed)
5. Then, Transfer ether back from new wallet to imported wallet (It will get stuck)

You can check queued transaction using txpool.content.queued or txpool.inspect.queued.

#### txpool.inspect.queued
```
> txpool.content.queued
{
  0x57D3FF2b3D90fA014f4722C2509dB5c6a1014a60: {
    13: {
      blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
      blockNumber: null,
      from: "0x57d3ff2b3d90fa014f4722c2509db5c6a1014a60",
      gas: "0x5208",
      gasPrice: "0x2540be400",
      hash: "0x2a20db55d59c74d696b46324ce9711e0497c734ff451eb7beebcfc07aa1f6255",
      input: "0x",
      nonce: "0xd",
      r: "0xa00fac277795c8084a45d74d64a157a709c07b5b0e634669c99940a88058c6f5",
      s: "0x41c355d02e2d6501e8d75c3f2c9363a9d29ca3fcb76e0c504b36c7d0897dd756",
      to: "0xcc8a6a72f088b278157ecc68fa8813da266f4033",
      transactionIndex: "0x0",
      v: "0x3d",
      value: "0xde0b6b3a7640000"
    }
  }
}
```

```
> txpool.inspect.queued
{
  0x57D3FF2b3D90fA014f4722C2509dB5c6a1014a60: {
    13: "0xCc8A6a72F088B278157ecc68Fa8813da266F4033: 1000000000000000000 wei + 21000 gas × 10000000000 wei"
  }
}
```
#### Command to start geth
geth --rpc --rpccorsdomain "*" --ws --wsorigins "*" --wsaddr "127.0.0.1" --rpcapi "web3,personal,eth,admin,net,debug" --wsapi personal,web3,eth,net,db,admin,debug --unlock 0  --preload "auto_start_mining.js" --networkid 13 console

**Comment by karalabe** [comment]
If a transaction is in the `queue`, it means it's not executable. Most probably there's a nonce gap.

**Comment by princesinha19** [comment]
> If a transaction is in the queue, it means it's not executable. Most probably there's a nonce gap.

Yes, I checked and there is a nonce gap so, how to solve this. Why If I create a wallet in metamask goes into the txpool queue?

**Comment by karalabe** [comment]
Fill the gap. Create a transaction with the correct nonce. As to why Metamask created an invalid transaction, that I cannot say.

**Comment by adamschmideg** [comment]
You may want to check the [nonce-related Metamask issues](https://github.com/MetaMask/metamask-extension/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+nonce) or report an issue there.

**Comment by karalabe** [comment]
This really seems an issue in Metamask, creating a wrong transaction (gapped one). There's not much we can do if the transaction signed is off. Please open an issue at Metamask with a repro. Perhaps ping us here to have a reference.
