### ISSUE TITLE
regression: rpc.Client#Unsubscribe blocks indefinitely when shutdown w node

### ISSUE THREAD

**Issue by dimroc** [ethereum/go-ethereum#19768]
Hi all,
I've reproduced a regression of https://github.com/ethereum/go-ethereum/issues/17837 but am unable to reopen the issue. I've copied and updated the description below. There is also a video and repo to reproduce the bug here:
* https://asciinema.org/a/lc2VEuz0zhCLWE4dkkoBdd4Hg
* https://github.com/dimroc/geth-blocks-unsubscribe

---

Hi there!
While developing [Chainlink](https://github.com/smartcontractkit/chainlink), which uses go-ethereum's rpc.Client libraries, we were unable to gracefully disconnect from our Geth node. We've traced it back to our inability to [`Unsubscribe`](https://github.com/ethereum/go-ethereum/blob/4bcc0a37ab70cb79b16893556cffdaad6974e7d8/rpc/client.go#L715) our websocket rpc.Client. We've reproduced the problem using exclusively `go-ethereum` code and appreciate any insight. We're also open to fixing the bug ourselves if pointed in the right direction.

Thanks in advance for any help.

#### System information

Geth version:
Version: 1.8.27
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.12
Operating System: darwin
GOPATH=/Users/dimroc/go
GOROOT=/usr/local/Cellar/go/1.12/libexec
GETH COMMIT SHA=4bcc0a37ab70cb79b16893556cffdaad6974e7d8

OS & Version: OSX

#### Expected behaviour
[`*rpc.Client#Unsubscribe`](https://github.com/ethereum/go-ethereum/blob/4bcc0a37ab70cb79b16893556cffdaad6974e7d8/rpc/client.go#L715) returns and does not block indefinitely.

#### Actual behaviour
[`*rpc.Client#Unsubscribe`](https://github.com/ethereum/go-ethereum/blob/4bcc0a37ab70cb79b16893556cffdaad6974e7d8/rpc/client.go#L715) blocks indefinitely.

#### Steps to reproduce the behaviour

[![asciicast](https://asciinema.org/a/lc2VEuz0zhCLWE4dkkoBdd4Hg.png)](https://asciinema.org/a/lc2VEuz0zhCLWE4dkkoBdd4Hg)

For a preconfigured reproduction, please see: https://github.com/dimroc/geth-blocks-unsubscribe

1. Run geth 
2. Run and attach a go-ethereum client
3. subscribe to newHeads and logs
4. Listen to a handful of heads and logs
5. Kill all processes simultaneously
6. Run `ps` and notice the client is blocked.
7. Use [dlv](https://github.com/derekparker/delve) to investigate.

Again, this is set up and done for you in https://github.com/dimroc/geth-blocks-unsubscribe.

This issue is spurious, but in practice it reproduces 75% of the time.

#### Backtrace

```
(dlv) bt
 0  0x0000000004030b9f in runtime.gopark
    at /usr/local/Cellar/go/1.12.6/libexec/src/runtime/proc.go:302
 1  0x000000000403fa48 in runtime.selectgo
    at /usr/local/Cellar/go/1.12.6/libexec/src/runtime/select.go:313
 2  0x000000000434eed4 in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*Client).send
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:422
 3  0x000000000434dc00 in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*Client).CallContext
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:263
 4  0x0000000004351dad in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*Client).Call
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:245
 5  0x0000000004351dad in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*ClientSubscription).requestUnsubscribe
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:797
 6  0x00000000043550d4 in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*ClientSubscription).quitWithError.func1
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:726
 7  0x0000000004070c93 in sync.(*Once).Do
    at /usr/local/Cellar/go/1.12.6/libexec/src/sync/once.go:44
 8  0x0000000004351345 in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*ClientSubscription).quitWithError
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:720
 9  0x0000000004351288 in github.com/dimroc/geth-blocks-unsubscribe/vendor/github.com/ethereum/go-ethereum/rpc.(*ClientSubscription).Unsubscribe
    at ./vendor/github.com/ethereum/go-ethereum/rpc/client.go:715
10  0x0000000004356d87 in main.main
    at ./main.go:47
11  0x00000000040307ac in runtime.main
    at /usr/local/Cellar/go/1.12.6/libexec/src/runtime/proc.go:200
12  0x000000000405b6f1 in runtime.goexit
    at /usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:1337
````

**Comment by fjl** [comment]
I will try to reproduce your issue.

**Comment by ShaAliLiton** [comment]
Support me

**Comment by dimroc** [comment]
Hi there @fjl, has there been any update regarding this bug?

**Comment by dimroc** [comment]
@fjl just checking in to see if there's been any progress. Thanks!

**Comment by spooktheducks** [comment]
@fjl Wanted to check back with you to see if you were ever able to reproduce.

**Comment by adamschmideg** [comment]
I managed to reproduce it (for me it reproduces 1 out of 5 times)

**Comment by renaynay** [comment]
@dimroc @spooktheducks Are you still running into this issue with the current version (v1.9.16) of geth?

**Comment by s1na** [comment]
I confirmed that the issue existed in v1.8.27, but couldn't reproduce it on the most recent version v1.9.25 using your scripts. Please let me know if you're still facing this and I'll re-open.
