### ISSUE TITLE
ethereum hardware spec

### ISSUE THREAD

**Issue by YangDaeIl** [ethereum/go-ethereum#19778]
With vmware, can you tell me the minimum hardware specifications for ethereum deployment?
thank you.

**Comment by karalabe** [comment]
Unfortunately we cannot. We don't maintain hardware specs. Generally for a mainnet node you must have a fast SSD, 200GB space, and ideally 8+GB RAM. Network wise it helps to have a public IP address with port 30303 forwarded.
