### ISSUE TITLE
How pay gas price using ERC20 token 

### ISSUE THREAD

**Issue by AmrataRajput** [ethereum/go-ethereum#19789]
Hi,
please help me for this
 
I implement my private poa network using geth poa and deploy contract using truffle all i working fine.
now i need to send my erc20 token with the gas price but i do not have ether in my account and i want to use the erc20 to pay gas price is it is possible .

**Comment by karalabe** [comment]
Transaction fees can only be paid in Ether. Theoretically you could make a transaction that uses 0-gasprice and does an internal transfer of an ERC20 token to a miner, and have someone explicitly mine that, but the network does not propagate such transactions and default mining code does not check ERC20 stuff.

**Comment by AmrataRajput** [comment]
Thanks..
