### ISSUE TITLE
i am configure private block-chain  with the help of geth but after some time my eth.coinbase account update to zero 

### ISSUE THREAD

**Issue by AmrataRajput** [ethereum/go-ethereum#19781]
hi,

i am configure private block-chain  with the help of geth and i get initial balance of my miner account i.e. 904625697166532776746648320380374280103671755200316906509 .
but after 8-15 days my balance is update to Zero. Please provide any solution by my account balance is update to zero . 
![image](https://user-images.githubusercontent.com/47444071/60488581-f71bed80-9cbf-11e9-88b1-9298b023f1dc.png)

**Comment by karalabe** [comment]
My guess is that you exposed your node publicly to the internet, the RPC that is. There are bots scanning for Ethereum nodes and just sending any funds to themselves, irrelevant of network. Please never expose your node to the internet. Geth v1.9.0 explicitly forbids this btw.
