### ISSUE TITLE
How to run two validator on same rpc address for mining the transaction 

### ISSUE THREAD

**Issue by AmrataRajput** [ethereum/go-ethereum#19796]
Hi,
i create geth poa network for single validator i.e the eth coinbase account run the geth using nohup command and mine the transaction all is working fine.

but now i create the new signer(validator) using the clique.propose("0xaddress", true) and get the list of validator using the clique.getSigners().
but when i try to run my newly create validator with geth for mining the transaction i got the error 
data directory is already used by another process. because on this network directory my nohup geth is running. 
plz provide me solution how can i run my second validator node

**Comment by karalabe** [comment]
Each node needs its own data directory and database, as Geth assumes it has exclusive access to the data. If you want to run multiple Geth instances on the same machine, you'll need to set a different data directory (`--datadir`), ports (`--port`) and possibly anything else you rely on.

**Comment by AmrataRajput** [comment]
after creating the poa network using puppeth and geth.
now i create new sealer account by clique.
this propose account i create using personal create account which in present inside my geth running directory.
than how can i do mining with the new sealer account for conforming the transaction.
because the transaction goes into pending state if both the sealer is not mine the transaction
