### ISSUE TITLE
Building on windows, OpenCL disabled - can't get GPU mining working

### ISSUE THREAD

**Issue by timelf123** [ethereum/go-ethereum#1979]
```
c:\godev\src\github.com\ethereum\go-ethereum\cmd\geth>git checkout develop && godep go install
Already on 'develop'
Your branch is up-to-date with 'origin/develop'.

C:\godev>geth gpuinfo
OpenCL disabled. Set GO_OPENCL and re-build to enable.
```

I have the GO_OPENCL = true in my env variables

**Comment by fjl** [comment]
The `GO_OPENCL` environment variable is not honoured when building with `godep go install`.
Use `godep go install -tags opencl` instead.

**Comment by timelf123** [comment]
Thank you felix

**Comment by fjl** [comment]
These messages mean that the OpenCL SDK is not installed or can't be found.

**Comment by timelf123** [comment]
@fjl the Nvidia CUDA toolkit is installed in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5

What env variable needs to be set to get this working?

**Comment by fjl** [comment]
@Gustav-Simonsson does it even build with the CUDA SDK?
I'm not sure about it.

**Comment by Gustav-Simonsson** [comment]
@timelf123 Haven't tried building with CUDA - only with http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/

You can try compiling https://github.com/Gustav-Simonsson/go-opencl separately and make sure you have OpenCL headers in your paths. If that works, then go-ethereum should build.

**Comment by vindicatorr** [comment]
I'm under the impression that I should be seeing "clEnqueueFillBuffer" if I "nm" the library file, but I don't when viewing libmali.so (ARM T62x r6p0-02rel0).
Instead, the only Enqueue items are:
```
$ nm -D /usr/local/lib/libmali.so |grep Enqueu
001eadbc T clEnqueueAcquireEGLObjectsKHR
001eaa44 T clEnqueueAcquireGLObjects
001ea6f8 T clEnqueueBarrier
001e9578 T clEnqueueCopyBuffer
001e96d8 T clEnqueueCopyBufferRect
001e9d64 T clEnqueueCopyBufferToImage
001e99c4 T clEnqueueCopyImage
001e9bcc T clEnqueueCopyImageToBuffer
001e9ef0 T clEnqueueMapBuffer
001ea088 T clEnqueueMapImage
001ea684 T clEnqueueMarker
001ea330 T clEnqueueNDRangeKernel
001ea50c T clEnqueueNativeKernel
001e8f94 T clEnqueueReadBuffer
001e90b0 T clEnqueueReadBufferRect
001e990c T clEnqueueReadImage
001eaef0 T clEnqueueReleaseEGLObjectsKHR
001eab8c T clEnqueueReleaseGLObjects
001ea45c T clEnqueueTask
001ea278 T clEnqueueUnmapMemObject
001ea6ac T clEnqueueWaitForEvents
001e9284 T clEnqueueWriteBuffer
001e93a0 T clEnqueueWriteBufferRect
001e9968 T clEnqueueWriteImage
```
*libOpenCL.so links back to libmali
