### ISSUE TITLE
Rinkeby faucet is down

### ISSUE THREAD

**Issue by parastooveisi** [ethereum/go-ethereum#19804]
![Screenshot from 2019-07-08 11-07-20](https://user-images.githubusercontent.com/8753103/60829054-44410900-a171-11e9-8de9-9bc75c4bf3c7.png)

It seems faucet is down. I tried with Chrome and Firefox on both Ubuntu and Windows.

**Comment by karalabe** [comment]
Ah shiet, out of disk. Cleaned up, resyncing from zero. Should be back up in 10 mins. Thanks for the heads up!
