### ISSUE TITLE
rinkeby faucet seems to be down

### ISSUE THREAD

**Issue by romewillraiseagain** [ethereum/go-ethereum#19805]
Im sure this will be fixed soon, but incase it takes some unexpected extra time could i get 3eth on b0bc9ab83c56451d353736955f99bbcbf5cdaaa7 ?
Thanks!

![rinkeby](https://user-images.githubusercontent.com/52677733/60838942-a1ba7180-a1d4-11e9-8301-f194694f2153.PNG)

**Comment by karalabe** [comment]
It was fixed while you opened the issue :P
