### ISSUE TITLE
Rinkeby facuet 502 errors

### ISSUE THREAD

**Issue by wbt** [ethereum/go-ethereum#19803]
When trying to access https://faucet.rinkeby.io/ the page loads but there does not seem to be any connection to the blockchain:
![image](https://user-images.githubusercontent.com/563406/60824070-f7f8c780-a176-11e9-9786-10409c57f481.png)

Firefox reports the following:
>faucet.rinkeby.io:127:13: Firefox can’t establish a connection to the server at wss://faucet.rinkeby.io/api. 

Chrome reports the following, repeatedly:
>reconnect @ (index):127: WebSocket connection to 'wss://faucet.rinkeby.io/api' failed: Error during WebSocket handshake: Unexpected response code: 502

The last [transactions](https://rinkeby.etherscan.io/address/0x31b98d14007bdee637298086988a0bbd31184523) from the faucet look to have been about a day and a half ago.

**Comment by karalabe** [comment]
Ah shiet, out of disk. Cleaned up, resyncing from zero. Should be back up in 10 mins. Thanks for the heads up!

**Comment by wbt** [comment]
@llussy it appears fixed now!
