### ISSUE TITLE
LESv2 SendTx2 Fails If Node is Syncing

### ISSUE THREAD

**Issue by EBGToo** [ethereum/go-ethereum#19808]
If I submit a transaction to a node that is syncing, I'd expect that node to handle the submission (or if it can't to disconnect the peer, perhaps).  Instead I get what looks like a random error in the TxStatus result.

I submitted this:
```
ETH: LES: Send: [ LES,         SendTx2 ] 
ETH: SEND: L  2: [
ETH: SEND:   I  1: 0x23
ETH: SEND:   L  2: [
ETH: SEND:     I  1: 0x1e
ETH: SEND:     L  1: [
ETH: SEND:       L  9: [
ETH: SEND:         I  1: 0x13
ETH: SEND:         I  4: 0x3b9aca00
ETH: SEND:         I  2: 0x5208
ETH: SEND:         I 20: 0x04d542459de6765682d21771d1ba23dc30fb675f
ETH: SEND:         I  6: 0x6d23ad5f8000
ETH: SEND:         I  0: 0x
ETH: SEND:         I  1: 0x26
ETH: SEND:         I 32: 0x3149...
ETH: SEND:         I 32: 0x424a...
ETH: SEND:       ]
ETH: SEND:     ]
ETH: SEND:   ]
ETH: SEND: ]
```

and I got this:
```
ETH: RECV: L  3: [
ETH: RECV:   I  1: 0x1e
ETH: RECV:   I  4: 0x11e1a300
ETH: RECV:   L  1: [
ETH: RECV:     L  3: [
ETH: RECV:       I  0: 0x
ETH: RECV:       L  0: []
ETH: RECV:       I 23: 0x6578636565647320626c6f636b20676173206c696d6974
ETH: RECV:     ]
ETH: RECV:   ]
ETH: RECV: ]
ETH: LES: Recv: [ LES,        TxStatus ]
```

where the error string of `0x6578...` decodes to `"exceeds block gas limit"`.  Note the same transaction was submitted to multiple other nodes at the same time and the transaction succeeds (was eventually included in the blockchain).

The Ethereum node receiving this SendTx2 was version v1.8.23.

**Comment by rjl493456442** [comment]
In the latest branch, if the node is not synced it will reject all LES connections. Hopefully it can make more sense.

Regarding the `exceeds block gas limit` error. Are you sending a transaction with large gas usage?  Since the transaction exceeds the current block limit gas.

**Comment by EBGToo** [comment]
It was not a large gas usage transaction; just an ETH transfer ("0x5208" -> 22,000).  The same transaction was submitted to other fully synced nodes and was eventually included (https://etherscan.io/tx/0xc18c61933d99c006615f650564ee054f88cd1d8845479a428defdf8acc3a2f92).

In the latest branch, will current LES connections be *dropped* if a sync starts?

**Comment by rjl493456442** [comment]
I would say the LES connections will not be accepted before a node is synced.

**Comment by veox** [comment]
I've experienced the `exceeds block gas limit` error on submitting to syncing nodes for a long time (quite sure that for v1.8.23 it has been the case), LES or not.

I'd guess this has to do with the fact that, according to the remote server - especially if it's doing fast sync?.. - the block gas limit is very low: [5000 on Frontier](https://etherscan.io/block/1).

**Comment by EBGToo** [comment]
@rjl493456442 A conclusion being that since many/my Light Clients maintain an open connection to a LES node and since a LES node can start a sync at any time, the Light Client needs to handle a 'exceeds block gas limit' error by, probably, disconnecting and connecting to another LES node.  Reasonable?

That is, existing connections won't be dropped by a syncing LES node and on submit the LES node will not confirm/propagate the transaction?

A syncing LES node won't be sending 'announce' message to the connected Light Clients, will respond to PING with PONG and will handle other LES/v2 messages (eg, GetBlocks) properly?
