### ISSUE TITLE
Should faucet limit requests?

### ISSUE THREAD

**Issue by wbt** [ethereum/go-ethereum#19806]
Are there limits on requests via a faucet?
Per [previous proposal](https://github.com/ethereum/go-ethereum/pull/18105#), we apparently can't add a few minutes grace period that would allow for regular consistency within human error, on a basis (the connection still doesn't make sense to me) referring to bots.  

I recently observed the Rinkeby faucet awarding payouts to the same address several times in quick succession, which seemed a bit against the intended spirit:

![image](https://user-images.githubusercontent.com/563406/60841742-8b92be00-a1a0-11e9-8113-7d29de10f8d9.png)

Some copy and paste from the recent logs:
  | 0x508710f58b70ebbea0cfb1b27b59fd859e7be744 | 3 minutes ago
  | 0x508710f58b70ebbea0cfb1b27b59fd859e7be744 | 3 minutes ago
  | 0x508710f58b70ebbea0cfb1b27b59fd859e7be744 | 3 minutes ago
  | 0x508710f58b70ebbea0cfb1b27b59fd859e7be744 | 3 minutes ago
  | 0x4b6c775a9cb3200433420ffaec1e574553072508 | 3 minutes ago
  | 0x4b6c775a9cb3200433420ffaec1e574553072508 | 3 minutes ago
  | 0x4b6c775a9cb3200433420ffaec1e574553072508 | 3 minutes ago
  | 0x4b6c775a9cb3200433420ffaec1e574553072508 | 3 minutes ago
  | 0x4b6c775a9cb3200433420ffaec1e574553072508 | 2 minutes ago
  | 0x4b6c775a9cb3200433420ffaec1e574553072508 | 2 minutes ago
  | 0x4b6c775a9cb3200433420ffaec1e574553072508 | 2 minutes ago
  | 0x4b6c775a9cb3200433420ffaec1e574553072508 | 2 minutes ago
  | 0x4b6c775a9cb3200433420ffaec1e574553072508 | 2 minutes ago
  | 0x4b6c775a9cb3200433420ffaec1e574553072508 | 2 minutes ago
  | 0x4b6c775a9cb3200433420ffaec1e574553072508 | 2 minutes ago
  | 0x4b6c775a9cb3200433420ffaec1e574553072508 | 2 minutes ago
  | 0x4b6c775a9cb3200433420ffaec1e574553072508 | a minute ago
  | 0xdf57a505dba37f11460089f2b6bfcccc1b0f959e | a minute ago
  | 0xdf57a505dba37f11460089f2b6bfcccc1b0f959e | a minute ago
  | 0xdf57a505dba37f11460089f2b6bfcccc1b0f959e | a minute ago
  | 0xdf57a505dba37f11460089f2b6bfcccc1b0f959e | a minute ago
  | 0xdf57a505dba37f11460089f2b6bfcccc1b0f959e | a minute ago
  | 0xdf57a505dba37f11460089f2b6bfcccc1b0f959e | a few seconds ago
  | 0xdf57a505dba37f11460089f2b6bfcccc1b0f959e | a few seconds ago
  | 0xdf57a505dba37f11460089f2b6bfcccc1b0f959e | a few seconds ago
  | 0xdf57a505dba37f11460089f2b6bfcccc1b0f959e | a few seconds ago
  | 0xffaa853b505e372eb60eee017bd3497a8168799e | a few seconds ago
  | 0x87b3acf160cd6147193f9220a014611c9e8015e6 | a few seconds ago
  | 0x3f46d43bc11211f5fee72ed37cdf448b96fd590b | a few seconds ago
  | 0x3f46d43bc11211f5fee72ed37cdf448b96fd590b | a few seconds ago
  | 0x3f46d43bc11211f5fee72ed37cdf448b96fd590b | a few seconds ago
  | 0x3f46d43bc11211f5fee72ed37cdf448b96fd590b | a few seconds ago
  | 0x3f46d43bc11211f5fee72ed37cdf448b96fd590b | a few seconds ago
  | 0x3f46d43bc11211f5fee72ed37cdf448b96fd590b | a few seconds ago

I suspect the same human is behind all of these, except the two one-offs.

I checked 0x508710f58b70ebbea0cfb1b27b59fd859e7be744 which drew 67 times so far today.  3 days ago, the account drew 71 times and then [pulled out](https://rinkeby.etherscan.io/tx/0x9b63e2d15a06fbd6b395e1aef2948a4476cc787f4d7927377ab444edddd3149c) 2,701 ETH to [this account](https://rinkeby.etherscan.io/address/0xdf977109f7e37bd73bf9a8e4ca5ced1f61e04551), which seems to be collecting quite a bit from the others as well. It's amassed >20K ETH in under 10 days!  In doing so, it joins a [long list of accounts](https://rinkeby.etherscan.io/accounts) with balances just over 20K, including other targets where funds from this facuet-drawing account [have been sent](https://rinkeby.etherscan.io/txs?a=0x508710f58b70ebbea0cfb1b27b59fd859e7be744&f=2), directly or indirectly.

Is there a desire to limit faucet transactions by address and medium?  (E.g. for a given address, only one Twitter post and if desired, also one Facebook post, is honored before the "you must wait" note is triggered?)
If not, and simply having more posts with an address is a great way to circumvent rate-limiting, why be so [strict](https://github.com/ethereum/go-ethereum/pull/18105#) about the fractional milliseconds?  

Of course, even adding this limit wouldn't block whomever is doing this; they would just have to use a wider variety of ETH addresses in the faucet draw step before aggregation.  However, observing this behavior really seems to weaken the case for rejecting the other [PR](https://github.com/ethereum/go-ethereum/pull/18105#).

**Comment by karalabe** [comment]
There is already a rate limit. This person is actually using unique Twitter accounts for each request.

**Comment by wbt** [comment]
I meant per ETH account.

**Comment by ligi** [comment]
the problem is that this is just a "hot-fix" but not a real solution to the problem. The "attacker" could simply generate new accounts per attempt and funnel the ETH together to one account afterwards

**Comment by wbt** [comment]
So could we please at least [make the process a little easier](https://github.com/ethereum/go-ethereum/pull/18105#) for people who are not using that sort of workaround?

**Comment by karalabe** [comment]
Fair enough

**Comment by ligi** [comment]
closing as it would not really help to solve a problem. This does not affect the grace period though. This one seems to go in (bit modified form)
