### ISSUE TITLE
eth_getTransactionReceipt returns null for a long time

### ISSUE THREAD

**Issue by yqzzj** [ethereum/go-ethereum#19813]
The block is up to date, but in some blocks the transaction receipt always returns null, maybe 2 seconds, maybe 3 hours before the correct return.
I almost come across a block two or three days where all the transactions are like this.
geth-linux-amd64-1.8.27

curl -X POST --data '[{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x164484848a90083901e7692afc1d1640739883d26232b4bb9055d1cf462f3b76"],"id":0}]' -H 'Content-type: application/json' http://127.0.0.1:8545
[{"jsonrpc":"2.0","id":0,"result":null}]

**Comment by ayrat555** [comment]
I think we're experiencing the same issue

**Comment by wangsai-silence** [comment]
Try geth-1.9.0. I think this problem is resolved.

**Comment by vbaranov** [comment]
@wangsai-silence is any reference to 1.9.0 release notes where the fix for this problem is mentioned?

**Comment by yqzzj** [comment]
1.9.0 is definitely fixed.

**Comment by wangsai-silence** [comment]
> @wangsai-silence is any reference to 1.9.0 release notes where the fix for this problem is mentioned?

https://github.com/ethereum/go-ethereum/pull/18447

**Comment by vbaranov** [comment]
I updated Geth up to 1.9.0 and it still returns null receipt for the same transactions. Seems, we need to resync the node from scratch.

**Comment by wangsai-silence** [comment]
> I updated Geth up to 1.9.0 and it still returns null receipt for the same transactions. Seems, we need to resync the node from scratch.

Maybe you can check ```eth.syncing``` result first.

**Comment by vbaranov** [comment]
>Maybe you can check eth.syncing result first.

This is not our case: our node was fully synchronized archive node before the update to 1.9.0
And yes, it still fully synced
```
curl -H "Content-type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' http://xxx.xxx.xxx.xxx:8545
{"jsonrpc":"2.0","id":1,"result":false}
```

**Comment by vbaranov** [comment]
Yes, resync from the genesis block with `1.9.0` solved the problem. @yqzzj should we close this?
