### ISSUE TITLE
Start exporting RPC, ETH and LES serve statistics

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#19822]
We've no idea how many RPC, ETH or LES requests we serve, how much data, how much processing, etc. We have extensive stats on what we retrieve from others, but nothing on what others retrieve from us. Adding these to the metrics will enable us to correlate hiccups with their root causes.

**Comment by fjl** [comment]
Good solution for the RPC server would be a `metrics.Timer` per method.

**Comment by rjl493456442** [comment]
The generic metrics for RPC https://github.com/ethereum/go-ethereum/pull/20847

**Comment by karalabe** [comment]
We have generic metrics for P2P packets and RPC. We can add more later if need be.
