### ISSUE TITLE
[1.9] dumpconfig throwing error "nil *params.TrustedCheckpoint"

### ISSUE THREAD

**Issue by Eric-Showers** [ethereum/go-ethereum#19824]
#### System information

Geth version: `1.9.0-stable-52f24617`
OS & Version: Ubuntu 16.04

#### Expected behaviour
Print TOML configuration and exit

#### Actual behaviour
Output's the following and exits:
```
INFO [07-10|09:24:25.132] Maximum peer count                       ETH=50 LES=0 total=50
INFO [07-10|09:24:25.133] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
toml: cannot marshal nil *params.TrustedCheckpoint
```

#### Steps to reproduce the behaviour
Have reproduced this with several configs eg.
`geth --datadir /srv/geth-db/ --gcmode archive --syncmode full dumpconfig`

**Comment by Eric-Showers** [comment]
It appears similar to the bug fixed [here](https://github.com/ethereum/go-ethereum/pull/15962/commits/226aef18c888049b5e82e05f0c063c91cc3dfc45)

**Comment by rjl493456442** [comment]
Thanks for catching this! Please check the fix #19825

**Comment by AkashiHidaka** [comment]
Same occur of the error.
How to create config.toml?

**Comment by karalabe** [comment]
It's fixed on master, will be released in 1.9.1 early next week.

**Comment by onemedicine** [comment]
Maybe it's because of the mount, but he still appears
![image](https://user-images.githubusercontent.com/20993492/62591843-8641a400-b903-11e9-9e67-b43dddc865e0.png)
**System information：**
Geth version: v1.9.1-stable-b7b2f60f
OS & Version: CentOS Linux release 7.4.1708

**Comment by karalabe** [comment]
@onemedicine "no space left on device"
