### ISSUE TITLE
Release description v1.9.0: broken url

### ISSUE THREAD

**Issue by DaWe35** [ethereum/go-ethereum#19821]
Hey @karalabe!

There is a broken link in the [v1.9.0](https://github.com/ethereum/go-ethereum/releases/tag/v1.9.0) release description: 
`<a href="/ethereum/go-ethereum/blob/v1.9.0">Geth v1.9.0 - Six months distilled</a>`

I't funny, because when I opened it from the email, [this page](http://www.ethereum.com/go-ethereum/blob/v1.9.0) opened. From the github release page, of course it worked as a normal relative [link](https://github.com/ethereum/go-ethereum/blob/v1.9.0).

Thank you!

**Comment by karalabe** [comment]
Thanks for the heads up, you caught the small window when we pushed the github release, but not yet the blog, so didn't have the URL :). It was backfilled since then.
