### ISSUE TITLE
log: RotatingFileHandler race on counter.count can crash geth

### ISSUE THREAD

**Issue by tangy-ong** [ethereum/go-ethereum#19839]
#System information
Geth version: 1.9.0
OS & Version: Linux
Commit hash : n/a

Counter.Close() will cause a segmentation error when the limit is set to a small value and the log is printed concurrently.

When I add the lock, it will run normally.
```go
        h := StreamHandler(counter, formatter)
        mu := sync.Mutex{}
	return FuncHandler(func(r *Record) error {
		mu.Lock()
		defer mu.Unlock()
		if counter.count > limit {
			counter.Close()
			counter.w = nil
		}
```

**Comment by kurkomisi** [comment]
This issue is fixed here similarly, waiting for merge:
https://github.com/ethereum/go-ethereum/pull/17665

**Comment by fjl** [comment]
RotatingFileHandler was deleted in #20586.
