### ISSUE TITLE
1.9.0 dumpconfig  ERROR

### ISSUE THREAD

**Issue by xianxiongwang** [ethereum/go-ethereum#19848]
root@edz-MS-7996:/work/repos/geth1.9/geth-linux-amd64-1.9.0-52f24617# ./geth-linux-amd64-1.9.0-52f24617 dumpconfig --miner.etherbase=0x04668Ec2f57cC15c381b461B9fED2B5D451c3F6F  --extradata=pool_00003  --datadir=/work400g/ethereum/data/.ethereum --ethash.dagdir=/work400g/ethereum/data/.ethash  > main-1.9.0.toml
INFO [07-17|15:05:27.122] Bumping default cache on mainnet         provided=1024 updated=4096
WARN [07-17|15:05:27.122] Sanitizing cache to Go's GC limits       provided=4096 updated=1278
INFO [07-17|15:05:27.123] Maximum peer count                       ETH=50 LES=0 total=50
INFO [07-17|15:05:27.123] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
toml: cannot marshal nil *params.TrustedCheckpoint

**Comment by karalabe** [comment]
Thanks for the report. This was fixed in https://github.com/ethereum/go-ethereum/pull/19825, and it's on master. Will be released to stable next week.
