### ISSUE TITLE
How to enable and use the accounting module?

### ISSUE THREAD

**Issue by marknguyen85** [ethereum/go-ethereum#19840]
I found the accounting module in this line and want to use them. 
i attached the accounting module to parameter --rpcapi accounting when run console node but could not found this module.

run node: 
<pre>
./build/bin/geth --rpc --datadir ~/mychain/data/ --port 30303 --nodiscover --rpcapi db,eth,net,web3,personal,accounting --networkid 15 init ~/mychain/CustomGenesis.json
</pre>
get modules supported 
<pre>
rpc: {
    modules: {
      admin: "1.0",
      debug: "1.0",
      eth: "1.0",
      ethash: "1.0",
      miner: "1.0",
      net: "1.0",
      personal: "1.0",
      rpc: "1.0",
      txpool: "1.0",
      web3: "1.0"
    },
</pre>

How can be use this module?

https://github.com/ethereum/go-ethereum/blob/6bd896a97f0c86fdb6d0538f5f839d7ea104e888/internal/web3ext/web3ext.go#L722

Thanks for the support.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by marknguyen85** [comment]
ok thank you.
