### ISSUE TITLE
keystore:account_cache/ find(a accounts.Account) Ignore a situation

### ISSUE THREAD

**Issue by eilinge** [ethereum/go-ethereum#19847]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.8.16-stable`
OS & Version: `Windows/Linux/OSX`
Commit hash : `master`

#### Expected behaviour
When looking through a.Address, it does not take into []accounts.Account may store multiple accounts

#### Actual behaviour
```
switch len(matches) {
// TODO: len(ac.byAddr[a.Address]) > 1
case 1:
	return matches[0], nil
case 0:
	return accounts.Account{}, ErrNoMatch
default:
	err := &AmbiguousAddrError{Addr: a.Address, Matches: make([]accounts.Account, len(matches))}
	copy(err.Matches, matches)
	sort.Sort(accountsByURL(err.Matches))
	return accounts.Account{}, err
}
```

#### Backtrace

````
[backtrace]
````

**Comment by adamschmideg** [comment]
Can you write a sample code when it causes a problem?

**Comment by eilinge** [comment]
Considering the boundary condition of []accounts.Account storage, if the []accounts.Account stores multiple accounts at the same time, then len(matches) is greater than 1, you can also use, matches[0] to retrieve the searched account. However, you did not take this special case into account.

**Comment by karalabe** [comment]
I don't really get what the issue here is. If we have 0 matches, we return that the account cnanot be found. If there is 1, we return it. If the keystore stores multiple version of the same account, we tell the user that there's an ambiguity. All these cases seem handled by the code correctly.

I'm not sure what other case you are referring to?

**Comment by eilinge** [comment]
sorry , you are right
