### ISSUE TITLE
Blockchain rolls back after quit accidentally

### ISSUE THREAD

**Issue by Yiran-Chen** [ethereum/go-ethereum#19842]
#### System information

Geth version: 1.8.27
OS & Version: Linux

#### Issue
options
--gcmode full
--dev
The latest block 701 was mined, then my computer was out of battery and shutdown . When I restart, the latest block become 645 (eth.blockNumber is 645), I still can get block data of 646 - 701 (eth.getBlock(646) ... eth.getBlock(701) still return old data) but they are no longer a part of the chain, newly mined blocks will replace the old blocks and link to 645.
Is it because the gcmode is enabled and the data of 645 - 701 was not flushed to disk ?
Is there a way to "reset the head" to the old 701 , since old data was not lost ?

**Comment by rjl493456442** [comment]
For the default gcmode `full`, Geth will maintain all state data in the memory and flush them in a time interval.
Since your Geth node exited without flushing data, so it rewinds the head automatically.

**Comment by Yiran-Chen** [comment]
> For the default gcmode `full`, Geth will maintain all state data in the memory and flush them in a time interval.
> Since your Geth node exited without flushing data, so it rewinds the head automatically.

Yes, that's also my suspicion.  But block 645 was mined 15 days ago, so it does not flush in a time interval but in a blocks window I guess, and there is no management API to "reset the head" even data still exists.

**Comment by rjl493456442** [comment]
Geth will import all "missing" blocks even there are existent.

Btw we have a private RPC call `debug_setHead`. You can try this API without exposing the `debug` namespace or via `ipc`

**Comment by Yiran-Chen** [comment]
> Geth will import all "missing" blocks even there are existent.
> 
> Btw we have a private RPC call `debug_setHead`. You can try this API with exposing the `debug` namespace or via `ipc`
Just tried debug_setHead, unfortunately it can only set the head to a past block but not a "future" one (maybe because some blocks has been replaced ).

**Comment by Yiran-Chen** [comment]
> Geth will import all "missing" blocks even there are existent.
> 
> Btw we have a private RPC call `debug_setHead`. You can try this API with exposing the `debug` namespace or via `ipc`

I tried debug_setHead,  nothing happen if set head to a "future" block

**Comment by karalabe** [comment]
You can't set the head to a future block, only to past ones. If you don't shut Geth down gracefully, there's no way currently to recover the data from a local crashed database, only from a remote node. Generally this is fine, unless you have a single-node network. In that case, you're out of luck for now.

There is a possibility to re-execute local blocks without state after a crash, but that requires code in Geth that we don't currently have. Also, if you've mined blocks on top of the crashed and rewound database, it's very very messy to do any recovery, since that would entail extracting dangling data from the database by hash and reconstructing the chain outside of Geth and then reimporting it.

**Comment by Yiran-Chen** [comment]
> You can't set the head to a future block, only to past ones. If you don't shut Geth down gracefully, there's no way currently to recover the data from a local crashed database, only from a remote node. Generally this is fine, unless you have a single-node network. In that case, you're out of luck for now.
> 
> There is a possibility to re-execute local blocks without state after a crash, but that requires code in Geth that we don't currently have. Also, if you've mined blocks on top of the crashed and rewound database, it's very very messy to do any recovery, since that would entail extracting dangling data from the database by hash and reconstructing the chain outside of Geth and then reimporting it.

Thanks
