### ISSUE TITLE
What is this spike about?

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#19841]
<img width="676" alt="Screenshot 2019-07-16 at 10 38 46" src="https://user-images.githubusercontent.com/6915/61279266-12095a00-a7b6-11e9-8dd9-dff346cad239.png">

**Comment by karalabe** [comment]
Leveldb needs to compact the area where we deleted all the ancient stuff from. Until that happens, it will keep this spike. Also, v1.9.0 does not reencode old receipts to use the smaller format, so an updated database will always be larger than a fresh sync.

**Comment by fjl** [comment]
Looks like it is resolved.

**Comment by karalabe** [comment]
Is it https://etherscan.io/chartsync/chainarchive ?
