### ISSUE TITLE
Transaction executed but account balance is wrong

### ISSUE THREAD

**Issue by gtrandxiangyu** [ethereum/go-ethereum#19844]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.8.15`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
right transaction get right balance

#### Actual behaviour
transaction has been in block,but account balance are not right.
all the transactions in the block(25722581) get right, but all the account balance get wrong.

#### Backtrace
here is the block info
> eth.getBlock(25722581)
{
  difficulty: 2,
  extraData: "0xd88301080f846765746888676f312e31302e32856c696e7578000000000000008d292dd62507d7006f91003ba2358f2d44344d0190f6bacd741e5ff7734ff93a0b1e602a21d04d965603c934a311e82dd75262fb436c87e0d56efa99fa3a788701",
  gasLimit: 8000000,
  gasUsed: 522501,
  hash: "0x36f8b72b3bd7dd168927d07b17a0e8315d47fe49aa0b178d991622df418f7af3",
  logsBloom: "0x00000040040000000000000000000000000000000000000000080000000000000000000000001000000000001000000000000200000000000000000000000004000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080040000000020080000000000000000000000000000000000000004000000000000008000200000000000000000000000000000000000001000000000000000000020000000000000200000000000000000008000008000000080000102000000000000000000000000000000000000000000000000000000000000000000000200000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 25722581,
  parentHash: "0x8323a2ee7696614844985733de61b25ae8bf8adaac2697a850ad4eb13897ef71",
  receiptsRoot: "0x8860b41337ba620e71e02ea0c13cf2e78898755ee80228eed2e1ba637f73316d",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 4531,
  stateRoot: "0x5b631556cc6cd230b8975e78a0c9adb2696e469c094e79973fb2e50176f6ccd6",
  timestamp: 1563253484,
  totalDifficulty: 51371915,
  transactions: ["0x12ffbe3e22ef081dd581800540def173e52a40544944db107e0d05a649b3d775", "0xbbd005883fc7bfd7b6f393f664d31b06c53770b5f08b40f61b69690444691f8c", "0x840ae38b78112813a577be8f84f5d11b5a470ef2f27d8a7e264a6f279d075197", "0xb0296f095660195aa9c0f8e94fd65ecdff58e7b90e490e8bb72e9a3dc0dcb801", "0xd18d95bee9a119e7c839b98f67b51a56d394b2825176649765a32e200fd164ff", "0x128755ce7a413cb8117ada6e31ad7d348d97278a666a788f5a50aaea332549bb", "0x68d3779d8643505edeffd67b5be9254b70e085da625430ed465a88b7e0a8bcc8", "0x6abb030173deb3650a6ac8d4d119d052f5720f3b3aa20bc3cdcb285eb88cfb5d", "0x240a969d67936199b02b5db80f66074e67bb42f6203732a49d25c732a2624d72", "0x1bab39329a9aa63bb1030b2d657c798770bb05b4fb4446e741a796d996b23771", "0x0a2c6f23e454beeab832305ccfd8e38872b7d9b6a8cfc70b7f024c49f2710c44", "0x4a3d41b0055bd70079e1638a92d13b9a1b2d212b5114e3b548cd8e0a46e57607", "0xf10ab53daf342d668b7cdf6c809770432c4d2fb83b1045362ea42c9df09267fd", "0x8ab1b5f0b5696eecaf1a5e4b231390d64aad47559b8c89c46a0cfccbad46b116", "0x389318dffc0d77ec970dc1b26a9dc64c6c43acb7e79c8044667976cf1cf30f2b", "0x9eff154bc3d728385d1905823a31ee74f74b83a2f019b94b617f0425789e06c0", "0x32cca7e828381d19b48379a66a0ff675b629f706a8a805abca53ba4da91e6103", "0xcfb5926080ff59a8b7c9e750e2f21bded507c97d1db43271f6f22cf28bd7200a", "0x68fe0a7af13ed70aff47bbe5bf8da3a6ec691cbe6df7cb4900658fd28d89ec67", "0x5937875b0091a7d3f0a6db28832995957bce27f481daf58301efe2520f61bd51", "0xb7ac7b52df929e1e306d8cfecc8745d140d1f08243e291a30232d7180c5c293c"],
  transactionsRoot: "0xc97ae2e49a8d0b117bdc632a63646353b8675e91cf53607e619db58ee646cf5b",
  uncles: []
}

lets get one transaction's account ,ex: 0x128755ce7a413cb8117ada6e31ad7d348d97278a666a788f5a50aaea332549bb
and we got from account is 0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe
> eth.getTransaction('0x128755ce7a413cb8117ada6e31ad7d348d97278a666a788f5a50aaea332549bb')
{
  blockHash: "0x36f8b72b3bd7dd168927d07b17a0e8315d47fe49aa0b178d991622df418f7af3",
  blockNumber: 25722581,
  from: "0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe",
  gas: 4300000,
  gasPrice: 3000,
  hash: "0x128755ce7a413cb8117ada6e31ad7d348d97278a666a788f5a50aaea332549bb",
  input: "0x9a6d3aaa00000000000000000000000000000000000000000000000002a58f3ae4e460470000000000000000000000000000000000000000000000000000000000000001",
  nonce: 4,
  r: "0xa35b0b4d3d2d3c3de8e1dcf1f5650134471089961f14c070378267e0dc3cbf82",
  s: "0x395554fc9305bdba1c5b159e3e06bcad3d1ed4a90504b31268551fbe5b73bc29",
  to: "0xe0676e50ead1337b428e0166c5e1ce1515a70b07",
  transactionIndex: 5,
  v: "0x1b",
  value: 100000000000000000000
}

then we got all tractions in 0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe

trasaction-hash	block#	from to 	trasaction-time	transaction-money
0x9c91a32145a8274eccd7b2eda89c0ba745794bc9b605030eb7317acba8d92f62	
25736820
0x22d7c2029f8624495f0fba0dee945417a6f2dbf9		0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe	2019-07-16 17:03:13	100GFC

0x128755ce7a413cb8117ada6e31ad7d348d97278a666a788f5a50aaea332549bb	
25722581
0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe		0xe0676e50ead1337b428e0166c5e1ce1515a70b07	2019-07-16 13:04:44	100GFC

0x3b9eb3b7d36b6e42ebb8e1bfb858f29349a543471ed2a547d5ae5b34baa3ae88	
24585722
0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe		0xe0676e50ead1337b428e0166c5e1ce1515a70b07	2019-07-01 21:54:55	100GFC

0x457f15b33add58caa472025c825c5e640f93140dded4548f282125790745544b	
22955832
0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe		0xe0676e50ead1337b428e0166c5e1ce1515a70b07	2019-06-13 01:01:10	100GFC

0xe8af29f9ad10be042bc39d73b2b49885d3bf805e5589d9f0654b84c60c351530	
21797898
0x6ac7885474e99df8fd6826bbcd6733119527edc1		0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe	2019-05-30 15:15:19	119.2614GFC

0x493c2e57b6013720f7adcbec6c7fd185f768b4ef87d1b54139b480787383c7f7	
21715048
0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe		0xe0676e50ead1337b428e0166c5e1ce1515a70b07	2019-05-29 16:13:42	100GFC

0x0d00fdd12e6e21ca23815882f3a1d860ba873ce9887f2b32ffb5adf88d24faa7	
21193341
0x5d32393a8a62884a1c5552c861834647f95dfbfe		0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe	2019-05-23 15:15:14	61.618GFC

0x81d26766afad37f09f388c2d904884529025484cabbf607a59148bb516136bd5	
21142371
0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe		0xe0676e50ead1337b428e0166c5e1ce1515a70b07	2019-05-23 01:05:18	50GFC

0x9475ba9645fbba9c5e05d48aab3af8664c412f737bebf72458efa665bfed83c5	
21142128
0x83caffdcda1bfdf95f0264ca8999d680abcc47de		0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe	2019-05-23 01:01:15	492.9879GFC

we got 9 transactions with account 0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe and 
0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe balance must be 323eth but we got 423eth in balace

> eth.getBalance('0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe')
423867299999487990000

Why eth has wrong balance? How to fix it?

**Comment by gtrandxiangyu** [comment]
Plus, We have four clique auth node and set 1 second get one block.

**Comment by ligi** [comment]
what I guess is happening here: the node you are querying is still not synced to the block where the transactions are happened that make the balance that you expect.
Please check if the node is synced to the block where the transaction happened. If this is the case please let us know.
On a side-note: interesting move to thumbs up your own post ..-)

**Comment by rjl493456442** [comment]
Do you also count the gas used by sending transaction?

**Comment by gtrandxiangyu** [comment]
> what I guess is happening here: the node you are querying is still not synced to the block where the transactions are happened that make the balance that you expect.
> Please check if the node is synced to the block where the transaction happened. If this is the case please let us know.
> On a side-note: interesting move to thumbs up your own post ..-)

Yes, The block has sync to others.
We have 4 auth node to seal blocks and all nodes has synced the block.

node1:
> eth.getBlock(25722581)
{
  difficulty: 2,
  extraData: "0xd88301080f846765746888676f312e31302e32856c696e7578000000000000008d292dd62507d7006f91003ba2358f2d44344d0190f6bacd741e5ff7734ff93a0b1e602a21d04d965603c934a311e82dd75262fb436c87e0d56efa99fa3a788701",
  gasLimit: 8000000,
  gasUsed: 522501,
  hash: "0x36f8b72b3bd7dd168927d07b17a0e8315d47fe49aa0b178d991622df418f7af3",
  logsBloom: "0x00000040040000000000000000000000000000000000000000080000000000000000000000001000000000001000000000000200000000000000000000000004000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080040000000020080000000000000000000000000000000000000004000000000000008000200000000000000000000000000000000000001000000000000000000020000000000000200000000000000000008000008000000080000102000000000000000000000000000000000000000000000000000000000000000000000200000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 25722581,
  parentHash: "0x8323a2ee7696614844985733de61b25ae8bf8adaac2697a850ad4eb13897ef71",
  receiptsRoot: "0x8860b41337ba620e71e02ea0c13cf2e78898755ee80228eed2e1ba637f73316d",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 4531,
  stateRoot: "0x5b631556cc6cd230b8975e78a0c9adb2696e469c094e79973fb2e50176f6ccd6",
  timestamp: 1563253484,
  totalDifficulty: 51371915,
  transactions: ["0x12ffbe3e22ef081dd581800540def173e52a40544944db107e0d05a649b3d775", "0xbbd005883fc7bfd7b6f393f664d31b06c53770b5f08b40f61b69690444691f8c", "0x840ae38b78112813a577be8f84f5d11b5a470ef2f27d8a7e264a6f279d075197", "0xb0296f095660195aa9c0f8e94fd65ecdff58e7b90e490e8bb72e9a3dc0dcb801", "0xd18d95bee9a119e7c839b98f67b51a56d394b2825176649765a32e200fd164ff", "0x128755ce7a413cb8117ada6e31ad7d348d97278a666a788f5a50aaea332549bb", "0x68d3779d8643505edeffd67b5be9254b70e085da625430ed465a88b7e0a8bcc8", "0x6abb030173deb3650a6ac8d4d119d052f5720f3b3aa20bc3cdcb285eb88cfb5d", "0x240a969d67936199b02b5db80f66074e67bb42f6203732a49d25c732a2624d72", "0x1bab39329a9aa63bb1030b2d657c798770bb05b4fb4446e741a796d996b23771", "0x0a2c6f23e454beeab832305ccfd8e38872b7d9b6a8cfc70b7f024c49f2710c44", "0x4a3d41b0055bd70079e1638a92d13b9a1b2d212b5114e3b548cd8e0a46e57607", "0xf10ab53daf342d668b7cdf6c809770432c4d2fb83b1045362ea42c9df09267fd", "0x8ab1b5f0b5696eecaf1a5e4b231390d64aad47559b8c89c46a0cfccbad46b116", "0x389318dffc0d77ec970dc1b26a9dc64c6c43acb7e79c8044667976cf1cf30f2b", "0x9eff154bc3d728385d1905823a31ee74f74b83a2f019b94b617f0425789e06c0", "0x32cca7e828381d19b48379a66a0ff675b629f706a8a805abca53ba4da91e6103", "0xcfb5926080ff59a8b7c9e750e2f21bded507c97d1db43271f6f22cf28bd7200a", "0x68fe0a7af13ed70aff47bbe5bf8da3a6ec691cbe6df7cb4900658fd28d89ec67", "0x5937875b0091a7d3f0a6db28832995957bce27f481daf58301efe2520f61bd51", "0xb7ac7b52df929e1e306d8cfecc8745d140d1f08243e291a30232d7180c5c293c"],
  transactionsRoot: "0xc97ae2e49a8d0b117bdc632a63646353b8675e91cf53607e619db58ee646cf5b",
  uncles: []
}

node2:
> eth.getBlock(25722581)
{
  difficulty: 2,
  extraData: "0xd88301080f846765746888676f312e31302e32856c696e7578000000000000008d292dd62507d7006f91003ba2358f2d44344d0190f6bacd741e5ff7734ff93a0b1e602a21d04d965603c934a311e82dd75262fb436c87e0d56efa99fa3a788701",
  gasLimit: 8000000,
  gasUsed: 522501,
  hash: "0x36f8b72b3bd7dd168927d07b17a0e8315d47fe49aa0b178d991622df418f7af3",
  logsBloom: "0x00000040040000000000000000000000000000000000000000080000000000000000000000001000000000001000000000000200000000000000000000000004000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080040000000020080000000000000000000000000000000000000004000000000000008000200000000000000000000000000000000000001000000000000000000020000000000000200000000000000000008000008000000080000102000000000000000000000000000000000000000000000000000000000000000000000200000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 25722581,
  parentHash: "0x8323a2ee7696614844985733de61b25ae8bf8adaac2697a850ad4eb13897ef71",
  receiptsRoot: "0x8860b41337ba620e71e02ea0c13cf2e78898755ee80228eed2e1ba637f73316d",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 4531,
  stateRoot: "0x5b631556cc6cd230b8975e78a0c9adb2696e469c094e79973fb2e50176f6ccd6",
  timestamp: 1563253484,
  totalDifficulty: 51371915,
  transactions: ["0x12ffbe3e22ef081dd581800540def173e52a40544944db107e0d05a649b3d775", "0xbbd005883fc7bfd7b6f393f664d31b06c53770b5f08b40f61b69690444691f8c", "0x840ae38b78112813a577be8f84f5d11b5a470ef2f27d8a7e264a6f279d075197", "0xb0296f095660195aa9c0f8e94fd65ecdff58e7b90e490e8bb72e9a3dc0dcb801", "0xd18d95bee9a119e7c839b98f67b51a56d394b2825176649765a32e200fd164ff", "0x128755ce7a413cb8117ada6e31ad7d348d97278a666a788f5a50aaea332549bb", "0x68d3779d8643505edeffd67b5be9254b70e085da625430ed465a88b7e0a8bcc8", "0x6abb030173deb3650a6ac8d4d119d052f5720f3b3aa20bc3cdcb285eb88cfb5d", "0x240a969d67936199b02b5db80f66074e67bb42f6203732a49d25c732a2624d72", "0x1bab39329a9aa63bb1030b2d657c798770bb05b4fb4446e741a796d996b23771", "0x0a2c6f23e454beeab832305ccfd8e38872b7d9b6a8cfc70b7f024c49f2710c44", "0x4a3d41b0055bd70079e1638a92d13b9a1b2d212b5114e3b548cd8e0a46e57607", "0xf10ab53daf342d668b7cdf6c809770432c4d2fb83b1045362ea42c9df09267fd", "0x8ab1b5f0b5696eecaf1a5e4b231390d64aad47559b8c89c46a0cfccbad46b116", "0x389318dffc0d77ec970dc1b26a9dc64c6c43acb7e79c8044667976cf1cf30f2b", "0x9eff154bc3d728385d1905823a31ee74f74b83a2f019b94b617f0425789e06c0", "0x32cca7e828381d19b48379a66a0ff675b629f706a8a805abca53ba4da91e6103", "0xcfb5926080ff59a8b7c9e750e2f21bded507c97d1db43271f6f22cf28bd7200a", "0x68fe0a7af13ed70aff47bbe5bf8da3a6ec691cbe6df7cb4900658fd28d89ec67", "0x5937875b0091a7d3f0a6db28832995957bce27f481daf58301efe2520f61bd51", "0xb7ac7b52df929e1e306d8cfecc8745d140d1f08243e291a30232d7180c5c293c"],
  transactionsRoot: "0xc97ae2e49a8d0b117bdc632a63646353b8675e91cf53607e619db58ee646cf5b",
  uncles: []
}

node3:> eth.getBlock(25722581)
{
  difficulty: 2,
  extraData: "0xd88301080f846765746888676f312e31302e32856c696e7578000000000000008d292dd62507d7006f91003ba2358f2d44344d0190f6bacd741e5ff7734ff93a0b1e602a21d04d965603c934a311e82dd75262fb436c87e0d56efa99fa3a788701",
  gasLimit: 8000000,
  gasUsed: 522501,
  hash: "0x36f8b72b3bd7dd168927d07b17a0e8315d47fe49aa0b178d991622df418f7af3",
  logsBloom: "0x00000040040000000000000000000000000000000000000000080000000000000000000000001000000000001000000000000200000000000000000000000004000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080040000000020080000000000000000000000000000000000000004000000000000008000200000000000000000000000000000000000001000000000000000000020000000000000200000000000000000008000008000000080000102000000000000000000000000000000000000000000000000000000000000000000000200000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 25722581,
  parentHash: "0x8323a2ee7696614844985733de61b25ae8bf8adaac2697a850ad4eb13897ef71",
  receiptsRoot: "0x8860b41337ba620e71e02ea0c13cf2e78898755ee80228eed2e1ba637f73316d",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 4531,
  stateRoot: "0x5b631556cc6cd230b8975e78a0c9adb2696e469c094e79973fb2e50176f6ccd6",
  timestamp: 1563253484,
  totalDifficulty: 51371915,
  transactions: ["0x12ffbe3e22ef081dd581800540def173e52a40544944db107e0d05a649b3d775", "0xbbd005883fc7bfd7b6f393f664d31b06c53770b5f08b40f61b69690444691f8c", "0x840ae38b78112813a577be8f84f5d11b5a470ef2f27d8a7e264a6f279d075197", "0xb0296f095660195aa9c0f8e94fd65ecdff58e7b90e490e8bb72e9a3dc0dcb801", "0xd18d95bee9a119e7c839b98f67b51a56d394b2825176649765a32e200fd164ff", "0x128755ce7a413cb8117ada6e31ad7d348d97278a666a788f5a50aaea332549bb", "0x68d3779d8643505edeffd67b5be9254b70e085da625430ed465a88b7e0a8bcc8", "0x6abb030173deb3650a6ac8d4d119d052f5720f3b3aa20bc3cdcb285eb88cfb5d", "0x240a969d67936199b02b5db80f66074e67bb42f6203732a49d25c732a2624d72", "0x1bab39329a9aa63bb1030b2d657c798770bb05b4fb4446e741a796d996b23771", "0x0a2c6f23e454beeab832305ccfd8e38872b7d9b6a8cfc70b7f024c49f2710c44", "0x4a3d41b0055bd70079e1638a92d13b9a1b2d212b5114e3b548cd8e0a46e57607", "0xf10ab53daf342d668b7cdf6c809770432c4d2fb83b1045362ea42c9df09267fd", "0x8ab1b5f0b5696eecaf1a5e4b231390d64aad47559b8c89c46a0cfccbad46b116", "0x389318dffc0d77ec970dc1b26a9dc64c6c43acb7e79c8044667976cf1cf30f2b", "0x9eff154bc3d728385d1905823a31ee74f74b83a2f019b94b617f0425789e06c0", "0x32cca7e828381d19b48379a66a0ff675b629f706a8a805abca53ba4da91e6103", "0xcfb5926080ff59a8b7c9e750e2f21bded507c97d1db43271f6f22cf28bd7200a", "0x68fe0a7af13ed70aff47bbe5bf8da3a6ec691cbe6df7cb4900658fd28d89ec67", "0x5937875b0091a7d3f0a6db28832995957bce27f481daf58301efe2520f61bd51", "0xb7ac7b52df929e1e306d8cfecc8745d140d1f08243e291a30232d7180c5c293c"],
  transactionsRoot: "0xc97ae2e49a8d0b117bdc632a63646353b8675e91cf53607e619db58ee646cf5b",
  uncles: []
}

node4:
> eth.getBlock(25722581)
{
  difficulty: 2,
  extraData: "0xd88301080f846765746888676f312e31302e32856c696e7578000000000000008d292dd62507d7006f91003ba2358f2d44344d0190f6bacd741e5ff7734ff93a0b1e602a21d04d965603c934a311e82dd75262fb436c87e0d56efa99fa3a788701",
  gasLimit: 8000000,
  gasUsed: 522501,
  hash: "0x36f8b72b3bd7dd168927d07b17a0e8315d47fe49aa0b178d991622df418f7af3",
  logsBloom: "0x00000040040000000000000000000000000000000000000000080000000000000000000000001000000000001000000000000200000000000000000000000004000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080040000000020080000000000000000000000000000000000000004000000000000008000200000000000000000000000000000000000001000000000000000000020000000000000200000000000000000008000008000000080000102000000000000000000000000000000000000000000000000000000000000000000000200000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 25722581,
  parentHash: "0x8323a2ee7696614844985733de61b25ae8bf8adaac2697a850ad4eb13897ef71",
  receiptsRoot: "0x8860b41337ba620e71e02ea0c13cf2e78898755ee80228eed2e1ba637f73316d",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 4531,
  stateRoot: "0x5b631556cc6cd230b8975e78a0c9adb2696e469c094e79973fb2e50176f6ccd6",
  timestamp: 1563253484,
  totalDifficulty: 51371915,
  transactions: ["0x12ffbe3e22ef081dd581800540def173e52a40544944db107e0d05a649b3d775", "0xbbd005883fc7bfd7b6f393f664d31b06c53770b5f08b40f61b69690444691f8c", "0x840ae38b78112813a577be8f84f5d11b5a470ef2f27d8a7e264a6f279d075197", "0xb0296f095660195aa9c0f8e94fd65ecdff58e7b90e490e8bb72e9a3dc0dcb801", "0xd18d95bee9a119e7c839b98f67b51a56d394b2825176649765a32e200fd164ff", "0x128755ce7a413cb8117ada6e31ad7d348d97278a666a788f5a50aaea332549bb", "0x68d3779d8643505edeffd67b5be9254b70e085da625430ed465a88b7e0a8bcc8", "0x6abb030173deb3650a6ac8d4d119d052f5720f3b3aa20bc3cdcb285eb88cfb5d", "0x240a969d67936199b02b5db80f66074e67bb42f6203732a49d25c732a2624d72", "0x1bab39329a9aa63bb1030b2d657c798770bb05b4fb4446e741a796d996b23771", "0x0a2c6f23e454beeab832305ccfd8e38872b7d9b6a8cfc70b7f024c49f2710c44", "0x4a3d41b0055bd70079e1638a92d13b9a1b2d212b5114e3b548cd8e0a46e57607", "0xf10ab53daf342d668b7cdf6c809770432c4d2fb83b1045362ea42c9df09267fd", "0x8ab1b5f0b5696eecaf1a5e4b231390d64aad47559b8c89c46a0cfccbad46b116", "0x389318dffc0d77ec970dc1b26a9dc64c6c43acb7e79c8044667976cf1cf30f2b", "0x9eff154bc3d728385d1905823a31ee74f74b83a2f019b94b617f0425789e06c0", "0x32cca7e828381d19b48379a66a0ff675b629f706a8a805abca53ba4da91e6103", "0xcfb5926080ff59a8b7c9e750e2f21bded507c97d1db43271f6f22cf28bd7200a", "0x68fe0a7af13ed70aff47bbe5bf8da3a6ec691cbe6df7cb4900658fd28d89ec67", "0x5937875b0091a7d3f0a6db28832995957bce27f481daf58301efe2520f61bd51", "0xb7ac7b52df929e1e306d8cfecc8745d140d1f08243e291a30232d7180c5c293c"],
  transactionsRoot: "0xc97ae2e49a8d0b117bdc632a63646353b8675e91cf53607e619db58ee646cf5b",
  uncles: []
}

**Comment by gtrandxiangyu** [comment]
> Do you also count the gas used by sending transaction?

All the transactions gas is set to  4300000 and gas gasPrice: 3000 when signed transaction.

**Comment by gtrandxiangyu** [comment]
Sorry all,

I got the problem. The transactions status is 0 all.

 eth.getTransactionReceipt('0x128755ce7a413cb8117ada6e31ad7d348d97278a666a788f5a50aaea332549bb')
{
  blockHash: "0x36f8b72b3bd7dd168927d07b17a0e8315d47fe49aa0b178d991622df418f7af3",
  blockNumber: 25722581,
  contractAddress: null,
  cumulativeGasUsed: 176684,
  from: "0x44d9a510060f48a180c31e9d7d34bbf21afa1dfe",
  gasUsed: 23097,
  logs: [],
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  status: "0x0",
  to: "0xe0676e50ead1337b428e0166c5e1ce1515a70b07",
  transactionHash: "0x128755ce7a413cb8117ada6e31ad7d348d97278a666a788f5a50aaea332549bb",
  transactionIndex: 5
}

But I also have the question.
If the status is 0 means the transaction is not execute by EVM and why have this case?

**Comment by rjl493456442** [comment]
`Status == 0x0` means the transaction execution is failed.

**Comment by gtrandxiangyu** [comment]
> `Status == 0x0` means the transaction execution is failed.

Do you know how the transaction is failed and how to find the error?
Because other block transactions can be execute right and status is 0.

**Comment by rjl493456442** [comment]
Please check the JSON RPC wiki for more information https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt
