### ISSUE TITLE
Geth attach should not sanitize cache settings

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#19858]
When doing `geth attach`, a log message appears that sanitizes `--cache`: `INFO [07-18|13:10:02.234] Bumping default cache on mainnet         provided=1024 updated=4096`. Is is lame, because `attach` does not use "any" memory. Would be nice to detect and skip displaying in this case.

**Comment by fjl** [comment]
This happens because the cache flags are handled in the `app.Before` hook. They should be handled in the node setup code instead.
