### ISSUE TITLE
1.9.0 fails to sync Rinkeby

### ISSUE THREAD

**Issue by jakubgs** [ethereum/go-ethereum#19859]
#### System information

Geth version: `1.9.0-stable-52f24617`
OS & Version: `Ubuntu 18.04.2 LTS`

#### Expected behaviour

A miner syncs and starts mining.

#### Actual behaviour

The node syncs some blocks, then drops to `0` or almost `0` and starts again after logging this:
```
Truncating freezer table     database=/data/geth/chaindata/ancient table=bodies items=315496 limit=55
Truncating freezer table     database=/data/geth/chaindata/ancient table=receipts items=315496 limit=55
Truncating freezer table     database=/data/geth/chaindata/ancient table=diffs    items=315496 limit=55
Truncating freezer table     database=/data/geth/chaindata/ancient table=headers  items=315496 limit=55
Truncating freezer table     database=/data/geth/chaindata/ancient table=hashes   items=315496 limit=55
```
This seems to be the source:
https://github.com/ethereum/go-ethereum/blob/3d3e83ecff5e830f6256b20d81f304febc39aeb2/core/rawdb/freezer_table.go#L339-L343
But no idea what that means.

#### Steps to reproduce the behaviour

Here are the flags I use for the `ethereum/client-go:v1.9.0` docker image:
```
admin@miner-01.gc-us-central1-a.faucet.rinkeby:~ % d inspect geth-miner | jq '.[].Config.Cmd'
[
  "--rinkeby",
  "--v5disc",
  "--syncmode=full",
  "--lightserv=90",
  "--mine",
  "--miner.threads=2",
  "--miner.etherbase=0xMY_ETHER_BASE",
  "--metrics",
  "--extradata=miner-01.gc-us-central1-a.faucet.rinkeby",
  "--verbosity=3",
  "--cache=5604",
  "--maxpeers=50",
  "--maxpendpeers=30",
  "--port=30303",
  "--nat=extip:1.2.3.4",
  "--unlock=0xSUPER_SECRET",
  "--allow-insecure-unlock",
  "--datadir=/data",
  "--password=/keys/account.pass",
  "--keystore=/keys",
  "--rpc",
  "--rpcaddr=0.0.0.0",
  "--rpcport=8545",
  "--rpcvhosts=localhost,miner,miner-01.gc-us-central1-a.faucet.rinkeby,miner-01.gc-us-central1-a.faucet.rinkeby.tinc",
  "--rpcapi=eth,net,web3,personal,shh,admin",
  "--ipcpath=/data/geth.ipc"
]
```

#### Context

I've been graphing the progress based on the `eth_syncing` RPC call and it looks like this:
![190_rinkeby_sync_fail](https://user-images.githubusercontent.com/2212681/61464299-0c417f00-a944-11e9-8ef2-9bc9c5070cfe.png)

Sometimes it also jut gets stuck somewhere in the low 100k's and stays there forever.

**Comment by karalabe** [comment]
Could you provide more logs? All that you have? This seems really weird.

Btw, you won't be able to mine on Rinkeby, it's a PoA (Clique) network where only authorized signers can seal blocks.

**Comment by jakubgs** [comment]
Sure, here's an hour-slice of logs.
https://gist.github.com/jakubgs/a5e19cca64e836cab0f000ca50e313cc
I'll get your `TRACE` logs in a minute.

**Comment by jakubgs** [comment]
Here's a ~22 minute slice of `DEBUG` logs from start with cleaned `geth` direcotry, til a bit after the time when the `Truncating freezer table` show up in the logs and the sync level drops: [geth.log.tar.gz](https://github.com/ethereum/go-ethereum/files/3408360/geth.log.tar.gz)

**Comment by karalabe** [comment]
In your first dump, there's something very odd:

```
INFO [07-18|19:52:59.442] Imported new chain segment               blocks=82    txs=148   mgas=534.603  elapsed=8.000s    mgasps=66.825  number=405413 hash=da5158…a65b6d age=2y1mo6d  dirty=109.26MiB

WARN [07-18|19:53:05.249] Sanitizing cache to Go's GC limits       provided=5604 updated=2491
```

I.e. Here Geth was murdered and restarted. Could you check why docker would be terminating the container forcefully? Geth didn't log any error, any warning, any clean shutdown. It looks as if it was just silently murdered.

**Comment by jakubgs** [comment]
So I disabled the `--restart-policy=always` from my docker container and tried again.
Here is what I got:
```json
{
  "Status": "exited",
  "Running": false,
  "Paused": false,
  "Restarting": false,
  "OOMKilled": true,
  "Dead": false,
  "Pid": 0,
  "ExitCode": 137,
  "Error": "",
  "StartedAt": "2019-07-19T14:04:59.188477944Z",
  "FinishedAt": "2019-07-19T14:15:35.214579829Z"
}
```
The `OOMKilled` being set to `true` indicates that the container was killed due to lack of memory.
It must be my docker memory limit:
```bash
 $ docker inspect geth-miner | jq '.[].HostConfig.Memory'
5485101056
```
So about `5485 MB` of limit, which is actually lower than my setting of `--cache` of `5604 MB`
Memory graph from last sync attempt:
![geth_miner_memory](https://user-images.githubusercontent.com/2212681/61542285-33b14e00-aa0f-11e9-94b8-c4c0e40c12f0.png)
![geth_miner_memory_cont](https://user-images.githubusercontent.com/2212681/61542438-9276c780-aa0f-11e9-9f8e-bf8bdf7c73e9.png)

And the container itself reached 3.958 GB of memory, so it didn't seem to me like it should be killed, but apparently it was.

It seems to me the issue is `--cache` setting being high than my docker container memory limit.
I will try to change that and get back to you.

**Comment by jakubgs** [comment]
Yep, it seems to be syncing now beyond the previous limit:
![geth_syncing_progress](https://user-images.githubusercontent.com/2212681/61544379-53e30c00-aa13-11e9-833d-02ee7617ca81.png)

Added a memory check so this doesn't happen in my role again: https://github.com/status-im/infra-role-geth/commit/b78e128d91e2463537aac517dd6c978339e3717d

Remember boys and girls, pay attention to your memory limits.
