### ISSUE TITLE
#14555 Is this really closed?

### ISSUE THREAD

**Issue by h6dworker** [ethereum/go-ethereum#19865]
https://github.com/ethereum/go-ethereum/issues/14555

Is this really closed?
The problem is happening many times

Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-142-generic x86_64)
1.8.23-stable |   | go1.11.5
ERROR[07-19|16:48:43.618] Section processing failed                type=bloombits error="leveldb/table: corruption on data-block (pos=987764): checksum mismatch, want=0x7e09ff99 got=0x35080295 [file=1027430.ldb]"
CRIT [07-19|16:48:43.853] Failed to store last header's hash       err="leveldb/table: corruption on data-block (pos=987764): checksum mismatch, want=0x7e09ff99 got=0x35080295 [file=1027430.ldb]"

1.9.0-stable |   | go1.11.5
CRIT [07-17|17:58:15.726] Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=129212): checksum mismatch, want=0xff3aa83f got=0xcb19e47f [file=16007340.ldb]"

**Comment by karalabe** [comment]
Your disk is corrupted (you need a new one).

**Comment by h6dworker** [comment]
Thank you for providing information.

If it is a hardware issue, please let us know the recommended hardware specification.

I have added an SSD (Transcend SSD TS480GMTS820S) to my Dell laptop computer, but it is not very stable.

If possible, I would like to know the company and model number of the SSD.
Please tell us the recommended server configuration.
