### ISSUE TITLE
Geth limited to 16 peers

### ISSUE THREAD

**Issue by gjeanmart** [ethereum/go-ethereum#19864]
Hi there,

I'm currently trying to sync an Ethereum mainnet full node on an ARM64 single board with Geth. While the block syncing went well, the number of peers seems to be limited to 16 peers max when I'm using the flag `--maxpeers 50`. I have tested two different locations with high-speed Internet connections and no obvious firewall limitations and with two different versions (geth-1.9.0-stable and geth-1.8.7-stable) but the problem seems to be the same.

You can see below some metrics taken while syncing, the last two showing `admin.peers.length`

**Block sync (geth-1.9.0)**
![](https://i.imgur.com/Y01O8Zy.png)

**State sync (geth-1.9.0)**
![](https://i.imgur.com/dIKHJUd.png)

**Peers (geth-1.9.0)**
![](https://i.imgur.com/7Q7CWX3.png)

**Peers (geth-1.8.7) - only 10 hours**
![](https://i.imgur.com/4hpwcOo.png)

### System information

**Geth options:** `geth --syncmode fast --cache 2048 --maxpeers 50 --datadir /mnt/ssd/ethereum`
**Geth version:** 1.9.0-stable and 1.8.7-stable
**Machine:** [NanoPi-M4](http://wiki.friendlyarm.com/wiki/index.php/NanoPi_M4) (arm64 6 cores, 4GB RAM, USB 3.0)
**Disk:** SSD SanDisk Plus 256GB
**OS:** [ARMBian](https://www.armbian.com/) (Debian Stretch)

### Expected behaviour

Should reach more peers (max 50)

### Actual behaviour

Number of peers oscillating between 15-16 peers.

### Backtrace

Logs of the last attempt using geth-1.8.7-stable during 10 hours.

https://gist.githubusercontent.com/gjeanmart/21c83a5b7d1e33925861577c12d67b48/raw/267e17b9b91fab4b666401a0e08f7c831fe90934/gistfile1.txt

**Comment by fjl** [comment]
Could you provide debug logs with `--vmodule=p2p=5` for the geth 1.9.0 instance?

**Comment by karalabe** [comment]
Please make sure you're not firewalled. If port 30303 is blocked from the outside, no inbound connections are allowed, which is half the peer count.

**Comment by gjeanmart** [comment]
Thank you your quick answers.

@fjl : I enabled peer-to-peer tracing (`--vmodule=p2p=5`), waited a few hours and finally reached the limit of 15-16 peers. I pasted the result [here](https://gist.githubusercontent.com/gjeanmart/5834b6c6339e97df3d4d2858ccf61aff/raw/13c71d2ae260f49f828a480f43169041874019aa/gistfile1.txt)

@karalabe my firewall seems correctly configured but I could miss something. Please have a look to the [peer-to-peer trace file](https://gist.githubusercontent.com/gjeanmart/5834b6c6339e97df3d4d2858ccf61aff/raw/13c71d2ae260f49f828a480f43169041874019aa/gistfile1.txt) and let me know if it suggests the port 30303 is blocked.

**Comment by gjeanmart** [comment]
I actually fixed the problem by manually configuring the router with a port-forwarding rule between outside and the board (on port 30303).

Now I have found 47 peers in less than 10 min !

Thank you.
