### ISSUE TITLE
GetTransactionReceipt - not always shows the status field in response

### ISSUE THREAD

**Issue by bansatya** [ethereum/go-ethereum#19879]
Hi there,

While performing transactions from Geth console on the smart contract which have been deployed via go binding. The transaction receipt doesn't show the status field in response.
The snapshots are given below.

#### System information

Geth version: `1.9.0'
OS & Version: Linux (Ubuntu 16.06.xx)
Commit hash : (if `develop`)

#### Expected behaviour
Eth.getTransactionReceipt should always show the status field in response

#### Actual behaviour
Eth.getTransactionReceipt is not showing the status field in response sometimes.

#### Steps to reproduce the behaviour
By deploying contract via go binding and execute transactions from Geth console as mentioned in **https://github.com/ethereum/go-ethereum/issues/19832**

#### Snapshots for reference

![image](https://user-images.githubusercontent.com/33546557/61722098-2ec70400-ad59-11e9-9af0-f993e49e17ab.png)

**Comment by karalabe** [comment]
Did you initialize the forks properly for your network? The status field for receipts was introduced in Byzantium, receipts before that don't contain it. Actually, I'm sure you haven't inited Byzantium yet, because you have `root`, which was removed in Byzantium.

**Comment by bansatya** [comment]
Hi @Karalabe,  
Thanks. I am getting this response for few transactions(in my case txn did using the contract deployed via go binding). 
In all other cases (any other txn) ,  I am getting it with 'status'  value. Please refer the screen shots in refered issue or I can share the same.  In my local network,  Byzantium is initiated. I will share the Genesis file.

**Comment by karalabe** [comment]
Based on your chain config, you enabled Byzantium in block 4. That means until block 4, all transactions will have a `root` and won't have a `status`, and all transaction after block 4 will have `status`. If you want `status` for transaction starting earlier, initialize all forks in block 0.

You probably also want to initialize `constatninopleBlock` and `petersburgBlock` too, since those are 2 more forks that have been passed since.

**Comment by bansatya** [comment]
@karalabe , Thanks.

**Comment by wangruics** [comment]
> Did you initialize the forks properly for your network? The status field for receipts was introduced in Byzantium, receipts before that don't contain it. Actually, I'm sure you haven't inited Byzantium yet, because you have `root`, which was removed in Byzantium.


Hao  can I know  the transaction  before  Byzantium  is  success or fail?   
 Latest transactions      I use  status field.

**Comment by karalabe** [comment]
Before Byzantium there was no status to reveal this information. Please though don't comment on issues closed 2.5 years ago, opening a new one and referencing an older closed one if preferred to keep the history cleaner.
