### ISSUE TITLE
High memory usage with Geth v1.9.0 

### ISSUE THREAD

**Issue by jbunce** [ethereum/go-ethereum#19874]
#### System information

Geth version: `v1.9.0`
OS & Version: Linux/OSX (container)
Docker images: ethereum/client-go:v1.8.27 & ethereum/client-go:v1.9.0

Spotted by @pdobacz. Memory usage is significantly higher with v1.9.0 vs v1.8.27. Both instances were serving no RPC requests when the below outputs were taken.

#### v1.8.27

`docker run -d --entrypoint /bin/sh ethereum/client-go:v1.8.27 -c geth --dev --dev.period 1`

After 15 minutes:

```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
264d11d1015f        sharp_leakey        17.43%              258.2MiB / 1.952GiB   12.92%              13.4MB / 2.99MB     23.2MB / 16.4kB     12
```

#### v1.9.0

`docker run -d --entrypoint /bin/sh ethereum/client-go:v1.9.0 -c geth --dev --dev.period 1`

After 15 minutes:

```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
827aab4dea99        frosty_noether      125.79%             1.653GiB / 1.952GiB   84.68%              178MB / 31.7MB      283MB / 1.22GB      12
```

**Comment by karalabe** [comment]
This is a bug. Geth 1.9.0 introduced a special casing for memory so that mainnet by default uses 4GB, everything else the old 1GB. `--dev` for some reason thinks it's on mainnet. Will fix for 1.9.1
