### ISSUE TITLE
Typo/Error in Cross compiling Wiki

### ISSUE THREAD

**Issue by tylerferrara** [ethereum/go-ethereum#19880]
Minor typo in [Cross compiling Ethereum](https://github.com/ethereum/go-ethereum/wiki/Cross-compiling-Ethereum) wiki.

#### Error

Developers usually have a preferred platform that they feel most comfortable working in, with all the necessary tools, libraries and environments set up for an optimal workflow. However, there's often need to build for either a different CPU architecture, or an entirely different operating system; but maintaining a development environment for each and switching between **the** them quickly becomes unwieldy.

#### Fix

...development environment for each and switching between them quickly...

**Comment by ligi** [comment]
thanks - fixed
