### ISSUE TITLE
why append "Linking completed." to output in the solc compiler

### ISSUE THREAD

**Issue by garyng2000** [ethereum/go-ethereum#19884]
#### System information

Geth version: 1.9.0(solc 0.5.10+commit.5a6ea5b1.Windows.msvc)
OS & Version: Windows
Commit hash : (if `develop`)

#### Expected behaviour
I piped the bin code into solc via in the form of Window's startProcess logic in c#
equivalent to 

echo bycode_in_string_form | solc - --link --libraries abc:0x12344444...

To my surprise the output has 'Linking completed.' appended at the end of the stdout which is not a valid bytecode anymore.
Shouldn't that go to stderr instead ?

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Please ask on the Solidity repo https://github.com/ethereum/solidity.
