### ISSUE TITLE
Feature: add absolute-time based disk flushing

### ISSUE THREAD

**Issue by prd-fox** [ethereum/go-ethereum#19895]
Feature request

When `geth` runs with `--gcmode=full`, there is a timeout condition that, if reached, will flush the current in-memory data to disk.

If I read the code correctly, the timeout is based on the cumulative execution time of block processing, rather than an absolute time period.
For private networks under variable load (a period of lots of full blocks followed by a period of lots of empty blocks), this can be tricky to gauge a good value to use for the timeout.

It would be simpler for users to specify an absolute time period that flushing could happen, so they are never out of sync by a period of more than the time they specify. (In addition to the block execution time timeout).

**Comment by holiman** [comment]
> It would be simpler for users to specify an absolute time period that flushing could happen, so they are never out of sync by a period of more than the time they specify.

That's the exact point of the current system. When you execute blocks in real time, you only get one block every 14 seconds (on mainnet). Thus, going through old blocks goes much faster, so absolute time does not tell you how much time it will take to re-execute. 

Same goes for private networks, actually. A `timeout` of 1 hour means that your computer will take about one hour to get back to up head (in the worst case)

**Comment by adamschmideg** [comment]
To be fixed by #19920

**Comment by prd-fox** [comment]
Yeah that makes sense. I guess I was thinking about flushing every X blocks, which would equal some time period, regardless of the size of the blocks. Still, I think what is there now is sufficient. Thanks!
