### ISSUE TITLE
how to judge token is erc20 or erc721 token to use code?

### ISSUE THREAD

**Issue by SalleryWang** [ethereum/go-ethereum#19894]
Hi there,

how to judge token is erc20 or erc721 token to use code?

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Please ask on the Etheruem stack exchange, this has nothing to do with Geth.
