### ISSUE TITLE
Change in block size format broke many libraries

### ISSUE THREAD

**Issue by kochol** [ethereum/go-ethereum#19918]
Hi there,

I upgraded to the latest version of geth 1.9.1v in this version the IPC returns block size in integer format but before geth returns it in hex string format. This change brakes some libraries that I use in my project. Why you did this unnecessary change?

**Comment by karalabe** [comment]
It was a regression from a larger refactor. It was already fixed on master and will be shipped in 1.9.2. https://github.com/ethereum/go-ethereum/pull/19885
