### ISSUE TITLE
Ethereum synchronize stoppped in 8286900 block

### ISSUE THREAD

**Issue by AkashiHidaka** [ethereum/go-ethereum#19914]
Hi there,
Ethereum synchronize stoppped in 8286900 block and it is restart from 8286850 block.

#### System information

Geth version: `Geth/v1.9.1-unstable-e8c9579f/linux-amd64/go1.11.5`
OS & Version: Ubuntu
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by AkashiHidaka** [comment]
This is show of the issue.
![image](https://user-images.githubusercontent.com/44053447/62442072-39d25900-b789-11e9-8fe8-060344d736e4.png)
Continue this event occur.

**Comment by thomasmodeneis** [comment]
Why is this a issue ? have you tried restarting it ? there are hundreds of reasons why sync could stop, including connectivity or bad actors sending you garbage.

**Comment by AkashiHidaka** [comment]
Yes, I tried restart server and restart geth service .
But same

**Comment by AkashiHidaka** [comment]
When the block reached of the value the geth service cpu usage value have 300% + and when restart block count , it down.
How to skip of the values?

**Comment by AkashiHidaka** [comment]
Hello
I find the some reason of it and the geth own much resources.
I update 16GB Ram and 6 cpu in Digitalocean server.
But still the geth using 500% CPU and some hundred blocks calculate and it is returned original value.
What is the reason of it?
I used 1.9.1 stable version.

**Comment by karalabe** [comment]
This is really weird. Could you please run with `--vmodule=downloader=5` and upload the logs somewhere? Thanks
