### ISSUE TITLE
Lag in eth_getTransactionByHash

### ISSUE THREAD

**Issue by ds414** [ethereum/go-ethereum#19924]
#### System information

Geth version: `1.8.23-stable`
OS & Version: Ubuntu 18.04.2 LTS x64
Mode: --gcmode archive --syncmode full
Synced: Yes

#### Expected behaviour
We regularly check the geth for new events. When a new event appears, we immediately try to get transaction properties - eth_getTransactionByHash. For example:
> curl --data '{"method":"eth_getTransactionByHash","params":["0xf5c0fe7f75f9b4aceee2dd87fb983cfe544607afcf1a9a462c218c0c0f744517"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

`{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x937ecf4e0a98abeafde57529133b9b1bcdb6a42c5efa67d149c7b5692cb522f7","blockNumber":"0x7eb18d","from":"0x6d5591ea38e3ea32cd4db138d26341c86827946a","gas":"0x5fe1b","gasPrice":"0x77359400","hash":"0xf5c0fe7f75f9b4aceee2dd87fb983cfe544607afcf1a9a462c218c0c0f744517","input":"0x1cff79cd000000000000000000000000526af336d614ade5cc252a407062b8861af998f500000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000044bc25a810000000000000000000000000448a5065aebb8e423f0896e6c5d525c040f59af3000000000000000000000000000000000000000000000000000000000000fd5a00000000000000000000000000000000000000000000000000000000","nonce":"0x5","to":"0xc34ff80be0290bc4e90e19f9892773f3e1d2fc5b","transactionIndex":"0x48","value":"0x1ff973cafa8000","v":"0x25","r":"0x1cd79478210eeea6270c75c64bd85ebe6f25d234c2970f2ec0028ad2913aadc5","s":"0x3a71ff8b2423c1dedc72ede14b2c7092dca45123fc5f9359a5896cd3209f84"}}`

#### Actual behaviour
But sometimes it returns empty response:
`{" jsonrpc ":" 2.0 "," result ": null," id ": 1}`
We try again and again, usually within a minute "transaction receipt" comes.
Recently, empty response has been happening more and more often and the interval between the empty response and the "transaction receipt" in the response has been increasing (up to 5 min).

#### Steps to reproduce the behaviour
Wait new events and immediately send eth_getTransactionByHash. Sometimes you will get empty response.

#### Question
Is this normal behavior?
Can we to get "transaction receipt" content from the first request eth_getTransactionByHash?

**Comment by karalabe** [comment]
Does this reproduce with latest stable? 1.8.23 is a fairly old release

**Comment by ds414** [comment]
Geth updated to 1.9.1-stable. Now waiting before errors will come. This can take some days.

**Comment by adamschmideg** [comment]
@ds414 I assume you haven't experienced this problem since. If the problem persists, please open a new issue.
