### ISSUE TITLE
Error in subscribing and making node up in pvt blockchain

### ISSUE THREAD

**Issue by horizon-19** [ethereum/go-ethereum#19925]
Hi there,
With the latest stable geth version 1.9.x, there is some breaking change ie,  to subscribe the nodes to bootnode,  in pvt blockchain, I am getting  the error mentioned as the stackoverflow l[link](https://ethereum.stackexchange.com/questions/73326/node-cannot-be-made-up-in-private-blockchain-by-using-command-line)

In another system, running prev version of geth 1.8.27 the problem does not reproduceable. As using ppa we can only able to download the newest version thus please help me how to download the previous version.

I have also downloaded the tar file of previous version but **bootnode binary** is missing from those version thus could **not create** our own **private blockchain**.

Please help

**Comment by AkashiHidaka** [comment]
I running the new 1.9.1 stable version in digitalocean computer.
In there geth process using CPU usage to 600% more and after some time it is returned initial header block index number calculate.
Blocksynchronize isn't work well.
I used 8cpu , 32GB RAM server and it isn't problem of resource.
How to solve this problem?
Please.

**Comment by rjl493456442** [comment]
@horizon-19 You are using clique but you don't specify any signer in `extra` field of genesis. Not sure whether you create the genesis manually or not. 
Actually, we have an awesome tool `puppeth`, you can use it to generate the genesis config file.

**Comment by horizon-19** [comment]
@karalabe  Hi there, I am doing from scratch and while creating the account using newer geth version 1.9.x I am getting this

> INFO [08-08|10:36:37.532] Bumping default cache on mainnet         provided=1024 updated=4096
WARN [08-08|10:36:37.532] Sanitizing cache to Go's GC limits       provided=4096 updated=1002
INFO [08-08|10:36:37.535] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-08|10:36:37.535] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
Your new account is locked with a password. Please give a password. Do not forget this password.

what this  

> smartcard  socket not found disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory" 
means?

This error is not popping up while creating the account using 1.8.7 geth version. Is this kind of issue?

**Comment by horizon-19** [comment]
@karalabe  please reopen the issue as even specifying the node address the error is reproducible.

I ll let u know the steps to reproduce it(I am using VirtualBox linux machine and using vagrant to create the instance):

- installed geth 1.9.1 using ppa (through ppa we can only get the latest geth version)

- created the folder in 

> /home/vagrant/  
with devnet name
created 2 folder with name node1 and node2 inside devnet

- created the account in each node folder with password node1 and node2 respectively.

- copied the public address and also stored the password as password.txt in each node folder respectively.

- created the genesis.json with following content
`{
  "config": {
    "chainId": 46860,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "byzantiumBlock": 4,
    "constantinopleBlock": 5,
    "clique": {
      "period": 5,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x5c596a29",
  "extraData": "0x202952430057c94DD1F2dAD58A8AfE15E9213465",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "0x202952430057c94DD1F2dAD58A8AfE15E9213465": {
      "balance": "0x900000000000000000000000000000000000000000000000000000000000000"
    },
	"0xB7b056d29Da0F5A1fcB0763e6080e774a6F1E6f0": {
      "balance": "0x900000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}`
here node1 address is used in extradata as specified by you

- initialise all the nodes with this genesis.json using `geth --datadir node1/ init genesis.json` likewise the second node as well

- created the bootnode 

- made the bootnode up inorder to be used as a manager of the private node communication process using `nohup bootnode -nodekey boot.key -verbosity 9 -addr 127.0.0.1:30302 > boot.log 2>&1 & ` where 30302 is the post which is used for the process

- now to make all the node connected and up need  provided `nohup geth --datadir node1/ --syncmode 'full' --port 30303 --rpc --rpcaddr 127.0.0.1 --rpcport 3503 --rpcapi 'personal,db,eth,net,web3,txpool,miner' --bootnodes 
'enode://00f1bd4f26b16a7216a46de5324aac8b33ec3fbc3de4987c06dfa7549511210b9745961e2664b46cc63eafbfff37fd0b135080766ba5efde28c33131e0c13c9
8@127.0.0.1:30302' --networkid 1505 --gasprice '1' --unlock 0 --password node1/password.txt --mine > node1/01.log 2>&1 &`

I am getting the same problem and log looks like this 

> WARN [08-08|12:35:19.560] Sanitizing cache to Go's GC limits       provided=1024 updated=1002
> INFO [08-08|12:35:19.561] Maximum peer count                       ETH=50 LES=0 total=50
> INFO [08-08|12:35:19.561] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
> ERROR[08-08|12:35:19.561] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
> ERROR[08-08|12:35:19.561] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
> ERROR[08-08|12:35:19.561] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
> ERROR[08-08|12:35:19.561] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
> ERROR[08-08|12:35:19.561] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
> ERROR[08-08|12:35:19.562] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
> INFO [08-08|12:35:19.562] Starting peer-to-peer node               instance=Geth/v1.9.1-stable-b7b2f60f/linux-amd64/go1.11.5
> INFO [08-08|12:35:19.562] Allocated trie memory caches             clean=250.00MiB dirty=250.00MiB
> INFO [08-08|12:35:19.562] Allocated cache and file handles         database=/home/vagrant/devnet/node1/geth/chaindata cache=501.00MiB handles=524288
> INFO [08-08|12:35:19.572] Opened ancient database                  database=/home/vagrant/devnet/node1/geth/chaindata/ancient
> INFO [08-08|12:35:19.572] Initialised chain configuration          config="{ChainID: 46860 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: 5  Petersburg: <nil> Engine: clique}"
> INFO [08-08|12:35:19.572] Initialising Ethereum protocol           versions=[63] network=1505 dbversion=<nil>
> WARN [08-08|12:35:19.572] Upgrade blockchain database version      from=<nil> to=7
> INFO [08-08|12:35:19.602] Loaded most recent local header          number=0 hash=7eb056…7f1deb td=1 age=6mo4d1h
> INFO [08-08|12:35:19.602] Loaded most recent local full block      number=0 hash=7eb056…7f1deb td=1 age=6mo4d1h
> INFO [08-08|12:35:19.602] Loaded most recent local fast block      number=0 hash=7eb056…7f1deb td=1 age=6mo4d1h
> INFO [08-08|12:35:19.602] Regenerated local transaction journal    transactions=0 accounts=0
> panic: runtime error: makeslice: len out of range
> 
> goroutine 52 [running]:
> github.com/ethereum/go-ethereum/consensus/clique.(*Clique).snapshot(0xc00024ea10, 0x1370400, 0xc004ca8000, 0x0, 0x5ddc6147f556b07e, 0xcab77ea643c9d30, 0xdf26237f79652cda, 0xeb1d7f80862d2e79, 0x0, 0x0, ...)
>         /build/ethereum-Tzgcbu/ethereum-1.9.1+build19532+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/clique/clique.go:377 +0x48c
> github.com/ethereum/go-ethereum/consensus/clique.(*Clique).Prepare(0xc00024ea10, 0x1370400, 0xc004ca8000, 0xc0000fbb00, 0xeb1d7f80862d2e79, 0x0)
>         /build/ethereum-Tzgcbu/ethereum-1.9.1+build19532+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/clique/clique.go:497 +0xcc
> github.com/ethereum/go-ethereum/miner.(*worker).commitNewWork(0xc0000304e0, 0xc000293cb0, 0x0, 0x5d4c1707)
>         /build/ethereum-Tzgcbu/ethereum-1.9.1+build19532+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:865 +0x3a6
> github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0xc0000304e0)
>         /build/ethereum-Tzgcbu/ethereum-1.9.1+build19532+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:408 +0xbe3
> created by github.com/ethereum/go-ethereum/miner.newWorker
>         /build/ethereum-Tzgcbu/ethereum-1.9.1+build19532+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:216 +0x4ec
> 
> > 


Please help me understand where I went wrong.
Is the problem due to 

> smartcard socket not found disabling err="stat /run/pcscd/pcscd.comm: no such file or directory"

as in 1.8.7 version this error is not coming and also when I have looked into geth version I got to know that from 1.9.x onwards these are working on ethereum protocol 63 and not on [62 ,63] both. 
Does that makes some change in specifying and making the nodes up?

Please help

**Comment by karalabe** [comment]
Please use puppeth to make the genesis block. Clique has a quirky extradata format. Either construct it according to spec (http://eips.ethereum.org/EIPS/eip-225), or use a tool that will do it for you.

**Comment by horizon-19** [comment]
@karalabe  thanks for the help, using I have created the genesis.json and it worked, the extradata there needs some extra 0's to prefix and suffix, don't know why but it worked like charm, thanks once again

**Comment by karalabe** [comment]
Glad it worked out :) :+1:
