### ISSUE TITLE
Fresh full node - "most recent local full block" remains 0

### ISSUE THREAD

**Issue by SjonHortensius** [ethereum/go-ethereum#19935]
#### System information

Geth version: `instance=Geth/v1.9.1-stable-b7b2f60f/linux-amd64/go1.12.7`
OS & Version: `linux-amd64`

#### Description of issue

Despite several restarts, I never seem to get my node to fully sync. For example - here are a few notable log-entries from last restart:

```
Loaded most recent local header          number=8316493 hash=db0636<E2><80><A6>c951e5 td=11385618476212767437766 age=1m28s
Loaded most recent local full block      number=0       hash=d4e567<E2><80><A6>cb8fa3 td=17179869184             age=50y3mo3w
Loaded most recent local fast block      number=8316425 hash=2590dd<E2><80><A6>bc63df td=11385464097476829842966 age=16m2s
...
Switch sync mode from full sync to fast sync
...
Initializing fast sync bloom
...
Initializing fast sync bloom             items=332228780 errorrate=0.009 elapsed=37m17.409s
Imported new block headers               count=1    elapsed=1.072s     number=8317197 hash=3bfab1<E2><80><A6>2cd548
Initialized fast sync bloom              items=333439053 errorrate=0.009 elapsed=37m22.027s
Imported new state entries               count=384  elapsed=2.283ms    processed=334198211 pending=6974  retry=0  duplicate=6 unexpected=86
Imported new state entries               count=768  elapsed=4.002ms    processed=334198979 pending=9362  retry=0  duplicate=6 unexpected=86
...
Imported new block headers               count=1    elapsed=13.656ms   number=8322584 hash=8ded8b<E2><80><A6>e8772f
Imported new state entries               count=494  elapsed=4.524ms    processed=351950314 pending=1637  retry=0   duplicate=5977 unexpected=40197
Imported new state entries               count=448  elapsed=6.386ms    processed=351950762 pending=1539  retry=0   duplicate=5977 unexpected=40197
Imported new state entries               count=420  elapsed=6.749ms    processed=351951182 pending=1452  retry=0   duplicate=5977 unexpected=40197
...
Got interrupt, shutting down...
HTTP endpoint closed                     url=http://127.0.0.1:8545
IPC endpoint closed                      url=/srv/geth/geth.ipc
Blockchain manager stopped
Stopping Ethereum protocol
Ethereum protocol stopped
Transaction pool stopped
Failed to store last header's hash       err="leveldb: closed"
```

Due to the local full block never getting past 0, geth always restarts a fast-sync (even though probably unneccesary). My current eth_syncing output:

```json
{"jsonrpc":"2.0","id":1,"result":{
"currentBlock":"0x7efde8",
"highestBlock":"0x7efe4b",
"knownStates":"0x14fb44ff",
"pulledStates":"0x14fb3fc1",
"startingBlock":"0x7ee7fa"
}}
```

I have a strong suspicion the `Failed to store last header's hash | err="leveldb: closed"` is a significant cause - but I am unable to debug what causes it. I see no other errors and for as far as I can see the other leveldb writes are successful

**Comment by SjonHortensius** [comment]
Okay - so apparently simply more time was needed. The "leveldb: closed" is probably caused by leveldb not being opened yet due to the fast-sync not being completed yet. After another day of syncing, the node catched up with 363M state entries and switched to normal syncing:

```
Committed new head block   
Deallocated fast sync bloom
Imported new chain segment 
```

and a restart now works as expected, logging the correct values

**Comment by sssubik** [comment]
@SjonHortensius How long did it take for fast sync to completely finish? I am also getting similar logs in my sync.

**Comment by SjonHortensius** [comment]
> @SjonHortensius How long did it take for fast sync to completely finish? I am also getting similar logs in my sync.

this happened on a virtual server with an ssd, and I'm pretty sure it took a few weeks to get in sync fully

**Comment by sssubik** [comment]
@SjonHortensius
