### ISSUE TITLE
Bug Security : Locked Ether

### ISSUE THREAD

**Issue by L-KH** [ethereum/go-ethereum#19930]
The locked Ether bug occurs in contracts that can receive ether but do not allow users to extract ether from them (nor to destroy them).

```
contract MarketPlace {
    function deposit() payable {
    }

    function transfer() {
        uint x = msg.value;
    }
}
```
     
This contract is vulnerable to the locked ether vulnerability because it allows users to deposit ether by calling the _deposit_ function and it does not contain any function that would allow users to withdraw the deposited ether.

**Comment by karalabe** [comment]
Don't send Ether to such contract. Ethereum allows anyone to program any kind of contract. It's up to the developer and user to ensure the program is correct.
