### ISSUE TITLE
Question: How can a user specify the number of block after which pruning happens?

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/go-ethereum#19940]
## Problem Definition

This is just a question I had. Tried to contact you through gitter and twitter but no response yet so I guess an issue is also good since other people may have the same question.

In Raiden we would like to emulate the behaviour of some old blocks being pruned in some of our tests. So naturally the question came up how can this be achieved with geth.

## Question

Is there any combination of arguments that can guarantee the number of blocks after which old state is pruned and won't be returned when queried?

**Comment by karalabe** [comment]
Geth does in-memory pruning for blocks older than HEAD-128. Periodically some states are flushed to disk (every hour + on shutdown). There's no disk pruning yet.

# Answer

128 blocks, don't restart Geth in between

**Comment by LefterisJP** [comment]
Hey Peter, thanks for the response.

So it's not configurable at all? Can we somehow put it to 5 blocks for a testcase?

Also I am trying to determine if the 128 limit is strictly fixed. We have a test that tries to test for this and the test is flaky in between. Some times it works at the 129th block but sometimes it does not. 

Could there be other factors that could make geth not prune for blocks older than HEAD-128 ?

**Comment by karalabe** [comment]
Well, if you run a PoA chain (clique, dev mode) and HEAD-127 doesn't contain any transactions, then the state of HEAD-127 will be the same as HEAD-128, so it will still be referenced and not deleted.

The number 128 is hard coded as the sync code needs to be aware of what state is available in the network and what isn't, so we can't allow users to change it.

**Comment by LefterisJP** [comment]
> Well, if you run a PoA chain (clique, dev mode) and HEAD-127 doesn't contain any transactions, then the state of HEAD-127 will be the same as HEAD-128, so it will still be referenced and not deleted.

Thank you that's valuable info. Let us investigate on the flakiness then.

**Comment by LefterisJP** [comment]
I will close this issue as I the questions have been answered. May open more if more questions arise.
