### ISSUE TITLE
account list - Failed to unlock developer account: could not decrypt key with given passphrase

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#19941]
Here's what I do
```bash
> mkdir new_empty_dir
> cd new_empty_dir
> # Create an account with a password
> geth account new
> geth account list
Account #0: {....}
> geth --dev account list
Fatal: Failed to unlock developer account: could not decrypt key with given passphrase
```
Apparently, the last command tries to unlock the account with an empty password and fails. I'd expect one of two things. Since the command does nothing else than lists the accounts, I'd expect it to just do that in dev mode, too. Or, if it's not an option, I'd expect a better error message like "Failed to unlock the first, developer account: could not decrypt key with empty password".

**Comment by karalabe** [comment]
Developer mode is a standalone thing, it does not support extra commands. `geth --dev` that's it, no subcommands (other than `console`).

**Comment by adamschmideg** [comment]
If other commands are not supported, a warning should be given. I first entered this command accidentally and it made sense to me.

**Comment by hobbydev71** [comment]
I tried to run the geth, but `Fatal: Failed to unlock developer account: could not decrypt key with given password` is occured.
`geth --datadir data --networkid 15 --http --http.corsdomain="https://remix.ethereum.org" --http.api web3,eth,debug,personal,net --vmdebug --dev console`

How can I solve this?

**Comment by parveensaini1** [comment]
kdjnfkjv kejrf
