### ISSUE TITLE
Block synchronization

### ISSUE THREAD

**Issue by DingGeng-GitHub** [ethereum/go-ethereum#19969]
Geth version: `geth 1.9.2`
OS & Version: `Ubuntu16.04`

My local block has always been consistent with the blockchain, but after restarting the server, geth.log shows that the block is several hundred less and starts to synchronize again. Why?

geth.log
![image](https://user-images.githubusercontent.com/39077274/63143064-1d52de00-c01f-11e9-81ae-be47d61b984d.png)

**Comment by karalabe** [comment]
Geth keeps all recent state in memory and garbage collects in memory. When you shut it down, all that live state data needs to be written to disk. You didn't wait for Geth to terminate gracefully, rather murdered it in the process (there's a log `Writing cached state to disk`, it's never logged success).

Writing the cached state generally can take even up to a minute. Please make sure you don't murder the process while it's shutting down. If you use docker, please bump the shutdown timeout from the default 10 seconds to maybe 3 minutes.

**Comment by DingGeng-GitHub** [comment]
Can you provide the command to turn off the geth service correctly?

**Comment by DingGeng-GitHub** [comment]
I can not figure out how to stop a running geth node without killing the process. I tried to lookup geth help but there is no mention of stopping, halting or any shutdown command.

**Comment by DingGeng-GitHub** [comment]
I'm running it as a daemon

**Comment by DingGeng-GitHub** [comment]
@karalabe
