### ISSUE TITLE
Syncing with Geth 1.9.2 - rinkeby - get stuck from time to time

### ISSUE THREAD

**Issue by AndreiD** [ethereum/go-ethereum#19978]
#### System information

Geth version: 1.9.2 stable
OS & Version: Ubuntu 19
Good CPU
SSD with plenty of space

#### Expected behaviour

To sync till the end no matter if invalid things happen

#### Actual behaviour

halts with:
 
~~~~
CRIT [08-18|19:03:39.431] Failed to store last header's hash       err="leveldb/table: corruption on data-block (pos=1140825): checksum mismatch, want=0xc5a83e88 got=0x32c3d4fa *[file=003715.ldb]*"
~~~~

#### Steps to reproduce the behaviour

This will be difficult to reproduce but...

- install latest geth

- geth --rinkeby --datadir /home/me/rinkeby --v5disc  --port=50111  --cache=1024 --ipcdisable

#### Backtrace

~~~~
INFO [08-18|18:26:57.179] Imported new block receipts              count=257  elapsed=231.340ms number=2333832 hash=608479…ab68b2 age=1y3mo2d   size=2.51MiB
INFO [08-18|18:26:57.225] Imported new state entries               count=1773 elapsed=25.399ms  processed=4415435 pending=34381 retry=0   duplicate=319 unexpected=1269
INFO [08-18|18:26:57.439] Imported new block receipts              count=257  elapsed=245.707ms number=2334089 hash=6f300f…a4f5dd age=1y3mo2d   size=2.76MiB
INFO [08-18|18:26:57.654] Imported new block receipts              count=258  elapsed=211.562ms number=2334347 hash=76460a…607010 age=1y3mo2d   size=2.63MiB
INFO [08-18|18:26:57.829] Imported new block headers               count=2048 elapsed=605.414ms number=2371776 hash=a86b42…e56853 age=1y2mo3w
INFO [08-18|18:26:58.541] Imported new state entries               count=1773 elapsed=3.984ms   processed=4417208 pending=34349 retry=177 duplicate=319 unexpected=1269
INFO [08-18|18:26:59.333] Imported new state entries               count=1980 elapsed=5.098ms   processed=4419188 pending=33175 retry=177 duplicate=319 unexpected=1269
INFO [08-18|18:26:59.699] Imported new state entries               count=1773 elapsed=4.458ms   processed=4420961 pending=32539 retry=177 duplicate=319 unexpected=1269
INFO [08-18|18:26:59.999] Imported new state entries               count=798  elapsed=3.945ms   processed=4421759 pending=34010 retry=177 duplicate=319 unexpected=1269
CRIT [08-18|18:27:00.304] Failed to store last header's hash       err="leveldb/table: corruption on data-block (pos=1140825): checksum mismatch, want=0xc5a83e88 got=0x32c3d4fa [file=003715.ldb]"
~~~~

I have to go into chaindata, delete the file, start the sync again. 

Shouldn't this operation be done automatically somehow ?

**Comment by karalabe** [comment]
1. You can'd just delete a random file from a database and expect thing to keep working. The database will be blown and useless eventually hitting a bad block due to missing data.
2. `corruption on data-block` means that LevelDB wrote something to disk, but later when reading it back, the disk is returning something else. Generally this means your disk is dying, you'll need to buy a new one.

**Comment by AndreiD** [comment]
1. well I just did that, re-started the sync and all is ok.
2. it's a new SSD Disk just bought 1 months ago... Samsung evo 860 1TB.  I don't think the disk is the problem.
