### ISSUE TITLE
Add ARM/ARM64 CI environments

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#19982]
Apparently there's a `big.Int` error in Go on ARM64 prior to 1.12.9 (https://github.com/golang/go/issues/32940), which may or may not be the only issue causing bad blocks (https://github.com/ethereum/go-ethereum/issues/19754).thttps://github.com/ethereum/go-ethereum/issues/19754). As ARM is getting more and more prevalent, I think we should consider expanding our CI with ARM targets too somehow.

**Comment by diglos** [comment]
@karalabe, NanoPC manufacturer team (FriendlyARM) approached me several days ago offering help for developing the Ethereum ARM64 images. Let me know if you guys need something from them (spare boards, further tech info, ...).

Of course, I can give you a hand for any test you may need to run.
