### ISSUE TITLE
solC not on Chocolatey

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/go-ethereum#1998]
Following the windows install instructions from [the wiki](https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial#install-solc-on-windows), I get the following error message:

    C:\Users\sbuergel>cinst -pre solC-stable
    Installing the following packages:
    solC-stable
    By installing you accept licenses for the packages.
    solC-stable not installed. The package was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is pos
    sible that the package name exists but the version does not.
     Version: ""
     Source(s): "https://chocolatey.org/api/v2/"
    Chocolatey installed 0/1 package(s). 1 package(s) failed.
     See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    Failures:
     - solC-stable

It seems either that solC is not maintained on chocolatey or we need to know the specific version. In either case it would be great to fix and (if required) update the wiki linked above.

**Comment by obscuren** [comment]
@tgerring @chriseth any idea who's maintaining this?

**Comment by tgerring** [comment]
Seems like Chocolatey support is patchy. Maybe better that we introduce clearer instructions with Homestead website revamp that @alexvandesande is working on

**Comment by tgerring** [comment]
Nominate to close this issue and move it to the appropriate solc repo.

**Comment by thebitpost** [comment]
Is there any solution for windows 8.1?
