### ISSUE TITLE
Synchronized Geth But getBalance return zero

### ISSUE THREAD

**Issue by mtahani** [ethereum/go-ethereum#19988]
Hi there,

#### System information
CPU: Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz, 12 cores
Memory: 16GB
OS: CentOS Linux 7.6.1810
Geth version: 1.9.2

I ran the Geth on the following parameters and waited a long time:
./geth  --datadir="/run/media/root/external/ethereum/" --port 3020 --networkid 58342 --nodiscover --maxpeers=0 --ipcpath $HOME/.ethereum/geth.ipc console

Returns the value **false** when I execute the command **eth.syncing**
But when I execute the command eth.getBalance it still returns **ZERO**
![image](https://user-images.githubusercontent.com/5221970/63241613-9cd3ed80-c269-11e9-809a-11cb5d441930.png)

I installed **Mist Wallet**  to ensure gate update and synced with geth($HOME/.ethereum/geth.ipc)
When I got started wallet,I had all the accounts with their balance.
![image](https://user-images.githubusercontent.com/5221970/63241576-72823000-c269-11e9-8ab5-584276a532bd.png)

**_The question is if Geth is not yet fully updated Why display balance accounts in wallet but given zero with command getBalance?_**

#### Backtrace
````
[backtrace]
````

**Comment by cajunlady78** [comment]
i dont know how this works but im a fast learner

**Comment by holiman** [comment]
According to the screnshots above, geth deems `0xda55`to have zero balance, and that's what Mist also shows. 

Mist also says geth is at block `8378981`, which seems accurate, for mainnet. However, it's all a bit odd. Why are you using `networkid=58342` ? And you have disabled connectivity with `--maxpeers=0 --nodiscover` . 

And that account on Mainnet does have a bit of ether: https://etherscan.io/address/0xda55a2cfa3e0a2c1970410e90dc15ed33eac459e  (`0.0000002879798509 Ether`). 

I'm not sure what you're trying to do.... A private net? Sync mainnet?

**Comment by mtahani** [comment]
I'm implementing a project(Exchange) where I need to connect to the **mainnet** and do some commands.
But after a long time, I still couldn't get out of the simple command getBalance.
plz help me!

**Comment by karalabe** [comment]
Mist uses Infura until Geth syncs. My guess is that Geth is not yet synced. Wait, you have `--maxpeers=0`, that means networking is disabled. Without networking, sync is never even started.

**Comment by mtahani** [comment]
Corrected as follows
it's true?
How long should I wait?
Do I need **--networkid**?

./geth  --datadir="/run/media/root/external/ethereum/" --port 3020 --networkid 58342 --nodiscover --ipcpath $HOME/.ethereum/geth.ipc console

**Comment by mtahani** [comment]
Is there anyone here?

**Comment by gballet** [comment]
@mtahani you know that you have synced when typing `eth.blockNumber` in the console returns roughly the same value as the latest block, that you can check on e.g. on etherscan.io. As the time of this writing, the current block number is  `8490484`. If you have a value that is way lower than this, you are not synced.

**Comment by adamschmideg** [comment]
The original question seems to be answered. If you are still facing a problem, please open a new issue.
