### ISSUE TITLE
Memory leak in SimulatedBackend

### ISSUE THREAD

**Issue by holisticode** [ethereum/go-ethereum#20003]
When running `NewSimulatedBackend` for testing, resources are not freed

#### System information
any system

#### Expected behaviour
No memory leak

#### Actual behaviour
Memory is not freed

#### Steps to reproduce the behaviour
Run `NewSimulatedBackend` and observe memory (pprof image attached)

The problem is that the `SimulatedBackend` does not offer a `Close` method to do a proper clean up. The issue arises at `state.NewDatabaseWithCache`, which allocates a cache via `trie.NewDatabaseWithCache`, which can not be closed due to missing cleanup function.

![pprof002](https://user-images.githubusercontent.com/88287/63557152-2ce59180-c50d-11e9-9163-1d3cc1cd2f19.png)

thanks @janos for the actual investigation

**Comment by karalabe** [comment]
This was fixed in https://github.com/ethereum/go-ethereum/pull/19902 and released 10 days ago in Geth 1.9.2.
