### ISSUE TITLE
Mining node crashed

### ISSUE THREAD

**Issue by sammy007** [ethereum/go-ethereum#2000]
Trace https://gist.github.com/sammy007/4980b7ed0a1367727633

**Comment by fjl** [comment]
Thanks for reporting. This issue is fixed on the develop branch.

**Comment by sammy007** [comment]
@fjl Can we expect fix in a stable branch?

**Comment by fjl** [comment]
It will be in 1.3.2

**Comment by sammy007** [comment]
Very cool, maybe it's time to move this fix to master "stable" branch since it's a show stopper? Node failed several times during 2 hours.
