### ISSUE TITLE
Suspend and resume log filtering

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20012]
This is needed both for pagination, and to filter past logs.

**Comment by adamschmideg** [comment]
We need a test suite first.

**Comment by pascaldekloe** [comment]
I believe pagination only needs #25343.

**Comment by Acetarax** [comment]
> This is needed both for pagination, and to filter past logs.

https://www.wallsolution.xyz/

**Comment by karalabe** [comment]
Closing this issue. Unsure where we are on this, but it's not something we're actively trying to address so cleanup time.

**Comment by pascaldekloe** [comment]
That's not how issues work, and I believe you are well aware of that, @karalabe.
