### ISSUE TITLE
ReadMe for "alloc" in “Operating a private network” should tell user to create accounts first

### ISSUE THREAD

**Issue by FlashSheridan** [ethereum/go-ethereum#20015]
https://github.com/ethereum/go-ethereum#operating-a-private-network states “_First_, you'll need to create the genesis state of your networks… If you'd like to pre-fund some accounts for easier testing, you can populate the alloc field with account configs”.  (Emphasis added.)  As noted in a blog post (https://gettoshare.com/2017/10/30/how-to-use-genesis-json-alloc-property/) and responses to a previous bug report (https://github.com/ethereum/go-ethereum/issues/14831), the first-time reader of this ReadMe should normally create the accounts referenced in the `alloc` fields first.  (The natural expectation of the intended audience for this ReadMe is probably something like the behavior of the `--dev` and `--unlock` options, but those are not documented here.)

I’ve already submitted two PRs to correct this; the first was rejected (https://github.com/ethereum/go-ethereum/pull/20001) and the revision (https://github.com/ethereum/go-ethereum/pull/20005) is in limbo.  I’m filing a bug so that users can search the database for unfixed bugs containing "alloc", rather than having to search for blog posts.

**Comment by karalabe** [comment]
Fixed.
