### ISSUE TITLE
“Managing Accounts” link broken at https://geth.ethereum.org/docs/

### ISSUE THREAD

**Issue by FlashSheridan** [ethereum/go-ethereum#20014]
The “Managing Accounts” link on the top-level documentation page (https://geth.ethereum.org/docs/) returns a 404 error: https://geth.ethereum.org/how-to/Managing-your-accounts

**Comment by ankitm123** [comment]
You can try this link for the time being: https://geth.ethereum.org/interface/Managing-your-accounts
@karalabe @adambabik, I can do a PR, it seems like a trivial fix, is it ok?

**Comment by MariusVanDerWijden** [comment]
Account management now moved to https://geth.ethereum.org/docs/interface/managing-your-accounts
There are no broken links at the top page anymore as the intro was rewritten
