### ISSUE TITLE
rewrite ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#20024]
in context of #20023 we saw that the ISSUE_TEMPLATE is a bit weird. It needs some rewriting and perhaps we should also use the new feature of different issue templates for bugs/feature_requests/..

**Comment by ligi** [comment]
also seeing #21889 we should also have a issue template for vulnerabilities to maybe even prevent a potential 0day hitting the issue tracker and channel them to https://bounty.ethereum.org

**Comment by holiman** [comment]
@ligi we already do have a security policy file though:  https://github.com/ethereum/go-ethereum/security/policy

**Comment by ligi** [comment]
true - this can also be linked there - it would surface it more as you would see it when reporting an issue.
