### ISSUE TITLE
add PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#20023]
currently we do not have a PULL_REQUEST_TEMPLATE.md - we only have a ISSUE_TEMPLATE.md
a PULL_REQUEST_TEMPLATE could be helpful to improve the quality of PR-submissions and the whole PR process in general. E.g. encourage submitters to have tests in their PRs. This template can also point to: https://geth.ethereum.org/developers/Code-Review-Guidelines

**Comment by ligi** [comment]
new link here: https://geth.ethereum.org/docs/developers/code-review-guidelines

**Comment by adamschmideg** [comment]
We agreed we don't need a PR template because we assume contributors have already read the guidelines.
