### ISSUE TITLE
web3j whisper 

### ISSUE THREAD

**Issue by MrFanLee** [ethereum/go-ethereum#20031]
i use web3J sshpost to send a message, but geth return a exception :
invalid argument 0: json: cannot unmarshal string into Go struct field NewMessage.ttl of type uint32
this is my code:
```
ShhPost shhPost = new ShhPost(
                "0xb9cc8dbf9e2008f37f5b0a9c467020d658ba908c",
                "0xdc2841c89cdbe8b278cefd8fd6a71ed94eef629c",
                Arrays.asList(
                        "0x776869737065722d636861742d636c69656e74",
                        "0x4d5a695276454c39425154466b61693532"),
                "0x7b2274797065223a226d6a",
                Numeric.toBigInt("0x64"),
                Numeric.toBigInt("0x64"));
        admin.shhPost(shhPost).send().messageSent();
```
so what is wrong for my operation?

**Comment by WhiteRaBot17** [comment]
You are passing in a string, and need to pass in an uint32, and it looks like your first argument.

**Comment by MrFanLee** [comment]
> You are passing in a string, and need to pass in an uint32, and it looks like your first argument.

sorry，NewMessage.ttl is the last argument , in web3J, ttl is  Biginteger type. 
sshpost has fromaddress,toaddress,topics,payload,parity and ttl.

**Comment by WhiteRaBot17** [comment]
In order for the unmarshalling to be successful your input types must match the types that the struct expects.

It's hard to tell specifically, but I would test the types for the parity/ttl. If you are sending in uint32 try sending in as a string. If you are sending in a string send it in as uint32.

**Comment by gballet** [comment]
I can see two possible root causes for this issue.

  * The most likely is that you are adding the `0x` prefix in one (possibly all) string(s) that you are passing. I believe that it has a fix somewhere in the pipe, but before that fix, the RPC logic didn't like the `0x` prefix.
  * Otherwise, this is a web3j issue, in which case I recommend that you create an issue there.
