### ISSUE TITLE
website/docs: Update Install section

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20032]
- [x] Remove Install go, make it only a section
- [x] One page for Install
- [x] One page how to build
- [ ] Fix link to cross compile
- [x] Go version -> no specific, use the most recent one
- [x] Update PPA version -> no specifics, use the most recent one

**Comment by holiman** [comment]
build-page: https://geth.ethereum.org/docs/install-and-build/build-from-source
