### ISSUE TITLE
graphql: Return error locations and path

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20042]
The [GraphQL spec](https://graphql.github.io/graphql-spec/June2018/#sec-Errors) says 
> If an error can be associated to a particular point in the requested GraphQL document, it should contain an entry with the key locations with a list of locations, where each location is a map with the keys line and column, both positive numbers starting from 1 which describe the beginning of an associated syntax element.

And it says the same about the path to that field.

I run this query
```graphql
{
  block(hash: 99) {
    hash
}
```

This is what Geth returns now
```json
{
  "errors": [
    {
      "message": "Unexpected type for Bytes32: 99"
    }
  ],
  "data": {}
}
```

This is what I expect it to return
```json
{
  "errors": [
    {
      "message": "Unexpected type for Bytes32: 99",
      "locations": [ { "line": 2, "column": 15 } ],
      "path": [ "block", "hash" ]
    }
  ]}
```

#### System information

Geth version: `1.9.0-stable`
OS & Version: OSX

**Comment by yuzhoumao** [comment]
@adamschmideg from my understanding, this may require direct changes to the graph-gophers/graphql-go code, see e.g. #20114 for how the fix will roughly look like. I will create an issue there.

**Comment by adamschmideg** [comment]
@yuzhoumao cool. Once you created the issue, can you link it please?
