### ISSUE TITLE
graphql: Return Long for gas, gasUsed, cumulativeGasUsed, estimateGas, and status

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20040]
The current [GraphQL schema](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1767.md#schema) defines Long as a 64-bit unsigned integer.  The values of `gas`, `gasUsed`, `cumulativeGasUsed`, `estimateGas`, and `status` are now returned as BigInt encoded as a 0x-prefixed string. They should return a number instead.

Reproduce running this query
```graphql
query pending {
  block(number:1) {
    transactions {
      gas
      gasUsed
      cumulativeGasUsed
      status
    }
    estimateGas(data: {})
  }
}
```

**Comment by karalabe** [comment]
Unfortunately JavaScript does not support 64 bit ints, so we must return hex strings.

More details at https://github.com/graphql/graphql-spec/issues/73.

The schema should be changed.

**Comment by karalabe** [comment]
status should probably be an `int`? Does that support `null`?

**Comment by adamschmideg** [comment]
`status: Int` should be fine, it supports null (as opposed to `status: Int!` which makes it non-nullable)

**Comment by renaynay** [comment]
The following PRs have resolved this issue: 
https://github.com/ethereum/go-ethereum/pull/21883
https://github.com/ethereum/go-ethereum/pull/22153
