### ISSUE TITLE
Higher CPU usage with Geth 1.19.x

### ISSUE THREAD

**Issue by peterlayke** [ethereum/go-ethereum#20045]
G'day,

Just trying to see what the normal CPU usage is for a fast synced node. I've spun a new v1.9.2 node and I notice after sync the VM runs on roughly 60-80% CPU (Azure D4s v3 - 4vCPU, 16GiB mem) 

Previous version (1.8.x) sat on 40-60%, is anyone else getting this or is it by design? 

Thanks.

**Comment by karalabe** [comment]
So, in 1.9 we raised the default number of peers from 25 to 50. My bet is that the bump is caused by more network traffic and more network crypto. You could try running with `--maxpeers=25` to verify the old behavior.

**Comment by play0** [comment]
Thanks, for the suggestion. I've lowered maxpeers back to 25 and will leave soak for 24 hours. I will report back on my findings then.

**Comment by play0** [comment]
On initial look it seems CPU usage has dropped to 30/40% on idle. Good guess @karalabe  ;)

I remember reading (and forgive me if I get this wrong as it's been a long time) somewhere that Maxpeers had no effect on CPU just bandwidth, obviously this is not the case.

![image](https://user-images.githubusercontent.com/34048474/64666768-c5cb5500-d49a-11e9-8279-932aab5fa288.png)

**Comment by play0** [comment]
As you can see this has definately helped a lot as the server now bunces between 20 to 60%. 

Thanks for you help, this issue can be closed off.

![image](https://user-images.githubusercontent.com/34048474/64754550-20cc7d00-d56b-11e9-9c89-38b2c90c5ef7.png)

**Comment by karalabe** [comment]
Let's leave it open for now. CPU shouldn't be hit to hard, so I think it's
still a valuable issue (the root cause that is).

**Comment by AusIV** [comment]
I may have some insight into this.

At Rivet we manage several nodes, and found a number of issues relating to bad peers. We often see peers that are way behind on syncing, and aren't making any forward progress on syncing the blockchain. We have a script set up that will drop any peers that are more than a certain number of blocks behind *and* don't have their TD increase over a 5 minute period.

When we implemented this peer management script, we saw a significant decrease in the CPU utilization. It seems that these peers that are way behind and not making forward process are causing an uptick in CPU usage.

**Comment by offerm** [comment]
@AusIV can you share more information (or maybe the script itself?)?

How do you detect if the peer is behind and not making progress?
What does it mean to drop it? How do you  prevent it from reconnecting back?
What is TD?

Looks like this is exactly the problem I'm facting.

**Comment by soulmachine** [comment]
> AusIV

Hi @AusIV , Can you share your script? Thanks a lot, I'm having the same issue recently
