### ISSUE TITLE
can not load ABI containing fixed<M>x<N> types using abi.JSON

### ISSUE THREAD

**Issue by tzapu** [ethereum/go-ethereum#20044]
#### System information

Geth version: `v1.9.3`
OS & Version: used as go package

#### Expected behaviour
To be able to use any ABI containing any valid types.

#### Actual behaviour
When trying to load a JSON containing a fixed<M>x<N> type, `abi.JSON()` errors with `abi: error parsing variable size: strconv.Atoi: parsing "168x10": invalid syntax`

Found some TODOs here https://github.com/ethereum/go-ethereum/blob/5b0d3fa39359c027882705c221b6ddb5cd73f3d9/accounts/abi/type_test.go#L91

#### Steps to reproduce the behaviour
Use the ABI from here https://etherscan.io/address/0x652511ebd2c77aa00bc3f0b910928418708ad2ee#code
and 
```
unpackedABI, err := abi.JSON(strings.NewReader(theABIFromAbove))
log.Printf("%s", err)
```

thank you guys for all your hard work

**Comment by holiman** [comment]
```
  {
    "name": "fees",
    "outputs": [
      {
        "type": "fixed168x10",
        "name": "out"
      }
    ],
    "inputs": [
      {
        "type": "string",
        "name": "fee_name"
      }
    ],
    "constant": true,
    "payable": false,
    "type": "function",
    "gas": 1421
  },
```

**Comment by MariusVanDerWijden** [comment]
Will close this for now as it is not supported by solidity in any capacity. 
Once solidity supports fixed types we will implement it
