### ISSUE TITLE
Do not use reserved JSON-RPC error codes

### ISSUE THREAD

**Issue by BelfordZ** [ethereum/go-ethereum#20050]
#### System information

Geth version: all
OS & Version: all

#### Expected behaviour

Go ethereum returns errors whose code is not in the range -32768 to -32000 **inclusive**.

this means that the error defined as 
```json
{
  "code": -32000,
  "message": "Invalid input",
  "data": "- Missing or invalid parameters"
}
```

Should have a `code` that is 1 greater than the current greatest error code, so -32005

#### Actual behaviour

As described by (eip-1474)[https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md], -32000 is in use

#### Steps to reproduce the behaviour

call any json rpc method without parameters

```bash
curl -XPOST localhost:8545 -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id": 1, "method": "eth_getBlockByNumber", "params": []}'
```

#### Backtrace

````
[backtrace]
````

**Comment by adamschmideg** [comment]
To be fixed by #20117

**Comment by BelfordZ** [comment]
you close an issue before its fixed? how odd.

**Comment by adamschmideg** [comment]
I consider this issue to be a subset of the referred issue. Why have both open?

**Comment by BelfordZ** [comment]
because now I have to track a different issue that will take far longer to resolve than one individual error code that is more wrong than the others.

**Comment by BelfordZ** [comment]
all good though. Thanks for taking a look.

**Comment by holiman** [comment]
The thing is, we don't want to just "fix" one thing, if we do decide to make a change which breaks backwards compatibility. It's better to implement that EIP across the board. Then we can roll out the changes complete with documentation/warnings about what and why, in a new version number.

**Comment by BelfordZ** [comment]
Actually I've made a mistake on this one. Idk what I was thinking / reading lol.

Turns out pretty much all the error codes are pretty borked anyways. @holiman What you are saying also makes a lot of sense anyhow.

My apologies!
