### ISSUE TITLE
Integrate discover v5 with RLPx

### ISSUE THREAD

**Issue by WinstonPrivacy** [ethereum/go-ethereum#20055]
#### System information

Geth version: N/A
OS & Version: Linux
Commit hash : 

#### Expected behaviour

Nodes connecting via Discover v5 protocol should trigger RLPx communication (runPeer()).

#### Actual behaviour

Nodes negotiate a connection and move to "Known" state but never trigger RLPx. This is from a test project which works as expected using discv4.

#### Steps to reproduce the behaviour

This is a private project but the code is straightforward. We create two nodes and bootstrap one to the other. Tracing through the logging output, we have discovered that the nodes successfully negotiate the PING/PONG handshake and both move to the known state and wait indefinitely. A p2p Server is running and it sits in the run() loop, continuing to execute discovery lookup tasks but never receives a message on the srv.checkpointAddPeer channel, so it never triggers the runPeer() function.

```
		case c := <-srv.checkpointAddPeer:
			// At this point the connection is past the protocol handshake.
			// Its capabilities are known and the remote identity is verified.
			err := srv.addPeerChecks(peers, inboundCount, c)
```

This same project works fine if discv4 is used.

**Comment by WinstonPrivacy** [comment]
Digging deeper into this, it appears that discv5 is in a very incomplete state overall. Was wondering if someone could comment to provide more background?

The things that initially jump out at me are partial implementation of the discoverTable interface, lack of thread safety (mutexes around table buckets), and no ENR support in discv4 Node struct.

If these were added, it seems like it might be straightforward to send the discv5 table into newDialState. That would provide a path (maybe a completely working one) for discv5 to replace v4.

**Comment by fjl** [comment]
Closing this because things have changed a lot since this was opened. p2p/discv5 is officially deprecated and will be removed soon. We are working on the final version of discovery v5, with ENR support. The p2p dial infrastructure is now pluggable, providing ways to integrate other discovery mechanisms.
