### ISSUE TITLE
[Help!!]PendingTransactions can't be mined!!

### ISSUE THREAD

**Issue by ushiwak** [ethereum/go-ethereum#20057]
Hi there,

I'm a student running a **private network** with Geth.

I installed geth, and I try to send  transactions. First, I can mine some coins.Though, my transaction can't be mined. It reminds as sendingTransaction in many time.

How to solove it? Please help me!!

OS:windows 10
myGenesisfile
{
  "config": {
    "chainId": 15
  },
  "nonce": "0x0000000000000042",
  "timestamp": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "",
  "gasLimit": "0x8000000",
  "difficulty": "0x4000",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x3333333333333333333333333333333333333333",
  "alloc": {}
}

log
> eth.sendTransaction({from: eth.accounts[0], to:eth.accounts[1], value: web3.toWei(5, "ether")})
"0xcea578485e0be66e5c4ec44abd7df88c11f7d9c70586da5f4ddbdde01abee599"
> eth.pendingTransactions
[{
    blockHash: null,
    blockNumber: null,
    from: "0x637261b9dd94342eb2e0c5a52d514bdb1432bbf6",
    gas: 21000,
    gasPrice: 1000000000,
    hash: "0xcea578485e0be66e5c4ec44abd7df88c11f7d9c70586da5f4ddbdde01abee599",
    input: "0x",
    nonce: 0,
    r: "0xbab734cb1fa2835bdf6bafb13791299b9edef6f5b6d014c564afb368e4b27d6d",
    s: "0x5221d506bf649fcd73f56c7d96a3a23ebd3f780347d923619e8b3befcac75edc",
    to: "0x9e9503229c0ff47eed082de6bde51344d05f1656",
    transactionIndex: null,
    v: "0x41",
    value: 5000000000000000000
}]

I waited over 24 hours, but it can't be solved.This transaction reminds as sendingTransaction.

**Comment by ushiwak** [comment]
I have already delete that log...

I solved this problem to downgrade geth version for geth1.8.20.
I tried same way  for older version, transaction is approved quickly.

I think latest version of geth have some  trouble, but I didn't find what  is wrong.

**Comment by karalabe** [comment]
Unfortunately there's not much information to go with here. With some logs or inspections we could make some guesses. Given that the mentioned release is also ancient, it might have also been a regression fixed long ago.
