### ISSUE TITLE
err="leveldb/table: corruption on data-block

### ISSUE THREAD

**Issue by arunsybex** [ethereum/go-ethereum#20062]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth
Version: 1.9.3-stable
Git Commit: cfbb969da803d4cc92e1a64fc1b3c06db299b564
Architecture: amd64
Protocol Versions: [63]
Network Id: 1
Go Version: go1.11.5
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.11

#### Below issue I'm facing 

> CRIT [09-12|17:15:54.928] Failed to store last header's hash       err="leveldb/table: corruption on data-block (pos=19941): checksum mismatch, want=0xc802ab41 got=0xccf65f4e [file=012760.ldb]"

**Comment by arunsybex** [comment]
@karalabe  how to resolve it ?  Because blocks sync completed upto 80%.

**Comment by karalabe** [comment]
If the database is corrupted, there's not much you can do. If the disk is failing, you're out of luck, you need a new disk.
