### ISSUE TITLE
Feature Request: Stable GIT Tag

### ISSUE THREAD

**Issue by jleeh** [ethereum/go-ethereum#20074]
I build Geth server images by checking out the repo at a git branch/tag rather than using Docker. With this approach, I cannot build images at a stable version, rather have to lock to version or use master (unstable).

Proposal is to have a stable git tag like there is in Docker:
```
ethereum/client-go:stable
```

So I can then build from source by running:
```
git clone --branch stable --depth 1 https://github.com/ethereum/go-ethereum.git
cd go-ethereum
make geth
```

**Comment by karalabe** [comment]
`release/1.9`

**Comment by karalabe** [comment]
Though there's no cross-major-version-stable-branch.
