### ISSUE TITLE
Transactions are not processed after debug_setHead

### ISSUE THREAD

**Issue by ferranbt** [ethereum/go-ethereum#20078]
#### System information

Geth version: 1.9.3-unstable-22fdbee8-20190822
OS & Version: Ubuntu

#### Expected behaviour
During dev mode, after debug_setHead I should be able to send more transactions.

#### Actual behaviour
During dev mode, after debug_setHead I can send transactions but the call to eth_getTransactionsReceipt returns always "not found". There does not seem to be any block mined.

#### Steps to reproduce the behaviour
https://gist.github.com/ferranbt/4ab9730cf764eab0b44bae27cfc3b755

This gist reproduces the reported behavior. I send two transactions that create two new blocks, after that, I reset the blockchain with debug_setHead to the block number 1. Then, I send another transaction, it returns a hash but the transactions receipt returns always "not found".

This is the code I use to run geth in dev mode:
```
geth --dev --rpc --rpcapi eth,debug
```

**Comment by unparalleled-js** [comment]
I am having a similar issue where I run `deubg_setHead` and everything seems fine... Nonce values for accounts seem correct, etc.... but then I try to make a new transaction and I get `Nonce too low`

**Comment by cawabunga** [comment]
I'm struggling with the same issue. Looks like I don't understand how geth works. I found that `eth_getTransactionCount` returns different value for latest and pending block after `deubg_setHead` called.
