### ISSUE TITLE
karalabe/hid package not working on windows

### ISSUE THREAD

**Issue by benma** [ethereum/go-ethereum#20073]
There is a critical issue with the usb dependency on Windows. 
See https://github.com/karalabe/usb/issues/7

This affects the accounts/usbwallet subpackage (Trezor, Ledger integration).

Also, until this is fixed, Go projects using go-ethereum can't use karalabe/hid (where the issue is not present) at the same time due to the C libraries being the same (name clashes).

**Comment by karalabe** [comment]
Huh, didn't know about this issue. Will investigate and fix if it's borked for the next release.
