### ISSUE TITLE
Regenerated local transaction journal    transactions=0 accounts=0

### ISSUE THREAD

**Issue by Carey411** [ethereum/go-ethereum#20076]
hello everyone:
    my geth is running on window server, and i found that it sometime stoped and print log :
INFO [09-13|16:04:57.013] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-13|17:04:57.016] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-13|18:04:57.014] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-13|19:04:57.014] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-13|20:04:57.014] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-13|21:04:57.014] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-13|22:04:57.014] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-13|23:04:57.014] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-14|00:04:57.016] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-14|01:04:57.016] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-14|02:04:57.014] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-14|03:04:57.014] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-14|04:04:57.016] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-14|05:04:57.016] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-14|06:04:57.016] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-14|07:04:57.116] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-14|08:04:57.014] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-14|09:04:57.016] Regenerated local transaction journal    transactions=0 accounts=0
other info:
Geth version: 1.9.2-stable
OS & Version: Windows

I must restart geth to fix this . but I want to know how to fix this, and let geth don`t stop sync.
thanks.

**Comment by Carey411** [comment]
any one can help me?

**Comment by ligi** [comment]
is this happening with ethereum main net?

**Comment by Carey411** [comment]
> is this happening with ethereum main net?

yes, main net. and every time happend this ,i have to restart geth.

**Comment by ligi** [comment]
If this happens - can you connect to the geth instance to get a stacktrace?

**Comment by holiman** [comment]
So, the message does not indicate an error, it's an jourly rotation of the transaction journal. The real error is that nothing else is happening. When this happens, it would be good to know what happens. 
We can figure this out by `debug.stacks()`, or `build/bin/geth attach /path/to/geth.ipc --exec "debug.stacks()"`

**Comment by karalabe** [comment]
There's not enough information to proceed with this issue. There are two possible cases: no peers or deadlock. For the former, we've added a while back a feature to keep printing "Looking for peers" if there are only a few connections, to let the user know there's a network issue. In the second case we need the stack traces to see what's stuck and where.

**Comment by sahityakumarsuman** [comment]
can someone give the solution for this, everyone is just trying to explain the problem .... please provide solution out of it.

**Comment by leetakchun** [comment]
After update to new geth version (1.10.20-stable), it will also get "Regenerated local transaction journal transactions=0 accounts=0".
Restart the geth.service will solve that issue and get "imported new chain segment" again.
For reference, about to setup the geth.service, please check : https://pawelurbanek.com/ethereum-node-aws
