### ISSUE TITLE
Synchronisation failed, retrieved hash chain is invalid

### ISSUE THREAD

**Issue by 9974** [ethereum/go-ethereum#20087]
geth 1.9.2 , when i syncing  the block  8530849 ,  always sync failed,   retrieved hash chain is invalid,  this is the error log 

```
WARN [09-18|18:57:40.708] Synchronisation failed, dropping peer    peer=009a99b4a64fb46e err="retrieved hash chain is invalid"
WARN [09-18|18:57:59.374] Checkpoint challenge timed out, dropping id=2d1f1ff277435247 conn=dyndial addr=35.158.244.151:30303 type=Geth/v1.9.4-unstable-db9c6b0f-20190918/linux-amd64/go1.13
WARN [09-18|18:58:44.349] Synchronisation failed, dropping peer    peer=2d1f1ff277435247 err=timeout
huike0429@huike0429:~$ retrieved hash chain is invalidretrieved hash chain is invalidSynchronisation failed
```

**Comment by karalabe** [comment]
There are a few reasons why that could happen. E.g. a peer we're syncing from disconnects at a strange place in the code. If it's consistently not going away, please run with `--vmodule=downloader=5` to log out what's the syncer is doing and please share it.

**Comment by holiman** [comment]
These are pretty common warnings, telling notifying you about peers that aren't on the same chain as you, or are not responsive. Since OP hasn't responded, I'm closing
