### ISSUE TITLE
When I run " make geth-windows "  this error is happened , why? 

### ISSUE THREAD

**Issue by YongilChoi** [ethereum/go-ethereum#20093]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: 1.9.1-stable 
OS & Version:  Ubuntu 19.04 
Commit hash : (if `develop`)

#### Expected behaviour
if I run " make geth-windows" , 
builder should make geth.exe on linux ,, /build/bin/ 

#### Actual behaviour

compile error. 

#### Backtrace

````
[backtrace]
````

# github.com/ethereum/go-ethereum/vendor/github.com/karalabe/usb
In file included from /usr/share/mingw-w64/include/objbase.h:14:0,
                 from /usr/share/mingw-w64/include/ole2.h:17,
                 from /usr/share/mingw-w64/include/wtypes.h:12,
                 from /usr/share/mingw-w64/include/winscard.h:10,
                 from /usr/share/mingw-w64/include/windows.h:97,
                 from ../../vendor/github.com/karalabe/usb/libusb/libusb/libusb.h:76,
                 from ../../vendor/github.com/karalabe/usb/libusb/libusb/libusbi.h:39,
                 from ../../vendor/github.com/karalabe/usb/libusb/libusb/os/poll_windows.c:43,
                 from ../../vendor/github.com/karalabe/usb/libs.go:41:
/usr/share/mingw-w64/include/oledlg.h:428:3: error: unknown type name 'interface'
   DECLARE_INTERFACE_(IOleUILinkContainerW,IUnknown) {
   ^
/usr/share/mingw-w64/include/oledlg.h:428:3: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
   DECLARE_INTERFACE_(IOleUILinkContainerW,IUnknown) {

**Comment by karalabe** [comment]
If you want to run on Windows, please build on Windows for now. I can try to take a peek into the cross compiler, but it's really low priority.

**Comment by bobcodz** [comment]
Have got the same issue when I try go run a simple project on windows.. 

Used to work before.

**Comment by hunjixin** [comment]
same error

**Comment by gpersoon** [comment]
I just figured out how to compile on windows: https://github.com/ethereum/go-ethereum/issues/20121#issuecomment-545793038

**Comment by charliehorse55** [comment]
This is fixed when using a mingw version 6+. Versions of Ubuntu earlier than 19.04 have mingw ver. 5 in the package manager. I ran into this problem, found a comment on another issue (https://github.com/vipnode/vipnode/issues/82#issuecomment-562785760) and tried installing a version 6 backport: https://launchpad.net/~mati865/+archive/ubuntu/mingw-w64

As soon as I installed mingw 6, everything compiled nicely.

**Comment by vkuznecovas** [comment]
Can confirm that gcc 8+ and mingw 6+ seems to solve this, thanks @charliehorse55

**Comment by ligi** [comment]
@YongilChoi do you still have this issue? Or did the solution from @charliehorse55 work for you?

**Comment by MariusVanDerWijden** [comment]
I have a similar issue when running with gcc 10.2 mingw-w64-gcc-10.2
```
# github.com/karalabe/usb
In file included from /usr/share/mingw-w64/include/objbase.h:14:0,
                 from /usr/share/mingw-w64/include/ole2.h:17,
                 from /usr/share/mingw-w64/include/wtypes.h:12,
                 from /usr/share/mingw-w64/include/winscard.h:10,
                 from /usr/share/mingw-w64/include/windows.h:97,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libusb/libusb/libusb.h:76,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libusb/libusb/libusbi.h:39,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libusb/libusb/os/poll_windows.c:43,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libs.go:41:
/usr/share/mingw-w64/include/oledlg.h:428:3: error: unknown type name 'interface'
   DECLARE_INTERFACE_(IOleUILinkContainerW,IUnknown) {
   ^
/usr/share/mingw-w64/include/oledlg.h:428:3: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
   DECLARE_INTERFACE_(IOleUILinkContainerW,IUnknown) {
   ^
In file included from /usr/share/mingw-w64/include/setupapi.h:27:0,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libusb/libusb/os/windows_winusb.c:29,
                 from /go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libs.go:55:
/usr/share/mingw-w64/include/oledlg.h:429:31: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD(QueryInterface)(THIS_ REFIID riid,LPVOID *ppvObj) PURE;
                               ^
/usr/share/mingw-w64/include/oledlg.h:430:30: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
                              ^
/usr/share/mingw-w64/include/oledlg.h:431:31: error: expected declaration specifiers or '...' before 'IOleUILinkContainerW'
     STDMETHOD_(ULONG,Release)(THIS) PURE;
```

**Comment by charliehorse55** [comment]
What version of mingw is that?

**Comment by MariusVanDerWijden** [comment]
@charliehorse55 I think it is 8, it's this one https://www.archlinux.org/packages/community/x86_64/mingw-w64-gcc/

**Comment by YongilChoi** [comment]
p{margin-top:0;margin-bottom:0}
    


    I did not solve the issue,, Just build native

go build..  folder names..



 소리노리닷컴(주) 서울사무실: 우) 06069 서울 강남구 선릉로 704  청담벤처프라자 12층 256호 Fax: 02-544-6699Sorynory.com smart hearing aids,   smart ears :  

http://youtu.be/rbGmItvVOo0

From Yong il Choi.    www.sorynory.com   My Skype id: hurstchoi2013My Cell: 82-10-9769-4876

--------- 원본 메일 ---------

    
        보낸사람: ligi <notifications@github.com>
        받는사람: ethereum/go-ethereum <go-ethereum@noreply.github.com>
        
            참조: 최용일 <hurstchoi@daum.net>, Mention <mention@noreply.github.com>
        
        날짜: 20.12.17 18:30 GMT +0900
        제목: Re: [ethereum/go-ethereum] When I run " make geth-windows "  this error is happened , why?  (#20093)
        
        
    
    
        
@YongilChoi do you still have this issue? Or did the solution from @charliehorse55 work for you?

**Comment by holiman** [comment]
Whatever build problem we have on windows now, I don't think they have any relation to build issues in 2019. Closing.
