### ISSUE TITLE
net.peerCount not increasing

### ISSUE THREAD

**Issue by osiztechnologies** [ethereum/go-ethereum#20101]
We have used geth-1.8.27 package with syncmode=light. Last two net.peerCount not increasing.

sometimes we got "Sorry, We are unable to locate this TxnHash." from Etherscan.

FYI - https://etherscan.io/tx/0xc633e8e89544ea19e072eff295eedf5bfba7d64074a91178f5b9c402068bc1fa

Kindly advise us how to overcome this issue.

**Comment by karalabe** [comment]
Does this happen with latest release? Please post some logs.

**Comment by OliverBui** [comment]
After upgrade to version 1.9.5, i have same issue: `no suitable peers available`. my `net_peerCount` is alway 0. My node using Light version

**Comment by osiztechnologies** [comment]
@karalabe After upgrade to new version 1.9.5. we have faced same issue. 

net_peerCount = 0 & "Sorry, We are unable to locate this TxnHash"

**Comment by osiztechnologies** [comment]
@karalabe could you please share the static node peers to increase net.peerCount.

**Comment by osiztechnologies** [comment]
@karalabe could you please share the static node peers to increase net.peerCount.

**Comment by karalabe** [comment]
We're always trying to improve light clients and peering, but at the end of the day only a few people run light servers and you need to wait it out until you connect to one (or run your own light server). We're also introducing DNS discovery for the light client which should help even more.

**Comment by piratoskratos** [comment]
I'm not sure we can say this is a "closed issue". 

No peer on a light client : it's real problem.

I'm running 2 geth in light mode. On both it's the same, it's mostly between 0 to 2 peers maximum.... So when we don't have any peers our client is just useless and it could take hours before getting any peer. I don't think it's OK. :-1:

**Comment by karalabe** [comment]
@piratoskratos Feel free to run a full node and a light server so the situation improves for others. If you are not willing to serve others, why do you expect others to do it for you? Yes, the situation is a bit crappy, but it's not a technical problem that we can address.

**Comment by piratoskratos** [comment]
Full node is a lot of space, more bw & cost which is not accessible to all; that's why the light mode exist, so it's supposed to be working ok, IMO. I absolutely don't know the ratio full/light on the network but I hope isnt so bad... or we should found a solution to help this mode running ok.

I'll try to run a full node somewhere if it's help. :+1:

**Comment by osiztechnologies** [comment]
We have used updated version of v1.9.17. But peercount showing 0 only. Kindly guide me to solve this issue.
