### ISSUE TITLE
block age raises unexpectedly while blocknr is progressing after deep froze chain segment  

### ISSUE THREAD

**Issue by ethernian** [ethereum/go-ethereum#20109]
#### System information
Geth version: `geth-windows-amd64-1.9.5-a1c09b93`
OS & Version: Windows

#### Expected behaviour
while blocknumber increases block age should reduce

#### Actual behaviour
unexpected increasing of block age while blocknumber is counting

#### Backtrace
![image](https://user-images.githubusercontent.com/4574735/65373574-ae9d1c00-dc7f-11e9-9c5d-b0d494415709.png)

````
INFO [09-21|11:37:09.215] Imported new chain segment               blocks=9   txs=1549 mgas=66.127  elapsed=8.081s    mgasps=8.182  number=8560312 hash=6e781e…9a7f7f age=4d21h49m dirty=774.65MiB
INFO [09-21|11:37:13.711] Deep froze chain segment                 blocks=124 elapsed=234.758ms number=8470324 hash=c25ed3…6515e1
INFO [09-21|11:37:17.374] Imported new chain segment               blocks=21  txs=2830 mgas=156.304 elapsed=8.159s    mgasps=19.157 number=8560333 hash=528ac3…392410 age=5d38m57s dirty=776.92MiB
INFO [09-21|11:49:20.868] Regenerated local transaction journal    transactions=0 accounts=0
```

**Comment by holiman** [comment]
Wow, that's quirky! Tried to, but failed, to reproduce. Really curious how that happened...

**Comment by karalabe** [comment]
Funky. I don't see how this could happen based on our code tbh :| Checked the blocks on Etherscan, the timestamps are incremental there. We just report `time.Since(timestamp)`. Which version of Go are you running?

**Comment by adamschmideg** [comment]
We have not enough information to explore it further.

**Comment by cryptodatawizard** [comment]
I have the same problem, any new information on this ?
