### ISSUE TITLE
Merge old Windows build documentation to new website

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20116]
from https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows to https://geth.ethereum.org/install-and-build/Installing-Geth#build-it-from-source-code

**Comment by fjl** [comment]
It would be nice to have a dedicated section for Windows that explains the installer, etc.

**Comment by MariusVanDerWijden** [comment]
It was moved here: https://geth.ethereum.org/docs/install-and-build/installing-geth#windows
