### ISSUE TITLE
accounts/abi unpack doesn't correctly create zero *big.Int values

### ISSUE THREAD

**Issue by Smilenator** [ethereum/go-ethereum#20118]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version 1.9.1`
OS & Version: Linux

#### Expected behaviour

the following test should pass:
```go
unpackTest{
	def:  `[{"type": "uint256[3]"}]`,
	enc:  "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002",
	want: [3]*big.Int{big.NewInt(0), big.NewInt(1), big.NewInt(2)},
}
```

#### Actual behaviour

go-ethereum/accounts/abi/unpack_test.go:433: test 36 ([{"type": "uint256[3]"}]) failed: expected [0 1 2], got [0 1 2]

deeper analysis shows that zeros' nat slices are not the same (empty slice vs nil slice):
expected: big.Int{neg:false, abs:big.nat(nil)}
got  : big.Int{neg:false, abs:big.nat{}}

#### Steps to reproduce the behaviour

changed the unpackTest in go-ethereum/accounts/abi/unpack_test.go:244 to the above test

#### Backtrace

````
[backtrace]
````

**Comment by rjl493456442** [comment]
Should be fixed during the refactor. See #20275

**Comment by adamschmideg** [comment]
This causes a problem only in the test, not in the production code.

**Comment by MariusVanDerWijden** [comment]
Hey @Smilenator 
Unfortunately this is not an issue with go-ethereum but with golang in general. 
The internal presentation of big.Int(0) differs on how the integer was created. 
I think this is an oversight of the golang developers and should be fixed upstream. 
They seem to be against that change though, see: https://github.com/golang/go/issues/27379

**Comment by MariusVanDerWijden** [comment]
We could use the go-cmp package as suggested in the answer, however it is rather lenient and some encoding errors might slip by.
