### ISSUE TITLE
Failed to open master .. masterseed.json.. has insecure file permissions

### ISSUE THREAD

**Issue by gpersoon** [ethereum/go-ethereum#20123]
#### System information
```JS
geth version
Geth
Version: 1.9.5-stable
Git Commit: a1c09b93871dd3770adffb177086abda1b2ff3af
Git Commit Date: 20190920
Architecture: amd64
Protocol Versions: [63]
Network Id: 1
Go Version: go1.13
Operating System: windows
GOPATH=C:\Users\...\go
GOROOT=C:\Go\
```
```JS
clef -v
Clef version 0.0.0
```
#### Expected behaviour
Clef can use masterseed.json on windows

#### Actual behaviour
When starting clef.exe on windows the following error is shown:
```JS
WARN [09-24|17:00:39.980] Failed to open master, rules disabled    
err="file (C:\\Users\\...\\AppData\\Roaming\\Signer\\masterseed.json) 
has insecure file permissions (-rw-rw-rw-)"
```
When masterseed.json is made read only, the message changes to:
```JS
WARN [09-24|17:06:55.978] Failed to open master, rules disabled    
err="file (C:\\Users\\...\\AppData\\Roaming\\Signer\\masterseed.json) 
has insecure file permissions (-r--r--r--)"
```

However there is no way to get to the required security of the file, even changing or deleting all the windows rights doesn't help.

#### Steps to reproduce the behaviour
On windows: do clef init and then start clef

#

**Comment by ligi** [comment]
can't you give read permissions to just the user on windows?

**Comment by gpersoon** [comment]
You can adjust the permissions using the "windows" way, however the linux way to query the access rights gives different results. I've tried setting the access rights in multiple ways, but clef wasn't happy with any of them.

**Comment by sunilkumarsistla** [comment]
```chmod 400 <filepath>``` helped me to get rid of the prompt 
but i'm not sure how to use/ prepare the **signersecret** value file path and the contents inside file

**Comment by ralph-pichler** [comment]
this issue still exists in the latest version of clef. has anyone been able to set permissions correctly?

**Comment by lmj0011** [comment]
@ralph-pichler

If you're on Windows this [PR](https://github.com/ethereum/go-ethereum/pull/22251) is suppose to fix the issue, but if you're on Unix/Linux the permission is [0400](https://github.com/ethereum/go-ethereum/blob/v1.9.25/cmd/clef/main.go#L808)

so you would have to do something like this on the command line (Linux):

```bash
~/.clef$ ls -al /home/user/.clef/masterseed.json 
-rwxrwxrwx 1 user user 868 Jan 26 22:58 masterseed.json

~/.clef$ chmod 400 /home/user/.clef/masterseed.json 

~/.clef$ ls -al /home/user/.clef/masterseed.json 
-r-------- 1 user user 868 Jan 26 22:58 masterseed.json
```

worth noting that permissions for the `masterseed.json` or any file will probably get changed when moving it to different location on your computer.
