### ISSUE TITLE
Rinkeby gas limit increase request

### ISSUE THREAD

**Issue by rstormsf** [ethereum/go-ethereum#20129]
I understand that it's probably not the best place to reach out to rinkeby validators, but I have no idea where the community forum/chat for rinkeby validators is. 
Anyway, since ETH has 10MM gas limit, I think it makes sense for rinkeby to match the same gas limit, so that dapp developers can have exact same experience. 

Kovan validators are already in the process of increasing the gas limit it. 
https://kovan-netstat.poa.network/

**Comment by ligi** [comment]
maybe bring it up here: https://discordapp.com/channels/482467812179181568/482483750194774017

**Comment by Nguyentiensy99** [comment]
Ok
