### ISSUE TITLE
Clef tutorial : no "nc -U" available for windows

### ISSUE THREAD

**Issue by gpersoon** [ethereum/go-ethereum#20124]
#### System information
Windows 10

#### Expected behaviour
The tutorial https://geth.ethereum.org/clef/Tutorial is usable on Windows

#### Actual behaviour
The tutorial contains the following part:
```JS
echo .... | nc -U ~/.clef/clef.ipc
```
This requires the command "nc -U".  Although some versions of nc exist for windows, i haven't been able to find a version that supports named pipes.

#### Suggested solution
Use putty ( https://www.putty.org ) to interact with named pipes.
Start clef in the following way:
```JS
clef --ipcpath \\.\pipe\clef.ipc
```
In putty:
* at Host Name, enter \\.\pipe\clef.ipc
* at Connection type, select "Serial"
* at Close window on exit, select "Never"
![image](https://user-images.githubusercontent.com/5469459/65525589-0d68cc80-def0-11e9-93fe-c048dac1958c.png)

Click open to start a session. 
In the terminal window paste:
```JS
{"id": 1, "jsonrpc": "2.0", "method": "account_list"}
```
And observe the clef.exe screen.

**Comment by ligi** [comment]
thanks for the report. Just wondering if Cygwin would be a better option so the documentation does not have to be changed/complicated too much. cc @holiman

**Comment by gpersoon** [comment]
I've tried the nc from Cygwin. It does indeed have the -U option. However it doesn't work in windows:

![image](https://user-images.githubusercontent.com/5469459/65613304-11f7b880-dfb6-11e9-9c4d-a3a6cbbf992c.png)

Clef is showing the error:
```JS
DEBUG[09-25|16:59:17.150] RPC connection read error                err=EOF
```

**Comment by ligi** [comment]
dam - perhaps @FrankSzendzielarz has some idea - AFAIK he is the only one using windows in the team.

**Comment by manzier** [comment]
Having any direction to go is better than nothing at all.  This at least clued me in a bit.   The bar is a little high for understanding for a windows admin it seems.

**Comment by manzier** [comment]
curl may work

**Comment by holiman** [comment]
I don't think we have a lot of windows-users of clef. If we do, I welcome someone at some point helping out with the docs, for now I choose to close tihs stale ticket.
