### ISSUE TITLE
Clef: Fatal: Could not start IPC api: Invalid pipe address '%appdata%\Signer\clef.ipc'

### ISSUE THREAD

**Issue by gpersoon** [ethereum/go-ethereum#20121]
#### System information
```JS
geth version
Geth
Version: 1.9.5-stable
Git Commit: a1c09b93871dd3770adffb177086abda1b2ff3af
Git Commit Date: 20190920
Architecture: amd64
Protocol Versions: [63]
Network Id: 1
Go Version: go1.13
Operating System: windows
GOPATH=C:\Users\...\go
GOROOT=C:\Go\
```
```JS
clef -v
Clef version 0.0.0
```

#### Expected behaviour
Clef works with default (pipe) configuration on windows.

#### Actual behaviour

When clef is started without parameters, the following error is shown:
```JS
...
Fatal: Could not start IPC api: Invalid pipe address 'C:\Users\...\AppData\Roaming\Signer\clef.ipc'.
```

#### Steps to reproduce the behaviour
On windows, start clef.exe

#### Workaround
When clef is started with a windows type pipe config (similar like geth is using), it works fine:
```JS
clef --ipcpath \\.\pipe\clef.ipc

....
INFO [09-24|16:51:20.368] IPC endpoint opened                      url=\\\\.\\pipe\\clef.ipc
```

**Comment by ligi** [comment]
@gpersoon can you verify this solves your issue?

**Comment by gpersoon** [comment]
@ligi : be happy to. 
@holiman: can I get a compiled clef.exe somewhere? (i tried compiling it myself but got a bit stuck)

**Comment by ligi** [comment]
@gpersoon great! wonder where you got stuck in compiling though

**Comment by gpersoon** [comment]
@ligi the last thing i go stuck in is: cmd\clef\main.go:46:2: use of internal package github.com/ethereum/go-ethereum/internal/ethapi not allowed

**Comment by ligi** [comment]
@gpersoon did you follow this instructions to build? https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows#compiling-geth-with-tools-from-chocolatey

**Comment by gpersoon** [comment]
@ligi : I can confirm the invalid pipe address issue is solved.

I was able to compile clef in the following way:
```JS
cd %GOPATH%
mkdir src\github.com\ethereum
git clone https://github.com/holiman/go-ethereum  src\github.com\ethereum\go-ethereum
cd src\github.com\ethereum\go-ethereum
git checkout fix_windows_clefpath
go build -v ./cmd/clef
```

The windows install instructions are not exact. Here is an alternative:
```JS
cd %GOPATH%
mkdir src\github.com\ethereum
git clone https://github.com/ethereum/go-ethereum src\github.com\ethereum\go-ethereum
cd src\github.com\ethereum\go-ethereum
go install -v ./cmd/clef
rem The resulting executable is located at %GOPATH%\bin, which is already part of Path
```

**Comment by ligi** [comment]
@gpersoon great! thanks for confirming the fix worked
