### ISSUE TITLE
-pkg option broken again

### ISSUE THREAD

**Issue by gballet** [ethereum/go-ethereum#20128]
There seems to be either a regression or an incomplete fix with recent version of geth, where it's no longer possible to pipe the abi from `stdin`. This is the tracking issue. Thanks to @hkalodner for reporting it. This should have been fixed when #19292 was fixed, somehow it's broken again.

#### System information

Geth version: 1.9.5-unstable-24ef8351-20190919
OS & Version: Linux

#### Expected behaviour

No error

#### Actual behaviour

```
Fatal: Failed to generate ABI binding: json: cannot unmarshal object into Go value of type []struct { Type string; Name string; Constant bool; Anonymous bool; Inputs []abi.Argument; Outputs []abi.Argument }.
```

#### Steps to reproduce the behaviour

```
echo '{"contracts":{"test.sol:Test":{"abi":"[]","bin":"6080604052348015600f57600080fd5b50603580601d6000396000f3fe6080604052600080fdfea165627a7a723058204607ea1e116ed157fa353615ead6dab3b941f6c06adf7c0e724273ad8ca0a9c80029","devdoc":"{\"methods\":{}}","userdoc":"{\"methods\":{}}"}},"version":"0.5.3+commit.10d17f24.Linux.g++"}' | abigen --abi - --pkg test
```

**Comment by MariusVanDerWijden** [comment]
@gballet The following command works for me 
`echo '[{"constant":true,"inputs":[{"name":"i","type":"uint256"},{"name":"j","type":"uint256"}],"name":"foo","outputs":[],"payable":false,"stateMutability":"pure","type":"function"},{"constant":true,"inputs":[{"name":"i","type":"uint256"}],"name":"foo","outputs":[],"payable":false,"stateMutability":"pure","type":"function"},{"anonymous":false,"inputs":[{"indexed":false,"name":"i","type":"uint256"}],"name":"bar","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"i","type":"uint256"},{"indexed":false,"name":"j","type":"uint256"}],"name":"bar","type":"event"}]' | abigen --abi - --pkg test
`
How did you generate your input?

**Comment by vsbogd** [comment]
@gballet, looks like my test is not actual anymore, because in latest versions of `abigen` the combined JSON which is used in test should be passed via separate command line parameter: `--combined-json`. And this parameter gets data from file only not from STDIN. So more accurate version of the test for the version 1.9.15 for example is:

```sh
echo '{"contracts":{"test.sol:Test":{"abi":"[]","bin":"6080604052348015600f57600080fd5b50603580601d6000396000f3fe6080604052600080fdfea165627a7a723058204607ea1e116ed157fa353615ead6dab3b941f6c06adf7c0e724273ad8ca0a9c80029","devdoc":"{\"methods\":{}}","userdoc":"{\"methods\":{}}"}},"version":"0.5.3+commit.10d17f24.Linux.g++"}' > combined.json
abigen --combined-json combined.json --pkg test
```

which works.

**Comment by MariusVanDerWijden** [comment]
Seems to fixed by now
