### ISSUE TITLE
'admin_chainSyncStatus method not implemented'

### ISSUE THREAD

**Issue by Ryanmtate** [ethereum/go-ethereum#2012]
I am using the IPC socket to send the method; it returns:

```
{ id: 1, jsonrpc: '2.0',error: { code: -32601, message: 'admin_chainSyncStatus method not implemented' } }
```

payload looks like: 

```
{jsonrpc: '2.0',method: 'admin_chainSyncStatus',params: [],id: 1};
```

Is the method no longer implemented?

Thanks,

Ryan

**Comment by bas-vk** [comment]
This method has been standardised. Take a look at [`eth_syncing`](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_syncing).

**Comment by Ryanmtate** [comment]
Thanks, will update my code base.

**Comment by knocte** [comment]
What does standardised mean? If it means "obsolete", probably it should be removed from the docs then (wiki).

**Comment by bas-vk** [comment]
It means that it is part of the official API Ethereum nodes need to offer to be compliant. In this case the name has changed from `admin_chainSyncStatus` to `eth_syncing`. Could you point to the places in the wiki that where this old function is still mentioned?

**Comment by knocte** [comment]
Sure: https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#adminchainsyncstatus
