### ISSUE TITLE
Failing transaction goes through in simulated back-end

### ISSUE THREAD

**Issue by Pet3ris** [ethereum/go-ethereum#20138]
Hi there,

I'm trying to call `SendTransaction` with a reverting transaction but able to do so successfully? Should a reverting transaction cause a runtime exception in the simulated back-end or is this intended behavior? If it's indended, are there other ways to force a reverting transaction to signal errors?

#### System information

Geth version: `1.9.5`
OS & Version: OSX 10.14.3
Commit hash : (if `develop`)

#### Expected behaviour

Transaction should revert and cause a `panic` or runtime error.

#### Actual behaviour

Transaction succeeds and there is a `nil` error message.

#### Steps to reproduce the behaviour

I'm using `sendTransaction` to issue a contract transaction and then calling `sim.Commit()`. This is done with a contract that will revert upon that transaction.

#### Backtrace

n/a

**Comment by karalabe** [comment]
Why would a failing transaction cause a panic? The EVM executes, finishes execution potentially with an error, and that failure is recorded in the chain, as with all private, test and mainnets.

**Comment by Pet3ris** [comment]
Not saying it should! I was worried when my transaction didn't fail because I assumed that since simulated back-end is built for testing the behavior could be similar to `web3.js` or `web3.py`.

Just to clarify - is the best way to check transaction success to check the `status` field of the transaction receipt?

**Comment by gitteri** [comment]
@Pet3ris I believe the sim is acting as intended. Since the transaction is put into a block and the chain continues, it wouldn't make sense to return an error in this case. The best way to check for the reversion is to check the status as you mentioned

**Comment by Pet3ris** [comment]
Thank you @gitteri - do you know where the status is provided in the API? I couldn't find a way to extract it.

**Comment by adamschmideg** [comment]
The original question is answered. If you still have a problem, please open a new issue.
