### ISSUE TITLE
byzantiumBlock config breaks contract calls

### ISSUE THREAD

**Issue by naddison36** [ethereum/go-ethereum#20137]
#### System information

Geth version: 1.9.4-stable
OS & Version: OSX

#### Expected behaviour

call the `getOwner()` function in the below contract should return the address of the account that deployed the contract (msg.sender).

```Solidity
pragma solidity ^0.5.11;
contract GethTest
{
    address private _owner = msg.sender;
    function getOwner() external returns (address) {
        return _owner;
    }
}
```

#### Actual behaviour

calling `getOwner()` returns `0x0000000000000000000000000000000000000000` when the genesis.json file contains config `"byzantiumBlock": 0`.
Remove the `"byzantiumBlock": 0` config and calls to the `getOwner()` function behave as expected, but that means the transaction receipt does not include the `status` field.

#### Steps to reproduce the behaviour

Run a local Geth with `genesis.json` file
```json
{
  "config": {
    "chainID": 8998,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 1000
  },
  "nonce": "0",
  "difficulty": "0x400",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "timestamp": "0x00",
  "extraData": "",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x989680",
  "alloc": {
    "0x19E7E376E7C213B7E7e7e46cc70A5dD086DAff2A": {
      "balance": "10000000000000000000000000"
    }
  }
}
```

Deploy the above contract to the local Geth node. For example
`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf903270180839896808080b902d7608060405234801561001057600080fd5b506040516102b73803806102b78339818101604052602081101561003357600080fd5b505160018054600160a060020a031916600160a060020a03909216919091179055610254806100636000396000f3fe608060405234801561001057600080fd5b5060043610610073577c010000000000000000000000000000000000000000000000000000000060003504630178b8bf81146100785780633b3b57de146100b1578063893d20e8146100ce578063a2236399146100d6578063d5fa2b00146100f3575b600080fd5b6100956004803603602081101561008e57600080fd5b5035610121565b60408051600160a060020a039092168252519081900360200190f35b610095600480360360208110156100c757600080fd5b5035610126565b610095610141565b610095600480360360208110156100ec57600080fd5b5035610150565b61011f6004803603604081101561010957600080fd5b5080359060200135600160a060020a031661016b565b005b503090565b600090815260208190526040902054600160a060020a031690565b600154600160a060020a031690565b600060208190529081526040902054600160a060020a031681565b600154600160a060020a031633146101e457604080517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152601160248201527f4d75737420626520746865206f776e6572000000000000000000000000000000604482015290519081900360640190fd5b600091825260208290526040909120805473ffffffffffffffffffffffffffffffffffffffff1916600160a060020a0390921691909117905556fea265627a7a72315820f5399786b33856b8bc405f77650fddf1b582c6937032ac58d04281c8e5a0057764736f6c634300050b00320000000000000000000000001563915e194d8cfba1943570603f7606a311550882466fa0439c608955195990792066f9acfce219f3960692ab1e0c5d0bb9c7c5f4f78fdba05e687b586061434cb058c72a6a861c845187dc11090c26dd74a43480564e4979"],"id":"1"}' http://127.0.0.1:8545`

Call the `getOwner()` function which will incorrectly return `0x0000000000000000000000000000000000000000`. For example
`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0x1563915e194D8CfBA1943570603F7606A3115508","to":"0x93FEB81f0d93A45A7cd5d0f296bD3915Fa437585","data":"0x893d20e8"},"latest"],"id":"2"}' http://127.0.0.1:8545`

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
There was a bug in 1.9.4 that resulted in the state being corrupted. v1.9.5 was released a day after 1.9.4 as a hotfix. Please update https://github.com/ethereum/go-ethereum/releases/tag/v1.9.5

**Comment by naddison36** [comment]
How do I upgrade to Geth v1.9.5 using brew?

I've tried installing the latest
```bash
brew tap ethereum/ethereum
brew install ethereum
```

upgrading
```bash
brew update && brew upgrade
```

upgrading the minor version
```bash
brew update && brew reinstall ethereum
```

All leave me on geth 1.9.4-stable

**Comment by naddison36** [comment]
I've also tried the following as per https://github.com/ethereum/homebrew-ethereum#development
```
brew reinstall ethereum --devel
```
But that fails with `Error: invalid option: --devel`

**Comment by naddison36** [comment]
I worked out how to upgrade Geth using brew
```
brew uninstall ethereum
brew install ethereum
```

I'm now on `1.9.5-stable` which fixes my original problem

Thanks

**Comment by karalabe** [comment]
Sorry about that. When we pushed the 1.9.5 stable release, we forgot to bump homebrew. Just did that now. You don't need `devel`.
