### ISSUE TITLE
Internal types used for RPC call return values and arguments in ethapi/api.go

### ISSUE THREAD

**Issue by i-norden** [ethereum/go-ethereum#20131]
#### System information

Geth version: latest

#### Expected behaviour

According to `rpc/doc.go`
```
Methods that satisfy the following criteria are made available for remote access:

 - method must be exported
 - method returns 0, 1 (response or error) or 2 (response and error) values
 - method argument(s) must be exported or builtin types
 - method returned value(s) must be exported or builtin types
```

#### Actual behaviour

The `internal/ethapi/api.go` exposes a number of RPC methods which return types that are not exported since they are defined in the internal directory. Namely, the `GetProof` method which returns [AccountResult](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L542) type, the handful of methods which return the [RPCTransaction](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1084) type, and the `SignTransaction` method which returns the [SignTransactionResult](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1536) type. 

There are also some arguments for the RPC methods in `internal/ethapi/api.go` which are not exported, e.g. [SendTxArgs](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1347) and [CallArgs](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L737).

You can still unpack the results from these methods calls into custom structs with the proper types and `json` tags- and do the same for the args- but I'm curious why these types aren't exported in the first place.

If it is desirable to move those types outside of `internal`, I'd be happy to make the changes!

**Comment by karalabe** [comment]
What is it exactly you are trying to do? We placed these into `internal` because this stuff is not Go API, it's rather some internal detail for the RPC. We don't really want to expose these into Go.

**Comment by i-norden** [comment]
I'm making batch calls to `eth_getTransactionByHash` and `eth_getProof`, I can define my own  `RPCTransaction` and `AccountResult` types to unpack the results into but wasn't clear why these types couldn't be exported and reused. The `ethclient/ethclient.go` exposes a `TransactionByHash` method which is wrapped around the internal `GetTransactionByHash` and returns the exported `*types.Transaction` type, but for batch calls I use the `rpc/client.go` `BatchCall` or `BatchCallContext` methods with calls directly to `eth_getTransactionByHash` (the internal endpoint). Sorry if I'm missing something!

**Comment by adamschmideg** [comment]
We decided we are not planning to expose those functions in the near future, because we don't want to commit to those types as a stable API.

**Comment by karalabe** [comment]
The returned JSON scheme is stable, so if you create your own Go type + json tags it should be simple enough and survive long term. I don't think there's a super need to reuse our own types, which have a bit of a different purpose (and are hacky currently).

**Comment by fjl** [comment]
To add to that, another reason why we don't want to export those is that these types are for use by the RPC server.

The types we support for public use are in `core/types`. We will try very hard to never change those types again.

**Comment by i-norden** [comment]
That all makes sense, thanks for the clarification!
