### ISSUE TITLE
Ropsten synchronisation stopped

### ISSUE THREAD

**Issue by g574** [ethereum/go-ethereum#20135]
#### System information

Geth version: `1.9.5`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Continuous syncing

#### Actual behaviour
Syncing stops at block 6485846

#### Steps to reproduce the behaviour
The node stopped suddenly a few hours ago. I restarted it, it resynced the last few hundred blocks and got stuck again at the same block.

#### Backtrace

````
########## BAD BLOCK #########
Chain config: {ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: 4230000 Petersburg: 4939394 Istanbul: 6485846 Engine: ethash}

Number: 6485846
Hash: 0x5bd02cabf0bedac8168e43e25e0c306d1140139b5f5b02a08b18464dd9b5dc6b
         0: cumulative: 186413 gas: 186413 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xa18915222e16543aab076d05b5f9ec804906ca1767cf208986e32df67b6ffeaa logs: [0xc017eb5a20] bloom: 00000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000020000000000000000000000000000000000000000000040000000000000000002000000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000008000000000000000000000000000000000000000000 state:


Error: invalid gas used (remote: 162041 local: 186413)
##############################

````
Additional info: https://ropsten.etherscan.io/ has stopped, as well. 
![image](https://user-images.githubusercontent.com/51915615/65870924-9b740580-e37d-11e9-93a5-520ec3730592.png)

**Comment by karalabe** [comment]
All the miners are on non-updated nodes. We've spun up a few miners on Istanbul. You can whitelist the Istanbul block to lock out non-updated nodes: https://twitter.com/peter_szilagyi/status/1178634327518781441
