### ISSUE TITLE
geth starts resyncing even after the full sync is complete .

### ISSUE THREAD

**Issue by amanpruthi** [ethereum/go-ethereum#20149]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: ` 1.9.5-stable`
OS & Version: CentOS Linux release 7.6.1810 
Commit hash : (if `develop`)

#### Expected behaviour
After the fast sync is complete the latest block from ropsten bootnodes should be synced  .

#### Actual behaviour
Geth starts syncing again even though it already has the  latest block details 
PFA the logs .
If we restart geth it reads from disk and starts syncing from the latest block .

[ geth_logs.log](https://github.com/ethereum/go-ethereum/files/3684740/geth_logs.log)

#### Steps to reproduce the behaviour
sync to ropsten from scratch without restart 

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Whoah, that's funky. Definitely should not have done that.

**Comment by amanpruthi** [comment]
Encountered this again on restart this time it was due to missing head chain PFB  
[10-03|06:22:07.058] Imported new chain segment               blocks=295 txs=10802 mgas=634.681 elapsed=6.751s    mgasps=94.007 number=6495423 hash=c2bdf0…e90ebd age=2m3s      dirty=42.58MiB
INFO [10-03|06:22:07.288] Imported new chain segment               blocks=5   txs=235   mgas=33.925  elapsed=227.260ms mgasps=149.279 number=6495428 hash=006eca…4d679a dirty=43.22MiB
INFO [10-03|06:22:09.226] Deep froze chain segment                 blocks=2083 elapsed=672.108ms number=6405427 hash=4b1989…ddfa9c
INFO [10-03|06:22:11.781] Imported new chain segment               blocks=1    txs=48    mgas=7.703   elapsed=70.000ms  mgasps=110.044 number=6495429 hash=385ae9…208910 dirty=43.38MiB
WARN [10-03|06:22:15.622] Synchronisation failed, dropping peer    peer=c7e7675577416d6b err=timeout
INFO [10-03|06:23:09.248] Deep froze chain segment                 blocks=1    elapsed=21.939ms  number=6405428 hash=fb146c…8830c0
INFO [10-03|06:23:36.120] Got interrupt, shutting down...
INFO [10-03|06:23:36.120] WebSocket endpoint closed                url=ws://<endpoint>
INFO [10-03|06:23:36.120] HTTP endpoint closed                     url=http://<endpoint>
INFO [10-03|06:23:36.120] IPC endpoint closed                      url=<geth_dir>/geth.ipc
INFO [10-03|06:25:06.845] Maximum peer count                       ETH=50 LES=0 total=50
INFO [10-03|06:25:06.845] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
ERROR[10-03|06:25:06.847] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-03|06:25:06.847] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-03|06:25:06.847] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-03|06:25:06.847] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-03|06:25:06.847] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-03|06:25:06.848] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
INFO [10-03|06:25:06.849] Starting peer-to-peer node               instance=Geth/v1.9.5-stable-a1c09b93/linux-amd64/go1.11.5
INFO [10-03|06:25:06.849] Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
INFO [10-03|06:25:06.849] Allocated cache and file handles         database=<geth_dir>/geth/chaindata cache=512.00MiB handles=25000
INFO [10-03|06:25:07.724] Opened ancient database                  database=<geth_dir>/geth/chaindata/ancient
INFO [10-03|06:25:07.735] Persisted trie from memory database      nodes=355 size=50.67KiB time=1.464734ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [10-03|06:25:07.735] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: 4230000 Petersburg: 4939394 Istanbul: 6485846 Engine: ethash}"
INFO [10-03|06:25:07.735] Disk storage enabled for ethash caches   dir=<geth_dir>/geth/ethash count=3
INFO [10-03|06:25:07.735] Disk storage enabled for ethash DAGs     dir=<home>/.ethash count=2
INFO [10-03|06:25:07.737] Initialising Ethereum protocol           versions=[63] network=3 dbversion=7
WARN [10-03|06:25:07.791] Head state missing, repairing chain      number=6495429 hash=385ae9…208910
ERROR[10-03|06:25:07.848] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-03|06:25:07.849] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-03|06:25:07.849] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
INFO [10-03|06:25:09.670] Rewound blockchain to past state         number=6492816 hash=b1e95f…15fff6
INFO [10-03|06:25:09.670] Loaded most recent local header          number=6495429 hash=385ae9…208910 td=23353368394462902 age=3m22s
INFO [10-03|06:25:09.670] Loaded most recent local full block      number=6492816 hash=b1e95f…15fff6 td=23353321757165960 age=12h29m39s
INFO [10-03|06:25:09.670] Loaded most recent local fast block      number=6495429 hash=385ae9…208910 td=23353368394462902 age=3m22s
INFO [10-03|06:25:09.671] Loaded local transaction journal         transactions=0 dropped=0
INFO [10-03|06:25:09.671] Regenerated local transaction journal    transactions=0 accounts=0
WARN [10-03|06:25:09.671] Switch sync mode from fast sync to full sync
INFO [10-03|06:25:09.723] New local node record                    seq=4 id=c5917744c95c73f4 ip=127.0.0.1 udp=30303 tcp=30303
INFO [10-03|06:25:09.724] Started P2P networking                   self=enode://baf1e614b79e02cb2feaefd97e92127aba60e62cab7ecd7c9c3aee7a9e71395ccd5c2fc1080dc65fd5ca4e067cc5095ad4d41e502301a44b4984b18abf27264c@127.0.0.1:30303
INFO [10-03|06:25:09.729] IPC endpoint opened                      url=<geth_dir>/geth.ipc
INFO [10-03|06:25:09.730] HTTP endpoint opened                     url=http://<endpoint> cors= vhosts=*
INFO [10-03|06:25:09.731] WebSocket endpoint opened                url=ws://<endpoint>
INFO [10-03|06:25:39.724] Block synchronisation started
INFO [10-03|06:36:24.938] Importing heavy sidechain segment        blocks=2048 start=1 end=2048
INFO [10-03|06:36:26.703] Imported new chain segment               blocks=2048 txs=22 mgas=1.258 elapsed=1.764s mgasps=0.713 number=2048    hash=6708aa…742bab age=2y10mo3w  dirty=193.96KiB
INFO [10-03|06:36:26.752] Importing heavy sidechain segment        blocks=2048 start=2049 end=4096
INFO [10-03|06:36:28.102] Imported new chain segment               blocks=2048 txs=3  mgas=2.351 elapsed=1.349s mgasps=1.742 number=4096    hash=769903…c570f8 age=2y10mo3w  dirty=244.46KiB
INFO [10-03|06:36:28.153] Importing heavy sidechain segment        blocks=2048 start=4097 end=6144
INFO [10-03|06:36:29.678] Imported new chain segment               blocks=2048 txs=108 mgas=7.634 elapsed=1.524s mgasps=5.009 number=6144    hash=541ec9…c6ac03 age=2y10mo3w  dirty=286.38KiB
INFO [10-03|06:36:29.724] Importing heavy sidechain segment        blocks=2048 start=6145 end=8192
INFO [10-03|06:36:31.991] Imported new chain segment               blocks=2048 txs=76  mgas=30.550 elapsed=2.265s mgasps=13.483 number=8192    hash=00033e…c88ae3 age=2y10mo3w  dirty=294.08KiB
INFO [10-03|06:36:32.040] Importing heavy sidechain segment        blocks=2048 start=8193 end=10240
INFO [10-03|06:36:34.492] Imported new chain segment               blocks=2048 txs=77  mgas=32.112 elap

**Comment by holiman** [comment]
It does a fast-sync, to `6492699`
```
INFO [10-02|17:55:46.313] Committed new head block                 number=6492699 hash=31fe6d…85eb2b
```
Then imports some remaining blocks on top, until `6492816`
```
INFO [10-02|17:55:51.779] Imported new chain segment               blocks=115 txs=2686 mgas=228.939 elapsed=5.410s    mgasps=42.317 number=6492814 hash=b66fdc…cc8264 dirty=10.65MiB
INFO [10-02|17:55:53.011] Imported new chain segment               blocks=2   txs=25   mgas=1.008   elapsed=38.896ms  mgasps=25.915 number=6492816 hash=b1e95f…15fff6 dirty=10.76MiB
INFO [10-02|17:55:53.011] Fast sync complete, auto disabling
```
Simultaneously, it finds out about a sidechain, and imports some of that
```
INFO [10-02|17:55:56.391] Sidechain written to disk                start=6485846 end=6485851 sidetd=23351892562934351 localtd=23353321757165960
INFO [10-02|17:55:56.972] Sidechain written to disk                start=6485852 end=6485858 sidetd=23351908709003239 localtd=23353321757165960
```
Sidechain appears to be `6485846` to `6485852`. At this point, I think it discovers that the sidechain is indeed longer than the chain it's currently at. So it needs to switch over. However, block `6485846` is earlier than our pivot block `6492699`, so the only place where we have a `state`, is genesis. So it uses that: 

Starting at block 1`, importing blocks one by one:
```
INFO [10-02|18:06:00.673] Importing heavy sidechain segment        blocks=2048  start=1       end=2048
INFO [10-02|18:06:02.853] Imported new chain segment               blocks=2048  txs=22   mgas=1.258   elapsed=2.177s    mgasps=0.578  number=2048    hash=6708aa…742bab age=2y10mo3w   dirty=10.95MiB
```

**Comment by holiman** [comment]
@amanpruthi I recommend that you start over, and this time use the cmd line flag `--whitelist=6485846=0x43f0cd1e5b1f9c4d5cda26c240b59ee4f1b510d0a185aa8fd476d091b0097a80`

That flag makes your node issue a challenge to peers, checking that the block `6485846` is indeed the Istanbul block, and not the non-forked chain. That should 'solve' your problem going forward, but there are underlying issues which we need to fix aswell, as documented in #20150

**Comment by amanpruthi** [comment]
Thanks @holiman .I tried cleaning data dir and starting sync from scratch again and faced this issue  again .I am trying again lets see if I am able to succeed .Is there  other solution so that I can proceed?

**Comment by holiman** [comment]
> I tried cleaning data dir and starting sync from scratch again and faced this issue again

hmm.. Please clarify -- did you use `--whitelist=6485846=0x43f0cd1e5b1f9c4d5cda26c240b59ee4f1b510d0a185aa8fd476d091b0097a80` _and_ had the same issue again?

**Comment by amanpruthi** [comment]
Nope did not use this option .Is there a compiled  list of blocks for which I should do this ? .In any case will update you after using this option .
Also Faced the same issue on fully synced node with different block  as well PFB .The sync went back around 40k blocks .
```
NFO [10-01|17:46:49.609] Imported new chain segment               blocks=1    txs=35   mgas=7.735    elapsed=23.330s   mgasps=0.332   number=6488115 hash=e36eed…842e44 age=3h7m6s    dirty=3.56MiB
INFO [10-01|17:46:50.095] Imported new chain segment               blocks=2    txs=38   mgas=8.721    elapsed=484.689ms mgasps=17.994  number=6488117 hash=9f2cfe…bb8c8b age=3h5m22s   dirty=3.85MiB
INFO [10-01|17:46:58.284] Imported new chain segment               blocks=44   txs=1132 mgas=199.926  elapsed=8.178s    mgasps=24.446  number=6488161 hash=b65d21…c1706f age=2h30m12s  dirty=12.42MiB
INFO [10-01|17:47:06.291] Imported new chain segment               blocks=41   txs=1773 mgas=272.471  elapsed=8.006s    mgasps=34.031  number=6488202 hash=c851e0…550aa3 age=1h59m21s  dirty=21.12MiB
INFO [10-01|17:47:14.552] Imported new chain segment               blocks=45   txs=1986 mgas=264.537  elapsed=8.261s    mgasps=32.020  number=6488247 hash=9f1188…040ec9 age=1h30m58s  dirty=31.72MiB
INFO [10-01|17:47:16.017] Deep froze chain segment                 blocks=139  elapsed=758.592ms number=6398252 hash=75acf9…d42bab
INFO [10-01|17:47:22.667] Imported new chain segment               blocks=38   txs=1612 mgas=239.438  elapsed=8.114s    mgasps=29.508  number=6488285 hash=335395…4dd36a age=1h10m2s   dirty=40.37MiB
INFO [10-01|17:47:30.687] Imported new chain segment               blocks=40   txs=938  mgas=249.362  elapsed=8.019s    mgasps=31.093  number=6488325 hash=14932e…e11219 age=46m24s    dirty=44.86MiB
INFO [10-01|17:47:38.812] Imported new chain segment               blocks=80   txs=2024 mgas=495.937  elapsed=8.125s    mgasps=61.038  number=6488405 hash=5e4dc6…0e6754 age=5m7s      dirty=49.11MiB
INFO [10-01|17:47:40.264] Imported new chain segment               blocks=8    txs=111  mgas=55.108   elapsed=1.452s    mgasps=37.937  number=6488413 hash=b870ba…b9f76a age=2m44s     dirty=49.89MiB
INFO [10-01|17:47:40.268] Sidechain written to disk                start=6488118 end=6488118 sidetd=23353227386466404 localtd=23353238008061908
INFO [10-01|17:47:40.589] Imported new chain segment               blocks=3    txs=77   mgas=22.738   elapsed=317.185ms mgasps=71.687  number=6488416 hash=fd449b…5f3000 age=1m13s     dirty=49.96MiB
INFO [10-01|17:48:01.690] Importing heavy sidechain segment        blocks=2048 start=6449977 end=6452024
INFO [10-01|17:48:11.260] Imported new chain segment               blocks=3    txs=6    mgas=23.941   elapsed=9.569s    mgasps=2.502   number=6449979 hash=186ff4…0c6bbf age=1w8h23m   dirty=53.11MiB
INFO [10-01|17:48:16.105] Deep froze chain segment                 blocks=163  elapsed=87.220ms  number=6398415 hash=053bd0…f871ff
INFO [10-01|17:48:19.472] Imported new chain segment               blocks=8    txs=178  mgas=58.905   elapsed=8.211s    mgasps=7.173   number=6449987 hash=e06e4c…fc8f16 age=1w8h21m   dirty=59.83MiB
INFO [10-01|17:48:28.163] Imported new chain segment               blocks=25   txs=540  mgas=135.514  elapsed=8.690s    mgasps=15.593  number=6450012 hash=bfa24e…43906e age=1w8h4m    dirty=70.63MiB
INFO [10-01|17:48:36.211] Imported new chain segment               blocks=15   txs=427  mgas=119.589  elapsed=8.048s    mgasps=14.858  number=6450027 hash=e88113…ca07c9 age=1w7h46m   dirty=82.85MiB
INFO [10-01|17:48:44.401] Imported new chain segment               blocks=19   txs=908  mgas=151.772  elapsed=8.189s    mgasps=18.533  number=6450046 hash=ad120d…4e4e61 age=1w7h37m   dirty=94.22MiB
INFO [10-01|17
```

**Comment by amanpruthi** [comment]
Just an update as soon as I added the flag   --whitelist=6485846=0x43f0cd1e5b1f9c4d5cda26c240b59ee4f1b510d0a185aa8fd476d091b0097a80  geth started syncing from latest block and is in sync now .Thanks

**Comment by holiman** [comment]
> Is there a compiled list of blocks for which I should do this ?

No. It can be seen as an emergency procedure to use when there are long (invalid) sidechains, but you specifically know what chain you want to hone in on, and ignore other forks

**Comment by jayboy-mabushi** [comment]
@holiman I am seen something similar on my node 

INFO [08-24|03:23:19.064] Importing heavy sidechain segment        blocks=989  start=13,052,144 end=13,053,132
INFO [08-24|03:23:27.507] Imported new chain segment               blocks=31   txs=5361 mgas=462.227  elapsed=8.442s  mgasps=54.750  number=13,052,174 hash=68b0da..8984e1 age=5d3h53m  dirty=0.00B
INFO [08-24|03:23:35.562] Imported new chain segment               blocks=27   txs=4554 mgas=403.459  elapsed=8.054s  mgasps=50.091  number=13,052,201 hash=a1586e..3b9a9e age=5d3h47m  dirty=0.00B
INFO [08-24|03:23:43.609] Imported new chain segment               blocks=25   txs=4887 mgas=404.859  elapsed=8.047s  mgasps=50.308  number=13,052,226 hash=2d9b7e..35733c age=5d3h41m  dirty=0.00B
INFO [08-24|03:23:52.420] Imported new chain segment               blocks=27   txs=4923 mgas=408.903  elapsed=8.810s  mgasps=46.412  number=13,052,253 hash=ad72a4..61aee8 age=5d3h32m  dirty=0.00B
INFO [08-24|03:24:00.709] Imported new chain segment               blocks=19   txs=2883 mgas=271.418  elapsed=8.289s  mgasps=32.742  number=13,052,272 hash=ce522a..d58e24 age=5d3h29m  dirty=0.00B
INFO [08-24|03:24:09.438] Imported new chain segment               blocks=29   txs=4927 mgas=443.420  elapsed=8.728s  mgasps=50.800  number=13,052,301 hash=8fca94..319333 age=5d3h23m  dirty=0.00B
INFO [08-24|03:24:17.586] Imported new chain segment               blocks=25   txs=5050 mgas=400.169  elapsed=8.147s  mgasps=49.115  number=13,052,326 hash=bede0a..174520 age=5d3h16m  dirty=0.00B
INFO [08-24|03:24:26.043] Imported new chain segment               blocks=28   txs=4640 mgas=416.005  elapsed=8.456s  mgasps=49.191  number=13,052,354 hash=32e2ab..886ccd age=5d3h10m  dirty=0.00B
INFO [08-24|03:24:34.117] Imported new chain segment               blocks=26   txs=4301 mgas=383.405  elapsed=8.074s  mgasps=47.485  number=13,052,380 hash=1b3bd8..de7b4c age=5d3h6m   dirty=0.00B
INFO [08-24|03:24:42.360] Imported new chain segment               blocks=26   txs=4633 mgas=414.324  elapsed=8.243s  mgasps=50.262  number=13,052,406 hash=1afe0a..50314a age=5d3h35s  dirty=0.00B
INFO [08-24|03:24:50.457] Imported new chain segment               blocks=27   txs=4225 mgas=392.878  elapsed=8.097s  mgasps=48.521  number=13,052,433 hash=fa8cf8..c28822 age=5d2h55m  dirty=0.00B
INFO [08-24|03:24:58.681] Imported new chain segment               blocks=25   txs=4453 mgas=396.784  elapsed=8.223s  mgasps=48.250  number=13,052,458 hash=12a728..bfd543 age=5d2h50m  dirty=0.00B
INFO [08-24|03:25:06.754] Imported new chain segment               blocks=19   txs=4273 mgas=290.552  elapsed=8.073s  mgasps=35.990  number=13,052,477 hash=5421d3..2b84c8 age=5d2h46m  dirty=0.00B
INFO [08-24|03:25:14.763] Imported new chain segment               blocks=25   txs=4709 mgas=405.624  elapsed=8.009s  mgasps=50.644  number=13,052,502 hash=670f48..130fa2 age=5d2h38m  dirty=0.00B
