### ISSUE TITLE
How light client and full node connected in Ethereum private chain?

### ISSUE THREAD

**Issue by caotingtingctt** [ethereum/go-ethereum#20144]
#### System information

Geth version: `geth 1.8`
OS & Version: Linux
Commit hash : (if `develop`)

 How light client and full node connected in Ethereum private chain?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
