### ISSUE TITLE
Any way to statically link geth to libc? Or any other way of getting geth to run on SLES11?

### ISSUE THREAD

**Issue by ericcurtin** [ethereum/go-ethereum#20143]
Hi there,

Trying to run geth on SLES11, golang is working fine on this system, I grabbed the pre-built binaries, but I think my glibc library might be a bit old:

```
~> geth-linux-amd64-1.9.5-a1c09b93/geth
geth-linux-amd64-1.9.5-a1c09b93/geth: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by geth-linux-amd64-1.9.5-a1c09b93/geth)
~> strings /lib64/libc.so.6 | grep GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_PRIVATE
```

#### System information

Geth version: 1.9.5
OS & Version: SLES11
Commit hash : (if `develop`)

#### Expected behaviour

I can run geth

#### Actual behaviour

geth-linux-amd64-1.9.5-a1c09b93/geth
geth-linux-amd64-1.9.5-a1c09b93/geth: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by geth-linux-amd64-1.9.5-a1c09b93/geth)

#### Steps to reproduce the behaviour

Execute geth.

**Comment by karalabe** [comment]
You'll need to build it yourself I'm afraid. Even though we can link some parts of glibc statically, some cannot be done (user handling and dns resolution, not sure why). Statically linked code accessing those APIs crashes.

**Comment by ericcurtin** [comment]
Yeah managed to build it on openSUSE 11.4 for our SLES vm. Thanks for highlighting those issues! Might be useful if we see something funky.
