### ISSUE TITLE
ErrFutureBlock doesn't stop inserting weird block to local blockchain

### ISSUE THREAD

**Issue by CoreyLin** [ethereum/go-ethereum#20142]
#### Code information

https://github.com/ethereum/go-ethereum/blob/master/eth/fetcher/fetcher.go#L657

```go
		case consensus.ErrFutureBlock:
			// Weird future block, don't fail, but neither propagate

		default:
```

#### Expected behaviour

Since ErrFutureBlock means the propagated block is a weird future block, the `insert` method should **return** immediately instead of continuing to invoking `f.insertChain(types.Blocks{block})` to insert it to current node's local blockchain. Maybe I didn't get it right here, but could you clarify it?

#### Actual behaviour

When ErrFutureBlock happens, it still continue to insert the weird block to local blockchain. Why?

**Comment by holiman** [comment]
What you're looking at is the `fetcher`. It isn't too intelligent, and the real import logic happens in blockchain.go. In this case, it will deliver the future block to the blockchain, which will put it into a future-cache and try to reprocess later. 

It may be the case that our time is off, and our peers will deliver blocks that we consider to be in the future. In that case, we still want the blocks to be (eventually) processed.
