### ISSUE TITLE
[Feature] Add metric for per-message-type network packet counts 

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#20146]
Last week we added support for measuring the bandwidth used by subprotocol messages (https://github.com/ethereum/go-ethereum/pull/20133). We should extend that with packet counters too. This would allow us to see if we can optimize network traffic via batching, or if something is out of this world (e.g. state requests / responses, which otherwise are tiny).

**Comment by fjl** [comment]
Added in #21256
