### ISSUE TITLE
web3ext.go seems to have accounting.properties defined as methods

### ISSUE THREAD

**Issue by ItsAsbreuk** [ethereum/go-ethereum#20147]
See line:
https://github.com/ethereum/go-ethereum/blob/master/internal/web3ext/web3ext.go#L750

#### Actual code
```js
methods: [
    new web3._extend.Property({
    ...
```

#### Expected code
```js
methods: [],
properties: [
    new web3._extend.Property({
    ...
```

**Comment by ligi** [comment]
You are correct - but unfortunately this became part of the API and changing it would break things.
