### ISSUE TITLE
abi improperly formatted

### ISSUE THREAD

**Issue by jjhesk** [ethereum/go-ethereum#20157]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: OSX
Commit hash : 1.9.4

#### Expected behaviour
completely formmated the abi code

#### Steps to reproduce the behaviour
build contract using go abi

#### Backtrace
`abi: improperly formatted output:�y� "Roles: account is the zero address - Bytes: [[8 195 121 160 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 34 82 111 108 101 115 58 32 97 99 99 111 117 110 116 32 105 115 32 116 104 101 32 122 101 114 111 32 97 100 100 114 101 115 115 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]])`
````
[backtrace]
````

**Comment by jjhesk** [comment]
resolved as the contract has the permission limitation and it was blocked by the entrance of the address.

**Comment by priyanshu-digi** [comment]
> resolved as the contract has the permission limitation and it was blocked by the entrance of the address. change the input from address and it will resolved that properly.

Hi, can you further elaborate it?
What exact changes you made to the function?

I modified the bsc genesis contract and added only more function:

**function addValidator(address _consensusAddress) public  {
  
    currentValidatorSet.push(Validator({
        consensusAddress: _consensusAddress,
        feeAddress: address(0), // default to address(0) for uninitialized addresses
        BBCFeeAddress: address(0), // default to address(0) for uninitialized addresses
        votingPower: 0, // default to 0 for uninitialized voting power
        jailed: false, // default to false for uninitialized jail status
        incoming: 0 // default to 0 for uninitialized incoming
    }));
}**



It was compiled properly but constantly getting error: "abi improperly formatted"
