### ISSUE TITLE
Prevent fast-synced node from reorg to before pivot

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#20150]
As evidenced by https://github.com/ethereum/go-ethereum/issues/20149 , on a chain where there are long (invalid) sidechains, there's a possibility for a fast-synched chain to basically switch over to a full block-by-block sync from genesis. 

1. Node syncs to pivot block `N`. 
2. Node finds out about a sidechain -- in the case of #20149, the old non-istanbul chain which is still being mined.  Node eventually detects that the sidechain has higher `TD` than his own chain.
3.  Normally, the fetcher prevents extremely long reorgs, where the common ancestor is more than an epoch back. However, in this case, the common ancestor is not _that_ far off. 
4. The crucial point here is that although the common ancestor is not that far off, it's _behind the pivot point_, so the node does not have any state for it. 
5. So the sidechain importer goes all the way back to genesis, where it _has_ the state, and then reimports every block to recreate the state for the common ancestor. 
6. It will eventually reach the fork point, and there detect that there's an invalid block, and reject the sidechain. However, I believe that this scenario might actually repeat multiple times.

A couple of things we can/should fix: 
- A fast-synched node should _not_ try to regenerate state / import a sidechain if the common ancestor is earlier than the pivot point. This can maybe be expressed more generically as: A node should not regenerate state from genesis (?).
- The _penalty_ of the repeating behaviour can be stopped, if we always store the state of a common ancestor, after we have recalculated it (but before we commence on the potentially bad sidechain). (Note: this does not prevent the repetitive behaviour, only the ovehead) 
- It _might_ make sense to remember bad blocks, but that is a bit dangerous too. That would stop the repetitive behaviour

**Comment by karalabe** [comment]
* We perhas should also force-commit `FORK_BLOCK - 1` states. This would help doing long side chain reimports and would rather always fail instantly at the first invalid block. Though this doesn't help fast sync.

**Comment by karalabe** [comment]
* We should propose an EIP to add some special marker to fork block headers so we can instantly invalidate blocks that are on a different fork, without having to even regenerate the state for it. This is a secondary mechanism beside the forkid (which is cheaper/simpler, but can be faked).
