### ISSUE TITLE
admin.sleepBlocks hangs

### ISSUE THREAD

**Issue by silly-n** [ethereum/go-ethereum#2016]
Running geth for private chain, on console I issue miner.start(8); then admin.sleepBlocks(1); and the terminal stops responding. It doesn't recover even when many blocks are mined.
Any suggestions?

geth 1.4.0, but the behaviour was the same yesterday on 1.3

Some logs ...
>I1130 12:38:44.672084    4166 mergedapi.go:61] admin_sleepBlocks [1,null]
>I1130 12:38:45.281871    4166 state_object.go:184] 5102a5dfa7fddde0fbdb85ef8e1735ea37f9103b: #5 9185000000000000000000 (+ 5000000000000000000)
>I1130 12:38:45.282007    4166 worker.go:570] commit new work on block 2072 with 0 txs & 0 uncles. Took 5.000389623s
>I1130 12:38:45.282025    4166 worker.go:448] 🔨 🔗  Mined 5 blocks back: block #2066
>I1130 12:38:45.282076    4166 agent.go:118] (re)started agent[6]. mining...
>I1130 12:38:45.282091    4166 agent.go:118] (re)started agent[2]. mining...
>I1130 12:38:45.282101    4166 agent.go:118] (re)started agent[5]. mining...
>I1130 12:38:45.282112    4166 agent.go:118] (re)started agent[7]. mining...
>I1130 12:38:45.282095    4166 agent.go:118] (re)started agent[3]. mining...
>I1130 12:38:45.282386    4166 state_object.go:184] 5102a5dfa7fddde0fbdb85ef8e1735ea37f9103b: #5 9185000000000000000000 (+ 5000000000000000000)
>I1130 12:38:45.282503    4166 worker.go:570] commit new work on block 2072 with 0 txs & 0 uncles. Took 235.158µs
>I1130 12:38:45.282540    4166 agent.go:118] (re)started agent[7]. mining...

**Comment by bas-vk** [comment]
@silly-n, this issue is fixed in develop.
Thx for reporting.

**Comment by aaronstjohn** [comment]
I'm experiencing the same issue, even after switching to the develop branch. I'm running geth consistently with the tutorial docs here:
https://ethereum.gitbooks.io/frontier-guide/content/testing_contracts_and_transactions.html

Here's my session:
```
instance: Geth/v1.4.0-unstable-0ab8a175/darwin/go1.5.2
coinbase: null
at block: 0 (Wed, 31 Dec 1969 16:00:00 PST)
 datadir: testnet
> personal.newAccount();
Passphrase: 
Repeat passphrase: 
"0x7621b34d585daed08f2a2d02f08abadfc2b352fc"
> miner.start(8);
true
> admin.sleepBlocks(10);
```
Here's the log file that gets dumped out:
[testnet.txt](https://github.com/ethereum/go-ethereum/files/85325/testnet.txt)
