### ISSUE TITLE
Go modules

### ISSUE THREAD

**Issue by eccles** [ethereum/go-ethereum#20164]
Not a bug but a request/question

when is go-ethereum moving to go modules instead of using dep?

**Comment by zjiekai** [comment]
People are working on it
https://github.com/ethereum/go-ethereum/pull/19605

**Comment by eccles** [comment]
Please see https://github.com/urfave/cli/issues/904 where I had issues in my own repo with go get -u.
The suggestion is to use the github.com url for urfave/cli and not the gopkg.in url.

I also had problems with go-interpreter/wagon. (also pulled in by go-ethereum.)

The caveat here is that I am currently pinned to version 1.8.27 of go-ethereum due to circumstances beyond my control so I did not report this as a bug in go-ethereum.(yet)

Hope this is helpful.

**Comment by karalabe** [comment]
Yes, this is something we want to do. Unfortunately we need to switch over our launchpad builders to snaps + make launchpad meta packages because Go 1.13 is not available on older versions of Ubuntu. Until that work is done, go modules are blocked.

**Comment by Pet3ris** [comment]
I've just filed a potentially related [issue](https://github.com/ethereum/go-ethereum/issues/20226).

It seems like not only does `go-ethereum` not use go modules, it may not be able to be used in any go module project that invokes the indirect `leveldb` dependency.
