### ISSUE TITLE
rpc: add support for setting HTTP headers on Client

### ISSUE THREAD

**Issue by ricktian1226** [ethereum/go-ethereum#20163]
"ethclient.Client" doesn't support setting http header.
While i use infura jsonapi with "ethclient.Client", for security considerations, i gonna set "User-Agent", "Origin" by HTTP Headers.
But i can't find a way to do so.
Do i miss something ?

#### System information

Geth version: `v1.9.5`
OS & Version: ubuntu 18.04.01 

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Hmm, we indeed do not support setting headers on the individual requests currently. I guess we could add a method to modify headers too. Why would setting User-Agent and Origin however help security?

**Comment by ricktian1226** [comment]
infura supply security policy as follow， although i think it is weak ：
https://infura.io/docs/gettingStarted/whitelisting
=================================================================
Securing With Whitelists

If you are sending API requests from a web browser or other client-side application which does not have the ability to secure your Project Secret, whitelisting can be used to prevent a third party from using your Project ID on another website.
Understanding Whitelist Behavior

    If a project has no whitelists enabled, any request will be accepted.
    As soon as any whitelist entries are added, all requests must pass each whitelist type.
    Each whitelist type is "AND"ed together
    Multiple entries of the same type are "OR"ed.

Example

Scenario: Alice whitelisted the User-Agent of her mobile application and the Origin where her web app is hosted.

User-Agent Whitelist entry: com.example.aliceapp

Origin Whitelist Entry: aliceapp.example.com

Result: Both Alice's mobile app AND her website are allowed to use the same Project ID. If Alice created a new website under aliceawesomeapp.example.com, she would need to add this new Origin to the whitelist to allow the Project ID to function on the new site.

**Comment by fjl** [comment]
I think we should fix this by adding a method like `SetHeader` on `rpc.Client`.
