### ISSUE TITLE
Too high block number (ropsten)

### ISSUE THREAD

**Issue by nikitasius** [ethereum/go-ethereum#20162]
#### System information

Geth version: `1.9.6`
OS & Version: debian 9
Commit hash : `geth-linux-amd64-1.9.6-bd059680`

#### Expected behaviour
Same block like on etherscan for ropsten (6545322) when i call `eth.syncing` while it syncing from zero (i wiped all data).

#### Actual behaviour
Block is much more bigger: `6556362`

```json
{
	currentBlock: 119743,
	highestBlock: 6556362,
	knownStates: 270675,
	pulledStates: 249033,
	startingBlock: 0
}
```

```json
{
  currentBlock: 998540,
  highestBlock: 6556362,
  knownStates: 1819868,
  pulledStates: 1812477,
  startingBlock: 0
}
```

#### Steps to reproduce the behaviour
`/path/to/geth --allow-insecure-unlock --syncmode=fast --keystore '/path/to/wallets' --cache=4096 --testnet console --rpc --rpcaddr 127.0.0.1 --rpcport 8545 --rpcapi='admin,eth,miner,personal'`

This is my ropsten setup for testing.

**Comment by nikitasius** [comment]
Still syncing and this is currentBlock

```json
> eth.syncing
{
  currentBlock: 6556297,
  highestBlock: 6556378,
  knownStates: 20942332,
  pulledStates: 20914863,
  startingBlock: 0
}
```

**Comment by nikitasius** [comment]
Now it's changed:

```json
{
  currentBlock: 6547411,
  highestBlock: 6547506,
  knownStates: 128143463,
  pulledStates: 128135821,
  startingBlock: 6501206
}
```

Well, just know what strange issue exists.

**Comment by FantaZZ** [comment]
Same question, Any suggest ?

**Comment by FantaZZ** [comment]
@nikitasius Did you find some solution ?

**Comment by karalabe** [comment]
There are two chains currently on Ropsten, one without Istanbul and one with. For a very long time the non-updated chain was being pushed, hence why it has many blocks. However, the heaviest now is the correct Istanbul one.

You should be able to correctly sync to the proper chain, but you can help it via the `--whitelist=6485846=0x43f0cd1e5b1f9c4d5cda26c240b59ee4f1b510d0a185aa8fd476d091b0097a80` CLI flag.

**Comment by nikitasius** [comment]
> @nikitasius Did you find some solution ?

yes, 

* i wiped stored blockchain data for ropsten (ALL except wallets)
* installed 1.9.6
* run as `/path/to/geth --allow-insecure-unlock --syncmode=fast --keystore '/path/to/wallets' --cache=4096 --testnet console --rpc --rpcaddr 127.0.0.1 --rpcport 8545 --rpcapi='admin,eth,miner,personal'`
* let to be fully syncronised
* once syncronised its fine
