### ISSUE TITLE
gas needed too much

### ISSUE THREAD

**Issue by yekai1003** [ethereum/go-ethereum#20173]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.9.6`
OS & Version: OSX
Commit hash : (if `develop`)

#### remix 

remix call contract error

````
gas required exceeds allowance (1634198256) or always failing transaction
````
contract is 

```
pragma solidity^0.5.11;

contract Person {
    string public name ;
    uint256 public number;
    function setName(uint256 _num) public {
        number = _num;
    }
}
```

**Comment by karalabe** [comment]
How are you running Geth? New versions of Solidity require Constantinople forks to be enabled. Did you enable it properly in your genesis?
