### ISSUE TITLE
What is the preferred way to build geth binaries?

### ISSUE THREAD

**Issue by ryanschneider** [ethereum/go-ethereum#20175]
I've noticed that `xgo` has not been updated to recent go releases, and thus cross-compiling on OSX via `make geth-linux-amd64` builds with go 12.x, and yet the binaries on the EF website are all built using Go 1.13.x.  What is the current best way to build a branch for compatibility testing before sending a PR?

I see that travis is using `build/ci.go install` but I don't believe that path supports cross-compiling; is cross-compiling no longer fully supported?

**Comment by karalabe** [comment]
Why are you cross compiling though? I'd just recommend building on your own platform where you are developing. Cross compilation will always have its quirks. We mostly have `xgo` for mips lacking a better alternative.

**Comment by ryanschneider** [comment]
My workflow is typically to get things working with a Goerli chain on my laptop (running macOs), and then to test it out on a couple linux nodes.  I can migrate to using a linux build server/VM/container for that second part, but had been using the Makefile's xgo support up until now since it seemed the most straight-forward/discoverable way to do cross-platform builds.

Maybe we should add a note to the Cross Compilation targets that they aren't the preferred way to build, and that for best results you should use the build system on the target OS whenever possible?
