### ISSUE TITLE
Set a max length to the journals used for RevertToSnapshot?

### ISSUE THREAD

**Issue by james-ray** [ethereum/go-ethereum#20176]
About #20172
Seems like I have found the reason where all these *big.int are held, they are likely being held by the BalanceChange journalEntry.

func (self *stateObject) SetBalance(amount *big.Int) {
	self.db.journal.append(balanceChange{
		account: &self.address,
		prev:    new(big.Int).Set(self.data.Balance),   //this is the cause
	})
	self.setBalance(amount)
}

Our test is simply lots of transfer txs, without any contract execution. Each transaction tx just adds one wei to the to account.

I am wondering, if we need to keep those journals in memory forever, should we have some cleaning mechanism, or set a max length to it?

**Comment by karalabe** [comment]
The journal is flushed after every transaction.
