### ISSUE TITLE
gcmode missing in toml config?

### ISSUE THREAD

**Issue by phahulin** [ethereum/go-ethereum#20170]
#### System information

Geth version
```
Geth
Version: 1.9.6-stable
Git Commit: bd05968077f27f7eb083404dd8448157996a8788
Git Commit Date: 20191003
Architecture: amd64
Protocol Versions: [63]
Network Id: 1
Go Version: go1.13.1
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.13.1.linux.amd64
```
OS & Version: Amazon Linux

#### Expected behaviour
We started a ropsten node with toml config file generated by dumpconfig
```
./geth --testnet --syncmode full --gcmode archive --cache 2048  --datadir /data/ropsten --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpcapi "debug, net, eth, shh, web3, txpool" --ws --wsaddr 0.0.0.0 --wsapi "eth, net, web3, network, debug, txpool" --wsorigins "*" --rpccorsdomain "*" dumpconfig > ropsten.toml
```
(note that there's `--gcmode archive` option enabled) and started the node with `./geth --config ropsten.toml`.

#### Actual behaviour
It seems `gcmode` is not present in the toml file: https://gist.github.com/phahulin/9851a3a1bbe70586ba9201ce4d4b0a89
and we're seeing errors like
```
%{code: -32000, data: %{block_number: 6575111, transaction_hash: "0x84f6f459a31a8e5b7b8678ca6c7cce30132c9113c35c7ccfece904095fae8a56", transaction_index: 7}, message: "required historical state unavailable (reexec=128)"}
```
which usually happen when gcmode was not set to `archive`.

#### Steps to reproduce the behaviour
See above

#### Backtrace
None

----------

Is there something else we missed? If we have to resync, is there a geth option to start syncing from specific block number?

**Comment by karalabe** [comment]
The flag in the config file is named a bit differently:

```
$ geth --gcmode=archive dumpconfig

[Eth]
NetworkId = 1
SyncMode = "fast"
NoPruning = true   <- this one

...
```

Are you sure you did a full sync with archive mode enabled? If you just accidentally messed this up for the last blocks, you can run `debug.setHead(blocknum)` to revert to an older block.

**Comment by PeaStew** [comment]
So that is really confusing... does the command line switch override the config.toml setting?

if node is run as gcmode = archive and the config.toml is set to NoPruning = false, which one wins when running the node?

**Comment by MikeC-BC** [comment]
yes, confused about this as well.

**Comment by karalabe** [comment]
Priority is always `CLI > Config > Defaults`
