### ISSUE TITLE
Memory Leak? during transaction decoding

### ISSUE THREAD

**Issue by james-ray** [ethereum/go-ethereum#20172]
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top20
Showing nodes accounting for 1114.87MB, 93.85% of 1187.94MB total
Dropped 166 nodes (cum <= 5.94MB)
Showing top 20 nodes out of 174
      flat  flat%   sum%        cum   cum%
  259.53MB 21.85% 21.85%   259.53MB 21.85%  reflect.New
  244.01MB 20.54% 42.39%   477.02MB 40.16%  github.com/ethereum/go-ethereum/rlp.decodeBigInt
  217.01MB 18.27% 60.66%   217.01MB 18.27%  math/big.nat.make
     192MB 16.16% 76.82%      192MB 16.16%  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/memdb.New
   40.50MB  3.41% 80.23%    40.50MB  3.41%  github.com/ethereum/go-ethereum/rlp.(*Stream).Bytes
   20.01MB  1.68% 81.91%    20.01MB  1.68%  github.com/tendermint/tendermint/vendor/github.com/syndtr/goleveldb/leveldb/memdb.New
   16.93MB  1.43% 83.34%    16.93MB  1.43%  bytes.makeSlice
   15.33MB  1.29% 84.63%    15.33MB  1.29%  fmt.(*fmt).fmtSbx
   15.27MB  1.29% 85.91%    15.27MB  1.29%  github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop
   13.20MB  1.11% 87.02%    13.70MB  1.15%  github.com/ethereum/go-ethereum/core/types.(*Block).WithBody
   12.50MB  1.05% 88.08%   553.52MB 46.60%  github.com/ethereum/go-ethereum/core/types.(*Transaction).DecodeRLP
      11MB  0.93% 89.00%       13MB  1.09%  github.com/tendermint/tendermint/libs/clist.(*CList).PushBack
   10.96MB  0.92% 89.92%    18.20MB  1.53%  sync.(*Map).Store
    9.73MB  0.82% 90.74%     9.73MB  0.82%  github.com/tendermint/go-amino.DecodeByteSlice
    8.04MB  0.68% 91.42%     8.04MB  0.68%  github.com/tendermint/tendermint/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).Get
       7MB  0.59% 92.01%    21.50MB  1.81%  github.com/ethereum/go-ethereum/core/types.(*Transaction).WithSignature
    6.62MB  0.56% 92.57%     6.62MB  0.56%  github.com/green-element-chain/gelchain/ethereum.(*Backend).InsertCachedTxFrom
    6.24MB  0.53% 93.09%     6.24MB  0.53%  sync.(*Map).dirtyLocked
    4.50MB  0.38% 93.47%    36.20MB  3.05%  github.com/tendermint/tendermint/mempool.(*CListMempool).resCbFirstTime
    4.50MB  0.38% 93.85%        8MB  0.67%  github.com/ethereum/go-ethereum/core/state.(*stateObject).SetBalance

Our application is based on ethermint and Tendermint, we are doing performance test lately. We found the memory used for big.int decoding continuously rising.
Any hint about this?

**Comment by james-ray** [comment]
Time: Oct 16, 2019 at 11:54am (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top20
Showing nodes accounting for 2030.17MB, 94.28% of 2153.44MB total
Dropped 285 nodes (cum <= 10.77MB)
Showing top 20 nodes out of 140
      flat  flat%   sum%        cum   cum%
  545.56MB 25.33% 25.33%   545.56MB 25.33%  reflect.New
  524.02MB 24.33% 49.67%  1039.04MB 48.25%  github.com/ethereum/go-ethereum/rlp.decodeBigInt
  468.03MB 21.73% 71.40%   468.03MB 21.73%  math/big.nat.make
     192MB  8.92% 80.32%      192MB  8.92%  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/memdb.New
      83MB  3.85% 84.17%       83MB  3.85%  github.com/ethereum/go-ethereum/rlp.(*Stream).Bytes
      30MB  1.39% 85.57%  1202.05MB 55.82%  github.com/ethereum/go-ethereum/core/types.(*Transaction).DecodeRLP
   27.07MB  1.26% 86.82%    27.07MB  1.26%  github.com/ethereum/go-ethereum/core/types.(*Block).WithBody
   21.72MB  1.01% 87.83%    59.57MB  2.77%  github.com/ethereum/go-ethereum/core/vm.NewEVM
   20.71MB  0.96% 88.79%    37.85MB  1.76%  github.com/ethereum/go-ethereum/core/vm.NewInterpreter
   20.01MB  0.93% 89.72%    20.01MB  0.93%  github.com/tendermint/tendermint/vendor/github.com/syndtr/goleveldb/leveldb/memdb.New
   17.13MB   0.8% 90.52%    17.13MB   0.8%  github.com/ethereum/go-ethereum/core/vm.newstack
   15.27MB  0.71% 91.23%    15.27MB  0.71%  github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop
   12.29MB  0.57% 91.80%    12.29MB  0.57%  github.com/tendermint/tendermint/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).Get
   12.01MB  0.56% 92.36%    12.01MB  0.56%  github.com/ethereum/go-ethereum/crypto/sha3.(*state).clone
      12MB  0.56% 92.91%       12MB  0.56%  github.com/tendermint/tendermint/libs/clist.(*CList).PushBack
   10.84MB   0.5% 93.42%    10.84MB   0.5%  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/memdb.(*DB).Put
       7MB  0.33% 93.74%   111.08MB  5.16%  github.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync
    5.50MB  0.26% 94.00%    14.07MB  0.65%  sync.(*Map).Store
       4MB  0.19% 94.18%       11MB  0.51%  github.com/ethereum/go-ethereum/core/types.(*Transaction).WithSignature
       2MB 0.093% 94.28%    30.07MB  1.40%  github.com/tendermint/tendermint/mempool.(*CListMempool).resCbFirstTime

**Comment by james-ray** [comment]
Type: inuse_space
Time: Oct 16, 2019 at 2:20pm (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top20
Showing nodes accounting for 2959.73MB, 94.31% of 3138.16MB total
Dropped 314 nodes (cum <= 15.69MB)
Showing top 20 nodes out of 109
      flat  flat%   sum%        cum   cum%
  816.60MB 26.02% 26.02%   816.60MB 26.02%  reflect.New
  778.52MB 24.81% 50.83%  1566.56MB 49.92%  github.com/ethereum/go-ethereum/rlp.decodeBigInt
  723.54MB 23.06% 73.89%   723.54MB 23.06%  math/big.nat.make
     192MB  6.12% 80.00%      192MB  6.12%  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/memdb.New
  119.50MB  3.81% 83.81%   119.50MB  3.81%  github.com/ethereum/go-ethereum/rlp.(*Stream).Bytes
   60.62MB  1.93% 85.74%   160.04MB  5.10%  github.com/ethereum/go-ethereum/core/vm.NewEVM
   60.62MB  1.93% 87.68%    98.92MB  3.15%  github.com/ethereum/go-ethereum/core/vm.NewInterpreter
      43MB  1.37% 89.05%  1800.57MB 57.38%  github.com/ethereum/go-ethereum/core/types.(*Transaction).DecodeRLP
   38.29MB  1.22% 90.27%    38.29MB  1.22%  github.com/ethereum/go-ethereum/core/vm.newstack
   37.54MB  1.20% 91.46%    37.54MB  1.20%  github.com/ethereum/go-ethereum/core/types.(*Block).WithBody
   20.51MB  0.65% 92.12%    20.51MB  0.65%  github.com/ethereum/go-ethereum/crypto/sha3.(*state).clone
   17.01MB  0.54% 92.66%    17.01MB  0.54%  github.com/ethereum/go-ethereum/trie.(*fullNode).copy
   16.50MB  0.53% 93.18%    26.42MB  0.84%  sync.(*Map).Store
   16.01MB  0.51% 93.69%    16.01MB  0.51%  github.com/tendermint/tendermint/vendor/github.com/syndtr/goleveldb/leveldb/memdb.New
       4MB  0.13% 93.82%    48.42MB  1.54%  github.com/tendermint/tendermint/mempool.(*CListMempool).resCbFirstTime
       4MB  0.13% 93.95%    26.01MB  0.83%  github.com/ethereum/go-ethereum/common.Address.Hex
    3.50MB  0.11% 94.06%    27.41MB  0.87%  github.com/tendermint/tendermint/mempool.(*CListMempool).addTx
       3MB 0.096% 94.16%   272.57MB  8.69%  github.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync
       3MB 0.096% 94.25%    23.51MB  0.75%  github.com/ethereum/go-ethereum/crypto/sha3.(*state).Sum
    1.96MB 0.062% 94.31%    44.88MB  1.43%  github.com/green-element-chain/gelchain/ethereum.(*Backend).txBroadcastLoop

**Comment by fnaticwang** [comment]
advertent

**Comment by holiman** [comment]
Hard to say anything about this. IIUC, the data above shows where the memory was allocated, not who holds the memory. Meaning, that although a lot of data was allocated during the `rlp` decoding of e..g transactions, the cause of holding on to memory might be within the transaction pool. It seems that you're using tendermint, which has it's own txpool. 

That txpool stores transactions in a synced map: https://github.com/tendermint/tendermint/blob/master/mempool/clist_mempool.go#L340 , and I'm not sure if it get's cleaned up properly. 

You might want to open this ticket with tendermint instead, we have refactored our txpool quite a lot and it's very different from theirs.

**Comment by james-ray** [comment]
Originally I doubt that map too, below was the original pprof result:
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top30
Showing nodes accounting for 2956.49MB, 96.83% of 3053.21MB total
Dropped 221 nodes (cum <= 15.27MB)
Showing top 30 nodes out of 94
flat flat% sum% cum cum%
455.04MB 14.90% 14.90% 575MB 18.83% sync.(*Map).Store
405.05MB 13.27% 28.17% 405.05MB 13.27% reflect.New
368.51MB 12.07% 40.24% 763.03MB 24.99% github.com/ethereum/go-ethereum/rlp.decodeBigInt
367.52MB 12.04% 52.28% 367.52MB 12.04% math/big.nat.make
347.53MB 11.38% 63.66% 378.53MB 12.40% github.com/tendermint/tendermint/libs/clist.(*CList).PushBack
195.52MB 6.40% 70.06% 195.52MB 6.40% github.com/ethereum/go-ethereum/rlp.(*encbuf).toBytes
192MB 6.29% 76.35% 192MB 6.29% github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/memdb.New
168.52MB 5.52% 81.87% 198.02MB 6.49% github.com/tendermint/tendermint/libs/clist.(*CElement).SetPrev
153.01MB 5.01% 86.88% 1108.04MB 36.29% github.com/tendermint/tendermint/mempool.(*CListMempool).resCbFirstTime
102.46MB 3.36% 90.24% 102.46MB 3.36% sync.(*Map).dirtyLocked
60.50MB 1.98% 92.22% 60.50MB 1.98% github.com/tendermint/tendermint/libs/clist.waitGroup1
59MB 1.93% 94.15% 59MB 1.93% github.com/ethereum/go-ethereum/rlp.(*Stream).Bytes
20.32MB 0.67% 94.82% 20.82MB 0.68% github.com/ethereum/go-ethereum/core/types.(*Block).WithBody
20MB 0.66% 95.47% 877.53MB 28.74% github.com/ethereum/go-ethereum/core/types.(*Transaction).DecodeRLP
17.50MB 0.57% 96.05% 17.50MB 0.57% sync.newEntry
16.01MB 0.52% 96.57% 16.01MB 0.52% github.com/tendermint/tendermint/vendor/github.com/syndtr/goleveldb/leveldb/memdb.New
6.50MB 0.21% 96.78% 18MB 0.59% github.com/ethereum/go-ethereum/core/types.(*Transaction).WithSignature
1.50MB 0.049% 96.83% 387.45MB 12.69% github.com/tendermint/tendermint/mempool.(*CListMempool).addTx
0 0% 96.83% 18MB 0.59% github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).SignTx
0 0% 96.83% 18MB 0.59% github.com/ethereum/go-ethereum/accounts/keystore.(*keystoreWallet).SignTx
0 0% 96.83% 1223.90MB 40.09% github.com/ethereum/go-ethereum/core.(*BlockChain).GetBlock
0 0% 96.83% 1223.90MB 40.09% github.com/ethereum/go-ethereum/core.(*BlockChain).GetBlockByNumber
0 0% 96.83% 196.77MB 6.44% github.com/ethereum/go-ethereum/core.(*BlockChain).WriteBlockWithState
0 0% 96.83% 1223.90MB 40.09% github.com/ethereum/go-ethereum/core.GetBlock
0 0% 96.83% 1203.08MB 39.40% github.com/ethereum/go-ethereum/core.GetBody
0 0% 96.83% 18MB 0.59% github.com/ethereum/go-ethereum/core/types.SignTx
0 0% 96.83% 1223.90MB 40.09% github.com/ethereum/go-ethereum/eth.(*EthApiBackend).BlockByNumber
0 0% 96.83% 1223.90MB 40.09% github.com/ethereum/go-ethereum/eth/gasprice.(*Oracle).getBlockPrices
0 0% 96.83% 193.10MB 6.32% github.com/ethereum/go-ethereum/ethdb.(*ldbBatch).Write
0 0% 96.83% 33.08MB 1.08% github.com/ethereum/go-ethereum/internal/ethapi.(*PublicTransactionPoolAPI).SendTransaction

But later I found some of our codes that iterate the txlist in the memPool sleeps for a long time without set nil to the iterated element, so I modified them. After the modification, the pprof result turned as shown in this issue. We can see the allocation in this line:
16.50MB  0.53% 93.18%    26.42MB  0.84%  sync.(*Map).Store    
has dropped.

**Comment by holiman** [comment]
It might be better to run @fjl 's memory tool to figure out not only where it's allocated, but who holds on to the memory. @fjl, can you provide some info on how to use it?

**Comment by james-ray** [comment]
0: 0 [3: 48] @ 0x5682a3 0x568142 0x5b3a1e 0x5b39eb 0x5c0af3 0x5b912e 0x6ff39f 0x11e8a58 0x11e4358 0x10283f2 0x10330f1 0x1037dc7 0x10379e9 0x103f53a 0x103e845 0x10a876a 0x10a7c00 0x107eab4 0x109ecc1 0x4998f1
#	0x5682a2	math/big.nat.make+0x182									/root/.go/src/math/big/nat.go:63
#	0x568141	math/big.nat.setBytes+0x21								/root/.go/src/math/big/nat.go:1312
#	0x5b3a1d	math/big.(*Int).SetBytes+0x67d								/root/.go/src/math/big/int.go:434
#	0x5b39ea	github.com/ethereum/go-ethereum/rlp.decodeBigInt+0x64a					/energy/gopath/src/github.com/ethereum/go-ethereum/rlp/decode.go:236
#	0x5c0af2	github.com/ethereum/go-ethereum/rlp.makeStructDecoder.func1+0x632			/energy/gopath/src/github.com/ethereum/go-ethereum/rlp/decode.go:398
#	0x5b912d	github.com/ethereum/go-ethereum/rlp.(*Stream).Decode+0x1ed				/energy/gopath/src/github.com/ethereum/go-ethereum/rlp/decode.go:764
#	0x6ff39e	github.com/ethereum/go-ethereum/core/types.(*Transaction).DecodeRLP+0x5e		/energy/gopath/src/github.com/ethereum/go-ethereum/core/types/transaction.go:144
#	0x11e8a57	github.com/green-element-chain/gelchain/app.decodeTx+0xd7				/energy/gopath/src/github.com/green-element-chain/gelchain/app/utils.go:31
#	0x11e4357	github.com/green-element-chain/gelchain/app.(*EthermintApplication).CheckTx+0x87	/energy/gopath/src/github.com/green-element-chain/gelchain/app/app.go:208
#	0x10283f1	github.com/tendermint/tendermint/abci/client.(*localClient).CheckTxAsync+0xd1		/energy/gopath/src/github.com/tendermint/tendermint/abci/client/local_client.go:99
#	0x10330f0	github.com/tendermint/tendermint/proxy.(*appConnMempool).CheckTxAsync+0x60		/energy/gopath/src/github.com/tendermint/tendermint/proxy/app_conn.go:114
#	0x1037dc6	github.com/tendermint/tendermint/mempool.(*CListMempool).recheckTxs+0x236		/energy/gopath/src/github.com/tendermint/tendermint/mempool/clist_mempool.go:621
#	0x10379e8	github.com/tendermint/tendermint/mempool.(*CListMempool).Update+0x378			/energy/gopath/src/github.com/tendermint/tendermint/mempool/clist_mempool.go:592
#	0x103f539	github.com/tendermint/tendermint/state.(*BlockExecutor).Commit+0x6b9			/energy/gopath/src/github.com/tendermint/tendermint/state/execution.go:258
#	0x103e844	github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock+0x704		/energy/gopath/src/github.com/tendermint/tendermint/state/execution.go:195
#	0x10a8769	github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit+0x9d9	/energy/gopath/src/github.com/tendermint/tendermint/consensus/state.go:1403
#	0x10a7bff	github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit+0x3df	/energy/gopath/src/github.com/tendermint/tendermint/consensus/state.go:1321
#	0x107eab3	github.com/tendermint/tendermint/consensus.(*ConsensusReactor).handleSignMsg+0x1563	/energy/gopath/src/github.com/tendermint/tendermint/consensus/reactor.go:1940
#	0x109ecc0	github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine+0x590	/energy/gopath/src/github.com/tendermint/tendermint/consensus/state.go:683


0: 0 [1: 32] @ 0x5b8489 0x5b33e0 0x5c0af3 0x5b912e 0x6ff39f 0x11e8a58 0x11e46bb 0x1028052 0x1032dce 0x103fd12 0x103e2bb 0x10a876a 0x10a7c00 0x107eab4 0x109ecc1 0x4998f1
#	0x5b8488	github.com/ethereum/go-ethereum/rlp.(*Stream).Bytes+0x78				/energy/gopath/src/github.com/ethereum/go-ethereum/rlp/decode.go:612
#	0x5b33df	github.com/ethereum/go-ethereum/rlp.decodeBigInt+0x3f					/energy/gopath/src/github.com/ethereum/go-ethereum/rlp/decode.go:223
#	0x5c0af2	github.com/ethereum/go-ethereum/rlp.makeStructDecoder.func1+0x632			/energy/gopath/src/github.com/ethereum/go-ethereum/rlp/decode.go:398
#	0x5b912d	github.com/ethereum/go-ethereum/rlp.(*Stream).Decode+0x1ed				/energy/gopath/src/github.com/ethereum/go-ethereum/rlp/decode.go:764
#	0x6ff39e	github.com/ethereum/go-ethereum/core/types.(*Transaction).DecodeRLP+0x5e		/energy/gopath/src/github.com/ethereum/go-ethereum/core/types/transaction.go:144
#	0x11e8a57	github.com/green-element-chain/gelchain/app.decodeTx+0xd7				/energy/gopath/src/github.com/green-element-chain/gelchain/app/utils.go:31
#	0x11e46ba	github.com/green-element-chain/gelchain/app.(*EthermintApplication).DeliverTx+0x8a	/energy/gopath/src/github.com/green-element-chain/gelchain/app/app.go:225
#	0x1028051	github.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync+0xd1		/energy/gopath/src/github.com/tendermint/tendermint/abci/client/local_client.go:88
#	0x1032dcd	github.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync+0x5d		/energy/gopath/src/github.com/tendermint/tendermint/proxy/app_conn.go:73
#	0x103fd11	github.com/tendermint/tendermint/state.execBlockOnProxyApp+0x6b1			/energy/gopath/src/github.com/tendermint/tendermint/state/execution.go:323
#	0x103e2ba	github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock+0x17a		/energy/gopath/src/github.com/tendermint/tendermint/state/execution.go:160
#	0x10a8769	github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit+0x9d9	/energy/gopath/src/github.com/tendermint/tendermint/consensus/state.go:1403
#	0x10a7bff	github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit+0x3df	/energy/gopath/src/github.com/tendermint/tendermint/consensus/state.go:1321
#	0x107eab3	github.com/tendermint/tendermint/consensus.(*ConsensusReactor).handleSignMsg+0x1563	/energy/gopath/src/github.com/tendermint/tendermint/consensus/reactor.go:1940
#	0x109ecc0	github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine+0x590	/energy/gopath/src/github.com/tendermint/tendermint/consensus/state.go:683


0: 0 [64: 1024] @ 0x5682a3 0x568142 0x5b3a1e 0x5b39eb 0x5c0af3 0x5b912e 0x6ff39f 0x11e8a58 0x11e4358 0x10283f2 0x10330f1 0x1035646 0x103517f 0x11dd382 0x11dd772 0x11dd065 0x4998f1
#	0x5682a2	math/big.nat.make+0x182									/root/.go/src/math/big/nat.go:63
#	0x568141	math/big.nat.setBytes+0x21								/root/.go/src/math/big/nat.go:1312
#	0x5b3a1d	math/big.(*Int).SetBytes+0x67d								/root/.go/src/math/big/int.go:434
#	0x5b39ea	github.com/ethereum/go-ethereum/rlp.decodeBigInt+0x64a					/energy/gopath/src/github.com/ethereum/go-ethereum/rlp/decode.go:236
#	0x5c0af2	github.com/ethereum/go-ethereum/rlp.makeStructDecoder.func1+0x632			/energy/gopath/src/github.com/ethereum/go-ethereum/rlp/decode.go:398
#	0x5b912d	github.com/ethereum/go-ethereum/rlp.(*Stream).Decode+0x1ed				/energy/gopath/src/github.com/ethereum/go-ethereum/rlp/decode.go:764
#	0x6ff39e	github.com/ethereum/go-ethereum/core/types.(*Transaction).DecodeRLP+0x5e		/energy/gopath/src/github.com/ethereum/go-ethereum/core/types/transaction.go:144
#	0x11e8a57	github.com/green-element-chain/gelchain/app.decodeTx+0xd7				/energy/gopath/src/github.com/green-element-chain/gelchain/app/utils.go:31
#	0x11e4357	github.com/green-element-chain/gelchain/app.(*EthermintApplication).CheckTx+0x87	/energy/gopath/src/github.com/green-element-chain/gelchain/app/app.go:208
#	0x10283f1	github.com/tendermint/tendermint/abci/client.(*localClient).CheckTxAsync+0xd1		/energy/gopath/src/github.com/tendermint/tendermint/abci/client/local_client.go:99
#	0x10330f0	github.com/tendermint/tendermint/proxy.(*appConnMempool).CheckTxAsync+0x60		/energy/gopath/src/github.com/tendermint/tendermint/proxy/app_conn.go:114
#	0x1035645	github.com/tendermint/tendermint/mempool.(*CListMempool).CheckTxWithInfo+0x405		/energy/gopath/src/github.com/tendermint/tendermint/mempool/clist_mempool.go:301
#	0x103517e	github.com/tendermint/tendermint/mempool.(*CListMempool).CheckTx+0x5e			/energy/gopath/src/github.com/tendermint/tendermint/mempool/clist_mempool.go:223
#	0x11dd381	github.com/green-element-chain/gelchain/ethereum.(*Backend).BroadcastTxSync+0xc1	/energy/gopath/src/github.com/green-element-chain/gelchain/ethereum/txs.go:51
#	0x11dd771	github.com/green-element-chain/gelchain/ethereum.(*Backend).BroadcastTx+0x151		/energy/gopath/src/github.com/green-element-chain/gelchain/ethereum/txs.go:84
#	0x11dd064	github.com/green-element-chain/gelchain/ethereum.(*Backend).txBroadcastLoop+0x1f4	/energy/gopath/src/github.com/green-element-chain/gelchain/ethereum/txs.go:34




0: 0 [9: 432] @ 0x4d51d5 0x86bc48 0x854c66 0x8541fa 0x85122c 0x1091476 0x106a6a7 0x1015812 0xfb43f9 0x4998f1
#	0x4d51d4	reflect.New+0x44								/root/.go/src/reflect/value.go:2290
#	0x86bc47	github.com/tendermint/go-amino.constructConcreteType+0x47			/energy/gopath/src/github.com/tendermint/go-amino/reflect.go:184
#	0x854c65	github.com/tendermint/go-amino.(*Codec).decodeReflectBinaryInterface+0x315	/energy/gopath/src/github.com/tendermint/go-amino/binary-decode.go:360
#	0x8541f9	github.com/tendermint/go-amino.(*Codec).decodeReflectBinary+0x18c9		/energy/gopath/src/github.com/tendermint/go-amino/binary-decode.go:86
#	0x85122b	github.com/tendermint/go-amino.(*Codec).UnmarshalBinaryBare+0x1fb		/energy/gopath/src/github.com/tendermint/go-amino/amino.go:344
#	0x1091475	github.com/tendermint/tendermint/consensus.decodeMsg+0x195			/energy/gopath/src/github.com/tendermint/tendermint/consensus/reactor.go:3713
#	0x106a6a6	github.com/tendermint/tendermint/consensus.(*ConsensusReactor).Receive+0x2a6	/energy/gopath/src/github.com/tendermint/tendermint/consensus/reactor.go:261
#	0x1015811	github.com/tendermint/tendermint/p2p.createMConnection.func1+0x271		/energy/gopath/src/github.com/tendermint/tendermint/p2p/peer.go:385
#	0xfb43f8	github.com/tendermint/tendermint/p2p/conn.(*MConnection).recvRoutine+0x888	/energy/gopath/src/github.com/tendermint/tendermint/p2p/conn/connection.go:586


The three cases show how the decoding was called, mainly in "checkTx" triggered by Tendermint.

**Comment by james-ray** [comment]
func (app *EthermintApplication) CheckTx(req abciTypes.RequestCheckTx) abciTypes.ResponseCheckTx {
	txBytes := req.Tx
	tx, err := decodeTx(txBytes)
	if err != nil {
		// nolint: errcheck
		app.logger.Debug("CheckTx: Received invalid transaction", "tx", tx)
		return abciTypes.ResponseCheckTx{
			Code: uint32(errors.CodeInternal),
			Log:  err.Error(),
		}
	}
	app.logger.Debug("CheckTx: Received valid transaction", "tx", tx) // nolint: errcheck

	return app.validateTx(tx, req.Type)
}


The CheckTx in ethermint is shown as above, and below is one place where it is called:
	invalidTxs := make([]common.Hash, 0)
	for e := mem.txs.Front(); e != nil; e = e.Next() {
		memTx := e.Value.(*mempoolTx)
		reqRes := mem.proxyAppConn.CheckTxAsync(abci.RequestCheckTx{Tx: memTx.tx, Type: abci.CheckTxType_Recheck})
		r := reqRes.Response.GetCheckTx()
		if r.Code != abci.CodeTypeOK && mem.recheckFailCallback != nil {
			transaction, err := DecodeTx(memTx.tx)
			if err != nil {
				mem.logger.Error(fmt.Sprintf("tx recheck decodeTx fail,tx is %X ", memTx.tx))
			}
			txHash := transaction.Hash()
			mem.logger.Info(fmt.Sprintf("Invalid Tx, after decodeTx is %v, txHash is %v",  transaction, txHash))
			invalidTxs = append(invalidTxs, txHash)
		}
	}

If the mem.txs has not been released correctly, it is indeed possible that the txBytes is still held.

**Comment by james-ray** [comment]
Sorry, I messed up the format

**Comment by karalabe** [comment]
The `rlp` pckage simply decodes the big.Int. It's up to you what you do with it afterwards. If you can create a repro that leaks memory using only the `rlp` package we'll gladly take a closer look. Without a repro, I'm going to assume the leak is in `ethermint`, which we will not be able to help you with. Please open an issue on the `ethermint` repo.
