### ISSUE TITLE
Unavailable to process logs with payload size greater than 405KB (Approx.) 

### ISSUE THREAD

**Issue by CodeUltimate** [ethereum/go-ethereum#20171]
Hi there,

I am trying to use a smart contract to publish data on it so that it can log back the data to the API, however I have noticed if the payload is lower than approximately less than 405KB it seems to be fine but anything over approximately over 405KB it fails. I am not sure if there is a maximum size in which a log can be e.g. 0.5MB. I am using JQ.Morgan's Quorum fork of Geth.
Can I emit event logs more than 405KB approx? 

#### System information

Geth
Version: 1.8.18-stable
Quorum Version: 2.3.0
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.9.3
Operating System: linux

````
org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 413; content length too large (526385>524288) at org.web3j.protocol.http.HttpService.performIO(HttpService.java:163) at org.web3j.protocol.Service.send(Service.java:34) at org.web3j.protocol.core.Request.send(Request.java:72) at org.web3j.quorum.tx.ClientTransactionManager.sendTransaction(ClientTransactionManager.java:83
````

**Comment by jpmsam** [comment]
Please open this under Quorum and we'll look into it. It probably has to do with the contract not being included in a block.

**Comment by CodeUltimate** [comment]
I have done so.
