### ISSUE TITLE
STATICCALL stores unnecessary snapshot of state

### ISSUE THREAD

**Issue by MrChico** [ethereum/go-ethereum#20180]
Since STATICCALL enforces that no change can be made to state, it seems that the snapshotting of state in [here](https://github.com/ethereum/go-ethereum/blob/master/core/vm/evm.go#L344) and subsequent `revertToSnapshot` is redundant. 

Indeed, I tried commenting out L344 and L362 and I'm still passing the tests in `GeneralStateTests/stStaticCall`.

Is there any other reason that it is included that I have missed? It might be a simple copy-paste mistake.

**Comment by holiman** [comment]
You're totally right, and I think I actually commented as much once upon a time (but can't seem to find it right now). 

IIRC, the reason it was left untouched was that it taking a snapshot is basically free, and similarly, reverting a journal which is empty is also basically a no-op.
