### ISSUE TITLE
[help] how can I get the failed reason for an invalid transaction through RPC?

### ISSUE THREAD

**Issue by guagualvcha** [ethereum/go-ethereum#20188]
in etherscan, I can see the fail info message:
![image](https://user-images.githubusercontent.com/7310198/67179158-0e661e80-f408-11e9-9a49-f6363be9c897.png)

however, by using `TransactionReceipt` RPC call , I can only get the status code, how can I get the specified failed message?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
