### ISSUE TITLE
Documentation does not specify what sync modes are

### ISSUE THREAD

**Issue by fulldecent** [ethereum/go-ethereum#20184]
The documentation at https://geth.ethereum.org/docs/interface/command-line-options

explains that a "fast" sync mode is available. No definition of this sync mode is provided.

Additionally, no explanation is given for which circumstances "fast" and "light" should be avoided.

I know these circumstances, this is not a support request. Instead, the issue is that the Go Ethereum project is lacking this authoritative statement. When I tell my clients "don't use Geth this way" it would be better if such statements were referenced to the Geth website, rather that to William Entriken as an individual.

**Comment by ligi** [comment]
changing as @adamschmideg said in standup @ChrisChinchilla will now work on this

**Comment by ChrisChinchilla** [comment]
Sorry for the delay, tackling this next.

**Comment by MariusVanDerWijden** [comment]
closed in favor of https://github.com/ethereum/go-ethereum/issues/20260
