### ISSUE TITLE
Documentation is not editable

### ISSUE THREAD

**Issue by fulldecent** [ethereum/go-ethereum#20183]
Please host https://geth.ethereum.org using a mechanism that allows continuous shipping, such as GitHub Pages. Then include a link to the source on the page.

Then I can make corrections there.

**Comment by holiman** [comment]
> Please host https://geth.ethereum.org using a mechanism that allows continuous shipping, such as GitHub Pages.  

It is already -- check the `gh-pages` branch.

**Comment by fulldecent** [comment]
Fix at https://github.com/ethereum/go-ethereum/pull/20200

**Comment by fulldecent** [comment]
Fixed at https://github.com/ethereum/go-ethereum/pull/20200
