### ISSUE TITLE
find strategy to keep wiki/Command-Line-Options up to date

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#20196]
I was pinged that https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options is out of date.
I brought it up to date - but we should find a strategy to keep it up to date. I see 3 options:

 - make it part of a PR checklist - so if a PR touches the CLI flags - updating the wiki gets part of the process
 - make a script that executes geht help on the last version and sees if there is a diff
 - remove this wiki page (people can just execute geth help on their version)

cc @adamschmideg

**Comment by adamschmideg** [comment]
The plan is to basically remove all wiki pages. If applicable, redirect to the corresponding page on the docs site.
Your strategies still apply to https://geth.ethereum.org/docs/interface/command-line-options, though.

**Comment by ligi** [comment]
hm - but that just moves the same problem to a different location ;-)
btw: https://geth.ethereum.org/docs/interface/command-line-options is outdated

**Comment by adamschmideg** [comment]
I mean the problem is still there, just not with the wiki page but with the docs. So it's to be addressed by any of the ways you suggested.
See also #19998 I added now that wiki pages have to be checked for any changes after the doc migration.

**Comment by adamschmideg** [comment]
Remove the doc page

**Comment by MariusVanDerWijden** [comment]
I'd propose to close this @ligi 
We often have contributions of external contributers updating the cli options so they never go stale too badly
