### ISSUE TITLE
Memory leak caused by repeated usage of the pointer of price in the func SuggestPrice

### ISSUE THREAD

**Issue by james-ray** [ethereum/go-ethereum#20192]
About #20172  
@holiman 
I've used flj's memsize tool, and located the problem seems inside the 
```
type TxPool struct {

	config       TxPoolConfig
	chainconfig  *params.ChainConfig
	chain        blockChain              //inside this structure


```

and is inside this
```
blockCache   *lru.Cache 
```
```
 

ALL                19556118  1318.964 MB
big.Int            13968186   831.223 MB
types.Transaction   2793452   412.935 MB
common.Address      2793452    53.281 MB
types.Block             256    21.353 MB
types.Header            256   136.000 KB
simplelru.entry         256    16.000 KB
simplelru.LRU             1    14.031 KB
list.Element            256    10.000 KB
list.List                 1         48 B
lru.Cache                 1         32 B
*lru.Cache                1          8 B


ALL                19822764  1336.947 MB
big.Int            14158648   842.557 MB
types.Transaction   2831544   418.566 MB
common.Address      2831544    54.007 MB
types.Block             256    21.644 MB
types.Header            256   136.000 KB
simplelru.entry         256    16.000 KB
simplelru.LRU             1    14.031 KB
list.Element            256    10.000 KB
list.List                 1         48 B
lru.Cache                 1         32 B
*lru.Cache                1          8 B



Root: "blockCache"
Date: 2019-10-22 13:39:37 +0800 CST
Duration: 38.909950976s
Bitmap Size: 612.625 MB
Bitmap Utilization: 0.2918385
ALL                21555977  1453.832 MB
big.Int            15396661   916.231 MB
types.Transaction   3079144   455.167 MB
common.Address      3079144    58.730 MB
types.Block             256    23.533 MB
types.Header            256   136.000 KB
simplelru.entry         256    16.000 KB
simplelru.LRU             1    14.031 KB
list.Element            256    10.000 KB
list.List                 1         48 B
lru.Cache                 1         32 B
*lru.Cache                1          8 B


Root: "blockCache"
Date: 2019-10-22 13:49:27 +0800 CST
Duration: 40.977649022s
Bitmap Size: 634.375 MB
Bitmap Utilization: 0.32366452
ALL                24755736  1669.621 MB
big.Int            17682210  1052.242 MB
types.Transaction   3536249   522.737 MB
common.Address      3536249    67.449 MB
types.Block             256    27.020 MB
types.Header            256   136.000 KB
simplelru.entry         256    16.000 KB
simplelru.LRU             1    14.031 KB
list.Element            256    10.000 KB
list.List                 1         48 B
lru.Cache                 1         32 B
*lru.Cache                1          8 B

```
From the reports, we could see the transaction number is continuously rising. Strangely, when debugging in local, the transaction number did not exceed 418181, while the number of list.Element was 256 too.
I don't know why when debugging in multiple nodes, the transaction number continuously rises.

**Comment by james-ray** [comment]
By the way, may I ask, how can I update the vendors? Seems like some dependent projects like golang-lru is an old version one.

**Comment by james-ray** [comment]
Root: "blockCache"
Date: 2019-10-22 14:10:24 +0800 CST
Duration: 1m9.836089148s
Bitmap Size: 742.750 MB
Bitmap Utilization: 0.3374587
ALL                30220530  2038.160 MB
big.Int            21585646  1284.534 MB
types.Transaction   4316928   638.139 MB
common.Address      4316928    82.339 MB
types.Block             256    32.977 MB
types.Header            256   136.000 KB
simplelru.entry         256    16.000 KB
simplelru.LRU             1    14.031 KB
list.Element            256    10.000 KB
list.List                 1         48 B
lru.Cache                 1         32 B
*lru.Cache                1          8 B

**Comment by james-ray** [comment]
I debug and find the caller of the LRU insertion is by this func:

> func (gpo *Oracle) getBlockPrices(ctx context.Context, signer types.Signer, blockNum uint64, ch chan getBlockPricesResult) {

	block, err := gpo.backend.BlockByNumber(ctx, rpc.BlockNumber(blockNum))
	if block == nil {
		ch <- getBlockPricesResult{nil, err}
		return
	}

	blockTxs := block.Transactions()
	txs := make([]*types.Transaction, len(blockTxs))
	copy(txs, blockTxs)
	sort.Sort(transactionsByGasPrice(txs))

	for _, tx := range txs {
		sender, err := types.Sender(signer, tx)
		if err == nil && sender != block.Coinbase() {
			ch <- getBlockPricesResult{tx.GasPrice(), nil}
			return
		}
	}
	ch <- getBlockPricesResult{nil, nil}
}

>

**Comment by james-ray** [comment]
Now I edit our test tool, set the price in the sendArgs, and the memory in the server side is OK.
Seems like I have found the cause.

**Comment by james-ray** [comment]
I think the reason why a local node does not leak memory is because all the blocks are proposed by itself, in the test of multiple nodes, there are other blocks and the txs in those blocks are not in its LRU cache. The txs in the block in the LRU cache continuously link the price pointer to some previous txs.

**Comment by holiman** [comment]
Yes, there's a mem leak regarding the gas prices. Thanks for diving into it!

Here: https://github.com/ethereum/go-ethereum/blob/e8f229b82ef99213f8f84b8a71f752b236024494/eth/gasprice/gasprice.go#L106-L107 

We start `n` goroutines, that each will 'hold' a block and try to return one value over a channel. However, if any one of them returns an error, we will stop listening to the channel: https://github.com/ethereum/go-ethereum/blob/e8f229b82ef99213f8f84b8a71f752b236024494/eth/gasprice/gasprice.go#L114-L116 

Before we figure out how to fix this, we need to figure out a good testcase that repros this

**Comment by holiman** [comment]
Sponteneously, a better approach would be to not keep track of `exp`, but always keep reading until the channel is emptied

**Comment by james-ray** [comment]
Would you please allow me to propose a PR for this? I will feel honored if I could make some contribution to Ethereum.

**Comment by holiman** [comment]
That'd be great, thanks

**Comment by james-ray** [comment]
I suppose a code of copying big.int, like new(big.Int).Set(price)  will fix this.

**Comment by james-ray** [comment]
I don't know how to write a UT to produce a memory problem, do you mean we have to repro it in a UT?

**Comment by holiman** [comment]
Hm... I actually don't see why holding on to that bigint pointer matters, tbh. I mean, if it fixes your problem, great, but I don't understand how..

Yes, would be nice with a unit test for this

**Comment by james-ray** [comment]
Block A             Block B             Block C
tx a1                  tx b1                  tx c1
tx a2                  tx b2                  tx c2
tx a3                  tx b3                  tx c3

If b1 reuses a1's price pointer, and a1 is generated by itself, it is fine.
But if Block A is generated by some other proposer, then the block and the txs in it is RLP decoded and allocated a new memory.

**Comment by holiman** [comment]
> The GC won't recycle a struct instance if some field of this instance is still held by others, right?

As far as I understand, holding a member wouldn't prevent the struct from being GC:ed - so that wouldn't explain the issue. cc @fjl

**Comment by james-ray** [comment]
Indeed, I've modified code to copy the big.int, but the mem problem still appears, I temporally close this, if I have some new discovery, I might open a new issue.
```
ALL                32049475  2161.502 MB
big.Int            22892037  1362.276 MB
types.Transaction   4578205   676.761 MB
common.Address      4578205    87.322 MB
types.Block             256    34.970 MB
types.Header            256   136.000 KB
simplelru.entry         256    16.000 KB
simplelru.LRU             1    14.031 KB
list.Element            256    10.000 KB
list.List                 1         48 B
lru.Cache                 1         32 B
*lru.Cache                1          8 B
```

**Comment by james-ray** [comment]
It might be a normal case. We have nearly 20000 txs in each block, so 256*20000=512 0000 txs, it is not a small number, the allocated memory may exceeds limit because of this.
We have modified the 256 to 64 to confirm this.
Thanks for recommending the memsize tool which helps us find the cause of the issue.

**Comment by holiman** [comment]
> We have nearly 20000 txs in each block, so 256*20000=512 0000 txs, 

Oh, right, yes, that definitely explains it :)

**Comment by james-ray** [comment]
Yes, the reason why local test cannot reproduce it is because the consensus of a single node is very fast, less than 1 second per block, while in multiple nodes, it may need at least 3 seconds, so the in txs > the output capability, causing each block carries the maximum txs---nearly 20000.
While in local mode, the block commits so fast that each block carries only less than 2000 txs, so the allocated memory wouldn't be that large.
