### ISSUE TITLE
Build error: Unknown field 'DisableSeeksCompaction' in struct literal

### ISSUE THREAD

**Issue by Chadsr** [ethereum/go-ethereum#20199]
#### System information

Geth version: Not relevant
OS & Version: Not relevant
Commit hash : `db79143a13c9`

#### Expected behaviour
Being able to build geth from master.

#### Actual behaviour
Build fails because of option flag, `DisableSeeksCompaction` at `ethdb/leveldb/leveldb.go:103`. It looks like the functionality was removed, but this flag is still there by accident?

#### Steps to reproduce the behaviour
Try to build geth from master branch

#### Backtrace

````
go-ethereum@v1.9.7-0.20191024084507-db79143a13c9/ethdb/leveldb/leveldb.go:103:3: unknown field 'DisableSeeksCompaction' in struct literal of type opt.Options````

**Comment by karalabe** [comment]
You seem to be building Geth with an old leveldb dependency. Our repo contains the newest vendored in, so youáll need to check you build environment as to why you're using an old version.

**Comment by cnjack** [comment]
it works for me
```
go get -u -v github.com/syndtr/goleveldb@master
```

**Comment by mvandemar** [comment]
@karalabe 
> You seem to be building Geth with an old leveldb dependency. Our repo contains the newest vendored in, so you'll need to check you build environment as to why you're using an old version.

I just installed both golang and dep today on Fedora 30 in order to compile geth, since there are no Fedora binaries that I saw, and I am getting this exact same error. As far as I know nothing should be old. When I try and use @cnjack's solution I get:

`go: cannot use path@version syntax in GOPATH mode`
