### ISSUE TITLE
toml config might be dropping archival gc mode flag.

### ISSUE THREAD

**Issue by RaghavSood** [ethereum/go-ethereum#20201]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: 1.9.6
OS & Version: Linux

#### Expected behaviour

NoPruning = true in the dumped config

#### Actual behaviour

NoPruning = false in the dumped config

#### Steps to reproduce the behaviour

We have a geth.toml that includes:

```
[Eth]
NetworkId = 1
SyncMode = "full"
DatabaseCache = 4096
NoPruning = true
```

I would expect this to enable an archival gc mode (we've been running with --gcmode=archiva as a cli flag until now). To verify this, I tried to read the config in and then dump it using:

    geth --config=/var/lib/blockchains/ethereum/geth.toml dumpconfig

However, this gives me a config dump with `NoPruning = false`

**Comment by rjl493456442** [comment]
I just test it. Specify an external config file with `NoPruning` as true, and dump it. The dumped config has `NoPruning = True`

**Comment by holiman** [comment]
```
build/bin/geth --datadir /tmp/baz --gcmode=archive --syncmode=full dumpconfig > config.dump
build/bin/geth --datadir /tmp/bar --config config.dump dumpconfig > config.dump2
diff config.dump config.dump2 
56c56
< DataDir = "/tmp/baz"
---
> DataDir = "/tmp/bar"
cat config.dump  | grep Pru -B4
[Eth]
NetworkId = 1
SyncMode = "full"
NoPruning = true
```
Same here, works as expected. I'll close this, feel free to reopen if you get a different result, @RaghavSood
