### ISSUE TITLE
clef: account_signTransaction throws false Invalid checksum on recipient address

### ISSUE THREAD

**Issue by meowsbits** [ethereum/go-ethereum#20214]
#### System information

Geth version:
```
$ ./build/bin/geth version
Geth
Version: 1.9.7-unstable
Git Commit: 538f763fdc304329d6231e6cb31efab4cba5153e
Architecture: amd64
Protocol Versions: [63]
Network Id: 1
Go Version: go1.12.1
Operating System: linux
GOPATH=/home/ia/go
GOROOT=/home/ia/go1.12.1.linux-amd64/go
```
OS & Version: 
```
$ uname -a
Linux ubp52 5.2.9-050209-generic #201908160940 SMP Fri Aug 16 09:42:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

#### Expected behaviour
`clef` is able to sign a bare-minimum valid transaction using the `account_signTransaction` method.

#### Actual behaviour
`clef` reports `Validation failed: Invalid checksum on recipient address` despite the Tx using a valid `to` address.

#### Steps to reproduce the behaviour
1. Run `clef` (I'm using HTTP)
2. POST the following to clef.
```
[{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "account_signTransaction",
  "params": [
    {
      "from": "0xf215e98b4f0c749fe9b78d0d4fa97ac7c9a4fe11",
      "to": "0x07a565b7ed7d7a678680a4c162885bedbb695fe0",
      "value": "0x1"
    }
  ]
}]
```
3. See result:
```
[
    {
        "jsonrpc": "2.0",
        "id": 1,
        "error": {
            "code": -32000,
            "message": "Validation failed: Invalid checksum on recipient address"
        }
    }
]
```

---

This patch:
```
diff --git a/signer/fourbyte/validation.go b/signer/fourbyte/validation.go
index 4d042d240..7c5bfb6e5 100644
--- a/signer/fourbyte/validation.go
+++ b/signer/fourbyte/validation.go
@@ -68,7 +68,7 @@ func (db *Database) ValidateTransaction(selector *string, tx *core.SendTxArgs) (
        }
        // Not a contract creation, validate as a plain transaction
        if !tx.To.ValidChecksum() {
-               messages.Warn("Invalid checksum on recipient address")
+               messages.Warn("Invalid checksum on recipient address: " + tx.To.String() + "a: " + tx.To.Address().Hex() + " o: " + tx.To.Original())
        }
        if bytes.Equal(tx.To.Address().Bytes(), common.Address{}.Bytes()) {
                messages.Crit("Transaction recipient is the zero address")
```
shows that `!tx.To.ValidChecksum()` is returning false because `original` and `Address` fields are not held in equivalent cases. https://github.com/ethereum/go-ethereum/blob/49b86a28590917eebf43bce213a2e0586db58755/common/types.go#L363

This can be resolved with the following patch:
```
diff --git a/common/types.go b/common/types.go
index 8ca51a05f..93f049069 100644
--- a/common/types.go
+++ b/common/types.go
@@ -360,7 +360,7 @@ func (ma *MixedcaseAddress) String() string {
 
 // ValidChecksum returns true if the address has valid checksum
 func (ma *MixedcaseAddress) ValidChecksum() bool {
-       return ma.original == ma.addr.Hex()
+       return strings.ToLower(ma.original) == strings.ToLower(ma.addr.Hex())
 }
 
 // Original returns the mixed-case input string
``` 

... although I have a feeling that might not be addressing (get it?) the root cause of the issue...

**Comment by karalabe** [comment]
The correct check-summed address of your `to` address is `0x07a565B7ED7D7A678680A4C162885bEDbB695Fe0`. I guess Clef is strictly enforcing checsumming.

**Comment by meowsbits** [comment]
Yea. I pulled the address verbatim from the clef docs at https://github.com/ethereum/go-ethereum/tree/master/cmd/clef#sample-call-2.

**Comment by holiman** [comment]
Clef strictly enforces checksumming. After the audit, we put that in. It can be changed by using a switch: 
```
   --advanced                         If enabled, issues warnings instead of rejections for suspicious requests. Default off
```

**Comment by meowsbits** [comment]
Got it. So it's just the docs are wrong, then.

**Comment by meowsbits** [comment]
Also, maybe I'm looking in the right place, but I'm not seeing any warnings with `--advanced` in the console:

```
INFO [10-29|09:05:49.674] Op approved
INFO [10-29|09:05:50.276] error occurred during execution          error="ReferenceError: 'OnApprovedTx' is not defined"
DEBUG[10-29|09:05:50.276] Served account_signTransaction           conn=127.0.0.1:45370 reqid=2 t=607.113887ms
INFO [10-29|09:05:50.284] Op approved
INFO [10-29|09:05:50.887] error occurred during execution          error="ReferenceError: 'OnApprovedTx' is not defined"
DEBUG[10-29|09:05:50.887] Served account_signTransaction           conn=127.0.0.1:45412 reqid=3 t=607.306734ms
INFO [10-29|09:05:50.894] Op approved
INFO [10-29|09:05:51.482] error occurred during execution          error="ReferenceError: 'OnApprovedTx' is not defined"
DEBUG[10-29|09:05:51.482] Served account_signTransaction           conn=127.0.0.1:45450 reqid=4 t=592.742955ms
INFO [10-29|09:06:02.707] Op approved 
INFO [10-29|09:06:03.313] error occurred during execution          error="ReferenceError: 'OnApprovedTx' is not defined"
DEBUG[10-29|09:06:03.313] Served account_signTransaction           conn=127.0.0.1:45800 reqid=5 t=625.729507ms
INFO [10-29|09:06:03.319] Op approved 
INFO [10-29|09:06:03.921] error occurred during execution          error="ReferenceError: 'OnApprovedTx' is not defined"
DEBUG[10-29|09:06:03.922] Served account_signTransaction           conn=127.0.0.1:45814 reqid=6 t=606.85335ms
INFO [10-29|09:06:03.927] Op approved 
INFO [10-29|09:06:04.525] error occurred during execution          error="ReferenceError: 'OnApprovedTx' is not defined"
DEBUG[10-29|09:06:04.525] Served account_signTransaction           conn=127.0.0.1:45844 reqid=7 t=601.932392ms
```

If helpful, I'm running with these flags:

```shell
clef \
  --chainid 5 \
  --configdir ./clef \
  --keystore ./keystore \
  --rules ./rules.js \
  --nousb \
  --advanced \
  --ipcdisable \
  --rpc \
  --rpcport 45821 \
  --loglevel 5
```

**Comment by karalabe** [comment]
Ping @holiman

**Comment by holiman** [comment]
Warnings are sent to the ui. Do you use rule-based approval? Then I can't recall if they are sent to the ui, but the CLI should display them.

**Comment by meowsbits** [comment]
Yea, I'm using a `rules.js` where 

```
$ cat rules.js 
function ApproveTx(req) {
    if (req.transaction.from.toLowerCase() == "0xf215e98b4f0c749fe9b78d0d4fa97ac7c9a4fe11") {
        return "Approve";
    }
```

**Comment by meowsbits** [comment]
And, perhaps also interestingly, it `clef` doesn't seem to be validating the checksum of the `from` account address, just `to`.

**Comment by holiman** [comment]
> And, perhaps also interestingly, it seems clef isn't validating the checksum of the from account address, just to.

There's no point checking the checksum on the `from` -- either you have the address and can do the signing, or you don't. So a mistyped address will simply fail. Whereas on the `to` part, a mistyped address can cause loss of funds.

**Comment by meowsbits** [comment]
Got it, makes sense. Although I might suggest that this reasoning is not immediately apparent, and that given the apparent asymmetry (Why checksum one field and not the other?) this can be IMO a little counter-intuitive. Is there anything to lose by validating checksums for all address fields just for the sake of consistency?

**Comment by meowsbits** [comment]
Anyways, maybe this discussion should be spun off somewhere else ;) 

And 
- do you want to spin the issue above about missing warnings off into it's own Issue?
- do you want to spin the issue above about the wiki documentation being wrong into it's own Issue?

**Comment by holiman** [comment]
>  (Why checksum-validate one field and not the other?)

Checksumming `to` prevents accidentally sending to a wrong recipient (funds lost forever)
Checksumming 'from' prevenst accidentally trying to send from an address you do not control -- which will fail anyway. 

 >  Is there anything to lose by validating checksums for all address fields just for the sake of consistency?

Yes, why add more errors for the user to run into when it's not needed? 

> do you want to spin the issue above about missing warnings off into it's own Issue?

I don't see what the issue is around missing warnings...? 

> do you want to spin the issue above about the wiki documentation being wrong into it's own Issue?

SGTM, thanks

**Comment by meowsbits** [comment]
> There's no point checking the checksum on the from -- either you have the address and can do the signing, or you don't. So a mistyped address will simply fail. Whereas on the to part, a mistyped address can cause loss of funds. (https://github.com/ethereum/go-ethereum/issues/20214#issuecomment-550271999)
> Checksumming 'from' prevenst accidentally trying to send from an address you do not control -- which will fail anyway (https://github.com/ethereum/go-ethereum/issues/20214#issuecomment-638719860)

I think these are unreasonable assumptions. Are users not able to control multiple, even very many addresses...? Why would I not want the same checks to ensure that I am indeed sending from the address I expect as I am sending it _to_ the address I expect?  Should we really design these programs to be less careful about senders than recipients? 

I could dox myself. I could accidentally send 4 thousand transactions from the company's tax account instead of its commercial account. I could send from the pool owner and not the pool manager. I could send a payment on behalf of the wrong client. Sure, some cases are recoverable. But not all of them. And they're all irreversible.

> Yes, why add more errors for the user to run into when it's not needed?

Why add errors at all? But this is my point; it's not about _more_ errors. It's about understandable errors. _Symmetric_ errors (say, errors which happen consistently for the parameters I can observe) are errors helpful to me as a user because they present a pattern that I can understand and fix. Asymmetric errors, not the number of errors, are what, to me, is the source of confusion and frustration;  Why is the program erroring for the `to` and not `from`? Are they not both addresses?
