### ISSUE TITLE
How to deal with the memory pool when the amount of several consecutive transactions is insufficient

### ISSUE THREAD

**Issue by vae520283995** [ethereum/go-ethereum#20237]
I transferred three transactions in a short period of time consecutively: nonce is 169, 170, 171. The transaction is in the pending state. The transaction balance with nonce of 169 is enough, so he was packed by the miner, but 171 disappeared. After I recharge, 170 was packed by the miner. What's the situation

**Comment by karalabe** [comment]
Geth will drop any transactions that cannot be executed due to the account not having enough balance. There's no way we can keep unexecutable transactions around, hoping that they will become valid in the future.

**Comment by vae520283995** [comment]
> Geth will drop any transactions that cannot be executed due to the account not having enough balance. There's no way we can keep unexecutable transactions around, hoping that they will become valid in the future.

![image](https://user-images.githubusercontent.com/30487254/68177999-2e2f4200-ffc5-11e9-9602-5475e3ca8dc0.png)
These eight are consecutive transfers from 06:33 to 06:34 on November 3, 2019
When nonce is 169, the balance is enough. The balance is 0.0538538
But the balance of nonce 170 send 0.119 ether and 171 send 0.143 ether was not enough to send, so 171 was deleted, but 170 was saved. After recharging 2.7 eth, 170 was packed by the miner at the same time of recharging. 171 I manually used the original transaction to go to etherscan.io to broadcast

**Comment by karalabe** [comment]
There are a few possible answers:

- If you use Geth to broadcast your transactions, Geth will cache all locally created tx and will try to push them back into the network from time to time (when new peer connections are made).
- Etherscan and Infura AFAIK use custom transaction caching and rebroadcasting, so it also might come from them.

All in all once a transaction is signed, there's a non-zero chance that someone will keep it around even if it's not executable yet (out of balance) and submit it later. Also each client implementation behaves differently wrt tx pooling, so it can also happen that even though Geth drops it, Besu or some other clients keeps it and republishes it.

**Comment by vae520283995** [comment]
> There are a few possible answers:
> 
> * If you use Geth to broadcast your transactions, Geth will cache all locally created tx and will try to push them back into the network from time to time (when new peer connections are made).
> * Etherscan and Infura AFAIK use custom transaction caching and rebroadcasting, so it also might come from them.
> 
> All in all once a transaction is signed, there's a non-zero chance that someone will keep it around even if it's not executable yet (out of balance) and submit it later. Also each client implementation behaves differently wrt tx pooling, so it can also happen that even though Geth drops it, Besu or some other clients keeps it and republishes it.

thank you very much
