### ISSUE TITLE
How to specify version of geth when I install it using Ubuntu?

### ISSUE THREAD

**Issue by ushiwak** [ethereum/go-ethereum#20230]
Hi there,

I'm a student studying ethereum now.
Now, I confuse I cant send transaction in latest version of geth.

So I want to re-install older version of geth using Ubuntu. Please tell me how to do it.

[Current status]
~$ sudo apt-get install ethereum=1.8.20-stable-24d727b6d6
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    E: Version '1.8.20-stable-24d727b6d6' for 'ethereum' was not found

~$ sudo apt-get install ethereum=1.8.20
     Reading package lists... Done
     Building dependency tree       
     Reading state information... Done
     E: Version '1.8.20' for 'ethereum' was not found

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
