### ISSUE TITLE
Memory consumption got much bigger after commit tx for a while

### ISSUE THREAD

**Issue by ayeteng** [ethereum/go-ethereum#20245]
Hi there,

#### System information

Geth version: 1.9.6
OS & Version: OSX
Commit hash : stable

#### Expected behaviour
Perform a PoA environment by geth which can get tx committed by web3

#### Actual behaviour
The memory usage become much bigger after running for a while. 

#### Steps to reproduce the behaviour
geth --datadir=~/.ethereum/testnet --networkid=9999 --rpc --rpcvhosts=* --rpcaddr=0.0.0.0 --rpcapi=admin,db,eth,debug,miner,net,shh,txpool,personal,web3,clique --rpccorsdomain=* --verbosity=3 --nodiscover --syncmode=full --cache=512 --ws --wsapi=admin,db,eth,debug,miner,net,shh,txpool,personal,web3,clique --wsorigins=* --wsaddr=0.0.0.0 --wsport=7546 --rpcport=7545 --allow-insecure-unlock --mine --unlock 0x175EC34c2B390a4E2195390FE03A83907e594390 --password pass.txt &

The memory snapshop:
$ top -l 1 |grep geth
14279  geth             0.0  00:24.26 18    2   180+   180M+  0B     0B     14278 1     sleeping *0[1+]     0.00000 0.00000    501 148938+   163+   756850+   358191+   606798+   806182+   448134+   1236+   46592   0.0   john             N/A    N/A   N/A   N/A   N/A   N/A

after running for a while with some tx transaction:
$ top -l 1 |grep geth
14279  geth             0.0  01:23.13 18    2   180+   10G+  0B   19G+   14278 1     stuck    *0[1+]     0.00000 0.00000    501 6305687+  163+   855294+   404766+   752952+   911100+   1166822+  1262+   124544  0.0   john             N/A    N/A   N/A   N/A   N/A   N/A

The memory usage from 180M to 10G.

**Comment by ayeteng** [comment]
Found it might related with --allow-insecure-unlock. When not use this parameter, the memory consumption is acceptable.

$ top -l 1 |grep geth
1083  geth             0.0  27:56.89 22    3   199+   209M+  0B     132M+  1076 1076 sleeping *0[1+]     0.00000 0.00000    501 5664098+ 172+   1970577+  932533+   10701648+ 2099150+  7796017+  156+    112456  0.0   john             N/A    N/A   N/A   N/A   N/A   N/A

**Comment by ligi** [comment]
I think this issue can be closed then - right?

**Comment by ayeteng** [comment]
I think some of people still need to use --allow-insecure-unlock parameter. Not sure if we can close such memory issue by far.

**Comment by karalabe** [comment]
My guess is you exposed your node over the internet and bots are brute forcing your account password (which causes high mem usage). **Never expose your RPC APIs to the internet.**
