### ISSUE TITLE
Getting "gas required exceeds allowance or always failing transaction" when using web3js but transaction works fine when done from console

### ISSUE THREAD

**Issue by tanaybhartia** [ethereum/go-ethereum#20246]
#### System information

Geth version: `1.9.3-stable-cfbb969d`
OS & Version: Ubuntu 18.04.3 LTS

#### Expected behaviour
Transaction receipt

#### Actual behaviour
Returned error: gas required exceeds allowance (91135865401031) or always failing transaction

#### Steps to reproduce the behaviour
I  have created a private network with the following genesis block (similar response even if I alloc an account with ether):
```
{
"config": {
"chainId": 16,
"homesteadBlock": 0,
"eip155Block": 0,
"eip158Block": 0
},
"constantinopleBlock": 1,
"petersburgBlock": 1,
"alloc": {
	"0xc3ec8cfb877b639094d2bc4bb99651dcb0c36aff": { 
		"balance": "1000000000000000000000000000000000000000"
		}
	},
"difficulty" : "200",
"gasLimit" : "99999999999999"
}
```
I have the following command to run the network:

`geth --datadir ./exp4 --networkid 16 --rpc --rpcapi "eth,net,web3,personal,miner" --nodiscover --allow-insecure-unlock --port 3000 console`

This is my truffle contract:

```
pragma solidity ^0.5.8;
contract Hello {
   string public message;
   function HelloWorld() public{
       message = "Hello, World : This is a Solidity Smart Contract on the Private Ethereum Blockchain ";
   }
}
```
Truffle Config: 

```
rpc: {
    host:"localhost",
    port:8545
},
networks: {
    development: {
        host: "127.0.0.1",     // Localhost (default: none)
        port: 8545,            // Standard Ethereum port (default: none)
        network_id: "16",      // Any network (default: none)
        from: "0xc3ec8cfb877b639094d2bc4bb99651dcb0c36aff",
        gas: 20000000
    }
}
```

This is the nodejs script that I am running:
 
```
var Web3 = require('web3')
var web3_http = new Web3(new Web3.providers.HttpProvider('http://127.0.0.1:8545'));
const fs = require('fs');
const con = JSON.parse(fs.readFileSync('./build/contracts/Hello.json', 'utf8'));
var abi = con.abi;
web3_http.eth.getBalance("0xc3ec8cfb877b639094d2bc4bb99651dcb0c36aff")
.then(console.log);
var cont = new web3_http.eth.Contract(abi, "0xdCf9a6832Fae44B081f62513D04c2E30fB9a6A00");
console.log(cont);

cont.methods.HelloWorld().estimateGas({from: "0xc3ec8cfb877b639094d2bc4bb99651dcb0c36aff"})
.then(function(gasAmount){
    console.log(gasAmount);
})
.catch(function(error){
    console.log(error);
});
```

`0xc3ec8cfb877b639094d2bc4bb99651dcb0c36aff` is the account address and `0xdCf9a6832Fae44B081f62513D04c2E30fB9a6A00` is the address at which my contract is deployed. It shows correct ether value for my account and fetches the contract correctly but gives a gas limit exceeding error when estimating gas.

But when I access the contract through Truffle console, it works fine and the transaction is successful. Truffle code:

 ```
let instance = await Hello.deployed()  
instance.HelloWorld()
```
If there is an actual error for gas exceed, then it should be the same whether I use web3js or console but I don't get this error while submitting transactions through truffle console.

Thank you.

**Comment by karalabe** [comment]
Your chain config seems very wrong (half the fields are outside of it). Please fix according to

```
  "config": {
    "chainId": <arbitrary positive integer>,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0
  },
```
