### ISSUE TITLE
Docs: Remove run-hints from FreeBSD installation page

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#20255]
The installation page https://geth.ethereum.org/docs/install-and-build/installing-geth at the FreeBSD via `pkg` section contains a note on how to run Geth. This should imho be removed as we should have a uniform global page on how to run geth, not a tiny one on one specific platform on one specific package manager.

![Screenshot from 2019-11-08 11-42-06](https://user-images.githubusercontent.com/129561/68466688-94160680-021d-11ea-99fa-0011de976df8.png)

**Comment by ChrisChinchilla** [comment]
@karalabe Good call, I think I did review that page recently and didn't notice it, but I will do this as part of a re-review after the recent PR from @fjl anyway.
