### ISSUE TITLE
Does Geth sync with a private or public network? 

### ISSUE THREAD

**Issue by bayanhd** [ethereum/go-ethereum#20253]
Hi
I'm new to the Blockchain world, lacking experience and I'm looking for some assistance.
I'm just syncing with ethereum network by using Geth and rinkeby network
by using this command:
`geth --rinkeby --rpc --rpcapi="personal,eth,network,web3,net" --ipcpath "\\\\.\\pipe\\'\\\\.\\pipe\\geth.ipc"`
but I cannot know what type of network I was syncing with? Is it private or public?
and what are the differences between both, as we can see for all transactions detail for both?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
