### ISSUE TITLE
How to get "Internal"  transactions

### ISSUE THREAD

**Issue by xuehuizhang** [ethereum/go-ethereum#20250]
How to get "Internal" transactions in etherscan?

now，I can use a third-party interface

example: [link](http://api.etherscan.io/api?module=account&action=txlistinternal&address=0x2c1ba59d6f58433fb1eaee7d20b26ed83bda51a3&startblock=0&endblock=2702578&sort=asc&apikey=YourApiKeyToken)

but i have many address，this way is very slow，How can I get it quickly？

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
