### ISSUE TITLE
Getting 0 tether on local getBalance()

### ISSUE THREAD

**Issue by navitern** [ethereum/go-ethereum#20259]
Hi,

I face the problem of getting a balance of erc-20 on local accounts.

`> eth.accounts`
`["0x6c197808a849b9157422ed33d821e8e6e29ad8f8", "0x6e062dc98a5e4d7e494cb8c4b4d8cf40e8a4d958"]`

`> eth.coinbase`
`"0x6c197808a849b9157422ed33d821e8e6e29ad8f8"`

`> web3.fromWei(eth.getBalance(eth.coinbase), "tether")`
`0`

`> web3.fromWei(eth.getBalance('0x6c197808a849b9157422ed33d821e8e6e29ad8f8'), "tether")`
`0`

`> web3.fromWei(eth.getBalance('0x6c197808A849B9157422Ed33d821e8e6E29Ad8F8'), "tether")`
`0`

Etherscan telling me that tokens are already on the address.
![Screenshot from 2019-11-11 11-28-55](https://user-images.githubusercontent.com/25767601/68572594-d9814080-0476-11ea-90fb-6ac9dacf1f3b.png)

Chain is configured, synced and is on current block.
`> eth.syncing`
`false`

And I can see balances on other, not my local,  addresses.
`> web3.fromWei(eth.getBalance('0xD72D878EC833788a087fD613BDdd9A15Bcb6eF2d'), "tether")`
`4.4612e-15`

#### System information

Geth version: `1.9.6-stable`
OS & Version: Ubuntu 18.04
Git Commit: `bd05968077f27f7eb083404dd8448157996a8788`
Architecture: amd64
Protocol Versions: [63]
Network Id: 1
Go Version: go1.11.5
Operating System: linux

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

Please see the documentation to web3.fromWei - it does not do what you think it does. Please read the documentation or ask on stackoverflow how to do what you want to do
