### ISSUE TITLE
Rinkeby Ether Faucet too many requests

### ISSUE THREAD

**Issue by hmpch** [ethereum/go-ethereum#20258]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
just tried the faucet and it worked. Can you give some more details? Which method did you use? I just tried with twitter.
