### ISSUE TITLE
website/docs: Write missing doc pages

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20260]
- [x] light client overview (@adamschmideg)
- [x] geth system requirements
- [x] command line options (@fjl)
- [x] puppeth
- [x] config file (@ChrisChinchilla)
- [x] ethclient
- [x] Go API
- [x] Geth architecture overview (consensus engine, etc)
- [x] sync modes (@ChrisChinchilla)
- [x] graphql
- [x] clef ui
- [x] hardware requirements
- [ ] goevmlab / traceview
- [x] caching (gcmode, flushing tries after timeout etc.)
- [x] update FAQ page re fast sync being dropped and common snap sync issues
- [x] individual built-in tracers (e.g. `prestateTracer`, `unigramTracer` etc.)
- [x] other built-in commands like `devp2p`, `abigen`, etc.
- [x] more in-depth cli cmd description: e.g. how to prune your node

**Comment by MariusVanDerWijden** [comment]
Please don't ask if you can work on this, just pick a topic that you want to write about and send a pr if you think you have appropriately captured the topic.

**Comment by vj-codes** [comment]
@ligi @adamschmideg what branch should I push the code to?
TIA

**Comment by jmcook1186** [comment]
if you are adding docs please raise a PR to the `gh-pages` branch.

**Comment by holiman** [comment]
` goevmlab / traceview` should _not_ have a doc-section in the go-ethereum repo, it is a standalone repo. 
Looks like we can (almost?) close this ticket?

**Comment by jmcook1186** [comment]
i think it would be good to also add a page on config files. At the moment they are only mentioned in the "connecting to the network" page. I'll do this asap and then I agree this can be closed out.

**Comment by lightclient** [comment]
We have a page on config files now: https://geth.ethereum.org/docs/fundamentals/config-files

This ticket looks closed out :+1:
