### ISSUE TITLE
abigen produces invalid go-code, redeclares structs

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum/go-ethereum#20282]
Hey guys, 
I'm currently running into a bug while generating go-bindings out of our smart contracts. 

Our current setup of the contract is the following: 
contract X contains the definition of struct2
contract A includes contract B
contract B includes contract X
contract A includes contract X
both A and B use struct2 as function parameters for public + external functions.

If I generate the go bindings for A like this
`go:generate abigen --pkg a --sol A.sol --out ../a/a.go`
Abigen generates some structs twice. e.g. 

```
// Struct2 is an auto generated low-level Go binding around an user-defined struct.
type Struct2 struct {
	a   []common.Address
	b [][]*big.Int
	c   []Struct1
}

//...

// Struct2 is an auto generated low-level Go binding around an user-defined struct.
type Struct2 struct {
	a   []common.Address
	b [][]*big.Int
	c   []Struct1
}
```
The issue still persists with ```1.9.7-stable-a718daa6```

**Comment by MariusVanDerWijden** [comment]
Nvm it was fixed in a newer version, since solidity ^v0.5.11 includes the struct names

**Comment by MariusVanDerWijden** [comment]
It even persists with `abigen version 1.9.8-unstable-22e3bbbf` which includes https://github.com/ethereum/go-ethereum/pull/20179

**Comment by rjl493456442** [comment]
@MariusVanDerWijden Can you please share some code snippets so that we can reproduce? 

```
contract X contains the definition of struct2
contract A includes contract B
contract B includes contract X
contract A includes contract X
both A and B use struct2 as function parameters for public + external functions
```

Do you mean?

```
contract X {
     struct2
}
contract B is X {...}
contract A is B, X {...}
```

**Comment by MariusVanDerWijden** [comment]
@rjl493456442 
```
pragma solidity 0.5.12;
pragma experimental ABIEncoderV2;

library X {
    struct Params{
		uint256 challengeDuration;
		uint256 nonce;
		address app;
	}
}

contract A {
    function funA(X.Params memory params) public {
        // Do stuff
    }
}

contract B {
    function funB(X.Params memory params) public {
        // Do stuff
    }
}
```
