### ISSUE TITLE
block.timestamp returning 0

### ISSUE THREAD

**Issue by tymat** [ethereum/go-ethereum#2029]
```
  function getBlockTime() public returns (uint256) {
    uint256 _ts = block.timestamp;
    return _ts;
  }
```
Calling this function returns 0.
When called as part of a contract constructor it returns the correct value.  

Not sure if this is Solidity or go-ethereum issue at this point. 

**Version**
```
Geth/v1.3.1

solc, the solidity compiler commandline interface
Version: 0.1.6-22723da1/RelWithDebInfo-Darwin/unknown/JIT linked to libethereum-1.1.0-16476b37/RelWithDebInfo-Darwin/unknown/JIT

```

**Comment by obscuren** [comment]
@tymat any update on this? Have you discussed this with @chriseth perhaps?

**Comment by tymat** [comment]
@obscuren haven't been able to catch him online last night.  Will try again today.

**Comment by tymat** [comment]
This can be closed.
