### ISSUE TITLE
The Gas needed is too high

### ISSUE THREAD

**Issue by lwshanbd** [ethereum/go-ethereum#20319]
Now,I want to send eth to my contracts on my private chian. However, two similar contracts need different gas. According to 'estimateGas' function,  one needs about 21000 while another needs about 30000000. So I want to know how I can solve this problem. By change geth source code and recompile or I need some other commands to reduce the amount of gas the second contract needs？

The contract as follow：
```
https://etherscan.io/address/0x09515cb5e3acaef239ab83d78b2f3e3764fcab9b#code
https://etherscan.io/address/0x9d31ff892f984a83e8b342a5ece8e8911ed909e0#code
```

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
