### ISSUE TITLE
go-ethereum changed data from contract

### ISSUE THREAD

**Issue by olda220** [ethereum/go-ethereum#20333]
Hi, when i store to contract byte array with zero on the begin byte[] foo = [0,1,2,3], then in web3 i get corretly all array, but in golang i get only [1,2,3]. Is there way to get all array?

**Comment by karalabe** [comment]
Could you please provide a repro?

**Comment by olda220** [comment]
> Could you please provide a repro?

No, i test this localy only. I mean go code, the contract is on Kovan, but problem must be in go, because web3 read all data. I generate go file by abigen and use ABIEncoderV2, because i use two dimensional array [][]byte. 
In remix i get this (correctly)
![image](https://user-images.githubusercontent.com/10205982/69224803-7a5db300-0b7d-11ea-987d-57a396a0b3b3.png)

but in go i get 
![image](https://user-images.githubusercontent.com/10205982/69224898-9e20f900-0b7d-11ea-80d9-d8918b684d52.png)

**Comment by olda220** [comment]
I don't know maybe go-ethereum takes a byte array like ascii char, and value 0 like empty char, so it is trimmed.

**Comment by karalabe** [comment]
Can you please provide a contract address and abi + call parameters so we might repro?

**Comment by olda220** [comment]
Contract 0x6a0593B9BA935db53950B487F0dcA064eb6553BC on Kovan
Method without parameters 0x370158ea

`{
  "constant": true,
  "inputs": [],
  "name": "info",
  "outputs": [
    {
      "internalType": "address",
      "name": "carrierAddress",
      "type": "address"
    },
    {
      "internalType": "uint256",
      "name": "_carrierId",
      "type": "uint256"
    },
    {
      "components": [
        {
          "internalType": "bytes10",
          "name": "fromLat",
          "type": "bytes10"
        },
        {
          "internalType": "bytes11",
          "name": "fromLng",
          "type": "bytes11"
        },
        {
          "internalType": "bytes10",
          "name": "toLat",
          "type": "bytes10"
        },
        {
          "internalType": "bytes11",
          "name": "toLng",
          "type": "bytes11"
        }
      ],
      "internalType": "struct Trip.TripLoc",
      "name": "_tripLoc",
      "type": "tuple"
    },
    {
      "internalType": "uint256",
      "name": "_price",
      "type": "uint256"
    },
    {
      "internalType": "bytes[]",
      "name": "_schedule",
      "type": "bytes[]"
    },
    {
      "internalType": "uint8",
      "name": "_places",
      "type": "uint8"
    },
    {
      "internalType": "bytes",
      "name": "_description",
      "type": "bytes"
    },
    {
      "internalType": "bool",
      "name": "_enabled",
      "type": "bool"
    },
    {
      "internalType": "address",
      "name": "_token",
      "type": "address"
    },
    {
      "internalType": "enum TransportH.RouteType",
      "name": "_routeType",
      "type": "uint8"
    }
  ],
  "payable": false,
  "stateMutability": "view",
  "type": "function"
}`

The value is stored in **_schedule**

**Comment by olda220** [comment]
Now i try simple call the contract: 
![image](https://user-images.githubusercontent.com/10205982/69227597-610b3580-0b82-11ea-9839-d3e7b6354290.png)
And the result is without zero
![image](https://user-images.githubusercontent.com/10205982/69227666-8009c780-0b82-11ea-9c2c-df920817b2ff.png)
I need
0 1 163 31 47 63 79 93 10 107 196 250 242 47 31 31 30 123 ....

**Comment by olda220** [comment]
In MEW looks okay, schedule started with zero on start:
0x01a31f2f3f4....
![image](https://user-images.githubusercontent.com/10205982/69228953-ce1fca80-0b84-11ea-9fec-c82a0c5f4e08.png)
