### ISSUE TITLE
The hard fork of Istanbul will change pow to ProgPow?

### ISSUE THREAD

**Issue by DinoStray** [ethereum/go-ethereum#20345]
Istanbul is coming soon.
Will the ProgPow be active at that time?
If not, when the ProgPow will be active?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
