### ISSUE TITLE
Disable recording state trie preimages

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#20344]
A current full-synced node looks like this:

```
+-----------------+--------------------+------------+
|    DATABASE     |      CATEGORY      |    SIZE    |
+-----------------+--------------------+------------+
| Key-Value store | Headers            | 49.10 MiB  |
| Key-Value store | Bodies             | 1.84 GiB   |
| Key-Value store | Receipts           | 3.72 GiB   |
| Key-Value store | Difficulties       | 8.60 MiB   |
| Key-Value store | Block number->hash | 7.63 MiB   |
| Key-Value store | Block hash->number | 350.68 MiB |
| Key-Value store | Transaction index  | 19.66 GiB  |
| Key-Value store | Bloombit index     | 1.20 GiB   |
| Key-Value store | Trie nodes         | 246.71 GiB |
| Key-Value store | Trie preimages     | 19.17 GiB  |
| Key-Value store | Clique snapshots   | 0.00 B     |
| Key-Value store | Singleton metadata | 139.00 B   |
| Ancient store   | Headers            | 3.63 GiB   |
| Ancient store   | Bodies             | 69.73 GiB  |
| Ancient store   | Receipts           | 29.50 GiB  |
| Ancient store   | Difficulties       | 136.95 MiB |
| Ancient store   | Block number->hash | 321.76 MiB |
| Light client    | CHT trie nodes     | 0.00 B     |
| Light client    | Bloom trie nodes   | 0.00 B     |
+-----------------+--------------------+------------+
|                         TOTAL        | 396.00 GIB |
+-----------------+--------------------+------------+
```

Part of this is 20GB wasted for the pre-images. One option is to completely disable recording pre-images. Another is to introduce an in-memory GC for them similar to the trie GC (simpler as there are no ref graphs, just a single counter).

Posting this as an issue so the idea doesn't get lost.

**Comment by holiman** [comment]
I have an alternate proposal. The `20Gb` of preimage contains 50% preimages and 50% postmages. The postimages are fully derive:able from the preimages, so if we nuke those we've cut down `50%`. 
If we also nuke the index, and dump it all out into a memory mapped file, we can probably shave down from `20Gb` to `8Gb` or less. 

So then we'd wind up with a binary dump of preimages. Doing a binary search means `O(n log(n))` `sha3` operations/disk access, and so would an insert. We basically never ever search, so that's fine, and we could do inserts on some append-only file and compact it once every blue moon (e.g. at startup or shutdown)

Anyway, it's non-core data, that wouldn't have to live in leveldb.

**Comment by rjl493456442** [comment]
How can we count the reference of preimages? Preimages are bound with accounts or storage entries, 1 key has 1 preimage.

**Comment by lyh169** [comment]
> A current full-synced node looks like this:
> 
> ```
> +-----------------+--------------------+------------+
> |    DATABASE     |      CATEGORY      |    SIZE    |
> +-----------------+--------------------+------------+
> | Key-Value store | Headers            | 49.10 MiB  |
> | Key-Value store | Bodies             | 1.84 GiB   |
> | Key-Value store | Receipts           | 3.72 GiB   |
> | Key-Value store | Difficulties       | 8.60 MiB   |
> | Key-Value store | Block number->hash | 7.63 MiB   |
> | Key-Value store | Block hash->number | 350.68 MiB |
> | Key-Value store | Transaction index  | 19.66 GiB  |
> | Key-Value store | Bloombit index     | 1.20 GiB   |
> | Key-Value store | Trie nodes         | 246.71 GiB |
> | Key-Value store | Trie preimages     | 19.17 GiB  |
> | Key-Value store | Clique snapshots   | 0.00 B     |
> | Key-Value store | Singleton metadata | 139.00 B   |
> | Ancient store   | Headers            | 3.63 GiB   |
> | Ancient store   | Bodies             | 69.73 GiB  |
> | Ancient store   | Receipts           | 29.50 GiB  |
> | Ancient store   | Difficulties       | 136.95 MiB |
> | Ancient store   | Block number->hash | 321.76 MiB |
> | Light client    | CHT trie nodes     | 0.00 B     |
> | Light client    | Bloom trie nodes   | 0.00 B     |
> +-----------------+--------------------+------------+
> |                         TOTAL        | 396.00 GIB |
> +-----------------+--------------------+------------+
> ```
> 
> Part of this is 20GB wasted for the pre-images. One option is to completely disable recording pre-images. Another is to introduce an in-memory GC for them similar to the trie GC (simpler as there are no ref graphs, just a single counter).
> 
> Posting this as an issue so the idea doesn't get lost.

How can i statistic this Key-Value space usage?

**Comment by rjl493456442** [comment]
@lyh169 `geth inspect`

**Comment by lyh169** [comment]
> @lyh169 `geth inspect --datadir <dir>`

ok  thank you

**Comment by holiman** [comment]
AS far as I know, we did disable this long ago
