### ISSUE TITLE
What is the current version of the master branch?

### ISSUE THREAD

**Issue by Tongnm** [ethereum/go-ethereum#20343]
I want update to geth1.9.7, so which branch should I download?

**Comment by ligi** [comment]
Why don't you checkout the tag v1.9.7 then? master has some commits on top of 1.9.7 - but is not yet tagged as 1.9.8

**Comment by Tongnm** [comment]
> Why don't you checkout the tag v1.9.7 then? master has some commits on top of 1.9.7 - but is not yet tagged as 1.9.8

ok，thanks
