### ISSUE TITLE
bring back the stale bot

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#20348]
seems the stale bot is not active anymore - let's investigate and bring it back
Perhaps @jpitts has an idea - as he is currently in communication with github for another issue (actions)

Indicator it is not working here:

https://github.com/ethereum/go-ethereum/issues/16844

the issue should have been closed by the bot long time ago

**Comment by adamschmideg** [comment]
It's active, but it may take it longer to mark an issue stale. As we discussed in an issue triage session, we'd rather not close issues automatically.
