### ISSUE TITLE
geth attach http://127.0.0.1:8545 --allow-insecure-unlock Incorrect Usage: flag provided but not defined: -allow-insecure-unlock

### ISSUE THREAD

**Issue by ArtieLadie** [ethereum/go-ethereum#20378]
**geth attach http://127.0.0.1:8545 --allow-insecure-unlock** gives error

**Incorrect Usage: flag provided but not defined: -allow-insecure-unlock**

Even tried **sudo geth attach http://127.0.0.1:8545 --allow-insecure-unlock**

**Comment by rjl493456442** [comment]
`-allow-insecure-unlock` flag can't be used in `attach` command.
