### ISSUE TITLE
geth does not persist trie node data from memory to disk on ungraceful system restart

### ISSUE THREAD

**Issue by ryzhak** [ethereum/go-ethereum#20383]
Hello everybody!

Issue: geth 1.8.22 starts mining from one of the first blocks instead of the last one on system reboot.

**System information**

Geth version: `1.8.22-stable-7fa3509e`
OS & Version: Linux Mint 19

**What we have**

We have 3 synced private geth nodes using PoA(clique).

**What happened**

One day(a week ago) we had issues with our hosting provider so we had to restart 2 out of 3 nodes(each node is on separate VPS). Current block is 4 000 000. When node 1 and node 2 were restarted they started mining from block 372 instead of the last one 4 000 000.

**Why it happened (my guess)**

Geth 1.8.22 keeps some data with trie node data in RAM instead of a disk. On graceful node shutdown(for example from console) this trie node data is saved to hard drive from RAM. On forced system shutdown(for example from hosting admin panel) trie node data does not have time to be saved on a hard drive. We had our nodes running for 6 months without any reboot so I think that this trie node data was kept in RAM for the whole time and it was vanished on system reboot(though we still have node 3 which is up and running).

**Logs**

Here are the logs when I'm trying to run the backup version of one of the nodes:
```
vladimir@comp:~/Public/projects/ethereum/repro-geth-bug/geth-linux-amd64-1.8.22-7fa3509e$ ./geth --datadir ../opt/ethereum/data/ --networkid 1515 --unlock 0xd6ee38421e1713dd50e888c6d689b82953946bc3 --password ../opt/ethereum/unlock_password --port 30306 --mine
INFO [11-21|17:06:25.374] Maximum peer count                       ETH=25 LES=0 total=25
INFO [11-21|17:06:25.374] Starting peer-to-peer node               instance=Geth/v1.8.22-stable-7fa3509e/linux-amd64/go1.11.5
INFO [11-21|17:06:25.374] Allocated cache and file handles         database=/home/vladimir/Public/projects/ethereum/repro-geth-bug/opt/ethereum/data/geth/chaindata cache=512 handles=2048
INFO [11-21|17:06:26.550] Initialised chain configuration          config="{ChainID: 1515 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: 5  ConstantinopleFix: <nil> Engine: clique}"
INFO [11-21|17:06:26.550] Initialising Ethereum protocol           versions="[63 62]" network=1515
WARN [11-21|17:06:26.579] Head state missing, repairing chain      number=4073749 hash=9bfb53…56d503
INFO [11-21|17:07:45.179] Rewound blockchain to past state         number=371     hash=102018…d91947
INFO [11-21|17:07:45.180] Loaded most recent local header          number=4073749 hash=9bfb53…56d503 td=8147499 age=2d5h43m
INFO [11-21|17:07:45.180] Loaded most recent local full block      number=371     hash=102018…d91947 td=743     age=7mo3w6d
INFO [11-21|17:07:45.180] Loaded most recent local fast block      number=4073749 hash=9bfb53…56d503 td=8147499 age=2d5h43m
INFO [11-21|17:07:45.180] Loaded local transaction journal         transactions=3 dropped=3
INFO [11-21|17:07:45.180] Regenerated local transaction journal    transactions=0 accounts=0
WARN [11-21|17:07:45.180] Blockchain not empty, fast sync disabled 
INFO [11-21|17:07:45.623] New local node record                    seq=6 id=e8c5a9e8848d4e30 ip=127.0.0.1 udp=30306 tcp=30306
INFO [11-21|17:07:45.623] Started P2P networking                   self=enode://9647000ba2579dd529574b49f472f029839a09257c1bc3ade5135cbbb5f3ceaf1237aff5b6b947d2fa4f218fa24858dc2767bd4b78e082b04c9d013c1482cfa6@127.0.0.1:30306
INFO [11-21|17:07:45.624] IPC endpoint opened                      url=/home/vladimir/Public/projects/ethereum/repro-geth-bug/opt/ethereum/data/geth.ipc
INFO [11-21|17:07:46.192] Unlocked account                         address=0xd6ee38421e1713dD50E888c6D689B82953946bC3
INFO [11-21|17:07:46.192] Transaction pool price threshold updated price=1000000000
INFO [11-21|17:07:46.192] Transaction pool price threshold updated price=1000000000
INFO [11-21|17:07:46.192] Etherbase automatically configured       address=0xd6ee38421e1713dD50E888c6D689B82953946bC3
INFO [11-21|17:07:46.192] Commit new mining work                   number=372     sealhash=685e15…2c52df uncles=0 txs=0 gas=0 fees=0 elapsed=75.951µs
INFO [11-21|17:07:46.192] Successfully sealed new block            number=372     sealhash=685e15…2c52df hash=0c60ef…f29e6b elapsed=385.27µs
INFO [11-21|17:07:46.192] 🔨 mined potential block                  number=372     hash=0c60ef…f29e6b
INFO [11-21|17:07:46.193] Commit new mining work                   number=373     sealhash=337ae5…2b4704 uncles=0 txs=0 gas=0 fees=0 elapsed=222.362µs
INFO [11-21|17:07:47.962] Mapped network port                      proto=tcp extport=30306 intport=30306 interface="UPNP IGDv1-IP1"
INFO [11-21|17:07:48.391] Mapped network port                      proto=udp extport=30306 intport=30306 interface="UPNP IGDv1-IP1"
INFO [11-21|17:07:49.625] New local node record                    seq=7 id=e8c5a9e8848d4e30 ip=128.71.103.50 udp=30306 tcp=30306
INFO [11-21|17:07:51.001] Successfully sealed new block            number=373     sealhash=337ae5…2b4704 hash=b67668…81f164 elapsed=4.807s
INFO [11-21|17:07:51.001] 🔨 mined potential block                  number=373     hash=b67668…81f164
INFO [11-21|17:07:51.002] Commit new mining work                   number=374     sealhash=c0e9f6…628d51 uncles=0 txs=0 gas=0 fees=0 elapsed=1.434ms
INFO [11-21|17:07:56.001] Successfully sealed new block            number=374     sealhash=c0e9f6…628d51 hash=77aae2…9c44e8 elapsed=4.998s
INFO [11-21|17:07:56.001] 🔨 mined potential block                  number=374     hash=77aae2…9c44e8
INFO [11-21|17:07:56.003] Commit new mining work                   number=375     sealhash=6f7db7…adca12 uncles=0 txs=0 gas=0 fees=0 elapsed=1.305ms
^CINFO [11-21|17:07:58.483] Got interrupt, shutting down... 
INFO [11-21|17:07:58.483] IPC endpoint closed                      url=/home/vladimir/Public/projects/ethereum/repro-geth-bug/opt/ethereum/data/geth.ipc
INFO [11-21|17:07:58.483] Writing cached state to disk             block=374 hash=77aae2…9c44e8 root=e16e04…e93be1
INFO [11-21|17:07:58.483] Persisted trie from memory database      nodes=0 size=0.00B time=7.185µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [11-21|17:07:58.483] Writing cached state to disk             block=373 hash=b67668…81f164 root=e16e04…e93be1
INFO [11-21|17:07:58.483] Persisted trie from memory database      nodes=0 size=0.00B time=2.571µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [11-21|17:07:58.484] Writing cached state to disk             block=247 hash=7b422a…5f9a62 root=e16e04…e93be1
INFO [11-21|17:07:58.484] Persisted trie from memory database      nodes=0 size=0.00B time=2.784µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [11-21|17:07:58.484] Blockchain manager stopped 
INFO [11-21|17:07:58.484] Stopping Ethereum protocol 
INFO [11-21|17:07:58.484] Ethereum protocol stopped 
INFO [11-21|17:07:58.484] Transaction pool stopped 
INFO [11-21|17:07:58.497] Database closed                          database=/home/vladimir/Public/projects/ethereum/repro-geth-bug/opt/ethereum/data/geth/chaindata
```

**How to fix**

The 1st thing that comes to mind is to restart geth nodes(gracefully) via cron everyday so that nodes persist trie node data on the disk.

**So question is**: how to handle **UN**graceful system shutdown so that geth node persists data and keeps mining from the latest block on restart? Probably I miss something or have wrong understanding of how geth works.

Hope you got what I mean, thanks in advance

**Comment by karalabe** [comment]
Geth persists data after 1 hour worth of block processing (so for example if your blocks are processed in 100ms, that's 10/s * 60s * 60m = after 36000 blocks). If your network is super light (i.e. mostly empty blocks), it may happen that it takes a very very long time until blocks are flushed.

An ungraceful shutdown should still eventually sync up with the network when connections are made to old nodes that are still healthy, so it should eventually self heal itself.

Currently there is no way to configure the period for these persistency rounds because every piece of data pushed to disk cannot be garbage collected any more, so the more frequent, the more junk. You can hack around the issue currently with your workaround of restarting Geth periodically.

We have an alternative idea in the works that would persist the in-memory state not to the database, rather to a flat file. That will allow users to configure wall-clock timeouts for the backups without adding junk to their databases. Not sure when that will ship however, it's not a high priority feature.

**Comment by ryzhak** [comment]
> If your network is super light (i.e. mostly empty blocks), it may happen that it takes a very very long time until blocks are flushed.

yes, we have a super light network

> An ungraceful shutdown should still eventually sync up with the network when connections are made to old nodes that are still healthy, so it should eventually self heal itself.

yes, but if we had restarted all our nodes at the same time then data would have been lost(or at least we would have to think how to restore it, wonder if it is possible)

> You can hack around the issue currently with your workaround of restarting Geth periodically.

yes, it seems the only option

@karalabe thank you for clarification!

**Comment by balajipachai** [comment]
> Geth persists data after 1 hour worth of block processing (so for example if your blocks are processed in 100ms, that's 10/s * 60s * 60m = after 36000 blocks). If your network is super light (i.e. mostly empty blocks), it may happen that it takes a very very long time until blocks are flushed.
> 
> An ungraceful shutdown should still eventually sync up with the network when connections are made to old nodes that are still healthy, so it should eventually self heal itself.
> 
> Currently there is no way to configure the period for these persistency rounds because every piece of data pushed to disk cannot be garbage collected any more, so the more frequent, the more junk. You can hack around the issue currently with your workaround of restarting Geth periodically.
> 
> We have an alternative idea in the works that would persist the in-memory state not to the database, rather to a flat file. That will allow users to configure wall-clock timeouts for the backups without adding junk to their databases. Not sure when that will ship however, it's not a high priority feature.

This might sound a dumb question:

1. How would I know that the blocks are not yet processed and are still in memory?
2. What if during the periodic restart, a transaction is submitted to the network and all my geth nodes are undergoing periodic restarts?
3. Apart from a workaround is there any fix solution to counter this problem?

**Comment by karalabe** [comment]
1. Blocks are written to disk recent state is not. Whenever Geth flushes state to disk, it prints something along the lines of "Persisted state to disk [...]".
2. Don't do periodic restarts. It just pushes more junk into the database.
3. What's the problem?

**Comment by balajipachai** [comment]
Please find the below logs:
```
INFO [10-08|10:33:36.296] Maximum peer count                       ETH=50 LES=0 total=50
INFO [10-08|10:33:36.296] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
ERROR[10-08|10:33:36.540] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-08|10:33:36.541] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-08|10:33:36.541] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-08|10:33:36.541] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-08|10:33:36.541] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-08|10:33:36.542] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
INFO [10-08|10:33:36.543] Starting peer-to-peer node               instance=Geth/Node1/v1.9.1-stable-b7b2f60f/linux-amd64/go1.11.5
WARN [10-08|10:33:36.544] Sanitizing invalid miner gas price       provided=0 updated=0
INFO [10-08|10:33:36.544] Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
INFO [10-08|10:33:36.544] Allocated cache and file handles         database=/home/ibcadmin/Node1/geth/chaindata cache=512.00MiB handles=524288
INFO [10-08|10:33:36.764] Opened ancient database                  database=/home/ibcadmin/Node1/geth/chaindata/ancient
INFO [10-08|10:33:36.766] Initialised chain configuration          config="{ChainID: 25 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil>  Petersburg: <nil> Engine: clique}"
INFO [10-08|10:33:36.767] Initialising Ethereum protocol           versions=[63] network=25 dbversion=7
WARN [10-08|10:33:36.806] Head state missing, repairing chain      number=554 hash=b3e5c9…8ae258
INFO [10-08|10:33:36.808] Rewound blockchain to past state         number=490 hash=0a243d…6b0b76
INFO [10-08|10:33:36.809] Loaded most recent local header          number=554 hash=b3e5c9…8ae258 td=1109 age=17m53s
INFO [10-08|10:33:36.809] Loaded most recent local full block      number=490 hash=0a243d…6b0b76 td=981  age=18h59m54s
INFO [10-08|10:33:36.809] Loaded most recent local fast block      number=554 hash=b3e5c9…8ae258 td=1109 age=17m53s
INFO [10-08|10:33:36.969] Loaded local transaction journal         transactions=15 dropped=0
INFO [10-08|10:33:36.970] Regenerated local transaction journal    transactions=15 accounts=15
INFO [10-08|10:33:37.287] New local node record                    seq=47 id=e8588b1b796c694a ip=127.0.0.1 udp=30321 tcp=30321
INFO [10-08|10:33:37.290] IPC endpoint opened                      url=/home/ibcadmin/Node1/geth.ipc
INFO [10-08|10:33:37.291] HTTP endpoint opened                     url=http://10.0.10.4:8560         cors=* vhosts=localhost
INFO [10-08|10:33:37.297] Started P2P networking                   self=enode://f73fe00b3bdabfad87b55765f69dbd7d9c28f62f7d20db2fbae23da3c93354add0a605cd312c175dab2914bb487b75fba5fb5e2c26dca79510d6880ccdd1c887@127.0.0.1:30321
ERROR[10-08|10:33:37.542] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-08|10:33:37.543] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-08|10:33:37.543] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
INFO [10-08|10:33:38.201] Unlocked account                         address=0x1e9b9105B313c5AdcBF003aAc21461e88c4Da9AF
INFO [10-08|10:33:38.201] Transaction pool price threshold updated price=0
INFO [10-08|10:33:38.201] Transaction pool price threshold updated price=0
INFO [10-08|10:33:38.201] Etherbase automatically configured       address=0x1e9b9105B313c5AdcBF003aAc21461e88c4Da9AF
INFO [10-08|10:33:38.201] Commit new mining work                   number=491 sealhash=ce85ca…8b06b1 uncles=0 txs=0 gas=0 fees=0 elapsed=126.1µs
INFO [10-08|10:33:38.202] Successfully sealed new block            number=491 sealhash=ce85ca…8b06b1 hash=0de3d9…6ec3ad elapsed=1.064ms
INFO [10-08|10:33:38.202] 🔨 mined potential block                  number=491 hash=0de3d9…6ec3ad
INFO [10-08|10:33:38.203] Commit new mining work                   number=491 sealhash=8c160a…371e24 uncles=0 txs=15 gas=683304 fees=0 elapsed=2.167ms
INFO [10-08|10:33:38.204] Commit new mining work                   number=492 sealhash=8db4ab…92ef58 uncles=0 txs=0  gas=0      fees=0 elapsed=545.4µs
INFO [10-08|10:33:38.205] Successfully sealed new block            number=491 sealhash=8c160a…371e24 hash=eb6f69…bc7be5 elapsed=1.928ms
INFO [10-08|10:33:38.205] 🔨 mined potential block                  number=491 hash=eb6f69…bc7be5
INFO [10-08|10:33:38.206] Commit new mining work                   number=492 sealhash=12ce39…739672 uncles=0 txs=15 gas=683304 fees=0 elapsed=2.703ms
INFO [10-08|10:33:38.208] Commit new mining work                   number=492 sealhash=12ce39…739672 uncles=1 txs=15 gas=683304 fees=0 elapsed=469.2µs
INFO [10-08|10:33:43.001] Successfully sealed new block            number=492 sealhash=12ce39…739672 hash=9b8cff…7b71fb elapsed=4.794s
```

The logs shows a warning: WARN [10-08|10:33:36.806] Head state missing, repairing chain      number=554 hash=b3e5c9…8ae258 and then you can see that instead of mining the new block from number 555, the mining started from block number 491.

I am running a geth private network of 2 nodes, and occassionally say after a crash or after killing and restarting the geth node, it exhibits the above behaviour which results in block losses.

**Comment by karalabe** [comment]
Don't kill it. Shut it down gracefully.

**Comment by balajipachai** [comment]
Thank You, this helps.
I am following below approach for shutting it down gracefully:

- When geth is launched in console mode, then I do `Ctrl^c` or `exit`
- When geth is launched as a daemon, then I do `pkill -INT pid` where pid is of geth process

Any other methods of shutting it down gracefully, you are aware of, that's missing from the above points.
However, what if the system crashes? in that case how do we mitigate the risk of block losses? Does geth shuts down gracefully in this scenario?

**Comment by saccura** [comment]
Any solution here?

**Comment by wenbin0** [comment]
And I have same problems.

**Comment by xanatos** [comment]
Just out of curiousity. I see in my logs that there is a "dirty" measurement that, empirically, tops at 2.00GiB. Is it the data that isn't persisted? And if yes, could we have a flag to control this "2.00GiB"?

INFO [11-17|07:59:48.810] Imported new potential chain segment     blocks=1  txs=116  mgas=12.881 elapsed=75.048ms   mgasps=171.639 number=15,988,110 hash=a5ae91..ccf530 dirty=2.00GiB
INFO [11-17|07:59:48.876] Chain head was updated                   number=15,988,110 hash=a5ae91..ccf530 root=023ef3..b6da03 elapsed=2.6868ms

**Comment by hpmv** [comment]
> Geth persists data after 1 hour worth of block processing (so for example if your blocks are processed in 100ms, that's 10/s * 60s * 60m = after 36000 blocks). If your network is super light (i.e. mostly empty blocks), it may happen that it takes a very very long time until blocks are flushed.

This is laughable. Wall clock exists as a thing, and I can't think of any other system who would refuse to flush data to disk in days.

> Don't kill it. Shut it down gracefully.

Unfortunately this is almost never practical. Power cuts, OOM kills, etc. happen all the time.

> You can hack around the issue currently with your workaround of restarting Geth periodically.

This is also not an acceptable solution, especially when restarting is such risky business that it might lose state.

> What's the problem?

That node upon restarting takes forever to sync because it rewound back by so many blocks due to days of not flushing? (Yes I'm talking about a different network but many networks use use geth).

And I don't understand it, why not just fix this by flushing after 1 hour worth of **wall time**? Sorry to be so blunt but I've just never seen software that is so buggy and the team refuses to fix it for years.

**Comment by karalabe** [comment]
You really started to complain about a 5 year old comment that is not even
relevant any more?

**Comment by hpmv** [comment]
Yep, because the issue still exists. We were recently setting up a PoA network based on geth for a CTF, and it was a real PITA that whenever we restarted the node, it would rewind back to nearly genesis. It was very cryptic and I finally found this 5 year old issue that helped me figure out why. I also operate another node for a real network that has the same issue, and after changing it in my own codebase so that it uses walltime instead of compute time, it is finally persisting data.

Just because an issue is 5 years old doesn't mean we can just ignore it. I'd still like to understand why we do not use wall time as a flushing criteria, as it is an intuitive expectation that in-memory cache would be flushed after a long time. Do you not agree that having a node not flush in-memory state for five days is a problem, and if you disagree, what sort of problems were we trying to solve by not flushing based on wall time (which seems like a deliberate choice)?

**Comment by karalabe** [comment]
This issue does not exist any more for --state.scheme=path, which will be the default once we switch over to Cancun.

**Comment by hpmv** [comment]
Ohhhh that's awesome, thank you! I do wish I knew that.

**Comment by karalabe** [comment]
@hpmv The only way to change the state scheme is a resync though, keep that in mind. Otherwise Geth will default to whatever's in the db.

There were various reasons we did hash flushing as it is, you can probably find them in our issue tracker, but given that we're moving away from that model, there's not much point to debated it any more.

**Comment by hpmv** [comment]
Gotcha, thanks for the tips @karalabe ; the presence of the path scheme definitely changes this discussion. One last question since I couldn't find it, is a path node able to snap sync against another node that was hash based?

**Comment by namiloh** [comment]
> is a path node able to snap sync against another node that was hash based?

Yes... Of course!
