### ISSUE TITLE
Light client hangs when calling light server via json-rpc

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20387]
Here is what I do. I run three terminals
1. geth --goerli --datadir foo --lightserv 100 --rpc -rpcapi personal,eth,net,web3b,les
2. geth --syncmode "light" --rpc --datadir bar --port 30304 --rpcport 8546 --goerli console
3. geth --datadir foo attach

In the 2nd terminal I run `admin.nodeInfo.id` to get the nodeID
In the 3rd terminal I execute
```javascript
les.addBalance(<nodeID>, 100000, "whatever")
les.clientInfo([<nodeID>])
```
The client in the 3rd terminal hangs. I can't see any error message in the first terminal.

**Comment by rjl493456442** [comment]
Fixed by #20395
