### ISSUE TITLE
Write documentation for puppeth

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/go-ethereum#20398]
To tidy up the various private mode guides we currently have, @fjl and I discussed keeping the content submitted by @fjl as the "advanced" / full details steps, and creating a new getting started guide that instead uses pupeth to make an easier to follow tutorial. Thus probably closing #20256

**Comment by holiman** [comment]
We will probably phase out puppeth rather than document it, so closing this as wont-fix.
