### ISSUE TITLE
Proposal: Implement a cheaper price suggester for light client

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/go-ethereum#20401]
Currently, we use `gasPrice` oracle to offer a suitable gas price for new transactions.
The underlying mechanism is very simple:
* grab recent blocks(default number is 20)
* sort all recently received transactions by gas-price
* select the suitable recommended gas price by `gpopercentile`

It definitely works for full node which has all recent blocks. However it's not cheap for light
clients.  Retrieving 20 block bodies is quite expensive.

We need an alternative mechanism for light client `SuggestPriceLight`

Perhaps the easiest way to achieve it is by using a different lighter default config for light clients.

**Comment by ligi** [comment]
Sounds great. Just wondering if it makes sense to implement as it would become obsolete after [EIP1559](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md) which I really hope comes soon.

**Comment by rjl493456442** [comment]
@ligi Oh, I haven't checked the EIP yet. I will check it now. Open this issue is basically acts as a memo which can make light client lighter.

**Comment by ligi** [comment]
Love your initiative to make the light client lighter! Just do not want efforts to be in vain. But it could take a bit until 1559 comes - just really wish it comes soon - could improve UX so much ..
