### ISSUE TITLE
[swarm] separate dns/hashonly/raw url schemes

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#2040]
implement distinct url scheme protocols for:
- dns 
- strictly immutable store
- raw content retrieval (via header or forced content)

names still to be decided

this is requirement for mist integration @frozeman @alexvandesande

**Comment by frozeman** [comment]
- `eth://` will resolve namereg DNS
- `bzz://` will resolve swarm hashes (and manifest files, immuteable)
- raw content is to be decided

**Comment by alexvandesande** [comment]
@frozeman according to our conversation with them

* `eth://` will be a meta-protocol that resolves name reg into any protocol the name owner wants
* Swarm would have two prefixes one for immutable and other for mutable storage, to be decided by them. I would suggest `bzz://` for mutable and maybe `bzzs://` for immutable (`s` stands for secure, like `https://`)

**Comment by zelig** [comment]
`eth` is indeed the meta-protocol that resolves the domain into a full url, using any protocol scheme the name owner wants. this is a mist feature. do you want to have it implemented in swarm?
could do, but maybe it should be above swarm.

this issuee is about the 3 swarm specific scheme handlers:
*  bzz using swarm DNS resolving to swarm hash
* only allowing swarm hash (no trixs with names, as permanent as you get)
* raw access, just display manifest not resolve paths through it

**Comment by nagydani** [comment]
Has a conclusion been reached on how to do it that I can start implementing?

**Comment by frozeman** [comment]
bzz://domain[:blocknumber]/path
bzzi://hash/path
bzzr://hash/path

or

bzz+://domain[:blocknumber]/path
bzz://hash/path
bzzr://hash/path

**Comment by zelig** [comment]
gone in as #2372
