### ISSUE TITLE
Feature and or ability to manually or automatically repair ethereum geth database.

### ISSUE THREAD

**Issue by megahz2** [ethereum/go-ethereum#20400]
**Can geth do an auto repair for database after bad geth.exe shutdown?** 

In the past I was able to use a repair command to fix the bad block and database, the command seems to be retired, changed or I forgot how to use the command as I am unable to repair manually.

**Is there still away to repair the database?**
Command string used: geth --syncmode fast --datadir D:\folder\EthereumGethChain

Geth version: `all`
OS & Version: 'Windows 10'

#### Actual behaviour: 

INFO [11-22|05:51:50.137] Importing sidechain segment              start=4684119 end=4685311
ERROR[11-22|05:51:51.651]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000 Engine
: ethash}

Number: 4684119
Hash: 0x3931429c2abc2490a408b98e266672678aaebf24b2b11f36faf7727a0b4cd5cd

         0: cumulative: 52256 gas: 52256 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x803babba18dd951de78a0532b8ccf84c1168287e50ab18a6761ecdd07bbbc7e9 logs: [0xc002ac6630] bloom: 0000000
000000000000000000000000000000000088000000008000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000800800000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000040000000800000000000000000000000000000000000000000000000000000000000000000200000000000000000000000208000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:

Synchronisation failed, dropping peer    peer=4ex816dabf740eb7 err="retrieved hash chain is invalid"
Error: invalid gas used (remote: 6687315 local: 6632767)
##############################

#### Steps to reproduce the behaviour: while geth is downloading chainstate / database, Close or terminate command prompt window.

**Is there still a repair command and special format of command to repair or fix geth --syncmode fast --datadir D:\folder\EthereumGethChain?**

**Comment by momaee** [comment]
When the client starts up it checks for rollback and if it is necessary it will do that(core/blockchain.go: bc.Rollback(hashes)). Usually, you don't need to do anything. Also, there is a file named blocks.go in the core directory that consists of a map and if you want to ban some block hashes you can add the hash to this map, in a startup, the client will get back to one block before that blocks. (core/blockchain.go - NewBlockChain function)

**Comment by karalabe** [comment]
This should be working. Please open an issue if this happens on latest releases.
