### ISSUE TITLE
Idea/Discussion: Degrade service when node is not updated

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#20429]
seeing this:

![image](https://user-images.githubusercontent.com/111600/70285307-6c10c780-180a-11ea-8253-c8e94e01eeca.png)

made me a bit worried and thinking.
I do not think istanbul is contentious - I think it is just node operators not caring to update.
Perhaps one idea to fight this problem in the future might be to degrade service when geth is not updated before a fork (perhaps with signaling on chain) - an Idea might be a X second sleep before answering a RPC call.
I have seen this with libraries that also wanted to force users to update to newer versions.
Just throwing the idea out there in the hope to spark a discussion - perhaps something arises from this.

**Comment by AusIV** [comment]
This strikes me as a denial of service attack vector if the signal used to notify clients of an impending fork isn't perfectly secured.

**Comment by karalabe** [comment]
Updating is a voluntary process. The devs can only ship a new code, but we cannot force people to update. This is a feature, not a bug.

Also I don't want to have control over when someone updates. If they decide to update 3 days before the fork, it's up to them, they know their business best. My best idea is to provide a means for auto-updating nodes (e.g. Ubuntu Snap), and describe to people how they can opt in if they wish so.

Even then, updating still requires a reboot at some point, which we cannot decide for the user.
