### ISSUE TITLE
geth complains that file system is read only when it is not

### ISSUE THREAD

**Issue by colourful-land** [ethereum/go-ethereum#20425]
#### System information

Geth version: 1.9.6-unstable
OS & Version: Linux (Debian 10)

#### Expected behaviour

Geth start syncing after `geth --datadir=/var/local/ethereum` command.

#### Actual behaviour

````
$ geth --datadir=/var/local/ethereum
INFO [12-04|18:49:49.795] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [12-04|18:49:49.796] Maximum peer count                       ETH=50 LES=0 total=50
INFO [12-04|18:49:49.796] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
Fatal: Failed to create the protocol stack: mkdir /var/local/ethereum: read-only file system
````

Note that the directory already exists, so it's weird that geth tried to create it. And it is configured with the loosest permission (in attempt to disapprove "read-only").

````
$ ls -lhd /var/local/ethereum
drwxrwxrwx 2 root root 4.0K Dec  4 18:43 /var/local/ethereum
````
also that it is not read-only:
````
$ touch /var/local/ethereum/f
$ ls /var/local/ethereum/f
````
#### Steps to reproduce the behaviour

1. Install snapd on Debian 10
2. Use snap to install geth
3. Create /var/local/ethereum with the loosest permission.
4. Run `geth --datadir=/var/local/ethereum`

**Comment by colourful-land** [comment]
cause is snap confinement.

**Comment by digitalnomad91** [comment]
@colourful-land Do you think you could maybe elaborate a little bit...? Your answer doesn't exactly give any info on what the solution might be. I understand it has something to do with snap / snap user, but what exactly?
