### ISSUE TITLE
a question about make geth

### ISSUE THREAD

**Issue by zhujin97** [ethereum/go-ethereum#20423]
Hi bro,
when i use make geth 
```
zhujin@DESKTOP-UGN3TGP:/ethereum/go-ethereum$ make geth
build/env.sh go run build/ci.go install ./cmd/geth
lsinternal/build/azure.go:25:2: cannot find package "github.com/Azure/azure-storage-blob-go/azblob" in any of:
        /usr/local/go/src/github.com/Azure/azure-storage-blob-go/azblob (from $GOROOT)
        /ethereum/go-ethereum/build/_workspace/src/github.com/Azure/azure-storage-blob-go/azblob (from $GOPATH)
build/ci.go:61:2: cannot find package "github.com/cespare/cp" in any of:
        /usr/local/go/src/github.com/cespare/cp (from $GOROOT)
        /ethereum/go-ethereum/build/_workspace/src/github.com/cespare/cp (from $GOPATH)
internal/build/pgp.go:27:2: cannot find package "golang.org/x/crypto/openpgp" in any of:
        /usr/local/go/src/golang.org/x/crypto/openpgp (from $GOROOT)
        /ethereum/go-ethereum/build/_workspace/src/golang.org/x/crypto/openpgp (from $GOPATH)
common/types.go:31:2: cannot find package "golang.org/x/crypto/sha3" in any of:
        /usr/local/go/src/golang.org/x/crypto/sha3 (from $GOROOT)
        /ethereum/go-ethereum/build/_workspace/src/golang.org/x/crypto/sha3 (from $GOPATH)
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 1
``` 
it's mean i need use this command ?
```
go get -u "github.com/Azure/azure-storage-blob-go/azblob"
```

**Comment by kmcnayr** [comment]
see #20411 

install go 1.13
I used this guide: https://github.com/golang/go/wiki/Ubuntu

Worked for me, make geth was successful

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by zhujin97** [comment]
> see #20411
> 
> install go 1.13
> I used this guide: https://github.com/golang/go/wiki/Ubuntu
> 
> Worked for me, make geth was successful



> see #20411
> 
> install go 1.13
> I used this guide: https://github.com/golang/go/wiki/Ubuntu
> 
> Worked for me, make geth was successful


Your answer solved my problem, thank you very much！

**Comment by AusIV** [comment]
A note in case it helps anyone else: I had to run `docker pull karalabe/xgo-latest` to update to the latest version of xgo. Without doing that it was still trying to build with an older version of go, and failing to gather the dependencies.
