### ISSUE TITLE
How could I check my sync mode in console since I have started geth to sync?

### ISSUE THREAD

**Issue by anymorefree** [ethereum/go-ethereum#20431]
Hi there,
Geth version: `1.9.8-stable-d62e9b28`
OS & Version: Linux

#### Expected behaviour

I can recheck the sync mode since I have started geth to sync in fast mode.

#### Actual behaviour
I dont find any command I can use in the console.

#### Steps to reproduce the behaviour
1. I started geth at command: geth --datadir data --rpc --rpcaddr 127.0.0.1 --rpcport 8545  --rpcapi eth,admin,personal,web3,net,tx,miner --syncmode fast --cache 4096
2. It syncing very long time and I restarted before, I see some articles say that: When you restart your geth , it will swich your sync mode from fast to full .  But I want to check my mode, what's the actrual sync mode.
3. I attach my geth by command: geth attach http://127.0.0.1:8545 , then I want to check my mode, HOW CAN I CHECK? WHICK COMMAND CAN I USE？

**Comment by karalabe** [comment]
Well, should be clear from the logs. Fast sync only ever runs on initial sync. After that you're processing block by block.
