### ISSUE TITLE
Geth 1.9.8 stopped  syncing since 06Dec 2019

### ISSUE THREAD

**Issue by ankita-p17** [ethereum/go-ethereum#20435]
Hi,
i started geth 1.9.8 to sync one week back. State entries were syncing till 06-Dec then gets stopped.

#### System information

Geth version: 1.9.8
OS & Version: Linux

#### Expected behaviour
It should sync

#### Actual behaviour
06Dec logs : 
Dec 06 09:22:56 dcx-geth geth[28807]: INFO [12-06|09:22:56.601] Regenerated local transaction journal    transactions=0 accounts=0
Dec 06 08:55:03 dcx-geth geth[28807]: WARN [12-06|08:55:03.449] Synchronisation failed, dropping peer    peer=8708e04b2712b6db err="retrieved hash chain is invalid"

Current logs : 
Dec 09 06:00:54 a-geth geth[10090]: WARN [12-09|06:00:54.526] Served eth_coinbase                      reqid=3  t=53.945µs   err="etherbase must be explicitly specified"
Dec 09 05:45:54 a-geth geth[10090]: INFO [12-09|05:45:54.779] Regenerated local transaction journal    transactions=0 accounts=0
Dec 09 04:45:54 a-geth geth[10090]: INFO [12-09|04:45:54.779] Regenerated local transaction journal    transactions=0 accounts=0
Dec 09 03:45:54 a-geth geth[10090]: INFO [12-09|03:45:54.779] Regenerated local transaction journal    transactions=0 accounts=0
Dec 09 02:45:54 a-geth geth[10090]: INFO [12-09|02:45:54.779] Regenerated local transaction journal    transactions=0 accounts=0
Dec 09 01:45:54 a-geth geth[10090]: INFO [12-09|01:45:54.779] Regenerated local transaction journal    transactions=0 accounts=0

Is it because of the recent hard fork? 
Any help appreciated.

**Comment by wh0am111** [comment]
i have same problem

**Comment by ligi** [comment]
Yes - this date correlates with the Hardfork and if you run geth 1.9.6 you will need to update

**Comment by ankita-p17** [comment]
> Yes - this date correlates with the Hardfork and if you run geth 1.9.6 you will need to update

I am running geth 1.9.8

**Comment by wh0am111** [comment]
geth 1.9.9

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: ankita-p17 <notifications@github.com>
发送时间: Tuesday, December 10, 2019 2:05:23 PM
收件人: ethereum/go-ethereum <go-ethereum@noreply.github.com>
抄送: wh0am111 <wh0am11@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [ethereum/go-ethereum] Geth 1.9.8 stopped syncing since 06Dec 2019 (#20435)


Yes - this date correlates with the Hardfork and if you run geth 1.9.6 you will need to update

I am running geth 1.9.8

―

**Comment by ankita-p17** [comment]
Can I get list of peer to add to. @karalabe

**Comment by Heliosmaster** [comment]
We were having the same issue. We removed the peers from the config in order to let `geth` get the peers automatically and that seemed to help.

**Comment by ankita-p17** [comment]
> We were having the same issue. We removed the peers from the config in order to let `geth` get the peers automatically and that seemed to help.

> admin.peers
[]
> net.peerCount
0

Is there any other option to remove `peers` from? It is halted since two days.

**Comment by fjl** [comment]
Would be good to get a stack trace from a hanging node. To get the trace, run `geth attach --exec 'debug.stacks()' > stacktrace.txt`.

**Comment by karalabe** [comment]
Please also paste the command you use to run Geth.

**Comment by ankita-p17** [comment]
> Would be good to get a stack trace from a hanging node. To get the trace, run `geth attach --exec 'debug.stacks()' > stacktrace.txt`.

[stacktrace.txt](https://github.com/ethereum/go-ethereum/files/3966415/stacktrace.txt)
please look into this file
@karalabe  @fjl 

Command to run geth : /path/to/geth/geth1.9.8/geth-linux-amd64-1.9.8-d62e9b28/geth --datadir=/home/dcx/EthereumMainnet/ --cache 4096 --rpc --rpcapi eth,web3,net,ssh,db,debug,personal,admin --rpcaddr 10.128.0.3 --rpcport 8545 --port 35556

**Comment by ankita-p17** [comment]
Hi, any help??

**Comment by rjl493456442** [comment]
It seems Geth node doesn't have any p2p level activity for 1 hour. 

```
goroutine 105 [select, 53 minutes]:
github.com/ethereum/go-ethereum/p2p.(*Server).run(0xc00028ca00, 0x13f9f40, 0xc000988240)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/server.go:696 +0x745
created by github.com/ethereum/go-ethereum/p2p.(*Server).Start
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/server.go:483 +0x48f
```

**Comment by holiman** [comment]
@fjl the stack trace contains

```

goroutine 104 [select]:
github.com/ethereum/go-ethereum/p2p/discover.(*lookup).slowdown(0xc0001c4cf0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/discover/lookup.go:137 +0xf9
github.com/ethereum/go-ethereum/p2p/discover.(*lookup).startQueries(0xc0001c4cf0, 0x45de3da70ebf13ab)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/discover/lookup.go:114 +0x2b4
github.com/ethereum/go-ethereum/p2p/discover.(*lookup).advance(0xc0001c4cf0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/discover/lookup.go:69 +0x28e
github.com/ethereum/go-ethereum/p2p/discover.(*lookupIterator).Next(0xc0001bbe00, 0xc000607eb4)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/discover/lookup.go:213 +0xac
github.com/ethereum/go-ethereum/p2p/enode.(*FairMix).runSource(0xc0001953e0, 0xc0030882a0, 0xc0001b9660)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/enode/iter.go:277 +0xc5
created by github.com/ethereum/go-ethereum/p2p/enode.(*FairMix).AddSource
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/enode/iter.go:178 +0x17a
```

You modified that 23 days ago: https://github.com/ethereum/go-ethereum/pull/20389 . PTAL?

**Comment by ankita-p17** [comment]
[stacktrace.txt](https://github.com/ethereum/go-ethereum/files/3983637/stacktrace.txt)
 find the latest stack trace attached

**Comment by ankita-p17** [comment]
Hi @fjl, any update?

**Comment by ankita-p17** [comment]
Hi @karalabe, @ligi @fjl, any update on this??
For Muir Glacier fork, I need to upgrade the existing 1.9.8 to 1.9.9, correct if not. How an unsynced node will get affected?

**Comment by BadMachine** [comment]
Same problem here!
Tried to remove db and start sync from scratch, after 3 hours syncing i`ve got same result 
"Syncronization failed, dropping peer"

**Comment by fjl** [comment]
Here is why this issue is happening:

- The peer discovery table is empty. Reasons for this can be firewall misconfiguration (e.g. UDP blocked) or system time not being synchronized with NTP.
- The subsystem which creates peer connections is stuck waiting for discovery results and is hanging in `p2p.Server.run`. 

We can fix the software bug where it's hanging, but sync will not work properly unless you ensure UDP connectivity is working.

**Comment by holiman** [comment]
Geth 1.9.8 is very very old by now, and this issue is not relevant any longer. Closing
