### ISSUE TITLE
lower minimum default pool price threshold for mining a transaction

### ISSUE THREAD

**Issue by tribycol** [ethereum/go-ethereum#20432]
Hi everyone

#### System information

Geth version: 1.9.9
OS & Version:Ubuntu Linux 18.04
Commit hash : (if `develop`)

#### Expected behaviour

Define lower that one the GasFloor and GasPrice

#### Actual behaviour

it is limited to 1. not let use 0.00001

#### Steps to reproduce the behaviour

If I set "0.0001"as Gasprice, Geth drop an error of integral number, then it cannot use it. 

if I set -1, transaction pool price threshold will update to "1000000000". 

#####why lower ..
1) I am looking for the block reward, as I am solo miner, I will accept lower fee.
3) Pools are behaving as a banks. as they have all the power for process the transactions. if you open an opportunity to every solo miner, it will change the game rules.
2)Lower fees makes a reason why use ethereum instead of a current bank transaction

**Comment by gballet** [comment]
`GasPrice` is in [Wei](https://github.com/ethereum/wiki/wiki/White-Paper#currency-and-issuance), which is the smallest unit of the Ether. Like it is not possible to pay less than a cent, it is not possible to handle less than a Wei.

The problem you are running into is that the gas price is coded as an integer, which is the correct behavior. When you try to pass a decimal number, it will fail. `-1` is recognized as an integer, but the sanitization code will not accept a value lower than 1, and uses the default value of `1000000000` instead.

So I'll be closing this issue, setting `GasPrice` to 1 does exactly what you want.
