### ISSUE TITLE
v1.9.8 sync don't finish??

### ISSUE THREAD

**Issue by boy-good** [ethereum/go-ethereum#20433]
![image](https://user-images.githubusercontent.com/39320533/70389676-9080c580-19fd-11ea-8197-ab09b1647e22.png)
How to solve sync problem?? Help me please. This is very urgent for me.

Eight-core 16G
500G SSD

**Comment by boy-good** [comment]
It ’s been syncing for four days, it ’s still like this

**Comment by AusIV** [comment]
It looks like you're still pulling state trie entries. This can go faster by increasing your number of connected peers (--maxpeers). You're also probably not fully utilizing your available RAM, --cache defaults to 4096 on mainnet, so you'd only be using around 4 GB of RAM even though you have 16.

**Comment by karalabe** [comment]
There are about 400M trie nodes. You'll need to wait it out. We're working on a new protocol.
