### ISSUE TITLE
Cannot start Snap installed geth node

### ISSUE THREAD

**Issue by maxweng** [ethereum/go-ethereum#20442]
#### System information

Geth version: `1.9.5 ~ 1.9.7`
OS & Version: `Ubuntu 18`
Snap channel: `stable, beta, edge`

Geth wont boot up when setting `datadir` to be on another mounted device other than the root device `/`.

For example, 

`/share` is the mount point of  `/dev/nvme1n1`

And when using the following command to start Geth

`geth --datadir=/share/.ethereum`

Got the errors as follows:
````
INFO [12-10|08:42:41.256] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [12-10|08:42:41.259] Maximum peer count                       ETH=50 LES=0 total=50
INFO [12-10|08:42:41.259] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
Fatal: Failed to create the protocol stack: mkdir /share: read-only file system
````

**Comment by holiman** [comment]
It says 'read-only file system'. Could you show us the output of e.g. `mount` ?

**Comment by karalabe** [comment]
Btw, we don't maintain the Snap packages.

**Comment by maxweng** [comment]
> It says 'read-only file system'. Could you show us the output of e.g. `mount` and maybe `df` ?

Just fyi, the one i compiled myself doesn't have the issue. And the device is mounted as follows:

```
/dev/nvme0n1 /share ext4 defaults,nofail  0  2
```

And, `df` output, 

```
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  776K  1.6G   1% /run
/dev/nvme1n1p1   20G  3.7G   16G  19% /
tmpfs           7.8G     0  7.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/loop2       18M   18M     0 100% /snap/amazon-ssm-agent/1480
/dev/loop3       18M   18M     0 100% /snap/amazon-ssm-agent/930
/dev/nvme0n1    984G  291G  694G  30% /share
tmpfs           1.6G     0  1.6G   0% /run/user/1000
/dev/loop4       90M   90M     0 100% /snap/core/8213
/dev/loop0       90M   90M     0 100% /snap/core/8268
```

**Comment by karalabe** [comment]
Snap binaries run in certain sandboxes. Apps need to explicitly ask for permission for everything. The packager possibly didn't request permission for accessing external mounts or whatnots. Not familiar. That's why I said it's now our package and we don't really know what's its limitations are.

**Comment by maxweng** [comment]
I see. I'll mark this issue is closed, thanks!
