### ISSUE TITLE
Windows build failed: /include/oledlg.h:428:3: error: unknown type name 'interface'

### ISSUE THREAD

**Issue by yiyanwannian** [ethereum/go-ethereum#20449]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: 1.13.4
OS & Version: Windows 10
Commit hash :  d90d1db609c8d77baa422d49bd371207c06b4711

#### Expected behaviour
 go build github.com/ethereum/go-ethereum/cmd/geth pass

#### Actual behaviour
build failed:
# gopkg.in/olebedev/go-duktape.v3
duk_minimal_printf.c: In function 'duk__parse_pointer':
duk_minimal_printf.c:126:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  *out = (void *) val;
         ^
duk_minimal_printf.c: In function 'duk_minimal_vsnprintf':
duk_minimal_printf.c:236:76: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     off = duk__format_long(str, size, off, sizeof(void *) * 2, '0', 16, 0, (unsigned long) v);
.........
 #pragma GCC diagnostic ignored "-Wstringop-overflow"

#### Steps to reproduce the behaviour
1. git clone go-etherenum code
2. set GO111MODLUE=on
3. wait Goland sync packages
4. type :  go build github.com/ethereum/go-ethereum/cmd/geth then error encountered

#### Backtrace
more detail in my etherror.log file
[etherror.txt](https://github.com/ethereum/go-ethereum/files/3951146/etherror.txt)

````
[backtrace]
````
...

**Comment by karalabe** [comment]
The duktape build log is a warning, not a build error.

Regarding USB, your gcc/mingw installation seems to be too old and does not recognize some newer constructs? When did you install it, which version? Maybe we are using an older one?

**Comment by yiyanwannian** [comment]
My version info:
D:\Code\GoProjects\src\github.com\ethereum\go-ethereum>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=D:/Software/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/5.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-5.1.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_
STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-t
ime --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 5.1.0 (tdm64-1)

**Comment by yiyanwannian** [comment]
fixed by install TDM-GCC-64 again
