### ISSUE TITLE
geth send transaction to unknown account?

### ISSUE THREAD

**Issue by splxsg** [ethereum/go-ethereum#20440]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.9.9`
OS & Version: Linux
Commit hash : download from geth.ethereum.org

#### Expected behaviour

Create a transaction send to specific dest account.

#### Actual behaviour

the original tx dropped and replaced... 

#### Backtrace

````
[backtrace]
````

I send tx from web3, it creates a tx 0x97b04b4a3f94ac48e153ab70975cb0bc7ee183e6987075b319ee3de584f5bb8e
however, it dropped and replaced by another tx sec later
0x8670a564beaa1e88be8af4eaf77fe124a869dcbad5c570381f5b42f6e5597fe4
while the second tx, dest address is an unknown address,

 anyone got idea? Since I had lost 0.6 ETH.....

**Comment by splxsg** [comment]
I tried several times, send to different address, all goes to this strange address.... Trojans?

**Comment by holiman** [comment]
Do you use `unlock` ? Do you have your rpc-interface exposed against the internet?

**Comment by holiman** [comment]
Please provide the exact command you use to start geth, and also ifno about how you send your transaction (e.g. is it done programatically by some javascript, or are you doing it manually in the geth REPL?)

**Comment by ligi** [comment]
Removing the triage label for now - I think we should wait with triage until the questions by @holiman are answered
