### ISSUE TITLE
Feature Request: Make base block mining reward queryable.

### ISSUE THREAD

**Issue by GhostTyper** [ethereum/go-ethereum#20458]
Hello and sorry for disobeying the predefined input mask.

My feature request is: Implement a call which will give back an array of starting block and base block mining reward.

This will prevent people from hard coding the block rewards for Byzantium, Constantinople and any future changes to Ethereum in this regard, like it's done here: https://github.com/ethereum/go-ethereum/blob/f51cf573b5c602914d22f5a31c58378c5aa17ffd/consensus/ethash/consensus.go#L42

I'm very sorry, if this already exists somehow and I just overlooked it. If so, you could point me to the right direction in the documentation.

**Comment by holiman** [comment]
I don't understand... What do you mean hardcoding? The line you're pointing to is where we define the byzantium block reward. Even if we put it inside a function, the definition still needs to exist _somewhere_? 
Do you mean you want an API-method so it's accessible when using geth as a library? As an RPC endpoing?

**Comment by holiman** [comment]
I'll close this, feel free to reopen if you have a more concrete proposal and a some good supporting reasons.

**Comment by GhostTyper** [comment]
Yes, ofc I mean a RPC endpoint.

Right now someone examining all blocks and changes of balances to accounts needs to somewhere store these informations in his own software (afaik), which is not futureproof.

If such an endpoint is already accessible, just keep this ticket closed. Else I would suggest to reopen it, because right now I (and I think at least all blockchain explorers) need to change their software, if the mining reward changes. And also I think this API call is not very hard to implement.

**Comment by GhostTyper** [comment]
I updated the ticket for better understanding.
