### ISSUE TITLE
GetModifiedAccountsByNumber is inconsistent. Doesn't indicate address which received tokens.

### ISSUE THREAD

**Issue by darklow** [ethereum/go-ethereum#20457]
I get inconsistent behaviour on `GetModifiedAccountsByNumber`. There are occasions when it doesn't return address that received tokens at specific block. Here is such example:

Related address: https://etherscan.io/address/0x7A4b4E6179987341f5404EBCb04ed6134aBADA27#tokentxns

Address received USDT tokens in following TX: https://etherscan.io/tx/0xd0b492af0fc84eec7b38768a76f8abe8374e08d51b6e38ea4ca3b3f467a0eb53

TX Block: **9099581**

Calling for modified accounts
```
web3.manager.request_blocking('debug_getModifiedAccountsByNumber', [9099580, 9099581])
# Returns a list of 242 addresses, but there is no mention of 0x7A4b4E6179987341f5404EBCb04ed6134aBADA27
```

#### System information

Geth version: `1.9.9-stable-0174499`
OS & Version: Linux / Docker
Geth params:
```
--nousb --port 30303 --cache 3072 --rpc --rpcaddr 0.0.0.0 --rpcapi eth,net,web3,debug,txpool
```

**Comment by ligi** [comment]
GetModifiedAccountsByNumber does only reflect ether transactions - not token (internal) transactions

**Comment by darklow** [comment]
@ligi Thank you. Didn't found info indicating such behaviour. Function name makes you think it will detect any kind of modifications, not just ETH.

I'm using debug trace for blocks and it is very inefficient to do trace on every block if you know exact addresses you're looking for. Anyone knows any workarounds to be able to tell if account had any token modifications within block before doing full debug trace? Thank you.

**Comment by holiman** [comment]
> Function name makes you think it will detect any kind of modifications, not just ETH.

Actually, it does. The thing is, a token is just a slot on the token-contract `C` that says `X` holds `Y` tokens. So the function _does_ detect that the storage root of `C` has changed.
