### ISSUE TITLE
Remote RPC Connection

### ISSUE THREAD

**Issue by pool2mine** [ethereum/go-ethereum#20454]
Hi, i am running an ethereum pool and 2 days ago my geth database exploded somehow, I deleted the entire database (geth removedb), tried to sync again and had same errors before fully sync, so I formatted my server and i am currently syncing again... As i have 2 servers i also formatted and made a clean install on my second server and syncing another node so i have a backup node, but the question is... i have my pool runing on server#1 and also my daemon but i would like to connect this pool to the backup deamon running in server#2 as failover (connected on same LAN). I didn't wanted to allow remote rpc running --rpccorsdomain because read that's extremely unsecure, so i would like to know how to allow remote RPC connection ONLY to my server#1 on the same LAN. Thanks in advance.

**Comment by GhostTyper** [comment]
I'm a noob, but I assume that's the job of some external <-> internal firewall rules.

**Comment by holiman** [comment]
So the gist of the question: how do I whitelist a certain remote endpoint on my server, so that it can speak to my server? 

Answer: use a firewall, e.g. `iptables` to allow only the specific remote peer, and block all others. Other possible ways to achieve this is vpn or ssh-tunneling.
