### ISSUE TITLE
ASIC Resistance

### ISSUE THREAD

**Issue by NickTheLim** [ethereum/go-ethereum#20463]
Hi,

ASIC resistance was a key feature in the white paper, and a primary reason why Ethereum became popular among the general public which drove a lot of its value.

Now basically no one uses ethereum except for fringe people.

Why is the coin no longer ASIC resistant?

Ethereum just got delisted from a huge exchange and price keeps going down. Whatever strategy or logic behind having huge chinese ASIC miners on the network doesn't seem to make sense morally, logically, or even in reality.

When will we have ASIC resistance?

No normal can use the coin or mine it anymore.

Looking to hear that this will happen so or at least some intelligent thoughts as to why you think Ethereum should stay on this downward path.

**Comment by NickTheLim** [comment]
Ethereum is supposed to be asic resistant and currently it is not. That is a big and this issue should be highly prioritized until solved.

**Comment by ligi** [comment]
I think this is the wrong place (layer) to discuss this. Perhaps https://ethereum-magicians.org is a better place?

**Comment by NickTheLim** [comment]
This is a critical software bug

**Comment by holiman** [comment]
This is the go-ethereum repository, use to build `geth`. `geth` is an ethereum node implementation, which follows the current specification. This is the correct place to file a bug relating to how `geth` does something wrong, but not the right place to report/discuss a change in Ethereum. For that we have, for example, ethereum magicians.
