### ISSUE TITLE
616GB chaindata! Whether if there is a way to shrink these data?

### ISSUE THREAD

**Issue by wuyudian1** [ethereum/go-ethereum#20466]
Hi there,

I upgraded my full node from 1.8.23 to 1.9.9 on Dec. 6(Because the old one can not sync. blocks any more)

**I was shocked**: the disk usage increased to **616GB** at a "visible speed"

Infact,  I found that a newly synced full node will use less disk space than one which has been running for a long time. 

So I guess there's some data can be deleted, is there a way to shrink the chaindata?

**Comment by MysticRyuujin** [comment]
The simplest method to reduce the bloat is to simply wipe the db and start a new fresh fast sync.
