### ISSUE TITLE
feature request: pruning in combination with light mode

### ISSUE THREAD

**Issue by sidhujag** [ethereum/go-ethereum#20479]
Now that we have oracle CHT making light mode sync making a standard sync process of about 2 weeks or so regularly does it make sense to enable some sort of pruning so data kept by the local node can be configured to be minimally viable (the amount it syncs with ~2 weeks). This would help tremendously with long-term storage requirements.

**Comment by rjl493456442** [comment]
Check this branch https://github.com/ethereum/go-ethereum/pull/19570. It's just waiting for merging :P

**Comment by sidhujag** [comment]
@rjl493456442 thanks Gary! This is exactly what I was envisioning because of runtime rolling checkpoints you can create constant storage requirements. Sweet. We have around 2000 to 3000 light nodes running which will appreciate this.

**Comment by rjl493456442** [comment]
It's merged in the master branch now.
