### ISSUE TITLE
geth retesteth + Ethash

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#20487]
repo: https://github.com/ethereum/retesteth/pull/73  (retesteth)
https://github.com/ethereum/tests/pull/670  (tests)

test:src/BlockchainTestsFiller/InvalidBlocks/bcUncleHeaderValidity/correctFiller.json 

change NoProof to Ethash
retesteth command```./retesteth -t BlockchainTests/InvalidBlocks/bcUncleHeaderValidity -- --clients "default" --singletest correct --filltests --verbosity 6
```
geth retesteth error:```Request: {"jsonrpc":"2.0","method":"test_mineBlocks","params":[1],"id":5}
Reply: {"jsonrpc":"2.0","id":5,"error":{"code":-32000,"message":"invalid mix digest"}}
```
Apparently test mining with Ethash is not supported. with NoProof the command works just fine and the test is being generated.

**Comment by holiman** [comment]
Closing this, we're not going to continue supporting retesteth. If this is needed to assist in building testcases, let's create a new ticket, and we can consider maybe creating a special tool for sealing/mining.
