### ISSUE TITLE
geth: large peer count, slow block downloads [question]

### ISSUE THREAD

**Issue by titus-anromedonn** [ethereum/go-ethereum#20489]
#### System information

Geth version: `Geth/v1.9.9-stable-01744997/linux-amd64/go1.13.4`
OS & Version: `Linux`

#### Expected behavior

Block Download Speed: >= 1MB/s

- 900+ Peer Count
- Gigabit link
- NVME Storage

#### Actual behavior

Block Download Speed: ~1MB/s
- 900+ Peer Count
- Gigabit link
- NVME Storage

**EDIT**

- Up to 1200 Peers. Averaging about 4 MB/s  (12/29)
- Up to 1800 Peers. Averaging about 7 MB/s (12/29)

#### Steps to reproduce the behavior

`geth --cache 32768  --syncmode full --gcmode archive --maxpeers 4096 --metrics --metrics.influxdb .... `

#### Background
I've been doing a lot of research trying to figure out how to increase the speed of the block downloads but have not been able to find anything besides a few suggestions referencing an increase to the max peer count. Could someone please fill in my lack of knowledge as to what may be causing this? 

In theory, I should be able to fully saturate a Gigabit line, no?

**Comment by karalabe** [comment]
Could you please post some logs? Are you downloading blocks, or already at the states? States require insane number of round trips, so there latency is the king (we're working on a new sync algo).
