### ISSUE TITLE
abigen generate view methods as transaction methods

### ISSUE THREAD

**Issue by alonana** [ethereum/go-ethereum#20491]
Looks like abigen is broken after moving to latest solidity version.
All view methods are generated as transaction methods.

for example, this contract method:

```
	function getDefaultXAndY() public view returns (uint x, uint y){
		return (defaultX, defaultY);
	}

```
is generated as:
```
// GetDefaultXAndY is a paid mutator transaction binding the contract method 0xcd80054d.
//
// Solidity: function getDefaultXAndY() returns(uint256 x, uint256 y)
func (_MyContract *MyContractTransactor) GetDefaultXAndY(opts *bind.TransactOpts) (*types.Transaction, error) {
	return _My.contract.Transact(opts, "getDefaultXAndY")
}
```

Looks like this is a mismatch between abigen and solc.
abigen is looking for "constant" file in the abi file, while the solc compiler creates:

```
{"inputs":[]
,"name":"getDefaultXAndY"
,"outputs":[{"internalType":"uint256","name":"x","type":"uint256"},{"internalType":"uint256","name":"y","type":"uint256"}],
"stateMutability":"view","type":"function"
},

```

a bypass to this problem is to manually update the abi file before running the abigen, and add field: constant:true

#### Reproduce steps
solc --abi --output-dir ./compiled_contracts MyContract.sol
solc --bin --output-dir ./compiled_contracts MyContract.sol
cd compiled_contracts
abigen --bin MyContract.bin --abi MyContract.abi --pkg=my_contract --out=MyContract.go

#### System information

solc --version
Version: 0.6.0+commit.26b70077.Linux.g++

 abigen --version
abigen version 1.9.9-stable-01744997

**Comment by rjl493456442** [comment]
Will fixed by #20482, waiting for merging.

**Comment by gballet** [comment]
#20482 got merged, closing

**Comment by chromafunk** [comment]
I just discovered this problem, is this ever going to be merged ? Otherwise, how do I modify abi so I get the correct binding requirements ?
