### ISSUE TITLE
please enable network time synchronization in system settings

### ISSUE THREAD

**Issue by lamart1** [ethereum/go-ethereum#20498]
Hi there. I can't run internet time on win7 = I can't run node?
![asdaa](https://user-images.githubusercontent.com/10207118/71714761-627d7e00-2e0f-11ea-97f8-68c7c312dba3.png)

**Comment by karalabe** [comment]
The discovery protocol relies on clock drift being smaller than 30 seconds. Currently you need to ensure that in order to run a node. We're working on a secondary discovery protocol based on DNS that should not have this requirement.
