### ISSUE TITLE
Puppeth dashboard Customise Text and Possible Pages

### ISSUE THREAD

**Issue by anistark** [ethereum/go-ethereum#20500]
`cmd/puppeth` serves great to us as we host our [Indium.Network](https://indium.network/) [dashboard here](http://dashboard.indium.network/), via puppeth.

But, the Page Title still says `Ethereum Testnet`. Is there any way to customise this text?

Also, the other texts and messages such as `This page does not represent the entire state of the ethereum network - listing a node on this page is a voluntary process.`.

**Comment by karalabe** [comment]
Hmm, there's no way to customize any text really. I do see your point though. I guess we could change from Testnet to Network. Whether it's a testnet or not is not that important really.

**Comment by anistark** [comment]
@karalabe Yeah that would be great. **Network** makes more sense than **Testnet**.

**Comment by karalabe** [comment]
Fixed by the mentioned PR.
