### ISSUE TITLE
wiki: eth_pendingTransactions documentation lacks 'for managed addresses' caveat

### ISSUE THREAD

**Issue by meowsbits** [ethereum/go-ethereum#20523]
#### System information

Geth version: any from at least last few years

#### Expected behaviour

`eth_pendingTransactions` returns all transactions marked as pending in the transaction pool, as documented here: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_pendingtransactions

```
__eth_pendingTransactions__

Returns the pending transactions list.
```

#### Actual behaviour

`eth_pendingTransactions` returns pending transactions sent from accounts managed by geth instance. 

#### Proposed Solution

Fix documentation to read:

```
__eth_pendingTransactions__

Returns the transactions that are pending in the transaction pool and have a from address that is one of the accounts this node manages.
```
> https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1582-L1584

**Comment by karalabe** [comment]
Please open the issue on the wiki repo https://github.com/ethereum/wiki/issues
