### ISSUE TITLE
RPC: eth.sign should return the ethereum canonical version of the signature

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#2053]
Ethereum defines the `V` param as `V + 27` (Py relic)

**Comment by tgerring** [comment]
Will this be included with the 1.4.0 milestone?

**Comment by kumavis** [comment]
👍  plz 👍

**Comment by axic** [comment]
Can we get this discrepancy fixed in the future (soon-ish)? Many tools actually support both [0, 1] and [27, 28] so the impact should be limited. The longer this "fix" waits, the bigger the impact will be.

**Comment by fjl** [comment]
The next chance to fix it is #2940

**Comment by fjl** [comment]
Please leave any suggestions for improving eth_sign there.

**Comment by 3esmit** [comment]
this was fixed?

**Comment by Moejoe90** [comment]
What's the update on this?

**Comment by Firescar96** [comment]
I think you can close this now, it's been resolved.

**Comment by alexeyneu** [comment]
yeah it's been resolved but we still have `+27` haha  
https://github.com/bitbill/bitbill-multisig-contracts/blob/f79bf0ad58990b80cc584786044c140a44adbe73/OwnbitMultiSigV4.sol#L168
