### ISSUE TITLE
Geth 1.9.9 seems to leak memory while mining

### ISSUE THREAD

**Issue by lehisnoe** [ethereum/go-ethereum#20549]
#### System information

Version: 1.9.9-stable
Git Commit: 017449971e1e9e220efcd97d3313a0e27f47003b
Architecture: amd64
Protocol Versions: [64 63]
Go Version: go1.13.4
Operating System: linux

#### Expected behaviour

Nodes should run without crashes.

#### Actual behaviour
I run 2 geth nodes for mining purposes. Just after upgrade to 1.9.9 they've started crashing with 'out of memory' error. There is 32GB RAM on each server, the config hasn't changed. Nodes run under systemd:
```
[Service]
Type=simple
ExecStart=/usr/bin/geth --mine --etherbase=0x... --rpcvhosts=* --rpc --rpcport 1234 --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "eth,net,web3,txpool,miner" --maxpeers "150" --cache "8192"  --txpool.globalslots 1024 --txpool.globalqueue 256
ExecReload=/bin/kill -HUP $MAINPID
KillSignal=TERM
Restart=on-failure
RestartSec=15s
LimitNOFILE=32768
LimitAS=26843545600
```
#### Backtrace
```
Jan 13 07:51:21 eu geth[11356]: INFO [01-13|07:51:21.414] Successfully sealed new block            number=9271359 sealhash=5d389f…27b763 hash=dd62bf…9185f6 elapsed=2.242s
Jan 13 07:51:21 eu geth[11356]: INFO [01-13|07:51:21.414] 🔨 mined potential block                  number=9271359 hash=dd62bf…9185f6
Jan 13 07:51:21 eu geth[11356]: INFO [01-13|07:51:21.415] Commit new mining work                   number=9271360 sealhash=7fcc57…d050c7 uncles=0 txs=0     gas=0       fees=
0              elapsed=481.049µs
Jan 13 07:51:21 eu geth[11356]: INFO [01-13|07:51:21.426] Commit new mining work                   number=9271360 sealhash=040c0c…5de728 uncles=0 txs=16    gas=756860  fees=
0.0122152808   elapsed=11.580ms
Jan 13 07:51:23 eu geth[11356]: ERROR[01-13|07:51:23.140] Failed to generate mapped ethash dataset epoch=310 err="cannot allocate memory"
Jan 13 07:51:23 eu geth[11356]: runtime: out of memory: cannot allocate 7348420608-byte block (14074249216 in use)
Jan 13 07:51:23 eu geth[11356]: fatal error: out of memory
Jan 13 07:51:23 eu geth[11356]: runtime stack:
Jan 13 07:51:23 eu geth[11356]: runtime.throw(0x116068a, 0xd)
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/.go/src/runtime/panic.go:774 +0x72
Jan 13 07:51:23 eu geth[11356]: runtime.largeAlloc(0x1b5ffed00, 0x1ed0101, 0x7f5f4c8332a8)
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/.go/src/runtime/malloc.go:1140 +0x16a
Jan 13 07:51:23 eu geth[11356]: runtime.mallocgc.func1()
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/.go/src/runtime/malloc.go:1033 +0x46
Jan 13 07:51:23 eu geth[11356]: runtime.systemstack(0x0)
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/.go/src/runtime/asm_amd64.s:370 +0x66
Jan 13 07:51:23 eu geth[11356]: runtime.mstart()
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/.go/src/runtime/proc.go:1146
Jan 13 07:51:23 eu geth[11356]: goroutine 2116805 [running]:
Jan 13 07:51:23 eu geth[11356]: runtime.systemstack_switch()
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/.go/src/runtime/asm_amd64.s:330 fp=0xc0271c1b78 sp=0xc0271c1b70 pc=0x473280
Jan 13 07:51:23 eu geth[11356]: runtime.mallocgc(0x1b5ffed00, 0xf87ec0, 0x1, 0x2)
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/.go/src/runtime/malloc.go:1032 +0x895 fp=0xc0271c1c18 sp=0xc0271c1b78 pc=0x422265
Jan 13 07:51:23 eu geth[11356]: runtime.makeslice(0xf87ec0, 0x6d7ffb40, 0x6d7ffb40, 0xc1892bcfc0)
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/.go/src/runtime/slice.go:49 +0x6c fp=0xc0271c1c48 sp=0xc0271c1c18 pc=0x45bd6c
Jan 13 07:51:23 eu geth[11356]: github.com/ethereum/go-ethereum/consensus/ethash.(*dataset).generate.func1()
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:3
44 +0x87a fp=0xc0271c1e98 sp=0xc0271c1c48 pc=0xafcdea
Jan 13 07:51:23 eu geth[11356]: sync.(*Once).doSlow(0xc07aa58180, 0xc15eef2f48)
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/.go/src/sync/once.go:66 +0xe3 fp=0xc0271c1f38 sp=0xc0271c1e98 pc=0x493603
Jan 13 07:51:23 eu geth[11356]: sync.(*Once).Do(...)
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/.go/src/sync/once.go:57
Jan 13 07:51:23 eu geth[11356]: github.com/ethereum/go-ethereum/consensus/ethash.(*dataset).generate(0xc07aa58140, 0xc0002ab5d0, 0xd, 0x2, 0x0)
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:2
94 +0x9a fp=0xc0271c1f88 sp=0xc0271c1f38 pc=0xaf464a
Jan 13 07:51:23 eu geth[11356]: github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).dataset.func1(0xc07aa580f0, 0xc0001e2c30, 0x100aaa0, 0xc07aa58140)
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:5
81 +0xa7 fp=0xc0271c1fc0 sp=0xc0271c1f88 pc=0xafd4c7
Jan 13 07:51:23 eu geth[11356]: runtime.goexit()
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/.go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0271c1fc8 sp=0xc0271c1fc0 pc=0x475351
Jan 13 07:51:23 eu geth[11356]: created by github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).dataset
Jan 13 07:51:23 eu geth[11356]: #011/build/ethereum-Bq7Cjd/ethereum-1.9.9+build20761+bionic/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:5
76 +0xc5
Jan 13 07:51:23 eu geth[11356]: goroutine 1 [chan receive, 90 minutes]:
Jan 13 07:51:23 eu geth[11356]: github.com/ethereum/go-ethereum/node.(*Node).Wait(0xc0000edb80)
...
```
Full log available [here](http://tmp.lehis.ru/tmp/geth.txt)
How I can fix it?

**Comment by karalabe** [comment]
Geth tries to memory map a file to generate the next mining DAG and the OS refuses to grant it.

According to https://www.freedesktop.org/software/systemd/man/systemd.exec.html, `LimitAS` sets the `virtual` memory limit (`ulimit -v`), which also acts as a limit on mmap. Essentially you are limiting the address space Geth can use, even if that much memory is never actually consumed.

> RLIMIT_AS The maximum size of the process's virtual memory (address space) in bytes. This limit affects calls to brk(2), mmap(2) and mremap(2), which fail with the error ENOMEM upon exceeding this limit.

Instead of limiting the virtual address space (which doesn't make much sense really), you should limit the amount of physical memory that you're willing to give Geth (`ulimit -m`). I think at is `LimitRSS` in systemd world.

More at https://unix.stackexchange.com/questions/438986/is-setting-ulimit-v-sufficient-to-avoid-memory-leak

**Comment by lehisnoe** [comment]
I've used LimitAS because on servers even ixgbe drivers start lagged because there were nor free RAM nether free swap space.
Normally, LimitAS shouldn't be used at all (as it was with 1.9.8).

What size of RAM geth require if 32Gb is not enough?

**Comment by karalabe** [comment]
Our bootnodes consume 6-7GB RAM (with --cache 4096). Shoud definitely not eat up 32GB in any case.

LimistAS is still wrong, because you put a cap on the virtual address space, which mmap also uses. Current + future mining DAGs is already a huge address space, which never gets pulled into RAM, but nonetheless still needs to exist as address space.

Does Geth crash with the virtual memory limit removed? Do you have a log of such a crash?

**Comment by lehisnoe** [comment]
There is no crash geth 1.9.9 with virtual memory limit removed, but servers stop responding by network when no free memory left.

**Comment by lehisnoe** [comment]
I've removed LimitAS and restart one of geth nodes. Let's wait while geth will eat all available RAM.
What kind info may be helpful?

**Comment by karalabe** [comment]
Are you monitoring the node via the exposed metrics? (Influx / Grafana)? If yes, this is one of our current dashboard snapshots https://gist.github.com/karalabe/858516531f611de2c217630d698c60a0, it would be helpful to see how things evolve.

**Comment by lehisnoe** [comment]
Not yet, but I'll do right now: I've already installed influxdb+grafana.

**Comment by karalabe** [comment]
Btw, we've reached out to Bitfly and Sparkpool and they are running 1.9.9 since it was released without issues, memory consumption seems stable.

**Comment by lehisnoe** [comment]
Maybe my startup args are differ from them.
Let's wait when geth eats all RAM. Now it looks like
```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
18418 root       20   0 25.0G 13.7G 71188 S 242. 43.9 92h06:52 /usr/bin/geth
```
![image](https://user-images.githubusercontent.com/12033768/72594869-92ea0f80-3919-11ea-8682-6fe91c66fef9.png)

**Comment by lehisnoe** [comment]
Update info:
```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
18418 root       20   0 28.1G 15.4G  102M S 291. 49.2     153h /usr/bin/geth
```
![image](https://user-images.githubusercontent.com/12033768/72661700-82579900-39ee-11ea-84c0-51864cfa2fe6.png)

**Comment by lehisnoe** [comment]
Current info:
```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
18418 root       20   0 29.5G 16.5G 69948 S 256. 52.9     370h /usr/bin/geth
```
![image](https://user-images.githubusercontent.com/12033768/72866881-fe532900-3ced-11ea-82e6-59cb14370ae7.png)

Look at **VIRT** - it seems that value is too high, isn't it?

**Comment by lehisnoe** [comment]
Looks like geth became runs stable. Current data:
```  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
18418 root       20   0 31.7G 15.7G  123M S 291. 50.4    2170h /usr/bin/geth```

![image](https://user-images.githubusercontent.com/12033768/74810525-9d287080-5300-11ea-8378-33caf04807a4.png)

Geth-1.9.10 looks like stable too on another node.

It's time to upgrade to geth-1.9.11 ;), so let's close this issue.

Thanks for the support.

**Comment by karalabe** [comment]
Thanks for all the investigation :)

**Comment by nyetwurk** [comment]
v1.10.4 is leaking now.

**Comment by karalabe** [comment]
@nyetwurk Please open an issue then. Your comment is absolutely useless to try and even figure out what's wrong if any.
