### ISSUE TITLE
POA old Node join New chain, old data over new chain data.

### ISSUE THREAD

**Issue by sueboy19** [ethereum/go-ethereum#20543]
Make POA chain： 3 singer,  2 node

signer1  (mining)  
signer2  (mining)  
signer3  (mining)  
node1  
node2  

    signer1 <- node1
    signer2 <- node2
    signer1 <-> signer2
            <-> signer3

Send transaction to node1 1xxx records and block number is 1xxx. Check all chain sync data is OK. Send transaction & contract get/set both work correct.

Stop all signers & nodes. Delete signer1、signer2、 signer3、node2 data. Only Deep node1 old data.
Now start signer1、signer2、signer3、node2 and clique.propose() signers. Sure now chain is working. Use web3 send transaction to signer1. Signer1 get trasactions and smart contract get/set can get number and number is correct.

    signer1 X  node1(old data)
    signer2 <- node2
    signer1 <-> signer2
            <-> signer3

New chain: block number is 3x.

Now start node1. Wait maybe 1min. Old data over new Chain data. Signer1 block number become 1xxx. And contract get/set value is 0. Contract disappear.

Why old node data recover to new chain？ Usually is node1 have error or can't connection to sigenr1 that Kick off node1.

This is BUG or ?

#### System information

Geth version: `1.9.6`
OS & Version: Linux
Docker & docker-compose
Image:  FROM ethereum/client-go:alltools-v1.9.6

#### genesis
    "clique": {
      "period": 5,
      "epoch": 30000
    }

**Comment by karalabe** [comment]
Not sure I follow. Nodes will cross sync between each other and will end up with the most difficult chain. Even if you delete a chain locally, when you connect to a remote node, if that chain is heavier, yours will be dropped in favor of the remote one.
