### ISSUE TITLE
Missing trie node error

### ISSUE THREAD

**Issue by bulgakovk** [ethereum/go-ethereum#20557]
#### System information

Geth version: `Geth/v1.9.10-unstable-3bb6815f-20191225/darwin-amd64/go1.13.5`

OS & Version: OSX

Branch, Commit Hash or Release: `e9e69d6e`

#### Expected behaviour
`state.New()` should return a new state from a given block hash when `full` database directory provided. 

#### Actual behaviour
Getting `panic: missing trie node <block hash>`

#### Steps to reproduce the behaviour
I completely synced a tesnet chain with following command: `geth --datadir /Users/kirill/geth/data --syncmode full --goerli`. Then started this util: https://github.com/bulgakovk/go-ethereum/commit/8ee6485ec0a432e0e8ed4acee38ce6d8055fc492. The code contains latest know at that moment hash but I also tried with genesis.

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Take care, state.New() does not operate on block hashes, rather state roots. That's a field within the block.

**Comment by bulgakovk** [comment]
@karalabe Thank you for your answer, that makes a lot of sense. If you're still here, could you please point me on documentation or comments where I can clarify details about tries lifecycle e.g. how geth decide which block's trie should be built and saved etc. I'm wondering because `state.New()` could find trie for genesis block but can't for the most recent.

Thank you!

**Comment by holiman** [comment]
There's no external documentation about this, but it's documented within the code. Look at `trie.go`, for example. The trie nodes reference other trie nodes, and 'expands' as needed. So if you have only a root, and you try to walk it down a certain path, it will resolve nodes from the database as needed. 

> I'm wondering because state.New() could find trie for genesis block but can't for the most recent.

That sounds like you're not yet synced. If you are not finished with your fast-sync, your node will report a certain block as being the most recent, but all state is not finished downloading: this will have an incomplete state-trie.

**Comment by bulgakovk** [comment]
@holiman Thank you for clarification!
