### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by brw31415** [ethereum/go-ethereum#2055]
hi, i'm trying to build ethereum on debian jesse using the Makefile include in the download  and get these  errors, http://pastebin.com/ZY4KbcPu which seems to be in line 17 of Makefile  http://pastebin.com/A0QATV8M  thanks for any help!

**Comment by fjl** [comment]
go-ethereum requires Go 1.4 or later to compile. Please install the go compiler from https://golang.org/dl/ instead of using `apt-get`.
