### ISSUE TITLE
Get rid of "Failed to enumerate USB devices" error log

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20568]
When I run a Geth instance, it starts with a bunch of error logs complaining "Failed to enumerate USB devices". I'm not using a hardware wallet.

#### System information

Geth version: 1.9.9
OS & Version: both Linux, and OSX
Commit hash : (if `develop`)

#### Expected behaviour
Complaing about a problem with usb only if I explicitly expressed I want to use usb.

#### Actual behaviour
Always complains.

#### Steps to reproduce the behaviour
`geth` :)

**Comment by karalabe** [comment]
You can run with `--nousb` if you want USB wallet support disabled. By default it's enabled.

**Comment by edo-lynx** [comment]
Alternatively you can add libusb to docker container :
apk add  libusb
apk add libusb-dev

and error will go away
