### ISSUE TITLE
Unexpected signal during runtime execution

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#20574]
#### System information

Geth version: `1.9.9-stable-01744997`
OS & Version: Windows 10 x64 1909

#### Expected behaviour
No crash

#### Actual behaviour
Crash, followed by the following after restarting the node:
```
WARN [01-17|09:55:34.093] Synchronisation failed, dropping peer    peer=1163b590769a2845 err="retrieved hash chain is invalid"
WARN [01-17|09:55:52.023] Synchronisation failed, dropping peer    peer=11e0c1edda09ea9b err="retrieved hash chain is invalid"
WARN [01-17|09:55:58.074] Synchronisation failed, dropping peer    peer=b5e858d3910cf838 err="retrieved hash chain is invalid"
WARN [01-17|09:56:37.362] Synchronisation failed, dropping peer    peer=b5e858d3910cf838 err="retrieved hash chain is invalid"
WARN [01-17|09:56:50.510] Synchronisation failed, dropping peer    peer=3b95c0d3e14e5021 err="retrieved hash chain is invalid"
WARN [01-17|09:57:18.111] Synchronisation failed, dropping peer    peer=b5e858d3910cf838 err="retrieved hash chain is invalid"
WARN [01-17|09:58:46.065] Synchronisation failed, dropping peer    peer=fdd095bfbd54c5fe err="retrieved hash chain is invalid"
WARN [01-17|09:58:57.225] Synchronisation failed, dropping peer    peer=b5e858d3910cf838 err="retrieved hash chain is invalid"
```

I think my sync is hosed? Also this is actually the 2nd time this has happened to me, I just didn't open an issue the 1st time.

#### Steps to reproduce the behaviour
I run geth via a scheduled task via a bat file. This is a `--syncmode full` run

```
@ECHO OFF
FOR /F "tokens=*" %%g IN ('curl -s ipinfo.io/ip') do (SET extip=%%g)
C:\Geth\geth.exe --datadir C:\Geth\Data --datadir.ancient D:\Geth\Data --identity MysticRyuujin-Geth03 --ethstats=MysticRyuujin-Geth03:<redacted>@ethstats.net --maxpeers 200 --light.serve 100 --nat extip:%extip% --rpc --rpcapi db,eth,net,web3,admin --rpcaddr 192.168.10.50 --rpccorsdomain "*" --rpcvhosts "*" --rpcport 8543 --syncmode full --cache 8192 >> c:\geth\log.txt 2>&1
```

#### Backtrace

This is the full and complete log.

[crashlog.zip](https://github.com/ethereum/go-ethereum/files/4077614/crashlog.zip)

Crash happens @ line 10871 starting with:
```
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x4167c3]
```

**Comment by MysticRyuujin** [comment]
Question: I was unable to get the sync to resume after closing due to the above `retrieved hash chain is invalid` errors. So, I deleted the chaindata folder, but kept the freezer, and restarted the node.

It appears that Geth then imported everything from the freezer but proceeded to sync in fast mode, ignoring the `--syncmode full` parameter.

Is that expected behavior?

```
INFO [01-17|10:37:35.356] Initializing chain from ancient data     number=4501014 hash=9830a5…f3c841 total=4504404 elapsed=13m34.434s
INFO [01-17|10:37:37.600] Initialized chain from ancient data      number=4504404 hash=819e10…bec160 elapsed=13m36.678s
INFO [01-17|10:37:37.605] Loaded most recent local header          number=4504404 hash=819e10…bec160 td=1393144136821823616606 age=2y2mo3w
INFO [01-17|10:37:37.606] Loaded most recent local full block      number=0       hash=d4e567…cb8fa3 td=17179869184            age=50y9mo1w
INFO [01-17|10:37:37.606] Loaded most recent local fast block      number=4504404 hash=819e10…bec160 td=1393144136821823616606 age=2y2mo3w
INFO [01-17|10:37:37.608] Upgrading chain index                    type=bloombits percentage=0
INFO [01-17|10:37:37.610] Loaded local transaction journal         transactions=0 dropped=0
INFO [01-17|10:37:37.612] Regenerated local transaction journal    transactions=0 accounts=0
WARN [01-17|10:37:37.612] Switch sync mode from full sync to fast sync 
```

**Comment by holiman** [comment]
It is not desired behavior, but we know about it: https://github.com/ethereum/go-ethereum/issues/19199

**Comment by MysticRyuujin** [comment]
Started fresh. Happened again.

Starting Line 5158:

```
INFO [01-18|16:31:26.490] Imported new chain segment               blocks=341   txs=8394  mgas=504.427  elapsed=8.023s    mgasps=62.870  number=3776790 hash=37f10b…9d8aa2 age=2y8mo6d   dirty=993.86MiB
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x4646c7]
```

[crashlog2.zip](https://github.com/ethereum/go-ethereum/files/4082037/crashlog2.zip)

**Comment by karalabe** [comment]
This seems very wrong. It's a memory corruption issue.

Either we mess up some custom memory handling (we only ever do that for the ethash cache/dag handling via SetFinalizer... did we bork it in a fresh release? Seems to be modified in November).

Alternatively Go borked something, but that might be odd.

**Comment by karalabe** [comment]
We should probably start by building with Go 1.13.6 and see if it still persists. At least 1 runtime fix was included in 1.13.5 that produced an unexpected fault address error https://github.com/golang/go/issues/35207, though my hunch is that it's unrelated.

**Comment by MysticRyuujin** [comment]
I'd be happy to do a build from source or whatever it is that might help. Do you want me to try to build Master from source for Windows? I've not done that before but I can probably figure it out.

**Comment by karalabe** [comment]
Neah, we'll do a stable release anyway, so might as well grab that when it's out.

**Comment by karalabe** [comment]
Pushed the release. Please grab a copy of 1.9.10 from your usual location and check if it still acts up. It should be built with the latest Go release available.

**Comment by MysticRyuujin** [comment]
Alright, I did a totally fresh run on the Windows 1.9.10 binary. Same error.

```
INFO [01-20|17:20:22.388] Imported new chain segment               blocks=282   txs=12612 mgas=699.166  elapsed=8.006s    mgasps=87.321  number=4095753 hash=d619bd…ba19be age=2y6mo4d   dirty=1.71GiB
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x4164ce]
```

Starting at line 6488. Complete log attached.

[errorlog.zip](https://github.com/ethereum/go-ethereum/files/4094941/errorlog.zip)

**Comment by MysticRyuujin** [comment]
So I'm guessing this is a similar situation as my other node, something is getting bit flipped or corrupted? This PC also does not have ECC memory, but it is a brand new PC with brand new storage. 🤷‍♂  I'll happily run hardware diagnostics on it too if you think it would help.
