### ISSUE TITLE
App test fails if this package is a dependency

### ISSUE THREAD

**Issue by sammy007** [ethereum/go-ethereum#20571]
#### System information
```yaml
[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.9.9"
```

I am using some packages from this repo in my app, when I am running `go test -v ./...` for my package I am getting the following errors:

There is no even code in tests yet, just a stub which fails.

#### Backtrace

````
vendor/github.com/karalabe/usb/hid_enabled.go:22:10: fatal error: './hidapi/hidapi/hidapi.h' file not found
#include "./hidapi/hidapi/hidapi.h"
````

````
vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:42:10: fatal error: 'libsecp256k1/include/secp256k1.h' file not found
#include "libsecp256k1/include/secp256k1.h"
````

**Comment by karalabe** [comment]
Go fails to properly vendor in packages that have subfolders containing only C files. I opened an issue way way back, but the response was that Go is not C and they won't fix it. Unfortunately this means that if you use vendoring on top of Go modules, you'll need to manually add the missing C folder for USB, sekp256k1 and maybe ducktape.

**Comment by karalabe** [comment]
Can't find my issue, but here's one from someone else, closed as always https://github.com/golang/go/issues/27832

**Comment by sammy007** [comment]
It's also because I have used:

```yaml
[prune]
  go-tests = true
  unused-packages = true
```

Removed pruning and all fine. Closing.

**Comment by glowkeeper** [comment]
I'm seeing this after running go mod vendor. As you suggest @karalabe (thanks), I can 'fix' by manually copying over the missing header files, but that's not ideal. Are the _Go_ people really not going to fix this?
