### ISSUE TITLE
permission denied when using --datadir

### ISSUE THREAD

**Issue by 7--** [ethereum/go-ethereum#20584]
```
$ geth --datadir /home/phil/media/hd/eth-node
INFO [01-20|20:21:09.759] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [01-20|20:21:09.763] Maximum peer count                       ETH=50 LES=0 total=50
INFO [01-20|20:21:09.763] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
Fatal: Failed to create the protocol stack: mkdir /home/phil/media/hd/eth-node/keystore: permission denied
```

The folder has full permission.
```
$ ll  /home/phil/media/hd/ 
drwxrwxrwx 2 phil phil  4096 Jan 20 18:27 eth-node/
```
```
$ geth version
Geth
Version: 1.9.6-unstable
Architecture: amd64
Protocol Versions: [63]
Network Id: 1
Go Version: go1.11.13
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.11.13.linux.amd64

```

I'm reinstalled geth with snap and have the same issue.

**Comment by holiman** [comment]
I'm not very familiar with `snap`, but it's apparently some form of light virtualization? It seems that snap installed binaries are not able to write data to arbitrary locations. 

One search result: https://askubuntu.com/questions/762354/where-can-ubuntu-snaps-write-data :

> That wrapper contains most of the environment under which the application will run. The two environment variables that are most relevant to this question are `SNAP_DATA` and `SNAP_USER_DATA`.
>
>    `SNAP_DATA` is a system-wide writable area (in /var/snap/). This might be used to host logs for services, for instance.
>
>    `SNAP_USER_DATA` is a user-specific writable area in the home directory of the user running the application (specifically /home/<user>/snap/). This might be used for user-specific configuration files, etc.

**Comment by karalabe** [comment]
Also FYI, that Geth is outdated and is lacking the two latest forks. We do not maintain the snaps, so we also cannot control it's security. Please use PPAs, grap prebuilt downloads from https://geth.ethereum.org/downloads/ or build it yourself.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@karalabe Which PPAs do you have control over? Please tell URLs

**Comment by isti4github** [comment]
Please before trying other solution, try to run your command in root user mode. In Linux you may jump to root user mode using $sudo su
