### ISSUE TITLE
About block size limit

### ISSUE THREAD

**Issue by usd-yamazaki** [ethereum/go-ethereum#20588]
Normally, block creation is limited only by the block gas limit, not by the data size.
However, the RLPx protocol for sending and receiving created blocks has a 24bit (16MB) data size limit.
https://github.com/ethereum/devp2p/blob/master/rlpx.md#message-encoding

Thus, if Parity creates a huge block over 16MB,
It seems that there is a problem that it has the latest block but cannot send, and stops synchronization.
https://github.com/paritytech/parity-ethereum/issues/11334

Does Geth have this problem?
If not, how do you avoid it?

Also, if you have an EIP that mentions this issue, could you tell me?

Thank you.

**Comment by karalabe** [comment]
Yes, the network packets are limited to 10MB. The only way around it is to implement chunking, either in the devp2p protocol (there's a spec, but not much tendency) or in the `eth` subprotocol (might get messy).

**Comment by usd-yamazaki** [comment]
If the data size of the created block is large, the situation where the block cannot be transmitted and the synchronization stops completely is a very serious problem.
If it is difficult to modify the protocol, is it possible to add a function to keep the data size of the block created on Geth side within 16MB (10MB?)?

Unfortunately the Parity community has no response ...
