### ISSUE TITLE
Non-local, non-executable transactions are 'randomly' removed from transaction pool queue

### ISSUE THREAD

**Issue by SatpalSandhu61** [ethereum/go-ethereum#20582]
#### System information

Version: 1.9.10-unstable
Git Commit: 3e97b04a3df8a175b7cc61ae8f6f7e0d40f5cd4b
Git Commit Date: 20200116
Architecture: amd64
Protocol Versions: [64 63]
Go Version: go1.11.13
Operating System: darwin

#### Expected behaviour

Non-local, non-executable transactions held in txpool.queue should be discarded after the time specififed by `--txpool.lifetime` has passed (similar to the behaviour for pending transactions).

#### Actual behaviour

Non-local, non-executable transactions are removed from txpool.queue on the next tick of the `evictionInterval` timer, which ticks every minute.
This basically means that any non-local transaction with a future nonce will get deleted, if it doesn't quickly become eligible for execution.

#### Steps to reproduce the behaviour

- Run geth with `--txpool.nolocals`, to simulate non-local transactions.
- Submit a transaction with a future nonce, so that it sits in txpool.queue.
- When the next tick occurs (within one minute), the transaction will be deleted from the queue.

Looking into this issue, I can see that transactions are removed from the queue by the following code in tx_pool.go:
```
if time.Since(pool.beats[addr]) > pool.config.Lifetime {
	for _, tx := range pool.queue[addr].Flatten() {
		pool.removeTx(tx.Hash(), true)
	}
}
```

The problem is that pool.beats[addr] is not being initialised for non-executable transactions.
The code to initialise pool.beats[] was added in [promoteTx()](https://github.com/ethereum/go-ethereum/blob/master/core/tx_pool.go#L728) for executable transactions as part of [PR #2742](https://github.com/ethereum/go-ethereum/pull/2742).
However, that code should also have been added for non-executables in [enqueueTx()](https://github.com/ethereum/go-ethereum/blob/master/core/tx_pool.go#L652).

**Comment by karalabe** [comment]
Oh nice, thanks for the report. Will look into it tomorrow and try to repro.

**Comment by holiman** [comment]
Closed with https://github.com/ethereum/go-ethereum/pull/21300
