### ISSUE TITLE
Don't try to create chain spec if consensus engine not supported

### ISSUE THREAD

**Issue by wbt** [ethereum/go-ethereum#20600]
In [this issue](https://github.com/ethereum/go-ethereum/issues/19905), there is a subset of console output: 

````
Shell> puppeth
...
Which consensus engine to use? (default = clique)
 1. Ethash - proof-of-work
 2. Clique - proof-of-authority
> 2
...
Which folder to save the genesis specs into? (default = current)
  Will create issuedemo.json, issuedemo-aleth.json, issuedemo-harmony.json, issuedemo-parity.json
>
�[32mINFO �[0m[07-30|10:08:17.511] Saved native genesis chain spec          �[32mpath�[0m=issuedemo.json
�[31mERROR�[0m[07-30|10:08:17.511] Failed to create Aleth chain spec        �[31merr�[0m="unsupported consensus engine"
�[31mERROR�[0m[07-30|10:08:17.511] Failed to create Parity chain spec       �[31merr�[0m="unsupported consensus engine"
�[32mINFO �[0m[07-30|10:08:17.513] Saved genesis chain spec                 �[32mclient�[0m=harmony �[32mpath�[0m=issuedemo-harmony.json
````

I've just observed this again on geth 1.9.10 64-bith for Windows 10.

#### Expected behaviour
Before displaying the "will create" list, puppeth checks the genesis block's consensus engine.  If `clique` is selected, the "will create" list lacks *networkname*-aleth.json and *networkname*-parity.json and does not attempt to create these files after a location is entered.

When an error is presented, characters are printable.

#### Actual behaviour
Errors are encountered, confusing the user, when this outcome was easily predictable before the question triggering the error.  Error messages are hard to read with unprintable characters. 

#### Steps to reproduce the behaviour
See linked issue for more detailed command/interaction steps if the above isn't sufficient.

**Comment by holiman** [comment]
Geth/puppeth should properly detect whether the console supports ANSI-codes or not, and modify the behaviour as needed. 
Regarding the confusing error messages, this works as expected (it tries, but fails to create them)

**Comment by karalabe** [comment]
Also we should probably add support for parity clique

**Comment by holiman** [comment]
Puppeth is more or less deprecated by now, post-merge. It is not up to date with regards to configurations and clients, and needs either an very thorough overhaul, or removal.

Closing this as a wont-fix
