### ISSUE TITLE
why sendTransaction via RPC is too slow?

### ISSUE THREAD

**Issue by lnpu** [ethereum/go-ethereum#20607]
I want to make a multi-user eth wallet , use geth as client, when user send a transaction, i submit it to a queue server, then my server get the transaction data from queue and call RPCAPI sendTransaction.

But sendTransaction often take a lot of seconds, if I submit 1000 transaction, it is very slow, Is there any solution?

**Comment by ligi** [comment]
You will need to provide some more information. I can just guess you are on some private (PoA?) network as otherwise

> if I submit 1000 transaction, it is very slow

would be easily to explain as 1000 transaction would need multiple blocks and multiple blocks would need multiple blocktimes which is a "lot of seconds"
So please provide more details about your problem and use-cases.

**Comment by lnpu** [comment]
> You will need to provide some more information. I can just guess you are on some private (PoA?) network as otherwise
> 
> > if I submit 1000 transaction, it is very slow
> 
> would be easily to explain as 1000 transaction would need multiple blocks and multiple blocks would need multiple blocktimes which is a "lot of seconds"
> So please provide more details about your problem and use-cases.

I use ropsten network, running geth with follow command:

`nohup geth --testnet --syncmode "light" --port "30303" --cache=256 --datadir /data/geth --allow-insecure-unlock --rpc --rpcapi db,eth,net,web3,personal,admin --rpcport 8545 --rpcaddr 0.0.0.0 --rpccorsdomain "*"  --maxpeers 256  --maxpendpeers 256 > output.log 2>&1 &`

the i use nginx as proxy listening to 8545
`        location /eth {
                auth_basic "Restricted access to this site";
                auth_basic_user_file /etc/nginx/protected.htpasswd;

                # Proxy to geth note that is bind to localhost port                        
                proxy_pass http://localhost:8545;
        }`

**Comment by ligi** [comment]
Hm, but if you use ropsten I really do not see your point. if you send 1000 tx to ropsten it will take a while - do not see how geth could improve here ..
What is your use-case?

**Comment by lnpu** [comment]
> Hm, but if you use ropsten I really do not see your point. if you send 1000 tx to ropsten it will take a while - do not see how geth could improve here ..
> What is your use-case?

oh, no. I call sendTransaction in my other serve,  ervey sendTransaction response too slow.thanks.

**Comment by lnpu** [comment]
> Hm, but if you use ropsten I really do not see your point. if you send 1000 tx to ropsten it will take a while - do not see how geth could improve here ..
> What is your use-case?

It is there any suggestion about my think in my use-case?  Thanks a million

**Comment by ligi** [comment]
I still do not know what your use-case is tbh ..

**Comment by lnpu** [comment]
> I still do not know what your use-case is tbh ..

 like this: 

<img width="488" alt="aaaaaa" src="https://user-images.githubusercontent.com/56826056/73425191-d3ab4500-436b-11ea-9316-68dd8cc2713f.png">

**Comment by ligi** [comment]
With use-case I mean something  more high-level. What you show is a "how" and I am looking for a "what"

**Comment by lnpu** [comment]
> With use-case I mean something more high-level. What you show is a "how" and I am looking for a "what"
Sorry
<img width="674" alt="aaaaaaaaaa" src="https://user-images.githubusercontent.com/56826056/73503232-ad86b300-4406-11ea-95e8-f67637dc9fca.png">


> With use-case I mean something more high-level. What you show is a "how" and I am looking for a "what"

Sorry, see the new image

**Comment by karalabe** [comment]
Which RPC method are you using?

**Comment by lnpu** [comment]
> Which RPC method are you using?

I using nginx proxy http RPC, using web3.eth.sendTransaction(transaction) send transaction

code:
`
            transaction = {'to': _to, 'from': _from, 'value': self.toWei(value)}
            estimateGas = web3.eth.estimateGas(transaction)
            if int(estimateGas*web3.eth.gasPrice+int(self.toWei(value)))>int(web3.eth.getBalance(_from)):
                app.logger.warning('insufficient balance: gas*gasPrice+value < balance')
                return False
            web3.geth.personal.unlockAccount(_from, self.passphrase)
            return web3.eth.sendTransaction(transaction)

`

**Comment by ligi** [comment]
oh - then it is very likely that unlockAccount is the slow thing here and not the sendTransaction. You should not really unlock for every sendTransaction - that is quite bad design.

**Comment by gballet** [comment]
Yeah, unlocking accounts is your bottleneck. We suggest you look into clef in order to sign the transactions, and therefore not need to go through that bottleneck. We're closing this issue as there is a preferred way to do this.
