### ISSUE TITLE
Upgrading account non-interactive mode: flag provided but not defined: -password

### ISSUE THREAD

**Issue by pi11** [ethereum/go-ethereum#20606]
Geth
Version: 1.9.10-stable
Git Commit: 58cf5686eab9019cc01e202e846a6bbc70a3301d
Git Commit Date: 20200120
Architecture: amd64
Protocol Versions: [64 63]
Go Version: go1.13.6
Operating System: linux
GOPATH=
GOROOT=/home/serge/bin/go

So I run command - 
geth account update --password 'MySuperPassword' my_account

And got error:
flag provided but not defined: -password

**Comment by adamschmideg** [comment]
Try 
```
geth --password 'SuperPassword' account update your_account
```
The `--password` flag belongs to the top level, not to the `account update` subcommand.

**Comment by adamschmideg** [comment]
@ravinitp why not open a PR

**Comment by ravinitp** [comment]
Already raised PR but got rejected.
https://github.com/ethereum/go-ethereum/pull/21151

**Comment by karalabe** [comment]
@pi11 Just use `geth account update my_account` and type in both old and new password.

**Comment by fjl** [comment]
Since @karalabe suggestion does not work non-interactively, let me provide another suggestion.
If you use the ethkey command (it's included in go-ethereum alltools), you can change the password
of an account like this:

```
ethkey changepassword --passwordfile <file> --newpasswordfile <file2> keyfile.json
```
