### ISSUE TITLE
Feature request: ability to define for how long old states are kept (in memory OR on disk) before pruning

### ISSUE THREAD

**Issue by toruvinn** [ethereum/go-ethereum#20625]
Hello. While playing around and pulling data from the chain, I've ran into an issue.

What I personally need to do is call one readonly contract function every block and store the return value in a database. With the default setting of 128 past historical states kept in memory, once my process pulling the data goes down for 128*15 (well, less now) seconds, I lose the ability to access the data. What I would really like is an option to just keep the states for, say, the past week. Then prune them. Some sort of setting that would define the time (or block count) for the states to be kept available for eth_call RPC would solve the issue.

Currently keeping a full archival node is a bit of an overkill and requires significant amount of storage, yet I'm sure quite often we do not need to check the state of a really old block.

This sounds more like a pruning mechanism enhancement to me - have a node that persists states (archival mode), but a tunable prune function that would remove everything that isn't needed to retrieve states for blocks not older than PruneStatesOlderThan seconds (or blocks, I don't care).

I also wonder if keeping a separate leveldb instance for tries could be beneficial. The reason for that is that we can divide those types of storage (ancient, not-frozen - and tries) across different filesystems/storages (what would happen if I wiped the trie database, though?).

Thank you.

**Comment by AmitShah** [comment]
Have you examined the rpc "reexec" parameter which will attempt to regenerate state by the number of blocks passed as a parameter?  Of course this is problematic if all the state cannot be recreated in the window.

**Comment by holiman** [comment]
An alternative solution to this, without causing memory issues or disk issues with massive states, is if geth could support a "plugin" model, where 

- For each block, run plugin 'x'
- In 'x', you can have programmatic access to the state, and do whatever data collection you want.
- Next block is only processed after the plugin is done. 

Then you could start geth with e.g.  `geth --blockpostprocess=blabla.wasm` . Thoughts?

**Comment by toruvinn** [comment]
That would work assuming blabla.wasm always executes perfectly and never loses its output.
On the other hand, assuming wrong blabla.wasm implementation, as long as we have n blocks worth of states, we can always easily "rewind" and retry...
That's useful if we're coding something from scratch and want to test it, even if we're just trying things out to create said blabla.wasm.

That said, I'd still kind of welcome a prune function that can remove old, not useful data from disk. That could be helpful with cleaning the database that has some unneeded states flushed to reduce the storage size. Additionally, the ability to store states to a separate leveldb could also help with cleanup.

**Comment by Shirley-Ji** [comment]
Not sure if there is any updates on this issue?
There are more and more space used currencly in the archive node, it is very space consuming to keep. In current dapp/browser/wallet service scenarios, actually those old data has been parsed and moved to other places(e.g. hbase, mysql, graphnode) to store and access, keeping the old tx data and contract data is really space consuming.

**Comment by MariusVanDerWijden** [comment]
This will be a feature in the new PBSS archive node. Since this FR is quite old I'm going to close it for now. We are very aware of this feature and it will definitely be available with the PBSS archive node at some point
