### ISSUE TITLE
How to find bottleneck in geth sync?

### ISSUE THREAD

**Issue by poma** [ethereum/go-ethereum#20620]
I'm trying to benchmark geth full sync. Here are my current machine specs:

- Google Cloud
- Ubuntu 16.04.6, Docker 19.03.5, Geth 1.9.11
- 16 vCPU
- 14 Gb RAM
- 700 Gb NVMe SSD RAID 0
- 772k read/258k write IOPS
- 6+ Gbps network

Launching with following `docker-compose.yml`

    version: '2'
    services:
      geth:
        image: ethereum/client-go
        command: "--syncmode full --nat=extip:x.x.x.x --cache=12288 --nousb"
        restart: always
        stop_grace_period: 4m
        stop_signal: SIGINT
        ports:
          - 30303:30303
        volumes:
          - /mnt/disks/ssd:/root/.ethereum

So far none of the resources seem to be maxed out:

- loadavg 3/16
- network 0.3/750 MB/s
- iops (r+w) 20/1000000

The machine appears to be mostly idle. How do I find out what is currently limiting sync speed?

Current speed at block 2M is ~300 blocks/sec

**Comment by poma** [comment]
It looks as if there is not enough nodes seeding block data

**Comment by karalabe** [comment]
Block processing unfortunately is inherently single threaded (each tx execution depends on the one before it). This means that during full sync, although we try to do as many things as we can parallel (e.g. PoW checks, header validation), at the end of the day only a single core will be fully saturated.

Overall speed wise, in full sync the bottleneck is your local CPU, so more peers won't help (they would for fast sync).
