### ISSUE TITLE
GraphQL: Expose signature parameters for Transactions 

### ISSUE THREAD

**Issue by AmitShah** [ethereum/go-ethereum#20622]
#### System information

Geth version: 1.9.8-stable
OS & Version: OSX

#### Feature Request
Currently when querying transactions using the GraphQL interface, there is no means to retrieve the signature parameters [R,S,V]. 

The fields are necessary to calculate transaction hash and perform any validation on the returned results.  

Are there any plans to add the support or I can submit a pull request

**Comment by ligi** [comment]
Thanks for the issue and the PR! Can you elaborate a bit more on your use-case?

**Comment by AmitShah** [comment]
I allow others to query my full sync unpruned geth node.  As I am acting as a central data authority, clients want to verify the BlockHash and currently just the TransactionRoot my api returns. The clients construct a local Merkle Patricia Trie proof.  All the information for creating this proof can be gathered with a single GraphQL query if we expose the signature parameters.  If not, they have to query for the Signature parameters for each transaction in the block.

**Comment by AmitShah** [comment]
merged pr: https://github.com/ethereum/go-ethereum/pull/20623
