### ISSUE TITLE
Add tx hash to tracers

### ISSUE THREAD

**Issue by kryvel** [ethereum/go-ethereum#20629]
Hi there,
Is it possible to get transaction hash in tracer?
Using this one or any other (custom) js tracer
https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/internal/tracers/call_tracer.js
I tried to use debug_traceBlock endpount, there are all necessary information except tx hash

My goal is to find all incoming transactions to my addresses by RPC API. 

I just moved from parity, and they have trace_block.

TIA

**Comment by holiman** [comment]
So let me summarize: 
From the js context, for certain transactions (that e..g touch your account), you want to spit out the tx hashes.

**Comment by karalabe** [comment]
I think this is a valid feature request, needs a bit of API massaging though. We'd need to modify CaptureStart to add some more contextual fields (block number, tx hash).

**Comment by kryvel** [comment]
> So let me summarize:
> From the js context, for certain transactions (that e..g touch your account), you want to spit out the tx hashes.
> 
> We agree, it's a feature worth having

Hi,
Yes, exactly

**Comment by holiman** [comment]
cc @s1na want to have a go^ ?

**Comment by s1na** [comment]
`result()` has access to the transaction hash (`ctx.txHash`) now. I'm guessing that should be enough for the use-case. Closing the issue but please re-open if I misunderstood the feature request.

**Comment by pyropy** [comment]
Is this available inside native tracers? I'm using a custom native tracer and currently am limited to mapping traces to txs via index. 

Having something like this inside native tracer would be a great addition.

**Comment by s1na** [comment]
@pyropy Yep, the constructor to the tracer will receive a [Context](https://github.com/ethereum/go-ethereum/blob/ba2dd9385c2a51134e520083dc732787a813b107/eth/tracers/tracers.go#L32-L37) in which it is being executed.
