### ISSUE TITLE
Private network nodes connection problems

### ISSUE THREAD

**Issue by cryptohazard** [ethereum/go-ethereum#20633]
I am trying to run a private networks with a certain number nodes, using docker containers.
You can find the files here: [conteneurs](https://github.com/cryptohazard/conteneurs/tree/master/ethereum)

#### System information

```
Geth
Version: 1.9.10-stable
Git Commit: 58cf5686eab9019cc01e202e846a6bbc70a3301d
Architecture: amd64
Protocol Versions: [64 63]
Go Version: go1.13.6
Operating System: linux
```

#### Expected behaviour
Each nodes has the other ones as peers and they are on the same chain.

#### Actual behaviour
My nodes don't have many peers (logs not shared because of the IPs). They see nodes from other clusters but I get `Removing p2p peer ...   err="useless peer`

#### Steps to reproduce the behaviour

Start 2 clusters of containers nodes referencing each other's bootnode. I did my test with 3 servers and 4 nodes on each (1 bootnode, 1 normal node and 2 mining nodes).

**Comment by karalabe** [comment]
Could you run with `--verbosity=4` and send us some logs?

**Comment by holiman** [comment]
Also, more information about the general setup is needed -- what are the commandlines for the nodes and the bootnodes etc.

**Comment by karalabe** [comment]
Perhaps also the genesis config you're using and how your initializing your network.

**Comment by cryptohazard** [comment]
Hi all,

So I made a repo with all the files:
[the genesis](https://github.com/cryptohazard/conteneurs/blob/master/ethereum/ethnode/genesis.json)
[node dockerfile](https://github.com/cryptohazard/conteneurs/blob/master/ethereum/ethnode/Dockerfile)
[bootnode dockerfile](https://github.com/cryptohazard/conteneurs/blob/master/ethereum/bootnode/Dockerfile)
[docker-compose](https://github.com/cryptohazard/conteneurs/blob/master/ethereum/docker-compose.yml)

Now my issue is that my non-mining node (*injectionnode*) doesn't connect to the rest. So I just finish a test for ~20 minutes. I have a bootnode, one normal node and 3 miners. I put all the logs on the repo too:
[log folder](https://github.com/cryptohazard/conteneurs/tree/master/ethereum/logs)
[log bootnode](https://github.com/cryptohazard/conteneurs/blob/master/ethereum/logs/logbootnode)
[log injection node ](https://github.com/cryptohazard/conteneurs/blob/master/ethereum/logs/loginjectionnode)

**Comment by adamschmideg** [comment]
The links give a 404
