### ISSUE TITLE
build fails on RockPi4 (arm64 / aarch64) "Makefile:16: recipe for target 'geth' failed"

### ISSUE THREAD

**Issue by narayaana** [ethereum/go-ethereum#20639]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.9.10`
OS & Version: Linux, Debian 9.9
Commit hash : (if `develop`)
Go version: ` go1.13.7 linux/arm64`

#### Expected behaviour
compile with no error

#### Actual behaviour
see log attached. 

#### Steps to reproduce the behaviour
install debian 9.9 from https://wiki.radxa.com/Rockpi4/downloads
apt-get gcc make sysstat git
install go arm64 (https://dl.google.com/go/go1.13.7.linux-arm64.tar.gz)
get source and compile:
git clone https://github.com/ethereum/go-ethereum.git --branch v1.9.10
make geth

#### Backtrace

````
[backtrace]
````
[make.geth.log](https://github.com/ethereum/go-ethereum/files/4173735/make.geth.log)

**Comment by narayaana** [comment]
I did a full clean up of my debian and tried again. it works now. sorry for opening issue. might have been some files let somewhere in my tests.

**Comment by gballet** [comment]
Good to know. In general, for your experiments, you can just build `geth` with go: `go build ./cmd/geth/`
