### ISSUE TITLE
iGeth - ViewController.swift

### ISSUE THREAD

**Issue by alanwunsche** [ethereum/go-ethereum#2063]
Compiled iGeth in Xcode 7.2 and got a warning

Line 22: 
            let data = try NSURLConnection.sendSynchronousRequest(req, returningResponse: &res)

'sendSynchronousRequest... was deprecated in iOS9.0

**Comment by karalabe** [comment]
I know, that code is just an example playground, it's nothing official or even necessarily good coding practice. It was just quickly hacked together to display the functionality. Consider it demo sample code.
