### ISSUE TITLE
cmd line port 0 means it will be autogenerated

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20637]
I understand setting `--port 0` or `--rpcport 0` will assign a random available port. `geth help` should display this information.

**Comment by ligi** [comment]
I disagree here. `geth help` should be concise and this behavior is common and not specific to geth. Perhaps it should be somewhere in the documentation but IMHO it should not be part of `geth help`

**Comment by holiman** [comment]
I agree. Port 0 is special, and there actually is no port 0 iirc. Should randomize to some number above 1024 imo (sub 1024 are non-root ports)

**Comment by adamschmideg** [comment]
@holiman Do you agree with displaying it in geth help or do you agree with Ligi to keep the help concise and make it only part of the online documentation?

**Comment by karalabe** [comment]
Port 0 meaning "pick whatever is free" is standard networking. I don't think that should be part of the CLI, but we can definitely detail it in a web doc.
