### ISSUE TITLE
Naïve solution to blockchain size

### ISSUE THREAD

**Issue by lnogue** [ethereum/go-ethereum#20641]
It is simple, every 10K blocks, a special block is produced.

The special block has the balances of every wallet, once it is mined, its broadcasted to the network and validated as any other block and added to the blockchain.

You can then, delete all the blocks behind that special block, because it contains all the information of the balances and contracts previously created.

**Comment by ligi** [comment]
This is the wrong place to discuss something like this as it is not only about the go-ethereum implementation, but about a protocol change. You might want to discuss it here:

https://ethereum-magicians.org

That said I think this suggestion is so naive that it would not work. Balances are not the only state on Ethereum ..

**Comment by karalabe** [comment]
The state of Ethereum is about 15GB raw data. Receipts (which contain the log entries) are maybe about 100GB. That would be one big block :P You also have the issue of deep-er reorgs. PoW does not guarantee finality, so in theory you could have a deeper reorg than your snapshot block.

All in all, yes, please head over to the magicians to discuss these ideas.
