### ISSUE TITLE
gpg Go Ethereum Builder keys check failed

### ISSUE THREAD

**Issue by begetan** [ethereum/go-ethereum#20662]
#### System information
Geth version: `geth 1.9.10`
OS & Version: Linux Ubuntu 18.04.LTS

#### Expected behaviour
According to the [release documentation](https://geth.ethereum.org/downloads/) is should be used gpg keys to verify binary release:
```gpg --recv-keys F9585DE6 C2FF8BBF 9BA28146 7B9E2481 D2A67EAC```

#### Actual behaviour
Today our deployment system failed to verify Linux release. I checked each key manualy and found that 3 keys from 5 absence in gpg defaut server.

> gpg --recv-keys F9585DE6
> gpg: keyserver receive failed: No data
> $ gpg --recv-keys C2FF8BBF
> gpg: keyserver receive failed: No data
> $ gpg --recv-keys 9BA28146
> gpg: keyserver receive failed: No data
> $ gpg --recv-keys 7B9E2481
> gpg: key 558915E17B9E2481: 2 signatures not checked due to missing keys
> gpg: key 558915E17B9E2481: "Go Ethereum macOS Builder <geth-ci@ethereum.org>" not changed
> gpg: Total number processed: 1
> gpg:              unchanged: 1
> $ gpg --recv-keys D2A67EAC
> gpg: key 9417309ED2A67EAC: 2 signatures not checked due to missing keys
> gpg: key 9417309ED2A67EAC: "Go Ethereum Windows Builder <geth-ci@ethereum.org>" not changed
> gpg: Total number processed: 1
> gpg:              unchanged: 1
> 

#### Steps to reproduce the behaviour
```bash
gpg --recv-keys F9585DE6
gpg --recv-keys C2FF8BBF
gpg --recv-keys 9BA28146
gpg --recv-keys 7B9E2481
gpg --recv-keys D2A67EAC
```

**Comment by holiman** [comment]
I cannot repro: 
```
[user@work ~]$ gpg --recv-keys F9585DE6
gpg: key 70AD154BF9585DE6: public key "Go Ethereum Android Builder <geth-ci@ethereum.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
[user@work ~]$  gpg --recv-keys C2FF8BBF
gpg: key F29DEFAFC2FF8BBF: public key "Go Ethereum iOS Builder <geth-ci@ethereum.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
[user@work ~]$ gpg --recv-keys 9BA28146
gpg: key A61A13569BA28146: public key "Go Ethereum Linux Builder <geth-ci@ethereum.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
[user@work ~]$ gpg --recv-keys 7B9E2481
gpg: key 558915E17B9E2481: public key "Go Ethereum macOS Builder <geth-ci@ethereum.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
[user@work ~]$ gpg --recv-keys D2A67EAC
gpg: key 9417309ED2A67EAC: public key "Go Ethereum Windows Builder <geth-ci@ethereum.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by ligi** [comment]
Seems you get "keyserver receive failed: No data" when there is no connection to the keyserver possible. See e.g. https://forum.mxlinux.org/viewtopic.php?t=47885 Can you check your connectivity and try again?

**Comment by karalabe** [comment]
Works for me too

**Comment by begetan** [comment]
It was not a connectivity problem, because I was able to validate 2 of 5 keys with the same command at the same moment. Repeated procedure several time.

Also this issue has been appeared initially in AWS us-east-1 region, and then I confirmed it in my local network in another region.

Currently all five keys are validating fine for me to.  So if developers haven't update anything it was a gpg server issue.  Anyway I just warmed about it because it may be security related.

**Comment by ligi** [comment]
Thanks for the warning - appreciated. Better once too often than missed once. Still closing as I see nothing actionable here for us. But please reopen if you see something funky again.

**Comment by luisnaranjo733** [comment]
I was also seeing this issue despite having a stable internet connection.
I was able to resolve by using one of the --keyserver workarounds listen in the thread that @ligi shared in February (session below).

Maybe the geth GPG pub keys are only registered with the ubuntu GPG server, and not the keys.gnupg.net server? It could be that different distributions of gpg default to different keyservers, but I'm just speculating here.

```bash
➜  ~ gpg --recv-keys F9585DE6 C2FF8BBF 9BA28146 7B9E2481 D2A67EAC
gpg: keyserver receive failed: No data
➜  ~ gpg --keyserver hkp://keys.gnupg.net --recv-keys F9585DE6 C2FF8BBF 9BA28146 7B9E2481 D2A67EAC
gpg: keyserver receive failed: No name
➜  ~ gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys F9585DE6 C2FF8BBF 9BA28146 7B9E2481 D2A67EAC
gpg: /home/ethereum/.gnupg/trustdb.gpg: trustdb created
gpg: key 9417309ED2A67EAC: public key "Go Ethereum Windows Builder <geth-ci@ethereum.org>" imported
gpg: key 558915E17B9E2481: public key "Go Ethereum macOS Builder <geth-ci@ethereum.org>" imported
gpg: key A61A13569BA28146: public key "Go Ethereum Linux Builder <geth-ci@ethereum.org>" imported
gpg: key F29DEFAFC2FF8BBF: public key "Go Ethereum iOS Builder <geth-ci@ethereum.org>" imported
gpg: key 70AD154BF9585DE6: public key "Go Ethereum Android Builder <geth-ci@ethereum.org>" imported
gpg: Total number processed: 5
gpg:               imported: 5
```
