### ISSUE TITLE
summary of possible goroutine leaks

### ISSUE THREAD

**Issue by BurtonQin** [ethereum/go-ethereum#20663]
#### System information
Geth version: 1.9.10
OS & Version: Windows/Linux/OSX
Commit hash : 8045504abf64a865be4b1dbc780b796a9f5d11cc

#### Expected behaviour
Possible goroutine leaks in test.
1. p2p/server_test.go: `TestServerDial()`: `accepted`
https://github.com/ethereum/go-ethereum/blob/5f2002bbcc1ad21818d9b08badea84acac6d0481/p2p/server_test.go#L134-L142
Goroutine may leak because sending to `accept` is blocked on L141 when `select` on L154 selects timeout. Although `t.Error()` is often called in these certain cases, it won't stop the leaking, because "[Calling FailNow does not stop those other goroutines.](https://golang.org/pkg/testing/#T.FailNow)". The fix is to replace the unbuffered channel with a buffered channel (buffer size 1).
2. p2p/server_test.go: `TestServerInboundThrottle`: `connClosed`
https://github.com/ethereum/go-ethereum/blob/5f2002bbcc1ad21818d9b08badea84acac6d0481/p2p/server_test.go#L673-L685
Similar to 1.
3. rpc/client_test.go: `TestClientSubscribeClose`: `errc`
https://github.com/ethereum/go-ethereum/blob/5f2002bbcc1ad21818d9b08badea84acac6d0481/rpc/client_test.go#L300-L306
Similar to 1.
4. rpc/subscription_test.go: `TestSubscriptions`: `successes` and `notifications`
https://github.com/ethereum/go-ethereum/blob/5f2002bbcc1ad21818d9b08badea84acac6d0481/rpc/subscription_test.go#L60-L75
5. rpc/client_test.go: `TestClientHTTP`: `errc`
https://github.com/ethereum/go-ethereum/blob/5f2002bbcc1ad21818d9b08badea84acac6d0481/rpc/client_test.go#L414-L421
6. event/event_test.go: `BenchmarkChanSend`: `closed`
https://github.com/ethereum/go-ethereum/blob/5f2002bbcc1ad21818d9b08badea84acac6d0481/event/event_test.go#L205-L208
7. eth/handler_test.go: `TestBroadcastMalformedBlock`: `notify`
https://github.com/ethereum/go-ethereum/blob/5f2002bbcc1ad21818d9b08badea84acac6d0481/eth/handler_test.go#L680-L693
8. miner/worker_test.go: `testGenerateBlockAndImport`: `loopErr`
https://github.com/ethereum/go-ethereum/blob/5f2002bbcc1ad21818d9b08badea84acac6d0481/miner/worker_test.go#L218-L228
9. console/console.go: `Interactive`: `scheduler`
https://github.com/ethereum/go-ethereum/blob/5f2002bbcc1ad21818d9b08badea84acac6d0481/console/console.go#L346-L364
10. common/mclock/simclock_test.go: `TestSimulatedSleep`: `done`
https://github.com/ethereum/go-ethereum/blob/5f2002bbcc1ad21818d9b08badea84acac6d0481/common/mclock/simclock_test.go#L99-L103
11. common/prque/lazyqueue_test.go: `TestLazyQueue`: `stopCh`
https://github.com/ethereum/go-ethereum/blob/5f2002bbcc1ad21818d9b08badea84acac6d0481/common/prque/lazyqueue_test.go#L78-L86
I have not verified all of them. I will try to fix similar bugs in one patch.

#### Actual behaviour
No, I found it through static analysis.

#### Steps to reproduce the behaviour
No.

#### Backtrace
No.

**Comment by holiman** [comment]
This is awesome. I guess we'll keep this open until most of them are fixed. Status

- [x]  1. p2p/server_test.go: `TestServerDial()`: `accepted`
- [ ]  2. p2p/server_test.go: `TestServerInboundThrottle`: `connClosed`
- [x] 3. rpc/client_test.go: `TestClientSubscribeClose`: `errc`
- [ ] 4. rpc/subscription_test.go: `TestSubscriptions`: `successes` and `notifications`
- [ ] 5. rpc/client_test.go: `TestClientHTTP`: `errc`
- [ ] 6. event/event_test.go: `BenchmarkChanSend`: `closed`
- [x] 7. eth/handler_test.go: `TestBroadcastMalformedBlock`: `notify`
- [ ] 8. miner/worker_test.go: `testGenerateBlockAndImport`: `loopErr`
- [ ] 9. console/console.go: `Interactive`: `scheduler`
- [x] 10. common/mclock/simclock_test.go: `TestSimulatedSleep`: `done`
- [ ] 11. common/prque/lazyqueue_test.go: `TestLazyQueue`: `stopCh`
