### ISSUE TITLE
les: a potential circular wait of *lightFetcher.requestTrigger

### ISSUE THREAD

**Issue by lzhfromustc** [ethereum/go-ethereum#20675]
#### System information

Geth version: master branch
OS & Version: All OS
Commit hash : 37531b18847774a7f057496bc34f2a48053fa417

#### Actual behaviour
In short, I seek for your help to understand a channel's usage, because it may trigger a circular wait bug. I am sorry for not having input to trigger this bug.

`f.requestTrigger` is a channel made with 1 buffer. Could you help me take a look at the following code, and see whether `f.requestTrigger <- struct{}{}` can block (i.e. buffer is already full)? If it can, then it is likely to be buggy. If not, this Issue can be closed.

https://github.com/ethereum/go-ethereum/blob/37531b18847774a7f057496bc34f2a48053fa417/les/fetcher.go#L251-L253
https://github.com/ethereum/go-ethereum/blob/37531b18847774a7f057496bc34f2a48053fa417/les/fetcher.go#L353-L356

**Comment by lzhfromustc** [comment]
If it can block, a circular wait bug in the following pattern can be formed;

```Go
var m sync.Mutex

func main() {
	ch := make(chan bool, 1)
	go f1()
	go f2()
}

func f1() {
	for {
		m.Lock()
		ch <- true // LINE A
		m.Unlock()
	}
}

func f2() {
	for {
		<-ch
		m.Lock() // LINE B
		m.Unlock()
	}
}
```

When f1() is at LINE A, and ch's buffer is full, and f2() is at LINE B, both f1() and f2() will be blocked.

In les/fetcher.go, `f.requestTrigger` can circular wait with `f.lock.Lock()`

```Go
func newLightFetcher(h *clientHandler) *lightFetcher {
	f := &lightFetcher{
		...
		requestTrigger: make(chan struct{}, 1),
		...
	}

	...
	go f.syncLoop()
	return f
}

func (f *lightFetcher) syncLoop() {
	...
	for {
		select {
		case <-f.closeCh:
			...
		case <-f.requestTrigger:
			
			f.lock.Lock() // LINE B
			...
			f.lock.Unlock()

			if rq != nil {
				if _, ok := <-f.handler.backend.reqDist.queue(rq); ok {
					if syncing {
						...
					} else {
						go func() {
							...
							// keep starting new requests while possible
							f.requestTrigger <- struct{}{}
						}()
					}
				} else {
					f.requestTrigger <- struct{}{}
				}
			}
		case ...:
			...
		case p := <-f.syncDone:
			...
			f.requestTrigger <- struct{}{}
		}
	}
}

// announce processes a new announcement message received from a peer, adding new
// nodes to the peer's block tree and removing old nodes if necessary
func (f *lightFetcher) announce(...) {
	f.lock.Lock()
	defer f.lock.Unlock()
	...
	if !f.requestTriggered {
		...
		f.requestTrigger <- struct{}{} // LINE A
	}
}
```

**Comment by adamschmideg** [comment]
Our plan is to have a new fetcher merged soon #20692

**Comment by rjl493456442** [comment]
@lzhfromustc Hi, first this code is quite old and will be replaced very soon.

And regarding your question, you can check `f.requestTriggered`. It uses this flag to control `f.requestTrigger` channel.

For example, if we get a request from the queue and start to process it, the `f.requestTriggered` will be set and `f.requestTrigger` won't be triggered.

**Comment by lzhfromustc** [comment]
Thanks for explanation! I see with `f.requestTriggered`, it is impossible for `f.requestTrigger <- struct{}{}` in `announce()` to be blocked. I will close this issue
