### ISSUE TITLE
Could not connect to your Ethereum client.

### ISSUE THREAD

**Issue by RajSChawda** [ethereum/go-ethereum#20670]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````
![image](https://user-images.githubusercontent.com/60027125/74510776-7a761080-4f2a-11ea-93d5-00a903028c0b.png)

**Comment by ligi** [comment]
how did you start geth?
