### ISSUE TITLE
Allow lock and unlocking the account through the RPC

### ISSUE THREAD

**Issue by mitar** [ethereum/go-ethereum#2068]
Otherwise it is really hard to do rally anything remotely (what R in RPC stands for). Unless geth is unlocked for the whole session. Which again means you cannot run geth really remotely.

**Comment by sammy007** [comment]
I like it.

**Comment by karalabe** [comment]
`--rpcapi "db,eth,net,web3,personal"`

Please be aware of the consequences of opening up account methods to networked computers.

**Comment by mitar** [comment]
Personal API is not [documented here](https://github.com/ethereum/wiki/wiki/JSON-RPC)? How stable it is?

Also, it is lacking account locking, there is just unlocking.

**Comment by karalabe** [comment]
The `personal` module is part of the [go-ethereum management API](https://github.com/ethereum/go-ethereum/wiki/Go-ethereum-management-API's). It's not supposed to be used by average DApps, hence why it's not part of the standard spec.

**Comment by obscuren** [comment]
Not gonna happen.

**Comment by obscuren** [comment]
Another thing is that a DApp isn't supposed to care about locking or unlocking, it should "just happen". It's very domain specific knowledge and that knowledge does not belong with the DApp.

**Comment by mitar** [comment]
> Another thing is that a DApp isn't supposed to care about locking or unlocking, it should "just happen". 

Yes, by providing the API it can "just happen".

> EDIT: too insecure. And we're thinking about removing the key management from geth completely and move it to the client (e.g. mist).

In fact, I was looking into this because I wanted to make it more secure. So I was pretty surprised that you have to run your geth in unlocked mode for the wallet to work. I think this is pretty insecure. So what exactly are the plans for making this more secure? How would mist help here?

I am asking because I am working on a project making web apps more secure, where they can have secrets only trusted codebase can have access to. I wanted to look into how we could apply this to Ethereum wallets, as an example, but I see that there is no good story here at all, which we could then improve upon.

**Comment by obscuren** [comment]
> Yes, by providing the API it can "just happen".

No :-)

Remove accounts entirely from the node. Have the node serve public data **only**. Let whoever need accounting, implement accounting (e.g. mist).
