### ISSUE TITLE
escape/unescape is not defined on geth console

### ISSUE THREAD

**Issue by clomie** [ethereum/go-ethereum#20693]
Hi there,

Goja, the new JavaScript interpreter for v1.9.11, does not seem to support escape/unescape methods. 
This causes contract method calling failure on console.

#### System information

Geth version:
```
Geth
Version: 1.9.11-stable
Git Commit: 6a62fe399b68ab9e3625ef5e7900394f389adc3a
Git Commit Date: 20200218
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.8
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

#### Expected behaviour
```
> escape
function escape()
```

#### Actual behaviour
```
> escape
ReferenceError: escape is not defined
        at <eval>:1:1(0)
```

#### Steps to reproduce the behaviour
```
% docker run --rm -it ethereum/client-go:v1.9.11 console
> escape
ReferenceError: escape is not defined
        at <eval>:1:1(0)
```

**Comment by holiman** [comment]
Yeah, that's actually pretty bad. 
Previously:
```
> x="t'e=s\"ta?\n\r";y=escape(x);z=unescape(y);z==x&&y=="t%27e%3Ds%22ta%3F%0A%0D"
true
```
I went through the alphabet with tab completions, afaict `escape`/`unescape` are the only ones missing

**Comment by holiman** [comment]
Apparently known upstream: https://github.com/dop251/goja/issues/39

**Comment by holiman** [comment]
Also, apparently, if it weren't for backward-compatibility. `escape`/`unescape` would have been removed from the ecmascript standard: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape 

> Note that this function was used mostly for URL queries (the part of a URL following '?') not for escapes in ordinary String literals, which use the format "\xHH", where HH are two hexadecimal digits (with \xHH\xHH... for higher-plane Unicode characters). Escaped characters in String literals can be expanded by replacing the \x by % and then using the decodeURIComponent function.

For reference, in case anyone wants to implement this, here's the specification for how it should work: https://tc39.es/ecma262/#sec-escape-string

**Comment by holiman** [comment]
Another reference -- the Otto implementation: https://github.com/robertkrimen/otto/blob/master/builtin.go#L286 . That one is based on `string` objects, and Goja uses some sort of unicode/rune-based `Value` objects, so unfortunately it's not just a matter of a trivial copy-paste to get it working.

**Comment by holiman** [comment]
Hm, it was actually pretty simple to port over. I've done so now, but noticed that there's an error in the original Otto-implementation. According to the spec, these should not be escaped:
```
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@*_+-./
```
Google chrome:
```
x="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@*_+-./";x==escape(x)
true
```
However, Otto escapes `@` into `%40`.

**Comment by holiman** [comment]
Ok, let's see if this makes it upstream: https://github.com/dop251/goja/pull/123 .

**Comment by gballet** [comment]
Explanation here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape

> Warning: Although `unescape()` is not strictly deprecated (as in "removed from the Web standards"), it is defined in Annex B of the ECMA-262 standard, whose introduction states:
… All of the language features and behaviours specified in this annex have one or more undesirable characteristics and in the absence of legacy usage would be removed from this specification. …
… Programmers should not use or assume the existence of these features and behaviours when writing new ECMAScript code. …

Same thing for `escape`. This is most likely why it's not implemented in goja. Assuming the (likely) outcome that it will not be, we have to decide if we want to implement it on our side. Which brings the question: what use case do you need these methods for, @clomie ?

**Comment by clomie** [comment]
@gballet  Actually my use case was running contract methods on geth console.

I'm very new to ethereum, so I tried to start simple example which can be found on Solidity document, but I got an error.
```
> var contract = eth.contract(abi).new({from: eth.accounts[0], data: bin})
> contract.get()
ReferenceError: unescape is not defined
        at web3.js:8360:42(10)
        at web3.js:8398:35(11)
        at web3.js:8563:30(8)
        at web3.js:8589:54(8)
        at web3.js:1839:16(46)
        at web3.js:4070:16(6)
        at web3.js:4059:41(48)
        at web3.js:4130:33(32)
        at web3.js:4223:75(24)
        at <eval>:1:1(2)
```

As per my understanding, running contract method is performed in web3.js through the interpreter, and web3.js uses unescape method to run contract methods.
https://github.com/ethereum/web3.js/blob/c3e6c3867f7976e6c8670e2f2fd093286d0ef968/dist/web3.js#L8358

Removing escape/unescape dependency from web3.js might be an another solution.

**Comment by tomoki-togashi** [comment]
Apparently `escape`/`unescape` support has been added upstream: dop251/goja@d1232e6

**Comment by clomie** [comment]
Apparently `escape`/`unescape` support has been added upstream: dop251/goja@d1232e6
