### ISSUE TITLE
[PUPPETH] module explorer postgres do not auto initialize

### ISSUE THREAD

**Issue by blazejkrzak** [ethereum/go-ethereum#20706]
Hi there,
Puppeth do not deploy module explorer properly

#### System information

Geth version: `geth 1.9.9 stable`
OS & Version: Windows/Linux/OSX

#### Expected behaviour
Context: Puppeth
Via remote call I should be able to auto-deploy module explorer through steps:
4. Manage network components -> (n) deploy new network component 

#### Actual behaviour
Initialzation passes, but 
`502 Bad Gateway
nginx/1.17.6`
occurs on reverse proxy side.

#### Steps to reproduce the behaviour
Deploy new module explorer on private network

### Solution:
add env `POSTGRES_HOST_AUTH_METHOD=trust`
`POSTGRES_HOST_AUTH_METHOD=trust /usr/local/bin/docker-entrypoint.sh postgres &' >> explorer.sh && \` in `module_explorer.go`

### Backtrace
Postgres dies, because no password on admin is not preferred option. Either inject password or env `POSTGRES_HOST_AUTH_METHOD`

**Comment by blazejkrzak** [comment]
Next issue is that 
```
ADD genesis.json /genesis.json
RUN \
  echo 'geth --cache 512 init /genesis.json' > explorer.sh && \
  echo $'geth --networkid {{.NetworkID}} --syncmode "full" --gcmode "archive" --port {{.EthPort}} --bootnodes {{.Bootnodes}} --ethstats \'{{.Ethstats}}\' --cache=512 --rpc --rpcapi "net,web3,eth,shh,debug" --rpccorsdomain "*" --rpcvhosts "*" --ws --wsorigins "*" --exitwhensynced' >> explorer.sh && \
  echo $'exec geth --networkid {{.NetworkID}} --syncmode "full" --gcmode "archive" --port {{.EthPort}} --bootnodes {{.Bootnodes}} --ethstats \'{{.Ethstats}}\' --cache=512 --rpc --rpcapi "net,web3,eth,shh,debug" --rpccorsdomain "*" --rpcvhosts "*" --ws --wsorigins "*" &' >> explorer.sh && \
  echo 'POSTGRES_HOST_AUTH_METHOD=trust /usr/local/bin/docker-entrypoint.sh postgres &' >> explorer.sh && \
  echo 'sleep 5' >> explorer.sh && \
  echo 'mix do ecto.drop --force, ecto.create, ecto.migrate' >> explorer.sh && \
  echo 'mix phx.server' >> explorer.sh

ENTRYPOINT ["/bin/sh", "explorer.sh"]
```

`&` does not hide geth process and bash script never reaches line 
`echo /usr/local/bin/docker-entrypoint.sh postgres &' >> explorer.sh && \`

I suggest `screen` or `supervisor` or something else to hide process not just simply `&`

**Comment by karalabe** [comment]
The only way to really fix these issues is for someone to jump in and update blockscout and all the deps and check what needs to be done to make it work. Would be nice, but it's a bit of a low priority thing.

**Comment by sidhujag** [comment]
I actually took a look at this and fixed it... I am working to try to integrate this upstream so Geth team does not have to manage a fork of blockscout (its over 2000 commits behind). 

here is my docker for intuition: https://github.com/syscoin/blockscout/blob/master/Dockerfile

Syscoin has a fork of geth but we tweaked pupeth, some things that might be interesting are adding ability for those composer env variables to be parameterized by the user but for now we just hardcoded them but these allow customization of the explorer: https://github.com/sidhujag/go-ethereum/blob/nevm/cmd/puppeth/module_explorer.go#L32

**Comment by holiman** [comment]
`puppeth` is removed as of https://github.com/ethereum/go-ethereum/pull/26581. Closing puppeth-related tickets.
