### ISSUE TITLE
What is safe memory limit for geth

### ISSUE THREAD

**Issue by mesudip** [ethereum/go-ethereum#20709]
Hi there,
I recently ran into OOMKilled message with my docker geth instance.

#### System information

Geth version: `1.9.12-unstable-6ffee2af-20200221`
OS & Version: Linux 4.15.0-55-generic inside Docker image

#### Expected behavior
5.5G memory should be more than sufficient when the cache size is set to 1024

#### Actual behaviour
The container was killed with reason `OOMKilled` (Out Of Memory)

#### Steps to reproduce the behaviour
I was using 1.8 version that was working fine under the limit for about 4 months.
I upgraded to latest version and later It was killed.

#### Backtrace

````json
{
        "Id": "07915d2eabcd0c8c3f47f92d1b2a390fc3b7ae1369588653dc1d19cc31cf7601",
        "Created": "2020-02-23T18:36:18.356205081Z",
        "Path": "geth",
        "Args": [
            "--rpc",
            "--rpcapi",
            "db,eth,net,web3",
            "--rpcaddr",
            "0.0.0.0",
            "--rpcport",
            "8545",
            "--rpcvhosts",
            "*",
            "--ws",
            "--wsapi",
            "db,eth,net,web3",
            "--wsaddr",
            "0.0.0.0",
            "--wsport",
            "8546",
            "--wsorigins",
            "*",
            "--cache",
            "1024"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": true,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 137,
            "Error": "",
            "StartedAt": "2020-02-23T18:36:21.488901932Z",
            "FinishedAt": "2020-02-23T23:51:56.066285084Z"
        },
        "Image": "sha256:e4729995ebd6327c1e9eb3f245dbf6bc5898f75417b9bc0208a0a52f952e9e5b",
        "Isolation": "default",
        "CpuShares": 0,
        "Memory": 5905580032
}
````

**Comment by karalabe** [comment]
Indeed it should not use that much with a cache of 1GB. Are you making public RPC queries against this node? If you open it up for the entire world, you might end up with bots running queries against it. So you have any logs from the node? Memory usage charts perhaps (monitoring?)

**Comment by mesudip** [comment]
This time, the port exposed was only `30303`. Yet it was `OOMKilled` after 8 days. Also, for a node already synced, It's doing a lot of disk/network I/O.
```
CONTAINER ID        NAME                                           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
886f269002ec        ethereum_mainnet.1.tkbfwhrl52xp8rfnxbzp5f9ng   134.43%             4.406GiB / 5.5GiB   80.11%              35.4GB / 53.4GB     671GB / 158GB       73
# docker ps -a | grep geth
886f269002ec        ethereum/client-go:latest                 "geth --rpc --rpcapi…"   45 hours ago   Up 45 hours                    ethereum_mainnet.1.tkbfwhrl52xp8rfnxbzp5f9ng
af0ac4ce450a        ethereum/client-go:latest                 "geth --rpc --rpcapi…"   10 days ago    Exited (137) 45 hours ago      ethereum_mainnet.1.vg6n2z345axoxkj8y65642pcq

**Comment by holiman** [comment]
This ticket is pretty old. Does this still persist? If it does, do you have any crash-dump with the full stack trace available? Those will help investigate issues with e.g. blocked/locked go-routines piling up
