### ISSUE TITLE
Web-socket connection is not working after upgrade from 1.9.10 to 1.9.11

### ISSUE THREAD

**Issue by begetan** [ethereum/go-ethereum#20701]
#### System information

Geth version: **Geth/v1.9.11-stable-6a62fe39/linux-amd64/go1.13.8**

#### Expected behaviour
Connection to websocket with the curl http protocol should return HTTP 101 status 

#### Actual behaviour
Connection to websocket port returns error 400 

```bash
curl --include --no-buffer \
    --header "Connection: close" \
    --header "Upgrade: websocket" \
    --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
    --header "Sec-WebSocket-Version: 13" \
    http://localhost:8546

HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Sec-Websocket-Version: 13
X-Content-Type-Options: nosniff
Date: Thu, 20 Feb 2020 10:29:55 GMT
Content-Length: 12
Connection: close
```

#### Steps to reproduce the behaviour
I run geth service with the following comand:

```bash
geth --nousb --rinkeby --cache=512 --ws --wsorigins '*' --wsaddr "0.0.0.0" --rpc -rpcaddr "0.0.0.0" --rpcvhosts=* --rpccorsdomain '*' --rpcapi eth,net,web3,debug
```
Also tried to add  option  `--wsapi eth,net,web3,debug` without changes.

JSON-RPC on port 8545 works fine

Could you please provide an update if this release contains an incompatible configuration changes.

**Comment by karalabe** [comment]
Are you sure your request is the same? The `curl` command indeed fails for me too, but it fails for 1.9.11, 1.9.10 and 1.9.9 too (haven't tried lower).

**Comment by karalabe** [comment]
Btw, if I replace your `"Connection: close"` header with `"Connection: Upgrade"`, it works

**Comment by begetan** [comment]
@karalabe yes, you i right.

Initially I have configured AWS Application Load Balancer for the test.

When using properly configured AWS ALB you may test connection with the `--header "Connection: Close"`and `--header "Connection: Upgrade"`  parameters both.

After deploy of new version of Geth with new AWS balancer I forgot to disable HTTP/2 support. Webs-socket protocol is incompatible with HTTP/2, so I got Error 400 for any kind of requests.

The only issue here is why Geth not properly handle  `--header "Connection: Close"`  according to standard. It shouldn't affect real operation.

**Comment by de1acr0ix** [comment]
> #### System information
> 
> Geth version: **Geth/v1.9.11-stable-6a62fe39/linux-amd64/go1.13.8**
> #### Expected behaviour
> 
> Connection to websocket with the curl http protocol should return HTTP 101 status
> #### Actual behaviour
> 
> Connection to websocket port returns error 400
> 
> ```shell
> curl --include --no-buffer \
>     --header "Connection: close" \
>     --header "Upgrade: websocket" \
>     --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
>     --header "Sec-WebSocket-Version: 13" \
>     http://localhost:8546
> 
> HTTP/1.1 400 Bad Request
> Content-Type: text/plain; charset=utf-8
> Sec-Websocket-Version: 13
> X-Content-Type-Options: nosniff
> Date: Thu, 20 Feb 2020 10:29:55 GMT
> Content-Length: 12
> Connection: close
> ```
> 
> #### Steps to reproduce the behaviour
> 
> I run geth service with the following comand:
> 
> ```shell
> geth --nousb --rinkeby --cache=512 --ws --wsorigins '*' --wsaddr "0.0.0.0" --rpc -rpcaddr "0.0.0.0" --rpcvhosts=* --rpccorsdomain '*' --rpcapi eth,net,web3,debug
> ```
> 
> Also tried to add option `--wsapi eth,net,web3,debug` without changes.
> 
> JSON-RPC on port 8545 works fine
> 
> Could you please provide an update if this release contains an incompatible configuration changes.

@begetan I have tested that Geth can properly handle the connection with both `--header "Connection: Close"` and `--header "Connection: Upgrade"`. But your command line does not have `--header "Connection: Upgrade"`.

**Comment by begetan** [comment]
@de1acr0ix could you please provide exact command for test websock connection with Geth? 

I used for test this gist: https://gist.github.com/htp/fbce19069187ec1cc486b594104f01d0
Later changed to  "Connection: Close" as was recommended in some discussion.

**Comment by de1acr0ix** [comment]
@begetan see my command line below. You need to have at least one `Connection: upgrade` and one `Upgrade: websocket` there to make WebSocket connection work. Apart from that adding extra header of `Connection: close` won't harm the connection.

```
~ ❯❯❯ curl --include --no-buffer \
    --header "Connection: close" --header "Connection: upgrade" \
    --header "Upgrade: websocket" \
    --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
    --header "Sec-WebSocket-Version: 13" \
    http://localhost:8546
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: qGEgH3En71di5rrssAZTmtRTyFk=
```

**Comment by begetan** [comment]
@de1acr0ix 

This header `--header "Connection: close"` actually doesn't change anything.  Connection is staying open with or without it.

Anyway this behavior makes so litlle impact, so I would closed this issue.

**Comment by begetan** [comment]
As for recap:
 `--header "Connection: close"` is not working actually with the Geth WebSocket port, but it causes no real impact for the operations
