### ISSUE TITLE
pi-hole shows over 10,000 hits for "all.mainnet.ethdisco.net". 

### ISSUE THREAD

**Issue by Zaphod101010** [ethereum/go-ethereum#20713]
Is this expected behavior?  Or is this a bug?

They are all TXT query type.

#### System information
Geth version: 1.9.11
OS & Version: MacOS

#### Expected behavior
Fewer dns queries

#### Actual behavior
Over 10,000 dns queries in the last 24 hours.

**Comment by karalabe** [comment]
In 1.9.11 we've introduces a DNS discovery. A crawler is constantly mapping out the Ethereum network and is publishing its results in a Merkle tree on top of DNS (via TXT records). These trees are published on the `ethdisco.net` domain (mainnet, ropsten, rinkeby and goerli). Geth slowly downloads this tree as a secondary discovery protocol beside the DHT (or for people who don't have UDP connectivity). Although Geth does access a lot of "subdomains", these are immutable so the DNS infrastructure should be able to very very aggressively cache it and not have to do actual network lookups.

**Comment by karalabe** [comment]
Here's the protocol btw https://eips.ethereum.org/EIPS/eip-1459

**Comment by Zaphod101010** [comment]
Does anyone have any idea for a way to have geth not use the pi-hole for it's dns?

pi-hole logs are over 130MB and growing.  It's making a dozen requests per second.

The excessive logging of geth dns requests makes the pi-hole query log kind of unusable.

**Comment by holiman** [comment]
This is an issue with pi-hole, perhaps suggest to them a feature to whitelist/ignore certain domains? Nothing we can do here on our side.

**Comment by MariusVanDerWijden** [comment]
@Zaphod101010 Maybe you can take a look at this: https://discourse.pi-hole.net/t/option-to-ignore-hosts-from-appearing-in-the-query-log/6319/21

**Comment by cleanunicorn** [comment]
> Does anyone have any idea for a way to have geth not use the pi-hole for it's dns?
> 
> pi-hole logs are over 130MB and growing. It's making a dozen requests per second.
> 
> The excessive logging of geth dns requests makes the pi-hole query log kind of unusable.

DNS is set at machine level. That means if you are running geth on you own machine, it will be hard to change the DNS without any virtualization.

However, if you're running it in Docker, you can specify a DNS server with `--dns`.
