### ISSUE TITLE
Provide lockAccount account management API command

### ISSUE THREAD

**Issue by mitar** [ethereum/go-ethereum#2071]
Currently, [management API](https://github.com/ethereum/go-ethereum/wiki/Go-ethereum-management-API's) provides only `unlockAccount` API. It would be great to provide also the `lockAccount` so that you can lock the instance after you do not need it unlocked anymore.

**Comment by obscuren** [comment]
![NEIN!!!](https://media.giphy.com/media/X3KNwlvpahFBK/giphy.gif)

For a more nuanced answer see https://github.com/ethereum/go-ethereum/issues/2068#issuecomment-164428655
