### ISSUE TITLE
Fail gracefully when trying to import blocks that were exported with a different consensus engine

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20711]
```
> geth --datadir ethash init ethash.json
> geth --datadir ethash export blocks
> geth --datadir clique init clique.json
> geth --datadir clique import blocks
...
Import error      err="invalid block 32: vote nonce not 0x00..0 or 0xff..f"
...
`
``

**Comment by karalabe** [comment]
Well, it kind of says the block is invalid :) Not sure what more you would like to see.

**Comment by adamschmideg** [comment]
I can't tell if the file was corrupted. The "vote nonce" part is confusing. I'd see something like "the blocks were exported by a different consensus engine than what you're using now"

**Comment by karalabe** [comment]
Well, there's no way to tell really. The headers look the same, just the field contents mean different things. And one consensus engine doesn't know what is valid for another, the only thing it knows is that it's not valid for itself and why.

**Comment by karalabe** [comment]
E.g. If I try to open a movie file in a word processor, it won't tell me that "no, sorry, that's a video file", it can only tell me that it is not a valid word file. Kind of what the error above tells you, that it's not a valid block.

**Comment by adamschmideg** [comment]
I assume the file is already parsed  when this error is raised. So the error message could say "It's a valid blocks file but not an <xxx> blocks file" where xxx is the current consensus engine.

**Comment by adamschmideg** [comment]
Re: word processor. If you open a spread sheet in a word processor of the same product family, I'd expect it to say, "hey, this looks like a spread sheet, not a document". It can be ignorant about other products, of course.
