### ISSUE TITLE
Fast sync always 6000 blocks behind for more than 1 day

### ISSUE THREAD

**Issue by rlinxy** [ethereum/go-ethereum#20715]
I just want to sync a new node. So I copied the block data from a synced node to another vps and started syncing yesterday. However the syncing process seems extreamely slow, around 2 or 3 blocks per minute, so it should never catch up :(
I have tried several different version of geth including the latest 1.9.11, but no luck, the problem remains the same. Now I am using 1.9.10.

The sync out put:

> INFO [02-25|12:24:51.644] Imported new chain segment               blocks=1  txs=216 mgas=9.893  elapsed=18.546s   mgasps=0.533 number=9543256 hash=8ec305…a131b6 age=1d2h39m dirty=118.85MiB
INFO [02-25|12:25:18.167] Imported new chain segment               blocks=1  txs=159 mgas=9.900  elapsed=26.522s   mgasps=0.373 number=9543257 hash=09547e…310b22 age=1d2h39m dirty=119.11MiB
INFO [02-25|12:25:25.576] Deep froze chain segment                 blocks=3  elapsed=216.437ms number=9453256 hash=64994f…2b428d
INFO [02-25|12:25:42.579] Imported new chain segment               blocks=1  txs=186 mgas=9.910  elapsed=24.412s   mgasps=0.406 number=9543258 hash=e9f5e6…fb6cff age=1d2h39m dirty=119.73MiB
INFO [02-25|12:26:04.024] Imported new chain segment               blocks=2  txs=246 mgas=10.603 elapsed=21.444s   mgasps=0.494 number=9543260 hash=37ab56…4fd2cf age=1d2h38m dirty=120.12MiB
INFO [02-25|12:26:17.602] Imported new chain segment               blocks=1  txs=130 mgas=6.804  elapsed=13.577s   mgasps=0.501 number=9543261 hash=72e99c…d95585 age=1d2h38m dirty=120.20MiB
INFO [02-25|12:26:27.298] Deep froze chain segment                 blocks=4  elapsed=1.718s    number=9453260 hash=e74ab1…e76967
INFO [02-25|12:26:39.397] Imported new chain segment               blocks=1  txs=151 mgas=9.890  elapsed=21.795s   mgasps=0.454 number=9543262 hash=6414ed…e21112 age=1d2h38m dirty=121.13MiB
WARN [02-25|12:26:53.931] Checkpoint challenge timed out, dropping id=0f7bc70eb4d4650d conn=inbound             addr=209.181.88.62:53106  type=Geth/v1.9.9-stable-01744997/linux-amd64/go1.13.5
INFO [02-25|12:26:57.701] Imported new chain segment               blocks=1  txs=137 mgas=9.872  elapsed=18.303s   mgasps=0.539 number=9543263 hash=ff2b83…eb0611 age=1d2h38m dirty=121.76MiB
INFO [02-25|12:27:11.955] Imported new chain segment               blocks=1  txs=101 mgas=9.890  elapsed=14.254s   mgasps=0.694 number=9543264 hash=cf2aed…af21a3 age=1d2h38m dirty=122.19MiB
INFO [02-25|12:27:26.477] Imported new chain segment               blocks=1  txs=54  mgas=9.878  elapsed=14.522s   mgasps=0.680 number=9543265 hash=4f233a…f722ff age=1d2h39m dirty=122.43MiB
INFO [02-25|12:27:27.422] Deep froze chain segment                 blocks=4  elapsed=116.705ms number=9453264 hash=dc81d8…c19543
INFO [02-25|12:27:43.285] Imported new chain segment               blocks=1  txs=124 mgas=9.900  elapsed=16.807s   mgasps=0.589 number=9543266 hash=470908…05f26f age=1d2h38m dirty=122.92MiB
INFO [02-25|12:28:07.890] Imported new chain segment               blocks=2  txs=343 mgas=18.076 elapsed=24.605s   mgasps=0.735 number=9543268 hash=308ae0…9fcd9f age=1d2h39m dirty=124.95MiB
WARN [02-25|12:28:14.823] Checkpoint challenge timed out, dropping id=db7687442af0ca80 conn=inbound             addr=47.90.189.150:53588  type=Geth/v1.9.9-stable-01744997/windows-amd64/go1.13.4
INFO [02-25|12:28:27.577] Deep froze chain segment                 blocks=4  elapsed=153.581ms number=9453268 hash=a2b2c5…ff67d6
INFO [02-25|12:28:46.865] Imported new chain segment               blocks=2  txs=286 mgas=19.060 elapsed=38.975s   mgasps=0.489 number=9543270 hash=cbcc94…677f68 age=1d2h38m dirty=126.49MiB
INFO [02-25|12:29:10.644] Imported new chain segment               blocks=1  txs=132 mgas=9.912  elapsed=23.779s   mgasps=0.417 number=9543271 hash=8d45d9…a25ef2 age=1d2h38m dirty=126.73MiB
INFO [02-25|12:29:27.746] Deep froze chain segment                 blocks=3  elapsed=166.729ms number=9453271 hash=f76b01…929b38
INFO [02-25|12:29:32.522] Imported new chain segment               blocks=2  txs=101 mgas=10.070 elapsed=21.877s   mgasps=0.460 number=9543273 hash=d4f158…c40c7b age=1d2h38m dirty=126.17MiB
INFO [02-25|12:29:55.362] Imported new chain segment               blocks=1  txs=193 mgas=9.901  elapsed=22.840s   mgasps=0.433 number=9543274 hash=d9010e…18ff73 age=1d2h38m dirty=127.22MiB
INFO [02-25|12:30:17.690] Imported new chain segment               blocks=1  txs=116 mgas=9.909  elapsed=22.327s   mgasps=0.444 number=9543275 hash=4e26eb…86a731 age=1d2h38m dirty=126.98MiB
INFO [02-25|12:30:27.816] Deep froze chain segment                 blocks=4  elapsed=69.137ms  number=9453275 hash=f5cae8…9849bd
INFO [02-25|12:30:38.978] Imported new chain segment               blocks=2  txs=273 mgas=13.716 elapsed=21.287s   mgasps=0.644 number=9543277 hash=35d386…82f9d6 age=1d2h39m dirty=127.90MiB
INFO [02-25|12:31:04.556] Imported new chain segment               blocks=1  txs=90  mgas=9.931  elapsed=25.577s   mgasps=0.388 number=9543278 hash=006a78…879a3e age=1d2h39m dirty=127.79MiB
INFO [02-25|12:31:14.454] Imported new chain segment               blocks=2  txs=39  mgas=6.399  elapsed=9.898s    mgasps=0.647 number=9543280 hash=fbc96d…3a9b0e age=1d2h39m dirty=127.04MiB
INFO [02-25|12:31:27.976] Deep froze chain segment                 blocks=5  elapsed=156.439ms number=9453280 hash=94c3a4…82024b
INFO [02-25|12:31:32.252] Imported new chain segment               blocks=2  txs=190 mgas=7.958  elapsed=17.797s   mgasps=0.447 number=9543282 hash=62372c…77ce17 age=1d2h39m dirty=127.14MiB
INFO [02-25|12:31:54.780] Imported new chain segment               blocks=2  txs=202 mgas=10.414 elapsed=22.528s   mgasps=0.462 number=9543284 hash=1fa6c6…6ffba1 age=1d2h39m dirty=127.86MiB
INFO [02-25|12:32:03.733] Imported new chain segment               blocks=2  txs=81  mgas=8.882  elapsed=8.952s    mgasps=0.992 number=9543286 hash=1116ed…3ff12c age=1d2h39m dirty=126.91MiB
INFO [02-25|12:32:25.633] Imported new chain segment               blocks=2  txs=20  mgas=1.714  elapsed=21.900s   mgasps=0.078 number=9543288 hash=eb7552…189804 age=1d2h39m dirty=126.46MiB
INFO [02-25|12:32:28.130] Deep froze chain segment                 blocks=8  elapsed=150.644ms number=9453288 hash=9ab8b4…ff2ff9
INFO [02-25|12:32:39.687] Imported new chain segment               blocks=2  txs=232 mgas=16.024 elapsed=14.053s   mgasps=1.140 number=9543290 hash=0cb0db…fde8cb age=1d2h39m dirty=127.53MiB
INFO [02-25|12:32:54.845] Imported new chain segment               blocks=2  txs=109 mgas=7.194  elapsed=15.158s   mgasps=0.475 number=9543292 hash=d7018f…380104 age=1d2h39m dirty=127.42MiB
INFO [02-25|12:33:05.524] Imported new chain segment               blocks=1  txs=107 mgas=4.266  elapsed=10.678s   mgasps=0.400 number=9543293 hash=eb8964…6c819e age=1d2h39m dirty=127.09MiB
INFO [02-25|12:33:13.818] Imported new chain segment               blocks=1  txs=66  mgas=4.035  elapsed=8.294s    mgasps=0.487 number=9543294 hash=10479f…9fa8e7 age=1d2h39m dirty=126.66MiB
INFO [02-25|12:33:28.263] Deep froze chain segment                 blocks=6  elapsed=131.437ms number=9453294 hash=8dd465…24d67d
INFO [02-25|12:33:38.387] Imported new chain segment               blocks=2  txs=206 mgas=10.996 elapsed=24.568s   mgasps=0.448 number=9543296 hash=7092f7…9aebac age=1d2h39m dirty=127.12MiB
INFO [02-25|12:34:04.277] Imported new chain segment               blocks=1  txs=159 mgas=8.050  elapsed=25.889s   mgasps=0.311 number=9543297 hash=e050ab…1ec58a age=1d2h39m dirty=127.02MiB

>

**Comment by karalabe** [comment]
Are you using an SSD? Geth does a **lot** of disk IO during syncing. Also when you start Geth, the caches are cold, so blocks are slower. Btw, how much memory allowance did you give it?

**Comment by rlinxy** [comment]
I set --cache=512. I think it's not the issue. Because I am currently running several ETH nodes for our mining pool, most of them are working on the vps with same system specification(CPU, mem etc...). Just this one has such syncing problem, now it's around 1 day 5 hours behind, never catch up.

The difference is I copied the block data from another synced node. I guess I may have to run a completely 'new' start, no short cut :(

> INFO [02-25|20:50:21.171] Imported new chain segment               blocks=1 txs=98  mgas=9.958  elapsed=19.420s   mgasps=0.513 number=9544910 hash=16ce44…d4f18a age=1d4h58m dirty=64.48MiB
INFO [02-25|20:50:37.467] Commit new mining work                   number=9544911 sealhash=180f66…898d64 uncles=0 txs=269 gas=9968855 fees=0.3687443786  elapsed=171.405ms
INFO [02-25|20:50:39.200] Imported new chain segment               blocks=1 txs=40  mgas=6.750  elapsed=18.029s   mgasps=0.374 number=9544911 hash=46fe49…066134 age=1d4h58m dirty=65.08MiB
INFO [02-25|20:50:52.659] Imported new chain segment               blocks=1 txs=210 mgas=9.955  elapsed=13.458s   mgasps=0.740 number=9544912 hash=c3144b…9e6e99 age=1d4h58m dirty=66.57MiB
INFO [02-25|20:50:57.660] Commit new mining work                   number=9544913 sealhash=625ab0…1b54bf uncles=0 txs=271 gas=9963794 fees=0.3694941686  elapsed=360.378ms
INFO [02-25|20:51:01.945] Imported new chain segment               blocks=1 txs=96  mgas=9.897  elapsed=9.286s    mgasps=1.066 number=9544913 hash=41f6ec…cb7b6b age=1d4h58m dirty=67.29MiB
INFO [02-25|20:51:17.584] Commit new mining work                   number=9544914 sealhash=5e104f…e52d91 uncles=0 txs=273 gas=9975826 fees=0.3711552298  elapsed=280.625ms
INFO [02-25|20:51:27.531] Imported new chain segment               blocks=1 txs=225 mgas=9.954  elapsed=25.585s   mgasps=0.389 number=9544914 hash=61b5a5…9f7eae age=1d4h59m dirty=68.74MiB
INFO [02-25|20:51:37.368] Commit new mining work                   number=9544915 sealhash=36bebd…46c77d uncles=0 txs=271 gas=9983979 fees=0.3713333836  elapsed=60.464ms
INFO [02-25|20:51:49.978] Imported new chain segment               blocks=1 txs=147 mgas=9.920  elapsed=22.447s   mgasps=0.442 number=9544915 hash=303ef6…cd06ac age=1d4h59m dirty=70.01MiB
INFO [02-25|20:51:57.670] Commit new mining work                   number=9544918 sealhash=a75d20…47b965 uncles=0 txs=272 gas=9971918 fees=0.3714509036  elapsed=359.001ms
INFO [02-25|20:52:17.469] Commit new mining work                   number=9544918 sealhash=6a45f7…5eb27b uncles=0 txs=276 gas=9972625 fees=0.3717594498  elapsed=153.291ms
INFO [02-25|20:52:21.176] Imported new chain segment               blocks=3 txs=178 mgas=12.624 elapsed=31.197s   mgasps=0.405 number=9544918 hash=e9fa89…1e0962 age=1d4h59m dirty=71.53MiB
INFO [02-25|20:52:35.744] Imported new chain segment               blocks=1 txs=178 mgas=7.557  elapsed=14.567s   mgasps=0.519 number=9544919 hash=f2842f…7477e1 age=1d4h59m dirty=72.71MiB
WARN [02-25|20:52:49.547] Checkpoint challenge timed out, dropping id=6d5dfe0d25f8f5a9 conn=inbound    addr=54.200.225.63:25774   type=Geth/v1.8.23-stable-c9427004/linux-amd64/go1.10.4
INFO [02-25|20:52:53.253] Imported new chain segment               blocks=1 txs=145 mgas=6.672  elapsed=17.509s   mgasps=0.381 number=9544920 hash=65f0a2…09406c age=1d4h59m dirty=73.76MiB
INFO [02-25|20:53:00.476] Commit new mining work                   number=9544920 sealhash=8d68d3…587fcd uncles=0 txs=271 gas=9953971 fees=0.3718510836  elapsed=23.156s

**Comment by karalabe** [comment]
Are you really sure the others are running with so little cache allowances? I'm pretty sure Geth cannot handle mainnet with only 512MB RAM. The defaults for mainnet at 4GB.

**Comment by karalabe** [comment]
Also you seem to already be running the miner all while the node is still syncing, which is quite a significant extra load. You should first make sure the node is synced before attaching miners to it.

**Comment by rlinxy** [comment]
The ram is 4GB, and now there is around 2 GB free. What I mean is I am using the parameter  '--cache=512', the same as other nodes of mine currently running. 
I not sure why the mining started, the mining process should abort automatically until the synced.
Anyway, I removed the '--mine' from parameter 1 hour ago, and started syncing again, but nothing improved

> INFO [02-25|22:11:59.149] Deep froze chain segment                 blocks=4 elapsed=117.552ms number=9455025 hash=1eb768…0b806d
INFO [02-25|22:12:05.216] Imported new chain segment               blocks=2 txs=143 mgas=8.478  elapsed=17.760s   mgasps=0.477  number=9545027 hash=8b88d8…5c4126 age=1d5h54m dirty=134.42MiB
INFO [02-25|22:12:38.599] Imported new chain segment               blocks=2 txs=250 mgas=12.498 elapsed=33.382s   mgasps=0.374  number=9545029 hash=5d9e84…b158cf age=1d5h54m dirty=135.20MiB
INFO [02-25|22:12:51.602] Imported new chain segment               blocks=1 txs=217 mgas=9.947  elapsed=13.002s   mgasps=0.765  number=9545030 hash=484cf1…1775ba age=1d5h54m dirty=136.06MiB
INFO [02-25|22:12:59.223] Deep froze chain segment                 blocks=4 elapsed=72.114ms  number=9455029 hash=a0e11c…7e0f1b
INFO [02-25|22:13:10.361] Imported new chain segment               blocks=1 txs=120 mgas=9.943  elapsed=18.758s   mgasps=0.530  number=9545031 hash=3daa01…5cce47 age=1d5h54m dirty=136.89MiB
INFO [02-25|22:13:37.540] Imported new chain segment               blocks=1 txs=209 mgas=9.942  elapsed=27.179s   mgasps=0.366  number=9545032 hash=57051b…30bdd8 age=1d5h54m dirty=137.91MiB
INFO [02-25|22:13:57.028] Imported new chain segment               blocks=1 txs=238 mgas=9.969  elapsed=19.488s   mgasps=0.512  number=9545033 hash=f3610a…2c2288 age=1d5h54m dirty=138.51MiB
INFO [02-25|22:13:59.288] Deep froze chain segment                 blocks=3 elapsed=60.550ms  number=9455032 hash=17d52b…49f0c8
INFO [02-25|22:14:08.265] Imported new chain segment               blocks=1 txs=66  mgas=3.579  elapsed=11.236s   mgasps=0.319  number=9545034 hash=d1d6ee…1759ca age=1d5h54m dirty=138.83MiB
INFO [02-25|22:14:36.745] Imported new chain segment               blocks=2 txs=203 mgas=9.989  elapsed=28.480s   mgasps=0.351  number=9545036 hash=a0a702…7ef5db age=1d5h55m dirty=139.10MiB
INFO [02-25|22:14:59.344] Deep froze chain segment                 blocks=3 elapsed=52.188ms  number=9455035 hash=5a6718…9f2a62
INFO [02-25|22:15:26.682] Imported new chain segment               blocks=1 txs=163 mgas=9.981  elapsed=49.936s   mgasps=0.200  number=9545037 hash=c4d127…104679 age=1d5h55m dirty=140.11MiB
INFO [02-25|22:15:41.697] Imported new chain segment               blocks=1 txs=164 mgas=9.998  elapsed=15.014s   mgasps=0.666  number=9545038 hash=8e2473…3a6b42 age=1d5h55m dirty=141.14MiB
INFO [02-25|22:15:55.178] Imported new chain segment               blocks=1 txs=161 mgas=7.231  elapsed=13.481s   mgasps=0.536  number=9545039 hash=6a175a…1c0a8d age=1d5h55m dirty=141.61MiB
INFO [02-25|22:16:00.142] Deep froze chain segment                 blocks=3 elapsed=794.811ms number=9455038 hash=34dbac…c7cbf3

**Comment by rlinxy** [comment]
Well, I gave up. Just delete all the block data and running a completely 'new' sync now. Seems so far so good

**Comment by begetan** [comment]
@rlinxy Have you finished your sync process?

**Comment by rlinxy** [comment]
Yes, seems it was a bug with previous version.
