### ISSUE TITLE
eth TestCheckpointChallenge fails frequently in Travis builds

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20726]
This is how it [fails here](https://github.com/ethereum/go-ethereum/blob/master/eth/handler_test.go#L542)
```
TestCheckpointChallenge/sync_fast_checkpoint_true_timeout_true_empty_false_match_true
    handler_test.go:542: peer count mismatch: have 1, want 0
```

**Comment by rjl493456442** [comment]
After running stress `756 runs so far, 0 failures` no failure actually occurs. 

Though we can blindly increase the time sleep duration to reduce the possibility of failure

**Comment by adamschmideg** [comment]
It hasn't shown up in the last 2 weeks
