### ISSUE TITLE
eth TestSendTransactions63 fails frequently on Travis

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20725]
The error message is
```
protocol_test.go:343: Peer xxx pipe: got tx more than once: xxx
```

**Comment by karalabe** [comment]
AFAIK this was fixed in the last release. Did you see it happen since the tx fetcher PR was merged?

**Comment by adamschmideg** [comment]
I'm checking its timeline

**Comment by adamschmideg** [comment]
Do you mean  https://github.com/ethereum/go-ethereum/pull/20712 ? [its build](https://travis-ci.org/ethereum/go-ethereum/builds/654398055) was cancelled.

**Comment by karalabe** [comment]
https://github.com/ethereum/go-ethereum/pull/20234

**Comment by adamschmideg** [comment]
Cool, that issue hasn't come back in the builds since.
