### ISSUE TITLE
bad block in 1.9.11

### ISSUE THREAD

**Issue by sirnicolas21** [ethereum/go-ethereum#20739]
```
Welcome to the Geth JavaScript console!

instance: Geth/v1.9.11-stable-6a62fe39/linux-arm/go1.11.6
coinbase: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
at block: 9597703 (Tue Mar 03 2020 12:44:01 GMT+0200 (EET))
 datadir: /sharedfolders/ssd/CryptoCoins/eth/chain
 modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> INFO [03-03|12:54:56.173] Block synchronisation started
INFO [03-03|12:54:56.227] Looking for peers                        peercount=2 tried=40 static=0
INFO [03-03|12:54:56.839] New local node record                    seq=865 id=7b08396837ccc2d1 ip=185.235.240.215 udp=30303 tcp=30303
ERROR[03-03|12:55:01.627]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Engine: ethash}

Number: 9597704
Hash: 0xae2bee3bd56112cfd10606b66f7af2578cc0f172d82fd867626fed39955d946b


Error: nonce too high
##############################

```
it does that all the time without progressing

**Comment by ligi** [comment]
what are the parameters/genesis you started geth with?

**Comment by sirnicolas21** [comment]
geth --datadir /sharedfolders/ssd/CryptoCoins/eth/chain/ --cache 256 console

nothing fancy, just datadir and cache (its in a raspberry 4)
i didn't touch the genesis, its on main net and transactions where broadcasting normally on it

**Comment by sirnicolas21** [comment]
```
> eth.getBlock(9597703)
{
  difficulty: 2235728764246161,
  extraData: "0x737061726b706f6f6c2d6574682d636e2d687a34",
  gasLimit: 10000000,
  gasUsed: 9985847,
  hash: "0x43203cefb7593623b33080cac68877cce2200873ee500bd13d413a1b73b9f7ac",
  logsBloom: "0x04468e0204862e192a05a266101c1a840484018e060e08fd8128086112180000040249a77810a84099c60354528e15093a82049e8b009c0101808092103a06a0000c0dcc10720009ee2686cc02349041a503401e0a2521440a524164e64860b91a00092e3ae4400950008a0c0080082206ec5220040808901020053a6401128800c0c9198221280240011120a00003000009ad45430004424a0060c72650d0ac0614b0f501d06091283053c1619110852000c7c38201582525063a1018c413752210600208403455051010200328e00c3c0052a871470664031310cc50502442a11224b01588006061a80449023182240804448081ea2852989600f96980405b",
  miner: "0x5a0b54d5dc17e0aadc383d2db43b0a0d3e029c4c",
  mixHash: "0x3febf460a6e504868df9e88afae923dda7ed7349359c2efddd6f4122ac71b315",
  nonce: "0x61fb6af806fdd758",
  number: 9597703,
  parentHash: "0x1bf8e898c95a7ace2674cccdbccce56acc879222198c0e360a8a939d6a4c411c",
  receiptsRoot: "0xf1ba38ea6ffbb39d89f2da6e71ab84748da285f56220cdee7d773303299fe045",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 23443,
```

my current  block is ok, its still some hours and still stuck there

**Comment by karalabe** [comment]
First up, we have no idea :P 

We did notice a few things:

 * Your Go compiler is pretty old (1.11 vs. 1.14 was just released). You might want to rebuild with Go 1.14. Go did a lot of major reworks around ARM CPUs, I know of some nasty runtime bugs fixed too, which may or may not be included in 1.11 (it's not supported any more).
 * AFAIK the RPI4 is a 64bit arm architecture, but you're running a 32 bit build. IT might make sense to build a 64bit Geth binary.
 * Using 256MB cache is pretty low, amazed that it could keep up with the network. What SSD are you using? More cache allowance generally results in better pruning (i.e. less junk on disk over the long term).

Did your Geth crash at any time? Alternatively, did you ever hard-stopped it (it can take some time for it to gracefully shut down, which if it doesn't do, some things might go missing (generally auto-corrects)). Just asking to cover possibilities.

All in all we're semi-convinced the database might got ruined at this point. You might try doing a `debug.setHead(0x...)`, setting to some numbers in the past (maybe 5000 (a day)) and hope that the corruption happened in that time frame. If that doesn't work out though, a resync might be needed.

**Comment by sirnicolas21** [comment]
1.11go was in the repos so i didn't compile one myself..... did so now however to 1.14
instance: Geth/v1.9.11-stable-6a62fe39/linux-arm/go1.14

sync now is causing a panic all the time

debug.setHead('0x9254F0') //9590000
that caused a panic and removed my whole progress to block 0 without being able to restart because it was panicking all the time

bringing back my backup from the NAS and i will retry later, if it panics again i will post the output (i forgot to copy paste it before) i will also try with go1.13 if 1.14 is not working at all

since you asked, the ssd is a Samsung Portable SSD T5 1TB and it can handle bitcoind_mainnet geth_testnet and geth_mainnet with no problems or any delay anywhere

**Comment by sirnicolas21** [comment]
after some digging i found on which transaction it stuck

by changing core/state_transition.go  preCheck to 

```
func (st *StateTransition) preCheck() error {
        // Make sure this transaction's nonce is correct.
        if st.msg.CheckNonce() {
                nonce := st.state.GetNonce(st.msg.From())
                if nonce < st.msg.Nonce() {
                        fmt.Printf("error nonce: current = %d trying to parse = %d, to = %s, value = %d\n",nonce, st.msg.Nonce(), st.msg.To().String(),st.msg.Value())
                        return ErrNonceTooHigh
                } else if nonce > st.msg.Nonce() {
                        return ErrNonceTooLow
                }
                fmt.Printf("parsing nonce: current = %d, parse=%d to = %s\n",nonce, st.msg.Nonce(),st.msg.To().String())
        }
        return st.buyGas()
}
```
some of the output is 

> parsing nonce: current = 1, parse=1 to = 0x19b4F14cC33D0bB0E08e96E8680d9C425B3078d1
> parsing nonce: current = 12, parse=12 to = 0x077d52B047735976dfdA76feF74d4d988AC25196
> parsing nonce: current = 0, parse=0 to = 0xb41df9CEB13Bb1DE309fb152AaE24606DF3b2816
> **error nonce: current = 0 trying to parse = 1, to = 0xb41df9CEB13Bb1DE309fb152AaE24606DF3b2816, value = 169755680000000000**
> parsing nonce: current = 18263, parse=18263 to = 0x239ec890C0ae862aEc500dE5fd18515fb9Ebf8D8
> ERROR[03-06|22:17:14.794]
> ########## BAD BLOCK #########

the transaction is.... 
https://etherscan.io/tx/0x25948303c0c1888406a3117ee1f06181fb208b2afbef0f24101e034882e1fb2a

i will dig further while i resync from scratch on another folder, but if there are any insights they are welcome

**Comment by sirnicolas21** [comment]
this is happening also in my windows machine (i pulled the files there)
```
instance: Geth/v1.9.11-stable-6a62fe39/windows-amd64/go1.13.8
coinbase: xxxxxxxxxxxxxxxxx
at block: 9597703 (Tue Mar 03 2020 12:44:01 GMT+0200 (EET))
 datadir: E:\CryptoCoins\eth\chain
 modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> INFO [03-07|12:17:41.640] New local node record                    seq=887 id=7b08396837ccc2d1 ip=185.235.240.215 udp=47353 tcp=30303
INFO [03-07|12:17:53.873] Looking for peers                        peercount=1 tried=42 static=0
INFO [03-07|12:18:04.188] Looking for peers                        peercount=1 tried=55 static=0
INFO [03-07|12:18:13.593] Block synchronisation started
INFO [03-07|12:18:14.198] Looking for peers                        peercount=2 tried=35 static=0
WARN [03-07|12:18:48.090] Checkpoint challenge timed out, dropping id=71f09568b58a19fa conn=dyndial addr=47.244.175.202:30303 type=Geth/v1.9.12-unstable-556888c4-20200302/linux-amd64/go1.13.8
WARN [03-07|12:18:50.475] Checkpoint challenge timed out, dropping id=90573716acb1308a conn=dyndial addr=45.32.107.133:30303  type=Getc/v6.0.6/linux/go1.12.6
ERROR[03-07|12:20:25.430]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Engine: ethash}

Number: 9597704
Hash: 0xae2bee3bd56112cfd10606b66f7af2578cc0f172d82fd867626fed39955d946b


Error: nonce too high
##############################
```

**Comment by holiman** [comment]
If by "pull the files" you mean that you copied over the database to another instance, then yes, you'd most likely see the same issue. The issue seems to be that the database is corrupted, and the nonce for the sender of the tx `0x25948303c0c1888406a3117ee1f06181fb208b2afbef0f24101e034882e1fb2a` (account `
0x958f46dbd800a57b44e05f362f76da262e89d675`) is zero -- so it's possible that the account is non-existant in that databse.

**Comment by sirnicolas21** [comment]
```
> web3.eth.getBalance('0x958f46dbd800a57b44e05f362f76da262e89d675')
WARN [03-13|12:36:58.273] Served eth_getBalance                    reqid=63 t=204.868493ms err="missing trie node f4df7216f1343837784c30a858095de6b23ad80d7c800002e426c2a4e5068d56 (path 070b070a040001)"
Error: missing trie node f4df7216f1343837784c30a858095de6b23ad80d7c800002e426c2a4e5068d56 (path 070b070a040001)




> web3.eth.getBalance('0xb41df9ceb13bb1de309fb152aae24606df3b2816')
12050170057200000000
```

yes the database is corrupt, rewinding on my raspberry is impossible at least with my settings, it seems to run out of memory on the tx pool and it panics, i also see no progress indicator on the rewind process anywhere on my main machine (that has memory to do it) 

```
ps aux  | awk '{print $6/1024 " MB\t\t" $11}'  | sort -n | grep geth
29938.5 MB              geth
```
(and 20gb swap usage)
at this point i believe that issue can be closed unless you want it open to tweak the rewind process, maybe stop and memfree txpool? thanks for the help

**Comment by holiman** [comment]
I guess we might close this, just thought I'd ask.. I'm looking into some tooling to help recover a corrupted db, I don't suppose you still have this chaindata laying around?

**Comment by sirnicolas21** [comment]
no i don't have it now, i wiped everything a week ago and i synced from scratch, sorry
