### ISSUE TITLE
[CROSS-COMPILE] Windows build fails on release/1.9

### ISSUE THREAD

**Issue by blazejkrzak** [ethereum/go-ethereum#20733]
Hi there,

#### System information

OS & Version: Linux
GO VERSION: 1.13
branch `release/1.9`

#### Expected behaviour
```
xgo --deps=https://gmplib.org/download/gmp/gmp-6.0.0a.tar.bz2 \
  --targets=windows/* /
      ./cmd/geth
```
also 
```
make geth-windows
```

should build a proper binary file
#### Actual behaviour
Xgo fails with exit code 2.
```
# gopkg.in/olebedev/go-duktape.v3
duk_minimal_printf.c: In function 'duk__parse_pointer':
duk_minimal_printf.c:126:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  *out = (void *) val;
         ^
duk_minimal_printf.c: In function 'duk_minimal_vsnprintf':
duk_minimal_printf.c:236:76: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     off = duk__format_long(str, size, off, sizeof(void *) * 2, '0', 16, 0, (unsigned long) v);
                                                                            ^
2020/02/29 14:24:44 Failed to cross compile package: exit status 2.
```

#### Steps to reproduce the behaviour
cross compile from linux ubuntu 18.04

**Comment by karalabe** [comment]
The logs you pasted are warning, not errors. We're aware of them, but unless upstream fixes them, there's not much we can do. Re: the failure, please scroll up a bit in your logs and sew what failed really and please share them. Then we can proceed.
