### ISSUE TITLE
[swarm] Mist integration - landing dashboard backend functionality

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#2074]
- [ ] dedicated and actual disk space used for local storage 
- [ ] cumulative download / upload in Mb 
- [ ] bandwidth/peer reporting, swap arrangement, disconnects due to non-payment, for this we need to explicitly intriduce protocolspecific disconnect reason. 
- [ ] autocash/autodeposit settings, balance 
- [ ] swap price reporting and dynamic setting? recreate swap arrangement on the fly. 
- [ ] ~~insurance on?~~
- [ ] ~~encryption?~~

see https://files.gitter.im/ethereum/go-ethereum/private/mVN4/Swarm-SWAP_2x.png

**Comment by alexvandesande** [comment]
>  dedicated and actual disk space used for local storage

I don't need precision on these numbers. If you have already an average size for the chunks and the user can control the amount of chunks to be stored, then it's all good

> bandwidth/peer reporting, swap arrangement, disconnects due to non-payment, for this we need to explicitly intriduce protocolspecific disconnect reason.
>  autocash/autodeposit settings, balance

Isn't that how it works currently? I designed these based on my understanding

**Comment by homotopycolimit** [comment]
closing in favour of discussions at ethersphere
A lot of the functionality described here is still missing on the swarm side of things and eventually we'll want a status page for swarm independent of mist.

See for example 
https://github.com/ethersphere/go-ethereum/issues/158
https://github.com/ethersphere/go-ethereum/issues/159
https://github.com/ethersphere/go-ethereum/issues/243
