### ISSUE TITLE
Unexpected fault address while

### ISSUE THREAD

**Issue by miguelconde91** [ethereum/go-ethereum#20740]
I picked up an Ethereum Blockchain at AWS ECS almost 3 months ago, it was working perfectly until I got this bug yesterday from the mining node:

unexpected fault address 0x7fb93c71d000
[signal SIGBUS: bus error code=0x2 addr=0x7fb99641a000 pc=0x4733c0]
goroutine 273542628 [running]
runtime.throw(0xf75488, 0x5)

I managed to get the mineral back and have it replicated from the client, but it turns out that it has happened again and it has even happened to me already in the client. This address is not linked to any wallet or hash of transaction or anything processed by the Blockchain. What could be the cause of this error and how to avoid it? 
Using Geth/v1.8.2-stable/linux-amd64/go1.9.7

**Comment by karalabe** [comment]
The latest Geth release is 1.9.11. There have been 37 releases made since the version you are using (which will be 2 years old tomorrow). We cannot support such an old codebase.

**Comment by karalabe** [comment]
Just to expand, if this happens on the latest release, we can definitely take a look, but there's a very high chance this was fixed long ago.

**Comment by Liquidator2048** [comment]
same issue on 1.9.23-stable-8c2f2715 and 1.9.24-unstable-b305591e-20201016
`unexpected fault address 0x7f02a074d000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f02a074d000 pc=0x48d8a0]
`
