### ISSUE TITLE
What is the meaning of the gas in{"gasUsed":"0x2540be400"}?

### ISSUE THREAD

**Issue by BattleBird** [ethereum/go-ethereum#20744]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.9.0`
OS & Version: Linux
Commit hash : (if `develop`)

#### Actual behaviour
{"output":"","gasUsed":"0x2540be400","time":1588231,"error":"stack underflow (5 \u003c=\u003e 6)"}

When i run a piece of bytecode, the output is {"output":"","gasUsed":"0x2540be400","time":1588231,"error":"stack underflow (5 \u003c=\u003e 6)"}

I would like to ask what is the meaning of the gas? it has special meaning? Because when an error throw in the execution, the gas will be 0x2540be400  :)  Thank you for your explanation

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
