### ISSUE TITLE
evm version 1.9.0 refuse the odd length of bintime bytecode

### ISSUE THREAD

**Issue by BattleBird** [ethereum/go-ethereum#20743]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.9.0`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
print traces like before version 1.9.0

#### Actual behaviour
Invalid input length for hex data (8165)

Hello, when I use the evm 1.9.0 run a transaction, whose the length of bytecode is 8165, it says Invalid input length for hex data (8165); but when I use the evm 1.8.27 run the same bintime code, it can generate normally a list of trace like this:
"pc":0,"op":96,"gas":"0x2540be400","gasCost":"0x3","memory":"0x","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH1","error":""}
{"pc":2,"op":96,"gas":"0x2540be3fd","gasCost":"0x3","memory":"0x","memSize":0,"stack":["0x80"],"depth":1,"refund":0,"opName":"PUSH1","error":""}
{"pc":4,"op":82,"gas":"0x2540be3fa","gasCost":"0xc","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","memSize":96,"stack":["0x80","0x40"],"depth":1,"refund":0,"opName":"MSTORE","error":""}

Actually, I would like to ask why the evm refuse the odd length of runtime code after version 1.9.0:)

**Comment by karalabe** [comment]
Every byte needs 2 characters to be encoded into hex format. If you specify an odd number of hex characters, that means that somewhere half a byte is missing. Old versions of Geth probably didn't enforce this and padded the blob with a zero at the beginning.

Whilst there are some cases when more flexibility *can* be correct (e.g. if the byte blob has `0000` as the first 4 bits), generally it's more common that someone copy-pastes a hex string and accidentally doesn't select all of it. By enforcing proper lengths we can ensure that accidental copy-paste errors don't slip by unnoticed.
