### ISSUE TITLE
the method shh_newKeyPair does not exist/is not available

### ISSUE THREAD

**Issue by rohankeskar19** [ethereum/go-ethereum#20756]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: 
```
Geth
Version: 1.9.11-stable
Git Commit: 6a62fe399b68ab9e3625ef5e7900394f389adc3a
Git Commit Date: 20200218
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.8
Operating System: windows
GOPATH=C:\Projects\GoProjects;
GOROOT=C:\go
```
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Should get a new key pair

#### Actual behaviour
Program output
```
2020/03/11 16:54:48 the method shh_newSymKey does not exist/is not available
exit status 1
```

Geth output
```
WARN [03-11|16:49:49.314] Served shh_newKeyPair                    reqid=1 t=0s err="the method shh_newKeyPair does not exist/is not available"
```

#### Steps to reproduce the behaviour
Run this code
```
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/ethereum/go-ethereum/whisper/shhclient"
)

func main() {
	client, err := shhclient.Dial("ws://127.0.0.1:8546")

	if err != nil {
		log.Fatal(err)
	}

	keyID, err := client.NewSymmetricKey(context.Background())
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(keyID)
}

```

#### Backtrace

````
go run src\github.com\rohankeskar19\whisper\main.go
2020/03/11 16:54:48 the method shh_newSymKey does not exist/is not available
exit status 1
````

**Comment by karalabe** [comment]
Is your remote Geth node running Whisper? Does it expose `shh` on websockets?

**Comment by rohankeskar19** [comment]
Yeah I started it using ```geth --rpc --shh --ws```

**Comment by karalabe** [comment]
Spinning up a node just now, I think by default `shh` is not exposed on websockets:

```
$ geth --goerli -ws
```

```
$ geth attach ws://127.0.0.1:8546
[...]
 modules: eth:1.0 net:1.0 rpc:1.0 web3:1.0
```

You probably need to explicitly specify `--wsapi eth,net,rpc,web3,shh` too.

**Comment by rohankeskar19** [comment]
> Spinning up a node just now, I think by default `shh` is not exposed on websockets:
> 
> ```
> $ geth --goerli -ws
> ```
> 
> ```
> $ geth attach ws://127.0.0.1:8546
> [...]
>  modules: eth:1.0 net:1.0 rpc:1.0 web3:1.0
> ```
> 
> You probably need to explicitly specify `--wsapi eth,net,rpc,web3,shh` too.

I started it using ```geth --goerli -ws``` still gives me same error

**Comment by karalabe** [comment]
> You probably need to explicitly specify --wsapi eth,net,rpc,web3,shh too.

**Comment by rohankeskar19** [comment]
Hey, I got it working with ```geth -ws --shh --wsapi eth,net,rpc,web3,shh```
