### ISSUE TITLE
Different results from function "opCaller" between Geth and Parity, which causes the differnt behaviours

### ISSUE THREAD

**Issue by BattleBird** [ethereum/go-ethereum#20759]
#### System information

Geth version: `1.9.11`
parity version: '2.7.2"
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
the Geth's output should be the same with the parity' output

#### Actual behaviour
**Geth**:  {"output":"","gasUsed":"0x42b","time":1400092,"error":"evm: execution reverted"}

**parity**: {"error":"EVM: Out of gas","gasUsed":"0x100000","time":1015415} 

#### Steps to reproduce the behaviour
import subprocess
bincode = "6080604052600436106100d0576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806319449cb2146100d557806328090abb146101185780633c18d318146101a55780635e949fa0146102285780635ed7ca5b1461026b5780636fcb15001461028257806377bb09eb146102d95780638da5cb5b1461033c57806397dc97cb14610393578063a6f9dae1146103ea578063a9b1d5071461042d578063b269681d14610484578063b9b8af0b146104db578063be9a65551461050a575b600080fd5b3480156100e157600080fd5b50610116600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610521565b005b34801561012457600080fd5b506101a3600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001909291905050506105c0565b005b3480156101b157600080fd5b506101e6600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610642565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561023457600080fd5b50610269600480360381019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291905050506106f5565b005b34801561027757600080fd5b50610280610794565b005b34801561028e57600080fd5b50610297610866565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b3480156102e557600080fd5b5061033a600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff16906020019092919050505061088c565b005b34801561034857600080fd5b50610351610969565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561039f57600080fd5b506103a861098e565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b3480156103f657600080fd5b5061042b600480360381019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291905050506109b4565b005b34801561043957600080fd5b50610442610a52565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561049057600080fd5b50610499610bcd565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b3480156104e757600080fd5b506104f0610bf3565b604051808215151515815260200191505060405180910390f35b34801561051657600080fd5b5061051f610c06565b005b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561052157600080fd5b80600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b8173ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff168573ffffffffffffffffffffffffffffffffffffffff167fa64da754fccf55aa65a1f0128a648633fade3884b236e879ee9f64c78df5d5d7846040518082815260200191505060405180910390a450505050565b600080600460008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905060008173ffffffffffffffffffffffffffffffffffffffff1614156106ec57600360009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1690505b80915050919050565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561075057600080fd5b80600260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415801561083f57506000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614155b1561084957600080fd5b6001600260146101000a81548160ff021916908315150217905550565b600360009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415156108e757600080fd5b80600460008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505050565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141515610a0f57600080fd5b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b6000600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614158015610aff57506000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614155b15610b0957600080fd5b30610b12610c7e565b808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001915050604051809103906000f080158015610b64573d6000803e3d6000fd5b5090507fef4c8685c12779a52dae7549eb7defa8523f67a054ad425b877a6b2da469a33181604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390a190565b600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600260149054906101000a900460ff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141515610c6157600080fd5b6000600260146101000a81548160ff021916908315150217905550565b60405161033580610c8f833901905600608060405234801561001057600080fd5b5060405160208061033583398101806040528101908080519060200190929190505050806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550506102b2806100836000396000f30060806040526004361061004c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680636ea056a91461004e578063c0ee0b8a146100b3575b005b34801561005a57600080fd5b50610099600480360381019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190505050610146565b604051808215151515815260200191505060405180910390f35b3480156100bf57600080fd5b50610144600480360381019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509192919290505050610281565b005b600080809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16633c18d318846040518263ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001915050602060405180830381600087803b15801561020357600080fd5b505af1158015610217573d6000803e3d6000fd5b505050506040513d602081101561022d57600080fd5b810190808051906020019092919050505073ffffffffffffffffffffffffffffffffffffffff1660003660405180838380828437820191505092505050600060405180830381855af4915050905092915050565b5050505600a165627a7a7230582096d30d43ac84da6ca406f9bdb705dc4d45ae2ad120e8e63ba323e2b2edc50fb80029a165627a7a723058208a622ab443052d29e2b70988be79000000000000639ac1278c7eca1fdd4c28620d7b2be396050029"
sigName = "0x19449cb2000000000000000000000000b122f0fe63e1e049c230517fee7dd0d8efe5654d"

retcodegethtimeoutOrRunError = subprocess.call(
        "/home/xuhang/bin/benchmarks/evm/evm_1_9_11 --debug --json --code " + bincode + " --input " + sigName[
                                                                                2:] + " run > "  + "./" + "gethout.json 2>&1",
        timeout=60,
        shell=True)
    print("success!")

retcodeparity = subprocess.call(
        "/home/xuhang/bin/benchmarks/parity-evm/parity-evm_2_7_2 stats --json --gas 100000 --code " + bincode + " --input " + sigName[
                                                                                          2:] + " > " + "parityout.json 2>&1",
        timeout=60,
        shell=True)

#### Backtrace
**The Geth's trace(the last 9 lines):** 
{"pc":1370,"op":51,"gas":"0x2540bdff9","gasCost":"0x2","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0"],"depth":1,"refund":0,"opName":"CALLER","error":""}
{"pc":1371,"op":115,"gas":"0x2540bdff7","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0","0x73656e646572"],"depth":1,"refund":0,"opName":"PUSH20","error":""}
{"pc":1392,"op":22,"gas":"0x2540bdff4","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0","0x73656e646572","0xffffffffffffffffffffffffffffffffffffffff"],"depth":1,"refund":0,"opName":"AND","error":""}
{"pc":1393,"op":20,"gas":"0x2540bdff1","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0","0x73656e646572"],"depth":1,"refund":0,"opName":"EQ","error":""}
{"pc":1394,"op":21,"gas":"0x2540bdfee","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0"],"depth":1,"refund":0,"opName":"ISZERO","error":""}
{"pc":1395,"op":21,"gas":"0x2540bdfeb","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x1"],"depth":1,"refund":0,"opName":"ISZERO","error":""}
{"pc":1396,"op":97,"gas":"0x2540bdfe8","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0"],"depth":1,"refund":0,"opName":"PUSH2","error":""}
{"pc":1399,"op":87,"gas":"0x2540bdfe5","gasCost":"0xa","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0","0x521"],"depth":1,"refund":0,"opName":"JUMPI","error":""}
{"pc":1400,"op":96,"gas":"0x2540bdfdb","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d"],"depth":1,"refund":0,"opName":"PUSH1","error":""}
{"pc":1402,"op":128,"gas":"0x2540bdfd8","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0"],"depth":1,"refund":0,"opName":"DUP1","error":""}
{"pc":1403,"op":253,"gas":"0x2540bdfd5","gasCost":"0x0","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0","0x0"],"depth":1,"refund":0,"opName":"REVERT","error":""}
{"output":"","gasUsed":"0x42b","time":1400092,"error":"evm: execution reverted"}

**parity' output**
{"pc":1370,"op":51,"opName":"CALLER","gas":"0x65","gasCost":"0x2","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0"],"storage":{},"depth":1}
{"pc":1371,"op":115,"opName":"PUSH20","gas":"0x63","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0","0x0"],"storage":{},"depth":1}
{"pc":1392,"op":22,"opName":"AND","gas":"0x60","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0","0x0","0xffffffffffffffffffffffffffffffffffffffff"],"storage":{},"depth":1}
{"pc":1393,"op":20,"opName":"EQ","gas":"0x5d","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0","0x0"],"storage":{},"depth":1}
{"pc":1394,"op":21,"opName":"ISZERO","gas":"0x5a","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x1"],"storage":{},"depth":1}
{"pc":1395,"op":21,"opName":"ISZERO","gas":"0x57","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x0"],"storage":{},"depth":1}
{"pc":1396,"op":97,"opName":"PUSH2","gas":"0x54","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x1"],"storage":{},"depth":1}
{"pc":1399,"op":87,"opName":"JUMPI","gas":"0x51","gasCost":"0xa","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","stack":["0x19449cb2","0x116","0xb122f0fe63e1e049c230517fee7dd0d8efe5654d","0x1","0x521"],"storage":{},"depth":1}

**"ROOT CAUSE"**
I find the returned address of opcode "CALLER" is different.
In Geth: it returns an address "0x73656e646572" (not 0x0)
In parity: it returns an address  "0x0"
and then this causes the different results in "AND""EQ""ISZERO" and "JUMPI" opcodes
so the final results are different.
Is this a bug in implementation in **func opCaller** in Geth?

**Comment by holiman** [comment]
WHhen using the raw evm binaries, you run into things like this. So geth uses `0x73656e646572` -- which is ascii `sender`. Parity uses `0x0..0`. There are other differences, and unless you specify each and every little detail via command line parameters, you'll hit issues like this. 

In order to get around it, it's better to _not_ use `code` option, but instead bundle together your code+environment info (blocknumber, timestamp, sender, receiver etc) into a state test. All vms can interpret state-tests, and that's what we use for fuzzing the vms against eachother in e.g. github.com/holiman/goevmlab/
