### ISSUE TITLE
The 'MLOAD' opcode cause an "out of gas" error

### ISSUE THREAD

**Issue by BattleBird** [ethereum/go-ethereum#20757]
#### System information

Geth version: `geth 1.9.7`
OS & Version: Linux

#### Actual behaviour
{"pc":373,"op":128,"gas":"0x2540be389","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0x6ea056a9","0x6ea056a9","0x6ea056a9"],"depth":1,"refund":0,"opName":"DUP1","error":""}
{"pc":374,"op":81,"gas":"0x2540be386","gasCost":"0x5f9d041aece","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0x6ea056a9","0x6ea056a9","0x6ea056a9","0x6ea056a9"],"depth":1,"refund":0,"opName":"MLOAD","error":"out of gas"}

#### Steps to reproduce the behaviour
import subprocess
bincode = "608060405260043610610041576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680636ea056a914610053575b34801561004d57600080fd5b50600080fd5b34801561017057600080fd5b5061009e600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001909291905050506100b8565b604051808215151515815260200191505060405180910390f35b6000806000806000806000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166397dc97cb6040518163ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401602060405180830381600087803b15801561014657600080fd5b505af115801561015a573d6000803e3d6000fd5b505050506040513d602081101561017057600080fd5b810190808051906020019092919050505073ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141580156102a757506000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16638da5cb5b6040518163ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401602060405180830381600087803b15801561023c57600080fd5b505af1158015610250573d6000803e3d6000fd5b505050506040513d602081101561026657600080fd5b810190808051906020019092919050505073ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614155b156102b157600080fd5b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1663b9b8af0b6040518163ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401602060405180830381600087803b15801561033657600080fd5b505af115801561034a573d6000803e3d6000fd5b505050506040513d602081101561036057600080fd5b81019080805190602001909291905050501561037b57600080fd5b600094506000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1663b269681d6040518163ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401602060405180830381600087803b15801561040457600080fd5b505af1158015610418573d6000803e3d6000fd5b505050506040513d602081101561042e57600080fd5b81019080805190602001909291905050509350600073ffffffffffffffffffffffffffffffffffffffff168873ffffffffffffffffffffffffffffffffffffffff16141515610648578792508691508273ffffffffffffffffffffffffffffffffffffffff166370a08231306040518263ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001915050602060405180830381600087803b15801561051857600080fd5b505af115801561052c573d6000803e3d6000fd5b505050506040513d602081101561054257600080fd5b810190808051906020019092919050505082111561056357600095506107fa565b8273ffffffffffffffffffffffffffffffffffffffff1663a9059cbb85846040518363ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200182815260200192505050602060405180830381600087803b15801561060657600080fd5b505af115801561061a573d6000803e3d6000fd5b505050506040513d602081101561063057600080fd5b810190808051906020019092919050505094506106ab565b8690503073ffffffffffffffffffffffffffffffffffffffff163181111561067357600095506107fa565b8373ffffffffffffffffffffffffffffffffffffffff166108fc829081150290604051600060405180830381858888f1935050505094505b84156107f6576000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166328090abb30868b8b6040518563ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001828152602001945050505050600060405180830381600087803b1580156107dd57600080fd5b505af11580156107f1573d6000803e3d6000fd5b505050505b8495505b5050505050929150505600a165627a7a723058207d6de0ae39c8400ce1f6ead9a4fadd005ba27ccce42761a5c422f0811015bce50029"
sigName = "0x6ea056a90000000000000000000000005fadeb204bf1df98095e0388377d1bef2cab1cdf000000000000000000000000000000000000000000000000000000000000004a"
retcodegethtimeoutOrRunError = subprocess.call(
        "./evm --debug --json --code " + bincode + " --input " + sigName[
                                                                                2:] + " run > "  + "./" + "gethout.json 2>&1",
        timeout=60,
        shell=True)

#### Question
I check the gas of MLOAD opcode is 3, but in this runtime test, in pc:374 , the gasCost of "MLOAD" is "0x5f9d041aece" and then cause the "out of gas" error. Is this a bug?

**Comment by fjl** [comment]
The gas cost of this MLOAD is so high because MLOAD will first resize the memory up to the address which you are loading. The overall cost of MLOAD is the constant gas for the op itself plus the cost of the expansion. I know it sounds stupid, but that's what EVM semantics dictate and it's not a bug in go-ethereum.
