### ISSUE TITLE
Geth light is synced but the account balance still returns 0

### ISSUE THREAD

**Issue by mbsaberi** [ethereum/go-ethereum#20768]
#### System information
Geth version: `1.9.11-stable`
OS & Version: Linux (Ubuntu 18.04)
Commit hash : 6a62fe399b68ab9e3625ef5e7900394f389adc3a

#### Expected behaviour
Account balance should be ETH 0.00001

#### Actual behaviour
Account balance returns 0

#### Steps to reproduce the behaviour
I've installed Geth and ran it with light more. Serve is now synced regarding to the output below:  
```
> eth.syncing  
false
```
I had a testing transaction on a generated account which its details is available [here](https://etherscan.io/address/0xd9de4af752b564e6d0d2d03d4a7c413b726c2ab0). But the given balance still returns 0  
```
> web3.fromWei(eth.getBalance('0xd9de4af752b564e6d0d2d03d4a7c413b726c2ab0'), 'ether')  
0

```

**Comment by rjl493456442** [comment]
It works for me. 

```
> web3.fromWei(eth.getBalance('0xd9de4af752b564e6d0d2d03d4a7c413b726c2ab0'), 'ether')
0.0026469
```

Probably your light client hasn't started syncing yet, and the flag `eth.syncing` is also false

**Comment by mbsaberi** [comment]
The balance became OK with a delay about 20 minutes
