### ISSUE TITLE
Ways to improve RLP processing speed (caching?, concurrency?)

### ISSUE THREAD

**Issue by fxfactorial** [ethereum/go-ethereum#20786]
I understand that RLP encoding isn't going away anytime soon because the advantage of byte for byte correctness is hard to beat. That said, I find the performance of RLP encoding/decoding to be quite slow and I'm looking for ways to increase speed. That is, are there any tricks or insights that the ethereum codebase uses to make RLP encoding go faster? Or insights about how to organize data structures that are fastest, easiest for RLP to encode/decode. 

What about concurrency, would it be possible somehow to say take a slice of 1000 encodable things and then have 10 threads encode 100 at once and then concat the byte results? Anyway to cache RLP partial results without issues of losing correctness?

Thank you

@karalabe (tagging you because I appreciate you answering in previous issue of mine and maybe you can help explain here too)

**Comment by karalabe** [comment]
RLP encoding/decoding isn't particularly speedy (it was never really attempted to make it super fast). But generally there's also no particular need for it (I may be horribly wrong here). Can you provide some infos about what you're trying to do and why RLP is a bottleneck there?

**Comment by fjl** [comment]
Are you using Go and the RLP contained in this repo for your work?

**Comment by fjl** [comment]
Concurrency will not really help I think. If we wanted to make RLP processing faster, the next step would be creating a code generator.

**Comment by fxfactorial** [comment]
@karalabe Just thinking of places where I could have data structures like slices of types which themselves have fields which are slices. Where the nested slices can be of length 100,000 and have many usages of things like `*big.Int`. The decode and encode is painful in both memory and compute. 

@fjl yes, using the plain RLP impl. Has there been any improvement in it since go ethereum 1.8.27?

But I was thinking, say I have a RLP encoded slice of 100 items. Is there no way to correctly know where the middle index is and have at least two go threads decoding in parallel? 

Or what about EncodeToBytes, any caching ideas I could use there ? 

Can you elaborate on code generator? I want to keep the RLP encoding itself, just the runtime impl of it is something I wish I could make faster in some way (either in compute, or memory, or some caching)

**Comment by ferranbt** [comment]
You may want to check [fastrlp](https://github.com/umbracle/fastrlp). It does not do reflection so you can optimize both memory and cpu more efficiently (there are some benchmarks with respect to go-ethereum/rlp). You need to manually write the encoding/decoding yourself though. However, in the case of eth1, there are not that many data structures that need RLP encoding so is not that hard to do it manually like [here](https://github.com/umbracle/minimal/blob/develop/types/transaction_encoding.go#L11).

**Comment by fxfactorial** [comment]
Not relevant to me anymore
