### ISSUE TITLE
Not connecting to any nodes

### ISSUE THREAD

**Issue by infamousrev** [ethereum/go-ethereum#2079]
Hello,

I downloaded and compiled go-ethereum, however it does not connect to any nodes and it says "Table.go: No seed nodes found".

Analysing the network-traffic with wireshark shows that there are no problems with connectivity it simply does not try.

I am able to add nodes manually by extracting the enodes from ./eth/backend.go and adding them with admin.addPeer()

Using this technique it connects to 3 nodes and it will function properly, however it will never connect to more then just those 3 nodes.

So the issue is:
It does not connect to any bootnodes.
It does not exchange any peers with connected nodes.

**Comment by infamousrev** [comment]
I understand the most likely cause of this is a configuration issue.

However, since I checked carefully and cannot find anything (wireshark,iptables,strace) I decided it was a good idea to post it here in case it is caused by a regression in the code.

**Comment by infamousrev** [comment]
It does exchange UDP packages with multiple nodes, but it never connects without manual intervention

**Comment by fjl** [comment]
Is your local clock out of sync, by any chance?

**Comment by infamousrev** [comment]
Hmm, I had already synced it I thought, but tried syncing it again after your comment and it solved my problem.

**Comment by DavidBurela** [comment]
I had the exact same issue. Problem was computer time was off by only 1 or 2 mins. Syncing time resolved it.

**Comment by panicape** [comment]
ey guys, how can i see if local clock is out of sync and how to fix it?

**Comment by imifos** [comment]
on UBUNTU, something like this should help:  sudo ntpdate -s ntp.ubuntu.com (You may need to "apt-get install ntpdate" first).
