### ISSUE TITLE
Key store

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#208]
A new key store needs to be developed for genesis release. The current version has always been in a stand in for the final version.

Possible model

```
+----------------------+
| KeyStore - Generic   |
+----------------------+
          |
         \|/
+----------------------+
| KeyManager           |
+----------------------+
          |
         \|/
+----------------------+
| Wallet               |
+----------------------+
```

`KeyStore` is a generic interface and should potentially contains:
  * `Keys() []Key` returns all keys currently in the `KeyStore`
  * `Store(Key)` add a new key to the `KeyStore`
If any encryption needs to be done for storing, the `KeyStore` should handle this. `Store` and `Keys` simply return keys (unencrypted).

`KeyManager` should accept a `KeyStore` as its backing mechanism. KeyManager need not to know about the implementation details of the `KeyStore`:
  * `NewKey() Key` generates a new key and adds it to the key store.
  * `DeleteKey(Key)` deletes a key from the key manager as well as the `KeyStore`

`Wallet` basic wallet functionality. Manages accounts currently in use, known and owned by the author. Creating transactions for specific accounts should also be handled by the `Wallet`.

**Comment by Gustav-Simonsson** [comment]
WIP branch with to-be-squashed WIP commits: https://github.com/Gustav-Simonsson/go-ethereum/tree/new_key_handling
