### ISSUE TITLE
Cocoapod build fails on Travis

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20814]
Last good build: https://travis-ci.org/github/ethereum/go-ethereum/jobs/541245571
First bad build: https://travis-ci.org/github/ethereum/go-ethereum/builds/665807676

**Comment by karalabe** [comment]
This was mentioned in https://github.com/ethereum/go-ethereum/issues/20160
Apparently it needs to be fixed upstream: https://github.com/elastic/gosigar/pull/134

**Comment by karalabe** [comment]
Reopening until moment of truth

**Comment by adamschmideg** [comment]
Moment of truth :( https://travis-ci.org/github/ethereum/go-ethereum/jobs/667195095#L1523-L1529

**Comment by karalabe** [comment]
Well, the original issue s fixed. This is a new one :)

**Comment by ellen87006** [comment]
https://github.com/ethereum/go-ethereum/blob/7a63faf734d7150e764c0c08de7f83ceaf64e272/mobile/bind.go#L38 

It seems that new issue caused by structure rename from signer to MobileSigner.
@karalabe Is that acceptable to change it back?

**Comment by MariusVanDerWijden** [comment]
Build still fails, but it seems to fail now on uploading not on the code

**Comment by karalabe** [comment]
Added it back to triage for next week, lets see where the verbosity fix takes us.

**Comment by karalabe** [comment]
New error:

```
[!] Authentication token is invalid or unverified. Either verify it with the email that was sent or register a new session.
util.go:45: exit status 1
exit status 1
The command "go run build/ci.go xcode -signer IOS_SIGNING_KEY -deploy trunk -upload gethstore/builds" exited with 1.
```

**Comment by karalabe** [comment]
Android and iOS support dropped via https://github.com/ethereum/go-ethereum/pull/26599.
