### ISSUE TITLE
new state entries be imported faster?

### ISSUE THREAD

**Issue by 1blockologist** [ethereum/go-ethereum#20813]
What resources do new state entries use when syncing? is it CPU bound? Network bound? Memory bound? etc

I would like it to be possible to process them faster but there seems to be a limit and all my system resources are not being used for this.

#### System information

Geth version: `1.9.12`
OS & Version: Windows

#### Expected behaviour

A flag or default behavior to use more system resources, or make new network connections, in order to pull and process chain states faster

#### Actual behaviour

A limitation with only 10% of an 8-core CPU used and not heavily. 32gb RAM.

I am mainly curious about the information

#### Steps to reproduce the behaviour

geth -syncmode fast --cache 8192

**Comment by karalabe** [comment]
Fast sync is mostly limited by network latency (and serving latency/capacity of your peers). We're working on a new sync algorithm. There's not much to do in the mean time, but wait it out unfortunately.
