### ISSUE TITLE
Geth is still 1.9.11 in ubuntu launchpad

### ISSUE THREAD

**Issue by alvinoktavbitcoin** [ethereum/go-ethereum#20823]
Hi there,

I try to update geth to v1.9.12 using ubuntu packages.

by doing command :
sudo apt update
sudo apt install geth

But it return this result 
geth is already the newest version (1.9.11+build21238+xenial).

Is ubuntu launchpad not being update yet ?

**Comment by karalabe** [comment]
Huh, this is messed up. 6 builds out of 12 failed on launchpad. Logs are not available. Super weird. Restarted all the failed ones, less see what happens.

**Comment by karalabe** [comment]
Yeah, probably Launchpad was having some issues when we published the builds. Everything green now, all missing builds succeeded. Should be published soon, just needs to go through Launchpad's mirroring.
