### ISSUE TITLE
Can't connect to geth with ws api running on aws ec2 instance

### ISSUE THREAD

**Issue by rohankeskar19** [ethereum/go-ethereum#20825]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: ` 1.9.12-stable`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
I should be able to connect to remote node on ec2 instance

#### Actual behaviour
```
connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

I have an ec2 instance which is running geth, I ran it using 
``` geth --syncmode "light" -ws --shh -wsapi shh```
But when I use the ip of the ec2 instance, I can't connect to the instance, I'm running a go program which connects and generates key pair, I have enabled all ports on the instance and allowed all incoming traffic, But I can't connect to it, But when I ran a normal server which sends a response, It works and when I ran the program locally on the instance it worked, So I don't know what's wrong please help me.

```
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/ethereum/go-ethereum/whisper/shhclient"
)

func main() {
	client, err := shhclient.Dial("ws://ip_of_ec2:8546")
	if err != nil {
		log.Fatal(err)
	}
	keyID, err := client.NewKeyPair(context.Background())
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(keyID) // 0ec5cfe4e215239756054992dbc2e10f011db1cdfc88b9ba6301e2f9ea1b58d2
	publicKey, err := client.PublicKey(context.Background(), keyID)

	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(publicKey)

}


```

**Comment by thesolyd** [comment]
How did you solve this?

**Comment by rohankeskar19** [comment]
> How did you solve this?

You need to specify wsaddr param as 0.0.0.0 same for httpaddr.
