### ISSUE TITLE
Ignored if GasPrice is specified in toml file.

### ISSUE THREAD

**Issue by usd-yamazaki** [ethereum/go-ethereum#20839]
#### System information
Geth
Version: 1.9.11-stable
Git Commit: 6a62fe399b68ab9e3625ef5e7900394f389adc3a
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.8
Operating System: linux
GOPATH=
GOROOT=/build/ethereum-2t6lYR/.go

#### Expected behaviour
The following two do the same
--miner.gasprice 0

[Eth.Miner]
GasPrice = 0

#### Actual behaviour
When gasprice is specified in toml file, transaction with gasprice of 0 is not propagated.

#### Steps to reproduce the behaviour
Build a private clique with two miner and non-miner nodes.
Change only the above options and send transactions with gasprice of 0 to non-miners.

**Comment by holiman** [comment]
```
[user@work go-ethereum]$ build/bin/geth --dev --miner.gasprice=0 --txpool.pricelimit=0 2>&1 | grep WARN
WARN [04-02|11:00:50.694] Sanitizing invalid miner gas price       provided=0 updated=0
WARN [04-02|11:00:50.695] Upgrade blockchain database version      from=<nil> to=7
WARN [04-02|11:00:50.695] Sanitizing invalid txpool price limit    provided=0 updated=1
```

**Comment by adamschmideg** [comment]
Setting the gas price to 0 would make it possible to DDOS the network, that's why Geth should give a warning "Sanitizing invalid miner gas price" and set it to 1.

Note to ourselves: We should forbid users from running a miner node with gas price 0.

**Comment by holiman** [comment]
The txpool cannot be set to accept `0`-value transactions. The miner codepath has some error, it says bumping from zero to zero, which is obviously wrong. So something's buggy there

**Comment by rjl493456442** [comment]
I will close this issue now. 

There are two minimal gasprice settings in Geth, one is `miner.gasprice` which specifies the minimal acceptable price for mining. Another one is `txpool.pricelimit` which specifies the minimal acceptable price for "propagation".

Zero price transactions won't be propagated through the network. So in your case the transaction won't arrive the miner's node even you change the `miner.gasprice`.
