### ISSUE TITLE
ERROR : gas limit reached.. !

### ISSUE THREAD

**Issue by ellen4** [ethereum/go-ethereum#20845]
## System information

Geth version: 1.9.9
OS & Version: ubuntu 18.04
Commit hash : (if `develop`)

Hi, I'm having a problem with a geth running.
I expected geth to synch blocks..

But It goes wrong..
with a error message below

It just keeps having problem
every time I run the geth.

How can I solve this problem .. ?

```
ERROR[04-01|14:35:20.828]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Engine: ethash}

Number: 9708068
Hash: 0x4ea1f0f35d1121a8594ee02ce3e3e75f2388280bf14efca2970780ae4975f975


Error: gas limit reached
```

**Comment by ligi** [comment]
can you provide the command line options you started the node with?

**Comment by ellen4** [comment]
> can you provide the command line options you started the node with?

```
./geth --syncmode "fast" --cache 4096 --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --rpcport 8545 --rpcvhosts=lyze.iptime.org,localhost --rpcapi "debug,net,eth,web3" --gcmode "archive" --verbosity 3 console --datadir "/media/raid_ssd/geth/evm_geth_fast/evm_geth"
```

That was my command to execute geth in `build/bin/`

**Comment by ligi** [comment]
Thanks for the info - and you where building on commit 017449971e1e9e220efcd97d3313a0e27f47003b ?

**Comment by ellen4** [comment]
Hmm I don't know actually cause I didn't install it. It's version 1.9.9

**Comment by ellen4** [comment]
> Thanks for the info - and you where building on commit [0174499](https://github.com/ethereum/go-ethereum/commit/017449971e1e9e220efcd97d3313a0e27f47003b) ?

Hmm I don't know actually cause I didn't install it. It's version 1.9.9

**Comment by ellen4** [comment]
> Thanks for the info - and you where building on commit [0174499](https://github.com/ethereum/go-ethereum/commit/017449971e1e9e220efcd97d3313a0e27f47003b) ?

Yes it's on that commit. and it's version 1.9.9

**Comment by karalabe** [comment]
This seems to be a corrupted database. The interesting question is how that happened. Did your node crash recently? Long term we've been thinking about doing a database check/repair tool to aid, but that won't help you. The quickest thing would be to resync (you could delete the chaindata files but **not** the `ancient` folder within, which would keep all the downloaded chain data and only download the state).

**Comment by ellen4** [comment]
> This seems to be a corrupted database. The interesting question is how that happened. Did your node crash recently? Long term we've been thinking about doing a database check/repair tool to aid, but that won't help you. The quickest thing would be to resync (you could delete the chaindata files but **not** the `ancient` folder within, which would keep all the downloaded chain data and only download the state).

It maybe related with ptoblem you mentioned `Did your node crash recently?` 
The server running Geth has gone without appropriate reason about few days ago. 

Could this abnormal server down problem cause a problem I mentioned?

**Comment by ucwong** [comment]
@ellen4 Have u clean the data-dir before starting sync this time, whether u download other chainId chain before...

**Comment by ellen4** [comment]
> @ellen4 Have u clean the data-dir before starting sync this time, whether u download other chainId chain before...

Yes There was some process like below

1. full sync from block 0 to near 9000000

2. datadir (SSD) was full.

3. backup past data (0 ~ 9000000) to HDD and I started fast sync on SSD

Is there anything in the process that could cause problems?

**Comment by ligi** [comment]
step #2 could corrupt the DB as far as I see.

**Comment by ellen4** [comment]
> step #2 could corrupt the DB as far as I see.

Ok, then.. What could I do ..? I need to crawl Geth again soon T_T

**Comment by holiman** [comment]
> Ok, then.. What could I do ..? I need to crawl Geth again soon T_T


Sorry, but you need to resync. Geth current has no way to repair a corrupted database.

**Comment by jayboy-mabushi** [comment]
@karalabe I have had this issue like twice now and had to resync. can losing internet connection also cause this issue?
