### ISSUE TITLE
eth/downloader: TestBoundedXXXForkedSyncXXXFast tests are flaky on Travis

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20842]
TestBoundedHeavyForkedSync63Fast: https://travis-ci.org/github/ethereum/go-ethereum/jobs/669570148
TestBoundedHeavyForkedSync64Fast: https://travis-ci.org/github/ethereum/go-ethereum/jobs/668816462
TestBoundedForkedSync63Fast: https://travis-ci.org/github/ethereum/go-ethereum/jobs/669527255
TestBoundedForkedSync64Fast: https://travis-ci.org/github/ethereum/go-ethereum/jobs/669534995

**Comment by holiman** [comment]
Yeah, this is exactly one of those cases where we'd be better off with go 1.13-type error handling, so we wouldn't reuse the same error in N different places without any context information 
![Screenshot from 2020-03-31 20-11-56](https://user-images.githubusercontent.com/142290/78060507-e8b44c80-738b-11ea-9b47-6af3020950a2.png)

**Comment by adamschmideg** [comment]
This is the first commit where these tests started to fail: https://github.com/ethereum/go-ethereum/commit/1b6b0df831934ee7f012881cd023f787d6b5fa73
