### ISSUE TITLE
No package found github.com/influxdata/influxdb/client

### ISSUE THREAD

**Issue by ali2210** [ethereum/go-ethereum#20840]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX 18.4
Commit hash : (if `develop`)

#### Expected behaviour
install./... 
execute and allow contracts

#### Actual behaviour
Return github.com/influxdata/influxdb/client no package found

#### Steps to reproduce the behaviour
go get -u github.com/ethereum/go-ethereum 

#### Backtrace
dependencies check except this error 
````
[backtrace]
````

**Comment by karalabe** [comment]
Please run with Go 1.13 or later. We depend on go modules to fetch the correct versions of dependencies.

**Comment by karalabe** [comment]
Ah yeah, Go is broken, again: https://github.com/golang/go/issues/24250#issuecomment-377553022

You **cannot** `go get` a project any more that uses modules. You can clone the `go-ethereum` repo and then `go install` inside it. That will work properly as Go will take the module locks into consideration.

**Comment by karalabe** [comment]
Opened a new issue upstream, honestly doubt they will fix it if they ignored it for 2 years: https://github.com/golang/go/issues/38196
