### ISSUE TITLE
upgrading of geth-stable fails in chocolatey (windows)

### ISSUE THREAD

**Issue by altsheets** [ethereum/go-ethereum#2086]
choco upgrade geth-stable

fails:

![screenshot](http://i.imgur.com/FGwH6cK.png)

what to do?

thanks.

**Comment by altsheets** [comment]
ah, the version is needed

    choco install geth-stable -version 1.2.2.0

I suggest you get the version [approved](https://chocolatey.org/packages/geth-stable)   
or   
put that line [into the manual](https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows)

Thanks

**Comment by altsheets** [comment]
how to get a newer version than 1.2.2.0 --> https://github.com/ethereum/go-ethereum/issues/2087#issuecomment-166663969

**Comment by tgerring** [comment]
Chocolatey package needs to be updated per https://github.com/ethereum/go-ethereum/issues/1950#issuecomment-152498107

**Comment by altsheets** [comment]
See https://github.com/ethereum/go-ethereum/issues/2087#issuecomment-168516500
