### ISSUE TITLE
EthCall on past blocks gives [ missing trie node .... ]

### ISSUE THREAD

**Issue by mesudip** [ethereum/go-ethereum#20874]
Hi there,
I am interacting with a contract using rpc api, and I am making ethCall to get token balance at past blocks.It works on about 50 old blocks, but on querying older blocks, it gives me the error.

**What sets that limit and how can I increase the limit?**

### Message
````
missing trie node ef7df5d88cb1614dc3f143879a653cd90717ee42e967c5fabbcd7505a968f314 (path )
````

**Comment by karalabe** [comment]
You cannot increase the limit. A Geth full node prunes states older than 128 blocks. The 128 are kept in memory, so increasing it would be a huge memory hit.
