### ISSUE TITLE
getUncleCount(fromBlock,toBlock) - or: Doesn't total supply depend on uncle count?

### ISSUE THREAD

**Issue by altsheets** [ethereum/go-ethereum#2088]
I want to calculate the total supply.   

I am wondering if I understand the mining rewards correctly. 
I think it is **not** simply 

    supply = premine + blocknumber*blockreward

because of "uncles", right?

An *uncle miner* gets 4.375 coins or 3.75 coins (for 0Uncles and 1Uncles).   Correct? Other options?

Plus *including* an uncle *into a block* gives an extra 5/32 coins to the block miner. Correct?

So the total supply of ETH is (probably)

    supply = premine 
    + blockReward * blockNumber 
    + 0UncleReward * NumberOf0Uncles 
    + 1UncleReward * NumberOf1Uncles 
    + includeUnclesReward * NumberOfIncludedUncles

Correct, or am I completely missing the point?

**If** that is (near to) correct ... then it is impossible to calculate the REAL current supply at the moment. So: 

**I suggest new API functions:**

    getUncleCount(fromBlock,toBlock)
    getIncludedUnclesCount(fromBlock,toBlock)

where the first one returns the tuple of number of 0Uncles and 1Uncles (and 2Uncles if there are any), and the second one simply totals the number of uncles included into blocks

Or is there an easier way to do this?

Used sources:
* https://github.com/ethereum/go-ethereum/issues/1591#issuecomment-128049106
* http://gavwood.com/paper.pdf equation 143 & 144
* https://forum.ethereum.org/discussion/2437/confused-about-block-rewards

P.S.: Even the "big guys" are of a differing opinion on the "supply" topic - there is a (0.3 percent) difference between the "supply" reported at etherscan and CMC. Is that because of the above ?

**Comment by obscuren** [comment]
I don't see the point of having these new API calls. Could you please specify why these would be required for DApp development (or any other type of development)?

If you'd like to get all uncles for statistics just loop over all the blocks in your desired range.

Unsure what `+ includeUnclesReward * NumberOfIncludedUncles` means however.

**Comment by altsheets** [comment]
Thanks a lot for your answer.


> I don't see the point of having these new API calls.  

Because otherwise I would have to iterate over all 800,000 blocks, checking all of them for uncles. 


> why these would be required

I would like to calculate the REAL total supply.

supply = premine + mined

The 'mined' part is tricky because of the uncle rewards.


> Unsure what ...

There is a reward given to miners who have included uncles into their mined blocks - right?

**Comment by tgerring** [comment]
> Because otherwise I would have to iterate over all ~800,000 blocks, checking all of them for uncles. 
And each time I want to update that information I either have to store my intermediate results, or completely redo them (and why should I store such a result, which is of such general interest? The ethereum software itself should know about those numbers - they are just small integers, and will not take up much space.).

What you're describing are **database indexes** which is a non-trivial topic and why you're not likely to get an answer about aggregates via API any time soon. To effectively respond to queries like this will require more forethought than demanding a new API is created

**Comment by altsheets** [comment]
Exactly.

To prevent that, I was thinking about a supersimple internal summation, whenever a new block is added.

These are thoughts about a future API, of course ...

Is my above "supply = premine + ..." formula correct at all? Perhaps I am wrong in my assumption how much ether has been mined. But if not ...:

Right now (without iterating over all 800k blocks) it is impossible to name the **correct total supply of ether** - right?  



---

So what about (in the future) storing just two values:

* total NumberOf0Uncles that were included in all blocks until now
* total NumberOf1Uncles that were included in all blocks until now

That won't cost much. And (only) with that information, the REAL supply of ether can be calculated.

---

Or ... if you think you can afford to store 800,000 * 4 bytes * 2 ... you could store 2 numbers for each block:

* total NumberOf0Uncles that were included in all blocks until that block 
* total NumberOf1Uncles that were included in all blocks until that block 

That would allow an easy getUncleCount(fromBlock,toBlock), and reveal all information.

---

The first suggestion is really easy to include in a future version - don't you think so?

To not be able to correctly name the total supply of a (platform that is also used as a) currency ... is a bit odd, no?

**Comment by altsheets** [comment]
Exactly.

To prevent that, I was thinking about a supersimple internal summation, whenever a new block is added.

These are thoughts about a future API, of course ...

Is my above "supply = premine + ..." formula correct at all? Perhaps I am wrong in my assumption how much ether has been mined. But if not ...:

Right now (without iterating over all 800k blocks) it is impossible to name the **correct total supply of ether** - right?  



---

So what about (in the future) storing just **two integer values**:

* total NumberOf0Uncles that were included in all blocks until now
* total NumberOf1Uncles that were included in all blocks until now

That won't cost much. And (only) with that information, the REAL supply of ether can be calculated.

---

Or ... if you think you can afford to store 800,000 * 4 bytes * 2 ... you could store 2 numbers for each block:

* total NumberOf0Uncles that were included in all blocks until that block 
* total NumberOf1Uncles that were included in all blocks until that block 

That would allow an easy getUncleCount(fromBlock,toBlock), and reveal all information.

---

The first suggestion is really really easy to include in a future version - don't you think so?

And to not be able to correctly name the total supply of a (platform that is also used as a) currency ... is a bit odd, no?

**Comment by fjl** [comment]
If you need detailed information on the uncle headers of all blocks, please consider creating your own index. It is not that hard to build one. You can even update it incrementally using existing features of the web3 API.

Just to be clear on this: We take suggestions for new APIs seriously and keep track of them. This is the first time anyone has requested an API for aggregate information on uncle headers. Consider
your suggestion noted.

**Comment by altsheets** [comment]
Thanks a lot.

> Consider your suggestion noted.

Nice. So one day, I might see that function. Thx.

A tiny thing to add to it: While you are on it anyways, and when that above data is then available, please also create a simple API function that tells me, us, everyone ... about the total coin supply:

supply()

**Comment by altsheets** [comment]
Thanks a lot.

> Consider your suggestion noted.

Nice. So one day, I might see that function. Thx.

A tiny thing to add to it: While you are on it anyways, and when that above data is then available, please also create a simple API function that tells me, us, everyone ... about the total real coin supply:

supply()

**Comment by altsheets** [comment]
is my rewards calculation correct?

**Comment by altsheets** [comment]
When I came across this function suggestion ``totalSupply()`` for '[total token supply](https://github.com/ethereum/wiki/wiki/Standardized_Contract_APIs#totalsupply)' I was reminded of my -still unanswered- question above.

*I actually consider it suboptimal communication, to close github issues before they are actually answered.*

--> 

**What is the totalSupply of ETH ?**

**Comment by altsheets** [comment]
anyone?

**Comment by altsheets** [comment]
So here can can see what happens when issues are closed before they are answered. 

They are not on your radar anymore.

This admin behaviour is just ... wrong.
