### ISSUE TITLE
eth_getBlockByHash  duplicate fields (author/miner)

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#20889]
Request: 
``` {"jsonrpc":"2.0","method":"eth_getBlockByHash","params":["0xd9df00950a9a3158f91c7f9e4388df696ea78796ad32b7780e4508fd03f1c6c6", true],"id":341} ```

Reply:
```
{
 "author":"0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
 "difficulty":"0x20000",
 "extraData":"0x42",
 "gasLimit":"0x98bca4",
 "gasUsed":"0x0",
 "hash":"0xd9df00950a9a3158f91c7f9e4388df696ea78796ad32b7780e4508fd03f1c6c6", 
 "logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
 "miner":"0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
 "mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000",
 "nonce":"0x0000000000000000",
 "number":"0x1",
 "parentHash":"0x0f239a780ff30676c2f3b185a17b80a14de3efe7667051ff78e8f4b18f791c3f",
 "receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
 "sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
 "size":"0x1fd",
 "stateRoot":"0xac0fd0e85dd635c869a69c1a89b4982ce862f6e996aac792aaf1252243e24cc3",
 "timestamp":"0x7d0",
 "totalDifficulty":"0x40000",
 "transactions":[
 ], 
 "transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
 "uncles":[
 ]
}
```

Response has duplicated fields `author` and `miner` 
Field `author` is not declared in specs.

**Comment by rjl493456442** [comment]
Weird, how did you run the jsonrpc call? I can't reproduce it locally

**Comment by winsvega** [comment]
@holiman says this stays from Parity time long time ago

**Comment by karalabe** [comment]
It's in your retesteth code https://github.com/ethereum/go-ethereum/blob/master/cmd/geth/retesteth.go#L631

See, this is why we said retesteth is a horrible idea. You are opening bug reports against Geth, we spend time trying to find it and it turns out that the crappy tester hacked into Geth is wrong. You are not testing Geth, you are testing some random extension that's not live code.

**Comment by karalabe** [comment]
@holiman Can we drop retesteth?

**Comment by winsvega** [comment]
well thats because it was not implemented in the first place. 
there is no retesteth support in geth. its an extension hack.

**Comment by winsvega** [comment]
the goal was to use existing geth api:
https://github.com/ethereum/go-ethereum/pull/20905

then no code copy required.

**Comment by holiman** [comment]
Closed since we now have `evm t8n` for these usecases
