### ISSUE TITLE
env GO111MODULE=on go run build/ci.go install ./cmd/geth

### ISSUE THREAD

**Issue by HubZml** [ethereum/go-ethereum#20892]
what's wrong? My go version(1.14.1)   Please help.
env GO111MODULE=on go run build/ci.go install ./cmd/geth
go: writing go.mod cache: mkdir /usr/local/sbin/pkg: permission denied
go: writing go.mod cache: mkdir /usr/local/sbin/pkg: permission denied
.......................
go: downloading github.com/cespare/cp v0.1.0
go: downloading github.com/Azure/azure-storage-blob-go v0.7.0
go: downloading golang.org/x/crypto v0.0.0-20200311171314-f7b00557c8c4
internal/build/azure.go:25:2: mkdir /usr/local/sbin/pkg: permission denied
build/ci.go:61:2: mkdir /usr/local/sbin/pkg: permission denied
internal/build/pgp.go:27:2: mkdir /usr/local/sbin/pkg: permission denied
common/types.go:31:2: mkdir /usr/local/sbin/pkg: permission denied
Makefile:16: recipe for target 'geth' failed
make: *** [geth] Error 1

**Comment by dyntaos** [comment]
You aren't running the command as a user with appropriate permissions. Did you sudo the install command?

**Comment by HubZml** [comment]
> 您没有以具有适当权限的用户身份运行命令。您是否对安装命令进行了sudo？

Thank you for your answer, but there is still a problem. After using sudo, it prompts that go cannot be found.My go is installed in  /usr/local.
env GO111MODULE=on go run build/ci.go install ./cmd/geth
env: ‘go’: No such file or directory
Makefile:16: recipe for target 'geth' failed
make: *** [geth] Error 127

**Comment by karalabe** [comment]
This is not an issue with go-ethereum, rather the way you are misusing Go.

It is not obvious what user you are using and what Go configs you have. The first post is attempting to write to `/usr/local/sbin/pkg` which Go would never do, unless so configured `/usr/local/sbin/pkg` as your cache, which I don't know why you would do. Go's build cache is usually in your current user's home folder. Please make sure you don't have some strange configs. You don't need root permissions to build Geth.

The second issue is simply Go not being in PATH for your sudo user.

**Comment by shooresh-golzari-cko** [comment]
You likely do not have Go installed `sudo apt install golang-go` and try again.

**Comment by PatrickAlphaC** [comment]
For anyone who ran into this, I did:

```
# Remove go.sum
rm go.sum

# Then re-generate go.sum
go mod tidy
```
