### ISSUE TITLE
"eth_chainId" sometimes returns 0x0 instead of the correct chainId

### ISSUE THREAD

**Issue by nicinuse** [ethereum/go-ethereum#20894]
Hi there,

I am trying to set up a chainlinnk node with latest stable geth client, but it fails vecause of missing chainId value.

#### System information

Geth version: 
```
Geth
Version: 1.9.12-stable
Git Commit: b6f1c8dcc058a936955eb8e5766e2962218924bc
Git Commit Date: 20200316
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.8
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```
OS & Version:
````
Alpine Linux
```
Commit hash : (if `develop`)

#### Expected behaviour
Return the correct chainId


#### Actual behaviour
ChainId is always "0x0" (not available)


#### Steps to reproduce the behaviour
Run geth with
```
geth --testnet --nousb --rpc --rpcaddr '0.0.0.0' --rpcvhosts '*' --rpccorsdomain '*'
```
Ask for chainId
```
curl -k -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"eth_chainId","id":1}' http://localhost:8545
```

**Comment by ligi** [comment]
seems to just happen for "--testnet" - got the correct results for --goerli and main net. Testnet will be deprecated soon anyway as of #20852 - but should still be fixed IMHO. Thanks for the report

**Comment by nicinuse** [comment]
Hi there,

running a geth client on main net

`geth --nousb --ws`

and trying to get the network id via ws api request returns "0x0" too.

```
wscat -c localhost:8546
Connected (press CTRL+C to quit)
> {"jsonrpc":"2.0","method":"eth_chainId","id":1}
< {"jsonrpc":"2.0","id":1,"result":"0x0"}
```

**Comment by ligi** [comment]
hm - very strange - for mainnet I get the correct result:
```

> {"jsonrpc":"2.0","method":"eth_chainId","id":1}
< {"jsonrpc":"2.0","id":1,"result":"0x1"}

```

**Comment by tyrion70** [comment]
Having no issues here on Ropsten either, @nicinuse could it be that your chain hasn't synced completely yet? If you try this on an unsynced chain you get the 0x0 result (not sure if thats correct behaviour @ligi though). Once the chain is synced it will give the right value.

**Comment by ligi** [comment]
for me it is also working when it is still syncing:

```
> {"jsonrpc":"2.0","method":"eth_syncing","id":1}
< {"jsonrpc":"2.0","id":1,"result":{"currentBlock":"0x3b927b","highestBlock":"0x8a61c9","knownStates":"0x0","pulledStates":"0x0","startingBlock":"0x3e2fc5"}}

> {"jsonrpc":"2.0","method":"eth_chainId","id":1}
< {"jsonrpc":"2.0","id":1,"result":"0x1"}
```

there must be something else to it. But I would also expect to give the correct result when it is still syncing.

**Comment by q9f** [comment]
> seems to just happen for "--testnet" - got the correct results for --goerli and main net.

does it also happen for `--ropsten`?

**Comment by ligi** [comment]
wasn't the "--ropsten" just included by your PR? Did not try it on top of this - but also do not see why this would be the reason.

**Comment by MariusVanDerWijden** [comment]
For me it works only for the `--goerli` testnet.
| command | output  |
|---|---|
|  `geth --nousb --ws ` | `< {"jsonrpc":"2.0","id":1,"result":"0x0"}`  |
| `geth --nousb --ws --rinkeby  | `< {"jsonrpc":"2.0","id":1,"result":"0x0"}`  |
| `geth --nousb --ws --testnet`  | `< {"jsonrpc":"2.0","id":1,"result":"0x0"}`  |
| `geth --nousb --ws --goerli`  | `< {"jsonrpc":"2.0","id":1,"result":"0x5"}`  |

**Comment by ligi** [comment]
The PR implementing this feature: https://github.com/ethereum/go-ethereum/pull/19694/files

**Comment by ligi** [comment]
currently it depends on the sync state - but IMHO it should just take the value from the config

**Comment by karalabe** [comment]
https://github.com/ethereum/go-ethereum/pull/17617
