### ISSUE TITLE
Minimum Gas Price option

### ISSUE THREAD

**Issue by aghamir** [ethereum/go-ethereum#20909]
Hi there,
### System information

Geth version: `1.9.12-stable-b6f1c8dc`
OS & Version: Linux

### Feature requested
I need an option same as gppercentile named gpminfee(I think there was in older version of geth) to offer gas price greater that the limit.

### What is my problem
I send too many transaction with 1Gwei fee. And therefore, I need to double spend that transactions.

**Comment by MariusVanDerWijden** [comment]
You can always optionally set the gas price that you're willing to pay, see: https://github.com/ethereum/wiki/wiki/JSON-RPC#parameters-24
Does that answer your question?

**Comment by aghamir** [comment]
That doesn't actually. I still want to use dynamic gas price calculation. However, I don't want it is lower than some threshold, for example, 10 Gwei.

**Comment by karalabe** [comment]
You can call `eth.gasPrice` to get a current dynamic number and then you can bump / decrease that at will.
