### ISSUE TITLE
Fatal: Error starting protocol stack: gap (#808500) in the chain between ancients and leveldb

### ISSUE THREAD

**Issue by teruyukisaito** [ethereum/go-ethereum#20912]
Hi there,

#### System information

Geth version: 1.9.12-stable-b6f1c8dc
OS & Version: OSX

#### Expected behaviour
Start geth console

#### Actual behaviour
Fatal: Error starting protocol stack: gap (#808500) in the chain between ancients and leveldb

#### Steps to reproduce the behaviour
$ geth --syncmode "full" --jitvm --cache=4096 --rpcapi admin,eth,net,web3,personal --datadir /Users/aaaa/Library/Ethereum/ 2>> /Users/aaaa/mainnet_data/e01.log &

$ geth console

After blockchain synchronization

> miner.start(2)

> exit

$ geth --syncmode "full" --jitvm --cache=4096 --rpcapi admin,eth,net,web3,personal --datadir /Users/aaaa/Library/Ethereum/ 2>> /Users/aaaa/mainnet_data/e01.log &

$ geth console

Fatal: Error starting protocol stack: gap (#808500) in the chain between ancients and leveldb

#### What you want to check

It's a coincidence, but I feel that the leveldb went wrong due to the exit.
Isn't geth supposed to exit in the first place?

I want you to tell me how to finish properly

**Comment by karalabe** [comment]
Hmm, the commands you specified are invalid, there's no such thing as `--jitvm` for the past 4 years. The CLI will reject it: 

```
$ geth --jitvm
flag provided but not defined: -jitvm
```

All in all that error means that your leveldb database (which stores the recent chain pieces) and the ancient database (which stores the old chain segments) don't match up. You either misconfigured your flags and leveldb and ancients point to mismatching chains, or somehow your databases are fried. If everything's correct, a resync will solve it.

Btw, which network are you on?

**Comment by karalabe** [comment]
Could you provide some logs that Geth prints? Was Geth in sync previously and it crashed?

**Comment by hmajidy2001** [comment]
I am also getting this error with geth 1.9.16 stable and unable to recover. Is the only option to dump dbs and start over?
Error message:
Fatal: Error starting protocol stack: gap (#5861013) in the chain between ancients and leveldb

**Comment by osizadmin** [comment]
I am also getting same error while start fast syncmode
