### ISSUE TITLE
Not able to Initialize Geth

### ISSUE THREAD

**Issue by HideomiOgata** [ethereum/go-ethereum#20910]
Hi there,

I want to use get on private net,but
It doesn't work well.How can I solve it?

#### System information

Geth version: `geth 1.8.3`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour
INFO  [] Successfully wrote genesis state

#### Actual behaviour
INFO  [] Mapped network port

#### Steps to reproduce the behavior

install geth→add to PATH→

#### Backtrace

`[backtrace]
`The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
ogatahideominoMacBook-Pro-79:~ hideomi$ geth version
Geth
Version: 1.8.3-stable
Git Commit: 329ac18ef617d0238f71637bffe78f028b0f13f7
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: darwin
GOPATH=
GOROOT=/Users/travis/.gimme/versions/go1.10.darwin.amd64
ogatahideominoMacBook-Pro-79:~ hideomi$  geth -datadir ~/geth/private_net/init ~/geth/private_net/genesis.json
INFO [04-13|17:55:31] Maximum peer count                       ETH=25 LES=0 total=25
INFO [04-13|17:55:31] Starting peer-to-peer node               instance=Geth/v1.8.3-stable-329ac18e/darwin-amd64/go1.10
INFO [04-13|17:55:31] Allocated cache and file handles         database=/Users/hideomi/geth/private_net/init/geth/chaindata cache=768 handles=1024
INFO [04-13|17:55:31] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: <nil> Engine: ethash}"
INFO [04-13|17:55:31] Disk storage enabled for ethash caches   dir=/Users/hideomi/geth/private_net/init/geth/ethash count=3
INFO [04-13|17:55:31] Disk storage enabled for ethash DAGs     dir=/Users/hideomi/.ethash                           count=2
INFO [04-13|17:55:31] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [04-13|17:55:31] Loaded most recent local header          number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [04-13|17:55:31] Loaded most recent local full block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [04-13|17:55:31] Loaded most recent local fast block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [04-13|17:55:31] Loaded local transaction journal         transactions=0 dropped=0
INFO [04-13|17:55:31] Regenerated local transaction journal    transactions=0 accounts=0
INFO [04-13|17:55:31] Starting P2P networking 
INFO [04-13|17:55:33] UDP listener up                          self=enode://c5bf6fe5888f6ac81f0f165dbc73386f9de555fc306acddea3876be0beefef92bb9f7930fcaa79d8937ef6bfa683ddc94d0a5ac54f578b8f3e1910d11dcde9a4@210.20.122.4:30303
INFO [04-13|17:55:33] RLPx listener up                         self=enode://c5bf6fe5888f6ac81f0f165dbc73386f9de555fc306acddea3876be0beefef92bb9f7930fcaa79d8937ef6bfa683ddc94d0a5ac54f578b8f3e1910d11dcde9a4@210.20.122.4:30303
INFO [04-13|17:55:33] IPC endpoint opened                      url=/Users/hideomi/geth/private_net/init/geth.ipc
INFO [04-13|17:55:33] Mapped network port                      proto=udp extport=30303 intport=30303 interface="UPNP IGDv1-IP1"
INFO [04-13|17:55:33] Mapped network port                      proto=tcp extport=30303 intport=30303 interface="UPNP IGDv1-IP1"`

**Comment by karalabe** [comment]
First up please use a recent release. The one you are using is super old.

Next, your command is wrong (the `init` command is written together with the datadir in your dump): ` geth -datadir ~/geth/private_net/init ~/geth/private_net/genesis.json`

Please leave a space before init `geth -datadir ~/geth/private_net init ~/geth/private_net/genesis.json`

**Comment by HideomiOgata** [comment]
karalabe

Thank you so much.
I am glad to inform you that the problem is now solved.

Hideomi
