### ISSUE TITLE
Served eth_getBlockByNumber err="context canceled" 

### ISSUE THREAD

**Issue by olhabilan** [ethereum/go-ethereum#20929]
#### System information

Geth version: 1.9.12-stable
OS & Version: Linux

#### Expected behaviour
Node is syncing and accessible  and there are no errors like that in logs:
`Apr 15 20:28:00 ip-10-10-0-1 geth[15961]: WARN [04-15|20:28:00.398] Served eth_getBlockByNumber              conn=127.0.0.1:38060 reqid=1104250 t=10.007163615s err="context canceled"`

#### Actual behaviour
a node can't be reached(Read timed out)  and in logs I can see only these lines:
`Apr 15 20:28:00 ip-10-10-0-1 geth[15961]: WARN [04-15|20:28:00.398] Served eth_getBlockByNumber              conn=127.0.0.1:38060 reqid=1104250 t=10.007163615s err="context canceled"`
After a restart, the problem disappears
#### Steps to reproduce the behaviour
Run geth version 1.9.12-stable with light syncmode

#### Backtrace

````
Apr 15 20:28:00 ip-10-10-0-1 geth[15961]: WARN [04-15|20:28:00.398] Served eth_getBlockByNumber              conn=127.0.0.1:38060 reqid=1104250 t=10.007163615s err="context canceled"
````

**Comment by rjl493456442** [comment]
We just fixed a deadlock issue in light client. https://github.com/ethereum/go-ethereum/pull/20828

Geth v1.9.13 is just released, could you please try it?

**Comment by olhabilan** [comment]
Thanks, I've updated to the new version.
If the problem appears again (I hope not), I'll reopen the ticket.
