### ISSUE TITLE
Performance measure for Rinkeby testnet network.

### ISSUE THREAD

**Issue by bayanhd** [ethereum/go-ethereum#20928]
I have a project into Ethereum blockchain by using the Rinkeby testnet network. The project aims to manage IoT devices ownership securely. I need to evaluate my project by analysing the model performance upon different criteria such as - Time of delay - Amount of gas (cost) - Transactions Per Second ...etc

My questions:

**Is there any way to measure these criteria by using the Rinkeby (testnet)?
<br>
Are there any tools that will help to measure and analyse the performance?**

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
