### ISSUE TITLE
Genesis allocation in RevertPrecompiledTouchExactOOG test

### ISSUE THREAD

**Issue by adria0** [ethereum/go-ethereum#20926]
I'm updating the test set for openethereum (develop branch) and there are some differences between OE and geth. I've been digging with the following tests:

- `RevertPrecompiledTouchExactOOG_d0g1v0_ConstantinopleFix`
- `RevertPrecompiledTouchExactOOG_d7g1v0_ConstantinopleFix`

both tests define a genesis Alloc from `0000…0001` to `0000…008` addresses (no code, no balance), and as the last step `0000…0001` is called in the first test and `0000…0008` is called in the second one.

With 94145 gas, the result is:
- first test calls `ecrecover`, and the `0000…0001` is removed from the state trie
- second test calls `alt_bn128`, OOGs, and the `0000…0008` address remains in the state trie

So, should not the genesis.alloc overwrite the current precompile space?

**Comment by holiman** [comment]
This wormhole goes very deep. Here's some good context: https://github.com/ethereum/EIPs/issues/716
