### ISSUE TITLE
Current total of state entries

### ISSUE THREAD

**Issue by AtomicLemon** [ethereum/go-ethereum#20939]
Hey everyone,

My geth node has been syncing on full mode for a few days now, I just wanted to know the total number of state entries.. I've googled a bit and some people say 33 Million and others say 300 Million+

I'm currently on around 237,000,000. How far off am I?

Thanks in advance :)

**Comment by karalabe** [comment]
Last number I've seen were around 450M. Sorry for the long sync time, we're working on a new mechanism but it takes a lot of effort.

**Comment by AtomicLemon** [comment]
Thanks, do they pull slower the higher the number? Or do they pull at a constant speed?

**Comment by AtomicLemon** [comment]
@karalabe Sorry for the mention, just kind of urgent for me

**Comment by karalabe** [comment]
Network latency wise should be the same independent how many you downloaded already. Generally on an AWS machine we can pull all states in in about 4 hours.

**Comment by AtomicLemon** [comment]
So do the states get bigger the more closer to the end we get?

**Comment by benslaney** [comment]
can anyone say roughly how many state entries there are now? for me it's at 690 million and still syncing, and i'm concerned that at the beginning it somehow started an archive node rather than a fast sync so now it's trying to do that. 

It's been syncing for nearly two weeks on digital ocean at this point, on a high spec vps

**Comment by AtomicLemon** [comment]
@benslaney Honestly at this point, no VPS really works anymore... Either use your own hardware or get a really big one at something like https://contabo.com/en/vps/. The 15 and 27 Euro ones work really well for me. (30/60GB RAM)

**Comment by benslaney** [comment]
ah thanks for that! just got a 60GB instance with the provider that you recommended, that looks like a great deal. AWS still seems to sync fine for me, so hopefully this will sync on this VPS and it's not a latency issue where the node likes to reside on AWS with basically zero latency with all the other nodes...

**Comment by AtomicLemon** [comment]
Ahh fair enough @benslaney. Let me know if you need help with anything else, I'm glad :)

**Comment by karalabe** [comment]
@benslaney Unfortunately fast sync currently is heavily limited by network latency and it places a significant serving time on the remote side too. There's a new sync algo that we're rolling out in the short term (been sitting on it for a year now), which will hopefully help in the future.
