### ISSUE TITLE
Connection attempts to TCP Port 0

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#20937]
#### System information

Geth version:
```
Geth
Version: 1.9.13-stable
Git Commit: cbc4ac264e9671898bff6ec7e434da3eca4bd273
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.2
Operating System: linux
GOPATH=
GOROOT=/build/ethereum-MOW1yG/.go
```
OS & Version: `Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-96-generic x86_64)`

#### Expected behaviour
Geth should reject and/or ignore nodes advertised as reachable on TCP Port 0 and not try to connect to them. It should not advertise on port 0 either (I don't know if it does? Might be other clients?)

#### Actual behaviour
Geth seems to have no issues trying to connect to remote IP addresses on TCP Port 0

#### Steps to reproduce the behaviour
I see these connection attempts at my firewall all the time, I assume just waiting for your node to try to connect to one would be enough.

**Comment by ligi** [comment]
That sounds reasonable - cc @fjl
