### ISSUE TITLE
Recovery from CRIT Failed to write block into disk ?

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#20943]
version    1.9.12-stable-b6f1c8dc

Is it possible to recover from Failed to write block into disk ?

```
Failed to write block into disk          err="open chaindata/005781.log: operation not permitted"
```
This was a temporary glitch I believe from my side and would be nice if restarting Geth, it was possible to recover from this point in time.

The next runs of Geth stop with fatal error:
```
INFO [04-18|16:46:53.616] Initialised chain configuration          config="{ChainID: 5 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 
0 Constantinople: 0 Petersburg: 0 Istanbul: 1561651, Muir Glacier: <nil>, Engine: clique}"
INFO [04-18|16:46:53.685] Initialising Ethereum protocol           versions="[65 64 63]" network=5 dbversion=7
WARN [04-18|16:46:53.695] Head state missing, repairing chain      number=2544958 hash=96b909…8f0bd9
INFO [04-18|16:46:53.875] Deep froze chain segment                 blocks=177 elapsed=285.522ms number=2454957 hash=85b977…198956
Fatal: Error starting protocol stack: missing block 2528964 [4b2c917702ba5c14eaf0823f2b28750f1a8fe86834ef562eff9b5eb3cdc4c4a1]
```

And the next one:
```
INFO [04-18|16:47:53.459] Initialising Ethereum protocol           versions="[65 64 63]" network=5 dbversion=7
WARN [04-18|16:47:53.463] Head state missing, repairing chain      number=2544958 hash=96b909…8f0bd9
Fatal: Error starting protocol stack: missing block 2529790 [9f09e359ef15dfbd29840cfd50de5acfa09029e5205ccf22fb1933afff53d965]
```

Is there a way to tell Geth to (re)request peers for the missing block/s, rather than giving up immediately?

**Comment by ethers** [comment]
i am currently trying #20067

**Comment by madnesspie** [comment]
I faced the same issue. Is there a solution except resync database as #14432 suggested?

**Comment by karalabe** [comment]
The only solution here is to resync. We're working on avoiding certain known cases that can lead to a data loss after a crash, but once it's messed up, there's no easy way out.

**Comment by karalabe** [comment]
I.e. we are even now trying to make recovery a bit smarter, but it's faster to not wait for it.
