### ISSUE TITLE
Transactions are not processed

### ISSUE THREAD

**Issue by olhabilan** [ethereum/go-ethereum#20950]
#### System information

Geth version: 1.9.13-stable
OS & Version: Linux

#### Expected behaviour
All submitted transactions go to ethereum network and I can see them by hash in etherscan.

#### Actual behaviour
A few of submitted transactions are in the pending list, some of them just disappear.
no one of them can be seen at etherscan and they are not processed.
In logs I can see that my transaction was submitted:
````
Apr 20 16:15:30 ip-10-10-0-1 geth[32359]: INFO [04-20|16:15:30.167] Submitted transaction                    fullhash=* recipient=*
````

#### Steps to reproduce the behaviour
Run geth client with the specified above version in light mode and try to create some transaction afterwhile.

#### Backtrace
There are no specific errors on logs, time to time I can see these lines except _Imported new block headers_
````
Apr 20 16:10:00 ip-10-10-0-1 geth[7923]: INFO [04-20|16:10:00.978] Looking for peers                        peercount=2 tried=8  static=11
Apr 20 16:27:22 ip-10-10-0-1 geth[6604]: WARN [04-20|16:27:22.904] Served eth_coinbase                      reqid=3 t=26.845µs err="mining is not supported in light mode"
````
We updated to the latest version 4 days ago, but the problem appears only today. A restart of the geth helps only for a few minutes. Also, the server is good in resources (load average is super small).

**Comment by olhabilan** [comment]
I downgraded to 1.9.12-stable version now and seems the current problem gone
but in 1.9.12 version I sometimes faces with [the issue regarding _ eth_getBlockByNumber err="context canceled"_](https://github.com/ethereum/go-ethereum/issues/20929), so I can't stay on this release too

**Comment by karalabe** [comment]
Could you check (and maybe provide details) as to the gas prices used, nonces, just to make sure those were correct. It also helps to check if you have stable light server connections or not (are blocks coming in reliably?).

Might want to also list the transactions in your local pool via `txpool.content` (I hope it's implemented for LES).

All in all we kind of need some infos, logs. The functionality should work, so let's try to find why it doens't.

**Comment by olhabilan** [comment]
Thanks for your response.
List of the transactions:
````
> txpool.content
{
  pending: {
    0x18ABE9101ACF9F07Cf348C915BE9FFeA8F317139: {
      1858: {
        blockHash: null,
        blockNumber: null,
        from: "0x18abe9101acf9f07cf348c915be9ffea8f317139",
        gas: "0x5208",
        gasPrice: "0x23f66cc89",
        hash: "0xc950041711c72f455a39eeb92cc033968feca4c5c209235b69fe576b3bdece09",
        input: "0x",
        nonce: "0x742",
        r: "0x687da7f8e45052d0c42171efe9448d8bdc1a952b911407e072ff676b43e0bd5d",
        s: "0x1dc324c5adeca1d3350be4f750918dc29a8e812b01336ee4b44e4b1e69a55124",
        to: "0x77191a26c438344c897291622c05f9c96c7998f7",
        transactionIndex: null,
        v: "0x1b",
        value: "0x283281982fa65a"
      },
      1859: {
        blockHash: null,
        blockNumber: null,
        from: "0x18abe9101acf9f07cf348c915be9ffea8f317139",
        gas: "0x5208",
        gasPrice: "0x24efc1b86",
        hash: "0xd47d5933142d1c7f9e8cd4fa33bd8da75bef43d1432b534dfb2d466f069d0524",
        input: "0x",
        nonce: "0x743",
        r: "0xf9d784ca205b074f27adf1bfc7a8291072520b14ed86cd778d4b8a291f8ee529",
        s: "0x4e7766618d10f792ed340e0424aae4c60b215c88c396bee7ef0a4ee8e738f469",
        to: "0x6d1dd9d9d5fd7dc66584d24be15b03ef3f7950f6",
        transactionIndex: null,
        v: "0x1c",
        value: "0x264d4a57a864b7"
      },
      1930: {
        blockHash: null,
        blockNumber: null,
        from: "0x18abe9101acf9f07cf348c915be9ffea8f317139",
        gas: "0x5208",
        gasPrice: "0x1874205ef",
        hash: "0x262bb8fd4a009abbcd738163df51609ede3045a63e8c48e35420f24656d4a491",
        input: "0x",
        nonce: "0x78a",
        r: "0x8ef7dbdb34e5054dffaf001920c266df58671bdc53b6bb5e702bd43a4265aab7",
        s: "0x5b260da2c5a1571c98cd0e90d7363c4d52126eeaf2ac20fb8d9625975e6a0bb4",
        to: "0x946e89e6d5e1dfd36cc47526d331bde53a43ea6d",
        transactionIndex: null,
        v: "0x1b",
        value: "0x905438e60010000"
      }
    }
  },
  queued: {}
}
````

**Comment by rjl493456442** [comment]
@olhabilan Does the issue still exist? The gasprice of the first pending tx is quite low, it's around 9GWei.

**Comment by holiman** [comment]
The sending-account has now nonce above `5K` (https://etherscan.io/address/0x18ABE9101ACF9F07Cf348C915BE9FFeA8F317139), so this issue has already been worked around -- most likely via replacing the low-priced transaction (because that one `0xc950041711c72f455a39eeb92cc033968feca4c5c209235b69fe576b3bdece09`) is not found on etherscan.
