### ISSUE TITLE
`--fakepow` flag is disregarded

### ISSUE THREAD

**Issue by lightclient** [ethereum/go-ethereum#20954]
#### System information

Geth version: `1.9.14`
OS & Version: Linux
Commit hash : ca22d076

#### Expected behaviour
Ethash initialized in `FakePow` mode.

#### Actual behaviour
Ethash initialized in normal mode.

#### Steps to reproduce the behaviour
```console
> geth init --datadir /some/path/here
...
> geth --datadir /some/path/here --fakepow

INFO [04-21|10:57:53.130] Starting Geth on Ethereum mainnet...
INFO [04-21|10:57:53.130] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [04-21|10:57:53.131] Maximum peer count                       ETH=50 LES=0 total=50
INFO [04-21|10:57:53.131] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [04-21|10:57:53.132] Starting peer-to-peer node               instance=Geth/v1.9.14-unstable-0d6c9ca4-20200417/linux-xxxxx/go1.13.4
INFO [04-21|10:57:53.132] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
INFO [04-21|10:57:53.132] Allocated cache and file handles         database=/some/path/here/geth/chaindata cache=2.00GiB handles=262144
INFO [04-21|10:57:53.151] Opened ancient database                  database=/some/path/here/geth/chaindata/ancient
INFO [04-21|10:57:53.151] Initialised chain configuration          config="{ChainID: 1337 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Engine: ethash}"
INFO [04-21|10:57:53.151] Disk storage enabled for ethash caches   dir=/some/path/here/geth/ethash count=3
INFO [04-21|10:57:53.151] Disk storage enabled for ethash DAGs     dir=/some/path/here/.ethash               count=2
INFO [04-21|10:57:53.151] Initialising Ethereum protocol           versions="[65 64 63]" network=1 dbversion=<nil>
```

**Comment by karalabe** [comment]
Hmm, the `--fakepow` flag is mostly use to benchmark EVM runs / block imports without spending time on PoW verification. I'm not entirely sure it's wise to expose it to a live node.

**Comment by lightclient** [comment]
If so, it might be helpful to make it clearer when `--fakepow` can be used, because the `help` print out indicates to me that it can be switched on for a live node. I'd be happy to submit an alternative PR which adds some clarification if desired.

The reason I'm trying to use it currently is that I'm trying to quickly sync a victim node to a certain block height, then exposing difference permutations of transaction announcements to benchmark the mempool. Do you have a preferred method for modeling performance regressions of changes I'm experimenting with in the mempool? Naively, I expected the best entry point for test attacks would be over the eth wire protocol -- as it is agnostic to the adversary.

**Comment by holiman** [comment]
We don't want to add a 'generic' way to disable PoW for users. Anyone who is sufficiently "advanced" to research about attacks can easily disable the PoW by modifying the code, but we don't want it to wind up being a "nifty trick to save some CPU".

**Comment by lightclient** [comment]
@holiman, that makes sense. In that case, does it make sense to clarify in the usage dialog when `--fakepow` is a valid flag?
