### ISSUE TITLE
Graceful shutdown if disk is full

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#20965]
this is a follow up of #20845

we should periodically monitor the free space on the disk we are operating on and if we fall under a certain limit we should gracefully shutdown the node to prevent database corruption

**Comment by holiman** [comment]
I think this is a fairly good first issue. The feature should: 
- Every N seconds, check the disk where the `datadir` resides, 
- If available space is `< some limit`, maybe `500Mb`, then start printing warnings

**Comment by HowJMay** [comment]
Let me take a look, and try to implement it!

**Comment by HowJMay** [comment]
> I think this is a fairly good first issue. The feature should:
> 
> * Every N seconds, check the disk where the `datadir` resides,
> * If available space is `< some limit`, maybe `500Mb`, then start printing warnings

@holiman So does this be two stage operation? Once the free space is under stage 1 limit then geth will start to print warnings. If the free space is keeping dropping until the stage 2 limit, then geth will graceful shutdown

**Comment by vyrwu** [comment]
I made a pull request that implements this: https://github.com/ethereum/go-ethereum/pull/21884.

Would appreciate some review comments and guidance, I'm new to this repository and still learning, thx. ✌️

**Comment by alex347** [comment]
Please review a new implementation: #22103

**Comment by holiman** [comment]
Fixed via https://github.com/ethereum/go-ethereum/pull/22103
