### ISSUE TITLE
Feature Request: flag so geth prefers nodes in the LAN

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#20964]
this flag can be useful for events/hackathons that have limited bandwidth. They can then tell their participants when they run geth that they should use this flag. Basically it is the opposite to the current behavior that filters out LAN nodes.

cc @fjl would like to hear your take on this

**Comment by fjl** [comment]
This could be solved by adding local network discovery via broadcasts, for example. With the current protocols, it's not really possible to implement this idea.

**Comment by MariusVanDerWijden** [comment]
Maybe we can use the TrustedNodes feature to provide a list of pre-synced trusted node in lan that people can connect to

**Comment by MariusVanDerWijden** [comment]
e.g. all nodes have to enable `--nodiscover` and add the "masternode" with `admin.AddPeer`

**Comment by MariusVanDerWijden** [comment]
I think this can be achieved by using `admin.AddPeer` in order to preferably connect to local peers. Don't think that we need a separate feature for this. Closing this for now, feel free to reopen if you disagree
