### ISSUE TITLE
SubscribeMessages not working on android

### ISSUE THREAD

**Issue by rohankeskar19** [ethereum/go-ethereum#20966]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.9.13`
OS & Version: Android
Commit hash : (if `develop`)

#### Expected behaviour
Subscribe messages should give messages on receiving messages, I'm using geth for android and I'm trying to use the subscribe messages function for subscribing to whisper messages, But when I use it it doesn't outputs any messages on receiving new messages, I'm sending a message from an go program both the android app and the go program are connected to same remote node which I'm running on aws, When I send a message from the go program the onNewMessage call back is not getting executed, And also the NewMessage object which has a member function setPublicKey
accepts a byte array as an parameter but the problem is that in java you can't convert hex characters to byte which are greater than 127, Because bytes in java are signed and then golang gives error as invalid public key, So you need to set the parameter as string and convert the string to byte inside golang, And please help me as quick as possible regarding the subscribe messages, I would really appreciate it

```
MainActivity.java
Context context = Geth.newContext();

            Criteria criteria = Geth.newCriteria("Ethereum Chat".getBytes());

            criteria.setPrivateKeyID("d31618391bcd8e3accb8bf7daf08aa7483933c8be91913e7a5d0b108a9c56ae4");

            ChatMessageHandler chatMessageHandler = new ChatMessageHandler();
whisperClient.subscribeMessages(context, criteria, chatMessageHandler,1000);

ChatMessageHandler.java
public class ChatMessageHandler  implements NewMessageHandler {

    private static final String TAG = "ChatMessageHandler";
    @Override
    public void onError(String s) {
        Log.d(TAG, "onError: " + s);
    }

    @Override
    public void onNewMessage(Message message) {
        Log.d(TAG, "onNewMessage: New message arrived");
        Log.d(TAG, "onNewMessage: " + new String(message.getPayload()));
    }
}


``` 

#### Actual behaviour
In subscribe message the callback is not getting called

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
can you provide the full source?

**Comment by ligi** [comment]
also to convert a hex string to a bytearray you can e.g. use: https://github.com/komputing/KHex/blob/master/extensions/src/main/kotlin/org/komputing/khex/extensions/HexStringExtensions.kt#L15
It is no problem for the private key that the values become negative. It is just another representation of the 8 bit.

**Comment by rohankeskar19** [comment]
> can you provide the full source?

https://github.com/rohankeskar19/Ethereum-Chat this is the repo

**Comment by adamschmideg** [comment]
Whisper is discontinued, we're moving it to its own repo and not touch it in the near future. You may want to check out https://vac.dev/ for p2p messaging instead.
