### ISSUE TITLE
Light client can't send `GetHeader` request if there is no CHT

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/go-ethereum#20989]
When the light client wants to retrieve some headers from the network, it needs the CHT to verify the response. 

But the issue is if there is no CHT generated(chain height is less than 32768), light client has nothing to verify. Now it just refuses to send this kind of request.

How can we resolve this issue?

**Comment by rjl493456442** [comment]
Wondering whether the issue really exists(need to check). If there is no CHT, then the light client should sync all headers from genesis.  
In this case, we should be able to verify the response through the local headers.

**Comment by alialthaibani** [comment]
ليه

**Comment by MariusVanDerWijden** [comment]
We recently removed the light client code, closing this
