### ISSUE TITLE
[core/state] State dumper skips the 0x000..000 account even if it is present in the state

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ethereum/go-ethereum#20981]
This commit fixed it for me: https://github.com/ledgerwatch/go-ethereum/commit/9061bd66392a724a94367886b576a679cc6187a1

The current code uses empty address as an indication that preimage retrieval failed. But this approach means that if preimage is legitimately an empty address, this record will be wrongly excluded

**Comment by holiman** [comment]
I hit the same issue when implementing `statet8n` tool. This fixed it for me: https://github.com/ethereum/go-ethereum/pull/20958/commits/16d72c5ee76252798d47ad9eafd64b98da58b302

**Comment by holiman** [comment]
@AlexeyAkhunov thanks for the ticket, we'll cherry-pick your fix!
