### ISSUE TITLE
Invalidate transactions with useless 0x0 bytes at the end of a transaction

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#210]
Transactions with the data field ending with 0x00s should be invalidated and rejected.

**Comment by winsvega** [comment]
that would conflict with ABI specification
https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI

**Comment by CJentzsch** [comment]
More importantly, it conflicts with the YP. People are allowed to add as many 0's as they want, as long as they pay the gas for doing so.

**Comment by obscuren** [comment]
Very old issue.
