### ISSUE TITLE
questions of reexec

### ISSUE THREAD

**Issue by strongpower** [ethereum/go-ethereum#21005]
I have a question of [Release note v1.8.0](https://github.com/ethereum/go-ethereum/releases/tag/v1.8.0)

>  Alternatively, specify the "reexec" tracer option to allow regenerating historical state; and ideally switch to chain tracing which amortizes overhead across all traced blocks.

I did't see the docs of how to do that.

I found related answer [here](https://ethereum.stackexchange.com/questions/40648/full-node-sync-only-preserve-the-last-128-history-states), but it didn't answer my question.

#### System information

Geth version: `v 1.9.11`
OS & Version: OSX

**Comment by holiman** [comment]
Some docs are here: https://geth.ethereum.org/docs/rpc/ns-debug

What is the question exactly? How to set pass the parameter? Could you paste your query here?

**Comment by holiman** [comment]
and https://geth.ethereum.org/docs/dapp/tracing , but that doesn't really go into `reexec`

**Comment by adamschmideg** [comment]
The current documentation is https://geth.ethereum.org/docs/dapp/tracing It does need improvement, though.

**Comment by coinwalletdev** [comment]
Bump for this issue. 
Currently experimenting with this (https://ethereum.stackexchange.com/questions/85298/best-way-to-sync-a-node-to-use-tracetransaction-in-go-ethereum), the doc is not really clear.

**Comment by MariusVanDerWijden** [comment]
An example for correct usage:
```
debug.standardTraceBlockToFile("0x6c0f5361d0161200637472a98e6514bb479e18fcde4685a016fd5a6d7d6e0069", {txHash:"0x5826b1d1a53befc97a3ad5e8eb909b201a7b6ec3e59ef45d8bfc0b1061bf0125", disableMemory:false, reexec:6000000})
```
we'll update the docs soonish

**Comment by Undead8** [comment]
Looks like `reexec` can be very useful. Is there any way to specify a `reexec` value when making a call using web3?

**Comment by MariusVanDerWijden** [comment]
@Undead8 I don't think so
