### ISSUE TITLE
How to change web3 version?

### ISSUE THREAD

**Issue by Kindhearted57** [ethereum/go-ethereum#21016]
#### System information

Geth version: `1.9.13-stable-cbc4ac26`
OS & Version: Linux Ubuntu 18.04

#### Expected behaviour

I can get the `status` field from the json response.

#### Actual behaviour

`status` is missing.

#### Steps to reproduce the behaviour

I started Geth on my private chain and made one transaction. When I run `eth.getTransactionReceipt(transactionHash)` in the console, here is the result.
```
{
  blockHash: "0x5a083fee180cd7ae1a0a5c184463e87069a477fe5f850a41f5d51ee4bf8b6983",
  blockNumber: 76,
  contractAddress: "0x302fba66c257a43f89b715322eb83d51da5192ef",
  cumulativeGasUsed: 117363,
  from: "0x8b8d9f7b3a3e4ca173edc06c68698c7b228433d7",
  gasUsed: 117363,
  logs: [],
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  root: "0xe40331cf3f7ceb494dffffc3f8aaee3a3cbbc303fc027e5f3a6395ca2d53c79c",
  to: null,
  transactionHash: "0xd8a4e95c93176189fcd153738ee6fd1a6188090434f056177d141299d40537aa",
  transactionIndex: 0
}
```

I learned from [this issue](https://github.com/ethereum/web3.js/issues/2410) in web3.js that there was a bug in the previous release of web3.js. So I think maybe change web3 version manually to v1.xxx can solve this problem. So is there any way to change web3 version?

**Comment by karalabe** [comment]
The Geth console uses an ancient web3.js. v1.0.0 changed from a blocking API to async calls and callbacks, which is not compatible with the console requirements. There are also some other annoyances that prevent us from updating web3.js.

All in all, the console is mostly a developer help tool, allows some basic functionality with managing a Geth node and inspecting the chain. If you want to run live meaningful code against Geth however, please run an external node.js environment and use an up to date web3.js.
