### ISSUE TITLE
geth CHT request behavior does not match LES spec 

### ISSUE THREAD

**Issue by iCodeSometime** [ethereum/go-ethereum#21019]
#### System information

Geth version: 1.9.13-unstable
OS & Version: Windows 10
Commit hash : 510b6f9

#### Expected behaviour
According to the [LES specification](https://github.com/ethereum/devp2p/blob/master/caps/les.md), the CHT sections are divided into sections of 32768, such that 

> CHT[i] containing data for blocks 0..i * 32768-1
> header number N (where N < i * 32768)

In the ropsten trusted checkpoint, the sectionIndex is 223, so the highest numbered block in that section should be 234 * 32768 - 1 = 7667711. 
 
#### Actual behaviour

The SectionHead hash stored with section 234 in the checkpoint, is for block number 7700479.
This seems consistent with an off by one error in either the application or documentation.

e.g.
> CHT[i] containing data for block 0..(i + 1) * 32768 - 1

#### Steps to reproduce the behaviour

1. `geth --ropsten --syncmode light --verbosity 4`
2. View logs requesting CHT 234, block 7700479

edit: updated block and cht numbers to match the commit hash referenced.

**Comment by karalabe** [comment]
@rjl493456442 Could you take a peek?

**Comment by rjl493456442** [comment]
I don't understand your issue. 

The `sectionIndex` for ropsten is 234 https://github.com/ethereum/go-ethereum/blob/master/params/config.go#L113, it means there are 235 sections in total, so the head should be `235 * 32768 - 1 = 7700479`

**Comment by rjl493456442** [comment]
Ah, you mean the spec, yes, it's wrong. I'll fix it

**Comment by rjl493456442** [comment]
The fix for spec is here https://github.com/ethereum/devp2p/pull/149/. 

Thanks @iCodeSometime  for pointing out!
