### ISSUE TITLE
fatal error: unexpected signal during runtime execution (1.9.13, Windows)

### ISSUE THREAD

**Issue by remyroy** [ethereum/go-ethereum#21011]
#### System information

Geth version: `geth version`
```
Version: 1.9.13-stable
Git Commit: cbc4ac264e9671898bff6ec7e434da3eca4bd273
Git Commit Date: 20200416
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.2
Operating System: windows
GOPATH=
GOROOT=C:\go
```
OS & Version: Windows 10
Commit hash : 1.9.13 release

#### Expected behaviour
No crash during normal usage while using the console to get the lastBlock

#### Actual behaviour
Crashed during normal usage.

#### Steps to reproduce the behaviour
- Start geth 1.9.13 with the following command line: `geth.exe --ipcdisable --verbosity 1 --light.serve 10 console`
- Perform some commands in console
- Type `Date(web3.eth.getBlock('latest').timestamp*1000)` in console
- Notice the fatal error

#### Backtrace

See https://gist.github.com/remyroy/f641f1bcbf89066fa8ef983eab3267de for the full backtrace

**Comment by karalabe** [comment]
I've tried a Goerli node on Windows. Seems to work for me, console response. I've tried to run you code and it also works.

Btw, funky, Date() returns the current time, irrespective of arguments for me.

**Comment by gballet** [comment]
@remyroy we are not able to reproduce the problem and need more details.

Are you synced, and does it happen if you just call `web3.eth.getBlock('latest')` ?

**Comment by remyroy** [comment]
I'm synced with the latest block.

`web3.eth.getBlock('latest').timestamp` = 1588859812
`web3.eth.getBlock('latest').number` = 10019525
`web3.eth.syncing` = false

Calling `web3.eth.getBlock('latest')` returns something valid. I'll try just calling that to see if it crashes. 

This issue is not consistent and I'm not sure what are the real steps to reproduce it. It happened 5 or 6 times in the last week but I'll see if I can get more information the next time it happens.

**Comment by remyroy** [comment]
After some time, the console gets unresponsive. I killed the geth process and restarted it. I typed `web3.eth.getBlock('latest')` and I got the fatal error again.

See this gist for the backtrace: https://gist.github.com/remyroy/d9936b558e89ffe4f11d9a3619eef017

**Comment by adamschmideg** [comment]
Can you do a memory check please
