### ISSUE TITLE
FR: Database over network

### ISSUE THREAD

**Issue by cerealkill** [ethereum/go-ethereum#21024]
### Intro/Problem
Hi Geth team, first of all, thanks for the great work. I run Nethermind on a VPS and my instance has run out of storage. Unfo the provider doesn't offer larger instances, but offers storage instances that I can connect over NFS/SMB or any other network-file-system.
### Feature
Execute the client with recent blocks on one storage and use a remote database to scale. Best if the user can determine when the  database starts storing on execution. i.e. 
`mainnet.cfg`
```json
{
...
"RemoteDBURL": "192.168.2.43:134",
"RemoteDBFromLatest": 50,
...
}
```
This would start storing blocks on this second, remote, slower database.
### Dream feature
The best scaling scenario would be to have multiple storages that can be added later, as chains get larger, and benefit from paralellism, maybe even redundancy, IPFS-style.
i.e. 
`mainnet.cfg`
```json
{
...
"RemoteDBEnabled": true,
"RemoteDBFromLatest": 50
"RemoteDBConfig: [
  {"RemoteDBIndex": 0,
    "RemoteDBURL": "192.168.2.43:134",
    "RemoteDBCapacity": 10001337
  },
  {"RemoteDBIndex": 1,
    "RemoteDBURL": "192.168.2.45:134",
    "RemoteDBCapacity": 1337
  }],
...
}
```

**Comment by holiman** [comment]
Hi, 
The go-ethereum repository is the repo for the `geth` client. For `nethermind`, file a ticket here instead: https://github.com/NethermindEth/nethermind 

In general, the feature you describe is not really doable. A client needs to have a very fast lookup of state. Geth does have the ability to place old blocks into a so called 'ancient' folder, which can reside on an NFS share, or an HDD.
