### ISSUE TITLE
make cannot find packages (cespare/cp, go-ethereum/internal/build, go-ethereum/params)

### ISSUE THREAD

**Issue by dchmelik** [ethereum/go-ethereum#21029]
#### System information

Geth version: none yet (want to make for first time: make error)
OS & Version: Kubuntu 18.04.1 LTS (yes, I know 20.04 LTS is out, but w/no AMDGPU-PRO yet...)

#### Expected behaviour

make

#### Actual behaviour

```
d@1.cosmos:~/go-ethereum$ make
env GO111MODULE=on go run build/ci.go install ./cmd/geth
build/ci.go:61:2: cannot find package "github.com/cespare/cp" in any of:
        /usr/lib/go-1.10/src/github.com/cespare/cp (from $GOROOT)
        /home/d/go/src/github.com/cespare/cp (from $GOPATH)
build/ci.go:62:2: cannot find package "github.com/ethereum/go-ethereum/internal/build" in any of:
        /usr/lib/go-1.10/src/github.com/ethereum/go-ethereum/internal/build (from $GOROOT)
        /home/d/go/src/github.com/ethereum/go-ethereum/internal/build (from $GOPATH)
build/ci.go:63:2: cannot find package "github.com/ethereum/go-ethereum/params" in any of:
        /usr/lib/go-1.10/src/github.com/ethereum/go-ethereum/params (from $GOROOT)
        /home/d/go/src/github.com/ethereum/go-ethereum/params (from $GOPATH)
Makefile:16: recipe for target 'geth' failed
```

#### Steps to reproduce the behaviour

unsure

#### Backtrace

If that's necessary to do here, and documented, I will do it.

**Comment by ligi** [comment]
Please update your go-version. README states you need 1.13 (https://github.com/ethereum/go-ethereum#building-the-source) - but it seems you have 1.10 installed

**Comment by dchmelik** [comment]
Sorry (if only those .md files on GitHub had a .txt version; ) worked after that (though unsure what to do as there's no ‘make install.’)

**Comment by karalabe** [comment]
Geth is a single binary. If you build it via `make`, it will put the binary in `builb/bin/geth`. You can move that to another location if you wish, or you could add this folder to your `PATH`.
