### ISSUE TITLE
node crashes after [libsecp256k1] illegal argument: recid >= 0 && recid <= 3

### ISSUE THREAD

**Issue by simon-jentzsch** [ethereum/go-ethereum#2103]
Version:

Geth
Version: 1.3.1
Git Commit: e5532154a50114d5ffb1ffd850b746cab00cb899
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=/root/go
GOROOT=/usr/local/go

[gocrash.txt](https://github.com/ethereum/go-ethereum/files/77057/gocrash.txt)

**Comment by fjl** [comment]
This is fixed in geth 1.3.2.

**Comment by simon-jentzsch** [comment]
Thanks, I'll update
