### ISSUE TITLE
JSON RPC do not handle Connection: close

### ISSUE THREAD

**Issue by ang-st** [ethereum/go-ethereum#21048]
#### System information

Geth
Version: 1.9.12-stable
Git Commit: b6f1c8dcc058a936955eb8e5766e2962218924bc
Git Commit Date: 20200316
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.8
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

#### Expected behaviour
JSON RPC server should handle `Connection: close` and release socket

#### Actual behaviour

Geth let socket open even after client close the connection causing the OS handling it through `CLOSE_WAIT` `TIME_WAIT` mechanism 

#### Steps to reproduce the behaviour
Issue thousands requests in order to exhaust file descriptors (not sure it is FD as i'm below system limit).

At some point rpc responds erratically 

```
 netstat -naltp | grep TIME|wc -l
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
0

```

```
netstat -naltp | grep TIME|wc -l
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
13673
```

**Comment by fjl** [comment]
We rely on the Go standard library HTTP server. I think this server handles Connection: close correctly. Which client implementation are you using?

**Comment by karalabe** [comment]
Go has quite a number of default parameters around idle connection tracking per host, globally, etc. https://golang.org/src/net/http/transport.go And other also reported issues with TIME_WAIT in strange scenarios: http://tleyden.github.io/blog/2016/11/21/tuning-the-go-http-client-library-for-load-testing/

@ang-st Could you detail how many hosts, how many requests you are hitting Geth with? We may be able to tweak things, but need to know what's failing exactly first.

**Comment by ang-st** [comment]
@karalabe 
- I used a single host and `bluebird` `Promise.map` using web3js client with 10 request per map
- I then noticed that web3js was sending `Connection: keep-alive` so i hacked the underlying library `xhr2-cookies/dist/xml-http-request.js` in order to force it to send `Connection: close`

I had something like 100 000 balance to query (both ethereum and ERC20 one).

I finally dropped `Promise.map` and iterated one by one up to completion, i still had more than 8000 TIME_WAIT connection by the time the script finished

I'm sorry i can't come with a reproducer as I completely removed the `Promise.map` part from my script but roughly it was an async for loop  chunking a large array per 10 block requesting `web3.eth.getBalance` and `web3.eth.call(balanceOfPayload)`

**Comment by holiman** [comment]
Wait what? Why did you hack it to disable connection reuse? That sounds very wrong, unless I completely misunderstand something here.

**Comment by holiman** [comment]
Unless you did it only to repro the issue, you should undo that hack again: https://en.m.wikipedia.org/wiki/HTTP_persistent_connection

**Comment by ang-st** [comment]
With either header (close or keep-alive) the behaviour is the same, i could not eliminated that could come from web3js.
And yes indeed that's just for testing purpose.

**Comment by holiman** [comment]
Closing this. We use the standard stuff, and if I understand correctly, the caller was issuing tons of requests using connection `keep-alive`, so it seems not an error on the server side.
