### ISSUE TITLE
Unable to start after fresh installation

### ISSUE THREAD

**Issue by gusarov** [ethereum/go-ethereum#21054]
Hi there,

I just decided to start from scratch. Created new fresh VM, downloaded latest geth version, installed and I got 2 lnk files in start menu: one with "attach" the other with "--fast" arguments.
Neither of them works!
```
C:\Program Files\Geth>"C:\Program Files\Geth\geth.exe" --fast
Incorrect Usage. flag provided but not defined: -fast

C:\Program Files\Geth>"C:\Program Files\Geth\geth.exe" attach
Fatal: Unable to attach to remote geth: no known transport for URL scheme "c"
```

#### System information

Geth version: `Version: 1.9.13-stable amd64`
OS & Version: Windows
Commit hash : cbc4ac264e9671898bff6ec7e434da3eca4bd273

#### Expected behaviour
I expect that after clean installation user can use regular lnk files.

#### Actual behaviour
Both lnk files failed.

#### Steps to reproduce the behaviour
Just make fresh installation of the latest version

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
I guess you want `--syncmode` fast instead of `--fast`

**Comment by gusarov** [comment]
Honestly, I want a software that works out of the box. The bug report here is not about commandline, it is about LNK that is installed by official installer.

**Comment by ligi** [comment]
Ah - now I see #21055 should fix the syncmode problem. Not yet sure why attach on windows throws this weird error.
