### ISSUE TITLE
Can not run Geth anymore!

### ISSUE THREAD

**Issue by mbsaberi** [ethereum/go-ethereum#21052]
#### System information

Version: 1.9.12-stable
Git Commit: b6f1c8dcc058a936955eb8e5766e2962218924bc
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.8
Operating System: linux
GOPATH=
GOROOT=/build/ethereum-YoJS3q/.go

#### Expected behaviour
I am not able to run Geth anymore! Previously, when I was usign the command below, I could start Geth:  
```
geth --syncmode full --rpc --rpcport 2555 --rpcapi personal,eth,web3,txpool,net
```

#### Actual behaviour
Now, when I run the same command, I receive this output and everything stop:  
```
WARN [05-09|17:14:14.571] Sanitizing cache to Go's GC limits       provided=16384 updated=5220
INFO [05-09|17:14:14.574] Maximum peer count                       ETH=50 LES=0 total=50
INFO [05-09|17:14:14.574] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [05-09|17:14:14.576] Starting peer-to-peer node               instance=Geth/v1.9.12-stable-b6f1c8dc/linux-amd64/go1.13.8
INFO [05-09|17:14:14.576] Allocated trie memory caches             clean=1.27GiB dirty=1.27GiB
INFO [05-09|17:14:14.576] Allocated cache and file handles         database=/mnt/geth/chaindata cache=2.55GiB handles=524288
```
The stranger point is that I have some command running in background. But when I use `geth attach` command, I receive this error:  
```
Fatal: Failed to start the JavaScript console: api modules: Post http://127.0.0.1:2555: dial tcp 127.0.0.1:2555: connect: connection refused
```

**Comment by holiman** [comment]
Try adding higher verbosity level and provide the start-up logs

**Comment by mbsaberi** [comment]
This is the output after using --verbosity 5:  
```
WARN [05-10|10:57:48.101] Sanitizing cache to Go's GC limits       provided=16384 updated=5220
DEBUG[05-10|10:57:48.101] Sanitizing Go's GC trigger               percent=20
INFO [05-10|10:57:48.104] Maximum peer count                       ETH=50 LES=0 total=50
INFO [05-10|10:57:48.104] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
DEBUG[05-10|10:57:48.104] FS scan times                            list=74.374µs set=5.564µs diff=3.183µs
TRACE[05-10|10:57:48.104] Handled keystore changes                 time=59.934µs
TRACE[05-10|10:57:48.105] Started watching keystore folder         path=/mnt/keystore
INFO [05-10|10:57:48.107] Starting peer-to-peer node               instance=Geth/v1.9.12-stable-b6f1c8dc/linux-amd64/go1.13.8
INFO [05-10|10:57:48.107] Allocated trie memory caches             clean=1.27GiB dirty=1.27GiB
INFO [05-10|10:57:48.108] Allocated cache and file handles         database=/mnt/geth/chaindata cache=2.55GiB handles=524288
```

**Comment by holiman** [comment]
Does it exit on ctrl-c? Or does it eventually crash? Stack trace from crash?

**Comment by mbsaberi** [comment]
@holiman when I run the code above, it stops with the mentioned output, while background processes start to run, but there is not any access to Geth usign `attach`. I tested running command on another path for test, and Geth started again successfully. However, I should run geth on the previous and main path. I don't know what is the issue

**Comment by holiman** [comment]
Right, but when you run that, the process hangs, correct?If so, how do you eventually get it killed? Via ctrl-c?

**Comment by mbsaberi** [comment]
Yes it is correct. The process hangs and keep taking this situation until I press `Ctrl+C`. Although, I tried to kill the process using `killall -HUP geth` too.

**Comment by holiman** [comment]
And ctrl-c just exits it nicely? No stack trace?

**Comment by mbsaberi** [comment]
Nothing happens after `Ctrl+C`. Everything get stopped and the background processes end.

**Comment by holiman** [comment]
You reported that your command was `geth --syncmode full --rpc --rpcport 2555 --rpcapi personal,eth,web3,txpool,net` -- but that's not all, is it? 
You seem to have both keystore and datadir on `/mnt`, so either you're using some more arguments, or a toml file? 
I'm thinking that there may be some problems if geth tries to open a unix socket on a mount point which is across a filesystem boundary, where the other filesystem is some form of network filesystem, like ntfs. Is that the case? 
And secondly, could you try _not_ doing that, and see if it boots up ok?
