### ISSUE TITLE
DisableSeeksCompaction option of leveldb

### ISSUE THREAD

**Issue by ucwong** [ethereum/go-ethereum#21069]
```
DisableSeeksCompaction : true
```
Why disable seek compaction of leveldb, is it ok to false it

**Comment by MariusVanDerWijden** [comment]
Seems to be faster without seek compaction, see: https://github.com/ethereum/go-ethereum/pull/20130

**Comment by ucwong** [comment]
![image](https://user-images.githubusercontent.com/22344498/81783834-8a53bf80-952e-11ea-93df-9b3fcdba02a2.png)
@MariusVanDerWijden Thank you for comment. The green/yellow line is represent of disable seeking compaction on the chart above?

**Comment by ligi** [comment]
can we close this? Seems to be not actionable
