### ISSUE TITLE
[swarm] Swap pricing

### ISSUE THREAD

**Issue by nagydani** [ethereum/go-ethereum#2107]
The semantics of the price set in the configuration (and later in a user friendly interface) must be the amount ASKED for settlement, if the other party goes into debt.

Rationale: a node knows their bandwidth costs, so if you are providing swarm service for profit, you buy bandwidth from, say, Amazon (in dollars) and sell it to swarm users (for ethers) and there is a market exchange rate to which you can refer. As a user of the service, the value of the information you are requesting is entirely subjective and you just want to get it as cheaply as possible. Thus, you cannot make an informed decision on the price you are willing to pay and it probably changes from download to download anyway.

Detailed mode of operation: One chunk is still worth one chunk, any debt can be settled by immediate reciprocal service. However, if one party goes very deeply in debt, the amount in ether in which that debt can be settled can be different depending on the direction of the disbalance. The ASK price must be part of the handshake and changes in this price (which are very infrequent) can be communicated by disconnecting and re-connecting with a new handshake.

**Comment by zelig** [comment]
https://github.com/ethereum/go-ethereum/issues/2960
https://github.com/ethereum/go-ethereum/issues/2961
