### ISSUE TITLE
Unclean (or extremely slow) shutdown

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#21087]
When the shutdown sequence was redesigned, a regression was introduced. 

The new shutdown mechanism is designed to "close from bottom up", with the pretty sensible idea to stop the peering, stop the downloader and 'starve' the upper protocols. However, while we're waiting for the downloader goroutines to exit, there's a dependency to a upper layer which causes problems. 

When a node is catching up, the downloader delivers blocks in batches of `2048` to it. And therefore, the processfullsyncContent goroutine cannot exit until the blockchain has slogged through maybe  `2000` blocks, which can take 400s (for 200ms blocks) and up to several thousand seconds.  

I guess this worked fine when we just shut down the blockchain. 

Some logs from a very very slow bootnode (5 second block times): 
```
May 14 23:22:44 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:44.837] Got interrupt, shutting down...
May 14 23:22:44 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:44.838] IPC endpoint closed url=/root/.ethereum/geth.ipc
May 14 23:22:44 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:44.838] Stopping protocol manager
May 14 23:22:44 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:44.838] protocol manager tx sync loop exiting
May 14 23:22:44 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:44.838] chainsyncer received quit signal
May 14 23:22:44 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:44.838] protocol manager, minedBroadcastLoop loop exiting
May 14 23:22:44 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:44.838] protocol manager, txBroadcastLoop loop exiting
May 14 23:22:44 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:44.838] chainsyncer terminating downloader
May 14 23:22:44 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:44.838] Downloader closed quitCh
May 14 23:22:44 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:44.838] Downloader calling 'cancel'
May 14 23:22:44 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:44.838] Downloader waiting for wg
May 14 23:22:44 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:44.838] processHeaders terminated
May 14 23:22:46 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:46.960] Imported new chain segment blocks=7 txs=856 mgas=69.874 elapsed=8.265s mgasps=8.453 number=10061486 hash="e74420…29ee1b" remaining=1369 age=19h20m42s dirty=342.14MiB
May 14 23:22:55 bootnode-aws-us-east-1-001 geth INFO [05-14|21:22:55.471] Imported new chain segment blocks=8 txs=1318 mgas=79.745 elapsed=8.511s mgasps=9.370 number=10061494 hash="1d559a…fb4408" remaining=1361 age=19h19m16s dirty=346.22MiB
May 14 23:23:05 bootnode-aws-us-east-1-001 geth INFO [05-14|21:23:05.025] Imported new chain segment blocks=7 txs=884 mgas=59.867 elapsed=9.554s mgasps=6.266 number=10061501 hash="2b8893…a3cc81" remaining=1354 age=19h18m42s dirty=349.41MiB
May 14 23:23:14 bootnode-aws-us-east-1-001 geth INFO [05-14|21:23:14.000] Imported new chain segment blocks=11 txs=1543 mgas=79.728 elapsed=8.975s mgasps=8.883 number=10061512 hash="48bca9…a8556b" remaining=1343 age=19h15m58s dirty=348.86MiB
May 14 23:23:24 bootnode-aws-us-east-1-001 geth INFO [05-14|21:23:24.823] Imported new chain segment blocks=7 txs=1019 mgas=69.732 elapsed=10.822s mgasps=6.443 number=10061519 hash="77b36c…2021fd" remaining=1336 age=19h14m37s dirty=351.87MiB
May 14 23:23:34 bootnode-aws-us-east-1-001 geth INFO [05-14|21:23:34.028] Imported new chain segment blocks=7 txs=912 mgas=59.887 elapsed=9.204s mgasps=6.506 number=10061526 hash="8abf42…b5bcd5" remaining=1329 age=19h12m42s dirty=353.18MiB
```

As you can see, with some added logs, the block importer has `remaining=1329` in the current batch which was delivered from the downloader. And not until all of those have been processed does the downloader get a chance to check the quitCh, exit, and complete the waitgroup that we're waiting for. 

Potential fixes: 
- Adapt the batch size, let downloader 'tune' the size so the task completes in ~10 seconds, 
- Give the downloader a time limit to terminate, but proceed anyway with other shutdown tasks if it fails. 
- Pass some channel or context from downloader into the blockchan (ugh)

Related: https://github.com/ethereum/go-ethereum/issues/20975

**Comment by turboboost55** [comment]
I've seen this twice the last few days.  Tried to shutdown geth while it was "catching up" (the node had been turned off for a few hours).  It took about 20 minutes to shutdown.
