### ISSUE TITLE
Run geth import is very very slow.

### ISSUE THREAD

**Issue by tyrone98** [ethereum/go-ethereum#21089]
I run the geth import for importing recently blocks.
``` shell
geth --datadir /chain/geth import blocks
```

But importing is extremely slow.
.. blocks=1 txs=103 mgas=9.983 elapsed=**1m4.304s** mgasps=0.155 number=10015904 ..
.. blocks=2 txs=80  mgas=19.948 elapsed=**35.964s**  mgasps=0.555 number=10015906 ...

Run iostat 1 100 outputs.
Device             tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sdc               7.00        76.00         0.00         76          0
sdd              30.00       332.00         0.00        332          0

Run vmstat 1 100 outputs.
r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
3  0 1878764 491464  77420 40912296    0    0   316   424 11296 14798 16  1 83  0  0
3  0 1878764 491212  77420 40912708    0    0   400     0 12393 15660 18  3 79  0  0
3  0 1878764 490456  77420 40913144    0    0   376     0 12534 16053 17  4 79  0  0
3  0 1878764 490204  77420 40913388    0    0   140     0 12048 15100 18  2 80  0  0

Have any idea about this? 

#### System information
Geth  Version: 1.9.13-stable
Operating System: linux
OS & Version: Linux

**Comment by karalabe** [comment]
Are you running on an SSD?

**Comment by tyrone98** [comment]
I run on an SSD, I resync on the same machine in this week, This problem seemed resolved.
All of the blocks can be imported within 200ms.
