### ISSUE TITLE
Cache config in config file is useless for mainnet

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/go-ethereum#21090]
If we config the cache options in the config file, then it will be overwritten.

**Comment by iraj465** [comment]
Hey i would love to work on this one. Can somebody please give me a bit of context as i'm new to this codebase?

**Comment by rjl493456442** [comment]
@iraj465 Hi! It would be nice if you can pick it up. Now Geth supports two approaches for the configuration: cmd flags and config files. The order for applying the configs is: (1) default config (2) config file (3) command-line flags(if they are set)

Now the issue is even the command-line flags are not set, the cache config in the config file will be overwritten by the default config. 

Before a bit more context in the codebase, check here https://github.com/ethereum/go-ethereum/blob/master/cmd/geth/config.go#L119

**Comment by rjl493456442** [comment]
The real root cause is: we will try to bump the default cache size for mainnet before we initialize the configs. https://github.com/ethereum/go-ethereum/blob/master/cmd/geth/main.go#L309

So the command-line flags will be set anyway

**Comment by iraj465** [comment]
Thanks @rjl493456442 for the detailed context ! Let me have look into it.

**Comment by jchengjr77** [comment]
Hey! Is @iraj465 still working on this? I don't see an assignee...

Looking for a good first issue in this project, so let me know!
