### ISSUE TITLE
Clef: Outdated API in Clef documentation

### ISSUE THREAD

**Issue by cygnusv** [ethereum/go-ethereum#21098]
The documented API for `account_list` (https://github.com/ethereum/go-ethereum/tree/master/cmd/clef#account_list, and https://geth.ethereum.org/docs/clef/apis) in Clef shows an outdated format for the response. Currently, only an array of addresses is returned. 

The changelog does explain what's the new format, but the actual docs should reflect this.

**Comment by MariusVanDerWijden** [comment]
I think this was fixed in https://github.com/ethereum/go-ethereum/commit/e5871b928fb0a4caf65153b552187c5c103e24d7#diff-0d96d8af54620b2c12dcc9c20fd2cd4c, could you take a look @cygnusv ? I'll close the issue in the meantime, feel free to reopen if this issue is still valid

**Comment by cygnusv** [comment]
All good, thanks!
