### ISSUE TITLE
Could you provide a list about the changes to EVM from Constantinople fork and later forks

### ISSUE THREAD

**Issue by fenghaoming** [ethereum/go-ethereum#21100]
What are the changes to EVM from Constantinople fork and later forks?
Could you tell me which commit in git?
Or Could you provide a list?
Thanks for your attention!

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
