### ISSUE TITLE
Android geth error: ./geth[1]: syntax error: unexpected ')'

### ISSUE THREAD

**Issue by aaron200453** [ethereum/go-ethereum#21117]
Hi,

I'm trying to run geth on Android and getting this error message in the android device:\./geth[1]: 

> syntax error: unexpected ')'

I have tried:
1) install latest binary (aar) - got the above error message
2) build aar on my machine - build finished successfully but running get came uo with the error message
3) tried to install Peter's version from 4 yrs ago (https://www.reddit.com/r/ethereum/comments/3wx09s/experimental_android_geth_library_archive/) - same error message 

see screen shot of the "adb shell" to the device

any suggestions / ideas? Did anyone succeed with it?

thanks, aaron

<img width="512" alt="Screenshot 2020-05-22 at 23 07 36" src="https://user-images.githubusercontent.com/65803185/82723099-2b561f00-9c81-11ea-990b-77d076b5f53c.png">

**Comment by ligi** [comment]
An aar is a library - not an executable

**Comment by aaron200453** [comment]
ok thanks. How do I make this library into an executable on Android?

**Comment by ligi** [comment]
you should be able to just use a linux binary compiled for ARM.
What exactly is your goal?

**Comment by aaron200453** [comment]
i need to my final project run geth on android (not as full node) and make some interaction with it from a JS / web3 client. The android part is the one i'm struggling with (no experience with android at all)

**Comment by karalabe** [comment]
The Geth library is an Android Java package (natively linked with Geth's Go code). You can import the library in Android Studio and it should give you access from Java to call the methods to set up and run a node. Though I'm not sure there's a way to access the RPC via HTTP like this, since that's not a safe setup. Java can access the APIs, so you might need to run a Java HTTP webserver if you want to access it from JavaScript.

**Comment by aaron200453** [comment]
thank you @karalabe! will try it.

**Comment by adamschmideg** [comment]
I assume the original problem was addressed. If you are facing another problem, please open a new issue (if you think it's a problem with Geth) or head over to Stackoverflow (if you need help).
