### ISSUE TITLE
how can i change the num of common.Address

### ISSUE THREAD

**Issue by w25193** [ethereum/go-ethereum#21122]
here`s my code
![image](https://user-images.githubusercontent.com/29299286/82783178-8f026700-9e90-11ea-96cc-c003df623f60.png)

this is the error message
![image](https://user-images.githubusercontent.com/29299286/82783217-a17ca080-9e90-11ea-8b0e-fb6e7bebfea2.png)

**Comment by MariusVanDerWijden** [comment]
Your address (from and to) are already in hex. You are trying to convert a hex string again, which produces a hex string that is twice as big as needed.
Just use 
```go
String from = "0x" + "5c1..."
String to = "0x" + "0828..."
Transaction tx = new Transaction(...)
```
Please paste your code in the future instead of sending screenshots, makes it easier to test!

**Comment by w25193** [comment]
i changed my code to
        from = "0x"+"4826a23c0e30c6b2d7c2fb6f6c8a2b42bbdf75fa";
        to = "0x"+ "92eaef2c075c4eff2fb28857667b80a7ca66bb16";
but still dont work here is the error
"error":{"code":-32602,"message":"invalid argument 0: json: cannot unmarshal invalid hex string into Go struct field SendTxArgs.data of type hexutil.Bytes"}}

**Comment by w25193** [comment]
i changed my code like this
`"error":{"code":-32602,"message":"invalid argument 0: json: cannot unmarshal invalid hex string into Go struct field SendTxArgs.data of type hexutil.Bytes"}}`
but it still dont work
here is the error info
`"error":{"code":-32602,"message":"invalid argument 0: json: cannot unmarshal invalid hex string into Go struct field SendTxArgs.data of type hexutil.Bytes"}}`

**Comment by w25193** [comment]
`        Transaction transaction = new Transaction(from,BigInteger.valueOf(1),
                BigInteger.valueOf(2),
                BigInteger.valueOf(1),
                to,BigInteger.valueOf(1),
                content);`
this is my constructor,is the params wrong?

**Comment by MariusVanDerWijden** [comment]
Which `Transaction` type is this? Your not using golang right? I think your question is better suited in https://github.com/web3j/web3j

**Comment by w25193** [comment]
thanks
