### ISSUE TITLE
master branch code can not connect "https://proxy.golang.org/github.com/%21azure/azure-pipeline-go/@v/v0.2.2.mod

### ISSUE THREAD

**Issue by freezehe** [ethereum/go-ethereum#21129]
Hi there,

I git clone newest master branch code,when I make geth，the error is “ github.com/Azure/azure-pipeline-go@v0.2.2: Get "https://proxy.golang.org/github.com/%21azure/azure-pipeline-go/@v/v0.2.2.mod": dial tcp 172.217.160.81:443: i/o timeout
make: *** [geth] Error 1”

long time ago  I can make geth，but I pull new code it is error.

please tell me how can i do it？

thank you!!!
 
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
looks to me there was a problem with your internet at this point. Can you try again? Do you have flaky internet currently?

**Comment by freezehe** [comment]
> looks to me there was a problem with your internet at this point. Can you try again? Do you have flaky internet currently?

no i try so many times ,but it doesn't work，i git checkout v1.8.17 code，the master code may be not stable

**Comment by ligi** [comment]
what happens if you wget or curl https://proxy.golang.org/github.com/%21azure/azure-pipeline-go/@v/v0.2.2.mod ?

**Comment by karalabe** [comment]
The Go package proxy is blocked in China. Please disable it by setting the `GOPROXY=direct` env var.

**Comment by karalabe** [comment]
Alternatively, there's also a Chinese mirror of the proxy, but it is not officially maintained by Google, so I cannot vouch for it (though the packages referenced by Geth are checksummed, so I don't think things can go horribly wrong). https://goproxy.cn/

**Comment by anilchoudhury** [comment]
> what happens if you wget or curl https://proxy.golang.org/github.com/%21azure/azure-pipeline-go/@v/v0.2.2.mod ?

I am facing a similar issue when i am trying to build EdgeX:
`| ERROR: Execution of '/home/anil/git/px-red-yocto/build/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/edgex-cli/1.0-r0/temp/run.do_compile.34488' failed with exit code 1:
| go: github.com/BurntSushi/toml@v0.3.1: Get "https://proxy.golang.org/github.com/%21burnt%21sushi/toml/@v/v0.3.1.mod": net/http: TLS handshake timeout
| go: github.com/BurntSushi/toml@v0.3.1: Get "https://proxy.golang.org/github.com/%21burnt%21sushi/toml/@v/v0.3.1.mod": net/http: TLS handshake timeout
| WARNING: /home/anil/git/px-red-yocto/build/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/edgex-cli/1.0-r0/temp/run.do_compile.34488:1 exit 1 from 'arm-poky-linux-gnueabi-go install -p 6 -v -ldflags="-r /usr/lib/go/pkg/linux_arm_dynlink  -extldflags ' -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a8 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/anil/git/px-red-yocto/build/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/edgex-cli/1.0-r0/recipe-sysroot -Wl,-rpath-link=/home/anil/git/px-red-yocto/build/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/edgex-cli/1.0-r0/recipe-sysroot/usr/lib/go/pkg/linux_arm_dynlink -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now'" -modcacherw -buildmode=pie `go_list_packages`'
|
ERROR: Task (/home/anil/git/px-red-yocto/meta-pxred/meta-edgex/recipes-core/edgex-cli/edgex-cli.bb:do_compile) failed with exit code '1'
`
I am able to access the path with wget.
I have tried following ways but didn't succeeddd:
- export GOPROXY=http://<proxy>:8080/
- alias go='https_proxy=http://<proxy>:8080/ http_proxy=http://<proxy>:8080/ no_proxy=localhost,127.0.0.0/8,::1 go'
- added proxy to bb files
- added proxy to .gitconfig file
[http]
[http "https://proxy.golang.org"]
        proxy=http://<proxy>:8080/
        sslVerify = false

**Comment by kuncle** [comment]
> Alternatively, there's also a Chinese mirror of the proxy, but it is not officially maintained by Google, so I cannot vouch for it (though the packages referenced by Geth are checksummed, so I don't think things can go horribly wrong). https://goproxy.cn/

thanks, it’s work.
