### ISSUE TITLE
eth.pendingTransactions doesn't return any pending transactions

### ISSUE THREAD

**Issue by csyzhou1037** [ethereum/go-ethereum#21138]
#### System information

Version: 1.9.13-stable
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.2
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.14.2_1/libexec

#### Expected behaviour

'eth.pendingTransactions' returns a series of pending transactions

#### Actual behaviour

'eth.pendingTransactions' doesn't return any pending transactions

#### Steps to reproduce the behaviour

curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_pendingTransactions","params":[],"id":1}' http://localhost:8545

#### Backtrace

The client is synchronous which can be verified by running 'eth.syncing' which returns false.

There does exist pending transactions which can be verified by running 'txpool.content' which returns a series of pending transactions.

But 'eth.pendingTransaction' returns an empty set of pending transactions

**Comment by karalabe** [comment]
That API endpoint only returns your own locally created transactions. Inspecting the entire tx pool content is fairly expensive, that's why it has it's own method.
