### ISSUE TITLE
[fixed] Installation Instructions for Mac

### ISSUE THREAD

**Issue by Zwilla** [ethereum/go-ethereum#21136]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

Geth version: `geth all`

OS & Version: OSX **Catalina** 10.15.4

#### Expected behavior
valid build on` make all`

#### Actual behaviour
build not possible

#### Steps to reproduce the behavior
follow just the instructions on given here: [WIKI: Installation Instructions for Mac - Building Geth  command line client](https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Mac#building-from-source)

#### Solution for a valid build

````
brew install go
brew upgrade go
sudo chown -R $USER /usr/local/go
git clone https://github.com/ethereum/go-ethereum
cd go-ethereum
sudo make all
````

#### Why?
Because of the new security system of osx and if you try to get the needed
dependencies you are not able to caused by thousands of 'permission denied'
errors

**Comment by adamschmideg** [comment]
The wiki pages are outdated as it says in the header. Please feel free to edit https://github.com/ethereum/go-ethereum/blob/gh-pages/docs/_install-and-build/Installing-Geth.md#install-on-macos-via-homebrew and/or https://github.com/ethereum/go-ethereum/blob/gh-pages/docs/_install-and-build/Build-from-Source.md and open a PR

**Comment by fjl** [comment]
I don't understand the original issue. It says something about 'permission denied' errors, which may happen when go-ethereum is cloned to a non-writable directory. It is not an issue with `make all`.
