### ISSUE TITLE
The modified code does not take effect

### ISSUE THREAD

**Issue by SoftProgramLX** [ethereum/go-ethereum#21131]
I want to modify the source code of go-ethereum. What steps need to be taken to make the modified code take effect?
> Here is the 3930 line of the file "go-ethereu/internal/jsre/deps/web3.js" that I modified, but I can see through the geth that the output is still "invalid address". The modified code does not take effect.
> ![](http://img.kongyixueyuan.com/1590565532436.jpg)

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
