### ISSUE TITLE
Inconsistent subjects between commit and proposal address 

### ISSUE THREAD

**Issue by YongilChoi** [ethereum/go-ethereum#21146]
Hi there,

WARN [04-01|11:33:02] Inconsistent subjects between commit and proposal address=0xc6dc88c4292612184197134c2f39a08c72948aec from=0x2346ca12d69b9991c6178440042f356a8718c54b state="Request ExtraData" expected=nil got="{View: {Round: 1, Sequence: 1}, Digest: 0x82363a76f3ef9eae6693a6fd918af503ed77b5f6a7b9a7d921b3ab30f8964166}"

What is this? 

I can not find the problem..

**Comment by karalabe** [comment]
No idea, because that's not in go-ethereum. The only reference I've found to that message is in Tendermint https://github.com/clearmatics/autonity/pull/90/files/51ff9b327aba7c8d38b10fe2ef418e58cfe0b537
