### ISSUE TITLE
JSON_RPC eth_pendingTransactions Filtering

### ISSUE THREAD

**Issue by Samyoul** [ethereum/go-ethereum#21143]
## Background

I recently posted [this question](https://ethereum.stackexchange.com/questions/83742/is-it-possible-to-filter-pendingtransactions) on `ethereum.stackexchange` and after solving my own question I thought that I'd raise the issue to have filter functionality included in the `go-ethereum` RPC calls.

Currently OpenEthereum has this functionality.

[`parity_pendingtransactions`](https://openethereum.github.io/wiki/JSONRPC-parity-module.html#parity_pendingtransactions)

**Example:**

```json
{
  "jsonrpc":"2.0",
  "method":"parity_pendingTransactions",
  "params":[
    null,
    {
      "to": { "eq": "0xe8b2d01ffa0a15736b2370b6e5064f9702c891b6" }
    }
  ],
  "id":1
}
```

I don't see introducing filter fields to the parameters to the `go-ethereum` `eth_pendingTransactions` JSON_RPC method would introduce any kind of breaking change, as the change is an extension of existing functionality.

## Proposal

Extend the functionality of the `eth_pendingTransactions` JSON_RPC method, so that the method can accept parameters used for filtering transactions in the pending pool.

## Benefits

- Reduce the amount of bandwidth consumed by a client only interested in a small subset of the current pending transaction pool.
- Reduce the amount of data parsing a client needs to do to find the relevant data.

**Comment by ligi** [comment]
Can you give some more details on your use-case?

**Comment by xas** [comment]
It could be interesting to monitor a specific address for KPI, alerts, ...
Could be useful and offer the possibility to people to use it with solutions like Infura, without need to get the details of each tx (and quickly reach a rate limit).

I think be able to filter between _from_ or _to_ should be enough

**Comment by Jolly23** [comment]
> Can you give some more details on your use-case?

https://github.com/ethereum/go-ethereum/issues/22299#issuecomment-857787163

**Comment by MariusVanDerWijden** [comment]
Will be implemented here: https://github.com/ethereum/go-ethereum/pull/22977
