### ISSUE TITLE
Require function does not work in geth

### ISSUE THREAD

**Issue by david179** [ethereum/go-ethereum#21150]
I have a smart contract that uses `require` to validate the parameters inside some functions and I have noticed that geth 1.9.13 and 1.9.14 do not enforce the condition in require. I could reproduce the problem with this simple smart contract  

```    
pragma solidity >=0.6.0 <0.7.0;

contract NodeContract {
    
    
      // Define the struct with the data of a node
      struct Node {
        // UUID
        bytes32 nodeId;
      }

      uint numberOfNodes = 0;
    
      mapping (uint => Node) nodes;

      constructor() public {
      }

      function publishNewNode(bytes32 nodeId) external returns(uint256)
      {
       
        uint256 nodeIndex = numberOfNodes;
        
        nodes[nodeIndex] = Node({nodeId:nodeId});

        numberOfNodes += 1;

        return (nodeIndex);
       }

    
      function getNodeData(uint256 nodeIndex) external view returns(bytes32  nodeId)
      {
        require(nodeIndex < numberOfNodes, "The nodeIndex supplied is larger than the number of available nodes");

        return (nodes[nodeIndex].nodeId);
      }
    

      function nodesCount () external view returns(uint) {
       return (numberOfNodes);
      }
  }
```

#### System information

Geth version: `1.9.13` and `1.9.14`
OS & Version: Ubuntu 18.04

#### Expected behaviour
If I deploy the contract above in https://remix.ethereum.org/ and I call getNodeData(0) then I get the expected error message `Reason provided by the contract: "The nodeIndex supplied is larger than the number of available nodes"`. On the other hand, if I deploy that contract in my private blockchain in geth and call `myContractInstance.getNodeData.call(0);` I get `0x` which means that the whole function executes instead of stopping at the require line. Is there a way to fix this and get the expected behavior?

**Comment by MariusVanDerWijden** [comment]
see https://github.com/ethereum/go-ethereum/issues/21082
