### ISSUE TITLE
Node Stalled at EVM layer when sending higher txs to it

### ISSUE THREAD

**Issue by cyrilnavessamuel** [ethereum/go-ethereum#21158]
Hi there,

#### System information

Geth version: 1.9.12
OS & Version: Linux
Clique PoA
Processor: Intel i7 - 3770
CPU: 8
RAM : 16 GB
TXPOOL.GlobalSlots: 100000000

#### Expected behaviour
Process the transactions and signing as normal

#### Actual behaviour
In my private clique network with 4 Nodes I have a genesis with block period 2.

Block gas limit: 500000000

I also set my miner gas limit and gas target as 500000000 to ensure a linear block gas limit from start to end.

I send transactions to my nodes at faster rates with each txs consuming 30200 gas so I end up having blocks with each of them having txs upto block gas limit. I end up getting 16000 - 15000 txs included in each block.

Then the Node gets stuck at EVM operation which I noticed while I run cpu profiling on my node. When I set a lower block gas limit & miner gas limit and target around 250000000 node doesnt stall which has blocks with 8000 txs in each.

Also another pointer to add is while 250000000 doesnt stall my node for the same txs but 150000000 (blocks with 5000 txs in each) ensures my node processes the transaction much faster in the network. Please can some one let me know if you had similar issue or is there any specific limit to set based on the type of txs executed in the network.

#### Steps to reproduce the behaviour

Send Large Transaction to the Nodes by maintaining >8000 txs included per block, also needs adjusting block gas limit and txpool.globalslots

#### Backtrace````
CPU Profiling Trace

![image](https://user-images.githubusercontent.com/8938494/83494794-149c9d00-a4b7-11ea-8716-ef9954d65364.png)

**Comment by karalabe** [comment]
Do you have some repro script that we might try? Are these transactions contract calls? Are you calling the same contract with all of them? That big red area is something we've discussed just yesterday, but it seems surprising that it makes such a difference. We can possible help in your particular case with it if you can provide some details.

**Comment by cyrilnavessamuel** [comment]
Thanks Karalabe for your reply. Yes I have uploaded the script in my repo to replicate the scenario with README file to follow. @ https://github.com/cyrilnavessamuel/ethereumissue.

Yes these are repetitive transaction contract calls to the same method in it. Yes the same contract is called repetitively.

I have also attached in the repo my CPU Profile svg file to verify in case. Good day!

**Comment by cyrilnavessamuel** [comment]
Hello Karalabe,

Did you have time to check out this issue. Please let me know in case of any issues. 
Cheers

**Comment by MariusVanDerWijden** [comment]
Hey @cyrilnavessamuel I've been trying to replicate your issue today, could you maybe add the genesis,json to your repo?

**Comment by cyrilnavessamuel** [comment]
Hi @MariusVanDerWijden  Thanks for trying. I have uploaded genesis.json to my repo.
Cheers

**Comment by holiman** [comment]
The problem here is not that jumpdest analysis is slow, in particular, but that jumpdest analysis is not reused across transactions. You are doing 12K calls to the same contract, and thus each block has to do 12K jumpdest analysis:es. 
We could definitely improve this by using a global LRU of them, but it's not a trivial change. It should be an LRU which also takes cost into account (where cost is the actual size of the code). Perhaps we could use a `fastcache.Cache` for this purpose (and don't care about the recentness)

**Comment by holiman** [comment]
I saw that the repro repository has the `sol` file, but could you also attach the compiled runtime code? It would be pretty easy to check how much time `12K` jumpdest analysis:es of that particular piece of code _should_ take, and thus verify if my theory matches what you see

**Comment by holiman** [comment]
here's what remix gave me: `608060405234801561001057600080fd5b50600436106100575760003560e01c80631c1df5fb1461005c5780633863dbb81461007a5780634865f28d146100985780639b76ee56146100c8578063a1279143146100e6575b600080fd5b610064610104565b604051610071919061019b565b60405180910390f35b61008261010d565b60405161008f919061019b565b60405180910390f35b6100b260048036036100ad9190810190610163565b610113565b6040516100bf919061019b565b60405180910390f35b6100d0610142565b6040516100dd919061019b565b60405180910390f35b6100ee610148565b6040516100fb919061019b565b60405180910390f35b60008054905090565b60015481565b600060016000540160008190555060018054016001819055506001600254016002819055506000549050919050565b60005481565b60025481565b60008135905061015d816101c0565b92915050565b60006020828403121561017557600080fd5b60006101838482850161014e565b91505092915050565b610195816101b6565b82525050565b60006020820190506101b0600083018461018c565b92915050565b6000819050919050565b6101c9816101b6565b81146101d457600080fd5b5056fea365627a7a723158203cef65d6b559e46699acc0bfcdb73572ca52273f17596e18a0d6580ebaf2c6146c6578706572696d656e74616cf564736f6c63430005110040`

**Comment by cyrilnavessamuel** [comment]
Please find the bytecode @ https://github.com/cyrilnavessamuel/ethereumissue/blob/master/contract-bytecode I used Remix as well.

**Comment by holiman** [comment]
Actually, that doesn't make sense: 
```
BenchmarkNodeStalled-6   	     100	  13812538 ns/op
```
My machine does `12K` analysis:es in `13ms`.  

Or maybe it does make sense -- your trace image has a durationf of one hour, so quite a lot of blocks I assume

**Comment by cyrilnavessamuel** [comment]
Yes Thanks. Is there some information you might need or you want me to try as part of the analysis?

**Comment by holiman** [comment]
I suspect that the 'stalling' isn't due to anything that's visible in the cpu profile-graph. I'm wondering if it isn't some lock contention which isn't visible on that graph. 

I mean, with `27s` spent on `JUMP`, having `400+` seconds spent on jumpdest analysis looks pretty much within reason.

**Comment by cyrilnavessamuel** [comment]
Hello All,

Just wanted to check If you need any more information for this issue I may help with other than the cpu profile

Cheers,
Cyril

**Comment by holiman** [comment]
We think this is now fixed (more or less) with some changes we've done recently on how the txpool handles 'local' transactions. Previously, there was some thrashing going on which should be a lot better now.

**Comment by karalabe** [comment]
Could you please check with latest master (or stable)?

**Comment by adamschmideg** [comment]
I assume it's fixed. If the problem still persists, please open a new issue.

**Comment by cyrilnavessamuel** [comment]
Hello Team,
I can confirm its fixed, tested it with the latest version. Thank you for the efforts!!
I am a bit curious to know what was the issue and the fix applied on please.
Cheers,
Cyril

**Comment by karalabe** [comment]
I'm not sure exactly (long time ago). The notion of "local" transactions was tacked on to the txpool after it's initial implementation and certain data structures don't play well with certain transactions not adhering to the rules. There are a few more corner-cases where ideally we'd need to make local transactions separate from the rest to prevent them from messing with the pool, but we did try to address a few obvious ones. Glad yours was among them :)
