### ISSUE TITLE
Rinkeby Faucet: No Ethereum address found to fund

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#21166]
this is the tweet that clearly contains an ethereum address: https://twitter.com/mr_ligi/status/1268171687159357443

![Rinkeby: Authenticated Faucet - Brave_579](https://user-images.githubusercontent.com/111600/83642075-a6d39c80-a5ae-11ea-9e0b-bccf9b769eb5.png)

Guess there is something off with the twitter connection

**Comment by vdo** [comment]
Looks like we have the same issue with the goerli faucet:
https://goerli-faucet.dappnode.net/

**Comment by ligi** [comment]
also with the https://yolonet.xyz - but this one at least has the fallback to plain addresses

**Comment by ligi** [comment]
People now also start complaining on reddit: https://www.reddit.com/r/ethereum/comments/gvsfaf/rinkeby_faucet_not_allowing_me_to_gain_test_eth/

**Comment by ZazzyDictionary** [comment]
The issue still exist.
![Screenshot 2020-12-20 at 9 26 21 PM](https://user-images.githubusercontent.com/25434034/102714521-022a6980-430a-11eb-9167-b559d3e88ed5.png)

**Comment by Holger-Will** [comment]
same problem with facebook posts, too

**Comment by olimdzhon** [comment]
same problem on twitter,  and facebook  says invalid facebook post url

**Comment by pramhedadev** [comment]
Is there an alternative method of getting ether ?

**Comment by ligi** [comment]
Please send me your address and how much rinkeby ether you need

**Comment by pramhedadev** [comment]
Hi @ligi thank you. 
I need roughly about 15 ether : 0x151efe3c9612AC77E112a39944Cd119ECC7817C8

**Comment by ligi** [comment]
@pramhedadev 
https://rinkeby.etherscan.io/tx/0x58adbfb87a042546106442112eafa8dff000041a4599ae5d9255319e45beb23e

**Comment by pramhedadev** [comment]
> @pramhedadev
> https://rinkeby.etherscan.io/tx/0x58adbfb87a042546106442112eafa8dff000041a4599ae5d9255319e45beb23e

Thank you. I received it

**Comment by mehulsc** [comment]
can I get 15 RETH as well: 0xD37ba182d8528E2EcA85fba497C804EDC84A8324
ty

**Comment by ligi** [comment]
@mehulsc 0xD37ba182d8528E2EcA85fba497C804EDC84A8324

**Comment by ktym1** [comment]
Hi @ligi can I get 18.75 RETH: 0x41f038C12D2A93009a5DA3B99e063235fdf93303

Thank you for your help!

**Comment by ligi** [comment]
@ktym1 https://rinkeby.etherscan.io/tx/0x8229bad893cef32cf0deb315848173b10ba94a52a496ca4a18371ac98acaee67

**Comment by ktym1** [comment]
> @ktym1 https://rinkeby.etherscan.io/tx/0x8229bad893cef32cf0deb315848173b10ba94a52a496ca4a18371ac98acaee67

Thank you!

**Comment by ZazzyDictionary** [comment]
@ligi can i get 20 RETH :  0x94EaDfdD92076932c04d8F5D01B379C09212EeF8

**Comment by ligi** [comment]
@ZazzyDictionary wondering why you need 20 - this is more than you would get from the faucet. Greed or real need?-)

**Comment by therealssj** [comment]
https://github.com/ethereum/go-ethereum/pull/21172
seems like the solution of switching over to mobile twitter doesn't work anymore

doing some quick tests, `http.Get` returns -> `This browser is no longer supported`

faking it with a iPhone/Chrome user agent returns -> `JavaScript is not available.....`

not sure what the solution could be here, executing requests with a headless browser api?

**Comment by ZazzyDictionary** [comment]
@ligi i am not sure when will i get the chance to get more Reth so i guess i will take what i can get haha :)

**Comment by ligi** [comment]
@ZazzyDictionary I send you 4 - LMK when you used them and need more. Then I will check if you used them wisely or just blew it all and send you more depending on this check ;-)

@therealssj thanks for looking into this. The problem is that there are now 2 issues at play: the twitter communication and the communication with the network (as also other methods other than twitter do not work)

**Comment by Holger-Will** [comment]
@ligi i guess 15 would help finish: https://ethernaut.openzeppelin.com/ (idk)

0xEB9366Eb2735E8E2FC7eCBCCAFA213068fc181dB

**Comment by ligi** [comment]
@Holger-Will for something like this always: https://rinkeby.etherscan.io/tx/0x6bf1b5f2d844b320a2eb18767cd9de925d5cf8c0060b9a9db30657123dff1adf

**Comment by dileepfrog** [comment]
Hi there, I'm a developer at IDEX and our sandbox environment's automated load generator often runs through RIN due to users taking the bot's orders. It would be very helpful to obtain a larger amount of RIN to support this use case, but also the standard 18.75 would be great to 0x36915be02c6e9b3a7ffa342cfb81c080dc48e0ab. Thank you!

**Comment by ligi** [comment]
@dileepfrog 42 for you: https://rinkeby.etherscan.io/tx/0x349fb6094b22eed7d93aa1728c6b1be082b4297ba97432de111e6c56f81bdcc0

**Comment by canberk17** [comment]
Hi @ligi  can you send 15  to 0x343A53A1E8b17beDd15F47a28195Bc8C120d4443. I've been having the same problem

**Comment by canberk17** [comment]
hi @ligi I've been having the same problem with  Rinkeby website no matter how many times I tweet it says No ethereum address is found to fund. Could you send 18.75 eth  to 0x343A53A1E8b17beDd15F47a28195Bc8C120d4443, I'm trying to test my algorithm

**Comment by reyemb** [comment]
@ligi Hi I am getting started to learn about smart contracts. Can you send me some ether to play with? :)
0x3a3CBfBef28054692b591CF0d6Fd3dD290d43Ee0

Dank dir 👍

**Comment by mudabbirk** [comment]
Hi, can I get 15 Ether at the below address? I am doing some academic research and trying to play around on the Rinkeby testnet.
Address:    0xCb023a46aB79D3067BC5A30A287DC742d531727f

**Comment by FinnitoProductions** [comment]
Hi @ligi, would it be possible for you to send over 15 ETH on Rinkeby to 0xdB8F136534e2ad78D988f167E9852dd7E09336fA? I am beginning to pursue smart contract development and some ETH to get started would be very much appreciated. Thank you!

**Comment by olimdzhon** [comment]
Hi @ligi can i get some tokens on this account 0x26f5061c62115aba83c2Fd180b32a304Df6Ca8Be i wanna test my smart contract

**Comment by nprog** [comment]
Hi @ligi, can I get 15 Ether at the below address? I am doing some academic research and trying to play around on the Rinkeby testnet.
Address: 0x1fA6543e00ff225D50c337765634Aae2C7eE4085

**Comment by hasijasaurabh** [comment]
> Please send me your address and how much rinkeby ether you need

Hi can you also send 5 ETH to 0x9e45156C84DAE9812A8B2DBf38878F9b8d34f7BD

**Comment by Tigo9527** [comment]
@ligi Hi there, please help us for the same problem. could you please send ether to these address(they are my team mate):
0x9a5ef76F0e2d03dEDa0e42bA692B36d685C93F2e  ten ether to it, or 3 ether to each. thanks.
0xd76f955ac8FAa0eb9c139A32cBf19d9E678Cd1F9
0xa1F29a57BD2240aAECABcAfB3Febed914648b64E

**Comment by vineshkamble** [comment]
Please send some ethers to this address 0xf93afdd67f30495bdf37ed29db8fcf05c95d8dcd

**Comment by will3dev** [comment]
is it possible to have some ether sent to the below address. I am running in to the same situation mentioned in this ticket.

0x6b73B16c913A6491368831135EF957A463Cf8177

**Comment by olimdzhon** [comment]
you can get tokens from here guys https://app.mycrypto.com/faucet

**Comment by MisterWind** [comment]
@ligi Hello, can you please send 3 test tokens to this wallet: 0xF179f4bD6842f2305C6569Fbf3838F6414D5a77F ? I have an exam on "researching cryptocurrencies" discipline and this is a part of the task, but i got the same problem with twitter and facebook as in the post.

**Comment by LeonDragon** [comment]
Please send me some ETH for the testnet Rinkeby  0xcF123a28a6BcEBD27FD08EfE9A59594C2c4bAEB9
Thank a lot

**Comment by jcswapper** [comment]
Please a need 18.75 ETH for Rinkeby testnet to address 0xB23FaFfF64E0670E8E72a2B522e5e63e7d83940e

**Comment by xanarry** [comment]
Please send me 18.75 ETH for the testnet Rinkeby "0xbffa773f1c8d34b3a7d98c8ff6acb56478c8abdc"
Thank a lot

**Comment by amshirif** [comment]
18.75 ETH please!
0x14B181Ed9030F5174a95E80712D4c43697275317
thank you

**Comment by khenchi** [comment]
Hi @ligi  can I get 18.75 RETH: 0x7dD86Ef978A086F6635B21363515F09BC9E2800c

It is for a project, migrating smart contract

Thank you for your help!

**Comment by sid-viluva** [comment]
Hi @ligi can I get 2ETH for 0xD0A16a95669B14161B09dafFa20B24575b77b731.
Thanks a ton

**Comment by rafael-varela** [comment]
Hi, can I get some Rinkeby ETH please? 0xF78C704c0510402C05e54C6a5c8715a947b79f24
Thanks in advance!

**Comment by SpicyHabanero** [comment]
Can you please hook it up? It seems the rinkeby website still doesn't recognize the eth address in my twitter post.. 0xe0e263478A6CEc9f2C1621b269A0bCfc646a404e

**Comment by tfelix** [comment]
I want to checkout a Chainlink Node, I would need maybe 10 rETH on 0xd36e44EFf4160F78E5088e02Fe8406D7638f73b4 thank you! :)

**Comment by JavedRNC** [comment]
> 
> 
> @pramhedadev
I need some ether.
Here is my address: 0x4D445080f46FDf0c4CA5E706f621Fdf789F52D49
Please, I m in learning phase.

**Comment by JavedRNC** [comment]
I need some ether.
Here is my address: 0x4D445080f46FDf0c4CA5E706f621Fdf789F52D49

Please, if someone can help, I m in learning phase

**Comment by NohaThabet** [comment]
@ligi
Hi,
I'm a developer, please send me 18.75 ETH for the testnet Rinkeby "0x95352853C6B247EF80a44209f7BDeec400c54037"
Thanks for your help

**Comment by mehulnagar12** [comment]
Hi @ligi,
I'm facing the same issue, can I get 18.75 ETH for the testnet Rinkeby.
address : 0x0F397D4c00e7592E4915Bd8654500868C3cC72CE

Thank You!

**Comment by viktorliddell** [comment]
Hi, @ligi
Please send me 18.75 ETH for the testnet Rinkeby 0x0344855228f86E142369847F9022E33badd1Bc0d
Because it's still not working...

Thank you)

**Comment by somenath1435** [comment]
Hi, @ligi
Please send me 15 ETH for the testnet Rinkeby 0x0741015bae45fF71132fcA04a174b1Ee641CD016

**Comment by sakshjha2000** [comment]
Hi, @ligi
Please send me 18 ETH for the testnet Rinkeby 0xBE558BAB78ca948cBCf99523Ec4154635a09A56F

**Comment by MattV1993** [comment]
Hi, please send 18.75 ETH to address 0x84ab149210ee64B3BDe0f4e340F3B032A5100049
Thanks!

**Comment by SirLemuel** [comment]
Hi @ligi , I could use 18.75 Ethers for the Rinkeby test net please.
My address: 0x9960b79214759A5103430466d156D93ee771c48d

Thank You.

**Comment by ligi** [comment]
sorry - cannot send anymore funds - rinkeby is stuck. #22086 
Please try to move to goerli in the meantime if possible
Sorry for the inconvenience!

**Comment by ngrt** [comment]
Hi, @ligi
Please send me 18 ETH for the testnet Rinkeby 0x612a6883ff751a8315e7A8CF95fF69019025D1c5

Thanks!

**Comment by AntonioPMCS** [comment]
Hello, I am having the same problem. Do you have any idea when this might be fixed?

In the meanwhile, @ligi  is it possible to send 15 ETH to 0x95C95792697d2b024aF824fE3e455b1be4994db1?

**Comment by sonish777** [comment]
Having the same problem. Please send me 18 ETH for the Rinkeby test network, my address is 0xcba659d3a182EC0A8D69159DA02C90690c440887
Thank you very very much in advance!!!

**Comment by tientvt** [comment]
Hi @ligi , I could use 18.75 Ethers for the Rinkeby test net please.
My address: 0x7361098D77d2437475c7cF5489D61784EC61A261

Thank You!!!

**Comment by metthebet** [comment]
Hello! While I'm still getting the same "Ethereum address not found for funding" error message, can please anyone send me any amount (ideally -- 18) of test ETH to 0x2Ac05a5B19c882B91B537dcfae613FA0E4aFEE

Thank you!

**Comment by ph0ly** [comment]
Hi @ligi , I could use 18.75 Ethers for the Rinkeby test net please.
My address: 0x699DB98B976BC6B42c7E0F35f283f62656dC5A86

Thank You!!!

**Comment by rbsamtest** [comment]
Hi @ligi. I am having the same problem. Can you please send me 18 Ethers for the Rinkeby test net.
My Address: 0x575416c12C13e46A998e862aC10372b198D174cd.

Thanks a lot.

**Comment by makerzy** [comment]
Hi, @ligi could you please send 18.75 ETH to address 0xbd7a862eBCc528002cC77786643A97D43f8ec948
Thanks you!

**Comment by ggilboo** [comment]
@ligi, sorry to jump on the bandwagon but could use some as well

0xC61f96bb09087f516e7edF42aD3767B6d5dfF70D

**Comment by artkkk** [comment]
Hi @ligi  ,could you pleses send 8 ETH to address  0x3c3167C5974485E3d736f328C3a1810606173169     Thank u very much!

**Comment by gtrrz-victor** [comment]
Hi @ligi, thanks so much for giving that support to the solidity learners whereas this issue is being fixed. I would like to have some ethers to build up examples in order to learn about solidity. 
My address is: 0x19a4a7544456bFca6C4d1C8c269bb46c0350A2f2

**Comment by JeanGalt1957** [comment]
FYI, Ropsten faucet is working fine - just deployed there :)

**Comment by gtrrz-victor** [comment]
> FYI, Ropsten faucet is working fine - just deployed there :)

Thx! You have made my day!! Now, I can keep doing my course.

**Comment by to101380** [comment]
Hi @ligi ,could you pleses send 18.75 ETH to address 0xbc1ADfF2EAC8dbA22d382DFADDf7e6B73aBC2334 Thank u very much!

**Comment by zpcodemen** [comment]
,could you pleses send 1 ETH to address 0x68e30F64c71F311bbF7B5b1499b49d33Fde45a67 Thank u very much!

**Comment by hqman** [comment]
Thank you!  please send me 18.75 ETH :0x5386D64023Dde8e391f8bCE92B5cd5bFF31413ef

**Comment by kurochkagril** [comment]
pls send me 0.1 eth 0xEbB166E1E8c3b4e9c51E4463Cbf5C59A5899DAB8

**Comment by tanqiangyes** [comment]
Hi, @ligi
Please send me 18.75 ETH for the testnet Rinkeby 0xb03eB40add8f80472804eA658D7B18585d0Ae737
Because it's still not working...

Thank u very much!

**Comment by z280723809** [comment]
Hi,@ligi
 I also need 5 ETH for the testnet Rinkeby 0xdcd6da2575fF04b363A6467d568e965F777d40E0

Thank u very much!

**Comment by LeTranMinhQuoc** [comment]
Hi, 
I need 15 Rinkeby ETH for testing,could you pleses send me at 0x0ec104399A639e14d0c5f3d97c6F4A519663f646

Thank u so much!!!

**Comment by clifton** [comment]
im also trying to get this to work for ethernaut thx -- 0xF9bF754c92dC813301bc2bc014d2015fc86b980A

**Comment by xiaoxiaoleo** [comment]
Hi,@ligi
I also need 15 ETH for the testnet Rinkeby 0x146a4ee57464b1F241c6d5F6b0ee45A9FAB98307

Thank u very much!

**Comment by zonghai-li** [comment]
15eth   Rinkeby  0x7913AcB42289768FCf6817B006842D0c66f4682B   Appreciate that!

**Comment by JohnattanD88** [comment]
dear all, if there is someone among u who still has some ETH to spare (I literary need 1 ETH - I just started with Dapps and still learning)... anyway I would appreciate if someone could help me out here... thx in advance!

0xe48A001eDB1F0ef962669CD7aB58aE67fb2d342f

**Comment by JeanGalt1957** [comment]
I recommend the Ropsten network - the facet works fine!

**Comment by rajinder712** [comment]
hi @ligi please send me 15 ethers. ineed urgent

**Comment by JeanGalt1957** [comment]
> > FYI, Ropsten faucet is working fine - just deployed there :)
> 
> Thx! You have made my day!! Now, I can keep doing my course.

@gtrrz-victor  glad it helped! I’m doing the same thing :)

**Comment by mimigon** [comment]
hello,@ligi
I need 3eth for the testnet Rinkeby 0x7F5687ED5e026f601d1D8Ba7301C8C0f6430Df7b

Thank u very much!

**Comment by iAmShakil** [comment]
Need 5 ETH for development 0x6ABce4D8fB88d8Fbb4b23D8d2De24172dB8640F9

**Comment by SirLemuel** [comment]
Attention: Ringeby is likely to be down for some time, I've tried for a few days now. Use the Ropsten network @ https://faucet.ropsten.be/

**Comment by gio5151** [comment]
@ligi Hi, please send 3 ETH at (Thank you)

0x870cE981DDc757f25E5B069f0cDa7ea65946c75e

**Comment by lucagrossi** [comment]
Hi can you send 5 Eth to 0xe3Ba28D6734dE86839BBe8B922233806C73C98bE.
thanks a lot!

**Comment by jcswapper** [comment]
Hi @ligi ,could you pleses send 8 ETH to address 0xB23FaFfF64E0670E8E72a2B522e5e63e7d83940e Thank u very much!

**Comment by barracuda7777** [comment]
Hello, Can you send 8 ETH to my address please?

0xc35B0C09a86F003EdccACD0c6a3fF41194fE26fd

Thank you for the help!

**Comment by nikolavranic** [comment]
Hello @ligi can you please send 8 EHT to address: 0xFeD3b599698bDf8f70495F6F85a1f5457f1eeA41 Thank you!

**Comment by erhenglu** [comment]
Hi @ligi, Can you send 8 ETH to address 0xE3f7580315DC100C2B64731c1868A742D77d1d23   Thank you

**Comment by sonish777** [comment]
Hi everyone, just letting everyone know that the Rinkeby faucet now seems to be working. 
I used facebook post option and it worked just fine! Please check it out. Happy Coding !!!!!!!!!!!

**Comment by carthorian** [comment]
Hi @sonish777 ,
I've just tried vie Twitter but didn't work.

Hi @ligi,
Can you send 8 ETH to address 0x4D4351EB699a85eb3B68cB0E26B36174dDCC2237 ?
Thank you.

**Comment by formulatrout** [comment]
Neither twitter or Facebook works for me.

Requesting faucet funds into 0x9d868d2900e3df96e5A7938bfab8B89Aa6B9dB09 on the #Rinkeby #Ethereum test network.

**Comment by oanatudor-umc** [comment]
Twitter or Facebook posts do not work for me in the Rinkeby Faucet.
If @ligi can still help (much appreciated), I would need about 4 ETH to get going on the Rinkeby Ethereum test network. Address is 0x96DF371cd4Abe23083c29c62272EF5E635548784

**Comment by luckhoi56** [comment]
0x67E4b1172B64b8D04B72eD2BD05473003969F8E0
can i get 5 eth please

**Comment by masoodamodak** [comment]
Hi,@ligi
I also need 15 ETH for the testnet Rinkeby 0xdf2Cd225177E96C3426F761146ab2FC7EF1966Cf

Thank u very much!

**Comment by Philipid3s** [comment]
HI @ligi 
I will need 5 ETH for the testnet Rinkeby 0xA7236a1aD6EA72649EDdB0045501ae92AD61d0Cb

Many thanks in advance !

**Comment by karalabe** [comment]
Hey all, the upstream faucet is back online https://faucet.rinkeby.io/

Sorry about the downtime, Twitter decommissioned their old site that we used to fetch tweets from and needed to switch over to an API workflow, which is a bit more work than we wanted to put in during xmas. Should be fine now, please ping if there's still some issue.

**Comment by fatimahambreen** [comment]
@karalabe I have tried the whole day yesterday but the faucet.rinkeby.io is still not working....it's notifying the same message that "no Ethereum addresses found to fund" ....
Please help me I need 20 ether for my college project. It's very important ...

If anyone could give me please do reply I will send my account address

**Comment by karalabe** [comment]
Something seems broken in the light client, the faucet keeps stopping pushing transactions out to the network.

@fatimahambreen Please paste the link here you're trying to use so I can take a look at it.

**Comment by fatimahambreen** [comment]
Hello sir,

First of all thanks a lot. I would be very grateful for your help.

This is my account address 0x956Bcb03a6f8Df9566C7b300E35A21571e30c559

Sir please provide me atleast 20 ether so that I can complete my project at
university.

Anticipating for your help

Thanks & regards
Ambreen Fatimah

**Comment by fatimahambreen** [comment]
Sir this is my facebook post link that I pasted in faucet.rinkeby.io

https://www.facebook.com/ambreen.fatimah.1/posts/781618749097122


But its saying "No ethereum address found to fund"

Please help me sir

**Comment by fatimahambreen** [comment]
@karalabe please sir do reply..

**Comment by karalabe** [comment]
Windows auth was just fixed and deployed.

**Comment by canberk17** [comment]
All of you for once read the whole discussion instead of asking for coins. The guy literally said that he doesn’t have any

**Comment by masoodamodak** [comment]
U can use a Twitter post instead of  a Facebook post

**Comment by fatimahambreen** [comment]
thankyou so much sir

**Comment by fatimahambreen** [comment]
I received ether

**Comment by al-codes** [comment]
> Please send me your address and how much rinkeby ether you need

Hello @ligi, not sure if you are still taking requests but Twitter and FB is not working for me. Wondering if I could please get 8 ETH for the testnet Rinkeby?  0x38be8A0741eC4E1C9B66C1983128773Fe5545e94 
Thank you!

**Comment by reecemak** [comment]
I am having the same issue. I want to test the transaction, but I have no test eth in rinkeby. please fund mine 20 eth for both of these address.
0xdb128a2516455b43fd28a3c8450b9d519ff64943
0x95c9d3b734d03db3f76718e8a85a11550b0444b3

**Comment by karalabe** [comment]
Just tried it, both Twitter and Facebook auth works. Not sure what you're seeing.

**Comment by karalabe** [comment]
The faucet is also actively giving out funds, so it's working for other people too https://rinkeby.etherscan.io/address/0x31b98d14007bdee637298086988a0bbd31184523

**Comment by aet00** [comment]
Met same issue ..
Hi @ligi @karalabe .
May I get roughly about 15 ether : 0xF7e997478843D0dD9e52917032086F33Ba0734C1

**Comment by sinoserous** [comment]
Hi @ligi 
Same issue here. May I also request ~15 ether at:
0xb4E08BE3CF56c8f62e1aa412601c0c3490CD7f35
Many thanks in advance!

**Comment by kaiserwoo** [comment]
Hi @ligi
Same issue here. Could you please send me 15 ether as well at: 
0x5C7938F3dffb97fF3F6415Fe98F85F9024BF2685

Thanks a lot!

**Comment by karalabe** [comment]
Faucet works, please check that your posts are public.
