### ISSUE TITLE
test case contains "infinite loop" causes "out of memory" problem 

### ISSUE THREAD

**Issue by BattleBird** [ethereum/go-ethereum#21169]
when we use a bytecode which contains an "infinite loop" to test the go-ethereum, the **binary evm** will keep running and consume the memory and CPU resources until the **out of memory** and **crash**.  for example, we use this simple contract as follows,
![Screenshot from 2020-05-31 22-36-52](https://user-images.githubusercontent.com/13298978/83708346-aa1e6500-a64e-11ea-83d3-2726b4cb1aa0.png)
The command is **evm --debug --json --code run** 
#### System information

Geth version: `1.9.11`
OS & Version: Linux
Commit hash : (if `develop`)

bincode = "608060405260043610603f576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063f8a8fd6d146044575b600080fd5b348015604f57600080fd5b506056606c565b6040518082815260200191505060405180910390f35b6000806000809150600590505b60018111156094578181830201915080806001019150506079565b8192505050905600a165627a7a72305820312eb5b58f64ed74312b1ca78ec7ed036d4f11828abce1abdaa34a78b0cdef9e0029"

inputdata = "f8a8fd6d"

**Comment by MariusVanDerWijden** [comment]
same as https://github.com/ethereum/go-ethereum/issues/21153
Basically we prevent DOS by using a mechanism called gas.
Each operation on the evm costs gas. If you run a infinite loop within a normal transaction the gas mechanism would prevent the DOS. However you are trying to run the operation directly on the evm which means you surpass the safety mechanism
