### ISSUE TITLE
personal.sendTransaction not broadcasting?

### ISSUE THREAD

**Issue by AtomicLemon** [ethereum/go-ethereum#21167]
#### System information

Geth version: `Geth/v1.9.14-stable-6d74d1e5/linux-amd64/go1.14.2`
OS & Version: Linux

#### Expected behaviour
Transaction is broadcasted to the network and confirms

#### Actual behaviour
I get a tx hash in return, the tx is also added to the eth.pendingTransactions list, but never shows up in any ETH explorers and never confirms.

#### Steps to reproduce the behaviour
Try sending a transaction using personal.sendTransaction()

This is the output from eth.pendingTransactions if it helps:
```
}, {
    blockHash: null,
    blockNumber: null,
    from: "0x66ec231d3d50fd2c5a9a5242c76d91ca39a79c35",
    gas: 21000,
    gasPrice: 18010524411,
    hash: "0x9367ca24e37184f328a5b9edd67a776f98f2195803a6237d452de2e8f4fb2083",
    input: "0x",
    nonce: 5,
    r: "0x7f0e5d712072782ecb5ac39072044229d6283166a182749b0e50adce1224601f",
    s: "0x63c276600b15e7db1543fcb115c30cf94ee0948bbf7ead1200925602428ec54f",
    to: "0x4408f69a5a7ef19c5cf61309a046e735e2e38ea3",
    transactionIndex: null,
    v: "0x25",
    value: 1000000000000000
}]
```

Help would be really appreciated!

Update:
I've now tried this on both a light client and a fast sync. Both return a valid tx hash but it doesn't look like it's been broadcasted.

Update 2:
This issue occurs on both v1.9.9 and v1.9.14.

**Comment by ethbugreport** [comment]
Confirming the same issues with `Geth/v1.9.14-stable-6d74d1e5/linux-amd64/go1.14.2` on both main and ropsten networks.

Transactions are listed in `eth.pendingTransactions` and `txpool.inspect.pending`, but is not broadcasted to other peers (at least transactions are not mined to blocks and not detected by blockchain explorers such as etherscan)

Moreover after some time node decided that transaction should be dropped and reuse nonce for the furher transactions. This leads to occasional drop and replace of origin transaction.

**Comment by AtomicLemon** [comment]
@ethbugreport Thanks for reporting this as well, hopefully this issue should get some attention

**Comment by rjl493456442** [comment]
According to the gas station https://ethgasstation.info/ Now 18GWei seems a low price for transactions. Can you please re-assign a higher one? If it still doesn't work, there may exist some bugs for broadcasting.

**Comment by rjl493456442** [comment]
Are you using mainnet? https://etherscan.io/address/0x66ec231d3d50fd2c5a9a5242c76d91ca39a79c35

The current next nonce should be 2, why are you using 5 here? Maybe you have submitted a batch of transactions but they are all in the pending list and never be mined?

**Comment by AtomicLemon** [comment]
> Are you using mainnet?

Yes

> The current next nonce should be 2, why are you using 5 here? Maybe you have submitted a 
batch of transactions but they are all in the pending list and never be mined?

I'm just letting geth decide what nonce to use, I am not assigning them manually.

**Comment by karalabe** [comment]
> I'm just letting geth decide what nonce to use, I am not assigning them manually.

If you created a transaction that's too cheap for the network, that will be blocking all subsequent ones. Please check all your txs, the smallest nonce in particular as to what gas price it has.

**Comment by donald-jackson** [comment]
Just thought I'd add my similar experience here. Transaction is accepted by geth but never relayed, and never shown in pendingTransactions

eth_sendRawTransaction:

`{"jsonrpc":"2.0","id":24247,"result":"0x4ce7e971930a147eb11d9e992d1ffd6433530951561f4bd5b0a44b2487802046"}`

eth_getTransactionByHash:

`{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": null,
        "blockNumber": null,
        "from": "0x694c1133be49de3b0101fe9f8de832932ecf4ae4",
        "gas": "0xc350",
        "gasPrice": "0x12dbf9ea00",
        "hash": "0x4ce7e971930a147eb11d9e992d1ffd6433530951561f4bd5b0a44b2487802046",
        "input": "0x",
        "nonce": "0x5",
        "to": "0x07b4e975ea6dace4b037a482685d55c4d6ee1b8e",
        "transactionIndex": null,
        "value": "0x12c7102d58f2c00",
        "v": "0x26",
        "r": "0x68420503cb94f95286a3a4fd2ef2f93dde61ea7ae5d03bdae72bde6fd1eb69b2",
        "s": "0x6bc11f592ac9a38552a7c2dbe8e33f2c1e0ade97cbdcc2a7d6280c726219a313"
    }
}`

eth_pendingTransactions:

`{
    "jsonrpc": "2.0",
    "id": 71,
    "result": []
}`

web3_clientVersion:

`{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "Geth/v1.9.15-stable-0f77f34b/linux-amd64/go1.13.3"
}`

**Comment by AtomicLemon** [comment]
> If you created a transaction that's too cheap for the network, that will be blocking all subsequent ones. Please check all your txs, the smallest nonce in particular as to what gas price it has.

That's what I thought the issue would be, but I tried on a completely different address and it still wasn't relayed. Is that supposed to happen?

**Comment by rjl493456442** [comment]
@donald-jackson are you sending lots of transactions from the SAME address?

**Comment by donald-jackson** [comment]
hi @rjl493456442 - see attached - this is still happening 
![Screenshot 2020-06-15 at 12 55 48](https://user-images.githubusercontent.com/605195/84649897-9a810500-af07-11ea-8845-813d6b863fca.png)

**Comment by donald-jackson** [comment]
@rjl493456442 sorry should have also mentioned eth.pendingTransactions shows nothing pending as well.

**Comment by donald-jackson** [comment]
Sorry to thread spam but for others having this issue, the only way I was able to resolve it was to stop geth, remove ~/.ethereum/geth/transactions.rlp and then restart and relay newly created transactions.

**Comment by ca42** [comment]
We are experiencing the same behavior and is causing serious issues with our production environment:
Geth version:  Geth/v1.9.15-stable-0f77f34b/linux-amd64/go1.14.4
OS: Linux

> txpool.status
{
  pending: 137819,
  queued: 12094
}
> eth.syncing
false
> eth.pendingTransactions
[]
> 

The workaround for now is the same as @donald-jackson suggested.  I would like to mention that we have several different users sending raw transactions using their own unique addresses and once this problem manifests no transactions are broadcast from that point on regardless of who is trying to send.

**Comment by AtomicLemon** [comment]
> We are experiencing the same behavior and is causing serious issues with our production environment on mainnet

Exactly the case here too.

**Comment by rjl493456442** [comment]
I think the issue is: we truncate the pending list after inserting new transactions. Unfortunately, we evict the newly inserted transaction. https://github.com/ethereum/go-ethereum/blob/master/core/tx_pool.go#L1051

But in theory, even the transaction is excited from the local pool, it should still be broadcasted.

cc @karalabe @holiman

**Comment by rjl493456442** [comment]
@ca42 Can you try to dump the stacks by console? 

`geth attach /path/to/geth.ipc` then `debug.stacks()`.

**Comment by ca42** [comment]
@rjl493456442 I will try to get a dump to you, though it may take some time because I am unsure what conditions must be met to cause the problem.  I had to roll everything back to an older version of geth in order to get our environment stable again.  This issue didn't occur in 1.9.10 that I'm aware of, and I'm fairly certain (though I have no proof right now) that this started in version 1.9.13 as that is the first version I saw this happen on.  @AtomicLemon @donald-jackson please feel free to provide dumps as well in case you might beat me to it.

Some additional info which may or may not be relevant:
- these are fast-synced full nodes.
- the problem occurs both with and without the --txpool.nolocals flag. 
- our users connect via websockets.

**Comment by rjl493456442** [comment]
@ca42 
> our users connect via websockets.

Are they using the subscription? e.g. `newPendingTransactions`

**Comment by ca42** [comment]
@rjl493456442 Yes, they subscribe to newHeads and logs.

**Comment by ca42** [comment]
@rjl493456442 we had this happen again a couple of days ago, but this time it was on geth 1.9.12.  A customer sent raw transactions which never got broadcast but received transaction hashes for them.  I've attached the output from debug.stacks() as you requested. This may or may not be related, but our node lost sync briefly (got 7 blocks behind and then caught back up) around the same time that this occurred.  Could this possibly be related to this issue?  
https://github.com/ethereum/go-ethereum/issues/19455

More detail on the transactions that experienced this:
- The nonces are determined by the client.
- Gas prices being used are based off of what is considered fast, for example from ethgasstation.info.

debug.stacks() output:
[geth_debug.txt](https://github.com/ethereum/go-ethereum/files/4814124/geth_debug.txt)

txpool_local in Grafana (sudden drop in the middle was when stopped the node, removed transactions.rlp, and started again):
![image](https://user-images.githubusercontent.com/41489329/85315795-5353c080-b481-11ea-9f03-629ae17ee035.png)

**Comment by donald-jackson** [comment]
Apologies for not commenting more, unfortunately I had already resolved the issue using reset method above before I could do the stacks debug output. I am making use of another service now just for the relaying of raw transactions until there is a patch unfortunately as it was causing too much disruption.

**Comment by donald-jackson** [comment]
Still happening in 1.10.1 unfortunately :/

**Comment by openwse** [comment]
Same case with latest version (in dev mode) :/

Launching the client with : 
```
geth --http \
  --http.addr "0.0.0.0" \
  --http.corsdomain "*" \
  --http.vhosts "*" \
  --http.api personal,eth,net,web3 \
  --http.port 8545 \
  --ws \
  --ws.addr "0.0.0.0" \
  --ws.origins "*" \
  --ws.api eth,net,web3 \
  --ws.port 8546 \
  --verbosity 4 \
  --dev.period 14 \
  --dev
```

It works when using geth attach:
`geth attach "http://127.0.0.1:8545" --exec "personal.importRawKey('22aabb811efca4e6f4748bd18a46b502fa85549df9fa07da649c0a148d7d5530', 'deadbeaf')"`
`geth attach "http://127.0.0.1:8545" --exec "eth.sendTransaction({from:eth.coinbase, to:'0xa508dd875f10c33c52a8abb20e16fc68e981f186', value: web3.toWei(1000, 'ether')})"`
The transaction is submitted, then broadcasted.

But with my Http Client > `personal_sendTransaction` is submitted but never broadcasted. 
As @AtomicLemon i get a tx hash, but eth.pendingTransactions remains empty.
