### ISSUE TITLE
No way to get "pending" via ethclient.FilterQuery

### ISSUE THREAD

**Issue by sammy007** [ethereum/go-ethereum#21175]
https://godoc.org/github.com/ethereum/go-ethereum#FilterQuery

Since there is only bigint option, I can't set it to "pending". My proposal is to make it an interface and allow anything, just throw if case it's not a bigint or a string. Or -1 maybe, then check and serialize as "pending".

```
toBlock [optional, default is "latest"] - an integer block number, or the string "latest", "earliest" or "pending"
```

**Comment by sammy007** [comment]
Also needed for fromBlock.

**Comment by fjl** [comment]
I like the idea to use negative numbers for special purposes!

**Comment by sammy007** [comment]
There are pending, latest, earliest. Why not just make them an interface?

**Comment by sammy007** [comment]
It seems 0 is `earliest`, `pending` is `pending` and `latest` is already there anyway.

**Comment by fjl** [comment]
I don't want to change the API, that's why I liked your idea to use negative numbers.

**Comment by sammy007** [comment]
Well, the PR is using negative number for "pending" and contains some Log serialisation changes as well. @fjl is it possible to speedup the review somehow?
