### ISSUE TITLE
Updates from Turbogeth

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#21179]
There are a few interesting PRs made into Turbogeth, which we should investigate and possibly upstream.

- [x] https://github.com/ledgerwatch/turbo-geth/pull/564 (pretty trivial, LGTM)
- [x] https://github.com/ledgerwatch/turbo-geth/pull/619 (some changes to rlp list encoding)
- [x] https://github.com/ledgerwatch/turbo-geth/pull/600 (Update Secp256k1 and tune its flags for performance: a pretty huge PR, would probably take some time to go through)

cc @AlexeyAkhunov any other tips for us?

**Comment by AlexeyAkhunov** [comment]
There are also a few PRs that introduce your `uint256` types in at lot places, to reduce garbage production.

**Comment by holiman** [comment]
Yeah, I've seen that! That's great, and I think the plan is to merge the uint256 after next release
