### ISSUE TITLE
Multiple blocks with same timestamp in clique network.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/go-ethereum#21184]
#### System information
Geth version: `1.9.10`
OS & Version: Docker

#### Expected behaviour
When mining a new block, its timestamp should always be higher than the timestamp of its parent.

#### Actual behaviour
When mining a new block in a clique network it is possible to sometimes end up with two blocks in a row that share a timestamp.

#### Steps to reproduce the behaviour
1. Setup a clique node with a `period` of `0` or run `docker container run --rm -it -p 8545:8545 keydonix/geth-clique`
2. Submit two transactions back to back in rapid succession (less than 1 second between them).
3. Notice that two blocks are mined (one containing each transaction) and they both have the same timestamp (if they don't run test again).

## Thoughts
I can appreciate that if the throughput of a clique chain with a block time of 0 is higher than 1 transaction per second you may end up far in the future if every block is always *at least* `parentblock.timestamp + 1`, I suspect that anyone running a one-transaction-per-block clique chain is doing it for testing and they likely don't care about time running into the future.  Further, if they are running a test chain, then it should try to mimick the real chain int as many ways as possible which includes the mainnet guarantee that `block.timestamp > block.parent.timestamp`.  At the moment, this guarantee is not upheld in clique networks and it can lead to failures in test that wouldn't present themselves in production.

If it is believed that some users desire the behavior of multiple blocks in a row sharing a timestamp, then perhaps an option can be added to the clique config that tells it whether to maintain consistency with the system clock, or maintain internal consistency with the chain.

**Comment by karalabe** [comment]
The Geth code is architected to ignore blocks in the future. It would be very messy for us to support a corner case where future blocks are permissible. Why is it important to reject same timestamps? In theory a PoW chain (mainnet) could also mine two blocks in the same second and they should be valid.

**Comment by holiman** [comment]
https://github.com/ethereum/go-ethereum/blob/master/consensus/ethash/consensus.go#L257 : 

```golang
	if header.Time <= parent.Time {
		return errOlderBlockTime
	}
```

So for ethash it's not allowed to have same time on consecutive blocks

**Comment by holiman** [comment]
Yeah, so this is only ever an issue in clique if the chain is configured with `0` interval blocks

```golang
	if parent.Time+c.config.Period > header.Time {
		return errInvalidTimestamp
	}
```

**Comment by MicahZoltu** [comment]
Clique has to break one of the two PoW consensus rules.  Either it breaks the "no future blocks" rule or it breaks the "blocks must have timestamp greater than parent blocks" rule.  As someone who uses clique for testing (which I *suspect* is when this comes up), ensuring that block timestamps are consecutive is more useful than disallowing future blocks because in test.

If the internal architecture of Geth makes this a particularly challenging change, I can appreciate that and I'll just have to use other clients for testing (the stuff I'm testing requires blocks follow the consecutive block timestamp consensus rules).  I personally think that violating the "time in the future" is a better choice for testing than violating the "block timestamps are consecutive", but maybe there is a use-case for choosing the other way around?

**Comment by holiman** [comment]
>  Either it breaks the "no future blocks" rule or

There's no such rule in ethash. There's a loose agreement between clients to not import blocks that are too far off in the future though, but it's not a consensus-rule. 

>  or it breaks the "blocks must have timestamp greater than parent blocks" rule. 

Yeah, well, it has it's own rule, which is the a configurable via `c.config.Period`. If it's set to zero then it's set to zero. 

I guess what you'd want is maybe having `1` blocktime, but _combined_ with "don't mine empty blocks"?

**Comment by MicahZoltu** [comment]
> I guess what you'd want is maybe having 1 blocktime, but combined with "don't mine empty blocks"?

@holiman For testing I explicitly want the ability to mine *many* blocks per second.  I very much don't want it to wait for a full second when running a test suite that requires mining thousands of blocks.  😀  Anything that rate limits block creation automatically is a non-starter for anything short of full integration tests against a public network for *all* of my projects.

Separately, for the project I'm currently working on (which I admit is a bit niche in its requirements) I have a dependency on `block.timestamp` moving forward during testing.  For the same reason as above, I don't want to have my test suite sleep just to get time to move forward because that would make my tests take *forever* since a single test run mines over a hundred blocks (and I have only just started building out the suite).  Nethermind (and I think Parity) when running in their instant-block-mining mode will set the block.timestamp to `max(now, parentBlock.timestamp + 1)` which is great for testing because time does move forward at a rate of ~1 second per block (though not *exactly* that) but I am not rate limited in the speed at which my tests can burn through blocks.

**Comment by holiman** [comment]
The current limit in geth is that it won't import a block which is `>30s` in the future. If we add a hack to the miner to bump the timestamp, it would still only allow you to operate on 30 blocks per second. Doing a more thorough rewrite of geth-internals to gracefully handle this case is probably not worth it, IMO. 

Not sure what to do here. It's not an error in clique or geth per se, but you have a particular usecase which doesn't work well with how Clique works...

**Comment by holiman** [comment]
I think you're going to have to work with the throttling on your end to handle this. We've decided it's not sufficiently motivated to make any changes at this point, so closing this.

**Comment by MicahZoltu** [comment]
Thanks for closing this with a clear reason why.  😄 (too many GitHub issues just sit forever in an indecisive state).  I think my solution will be to just not test with Geth if I have code that cares about `block.timestamp`.  It is unfortunate, but I at least understand why things are the way they are now so thanks!
