### ISSUE TITLE
Proof Of Authority Clique Block Period 0 does not seal blocks even on pending txs

### ISSUE THREAD

**Issue by cyrilnavessamuel** [ethereum/go-ethereum#21189]
Hi there,

#### System information

Geth version: 1.9.12
OS & Version: Linux
Clique PoA
Processor: Intel i7 - 3770
CPU: 8
RAM : 16 GB
txpool.global slot : 100000000

#### Expected behaviour
Clique Block Period 0 should seal blocks when there is pending transaction in the network.

#### Actual behaviour
When I tested for set of 200000 transactions which invokes a simple smart contract method of addition repetitively. After some transactions are sealed into a block, sealing of blocks is stopped even when there are pending transactions in the network. 70000 txs are pending

During the pending transaction state, Again when some more transactions 200000 are sent it starts to seal again and then stops again with some transactions being in pending state. 50000 txs are pending this time.

#### Steps to reproduce the behaviour

Send transaction in block period 0 for large no of transactions continuously 200000.

No of sealers in network : 4

In case of replication, please refer https://github.com/cyrilnavessamuel/ethereumissue which contains client script and smart contract file which can be used

**Comment by rjl493456442** [comment]
Can you retrieve the txpool status via console(`txpool.status`)? My hunch is there exists nonce gap so all following transactions can't be packed.

**Comment by cyrilnavessamuel** [comment]
Hello,
Sorry for the delay in my response.

Yes I have checked it as well to identify a nonce gap which would result in transaction stocked in queue.

So I reran the tests with block period 0 having 4 Geth Nodes as sealers in the network.
I sent 100000 transactions out of which only 12500 txs were processed onto block.
I ran txpool.status on 4 Nodes individually:
Node A: 
 txpool.status
{
  pending: 87495,
  queued: 0
}
Node B: txpool.status
{
  pending: 3951,
  queued: 1024
}
Node C: 
txpool.status
{
  pending: 0,
  queued: 0
}
 txpool.status
{
  pending: 3951,
  queued: 1024
}

So It means results are varied with each Nodes, with 2 Nodes having same status of txpool.

On looking at the logs:
Node A & Node D: 
Wait for block seal to be signed by the other Nodes

Log Excerpt: Commit new mining work                   number=24 sealhash=f86454…d030ac uncles=1 txs=3951 gas=149746851 fees=1.49746851e-10 elapsed=211.618ms


Node B & Node C:
Log Excerpt:
INFO [07-01|15:36:03.822] Looking for peers                        peercount=3 tried=1 static=0

I can confirm there is no Nonce gap in the network.

Cheers,
Cyril

**Comment by holiman** [comment]
This is a bit odd. I suspect that it's `B`'s turn to mine, and `B` knows no transactions. In order to figure this out, I think we don't have sufficient logs (the logs from C for example). Sorry it's taken so long to respond. 
Do you have a script to repro this? Could you publish it as a gist or repository?

**Comment by karalabe** [comment]
Without more information sadly there's no way to continue. Please open a new PR if it happens again with a bit more information and logs from various nodes.
