### ISSUE TITLE
Geth Clique Block Period 1, Fork of Chain inconsistency

### ISSUE THREAD

**Issue by cyrilnavessamuel** [ethereum/go-ethereum#21191]
Hi there,

I am posting this bug which is already discussed but is inactive https://github.com/ethereum/go-ethereum/issues/18402.

Moreover the bug which I post here is a slight modification of the one posted in [18402](https://github.com/ethereum/go-ethereum/issues/18402)

I have also posted in stack exchange which didn't have much response: https://ethereum.stackexchange.com/questions/83357/geth-clique-block-period-1-fork-of-chain-inconsistency

#### System information

Geth version: 1.9.12
OS & Version: Linux
Clique PoA
Processor: Intel i7 - 3770
CPU: 8
RAM : 16 GB
TXPOOL.GlobalSlots: 100000000
Block Period 1 or 2 (Faster block times)
No of Sealers/ Nodes : 4

#### Expected behaviour
Block Period 1 / 2 / 3  (Shorter block times)  fork is  created but should be resolved or reorged atleast
#### Actual behaviour

In my private Clique network with 4 Nodes (A,B,C,D) I noticed a fork in the chain for block period 1.

I noticed that it happens some times with block period 1 & 2.

I noticed that the fork happens at block 1678 . Nodes A & D have a similar chain data meanwhile Nodes B& C have similar data.

At block 1677, I noticed the difference in data between 2 chains: 
1) Block hashes are different 
2) Block of one chain is an uncle block while for other chain it has 5000 txs included 
3) Both blocks have **same difficulty 2** which means that it was mined in turn
 4) Another complication arises when I noticed it was the **same sealer** who sealed the block.

This results in fork of the network and stalling at the end which cannot undergo any reorg in this deadlock situation.

#### Steps to reproduce the behaviour
1) Setup PoA Clique network with block period 1 / 2
2) No of Nodes/ Sealers : 4
3) Send transactions faster to invoke smart contract method. Eg client available in : https://github.com/cyrilnavessamuel/ethereumissue 
4) You will notice fork when the nodes stop mining and when you debug the issue looking at the latest block header.
#### Backtrace

Latest Block 1678 details in Node A:
![1](https://user-images.githubusercontent.com/8938494/84015754-9f304100-a97c-11ea-91ed-4db143bb23ce.jpg)
 Block 1677 fork occured between Node A & Node C on 1 fork and other fork having Node B & Node D.
Notice the 
difference in block hash , 
different no of txs in block (1 fork has 0 txs and other has 4791 txs)
**same difficulty** in both forks
Fork 1 details: Node A & Node D
![2](https://user-images.githubusercontent.com/8938494/84016121-1b2a8900-a97d-11ea-82ed-4fb52e2dd1eb.jpg)
Fork 2 details: Node B & Node C
![3](https://user-images.githubusercontent.com/8938494/84016180-30071c80-a97d-11ea-9be6-1b38438932c0.jpg)
Note: Fork 2 image is different since 4791 txs were printed which was too large;

**Comment by holiman** [comment]
The curios thing here is that one miner mined two different variants of block `1676`, one empty and the other with `4791` transactions. It _could_ be that there's a race here somewhere, since the default behaivour of the miner is to start mining an empty block, and then update the work as transactions come in.

**Comment by holiman** [comment]
A blocktime of `1` second, combined with a `gasLimit` of `250M`, filled with thousands of transactions probably hits some cornercase in the miner.

**Comment by karalabe** [comment]
You gas limit seems to be insanely large (250M), and you block time quite small (1-3s). How much time do nodes need to actually process one such block? If the block processing times exceed the period, you can end up in very strange scenarios where signers start to race with themselves betwene importing/mining.

**Comment by karalabe** [comment]
Perhaps if you could share normal operational logs so we can see how heavy subsequent blocks are, how much time they take, etc.

**Comment by cyrilnavessamuel** [comment]
Thanks Martin and Peter for looking into the issue. I'll try to recreate the scenario and share the operational logs of it.
Cheers

**Comment by cyrilnavessamuel** [comment]
Hello All,

Sorry for the time to reproduce the issue.

This time I got with the same configuration (Block period 1) and with three scripts sending concurrently to 3 nodes from a 4 node blockchain network. Fork Happened at block 109. Although the fork happened and stuck there, the same node sealing two varieties of block was not reproduced.

Node A & Node B on one Fork
![NodeA B](https://user-images.githubusercontent.com/8938494/86258197-d5975f80-bbba-11ea-96a0-e9636734bc36.PNG)

Node C & Node D on other Fork;
![NodeC D](https://user-images.githubusercontent.com/8938494/86258221-dcbe6d80-bbba-11ea-9bae-3a90d635137a.PNG)

Please find the attached log files of 4 Nodes in zip file on google drive since the file is some what big.

[https://drive.google.com/file/d/18E-0DHueFt3OOYb51Y7s0M5tYEGzPZvV/view?usp=sharing](Logs)

Thanks for looking,
Cheers

**Comment by fnaticwang** [comment]
This problem has been around for almost a year and we still haven't solved it.

**Comment by sambacha** [comment]
try the following changes:

## Genesis file changes 
change gasblock to: `1DCD6000` 
delete: `"petersburgBlock": 0,`

### period time 
```
*where*, `OUT_OF_TURN_DELAY_MULTIPLER` == 500ms
*where*, `MIN_OUT_OF_TURN_DELAY` == your_desired_period (in this case `2000ms`

${G_PERIOD} == [ MIN_OUT_OF_TURN_DELAY + rand(SIGNER_COUNT * OUT_OF_TURN_DELAY_MULTIPLER) ]
```
so that you change: `period: ${G_PERIOD}` in your `genesis` file. 


make sure your closing connections as well, 
`netstat -a | grep 8545 | wc -l` 

### additional 
Clique out of turn is a known issue, the best practices are

**Comment by holiman** [comment]
I think the root problem here is 

> No of Nodes/ Sealers : 4

If you'd had `5` instead, the situation would be less prone to chain ties (2 sealers vs 2 sealers), and you'd have a natural tie-breaker.
