### ISSUE TITLE
Storage field in debug_traceTransaction traces does not include storage read from, only written to

### ISSUE THREAD

**Issue by haltman-at** [ethereum/go-ethereum#21198]
#### System information

Geth version: 1.9.15-stable
OS & Version: Release Linux Mint 19.1 Tessa 64-bit

#### Expected behaviour

The trace output from `debug_traceTransaction`, in its `storage` field for each step, should include both all storage written to so far during the current call, and all storage read from so far during the current call.

By way of comparison, Ganache does this; now I know Geth invented `debug_traceTransaction`, and so gets to define what it does, but this seems like a distinct omission of relevant information, as storage read from is definitely relevant to the transaction.

#### Actual behaviour

Only storage written to is included; storage read from is omitted.  This causes problems for debuggers based on `debug_traceTransaction`.  For instance, storage variables will erroneously display as zero even after they've been read from, which is confusing when debugging.

(Reason I'm filing this bug: I'm the maintainer of the Truffle Debugger, and there, in addition to the above, it could possibly cause the wrong mapping keys to be kept track of.  If you want to see the discussion of this over on our GitHub, it's on [this issue](https://github.com/trufflesuite/truffle/issues/2066).)

#### Steps to reproduce the behaviour

Start geth with `geth --dev --http --http.api eth,net,debug`.  Deploy the following contract:

```solidity
pragma solidity ^0.5.16;

contract DebugTest {
  uint zr;
  uint nzr = 1;
  uint zwz;
  uint zwnz;
  uint nzwz = 2;
  uint nzwnz = 3;
  uint zwr;
  uint nzwr;

  function run() public {
    uint x;
    x = zr; //read zero
    x = nzr; //read nonzero
    zwz = 0; //write zero to zero
    zwnz = 4; //write nonzero to zero
    nzwz = 0; //write zero to nonzero
    nzwnz = 5; //write nonzero to nonzero
  }
}
```

Send a transaction for the `run()` function.  Use `debug_traceTransaction` on the result; since everything's within the same call, we can just look at the final trace step.  Observe that its `storage` field contains entries for storage slots 2 through 5, but not 0, 1, 6, or 7.

Thank you!

**Comment by rjl493456442** [comment]
Hi @haltman-at, I have a version for generating tracing logs include storage read.

I am curious about your requirement and want to confirm. Now we can offer storage read/write until this instruction. But the storage can be overwritten. 

e.g. If we write a slot twice with two different value, then the written storage in this 2 instructions is different. I guess it can work with your debugger?

example output
```
storage: {
        0000000000000000000000000000000000000000000000000000000000000002: "0000000000000000000000000000000000000000000000000000000000000000",
        0000000000000000000000000000000000000000000000000000000000000003: "0000000000000000000000000000000000000000000000000000000000000004",
        0000000000000000000000000000000000000000000000000000000000000004: "0000000000000000000000000000000000000000000000000000000000000000",
        0000000000000000000000000000000000000000000000000000000000000005: "0000000000000000000000000000000000000000000000000000000000000005"
      },
      storageRead: {
        0000000000000000000000000000000000000000000000000000000000000000: "0000000000000000000000000000000000000000000000000000000000000000",
        0000000000000000000000000000000000000000000000000000000000000001: "0000000000000000000000000000000000000000000000000000000000000001"
      },
      storageWritten: {
        0000000000000000000000000000000000000000000000000000000000000002: "0000000000000000000000000000000000000000000000000000000000000000",
        0000000000000000000000000000000000000000000000000000000000000003: "0000000000000000000000000000000000000000000000000000000000000004",
        0000000000000000000000000000000000000000000000000000000000000004: "0000000000000000000000000000000000000000000000000000000000000000",
        0000000000000000000000000000000000000000000000000000000000000005: "0000000000000000000000000000000000000000000000000000000000000005"
      }
```

**Comment by rjl493456442** [comment]
The storage is kept for backward compatibility

**Comment by haltman-at** [comment]
Well, I'm not trying to separately keep track of storage read and storage written.  Rather I'm thinking of the `storage` field as a partial view of storage as it currently exists.  Obviously it's not all of it, only the relevant parts.  The question then is what counts as relevant.

Like right now, if you have two storage writes to the same slot, the later one will overwrite the earlier one.  This does not make sense from a point of view where `storage` is meant to record every write and read, but *does* make sense from a point of view where `storage` provides a partial view of storage, restricted to the relevant parts, which is the point of view I'm taking.  I want to stick to that point of view; I don't want to change to a point of view of individually keeping track of each read and write.

From that point of view, then, as soon as a storage slot is read, it should be considered relevant and shown.  Sure, the read value may be overwritten later -- but that's fine!  Storage has changed so what we see of it should change correspondingly.  Like I said, I'm working from a "partial view of storage" point of view, not a "record of reads and writes" point of view, with the only question being what is deemed sufficiently relevant to be included in that partial view.

As mentioned, Ganache's version of `debug_traceTransaction` already works this way, and I was a little surprised to find that Geth doesn't do this.  Note that this would be useful not just for Truffle Debugger in particular, but for all `debug_traceTransaction`-based debuggers, of which I believe there are several (Remix being the other big one).  I doubt there would realistically be any compatibility problem.  I mean, I suppose technically it would break things for any programs that rely on `storage` *only* containing storage written, but I don't know that that exists.  For debuggers I think it would be just upside.

Of course, if the behavior of `storage` really cannot be changed for compatibility reasons, then `storageRead` and `storageWritten` is certainly something we could work with, but I think what would be better would be to add `storageView` (or whatever you want to call it) that works like I suggest, like Ganache's `storage`; that would be simpler to work with.  Given, as mentioned, that I'm interested in a partial view of storage, rather than a record of reads and writes.

Hope that makes sense, thanks for listening!

**Comment by karalabe** [comment]
I agree with @haltman-at on this one. We should simply add to the returned `storage` the data items read too.
