### ISSUE TITLE
[Feature Request] Display maximumStates in cli status

### ISSUE THREAD

**Issue by greywolf42069** [ethereum/go-ethereum#21194]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `current / all'
OS & Version: Windows/Linux/OSX

#### Expected behaviour
Trying to sync a node in fast mode should have a way to indicate to the user what percentage of complete it is at, normally you check the synced blockheight but this is not as relevant in fast mode..

Checking the network information should show this:

{
  currentBlock: 10225520,
  highestBlock: 10225628,
  knownStates: 316323862,
  pulledStates: 316298797,
  maximumStates: 4XXXXXXXX,
  startingBlock: 10225050
}

#### Actual behaviour
{
  currentBlock: 10225520,
  highestBlock: 10225628,
  knownStates: 316323862,
  pulledStates: 316298797,
  startingBlock: 10225050
}
There is no way to know what your progress is..

#### Steps to reproduce the behaviour
Sync node in fast mode

**Comment by karalabe** [comment]
The node doesn't know how many states there are. It's a Merkle trie, expanded as it goes along. It has no clue how deep or wide newly found branches are.

We're working on snap sync that will have progress support.
