### ISSUE TITLE
Geth skipping-empty-blocks preload-option of js file doesnt work and also option to set gas target and gas limit  missing in api

### ISSUE THREAD

**Issue by cyrilnavessamuel** [ethereum/go-ethereum#21190]
Hi there,

I am not posting this as a bug since I need some information which I unable to get help from stack exchange: https://ethereum.stackexchange.com/questions/83931/ethereum-skipping-empty-blocks-preload-option-doesnt-work 

#### System information

Geth version: 1.9.12
OS & Version: Linux
Clique PoA
Processor: Intel i7 - 3770
CPU: 8
RAM : 16 GB

#### Expected behaviour

In my clique PoA private network setup I try to mine skipping empty blocks and mine only when there is transaction present. I try to follow : How to make miner to mine only when there are Pending Transactions? but I cannot notice that the mining works when I load the script with -- preload followed by .js file.

Instead on starting the node, I open the ipc console and then use loadScript which works fine.

1) Is there a better way to load the js script while starting the node?

2) Also is there a way to specify inside the js script the **miner gas target** and **miner gas limit** since I need to set up a uniform block gas limit in the network. I noticed that this option is missing in RPC API definitions which could be the reason ?

#### Actual behaviour
--preload option with js file while starting a client doesnt work but instead loadScript works

Option to set **miner gas target** and **miner gas limit**  withing the javascript file is not possible since there is no api method to set this

#### Steps to reproduce the behaviour

1) Start the geth client without mining option enabled
2) Then get the script https://ethereum.stackexchange.com/questions/3151/how-to-make-miner-to-mine-only-when-there-are-pending-transactions/3152#3152 and save it as .js file
3) The while starting the geth client try to load the script with --preload javascriptfile.js
4) Mining does not start even when there are pending transactions
5) Instead open the ipc console and use loadScript passing javascript file which loads the script successfully
6) Mining starts and stops properly as in script

**Comment by holiman** [comment]
I agree about these semantics: `--preload` _should_ work the same was as starting with `console` and then loading the script.

**Comment by s1na** [comment]
I just tried this on v1.10.19 and it's working. I have a node running clique with mining disabled. Then I attach to it and pass `--preload mine.js`. Sending txes results in mining getting activated:

```console
❯ ./build/bin/geth --datadir clique-data --preload mine.js attach
== No transactions! Mining stopped.
Welcome to the Geth JavaScript console!

instance: Geth/v1.10.19-stable-23bee162/darwin-amd64/go1.18
coinbase: 0xa724065f3e3168fbf96d97c2d008bb91251feb38
at block: 0 (Thu Jan 01 1970 01:00:00 GMT+0100 (CET))
 datadir: /go-ethereum/clique-data
 modules: admin:1.0 clique:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

To exit, press ctrl-d or type exit
> personal.unlockAccount(eth.accounts[0], '', 0)
true
> eth.sendTransaction({ from: eth.accounts[0], to: eth.accounts[0], value: 1 })
"0xd89c038a7efaee046b7b50abf2c7846cd7d8665e28e612d8aceace1c4a016f23"
> == Pending transactions! Mining...
== No transactions! Mining stopped.

> == No transactions! Mining stopped.
```
