### ISSUE TITLE
mist on qt 5.4.0 panic: unsupported variant type: 1024 (QJSValue)

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#212]
With QT 5.4.0, works fine on QT 5.3.2.

```
$ mist
2014/12/16 12:53:26 [CLI] Main address e71de707f05da29b62325a19cf1e24f452f95684
2014/12/16 12:53:36 [CHAIN] Last block (#0) 779b1b620b03c0fb24963e183d5e88e3dbe4484e3f6e2aa05942e3be7b48e179
ETH stack took 10.019111037s
2014/12/16 12:53:36 [GUI] Starting GUI
2014/12/16 12:53:36 [CLI] Starting Mist/v0.7.9/darwin/go1.4
2014/12/16 12:53:36 [SERV] Ready and accepting connections
2014/12/16 12:53:36 [JSRE] started
panic: unsupported variant type: 1024 (QJSValue)

goroutine 1 [running, locked to thread]:
gopkg.in/qml%2ev1.hookPanic(0x12d22200)
	/private/tmp/go-ethereum-49DUTo/src/gopkg.in/qml.v1/bridge.go:631 +0x8d
gopkg.in/qml%2ev1._Cfunc_componentCreateWindow(0xee03c40, 0x0, 0x0)
	/private/tmp/go-ethereum-49DUTo/src/gopkg.in/qml.v1/:83 +0x44
gopkg.in/qml%2ev1.func·026()
	/private/tmp/go-ethereum-49DUTo/src/gopkg.in/qml.v1/qml.go:750 +0x56
gopkg.in/qml%2ev1.hookIdleTimer()
	/private/tmp/go-ethereum-49DUTo/src/gopkg.in/qml.v1/bridge.go:190 +0x60
gopkg.in/qml%2ev1._Cfunc_applicationExec()
	/private/tmp/go-ethereum-49DUTo/src/gopkg.in/qml.v1/:59 +0x45
gopkg.in/qml%2ev1.Run(0x4aa3510, 0x0, 0x0)
	/private/tmp/go-ethereum-49DUTo/src/gopkg.in/qml.v1/bridge.go:63 +0x204
main.main()
	/private/tmp/go-ethereum-49DUTo/src/github.com/ethereum/go-ethereum/cmd/mist/main.go:94 +0x72
```

**Comment by tgerring** [comment]
I was able to work around this bug by downgrading to 5.3.2 and clearing out some old packages:

First, force checkout the specific commit for QT 5.3.2 in brew:
```
cd $( brew --prefix ) && git checkout 4f25f52 /usr/local/Library/Formula/qt5.rb
```

Update environment variables to point to 5.3.2:
```
export PKG_CONFIG_PATH=/usr/local/Cellar/qt5/5.3.2/lib/pkgconfig
export CGO_CPPFLAGS="-I/usr/local/Cellar/qt5/5.3.2/include/QtCore/5.3.2/QtCore"
export LD_LIBRARY_PATH=/usr/local/Cellar/qt5/5.3.2/lib
```

Remove QML references and re-get all dependencies: 
```
rm -rf $GOPATH/src/gopkg.in/qml.v*
ETH_DEPS=$(go list -f '{{.Imports}} {{.TestImports}} {{.XTestImports}}' github.com/ethereum/go-ethereum/... | sed -e 's/\[//g' | sed -e 's/\]//g' | sed -e 's/C //g'); if [ "$ETH_DEPS" ]; then go get $ETH_DEPS; fi
```

Re-install mist:
```
go clean && go install && mist
```

**Comment by caktux** [comment]
If you already had 5.3.2, you can probably just `brew switch qt5 5.3.2` instead.

**Comment by obscuren** [comment]
Submitted possible solution to go-qml repo. See: https://github.com/go-qml/qml/issues/137

**Comment by jinserk** [comment]
using brew only, I've resolve this as follows:

As tgerring commented, first you checked the qt 5.3.2 from doing this:
```
cd $( brew --prefix ) && git checkout 4f25f52 /usr/local/Library/Formula/qt5.rb
```

Then, just reinstall qt5 using brew:
```
brew reinstall qt5
```

Switch qt5 to 5.3.2:
```
brew switch qt5 5.3.2
```

finally reinstall go-ethereum:
```
brew reinstall go-ethereum
```

**Comment by obscuren** [comment]
Fixed `go-qml` and created PR https://github.com/go-qml/qml/pull/140

**Comment by fivedogit** [comment]
I'm having runtime errors for mist as well. qt is v 5.2.1 which is the most up-to-date version for ubuntu 14.04.1 LTS. I don't know much about go and I'm just getting into testing ethereum for the first time, so maybe I've missed something obvious. I tried the suggestion of moving the asset_path, but it didn't help. "mist/qml/main.qml" doesn't exist anywhere on my system. Is there something separate I need to install (go-qml?) or do I simply have a QT version issue like OP?

----------------------------
$ qmake -v
QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu

$ ./mist 
2015/01/26 23:00:39 [CLI] Main address 2a77104eb7754c8e30c55b028bbf2bda4299187d
2015/01/26 23:00:40 [CHAIN] Last block (#0) 779b1b620b03c0fb24963e183d5e88e3dbe4484e3f6e2aa05942e3be7b48e179
ETH stack took 321.450706ms
2015/01/26 23:00:40 [GUI] Starting GUI
2015/01/26 23:00:40 [CLI] Starting Mist/v0.7.11/linux/go1.2.1
2015/01/26 23:00:40 [SERV] Ready and accepting connections
2015/01/26 23:00:40 [JSRE] started
2015/01/26 23:00:40 [GUI] asset not found: you can set an alternative asset path on the command line using option 'asset_path' open /usr/share/mist/qml/main.qml: no such file or directory
panic: open /usr/share/mist/qml/main.qml: no such file or directory

goroutine 7 [running]:
runtime.panic(0xa38b40, 0xc210e1dc30)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.(*Gui).Start(0xc210062c60, 0xb42bf0, 0xf)
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/cmd/mist/gui.go:161 +0x54d
main.run(0xc49760, 0x0)
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/cmd/mist/main.go:83 +0x65f
gopkg.in/qml%2ev1.func·002()
	/home/cyrus/gocode/src/gopkg.in/qml.v1/bridge.go:60 +0x46
created by gopkg.in/qml%2ev1.Run
	/home/cyrus/gocode/src/gopkg.in/qml.v1/bridge.go:62 +0x17b

goroutine 1 [syscall]:
gopkg.in/qml%2ev1._Cfunc_applicationExec(0xa79cc0)
	gopkg.in/qml.v1/_obj/_cgo_defun.c:57 +0x31
gopkg.in/qml%2ev1.Run(0xc4b2a8, 0x19, 0xb42cb0)
	/home/cyrus/gocode/src/gopkg.in/qml.v1/bridge.go:63 +0x182
main.main()
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/cmd/mist/main.go:94 +0x6b

goroutine 3 [select]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/logger/loggers.go:78 +0x512
created by github.com/ethereum/go-ethereum/logger.init·1
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/logger/loggers.go:57 +0x21

goroutine 4 [syscall]:
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1394

goroutine 6 [syscall]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 8 [chan receive]:
github.com/ethereum/go-ethereum/logger.sysLoop(0x7fadf6886b48, 0xc210093c30, 0xc2100e2000, 0xc21004b860)
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/logger/loggers.go:114 +0x3d
created by github.com/ethereum/go-ethereum/logger.func·001
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/logger/loggers.go:74 +0x12d

goroutine 9 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc210044540)
	/home/cyrus/gocode/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x1e7
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/home/cyrus/gocode/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x224

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc21005e840)
	/home/cyrus/gocode/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x397
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/cyrus/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x4d8

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc21005e840)
	/home/cyrus/gocode/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73 +0x104
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/cyrus/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x4ef

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc21005e840)
	/home/cyrus/gocode/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:812 +0x6a8
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/cyrus/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x530

goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc21005e840)
	/home/cyrus/gocode/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x1f3
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/cyrus/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x547

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc21005e840)
	/home/cyrus/gocode/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x13d
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/cyrus/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x55e

goroutine 25 [syscall]:
net._C2func_getaddrinfo(0x7fadac0008c0, 0x0, 0xc210923bd0, 0xc210000fc0, 0xc2100f6410, ...)
	net/_obj/_cgo_defun.c:50 +0x36
net.cgoLookupIPCNAME(0xb614d0, 0xc, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/pkg/net/cgo_unix.go:96 +0x174
net.cgoLookupIP(0xb614d0, 0xc, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/pkg/net/cgo_unix.go:148 +0x69
net.lookupIP(0xb614d0, 0xc, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/pkg/net/lookup_unix.go:64 +0x63
net.func·022(0x14b19a0, 0xc210923ba0, 0xb614d0, 0xc)
	/usr/lib/go/src/pkg/net/lookup.go:41 +0x2d
net.(*singleflight).Do(0x14b19a0, 0xb614d0, 0xc, 0x7fade4141b58, 0x0, ...)
	/usr/lib/go/src/pkg/net/singleflight.go:45 +0x1de
net.lookupIPMerge(0xb614d0, 0xc, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/pkg/net/lookup.go:42 +0xc0
net.LookupIP(0xb614d0, 0xc, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/pkg/net/lookup.go:31 +0x63
github.com/ethereum/go-ethereum.(*Ethereum).Seed(0xc2100d3000)
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:439 +0x415
github.com/ethereum/go-ethereum.(*Ethereum).Start(0xc2100d3000, 0xb4b501)
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:420 +0x249
github.com/ethereum/go-ethereum/cmd/utils.StartEthereum(0xc2100d3000, 0x14af801)
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:163 +0x112
created by main.run
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/cmd/mist/main.go:78 +0x524

goroutine 26 [select]:
github.com/ethereum/go-ethereum.(*BlockPool).downloadThread(0xc210936000)
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/block_pool.go:247 +0x226
created by github.com/ethereum/go-ethereum.(*BlockPool).Start
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/block_pool.go:235 +0x2e

goroutine 27 [select]:
github.com/ethereum/go-ethereum.(*BlockPool).chainThread(0xc210936000)
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/block_pool.go:294 +0x877
created by github.com/ethereum/go-ethereum.(*BlockPool).Start
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/block_pool.go:236 +0x45

goroutine 28 [IO wait]:
net.runtime_pollWait(0x7fadf6888d80, 0x72, 0x0)
	/usr/lib/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc21009d680, 0x72, 0x7fadf6886368, 0xb)
	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc21009d680, 0xb, 0x7fadf6886368)
	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).accept(0xc21009d620, 0xc4d618, 0x0, 0x7fadf6886368, 0xb)
	/usr/lib/go/src/pkg/net/fd_unix.go:382 +0x2c2
net.(*TCPListener).AcceptTCP(0xc210000fb0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/pkg/net/tcpsock_posix.go:233 +0x47
net.(*TCPListener).Accept(0xc210000fb0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/pkg/net/tcpsock_posix.go:243 +0x27
github.com/ethereum/go-ethereum.(*Ethereum).peerHandler(0xc2100d3000, 0x7fadf688df08, 0xc210000fb0)
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:481 +0x2d
created by github.com/ethereum/go-ethereum.(*Ethereum).Start
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:407 +0x436

goroutine 29 [chan receive]:
github.com/ethereum/go-ethereum.(*Ethereum).reapDeadPeerHandler(0xc2100d3000)
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:387 +0x67
created by github.com/ethereum/go-ethereum.(*Ethereum).Start
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:415 +0x1f8

goroutine 30 [select]:
github.com/ethereum/go-ethereum.(*Ethereum).update(0xc2100d3000)
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:574 +0x1da
created by github.com/ethereum/go-ethereum.(*Ethereum).Start
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:416 +0x212

goroutine 31 [chan receive]:
github.com/ethereum/go-ethereum.(*Ethereum).filterLoop(0xc2100d3000)
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:618 +0x143
created by github.com/ethereum/go-ethereum.(*Ethereum).Start
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:417 +0x22c

goroutine 32 [chan receive]:
github.com/ethereum/go-ethereum/javascript.(*JSRE).mainLoop(0xc210960330)
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/javascript/javascript_runtime.go:110 +0x51
created by github.com/ethereum/go-ethereum/javascript.NewJSRE
	/home/cyrus/gocode/src/github.com/ethereum/go-ethereum/javascript/javascript_runtime.go:69 +0x253

**Comment by fivedogit** [comment]
Ok. Sorry. I got mist to execute just now on 5.2.1 anyway.
