### ISSUE TITLE
The process EVM is terminated automatically when it detect an "infinite loop" 

### ISSUE THREAD

**Issue by BattleBird** [ethereum/go-ethereum#21215]
when I use the binary EVM to run the following code,
./evm_1_9_11 --debug --json --code 608060405260043610603f576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063f8a8fd6d146044575b600080fd5b348015604f57600080fd5b506056604f565b6040518082815260200191505060405180910390f35b6000806000809150600090505b6101008110156095578181830201915080806001019150506079565b8192505050905600a165627a7a723058209532f82c5915ea5c48e4bec8d992af9c7b0000000000000000000000c467441af9aaf8c53a5bb7d6074e680029 --input f8a8fd6d run

System information
Geth version: 1.9.11
OS & Version: Linux
Commit hash : (if develop)

Expected behaviour
evm will keep running because there is enough gas

Actual behaviour
process is terminated after running a few second

Steps to reproduce the behaviour
The bytecode THAT I provided above contains an "infinite loop"

Backtrace
[backtrace]
![trace_geth](https://user-images.githubusercontent.com/13298978/84346040-98eece80-abe1-11ea-89ca-ed44681e1be6.png)

**Comment by BattleBird** [comment]
I know restricting the gas limit is the only way to detect (or rather protect against) infinite loops. However, in this example, the program has enough gas limit. As the trace picture shows, the remaining gas is enough to keep running. Why the process is terminated automatically?

**Comment by MariusVanDerWijden** [comment]
I tried to repro, but couldn't. The infinite loop has been running on my machine for ~10 minutes now and it didn't crash. Maybe your program was terminated by the OS as it used to much memory or cpu? 
Maybe you also need to update from evm_1_9_11 to a newer version

**Comment by BattleBird** [comment]
> I tried to repro, but couldn't. The infinite loop has been running on my machine for ~10 minutes now and it didn't crash. Maybe your program was terminated by the OS as it used to much memory or cpu?
> Maybe you also need to update from evm_1_9_11 to a newer version
> 
> I ran the test down to
> 
> ```
> {"pc":81,"op":96,"gas":"0x252ee7102","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0xf8a8fd6d"],"returnStack":[],"depth":1,"refund":0,"opName":"PUSH1","error":""}
> {"pc":83,"op":96,"gas":"0x252ee70ff","gasCost":"0x3","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0xf8a8fd6d","0x56"],"returnStack":[],"depth":1,"refund":0,"opName":"PUSH1","error":""}
> {"pc":85,"op":86,"gas":"0x252ee70fc","gasCost":"0x8","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080","memSize":96,"stack":["0xf8a8fd6d","0x56","0x4f"],"returnStack":[],"depth":1,"refund":0,"opName":"JUMP","error":""}
> ```

Yeah, I think you're right. Thanks.
