### ISSUE TITLE
Converting values from ether to wei and vice-versa [feature request]

### ISSUE THREAD

**Issue by JackBekket** [ethereum/go-ethereum#21221]
I need a feature of converting values from ether to wei and vice-versa. I've tried to find some in go-eth modules, but didn't find anything.

**Comment by JackBekket** [comment]
I should also notice, that we (I don't actually understand why) have no **web3** implementation in golang. 
In any cases everyone said, that "you should use go ethereum for interacting with ethereum in go"

But go-ethereum with comparsion to web3 is not really comfortable to use, because it's missing some usefull tools such this simple thing -- converting ethereum values. (and also it's much more complex interaction with events than in web3)

I don't understand, why everyone else, who interact with ethereum in python, java-script, java and other languages have this convinient tools, but not golang developers. 

More than that - in other languages web3 implementations are pretty simple, and they have similar functions for any implementation in any language. 
But if I need to build something in go, I have to use go-ethereum, which have completly different (and more complex)syntax, and many usefull functions I need is just  don't exist.
So current situation is looked...so sad! 


So please, I ask you to make lives of go developers a bit better and gave us at least this particular feature

**Comment by MariusVanDerWijden** [comment]
Hey @JackBekket take a look at https://github.com/ethereum/go-ethereum/blob/master/params/denomination.go. I disagree that interaction with contracts is trickier in golang compared to web3. You can use abigen to quickly generate bindings for your smart contracts that basically do all event handlings and interactions for you. If you have the need for particular features that web3 has, that we do not provide, please open another issue. We're happy for all feedback we get!

**Comment by MariusVanDerWijden** [comment]
```go
func etherToWei(val *big.Int) *big.Int {
	return new(big.Int).Mul(val, big.NewInt(Ether))
}

func weiToEther(val *big.Int) *big.Int {
	return new(big.Int).Div(val, big.NewInt(Ether))
}
```

**Comment by kimxilxyong** [comment]
If you don't want to loose fractions of an ETH to truncating (I don't have that much money to loose 0.x ETHs)
Better use:
````go
func weiToEther(wei *big.Int) *big.Float {
	return new(big.Float).Quo(new(big.Float).SetInt(wei), big.NewFloat(params.Ether))
}
````
The etherToWei is also affected but i don't have time now and only need weiToEther

**Comment by kimxilxyong** [comment]
As it happens, I now needed the etherToWei(), too. Luckily i had the tab still open, so here it is for future researchers:

````go
func etherToWei(eth *big.Float) *big.Int {
	truncInt, _ := eth.Int(nil)
	truncInt = new(big.Int).Mul(truncInt, big.NewInt(params.Ether))
	fracStr := strings.Split(fmt.Sprintf("%.18f", eth), ".")[1]
	fracStr += strings.Repeat("0", 18 - len(fracStr))
	fracInt, _ :=  new(big.Int).SetString(fracStr, 10)
	wei := new(big.Int).Add(truncInt, fracInt)
	return wei;
}
````
helper function: Parsing a string "123.456" into a big.Float

````go
// ParseBigFloat parse string value to big.Float
func ParseBigFloat(value string) (*big.Float, error) {
	f := new(big.Float)
	f.SetPrec(236)  //  IEEE 754 octuple-precision binary floating-point format: binary256
	f.SetMode(big.ToNearestEven)
	_, err := fmt.Sscan(value, f)
	return f, err
}
````

Testing:
````go
	var balanceWei *big.Int
	var balanceETH *big.Float

	log.Println("--------------------------Start: 123456789012345678.987654321012345678")
	balanceETH = big.NewFloat(123456789012345678.987654321012345678)
	balanceWei = etherToWei(balanceETH);
	log.Println("Balance in ETH", weiToEther(balanceWei))
	log.Printf("Balance in ETH %18.18f", weiToEther(balanceWei))
	log.Println("Balance in WEI", balanceWei)
	log.Println("--------------------------End  : 123456789012345678.987654321012345678")

	log.Println("--------------------------Start: 123456789012345678.987654321012345678")
	balanceETH, _ = ParseBigFloat("123456789012345678.987654321012345678")
	balanceWei = etherToWei(balanceETH);
	log.Println("Balance in ETH", weiToEther(balanceWei))
	log.Printf("Balance in ETH %18.18f", weiToEther(balanceWei))
	log.Println("Balance in WEI", balanceWei)
	log.Println("--------------------------End  : 123456789012345678.987654321012345678")
````

**Comment by kimxilxyong** [comment]
Update regarding the precision of big.Float:

````go
import "math/big"

func weiToEther(wei *big.Int) *big.Float {
	f := new(big.Float)
	f.SetPrec(236)  //  IEEE 754 octuple-precision binary floating-point format: binary256
	f.SetMode(big.ToNearestEven)
	fWei := new(big.Float)
	fWei.SetPrec(236)  //  IEEE 754 octuple-precision binary floating-point format: binary256
	fWei.SetMode(big.ToNearestEven)
	return f.Quo(fWei.SetInt(wei), big.NewFloat(params.Ether))
}
````

**Comment by nuliknol** [comment]
@kimxilxyong since this is only for humans, we use strings

```
func Wei2Eth_str(amount *big.Int) string {

    compact_amount := big.NewInt(0)
    reminder := big.NewInt(0)
    divisor := big.NewInt(1e18)
    compact_amount.QuoRem(amount,divisor,reminder)
    return fmt.Sprintf("%v.%018s",compact_amount.String(),reminder.String())
}

```

you're going to print it to screen anyway
