### ISSUE TITLE
After a transaction is broadcasted???

### ISSUE THREAD

**Issue by Jetlum** [ethereum/go-ethereum#2122]
What info is shown after a transaction is broacasted?

**After it goes on the blockchain has an ID,but what else is shown any other info?**

**Comment by karalabe** [comment]
You can query the transaction based on the ID. Initially you'll see only relatively little information since it's not included in the chain, but afterwards you should get quite a detailed listing:

e.g.

```
> eth.getTransaction("0x9c9e4e4f17e1d0d033ad34753f9fc6ffa1f973280aeb7e2633a39ce546fc85ed")
{
  blockHash: "0x95431e3f12004326f74c35d564242092cefd037ba41e996a5be67e470882b683",
  blockNumber: 847431,
  from: "0x972ad000397a3c903299f1353d6d4b85ee4e4e2a",
  gas: 21000,
  gasPrice: 60000000000,
  hash: "0x9c9e4e4f17e1d0d033ad34753f9fc6ffa1f973280aeb7e2633a39ce546fc85ed",
  input: "0x",
  nonce: 530,
  to: "0x32be343b94f860124dc4fee278fdcbd38c102d88",
  transactionIndex: 0,
  value: 5866205550000000000
}
```

**Comment by Jetlum** [comment]
After it's included in the chain can we get a transaction dataset and a block dataset?

**Comment by karalabe** [comment]
Not sure what you're trying to do Could you elaborate a bit?

**Comment by Jetlum** [comment]
The example above is it the list after it's included in the chain?

Cause I want to know what info or data can we get after the transaction is broadcasted,the data of the tx and the data of the block

**Comment by karalabe** [comment]
My example was one already included in the chain.

**Comment by Jetlum** [comment]
Okay thanks for the answer
