### ISSUE TITLE
miner.etherbase flag doesn't SetEtherbase

### ISSUE THREAD

**Issue by wjmelements** [ethereum/go-ethereum#21234]
#### System information

Geth version: `1.9.13`
OS & Version: Linux

#### Expected behaviour
miner worker coinbase is set by miner.etherbase

#### Actual behaviour
miner worker coinbase is 0 until set by the private miner api

#### Steps to reproduce the behaviour
print w.coinbase in miner/worker.createPending

**Comment by rjl493456442** [comment]
I can't reproduce.

`geth --miner.etherbase <addr> --mine`, etherbase is set to <addr>
`geth --miner.etherbase <addr> console & miner.start()`, etherbase is set to <addr>

**Comment by wjmelements** [comment]
I don't do `--mine` or `miner.start()` in my use case so the worker.coinbase is never set.

**Comment by rjl493456442** [comment]
Why do you want to set the `etherbase` without mining enabled?

**Comment by karalabe** [comment]
Weáre not sur ewhy this is needed really. Would gladly discuss if you have some time. Until then I'll close it.
