### ISSUE TITLE
calling another contract function always revert(out of gas) ?

### ISSUE THREAD

**Issue by garyng2000** [ethereum/go-ethereum#21249]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.9.15`
OS & Version: Windows Server 2016
#### Expected behaviour
in one of the version between 1.9.1 and 1.9.15, there is some changes in how to calculate gas when involving other contract calls, below is a simple example:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

contract Foo {
    uint public _x;
    constructor(uint v)
        public
    {
        _x = v;
    }

    function getFoo() public pure returns(uint x) {
        return x;
    }

    function setFoo(uint x) public {
        _x = x;
    }
}

// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;
import { Foo } from "./Foo.sol";

contract Bar {
    address public foo;
    constructor(address _foo)
        public
    {
        foo = _foo;
    }

    function setFoo(address _foo) public {
        foo = _foo;
    }

    function setFooVal(uint x) public {
        Foo f = Foo(foo);
        f.setFoo(x);
    }

    function getFoo() public view returns(uint x) {
        Foo f = Foo(foo);
        uint y = f.getFoo();
        return y;
    }

    function getBar() public pure returns(uint x) {
        return 10;
    }
}
```

the getFoo() in contract Bar returns normally in 1.9.1(I haven't test other version) but return 'out of gas' or 'revert' in 1.9.15. And it doesn't matter if it is a eth_call or a send_transaction. calling Foo's getFoo() directly returns normal in 1.9.15.

**Comment by garyng2000** [comment]
just did some backward test. starting from 1.9.2, I am getting nothing(but not fail so I think it was already failing but not returning). in 1.9.15, it probably shows the error. though I don't quite understand what is the reason.

**Comment by garyng2000** [comment]
found out why. I am using a pre-Istanbul private network(POW, yeah I know it should be POA but this is a pretty old one). Starting 1.9.2, there are some Istanbul related change. Because I haven't 'hard fork' as mainnet, that appears to be the problem. After I simulate the hard-fork, things work again. There needs to be some documentation mentioning this. Which is even for private network that may not need the hard fork, it still has to be done.

**Comment by karalabe** [comment]
I'm not sure it's Geth at fault here. New Solidity compiler versions rely on new hard fork features. If you want to run EVM code on a network without all the forks enabled, you'll need to go back to a Solidity compiler version that does not rely on them.

**Comment by karalabe** [comment]
As for 1.9.15 erroring and previous ones not, it's just a feature we've added in the last 2 releases that revertals are ubpacked from the returned failure and exposed to the user. It was still failing before, just was not expanding it into a user readable failure.

**Comment by garyng2000** [comment]
I assume you mean the compiler within Geth(that handled the EVM code), not compiler as in solc ? As I was having trouble with already deployed contracts, pre-1.9.2

**Comment by karalabe** [comment]
There is no compiler in Geth. I was indeed referring to `solc`.

I tried your code via remix, it also fails there with the JS VM with the following error:

```
CALL
[call]from:0x48c10f4F2f0e00641d2B813E3361bf3679232308to:Bar.getFoo()data:0x243...dc8da
call to Bar.getFoo errored: VM error: revert.
revert	The transaction has been reverted to the initial state.
Note: The called function should be payable if you send value and the value you send should be less than your current balance.	Debug the transaction to get more information. 
```

**Comment by garyng2000** [comment]
may be we misunderstood each other than. I have some contracts that compiled with 0.5.10 and deployed to the network(then running 1.9.1) which is basically doing the code shown (contract Bar calling contract Foo, constant function or transaction). It worked fine back then. We recently upgraded to 1.9.15 and it no longer works(same contract, no new deployment). I traced it back to changes in 1.9.2 that starts to have Istanbul related changes(as it seems) which starts to behave differently.

IOW, same contract if I run it via 1.9.1 node, it works. 1.9.2+, it failed and in 1.9.15 it return the reason which is revert/out of gas. Then I 'hard fork' the chain to Istanbul(and the latest one as well) and it works again.

So this problem to me is solved, just that I don't expect that a newer version node require hard fork(rather than can handle hard fork) and why I said better documentation is needed. This would never be a problem on mainnet(and those public test net) but for private network usage, it may not be a known requirement.

**Comment by karalabe** [comment]
Hmm, that should not happen. All past contracts should keep on working - unless at worst you fork and that breaks it. Without an explicit fork it should never fail with a newer version of Geth. Something might be borked then.

**Comment by karalabe** [comment]
I've build and deployed your repro contracts on Goerli, but it still reverts on getfoo for me:

https://goerli.etherscan.io/address/0x169c0b21c67f8182c18b7bbe4eeb64c4324434d6

```
> eth.call({to: "0x169c0B21C67f8182c18B7bbe4eEB64C4324434D6", data: "0x243dc8da"})
WARN [06-25|09:11:21.559] Served eth_call                          reqid=15 t=1.329572ms err="execution reverted"
Error: execution reverted
	at web3.js:6347:37(47)
	at web3.js:5081:62(37)
	at <eval>:1:9(8)

```

**Comment by garyng2000** [comment]
that was exactly my initial reaction, how come upgraded node broken my old contracts. I only changed it to 0.6 thinking may be newer node requires new compiler. As for Goerli, I have no idea. You can see that the contracts are really simple, only thing I noticed is it calls out to another contract and that it works in 1.9.1 and failed in 1.9.2+(until I put in Instanbul block#)

**Comment by karalabe** [comment]
I'm just not sure why it would start working for you. It definitely does not for me, even on Istanbul on Görli. Are you also running the repro code from your original issue report?

**Comment by garyng2000** [comment]
yes.

**Comment by garyng2000** [comment]
though forget about my network, I can't see anything unusual in my foo/bar example and no idea why it doesn't work on Gorli. But on my network, everything is back to normal.

**Comment by karalabe** [comment]
Tried on a local private network with latest Geth and Istanbul disabled, still works:

```
[...]
INFO [06-25|09:42:54.366] Initialised chain configuration          config="{ChainID: 1337 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 1000, Muir Glacier: <nil>, YOLO v1: <nil>, Engine: clique}"

> eth.sendTransaction({from: eth.accounts[0], data: "0x608060405234801561001057600080fd5b506040516101073803806101078339818101604052602081101561003357600080fd5b505160005560c1806100466000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c8063243dc8da14604157806329809703146059578063dc80035d14605f575b600080fd5b6047607b565b60408051918252519081900360200190f35b60476080565b607960048036036020811015607357600080fd5b50356086565b005b600090565b60005481565b60005556fea26469706673582212209582391e1a453f3c5432c581f472166d83a9d9f8152eb8be490d6c9c9750c43b64736f6c634300060a0033000000000000000000000000000000000000000000000000000000000000013a"})
INFO [06-25|09:43:26.588] Submitted contract creation              fullhash=0x57287fe7e724458bc7e16dc516ff926d4c504e36ed52215352d117743d315e2f contract=0x585699c5861703fb709Bcb4415E4c70f95A1eE3F

> eth.sendTransaction({from: eth.accounts[0], data: "0x608060405234801561001057600080fd5b5060405161029d38038061029d8339818101604052602081101561003357600080fd5b5051600080546001600160a01b039092166001600160a01b0319909216919091179055610238806100656000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c806321352b621461005c578063243dc8da1461008457806334553e3e1461009e57806367a23d13146100bb578063c2985578146100c3575b600080fd5b6100826004803603602081101561007257600080fd5b50356001600160a01b03166100e7565b005b61008c610109565b60408051918252519081900360200190f35b610082600480360360208110156100b457600080fd5b5035610186565b61008c6101ee565b6100cb6101f3565b604080516001600160a01b039092168252519081900360200190f35b600080546001600160a01b0319166001600160a01b0392909216919091179055565b600080546040805163121ee46d60e11b815290516001600160a01b03909216918391839163243dc8da91600480820192602092909190829003018186803b15801561015357600080fd5b505afa158015610167573d6000803e3d6000fd5b505050506040513d602081101561017d57600080fd5b50519250505090565b600080546040805163dc80035d60e01b81526004810185905290516001600160a01b0390921692839263dc80035d92602480820193929182900301818387803b1580156101d257600080fd5b505af11580156101e6573d6000803e3d6000fd5b505050505050565b600a90565b6000546001600160a01b03168156fea264697066735822122006ea668ace37d5268d9c81264d5ae9b1f5b0abcf1d1c4f644cd7363b87c1892264736f6c634300060a0033000000000000000000000000585699c5861703fb709Bcb4415E4c70f95A1eE3F"})
INFO [06-25|09:44:46.796] Submitted contract creation              fullhash=0x40398becfe89f65473d2022b8056bf7920cbcbdb5f58d7d34bf6ca127378baaa contract=0x06B61D59866D71b29E95Bd91AEe888C0D31e1744

> eth.call({to: "0x06B61D59866D71b29E95Bd91AEe888C0D31e1744", data: "0x243dc8da"})
"0x0000000000000000000000000000000000000000000000000000000000000000
```

**Comment by karalabe** [comment]
Rebuilt everything with Solidity 0.5.10 and deployed again with Istanbul disabled:

```
> eth.sendTransaction({from: eth.accounts[0], data: "0x608060405234801561001057600080fd5b506040516101073803806101078339818101604052602081101561003357600080fd5b505160005560c1806100466000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c8063243dc8da14604157806329809703146059578063dc80035d14605f575b600080fd5b6047607b565b60408051918252519081900360200190f35b60476080565b607960048036036020811015607357600080fd5b50356086565b005b600090565b60005481565b60005556fea26469706673582212209582391e1a453f3c5432c581f472166d83a9d9f8152eb8be490d6c9c9750c43b64736f6c634300060a0033000000000000000000000000000000000000000000000000000000000000013a"})
INFO [06-25|09:48:49.197] Submitted contract creation              fullhash=0xe3aadfe7cb4e46a837f8e9510123878ea78e735029e9446a3134ac88a72786c6 contract=0x8528533C1ED249275b58fF88C419b27d796C333c

> eth.sendTransaction({from: eth.accounts[0], data: "0x608060405234801561001057600080fd5b5060405161029d38038061029d8339818101604052602081101561003357600080fd5b5051600080546001600160a01b039092166001600160a01b0319909216919091179055610238806100656000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c806321352b621461005c578063243dc8da1461008457806334553e3e1461009e57806367a23d13146100bb578063c2985578146100c3575b600080fd5b6100826004803603602081101561007257600080fd5b50356001600160a01b03166100e7565b005b61008c610109565b60408051918252519081900360200190f35b610082600480360360208110156100b457600080fd5b5035610186565b61008c6101ee565b6100cb6101f3565b604080516001600160a01b039092168252519081900360200190f35b600080546001600160a01b0319166001600160a01b0392909216919091179055565b600080546040805163121ee46d60e11b815290516001600160a01b03909216918391839163243dc8da91600480820192602092909190829003018186803b15801561015357600080fd5b505afa158015610167573d6000803e3d6000fd5b505050506040513d602081101561017d57600080fd5b50519250505090565b600080546040805163dc80035d60e01b81526004810185905290516001600160a01b0390921692839263dc80035d92602480820193929182900301818387803b1580156101d257600080fd5b505af11580156101e6573d6000803e3d6000fd5b505050505050565b600a90565b6000546001600160a01b03168156fea264697066735822122006ea668ace37d5268d9c81264d5ae9b1f5b0abcf1d1c4f644cd7363b87c1892264736f6c634300060a00330000000000000000000000008528533C1ED249275b58fF88C419b27d796C333c"})
INFO [06-25|09:49:32.560] Submitted contract creation              fullhash=0x01e1db77b8d97ae8790978e4bec483b20e10766908b90e60fd3d9ca463ebf9a8 contract=0x941811044E3DAF69D9DE17e57edb916094576d68

> eth.call({to: "0x941811044E3DAF69D9DE17e57edb916094576d68", data: "0x243dc8da"})
"0x0000000000000000000000000000000000000000000000000000000000000000"
```

Everything seems to work.

**Comment by karalabe** [comment]
At this point I'm kind of concluding that there's something different in the code that you are running, or the way you are setting it up. I've checked on Görli (Istanbul) with Solidity 0.5.10 and 0.6.10 and it works ok. I've also checked on a local net with Istanbul disabled with Solidity 0.5.10 and 0.6.10 and it works ok.
