### ISSUE TITLE
When will the Berlin fork happen？

### ISSUE THREAD

**Issue by GongSuiLi** [ethereum/go-ethereum#21258]
I noticed here https://github.com/ethereum/go-ethereum/releases/tag/v1.9.15 that there is an upcoming Berlin fork, I want to know when it will happen?

**Comment by MariusVanDerWijden** [comment]
There is no concrete timeline for the fork yet. In v1.9.15 we released features that might make it into the Berlin fork, but that is not clear yet. Once the date is set, it will be announced on the usual channels e.g. https://blog.ethereum.org/
