### ISSUE TITLE
Missing TOML properties for (some) boolean options in dumpconfig

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#21262]
#### System information

```
Geth
Version: 1.9.15-stable
Git Commit: 0f77f34bb67b640bd8af22b215f3d279a1e21170
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.2
Operating System: linux
```

#### Expected behaviour
running `geth --ipcdisable --shh dumpconfig` should generate a config file that both disables ipc and enables shh

#### Actual behaviour
When doing `geth dumpconfig` with some flags, such as `--shh` or `--ipcdisable`, the output toml file doesn't actually enable shh or disable ipc...

I'm not sure if there are other options that are not being translated to the config file, but I did run into both `shh` and `ipcdisable` today.

#### Steps to reproduce the behaviour
```
geth --ipcdisable dumpconfig > disabled.cfg
geth dumpconfig > enabled.cfg

diff enabled.cfg disabled.cfg
60d59
< IPCPath = "geth.ipc"
```

However...when I try to actually run the disabled.cfg config file:
`Fatal: Error starting protocol stack: listen unix /mnt/e/geth/data/geth.ipc: bind: operation not supported`

I assume this is because it's assuming the default here, there isn't actually a property in the config that is disabling it.

The workaround is obviously to specify the options on the cli command, but it should be set in the toml file...

**Comment by MysticRyuujin** [comment]
FWIW: I don't believe this is windows specific at all, I was just clarifying why I got the error that I did and why this is important.

The `dumpconfig` on linux would do the same thing and behave the same way

**Comment by karalabe** [comment]
Can confirm that these do not get dumped out, possibly because the IPC disabling is transformed from some boolean into another option. Either way, I think the use case is valid and should work.

**Comment by rjl493456442** [comment]
@MysticRyuujin Please see #21296 

Regarding the SHH, we don't have the Enable SHH field in the config, so it may involve more changes. I don't know whether we need the fix it. cc @gballet
