### ISSUE TITLE
Request: Split chain datadir from keystore datadir

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/go-ethereum#2127]
A user might want to use multiple apps which connect to the ethereum network. However, they might wish to keep their keystores separate. There is security and privacy reason for this (not letting other apps access keys they don't want accessed).

Ideally, a user should only have to sync the blockchain once regardless of how many apps are installed on their computer. This is only possible (AFAIK) by splitting the chain datadir from the keystore datadir

**Comment by aakilfernandes** [comment]
Another possible solution would be to provide an interface for geth to load keys at runtime, that way apps could do their own private key management

**Comment by fjl** [comment]
Apps can do their own key management today, by signing transactions outside of geth and sending them using `eth_sendRawTransaction`.

**Comment by aakilfernandes** [comment]
True. However, web3 was built the assumption that rpc clients would handle the signing of transactions. (double checking with the web3 team to make sure, but this is my understanding).

**Comment by aakilfernandes** [comment]
It turns out https://github.com/ConsenSys/eth-lightwallet provides everything needed to sign in the browser. Closing this issue for now
