### ISSUE TITLE
Out of the blue chaindata takes up ~700GB

### ISSUE THREAD

**Issue by wschwab** [ethereum/go-ethereum#21281]
#### System information

Geth version: `1.9.11`
OS & Version: Linux Debian 10 latest

#### Expected behaviour
It would seem the expected size of `chaindata` on a full (not archive) node is currently ~350 GB. [source](https://bitinfocharts.com/ethereum/) About a week ago I started getting notifications that I was running out of disk space, and discovered my `chaindata` was ~700GB, and `ancient` another ~150GB.

I moved `ancient` to an auxiliary drive, but the node 'died' shortly thereafter, citing `Fatal: Error starting protocol stack: gap in the chain between ancients and leveldb`.

#### Steps to reproduce the behaviour
I don't know how to reproduce this. I figured it would be wise to bring it to your attention in case this is not a one-time event. The only thing I can think of is that I was not explicitly using the `--syncmode fast` flag, and was relying on fast sync being the default behavior, as I believe is specified in the docs.

Again, I don't have a specific issue to solve - I deleted `chaindata` and started a new sync off of the `ancient`. Just in case this part of a larger bug, though, I figured I should bring it to your attention,

Thanks for all the great work! We ❤️ Geth!

**Comment by holiman** [comment]
A fast-sync starts off having the 'bare minimum' state -- nothing more than required to operate at the 'pivot point' where you synced to. After fast-sync is done, blocks are imported one by one, and when blocks are imported one by one, we do an in-memory pruning of state. We try to maintain minimum state, but the effectiveness of the in-memory pruner depends on how much memory it has, and it can never be perfect. 

So the longer you run it, the more extraneous data is collected. If you've ran it for a long time, it can easily be double the size, compared to if you do a fresh fast-sync.

**Comment by holiman** [comment]
> Thanks for all the great work! We :heart: Geth!

And thanks a lot for the support!
