### ISSUE TITLE
Got error when using Geth to connect and operate transaction node in Azure Blockchain Service 

### ISSUE THREAD

**Issue by CassieJie** [ethereum/go-ethereum#21288]
Hi there,

I got error as follows, it's using miner to mine after successfully connect a transaction node in Azure Blockchain Service.

```
geth attach https://resourcename.blockchain.azure.com:port/xxx
Welcome to the Geth JavaScript console!

instance: Geth/v1.9.7-stable-9339be03(quorum-v2.6.0)/linux-amd64/go1.13.12
coinbase: 0x46dfb271b0dd7c097acad952943dffaa5016c571
at block: 140369 (Thu Jul 02 2020 16:07:52 GMT+0800 (CST))
 datadir: /working-dir/dd
 modules: admin:1.0 debug:1.0 eth:1.0 istanbul:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

>miner.start()
ReferenceError: miner is not defined
        at <eval>:1:1(0)
```

#### System information

Geth version: `v1.9.7`
OS & Version: Windows

**Comment by rjl493456442** [comment]
Apprently the Azure Blockchain Service is using the quorum(the fork of the geth). I'm not sure what kind of changes the quorum has made. Maybe they just remove the miner namespace.

**Comment by jpmsam** [comment]
@rjl493456442 is correct, Azure blockchain service uses Quorum and it doesn't support mining. For any future ABS Quorum issues, please report them on our [github repo](https://github.com/jpmorganchase/quorum/issues).

**Comment by CassieJie** [comment]
got it, thanks!
