### ISSUE TITLE
Unable to install crypto package

### ISSUE THREAD

**Issue by sammy007** [ethereum/go-ethereum#2129]
go get github.com/ethereum/ethash
# github.com/ethereum/go-ethereum/crypto
C:\...\ethereum\go-ethereum\crypto\crypto.go:92: undefined: secp256k1.RecoverPubkey
C:\..\ethereum\go-ethereum\crypto\crypto.go:203: undefined: secp256k1.Sign

**Comment by Gustav-Simonsson** [comment]
Looks like it pulls in `crypto` but not it's dependency package `secp256k1` https://github.com/ethereum/go-ethereum/tree/master/crypto/secp256k1

Meanwhile one can work around this not using `go get` directly on `ethash` but rather `go-ethereum` and then using `godep restore` to set ethash in the GOPATH to the version `go-ethereum` is using.

If you want to develop something in package `ethash` or use it in some way feel free to ping me or @LefterisJP if you have any questions.
