### ISSUE TITLE
geth not exit gradually when a service fails to start

### ISSUE THREAD

**Issue by trung** [ethereum/go-ethereum#21292]
### System information

Geth version:
```
Geth
Version: 1.9.16-unstable
Git Commit: 61270e5e1c7986427fb1a80789344daafd4bda3f
Git Commit Date: 20200703
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.4
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```
OS & Version: Docker (ethereum/client-go:latest)

### Expected behaviour

`geth` process must exit gradually with fatal message

### Actual behaviour

`geth` process keeps running and does not exit

#### Steps to reproduce the behaviour

* Run the first node: `docker run --rm -it -p 30303:30303 ethereum/client-go:latest --verbosity 5 --nodiscover`
* From the logs, capture its enode and replace the IP with the container IP (e.g.: 172.17.0.2)
* From another terminal:
   * `mkdir -p /tmp/data`
   * Create `static-nodes.json` in `/tmp/data` and add the above enode url
   * Run the second node: `docker run --rm -it -v /tmp/data:/tmp/data ethereum/client-go:latest --verbosity 5 --nodiscover -datadir /tmp/data --graphql --graphql.addr 1.2.3.4`

The second node must exit with fatal message due to invalid `--graphql.addr` however with **some attempts** the second node would just not exit gradually.

### Observation

`eth` service is the first service being registered
https://github.com/ethereum/go-ethereum/blob/61270e5e1c7986427fb1a80789344daafd4bda3f/cmd/geth/config.go#L147-L150
and the `graphql` service is the last. However, this order is kept only when calling their constructors. 
When starting services, the order is random due to looping through the map structure
https://github.com/ethereum/go-ethereum/blob/61270e5e1c7986427fb1a80789344daafd4bda3f/node/node.go#L229-L241

There would be an occasion in which `graphql` service starts first and fails. The nutshell implication of this is that if there's a peer connected before that happens, peer handler will be blocked causing `geth` not able to exit. And the only way to get out is via `eth` service `Stop()` which is impossible as `eth` service is not yet started.

Although this timing issue is not really a big problem when connecting to MainNet or TestNet due to the latency of peer connectivity it would likely happen in a private network.

A fix would be to make sure the order of service startups is the same as service constructors. Happy to raise a PR once this issue is confirmed.

**Comment by renaynay** [comment]
#21105 will likely solve this issue.

**Comment by trung** [comment]
Thanks @renaynay. I believe the refactoring would do the job well. 

Do you have estimation on when it will be available?

**Comment by renaynay** [comment]
#21105 has been merged @trung 

Please let me know if the issue persists.

**Comment by trung** [comment]
Thanks for the merge. 

Unfortunately i am not able to reproduce as I couldn't find a service to make it fail when `Start()` without modifying the code. 
From the dry run I think the order is preserved so it would definitely solve the issue.

I'm closing this issue for now.
