### ISSUE TITLE
Sync checkpoint failed

### ISSUE THREAD

**Issue by flgh** [ethereum/go-ethereum#21294]
#### System information

Geth version: 1.9.15-stable
OS & Version: Linux

Both client and server are in each other's static and trusted peer.
#### Expected behaviour

Light client sync succesfully with remote light server peer (--nodiscover --netrestrict 192.168.1.2/32 --maxpeers 1) 
#### Actual behaviour
Works flawlessly for a few months then:
WARN [07-05|15:58:25.827] Synchronisation failed, retrying         err="peer is unknown or unhealthy"

<pre>
TRACE[07-05|19:45:29.798] Starting p2p dial                        id=dfc7027894e168c3 ip=192.168.1.2  flag=staticdial
DEBUG[07-05|19:45:29.800] Adding p2p peer                          peercount=1 id=dfc7027894e168c3 conn=trusted-staticdial addr=192.168.1.2:30303 name=Geth/v1.9.15-stable-...
TRACE[07-05|19:45:29.800] Starting protocol les/3                  id=dfc7027894e168c3 conn=trusted-staticdial
DEBUG[07-05|19:45:29.800] Light Ethereum peer connected            id=dfc7027894e168c3 conn=trusted-staticdial name=Geth/v1.9.15-stable-0f77f34b/linux-amd64/go1.14.4
DEBUG[07-05|19:45:29.800] Node entered                             set=connected id=dfc7027894e168c3 count=1
TRACE[07-05|19:45:29.801] Registering sync peer                    peer=dfc7027894e168c3292c50b5461ef8ec635a5e04874b1e13b5ad7596a98f3bda
DEBUG[07-05|19:45:29.801] Received new announcement                id=dfc7027894e168c3 conn=trusted-staticdial number=10400821 hash="792667…f8e5b3" reorg=0
DEBUG[07-05|19:45:29.801] Synchronisation started                  id=dfc7027894e168c3 conn=trusted-staticdial
DEBUG[07-05|19:45:29.801] Disable checkpoint syncing               reason="checkpoint is hardcoded"
DEBUG[07-05|19:45:29.801] Checkpoint syncing start                 peer=dfc7027894e168c3292c50b5461ef8ec635a5e04874b1e13b5ad7596a98f3bda checkpoint=310
DEBUG[07-05|19:45:29.801] Sync checkpoint failed
DEBUG[07-05|19:45:29.801] Node left                                set=connected id=dfc7027894e168c3 count=0
TRACE[07-05|19:45:29.801] Unregistering sync peer                  peer=dfc7027894e168c3292c50b5461ef8ec635a5e04874b1e13b5ad7596a98f3bda
DEBUG[07-05|19:45:29.801] Done synchronising with peer             id=dfc7027894e168c3 conn=trusted-staticdial
DEBUG[07-05|19:45:29.801] Light Ethereum message handling failed   id=dfc7027894e168c3 conn=trusted-staticdial err=EOF
DEBUG[07-05|19:45:29.801] Unknown peer to check sync headers       id=dfc7027894e168c3 conn=trusted-staticdial
DEBUG[07-05|19:45:29.801] Removing p2p peer                        peercount=0 id=dfc7027894e168c3 duration=1.060ms     req=false err="disconnect requested"
</pre>
Tried removing ~/.ethereum/geth content on the light client, doesn't fix the issue.
Then after a few hours, the light client syncs again correctly.

**Comment by rjl493456442** [comment]
The mechanism of light sync is light client will try to start with a checkpoint and then sync the remaining headers.
In this case(from your log), light client is failed to fetch the checkpoint header, so the procedure is aborted.

There are lots of possibilities that can lead to this situation:
- the peer doesn't delivery the requested header in time
- the peer doesn't have the requested header(out of sync, in the fork chain)
- the peer deliberately don't send the requested header

So it's not incorrect behavior.

> Then after a few hours

Because there are limited LES server for serving clients, so it takes that long time to find the next suitable server.

**Comment by sblackstone** [comment]
I like dfc7027894e168c3292c50b5461ef8ec635a5e04874b1e13b5ad7596a98f3bda

:-)
