### ISSUE TITLE
I have a transaction information problem and need help. I hope someone can help me

### ISSUE THREAD

**Issue by arCzWw** [ethereum/go-ethereum#21308]
Is there any way that I can efficiently find the transaction information of a certain erc20 token in a certain period of time on the main network

use 
golang  1.13.7
go-ethereum v1.9.15

**Comment by MariusVanDerWijden** [comment]
Do you want to find it in a program or just in general? 
If you just want to find a specific transaction, try etherscan e.g. https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7
If you are looking for a way to interact with the blockchain using golang and find a specific transaction you can take a look at this: https://medium.com/@m.vanderwijden1/web3-go-part-1-31c68c68e20e
You could also try to use the javascript console of geth, but that would hardly be efficient
