### ISSUE TITLE
(Whisper) 'RequestHistoricMessages' function is not exposed to call

### ISSUE THREAD

**Issue by LijuJoseJJ** [ethereum/go-ethereum#21314]
#### Expected behaviour
Just like 'targetPeer' key available to parameter of `shh.post({})` to make P2PMessage
Similarly, some key should be made available to make post as request to mail server for historic messages, 
or
a new function to 'web3.shh' (probably a getter) to get historic messages

#### Actual behaviour
Currently `RequestHistoricMessages` is only called in wnode client setup.
why its not kept as part web3 apis ?

#### code snippet 

```
// send to specific node (skip PoW check)
	if len(req.TargetPeer) > 0 {
		n, err := enode.Parse(enode.ValidSchemes, req.TargetPeer)
		if err != nil {
			return nil, fmt.Errorf("failed to parse target peer: %s", err)
		}
		err = api.w.SendP2PMessage(n.ID().Bytes(), env)
		if err == nil {
			hash := env.Hash()
			result = hash[:]
		}
		return result, err
	}
```

can something be possible for `RequestHistoricMessages`
```
// send to specific node (skip PoW check)
	if len(req.TargetPeer) > 0 {
		n, err := enode.Parse(enode.ValidSchemes, req.TargetPeer)
		if err != nil {
			return nil, fmt.Errorf("failed to parse target peer: %s", err)
		}
		err = api.w.RequestHistoricMessages(n.ID().Bytes(), env)
		if err == nil {
			hash := env.Hash()
			result = hash[:]
		}
		return result, err
	}
```

**Comment by gballet** [comment]
Whisper support is being removed from `geth` and being moved to [its own repository](github.com/ethereum/whisper). No action will therefore be taken and I'm closing the PR.

`RequestHistoricMessages` is a convenience method used for retrieving messages from the mailserver. The mailserver code is only provided as an example and is not considered production code.

In the case you have your own, production-grade implementation of the mail server and want to recover the data, I suggest that you `import "github.com/ethereum/whisper"` in your code and expose your own RPC call from there.
