### ISSUE TITLE
Is there any potential nil pointer in stateobject deepcopy

### ISSUE THREAD

**Issue by ucwong** [ethereum/go-ethereum#21313]
https://github.com/ethereum/go-ethereum/blob/master/core/state/state_object.go#L418
Is there any potential nil pointer panic here? When multi threads invoke here? 
```
func (s *stateObject) deepCopy(db *StateDB) *stateObject {
          stateObject := newObject(db, s.address, s.data)
```
may s be nil here ? when commit mining work call statedb.copy

**Comment by holiman** [comment]
statedb/stateobjects are not concurrency-safe, that particular method should be only accessed by one thread at a time
