### ISSUE TITLE
SSD Disk Speed for 2 nodes

### ISSUE THREAD

**Issue by pool2mine** [ethereum/go-ethereum#21322]
Hi, sorry this may be a dumb question but i need to be sure before i mess things up.

I have a bare metal server with virtualization software. I made a VM and it's running my geth node. I wanted to make another VM so i can sync a backup node since i have plenty of space, memory and CPU, but i know the critical thing for running the node is the disk writing speed, I have 6GB/s SSD on RAID 10, now the dumb question... if I run the second node even that it's on a separate VM, it's in the same physical server... will the writing speed maintain 6GB/s for both nodes or would I be reducing like 3GB/s for each node?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
