### ISSUE TITLE
LES checkpoint question

### ISSUE THREAD

**Issue by sidhujag** [ethereum/go-ethereum#21337]
Hello,

In Syscoin we run a light geth mode to verify Eth SPV proofs by pulling in reciept and tx roots directly into Syscoin (fork of Bitcoin).

We ensure that roots are available (~3 weeks worth or 150000 blocks minimum) before validating transactions with SPV proofs. Does LES client for Geth ensure that checkpoint are always atleast a certain age? Is there a policy you have to ensure checkpoints don't get put in that are newer? This would help I think.

Thanks!

**Comment by rjl493456442** [comment]
> Does LES client for Geth ensure that checkpoint are always atleast a certain age?

I guess your question is: can we use the latest checkpoint for verifying the old data(receipts, txs, etc).
Yes, In LES the checkpoint is cumulative, the latest checkpoint can cover all past data.

**Comment by sidhujag** [comment]
> > Does LES client for Geth ensure that checkpoint are always atleast a certain age?
> 
> I guess your question is: can we use the latest checkpoint for verifying the old data(receipts, txs, etc).
> Yes, In LES the checkpoint is cumulative, the latest checkpoint can cover all past data.

Basically we run geth nodes to push reciept/tx roots to syscoin so it can validate SPV proofs from eth to sys. So if you run Geth from scratch it will sync up from latest checkpoint right that is the roots that get sent to syscoin. We need atleast 3 weeks of those roots to exist as that is the cutoff for an eth spv proof to become invalid on syscoin (where they can cancel on eth contract to get money back if they couldn't post it on syscoin), so there is risk of double spend if the geth client is not providing adequate data which is why I asked if we can ensure after every upgrade that checkpoints are atleast 3 weeks or more old.

**Comment by rjl493456442** [comment]
In Geth, if there are 32768 blocks generated, then a new checkpoint *can* be created. But the checkpoint updating is manual. So usually we only update the checkpoint when we make a new release(~2 weeks).

But as I said, the latest checkpoint can cover all historical data. If I understand correctly, You can even use the latest checkpoint but only use it for verifying the `receipt/tx` which is old enough(more than 3 weeks). 
It doesn't matter how old the checkpoint is, it matters how old the data is(right?).

But if you really want to "old enough" checkpoint, you can check the `checkpoint oracle` which we use to publish the checkpoint. All historical votes will be put in the event. https://github.com/ethereum/go-ethereum/blob/master/contracts/checkpointoracle/contract/oracle.sol#L111

**Comment by sidhujag** [comment]
Our algorithm is as follows:

1) notice an ethereum burn transaction, to try to mint on Syscoin. Get the stored ethereum header data via block height encoded in the transaction payload
2) SPV proof validation of tx root and receipt root
3) validate data inside of ethereum tx payload

The ethereum header must be atleast 1 hour old and under 3 weeks old for it to be valid.

How can the checkpoint help here? keep in mind every Syscoin node does this check independently for longest chain validation. A relayer pushes ethereum header data using geth light node to syscoin node via RPC locally.

**Comment by rjl493456442** [comment]
The light client can verify any header covered by the checkpoint. Like the `GetHeaderByNumber` API used by light client, https://github.com/ethereum/go-ethereum/blob/master/light/odr_util.go#L36, maybe you can always fetch the corresponding header by number and compare the hash?

**Comment by sidhujag** [comment]
> The light client can verify any header covered by the checkpoint. Like the `GetHeaderByNumber` API used by light client, https://github.com/ethereum/go-ethereum/blob/master/light/odr_util.go#L36, maybe you can always fetch the corresponding header by number and compare the hash?

We don't want to query geth at runtime of syscoin consensus, the relayer pushes data and indexes into syscoin from geth node as it syncs up. At runtime we fetch header data by number and verify SPV proof which essentially validates the receipt and tx roots and payload commits to those roots. So maybe you are saying you index the checkpoints instead and use some kind of proof to validate that roots commit to the checkpoint if its older than say 3 weeks?

**Comment by rjl493456442** [comment]
> So maybe you are saying you index the checkpoints instead and use some kind of proof to validate that roots commit to the checkpoint if its older than say 3 weeks?

NO, I mean no matter the checkpoint is fresh new or not(even the checkpoint is new, the possibility the checkpoint is invalid is very low seems we have 2048 block confirms), you can use it for proving anyway(prove headers, receipts, txs).

I don't understand why you have this kind of restriction that the checkpoint should be older than 3 weeks. If you really need this restriction, you can use the latest checkpoint but only use it for verifying the data(headers, receipts, txs) older than 3 weeks. It has the same security guarantee.

**Comment by sidhujag** [comment]
I am not using checkpoint directly I was just saying that once checkpoint was newer if someone was syncing from scratch they would end up only syncing less than 3 weeks of data and we wanted mroe than 3 weeks of headers in sys chain to allow for eventuality that an eth to sys transactions times out and gets cancelled (extracting erc20 out of our smart contract back to user).. it times out after 3 weeks so its assumed user can get money back. If you can use latest checkpoint to prove an older tx receipt proof and tx root proof somehow then we dont need cancel feature and can just use latest checkpoint for every single proof and do not even need to store eth headers in sys just the latest checkpoints. 

How do you prove that a transaction was valid at some block X, where checkpoint is on block Y such that Y > X. The transaction commits to tx merkle root and receipt data commits to receipt merkle root in block X, how to prove it against checkpoint of block Y with no knowledge of block X, not even the tx roots, reciept root?

**Comment by sidhujag** [comment]
@rjl49345644 I noticed on rinkeby a checkpoint that is less than 2 weeks old. This is really concerning to us as 2 weeks old checkpoint is not really secure. I ask again, what are your security practices around updating these checkpoints? We want to use the checkpoints so we don't have to download from genesis but 2 weeks is too new I feel. I suggested to wait atleast 3 weeks before the block is checkpointed as that is an assumption we are using in our code, as it will give us enough data availability to do SPV proofs for Ethereum safely, under that and it becomes risky.

**Comment by rjl493456442** [comment]
@sidhujag Yes, it should be feasible. You can checkout the LES spec here https://github.com/ethereum/devp2p/blob/master/caps/les.md. 

Essentially the CHT root is the root of a merkle tree. The leaves of the merkle tree
is the canonical block hash. So a simple merkle proof should solve your problem.

**Comment by sidhujag** [comment]
@rjl493456442 thanks, ok so let me see if I can clarify

So basically right now we store eth block number, tx root and receipt root in our db, and later checking against them when we get a bridge request from eth to sys we check:

1) We get the tx root/receipt root info via block number fetch from the db
2) We check the embedded transaction has a receipt root == to stored receipt root
3) same for tx root
4) validate the receipt and tx roots via SPV proof data passed along by the user in the syscoin transaction payload
5) Some other specific validations on the values of events logs etc

so I can instead store the CHT's of the last few (pull in latest and also pull in previous one to cover the 2-3 weeks at all times). The reason we want to atleast cover for 3 weeks is that if a proof isn't posted on Syscoin and subseqeuently coins minted on Syscoin from Ethereum they can "cancel" to get coins back as ERC20 with a bonded fraud proof game, using availability of the tx on syscoin as the fraud proof. So if we store the CHT then we would simply only need to proof the transactions ID links to the CHT specified by the user. For this we need:

1) Likely the full block header so we can reconstruct the block hash
2) User specified merkle path of block hash committing to the CHT specified in the payload
3) Instead of 1 above we can simply get the CHT from the stored db of CHT's and then do SPV proof of validity of the block header with the transaction in question must be canonical chain.
4) We would need a call to be able to receive CHT's right now we simply do web3 calls running on a local relayer which receives block information and then propogate the tx roots/receipt roots and block numbers to syscoin via local RPC call. In the same way we would only recieve CHT's or pull CHT's from geth upon startup, but also at runtime as new CHT's are created.

I think the new way of validating only applies to transactions that are in blocks not commited to by a CHT right, so I would need to still do normal validation for anything not in a CHT and then for older ones use CHT to validate the block is part of canonical chain?

Is this correct?

**Comment by rjl493456442** [comment]
@sidhujag I think it would be more efficient to chat directly? Because I guess you are using the light client heavily, so would you mind joining the geth dicord so that we can understand your problem better?

The link https://discord.gg/cb5s8b2t

**Comment by zsfelfoldi** [comment]
I think there is no security advantage in using an older CHT. CHTs are not trustless, they are announced by the dev team and they are basically just a performance optimization. They do not become safer with time. If you don't want to trust them but want to download and verify all headers, there is no option for that at the moment but it is easy to change in the code:
https://github.com/ethereum/go-ethereum/blob/master/les/sync.go#L126
You have to change the default mode to `lightSync` instead of `checkpointSync`.

**Comment by sidhujag** [comment]
> I think there is no security advantage in using an older CHT. CHTs are not trustless, they are announced by the dev team and they are basically just a performance optimization. They do not become safer with time. If you don't want to trust them but want to download and verify all headers, there is no option for that at the moment but it is easy to change in the code:
> https://github.com/ethereum/go-ethereum/blob/master/les/sync.go#L126
> You have to change the default mode to `lightSync` instead of `checkpointSync`.

the problem with all headers is that it requires alot of storage costs running syscoin storing all headers and time of sync as well.. I set it up so that it would require only a few week or month and then verification will enforce that anything older than a few weeks is not allowed to move over the bridge, so you have say 2 weeks to execute or cancel it on the eth contract side, from 0 is fine but requires more data storage and sync time/bandwidth, whereas we made a tradeoff of 2 weeks to execute and live state validation only so that we only ever need to download say the last 3 or 4 weeks to be safe

**Comment by sidhujag** [comment]
Who do I talk to on there I left a message looking for you guys but received no response.

**Comment by holiman** [comment]
CHT's are gone
