### ISSUE TITLE
geth always stop sync

### ISSUE THREAD

**Issue by TamirTian** [ethereum/go-ethereum#21335]
[stacktrace.txt](https://github.com/ethereum/go-ethereum/files/4931195/stacktrace.txt)

## version 
1.9.x-stable
## system
ubuntu20、centos etc..

**Comment by karalabe** [comment]
You'll need to provide a lot more information and logs, otherwise there's nothing to go about. We don't even know what you're seeing.

**Comment by TamirTian** [comment]
I can't see more details of logs in default level. 

I remember geth print normal 'reorganization' logs and some peers timeout, but it doesn't work.

I've been in situations like this many times

**Comment by TamirTian** [comment]
```
WARN [07-21|09:06:21.687] Served eth_sendTransaction               conn=   reqid=0 t="40.986µs"  err="unknown account"
WARN [07-21|09:06:39.955] Database compacting, degraded performance database=/data/ethereum/geth/chaindata
WARN [07-21|09:07:39.973] Database compacting, degraded performance database=/data/ethereum/geth/chaindata
WARN [07-21|09:08:39.985] Database compacting, degraded performance database=/data/ethereum/geth/chaindata
WARN [07-21|09:09:40.006] Database compacting, degraded performance database=/data/ethereum/geth/chaindata
WARN [07-21|09:10:40.048] Database compacting, degraded performance database=/data/ethereum/geth/chaindata
WARN [07-21|09:11:40.096] Database compacting, degraded performance database=/data/ethereum/geth/chaindata
```
I got these on other geth

**Comment by rjl493456442** [comment]
@TamirTian In this case, all write stalls because the underlying database(leveldb) has accumulated too many internal jobs(compactions) so it just suspends all writes until the jobs are done.

**Comment by TamirTian** [comment]
@rjl493456442 it only used 100+ iops, buy my instances is 3w iops+

**Comment by karalabe** [comment]
There's not much to debug here. Leveldb is starved of IO ops. Please double check that you are indeed storing the database on the drive with that many ioops.

**Comment by samuelmattjohnston** [comment]
@karalabe I see issues similar to this sometimes on our systems. What kind of information do you need to debug it?

From what I've seen compacting is a linear process that doesn't scale in speed with more IO/s, but rather latency. However, even that is still horribly slow. If I misunderstand the limitations, let me know what to do to get you information you need to debug and next time I see it on a system I'll be able to drop it here.

**Comment by TamirTian** [comment]
@karalabe just geth, and system's monitor say ok. Maybe i call many 'filter event' ?

I guess the question is 'internal queue'(just guess, i don't know the details of geth)

Can I optimize if it has  parameters?

**Comment by 9cat** [comment]
> 
> 
> @karalabe just geth, and system's monitor say ok. Maybe i call many 'filter event' ?
> 
> I guess the question is 'internal queue'(just guess, i don't know the details of geth)
> 
> Can I optimize if it has parameters?
any better solution on this.

Always happend on one node.
