### ISSUE TITLE
ethstats: stats.goerli.net not working

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#21345]
Somewhere between docker builds `ethereum/client-go:v1.9.15` (`db2cbcf60879c294d26d750b7e3f4f648c4ebfe613b274a66f3874267d61dac2`) and the current `ethereum/client-go:stable` (`d14301a810454b9701ff9af63eb882f17df9df84815f664e922f8c507f58774c`) reporting stats to https://stats.goerli.net/ broke.

Both builds generally throw the same error(s):

```
WARN [07-19|17:37:55.401] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-19|17:37:56.446] Transaction stats report failed          err="tls: use of closed connection"
```

The difference appears to be that `ethereum/client-go:v1.9.15` ignores this error and keeps trying. I get this error quite often in the logs, but it remains connected to the stats.goerli.net dashboard and it continues to report stats.

`ethereum/client-go:stable` on the other hand will report this error once, and then it seems to just give up.

I also tried with `ethereum/client-go:latest` and the issue remains.

Any build newer than `ethereum/client-go:v1.9.15` seems to report its block number once, then it just shows offline

**Comment by karalabe** [comment]
Thanks for reporting this! Fixed + also the underlying disconnect on Goerli stats.
