### ISSUE TITLE
Node sync fails

### ISSUE THREAD

**Issue by 0x53fa29jhezc** [ethereum/go-ethereum#21349]
Use the docker image on Google GCP with Container Optimised OS (1 CPU - 4GB RAM- SSD)

When I start the container the Node is syncing for a while.
Then I get this Error:

WARN [07-20|10:54:28.439] Checkpoint challenge timed out, dropping id=***** conn=dyndial addr=********:30303   type=Geth/v1.9.9-stable-01744997/linux-amd64/go1.13.5
INFO [07-20|10:54:28.457] Imported new state entries               count=814  elapsed=8.124ms     processed=80394540 pending=35995 retry=261  duplicate=2171 unexpected=11440
WARN [07-20|10:54:34.114] Checkpoint challenge timed out, dropping id=d775bde9d1b9d86e conn=dyndial addr=**********:30303    type=Geth/v1.9.16-stable-ea3b00ad/linux-amd64/go1.14.4
ERROR[07-20|10:54:53.985] Failed to unregister sync peer           peer=****** err="peer is not registered"

And the node stop syncing, but the process does not crash.

When I restart the container the syncing starts again for a while until it fails again 

here is the container creation command:

docker run -d --name ethereum-node -h 0.0.0.0 --restart always -v /mnt/stateful_partition/var/ethereum:/root \
           -p 8545:8545 -p 8546:8546 -p 30303:30303 \
           ethereum/client-go --ws --ws.addr "0.0.0.0" --http --http.addr "0.0.0.0"

**Comment by rjl493456442** [comment]
> WARN [07-20|10:54:34.114] Checkpoint challenge timed out, dropping id=d775bde9d1b9d86e conn=dyndial addr=****:30303 type=Geth/v1.9.16-stable-ea3b00ad/linux-amd64/go1.14.4

It's because the remote peer can't reply the required header in time.

> ERROR[07-20|10:54:53.985] Failed to unregister sync peer peer= err="peer is not registered"

There should exist some data race for un-registration

The node stops syncing I think it's due to no peer connection.

Btw `1 CPU - 4GB RAM- SSD` probably is not enough for running a full node?

**Comment by veox** [comment]
> Btw `1 CPU - 4GB RAM- SSD` probably is not enough for running a full node?

Sufficient on Goerli (or private net), but judging by the number of state entries (`processed=80394540`) this is not the case. (Goerli had slightly over 19 million state entries on 2020-07-19.)

**Comment by 0x53fa29jhezc** [comment]
Thanks guys 

Yea running it on mainnet.
Will try it with more ram.

Will comeback here and report the result.

**Comment by rjl493456442** [comment]
I will close it now. If any other issue show up, feel free to reopen it again.

**Comment by 0x53fa29jhezc** [comment]
@rjl493456442 

> Btw `1 CPU - 4GB RAM- SSD` probably is not enough for running a full node?

confirmed!

Created a new VM with 7.5 GB and the sync works without problems.

Maybe It's good to place the System Requirements a bit 'more visible' in the instruction AND maybe throwing an Exception would be better than let the sync hang/failing silently, in my opinion.

Think I am not the only person who ran into this.
On the web are a lot of (old) pages where you can read that a very small machine is enough  (Rasberry PI etc.)
