### ISSUE TITLE
Can't make ios

### ISSUE THREAD

**Issue by ToJen** [ethereum/go-ethereum#21340]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)
```
Geth
Version: 1.9.17-unstable
Git Commit: 9e88224eb86c92c78f5f03ffcd0793704a8b4309
Git Commit Date: 20200716
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.10
Operating System: darwin
GOPATH=/my/go
GOROOT=/usr/local/Cellar/go@1.13/1.13.10_1/libexec
```

#### Expected behaviour
```
$ make ios
[...]
Done building.
Import "build/bin/Geth.framework" to use the library.
```

#### Actual behaviour
```
$ make ios
[...]
# gobind/gobind
Geth_darwin.m:5133:17: error: method 'sign:p1:error:' in protocol 'GethSigner' not implemented [-Werror,-Wprotocol]
gobind/Geth.objc.h:87:1: note: method 'sign:p1:error:' declared here
/code/go-ethereum/build/bin/gomobile: darwin-arm: go build -tags ios -v -ldflags -s -w -buildmode=c-archive -o /var/folders/05/rlnn721s0_d3yhbbx027602dsk4gsv/T/gomobile-work-343520635/geth-arm.a ./gobind failed: exit status 2
```

#### Steps to reproduce the behaviour
- I cloned the repo
- I ran `make ios`
- This didn't work so I ran `make geth android ios`. The Android `.aar` was built but not the iOS `.framework` folder.

#### Backtrace

````
[backtrace]
````

**Comment by KevinVitale** [comment]
I'm seeing exactly the same issue.
```
macOS Catalina, 10.15.6 (19G73)

Version: 1.9.18-unstable
Git Commit: 123864fc055482279fa61ce063b7e2aad48c0609
Git Commit Date: 20200721
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.5
Operating System: darwin
```

**Comment by fjl** [comment]
I can reproduce the build failure. The issue is with this interface: https://github.com/ethereum/go-ethereum/blob/997b55236ebb5c35a87fa25dd5ec89fe6240d801/mobile/bind.go#L34-L36

When gomobile generates objc, it uses the parameter names for the method selector. For the Signer interface, it generates

```
@protocol GethSigner <NSObject>
- (GethTransaction* _Nullable)sign:(GethAddress* _Nullable)p0 p1:(GethTransaction* _Nullable)p1 error:(NSError* _Nullable* _Nullable)error;
@end
```

For the GethMobileSigner type https://github.com/ethereum/go-ethereum/blob/997b55236ebb5c35a87fa25dd5ec89fe6240d801/mobile/bind.go#L42 it generates:

```
- (GethTransaction* _Nullable)sign:(GethAddress* _Nullable)addr unsignedTx:(GethTransaction* _Nullable)unsignedTx error:(NSError* _Nullable* _Nullable)error {
```

This doesn't compile because the method selectors don't match.

**Comment by ToJen** [comment]
Can confirm it works now 👍

**Comment by KevinVitale** [comment]
Builds successfully 👍
