### ISSUE TITLE
Connect non bootstrap nodes on a private chain

### ISSUE THREAD

**Issue by danielescattaglia** [ethereum/go-ethereum#21355]
Hi 

I'm working on a private chain but i've not so clear the discovery protocol. I'm using bootnodes to connect nodes on the chain but nodes seems to connect only to the bootnodes, they never get connected to other non-bootstrap nodes. I can connect manually all nodes using admin.addPeer, so it doesn't seem a network related problem. Is it the normal behaviour?
Thanks

Bye

Daniele 

#### System information

Geth version: `1.9.16-stable`
OS & Version: `Linux Ubuntu 20.04`
Commit hash : `ea3b00ad75aebaf1790fe0f8afc9fb7852c87716`

#### Expected behaviour
Using a full fledged geth as a bootnode. A node running with --bootnodes parameter, connected to the geth acting as bootnode, should connect to some/all nodes that bootnode has as peers. 

#### Actual behaviour
In a 10 node chain, bootnode get connected to all other nodes, other nodes are connected only to bootnode and never try or get connected to other node of chain. All nodes are running in the same private network. Same behaviour running boostrap node as normal node or miner. Sometime I get a RPC Timeout, but connecting the node with addPeer I'm able to connect the node.

#### Steps to reproduce the behaviour
1. Run a node with --nodekey parameter and no --bootnodes parameter. 
2. Other nodes run with --bootnodes pointing to the node at point 1.

`geth --mine --miner.threads=1 --allow-insecure-unlock --unlock 0 --password ./.accountpassword  --nodekey nodekey --networkid "35"  --datadir /ethereum --pprof --pprof.addr x.x.x.x --http --http.corsdomain "*"  --http.addr x.x.x.x --http.vhosts "*"  --http.api debug,net,admin,eth,web3 --ws --ws.origins "*" --ws.addr x.x.x.x  --ws.api eth,net,web3,personal  --metrics --metrics.expensive --nat=extip:x.x.x.x --nousb --verbosity 6 --trace /tmp/trace.txt --cpuprofile /tmp/cpu.txt --netrestrict x.x.x.x/y --cache 2048 --port 30303`

`geth --bootnodes "enode://z@x.x.x.x:30303" --networkid 35 --datadir /ethereum --pprof --pprof.addr x.x.x.y  --http --http.corsdomain "*" --http.addr x.x.x.y --http.vhosts "*"  --http.api debug,net,admin,eth,web3 --ws --ws.origins "*"   --ws.addr x.x.x.y --ws.api eth,net,web3,personal --metrics --metrics.expensive --nat=extip:x.x.x.x --nousb  --verbosity 6  --trace /tmp/trace.txt  --cpuprofile /tmp/cpu.txt --netrestrict "192.168.100.0/24"   --cache 2048 --syncmode "full"  --port 30303`

#### Backtrace

````
TRACE[07-22|07:33:01.633] Findnode failed                          id=c28134e93d2c425f failcount=1 results=0 err="RPC timeout"
````

**Comment by axon-consultancy** [comment]
We have the same issue on what is currently latest master:

```
Geth
Version: 1.9.19-unstable
Git Commit: 9e04c5ec83cbbb227e63e53d3cd08d97e5f2a874
Git Commit Date: 20200729
```
I have created a batch script that starts a small Clique based private network with 1 geth full node that acts as bootnode and 3 signer nodes (clique) that can be used to reproduce the issue. Keys and script can be found here: https://gofile.io/d/xWSv6U

**Comment by holiman** [comment]
Should be fixed in last release

**Comment by adamschmideg** [comment]
I assume this got fixed in the last release. If you face the same problem, please open a new issue.
