### ISSUE TITLE
connect to nodes that not have update(hard fork)

### ISSUE THREAD

**Issue by prettyCoders** [ethereum/go-ethereum#21354]
![图片](https://user-images.githubusercontent.com/36216120/88148958-f8ed8180-cc31-11ea-9685-880d2538ebaa.png)

**Comment by prettyCoders** [comment]
my node is a new node, if it always connect to nodes that not have update, so, my node is useless to me!

**Comment by prettyCoders** [comment]
![图片](https://user-images.githubusercontent.com/36216120/88149419-a3fe3b00-cc32-11ea-8e5d-4306810b2890.png)

**Comment by rjl493456442** [comment]
https://github.com/ethereum/go-ethereum/releases/tag/v1.9.9 1.9.9 already enables the hardfork.

**Comment by prettyCoders** [comment]
@rjl493456442 But the latest block height is 10841850, my peer`s latest block height is 10399145

**Comment by rjl493456442** [comment]
The fork point is #9200000. So definitely it's a node with fork enabled.

Why the remote peer is lagging behind? There are several reasons like the peer is out of sync. 
But the peer is still helpful for your peer because the local chain height is 550,000.

**Comment by prettyCoders** [comment]
Oh. I'm sorry, it`s problem of etc, i came to the wrong place
