### ISSUE TITLE
sendRawTransaction: fails without presence of an arbitrary account

### ISSUE THREAD

**Issue by mudpedal** [ethereum/go-ethereum#2135]
What I did is make an application that signs transactions offline then sends them via sendRawTransaction, everything works great besides that I have to trick geth each time by storing a dummy wallet in the keystore folder as UTC--time--address. If I dont I get the "account does not exist or balance too low" error. For the moment, I got past this with this dummy file trick, but I wish sendRawTransaction wouldn't check if the wallets exists in your keystore because it might just someone else's wallet and I can act as a gateway.

If you dont mind, I can even make it myself and make a pull request regarding this if it's cool.

Andi.

**Comment by karalabe** [comment]
That's most definitely a bug then :) It should work fine without requiring even a dummy account. If you wish, please fix it and open a PR. If not, we'll look into it :)

**Comment by mudpedal** [comment]
I just tested this again, seems it's been already fixed in geth 1.4.0. Sorry to bother you with this issue, seems it's Not A Bug. You may close this.
