### ISSUE TITLE
what's the meanning of miner.recommit?

### ISSUE THREAD

**Issue by DinoStray** [ethereum/go-ethereum#21359]
miner.recommit is one of the  config parameter,  what's the meaning of it?
If mining pool set this, what's the effect?

**Comment by rjl493456442** [comment]
Usually in ethereum mainnet, the average mining time is around 15s. But during this "LONG"'
procedure, lots of new transactions with higher gas price will arrive but they have to wait
a few seconds to be included even the price is higher than the txs in the mining block.

So we have this idea to re-create the mining block with configured interval(`--miner.recommit`).
In this way, we can always try to fill the mining block with the highest price txs.

The upside is quite obvious
- the mining pool can get a higher revenue
- it's fairer for users who send the high price transaction
- it's basically no overhead for switching the mining block in the miner side

The default interval is 3 seconds. You can choose the value by yourself.
