### ISSUE TITLE
les node can't serve historical block query

### ISSUE THREAD

**Issue by secmask** [ethereum/go-ethereum#21363]
hello, I have two node, one is archive node, and the other is LES node
I setup my LES node to connect to my archive node, and `admin.peers` show it connected
1. archive node: ubuntu 18.04, geth v1.9.15
2. les node: macos, geth v1.9.17

the problem is when I call a contract function using my node
- call with old block using my archive node works fine
- call with latest block using LES node works fine too
- call with old block using LES node, it return error: `getDeleteStateObject (1e158c0e93c30d24e918ef83d1e0be23595c3c0f) error: no suitable peers available`

my archive node has already set `--light.serve 50 --light.ingress 10240 --light.egress 10240 --light.maxpeers 70`, and I am the only client connect to the archive node. Do you have idea on how to make my LES node to work with old block?

**Comment by osiztechnologies** [comment]
We also faced same issue. No peercount increasing in light sync mode. Kindly give solution to us.

**Comment by zsfelfoldi** [comment]
I quickly checked the code and it looks like it should work so I am now archive syncing Goerli to see why it does not. Will get back soon.

**Comment by osiztechnologies** [comment]
@zsfelfoldi Is there any update for this issue.

**Comment by zsfelfoldi** [comment]
Found the issue in the old light fetcher code which has been recently replaced on master. Can you try updating with the recent master branch on the client side? The new code does not have the same faulty condition and old state retrieval seems to work now.

**Comment by secmask** [comment]
I tested and it worked on my side
