### ISSUE TITLE
[JSRE] Duplicate eth.contract in tab-completion

### ISSUE THREAD

**Issue by fzzr-** [ethereum/go-ethereum#2137]
![screen shot 2016-01-20 at 17 19 47](https://cloud.githubusercontent.com/assets/888526/12451510/f0bddcd8-bf9a-11e5-99d9-a9f5deadf2d8.png)

**Comment by karalabe** [comment]
Not sure if this still applies after transitioning to the new API implementation which should gather the list of supported methods automatically. Will look into this, thanks for reporting it!

**Comment by karalabe** [comment]
This issue seems to be corrected upstream in develop, so closing.
