### ISSUE TITLE
Rinkeby faucet doesn't seem to work

### ISSUE THREAD

**Issue by Armando1514** [ethereum/go-ethereum#21375]
Getting an error insufficient funds for gas * price +value when trying to obtain rETH. .

![image](https://user-images.githubusercontent.com/23108930/88477212-60f7dc80-cf3e-11ea-9a43-77dd293fbf7d.png)

**Comment by MariusVanDerWijden** [comment]
Confirmed, get the same error and sometimes "getDeleteStateObject (31b98d14007bdee637298086988a0bbd31184523) error: no suitable peers available"

**Comment by karalabe** [comment]
Restarted it, but as long as the LES discovery is disabled, we're going to keep doing this non stop.

**Comment by uivlis** [comment]
@karalabe Same issue now, pesky ` insufficient funds for gas * price + value`. Could you wave your hand for that fix again?

**Comment by CircuitBreaker88** [comment]
@karalabe I am running into the same issue trying to get Test Eth on the kinkeby testnet

apologies to bother you but if you can restart it once more it would be greatly appreciated

**Comment by aasagba** [comment]
I am also getting the same issue unfortunately, any chance it could be restarted please? Thanks.

**Comment by billpottle** [comment]
Having the same issue. Thanks for your hard work

**Comment by dportabella** [comment]
same issue here.

**Comment by sebamatusr** [comment]
yeah I can't get it to work either

**Comment by bitboki** [comment]
Cant get it to work same thing, can anyone send me some ether if ya dont mind, may I have some more soup sir?

0xE412CB6bE5b322Ce8C0d82B9C37E683cf719D0cE

**Comment by Raid55** [comment]
I can't get any eth on rinkeby faucet. There is no faucet alternative (#anti-consumer). I am running dry (and too lazy to switch networks)!!!
`0x903482EDd1eDeF99ef30e66257dEd3BE998930ff`

YOU DON't MISS YOUR RINKEBY ETH, TILL THAT ETH RUNS DRY
seems like only yesterday, I was building dApps
now its gone away, and I know its in a different wallet
no testing for me, or transactions for you, cant deploy....smart contracts
How long...till we see a fix? How long...till we see success...HOW LONG?
(lol thank god I'm not a lyricist)

lol I'm bored....ok have a good weekend everyone!

**Comment by NadimBaker** [comment]
Same issue, any solutions in sight?

**Comment by CRYPTO-GENIK** [comment]
It's not working again

**Comment by yasiryagi** [comment]
+1

**Comment by OsoianMarcel** [comment]
+1

**Comment by 0xnu** [comment]
+1

**Comment by tontonkiller** [comment]
+1

**Comment by gaieges** [comment]
@karalabe when you have a chance can you take a look at this plz?

**Comment by gCAN9** [comment]
Yep, not working now either.

**Comment by justlucdewit** [comment]
its not working for me either `0x621edbe5d9302dD10caBFF79FDD81dea35d57db8`

**Comment by michel-lacle** [comment]
Can someone share alternative faucets? I don't want to spend my entire netflix night looking for working faucets.

**Comment by sam-woodridge** [comment]
Not working here either. If you could restart that would be awesome.

Also in the meantime if anyone wants to share some test coins I would appreciate it :)

`0x16c7d59468CA4A2e1bA1DcC1A866fDD47e121647`

**Comment by mpetrone** [comment]
Another guy here asking for some test coin give that the faucet is not working 0x8f08A8466388a46AEE98570478cD7391e4d4D1ba
I would really appreciate it!

**Comment by Deelux** [comment]
Still not working 👎 
If anyone has some coins so I can start testing, would be great <3
0x5d6F3d0c92D0564151357B0863E55e9ed4631b8d

**Comment by 6proof** [comment]
Sorry, faucet is not working... if possible could someone please send a few Rinkeby to cover testing transaction fees?
0xdC3Ad42f950F12e7DbAD469267F9e48623637A31

Thanks in advance!

**Comment by 6proof** [comment]
Looks like faucet worked for a bit and is down again... unfortunately I did not receive any :)  Please reload or restart faucet, and if possible send some Rinkeby to following address.  Thanks!
0xdC3Ad42f950F12e7DbAD469267F9e48623637A31

**Comment by 6proof** [comment]
Sorry to keep posting here... looks like the faucet started and then failed again, now showing results with following error:
     "No Ethereum address found to fund"
Are there other faucets?  I'll be happy to host one if someone can send me some Rinkeby to test with.  Otherwise will need to move to another TestNet.  Thanks, let me know how I can help!

**Comment by trazyn** [comment]
Still go error 😥
"No Ethereum address found to fund"

Pls give me some coins start test, thanks!
0xCfecbaBF3E313E2Aea847B4f62DEF479fC255E44

**Comment by Deelux** [comment]
Yup, same error for me.

**Comment by pauliepontoon** [comment]
Same error here, would love to proceed with some test ETH:
0x0067d567BFEaEcB819ca25ca37f35078FF4634CA

**Comment by billpottle** [comment]
@pauliepontoon , @Deelux , @trazyn , @6proof , @mpetrone , @sam-woodridge , @justlucdewit 

I grabbed 18 the last time it was up and sent you each 0.5 ETH which hopefully should be enough. Let me know if any issues.

**Comment by pauliepontoon** [comment]
thx!

**Comment by cuhulainn** [comment]
@billpottle - if you can spare any more, could you send me some as well, please?  Thanks!
0x292039727d563aA9c4cC9CAeee077872B9BC7140

**Comment by billpottle** [comment]
@cuhulainn - You got it!

**Comment by cctanfujun** [comment]
could any one can share me some,Thanks!   

0xa6870754C96b0c910ceBB672948e7D950e1881df

**Comment by billpottle** [comment]
@cctanfujun - You are good to go!

**Comment by billpottle** [comment]
Also looks like mycrypto has  created a new faucet. app.mycrypto.com/faucet

**Comment by GTDev87** [comment]
I can use some too if anyone has some extra 0xd4fB42a95CF8B82f0400291661e8F86474F7Cd68.  Thanks

**Comment by alber06** [comment]
Can anyone share me some too please?

0x8A08057808E3F746bF923e18268bDaEa9699D436

**Comment by tkdcoop** [comment]
@alber06 You are all set

**Comment by alber06** [comment]
> @alber06 You are all set

@tkdcoop many many thanks!!

**Comment by olimdzhon** [comment]
Can anyone share me some too please?

0x26f5061c62115aba83c2Fd180b32a304Df6Ca8Be

**Comment by eirtscience** [comment]
Hello Guy , could anyone share some eth with this address please:

 0x995cE948e12a4A40875156a284C17E7940C7BF89

**Comment by safciezgi** [comment]
> Still go error 😥
> "No Ethereum address found to fund"
> 
> Pls give me some coins start test, thanks!
> 0xCfecbaBF3E313E2Aea847B4f62DEF479fC255E44

I have this issue for 2 weeks, I need some test ether to complete my school project, please someone send me some I would be happy.  0xA8bdcfF6F799c7337cb535AA4c202BBbFF6Eb6ba

**Comment by billpottle** [comment]
@safciezgi , @eirtscience , @olimdzhon - Have you guys tried the app.mycrypto.com/faucet listed above? I just tried it and it worked for me. Just make sure your metamask is connected to Rinkeby. If you can't get it to work, reply here and I will send you some.

**Comment by safciezgi** [comment]
> @safciezgi , @eirtscience , @olimdzhon - Have you guys tried the app.mycrypto.com/faucet listed above? I just tried it and it worked for me. Just make sure your metamask is connected to Rinkeby. If you can't get it to work, reply here and I will send you some.

Yes it worked Thank you so much!

**Comment by Deelux** [comment]
> @safciezgi , @eirtscience , @olimdzhon - Have you guys tried the app.mycrypto.com/faucet listed above? I just tried it and it worked for me. Just make sure your metamask is connected to Rinkeby. If you can't get it to work, reply here and I will send you some.

Thank you! This worked like a charm. If anyone has problems, check out this link.

**Comment by dvdsm** [comment]
Can someone please transfer some ETH to this address? 
0x965eE3C36a6C7D512142949351a2372FFB96221E
Thank you!

**Comment by jcswapper** [comment]
@billpottle please could you send me 3 Rinkeby ETH 0xB23FaFfF64E0670E8E72a2B522e5e63e7d83940e ? Thank you !

**Comment by IoT-master** [comment]
Can I get 18.75 Rinkeby ETH? 0x6b0eee108783fF52Ff2c3477f99C0DE4Df76a4DD Thanks in Advance

**Comment by karalabe** [comment]
Hey all, the upstream faucet is back online https://faucet.rinkeby.io/

Sorry about the downtime, Twitter decommissioned their old site that we used to fetch tweets from and needed to switch over to an API workflow, which is a bit more work than we wanted to put in during xmas. Should be fine now, please ping if there's still some issue.

**Comment by DGKSK8LIFE** [comment]
this ^

**Comment by gaieges** [comment]
Confirmed working, thanks @karalabe !!

cc: @uivlis

**Comment by DGKSK8LIFE** [comment]
someone lock/archive the thread

**Comment by grantweii** [comment]
It seems to me that the faucet is not woking again? Just started working with test networks. Does the red bar mean it has failed?

**Comment by lukajose** [comment]
Still failing but as mentioned above just visit https://app.mycrypto.com/faucet it works!

**Comment by ShinoyVK** [comment]
Can anyone send me some rinkeby test ethers please...Tried myltiple times from faucet, couldnt get any.
 Thanks in advance..
0xE734EC83b615DEDd7CB2b24DDd69b3dF56735d1f

**Comment by ligi** [comment]
@ShinoyVK which URL did you use?

**Comment by ShinoyVK** [comment]
https://faucet.rinkeby.io/
this one. I pasted fb the post URL and says no ethereum address found.

**Comment by ligi** [comment]
Was it a public FB post? Can you share it?

**Comment by lukajose** [comment]
just use twitter it works fine for me, I did it just now

**Comment by ligi** [comment]
It would still be good to know if there is a real problem with the FB auth - so the link would be helpful still

**Comment by ShinoyVK** [comment]
> Was it a public FB post? Can you share it?

ahh...i checked it now and it was not public. Sorry..i should have checked it before. I made it public and test ethers got funded.
Thank you so much Ligi..!!

**Comment by ShinoyVK** [comment]
> just use twitter it works fine for me, I did it just now

will try that for sure. Thanks Lukajose

**Comment by ligi** [comment]
@ShinoyVK thanks for getting back to us! Glad it worked now for you

**Comment by karalabe** [comment]
Facebook is broken now even for public posts. I think they finally switched over to fully use AJAX so we'll need to bite the bullet and roll out APIs.

**Comment by karalabe** [comment]
> > Was it a public FB post? Can you share it?
> 
> ahh...i checked it now and it was not public. Sorry..i should have checked it before. I made it public and test ethers got funded.
> Thank you so much Ligi..!!

Oh, or maybe it works. Funky, something's weird then.

**Comment by Shahzayb** [comment]
> Facebook is broken now even for public posts.

Same for me. And I don't have a Twitter account. 0x59dAC24F621100c5fD781463d248bC65D55a0A55

**Comment by mickys** [comment]
@karalabe @ligi faucet seems to be stuck again.

**Comment by sumit-sharma7** [comment]
Faucet is not working for me as well.

**Comment by chrishorizon** [comment]
Faucet is not working. Anyone have spare coins I'd appreciate it!
0x9A69370688D0130C1CcA5B606Ddcd07CC2F4B89C

**Comment by muharremb** [comment]
It seems Faucet is not working. If anyone sends me spare coins, it would be great. Thanks again. 
0x5F28a6245b28D53AB7b43cCCF828Ce04F5deabda

**Comment by MayerDaniel** [comment]
@karalabe the faucet is dead again! If anyone has extra eth to spare please hit me up 0x5f2d21Bc72B8F190FD0d330F6cfdC0F8b7C3Fc8E

**Comment by MayerDaniel** [comment]
Fixed! Thanks for the swift response whoever reset it!

**Comment by MayerDaniel** [comment]
Just kidding. Its not. There was one peer up for a moment but no longer

**Comment by Oleh-Pashchenko** [comment]
The same issue, if someone could send a tokens  I'd appreciate it 0xb9390a79B7C77102D03e1463E6a5b2aC60c26212

**Comment by Cruzm430** [comment]
Also getting that issue. If anyone can send to me too, I'd greatly appreciate it! 0xf29838b6eaf1F86e82330A35868aD35e38664c8c

**Comment by CourdYou** [comment]
I'd greatly appreciate If anyone can send to me Reth. 0xC2a8a09c4ABD25B1581f66f805AA3Effa51cE99F

**Comment by davidrichard23** [comment]
I'd really appreciate some tokens if anyone can spare them! 0x51bFB4CAeA1780e8200b8B52700c0EABa94b699D

**Comment by stevenliu081894** [comment]
It's down again! I'd really appreciate some tokens if anyone can spare them! 0xae64482A534a81CB3bef9152c900CBd8a4597E0A

**Comment by VictorOdede** [comment]
Faucet is still down! If anyone has some spare tokens kindly send to  0xBD8EFC56c7D037358890E645C99679aa4df7Bb00

**Comment by rogotulka** [comment]
I also have problem with fund, could you send me some ETH to 0x7f0F71509421aD7E44B7F2E4A56013b903e7954c

**Comment by samkala11** [comment]
can you please send some ETH to 0xFD130CF35a0071983BC80758F7CbE0bd061Daed3

**Comment by epintos** [comment]
I am also having the same problem, could you send me some ETH to 0xBCBf295f3A59b8038324C2395Cc9ae482f2725A2, please?

**Comment by questionreality** [comment]
Facing the same problem. If anyone has got spare ETH, could you please send them to 0x2564E0F71aA87a5b940112fB778713d5B2b59b87?

**Comment by luciszzZ** [comment]
I am also having the same problem, could you send me some ETH to 0x5812B9296226f278A1463B0688Ab8F7484153320 please?

**Comment by Edalgo** [comment]
Same here.  How can I get test rinkeby ETH to this wallet, every faucet is not working..

0x7510073855cbD342b7eD5a9AAE591916bfBFB1A7

**Comment by luciszzZ** [comment]
> 同样在这里。我怎样才能得到这个钱包的测试 rinkeby ETH，每个水龙头都不工作..
> 
> 0x7510073855cbD342b7eD5a9AAE591916bfBFB1A7
可以参考https://support.mycrypto.com/how-to/getting-started/where-to-get-testnet-ether

**Comment by Edalgo** [comment]
Thanks for sending!

**Comment by ianskea** [comment]
I am also having the same problem. If anyone has got spare ETH, could you please send them to:
0xBE624b1E2b411AB2a3e703a55591D7273A4E473F

**Comment by dataonoff** [comment]
Same problem here. If anyone has spare ETH 🙏 to share, I would gladly appreciate.
ETH address: 0xa77F02A8316290daa12a600b5e28146c8Fb2f1dE

**Comment by mp-mcb** [comment]
Same problem. Please send some ETH to 0x5fFecA8333463399e9474aBf1081a4230406a471 if possible.
Thanks.

**Comment by ianskea** [comment]
I managed to find a working faucet at:
https://app.mycrypto.com/faucet

**Comment by FaisalAli19** [comment]
The same issue here. Could you please assist if you have any spare ETH?
Address: 0x349aE19523245c36825c71C8D0e07166B9ca1eaE

**Comment by ezellbuoee** [comment]
Facing the same issue, please send some ETH to 0x6A0ffC5cb9BBC54A5508C648542C2fF037809d50 if possible, thanks in advance

**Comment by indeedhat** [comment]
I am also getting the `insufficient funds for gas * price + value` with my address `0x216D45548f097Dab650Db1D9E583c2815252BE46`

The faucet mentioned by @ianskea is working for me but they only give 0.01eth a time so if you need a whole bunch for testing it takes a good while

**Comment by v0st0k1** [comment]
Still not working, I would appreciate if you could send me some eth to 0xa543D4EEA426Bd16630f2461D3b955e8A8045a82

**Comment by JL978** [comment]
Seems like everyone on this issue is requesting ETH so I'm going to do the same:
0x0480A1F4c7a2Bfc5d2eF018F857E0c2c9827d5e6
Thank you very much!

**Comment by Edalgo** [comment]
Hello would it be possible to get 3 test rinkeby eth sent to 0x7510073855cbD342b7eD5a9AAE591916bfBFB1A7 ?  Nothing seems to be working on the faucets...

**Comment by JossDuff** [comment]
Just need a enough eth for a single baby sized function call: 0x961bdA3F1b384f3c1F8DBE26B5eF46bd5a9A80c3

**Comment by polyballwin** [comment]
Can someone pass me some ether in Rinkeby test? Thank you!
0x855aA52aA655E2b7999B7a6453800310fccF427B

**Comment by godindustry** [comment]
0x855aA52aA655E2b7999B7a6453800310fccF427B

**Comment by nyash04** [comment]
> Restarted it, but as long as the LES discovery is disabled, we're going to keep doing this non stop.

Account ID:
0x878Eb98a99926e21f564F6c5753EA637b2e451b2

I have already used the method of twitter but it is throwing error - insufficient funds for gas * price + value

Can anyone confirm this issue please?

**Comment by Jabbasmith** [comment]
Same here, I used the Twitter approach and still it does not work, coming back with insufficient
Please send me some ETH by Rinkeby.  I need it for testing.   Thanks 

0x4e34b78C93298314C2779bd61F0DC3bA333DA745

**Comment by milesguidon** [comment]
Same issue for me -- not working with my tweet links. 

If you send Rinkeby ETH to the wallet address below, you will be visited by the MAXIMUM SUCCESS GHOST and he will bestow upon you his JOYOUS GIFTS for the rest of your long and fruitful life:

0x83d72B8C0769C92a0E39aE976d88A1d55e5d647b
