### ISSUE TITLE
Docker Build failed due to ethereum 

### ISSUE THREAD

**Issue by ali2210** [ethereum/go-ethereum#21393]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`1.9.14-stable
OS & Version: Windows/Linux/OSX Linux
Commit hash : (if `develop`) 

#### Expected behaviour
github.com/ethereum/go-ethereum/crypto/secp256k1  
   -- when I run on docker @ this dependency , exec gcc executable file not found in this $path 
and after that
github.com/ethereum/go-ethereum/rpc/ exec gcc executable file not found in this $path

#### Actual behaviour
Build Ok

#### Steps to reproduce the behaviour
I 'm using the ethereum crypto package in my project but docker compile whole packages before produce build 
#### Backtrace
1. Step 1: exec gcc executable file not found in this $path
2. search folder inside go/src
3. search on google but nothing found

````
[backtrace]
````

**Comment by i-norden** [comment]
There is some c and cgo code in that package, do you have a gcc compiler in your docker image? If you are using a minimal base image like alpine you will need to add it in the dockerfile yourself e.g. `RUN apk --update --no-cache add g++`

**Comment by karalabe** [comment]
^
