### ISSUE TITLE
invalid transaction: invalid transaction v, r, s values

### ISSUE THREAD

**Issue by Yazanalsharif** [ethereum/go-ethereum#21394]
Hi there,

can you help me please
i created my private network with geth with gensis.json file
`{
    "config":{
        "chainId":1337,
        "homesteadBlock":0,
        "eib155":0,
        "eib158":0
    },
    "difficulty":"0x20000",
    "gasLimit":"0x8000000",
    "alloc":{}
}`
i have runed geth with `geth --datadir = ./chainData init gensis.json` in root folder

and i am using  this command to start geth :

geth --rpc --rpcapi="personal,eth,web3,net,miner" --datadir=./privateNetworkEthereum --nodiscover --allow-insecure-unlock

and in another terminal i attach the geth with this command
geth --rpc --rpcapi="personal,eth,web3,net,miner" --datadir=./privateNetworkEthereum --nodiscover --allow-insecure-unlock

after that i mined some ether and i unlocked my account

so the problem is the transaction is Submitted

Submitted transaction fullhash=0x7cdca37a009deca7db97125114bf50506d8a23795d5be27fb358b6de38eb267c

but no transaction happened

and when i am trying deploy my smart contract in geth it's display this error

invalid transaction: invalid transaction v, r, s values

Geth version: `1.9.16`
OS & Version: Windows
Commit hash : (if `develop`)

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
