### ISSUE TITLE
core: while sending transaction-hashes to peer, truncated transaction-hashes are assumed to be known by peer. 

### ISSUE THREAD

**Issue by timcooijmans** [ethereum/go-ethereum#21418]
Hi,

Geth keeps track of the transactions known to the peers:
https://github.com/ethereum/go-ethereum/blob/d21303f9ddac0c01fa5acb8a8dd98758daa73d15/eth/peer.go#L104

This set is filled when transactions are send or broadcasted to a peer, for example in:
https://github.com/ethereum/go-ethereum/blob/93142e50c3d4ced88ca1620b4cee2038c4c145ba/eth/peer.go#L397-L413

Note that this functions adds the whole slice of transaction-hashes to the list of transactions to be known by the peer. 

However when the hashes announced on the `p.txAnnounce` channel are actually send. Only `maxQueuedTxs` (currently 4096) are send to the peer, the rest is truncated:
https://github.com/ethereum/go-ethereum/blob/93142e50c3d4ced88ca1620b4cee2038c4c145ba/eth/peer.go#L259-L267

This results in transactions that we assume are sent to the peer, but actually are not.

To make matters worse, the transaction-hashes are truncated such that the oldest ones are deleted first. When having more than `maxQueuedTxs` transactions from a single "own" account in the tx-pool as pending, the transactions having the lowest nonce will never be announced or broadcasted to other peers. This blocks all later transactions from this account.

**Comment by karalabe** [comment]
Yes, this is true. That said, Geth's default pool limits are 4K, so even if you send more, the remote side is going to drop it anyway. Apart from revamping the txpool to persist to disk, there's no easy way around this.

**Comment by timcooijmans** [comment]
The issue I hit, was that I had more than 4K "own" transactions in the pool. And the truncating causes the oldest transactions to be dropped. This will cause a nonce gap and pool of peers to be filled with newer transactions and the older transactions will never be send to the peers. 

Another issue may be during re-orgs.

**Comment by karalabe** [comment]
Yes, this is a know limitation unfortunately.

**Comment by timcooijmans** [comment]
Can't we fix this? 

We could make a "smarter" selection of the transactions to be announced (16 oldest ones, and 4080 newest ones) and only mark those transactions as known by the peer. This would resolve such deadlock situations. 

I can prepare a PR if you want...

**Comment by holiman** [comment]
This is not trivially fixable - I mean, you can fix the problem that you are having, but the macro effects of that will still be the same: first we send `4K` transactions, then we'll send another batch of `4K` because "Hey, peer doesn't have these", and continue to do so. And the peer will most likely drop all but the first batch on the floor. 

This means that the overall network noise/traffic goes up. As Peter said, we can't really solve this until we have a disk-backed txpool
