### ISSUE TITLE
personal.sign failed with error of invalid address

### ISSUE THREAD

**Issue by zexxlin** [ethereum/go-ethereum#21417]
#### System information

Geth version: `v1.9.18`
OS & Version: Arch Linux

#### Expected behaviour
`personal.sign` should returned signed hex string successfully

#### Actual behaviour
GoError: Error: invalid address

#### Steps to reproduce the behaviour
1. Attach to interactive console of a full node on a private chain with `geth attach`
2. Execute `personal.newAccount()` to create a new account
3. Use the newly created account to sign random message
`````
acc = personal.listAccounts[0] // 0x79675200a034a60659f625d29a95f3630e825c62
personal.sign(msg, acc)
`````
4. Double check the address is valid with web3 utils
#### Backtrace

````
GoError: Error: invalid address at web3.js:3930:11(47)
	at native
	at <eval>:1:18(7)
````

**Comment by MariusVanDerWijden** [comment]
Could confirm: 
`geth --goerli console`
```
> personal.newAccount()
Passphrase: 
Repeat passphrase: 
"0x60e68d9744cd83c08cec55b41e057aeeae394a2e"
> acc = personal.listAccounts[0]
"0x60e68d9744cd83c08cec55b41e057aeeae394a2e"
> personal.sign("adsf", acc)
Give password for account 0x60e68d9744cd83c08cec55b41e057aeeae394a2e
Password: 
GoError: Error: invalid address at web3.js:3930:11(47)
	at native
	at <eval>:1:23(4)
```
