### ISSUE TITLE
geth does not exit

### ISSUE THREAD

**Issue by LeeAbell79** [ethereum/go-ethereum#2142]
geth hangs issuing : geth js <(echo 'console.log(admin.nodeInfo.enode); exit;')

I0122 07:19:00.080405    7824 blockchain.go:215] Last block: #0 [d4e56740…] TD=17179869184
I0122 07:19:00.080607    7824 blockchain.go:216] Fast block: #0 [d4e56740…] TD=17179869184
I0122 07:19:00.091089    7824 cmd.go:114] Starting Geth/v1.3.3-c541b38f/linux/go1.5.1
I0122 07:19:00.091333    7824 server.go:311] Starting Server
I0122 07:19:02.558016    7824 udp.go:204] Listening, enode://edadda367c04b49d3dd44a5830dadb843b6db30282ea73bcff435400fb0c257a7a863aabd527b001cf7046c7e2d70978640ea81085559660cb58af864396205c@[::]:30303
I0122 07:19:02.558532    7824 backend.go:526] Server started
I0122 07:19:02.582444    7824 server.go:552] Listening on [::]:30303
I0122 07:19:02.582978    7824 ipc.go:112] IPC service started (/home/ethnetintel/.ethereum/geth.ipc)
enode://edadda367c04b49d3dd44a5830dadb843b6db30282ea73bcff435400fb0c257a7a863aabd527b001cf7046c7e2d70978640ea81085559660cb58af864396205c@[::]:30303

**Comment by karalabe** [comment]
This was fixed in the develop branch, but it will not be backported into the 1.3.x releases as far as I know as it's not something essential. If you really really need it, I'd suggest trying develop, otherwise it will land after the homestead release is done.

**Comment by LeeAbell79** [comment]
this issue was in 1.5.1

**Comment by karalabe** [comment]
I was talking about Geth versions. Current master is 1.3.3, develop is 1.4.0.

What I'm guessing you wrote above is the Go runtime version, which is independent of this issue.
