### ISSUE TITLE
Mining at 1 Wei - No error but TXns never mined

### ISSUE THREAD

**Issue by cyberiums** [ethereum/go-ethereum#21442]
Hi there,

We are trying to build a private network with mining at 1 Wei. 
Setup: We have 3 miners and 2 RPC nodes. Each node has the geth flag "--gasPrice 1". But the transactions wait indefinitely to get mined. There is no error or alert in Geth log or in call maker nodejs app.
Although mining works fine at gasPrice 1e9.
Any idea why mining at 1 Wei gets blocked when all the nodes have the given flag set already?

Thanks community.

**Comment by karalabe** [comment]
You mean `--miner.gasprice`?
