### ISSUE TITLE
personal_sendTransaction

### ISSUE THREAD

**Issue by aghamir** [ethereum/go-ethereum#21440]
Dear devs,

#### System information

Geth version: `1.9.18-stable`
OS & Version: Linux
Commit hash : f5382591874220287de253bfc08b10afd5244927

When I using personal_sendTransaction and send contract like bellow:
```
data = '0xa9059cbb' + wallet_to.zfill(64) + value.zfill(64)
params = [{
            'from': wallet_from,
            'to': self.contract_address,
            'data': data,
            'gas': '0x11170'
        }, geth.password]
response = geth.request(
                'personal_sendTransaction',
                params,
                rpc_id
            )
```
the SSTORE operation consumes 20000 gas cost. Like bellow link(Row 524):
https://etherscan.io/vmtrace?txhash=0x692b449682c49b61fe57d51ec8f1e0da479592744e0837d0821588bd2b3dcf35#raw

You can compare it with other transfer call which use 5000 gas(Row 524):
https://etherscan.io/vmtrace?txhash=0x7257fb6bb5bdafdb36ae2638eb11accb73ac4048231873fe38590b7527c20d9d

Here is my question. How can I change personal_sendTransaction parameters to use 5000 gas instead of 20000? Is there any way to reduce this SSTORE.

P.S.: I created the smart contract transfer call with web3 and it used 5000 gas too.

**Comment by ligi** [comment]
AFAIR it depends on the previous value. 
If the previous value is 0 -> it costs 20000
if the previous value is anything else -> it costs 5000
