### ISSUE TITLE
TOML config for GraphQL broken?

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#21443]
I just updated my Geth docker, using the same config file as before and now I get this:

```
INFO [08-13|15:57:50.958] Starting Geth on Görli testnet...
Fatal: /data/config/geth.toml, line 141: field 'GraphQLHost' is not defined in node.Config, see https://godoc.org/github.com/ethereum/go-ethereum/node#Config for available fields
```

If I go to the address listed and search "GraphQL" I only see `DefaultGraphQLHost`, I thought maybe this config flag just changed its name so I tried that and I get:

```
Fatal: /data/config/geth.toml, line 143: field 'DefaultGraphQLPort' is not defined in node.Config, see https://godoc.org/github.com/ethereum/go-ethereum/node#Config for available fields
```

I tested with `latest` and `stable` same thing.

So, it looks like the latest release broke that flag?

Default config dump is:
```
[Node]
DataDir = "/root/.ethereum"
IPCPath = "geth.ipc"
HTTPHost = ""
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth"]
WSHost = ""
WSPort = 8546
WSModules = ["net", "web3", "eth"]
GraphQLVirtualHosts = ["localhost"]
```

Same thing for the `GraphQLPort`

**Comment by karalabe** [comment]
Sigh. Yeah, it's broken. GraphQL was merged on top of HTTP, it's a single endpoint from now on. Just drop those two and if you use GraphQL, use the HTTP RPC endpoint.

**Comment by MysticRyuujin** [comment]
Easy peasy. Might be worth a note on the release page. No worries here.

**Comment by karalabe** [comment]
Sorry about that, should have mentioned it indeed.

**Comment by karalabe** [comment]
Added a note to the release page https://github.com/ethereum/go-ethereum/releases/tag/v1.9.19

**Comment by clouds56** [comment]
Shall we have `--graphql` switch in config.toml? Now it seems we have to config it via cmd line.
