### ISSUE TITLE
Web sockets seems to have moved from /ws to / on latest upgrade

### ISSUE THREAD

**Issue by credfeto** [ethereum/go-ethereum#21441]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: 
```ubuntu@ip-172-31-4-241:~$ geth version
Geth
Version: 1.9.19-stable
Git Commit: 3e0641923d78bf1905e596a3a41a54277540bec7
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.2
Operating System: linux
GOPATH=
GOROOT=go
```

OS & Version: Linux
Commit hash : n/a

#### Expected behaviour
To be able to connect to web sockets still to be ``ws://host:port/ws``

#### Actual behaviour

Web sockets now appear at:

``ws://host:port``

#### Steps to reproduce the behaviour

Upgrade a working geth on previous release version with command line:

```geth --port 30304 --http --http.port=8545 --http.addr=0.0.0.0 --http.api=eth,net,web3,debug --http.corsdomain="*" --http.vhosts=examplecom --nodiscover --graphql --graphql.corsdomain="*" --graphql.vhosts=example.com --networkid 1234 --ws --ws.port=8546 --ws.addr=0.0.0.0 --ws.origins="*" -ws.api=eth,net,web3,debug --verbosity 3 --identity test-node```

* note had to change the graphql so its on the same port as http, but didn't see any corresponding requested change for web sockets.

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Websockets were always supposed to be on the root. Perhaps previously it didn't care about the path and answered on all of them and now someone fixed it so it only answers on root?

**Comment by renaynay** [comment]
Yeah I checked it out and previous version allowed any path (not just `/ws`) which shouldn't be the case. #21105 refactored the way http servers work, so this likely solved the issue.

**Comment by renaynay** [comment]
Closing this issue as the described behavior was unexpected and has now been fixed.
