### ISSUE TITLE
Always Synchronisation failed, dropping peer

### ISSUE THREAD

**Issue by prettyCoders** [ethereum/go-ethereum#21463]
![图片](https://user-images.githubusercontent.com/36216120/90618573-c8a1fe80-e242-11ea-9d36-742a6799efe0.png)

**Comment by karalabe** [comment]
Your logs print that it takes 8s to import a couple of blocks. That's way too much. Do you have an SSD?

**Comment by OliverBui** [comment]
Hello all,
My Light Node [1.9.19-stable] have error `No suitable peers available`. and always drop peerspeers
Please help me check my Node.
Thanks so much

**Comment by rjl493456442** [comment]
@OliverBui it's totally different. You are running the light client which requires the LES servers for offering data.
Nowaday there are not enough LES servers in the network, so it's a little struggling to find them in the mainnet.

**Comment by sidhujag** [comment]
@rjl493456442 for our network we are running many LES clients there are around 2000 or more, and they are paid to be online through our consensus. Is there a way to add peers to startup and increase the num peers so it ends up finding them in a way where if atleast a few of the hundreds or thousands of nodes get connected to LES servers then they will end up all syncing together? In other words perhaps randomly picking a handful of nodes and saying here try these they are secure and if a few of them aren't we will know and disconnect those anyways.
