### ISSUE TITLE
Rename RPC tx property name input -> data

### ISSUE THREAD

**Issue by wanderer** [ethereum/go-ethereum#2148]
Hi, can we rename tx property `input` to `data`? This is what the yellow paper calls it.

**Comment by wanderer** [comment]
related https://github.com/ethereumjs/ethereumjs-tx/issues/7

**Comment by karalabe** [comment]
I don't think that's a viable possibility. The API is "standardized" across all clients and confirms to the [JSON-RPC sped](https://github.com/ethereum/wiki/wiki/JSON-RPC). Renaming the field would instantly break all code depending on the specific field. I don't see this happening any time soon to be honest.

Further, [data isn't that good of a name actually](http://archive.oreilly.com/pub/post/the_worlds_two_worst_variable.html). Input makes it imho much clearer that it's the input blob provided to the transaction. Data would lose that semantic.

**Comment by wanderer** [comment]
well i'll deal with it then
