### ISSUE TITLE
cmd/geth: set log verbosity through config file

### ISSUE THREAD

**Issue by JiashengRen** [ethereum/go-ethereum#21492]
I want to modify geth Log level by config files, not cmd .
is there some ways to solve ?
Please help me ~
Thanks

**Comment by holiman** [comment]
Unfortunately not.. 
```
[user@work bin]$ ./geth --vmodule=eth/*=5,p2p=4 --verbosity 5 dumpconfig > conf1.toml
[user@work bin]$ ./geth dumpconfig > conf2.toml
[user@work bin]$ diff conf1.toml conf2.toml 
```
So it appears we haven't enabled logging options via toml.

**Comment by JiashengRen** [comment]
> Unfortunately not..
> 
> ```
> [user@work bin]$ ./geth --vmodule=eth/*=5,p2p=4 --verbosity 5 dumpconfig > conf1.toml
> [user@work bin]$ ./geth dumpconfig > conf2.toml
> [user@work bin]$ diff conf1.toml conf2.toml 
> ```
> 
> So it appears we haven't enabled logging options via toml.

thanks for your help!!!

**Comment by fjl** [comment]
If anyone ever wants this feature, it should be pretty easy to implement.

**Comment by sunset1234321** [comment]
but seems on the geth implemented by bsc,  they done it already,  

https://github.com/binance-chain/bsc/releases/download/v1.1.7/mainnet.zip     their config toml set the log to a log file
