### ISSUE TITLE
Rinkeby faucet transactions not going through 

### ISSUE THREAD

**Issue by jendaa** [ethereum/go-ethereum#21499]
Hi there,

[Rinkeby faucet ](https://www.rinkeby.io/#faucet) does not seem to work. I submitted a request with address [0x7bd8666e0e56628d47a1301df3272016d1d48246](https://rinkeby.etherscan.io/address/0x7bd8666e0e56628d47a1301df3272016d1d48246). The address got successfully listed on the faucet page, but there is no transaction on the etherscan. I also checked other addresses listed on the page and it seems none of them got any ethers.

Jan

**Comment by sseongha11** [comment]
I have the same issue with the address (0xEf5A68E79Aa45f0E127796F72765618998708a04). If possible, please send some ETH for my dapp development (address: 0xEf5A68E79Aa45f0E127796F72765618998708a04) on Rinkeby network.

**Comment by karalabe** [comment]
Seems to be working now, closing.
