### ISSUE TITLE
transaction_pool.go : RemoveTx  - inefficient remove algorithm

### ISSUE THREAD

**Issue by pnomarev** [ethereum/go-ethereum#2149]
I'm testing a higher than usual load of transactions, and discovered a bottleneck in the RemoveTx function. It simply traverses all accounts in the queue
for address, txs := range pool.queue {
}
and removes the hash when found. The performance of this algorithm is really bad when there 50 account and 20k-50k transactions, and it's getting worse exponentially with increase of transactions/addresses.

Please consider rewriting this function using some kind of reverse map hash->address and access the required address directly without scanning the whole queue.

**Comment by obscuren** [comment]
Thanks. We are aware that the transaction pool needs some attention and optimisation. Thus far it hasn't been necessary considering the amount of transaction relayed on the network at present.

A change will likely hit after homestead.

**Comment by fjl** [comment]
Fix released in 1.5.0.
