### ISSUE TITLE
Scalability 

### ISSUE THREAD

**Issue by mmitech** [ethereum/go-ethereum#2150]
Not sure where I need to ask this question, but please bear with me, now that the scalability topic is a hot topic, I had to research Ethereum especially that everybody is calling it the next big thing and I came across this in the wiki: 
 _"Ethereum is likely to suffer a similar growth pattern, worsened by the fact that there will be many applications on top of the Ethereum blockchain instead of just a currency as is the case with Bitcoin, but ameliorated by the fact that Ethereum full nodes need to store just the state instead of the entire blockchain history"_

So what does the last sentence technically means, and how will Ethereum perform now at this state if we get 10 times the amount of transactions that Bitcoin have today ?

**Comment by karalabe** [comment]
I'm going to close this issue as it's not really tied to the Go implementation (or any specific implementation) in particular, rather a philosophical and high level question. Please reach out to the [Research Gitter](https://gitter.im/ethereum/research) room for discussion about these kinds of topics :)
