### ISSUE TITLE
http://127.0.0.1:6060/debug/metrics  how  can i find some  paper  to know this metrics means

### ISSUE THREAD

**Issue by stivenMirinda** [ethereum/go-ethereum#21510]
"rpc/duration/admin_addPeer/success.max": 0,
"rpc/duration/admin_addPeer/success.mean": 0,
"rpc/duration/admin_addPeer/success.mean-rate": 2.527424091986247e-05,
"rpc/duration/admin_addPeer/success.min": 0,
"rpc/duration/admin_addPeer/success.one-minute": 9.406445676423601e-284,
"rpc/duration/admin_addPeer/success.std-dev": 0,
"rpc/duration/admin_datadir/success.50-percentile": 0,
"rpc/duration/admin_datadir/success.75-percentile": 0,
"rpc/duration/admin_datadir/success.95-percentile": 0,
"rpc/duration/admin_datadir/success.99-percentile": 0,
"rpc/duration/admin_datadir/success.999-percentile": 0,
"rpc/duration/admin_datadir/success.count": 1,
"rpc/duration/admin_datadir/success.fifteen-minute": 2.997622585516834e-20,
"rpc/duration/admin_datadir/success.five-minute": 6.733965166107096e-58,
"rpc/duration/admin_datadir/success.max": 0,
"rpc/duration/admin_datadir/success.mean": 0,
"rpc/duration/admin_datadir/success.mean-rate": 1.2636788803234757e-05,
"rpc/duration/admin_datadir/success.min": 0,
"rpc/duration/admin_datadir/success.one-minute": 8.654347806107682e-284,
"rpc/duration/admin_datadir/success.std-dev": 0,
"rpc/duration/admin_peers/success.50-percentile": 984400,
"rpc/duration/admin_peers/success.75-percentile": 1.79903e+07,
"rpc/duration/admin_peers/success.95-percentile": 1.79903e+07,
"rpc/duration/admin_peers/success.99-percentile": 1.79903e+07,
"rpc/duration/admin_peers/success.999-percentile": 1.79903e+07,
"rpc/duration/admin_peers/success.count": 3,
"rpc/duration/admin_peers/success.fifteen-minute": 2.575058777666075e-09,
"rpc/duration/admin_peers/success.five-minute": 4.149263959151528e-20,
"rpc/duration/admin_peers/success.max": 1.79903e+07,
"rpc/duration/admin_peers/success.mean": 6.3249e+06,
"rpc/duration/admin_peers/success.mean-rate": 3.79144584673542e-05,
"rpc/duration/admin_peers/success.min": 0,
"rpc/duration/admin_peers/success.one-minute": 4.982081937280252e-87,
"rpc/duration/admin_peers/success.std-dev": 8.258467521681408e+06,
"rpc/duration/all.50-percentile": 0,
"rpc/duration/all.75-percentile": 0,
"rpc/duration/all.95-percentile": 1.002065e+06,
"rpc/duration/all.99-percentile": 7.706587000000036e+06,
"rpc/duration/all.999-percentile": 1.0607138240000011e+08,
"rpc/duration/all.count": 38053,
"rpc/duration/all.fifteen-minute": 0.7834151019108535,
"rpc/duration/all.five-minute": 0.4085552840963308,
"rpc/duration/all.max": 1.069708e+08,
"rpc/duration/all.mean": 554382.1984435797,
"rpc/duration/all.mean-rate": 0.4808617423961051,
"rpc/duration/all.min": 0,
"rpc/duration/all.one-minute": 0.023751913100862634,
"rpc/duration/all.std-dev": 4.719460496103794e+06,
"rpc/duration/eth_accounts/success.50-percentile": 0,
"rpc/duration/eth_accounts/success.75-percentile": 0,
"rpc/duration/eth_accounts/success.95-percentile": 999355,
"rpc/duration/eth_accounts/success.99-percentile": 2.998042e+06,
"rpc/duration/eth_accounts/success.999-percentile": 8.118391210000023e+07,
"rpc/duration/eth_accounts/success.count": 3715,
"rpc/duration/eth_accounts/success.fifteen-minute": 0.09782924742051319,
"rpc/duration/eth_accounts/success.five-minute": 0.07441996837457049,
"rpc/duration/eth_accounts/success.max": 8.29519e+07,
"rpc/duration/eth_accounts/success.mean": 211170.23346303502,
"rpc/duration/eth_accounts/success.mean-rate": 0.04694610796930469,
"rpc/duration/eth_accounts/success.min": 0,
"rpc/duration/eth_accounts/success.one-minute": 0.0018937793896533783,
"rpc/duration/eth_accounts/success.std-dev": 2.7577185327097685e+06,
"rpc/duration/eth_blockNumber/success.50-percentile": 0,
"rpc/duration/eth_blockNumber/success.75-percentile": 0,
"rpc/duration/eth_blockNumber/success.95-percentile": 0,
"rpc/duration/eth_blockNumber/success.99-percentile": 1e+06,
"rpc/duration/eth_blockNumber/success.999-percentile": 1.581418990000002e+07,
"rpc/duration/eth_blockNumber/success.count": 3053,
"rpc/duration/eth_blockNumber/success.fifteen-minute": 0.03245133830135888,
"rpc/duration/eth_blockNumber/success.five-minute": 0.00018509288291398117,
"rpc/duration/eth_blockNumber/success.max": 1.59881e+07,
"rpc/duration/eth_blockNumber/success.mean": 57351.459143968874,
"rpc/duration/eth_blockNumber/success.mean-rate": 0.03858011475466449,
"rpc/duration/eth_blockNumber/success.min": 0,
"rpc/duration/eth_blockNumber/success.one-minute": 3.768730067075593e-18,
"rpc/duration/eth_blockNumber/success.std-dev": 627656.6788970056,
"rpc/duration/eth_coinbase/success.50-percentile": 6.9966e+06,
"rpc/duration/eth_coinbase/success.75-percentile": 6.9966e+06,
"rpc/duration/eth_coinbase/success.95-percentile": 6.9966e+06,
"rpc/duration/eth_coinbase/success.99-percentile": 6.9966e+06,
"rpc/duration/eth_coinbase/success.999-percentile": 6.9966e+06,
"rpc/duration/eth_coinbase/success.count": 1,
"rpc/duration/eth_coinbase/success.fifteen-minute": 2.997622585516834e-20,
"rpc/duration/eth_coinbase/success.five-minute": 6.733965166107096e-58,
"rpc/duration/eth_coinbase/success.max": 6.9966e+06,
"rpc/duration/eth_coinbase/success.mean": 6.9966e+06,
"rpc/duration/eth_coinbase/success.mean-rate": 1.2636788324488859e-05,
"rpc/duration/eth_coinbase/success.min": 6.9966e+06,
"rpc/duration/eth_coinbase/success.one-minute": 8.654347806107682e-284,
"rpc/duration/eth_coinbase/success.std-dev": 0,
"rpc/duration/eth_estimateGas/success.50-percentile": 2.9991e+06,
"rpc/duration/eth_estimateGas/success.75-percentile": 4.389675e+06,
"rpc/duration/eth_estimateGas/success.95-percentile": 1.199298e+07,
"rpc/duration/eth_estimateGas/success.99-percentile": 5.186066700000002e+07,
"rpc/duration/eth_estimateGas/success.9

**Comment by MariusVanDerWijden** [comment]
Hey @stivenMirinda thanks for the suggestion, currently there is no documentation about the metrics.
This is the only thing close to it,  but it doesnt explain any of the metrics: https://github.com/ethereum/go-ethereum/wiki/Metrics-and-Monitoring
I will write some documentation in the coming days and ping you here once it's done.

**Comment by MariusVanDerWijden** [comment]
I've added an explanation of the most commonly used metrics on the docu page: https://geth.ethereum.org/docs/interface/metrics
Explanation of the other metrics can only be found by looking through the code for them. 
They do change sometimes so I don't think it makes sense to document all of them.
