### ISSUE TITLE
Geth 1.9.20 regularly causes ssh sessions to freeze (1.9.19 doesn't)

### ISSUE THREAD

**Issue by kilrau** [ethereum/go-ethereum#21516]
I am running geth locally on two different amd64 ubuntu 20.04 server machines with the [official docker image](https://hub.docker.com/layers/ethereum/client-go/v1.9.20/images/sha256-c78326a2ef4b37e05e75949b07fb655d5afde48d90a803abb9b6bb64379c823b?context=explore) and noticed that since the upgrade to 1.9.20, ssh sessions to this host machine regularly freeze. Sometimes for a minute, sometimes forever and I have to kill the ssh session. A ssh session also freezes if I have a second ssh session open in parallel works just fine.

No CPU spikes out of the usual, no RAM or disk/IO spikes neither, nothing out of the usual in the logs neither

If I stop geth, the freezes are gone and SSH works just like normal. `1.9.19`, which I ran for the full two weeks the release was out until I switched to `1.9.20` didn't show this behavior, nor any version before. I am fairly certain some change from 1.9.19 to 1.9.20 caused this.

#### System information

Geth version: `1.9.20`
OS & Version: Ubuntu 20.04 LTS Server
Commit hash : (if `develop`)

#### Expected behaviour
SSH sessions work and are not affected by geth

#### Actual behaviour
SSH sessions regularly freeze evidently caused by geth

#### Steps to reproduce the behaviour
Run geth for some hours on above described system.

**Comment by karalabe** [comment]
Could you double check your disk usage? Perhaps Geth is compacting the database, which saturates your capacity up to the point that other processes are starving?

**Comment by gballet** [comment]
since it's local, could you also check the networking load and if `geth` is able to sync while this happens? Also, are other networking services halted or is it just ssh?

**Comment by kilrau** [comment]
I did and its not disk, nor network, just one SSH session freezing while another ssh session open in parallel works just fine. Didn't experience it with 1.9.21 yet. Will close if it doesn't appear again with 1.9.21 in the next couple of days.

**Comment by kilrau** [comment]
Doesn't reproduce with `1.9.21`. Closing.

**Comment by kilrau** [comment]
I was wrong, reproduces `1.9.20` -> `1.9.23`.

**Comment by kilrau** [comment]
I triple checked, the SSD geth is running on is not heavily used and geth is not in inital sync.

**Comment by holiman** [comment]
When this happens, could you try checking how many file handles geth holds? `lsof $(pidof geth) | wc -l`
