### ISSUE TITLE
Any suggestion how to reduce the uncle rate?

### ISSUE THREAD

**Issue by rlinxy** [ethereum/go-ethereum#21523]
Hi there,

Our uncle rate is around 10%, much higher than the overall average 5%.
The main mining node is running on a VM with 8C 32G RAM, 1T Local SSD with 147510 IOPS, 10M bandwidth.
We have several synced nodes running all over the world connecting to the main node as static nodes. Most of them are running on VM with 2C 8G, but just 'cloud disk', a little better than HDD though.

The Geth is the newest version 1.9.20. Command line I use is:
./geth --datadir "dir-to-localSSD" --ethash.dagdir "dir-to-localSSD"  --syncmode "fast" --cache=16384 --mine --miner.threads 0 --http -http.addr 0.0.0.0 -http.port xxxx --http.api eth,web3,personal,net --maxpeers 80 -miner.etherbase "0x1234567890" --miner.recommit 6s --miner.extradata "ABC"

We have been working on this for months, but, really frustrated, no much progress for now. 
I know issues here are mostly for bugs, but I got no answer somewhere else such as Discord. 

Please share some experience, thanks in advance.

**Comment by karalabe** [comment]
Maybe @peterbitfly could help how to reduce uncles based on his experience.

If you are running remote miners, you could try running Geth with `--miner.noverify`. Originally external miners submitted possible solutions to Geth, which double checked them before pushing to the network. If you feel confident your miner nodes produce good PoWs, you can tell Geth to skip double checking .This can shave off some milliseconds from network propagation.

**Comment by rlinxy** [comment]
> Maybe @peterbitfly could help how to reduce uncles based on his experience.
> 
> If you are running remote miners, you could try running Geth with `--miner.noverify`. Originally external miners submitted possible solutions to Geth, which double checked them before pushing to the network. If you feel confident your miner nodes produce good PoWs, you can tell Geth to skip double checking .This can shave off some milliseconds from network propagation.

Thanks! I will add this parameter.
Any other suggestions will be appreciated :)

**Comment by rlinxy** [comment]
According to this
[https://www.reddit.com/r/ethereum/comments/7l0tsy/information_for_miners_on_how_to_improve_their/](url)
Parity users may set --tx-queue-gas 70000000 to improve the performance, I am wondering if Geth has the similar  parameter?
I just went through the command line options of Geth, should I set the miner.gaslimit to some lower value?
[https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options](url)

**Comment by holiman** [comment]
We don't really have any good further tips. Changing the `miner.gasLimit` should not affect uncle rate.
