### ISSUE TITLE
rpc: consider supporting HTTP in Client.Subscribe

### ISSUE THREAD

**Issue by mvdan** [ethereum/go-ethereum#21522]
https://github.com/ethereum/go-ethereum/blob/f86324edb7897b539cd44ce9710095d570e27699/rpc/client.go#L443-L445

HTTP server-sent events could be used to support subscribing to events over HTTP, aside from other protocols like Websockets.

An intro: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events
A Go example: https://thoughtbot.com/blog/writing-a-server-sent-events-server-in-go

Note that server-sent events with HTTP1 are unidirectional; only the server can send data to the client. I think that should be fine for this use case, but if a bidirectional connection is needed, we could always rely on HTTP2. See https://www.infoq.com/articles/websocket-and-http2-coexist/

I'm opening this issue to see if this would be a useful feature that would be wanted in the future. The current `ErrNotificationsUnsupported` makes me wonder if it's not supported by design.

**Comment by holiman** [comment]
Implementing http2 to get this feature sounds like it would be a pretty large task, and from a UX perspective, it wouldn't bring anything new -- everything described can already be achieved via websockets. Unless I'm missing something?

**Comment by fjl** [comment]
I also think that WebSocket and HTTP/2 fulfill different needs. WebSocket gives you a bi-directional data stream on which anything can be sent. It is possible to send multiple requests on the same connection with HTTP/2 (as with HTTP/1.1), and Server-Sent Events can be used to relay real-time data to the client, but it's not the same thing as WebSocket. Given that WebSocket works everywhere nowadays, including in browsers, I think there is no need for us to try and create an alternative to it.

**Comment by p4u** [comment]
Well, the first reason is that HTTP endpoints are quite more common than Websockets on the real world. The second is, from the API consumer perspective, it's a bit weird a RPC client that accept both (WS and HTTP) but some calls only work in one case.

I think supporting HTTP2 and event subscription would make things easier and less complex in the future. In my opinion Websockets will eventually become obsoleted.

But sure, it does not seems like an urgent feature to add. I cannot evaluate (yet) if it's a hard work or not. In any case, would a PR on this issue be accepted?

**Comment by mvdan** [comment]
To clarify, I don't think websockets will get entirely obsoleted by http2, but for simple use cases like sending events to a client, I think they will be replaced for the reasons @p4u mentions - consistency and simplicity.

**Comment by p4u** [comment]
Well, not obsoleted by meaning that it will disappear from browsers or servers. But with the time I think HTTP2 will be more used and will probably become the default way to create bidirectional connections on the Web ecosystem.

**Comment by holiman** [comment]
>  In any case, would a PR on this issue be accepted?

Hard to say - that always depends on the quality of the PR, and how wide-ranging the effects of it is. If it touches a lot of core components or refactors the entire rpc package, the chances are pretty slim. If it's more of a standalone shim, chances increase. 

We'll definitely review it if it comes in.
