### ISSUE TITLE
question about fast downloading block data

### ISSUE THREAD

**Issue by puffanddmx** [ethereum/go-ethereum#21533]
hi
Receiving block data from scratch takes a long time for the geth running. So, is there a site that uploads the latest block data daily in the form of a zip file?

**Comment by begetan** [comment]
The idea of a blockchain is a ability to not trust to everyone, thus initial synchronization is required and recommended.  I would not relay on any kind of a public available snapshot for security reason, but it is quite normal run snapshot system in a restricted private environment. It is quiet easy to upload just block-chain data folder from a synced node to AWS S3 bucket, for example, and spin up new nodes with initial download from this bucket.

**Comment by puffanddmx** [comment]
thanks!
