### ISSUE TITLE
Expired PGP keys on the download page

### ISSUE THREAD

**Issue by begetan** [ethereum/go-ethereum#21539]
I am using automate image builder for deploy new version of Geth. I found that some GPG keys mentioned in the [download page](https://geth.ethereum.org/downloads/) have been expired for a long time.

```
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9BA28146 E058A81C 85BE4B0C 05A5DDF0 2F295D12 1CCB7DD2 99E23788
Executing: /tmp/apt-key-gpghome.KB5CfCrjgI/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 9BA28146 E058A81C 85BE4B0C 05A5DDF0 2F295D12 1CCB7DD2 99E23788
gpg: key 5219CDE299E23788: public key "Viktor Tron <viktor@ethereum.org>" imported
gpg: key 119A76381CCB7DD2: public key "Péter Szilágyi <peter@ethereum.org>" imported
gpg: key 6D9649932F295D12: public key "Nick Johnson <nick@ethereum.org>" imported
gpg: key 683B438C05A5DDF0: public key "Martin Holst Swende <martin@swende.se>" imported
gpg: key A6766F7185BE4B0C: public key "Jeffrey Wilcke <jeffrey@ethereum.org>" imported
gpg: key 337E68FCE058A81C: public key "Felix Lange <fjl@twurst.com>" imported
gpg: key A61A13569BA28146: public key "Go Ethereum Linux Builder <geth-ci@ethereum.org>" imported
gpg: Total number processed: 7
gpg:               imported: 7
```

```
gpg -k 5219CDE299E23788
pub   rsa2048 2016-10-10 [SCEA] [expired: 2017-01-08]
      446D939E45C0DC1E2A8E2F625219CDE299E23788
uid           [ expired] Viktor Tron <viktor@ethereum.org>
```

```
gpg -k 337E68FCE058A81C
pub   rsa4096 2016-08-09 [SC] [expired: 2019-12-11]
      60470B715865392DE43D75A3337E68FCE058A81C
uid           [ expired] Felix Lange <fjl@twurst.com>
uid           [ expired] Felix Lange <fjl@ethereum.org>
```

Should any personal keys be removed from the download page at all, because there is only the builder key 
signs a build for the specific platform?  I see no reason to keep the personal keys, especially expired.

Here is the very noisy log for the verification with the personal keys:

```
amazon-ebs: ==> Install Geth binary
==> amazon-ebs: gpg: directory '/root/.gnupg' created
==> amazon-ebs: gpg: keybox '/root/.gnupg/pubring.kbx' created
==> amazon-ebs: gpg: key 5219CDE299E23788: 1 signature not checked due to a missing key
==> amazon-ebs: gpg: /root/.gnupg/trustdb.gpg: trustdb created
==> amazon-ebs: gpg: key 5219CDE299E23788: public key "Viktor Tron <viktor@ethereum.org>" imported
==> amazon-ebs: gpg: key 119A76381CCB7DD2: 2 signatures not checked due to missing keys
==> amazon-ebs: gpg: key 119A76381CCB7DD2: public key "Péter Szilágyi <peter@ethereum.org>" imported
==> amazon-ebs: gpg: key 6D9649932F295D12: 1 signature not checked due to a missing key
==> amazon-ebs: gpg: key 6D9649932F295D12: public key "Nick Johnson <nick@ethereum.org>" imported
==> amazon-ebs: gpg: key 683B438C05A5DDF0: 4 signatures not checked due to missing keys
==> amazon-ebs: gpg: key 683B438C05A5DDF0: public key "Martin Holst Swende <martin@swende.se>" imported
==> amazon-ebs: gpg: key A6766F7185BE4B0C: 13 signatures not checked due to missing keys
==> amazon-ebs: gpg: key A6766F7185BE4B0C: public key "Jeffrey Wilcke <jeffrey@ethereum.org>" imported
==> amazon-ebs: gpg: key 337E68FCE058A81C: 2 signatures not checked due to missing keys
==> amazon-ebs: gpg: key 337E68FCE058A81C: public key "Felix Lange <fjl@twurst.com>" imported
==> amazon-ebs: gpg: key A61A13569BA28146: 1 signature not checked due to a missing key
==> amazon-ebs: gpg: key A61A13569BA28146: public key "Go Ethereum Linux Builder <geth-ci@ethereum.org>" imported
==> amazon-ebs: gpg: no ultimately trusted keys found
==> amazon-ebs: gpg: Total number processed: 7
==> amazon-ebs: gpg:               imported: 7
==> amazon-ebs: gpg: assuming signed data in '/tmp/geth-linux-amd64-1.9.21-0287d548.tar.gz'
==> amazon-ebs: gpg: Signature made Wed Sep  9 09:09:33 2020 UTC
==> amazon-ebs: gpg:                using RSA key A61A13569BA28146
==> amazon-ebs: gpg: Good signature from "Go Ethereum Linux Builder <geth-ci@ethereum.org>" [unknown]
==> amazon-ebs: gpg: WARNING: This key is not certified with a trusted signature!
==> amazon-ebs: gpg:          There is no indication that the signature belongs to the owner.
==> amazon-ebs: Primary key fingerprint: FDE5 A1A0 44FA 13D2 F7AD  A019 A61A 1356 9BA2 8146
```

**Comment by holiman** [comment]
> Should any personal keys be removed from the download page at all, because there is only the builder key
signs a build for the specific platform? I see no reason to keep the personal keys, especially expired.

Good question. So the personal keys can be used for 

- verifying (old) commits, 
- verifying any out-of-band releases, if we ever should need to do a critical release but are having problems with our automated build-pipeline. 

However, there are several keys that are currently not used, like Jeff, Victor and Nick. If we still want them public for commit-verification, then we should move them to some other place, like "Old developer keys". Otherwise, we should just delete them. 

And @fjl I guess you need to create a new expiration date?

**Comment by fjl** [comment]
Yes, will update my key!

**Comment by fjl** [comment]
Agree about removing Jeff's, Victor's and Nick's keys.

**Comment by ligi** [comment]
@holiman deleted the keys - and @fjl will update his key - closing the issue - thanks for reporting!

**Comment by boy1bot2** [comment]
> I am using automate image builder for deploy new version of Geth. I found that some GPG keys mentioned in the [download page](https://geth.ethereum.org/downloads/) have been expired for a long time.
> 
> ```
> apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9BA28146 E058A81C 85BE4B0C 05A5DDF0 2F295D12 1CCB7DD2 99E23788
> Executing: /tmp/apt-key-gpghome.KB5CfCrjgI/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 9BA28146 E058A81C 85BE4B0C 05A5DDF0 2F295D12 1CCB7DD2 99E23788
> gpg: key 5219CDE299E23788: public key "Viktor Tron <viktor@ethereum.org>" imported
> gpg: key 119A76381CCB7DD2: public key "Péter Szilágyi <peter@ethereum.org>" imported
> gpg: key 6D9649932F295D12: public key "Nick Johnson <nick@ethereum.org>" imported
> gpg: key 683B438C05A5DDF0: public key "Martin Holst Swende <martin@swende.se>" imported
> gpg: key A6766F7185BE4B0C: public key "Jeffrey Wilcke <jeffrey@ethereum.org>" imported
> gpg: key 337E68FCE058A81C: public key "Felix Lange <fjl@twurst.com>" imported
> gpg: key A61A13569BA28146: public key "Go Ethereum Linux Builder <geth-ci@ethereum.org>" imported
> gpg: Total number processed: 7
> gpg:               imported: 7
> ```
> 
>  ```
> gpg -k 5219CDE299E23788
> pub   rsa2048 2016-10-10 [SCEA] [expired: 2017-01-08]
>       446D939E45C0DC1E2A8E2F625219CDE299E23788
> uid           [ expired] Viktor Tron <viktor@ethereum.org>
> ```
> 
>  ```
> gpg -k 337E68FCE058A81C
> pub   rsa4096 2016-08-09 [SC] [expired: 2019-12-11]
>       60470B715865392DE43D75A3337E68FCE058A81C
> uid           [ expired] Felix Lange <fjl@twurst.com>
> uid           [ expired] Felix Lange <fjl@ethereum.org>
> ```
> 
> Should any personal keys be removed from the download page at all, because there is only the builder key signs a build for the specific platform? I see no reason to keep the personal keys, especially expired.
> 
> Here is the very noisy log for the verification with the personal keys:
> 
> ```
> amazon-ebs: ==> Install Geth binary
> ==> amazon-ebs: gpg: directory '/root/.gnupg' created
> ==> amazon-ebs: gpg: keybox '/root/.gnupg/pubring.kbx' created
> ==> amazon-ebs: gpg: key 5219CDE299E23788: 1 signature not checked due to a missing key
> ==> amazon-ebs: gpg: /root/.gnupg/trustdb.gpg: trustdb created
> ==> amazon-ebs: gpg: key 5219CDE299E23788: public key "Viktor Tron <viktor@ethereum.org>" imported
> ==> amazon-ebs: gpg: key 119A76381CCB7DD2: 2 signatures not checked due to missing keys
> ==> amazon-ebs: gpg: key 119A76381CCB7DD2: public key "Péter Szilágyi <peter@ethereum.org>" imported
> ==> amazon-ebs: gpg: key 6D9649932F295D12: 1 signature not checked due to a missing key
> ==> amazon-ebs: gpg: key 6D9649932F295D12: public key "Nick Johnson <nick@ethereum.org>" imported
> ==> amazon-ebs: gpg: key 683B438C05A5DDF0: 4 signatures not checked due to missing keys
> ==> amazon-ebs: gpg: key 683B438C05A5DDF0: public key "Martin Holst Swende <martin@swende.se>" imported
> ==> amazon-ebs: gpg: key A6766F7185BE4B0C: 13 signatures not checked due to missing keys
> ==> amazon-ebs: gpg: key A6766F7185BE4B0C: public key "Jeffrey Wilcke <jeffrey@ethereum.org>" imported
> ==> amazon-ebs: gpg: key 337E68FCE058A81C: 2 signatures not checked due to missing keys
> ==> amazon-ebs: gpg: key 337E68FCE058A81C: public key "Felix Lange <fjl@twurst.com>" imported
> ==> amazon-ebs: gpg: key A61A13569BA28146: 1 signature not checked due to a missing key
> ==> amazon-ebs: gpg: key A61A13569BA28146: public key "Go Ethereum Linux Builder <geth-ci@ethereum.org>" imported
> ==> amazon-ebs: gpg: no ultimately trusted keys found
> ==> amazon-ebs: gpg: Total number processed: 7
> ==> amazon-ebs: gpg:               imported: 7
> ==> amazon-ebs: gpg: assuming signed data in '/tmp/geth-linux-amd64-1.9.21-0287d548.tar.gz'
> ==> amazon-ebs: gpg: Signature made Wed Sep  9 09:09:33 2020 UTC
> ==> amazon-ebs: gpg:                using RSA key A61A13569BA28146
> ==> amazon-ebs: gpg: Good signature from "Go Ethereum Linux Builder <geth-ci@ethereum.org>" [unknown]
> ==> amazon-ebs: gpg: WARNING: This key is not certified with a trusted signature!
> ==> amazon-ebs: gpg:          There is no indication that the signature belongs to the owner.
> ==> amazon-ebs: Primary key fingerprint: FDE5 A1A0 44FA 13D2 F7AD  A019 A61A 1356 9BA2 8146
> ```

**Comment by boy1bot2** [comment]
**0xc1d78db0f5d00110935df8679a9b61da759f1e04**

**Comment by boy1bot2** [comment]
``

> [0xc1d78db0f5d00110935df8679a9b61da759f1e04](``)

`

**Comment by boy1bot2** [comment]
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCgAGBQJW4aZxAAoJELteLjW5Ljc+KEcP/RVSkj+dWnjIalN0cofdq98M
+BqJ5VYP3L/pp//SJiX4RM0E87WaQKK4TpwefaTnf3vYISDqsVwAWyLXUnAGOgjy
STbW/nhc1HRx+s9ayvqKuRrCItVhqZfmqhWpxGIq5xZSn5tBNaW0Kod3z/W7WT6z
O1bgC9f+7lf1b9QiCvdpX3o5KCxKDz+L6mSZhlGPXR1mqbD9Ugucv0H8w+Vb6pZg
uVs5v+5icV0wrkCx2nmSq15xv21Hz05GY4AJVpMuRqPgtcQ0j62VSGPzYDIyn1K6
hr7xByUv2r44WgP3fJqwxYlJkwdL6cQBaqMQp1UDt51xO5Ahaf/hF6oNkFrvhIAe
zelBolWS5YiyA6o/X0A46ma5tRNtsLmQfnXtzx3Ww9bIuvQBbWlveTPWsSgb051X
411Vt/pVd6R8q3yBB0umhAJG9qyZPM1o8UouLESI+6wjYi0TElfhi9bFD7Unm3sU
99x/Hb7oGPK8oWNbJSVBi5GIEjxeWwNPPAwBZI6GwYLqYQNlhJ+OHWCLXc/M4FvW
ObkMCHDoAqxmAjsfRM3nm+yvSwLOsNP1s4HmU91BektaPzJ4i/V0j+DV8gtRlagK
gEKiXsci9a/T8dkeNRoR8+SguErxIOneeeHOcuM8faIFKlFDv1Vg4XCTH0mN8CV0
PU4MWVh2bd7q1L4+Wxzy
=Dx4p
-----END PGP SIGNATURE-----
`

> 0xc1d78db0f5d00110935df8679a9b61da759f1e04

 `
