### ISSUE TITLE
Rinkeby Faucet Facebook URL parser

### ISSUE THREAD

**Issue by ricmoo** [ethereum/go-ethereum#21532]
I've found historic issues regarding the Rinkeby Faucet in this repository, and @karalabe suggested opening an issue to remind him to fix this.

The URL parser for Facebook Post URLs on the Authenticated Rinkeby Faucet does not correctly parse URLs if they end in a `/` or contains a query string.

Thanks! :)

**Comment by LieutenantRoger** [comment]
Hello, I made a pull request for this ticket, but the CI reported this error. 

`go: failed to remove work dir: remove C:\Users\appveyor\AppData\Local\Temp\1\go-build657629172\b479\geth.test.exe: Access is denied.`

It looks the privilege issue of the CI, please help.

**Comment by Jabrik07** [comment]
Pleace
https://www.facebook.com/jabrik.nggathelli0/x3D86B64895417aeCF5fe815482B41CE8bb2Cfb3c
