### ISSUE TITLE
field 'Shh' is not defined in main.gethConfig

### ISSUE THREAD

**Issue by gaia** [ethereum/go-ethereum#21542]
upgrade from the previous to the current version, started systemd, and

`config.toml, line 59: field 'Shh' is not defined in main.gethConfig`

removed the `Shh` section and it works.

is this behavior by default? I'll leave it as is now (working, no Shh)

**Comment by gballet** [comment]
This is indeed the new behavior as of 1.9.21, however it should not error out. I'll fix that.
