### ISSUE TITLE
race condition on ancientLimit

### ISSUE THREAD

**Issue by fxfactorial** [ethereum/go-ethereum#21557]
this is off latest HEAD as of now `4e2641319be2fd33a8cd61f0258456b7cef07957`

so was syncing and then sent signal to stop `CTRL-C`

and at downloader.go:617, a routine calls `.Cancel()`
but at download.go:569, another routine also calls `.Cancel()`, 

this causes a race condition on downloader.go:597 aka, two routines writing to `d.ancientLimit = 0`

not sure how important this is though - but it is wrong

**Comment by holiman** [comment]
We could/should probably remove that `d.ancientLimit = 0` in `Cancel` -- it seems it's not needed. @rjl493456442 do you agree?
