### ISSUE TITLE
The balance is sufficient but the transfer failed

### ISSUE THREAD

**Issue by emmeair** [ethereum/go-ethereum#21569]
````
Geth
Version: 1.9.22-unstable
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.14
Operating System: linux
GOPATH=
GOROOT=/usr/lib/golang

````
The block has been synchronized
I have an address with a balance of 0.011ETH
I want to transfer 0.001 ETH to another address
gasPrice is the value obtained using SuggestGasPrice: 18400001459 wei
gasLimit is 21000wei
I used rpc to call the SendTransaction method, and it returned sufficient funds for gas * price + value

If you use this formula: gas * price + value
There should be enough money to transfer successfully

This is my code:
````golang

func trans (){

	client, err := ethclient.Dial("http://127.0.0.1:8333")

	if err != nil {
		log.Fatal(err)
	}

	fromAddress := common.HexToAddress("XXXXXXXXX")

	nonce, err := client.PendingNonceAt(context.Background(), fromAddress)
	if err != nil {
		log.Fatal(err)
	}

	value := big.NewInt(10000)

	gasLimit := uint64(21000)

	gasPrice, err := client.SuggestGasPrice(context.Background())

	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(int64(gasLimit) * gasPrice.Int64() + value.Int64())

	toAddress := common.HexToAddress("XXXXXXX")

	tx := types.NewTransaction(nonce, toAddress, value, gasLimit, gasPrice, nil)

	chainID, err := client.NetworkID(context.Background())

	if err != nil {
		log.Fatal(err)
	}
	privateKey, err := crypto.HexToECDSA("XXXXXXXX")

	if err != nil {
		log.Fatal(err)
	}

	signedTx, err := types.SignTx(tx, types.NewEIP155Signer(chainID), privateKey)

	if err != nil {
		log.Fatal(err)
	}
	err = client.SendTransaction(context.Background(), signedTx)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Printf("tx sent: %s", signedTx.Hash().Hex())

}

````

**Comment by MariusVanDerWijden** [comment]
Hey @emmeair I tried to repro your issue but can't. Are you sure that the gas price oracle returns 18400001459. 18gwei seems like very little to me. Also you said that you want to send 0.001 ETH, but in the code you send `value := big.NewInt(10000)` which is 0.00000000000001 ETH. Check my repro here: 
https://github.com/MariusVanDerWijden/go-snippets/blob/master/geth-test/send_tx_test.go

**Comment by emmeair** [comment]
Hi everyone,@MariusVanDerWijden My attempt has been successful. I’m sorry I didn’t notify you at the first time. I suspect the problem is the address and key. Maybe I’m a novice. I used the address generated by `personal.newAccount()` at the time. It seems that the key is incorrect or For other reasons, there is no problem with my regenerated address transfer

```go
//The private key generated in this way is fine and can be transferred
privateKeyBytes := crypto.FromECDSA(privateKey)
    fmt.Println(hexutil.Encode(privateKeyBytes)[2:]) 
```
tranks
