### ISSUE TITLE
--wsorigins "*" throws CORS error

### ISSUE THREAD

**Issue by 7--** [ethereum/go-ethereum#21570]
`--wsorigins "*"` throws CORS error when I call geth from my browser in a local file. Tried running geth on same computer and different computer.

`geth --syncmode light  --ws --ws.api eth,net,web3 --wsorigins "*"`

![Screenshot from 2020-09-15 03-45-58](https://user-images.githubusercontent.com/4725003/93181121-10169000-f706-11ea-8e29-db291eaf3942.png)

I tried `--http.corsdomain '*'` and that works properly not throwing a CORS error.  
HTTP shows all domains allowed but WSS is blank:
![Screenshot from 2020-09-15 04-13-34](https://user-images.githubusercontent.com/4725003/93184111-de9fc380-f709-11ea-9440-b770e6fca4d4.png)

#### System information

Geth
Version: 1.9.14-stable
Git Commit: 6d74d1e5f762e06a6a739a42261886510f842778
Git Commit Date: 20200513
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.2
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.14.2.linux.amd64

#### Expected behaviour
No CORS errors

#### Actual behaviour
CORS error

#### Steps to reproduce the behaviour
Run geth with ws 

Run this html/js
```
<script type="text/javascript" src="./web3.min.js"></script>
   <script type="text/javascript">
       window.web3 = new Web3(new Web3.providers.HttpProvider("ws://localhost:8546"));
  </script>
```

**Comment by 7--** [comment]
I don't think this is a geth issue now. 

![Screenshot from 2020-09-15 21-45-17](https://user-images.githubusercontent.com/4725003/93282883-5cf97580-f79d-11ea-854c-bd22603a13be.png)

**Comment by holiman** [comment]
> I think browsers just don't allow cross origin requests unless it's HTTP(S).

Yes, in general, whenever you want to CORS, you cannot use `file://` protocol. Spin up a little webserver
