### ISSUE TITLE
Is gasPrice capped out at 500 gwei?

### ISSUE THREAD

**Issue by junderw** [ethereum/go-ethereum#21578]
We track our archive node's gasPrice with a 5 minute interval, and today's spike hit 500 gwei and is staying there...

Looking at the trajectory and speed at which it was increasing, it was much faster than any of the other previous gas price jumps with the DeFi markets recently.

Having the per-5-minute job suddenly stop at 500 gwei, and return exactly 500 gwei each time for the past 3.5 hours is unusual.

```
$ geth --verbosity 0 attach --exec eth.gasPrice
500000000000
```

So I figured I would ask the topic question before making an official bug report.

Thanks for your time.

**Comment by junderw** [comment]
We have mitigations in place, so this is not an urgent issue, but if gas price stays steady above 500 gwei and our estimates are stuck at 500 gwei we might run into problems eventually.

**Comment by karalabe** [comment]
Gas estimation by default is capped at 500gwei, yes. Current master contains a flag `--gpo.maxprice` which you can use to lift this default limit higher. It will be in next week's release.
