### ISSUE TITLE
Reward for the 2nd uncle appears to be wrong in accumulateRewards 

### ISSUE THREAD

**Issue by wenbingatcsu** [ethereum/go-ethereum#21589]
#20955 ## System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

Irrelevant. The issue is from the source code inspection at:
https://github.com/ethereum/go-ethereum/blob/fb458280d1b0b90156745202677dabbc74187697/consensus/ethash/consensus.go

#### Expected behaviour
Each uncle should get a block reward = (8+ UncleBlockHeight - CurrentBlockHeight)/8

#### Actual behaviour
In the for loop for up-to-two uncles:
reward := new(big.Int).Set(blockReward)
	r := new(big.Int)
	for _, uncle := range uncles {
		r.Add(uncle.Number, big8)
		r.Sub(r, header.Number)
		r.Mul(r, blockReward)
		r.Div(r, big8)
		state.AddBalance(uncle.Coinbase, r)

		r.Div(blockReward, big32)
		reward.Add(reward, r)
	}

The variable 4 is not reset to 0 after the first iteration. So, if there are two uncles, the second uncle would get an additional UncleBlockReward/32 than the first uncle.

#### Steps to reproduce the behaviour
N/A. Source code is very clear.

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
`r.Add(uncle.Number, big8)` is equivalent to `r = uncle.Number + big8`. The original value of `r` is discarded there.

**Comment by wenbingatcsu** [comment]
Thank you so much for the clarification.
