### ISSUE TITLE
RPC call for eth_subscribe with newHeads fails when an extra empty {} object is passed - incorrect docs or bug?

### ISSUE THREAD

**Issue by onqtam** [ethereum/go-ethereum#21588]
Looking at the RPC PUB/SUB documentation: https://geth.ethereum.org/docs/rpc/pubsub

When I try `{"jsonrpc":"2.0","id": 1, "method": "eth_subscribe", "params": ["newHeads", {}]}` I get an error `too many arguments, want at most 1`.

However when I remove the empty json object argument (`{}`) then it works: `{"jsonrpc":"2.0","id": 1, "method": "eth_subscribe", "params": ["newHeads"]}`.

Infura accepts it with the extra `{}` without a problem. Is this a bug? We managed to circumvent the issue by omitting the extra `{}` from the request but wanted to raise this issue here in case the geth docs need updating.

Using websockets and not HTTP if that's relevant.

#### System information

Geth version: `1.9.22-unstable`
OS & Version: Linux
Commit hash : `71c37d82adaa2b69ea98ce0c5505489d6b711c1e`

**Comment by fjl** [comment]
This is an issue with the documentation. The extra object parameter is not supported, and was never supported by go-ethereum.

**Comment by holiman** [comment]
https://github.com/ethereum/go-ethereum/issues/19909 --
