### ISSUE TITLE
block lost error

### ISSUE THREAD

**Issue by zeoio** [ethereum/go-ethereum#21585]
Does anyone know the cause of this error `block lost number=1834749 hash="aaf9e1…21e72a"`?

geth version 1.9.20

**Comment by MariusVanDerWijden** [comment]
This happens whenever a block is superseeded by newer blocks. If the block is not included as an uncle, the block is stake and gets dropped. This error happens often if you mine on a test chain, as the difficulty is so low that you can mine many block very fast, but it can also happen on mainnet, if other miners don't include your block.
