### ISSUE TITLE
Geth never re-sync block data after network interrupt

### ISSUE THREAD

**Issue by saltduck** [ethereum/go-ethereum#2158]
I just run geth the first time. It started to sync block data from the p2p network. After some hours, my network is down. So geth stopped to sync block data. It's all right. But while my network is up again, geth never sync data again. I have to press CTRL+C to stop it and run it again. Then every thing is OK and new block data is coming. I think that's a bug. Geth should automatically re-sync block data while the network is up.

**Comment by karalabe** [comment]
Could you tell us please what version of Geth are you using, how you installed it and on what operating system?

**Comment by saltduck** [comment]
I build it from git branch master.

OS: Ubuntu15.04

**Comment by drupalnomad** [comment]
I find this also. I am always switching network connections / suspending my computer, etc and sometimes Geth gets stuck and I have to restart it. bitcoind is much better in this regard - it can always recover.

**Comment by fjl** [comment]
This issue should be resolved in geth >= 1.3.4.
