### ISSUE TITLE
Ask a question about stateObject.updateTrie

### ISSUE THREAD

**Issue by james-ray** [ethereum/go-ethereum#21582]
```
func (s *stateObject) updateTrie(db Database) Trie {
	// Make sure all dirty slots are finalized into the pending storage area
	s.finalise()
	if len(s.pendingStorage) == 0 {
		return s.trie
	}
	// Track the amount of time wasted on updating the storge trie
	if metrics.EnabledExpensive {
		defer func(start time.Time) { s.db.StorageUpdates += time.Since(start) }(time.Now())
	}
	// Insert all the pending updates into the trie
	tr := s.getTrie(db)
	for key, value := range s.pendingStorage {
		// Skip noop changes, persist actual changes
		if value == s.originStorage[key] {
			continue
		}
		s.originStorage[key] = value

		if (value == common.Hash{}) {
			s.setError(tr.TryDelete(key[:]))
			continue
		}
		// Encoding []byte cannot fail, ok to ignore the error.
		v, _ := rlp.EncodeToBytes(common.TrimLeftZeroes(value[:]))
		s.setError(tr.TryUpdate(key[:], v))
	}
	if len(s.pendingStorage) > 0 {
		s.pendingStorage = make(Storage)
	}
	return tr
}
```

The deletion of the key value in the contract does not delete the key value in stateDB.  The tr.TryDelete(key[:]) does not delete stateDB.
Why can't we delete the obsolete unused key values from the stateDB to release disk space?

**Comment by karalabe** [comment]
Statedb is only a memory cache + convenience API on top of the tries. It's reset after every block so there's no point to manage life cycles in there too.

**Comment by james-ray** [comment]
> Statedb is only a memory cache + convenience API on top of the tries. It's reset after every block so there's no point to manage life cycles in there too.

I mean, the key values in the LevelDB, the storage trie of each contract is stored in the LevelDB. If there is a map there, for example, a map named "taskList", I want to delete the finished tasks, but seems like this does not free any disk space, because the deleted key values is still stored in LevelDB, though the storage root of the contract stateObject changes.

**Comment by holiman** [comment]
> because the deleted key values are still stored in LevelDB, though the storage root of the contract stateObject changes.

We store data by hash, and thus there's this inherent deduplication of data. Thus, we cannot blindly remove an item just because _one_ trie is no longer refernecing it, other tries might be. This is what 'pruning' is all about, and the reason that the state grows more when processing block-by-block compared to fast-sync.
