### ISSUE TITLE
Geth does not save synced data on Ctrl-C shutdown

### ISSUE THREAD

**Issue by bogatyy** [ethereum/go-ethereum#21584]
#### System information

Geth version: 1.9.20-stable
OS & Version: Ubuntu 18.04 LTS
Commit hash : `979fc96899c77876e15807005eadd936da17b6c2`

#### Expected behaviour

On Ctrl-C pressed while `geth` is running, `geth` takes some time to save sync progress to disc, and shuts down after that.

#### Actual behaviour

On Ctrl-C pressed while `geth` is running, `geth` stops immediately.
Upon restart, it needs to sync ~3 days worth of blocks.

#### Steps to reproduce the behaviour

Run `geth 1.9.20-stable`, sync chain, press Ctrl-C.
Might not be reproducible 100% of the time, sometimes `geth` does save progress to disc.

**Comment by bogatyy** [comment]
Git blame on the relevant code path only produces one recent update: https://github.com/ethereum/go-ethereum/commit/c0c01612e95dd20f125154646b38283ab780f357#diff-8d155028f84d7906b9c88c7630d3f7c4

Possibly related issues: https://github.com/ethereum/go-ethereum/issues/21087 https://github.com/ethereum/go-ethereum/pull/21114

**Comment by MariusVanDerWijden** [comment]
I tried to repro this, but couldn't. Could you paste the parameters you started your node with?
Is the node syncing or fully synced?

**Comment by holiman** [comment]
Would also be good with output, a few lines before and after pressing the ctrl-c button. Like, does it even show `log.Info("Got interrupt, shutting down...")`
Is it using `--console`?

**Comment by bogatyy** [comment]
Thank you for looking into the issue! Figured it out :)

> Like, does it even show log.Info("Got interrupt, shutting down...")
This was the clue.

I want to read `geth` logs but also preserve them for future reference, and so launched it as:
```bash
geth <FLAGS> |& tee -a /home/user/geth-log.txt
```
As a result, pressing Ctrl-C sent the signal into `tee`, not into `geth`.

**Comment by bogatyy** [comment]
On that note, any advice for printing `geth` logs both to console and into a logfile?
Parity has a `--log-file` flag that is super-useful, allows for pretty-printing logs into console (with color) and also writing them to a file.

**Comment by fjl** [comment]
Sorry, we don't have a file-based logger anymore. We removed it about 2 years ago because it's not possible to cater to everyone's needs regarding file logging. People usually have a custom setup anyway, for example, if you are using systemd or supervisord, it can handle this for you. If you are using some cloud deployment tool, it wants to be in charge of logging, etc.

**Comment by fjl** [comment]
Anyway, thanks for getting back to us!

**Comment by lrettig** [comment]
```
geth <FLAGS> |& tee -a /home/user/geth-log.txt
```

I'm doing the same thing, and running into the same issue. FYI, the right way to kill geth gracefully in this case would be to send a `kill -INT <pid>` - which is working well for me.
