### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by HafeezRai** [ethereum/go-ethereum#21599]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Account should not be able to send tx to it self
like your account address is abc your should not be able to send ethereum to your own account

#### Actual behaviour
You can send ethereum to your own address like abc to abc in etherscan it show self in transactions type 

#### Steps to reproduce the behaviour
send ethereum to your own account

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Sending to yourself is allowed by the protocol.

**Comment by holiman** [comment]
Also: sending to yourself is actually useful in some cases: 
- Replace a transaction by 'burning' the nonce, 
- Prove ownership of a key, e.g. with a hw wallet that doesn't support data-signing
