### ISSUE TITLE
All RAM is cached regardless of amount

### ISSUE THREAD

**Issue by sammy007** [ethereum/go-ethereum#2160]
After server boot and running geth eventually after several minutes all available RAM is cached. Regardless of how swapiness tuned on servers they will eventually start to swap. I am very sure this is not how geth must perform.

**Comment by karalabe** [comment]
Are you sure you're hitting swap? Linux always uses all the available memory for disk caches. I can imagine if an app requests a huge chunk of memory at once it might overflow for a moment into the swap space before flushing out the disk cache, but this isn't something we have any say about. It's just how the Linux kernel works.

**Comment by karalabe** [comment]
Closing this with works-as-intended. If you see the memory used by geth itself rising (as reported by `ps` or `top`) I'll gladly take a look, but disk caching is a Linux feature and should not interfere with your daily routines.
