### ISSUE TITLE
Transactions are not ordered by gasprice in the same block

### ISSUE THREAD

**Issue by DbIsFantastic** [ethereum/go-ethereum#21600]
Hi there,

I found some blocks mined by SparkPool are not ordered by `gasprice` anymore.
For example, take a look at this [transaction](https://etherscan.io/tx/0x64363d2366392a5f2c4950479a3d9c3a3ed412bad4d55a6e559273b31d5cdfd8), 
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/71758522/93991189-942fde00-fdbe-11ea-9192-2673b563d3a7.png">
which is in the block [10917864](https://etherscan.io/block/10917864),  mined by SparkPool, which is on the position 199. And its gasprice is 111 Gwei, but in the same block, there are a lot of transaction which has lower gasprice, but located in the position before that transaction.  Here are some screenshots:
1.  
[](https://user-images.githubusercontent.com/71758522/93991422-dd802d80-fdbe-11ea-801d-347ce4d2c6e0.png)
2.
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/71758522/93991450-e8d35900-fdbe-11ea-87c5-aa9d572902fe.png">
3.
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/71758522/93991477-f1c42a80-fdbe-11ea-9d9c-02eeb47ac5ae.png">

Currently, I could only find blocks from Sparkpool follow this rule, but is it new feature?  If not, does it affect the blockchain system?

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
In the same block, txs are ordered by gasprice.

#### Actual behaviour
In the same block, txs are no longer ordered by gasprice.

#### Steps to reproduce the behaviour
Please take a look at the links and screenshots I posted. 

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Etherscan sorts the transactions in reverse order (i.e. latest transaction first), so the price list is actually reverse.

**Comment by karalabe** [comment]
There is 1 transaction - the very first - at 10 gwei. That is probably a "local" transaction. Miners will always include those first at arbitrary price points. If there are other inversions, please point them out.

**Comment by DbIsFantastic** [comment]
@karalabe 

I think the transaction [0x64363d2366392a5f2c4950479a3d9c3a3ed412bad4d55a6e559273b31d5cdfd8](https://etherscan.io/tx/0x64363d2366392a5f2c4950479a3d9c3a3ed412bad4d55a6e559273b31d5cdfd8) is in the wrong position. 
### Details for 0x64363d2366392a5f2c4950479a3d9c3a3ed412bad4d55a6e559273b31d5cdfd8
<img width="949" alt="image" src="https://user-images.githubusercontent.com/71758522/94003162-7c138b00-fdcd-11ea-9f57-b303eb2866a8.png">


The gasprice for this transaction is 111GWei, and its position is 199. 

Take a look at its pre-pre-sibling(position 197) transaction [0x82f42e47b12cf55c5b600b84636ecf0c3f9a13d6e799fd23695ff50fdca57db7](https://etherscan.io/tx/0x82f42e47b12cf55c5b600b84636ecf0c3f9a13d6e799fd23695ff50fdca57db7)  and next sibling(position 200)  [0xca0d6f9055aacc370380f54b6bebb2e8e01e7a0d3c39a597e670769a902d4ada](https://etherscan.io/tx/0xca0d6f9055aacc370380f54b6bebb2e8e01e7a0d3c39a597e670769a902d4ada), their `gasprice` are both lower than the price of 0x64363d2366392a5f2c4950479a3d9c3a3ed412bad4d55a6e559273b31d5cdfd8.

### Details for 0x82f42e47b12cf55c5b600b84636ecf0c3f9a13d6e799fd23695ff50fdca57db7 
<img width="958" alt="image" src="https://user-images.githubusercontent.com/71758522/94003360-b41ace00-fdcd-11ea-8415-a9d991a86006.png">

### Details for 0xca0d6f9055aacc370380f54b6bebb2e8e01e7a0d3c39a597e670769a902d4ada
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/71758522/94002984-322aa500-fdcd-11ea-800d-368fcb24b3a3.png">

So the gasprice of the problem transaction(position 199) is higher than both its pre-pre-sibling(position 197) and its next-sibling transaction(position 200).

**Comment by holiman** [comment]
There are a lot of unknowns here, sparkpool may be running some custom miner (the extradata is `
eth-pro-hzo-t005 `), or other non-geth, like Parity. ISTR that parity supports setting various strategies for how to select transactions. 

> Currently, I could only find blocks from Sparkpool follow this rule, but is it new feature? If not, does it affect the blockchain system?

No, it doesn't matter for the ethereum blockchain if transactions are ordered by price or by random. It's totally up to the miner to put the together in a way to maximize profit. 

I don't think this ticket points to a a bug in geth, so I'm going to close this. If you find any evidence that geth erroneously packs transactions into blocks, please reopen.

**Comment by wsy2220** [comment]
Txs are sorted by gasprice and nonce, and nonce order must be enforced. See https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction.go#L349

This account has 2 txs in that block. The first one has lower gasprice, so it is arranged at later half of the block. The second one has higher price but can not be placed before the first one. This happens very often.
