### ISSUE TITLE
Peer discovery service provokes firewall bans 

### ISSUE THREAD

**Issue by chfast** [ethereum/go-ethereum#2162]
My corporate firewall starts blocking any connections comping from my computer after using geth with peer discovery service enabled. geth is configured for private network so it has no change finding any peer matching network id. This has never happened with C++ and Python implementation.

**Comment by karalabe** [comment]
Hmm, could you tell us **why** the firewall is banning you? I mean what filtering rules are you hitting?

**Comment by chfast** [comment]
Sorry for late response. I was trying to get any more details about the issue.

So the firewall we have is Cisco ASA5505, but I was said by IT guy it _does not_ blocks connections from my computer. The limit of opened connections is 2000.

The true issue is, after some time of running geth (`geth --networkid 666`) I have internet connectivity problems - some hosts are unreachable and/or responses are very slow. If you have idea what test I can perform to detect the issue please let me know.

**Comment by fjl** [comment]
I haven't had time to look deeper into the packet trace you provided recently. For reference, my findings from looking quickly were:

> I looked briefly and there is indeed not much to report.
> But some things are 'interesting' in the trace.
> One of the side effects of the discovery protocol is that it shoots a
> ton of packets to all kinds of destinations.
> Depending on your network and OS, this triggers all kinds of responses
> floating around in the network.
> For example, some remote hosts will actually send an ICMP reply back
> which tells geth that there is nothing at that port.
> For others, it seems to cause various broadcasts from your routers.

**Comment by fjl** [comment]
I'm *dusting off my Stevens* for this one.

**Comment by pdobacz** [comment]
+1

**Comment by chfast** [comment]
Can we proceed with this issue somehow?
