### ISSUE TITLE
"admin.addPeer" is not working.

### ISSUE THREAD

**Issue by PhzCode** [ethereum/go-ethereum#21631]
1. I run those in two terminal to start two nodes
```
geth --datadir . --port 30302 console
geth --datadir . --port 30301 console
```
2. then, I want connect to two nodes
```
> admin.nodeInfo.enode
"enode://f42ad69b517c0339bfb679b43e6959e42149d815dd92738f0474194dca6e5efe9fd4829941e3f9655de8cfe5e6aaa97d0131ab461240455656d2dce2797fa160@10.82.59.136:30301"
```
in next node:
```
> admin.addPeer("enode://f42ad69b517c0339bfb679b43e6959e42149d815dd92738f0474194dca6e5efe9fd4829941e3f9655de8cfe5e6aaa97d0131ab461240455656d2dce2797fa160@10.82.59.136:30301")
true
> admin.peers
[]
```

## result
even I use the function `addPeer`, it is not be connected!
I do not know what is going on,
(it is the first time to write issue, please ignore some mistakes, hhhhhh)

**Comment by beyonderyue** [comment]
You should see logs, maybe use flag `--verbosity 5`. And you should use different datadir with different geth.

**Comment by PhzCode** [comment]
> You should see logs, maybe use flag `--verbosity 5`. And you should use different datadir with different geth.

I do run every node in different datadir, and the logs have no useful infomation. anyway, thx

**Comment by beyonderyue** [comment]
You can use flag `--verbosity 5` to get more detailed information.

**Comment by MariusVanDerWijden** [comment]
`addPeer` adds the peer asynchronously so you have to wait some time for your list of peers to update. I think you're using the public ip of the nodes right? maybe it is some issue with your nat or router that doesn't allow incoming connections. You could try replacing the ip with "127.0.0.1:30301"

**Comment by PhzCode** [comment]
> `addPeer` adds the peer asynchronously so you have to wait some time for your list of peers to update. I think you're using the public ip of the nodes right? maybe it is some issue with your nat or router that doesn't allow incoming connections. You could try replacing the ip with "127.0.0.1:30301"

I tested this private chain in my local network environment, so all the IPs are beginning with "127.0.0.1". As you say, I waited for minutes after addPeer, but it did not work either. 

Addition, below it is some output in terminal, `peercount` is changing sometimes. Also, before I `addPeer`, there is also `peercount=1` sometimes.

```
INFO [09-30|15:48:47.433] Looking for peers                        peercount=1 tried=49 static=1
INFO [09-30|15:48:58.266] Looking for peers                        peercount=0 tried=46 static=1
```

**Comment by karalabe** [comment]
You'll need to provide some logs, otherwise there's no way to see what's wrong. We're using addPeer regularly in our tests so the functionality most definitely works.

**Comment by Maksim-lk** [comment]
try add  --http.addr 0.0.0.0 
Ensure that the chainId of the two nodes are the same

and then let one node keep mining, another node will automatically connect and synchronize

another way is to create a static config file static-nodes.json at ../geth/, add your nodes' enode info as a JSON array

**Comment by Lucas-gif845** [comment]
> You'll need to provide some logs, otherwise there's no way to see what's wrong. We're using addPeer regularly in our tests so the functionality most definitely works.

hello, here's a fraction of my log : TRACE[10-29|14:02:18] Dial error                               task="staticdial c859e63b8ea2e0db 192.168.31.59:30303" err="dial tcp 192.168.31.59:30303: connectex: No connection could be made because the target machine actively refused it."
DEBUG[10-29|14:02:18] Can't resolve node                       id=c859e63b8ea2e0db err="discovery is disabled"
then I deleted the parameters "--nodiscover", it worked.  I don't figure out why

**Comment by korgx5dsynth** [comment]
If you are just testing locally, add the `--nat=extip:127.0.0.1` and then your enode should now use `127.0.0.1` and thereby the nodes shall find each other.

**Comment by zhengxinle** [comment]
> try add --http.addr 0.0.0.0 Ensure that the chainId of the two nodes are the same
> 
> and then let one node keep mining, another node will automatically connect and synchronize
> 
> another way is to create a static config file static-nodes.json at ../geth/, add your nodes' enode info as a JSON array

thanks, i  use admin.addpeer to conect node0 and node1 and then it return true but doesn't work, finally, i find the reason:
for node0, i 
`./geth --datadir "./data0" init init.json  `
  and then start the node0;
`./geth --datadir "./data0" --port "30303"   --http.port 8545  --networkid 2333 --rpcapi eth,net,web3,personal --nodiscover console 2>> ./data1/log`

for node1,
 i foget to init node1 with init.json, just directly start node1 
`./geth --datadir "./data1" --port "30304"   --http.port 8547  --networkid 2333 --rpcapi eth,net,web3,personal --nodiscover console 2>> ./data1/log`

this cause the two node with diffrent chainid, and when i use addpeer(node0's enode) in node1, there is no any err message in log, certianly the  node0 and node1 are not connected;
just remember to init each node with init.json before start it.

**Comment by dinohondo** [comment]
> If you are just testing locally, add the `--nat=extip:127.0.0.1` and then your enode should now use `127.0.0.1` and thereby the nodes shall find each other.

Solved the problem for me, thanks
