### ISSUE TITLE
Rinkeby faucet not working

### ISSUE THREAD

**Issue by gaieges** [ethereum/go-ethereum#21637]
Lots of details / comments in this ticket here, which it seems people have been adding to indicating there's a problem:

https://github.com/ethereum/go-ethereum/issues/21375

@karalabe @uivlis

**Comment by MariusVanDerWijden** [comment]
Yes, we are aware that the faucet is down. There is a problem with the light client on rinkeby which basically means the faucet is unable to find peers. We are working on it

**Comment by karalabe** [comment]
Should be more stable now, we've enabled DNS discovery on the faucet too.

**Comment by tontonkiller** [comment]
Hello
Sorry to disturb
Still having the error, trying to use the Rinkeby testnet faucet " insuficient funds for gas * price + value"
I'm using this address
0x7b41b76D6c816ba19671C5120E957DE9992e7199

**Comment by WolveIT** [comment]
its not working atm

**Comment by UsabilitySpace** [comment]
Can't get test ether, I confirm the issue
