### ISSUE TITLE
signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xda5a78

### ISSUE THREAD

**Issue by joeytwiddle** [ethereum/go-ethereum#21632]
#### System information

Geth version: 1.9.21-stable
OS & Version: Linux (Amazon Linux 4.14.193-149.317.amzn2.x86_64)

#### Actual behaviour

I keep getting the follow error after a few hours of running a light node. This happens on both mainnet and ropsten nodes, with an identical stacktrace (minus arguments).

```
INFO [09-27|02:09:33.807] Imported new block headers               count=192  elapsed=793.052ms number=8759832 hash="dcbb17…dcfc96" age=15h4m44s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xda5a78]

goroutine 70 [running]:
github.com/ethereum/go-ethereum/light.(*TxPool).reorgOnNewHead(0xc002eaf4a0, 0x1520660, 0xc002730ae0, 0xc002f37440, 0xc002730ae0, 0xc002ee29d0, 0x4664ac)
        github.com/ethereum/go-ethereum/light/txpool.go:229 +0x238
github.com/ethereum/go-ethereum/light.(*TxPool).setNewHead(0xc002eaf4a0, 0xc002f37440)
        github.com/ethereum/go-ethereum/light/txpool.go:310 +0xf7
github.com/ethereum/go-ethereum/light.(*TxPool).eventLoop(0xc002eaf4a0)
        github.com/ethereum/go-ethereum/light/txpool.go:291 +0x56
created by github.com/ethereum/go-ethereum/light.NewTxPool
        github.com/ethereum/go-ethereum/light/txpool.go:108 +0x3da
```

#### Steps to reproduce the behaviour

1. Create a free tier instance on AWS EC2.

2. Open ports in the firewall.

3. Log in and start a node with:

```
cd geth-linux-amd64-1.9.21-0287d548/

./geth --syncmode light \
  --datadir "$HOME/.ethereum-mainnet" \
  --port 30303 \
  --cache 32 \
  --rpc --rpcaddr 172.31.42.120 --rpcport 28545 --rpcapi personal,web3,eth \
  --ws --wsaddr 172.31.42.120 --wsport 28546 --wsapi personal,web3,eth
```

In the meantime, I'm going to try downgrading to an earlier version that worked for me in the past.

Update: I downgraded to geth-linux-amd64-1.9.17-748f22c1 and have not encountered the same problem.

**Comment by holiman** [comment]
@rjl493456442 is this the same root cause as https://github.com/ethereum/go-ethereum/issues/21583 ? The stack trace is not identical

**Comment by rjl493456442** [comment]
@holiman Yes, it is. It's the original issue why Peter starts to fix it.

@joeytwiddle We just have the latest release which should already fix this issue. Could you please have another try?

**Comment by joeytwiddle** [comment]
Looks good. After 8 hours running geth-linux-amd64-1.9.22-c71a7e26, the mainnet node has not crashed.

The testnet node I cannot judge, because it is still looking for peers.
