### ISSUE TITLE
Full Sync failing repeatedly on Block 6318496

### ISSUE THREAD

**Issue by jim3456** [ethereum/go-ethereum#21641]
I am trying to create a full node on a 1 TB SSD. 
It is repeatedly failing on the same block. Restarts and removing the hash cache did not fix the issue

#### System information

Geth
Version: 1.9.21-stable
Git Commit: 0287d54847d3297f3ced62cd83a4c95ccbe0045b
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15
Operating System: linux
GOPATH=
GOROOT=go

#### Expected behaviour

The block in question contains some contracts that failed due to gas, but I would have expected the sync to move past these errors. https://etherscan.io/txs?block=6318496

#### Actual behaviour

ERROR[09-29|17:09:33.349] 
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, YOLO v1: <nil>, Engine: ethash}

Number: 6318496
Hash: 0xc5bb82478337242b65dbc36772de71a76617561d1ed06fc5473edfba0ab7406a

Error: insufficient funds for gas * price + value
##############################
 
WARN [09-29|17:09:33.349] Synchronisation failed, dropping peer    peer=38572328646ff294 err="retrieved hash chain is invalid: insufficient funds for gas * price + value"
INFO [09-29|17:09:34.252] Looking for peers                        peercount=1 tried=60 static=0
INFO [09-29|17:09:44.296] Looking for peers                        peercount=1 tried=60 static=0
INFO [09-29|17:09:54.297] Looking for peers                        peercount=1 tried=46 static=0

#### Steps to reproduce the behaviour
geth --syncmode "full" --rpc --signer=/home/jim/.clef/clef.ipc --maxpeers=25

**Comment by holiman** [comment]
Did the node at any point crash and was restarted?

**Comment by holiman** [comment]
In order to recover from this, you probably will need to do a setHead, though I'm not sure what's a good value to go back to. I would suspect `debug.setHead(6328490)` or something like that should trigger a rollback to some point in time where the state is present. Does that sound correct, @karalabe ?

**Comment by jim3456** [comment]
@holiman the node did crash and was restarted during the sync. There have been multiple crashes of varying types. Some There have been two seg faults, a Bad Block error, and a bad database file. 
Each time, I was unable to connect to the node to debug.setHead before it would bail. 
However, each time a full reboot of the computer.. the sync was able to proceed.

**Comment by karalabe** [comment]
How did you solve a bad database file? That seems like a deal breaker problem with your disk. If your database is getting corrupted on disk, there's not much we can do.

**Comment by karalabe** [comment]
If a machine restart fixes a problem then I'm afraid the issue is somewhere else. I'd recommend checking the disk for bad sectors or the memory for failures.

Saying "half a dozen different errors" doesn't help. Please provide each and every one of them, otherwise we can't help you.

**Comment by MariusVanDerWijden** [comment]
@jim3456 Could you please provide logs for all errors you encountered?
We synced several nodes past 6318496 in the past weeks without any issues
