### ISSUE TITLE
Geth has been syncing for over a month in fast mode on AWS

### ISSUE THREAD

**Issue by coval3nte** [ethereum/go-ethereum#21648]
We have been trying to setup geth on our AWS infrastructure for over a month now, but it still has not synced.

Useful information:
- Geth fast mode
- > eth.syncing
{
  currentBlock: 10969281,
  highestBlock: 10969437,
  knownStates: 851958910,
  pulledStates: 851958909,
  startingBlock: 10968794
}
- the currentBlock never catches up with the highestBlock
- on AWS we’re using a t2.large to sync with EFS (instance is on a VPC with NAT)

geth CLI opts:  --datadir /mnt/geth --cache=55000

**Comment by holiman** [comment]
Yeah, `851958909` -- way more than should be needed, as there are only somewhere around 600M entries. Since the progress was so slow, it kept moving the pivot point, and that causes extra fetches. 
What version are you running? 
What speeds are you getting with that mounted EFS?

**Comment by coval3nte** [comment]
geth version: 1.9.19-stable-3e064192
```
$ nfsiostast
fs-xxxxxxxx.efs.eu-central-1.amazonaws.com:/ mounted on /mnt:
           ops/s       rpc bklog
         224.140           0.000

read:              ops/s            kB/s           kB/op         retrans    avg RTT (ms)    avg exe (ms)
                 151.225        3855.045          25.492        5 (0.0%)           3.655           3.714
write:             ops/s            kB/s           kB/op         retrans    avg RTT (ms)    avg exe (ms)
                   0.864         538.392         622.802        0 (0.0%)         141.335         183.549
```

**Comment by holiman** [comment]
That looks pretty bad, tbh. Here's on one of our benchmarker machines, also on AWS, an `i3.2xlarge` which has an `1.9Tb NVMe SSD`:
```
iostat -d -x 
Linux 5.3.0-1032-aws (bench03.ethdevops.io) 	10/01/20 	_x86_64_	(8 CPU)

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
nvme0n1        735.15   82.32   8712.76   8506.39     3.10    53.63   0.42  39.45    0.14    1.64   0.08    11.85   103.34   0.39  31.69

```

**Comment by coval3nte** [comment]
so you advise to don't use EFS but switch to an EBS (io1 for example)?

**Comment by karalabe** [comment]
You'll need a storage system that has a high IOPS throughput and a low latency. For us directly attached NVMe driver perform best.
