### ISSUE TITLE
Cannot get the correct nonce using the pending parameter.

### ISSUE THREAD

**Issue by ckmonkey** [ethereum/go-ethereum#21642]
Hi there,

platon.getTransactionCount("xxxxxxx","pending") -> 0 (can not get real nonce)
platon.getTransactionCount("xxxxxxx","latest") -> 2 (get real nonce)

Why? What to pay attention to.

**Comment by ligi** [comment]
please provide more info like your geth version

**Comment by holiman** [comment]
Is this even geth? `platon.xxx` ?
