### ISSUE TITLE
No differentiation between 'pending' and 'queued' transactions when querying txpool with GraphQL

### ISSUE THREAD

**Issue by liamaharon** [ethereum/go-ethereum#21658]
Hi, I have a feature request for the GraphQL interface. 

It can be useful to be able to differentiate between transactions in the `pending` and `queued` part of the txpool. 

The `txpool_content` JSONRPC method allows for this, returning the txpool in 2 sections, `pending` and `queued`.

The only downside with that query is that it can be pretty expensive to run on nodes with a high `txpool.globalslots` config option. 

Using the GraphQL interface it's much faster to query which hashes are pending in the pool with a simple query, really awesome.
```
{
  pending {
    transactions {
      hash
    }
  }
}
```
The only downside with this method is that it returns transactions from both `pending` and `queued` parts of the txpool. 

Ideally I'd be able to make a query like this
```
{
  pending {
    transactions {
      hash
    }
  },
  queued {
    transactions {
      hash
    }
  }
}
```
so it would be clear which txns are eligible for inclusion in a block, and which are 'stuck'.

I understand it would be a breaking change to the `pending` query, but I think the definition is a little ambiguous as it is right now anyway. https://eips.ethereum.org/EIPS/eip-1767 makes no mention of which part/s of the txpool a `pending` query would return, and given that when using `txpool_content` `pending` very clearly means the part of the txpool eligible for inclusion in a block, I think people could be forgiven for thinking that querying `pending` with GraphQL would also only return txns eligible for inclusion in a block.

For my txpool use case at least, this limitation with GraphQL is a deal breaker and I'll need to keep on using `txpool_content` until it's addressed. 

Aside from this one instance with the txpool, my experience with the GraphQL interface has been great. Replacing wasteful JSONRPC queries is a special kind of rush ;) Thanks for the awesome work building this in.

**Comment by holiman** [comment]
Looking at the code: 
https://github.com/ethereum/go-ethereum/blob/341f4510830f169653f47a3428037c612fdd0e36/graphql/graphql.go#L844

It calls `txs, err := p.backend.GetPoolTransactions()`, which is implemented here: https://github.com/ethereum/go-ethereum/blob/341f4510830f169653f47a3428037c612fdd0e36/eth/api_backend.go#L229

This method returns the `pending` transactions from the pool, but does not add the `queued`. So afaict, it doesn't work like you describe. Could you please check this again?
