### ISSUE TITLE
How can I solve the transfer  problem?

### ISSUE THREAD

**Issue by busgo** [ethereum/go-ethereum#21651]
When I use web3j to initiate a transfer and no response has been received, the network is disconnected. Now I don't have the hash value of the current transaction. How can I know the status of the current transaction?
How can I solve this problem?

**Comment by karalabe** [comment]
Not sure what you are doing or what the error is without any logs or code.

If a transaction is submitted through Geth, it will get logged, so you can look up the hash from the logs. You can check currently pending transactions via eth.pendingTransactions or txpool.inspect and find your sender account in the list.

**Comment by busgo** [comment]
Is there a way to get the "txHash" when send the request?       

>  Hash.sha3(input)   ???

**Comment by beyonderyue** [comment]
Maybe you can use RawTransaction, RawTransactionManager in web3j to do this..

**Comment by beyonderyue** [comment]
Refer codes below:
```java
RawTransactionManager rawTransactionManager = new RawTransactionManager(web3j, credentials);
count = web3j.ethGetTransactionCount(credentials.getAddress(), DefaultBlockParameterName.LATEST).send();
RawTransaction rawTransaction = RawTransaction.createTransaction(count.getTransactionCount(), gasPrice, gasLimit, toAddress, BigInteger.ONE, null);
String sign = rawTransactionManager.sign(rawTransaction);
String hash = Hash.sha3(sign);// This hash is what you want
```

**Comment by busgo** [comment]
> Refer codes below:
> 
> ```java
> RawTransactionManager rawTransactionManager = new RawTransactionManager(web3j, credentials);
> count = web3j.ethGetTransactionCount(credentials.getAddress(), DefaultBlockParameterName.LATEST).send();
> RawTransaction rawTransaction = RawTransaction.createTransaction(count.getTransactionCount(), gasPrice, gasLimit, toAddress, BigInteger.ONE, null);
> String sign = rawTransactionManager.sign(rawTransaction);
> String hash = Hash.sha3(sign);// This hash is what you want
> ```

ok   thank you   !
