### ISSUE TITLE
oss-fuzz integration of go-ethereum

### ISSUE THREAD

**Issue by AdamKorcz** [ethereum/go-ethereum#21657]
(Repost of https://github.com/ethereum/go-ethereum/issues/21656 from my personal GH account)

This issue is to suggest integration of go-ethereum into Google's [oss-fuzz](https://github.com/google/oss-fuzz).

Integration would mean that Google would run the existing fuzzers free of charge continuously, and in case any bugs are found, a detailed bug report is sent out to the maintainers.

I can confirm that the existing fuzzers run on oss-fuzz's infrastructure, and I will be happy to commit my setup to oss-fuzz. All I need are the email addresses of the maintainers. These email addresses would be uploaded to a public list and can be changed at any time.

While oss-fuzz is a free service, there is an implied expectation that found bugs are fixed, so that the resources spent on fuzzing go-ethereum will be put to good use.

A list of projects being fuzzed through oss-fuzz can be found [here](https://github.com/google/oss-fuzz/tree/master/projects).

**Comment by holiman** [comment]
Sounds great! As for maintainer addresses, there are three listed on https://geth.ethereum.org/downloads/ :
```
Felix Lange <fjl@ethereum.org>
Martin Holst Swende <martin.swende@ethereum.org>
Péter Szilágyi <peter@ethereum.org>
```

**Comment by holiman** [comment]
Waiting for @karalabe: https://github.com/google/oss-fuzz/pull/4515

**Comment by MariusVanDerWijden** [comment]
Integration into oss-fuzz was merged
