### ISSUE TITLE
go-ethereum doesn't support the methods 'getPendingTransactions'? why,how can I get the pending txes?

### ISSUE THREAD

**Issue by trybye** [ethereum/go-ethereum#21663]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information
linux
Geth version: `1.9.22`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
It's eth_pendingTransactions (via the API) or eth.pendingTransactions via the console.

**Comment by trybye** [comment]
> It's eth_pendingTransactions (via the API) or eth.pendingTransactions via the console.

I can't find eth_pendingTransactions or eth.pendingTransaction in go-ethereum
