### ISSUE TITLE
CPU usage permanently between 100-300% usage, 24-core - 200GB RAM Server

### ISSUE THREAD

**Issue by dappstatus** [ethereum/go-ethereum#21667]
**Problem:**
I finished to sync my eth fullnode and run it since a month now. As you can see in the following pictures, my main problem now is that the CPU usage is permanently between 100-300%, even though i have 24-core and 200GB of RAM! I just tried to restart the import with "systemctl start geth" but it immediately goes back to 100-300% CPU usage.

**System:**
Geth version:  1.9.17-stable
OS & Version: Ubuntu 18.04.4 LTS
Server hardware: 24-core - 200GB RAM

**After full sync:** 
![1](https://user-images.githubusercontent.com/42303143/95222921-9a48a480-082b-11eb-86b1-99bbc659cc5b.JPG)
![2](https://user-images.githubusercontent.com/42303143/95222928-9caafe80-082b-11eb-9b7d-86dc6949af20.JPG)
![3](https://user-images.githubusercontent.com/42303143/95222940-9e74c200-082b-11eb-8da2-102d1f092880.JPG) 
 

**Stop after full sync:**
![1](https://user-images.githubusercontent.com/42303143/95223014-b0eefb80-082b-11eb-84f1-d41ec95cf46b.JPG)
![2](https://user-images.githubusercontent.com/42303143/95223018-b2202880-082b-11eb-89cf-921f59316ef9.JPG) 

**Restart after stop from full sync:**
![1](https://user-images.githubusercontent.com/42303143/95222963-a3397600-082b-11eb-8aea-7d16b68378e3.JPG)
![2](https://user-images.githubusercontent.com/42303143/95222989-aa608400-082b-11eb-8add-09c5dde8fb0b.JPG)
![3](https://user-images.githubusercontent.com/42303143/95222998-ac2a4780-082b-11eb-966a-6f92927dca48.JPG)

**Comment by MariusVanDerWijden** [comment]
Top displays the usage in percent of a single core. Which means 100% is one core fully utilized, 300% is three cores fully utilized. 
Depending on what kind of cores you have in your system we expect geth to use two ore three cores worth of CPU time.
For more info see https://unix.stackexchange.com/questions/145247/understanding-cpu-while-running-top-command
