### ISSUE TITLE
Geth Websocket Connections Return 200

### ISSUE THREAD

**Issue by BisonAl** [ethereum/go-ethereum#21668]
#### System information
Geth version: `1.9.20`
OS & Version: Alpine

Running both websocket and rpc on port `8545`, using the
```
--ws.port
8545
```
flag

#### Expected behaviour
When attempting to query the rpc endpoint over `https` at `/` and port `8545`, a correct response is served.

When attempting to connect to the websocket over `wss` endpoint at `/` and port `8545`, while passing through the headers:
```
Connection: Upgrade
Upgrade: websocket
```
a lasting websocket connection is made.

#### Actual behaviour
When attempting to query the rpc endpoint over `https` at `/` and port `8545`, a correct response is served.

When attempting to connect to the websocket over `wss` endpoint at `/` and port `8545`, while passing through the headers:
```
Connection: Upgrade
Upgrade: websocket
```
I'll get back a `200` response code instead, and no lasting connection made.

The same behavior was encountered with a variety of tools:

```
~ ❯ wscat -c wss://myethereumurl.net                    
error: Unexpected server response: 200

~ ❯ geth attach wss://myethereumurl.net
Fatal: Unable to attach to remote geth: websocket: bad handshake (HTTP status 200 OK)

~ ❯ websocat -k wss://myethereumurl.net 
websocat: WebSocketError: Received unexpected status code (200 OK)
websocat: error running
```

My theory is that geth is not treating this incoming request as an websocket connection, and is not switching protocols properly. 

#### Steps to reproduce the behaviour
- Create a geth full node on `v1.9.20` with websocket and rpc served at port `8545`.
- Expose this geth node to external traffic
- Attempt to establish a websocket connection using `wss://`, with a tool such as `geth attach`, `wscat` or `websocat`
- See that you'll receive a 200 error code back.

#### Additional Note
Wondering if anyone else has ran into this, and may have some additional insight. I am not sure if this is a bug, or an expected result given the way I'm trying to interact with my node.

My setup was working on geth `1.9.13`, however since then I know there's been a good deal of work done overhauling websockets. I'm wondering if there's any changes since then that could be causing this behavior, however I couldn't find any details in recent release notes.

If this is a known issue and can be solved by altering my configuration, I would greatly appreciate the insight!

**Comment by BisonAl** [comment]
Issue solved, we can close it when https://github.com/ethereum/go-ethereum/pull/21646 is merged.

**Comment by mattfixme** [comment]
did u solve this question, i have the same issue. my geth version is **1.11.0-unstable**. @BrockMcCullough
