### ISSUE TITLE
Clef returns `request denied` instead of an empty list when there are no accounts to list

### ISSUE THREAD

**Issue by cygnusv** [ethereum/go-ethereum#21674]
When we perform an `account_list` request to clef and there is no hardware wallet plugged-in or keystore files in the keystore directory, Clef errors with a `request_denied`. Seems like a better approach would be to respond with an empty list.

#### System information

Geth version: 1.9.15-stable
OS & Version: OSX

#### Expected behaviour
Return an empty list.

#### Actual behaviour
Errors with `request_denied`.

#### Steps to reproduce the behaviour
* Run clef with no HW wallet and using a keystore directory with no keystore files
* Make an `account_list` request

#### Backtrace

On Clef side: 
```
WARN [10-08|01:35:34.789] Served account_list                      reqid=0 t=6.788424ms               err="request denied"
```

On the requesting application side (using web3py):
```
  
File "/Users/david/NuCypher/dev/nucypher/nucypher/blockchain/eth/signers/software.py", line 167, in accounts
    normalized_addresses = self.__ipc_request(endpoint="account_list")
  File "/Users/david/NuCypher/dev/nucypher/nucypher/blockchain/eth/signers/software.py", line 136, in __ipc_request
    response = self.w3.manager.request_blocking(endpoint, request_args)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.8/site-packages/web3/manager.py", line 153, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'request denied'}
```

**Comment by holiman** [comment]
Thanks, patch upcoming

**Comment by holiman** [comment]
> Lost my key file but have the masterseed.json file!

The private key behind an ethereum account is in the keyfile. The masterseed does not contain sufficient information to recreate an account.

**Comment by accessaaaa** [comment]
Is everything lost? If I start over!? How many accounts will it threat??

**Comment by accessaaaa** [comment]
Hello,

Thanks for your email btw.

Anyhow the wallet with mining coins 1.5 years old. Clef said that it would
make another key file from the others. But nothing yet it is now listin and
setting the corrections.
So maybe when it's done?
