### ISSUE TITLE
Half a million open chaindata LevelDB files with main net archive node

### ISSUE THREAD

**Issue by terorie** [ethereum/go-ethereum#21675]
#### System information

Geth version: `v1.9.21`
OS & Version: Linux 5.4.0-47-generic, Ubuntu 20.04

#### Expected behaviour

I would expect the number of open files to be less than a hundred thousand.

For example, a Parity v2.5 main net archive/tracing node has the following statistics.

```
# 5.2 TB archive data
archive/db$ sudo du -sh .
5.2T	.

# 512 open RocksDB SSTables
archive/db$ lsof -p $(pidof parity) | grep .sst | wc -l
512

# 86.6K SSTable files
archive/db$ find . -name '*.sst' | wc -l
86566
```

#### Actual behaviour

go-ethereum's chaindata LevelDB uses much more handles and files. `debug.chaindbCompact` does not decrease the number of files noticeably.

```
# 5.1 TB archive data
geth/chaindata # du -sh .
5.1T	.

# 522676 open LevelDB files !
geth/chaindata # lsof -p 559621 | grep .ldb | wc -l
522676

# 2.7 million LevelDB files
geth/chaindata # find . -name '*.ldb' | wc -l
2686612
```

#### Steps to reproduce the behaviour

Sync an archive node on main net.

#### Is this a bug?

Honestly, I don't know. Modern file systems handle hundreds of thousands of files just fine. I think it's fair to discuss whether this could become a bottleneck.

**Comment by karalabe** [comment]
We're aware of this. Generally LSM type databases make files in each subsequent level 2x as large as the previous one. This works well when the database is stable, but in the case of Ethereum, trie nodes are written by hash (i.e. fully random), so compaction keeps overwriting the entire files over and over and over again. By having smaller files (i.e. not 2x, rather the same size on every level) we can keep the disk IO at a much smaller number. The price is gazillions of 2MB files. Not ideal, but we're not aware of a better solution that doesn't blow up IO.

**Comment by terorie** [comment]
@karalabe Thanks, makes sense. Parity goes great lengths to keep the number of files sane, sometimes compacting up to 20 minutes before starting up.
Does geth expose any config parameters for tuning LSM parameters?
