### ISSUE TITLE
get block rpc giving result as '0' .curl -X POST -H 'content-type:application/json' --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}' http://localhost:8545. i have started the node using below sudo docker run -d  --name coregethnode -v /node-etc-geth/data:/root  -p 127.0.0.1:8545:8545  -p 30303:30303 etclabscore/core-geth --classic  --http --http.port 8545 --http.addr "0.0.0.0"

### ISSUE THREAD

**Issue by sankararaokgmail** [ethereum/go-ethereum#21679]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
This is not etc, nor coregeth.
