### ISSUE TITLE
How to create a private network parameters like testnet on config.go?

### ISSUE THREAD

**Issue by riddlerx** [ethereum/go-ethereum#21671]
How to create the parameters like testnet on config.go ?

TestnetChainConfig = &ChainConfig TestnetTrustedCheckpoint = &TrustedCheckpoint TestnetCheckpointOracle = &CheckpointOracleConfig

**Comment by karalabe** [comment]
The chain config is the forks (upgrades) applied at the block numbers at which you apply them. Ethash/Clique is the consensus setting, whether you want PoW or PoA. You can possibly use `puppeth` to generate a genesis for you. You can read about the checkpoint oracle here: https://github.com/ethereum/go-ethereum/tree/master/cmd/checkpoint-admin

All in all I don't recommend editing the source files as it will lead to you having to maintain a fork of Geth. Geth can handle private networks by loading a genesis config (see `puppeth` to generate it) and running a private network like that.
