### ISSUE TITLE
ethclient.SendTransaction hangs indefinitely, transaction is not broadcast until node is restarted

### ISSUE THREAD

**Issue by RaghavSood** [ethereum/go-ethereum#21684]
#### System information

Geth version: 1.9.13-stable
OS & Version: Linux
Commit hash: 1.9.13 release build 

#### Expected behaviour

Calling SendTransaction results in the transaction being broadcast, and transaction hash being returned

#### Actual behaviour

The transaction is not broadcast, and the call hangs indefinitely

I believe this might be linked to the state clean up procedures - the same node was able to broadcast transactions just fine about 24 hours ago, and starting having this issue around 16 hours ago. The logs contain messages such as:

```
Deleted state snapshot leftovers         kind=accounts wiped=104546 elapsed=1m25.876s
Compacting snapshot account area
Wiper running, state snapshotting paused
```

The deletion and wiper messages indicated `elapsed` times of several hours (which is not an issue, I'd expect that given that this is an archival node)

If I restart the node, I receive the submission messages (outlined below) for all the SendTransaction calls that are currently pending:

```
Submitted transaction                    fullhash=txid recipient=destination
```

After those messages in the logs, the transactions are still not broadcast - the node shuts down, and the transactions are sent to the network only after it starts again.

Once restarted, the SendTransaction call works fine for a minute or two, after which is starts demonstrating the same behaviour.

Throughout all this, other calls over the same ethclient+websocket endpoint continue to work fine - I am able to receive new chain heads, get transaction receipts, get account balances/nonces without any additional delays or issues.

Even before the `Submitted transaction` log messages are created, if I try and resend a stuck transaction via the `geth attach` console, it says the tx is already known - however, it is not broadcast into the network until after a restart, and the original SendTransaction call remains stuck

#### Steps to reproduce the behaviour

Try and broadcast a transaction with a node exhibiting the above behaviour, possibly caused by snapshot cleanup.

#### Backtrace

N/A, the node does not crash

**Comment by RaghavSood** [comment]
The node now appears to be regeneration state snapshots:

```
INFO [10-10|05:33:37.493] Aborting state snapshot generation       at=004ee6…4f717c accounts=123825 slots=890805 storage=69.41MiB  elapsed=34m5.704s  eta=471h25m56.083s
INFO [10-10|05:33:37.494] Resuming state snapshot generation       at=004ee6…4f717c accounts=123825 slots=890805 storage=69.41MiB  elapsed=34m5.704s  eta=471h25m56.083s
```

These messages show up every 30-40 seconds, always in quick succession - the eta started at a couple of days, and has moved up to around 20 days now.

Transaction broadcasting still hangs indefinitely.

**Comment by karalabe** [comment]
Please update your node to a recent release. We're constantly doing bugfix releases and there's a high chance your issue is already solved. We're 10 releases ahead of your node.

**Comment by RaghavSood** [comment]
Closing for now as an upgrade does seem to have fixed it
