### ISSUE TITLE
ethclient using HeaderByNumber and BlockByNumber return error "missing required field 'miner' for Header"

### ISSUE THREAD

**Issue by luizaclima2020** [ethereum/go-ethereum#21696]
Hi there,

I tried to get information for a pending block (blockNumber -1) and the result was "missing required field 'miner' for Header". 

The problem is on type definition for struct Header; the 'miner' is set 'required', but retrieving information for pending block this field is null.

```
// Header represents a block header in the Ethereum blockchain.
type Header struct {
	ParentHash  common.Hash    `json:"parentHash"       gencodec:"required"`
	UncleHash   common.Hash    `json:"sha3Uncles"       gencodec:"required"`
	Coinbase    common.Address `json:"miner"            gencodec:"required"`
	Root        common.Hash    `json:"stateRoot"        gencodec:"required"`
	TxHash      common.Hash    `json:"transactionsRoot" gencodec:"required"`
	ReceiptHash common.Hash    `json:"receiptsRoot"     gencodec:"required"`
	Bloom       Bloom          `json:"logsBloom"        gencodec:"required"`
	Difficulty  *big.Int       `json:"difficulty"       gencodec:"required"`
	Number      *big.Int       `json:"number"           gencodec:"required"`
	GasLimit    uint64         `json:"gasLimit"         gencodec:"required"`
	GasUsed     uint64         `json:"gasUsed"          gencodec:"required"`
	Time        uint64         `json:"timestamp"        gencodec:"required"`
	Extra       []byte         `json:"extraData"        gencodec:"required"`
	MixDigest   common.Hash    `json:"mixHash"`
	Nonce       BlockNonce     `json:"nonce"`
}
```
#### System information

Geth version: Geth/v1.9.22-stable-c71a7e26/linux-amd64/go1.15
OS & Version: OSX
Commit hash : none

#### Expected behaviour

Return of block pending information

#### Actual behaviour

"missing required field 'miner' for Header"

#### Steps to reproduce the behaviour

	var blknum *big.Int

	conn, err := ethclient.Dial(ipc)
	if err != nil {
		return fmt.Errorf("Failed to connect to the Ethereum client: %v", err)
	}

	defer conn.Close()

	if len(blkstr) > 0 {
		blknum = new(big.Int)
		blknum.SetString(blkstr, 0)
	}

	header, err := conn.HeaderByNumber(context.Background(), blknum)
	if err != nil {
		log.Fatal(err)
	}

	blockNumber := big.NewInt(header.Number.Int64())
	block, err := conn.BlockByNumber(context.Background(), blockNumber)
	if err != nil {
		log.Fatal(err)
	}

#### Backtrace

````
````

**Comment by holiman** [comment]
Yes, there are actually three fields being droppped for `pending` block
```golang
		if number == rpc.PendingBlockNumber {
			// Pending header need to nil out a few fields
			for _, field := range []string{"hash", "nonce", "miner"} {
				response[field] = nil
			}
		}
```

**Comment by luizaclima2020** [comment]
> Yes, there are actually three fields being droppped for `pending` block
> 
> ```go
> 		if number == rpc.PendingBlockNumber {
> 			// Pending header need to nil out a few fields
> 			for _, field := range []string{"hash", "nonce", "miner"} {
> 				response[field] = nil
> 			}
> 		}
> ```

BTW, I think that problem is at file go-ethereum/core/types/gen_header_json.go when getting pending block:

	if dec.Coinbase == nil {
		return errors.New("missing required field 'miner' for Header")
	}
	h.Coinbase = *dec.Coinbase

**Comment by MariusVanDerWijden** [comment]
This has been fixed at some point, the field 'miner' is not required anymore
