### ISSUE TITLE
invalid merkle root error while change config in unit test

### ISSUE THREAD

**Issue by strongpower** [ethereum/go-ethereum#21694]
I'm doing `go test` for `core/blockchain_test.go`, when I changed [TestChainConfig](https://github.com/ethereum/go-ethereum/blob/master/params/config.go#L251) in `prarams/config.go`, more specific speak, I changed `ByzantiumBlock` from `big.NewInt(0)` to `big.NewInt(1)`, and other fields like `ConstantinopleBlock ` and `PetersburgBlock `. 
Some test cases in `blockchain_test.go` (e.g: `TestFastVsFullChains`) fails with error:
```
failed to process block 0: invalid merkle root (remote: 7d390f1b910e5da714bb029167ca9a67a0495f6e6d3624aa5806945e8945cdc4 local: 2d1d708f4aa049f491757eea5031b8c1eefa93dd5c9bcc60741de767f8d4c4f2)
```

Why use `0` as height for `ByzantiumBlock`, `ConstantinopleBlock` and other fork height in Test? Why couldn't use a none-zero value?

#### System information

Geth version: `geth 1.9.22`
OS & Version: OSX

#### Steps to reproduce the behaviour
1. change `TestChainConfig`
```
TestChainConfig = &ChainConfig{big.NewInt(1), big.NewInt(0), nil, false, big.NewInt(0), common.Hash{}, big.NewInt(0), big.NewInt(0), big.NewInt(1), big.NewInt(0), big.NewInt(0), big.NewInt(30), nil, nil, nil, new(EthashConfig), nil}
```

2. go test it
```
go test -timeout 30s github.com/ethereum/go-ethereum/core -run ^TestFastVsFullChains$ -v
```

**Comment by holiman** [comment]
If you change the byzantiumblock from `0` to `1`, it means that you are activating byzantium rules one block later. So when importing block `0`, byzantium is not active. And that leads to a different stateroot when executing the transactions. Thus, when the calculated stateroot is compared to the stateroot that the block header "claims", we find that "nope, this block/header doesn't produce the stateroot that it says it does", and we reject it. 


> Why use 0 as height for ByzantiumBlock, ConstantinopleBlock and other fork height in Test? Why couldn't use a none-zero value?

We could, but then the tests would have to be regenerated with different expectations.

**Comment by strongpower** [comment]
Now I get the point, thanks for reply~
