### ISSUE TITLE
undefined: abi.ConvertType

### ISSUE THREAD

**Issue by jeyldii** [ethereum/go-ethereum#21702]
Hi there,

I want to use abigen, but in generated pkg i haven't got ConvertType func. In master branch i see this func. How can i resolve this problem?

#### System information

Geth version: `1.9.20`
OSX Catalina 10.15.5

#### Expected behaviour
out0 := *abi.ConvertType(out[0], new(common.Address)).(*common.Address)

#### Actual behaviour
undefined: abi.ConvertType

#### Steps to reproduce the behaviour
Maybe i should use another version?

#### Backtrace

````
[undefined: abi.ConvertType]
````

**Comment by MariusVanDerWijden** [comment]
Hey @jeyldii, I recently changed the api a bit for abigen. You have two options, either you downgrade abigen or you upgrade geth to an unstable version. See: https://github.com/ethereum/go-ethereum/issues/21644
We will push a new release soon

**Comment by gballet** [comment]
@jeyldii the new version is out, could you please check if the problem still exists with the new version of abigen?

**Comment by jeyldii** [comment]
@gballet hey, 
i installed geth-alltools-darwin-amd64-1.9.22-c71a7e26 at the moment of reply from @MariusVanDerWijden and it works

**Comment by JGcarv** [comment]
Hi!

I'm getting this same issue again using geth-alltools-linux-386-1.10.0-unstable-bf5b379b!

**Comment by hmajiaqi** [comment]
现在您的问题解决了吗 我也遇到同样问题 abigen版本abigen version 1.10.1-unstable
