### ISSUE TITLE
Document: Web3b is a probably a wrong value

### ISSUE THREAD

**Issue by chiro-hiro** [ethereum/go-ethereum#21711]
I think, this line in document is probably wrong:

https://github.com/ethereum/go-ethereum/blame/gh-pages/docs/_rpc/server.md#L41

```
geth --http --http.api personal,eth,net,web3b
```

I've been received this error message:

```
ERROR[10-16|06:34:16.552] Unavailable modules in HTTP API list     unavailable=[web3b] available="[admin debug web3 eth txpool personal ethash net les lespay]"
```

It's `web3` not `web3b`.

**Comment by gballet** [comment]
yup, it should be `web3`, thanks for pointing this out.

**Comment by gballet** [comment]
Fixed, it will be updated during the next redeploy. Thanks!
