### ISSUE TITLE
Eth contract address transfer

### ISSUE THREAD

**Issue by HYHRainman** [ethereum/go-ethereum#21712]
![image](https://user-images.githubusercontent.com/19492741/96222247-7f5df900-0fbe-11eb-87a3-ba3c91e6c836.png)

I use eth_getTransactionReceipt to get the transaction details, but the logs object has no specific data.
["logs"]=>
  array(1) {
    [0]=>
    array(9) {
      ["address"]=>
      string(42) "0x35c96c1e2c25616797fafd5f9a5b78193e38a313"
      ["topics"]=>
      array(1) {
        [0]=>
        string(66) "0x442e715f626346e8c54381002da614f62bee8d27386535b2521ec8540898556e"
      }
      ["data"]=>
      string(130) "0xffb7d379f6e0ae2473447df17324b03460456d822ce03391b0696efbe13d3e590000000000000000000000000000000000000000000000000000000000000000"
      ["blockNumber"]=>
      string(8) "0xa56118"
      ["transactionHash"]=>
      string(66) "0x5fb6b4914cf2a21aee22a5f558753f09e58279c0e0f31efecad79b43bc11f4ee"
      ["transactionIndex"]=>
      string(4) "0x50"
      ["blockHash"]=>
      string(66) "0x77972defbf5be2d952bd791f8d30fb51a2b7c135146f5f0b521cdd824f99828b"
      ["logIndex"]=>
      string(4) "0xd0"
      ["removed"]=>
      bool(false)
    }
  }

Is there any other way to read the redlined data

**Comment by gballet** [comment]
It seems that `eth_getTransaction` is what you are looking for.
