### ISSUE TITLE
prometheus goerli and the scrape config hell, thanks to /debug/metrics

### ISSUE THREAD

**Issue by ChuckNorrison** [ethereum/go-ethereum#21721]
Hi there,

after several hours of configs and params in geth application, i was not able to get your special metrics_path (/debug/metrics) work together with a default metrics path (/metrics) from another client.

#### Expected behaviour
just use /metrics as everybody do

#### Actual behaviour
special metrics path to get maximum of user depressions on config hells

#### Steps to reproduce the behaviour
just setup geth --goerli and lighthouse metrics from several machines to a single grafana instance

**Comment by ChuckNorrison** [comment]
to get this solved you need to add another scrape_config to the prometheus.yml with a file path to a new scrape_config.json and with the special metrics_path /debug/metrics. A lot of fun if used in a docker compose and this guy dont want  to read the second scrape json. Makes me mad, just cause one guy thought it would be useful to change some defaults for fun

**Comment by ChuckNorrison** [comment]
i will close that, seems this will not change. Users which get aware of this could help here with a tutorial how to grafana with goerli together with another prometheus scrape target

**Comment by ChuckNorrison** [comment]
i will close that, seems this will not change. Users which get aware of this could help here with a tutorial how to grafana with goerli together with another prometheus scrape target

**Comment by ChuckNorrison** [comment]
This is related to that: https://github.com/prometheus/prometheus/issues/1852

**Comment by holiman** [comment]
I've read the text you wrote, apparently in anger, and I still don't quite understand what the original problem is/was, or what " useful to change some defaults for fun" refers to, or why you say "seems this will not change.". 

If our metrics are exposed in a non-standard way, which for some reason is 'wrong', then by all means open a ticket which describes the problem and what could be done to make it better.

**Comment by ChuckNorrison** [comment]
The issue is caused by prometheus and `scrape_configs` so this repo was not the right place. If prometheus scrape_configs would work as documented this special metrics_path of geth --goerli would have worked. 

it was just annoying to not get it up and running cause this metric_paths was changed at geth to `/debug/metrics` without possibility to parameterize, which is called "uncommon" for prometheus.

thanks for your reply, i still try to push those repos, even my language could be more clear. At this point i got all informations i was missing and closed it.
