### ISSUE TITLE
 batch transfer tokens examples

### ISSUE THREAD

**Issue by emmeair** [ethereum/go-ethereum#21729]
### Hi everyone , Is there any related examples of golang batch transfer tokens for reference, I haven't found it for a long time.

**Comment by MariusVanDerWijden** [comment]
Batch transfers are not a feature of ethereum itself. If you want to interact with a smart contract that allows for batch token transfers you can use abigen to generate golang bindings to the contract. I've written a reference for it here: https://medium.com/coinmonks/web3-go-part-1-31c68c68e20e
