### ISSUE TITLE
Problem with Ethereum transaction

### ISSUE THREAD

**Issue by Peppeblog** [ethereum/go-ethereum#21737]
hi,with this fields i have this error code:ValueError: {'code': -32000, 'message': 'insufficient funds for gas * price + value'}
Thanks for help,guys.  
  signedTx = w3.eth.account.signTransaction(dict(
        #chainId=3,
        nonce=nonce,
        gasPrice=gasPrice,
        gas=15000,
        to='0x0000000000000000000000000000000000000000',
        value=value,
        data=message.encode('utf-8')
    ), PrivateKey)
    tx = w3.eth.sendRawTransaction(signedTx.rawTransaction)
    txId = w3.toHex(tx)
    return txId

**Comment by karalabe** [comment]
I mean, it's pretty obvious: `insufficient funds for gas * price + value`: the account doesn't have enough funds to cover the transaction.

**Comment by Peppeblog** [comment]
I try to take eth,but he didnt work

**Comment by Peppeblog** [comment]
How much should i take?
