### ISSUE TITLE
debug_traceBlockByNumber method with callTracer tracer is hanging on 1 block (block 11092712  (0xA942E8))

### ISSUE THREAD

**Issue by ellemouton** [ethereum/go-ethereum#21732]
Hi, I am using the 'debug_traceBlockByNumber' endpoint with the "callTracer" tracer. It has been running smoothly so far except that for that it hangs when called for block 11092712  (0xA942E8). The block is not particularly large and the call has been working for all other blocks. I have also called it with a long timeout of 100s. I have tried the call many times and all produce the same result. Any ideas what the problem may be?

#### Expected behaviour
Expect the block calls to be returned

#### Actual behaviour
The call times out.

#### Steps to reproduce the behaviour
Call geth with the following: 

'{"method":"debug_traceBlockByNumber","params":["0xA942E8", {"tracer": "callTracer", "timeout":"100s"}],"id":1,"jsonrpc":"2.0"}'

**Comment by holiman** [comment]
You could do a `debug_standardTraceBlockToFile` on that block, then we'd be able to get a better understanding of exactly what the txs in the block are doing, if you upload them somewhere?
