### ISSUE TITLE
when I invoke txpool_content,something is wrong

### ISSUE THREAD

**Issue by macchain** [ethereum/go-ethereum#21731]
```golang
func (c *Client) TxPoolContent() (map[string]map[string]map[string]interface{}, error) {
	var result map[string]map[string]map[string]interface{}
	err := c.client.Call(&result, "txpool_content", nil)
	return result, err
}
```
the err is "err: too many arguments, want at most 0"

#### System information

Geth version: `geth version`
OS & Version: OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
Just don't send the argument
```
	err := c.client.Call(&result, "txpool_content")
```
?

**Comment by karalabe** [comment]
The `txpool_content` method takes no argument, but you sent a `nil` along. Just drop the last argument. It's variadic.
