### ISSUE TITLE
[private net] Can't open RPC on unlocked account, can't deploy contract on a locked account

### ISSUE THREAD

**Issue by 1337SEnergy** [ethereum/go-ethereum#21734]
alright, so, I have no idea how this is designed, but:
1. I'm running private PoA chain
2. I have to open geth node with unlocked account in order to actually mine new blocks
3. if I open a geth node with unlocked account, I have to disable IPC/RPC
4. if I have disabled IPC/RPC, I can't connect via remix to deploy the contract, because it requires unlocked account

so, how am I actually supposed to work with this?

**Comment by ligi** [comment]
One solution I see is to have 2 nodes running:
 * one mining blocks with unlocked account and closed RPC
 * one just syncing the chains with an open RPC and no unlocked account

does this work for you or is your chain so heavy that running 2 nodes is a problem?

**Comment by 1337SEnergy** [comment]
> One solution I see is to have 2 nodes running:
> 
> * one mining blocks with unlocked account and closed RPC
> * one just syncing the chains with an open RPC and no unlocked account
> 
> does this work for you or is your chain so heavy that running 2 nodes is a problem?

that's exactly the problem, in order to use remix, the account on the node has to be unlocked [to sign TXs] AND have enabled RPC [to let the remix actually connect]

I was, in fact, originally using unlocked account on a mining node and another node for RPC/WS connection, but that node can't be used to deploy contracts via remix, as it has to have unlocked account

**Comment by holiman** [comment]
You _can_ use 
```
  --allow-insecure-unlock             Allow insecure account unlocking when account-related RPCs are exposed by http
```

**Comment by karalabe** [comment]
Your options are

- Explicitly allow unlocking accounts at the risk of remote attacks. If you know you have a private ephemeral network, it should be fine. This is @holiman's suggestion above.
- Use IPC instead of HTTP as that permits unlocking accounts.
- Run a separate miner and API node, connected via devp2p, one can mine, the other just serves requests.

A fourth would be `--dev`, which unlocks the miner by default.

**Comment by 1337SEnergy** [comment]
@ligi I don't think this should be close -, yes, I can use --allow-insecure-unlock, but how do you imagine doing this on a mainnet? you don't want an unlocked account with remote access enabled... but you need an unlocked account in order deploy contracts via remix... the whole design behind this is flawed

> Your options are
> 
> * Explicitly allow unlocking accounts at the risk of remote attacks. If you know you have a private ephemeral network, it should be fine. This is @holiman's suggestion above.
> * Use IPC instead of HTTP as that permits unlocking accounts.
> * Run a separate miner and API node, connected via devp2p, one can mine, the other just serves requests.
> 
> A fourth would be `--dev`, which unlocks the miner by default.

@karalabe 
1. after moving this to the mainnet, I can't have unlocked account and RPC open, how could I solve this?
2. as far as I understand it, RPC [what I assume you meant by http in this case] is a form of IPC... and remix either uses "web3 provider" with RPC connection, or "injected web3"... there's no information - neither on the remix website nor in docs on how to connect it via other means using IPC
3. the problem is not really how to mine - when running on mainnet, there will not be a mining node as it's not using PoA, the problem is that the node that connects to remix has to have RPC enabled, but in order for geth to actually sign TXs, it has to have unlocked account, which is a security risk
4. again, this is not really an issue with mining

ignore the fact that I am currently testing on private PoA net, but imagine you're running a full mainnet geth node, and you want to connect a remix to it...
1. you enable RPC, so remix can connect
2. you try to unlock the account, but it gives you an error saying that you can't do that with RPC enabled, as it's a security risk
3. you restart the node with --allow-insecure-unlock
4. your ETH gets stolen while you deploy and work with the contract

or how does it actually work? I don't want to use MetaMask, but actually have an account as a keystore file that I can move around and my own node

**Comment by beyonderyue** [comment]
Maybe remix is just for debugging contract...So please don't use remix on your mainnet geth node.

**Comment by 1337SEnergy** [comment]
> Maybe remix is just for debugging contract...So please don't use remix on your mainnet geth node.

alright, then what do you use when you work with SCs, when you say that the probably most feature-full IDE is "just for debugging" ?
is the IDE you're using not connecting to the node via RPC?
how do you deploy contract via your own node? do you not send the compiled bytecode to the node via RPC, or however that actually works behind the scenes?
if so, then how do you actually send the bytecode to the geth node and sign the deployment TX, if you do not have both, RPC enabled and account unlocked?
keep in mind that - for your pleasure - I am omitting the remix now, let's say I have compiled bytecode I want to deploy - I assume I have to send that bytecode to the node via RPC/IPC call, and sign the TX with an unlocked account... well, that's not possible, because having an unlocked account with open RPC/IPC is a security risk
so... how do you actually do that?

**Comment by beyonderyue** [comment]
> > Maybe remix is just for debugging contract...So please don't use remix on your mainnet geth node.
> 
> alright, then what do you use when you work with SCs, when you say that the probably most feature-full IDE is "just for debugging" ?
> is the IDE you're using not connecting to the node via RPC?
> how do you deploy contract via your own node? do you not send the compiled bytecode to the node via RPC, or however that actually works behind the scenes?
> if so, then how do you actually send the bytecode to the geth node and sign the deployment TX, if you do not have both, RPC enabled and account unlocked?
> keep in mind that - for your pleasure - I am omitting the remix now, let's say I have compiled bytecode I want to deploy - I assume I have to send that bytecode to the node via RPC/IPC call, and sign the TX with an unlocked account... well, that's not possible, because having an unlocked account with open RPC/IPC is a security risk
> so... how do you actually do that?

Actually， I use web3j for deploying and using the contract, and it sends signed raw transaction to the node, so I don't need unlock the account.

**Comment by 1337SEnergy** [comment]
> > > Maybe remix is just for debugging contract...So please don't use remix on your mainnet geth node.
> > 
> > 
> > alright, then what do you use when you work with SCs, when you say that the probably most feature-full IDE is "just for debugging" ?
> > is the IDE you're using not connecting to the node via RPC?
> > how do you deploy contract via your own node? do you not send the compiled bytecode to the node via RPC, or however that actually works behind the scenes?
> > if so, then how do you actually send the bytecode to the geth node and sign the deployment TX, if you do not have both, RPC enabled and account unlocked?
> > keep in mind that - for your pleasure - I am omitting the remix now, let's say I have compiled bytecode I want to deploy - I assume I have to send that bytecode to the node via RPC/IPC call, and sign the TX with an unlocked account... well, that's not possible, because having an unlocked account with open RPC/IPC is a security risk
> > so... how do you actually do that?
> 
> Actually， I use web3j for deploying and using the contract, and it sends signed raw transaction to the node, so I don't need unlock the account.

you need to sign that TX first, and you can't sign a TX with locked account... that's the point of unlocking the account first
I assume you'll claim next that you have exported privkey and are using that to sign the TX, which, again, is not what this issue is about, as geth can't export privkeys, nor I'd want to, since, as mentioned already, I want to use the encrypted keystore that I can actually move

**Comment by beyonderyue** [comment]
> > > > Maybe remix is just for debugging contract...So please don't use remix on your mainnet geth node.
> > > 
> > > 
> > > alright, then what do you use when you work with SCs, when you say that the probably most feature-full IDE is "just for debugging" ?
> > > is the IDE you're using not connecting to the node via RPC?
> > > how do you deploy contract via your own node? do you not send the compiled bytecode to the node via RPC, or however that actually works behind the scenes?
> > > if so, then how do you actually send the bytecode to the geth node and sign the deployment TX, if you do not have both, RPC enabled and account unlocked?
> > > keep in mind that - for your pleasure - I am omitting the remix now, let's say I have compiled bytecode I want to deploy - I assume I have to send that bytecode to the node via RPC/IPC call, and sign the TX with an unlocked account... well, that's not possible, because having an unlocked account with open RPC/IPC is a security risk
> > > so... how do you actually do that?
> > 
> > 
> > Actually， I use web3j for deploying and using the contract, and it sends signed raw transaction to the node, so I don't need unlock the account.
> 
> you need to sign that TX first, and you can't sign a TX with locked account... that's the point of unlocking the account first
> I assume you'll claim next that you have exported privkey and are using that to sign the TX, which, again, is not what this issue is about, as geth can't export privkeys, nor I'd want to, since, as mentioned already, I want to use the encrypted keystore that I can actually move

Web3j can use the encrypted keystore directly if you want, so you don't need exported the privkey.  And if you don't want to use other tools, maybe you can ask help under remix project..

**Comment by 1337SEnergy** [comment]
bruh, please stop, you're just spamming here at this point, diminishing the actual chances of getting a reply from someone who actually can help me... this has nothing to do with remix really, I can compile the contract into bytecode in remix and then export that, which does not require connection to the node at all... what I need geth for is I need to send the compiled bytecode to the geth (via RPC) and let it sign it (but that requires unlocked account)

the point is that I need to get that bytecode into the geth, and let geth sign it INSTEAD of using yet another tool to sign it outside of geth... (like you and your web3j)

you're using web3j to sign transactions, which should be obvious to you, I need to use geth to sign the transaction

you obviously do not understand the point of this issue, regardless of how much time I spent trying to explain it to you, so please just stop

**Comment by karalabe** [comment]
@1337SEnergy You don't need to unlock an account to send a transaction though. You can use `personal_sendTransaction`, which is essentially the same as `eth_sendTransaction` but takes a second parameter - the account passphrase. That should always be preferred over unlocking an account because that way the key doesn't stay in memory, it's just decrypted, used for a single signature and discarded.
