### ISSUE TITLE
Insufficient funds error when sending entire balance.

### ISSUE THREAD

**Issue by tjade273** [ethereum/go-ethereum#2173]
When attempting to send an account's entire balance, geth returns `error: Insufficient funds for gas * price + value`

The command used was 

```
eth.sendTransaction( {
    from: eth.coinbase,
    to: eth.accounts[1],
    value: eth.getBalance(eth.coinbase)-21000*50000000000,
    gas: 21000,
    gasPrice: 50000000000
})
```

Looks like there's a `<=` instead of `<` somewhere in the code where the balance is checked.

**Comment by karalabe** [comment]
I think this might actually be a JavaScript rounding error. JS uses 64 bit floats to represent integers (wtf?), which means that anything greater than [2^53 - 1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) (which is about 0.01 ETH) will be rounded, up or down.

It might be interesting to check if you calculate the sweep transaction and feed it to the RPC/IPC directly and not through the console.

PS: Here's the code that checks the total account balance and it seems correct to me: https://github.com/ethereum/go-ethereum/blob/master/core/transaction_pool.go#L220.

**Comment by obscuren** [comment]
@tjade273 could you check with strings and report back, please?

**Comment by tjade273** [comment]
Ah, that was the issue. `eth.getBalance(eth.coinbase)-21000*50000000000` causes rounding in the JS console. When I do the calculation manually, and use all strings, it works as expected. Thanks :)

**Comment by karalabe** [comment]
I'll leave this open for now until we figure out a solution. This shouldn't really happen.

**Comment by fjl** [comment]
We could change the JS VM to throw on overflow. Does this sound like a good solution to you?

**Comment by karalabe** [comment]
As long as it doesn't silently fail, fine by me :)

**Comment by fjl** [comment]
@bas-vk just mentioning you here so you're aware of this issue.

**Comment by gGololicic** [comment]
How about internally using decimal.js and treating number as strings so rounding does not happen?

**Comment by karalabe** [comment]
Actually we were considering treating all constants as big ints in the console. It probably will be the route taken.

**Comment by gituser** [comment]
I'm having same error, whilst trying to empty the balance.

If balance was deducted let's say by 1 wei, it's impossible to send all what was left:

e.g. balance like: 11.999579999999999999 ether

I can't move whole balance from one account to another, geth always gives me:
error: Insufficient funds for gas * price + value.

Of course I substract gas*gasPrice, gas: 21000, gasPrice: 20000000000

So I need to move 44999159999999999996 wei out of 44999579999999999996 wei.

Any idea why this is happening? 

Running Geth/v1.3.5-506c9277/linux/go1.4.2

**Comment by karalabe** [comment]
It is a JavaScript rounding error: https://github.com/ethereum/go-ethereum/issues/2173#issuecomment-180276148

JavaScript cannot handle these numbers with a high enough precision, so it rounds it in some direction, and if the rounding is upward, then all of a sudden the amount requested to be sent goes over your balance. I can't give you a clean solution/workaround though, apart from using a bignumber library to handle the conversions. We planned to hook bignums into our console, alas it's fairly low priority compared to other issues.

**Comment by gituser** [comment]
@karalabe, I pass these values directly to RPC without any javascript calculations.

Sometimes it works, sometimes not. Usually it's not working for numbers like I gave as an example, when there is simple wei involved.

So I guess there is a problem inside geth binary?

**Comment by karalabe** [comment]
The RPC layer expects numbers to be hex encoded (https://github.com/ethereum/wiki/wiki/JSON-RPC#output-hex-values). I'm not sure how Geth 1.3.x decoded these numbers, maybe it was a bit lax, but 1.4.x should be a lot stricter in this regard. Please try with hex and report back if there's still an error. Also please tell us the exact RPC payload you send to the server.

**Comment by gituser** [comment]
@karalabe I've tried converting to hex with bc: it gave me this number: 0x323953746249706848754070
tried once again, but still the same error there.

**Comment by karalabe** [comment]
`0x323953746249706848754070` is `15543553366107993512269398128` decimal.

**Comment by gituser** [comment]
@karalabe 
yes, it was my mistake, i set ibase in bc instead of obase, but it doesn't help:

``
./geth --exec "eth.sendTransaction({from:'0xXXXX', to:'0xXXX', value: 0x2707D219AAEF77FFC, gas:0x5208});" attach
error: Insufficient funds for gas * price + value
``

**Comment by karalabe** [comment]
* Please put the hex into quotes. 
 * Please make even number of digits (the value is invalid, has odd number of digits)
 * You might want to explicitly specify the gas price (20 gwei) as the node may propose a higher amount if there are many transactions

**Comment by gituser** [comment]
@karalabe, finally it's worked!

So for others who encounter this issue here is how to use this:

Convert all values to hex (with bc if you use bash) and pass them to RPC / console:

``
./geth --exec "eth.sendTransaction({from:'0x123456', to:'0x123456', value: '0x8AC4270ACC4B7FF7', gas: '0x5208', gasPrice: '0x4A817C800'});" attach
``

**Comment by sjStefan** [comment]
@karalabe As well as @gituser as don´t get this sentence:

> Please make even number of digits (the value is invalid, has odd number of digits)

Do you mean, the hex or the dec-representation needs an even number of digits?

In my case I'm trying to empty an address which owns 1 ETH.

The details for the transaction look like this:

- gasPrice: '27221063327' in wei
- gas: '21000'
- value: '999428360000000000' in wei

Converted to hex all of this looks like this:
- gasPrice: '0x65680769f'
- gas: '0x5208'
- value: '0xddeaecc58405000' 

The error which occurs, while trying to send the transaction, looks like:

> Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 1000000002329867000 and got: 1000000000000000000

I had explicitly specified the gas price and quoted the hex values.

Are you sure the number of digits has to be even? Or does it not make more sense, that that number (or the last digit) has to be even?

And does this mean, I won't be able to completely empty an account, if the error occurs and I'll alter the numbers or number of digits to still send the transaction?

BTW: I'm using parity for sending the ether and not geth. Does that make any difference in terms of the reason for the error?

Thanks in advance.

**Comment by karalabe** [comment]
How are you trying to send these funds? Geth most certainly doesn't have these type of error messages.

**Comment by karalabe** [comment]
> BTW: I'm using parity for sending the ether and not geth. Does that make any difference in terms of the reason for the error?

Erm, then please open an issue on their reporitory. This is go-ethereum, not Parity.

**Comment by milledragon** [comment]
Hello, everyone. I also encounter this problem.

My geth VERSION:
   1.7.3-stable-4bb3c89d

c:\Geth>geth --datadir "c:\Geth\Chain\node1" console

......

> eth.getBalance(eth.accounts[0])
1.39e+21

> eth.sendTransaction({from:eth.accounts[0], to:eth.accounts[1], value: '0x1d6f347d9f77b4', gas: '0x5208', gasPrice: '0x0BA43B7400'})
Error: insufficient funds for gas * price + value
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

**Comment by HeDeHeng** [comment]
@karalabe 
> eth.getBalance(eth.accounts[0])


550000000000000000000
> web3.fromWei(eth.getBalance(eth.accounts[0]))


550
> eth.sendTransaction({from:'0xa38f5c0630d17b30895647d782d1b46bbc76f5cf', to:'0x6b579b9dec30f74260d73c6b125989ffd13fac8c',value:'1000000000000000000', gas: '70000', gasPrice: '70000000000'})
Error: insufficient funds for gas * price + value
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

> eth.sendTransaction({from:'0xa38f5c0630d17b30895647d782d1b46bbc76f5cf', to:'0x6b579b9dec30f74260d73c6b125989ffd13fac8c',value:'0xde0b6b3a7640000', gas: '0x11170', gasPrice: '0x104c533c00'})
Error: insufficient funds for gas * price + value
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

why no use.TT

**Comment by CodeMath** [comment]
me too.

```
> eth.getBalance(eth.coinbase)
800000000000000000000

> eth.sendTransaction({from:eth.coinbase, to:eth.accounts[1], 
value:eth.getBalance(eth.coinbase)-21000*50000000000,gas: 21000,gasPrice: 50000000000})
Error: insufficient funds for gas * price + value
```

**Comment by HeDeHeng** [comment]
Resolved my problem after rebooting
