### ISSUE TITLE
(CPU) miner does not start

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/go-ethereum#2174]
I am using Version: 1.4.0-unstable (installed yesterday) on Ubuntu 14.04.3 LTS on a large exoscale.ch cloud machine.

Several times `miner.start(1)` is not responding, it is hard to reproduce but pops up regularly. Now it happened while geth was running (but not mining) and ssh crashed, I had to disconnect, just in case rebooted the machine. Then I started geth (as always) with `geth --genesis customGenesis.json --datadir dataDir --networkid 123 --nodiscover --maxpeers 0 --rpc --rpccorsdomain '*' --rpcaddr 0.0.0.0 --unlock 0x9b33ab4d5a2c575540dc667e28b3b9cb7a19ddc4 console` and then attempted to start mining (I know that exposing the rpc to the world is not a good idea, all for testing only)

```
> miner.start(1)
I0205 10:18:49.925763 eth/backend.go:415] Automatic pregeneration of ethash DAG ON (ethash dir: /root/.ethash)
I0205 10:18:49.925841 miner/miner.go:119] Starting mining operation (CPU=1 TOT=5)
I0205 10:18:49.926492 eth/backend.go:422] checking DAG (ethash dir: /root/.ethash)
true
> I0205 10:18:49.931465 miner/worker.go:570] commit new work on block 209 with 0 txs & 0 uncles. Took 5.240275ms
I0205 10:18:49.931640 ethash.go:220] Generating DAG for epoch 0 (size 1073739904) (0000000000000000000000000000000000000000000000000000000000000000)
I0205 10:18:51.686124 ethash.go:237] Done generating DAG for epoch 0, it took 1.754482029s
```

At that point it was stuck forever. It was not just an output issue, the miner was really not running, CPU load was minimal and I see tx piling up in `web3.eth.pendingTransactions`. After a while I figured that when doing `miner.stop(1)` and `miner.start(1)` it would eventually start mining. Alternatively, it was not sufficient to delete the entire dataDir, I had to also delete the .ethash folder and then initialize the DAG again. Also note that I had set my etherbase, defaultAccount (both same) and the account was also unlocked. Maybe somebody could look into this. Thanks!

**Comment by fraspadafora** [comment]
I confirm the same problem.

**Comment by jtobin** [comment]
I've observed this as well, as reported in [this Stack Exchange question](https://ethereum.stackexchange.com/questions/1658/mining-w-geth-on-private-network-hangs-indefinitely) I posted.

[This other question](https://ethereum.stackexchange.com/questions/743/getting-more-ether-on-a-private-test-net) I found also seems to reflect the same problem.

**Comment by fjl** [comment]
If any of you can reproduce this issue, please try the following:

* Start geth with `--pprof` in addition to your usual flags. You should probably just pass it all the time
  because the issue might not happen that time.
* When `miner.start` hangs:
* Open http://127.0.0.1:6060/debug/pprof/goroutine?debug=2 in your browser
* Upload the text there to a gist

This will let us see where exactly it is hanging.

**Comment by jtobin** [comment]
Halting / rebooting my Vagrant VM seemingly solved the problem for me - I haven't been able to reproduce the issue since.

**Comment by nickfierro** [comment]
I have the same problem. Output of pprof is at 
https://gist.github.com/nickfierro/105fcf9e996c52b4a93dc3035ce174b8

**Comment by VladWulf** [comment]
Had the same problem.
You just have to wait. And you might wait a couple of minutes because you gave it only thread.

The confusion comes from the fact that the console is prompting while it should show some loading.

**Comment by lilijreey** [comment]
I have same problem.
but a start node with --dev option is can mining.

**Comment by kazuuu** [comment]
@fjl 
https://gist.github.com/kazuuu/31cedabfd4ac6ac03104a77d6c03491c
The dag is finished, but it's not mining..

I did what you asked for.

Hope you can help us! :D

Best,

**Comment by ramboze** [comment]
Be sure to initialise geth with `geth init /path/to/custom_genesis.json` otherwise you're pointing to the in-built genesis block and not your genesis.json file.

Please let me know if this has solved your issue.

**Comment by karalabe** [comment]
This is an ancient thread, which is seriously outdated since the ethash rewrite in Geth 1.6.0. Please open a new thread if any issues persist.

**Comment by ysqi** [comment]
@fjl 
my debug   pprof info:
https://gist.github.com/ysqi/a2478295ad585295f71165e44facb585
but it's not mining...
my command ：
```shell
eth --identity "OneTestETH" --rpc --rpcport "8080" --rpccorsdomain "*" --datadir ./data01  --nodiscover --rpcapi "db,eth,net,web3"   --networkid 1999 --ipcpath $HOME/Library/Ethereum/geth.ipc  console
```
output:
```txt
INFO [09-08|20:00:19] Starting peer-to-peer node               instance=Geth/OneTestETH/v1.6.7-stable-ab5646c5/darwin-amd64/go1.9
INFO [09-08|20:00:19] Allocated cache and file handles         database=/ethprivate/data01/geth/chaindata cache=128 handles=1024
INFO [09-08|20:00:20] Initialised chain configuration          config="{ChainID: 15 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Metropolis: <nil> Engine: unknown}"
INFO [09-08|20:00:20] Disk storage enabled for ethash caches   dir=/ethprivate/data01/geth/ethash count=3
INFO [09-08|20:00:20] Disk storage enabled for ethash DAGs     dir=/Users/nerthus03/.ethash       count=2
INFO [09-08|20:00:20] Initialising Ethereum protocol           versions="[63 62]" network=1999
INFO [09-08|20:00:20] Loaded most recent local header          number=172 hash=6a67fe…92d93e td=23636229
INFO [09-08|20:00:20] Loaded most recent local full block      number=172 hash=6a67fe…92d93e td=23636229
INFO [09-08|20:00:20] Loaded most recent local fast block      number=172 hash=6a67fe…92d93e td=23636229
WARN [09-08|20:00:20] Blockchain not empty, fast sync disabled
INFO [09-08|20:00:20] Starting P2P networking
INFO [09-08|20:00:20] RLPx listener up                         self="enode://4f7c1599f792f99a71f002e4456790f841527c829e996b1044659abd2c0beb7a795cafa89270a29453883bac9dfa76633b62aeb653f3efc4a4dff46db7666873@[::]:30303?discport=0"
INFO [09-08|20:00:20] IPC endpoint opened: /Users/one/Library/Ethereum/geth.ipc
INFO [09-08|20:00:20] HTTP endpoint opened: http://127.0.0.1:8080
Welcome to the Geth JavaScript console!

instance: Geth/OneTestETH/v1.6.7-stable-ab5646c5/darwin-amd64/go1.9
coinbase: 0x8b81235dd838d3a92236ce854a753ee0c0260bf8
at block: 172 (Fri, 08 Sep 2017 15:19:18 CST)
 datadir: /ethprivate/data01
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> miner.start(2)
INFO [09-08|20:00:27] Updated mining threads                   threads=2
INFO [09-08|20:00:27] Transaction pool price threshold updated price=18000000000
INFO [09-08|20:00:27] Starting mining operation
null
> INFO [09-08|20:00:27] Commit new mining work                   number=173 txs=0 uncles=0 elapsed=132.085µs
```
then, delete DAG file ,and miner.start(2) is fine. create dag and mining.
```
rm -rf $HOME/.ethash
```
```txt
INFO [09-08|20:11:10] Generating DAG in progress               epoch=0 percentage=99 elapsed=1m49.077s
INFO [09-08|20:11:10] Generated ethash verification cache      epoch=0 elapsed=1m49.079s
INFO [09-08|20:11:15] Generating DAG in progress               epoch=1 percentage=0  elapsed=1.711s
INFO [09-08|20:11:16] Generating DAG in progress               epoch=1 percentage=1  elapsed=3.305s
INFO [09-08|20:11:18] Successfully sealed new block            number=173 hash=1e998f…ce5c89
INFO [09-08|20:11:18] 🔨 mined potential block                  number=173 hash=1e998f…ce5c89
INFO [09-08|20:11:18] Commit new mining work                   number=174 txs=0 uncles=0 elapsed=863.7µs
```

**Comment by AnamikaD** [comment]
@ysqi did you use any custom genesis file? I am getting the issue even after removing .ethash

**Comment by ysqi** [comment]
@AnamikaD yes, I use custom genesis file , work for private network.

**Comment by yyd106** [comment]
I'm facing the same issue too. This seems have not yet got a official fixing or update right?

**Comment by AnamikaD** [comment]
@ysqi Thank you for the reply!

**Comment by AnamikaD** [comment]
@yyd106 if you don't have genesis.block file you need to create that. Also use unlock account in your argument!

**Comment by yyd106** [comment]
@AnamikaD  I have did them in right way. You could also check my question [Could not start mining on my private chain](https://stackoverflow.com/questions/48106858/could-not-start-mining-on-my-private-chain) as well.

**Comment by AnamikaD** [comment]
@yyd106 I saw your question. It shouldn't be because of RAM / CPU. Since it is cloud, there might be other arguments. Also try unlocking account in the argument.
```
-- unlock account number

**Comment by yyd106** [comment]
@AnamikaD I'm just upgrade the env to 2cores+2GB RAM before I saw your answer. After the upgrading it is working fine now LOL. Thank you for the information as well.

**Comment by AnamikaD** [comment]
@yyd106 Lol nice! Good to know.

**Comment by AnamikaD** [comment]
@yyd106  I am facing a weird issue. I am not able to connect to peers in ( private )ethereum! Can you give me some pointers?

**Comment by yyd106** [comment]
@AnamikaD Please copy the genesis.json here and your env as well.

**Comment by wale3d** [comment]
Same issue :(

**Comment by Akhimlee** [comment]
i have problem and and this i cant undersstand, can help me ?

WARN [02-19|21:56:53] Skipping deep transaction reorg          depth=2048

**Comment by kggp1995** [comment]
Remove the .ethash/ folder, re-init the genesis file with proper JSON key-value semantics (values in hex to prevent any surprises!) and you can bootstrap geth as usual

**Comment by rednaxus** [comment]
So ...why is this closed?  Still an issue with 1.8.11

Consistently broken

**Comment by kggp1995** [comment]
cc @karalabe , should a new thread be created? 
As per my observation, removing the `~/.ethash` should work; in case there was a DAG created in superposition with another previous attempt.

**Comment by rednaxus** [comment]
Wow, this is frustrating...for more than a year, i have tried installing private server on many platforms and the mining never ever has worked properly...yet it seems like others are able to make it work... whole articles are written on it.   what's the real story?  Am I missing something?

Sometimes it helps to delete and rebuild the ethash...sometimes not...usually if i delete the whole datadir, i can mine again for a few times, then back at the same lockup.  Does this stuff work at all?

Am I just setting something wrong?  Or does nobody actually use this?

my current genesis.json:
    "config": {
        "chainId": 7,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "nonce": "0x0000000000000442",
    "timestamp": "0x00",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x00",
    "gasLimit": "0x8000000",
    "difficulty": "0x01",
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x5DFE021F45f00Ae83B0aA963bE44A1310a782fCC",

**Comment by tipu** [comment]
I'm suffering the same issues at @rednaxus, except after nuking all the datadir contents it's a hit and miss, after rebuilding everything, whether the mining happens.

**Comment by kggp1995** [comment]
@rednaxus , suggest you to create a new thread. Sorry to hear about the issue you're facing for this long time. I hope it gets fixed in another fresh issue as there is no response on this one 🤞

**Comment by SlightlyCyborg** [comment]
Same isue
