### ISSUE TITLE
why dose jsonrpc method eth_estimateGas is difference between true used on erc20 token 

### ISSUE THREAD

**Issue by RedheatWei** [ethereum/go-ethereum#21740]
Hi there,

I have a question that when I used jsonrpc method eth_estimateGas, I can get a value for gas used.
But this value is difference between ture used gas erc20 token .
For example: https://cn.etherscan.com/tx/0x006d44edb2d6d1641a0201acf53c138b04ed869ecf65b955ecb1bf8fddd9a4f6
This gas used is  51,373 , but use eth_estimateGas method, I'll get 36373.
Why it can be happen?'
Thanks of all.

**Comment by MariusVanDerWijden** [comment]
Estimate gas basically does what it says, it **estimates** the gas usage of a transaction. It always depends on the current state of the network. If the data in the contract changes, the gas usage might also change. For example if you modify a storage slot that wasn't modified before it costs more than changing a storage slot that was accessed previously. Additionally setting a storage slot to zero gives you a refund. Thus there are a lot of things that can change between estimating gas an sending the actual transaction. 

Does that answer your question? In the future please use the ethereum stackoverflow https://ethereum.stackexchange.com/
