### ISSUE TITLE
Yolov2 attempts to attach to path for yolov1 ipc

### ISSUE THREAD

**Issue by prestwich** [ethereum/go-ethereum#21748]
Seems to be a simple missed find+replace. I can prep a PR if you want.

#### Expected behaviour

Yolov2 ought to attach to the yolov2 `geth.ipc`

#### Actual behaviour

Yolov2 attempts to attach to the yolov1 datadir

```Fatal: Unable to attach to remote geth: dial unix /home/james/.ethereum/yolo-v1/geth.ipc```

Problem appears to be here:
https://github.com/ethereum/go-ethereum/blob/master/cmd/geth/consolecmd.go#L140

#### Steps to reproduce the behaviour

1. build and run latest master with `--yolov2`
2. `.build/bin/geth --yolov2 attach`

**Comment by holiman** [comment]
Yes please, that'd be great

**Comment by prestwich** [comment]
See #21749 👍
