### ISSUE TITLE
why it take so long time to sync?

### ISSUE THREAD

**Issue by bob2325168** [ethereum/go-ethereum#21741]
Hi there,

Geth version:  1.9.21-stable
OS & Version: Linux/
Commit hash : 0287d54847d3297f3ced62cd83a4c95ccbe0045b

_**it takes about a mouth and half to sync block data, but currentBlock is 6783693 for now（heighestBlock：11111799）. Actually, it's unormal. so how to handle this problem. please help me, thanks**_

`root@ipsbsuper:/home/ipsbsuper# geth attach rpc:http://localhost:8545
Welcome to the Geth JavaScript console!

instance: Geth/v1.9.21-stable-0287d548/linux-amd64/go1.15.1
coinbase: 0xb50970d977fe010dfb6f6759bb5c832a8ef0017b
at block: 6783690 (Tue Nov 27 2018 18:45:28 GMT+0000 (UTC))
 modules: eth:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> eth.syncing
{
  currentBlock: 6783693,
  highestBlock: 11111799,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 0
}
> 
`

**Comment by MariusVanDerWijden** [comment]
What is your hardware setup? Syncing on an HDD is super slow. You need an SSD, otherwise you will always be slower than the chain

**Comment by bob2325168** [comment]
uh, currently it's HDD for saving money.

**Comment by MariusVanDerWijden** [comment]
Unfortunately syncing with an HDD is not possible anymore as we need more iops than a HDD can provide. I know that turbogeth is trying to make hdd syncs possible but afaik they haven't succeeded either
