### ISSUE TITLE
with the same gas price ,which will be mining first

### ISSUE THREAD

**Issue by macchain** [ethereum/go-ethereum#21752]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by MariusVanDerWijden** [comment]
The one that was first received by the miner (as of lately). Before that it was randomly selected. For the future please use the stackexchange for questions like this
