### ISSUE TITLE
sometimes abi lengthprefixPointsTo has an unusual value and unpacking breaks 

### ISSUE THREAD

**Issue by fxfactorial** [ethereum/go-ethereum#21754]
reproduced in 1.9.21 and 1.9.23

I get this error occasionally coming from abigen made code 

```
issue abi: cannot marshal in to go slice: offset 34961168813970327555695277297180835388765524858413590296049745231963419050016 would go over slice boundary (len=32)
```

```
) call bigOffsetEnd.String()
> github.com/ethereum/go-ethereum/accounts/abi.lengthPrefixPointsTo() /home/edgar/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.23/accounts/abi/unpack.go:263 (hits goroutine(1):3 total:3) (PC: 0x7415ac)
Warning: debugging optimized function
Values returned:
	~r0: "34961168813970327555695277297180835388765524858413590296049745231963419050016"

   258:		bigOffsetEnd := big.NewInt(0).SetBytes(output[index : index+32])
   259:		bigOffsetEnd.Add(bigOffsetEnd, common.Big32)
   260:		outputLength := big.NewInt(int64(len(output)))
   261:	
   262:		if bigOffsetEnd.Cmp(outputLength) > 0 {
=> 263:			return 0, 0, fmt.Errorf("abi: cannot marshal in to go slice: offset %v would go over slice boundary (len=%v)", bigOffsetEnd, outputLength)
   264:		}
   265:	
   266:		if bigOffsetEnd.BitLen() > 63 {
   267:			return 0, 0, fmt.Errorf("abi offset larger than int64: %v", bigOffsetEnd)
   268:		}
```

the value of bigOffsetEnd is sometimes this huge value which maybe suggests overflow? 
this condition is raised and this error goes off `"abi: cannot marshal in to go slice` )

I have it happen randomly while quickly looping over many contracts and calling abigened method call - it makes me suspect something like maybe the unpack code is sharing a bytes buffer somewhere inadvertently ? (but nothing came up under -race)

**Comment by fxfactorial** [comment]
solved - $mkr deviates from other ERC20s and gives back bytes32 instead of string for its symbol and hence abigen exploded (it was build against erc20)

**Comment by MariusVanDerWijden** [comment]
I created this thingy here: https://github.com/ethereum/go-ethereum/pull/20645/files
Which would make it easy to catch errors like that, do you think that makes sense @fxfactorial

**Comment by fxfactorial** [comment]
@MariusVanDerWijden ya - looks useful!

**Comment by shixiaofeia** [comment]
my version github.com/ethereum/go-ethereum v1.10.13 ,  This problem still occurs, how to solve it?

**Comment by shixiaofeia** [comment]
> solved - $mkr deviates from other ERC20s and gives back bytes32 instead of string for its symbol and hence abigen exploded (it was build against erc20)

my version github.com/ethereum/go-ethereum v1.10.13 , This problem still occurs, how to solve it?

**Comment by MariusVanDerWijden** [comment]
Your ABI does not match the actual implementation of the contract. You would need to create the binding with the correct ABI

**Comment by shixiaofeia** [comment]
> 您的 ABI 与合同的实际实施不符。您需要使用正确的 ABI 创建绑定

Where can I get abi for all currencies? Thank you

**Comment by franco-bianco** [comment]
I'm facing a similar issue when trying to parse the log data of an event. I have also generated my ABI from the contract, so it is a match. I'm getting the following error, 1282 is the character count of the log data.

```
panic: abi: cannot marshal in to go slice: offset 44952455605068553573837941281666178605521118713043027060804374982093174814594 would go over slice boundary (len=1282)
```

**Comment by franco-bianco** [comment]
> > 您的 ABI 与合同的实际实施不符。您需要使用正确的 ABI 创建绑定
> 
> Where can I get abi for all currencies? Thank you

You can generate the ABI on your own using solc

Install solc by running the command:
```
npm i -g solc@0.8.16
```
Input the source code of the contract in another file, then generate the ABI by running the command:
```
solc --abi ContractName.sol
```

**Comment by megalepozy** [comment]
> I'm facing a similar issue when trying to parse the log data of an event. I have also generated my ABI from the contract, so it is a match. I'm getting the following error, 1282 is the character count of the log data.
> 
> ```
> panic: abi: cannot marshal in to go slice: offset 44952455605068553573837941281666178605521118713043027060804374982093174814594 would go over slice boundary (len=1282)
> ```

@franco-bianco u probably solved it (in that case it may be useful to someone else) but it doesn't have to be a match if u created an ABI (its not from the contract but from the .sol file which the ABI file originate from).
Anyway, to solve the issue u need to change the .sol type of the name and symbol attributes to bytes32 (at least when its for the name and symbol of course :)).
btw u'll still want to keep using the "default" string version if u need to support other ERC20 contracts as well
