### ISSUE TITLE
abigen generates an invalid argument of BoundContract.Call

### ISSUE THREAD

**Issue by crazybae** [ethereum/go-ethereum#21758]
Hi there,

#### System information

Geth version: `1.9.23`
OS & Version: Windows WSL2 (Ubuntu 18.04)
Commit hash : (if `develop`)
Go 1.52

#### Expected behaviour

The codes generated by abigen should generate exact arguments according to the signatures for BoundContract.Call(..)
The signature is  `(c *BoundContract) Call(opts *CallOpts, results *[]interface{}, method string, params ...interface{})`

#### Actual behaviour

But, abigen generates a wrong argument for the second one as follows:
```go
func (_Keyinfo *KeyinfoCaller) PubkeyForwards(opts *bind.CallOpts, arg0 []byte) ([]byte, error) {
	var (
		ret0 = new([]byte)
	)
	out := ret0
	err := _Keyinfo.contract.Call(opts, out, "pubkeyForwards", arg0)   /// here, second argument
	return *ret0, err
}
```
When I manually substitute the single value (out) to a slice  (&[]interface{}{out})) of all Call functions in the generated code, it works well.
e.g.)	err := _Keyinfo.contract.Call(opts, &[]interface{}{out}, "pubkeyForwards", arg0)

#### Steps to reproduce the behaviour

$ abigen --bin=mycode.bin --abi=mycode.abi --pkg=mypkg --out=mycode.go

#### Backtrace

````
[backtrace]
````

**Comment by MariusVanDerWijden** [comment]
@crazybae could you please add the contract for easier debugging? Will take a look asap

**Comment by crazybae** [comment]
thanks for your time..
this is our test contract in kovan..

https://kovan.etherscan.io/address/0xb4568621029e8c562bd936d9c819933e3411f308#writeContract

**Comment by MariusVanDerWijden** [comment]
Oh I know the problem. You're using an old version of abigen with a newer version of geth.
You need to update your version of abigen to 1.9.23 at least (or downgrade your geth dependency in go modules)
