### ISSUE TITLE
Why admin.nodeInfo.enode IP is 127.0.0.1?

### ISSUE THREAD

**Issue by dume2007** [ethereum/go-ethereum#21759]
I created a local private chain like below in the Server 192.168.40.113:

```
geth --datadir "./" --networkid 2020888 --port 30301 console --http --allow-insecure-unlock --http.api="eth,net,web3,personal,web3" --http.addr "192.168.40.113" --http.vhosts "*" --http.corsdomain "*"
```

admin.nodeInfo.enode showed

> "enode://dd47aff4da11c82496fec9253a1d2dac8c4abdbf93ff7458cf7965447355c265907b41dbd8c4b1dded6ae28b5a4d2d6b4d3fdad2950e5b6ef56169958b80b450@**127.0.0.1**:30301"

The enode value is bind to the 127.0.0.1, how can I addPeer this enode in another server node? I hope it should be bind to 192.168.40.113, like this

> "enode://dd47aff4da11c82496fec9253a1d2dac8c4abdbf93ff7458cf7965447355c265907b41dbd8c4b1dded6ae28b5a4d2d6b4d3fdad2950e5b6ef56169958b80b450@**192.168.40.113**:30301"

or like this

> "enode://dd47aff4da11c82496fec9253a1d2dac8c4abdbf93ff7458cf7965447355c265907b41dbd8c4b1dded6ae28b5a4d2d6b4d3fdad2950e5b6ef56169958b80b450@**[::]**:30301"

I can't find any OPTIONS to set the ip.

**Comment by karalabe** [comment]
You can explicitly set your IP address via `--nat=extip:192.168.40.113`. Otherwise Geth will try to detect your public IP address, but that may not work, in which case it will be left on `localhost`. Note, Geth explicitly excludes internal IP addresses from it's discovery to avoid publishing unreachable nodes into the DHT. If you want to run the discovery protocol in a completely private setting, you might need to play with the `--netrestrict` flag, though I've never used it, so don't have enough knowledge how to best set it. Cc @fjl?

**Comment by fjl** [comment]
If you run the discovery for a while, it will eventually find its own IP. If you don't want to use the discovery, just use the `--nat=extip:...` like @karalabe says.

**Comment by dume2007** [comment]
> You can explicitly set your IP address via `--nat=extip:192.168.40.113`. Otherwise Geth will try to detect your public IP address, but that may not work, in which case it will be left on `localhost`. Note, Geth explicitly excludes internal IP addresses from it's discovery to avoid publishing unreachable nodes into the DHT. If you want to run the discovery protocol in a completely private setting, you might need to play with the `--netrestrict` flag, though I've never used it, so don't have enough knowledge how to best set it. Cc @fjl?

Yes, it's useful. Thanks! 
And there is a new problem here:
I can get the first node's account balance with use getBalance command, but list accounts is empty. It seems that the synchronization between the two nodes is not successful. What is the reason for this?

In the new second server node:
```
> eth.getBalance("0xd4ad5901fb321b0def8eb1a573b4249d57f6d4c9")
1.38999999999267578125e+21
> eth.getBalance("0xffb555d9ab938fe8bf879f59baeb140e33915d5b")
5000000007324218750
> eth.accounts
[]
> eth.sendTransaction({from:"0xd4ad5901fb321b0def8eb1a573b4249d57f6d4c9", to:"0xffb555d9ab938fe8bf879f59baeb140e33915d5b", value:amount})
INFO [10-28|10:25:36.410] Imported new chain segment               blocks=1  txs=0 mgas=0.000 elapsed=3.036ms     mgasps=0.000 number=322 hash="f79b08…54871e" dirty=56.75KiB
WARN [10-28|10:25:36.542] Served eth_sendTransaction               reqid=29 t="455.224µs" err="unknown account"
Error: unknown account
	at web3.js:6347:37(47)
	at web3.js:5081:62(37)
	at <eval>:1:20(10)

```

in the first server node:
```
> eth.accounts
["0xd4ad5901fb321b0def8eb1a573b4249d57f6d4c9", "0xffb555d9ab938fe8bf879f59baeb140e33915d5b"]
```

**Comment by MariusVanDerWijden** [comment]
`eth.accounts` lists the accounts that are **locally** available on this node. They are not synced between nodes. With `eth.getBalance` you can query the balance of **any** account (not necessarily a local one). So this behavior is expected. If you want to send transactions from your account with the "second server node" you need to copy your accounts to it. `geth account import`

**Comment by dume2007** [comment]
I knew it, Thank you!
