### ISSUE TITLE
Unable to find peers 

### ISSUE THREAD

**Issue by gottabpro** [ethereum/go-ethereum#21767]
geth --networkid 999 --ipcpath ~/Lbrary/Ethereum/geth.ipc --rpc --rpcaddr "127.0.0.1" --rpcapi="eth,net,web3,db,personal,web3" --rpcport "8545" --datadir=./data --rpccorsdomain "*" console

I used this command to run my private blockchain, but couldn't find any peers. It also says that "db" rpc api is not available.

C:\Users\lenovo\OneDrive\Desktop\first-edition\ethereum\setup>geth --networkid 999 --ipcpath ~/Lbrary/Ethereum/geth.ipc --rpc --rpcaddr "127.0.0.1" --rpcapi eth,net,web3,db,personal --rpcport "8545" --datadir=./data --rpccorsdomain "*" console
INFO [10-30|20:12:29.682] Maximum peer count                       ETH=50 LES=0 total=50
WARN [10-30|20:12:29.685] The flag --rpc is deprecated and will be removed in the future, please use --http
WARN [10-30|20:12:29.687] The flag --rpcaddr is deprecated and will be removed in the future, please use --http.addr
WARN [10-30|20:12:29.690] The flag --rpcport is deprecated and will be removed in the future, please use --http.port
WARN [10-30|20:12:29.695] The flag --rpccorsdomain is deprecated and will be removed in the future, please use --http.corsdomain
WARN [10-30|20:12:29.698] The flag --rpcapi is deprecated and will be removed in the future, please use --http.api
INFO [10-30|20:12:29.735] Set global gas cap                       cap=25000000
INFO [10-30|20:12:29.739] Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
INFO [10-30|20:12:29.743] Allocated cache and file handles         database=C:\Users\lenovo\OneDrive\Desktop\first-edition\ethereum\setup\data\geth\chaindata cache=512.00MiB handles=8192
INFO [10-30|20:12:29.780] Opened ancient database                  database=C:\Users\lenovo\OneDrive\Desktop\first-edition\ethereum\setup\data\geth\chaindata\ancient
INFO [10-30|20:12:29.787] Initialised chain configuration          config="{ChainID: 1 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: <nil> Constantinople: <nil> Petersburg: <nil> Istanbul: <nil>, Muir Glacier: <nil>, YOLO v1: <nil>, Engine: unknown}"
INFO [10-30|20:12:29.796] Disk storage enabled for ethash caches   dir=C:\Users\lenovo\OneDrive\Desktop\first-edition\ethereum\setup\data\geth\ethash count=3
INFO [10-30|20:12:29.800] Disk storage enabled for ethash DAGs     dir=C:\Users\lenovo\AppData\Local\Ethash count=2
INFO [10-30|20:12:29.804] Initialising Ethereum protocol           versions="[65 64 63]" network=999 dbversion=8
INFO [10-30|20:12:29.807] Loaded most recent local header          number=0 hash="5e1fc7…d790e0" td=131072 age=51y6mo3w
INFO [10-30|20:12:29.811] Loaded most recent local full block      number=0 hash="5e1fc7…d790e0" td=131072 age=51y6mo3w
INFO [10-30|20:12:29.814] Loaded most recent local fast block      number=0 hash="5e1fc7…d790e0" td=131072 age=51y6mo3w
INFO [10-30|20:12:29.817] Loaded local transaction journal         transactions=0 dropped=0
INFO [10-30|20:12:29.821] Regenerated local transaction journal    transactions=0 accounts=0
INFO [10-30|20:12:29.829] Allocated fast sync bloom                size=512.00MiB
INFO [10-30|20:12:29.831] Initialized fast sync bloom              items=0 errorrate=0.000 elapsed=0s
INFO [10-30|20:12:29.831] Starting peer-to-peer node               instance=Geth/v1.9.23-stable-8c2f2715/windows-amd64/go1.15
INFO [10-30|20:12:29.873] New local node record                    seq=7 id=872b2890de0ab163 ip=127.0.0.1 udp=30303 tcp=30303
INFO [10-30|20:12:29.884] Started P2P networking                   self=enode://34eb7af1311aea91d2f0e081024792b3e7399a3f6780b62e5b5a407ca47d7099d6c2d079a84caadb0f9e386ecf6f55334db968fe0baca7e329ebdbf85a8302c1@127.0.0.1:30303
INFO [10-30|20:12:29.887] IPC endpoint opened                      url=\\.\pipe\C:\Users\lenovo/Lbrary/Ethereum/geth.ipc
**ERROR[10-30|20:12:29.915] Unavailable modules in HTTP API list     unavailable=[db] available="[admin debug web3 eth txpool personal ethash miner net]"**
INFO [10-30|20:12:29.921] HTTP server started                      endpoint=127.0.0.1:8545 cors=* vhosts=localhost
WARN [10-30|20:12:29.969] Served eth_coinbase                      reqid=3 t=0s err="etherbase must be explicitly specified"
Welcome to the Geth JavaScript console!

instance: Geth/v1.9.23-stable-8c2f2715/windows-amd64/go1.15
at block: 0 (Thu Jan 01 1970 05:30:00 GMT+0530 (IST))
 datadir: C:\Users\lenovo\OneDrive\Desktop\first-edition\ethereum\setup\data
 modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> INFO [10-30|20:12:35.670] New local node record                    seq=8 id=872b2890de0ab163 ip=112.196.163.160 udp=30285 tcp=30303
INFO [10-30|20:12:40.146] Looking for peers                        peercount=1 tried=121 static=0
INFO [10-30|20:12:50.423] Looking for peers                        peercount=0 tried=34  static=0
INFO [10-30|20:13:00.636] Looking for peers                        peercount=0 tried=92  static=0
INFO [10-30|20:13:10.657] Looking for peers                        peercount=0 tried=71  static=0
INFO [10-30|20:13:21.565] Looking for peers                        peercount=0 tried=113 static=0
INFO [10-30|20:13:31.607] Looking for peers                        peercount=0 tried=86  static=0
INFO [10-30|20:13:41.607] Looking for peers                        peercount=0 tried=64  static=0
INFO [10-30|20:13:51.612] Looking for peers                        peercount=0 tried=92  static=0
INFO [10-30|20:14:01.625] Looking for peers                        peercount=0 tried=64  static=0
INFO [10-30|20:14:11.656] Looking for peers                        peercount=0 tried=30  static=0
INFO [10-30|20:14:21.686] Looking for peers                        peercount=0 tried=108 static=0
INFO [10-30|20:14:31.741] Looking for peers                        peercount=0 tried=49  static=0
INFO [10-30|20:14:51.905] Looking for peers                        peercount=1 tried=115 static=0
INFO [10-30|20:15:02.504] Looking for peers                        peercount=0 tried=35  static=0
INFO [10-30|20:15:13.367] Looking for peers                        peercount=0 tried=124 static=0
INFO [10-30|20:15:23.394] Looking for peers                        peercount=0 tried=68  static=0
INFO [10-30|20:15:33.531] Looking for peers                        peercount=0 tried=63  static=0
INFO [10-30|20:15:43.561] Looking for peers                        peercount=0 tried=97  static=0
INFO [10-30|20:15:53.850] Looking for peers                        peercount=0 tried=24  static=0
INFO [10-30|20:16:03.881] Looking for peers                        peercount=1 tried=104 static=0
INFO [10-30|20:16:14.779] Looking for peers                        peercount=0 tried=43  static=0
INFO [10-30|20:16:25.250] Looking for peers                        peercount=0 tried=55  static=0
INFO [10-30|20:16:35.455] Looking for peers                        peercount=0 tried=38  static=0
INFO [10-30|20:16:45.898] Looking for peers                        peercount=0 tried=123 static=0
INFO [10-30|20:16:55.954] Looking for peers                        peercount=0 tried=93  static=0
INFO [10-30|20:17:05.962] Looking for peers                        peercount=0 tried=52  static=0
INFO [10-30|20:17:17.813] Looking for peers                        peercount=0 tried=98  static=0
INFO [10-30|20:17:27.959] Looking for peers                        peercount=0 tried=68  static=0
INFO [10-30|20:17:37.961] Looking for peers                        peercount=1 tried=82  static=0
INFO [10-30|20:17:59.556] Looking for peers                        peercount=0 tried=71  static=0
INFO [10-30|20:18:11.099] Looking for peers                        peercount=0 tried=71  static=0
INFO [10-30|20:18:21.828] Looking for peers                        peercount=0 tried=83  static=0
INFO [10-30|20:18:32.213] Looking for peers                        peercount=1 tried=96  static=0
INFO [10-30|20:18:42.351] Looking for peers                        peercount=0 tried=41  static=0
INFO [10-30|20:18:54.597] Looking for peers                        peercount=0 tried=6   static=0
INFO [10-30|20:19:04.631] Looking for peers                        peercount=0 tried=9   static=0

**Comment by MariusVanDerWijden** [comment]
I'm not sure what you are trying to achieve here. You want to create your own private network? Then you either need to specify the other nodes with the `--bootnodes` flag or add them on the console using `admin.AddPeer()`
