### ISSUE TITLE
can't add a new node in my own blockchain

### ISSUE THREAD

**Issue by Lucas-gif845** [ethereum/go-ethereum#21765]
> You'll need to provide some logs, otherwise there's no way to see what's wrong. We're using addPeer regularly in our tests so the functionality most definitely works.

hello, here's a fraction of my log : TRACE[10-29|14:02:18] Dial error                               task="staticdial c859e63b8ea2e0db 192.168.31.59:30303" err="dial tcp 192.168.31.59:30303: connectex: No connection could be made because the target machine actively refused it."
DEBUG[10-29|14:02:18] Can't resolve node                       id=c859e63b8ea2e0db err="discovery is disabled"
then I deleted the parameters "--nodiscover", it worked.  I don't figure out why

_Originally posted by @Lucas-gif845 in https://github.com/ethereum/go-ethereum/issues/21631#issuecomment-718386845_

**Comment by karalabe** [comment]
Seems that there's something blocking that port. Either you are running Geth on a different port, or there's a firewall that's not opened.

**Comment by Lucas-gif845** [comment]
thanks! I fixed it. but here was another question when I added another node into my blockchain. I uesed addPeer(), but the log I output didn't update which normally update some infomation like adding new node etc..   and when I add a new node into my blockchain, how do I broadcast it to other nodes in my chain so I don't need to type the same command in all nodes

**Comment by holiman** [comment]
Documentation is here: https://geth.ethereum.org/docs/interface/private-network , see "Setting Up Networking"
