### ISSUE TITLE
Geth remote central server with local keystores

### ISSUE THREAD

**Issue by bogdangainusa** [ethereum/go-ethereum#21764]
Hi there,

We are running multiple wallets and each wallet is connected to local geth. Because of high usage we created one central geth and we connected our wallets to this remote geth. 
Our issue here is that the keystores are stored on remote geth and we want them to be saved on the machine from where we're sending this requests to our central geth. 

How we can manage to connect our wallets to one central geth but to save keystores locally on server from where we are sending this requests to central geth?

Is there any documentation available? Tried different setup using ssh tunnels but it seems keystores are still generated on remote central geth server. 

Thank you.

**Comment by MariusVanDerWijden** [comment]
The easiest way to do this is probably using clef: https://geth.ethereum.org/docs/clef/tutorial

**Comment by Gbogdann93** [comment]
@MariusVanDerWijden Thanks for your response but it seems using clef i wasn't able to store keystore locally if we're sending curl request to geth which is running on another server/ip. 

Currently this is a big issue for us and at this point it makes no sense to run geth on each server from where we're sending such requests and keystores are stored on central geth and not on local server.

**Comment by holiman** [comment]
> Our issue here is that the keystores are stored on remote geth and we want them to be saved on the machine from where we're sending this requests to our central geth.

What is your usecase? What are you doing on the local geth nodes? I don't understand why you need all this. If you want to generate a tx locally (using a local keystore), you can just use something like web3.js or web3.py to query the central geth for nonce, gasPrice, but craft the transaction locally. Locally, you _could_ use clef, or some other wallet backend (even geth, which you could theoreticaly run with `--nodiscover --maxpeers=0` to make it a totally idle node)

**Comment by Gbogdann93** [comment]
@holiman  Currently we are running several wallet instances on multiple servers. 
Because geth is requiring huge space in mainnetwork and we had issues after some time with geth sync we decided to create one central geth server.

Currently we're sending all curl requests to central geth and everything is managed by it. The only issue that we're running is that we need to have stored accounts keystores locally on servers from where we're sending this curl requests. 
At this moment all keystores are stored on remote geth and we're searching for a solution to:
- not run geth locally on each server where we're using our wallets (to avoid high server usage)
- send requests to central geth server but keystores to be saved somehow on server from where we're sending this reuqests (when creating new account)

Thank you for your response, if something is unclear i will be happy to let you know more about our issue and how we can solve this.

**Comment by holiman** [comment]
I still don't quite understand in what capacity the 'local geth' is needed. To craft transactions? To query stuff? 
One way to manage it could also be to run local light-clients, which have fixed connection to the central one, which basically whitelists the local ones, so they always are given a light slot.

**Comment by Gbogdann93** [comment]
@holiman  There is no needed in local geth, we just want to save keystores locally but transfers/blocks to be read from central geth using curl to the ip/port.

**Comment by Gbogdann93** [comment]
@holiman Do you have any other suggestion for this? 
P.S: Tried to run geth locally on our servers in light mode but it seems it's stuck on all servers and won't find any available peers even after 4-5 hours.
`INFO [11-11|12:25:51.923] Looking for peers                        peercount=0 tried=0 static=0
INFO [11-11|12:26:01.926] Looking for peers                        peercount=0 tried=1 static=0`

**Comment by holiman** [comment]
> I still don't quite understand in what capacity the 'local geth' is needed. To craft transactions? To query stuff?

I still don't understand. 

> Our issue here is that the keystores are stored on remote geth and we want them to be saved on the machine from where we're sending this requests to our central geth.

That sounds like a bad idea. Your local nodes will be sending passwords to the central server, which will be handling unencrypted keys. It's nearly the same as the central server having them all unlocked. You're better off signing the transactions locally, where the keystores are today. 

> How we can manage to connect our wallets to one central geth but to save keystores locally on server from where we are sending this requests to central geth?

Just use local geth nodes. If you don't want them to be blockchain-aware, set `--no-discover --maxpeers=0` and just use them for signing `eth_signTransaction` (or use clef) and then submit the raw signed transactions to the central node . Oh, and also use the central node to query for nonces and gasprice etc. You can use `eth_fillTransaction` to make it filll the details.
