### ISSUE TITLE
cURL invoke RPC method "eth_call" with doMultiply constract function returns "-32000", "invalid opcode": "REVEERT"

### ISSUE THREAD

**Issue by zhang112596** [ethereum/go-ethereum#21771]
#### Steps to reproduce the behaviour

1. Here is the Solidity constract function "doMultiply":
```javascript
pragma solidity 0.4.22;

contract Multiply {
   
  function doMultiply(uint in01, uint in02) public constant returns (uint) {
   return in01 * in02;
  }
}
```
2. use online ethereum website to compile upper "doMultiply.js" into ABI and save into file "Multiply.abi".
3. load the ABI file with command `loadScript("Multiply.abi")` in geth console which launched by command `geth attach ipc:\\.\pipe\geth.ipc`.
4. I can execute ABI call successfully like bellowing return `64`.

```
var myContract = eth.contract ([{"constant": true,"inputs": [{"name": "in01","type": "uint256"},{"name": "in02","type": "uint256"}],"name": "doMultiply","outputs": [{"name": "","type": "uint256"}],"payable": false,"stateMutability": "view","type": "function"}]).at("0x9ebf2d48d78d50ae47e81c25410d645b41546883");
```
5. get coinbase hash and "doMultiply" uint256 coding string through following commands:
```
curl -X POST -H "Content-Type: application/json" --data "{\"jsonrpc\": \"2.0\",\"method\":\"eth_coinbase\",\"params\":[],\"id\":64}" localhost:8080
```
```
web3.sha3("doMultiply(unit256,unit256)").substring(0,10)
```

6. the final step try to "doMultiply" 8 and 9 report error.
```
curl -X POST -H "Content-Type: application/json" --data "{\"jsonrpc\":\"2.0\",\"id\": 1,\"method\":\"eth_call\",\"params\":[{\"to\":\"0x9ebf2d48d78d50ae47e81c25410d645b41546883\",\"data\":\"0x06eb4e9b00000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000009\"},\"latest\"]}"  localhost:8080
```
Here is the error output:

![微信图片_20201101120035](https://user-images.githubusercontent.com/51774160/97794908-d3154700-1c3a-11eb-96fb-71d799e19361.png)

#### System information

Geth version:
```
Geth
Version: 1.9.22-stable
Git Commit: c71a7e26a8b1e332bbf3262d88ba3ff32071456c
Git Commit Date: 20200928
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15
Operating System: windows
GOPATH=
GOROOT=go
```

OS & Version: Windows
Commit hash : (if `develop`)

#### Expected behaviour
The final step 6 suppose to return result:
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x0000000000000000000000000000000000000000000000000000000000000040"
}
```

#### Backtrace

Newbie on Ethereum project, don't know how to generate backtrace.
If you need it, can you tell me how to generate it? Thanks in advance.

**Comment by ligi** [comment]
with all credits to @rjl493456442:

unit256,unit256

must be 

uint256,uint256

can you try with this change and let us know if your problem is gone

**Comment by holiman** [comment]
```
0x648146a2
```

**Comment by karalabe** [comment]
Also another info you need to be aware of is how you initialize your chain. It still seems you're running your network without all the forks configured (hence why it doesn't recognize the `REVERT` opcode). How did you init your chain?

**Comment by zhang112596** [comment]
@ligi
Hello, I changed as you said, but still got the same wrong result

**Comment by zhang112596** [comment]
@karalabe 
Thank you for your insight, this is how I initialized my blockchain：
`geth --identity "Nodel" --networkid 168 --nodiscover --maxpeers 5 --rpc --rpcapi "db,eth,net,web3,personal" --rpcport "8080" --datadir "c:\MyGeth\node01" --port "30303" --mine --minerthreads=1 --cache=1024  --unlock 0 --allow-insecure-unlock`
`geth --identity "Node2" --networkid 168 --ipcdisable --nodiscover --datadir "c:\MyGeth\node02" --port "30304"`
`geth --identity "Node3" --networkid 168 --ipcdisable --nodiscover --datadir "c:\MyGeth\node03" --port "30305"`

**Comment by stardiviner** [comment]
Any updates? I got similar issue. Gentle ping...

**Comment by zhang112596** [comment]
I haven't continued to study this problem, so I still haven't found a solution to this problem, sorry @stardiviner

**Comment by MariusVanDerWijden** [comment]
@zhang112596 Could you try to dump your genesis? `./geth -datadir "c:\MyGeth\node01" dumpgenesis` This allows us to see which forks are enabled in your private network. The REVERT opcode was introduced in the Byzantium hardfork. If your network doesn't have this fork enabled, transactions that use this opcode will fail. A solution then would be to upgrade your private network with the byzantium hardfork. 
Another solution might be to downgrade the solidity compiler to a version that didn't produce code for post-byzantium.

**Comment by MariusVanDerWijden** [comment]
@stardiviner Do you have a way to reproduce this (or your similar) issue?

**Comment by stardiviner** [comment]
I solved the problem long ago. But don't remember how......

**Comment by MariusVanDerWijden** [comment]
So it's probably not an issue with geth. @zhang112596 If you have any more information to reproduce this issue please lmk
