### ISSUE TITLE
Geth client keep synchronizing failed for more than 2 hours

### ISSUE THREAD

**Issue by Muggle-Du** [ethereum/go-ethereum#21777]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: geth1.9.19
OS & Version: ubuntu 18
Commit hash :  3e06419

#### Expected behaviour
expect the geth node always keeps up with the latest blocks

#### Actual behaviour
the geth node keeps dropping peers and connect peers, sometimes it was fetching block bodies but this never succeeded, so the block height stops growing and synchronization gets stuck

#### Backtrace
<img width="977" alt="截屏2020-11-03 上午2 23 07" src="https://user-images.githubusercontent.com/25078682/97905187-8e91c480-1d7c-11eb-9da5-5549eabe1f2e.png">

and everytime fetching batch of block bodies finally failed , some messages like these occured:
<img width="986" alt="1" src="https://user-images.githubusercontent.com/25078682/97906499-bf72f900-1d7e-11eb-87a9-a419061ccc56.png">

**Comment by karalabe** [comment]
Please don't run with debug logs. Those are too verbose to make heads or tails (especially when you just posted two random screenshots). Info should be enough to see if there's a problem and to start out with.

Also, I'd always recommend updating to the latest stable release before filing bugs and it can happen that we've already fixed an issue you're hitting.

**Comment by Muggle-Du** [comment]
thanks. I'm trying to update the geth client to the latest stable version.

**Comment by Muggle-Du** [comment]
By the way, what's the default value of verbosity

**Comment by Muggle-Du** [comment]
upgrading geth client successfully solve the problem
