### ISSUE TITLE
eth_getLogs returns wrong number of logs on goerli

### ISSUE THREAD

**Issue by pawanjay176** [ethereum/go-ethereum#21770]
#### System information

Geth version: `Geth/v1.9.23-stable-8c2f2715/linux-arm64/go1.15.3`
OS & Version: Ubuntu 20.04

#### Expected behaviour

The latest stable version is giving different number of logs for an `eth_getLogs` http request compared to the previous versions.
Found this issue while trying to query the eth2 medalla testnet deposit contract logs on goerli. Following are the params for the rpc request:

```
[
  {
    "address": "0x07b39F4fDE4A38bACe212b546dAc87C58DfE3fDC",
    "topics": [
      "0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"
    ],
    "fromBlock": "0x35FC08",
    "toBlock": "0x35FFF0"
  }
]
``` 
The `eth_getLogs` request with the above params returned 120 logs in the latest version (Geth/v1.9.23-stable-8c2f2715/linux-arm64/go1.15.3) and 125 logs in an earlier version (Geth/v1.9.22-stable-c71a7e26/linux-amd64/go1.15.2). Both nodes are fast synced.

Please note that deleting the datadir and resyncing the geth node seems to fix the issue (gives correct number of logs for the above query)

#### Actual behaviour

Should always return correct number of logs.

#### Steps to reproduce the behaviour

Non deterministic issue. Happening on a specific 1.9.23 goerli node. Other nodes of the same version return correct number of logs. 

I think this could be an issue with changes to the bloom filter in the latest version. Had a similar type of issue on nethermind a few months back https://github.com/NethermindEth/nethermind/issues/1980 which was an issue with bloom filters.

**Comment by ligi** [comment]
can you provide both sets of logs (the one with 120 and the one with 125)?

**Comment by holiman** [comment]
Tried to repro this, 
```
$ cat getlogs.json
{
  "method": "eth_getLogs",
  "params": [
    {
      "address": "0x07b39F4fDE4A38bACe212b546dAc87C58DfE3fDC",
      "topics": [
        "0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"
      ],
      "fromBlock": "0x35FC08",
      "toBlock": "0x35FFF0"
    }
  ],
  "id": 1,
  "jsonrpc": "2.0"
}
[user@work go-ethereum]$ curl --data @getlogs.json  -H "Content-Type: application/json" -X POST localhost:8545 2>/dev/null  | jq ".result | length" 
125
```
It produces the same `125` every time. 

My theory is that the root cause may be that the bloom indexing is not finished (`eth/filters/filter.go`): 
```go
	if indexed := sections * size; indexed > uint64(f.begin) {
		if indexed > end {
			logs, err = f.indexedLogs(ctx, end)
		} else {
			logs, err = f.indexedLogs(ctx, indexed-1)
```

It's a bit odd, API-wise, that we just silently truncate the range without any form of notification - one might have expected a server log message at least.

**Comment by holiman** [comment]
Actually, my explanation doesn't fit. If the `to` is `0x35FFD8`, then the number of logs are `118`, but if one more block is included, (`0x35FFD9`), then the number of logs are `124`.

**Comment by holiman** [comment]
If the range is changed to       
```
"fromBlock": "0x35FC13",
      "toBlock": "0x35FFF0"
```
Then it produces `120` logs. So it's almost like it's missing the logs for a few blocks in the beginning of the range. Very odd. 
If you manage to repro this, and save the logs, so we can cross-check which ones are missing, it might be easier to figure out what's happening.

**Comment by pawanjay176** [comment]
@holiman Sorry, but I don't have the full logs, just the counts. The issue was observed in a Lighthouse user's geth node. I asked him to run a script to get the log counts in a certain range in increments of 1000 and highlighted the one with the mismatch in the issue. I'll try to chase him up again to get the full logs from his node.

Here are the log counts for his node vs my node if it's useful in any way. https://gist.github.com/pawanjay176/b7f2deab6af05e4bdd2c67651790e072

Lines 5 and 6 are different in data obtained from the two nodes, but everything above and below that are same.

**Comment by holiman** [comment]
```
31 logs in range: 3536928..3537928
120 logs in range: 3537928..3538928
```
vs
```
80 logs in range: 3536928..3537928
125 logs in range: 3537928..3538928
```
So the upper one seems to be missing logs, `49` in one segment, and `5` in the segment after.

**Comment by pawanjay176** [comment]
Hey @holiman . Unfortunately, the user resynced his node so I'm not able to get the full logs anymore.

I'll try a few resyncs to see if I can reproduce the error.

**Comment by pawanjay176** [comment]
@holiman 
Saw this issue again with an older version (Geth 1.9.16-stable) node on mainnet with one of our users.
Got the logs this time though
https://gist.github.com/pawanjay176/8cb38b296346ef56e621dfea29445e55

Used this request to get the logs in the range where there seemed to be deviation.
```
curl --location --request POST 'http://localhost:8545' \
    --header 'Content-Type: application/json' \
    --data-raw '{
    "jsonrpc":"2.0",
    "method":"eth_getLogs",
    "params":[{"address": "0x00000000219ab540356cBB839Cbe05303d7705Fa", "topics": ["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"], "fromBlock": "0xAB6CDC", "toBlock": "0xAB8834"}],
    "id":1
    }' | jq '.'
```
Ideally, this particular range should have 166 logs, the faulty node returns only 12.
In the gist, the `faulty_logs.json` contains the full logs from the faulty node. 
`count_diff.txt` is the diff of the counts between a correct geth node (left) and the faulty node (right). As you can see, it seems that the logs are missing only for a particular range of blocks.

Not sure if this will help though since it's an older geth version :sweat_smile: 
Let me know if you need any other details. AFAIK, the user hasn't resynced his geth node yet.

**Comment by holiman** [comment]
Interesting. So the faulty one returns logs for these blocks:  
```
"0xab6d14"
"0xab85ee"
"0xab8767"
"0xab87a1"
"0xab87cf"
"0xab87d8"
"0xab87e3"
"0xab87ed"
"0xab87fc"
"0xab8805"
"0xab8818"
"0xab8825"
```
The correct one returns 
```
"0xab6d14"
// 153 omitted for brevity
"0xab85ee"
"0xab8767"
"0xab87a1"
"0xab87cf"
"0xab87d8"
"0xab87e3"
"0xab87ed"
"0xab87fc"
"0xab8805"
"0xab8818"
"0xab8825"
```
So `11234580` was included, `11235267 - 11240833` were skipped over, and `11240942` and onwards were included.

**Comment by holiman** [comment]
Still, it doesn't seem to be the case that a particular segment is skipped: 
```
Block 11234580, segment: 2742 (start: 11231232 end 11235327)
Block 11235267, segment: 2742 (start: 11231232 end 11235327)
Block 11240833, segment: 2744 (start: 11239424 end 11243519)
Block 11240942, segment: 2744 (start: 11239424 end 11243519)
```
Some parts of segment `2742` was included, some parts of `2744`, nothing of `2743`

**Comment by holiman** [comment]
This issue is stale: we investigated it but it didn't lead anywhere back then. Until we get some new "evidence" to work on, or ways to repro this, let's assume it's not an issue anymore.
