### ISSUE TITLE
Add informational metrics to prometheus endpoint

### ISSUE THREAD

**Issue by ulope** [ethereum/go-ethereum#21783]
#### System information

Geth version: `1.9.23`
OS & Version: OSX

#### Feature request
Please add informational metrics to the prometheus endpoint:
- Chain / network info 
- Geth version 

For example:
```
# TYPE chain_info gauge
chain_info{chain_id="5", network_name="goerli"} 1
# TYPE geth_info gauge
geth_info{version="1.9.23-stable", arch="amd64", os="darwin", commit="deadbeef", protocol_versions="63,64,65"} 1
```

**Comment by karalabe** [comment]
We'd need to investigate a bit how to expose metadata in Prometheus and InfluxDB. I'm all for surfacing these infos, just have no idea yet what the standard way is. If you have any docs you could point us to, that would be grand.

**Comment by ulope** [comment]
@karalabe Sorry I missed this.

Here's a (pretty old but still accurate) [post on the Robust Perception blog](https://www.robustperception.io/exposing-the-software-version-to-prometheus)

As well as a sample of some of the exporters / tools I've used in the past few days that include such a metric:
- [Apache Exporter](https://github.com/Lusitaniae/apache_exporter/blob/712a6796fb84f741ef3cd562dc11418f2ee8b741/apache_exporter.go#L114-L118)
- [Postgres Exporter](https://github.com/wrouesnel/postgres_exporter/blob/master/cmd/postgres_exporter/postgres_exporter.go#L1445-L1446)
- [Redis Exporter](https://github.com/oliver006/redis_exporter/blob/aeb7c60fac70f5b912a71903cf91a6f5f28e6d7b/exporter.go#L421)
- [Docker](https://github.com/moby/moby/blob/2e5923c547bf4f1d8f3219f1b35df3f6d833b8d5/daemon/metrics.go#L45)
- [node exporter](https://github.com/prometheus/node_exporter/blob/306a3653779c13244b2dc72f5bdd6098a56f83ef/collector/uname.go#L24-L36)

My example above follows this pattern.

**Comment by Ab-hishek** [comment]
I would like to work on this issue if this is still required.

**Comment by muddlebee** [comment]
@karalabe @holiman @MariusVanDerWijden can this be closed ?

MONITORING GETH WITH INFLUXDB AND GRAFANA :  https://ethereum.org/en/developers/tutorials/monitoring-geth-with-influxdb-and-grafana/ has been already added.

**Comment by muddlebee** [comment]
@ulope FYI

**Comment by holiman** [comment]
Cannot be closed, no. The issue requests meta-information to be exposed via influx/prometheus, like 
```
# TYPE chain_info gauge
chain_info{chain_id="5", network_name="goerli"} 1
# TYPE geth_info gauge
geth_info{version="1.9.23-stable", arch="amd64", os="darwin", commit="deadbeef", protocol_versions="63,64,65"} 1
```
Not fixed

**Comment by muddlebee** [comment]
@holiman this looks interesting. Can I work on this? I am participating in "Core Developer" [Apprenticeship Program ](https://github.com/ethereum-cdap/cohort-one/blob/master/program-details.md) by Ethereum. I might add this as well in my [deliverable tasks](https://github.com/ethereum-cdap/cohort-one/blob/master/stage-1-project-discovery.md#1-a-well-defined-goal). 

If this sounds good. Can you assign this to me please?

**Comment by holiman** [comment]
Sure, just go ahead. 
(no need to assign the ticket though)

**Comment by Johny2022** [comment]
Please did anyone has valid Bitcoin token contract address, I need please so as to earn money for me to buy computer system/ laptop to go forward on programming career.

**Comment by aertoria** [comment]
this ticket is still open? should we close it?

**Comment by p2p-sergey-y** [comment]
I also really need that metrics, it's very useful!

**Comment by timqian** [comment]
Is this feature still needed? Saw an old relevant PR: https://github.com/jorgeacortes/go-ethereum/commit/cff0d5924b1f531fcdf7da59cea5548c6afbc4a2 why didn't we merge that?
If this feature is still needed, I would like to have a try

**Comment by holiman** [comment]
> why didn't we merge that?

The PR in question is here: https://github.com/ethereum/go-ethereum/pull/24877 . As for why it has not been merged, I would guess that the answer is that it touches 17 files and adds 423 LOC, adding a new gauge-type. Reviewing + testing that is non-trivial, particularly since the testing involves not only the code itself, but testing against e.g. grafana. 

So, (and this is not criticism!), it kind of has the combo of being "rather large amount of work" and also  "not considered high prio". 

> If this feature is still needed, I would like to have a try

If you want to help push the feature along, I think rather than implementing it all over again (unless you have some better idea about how to do it),  it would be better to spend the effort towards reviewing and testing that pr, and give feedback on how it works.

**Comment by karalabe** [comment]
THere was AFAIK a different PR opened that also does this for influx. Should look into that, we need both.

**Comment by Francesreid** [comment]
Thankyou forball the work you're putting in , what have I got to do at my
end Frances Reid

**Comment by timqian** [comment]
@holiman Thanks for the note, the PR looks good to me, looks adding a new gauge-type is inevitable. I have tested it and left [a comment](https://github.com/ethereum/go-ethereum/pull/24877#issuecomment-1432362540) there
@karalabe I didn't see another PR doing this for influx. Seems the influx part is also handled in the same PR

**Comment by mcdee** [comment]
I made a few comments on the PR.  This would be very useful to have: for anyone attempting to manage multiple instances of geth, having version information to hand via prometheus allows much easier understanding of which versions are where.

**Comment by holiman** [comment]
> THere was AFAIK a different PR opened that also does this for influx. Should look into that, we need both.

The PR contains both. I searched but haven't found any other PR, if you know of one I'd gladly check what it contains and if there's anything we're missing.

**Comment by holiman** [comment]
Closed by https://github.com/ethereum/go-ethereum/pull/24877
