### ISSUE TITLE
Is possible to start from 0 for a light client?

### ISSUE THREAD

**Issue by AurevoirXavier** [ethereum/go-ethereum#21786]
I want all the headers.

**Comment by ligi** [comment]
Out of curiosity: What is your use case?
Are you aware that the light client can still retrieve the old headers?

**Comment by zsfelfoldi** [comment]
There is currently no option to disable using the CHT if there is one present. It wouldn't be hard to add it but I don't see why it's necessary since as @ligi wrote the old headers can still be safely retrieved on demand.

**Comment by AurevoirXavier** [comment]
> Out of curiosity: What is your use case?
> Are you aware that the light client can still retrieve the old headers?

I want to calculate the the MMR root for every header.

All I need is the headers data (other data is useless to me), so I don't want to waste too much disk space. Any way to achive this?

**Comment by rjl493456442** [comment]
I think it's a valid feature request if you want to recalculate some other things with all headers from the genesis. Any option? @zsfelfoldi

**Comment by rjl493456442** [comment]
The feature is implemented in #22123

**Comment by AurevoirXavier** [comment]
> The feature is implemented in #22123

But seems the old header will be pruned. Once I completed the sync. Is that expected? So I still can not get/store all headers.

**Comment by rjl493456442** [comment]
@AurevoirXavier  Use `--light.nopruning Disable ancient light chain data pruning` to disable the automatic pruning.

**Comment by AurevoirXavier** [comment]
> --light.nopruning

Okay, I've added it

But every time I use 

```
header 'Content-Type: application/json' \
--data-raw '{
        "jsonrpc":"2.0",
        "method":"eth_getBlockByNumber",
        "params":[
                "xxx",
                true
        ],
        "id":1
}'
```

It still takes a few seconds to fetch the header.
