### ISSUE TITLE
How to get internal transactions info generated by contracts using geth

### ISSUE THREAD

**Issue by polarwk** [ethereum/go-ethereum#21780]
Hi there,

#### System information

Geth version: `v1.9`
OS & Version: Ubuntu18.04

#### Expected behaviour
we used debug_traceTransaction API to get info about specific transaction

#### Actual behaviour
we can only access the recent transactions in 128 blocks. 

#### Steps to reproduce the behaviour
`debug_traceTransaction('0x87ea095e22bd3a8926c4db12bedef9d99a8b41d2f509278ce40b91628b6ba47f')
`
#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
So you want to be able to trace all transactions? You need to run an archive node then

**Comment by MariusVanDerWijden** [comment]
As ligi said, normal full nodes can only trace transactions in the latest 128 blocks. To trace more than that you need to run an archive node as it will save the intermediary states
