### ISSUE TITLE
Reduce label count

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#21789]
we have a lot of labels - IMHO we should reduce the count.

![Selection_278](https://user-images.githubusercontent.com/111600/98294229-e19f8d80-1faf-11eb-9e7e-07b305dedef8.png)

Suggestion: we delete all labels that have no concrete use cases

Labels with use-cases:
 * status:triage - marking PRs/issues to be triaged in the next triage
 * need:more-information - for stale-bot and signaling we wait for things
 * good first issue - AFAIK they are specially exposed by github and picked up by some tools/interfaces

I would also say for a rough-categorization type:bug, type:feature, type:refactor, type:research

this would mean we have less than 10 rather than close to 100

Do you see other labels that you would miss and cannot live without? If so marie kondo-style: "Does this label make you happy"?

EDIT: new label list after requested added:
 * status:triage - marking PRs/issues to be triaged in the next triage
 * status:on-hold - waiting for "something" - should be checked from time to time
 * status;backlog - if idle time appears they are next to grab
 * status:critical
 * status:important

 * fork:yolov3
 * fork:berlin
 
 * need:docs - documentation requested
 * need:more-information - for stale-bot and signaling we wait for things
 * good first issue - AFAIK they are specially exposed by github and picked up by some tools/interfaces

 * docs_in_pr

**Comment by MariusVanDerWijden** [comment]
A need:docs label would be cool (merge of type:docs, todo-pr-into-docs and need:documentation)

**Comment by MariusVanDerWijden** [comment]
I also kinda like the prio 1, 2 backlog labels and the on-hold

**Comment by holiman** [comment]
I want hardfork-tracking tags to remain, such as yolov3. Also there's a tag 'docs-in-pr', sth like that, to signify that the PR contain good docs that should be lifted to gh-pages

**Comment by ligi** [comment]
We removed some labels
