### ISSUE TITLE
Block timestamp equals last block received time, not mining time

### ISSUE THREAD

**Issue by Taodactyl** [ethereum/go-ethereum#21784]
As I experiments with hosting a full node, I've runned this little code to understand block propagation in the network :

```
const web3 = initWeb3();
const newBlockHeaders = web3.eth.subscribe("newBlockHeaders");
newBlockHeaders.on("data", async (blockHeader) => {
    console.log("block: " + blockHeader["number"] + " - ts: " + blockHeader["timestamp"] + " - received at: " + Math.floor(new Date() / 1000));
});
```

#### System information

Geth version: `Geth
Version: 1.9.23-stable
Git Commit: 8c2f271528f9cccf541c6ea1c022e98407f26872
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15
Operating System: linux
GOPATH=
GOROOT=go
`
OS & Version: Ubuntu 20.04.1 LTS

#### Expected behaviour

The new block's timestamp is equal to the time of mining on the remote node. If a new block is mined at TS=1234, sent to the network and received by my node at TS=1257, I expect the block timestamp to be 1234, not 1257.

#### Actual behaviour

Here is a dump of the result :

```
block: 11185527 - ts: 1604424887 - received at: 1604424911
block: 11185528 - ts: 1604424911 - received at: 1604424915
block: 11185529 - ts: 1604424914 - received at: 1604424934
block: 11185530 - ts: 1604424935 - received at: 1604424970
block: 11185531 - ts: 1604424970 - received at: 1604424979
block: 11185532 - ts: 1604424979 - received at: 1604424983
block: 11185533 - ts: 1604424983 - received at: 1604424987
block: 11185534 - ts: 1604424987 - received at: 1604424991
block: 11185535 - ts: 1604424991 - received at: 1604425007
block: 11185536 - ts: 1604425007 - received at: 1604425013
block: 11185537 - ts: 1604425012 - received at: 1604425027
block: 11185538 - ts: 1604425026 - received at: 1604425031
```

You can see that the received block's timestamp is equal to the last block received time (accounting for rounding errors and time execution of my code). My guess is that the timestamp of the next block to be mined is set when we receive a block. I checked the timestamps for a few block, they are the same in the geth console and on etherscan.io

**Comment by holiman** [comment]
The block timestamp is set when the miner _starts_ working on the block. So it will most likely be pretty close to the time when the previous block was propagated on the network. The header needs to be set before the pow-grinding starts.

**Comment by isramali1** [comment]
> The block timestamp is set when the miner _starts_ working on the block. So it will most likely be pretty close to the time when the previous block was propagated on the network. The header needs to be set before the pow-grinding starts.

I would like to change the block timestamp from seconds to milliseconds to be more precise. 
I wonder if it is possible to point me to the source-code line at which the timestamp is recorded by the miner. 
Thanks.
