### ISSUE TITLE
Threshold for "oversized data" too low

### ISSUE THREAD

**Issue by ItsNickBarry** [ethereum/go-ethereum#21788]
#### Expected behaviour

A contract deployment which does not exceed the gas limit should work as expected.  This includes the deployment of a contract which deploys multiple other contracts in its constructor.  

#### Actual behaviour

Deployment fails with an "oversized data" error.

#### Steps to reproduce the behaviour

The `JusDeFi` contract found here fails to deploy via geth (Infura):
https://github.com/jusdefi/jusdefi

However, deployment works as expected using an alternative node implementation.

**Comment by ligi** [comment]
Please provide more information. Stacktraces, versions, ..
