### ISSUE TITLE
how to set up the node for eth2.0?

### ISSUE THREAD

**Issue by 1971192997** [ethereum/go-ethereum#21791]
i am trying to set up the node of eth2.0   but   some error note that chain id is 5? 

is that normal?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
