### ISSUE TITLE
*interrupt always equal to 0 ?

### ISSUE THREAD

**Issue by tkblack** [ethereum/go-ethereum#21790]
I saw some code in miner/worker.go,line 344:
```
commit := func(noempty bool, s int32) {
		if interrupt != nil {
			atomic.StoreInt32(interrupt, s)
		}
		interrupt = new(int32)
		w.newWorkCh <- &newWorkReq{interrupt: interrupt, noempty: noempty, timestamp: timestamp}
		timer.Reset(recommit)
		atomic.StoreInt32(&w.newTxs, 0)
	}
```
If we `interrupt = new(int32)` ,`interrupt` will reassign the address and `*interrupt` is equal to 0. So, the `s` will not work. Did I get it right?

**Comment by rjl493456442** [comment]
Every time when we try to schedule up some operations, a new signal receiver `interrupt` will be allocated.
And the signal is only passed by the **this** pointer to the relevant operations.

So in this case, the `s` is only passed to some old operations and then it's useless.
