### ISSUE TITLE
cannot find package "github.com/docker/docker/pkg/reexec

### ISSUE THREAD

**Issue by blackhoole** [ethereum/go-ethereum#21810]
help, I can't find  "github.com/docker/docker/pkg/reexec" from github. 
Thanks a lot

**Comment by MariusVanDerWijden** [comment]
It was moved here: https://github.com/moby/moby/tree/master/pkg/reexec

**Comment by blackhoole** [comment]
> 
> 
> It was moved here: https://github.com/moby/moby/tree/master/pkg/reexec I guess.
> Docker/docker was renamed to moby/moby (github forwards docker/docker to moby/moby)

Yeah. Your answer just solved my problem.  I am very greatful for  your kindness. Thank you friend
