### ISSUE TITLE
RNG always seeded to same value in geth javascript console

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/go-ethereum#2181]
This a pretty weird bug. All 4 times, the same random numbers are generated. While probably not imminently critical, an enterprising scammer could take advantage of this

![screen shot 2016-02-06 at 8 24 04 pm](https://cloud.githubusercontent.com/assets/1577353/12870382/df08d1fa-cd0f-11e5-9684-53292c77e67b.png)

Here's the contents of randomtest.js

    for(var i = 0; i<5; i++){
        console.log(Math.random())
    }
    process.exit()

**Comment by aakilfernandes** [comment]
Geth
    Version: 1.3.2
    Protocol Versions: [63 62 61]
    Network Id: 1
    Go Version: go1.5.1
    OS: darwin
    GOPATH=
    GOROOT=/usr/local/Cellar/go/1.5.1/libexec

**Comment by bas-vk** [comment]
`Math.random` isn't meant to be cryptographically secure. Trusting on it for any crypto/security related operations isn't a good idea. Geth uses the otto vm which comes with a `Math.random` implementation that uses the `math/rand` package to generate pseudo random floats. There is actually a [PR](https://github.com/robertkrimen/otto/pull/95) in the otto vm repo to use a somewhat better seed.

**Comment by deoxxa** [comment]
See https://github.com/robertkrimen/otto/pull/163 - I just implemented a mechanism to supply an external `Math.random()` provider.

**Comment by bas-vk** [comment]
@deoxxa, great thanks. Will check it out.

**Comment by bas-vk** [comment]
@aakilfernandes, fixed in develop.
