### ISSUE TITLE
How to add ethereum node to already existing blockchain without knowing genesis file ?

### ISSUE THREAD

**Issue by shivam201312** [ethereum/go-ethereum#21840]
Hi , i am new blockchain
Target :  i want to add new node to already running blockchain.
Correct, if i am wrong for adding node to network. two node's should have same genesis block.
if genesis block have different values then newly setup node will not be able to mine the transaction from already running blockchain.

Issue :
i dont have gensis.json for creating same gensis block on new node.

Tried :
i have tried to setup gensis block but live blockchain gensis block value is different from newly setup on local system.
Checked by connecting to geth console and running following command in console.
```
admin.nodeInfo
```
so when i add peers using following command it returns true.
```
admin.addPeer("endoevaluefromec2instance")
```
when i list peers on ec2 instance it shows count 0.
```
0
```
Note : i am able to connect to blockchain using web3 module so i don't think there is connectivity issue
Question :
1) How can i create gensis.json file from already running etherum instance ?
2) Is there any other way to add node to already running instance or mine the transaction ?
3) How can i take backup of already running blockchain and restore on system ?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by shivam201312** [comment]
Hi, @ligi  thanks for your suggestion. I understand that team only wants to keep bugs and reported issue's on Github so that it will be clean.
But posting on the above platform is not always helpful that's why I have posted my issue on GitHub because after trying many things I got stuck at one point. Currently, I got stuck at the BAD block issue.
Any other platform you can suggest?
