### ISSUE TITLE
Geth to 1.9.23, web3j (Java) call error

### ISSUE THREAD

**Issue by gitzkm** [ethereum/go-ethereum#21843]
After geth version is upgraded from 1.9.15 to 1.9.23, the same code reports an error through web3j (Java) call, and the error message is method thread ' java.lang.NoSuchMethodError ' exception.
It can be called when the original geth version is 1.9.15. Geth start command is

nohup ./geth --identity "secbro etherum" --rpc --rpccorsdomain "127.0.0.1" --datadir "/eth/ethdata" --port "30303" --rpcapi="db,eth,net,web3,personal,admin,miner" --rpcaddr 127.0.0.1 --rpcport 9721 --allow-insecure-unlock --syncmode "fast" >> /eth/ethdata/ethlog.log &

#### System information
Geth version: `1.9.15`
OS & Version: centos7.5
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
please provide the java code to reproduce this error

**Comment by ligi** [comment]
maybe related the removal of abi.U256() mentioned in #21837

**Comment by gitzkm** [comment]
> 请提供Java代码来重现此错误
Thank you. Part of my code is as follows:

HttpService httpService = new HttpService(ethConfig.getServiceUrl(), buildBasicAuthClient(ethConfig), false);
ethConfig.setWeb3j(Web3j.build(httpService));
ethConfig.setAdmin(Admin.build(httpService));
BigInteger lastBlockNumber = ethConfig.getWeb3j().ethBlockNumber().send().getBlockNumber();

web3j version
<dependency>
            <groupId>org.web3j</groupId>
            <artifactId>core</artifactId>
            <version>4.5.11</version>
        </dependency>

error info
![image](https://user-images.githubusercontent.com/9098704/99034979-7a8a6600-25b9-11eb-9a9a-914834280b62.png)
![image](https://user-images.githubusercontent.com/9098704/99035011-968e0780-25b9-11eb-83b2-fb0f10e097ec.png)
![image](https://user-images.githubusercontent.com/9098704/99035068-bc1b1100-25b9-11eb-96a0-f1d44f781d11.png)

**Comment by ligi** [comment]
can you provide ethlog.log when the error was triggered?

**Comment by gitzkm** [comment]
> can you provide ethlog.log when the error was triggered?
No error message found
![image](https://user-images.githubusercontent.com/9098704/99035905-8f67f900-25bb-11eb-8456-f70c06b250cf.png)

**Comment by gitzkm** [comment]
> can you provide ethlog.log when the error was triggered?
No error message found
![image](https://user-images.githubusercontent.com/9098704/99036183-26cd4c00-25bc-11eb-870c-23be6c51cf6e.png)

**Comment by ligi** [comment]
> Part of my code is as follows:

does it trigger this error with that part of the code only? Or is the error maybe triggered in other parts of your code?

**Comment by gitzkm** [comment]
> > Part of my code is as follows:
> 
> does it trigger this error with that part of the code only? Or is the error maybe triggered in other parts of your code?

The possibility is relatively small, when I even get version 1.9.15, there is no problem, the same code. Is there any restriction on RPC in the recent geth version update? Do you need to add other configuration in the startup command to allow RPC?

**Comment by karalabe** [comment]
@gitzkm Hmm, we've got a report from Infura that their infra was appending weird paths to the RPC endpoint, which old Geth versions ignored, but new ones rejected. I think that might be the case for you too, as the request you are making is to `http://IP:8545/eth`. Not sure why the library would add that `/eth` there, but it's wrong, the endpoint is simply the `http://IP:port`.

**Comment by gitzkm** [comment]
> @gitzkm Hmm, we've got a report from Infura that their infra was appending weird paths to the RPC endpoint, which old Geth versions ignored, but new ones rejected. I think that might be the case for you too, as the request you are making is to `http://IP:8545/eth`. Not sure why the library would add that `/eth` there, but it's wrong, the endpoint is simply the `http://IP:8545` (or `http://IP:8545/` should also work).

Thank you for your answer. This is only authenticated through nginx, which is set up between business system services and geth node services. The actual connection to geth is still the same as you said, for example http://IP :8545。 You can see my start command.
![image](https://user-images.githubusercontent.com/9098704/99329440-36e57400-28b9-11eb-9105-84a48de952a2.png)

**Comment by gitzkm** [comment]
> @gitzkm Hmm, we've got a report from Infura that their infra was appending weird paths to the RPC endpoint, which old Geth versions ignored, but new ones rejected. I think that might be the case for you too, as the request you are making is to `http://IP:8545/eth`. Not sure why the library would add that `/eth` there, but it's wrong, the endpoint is simply the `http://IP:8545` (or `http://IP:8545/` should also work).

nginx config




> > @gitzkm Hmm, we've got a report from Infura that their infra was appending weird paths to the RPC endpoint, which old Geth versions ignored, but new ones rejected. I think that might be the case for you too, as the request you are making is to `http://IP:8545/eth`. Not sure why the library would add that `/eth` there, but it's wrong, the endpoint is simply the `http://IP:8545` (or `http://IP:8545/` should also work).
> 
> Thank you for your answer. This is only authenticated through nginx, which is set up between business system services and geth node services. The actual connection to geth is still the same as you said, for example http://IP :8545。 You can see my start command.
> ![image](https://user-images.githubusercontent.com/9098704/99329440-36e57400-28b9-11eb-9105-84a48de952a2.png)

nginx config
![image](https://user-images.githubusercontent.com/9098704/99333427-72813d80-28bb-11eb-8e10-7587732d7b0e.png)

**Comment by gitzkm** [comment]
> @gitzkm Hmm, we've got a report from Infura that their infra was appending weird paths to the RPC endpoint, which old Geth versions ignored, but new ones rejected. I think that might be the case for you too, as the request you are making is to `http://IP:8545/eth`. Not sure why the library would add that `/eth` there, but it's wrong, the endpoint is simply the `http://IP:8545` (or `http://IP:8545/` should also work).

Thank you for your reply. It helped me a lot and solved this problem

**Comment by karalabe** [comment]
:+1:
