### ISSUE TITLE
abigen - Failed to generate ABI binding: duplicated identifier "totalSupply"(normalized "TotalSupply"), use --alias for renaming

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#21846]
#### System information

geth: 1.9.24-unstable
solc: 0.4.17+commit.bdeb9e52.Linux.g++
abigen: abigen version 1.9.24-unstable

#### Expected behavior

get TetherToken.sol from https://etherscan.io/address/0xdac17f958d2ee523a2206206994597c13d831ec7#code

generate go code by abigen successfully

#### Actual behaviour

abigen failed

```bash
$ abigen -sol TetherToken.sol -pkg usdt -out usdt.go
Fatal: Failed to generate ABI binding: duplicated identifier "totalSupply"(normalized "TotalSupply"), use --alias for renaming
```

**Comment by huahuayu** [comment]
@karalabe I have seen you discuss the duplicated identifier issue, can you please guide how to deal with it?

related issue: https://github.com/miguelmota/ethereum-development-with-go-book/issues/56

**Comment by ligi** [comment]
`./build/bin/abigen -sol tmp/token.sol --pkg usdt -out usdt.go --alias _totalSupply=yourOtherName
`
Please let us know how to improve the error message so it is more obvious - I thought `use --alias for renaming` is quite obvious

**Comment by huahuayu** [comment]
@ligi but from the `abigen -h`, it's said, it's comma-separated, so I tried 

```
abigen --bin=bin/TetherToken.bin --abi=abi/Contract.abi --pkg=usdt --out=usdt.go --alias=totalSupply,totalSupply1
```

so the help information is missleading?

**Comment by ligi** [comment]
coma separated in case there is more than one replacement. How would you write it so it is better understandable?

**Comment by huahuayu** [comment]
how about this?

```
 --alias value                      Comma separated aliases for function and event renaming, e.g. foo=_foo, bar=_bar
```

**Comment by rjl493456442** [comment]
@huahuayu Feel free to open a PR for the doc.

**Comment by huahuayu** [comment]
@rjl493456442 👌

**Comment by huahuayu** [comment]
I have raised a pr for this, pending review

https://github.com/ethereum/go-ethereum/pull/21875
