### ISSUE TITLE
install 1.9.24, installs golang 1.15.4 instead of 1.15.5 with brew

### ISSUE THREAD

**Issue by bg1156** [ethereum/go-ethereum#21845]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
Could you elaborate on what steps you took?

**Comment by bg1156** [comment]
terminal- brew install ethereum and that is what popped up, i'm guessing
not updated

byronglenn$ brew install ethereum
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
libcap
==> Updated Formulae
Updated 9 formulae.

==> Downloading
https://homebrew.bintray.com/bottles/ethereum-1.9.24.catalina.bottle.tar.gz
Already downloaded:
/Users/byronglenn/Library/Caches/Homebrew/downloads/d1bfd20275dcdd2480afa722fd39ef080f3fcf2f85e8f4d5391cf54e7d392bcd--ethereum-1.9.24.catalina.bottle.tar.gz
==> Pouring ethereum-1.9.24.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/ethereum/1.9.24: 19 files, 289.5MB
byrons-iMac:~ byronglenn$ geth
INFO [11-13|17:16:51.534] Starting Geth on Ethereum mainnet...
INFO [11-13|17:16:51.535] Bumping default cache on mainnet
provided=1024 updated=4096
INFO [11-13|17:16:51.536] Maximum peer count                       ETH=50
LES=0 total=50
INFO [11-13|17:16:51.564] Set global gas cap
cap=25000000
INFO [11-13|17:16:51.564] Allocated trie memory caches
clean=1023.00MiB dirty=1024.00MiB
INFO [11-13|17:16:51.564] Allocated cache and file handles
database=/Users/byronglenn/Library/Ethereum/geth/chaindata cache=2.00GiB
handles=5120
INFO [11-13|17:16:52.742] Opened ancient database
 database=/Users/byronglenn/Library/Ethereum/geth/chaindata/ancient
INFO [11-13|17:16:52.803] Initialised chain configuration
 config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true
EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000
Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir
Glacier: 9200000, YOLO v2: <nil>, Engine: ethash}"
INFO [11-13|17:16:52.803] Disk storage enabled for ethash caches
dir=/Users/byronglenn/Library/Ethereum/geth/ethash count=3
INFO [11-13|17:16:52.803] Disk storage enabled for ethash DAGs
dir=/Users/byronglenn/Library/Ethash count=2
INFO [11-13|17:16:52.805] Initialising Ethereum protocol
versions="[65 64 63]" network=1 dbversion=8
INFO [11-13|17:16:52.809] Loaded most recent local header
 number=10411324 hash="eea06e…ce565e" td=16225617625575555765761 age=4mo1w2d
INFO [11-13|17:16:52.809] Loaded most recent local full block      number=0
       hash="d4e567…cb8fa3" td=17179869184             age=51y7mo1w
INFO [11-13|17:16:52.809] Loaded most recent local fast block
 number=10406056 hash="53fc38…5f36a9" td=16213176316530212703949 age=4mo1w2d
INFO [11-13|17:16:52.809] Loaded last fast-sync pivot marker
number=11245798
INFO [11-13|17:16:52.813] Loaded local transaction journal
transactions=0 dropped=0
INFO [11-13|17:16:52.815] Regenerated local transaction journal
 transactions=0 accounts=0
INFO [11-13|17:16:52.847] Allocated fast sync bloom
 size=2.00GiB
INFO [11-13|17:16:52.850] Starting peer-to-peer node
instance=Geth/v1.9.24-stable/darwin-amd64/go1.15.4

**Comment by bg1156** [comment]
mind you i have it downloaded and can run the new but homebrew is not
updated for some reason although it should be

**Comment by fjl** [comment]
We cannot change the version that homebrew builds with because we do not maintain this formula ourself. If you want to be safe against a potential attack, you can always rebuild it yourself once the homebrew Go formula is updated to 1.15.5.
