### ISSUE TITLE
Block gaslimit target decays to 3141592 with custom genesis gasLimit

### ISSUE THREAD

**Issue by aiman** [ethereum/go-ethereum#2185]
I am running tests on a private network using the [example](http://jev.io/example_genesis.json) genesis block linked at the go-ethereum wiki page [Private network](https://github.com/ethereum/go-ethereum/wiki/Private-network), with the addition of a `1` ether allocation for address `0xffffffffffffffffffffffffffffffffffffffff`.

```
{
    "nonce": "0xdeadbeefdeadbeef",
    "timestamp": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x686f727365",
    "gasLimit": "0x8000000",
    "difficulty": "0x400",
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x3333333333333333333333333333333333333333",
    "alloc": {
        "fffffffffffffffffffffffffffffffffffffff0": {
            "balance": "1000000000000000000"
        }
    }
} 
```

Note I have left the `gasLimit` 0x8000000 (`134217728`) unchanged.

I am launching a single instance of geth `1.3.3` as follows:

```
geth \
    --mine \
    --networkid 1234 \
    --nodiscover \
    --maxpeers 0 \
    --genesis /deadbeef.json \
    --etherbase 0xffffffffffffffffffffffffffffffffffffffff
```

I observed that the block `gasLimit` decays toward the frontier gas target `3141592`:

```
> eth.getBlock(0).gasLimit
134217728
> eth.getBlock(500).gasLimit
82347720
> eth.getBlock(1000).gasLimit
50523715
> eth.getBlock(1500).gasLimit
30998596
```

Updating the genesis block with a `gasLimit` of 0x2fefe2 (`3141602`), the gasLimit reaches `3141592` in the next block and remains there:

```
> eth.getBlock(0).gasLimit
3141602
> eth.getBlock(1).gasLimit
3141592
> eth.getBlock(50).gasLimit
3141592
```

But this is not expected behaviour. `geth` should respect the `gasLimit` that is set in the imported genesis block `deadbeef.json`.

I traced the issue to `worker.commitNewWork()`, which makes a call to `core.CalcGasLimit(parent)` to determine the gaslimit for the next block. It seems like `core.CalcGasLimit()` references `params.GenesisGasLimit`, but that variable is not updated from the imported genesis file and so remains at the `geth` default of `3141592`. As a result the calculated gas target is adjusted downwards from the `parent` block gas limit towards `3141592`.

**Comment by karalabe** [comment]
The gas limit specified in the genesis block is the limit of the genesis block itself, not the chain. You cannot influence the chain's target gas limit from the outside using Geth. You could always build your own version of Geth that has a modified parameter set to target a different block limit, but I don't think we aim to support such a use case any time soon via CLI parameters.

**Comment by aiman** [comment]
That makes sense now. Thanks!

**Comment by qnimate** [comment]
@karalabe where in the source code I can change the gasLimit? You can point me to that file?

**Comment by Jacodelange** [comment]
@pnarayanprusty were you able to change the gasLimit of the chain?

**Comment by karalabe** [comment]
Just set your target gas limit in your miner to whatever you want `--targetgaslimit` and mine till it gets there.
