### ISSUE TITLE
2 days no peers in light mode

### ISSUE THREAD

**Issue by develflowing** [ethereum/go-ethereum#21866]
Hi there.

2 days no peers in light mode.
In fast mode it works fine.

#### System information
Geth version: `Geth/v1.9.24-stable-cc05b050/linux-amd64/go1.15.5`
OS & Version: `Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-52-generic x86_64)`

`> net.listening
true`
`> net.peerCount
0
`

**Comment by ChuckNorrison** [comment]
Still waiting for a magic event after 3 days running a light node. Some bootnodes to recommend for light nodes?

**Comment by develflowing** [comment]
Same problem started with fast mode. No peers

**Comment by holiman** [comment]
> Some bootnodes to recommend for light nodes?

Same ones as regular nodes, those bootnodes do serve lightclients (but I guess they become pretty full pretty fast)

**Comment by holiman** [comment]
> Same problem started with fast mode. No peers

@develflowing that sounds strange. Perhaps you can open a separate ticket with more info about your setup (networking) + logs

**Comment by ligi** [comment]
There is a plan to enable LES servers by default soon - but short term there is no good advice we can give.

**Comment by picatextra** [comment]
Revert to v1.9.24 worked for me.  #21880
