### ISSUE TITLE
joining --bootnodes with resolvable DNS name doesnt work

### ISSUE THREAD

**Issue by tayzlor** [ethereum/go-ethereum#2186]
If i try and use the --bootnodes arg and have something like - 

```
--bootnodes='enode://ENODE_IP@host1:30303'
```

This won't join - even though if I ```ping host1``` it resolves to its IP address. If I however replace the above with - 

```
--bootnodes='enode://ENODE_IP@127.0.3.1:30303'
```
It works just fine. Should the bootnodes arg be able to use DNS (via /etc/hosts for example) to resolve the IP address? The reason i'm asking as i'm trying to set up a cluster via Docker and using DNS vs IP addresses would be handy in this situation. I'm booting a container off the latest ethereum go docker container on the hub.

**Comment by fjl** [comment]
The lack of DNS resolution for bootnodes (and `addPeer`) is intended.
