### ISSUE TITLE
Missing trie node after 1 month of geth fully sync

### ISSUE THREAD

**Issue by Gbogdann93** [ethereum/go-ethereum#21865]
Hello, 

We're running full geth service and after ~ 1 - 2 months we're receiving this error inside geth (missing trie node) and resync from scratch is needed. This time we received the following error - this is pretty annoying since after some time geth is returning such error and we can't send transfers out or read blocks data because geth won't sync properly.

`exception: getDeleteStateObject (aa5952230aefc4c92a580c347a335bf7d4bb009d) error: missing trie node b639e8f6d3ec9d5a6d2b37d148f1e0d33b7a45e2e943b96e44d002c20bebc17d (path 0605) [] []`

#### System information

Geth version: 0.1.9.23
OS & Version: Debian 10

**Comment by ligi** [comment]
did the node run through or where there unclean shutdowns (e.g. due to reboots or crashes)?

**Comment by Gbogdann93** [comment]
@ligi We updated geth server at that time, but as you can see from geth logs, geth service was stopped. 
Here are full logs from that time 

>  Stopping geth Service Unit...
 INFO [11-17|21:13:05.022] Got interrupt, shutting down...
 DEBUG[11-17|21:13:05.023] RPC server shutting down
 TRACE[11-17|21:13:05.069] << PONG/v4                               id=599db395a3002e45 addr=142.93.219.249:30303  err=nil
 TRACE[11-17|21:13:05.070] Failed p2p handshake                     id=bf07c07983d92d07 addr=51.15.80.113:40333    conn=dyndial         err="too many peers"
 TRACE[11-17|21:13:05.086] Failed p2p handshake                     id=77390dbee2558aaf addr=5.9.16.119:30303      conn=dyndial         err="too many peers"
 DEBUG[11-17|21:13:05.092] Inserted forked block                    number=11234799 hash="8e627d…465b7d" diff=3421108272603742 elapsed=2.419s     txs=233 gas=12434846 uncles=0  root="7bf0c1…15971a"
 TRACE[11-17|21:13:05.101] >> FINDNODE/v4                           id=bfc182bbd8ac79e4 addr=3.20.44.56:30303      err=nil
 TRACE[11-17|21:13:05.302] Failed p2p handshake                     id=12355c0fc2f6a2aa addr=70.112.65.167:30303   conn=dyndial         err="too many peers"
 TRACE[11-17|21:13:05.419] Dial error                               id=bfc182bbd8ac79e4 addr=3.20.44.56:30303      conn=dyndial         err="i/o timeout"
 TRACE[11-17|21:13:05.426] Rejected peer                            id=bf1114e03473a29d addr=192.241.158.217:30303 conn=dyndial         err="useless peer"
 INFO [11-17|21:13:05.531] HTTP server stopped                      endpoint=127.0.0.1:8545
 DEBUG[11-17|21:13:05.531] RPC server shutting down
 INFO [11-17|21:13:05.531] IPC endpoint closed                      url=/home/cryptodaemon/.ethereum/geth.ipc
 DEBUG[11-17|21:13:05.531] RPC server shutting down
 DEBUG[11-17|21:13:05.531] RPC connection read error                err=EOF
 DEBUG[11-17|21:13:05.531] Transaction receipt download terminated  err="syncing canceled (requested)"
 DEBUG[11-17|21:13:05.531] Block body download terminated           err="syncing canceled (requested)"
 DEBUG[11-17|21:13:05.531] Header download terminated               peer=03437da1d05c86e5
 TRACE[11-17|21:13:05.611] FINDNODE failed                          id=bfc182bbd8ac79e4 failcount=14   dropped=true  err="RPC timeout"
 TRACE[11-17|21:13:05.611] >> PING/v4                               id=bff5bcd8333351a0 addr=188.166.236.177:30303 err=nil
 TRACE[11-17|21:13:05.695] << PONG/v4                               id=a53ebca5e2c81a2d addr=188.166.236.177:30303 err="unsolicited reply"
 TRACE[11-17|21:13:05.777] >> FINDNODE/v4                           id=bfff9cbea2caf862 addr=54.224.75.141:30303   err=nil
 TRACE[11-17|21:13:05.934] >> FINDNODE/v4                           id=bff835afcd7f7949 addr=142.93.219.249:30303  err=nil
 TRACE[11-17|21:13:06.023] << NEIGHBORS/v4                          id=599db395a3002e45 addr=142.93.219.249:30303  err="unsolicited reply"
 TRACE[11-17|21:13:06.086] Dial error                               id=bfff9cbea2caf862 addr=54.224.75.141:30303   conn=dyndial         err="i/o timeout"
 TRACE[11-17|21:13:06.262] FINDNODE failed                          id=bfff9cbea2caf862 failcount=2    dropped=false err="RPC timeout"
 TRACE[11-17|21:13:06.263] >> PING/v4                               id=bff7667119311a20 addr=206.189.23.182:30303  err=nil
 TRACE[11-17|21:13:06.434] FINDNODE failed                          id=bff835afcd7f7949 failcount=1    dropped=false err="RPC timeout"
 TRACE[11-17|21:13:06.614] >> FINDNODE/v4                           id=bff5bcd8333351a0 addr=188.166.236.177:30303 err=nil
 TRACE[11-17|21:13:06.711] << NEIGHBORS/v4                          id=a53ebca5e2c81a2d addr=188.166.236.177:30303 err="unsolicited reply"
 TRACE[11-17|21:13:07.114] FINDNODE failed                          id=bff5bcd8333351a0 failcount=2    dropped=false err="RPC timeout"
 TRACE[11-17|21:13:07.264] >> FINDNODE/v4                           id=bff7667119311a20 addr=206.189.23.182:30303  err=nil
 DEBUG[11-17|21:13:07.311] Inserted forked block                    number=11234800 hash="8e0379…062340" diff=3416096884581122 elapsed=2.216s     txs=178 gas=12475288 uncles=0  root="91f5c9…57f2f9"
 INFO [11-17|21:13:07.311] Imported new chain segment               blocks=3    txs=644 mgas=37.391 elapsed=8.719s     mgasps=4.288 number=11234800 hash="8e0379…062340" age=6d14h19m            dirty=4.83MiB
 DEBUG[11-17|21:13:07.314] Abort during block processing
 DEBUG[11-17|21:13:07.314] Abort during blocks processing
 DEBUG[11-17|21:13:07.315] Synchronisation terminated               elapsed=43.578s
 WARN [11-17|21:13:07.315] Synchronisation failed, retrying         err="content processing canceled (requested)"
 DEBUG[11-17|21:13:07.315] Ethereum message handling failed         id=bf799214872f28e7 conn=dyndial         err=EOF
 DEBUG[11-17|21:13:07.315] Removing Ethereum peer                   peer=bf799214872f28e7
 TRACE[11-17|21:13:07.315] Unregistering sync peer                  peer=bf799214872f28e7
 DEBUG[11-17|21:13:07.316] Removing p2p peer                        peercount=2 id=bf799214872f28e7 duration=3.831s      req=false err="client quitting"
 DEBUG[11-17|21:13:07.316] Ethereum message handling failed         id=03437da1d05c86e5 conn=dyndial         err=EOF
 DEBUG[11-17|21:13:07.316] Removing Ethereum peer                   peer=03437da1d05c86e5
 TRACE[11-17|21:13:07.316] Unregistering sync peer                  peer=03437da1d05c86e5
 DEBUG[11-17|21:13:07.316] Removing p2p peer                        peercount=1 id=03437da1d05c86e5 duration=43.860s     req=false err="client quitting"
 DEBUG[11-17|21:13:07.316] Ethereum message handling failed         id=bfbf25f2165e0d18 conn=dyndial         err=EOF
 DEBUG[11-17|21:13:07.316] Removing Ethereum peer                   peer=bfbf25f2165e0d18
 TRACE[11-17|21:13:07.316] Unregistering sync peer                  peer=bfbf25f2165e0d18
 INFO [11-17|21:13:07.316] Ethereum protocol stopped
 INFO [11-17|21:13:07.316] Transaction pool stopped
 DEBUG[11-17|21:13:07.316] Removing p2p peer                        peercount=0 id=bfbf25f2165e0d18 duration=10.517s     req=false err="client quitting"
 INFO [11-17|21:13:07.317] Writing cached state to disk             block=11234924 hash="80b3a3…8d15e5" root="101621…47cce9"
 INFO [11-17|21:13:07.320] Persisted trie from memory database      nodes=0 size=0.00B     time=2.641589ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=10661 livesize=3.83MiB
 INFO [11-17|21:13:07.321] Writing cached state to disk             block=11234923 hash="427744…e6767c" root="479c17…c20565"
 INFO [11-17|21:13:07.321] Persisted trie from memory database      nodes=0 size=0.00B     time="3.735µs"  gcnodes=0 gcsize=0.00B gctime=0s livenodes=10661 livesize=3.83MiB
 INFO [11-17|21:13:07.321] Writing cached state to disk             block=11234797 hash="294ce3…ff7174" root="40f040…84416b"
 INFO [11-17|21:13:07.321] Persisted trie from memory database      nodes=0 size=0.00B     time="1.651µs"  gcnodes=0 gcsize=0.00B gctime=0s livenodes=10661 livesize=3.83MiB
 DEBUG[11-17|21:13:07.324] Dereferenced trie from memory database   nodes=777 size=323.68KiB time=2.765316ms gcnodes=777 gcsize=323.68KiB gctime=2.764494ms livenodes=9884  livesize=3.52MiB
 DEBUG[11-17|21:13:07.327] Dereferenced trie from memory database   nodes=835 size=353.38KiB time=2.413414ms gcnodes=1612 gcsize=677.05KiB gctime=5.177179ms livenodes=9049  livesize=3.17MiB
 DEBUG[11-17|21:13:07.345] Dereferenced trie from memory database   nodes=9048 size=3.17MiB   time=18.033112ms gcnodes=10660 gcsize=3.83MiB   gctime=23.209752ms livenodes=1     livesize=0.00B
 INFO [11-17|21:13:07.346] Writing clean trie cache to disk         path=/home/cryptodaemon/.ethereum/geth/triecache threads=4
 INFO [11-17|21:13:07.367] Persisted the clean trie cache           path=/home/cryptodaemon/.ethereum/geth/triecache elapsed=20.487ms
 INFO [11-17|21:13:07.367] Blockchain stopped
 TRACE[11-17|21:13:07.367] Ethash remote sealer is exiting
 DEBUG[11-17|21:13:07.377] Read error                               err="accept tcp [::]:30303: use of closed network connection"
 DEBUG[11-17|21:13:07.377] Deleting port mapping                    proto=tcp extport=30303 intport=30303 interface="UPnP or NAT-PMP"
 TRACE[11-17|21:13:07.377] P2P networking is spinning down
 DEBUG[11-17|21:13:07.377] UDP read error                           err="read udp [::]:30303: use of closed network connection"
 DEBUG[11-17|21:13:07.377] Deleting port mapping                    proto=udp extport=30303 intport=30303 interface="UPnP or NAT-PMP"
 TRACE[11-17|21:13:07.377] Dial error                               id=bff2936dd84c9d14 addr=101.32.207.238:30303  conn=dyndial         err="operation was canceled"
 TRACE[11-17|21:13:07.377] Dial error                               id=5c23f75d4945a0fb addr=54.255.218.140:30303  conn=dyndial         err="operation was canceled"
 TRACE[11-17|21:13:07.377] Dial error                               id=ffbd85e4bda67e20 addr=95.217.236.3:30303    conn=dyndial         err="operation was canceled"
 TRACE[11-17|21:13:07.378] Dial error                               id=bfe7d2d51a0d898f addr=81.34.215.19:30303    conn=dyndial         err="operation was canceled"
 TRACE[11-17|21:13:07.378] Dial error                               id=bf8dd37f45c3aa53 addr=223.167.1.209:30303   conn=dyndial         err="operation was canceled"
 TRACE[11-17|21:13:07.378] Dial error                               id=bfce371d9228c899 addr=13.57.71.117:8090     conn=dyndial         err="operation was canceled"
 TRACE[11-17|21:13:07.386] DNS discovery lookup                     name=SAY53EYESKYB3WHH4BFAJVYXIY.all.mainnet.ethdisco.net err=nil
 Stopped geth Service Unit.

**Comment by holiman** [comment]
Thanks for the report. We are working on some tooling to repair the state, when situations like these arise. It's by no means a trivial task, however, and the tooling we have is not yet production ready. 

If you want to make an attempt at repairing it, however, you could try this PR: https://github.com/ethereum/go-ethereum/pull/21650 . After building geth, you would run `./build/bin/geth repairtrie`. That will 'clean out' some corruptions, and put the node into a state where, next time you restart it, it will fast-sync to head, but based upon the existing database, so the healing should go much quicker than a regular fast-sync. 

There's no guarantee it will work, but it's definitely faster than a sync from scratch. If you are rnining an archive node, the end result might be that the state is missing for some blocks, but you would still retain most of all states.

**Comment by holiman** [comment]
Also, do you have any more context (log lines) around the `exception: getDeleteStateObject (aa5952230aefc4c92a580c347a335bf7d4bb009d) error: missing trie node b639e8f6d3ec9d5a6d2b37d148f1e0d33b7a45e2e943b96e44d002c20bebc17d (path 0605) ` error?

**Comment by Gbogdann93** [comment]
@holiman  

> INFO [11-18|01:21:36.139] Imported new chain segment               blocks=9    txs=1516 mgas=112.259 elapsed=8.691s    mgasps=12.916 number=11255428 hash="e33e3c…348894" age=3d14h21m dirty=255.19MiB
WARN [11-18|01:21:40.479] Checkpoint challenge timed out, dropping id=4cd05483417fc6d3 conn=dyndial         addr=46.183.218.196:30303 type=Geth/v1.9.10-stable-...
INFO [11-18|01:21:44.168] Imported new chain segment               blocks=9    txs=870  mgas=112.388 elapsed=8.029s    mgasps=13.997 number=11255437 hash="bf9e6b…ee79f8" age=3d14h21m dirty=254.65MiB
INFO [11-18|01:21:52.291] Imported new chain segment               blocks=10   txs=1024 mgas=99.828  elapsed=8.122s    mgasps=12.290 number=11255447 hash="2cd480…1ebb43" age=3d14h20m dirty=254.35MiB
WARN [11-18|01:21:55.830] Served personal_sendTransaction          conn=127.0.0.1:48400 reqid=2  t=873.179286ms err="insufficient funds for gas * price + value"
WARN [11-18|01:21:55.832] Served eth_call                          conn=127.0.0.1:48400 reqid=5  t="141.72µs"   err="err: insufficient funds for gas * price + value (supplied gas 100000)"
WARN [11-18|01:21:56.961] Served personal_sendTransaction          conn=127.0.0.1:48400 reqid=6  t=1.128435431s err="insufficient funds for gas * price + value"
WARN [11-18|01:21:56.964] Served eth_call                          conn=127.0.0.1:48400 reqid=9  t="217.179µs"  err="err: insufficient funds for gas * price + value (supplied gas 100000)"
WARN [11-18|01:21:57.960] Served personal_sendTransaction          conn=127.0.0.1:48400 reqid=10 t=994.411374ms err="insufficient funds for gas * price + value"
WARN [11-18|01:21:57.961] Served eth_call                          conn=127.0.0.1:48400 reqid=13 t="128.586µs"  err="err: insufficient funds for gas * price + value (supplied gas 100000)"
WARN [11-18|01:21:58.906] Served eth_getBalance                    conn=127.0.0.1:48400 reqid=50 t="188.187µs"  err="getDeleteStateObject (696334d05d8c57b94a8f0a7deddff4cdf90950cb) error: missing trie node 76039d8a7232257a741cb7f310d551ec5a7e0136e32526a2a058b3cc1c855307 (path 0402)"

**Comment by ligi** [comment]
The DB seems to be corrupted. It would need repair as @holiman suggested.
Is this an archive node you are running?

**Comment by Gbogdann93** [comment]
@ligi No, this is new geth server setup ~ 1 month ago. 
Geth is setup in **-syncmode=full** . We got this issue after some time also in other servers where we're running geth in same mode.

**Comment by wbt** [comment]
Do you have the `--gcmode "archive"` flag in your startup command? That might be the cause of the issue.

**Comment by Gbogdann93** [comment]
@wbt  No we don't have such flag in our startup command

**Comment by wbt** [comment]
Add that in before your next resync, and keep in there for your subsequent startups.  Otherwise it probably will start to prune older data after a month or two to save on disk space, and you'll get the missing trie node error.  Speaking from experience, I can agree that's frustrating and hard to debug, but hopefully that flag will help solve it!

(Note: also make sure you have plenty of disk space...things can silently fail when the disk fills, in a way that can also be puzzling and nontrivial to debug.)

**Comment by Gbogdann93** [comment]
@wbt This is not the case.
We have plenty of space on our servers and when issue with "missing trie node" happened we just keep keystores folder and started new geth sync from scratch without having any other data in our geth directory.

**Comment by holiman** [comment]
> Otherwise it probably will start to prune older data after a month or two to save on disk space, and you'll get the missing trie node error.

That's not quite how it works. Anyway, I'd recommend running the PR I linked, to see where the corruption resides, and also see if the database can be healed.

**Comment by jayboy-mabushi** [comment]
@wbt where you able to resolve this issue?

**Comment by wbt** [comment]
@jayboy-mabushi I was able to solve these issues when I encountered them by adding `--gcmode "archive"` as a startup flag to geth + ensuring plenty of disk space, and suggested that to OP...but it's not clear to me what's going on for them.
