### ISSUE TITLE
Fast sync not fast? How long will pull states?

### ISSUE THREAD

**Issue by develflowing** [ethereum/go-ethereum#21868]
Hi there.

#### System information

Geth version: `Geth/v1.9.24-stable-cc05b050/linux-amd64/go1.15.5`
OS & Version: `Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-52-generic x86_64)`
SSD: `1Tb WD Green [WDS100T2G0A] (R545/WMB/s)`
Working time: `72 hours`
Startup: ` geth --http --http.api eth,web3,personal`

> eth.syncing
{
  currentBlock: 11281227,
  highestBlock: 11281353,
  knownStates: 585146654,
  pulledStates: 585112812,
  startingBlock: 11278433
}

How long will pull states?

Thanks.

**Comment by MariusVanDerWijden** [comment]
should be ~800.000.000 states or so, see https://github.com/ethereum/go-ethereum/issues/15616

**Comment by develflowing** [comment]
> should be ~800.000.000 states or so, see #15616

Thank You so match!
