### ISSUE TITLE
Latest develop mines to 0x0000... if etherbase is set via the commandline

### ISSUE THREAD

**Issue by ppratscher** [ethereum/go-ethereum#2188]
The latest develop branch seems to mine to 0x0000000000000000000000000000000000000000 if the coinbase/etherbase address is set via the commandline flag.

To reproduce:
geth  --rpc --etherbase 0xabababa...
Mine & notice that mined blocks have 0x0000000000000000000000000000000000000000 set as their miner.

**Comment by ppratscher** [comment]
A lot of people have already mined block to the zero address, see: https://etherchain.org/account/0x0000000000000000000000000000000000000000#blocks

**Comment by karalabe** [comment]
@ppratscher Could you please check this PR https://github.com/ethereum/go-ethereum/pull/2189 if it works for you?

**Comment by ppratscher** [comment]
yes, I can confirm the PR fixes this issue!

**Comment by karalabe** [comment]
Great, thank you! :)
