### ISSUE TITLE
./geth --datadir data dumpgenesis

### ISSUE THREAD

**Issue by username1565** [ethereum/go-ethereum#21881]
Try to do this: https://geth.ethereum.org/docs/interface/private-network

After `./geth --datadir data init genesis.json`,
the command `./geth --datadir data dumpgenesis` return previous genesis.

How to sucessfully re-initialize the old genesis.json?

**Comment by wbt** [comment]
Have you tried clearing your datadir (or making a new one that starts empty) and running the init command from the first line of your post?

**Comment by username1565** [comment]
Yes, I did try to run `./geth --datadir="pathway_to_data" removedb`
and ./geth --datadir="pathway_to_data" init "pathway_to_genesis.json"
but after `./geth --datadir="pathway_to_data" dumpgenesis`, I see the same result.
I see default genesis in console.

Moreover, I did try to run `rm -rf "pathway_to_data"`, and `mkdir "pathway_to_data"`, and init geth with genesis again:
and ./geth --datadir="pathway_to_data" init "pathway_to_genesis.json"
but after `./geth --datadir="pathway_to_data" dumpgenesis`, I see the same result too.
I see default genesis in console, with ethereum premine:
https://github.com/ethereum/go-ethereum/blob/23524f8900bceb0c921b61cbf6f51f38325e2971/core/genesis.go#L335-L345
https://github.com/ethereum/go-ethereum/blob/23524f8900bceb0c921b61cbf6f51f38325e2971/core/genesis_alloc.go#L24

**Comment by username1565** [comment]
@wbt, yes, I did try to run
```sh
# remove database in dir
./geth --datadir="pathway_to_data" removedb
# initialize with new genesis.json
./geth --datadir="pathway_to_data" init "pathway_to_genesis.json"
# but after 
./geth --datadir="pathway_to_data" dumpgenesis
# I see the same result. I see default genesis in console.
```

Moreover, I did try to run:
```sh
# remove database directory with all the files:
rm -rf "pathway_to_data"
# and create this directory again:
mkdir "pathway_to_data"
# and init geth with genesis again:
./geth --datadir="pathway_to_data" init "pathway_to_genesis.json"
# but after dumpgenesis:
./geth --datadir="pathway_to_data" dumpgenesis
# I see the same result too. Old, default genesis, in console stdout.
```
I see default genesis in console:
https://github.com/ethereum/go-ethereum/blob/23524f8900bceb0c921b61cbf6f51f38325e2971/core/genesis.go#L335-L345
with ethereum pre-mine:
https://github.com/ethereum/go-ethereum/blob/23524f8900bceb0c921b61cbf6f51f38325e2971/core/genesis_alloc.go#L24

Also, I did try to change `--networkid=2020` and did try with that [`2020-genesis.json`](https://medium.com/coinmonks/creating-and-exploring-a-private-ethereum-blockchain-using-geth-d71afc5cdcf9):

```sh
#networkid changed in config
./geth --datadir="pathway_to_data" --networkid=2020 dumpconfig 

# but old default genesis for networkid=1
./geth --datadir="pathway_to_data" removedb
./geth --datadir="pathway_to_data" --networkid=2020 init "pathway_to_2020-genesis.json"
./geth --datadir="pathway_to_data" --networkid=2020 dumpgenesis
```

**Comment by wbt** [comment]
A few questions that may or may not help:
What networkid is in your genesis file? How does your genesis file differ from the default?  Have you opened the pathway_to_2020-genesis.json file in a text editor to verify that it has those differences?

**Comment by username1565** [comment]
@wbt 
I tryed to use [2020-genesis.json, from this article](https://medium.com/coinmonks/creating-and-exploring-a-private-ethereum-blockchain-using-geth-d71afc5cdcf9), and there is specified
```
"chainId": 2020,
```
No, networkid param. This param, I set, using command-line argument `--networkid=2020`,
`./geth --datadir="pathway_to_data" --networkid=2020 init "pathway_to_2020-genesis.json"`
and I'm not sure the `networkid` is the same as `chainId`.
Yes, this file is opening, using the command `nano "pathway_to_2020-genesis.json"`, and this contains correct `2020-genesis.json`, like writted in that article.
It seems, like `2020-genesis.json` writting is sucessfull, but command `dumpgenesis`, seems like working incorrect, after init `geth` with `custom genesis`, and even after specify the `--networkid=2020` argument.
Maybe, you can test it, and see the source code, and change something.

Seems, like `networkid=1`, somewhere, by default, so default genesis, for ETH-mainnet is returned,or maybe... Writted on init geth...

**Comment by wbt** [comment]
As some guideposts for others trying to debug this:
The dumpgenesis command was added in [PR #20191](https://github.com/ethereum/go-ethereum/pull/20191), and it looks like  a [merge commit](https://github.com/ethereum/go-ethereum/commit/711ed74e091f2ada6e2aa84e5e62b9696b589d8a) was included starting in v1.9.11.

That PR had a post-merge [comment](https://github.com/ethereum/go-ethereum/pull/20191#issuecomment-595134049) "Question: shouldn't this function also dump a custom genesis?" which never got a response.  Maybe the correct response is "it should but it currently doesn't." 

Though I haven't tested it in any detail, I suspect [this line](https://github.com/ethereum/go-ethereum/blob/3ef52775c4756b7cbdc28b807eb4600127a9a873/cmd/geth/chaincmd.go#L262) (`genesis := utils.MakeGenesis(ctx)`) is returning nil, causing the next few lines to return `core.DefaultGenesisBlock()`.  Having a look at the [function](https://github.com/ethereum/go-ethereum/blob/23524f8900bceb0c921b61cbf6f51f38325e2971/cmd/utils/flags.go#L1795) I think is being called, I see a switch statement which looks like it might only return non-nil if the network is one of the predefined test networks.

The code does not make me think this would be likely to work as OP expects, though the documentation does. 

Thanks for reporting!

**Comment by wbt** [comment]
I should also note that I don't think all developer chains should be considered ephemeral.  There might be some non-ephemeral private ETH chains out there serving a useful purpose; part of the value of open-source software is the possibility of using it outside of its original context/chain.

**Comment by username1565** [comment]
>Thanks for reporting!
Ok, no problem. Maybe your developers, can fix it, in new releases,
because I do not know GoLang. Just keep attention on this.

>I should also note that I don't think all developer chains should be considered ephemeral.
>There might be some non-ephemeral private ETH chains out there serving a useful purpose;
>part of the value of open-source software is the possibility of using it outside of its original context/chain.

Yes, I know, but the main think, that I wanted to check, is the following thing:
when in Private Network, selected `chainId=1`, or/and `networkid=1`,
it seems, like default `genesis.json`, with ethereum-premine,
is writting in the custom network too.
But with that bugs of `dumpgenesis`, I'm not sure in this,
because `dumpgenesis` return default genesis, after `init geth` with custom genesis.
Also, `nano "pathway_to_data"/geth/chaindata/000001.log` can not be opened,
when some blocks contains in blockhain of private network.

**Comment by username1565** [comment]
@wbt 

>Thanks for reporting!

Ok, no problem. Maybe your developers, can fix it, in new releases,
because I do not know GoLang. Just keep attention on this.

>I should also note that I don't think all developer chains should be considered ephemeral.
>There might be some non-ephemeral private ETH chains out there serving a useful purpose;
>part of the value of open-source software is the possibility of using it outside of its original context/chain.

Yes, I know, but the main think, that I wanted to check, is the following thing:
when in Private Network, selected `chainId=1`, or/and `networkid=1`,
it seems, like default `genesis.json`, with ethereum-premine,
is writting in the custom network too.
But with that bugs of `dumpgenesis`, I'm not sure in this,
because `dumpgenesis` return default genesis, after `init geth` with custom genesis.
Also, `nano "pathway_to_data"/geth/chaindata/000001.log` can not be opened,
when some blocks contains in blockhain of private network,
so I do not see any way to verify the current genesis, in the custom private-network.

**Comment by wbt** [comment]
[This comment](https://github.com/ethereum/go-ethereum/issues/21881#issuecomment-731500286) was intended for other geth developers, based on a comment in the code stating the opposite. 
 
>when in Private Network, selected chainId=1, or/and networkid=1,

In general, you should not be using a custom/private genesis/network with chainId/networkId = 1. That id is for mainnet, and it's reasonable to expect the mainnet genesis coming back from that.  
However, from the OP and comments above this Issue is understood to be limited to where the genesis block has a chainId not belonging to mainnet or a known public testnet, and you're running geth with the command line flag for this other networkId/chainId.  When that is true, as it seems to be for you, I agree that you should get the private-net genesis back per documentation and reasonable expectations but that by looking at current code I don't think you would.
