### ISSUE TITLE
Light mode (not looking for peers ?)

### ISSUE THREAD

**Issue by picatextra** [ethereum/go-ethereum#21880]
Geth VERSION:  1.9.24-stable-cc05b050

I've been using Geth with Light mode for 1 year, after a server reboot, it always take a few hours to find a peer.
But this time things looks different , the  `Looking for peers` appears to have bigger intervals.
Also many `tried=0` ... never saw that behavior before.

Nov 20 01:23:30 vultr.guest geth[2987]: INFO [11-20|01:23:30.799] Looking for peers                        peercount=0 tried=0 static=0
Nov 20 01:08:14 vultr.guest geth[2987]: INFO [11-20|01:08:14.799] Looking for peers                        peercount=0 tried=0 static=0
Nov 20 00:51:13 vultr.guest geth[2987]: INFO [11-20|00:51:13.799] Looking for peers                        peercount=0 tried=1 static=0
Nov 20 00:50:38 vultr.guest geth[2987]: INFO [11-20|00:50:38.799] Looking for peers                        peercount=0 tried=0 static=0

**Comment by picatextra** [comment]
Downloaded geth-linux-amd64-**1.9.23**-8c2f2715 , now it looks better

INFO [11-20|16:10:03.070] Looking for peers                        peercount=0 tried=11 static=0
INFO [11-20|16:10:13.142] Looking for peers                        peercount=1 tried=15 static=0

**Comment by tnt288** [comment]
Hi I don't I did not have any training in Android, but I learned old programming languages ​​like Basic and Pascal a long time ago, if you can teach me how to install and run an API in GetHub Thankful

**Comment by turboboost55** [comment]
Just to chime in here ... I'm seeing pretty much the same thing with v1.9.24.  It will not find any peers.  For me it prints out the usual first 15 lines or so, ending with 
```
...
...
INFO [11-24|21:08:34.524] HTTP server started                      endpoint=127.0.0.1:8545 cors= vhosts=localhost
WARN [11-24|21:08:34.524] Light client mode is an experimental feature 
INFO [11-24|21:08:34.524] New local node record                    seq=1 id=dadfd2474c4096bc ip=127.0.0.1 udp=30303 tcp=30303
INFO [11-24|21:08:34.525] Started P2P networking                   self=enode://.....@127.0.0.1:30303
```

and then it just sits there and does nothing ... for hours.  I downgraded to v1.9.23 and everything is back to normal.

**Comment by zsfelfoldi** [comment]
Sorry, my mistake, I accidentally disabled DNS discovery (regardless of the --nodiscover flag) and did not notice because my client already had known peers in the server pool. Fixed by https://github.com/ethereum/go-ethereum/pull/21906
