### ISSUE TITLE
Allow setting permission for geth.ipc

### ISSUE THREAD

**Issue by colourful-land** [ethereum/go-ethereum#21901]
# Rationale

Why should this feature exist?

Sysop creates a specialized user for each dæmon for security reasons, in this case, a user called `geth`. However, developers on the same host needs to access the IPC as their own login user.

What are the use-cases?

Developer `john` wishes to atttach through geth.ipc which is owned by user `geth` on the same server. He shares a user group with geth (e.g. adm)

# Workaround

Suppose `john` is a member of `geth`'s group. Currently, john can run:

    $ sudo chmod 660 /home/geth/.ethereum/geth.ipc
    $ geth attach ipc://home/geth/.ethereum/geth.ipc

This has to be done everytime the geth dæmon starts. To do it automatically requires  a crontab line like this

    * * * * * chmod 660 /path/to/geth.ipc

# Implementation

Do you have ideas regarding the implementation of this feature?

Adding `--ipcumask` which accepts the same value as `umask` and use it for the file created by `--ipcpath`.

Are you willing to implement this feature?

Lacking domain knowledge (programming in go)

**Comment by ligi** [comment]
Thanks for the feature request. Really wonder if this should be part of the geth command - I rather see this as responsibility of the startup scripts that start geth (also think this would be better than doing it via crontab).
Have you seen this design pattern this way in other software? If so can you provide us with examples?

**Comment by colourful-land** [comment]
> Thanks for the feature request. Really wonder if this should be part of the geth command - I rather see this as responsibility of the startup scripts that start geth (also think this would be better than doing it via crontab).
> Have you seen this design pattern this way in other software? If so can you provide us with examples?

Yes, typically, one configures umask through systemd

````
[Service]
UMask=0002
````

However, currently, geth seem to enforce 600 even though the environment is configured otherwise (e.g. 660). Unless geth can turn of this enforcement this issue remains in the hands of geth dæmon.

One argument for geth to take the matter into its own hand is that today's blockchain worlds are not operated by sysops (the old-time terminology for devops), who rarely uses systemd. Observe that geth's Ubuntu packager didn't ship a systemd configuration like every other dæmon on Linux, and that the official tutorial recommended running geth directly, but geth still wants to protect these users from a misconfigured environment unsuitable for running dæmons.

If you take the matter into your own hands, you will need to also take into your own hands the advanced options for fine tuning.

**Comment by samuelhbne** [comment]
Guess we can change the IPC ownership after starting geth as specific user from daemon startup script, which supposed to be running with privilege.

**Comment by colourful-land** [comment]
> Guess we can change the IPC ownership after starting geth as specific user from daemon startup script, which supposed to be running with privilege.

How would you time that? start the dæmon and wait for 1s?

**Comment by ligi** [comment]
waiting for a magic time sounds brittle to me. I think better options would be:
 * wait for "IPC endpoint opened" in the log
 * wait for the IPC file to exist (guess this would be my preferred option)

**Comment by colourful-land** [comment]
> waiting for a magic time sounds brittle to me. I think better options would be:
>     * wait for the IPC file to exist (guess this would be my preferred option)

It can exist because a zombie process didn't remove it, so if I had to choose between the two, waiting for the right message in the log then wait for the file.

**Comment by ligi** [comment]
The script could remove the file as step1 to fight the zombies

**Comment by holiman** [comment]
Some historical discussion about this feature can be found here: https://github.com/ethereum/go-ethereum/pull/21364

**Comment by holiman** [comment]
I don't think we will implement this feature. Closing this
