### ISSUE TITLE
After crash, Head state missing, repairing - age=1d17h26m

### ISSUE THREAD

**Issue by SjonHortensius** [ethereum/go-ethereum#21902]
#### System information

Geth version: `1.9.24`
OS & Version: Linux

#### Expected behaviour

While some regression is expected, repairing the Head state should not revert the state more than ~ an hour.

#### Actual behaviour

After killing my geth process forcefully, the head state was missing and repaired. However, while the chain was fully up-to-date it was 'repaired' to a state of almost two days ago, meaning I had to resync two days of txs again. Why?

#### Steps to reproduce the behaviour

Forcefully kill geth, observe repair of head.

#### Backtrace

````
Loaded most recent local header          number=11326453 hash="5d8615…cdb31d" td=18945964326052332637063 age=59s
Loaded most recent local full block      number=11326453 hash="5d8615…cdb31d" td=18945964326052332637063 age=59s
Loaded most recent local fast block      number=11326453 hash="5d8615…cdb31d" td=18945964326052332637063 age=59s
Loaded last fast-sync pivot marker       number=10772021
Head state missing, repairing            number=11326453 hash="5d8615…cdb31d"
Loaded most recent local header          number=11326453 hash="5d8615…cdb31d" td=18945964326052332637063 age=1m29s
Loaded most recent local full block      number=11315145 hash="7f47a8…be41c7" td=18906307610258064779456 age=1d17h26m
Loaded most recent local fast block      number=11326453 hash="5d8615…cdb31d" td=18945964326052332637063 age=1m29s
````

**Comment by rjl493456442** [comment]
It's the expected behavior. During the normal block processing, Geth won't flush out the state change every block. Instead, it tries to GC in the memory in order to reduce the disk size.

But Geth will periodically flush the state change if:
- The cumulative "evm execution time" is more than the configured value(it's 1 hour by default)
- The accumulated memory usage beyond the limitation.

The idea for periodically flushing the state change by cumulative evm execution time is:
- The flushed data amount is limited, the state size growth in the disk can be controlled
- One hour repairing time is acceptable

**Comment by SjonHortensius** [comment]
@rjl493456442 that's actually pretty clever, thanks for the reply. I agree 1 hour of syncing is acceptable, I didn't realize that metric was already being used. For the sake of completeness, can you confirm you are referring to the `TrieCleanCacheRejournal` aka `--cache.trie.rejournal` setting?

**Comment by rjl493456442** [comment]
If I remember correctly, the interval can only be changed via config file.


```shell
[Eth]
TrieCleanCacheRejournal = 3600000000000
```

You can firstly dump out the config file via `geth dumpconfig > config.toml`, then start with the modified config

**Comment by rjl493456442** [comment]
Btw, the order for applying the configs is: 

- First load the default config
- Apply the config in the config file if it's specified
- Apply the config from the CLI flags

So you can still apply the other configs via CLI flags but only change this interval in config file.

**Comment by SjonHortensius** [comment]
thanks for verifying :+1:
