### ISSUE TITLE
How can I mint my own(raw) token on my own public chain and contract tokens which is deploy on it at the same time?

### ISSUE THREAD

**Issue by Jackie-Zhong** [ethereum/go-ethereum#21905]
hi,good to everybody!
   I have my own public chain of proof of work algorithm. 
   I deploy an erc20 contract token to this public chain,which it named dyc token.

my problem is:
   I use the mill to mint token on my own public chain,and i want to mint the dyc token at the sametime. Is this feasible? If it can,how to do?

你好，各位！
   我有一条pow算法的公链
   我部署了一份erc20合约代币叫做dyc在我的公链上。

我的问题是：
   我使用矿机在我这条公链上挖代币，而且我又能同时挖dyc token，这可行吗？如果可以的话，应该怎么做？

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
