### ISSUE TITLE
eth.syncing.highestBlock is constant while eth.syncing.currentBlock grows

### ISSUE THREAD

**Issue by colourful-land** [ethereum/go-ethereum#21910]
#### System information

Geth version: `geth version`
1.9.24-stable
OS & Version: Windows/Linux/OSX
Ubuntu Server 20.04

#### Expected behaviour

Running a **full node**. `eth.syncing.highestBlock` reads a different number once a few munites (currently etherscan.io says the latest block is 11338882 so I expected `eth.syncing.highestBlock` to match that.

#### Actual behaviour
eth.syncing.highestBlock is constantly 11334236

#### Steps to reproduce the behaviour

Run the same command on console once per 10 mintues:
````
> eth.syncing.highestBlock
11334236
> eth.syncing.highestBlock
11334236
> eth.syncing.highestBlock
11334236
````
This bug isn't about slowness but as a side note:
> `eth.syncing.currentBlock` grows at the rate of 2 to 3 blocks per minute. It is already far behind, 11334236 is 62350 blocks behind the current latest block and my node is connected to [50 peers](https://github.com/ethereum/go-ethereum/files/5606255/peers.txt) so it shouldn't be syncing up just 2 to 3 blocks per minute.

**Comment by colourful-land** [comment]
8 hours later, I still have

````
> eth.syncing.highestBlock
11334236
````

In the meanwhile, currentBlock grew by 2183

**Comment by colourful-land** [comment]
After `eth.syncing.highestBlock` stagnated for a week, I restarted `geth` and now it learned a new value for  `eth.syncing.highestBlock` 11356583 and that becomes the new constant.

**Comment by colourful-land** [comment]
Here are some more debug information.

## Memory: 80% unused ##

````
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          20022        1655       13936           1        4430       18570
````

## System Load: high but not maxed out ##

Since the CPU has 4 cores, load average 3.54 indicates high but not full load.

````
$ uptime
 23:47:24 up 15 min,  2 users,  load average: 3.54, 3.20, 1.95
````

## Network load: using 1/2 of available bandwidth ##

Average 1.3MB/s download on this host (there are no other active services than geth). This is half of the typical youtube/steam download speed on the same network. Upload is around 300kBits/s

## CPU usage: 33% of one core (total 4 core) ##

Geth typically uses 33% ~ 34% of one CPU. (It doesn't look like multi-threadable)

**Comment by colourful-land** [comment]
Cross-linking this issue from https://ethereum-magicians.org/t/willing-to-pay-for-fixing-a-geth-node-with-sync-issue/4976 where I offered to pay to let some Ethereum node operator check this issue.

**Comment by colourful-land** [comment]
Given that all of the resources are underused: CPU, Disk IO, Network, Memory, and by the fact of a strange growth rate of eth.syncing.currentBlock one block per minute, is it possible geth mistaken this under synched situation as fully synced and only sync up at the rate new blocks are mined?

**Comment by AusIV** [comment]
Do you have disk iops numbers? Throughput isn't a huge concern for Geth, but read latency is. Geth nodes do a ton of small, sequential read operations, so if a disk seek is slow your node can't keep up even if your disks are capable of high throughput.

You might try running with the - -snapshot flag, as that can reduce sequential reads.

**Comment by holiman** [comment]
I know this ticket is now pretty old, sorry about not answering sooner. If this is still a problem, could you provide some logs from the node?

**Comment by colourful-land** [comment]
This problem disappeared with the replacement of a RAID card. So for those who come here by Google search, this problem seem to be happening when the HDD I/O is limited for some reason.

**Comment by alisscco** [comment]
Honestly trying to gather them.. been so focused on liquidity mining forgot
my miners ..
will get notes ready.
Thanks .
