### ISSUE TITLE
Failed to store pivot block number       err="leveldb/table: corruption on data-block (pos=384824320): checksum mismatch, want=0x0 got=0xf0423001 [file=592568.ldb]"

### ISSUE THREAD

**Issue by vijay055** [ethereum/go-ethereum#21916]
#### System information

Geth version: `v1.9.19`
OS & Version: Windows 10 ( 1 tb SSD , Intel core 17 )
Commit hash : (if `develop`)

#### Expected behaviour
waiting for all block headers to be downloaded and start mining

#### Actual behaviour
Failed to store pivot block number       err="leveldb/table: corruption on data-block (pos=384824320): checksum mismatch, want=0x0 got=0xf0423001 [file=592568.ldb]"

#### Steps to reproduce the behaviour
Geth connected to mainnet , downloaded all most all blocks just behind 100 (took more than 2 weeks)( nearly 400 GB data)

eth.syncing
  currentBlock: 11349254,
  highestBlock: 11349325,
  knownStates: 445589841,
  pulledStates: 445589568,
  startingBlock: 11349042

**Comment by ligi** [comment]
did you at some point have a unclean shutdown of geth? e.g. a reboot / crash / ..

**Comment by vijay055** [comment]
@ligi 
Yes , i did stop at one point when i moved files to external SSD ( moved around 250gb from internal SSD to external SSD) then started geth ( geth was put in .bat file, so stopped batch file and started again after moving files )
it was downloading more than 100 Gb of headers after that.

**Comment by ligi** [comment]
How did you stop geth?

**Comment by vijay055** [comment]
stopped the batch file..Ctrl+c

**Comment by derbrachialist** [comment]
I have the same problem, it corrupted 3 times on 2 different SSDs.

**Comment by karalabe** [comment]
@vijay055 You can't just remove a file from the database, if you delete part of the dataset you'll get bad blocks. You'll need to resync.


@derbrachialist What os? What error message? Any logs?

**Comment by derbrachialist** [comment]
Manjaro Gnome
same error message, did not save any logs. Got frustrated after only comments on github that I found were that the ssd must be broken. I'm running on a brand new nvme ssd, bought for the purpose of running a node and even tried my old 2.5 ssd. switched to [openethereum](https://github.com/openethereum/openethereum).

**Comment by vijay055** [comment]
@karalabe 
i removed and started the geth , it went on for while ( remember it did some compression on the db files i guess)
but I have given up at that point.

@derbrachialist I also bought a new 1 TB SSD and it failed. Now the issue is SSD with or geth. ?
or is that bcoz I used external SSD and if there is slight shaking in the USB connections it is corrupting files ??? just guessing..

**Comment by derbrachialist** [comment]
It corrupted both on my external usb and internal m.2 ssd.

**Comment by ppershing** [comment]
Another instance here. I believe I first saw checksum error. Now, after deleting all data and resyncing I see

```
CRIT [02-22|00:54:58.104] Failed to write block into disk          err="leveldb/table: Writer: keys are not in increasing order: \"\\xf5R;\\x8e\\xec\\xe0K\\x92ꙉ\\xab\\x8c\\xfaH\\x99\\f\\x03\\x9d\\\\\\xbaj\\xcf,\\xb5\\xf08\\x03m\\xfda\\xaa\\xda\\xc09\\xae~\\x86\\xb2\\x12\\x85\\x1cqY{\\xc1cJk\\xad\\x8a\\xd2\\xf5\\x04@}\\xc1\\x82\\xc5\\xd9*\\xb0\\xe9\\xf2\\xe4V\\xc9i=\\x1eg\\xbf~\", \"]\\xb7P\\x99\\xfd\\xa1p\\xc0\\xf50\\xc4\\xf12>\\x8dK\\xe4\\x84\\xc9ѐh\\x16\\xb1\\xa6\\x8e\\xc7\\xf8P\\xbe\\x11p\\xf8i\\xb6\\x9a3\\x98.\\x85\\x95G\\x97\\x19\\xf2\\xd2\\xeb\\x01\\x8eE\\xa7\\xae\\xc9\\xeb\\x83a\\x13\\xf8~Z\\x94\\\"\\x1e\\ue415\\x92\\x1a\\x9a\\xd1q\\x883\""
```

**Comment by jayboy-mabushi** [comment]
@derbrachialist  did you find a solution?

**Comment by derbrachialist** [comment]
It corrupted with go-ethereum and openethereum so i guess my new ssd must have been broken. I did not find a solution, I would recommend trying another ssd.

**Comment by holiman** [comment]
Stale, closing this
