### ISSUE TITLE
sendRawTransaction results in transaction hash, but cannot find transaction on the network

### ISSUE THREAD

**Issue by drsaluml** [ethereum/go-ethereum#21912]
I used sendRawTransaction to broadcast successfully but once the hash is received, the hash does not appear in etherscan.
Does anyone know how to fix it?
Im running the latest version of Geth.
Geth/v1.9.24-stable-cc05b050/linux-amd64/go1.15.5

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
