### ISSUE TITLE
Go-ethereum tracer information doesn't mark all internal transactions as failed

### ISSUE THREAD

**Issue by HaoyangLiu** [ethereum/go-ethereum#21924]
#### Expected behaviour

For a `delegateCall`, if it is reverted because the last subcall is reverted, then all its subcalls should be marked as failed. 

#### Actual behaviour
On a go-ethereum node, if a`delegateCall` contains multiply subcalls, and the last subcall is reverted, both the `delegateCall` and all other subcalls should be marked as failed. However, according to my test, only the `delegateCall` and the last subcall are marked as failed, other subcalls are marked as successful:

https://testnet.bscscan.com/tx/0x117156b040a2d05afe04488005953b3b1710f6bebdd6d7a8643e44006fdfec83#internal

![image](https://user-images.githubusercontent.com/2945006/100612355-d260f500-334d-11eb-8e14-3d86f388dda3.png)

`bscscan` is an explorer for Binance Smart Chain which is forked from go-ethereum v1.9.10.

In addition, [parity ethereum](https://github.com/openethereum/openethereum) doesn't have this issue. I have tried this issue on Ropsten testnet and Ropsten explorer marked all subcalls as failed. And Ropsten explorer connects to a parity implementation node.

https://ropsten.etherscan.io/tx/0x866ac443a27f4e62d5c085a6b2291bdd3bdf777da78980546fe1e868377c04b1#internal

![image](https://user-images.githubusercontent.com/2945006/100612378-dd1b8a00-334d-11eb-9f42-b76ffec33bc5.png)

##### Reproduce on ropsten
1. Open [ropsten contract write page](https://ropsten.etherscan.io/address/0x49332a17aa62979c04db5f9c3659bebc4ffc816b#writeContract)

2. Input 10 and click `write` buttion
![image](https://user-images.githubusercontent.com/2945006/100612596-35528c00-334e-11eb-9164-2aa6116e1973.png)

##### Reproduce on BSCScan
1. Open [bsc contract write page]
https://testnet.bscscan.com/address/0xeeb2be6b1f5da51aba57fe5f508282b10e39481d#writeContract

2. Input 10 and click `write` buttion
![image](https://user-images.githubusercontent.com/2945006/100612668-4ef3d380-334e-11eb-994a-95a585d6541c.png)

#### Backtrace

Dumped tracer information from a BSC(Binance Smart Chain) node.

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "type": "CALL",
    "from": "0x80bb68f2664015b18c0c9fd9ed289a08334e4122",
    "to": "0xeeb2be6b1f5da51aba57fe5f508282b10e39481d",
    "value": "0x0",
    "gas": "0x105aa",
    "gasUsed": "0x9dd9",
    "input": "0x3b5c9271000000000000000000000000000000000000000000000000000000000000000a",
    "output": "0x",
    "time": "8.67027ms",
    "calls": [
      {
        "type": "CALL",
        "from": "0xeeb2be6b1f5da51aba57fe5f508282b10e39481d",
        "to": "0xe91ec9e9e5754457cae0e1472383c3ec7a1c3326",
        "value": "0x0",
        "gas": "0xf7d1",
        "gasUsed": "0x927a",
        "input": "0x3b5c9271000000000000000000000000000000000000000000000000000000000000000a",
        "error": "execution reverted",
        "calls": [
          {
            "type": "DELEGATECALL",
            "from": "0xe91ec9e9e5754457cae0e1472383c3ec7a1c3326",
            "to": "0xde296803adea13566f22629d62e97aeddc05644c",
            "gas": "0xe98e",
            "gasUsed": "0x87b6",
            "input": "0x3b5c9271000000000000000000000000000000000000000000000000000000000000000a",
            "error": "execution reverted",
            "calls": [
              {
                "type": "CALL",
                "from": "0xe91ec9e9e5754457cae0e1472383c3ec7a1c3326",
                "to": "0x03baaf5977d6d76fd27600b655a9013e35584d7f",
                "value": "0x2386f26fc10000",
                "gas": "0xc261",
                "gasUsed": "0x58ae",
                "input": "0xd0e30db0",
                "output": "0x"
              },
              {
                "type": "CALL",
                "from": "0xe91ec9e9e5754457cae0e1472383c3ec7a1c3326",
                "to": "0xa433d90bd25458305ab7021ce70148a7ad6c42fb",
                "value": "0x0",
                "gas": "0x61bc",
                "gasUsed": "0x13f",
                "input": "0xc14731ca000000000000000000000000000000000000000000000000000000000000000a",
                "error": "execution reverted"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

**Comment by holiman** [comment]
I see your point. 
Basically: "If an outer scoped transaction reverts, then all actions within that scope are also side-effect free, so they should be retroactively marked as 'failed'"

However, I don't quite agree. Currently, geth shows whether the inner call, _by itself_ failed or did not fail. This is relevant information for someone who wants to figure out why something works (or doesn't). The fact that the side-effects are later reverted due to the outer-scope failure doesn't, IMO, make it "correct" to say that the inner call failed, when it de facto did not.

**Comment by holiman** [comment]
Answered, closing this
