### ISSUE TITLE
Logging in JSON format

### ISSUE THREAD

**Issue by willianpaixao** [ethereum/go-ethereum#21926]
# Rationale

There should be more options on logging format for Geth.
At the moment, the only option available is the verbosity level.
For example, logging parsing is a great tool for managing highly available nodes.
I am suggesting two flags, one that would change the formatted log to JSON and a second flag to specify the output log file, rather than dump onto `stdout`.

These two flags combined would allow a variety of tools to monitor the health of a Geth node.
# Implementation

The [`log/` folder](https://github.com/ethereum/go-ethereum/tree/master/log), containing the `log15` package already parses the log messages in JSON format, but it converts to syslog before dumping. The first mentioned flag would skip the conversation.

Also, it's (to my knowledge) trivial to create a flag that receives one argument (file) and writes the log into it rather than `stdout`.

**Comment by rjl493456442** [comment]
Regarding the file output, you can easily rediect the output. Actually in a very old version Geth, it's supported to dump the log to files. While we think it's totally unecessary.

**Comment by mjpowersjr** [comment]
Just a few weeks ago I started to look at patching a local build of geth to support this. This seems like a great feature. :-)

**Comment by willianpaixao** [comment]
Hi @rjl493456442, I currently use redirectors to save the log into a file.
Although the vast majority of the services out there have this feature (specify output log file).

But the JSON format logging could it's a good candidate for a feature.

**Comment by MysticRyuujin** [comment]
Not to mention that support for log redirection stuff is terrible in Windows, and when used with something like systemd and journalctl - breaking out stderr and stdout is harder to do, and if you want to syslog stuff it's also hard to get levels correct.

There's multiple instances of people patching geth themselves to support log files because of the assumption that redirecting output is good enough :slightly_frowning_face:

**Comment by holiman** [comment]
This is what `clef` uses (`auditlog.go`): 
```

func NewAuditLogger(path string, api ExternalAPI) (*AuditLogger, error) {
	l := log.New("api", "signer")
	handler, err := log.FileHandler(path, log.LogfmtFormat())
	if err != nil {
		return nil, err
	}
	l.SetHandler(handler)
	l.Info("Configured", "audit log", path)
	return &AuditLogger{l, api}, nil
}
```
