### ISSUE TITLE
How starting a graphql

### ISSUE THREAD

**Issue by PHPJourney** [ethereum/go-ethereum#21931]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

This geth version code

> Geth/v1.9.22-unstable-a99ac533-20200914/linux-amd64/go1.14.3

I'm use --graphql dumpconfig to toml , and start it.

```
./geth --datadir /ssddata/ethereum --cache 4096 --maxpeers 50 --http --graphql --http.addr "127.0.0.1" --http.port 8545 --http.vhosts "*.eth.api.lc"  --http.api “admin,net,txpool,debug,ethash,eth,personal,rpc,web3”  --ws --ws.port 8546 --ws.origins "127.0.0.1" --graphql.corsdomain "*" --graphql.vhosts "*" --shh --allow-insecure-unlock --syncmode full dumpconfig > ./geth.toml
```
but can't use graphql query. I don't know whether this graphql was started successfully, because there is no separate port number that can be used for tracking. I did a query test on postman

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
