### ISSUE TITLE
GoQuorum with Istanbul BFT Consensus starts the tessera

### ISSUE THREAD

**Issue by chriswsq** [ethereum/go-ethereum#21933]
## Using BFT Consensus to enable Tessera, starting times wrong

**Start the command：**

cd node0
 PRIVATE_CONFIG=/bsn/quorum/fromscratchistanbul/istanbul-tools/new-node-1t/tm.ipc  geth --datadir node0 --nodiscover --verbosity 5 --networkid 31337 --raft --raftport 50000 --rpc --rpcaddr 0.0.0.0 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints --port 21000

**Error message：**

DEBUG[12-01|16:53:20.061] Reinjecting stale transactions           count=0
INFO [12-01|16:53:20.061] Loaded local transaction journal         transactions=0 dropped=0
INFO [12-01|16:53:20.061] Regenerated local transaction journal    transactions=0 accounts=0
INFO [12-01|16:53:20.071] Allocated fast sync bloom                size=512.00MiB
WARN [12-01|16:53:20.072] Found deprecated node list file node0/static-nodes.json, please use the TOML config file instead. 
Fatal: raftport querystring parameter not specified in static-node enode ID: enode://9ecd977f68669b06f8e4bfdb81ba80894167781689f64a854a08ec27612cdc4844abb7230e2524b4475319ff59242e7841b9875973337b043afcf204c82f287a@0.0.0.0:30001?discport=0. please check your static-nodes.json file.

## Tessera is not enabled, and the service works fine

**Start the command：**

cd node0
PRIVATE_CONFIG=ignore nohup geth --datadir data --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul --emitcheckpoints --port 30300 2>>node.log &

**How do I adjust the static-nodes.json file after enabling tessera service？What is the boot command?**

**Comment by karalabe** [comment]
You'll need to take this up with the Quorum team https://github.com/ConsenSys/quorum
