### ISSUE TITLE
Long Term Support Release or Stable Branch

### ISSUE THREAD

**Issue by AusIV** [ethereum/go-ethereum#21937]
# Rationale

Most major software systems used within enterprises have a versioning process whereby a major version defines a specific set of functionality that the version of the software provides, while patch versions introduce only changes to make the software more stable (criticial bug fixes and security fixes). You would be hard pressed to find a software project backing billions of dollars of value that only makes critical bug fixes in the same stream of releases as new features and breaking changes. Some examples of different project’s release policies:

* [Apache Webserver](https://httpd.apache.org/dev/release.html )
* [Linux Kernel](https://www.kernel.org/category/releases.html)
* [Node JS](https://nodesource.com/blog/understanding-how-node-js-release-lines-work/)
* [Golang](https://golang.org/doc/devel/release.html#policy)
* [Postgres](https://www.postgresql.org/support/versioning/)
* [Redis](https://redis.io/topics/releases)
* [SemVer](https://semver.org/) - a versioning protocol used by many open source projects

All of these projects have some form of active development branch, along with a separate option for enterprise users to get only critical security updates.

Most enterprise teams work on two week sprint schedules. When Geth is on an approximately bi-weekly release schedule, and those releases may include a combination of new features, breaking changes, and critical security updates, it becomes necessary for teams to allocate a portion of each and every sprint just in case they need to make software or infrastructure changes to account for changes introduced in Geth. Some examples of breaking changes include:

* Geth 1.9.12 changed the default account for eth_call invocations. Applications depending on the old default had to make software changes.
* Geth 1.9.14 changed error messages to include revert reasons. While this is very useful, applications built to react to old error messages had to make software changes.
* Geth 1.9.19 merged GraphQL onto the same port as RPC. This made it impossible to run RPC and GraphQL on separate interfaces (which was previously possible) and introduced new security concerns for projects that needed to run both RPC and GraphQL, but wished to restrict access to one or the other.

In the midst of these breaking changes were a mix of other new features, optimizations, and critical security updates. Some critical security updates were mischaracterized by the Geth team as optimizations, so even a team making an effort to keep up with critical security updates would be unaware of them.

We also believe this would help a little bit with the client diversity concerns noted [here](https://blog.ethereum.org/2020/11/12/geth_security_release/). While a stable release of Geth is likely to offer less resilience than a wholly separate implementation, having some clients on releases with new features and optimizations while other clients remain on stable releases based on earlier implementations will add a degree of client diversity.

# Implementation

The Rivet team would like to support some kind of stable release or Long Term Support branch, which would select a specific set of features and apply only critical bug fixes and security patches to that branch. This would allow ourselves and other teams to quickly apply security updates, and deal with any new features or breaking changes on a more predictable, enterprise friendly schedule. We’re happy to work with the Geth team on the specific structure of this branch - defining a policy for what is backported into this branch and what is not, how long a stable branch is supported and what a transition period looks like, etc. We would ask that the Geth team highlight critical fixes that need to be backported, and we will take responsibility for backporting those changes into a stable branch. 

Our goal is to minimize the friction in the Geth team’s development process, while giving enterprise users the ability to apply critical updates quickly with minimal changes to other systems, and put major upgrades onto a predictable schedule.

Our team has supported a fork of Geth since the spring of 2018, and have made several contributions upstream to Geth. This experience makes us immediately qualified to handle backporting fixes throughout the Geth codebase.

**Comment by ligi** [comment]
related #21837

**Comment by willianpaixao** [comment]
I think this possibly would have mitigated Infura's latest outage. [[1]](https://blog.infura.io/infura-mainnet-outage-post-mortem-2020-11-11/)

**Comment by ligi** [comment]
Would you be able to have a call about this?

**Comment by AusIV** [comment]
I'd love to. austin.roberts@openrelay.xyz

**Comment by cmeisl** [comment]
@ligi any update on this issue from call with @AusIV?

**Comment by ligi** [comment]
@AusIV @cmeisl oh sorry - this one fell through the cracks - dropping an email soon - sorry for the delay

**Comment by ligi** [comment]
We had another conversation in the team about this now with everyone on the (virtual) table. And there was rough consensus to not go forward with this for mainly 2 reasons:
 * The long term branch would highlight security fixes
 * It will make it harder to get new features to a critical mass of nodes out (Snap Sync, ..)

**Comment by ligi** [comment]
Seems this one needs some more context:
 * There are stable releases, generally pushed every two weeks unless deemed otherwise.
 *  If a release is risky (e.g. large feature release, there is a bump bump from 1.9 to 1.10 and warn high risk users to upgrade later).
 * Geth v1.9.17 Post Mortem - https://gist.github.com/karalabe/e1891c8a99fdc16c4e60d9713c35401f
 * Geth recently committed to a slightly more open vulnerability disclosure format where we highlight that a previous release contained security fixes and a few weeks later - when people had time to upgrade - reveal the details: https://twitter.com/go_ethereum/status/1337330720277213184
