### ISSUE TITLE
Latest develop sets default gas price for tx send via rpc to 10000000000000 Wei

### ISSUE THREAD

**Issue by ppratscher** [ethereum/go-ethereum#2194]
If no gas price is specified in the send Transaction call a default gas price of 10000000000000 Wei is applied.

See line https://github.com/ethereum/go-ethereum/blob/develop/eth/api.go#L1025

This makes tx extremely expensive. Ideally sendTransaction should retrieve the current gas price from the gpo.

**Comment by obscuren** [comment]
It is correct that the default gas price should be retrieved from the GPO, however, that doesn't necessarily make transactions by default any cheaper.

**Comment by ppratscher** [comment]
no, but currently it makes them by default extremely expensive with 0.21 Ether/tx

**Comment by obscuren** [comment]
The GPO won't fix that by default. The GPO actually has the ability to make them much more expensive.

**Comment by karalabe** [comment]
This should be fixed now. Please check again with latest develop.

**Comment by karalabe** [comment]
Assuming fixed. Please reopen if not :)
