### ISSUE TITLE
Add on the documentation the mandatory action to init the genesis.json on a private network for a member node peer allowing to start correctly the chain synchronisation. 

### ISSUE THREAD

**Issue by cozcan** [ethereum/go-ethereum#21945]
On the official wiki documentation and on many forums the information to start correctly synchronizing on a private Ethereum Blockchain network is not mentionned. Since the Geth version 19.1.15 is mandatory to init the genesis.json file before starting to be synchronized and update the state of the Private Blockchain. 

Could you then for better clarification add on the section such important information which is not mentioned.  Only the creation of the genesis.json is in fact described. 

https://github.com/ethereum/go-ethereum/wiki/Private-network or it could be describe somewhere on this section.

Thank you for your feedback.

**Comment by MariusVanDerWijden** [comment]
rel: https://github.com/ethereum/go-ethereum/issues/20398

**Comment by MariusVanDerWijden** [comment]
Well in the new documentation https://geth.ethereum.org/docs/interface/private-network it's pretty clearly described that you need to run `geth init --datadir data genesis.json` I think that is enough, but if you want to add something, we can add it of course!

**Comment by fjl** [comment]
The wiki is not updated anymore. Closing this because the geth.ethereum.org docs contain this information. We could make the link to geth.ethereum.org even more prominent, or just delete the wiki.
