### ISSUE TITLE
Rinkeby testnet halted?

### ISSUE THREAD

**Issue by jun0tpyrc** [ethereum/go-ethereum#21942]
seem so per our nodes and the public explorers 

https://rinkeby.etherscan.io/
https://explorer.anyblock.tools/ethereum/ethereum/rinkeby/

**Comment by holiman** [comment]
Yes, one signer got restarted this morning and failed to come up gracefully, it's catching up now. Unfortunately, some other sealers were also down, apparently. 

```
{
  inturnPercent: 14.0625,
  numBlocks: 64,
  sealerActivity: {
    0x42eb768f2244c8811c63729a21a3569731535f06: 16,
    0x6635f83421bf059cd8111f180f0727128685bae4: 16,
    0x6dc0c0be4c8b2dfe750156dc7d59faabfb5b923d: 0,
    0x7ffc57839b00206d1ad20c69a1981b489f772031: 16,
    0xb279182d99e65703f0076e4812653aab85fca0f0: 0,
    0xd6ae8250b8348c94847280928c79fb3b63ca453e: 16,
    0xf10326c1c6884b094e03d616cc8c7b920e3f73e0: 0
  }
}

```
So three of them were already not active and `0x7ffC57839B00206D1ad20c69A1981b489f772031` is the one catching up.

**Comment by jun0tpyrc** [comment]
looks just mostly resumed , thanks

7648431 | 7 mins ago (Dec-02-2020 08:46:09 AM +UTC)
