### ISSUE TITLE
Synchronizing a block takes a few minutes.Slow sync speed.

### ISSUE THREAD

**Issue by CharlieWangA** [ethereum/go-ethereum#21947]
I used AWS EC2 c5d.2xlarge.I already have a node that synchronizes to complete,But I don't have enough storage space(used 98%).So I restarted an instance with a mirror(AMI),It took about 10 hours to do this.But when I started geth on a new instance, the synchronization was very slow.
These is logs:

<img width="1374" alt="截屏2020-12-03 下午3 55 34" src="https://user-images.githubusercontent.com/49639433/100980347-10ddf600-3580-11eb-8ad8-23a4a82dacea.png">

In the meantime, the previous instance is normal:
<img width="1306" alt="截屏2020-12-03 下午3 57 08" src="https://user-images.githubusercontent.com/49639433/100980467-3a971d00-3580-11eb-812f-1289d42e56f8.png">

**Comment by CharlieWangA** [comment]
The configuration is the same except for storage of 1000G and 1500G

**Comment by CharlieWangA** [comment]
Please tell me other methods besides resynchronizing if you can.Thank you.

**Comment by MariusVanDerWijden** [comment]
Does the new node also have an ssd or did you switch to an hdd?

**Comment by CharlieWangA** [comment]
Both are separate SSD

**Comment by holiman** [comment]
So the reasonable explanation is that this new setup does not deliver quick enough IO. 
To verify this, you could do some read-write tests against the drives, and compare the results. You could also check `iostats` and see what it reports. 
Now, to dive a bit deeper as to _why_ it doesn't, one would need more information, e..g. are you using EBS-drives? What filesystems are used?

**Comment by CharlieWangA** [comment]
I tried to resynchronize with a Datadir, and everything worked fine.So can rule out the above problem.

**Comment by holiman** [comment]
Not sure I understand... So problem solved then?

**Comment by CharlieWangA** [comment]
Using another Datadir problem was resolved, but I needed to resynchronize.
Can eliminate the network disk IO problem.

**Comment by CharlieWangA** [comment]
Sorry, my English is poor. If I can't find the specific problem, I have to resynchronize.

**Comment by MariusVanDerWijden** [comment]
I'll close this issue for now, feel free to reopen if it still persists
