### ISSUE TITLE
Clique period=0: all transactions go straight to pending, and no transactions get sealed

### ISSUE THREAD

**Issue by nazneenk** [ethereum/go-ethereum#21951]
[Logs_period_0.txt](https://github.com/ethereum/go-ethereum/files/5642435/Logs_period_0.txt)
[Logs_period_15.txt](https://github.com/ethereum/go-ethereum/files/5642437/Logs_period_15.txt)

#### System information

Geth version: v1.9.24-stable-cc05b050/linux-amd64/go1.15.5
OS & Version: Ubuntu 16.04
Commit hash : (if `develop`)

#### Expected behaviour
Expecting blocks to be sealed as transactions get submitted with period=0.

#### Actual behaviour
No blocks get sealed with period=0
With all else setup equally, but setting period=1, period=5, period=15, blocks get sealed at the expected frequency, and all submitted transactions get sealed.
Looking with txpool.content, you can see all the transactions go straight to the pending section.
Tried a new instance, with a transaction with nonce=1, and transaction goes to queued txpool, as expected

#### Steps to reproduce the behaviour
Set up 1 node and 1 sealer (or 3 nodes and 3 sealers, there is no difference in behavior)
Use peppeth to generate genesis file with period=0 
Start node with
/usr/bin/geth --nousb --allow-insecure-unlock --identity "xyz" --verbosity "5" --rpc --rpcaddr "0.0.0.0" --rpcport "8545" --rpccorsdomain "*" --rpcvhosts "*" --rpcapi "miner,eth,net,personal,web3" --port "30303" --nodiscover --gcmode "archive" --miner.gasprice "1" --miner.gastarget "8000000000" --miner.gaslimit "8000000000" --networkid "850" --ipcpath "/home/eth_user/gethipc/geth.ipc"  --unlock "xyz" --password "/xyz" --mine --syncmode "full" 

Submit a transaction using nodejs and web3:
> web3.eth.getAccounts().then(function(acc){accounts=acc;}).catch(e => console.log(e));
> web3.eth.getBalance(accounts[0]).then(console.log).catch(e => console.log(e));
> web3.eth.getBalance(accounts[1]).then(console.log).catch(e => console.log(e));
904625697166532776746648320380374280103671755200316906558262375061821325312
> web3.eth.personal.unlockAccount(accounts[1],"xyz",3600).then(res => console.log(res)).catch(e => console.log(e))
true
> web3.eth.getTransactionCount(accounts[1]).then(console.log)
0
> web3.eth.sendTransaction({ from: accounts[1], to: accounts[0], nonce: 0, gasPrice: 2100000, gas: 2100000, value: 10000000000000000000 }).then(res => console.log(res)).catch(e => console.log(e))

Check geth console:
> txpool.content
{
  pending: {
    0x2D444677e802c1cBEFA3d1d8FeF4994d325bd332: {
      0: {
        blockHash: null,
        blockNumber: null,
        from: "0x2d444677e802c1cbefa3d1d8fef4994d325bd332",
        gas: "0x200b20",
        gasPrice: "0x200b20",
        hash: "0xd2bce44cffcc82101578b0e19718079da66032e752aee74c7dc8631c27e64341",
        input: "0x",
        nonce: "0x0",
        r: "0x1334934b877defb3502a9299925ef425ab82c1b45a747df1d1c31079d9938154",
        s: "0x30ffec938200144cbb11b7e472fb4fd0e0d8edd48abe1ab618f3746c05a5702b",
        to: "0x93284d9b0403b6d56306449234e46a80d0e9eb87",
        transactionIndex: null,
        v: "0x6b3",
        value: "0x8ac7230489e80000"
      }
    }
  },
  queued: {}
}

For comparison, set up another PoA node with everything the same except create genesis file with period=15, and logs show sealing starts and continues every 15 sec, transactions get sealed, and no transaction shows up in txpool.

#### Backtrace

Please see the attached logs for both instances for comparison (period=0 and period=15)

````
[backtrace]
````

**Comment by nazneenk** [comment]
Removed logs from the description and attached them instead, so the bug is more readable.

**Comment by nazneenk** [comment]
Tried on v1.9.25-stable-e7872729/linux-amd64/go1.15.6, but problem still persists.  

Any help on this issue would be greatly appreciated.

**Comment by holiman** [comment]
I don't quite understand -- you are using one sealer and one non-sealer. Are you submitting txs to the non-sealer, and checking the `pending` on the non-sealer? 
If so, have you checked if the two nodes are connected ? (`admin.peers`) ? And what about the txpool of the sealer?

**Comment by nazneenk** [comment]
When I use one node only, it's the sealer node.  When I have three nodes, they are all sealer nodes, and they are all connected.  I don't have any non-sealer nodes.  I check the txpool of the sealer nodes.

**Comment by holiman** [comment]
So, if it can be reproed with only one (sealer) node, then that's ideal.... Can it?

**Comment by nazneenk** [comment]
yes, it can be reproduced with one (sealer) node

**Comment by holiman** [comment]
I just tested this, one PoA sealer with a period of `0`, then attach to that node, submit transactions via `personal.sendTransaction`. They get included in newly mined blocks. Comparing with your logs, this happens when I submit one: 
```
TRACE[01-12|08:01:19.130] Pooled new future transaction            hash="37a901…f729d8" from=0x9cf55e4FF2Bc81ef2e7e3DBc42f3D592FFd2AE43 to=0x9cf55e4FF2Bc81ef2e7e3DBc42f3D592FFd2AE43
TRACE[01-12|08:01:19.130] Removed old queued transactions          count=0
TRACE[01-12|08:01:19.130] Removed unpayable queued transactions    count=0
TRACE[01-12|08:01:19.130] Promoted queued transactions             count=1
TRACE[01-12|08:01:19.130] Broadcast transaction                    hash="37a901…f729d8" recipients=0
```
So, it first get's pooled as `future`, then promoted from `queue` to `pending`. In your logs: 
 
```
TRACE[12-03|10:33:12.661] Pooled new future transaction hash="ab9dae…40b79c" from=0xC370dc4F05b03E0986729e2bdb329B715995A1fc to=0x6703F41aF7f520728F47649aFC23b312889DD38a
TRACE[12-03|10:33:12.661] Removed old queued transactions count=0
TRACE[12-03|10:33:12.661] Removed unpayable queued transactions count=0
TRACE[12-03|10:33:12.661] Promoted queued transactions count=0
INFO [12-03|10:33:12.661] Submitted transaction fullhash=0xab9daeb719e81c67a1dc3adcef6a36f4d59cfe403cfdf43e471f85b2ed40b79c recipient=0x6703F41aF7f520728F47649aFC23b312889DD38a
```
I.e: it does not get promoted (`Promoted queued transactions count=0`). 

Could you try to repro this without using nodejs and web3? Would be good to eliminate other potential sources of errors.

**Comment by nazneenk** [comment]
I reproduced it without using nodejs and web3, and used the personal namespace.  Still not getting the transaction sealed.

Here is the console session:

> > 
> > eth.accounts
> ["0xe42de93ae8c1aae237f2c9fb40043c1d378986bc", "0x67f4469a4e302536d7495779b7378629e660e051"]
> > personal.unlockAccount(eth.accounts[1])
> true
> > personal.sendTransaction({from: eth.accounts[1], to: eth.coinbase, value: web3.toWei(30, "ether")}, "12345")
> "0x15abf37364658f7a9a830a483d09a9beea3a9fe70fa9da17925984d666f4048a"
> > eth.blockNumber
> 0
> > txpool.content
> {
>   pending: {
>     0x67F4469A4E302536D7495779B7378629E660E051: {
>       0: {
>         blockHash: null,
>         blockNumber: null,
>         from: "0x67f4469a4e302536d7495779b7378629e660e051",
>         gas: "0x5208",
>         gasPrice: "0x1",
>         hash: "0x15abf37364658f7a9a830a483d09a9beea3a9fe70fa9da17925984d666f4048a",
>         input: "0x",
>         nonce: "0x0",
>         r: "0xcc4ee6b8e5ec4e6f467eeac41ce6c801fc8af24eefd861771d3fa5b5b49a8a18",
>         s: "0x659218bc3cc1a4bd80edd5b33fb9c29302730993b37f192f11d38287132c3a01",
>         to: "0xe42de93ae8c1aae237f2c9fb40043c1d378986bc",
>         transactionIndex: null,
>         v: "0x704",
>         value: "0x1a055690d9db80000"
>       }
>     }
>   },
>   queued: {}
> }
> 

Here is the log:

> DEBUG[01-14|20:38:52.363] Served eth_accounts                      reqid=15 t="45.342µs"
DEBUG[01-14|20:38:52.364] Served eth_coinbase                      reqid=16 t="22.907µs"
DEBUG[01-14|20:38:52.365] Executing EVM call finished              runtime="115.261µs"
DEBUG[01-14|20:38:52.365] Executing EVM call finished              runtime="108.943µs"
DEBUG[01-14|20:38:52.366] Executing EVM call finished              runtime="82.508µs"
DEBUG[01-14|20:38:52.366] Executing EVM call finished              runtime="71.073µs"
DEBUG[01-14|20:38:52.366] Executing EVM call finished              runtime="87.372µs"
DEBUG[01-14|20:38:52.366] Executing EVM call finished              runtime="80.992µs"
DEBUG[01-14|20:38:52.366] Executing EVM call finished              runtime="71.033µs"
DEBUG[01-14|20:38:52.366] Executing EVM call finished              runtime="75.43µs"
DEBUG[01-14|20:38:52.366] Executing EVM call finished              runtime="69.861µs"
DEBUG[01-14|20:38:52.366] Executing EVM call finished              runtime="73.435µs"
DEBUG[01-14|20:38:52.366] Executing EVM call finished              runtime="76.183µs"
DEBUG[01-14|20:38:52.366] Executing EVM call finished              runtime="83.414µs"
DEBUG[01-14|20:38:52.366] Executing EVM call finished              runtime="66.11µs"
DEBUG[01-14|20:38:52.367] Executing EVM call finished              runtime="68.688µs"
DEBUG[01-14|20:38:52.367] Executing EVM call finished              runtime="61.096µs"
DEBUG[01-14|20:38:52.367] Executing EVM call finished              runtime="66.251µs"
DEBUG[01-14|20:38:52.367] Executing EVM call finished              runtime="72.73µs"
DEBUG[01-14|20:38:52.367] Executing EVM call finished              runtime="104.228µs"
DEBUG[01-14|20:38:52.367] Executing EVM call finished              runtime="71.004µs"
DEBUG[01-14|20:38:52.367] Executing EVM call finished              runtime="40.098µs"
DEBUG[01-14|20:38:52.367] Executing EVM call finished              runtime="52.018µs"
DEBUG[01-14|20:38:52.367] Executing EVM call finished              runtime="49.448µs"
TRACE[01-14|20:38:52.367] Estimate gas usage automatically         gas=0x5208
INFO [01-14|20:38:53.138] Setting new local account                address=0x67F4469A4E302536D7495779B7378629E660E051
TRACE[01-14|20:38:53.138] Pooled new future transaction            hash="15abf3…f4048a" from=0x67F4469A4E302536D7495779B7378629E660E051 to=0xe42DE93AE8c1AaE237f2c9Fb40043C1d378986BC
TRACE[01-14|20:38:53.138] Removed old queued transactions          count=0
TRACE[01-14|20:38:53.138] Removed unpayable queued transactions    count=0
TRACE[01-14|20:38:53.138] Promoted queued transactions             count=1
TRACE[01-14|20:38:53.138] Ignoring reply protected transaction     hash="15abf3…f4048a" eip155=3
INFO [01-14|20:38:53.138] Commit new mining work                   number=1 sealhash="3a7e5e…f7ed75" uncles=0 txs=0 gas=0      fees=0 elapsed="126.999µs"
TRACE[01-14|20:38:53.138] Broadcast transaction                    hash="15abf3…f4048a" recipients=0
INFO [01-14|20:38:53.138] Submitted transaction                    fullhash=0x15abf37364658f7a9a830a483d09a9beea3a9fe70fa9da17925984d666f4048a recipient=0xe42DE93AE8c1AaE237f2c9Fb40043C1d378986BC
DEBUG[01-14|20:38:53.138] Served personal_sendTransaction          reqid=17 t=773.247421ms
INFO [01-14|20:38:53.138] Sealing paused, waiting for transactions 
DEBUG[01-14|20:38:53.401] Transaction pool status report           executable=1 queued=0 stales=0
DEBUG[01-14|20:38:53.405] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:39:13.405] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:39:21.202] Served eth_blockNumber                   reqid=18 t="40.426µs"
DEBUG[01-14|20:39:33.402] Current full block not old enough        number=0 hash="6c6c9f…503952" delay=90000
DEBUG[01-14|20:39:33.405] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:39:42.561] Served eth_coinbase                      reqid=19 t="39.409µs"
DEBUG[01-14|20:39:42.562] Served eth_getBalance                    reqid=20 t="120.721µs"
DEBUG[01-14|20:39:53.406] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:40:13.406] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:40:24.945] Served txpool_content                    reqid=21 t="168.983µs"
DEBUG[01-14|20:40:33.402] Current full block not old enough        number=0 hash="6c6c9f…503952" delay=90000
DEBUG[01-14|20:40:33.406] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:40:53.406] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:41:13.406] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:41:33.403] Current full block not old enough        number=0 hash="6c6c9f…503952" delay=90000
DEBUG[01-14|20:41:33.406] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:41:53.406] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:42:13.406] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:42:33.403] Current full block not old enough        number=0 hash="6c6c9f…503952" delay=90000
DEBUG[01-14|20:42:33.407] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:42:53.407] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:43:13.407] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:43:33.403] Current full block not old enough        number=0 hash="6c6c9f…503952" delay=90000
DEBUG[01-14|20:43:33.407] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:43:53.407] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:44:13.407] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:44:33.403] Current full block not old enough        number=0 hash="6c6c9f…503952" delay=90000
DEBUG[01-14|20:44:33.407] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:44:53.407] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:45:13.408] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:45:33.403] Current full block not old enough        number=0 hash="6c6c9f…503952" delay=90000
DEBUG[01-14|20:45:33.408] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:45:53.408] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-14|20:46:05.034] Served eth_blockNumber                   reqid=22 t="40.473µs"
DEBUG[01-14|20:46:13.408] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s

**Comment by holiman** [comment]
This means the tx cannot be included in a block on your chain, due to replay protection:> TRACE[01-14|20:38:53.138] Ignoring reply protected transaction hash="15abf3…f4048a" eip155=3

**Comment by holiman** [comment]
Looks pretty odd, really

**Comment by nazneenk** [comment]
Could this be the way I setup and start the node?

**Comment by nazneenk** [comment]
Tried the new 1.10.1 version.  With the same genesis file I was using before, the problem is still showing up the same way.

I tried using chainId: 1337 in the genesis file, but this didn't help.

I was getting this error when trying to send the first transaction:
> eth.sendTransaction({from: eth.accounts[1], to: eth.coinbase, value: web3.toWei(30, "ether")})
Error: invalid transaction v, r, s values
	at web3.js:6347:37(47)
	at web3.js:5081:62(37)
	at <eval>:1:20(19)

> eth.blockNumber
0

I noticed this line in the logs:
_INFO [03-10|03:04:01.359] Initialised chain configuration          config="{ChainID: 1337 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: 5 Petersburg: <nil> Istanbul: <nil>, Muir Glacier: <nil>, Berlin: <nil>, YOLO v3: <nil>, Engine: clique}"_

And saw this specification for EIP155
_If block.number >= FORK_BLKNUM and CHAIN_ID is available, then when computing the hash of a transaction for the purposes of signing, instead of hashing only six rlp encoded elements (nonce, gasprice, startgas, to, value, data), you SHOULD hash nine rlp encoded elements (nonce, gasprice, startgas, to, value, data, chainid, 0, 0). If you do, then the v of the signature MUST be set to {0,1} + CHAIN_ID * 2 + 35 where {0,1} is the parity of the y value of the curve point for which r is the x-value in the secp256k1 signing process. If you choose to only hash 6 values, then v continues to be set to {0,1} + 27 as previously._

It seemed like the block number for the EIP155 might be making the v,r and s values of the transaction invalid.  So, I thought I would change the block numbers for all the various forks in the genesis file equal to 0.
```
    "config": {
      "chainId": 1337,
      "homesteadBlock": 0,
      "eip150Block": 0,
      "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "eip155Block": 0,
      "eip158Block": 0,
      "byzantiumBlock": 0,
      "constantinopleBlock": 0,
      "clique": {
        "period": 0,
        "epoch": 30000
      }

```

This seems to have solved the problem for me.  Now I am able to get sealing happening normally with period=0.   

I can see why with period != 0, there was no issue with sealing, as the sealing was forced to happen periodically.   Perhaps with period=0, the specification for EIP155 came into play.

I have tested this with 1 node.

**Comment by tungpham2020** [comment]
Why not set period = 0 in geth/clique (PoA) always?
