### ISSUE TITLE
Running Mist Wallet and Geth together

### ISSUE THREAD

**Issue by azulmarino** [ethereum/go-ethereum#2196]
Hi,

To me it makes no sense to run Mist and Geth together as they both run a full mode. Also if I have started to run the wallet if I try to run Geth I get:
geth --fast I0210 14:25:58.932718 10870 database.go:71] Alloted 16MB cache to /Users/id/Library/Ethereum/chaindata Fatal: blockchain db err: resource temporarily unavailable (check if another instance of geth is already running with the same data directory '/Users/id/Library/Ethereum') 

However  if I run Geth , I can then run Mist and don't get such an error , Mist seems to be aware a node is running and syncs as expected.

**Comment by obscuren** [comment]
Once the LES protocol is out we expect to run Mist with the light client enabled, but until then, hang on!

As for the other issue, when you run geth **after** Mist is running it will tell you that a node is already running (and there's no reason to run another one). However if, for some reason, you'd like to run a second instance you'll have to specify a different `datadir` and `port` (e.g. `geth --datadir /tmp/datadir1 --port 30304`).

When you run mist **after** running `geth` mist will auto connect to the already running node.

**Comment by azulmarino** [comment]
Thanks , when is the LES protocol due ?
