### ISSUE TITLE
Discussion: Github Discussions

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#21979]
Github discussions is available now - IMHO it could lead to a cleaner issue tracker. Let's discuss if we want to enable this feature.

**Comment by rjl493456442** [comment]
Probably we can discuss it on the issue triage. And you can show us how to use the discussion feature!

**Comment by MariusVanDerWijden** [comment]
Example can be found here: https://github.com/githubevents/universe2020/discussions

**Comment by holiman** [comment]
Oh wow. Yeah I'm :+1:

**Comment by ligi** [comment]
Let's check back in a year if this github discussions feature is still alive and kicking - and reconsider then.

upsides:
 * we can easily create issues from questions
 * better overview and feedback through upvotes
  
downsides: 
 * *MIGHT* make more work
 * if we start it - it is hard to close it
 * it can become chaos

**Comment by DGKSK8LIFE** [comment]
I personally think that if we do implement github discussions, we need to have a system in place to mitigate bots and spam for sure.

**Comment by holiman** [comment]
We've discussed github discussions, and decided not to do this. Might re-evaluate later
