### ISSUE TITLE
idem same trouble and huge transaction "fee" 0.21 eth 

### ISSUE THREAD

**Issue by dths** [ethereum/go-ethereum#2197]
Same trouble
  code: -32000,
  message: "Insufficient funds for gas * price + value"

For a successfull transaction (default)
Gas Price: 0.00001 Ether
Gas Used: 21,000
Tx Price: 0.21 Ether

Geth
Version: 1.4.0-unstable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: linux

**Comment by karalabe** [comment]
It's a bug cause by the RPC refactoring. It's fixed by https://github.com/ethereum/go-ethereum/pull/2195, and should be merged soon (i.e. today, tomorrow latest).

**Comment by karalabe** [comment]
This should be fixed now. Please check again with latest develop.

**Comment by dths** [comment]
Thanks you for your help, will check asap.

**Comment by karalabe** [comment]
Assuming fixed. Please reopen if not :)
