### ISSUE TITLE
what is <YOUR_ETH1_NODE_ENDPOINT>of geth?

### ISSUE THREAD

**Issue by navy665180** [ethereum/go-ethereum#21975]
eth1.0:i use geth.and eth2.0,i use prysm.  in the geth terminal,the newest block is aready reach.
then a start ro build eth2.0 by prysm.the step2:  ./prysm.sh beacon-chain --http-web3provider=http://localhost:8545

run:the report an error: ERROR powchain: Could not connect to powchain endpoint error=eth1 node has not finished syncing yet

i don't know why?
![snapshot1 20201208](https://user-images.githubusercontent.com/75147624/101486383-850d0500-3997-11eb-9c95-b03932de156e.png)

**Comment by ligi** [comment]
I think you just need to wait to let it finsh sync

**Comment by navy665180** [comment]
@ligi thanks!,
