### ISSUE TITLE
"--syncmode light" never find out peer and cannot start sync

### ISSUE THREAD

**Issue by freeyssu** [ethereum/go-ethereum#21972]
Previously, I used light mode usually but nowadays geth cannot find out node to sync light mode data.
I tried to several times and a few weeks passed that I turned on geth app but cannot find any node to sync up.

`Geth
Version: 1.9.24-stable
Git Commit: cc05b050df5f88e80bb26aaf6d2f339c49c2d702
Git Commit Date: 20201112
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: linux
GOPATH=
GOROOT=go`

**Comment by rjl493456442** [comment]
Can you try the latest master? We had a fix for the discovery and it should fix your problem. #21906

**Comment by freeyssu** [comment]
@rjl493456442 oh it works well.
appreciate 👍 
You may close this issue right now.
