### ISSUE TITLE
M1 Chip with Big Sur Problem 

### ISSUE THREAD

**Issue by mkashiouris** [ethereum/go-ethereum#21978]
#### System information

Geth
Version: 1.9.24-stable
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: darwin
GOPATH=
GOROOT=go

OS & Version: Mac OSX BigSur 

#### Expected behaviour

Run normal node 

#### Actual behaviour

INFO [12-08|17:26:21.754] Imported new chain segment               blocks=9  txs=1634 mgas=112.232 elapsed=8.974s mgasps=12.506 number=11412822 hash="b1eb07…e56f09" age=7h27m4s  dirty=248.15MiB
assertion failed [*ret_index + 2 == num_insts]: RET should be second last instruction in translation
(StateRecovery.cpp:304 check_cfg)

#### Steps to reproduce the behaviour

geth console --datadir /Volumes/SSD/Eth1 --http.api eth,net,web3 --syncmode fast --ipcpath "./Library/Ethereum/geth.ipc" --http --http.port 8523  --networkid 1

#### Backtrace

````
[backtrace]
````
I am keep getting this error message when I run Rosetta terminal with the M1 Apple Mac 

![Screen Shot 2020-12-08 at 7 29 24 PM](https://user-images.githubusercontent.com/12383590/101557798-b4b61000-398b-11eb-8356-2cd36fc08bfd.png)

**Comment by AusIV** [comment]
This strikes me as a Rosetta issue rather than a geth issue, but I'm curious if there's a reason you're running the amd64 build under Rosetta rather than the arm64 build natively.

**Comment by fjl** [comment]
I think Go doesn't support darwin/arm64 yet. It will be supported in Go 1.16.

**Comment by hallahan** [comment]
Maybe try compiling with go 1.16beta1.darwin-arm64.pkg ?

https://golang.org/doc/install?download=go1.16beta1.darwin-arm64.pkg

**Comment by marcoVanLarco** [comment]
@mkashiouris hi did you manage now? I would like to test Geth on the M1 as well...should in theory be supported now? Tx

**Comment by hallahan** [comment]
I installed Go with 1.16beta1.darwin-arm64.pkg. This worked without any problems. Geth is now running on my M1 MacBook Air. I was able to pull in both mainnet and ropsten successfully.

**Comment by marcoVanLarco** [comment]
Hi @hallahan thanks a lot for your reply, looking forward to get this going. Cheers

**Comment by fjl** [comment]
Go 1.16 is out now and supports the M1
