### ISSUE TITLE
Delete the wiki

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#21983]
follow up from: https://github.com/ethereum/go-ethereum/issues/21945#issuecomment-741799164

the wiki already stated - "we will soon delete it"

and the duplication only leads to problems and support tickets

**Comment by danielsam** [comment]
I agree, Wiki should be deleted ASAP.

**Comment by holiman** [comment]
Steps: 
1. Add links on all (or the most visited) pages to the relevant doc-page on the official documentation, "Go here instead"
2. Remove the content on the page, so we only have the link
3. Much later: delete the wiki

**Comment by ligi** [comment]
next step is step 3 - so perhaps next step in a year?!
Maybe a reminder bot could be nice for this: https://github.com/probot/reminders

**Comment by fjl** [comment]
The wiki pages are now replaced with links. We can delete them in one year, but no need to keep an issue for that.
