### ISSUE TITLE
Why are so many threads turned on? 

### ISSUE THREAD

**Issue by Xcrab** [ethereum/go-ethereum#21982]
Version: 1.9.4-unstable
![image](https://user-images.githubusercontent.com/20314873/101640998-29607b80-3a6c-11eb-8c08-6ea65cedfa81.png)

**Comment by ligi** [comment]
Please provide more information. E.g. how do you start geth?

**Comment by Xcrab** [comment]
> Please provide more information. E.g. how do you start geth?

I use this command to activate geth.
./geth --cache=204500  --rpc --rpcapi eth,web3,debug --syncmode full  --gcmode archive --maxpeers 1000  --lightpeers 0 --lightserv 0 --datadir=/home/dapp/ethereum/.ethereum/ --datadir.ancient=/home/dapp/ethereum/.ethereum/old-chaindata

I don't think I would have started that many threads in a lower version of the client.

**Comment by rjl493456442** [comment]
There are lots of internal goroutines scheduled. OS will try to assign them to the different threads.

Btw your Geth version is super old. And it's even consensus broken. Please upgrade the node if you are using it for mainnet.

**Comment by Xcrab** [comment]
> There are lots of internal goroutines scheduled. OS will try to assign them to the different threads.
> 
> Btw your Geth version is super old. And it's even consensus broken. Please upgrade the node if you are using it for mainnet.

sorry, I wrote the wrong version. My Geth version is 1.9.24

**Comment by rjl493456442** [comment]
Yup, I will close it right now. If you have any other question, feel free to open a new ticket.
