### ISSUE TITLE
Ethereum Wallet: Is the address under the Ethbase account in mist a public address? 

### ISSUE THREAD

**Issue by azulmarino** [ethereum/go-ethereum#2198]
In Mist . Initial wallet screen:

Is the address under the Ethbase account in mist a public address?

If so, how do I find the related private key?

The address on the wallet shows keys , but I presume this is the public account/addr ? So I can send ether. 

May be I just need a pointer to docs.

**Comment by karalabe** [comment]
@frozeman

**Comment by frozeman** [comment]
Yes its a public address. The keys are store in your keystore folder, which you can reach when clicking in the meny the "Backup -> Accounts..." button
