### ISSUE TITLE
Is there a way to monitor the progress of Ethereum?

### ISSUE THREAD

**Issue by blackhatzw** [ethereum/go-ethereum#2199]
Is there a way to monitor the progress of Ethereum? For example, from where I can see how many hours/days left to release Homestead.

**Comment by karalabe** [comment]
The safest bet to track any announcement is the [Ethereum reddit](https://www.reddit.com/r/ethereum/) forum. Everything is announced there. There isn't a fixed release date for homestead. On Geth side we have all the preparations finished, but we need to wait for all clients to get the homestead changes done and then need to decide on a final block number for Homestead.
