### ISSUE TITLE
how to set ws.origins?

### ISSUE THREAD

**Issue by yushoaqiang** [ethereum/go-ethereum#21997]
set 192.168.1.2 allow this IP connect, set * allow any ip connect.
if need allow 192.168.1.2 and 192.168.1.3  connect, set what?

**Comment by fjl** [comment]
You can list multiple comma-separated origins. Please note that ws.origins applies filtering to the HTTP 'origin' header, it is not a filter for IP addresses. You need to use a firewall to filter by IP address.
