### ISSUE TITLE
Database compacting

### ISSUE THREAD

**Issue by 9974333** [ethereum/go-ethereum#21996]
Dec 10 20:45:14 geth geth[7675]: WARN [12-10|20:45:14.447] Database compacting, degraded performance database=/mnt/ssd/goethereum/geth/chaindata

This happened after my SSD was unplugged (by mistake) and a geth restart - this has been going on for over a day - do we know why and can we get this sorted? Am I able to delete a file then get geth to use frozen database ?) - I read that this had been fixed  ?

**Comment by rjl493456442** [comment]
> Database compacting, degraded performance database=/mnt/ssd/goethereum/geth/chaindata

This log means the leveldb is running the compaction and suspend all the write operations.

> This happened after my SSD was unplugged (by mistake) and a geth restart 

I think leveldb enters the recovery mode(I'm not sure whether your database can be recovered). I **guess**, the manifest file of leveldb is missing, so *all the files in the leveldb are put in the level0, so it needs BIG compaction to sort them again*.

I would suggest that let it running. And probably you can update the progress here.

Btw, are you running the archive node? Or just the normal fullnode.

**Comment by 9974333** [comment]
Thanks
I have exported to file up to the crash point (just before) then removed db then am currently importing so we will see if it does a good job, i did that prior to receiving your email so thank you very much for your attention
Cheers Simon

**Comment by ligi** [comment]
Seems this is not actionable so closing
