### ISSUE TITLE
dumpconfig doesn't output config for metrics

### ISSUE THREAD

**Issue by lightclient** [ethereum/go-ethereum#22007]
#### System information

Geth version: `v1.9.25`
OS & Version: linux

#### Expected behaviour
Print config that turns on monitoring.

#### Actual behaviour
No observable change to output

#### Steps to reproduce the behaviour
```console
$ diff <(geth --metrics --pprof dumpconfig) <(geth dumpconfig)
$
```

**Comment by rjl493456442** [comment]
The metrics flags are not part of the config. Are they necessary for you in some special scenario?

**Comment by lightclient** [comment]
No, not really. As a user, I just found it confusing that they weren't part of the configuration. I was trying to generate a few `config.toml` files for various scenarios and *seems* like `--metrics` should be configurable by the TOML.

**Comment by MysticRyuujin** [comment]
I opened a similar issue a while back, seems to just be a continuation of that :slightly_smiling_face: 

#21262

**Comment by lightclient** [comment]
Ah I see, nice catch. Also appears that `--goerli` isn't dumpable.

**Comment by MysticRyuujin** [comment]
I think `--goerli` just modifies the network flag and maybe a couple others, the flag itself doesn't dump, but the RESULTS of the flag does get dumped.

**Comment by lightclient** [comment]
@MysticRyuujin although it updates the config with the correct network ID, it doesn't start with the correct genesis block (starts with mainnet).

**Comment by 11qu1d** [comment]
Noticed this problem while trying to consolidate all config into a single file. At the moment i have to pass all the metrics config as flags and the rest in the config file. Not ideal if we want to keep things consistent.
