### ISSUE TITLE
Fatal: Failed to register the Ethereum service: failed to retrieve genesis from ancient EOF

### ISSUE THREAD

**Issue by navy665180** [ethereum/go-ethereum#22008]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.
my computer is powered off because the ele-power is sudden off,now i restart the geth ,but error:
Fatal: Failed to register the Ethereum service: failed to retrieve genesis from ancient EOF
what shall i do now?thanks

**Comment by rjl493456442** [comment]
Looks like your ancient folder is broken. Can you do a `ls -l`? The ancient folder is `<your-geth-datadir>/chaindata/ancient`

**Comment by navy665180** [comment]
@rjl493456442 yes ,i did it,and find it,can i delete it ?or do anything eles?

**Comment by ligi** [comment]
Sorry but you need to resync

**Comment by pepa65** [comment]
Note, I had this too.
