### ISSUE TITLE
Compilation error func Call()  from /accounts/abi/bind/base.go (master, release-1.9)

### ISSUE THREAD

**Issue by aquavirgo** [ethereum/go-ethereum#22001]
#### System information

Geth version: `1.9`
Solc version:  0.5.16+commit.9c3226ce.Linux.g++
OS & Version: Windows/Linux/OSX

#### Actual behaviour
The problem with compilation of the GO file generate from the abigen.
The error information is "(type *interface {}) as type *[]interface {} in argument to"

#### Steps to reproduce the behaviour
The base of the error is in changes in the accounts/abi/bind/base.go file on the master and the release-1.9 branches. 

 results argumet has type ***[]interface{}** 

(c *BoundContract) Call(opts *CallOpts, results ***[]interface{}**, method string, params ...interface{})

In lower versions result is interface{} type and works properly.
func (c *BoundContract) Call(opts *CallOpts, results interface{}, method string, params ...interface{}) error {
	
The fast solution for this problem is:

func (c *BoundContract) Call(opts *CallOpts, results interface{}, method string, params ...interface{}) error {
	// Don't crash on a lazy user
	if opts == nil {
		opts = new(CallOpts)
	}
//	if results == nil {
//		results = new([]interface{})
//	}
	// Pack the input, call and unpack the results
	input, err := c.abi.Pack(method, params...)
	if err != nil {
		return err
	}
	var (
		msg    = ethereum.CallMsg{From: opts.From, To: &c.address, Data: input}
		ctx    = ensureContext(opts.Context)
		code   []byte
		output []byte
	)
	if opts.Pending {
		pb, ok := c.caller.(PendingContractCaller)
		if !ok {
			return ErrNoPendingState
		}
		output, err = pb.PendingCallContract(ctx, msg)
		if err == nil && len(output) == 0 {
			// Make sure we have a contract to operate on, and bail out otherwise.
			if code, err = pb.PendingCodeAt(ctx, c.address); err != nil {
				return err
			} else if len(code) == 0 {
				return ErrNoCode
			}
		}
	} else {
		output, err = c.caller.CallContract(ctx, msg, opts.BlockNumber)
		if err != nil {
			return err
		}
		if len(output) == 0 {
			// Make sure we have a contract to operate on, and bail out otherwise.
			if code, err = c.caller.CodeAt(ctx, c.address, opts.BlockNumber); err != nil {
				return err
			} else if len(code) == 0 {
				return ErrNoCode
			}
		}
	}

//	if len(*results) == 0 {
//		res, err := c.abi.Unpack(method, output)
//		*results = res
//		return err
//	}
//	res := *results
	return c.abi.UnpackIntoInterface(results, method, output)
}

#### Backtrace

````
[backtrace]
````

**Comment by MariusVanDerWijden** [comment]
Yes, we changed something in abigen a while back. You need to update your dependencies or downgrade abigen.
See also https://github.com/ethereum/go-ethereum/issues/21758
