### ISSUE TITLE
Transactions losing not being broadcasted

### ISSUE THREAD

**Issue by janke99** [ethereum/go-ethereum#22027]
#### System information

Geth version: 
```
Geth
Version: 1.9.25-stable & 1.9.21-stable
Git Commit: e7872729012a4871397307b12cc3f4772ffcbec6
Git Commit Date: 20201211
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.6
Operating System: linux
GOPATH=
GOROOT=go
```
OS & Version: Linux

#### Expected behaviour
web3.eth.sendTransaction(...) returns a hash and the transaction should be broadcasted to the network.

#### Actual behaviour
returns a hash but the transaction is never broadcasted to the network, and then use web3.eth.getTransaction($hash) return null

#### Steps to reproduce the behaviour
it's not happen every time, if i send some (like 10) transactions at the same time, it may be losing 5 transactions
geth run cmdline
`./geth --syncmode 'fast' --datadir ./blocks --maxpeers 200 --light.maxpeers 200 --maxpendpeers 2000 --port 30304 --http --http.port 8555 --http.addr '0.0.0.0' --http.corsdomain '*' --http.vhosts '*' --ws --ws.port 8556 --ws.addr '0.0.0.0' --ws.origins '*' --txpool.nolocals --txpool.pricelimit 12000000000 --txpool.globalslots 40960 --rpc.txfeecap 100 console`

How can i prevent this from happening in the future?

**Comment by rjl493456442** [comment]
You can remove `--txpool.nolocals` then all transactions submitted via RPC or the sender is in `--txpool.locals` set will be treated as "local transactions".
All local transactions will be saved into the journal and will be resent across the restarts if it's still not confirmed.

**Comment by janke99** [comment]
`--txpool.nolocals` means Disables price exemptions for locally submitted transactions, i'm sure gasPrice is higher than local pricelimit 12 GWEI

**Comment by ligi** [comment]
How do you submit your transactions at the same time? Are you sure you have no conflicting nonces?

**Comment by holiman** [comment]
Please provide a js snippet showing how you do it.

**Comment by janke99** [comment]
it's just like this code
```
for (let i = 0; i < config.accounts.length; i++) {
    let account = config.accounts[i];
    this.web3.eth.sendTransaction({
        from: account.address,
        to: config.send.address,
        gas: new BigNumber(config.send.gas),
        gasPrice: new BigNumber(config.send.gasPrice * Math.pow(10, 9)).toFixed(0),
        value: sendValue.toFixed(0),
    }).on('transactionHash', function (hash) {
        console.log(`sendTransaction hash: ${hash}`);
    })
}
```

**Comment by karalabe** [comment]
Ok, is there a reason to disable local tracking? That ensures no matter what happens, locally submitted transactions won't get dropped. If you are running a public node I might understand wanting to disable it. Are you?

Setting the txpool price limit to 12 gwei only means your pool won't accept cheaper ones, but if there's enough more expensive ones to push yours out, your's are getting pushed out. Would be nice to know what prices you submit at and what are the network ones.

**Comment by MariusVanDerWijden** [comment]
This issue has become quite stale now. I'm going to close it. If you enable locals, you will not loose your transactions. I don't see a reason to disable the price exemption for local transactions, you can always choose to pay a higher price.
