### ISSUE TITLE
geth build failure

### ISSUE THREAD

**Issue by yp945** [ethereum/go-ethereum#22024]
#### System information

Geth version: `geth 1.9.24`
OS & Version: macOS Big Sur
go version : go1.15.6 darwin/amd64

#### Expected behaviour

When I use the `make geth` command, the compilation fails with the following error message

#### Backtrace
![image](https://user-images.githubusercontent.com/15030378/102230268-a2a61580-3f27-11eb-872e-950fc788f92f.png)
![image](https://user-images.githubusercontent.com/15030378/102230306-adf94100-3f27-11eb-9e1a-8ca9809ce706.png)

````
[backtrace]
````

**Comment by ligi** [comment]
Do you run it on an M1? So this might be related #21978

**Comment by yp945** [comment]
no, macbookpro 2017

**Comment by yp945** [comment]
> Do you run it on an M1? So this might be related #21978

no, macbookpro 2017

**Comment by yp945** [comment]
> #### System information
> Geth version: `geth 1.9.24`
> OS & Version: macOS Big Sur
> go version : go1.15.6 darwin/amd64
> 
> #### Expected behaviour
> When I use the `make geth` command, the compilation fails with the following error message
> 
> #### Actual behaviour
> #### Steps to reproduce the behaviour
> #### Backtrace
> ![image](https://user-images.githubusercontent.com/15030378/102230268-a2a61580-3f27-11eb-872e-950fc788f92f.png)
> ![image](https://user-images.githubusercontent.com/15030378/102230306-adf94100-3f27-11eb-9e1a-8ca9809ce706.png)
> 
> ```
> [backtrace]
> ```

**Comment by yp945** [comment]
It related with https://github.com/shirou/gopsutil/issues/976

**Comment by gballet** [comment]
It seems that you are using a non-official version clang/LLVM, which is the one coughing on the problem. The versions not provided by Apple don't seem to define `TARGET_OS_MAC`.

The gopls people don't look like they are keen on fixing it, so there's not much we can do. We will upgrade to the latest version of that package when they fix it. In the mean time, I'll close the issue as this is related to your configuration and not something geth-specific.
