### ISSUE TITLE
Crash with 'out of gas' on local geth node when querying Uniswap balances

### ISSUE THREAD

**Issue by hjorthjort** [ethereum/go-ethereum#22032]
#### System information

Geth version: 
```
Version: 1.9.25-stable
Git Commit: e7872729012a4871397307b12cc3f4772ffcbec6
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.6
Operating System: linux
GOPATH=
GOROOT=go
```

OS & Version: 
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

#### Expected behaviour

Querying Uniswap Liquidity Pools with a local Ethereum node: presents a list of the pools I'm participating in.

#### Actual behaviour

Notification:
```
Failed to retrieve Uniswap balances: Failed to query <bound method EthereumManager._call_contract of <rotkehlchen.chain.ethereum.manager.EthereumManager object at 0x7fd3f2589590>> after trying the following nodes: ['own node']
```

The Geth node logs:
```
WARN [12-17|16:58:03.122] Served eth_call                          conn=127.0.0.1:51492 reqid=27 t=163.914666ms err="out of gas"
```

#### Steps to reproduce the behaviour

0. In Profile -> Settings, set Eth RPC Endpoint to a local node's RPC endpoint, e.g. `http://localhost:8545`
1. Open DeFi -> Deposits -> Liquidity Pools
2. Open the settings (cog wheel)
3. Add a Uniswap module, and select an address participating in several liquidity pools (in my case 3).
4. Back to  DeFi -> Deposits -> Liquidity Pools and refresh

Might be possible by just adding any account with many liquidity pools. If that doesn't work, I can send my address (the failing one) over DM if needed.

#### Backtrace

N/A

**Comment by hjorthjort** [comment]
Same problem here as #22033: posted on the wrong repo. Really sorry for the screwup!

**Comment by MariusVanDerWijden** [comment]
No worries! Will the issue if that's ok
