### ISSUE TITLE
Show liquidity pool stakes in dashboard, and count toward total net worth

### ISSUE THREAD

**Issue by hjorthjort** [ethereum/go-ethereum#22033]
# Rationale

Staked liquidity are part of your total assets. Currently it seems staked liquidity is not counted to your totals or shown in your assets. That gives a skewed balance of your actual holdings.

I could imagine just having the liquidity pool stakes counted under your "accounts and balances". If some users really don't want to have their stakes and regular holdings counted together, "Liquidity Pools" could be a new card in the dashboard under "Assets" in the Dashboard.

# Implementation

The liquidity pools seem to be cached locally, at least temporarily. The interface shows the actual balances in the pools, and their value in the local currency. So it should be a matter of pulling in those balances when loading the dashboard and adding their value to the total value.

I don't have time to implement it myself (just yet), but would be willing to switch to (more permanent) premium for it :)

**Comment by MariusVanDerWijden** [comment]
I think this is the wrong repo, you probably wanted to open this issue here: https://github.com/rotki/rotki/issues

**Comment by hjorthjort** [comment]
Wow, what a blunder. Thanks!
