### ISSUE TITLE
Rinkeby Faucet No Ethereum Address Found

### ISSUE THREAD

**Issue by anti-seal** [ethereum/go-ethereum#22031]
So I clearly have a tweet with a valid ethereum address, but it says no ethereum address found.

https://twitter.com/josmans1/status/1339595978567892993?s=20

**Comment by ravisriv** [comment]
Same here. I tweeted several times. It can't read a tweet. Basically, it is not working. It keeps on saying no Ethereum address found. Its not working.

**Comment by sanoyphilippe** [comment]
same issue for me

**Comment by bernatfp** [comment]
Same, can't get it to work with tweets nor with FB posts...

**Comment by Aggrord09** [comment]
👍

**Comment by Aggrord09** [comment]
Top

**Comment by reuvenpo** [comment]
same here :shrug:

**Comment by ligi** [comment]
Please let me know your addresses and how much rinkeby ether you need

**Comment by sanoyphilippe** [comment]
> Please let me know your addresses and how much rinkeby ether you need

0xaEa9a49dEd76F9954DCD41E988Ee68EeA550CF47
10 ETH rinkeby

**Comment by ligi** [comment]
this seems to be a token contract that does not accept ether - please send an EOA

**Comment by sanoyphilippe** [comment]
> this seems to be a token contract that does not accept ether - please send an EOA

what's EOA? also why doesn't it accept ether? do I need ether to create NFTs? I am still new to this. thank you

**Comment by ligi** [comment]
EOA -> Externally Owned Address

Unfortunately I do not see the code of your contract - so I do not know why it does not accept it.
Yes - you need ether to create NFTs

**Comment by ravisriv** [comment]
> Please let me know your addresses and how much rinkeby ether you need

0x85F3d3793F58291460EFcE00c93f0E4f29841FdF

Thank you!

**Comment by ligi** [comment]
@ravisriv you have >18 ETH now in your account

**Comment by samson9993** [comment]
@ligi Some ETH (10) to this account would be great. Thank you!

0xB2cFB6454932Be803066435B8ee63Ae141f180D6

**Comment by ligi** [comment]
@samson9993 https://rinkeby.etherscan.io/tx/0x45df1e2c4a209aca59c92cda9fb92cfef413147a7e4e93b0643d774118c6a069

**Comment by samson9993** [comment]
Thank you! @ligi 👍

**Comment by bernatfp** [comment]
> Please let me know your addresses and how much rinkeby ether you need

Would it be possible to get 20 Rinkeby ETH?

0xFe093D3b19C6c52D40Dc3F11E5C5393d1fF4c59c

Thanks @ligi !

**Comment by reuvenpo** [comment]
My address is 0x60baA9f4ab5FC82B72d06Bc66Da1Eb1e8FDE60E1
Thanks @ligi ! :smile:

**Comment by ligi** [comment]
@remyroy https://rinkeby.etherscan.io/tx/0x7503a8812a432e59335b80083108c49e47aa807cd19188d7ec365f857cd17b07
@bernatfp 10 for now - LMK when you ran out: https://rinkeby.etherscan.io/tx/0x46ad80b0ff21a0b23137520335c3779d796df1840852cc5c22572bbba7f39dcc

**Comment by Tigo9527** [comment]
@ligi Please help me and my team mates: each for 6 eth or 18 eth to me. we runs a new chain and interact with ethereum, need eth to test cross chain operation. Thanks.
0xa1F29a57BD2240aAECABcAfB3Febed914648b64E
0xd76f955ac8FAa0eb9c139A32cBf19d9E678Cd1F9
0x9a5ef76F0e2d03dEDa0e42bA692B36d685C93F2e    me

**Comment by WuYansong** [comment]
@ligi Please help me...,My address is 0xdA9914E4479C87FBf80c8C2ECe3fe9A97F2f0fba, 10 ETH to this account would be great.Thank you~

**Comment by yayahappywork** [comment]
@ligi Please help me, my address is 0x5584A45499d9A19D83173894Bf57986E769E6198,I'd like 10 rinkeby ETH
Thanks~

**Comment by flickmaking** [comment]
Hi ligi,
Can I get 3 ETH on 0x76B9773B50523b3373077f7478F7DCA5856ee47e on Rinkeby?
Thanks

**Comment by dr3amboy** [comment]
I haven't been able to get any of the test faucets to work, @ligi if you could possibly send some Rinkeby test ETH to 0x5D79b92efed4Aa3a6a69868ab775A4773b712d4F that would be greatly appreciated!

**Comment by CarlGocht** [comment]
@ligi same issue as the others, can't get the rinkeby faucets to work, 10 rinkeby eth to 0xd1015Efa96441d2326F8194E7b1f5FE8425b84f8 would be appreciated. Thank You!

**Comment by isaac0440** [comment]
@ligi Same issue as the others, cant get the rinkeby faucets to work, 10 rinkeby eth to 0xdbC2E36941De2a4724EbfD25098c44B8F1ce476D would be awesome. THANK YOU!

**Comment by nilankanayana** [comment]
same issue, if you could send me 10 eth, it would be great, thanks.
address: 0xDc7026F5a4AEc3001817ed661Ff9B786E9186e28
post: https://twitter.com/nilankanayana/status/1343044369893355522

**Comment by dlarchikov** [comment]
Same problem
![20201227-150123](https://user-images.githubusercontent.com/3336114/103170312-6b533500-4854-11eb-8db1-4f75b21303f8.png)

**Comment by ligi** [comment]
You should all have rinkeby ether now 
@Tigo9527  I send 18 to you - please distribute to your mates
@dlarchikov please provide an address here so I can send you some

**Comment by dlarchikov** [comment]
> You should all have rinkeby ether now
> @Tigo9527 I send 18 to you - please distribute to your mates
> @dlarchikov please provide an address here so I can send you some

0xc399a24200E66F278cbD32B1ED5ad75f887c929B

**Comment by ligi** [comment]
@dlarchikov done

**Comment by thekryptozen** [comment]
I too face the same issue. Please send ETH to my address below

0x09c390aE708c9333124f9d7f6196bFec0a7C474B

**Comment by ligi** [comment]
done

**Comment by Kronoxis** [comment]
I also have this issue. Can you send some ETH to the following address?
0x57b2D27191d80afDb520AD07AD407C2a99B34127
Thanks

**Comment by pauloprea** [comment]
I could use some help as well. 10 ETH would be great.
0x83cbA40Cf3Ad0298CE83Ef105cE865234ca1dAFa

**Comment by ligi** [comment]
@Kronoxis @pauloprea done

**Comment by spagnolodesign** [comment]
Some ETH for testing please ...
0x7b3B9979FF6b4BfC4c352f05c30A94A68048cd2B
Namaste

**Comment by ligi** [comment]
@spagnolodesign done

**Comment by pauloprea** [comment]
Thank you @ligi!

**Comment by freestylsoccer** [comment]
Hello, I also have this issue
can you send me some ETH for test please, 3 ETH would be great.
0xeD2eF7d8e7E788147a57aA0EE99cBee926451Bb1

**Comment by ligi** [comment]
@freestylsoccer done

**Comment by freestylsoccer** [comment]
Thank you @ligi !

**Comment by Tigo9527** [comment]
Thank you @ligi . You are awesome.

**Comment by Kronoxis** [comment]
> @Kronoxis done

@ligi My Rinkeby ETH balance hasn't changed. Do you have the transaction address by any chance? Or can you retry?
0x57b2D27191d80afDb520AD07AD407C2a99B34127

**Comment by ligi** [comment]
@Kronoxis oh sorry must have been a c&p problem - so someone got double - should be there now ;-)

**Comment by busgo** [comment]
me to  
can you send me some ETH for test please, 8 ETH would be great.
0x7ad5a087a22ce6612388d267872ec2e60dafa691

**Comment by mehulnagar12** [comment]
Hi @ligi,
I'm facing the same issue, can I get 18.75 ETH for the testnet Rinkeby.
address : 0x0F397D4c00e7592E4915Bd8654500868C3cC72CE

Thank You!

**Comment by mxvsl** [comment]
Hey @ligi ,
Can you please send 30 rinkeby eth
Address: 0x34dFb79e107915805E73dad96059bFBB26219E00

**Comment by rbishopny** [comment]
0x339FC29d3F8D29Def2267484ff2db7537f396E35

Please send 18 ETH.  Thank you!

**Comment by 0xLeia** [comment]
Hey, could you please send 18 ETH to `0x1e1a88bdEf16b1906b85c31c625baEf8EAabBA98`? Thanks!

**Comment by navy1125** [comment]
> Please let me know your addresses and how much rinkeby ether you need

0x95b194fa00e6EC9a35b1b483f404b6CA89603380

thank you!

**Comment by malbecAr** [comment]
@ligi 10 eth please
0xcC4768Dfaae25224103A4801dED30787b74Ec28d

THANK YOU!

**Comment by aloisius82** [comment]
please send me 20 eth 0xD5fB11a7655D0095fE9E090c205C91a8f0CDef47
thanks

**Comment by SvyatoslavLiven** [comment]
5 ETH  please)
0x696CC718d80fDd2eC8e2CE0b29cFcEA4c16d9496

Thank you!!))

**Comment by cristocer** [comment]
@ligi 15 eth would be nice please
0x66353521A464345BE1AdCd74A25D686981a359c6

Thank you!

**Comment by k1jason2082** [comment]
@ligiCan you send me 10 ETh please 0xa531DF3729d02242f10B5F9934C81dEEafa98e7a
Thanks

Sent from Yahoo Mail for iPhone


On Wednesday, December 30, 2020, 11:31 PM, malbecAr <notifications@github.com> wrote:




@ligi 10 eth please
0xcC4768Dfaae25224103A4801dED30787b74Ec28d

THANK YOU!

**Comment by thelastjosh** [comment]
@ligi Same issue. 10 ETH please!
0x356bd1169A2b94B5a3C9D9F356FA5D35E584A521

Thank you!!!

**Comment by millileakz** [comment]
same issues - if anyone has some eth to Rinkeby ETh to spare for test i will appreciate this :) 

0x7058823b0F892aab83E4841c39a5Cef4f1AB962B

**Comment by einfach-edel** [comment]
same issue - I created my first account, shared my EOA via Facebook and Twitter. Entered the link on https://faucet.rinkeby.io/ and got the error message "No Eth address found to fund". 

Can someone send me 1 Rinkeby Eth to
0xF5aa9a685fCc792C1E616803B57a8c0F1015e0f1

**Comment by ttakumat** [comment]
Hi. same issue here.
I'd really appreciate if someone can fund 1 eth to
0x348c0a7a93F86E451971DFC89D2A74519bBaEBfd
Thanks.

**Comment by k1jason2082** [comment]
@ligi Please help me...,My address is 0x0bd5A2E73576Dc3eE3820d05A5985897A2D45B81, 10 ETH(Rinkeby) to this account would be great.Thank you~

**Comment by lordkayag** [comment]
Having same issue.
Please send 5 eth rinkeby to 0x43A0033408C2bCc86102385F1A4FcB37bABFe8f8

**Comment by noahc66260** [comment]
Me too.
Please send 3 ETH rinkeby to 0x71849D7a22890f60C6D6BE83E2E48cdB4A24CEA7
Post: https://twitter.com/devilscompiler/status/1344848283626180609

**Comment by z330789559** [comment]
> @ravisriv you have >18 ETH now in your account

me too 
Please send 18ETH rinkeby to 0x896267e34bD86ecc9478333F412705235Fc66E4a 
https://twitter.com/al84628047/status/1343894099783372801?s=20

**Comment by vnavascues** [comment]
> Please let me know your addresses and how much rinkeby ether you need

Hi, can I get 18 ETH at 0x5E1e93B6D25690B7A26d70468f81d5b6441885c4? Many thanks
https://twitter.com/vnavascues1/status/1345022515408756745

**Comment by Kronoxis** [comment]
We're planning on doing some extensive testing with 4 devs tomorrow, so I could use some more ETH to distribute among my team. Can you send 16-20 ETH to the following address?
0x57b2D27191d80afDb520AD07AD407C2a99B34127
Thanks!

**Comment by foravneet** [comment]
2-3 ETH at this address will help. Thanks ! - 0x1600431bD009a0EEb62247a429dE609b9E0014B5

**Comment by Ezparga** [comment]
Just found this thread, we're urgently needing to carry out some testing and the faucet isn't working

Please could you send 15 ETH to:

0xC20fabA9c8cc4E4Dfa059D8F7B39A6Eb17F34eDb

Thank you!

**Comment by luongs3** [comment]
Please 15 ETH to 0x91878ec5288E944fD4A357022d60DbE9Ab49c46f
I really need it now to test my product

**Comment by DGKSK8LIFE** [comment]
scam or not?

**Comment by setragk** [comment]
Can someone please send 10 ether to 0xB3D8C850aD1f50CF5863600b3F49c1AC068400e4

**Comment by karalabe** [comment]
This was fixed yesterday, needed a new Twitter auth workflow.

**Comment by eebit2020** [comment]
Please send me 1 ethe 0x8f6f2f241A993EBE06E7d383ab9D4945BF189138

**Comment by montalban** [comment]
Could someone please send 10 ETH to 0xf8B17B25032b82CBDDEe3413FDb7E195D6D2752C Thanks!!

**Comment by UsabilitySpace** [comment]
It's not working for me too. 

So, would someone send some test ether to 0x9413391975190f0413ddc331c41A2F32847D960d

**Comment by knottl** [comment]
Can someone send me some ether to 0xb89238b93Fb85a99daeb15121DF828F225f467BE thank you  @ligi

**Comment by kietfriends** [comment]
Could someone please send 10 ETH to 0xD3afb233FA3CB3982e59497a269D1de290373b74 Thanks!!

**Comment by ligi** [comment]
What problems do you face with the faucet?

**Comment by ZhuyichaoCode** [comment]
Please could you send 15 ETH to:

0xf32e76Bf36996b3b7A3977086969C13AdB4f3Ac9

Thank you!

**Comment by audreyberg** [comment]
No Ethereum address found ..... Can someone please help me ? 🙏 Need 18.75 Ethers0x5614e605c47A9947d9de72e5Ed2c5B443d423273

**Comment by tangtuozhou** [comment]
could you send me 10 ethers?thanks
add: 0x2dd5de5c1f17c670f4ab7bfd16ee21f23f0028ae

**Comment by 1549977849** [comment]
Hi. same issue here.
I'd really appreciate if someone can fund 10 eth to
bd666261229791e20e754b7848482137fa74f8d5
Thanks.

**Comment by MaryMak888** [comment]
Привет! Аналогичная проблема, очень буду признательна 3 эфира / 8 часов 0x8E9E83150d3dBf756c9982a93A73421d9764A1e7

**Comment by linyiios** [comment]
I'd really appreciate if someone can fund 10 eth to
0x516aD4169860e98FEC01fdcDfF4A67040B534579

https://www.facebook.com/linyiios/posts/3000330973625269

Thanks!!!

**Comment by KuldeepVagadiya** [comment]
Can someone please help me ? 🙏  Need 18.75 ETH in 
 0x880a8DA356DA570E1f79CB865cf68CC8beCf8121 
@ligi or someone, any help will highly appreciated.

**Comment by austinkat94** [comment]
Hi I've posted but keeps saying no account found when I do have one. Trying to test my smart contract please send 18.75 ETH if possible.

https://www.facebook.com/austintaylorkat/posts/5027431633938380

0x7e9b29fc4814422afdc55E537E5B1fc91050040f

Thank you!

**Comment by ubani** [comment]
Hi @ligi 
Same issue here, please Rinkeby ETH 18.75 to 0x9BdE7560C009827780021fcd0d847F64ba8Dc003
Thanks!
