### ISSUE TITLE
`net_version` method not available

### ISSUE THREAD

**Issue by realbigsean** [ethereum/go-ethereum#22034]
#### System information

Version: 1.9.26-unstable
Git Commit: 3c46f5570bd674cf49c0113352ff79a4e026a5b8
Architecture: amd64
Go Version: go1.15.6
Operating System: linux

#### Expected behaviour
```
$ curl -X POST 'localhost:8545' --header 'Content-type: application/json' --data-raw '{ "jsonrpc":"2.0", "method":"net_version", "params":[], "id":1 }'
{"jsonrpc":"2.0","id":1,"result":"1"}
```
#### Actual behaviour
```
$ curl -X POST 'localhost:8545' --header 'Content-type: application/json' --data-raw '{ "jsonrpc":"2.0", "method":"net_version", "params":[], "id":1 }'
{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method net_version does not exist/is not available"}}
```
geth logs: 
```
WARN [12-17|21:04:03.023] Served net_version                       conn=127.0.0.1:36678 reqid=1 t="34.56µs" err="the method net_version does not exist/is not available"
```
#### Steps to reproduce the behaviour

Run `geth --http` and the above `curl` command

#### Backtrace
N/A

**Comment by MariusVanDerWijden** [comment]
Hmm yeah I could repro, also `net.version` in the console doesn't seem to work anymore. I'll take a look

**Comment by MariusVanDerWijden** [comment]
It seems a recent PR deprecated `net_version`. You can still use `eth_chainId` to query the current chain

**Comment by realbigsean** [comment]
Thanks for the reply.

Is it intentionally being deprecated? Lighthouse depends on it at the moment.

**Comment by Torabek** [comment]
> Thanks for the reply.
> 
> Is it intentionally being deprecated? Lighthouse depends on it at the moment.

Aslo Remix IDE can connects to a network, but unable to recognize its networkId

**Comment by holiman** [comment]
> It seems a recent PR deprecated net_version. You can still use eth_chainId to query the current chain

Hol' up! The `chainId` corresponds to the blockchain chain id. Which, in the case of mainnet, is the same as the `network id`. For private networks, that's not a given, although it's usually the case. 

The `network-id` decides whether two peers will talk to eachother on the p2p layer. It's a network setting, basically. 

> Lighthouse depends on it at the moment.

Well, they depend on the `chainId`, no the network id, right?

**Comment by jbcebe** [comment]
This is possibly breaking Prysm: https://github.com/prysmaticlabs/prysm/issues/8124

**Comment by realbigsean** [comment]
> Well, they depend on the `chainId`, no the network id, right?

Both are used because both are mentioned in the eth2 spec: https://github.com/ethereum/eth2.0-specs/blob/dev/configs/mainnet/phase0.yaml#L54-L55
