### ISSUE TITLE
Where to rename "ether" cryptocurrency

### ISSUE THREAD

**Issue by yehia67** [ethereum/go-ethereum#22042]
Hey,
I am trying to run ethereum codebase and change the cryptocurrency used from "ether" to anything else. I just want to rename the ether but I can't find where to do that from the documentation. Can you please tell me where to rename the ETH cryptocurrency? which module to modify? would I face some issues because of the imported contracts?

**Comment by ligi** [comment]
Why would you want to do this?

**Comment by yehia67** [comment]
Its a research task.

**Comment by developerfred** [comment]
@yehia67 Assemble your Blockchain and put the name you want.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
