### ISSUE TITLE
Synchronisation failed: no peers to keep download active - will this resolve?

### ISSUE THREAD

**Issue by thebashfeed** [ethereum/go-ethereum#2204]
I read another, closed thread with a similar issue, but it did not solve my problem.  Forgive me for my ignorance but I'm pretty new to how this works.

I'm trying to run the synchronisation program (geth --rpc) in the cmd console. It was working fine up until about #820919, at which point it gave me the following error message:

Synchronisation failed: no peers to keep download active

![uvtunvf](https://cloud.githubusercontent.com/assets/17187115/12993752/0353d02c-d0d1-11e5-9275-e26eb9192b9e.png)

Will it resolve itself, or do I have to start the whole process over again? I've been running it all day so I'm hoping there's a simple fix for this issue...

**Comment by karalabe** [comment]
Yes, it will resolve itself.
You can also restart it, it will continue where it left off.
You could have used `--fast` option, which finishes in 20 minutes :P

**Comment by MaxXor** [comment]
Same issue for me. After about 30-40mins syncing the blockchain the same error apppears and I'll need to restart geth.

**Comment by Bubleek** [comment]
Same issue for me too! I think this is a bug, but i don't know where this bug(in windows, in internet connection or in geth or somewhere). I'm put new issue in mist folder, but @frozeman close it and recomend put it issue here.
https://github.com/ethereum/mist/issues/171

**Comment by MaxXor** [comment]
I had to restart geth now over 100 times to finish the synchronization... now it's working flawlessly when a newly generated block is imported.

**Comment by thebashfeed** [comment]
Yes, it resolved after restarting a couple of times. Once it fully syncs it has zero issues. Now I just need to upgrade my GPU and I'll be good to go!

Thanks for the responses everyone.

**Comment by fjl** [comment]
This should be resolved as of geth 1.3.5.

**Comment by hnaparst** [comment]
I have this problem with 1.3.5

**Comment by canadaduane** [comment]
I'm seeing this on 1.3.5 as well. Possibly related: the last time I tried to quit geth, it stalled for a long time (10 min?) and then ended with a "panic". I'm wondering if my db is corrupt as a result, and possibly related to this issue.

**Comment by canadaduane** [comment]
Turns out my clock was off by about 60 seconds.

**Comment by jamesmorgan** [comment]
I've just reset my clock (Mac OSX) and it kicking back into full spead, flying through now. 👍

**Comment by srw** [comment]
@jamesmorgan @canadaduane good catch! my clock was only off by ~20 seconds and the problem arised too.

**Comment by gorilla2112** [comment]
Im getting both 'no peers' error AND 'Synchronisation failed: leveldb/table: corruption on data-block (pos=0): checksum mismatch, want=0x8f40a97e got=0x792b89e6 [file=4762443.ldb]'

Cant get it to sync for anything. Thoughts?

**Comment by obscuren** [comment]
Table corruption occurs when there are partial writes due to sudden shutdowns. Could that be the case? Have you had a sudden shutdown prior to getting this message?

**Comment by lklancir** [comment]
I'm also getting this "no peers" error on the --fast mode. It imports like 3-5k transactions and then it snaps? Could it really be that the network is overloaded due to DAO hype?

**Comment by blocksonic** [comment]
Happens constantly for me (in Brazil). Maybe a lack of peers nearby?  It's annoying as hell. Even with --fast option I've been trying to sync for two days.  It's completely unusable for me.  I'm running the latest (Beta) geth as of now.

**Comment by holgerkpedersen** [comment]
There's a LOCK file in the chaindata that might be deleted to get the autosynch going again. But, I'm not sure what consequences it can have in other situations. But, I suspect it has something to do with timing of writing to the file and the progress of the import of blocks

**Comment by sheeeev66** [comment]
> Yes, it will resolve itself.
> You can also restart it, it will continue where it left off.
> You could have used `--fast` option, which finishes in 20 minutes :P (only allowed on an empty database)

I am running the `--fast` option, but still it has been running for about 5 hours and it still didn't finish. + the "pending" is only going up:

```
INFO [01-31|17:23:19.822] Imported new state entries               count=1152 elapsed=11.959ms  processed=35544583 pending=33984  trieretry=0    coderetry=0 duplicate=4685 unexpected=18835
INFO [01-31|17:23:20.475] Imported new state entries               count=0    elapsed=7.915ms   processed=35544583 pending=36006  trieretry=0    coderetry=0 duplicate=4817 unexpected=18889
INFO [01-31|17:23:20.488] Imported new state entries               count=966  elapsed=2.999ms   processed=35545549 pending=36006  trieretry=0    coderetry=0 duplicate=4817 unexpected=18889
INFO [01-31|17:23:20.515] Imported new state entries               count=0    elapsed=9.966ms   processed=35545549 pending=37041  trieretry=0    coderetry=0 duplicate=4956 unexpected=18946
```


is there any way I can fix it? I executed with this command:
`geth --rcp --etherbase <wallet address> --syncmode=fast --cache=2048`

you said it takes about 20 minutes so am I doing anything wrong?
I followed the tutorial from https://geth.ethereum.org/docs/interface/mining

**Comment by holiman** [comment]
Hah, the quote from @karalabe is five years old!Those 20 minutes are now more like "a day or two"
