### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by anuragsodhi** [ethereum/go-ethereum#22055]
Hi I am running Linux 20.04 on Ryzen 5 4650 with 32 GB ram

I am running Geth 1.9.25 with max peers =64 and cache = 4096

My Ram usage keeps on increasing, earlier this week it was 8GB and then it increased to 9 and now today it is sitting at 11GB. All 12 cores of Cpu also spike to 100% every ~25 seconds.

**Comment by ligi** [comment]
Regarding the RAM: does not seem to be a leak but it seems to be normal behavior
Regarding the CPU: is it 100% on all cores?
Can you provide all CLI parameters?

**Comment by holiman** [comment]
1. The go garbage collector doesn't immediately return the allocated memory to the OS, it just signals that if the OS should need it, it can be returned. 
2. A cache of `4Gb` means that geth will actively make use of 4G, it doesn't constrain geth to not use more in case there is more available.

**Comment by karalabe** [comment]
Go's GC is also a bit sucky in that it will use more RAM and run the GC sweep when too much accumulates. This can lead to a 2x overhead easily. If this is really bothersome for you, there are so GC config flags to play with, but it would be a perf hit.

**Comment by anuragsodhi** [comment]
> Regarding the RAM: does not seem to be a leak but it seems to be normal behavior
> Regarding the CPU: is it 100% on all cores?
> Can you provide all CLI parameters?

Yes it is 100% on all cores. 
![Screenshot from 2021-01-12 20-55-20](https://user-images.githubusercontent.com/6956109/104396391-8ee6d280-5518-11eb-8b19-acb04174730b.png)

**Comment by ligi** [comment]
Can you provide all CLI parameters?

**Comment by anuragsodhi** [comment]
Can you provide all CLI parameters? how to provide these? 
It starts normal when i start geth, then over time when full peers are synced, it starts spiking every 20-30 seconds

**Comment by holiman** [comment]
> how to provide these?

CLI parameters: the Command Line Interface parameters. That is: he was asking what the exact the command was that you used for starting the node. 

Spiking every 20-30 seconds is not exceptional or indicative of an error. Closing this
