### ISSUE TITLE
It is not possible to send a transaction through the ledger

### ISSUE THREAD

**Issue by maxttor** [ethereum/go-ethereum#22051]
#### System information

Geth version: 1.9.20-stable-979fc968
OS & Version: Windows

**I am trying to send tx via ledger:**
eth.sendTransaction({from:eth.accounts[1], to:eth.accounts[1], value:0})

**get error:**
Error: Ledger v1.6.2 doesn't support signing this transaction, please update to v1.0.3 at least
        at web3.js:6347:37(47)
        at web3.js:5081:62(37)
        at <eval>:1:20(16)

**Comment by holiman** [comment]
Fixed as of `1.9.24` in https://github.com/ethereum/go-ethereum/pull/21733
