### ISSUE TITLE
A large number of concurrent RPC requests resulted in excessively long response times

### ISSUE THREAD

**Issue by tyrone98** [ethereum/go-ethereum#22063]
#### System information

Geth version: 1.9.25
OS & Version: Linux
Commit hash : 

#### Expected behaviour
In response to a large number of concurrent JSONRPC requests, results can be returned in less than 200ms

#### Actual behaviour
Our machine is 4c16g, use geth --cache 4000 ....  and when the number of concurrent requests is greater than 200, 5% of the requests will fail due to a timeout.
using "go pprof" that present 80% time spent for runtime.scanobject()。

#### Backtrace

````
[backtrace]
````

**Comment by MariusVanDerWijden** [comment]
Can you add the svg of the pprof trace? We are aware that there are some problems with RPC since all requests are scheduled regardless of whether we have enough resources available
