### ISSUE TITLE
Depreciation of GitHub Wiki Pages

### ISSUE THREAD

**Issue by suriyaa** [ethereum/go-ethereum#22065]
As part of an ongoing effort to update and overhaul the Ethereum wiki to make it more useful to the community, the wiki pages has been moved to eth.wiki and the Geth documentation site.

*(This issue thread is used to link to pull requests for reference.)*

**Comment by suriyaa** [comment]
@holiman @karalabe @ligi @rjl493456442 WIP completed. ✅ PRs can now be merged. :shipit:

**Comment by ligi** [comment]
thanks - those look really good - please give some time to merge them

**Comment by ligi** [comment]
As far as I see the PRs are merged - so this can be closed?
