### ISSUE TITLE
Rinkeby Faucet: No Ethereum address found to fund

### ISSUE THREAD

**Issue by wsavas** [ethereum/go-ethereum#22072]
this is the tweet that clearly contains an ethereum address: https://twitter.com/wsavas/status/1342294056794284035
<img width="1280" alt="Screen Shot 2020-12-24 at 9 34 14 PM" src="https://user-images.githubusercontent.com/76575967/103115271-f4d5ed80-462f-11eb-8762-2b8d3eb2adab.png">
guess there is something wrong with the twitter connection still.

**Comment by Holt666** [comment]
yes, same issue! 0xcfdA510402D31420ED3518E16C5d8DbB1c120C4c,send me 15eth please.

**Comment by maihefande** [comment]
same issue. I tried the url https://twitter.com/bobalice12/status/1342786068811108352 and failed.

**Comment by trevistra** [comment]
same issue here! please I need some eth on 0xC7fEB286C61734b24C9D850dC54371908f6c4406

**Comment by ysknsn** [comment]
same issue

**Comment by ligi** [comment]
@Holt666 you have 15rETH now
@maihefande the address in the tweet is not correct
@trevistra send you rETH
 @ysknsn please provide your address

**Comment by maihefande** [comment]
@ligi 0xAcfadD9eD331500610cEb5ebcca57DCC2d2eFCB6 thanks much

**Comment by ysknsn** [comment]
@ligi
Thank you, This is my Rinkeby address.
0x8D863d7B790d9d8ac0c77f0fC7a1B252895E7ECD

**Comment by wsavas** [comment]
> @Holt666 you have 15rETH now
> @maihefande the address in the tweet is not correct
> @trevistra send you rETH
> @ysknsn please provide your address

@ligi 
My ETH is address is 0x80cEc71a1c4Eb3079Ae1d06E092Bf83463955997
Been trying to request 15 ETH, please help

**Comment by ligi** [comment]
@wsavas done

**Comment by Soren74** [comment]
I'm having the same issue as everyone - please send 15 ETH to:  0x5AB8CB9476B10d100D0484Da732dfA5FCC2043Df

thanks!

**Comment by ligi** [comment]
@Soren74 done

**Comment by JaiK-bc** [comment]
Hi @ligi is there anyway I could get 15 ETH sent to this address as well: 0x5bD5D07F015172E0dFf187B04ebeEfa7146B0958

I am trying to learn how to develop dapps but cannot move on without some ETH and I couldn't figure out the Rinkeby Faucet issue for the life of me. Thanks in advance!

**Comment by rayzor813** [comment]
I have the same issue.... Please send ETH 0x32D91091E19f797Ec1F89db91a22f569eE47b388
@ligi I noticed you've been helping people, i'd appreciate it alot!

**Comment by ligi** [comment]
@JaiK-bc @rayzor813 done

**Comment by rayzor813** [comment]
Greatly appreciated! @ligi

**Comment by will3dev** [comment]
Hi I am running into the same issue. The Rinkeby Faucet is a fantastic tool. Is there anyway that I can have some assistance to fund the below account?

0x6b73B16c913A6491368831135EF957A463Cf8177

**Comment by ligi** [comment]
@will3dev sending done

**Comment by Stagflation** [comment]
having the same issue, please send 15 ETH to: 0x2f822F5c0B2f541A043e0Ac7d5f0A3451271a51e
cheers.

**Comment by ligi** [comment]
@Stagflation done

**Comment by WolveIT** [comment]
having the same issue 
address is: 0xF4fF64CaC8cB7d16d517798f36bDbf5aBeffA228

**Comment by vitormartinsc** [comment]
@ligi same issue here, can you please send  15 ETH to: 0x618d9B736BcA649E7bC34Aa22Be2D5A5566FB4BA 
Thanks

**Comment by oberkayb** [comment]
same problem 0x262bD6c492cB673Ca2aC9C078E14B605Fad7daC6 but I need more because my homework

**Comment by maihefande** [comment]
@ligi  can you send 15 ETH to 0xAcfadD9eD331500610cEb5ebcca57DCC2d2eFCB6
thanks a lot!

**Comment by Holt666** [comment]
> @Holt666 you have 15rETH now
> @maihefande the address in the tweet is not correct
> @trevistra send you rETH
> @ysknsn please provide your address

thanks!:)

**Comment by s-naveen** [comment]
0x5327C91DAc34008B33f67b0AEF66a3f6Ef61f127
send 15 ETH to here please

**Comment by ligi** [comment]
@s-naveen done

**Comment by ysknsn** [comment]
@ligi 
can you please send 15 ETH to
0x8D863d7B790d9d8ac0c77f0fC7a1B252895E7ECD

**Comment by jcortejoso** [comment]
When rinkeby is up again (seems stalled for the last 30 minutes), can I have 15 rinkeby ETH to 0x480b0e0A641AE45521377d4984d085a003934561?
Thanks a lot @ligi

**Comment by oberkayb** [comment]
same problem, need 20 or more 0x262bD6c492cB673Ca2aC9C078E14B605Fad7daC6 because my homework

**Comment by oliverxie2020** [comment]
@ligi thanks for helping us, would you please send me 15 ETH to Rinkeby testnet ETH? my address is: 0xF24E87303210047E72c68d99f33E152e0b3d2cCc

**Comment by WolveIT** [comment]
@ligi we would really appreciate eth to our address on rinkeby testnet address is: 0xF4fF64CaC8cB7d16d517798f36bDbf5aBeffA228

**Comment by jcortejoso** [comment]
It does not work yet. Facebook posts also throw the same error.

**Comment by hjmoon83** [comment]
@ligi same problem occurs here as well. Neither Twitter nor Facebook works. (Keeps happening for the past few days) 
Could you kindly send 30 or more to my Rinkeby wallet? 0x50FB0557eA3fB5c5ee5588f1A30c3B2A292739Ed

**Comment by sonish777** [comment]
@ligi hi there, could you please send some ether (rinkeby test network) for me too. Thank you very much!!!!

**Comment by amir92io** [comment]
Same issue.
I would be glad if someone can send me some ether at:
0x1C6A93D195842305d78F6B890e8283220Da0C97B

**Comment by monkeyden** [comment]
Could use some as well.  Thanks.
0x253641e1970cEcB61FDaa8608718370765CAb905

**Comment by makerzy** [comment]
Hi @ligi, please send 18.75 ETH to address 0xbd7a862eBCc528002cC77786643A97D43f8ec948
Thank you!

**Comment by soulremover** [comment]
0xCB3b1e1BBECeC51dfeAca6B2E935171Dd75c28fF
Can you please add me some ETH for testing purposes ?
Thanks a lot in advance

**Comment by monkeyden** [comment]
An alternative, if you don't already have too much running on Rinkeby, is to use Ropsten.  This faucet worked for me this morning.
[https://faucet.dimensions.network/](https://faucet.dimensions.network/)

**Comment by okuma10** [comment]
Following a tutorial and the faucet does not work.
0xB4F49a489519b3ADee909dA0F5323b915fF47Dc9

**Comment by ganmaf** [comment]
0xB4F49a489519b3ADee909dA0F5323b915fF47Dc9

**Comment by helderribeirosousa** [comment]
Hello, I'm giving a class on Ethereum Dapps in a few days and I need some ether to transfer into the students' accounts so they can try some smart-contracts on the Rinkeby Test network.

Since the faucet is not working, could someone please transfer 10ETH to 0x0Ffa0373899e678D54811569E1D1D7beBa30efEC?

**Comment by testacc-a11y** [comment]
Can you please send 18.75 ETH to 0xe1783E2BF6e49fEB6e6C433B8c3295A0DC278eD9? Thanks in advance.

**Comment by bnestars** [comment]
Could you pleas send 15 ETH to 0xAe57603429faF930887122AdB87378a42067B373 ? Thanks.

**Comment by Kantitad** [comment]
2564-01-02 6:38 GMT+07:00, bnestars <notifications@github.com>:

**Comment by monkeyden** [comment]
> Rinkeby

Just noticed I received 5ETH 16hrs ago.  Back to dev and testing.  Thank you to whomever is responsible.

**Comment by masoodamodak** [comment]
Hi @ligi, please send 15 ETH to address 0xdf2Cd225177E96C3426F761146ab2FC7EF1966Cf
Thank you!

**Comment by karalabe** [comment]
This was fixed yesterday. Twitter discontinued their old site so we needed to swap the auth workflow.

**Comment by BulanAB** [comment]
Please send eth 0xF383A484CaF6d832bF1f9448c8D536ef5FFC2688 ....Thank you

**Comment by yuhang-eng** [comment]
Hi @ligi, i want about 12ETH and this is my address, 0x406D617814ac1af1f38980038Ab203528Dec596B  Thanks a lot !

**Comment by kurickabides** [comment]
I am taking a class and can not get any coins please help
https://www.facebook.com/kurick.dumuzi/posts/10227021294584144

0x436c733ba82469e15F3B85d28Aa56a94f7fD0A38

**Comment by heatif1992** [comment]
please help: 0xa4737d439C11Cab43A2A3DcbD5B54871Ef14d4B6

**Comment by kurickabides** [comment]
I switched to using this faucet 
https://faucet.goerli.mudit.blog/
It worked so I am testing on this network instead

**Comment by koslib** [comment]
Having the same issue at the moment with facebook. Yes the post is public.

**Comment by kemalcleva** [comment]
It doesn't work for me too . please send me 15 ETH 0xc102a9BCe7c3E2CB11e8AAFdB462308a566305D6  Thanks a lot !

**Comment by DavLiendoProgramming** [comment]
Having the same problem, please send me ETH to perform developing test, I would appreciate it.
Address: 0x7507c81147Dc2347B159c21d45fAe05e1A06a106
My post was: https://www.facebook.com/David.Liendo/posts/10225735263512114

**Comment by AllenZhang1984** [comment]
@ligi
can you please send 15 ETH to
0x26786995E1Ba7d3c7836406713B4C63c1E97DD04
That would really help thx

**Comment by wilkenswilco** [comment]
Also having this problem unfortunately,
15 ETH would be greatly appreciated

0x70072B05035AEc94177AF4bC146c5491Ce7476D0

**Comment by InvokerMaster** [comment]
@ligi 
Can you please send 15 Eth to 0x10ec5e46CCC0E01471d7BfCFD98BdA89a269d541
Have submitted using facebook post https://www.facebook.com/odin.zhu.9/posts/277843890738723 
but it didn't work
Thank you in advance

**Comment by rrithick116** [comment]
facing the same issue :

please provide with 15 eth 👍 

0x4B0aF22bd6B9833Edb84489DFf0B3fDF902cc34D

**Comment by ligi** [comment]
Please make sure your posts are public. Me playing manual faucet does not scale - just did that while there was a real problem with the faucet. But currently it seems to work - just drained some from it. It is just important that your posts are public and the faucet can actually read it.

**Comment by InvokerMaster** [comment]
Well my post is public. You can check this https://www.facebook.com/odin.zhu.9/posts/277843890738723
Can you please help me with this? I am urgently needs some Rinkeby Eth for running test and this is blocker to me. Thank you @ligi

**Comment by ligi** [comment]
When I click on that link I see no post (having no fb account like the faucet)

**Comment by karalabe** [comment]
@InvokerMaster Your post is not public. I can't see it.

**Comment by karalabe** [comment]
Work for me both Twitter and Facebook. Please fix your post and it will work. Locking this issue as there's no point for everyone to keep piling here because they don't bother to check the issue themselves.

**Comment by InvokerMaster** [comment]
Oh yeah it was not public and it worked. Thanks
