### ISSUE TITLE
Is there a way to make geth include a specific transaction in it's next block?

### ISSUE THREAD

**Issue by TennisBowling** [ethereum/go-ethereum#22078]
How would I make it so that geth is forced to include x transactions in the next block it mines?

**Comment by ligi** [comment]
What is your use-case?

**Comment by TennisBowling** [comment]
my use case is to mine trasactions while paying 0 gas fee. propagating isn't the concern, its forcing geth to mine it.

**Comment by karalabe** [comment]
Geth prioritizes local transactions. Local == submitted via the RPC or received from the network and recipient being in the `--txpool.locals` CLI flag (though you'll probable never get a 0 wei gas price tx propagated across the network). If you submit a tx to our miner directly with 0 gas price, it will pick it up before anything else.

**Comment by MariusVanDerWijden** [comment]
@TennisBowling this is not supported by geth. If you want to do that, you need to rewrite the transaction pool. We won't include such a change into geth as it leads to centralization. Being able to select specific transactions would enable the miner to censor other transactions, which should not be a feature in geth. If someone goes through the hoops of rewriting geth to do that, that's fine and nothing we can do about, but we will not add it as a feature.

**Comment by TennisBowling** [comment]
cool! thanks for everything.
