### ISSUE TITLE
pending transaction is not committed after mining a new block

### ISSUE THREAD

**Issue by machen382847508** [ethereum/go-ethereum#22073]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

```
eth.sendTransaction({from:eth.accounts[0],to:eth.accounts[1],value:web3.toWei(1,"ether")})
eth.pendingTransaction
return:
[{
    blockHash: null,
    blockNumber: null,
    from: "0x1d6114ba54a9003fb0528b2dcb727e108c196e31",
    gas: 21000,
    gasPrice: 1000000000,
    hash: "0xbc04dff35f0fcd0352529b3159735f1d496018377f09570e78a711b24618e4c1",
    input: "0x",
    nonce: 0,
    r: "0x802ae40163e88d4ab507fd518a39adcf6b30753761f7d4497372b748999bb599",
    s: "0x494afd223fa410cb0258ebf3601ca0113a3c72d8209591cd90f415d99bf35aa2",
    to: "0x90863de4f109bb12fa80abb49462d15c0a2a462e",
    transactionIndex: null,
    v: "0x50",
    value: 1000000000000000000
}]
```
After mining a new block, eth.pendingTransaction will be empty,and the balance of eth.accounts[1] is 1ether

#### Actual behaviour
After mining a new block, eth.pendingTransaction is not empty,and the balance of eth.accounts[1] is 0

#### Backtrace

````
[backtrace]
````

**Comment by MariusVanDerWijden** [comment]
Could you paste the arguments you used to start geth?

**Comment by machen382847508** [comment]
$GETH --mine --miner.threads=2 --datadir=$datadir \
  --identity="$dd" \
  --port=$port \
  --password=<(echo -n $dd) \
  --http --http.port=$httpport --http.corsdomain='*' \
  --http.api="eth,net,web3,personal,miner,admin" --allow-insecure-unlock

**Comment by ligi** [comment]
Do you start and stop the miner?

**Comment by holiman** [comment]
How fast is the mining happening? We don't immediately update the work-package on new transactions, because that would mean interrupting the workers all the time.
