### ISSUE TITLE
Unable to Deploy/Migrate to Mainnet via Truffle/Infura

### ISSUE THREAD

**Issue by flickmaking** [ethereum/go-ethereum#22082]
On 12/26/2020 I successfully compiled, migrated and tested on Ropsten via Truffle the following contract https://github.com/estudios-amazonia/FilmVault/blob/main/contracts/FVP_Token.sol. 
See Ropsten Contract Address: 0x82Bc5871e30FB2C00A3E5B5E6475A2baD88978ba

Today, 12/27/2020 I have been trying to deploy the same contract using the same truffle-config.js file on Mainnet and it gets frozen after compilying. I have used an array of gas / gasPrice combinations. The latest is as follows:

    mainnet: {
      networkCheckTimeout: 100000000,
      provider: function() {
        return new HDWalletProvider(maimnem, 'https://mainnet.infura.io/v3' + key);
    },
      network_id: 1,
      gas: 4000000,
      gasPrice: 65000000000, // 65Gwei

Therefore, I tried to use Remix, with GASLIMIT 350000 and VALUE 60 Gwei and it has failed twice. See the following Tx
https://etherscan.io/tx/0xdbdbe42e7f937f18952db19e94c6e6b42628f90241653f06d724999e278698e5
https://etherscan.io/tx/0x794243d66ba78ab9b349bb0a9abd38c3b2e6de55b396dd7a6b6a1f6258cff005

Would anyone be able to help me troubleshoot what is going on with this migration on Mainnet?

Greatly appreciated.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by flickmaking** [comment]
Thanks for your prompt response. I just posted the question on https://ethereum.stackexchange.com/questions/91597/unable-to-deploy-migrate-to-mainnet-via-truffle-infura

Cheers and all the best!
