### ISSUE TITLE
Fully Synced Archive Node on v1.9.25 - Missing Trie Node Errors on ETH Balance Calls, Yet Succeeds on Subsequent Attempts

### ISSUE THREAD

**Issue by ymonye** [ethereum/go-ethereum#22087]
#### System information

Geth version: v1.9.25-stable-e7872729
OS & Version: CentOS 7
Hardware: Dell PowerEdge R720, 128GB RAM, (8) Toshiba 1.92 TB SSDs in RAID-6
Commit hash : e7872729012a4871397307b12cc3f4772ffcbec6

#### Detail

Hi all. I have a few fully synced archive nodes for my company, running off Dell PowerEdge R720 servers with CentOS 7. Every now and then I receive a "missing trie node" error when attempting to retrieve ETH balance information from older blocks, then no error on subsequent attempts off the same ETH call.

I haven't any idea if this is hardware related as I have the same problem across multiple servers. Perhaps I'd need to explore the same version of Geth used by Infura, optimized for cloud infra? I'd love to trouble-shoot this sometime (or in Discord), as a RAID-6 configuration is the only way I can store an archive node from an economical standpoint. I've also played with various cache settings and still received the error on random balance calls, yet it seems everything else works fine as far as gathering historical ETH data.

Archive nodes were fully synced from scratch.

#### Steps to reproduce the behaviour
geth --syncmode=full --gcmode=archive

**Comment by holiman** [comment]
> then no error on subsequent attempts off the same ETH call.

Just to be clear: the _exact_ same call parameters?

**Comment by ymonye** [comment]
> > then no error on subsequent attempts off the same ETH call.
> 
> Just to be clear: the _exact_ same call parameters?

Hey Martin, this was resolved. I'm currently using a software (CentOS) RAID-6 setup, which heavily / negatively impacts overall performance versus a hardware RAID setup, which I plan to migrate to.
