### ISSUE TITLE
make: [geth] error 2

### ISSUE THREAD

**Issue by chyand** [ethereum/go-ethereum#2208]
I re-loaded Ubuntu 14.04 with multiple AMD graphics cards using proprietary drivers. I get a make geth error. Here is the complete load. It appears a reference is failing: github.com/Gustav-Simonsson/go-opencl/cl/usr/bin/ld: cannot find -lOpenCL I don't know where to look for the correct reference file. Any suggestions?

######:~/go-eth132/go-ethereum$ make geth
build/env.sh go install -v -ldflags '-X main.gitCommit=c541b38fb36587d23c60f5e2f2b9b3c8700ec489' -tags opencl ./cmd/geth
github.com/codegangsta/cli
github.com/Gustav-Simonsson/go-opencl/cl
github.com/ethereum/go-ethereum/rlp
github.com/ethereum/go-ethereum/crypto/ecies
github.com/ethereum/go-ethereum/crypto/sha3
github.com/pborman/uuid
golang.org/x/crypto/pbkdf2
golang.org/x/crypto/ripemd160
golang.org/x/crypto/scrypt
github.com/ethereum/go-ethereum/logger/glog
github.com/ethereum/go-ethereum/crypto/randentropy
github.com/ethereum/go-ethereum/params
github.com/ethereum/go-ethereum/crypto/secp256k1
github.com/hashicorp/golang-lru
github.com/rcrowley/go-metrics
github.com/syndtr/goleveldb/leveldb/util
github.com/syndtr/goleveldb/leveldb/comparer
github.com/syndtr/gosnappy/snappy
gopkg.in/karalabe/cookiejar.v2/collections/prque
github.com/ethereum/go-ethereum/event
gopkg.in/fatih/set.v0
github.com/ethereum/go-ethereum/common
github.com/syndtr/goleveldb/leveldb/cache
github.com/syndtr/goleveldb/leveldb/storage
github.com/syndtr/goleveldb/leveldb/filter
github.com/huin/goupnp/httpu
github.com/huin/goupnp/scpd
github.com/syndtr/goleveldb/leveldb/opt
github.com/huin/goupnp/soap
golang.org/x/net/html/atom
golang.org/x/net/html
github.com/huin/goupnp/ssdp
github.com/ethereum/go-ethereum/logger
golang.org/x/text/transform
github.com/syndtr/goleveldb/leveldb/errors
golang.org/x/text/encoding/internal/identifier
github.com/jackpal/go-nat-pmp
github.com/syndtr/goleveldb/leveldb/iterator
github.com/syndtr/goleveldb/leveldb/journal
github.com/ethereum/go-ethereum/event/filter
golang.org/x/text/encoding
github.com/robertkrimen/otto/file
github.com/robertkrimen/otto/token
github.com/syndtr/goleveldb/leveldb/memdb
github.com/syndtr/goleveldb/leveldb/table
golang.org/x/text/encoding/internal
golang.org/x/text/encoding/unicode
golang.org/x/text/encoding/charmap
golang.org/x/text/encoding/japanese
github.com/ethereum/go-ethereum/metrics
golang.org/x/text/encoding/korean
golang.org/x/text/encoding/simplifiedchinese
github.com/syndtr/goleveldb/leveldb
golang.org/x/text/encoding/traditionalchinese
github.com/robertkrimen/otto/ast
github.com/robertkrimen/otto/dbg
github.com/robertkrimen/otto/registry
github.com/ethereum/go-ethereum/rpc/shared
github.com/robertkrimen/otto/parser
github.com/rs/cors
# github.com/Gustav-Simonsson/go-opencl/cl
/usr/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status
github.com/peterh/liner
github.com/mattn/go-isatty
github.com/shiena/ansicolor
github.com/fatih/color
github.com/ethereum/go-ethereum/rpc/codec
github.com/mattn/go-runewidth
golang.org/x/net/html/charset
github.com/nsf/termbox-go
github.com/robertkrimen/otto
github.com/huin/goupnp
github.com/gizak/termui
github.com/ethereum/go-ethereum/ethdb
github.com/huin/goupnp/dcps/internetgateway1
github.com/huin/goupnp/dcps/internetgateway2
github.com/ethereum/go-ethereum/p2p/nat
github.com/ethereum/go-ethereum/crypto
github.com/ethereum/go-ethereum/jsre
github.com/ethereum/go-ethereum/core/vm
github.com/ethereum/go-ethereum/trie
github.com/ethereum/go-ethereum/accounts
github.com/ethereum/go-ethereum/common/compiler
github.com/ethereum/go-ethereum/common/httpclient
github.com/ethereum/go-ethereum/p2p/discover
github.com/ethereum/go-ethereum/common/registrar
github.com/ethereum/go-ethereum/rpc/useragent
github.com/ethereum/go-ethereum/rpc/comms
github.com/ethereum/go-ethereum/p2p
github.com/ethereum/go-ethereum/core/types
github.com/ethereum/go-ethereum/core/state
github.com/ethereum/go-ethereum/whisper
github.com/ethereum/go-ethereum/pow
github.com/ethereum/go-ethereum/eth/downloader
github.com/ethereum/go-ethereum/core
github.com/ethereum/go-ethereum/eth/fetcher
github.com/ethereum/go-ethereum/eth/filters
make: *** [geth] Error 2

**Comment by chyand** [comment]
I found a solution here: https://gist.github.com/mingderwang/31bc3d2e7a6ad6272ba7
which talks about downloading the AMD developers toolkit. That resolved the make error for my graphics cards. I am able to use all AMD cards now, however, there is a video problem when the mining begins. Perhaps reducing the allocation to 90% from 95% would give me a clear screen. I have also imported the blockchain from backup successfully. Thank you everyone for the resources! I used SkithUno's Spacience blog (http://spacience.blogspot.ae/2015/05/ethereum-gpu-mining-ubuntu-1404-lts.html) for installation guidance. Much easier to get started with go-ethereum using specific OS versions.

**Comment by karalabe** [comment]
GPU mining requires OpenCL libraries to be installed for your specific video card. That's a prerequisite and not something we could bundle up into our own source.

You can always ever use a graphics card for one purpose at a time: either display something, or have it crunch something. If the card is doing some OpenCL calculation, it cannot work on display, so you'll see your screen "freeze" until the calculation is done. If the calculation is a shorted burst repeated very frequently, then it might just seem "stuttery", but you get the picture where this issue comes from. A popular solution is to have an integrated graphics card power the display, and the dedicated one do OpenCL crunching.

Regarding the hashrate, I think it's a long standing issue though not one of particular importance since the miner itself should report its hashrate already, and you don't really have any useful way to programatically react to it. Lastly as the long term goal is proof-of-stake, mining in general has a little less priority (as long as it works properly of course, which currently it seems to do).

**Comment by karalabe** [comment]
I'll close this issue as being non related to geth (the compilation and video card stuttering issues that is). The hashrate is a known bug, so that's tracked elsewhere.

**Comment by chyand** [comment]
Sorry for the dev-less comments and lack of contribution... Thank you for
your time... I found the forums for these types of entries. I'll definitely
post a dev comment if I come up with something. Again, thank you.

On Mon, Feb 15, 2016 at 10:49 AM, Péter Szilágyi <notifications@github.com>
wrote:

> Closed #2208 <https://github.com/ethereum/go-ethereum/issues/2208>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/go-ethereum/issues/2208#event-551084982>.
>



-- 
Cheryl Anderson
