### ISSUE TITLE
Create a GUI to select directory of where one wants to store the ETH blockchain

### ISSUE THREAD

**Issue by jm9151821** [ethereum/go-ethereum#22085]
# Rationale
Given how complicated it is to download the whole ethereum blockchain to an external ssd, one could look at bitcoin core and how easy they have made it through a GUI to select where one wants to download the entire blockchain to.

Why should this feature exist?
There would be a whole lot more nodes in the world. I currently have the external ssd ready to go but GETH i not very GUI Friendly, its CLI intensive, nothing against CLI, it just makes it more complex for the average person

What are the use-cases?
Download ETH blockchain to external SSDs and probably have a lot more nodes around the world, thus increasing decentralization.

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

I can't I am not technical enough.

**Comment by ligi** [comment]
I do not think a GUI should be in the scope of geth

**Comment by jm9151821** [comment]
It would make things way easier for the average non command line speaking
person. i don't have hard data but this is most likely strongly preventing
it from their being more nodes in the world.

It sure is the reason why I could set up a bitcoin node in 2 days but I'm
having to give more time to setting up an eth node. I think I've figured it
out with some help from the Eth staker discord group. Until then, there
will be less nodes in the world until a solution comes about.

**Comment by ligi** [comment]
Not saying it should not exist - just saying IMHO it should not be part of this. Should be another app/repo that uses this. Something like Grid was going in the direction.

**Comment by jm9151821** [comment]
Okay,  I guess all I am trying to point out to, is that the bitcoin core
has a very simple GUI, why couldn't Geth?

Juan Mayen | IMBA
Class of 2018
The University of Memphis
University of Central Arkansas '15

**Comment by DGKSK8LIFE** [comment]
> the scope of geth

Agreed. geth is a command line client.

**Comment by MariusVanDerWijden** [comment]
I'm closing this issue, geth is supposed to be a cli client. Creating a gui to start geth (and set parameters and stuff) would be a great hackathon project. If someone wants to pick it up, I would be happy to help
