### ISSUE TITLE
Does swarm support IPv6 network？

### ISSUE THREAD

**Issue by HappyThis** [ethereum/go-ethereum#22081]
I started several swarm in several docker containers of the IPv4 server, and swarm can work. But when I use docker to deploy swarm in IPv6 server, swarm can't work。

1.create ipv6 network:
docker network create -d bridge --ipv6 --subnet "fd00:daad:beee:1::/64" FLChainNet
2.create docker container:
docker run --name=node1 --network FLChainNet --ip6="fd00:daad:beee:1::101" --hostname=node1 --rm -it node:v3
3.Starting swarm in docker：
swarm --bzzaccount 0x865932603FC99595775323476346b121dA8B65d7 --datadir /home/geth/data

**Comment by ligi** [comment]
please open here: https://github.com/ethersphere/swarm
