### ISSUE TITLE
eth_sendRawTransaction return already known

### ISSUE THREAD

**Issue by vae520283995** [ethereum/go-ethereum#22093]
#### System information

Geth version: `Geth/v1.9.23-stable-8c2f2715`
OS & Version: Linux
Commit hash : stable-8c2f2715

#### Expected behaviour
Broadcast normally returns txhash

#### Actual behaviour
return already known

#### Steps to reproduce the behaviour
Unable to reproduce, appeared once

#### Backtrace

````
[backtrace]
![image](https://user-images.githubusercontent.com/30487254/103393118-149f7100-4b5c-11eb-885a-1b98431fc03d.png)

````

**Comment by MariusVanDerWijden** [comment]
This error is returned if a transaction was already in the mempool. It has to be the exact same transaction, because it is compared by txHash. So there are two possibilities: you either submitted the same rawTransaction twice (maybe because there was a reorg right before it) or there's  a slight race and the rawTransaction was internally handled twice. Since it appeared only once and is not reproducible I would argue for the former, but we should keep our eyes open if more people have this problem

**Comment by vae520283995** [comment]
> This error is returned if a transaction was already in the mempool. It has to be the exact same transaction, because it is compared by txHash. So there are two possibilities: you either submitted the same rawTransaction twice (maybe because there was a reorg right before it) or there's a slight race and the rawTransaction was internally handled twice. Since it appeared only once and is not reproducible I would argue for the former, but we should keep our eyes open if more people have this problem

Thank you for your answer, I am sure I only broadcast once, and I only have this situation once, which cannot be reproduced

**Comment by ligi** [comment]
Which is the code that sends the transactions? Are you sure the bug is not in there that executed a tx twice?

**Comment by vae520283995** [comment]
> Which is the code that sends the transactions? Are you sure the bug is not in there that executed a tx twice?

Use web3j eth_sendRawTransaction,  Not executed twice

**Comment by holiman** [comment]
Signing a transaction (at least in geth) is deterministic, if you sign the same data twice, it becomes the exact (hash-wise) duplicate. 
So it's not necessarily that you submit the same signed data blob twice, it could be that whatever backend you used, produced the same (same nonce, same value same recipient etc) twice, and it resulted in the same blob twice. 
If you don't have any more info about how the pipeline looked which produced this transaction, there's not much we can do.

**Comment by vae520283995** [comment]
> Signing a transaction (at least in geth) is deterministic, if you sign the same data twice, it becomes the exact (hash-wise) duplicate.
> So it's not necessarily that you submit the same signed data blob twice, it could be that whatever backend you used, produced the same (same nonce, same value same recipient etc) twice, and it resulted in the same blob twice.
> If you don't have any more info about how the pipeline looked which produced this transaction, there's not much we can do.

Both create transaction and sign transaction use web3j, without calling geth, but I called eth_estimateGas before signing

**Comment by holiman** [comment]
> Both create transaction and sign transaction use web3j,

Web3j gets nonce information from somewhere. And some caller provides a value to send.  That's what I mean by the "pipeline which produced this transaction". How does that pipeline look.

**Comment by vae520283995** [comment]
> > Both create transaction and sign transaction use web3j,
> 
> Web3j gets nonce information from somewhere. And some caller provides a value to send. That's what I mean by the "pipeline which produced this transaction". How does that pipeline look.

web3j gets the nonce based on the address, eth_getTransactionCount
It has appeared several times in a row recently, I first try to update to the latest version

**Comment by vae520283995** [comment]
I updated the node to the latest version, but the problem still occurs
 Geth/v1.9.25-stable-e787272

Below is the log

WARN [01-12|09:54:23.497] Synchronisation failed, dropping peer    peer=aecb116c787b2dac err="action from bad peer ignored: header request timed out"
INFO [01-12|09:54:24.687] Deep froze chain segment                 blocks=9  elapsed=64.093ms  number=11549438     hash="3e9c32…b37c11"
INFO [01-12|09:54:28.340] Imported new chain segment               blocks=1  txs=207 mgas=12.496 elapsed=715.639ms mgasps=17.461  number=11639439     hash="332bae…3c1b8b" dirty=201.78MiB
INFO [01-12|09:54:30.907] Imported new chain segment               blocks=1  txs=175 mgas=12.484 elapsed=1.323s    mgasps=9.430   number=11639440     hash="c54b71…1f93f8" dirty=202.75MiB
INFO [01-12|09:54:37.597] Imported new chain segment               blocks=1  txs=261 mgas=12.482 elapsed=1.488s    mgasps=8.385   number=11639441     hash="5cc161…ecbe42" dirty=203.89MiB
INFO [01-12|09:54:50.394] Imported new chain segment               blocks=1  txs=219 mgas=12.492 elapsed=968.487ms mgasps=12.898  number=11639442     hash="e565f3…e0a128" dirty=205.16MiB
INFO [01-12|09:55:24.721] Deep froze chain segment                 blocks=4  elapsed=33.194ms  number=11549442     hash="da81b4…6e2456"
WARN [01-12|09:55:55.409] Unexpected transaction delivery          peer=aecb116c787b2dac
WARN [01-12|09:55:55.410] Unexpected transaction delivery          peer=49d1c40d6d552aac
INFO [01-12|09:56:05.833] Imported new chain segment               blocks=1  txs=229 mgas=12.501 elapsed=782.394ms mgasps=15.978  number=11639443     hash="5275ff…441913" age=1m16s dirty=206.30MiB
INFO [01-12|09:56:06.125] Submitted transaction                    fullhash=0xc441a97925485f01e436bf2cdf5a5f4c8a4ba4d2b2fecb424a54554a2d386e09 recipient=0xB4D51645A4466EBD87faefAc421b68523097baFB
WARN [01-12|09:56:06.133] Served eth_sendRawTransaction            conn=18.139.60.104:39374 reqid=eth_sendRawTransaction_id t="67.842µs"   err="already known"
INFO [01-12|09:56:15.659] Imported new chain segment               blocks=1  txs=250 mgas=12.507 elapsed=2.368s    mgasps=5.280   number=11639444     hash="10962b…408429" age=1m9s  dirty=207.74MiB
WARN [01-12|09:56:20.861] Checkpoint challenge timed out, dropping id=3379f0a23d69f23c conn=dyndial             addr=89.141.238.195:30303  type=Geth/v1.9.25-stable-...
INFO [01-12|09:56:24.756] Deep froze chain segment                 blocks=2  elapsed=34.892ms  number=11549444     hash="afbbfd…bab8b8"
INFO [01-12|09:56:29.052] Imported new chain segment               blocks=1  txs=169 mgas=12.523 elapsed=604.197ms mgasps=20.727  number=11639445     hash="4624ba…e49d6d" dirty=208.47MiB
INFO [01-12|09:56:29.685] Imported new chain segment               blocks=1  txs=231 mgas=12.346 elapsed=534.181ms mgasps=23.111  number=11639446     hash="8cb940…22a2b1" dirty=209.45MiB
WARN [01-12|09:56:37.801] Checkpoint challenge timed out, dropping id=182de2cfe29eaab5 conn=inbound             addr=47.242.46.63:55514    type=Geth/v1.9.23-stable-...
INFO [01-12|09:56:42.311] Imported new chain segment               blocks=1  txs=196 mgas=12.526 elapsed=1.267s    mgasps=9.886   number=11639447     hash="d16183…9953cc" age=1m6s  dirty=210.59MiB
INFO [01-12|09:56:45.331] Imported new chain segment               blocks=1  txs=173 mgas=12.540 elapsed=2.511s    mgasps=4.994   number=11639448     hash="b58014…9aec8f" dirty=211.09MiB
WARN [01-12|09:56:50.946] Checkpoint challenge timed out, dropping id=28ff98b27ea153cc conn=inbound             addr=90.145.247.162:51474  type=Geth/v1.9.11-stable-...
INFO [01-12|09:56:57.603] Imported new chain segment               blocks=1  txs=229 mgas=12.518 elapsed=580.130ms mgasps=21.577  number=11639449     hash="320f16…123455" age=1m4s  dirty=211.95MiB
WARN [01-12|09:56:57.863] Checkpoint challenge timed out, dropping id=39f9dc1f2159e119 conn=inbound             addr=184.145.60.30:52626   type=Geth/v1.9.26-unstabl...
INFO [01-12|09:57:04.244] Imported new chain segment               blocks=1  txs=195 mgas=12.507 elapsed=484.194ms mgasps=25.830  number=11639450     hash="8ec79d…ef4dcb" dirty=212.37MiB
INFO [01-12|09:57:05.949] Imported new chain segment               blocks=1  txs=568 mgas=12.510 elapsed=1.644s    mgasps=7.608   number=11639451     hash="3a79fc…72c25f" dirty=212.95MiB
WARN [01-12|09:57:12.185] Checkpoint challenge timed out, dropping id=46776dff2667d129 conn=inbound             addr=95.216.34.53:44942    type=OpenEthereum/v3.0.1-...
INFO [01-12|09:57:20.433] Imported new chain segment               blocks=1  txs=174 mgas=12.513 elapsed=591.962ms mgasps=21.138  number=11639452     hash="2facee…72ec1b" dirty=213.87MiB
INFO [01-12|09:57:21.404] Imported new chain segment               blocks=1  txs=153 mgas=12.527 elapsed=794.334ms mgasps=15.770  number=11639453     hash="48731c…276f95" dirty=214.86MiB
INFO [01-12|09:57:24.784] Deep froze chain segment                 blocks=9  elapsed=26.259ms  number=11549453     hash="e56425…ac40f6"
INFO [01-12|09:57:32.351] Submitted transaction                    fullhash=0x658cc27aee12e603831c3888180d5e2abe5068be3d494a7c050253d80dd841cf recipient=0xf775956E1E9d9ddc63104A52626fE1A607B5769B
INFO [01-12|09:57:32.374] Imported new chain segment               blocks=1  txs=215 mgas=12.524 elapsed=372.419ms mgasps=33.629  number=11639454     hash="841a9a…4fbcbb" dirty=216.12MiB
WARN [01-12|09:57:35.289] Checkpoint challenge timed out, dropping id=94b82260db33e63d conn=inbound             addr=15.236.39.217:57856   type=Geth/v1.9.22-unstabl...
INFO [01-12|09:57:36.089] Imported new chain segment               blocks=1  txs=154 mgas=12.519 elapsed=3.280s    mgasps=3.816   number=11639455     hash="736492…b8a412" dirty=217.42MiB
INFO [01-12|09:57:43.071] Imported new chain segment               blocks=1  txs=140 mgas=12.522 elapsed=2.215s    mgasps=5.653   number=11639456     hash="8721f3…d6e2b7" dirty=218.39MiB
INFO [01-12|09:57:43.840] Imported new chain segment               blocks=1  txs=203 mgas=12.529 elapsed=762.649ms mgasps=16.428  number=11639457     hash="69e796…546c10" dirty=218.92MiB

Two transactions were submitted in the log, but one of them returned already known

**Comment by holiman** [comment]
This is the transaction which is 'already known': https://etherscan.io/tx/0xc441a97925485f01e436bf2cdf5a5f4c8a4ba4d2b2fecb424a54554a2d386e09 . It was mined in block `11639449`. 
I can't see how that can possibly happen, unless you either have a second node which _also_ sends transactions with the same key, or double-send the transactions using `sendRaw`. 

If you use `getTransactionCount`, it returns the `canon` transaction count, IIRC, which does not take `pending` into account. So invoking it twice will give the same nonce, even if you submit a transaction inbetween. 
As opposed to if you send a transaction using `sendTransaction` but without specifying a nonce -- in that case it will check what the next nonce should be based on current state and the transactions floating around in `pending`.

**Comment by holiman** [comment]
> If you use getTransactionCount, it returns the canon transaction count, IIRC, which does not take pending into account. So invoking it twice will give the same nonce, even if you submit a transaction inbetween.

Since we haven't heard back, I'll assume that this indeed was/is the issue, and I'll close this. Feel free to get back to us if there's something still not clear.

**Comment by feizerl** [comment]
Hello,

I am getting this error as well. Here my alchemy screenshot:

<img width="1182" alt="Screenshot 2022-02-25 at 3 50 12 PM" src="https://user-images.githubusercontent.com/88751631/155800905-51715423-ee71-4b13-8e62-ccd96e981974.png">

I have checked the nonces, and am pretty sure the txn was not submitted twice. 

One interesting thing (in my case) is that I observed this on polygon. (which seems to have a significant number of reorgs: https://polygonscan.com/blocks_forked). I am wondering if that could be potentially a reason for this.

**Comment by MicahZoltu** [comment]
I think this behavior is incorrect and Geth should return the transaction hash.  Calling `eth_sendRawTransaction` is (should be) an idempotent operation and no matter how many times you call it, you should always get the same result.  If the dapp actually wants to know if the transaction already exists, they can query for it.

Generally speaking, idempotency in API design improves robustness because it allows application authors to do "at least once" without having to worry about hitting unexpected code paths, rather than "at most once" ("exactly once" being impossible across failure domains of course).

**Comment by holiman** [comment]
>  Calling eth_sendRawTransaction is (should be) an idempotent operation and no matter how many times you call it, you should always get the same result.

That sounds odd to me. Typical things that can happen: 
- The tx is rejected outright, due to too low basefee. Ten minutes later it would have been fine
- The tx is rejected, because the nonce is already passed. Might, or might not, be because this exact tx was already included in a block

So what  you're saying is that in these cases, the node should just squelch the error message and return the transaction hash? I don't see how that makes the UX any better.

**Comment by MicahZoltu** [comment]
Ah, I just reread the quoted part of my comment and I see the confusion.  I think this should be idempotent when a write happens, in the sense that if you do two writes of the same data to a database they will both succeed (even though the second was redundant).  You are correct, this call isn't idempotent if the transaction is rejected for any reason, and calling again after receiving a rejection may give a different result.  If the transaction is in a block already or in the mempool though, you should get a success result (transaction hash) no matter how many times you execute the call.

**Comment by holiman** [comment]
> If the transaction is in a block already [...] , you should get a success

So, if a node receives a tx, it will check the nonce of that tx pretty early. It will see that the nonce is _old_, and the tx is rejected. In order to figure out that this exact tx was already included in a block, it would have to do a lookup in the `txhash->block number` index (if such exist). And it would still be pretty quirky behaviour, basically

> If the nonce is too low, we return an error. Except if this exact tx was already included in a block somewhere between now and genesis, in which case we return the tx hash instead (best effort: assuming we can locate it in our index)

**Comment by holiman** [comment]
>  This is not an error state, it is a success state because the intent of the caller was to get a transaction into the mempool and that is a success 

I do kind of agree with this statement though.

 ... In theory, theory and practice is the same thing...

**Comment by MicahZoltu** [comment]
While I wouldn't be ecstatic about it, I would accept at least returning the transaction hash in the `AlreadyKnown` case.  In this scenario you presumably have identified the presence of that transaction in the mempool so no additional work would be required, and you can simply choose to send back success instead of failure.

Separately, for the scenario you mentioned it *feels* to me like doing the lookup you described would be the right course of action here.  Is the concern that this would turn a lightweight call into a heavyweight one in some scenarios, or that it adds significant complexity to what is currently a simple codepath?
