### ISSUE TITLE
Newline separator in IPC call response

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/go-ethereum#2209]
Hey all,

This is either a question or a bug report. It is not clear to me if there should be a line separator between responses to IPC calls or not.

If there is, then web3.js should also include a behaviour like I include in [this](https://github.com/ethereum/web3.js/pull/387) PR in order to properly dechunk the responses.

If not then, the latest version of Geth seems to be mistakenly adding a newline to each different response via IPC as can be seen in the example below:
![2016-02-12-184255_1545x93_scrot](https://cloud.githubusercontent.com/assets/1658405/13015444/5e1a5484-d1b9-11e5-9a70-3e6e4e408c33.png)

```sh
socat - UNIX-CONNECT:/home/lefteris/.ethereum/geth.ipc 
{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}
{"jsonrpc":"2.0","id":83,"result":"0xf29e2"}
{"jsonrpc":"2.0","id":83,"result":"0xf29e2"}
{"jsonrpc":"2.0","id":83,"result":"0xf29e2"}
{"jsonrpc":"2.0","id":83,"result":"0xf29e2"}
```

**Comment by LefterisJP** [comment]
by request of @frozeman I am pinging @bas-vk for this issue :)

**Comment by bas-vk** [comment]
Afaik there is no convention if the newline should be included or not. The new RPC implementation uses the go json de/encoder which prefixes a newline before each message. According to a [comment](https://golang.org/src/encoding/json/stream.go?s=4283:4330#L193) just for easy of debugging. 

Changing this is fairly simple but I would recommend making the dechunker in web3 a bit more robust that it will skip whitespace characters between messages. If web3 is used with a different implementation it might be affected again.

**Comment by bas-vk** [comment]
Afaik there is no convention if the newline should be included or not. The new RPC implementation uses the go json de/encoder which prefixes a newline before each message. According to a [comment](https://golang.org/src/encoding/json/stream.go?s=4283:4330#L193) just for easy of debugging. 

Changing this is fairly simple but I would recommend making the dechunker in web3 a bit more robust that it will skip whitespace characters between messages. If web3 is used with a different implementation it might be affected again.

**Comment by LefterisJP** [comment]
Sure that can be done.

**Comment by karalabe** [comment]
I think the important part behind the space is:

> [...] and some kind of space is required if the encoded value was a number, so that the reader knows there aren't more digits coming.

**Comment by frozeman** [comment]
I improved the dechunker in web3.js, mist had it already improved :)
I guess @LefterisJP youre the first one to use the web3.js ipcprovider..

**Comment by LefterisJP** [comment]
@frozeman that's disturbing :santa:
