### ISSUE TITLE
Add an option to disable locking so that it can be used as a deployment i k8s

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#22097]
## Why should this feature exist?
To allow using geth in kubernetes
In k8s a deployment rollout creates a second container before deleting the original one so with the file locking this is no possible as the second container can't start. I know that allowing more then a single app to write to the same data folder is dangerous and might lead to corruptions, but with k8s that is the only way AFAIC

## What are the use-cases?
HA

## Implementation

Are you willing to implement this feature?
YES

**Comment by raohammad** [comment]
I am running geth based full node in K8s without problems. Probably I
didn't have that scenario yet? What can I do to create failure scenario?

Thanks,

**Comment by MariusVanDerWijden** [comment]
Disabling the locking for the data directory can be dangerous. It would mean that two different processes would be able to write and change files that are currently in use by the other process. I don't think it would be possible to allow this with the way geth uses the datadir. There are some tutorials that use geth inside kubernetes without a problem e.g. https://messari.io/article/running-an-ethereum-node-on-kubernetes-is-easy

**Comment by krasi-georgiev** [comment]
Thanks, for the link my manifests are almost identical. The problem is when do rolling updates.
For example if you change anything in the manifest file and do 
```
kubectl apply -f deploy.yml
```
What happens in the background is that k8s will schedule a new pod with the same data directory but because of the LOCK file this new pod can't start so k8s will never delete the old one.

Like I said I understand it is dangerous, but don't think there is another way in k8s to set it up so that is deletes the old pod first and only then to create the new one.
https://github.com/tellor-io/eth-node

Strange thing is that I tried it again just now and it seems that this time it managed to do a complete rolling update without any issues.

closing and will re-open if needed with more details.
