### ISSUE TITLE
Deploying to Simulated backend with bytecode from etherscan results in error: `execution reverted`

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#22098]
#### System information

Geth version: 0a3993c55861
OS & Version: Linux

abigen : 0a3993c55861

Trying to run some tests against this contract https://etherscan.io/address/0xf7914ebf0f021adaf95114b068502d0c7d107bc9#code

I downloaded the bytecode `608060405234801.....` and the abi `[{"constant":false,"inputs":[{"in....`
generated the binding using
```
abigen --bin=.local/mainByte --abi=.local/mainAbi.json --solc=/tmp/bin/solc --pkg=tellorNew --type=Tellor --out=pkg/contracts/tellorNew/tellor.go
```

and when trying to deploy with the code below getting the error for a reverted transaction
```
	key, err := crypto.GenerateKey()
	testutil.Ok(t, err)
	auth, err := bind.NewKeyedTransactorWithChainID(key, big.NewInt(1337))
	testutil.Ok(t, err)

	sim := backends.NewSimulatedBackend(core.GenesisAlloc{auth.From: {Balance: big.NewInt(math.MaxInt64)}}, math.MaxInt64)

	address, tx1, _, err := tellorNew.DeployTellor(auth, sim)
	testutil.Ok(t, err)
```

**Comment by MariusVanDerWijden** [comment]
I tried to replicate by generating the binding directly from the solidity which works fine.
Just copied the sol from https://etherscan.io/address/0xf7914ebf0f021adaf95114b068502d0c7d107bc9#code (copy source code to clipboard) into a file and called abigen as follows: `abigen --pkg geth --sol contract.sol --out contract.go --solc ./solc-static-linux-5-16` I then ran both your and deployment code and my own, both of which worked fine. So the problem is not in the deployment code but in the way you generated the binding. Will try your method of generating the abi next

```go
func TestTellor(t *testing.T) {
	backend, sk := getSimBackend()
	transactor := bind.NewKeyedTransactor(sk)
	_, tx, tellor, err := DeployTellor(transactor, backend)
	if err != nil {
		t.Fail()
	}
	backend.Commit()
	ctx, _ := context.WithDeadline(context.Background(), time.Now().Add(5*time.Second))
	addr, err := bind.WaitDeployed(ctx, backend, tx)
	if err != nil {
		t.Error(err)
	}
	_ = addr
	_ = tellor
}

func TestGivenTellor(t *testing.T) {
	key, err := crypto.GenerateKey()
	auth := bind.NewKeyedTransactor(key)

	sim := backends.NewSimulatedBackend(core.GenesisAlloc{auth.From: {Balance: big.NewInt(math.MaxInt64)}}, math.MaxInt64)

	address, tx, _, err := DeployTellor(auth, sim)
	if err != nil {
		t.Error(err)
	}
	sim.Commit()
	ctx, _ := context.WithDeadline(context.Background(), time.Now().Add(5*time.Second))
	addr, err := bind.WaitDeployed(ctx, sim, tx)
	if err != nil {
		t.Error(err)
	}
	_ = addr
	_ = address
}
```

**Comment by MariusVanDerWijden** [comment]
Hmm no, it works for me even with the way you build your binding...
```
abigen --bin=contract_bytecode --abi=contract_abi.json --solc=./solc-static-linux-5-16 --pkg=geth --type=Tellor --out=contract.go 
```

**Comment by MariusVanDerWijden** [comment]
My repro code is here btw: https://github.com/MariusVanDerWijden/go-snippets/tree/master/contract_repro

**Comment by krasi-georgiev** [comment]
Thanks, I will look into it shortly.

**Comment by krasi-georgiev** [comment]
So strange now it also worked for me as well. Thanks for the support, I hope the examples help someone else as well.
