### ISSUE TITLE
limit number of inbound syncing peers

### ISSUE THREAD

**Issue by Code0x2** [ethereum/go-ethereum#22101]
Geth should have a feature (i.e. cli flag) that will restrict the amount of inbound syncing peers that the node will serve data to. This should be an option to effectively be able to connect to lots of peers on Geth, but reducing network out bandwidth. Useful if the node is hosted on a hosting provider (such as AWS) that charges additional funds for outbound data.

**Comment by MariusVanDerWijden** [comment]
You can limit the number of syncing peers by limiting the number of max peers (using the `--maxPeers` flag)
I think implementing such a feature would severely weaken the network since it creates the incentive to never allow anyone to sync off of your node.

**Comment by Code0x2** [comment]
> You can limit the number of syncing peers by limiting the number of max peers (using the `--maxPeers` flag)
> I think implementing such a feature would severely weaken the network since it creates the incentive to never allow anyone to sync off of your node.

This will limit the number of synced peers that the node is connected to, which might work. Ill give it a try and check my data transfer costs after and see if they get reduced.
