### ISSUE TITLE
How to sync block quickly and full history state trie?

### ISSUE THREAD

**Issue by lxex** [ethereum/go-ethereum#22117]
**System information**
Geth version: Geth/v1.9.26
OS & Version:
windows 10 pro

I used the following command, but  slower than mainnet producted!

**geth  --syncmode=full --gcmode=archive --cache=1024 --verbosity=2**

**Comment by holiman** [comment]
Well, that looks correct, if you want the full archive state of every single block ever produced. You better have good hardware; fast IO and huge disks. 

You lowered the `--cache`, bumping it up should improve things a bit. 

In my experience, a lot of people who thinks they want a full archive node would actually only need a `syncmode=fast gcmode=archive`, but of course that depends on your usecase. 

Also, if you indeed import blocks at slower than 14s per block, then yes, something is truly bad. While not blazing fast, it should be a lot++ faster than block production time.

**Comment by lxex** [comment]
thanks for your message @holiman.

My application scenario is to use the account(`common.Address{}`) to traverse all the historical transactions.
my solution is
1) use one `Address`  and block number `start `and `end`
2) Dichotomy to find the history `Nonce` and `Balance` changes
3) Get the block
4) Find the address's transactions with block.Transactions()

**Do you have a better way to quickly query historical transactions according to a address?**
thanks!

**Comment by ligi** [comment]
You might want to give turbo_geth a try - it *might* help you
It would be good to know a bit more about your use-case to help you further here. E.g. are you only interested in the outgoing transactions of one account?

**Comment by holiman** [comment]
Also, if you're only interested in the outgoing transactions, you wouldn't even need an archive node, just some custom go-code to traverse the transactions in the block bodies in `ancients` and find the ones that are relevant.

**Comment by karalabe** [comment]
It's not really clear what your end goal is here.

If you want to get all outgoing transactions for a specific account, you can iterate over the blocks and just retrieve the transactions from each block and look at the senders. If you want to do this regularly or as a service, you can maintain your own index. Geth will not maintain this index because it's not something every user wants. Using an archive node for this seems overkill.

**Comment by lxex** [comment]
Thanks for all.
If I retrieve the transactions from each block and compare each transaction's from and to with the address, I think its low performance. otherwise there are many addresses.

how a wallet user gets more history transactions?

**Comment by holiman** [comment]
> If I retrieve the transactions from each block and compare each transaction's from and to with the address, I think its low performance.

It's low performance yes, also it misses the cases where you receive funds via a contract. 

> how a wallet user gets more history transactions?

Usually logs, solidity `event`s, that leave a few bits in the block bloomfilter. There are basically no super-easy and good ways to obtain a complete listing of everything that went into your account. I'm not saying it can't be done, obviously it can, but there's no super-easy way to do it.

**Comment by lxex** [comment]
> It's low performance yes, also it misses the cases where you receive funds via a contract.

Yes I konw, it losts contract state that's not I need, we only need the account that has priv key.

thanks for your replay.


by the way, does eth support to sync the latest state trie?
