### ISSUE TITLE
error on running geth attach to a local script

### ISSUE THREAD

**Issue by jason12343** [ethereum/go-ethereum#22110]
my js code is fine if i use node wstest.js
geth attach --exec 'loadScript("wstest.js")'
when i tried to use this command . 
errors :
Unexpected reserved word
        at native
and i located the line with error , was just some 
import statement like this 
const WebSocket = require('ws');
is the interact console doesn't support import statement or something im missing here?
any way i can make this work?need some information from my ws channel to code the logic here.

**Comment by DGKSK8LIFE** [comment]
could I get some more context here? @jason12343

**Comment by jason12343** [comment]
> could I get some more context here? @jason12343

const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 8081 });

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    console.log('received: %s', message);
  });
});

here is the script 


GoError: Error while compiling or running script: SyntaxError: /root/ws/testws.js: Line 2:1 Unexpected reserved word
        at native
        at <eval>:1:12(1)

this is the error

**Comment by DGKSK8LIFE** [comment]
could you please put your code in a formatted codeblock so I can read it easier? Thanks @jason12343

**Comment by jason12343** [comment]
> could you please put your code in a formatted codeblock so I can read it easier? Thanks @jason12343

sorry for the format DGKSK8LIFE ,  the code went wrong at first 2 lines 
so this two statement was not able to pass the compiler

const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 8081 });

**Comment by DGKSK8LIFE** [comment]
Thanks sorry had class @jason12343

**Comment by jason12343** [comment]
> Thanks sorry had class @jason12343

no problem . I changed the const key word to var then it works .don't know why but it's ok now

**Comment by DGKSK8LIFE** [comment]
@jason12343 it's best to use `let` instead of `var`; if you're declaring the import in the global scope then you should have no problem referencing it anywhere you want in code.

**Comment by jason12343** [comment]
> @jason12343 it's best to use `let` instead of `var`; if you're declaring the import in the global scope then you should have no problem referencing it anywhere you want in code.

@DGKSK8LIFE , I think i know this , but running code in geth console is different . the problem only appear when i use --exec 'loadScript("/xxx/xxx.js") to start the code .. and i also am running into problems like js modules .seems like the interact console can not simply import any js modules ,related to this https://github.com/ethereum/web3.js/issues/1849 ..

**Comment by DGKSK8LIFE** [comment]
ok no problem @jason12343. Might wanna report said problems
