### ISSUE TITLE
Solidity used require() Reverted need gas?

### ISSUE THREAD

**Issue by boy-good** [ethereum/go-ethereum#22116]
transaction: https://etherscan.io/tx/0x5b0b03e5d589fef5306e261a26a206f806d9df8d8faf2c8840fb495815c134e9
This tx Reverted & Contract used **require()** but also need gas?
But i see docs “From the Metropolis version, require type exceptions do not consume any gas.”
I don't quite understand, please help.
![image](https://user-images.githubusercontent.com/39320533/103618789-823c0a80-4f6b-11eb-973d-a87af6abf02d.png)

**Comment by MariusVanDerWijden** [comment]
See https://stackoverflow.com/questions/48077773/ethereum-solidity-does-require-use-any-gas
The transaction consumes gas up until the require. Difference is that the require does not consume *all* gas left.
For the future please ask questions like this on the stackexchange https://ethereum.stackexchange.com/
