### ISSUE TITLE
[ABIGEN] Add option to create bindings from a contract addres and use etherscan to fetch it.

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#22119]
# Rationale

Why should this feature exist?
Much nicer workflow for e2e test and make sure the tests run against the deployed version.

What are the use-cases?
e2e tests
# Implementation
Happy to open a PR for this.

so the change would be that when the contract paths is an address it uses etherscan to fetch it. One requirement is that it would also need an etherscan API key.

**Comment by karalabe** [comment]
This is a nice idea, but very much out of scope for `abigen`. It goes also a bit against the notion that a compiler should be deterministic. Using Etherscan for source retrieval would also be trusting a remote server to deliver highly sensitive data that can cause serious loss if used badly. All in all, no :) But should not be that hard to add your own tool on top of abigen for your own use case.

**Comment by ligi** [comment]
If you write such a tool it would be nice if it also supports sourcify and not only etherscan. In this case you would not even need an API key.

**Comment by krasi-georgiev** [comment]
Actually, I just tried and with etherscan you can get the contract without an API key, has some rate limit but it is reasonable.

I agree with @karalabe points, but for e2e tests I think it is reasonable.

@karalabe is there any more trusting way to get a contract from the blockchain than relying on a central entity?
