### ISSUE TITLE
err="authentication needed: password or unlock"

### ISSUE THREAD

**Issue by Gui1105** [ethereum/go-ethereum#22120]
WARN [01-05|20:29:45.605] Served eth_sendTransaction               conn=195.123.222.16:41236 reqid=1 t="54.957µs"  err="authentication needed: password or unlock"
WARN [01-05|20:29:45.613] Served eth_sendTransaction               conn=195.123.222.16:40270 reqid=1 t="35.645µs"  err="authentication needed: password or unlock"
WARN [01-05|20:29:45.879] Served eth_sendTransaction               conn=195.123.222.16:37126 reqid=1 t="45.434µs"  err="authentication needed: password or unlock"
WARN [01-05|20:29:46.125] Served eth_sendTransaction               conn=195.123.222.16:40270 reqid=1 t="52.919µs"  err="authentication needed: password or unlock"
WARN [01-05|20:29:46.126] Served eth_sendTransaction               conn=195.123.222.16:41236 reqid=1 t="32.034µs"  err="authentication needed: password or unlock"
WARN [01-05|20:29:46.312] Served eth_sendTransaction               conn=195.123.222.16:52336 reqid=1 t="47.161µs"  err="authentication needed: password or unlock"
WARN [01-05|20:29:46.501] Served eth_sendTransaction               conn=195.123.222.16:40270 reqid=1 t="50.655µs"  err="authentication needed: password or unlock"
WARN [01-05|20:29:46.501] Served eth_sendTransaction               conn=195.123.222.16:41236 reqid=1 t="37.66µs"   err="authentication needed: password or unlock"
WARN [01-05|20:29:46.744] Served eth_sendTransaction               conn=195.123.222.16:35342 reqid=1 t="44.004µs"  err="authentication needed: password or unlock"
WARN [01-05|20:29:46.987] Served eth_sendTransaction               conn=195.123.222.16:40270 reqid=1 t="55.59µs"   err="authentication needed: password or unlock"
WARN [01-05|20:29:46.987] Served eth_sendTransaction               conn=195.123.222.16:41236 reqid=1 t="39.681µs"  err="authentication needed: password or unlock"
WARN [01-05|20:29:47.182] Served eth_sendTransaction               conn=195.123.222.16:48960 reqid=1 t="43.122µs"  err="authentication needed: password or unlock"
WARN [01-05|20:29:47.370] Served eth_sendTransaction               conn=195.123.222.16:40270 reqid=1 t="45.132µs"  err="authentication needed: password or unlock"
WARN [01-05|20:29:47.370] Served eth_sendTransaction               conn=195.123.222.16:41236 reqid=1 t="36.703µs"  err="authentication needed: password or unlock"
WARN [01-05|20:29:47.611] Served eth_sendTransaction               conn=195.123.222.16:59634 reqid=1 t="49.973µs"  err="authentication needed: password or unlock"
...

**Comment by ligi** [comment]
Please add more information. So far this issue is not actionable

**Comment by karalabe** [comment]
Oh yes it is. My hunch is that you opened up your RPC endpoint to the world / internet and someone is actively trying to exhaust your funds. You are actively being attacked. Close your RPC ports down!

**Comment by Gui1105** [comment]
> Oh yes it is. My hunch is that you opened up your RPC endpoint to the world / internet and someone is actively trying to exhaust your funds. You are actively being attacked. Close your RPC ports down!

Thank you for your reply.

**Comment by rjl493456442** [comment]
Close it now, feel free to open again.
