### ISSUE TITLE
Failed to write block into disk          err="write /root/.ethereum/geth/chaindata/2487982.log: no space left on device"

### ISSUE THREAD

**Issue by z2453564902** [ethereum/go-ethereum#22128]
Error before geth restart：
Error: invalid merkle root (remote: 57cc91ee8b91b956592a27b14386abc2aba723b5f4f9e5d3181ace6b5d3cd433 local: 1f9ee59bfa683a25c7a15b626995a3ad7c58c571b40df96eea31e5c5eed9732d)
end:
Failed to write block into disk          err="write /root/.ethereum/geth/chaindata/2487982.log: no space left on device"

**Comment by ligi** [comment]
seems your disc is full

**Comment by joeysino** [comment]
My colleague's light node and my own light node also ran out of disk space this week.

Perhaps it's because the network has been busy recently, the data files have grown faster than usual?

**Comment by joeytwiddle** [comment]
@z2453564902 If your light node is consuming more space than it should, I would recommend reverting to an older version (v1.19.17 works for me) or building the latest version from github.
