### ISSUE TITLE
Rinkeby faucet doesn't work for me 

### ISSUE THREAD

**Issue by ahmedeid6842** [ethereum/go-ethereum#22147]
I didn't receive any ethereum in my account even if i get acknowledgement from Rinkeby faucet website that the transaction completed successfully ... any help ?? 

this is my account address 0x9E864F1182E1FeCDE2C30CCA723d97A1F1278Da7 if anyone can send some ethereum for me ... thanks 😊😊🤗

**Comment by ligi** [comment]
@ahmedeid6842 you have some now

**Comment by karalabe** [comment]
T'was fixed now. Took a week until we finally found a PR from a month ago that broke some internals.

**Comment by ahmedeid6842** [comment]
thanks a lot @ligi  @karalabe 😊😊

**Comment by aet00** [comment]
@ligi May I get some Rinkeby test token,  0xF7e997478843D0dD9e52917032086F33Ba0734C1

**Comment by ligi** [comment]
@aet00 just tried the faucet and it works for me - what error do you get?

**Comment by aet00** [comment]
> @aet00 just tried the faucet and it works for me - what error do you get?

Rinkeby Faucet: No Ethereum address found to fund.

**Comment by ligi** [comment]
@aet00 If I do not see your tweet - the faucet can also not see it:

![Selection_018](https://user-images.githubusercontent.com/111600/110767847-f7bba400-8256-11eb-9c02-4a7d5866a8d1.png)
