### ISSUE TITLE
Remove deprecated command line flags

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#22141]
# Rationale

 * simplification
 * subtraction
 * decrease complexity

This also includes:
 * we need to update puppeth as it is still using them
 * remove dead code paths
 * update documentation

**Comment by DGKSK8LIFE** [comment]
I'd be willing to make a PR fix for this! Let me make a list of deprecated geth flags and go from there.

**Comment by renaynay** [comment]
Awesome @DGKSK8LIFE. Deprecated flags to be removed are located under the `show-deprecated-flags` command. Hope that helps!

**Comment by DGKSK8LIFE** [comment]
Now that I look at the codebase, this is a larger undertaking than I initially speculated. I also need some help navigating it. There's lots of interdependence within the code. Maybe I could open a draft PR and then we could work on addressing this issue from there?

**Comment by DGKSK8LIFE** [comment]
And if not, could someone explain where everything is in Ethereum's codebase related to flags? Thanks

**Comment by DGKSK8LIFE** [comment]
What do you think about the draft PR suggestion? @ligi

**Comment by ligi** [comment]
I think you should do something else then (e.g. test if #22145 works instead of telling others to do so)
IMHO when wanting to contribute in this project you should be familiar with the codebase or at least know how to get familiar.
I also think you should stop approving PRs when you are not familiar with the codebase.

**Comment by DGKSK8LIFE** [comment]
Yeah I'm gonna take a break from geth and come back once I feel I'm ready to contribute.

**Comment by renaynay** [comment]
Can we already deprecate most of the flags in the aliased section? Some where removed in May 2020
