### ISSUE TITLE
Add contract.abi to get ABI of contract

### ISSUE THREAD

**Issue by JohnDorien1** [ethereum/go-ethereum#2214]
In case I want to interact with a contract that I do not know the source for, and don't have the abi, contract.abi should receive the ABI.

```
var mycontract = web3.eth.contract.abi.at(address);
mycontract.function() ...
```

This would also help in case a registrar name is pointed to a contract, and its updated, the user will have the most recent abi to use instantly

**Comment by karalabe** [comment]
There's really no way to retrieve the ABI of a contract after it being compiled. The blockchain only contains an EVM bytecode, no naming, no methods, no nothing's included in there.
