### ISSUE TITLE
Force geth to continue using fast sync

### ISSUE THREAD

**Issue by 1blockologist** [ethereum/go-ethereum#22150]
Apparently geth uses full sync when it thinks your node is close to the latest state

I think this is not really the case. I think instead it looks to see if it has switched to full sync at any time in the past and continues to full sync from then on, no matter if I specified --syncmode fast or not

Is there a way around this?

I used fast sync on a node a year ago and let it run for a while before turning it off. now I have a year to catch up on but the system keeps switching to full sync

using command ./build/bin/geth --syncmode fast --cache=8192

and receiving WARN Switch sync mode from fast sync to full sync, which really means "hey I just switched your sync mode from fast sync to full sync no matter what you wanted"

**Comment by fjl** [comment]
If your node is one year behind, you might as well start fast sync from scratch. The chain data you have is not going to accelerate the fast sync because Ethereum state has high turnover.

**Comment by krychla1** [comment]
Why has been this closed? 
I'm experiencing the same, my node is 8 days behind (block 11734968), keeps switching to full sync, no way to switch to fast. (8days in full node at 5tx/s would take ~1 month of syncing). 
Are you sure this is the desired behavior? Have to start from scratch in case a node is a few days off?

**Comment by holiman** [comment]
Well, you should be able to catch up a few days without problem, but if you're only doing 5txs/s, instead of 5 blocks/s, then there's something else awry, and a resync won't fix it. What's the machine? Any numbers on io performance?

**Comment by krychla1** [comment]
Sorry, it was a typo. I meant 5blocks/s. 
Still it is far more than syncing it from scratch by --fast. I mean, its a pity that we should rather sync the whole blockchain, if we are just a few days behind, than to have the possibility to switch back to fast.

**Comment by holiman** [comment]
But hold on. If you import 5 blk/s, and the production of blocks is 1blk/15s, then one hour of imports is 18K blocks, or 1.3 days. So every hour you sync is 1+day. So it's definitely 'worth it' to chug through up to maybe a week or two of blocks in favor of fast-sync from scratch. Restarting fast-sync would be possible, yes, but would leave a lot of garbage data. We're switching to snapsync soon, not worth building more intricate models on fast-sync though.

**Comment by krychla1** [comment]
Now I see. Sorry, wrong math. Writing quicker than thinking. I already went the way to removedb, keeping ancient data, seems to be done in a few hours as well.
A look forward to the snapsync, I can only find very little about it. When will it be ready?
