### ISSUE TITLE
Erratic behaviour (hanging, very slow) in Windows 7, 64 bit

### ISSUE THREAD

**Issue by SteffenIvanhoe** [ethereum/go-ethereum#2216]
Acutally I experience the problems by using the wallet application. I filed the issue there but they told me that it is a network issue which belongs to be filed here. Here it goes:

I find it quite difficult to connect the wallet to the blockchain. It often hangs in the "Looking for peers" mode with no resolution. Multiple aborts and restarts are necessary to finally find some peers and get the blockchain updated. The update itself is rather slow. I remember a time when I first experimented with geth in Windows when block downloads where much faster (months ago). Finally when everything is up the wallet loses connection to peers after some time and never regains it without a restart.

I use Windows 7 64-bit and have a reliable high speed web access. I do not see similar problems with updating e.g. my Bitcoin or Dash full nodes.

Because this is a problem which might affect all MIst applications in Windows and Windows still is dominiating the desktop I think this issue should be taken seriously!

**Comment by rfikki** [comment]
Have you synchronized your time to be accurate on your computer. You my check it compared to an NTP Server. That could be the cause of your peer issue.

**Comment by SteffenIvanhoe** [comment]
Yes, my computer gets synchronized automatically via time.windows.com. I have never seen a serious deviation of time (>1s) compared to other clocks.

**Comment by Bubleek** [comment]
This is a f**ing windows! I'am too get this situation. You need swith off you antivirus(if you have it) and  change internet connection mode from the social network to private network, then gath start working normaly.
Read this question: https://github.com/ethereum/mist/issues/94

**Comment by SteffenIvanhoe** [comment]
I have Avast as antivirus program and of course I have it for a reason. Every other application can live with it, I will not switch it of for Geth!

I do not understand your second proposal for changing the internet connection mode. Don't know what "social network" means and where to switch it to "private network"?

**Comment by SteffenIvanhoe** [comment]
One more comment after reading ethereum/mist#94: I do not work with testnet and I do not have the problem that it never works. The hanging occurs about every second try. What almost always happens is that after a while (minutes or hours) the connection to peers get lost and updates stop (seen from the wallet).

**Comment by Bubleek** [comment]
I want help you, but maybe don't fuly understand you. I'am also have this situation(sometimes after working fine with main network mist lost peers connection). But i don't know why it happen.

**Comment by SteffenIvanhoe** [comment]
You don't understand what exactly?

**Comment by obscuren** [comment]
If `mist` is slow / hanging I'm afraid there's little we can do (mist and geth are two separate processes, we can help here with the latter).

There's a known issue on windows with message sizes. Is there a possibility to see if you can use the `develop` branch of `geth` and try to reproduce (or not) the problem?

**Comment by SteffenIvanhoe** [comment]
If there is a known problem then why don't you solve it? If it is not only me but almost every Windows user then you will make a lot of people unhappy who try to experiment a bit with geth / mist / wallet.

Currently I do not have the know how to quickly check all that with a `develop` branch of `geth`. I just have to evaluate `ethereum` for my company and my time doing that is quite limited. Sorry, but I just wanted to let you know of my bad experiences in using your software. It is up to you to ignore that.

**Comment by obscuren** [comment]
@SteffenIvanhoe Simply knowing about an issue doesn't mean one knows how to fix it (or where the problem is).

There's also a reason why I asked you about the `develop` branch. The **known** issue I'm referring to was fixed a while on the `develop` branch. I guess it's up to you to try it out or ignore it.

**Comment by obscuren** [comment]
`develop` binaries for `geth` can be found at https://build.ethdev.com/builders/Windows%20Go%20develop%20branch/builds/-1

**Comment by SteffenIvanhoe** [comment]
Ok, I used to pre-build `geth.exe` from the `develop` branch and it seemed to work faster (one try only). Only the step from 'Block synchronization started' till the first blocks get loaded takes about 3 minutes. But at least it did not hang and the following downloads were much faster then with the mist / wallet combo. 

I will check again tomorrow.
When will that go into the default release?

**Comment by obscuren** [comment]
Everything that you're seeing on the `develop` branch will take about 4 to 6 weeks to go in to `master`, stable, branch. Extra care is taken because of months work that went in to 1.4 (1.4 is next release, i.e. `develop` :)).

**Comment by SteffenIvanhoe** [comment]
Next morning is here. I started the new `Geth` developer version again and it takes 7 minutes and 13 seconds from the start of sync to loading the first block:

    I0216 07:27:52.010774 eth/downloader/downloader.go:295] Block synchronisation started
    I0216 07:35:05.142547 core/blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) ncluding 1579 txs in 3m2.0184108s. #1009568 [2bdd542a / 73f24983]

That feels a little bit like it hangs because I see no progress in between. Is this a normal delay?

**Comment by SteffenIvanhoe** [comment]
On a second try `Geth` needs only 3 seconds for the same step! There must be something wrong with the 7 minutes delay ...?
