### ISSUE TITLE
Problem of VMTest

### ISSUE THREAD

**Issue by LeoNCKU** [ethereum/go-ethereum#22168]
Dear all: 
   Recently I implement the EVM, but when I check the test suit of VMTest. I found that if the storage of key and value are both 0x00, the storage is empty in the "post" section after executing the opcode "PUSH1 0x00 SSTORE" (600055).
The attachment below is the example of test suit "iszero0.json".
![擷取](https://user-images.githubusercontent.com/50820380/104564695-30d7fd80-5686-11eb-9b6f-f17217bcfeb7.JPG)

**Comment by gballet** [comment]
that is normal behavior as per the yellow paper:

![image](https://user-images.githubusercontent.com/3272758/104567487-21898d80-564f-11eb-99cf-27857d22f79a.png)

Setting a slot value to 0 is effectively clearing it, in order to save storage space.

**Comment by LeoNCKU** [comment]
> that is normal behavior as per the yellow paper:
> 
> ![image](https://user-images.githubusercontent.com/3272758/104567487-21898d80-564f-11eb-99cf-27857d22f79a.png)
> 
> Setting a slot value to 0 is effectively clearing it, in order to save storage space.

Thanks you. I already understand.
