### ISSUE TITLE
Add Warning when peer discovery fails due to clock discrepancy

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/go-ethereum#2217]
Hey guys,

It can happen that when you start geth with an empty database that it will never start syncing. This is the second time I encounter this problem. Thankfully I remembered to check `ntpd` and see if the clock was a bit off again. Both times this was the case but had to do some digging to find it out.

If the clock is off by 15-30 secs it will never sync, and will need adjustment. It's trivial to adjust it with ntpd(`sudo ntpdate pool.ntp.org`),  but if the user has no idea of the reason behind the failure it can be a hard thing to spot.

Would it be possible to add some kind of warning when peer discovery fails due to time syncing issues?

**Comment by obscuren** [comment]
It's one of the pain points we're trying to resolve. @fjl is working on this displaying this to the user (merely a suggestion when too many packets get dropped due to out-of-time).

**Comment by LefterisJP** [comment]
Great, that would really be enough. 
A suggestion to check your clock and even a way to do it, maybe users don't know how to, would be great.

**Comment by karalabe** [comment]
We've been talking with Felix about this today but the tricky part is if you're time is in the future, as you'll never get any response from anybody, so it would be the same as if you're disconnected from the internet.

**Comment by karalabe** [comment]
Opinions https://github.com/ethereum/go-ethereum/pull/2218?

**Comment by fjl** [comment]
The warning has been added on the develop branch.
