### ISSUE TITLE
error with clef.ipc

### ISSUE THREAD

**Issue by TheIceHole** [ethereum/go-ethereum#22180]
### System info:
Geth:1.9.24
OS:windows
### Problem
I hava just tried to start geth  as the guidance here (https://geth.ethereum.org/docs/getting-started)
when i  executive command
geth --goerli --syncmode "light" --rpc --signer=<CLEF_LOCATION>/clef.ipc
 "geth --goerli --syncmode "light" --rpc –signer=//.pipe/clef.ipc",

it comes a warn Failed to open wallet  utl=extapi://\\.\pipe[clef.ipc err="operation not supported on external signers".Then, it doesn't output anything for 20 mins,I shutted down and re-executive that command again and get the same situation.What shoud I do next, or just wait ?Do I need to start the geth on a linux os :Ubuntu or others?
###  cmd Output
`D:\Cryptocurrencry\geth>geth --goerli --syncmode "light" --rpc --signer=\\.\pipe\clef.ipc
INFO [01-16|16:43:40.967] Starting Geth on Görli  testnet.

INFO [01-16|16:43:40.995] Dropping default light client cache      provided=1024 updated=128
INFO [01-16|16:43:41.002] Maximum peer count                       ETH=0 LES=10 total=50
WARN [01-16|16:43:41.005] The flag --rpc is deprecated and will be removed in the future, please use --http
INFO [01-16|16:43:41.012] Using external signer                    url=\\.\pipe\clef.ipc
INFO [01-16|16:43:41.036] Set global gas cap                       cap=25000000
INFO [01-16|16:43:41.043] Allocated cache and file handles         database=C:\Users\YCCong\AppData\Local\Ethereum\goerli\geth\lightchaindata cache=64.00MiB handles=8192
INFO [01-16|16:43:41.121] Allocated cache and file handles         database=C:\Users\YCCong\AppData\Local\Ethereum\goerli\geth\lespay cache=16.00MiB handles=16
INFO [01-16|16:43:41.154] Writing custom genesis block
INFO [01-16|16:43:41.167] Persisted trie from memory database      nodes=361 size=51.17KiB time=1.9949ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [01-16|16:43:41.191] Initialised chain configuration          config="{ChainID: 5 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 1561651, Muir Glacier: <nil>, YOLO v2: <nil>, Engine: clique}"
INFO [01-16|16:43:41.227] Added trusted checkpoint                 block=3538943 hash="ff3ae3…d375f2"
INFO [01-16|16:43:41.248] Loaded most recent local header          number=0 hash="bf7e33…b88c1a" td=1 age=1y11mo3w
INFO [01-16|16:43:41.265] Configured checkpoint registrar          address=0x18CA0E045F0D772a851BC7e48357Bcaab0a0795D signers=5 threshold=2
INFO [01-16|16:43:41.277] Starting peer-to-peer node               instance=Geth/v1.9.24-stable-cc05b050/windows-amd64/go1.15.5
INFO [01-16|16:43:41.348] UDP listener up                          net=enode://5e262b9626a5a6697e594070b4f6fbd49ee72c2a3f339b906f78dbd17107c7c629e11dab80acfb910e2141f5f05f599c0447b99e9c1cad074cad64cc1b92aff5@[::]:30303
INFO [01-16|16:43:41.384] New local node record                    seq=1 id=173af10081a5fad6 ip=127.0.0.1 udp=30303 tcp=30303
INFO [01-16|16:43:41.385] IPC endpoint opened                      url=\\.\pipe\geth.ipc
INFO [01-16|16:43:41.426] Started P2P networking                   self=enode://5e262b9626a5a6697e594070b4f6fbd49ee72c2a3f339b906f78dbd17107c7c629e11dab80acfb910e2141f5f05f599c0447b99e9c1cad074cad64cc1b92aff5@127.0.0.1:30303
INFO [01-16|16:43:41.440] HTTP server started                      endpoint=127.0.0.1:8545 cors= vhosts=localhost
WARN [01-16|16:43:41.525] Light client mode is an experimental feature
WARN [01-16|16:43:41.533] Failed to open wallet                    url=extapi://\\.\pipe\clef.ipc err="operation not supported on external signers"
INFO [01-16|17:09:33.758] Got interrupt, shutting down...
INFO [01-16|17:09:34.263] HTTP server stopped                      endpoint=127.0.0.1:8545
INFO [01-16|17:09:34.270] IPC endpoint closed                      url=\\.\pipe\geth.ipc
INFO [01-16|17:09:34.274] Blockchain stopped
INFO [01-16|17:09:34.276] Transaction pool stopped
INFO [01-16|17:09:34.290] Light ethereum stopped`

**Comment by TheIceHole** [comment]
I foun it。。。。。。。It has been started successfully.I just need to open another termimal ,go to that directory and input the command "geth attach ipc://.pupe/geth.ipc" to get the Interactive console.
I was stupid by myself。。。。。。。。

**Comment by ligi** [comment]
@TheIceHole can we close the issue then? Or do you have an idea how the documation could be improved?

**Comment by zayg** [comment]
Hi there. Any idea on why you got this "Failed to open wallet url" ? I am hitting the same issue..
