### ISSUE TITLE
verbosity option doesn't work

### ISSUE THREAD

**Issue by Code0x2** [ethereum/go-ethereum#22188]
#### System information

Geth version: `1.9.25`
OS & Version: linux
Commit hash : none

#### Expected behaviour
Running geth with --verbosity <level#> should set a logging option

#### Actual behaviour
Running the command `geth --verbosity 4` sets it to use debug logging, however, 
running the command `geth console --verbosity 4` does not work. Other options such as --ws and --maxpeers work fine

**Comment by MariusVanDerWijden** [comment]
`console` always needs to be the last argument (as it is a subcommand).
So `geth --verbosity 4 console` should work. If not please reopen

**Comment by Code0x2** [comment]
> `console` always needs to be the last argument (as it is a subcommand).
> So `geth --verbosity 4 console` should work. If not please reopen

Odd. It works for all other options other than verbosity. Thanks though!
