### ISSUE TITLE
Extend the "TraceCall" API so that the state override can be support

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/go-ethereum#22197]
Now the `eth_call`API can accept an optional parameter `overrides *map[common.Address]account` so that the user can customize the states by himself. Would be nice to include this feature in the tracer API too.

**Comment by holiman** [comment]
Triage discussion: this can be added without making a breaking change, by adding a new field to the input config for that particular call.

**Comment by huahuayu** [comment]
> Now the `eth_call`API can accept an optional parameter `overrides *map[common.Address]account` so that the user can customize the states by himself. Would be nice to include this feature in the tracer API too.

hi @rjl493456442 although the feature is been added, could you explain what's the typical use case, could you make an example?

**Comment by attente** [comment]
Is there a way to make this functionality accessible on the ethclient.Client interface?

**Comment by attente** [comment]
Hi, this is my first attempt to contribute to go-ethereum: https://github.com/ethereum/go-ethereum/pull/23129. It exposes an interface on ethclient.Client to allow account state overrides when performing `eth_call`. Comments and critique would be much appreciated!
