### ISSUE TITLE
Compiling with Go v1.42 on Debian Jessie - Error 2 

### ISSUE THREAD

**Issue by admazzola** [ethereum/go-ethereum#2219]
>make geth

build/env.sh go install -v -ldflags '-X main.gitCommit c541b38fb36587d23c60f5e2f2b9b3c8700ec489' ./cmd/geth
github.com/ethereum/go-ethereum/core/types
  # github.com/ethereum/go-ethereum/core/types
build/_workspace/src/github.com/ethereum/go-ethereum/core/types/transaction.go:39: undefined: atomic.Value
build/_workspace/src/github.com/ethereum/go-ethereum/core/types/transaction.go:40: undefined: atomic.Value
build/_workspace/src/github.com/ethereum/go-ethereum/core/types/transaction.go:41: undefined: atomic.Value
Makefile:17: recipe for target 'geth' failed
make: *** [geth] Error 2
andy@LANDSHARK:~/Ethereum/go-ethereum$

**Comment by xurunhua** [comment]
Hi Admazzola,

I have the same problem. Did you find out how to fix it? Tried go v1.4 and v1.5, both failed with the same message as yours.

Thanks,
Ryan
