### ISSUE TITLE
implement structured logging in go-ethereum

### ISSUE THREAD

**Issue by sveneh** [ethereum/go-ethereum#222]
Implement the structured logging spec from @heikoheiko defined at https://github.com/ethereum/system-testing/wiki/Log-Events

This is a requirement for https://github.com/ethereum/system-testing/issues/30

Will also be done for cpp, tracked here: https://github.com/ethereum/cpp-ethereum/issues/705

**Comment by fjl** [comment]
Sven is telling me that this is really urgent. @tgerring did you have a chance to look at this yet?

**Comment by tgerring** [comment]
@obscuren did yo have a chance to document the logging changes you had in mind?

**Comment by obscuren** [comment]
Yes but it will involve a full re-write of the logging system. Putting it up tomorrow

**Comment by obscuren** [comment]
Ignore my earlier statement regarding reimplementing the log system. Instead we'll add additional logging.

We'll use our current `event` system for passing `LogEvents` to the `ObjectLogger` object. The `ObjectLogger` should be started as a service when requested from the CLI and watch for `LogEvent`s. @tgerring I'll leave the implementation of how the ObjectLogger interprets events to you.

### Example

```go
// Event type
type LogEvent struct {
    // Additional fields?
    Object interface{} // json.Marshal this object
}

// Post object
eventMux.Post(LogEvent{myObject})

// Handle object
switch ev.(type) {
    case LogEvent:
        json.MarshalIndent(ev.Object)
}
```
