### ISSUE TITLE
Move the simulated backend and the abi package

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum/go-ethereum#22206]
# Rationale

Right now before the 1.10 release is the best timing to do breaking changes.
Moving the simulated backend from `accounts/abi/bind/simulated` to either `/simulated` or maybe `tests/simulated` would be good.
Also moving the `accounts/abi/bind` to `abi/bind/` would be a good change imo, as `abi` doesn't have anything to do with accounts.

# Implications
Moving the packages would have implications for all depending projects as they would have to update their dependencies to reflect the new paths.

**Comment by holiman** [comment]
Triage discussion: 
- No strong practical points in favour, other than it being 'more correct'.

@karalabe neither pro nor against

Decided to wait for input from @fjl

**Comment by MariusVanDerWijden** [comment]
We moved the simulated backend when we created SimulatedBackendV2

**Comment by MariusVanDerWijden** [comment]
We moved the simulated backend when we created SimulatedBackendV2
