### ISSUE TITLE
syncing error: header broke chain ordering

### ISSUE THREAD

**Issue by ryanschneider** [ethereum/go-ethereum#22209]
#### System information

Geth version: 1.9.25 
OS & Version: Linux

#### Expected behaviour

I was testing something so setup two nodes, node A is peered with the wider devp2p network while node B is started with a fairly recent copy of the chain (maybe an hour old) and is running with the arguments `--nodiscover --netrestrict 10.0.0.0/8`, it's then manually peered with node A via admin_addPeer/addTrustedPeer.

I would expect this scenario to work and for node B to sync to head from node A (and continue to stay in sync with node A).  I've done this before with more nodes successfully but never limited the process to just two nodes.

#### Actual behaviour

However, in this case once node B got close to head, it got into a state where it kept rejecting the blocks received from node A:

```
Jan 21 22:38:43 ip-10-0-74-205 geth[12200]: INFO [01-21|22:38:43.239] Imported new chain segment               blocks=16  txs=2635 mgas=199.946 elapsed=3.919s    mgasps=51.017 number=11701582 hash="a52330…62f0cc" age=1m30s    dirty=506.16MiB
Jan 21 22:38:48 ip-10-0-74-205 geth[12200]: INFO [01-21|22:38:48.192] Imported new chain segment               blocks=3   txs=381  mgas=37.481  elapsed=644.368ms mgasps=58.167 number=11701585 hash="b055c9…48715a" dirty=506.67MiB
Jan 21 22:38:57 ip-10-0-74-205 geth[12200]: INFO [01-21|22:38:57.067] Imported new chain segment               blocks=1   txs=144  mgas=11.983  elapsed=263.178ms mgasps=45.531 number=11701586 hash="3e9092…0b6929" dirty=507.09MiB
Jan 21 22:39:13 ip-10-0-74-205 geth[12200]: INFO [01-21|22:39:13.325] Imported new chain segment               blocks=1   txs=189  mgas=12.475  elapsed=309.923ms mgasps=40.253 number=11701587 hash="ab97c1…80fc48" dirty=507.26MiB
Jan 21 22:39:33 ip-10-0-74-205 geth[12200]: INFO [01-21|22:39:33.797] Deep froze chain segment                 blocks=21  elapsed=14.074ms  number=11611587 hash="d29346…775f81"
Jan 21 22:39:33 ip-10-0-74-205 geth[12200]: WARN [01-21|22:39:33.900] Head headers broke chain ordering        peer=b5d45226ed68e4b8 index=0 requested=11701586 received=11701590
Jan 21 22:39:33 ip-10-0-74-205 geth[12200]: WARN [01-21|22:39:33.900] Synchronisation failed, dropping peer    peer=b5d45226ed68e4b8 err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 21 22:39:33 ip-10-0-74-205 geth[12200]: INFO [01-21|22:39:33.901] Looking for peers                        peercount=0 tried=0 static=1
Jan 21 22:40:08 ip-10-0-74-205 geth[12200]: INFO [01-21|22:40:08.901] Looking for peers                        peercount=1 tried=1 static=1
Jan 21 22:40:14 ip-10-0-74-205 geth[12200]: WARN [01-21|22:40:14.499] Head headers broke chain ordering        peer=b5d45226ed68e4b8 index=0 requested=11701586 received=11701596
Jan 21 22:40:14 ip-10-0-74-205 geth[12200]: WARN [01-21|22:40:14.499] Synchronisation failed, dropping peer    peer=b5d45226ed68e4b8 err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 21 22:40:49 ip-10-0-74-205 geth[12200]: INFO [01-21|22:40:49.501] Looking for peers                        peercount=1 tried=1 static=1
Jan 21 22:41:21 ip-10-0-74-205 geth[12200]: INFO [01-21|22:41:21.097] Downloader queue stats                   receiptTasks=0 blockTasks=0    itemSize=42.72KiB throttle=1535
Jan 21 22:41:21 ip-10-0-74-205 geth[12200]: WARN [01-21|22:41:21.097] Synchronisation failed, dropping peer    peer=b5d45226ed68e4b8 err="retrieved hash chain is invalid: no peers available or all tried for download"
Jan 21 22:41:21 ip-10-0-74-205 geth[12200]: INFO [01-21|22:41:21.100] Looking for peers                        peercount=0 tried=0 static=1
Jan 21 22:41:44 ip-10-0-74-205 geth[12200]: WARN [01-21|22:41:44.922] Head headers broke chain ordering        peer=b5d45226ed68e4b8 index=0 requested=11701587 received=11701603
Jan 21 22:41:44 ip-10-0-74-205 geth[12200]: WARN [01-21|22:41:44.922] Synchronisation failed, dropping peer    peer=b5d45226ed68e4b8 err="retrieved hash chain is invalid: head headers broke chain ordering"
```

It tried this several times then eventual seemed to give up:

```
Jan 21 22:47:28 ip-10-0-74-205 geth[12200]: WARN [01-21|22:47:28.550] Header broke chain ancestry              number=11701623 hash="459a13…5ddd65"
Jan 21 22:47:28 ip-10-0-74-205 geth[12200]: INFO [01-21|22:47:28.551] Downloader queue stats                   receiptTasks=0 blockTasks=33   itemSize=42.72KiB throttle=1535
Jan 21 22:47:28 ip-10-0-74-205 geth[12200]: WARN [01-21|22:47:28.551] Synchronisation failed, dropping peer    peer=b5d45226ed68e4b8 err="action from bad peer ignored: stale headers"
Jan 21 22:47:28 ip-10-0-74-205 geth[12200]: INFO [01-21|22:47:28.551] Looking for peers                        peercount=0 tried=0 static=1
```

Restarting node B seemed to let it progress without hitting this issue again but it did take 5 minutes to sync the missing blocks.

#### Steps to reproduce the behaviour

- Start node A and sync to head.
- Make a backup of its chain data
- Restore the backup on a new node B (be sure not to use the same node `key`) that only has network access to node A
- Observe the issue above

#### Analysis

What I _think_ is happening is that node A is announcing new blocks as they are produced at the same time that node B is catching up to head and thus requesting slightly older headers from A at the same time.

Thus when node B gets the latest header for head while while expecting one of the older ones, the code below causes the downloader to error out: https://github.com/ethereum/go-ethereum/blob/83d317cff937940395fcb7ece29effc9c7779c13/eth/downloader/downloader.go#L846

It seems to me like maybe in this scenario is downloader should issue the warn about broken chain ordering but simply ignore the header instead of erring out the download?  Or maybe even resubmit the packet back onto `headerCh` for later processing?

**Comment by ryanschneider** [comment]
So I _think_ the issue is that `downloader.fetchHead`, `.findAncestor` and `.DeliverHeaders` all share the same `headerCh` but `findAncestor` and `.fetchHead` both seem to assume that the next header in the channel is always the one they asked for, even though there's nothing stopping `.DeliverHeaders` from injecting other headers, leading somewhat racy behavior.

For example, imagine:

- findAncestor asks for headers 11701586 to 11701590 on line 820 (notably in a goroutine)
- at roughly the same time node A announces block 11701596 to its peers
- node B receives block 11701596 and it's added to the channel via `DeliverHeaders` (in ethHandler.Handle)
- findAncestor reads from the channel on line 833 but gets the unexpected 11701596 packet instead of 11701586, and cancels downloading

**Comment by ryanschneider** [comment]
Also FWIW I don't think this error is actually related to the network topology above I described, I checked another test node running 1.9.24 (an archive node with "vanilla" devp2p network setup), and it seems like it's hit this same "race" 15 times in the last month:

```
Jan 08 01:23:37 ip-10-0-67-119 geth[22149]: WARN [01-08|01:23:37.014] Head headers broke chain ordering        peer=adab52156ed1c3a1 index=0 requested=11611002 received=11611005
Jan 08 01:23:37 ip-10-0-67-119 geth[22149]: WARN [01-08|01:23:37.014] Synchronisation failed, dropping peer    peer=adab52156ed1c3a1 err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 08 11:32:27 ip-10-0-67-119 geth[22149]: WARN [01-08|11:32:27.400] Head headers broke chain ordering        peer=3648da2b2c589bc9 index=0 requested=11613822 received=11613825
Jan 08 11:32:27 ip-10-0-67-119 geth[22149]: WARN [01-08|11:32:27.400] Synchronisation failed, dropping peer    peer=3648da2b2c589bc9 err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 09 06:02:55 ip-10-0-67-119 geth[22149]: WARN [01-09|06:02:55.188] Head headers broke chain ordering        peer=1224967e43246567 index=0 requested=11618863 received=11618867
Jan 09 06:02:55 ip-10-0-67-119 geth[22149]: WARN [01-09|06:02:55.188] Synchronisation failed, dropping peer    peer=1224967e43246567 err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 09 19:26:24 ip-10-0-67-119 geth[22149]: WARN [01-09|19:26:24.195] Head headers broke chain ordering        peer=ae0197451c696a6b index=0 requested=11622461 received=11622464
Jan 09 19:26:24 ip-10-0-67-119 geth[22149]: WARN [01-09|19:26:24.196] Synchronisation failed, dropping peer    peer=ae0197451c696a6b err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 12 10:25:42 ip-10-0-67-119 geth[22149]: WARN [01-12|10:25:42.615] Head headers broke chain ordering        peer=48784859a08962b0 index=0 requested=11639573 received=11639576
Jan 12 10:25:42 ip-10-0-67-119 geth[22149]: WARN [01-12|10:25:42.615] Synchronisation failed, dropping peer    peer=48784859a08962b0 err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 13 01:19:05 ip-10-0-67-119 geth[22149]: WARN [01-13|01:19:05.003] Head headers broke chain ordering        peer=74ca34024782e56e index=0 requested=11643637 received=11643640
Jan 13 01:19:05 ip-10-0-67-119 geth[22149]: WARN [01-13|01:19:05.003] Synchronisation failed, dropping peer    peer=74ca34024782e56e err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 13 11:56:02 ip-10-0-67-119 geth[22149]: WARN [01-13|11:56:02.638] Head headers broke chain ordering        peer=74ca34024782e56e index=0 requested=11646438 received=11646441
Jan 13 11:56:02 ip-10-0-67-119 geth[22149]: WARN [01-13|11:56:02.638] Synchronisation failed, dropping peer    peer=74ca34024782e56e err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 14 18:02:03 ip-10-0-67-119 geth[22149]: WARN [01-14|18:02:03.232] Head headers broke chain ordering        peer=f10d797a3ec9eb54 index=0 requested=11654710 received=11337727
Jan 14 18:02:03 ip-10-0-67-119 geth[22149]: WARN [01-14|18:02:03.232] Synchronisation failed, dropping peer    peer=f10d797a3ec9eb54 err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 15 15:01:40 ip-10-0-67-119 geth[22149]: WARN [01-15|15:01:40.551] Head headers broke chain ordering        peer=12bbc0788e783178 index=0 requested=11660375 received=11660378
Jan 15 15:01:40 ip-10-0-67-119 geth[22149]: WARN [01-15|15:01:40.551] Synchronisation failed, dropping peer    peer=12bbc0788e783178 err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 15 17:38:50 ip-10-0-67-119 geth[22149]: WARN [01-15|17:38:50.404] Head headers broke chain ordering        peer=48784859a08962b0 index=0 requested=11337724 received=11661142
Jan 15 17:38:50 ip-10-0-67-119 geth[22149]: WARN [01-15|17:38:50.404] Synchronisation failed, dropping peer    peer=48784859a08962b0 err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 18 22:21:20 ip-10-0-67-119 geth[22149]: WARN [01-18|22:21:20.997] Head headers broke chain ordering        peer=12bbc0788e783178 index=0 requested=11681902 received=11681905
Jan 18 22:21:20 ip-10-0-67-119 geth[22149]: WARN [01-18|22:21:20.997] Synchronisation failed, dropping peer    peer=12bbc0788e783178 err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 19 02:18:00 ip-10-0-67-119 geth[22149]: WARN [01-19|02:18:00.351] Head headers broke chain ordering        peer=877018c696938d8e index=0 requested=11682961 received=11337727
Jan 19 02:18:00 ip-10-0-67-119 geth[22149]: WARN [01-19|02:18:00.351] Synchronisation failed, dropping peer    peer=877018c696938d8e err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 20 05:32:24 ip-10-0-67-119 geth[22149]: WARN [01-20|05:32:24.414] Head headers broke chain ordering        peer=74ca34024782e56e index=0 requested=11690387 received=11337727
Jan 20 05:32:24 ip-10-0-67-119 geth[22149]: WARN [01-20|05:32:24.414] Synchronisation failed, dropping peer    peer=74ca34024782e56e err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 20 22:11:27 ip-10-0-67-119 geth[22149]: WARN [01-20|22:11:27.833] Head headers broke chain ordering        peer=207ae0400732475a index=0 requested=11695013 received=11695016
Jan 20 22:11:27 ip-10-0-67-119 geth[22149]: WARN [01-20|22:11:27.833] Synchronisation failed, dropping peer    peer=207ae0400732475a err="retrieved hash chain is invalid: head headers broke chain ordering"
Jan 21 17:28:38 ip-10-0-67-119 geth[22149]: WARN [01-21|17:28:38.952] Head headers broke chain ordering        peer=239c15d65fb14926 index=0 requested=11700145 received=11337727
Jan 21 17:28:38 ip-10-0-67-119 geth[22149]: WARN [01-21|17:28:38.952] Synchronisation failed, dropping peer    peer=239c15d65fb14926 err="retrieved hash chain is invalid: head headers broke chain ordering"
```

**Comment by holiman** [comment]
I've looked into this a bit now, and experimented a bit. There are two possible cases that I think you are reporting. 

1. Whether a 'spurious' header from some other peer can disrupt the common-ancestor phase of the sync. TLDR; No. 

At https://github.com/ethereum/go-ethereum/blob/master/eth/downloader/downloader.go#L854, there's this thing which _looks_ like it may cause problems

```golang	for finished := false; !finished; {
		select {
		case <-d.cancelCh:
			return 0, errCanceled

		case packet := <-d.headerCh:
			// Discard anything not from the origin peer
			if packet.PeerId() != p.id {
				log.Debug("Received headers from incorrect peer", "peer", packet.PeerId())
				break
			}
				
```
(there are similar constructs in other places too). 
However, [Golang spec](https://golang.org/ref/spec#Break_statements) says, about break statements, that 

> A "break" statement terminates execution of the innermost "for", "switch", or "select" statement within the same function. 

So that `break` indeed just ignores the packet (albeit with a debug log) and continues waiting for something from the peer we requested headers from. 


2. Whether a 'spurious' header from some other peer can disrupt the common-ancestor phase of the sync. TLDR; Yes, probably. 

I think this can happen -- while we're in the phase of querying for headers with `peerA`, and `peerA` decides to send over some header, that would definitely disturb the happenings here. However, I don't see how that can happen -- when new blocks arrive, they're broadcast to some of the peers, but _not as headers_, but as blocks. 

So I'm still not quite sure of what sequence of events would cause `peerA` to send a header like that (not saying it doesn't happen).

**Comment by ryanschneider** [comment]
I need to review the code again but I thought the block itself was
broadcast to the square root of len(peers) but then the header was sent to
all the other peers (or maybe all peers).

**Comment by holiman** [comment]
> It seems to me like maybe in this scenario is downloader should issue the warn about broken chain ordering but simply ignore the header instead of erring out the download? Or maybe even resubmit the packet back onto headerCh for later processing?

I agree -- it seems better to simply wait it out and see if the peer delivers what we asked for (before the timeout triggers), and simply ignore anything else coming in. 

Otherwise, we might end up in the scenario where previous deliveries keep piling up and being mistaken as answers to new queries.

**Comment by holiman** [comment]
> but then the header was sent to all the other peers (or maybe all peers).

Nope, AFAICT it's not the header, it's the announcement of new `(hash, number)` pairs

**Comment by ryanschneider** [comment]
> > but then the header was sent to all the other peers (or maybe all peers).
> 
> Nope, AFAICT it's not the header, it's the announcement of new `(hash, number)` pairs

Hmm, you are 100% correct it is the announcement not the header itself that's sent, my mistake.

But.. in response to the announcement if I'm tracing things correctly it's the block _fetcher_ not the _downloader_ that in turn ultimately issues a `GetBlockHeadersMsg` message in response to this announcement via `blockFetcher.Notifty(..., peer.RequestOneHeader, ...)` here:

https://github.com/ethereum/go-ethereum/blob/017831dd5b33a68076aed7c9ff05e62b0dcb5f92/eth/handler_eth.go#L195

So while even less likely now, I think it's still _possible_ that in between node B asking for headers N to M and node A replying with those headers that separately node A announces header Z, node B seems that announcement and then the fetcher issues `GetBlockHeadersMsg(Z)` which ends up conflicting with the expected `GetBlockHeadersMsg(N...M)` message.

Here's a quickly thrown together sequence diagram to (maybe? :) ) help explain what I'm seeing:

https://www.websequencediagrams.com/files/render?link=BFo7YS3IAbAcur7g5oW4yI4WMeQslFNEdgNnLYyIKZty2JgIehVPAWLDhK1xUyhm

<img src="https://www.websequencediagrams.com/files/render?link=BFo7YS3IAbAcur7g5oW4yI4WMeQslFNEdgNnLYyIKZty2JgIehVPAWLDhK1xUyhm">

**Comment by ryanschneider** [comment]
Anyways I'm very curious what your thoughts are on the idea of reenqueuing the "unexpected" messages instead of discarding them or erring out, if I recall correctly I've seen geth take that approach in other parts of the code but am having trouble finding where.

**Comment by holiman** [comment]
Yeah, that diagram looks like it could be a potential cause of these types of errors. With eth/66, these types of problems will go away. In the meantime, my fix will improve it a tiny bit, and seems pretty safe. If we instead do some more elaborate pushback/store thingy, that sounds pretty complex if we also want it not to be a DoS vector. I think.

**Comment by MariusVanDerWijden** [comment]
I think this issue can be closed now, since we have requestid's with eth/66. So we can uniquely attribute messages to requests.
Feel free to reopen if I'm being stupid rn
