### ISSUE TITLE
Can't call internal tracer in `traceBlockByNumber`

### ISSUE THREAD

**Issue by lightclient** [ethereum/go-ethereum#22208]
#### System information

Geth version: `1.9.25`
OS & Version: Ubuntu

#### Expected behaviour
Run internal tracers.

#### Actual behaviour
```
Error: json: error calling MarshalJSON for type json.RawMessage: unexpected end of JSON input
        at web3.js:6347:37(47)
        at web3.js:5081:62(37)
        at <eval>:1:25(7)
```

#### Steps to reproduce the behaviour
From JS console:
```
> debug.traceBlockByNumber(11701516, {tracer: 'unigramTracer'})
```

**Comment by ligi** [comment]
does `debug.traceBlockByNumber(11701516, {'tracer': 'unigramTracer'})` work?
