### ISSUE TITLE
Command line help

### ISSUE THREAD

**Issue by dankrad** [ethereum/go-ethereum#22218]
The current version of geth gives the following line in the command line help:
```
   geth [options] command [command options] [arguments...]
```
Actually, it appears that to start go-ethereum as an Ethereum node, the `command` argument is left out. This should be documented by showing that command is optional:
```
   geth [options] [command] [command options] [arguments...]
```
and adding a line describing this behaviour, e.g. "leaving out the `command` parameter starts geth as an ethereum node"

It may also be nice to add a "node" command and making this the default behaviour.

**Comment by ligi** [comment]
good point actually - fixing via 22220
not yet sure about adding the line describing the behavior as it breaks with the rest of the help layout - but for sure command should be marked optional

**Comment by dankrad** [comment]
> not yet sure about adding the line describing the behavior as it breaks with the rest of the help layout - but for sure command should be marked optional

Also consider my suggestion of adding a command "node" to actually start the Ethereum node. I filed this report after staring on the help screen for like 10 minutes and wondering "how to I actually start the node"

**Comment by ligi** [comment]
I think this is a great idea - then we could also mark this one as "default"

**Comment by fjl** [comment]
The documentation is fixed now, but we don't want to add the "node" command. Geth has subcommands for functionality beyond just running the node, but being an Ethereum node is the main thing, and doesn't need a subcommand.
