### ISSUE TITLE
debug_traceChain is no longer working

### ISSUE THREAD

**Issue by gballet** [ethereum/go-ethereum#22222]
The code for `TraceChain` is still present in the codebase, but somehow it's not callable from the rpc interface nor the console. `debug_traceBlock*` work as expected.

#### System information

Geth version: `1.9.26-unstable` && whatever runs on the archive node @ligi 
OS & Version: Linux
Commit hash : `master`

#### Expected behaviour

Returning a list of trace results.

#### Actual behaviour
```
$ curl -X POST -H "Content-Type: application/json" --data '{"method": "debug_traceChain", "params": ["0x1", "0x2"], "id": 1}' http://example.com | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   186  100   121  100    65   1163    625 --:--:-- --:--:-- --:--:--  1788
{
   "error" : {
      "code" : -32601,
      "message" : "the method debug_traceChain does not exist/is not available"
   },
   "id" : 1,
   "jsonrpc" : "2.0"
}
```

**Comment by ligi** [comment]
the archive node is currently running:

```
archive@archive:~$ ./geth version
Geth
Version: 1.9.25-stable
Git Commit: e7872729012a4871397307b12cc3f4772ffcbec6
Git Commit Date: 20201211
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.6
Operating System: linux
GOPATH=/home/archive/go
GOROOT=go
```

**Comment by rjl493456442** [comment]
You have to explicitly expose the `debug` namespace APIs via the http, by default it's not.

**Comment by rjl493456442** [comment]
You have to explicitly expose the `debug` namespace APIs via the http, by default it's not.

**Comment by ligi** [comment]
@rjl493456442 the archive is started with `-rpcapi eth,web3,debug` - guess this is what you mean? Also `debug_traceBlock` is working as expected

**Comment by gballet** [comment]
@s1na provided the right approach in js, this require the subscription.

```javascript
const { ethers } = require("ethers")
const provider = new ethers.providers.WebSocketProvider('ws://127.0.0.1:9546')
const res = provider.send('debug_subscribe', ['traceChain', '0x3f3a2a', '0x3f3a2b']).then((res) => console.log('got res', res)).catch((err) => console.log('failed', err))
```

#22232 proposes a fix for using with `ethclient`, it needs to be rebased and I don't want to spend any more time on this.
