### ISSUE TITLE
geth console can‘t input string slice, how to solve this problem？

### ISSUE THREAD

**Issue by tkblack** [ethereum/go-ethereum#22228]
version : v1.9.15
os : centos 7.6

```
abstract contract Table {
    /**
     * @dev create new table
     * @param _tableName the name of table
     * @param _fields the names of fields
     */
    function createTable(
        string memory _tableName, 
        string[] memory _fields) 
    public {
        ......
    }
......
}
```

I write a contract like above, geth console can't input string type or string slice type, but successfully by web3j. So, is there any way to input string type into the geth console?

**Comment by MariusVanDerWijden** [comment]
I think that's a problem with the old version of web3.js that we use in the console, we use 0.20.1.
It is not really possible for us to update web3js at this point. My suggestion would be to not use the geth console to interact with contracts.

**Comment by tkblack** [comment]
@MariusVanDerWijden Thanks for your reply! I got it.
