### ISSUE TITLE
Calling eth_signTransaction via JSON RPC reports "gas not specified" when gas field missing in transaction

### ISSUE THREAD

**Issue by thojest** [ethereum/go-ethereum#22223]
According to the [JSON RPC spec](https://eth.wiki/json-rpc/API) `eth_signTransaction` uses a gas default. However, when  trying to sign a transaction with the gas field missing, geth reports ` { code: -32000, message: "gas not specified" }`.

This does not happen when e.g. using the same transaction with the `eth_sendTransaction` procedure.

I am not sure if this is intended behavior or a bug. This behavior was observed using geth in `--dev` mode.

**Comment by MariusVanDerWijden** [comment]
Yeah you're right, some methods calculate meaningful default values for the gas, gasprice and other fields while others do not. We're currently looking into creating a new standard for JSON-RPC requests s.th. we can properly test against it and find issues like this. If it is okay for you, I would propose not to fix this bug right now but rather wait until the new specification is written.

**Comment by thojest** [comment]
Thanks for the info. I am currently writing an alternative web3 implementation and noticed this one because I run all my tests as integration tests against a geth node in `--dev` mode. There are some other deviations from the spec. If there is any interest to collect these deviations I could open a new issue?

**Comment by MariusVanDerWijden** [comment]
Yes, we collect these deviations here: https://github.com/ethereum-oasis/eth1.x-JSON-RPC-API-standard/issues/5
If you're interested in joining the calls about the JSON-RPC spec you can join the Ethereum R&D discord, there's a json-rpc-api channel there

**Comment by thojest** [comment]
Thanks for the link :) I will add my findings there. Also thanks for the discord link  :+1:
