### ISSUE TITLE
mining address get changed everytime i have set in ETH private blockchain

### ISSUE THREAD

**Issue by pawanlapits** [ethereum/go-ethereum#22226]
I have a private ethereum node running on aws instance, the time when started the node i set the etherbase/coinbase address to the first account of the node. As i started the node i find that first account is getting the rewards of mining and everything was as expected, but after few hours the miner/etherbase address automatically get changed, as a result of which funds from first account get transferred to miner address as a mining reward. And i unlocked the first account to send the transaction over the node and as all the funds get transferred to newly assigned miner address, all my transactions become pending due to insufficient funds in sender account. Any help will be appreciated.
Thanks in advance.

Here are the few details of geth client and command i used :

GO ETHEREUM CLIENT DETAILS :
Geth
Version: 1.9.12-stable
Git Commit: b6f1c8dcc058a936955eb8e5766e2962218924bc
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.8
Operating System: linux
GOPATH=
GOROOT=/build/ethereum-YoJS3q/.go

GETH COMMAND :
/usr/bin/geth --datadir node01 --networkid 10 --allow-insecure-unlock --targetgaslimit 9000000000000 --nousb --etherbase '0x669980d2EF6b14e15e4e1D32E70F2ccC83EC98c9' --rpc --rpcaddr "0.0.0.0" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3 --rpccorsdomain '*'

GENESIS.JSON :
{
"alloc": {
"0x669980d2EF6b14e15e4e1D32E70F2ccC83EC98c9": {
"balance": "10000000000000000000000000000000000000"
},
"0x61722d9D8F75E97A2F8B4C63Be1C8820D944C940":{
"balance": "1000000000000000000000000000000000000"
}
},
"coinbase": "0x669980d2EF6b14e15e4e1D32E70F2ccC83EC98c9",
"config": {
"homesteadBlock": 0,
"byzantiumBlock": 0,
"constantinopleBlock": 0,
"chainId": 10,
"eip150Block": 0,
"eip155Block": 0,
"eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"eip158Block": 0,
"maxCodeSize": 35,
"maxCodeSizeChangeBlock" : 0,
"isQuorum": true
},
"difficulty": "0x0",
"extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
"gasLimit": "0xE0000000",
"mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
"nonce": "0x0",
"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"timestamp": "0x00"
}

**Comment by holiman** [comment]
Well, you're running with `--allow-insecure-unlock`, plus expose the rpc interface to the public interface `0.0.0.0`, plus expose `admin, personal`. 
I suspect what's happening is that someone on the internet does RPC calls to set your miner address to their address, so they get the rewards. It's a useless attack, since you're not on mainnet, but I guess the attacker-scripts doesn't bother to check if it's worthwhile to do it, they just do it. 

You should see some info about it in the logs, like `Served miner.setCoinbaseBase` (or whatever method they used)

**Comment by holiman** [comment]
>  funds from first account get transferred to miner address

> as all the funds get transferred to newly assigned miner address


I suspect they also used the fact that the account was unlocked to also steal your funds.

**Comment by pawanlapits** [comment]
So what's your suggestion here. What can we do to protec?

**Comment by ligi** [comment]
e.g. don't ` --allow-insecure-unlock`

**Comment by holiman** [comment]
Typical recommendations: 
- Don't unlock accounts, especially if you also expose RPC. Unlocking is inherently _insecure_ hence the hint in the switch to explicitly do it anyway: `insecure-unlock`. 
- Don't expose your node RPC towards the internet: don't set `0.0.0.0` as the interface. use localhost instead, and if you want to interact with it, you set up an ssh tunnel `ssh -L 8545:localhost:8545 user@machine`, then you can interact with `localhost:8545` at the machine you made the connection from.

**Comment by pawanlapits** [comment]
"I suspect they also used the fact that the account was unlocked to also steal your funds."

how can we do transaction without unlock account.
how can we protect rpc interface, currently we have public(0.0.0.0)

We have deployed one service on same server which interact with node and further we will use that service api in our application.
in this case, how can we protect out rpc interface

**Comment by ligi** [comment]
> how can we do transaction without unlock account.

you can sign transactions outside the node - e.g. with clef

> how can we protect rpc interface, currently we have public(0.0.0.0)

make it not public or restrict it (by not having admin, personal )

**Comment by pawanlapits** [comment]
/usr/bin/geth --datadir node01 --networkid 10  --targetgaslimit 9000000000000 --nousb --etherbase '0x669980d2EF6b14e15e4e1D32E70F2ccC83EC98c9' --rpc --rpcaddr "127.0.0.1" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3 --rpccorsdomain '*'

Is this fine now

**Comment by pawanlapits** [comment]
can you please share any link or example of how can we use clef for transactions

**Comment by karalabe** [comment]
You can send transactions via `persona.sendTransacition` which requires the passphrase set up too, it does an ephemeral unlock and send, without allowing anyone else to use the key for anything else. That's usually the way if you want to do it via Geth.

**Comment by pawanlapits** [comment]
Hi @ligi @holiman @karalabe 

Thanks for your suggestions.  Its really helpful. I have one, how can someone change my minor address. Is there any way, by which we can change minor address without accessing server
