### ISSUE TITLE
Transaction recieved from subscribtion, but does not exist in the TX pool

### ISSUE THREAD

**Issue by iht76** [ethereum/go-ethereum#22229]
I am running local Geth and I subscribe to pending transactions....
so I start receiving the stream, however there are transactions which were broadcasted to the subscribtion (so I do recieve them), but when I check in the tx pool (via txpool.content) they do not exist there...

Why do they not appear in the tx pool, BUT get broadcasted via the subscribtion?

Should the Tx not enter in the Tx pool when the node recieves it, and then be broadcasted to any subscribtions?

**Comment by MariusVanDerWijden** [comment]
It could be that the txpool already dropped the transaction. The txpool only has a limited number of slots and if they are filled up, transactions that pay too little gas price are dropped. If the node received a replacement transaction (a transaction from the same sender with the same nonce but 10% more gas), it will also drop the old transaction.

**Comment by iht76** [comment]
in this case the transaction is still pending and its not dropped .... it just doesnt appear in my Tx pool.
and if its not in the pool, how and why do I recieve it via the subscribtion?

**Comment by ligi** [comment]
I guess it is just not in the pool anymore. Not really sure what action we can take here. Does it break any of your use-cases?

**Comment by iht76** [comment]
What I dont really understand is how the subscribtion works .... why I am recieving a transaction which is not in the nodes pool? Perhaps it never went through it and I got it from other node? I would expect that if I recieve a transaction throug subscribtion,  it would first go through the nodes pool, no ? 

I am trying to do fast check of say 2k transactions if they are mined or not.... if i do that tx by tx (web3.eth.getTransaction(txHash); its too slow, so instead i was thinking that downloading the nodes pool at once and doing the checks locally will solve that - and it does, however some txs never go through the node. Perhaps i shoud increase the node slots for pending txs?

**Comment by holiman** [comment]
> why I am recieving a transaction which is not in the nodes pool? 

1. New tx arrives -> sent to the pool + send out on the internal channels, which get's pushed to subscriptions. 
2. Now the tx exists in two totally separate places: as a piece of data in a subscription-pack, to be processed by the eventsystem, and as a transaction in the pool
3. Something happens: a higher priced one comes in, and it gets dropped by the pool. 
4. You process the notification, query the pool, find it missing  
5. You open a github ticket :) 

I don't think there are any open questions here any longer, so I'm closing tihs
