### ISSUE TITLE
web3.eth.pendingTransactions returns "no keys in store" error

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/go-ethereum#2223]
Geth
Version: 1.3.3
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go

**Comment by aakilfernandes** [comment]
I can "fix" this by creating a new account, but I believe the behavior should work with an empty keystore

**Comment by obscuren** [comment]
Correct, however, you can only have pending transactions if you created any transactions which requires a key. `pendingTransactions` is meant only for transactions that are "owned" (i.e. the sender of your tx is in your key store).

Doing `eth.pendingTransactions` should in the case of an empty key store (basically no transactions) return you `[]` (empty array).

**Comment by aakilfernandes** [comment]
Got it. That makes sense. I assumed it was supposed to return all transactions in the mempool. Thanks!

**Comment by obscuren** [comment]
Oh no, most certainly not. If you'd like to get that you can inspect the `txpool` (check `develop` branch) :-)
