### ISSUE TITLE
 RPCDaemon Out of Memory Error

### ISSUE THREAD

**Issue by relyt29** [ethereum/go-ethereum#22244]
This is a duplicate of https://github.com/ledgerwatch/turbo-geth/issues/1458 - the bug seems to be most likely in geth and not turbo-geth specifically, so I thought I'd copy the bug over to upstream for visibility.

Note: This could be leveraged as a denial of service attack against long-running Geth nodes with lots of history that expose the debug namespace publicly

#### System information
```
Geth
Version: 1.9.25-stable
Git Commit: e7872729012a4871397307b12cc3f4772ffcbec6
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.6
Operating System: linux
GOPATH=
GOROOT=go
```

#### Expected behaviour

Send me a trace of the transaction

#### Actual behaviour

silently crash, OOM killed by Linux (see https://github.com/ledgerwatch/turbo-geth/issues/1458 for dmesg dump)

#### Steps to reproduce the behaviour

```
curl -X POST  -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xd80a10106f2a8fb76cf6db6b9f7a64f08257b4952c94c888e1ac41ceb80733c9"],"id":1}' "http://127.0.0.1:8646"
```

#### Backtrace

````
Apparently not possible since geth crashes without any logging output
````

Note this is parially reported by @MysticRyuujin and not me, my geth node doesn't have enough history to be able to make this query, when I do it I get `{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"required historical state unavailable (reexec=128)"}}` - so to repro you may have to either have a long-running node, or be running geth under archive mode.

**Comment by Haaroon** [comment]
I concur with tyler that this tx indeed causes a crash

**Comment by ligi** [comment]
The cause seems to be that the tx touches a lot of memory. You can disable memory output when tracing - could this work for you? There is a vmconfig for this.

**Comment by holiman** [comment]
I _think_ this is the way to do it: 
```
curl -X POST  -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xd80a10106f2a8fb76cf6db6b9f7a64f08257b4952c94c888e1ac41ceb80733c9", { "disableMemory": true} ],"id":1}' "http://127.0.0.1:8646"
```

**Comment by MysticRyuujin** [comment]
I think the primary issue here is that there are no safeguards in place, geth literally gets killed without warning by the OS.

This could lead to database corruption, DoS, etc.

**Comment by holiman** [comment]
There's one way to get around this, and that's to NOT use RPC, but instead use `debug_standardTracetransaction`, which dumps it out, in a streaming form, to the filesystem.

**Comment by holiman** [comment]
> And there's basically no way to know "this tx is going to crash my node" in advance, and "I'd better disable memory here". One tx is fine, the next crashes your node.

Actually, one thing we _could_ do, would be to limit the size of the trace, so we'd only ever report back the first 1K lines or whatever. But IMO it's more hassle than it's worth, and also would just force us to add more options for rerunning it and get the next 1K lines etc. 

Basically, don't expose `debug` to arbitrary callers, they _will_ be able to crash your node.

**Comment by MysticRyuujin** [comment]
#21963
