### ISSUE TITLE
monitorcmd: termui out of date

### ISSUE THREAD

**Issue by immesys** [ethereum/go-ethereum#2225]
The build works fine for the version of gizak/termui specified in the Godeps (so there is nothing wrong with the build), but presumably the dependencies will be updated at some point, so I thought I would log this as a TODO. With the latest termui, the build fails with:

```
./monitorcmd.go:111: undefined: termui.UseTheme
./monitorcmd.go:123: footer.HasBorder undefined (type *termui.Par has no field or method HasBorder)
./monitorcmd.go:144: undefined: termui.EventCh
./monitorcmd.go:145: undefined: termui.EventKey
./monitorcmd.go:145: undefined: termui.KeyCtrlC
./monitorcmd.go:148: undefined: termui.EventResize
./monitorcmd.go:312: chart.Block.Border.Label undefined (type bool has no field or method Label)
./monitorcmd.go:314: chart.Block.Border.Label undefined (type bool has no field or method Label)
./monitorcmd.go:334: chart.Block.Border.LabelFgColor undefined (type bool has no field or method LabelFgColor)
./monitorcmd.go:334: chart.Block.Border.FgColor undefined (type bool has no field or method FgColor)
./monitorcmd.go:334: too many errors
```

**Comment by obscuren** [comment]
Thanks for reporting!

We vendor all our deps using `godep`. Please use `godep go install ./cmd/geth`.

**Comment by karalabe** [comment]
@immesys The code was actually updated in develop already yesterday, all the related code was fixed last week. You need to use develop to get them in :)

**Comment by ShamariFeaster** [comment]
I am seeing the same problem on master. If the accepted workflow is to have a broken master (which is highly unusual), it would seem the documentation (https://github.com/ethereum/go-ethereum/wiki/Developers'-Guide) should reflect this.

**Comment by immesys** [comment]
The workflow is to use godep. Master builds find for me with godep go build

**Comment by ShamariFeaster** [comment]
@immesys I deleted my repo, re-pulled master, and it built without the errors shown in the OP above. Removing my comment as I can't reproduce it.
