### ISSUE TITLE
EncodePacked missing in the abi package

### ISSUE THREAD

**Issue by vaibhavchellani** [ethereum/go-ethereum#22257]
# Rationale

## Why should this feature exist?

Solidity supports `abi.encode` as well as `abi.EncodePacked` and `abi` package only exposes the `pack` method that returns output that matches `abi.encode` in solidity. 

## What are the use-cases?

To be able to do `abi.encodePacked` using the abi package in `go-ethereum`

**Comment by MariusVanDerWijden** [comment]
I implemented a preliminary version of `abi.EncodePacked` here:
https://github.com/MariusVanDerWijden/go-ethereum/tree/encode-packed
It currently only does primitive types.
Am not sure whether we really want it in the code base since it is non-standard and ambiguous.

**Comment by JGcarv** [comment]
Just a question, wouldn't the result of  `abi.EncodePacked` be the same as encoding a dummy method with the same arguments and stripping the 4 bytes of function signature?

Asking because I need to encode  two variable-length arguments into a `[]byte` to be passed to a solidity contract.

Thank you!

**Comment by MariusVanDerWijden** [comment]
@JGcarv Unfortunately not, it might be for some cases, but it is more complicated than that generally, see also https://github.com/ethereum/go-ethereum/pull/22273

**Comment by MariusVanDerWijden** [comment]
We decided not to pursue this feature further as it might be used to introduce unsafe behaviour in smart contracts. 
The PR will be still be open for a while, if someone wants to take it over. But I'll close this issue for now
