### ISSUE TITLE
Simulated Backend Smart Contract Receive Function Should Increment Storage Variable But Does Not

### ISSUE THREAD

**Issue by bonedaddy** [ethereum/go-ethereum#22252]
#### System information

go-ethereum version: v1.9.25

#### Expected behaviour

Receive function should increment totalSupply variable

#### Actual behaviour

Does not increment variable.

#### Overview

I'm testing out [this contract](https://github.com/bonedaddy/geth-pending-state-test/blob/master/contracts/test.sol) using the simulated backend. I'm testing it [with this golang code](https://github.com/bonedaddy/geth-pending-state-test/blob/master/main.go). The TotalSupply variable should be set and incremented to 2, but it does not, as per the following output:

```
2021/01/30 01:34:39 gas used by deployment transaction:  147403 [test contract deployment]
2021/01/30 01:34:39 gas used by transaction:  42265 []
2021/01/30 01:34:39 gas used by transaction:  21000 [sendeth 0xd2d50a33c3c6bfed86333c000c6d1ffb6e40eb0c0fbd0630eef75b04ecd9c527]
2021/01/30 01:34:39 error: supply should be 2
```

#### Reproduction steps:

```shell
$> git clone https://github.com/bonedaddy/geth-pending-state-test.git
$> cd geth-pending-state-test
$> go mod download
$> go build
$> ./geth-pending-state-test
```

**Comment by holiman** [comment]
I don't know the specifics of your testing framework, but at one point, you do 
```
	addr, err := testenv.DoWaitDeployed(tx, "test contract deployment")
	if err != nil {
		log.Fatal(err)
	}
```

Later on, however, you do
```
	if err := testenv.SendETH(addr, big.NewInt(100000)); err != nil {
		log.Fatal(err)
	}
	// should be 2
	supply, err = bindings.TotalSupply(nil)
```
Are you sure that the sending of ether is actually mined into a block when you call `bindings.TotalSupply` here?

**Comment by bonedaddy** [comment]
@holiman ah sorry about that I should've included that information.  The framework does mine the block. 

* [here is the mining logic for DoWaitDeployed](https://github.com/bonedaddy/bdsm/blob/master/testenv/testenv.go#L49-L50)
* [Here is where SendETH calls DoWaitMined](https://github.com/bonedaddy/bdsm/blob/master/testenv/testenv.go#L86)
* [Here is the mining logic for DoWaitMined](https://github.com/bonedaddy/bdsm/blob/master/testenv/testenv.go#L42-L43)

So I'm 100% certain it is mining the blocks

**Comment by karalabe** [comment]
I think your fault is that sendETH hard codes 21000 gas, but you also have code execution there, so it should be more than 21000? In essence your tx is throwing?

**Comment by MariusVanDerWijden** [comment]
@bonedaddy your code needs to estimate the gas usage before constructing the transaction
