### ISSUE TITLE
make geth error

### ISSUE THREAD

**Issue by yueqianhaobo** [ethereum/go-ethereum#22254]
#### System information

Geth version: `go1.14.7`
OS & Version: Ubuntu

Hello.
When try to make geth take error
```
env GO111MODULE=on go run build/ci.go install ./cmd/geth
go: github.com/Azure/azure-pipeline-go@v0.2.2: Get "https://proxy.golang.org/github.com/%21azure/azure-pipeline-go/@v/v0.2.2.mod": dial tcp 172.217.160.81:443: i/o timeout
make: *** [Makefile:16: geth] Error 1
```

#### Backtrace

````
[backtrace]
````

**Comment by yueqianhaobo** [comment]
OS & Version:Ubuntu20

**Comment by MariusVanDerWijden** [comment]
Seems like an issue with your internet connection. 
Could you try again? And maybe try to execute `ping 172.217.160.81` and report back?

**Comment by holiman** [comment]
> Seems like an issue with your internet connection.

Definitely. Please reopen if it doesn't "fix itself" or generally does _not_ appear to be some network issue on your end
