### ISSUE TITLE
Caller gas above allowance, capping: functions.call() succeeds while functions.transact() fails

### ISSUE THREAD

**Issue by lzszsd** [ethereum/go-ethereum#22268]
#### System information
Geth
Version: 1.9.25-stable
Git Commit: e7872729012a4871397307b12cc3f4772ffcbec6
Git Commit Date: 20201211
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.6
Operating System: windows
GOPATH=
GOROOT=go

#### Expected behaviour
I am trying to use Web3.py to interact with my deployed contract. The following code is supposed to invoke the function "recharge" so that a user can recharge a specific amount of balance.
>         
        (temp_str, balance_int) = platform.functions.recharge(int(amount)).call()
        gas = platform.functions.recharge(int(amount)).estimateGas({'from': node.eth.accounts[0]}) + 1000
        tx_hash = platform.functions.recharge(int(amount)).transact({'from': node.eth.accounts[0], 'gas': gas})
        # time.sleep(10)
        tx_receipt = node.eth.waitForTransactionReceipt(tx_hash)
        print(tx_receipt)

And here is the initialization part of my program, where "platform" and "node" come from:
> 
    import sys
    import os
    import json
    import time
    ...
    from web3 import Web3
    ...
    from eth_utils.address import to_checksum_address
    os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

    ...

    if __name__ == '__main__':
        node = Web3(Web3.IPCProvider())
        time.sleep(1)
        contract_address = '0xDb2008E1B886056c016e212593B4925522D3F1Ff'
        platform_address = to_checksum_address(contract_address)
        abiTxt = open("abi.txt", "r")
        platform_abi = abiTxt.read()
        platform = node.eth.contract(address=platform_address, abi=platform_abi)
        node.geth.miner.start(1)
        node.geth.personal.unlockAccount(node.eth.accounts[0], 'XXX') 
        ...

And finally, the related part of the contract:
> 
    contract energyTrade{
        ...
        mapping (address => uint) balances;
        ...
        function recharge(uint _amount) public returns(string memory, uint) {
            balances[msg.sender] += _amount;
            return ("Recharge successfully!", balances[msg.sender]);
        }
Now let's go back to my first quote of code: **I hope to see** the right return from call() the first time I run the code. However, this does not provide enough information about whether the recharge amount X is really added into the balance in the contract. So **I hope to see** the right current amount, which should be X, when I run it for the second time with the input "int(amount)" equal to 0. 

Peer connection and block synchronization have proved stable on the private chain. The contract has been tested and works out well in Remix.         
#### Actual behaviour
However, when I ran the mentioned code, the transaction would not WRITE any data into the contract. The second return from call() was 0, which means the first transaction in which the function "recharge" was involved had failed. Here is more information I dug out when I was trying to fix the problem:

Reading the geth log, I think this is where the bug stems from, notably the first line:

> 
    WARN [02-04|20:37:47.140] Caller gas above allowance, capping      requested=232211324932526 cap=25000000
    INFO [02-04|20:37:47.192] Submitted transaction                    fullhash=0xc956dab71ff6b077f686b43ba65ef2e3c914398f4
    3a532671cb1fb0134552268 recipient=0xDb2008E1B886056c016e212593B4925522D3F1Ff
    INFO [02-04|20:37:48.461] Commit new mining work                   number=1321 sealhash="f13cf7鈥?e52d1" uncles=0 txs=0 
    gas=0     fees=0          elapsed=2.000s
    INFO [02-04|20:37:48.471] Commit new mining work                   number=1321 sealhash="75df5d鈥288fa" uncles=0 txs=1 
    gas=28061 fees=2.8061e-05 elapsed=2.009s
    INFO [02-04|20:37:48.741] Successfully sealed new block            number=1321 sealhash="75df5d鈥288fa" hash="84bd6c 
    鈥0
    e94e" elapsed=270.277ms
    INFO [02-04|20:37:48.741] 馃敆 block reached canonical chain          number=1314 hash="0789fa鈥3720c"
    INFO [02-04|20:37:48.741] 馃敤 mined potential block                  number=1321 hash="84bd6c鈥0e94e"

Why is the requested gas such huge? How can I set the global gas cap?

And an important finding is that the third INFO records the normal gas, which is very close to the gas I will consume if I test the function on Remix, and is also identical to the gas(28061) in the transaction receipt:

> 
    AttributeDict({'blockHash': HexBytes('0x84bd6c365f73aa715f2ef703d97fe14e3fb646167bd2bbf1d7659f42dab0e94e'), 
    'blockNumber': 1321, 'contractAddress': None, 'cumulativeGasUsed': 28061, 'from': 
    '0xA21c63eC1e5aCe46B25fc4e66a8aECc42062b232', 'gasUsed': 28061, 'logs': [], 'logsBloom': 
    HexBytes('0x0'), 'root': '0x8d6f08c7b3f8ae78c55d4040289df2b2cf1e8f30705c9661c9926b6ba3ad0692', 'to': 
    '0xDb2008E1B886056c016e212593B4925522D3F1Ff', 'transactionHash': 
    HexBytes('0xc956dab71ff6b077f686b43ba65ef2e3c914398f43a532671cb1fb0134552268'), 'transactionIndex': 0
    })

This is the first time I post an issue, and sorry for the wordiness. But it's really urgent. I have been working on this single problem for a week. Please help!  @gravityblast @bts @shazow @fjl @sauliusgrigaitis (Sorry, not sure about which expert to mention, so I just disturb you all.)
#### Steps to reproduce the behaviour
Forgot to post my geth instruction:

> 
    geth --identity "Energy" --http --http.corsdomain "*" --datadir energy --port 30303 --http.api "eth,net,web3,personal" --networkid 12 --gcmode archive --allow-insecure-unlock --nodiscover --syncmode "fast" console 2>>energy.log

#### Backtrace

````
[backtrace]
````

**Comment by MariusVanDerWijden** [comment]
I don't think this is an issue in geth. Seems like web3 sends the transaction with to much gas, nothing go-ethereum can do about that. You can try to run geth with higher verbosity, maybe that produce better logs. But I think the best way to debug this is to log out everything that web3 produces.

I will close this for now, please reopen if you find that this is indeed a bug in go-ethereum
