### ISSUE TITLE
Allow Graceful Handling Of WebSockets Connection Errors in Ethclient

### ISSUE THREAD

**Issue by bonedaddy** [ethereum/go-ethereum#22266]
# Rationale

At the moment the `ethclient` package supports websockets connection to target servers. Websockets can occasionally experience issues that basically require a "rehup" of the connection otherwise the connection will permanently return errors.

I experienced this last night when one of my services returned the following error:
```
websocket: close 1006 (abnormal closure): unexpected EOF
```

I had no choice but to shutdown the service, and restart it it. This is very undesirable in production workloads, and I dont see any easy way to "rehup" the connection.

# Implementation

I have no ideas as to how to implement this, maybe some sort of post-request processing handler that allows you to specify what errors that are received which should trigger a "rehup"? I would be willing to implement this.

**Comment by fjl** [comment]
Would be nice to figure out when this happens. Can you provide more information about the error? When you say that it 'permanently returns errors', are those errors returned by the RPC call? Is it the error message you posted?

Managing the connection is the responsibility of `rpc.Client`. In the client, we close the connection and reconnect when reading fails. So what you are suggesting is already implemented, it just seems to miss this error.

**Comment by xr9kayu** [comment]
@fjl from wich version there is rehup. Because i met such error using 1.9.13 version of go-ethereum package. Im listening new events for the specified contract. As i now infura node can close connection if there is no any transferred data within n minutes, if ethclient can rpc.Client can handle this and reopen closed connection?

**Comment by fjl** [comment]
When the connection fails while the client is idle, the rpc.Client will try to re-create it on the next request. So if a call fails, you must retry it to get a new connection.

**Comment by apecollector** [comment]
I'm using subscriptions for event logs and got a similar error, unsure how to handle it correctly without restarting the server.

```
websocket: close 1012: Service Restart
```

The docs for `sub.Err()` say:

> Err returns the subscription error channel. The error channel receives a value if there is an issue with the subscription (e.g. the network connection delivering the events has been closed). Only one value will ever be sent. The error channel is closed by Unsubscribe.

The part about `Only one value will ever be sent.` leads me to believe that it won't reconnect automatically.

Here's the example code, I'm also running geth locally which it's connecting to.

```go
package main

import (
	"context"
	"log"

	ethereum "github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
)

var contractAddressHex = "0x34d85c9cdeb23fa97cb08333b511ac86e1c4e258"
var contractAddress = common.HexToAddress(contractAddressHex)

func main() {
	conn, err := ethclient.Dial("ws://127.0.0.1:8546")
	if err != nil {
		log.Fatalf("Failed to connect to the Ethereum client: %v", err)
	}
	
	query := ethereum.FilterQuery{
		Addresses: []common.Address{contractAddress},
	}

	logs := make(chan types.Log)
	sub, err := conn.SubscribeFilterLogs(context.Background(), query, logs)
	if err != nil {
		log.Fatal(err)
	}

	for {
		select {
		case err := <-sub.Err():
			log.Fatal(err)
		case vLog := <-logs:
			log.Println(vLog)
		}
	}
}
```

**Comment by fjl** [comment]
When a subscription fails, you need to re-establish it. There is no automatic re-subscribe in ethclient because your application may need to handle the error. However, if you are sure you don't care about it, you can use [`event.Resubscribe`](https://pkg.go.dev/github.com/ethereum/go-ethereum/event#Resubscribe):

```
logs := make(chan types.Log, 1000)
sub := event.Resubscribe(2 * time.Second, func (ctx context.Context) (event.Subscription, error) {
    return conn.SubscribeFilterLogs(context.Background(), query, logs)
})
```
