### ISSUE TITLE
Syncing error: signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78ec7a

### ISSUE THREAD

**Issue by slyfoxhd** [ethereum/go-ethereum#22278]
System information

Geth version: geth version
Geth
Version: 1.9.25-stable
Git Commit: e787272
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.6
Operating System: linux
GOPATH=
GOROOT=go

Expected behaviour: Full node synch
Actual behaviour: Multiple WARN errors

Steps to reproduce:
geth.service file:

[Unit]
Description=Go Ethereum client
After=network.target
Wants=network.target

[Service]
User=goeth
Group=goeth
Type=simple
Restart=always
RestartSec=5
ExecStart=geth --http --datadir /var/lib/goethereum --cache 4096 --maxpeers 30

[Install]
WantedBy=default.target

Hi, my node stopped being active since today. I did an update but it is still not syncing. See screenshot below. Can anyone help how to fix this, I had no issues before. 
![grafik](https://user-images.githubusercontent.com/40612817/107144714-48c93700-693d-11eb-92bf-7068b0635d4d.png)

It also says "invaid block body RLP" and "sync panic:runtime error: invalid memeory address or nil pointer dereference"

![grafik](https://user-images.githubusercontent.com/40612817/107148542-065f2480-6954-11eb-94fa-bc818ed1410e.png)

See here: SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78ec7a

![grafik](https://user-images.githubusercontent.com/40612817/107247327-72fc2100-6a31-11eb-8760-b18f2d86077b.png)

Meanthwile I deleted the geth db file and did a resync. But I get the same error "exit-code" as above.

Resync failed. The log looks strange.

![grafik](https://user-images.githubusercontent.com/40612817/107159850-e7cc4e00-6992-11eb-8d6f-393582a1dbef.png)

Your feedback is much appreciated.
Thanks!

**Comment by slyfoxhd** [comment]
Segfault error, insisted on host move, that solved the issue.

**Comment by holiman** [comment]
Thank for reporting back and cosing it!
