### ISSUE TITLE
eth_SendRawTransaction return txid, but could not find in the network

### ISSUE THREAD

**Issue by haruki515** [ethereum/go-ethereum#22284]
#### System information

Geth version: `Geth/v1.9.25-e7872729`
OS & Version: Linux
Commit hash : `e7872729`

#### Expected behaviour
eth_sendRawTransaction returns a hash and the transaction should be broadcasted to the network.

#### Actual behaviour
returns a hash but the transaction is never broadcasted to the network, and then after restart the transaction broadcast to the network.
Rebooting seems to broadcast from the journal, but it will not broadcast without rebooting.

```
INFO [02-04|13:45:54.493] Loaded local transaction journal         transactions=14 dropped=7
INFO [02-04|13:45:54.495] Regenerated local transaction journal    transactions=7  accounts=2
```

#### Steps to reproduce the behaviour
it's not happen every time, about once a day.
geth run cmdline
```
/usr/bin/geth --cache 8192 --rpc --nousb --rpcapi "net,eth,web3,personal" --rpcport 8545 --syncmode fast --gcmode archive
```
How can i prevent this from happening in the future?

**Comment by haruki515** [comment]
When I sent ETH, and ERC20, ETH was not broadcasted, but ERC20 was sometimes broadcasted.
These transfers were sent from different accounts.

**Comment by MariusVanDerWijden** [comment]
If your transaction is underpriced it gets dropped by all your peers and you won't broadcast it to them anymore. Restarting your node rebroadcasts your transactions. This is expected behaviour, see also the discussion here: https://github.com/ethereum/go-ethereum/issues/22308
