### ISSUE TITLE
Watching pendingTransactions with go-ethereum as a library

### ISSUE THREAD

**Issue by jonasbostoen** [ethereum/go-ethereum#22299]
Why isn't it possible to subscribe to pendingTransactions using a method like `client.subscribePendingTxs` in Golang using go-ethereum as a library? The only subscriptions possible are `subscribeNewHead` and `subscribeFilterLogs`. Am I missing something here? (I have asked this question on the Ethereum stack exchange but to no avail.) Thanks!

**Comment by ligi** [comment]
Can you elaborate a bit on your use-case?

**Comment by MariusVanDerWijden** [comment]
The server side part of this is not implemented

**Comment by jonasbostoen** [comment]
> Can you elaborate a bit on your use-case?

@ligi I want to be able to monitor the transaction pool using Go, to parse pending transactions and see if the receiver is my address.

**Comment by EclesioMeloJunior** [comment]
@jonasbostoen you mean something like this:
```sh
txpool.watchTransaction(txHash)
```
And then update the console output with the events that the transaction is passing by?

**Comment by Jolly23** [comment]
I need something like 

```javascript
    web3.eth.subscribe('pendingTransactions', handler)
```

Because I want to subscribe DEX Swap transactions for arbitraging bot.

[This article](https://chainstack.com/exploring-the-methods-of-looking-into-ethereums-transaction-pool/) explain this.

**Comment by Kantitad** [comment]
https://chainstack.com/exploring-the-methods-of-looking-into-ethereums-transaction-pool/

**Comment by MariusVanDerWijden** [comment]
Will be implemented here: https://github.com/ethereum/go-ethereum/pull/22977
