### ISSUE TITLE
Geth client gets stuck and seems to meet with deadlock

### ISSUE THREAD

**Issue by Muggle-Du** [ethereum/go-ethereum#22296]
#### System information

Geth version: `geth 1.9.24`
OS & Version: ubuntu 18
Commit hash : (if `develop`)

#### Expected behaviour
geth node continually sync from peers

#### Actual behaviour
geth client gets stuck at block height 11816616

#### Steps to reproduce the behaviour

<img width="923" alt="截屏2021-02-09 下午2 52 59" src="https://user-images.githubusercontent.com/25078682/107326516-83ba9e80-6ae6-11eb-8e7f-43c9ae3fbeca.png">

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
`11816616` was mined 16 hours ago. It might be that you're doing a fast-sync, and it's reaching the head block but still has a lot of state to download. 

The screenshot you provided only shows ~30s of unrelated activity. 
Please provide more info, what command did you use to start `geth`, was it doing a fast-sync or was the fast-sync done? 

Also, for future reference, it's better to provide logs with copy-paste rather than screenshots.

**Comment by Muggle-Du** [comment]
Thanks for your reply
I have started syncing from scratch since March of last year, and I start the geth client in docker container with the command:

**entrypoint: ["geth","--ipcdisable","--syncmode","fast","--cache","1024","--nat","none","--datadir","/root","--port","38336","--ws","--wsaddr","0.0.0.0","--wsport","8036","--wsorigins","*","--rpc","--rpcport","8136","--rpcaddr","0.0.0.0","--rpccorsdomain","*","--rpcvhosts","*","--verbosity","3"]**

And I have met with the same problem just now after I restarted the geth client (got stuck in some height).

Or can you give any tutorial about how to debug geth client since I had little experience in developing with Golang?

**Comment by Muggle-Du** [comment]
When I tried to restart geth , this warning came out:

**Already shutting down, interrupt more to panic. times=9**

After more than 5 minutes , it didn't exit with code 0

**Comment by holiman** [comment]
`geth 1.9.24` is not the latest, and I know we've fixed a couple of hang-on-shutdown bugs semi-recently, so I'd recommend an update.

**Comment by Muggle-Du** [comment]
Thanks, I would update the geth client

**Comment by holiman** [comment]
Can we close this or does the original issue remain?
