### ISSUE TITLE
[GETH] [POA] [Clique] My private network is accepting transactions with zero gasprice.

### ISSUE THREAD

**Issue by Dkdaniz** [ethereum/go-ethereum#22292]
Good afternoon, everybody,

I am creating a private ethereum network with the consensus Poa - Proof of Authority (Click) .

My Genisis file: https://gist.github.com/Dkdaniz/a995edfc9c5dfc84112c00e876c4bd26

Number of Signer: 3

Signer 1: 0x598BC011b8F50B40a0Ec4CcC6d6E51B785eFB1F7
Signer 2: 0x888d72bA69958860BC67Bd80e90c76D84eE1977a
Signer 3: 0x0639f66b1f77c2f4e5505285f2a1dc93a2f99e1c

Geth command to rotate the knots:
`
geth --nousb --datadir=$pwd --syncmode 'full' --port 30310 --miner.gasprice 20000000000 --miner.gastarget 470000000000 --http --http.addr 'localhost' --http.port 8545 --http.api admin,eth,miner,net,txpool,personal,web3 --mine --allow-insecure-unlock --unlock "**SIGNER-1**" --password password.txt
`
I have already tested --miner.gasprice for 20000000000, I have tested it with a higher value, I have tested it by removing and leaving it as default.

My network has few transfers 10 or 15 per block at most, but it is accepting transactions with zero gasprice.

Has anyone been through this?

because I would like all transactions to pay a fee, i.e. that GasPrice is different from 0, better, GasPrice > 0;

**Comment by Dkdaniz** [comment]
An Exemple of  transaction with Zero Gas price

![image](https://user-images.githubusercontent.com/17903007/107266993-0bd86f80-6a25-11eb-8420-e5e90e603051.png)

**Comment by MariusVanDerWijden** [comment]
Are all signers geth nodes? We always accept incoming blocks with zero gas price, but we don't mine transactions with zero gasprice afaik (might be wrong though).

**Comment by Dkdaniz** [comment]
Currently I have 3 node, all are validators and it is working correctly, but I would like to remove this characteristic of accepting transaction with 0 gas price.

All have been executed equally, but with their respective ports and address.

`geth --nousb --datadir=$pwd --syncmode 'full' --port 30310 --miner.gasprice 20000000000 --txpool.pricelimit 20000000000 --miner.gastarget 470000000000 --http --http.addr 'localhost' --http.port 8545 --http.api admin,eth,miner,net,txpool,personal,web3 --mine --allow-insecure-unlock --unlock "0x598BC011b8F50B40a0Ec4CcC6d6E51B785eFB1F7" --password password.txt`

i try add `--txpool.pricelimit 20000000000` but dont work too

**Comment by Dkdaniz** [comment]
if you are having this problem, the only solution was to block directly in the code, i.e. I changed the source code and later remade the Geth build.

From:
https://github.com/ethereum/go-ethereum/blob/1bbc8a1944312b91ca72a298c2438133906e9503/core/tx_pool.go#L544

To:
https://github.com/Dkdaniz/go-ethereum/blob/df73ffcb82702172ff178bc0e805a347d02a0d6e/core/tx_pool.go#L549

**Comment by Dkdaniz** [comment]
if you are having this problem, the only solution was to block directly in the code, i.e. I changed the source code and later remade the Geth build.

From:
https://github.com/ethereum/go-ethereum/blob/1bbc8a1944312b91ca72a298c2438133906e9503/core/tx_pool.go#L544

To:
https://github.com/Dkdaniz/go-ethereum/blob/df73ffcb82702172ff178bc0e805a347d02a0d6e/core/tx_pool.go#L549
