### ISSUE TITLE
Build instructions for Mist on Ubuntu miss a dependency

### ISSUE THREAD

**Issue by amiller** [ethereum/go-ethereum#223]
The ubuntu dependencies are listed mostly by reference to this gist from obscuren:
https://gist.github.com/obscuren/fa1cc95360421194f363

https://github.com/ethereum/go-ethereum/wiki/Building-Ethereum(Go)

Although it lists a bunch of ubuntu package dependencies, the following package is missing:
   `qtdeclarative5-dialogs-plugin`

Without this, mist builds, but upon running `mist` the following error appears:
2014/12/31 10:40:07 [GUI] asset not found: you can set an alternative asset path on the command line:
`panic: file:////home/amiller/go/src/github.com/ethereum/go-ethereum/cmd/mist/assets/qml/main.qml.:4 module "QtQuick.Dialogs" is not installed`

This is an issue rather than an edit to the wiki because I don't want to fork/overwrite obscuren's install script without a note

**Comment by obscuren** [comment]
The install script will be removed. There are better tools out there to install `mist`  er `ethereum` :) (brew, apt-get). Feel free to update the wiki :+1:

**Comment by amiller** [comment]
Brew is for mac and apt-get is for binaries, so I guess the scope of this is more for dev / building from source. Regardless I've just updated the wiki to address this! Thanks
