### ISSUE TITLE
super long sync

### ISSUE THREAD

**Issue by Allan57790** [ethereum/go-ethereum#22300]
Hello, Ive decided to start mining the ethereum. So I downloaded Geth and started syncing as explained. The problem is that it's already been running for a few hours and the file is already 150 gb.

I have no error messages and everything seems to be going well. But I think it's starting to take a long time. 
I'll attach you an extract from the cmd.
Thanks in advance
Allan
![geth](https://user-images.githubusercontent.com/78851514/107500500-8379dc00-6b96-11eb-8761-0fe917ea8bc3.png)

**Comment by MariusVanDerWijden** [comment]
That's completely normal, a full ethereum node takes ~ 350GB of storage space. 
If you don't have many GPU's to mine, it might be better to join a pool instead of solo mine

**Comment by Allan57790** [comment]
Ooooooh okay ! Thanks dude, i will join a pool. Thanks again and good day !
