### ISSUE TITLE
Rinkeby Authenticated Faucet -> No Ethereum address found to fund

### ISSUE THREAD

**Issue by ianhyun007** [ethereum/go-ethereum#22305]
I am trying to get some ether for my own study but giving me No Ethereum address found to fund message and fails to give me fund. I would like to get 18.75 ethers and my address is 0xAbe9D5c64A1dcF3D843224bD222e706ea29680f3.

Please very important for me, Thank you.

**Comment by holiman** [comment]
Did you publish it somewhere the faucet can read it? E.g. facebook?

**Comment by ianhyun007** [comment]
yes, I did to FB and address was
https://www.facebook.com/ian.ch.98/posts/2295897023887570

even I put that in, it gave that error

**Comment by ianhyun007** [comment]
yes it was https://www.facebook.com/ian.ch.98/posts/2295897023887570 but it gave that error

**Comment by montalban** [comment]
I've been having problems on Rinkeby test faucet last several days - No Ethereum Address found to fund... could someone please send 10eth to 0xf8B17B25032b82CBDDEe3413FDb7E195D6D2752C? Thanks!

**Comment by holiman** [comment]
@ianhyun007 I've just tested that URL. Indeed, it cannot be fetched, for some reason. I don't think the code is wrong, the test-post "https://www.facebook.com/fooz.gazonk/posts/2837228539847129" still works, but yours doesn't. Perhaps you created the post in a way that makes it not public? I really have no idea how facebook works, but it might be some personal setting you have.

**Comment by karalabe** [comment]
@ianhyun007 That post is private. You need to make it public, otherwise it's not accessible outside of your friend circle.

**Comment by Amantel** [comment]
Hi! 
Trying to get some ETH.
https://www.facebook.com/amantels/posts/pfbid0pWEnXZuJnc4WJYBpgMYCg8XwRwrUbgES9pLEs3kQCYHYhxe8VYUpfKiZF5Kwttrcl

Post is public and I am getting `No Ethereum address found to fund` error.
