### ISSUE TITLE
Running geth results in a dropped Ethernet connection 

### ISSUE THREAD

**Issue by aydwi** [ethereum/go-ethereum#22304]
#### System information

Geth version: 

Version: 1.9.25-stable
Git Commit: e7872729012a4871397307b12cc3f4772ffcbec6
Git Commit Date: 20201211
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.6
Operating System: windows
GOPATH=C:\Users\username\go
GOROOT=go

OS & Version: Windows

![Capture](https://user-images.githubusercontent.com/29029116/107594191-56313a80-6c37-11eb-97fd-48512b678c6a.PNG)

#### Expected behaviour

`geth` should not cause the Ethernet connection to drop.

#### Actual behaviour

After `geth` has been running for, say a few minutes, Windows reports "No Internet" on the Ethernet adapter in use.

![Capture](https://user-images.githubusercontent.com/29029116/107594523-161e8780-6c38-11eb-9b7d-546df0323143.PNG)

Running the Windows Network Troubleshooter resolves the problem **temporarily** with the following message - _"The default gateway is not available"_

![image](https://user-images.githubusercontent.com/29029116/107595012-7eba3400-6c39-11eb-8d29-0f6e49088d1a.png)

#### Steps to reproduce the behaviour

Start geth to sync the Ethereum blockchain locally.

`geth --datadir <dir> --http --etherbase <ethereum_address>`

Wait for a few minutes, the network connection on the current Ethernet adapter should drop.

#### Hardware Details

```
Description . . . . . . . . . . : Realtek Gaming 2.5GbE Family Controller
Manufacturer  . . . . . . . . . : Realtek
Provider  . . . . . . . . . . . : Realtek
Version . . . . . . . . . . . . : 10.39.212.2020
```

**Comment by aydwi** [comment]
Additional information: <dir> pointed to an HDD in my case.

I'm now aware that it is not a good idea, but it could be relevant while debugging.

**Comment by aydwi** [comment]
**Additional information:** Encountered the issue with an SSD too.

**Comment by holiman** [comment]
I've seen issues like this from time to time, when the file descriptors run out -- that's on unix systems though, where sockets and files are "same same", so opening too many files causes networking to start failing. Don't know if it's analoguous to Windows. 

1. Could you check what geth says during startup, about how many fine descriptors it allocates? 
2. Could you check what the OS reports as available filedescriptors when this happens? (I'm not sure how to check that on windows, so can't help you there)

**Comment by karalabe** [comment]
For what it's worth, I personally managed to reliably crash certain routers with IPFS when it made a few thousand connections. How do you fix the issue when it happens? Stop Geth? Restart windows? Restart the router?

**Comment by aydwi** [comment]
@holiman I will look into the descriptor situation and update here.

@karalabe Doing any of the following fixed it - Restarting the router; rebooting Windows; running the in-built network troubleshooter. I am not sure if simply stopping Geth will eventually restore the connection later on, but it might be worth investigating.

**Comment by 01zaporozhets** [comment]
Hi @aydwi , just wondering if you ever managed to figure out what was causing this in the end ? I am building a new PC and have started observing the same issue. Weirdest thing being that it's almost certainly not the router, as it's plugged into exactly the same router and ethernet cable as my old PC was, and that runs geth just fine for days on end.

**Comment by aydwi** [comment]
@01zaporozhets Unfortunately, I did not find time to investigate this further.

**Comment by scripples** [comment]
Just wanted to pop in to comment that I'm having the same issue. Shortly after syncing my ethernet connection drops, and I'm not able to connect again until I do one of the above fixes. It's also worth noting that swapping to wifi (without restarting the router) does not resolve the issue. I'm trying a couple of other things, including attempting to connect through a VPN, just to see what happens. I'd happily pursue the descriptor situation if someone could point me in the right direction; I don't know how to begin looking for that sort of thing.
