### ISSUE TITLE
trace a pending transaction based on calldata

### ISSUE THREAD

**Issue by Code0x2** [ethereum/go-ethereum#22317]
Is there a feature for the JSON-RPC similar to debug_traceTransaction, which can be used for pending transactions given the call destination and the calldata?

**Comment by rjl493456442** [comment]
I think you can try `debug_traceCall` API which can you specify arbitrary call message based on the requested base state.
Also https://github.com/ethereum/go-ethereum/pull/22245 with this additional PR, you can even override/customize the base state.

**Comment by Code0x2** [comment]
> I think you can try `debug_traceCall` API which can you specify arbitrary call message based on the requested base state.
> Also #22245 with this additional PR, you can even override/customize the base state.

Not too sure how that would be used from json-rpc but looks cool. Ill give traceCall a try and see if it works.

**Comment by MariusVanDerWijden** [comment]
I think `debug_traceCall` provides the necessary functionality. Will close this issue for now, please reopen if something is missing

**Comment by huahuayu** [comment]
@rjl493456442 do I need an archive node for `debug_traceCall`?
