### ISSUE TITLE
flag rpccorsdomain "*" 

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#2231]
rpccorsdomain flag causes geth to hang in the console. The prompt does not appear at startup.

rocky@rocky-Virtual-Machine:~$ geth version
Geth
Version: 1.4.0-unstable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=/home/rocky/goApps
GOROOT=/home/rocky/go

**Comment by bas-vk** [comment]
Could you post the exact command that you use?
And if not already, try to put quotes around the rpccorsdomain that you specify.

E.g. `geth --rpc --rpccorsdomain "*" console`
