### ISSUE TITLE
consensus/ethash: checksum in cache file

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#22311]
It would be nice to have a checksum (like crc64) on ethash cache files. People have been
reporting issues with bad blocks saying "invalid mix digest", and it might be caused by
ethash cache file corruption. 

If we had a checksum in the cache file, we could easily check if the on-disk cache is intact
after mmaping it.

**Comment by ewan15** [comment]
Hey, is this feature still wanted and if so could I be assigned to it?

**Comment by fjl** [comment]
Sure, if you want.

**Comment by HoneyCivik** [comment]
Help wanted

**Comment by holiman** [comment]
Not relevant any more (post-pos)
