### ISSUE TITLE
Github <> Slack integration

### ISSUE THREAD

**Issue by lukerQuant** [ethereum/go-ethereum#22324]
# Rationale

Can you add the slack github integration to this repo (https://slack.github.com/), so that changes can be easily tracked in (other companies) slack. I understand that email notifications can be used, but in my opinion slack notifications provides easier team organisation.

# Implementation

This is a quick app addition to the repo (https://slack.github.com/)

**Comment by MariusVanDerWijden** [comment]
I don't think we need slack integration.
