### ISSUE TITLE
Importing new blocks takes a very long time (~1m)

### ISSUE THREAD

**Issue by TennisBowling** [ethereum/go-ethereum#22328]
#### System information

Geth version: `geth version`
1.9.25-stable
OS & Version: Windows/Linux/OSX
linux
Commit hash : (if `develop`)

#### Expected behaviour

geth syncs the block within a couple ms

#### Actual behaviour

geth takes longer than expected to import (30s-1m)

#### Steps to reproduce the behaviour

run geth normally

#### Backtrace

````
[backtrace]
````

I am using a raspberry pi 4, 8gb of ram, and my cpu is not being pinned. I did the initial sync up to chain head on another desktop pc, then upon bringing it on the raspberry pi, I can't manage to import the ~100 blocks that were added to chain head while I was moving the storage. My ssd is quick enough too.

**Comment by Muggle-Du** [comment]
+1
I have met with very slow synchronization recently (geth v1.9.25)
the average syncing speed is far slower than the speed that new blocks are mined
So I've got about 4700 blocks delay until now
But the I had been able to keep up with the latest block for the last 8 months
this is the logs I got for geth:

**INFO [02-16|13:49:06.991] Imported new chain segment               blocks=1  txs=269  mgas=12.412 elapsed=11.246s    mgasps=1.104 number=11863504 hash="e8e4f4…4ad0d7" age=17h19m48s dirty=254.77MiB
INFO [02-16|13:49:16.044] Imported new chain segment               blocks=1  txs=174  mgas=12.420 elapsed=9.052s     mgasps=1.372 number=11863505 hash="40f649…171885" age=17h19m53s dirty=254.65MiB
INFO [02-16|13:50:07.974] Deep froze chain segment                 blocks=4  elapsed=48.167ms   number=11773506 hash="8b1759…c146b8"
INFO [02-16|13:50:07.977] Imported new chain segment               blocks=2  txs=426  mgas=24.901 elapsed=51.933s    mgasps=0.479 number=11863507 hash="d4f545…5eb1cb" age=17h20m15s dirty=254.71MiB
INFO [02-16|13:50:19.109] Imported new chain segment               blocks=3  txs=554  mgas=37.387 elapsed=11.131s    mgasps=3.359 number=11863510 hash="82f417…1d4d17" age=17h19m43s dirty=255.09MiB
INFO [02-16|13:50:57.839] Imported new chain segment               blocks=3  txs=525  mgas=37.432 elapsed=38.730s    mgasps=0.966 number=11863513 hash="873706…96fafb" age=17h19m50s dirty=254.76MiB
INFO [02-16|13:51:44.015] Imported new chain segment               blocks=1  txs=207  mgas=12.456 elapsed=46.176s    mgasps=0.270 number=11863514 hash="53c47c…fc4a9a" age=17h20m32s dirty=254.76MiB
INFO [02-16|13:51:45.927] Deep froze chain segment                 blocks=7  elapsed=1.933s     number=11773513 hash="0124a1…f08d7d"
INFO [02-16|13:52:17.863] Imported new chain segment               blocks=1  txs=160  mgas=12.455 elapsed=33.847s    mgasps=0.368 number=11863515 hash="bb1fb2…912966" age=17h20m42s dirty=254.75MiB
INFO [02-16|13:52:26.752] Imported new chain segment               blocks=1  txs=197  mgas=12.455 elapsed=8.888s     mgasps=1.401 number=11863516 hash="2a0742…a23d74" age=17h20m42s dirty=254.73MiB
WARN [02-16|13:52:30.042] Checkpoint challenge timed out, dropping id=f5704f9ca33b735c conn=staticdial addr=161.117.5.113:30303   type=Geth/v1.9.23-stable-...
INFO [02-16|13:52:51.180] Imported new chain segment               blocks=2  txs=441  mgas=24.942 elapsed=24.428s    mgasps=1.021 number=11863518 hash="6972dc…b3276d" age=17h20m22s dirty=254.86MiB
INFO [02-16|13:52:52.162] Deep froze chain segment                 blocks=4  elapsed=1.038s     number=11773517 hash="2d1cd7…03e083"
INFO [02-16|13:52:53.411] Writing clean trie cache to disk         path=/root/geth/triecache threads=1
INFO [02-16|13:52:53.719] Regenerated local transaction journal    transactions=0 accounts=0
INFO [02-16|13:52:54.370] Persisted the clean trie cache           path=/root/geth/triecache elapsed=958.996ms
INFO [02-16|13:53:00.701] Imported new chain segment               blocks=1  txs=297  mgas=12.473 elapsed=9.521s     mgasps=1.310 number=11863519 hash="7bf281…eaa5e7" age=17h20m27s dirty=255.04MiB
INFO [02-16|13:53:50.432] Imported new chain segment               blocks=1  txs=195  mgas=12.481 elapsed=49.730s    mgasps=0.251 number=11863520 hash="96494c…c87c80" age=17h20m29s dirty=255.05MiB
INFO [02-16|13:53:52.589] Deep froze chain segment                 blocks=3  elapsed=426.368ms  number=11773520 hash="3b9083…52c107"
INFO [02-16|13:54:15.470] Imported new chain segment               blocks=2  txs=346  mgas=24.965 elapsed=25.037s    mgasps=0.997 number=11863522 hash="46e63e…cfc7eb" age=17h20m42s dirty=254.64MiB
INFO [02-16|13:54:46.721] Imported new chain segment               blocks=2  txs=374  mgas=24.974 elapsed=31.251s    mgasps=0.799 number=11863524 hash="9df32b…22331e" age=17h20m52s dirty=254.68MiB
INFO [02-16|13:54:53.465] Deep froze chain segment                 blocks=6  elapsed=875.564ms  number=11773526 hash="e3c2aa…cd9363"
INFO [02-16|13:56:57.667] Imported new chain segment               blocks=3  txs=627  mgas=37.438 elapsed=2m10.945s  mgasps=0.286 number=11863527 hash="7898c6…e652da" age=17h22m39s dirty=254.85MiB
INFO [02-16|13:57:07.381] Imported new chain segment               blocks=3  txs=501  mgas=37.463 elapsed=9.714s     mgasps=3.856 number=11863530 hash="3c12d8…80e271" age=17h22m27s dirty=254.69MiB
INFO [02-16|13:57:17.912] Imported new chain segment               blocks=2  txs=401  mgas=24.960 elapsed=10.530s    mgasps=2.370 number=11863532 hash="deb66a…b1694e" age=17h21m54s dirty=254.85MiB
INFO [02-16|13:57:28.360] Imported new chain segment               blocks=2  txs=331  mgas=24.918 elapsed=10.448s    mgasps=2.385 number=11863534 hash="f7394f…41f0ce" age=17h21m44s dirty=254.66MiB
INFO [02-16|13:57:37.823] Imported new chain segment               blocks=3  txs=545  mgas=37.441 elapsed=9.462s     mgasps=3.957 number=11863537 hash="4c69fa…433071" age=17h21m7s  dirty=254.76MiB
INFO [02-16|13:57:47.197] Imported new chain segment               blocks=3  txs=480  mgas=37.396 elapsed=9.374s     mgasps=3.989 number=11863540 hash="efc96c…110968" age=17h20m26s dirty=254.91MiB
INFO [02-16|13:57:56.903] Deep froze chain segment                 blocks=15 elapsed=1.094s     number=11773541 hash="1561f0…056960"**

How can I fix this?

**Comment by karalabe** [comment]
Based on your logs, you have Geth 1GB of cache allowance in total. That won't be enough for a mainnet node.

**Comment by TennisBowling** [comment]
hey @karalabe and @Muggle-Du! I was using a raspberry pi and my storage was an external ssd which was formatted (and originally synced with) a NTFS filesystem, which runs very slow on linux. I formatted it into ext4 and started syncing again and no longer slow.

**Comment by Muggle-Du** [comment]
> Based on your logs, you have Geth 1GB of cache allowance in total. That won't be enough for a mainnet node.

Thanks, I'll set 4096 for cache . 
By the way, what does "dirty " in the logs mean

**Comment by Muggle-Du** [comment]
> > Based on your logs, you have Geth 1GB of cache allowance in total. That won't be enough for a mainnet node.
> 
> Thanks, I'll set 4096 for cache .
> By the way, what does "dirty " in the logs mean

And after I restarted the geth with "--cache 4096", the syncing speed didn't get improved

**INFO [02-17|03:48:52.174] Looking for peers                        peercount=2 tried=12 static=823
INFO [02-17|03:49:07.835] Downloader queue stats                   receiptTasks=0 blockTasks=155 itemSize=8.83KiB throttle=7426
INFO [02-17|03:52:10.907] Looking for peers                        peercount=1 tried=18 static=823
INFO [02-17|03:52:21.378] Looking for peers                        peercount=2 tried=7  static=823
INFO [02-17|03:52:24.566] Imported new chain segment               blocks=1 txs=259 mgas=12.469 elapsed=3m16.731s mgasps=0.063 number=11868585 hash="81cf73…393c11" age=12h39m43s dirty=1.73MiB
INFO [02-17|03:52:32.114] Looking for peers                        peercount=2 tried=17 static=823
INFO [02-17|03:52:49.524] Imported new chain segment               blocks=1 txs=204 mgas=12.452 elapsed=24.957s   mgasps=0.499 number=11868586 hash="76377b…282b92" age=12h39m10s dirty=3.48MiB
INFO [02-17|03:52:49.525] Downloader queue stats                   receiptTasks=0 blockTasks=2152 itemSize=40.72KiB throttle=1610
INFO [02-17|03:53:00.203] Deep froze chain segment                 blocks=2 elapsed=761.687ms number=11778586 hash="4d7057…c68ac6"
INFO [02-17|03:53:17.020] Imported new chain segment               blocks=1 txs=271 mgas=12.466 elapsed=27.494s   mgasps=0.453 number=11868587 hash="ac236a…0e40f8" age=12h39m28s dirty=5.45MiB
INFO [02-17|03:54:31.425] Looking for peers                        peercount=2 tried=4  static=823
INFO [02-17|03:54:37.844] Imported new chain segment               blocks=1 txs=147 mgas=12.476 elapsed=1m20.823s mgasps=0.154 number=11868588 hash="d3148c…04e71a" age=12h40m23s dirty=6.90MiB
INFO [02-17|03:54:41.640] Looking for peers                        peercount=2 tried=13 static=823
INFO [02-17|03:54:53.620] Looking for peers                        peercount=2 tried=21 static=823
INFO [02-17|03:55:01.300] Deep froze chain segment                 blocks=2 elapsed=1.095s    number=11778588 hash="624661…af032a"
INFO [02-17|03:55:06.425] Looking for peers                        peercount=2 tried=8  static=823
WARN [02-17|03:55:19.522] Served eth_call                          reqid=58 t=7.369886009s err="execution aborted (timeout = 5s)"
WARN [02-17|03:55:24.923] Served eth_call                          reqid=69 t=5.398842345s err="execution aborted (timeout = 5s)"
WARN [02-17|03:55:35.591] Served eth_call                          reqid=82 t=10.667633561s err="execution aborted (timeout = 5s)"
WARN [02-17|03:55:52.210] Served eth_call                          reqid=105 t=13.872953346s err="execution aborted (timeout = 5s)"
WARN [02-17|03:56:00.771] Served eth_call                          reqid=139 t=8.559749188s  err="execution aborted (timeout = 5s)"
WARN [02-17|03:56:13.978] Served eth_call                          reqid=245 t="254.23µs"    err="execution reverted"
WARN [02-17|03:56:27.475] Served eth_call                          reqid=277 t=5.485536793s  err="execution aborted (timeout = 5s)"
WARN [02-17|03:56:31.483] Checkpoint challenge timed out, dropping id=cf34821586f4db46 conn=staticdial addr=47.107.113.245:30303 type=Geth/v1.9.24-stable-...
WARN [02-17|03:56:51.319] Served eth_call                          reqid=348 t=5.19359171s   err="execution aborted (timeout = 5s)"
INFO [02-17|03:57:13.332] Imported new chain segment               blocks=1 txs=106 mgas=12.450 elapsed=2m35.488s mgasps=0.080 number=11868589 hash="f63474…f7cf2e" age=12h42m57s dirty=8.23MiB
INFO [02-17|03:58:03.356] Deep froze chain segment                 blocks=2 elapsed=2.055s    number=11778590 hash="54277d…d9b829"
INFO [02-17|03:58:38.313] Imported new chain segment               blocks=2 txs=364 mgas=24.950 elapsed=1m24.980s mgasps=0.294 number=11868591 hash="9e9862…5222b8" age=12h44m11s dirty=11.24MiB
WARN [02-17|03:58:49.434] Checkpoint challenge timed out, dropping id=6d954e39513b2e9d conn=staticdial addr=8.210.14.97:30303    type=Geth/v1.9.18-stable-...
INFO [02-17|04:00:03.576] Imported new chain segment               blocks=1 txs=181 mgas=12.469 elapsed=1m25.263s mgasps=0.146 number=11868592 hash="94db42…54f266" age=12h45m29s dirty=13.01MiB
INFO [02-17|04:01:05.371] Deep froze chain segment                 blocks=2 elapsed=2.014s    number=11778592 hash="af7416…7c01a9"
INFO [02-17|04:02:13.536] Imported new chain segment               blocks=1 txs=162 mgas=12.459 elapsed=2m9.959s  mgasps=0.096 number=11868593 hash="90ad24…ad32c1" age=12h47m23s dirty=14.72MiB
WARN [02-17|04:03:26.345] Served eth_call                          reqid=3947 t=6.556733677s  err="execution aborted (timeout = 5s)"**

**Comment by TennisBowling** [comment]
@Muggle-Du what os are you on? what cpu do you have? what storage do you have?

**Comment by karalabe** [comment]
It takes a while for caches to get loaded with data.

**Comment by Muggle-Du** [comment]
> @Muggle-Du what os are you on? what cpu do you have? what storage do you have?

system info: Ubuntu 18
cpu: 64 cores server cpu 
storage: 252G SSD

**Comment by TennisBowling** [comment]
is your io slow? what filesystem is your ssd formatted with

**Comment by MariusVanDerWijden** [comment]
@Muggle-Du I'll close this issue for now. If you're still experience these long import times, please open a new issue!
Thanks @TennisBowling for reporting that execution speed increased when switching from NTFS to Ext4
