### ISSUE TITLE
"solc" is not found in $PATH

### ISSUE THREAD

**Issue by sham789** [ethereum/go-ethereum#22325]
#### System information

Geth version: Docker image with tag `ethereum/client-go:alltools-latest`
OS & Version: `Linux ubuntu-s-1vcpu-2gb-tor1-01 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
Commit hash : [`43458f`](https://github.com/Gravity-Tech/gateway/commit/43458f24873fd3df90b392a1c17785883875f2a0)

#### Expected behaviour

Successful *.abi files generation due to a fact that correct version of solc is already installed.

#### Actual behaviour

Fatal: Failed to build Solidity contract: exec: "solc": executable file not found in $PATH
Fatal: Failed to build Solidity contract: exec: "solc": executable file not found in $PATH
make: *** [Makefile:7: ethereum] Error 1

#### Steps to reproduce the behaviour

1. Visit https://github.com/Gravity-Tech/gateway/tree/add-docker
2. git clone https://github.com/Gravity-Tech/gateway.git
3. cd gateway/
4. git checkout add-docker
5. docker build -t gateway-tests .
6. docker run gateway-tests

**Comment by MariusVanDerWijden** [comment]
I think you don't have solc installed on your machine. 
To check you can execute `which solc`.

**Comment by sham789** [comment]
Hi! It's docker environment, and solc is installed, you can installation directive in Dockerfile.

**Comment by sham789** [comment]
`ENTRYPOINT cd workdir/ && npm i -g solc@0.6.11 && make waves && make ethereum`

**Comment by karalabe** [comment]
This is not a bug in Geth. Geth only tries to use `solc` from the $PATH. It's up to you to ensure it's available and reachable.
