### ISSUE TITLE
Not suitable peers in geth 1.9.25 and not syncing 

### ISSUE THREAD

**Issue by Smartboxweb98** [ethereum/go-ethereum#22335]
Geth version: `geth version` 1.9.25
OS & Version: Windows
Commit hash : (if `develop`)

geth node does not synchronize ... and on the console an error appears (not suitable peers) even with peers at 0

**Comment by karalabe** [comment]
Without any logs or any details, there's nothing we can do.

**Comment by Smartboxweb98** [comment]
C:\Users\Administrator>geth --ipcdisable --syncmode light  --http --allow-insecure-unlock --rpccorsdomain "*" --maxpeers 0 --http.port 7545 --bootnodes enode://4e281dd8217e3da401d3295d8abd4855b2458825f8d7761d8485a9c71cf0583bf78d96189a188299b6f74c98c278a86ee84df01d910b2dd5cb3612b37a8bce31@127.0.0.1:30303
INFO [02-17|11:02:44.602] Starting Geth on Ethereum mainnet...
INFO [02-17|11:02:44.620] Dropping default light client cache      provided=1024 updated=128
INFO [02-17|11:02:44.624] Maximum peer count                       ETH=0 LES=10 total=0
WARN [02-17|11:02:44.630] The flag --rpccorsdomain is deprecated and will be removed in the future, please use --http.corsdomain
INFO [02-17|11:02:44.697] Starting peer-to-peer node               instance=Geth/v1.9.14-stable-6d74d1e5/windows-amd64/go1.14.2
INFO [02-17|11:02:44.703] Allocated cache and file handles         database=C:\Users\Administrator\AppData\Local\Ethereum\geth\lightchaindata cache=64.00MiB handles=8192
INFO [02-17|11:02:44.723] Allocated cache and file handles         database=C:\Users\Administrator\AppData\Local\Ethereum\geth\lespay cache=16.00MiB handles=16
INFO [02-17|11:02:44.743] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Engine: ethash}"
INFO [02-17|11:02:44.756] Disk storage enabled for ethash caches   dir=C:\Users\Administrator\AppData\Local\Ethereum\geth\ethash count=3
INFO [02-17|11:02:44.765] Disk storage enabled for ethash DAGs     dir=C:\Users\Administrator\AppData\Local\Ethash count=2
INFO [02-17|11:02:44.774] Added trusted checkpoint                 block=10027007 hash="ebff61…08400a"
INFO [02-17|11:02:44.780] Loaded most recent local header          number=11510911 hash="d5ce88…a6f19b" td=19610548154456611896478 age=1mo3w4d
INFO [02-17|11:02:44.787] Configured checkpoint registrar          address=0x9a9070028361F7AAbeB3f2F2Dc07F82C4a98A02a signers=5 threshold=2
INFO [02-17|11:02:44.807] UDP listener up                          net=enode://4e281dd8217e3da401d3295d8abd4855b2458825f8d7761d8485a9c71cf0583bf78d96189a188299b6f74c98c278a86ee84df01d910b2dd5cb3612b37a8bce31@[::]:30303
WARN [02-17|11:02:44.820] Light client mode is an experimental feature
INFO [02-17|11:02:44.827] New local node record                    seq=22 id=42760ca4642f7ec3 ip=127.0.0.1 udp=30303 tcp=30303
INFO [02-17|11:02:44.837] Started P2P networking                   self=enode://4e281dd8217e3da401d3295d8abd4855b2458825f8d7761d8485a9c71cf0583bf78d96189a188299b6f74c98c278a86ee84df01d910b2dd5cb3612b37a8bce31@127.0.0.1:30303
INFO [02-17|11:02:44.835] HTTP endpoint opened                     url=http://127.0.0.1:7545/ cors=* vhosts=localhost
WARN [02-17|11:04:49.157] Served eth_coinbase                      conn=127.0.0.1:61326 reqid=3 t=3.0001ms err="mining is not supported in light mode"
WARN [02-17|11:04:52.183] Served eth_getBlockByNumber              conn=127.0.0.1:61326 reqid=6 t=3.0009961s err="no suitable peers available"
WARN [02-17|11:05:25.727] Served eth_getBalance                    conn=127.0.0.1:61326 reqid=8 t=3.0010265s err="getDeleteStateObject (457d9cc7f3da0aa72bc985cc6f1d8b3200b5f68d) error: no suitable peers available"
   



### console     #####


C:\Users\Administrator> geth attach  http://127.0.0.1:7545
Welcome to the Geth JavaScript console!

 modules: eth:1.0 net:1.0 rpc:1.0 web3:1.0

> web3.fromWei(eth.getBalance("0x457d9cc7f3XXXXXXXXXXXXXX"),'ether')
Error: getDeleteStateObject (457d9cc7f3da0aa72bc98XXXXXXXXXXXXXXX) error: no suitable peers available
        at web3.js:6347:37(47)
        at web3.js:5081:62(37)
        at <eval>:1:28(7)

>

**Comment by holiman** [comment]
`--syncmode light` means that you'll not actually run a full node, but require a LES server to provide data for you on the fly. The error message is simply that you haven't found a suitable server to serve you data. It's a tragedy of the commons, finding someone who'll donate processing time for free isn't easy. 

`--allow-insecure-unlock` -- why do this? It's an explicitly insecure thing to do, please avoid it, for your own best. 
`--maxpeers 0` -- how can you possibly hope to find any peers if you set the max peers to `0` ? 
`--bootnodes enode://4e281dd8217e3da401d3295d8abd4855b2458825f8d7761d8485a9c71cf0583bf78d96189a188299b6f74c98c278a86ee84df01d910b2dd5cb3612b37a8bce31@127.0.0.1:30303` 

This also doesn't make sense, as : 
```
INFO [02-17|11:02:44.807] UDP listener up                          net=enode://4e281dd8217e3da401d3295d8abd4855b2458825f8d7761d8485a9c71cf0583bf78d96189a188299b6f74c98c278a86ee84df01d910b2dd5cb3612b37a8bce31@[::]:30303
``` 

You're setting the bootnode (a node to connect to at start-up) as your own id. It simply makes no sense
