### ISSUE TITLE
GETH Trusted, Static and Bootstrap Peers

### ISSUE THREAD

**Issue by ceds** [ethereum/go-ethereum#22348]
I've been struggling for a long time trying to get my GETH node to only accept peers that I specify.  For some reason it never works as expected.

I selected 100 peers that I would like my GETH node to use.  Those 100 peers are added in the config.toml file as BootstrapNodes, BootstrapNodesV5, TrustedNodes and StaticNodes.  I also set NoDiscovery to false.

If I pull the peers after using such configuration, GETH still has about 50% peers that are not in my list of 100 nodes.

How is this possible?  What am I missing?

**Comment by karalabe** [comment]
You can disable discovery (set nodiscover to `true`!), but that doesn't prevent others from connecting to you via IP if your data already leaked into the network. You'd need to regenerate your node key to have an unleaked one.

You can specify your desired peers as trusted, and they will always be allowed in no matter how full your node is. You could specify the desired peers as static too to dial them, but the max peer count limit isn't allowed to be exceeded by them.

**Comment by aniquejapan** [comment]
How can i set peer only to static? Also wanted to know by doing this geth speed will be slow receiving and sending tx.

**Comment by ceds** [comment]
> You can disable discovery (set nodiscover to `true`!), but that doesn't prevent others from connecting to you via IP if your data already leaked into the network. You'd need to regenerate your node key to have an unleaked one.
> 
> You can specify your desired peers as trusted, and they will always be allowed in no matter how full your node is. You could specify the desired peers as static too to dial them, but the max peer count limit isn't allowed to be exceeded by them.

Thanks, that explains what I'm seeing.  Will regenerate node key if I don't want to be discovered.

**Comment by ceds** [comment]
Answer by aniquejapan resolved this question

**Comment by zhengger** [comment]
> You can specify your desired peers as trusted

 "You can specify your desired peers as trusted", how to set a peer as trusted or not?
 Thanks!

**Comment by FomoApe** [comment]
> You can disable discovery (set nodiscover to `true`!), but that doesn't prevent others from connecting to you via IP if your data already leaked into the network. You'd need to regenerate your node key to have an unleaked one.

Can allowing any node to discover/connect to my node be harmful? If so how and where can I find out more info about this as I have a new node that I spent a lot of money on?

> You can specify your desired peers as trusted, and they will always be allowed in no matter how full your node is. You could specify the desired peers as static too to dial them, but the max peer count limit isn't allowed to be exceeded by them.

Why would I want to use trusted peers?
