### ISSUE TITLE
RISC-V support

### ISSUE THREAD

**Issue by DavidBurela** [ethereum/go-ethereum#22354]
# Rationale

RISC-V CPUs are becoming a hot topic, especially in the conversation of decentralization + Open Hardware.
Ensuring that go-ethereum can compile for the target cpu architecture would be a good enhancement to help with an open network.

# Implementation

**Current status:**
Because it has been written in Golang, it is already mostly CPU agnostic.
But right now it does not compile on the current version of Go `1.15.8`, as not all of the included libraries used by geth have had RISC-V support

**Getting it working:**
Compiling the latest version of Golang available on GitHub does successfully compile and run geth. I was able to have it compile, connect, and start syncing with the network on an emulated RISC-V cpu architecture.

I have capture the research and steps it took to get working https://blog.davidburela.com/2020/12/03/ethereum-on-risc-v/

**Steps:**
- [Preferred] Use an emulated RISC-V environment via QEMU  
  1. [Example of how to get set up on Debian or Ubuntu](https://blog.davidburela.com/2020/11/15/emulating-risc-v-debian-on-wsl2.html)
  1. [Docker image that has QEMU preconfigured for RISC-V](https://github.com/DavidBurela/riscv-emulator-docker-image)
- [Optional] It is possible to cross compile. But go-ethereum requires a few extra build tools and libraries that need to be installed to support RISC-V (see blog post)

1. Install golang (to use as a boot strap)
1. Pull latest golang from github, and compile it
1. git clone go-ethereum
1. Compile go-ethereum with `-arch=riscv64` flag
1. Can now run the RISC-V binary and start syncing with the network

# Next steps

Creating this issue to track support as the golang support is updated. It might be a case of simply waiting for the next major version of golang that uses the current working version on GitHub.

**Comment by Shin-Asi** [comment]
Great work. The future is definitely RISC-V open source HW architecture David. Congratulations.

**Comment by ligi** [comment]
As the upstream issue is merged it should compile now - can we close this issue then?

**Comment by karalabe** [comment]
Go 1.16 was released a while ago and it contains the fix you linked https://github.com/golang/go/issues/36641. Is there anything to do now?

**Comment by MariusVanDerWijden** [comment]
Thank you very much for your work @DavidBurela!

**Comment by DavidBurela** [comment]
You are correct, `go 1.16` source release was 9 days ago. But isn't on package management systems (apt, etc) which is why I missed it.
https://github.com/golang/go/releases/tag/go1.16

I tried building the latest `go-ethereum` source, on a RISC-V system, using `go 1.16`, and I **can confirm it does now build successfully.**

![image](https://user-images.githubusercontent.com/1320729/109160256-aa0c5980-77c9-11eb-9c57-269efb667f5b.png)

**Comment by DavidBurela** [comment]
**Next steps:**
- Should we add it as a standard release binary `linux/riscv64`?
- Do we need to wait until the build pipeline upgrades to `go 1.16`?

**Comment by karalabe** [comment]
We're already building with Go 1.16.
I don't think we want to add support to an exotic platform. We can definitely reconsider it if RISC V takes off, but until then I don't really see a reason to add maintenance overhead.

**Comment by karalabe** [comment]
Wrt not being on APT, Go doesn't have official PPA distributions, so you can forget about that. You can either go with snap packages (done by the previous maintainer of the PPAs), download prebuilds or build from source if you want a reasonable new Go release.

**Comment by DavidBurela** [comment]
Closing this issue.
Codebase now builds with latest version of Golang.

Later if it makes sense to create an Epic to track support, it can be recreated then.
