### ISSUE TITLE
Benchmarks for Increasing Block Gas Limit

### ISSUE THREAD

**Issue by Mister-Meeseeks** [ethereum/go-ethereum#22366]
# Rationale

Team lead Peter Szilagyi has cited Geth client performance as the main reason not to increase block size gas limit. Major miners appear to be [listening to this advice](https://twitter.com/sparkpool_eth/status/1357753534033330178). However it's pretty clear that there's a major gas shortage, that's resulting in millions per day in unnecessary gas fees. Therefore improving Geth performance would literally be worth hundreds of millions to the community. 

Based on this, can we please define and build a performance benchmark suite for transparently determining what the safe block gas limit is. That way instead of just going off the core team's gut feeling, we can all point the current client code at the performance suite, run it through with the proposed block size and get a simple, transparent, easy to interpret yay or nay. If we pre-commit to this benchmark it makes the project much more transparent, and eliminates the inside baseball and back channeling between core devs and miners.

Even more importantly, it gives clear feedback and would-be performance improvements. Automated performance benchmarks built into the Geth project, would invite many more people to contribute performance improvements. It would be much simpler for pull requests to clearly show how much they increase block size capacity.

# Implementation

The performance benchmark suites should stress all the pain points that come with larger block sizes. That includes validation time, memory usage, bandwidth, simulated uncle rate, pre-mine commit, storage, disk I/O. It should also include tunable parameters for different runtime environments. Obviously the most important is simulated block size. But other components might be cache size, network connection, the number of CPUs, etc. The transaction data used to run the performance benchmark should probably be pulled as close as possible from the live block chain. Periodically that may need to be updated, as the contracts that run on chain change over time.

**Comment by karalabe** [comment]
You can just use mainnet as your benchmark. See how long it takes to sync it, see how fast the state grows, see how much time a block import takes while in sync. Though the catch is that we need to cover the worst possible case, not the average case.

**Comment by Mister-Meeseeks** [comment]
Thanks for the explanation. I'm currently running a custom fork that simulates an expanded pending block against mainnet. I've already got some benchmarks on block validation time.

I'm having trouble imagining how to benchmark state growth against mainnet. Obviously, all you can do is fork on the next pending block. Do you think it makes sense to compare the per-block difference in state growth, then extrapolate to long-term rates?

**Comment by Prygan** [comment]
@karalabe Would it be possible to have some insights on how one can measure state size on a local node? (excluding data not related to the state itself)

**Comment by karalabe** [comment]
Sorry for not going into too many details before, was trying to not reveal too much of the DoS problems.

Essentially currently it takes 0.3s to execute a 25M gas block with all the Geth optimizations in place. Without snapshots, it takes 1.5s. The code is available at https://blog.ethereum.org/2021/05/18/eth_state_problems/ .

This attack is IMHO a fairly good worst case scenario for benchmarking apart of doing a mainnet sync.
