### ISSUE TITLE
Question: How can I make my new variable specify with interger like gaslimit?

### ISSUE THREAD

**Issue by fantasticWolff** [ethereum/go-ethereum#22364]
I add a new variable TimeLimit

core/types/transaction.go
```
type txdata struct {
	AccountNonce uint64          `json:"nonce"    gencodec:"required"`
	Price        *big.Int        `json:"gasPrice" gencodec:"required"`
	GasLimit     uint64          `json:"gas"      gencodec:"required"`
	TimeLimit    uint64          `json:"time"     gencodec:"required"`
	Recipient    *common.Address `json:"to"       rlp:"nil"` // nil means contract creation
	Amount       *big.Int        `json:"value"    gencodec:"required"`
	Payload      []byte          `json:"input"    gencodec:"required"`

	// Signature values
	V *big.Int `json:"v" gencodec:"required"`
	R *big.Int `json:"r" gencodec:"required"`
	S *big.Int `json:"s" gencodec:"required"`

	// This is only used when marshaling to JSON.
	Hash *common.Hash `json:"hash" rlp:"-"`
}
```
internal/ethapi/api.go
```
type SendTxArgs struct {
	From     common.Address  `json:"from"`
	To       *common.Address `json:"to"`
	Gas      *hexutil.Uint64 `json:"gas"`
	Time     *hexutil.Uint64 `json:"time"`
	GasPrice *hexutil.Big    `json:"gasPrice"`
	Value    *hexutil.Big    `json:"value"`
	Nonce    *hexutil.Uint64 `json:"nonce"`
	// We accept "data" and "input" for backwards-compatibility reasons. "input" is the
	// newer name and should be preferred by clients.
	Data  *hexutil.Bytes `json:"data"`
	Input *hexutil.Bytes `json:"input"`
}
```
Then,
when I do below in geth
```
eth.sendTransaction({from:"0xb58042d7bfc549933494e00c25cb00fadba8453a", to:"0xb58042d7bfc549933494e00c25cb00fadba8453a", value: web3.toWei(0.05, "ether"), gas:21000, time:16});
```
I get
```
Error: invalid argument 0: json: cannot unmarshal non-string into Go struct field SendTxArgs.time of type hexutil.Uint64
```

I can only do time:"0x10" (transaction send successfully)
```
eth.sendTransaction({from:"0xb58042d7bfc549933494e00c25cb00fadba8453a", to:"0xb58042d7bfc549933494e00c25cb00fadba8453a", value: web3.toWei(0.05, "ether"), gas:21000, time:"0x10"});
```
![Screenshot from 2021-02-22 22-28-13](https://user-images.githubusercontent.com/29246352/108721808-63b2c280-755d-11eb-9242-9cc053a5dcf7.png)

 How can I make my new variable specify with interger like gaslimit?

**Comment by karalabe** [comment]
If you are forking Geth to add new feature, we won't be able to support you.

**Comment by fjl** [comment]
If you add a new field in transaction, you need to re-generate the MarshalJSON/UnmarshalJSON code using `go generate ./core/types`

**Comment by fjl** [comment]
Oh, wait, now I understand what you want to do. The integer to hex conversion happens in web3.js, the RPC API only accepts hex.

**Comment by fantasticWolff** [comment]
> Oh, wait, now I understand what you want to do. The integer to hex conversion happens in web3.js, the RPC API only accepts hex.

"gasPrice" and "gas" can be specified in both hex and integer
I want my "time" can be specified in both hex and integer too

Before 
I use  *hexutil.Uint64 `json:"time"`, it can only be specified in hex
type SendTxArgs struct {
	Gas      *hexutil.Uint64  `json:"gas"`
	Time    *hexutil.Uint64  `json:"time"`
}

Now
I use  *uint64 `json:"timeLimit"`, it can only be specified in integer
type SendTxArgs struct {
	Gas           *hexutil.Uint64 `json:"gas"`
	TimeLimit *uint64             `json:"timeLimit"`
}

gasPrice:987654321, gas:123456789, timeLimit:888888
![image](https://user-images.githubusercontent.com/29246352/109146089-55071e00-779e-11eb-894e-afc15fd95685.png)

gasPrice:"0x200000", gas:"0x100000", timeLimit:777777
![image](https://user-images.githubusercontent.com/29246352/109146568-f2fae880-779e-11eb-8b99-e8327cd10d1e.png)

**Comment by karalabe** [comment]
The console is running a web3.js wrapper. The gas fields are interpreted and reencoded by web3. It's not done by Geth.

**Comment by fantasticWolff** [comment]
> The console is running a web3.js wrapper. The gas fields are interpreted and reencoded by web3. It's not done by Geth.

Thank you!
