### ISSUE TITLE
Store blockchain in AppData Local, not AppData Roaming on Windows.is

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/go-ethereum#2237]
When connected to a domain, everything in the `Roaming` application data folder will be synchronized to the network on logout.  At the moment, this means the entire blockchain will attempt to be copied over the network on logout.  Most domains setup Roaming quotas to prevent user applications from destroying the network, in this case using Geth will cause the the user to be unable to sync their roaming profile on logout which can have significant negative side effects on other applications that depend on roaming profile syncing.

The correct location for this sort of thing would either be `%PROGRAMDATA%` if you want to allow multiple users on a shared machine share the data (all users will be able to read and write) or `%APPDATA%/Local` if you want only the current user to be able to access the data.  `%PROGRAMDATA%` is a better choice for very large files like this if you have some other security mechanism in place to ensure that file tampering isn't a problem since it means each user doesn't have to download their own entire block chain.  However, if verifying the entire blockchain is not easy/cheap, then `%APPDATA%/Local` is the correct choice.

Perhaps there is some way to have Geth store the blockchain in `%PROGRAMDATA%` and only store some kind of verification hash in `%APPDATA%/Local` that would allow them to quickly identify whether or not the blockchain has been tampered with?

Reference: http://superuser.com/a/150014/401511

Code: https://github.com/ethereum/go-ethereum/blob/bzz/common/path.go#L91

**Comment by MicahZoltu** [comment]
I haven't personally used geth lately, but unless someone has explicitly addressed this, it isn't one of those things that "goes away on its own as to codebase is iterated on".  Recommend keeping this bug active.

**Comment by holiman** [comment]
Changing this also involves Mist, which (at least historically) has sometimes interacted directly with the keystore folder (although I don't remember exactly under what circumstances, maybe during import). cc @evertonfraga what would happen if we move the keystore ?
