### ISSUE TITLE
`debug.traceTransaction` with callTracer Doesn't Work On Pending (Non-Existent) Txns

### ISSUE THREAD

**Issue by m-e-r-k-l-e-root** [ethereum/go-ethereum#22371]
#### System information
Geth version: v1.9.25
OS & Version: Ubuntu 18.04
Node Type: Full (not fast synced)

#### Expected behaviour
_debug.traceTransaction_ called using tracer _callTracer_ to properly trace calls on txns that are pending (i.e. non-existent).

#### Actual behaviour
_debug.traceTransaction_ when called using tracer _callTracer_ on a txn that is pending (i.e. non-existent) returns an error indicating that the txn is not found.

#### Steps to reproduce the behaviour
Call _debug.traceTransaction_ while specifying a txn hash that is associated with a pending (non-existent) txn.

#### Additional information
I was curious if writing a different tracer, i.e. possibly building on top of the tracer _callTracer_ would achieve what was described above? If not, what suggestions do you have regarding how to trace a txn that is still in a pending state? Thanks.

**Comment by ligi** [comment]
Can you give some more information about your use-case?

**Comment by ligi** [comment]
also please see #22197

**Comment by holiman** [comment]
So, what you want, is it the same thing as  (pseudo-code)
```js

var tx = txpool.pending(...)[0]
debug.traceCall({ from:  tx.from, to: tx.to, data: tx.data } )

```

which would execute some transaction on top of the current state. 

OR 
Do you want to execute the entire 'pending state', and then trace a transaction on top?

**Comment by m-e-r-k-l-e-root** [comment]
> So, what you want, is it the same thing as (pseudo-code)
> 
> ```js
> var tx = txpool.pending(...)[0]
> debug.traceCall({ from:  tx.from, to: tx.to, data: tx.data } )
> ```
> 
> which would execute some transaction on top of the current state.
> 
> OR
> Do you want to execute the entire 'pending state', and then trace a transaction on top?

Yes, the pseudocode you've provided is an entirely valid representation of what I am attempting to achieve. We're primarily attempting to get this functionality working to trace calls present within a transaction prior to the transaction being executed in order to provide in depth visualization of call traces pertaining to a transaction prior to submission/execution (a feature being implemented in our block explorer).

We've been able to implement this feature already for existing/executed transactions using the following:

`debug.traceTransaction("<hash>", {tracer: "callTracer"});`

But, as mentioned above when calling _debug.traceTransaction_ on a txn hash associated with a non executed/pending txn results in _debug.traceTransaction_ returning an error indicating that the txn hash could not be found.

**Comment by rjl493456442** [comment]
`debug.traceTransaction("<hash>", {tracer: "callTracer"});` It's only for the included transactions, not for pending.

So do you think the `traceCall` API can solve your issues? Can I close it?

**Comment by m-e-r-k-l-e-root** [comment]
> `debug.traceTransaction("<hash>", {tracer: "callTracer"});` It's only for the included transactions, not for pending.
> 
> So do you think the `traceCall` API can solve your issues? Can I close it?

Yes this issue can be closed, `traceCall` was suitable for my use case.
