### ISSUE TITLE
Export cmd should fail if chain length is shorter than input range

### ISSUE THREAD

**Issue by s1na** [ethereum/go-ethereum#22383]
#### System information

Geth version: `1.9.24-unstable`
OS & Version:Linux
Commit hash : `0391daf9abef68e5da078a24f7d214270dbb484d`

#### Expected behaviour

After fetching the tip of the chain from db, `export` should compare that against the block range provided by user and fail if range exceeds the local chain.

#### Actual behaviour

It starts exporting block batches and fails once it reaches the tip of local chain with `Fatal: Export error: export failed on #3863673: not found`.

#### Steps to reproduce the behaviour

For e.g. `geth export chain.gz 0 15000000`

**Comment by MariusVanDerWijden** [comment]
Maybe specifying a future block can just be interpreted as "give me the whole chain"  or at least the error should contain the chain height so users can specify it further
