### ISSUE TITLE
Node Receieve New Transaction from Peer

### ISSUE THREAD

**Issue by ceds** [ethereum/go-ethereum#22389]
I'm currently looking at the codebase as I'm trying to understand what happens in the code when a new transaction is received from connected peers (a transaction that is unknown to the GETH node).

Due to the massive size of the codebase I've been unable to find the code I'm looking for.  

Any direction from a GETH developer will be much appreciated.  Thanks :)

**Comment by MariusVanDerWijden** [comment]
That's not an easy question to answer (and also not really worth an issue here, better to ask these questions to the ethereum stackexchange).
When receiving a transaction over the wire, the transaction gets decoded in RLP and added to the txpool.
I suspect you want to do some frontrunning/MEV stuff. The place you're looking for is here: https://github.com/ethereum/go-ethereum/blob/master/core/tx_pool.go 
The txpool tracks all transactions that are not yet executed.
