### ISSUE TITLE
Geth 1.10 does not connect with openethereum node

### ISSUE THREAD

**Issue by geomad** [ethereum/go-ethereum#22394]
#### System information

Geth version: 1.10.0-unstable (master)
OS & Version: Debian Bullseye

I run geth and openethereum 3.0.1 nodes in the same machine. They connect to each other by setting enode@127.0.0.1:port to their static nodes lists. After updating geth to 1.10.0-unstable and fully generation the snapshot the nodes cannot find each other.

#### Expected behaviour
Nodes find and connect to each other

#### Actual behaviour
Nodes cannot find each other

#### Steps to reproduce the behaviour
Update geth from 1.9.25-stable to 1.10.0-unstable

**Comment by MariusVanDerWijden** [comment]
Yes, that's a known limitation with older openethereum versions. Basically geth 1.10 introduces a new sync protocol called `snap` but openethereum requires all protocols to be 3 letters (`eth`, `les`, `bzz`). Updating your openethereum node to one after this commit will work https://github.com/openethereum/openethereum/pull/271
