### ISSUE TITLE
geth repeatedly "killed" due to oom (out of memory). Can't fast sync

### ISSUE THREAD

**Issue by cyrusadkisson** [ethereum/go-ethereum#22391]
#### System information

Geth version: 1.9.25 e7872729
OS & Version: Linux Ubuntu 20.04.1

#### Expected behaviour

Smooth fast sync

#### Actual behaviour

Geth dies repeatedly with "killed". Dmesg shows 

```
[272157.031359] [  39469]  1000 39469  1711669  1088459  9228288        0             0 geth
[272157.031361] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=geth,pid=39469,uid=1000
[272157.031405] Out of memory: Killed process 39469 (geth) total-vm:6846676kB, anon-rss:4353836kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:9012kB oom_score_adj:0
[272157.175183] oom_reaper: reaped process 39469 (geth), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

#### Steps to reproduce the behaviour

Not sure. My computer is a normal x64 laptop feat. core i5 with 8GB of memory. Should be able to handle this, no problem. My command is:

`geth --syncmode fast --datadir /media/cyrus/WD\ red\ 500\ GB/ethereum --cache 2048 --maxpeers 60 --light.serve 30 --light.maxpeers 30 --nousb`

I was able to get to block number ~7M and eventually to 7.4M by repeatedly restarting geth but eventually gave up.

**Comment by cyrusadkisson** [comment]
Update: also happens on ethereum-unstable from ppa (previous report was stable from ppa)

**Comment by karalabe** [comment]
So, this seems like a bug that's compounded by a variety of things.

Go's GC is a bit relaxed in that it only starts wiping when 100% junk accumulates vs. the RAM left from the previous sweep. This makes RAM usage a bit funky. However, with 2GB cache, it should not hit 8.

So, my hunch is that fast sync might be expanding too many nodes sideways, causing a lot of RAM to be used temporarily. It would help if you could attach some logs from before the crash.

**Comment by cyrusadkisson** [comment]
FWIW, I upgraded to 1.10 when it was released a few days ago, wiped everything and have now sync'd to 7.5 million without any issues. I'll check back in when/if it goes the whole way.

**Comment by cyrusadkisson** [comment]
Chain successfully sync'd with same options on 1.10.
