### ISSUE TITLE
Synchronization problem after sleep

### ISSUE THREAD

**Issue by larspensjo** [ethereum/go-ethereum#2240]
I use Mist to manage my wallets. I put my computer in sleep mode, and wakes it up after a while again. As expected, the blockchain can be far behind at this point.

Almost always, there are 0 peers and no synchronization can be started. I waited for several minutes, and it did not improve.
![image](https://cloud.githubusercontent.com/assets/2412342/13201603/46196af2-d879-11e5-9c35-ad6fed98a44f.png)

However, restarting Mist, and thus restarting geth, quickly found peers and started to synchronize.

**Comment by obscuren** [comment]
It would be worthwhile to download an executable of geth and run that (prior to starting `mist`) with `geth --vmodule=p2p/*` and upload the logs in a [gist](https://gist.github.com) when this happens.

**Comment by larspensjo** [comment]
As this has happened a couple of times for me, I should be able to get a log. However, first test synchronized as it should

**Comment by larspensjo** [comment]
Ok, got the error now, but where can I find the logs?

I am on Windows.

The output from geth itself simply stopped when I paused Windows, and did not start again. So the last lines show:
```
I0226 22:38:41.787742   10784 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 5.5035ms. #1065038 [40df9243 / 40df9243]
I0226 22:38:55.942523   10784 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 3.5022ms. #1065039 [164c192a / 164c192a]
I0226 22:39:16.176947   10784 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 5.0033ms. #1065040 [2632be30 / 2632be30]
```

When I am writing this, Mist shows 0 peers and the current block should be 1067822. I have waited for approx one hour for any peer to be found.

**Comment by larspensjo** [comment]
I interrupted geth with a Cntrl-c, and got the response:
```
I0226 22:38:55.942523   10784 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 3.5022ms. #1065039 [164c192a / 164c192a]
I0226 22:39:16.176947   10784 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 5.0033ms. #1065040 [2632be30 / 2632be30]
I0227 17:39:05.800486   10784 cmd.go:123] Got interrupt, shutting down...
```
But geth didn't terminate, it was stuck at that position. That is, I didn't get back to the DOC prompt. Pressing CTRL-C again, produced  the following:
```
I0227 17:42:19.472916   10784 cmd.go:129] Already shutting down, please be patient.
I0227 17:42:19.478055   10784 cmd.go:130] Interrupt 9 more times to induce panic.
```
After a while (couple of minutes), I was no longer patient, and pressed additional CTRL-C. See [geth panic output 2016-02-27](https://gist.github.com/larspensjo/93f9d8fb7f6dec30e742) with output from the panic statement.

**Comment by larspensjo** [comment]
Btw, I am using geth v1.3.3. Restarting geth manually correctly starts the sync again.

**Comment by fjl** [comment]
Does it work with geth from develop branch? #2146 should fix this.

**Comment by larspensjo** [comment]
I get
```
# github.com/ethereum/go-ethereum/crypto/secp256k1
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
```
trying to compile latest develop. I suppose I'll wait for 1.3.4 and test.

**Comment by larspensjo** [comment]
Anyway, here is another clue to the issue. After waiting about 30 minutes for any synchronization to start (0 peers), something suddenly happened:
```
I0228 16:33:52.533443    9272 downloader.go:267] Synchronisation failed: no peers to keep download active
I0228 16:35:32.403771    9272 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 6.0043ms. #1073329 [4e71ef13 / 4e71ef13]
I0228 16:35:32.544056    9272 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 25.5206ms. #1073330 [ca3c2f74 / ca3c2f74]
I0228 16:35:32.555072    9272 blockchain.go:1243] imported 3 block(s) (0 queued 0 ignored) including 0 txs in 10.516ms. #1073333 [8718b177 / 1ecc1baa]
```
I now have 2 peers, and synchronization succeeded.

**Comment by obscuren** [comment]
@larspensjo could you perhaps try one of the pre compiled binaries found [here](https://build.ethdev.com/builders/Windows%20Go%20develop%20branch/builds/-1)

**Comment by obscuren** [comment]
@fjl fixed a windows issue on the `develop` branch a while ago. Would like to know if that has solved the issue.

**Comment by fjl** [comment]
@larspensjo The fix is also in geth 1.3.4, which was just released. The compilation error you saw is caused by using 64bit Go compiler with MinGW32. You can change to MinGW64 or just use the 1.3.4 binary.

**Comment by larspensjo** [comment]
Thanks, got this 1.4.0-unstable up and running. Will take a while, as I need to sleep my PC for half a day or so to trigger the issue. I'll be back.

**Comment by larspensjo** [comment]
For the first time, I could now see that the client started with 0 peers but it quickly found some and started to sync, and soon ended with a "normal set" of 13 peers. This is with the 1.4.0-unstable version.

I downloaded the official 1.3.4, and is testing it also now.

**Comment by larspensjo** [comment]
I was using vanilla Mist 0.5.0 today, letting the computer sleep for one day. Mist reported 25 peers, andone full day since last block. This state didn't change after one hour. I kille the application, started geth manually, and it didn't need to sync. It seems geth had already synced, but Mist didn't get it. This time, I am leaving geth running in its own window to be able to see what happens next time I have the computer sleep.

**Comment by fjl** [comment]
Hm, that sounds like a different kind of error.

**Comment by fjl** [comment]
Please open a new issue for the new problem.

**Comment by rustyx** [comment]
Still a problem with geth 1.8.3-stable on Windows 10 x64.
