### ISSUE TITLE
Geth full sync is very slow

### ISSUE THREAD

**Issue by nick4fake** [ethereum/go-ethereum#22410]
Geth version: `1.9.25`
OS & Version: Ubuntu 20.04 in Docker

Command line:
````bash
geth --maxpeers 500 --syncmode full --cache 8192 # + others (data dir, rpc, etc)
````

Machine:

- AWS i3.xlarge with NVMe used for chaindata, ext4
- No additional specific configuration
- ipv6 is used and supported

Issue:
Current sync process is terribly slow. I know that this has been reiterated dozens of times, I've looked through all Github tickets and know that IOPS, CPU and RAM requirements are very high (especially former). The only reason I'm posting this once again is that i3.xlarge is very decent machine, and it still only gives me 10 blocks/sec (so I estimate full sync will take like... weeks? months?). Am I missing something?

**Comment by nick4fake** [comment]
After many days of work:
````
Imported new chain segment               blocks=68   txs=9179  mgas=513.427 elapsed=8.037s    mgasps=63.882  number=5595880 hash="04d032…168031" age=2y10mo5d  dirty=505.38MiB
````

BTW, after directly moving chaindata to another place (from EBS to i3 NVMe) and starting geth it has reverted back by 500k blocks.

**Comment by karalabe** [comment]
EBS is super low on IOPS, don't even bother with that. Attached NVMe is what we use generally for benchmarks (`i3.2xlarge`). It takes us around 8-10 days to do a full sync, though I don't get why you'd want to reexecute all transactions from genesis.

> BTW, after directly moving chaindata to another place (from EBS to i3 NVMe) and starting geth it has reverted back by 500k blocks.

You didn't terminate Geth gracefully. It maintains a large dirty cache in memory that it flushes on shutdown (can take a minute or two). If you hard kill Geth without it flushing it's caches, it will lose all that dirty data and will need to revert to the last block for which it has everything in the database. Please make sure you give Geth 3 minutes to shut down (depends on the amount of ram you permit it to use for caching and the speed at which it can flush to disk).

**Comment by nick4fake** [comment]
@karalabe sorry for confusion, I didn't mean IOPS EBS volume, just the fact that I know it requires a lot of them.

I am using ephemeral NVMe, and it looks like it will take at least two weeks (or more). Regarding why - I mean, I want to support Ethereum blockchain by having full (not archive) node.

As for dirty cache - got it. We should probably create another ticket for docs on that,

**Comment by nick4fake** [comment]
@karalabe And if you don't mind - another question: can I move all the data to EBS after initial sync is finished? Will it keep up with the blockchain?

I am thinking about some t3.xlarge instance with 3000 iops gp3 for chain data, and HDD for ancient blocks.

**Comment by AlexSSD7** [comment]
> Can I move all the data to EBS after initial sync is finished? Will it keep up with the blockchain?

It will work, but keep in mind that your node will be pretty slow at importing new blocks.

You need to be aware that you will need to resync a couple of days of the Ethereum activity in case of the unclean shutdown event, which will take some time since EBS is pretty slow.

**Comment by MariusVanDerWijden** [comment]
Another thing is that during the initial sync you don't want to have that many peers. 
Managing these peers will reduce your sync speed. So you would want to run with maybe `--maxpeers 20` until your node is synced and then increase to `--maxpeers 500`. If you want to support the ethereum network, you can also enable `--light.serve 100` to enable one core to serve light clients.

Will close this issue for now, Feel free to open another one if you found a bug. Generally we prefer that you use the ethereum stackexchange for usage advice

**Comment by nick4fake** [comment]
For the sake of keeping track.
Full sync on i3.2xlarge has taken 17 days

**Comment by begetan** [comment]
You don't need to use `--syncmode full`  flag. With the regular fast sync option, it takes several hours to get synced on such a machine.

**Comment by nick4fake** [comment]
Please reopen this one.

See logs here:
https://github.com/ethereum/go-ethereum/issues/22528#issuecomment-808505377

Even on dedicated server it's still bery slow. Server used:
https://www.hetzner.com/dedicated-rootserver/ax61-nvme

**Comment by karalabe** [comment]
Define "very slow". In your previous logs, Geth processed almost 1200 transactions per second. On mainnet there are almost 1.1 billion transactions. I wouldn't call that "very slow".

That's why everyone is saying that you don't need to do a full sync. There's no reason to reexecute + years' worth of transaction. Sure, you can, but the cost is a lot of time. So ask yourself whether you actually need to run everything the network ran for 6 years or not.

**Comment by alisscco** [comment]
Advise ?

Also regarding uni claim ?
Much obliged ..

**Comment by alisscco** [comment]
Is there a priority bridge wallet you that will be best suitable for this
or I go ahead with fortmatic .

**Comment by karalabe** [comment]
@alisscco Please stop posting random questions on our issue tracker. If you have questions, ask them on https://ethereum.stackexchange.com/. This is a bugtracker for the go-ethereum codebase.

**Comment by alisscco** [comment]
Noted.

**Comment by nick4fake** [comment]
@karalabe thank you for the quick response. As I've said I am setting up the full node simply to do it "right blockchain way" and ensure everything is correct.

The issue is not 1200 transactions per seconds (that's around 8 blocks which is fine) but:
1. On EBS SSD it's around 40-50 transactions per second. So ANY synchronization way wouldn't work as it can't even keep up with network
2. On a very powerful dedicated server from hetzner i get only 1 block per second. That's enough to keep up with network for now, but is quite slow

**Comment by nick4fake** [comment]
@karalabe 

````
Imported new chain segment blocks=3 txs=669 mgas=37.252 elapsed=15.234s mgasps=2.445 number=12072827 hash="6ebcc0…e9a56c" age=1w17h17m dirty=613.21MiB
````

45 transactions per second. Current load:
![image](https://user-images.githubusercontent.com/1065993/112732244-7dbb3880-8f41-11eb-8afc-b97a1123be94.png)
![image](https://user-images.githubusercontent.com/1065993/112732281-a5120580-8f41-11eb-9b60-1c10fb6aeb04.png)

**Comment by nick4fake** [comment]
@MariusVanDerWijden I understand that bugtracker is for bugs, but I've spent many weeks looking for solutions and it doesn't look like I am doing something wrongly. I am out of ideas, unfortunately.

**Comment by nick4fake** [comment]
Well, sorry again for spamming, but looks like I've found the problem.

So in my case I've been using Docker with cpu/ram limits. Ram limit was not enough and it has been using swap. While that's already enough for slow performance It has been even worse: due to kernel limitations swap limits didn't propagate to the container so it has been continuously trying to allocate too much memory and dying with OOM that restarted sync over and over doing it slowly due to using swap... Quite challenging. Thanks for your help anyway
