### ISSUE TITLE
Cannot disable Transaction Lookup Limit when running in archive mode

### ISSUE THREAD

**Issue by ryanschneider** [ethereum/go-ethereum#22415]
#### System information

Geth version: `1.10.0-unstable`
OS & Version: Linux
Commit hash : 19d7a37abb9f3b9bf1a94baf6bd8c7d5042e54f8

#### Expected behaviour

Disabling transaction lookup limit via `--txlookuplimit 0` should work w/ `--gcmode-archive`.

#### Actual behaviour

> `Mar 02 22:32:06 ip-10-0-64-77 geth[19655]: Fatal: Flags --gcmode=archive, --txlookuplimit can't be used at the same time`

#### Steps to reproduce the behaviour

Run current master with these flags:

> `/usr/bin/geth --ropsten --txlookuplimit 0 --gcmode archive`

**Comment by ryanschneider** [comment]
@karalabe and @holiman (wouldn't normally at-mention but wanted to make sure you were aware w.r.t 1.10 release).

**Comment by ryanschneider** [comment]
The check that's failing is here: https://github.com/ethereum/go-ethereum/blob/744707a490705f292b0558aa6807b3848a9c4bf9/cmd/utils/flags.go#L1480

I suspect that the intent is that TxLookupLimit is never _enabled_ on an archive node, in which case maybe a custom check needs can be written that disables txlookupLimit if gcmode archive is set, and possibly warns if default is used and errors if user tries to set any non-zero txlookuplimit with archive mode.

**Comment by ryanschneider** [comment]
I see, it was broken in this PR which changed the default value: https://github.com/ethereum/go-ethereum/pull/22293

So the easiest fix would be to just make the default `0` again like it was in 1.9.x, I've done that locally and removed the `--txlookuplimit 0` argument and it seems to work fine, in that I can get an old tx ok.

<details>

<summary> Old Tx Lookup </summary>

```
> eth.getBlockByNumber("0x11234", false)
{
  difficulty: "0x670888c",
  extraData: "0xd783010503846765746887676f312e372e33856c696e7578",
  gasLimit: "0x47e7c4",
  gasUsed: "0x1814b",
  hash: "0x6b028480c1448f7de730d45e2418d7fa5c770f8787cae314a0c79bd9ab84df73",
  logsBloom: "0x04002008000000080000000000000000000500000000000000000000000000000000000010000000000000000000002000000000000000000000100400000000000000000000000000000000000000000000000000000000000000000000000020000000020400000000000000000800400000000000000000000000000000000000008800000000000000000000000000000000000000000000000000000088000000000000000000000100000000000000000000000000000000000400400010000000000000200000000000000000000000000000000000000000000020000000000000000000000000000000000008000000008000000000000000000000",
  miner: "0x71842f946b98800fe6feb49f0ae4e253259031c9",
  mixHash: "0xe7c478ba83aafbaa3fe51a57ce1e438d2f6483539170b486a675330e69e3fa7f",
  nonce: "0x03279f51a13b6eb7",
  number: "0x11234",
  parentHash: "0x077e5aa421a4bd2d4301c81d5e5691c0cf2adfd8af001d8f88ee4059c5f238b4",
  receiptsRoot: "0xb8bce07302dd106ed3c3f2dd5ddece21918fcd47e335ba38f037b64e2adac5aa",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: "0x2ac",
  stateRoot: "0x545d452f5312102278aa6bea6d532acb83286cb6b429da178a35356593dd8589",
  timestamp: "0x583f31a3",
  totalDifficulty: "0x69bf3d4183f",
  transactions: ["0x7554dff405be7b768c8b4065f7990272eb559f0a895bc67e30d54929631591b6"],
  transactionsRoot: "0xe814319a70404cb63008ea76f8b5236db22492583d530b7852a19a9d493cbfe9",
  uncles: []
}
> eth.getTransaction("0x7554dff405be7b768c8b4065f7990272eb559f0a895bc67e30d54929631591b6")
{
  blockHash: "0x6b028480c1448f7de730d45e2418d7fa5c770f8787cae314a0c79bd9ab84df73",
  blockNumber: 70196,
  from: "0x70c9217d814985faef62b124420f8dfbddd96433",
  gas: 250000,
  gasPrice: 20000000000,
  hash: "0x7554dff405be7b768c8b4065f7990272eb559f0a895bc67e30d54929631591b6",
  input: "0x51a34eb80000000000000000000000000000000000000000000000283164f33da5188000",
  nonce: 9212,
  r: "0x9eae614d29ad02f71591e307bebda1002d192c5f33137cafbaa64205bcb155cd",
  s: "0x163f4768b99b40a77620cb006af55535ed4f183d54fc189dc1bbcd31acc5d878",
  to: "0x8fc6738414035b1e341aa0de00e0657af61e1ca9",
  transactionIndex: 0,
  type: "0x0",
  v: "0x29",
  value: 0
}
```

</details>

**Comment by karalabe** [comment]
Good catch. Imho we should drop the exclusivity check and force the value to 0 ir running an archive node.
