### ISSUE TITLE
Old & copied SHA-3 code and misleading reference to SHA-3 instead of Keccak-256

### ISSUE THREAD

**Issue by jimenezrick** [ethereum/go-ethereum#2241]
This blog explains the issue: https://medium.com/@ConsenSys/are-you-really-using-sha-3-or-old-code-c5df31ad2b0. Ethereum uses **Keccak-256**, not **SHA-3**, which was standardized afterwards. 

I could myself prepare a PR with this improvements:
- Add to Godeps `golang.org/x/crypto/sha3` with a small patch to expose Keccak-256: https://github.com/jimenezrick/crypto/commit/8802e1c340c41c8d290e6315609cfbcbdf1b6229 (this thin fork could be hosted in the Ethereum Github obviously)
- Using upstream `crypto/sha3` gives some *extra performance*, tested running go test benchmark.
- Remove old copied **SHA-3 code**.
- Rename any code referencing **SHA-3** instead of **Keccak-256**

**Comment by karalabe** [comment]
Fixed per your PR.
