### ISSUE TITLE
Geth open too many files(more than 340k file descriptors)

### ISSUE THREAD

**Issue by Muggle-Du** [ethereum/go-ethereum#22420]
#### System information

Geth version: `geth 1.9.25 stable`
OS & Version: ubuntu 18
Commit hash : (if `develop`)

#### Expected behaviour
geth runs stably and no resource leakage

#### Actual behaviour
geth are opening more than 340k files

#### Steps to reproduce the behaviour
run geth in docker container with the command
entrypoint: ["geth","--ipcdisable","--syncmode","fast","--cache","4096","--nat","none","--datadir","/root","--port","38336","--ws","--wsaddr","0.0.0.0","--wsport","8036","--wsorigins","*","--rpc","--rpcport","8136","--rpcaddr","0.0.0.0","--rpccorsdomain","*","--rpcvhosts","*","--verbosity","3"]

#### Backtrace

````
pid = 11527 with 341265 fds: geth
````

**Comment by karalabe** [comment]
Works as expected. Check how many files there are in your database. As long as your OS allows us to open a lot of files, we will live with the opportunity.

**Comment by Muggle-Du** [comment]
Could I limit open files for geth?

**Comment by RayLvv** [comment]
> Could I limit open files for geth?

Hello, did you try to limit open files? I met silimilar problem and my system crushed.

**Comment by jsvisa** [comment]
> Hello, did you try to limit open files? I met silimilar problem and my system crushed.

instead of limit go-ethereum's open fds, you need to increase the system fd limit, eg: https://www.tecmint.com/increase-set-open-file-limits-in-linux/

**Comment by RayLvv** [comment]
> > Hello, did you try to limit open files? I met silimilar problem and my system crushed.
> 
> instead of limit go-ethereum's open fds, you need to increase the system fd limit, eg: https://www.tecmint.com/increase-set-open-file-limits-in-linux/

The system origin limit is 131072(cat /proc/sys/fs/file-max), user limit: 
```
root soft nofile 65535
root hard nofile 65535
* soft nofile 65535
* hard nofile 65535`
```
The geth client still reports `too many open files in system` errors, causing my system to break.
Isn't this fd limit big enough? I found the startup parameter for geth `--fdlimit value`. May I set this param?

**Comment by karalabe** [comment]
Geth can work with however many file descriptors are available. Half are used for the db and the rest for networking. Please make sure you're not hitting it with insane amounts of HTTP requests via RPC.

**Comment by holiman** [comment]
Would be interesting to know if it's files (regular) or unclosed sockets. Could you try this? 

```
$ lsof -p `pidof geth`  | grep REG | wc -l 
64
$ lsof -p `pidof geth`  | grep IPv | wc -l 
4
```

**Comment by RayLvv** [comment]
> Geth can work with however many file descriptors are available. Half are used for the db and the rest for networking. Please make sure you're not hitting it with insane amounts of HTTP requests via RPC.

I'm sure no process connect to this machine except lighthouse.
Maybe geth use the docker container system limit.
```
cat /proc/pidof geth/limits
ax open files            1048576              1048576              files
```

**Comment by RayLvv** [comment]
> > Geth can work with however many file descriptors are available. Half are used for the db and the rest for networking. Please make sure you're not hitting it with insane amounts of HTTP requests via RPC.
> 
> I'm sure no process connect to this machine except lighthouse. Maybe geth use the docker container system limit.
> 
> ```
> cat /proc/pidof geth/limits
> ax open files            1048576              1048576              files
> ```

Ok, I will use these commands to check.

**Comment by holiman** [comment]
Please open a new, separate  ticket, if you want to continue this. Discussions on closed old tickets are not really good form.

And include information on how you run the node, commands, info about OS and what file system is used, and file system of any mounts you are using.
