### ISSUE TITLE
Transactions get stuck

### ISSUE THREAD

**Issue by skyeatshorizon** [ethereum/go-ethereum#22427]
Hey Guys Im having the following problem/question:
Im using a PoA private network with a blocktime of 0. I can broadcast transactions and they are mined as they should.
If I send a transaction with gasPrice too low, all the miners ignore this transaction. That's OK for me but then all future transactions from this account get ignored by miners even if they have the correct gasPrice.
What is wrong here? Thx for helping.

**Comment by rymuff** [comment]
> Im using a PoA private network with a blocktime of 0. I can broadcast transactions and they are mined as they should.
If I send a transaction with gasPrice too low, all the miners ignore this transaction.

You can configure minimum gas price for mining a transaction with `--miner.gasprice value` (default value is 1 gwei = 1,000,000,000 wei, see [docs](https://geth.ethereum.org/docs/interface/command-line-options)).

> That's OK for me but then all future transactions from this account get ignored by miners even if they have the correct gasPrice.

I guess that If large amount of transactions are submitted from a sender, miner assume that the sender perform DDoS attack, and ignore all transactions from the sender. To solve this problem, increase the price of gas and re-submit the transactions.

**Comment by MariusVanDerWijden** [comment]
Transactions are ordered by an increasing number called nonce. If a transaction gets dropped (e.g. by specifying to little gas) all following transactions are stuck until a transaction is mined with the same nonce as the transaction that was dropped. So to unstuck all transactions you need to re-submit a transaction with the correct nonce.
