### ISSUE TITLE
Dropping unsynced node during fast sync, can't connect to peers (net.peerCount=0)

### ISSUE THREAD

**Issue by Alex2695** [ethereum/go-ethereum#22428]
Hey everyone, im new to geth and have currently an issue with the connection with peers in my private ethereum network. For my network im running a virtual machine with ubuntu and several Raspberry pis for my project. My issue is, that i can't connect between my minder node (the VM) and the Rpis. When im trying to add peers i always get this error: 
WARN [03-04|09:26:45.690] Dropping unsynced node during fast sync  id=095ffb29a2df4f05 conn=staticdial addr=192.168.2.202:30303 type=Geth/Pi2/v1.9.25-sta...

The genesis file is the same i double checked, my firewalls are all inactive, the local times were also right on both devices, i looked through several issues in the issue section here, but i couldn't find a solution for my problem even though by trying different solutions by other users. Could u guys maybe please take a look at this issue, maybe someone also faced this problem and knows what the problem is.  

**When i start my node i use the following startnode.sh file:** 
VM:
geth --identity miner --rpc --rpcport 8080 --rpccorsdomain "*" --datadir mpbc --port 30303 --rpcapi "eth,net,web3" --networkid 2662 --nat extip:192.168.2.211 --netrestrict 192.168.2.1/24 --allow-insecure-unlock console

Rpi2:
geth --identity "Pi2" --rpc --rpcport 8080 --rpccorsdomain "*" --datadir mpbc --port 30303 --rpcapi "eth,net,web3" --networkid 2662 --nat extip:192.168.2.202 --netrestrict 192.168.2.1/24 --allow-insecure-unlock console

**The consensus engine is Clique with the following genesis.json file:**
{
  "config": {
    "chainId": 2662,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "clique": {
      "period": 1,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x603a5cbf",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000059eff7e8bbf1abc1b13e360947c4609ea7d8e030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "059eff7e8bbf1abc1b13e360947c4609ea7d8e03": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    },
    "dBEF12Fe0E0f8831378849a510ed44834649178D": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}

**For a better overview with the issue i tried addPeer(..) with verbosity 5 to get the following log files:**

alex@alexvm:~$ ./startnode.sh
DEBUG[03-04|09:26:32.474] Sanitizing Go's GC trigger               percent=100
INFO [03-04|09:26:32.476] Maximum peer count                       ETH=50 LES=0 total=50
WARN [03-04|09:26:32.476] The flag --rpc is deprecated and will be removed in the future, please use --http 
WARN [03-04|09:26:32.476] The flag --rpcport is deprecated and will be removed in the future, please use --http.port 
WARN [03-04|09:26:32.476] The flag --rpccorsdomain is deprecated and will be removed in the future, please use --http.corsdomain 
WARN [03-04|09:26:32.476] The flag --rpcapi is deprecated and will be removed in the future, please use --http.api 
INFO [03-04|09:26:32.476] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
DEBUG[03-04|09:26:32.476] FS scan times                            list="51.786µs" set="5.36µs" diff="2.875µs"
TRACE[03-04|09:26:32.476] Handled keystore changes                 time="100.406µs"
TRACE[03-04|09:26:32.476] Started watching keystore folder         path=/home/alex/mpbc/keystore
INFO [03-04|09:26:32.477] Set global gas cap                       cap=25000000
INFO [03-04|09:26:32.477] Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
INFO [03-04|09:26:32.477] Allocated cache and file handles         database=/home/alex/mpbc/geth/chaindata cache=512.00MiB handles=2048
DEBUG[03-04|09:26:32.497] Chain freezer table opened               database=/home/alex/mpbc/geth/chaindata/ancient table=hashes items=0 size=0.00B
DEBUG[03-04|09:26:32.499] Chain freezer table opened               database=/home/alex/mpbc/geth/chaindata/ancient table=bodies items=0 size=0.00B
DEBUG[03-04|09:26:32.501] Chain freezer table opened               database=/home/alex/mpbc/geth/chaindata/ancient table=receipts items=0 size=0.00B
DEBUG[03-04|09:26:32.504] Chain freezer table opened               database=/home/alex/mpbc/geth/chaindata/ancient table=diffs    items=0 size=0.00B
DEBUG[03-04|09:26:32.506] Chain freezer table opened               database=/home/alex/mpbc/geth/chaindata/ancient table=headers  items=0 size=0.00B
INFO [03-04|09:26:32.506] Opened ancient database                  database=/home/alex/mpbc/geth/chaindata/ancient
INFO [03-04|09:26:32.507] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, YOLO v2: <nil>, Engine: ethash}"
INFO [03-04|09:26:32.507] Disk storage enabled for ethash caches   dir=/home/alex/mpbc/geth/ethash count=3
INFO [03-04|09:26:32.507] Disk storage enabled for ethash DAGs     dir=/home/alex/.ethash          count=2
INFO [03-04|09:26:32.507] Initialising Ethereum protocol           versions="[65 64 63]" network=2662 dbversion=8
DEBUG[03-04|09:26:32.507] Current full block not old enough        number=0 hash="d4e567…cb8fa3" delay=90000
INFO [03-04|09:26:32.509] Loaded most recent local header          number=0 hash="d4e567…cb8fa3" td=17179869184 age=51y11mo9h
INFO [03-04|09:26:32.509] Loaded most recent local full block      number=0 hash="d4e567…cb8fa3" td=17179869184 age=51y11mo9h
INFO [03-04|09:26:32.509] Loaded most recent local fast block      number=0 hash="d4e567…cb8fa3" td=17179869184 age=51y11mo9h
DEBUG[03-04|09:26:32.509] Reinjecting stale transactions           count=0
INFO [03-04|09:26:32.509] Loaded local transaction journal         transactions=0 dropped=0
INFO [03-04|09:26:32.509] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-04|09:26:32.516] Allocated fast sync bloom                size=512.00MiB
INFO [03-04|09:26:32.517] Starting peer-to-peer node               instance=Geth/miner/v1.9.25-stable-e7872729/linux-amd64/go1.15.6
DEBUG[03-04|09:26:32.517] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
INFO [03-04|09:26:32.544] Mapped network port                      proto=tcp extport=30303 intport=30303 interface=ExtIP(192.168.2.211)
DEBUG[03-04|09:26:32.544] TCP listener up                          addr=[::]:30303
INFO [03-04|09:26:32.545] New local node record                    seq=32 id=fe1af2506afed48e ip=192.168.2.211 udp=0 tcp=30303
INFO [03-04|09:26:32.545] Started P2P networking                   self="enode://63f004bf5fca30023853d72c0b776447ca40cb2469fd9e1860fafbf3f2a386a70bf1871cc13b778826aaa3810cb7bbfce86eafa497c86fca1aca039da4402470@192.168.2.211:30303?discport=0"
DEBUG[03-04|09:26:32.546] IPCs registered                          namespaces=admin,debug,web3,eth,txpool,personal,ethash,miner,net
INFO [03-04|09:26:32.547] IPC endpoint opened                      url=/home/alex/mpbc/geth.ipc
INFO [03-04|09:26:32.548] HTTP server started                      endpoint=127.0.0.1:8545 cors=* vhosts=localhost
DEBUG[03-04|09:26:32.640] Served rpc_modules                       reqid=1 t="61.574µs"
TRACE[03-04|09:26:32.640] Handled RPC response                     reqid=1 t="1.283µs"
DEBUG[03-04|09:26:32.646] Served web3_clientVersion                reqid=2 t="49.382µs"
TRACE[03-04|09:26:32.646] Handled RPC response                     reqid=2 t="1.162µs"
INFO [03-04|09:26:32.646] Etherbase automatically configured       address=0x059Eff7e8bBF1abc1b13E360947C4609ea7D8E03
DEBUG[03-04|09:26:32.646] Served eth_coinbase                      reqid=3 t="168.513µs"
TRACE[03-04|09:26:32.646] Handled RPC response                     reqid=3 t="1.082µs"
DEBUG[03-04|09:26:32.647] Served eth_blockNumber                   reqid=4 t="82.583µs"
TRACE[03-04|09:26:32.647] Handled RPC response                     reqid=4 t="1.122µs"
DEBUG[03-04|09:26:32.647] Served eth_blockNumber                   reqid=5 t="24.806µs"
TRACE[03-04|09:26:32.647] Handled RPC response                     reqid=5 t=922ns
DEBUG[03-04|09:26:32.648] Served eth_getBlockByNumber              reqid=6 t="300.026µs"
TRACE[03-04|09:26:32.648] Handled RPC response                     reqid=6 t="1.933µs"
DEBUG[03-04|09:26:32.650] Served admin_datadir                     reqid=7 t="62.917µs"
TRACE[03-04|09:26:32.650] Handled RPC response                     reqid=7 t="1.763µs"
DEBUG[03-04|09:26:32.650] Served rpc_modules                       reqid=8 t="52.608µs"
TRACE[03-04|09:26:32.651] Handled RPC response                     reqid=8 t=972ns
Welcome to the Geth JavaScript console!

instance: Geth/miner/v1.9.25-stable-e7872729/linux-amd64/go1.15.6
coinbase: 0x059eff7e8bbf1abc1b13e360947c4609ea7d8e03
at block: 0 (Thu Jan 01 1970 01:00:00 GMT+0100 (BST))
 datadir: /home/alex/mpbc
 modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

To exit, press ctrl-d
INFO [03-04|09:26:32.665] Initialized fast sync bloom              items=12356 errorrate=0.000 elapsed=148.264ms
**admin.addPeer("enode://d5c60bed94232a2afd13a5c30c1c606fa4e88f70f2d5a45c437fec59803d9822836978f085720c4ffae4e98f2bdfd351667150efffd7dcaa1a4ddb473f3a1832@192.168.2.202:30303")**
DEBUG[03-04|09:26:45.621] Served admin_addPeer                     reqid=9 t="379.944µs"
TRACE[03-04|09:26:45.622] Handled RPC response                     reqid=9 t="1.904µs"
true
TRACE[03-04|09:26:45.622] Adding static node                       id=095ffb29a2df4f05 ip=192.168.2.202 added=true
TRACE[03-04|09:26:45.622] Starting p2p dial                        id=095ffb29a2df4f05 ip=192.168.2.202 flag=staticdial
INFO [03-04|09:26:45.622] Looking for peers                        peercount=0 tried=0 static=1
DEBUG[03-04|09:26:45.681] Adding p2p peer                          peercount=1 id=095ffb29a2df4f05 conn=staticdial addr=192.168.2.202:30303 name=Geth/Pi2/v1.9.25-sta...
TRACE[03-04|09:26:45.681] Starting protocol eth/65                 id=095ffb29a2df4f05 conn=staticdial
DEBUG[03-04|09:26:45.681] Ethereum peer connected                  id=095ffb29a2df4f05 conn=staticdial name=Geth/Pi2/v1.9.25-sta...
TRACE[03-04|09:26:45.681] Registering sync peer                    peer=095ffb29a2df4f05
DEBUG[03-04|09:26:45.681] Fetching batch of headers                id=095ffb29a2df4f05 conn=staticdial count=1 fromnum=11337727 skip=0 reverse=false
WARN [03-04|09:26:45.690] Dropping unsynced node during fast sync  id=095ffb29a2df4f05 conn=staticdial addr=192.168.2.202:30303 type=Geth/Pi2/v1.9.25-sta...
DEBUG[03-04|09:26:45.691] Ethereum message handling failed         id=095ffb29a2df4f05 conn=staticdial err="unsynced node cannot serve fast sync"
DEBUG[03-04|09:26:45.691] Removing Ethereum peer                   peer=095ffb29a2df4f05
TRACE[03-04|09:26:45.691] Unregistering sync peer                  peer=095ffb29a2df4f05
TRACE[03-04|09:26:45.691] Protocol eth/65 failed                   id=095ffb29a2df4f05 conn=staticdial err="unsynced node cannot serve fast sync"
DEBUG[03-04|09:26:45.691] Removing p2p peer                        peercount=0 id=095ffb29a2df4f05 duration=10.450ms req=false err="useless peer"
DEBUG[03-04|09:26:52.518] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[03-04|09:27:12.518] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
TRACE[03-04|09:27:20.626] Starting p2p dial                        id=095ffb29a2df4f05 ip=192.168.2.202 flag=staticdial
INFO [03-04|09:27:20.626] Looking for peers                        peercount=0 tried=1 static=1
DEBUG[03-04|09:27:20.666] Adding p2p peer                          peercount=1 id=095ffb29a2df4f05 conn=staticdial addr=192.168.2.202:30303 name=Geth/Pi2/v1.9.25-sta...
TRACE[03-04|09:27:20.666] Starting protocol eth/65                 id=095ffb29a2df4f05 conn=staticdial
DEBUG[03-04|09:27:20.667] Ethereum peer connected                  id=095ffb29a2df4f05 conn=staticdial name=Geth/Pi2/v1.9.25-sta...
TRACE[03-04|09:27:20.673] Registering sync peer                    peer=095ffb29a2df4f05
DEBUG[03-04|09:27:20.673] Fetching batch of headers                id=095ffb29a2df4f05 conn=staticdial count=1 fromnum=11337727 skip=0 reverse=false
WARN [03-04|09:27:20.679] Dropping unsynced node during fast sync  id=095ffb29a2df4f05 conn=staticdial addr=192.168.2.202:30303 type=Geth/Pi2/v1.9.25-sta...
DEBUG[03-04|09:27:20.680] Ethereum message handling failed         id=095ffb29a2df4f05 conn=staticdial err="unsynced node cannot serve fast sync"
DEBUG[03-04|09:27:20.680] Removing Ethereum peer                   peer=095ffb29a2df4f05
TRACE[03-04|09:27:20.680] Unregistering sync peer                  peer=095ffb29a2df4f05
TRACE[03-04|09:27:20.680] Protocol eth/65 failed                   id=095ffb29a2df4f05 conn=staticdial err="unsynced node cannot serve fast sync"
DEBUG[03-04|09:27:20.680] Removing p2p peer                        peercount=0 id=095ffb29a2df4f05 duration=13.625ms req=false err="useless peer"
DEBUG[03-04|09:27:32.508] Current full block not old enough        number=0 hash="d4e567…cb8fa3" delay=90000
DEBUG[03-04|09:27:32.520] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[03-04|09:27:52.521] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
TRACE[03-04|09:27:55.630] Starting p2p dial                        id=095ffb29a2df4f05 ip=192.168.2.202 flag=staticdial
INFO [03-04|09:27:55.630] Looking for peers                        peercount=0 tried=1 static=1
DEBUG[03-04|09:27:55.660] Adding p2p peer                          peercount=1 id=095ffb29a2df4f05 conn=staticdial addr=192.168.2.202:30303 name=Geth/Pi2/v1.9.25-sta...
TRACE[03-04|09:27:55.660] Starting protocol eth/65                 id=095ffb29a2df4f05 conn=staticdial
DEBUG[03-04|09:27:55.660] Ethereum peer connected                  id=095ffb29a2df4f05 conn=staticdial name=Geth/Pi2/v1.9.25-sta...
TRACE[03-04|09:27:55.667] Registering sync peer                    peer=095ffb29a2df4f05
DEBUG[03-04|09:27:55.667] Fetching batch of headers                id=095ffb29a2df4f05 conn=staticdial count=1 fromnum=11337727 skip=0 reverse=false
WARN [03-04|09:27:55.673] Dropping unsynced node during fast sync  id=095ffb29a2df4f05 conn=staticdial addr=192.168.2.202:30303 type=Geth/Pi2/v1.9.25-sta...

Thanks in advance guys!

**Comment by MariusVanDerWijden** [comment]
Your node does not use the correct chain config
```
Initialised chain configuration config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, YOLO v2: , Engine: ethash}"
```
You need to delete the chain folder on alex@alexvm and reinit it with the correct genesis `geth init --datadir data genesis.json`

Please close the issue if that helped, if not report back

**Comment by Alex2695** [comment]
So tried to reinit my genesis and i still had the same issue. By removing --netrestrict in my startnode file it's finding peers finally, but the number is also inconsistent it fluctuates from 0 to 3 (i have 3 RPis in my private Network). After a while im getting the following Error: 
Snapshot extension registration failed 
err="peer connected on snap without compatible eth support"

**Comment by Alex2695** [comment]
So tried to reinit my genesis and i still had the same issue. By removing --netrestrict in my startnode file it's finding peers finally, but the number is also inconsistent it fluctuates from 0 to 3 (i have 3 RPis in my private Network). But the problem still remains with the Chain ID. Everytime im trying to geth init my new genesis im getting this error: 
geth --datadir ~/mpbc/blockchain init genesis.json
Fatal: Failed to read genesis file: open genesis.json: no such file or directory

So what i did was going to the folder with cd commands and init all genesis file(geth init genesis.json in the folder), is that maybe the mistake? But why do i get this error to init the genesis file when the files are in the folder?

**Comment by MariusVanDerWijden** [comment]
If you execute this `geth --datadir ~/mpbc/blockchain init genesis.json` than the `genesis.json` has to be in your current directory. If the `genesis.json` is in `~/mpbc/blockchain` than you need to run `geth --datadir ~/mpbc/blockchain init ~/mpbc/blockchain/genesis.json`

**Comment by Alex2695** [comment]
It worked for me, thank you!
