### ISSUE TITLE
Can i switch from fast to snap sync mode?

### ISSUE THREAD

**Issue by Jacks349** [ethereum/go-ethereum#22438]
So this is a very noob question and it's probably not possible, but i started syncing a mode using `geth --syncmode fast --cache=2048 --datadir /mnt --ws`, and the node seems to be stuck importing new state entries:  
`Imported new state entries count=385  elapsed="3.287µs"   processed=236000921 pending=100815`.

Now i'm on a VPS with 2 cores CPU and 8GB RAM and i'm afraid this process it's going to take a lot of days, so i was wondering: is `snap` faster than `fast` during this phase too? And, even though i'm afraid this is not possible, can i switch from `--syncmode fast` to `snap`? Thanks in advance!
 
And my last newbie question: i need to run a node in order to use it for a web3py api, can i do this with `snap` too? And am i still going to get an high number of peers with `snap`?

**Comment by MariusVanDerWijden** [comment]
You can switch to `syncmode=snap`, however all of your current synced states can not be used by snap sync which means you'll loose some of your progress. Snap starts syncing the state from scratch (won't redownload blocks and headers though). In theory it should be faster than fast sync even if you are halfway done with your fast sync, but it depends on how many of your peers have a snapshot generated to serve you. 

Yes you can, the syncmode only defines how your node initially syncs, it has no impact on your node operation going forward (though you can not query receipts that occurred before your node was fully synced). You should get the same amount of peers with snap (only some older OpenEthereum/Parity peers won't connect to you)

**Comment by Jacks349** [comment]
Awesome! Thank you a lot @MariusVanDerWijden
