### ISSUE TITLE
Build fails on OpenBSD arm64 

### ISSUE THREAD

**Issue by tobias-hildebrandt** [ethereum/go-ethereum#22434]
Hello, I'm unable to build geth on my Raspberry Pi 4 running OpenBSD -current. I'm not very knowledgeable on the Go build process. Please let me know what other information is necessary or if I should run any other commands.

#### System information

Raspberry Pi 4 (2GB RAM)
`$ uname -a`
`OpenBSD rpi4-openbsd.none 6.9 GENERIC.MP#1051 arm64`

#### Expected behaviour
geth builds successfully and exists in `./build/bin/`

#### Actual behaviour
geth fails on build, `./build/bin/` does not exist

#### Steps to reproduce the behaviour
`go install github.com/ethereum/go-ethereum/cmd/geth@latest` on a Raspberry Pi 4 running OpenBSD

#### ~~Backtrace~~ Logs
[goenv](https://github.com/ethereum/go-ethereum/files/6086989/goenv.txt)
[go install github.com/ethereum/go-ethereum/cmd/geth@latest](https://github.com/ethereum/go-ethereum/files/6087187/go-ethereum-build.txt) (the same errors occur when running `make geth` after cloning the git repo)

**Comment by MariusVanDerWijden** [comment]
From your log:
```
# github.com/shirou/gopsutil/mem
.go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:21:17: undefined: CTLVm
.go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:21:24: undefined: VmUvmexp
.go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:26:14: undefined: sizeOfUvmexp
.go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:29:13: undefined: Uvmexp
.go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:43:17: undefined: CTLVm
.go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:43:24: undefined: VmUvmexp
.go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:48:14: undefined: sizeOfUvmexp
.go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:51:13: undefined: Uvmexp
.go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:72:16: undefined: CTLVfs
.go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:72:24: undefined: VfsGeneric
.go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:72:24: too many errors
# github.com/ethereum/go-ethereum/cmd/utils
.go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.0/cmd/utils/diskusage.go:34:19: stat.Bavail undefined (type unix.Statfs_t has no field or method Bavail)
.go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.0/cmd/utils/diskusage.go:35:9: stat.Bavail undefined (type unix.Statfs_t has no field or method Bavail)
.go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.0/cmd/utils/diskusage.go:41:37: stat.Bsize undefined (type unix.Statfs_t has no field or method Bsize)
```
Seems that there is a problem in gopsutil on OpenBSD and in "golang.org/x/sys/unix", 
We'll investigate it, thank you for reporting!

**Comment by gballet** [comment]
Fix pushed at https://github.com/shirou/gopsutil/pull/1052, need to wait for the merge
