### ISSUE TITLE
Error when using Solidity: "solc: no build results found"

### ISSUE THREAD

**Issue by think2win** [ethereum/go-ethereum#2244]
Geth instance: Geth/v1.3.3/windows/go1.5.1
Solidity : Version: 0.2.2-d3bb5d01/Release-Windows/msvc/JIT linked to libethereum-
Error: 
solc: no build results found
    at InvalidResponse (<anonymous>:-81662:-44)
    at send (<anonymous>:-156322:-44)
    at solidity (<anonymous>:-133322:-44)
    at <anonymous>:1:12

Issue #1770 (https://github.com/ethereum/go-ethereum/issues/1770) is said to have been fixed but continue to see it in my latest windows installs for geth and solidity

**Comment by obscuren** [comment]
@zelig could you please have a look. I know you maintained this for a while :-)

**Comment by think2win** [comment]
If someone can suggest a compatible Geth and Solidity version to use on windows - it will help me move forward while the issue is being researched/ fixed. Thanks

**Comment by remyroy** [comment]
I'm also having this problem with `Geth/v1.3.5/windows/go1.5.1` and solc `Version: 0.2.2-0/Release-Windows/msvc/JIT linked to libethereum-`.

**Comment by remyroy** [comment]
This should be fixed with #2292.

**Comment by ynaciri** [comment]
Those versions are affected as well :

geth 1.3.6
solc 0.3.1-33b95459/Release-Windows/msvc/JIT linked to libethereum-
