### ISSUE TITLE
[puppeth] deployed explorer always response 502 bad gateway

### ISSUE THREAD

**Issue by rymuff** [ethereum/go-ethereum#22449]
#### System information

Geth version: `v1.10.1-unstable-dab90e4d-20210304/linux-amd64/go1.16`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Show explorer page

#### Actual behaviour
502 Bad Gateway

#### Steps to reproduce the behaviour
Deploy explorer with `puppeth`

#### Etc.
Node for `explorer` is successfully deploy, and shown in `ethstats`.

**Comment by MariusVanDerWijden** [comment]
Can you please share what commands you used exactly, so that we can reproduce the issue easier?
