### ISSUE TITLE
the method eth_protocolVersion does not exist/is not available

### ISSUE THREAD

**Issue by alexeirbv** [ethereum/go-ethereum#22441]
#### System information

Geth version: `v1.10.0`
OS & Version: Ubuntu 18.04.5 LTS

#### Expected behaviour
eth_protocolVersion returns protocol version

#### Actual behaviour
go-ethereum returns: `the method eth_protocolVersion does not exist/is not available`

#### Steps to reproduce the behaviour
`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_protocolVersion","params":[],"id":67}' -H "Content-Type: application/json" http://localhost:8545`

**Comment by evertonfraga** [comment]
This method was deprecated on 1.10.0. ease head to the release notes for more information on it.

**Comment by alexeirbv** [comment]
@evertonfraga Got it. Thanks

**Comment by meowsbits** [comment]
I don't see it in the Release Notes on Github.

![image](https://user-images.githubusercontent.com/45600330/112199236-f174e280-8bdb-11eb-831d-084367e100f9.png)
> https://github.com/ethereum/go-ethereum/releases/tag/v1.10.0

But it is noted at the [blog post](https://blog.ethereum.org/2021/03/03/geth-v1-10-0/):

![image](https://user-images.githubusercontent.com/45600330/112199305-06517600-8bdc-11eb-8ac8-f0105ccb89ae.png)

Related to https://github.com/ethereum/go-ethereum/pull/22064.
