### ISSUE TITLE
Prometheus metrics are broken

### ISSUE THREAD

**Issue by Swift42** [ethereum/go-ethereum#22458]
#### System information

Geth version: `1.10.1`
OS & Version: Linux

#### Expected behaviour
Prometheus should read the metrics without an error.

#### Actual behaviour
Prometheus scrape fails with "invalid metric type"
This happens because all of the new "les/clientcompact" and "les/clientdisk" metrics have a "." instead of "_" in the name. 
E.g.
eth_db_les.clientcompact_input 0
should be 
eth_db_les_clientcompact_input 0

**Comment by holiman** [comment]
I wonder if the problem isn't something else, namely that the namespace is `"eth/db/les.client"` and not `"eth/db/les.client/"`.At least, that's one error, because `eth/db/les.clientcompact` is not a metric, but `eth/db/les.client/compact` should be

**Comment by holiman** [comment]
Could you check if https://github.com/ethereum/go-ethereum/pull/22459 solves it?

**Comment by Swift42** [comment]
I modified the source as suggested, but this doesn't solve the problem (at least the problem with prometheus).
Now instead of e.g.
eth_db_les.clientcompact_input 0
the metrics contain
eth_db_les.client_compact_input 0

There is still a "." which causes the problem.

And yes, I still think that the "." is the problem, because Prometheus reports (without the patch):
err="invalid metric type \"clientcompact_input gauge\""
and now (with the patch):
err="invalid metric type \"client_compact_input gauge\""

This means everything after the dot is not recognized correctly. And all other metrics don't contain a dot and these are working correctly.

Maybe this breaks non-prometheus metrics, but if I change the line
`lesDb, err := stack.OpenDatabase("les.client", 0, 0, "eth/db/les.client/")`
to
`lesDb, err := stack.OpenDatabase("les.client", 0, 0, "eth/db/les/client/")`
all is working again and Prometheus don't report an error anymore. Now the metrics contain correctly:

```
# TYPE eth_db_les_client_compact_input gauge
eth_db_les_client_compact_input 187338
```

**Comment by holiman** [comment]
Thanks for checking -- I've fixed both issues in the linked PR now!
