### ISSUE TITLE
on private PoA network, only miners can sendTransaction

### ISSUE THREAD

**Issue by xoffey** [ethereum/go-ethereum#22450]
#### System information

Geth version: `1.9.25`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
transactions should be transmitted and acknowledged

#### Actual behaviour
transactions remain pending

#### Steps to reproduce the behaviour
1. create more than 1 node in a private network that uses the clique protocol
2. make at least one node mine
3. leave at least one node as a non-miner
4. try sendTransaction from a non-mining node

#### Backtrace

````
[backtrace]
````

At least 3 issues have been reported and closed for this problem, and yet the problem remains, as far as I can tell, in geth 1.9.25.
https://github.com/ethereum/go-ethereum/issues/2769
https://github.com/ethereum/go-ethereum/issues/2980
https://github.com/ethereum/go-ethereum/issues/3694

I created a private network that uses the clique protocol.
The first node is designated as a signer in the genesis json. That node by itself worked fine.

I created a second node. It syncs correctly but could not, at first, sendTransaction.
I followed a workaround mentioned in the earlier issues: established mining on the second node.
Now that works.

I created a third node. it syncs correctly, but can not sendTransaction.

What am I supposed to do? I don't want every node in my network to be a signer-sealer.

**Comment by MariusVanDerWijden** [comment]
Can you show an example transaction that you're trying to send?
Geth allows miners to send transactions with zero gas price, but might not accept remote transactions with 0 gas price

**Comment by xoffey** [comment]
Thanks for the reply, Marius!

I guess I am still confused by gas, My sendTransaction fails unless I pass gasPrice: 0.

sending 1000, without gasPrice
> eth.sendTransaction({from: myAddr, to: '0x0484b04a19aaabbbccc611353f6d1de', value: 1000 })
Error: gas required exceeds allowance (0)

with gasPrice: 1
> eth.sendTransaction({from: myAddr, to: '0x0484b04aaabbbccc342c611353f6d1de', value: 1000, gasPrice: 1 })
Error: gas required exceeds allowance (1000)

with gasPrice: 0
> eth.sendTransaction({from: myAddr, to: '0x0484aaabbbccc8b342c611353f6d1de', value: 1000, gasPrice: 0 })
"0xf49b0e50ab45bdaaabbbccc9356045d32084afa1c4c94049ad6689dda1"  // GOOD!

with gasPrice: 1000000000 
> eth.sendTransaction({from: myAddr, to: '0x0484b04aaabbbccc42c611353f6d1de', value: 100, gasPrice: 1000000000 })
Error: gas required exceeds allowance (0)

Can anyone recommend a good guide to managing gas and gas pricing for a PoA network?

**Comment by xoffey** [comment]
Thanks again. I will close this issue because it was mainly due to my incomplete understanding of gas.
