### ISSUE TITLE
Problem accessing ethwallet

### ISSUE THREAD

**Issue by odineH** [ethereum/go-ethereum#22454]
I created a wallet in 2017 using /geth new account but sth went wrong with the RAM and now I think the json file is corrupted as I cannot access my wallet even though I know my passphrase. Is there any way to get it back?

kind regards!

**Comment by holiman** [comment]
There might be, yes. I wrote a tool to try different permutations of bitflips that could occur during the wallet generation. I'll rebase the code and pust a link here

**Comment by odineH** [comment]
thanks, i'll have  a look !;)

**Comment by odineH** [comment]
thanks! is there any way to message you directly?

**Comment by odineH** [comment]
Hi! i tried the tool but it's not working for me as i think the problem was during the encryption and maybe more than 1 bit is flipped. I know one of the RAM modules was not working properly and it seems that that fact caused the whole problem. Any idea in order to recover the wallet?:D thanks anyway @holiman !

**Comment by MariusVanDerWijden** [comment]
There are some professional wallet recovery services out there (e.g. https://www.walletrecoveryservices.com/) that specialize in recovering wallets. If something happened during encryption, it is super unlikely that its possible to recover the secret

**Comment by odineH** [comment]
thanks for the info!:D
