### ISSUE TITLE
wifi authorisation problem

### ISSUE THREAD

**Issue by jzaw** [ethereum/go-ethereum#2246]
Client working properly on the laptop on home wifi connection causes authorization error for all other devices tying to connect to wifi. Problem disappears several minutes after geth is closed.

**Comment by obscuren** [comment]
Does your wifi router collect any logs? If so please put them in a gist (scan them for sensitive info, if any). While nothing is impossible I don't think it's because of geth but worth a look at the logs if you can provide any.

**Comment by obscuren** [comment]
Pling

**Comment by jzaw** [comment]
Unfortunately no useful information in logs & problem seems to be highly irregular. I have consulted @chfast and came to conclusion that this is the same case as in #2162
