### ISSUE TITLE
Excessive Disk Usage since upgrade from 1.9.25 -> 1.10.1

### ISSUE THREAD

**Issue by antbelcastro** [ethereum/go-ethereum#22467]
#### System information

Geth version:   1.10.1+build25351+focal
OS & Version: Ubuntu 20.04.2 LTS

#### Expected behaviour
Upgrade conducted from 1.9.25+build24398+focal to 1.10.1+build25351+focal using the ppa. 
I would have expected disk iops to behave similarly between versions.

#### Actual behaviour
Upon upgrade of the geth service (approx 13:33) excessive hardware read and write was seen. 
Currently unable to roll back as the 1.9.25 has been removed from the version table.
Upon restart of the device only the excessive read is seen. 
Disk activity stops if Geth is stopped. 

![image](https://user-images.githubusercontent.com/18137083/110449375-3e55b500-8116-11eb-8c46-46ee9750b25a.png)

Additional Notes:
Geth is run in the following configuration 
`geth --http --datadir /var/lib/goethereum --cache 2048 --maxpeers 30`
iotop confirms that it is Goeth is preforming the reads

There do not appear to be any erroneous logs.

Question: Is this expected behaviour?

**Comment by mikel2000** [comment]
I guess this happens because of the unindexing. This should be done after a few hours. Check here for details. https://blog.ethereum.org/2021/03/03/geth-v1-10-0/

**Comment by antbelcastro** [comment]
Thanks for the response. Ah true, sorry I missed the advice on the duration of the snapshoting. I’ll keep an eye on it. 

Thanks again
