### ISSUE TITLE
error="canonical block #11997255 unknown

### ISSUE THREAD

**Issue by andrewmayer1997** [ethereum/go-ethereum#22471]
#### System information

Geth version: `geth latest`
OS & Version: Linux

#### Actual behaviour
Section processing failed                type=bloombits               error="canonical block #11997255 unknown"

#### Steps to reproduce the behaviour
I don't know

**Comment by ligi** [comment]
can you provide the parameters you start geth with?

**Comment by andrewmayer1997** [comment]
> can you provide the parameters you start geth with?

nohup $GETH --datadir $GETHDATA --syncmode "fast" --miner.notify "http://localhost:4441"  --cache 26624 --ws --http --mine  --miner.etherbase $WALLET >$LOGDIR/geth.log 2>&1 & disown

The error appeared recently, before that everything was fine. There was a power outage a few days ago, the server was crashing

**Comment by ligi** [comment]
Thanks! the unclean shutdown due to the power outage is the root reason then. So to go forward you have 2 options:
 * try #21650
 * sync from scratch

**Comment by andrewmayer1997** [comment]
> * try #21650
> * sync from scratch

Thanks more!
