### ISSUE TITLE
Transaction pending on the network

### ISSUE THREAD

**Issue by developer2belfrics** [ethereum/go-ethereum#22478]
I initiated the transaction long back. it is still not confirmed on the network. i found that it is pending due to low gas price. so i am trying to resend the transaction with higher gas price but i am facing error insufficient fund for transfer even though i am having sufficient fund in my wallet

eth.getBalance('0x367ae801e27effe1f79394705d0696845ca13e0d')
30313139845072020

eth.sendTransaction({from:"0x367ae801e27effe1f79394705d0696845ca13e0d", to:"0x6f0dbff9f77dd6ff664d1e314135dd9eabffc100", value:"24000000000000000", nonce:"147", gasPrice:"9000000000", gasLimit:"21000"})

Please help me out on this

**Comment by karalabe** [comment]
Could you please paste the error?

Also, value and gasPrice should be hex really. Could you try with `web3.toWei(9, "gwei")` for the gas price and similarly for the value? Nonce and gasLimit is an int, no need for quotes.

According to etherscan, yous pending tx has a gas price ov 46 gwei, so replacing it with 9 won't help.

**Comment by developer2belfrics** [comment]
I even tried with 90 gwei but it was saying insufficient fund error. but in the wallet it is having sufficient fund

![Screen Shot 2021-03-11 at 12 35 32 PM](https://user-images.githubusercontent.com/57176610/110905326-4ee17780-8330-11eb-8c4c-060455528aba.png)

**Comment by karalabe** [comment]
> value and gasPrice should be hex

**Comment by karalabe** [comment]
> Nonce and gasLimit is an int

**Comment by developer2belfrics** [comment]
Yes. I Changed the nonce and gas limit to int but still, i am getting insufficient fund error

![Screen Shot 2021-03-18 at 8 40 18 AM](https://user-images.githubusercontent.com/57176610/111567895-bc285900-87c5-11eb-9007-cc038f864d67.png)

**Comment by developer2belfrics** [comment]
I canceled this transaction and initiated a new transaction.

**Comment by MariusVanDerWijden** [comment]
So this issue is resolved then?

**Comment by ligi** [comment]
@developer2belfrics Are you sure your node is fully synced?

**Comment by ligi** [comment]
And can you pleas post the console content as text not screenshots?

**Comment by MariusVanDerWijden** [comment]
This issue is quite stale now, closing
