### ISSUE TITLE
Allow users to choose where the blockchain is stored

### ISSUE THREAD

**Issue by cosban** [ethereum/go-ethereum#2248]
The blockchain is currently stored within the AppData/Roaming folder. Due to the fact that the combined size of the chain is rather large, many users will not want to store it there. I propose that the ability to set a custom location for storage of the blockchain be added. This can be something that the user has to enter in additional command-line arguments for. As long as the option is allowed, it will provide more usability to many people though.

**Comment by karalabe** [comment]
It was always allowed :) `--datadir=...`

**Comment by cosban** [comment]
Good work! Clearly the universe I'm from where this didn't exist has merged with the one where it did.
