### ISSUE TITLE
Should update docs - godep is archived

### ISSUE THREAD

**Issue by DevTenset** [ethereum/go-ethereum#22489]
Hello since go 1.11 is available go modules. godep and dep are depracted:
`As of 2020, Dep is deprecated and archived in favor of Go modules, which have had official support since Go 1.11. For more details, see https://golang.org/ref/mod.`

Docs shows depracted tools, for example:
`$ godep go install ./cmd/abigen
`
I think that should be change.

**Comment by MariusVanDerWijden** [comment]
Agreed! will fix, can you link me the docs where this is wrong?
