### ISSUE TITLE
[NOOB] HTTP Endpoint Creation and Location

### ISSUE THREAD

**Issue by SpeedMatchGaming** [ethereum/go-ethereum#22493]
I recently started up my own Geth node in my home and am trying to enable HTTP endpoints? I need to be able to enable the Http:// Endpoint and I need to then know where to find it. Any help would be amazing, considering I've been at this for several days now. so far I am able to enable the HTTP server but it looks like this and so I don't know what the actual link is...
![Screenshot (632)](https://user-images.githubusercontent.com/56319645/111022967-0efbae00-838b-11eb-9ebc-7208de48952f.png)

**Comment by ligi** [comment]
http://localhost:8545 ?

**Comment by SpeedMatchGaming** [comment]
I successfully got it to connect now I am running into trouble, it connects to my main wallet on Eth Mainnet, when I activate a transaction it says insufficient funds which is weird because I have funds in my main wallet.

**Comment by ligi** [comment]
is your node fully synced?

**Comment by SpeedMatchGaming** [comment]
yes the thing is that I am using Avado's Node it is all setup though

**Comment by SpeedMatchGaming** [comment]
I assume I need to create a wallet on Geth node and then fund it

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by SpeedMatchGaming** [comment]
its a Geth node the @ligi the supplier is Avado it is pre built that is all

**Comment by ligi** [comment]
but it's not really a geth issue - please ask on StackExchange
