### ISSUE TITLE
Section processing failed: "canonical block unknown" on upgrade to v1.10

### ISSUE THREAD

**Issue by jperaire** [ethereum/go-ethereum#22494]
#### System information

Geth version: v1.10.1
OS & Version: Ubuntu 20.04, but Geth is running inside the official docker image. 

The node was synced using Geth v1.9.25, and I just changed the docker image hoping to re-use the same chain data. 

I was running the node with an 8 GB RAM cap, but since getting the error, I increased it to 9 GB to see if that helped the issue. 

I also have ~100GB of SSD space left. 

Happy to answer any other questions. 

#### Actual behaviour
We are getting a `canonical block unknown` error. 

The error message appears after one of two possible info messages. Either a message which imports a new chain segment, or after it tries to upgrade the chain index. 

`geth              | 2021-03-14T16:23:15.030909637Z INFO [03-14|16:23:15.030] Imported new chain segment               blocks=1      txs=146      mgas=12.487 elapsed=2.268s      mgasps=5.504  number=12037750 hash="2110a4…f103a1" dirty=106.87MiB
geth              | 2021-03-14T16:23:15.582995709Z ERROR[03-14|16:23:15.582] Section processing failed                type=bloombits               error="canonical block #12029091 unknown"
`

`geth              | 2021-03-14T16:23:20.789550303Z INFO [03-14|16:23:20.789] Upgrading chain index                    type=bloombits               percentage=99
geth              | 2021-03-14T16:23:21.546963205Z ERROR[03-14|16:23:21.546] Section processing failed                type=bloombits               error="canonical block #12029091 unknown"
`

Even though I'm getting this error, though, geth continues to deep freeze and import blocks to the head of the chain:
`geth              | 2021-03-14T16:27:23.727250541Z INFO [03-14|16:27:23.727] Deep froze chain segment                 blocks=4      elapsed=2.359s      number=11947769 hash="a22a0e…4ead1f"
`

`geth              | 2021-03-14T16:27:28.382467746Z INFO [03-14|16:27:28.382] Imported new chain segment               blocks=1      txs=236      mgas=12.331 elapsed=4.692s      mgasps=2.628  number=12037770 hash="878008…56645a" dirty=141.76MiB
`

And also seems to continue generating the snapshot syncs:

`geth              | 2021-03-14T16:27:28.365493301Z INFO [03-14|16:27:28.365] Aborting state snapshot generation       root="45d191…3a66a4" in="0ac347…207cb5" at="87f4e8…734135" accounts=5119345 slots=20326591 storage=1.78GiB elapsed=13m16.055s  eta=1572h4m16.038s
geth              | 2021-03-14T16:27:28.366673341Z INFO [03-14|16:27:28.366] Resuming state snapshot generation       root="fca3d8…9c5c61" in="0ac347…207cb5" at="87f4e8…734135" accounts=5119345 slots=20326591 storage=1.78GiB elapsed=13m16.056s  eta=1572h4m23.147s
`

(Is this something to be worried about?)

**Comment by karalabe** [comment]
Did your node ever crash that could explain some missing data? Do you have some startup logs to share? Could you try to explicitly load up that unknown blocks via `eth_getBlock` and see what is produces?

**Comment by jperaire** [comment]
**Did your node ever crash that could explain some missing data?**
It's possible - I had the docker limits set a little low for a period of time so the node would occasionally crash and restart. But that happened pre v1.10 and I didn't see this issue. 

**Do you have some startup logs to share? **
Unfortunately I don't have the logs from the first 1.10 startup, as I shut down the docker container and restarted it. (In case something wonky had happened on initialization). I do have the initialization logs for the second startup though. (Which does show an unclean shutdown)

`{"log":"INFO [03-14|19:27:41.506] Starting Geth on Ethereum mainnet... \n","stream":"stderr","time":"2021-03-14T19:27:41.507451812Z"}
{"log":"INFO [03-14|19:27:41.517] Maximum peer count                       ETH=50 LES=0 total=50\n","stream":"stderr","time":"2021-03-14T19:27:41.518023554Z"}
{"log":"INFO [03-14|19:27:41.518] Smartcard socket not found, disabling    err=\"stat /run/pcscd/pcscd.comm: no such file or directory\"\n","stream":"stderr","time":"2021-03-14T19:27:41.518660627Z"}
{"log":"WARN [03-14|19:27:41.519] Found deprecated node list file /root/.ethereum/geth/trusted-nodes.json, please use the TOML config file instead. \n","stream":"stderr","time":"2021-03-14T19:27:41.520066924Z"}
{"log":"INFO [03-14|19:27:41.520] Set global gas cap                       cap=25000000\n","stream":"stderr","time":"2021-03-14T19:27:41.520468362Z"}
{"log":"INFO [03-14|19:27:41.520] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB\n","stream":"stderr","time":"2021-03-14T19:27:41.520849538Z"}
{"log":"INFO [03-14|19:27:41.520] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=2.00GiB handles=524288\n","stream":"stderr","time":"2021-03-14T19:27:41.52116497Z"}
{"log":"INFO [03-14|19:27:55.297] Opened ancient database                  database=/root/.ethereum/geth/chaindata/ancient\n","stream":"stderr","time":"2021-03-14T19:27:55.297974099Z"}
{"log":"INFO [03-14|19:27:55.375] Initialised chain configuration          config=\"{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, YOLO v3: \u003cnil\u003e, Engine: ethash}\"\n","stream":"stderr","time":"2021-03-14T19:27:55.375908132Z"}
{"log":"INFO [03-14|19:27:57.004] Disk storage enabled for ethash caches   dir=/root/.ethereum/geth/ethash count=3\n","stream":"stderr","time":"2021-03-14T19:27:57.004869025Z"}
{"log":"INFO [03-14|19:27:57.005] Disk storage enabled for ethash DAGs     dir=/root/.ethash               count=2\n","stream":"stderr","time":"2021-03-14T19:27:57.005796879Z"}
{"log":"INFO [03-14|19:27:57.009] Initialising Ethereum protocol           network=1 dbversion=8\n","stream":"stderr","time":"2021-03-14T19:27:57.010048126Z"}
{"log":"INFO [03-14|19:27:58.143] Loaded most recent local header          number=12038392 hash=\"474011…782369\" td=22044421456622451933437 age=44m13s\n","stream":"stderr","time":"2021-03-14T19:27:58.144063032Z"}
{"log":"INFO [03-14|19:27:58.143] Loaded most recent local full block      number=12038392 hash=\"474011…782369\" td=22044421456622451933437 age=44m13s\n","stream":"stderr","time":"2021-03-14T19:27:58.144174607Z"}
{"log":"INFO [03-14|19:27:58.143] Loaded most recent local fast block      number=12038392 hash=\"474011…782369\" td=22044421456622451933437 age=44m13s\n","stream":"stderr","time":"2021-03-14T19:27:58.144196116Z"}
{"log":"INFO [03-14|19:27:58.147] Loaded last fast-sync pivot marker       number=12036044\n","stream":"stderr","time":"2021-03-14T19:27:58.147761398Z"}
{"log":"INFO [03-14|19:27:58.170] Upgrading chain index                    type=bloombits percentage=99\n","stream":"stderr","time":"2021-03-14T19:27:58.171137329Z"}
{"log":"INFO [03-14|19:27:58.171] Resuming state snapshot generation       root=\"aad3e1…f51433\" at=\"0c1b15…b72cc6\" accounts=5758721 slots=22721119 storage=1.98GiB elapsed=\"753.693µs\"\n","stream":"stderr","time":"2021-03-14T19:27:58.171910911Z"}
{"log":"INFO [03-14|19:27:58.170] Loaded local transaction journal         transactions=0 dropped=0\n","stream":"stderr","time":"2021-03-14T19:27:58.172118812Z"}
{"log":"INFO [03-14|19:27:58.172] Regenerated local transaction journal    transactions=0 accounts=0\n","stream":"stderr","time":"2021-03-14T19:27:58.172367775Z"}
{"log":"WARN [03-14|19:27:58.172] Switch sync mode from fast sync to full sync \n","stream":"stderr","time":"2021-03-14T19:27:58.172989481Z"}
{"log":"WARN [03-14|19:27:58.174] Unclean shutdown detected                booted=2021-03-14T04:58:25+0000 age=14h29m33s\n","stream":"stderr","time":"2021-03-14T19:27:58.174677711Z"}
{"log":"WARN [03-14|19:27:58.174] Unclean shutdown detected                booted=2021-03-14T05:46:14+0000 age=13h41m44s\n","stream":"stderr","time":"2021-03-14T19:27:58.174737216Z"}
{"log":"INFO [03-14|19:27:58.174] Starting peer-to-peer node               instance=Geth/v1.10.1-stable-c2d2f4ed/linux-amd64/go1.16\n","stream":"stderr","time":"2021-03-14T19:27:58.174822025Z"}
{"log":"INFO [03-14|19:27:58.301] New local node record                    seq=230 id=43b314f7c04ab493 ip=127.0.0.1 udp=30303 tcp=30303\n","stream":"stderr","time":"2021-03-14T19:27:58.302061923Z"}
` 


**Could you try to explicitly load up that unknown blocks via `eth_getBlock` and see what is produces?**
All of the blocks between 12029091 and 12031360 seem to produce `null`, although 12031361+ seem to exist. Looks like I'm missing a whole bunch of data - probably user error (mine). I guess the question then is, is it possible to salvage just these blocks? Or do I need to do a full resync?

**Comment by karalabe** [comment]
@jperaire What you can try to do is `debug.setHead('0xblocknum')`, where `blocknum` should be the hex of the block number to rewind to. You should set that to prior the missing one. It will probably rewind more, until it reaches a block that has state available.

Hmm, based on `Loaded last fast-sync pivot marker number=12036044`, it seems you synced recently. Doing a sethead to before that should still work, it will reenable fast sync and in theory should help fix things. Could you try this?

Note, there's a none 0 change you'll need to resync if this doesn't work. But in theory it should work.

**Comment by jperaire** [comment]
OK - it seems to have worked! 
`geth              | 2021-03-16T16:33:28.146086900Z ########## BAD BLOCK #########
geth              | 2021-03-16T16:33:28.146101051Z Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, YOLO v3: <nil>, Engine: ethash}
geth              | 2021-03-16T16:33:28.146399648Z 
geth              | 2021-03-16T16:33:28.146411759Z Number: 12050728
geth              | 2021-03-16T16:33:28.146429651Z Hash: 0x5b00907b2a197f53995fecdf51ca49a80c8a542d2c15539a3efe6294381531ff
geth              | 2021-03-16T16:33:28.146441712Z 
geth              | 2021-03-16T16:33:28.146453545Z 
geth              | 2021-03-16T16:33:28.146465323Z Error: unknown ancestor
geth              | 2021-03-16T16:33:28.146476935Z ##############################
`

But it seems to have recovered after that, and am now importing new block headers and receipts, and `eth.getBlock` now has a block for 12029091 (and beyond). 

Do I need to worry about the snapshots I generated with the bad block? Or should those be taken care of automatically?

Thanks!

**Comment by jperaire** [comment]
EDIT: Looks like geth automatically cleared and restarted the snapshot generation. Should be good to go! Thanks!
