### ISSUE TITLE
Estimation gas problem

### ISSUE THREAD

**Issue by voronindev** [ethereum/go-ethereum#22499]
I've noticed after updating to 1.10.1 (ropsten chain) we have problem on tx gas limit estimation (Or I'm doing something wrong). Sometimes, tx estimation is not enough, up to several times. One of the interesting moments, that we have met:
```
// Let assume we are calling one contract in sequentially:
1) transferFrom(A, B, x) 45,415 gas limit // tansfer from A -> B x tokens
2) transferFrom(A, B, x) 36,415 gas limit // tansfer from A -> B x tokens
```
Last tx has been estimated to 36,415 - it might be EVM optimizations, I guess. But it failed due to `Out of Gas`.
Here they are:
1) https://ropsten.etherscan.io/tx/0x2c6111b36e2e68c3d145265b93dc785b3958c0ea9957c6e06c9d3cb98d444465 (Ok)
2) https://ropsten.etherscan.io/tx/0xdbe1a610cea66d19b5575642b8555a9050b5eac026517aff91aea02530083d13 (Failed)

The next interesting moment we have here very similar case:
```
// Let assume we are calling one contract in sequentially, again:
1) transferFrom(A, B, x) 45,415 gas limit // tansfer from A -> B x tokens
2) transferFrom(A, B, x) 45,415 gas limit // tansfer from A -> B x tokens
3) transferFrom(A, B, x) 36,415 gas limit // tansfer from A -> B x tokens
```
1) https://ropsten.etherscan.io/tx/0xcef794158c1ec7f5c6f04fd0575c0e90ce88c3949db7dff1abd120f7baf77470 (Ok)
2) https://ropsten.etherscan.io/tx/0x4445d678c7a754f430627e40eeae1cfc038472645d1b5125f1e0bcbe506e8016 (Ok)
3) https://ropsten.etherscan.io/tx/0x8accaa855f0a42fd94c6ec107f87fbb0fcd17f7507bd576afaee9943e67b465d (Failed)

These cases are could be reproduced easily. Idk why that working like this. Each case handled txs into one block. But I have some other cases, but it's difficult to catch.

**Comment by karalabe** [comment]
Gas estimation is problematic if you estimate on top of something that changes the state. The first tx may or may not be in the pending block, which means it may or may not influence the execution of the second one. Do you have a contract code / tx repro that we could run ourselves to see if we can trigger it? Otherwise it's hard to say what was the condition on your node.

**Comment by voronindev** [comment]
I'm understanding. But here we have 2 txs broadcast with one by one, and later 3 of them. Both cases we have the same problem with the last tx (it's failed always). I thought it's might be because of the last tx changing the state (amount of tokens) to zero, and due to state releasing we have some kind of "discount". But it's not correct., and . Code you can take from here:
https://ropsten.etherscan.io/address/0xbf4d811e6891ed044d245cafcc4caa96c969204d#code

**Comment by ligi** [comment]
Can you provide more information on how you do the estimation? Ideally in the form of a small repro?

**Comment by holiman** [comment]
@voronindev could you show exactly how you perform the gas estimation, as in, what the RPC method invocation is used?
