### ISSUE TITLE
Using Mist for a Marriage Contract

### ISSUE THREAD

**Issue by F1LT3R** [ethereum/go-ethereum#225]
In February I am getting married, so naturally I am wondering whether Mist would support a marriage contract?

If so, what would would that look like?

If not, why not?

**Comment by fjl** [comment]
Sorry, this issue tracker is for problems with the Go implementation and not for general questions about ethereum. Please ask this question on the [official forum](https://forum.ethereum.org). 

If you're interested in how it might look someday, check out [the UX presentation](https://www.youtube.com/watch?v=IgNjs_WaFSc) by @alexvandesande.

**Comment by F1LT3R** [comment]
Got it, thanks fjl
