### ISSUE TITLE
Can no longer install devp2p tool, it fails during installation.

### ISSUE THREAD

**Issue by ChrisKaelinJr** [ethereum/go-ethereum#22503]
#### System information

OS & Version: Ubuntu 20.04 (LTS)

#### Expected behaviour
Following command should install tool without issue, as it has done in the past:

`go get -u github.com/ethereum/go-ethereum/cmd/devp2p`

#### Actual behaviour
On a fresh image, after installing go, executing that command (as defined in: https://geth.ethereum.org/docs/developers/dns-discovery-setup), it faills.

#### Steps to reproduce the behaviour
1.  apt-get install golang
2. go get -u github.com/ethereum/go-ethereum/cmd/devp2p

#### Trace

![image](https://user-images.githubusercontent.com/2815937/111215132-29ab6e00-85a9-11eb-8b91-f6e541dc345f.png)

**Comment by karalabe** [comment]
This seems to be a peculiarity in Go. If you do `go get -u`, it will actually force update all the dependencies of the go-ethereum repo too, which breaks the pinned versions in `go mod`. I think nowadays if you do `go get` without `-u` it should work. Could you try that?

**Comment by ChrisKaelinJr** [comment]
> This seems to be a peculiarity in Go. If you do `go get -u`, it will actually force update all the dependencies of the go-ethereum repo too, which breaks the pinned versions in `go mod`. I think nowadays if you do `go get` without `-u` it should work. Could you try that?

Same thing. I reset the VM to a clean snapshot (fresh install) before trying again, but without the -u.

![image](https://user-images.githubusercontent.com/2815937/111376799-4bbef200-8676-11eb-85e1-47e415184b6b.png)

**Comment by ChrisKaelinJr** [comment]
This is a work-around but it seems to work:

`apt-get install golang`
`go export GO111MODULE=on`
`go get github.com/cloudflare/cloudflare-go@v0.10.2`
`go get github.com/ethereum/go-ethereum/cmd/devp2p`

Then to run (test):
`~go/bin/devp2p discv4 crawl -timeout 1m node-test.json`

I'll have to manually add it to the PATH file it seems, but it's a workable solution for now until updated I guess. Current version is v0.14.0 and there have been a few breaking changes since v0.10.2 it seems.

**Comment by karalabe** [comment]
What version of Go are you using? I think prior to 1.16 you need to explicitly set GO111MODULE=on like you did, so `GO111MODULE=on go get -u github.com/ethereum/go-ethereum/cmd/devp2p`. Should not be required on GO 1.16 any more. At least it seems to work for me, but haven't tried nuking a fresh env.

**Comment by ChrisKaelinJr** [comment]
Yeah, 1.13.8 as installed from `apt-get install golang` on Ubuntu 20.04 (LTS)

**Comment by ChrisKaelinJr** [comment]
I mean, it's working. I can close this issue but perhaps it would be nice to include that information (or my steps) in the documentation? 

I don't personally use go beyond this suite, which is quite good (kudos), and try to do as much as possible in languages that I am more familiar with. I'm sure it would benefit others.

Thank you for the help, I appreciate it.

**Comment by fjl** [comment]
The documentation has been updated to remove the `-u` flag, and we are upgrading to the newer CloudFlare client API in #22588
