### ISSUE TITLE
Random DB reset while syncing

### ISSUE THREAD

**Issue by TheRealVira** [ethereum/go-ethereum#22516]
#### System information

Geth version: `geth version`

```
Geth
Version: 1.10.1-stable
Git Commit: c2d2f4ed8f232bb11663a1b01a2e578aa22f24bd
Architecture: amd64
Go Version: go1.16
Operating System: linux
GOPATH=
GOROOT=go
```

OS & Version: Windows/Linux/OSX

```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

#### Expected behaviour

Syncing fast till currentBlock equals highestBlock.

#### Actual behaviour

Syncing slow till about 35% and then the db reset leaving me with a currentlbock of 0.

#### Steps to reproduce the behaviour

My service file is looking like followed:

```
[Unit]
Description=The Ethereum Blockchain Command Line Interface
Documentation=man:geth(1)
Requires=network.target

[Service]
Type=forking
User=%I
ExecStart=/usr/bin/geth --syncmode fast --cache=4096 --mine --miner.threads=15 --miner.etherbase 0x0467f8979845f87614d36abe7de8fbb1968f919f
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

I have enabled it over systemctl and it is starting on boot. On my firewall I have port 30303 forwarded.

Been stuck on this now for about five days and haven't gotten one successful sync so far. I am using M.2 SSDs and there is more than enough space on them (500GB+).

**Comment by TheRealVira** [comment]
I now synced up with mainnet by executing the following command by hand:

`geth -rpc`

Still not sure why the descriped service didn't work.

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
