### ISSUE TITLE
Feature: Check free disk space before "snapshot prune-state"

### ISSUE THREAD

**Issue by yorickdowne** [ethereum/go-ethereum#22518]
# Rationale

"snapshot prune-state" in testing takes additional disk space while it is running.

Users may prune because they are low on space, and running out during prune might worsen the situation. Maybe even up to DB corruption, going by initial reports.

# Implementation

Test for a safe amount of free space, and refuse to run if sufficient space is not present.
Bonus: Output a WARN log if free disk space is at or under N GiB, with N close to but over minimum needed free space, to be careful with space usage until prune has completed.

**Comment by ligi** [comment]
Thanks - this is a great suggestion!

**Comment by yorickdowne** [comment]
Broad implementation ideas:
- Check for estimated space needed for state iteration file
- If geth runs out of space while creating the file, abort
- Check for space needed before DB prune, abort if not enough
- After DB prune, delete state iteration file: This should leave enough space for DB compaction step
- Check for space needed before DB compaction, abort if not enough

**Comment by yorickdowne** [comment]
A user reports corrupting DB with 25 GiB free when starting prune. I asked about the size of the Geth DB(s) at that time.
