### ISSUE TITLE
snap sync state sync no progress

### ISSUE THREAD

**Issue by Trackerming** [ethereum/go-ethereum#22522]
#### System information
  - Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1039-aws x86_64)
  - AWS  c5.xlarge 4核8G  1T AWS gp2 EBS SSD
Geth version: `geth version` 
  - Geth/v1.10.1-stable-c2d2f4ed/linux-amd64/go1.16
OS & Version: Windows/Linux/OSX
  - Ubuntu
Commit hash : (if `develop`)

#### Expected behaviour
- State sync and download block receipts normal when I sync mainnet from genesis.

#### Actual behaviour
 1.  start geth, Imported new block receipts normal and  the state sync log is `State sync in progress                   synced=0.27% state=671.41MiB accounts=671686@61.53MiB slots=4205843@596.63MiB codes=4634@13.26MiB eta=3085h26m22.542s`
 2.  after imported all new block receipts, the state sync's log is same above.
 3.  after I restart the geth,`State sync` normal and finish sync normal 

#### Steps to reproduce the behaviour
 -  `Regenerated local transaction journal transactions=0 accounts=0`, Is it deadlock?
 - the log file and the stack info are in the attachment.
[stacktrace.txt](https://github.com/ethereum/go-ethereum/files/6160791/stacktrace.txt)
[statesyncprogress.txt](https://github.com/ethereum/go-ethereum/files/6160792/statesyncprogress.txt)

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
I don't know why you say "no progress". Looking at the output (last two lines)
```
INFO [03-18|05:04:49.027] State sync in progress                   synced=99.97% state=80.39GiB   accounts=125356053@22.53GiB slots=410150930@56.08GiB codes=365646@1.78GiB    eta=3.739s
INFO [03-18|05:04:52.060] State sync in progress                   synced=99.99% state=80.40GiB   accounts=125377626@22.54GiB slots=410164192@56.08GiB codes=365703@1.78GiB    eta=-2.466s
```
It went from `125356053` accounts to `125377626`, and both slots and codes was increasing too. It was finishing up the snap sync just fine. 

`Regenerated local transaction journal transactions=0 accounts=0` is just a background thread which from time to time flushes 'local' transactions to disk (you have none). 

Everything looks good to me. Feel free to reopen if I missed something.

**Comment by Trackerming** [comment]
I say this because I must restart geth when It download all the receipts,If I don`t restart the log is always `State sync in progress                   synced=0.27% state=671.41MiB accounts=671686@61.53MiB slots=4205843@596.63MiB codes=4634@13.26MiB eta=3085h26m22.542s`, Is it a issue? I'm not sure.
