### ISSUE TITLE
clef init, cant find the masterseed.json file as per instructions...

### ISSUE THREAD

**Issue by wildernessfarming** [ethereum/go-ethereum#22520]
I named this linux nistallation "shamoo"

after running clef init, and setting the password, it says "A master seed has been generated into /home/shamoo/.clef/masterseed.json"

My file directory starts with shamoo/home there is no .clef directory or masterseed.json   I searched for both.
What am I missing?

**Comment by holiman** [comment]
Did you try `ls -la`? Without `-la` it won't show 'hidden' files (files that start with `.`)

**Comment by wildernessfarming** [comment]
I was able to find it with that command, thanks, Im new to linux...
