### ISSUE TITLE
ropsten network always Hard fork and higher than the official website https://ropsten.etherscan.io/

### ISSUE THREAD

**Issue by princ1** [ethereum/go-ethereum#22525]
Hi，I have setup a ropsten network for eth ，and find that its higher than the official website https://ropsten.etherscan.io/

=====logs====
Mar 18 09:51:57 localhost ap-eth[4169]: INFO [03-18|09:51:57.806] Imported new chain segment               blocks=1   txs=21       mgas=1.231  elapsed=16.671ms    mgasps=73.848  number=9860631 hash="1dd891…93a3d9" dirty=3.15MiB
============
and then， the hight show in https://ropsten.etherscan.io/ is 9858105
==============
./geth version
Geth
Version: 1.10.0-stable
Git Commit: 56dec25ae26bf749b93c3ea69538fabea60c5768
Git Commit Date: 20210303
Architecture: amd64
Go Version: go1.16
Operating System: linux
GOPATH=
GOROOT=go
=============
ExecStart=/opt/ethereum/bin/geth --datadir /opt/ethereum/ethereumdata --mine --miner.noverify --syncmode "fast" --rpc --ropsten --rpcaddr=0.0.0.0 --http.port=18545 --ws.port=18546 --port 30303 --cache=4096 --txpool.locals=0xwallet_replaced --miner.extradata="testg" --miner.etherbase=0xwallet_replaced --txpool.pricelimit=10000000000 --rpccorsdomain=* --ws.api=admin,db,eth,debug,net,shh,txpool,personal,web3 --miner.gasprice 4000000000 --miner.gaslimit 4712388 --rpcvhosts=*

============
It's very strange that higher then official website，anybody can help me and tell me how to fix it?
Or show me some peers ,let me resync it，thx very much！！！

**Comment by MariusVanDerWijden** [comment]
You need to update your version to `1.10.1` The old version (`1.10.0`) did not have the new fork (berlin) enabled. Update your node and you should be able to sync the network again
