### ISSUE TITLE
Bug: If snapshot prune-state runs out of space during DB compaction, DB will be corrupted

### ISSUE THREAD

**Issue by yorickdowne** [ethereum/go-ethereum#22523]
#### System information

Geth version: 1.10.1
OS & Version: Linux

#### Expected behaviour

snapshot prune-state can survive running out of disk space without corrupting the DB

#### Actual behaviour

A user with < 25 GiB free before starting snapshot prune-state reports that the process "hung" at DB compaction, and he was left with a corrupted DB.

Additional feedback from user: "best i can remember was that it was only 3 lines of compacting, then i went to sleep and woke up and 10 hours later it was on the third status like still. meaning, it looked like it wasn’t progressing after 10 hours."

**Comment by ligi** [comment]
Yes we agree there should be a warning in this case.

**Comment by ligi** [comment]
Thanks for the report - will close the issue - tracked in #22518

**Comment by samlavery** [comment]
even open source contributors, need a day job
