### ISSUE TITLE
Can't get a viable ws or http connection to geth via node console

### ISSUE THREAD

**Issue by cyrusadkisson** [ethereum/go-ethereum#22527]
#### System information

Geth version: 1.10.1 from ubuntu ppas
OS & Version: Ubuntu Linux 20.04.1 64-bit

Moving "side issue" discussion from another bug report:

me: "(Side issue: can't connect to ws or http or ipc and spent all day trying. Internally, from another computer, ports, firewalls, tried to sideload web3, etc. I finally gave up, loaded web3 into node console, started using an Infura endpoint and gave up on geth entirely.)"

@holiman "Now this is a lot more concerning to me. Please provide more info, because connecting to ws or http always works like a charm for me, and it's very important that this works well."

-------

At first I was doing "geth --syncmode fast" (and letting it fully sync to eth.syncing false) and then "geth attach" in another terminal window. But because web3 is so out of date I had to scrap that plan.

So I stared geth with ws and/or http and attempted to connect from node console on another computer. 

These commands work against infura but not against the geth instance.

```
var Web3 = require('web3');
var web3 = new Web3('ws://192.168.1.121:8546');
//var web3 = new Web3('https://mainnet.infura.io/v3/MYHEXENDPOINT');
var abi = [{"constant":false,"inputs":[],"name":"setLocked","outputs":[],"type":"function"},{"constant":true,"inputs":[],"name":"getWhatHappened","outputs":[{"name":"","type":"string"}],"type":"function"},{"constant":true,"inputs":[],"name":"getLocked","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":false,"inputs":[{"name":"col","type":"uint8"},{"name":"row","type":"uint8"}],"name":"buyTile","outputs":[],"type":"function"},{"constant":false,"inputs":[],"name":"kill","outputs":[],"type":"function"},{"constant":false,"inputs":[{"name":"col","type":"uint8"},{"name":"row","type":"uint8"},{"name":"_s","type":"string"}],"name":"setStatus","outputs":[],"type":"function"},{"constant":false,"inputs":[{"name":"col","type":"uint8"},{"name":"row","type":"uint8"},{"name":"newowner","type":"address"}],"name":"setOwner","outputs":[],"type":"function"},{"constant":true,"inputs":[{"name":"col","type":"uint8"},{"name":"row","type":"uint8"}],"name":"getLastFarm","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"col","type":"uint8"},{"name":"row","type":"uint8"},{"name":"index","type":"uint256"},{"name":"_block","type":"int8[5]"}],"name":"editBlock","outputs":[],"type":"function"},{"constant":false,"inputs":[{"name":"col","type":"uint8"},{"name":"row","type":"uint8"},{"name":"blocktype","type":"int8"}],"name":"farmTile","outputs":[],"type":"function"},{"constant":false,"inputs":[{"name":"col","type":"uint8"},{"name":"row","type":"uint8"},{"name":"_n","type":"string"}],"name":"setName","outputs":[],"type":"function"},{"constant":true,"inputs":[{"name":"col","type":"uint8"},{"name":"row","type":"uint8"}],"name":"getName","outputs":[{"name":"","type":"string"}],"type":"function"},{"constant":true,"inputs":[{"name":"col","type":"uint8"},{"name":"row","type":"uint8"}],"name":"getStatus","outputs":[{"name":"","type":"string"}],"type":"function"},{"constant":true,"inputs":[{"name":"col","type":"uint8"},{"name":"row","type":"uint8"}],"name":"getOwner","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":false,"inputs":[],"name":"empty","outputs":[],"type":"function"},{"constant":true,"inputs":[{"name":"col","type":"uint8"},{"name":"row","type":"uint8"}],"name":"getBlocks","outputs":[{"name":"","type":"int8[5][]"}],"type":"function"},{"inputs":[],"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"col","type":"uint8"},{"indexed":false,"name":"row","type":"uint8"}],"name":"TileChanged","type":"event"}];
etheria = new web3.eth.Contract(abi,"0xb21f8684f23dbb1008508b4de91a0aaedebdb7e4");
etheria.methods.getOwner(15,9).call(function(error, result) { console.log(result) });
```
result when working against infura (which is the correct response)
```
> etheria.methods.getOwner(15,9).call(function(error, result) { console.log(result) });
Promise { <pending> }
> 0xcf684DFB8304729355B58315E8019B1aa2AD1Bac
```
result when failing against the geth ws or http
```
> etheria.methods.getOwner(15,9).call(function(error, result) { console.log(result) });
Promise { <pending> }
>
```
I have verified that the firewall of the geth instance is off (ufw disabled) and that installing something like httpd or sshd on that computer shows ports 80 and 22 open on the host computer from the client computer. nmap never shows any other ports listening for connections.

Any thoughts here? It's highly likely I'm just doing something dumb. (I've been out of the game for a long time.)

**Comment by holiman** [comment]
In order to start http or ws, you need to do `geth --http`. or `--ws`

**Comment by cyrusadkisson** [comment]
I definitely am starting with 

`geth --ws --ws.port 8546 --ws.origins "*" --ws.api eth,net,web3`

The geth logs then say 

`WebSocket enabled url=ws://127.0.0.1:8546`

And yet when I try to use this endpoint from another computer, I get

```
> (node:26905) UnhandledPromiseRejectionWarning: Error: connection not open on send()
    at Object.ConnectionError (/home/cyrus/node_modules/web3-core-helpers/lib/errors.js:66:23)
    at Object.ConnectionNotOpenError (/home/cyrus/node_modules/web3-core-helpers/lib/errors.js:49:21)
```
ufw on the host machine is inactive
nmap shows 

```
Host is up (0.00013s latency).
Not shown: 9999 closed ports
PORT   STATE SERVICE
22/tcp open  ssh

Nmap done: 1 IP address (1 host up) scanned in 0.12 seconds
```
I can ssh across the local network so it seems unlikely the router isn't doing something funky. 

Netstat on the host machine shows tcp running on 127.0.0.1:8546 and shows /geth at the line.

So why is my local machine reporting the connection error when attempting to interact with it?

**Comment by cyrusadkisson** [comment]
Nevermind. I got it. I had to explicitly set the ws.addr to the local network hostname 192.168.1.121.

Thanks for your help.

**Comment by holiman** [comment]
Yeah 127.0.0.1 is localhost, you want to use 0.0.0.0 , or, what you eventually did.
