### ISSUE TITLE
Faucet / LES not working since v1.10.1

### ISSUE THREAD

**Issue by maxsam4** [ethereum/go-ethereum#22531]
I've tried v1.10.1 and latest master but the (Goerli) faucet is not able to connect to any nodes. I've reset/resynced both the faucet and the node but still no connection. The node is added as a bootnode to the faucet so it is discovered, just not connected.

```
peercount=0 tried=1 static=1
```

Reverting to an older version of the faucet does not fix the problem. Reverting to an older version of the node is not possible since Goerli has already upgraded to Berlin.

Edit, I increased logging and found the following in faucet's logs against my node
```
"ForkID rejected - local incompatible or needs update"
```
Both the faucet and the node are updated so it's a bit weird.

Some more potentially interesting logs from the faucet:
```
INFO [03-19|12:55:16.457] Initialised chain configuration          config="{ChainID: 5 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: <nil>, Muir Glacier: <nil>, Berlin: <nil>, YOLO v3: <nil>, Engine: clique}"
INFO [03-19|12:55:16.457] Added trusted checkpoint                 block=4358143 hash="29fa24…7c5324"
INFO [03-19|12:55:16.457] Loaded most recent local header          number=0 hash="bf7e33…b88c1a" td=1 age=2y1mo4w
INFO [03-19|12:55:16.458] Configured checkpoint oracle             address=0x18CA0E045F0D772a851BC7e48357Bcaab0a0795D signers=5 threshold=2
INFO [03-19|12:55:16.458] Starting peer-to-peer node               instance=Geth/v1.10.2-unstable-91726e8a-20210316/linux-amd64/go1.16.2
```

**Comment by maxsam4** [comment]
Replacing https://github.com/ethereum/go-ethereum/blob/d3040a80d7a0721297cfac93b82e0e9428ddd3d1/cmd/faucet/faucet.go#L253
with 
```
cfg.Genesis = core.DefaultGoerliGenesisBlock()
```
fixes the issue.

This means that old genesis configs are no longer being processed properly. I'm using https://github.com/goerli/testnet/blob/master/geth/goerli.genesis as the genesis file and it was working fine till a couple of of upgrades ago.

**Comment by karalabe** [comment]
@maxsam4 AFAIK the faucet uses a custom network/chain config (i.e. there's no notion of --goerli or whatnot). If so, you'll need to reinit the faucet with the updated goerli chain spec (`geth --datadir /path/to/your/faucet init goerli.json`) to set the berlin fork number, otherwise it will be unaware of it. Did you do that?

**Comment by karalabe** [comment]
Ah, apologies, there's a genesis flag for the faucet. Hmmm, did you specify the updated spec with the Berlin number in there?

**Comment by karalabe** [comment]
Doesn't seem so `INFO [03-19|12:55:16.457] Initialised chain configuration          config="{ChainID: 5 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: <nil>, Muir Glacier: <nil>, Berlin: <nil>, YOLO v3: <nil>, Engine: clique}"`

This said even Istanbul is `nil`, and Berlin too. You need to get an updated genesis json from the goerli team.

**Comment by karalabe** [comment]
I guess this worked previously because the faucet didn't execute anything, so it didn't care what fork it's in. However AFAIK @zsfelfoldi added the fork ID to les/4, so from now on even light clients care about being on the same fork (which in general is a good thing to do).

**Comment by maxsam4** [comment]
Thanks @karalabe, that explains it. 

Honestly, I don't really want to keep updating the genesis file manually. Would it be fine if I submit a PR that adds `--goerli` and `--rinkeby` flags to the faucet?

ps Remember to update the genesis file when upgrading the Rinkeby faucet :)

**Comment by karalabe** [comment]
I'm going to close this issue as not-a-bug, but we can debate your proposal on the PR.
