### ISSUE TITLE
"only replay-protected (EIP-155) transactions allowed over RPC" error when try to submit a transaction in Ropsten network

### ISSUE THREAD

**Issue by mdeliadi** [ethereum/go-ethereum#22546]
#### System information

Geth version: Gemini Sigma (v1.10.1)
OS & Version: Debian GNU/Linux 9.6 (stretch)
Commit hash : c2d2f4e

#### Expected behaviour

Being able to submit a transaction over Ropsten network.

#### Actual behaviour

I'm not able to submit any kind of transaction over Ropsten network, when I try I get the error "only replay-protected (EIP-155) transactions allowed over RPC".
Adding `--rpc.allow-unprotected-txs` or switching to a different testnet fix this issue, but the potential bug still remains.

#### Steps to reproduce the behaviour

1. Try to submit a transaction over Ropsten network.

#### Startup command

`--ropsten --rpc --rpcaddr "0.0.0.0" --http.corsdomain "*" --http.vhosts "*" --http.port 8545 --http.api db,eth,net,web3,personal,rpc --ws --ws.port 8546 --port 30303 --whitelist 6485846=0x43f0cd1e5b1f9c4d5cda26c240b59ee4f1b510d0a185aa8fd476d091b0097a80 --syncmode full`

**Comment by ligi** [comment]
Why do you need to use non EIP-155 transactions?
Why do you think this is a bug?

**Comment by mdeliadi** [comment]
@ligi because it's a private test node and always worked before? If it's not a bug, why it's working in any other testnet except Ropsten?

**Comment by ligi** [comment]
Using non EIP-155 transactions is not a good idea as it does not have replay protection - you should really switch to using EIP-155. What is your pipeline here btw?
Also which other testnet did it work on (that might then actually be a bug - it should fail on all networks AFAIK)

**Comment by mdeliadi** [comment]
@ligi I see, I will try to talk with our other blockchain developers then - please forgive my ignorance, I'm more a server guy than a blockchain one.

Relating to the other testnet, iI've double-cheked it and now I'm not really sure about it - it could have been a server that hadn't yet been updated, so please dismiss that statement.

I'm closing this issue then, thanks for your help!
