### ISSUE TITLE
Offline Pruning with Ancient Chain Data Directory

### ISSUE THREAD

**Issue by 0xj0e1** [ethereum/go-ethereum#22542]
#### System information

Geth version: 1.10.1 stable
OS & Version: Linux Ubuntu 20.04.2 LTS
Commit hash : (if `develop`)

#### Expected behaviour

Expect geth to prune state with ancient chain data directory using:

`geth snapshot prune-state --datadir.ancient`

#### Actual behaviour

Unable to prune state with or without the ancient data directory flag

When attempting to offline prune state without the ancient data directory:

`geth snapshot prune-state` 
`Fatal: Could not open database: ancient chain segments already extracted, please set --datadir.ancient to the correct path`

But when attempting to prune state with the ancient data directory flag I get:
 
`geth snapshot prune-state --datadir.ancient`
`Incorrect Usage: flag provided but not defined: -datadir.ancient`

#### Steps to reproduce the behaviour

Setup the ancient data directory option and attempt to prune state

`geth snapshot prune-state --datadir.ancient`

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
This was fixed in https://github.com/ethereum/go-ethereum/pull/22486 and will be shipped in the next release. Until then you can move the flag to the `geth` command scope, i.e. `geth --datadir.ancient /some/path snapshot prune-state`
