### ISSUE TITLE
Cannot verify contract deployed with abi

### ISSUE THREAD

**Issue by GooGrand** [ethereum/go-ethereum#22544]
System
OS & Version: Linux

#### Expected behaviour
Contracts deployed with sol code and with golang abi will have the same bytecode.

#### Actual behaviour
I found trouble with verifying contract. The error is "Error! Unable to generate Contract ByteCode and ABI".  The bytecodes are different so contract cannot be verified.

#### Steps to reproduce the behaviour
1. Make solidity code
2. Create an abi for it with abigen tool
3. Deploy contract on BSC 
4. Try to verify contract with solidity code

**Comment by MariusVanDerWijden** [comment]
I don't think this is an issue with abigen. If you specify the bytecode to abigen, it will not generate something different. The bytecode in the go binding is the deployed bytecode + the deployment code, maybe that is your problem?
Can you please provide some more details, so we can reproduce it (command line arguments, example contract, ...)

**Comment by wantedpixelmaza** [comment]
> I don't think this is an issue with abigen. If you specify the bytecode to abigen, it will not generate something different. The bytecode in the go binding is the deployed bytecode + the deployment code, maybe that is your problem?
> Can you please provide some more details, so we can reproduce it (command line arguments, example contract, ...)

Compiler debug log:
 Error! Unable to generate Contract ByteCode and ABI
 Found the following ContractName(s) in source code : ERC20Interface, Pussy, SafeMath
 But we were unable to locate a matching bytecode (err_code_2)
 For troubleshooting, you can try compiling your source code with the Remix - Solidity IDE and check for exception

**Comment by Tech4Money** [comment]
Help, 

I deployed and then forgot to verify the same day. Had a eroro with my txt file and now am unable to verify getting this error.  0x9a877792c4c9fb2278ec4e11289217a9a4567378

Compiler debug log:
 Error! Unable to generate Contract ByteCode and ABI
 Found the following ContractName(s) in source code : Address, Context, IERC20, IUniswapV2Factory, IUniswapV2Pair, IUniswapV2Router01, IUniswapV2Router02, Ownable, SRG, SafeMath
 But we were unable to locate a matching bytecode (err_code_2)

**Comment by Tech4Money** [comment]
> I don't think this is an issue with abigen. If you specify the bytecode to abigen, it will not generate something different. The bytecode in the go binding is the deployed bytecode + the deployment code, maybe that is your problem?
> Can you please provide some more details, so we can reproduce it (command line arguments, example contract, ...)

Hi are you able to help me?

**Comment by Hon3stP3rson** [comment]
hello??? i have the same issue

**Comment by husone** [comment]
we have the same error code 
Error! Unable to generate Contract ByteCode and ABI

But we were unable to locate a matching bytecode (**err_code_2**)
