### ISSUE TITLE
Help geth variable

### ISSUE THREAD

**Issue by rafalohaki** [ethereum/go-ethereum#22554]
geth --config ./config.toml --datadir ./node -unlock {your-validator-address} --password password.txt  --mine --gcmode archive --allow-insecure-unlock  --pprofaddr 0.0.0.0 --metrics --pprof

when i use this command, I get this error:
flag provided but not defined: -pprofaddr

**Comment by MariusVanDerWijden** [comment]
You need to use `--pprof.addr` instead of `--pprofaddr`

**Comment by rafalohaki** [comment]
./geth_linux --config ./config.toml --datadir ./node -unlock {your-validator-address} --password password.txt  --mine --gcmode archive --allow-insecure-unlock  --pprofaddr 0.0.0.0 --metrics --pprof
 
Fatal: Failed to unlock account xxx (no key for given address or file)

i have password in password.txt

**Comment by MariusVanDerWijden** [comment]
Allowing insecure unlock is not something you want to do. Are you trying to mine on a private network?

**Comment by rafalohaki** [comment]
its working now
