### ISSUE TITLE
No support for --rpc.gascap --rpc.txfeecap in dumpconfig command

### ISSUE THREAD

**Issue by fkbenjamin** [ethereum/go-ethereum#22556]
#### System information

Geth version: ` 1.10.1-stable-c2d2f4ed`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour

`geth --rpc.gascap A --rpc.txfeecap B dumpconfig`

should output a config file that includes both of these configurations in TOML format.

#### Actual behaviour

It puts out a config file without any of these parameters. I've also been struggling to add these parameters manually as their format is not documented. Can anyone provide me with a valid .toml file including these two parameters?

**Comment by fkbenjamin** [comment]
It seems that older versions of dumpconfig work. I was able to get this from a node running on `1.9.24-stable`:

```
[Eth]
...
...
RPCGasCap = 25000000
RPCTxFeeCap = 1e+00
```

Since `RPCTxFeeCap` expects a float64, is value `0.0` disabling the cap like `0` does for `RPCGasCap`?

**Comment by MariusVanDerWijden** [comment]
Hmm it works for me on current master
```
> ./build/bin/geth --rpc.gascap 123 --rpc.txfeecap 1432 dumpconfig
INFO [03-24|13:42:46.742] Maximum peer count                       ETH=50 LES=0 total=50
INFO [03-24|13:42:46.742] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [03-24|13:42:46.742] Set global gas cap                       cap=123
[Eth]
NetworkId = 1
SyncMode = "fast"
...
RPCGasCap = 123
RPCTxFeeCap = 1.432e+03
```

**Comment by fkbenjamin** [comment]
I had a closer look and it seems that these parameters work with any non-zero value as you show in your example. However, when setting both of these to 0 and therefore disabling them, it doesn't add them to the config. Could you verify if it works with 0-values for you?

`geth --rpc.gascap=0 --rpc.txfeecap=0 dumpconfig`

```
geth --rpc.gascap=0 --rpc.txfeecap=0 dumpconfig | grep RPCGasCap
INFO [03-24|15:42:59.109] Maximum peer count                       ETH=50 LES=0 total=50
INFO [03-24|15:42:59.113] Global gas cap disabled
```

**Comment by MariusVanDerWijden** [comment]
Yeah, I can confirm that, will fix
