### ISSUE TITLE
Modifications Made To Tracer JavaScript Files Not Reflected

### ISSUE THREAD

**Issue by m-e-r-k-l-e-root** [ethereum/go-ethereum#22569]
#### System information

Geth version: v1.10.1
OS & Version: Ubuntu 18.04
Node Type: Full (not fast synced)

#### Expected behaviour
Modifications made to the javascript tracer files (located within: [path](https://github.com/ethereum/go-ethereum/tree/master/eth/tracers/internal/tracers)) should be apparent after re-compile.

#### Actual behaviour
For example, let's say I change [this line](https://github.com/ethereum/go-ethereum/blob/c5df05b9a9529cb17b4416e23cd24583335c6a9d/eth/tracers/internal/tracers/call_tracer.js#L228) within `call_tracer.js` to `type:    "test",`, then save the file, re-compile geth, start geth, then execute JSON RPC method `debug_traceTransaction` with `{"tracer": "callTracer"}` specified, the output in which is returned will not reflect changes made to `call_tracer.js` (i.e. the value corresponding `output.result.type` is not set to `"test"` within returned JSON object).

#### Steps to reproduce the behaviour
Make any change to any of the javascript tracers within: [path](https://github.com/ethereum/go-ethereum/tree/master/eth/tracers/internal/tracers), re-compile geth, start geth, execute any method within `debug namespace` in which a tracer can be defined (i.e. `debug_traceTransaction`), call the aforementioned method present within `debug namespace` specifying the tracer you've modified and you'll notice that the return value will not reflect any of the changes made to javascript tracer.

**Comment by karalabe** [comment]
The Go build system doesn't know you made changes. .js is not part of Go build. You need to bundle the .js into the Go files (run ` go generate ./eth/tracers/internal/tracers` from the repo root).

**Comment by karalabe** [comment]
Btw, you can also inject js directly into the tracer API call from the outside, so you don't need to recompile Geth for every modification.

**Comment by m-e-r-k-l-e-root** [comment]
> The Go build system doesn't know you made changes. .js is not part of Go build. You need to bundle the .js into the Go files (run ` go generate ./eth/tracers/internal/tracers` from the repo root).

Thanks!
