### ISSUE TITLE
params: YoloV3GenesisHash is wrong

### ISSUE THREAD

**Issue by meowsbits** [ethereum/go-ethereum#22560]
#### System information

Commit hash : e862cbff

#### Expected behaviour

`params.YoloV3GenesisHash` matches hash of `core.DefaultYoloV3GenesisBlock`.

#### Actual behaviour

```
    genesis_test.go:195: case: 4, want: 0x374f07cc7fa7c251fc5f36849f574b43db43600526410349efdca2bcea14101a, got: 0xf1f2876e8500c77afcc03228757b39477eceffccf645b734967fe3c7e16967b7
```

#### Steps to reproduce the behaviour

https://github.com/ethereum/go-ethereum/pull/22559

**Comment by karalabe** [comment]
Myeah, yolov3 is borked anyway because the berlin spec was changed and there was no reason to redeploy afaik. I'd guess the only reason we keep a notion of Yolo still in the code base is not to have to add it back for the London fork, but I don't think there's a reason to poke at it.

**Comment by jcc-alfred** [comment]
> Myeah, yolov3 is borked anyway because the berlin spec was changed and there was no reason to redeploy afaik. I'd guess the only reason we keep a notion of Yolo still in the code base is not to have to add it back for the London fork, but I don't think there's a reason to poke at it.
fsaf @karalabe
