### ISSUE TITLE
how to get signed raw txn from abigen go code 

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#22570]
hi, after use `abigen` to generate go code for a contract, I can invoke any function in a contract, no need to construct raw txn and sign it, which is good.

But what if I need the signed raw txn text?

Can I make use of the generated go code to get a signed raw txn (for avoiding repeat myself)?

Can you please suggest the best way to do it?

**Comment by huahuayu** [comment]
@ligi can you please take a look?

**Comment by ligi** [comment]
Can you elaborate a bit about your use-case? Using abigen for this sounds a bit like shooting sparrows with cannons ..-)

**Comment by huahuayu** [comment]
> Can you elaborate a bit about your use-case? Using abigen for this sounds a bit like shooting sparrows with cannons ..-)

first, I like abigen generated go code, so I can interact with contract easily.

second, I also want to get signed raw txn in the same time, so I can 1.) send raw txn to a service provider for faster broadcast 2) send a private txn to prevent front run https://docs.bloxroute.com/apis/frontrunning-protection , they only accept raw txn format.

**Comment by MariusVanDerWijden** [comment]
@huahuayu The generated code always returns the constructed transaction.
You can just set up a SimulatedBackend to deploy your transactions to, take these transactions and send them to the real backend. I don't think we should implement another mode to get raw transactions in abigen
e.g.
```
backend,_ := ethclient.Dial("infura")
fakeBackend,_ := getSimBackend()
_, tx, _, err := DeployIO(txopts, fakeBackend) // deploy on fake backend
backend.SendTransaction(context.Background(), tx)
```

**Comment by karalabe** [comment]
@huahuayu Abigen uses a signer provided by you to sign the transaction https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/base.go#L50. That one gets the raw transaction and signs it. The transactors out of the box are mostly convenience methods, but you can just use your own that does whatever you want with the raw tx.

**Comment by karalabe** [comment]
E.g. you can make one of these https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/auth.go#L119 and save the raw tx for later. You can even get the raw tx out and then return an error, so the tx will never be broadcast and you can do whatever you want with it (note, you might need to do your own nonce management at that point).

**Comment by huahuayu** [comment]
@karalabe thx for your reply, I have read the code you shared, and I noticed that there is a `NoSend` field added https://github.com/ethereum/go-ethereum/blob/54c0d573d75ab9baa239db3f071d6cb4d1ec6aad/accounts/abi/bind/base.go#L58 so I think I can use it to get a signedTx with minimum effort?

**Comment by MariusVanDerWijden** [comment]
Oh yes, I forgot about that. If you specify `NoSend` in your `TransactOpts`, the transaction will not be send, but estimated sign the transaction.
