### ISSUE TITLE
Update the unclean shutdown marker every 5 minutes

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#22580]
I had a unclean shutdown less than a day ago and got this warning afterwards:

`WARN [03-26|10:10:29.944] Unclean shutdown detected                booted=2021-03-17T13:16:42+0000 age=1w1d20h`

As it would be better to have the "age=" part closer to the shutdown @holiman suggested to update the marker like every 5 minutes

**Comment by David-C-Lee** [comment]
To clarify, you would like the "age=" to be precise, down to the minute?
PrettyAge() prints the age with precision of three units: https://github.com/ethereum/go-ethereum/blob/0c70b83e0012ce0f9c7b76e61eef7dde5a360838/les/client.go#L195

Therefore, as far as I understand, an unclean shutdown that happened < one week ago will display the days, hours, and minutes. An unclean shutdown that happened > one month ago will only display months, weeks, and days.

To solve your issue, we need to use something other than PrettyAge().

If I am misunderstanding anything, please correct me, as I am brand new to the codebase.

**Comment by MariusVanDerWijden** [comment]
No @David-C-Lee the problem is, that we set the unclean-shutdown marker on startup. If the node crashes two weeks after startup, the age that is printed is the old startup age. It would be better to write the unclean-shutdown time every five minutes, thus we could see better _when_ a node crashed

**Comment by alisscco** [comment]
Honestly which  ever work left for I would prefer to allocate them all to a
stable coin to avoid interaction on etherscan which I have yet to have the
experience to stop any interaction with my smart contract .
I am I wanted to wait till I have had. Discussion with a  firm, instead of
cause you guys so much stress .
I would like to unstake them all and send to binance, including my staked
in binance .
Sorry for the long email.
Perhaps you could direct me to the best option for a firm to handle my
transactions.
Thank you guys .
I owe you guys.

**Comment by himsngh** [comment]
Hey if this is something a novice can do  I would like to take work on this.

**Comment by prb22** [comment]
The reason it posts the startup time is because the crash doesn't last the entire time it takes to reboot. It only recognizes the last clean shutdown.

**Comment by Meegada-Mahesh** [comment]
Hi, can i work on it as per @MariusVanDerWijden  comment, i will take that as requirement for this feature

**Comment by MariusVanDerWijden** [comment]
Sure @Meegada-Mahesh

**Comment by BitBaseBit** [comment]
Hey, @MariusVanDerWijden  I've submitted a PR at #22974 that fixes this.

**Comment by jayboy-mabushi** [comment]
@Meegada-Mahesh  I am getting unclean shutdown error and it is not pulling any new data. How can I resolve this?
![image](https://user-images.githubusercontent.com/60149478/127900912-07262c06-5f77-4234-9a1c-24046712c132.png)
