### ISSUE TITLE
how to get more accurate block timestamp (in millisecond)

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#22595]
Hi, does anyone knows how to get block timestamp in milliseconds, I know that [eth_getblockbyhash](https://eth.wiki/json-rpc/API#eth_getblockbyhash) can get block timestamp but it's in UNIX timestamp second format, I want it's in millisecond because I need more accurate time.

Btw, since the block timestamp is set by the miner, does all the miner have synced time? is it possible that one miner's time is 5 seconds faster than another, so actually I can't trust the block timestamp？

**Comment by MariusVanDerWijden** [comment]
The ethereum block header only stores the timestamp in UNIX seconds, so it is not possible to get the timestamp in milliseconds. 
https://github.com/ethereum/go-ethereum/blob/76700ac892f6fe3d7865fbe2f724626c72a04227/miner/worker.go#L515

Yes, the miners can set the timestamp arbitrarily (within some window) so you can't trust the timestamp to be accurate.

**Comment by huahuayu** [comment]
okey, got it.
