### ISSUE TITLE
Please read!!!!!

### ISSUE THREAD

**Issue by Serqati** [ethereum/go-ethereum#22593]
Hello
Can I create my own ethereum with name blah and people can create their tokens with remix on my own ethereum (blah)??
because Ethereum is open source!!!

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by Serqati** [comment]
Thanks ligi
can you anser my q on stackexchange

**Comment by ligi** [comment]
the answer is yes you can - but no you should not

**Comment by Serqati** [comment]
https://ethereum.stackexchange.com/questions/96348/can-i-self-host-my-own-ethereum

**Comment by Serqati** [comment]
I can but I should not ??

If I can how?
