### ISSUE TITLE
how to get txn first seen time

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#22605]
hi guys, do you know how to get txn's [first seen time](https://github.com/ethereum/go-ethereum/blob/4a37ae510eb02bb7daf1fa5982f326e92a401c60/core/types/transaction.go#L50), I have read the code and tests, I can't find a way to get it.

as per my understanding, it is the time when the client sent it.

```go
type Transaction struct {
	data txdata   
	time time.Time // Time first seen locally (spam avoidance)

	// caches
	hash atomic.Value
	size atomic.Value
	from atomic.Value
}
```

so can I think that this: the txn's pending time = confirm time - first seen time?

**Comment by huahuayu** [comment]
@miguelmota can you please take a look

**Comment by karalabe** [comment]
There's no API for that. It's only used internally in the txpool.
