### ISSUE TITLE
Return the gas price from the call of  `client.TransactionReceipt` in `types.Receipt`.

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#22601]
# Rationale

Why should this feature exist?
It makes it possible to calculate a TX cost - gasUsed*gasPrice

What are the use-cases?
For contracts that gives rewards based on time passed, need to know the TX cost to know if the TX was profitable or not.

# Implementation

Do you have ideas regarding the implementation of this feature?
No
Are you willing to implement this feature?
Can look into it, if someone gives some directions.

**Comment by karalabe** [comment]
The gas price is already included in the transaction. Can't you retrieve it from there?

**Comment by krasi-georgiev** [comment]
sorry, I forgot to close this, yes this is totally right.
