### ISSUE TITLE
TransactionReceipt sometimes returns 0 (types.ReceiptStatusFailed) for tx that haven't failed.

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#22606]
Looking at the logs for tx `0x7fa512be3817e657de651d54f7ee789dcaf832a1b5a191e2e3995c28b470d872` it didn't fail but `TransactionReceipt` returned 0.
There was no reorg event for this tx, but the code filters out these anyway.

#### Expected behaviour
to always shows 1 for tx that haven't failed

#### Steps to reproduce the behaviour
Just run the code from this repo
https://github.com/krasi-georgiev/telliot/tree/profit-tracker
```
go run cmd/telliot/*.go mine --config=.local/config.json
```
config.json
```
{
    "envFile": ".local/.env",
    "Logger": {
        "profitChecker": "debug"
    }
}
```

.env
```
NODE_WEBSOCKET_URL=....
```
```
vLog tranfer &{0x0000000000000000000000000000000000000000 0x486874Fbe3FDBa8DEbF65356bcfEe663efb108be 100000000000000000 {0x88dF592F8eb5D7Bd38bFeF7dEb0fBc02cf3778a0 [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x0000000000000000000000000000000000000000000000000000000000000000 0x000000000000000000000000486874fbe3fdba8debf65356bcfee663efb108be] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 99 69 120 93 138 0 0] 8330901 0x7fa512be3817e657de651d54f7ee789dcaf832a1b5a191e2e3995c28b470d872 5 0x5ca615c8c47fcef4dde4664897d0f9f21ac2902a23ae743a03f97a5dbde4c22a 13 false}}
vLog tranfer &{0x0000000000000000000000000000000000000000 0x0e93f23278161bCa6F22D6268ca44691042ed437 100000000000000000 {0x88dF592F8eb5D7Bd38bFeF7dEb0fBc02cf3778a0 [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x0000000000000000000000000000000000000000000000000000000000000000 0x0000000000000000000000000e93f23278161bca6f22d6268ca44691042ed437] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 99 69 120 93 138 0 0] 8330901 0x7fa512be3817e657de651d54f7ee789dcaf832a1b5a191e2e3995c28b470d872 5 0x5ca615c8c47fcef4dde4664897d0f9f21ac2902a23ae743a03f97a5dbde4c22a 14 false}}
vLog tranfer &{0x0000000000000000000000000000000000000000 0x4A7DEA04eFE2b9BFF8332e50d8218306c5aec615 100000000000000000 {0x88dF592F8eb5D7Bd38bFeF7dEb0fBc02cf3778a0 [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x0000000000000000000000000000000000000000000000000000000000000000 0x0000000000000000000000004a7dea04efe2b9bff8332e50d8218306c5aec615] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 99 69 120 93 138 0 0] 8330901 0x7fa512be3817e657de651d54f7ee789dcaf832a1b5a191e2e3995c28b470d872 5 0x5ca615c8c47fcef4dde4664897d0f9f21ac2902a23ae743a03f97a5dbde4c22a 15 false}}
ts="jan 31 13:23:55.50" caller=profitChecker.go:258 level=error component=profitChecker addr=0x4A7D tx=0x7fa512be3817e657de651d54f7ee789dcaf832a1b5a191e2e3995c28b470d872 msg="profit event status not success so no profit added" status=0 raw=0x7fa512be3817e657de651d54f7ee789dcaf832a1b5a191e2e3995c28b470d872
ts="jan 31 13:23:55.51" caller=profitChecker.go:258 level=error component=profitChecker addr=0x27c2 tx=0x7fa512be3817e657de651d54f7ee789dcaf832a1b5a191e2e3995c28b470d872 msg="profit event status not success so no profit added" status=0 raw=0x7fa512be3817e657de651d54f7ee789dcaf832a1b5a191e2e3995c28b470d872
ts="jan 31 13:23:55.51" caller=profitChecker.go:272 level=debug component=profitChecker addr=0x4868 tx=0x7fa512be3817e657de651d54f7ee789dcaf832a1b5a191e2e3995c28b470d872 msg="adding profit" amount=0.021551
ts="jan 31 13:23:55.52" caller=profitChecker.go:258 level=error component=profitChecker addr=0x0e93 tx=0x7fa512be3817e657de651d54f7ee789dcaf832a1b5a191e2e3995c28b470d872 msg="profit event status not success so no profit added" status=0 raw=0x7fa512be3817e657de651d54f7ee789dcaf832a1b5a191e2e3995c28b470d872
```

change this line to remove the filter and monitor all addresses
```
sub, err := tellorFilterer.WatchTransferred(
		&bind.WatchOpts{},
		output,
		[]common.Address{
			common.HexToAddress("0x0000000000000000000000000000000000000000"),
		},
		nil, // <----- here
	)
```

**Comment by rjl493456442** [comment]
I can find this transaction on rinkeby testnet https://rinkeby.etherscan.io/tx/0x7fa512be3817e657de651d54f7ee789dcaf832a1b5a191e2e3995c28b470d872

Etherscan says it's successful. Are you sure the issue really exists?

**Comment by holiman** [comment]
In order for us to repro, could you please supply a minimal repro based on e.g. the geth console, setting up a filter and showing that geth produces "false failures" on transcations? Running large third-party frameworks is not something we're comfortable doing.

**Comment by krasi-georgiev** [comment]
Ok I will try.

**Comment by krasi-georgiev** [comment]
I worked a bit more on this and I think it was caused by network re-org event and the Removed events. I refactored the logic and now it looks ok, if it happens again will reopen.

**Comment by leyafo** [comment]
![image](https://user-images.githubusercontent.com/1463701/121686916-57467b80-caf4-11eb-8214-d7d9ecd71061.png)
After struggling one afternoon, I found this bug is because of this code.
I call the client by myself, the nil result never reappear agagin.

`var r types.Receipt
	err = n.client.C.CallContext(ctx, &r, "eth_getTransactionReceipt", newTransaction.Hash())
	if err != nil {
		logger.Fatal(err)
		//if r == nil {
		//	return nil, ethereum.NotFound
		//}

	}
`

**Comment by holiman** [comment]
> handle the nil result, but didn't handle the err.

That's not what that code does. If the result is `nil`, and there is _no_ error, then we return an error.
Otherwise, just return the result and a potential error

**Comment by leyafo** [comment]
> > handle the nil result, but didn't handle the err.
> 
> That's not what that code does. If the result is `nil`, and there is _no_ error, then we return an error.
> Otherwise, just return the result and a potential error

The nil result is a bug, this error should be handle in the internal. Not this module. 
The types.Receipt should not be a pointer type.
```
var r types.Receipt
err = n.client.C.CallContext(ctx, &r, "eth_getTransactionReceipt", newTransaction.Hash())
```
You just need to replace this this two code, the bug will be resloved.
