### ISSUE TITLE
ethereum/client-go docker images only support amd64 arch

### ISSUE THREAD

**Issue by jcrsilva** [ethereum/go-ethereum#22609]
# Rationale

Official docker images are already provided for geth [here](https://hub.docker.com/r/ethereum/client-go/), but only support amd64 arch. Considering there is the use case of running geth inside a docker container and that different architectures are becoming increasingly popular (arm specifically) providing images for other architectures makes sense.

# Implementation

This could be implemented in one of two ways:

1. Like in the [Dockerfile](https://github.com/ethereum/go-ethereum/blob/master/Dockerfile) by downloading and compiling geth inside a builder container;
2. Simply downloading and installing the precompiled binaries for each release.

Docker Inc has a [guide](https://www.docker.com/blog/multi-arch-images/) on building multi-arch images.

I am willing to implement this feature, but need guidance on the current build process.

**Comment by karalabe** [comment]
We are using docker hub automated builds, which does not support building ARM at the moment. We do not want to maintain a new build infra for making specialized images. The Dockerfile supplied by Geth will build fine on arm (and I'm guessing other systems too), so if you want to run non-amd64, you'll need to build the image yourself for now.

I don't think Docker Hub will introduce non-amd64 builds any time soon, so I don't think we'll add it soon either. Maybe if there's some very very good reason in the future to maintain a custom builder we might consider it, but currently we see no advantage.

**Comment by jcrsilva** [comment]
@karalabe understood, that makes sense. Thank you for your time.

**Comment by dahu33** [comment]
@karalabe I'm sorry to comment on this closed issue but I think there already are some very compelling reasons to provide arm64 docker images. This architecture is becoming increasingly popular, both at the consumer level (Apple Silicon) and in the cloud computing space (AWS Graviton2...). If Docker Hub is the issue, what about using Travis or Github Action to build the images instead? Happy to help implementing if needed but I think this issue should stay open as the demand for arm64 images is just going to grow exponentially from now.

**Comment by karalabe** [comment]
We don't really want to maintain additional build infrastructure at this time. Docker hub automated builds work very well for us now. If we were to push arm builds ourselves, we might as well replace the amd64 builds too. Travis isn't the best option lately (we're paying for it and even that way have a lot of issues due to credits running out and builds silently stopping). GitHub Actions are too much tied to a specific platform for our taste.
