### ISSUE TITLE
Issue when trying to resolve the sender of a transaction

### ISSUE THREAD

**Issue by xyderos** [ethereum/go-ethereum#22600]
I am trying to resolve the sender of a transaction and, unfortunately my code is not working. My code snippet is:

```go      
        signer:= types.NewEIP155Signer(transaction.ChainId())

        sender, err := signer.Sender(transaction)

        if err == nil {

                return nil, &err

        }

        res := sender.String()

        return &res, nil
```

This snippet is contained in a function that accepts a `*types.Transaction` struct, Go 1.15 builds the program with no warnings or issues but when it comes to testing its panicing on the 1st line I attached `signer...` . I am running a node in fast mode with snapshot closed so I wont interfere with the block operations.

Is it safer to try to verify the sender with rsv parameters(or in a sense the solution that would definitely work) or is there another problem that I might be missing?

Thanks for your time!

**Comment by xyderos** [comment]
The 2nd line was supposed to be inside the code block, sorry about that.

**Comment by karalabe** [comment]
You'll need to attach the crash log too. My guess is that `transaction` is `nil` if it crashes in the first line.

**Comment by xyderos** [comment]
Here is the crash log from the tests

   
     
      --- FAIL: TestGetSender (0.00s)
      transactionUtils_test.go:45: FAILED, Could not get the signer of the transaction
      FAIL
      exit status 1
      FAIL	transactionUtils	0.019s


Here is the code snippet of the test function:
    
          
    func TestGetSender(t *testing.T) {

        conn, _ := connectionUtils.EstablishConnection()

        txHash := common.HexToHash("0xa85ecc39970bc571c3d4f3b68f9b44de9bb0542748f3ecf2d9179c5229bea532")

        tx, _, _ := conn.TransactionByHash(context.Background(), txHash)

        res, err := GetSender(tx)

        if err != nil {

                t.Fatalf("FAILED, Could not get the signer of the transaction")

        }

        if *res == "0x28ed88c5f72c4e6dfc704f4cc71a4b7756bc4dbc" {

                t.Logf("PASSED: Could verify the sender of a trnasaction")

        } else {

                t.Errorf("FAILED: Could not verify the sender of a transaction")

        }

    }

The transaction is taken from `etherscan.io` and the numbers are taken accordingly. The `EstablishConnection` function is working (passing its tests).

**Comment by karalabe** [comment]
Might want to check the returned `err` content, should tell you what's wrong.

**Comment by xyderos** [comment]
Apparently this is working just fine, there was an issue with the if statement (I was checking if the error was nil but in reality I wanted to check if the error is not nil), thank you for your time and consideration!
