### ISSUE TITLE
Passing --datadir with a geth db command fails

### ISSUE THREAD

**Issue by TennisBowling** [ethereum/go-ethereum#22610]
#### System information

Geth version: `1.10.1`
OS & Version: ubuntu
Commit hash : c2d2f4ed8f232bb11663a1b01a2e578aa22f24bd

#### Expected behaviour
geth will use the specified datadir instead of the default one when running a `geth db` command.

#### Actual behaviour

geth fails and exits
#### Steps to reproduce the behaviour

run any `geth db` with `--datadir`

#### Backtrace

````
[backtrace]
````

**Comment by rjl493456442** [comment]
Perhaps you want to run the sub-commands under the `db` namespace? E.g. `geth db inspect`?

**Comment by TennisBowling** [comment]
thanks everyone that fixed this! you made my day.
