### ISSUE TITLE
Dependencies not found

### ISSUE THREAD

**Issue by ohmpatel1997** [ethereum/go-ethereum#22615]
System information
Geth version: geth 1.9.4
OS & Version: OSX

Expected behaviour
Till 4 hours ago, application deployed without any a problem.
I updated dependencies (go-ethereum)

Actual behaviour
github.com/karalabe/usb/hid_enabled.go:22:10:

fatal error: './hidapi/hidapi/hidapi.h' file not found
#include "./hidapi/hidapi/hidapi.h"

Steps to reproduce the behaviour
Deploy an app with Go-ethereum client

Backtrace
github.com/karalabe/usb/hid_enabled.go:22:10:

fatal error: './hidapi/hidapi/hidapi.h' file not found
#include "./hidapi/hidapi/hidapi.h"

**Comment by karalabe** [comment]
Are you using Go modules? You need to be using Go modules.

**Comment by ohmpatel1997** [comment]
Yes I am using go modules.

**Comment by karalabe** [comment]
Please send us repro code / project / repo. It works for us, so something's off on your side.

**Comment by cppfuns** [comment]
Encountered the same problem

**Comment by ohmpatel1997** [comment]
> Please send us repro code / project / repo. It works for us, so something's off on your side.

I solved it by using:

https://github.com/nomad-software/vend

**Comment by karalabe** [comment]
Closing as can't meaningfully solve without a repro.
