### ISSUE TITLE
eth_protocolVersion returns wrong value even --http.api is inserted correctly on latest release

### ISSUE THREAD

**Issue by redred77** [ethereum/go-ethereum#22613]
#### System information

Geth version: v1.10.1
OS & Version: Linux

#### Expected behaviour
eth_protocolVersion call should return correct version info

#### Actual behaviour
eth_protocolVersion call returns "the method eth_protocolVersion does not exist/is not available" even I launched with `--http.api "eth.net.web3.personal"` parameter

WARN [04-03|10:05:01.132] Served eth_protocolVersion               conn=127.0.0.1:14124 reqid=63 t=0s         err="the method eth_protocolVersion does not exist/is not available"

#### Steps to reproduce the behaviour
It worked well with 1.9.25-stable so it seems like there's breaking changes on latest release.

Here's some parameters I used on lauch.
geth --http --http.addr xxxxx --port xxx --http.port xxx --http.corsdomain localhost --mine --miner.threads "0" --miner.extradata "1" --maxpeers "250" --datadir=/home/username/.geth --http.api "eth,net,web3,personal"

**Comment by karalabe** [comment]
That API endpoint was removed as it was meaningless. Geth speaks 4 different `eth` protocol versions 1 `snap`, about 2-3 `les`. Which one should the protocol version return?

Also, the protocol version is negotiated for each individual peer, so a global number is meaningless as it may be different for each peer connection.

**Comment by redred77** [comment]
Actually I don't use `eth_protocolVersion` to retrieve data but to check whether the geth is running.
(we might use `net_version` call instead)
It would be better to remove `eth_protocolVersion` from https://eth.wiki/json-rpc/API
I couldn't notice this change from the latest document
