### ISSUE TITLE
How can i build a signature 

### ISSUE THREAD

**Issue by Rsand918** [ethereum/go-ethereum#22611]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

**Comment by chaddychad47** [comment]
Thank you it’s fine 🔗🙂



On Friday, April 2, 2564, 9:41 PM, Richard ***@***.***> wrote:




This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use discord or the Ethereum stack exchange at https://ethereum.stackexchange.com.
