### ISSUE TITLE
Puppeth: use ssh-agent instead of reading from file

### ISSUE THREAD

**Issue by lightclient** [ethereum/go-ethereum#22623]
Reading ssh keys from file doesn't work for users who rely on `ssh-agent` to manage their keys (e.g. through gpg). Therefore, it would be great to use `ssh-agent` to authenticate sessions instead of a key file. It appears the go ssh library has a agent client that would allow for this.

**Comment by ligi** [comment]
We would like to see a PR with the feature if it is not too complex (max 100 lines diff)

**Comment by lightclient** [comment]
@ligi ask and ye shall receive.
