### ISSUE TITLE
Expose the From field for the Transaction type

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#22627]
# Rationale

 - Why should this feature exist?
to all filtering TXs by the From address.
 - What are the use-cases?
I want to monitor all failed transactions for a given address. the bloom filter allows filtering by log topic , but I also want to filter by from address. My current implementation uses a subscription to the head and then uses a bloom filter to filter blocks only that contain a given event. then I am interested only in the failed transactions that were created by a given address. Looked through the code, but couldn't find how to get the From address for a given TXs. 
Here is the code
https://github.com/krasi-georgiev/telliot/blob/profit-tracker/pkg/tracker/profit/profit.go#L339
# Implementation

 - Do you have ideas regarding the implementation of this feature?
Yes, just expose the from data with a function
 - Are you willing to implement this feature?
Yes

**Comment by karalabe** [comment]
The transactions do not store the sender. The sender is recovered from the signature, which depends on what for you're in. You can use `types.Sender` to recover the `From` address: https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction_signing.go#L126

**Comment by krasi-georgiev** [comment]
Thanks that is exactly what I needed, asked few times on discord, but not much activity there. Thanks again. All working as expected now!
