### ISSUE TITLE
Puppeth: can't connect to ethstats from colocated node

### ISSUE THREAD

**Issue by lightclient** [ethereum/go-ethereum#22638]
When I deploy ethstats with the nginx reverse-proxy and a sealer node, the sealer node attempts to connect to it via the the remote address and port. For some reason, it seems docker is rerouting this to 127.0.1.1 and this doesn't seem to be linked to any loopback and therefore sealer cannot connect to the ethstats server. When I manually update the sealer's ethstats url to `ethstats:3000` it is able to connect via the default networking bridge in docker.

**Comment by lightclient** [comment]
Even if I deploy without nginx, it tries to connect to via server public IP and the port specified to serve ethstats. This also doesn't work. It seems like the ethstats server only listens on port `3000` and the only way to connect to it is using `ethstats` and have the docker networking route the communication to the ethstats container.

**Comment by holiman** [comment]
`puppeth` is removed as of https://github.com/ethereum/go-ethereum/pull/26581. Closing puppeth-related tickets.
