### ISSUE TITLE
Puppeth: invalid reserved nodes

### ISSUE THREAD

**Issue by lightclient** [ethereum/go-ethereum#22637]
I don't quite understand the purpose of this parameter, but it is being hard coded to "yournode". Seems like it could just be empty?

https://github.com/ethereum/go-ethereum/blob/04dcc9378dc38d54eeb6a688d81e8b5e13446519/cmd/puppeth/module_ethstats.go#L36

**Comment by karalabe** [comment]
You'll be amazed why I've added that.

https://www.rinkeby.io/#geth

There are commands to connect your node, specifically `--ethstats='yournode:password@stats.rinkeby.io'`. Half the people didn't bother changing `yournode` there and we had tens of nodes reporting using the same login, which made filtering out malicious reports a lot harder. (beside being annoying as hell to have an entry on the dashboard that is flipping 50 times per block).

**Comment by lightclient** [comment]
I probably should've start with by checking the [git blame](https://github.com/ethereum/go-ethereum/pull/15137#issue-140519211) :) that is ... wow.
