### ISSUE TITLE
Rinkeby-Faucet: Improve Error message when post is not public

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#22631]
users often use a non-public post in the rinkeby faucet. Some of them [come to the issue tracker](https://github.com/ethereum/go-ethereum/issues/21375#issuecomment-815539379) to report it and some might just silently cry and give up on Rinkeby and go to a different station.
Would be good to have a warning that makes users aware that the post must be public when it is not to reduce issues and user happiness.

**Comment by KrishnaSindhur** [comment]
hi, if no one is working on it can I pick it

**Comment by hari0806** [comment]
@ligi - Newbie for this repo. I would like to contribute to fix this issue. Please share any documentation related to this issue and to understand the flow if possible.

**Comment by hari0806** [comment]
@ligi - I have gone through the issue tracker and source code. I think the fix need to be applied in the below line. I'll fork the project and try to test. Thank you!
https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/cmd/faucet/faucet.go#L865

**Comment by hari0806** [comment]
As like mentioned in the comment section of code, Facebook Graph API still requires userAccessToken even for accessing public posts in users wall. In the response html by page scraping, the only hint to identify the non-public post is by searching the text "Log into Facebook to see this post". Below are the options I can think,

1. Get the userAccessToken by prompting login from the users and use the token for the API access
(OR)
2. Throw error message that the post is NOT public when the text "Log into Facebook to see this post" is found in the request body html
(OR)
3. Just add the text in the existing error message to ask the user to verify whether the post is public or not. Eg: changing the text from "No Ethereum address found to fund" to "No Ethereum address found to fund. Please verify the URL and make sure that the post is public"

@ligi  - Please share your thoughts and let me know if I can proceed with any of the options listed.

**Comment by g-alfieri** [comment]
> 3. Just add the text in the existing error message to ask the user to verify whether the post is public or not. Eg: changing the text from "No Ethereum address found to fund" to "No Ethereum address found to fund. Please verify the URL and make sure that the post is public"

I got the error but the post is public
https://www.facebook.com/KevinMcKenzy/posts/10225899867307365
address 0x62992a857C8b34719642fAA549fa21a119155700

**Comment by hari0806** [comment]
> > 1. Just add the text in the existing error message to ask the user to verify whether the post is public or not. Eg: changing the text from "No Ethereum address found to fund" to "No Ethereum address found to fund. Please verify the URL and make sure that the post is public"
> 
> I got the error but the post is public
> https://www.facebook.com/KevinMcKenzy/posts/10225899867307365
> address 0x62992a857C8b34719642fAA549fa21a119155700

I'm NOT able to access. It shows login screen for me. You can try access the link in incognito/private mode to make sure that you are not logged in.

**Comment by sboulden** [comment]
Please, I need help.  I know you locked the other thread due to users not being able to read and follow instructions, but I legitimately am stuck.
My PUBLIC facebook post is available here: https://www.facebook.com/JUSTcallmePRE/posts/1911734315654057
With my valid ETH address.  
And I still get the error "No ETH address found to be funded."

**Comment by basharz1** [comment]
I found this issue on https://ovio.org/projects and would love to contribute!
