### ISSUE TITLE
high memory consume after upgrading from 1.9.25 to 1.10.1 and 1.10.2 system crashes

### ISSUE THREAD

**Issue by wagnerspirigoni-mb** [ethereum/go-ethereum#22643]
#### System information

Version: 1.10.2-stable
Git Commit: 97d11b0187b4695ccf44e3b71b54155fe405a36f
Git Commit Date: 20210408
Architecture: amd64
Go Version: go1.16
Operating System: linux
64 GB memory

#### Expected behaviour

run geth without consuming all the instance memory

#### Actual behaviour

geth runs for a few hours, consumes all instance memory, then freezes instance, needs hard reset on instance to be able to access it again

#### Steps to reproduce the behaviour

I've been running a software that subscribe for new blocks and then it calls a debug_traceTransaction for every transaction since geth 1.8 and have been upgrading every major version, yesterday I've upgraded for 1.10.1 and then 1.10.2 in both I've seen a high memory consume, way more than before, and then the instance crashes

here are the last geth logs when the client crashes the instance:
```
Apr  9 05:11:46 eth1 geth[1071]: DEBUG[04-09|05:11:46.292] Served eth_getCode                       conn=127.0.0.1:37992 reqid=608407 t=116.488312ms
Apr  9 05:11:46 eth1 geth[1071]: DEBUG[04-09|05:11:46.338] Dereferenced trie from memory database   nodes=1669     size=693.85KiB  time=4.968523ms  gcnodes=37846   gcsize=15.36MiB   gctime=
105.174712ms  livenodes=56997   livesize=18.70MiB
Apr  9 05:11:46 eth1 geth[1071]: INFO [04-09|05:11:46.362] Regenerating historical state            block=12201654 target=12201709 remaining=55 elapsed=2m51.483434765s
Apr  9 05:11:48 eth1 geth[1071]: DEBUG[04-09|05:11:48.406] Transaction pool status report           executable=4093 queued=1027 stales=933
Apr  9 05:11:52 eth1 geth[1071]: DEBUG[04-09|05:11:51.541] Recalculated downloader QoS values       rtt=6.109868885s  confidence=1.000 ttl=18.329624982s
Apr  9 05:11:53 eth1 geth[1071]: DEBUG[04-09|05:11:52.442] Removed dead node                        b=5  id=87b5fa4fa4f27565 ip=167.86.125.46   checks=1
Apr  9 05:12:01 eth1 geth[1071]: DEBUG[04-09|05:11:59.405] Recalculated downloader QoS values       rtt=6.109866935s  confidence=1.000 ttl=18.329619132s
Apr  9 05:12:04 eth1 geth[1071]: DEBUG[04-09|05:12:03.377] Fetching single header                   id=1b47f0378da89e09 conn=dyndial         hash="61d894…45e9c8"
Apr  9 05:12:06 eth1 geth[1071]: DEBUG[04-09|05:12:05.573] Replaced dead node                       b=14 id=a185bc0dbdb1ec61 ip=176.9.122.147   checks=24 r=b563a8659cd5b51c rip=104.248.207.
3
Apr  9 05:14:54 eth1 geth[1071]: DEBUG[04-09|05:12:06.747] Failed to deliver headers                err="no sync active"
```

here are the `debug.stacks()` 
https://pastebin.com/uTuXcnxn

and the memory dump both just a couple of minutes before system crashed another time
[memory_dump.zip](https://github.com/ethereum/go-ethereum/files/6286992/memory_dump.zip)

and the memory consumption graph
<img width="719" alt="memory graph" src="https://user-images.githubusercontent.com/45392733/114206646-ee932500-9931-11eb-89ed-498b5e494cfa.png">

cli parameters:
`geth --datadir /opt/geth/.ethereum --syncmode 'fast' --rpc --rpcvhosts 'localhost' --rpcapi web3,eth,personal,txpool,debug --rpcaddr 'localhost' --rpcport 8544 --verbosity 4 --ws --nousb --allow-insecure-unlock --cache 2048 --rpc.gascap 300000`

**Comment by evertonfraga** [comment]
Trying to contribute to the bug report:

1) it might be generating the snapshot. you can disable it with the flag `--snapshot=false`

2) side-effects of trace for block numbers you don't hold the entire state of.

The third line of your log shows that the node is trying to reconstruct a past state, which is the default behavior for running tracers on blocks for which tries were already pruned. I don't know the specifics, but it is certainly not a trivial task.

```
Apr  9 05:11:46 eth1 geth[1071]: INFO [04-09|05:11:46.362] Regenerating historical state            block=12201654 target=12201709 remaining=55 elapsed=2m51.483434765s
```

**Comment by wagnerspirigoni-mb** [comment]
I'll try disabling the snapshot and post updates here

yeah sometimes we do have to query some old blocks, but mostly inside the 128 historical range, we are taking a look in ways to reduce it, but as far as we noticed, haven't been a big issue in older versions

**Comment by wagnerspirigoni-mb** [comment]
disabling snapshots were not effective, I'm attaching new memory dumps, stacks and memStats maybe it can help
[dumps.zip](https://github.com/ethereum/go-ethereum/files/6289094/dumps.zip)


it took around 6 hours to go from 3% of memory usage to 99% (around 60GB)

**Comment by MariusVanDerWijden** [comment]
Hmm I can't really see the issue in the memdumps. They both show ~ 2.6GB of RAM usage.  Maybe the tx-unindexing becomes an issue here? Can you provide some examples for the types of queries that you execute?
I can't find anything in the stack trace either, it correctly shows ~5TB of alloced and deallocd memory and a heap alloc of ~2GB.

**Comment by karalabe** [comment]
Could it be linked to the tracer? Gary did some refactors there for 1.10.0. does it happen with your node if you don't trace transactions too?

**Comment by wagnerspirigoni-mb** [comment]
@MariusVanDerWijden what we do is get all txs from a block, and then trace every transaction.

@karalabe we do heavy use of the traceTransaction, so it may be possible, I've tried some different confs, flags, etc and have noticed that if after geth finishs syncing, we waited like 10 minutes, and then started our app that consumes geth API, looks like everything runs fine, but if we start our app, right when geth finishs syncing, the memory gets all consumed, at first I thought was a coincidence, but we were able to reproduce it three times

**Comment by charlie-paxos** [comment]
Also seeing a similar issue. Had OOMs initially but bumped max memory from 8GB to 25GB and that has helped mitigate, although we're still seeing usage around the cap.

**Comment by cncr04s** [comment]
I'm having a problem with crashes as well. I've started a resync, same problem. Different hardware too, so don't blame that. Problem only started with 1.10.1, I tried 1.10.1 and 1.10.2 same crashes. Didn't occur with previous versions. 
How there is a problem, I don't know but, there should be some sort of bounds checking against corrupt data and or a repair process to identify these problems. Its getting to be a problem.

**Comment by charlie-paxos** [comment]
Hi all, we're still seeing a similar problem in 1.10.1. We're playing around with running the official docker image in K8s so it could be an issue with that. Any thoughts on this one?

**Comment by MariusVanDerWijden** [comment]
This issue is getting quite stale now, we think we"ve found an issue where the txpool retained more transactions than necessary (a memleak). This was fixed quite a while ago. Will close this issue. Please open a new issue if the same high memory consumption still happens with v.1.10.11.
