### ISSUE TITLE
LES client: Too few peers with 1.10.2

### ISSUE THREAD

**Issue by Swift42** [ethereum/go-ethereum#22647]
#### System information

Geth version: 1.10.2
OS & Version: Linux

#### Expected behaviour
The LES client had always 5 to 8 peers connected with 1.10.1

#### Actual behaviour
Now the LES client only has 1 peer connected, sometimes 2 peers. Even after hours, still 1 or 2 peers.
I checked it several times: 
If I switch back to 1.10.1, there are instantly 3 to 4 peers connected and 5 to 8 peers after ~30 minutes. 
Back to 1.10.2: 1 to 2 peers only.
I had the same number of peers (1 to 2) before DNS discovery was implemented with 1.9.11. So maybe the DNS discovery is broken in 1.10.2?

#### Steps to reproduce the behaviour
Running the LES client 1.10.2

**Comment by fjl** [comment]
In 1.10.2, there were multiple changes that make the light client peer discovery less aggressive. In particular, the light client now pre-negotiates connection with the server to avoid connecting to overloaded servers.

**Comment by fjl** [comment]
I've tried it myself now with v1.10.2, and my peer count goes up to 5 after about 10 minutes.

**Comment by Swift42** [comment]
I tested it with the new release (1.10.3). Sadly, I have the same problem: Even after hours I never see more than 2 peers.
fjl: You wrote that you get >=5 peers on your system. So what's different on my system? Is there anything I can check for?

**Comment by Swift42** [comment]
Now, after 2 days uptime, my node sees 5 peers, too. So it may have to do with the mentioned "less aggressive peer discovery". Maybe it is a bit too less aggressive now, but nevertheless I will close this issue.
