### ISSUE TITLE
Incorrect gas cost passed to tracer for EIP-2929 calls with cold account accesses

### ISSUE THREAD

**Issue by adietrichs** [ethereum/go-ethereum#22649]
#### System information
Commit hash : anything past https://github.com/ethereum/go-ethereum/commit/6487c002f6b47e08cb9814f16712c6789b313a97 that introduced EIP-2929 support

#### Expected behaviour
With [EIP-2929](https://github.com/ethereum/EIPs/blob/d679d09f7aa4c8aac78830bdee2436eea7d561ad/EIPS/eip-2929.md) enabled, the dynamic cost of all call types includes an optional `COLD_ACCOUNT_ACCESS_COST`. This cost, if charged, should also be part of the total opcode gas cost passed to the tracer and exposed e.g. via `debug_traceTransaction`.

#### Actual behaviour
While properly charged, the `COLD_ACCOUNT_ACCESS_COST` is never part of the gas cost reported to the tracer.

#### Explanation
https://github.com/ethereum/go-ethereum/commit/6487c002f6b47e08cb9814f16712c6789b313a97 added the new `core/vm/operations_acl.go` file for EIP-2929 gas logic. Dynamic gas cost calculation for all call types is wrapped in [operations_acl.go#L176](https://github.com/ethereum/go-ethereum/blob/9c653ff6625df1ff0f6c6612958b2a1da0021e40/core/vm/operations_acl.go#L176):
```
func makeCallVariantGasCallEIP2929(oldCalculator gasFunc) gasFunc {
	return func(evm *EVM, contract *Contract, stack *Stack, mem *Memory, memorySize uint64) (uint64, error) {
		addr := common.Address(stack.Back(1).Bytes20())
		if !evm.StateDB.AddressInAccessList(addr) {
			evm.StateDB.AddAddressToAccessList(addr)
			if !contract.UseGas(ColdAccountAccessCostEIP2929 - WarmStorageReadCostEIP2929) {
				return 0, ErrOutOfGas
			}
		}
		return oldCalculator(evm, contract, stack, mem, memorySize)
	}
}
```
The issue is that the `ColdAccountAccessCostEIP2929` is charged directly, instead of being passed to the outside together with the rest of the dynamic gas, to be charged there and passed to the tracer. While this is necessary to properly calculate the available call gas in the inner `gasFunc`, it causes the incorrect gas reporting to the tracer at [interpreter.go#L278](https://github.com/ethereum/go-ethereum/blob/9c653ff6625df1ff0f6c6612958b2a1da0021e40/core/vm/interpreter.go#L278).

**Comment by adietrichs** [comment]
I will create a PR later today with a proposed fix that keeps the existing `makeCallVariantGasCallEIP2929` wrapper structure.

**Comment by ligi** [comment]
Thanks for the great detailed issue! We would very much like to see the PR you make later today.

**Comment by adietrichs** [comment]
> later today

Turns out that was indeed optimistic. I created #22680 now though, which is the best minimal fix I could come up with.

**Comment by holiman** [comment]
I wanted to push some changes to this PR, but you seem to have disabled maintainer-push on your fork. I might open a new PR and cherry-pick your commit, if that's ok?

**Comment by adietrichs** [comment]
Ah, wasn't aware we had disabled maintainer-push. New PR is fine with me, will close the other one then.
