### ISSUE TITLE
why download all Receipts in FastSync mode?

### ISSUE THREAD

**Issue by 60wanjinbing** [ethereum/go-ethereum#22651]
P, beforeP, afterP := splitAroundPivot(pivot.Number.Uint64(), results)
		if err := d.commitFastSyncData(beforeP, sync); err != nil {
			return err
		}
		..................
		// Fast sync done, pivot commit done, full import
		if err := d.importBlockResults(afterP); err != nil {
			return err
		}
            after pivot  block, why download Receipts??

**Comment by karalabe** [comment]
The pivot moves every 15 mins. You don't know which will be the last pivot
that's actually gets committed. It's simpler to not special case it,
especially at a few extra MB in the 150GB set.
