### ISSUE TITLE
Transaction Receipts null returned

### ISSUE THREAD

**Issue by lukerQuant** [ethereum/go-ethereum#22653]
#### System information

Geth version: `1.10.1`
OS & Version: OSX
Commit hash : release

Attempted with light node and full node fast sync

#### Expected behaviour

Can get recent and historical transaction receipts

#### Actual behaviour

We only get recent transaction receipts. E.g. transaction receipt searches for transactions occurring a couple of years ago return null. 

I would at expect transaction receipts to be returned via at least full node fast sync as they "downloads all blocks (including headers, transactions and **receipts**)" (https://ethereum.org/en/developers/docs/nodes-and-clients/) . If this is not the intended behaviour of certain nodes then the documentation of https://ethereum.org/en/developers/docs/nodes-and-clients/ should be updated.

#### Steps to reproduce the behaviour

Query for an transactionReceipt of an old transaction on a light or full node (fast synced)

**Comment by MariusVanDerWijden** [comment]
Hmm the receipts should be written during fast sync. It might be that due to transaction unindexing the old receipts are not available anymore. You can disable transaction unindexing with `--txlookuplimit=0` as discussed here: https://blog.ethereum.org/2021/03/03/geth-v1-10-0/

**Comment by lukerQuant** [comment]
Many thanks for the information. We missed that geth upgrade detail. We will clarify it but I will assume that is the problem for now. So I will close this.
