### ISSUE TITLE
Return more metadata for HTTP errors

### ISSUE THREAD

**Issue by ryanc414** [ethereum/go-ethereum#22654]
# Rationale

When using an ethclient with an HTTP endpoint, sometimes it is useful for the client code to handle specific HTTP or JSON-RPC error codes. As a specific example, after a 429 Too Many Requests error, the client should extract the specified backoff time from the response body and wait for at least that length of time before retrying.

Currently, go-ethereum returns both the status text and response body formatted into a single string passed into the error constructor here: https://github.com/ethereum/go-ethereum/blob/master/rpc/http.go#L145 . While it is possible to extract the status code and response bodies using regex or similar string processing methods, it would be much more user-friendly (and efficient) if these attributes could be accessed through casting the error to some concrete error type exported by the go-ethereum library.

# Implementation

I would be happy to offer a PR to implement these changes.

The proposed API would be a new exported error type from the rpc package:

```
type HTTPRequestError struct {
	StatusCode int
	Status     string
	Body       []byte
}

func (err HTTPRequestError) Error() string {
	if len(err.Body) == 0 {
		return err.Status
	}

	return fmt.Sprintf("%v: %v", err.StatusCode, err.Body)
}
```

Then the requesting code would need to be modified to fill in the respective fields on error.

Client code could use this error type like:

```
weiBal, err := ec.BalanceAt(ctx, wallet.address, blockNumber)
if err != nil {
	if err, ok := err.(rpc.HTTPRequestError); ok {
		if err.StatusCode == http.StatusTooManyRequests {
			backoff := extractBackoff(err.Body)
			select {
			case <-time.After(backoff):
				return errRetryable
			
			case <-ctx.Done():
				return ctx.Err()
			}
		}
	}
}
```

**Comment by fjl** [comment]
I'm OK with adding this error type, but please call it `HTTPError`.
