### ISSUE TITLE
sendTransaction-'invalid sender'

### ISSUE THREAD

**Issue by veneersamuel** [ethereum/go-ethereum#22662]
When I use sendTransaction(), the geth console returns invalid sender.

example:
$ geth --datadir data --networkid 2021 console 2>output.log
> eth.sendTransaction({from:eth.accounts[0], to:eth.accounts[1]})
_Error: invalid sender
	at web3.js:6347:37(47)
	at web3.js:5081:62(37)
	at <eval>:1:20(14)_

The following is the environment
web3 version:
_{
  api: "0.20.1",
  ethereum: undefined,
  network: "2021",
  node: "Geth/v1.10.2-stable-97d11b01/linux-amd64/go1.16",
}_
my accounts:
_["0xe78861b4fe4a4471dd5791b35053640b869be306", "0x330ca196095bc7d3827dd8effb5aa34c26578db3"]_

How to solve this problem?

**Comment by balajipachai** [comment]
I tried sendTransaction, and it succeeded. Here is my output of web3.version
```
{
  api: "0.20.1",
  ethereum: undefined,
  network: "25",
  node: "Geth/ImagineBC/v1.10.1-stable-c2d2f4ed/linux-amd64/go1.16",
  whisper: undefined,
  getEthereum: function(callback),
  getNetwork: function(callback),
  getNode: function(callback),
  getWhisper: function(callback)
}
```
With geth v10.10.1-stable, I did not get this Invalid sender error

**Comment by karalabe** [comment]
What's your chain config? My hunch is that you are signing with replay protection, but trying to submit it to a node that does not have it enabled (e.g. not synced).

**Comment by veneersamuel** [comment]
> What's your chain config? My hunch is that you are signing with replay protection, but trying to submit it to a node that does not have it enabled (e.g. not synced).

I think I have configured my genesis block.
This is my genesis.json and command.
_{
	"config":{
		"chainId":2021
	},
	"difficulty":"200",
	"gasLimit":"2100000",
	"alloc":{
		"7df9a875a174b3bc565e6424a0050ebc1b2d1d82":{"balance":"3000000000000000000"},
		"f41c74c9ae680c1aa78f42e5647a62f353b7bdde":{"balance":"5000000000000000000"}
	}
}_

_$ geth --datadir data init genesis.json_

I don't understand the reply protection.
Could you tell me how to test or give me some files about it?

**Comment by veneersamuel** [comment]
> I tried sendTransaction, and it succeeded. Here is my output of web3.version
> 
> ```
> {
>   api: "0.20.1",
>   ethereum: undefined,
>   network: "25",
>   node: "Geth/ImagineBC/v1.10.1-stable-c2d2f4ed/linux-amd64/go1.16",
>   whisper: undefined,
>   getEthereum: function(callback),
>   getNetwork: function(callback),
>   getNode: function(callback),
>   getWhisper: function(callback)
> }
> ```
> 
> With geth v10.10.1-stable, I did not get this Invalid sender error

I followed the commands in the video exactly, but mine always reports errors, and I don’t know why.

**Comment by karalabe** [comment]
You are missing the fork specs, so you are running in an ancient mode but are trying to sign new transactions. Please init your network with newer forks enabled https://github.com/ethereum/go-ethereum#defining-the-private-genesis-state
