### ISSUE TITLE
web3.eth.getTransaction returns null for existing, older than a year transactions in mainnet

### ISSUE THREAD

**Issue by mdeliadi** [ethereum/go-ethereum#22661]
I'm running a geth node in mainnet, version Kepler Verge (v1.10.2). The sync mode is "fast".

When I try to execute web3.eth.getTransaction for some old transaction (e.g. 0x74e51fb791fe430856ca0d55fdfd63d8ba08463a725241a6bc9c031f6c221874) I get null. The same happens with web3.eth.getTransactionReceipt.

What's wrong here? Shouldn't a fast node be capable of handling at least getTransaction?

If I do the same test with a more recent transaction (e.g. 0x53ea196d87a8cdd05a02abd41d80a99b7f0e1814824819cb2fd8f4b05e3a44a7) I'm able to get everything right.

The node has been created and synced less than a week ago. What's going on here?

**Comment by mdeliadi** [comment]
@lukerQuant is this the same issue you reported yesterday here https://github.com/ethereum/go-ethereum/issues/22644#issuecomment-817663213 ?

**Comment by holiman** [comment]
https://github.com/ethereum/go-ethereum/releases/tag/v1.10.0

> Geth 1.10.0 contains some changes which remove unnecessary data in the blockchain database. In particular, Geth no longer keeps transaction inclusion info for all transactions, and instead limits the storage of inclusion records to one year. For application developers, this change means that very old transactions can no longer be accessed by hash. Note: if you would like to
disable this behavior and keep inclusion information for all historical transactions, you can re-enable indexing using the --txlookuplimit=0 command-line flag. (#22293, #22419)

**Comment by lukerQuant** [comment]
> @lukerQuant is this the same issue you reported yesterday here [#22644 (comment)](https://github.com/ethereum/go-ethereum/issues/22644#issuecomment-817663213) ?

Yes it was. For me it was difficult to find this information but hopefully from now on developers will have the notes placed here to point them in the correct direction 👍

**Comment by mdeliadi** [comment]
@holiman Thank You!!! But I don't understand how this is supposed to work. My node is in sync, I put the `--txlookuplimit=0` and that's it? Did I just need to wait for the recovering of old txs? Is there a way to check this is actually happening?

@lukerQuant The fix is above, please check holiman's answer!

**Comment by holiman** [comment]
> Did I just need to wait for the recovering of old txs? Is there a way to check this is actually happening? 

Yes, you should see something along the lines of `Indexed transactions   blocks=...`
