### ISSUE TITLE
Stop sync all node instances at block number: 12244000

### ISSUE THREAD

**Issue by BuyOwnEx** [ethereum/go-ethereum#22676]
#### System information

Version: 1.9.25-stable
Git Commit: e7872729012a4871397307b12cc3f4772ffcbec6
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.6
Operating System: linux
GOPATH=
GOROOT=go

OS Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-136-generic x86_64)

#### Expected behaviour

I expect node to continue syncing

#### Actual behaviour
```
INFO [04-15|12:06:20.463] Imported new chain segment               blocks=1  txs=152  mgas=12.448  elapsed=110.673ms mgasps=112.478  number=12243997 hash="4e9064…4b8390" dirty=1022.36MiB
INFO [04-15|12:06:53.470] Deep froze chain segment                 blocks=2  elapsed=7.422ms   number=12153997 hash="39a3a6…93874e"
INFO [04-15|12:06:54.362] Imported new chain segment               blocks=1  txs=187  mgas=12.439  elapsed=140.587ms mgasps=88.481   number=12243998 hash="3b4861…9f499e" dirty=1022.23MiB
INFO [04-15|12:07:03.303] Imported new chain segment               blocks=1  txs=205  mgas=12.445  elapsed=115.572ms mgasps=107.681  number=12243999 hash="d44a4d…ffbeac" dirty=1022.24MiB
ERROR[04-15|12:07:10.798]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, YOLO v2: <nil>, Engine: ethash}

Number: 12244000
Hash: 0x1638380ab737e0e916bd1c7f23bd2bab2a532e44b90047f045f262ee21c42b21


Error: could not apply tx 122 [0x2e91ec8bde129768ad253384dc6002e66cd878de2bc393373998a8c4ac3a456e]: gas limit reached
##############################

ERROR[04-15|12:07:10.862]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, YOLO v2: <nil>, Engine: ethash}

Number: 12244000
Hash: 0x1638380ab737e0e916bd1c7f23bd2bab2a532e44b90047f045f262ee21c42b21


Error: could not apply tx 122 [0x2e91ec8bde129768ad253384dc6002e66cd878de2bc393373998a8c4ac3a456e]: gas limit reached
##############################
```

Another node instance have geth version

Geth
Version: 1.10.1-stable
Git Commit: c2d2f4ed8f232bb11663a1b01a2e578aa22f24bd
Architecture: amd64
Go Version: go1.16
Operating System: linux
GOPATH=
GOROOT=go

And have the same issue

**Comment by sjlnk** [comment]
Happened with 1.9.21-unstable (commit: fc20680b95da65f952012f3370e5d316f0ba237d) as well.

**Comment by jayuuza** [comment]
Had similar issues with this block, upgraded to v1.10.2 and it resolved everything

**Comment by BuyOwnEx** [comment]
v1.10.2 was released 7 days ago !!!
I expected on of the options:
 - Warning in change log of release v1.10.2. Something like **We recommend everyone to upgrade to this release, cause ...**
 - Continue working on previous release v1.10.1

I`ll try to update to the latest version and let you know

**Comment by BuyOwnEx** [comment]
Yes, latest release fix this issue

Note: you must rename "**DiscoveryURLs**" param (if you have this one) in config.toml to "**EthDiscoveryURLs**"

**Comment by fjl** [comment]
Sorry for the inconvenience.

The Berlin hard fork was announced here: https://blog.ethereum.org/2021/03/08/ethereum-berlin-upgrade-announcement/
Also, the Geth v1.10.1 release notes said that it is required to handle the fork: https://github.com/ethereum/go-ethereum/releases/tag/v1.10.1

**Comment by liuhuanhui** [comment]
I'm the same mistake. Have you solved it?

**Comment by BuyOwnEx** [comment]
> 
> 
> I'm the same mistake. Have you solved it?

latest release fix this issue

**Comment by liuhuanhui** [comment]
> > I'm the same mistake. Have you solved it?
> 
> latest release fix this issue

Don't use the latest version, I use the stable version

**Comment by BuyOwnEx** [comment]
> 
> 
> > > I'm the same mistake. Have you solved it?
> > 
> > 
> > latest release fix this issue
> 
> Don't use the latest version, I use the stable version

It is stable

Geth
Version: 1.10.2-stable
Git Commit: 97d11b0187b4695ccf44e3b71b54155fe405a36f
Architecture: amd64
Go Version: go1.16
Operating System: linux
GOPATH=
GOROOT=go

**Comment by bjq** [comment]
Geth
Version: 1.10.9-stable
Git Commit: eae3b1946a276ac099e0018fc792d9e8c3bfda6d
Git Commit Date: 20210929
Architecture: amd64
Go Version: go1.17
Operating System: linux
GOPATH=
GOROOT=go

ERROR[10-21|11:59:11.328] 
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Engine: ethash}

Number: 13453260
Hash: 0x714c7b45e3b30f7c10b974a8b25a9fbb67c7550153c1d893050ff9bf7658dd53


Error: could not apply tx 415 [0x856d94be3e737edabc10d29c38d3a2d014fadfe44e5ad9427394760537caf896]: gas limit reached
##############################
