### ISSUE TITLE
different version for Official implementation of Ethereum

### ISSUE THREAD

**Issue by Michellezqy** [ethereum/go-ethereum#22672]
I just want to know where there has official implementation of Ethereum which is wirted by java.
please give me the official link.
Thanks a lot 
welcome to contact my e-mail:1206814310@qq.com

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
