### ISSUE TITLE
Understanding receipt serialisation on inclusion in a block.

### ISSUE THREAD

**Issue by mfornet** [ethereum/go-ethereum#22682]
Each block contains the merkle-root of the MPT that contains all receipts. Receipts are serialised as a tuple of four values, and I want to understand how is the first value determined. 

- [Serialisation of the receipt](https://github.com/ethereum/go-ethereum/blob/master/core/types/receipt.go#L342)
- The first value correspond with [statusEncoding](https://github.com/ethereum/go-ethereum/blob/master/core/types/receipt.go#L215-L223).

I noticed that it can be either a "boolean" (`0x00` or `0x01`), or instead the merkle root of the state after applying the relevant tx. 

When is the boolean value used, and when is the merkle root used?

For more information about this, I opened a question in [Ethereum SE](https://ethereum.stackexchange.com/questions/97266/building-receipts-proofs-using-only-information-from-rpc), and this issue: https://github.com/near/rainbow-bridge/issues/557

**Comment by MariusVanDerWijden** [comment]
The merkle root was used a long time ago, now only 0 or 1 is saved in the receipt depending on whether a transaction was successful
https://github.com/ethereum/EIPs/issues/98
