### ISSUE TITLE
Fatal: Error decrypting key: json: cannot unmarshal object into Go struct field CryptoJSON.crypto.kdf of type string

### ISSUE THREAD

**Issue by somanysteves** [ethereum/go-ethereum#22687]
#### System information

Geth version: `geth version`
Geth
Version: 1.9.6-unstable
Architecture: amd64
Protocol Versions: [63]
Network Id: 1
Go Version: go1.11.13
Operating System: linux
GOPATH=

OS & Version:
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

f79cce5de98332e6d54eb298fce85c69d1082ee2

#### Expected behaviour
Should be able to see the private information

#### Actual behaviour
Fatal: Error decrypting key: json: cannot unmarshal object into Go struct field CryptoJSON.crypto.kdf of type string

#### Steps to reproduce the behaviour
Use
./ethkey inspect ~/Downloads/eth2deposit-cli-256ea21-linux-amd64/validator_keys/keystore-m_Timestamp-IThink.json 
On a v4 keystore you got from using the eth2deposit staking utility

note: New to go and eth dev - try not to fall out of your chairs laughing at how dumb this is before you reply ;)

**Comment by gballet** [comment]
`eth2deposit` is a tool from the eth2 world, which uses the new BLS12-381 key type. `ethkey` is a tool from the eth1 world, that does not support this new format. This is what the key file should look like:

```{
   "address" : "c431452290ffb8b3a1c7a5fa684b827336a2eab6",
   "crypto" : {
      "cipher" : "aes-128-ctr",
      "cipherparams" : {
         "iv" : "d94506fa1fb93e7dd1103c6b7df46d56"
      },
      "ciphertext" : "726efc4d1cd94aba75d31755f3e44de95ae87a29940ead2c2998c4cef61615a5",
      "kdf" : "scrypt",
      "kdfparams" : {
         "dklen" : 32,
         "n" : 262144,
         "p" : 1,
         "r" : 8,
         "salt" : "0078754c66f7429495029e4bfe0f74a9ed94e42dc7d1da791928467614f79d7c"
      },
      "mac" : "5823c60ca4a37da8a426e2afba770b0088ff1858a57fd932104e50d931f7c711"
   },
   "id" : "20aeb7af-d714-4db2-9c64-72fe53d58846",
   "version" : 3
}
```
The schema of the `eth2deposit` output is rather different:

```
{
   "crypto" : {
      "checksum" : {
         "function" : "sha256",
         "message" : "a312ec6a204af92a167797400a2832f06d029afc89725251ac51e9ec32916adf",
         "params" : {}
      },
      "cipher" : {
         "function" : "aes-128-ctr",
         "message" : "4d310de0330a1464cf4ce0922ba13916d6ae2ea1a3a470912bea5b9bed9149b1",
         "params" : {
            "iv" : "b28ee16620659230a2ccfd76d70ce113"
         }
      },
      "kdf" : {
         "function" : "scrypt",
         "message" : "",
         "params" : {
            "dklen" : 32,
            "n" : 262144,
            "p" : 1,
            "r" : 8,
            "salt" : "3cefd1844d4cd6ed82d005e2a62f349ba4ff0b6952ed79b44b506e24b33de32b"
         }
      }
   },
   "description" : "",
   "path" : "m/12381/3600/0/0/0",
   "pubkey" : "b7ae5e6faca0a63896706cc4fcd1766c03866f3230542ea1dd0c4ae16d7014ea39bc56528e1a17e53892ac3d24e45123",
   "uuid" : "2fdc1568-3172-41bd-a8c8-3a81d1b38cda",
   "version" : 4
}
```

We have no immediate plans to support this format. If you want an utility to dump your eth2 key files, we suggest you open an issue in the [relevant repository](https://github.com/ethereum/eth2.0-deposit-cli)

**Comment by somanysteves** [comment]
That makes perfect sense - thank you for your time and the very clear response.
