### ISSUE TITLE
ecies: shared key is too big

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#227]
Happened once when running go test in src/github.com/ethereum/go-ethereum/crypto in branch branched from https://github.com/ethereum/go-ethereum/commit/9d429180f995f61e3448f9e0ffce713434590055

Running test again did not trigger it.

Test case is https://github.com/ethereum/go-ethereum/blob/9d429180f995f61e3448f9e0ffce713434590055/crypto/encrypt_decrypt_test.go

Could be edge-case with the randomly generated ephemereal key in each ECIES encryption. Looping the test case a few thousand times may trigger it.

**Comment by obscuren** [comment]
@Gustav-Simonsson confirm and close please.

**Comment by Gustav-Simonsson** [comment]
We couldn't reproduce the bug after the patch, so closing the issue for now. But we should revisit the ECIES library and see if we can add better tests to it.
