### ISSUE TITLE
get signed tx string from type.transaction 

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#22706]
hi, I can get a `types.Transaction` variable after send tx, but how can I get the signed tx in string from `type.Transaction`? 

In some previous version, I can do this

```go
	ts = types.Transactions{tx}
	signedRawTxBytes := ts.GetRlp(0)
	fmt.Printf("Signed Tx: %x\n", signedRawTxBytes)
```

But now the `GetRlp` method is gone.

**Comment by karalabe** [comment]
If you want RLP encoded, you can use `tx.EncodeRLP` or `rlp.EncodeToBytes`. For new typed transactions though, the consensus format is not RLP. If you want to stick to proper consensus format independent if old or new transaction, use `tx.MarshalBinary`

**Comment by huahuayu** [comment]
hi, @karalabe I want the encoding can be used in eth_sendRawTx, so it's RLP right?

I also found this method `func (tx *Transaction) EncodeRLP(w io.Writer) error {}` can you show me a snippet of how to use it? mainly...What's the ` io.Writer` I should give if I want the output can be directly used in eth_sendRawTx?

**Comment by MariusVanDerWijden** [comment]
You can use a `bytes.Buffer` as an `io.Writer` 
e.g.
```
var buf bytes.Buffer
tx.EncodeRLP(buf)
fmt.Printf("%v\n", buf.String())
```
