### ISSUE TITLE
Json-Rpc request Id only supports numbers in the latest version as opposed to string, numbers and null

### ISSUE THREAD

**Issue by juanfranblanco** [ethereum/go-ethereum#2270]
Hi, 

On the latest version Json-Rpc request Id only supports numbers in the latest version as opposed to string, numbers and null.

Please see the current issue here: https://github.com/Nethereum/Nethereum/issues/3
And spec here  http://www.jsonrpc.org/specification#request_object

Not that  needed here is the type:
https://github.com/ethereum/go-ethereum/blob/develop/rpc/types.go#L86-L91

and what I believe the old one:
https://github.com/ethereum/go-ethereum/blob/master/rpc/shared/types.go#L42-L47

**Comment by karalabe** [comment]
@bas-vk Ping :)

**Comment by slothbag** [comment]
Passing an "id" as a string results in

`{"jsonrpc":"2.0","error":{"code":-32700,"message":"json: cannot unmarshal string into Go value of type int64"}}`

**Comment by bas-vk** [comment]
The RPC implementation is changed in develop to support subscriptions (push). For some reason I thought that the old version only supported integers. I will create a PR that will restore the old behavior.

**Comment by juanfranblanco** [comment]
Thanks!

**Comment by karalabe** [comment]
@juanfranblanco We've pushed out the PR containing the fixes to this issue. Perhaps you could try out if it indeed fixes it for you.

**Comment by juanfranblanco** [comment]
Yes, it is working now :)
