### ISSUE TITLE
Can't Start Server error with Geth

### ISSUE THREAD

**Issue by Numba1guy** [ethereum/go-ethereum#2271]
I've disables all firewalls, and free AVG which my computer is currently using, but i just can't seem to get geth to start --rpc server, i simply use geth with the --rpc function and returns what looks like would be an otherwise normal start up, but it doesn't go any further than this. 

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd/

C:\>geth --rpc
I0228 13:38:25.057967   12180 database.go:71] Alloted 16MB cache to C:\Users\John\AppData\Roaming\Ethereum\chaindata
I0228 13:38:25.068973   12180 database.go:71] Alloted 16MB cache to C:\Users\John\AppData\Roaming\Ethereum\dapp
I0228 13:38:25.078981   12180 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0228 13:38:25.078981   12180 backend.go:362] Blockchain DB Version: 3
I0228 13:38:25.080981   12180 blockchain.go:214] Last header: #0 [d4e56740…] TD=17179869184
I0228 13:38:25.080981   12180 blockchain.go:215] Last block: #0 [d4e56740…] TD=17179869184
I0228 13:38:25.081982   12180 blockchain.go:216] Fast block: #0 [d4e56740…] TD=17179869184
I0228 13:38:25.087988   12180 cmd.go:114] Starting Geth/v1.3.3/windows/go1.5.1
I0228 13:38:25.088988   12180 server.go:311] Starting Server

How could i go about fixing this? do i need to wait for the next geth release?

**Comment by linagee** [comment]
How long do you want after "Starting Server" to determine it won't go any further? Please try it again and wait at least 15 minutes there, then post the results.

**Comment by Numba1guy** [comment]
Just left for a couple hours, left it running, server still hasn't started, output is same as above.
I'm running windows 10 on a Sager laptop.

**Comment by karalabe** [comment]
Please start it with `--verbosity=6` and paste any output. Seems a strange issue we haven't seen until now. Also just a random guess, could you try with `--nat=none`? It most probably won't be able to connect, but I'm just trying to find the component that seems to hang.

PS: Windows sometimes asks whether you allow network access to some program. Are you sure you didn't forbid it, or perhaps didn't answer it? I think Windows blocks the network calls until the user replies to the popup dialog.

**Comment by obscuren** [comment]
Please also make sure you're time is synced with some NTP server.

**Comment by Numba1guy** [comment]
--verbosity=6 resulted in output the same as above, the --nat=none results in what appears to be connecting to the server, but when i try to use ethminer to mine it says i'm not connected to rpc. Yes i'm synced with an NTP server.

The output of --nat=none is as follows:

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd/

C:\>geth --nat=none
I0229 18:57:58.273497   17324 database.go:71] Alloted 16MB cache to C:\Users\John\AppData\Roaming\Ethereum\chaindata
I0229 18:57:58.554023   17324 database.go:71] Alloted 16MB cache to C:\Users\John\AppData\Roaming\Ethereum\dapp
I0229 18:57:58.561029   17324 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0229 18:57:58.562028   17324 backend.go:362] Blockchain DB Version: 3
I0229 18:57:58.564033   17324 blockchain.go:214] Last header: #105311 [f4960509 …] TD=190991191029390461
I0229 18:57:58.565034   17324 blockchain.go:215] Last block: #105311 [f4960509…] TD=190991191029390461
I0229 18:57:58.566035   17324 blockchain.go:216] Fast block: #105311 [f4960509…] TD=190991191029390461
I0229 18:57:58.573040   17324 cmd.go:114] Starting Geth/v1.3.3/windows/go1.5.1
I0229 18:57:58.574040   17324 server.go:311] Starting Server
I0229 18:57:58.620083   17324 udp.go:204] Listening, enode://eceed9af953452710860ab0b330b5fd73cf81d4d58042b396e58e0d2e665fc4cc7adc1ecff7e4cb0576e12e8a9b7a85b8401a90c2ef5750627115b350bcb0262@[::]:30303
I0229 18:57:58.622074   17324 backend.go:526] Server started
I0229 18:57:58.622074   17324 server.go:552] Listening on [::]:30303
I0229 18:57:58.623075   17324 ipc.go:112] IPC service started (\\.\pipe\geth.ipc)
I0229 18:58:12.695347   17324 downloader.go:288] Block synchronisation started
I0229 18:58:16.321863   17324 blockchain.go:1243] imported 2 block(s) (0 queued 0 ignored) including 52 txs in 1.1830249s. #105313 [4a30586a / 9ba6e8c1]

**Comment by karalabe** [comment]
Well, the `--nat=none` only disabled UPnP, you still need the `--rpc` to open up the RPC port.

**Comment by newmzy** [comment]
I'm having exactly the same experience, except I'm running Windows 7.

**Comment by Numba1guy** [comment]
Installed Ubuntu linux dual-boot on system, now running ethminer, and Geth
with no problems, after VGA driver installation. i'm not sure why the
windows OS was struggling with the operation.

**Comment by misternils** [comment]
I had the same exact issue, and the --nat=none --rpc allowed me to start downloading the blockchain at least

**Comment by fjl** [comment]
See #2291

**Comment by karalabe** [comment]
Fixed via #2337 :)

**Comment by choprasaurav7** [comment]
can start geth by --rpc nat=none syncronization failure. working in 1.6 stable version.

**Comment by newmzy** [comment]
Now I just use Parity. No problems ever
