### ISSUE TITLE
The node retrieves the historical transaction data and returns null

### ISSUE THREAD

**Issue by limengyang-boy** [ethereum/go-ethereum#22719]
After the node is upgraded to v1.10, you can get the balance of the account and the number of transactions, and ETH_SYNCING can return the latest block, it's OK to use RPC to look up the latest block data, it's OK to look up the historical block data, but looking up the details of the transaction returns null, why.
Thank you for your answer!

**Comment by holiman** [comment]
See https://blog.ethereum.org/2021/03/03/geth-v1-10-0/#transaction-unindexing

> If you wish to disable transaction unindexing altogether, you can run Geth with --txlookuplimit=0, which reverts to the old behavior of retaining the lookup map for every transaction since genesis.

Also mentioned in the release notes:https://github.com/ethereum/go-ethereum/releases/tag/v1.10.0

> Geth 1.10.0 contains some changes which remove unnecessary data in the blockchain database. In particular, Geth no longer keeps transaction inclusion info for all transactions, and instead limits the storage of inclusion records to one year. For application developers, this change means that very old transactions can no longer be accessed by hash. Note: if you would like to disable this behavior and keep inclusion information for all historical transactions, you can re-enable indexing using the --txlookuplimit=0 command-line flag. (#22293, #22419)
