### ISSUE TITLE
Gas Price estimation is unstable

### ISSUE THREAD

**Issue by junderw** [ethereum/go-ethereum#22715]
#### System information

Geth version: `v1.10.0` (but this issue has been persisting for a while across many versions)
OS & Version: Linux

#### Expected behaviour

Gas Price estimation should be at least semi-consistent. Sudden drops of 97% should not be happening.

#### Actual behaviour

We have multiple mainnet geth nodes (for our prod, staging environments etc.) and they all consistently dip in their estimations from the "market price" to low-single-digit gwei. See the following graph for a sample.

This usually only happens during times of increased network congestion. But sometimes we get the occasional dip-to-5-gwei once in a while

![スクリーンショット_2021-04-22_07-32-33](https://user-images.githubusercontent.com/11246316/115629679-cc3fd500-a33d-11eb-93d7-65343d92ce53.png)

#### Steps to reproduce the behaviour

- Run geth 24/7
- Poll gas price once every minute and plot a graph
- See huge valleys of dipping down to single-digit gwei mostly consistent across multiple instances

#### Workaround

- Detecting abnormal valleys and triggering a geth restart usually fixes the issue for a couple of hours.

**Comment by junderw** [comment]
Our infrastructure engineer said that this might be occurring after blocks where abnormally low gas price txes have made it in the block (due to connections with miners etc.)

Which could make sense if we assume the occasional min-timing between instances was due to sync lag on one of the instances.

Also makes sense since the CPU, IOWAIT, etc. metrics are pretty all over the place between instances where as these valleys are mostly in lock step between all the instances.

**Comment by bulgakovk** [comment]
Also faced the same issue and posted a possible root reason here: https://github.com/ethereum/go-ethereum/issues/22705#issuecomment-823222671

**Comment by holiman** [comment]
This should be closed by #22722 , feel free to reopen if the problem persists
