### ISSUE TITLE
Using geth with the flags --dev and --datadir leads to an error since v1.10.2

### ISSUE THREAD

**Issue by invocamanman** [ethereum/go-ethereum#22720]
#### System information
Geth version: `v1.10.2`
OS & Version: Linux

#### Expected behavior
Should be able to specify a `--datadir <dir>` in the `--dev` mode without any problem when `dir` is empty

#### Actual behavior
Since v1.10.2 the `--datadir <dir>` option with the `--dev` flag leads to an error if the `dir` is empty
`docker run -it ethereum/client-go:v1.10.1 --dev --datadir /geth` works OK

`docker run -it ethereum/client-go:v1.10.2 --dev --datadir /geth` leads to an error ( see in backtrace)

#### Steps to reproduce the behaviour
`docker run -it ethereum/client-go:v1.10.2 --dev --datadir /geth` 

#### Backtrace

````
INFO [04-22|09:40:19.822] Starting Geth in ephemeral dev mode... 
INFO [04-22|09:40:19.823] Maximum peer count                       ETH=50 LES=0 total=50
INFO [04-22|09:40:19.823] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [04-22|09:40:19.824] Set global gas cap                       cap=25000000
INFO [04-22|09:40:21.627] Using developer account                  address=0x3D6225fe29Fa7ec246e2A9Dd56E68f8342dA89db
INFO [04-22|09:40:21.627] Allocated cache and file handles         database=/geth/geth/chaindata cache=512.00MiB handles=524288 readonly=true
Fatal: Could not open database: stat /geth/geth/chaindata: no such file or directory
````

**Comment by MariusVanDerWijden** [comment]
Probably something in this commit https://github.com/ethereum/go-ethereum/commit/0c70b83e0012ce0f9c7b76e61eef7dde5a360838

**Comment by binary-tanya** [comment]
After creating the` chaindata` directory manually, getting an error log :

```
Fatal: Could not open database: file does not exist
```

**Comment by MariusVanDerWijden** [comment]
Yeah, could confirm that this is the commit that broke it via a git-bisect
