### ISSUE TITLE
Send ETH Returned error: chain not synced beyond EIP-155 replay-protection fork block on mainnet

### ISSUE THREAD

**Issue by luatnd** [ethereum/go-ethereum#22729]
#### System information

Geth version: `1.10.2-stable`
OS & Version: Linux
Commit hash : 97d11b0187b4695ccf44e3b71b54155fe405a36f
```
Geth
Version: 
Git Commit: 97d11b0187b4695ccf44e3b71b54155fe405a36f
Git Commit Date: 20210408
Architecture: amd64
Go Version: go1.16.3
Operating System: linux
GOPATH=
GOROOT=go
```

#### Expected behaviour
Can send ETH

#### Actual behaviour
Sent ETH or any token will return this error:
> chain not synced beyond EIP-155 replay-protection fork block

#### Steps to reproduce the behaviour
Use docker image: 
```
image: ethereum/client-go:alltools-stable
entrypoint: ["geth"]
```
to start a eth node

After sync is done (not sure - but currently the syncing process is updated regularly):

Then do transfer coin from a address to another address

#### Backtrace

````
I don't know how to get backtrace
````

My eth sync progress:

Start: 2021-04-14
Current: 2021-04-24
I used fast sync:

```
> eth.syncing
{
  currentBlock: 12302237,
  highestBlock: 12302312,
  knownStates: 165739095,
  pulledStates: 165657294,
  startingBlock: 12285779
}
```

I tried to add: `--rpc.allow-unprotected-txs` arguments to allow EIP-155 but the error does not go away.

Can anyone point me out some ideas to pass through this issue?

**Comment by holiman** [comment]
Your node is still syncing, it will not process transactions until it is synced. Before it's synced, it can't really evalaute whether a given tx is valid (has right nonce, has sufficient balance etc), so you need to wait that out.
