### ISSUE TITLE
when i make geth is wrong

### ISSUE THREAD

**Issue by codeclud** [ethereum/go-ethereum#22730]
env GO111MODULE=on go run build/ci.go install ./cmd/geth
env: ‘go’: No such file or directory
make: *** [Makefile:16: geth] Error 127

**Comment by codeclud** [comment]
build /
the env.sh is not exist . so i do't know how to run.

**Comment by holiman** [comment]
`make geth`, but it does require you to have `go` installed: https://golang.org/doc/install
