### ISSUE TITLE
London hardfork tracker

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#22736]
London specification: https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/mainnet-upgrades/london.md

| EIP | PR | Status|  
| --- | --- | ---| 
| [1559](https://eips.ethereum.org/EIPS/eip-1559) (Fee market change)| #22837 #22896| Merged  Merged  |
| [3198](https://eips.ethereum.org/EIPS/eip-3198) (BASEFEE opcode)| #22837 | Merged | 
| [3228](https://eips.ethereum.org/EIPS/eip-3554) (:bomb: delay)| https://github.com/ethereum/go-ethereum/pull/22840 and https://github.com/ethereum/go-ethereum/pull/22870 |  Merged -- needs [update](https://github.com/ethereum/EIPs/pull/3563) to `9.7M` |
| [3529](https://eips.ethereum.org/EIPS/eip-3529) (alternative refund reduction)| #22733| Merged|
| [3541](https://github.com/ethereum/EIPs/blob/8aa8b36070c28808f32d1e6465e71e9d0f2b8d2f/EIPS/eip-3541.md) (Reject new contracts starting with the 0xEF byte) | https://github.com/ethereum/go-ethereum/pull/22809 | Merged | 

Also: london + baikal definnitions: https://github.com/ethereum/go-ethereum/pull/22822 (merged)

As of now, it should be possible to run `baikal` off of #22837

**Comment by lightclient** [comment]
Here are all the PRs for the various portions of the EIP-1559 implementation:
* `quilt/eip1559` - main consensus changes (https://github.com/ethereum/go-ethereum/pull/22617)
* `quilt/eip1559-mempool` - tx pool support for EIP-1559 (https://github.com/ethereum/go-ethereum/pull/22791)
* `quilt/eip1559-miner` - miner support for EIP-1559 (https://github.com/ethereum/go-ethereum/pull/22833)
* `quilt/eip1559-misc` - RPC support for EIP-1559 (https://github.com/ethereum/go-ethereum/pull/22834)

The are built on top of each other, e.g. `eip1559 <- eip1559-mempool <- eip1559-miner <- eip1559-misc`.
