### ISSUE TITLE
Unable to fetch Hashrate using the command eth_hashrate in v1.10.2 upgrade

### ISSUE THREAD

**Issue by binary-tanya** [ethereum/go-ethereum#22735]
#### System information

Geth version: `v1.10.2` (Kepler Verge)

#### Actual behaviour

 After connecting to latest upgraded version v1.10.2 and running the below command :

> bin/ethereum-cli eth_hashrate

We are getting the below error message :

```
Will run [eth_hashrate]
error code: -32601, error message: the method eth_hashrate does not exist/is not available (eth_hashrate)
```

The rpc command `eth_hasrate` is working fine in version Gemini Sigma (v1.10.1). The issue is only faced in latest version `Kepler Verge (v1.10.2)`

#### Expected behaviour

The rpc command `eth_hashrate` should return the number of hashes per second.

```

bin/ethereum-cli eth_hashrate

Will run [eth_hashrate]
$VAR1 = '0x0';

```
No error message, displays the number of hashes per second.

**Comment by ligi** [comment]
Thanks for making us aware & sorry for the inconvenience. Unfortunately a bug slipped in with the release that removed the command. It will be back soon.

**Comment by karalabe** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/22765
