### ISSUE TITLE
How much storage does the snapshot have？

### ISSUE THREAD

**Issue by zheng-bin** [ethereum/go-ethereum#22731]
1. Hello, I synchronize the data with the following command.

`./geth -syncmode full --datadir=/mnt/ethereum`

1. My geth version information is as follows

- [root@blockchain bin]# ./geth version
- Geth
- Version: 1.10.0-stable
- Git Commit: 56dec25ae26bf749b93c3ea69538fabea60c5768
- Git Commit Date: 20210304
- Architecture: amd64
- Go Version: go1.13.8
- Operating System: linux
- GOPATH=/root/go
- GOROOT=/usr/local/go

I have the following synchronization problems. The snapshot has generated 7GB, how long do I need to wait? 
Thank you

- INFO [04-25|01:10:53.395] Generating state snapshot                root="7ee066…078093" at="28f83f…4778cc" accounts=20290267 slots=83610940 storage=6.98GiB    elapsed=35h28m17.283s eta=187h14m6.964s
- INFO [04-25|01:11:01.397] Generating state snapshot                root="7ee066…078093" at="28fb2f…bb77ad" accounts=20295922 slots=83613900 storage=6.98GiB    elapsed=35h28m25.285s eta=187h11m3.375s
- INFO [04-25|01:11:09.398] Generating state snapshot                root="7ee066…078093" at="28fd60…782ce1" accounts=20300182 slots=83617444 storage=6.98GiB    elapsed=35h28m33.286s eta=187h8m57.165s

**Comment by rjl493456442** [comment]
The legacy snapshot generation algorithm is very ineffective. Perhaps you can try the latest master branch which includes an optimization for the generation.  See:

- https://github.com/ethereum/go-ethereum/pull/22504
- https://github.com/ethereum/go-ethereum/pull/22667

But it needs to resync the node with `syncmode snap`.And the entire sync procedure may take a few hours. The generation itself may take another a few(3 or 4) hours. 

Btw you are syncing with full mode, any particular reason for it? Looks like you are not running the archive node.

**Comment by zheng-bin** [comment]
> The legacy snapshot generation algorithm is very ineffective. Perhaps you can try the latest master branch which includes an optimization for the generation. See:
> 
> * #22504
> * #22667
> 
> But it needs to resync the node with `syncmode snap`.And the entire sync procedure may take a few hours. The generation itself may take another a few(3 or 4) hours.
> 
> Btw you are syncing with full mode, any particular reason for it? Looks like you are not running the archive node.

Thanks，I have changed the syncing with fast mode,  resync the node with "syncmode snap" and "--snapshot=false"

**Comment by zheng-bin** [comment]
In my tests, Snapshot requires about 15GB of storage.
