### ISSUE TITLE
Geth version upgrade problem

### ISSUE THREAD

**Issue by Tw-98** [ethereum/go-ethereum#22734]
A few days ago, Ethereum forked and upgraded the geth from 1.9.18 to 1.10.2. After the update, there was no problem in the synchronization of the block in geth, but my own wallet couldn't be connected to the chain. I kept reporting web3j error: org.web3j.protocol.exceptions.ClientConnectionException : Invalid response received: 404;

Do you have such a situation? How is it handled?

**Comment by ligi** [comment]
What was the request that led to the 404 response?

**Comment by Tw-98** [comment]
> 导致404回复的请求是什么？

Link Ethereum chain will report 404, it can be said that any request is like this

**Comment by karalabe** [comment]
There's not enough information here to do anything. Geth's endpoints work well, nobody else has been reporting any issues. My guess is that either web3j itself is ding something funky, or perhaps you're specifying some URL that's not the root to connect to.

Do you set the URL to connect to yourself? What is it?
