### ISSUE TITLE
Flag to pass in /path/to/keystore?

### ISSUE THREAD

**Issue by floating** [ethereum/go-ethereum#2274]
I'm interested in a `--keystore` flag that takes a path to a `/keystore` directory not relative to the `datadir`. I'd like to put my `/keystore` on a removable encrypted drive while still being able to mount and quickly do account operations with `geth --keystore /path/to/mounted/keystore`. Thoughts? Does a better pattern already exist for this?

**Comment by fjl** [comment]
I would like to have this, too.

**Comment by obscuren** [comment]
Seems like @kobigurk was nice enough to submit a PR for this. @floating you can try out the PR until it gets reviewed / merged.

**Comment by floating** [comment]
I just tried it and it works great, thanks!
