### ISSUE TITLE
How to get the internal transactions rapidly?

### ISSUE THREAD

**Issue by Shirley-Ji** [ethereum/go-ethereum#22758]
Hi guys,

The speed is too slow when I query the api <debug_traceTransaction> on heco archive node, especially on the current block height. As Heco forked the base code from go version geth, not sure if it is because this version itself has perf issue when facing so big txs count and 3 seconds per block. 

Is there any other methods/apis to get the internal transactions rapidly? 

for example, https://cn.etherscan.com/tx/0x10389012b0e122c9b1040871d1990fc8acccec72093a507a0e54366668fab432

![image](https://user-images.githubusercontent.com/34133322/116389839-ffa7c580-a84f-11eb-95c5-add0932c8e66.png)

Thanks,
Shirley

**Comment by karalabe** [comment]
There's no faster way at the moment.

**Comment by huahuayu** [comment]
@karalabe is `debug_traceTransaction` the method etherscan to used for extract internal tx? Only available on archive node?
