### ISSUE TITLE
No warning when no peers can be found

### ISSUE THREAD

**Issue by jonnor** [ethereum/go-ethereum#2276]
If there are no peers, geth cannot sync the blockchain.
This can be due to things like port forwarding / NAT punchthrough not working, or even trivial things like the clock being wrong. Some warning that things are (likely) off, and suggestions on what to check would be very appreciated.
Spent some hours debugging such scenario yesterday...

**Comment by karalabe** [comment]
Did you run the 1.3.4 Homestead release or the develop branch?

Develop should already warn you of clock drifts via https://github.com/ethereum/go-ethereum/pull/2218:

```
I0224 10:06:51.396999 p2p/discover/ntp.go:57] ---------------------------------------------------------------------------------
I0224 10:06:51.397023 p2p/discover/ntp.go:58] System clock seems off by -44m8.56346048s, which can prevent network connectivity.
I0224 10:06:51.397023 p2p/discover/ntp.go:58] Please enable network time synchronisation in system settings.
I0224 10:06:51.397030 p2p/discover/ntp.go:59] ---------------------------------------------------------------------------------
```

**Comment by jonnor** [comment]
This was on 1.3.4, so that sounds like `develop` has solved my particular issue.
Are there warnings for UPnP problems as well (or other failure modes)?

**Comment by fjl** [comment]
We removed any warnings for UPnP because they caused people to think that UPnP is required or that there is some kind of bug when it can't find the router. Many issues were filed. 

You can still see the warning by increasing verbosity, however the default settings will only tell you that UPnP was used when it actually works.
