### ISSUE TITLE
Deploying a contract hangs on contract.new() with latest develop.

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/go-ethereum#2277]
As already discussed with @karalabe this works fine with your latest release (1.3.4) but seems to fail on develop.

To reproduce:

```
git clone https://github.com/slockit/smart-contract
cd tests
geth --dev --genesis genesis_block.json --datadir ./data  console 2>> out.log.geth
> loadScript('deploy.js')
```

With 1.3.4 the script runs fine. But with latest develop it hangs waiting inside `contract.new()`. Any debug print statements placed inside the callback or after the `new()` function don't fire.

**Comment by obscuren** [comment]
1. I looked at the code within `deploy.js` on getting and I honestly don't think you should be using `sleepBlocks` (on that notion we should probably remove it). Please use [bitchin'-tricks#mining](https://github.com/ethereum/go-ethereum/wiki/bitchin-tricks#mining). This however is not related to your particular problem but more a suggestion.
2. could you provide an example which fails?

**Comment by karalabe** [comment]
@obscuren 2. He just did that :D :P

**Comment by LefterisJP** [comment]
@obscuren Thanks for the trick, will use that. The problem I reported was that in develop the above just hangs at `contract.new()`

**Comment by obscuren** [comment]
@LefterisJP did you unlock your account?

**Comment by obscuren** [comment]
nm, i see it's in the script

**Comment by obscuren** [comment]
@karalabe yes, i crossed it out

**Comment by obscuren** [comment]
Seems fine to me https://www.dropbox.com/s/v5dmilcvy78wf20/Screenshot%202016-03-01%2011.46.56.png?dl=0

**Comment by obscuren** [comment]
It does however fail with `> Error: The contract code couldn't be stored, please check your gas amount. undefined` but that's another problem I guess.

**Comment by obscuren** [comment]
Oh, BTW I did remove the `sleepBlocks` method.

**Comment by LefterisJP** [comment]
@obscuren Yes this is another problem I will work on now. But for me with latest develop it never gets there, only with the 1.3.4 release version.

**Comment by obscuren** [comment]
@LefterisJP I'm on `develop`

**Comment by obscuren** [comment]
```
7d598af49324176cd60b6ce89bc8a72080098675 2016-02-29 16:19:32 +0100

tree b3013f5e476d89f3fb92daff3455a5359e1cc161
parent 0d89e6c2f140a26fd615e9ebac08b17dd22a9616
author Jeffrey Wilcke <geffobscura@gmail.com> 1456759172 +0100
committer Jeffrey Wilcke <geffobscura@gmail.com> 1456759172 +0100

params: updated homestead block
```

**Comment by karalabe** [comment]
I've merged in two PRs this morning which have been "imminent" for a week or so now, maaaybe something broke? Bas's contract creation was among them

**Comment by obscuren** [comment]
Trying it out now

**Comment by LefterisJP** [comment]
I am on:
```
Merge: f30b809 45d08a8
Author: Péter Szilágyi <peterke@gmail.com>
Date:   Tue Mar 1 11:01:06 2016 +0200

    Merge pull request #2221 from karalabe/expost-key-decryption
    
    crypto: expose key decryption method to parse a string direclty
```

**Comment by obscuren** [comment]
Still works on that commit.

**Comment by obscuren** [comment]
Please make sure that 1. your account is unlocked prior to running that script and 2. you have that `sleepBlocks` removed.

**Comment by karalabe** [comment]
Seems to hang on my machine too.

**Comment by LefterisJP** [comment]
@obscuren I removed `sleepBlocks()` but it makes no difference since it's well after the point in the code where it hangs. The account unlocks in the very first line of the script.

**Comment by obscuren** [comment]
Do you do this through console or attached geth?

**Comment by LefterisJP** [comment]
In the very first post of the issue I wrote the steps I follow :)

```
git clone https://github.com/slockit/smart-contract
cd tests
geth --dev --genesis genesis_block.json --datadir ./data  console 2>> out.log.geth
> loadScript('deploy.js')
```

So essentially it's a geth with console.

**Comment by karalabe** [comment]
@LefterisJP You're on Ubuntu, right? (Me too)
@obscuren You're on OSX, right?

Could this be some platform dependent issue? @fjl Could you try to repro this on your OSX machine?

**Comment by obscuren** [comment]
@LefterisJP @karalabe could you try the `--testnet` and see if that makes a difference.

**Comment by obscuren** [comment]
Trying linux in ~1h

**Comment by fjl** [comment]
Stacks during hang https://gist.github.com/fjl/48d4f2359e4a16a3e39a

**Comment by karalabe** [comment]
Fixed :)

**Comment by LefterisJP** [comment]
thanks guys, can confirm it as fixed

**Comment by karalabe** [comment]
Cool, thanks for following up on it!
