### ISSUE TITLE
Miner Setup: flag provided but not defined (geth.ipc)

### ISSUE THREAD

**Issue by esmee96** [ethereum/go-ethereum#22793]
I am currently setting up miner 1 and I used the following command in my cmd: 

`geth --identity "MinerComputer" --networkid 42 -datadir "Ethereum/~Ethereum/MinerComputer" -nodiscover -rpc -rpcport "8042" -port "30303" -unlock 0 -password Ethereum/~Ethereum/MinerComputer/password.sec -ipcpath"Ethereum/geth.ipc"
`

However I am not able to find the write ipcpath. 
And I get the following error: flag provided but not defined: -ipcpathEthereum/geth.ipc

Tried many other paths as well, but without success. Can someone help me out?

**Comment by karalabe** [comment]
I mean, it says so in the error `flag provided but not defined: -ipcpathEthereum/geth.ipc`. You didn't leave a blank space or an equal between the flag name and value.
