### ISSUE TITLE
eth_getTransactionReceipt returns null

### ISSUE THREAD

**Issue by tanmaster** [ethereum/go-ethereum#22790]
#### System information

Geth version: `>=1.10.0`
OS & Version: Linux 5.4.0-54-generic
Commit hash : (if `develop`)

When using the `eth_getTransactionReceipt` command over the RPC interface it results in null from version 1.10.0 onwards.

#### Expected behaviour

When issuing the following command over the JSON RPC interface
```{"id": 1, "method": "eth_getTransactionReceipt", "params": ["0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060"]}```

I expect the following result:

```{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x4e3a3754410177e6937ef1f84bba68ea139e8d1a2258c5f85db9f1cd715a1bdd","blockNumber":"0xb443","contractAddress":null,"cumulativeGasUsed":"0x5208","from":"0xa1e4380a3b1f749673e270229993ee55f35663b4","gasUsed":"0x5208","logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","root":"0x96a8e009d2b88b1483e6941e6812e32263b05683fac202abc622a3e31aed1957","to":"0x5df9b87991262f6ba471f09758cde1c0fc1de734","transactionHash":"0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060","transactionIndex":"0x0"}}```

#### Actual behaviour

The result under >=1.10.0 is:

`{"jsonrpc":"2.0","id":1,"result":null}`

#### Steps to reproduce the behaviour

The easiest way to reproduce is to create a new db by specifying a new datadir:

```
git checkout tags/v1.10.0
make geth && ./build/bin/geth --datadir='./ethereum1.10.0/'
# let this sync till block ~47k
`nc -U geth.ipc`
# issue command > result is null
```

```
git checkout tags/v1.9.25
make geth && ./build/bin/geth --datadir='./ethereum1.9.25/'
# let this sync till block ~47k
`nc -U geth.ipc`
# issue command > result is correct
```

#### Further info
When at first starting the node with version 1.9.25 and letting it sync till block ~47k, then compiling v1.10.0 and starting it with the same datadir as 1.9.25, the RPC command will return the correct result. However, after a while (I dont know how long, but eventually), the result of the RPC request will again be null. Without knowing, my guess would be that geth does some background processing to the chaindata at some point of time. Downgrading back to 1.9.25 (and using again the same datadir) does then not fix the issue, at least not in the first couple minutes of running it. 

Maybe I should also add that I have a fully synced node running on  1.10.2 where this problem persists, so it's not a matter of synchronization progress. 

I hope I was able to explain the problem precisely.

**Comment by Neurone** [comment]
geth 1.10.0 introduced the [Transaction unindexing feature](https://blog.ethereum.org/2021/03/03/geth-v1-10-0/), it is activated by default. Maybe is it that? Try to pass `--txlookuplimit=0` and check the result.

> Can we shave some - for us - useless data off of our nodes? Yes! Geth v1.10.0 switches on transaction unindexing by default and sets it to 2,350,000 blocks (about 1 year). The transaction unindexer will linger in the background, and every time a new block arrives, it ensures that only transactions from the most recent N blocks are indexed, deleting older ones. If a user decides they want access to older transactions, they can restart Geth with a higher --txlookuplimit value, and any blocks missing from the updated range will be reindexed (note, the trigger is still block import, you have to wait for 1 new block).
> 
> Since about 1/3rd of Ethereum’s transaction load happened in 2020, keeping an entire year’s worth of transaction index will still have a noticeable weight on the database. The goal of transaction unindexing is not to remove an existing feature in the name of saving space. The goal is to move towards a mode of operation where space does not grow indefinitely with chain history.
> 
> If you wish to disable transaction unindexing altogether, you can run Geth with --txlookuplimit=0, which reverts to the old behavior of retaining the lookup map for every transaction since genesis.

**Comment by tanmaster** [comment]
> geth 1.10.0 introduced the [Transaction unindexing feature](https://blog.ethereum.org/2021/03/03/geth-v1-10-0/), it is activated by default. Maybe is it that? Try to pass `--txlookuplimit=0` and check the result.

Thanks a lot, it was exactly that! Next time I'll read the change logs before posting a question!

**Comment by xloem** [comment]
Is there any way to work around this when running a light node, to get receipts for historical transactions?

**Comment by Neurone** [comment]
I don't think so. As a light client, you relay on the data stored by the full node, so there's no way to do that but connecting to another full node actually storing historical transactions you need.

**Comment by xloem** [comment]
Thank you.
