### ISSUE TITLE
Mist: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by hackappcom** [ethereum/go-ethereum#228]
I've cloned go-ethereum on my linuxbox (Linux bright 3.17.2-1-ARCH #1 SMP PREEMPT Thu Oct 30 20:49:39 CET 2014 x86_64 GNU/Linux,  go version go1.4 linux/amd64 qt version 5.4.0)

and I try to launch GUI,  I get this:

[21:49:49 afx237@bright:~/go-ethereum]$/home/user/gocode/bin/mist   -asset_path="/home/afx237/go-ethereum/cmd/mist/assets/"
2015/01/02 21:49:58 [CLI] Main address 2777d2483e20d61a3a6f39ed8dce0bf2f1900b02
2015/01/02 21:50:08 [CHAIN] Last block (#0) 779b1b620b03c0fb24963e183d5e88e3dbe4484e3f6e2aa05942e3be7b48e179
ETH stack took 10.031407484s
2015/01/02 21:50:08 [GUI] Starting GUI
2015/01/02 21:50:08 [CLI] Starting Mist/v0.7.11/linux/go1.4
2015/01/02 21:50:08 [SERV] Ready and accepting connections
2015/01/02 21:50:08 [JSRE] started
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x7f6395b88c9a]

runtime stack:
runtime.gothrow(0xd25370, 0x2a)
        /usr/lib/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
        /usr/lib/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x44f050, 0xc208109d30, 0x0)
        /usr/lib/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208109d10 sp=0xc208109ce8
gopkg.in/qml%2ev1._Cfunc_componentCreateWindow(0x1f60910, 0x0, 0x0)
        /home/user/gocode/src/gopkg.in/qml.v1/:83 +0x44 fp=0xc208109d30 sp=0xc208109d10
gopkg.in/qml%2ev1.func·026()
        /home/user/gocode/src/gopkg.in/qml.v1/qml.go:750 +0x56 fp=0xc208109d58 sp=0xc208109d30
gopkg.in/qml%2ev1.hookIdleTimer()
        /home/user/gocode/src/gopkg.in/qml.v1/bridge.go:190 +0x60 fp=0xc208109d88 sp=0xc208109d58
runtime.call16(0x7fff8499a230, 0x7fff8499a2bf, 0x0)
        /usr/lib/go/src/runtime/asm_amd64.s:401 +0x45 fp=0xc208109da0 sp=0xc208109d88
runtime.cgocallbackg1()
        /usr/lib/go/src/runtime/cgocall.go:239 +0x12a fp=0xc208109e00 sp=0xc208109da0
runtime.cgocallbackg()
        /usr/lib/go/src/runtime/cgocall.go:193 +0x6e fp=0xc208109e30 sp=0xc208109e00
runtime.cgocallback_gofunc(0x53cd8f, 0x5027ad, 0x44eeb0)
        /usr/lib/go/src/runtime/asm_amd64.s:766 +0x57 fp=0xc208109e40 sp=0xc208109e30
asmcgocall()
        /usr/lib/go/src/runtime/asm_amd64.s:649 +0x37 fp=0xc208109e48 sp=0xc208109e40
runtime.asmcgocall_errno(0x44eeb0, 0xc208109e98)
        /usr/lib/go/src/runtime/asm_amd64.s:626 +0xf fp=0xc208109e50 sp=0xc208109e48
runtime.cgocall_errno(0x44eeb0, 0xc208109e98, 0x0)
        /usr/lib/go/src/runtime/cgocall.go:131 +0x10d fp=0xc208109e78 sp=0xc208109e50
gopkg.in/qml%2ev1._Cfunc_applicationExec()
        /home/user/gocode/src/gopkg.in/qml.v1/:59 +0x45 fp=0xc208109e98 sp=0xc208109e78
gopkg.in/qml%2ev1.Run(0xea9a58, 0x0, 0x0)
        /home/user/gocode/src/gopkg.in/qml.v1/bridge.go:63 +0x204 fp=0xc208109ef8 sp=0xc208109e98
main.main()
        /home/user/gocode/src/github.com/ethereum/go-ethereum/cmd/mist/main.go:94 +0x72 fp=0xc208109f98 sp=0xc208109ef8
runtime.main()
        /usr/lib/go/src/runtime/proc.go:63 +0xf3 fp=0xc208109fe0 sp=0xc208109f98
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208109fe8 sp=0xc208109fe0

goroutine 5 [select]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
        /home/user/gocode/src/github.com/ethereum/go-ethereum/logger/loggers.go:78 +0x6d0
created by github.com/ethereum/go-ethereum/logger.init·1
        /home/user/gocode/src/github.com/ethereum/go-ethereum/logger/loggers.go:57 +0x25

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 8 [chan receive]:
gopkg.in/qml%2ev1.RunMain(0xc2080bcec0)
        /home/user/gocode/src/gopkg.in/qml.v1/bridge.go:88 +0xd6
gopkg.in/qml%2ev1.(*Common).CreateWindow(0xc20813c6d0, 0x0, 0x7f63984a1520)
        /home/user/gocode/src/gopkg.in/qml.v1/qml.go:751 +0x19d
main.(*Gui).createWindow(0xc208a24000, 0x7f63984a1520, 0xc20813c6d0, 0x7f63984a1520)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/cmd/mist/gui.go:221 +0x37
main.(*Gui).showWallet(0xc208a24000, 0xc20813c0e0, 0x7, 0x0, 0x0)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/cmd/mist/gui.go:196 +0xeb
main.(*Gui).Start(0xc208a24000, 0x7fff8499afd3, 0x29)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/cmd/mist/gui.go:155 +0x784
main.run(0x0, 0x0)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/cmd/mist/main.go:83 +0x77a
gopkg.in/qml%2ev1.func·002()
        /home/user/gocode/src/gopkg.in/qml.v1/bridge.go:60 +0x49
created by gopkg.in/qml%2ev1.Run
        /home/user/gocode/src/gopkg.in/qml.v1/bridge.go:62 +0x1fd

goroutine 18 [chan receive]:
github.com/ethereum/go-ethereum/logger.sysLoop(0x7f6398494d80, 0xc20812a410, 0xc20813e000, 0xc20800af60)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/logger/loggers.go:114 +0x64
created by github.com/ethereum/go-ethereum/logger.func·001
        /home/user/gocode/src/github.com/ethereum/go-ethereum/logger/loggers.go:74 +0x176

goroutine 34 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc208160000)
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x24c

goroutine 9 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc20813a000)
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x48c
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x849

goroutine 10 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc20813a000)
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x863

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc20813a000)
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:812 +0x858
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x8a7

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc20813a000)
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x8c1

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc20813a000)
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x8db

goroutine 35 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc2080bb180)
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x24c

goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc2085b0000)
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x48c
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x849

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc2085b0000)
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x863

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc2085b0000)
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:812 +0x858
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x8a7

goroutine 66 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc2085b0000)
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x8c1

goroutine 67 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc2085b0000)
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/user/gocode/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x8db

goroutine 68 [syscall, locked to thread]:
net._C2func_getaddrinfo(0x7f63680008c0, 0x0, 0xc20858d918, 0xc20858d868, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/:26 +0x55
net.cgoLookupIPCNAME(0xc2080bce60, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/cgo_unix.go:96 +0x1c5
net.cgoLookupIP(0xc2080bce60, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5)
        /usr/lib/go/src/net/cgo_unix.go:148 +0x65

net.cgoLookupHost(0xc2080bce60, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/cgo_unix.go:27 +0x7c
net.lookupHost(0xc2080bce60, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/lookup_unix.go:56 +0x5f
net.LookupHost(0xc2080bce60, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/lookup.go:25 +0x5f
github.com/ethereum/go-ethereum.(*Ethereum).Seed(0xc208066140)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:459 +0xba3
github.com/ethereum/go-ethereum.(*Ethereum).Start(0xc208066140, 0xc65a01)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:420 +0x272
github.com/ethereum/go-ethereum/cmd/utils.StartEthereum(0xc208066140, 0xc208146001)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:163 +0x159
created by main.run
        /home/user/gocode/src/github.com/ethereum/go-ethereum/cmd/mist/main.go:78 +0x5e4

goroutine 69 [select]:
github.com/ethereum/go-ethereum.(*BlockPool).downloadThread(0xc20805c200)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/block_pool.go:247 +0x275
created by github.com/ethereum/go-ethereum.(*BlockPool).Start
        /home/user/gocode/src/github.com/ethereum/go-ethereum/block_pool.go:235 +0x32

goroutine 70 [select]:
github.com/ethereum/go-ethereum.(*BlockPool).chainThread(0xc20805c200)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/block_pool.go:294 +0xa93
created by github.com/ethereum/go-ethereum.(*BlockPool).Start
        /home/user/gocode/src/github.com/ethereum/go-ethereum/block_pool.go:236 +0x4c

goroutine 71 [IO wait]:
net.(*pollDesc).Wait(0xc208100290, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208100290, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208100230, 0x0, 0x7f6398494338, 0xc20802bc10)
        /usr/lib/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208146068, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208146068, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/ethereum/go-ethereum.(*Ethereum).peerHandler(0xc208066140, 0x7f639849c150, 0xc208146068)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:481 +0x37
created by github.com/ethereum/go-ethereum.(*Ethereum).Start
        /home/user/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:407 +0x4d0

goroutine 72 [chan receive]:
github.com/ethereum/go-ethereum.(*Ethereum).reapDeadPeerHandler(0xc208066140)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:387 +0x6b
created by github.com/ethereum/go-ethereum.(*Ethereum).Start
        /home/user/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:415 +0x21b

goroutine 73 [select]:
github.com/ethereum/go-ethereum.(*Ethereum).update(0xc208066140)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:574 +0x249
created by github.com/ethereum/go-ethereum.(*Ethereum).Start
        /home/user/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:416 +0x238

goroutine 74 [chan receive]:
github.com/ethereum/go-ethereum.(*Ethereum).filterLoop(0xc208066140)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:618 +0x1ed
created by github.com/ethereum/go-ethereum.(*Ethereum).Start
        /home/user/gocode/src/github.com/ethereum/go-ethereum/ethereum.go:417 +0x255

goroutine 51 [chan receive]:
github.com/ethereum/go-ethereum/javascript.(*JSRE).mainLoop(0xc208136750)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/javascript/javascript_runtime.go:110 +0x81
created by github.com/ethereum/go-ethereum/javascript.NewJSRE
        /home/user/gocode/src/github.com/ethereum/go-ethereum/javascript/javascript_runtime.go:69 +0x388
goroutine 75 [IO wait]:
net.(*pollDesc).Wait(0xc2085bf330, 0x77, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitWrite(0xc2085bf330, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:93 +0x43
net.(*netFD).connect(0xc2085bf2d0, 0x0, 0x0, 0x7f6398499ad0, 0xc208a38060, 0xecc38df6a, 0x1caac6e3, 0x12fb360, 0x0, 0x0)
        /usr/lib/go/src/net/fd_unix.go:114 +0x24b
net.(*netFD).dial(0xc2085bf2d0, 0x7f639849c188, 0x0, 0x7f639849c188, 0xc208a278c0, 0xecc38df6a, 0x1caac6e3, 0x12fb360, 0x0, 0x0)
        /usr/lib/go/src/net/sock_posix.go:139 +0x37a
net.socket(0xc4dff0, 0x3, 0x2, 0x1, 0x0, 0xc208a27800, 0x7f639849c188, 0x0, 0x7f639849c188, 0xc208a278c0, ...)
        /usr/lib/go/src/net/sock_posix.go:91 +0x422
net.internetSocket(0xc4dff0, 0x3, 0x7f639849c188, 0x0, 0x7f639849c188, 0xc208a278c0, 0xecc38df6a, 0x1caac6e3, 0x12fb360, 0x1, ...)
        /usr/lib/go/src/net/ipsock_posix.go:137 +0x148
net.dialTCP(0xc4dff0, 0x3, 0x0, 0xc208a278c0, 0xecc38df6a, 0x1caac6e3, 0x12fb360, 0xc208a30790, 0x0, 0x0)
        /usr/lib/go/src/net/tcpsock_posix.go:156 +0x125
net.dialSingle(0xc4dff0, 0x3, 0xc2080bc860, 0x12, 0x0, 0x0, 0x7f639849c120, 0xc208a278c0, 0xecc38df6a, 0x199999991caac6e3, ...)
        /usr/lib/go/src/net/dial.go:235 +0x3f5
net.func·016(0xecc38df6a, 0xe1caac6e3, 0x12fb360, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/dial.go:163 +0x12c
net.dial(0xc4dff0, 0x3, 0x7f639849c120, 0xc208a278c0, 0xc208059e58, 0xecc38df6a, 0xe1caac6e3, 0x12fb360, 0x0, 0x0, ...)
        /usr/lib/go/src/net/fd_unix.go:40 +0x6f
net.(*Dialer).Dial(0xc208a340c0, 0xc4dff0, 0x3, 0xc2080bc860, 0x12, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/dial.go:170 +0x4be
net.DialTimeout(0xc4dff0, 0x3, 0xc2080bc860, 0x12, 0x2540be400, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/dial.go:150 +0xe6
github.com/ethereum/go-ethereum.(*Peer).Connect(0xc208a561a0, 0xc2080bc860, 0x12, 0x0, 0x0, 0x0, 0x0)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/peer.go:226 +0x92
github.com/ethereum/go-ethereum.func·014()
        /home/user/gocode/src/github.com/ethereum/go-ethereum/peer.go:205 +0x3c
created by github.com/ethereum/go-ethereum.NewOutboundPeer
        /home/user/gocode/src/github.com/ethereum/go-ethereum/peer.go:218 +0x3e7

goroutine 76 [sleep]:
net.func·019()
        /usr/lib/go/src/net/dnsclient_unix.go:240 +0x5a
created by net.loadConfig
        /usr/lib/go/src/net/dnsclient_unix.go:269 +0x20c

**Comment by obscuren** [comment]
Which version of Qt5 do you have? (this is a known issue with 5.4)

**Comment by obscuren** [comment]
See https://github.com/ethereum/go-ethereum/issues/212#issuecomment-68538678

**Comment by hackappcom** [comment]
Thanks for your reply.
I've downgraded to  5.3.2 , but here is another problem:

[05:22:31 afx237@bright:~/go-ethereum]$/home/user/gocode/bin/mist   -asset_path="/home/afx237/go-ethereum/cmd/mist/assets/"
2015/01/03 05:23:02 [CLI] Main address a4d9a9a663a7858741e3228556529807628cafcb
2015/01/03 05:23:12 [CHAIN] Last block (#0) 779b1b620b03c0fb24963e183d5e88e3dbe4484e3f6e2aa05942e3be7b48e179
ETH stack took 10.034395417s
2015/01/03 05:23:12 [GUI] Starting GUI
2015/01/03 05:23:12 [CLI] Starting Mist/v0.7.11/linux/go1.4
2015/01/03 05:23:12 [SERV] Ready and accepting connections
2015/01/03 05:23:12 [JSRE] started
2015/01/03 05:23:12 qglxintegration.cpp:297: Could not initialize GLX
SIGABRT: abort
PC=0x7ffc42aef967
signal arrived during cgo execution

**Comment by hackappcom** [comment]
List of qt5 libs with versions:

afx237@bright ~> pacman -Q | grep qt5
phonon-qt5-gstreamer 4.8.0-2
python2-pyqt5 5.3.2-1
qt5-base 5.3.2-2
qt5-connectivity 5.3.2-2
qt5-declarative 5.3.2-2
qt5-enginio 5.3.2-2
qt5-graphicaleffects 5.3.2-2
qt5-imageformats 5.3.2-2
qt5-location 5.3.2-2
qt5-multimedia 5.3.2-2
qt5-quick1 5.3.2-2
qt5-quickcontrols 5.3.2-2
qt5-script 5.3.2-2
qt5-sensors 5.3.2-2
qt5-serialport 5.3.2-2
qt5-svg 5.3.2-2
qt5-tools 5.3.2-2
qt5-translations 5.3.2-2
qt5-webkit 5.3.2-2
qt5-websockets 5.3.2-2
qt5-x11extras 5.3.2-2
qt5-xmlpatterns 5.3.2-2

**Comment by hackappcom** [comment]
I've just figured out, it was mess with OpenGL drivers, you can read about it here:

https://harishnavnit.wordpress.com/2014/03/06/removing-nvidia-x-drivers-to-solve-the-glx-error/
http://forum.slitaz.org/topic/qt-creator-launch-error
https://bugreports.qt-project.org/browse/QTBUG-34109

On Arch I've just installed (removing all conflicts) mesa driver:

pacman -Sy mesa

**Comment by gillhofer** [comment]
My mist system crashed because of the same unexpected 0xb (Segfault) signal. My system also runs qt 5.4. 

But following the steps described in your first link, I can confirm that both problems are unrelated. My system correctly initialises the GLX extension of the Nvidia driver.

> cat /var/log/Xorg.0.log | grep GLX
>[     2.932] (II) NVIDIA GLX Module  346.35  Sat Jan 10 20:53:39 PST 2015
[     3.848] (II) Initializing extension GLX

But downgrading to qt 5.3.1 is currently not possible for me.
