### ISSUE TITLE
rpc: O(N**2) batch response matching

### ISSUE THREAD

**Issue by bennetyee** [ethereum/go-ethereum#22805]
https://github.com/ethereum/go-ethereum/blob/fc1c1cbea9123cfe6e403b8e21479fa90ee6f9ab/rpc/client.go#L367-L392

We scan the N=`len(b)` responses and for each we scan through `msgs` to look for the one with an `ID` that matches.  For large batches, if the response ID order is in reverse of the batch order, we can get O(N**2) runtime in the matching.

It may be okay to just add a comment to say do not use large batches in the interface, but ideally this shsould be fixed.

**Comment by fjl** [comment]
I will fix it.

**Comment by fjl** [comment]
No, not yet. I consider this low priority because batch requests are not used much. Even if used, I would consider it rare to use hundreds of requests in one batch. That said, I will fix it as soon as I get to it.
