### ISSUE TITLE
Node does not mine?

### ISSUE THREAD

**Issue by esmeevandenberg** [ethereum/go-ethereum#22800]
Hi, 

Currently I have set up two nodes. But they do not mine. See below my output. 

How come that my node does not start mining? 

![image](https://user-images.githubusercontent.com/70886818/116864182-be286900-ac07-11eb-8ed3-1c8306d2537d.png)

I have used the following start miner command: 
`geth -identity "Miner1" -networkid 42 -datadir "Thesis/Miner1" -nodiscover -mine -rpc -rpcport "8042" -rpcapi "db,eth,net,web3,miner" -port "30303" -unlock 0 --password Thesis/Miner1/password.sec -ipcpath "Ethereum/geth.ipc"
`

And the following genesis file: 
`{
  "config": {
    "chainId": 15,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "ethash": {}
  },
  "nonce": "0x0",
  "timestamp": "0x00",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x47b760",
  "difficulty": "0x02000",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "0000000000000000000000000000000000000088": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}`

**Comment by holiman** [comment]
Please provide the logs from the node (and preferrably not screenshots, but copy-pasted text). 

Note: there's no need to unlock the coinbase if you're doing PoW mining, that's only needed for PoA, where you seal the blocks with the key.

**Comment by esmeevandenberg** [comment]
See below the full log from the node, after starting it. 
Note that I entered the command: miner.start()  twice in the end. 



INFO [05-03|13:33:18.817] Maximum peer count                       ETH=50 LES=0 total=50
WARN [05-03|13:33:18.856] The flag --rpc is deprecated and will be removed June 2021, please use --http
WARN [05-03|13:33:18.859] The flag --rpcport is deprecated and will be removed June 2021, please use --http.port
WARN [05-03|13:33:18.860] The flag --rpcapi is deprecated and will be removed June 2021, please use --http.api
INFO [05-03|13:33:18.865] Set global gas cap                       cap=25000000
INFO [05-03|13:33:18.866] Allocated trie memory caches             clean=154.00MiB dirty=256.00MiB
INFO [05-03|13:33:18.868] Allocated cache and file handles         database=C:\Users\esmee\Thesis\Miner1\geth\chaindata cache=512.00MiB handles=8192
INFO [05-03|13:33:18.893] Opened ancient database                  database=C:\Users\esmee\Thesis\Miner1\geth\chaindata\ancient readonly=false
INFO [05-03|13:33:18.901] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, YOLO v3: <nil>, Engine: ethash}"
INFO [05-03|13:33:18.909] Disk storage enabled for ethash caches   dir=C:\Users\esmee\Thesis\Miner1\geth\ethash count=3
INFO [05-03|13:33:18.909] Disk storage enabled for ethash DAGs     dir=C:\Users\esmee\AppData\Local\Ethash      count=2
INFO [05-03|13:33:18.917] Initialising Ethereum protocol           network=42 dbversion=8
INFO [05-03|13:33:18.951] Loaded most recent local header          number=0 hash="d4e567…cb8fa3" td=17179869184 age=52y1mo11h
INFO [05-03|13:33:18.951] Loaded most recent local full block      number=0 hash="d4e567…cb8fa3" td=17179869184 age=52y1mo11h
INFO [05-03|13:33:18.959] Loaded most recent local fast block      number=0 hash="d4e567…cb8fa3" td=17179869184 age=52y1mo11h
INFO [05-03|13:33:18.959] Loaded local transaction journal         transactions=0 dropped=0
INFO [05-03|13:33:18.966] Regenerated local transaction journal    transactions=0 accounts=0
INFO [05-03|13:33:18.967] Allocated fast sync bloom                size=512.00MiB
WARN [05-03|13:33:18.975] Unclean shutdown detected                booted=2021-05-02T17:50:40+0200 age=19h42m38s
WARN [05-03|13:33:18.975] Unclean shutdown detected                booted=2021-05-03T13:07:16+0200 age=26m2s
INFO [05-03|13:33:18.983] Starting peer-to-peer node               instance=Geth/Miner1/v1.10.2-stable-97d11b01/windows-amd64/go1.16
INFO [05-03|13:33:19.005] New local node record                    seq=27 id=439b4bd53db8f4d2 ip=127.0.0.1 udp=0 tcp=30303
INFO [05-03|13:33:19.006] IPC endpoint opened                      url=\\.\pipe\Ethereum/geth.ipc
INFO [05-03|13:33:19.012] Started P2P networking                   self="enode://3088c33aa51cb1ad4da0473058aef6f96d563636b180f91bfea821feac7933e87ecc5c3135270209b0c4c9649352658f02523596fa417f8e2adf385c4f846def@127.0.0.1:30303?discport=0"
ERROR[05-03|13:33:19.018] Unavailable modules in HTTP API list     unavailable=[db] available="[admin debug web3 eth txpool personal ethash miner net]"
INFO [05-03|13:33:19.033] HTTP server started                      endpoint=127.0.0.1:8042 prefix= cors= vhosts=localhost
WARN [05-03|13:33:19.040] -------------------------------------------------------------------
WARN [05-03|13:33:19.041] Referring to accounts by order in the keystore folder is dangerous!
WARN [05-03|13:33:19.043] This functionality is deprecated and will be removed in the future!
WARN [05-03|13:33:19.046] Please use explicit addresses! (can search via `geth account list`)
WARN [05-03|13:33:19.048] -------------------------------------------------------------------
INFO [05-03|13:33:19.048] Initialized state bloom                  items=12356 errorrate=0.000 elapsed=73.126ms
INFO [05-03|13:33:20.062] Unlocked account                         address=0x3018a5c91bB59dE4b64843BdCb4cC4442a1B3fA3
INFO [05-03|13:33:20.062] Transaction pool price threshold updated price=1000000000
INFO [05-03|13:33:20.073] Updated mining threads                   threads=0
INFO [05-03|13:33:20.076] Transaction pool price threshold updated price=1000000000
INFO [05-03|13:33:20.083] Etherbase automatically configured       address=0x3018a5c91bB59dE4b64843BdCb4cC4442a1B3fA3
INFO [05-03|13:33:20.088] Commit new mining work                   number=1 sealhash="0d5438…fb0432" uncles=0 txs=0 gas=0 fees=0 elapsed=0s
INFO [05-03|13:33:21.921] Mapped network port                      proto=tcp extport=30303 intport=30303 interface="UPNP IGDv1-IP1"
INFO [05-03|13:34:01.476] Updated mining threads                   threads=8
INFO [05-03|13:34:14.861] Updated mining threads                   threads=8

**Comment by holiman** [comment]
```
INFO [05-03|13:33:20.088] Commit new mining work                   number=1 sealhash="0d5438…fb0432" uncles=0 txs=0 gas=0 fees=0 elapsed=0s
```
It's mining

**Comment by esmeevandenberg** [comment]
Sorry, if I do not understand it correctly. I am completely new here. 

But why, doesn't the mining continue? And why is my virtual balance not increasing? 
If I enter: **eth.getBalance(eth.accounts[1])** 
The balance is zero, of all accounts I have created. 

And the **eth.getBlock("latest").numbe**r also stays 0. 

So at the moment, it is not possible to do transactions between the accounts since they do not gain balance from mining.

**Comment by holiman** [comment]
How long did you let it run? You're using a proof-of-work engine, so doing CPU-mining, which means blocks actually take some time to mine.

**Comment by esmeevandenberg** [comment]
Yesterday I have waited for 3 hours, but nothing changed!

**Comment by karalabe** [comment]
What does `ethash.getHashrate()` say?

**Comment by esmeevandenberg** [comment]
I get the following output value: 
> ethash.getHashrate()
279559

**Comment by karalabe** [comment]
Seems it's mining just fine, but the difficulty is too large to find even a single block. You can try setting a lower starting difficulty. But perhaps you should just use a PoA network if you want to test things and don't need PoW.
