### ISSUE TITLE
native-bindings documentation needs updating

### ISSUE THREAD

**Issue by tmc** [ethereum/go-ethereum#22817]
https://geth.ethereum.org/docs/install-and-build/installing-geth

This document links to gists by @karalabe which don't compile with latest solidity.

**Comment by MariusVanDerWijden** [comment]
I don't see any link to a gist on the `installing-geth`page https://raw.githubusercontent.com/ethereum/go-ethereum/gh-pages/docs/_install-and-build/Installing-Geth.md

**Comment by MariusVanDerWijden** [comment]
Looks like this issue refers to an old version of the docs. The new docs don't have any links to gists afaict. Will close for now, feel free to reopen if the issue still persists
