### ISSUE TITLE
Checking 2 transactions wich are inter-dependent using eth_call?

### ISSUE THREAD

**Issue by slawomir-pryczek** [ethereum/go-ethereum#22810]
Checking single transaction is not an issue, but how to check multiple transactions?

```
example:
(1) First transaction will send 1 eth to account a
(2) Second transaction will send 1 eth from account a to account b
```

Now if I do 2 eth_call's (2) will fail as there is no balance on account a. I need to be able to run 2 transactions in a "block" which will retain state after (1) is executed, so the output will be that the "block" executed correctly. Is that possible using any API or maybe i can get changes to EVM state and pass it from transaction (1) to be used by transaction(2)?

Thanks for all help.

**Comment by rjl493456442** [comment]
You can override the state for `eth_call`. Check the doc here for `eth_call`
