### ISSUE TITLE
ths same issue

### ISSUE THREAD

**Issue by wingaimo** [ethereum/go-ethereum#22823]
my post on facebook is: https://www.facebook.com/aimo.wing.9/posts/100916242175679
and my address is 0x2e361a46487f5fa63d7c3f0c0d967b60017c69e5

**Comment by wingaimo** [comment]
> my post on facebook is: https://www.facebook.com/aimo.wing.9/posts/100916242175679
> and my address is 0x2e361a46487f5fa63d7c3f0c0d967b60017c69e5

please send fund, thank you!

**Comment by fjl** [comment]
If this is about the Rinkeby faucet, please note that your post must be public so that the faucet can see it.

**Comment by fjl** [comment]
I cannot see your post when clicking on it, so the faucet can probably not see it either.
