### ISSUE TITLE
Geth crashes on its own after running for several hours showing failed unlock Account

### ISSUE THREAD

**Issue by racetrack0616** [ethereum/go-ethereum#22829]
I started geth using the following command
`geth --snapshot=false --cache=4024  --rpc --rpcport 8545 --rpccorsdomain "*" --rpcapi eth,net,web3,personal,miner,admin,clique --networkid <network_id> --nat any --allow-insecure-unlock --unlock <my_address> --password "<password_file>" --datadir "node1" --http --mine`

It will start perfectly fine showing logs
![image](https://user-images.githubusercontent.com/68948218/117244793-6f720d80-ae59-11eb-9ae0-c919665ad585.png)
But it start to show following logs all of a sudden which doesn't even make sense.
![image](https://user-images.githubusercontent.com/68948218/117244860-8a448200-ae59-11eb-9b08-d282cb26b925.png)
Geth failing to unlock the account continuously is then causing high memory usage and then ultimately server crashes due to out of memory.
I am not sure why its trying to unlock the account which was unlocked initially. I have no idea how to resole the issue.

**Comment by karalabe** [comment]
Some process on your machine is attempting to brute force unlock your account (based on the localhost source addresses). Did you forward some port from the internet inside?

**Comment by racetrack0616** [comment]
> Some process on your machine is attempting to brute force unlock your account (based on the localhost source addresses). Did you forward some port from the internet inside?

- Sorry for the ignorance I am not sure I get you properly regarding forwarding some port. How do I start my geth ? What updates do I need to make for safer start?

**Comment by karalabe** [comment]
Something on your machine is making HTTP connections to your RPC port and trying to unlock your accounts. If your ports aren't exposed to the public internet, then you have a virus or other malicious program targeting your node.

**Comment by karalabe** [comment]
You also allowed any website in any browser tab to access your loclahost port, so a malicious website could also be trying to brute force your password.

**Comment by karalabe** [comment]
@holiman In this particular case, wouldn't `vhosts=localhost` prevent a browser from connecting?

**Comment by holiman** [comment]
This is indeed very curious. You could capture the traffic to that port, by doing `sudo tcpdump -p tcp -i lo -A  'port 8545'`. It dumps out the `tcp` packets on the `lo` (localhost) network interface, showing the `-A` (ascii) data sent over the wire, for port `8545`.

That might show you what is trying to connect to the service. 

Alternatively, you could try (without having the `geth` process running), to start a listener on `8545` which just dumps out the requests: 
```
$ ncat -l 8545
```
If I try to do a `geth attach http://localhost:8545`, this is what pops up: 
```
POST / HTTP/1.1
Host: 127.0.0.1:8545
User-Agent: Go-http-client/1.1
Content-Length: 47
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

{"jsonrpc":"2.0","id":1,"method":"rpc_modules"}
```

**Comment by racetrack0616** [comment]
> You also allowed any website in any browser tab to access your loclahost port, so a malicious website could also be trying to brute force your password.

I have web app that does connect private blockchain but no such rpc port related activities are in it. Other than that I have connected my private blockchain with Metamask but that also only requires rpc url and chain ID.

**Comment by holiman** [comment]
Both of those tricks should reveal to you what the `origin` is, which is basically the URL of the webpage which is doing this.

**Comment by holiman** [comment]
> In this particular case, wouldn't vhosts=localhost prevent a browser from connecting?

No (and yes). It wouldn't prevent a rogue webpage from making requests, such as submitting a transaction. It would only prevent the rogue webpage from reading the response.

**Comment by racetrack0616** [comment]
> Both of those tricks should reveal to you what the `origin` is, which is basically the URL of the webpage which is doing this.

Thanks. I will give a try and monitor it. Those attempts might occur at any time, sometimes more frequently and sometimes not once in a day. Although I will start monitoring it.

**Comment by racetrack0616** [comment]
> No (and yes). It wouldn't prevent a rogue webpage from making requests, such as submitting a transaction. It would only prevent the rogue webpage from reading the response.
> 
> EDIT to add: If the rogue webpage issues a cors json request to http://localhost/... , then the vhost would be correct, so it would be let through the vhosts filter. Since the `rpccorsdomain` is wildcard, however, it would still have a full bidirectional total communication.
> 
> Your setup is extremely insecure.

I  will also try to run geth update the `rpccorsdomain` passing only my desired domain.

**Comment by racetrack0616** [comment]
I started geth within `--nodiscover` and only with valid domains in `rpccorsdomain`. I am also monitoring the tcp logs. Amazingly I see no such issues. May be it worked. Thanks everyone.
