### ISSUE TITLE
Insufficient funds calculation is off

### ISSUE THREAD

**Issue by madduck** [ethereum/go-ethereum#2283]
I am trying the following in geth (v1.3.3, Ubuntu):

    d = 0xdeadbeef…
    v = 1000
    v = eth.getBalance(eth.coinbase) - eth.gasPrice * eth.estimateGas({from: eth.coinbase, to: d, value: v })
    eth.sendTransaction({from: eth.coinbase, to: d, value: v})

but this yields:

    Insufficient funds for gas * price + value
        at InvalidResponse (<anonymous>:-81662:-104)
        at send (<anonymous>:-156322:-104)
        at sendTransaction (<anonymous>:-133322:-104)
        at <anonymous>:1:1

which seems a bit weird. `eth.estimateGas` returns the going rate of 21,000. That should be all I need, no?

**Comment by madduck** [comment]
FTR, adding `gas: 21000` to the `eth.sendTransaction` call makes it go through just fine.

**Comment by obscuren** [comment]
You need big integer arithmetic. JavaScript implements integers as 32 bit ints (`2^32`). It's very likely that your balance in wei exceeds that number:

```
> eth.getBalance(eth.coinbase)
1.2230537249418869769081e+22
```

Try something like

```
eth.getBalance(eth.coinbase).sub(eth.gasPrice).Mul(....)
````

**Comment by madduck** [comment]
Thanks for the explanation! I hope the day doesn't come when an overflow or otherwise problem with the limited JavaScript scope yields to big losses.
