### ISSUE TITLE
After upgrade to 1.10.3 import of new chain segment takes 30 seconds while generating snapshot

### ISSUE THREAD

**Issue by farmer69420** [ethereum/go-ethereum#22839]
#### System information

Geth version: `1.10.3`
OS & Version: Linux

#### Expected behaviour
Node keep in sync while generating snapshot.

#### Actual behaviour
Node is falling behind while generating snapshot. Import of new chain segment takes around 30 seconds. It took around 1 sec before upgrade.

#### Steps to reproduce the behaviour
- clean shutdown of synced archive node version 1.10.2, that was halfway through snapshot generation
- upgrade to 1.10.3

#### Backtrace
before upgrade
````
May 06 20:59:53 ethnode geth[112378]: INFO [05-06|20:59:53.424] Aborting state snapshot generation       root="d82904…03c5ca" in="940916…91232a" at="62174c…b0a268" accounts=68158719 slots=227258352 storage=19.39GiB   elapsed=620h53m21.392s eta=452h49m25.934s
May 06 20:59:53 ethnode geth[112378]: INFO [05-06|20:59:53.446] Resuming state snapshot generation       root="484609…3a7ac9" in="940916…91232a" at="62174c…b0a268" accounts=68158719 slots=227258352 storage=19.39GiB   elapsed=620h53m21.414s eta=452h49m25.95s
May 06 20:59:53 ethnode geth[112378]: INFO [05-06|20:59:53.486] Imported new chain segment               blocks=1   txs=151  mgas=14.947  elapsed=563.071ms      mgasps=26.546  number=12383048 hash="98b7be…29c07e" dirty=0.00B
May 06 20:59:54 ethnode geth[112378]: INFO [05-06|20:59:54.606] Aborting state snapshot generation       root="484609…3a7ac9" in="940916…91232a" at="62236f…41af96" accounts=68158719 slots=227258434 storage=19.39GiB   elapsed=620h53m22.573s eta=452h49m26.795s
May 06 20:59:54 ethnode geth[112378]: INFO [05-06|20:59:54.681] Resuming state snapshot generation       root="16cdec…b92306" in="940916…91232a" at="62236f…41af96" accounts=68158719 slots=227258434 storage=19.39GiB   elapsed=620h53m22.649s eta=452h49m26.851s
May 06 20:59:54 ethnode geth[112378]: INFO [05-06|20:59:54.724] Imported new chain segment               blocks=1   txs=163  mgas=14.173  elapsed=1.228s         mgasps=11.537  number=12383049 hash="331541…a28a81" dirty=0.00B
May 06 20:59:56 ethnode geth[112378]: INFO [05-06|20:59:56.816] HTTP server stopped                      endpoint=172.31.26.205:8545
May 06 20:59:56 ethnode geth[112378]: INFO [05-06|20:59:56.829] IPC endpoint closed                      url=/ethereum/datadir/geth.ipc
May 06 20:59:56 ethnode geth[112378]: INFO [05-06|20:59:56.861] Ethereum protocol stopped
May 06 20:59:56 ethnode geth[112378]: INFO [05-06|20:59:56.868] Transaction pool stopped
May 06 20:59:56 ethnode geth[112378]: INFO [05-06|20:59:56.899] Aborting state snapshot generation       root="16cdec…b92306" in="940916…91232a" at="623a9a…fcefe0" accounts=68158719 slots=227258585 storage=19.39GiB   elapsed=620h53m24.867s eta=452h49m28.468s
May 06 20:59:56 ethnode geth[112378]: INFO [05-06|20:59:56.899] Journalling in-progress snapshot         root="16cdec…b92306" in="940916…91232a" at="623a9a…fcefe0" accounts=68158719 slots=227258585 storage=19.39GiB   elapsed=620h53m24.867s eta=452h49m28.468s
May 06 20:59:56 ethnode geth[112378]: INFO [05-06|20:59:56.906] Writing clean trie cache to disk         path=/ethereum/datadir/geth/triecache threads=8
May 06 21:00:06 ethnode geth[112378]: INFO [05-06|21:00:06.268] Persisted the clean trie cache           path=/ethereum/datadir/geth/triecache elapsed=9.362s
May 06 21:00:06 ethnode geth[112378]: INFO [05-06|21:00:06.268] Blockchain stopped
May 06 21:00:07 ethnode geth[112378]: INFO [05-06|21:00:07.522] Looking for peers                        peercount=1  tried=49 static=0
May 06 21:00:10 ethnode systemd[1]: geth.service: Succeeded.
May 06 21:00:10 ethnode systemd[1]: Stopped Ethereum go client.

````

after upgrade (it was restarted again to increase resources)
`````
May 07 10:44:06 ethnode geth[1685]: INFO [05-07|10:44:06.200] Imported new chain segment               blocks=1 txs=484 mgas=14.951 elapsed=30.210s      mgasps=0.495 number=12,384,356 hash=5ebf6a..ce82cb age=8h43m56s dirty=0.00B
May 07 10:44:36 ethnode geth[1685]: INFO [05-07|10:44:36.088] Aborting state snapshot generation       root=4ff6f0..781f35 at=940916..91232a accounts=68,158,719 slots=227,575,308 storage=19.41GiB elapsed=2h13m47.171s
May 07 10:44:36 ethnode geth[1685]: INFO [05-07|10:44:36.092] Resuming state snapshot generation       root=868682..1e18aa at=940916..91232a accounts=68,158,719 slots=227,575,308 storage=19.41GiB elapsed=2h13m47.176s
May 07 10:44:36 ethnode geth[1685]: INFO [05-07|10:44:36.150] Imported new chain segment               blocks=1 txs=494 mgas=14.952 elapsed=29.950s      mgasps=0.499 number=12,384,357 hash=8cc98a..5183c6 age=8h43m53s dirty=0.00B
May 07 10:44:39 ethnode geth[1685]: INFO [05-07|10:44:39.725] Deep froze chain segment                 blocks=2 elapsed=19.229ms     number=12,294,357 hash=c93cd6..dbf0e9
May 07 10:45:06 ethnode geth[1685]: INFO [05-07|10:45:06.028] Aborting state snapshot generation       root=868682..1e18aa at=940916..91232a accounts=68,158,719 slots=227,575,308 storage=19.41GiB elapsed=2h14m17.112s
May 07 10:45:06 ethnode geth[1685]: INFO [05-07|10:45:06.044] Resuming state snapshot generation       root=a6baa1..592394 at=940916..91232a accounts=68,158,719 slots=227,575,308 storage=19.41GiB elapsed=2h14m17.127s
May 07 10:45:06 ethnode geth[1685]: INFO [05-07|10:45:06.101] Imported new chain segment               blocks=1 txs=241 mgas=14.959 elapsed=29.950s      mgasps=0.499 number=12,384,358 hash=583074..199800 age=8h44m16s dirty=0.00B
`````

We also noticed weird reported reading behaviour. Geth is reporting huge storage reading, but we don't see it on OS level.
geth:
![image](https://user-images.githubusercontent.com/74717373/117439662-681f3280-af33-11eb-866f-0fb0a58051c6.png)
os:
![image](https://user-images.githubusercontent.com/74717373/117439799-969d0d80-af33-11eb-8e2e-d4925b7ff0a4.png)

EDIT: with `--snapshot=false` is node performace as expected

**Comment by karalabe** [comment]
Generating the snapshot for a node that didn't have it yet unfortunately is super slow. Full syncing would implicitly have the snapshots from block imports, and snap syncing would have most of it from the network and only need a fixup round. Fast sync (deprecated soon) or an old node will take a hit while it's generating unfortunately. I don't see a way around and unsure if there's anything to fix it given that it's a temporary state.

**Comment by nebojsa94** [comment]
That makes sense, but why does it slow down the import so much? Nodes are going out sync on very beefy machines when snapshots are enabled. which is by default. Btw, the speed of snapshotting on 1.10.3 is like 20x faster than 1.10.1, but it gets stuck where version 1.10.1 stopped previous snapshotting even when it starts from scratch on the new version. Could it be that snapshot resuming is somehow not compatible between 1.10.3 and 1.10.[0-2]?

**Comment by farmer69420** [comment]
We exprience the same. Gets gets almost stuck on snapshot resumed from previous version. Is it possible to drop snapshot generated by previous version and start generating it again on version 1.10.3?

**Comment by karalabe** [comment]
There are a number of ways out of this situation (slow snapshot generation on an old archive node):

1. Disable snapshots via `--snapshot=false`. This is easy, but will stop working eventually as we'll drop the flag at some point.
2. Wait snapshot generation out. This is super slow since iterating an archive node is insane, but does eventually get there.
3. Resync an entire archive node form 0. This will maintain the snapshot in lockstep with sync.
4. Sync another node via snap sync, export the snapshot data from it `geth db export snapshot dump.gz` and then import it on another node `geth db import dump.gz`. On startup, your archive node should regenerate the snapshot using the imported "old" data, which ideally is almost exactly what you need. Disclaimer: I haven't tried it on a mainnet archive node, so I can't 100% guarantee it will go without hiccups.
