### ISSUE TITLE
can not find geth.ipc anywhere.

### ISSUE THREAD

**Issue by magic-thomas** [ethereum/go-ethereum#22849]
#### System information
Geth version: `geth version`
 - Version: 1.10.3-stable

OS & Version: Windows/Linux/OSX
- ubuntu 12.04 LTS

Environment: docker, vagrant, host os
- native linux

#### Steps to reproduce the behavior

```sh
apt-get install software-properties-common 
add-apt-repository -y ppa:ethereum/ethereum 
apt-get update 
apt-get install ethereum
apt-get install geth
```
in console..

```sh
geth attach ipc:/mnt/eth-blockchain/geth.ipc

Fatal: Unable to attach to remote geth: dial unix /mnt/eth-blockchain/geth.ipc: connect: no such file or directory
```

#### Error Logs
```sh
Fatal: Unable to attach to remote geth: dial unix /mnt/eth-blockchain/geth.ipc: connect: no such file or directory
```

So I tried to find file. 
```sh
 find / -name "geth.ipc"
```

It shows nothing. 

What did I miss ?

**Comment by magic-thomas** [comment]
> Have you started geth? If so, could you provide your starting parameters?
> The `geth.ipc` is usually located in `.ethereum/geth.ipc` or `/tmp/geth.ipc`
> The startup log also prints out the location btw.
> 
> ```
> > geth --dev
> INFO [05-10|11:51:02.967] Starting Geth in ephemeral dev mode... 
> INFO [05-10|11:51:02.969] Maximum peer count                       ETH=50 LES=0 total=50
> INFO [05-10|11:51:02.969] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
> INFO [05-10|11:51:02.969] Set global gas cap                       cap=25000000
> [...]it was in 
> INFO [05-10|11:51:05.159] IPC endpoint opened                      url=/tmp/geth.ipc
> INFO [05-10|11:51:05.159] Transaction pool price threshold updated price=1000000000
> INFO [05-10|11:51:05.159] Transaction pool price threshold updated price=1
> ```

Thanks. 

I am newbie and didn't know I have to start geth first in another console. 

It was in '/tmp/geth.ipc' 

Thanks.

**Comment by MariusVanDerWijden** [comment]
No problem, good that it works now!
