### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by kamleshjoshi8102** [ethereum/go-ethereum#22863]
I can't find any solution to resolve this issue even in Discord server please help.!

/home/user/go-ethereum/build/bin/geth --datadir~/ethereum/net3/ init genesis/genesis3.json

bash: /home/kamlesh/go-ethereum/build/bin/geth: No such file or directory

**Comment by karalabe** [comment]
Did you build Geth locally? The geth executable does not exist on the path you specified.

**Comment by kamleshjoshi8102** [comment]
yep i have build it but i can't find my bin folder though I have made geth.json file too..!

**Comment by ZKhan007** [comment]
kamlesh was it solved? I am facing the same issue and I dont know how did you solve it

**Comment by kamleshjoshi8102** [comment]
No, it wasn't I tried different things but can't solve that issue. I don't know why he closed this 
If your issue gets solved then please notify me. : )
