### ISSUE TITLE
CPU Mining question

### ISSUE THREAD

**Issue by MiningNoobee** [ethereum/go-ethereum#22867]
Hi, 
I have installed and started Geth (full Ethereum node) using their document at: https://geth.ethereum.org/docs/
After my blockchain node is fully synchronized, I started mining with a newly created account address and proper quantity of threads.
Everything looked fine so far and console is running.
I can query  eth.hashrate, eth.coinbase, etc.
Just entering eth, I can see see that highest block in syncing{  }data is correct.

Today eth.getBalance(eth.coinbase) shows me a value which was 0 before. But searching for my address ( which is in eth.coinbase) in Etherscan or Etherchain websites return 0 balance.

Looking in my log I found these 2 lines:
INFO [05-12|05:34:50.204] Successfully sealed new block            number=1          sealhash=e86d04..65a314 hash=b358ec..26f2d4 elapsed=1h55m19.337s
INFO [05-12|05:34:50.248] 🔨 mined potential block                  number=1          hash=b358ec..26f2d4

Is there anything I am missing? how should I check and config my node (Geth on Windows) to work properly.
Thank you for your help.

**Comment by karalabe** [comment]
You seem to have mined block 1, so seems your chain is empty / your node is not yet synced. What does `eth.getBlock()` return?

**Comment by MiningNoobee** [comment]
I was using a separate volume of sas drives (3x10K as RAID 5) to keep all geth and chain data, now I am installing on 2 striped SSD supposing that problem was syncing. After full synchronization, I'll try again. BTW chain folder was not empty, it took more than a day to download full data 300GB or more. thanks for your reply.

**Comment by MariusVanDerWijden** [comment]
Will close for now, you can reopen if you like.
Your node was not synced yet, but the miner mined a block anyway. You should wait until the node is fully synced before activating the miner.
