### ISSUE TITLE
After Update 1.9.17 to 1.10.3: "cURL error 7: Failed to connect to 127.0.0.1 port 8545: Connection refused"

### ISSUE THREAD

**Issue by dappstatus** [ethereum/go-ethereum#22868]
I updated my version 1.9.17 to 1.10.3.
I resynced everything after that update and now i get the following error if i try to make a query; "cURL error 7: Failed to connect to 127.0.0.1 port 8545: Connection refused"

I use laravel for my query
`
$geth = new \gethrepository\Geth\JsonRpc([
            'version' => '2.0',
            'host' => '127.0.0.1',
            'port' => 8545,
            'assoc' => true,
        ]);
`

Everything was working before i did the update. (geth was deactivated for 2 weeks, but when it was active before, everything was working fine).

I didn't do any changes with my query code.
I already tried to use the actual server ip, but that didn't change anything.
I checked port 8545 with "ufw status" with the following response: "8545/tcp (v6) ALLOW Anywhere (v6)"
Checking the port with sudo ss -tulwn | grep 8545 shows no response. 
But that shouldn't be the problem, since it was working that way before.

I tried in my server console "curl https://domainname.com" which is working. "curl 127.0.0.1:8545" did response with Failed to connect. ServerIP:8545 did response with Failed to connect as well.

What could be the problem? Is there some setting i missed to change after the update?

**Comment by wenshunbiao** [comment]
Try to add the parameter `--http --http.api=eth,net,web3 --http.addr 0.0.0.0 --http.vhosts *` to start

**Comment by dappstatus** [comment]
I actually fixed it. By updating my geth version, i missed to change the following setting in config.toml
HTTPHost = ""
to
HTTPHost = "127.0.0.1"
