### ISSUE TITLE
Did you build Geth locally? The geth executable does not exist on the path you specified.

### ISSUE THREAD

**Issue by kamleshjoshi8102** [ethereum/go-ethereum#22866]
E: Command line option --datadir~/ethereum/net3/ is not understood in combination with the other options

I'm trying to run this command in Ubuntu 

/home/blockchain/go-ethereum/build/bin/geth –datadir ~/ethereum/net3/ init genesis/genesis3.json

and this error is comming 

Fatal: Failed to read genesis file: open genesis/genesis3.json: no such file or directory

I used this .json file 

{
    { "config":{ 
        "chainId": 123, 
        "homesteadBlock": 0, 
        "eip155Block": 0, 
        "eip158Block": 0, 
        }, 
    "nonce": "0x3", 
    "timestamp": "0x0", 
    "parentHash": "0x0000000000000000000000000000000000000000000000000000", 
    "extraData": "0x0", 
    "gasLimit": "0x4c4b40", 
    "difficulty": :0x400", 
    "mixhash": "0x0000000000000000000000000000000000000000000000000000", 
    "coinbase": "0x000000000000000000000000000000000", 
    "alloc":{ 
        }
}

**Comment by karalabe** [comment]
`genesis/genesis3.json: no such file or directory`

That file does not exist on the path you specified. Check where you put it and use the correct path.
