### ISSUE TITLE
How to overcome issue with the creation of DAG by using "bash create_dag.sh"..?

### ISSUE THREAD

**Issue by kashif-hub** [ethereum/go-ethereum#22862]
How to resolve the issue regarding with the creation of DAG data set by using "bash create_dag.sh" and getting some errors which is shown in snapshot.
![image](https://user-images.githubusercontent.com/84039991/117874262-2dfabb80-b2ba-11eb-83b2-d5d20bcba5ac.png)

**Comment by karalabe** [comment]
I have no idea what this is, it's not part of this repository.
