### ISSUE TITLE
sendTransaction timeout

### ISSUE THREAD

**Issue by erickcrus** [ethereum/go-ethereum#22874]
Sometimes my node just stop sending transactions, I can use most of the commands, but sendTransaction just timeout.

eth.syncing return false
eth.blockNumber return the latest block

htop shows my server is not overloaded (8cores 20gb ram)

It works sometimes, but then it stops and keep bugged for some hours, it was working perfectly about a week ago, no modifications have been made on the server and no updates on the node.

I'm trying to send the transaction from command line for test purposes, like:

eth.sendTransaction({from: "0x46da24dbb9a19dafaf620a363396cecf20c95fed",to: "0x46da24dbb9a19dafaf620a363396cecf20c95fed", value: "0"})

bsc.log don't show anything anormal.

Anyone experienced this issue?

Version: Version: Geth v1.0.7

**Comment by TheIceHole** [comment]
sorry to ask an unrelated question.How many peers can you connect with that configuration?

**Comment by MariusVanDerWijden** [comment]
This seems to be an issue on Binance Smart Chain which is not supported by the go-ethereum team
