### ISSUE TITLE
Wallet recovery.

### ISSUE THREAD

**Issue by whappshh** [ethereum/go-ethereum#22872]
Hello. In 2016 ish i created a eth wallet in Geth,remember doing it in cmd,using something like geth account new... 
So recently remembered about it,should have couple ETH's on it,checking the balance on it in etherscan.io it says 0. I have formatted the hard drive multiple times and i dont remember if the wallet itself was stored in HDD. I still have the HDD and im using it still. Ive made a topic about some problem i was having with mining and i was using geth 1.4.13,dont know if it helps tho. 
Just stating the problem and hopefully will get an answer if i can even recover the wallet, have all the passwords in my notebook. 
Thanks!

**Comment by holiman** [comment]
Well, if etherscan says the balance is zero, then there nothing to recover... (?)
