### ISSUE TITLE
Node stuck, sync false

### ISSUE THREAD

**Issue by duongvansang** [ethereum/go-ethereum#22875]
#### System information

Geth version: `Geth/v1.10.3-stable-991384a7/windows-amd64/go1.16.3`
OS & Version: Windows
Commit hash : (if `develop`)

#### Actual behaviour
Status is always sync false:
Welcome to the Geth JavaScript console!

instance: Geth/v1.10.3-stable-991384a7/windows-amd64/go1.16.3
at block: 12427059 (Thu May 13 2021 23:19:36 GMT+0700 (+07))
 datadir: D:\geth
 modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

To exit, press ctrl-d
> eth.syncing
false
> eth.blockNumber
12427091
>

WARN [05-13|23:22:24.879] Synchronisation failed, dropping peer    peer=b43a87c50a1e1b5c3c8d4211e311a522e5d7fcb23449fd93cc801c549c56ff34 err=timeout
ERROR[05-13|23:22:24.896] Ethereum peer removal failed             peer=b43a87c5 err="peer not registered"
INFO [05-13|23:23:12.809] Downloader queue stats                   receiptTasks=0 blockTasks=0 itemSize=52.29KiB throttle=1254
INFO [05-13|23:23:15.220] Imported new chain segment               blocks=2  txs=538  mgas=29.642  elapsed=1.029s    mgasps=28.804  number=12,427,076 hash=40e43b..a75a2d age=1m2s   dirty=209.43MiB
INFO [05-13|23:23:15.248] Unindexed transactions                   blocks=2  txs=216  tail=10,077,077 elapsed=3.526ms
INFO [05-13|23:23:16.307] Imported new chain segment               blocks=2  txs=410  mgas=29.641  elapsed=1.063s    mgasps=27.881  number=12,427,078 hash=4d6d3d..e60300 dirty=213.33MiB
INFO [05-13|23:23:16.335] Unindexed transactions                   blocks=2  txs=367  tail=10,077,079 elapsed=7.782ms
INFO [05-13|23:23:16.881] Imported new chain segment               blocks=1  txs=185  mgas=14.987  elapsed=540.103ms mgasps=27.749  number=12,427,079 hash=f91a52..176e72 dirty=215.06MiB
INFO [05-13|23:23:16.899] Unindexed transactions                   blocks=1  txs=134  tail=10,077,080 elapsed=2.377ms
INFO [05-13|23:23:17.225] Imported new chain segment               blocks=1  txs=179  mgas=14.799  elapsed=321.544ms mgasps=46.025  number=12,427,080 hash=354705..d71492 dirty=216.58MiB
INFO [05-13|23:23:17.243] Unindexed transactions                   blocks=1  txs=92   tail=10,077,081 elapsed=1.124ms
INFO [05-13|23:23:17.938] Imported new chain segment               blocks=1  txs=238  mgas=14.988  elapsed=689.702ms mgasps=21.731  number=12,427,081 hash=2a5b18..cb6604 dirty=218.57MiB
INFO [05-13|23:23:17.954] Unindexed transactions                   blocks=1  txs=0    tail=10,077,082 elapsed=1.001ms
INFO [05-13|23:23:18.406] Imported new chain segment               blocks=1  txs=255  mgas=14.800  elapsed=446.865ms mgasps=33.120  number=12,427,082 hash=f68426..fbf830 dirty=220.50MiB
INFO [05-13|23:23:18.426] Unindexed transactions                   blocks=1  txs=144  tail=10,077,083 elapsed=1.998ms
INFO [05-13|23:23:19.593] Imported new chain segment               blocks=1  txs=210  mgas=14.806  elapsed=971.132ms mgasps=15.247  number=12,427,083 hash=feb158..218525 dirty=222.45MiB
INFO [05-13|23:23:19.617] Unindexed transactions                   blocks=1  txs=219  tail=10,077,084 elapsed=2.944ms

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by MariusVanDerWijden** [comment]
Your node is up to date with the current network, so its not syncing anymore.
You can see in the logs that your node imported a block from 1 minute ago (`age=1m2s`) which means its in sync.
```
INFO [05-13|23:23:15.220] Imported new chain segment blocks=2 txs=538 mgas=29.642 elapsed=1.029s mgasps=28.804 number=12,427,076 hash=40e43b..a75a2d age=1m2s dirty=209.43MiB
```
Syncing is only set to true if your node needs to initially synchronize with the network
