### ISSUE TITLE
how to clear history from geth javascript console?

### ISSUE THREAD

**Issue by btcid** [ethereum/go-ethereum#2288]
i don't see a command to do this from the documentation. or did i miss it?

this is important to clear history after calling personal.unlockAccount so password will not stored in the geth history

**Comment by bas-vk** [comment]
This is a valid request. I'm working on some improvements in the console and will include this.

For this particular case, you can call `personal.unlockAccount` with only the address argument. The console will prompt you for the password.

**Comment by sorin** [comment]
Would this work? https://github.com/ethereum/go-ethereum/issues/2288
