### ISSUE TITLE
Ropsten stuck at 10253975

### ISSUE THREAD

**Issue by bert2002** [ethereum/go-ethereum#22885]
Hi,
it seems ropsten is stuck at `10253975`. We are running geth 1.10.3. This seems to be network wide.

bert

**Comment by MariusVanDerWijden** [comment]
Ropsten seems to look fine on etherscan... https://ropsten.etherscan.io/
Maybe it unstuck in the meantime?

**Comment by bert2002** [comment]
Seems like it @MariusVanDerWijden
