### ISSUE TITLE
Cant sync node fully on fast sync it gets stuck on a block and stays there

### ISSUE THREAD

**Issue by jadeden1999** [ethereum/go-ethereum#22880]
#### System information

Geth version: Geth
Version: 1.10.1-stable
Git Commit: c2d2f4ed8f232bb11663a1b01a2e578aa22f24bd
Architecture: amd64
Go Version: go1.16
Operating System: linux
GOPATH=
GOROOT=go
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour

syncing fully with highest block 

#### Actual behaviour
> eth.syncing
{
  currentBlock: 4047418, ( reaching a block and either decreasing or stating the same)(
  highestBlock: 12441640,
  knownStates: 22793780,
  pulledStates: 22786237,
  startingBlock: 3979047
}

#### Steps to reproduce the behaviour

geth --http 
#### Backtrace
additional data:
INFO [05-15|14:16:45.293] Looking for peers                        peercount=11 tried=34  static=0
ERROR[05-15|14:16:45.913] Ethereum peer removal failed             peer=d7cbc1b2         err="peer not registered"
WARN [05-15|14:16:47.624] Dropping unsynced node during sync       id=b769fbf2148ed347 conn=inbound addr=120.136.123.202:64686 type=OpenEthereum/v3.2.0-...
ERROR[05-15|14:16:48.578] Ethereum peer removal failed             peer=3557733f         err="peer not registered"
WARN [05-15|14:16:49.297] Dropping unsynced node during sync       id=38062aaaab6744b9 conn=inbound addr=206.189.148.205:39610 type=Geth/v1.9.25-stable-...
ERROR[05-15|14:16:49.313] Ethereum peer removal failed             peer=c141adf1         err="peer not registered"
INFO [05-15|14:16:55.294] Looking for peers                        peercount=8  tried=36  static=0
ERROR[05-15|14:16:56.856] Snapshot extension registration failed   peer=89027a8b         err="peer connected on snap without compatible eth support"
WARN [05-15|14:16:58.020] Checkpoint challenge timed out, dropping id=b8312d7ed459dc1b conn=inbound addr=27.111.160.18:30313   type=OpenEthereum/v3.2.4-...
ERROR[05-15|14:16:58.021] Ethereum peer removal failed             peer=b8312d7e         err="peer not registered"
WARN [05-15|14:16:58.150] Checkpoint challenge timed out, dropping id=5c963e1563ff58a6 conn=inbound addr=34.221.219.67:48496   type=OpenEthereum/v3.2.4-...
ERROR[05-15|14:16:58.151] Ethereum peer removal failed             peer=5c963e15         err="peer not registered"
WARN [05-15|14:16:59.362] Checkpoint challenge timed out, dropping id=58bab0cc27a56f26 conn=inbound addr=47.242.145.105:57154  type=Geth/v1.10.2-stable-...
ERROR[05-15|14:16:59.363] Ethereum peer removal failed             peer=58bab0cc         err="peer not registered"
ERROR[05-15|14:16:59.977] Ethereum peer removal failed             peer=f5704f9c         err="peer not registered"
WARN [05-15|14:17:02.246] Dropping unsynced node during sync       id=39ca1753907334ea conn=inbound addr=68.183.121.201:60404  type=Geth/v1.10.1-stable-...
INFO [05-15|14:17:05.663] Imported new block receipts              count=6    elapsed=40.084ms    number=3978644  hash="1f2bcd…fe3826" age=3y10mo4w  size=126.10KiB
INFO [05-15|14:17:10.948] Imported new state entries       
IOPS : [r=8000KiB/s,w=2658KiB/s][r=2000,w=664 IOPS]
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────TX:             cum:    684KB   peak:    367Kb                                                                        rates:    245Kb   271Kb   228Kb
RX:                    2.59MB            972Kb                                                                                  967Kb   965Kb   885Kb
TOTAL:                 3.26MB           1.30Mb                                                                                 1.18Mb  1.21Mb  1.09Mb
( from iftop)
i tried restarting geth no avail 

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
Seems to be importing based on your logs. Why do you say it's stuck?

**Comment by jadeden1999** [comment]
Hey guys found the culprit 
100kb/s is not enogh for syncing apparently :P
