### ISSUE TITLE
Geth Imported new chain segment sometimes freezes and sets node back by a minute or so.

### ISSUE THREAD

**Issue by ScriptLike** [ethereum/go-ethereum#22891]
#### System information

Geth version: 1.10.2-stable
OS & Version: Windows

#### Expected behaviour
node stays synced at all times

#### Actual behaviour
Sometimes when imported new chain segment the node will become out of sync for a minute or so

#### Steps to reproduce the behaviour
Run on windows with these settings 

Geth --cache=6144 --http --http.api=eth,web3,net,txpool, --txpool.globalslots=250000 --txpool.globalqueue=50000 --syncmode=fast --maxpeers 100

See trace below I bolded the line of info where the node becomes out of sync. What is the reason for this is it that I do not use enough cache, should  I limit maxpeers, or some other issue?

- INFO [05-17|22:13:11.680] Imported new chain segment               blocks=1  txs=161 mgas=14.973 elapsed=76.824ms  mgasps=194.903 number=12455620 hash="782690…bfec0c" dirty=589.21MiB
- INFO [05-17|22:13:11.683] Unindexed transactions                   blocks=1  txs=97  tail=10105621 elapsed="997.1µs"
- INFO [05-17|22:13:22.337] Imported new chain segment               blocks=1  txs=216 mgas=14.964 elapsed=281.673ms mgasps=53.125  number=12455621 hash="a26cc8…50718d" dirty=589.12MiB
- INFO [05-17|22:13:22.337] Unindexed transactions                   blocks=1  txs=134 tail=10105622 elapsed=0s
- INFO [05-17|22:13:22.841] Imported new chain segment               blocks=1  txs=1   mgas=12.322 elapsed=373.258ms mgasps=33.012  number=12455622 hash="ebcc85…0dfdd4" dirty=588.45MiB
- INFO [05-17|22:13:22.845] Unindexed transactions                   blocks=1  txs=113 tail=10105623 elapsed=1.219ms
- INFO [05-17|22:13:34.094] Deep froze chain segment                 blocks=7  elapsed=7.978ms   number=12365622 hash="0189fe…617c45"
- **INFO [05-17|22:14:29.156]** Imported new chain segment               blocks=1  txs=327 mgas=14.958 elapsed=172.619ms mgasps=86.654  number=12455623 hash="ee3d80…507ef2" **age=1m6s**   dirty=588.65MiB
- INFO [05-17|22:14:29.160] Unindexed transactions                   blocks=1  txs=111 tail=10105624 elapsed="997.3µs"
- INFO [05-17|22:14:55.821] Imported new chain segment               blocks=1  txs=312 mgas=14.964 elapsed=588.364ms mgasps=25.433  number=12455624 hash="91406d…598de9" dirty=588.72MiB

When submitting logs: please submit them as text and not screenshots.

**Comment by holiman** [comment]
The 'age' of a block is the header timestamp, which is set before the miner starts grinding the proof of work. As such, it's fully possible that the time on a brand new mined block is a bit 'old' already, since the mining time varies a bit.

**Comment by karalabe** [comment]
12455623's timestamp is 02:13:23 (the timestamp is when mining starts, so it's the mining timestamp of the parent).
12455624's timestamp is 02:14:28 (the mining time of 12455623).

So, it adds up, the "age" of 12455623 was correctly 1m6s, because it took 1m5s to mine it (and maybe a bit on top to propagate).

**Comment by ScriptLike** [comment]
@karalabe and @holiman  I looked on etherscan and from block 12455623  and for a few more blocks my node was a couple seconds behind confirming blocks than the confirmed timestamp on etherscan and then after a few more blocks the confirmed time for etherscan and my node were the same again. Is there anything I can do for my node to make sure that the incoming block is the most up to date and not a minute in the past? Should I run another geth node?

> 12455623's timestamp is 02:13:23 (the timestamp is when mining starts, so it's the mining timestamp of the parent).
> 12455624's timestamp is 02:14:28 (the mining time of 12455623).
> 
> So, it adds up, the "age" of 12455623 was correctly 1m6s, because it took 1m5s to mine it (and maybe a bit on top to propagate).
