### ISSUE TITLE
Sync issue with 1.3.5 on morden testnet

### ISSUE THREAD

**Issue by mtbitcoin** [ethereum/go-ethereum#2290]
Getting the following error when attempting to sync on testnet morden, the last successful block was 494441 :

E0303 17:15:07.034033    3020 blockchain.go:1385]     Difficulty check failed for header 29549000, 29534565
I0303 17:15:07.035031    3020 downloader.go:267] Synchronisation failed: Difficulty check failed for header 29549000, 29534565

**Comment by mtbitcoin** [comment]
response from karalabe:

"those error messages will keep on popping up until the homestead chain beats out the frontier miners producing the invalid chain"

**Comment by mtbitcoin** [comment]
karalabe
 01:24 
@mtbitcoin No, it's not a bug, it's the system just going crazy over the plethora of bad peers :smile:)

**Comment by Zoltu** [comment]
Does this mean that testnet is not working and there is no way to fix it?  I let my client run overnight and it spent all night spamming the same error message.

**Comment by Zoltu** [comment]
Updating to latest version of geth resolved this issue.
