### ISSUE TITLE
Reuse chain across tests

### ISSUE THREAD

**Issue by PavinStrickland** [ethereum/go-ethereum#22905]
I think it would be best to reuse the chain across tests where posssible. Many tests don't care about the specific content of the chain, we could just generate a long one and two forks on top and use that for all tests.

_Originally posted by @fjl in https://github.com/ethereum/go-ethereum/issues/17871#issuecomment-427850503_

**Comment by fjl** [comment]
I implemented this in https://github.com/ethereum/go-ethereum/pull/17916
