### ISSUE TITLE
Geth on localhost gives wrong pending nd queued data

### ISSUE THREAD

**Issue by KDawid** [ethereum/go-ethereum#22909]
#### System information

Geth version: `geth version` 
1.10.1-stable-c2d2f4ed

OS & Version: Windows/Linux/OSX
Linux

#### Expected behaviour
Get pending transactions from local binance node, match the result I get from https://bsc-dataseed1.binance.org
Get real pending transaction list

#### Actual behaviour
Number of pending transactions is more less than expected (~2000), number of queued transactions is much more than expected (~13000). 
Example: local node does not give back new token listings on pancakeswap but data from https://bsc-dataseed1.binance.org seems valid.
Local node seems to be synchronized.

#### Steps to reproduce the behaviour
using web3 in python3.8
getting pending transaction filter id with 'eth_newPendingTransactionFilter' method (POST to local node or https://bsc-dataseed1.binance.org)
using 'eth_getFilterChanges' method with the pending filter id (POST to local node or https://bsc-dataseed1.binance.org)

**Comment by holiman** [comment]
The `pending` and `queued` count is always your local node's view of the network, and is affected by the limits set on the local node. It's affected by the following options: 
```
TRANSACTION POOL OPTIONS:
 
 --txpool.pricelimit value           Minimum gas price limit to enforce for acceptance into the pool (default: 1)
  --txpool.pricebump value            Price bump percentage to replace an already existing transaction (default: 10)
  --txpool.accountslots value         Minimum number of executable transaction slots guaranteed per account (default: 16)
  --txpool.globalslots value          Maximum number of executable transaction slots for all accounts (default: 4096)
  --txpool.accountqueue value         Maximum number of non-executable transaction slots permitted per account (default: 64)
  --txpool.globalqueue value          Maximum number of non-executable transaction slots for all accounts (default: 1024)
  --txpool.lifetime value             Maximum amount of time non-executable transaction are queued (default: 3h0m0s)
```
That said, bsc has probably changed the defaults, and this repo is _not_ the proper place to file tickets related to bsc, they have their own forked repository.
