### ISSUE TITLE
puppeth/wallet:latest docker image uses an old version of geth

### ISSUE THREAD

**Issue by massi-ag** [ethereum/go-ethereum#22913]
#### System information

Geth version: `1.10.3-stable`
OS & Version: Ubuntu 18.04
Commit hash : (if `develop`)

#### Expected behaviour
When using puppeth to deploy a wallet service, it should run properly

#### Actual behaviour
wallet service container is simply crashing & rebooting

#### Steps to reproduce the behaviour
- Install Geth 1.10.3-stable
- With puppeth deploy  ethstats, bootnode & sealnode => those stetps are working fine
- try to deploy wallet and it is not working

Failing docker image :
```
puppeth/wallet       latest    fc77afa3c3eb   2 years ago         443MB
```

#### Backtrace
Using docker logs on wallet image

````
Geth
VERSION:
   1.9.0-unstable-43e1b7b1
...
Incorrect Usage. flag provided but not defined: -http

````
On the Wallet Dockerfile :
This is the failling command that uses the -http
echo $'exec geth --networkid 4242 --port 30304 --bootnodes enode://55b888e5e5f0c4fcd41b5c7d86bcb8c6eb5c03ef8134c6fced3b2cff6f78da86a5b69d7d657e8550227f51fa505fac2c215adc0255b9090937126ba74b4d3453@10.60.42.2:30303 --ethstats \'wallet:testchain@10.60.42.2:8081\' --cache=512 --http --http.addr=0.0.0.0 --http.corsdomain "*" --http.vhosts "*"' >> wallet.sh

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
Yeah, don't use the wallet. We wanted to have something cute, but it's not worth the hassle. We can't play catchup with integrating a wallet non stop and it's not really worth it either. Should probably just delete it altogether.
