### ISSUE TITLE
Error Bad Block #12464643

### ISSUE THREAD

**Issue by mikel2000** [ethereum/go-ethereum#22914]
#### System information
Version: 1.10.1-stable
Git Commit: c2d2f4ed8f232bb11663a1b01a2e578aa22f24bd
Git Commit Date: 20210308
Architecture: amd64
Go Version: go1.16
Operating System: linux
GOPATH=
GOROOT=go

#### Actual behaviour
For block 12464643 the error "bad block" occurred. Afterwards geth stopped importing new chain segments and seemed to start syncing. As I didn't see any progress, I shutdown geth, removed .ethereum and started syncing from scratch. Syncing worked without problems.

The following error messages repeated until I stopped geth.
```
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, YOLO v3: <nil>, Engine: ethash}

Number: 12464643
Hash: 0x827a753065f8342852301738c3d053d99dd98d2418ea21219b6d698f4cc78c0e
...
Error: invalid merkle root (remote: 66b393ca30a4886d6ad6be051263bae65356bd5878898bba48bb2fc22dafe623 local: 17e141c1347d04026c0684327ece140e378f40189a703d66b9fd1133bb67aac1)
##############################
```

**Comment by MariusVanDerWijden** [comment]
Weird. This seems to be the following block: https://etherscan.io/block/12464643 it looks like your data directory was fried. Does it work now after resyncing? Do you have some startup logs for the node (it should log unclean shutdowns which can potentially fry your database)

**Comment by mikel2000** [comment]
> Does it work now after resyncing? 

Yes, after syncing from scratch, it works without problems.

> Do you have some startup logs for the node (it should log unclean shutdowns which can potentially fry your database)

I had a look at the log, which I saved before starting the new sync. I didn't find an "unclean shutdown". Is this the exact wording I should look for in the log? 

Obviously I tried to start geth, although it was already running. This resulted in the error "Fatal: Failed to create the protocol stack: datadir already used by another process". This sounds for me, as this couldn't have caused the corruption.

**Comment by MariusVanDerWijden** [comment]
No the "datadir already used by another process" error can't cause a corruption.
Yeah, the nodes prints something like this on startup
 ```
 WARN [05-25|17:47:53.819] Unclean shutdown detected                booted=2020-12-28T14:21:51+0100 age=4mo4w2h
WARN [05-25|17:47:53.819] Unclean shutdown detected                booted=2021-01-27T13:29:20+0100 age=3mo4w3h
WARN [05-25|17:47:53.819] Unclean shutdown detected                booted=2021-01-27T13:36:25+0100 age=3mo4w3h
WARN [05-25|17:47:53.819] Unclean shutdown detected                booted=2021-02-26T14:30:25+0100 age=2mo4w2h
```
