### ISSUE TITLE
get from address in type.Transaction

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#22918]
hi, guys, how to get `from` address from `type.Transaction` type? I can get the `to` address by `tx.To().String()` but no similar method for get `from` address.

`https://github.com/ethereum/go-ethereum/blob/16bc57438bd3d28e947d12f6f295da62e4ca9e26/core/types/transaction.go#L50`
```
type Transaction struct {
	inner TxData    // Consensus contents of a transaction
	time  time.Time // Time first seen locally (spam avoidance)

	// caches
	hash atomic.Value
	size atomic.Value
	from atomic.Value
}
···

**Comment by huahuayu** [comment]
it seems someone has the same requirement https://github.com/ethereum/go-ethereum/issues/22627

but how can I construct a singer whenever I get a `type.Trsanction` @karalabe @krasi-georgiev

**Comment by metachris** [comment]
Try this:

```
if msg, err := tx.AsMessage(types.NewEIP155Signer(tx.ChainId())); err == nil {
	fromAddress = NewAddressDetail(msg.From().Hex())
}
```

**Comment by MariusVanDerWijden** [comment]
I think the best way to do so is:
```
from, err := types.Sender(types.NewEIP155Signer(tx.ChainId()), tx) 
if err != nil {
    from, err := types.Sender(types.HomesteadSigner{}, tx) 
}
```
Or you can use the ` types.LatestSignerForChainID(chainID *big.Int)` function to get the latest signer

**Comment by dmarzzz** [comment]
for posterity
```
from, err := types.Sender(types.LatestSignerForChainID(tx.ChainId()), tx)
```
worked best for me

**Comment by ngocnd0242** [comment]
```
func getFrom(tx *types.Transaction) (string, error) {
	from, err := types.Sender(types.LatestSignerForChainID(tx.ChainId()), tx)
	return from.String(), err
}
```
