### ISSUE TITLE
Windows UPnP freezes sometimes

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#2291]
I've encountered a few reports that Geth freezes on startup and it always turned out that disabling NAT/UPnP seems to immediately solve this issue. My guess is that the UPnP lookup just stalls for some reason (maybe Windows blocks it?) and it neither succeeds, nor fails, blocking up startup progress.

@fjl Was this something we already addressed, or if not, can't this be solved with a simple `Deadline` somewhere in the UPnP code?

Edit: Some details in:

 * https://github.com/ethereum/mist/issues/235

**Comment by fjl** [comment]
There is a deadline. We need to get a stack dump while it hangs to see where it is blocking.

**Comment by newmzy** [comment]
It's happening to me - if someone can help a noob like me to supply a "stack dump" I'll be happy to provide one.

**Comment by fjl** [comment]
@newmzy ok, if you're on 1.3.5 just hit Ctrl-C ten times.

**Comment by karalabe** [comment]
Managed to repro it, crash dump at https://gist.github.com/karalabe/0c3e79131ad94b5083aa (for the reference), fixed by the above PR.
