### ISSUE TITLE
newPendingTransactions support in ethclient.go

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#22916]
hi, for `eth_subscribe` method, I wonder why the client only supports `newHeads`

https://github.com/ethereum/go-ethereum/blob/16bc57438bd3d28e947d12f6f295da62e4ca9e26/ethclient/ethclient.go#L333

but don't support`newPendingTransactions` in [ethclient.go](https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go)

they are all be mentioned in the same place in the document: https://geth.ethereum.org/docs/rpc/pubsub

but if I want to subscribe `newPendingTransactions` I have to use underlaying rpc client. Since it's not exported, so I have to instantiation a `*rpc.Client` besides an `*ethclient.Client`

```go
type Client struct {	c *rpc.Client}
```

**Comment by huahuayu** [comment]
another issue is `newPendingTransactions` only returns tx hash, I have to do another query to get tx data, is it possible to return verbose tx content when subscribe?

**Comment by huahuayu** [comment]
@karalabe how do you think?

**Comment by MariusVanDerWijden** [comment]
`eth_subscribe` is a non-standard api and should therefore not be in ethclient but rather in the gethclient. I think supporting `newPendingTransactions` in the gethclient would be okay. Do you want to move and implement it?

**Comment by fjl** [comment]
This is not entirely true. We do have support for eth_subscribe APIs in ethclient, just not for pending transactions.

**Comment by MariusVanDerWijden** [comment]
I know, but it should not be in ethclient imo as it is not part of the json-rpc api standard

**Comment by senthilsamrat** [comment]
> https://geth.ethereum.org/docs/rpc/pubsub

can you post a sample code for subscribing to pending transaction. I am new to Go and Geth. Please it would help me a lot for my project. Thanks in advance!
