### ISSUE TITLE
Block synchronisation error

### ISSUE THREAD

**Issue by Neoblock8** [ethereum/go-ethereum#22934]
Hi,
Syncing ethereum mainnet with geth. 
**command:** ./geth --cache=1024 --rpc --rpcaddr <ip> --rpcport <port> --rpcapi admin,txpool,personal,eth,net,web3 --allow-insecure-unlock --port 30303 --lightpeers=500 console

'eth.syncing.highestBlock' does not match with current block of ethereum node.

>eth.syncing
{
  currentBlock: 4418410,
  highestBlock: 12244007,
  knownStates: 11192172,
  pulledStates: 11181643,
  startingBlock: 0
}

kindly solve this issue asap.

**Comment by MariusVanDerWijden** [comment]
You're not synced fully. After the node synced most blocks, it also needs to synchronize the current state of the network. This takes a long time currently. You need to wait until the `knownStates` are equal to `pulledStates`.
You can also try the snap sync mode with `--syncmode=snap`. 

There's no issue here, you just need to wait until your node is fully synced
