### ISSUE TITLE
same signedRawTx send to different node, the txHash all the same or different?

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#22956]
hi, if I have a signedRawTx, I want to broadcast it faster by sending to all the node I know, I wonder the txHash returned by the node, are they all the same or different?

**Comment by karalabe** [comment]
The tx hash is the hash of the tx :P All the nodes will compute the same hash if you give them the same data.

**Comment by huahuayu** [comment]
make sense :)

**Comment by huahuayu** [comment]
If I broadcast to all the nodes I know, it should be faster than (at least equal) the p2p network right? Hard to quantitative but I think so

**Comment by karalabe** [comment]
> If I broadcast to all the nodes I know, it should be faster than (at least equal) the p2p network right? Hard to quantitative but I think so

I wouldn't be able to put a number on it. Devp2p also propagates it super fast, it should cover the entire network in 2-3 hops.

**Comment by huahuayu** [comment]
we have this experience once a time, when listened a newTx in mempool, we send the exact same gasPrice tx, but our tx gets mined before the origin tx we listened to( our tx index is lower). Because we broadcast to all the nodes we know.

this is proof that it's meaningful to do this.

**Comment by huahuayu** [comment]
we have this experience once a time, when listened a newTx in mempool, we send the exact same gasPrice tx, but our tx gets mined before the origin tx we listened to( our tx index is lower). Because we broadcast to all the nodes we know.

this is proof that it's meaningful to do this.
