### ISSUE TITLE
Bad hard drive crashed, lost my mined ETH...

### ISSUE THREAD

**Issue by Film54** [ethereum/go-ethereum#2295]
My mining system's hard drive crashed bad... the system was accidentally dropped and now the drive is mechanically broken and the system will not boot up.  I hadn't transferred my mined ETH to my wallet yet, so it's still in my Frontier account.  I never backed up any files from miner.  Is that ETH gone forever?

Thanks.

**Comment by obscuren** [comment]
If the account contains a significant amount of ether I'd suggest you bring your harddrive to someone who has experience with damaged harddrives.

There's nothing we can do unfortunately. Good luck!

**Comment by Film54** [comment]
Thanks.
