### ISSUE TITLE
Geth 'OracleThreshold' is not defined in gasprice

### ISSUE THREAD

**Issue by RemiBaldy** [ethereum/go-ethereum#22954]
#### System information

Ubuntu 20.04
Geth
Version: 1.10.3-stable
Git Commit: 991384a7f6719e1125ca0be7fb27d0c4d1c5d2d3
Architecture: amd64
Go Version: go1.16.3
Operating System: linux
GOPATH=/home/ubuntu/go
GOROOT=go

#### Expected behaviour
When doing geth --config ./config.toml --datadir ./node  --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 given by the bsc tutorial (https://docs.binance.org/smart-chain/developer/fullnode.html).

#### Backtrace
I'm getting this error :
````
INFO [05-27|11:31:06.919] Starting Geth on Ethereum mainnet...
Fatal: ./config.toml, line 35: field 'OracleThreshold' is not defined in gasprice.Config, see https://godoc.org/github.com/ethereum/go-ethereum/eth/gasprice#Config for available fields
````

Edit:
I ran $geth console and it started running something, i don't know if i was suppose to do that... I saw it on (https://github.com/binance-chain/bsc). maybe that will resolve my problem...

Would be nice if someone could help me ?
Btw I didn't sync geth if that's the problem, but i rigorously followed the tutorial...

**Comment by holiman** [comment]
The tutorial you're following is related to BSC, but you're running go-ethereum, which has nothing to do with bsc. Looks like you have some setting in your config.toml which we don't support.

**Comment by RemiBaldy** [comment]
Right, yes i posted on wrong github... sorry. But isn't geth = go-ethereum ? cause they definitly run the bsc nodes with geth on this github (https://github.com/binance-chain/bsc)

**Comment by holiman** [comment]
Yes, they've forked go-ethereum, and afaict they haven't bothered changing the name of the resulting binary from `geth` to something else, so users are generally pretty confused about what's what.

**Comment by RemiBaldy** [comment]
Ok thanks a lot, i feel like it's gonna be a long road, have a good day !
