### ISSUE TITLE
Geth pendingTransactions listener get slow suddenly (not overtime, but suddenly)

### ISSUE THREAD

**Issue by ilyasELBANI** [ethereum/go-ethereum#22950]
So, I'm running a private node on AWS i3.2xlarge (8 vCPU, 61GiB RAM, 1.9 To NVMe SSD), and I double checked the problem doesn't seem to be coming from my code. I restarded the code thrice, I have a loop that check if the listeners is working, it was indeed, but the rate of TPS received was too low. Once I restarted my node with Geth, the problem was solved.

I'm not sure how to investigate the problem and determine the source so it doesn't repeat in the future, and is it possible to detect this somehow and autorestart geth in case of problems? I'm not sure how though, any ideas are welcome. 

Thanks!

#### System information

Geth version: 1.1.0-beta-032970b2-20210510
OS & Version: Ubuntu 20

#### Expected behaviour
my ethers.providers.on('Pending') should receive all pending transactions.

#### Actual behaviour
my ethers.providers.on('Pending') only receives a percentage of pending transactions making it miss a lot of interesting transaction for my bot.

#### Steps to reproduce the behaviour
Have a listener connected for hours, then you'll suddenly notice the change.

#### Backtrace
Here are the logs during the bug and during no bug 

[bsc.log.2021-05-26_07 No bugs ( Many submitted transaction) .txt](https://github.com/ethereum/go-ethereum/files/6546821/bsc.log.2021-05-26_07.No.bugs.Many.submitted.transaction.txt)
[bsc.log.2021-05-26_10 Bugged (Only two submitted transactions) .txt](https://github.com/ethereum/go-ethereum/files/6546822/bsc.log.2021-05-26_10.Bugged.Only.two.submitted.transactions.txt)

**Comment by holiman** [comment]
You are running a fork of geth, so please file issues on their repo instead.
