### ISSUE TITLE
Geth blockchain not syncing

### ISSUE THREAD

**Issue by gadfli** [ethereum/go-ethereum#2297]
Hi,

I've installed geth and opened the console using the command 'geth console', and as I understand it, geth should begin to sync the blockchain automatically, however it is stuck on block 0.

I'm using Windows 7 and I've made sure that my clock is synced to time.nist.gov.  I've also allowed connections to public networks on the firewall, and enabled network discovery in the network advanced sharing settings, but the console still says 'at block: 0'.

How do I get geth to sync to the ethereum blockchain so I can start mining my Windows PC?

Thanks, Phil

**Comment by rfikki** [comment]
Are you mining on private or testnet? Are you GPU mining or CPU mining? How did you install geth?

**Comment by fjl** [comment]
@pgalinsky in the console, what does `eth.syncing` return? The blockchain sync needs a short time before starting up. Once it is running, the result should look like:

```text
> eth.syncing
{
  currentBlock: 1086414,
  highestBlock: 1108691,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 1086414
}
```

**Comment by Fredar** [comment]
Same here, cant find any peers, tried to input some manually to no avail.
Tested on 1.3.3, 1.3.4 and 1.3.5.

**Comment by Fredar** [comment]
I have tried other clients, but also had problems so decided to look for causes on my PC side.

Turns out my clock was 90 seconds in the past of proper time (thought still syncing with windows time service). Updating to the right time fixed it for me.

**Comment by pgalinsky** [comment]
Thanks all for your quick replies.

@rfikki I'm not trying to mine on either a private net or test net.  I'm GPU mining. Using the latest binary, I installed Geth using the instructions here; https://www.cryptocompare.com/mining/guides/how-to-mine-ethereum/ 

@fjl the output from `eth.syncing` is; false

**Comment by Fredar** [comment]
@pgalinsky Check your time with some online service. (I mean compare them manually)
Yesterday I had to set my computer time 1 minute into the future to find any peers.

**Comment by karalabe** [comment]
@pgalinsky Could you run geth with `--verbosity=6` for a minute or two and paste the output into a github gist?

**Comment by dhruv-9** [comment]
@karalabe im facing the same problem being discussed herein.Iv been trying to sync the blockchain on Geth for the past three days now and have only managed to get half way through. Though initially i enjoyed download speeds of a few second per 256 blocks, speeds have decreased to more than two min per 256 blocks.. at this rate i dont see myself completely synced before another week.. 

Iv updated my system clock, turned off firewall and/or antivirus settings etc but all in vain..

I ran verbosity=6 as you asked for and here are the results:


b03b615660c25d7d2d3fcbeb52f7408bebfc924195520d094a6758e717205fb10f12cf586b4e2d60
828d26d79d4ac15321c5d2e892097b24bfa05ae: leveldb: not found
I0416 10:59:34.593949    3624 table.go:417] Bonding cf5d77175b03b615: known=fals
e, fails=0 age=405773h29m34.5939496s
I0416 10:59:34.586949    3624 database.go:183] failed to retrieve node eb6e1ba7d
16cd7a7e71de62cebce4a2fdf8293c350fd1d1b2d27564c15206853f70d9c2cdf29b446104a9e1f4
9af95d8dbc58671605f169fe42f72bf3dd9d2b9: leveldb: not found
I0416 10:59:34.594949    3624 table.go:417] Bonding eb6e1ba7d16cd7a7: known=fals
e, fails=0 age=405773h29m34.5949497s
I0416 10:59:34.587949    3624 database.go:183] failed to retrieve node 1fc35b16b
d10763a6d9fcb2fb2cc409a6fc14f61612171eeb28af0f50208ed290c6417b6dca242fbb1c48d1cd
5da06663a785f9cad50a0111b39abccb32360cb: leveldb: not found
I0416 10:59:34.596949    3624 table.go:417] Bonding 1fc35b16bd10763a: known=fals
e, fails=0 age=405773h29m34.5969498s
I0416 10:59:34.587949    3624 table.go:417] Bonding 3415d3bcd55539c1: known=fals
e, fails=0 age=405773h29m34.5879493s
I0416 10:59:34.586949    3624 database.go:183] failed to retrieve node ea339862b
d03e329437bee85213213b9d3ca1f62b2630e2a02e5ff77b3c1901dcc146a8d8e3c578491ac71d2e
d49affb8d4f1080d83c6a279556c977f3e146e0: leveldb: not found
I0416 10:59:34.586949    3624 database.go:183] failed to retrieve node f51ef0f0c
df3b6a37c64c818d939392992c51dbe09345451f819a7d5365fd23b5f312b433cf5b1c5a44d095e2
2184c06e677930ee5aef07b5febe318e8fa52e3: leveldb: not found


b03b615660c25d7d2d3fcbeb52f7408bebfc924195520d094a6758e717205fb10f12cf586b4e2d60
828d26d79d4ac15321c5d2e892097b24bfa05ae: leveldb: not found
I0416 10:59:34.593949    3624 table.go:417] Bonding cf5d77175b03b615: known=fals
e, fails=0 age=405773h29m34.5939496s
I0416 10:59:34.586949    3624 database.go:183] failed to retrieve node eb6e1ba7d
16cd7a7e71de62cebce4a2fdf8293c350fd1d1b2d27564c15206853f70d9c2cdf29b446104a9e1f4
9af95d8dbc58671605f169fe42f72bf3dd9d2b9: leveldb: not found
I0416 10:59:34.594949    3624 table.go:417] Bonding eb6e1ba7d16cd7a7: known=fals
e, fails=0 age=405773h29m34.5949497s
I0416 10:59:34.587949    3624 database.go:183] failed to retrieve node 1fc35b16b
d10763a6d9fcb2fb2cc409a6fc14f61612171eeb28af0f50208ed290c6417b6dca242fbb1c48d1cd
5da06663a785f9cad50a0111b39abccb32360cb: leveldb: not found
I0416 10:59:34.596949    3624 table.go:417] Bonding 1fc35b16bd10763a: known=fals
e, fails=0 age=405773h29m34.5969498s
I0416 10:59:34.587949    3624 table.go:417] Bonding 3415d3bcd55539c1: known=fals
e, fails=0 age=405773h29m34.5879493s
I0416 10:59:34.586949    3624 database.go:183] failed to retrieve node ea339862b
d03e329437bee85213213b9d3ca1f62b2630e2a02e5ff77b3c1901dcc146a8d8e3c578491ac71d2e
d49affb8d4f1080d83c6a279556c977f3e146e0: leveldb: not found
I0416 10:59:34.586949    3624 database.go:183] failed to retrieve node f51ef0f0c
df3b6a37c64c818d939392992c51dbe09345451f819a7d5365fd23b5f312b433cf5b1c5a44d095e2
2184c06e677930ee5aef07b5febe318e8fa52e3: leveldb: not found


b03b615660c25d7d2d3fcbeb52f7408bebfc924195520d094a6758e717205fb10f12cf586b4e2d60
828d26d79d4ac15321c5d2e892097b24bfa05ae: leveldb: not found
I0416 10:59:34.593949    3624 table.go:417] Bonding cf5d77175b03b615: known=fals
e, fails=0 age=405773h29m34.5939496s
I0416 10:59:34.586949    3624 database.go:183] failed to retrieve node eb6e1ba7d
16cd7a7e71de62cebce4a2fdf8293c350fd1d1b2d27564c15206853f70d9c2cdf29b446104a9e1f4
9af95d8dbc58671605f169fe42f72bf3dd9d2b9: leveldb: not found
I0416 10:59:34.594949    3624 table.go:417] Bonding eb6e1ba7d16cd7a7: known=fals
e, fails=0 age=405773h29m34.5949497s
I0416 10:59:34.587949    3624 database.go:183] failed to retrieve node 1fc35b16b
d10763a6d9fcb2fb2cc409a6fc14f61612171eeb28af0f50208ed290c6417b6dca242fbb1c48d1cd
5da06663a785f9cad50a0111b39abccb32360cb: leveldb: not found
I0416 10:59:34.596949    3624 table.go:417] Bonding 1fc35b16bd10763a: known=fals
e, fails=0 age=405773h29m34.5969498s
I0416 10:59:34.587949    3624 table.go:417] Bonding 3415d3bcd55539c1: known=fals
e, fails=0 age=405773h29m34.5879493s
I0416 10:59:34.586949    3624 database.go:183] failed to retrieve node ea339862b
d03e329437bee85213213b9d3ca1f62b2630e2a02e5ff77b3c1901dcc146a8d8e3c578491ac71d2e
d49affb8d4f1080d83c6a279556c977f3e146e0: leveldb: not found
I0416 10:59:34.586949    3624 database.go:183] failed to retrieve node f51ef0f0c
df3b6a37c64c818d939392992c51dbe09345451f819a7d5365fd23b5f312b433cf5b1c5a44d095e2
2184c06e677930ee5aef07b5febe318e8fa52e3: leveldb: not found


Could you help me troubleshoot? wasting way too much time trying to sync. 

Also  is there a list of active enodes somewhere, or the enodes of the bootstrap nodes? I would be most grateful if someone could post a list of 10-20 current stable working nodes. Would manually adding peers through admin.Peers() be suggested ?

Please help!

**Comment by dhruv-9** [comment]
@karalabe  

ok seems i have made a mistake while pasting the results.

here is the correct results after running --verbosity=6 


dffa5ac28e1171462104be1f58e2c86f5bd1475e4d509fda34c4db96b26eb1a91b3f1b0a63e022f6
22e49748f8722b3a4adea344eded8d11af552a3: leveldb: not found
I0416 10:59:35.524002    3624 table.go:417] Bonding fe453a6b5dffa5ac: known=fals
e, fails=0 age=405773h29m35.5240028s
I0416 10:59:35.521002    3624 database.go:183] failed to retrieve node 37a638b84
2b9546e725e24736dc67a62c0e2f3f4023755e88841decda3202899edebfb205d7ccdceeef7d8ae9
078f426010ddd5203f6ebc2068e05bd2e38ac48: leveldb: not found
I0416 10:59:35.526002    3624 table.go:417] Bonding 37a638b842b9546e: known=fals
e, fails=0 age=405773h29m35.5260029s
I0416 10:59:35.521002    3624 table.go:417] Bonding bfff1ddd6e58bbd3: known=fals
e, fails=0 age=405773h29m35.5210026s
I0416 10:59:35.528003    3624 udp.go:429] >>> 46.39.244.40:57181 discover.ping
I0416 10:59:35.521002    3624 udp.go:429] >>> 107.210.2.128:13232 discover.ping
I0416 10:59:35.522002    3624 database.go:183] failed to retrieve node cd4262411
28ff724f0c186a6e502d8fead69583dba24f7b2c9f135fe7251e4ba5f852964ad9740489999e7f0a
9164db1dc2f23d3876bd61e5ca30e9adfcd5518: leveldb: not found
I0416 10:59:35.530003    3624 table.go:417] Bonding cd426241128ff724: known=fals
e, fails=0 age=405773h29m35.5300032s
I0416 10:59:35.522002    3624 table.go:417] Bonding 5505cc2ccfa8d048: known=fals
e, fails=0 age=405773h29m35.5220027s
I0416 10:59:35.516002    3624 database.go:183] failed to retrieve node cf5d77175
b03b615660c25d7d2d3fcbeb52f7408bebfc924195520d094a6758e717205fb10f12cf586b4e2d60
828d26d79d4ac15321c5d2e892097b24bfa05ae: leveldb: not found
I0416 10:59:35.533003    3624 table.go:417] Bonding cf5d77175b03b615: known=fals
e, fails=0 age=405773h29m35.5330033s
I0416 10:59:35.534003    3624 udp.go:429] >>> 50.59.0.34:55007 discover.ping
I0416 10:59:35.522002    3624 database.go:183] failed to retrieve node a68e973c1
fc12de23f38cc80547092d0e0d65ab3569d8b957a0c593fafc2f81221da7fb53ceb6775ef01047d6
dc274a2bdc1f4df650ab5cfcdbdf2c6e315936a: leveldb: not found
I0416 10:59:35.536003    3624 table.go:417] Bonding a68e973c1fc12de2: known=fals
e, fails=0 age=405773h29m35.5360035s
I0416 10:59:35.516002    3624 database.go:183] failed to retrieve node 51a3cec2e
6b687125fd21b6d78a124e5d79307fd66d8c9c139b6f11870c58282142c6e4b32f2de769bc3e8a25
8f6b5d6331ff84980ed0f0c79385139e8826601: leveldb: not found
I0416 10:59:35.537003    3624 table.go:417] Bonding 51a3cec2e6b68712: known=fals
e, fails=0 age=405773h29m35.5370036s
I0416 10:59:35.526002    3624 udp.go:429] >>> 85.203.21.18:30303 discover.ping
I0416 10:59:35.539003    3624 udp.go:429] >>> 166.176.120.58:46874 discover.ping

I0416 10:59:35.530003    3624 udp.go:429] >>> 61.177.201.36:15222 discover.ping
I0416 10:59:35.522002    3624 database.go:183] failed to retrieve node 971fe7aaf
d1853d6de9e66a66c45322e6e27dbd20a630b09bd363b4270c28bcbf12af1a9c401252d5787cf871
671fb3bc33f1dced120f3f3c707170191a38836: leveldb: not found
I0416 10:59:35.540003    3624 table.go:417] Bonding 971fe7aafd1853d6: known=fals
e, fails=0 age=405773h29m35.5400037s
I0416 10:59:35.533003    3624 udp.go:429] >>> 213.192.19.26:30303 discover.ping
I0416 10:59:35.535003    3624 udp.go:429] >>> 129.31.142.4:30303 discover.ping
I0416 10:59:35.538003    3624 udp.go:429] >>> 78.46.49.102:30304 discover.ping
I0416 10:59:35.518002    3624 udp.go:429] >>> 75.13.130.219:30303 discover.ping
I0416 10:59:35.526002    3624 udp.go:429] >>> 78.46.49.102:30304 discover.ping
I0416 10:59:35.540003    3624 udp.go:429] >>> 78.46.49.102:30304 discover.ping
I0416 10:59:35.565005    3624 nat.go:105] deleting port mapping: udp 30303 -> 30
303 (ethereum discovery) using UPNP IGDv1-IP1
I0416 10:59:35.565005    3624 table.go:242] Bumping failures for 30baf8759dba3a6
f: 1
I0416 10:59:35.566005    3624 udp.go:429] >>> 24.100.189.129:30303 discover.find
node
I0416 10:59:35.567005    3624 udp.go:431] UDP send failed: write udp 0.0.0.0:303
03->24.100.189.129:30303: use of closed network connection
I0416 10:59:35.567005    3624 table.go:242] Bumping failures for a221a940dec3e45
e: 1
I0416 10:59:35.568005    3624 udp.go:429] >>> 14.3.81.90:30303 discover.findnode

I0416 10:59:35.568005    3624 udp.go:431] UDP send failed: write udp 0.0.0.0:303
03->14.3.81.90:30303: use of closed network connection
I0416 10:59:35.569005    3624 table.go:242] Bumping failures for 983d9bcb9b24229
0: 1
I0416 10:59:35.570005    3624 udp.go:429] >>> 104.208.33.128:1025 discover.findn
ode
I0416 10:59:35.571005    3624 udp.go:431] UDP send failed: write udp 0.0.0.0:303
03->104.208.33.128:1025: use of closed network connection
I0416 10:59:35.572005    3624 table.go:242] Bumping failures for f8015c35301b4dc
a: 1
I0416 10:59:35.573005    3624 udp.go:429] >>> 45.32.238.163:42786 discover.findn
ode
I0416 10:59:35.574005    3624 udp.go:431] UDP send failed: write udp 0.0.0.0:303
03->45.32.238.163:42786: use of closed network connection
I0416 10:59:35.574005    3624 table.go:242] Bumping failures for 599a6e37217a66e
4: 1
I0416 10:59:35.576005    3624 udp.go:429] >>> 37.59.121.19:30303 discover.findno
de
I0416 10:59:35.576005    3624 udp.go:431] UDP send failed: write udp 0.0.0.0:303
03->37.59.121.19:30303: use of closed network connection
I0416 10:59:35.577005    3624 table.go:242] Bumping failures for 73a2eec7b0ee2c2
6: 1
I0416 10:59:35.579006    3624 udp.go:429] >>> 70.70.230.160:30303 discover.findn
ode
I0416 10:59:35.579006    3624 udp.go:431] UDP send failed: write udp 0.0.0.0:303
03->70.70.230.160:30303: use of closed network connection
I0416 10:59:35.580006    3624 table.go:242] Bumping failures for de8c06ca41b44a7
1: 1
I0416 10:59:35.582006    3624 table.go:242] Bumping failures for 8890b1893650e92
4: 1
I0416 10:59:35.583006    3624 udp.go:429] >>> 52.62.76.200:30303 discover.findno
de
I0416 10:59:35.586006    3624 udp.go:431] UDP send failed: write udp 0.0.0.0:303
03->52.62.76.200:30303: use of closed network connection
I0416 10:59:35.586006    3624 table.go:242] Bumping failures for 219a8e05cc19ad0
2: 1
I0416 10:59:35.586006    3624 peer.go:180] Peer 04f44040c32b0c8d 78.217.180.48:3
0303: locally requested disconnect: Client quitting
I0416 10:59:35.586006    3624 udp.go:480] Read error: read udp 0.0.0.0:30303: us
e of closed network connection
I0416 10:59:35.585006    3624 udp.go:429] >>> 212.47.235.114:30303 discover.find
node
I0416 10:59:35.589006    3624 udp.go:431] UDP send failed: write udp 0.0.0.0:303
03->212.47.235.114:30303: use of closed network connection
I0416 10:59:35.589006    3624 table.go:242] Bumping failures for b7cb9468bb1081e
4: 1
I0416 10:59:35.589006    3624 handler.go:244] Peer 04f44040c32b0c8d [eth/63]: me
ssage handling failed: EOF
I0416 10:59:35.591006    3624 handler.go:163] Removing peer 04f44040c32b0c8d
I0416 10:59:35.591006    3624 downloader.go:240] Unregistering peer 04f44040c32b
0c8d
I0416 10:59:35.564005    3624 server.go:513] ignoring 9 pending tasks at spindow
n

**Comment by jesse-git** [comment]
+1 same symptoms and errors in my log
