### ISSUE TITLE
Can't estimate gas for an ETH transfer from a particular EOA

### ISSUE THREAD

**Issue by mdeliadi** [ethereum/go-ethereum#22997]
#### System information

Geth version: 1.10.3-stable
OS & Version: Debian GNU/Linux 9.6 (stretch)

#### Expected behaviour

Receive a gas estimation for an ETH transfer between two EOAs.

#### Actual behaviour

Unable to get any gas estimation for a transfer between two EOA; Every attempt ends in "err: insufficient funds for transfer: address [from] (supplied gas ...)". The "from" address contains more than 9 ETH and We get this error even trying to estimate a transfer of one single wei. No matter the value, We always get this error with this particular "from" address. Changing "to" address does not solve the error. Any other ETH transfer estimation, with different "from" addresses, works as intended.

#### Steps to reproduce the behaviour

Call web3.eth.estimateGas using the following payload:

```
{
  "from": "redacted",
  "to": "redacted",
  "value": "1000000000000000000",
  "data": "0x"
}
```
I'm sorry that I'm not able to publicly provide the "from" and "to" addresses, but I can do it privately, so please let me know if it can help! Thanks.

**Comment by holiman** [comment]
The node which you are running this estimation against -- is it in sync? 
Did you try it against a public and synced backend, e.g. infura?

**Comment by mdeliadi** [comment]
Hello @holiman ! We tried this estimation against two nodes, both in sync, and got the same error. We also tried against a public and synced backend, Infura, and there the estimation worked!

**Comment by holiman** [comment]
What does the `eth.getBalance(...)` return on the node for the address in question? Does it return something non-zero?

**Comment by mdeliadi** [comment]
@holiman eth.getBalance(...) returns something non-zero and it's aligned to the balance shown in Etherscan. In addition, I can see that the owner removed almost eveything from its wallet. I've re-tried the gas estimation and now it's working! I suspect that whatever caused the issue got fixed after the successful transfer!

**Comment by MariusVanDerWijden** [comment]
How old was the from address? E.g. did it recently receive the funds or was it funded for a longer period of time?

**Comment by mdeliadi** [comment]
Hello @MariusVanDerWijden ! The oldest transaction in the wallet is an ETH inbound transfer dated 2018-06-05. From Etherscan I can see it operated until 2021-05-23 so the issue appeared in between this date and 2021-06-04, when the owner was able to move them funds again.

**Comment by karalabe** [comment]
Unfortunately there's not much we can go on here. There isn't really anything that could have caused this to "not work" for 10 days and then start working again. Our best hunch is that the node might not have been in sync yet. Still, without any other infromation, we'll have to close this.
