### ISSUE TITLE
Change from --rpc to --http

### ISSUE THREAD

**Issue by Joter271** [ethereum/go-ethereum#22990]
Geth – Maroon Sea (v1.10.3)
Windows Server 2016

I am unable to attach to geth listening port.

Starting Geth http deamon:
geth --http --http.port 7999 --http.addr 127.0.0.1 --http.api eth,net,personal --http.corsdomain '*' --maxpeers "100"

Trying to attach to process on same machine:
geth attach http://127.0.0.1:7999

Can't attach. Nor there is listening port 7999 active.

**Comment by ligi** [comment]
Can you please provide some logs?

**Comment by Joter271** [comment]
Server restart helped. Now it binds.
