### ISSUE TITLE
mismatching Berlin fork block in database

### ISSUE THREAD

**Issue by darksh1ne** [ethereum/go-ethereum#23004]
I had a geth node of version 1.9.25 run in light mode synced up to the block #12535738. Then upgraded it to 1.10.3 and re-run on May, 30th. Since then geth stuck with the message:
`Rewinding chain to upgrade configuration err="mismatching Berlin fork block in database (have <nil>, want 12244000, rewindto 12243999)"`

1 week passed, no new messages have been printed. Only ~/.ethereum/geth/les.client/000001.log slowly grows by ~0.5MB per day.

Are this message and the delay expected behavior? When sould I expect the end of chain rewind?

OS: Linux
geth: 1.10.3
go: 1.16.4
disk: HDD Toshiba DT01ACA200
command line: `geth --syncmode=light --cache=512`

**Comment by MariusVanDerWijden** [comment]
Weird. It seems that LES does not migrate the genesis configuration properly between forks. We should investigate that. For now it would be best for you to nuke (maybe rename if we need it to investigate in the future) your data directory and sync from scratch

**Comment by rjl493456442** [comment]
It's super funny that you can sync the light client until `12535738` without enabling the fork. So here are two issues:

- Why you can sync up to the `12535738` in light mode
- After the head reset, it should come back to the right chain, but looks like it's not

I will try to repro.

**Comment by holiman** [comment]
Since light clients don't actually execute the blocks (process transactions), and the Berlin fork did not change the header format (or difficulty calculation), the light client which is not berlin-configured _can_ actually  function fine post-berlin (the same won't be true for London).

**Comment by karalabe** [comment]
Syncing up 1.9.25 to an arbitrary Berlin block should work fine because there's nothing in the header that would state Berlin-ness, so that's expected, if perhaps unintended.

Seems that the fault here is that resetting the chain doesn't work in LES.

**Comment by karalabe** [comment]
One interesting corner case might be if the CHT is *after* a particular fork block and we try to rewind before it. Unsure if that's handled or what happens then.
