### ISSUE TITLE
return constructor response in abigen

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#23015]
## background

hi, here is a very smart and generic multicall contract ([source](https://github.com/indexed-finance/multicall/blob/master/contracts/MultiCall.sol))

```sol
contract MultiCall {
  constructor(
    address[] memory targets,
    bytes[] memory datas
  ) public {
    uint256 len = targets.length;
    require(datas.length == len, "Error: Array lengths do not match.");

    bytes[] memory returnDatas = new bytes[](len);

    for (uint256 i = 0; i < len; i++) {
      address target = targets[i];
      bytes memory data = datas[i];
      (bool success, bytes memory returnData) = target.call(data);
      if (!success) {
        returnDatas[i] = bytes("");
      } else {
        returnDatas[i] = returnData;
      }
    }
    bytes memory data = abi.encode(block.number, returnDatas);
    assembly { return(add(data, 32), data) }
  }
}
```

The idea behind it is to call the constructor to query chain data without any fee. It's flexible so I like it.

Here is the usage by javascript https://github.com/indexed-finance/multicall#general-usage

But when it comes to go,  I don't know how to call it to get the same effect.

## question

I use abigen to get it's go binding code

```go
func DeployMulticall(auth *bind.TransactOpts, backend bind.ContractBackend, targets []common.Address, datas [][]byte) (common.Address, *types.Transaction, *Multicall, error) {
	parsed, err := abi.JSON(strings.NewReader(MulticallABI))
	if err != nil {
		return common.Address{}, nil, nil, err
	}

	address, tx, contract, err := bind.DeployContract(auth, parsed, common.FromHex(MulticallBin), backend, targets, datas)
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	return address, tx, &Multicall{MulticallCaller: MulticallCaller{contract: contract}, MulticallTransactor: MulticallTransactor{contract: contract}, MulticallFilterer: MulticallFilterer{contract: contract}}, nil
}
```

1. The go binding contract doesn't return the constructor's response, so I can't get the multicall result.

2. The first param in the go binding code is `auth *bind.TransactOpts` means that I have to use an address with some eth balance to deploy it, but if I just want to simulate the call, I also need to provide it.

**Comment by huahuayu** [comment]
I think I can use this:

https://github.com/ethereum/go-ethereum/blob/c503f98f6d5e80e079c1d8a3601d188af2a899da/ethclient/ethclient.go#L475

**Comment by MariusVanDerWijden** [comment]
Constructors do not return anything in solidity. Due to the assembly used in the contract you can force the constructor to return something. We have **no** idea what that something is (as we can not parse it from the contracts abi), thus we can not decode the response. Yes you can use `CallContract` (or `Transact` in the auto generated bindings) to invoke your contract with arbitrary code and parse the result. 

This is such a niche use case (wanting to get data from the constructor) that I don't think we should support it in abigen.
