### ISSUE TITLE
Websocket with basic auth ? Alternative to Dial ?

### ISSUE THREAD

**Issue by iangregsondev** [ethereum/go-ethereum#23017]
Hi, can anybody tell me what I am doing wrong with connecting to websockets using basic auth ? I have managed to do it via RPC and embedding the user:password in the URL but I don't think is support on protocol ws://

So looking through the code I guessed I could do something like the following but I get an error

```
    rpcClient, err := rpc.Dial("ws://geth.mydomain.network:80/ws/")
    rpcClient.SetHeader("Authorization", "Basic ABCDEFGHJJJJJJ==" )

    if err != nil {
        log.Fatal(err)
    }

    client := ethclient.NewClient(rpcClient)
    if err != nil {
        log.Fatal(err)
    }
```

I get an error on SetHeader like so

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x435b546]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/rpc.(*Client).SetHeader(0x0, 0x46bb387, 0xd, 0x46c76c9, 0x1e)
        /Users/ian/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/ethereum/go-ethereum@v1.10.3/rpc/client.go:267 +0x26
main.main()
        /Users/ian/Development/Personal/coininfo/go/test/main.go:18 +0xed
exit status 2

I am obviously not doing it right :frowning:

Can anyone lend a hand ?

I did the above because ethClient doesn't seem to accept headers or anything - so i can't pass in basic auth. I am a little lost.
This seems to be the line in the go-ethereum code base that it's indicating.

    if !c.isHTTP {
        return
    }

I think I am missing a step or I have done it completely wrong.

I could not find any examples anywhere - are there any ?
Just to make my question completely. I have nginx in front of the geth node. Using the url for 
http://user:password@somedomain.com/rpc

works great. but this is not websockets.

Thanks in advance.

**Comment by iangregsondev** [comment]
I got it working now :-) By using the URL

**Comment by krasi-georgiev** [comment]
Can we re-open this as setting custom headers for websockets would solve my issue where I am calling an endpoint that requires some special Auth headers.
