### ISSUE TITLE
geth node returned lower gas limit

### ISSUE THREAD

**Issue by arshad-binary** [ethereum/go-ethereum#23014]
Version : geth-linux-amd64-1.10.3-991384a7
For ERC20 tokens, to be specific USDC transaction i calculate the gas limit using `eth_estimateGas`. I have observed that sometimes the gas limit i set in the transaction is not enough that leads to transaction failed due to `out of gas` issue. 
Can someone help me to understand is `eth_estimateGas` reliable ?
one of sample txn failed is https://etherscan.io/tx/0x1840a8c649f5c9abdfab868985296253c2100055a4719d2932a47cb537ac52a3

TIA

**Comment by MariusVanDerWijden** [comment]
So the gas estimation is highly dependent on the current state of the contract. Thus if a prior transaction changes the state, the gas estimation might not be accurate anymore. You can see for example that this transaction https://etherscan.io/tx/0x765413b691aba47927a41db1cce138c5e2aa7396e562764cc4cbb6d828cc02ed used more than 66.000 gas for a transfer, while others use ~33.000.
'eth_estimateGas' uses a binary search to find the lowest gas limit that successfully executes the transaction, if something un the contract changes between execution and estimation, then the result will be unreliable.

**Comment by arshad-binary** [comment]
@MariusVanDerWijden thanks for your quick response. 
So what I can see is this is something managed at the blockchain/network end. What you suggest or what is the best way to handle such situations. Any suggestion will be much helpful.

TIA.
