### ISSUE TITLE
How install go-ethereum-1.3.5 - no executable

### ISSUE THREAD

**Issue by paulbush-gapview** [ethereum/go-ethereum#2302]
Have downloaded source code as zip. Where is the executable to install? Previously used Ethereum-win64-latest

**Comment by fjl** [comment]
Executables are linked from https://github.com/ethereum/go-ethereum/releases/tag/v1.3.5.
For Win64, use https://github.com/ethereum/go-ethereum/releases/download/v1.3.5/Geth-Win64-20160303142914-1.3.5-34b622a.zip.

**Comment by paulbush-gapview** [comment]
Felix - thanks. Doesn't quite answer question though. Have downloaded geth and run which connects PC as node to block-chain.

Want to install homestead source code so that  I can mine ETH. Have downloaded zip file which compared to frontier is written in Go. Have installed Go, but what are the go commands to compile homestead sourcecode?

Cheers

**Comment by fjl** [comment]
If you want to compile it yourself, you need to follow the [instructions from the wiki](https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows).
