### ISSUE TITLE
Error! Unable to generate Contract ByteCode and ABI

### ISSUE THREAD

**Issue by Tech4Money** [ethereum/go-ethereum#23021]
I deployed about a week ago and I forgot to verify went back to get a text file to verify that I can't find it I've been trying to figure out how to re-create the contract I don't know what I'm doing wrong and I really hope somebody can help

contract  0x9a877792c4c9fb2278ec4e11289217a9a4567378
 
Compiler debug log:
 Error! Unable to generate Contract ByteCode and ABI
 Found the following ContractName(s) in source code : Address, Context, IERC20, IUniswapV2Factory, IUniswapV2Pair, IUniswapV2Router01, IUniswapV2Router02, Ownable, SRG, SafeMath
 But we were unable to locate a matching bytecode (err_code_2)  0x9a877792c4c9fb2278ec4e11289217a9a4567378

**Comment by ligi** [comment]
Please provide more information - what command are you invoking with which parameters when you get this error?

**Comment by karalabe** [comment]
This seems an error message from etherscan. Can't help you with that.

**Comment by Tech4Money** [comment]
not its a message for bscscan.

**Comment by Tech4Money** [comment]
> Please provide more information - what command are you invoking with which parameters when you get this error?

what information do you need?

**Comment by Tech4Money** [comment]
> This seems an error message from etherscan. Can't help you with that.

its a message from https://bscscan.com/

**Comment by giobulia** [comment]
Hi, do you resolve this issue? I need help also. Already trying to fix it more then 5 hours and I can't. Please share me solution if it's possible. Thanks

**Comment by MariusVanDerWijden** [comment]
You need to contact bscscan with that. This is not a geth issue
