### ISSUE TITLE
convert balanceOf big.int to simple format

### ISSUE THREAD

**Issue by dfqroot** [ethereum/go-ethereum#23024]
Next code prints out the usdt balance:

```
func tetherAmount(addrHex string) {
    conn, err := ethclient.Dial("https://mainnet.infura.io/v3/[api_here]")
    if err != nil {
        log.Fatal("Whoops something went wrong!", err)
    }

    contract, err := NewTetherToken(common.HexToAddress("0xdAC17F958D2ee523a2206206994597C13D831ec7"), conn)
    if err != nil {
        log.Fatalf("Failed to initiate contract: %v", err)
    }

    // this func return *big.Int, error
    amount, _ := contract.BalanceOf(&bind.CallOpts{}, common.HexToAddress(addrHex))
    fmt.Println("amount:", amount)
}
```
result: ```amount: 917750889```

Real balance of this randomly taken address is 917.750889 USDT. So how can I convert gotten result (917750889) to simple format (usdt) ?

**Comment by MariusVanDerWijden** [comment]
You need to query how many decimal places the token has (its public in the contract `uint public decimals`) and shift the result (`amount`) by the decimal places. (divide by `1 lsh decimals`).
Please use the stackexchange for questions like this in the future: https://ethereum.stackexchange.com/
