### ISSUE TITLE
the easiest way get current evm for eth_call

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#23031]
hi, I want to execute below code in my application, the `msg` and `gp` param is easy to settle, but I don't know how to get the current `evm` , so I can do `eth_call`  in `evm`

```go
gp := new(core.GasPool).AddGas(math.MaxUint64)
res, gas, failed, err := core.ApplyMessage(evm, msg, gp)
if err := vmError(); err != nil {
    return nil, 0, false, err
}
return res, gas, failed, err
```

I have searched the code base for usage and testcase, like this

```go
	// Prepare the EVM.
	txContext := core.NewEVMTxContext(msg)
	context := core.NewEVMBlockContext(block.Header(), nil, &t.json.Env.Coinbase)
	context.GetHash = vmTestBlockHash
	context.BaseFee = baseFee
	evm := vm.NewEVM(context, txContext, statedb, config, vmconfig)

	// Execute the message.
	snapshot := statedb.Snapshot()
	gaspool := new(core.GasPool)
	gaspool.AddGas(block.GasLimit())
	if _, err := core.ApplyMessage(evm, msg, gaspool); err != nil {
		statedb.RevertToSnapshot(snapshot)
	}
```

but it's a little bit complex, can it be easier？

**Comment by huahuayu** [comment]
I read the issue history for keyword `eth_call`, didn't find an answer, I think you are experts on this topic, could you please take a look, thx @karalabe @rjl493456442

**Comment by karalabe** [comment]
If you want to do it without a blockchain object, you'll need to create it yourself via `vm.NewEVM`. The parameters are fairly straightforward I think.
