### ISSUE TITLE
JSONRPC eth_getBlockByHash returns block/acct/tx hashes that are all lowercase

### ISSUE THREAD

**Issue by admazzola** [ethereum/go-ethereum#2303]
Shouldn't the block, account, and tx JSON data all come through with the proper case and not just all be lowercase? This also reduces entropy which is bad.

**Comment by fjl** [comment]
What is the proper case for a hex string?

**Comment by admazzola** [comment]
Well some numbers, some uppercase characters, and some lowercase characters.  I think the JSON RPC calls are returning just numbers and lowercase characters for the hashes of blocks, tx, and accounts.

**Comment by admazzola** [comment]
For example, gav woods wallet is at address 0xbF35fAA9C265bAf50C9CFF8c389C363B05753275... no ?

**Comment by fjl** [comment]
OK, now I get what you are referring to. The mixed-case checksum encoding proposed in https://github.com/ethereum/EIPs/issues/55 is meant for account addresses only. It doesn't
provide any benefit for block/tx hashes IMHO. What would be the benefit to you, as a user of
the JSON-RPC API?

**Comment by admazzola** [comment]
Oh. Well I'm making a website using cached data from these calls and was worried that having nob mixed case hashes would be an issue. Looks like it isn't actually an issue and though.  It's confusing because etherchain.org uses mixed case but no big deal.  Thanks
