### ISSUE TITLE
Implement P2P WatchDog

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#23030]
# Rationale

The situation can arise that you are connected to nodes but you do not get any block announcements. E.g. all nodes you are connected to are syncing or they are all bad nodes.

# Implementation

We should check if we got block announcements in a TBD interval and if we did not we should kick random nodes to make room for better ones.

**Comment by padrone1225** [comment]
What techniques are used to expel nodes?

**Comment by lightclient** [comment]
Block announcements are no longer made over devp2p after the merge.
