### ISSUE TITLE
Geth crash during synchronization

### ISSUE THREAD

**Issue by Atrides** [ethereum/go-ethereum#2305]
Geth crash during synchronization.
Geth/v1.3.5/linux/go1.5.1
The whole error report here http://pastebin.com/YyUExG81

**Comment by fjl** [comment]
The interesting part of the trace is

```text
panic: interface conversion: interface {} is nil, not *types.Block

goroutine 67 [running]:
github.com/ethereum/go-ethereum/core.(*BlockChain).procFutureBlocks(0xc8200d4280)
        /build/ethereum-efb52a/ethereum-1.3.5+70trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/blockchain.go:697 +0x27b
github.com/ethereum/go-ethereum/core.(*BlockChain).update(0xc8200d4280)
        /build/ethereum-efb52a/ethereum-1.3.5+70trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/blockchain.go:1372 +0xbb
created by github.com/ethereum/go-ethereum/core.NewBlockChain
        /build/ethereum-efb52a/ethereum-1.3.5+70trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/blockchain.go:174 +0x1484
```

**Comment by obscuren** [comment]
I've looked in this issue and I can see one scenario where this might occur (and will occur more often on slow or heavy loaded machines).

At the moment there's no lock on the `futureBlock` `set.Set` which can result in future blocks being removed from the future block queue while iterating the set using `set.Keys`. This may happen when a block is received, placed in the future queue, future queue ticks, receive the same block and process it and remove it all together from the queue while the previous operation still ticks.

This can easily be solved by locking the future block queue (the `set.Set` itself is thread safe but the way we're using it this may still result in a race).
