### ISSUE TITLE
How to add a custom opcode in go-ethereum which support running an executable from the local ethereum node?

### ISSUE THREAD

**Issue by ck-chaudhary** [ethereum/go-ethereum#23064]
I just wanted to run an executable from a local ethereum node. Is there any methodology for doing this in go-ethereum?
How can adding a custom opcode help in this regard?
Also, which other existing opcode should i take help from to proceed?

**Comment by karalabe** [comment]
There is no functionality to run an external process. That would be both a security vulnerability as well as would be non-deterministic (multiple nodes end up with different results). It doesn't fit into the Ethereum design space.
