### ISSUE TITLE
geth sync really really slow 

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#2306]
I am downloading eth chain with geth for 24 hours now and it stuck at ~ 700 000 on Ubuntu (with --fast).
Windows still download new blocks and currently at ~1037000 (without --fast)

it takes about 3 minutes to process 256 blocks
new chunk of 256 blocks imported each 10 - 30 minutes

**Comment by karalabe** [comment]
HDD or SSD? Try bumping the cache to `--cache=512`. It should help significantly.

**Comment by winsvega** [comment]
HDD but pretty new and fast one.  It was not an issue before

**Comment by fjl** [comment]
See #2216
