### ISSUE TITLE
ld: library not found for -lpthread

### ISSUE THREAD

**Issue by shiziwen** [ethereum/go-ethereum#23067]
When I try to build geth use "make geth", I found the below errors:

# runtime/cgo
ld: library not found for -lpthread
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [geth] Error 2

$ which g++
/usr/bin/g++
MacBook-Pro-2:~ tron$ which g++-10
/usr/local/bin/g++-10

**Comment by karalabe** [comment]
You probably need to install the C++ development packages for your OS. `pthreads` is the standard multi-threading library used by linux and macos.
