### ISSUE TITLE
how can i get the internal txlist without etherscan-api??

### ISSUE THREAD

**Issue by lxl518000** [ethereum/go-ethereum#23071]
I want to retrieve the internal transactions of specified tx, the result should be same as "https://api-ropsten.etherscan.io/api?module=account&action=txlistinternal" api request reuslt.

So I want to know how to do it. There are anyone can give me some example golang code? Thanks very much.

how can i get the internal txlist without ethersca-api??

**Comment by alysak6075** [comment]
look up debug_traceTransaction. non archive node keeps last 128 blocks only. Archive keeps all. then use any type of connection to get the internal TXs and parse them. Use curl or web3.

**Comment by karalabe** [comment]
You can specify `{tracer: 'callTracer'}` as a second option to traceTransaction
