### ISSUE TITLE
Download page does not load in Tor browser

### ISSUE THREAD

**Issue by the-metalworker** [ethereum/go-ethereum#23072]
#### System information

Tor Browser 10.0.17
Linux

#### Expected behaviour

I expect the downloads page to load. https://geth.ethereum.org/downloads/

#### Actual behaviour

Error pops up: Failed to load latest release!

Retrieving package from release server... spins loading in the background. 

This error occurred even when I allowed Javascript and reloaded the page (though I would prefer it work on Tor without having to allow Javascript).

**Comment by karalabe** [comment]
Just tried it in Brave + Private Browsing with Tor. Worked for me.

Javascript is required as we're pulling in a single list of downloads from Azure and sorting them into tables client side. You might want to check your network tab in your browser's debug console. The download list is about 1MB in sice, so depending on your Tor exit node, perhaps it's sometimes a bit slower. Still, 1MB shouldn't be a problem.

**Comment by the-metalworker** [comment]
@karalabe it does work for me too now. thanks
