### ISSUE TITLE
--snapshot=false is broken in 1.10.4-stable?

### ISSUE THREAD

**Issue by ryny24** [ethereum/go-ethereum#23075]
I run several geth nodes on Raspberry PI (8GB). It is the only thing running on the Pi, but I find that system resources are MUCH better with snapshot disabled. So, I run the the option --snapshot=false.   I just upgraded today to 1.10.4, and it appears this option is being ignored. I now have the "Aborting/Resuming state snapshot generation" in the log.

I don't see in the release notes that this was changed. Am I missing something?

Thank you.

**Comment by PcDeaDZ** [comment]
Have the same issue.

**Comment by ryny24** [comment]
I'm also getting errors

`INFO [06-20|17:47:47.226] Skip duplicated bad block                number=12,673,628 hash=320a68..56bba0
ERROR[06-20|17:47:47.284]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 728000
0 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: <nil>, Engine: ethash}

Number: 12673628
Hash: 0x320a68fd36bbbb0620599d8f9bed148e2aa37d62c92fb5eb416121c7ff56bba0
         0: cumulative: 275486 gas: 275486 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x24c9716dca2d9127e357528faff91c2052656b59f75311c2781d
920de4c01732 logs: [0x400a300e70 0x400a300f20 0x400a300fd0 0x400a301130 0x400a3011e0 0x400a301290 0x400a3013f0 0x400a3014a0 0x400a301550 0x400a3016b0 0x400a301760 0
x400a301810 0x400a301970] bloom: 00200000000000000000000080000200000000000000000000010000000000080008000000000000000000000000000002000000080000000000000000200000000
04000000000000000000800000020000200000040000000000000000000400000000000000000000000000000000000000000000004100000401000000000000000000000010000400000000000000000000
00000000800000040000000000600000000000000000000000000000000000000000000000000000000000000000000020000000000000040000008000000000000000010000000020000200000102000000
00000000000000000000000000000000000200000000001000000 state:`

**Comment by ryny24** [comment]
I'm also getting these error messages flooding my LOG file. I shortened it because it's very long (repeating) but it keeps recurring.

```
WARN [06-20|19:31:51.273] Synchronisation failed, dropping peer    peer=66d65ad07a81f86a3d66aad42cae4668a6c03f30f69f5c9ccab454506eccaa51 err="retrieved hash chain i
s invalid: invalid merkle root (remote: 551fd3fedb0dad82a910e1a0a34ca28a17c57b408267b90f8fe7c29c97006b58 local: 4a3d51243edc3437a9006d433d18f5788b71781154be59736ffc
cadee64afbea)"
WARN [06-20|19:31:51.274] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [06-20|19:31:52.284] Generating state snapshot                root=b903d7..82c50b in=008f65..483efb at=23f5e7..b20e56 accounts=302,939 slots=92,044,386 storage
=7.92GiB elapsed=1h36m14.924s
INFO [06-20|19:31:55.137] Skip duplicated bad block                number=12,674,202 hash=de35c0..7857bd
ERROR[06-20|19:31:55.380]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 728000
0 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: <nil>, Engine: ethash}

Number: 12674202
Hash: 0xde35c08cab97e831ba6ba3040d46cb35ed13336c0414ce9994aee8a7457857bd
         0: cumulative: 34989 gas: 34989 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xd6489eead932de881ca1b817b236e752218438097efe036c0ab500
ba14e0c8cd logs: [0x40a11c6f20] bloom: 00000000000000000000000000001000000000000000000400000000000000000000000000000080000000000000000000000000000000000000000000000
00000000000000000004000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009400000000000000000000000000000001000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000040000000000000000020000000000000000000
00000000000000000000000000000000000000000000000000000000000 state:
..........
Error: invalid merkle root (remote: 551fd3fedb0dad82a910e1a0a34ca28a17c57b408267b90f8fe7c29c97006b58 local: 4a3d51243edc3437a9006d433d18f5788b71781154be59736ffccadee64afbea)
##############################```

I went back to 1.10.3, resources are back to normal and the errors are gone.

**Comment by karalabe** [comment]
Hmm, my guess is that the switch to `--syncmode=snap` by default is also forcing snapshots. Still, snapshots do make a huge difference is avoiding a DoS attack, so if you can afford a bit of downtime, I'd recommend resyncing with snap sync. That will net you an almost perfect snapshot that can be fixed very quickly afterwards. If you keep your `ancient` folder inside `chaindata`, then you won't even download the blocks, only the state (around 30GB).

**Comment by karalabe** [comment]
The invalid merkle root is more worrying. Did you node crash during snapshot gneration? Did you turn it off non-gracefully?

**Comment by karalabe** [comment]
Just FYI, `--snapshot=false` will be removed in the future completely, so it's better to try and not rely on it sooner rather than later.

**Comment by ryny24** [comment]
> The invalid merkle root is more worrying. Did you node crash during snapshot gneration? Did you turn it off non-gracefully?

I always turn it off gracefully. systemd has a 300 second wait. I always confirm "Blockchain stopped". It runs for about an hour before those messages start flooding the logs. I'm back to 1.10.3 and it's running fine again.

**Comment by easeev** [comment]
Can we please not break it? We use `--snapshot=false` for archive nodes that sync better this way and other Geth forks as well

**Comment by yflinn** [comment]
Moving forward, how should I turn off snapshotting given `--snapshot=false` has been broken and will be deprecated in the future? For context, our archival nodes cannot sync unless we explicitly turn off snapshotting

**Comment by petejkim** [comment]
+1. Please preserve `--snapshot=false`, it does not make much sense/doesn't seem to work very well for archival nodes.

**Comment by begetan** [comment]
A node running with `--snapshot=false` prevents the whole network to go to the snapshot syncing completely. If you run a new node version 1.10.4 right now which relies on the snapshot sync you may see a lack of peers supporting it.

**Comment by AusIV** [comment]
Running with `--syncmode=fast` resolves this problem for me.

I believe what happened here is that at one point, `--snapshot` defaulted to false and you had to explicitly pass it to set it to true. `--syncmode` defaulted to fast, and you had to explicitly set it to snap. At that time, the assumption was that if you set `--syncmode=snap` without setting `--snapshot=true` that you had actually intended to set `--snapshot=true`.

Then `--snapshot` started defaulting to true, but `--syncmode` still defaulted to fast, so setting `--snapshot=false` worked as expected. In 1.10.4, they changed the default `--syncmode` to snap, and now the assumption that if `--syncmode` is set to snap meant you intended `--snapshot=true` violates peoples expectations, because the only way `--snapshot=false` is if somebody explicitly set it that way.

**Comment by AusIV** [comment]
> A node running with `--snapshot=false` prevents the whole network to go to the snapshot syncing completely. If you run a new node version 1.10.4 right now which relies on the snapshot sync you may see a lack of peers supporting it.

If having a few Geth operators running with `--snapshot=false` is going to prevent the network from going to snapshot syncing, other clients like Nethermind, OpenEthereum, Besu, etc. are probably going to cause even bigger problems. The network needs to have a critical mass of nodes running with `--snapshot`, but client diversity is more important for the network than snapshot sync, and to my knowledge none of the other clients have any serious plans to implement it. One Geth operator running with `--snapshot=false` is no more of a risk to the network than if they had elected to run Nethermind instead of Geth.

**Comment by ryny24** [comment]
Excellent suggestion @AusIV. `--syncmode=fast` worked for me. I'm gonna try it on my backup node for a few days, though. Thank you!

**Comment by AusIV** [comment]
Note that --syncmode=fast will no longer work, but --syncmode=full will.

**Comment by karalabe** [comment]
`fast` was replaced with `snap`. (i.e. `--syncmode=snap`)

**Comment by AusIV** [comment]
Yes, but if you want the --snapshot=false flag to work, as is the point of this thread, you must also explicitly set the --syncmode flag to something other than snap.

**Comment by raulmonge** [comment]
> 

Yeah I have the same problem, I updated my node to the 1.10.15 version and with `--syncmode snap --snapshot=false` it still start with the snapshot generation

**Comment by MariusVanDerWijden** [comment]
Closing because stale. 
Geth ignores `--snapshot=false` if the node was synced with `--syncmode=snap`. This behavior is grandfathered in and `--snapshot=false` was thought of as an emergency flag that would/will be removed in the future
