### ISSUE TITLE
Expand view of command line options on geth.ethereum.org

### ISSUE THREAD

**Issue by DockBoss** [ethereum/go-ethereum#23070]
# Rationale

I have just stared using geth and I need to reference the command line options on the website a lot.
The way the page is set up you can not read the entire description for most commands. 
I know this is not super important, but it only takes one line of code and it would improve the readability of the page. 

# Implementation

Expand the with of the div that the command line options are in.

**Comment by karalabe** [comment]
Please send a fix if you know what needs to be done.

**Comment by holiman** [comment]
Seems stale, closing
