### ISSUE TITLE
`transactions.rlp` has odd permissions

### ISSUE THREAD

**Issue by nyetwurk** [ethereum/go-ethereum#23084]
#### System information

Geth version: v1.10.4
OS & Version: Linux

#### Expected behaviour

`transactions.rlp` should be mode 0644 or 0600

#### Actual behaviour

`transactions.rlp` is 0755

#### Steps to reproduce the behaviour

```bash
$ ls -al geth/transactions.rlp
-rwxr-xr-x 1 geth geth 601 Jun 21 18:21 geth/transactions.rlp

**Comment by karalabe** [comment]
Yup, that's indeed a better set of permissions. Want to open a PR to fix it? 

https://github.com/ethereum/go-ethereum/blob/master/core/tx_journal.go#L141

and

https://github.com/ethereum/go-ethereum/blob/master/core/tx_journal.go#L161
