### ISSUE TITLE
Geth archive node extremely slow syncing

### ISSUE THREAD

**Issue by noahc66260** [ethereum/go-ethereum#23085]
I'm syncing a geth archival node and the syncing is becoming progressively slower. Current sync status is block ~11.7M/12.6M and syncing 1 block every 2 seconds or 60-100 transactions per second. I have been syncing for 9 weeks so far. At the current rate of progress it will take another 3 weeks, but I am concerned that the sync could become slow enough to never reach the tip.

Command I'm running is geth --syncmode full --gcmode archive --txlookuplimit=0 --cache.preimages --datadir /datadrive --cache 128000 --snapshot=false

I'm running my node on Azure with a Standard E16as_v4 (16 vcpus, 128 GiB memory) instance and 16TB premium SSD storage attached disk. OS is Linux (ubuntu 18.04).

I am struggling to understand what the bottleneck is. I have tried connecting to new peers from https://etherscan.io/nodetracker, optimizing caching, running on a faster disk, and running with more RAM. The performance data I can see does not suggest any particular problem (CPU, RAM, IOPS, IO bandwidth, queue depth, etc.).

**Comment by holiman** [comment]
Could you show us some logs from block processing? 
Also, we ourselves make use of the built-in metrics to figure out what the bottlenecks are, when we do benchmarks. 
Example charts: 
![Screenshot_2021-07-01 Dual Geth - Grafana](https://user-images.githubusercontent.com/142290/124095091-a6c7f980-da59-11eb-8a29-de760792cd00.png)

**Comment by noahc66260** [comment]
I used logging level 5 for the following logs: https://pastebin.com/XzkpF4hN. Is this useful or do you want me to get logs in a different way?

**Comment by JavierMNieto** [comment]
I have a similar setup as @noahc66260 and have also been experiencing extremely slow syncing now at block ~10.5M. It has been syncing for a little over 6 weeks now.

I am running on version `1.10.4-stable-aa637fd3` with these flags:
`geth --mainnet --syncmode full --gcmode archive --cache 98304 --cache.preimages --txlookuplimit 0 --snapshot=false --datadir /data/.ethereum/ --maxpeers 100 --metrics --metrics.influxdb --metrics.influxdb.endpoint "http://0.0.0.0:8086" --metrics.influxdb.username "geth" --metrics.influxdb.password "password"`

The virtual machine it is running on has 16 vCPUs, 128GB memory, and 16TB SSD on Ubuntu 20.04.2.

I followed [this ](https://ethereum.org/en/developers/tutorials/monitoring-geth-with-influxdb-and-grafana/)tutorial to monitor the node. [Here ](https://snapshot.raintank.io/dashboard/snapshot/XAeLLVIlOUMVRa7Okg3du3JWrLYqf8eH)is a snapshot of my metrics over the past few hours.

**Comment by jithin03** [comment]
Any update on this?

**Comment by JavierMNieto** [comment]
I did not make any changes to my setup and have just been waiting on it to sync. I'm open to suggestions, but I'm at block ~12.6M, so I probably won't change anything now. I've accepted the process is just going to be slow. [Here](https://snapshot.raintank.io/dashboard/snapshot/5jiENblUP5laHyrgMigO6Yx087DVxmgf?orgId=2) is an updated grafana snapshot of my system.

**Comment by jithin03** [comment]
The current block in our node is around 12.3M. It takes around 1 minute to sync a new block. Is this normal? We have updated our GETH to stay aligned with the London fork. but at this slow rate, It would take months to reach the forking block. I am running it on a K8s cluster with a premium SSD of 16TB attached. Attaching the Grafana [snapshot](https://snapshot.raintank.io/dashboard/snapshot/SIgYtW46RI4M6nXs1Hv7woCzbYlDAGTX) for reference. Suggestions to improve the performance are highly appreciated!

**Comment by JavierMNieto** [comment]
Maybe try giving it more RAM (with `--cache` in megabytes), like over 30GB which seems to be where it caps at for me no matter how much I allow it to use. 

Also, I'm not for sure on this, but maybe try messing around with the `--maxpeers` option to reduce the number of peers you're connected to, which may help in reducing how many blocks your node has to send out just while you sync. As you can see from my [metrics](https://snapshot.raintank.io/dashboard/snapshot/5jiENblUP5laHyrgMigO6Yx087DVxmgf?orgId=2), I only have around `16` peers connected at a time, and although it still isn't incredibly fast, I have been syncing faster than 1 block per minute. Good luck, and I hope those suggestions are helpful.

**Comment by jithin03** [comment]
@JavierMNieto  Can you help me with your arguments. I have the following. Geth  v1.10.6
`          - '--cache=16384'
            - '--syncmode=full'
            - '--gcmode=archive'
            - '--datadir=/data/eth'
            - '--nousb'
            - '--maxpeers=200'
`

**Comment by JavierMNieto** [comment]
I am running on version `1.10.6-stable` with these flags:
`geth --mainnet --syncmode full --gcmode archive --cache 60000 --cache.preimages --txlookuplimit 0 --snapshot=false`

**Comment by noahc66260** [comment]
I needed to use 256GB of RAM to complete the initial sync, and it took several months. The impression I got was that this was a software bottleneck and the only way to somewhat compensate was adding huge amounts of RAM.

**Comment by jithin03** [comment]
@noahc66260 Did you mean 256GB as `--cache``. What about the `--maxpeers` count?. It would be helpful if you could share the arguments you used. @JavierMNieto What change does it brings by using `--snapshot=false`. Sorry if it sounds dumb. I am a newbie here

**Comment by JavierMNieto** [comment]
@jithin03 I believe at the time when I started the syncing process, if I did not have snapshot set to false, the archive node would not sync properly or would sync slower.

**Comment by MariusVanDerWijden** [comment]
The geth archive node has not seen much love over the last years as other clients (such as erigon) emerged. A switch from leveldb to pebble (--pebble) might accelerate it a bit, but the truth is that its just not supported anymore. At some point we might even remove the functionality for the archive node from geth. I'm going to close this issue for now
