### ISSUE TITLE
eth_sendRawTransaction call error [-32000] replacement transaction underpriced

### ISSUE THREAD

**Issue by zeleniy** [ethereum/go-ethereum#23081]
When i have pending tx and trying to send another one i get the error. Why should i wait till tx commitment? Any user on my website can send a tx via user interface. But pending tx may hangs few minutes. So i can't wait if there is too much users...

**Comment by karalabe** [comment]
You can only replace an existing transaction with one that is at least 10% more expensive. This is done to avoid people spamming the network with ` wei increments.

**Comment by zeleniy** [comment]
So how it should work? Firstly i send tx. Then after some time i should check whether the tx completed or not. If not then i should replace tx. Then i should wait and check again. And it may repeat time after time. All that time i can't send any another tx. So all other users on my website should wait till only one tx will be fulfiled. It works like prehistoric single-threaded application.

So the only decision is to track nonce and txs by myself. But [nobody knows how to do it](https://github.com/ethereum/go-ethereum/issues/23023#issuecomment-864065882).

I'm tired trying to fix all that errors i encountered since decided to work with Ethereum. You have developed piece of junk!

**Comment by karalabe** [comment]
You users should have their own keys and not use one centrally managed by you. If you are using central keys, it's up to you to publish transactions with high enough fees to get them included. AFAIK Geth's suggested gas price will always get you into the next 1-2 blocks. Not really clear if you set that yourself ot whether you let Geth suggest one.

> It works like prehistoric single-threaded application.

Well, yes, if you use one key, it's one thread. That's kind of the point of not having a single key, rather letting your users use their own keys (+ security).

> But nobody knows how to do it.

You not knowing is not "nobody knows". Tracking nonces / transactions yourself means that if you have a lot of tx traffic to do, it makes sense to not just fire to Geth and forget, rather to tell Geth "publish this tx with nonce 5". And then if it doesn't get included fast enough for your use case, you can always republish a new tx with nonce 5.

> You have developed piece of junk!

$250B piece of junk FTW
