### ISSUE TITLE
remove useless code in core/state

### ISSUE THREAD

**Issue by SanJue** [ethereum/go-ethereum#23091]
I‘m learning code in the core dir,
and I found some code useless, so I raise a PR to clean them,
thanks for reviewing

**Comment by holiman** [comment]
Seems a bit unnecessary to have both a ticket and a PR, I guess just open a PR (if you haven't already) and we'll review it.

**Comment by SanJue** [comment]
> Seems a bit unnecessary to have both a ticket and a PR, I guess just open a PR (if you haven't already) and we'll review it.

thanks, get it
