### ISSUE TITLE
Tx required args for EIP-1559

### ISSUE THREAD

**Issue by charlesjhongc** [ethereum/go-ethereum#23093]
Hi, just checked out the latest implementation of EIP-1559 and found there are 2 related fields in `TransactionArgs` which is `MaxFeePerGas` and `MaxPriorityFeePerGas`. I'm wondering if `MaxFeePerGas` is a required tx arg? since if only `MaxPriorityFeePerGas` is given, `gasPrice` in evm will be zero.

```
if gasFeeCap.BitLen() > 0 || gasTipCap.BitLen() > 0 {
	gasPrice = math.BigMin(new(big.Int).Add(gasTipCap, baseFee), gasFeeCap)
}
```

https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/transaction_args.go#L214-L216

**Comment by karalabe** [comment]
That's an OR, not an AND

**Comment by karalabe** [comment]
Ah, now I get it. That part of the code is used for `eth_call`, where it's allowed to be 0 gas price.

**Comment by charlesjhongc** [comment]
That's clear now. Thank you for answering :)
