### ISSUE TITLE
rpc: Add isSynced method.

### ISSUE THREAD

**Issue by JoeGruffins** [ethereum/go-ethereum#23099]
# Rationale

### Why should this feature exist?

When contacting a node for data about the state of the chain, we want to know if the node thinks it is synced. That is, has blocks up to the highest known header of a peer(s).

Currently, all we can know is if the node is currently syncing. syncProgress will return nil before and after syncing has started, so connecting to a node, if progress is nil, we don't know which.

We have explored several options to try and determine whether syncing has started at all. One is waiting for a block to come in, and then checking syncProgress. This is sub optimal because we need to wait for some time if the chain was already synced. Another is to check for peers, and then check syncProgress if peers > 0, but there is a window between finding a peer and sync starting, or it could drop the peer before syncing, so this is racy.

### What are the use-cases?

When connecting to a node, we know if we should **expect** this node to be synced. I realize there could be blocks the node doesn't know about, but its best guess is better than mine.

# Implementation

### Do you have ideas regarding the implementation of this feature?

Check if we have any peers. Check if peer's best block matches ours. Possibly check the best block's age isn't under some time that would suggest we aren't just connected to another peer that is not synced.

### Are you willing to implement this feature?

Uhhhh. Maybe?

**Comment by ligi** [comment]
isn't `eth_syncing` what you want?

**Comment by ligi** [comment]
As this is a problem touching all clients and not just geth - I think the best place to raise this is: https://ethereum-magicians.org

**Comment by JoeGruffins** [comment]
> Maybe elaborate a bit more on your use-case: so for what do you need the information?

When connecting to a node, we know if we should expect this node to be synced.

We're adding ethereum to https://github.com/decred/dcrdex and we are currently discussing this around https://github.com/decred/dcrdex/pull/1082#discussion_r649917244

When a dex's server's operator starts the dex, we want to know if the chains it is running are synced. The reasons for this should be obvious?

Any recommendation for time's to check? When's that ice age happening again, need to watch for that? ;P

**Comment by MariusVanDerWijden** [comment]
We can not unilaterally implement this feature, I would suggest raising this issue here: https://github.com/ethereum/execution-apis

I would check if the block was within the last minute, even with ice age we should only see blocks on average every 30 seconds.

**Comment by 09306677806** [comment]
System sync must be done from scratch to work properly
