### ISSUE TITLE
Feature Request - Add an RPC endpoint to flush the local transaction queue

### ISSUE THREAD

**Issue by watersnake1** [ethereum/go-ethereum#23098]
# Rationale
Sometimes buggy external code that is interacting with a geth node causes a transaction to be improperly constructed. A common example of this is using the incorrect nonce value in the transaction. This can cause a backlog in the transaction queue of the node, where no additional transactions can be broadcast to the ETH network until the offending transaction is ‘freed’. 

## Current Solution
Currently, in order to free the transaction queue of geth and return to normal operation, one must delete the file `transactions.rlp` on the node’s server instance then restart geth. 

This is a relatively trivial operation, but cannot be done remotely unless one has access to an ssh endpoint where the node is being run, assuming it is not being run locally. In 2020 [decrypt.co](https://decrypt.co/44321/70-of-ethereum-nodes-are-hosted-on-centralized-services) reported that more than 70% of nodes are run on hosted services, so it is likely for the average operator that their node is not on a local computer. In many cases, hosted nodes only provide a URL to access geth’s JSON-RPC API, rather than providing an ssh endpoint on port 22 that one could use to modify the underlying filesystem. Without access to the filesystem, the user must contact their hosting provider’s customer support and open a ticket, which could take several hours or days to process. In a space where minutes and even seconds can be critical, it is critical that there is a way to reduce the time needed to carry out this action.

# Implementation

I suggest that there should be an endpoint in the go-ethereum JSON-RPC API that allows for flushing the transaction queue remotely. Unfortunately I am not a geth developer, so cannot offer advice on how this feature could be implemented. My aim is to raise awareness about this usecase with the hope that others have experienced the same problem. I believe this would be an extremely useful feature to have as a part of the geth client, given that most node operators do not have direct access to the filesystem that their nodes are running on, because they are purchasing access to them through a service like infura.

**Comment by karalabe** [comment]
I'm not really sure what your blocker is here.

If a transaction you've submitted is unsuitable for whatever reason, you can always submit a replacement transaction with the same nonce. You don't need to clear your local pool to do that.

Furthermore, deleting stuff from your local pool won't help if the transaction was already propagated through the network and remote nodes still keep hold of it. You'll have to submit a replacement good enough to push it out of remote pools, which essentially is the same as replacing it in your local pool.

**Comment by nyetwurk** [comment]
The issue i've seen is that if it makes it out of the local pool, and is properly broadcast, there are no issues with the txn and the (badly designed) client (which the OP refers to) does the right thing. I don't know why it would make a difference, though.

**Comment by watersnake1** [comment]
> I'm not really sure what your blocker is here.
> 
> If a transaction you've submitted is unsuitable for whatever reason, you can always submit a replacement transaction with the same nonce. You don't need to clear your local pool to do that.
In cases of simple sends this is true, but when transactions are being constructed by a node on a different network (i.e. a resource network that interfaces with Ethereum) it may not always be trivial to do this. What motivated me to make this request was that a resource network node constructs a tx, but due to a bug in the code, it fails, but when I try to rebroadcast from the resource node, the logic of the node states that it cannot do so because the transaction has already been sent. Thus an option to manually clear the queue would be extremely helpful in simplifying recovery from these types of issues because presently it is the only viable solution.
> 
> Furthermore, deleting stuff from your local pool won't help if the transaction was already propagated through the network and remote nodes still keep hold of it. You'll have to submit a replacement good enough to push it out of remote pools, which essentially is the same as replacing it in your local pool.
These transactions are malformed and are thus never broadcast. You wouldn't see them on etherscan if you searched the tx hash

**Comment by MariusVanDerWijden** [comment]
This seems like a very specific use case and feature. It is always possible to clear the local transaction cache by shutting down the node and removing the `transactions.rlp` file from the datadir. You can also replace the transaction by sending a transaction with 10% higher gas price. I don't think that this is a feature that is worthwhile to add to geth.
