### ISSUE TITLE
lvl=warn msg="Gas estimation capped by limited funds"

### ISSUE THREAD

**Issue by Scumwong** [ethereum/go-ethereum#23096]
a problem occurred yestday and the  log shows "
```
lvl=warn msg="Gas estimation capped by limited funds" original=60,000,000 balance=70,768,463,300,000,000 sent=0 gasprice=11,000,000,000 fundable=6,433,496
t=2021-06-22T17:17:19+0800 lvl=warn msg="Served eth_estimateGas"                 reqid=3523880 t=42.581034ms              err="execution reverted: unexpect"           X-Forwarded-For=nil
t=2021-06-22T17:17:19+0800 lvl=warn msg="Served eth_estimateGas"                 reqid=3523880 t=42.580073ms              err="execution reverted: unexpect"           errdata=0x08c379a000000000"
```
 at the same time Sudden increase in CPU usage。the log disappered after about 30 minitues and the CPU usage became normal

**Comment by holiman** [comment]
You tried to do a gas estimation, and the sender-account which you tried to estimate for did not have sufficient funds. 
As for `X-Forwarded-For=nil` -- wut?

**Comment by karalabe** [comment]
The warning is just highlighting that based on your account funds and specified gas price, the max gas you can buy is `xyz`, so gas estimation is capped to that amount.

I don't think CPU usage is related. You might want to gather metrics via `--metrics`, push them into an InfluxDB instance and chart them via Grafana. Then you could see if you have CPU spikes and what it might be related to. There's a dashboard json you could use at https://gist.github.com/karalabe/5b4f2639d750f8925a49cd48817370df
