### ISSUE TITLE
How to get information from the ETH node(geth) about the USDT token 

### ISSUE THREAD

**Issue by MalininDD** [ethereum/go-ethereum#23106]
A question regarding the processing of tokens in the Ethereum network(for example, USDT ERC20). When accessing the ETH node itself, I get error "not found"(with tether erc 20). Can you please explain how this can be done? 
An example of my code for accessing the node with an error:

```go
for _, tx := range block.Transactions() {
 txLiteral := tx
 go func() {
  defer wg.Done()
  var txInfo *types.Transaction
  var isPanding bool
  var err error
  txInfo, isPanding, err = ethClient.TransactionByHash(context.Background(), txLiteral.Hash())
  if err != nil {
   if err.Error() == "not found" { // If the transaction is not ETH, but another token, for example USDT ERC-20, I get this error.
    log.Error().Msg(fmt.Sprintf("%s - %s", txLiteral.Hash().String(), err.Error()))
    return
   }
   log.Error().Msg(fmt.Sprintf("%s - %s", txLiteral.Hash().String(), err.Error()))
   return
  }
  if isPanding {
   toRescan = append(toRescan, txLiteral.Hash().String())
   log.Warn().Msg("isPanding")
   return
  }
 }
}
```

**Comment by holiman** [comment]
The example code is very confusing, to me. 
- You have a block with transactions, why do you need to spin up a new routine to fetch them by hash via ethclient? 
- Why do you call `wg.Done()`, when you have no `wg.Add(1)`, nor `wg.Wait()? `
- You don't actually invoke the function, `go func() { ... } `,must be followed by `()`. This cannot compile.. ?

All transactions are ethereum-transactions . Some modify the state of some contracts. Some of those contracts can be e.g. USDT token, but from a block perspective, there's nothing special about it.

**Comment by MalininDD** [comment]
Full code:
```
func FetchTransactionsInBlock(block *types.Block) (txs []models.PrettyTXInfo, toRescan []string, err error) {
 addressesList, err := storage.FetchJsonAddressesETH()
 if err != nil {
  log.Error().Msg(err.Error())
  return
 }
 var wg sync.WaitGroup
 wg.Add(block.Transactions().Len())
 for _, tx := range block.Transactions() {
  txLiteral := tx
  go func() {
   defer wg.Done()
   var txInfo *types.Transaction
   var isPanding bool
   var err error
   txInfo, isPanding, err = ethClient.TransactionByHash(context.Background(), txLiteral.Hash())
   if err != nil {
    if err.Error() == "not found" {
     log.Error().Msg(fmt.Sprintf("%s - %s", txLiteral.Hash().String(), err.Error()))
     return
    }
    log.Error().Msg(fmt.Sprintf("%s - %s", txLiteral.Hash().String(), err.Error()))
    return
   }
   if isPanding {
    toRescan = append(toRescan, txLiteral.Hash().String())
    log.Warn().Msg("isPanding")
    return
   }

   var find *models.AddressesToScan
   for i, _ := range addressesList {
    if txInfo.To() == nil {
     log.Warn().Msg(fmt.Sprintf("%s - nil .To()", txLiteral.Hash().String()))
     return
    }
    if strings.ToLower(txInfo.To().String()) == addressesList[i].Address {
     find = &addressesList[i]
    }
   }
   if find == nil {
    return
   }

   var msg types.Message
   msg, err = txLiteral.AsMessage(types.NewEIP155Signer(txLiteral.ChainId()))
   if err != nil {
    log.Error().Msg(err.Error())
    return
   }

   var receipt *types.Receipt
   receipt, err = ethClient.TransactionReceipt(context.Background(), txLiteral.Hash())
   if err != nil {
    log.Error().Msg(err.Error())
    return
   }

   if receipt.Status == 0 {
    toRescan = append(toRescan, txLiteral.Hash().String())
    log.Warn().Msg(fmt.Sprintf("%s - status zero", txLiteral.Hash().String()))
    return
   }

   prettyTx := models.PrettyTXInfo{
    TxHash:     txInfo.Hash().String(),
    Address:    txInfo.To().String(),
    From:       msg.From().String(),
    JsonData:   nil,
    JsonDataBy: "",
    Amount:     utils.ValueDivider("ETH", "ETH", float64(txInfo.Value().Int64())),
    Time:       time.Unix(int64(block.Time()), 0),
   }
   for _, toNotify := range find.ToNotify {
    // TODO: make notify
    utils.PrintStructJSON(toNotify)
   }

   txs = append(txs, prettyTx)
   return

  }()
 }
 wg.Wait()
 txRescanHolder.AddToBlock(*block.Number(), toRescan)
 return
}
```

-  _"You have a block with transactions, why do you need to spin up a new routine to fetch them by hash via ethclient?"_ - I need to get the full information in *types.Transaction

- _"Why do you call wg.Done(), when you have no wg.Add(1), nor wg.Wait()?"_ - full code above

- _"You don't actually invoke the function, go func() { ... } ,must be followed by (). This cannot compile.. ?"_ - full code above


All transactions are ethereum-transactions . Some modify the state of some contracts. Some of those contracts can be e.g. USDT token, but from a black perspective, there's nothing special about it. - then why do I get this error?

How to get `*type. Transaction`  for USDT ERC-20. That is, I need full information about the transaction

**Comment by karalabe** [comment]
There's no such thing as an ERC-20 or tether transactions.

There are only Ethereum transactions, which may interact with the Tether contracts either directly, or indirectly via other contract calls. My guess is that you mixed something up. Where do you have these hashes you are trying to find?

**Comment by MalininDD** [comment]
There is a list of Ethereum blockchain wallets. And in a certain situation, I need to get information about transactions in a certain block for wallets from this list.

The final result of the function is an array of objects that contains the following information:
1) ETH or USDT
2) Amount (Value)
3) From and to the address
4) Hash of the transaction

If I don't use the function `etclient.Transactionbyhash (context.Background (), txLiteral. Hash ())`, then there is no error (thanks to @holiman), and I can get information about the transaction (from the receipt and txLiteral) not only in ETH, but also in any other token. But, if this transaction is not an ETH, but for example USDT, then I do not get the transaction value.

Here's what I found - https://ethereum.stackexchange.com/questions/26612/get-the-value-of-erc20-tokens-transferred-using-the-etherscan-api

But using hexutil, I can't get this amount:
```
 v, err := hexutil.Decode("0x00000000000000000000000123c8f973")
 if err != nil {
  log.Error().Msg(err.Error())
 }
 fmt.Println(string(v))
```
I get this string -   #��s

Transaction - 0x53fc6fba4e5d35bad0d5ffc060240787fdfc0e50f2906806059ccd31d0f5ffab

Here's what I found - https://ethereum.stackexchange.com/questions/26612/get-the-value-of-erc20-tokens-transferred-using-the-etherscan-api (second answer)

> There's no such thing as an ERC-20 or tether transactions.
> 
> There are only Ethereum transactions, which may interact with the Tether contracts either directly, or indirectly via other contract calls. My guess is that you mixed something up. Where do you have these hashes from that you are trying to find?

**Comment by karalabe** [comment]
hexutil.Decode decodes the data into a byte slice. I assume you want to convert it into a decimal number. Please check the appropriate methods https://pkg.go.dev/github.com/ethereum/go-ethereum/common/hexutil

**Comment by MalininDD** [comment]
> hexutil.Decode decodes the data into a byte slice. I assume you want to convert it into a decimal number. Please check the appropriate methods https://pkg.go.dev/github.com/ethereum/go-ethereum/common/hexutil

Thanks! now I can get the amount of the USDT transaction. But how to understand this is a USDT transaction or ETH?

**Comment by MariusVanDerWijden** [comment]
This is not an issue with go-ethereum but rather usage advice. Please move this question to the stackexchange: ethereum.stackexchange.com. ETH transactions have the value set in the transaction while USDT transactions are function calls on a smart contract
