### ISSUE TITLE
Transactions created via types.NewTx(LegacyTx and AccessListTx) returns invalid hash

### ISSUE THREAD

**Issue by nnqq** [ethereum/go-ethereum#23101]
#### System information

Geth version: `v1.10.4`
OS & Version: OSX 11.4

#### Expected behaviour

Valid hash as in the blockchain when called types.NewTx().Hash().String()

#### Actual behaviour

New tx via types.NewTx().Hash().String() returns invalid tx hash

#### Steps to reproduce the behaviour

Clone and `go run main.go`

https://github.com/nnqq/geth-tx-hash-bug

I created newTx from valid ropsten tx, but i've got invalid hash

https://ropsten.etherscan.io/tx/0xb4848204c8432070136a41792003caf8dea08f9eb284eb4240845bf64a66a068

```
LegacyTx expected hash     => 0xb4848204c8432070136a41792003caf8dea08f9eb284eb4240845bf64a66a068
LegacyTx actual hash       => 0x9537f13faaa84f57e9231ab5fd6c4392123e2ae85951aad628772f73270472e0
AccessListTx expected hash => 0xb4848204c8432070136a41792003caf8dea08f9eb284eb4240845bf64a66a068
AccessListTx actual hash   => 0x7e7cd94b4e07b6c0175662891555ad3ec06b468af2878c02a11529341bf135db
```

**Comment by AusIV** [comment]
The transaction you linked is a type 2 transaction (EIP-1559). The type, gasFeeCap, and gasTipCap, are all properties that become part of the hash. Why would you expect a transaction that does not have these properties to have the same hash as a transaction that does have these properties?

**Comment by nnqq** [comment]
@AusIV ok. Is there an option to create valid `types.Transaction` structure with go-ethereum?

**Comment by AusIV** [comment]
Yes. Your code generates valid types.Transaction structures, you just have an incorrect expectation of what the hash should be.

**Comment by nnqq** [comment]
@AusIV In my case, i have some data returned from `go-ethereum` API (it builds `types.Transaction` for me), and i have some data from Geth GraphQL API (i should build `types.Transaction` on my own). So i expect these hashes to match.

Can you please provide any example to build `types.Transaction` manually in format which has the same hash as from `go-ethereum` API?

**Comment by AusIV** [comment]
You would need to use types.DynamicFeeTx{} and fill in the appropriate values to match. You'll never get a LegacyTx, AccessListTx, and DynamicFeeTx that hash to the same value, as the transaction type is a part of the hash.

**Comment by nnqq** [comment]
@AusIV thank you. I will try it
