### ISSUE TITLE
[ROPSTEN] Transaction type v2 flood

### ISSUE THREAD

**Issue by iFA88** [ethereum/go-ethereum#23107]
Hey!
Someone flooding ropsten network with free v2 txs:
https://ropsten.etherscan.io/block/10503570

Very strange, because normal they should pay fee.

**Comment by MariusVanDerWijden** [comment]
I think its okay, a miner can choose to include 0 fee transactions as long as the transaction covers the basefee.
I guess etherscan need to make it clearer how much a transaction cost overall and how much of that was burned

**Comment by iFA88** [comment]
Maybe it is an etherscan bug. Infura gives the following for a some type transaction:
```
{
  "accessList": [],
  "blockHash": "0x4c580c8b1a715075cd84cb781735030f2ea769f004ae4f21923a5b8cee19f850",
  "blockNumber": "0xa044f2",
  "chainId": "0x3",
  "from": "0x2f14582947e292a2ecd20c430b46f2d27cfe213c",
  "gas": "0x5208",
  "gasPrice": "0x10ee9a7bb98",
  "hash": "0x012db876535eb5e2bff30cbe81b5701b5b5bf1ce5c50e18aa90232a5b25345d8",
  "input": "0x",
  "maxFeePerGas": "0x38d9bffc8511c",
  "maxPriorityFeePerGas": "0x3b9aca00",
  "nonce": "0xa7bbf",
  "r": "0x95ec07b0617d1c71ea149ade64cf56d1ff5995f406375d7883ed5d63c25e7435",
  "s": "0x3a13e3a9392ba91e43abcf7774a455c766a7167210c63fe6159f6aace8a62a94",
  "to": "0x2f14582947e292a2ecd20c430b46f2d27cfe213c",
  "transactionIndex": "0x7",
  "type": "0x2",
  "v": "0x0",
  "value": "0x470de4df820000"
},
```
So there is transaction fee.

**Comment by MariusVanDerWijden** [comment]
Yeah I think that's an issue with the frontend of etherscan not correctly computing the transaction costs for new tx types

**Comment by iFA88** [comment]
In this case i close this issue :)
