### ISSUE TITLE
possible alternative to the proof-of-work

### ISSUE THREAD

**Issue by Slender1808** [ethereum/go-ethereum#23113]
A possible alternative to the proof-of-work currently used to keep the network secure that uses a hash search algorithm that starts with zeros, my suggestion would be to make this calculation useful for more things besides secure like a compression algorithm that at the same time protects the network as well. decreases her size.

Any blockchain could use this compression algorithm to design, in addition to decreasing the physical size of the network and the use of bandwidth in transmitting blocks.

An alternative to the implementation would be to use zstd with compression level related to network difficulty "note that it would be interesting to modify zstd to allow levels greater than 22"

I don't have enough knowledge for this to implement this feature

**Comment by MariusVanDerWijden** [comment]
@Slender1808 This is the wrong place for suggestions like this. This repository is only for the implementation of the ethereum protocol. Suggestions like this should be posted to the ethereum research forum at ethresear.ch
