### ISSUE TITLE
How do we specify the new parameters for the EIP-1559 transaction?

### ISSUE THREAD

**Issue by vae520283995** [ethereum/go-ethereum#23125]
We know that the transaction has two new parameters, maxFeePerGas and maxPriorityFeePerGas, so how should these two parameters be set, and what is their relationship with filecoin's gasFeeCap and gasPremium?

**Comment by karalabe** [comment]
When you send a transaction, you can specify `maxFeePerGas` and `maxPriorityFeePerGas` in place of the old `gasPrice` field.

Wrt filecoin, I don't want to diverge from Ethereum, but:

> GasFeeCap is the maximum price that the message sender is willing to pay per unit of gas (measured in attoFIL/gas unit). Together with the GasLimit, the GasFeeCap is setting the maximum amount of FIL that a sender will pay for a message: a sender is guaranteed that a message will never cost them more than GasLimit * GasFeeCap attoFIL (not including any Premium that the message includes for its recipient).

> GasPremium is the price per unit of gas (measured in attoFIL/gas) that the message sender is willing to pay (on top of the BaseFee) to “tip” the miner that will include this message in a block. A message typically earns its miner GasLimit * GasPremium attoFIL, where effectively GasPremium = GasFeeCap - BaseFee. Note that GasPremium is applied on GasLimit, as opposed to GasUsed, in order to make message selection for miners more straightforward.

As I understand it

- Ethereum's `maxFeePerGas` and Filecoin's `GasFeeCap` are the same thing
- Based on the GasPremium description, it seems to me that it's a similar scenario, Ethereum's `maxPriorityFeePerGas` and Filecoin's `GasPremium` meaning the same thing.
  - However, Filecoin seems to charge the premium on the gas requested, whereas Ethereum only charges for the gas actually consumed.

**Comment by vae520283995** [comment]
@karalabe Thank you, by the way, is there an api that replaces eth_gasPrice in the new Ethereum client? How much should the value of maxFeePerGas and maxPriorityFeePerGas be set?

**Comment by karalabe** [comment]
Geth sets it automatically if you leave them empty. Yo ucan retrieve Geth's auto values for the priority fee by `eth.maxPriorityFeePerGas` and the fee cap is the priority fee + 2x current basefee.

**Comment by vae520283995** [comment]
> Geth sets it automatically if you leave them empty. Yo ucan retrieve Geth's auto values for the priority fee by `eth.maxPriorityFeePerGas` and the fee cap is the priority fee + 2x current basefee.

I found eth_maxPriorityFeePerGas, but I did not find the api of how to get baseFee

**Comment by karalabe** [comment]
Retrieve the latest block. The base fee is part of it (`baseFeePerGas` field).

**Comment by vae520283995** [comment]
@karalabe Hi,
Now the gasprice in my legacy transaction is taken from eth_gasPrice, after the upgrade, do I need to change it to eth_maxPriorityFeePerGas?

**Comment by karalabe** [comment]
The old endpoint works the same way as it did until now.

**Comment by vae520283995** [comment]
> The old endpoint works the same way as it did until now.

thanks
