### ISSUE TITLE
Missing trie preimages after snap syncing with --cache.preimages enabled

### ISSUE THREAD

**Issue by jwasinger** [ethereum/go-ethereum#23122]
#### System information

OS & Version: Ubuntu 20.04
Commit hash : fc1c1cbea9123cfe6e403b8e21479fa90ee6f9ab

#### Expected behaviour

There should not be missing preimages.

#### Actual behaviour

`WARN [06-29|05:41:18.195] Dump incomplete due to missing preimages missing=...` present in logs.

#### Steps to reproduce the behaviour

* Sync geth with `--syncmode=snap` and `--cache.preimages` flags. 

* Fetch a preimage: `curl -X POST -H "Content-Type: application/json" --data "{ \"method\": \"debug_accountRange\", \"params\": [\"latest\", \"0x00\", 1, true, true, true], \"jsonrpc\": \"2.0\", \"id\": 0}" interface:port`

**Comment by holiman** [comment]
The sync process cannot obtain all preimages. The flag only helps collecting (instead of forgetting) preimages picked up during block execution.

**Comment by jwasinger** [comment]
I see.  I assumed that this full dataset would be part of the sync.  But I can see why having it is not really necessary outside analytics purposes.
