### ISSUE TITLE
unavailable=[shh] and unavailable=[network]

### ISSUE THREAD

**Issue by sami3232** [ethereum/go-ethereum#23127]
#### System information

Geth version: `geth version 1.9.25`
OS & Version: Linux 20.04LTS

#### Expected behaviour
A full archive node from a private chain working perfectly

#### Actual behaviour
I'm getting this error :

 ERROR[06-29|08:53:38.048] Unavailable modules in HTTP API list     unavailable=[shh] available="[admin debug web3 eth txpool personal ethash miner net]"

#### Steps to reproduce the behaviour

I've launched 2 nodes following this tutorial : 
https://medium.com/swlh/how-to-set-up-a-private-ethereum-blockchain-c0e74260492c

Here is my genesis.json file:
```json
{
    "nonce": "0x0000000000000042",
    "timestamp": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x00",
    "gasLimit": "0x000001",
    "difficulty": "0x040",
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x0000000000000000000000000000000000000333",
    "alloc": {},
    "config": {"chainId": 2021 , "homesteadBlock": 0, "eip155Block": 0, "eip158Block": 0, "eip150Block": 0}
}
```

Now I want to change the flags used on one of my nodes. I'd like to launch it in archive node with the following flags.

```
geth --nousb --rpc --rpcaddr 0.0.0.0 --port 30303 --rpcport 8085  --datadir ~/spicy  --rpcapi debug,net,eth,shh,web3,txpool --wsapi "eth,net,web3,network,debug,txpool" --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --syncmode=full --gcmode=archive --rpcvhosts=* --networkid 123 --nodiscover
```

When I execute this command, this error appears.

```
unavailable=[shh] available="[admin debug web3 eth txpool personal ethash miner net]
unavailable=[network] available="[admin debug web3 eth txpool personal ethash miner net]"

```

I guess shh and network don't exist for this version of rpcapi and wsapi but I'm not sure that's why I'm opening this issue.

I use this old version of geth because I try to use blockscout. It seems that the newer versions are not supported with blockscout.

https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache

**Comment by ligi** [comment]
Whisper was removed from geth. Can you just try running it without shh? I cannot really see why blockscout needs whisper - maybe also make a change request to their documentation.

**Comment by sami3232** [comment]
Yeah no problem when I remove network and shh. :+1: 
You're right, I'll make a change request for their doc.

Thank you for your help and especially your reactivity!

I guess we can close this issue now.
