### ISSUE TITLE
London hard fork, geth and openethereum return values ​​are different

### ISSUE THREAD

**Issue by vae520283995** [ethereum/go-ethereum#23124]
https://ropsten.etherscan.io/tx/0x2b6e2683876baa10f2de87811b7f4cb18b9b68e0519f7d943f0348cf6d4c77d9

geth:v1.10.4
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": "0x310e11add898b3b617579832164daeb5c4eca8c76b902ca6b44686f04b7ade67",
        "blockNumber": "0xa05e00",
        "from": "0x822378bfb78bb5635d45cc1f64e47db21ec75ffd",
        "gas": "0x5208",
        "gasPrice": "0x25a02aa9c",
        "maxFeePerGas": "0x25a02aa9c",
        "maxPriorityFeePerGas": "0x25a02aa9c",
        "hash": "0x2b6e2683876baa10f2de87811b7f4cb18b9b68e0519f7d943f0348cf6d4c77d9",
        "input": "0x",
        "nonce": "0x0",
        "to": "0x8210357f377e901f18e45294e86a2a32215cc3c9",
        "transactionIndex": "0xa",
        "value": "0x7b",
        "type": "0x2",
        "accessList": [],
        "chainId": "0x3",
        "v": "0x1",
        "r": "0x23b8a29e6e4ae9dbfa5db770c6d13c280ec6008ec2be3825ad881edbcb6ef8ce",
        "s": "0xc3d666377009573d404737f0fa23faebf74a469bc05b8aba16d46e45d9c7afe"
    }
}
```

openethereum:v3.3.0-rc2
```
{
    "jsonrpc": "2.0",
    "result": {
        "accessList": [],
        "blockHash": "0x310e11add898b3b617579832164daeb5c4eca8c76b902ca6b44686f04b7ade67",
        "blockNumber": "0xa05e00",
        "chainId": "0x3",
        "condition": null,
        "creates": null,
        "from": "0x822378bfb78bb5635d45cc1f64e47db21ec75ffd",
        "gas": "0x5208",
        "hash": "0x2b6e2683876baa10f2de87811b7f4cb18b9b68e0519f7d943f0348cf6d4c77d9",
        "input": "0x",
        "maxFeePerGas": "0x25a02aa9c",
        "maxPriorityFeePerGas": "0x25a02aa9c",
        "nonce": "0x0",
        "publicKey": "0xe72cffa12972763ce7363bc05eeb7f61688a780bb45728584f3fa37e2a53e87da29bf01c740ae0ad79d1081995bf6b814d36799f1145b61e9c6387cc53bba2c3",
        "r": "0x23b8a29e6e4ae9dbfa5db770c6d13c280ec6008ec2be3825ad881edbcb6ef8ce",
        "raw": "0x02f86c038085025a02aa9c85025a02aa9c825208948210357f377e901f18e45294e86a2a32215cc3c97b80c001a023b8a29e6e4ae9dbfa5db770c6d13c280ec6008ec2be3825ad881edbcb6ef8cea00c3d666377009573d404737f0fa23faebf74a469bc05b8aba16d46e45d9c7afe",
        "s": "0xc3d666377009573d404737f0fa23faebf74a469bc05b8aba16d46e45d9c7afe",
        "to": "0x8210357f377e901f18e45294e86a2a32215cc3c9",
        "transactionIndex": "0xa",
        "type": "0x2",
        "v": "0x1",
        "value": "0x7b"
    },
    "id": 1
}
```

https://github.com/openethereum/openethereum/issues/453#issuecomment-868720660

geth has one more field than openethereum: gasprice
So how should the real tx fee be calculated for eip-1559?

**Comment by holiman** [comment]
If it's an executed transaction, there is no need to calculate it - the gasPrice represents the effective price per gas in geth. So the cost is then calculated from that. Gas x gasPrice

**Comment by vae520283995** [comment]
> If it's an executed transaction, there is no need to calculate it - the gasPrice represents the effective price per gas in geth. So the cost is then calculated from that. Gas x gasPrice

You mean that on geth, the method of calculating the fee is the same as the previous transaction: gasUsed*gasPrice

But if the gasPrice field is deleted in a future version, or we can't get the gasprice on clients such as openethereum now, how should the fee be calculated?

**Comment by vae520283995** [comment]
> If it's an executed transaction, there is no need to calculate it - the gasPrice represents the effective price per gas in geth. So the cost is then calculated from that. Gas x gasPrice

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": "0xef34793f27e1a884e215f78364ff2d30a7da7a2784eacff82e7e4ba509e7f53d",
        "blockNumber": "0xa0b782",
        "contractAddress": null,
        "cumulativeGasUsed": "0xe7d7bd",
        "effectiveGasPrice": "0x3b9aca07",
        "from": "0x71b1887bba2de358b22cd053708f7beaed8a07e4",
        "gasUsed": "0x5208",
        "logs": [],
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "status": "0x1",
        "to": "0xa8ec6970fec8842dd229eef170f624c3d77dab45",
        "transactionHash": "0x27eca75ead5ce7a5c9e7da9c91a931e9f11e41d708594c02dfb1c61342e86976",
        "transactionIndex": "0x1b",
        "type": "0x2"
    }
}
```
fee = effectiveGasPrice * gasUsed

**Comment by karalabe** [comment]
So, this is working as expected:

The 1559 spec wanted to remove the old `gasPrice` field from transactions and publish a new `effectiveGasPrice` in the receipts. Geth made a slight variation of this spec:

- The `effectiveGasPrice` in the receipt was added, but that requires pulling the entire receipt from disk, just to discard it because it's not needed at all to calculate the gas price used. As such, we've also kept the gasPrice field in the transaction. Keeping the old field also prevents tools that look at gas prices from insta-breaking post-London.
- The `gasPrice` field for 1559 txs before being mined will return the feeCap, as we don't know how much exactly the cost will be, but we do know the maximum. After inclusion, the gasPrice will be the amount actually paid per gas (same as for non 1559 txs).

**Comment by sunce86** [comment]
> * The `effectiveGasPrice` in the receipt was added, but that requires pulling the entire receipt from disk, just to discard it because it's not needed at all to calculate the gas price used. As such, we've also kept the gasPrice field in the transaction. Keeping the old field also prevents tools that look at gas prices from insta-breaking post-London.

So, should we change the spec then? https://github.com/ethereum/eth1.0-specs/blob/05d6bf480a4e3228cf42b86b044de6832c077b3a/json-rpc/spec.json#L1709

**Comment by vae520283995** [comment]
@sunce86 https://github.com/ethereum/go-ethereum/issues/23125#issuecomment-872009070
Is there a new api for openethereum?
