### ISSUE TITLE
Potential deadlock issue in txSenderCacher

### ISSUE THREAD

**Issue by charlesxsh** [ethereum/go-ethereum#23121]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : 35dbf7a8a35dd4

#### Expected behaviour
 The channel should be properly closed.

#### Actual behaviour
txSenderCacher's tasks has "for range" and send operation, but has no close operation

In core/tx_cacher.go line 62:

```

func (cacher *txSenderCacher) cache() {
  for task := range cacher.tasks {
     for i := 0; i < len(task.txs); i += task.inc {
        types.Sender(task.signer, task.txs[i])
     }
  }
}

// send in another goroutine in In core/tx_cacher.go line 84:
cacher.tasks <- &txSenderCacherRequest{
  signer: signer,
  txs:    txs[i:],
  inc:    tasks,
}

```
Once all related groutings (sender and receiver) are asleep, it could be a deadlock.

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by holiman** [comment]
That's expected, and not an issue. Up to numcpu sender cachers will be "alive", in the global scope. It's not beautiful, and if someone uses geth as a library, there will be some sendercachers idling. However, there's no deadlock, only a very small constant resource usage.
