### ISSUE TITLE
New snapshot syncing mode is slower in 1.10.4 than old method in 1.10.3

### ISSUE THREAD

**Issue by begetan** [ethereum/go-ethereum#23136]
#### System information

Geth version: `Geth version 1.10.4`
OS & Version: Linux Ubuntu 20.04 LTS
AWS c5 instance with x86_x64 CPU comparing with a1/c6g instance with arm64 CPU 

#### Expected behaviour
Snapshot syncing is enabled by default. We expect that it should be faster than regular sync in comparable machine types.

#### Actual behaviour
1. For x86 CPU it took 
- 11 hours for the full sync
- 5 hours for "Rebuilding state snapshot"

2. For Arm64 it took  
- 30 hours for the full sync
- 7 hrs for "Rebuilding state snapshot"

#### Steps to reproduce the behaviour
Run 1.10.4 and check logs

#### Logs
Log timeline is in the below post

**Comment by holiman** [comment]
The speed of a sync depends on several factors, and comparing only two runs is not really worthwhile. It seems your first run took 23 hours, the second 36. While I agree that's a substantial difference, we ourselves run (snap) syncs quite regularly for benchmarking, and we have not seen any regressions recently. 

(I'd like to close this bug, but I'll leave it open a bit longer on the off-chance that there actually is a regression which we haven't noticed)

**Comment by karalabe** [comment]
What kind of disk are you using, what's your IOPs? Can you share full logs, otherwise it's shooting in the dark?

**Comment by begetan** [comment]
I am using AWS EBS volume 1000GB with 3000 IOPS and 125MBs throughput. CPU has 4 Core, RAM 8GB.
Geth `Run with --cache=3072` 

The main question here why after snapshot sync completion it started to regenerate snapshot as for regular sync? Is it expected behaviour or I missed some details about this kind of syncing?

I also wonder what does **State heal** means? This stage is much longer than the previous ordinary state syncing and looks like it does the same work.

I saw a lot of benchmarks of snapshot syncing comparing to old syncing on top machines, but I try to understand the performance of low-end servers. I suppose that snapshot syncing should increase performance on slow machines especially with low throughput discs because of less disk I/O operations.

**Comment by begetan** [comment]
I've completed more tests on different machines and can confirm that slow sync is the issue only for the ARM platform.
It's weird because a synced ARM node is working well in terms of CPU and memory consumption comparing intel machines.

Here is the comparison of similar intel and arm machines. Unfortunately, I haven't done a test for top-level Amazon C6 platform. So it might be really an issue of the Amazon a1 types

c5.xlarge  4 core, 8GB RAM, EBS Volume 1000GB with 3000 IOPS 

```Jul 5 13:31:00 Start 
Jul  5 19:19:16 State sync in progress: Last (5h 48m from start)
 Jul  5 19:19:30 State heal in progress: First 
 Jul  5 23:12:24 Disabling direct-ancient mode 
 Jul  5 23:55:16 Rebuilding state snapshot
Jul  5 23:58:47 Upgrading chain index 0% 
Jul  6 00:17:09 Upgrading chain index 99% (10h 38m) 
Jul  6 05:02:48 Resuming state snapshot generation: Last (+ 5h 7m)
```
  Full sync is about 11h + 5h for creating a new state snapshot. It's actually better than the old way of syncing.

a1.xlarge 4 core, 8GB RAM, EBS Volume 1000GB with 3000 IOPS

```Jun 29 10:46:00 Start 
Jun 29 22:59:43 State sync in progress: Last (12h 13m from start) 
Jun 29 22:59:53 State heal in progress: First
Jun 30 06:29:31 Disabling direct-ancient mode
Jun 30 16:30:35 Rebuilding state snapshot
Jun 30 16:32:31 Upgrading chain index 0% 
Jun 30 17:06:56 Upgrading chain index 99% (30h 20m from start)
Jul  1 00:00:13 Resuming state snapshot generation: last ( +7h 28 min)
```

I was surprised that even with snapshot sync a node starts the process of snapshot regeneration after a full sync. Although it is much faster now both for x86_64 and arm64 than in previous versions of Geth.

**Comment by holiman** [comment]
@begetan thanks for the stats! 

There's a direct relation between the time of the state-sync, and the time of the heal. 
If the state-sync finishes in `2N hours` instead of `N hours`, that means the data will be "twice as stale". And if the state is more stale, then there will be more healing to do. 

To add to that, whatever (network? IO? cpu?) it was that made the first phase (state sync) slow, will _also_ slow down the second phase. So there's this kind of double-combo-effect on the second phase (state heal).

**Comment by begetan** [comment]
I've updated stats with AWS c6 second-generation ARM instance. It's pretty the same both for the initial sync ~ 12h vs 11h and snapshot generation.

@holiman
My conclusion about snapshot sync based on your explanation: It requires powerful enough minimal CPU otherwise, the initial sync time may rise non proportionally higher.

**Comment by begetan** [comment]
I ran tests with the disabled snapshot sync option for the mentioned machine types. It looks like the old snapshot sync method takes more time for version 1.10.4 than the new snapshot methods.

Unfortunately, the constant growth of the blockchain data increasing sync time permanently, but this is not related to the new sync method. It does improve sync time.
