### ISSUE TITLE
abigen generates functions for golang withour error check

### ISSUE THREAD

**Issue by MikaelLazarev** [ethereum/go-ethereum#23130]
#### System information

Geth version: github.com/ethereum/go-ethereum v1.10.3
Abigen: 1.9.25-unstable-566cb4c5-20201130
OS & Version: OSX

#### Expected behaviour
I generate golang binding for chainlink aggregatorV3Interface (https://github.com/smartcontractkit/chainlink/blob/master/evm-contracts/src/v0.6/interfaces/AggregatorV3Interface.sol)

I expect that all errors during calling eth node has errors wrappers

#### Actual behaviour

For LatestRoundData it generates following:

// LatestRoundData is a free data retrieval call binding the contract method 0xfeaf968c.
//
// Solidity: function latestRoundData() view returns(uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound)
func (_AggregatorV3Interface *AggregatorV3InterfaceCaller) LatestRoundData(opts *bind.CallOpts) (struct {
	RoundId         *big.Int
	Answer          *big.Int
	StartedAt       *big.Int
	UpdatedAt       *big.Int
	AnsweredInRound *big.Int
}, error) {
	var out []interface{}
	err := _AggregatorV3Interface.contract.Call(opts, &out, "latestRoundData")

	outstruct := new(struct {
		RoundId         *big.Int
		Answer          *big.Int
		StartedAt       *big.Int
		UpdatedAt       *big.Int
		AnsweredInRound *big.Int
	})

	outstruct.RoundId = out[0].(*big.Int)
	outstruct.Answer = out[1].(*big.Int)
	outstruct.StartedAt = out[2].(*big.Int)
	outstruct.UpdatedAt = out[3].(*big.Int)
	outstruct.AnsweredInRound = out[4].(*big.Int)

	return *outstruct, err

}

This code breaks if out wasn't get correctly (for example communication error) and shut down all machine.

#### Steps to reproduce the behaviour

1. Download Chainlink oracle from https://github.com/smartcontractkit/chainlink/blob/master/evm-contracts/src/v0.6/interfaces/AggregatorV3Interface.sol
2. Generate abi file for it.
3. Check that there is no error handler

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by MariusVanDerWijden** [comment]
I think that was fixed quite a long time ago, could you retry with a newer version of abigen?
