### ISSUE TITLE
Bad block #116525

### ISSUE THREAD

**Issue by Aranad** [ethereum/go-ethereum#2313]
I'm trying to run geth but it won't sync, I tried reloading the whole block chain from scratch but still dies at the same block, 116525. I'm running the latest version 1.3.5.

I0308 15:34:54.188672   21792 downloader.go:278] Block synchronisation started
I0308 15:35:05.612007   21792 chain_manager.go:788] Bad block #116525 (ec46ee8db536b9bfe6c0721c9d98e231c9b4731acf60ae6e74f41645ad0354ac)
I0308 15:35:05.612036   21792 chain_manager.go:789] gas used error (2625335 / 2625969)
I0308 15:35:05.612132   21792 downloader.go:254] Synchronisation failed: hash fetching canceled (requested)

**Comment by karalabe** [comment]
Are you sure you're running `1.3.5`? 

 * I've just pulled and ran 1.3.5 and it synced just fine past that block.
 * The log `hash fetching canceled (requested)` does not exist in 1.3.5 (it doesn't exist since Novemeber).

**Comment by Atrides** [comment]
I have the same problem on one node. May be ralated with issue #2305 bacuse http://pastebin.com/rP5Re3i8

**Comment by karalabe** [comment]
@Atrides That is a simple data race. There's a PR open to address it. This issue is different and cannot happen unless you're using a half a year old version of the client.

**Comment by Aranad** [comment]
Thanks for pointing that out! I realised I had changed the git branch to 1.3.5 but hadn't run make again, working now :-)
