### ISSUE TITLE
Foreign character appears when syncing a geth lightclient on a network you haven't synced in a while

### ISSUE THREAD

**Issue by Zachinquarantine** [ethereum/go-ethereum#23135]
#### System information

Geth version: 1.10.4-stable-aa637fd3
OS & Version: Windows, Version 21H1 (OS Build 19043. 1081) (amd64)
Commit hash : N/A

#### Expected behaviour
When I run a lightmode client on a testnet I haven't used in a while, it should sync the block headers and show the normal time in milliseconds.

#### Actual behaviour
As the lightclient catches up and starts verifying the block headers of blocks that have been created within the last 3 minutes, the MS symbol (for milliseconds), starts glitching out, and instead shows µs on **some** new blocks

#### Steps to reproduce the behaviour
Download a fresh install of geth (only if you sync all networks regularly), or start running a light client of a testnet you don't sync often (this is what I did to get this), eg ``geth --goerli --syncmode light``

#### Backtrace

````
unsure what this means
````
Logs:
https://pastebin.com/AtcP01pD
Note that in the logs, as the block age for each new block I sync gets shorter and shorter, the µs starts occuring.

**Comment by holiman** [comment]
ms=millisecondsµs=microsecondsns=nanoseconds

**Comment by holiman** [comment]
Email ate my linebreaks :)ms=millisecondsµs=microsecondsns=nanoseconds

**Comment by Zachinquarantine** [comment]
ok
