### ISSUE TITLE
ethclient.Client in go-ethereum unit testing

### ISSUE THREAD

**Issue by livelybug** [ethereum/go-ethereum#23148]
I am using [backends.SimulatedBackend](https://pkg.go.dev/github.com/ethereum/go-ethereum@v1.10.3/accounts/abi/bind/backends#SimulatedBackend) in unit testing.

however, ```backends.SimulatedBackend``` is not compatible with [ethclient.Client](https://pkg.go.dev/github.com/ethereum/go-ethereum/ethclient#Client).

Any one can advise how to create a ```ethclient.Client``` in unit testing? Thank you

[Duplicated in stackexchange](https://ethereum.stackexchange.com/questions/98803/ethclient-client-in-go-ethereum-unit-testing)

**Comment by karalabe** [comment]
You probably just need to update your dependencies to the latest go-ethereum versions. AFAIK we use the exact same combo for CI tests too. Alternatively, please share the error you see.

**Comment by livelybug** [comment]
@karalabe Thank you for the reply.

I am composing a unit test case, which sends tx to a contract and listens to the corresponding events:
* Send a tx to the contract. I use ```backends.SimulatedBackend``` to simulate

  What I followed is [one of the official unit test cases](https://github.com/ethereum/go-ethereum/blob/aa637fd38a379db6da98df0d520fb1c5139a18ce/ethclient/ethclient_test.go#L190), but it doesn't compose ```backends.SimulatedBackend```.  So I modify the code below [this line](https://github.com/ethereum/go-ethereum/blob/aa637fd38a379db6da98df0d520fb1c5139a18ce/ethclient/ethclient_test.go#L211) to generate a ```backends.SimulatedBackend```

```go
  sim := backends.NewSimulatedBackend(genesis.Alloc, 80000000)
  return n, blocks, sim
```

   The test below is good.

```go
genesis, _, backend  := newTestBackend(t) // backend is of type backends.SimulatedBackend
client, err := genesis.Attach()

// Deploy a contract
  transactor := bind.NewKeyedTransactor(testKey)
  address, tx, contract, err := esource.DeployEsource(transactor, backend)
  backend.Commit()
  ctx, _ := context.WithDeadline(context.Background(), time.Now().Add(50*time.Second))
  address, err = bind.WaitDeployed(ctx, backend, tx)

// Send a lock tx to the contract
  tx, err = contract.LockAsset(transactor, "0xcA7210D4443a49e1807eD721089499634b75C9Fd",
    "ETH", lockAmt)
  backend.Commit()

// Verify the balance is changed accordingly
  backend.BalanceAt(ctx, transactor.From, backend.Blockchain().CurrentBlock().Number())
```

* Listen to the events of the contract tx but failed. I tried the following:
```go
//--Deploy a contract and sent tx to the contract, as the code snip above -- 

    rec, err := bind.WaitMined(context.Background(), backend, tx)
    // the rec returned is correct, containing the event expected

    // Failed to get block
    ec := ethclient.NewClient(client)
    ctx, cancel := context.WithTimeout(context.Background(), 100*time.Millisecond)
    block, err := ec.BlockByNumber(ctx, rec.BlockNumber)
    if err != nil {
      t.Fatal("Failed to get block by block height")  // The code stops here
    }
```

Is there any example of similar test cases(involved ethclient.Client)? 
Or can you help advise why the method ```BlockByNumber``` failed? 

Thank you

**Comment by MariusVanDerWijden** [comment]
>  v1.9.22
You're using a pretty old version, since then we changed some stuff in the simulated backend and in ethclient. 

The issue is that you're generating a simulated backend that has nothing to do with the node that was created before.
Basically you have two chains, one with the simulated backend and one with an actual node.
Now you send transactions on one chain (the simulated backend) and expect them to be delivered on the other chain (the actual blockchain).
You either need to modify your code to only use the simulated backend, or to only use the actual chain (the one you called `genesis`)

So something like this (might not be 100% accurate: 
```
genesis, _, _  := newTestBackend(t) // backend is of type backends.SimulatedBackend
client, err := genesis.Attach()

// Deploy a contract
  transactor := bind.NewKeyedTransactor(testKey)
  address, tx, contract, err := esource.DeployEsource(transactor, client)
  ctx, _ := context.WithDeadline(context.Background(), time.Now().Add(50*time.Second))
  address, err = bind.WaitDeployed(ctx, client, tx)

// Send a lock tx to the contract
  tx, err = contract.LockAsset(transactor, "0xcA7210D4443a49e1807eD721089499634b75C9Fd",
    "ETH", lockAmt)

// Verify the balance is changed accordingly
number, err := client.BlockNumber(context.Background())
  client.BalanceAt(ctx, transactor.From, number)
  ```

**Comment by MariusVanDerWijden** [comment]
Ethclient and simulated backend can be used synonymous as they both implement the interfaces declared here: https://github.com/ethereum/go-ethereum/blob/master/interfaces.go
They are drop-in replacements, this does not mean you can connect with an ethclient to a simulated backend though

**Comment by livelybug** [comment]
Thanks for the reply.

I tried to update to the latest go-ethereum, v1.10.4; But there are some breaking changes.
Retaining v1.9.22, is the answer you provided still working?

```go
	address, tx, contract, err := esource.DeployEsource(transactor, client)
```
hit error:
cannot use client (type *rpc.Client) as type bind.ContractBackend in argument to esource.DeployEsource:
	*rpc.Client does not implement bind.ContractBackend (missing CallContract method)

**Comment by MariusVanDerWijden** [comment]
Ah sorry, you need to wrap the client again as an ethclient.
```
genesis, _, _  := newTestBackend(t) // backend is of type backends.SimulatedBackend
client, err := genesis.Attach()
ec := ethclient.NewClient(client)

// Deploy a contract
  transactor := bind.NewKeyedTransactor(testKey)
  address, tx, contract, err := esource.DeployEsource(transactor, ec)
  ctx, _ := context.WithDeadline(context.Background(), time.Now().Add(50*time.Second))
  address, err = bind.WaitDeployed(ctx, ec, tx)

// Send a lock tx to the contract
  tx, err = contract.LockAsset(transactor, "0xcA7210D4443a49e1807eD721089499634b75C9Fd",
    "ETH", lockAmt)

// Verify the balance is changed accordingly
number, err := ec.BlockNumber(context.Backgrou
```

**Comment by livelybug** [comment]
Thanks, the incompatible type error is gone, but I was not able to find where to set the gas limit.
```go
// Hit error: contract creation code storage out of gas
address, tx, contract, err := esource.DeployEsource(transactor, ec)
```

I tried to set the gas limit [here](https://github.com/ethereum/go-ethereum/blob/aa637fd38a379db6da98df0d520fb1c5139a18ce/ethclient/ethclient_test.go#L233),
```go
genesis.GasLimit = 999999999
```
but hit an error: can't import test blocks: unknown ancestor

**Comment by MariusVanDerWijden** [comment]
You need to set it in the genesis definition here: https://github.com/ethereum/go-ethereum/blob/aa637fd38a379db6da98df0d520fb1c5139a18ce/ethclient/ethclient_test.go#L223

For further questions please use the stackexchange: https://ethereum.stackexchange.com/

**Comment by livelybug** [comment]
@karalabe Can you take a look at the relevant question on [ethereum stackexchange](https://ethereum.stackexchange.com/questions/103112/use-backends-simulatedbackend-and-ethclient-client-synonymously)?
