### ISSUE TITLE
Change initial behavior of eth_syncing

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#23143]
This is a follow up of a discussion sparked by #23099
Currently eth_syncing initially returns nil which is suboptimal - a better approach would be to initially return syncing with current- and highest- block "0" that better describes the current state.

**Comment by 0x0elliot** [comment]
hey, i am new to helping out with geth but i definitely want to break in. 

point me in the correct direction and i will quickly move! do keep in mind that i am new to the code base and here to learn more about it.

**Comment by kehiy** [comment]
> This is a follow up of a discussion sparked by #23099 Currently eth_syncing initially returns nil which is suboptimal - a better approach would be to initially return syncing with current- and highest- block "0" that better describes the current state.

@ligi 
where and in which file the `eth_syncing` going to be done?

**Comment by lightclient** [comment]
We should really discuss this in the execution apis repo, I opened an issue to track it: https://github.com/ethereum/execution-apis/issues/428
