### ISSUE TITLE
How to compact the current space of archive node?

### ISSUE THREAD

**Issue by Shirley-Ji** [ethereum/go-ethereum#23151]
Hey guys,

The SSD consuming is more and more heavy. I am doing a etherscan-similar website, I've already put those tx data and receipt data, contract data onto mysql/mongo, but I still have to keep those big blockchain data in my expensive SSD. Is there a way to compact those old data? or back up them to other non-SSD hard disk, SSD is too expensive and more and more expensive with more and more data.

Thanks,
Shirley

**Comment by CRYONE7** [comment]
366eb44a7a0aa5bd342deea215ec19a184a11f2ca22220304ebb20b9c8917e2b  bitcoin-0.21.1-x86_64-linux-gnu.tar.gz
-----BEGIN PGP SIGNATURE-----

wsFcBAABCAAQBQJfRS9FCRBwrRVL+Vhd5gAAe2kQAL/cMqjAzpmRr3VxRBJJ89Iz
t8kwOJrPpoqcegUuT/OmFU1m3dGClbIY8zdadF7oaQ2MpXAc0K1v0gIpI/Wj1c5h
5PbLznjB9trLdsbh4k3BEHQQhJQmFISXWxkASKpPJCJFymYrc9e2s5rMm294pfe7
hnY+ZGDx4RbDqjlKsuxPmUDQLWcZdeqCmYhg6KaDScqDvU8M+4w1lox4xsXZ/GlY
20lJmTBKlB0dfTt0e+wh5sdYmJwOka98eC89z2uVeel/oDQYIFeg9xn1x7IRlOZx
doK930GdLZWm2v+N4CDWsKEen0s6uQhwV6adUmbdS/oi2Q15Gl0RGCB+T8E3DPJc
0NFypoxxBGmEqvM2nVXu2vywJpqczooG5qnTDmKDrNrxRBwJFnFJ9FdMFhWArnk0
A9CkrewO4UPNenumgcRE9sa6Y79qgtGHamF5QHOyZnMPwXXU0IT1wX43Mhfubn7p
g5o8Lxx+d5K8+DLsmGSFgYZ2HSuv1eTopM0GFqFDqgWJoI3TXoUoOc9G8oV2rab2
rFm+5CAsk5zz6HB1+NodUZB4S4XM23L3qrT4S+TztqA42+6Ea4RQOxJY2SxMNeXA
wa2uICju+0FWzQSgaafqZENzhxEqGWNfMl9mYyffzp0nGxuovB8TNjNj+uJBur3y
gheTTJMrwUYb2bk2Komj
=2lm/
-----END PGP SIGNATURE-----

**Comment by karalabe** [comment]
Unfortunately, not.

**Comment by CRYONE7** [comment]
{<inG LUID NING IBPA>}
by: ¶CHRYSTOPHER CASERO DIZON¶
