### ISSUE TITLE
Make `TxData` functions public

### ISSUE THREAD

**Issue by fedekunze** [ethereum/go-ethereum#23154]
# Rationale

**Why should this feature exist?**

The existing `TxData` interface defines its functions as unexported, making it impossible to provide our own implementation of these methods.

https://github.com/ethereum/go-ethereum/blob/3b053185254959b2c52129b8d146d300a78eb1ad/core/types/transaction.go#L68-L88

**What are the use-cases?**

Our use case is that we need to implement the `TxData` implementation as a [`proto.Any`](https://developers.google.com/protocol-buffers/docs/proto3#any) that can support all the concrete implementations of the tx data: `LegacyTxType`, `AccessListTxType` and `DynamicFeeTxType`. We want our `TxData` interface to embed the `TxData` interface from geth so that we are able to reduce maintenance.

# Implementation

**Do you have ideas regarding the implementation of this feature?**
Make the `TxData` functions public.

**Are you willing to implement this feature?**

Yes

**Comment by fedekunze** [comment]
cc @s1na

**Comment by s1na** [comment]
Hey @fedekunze. I had a quick look and it seems in the lifetime of #21502 these accessor methods started out as public methods but were made private in https://github.com/lightclient/go-ethereum/commit/389f039c89211eccfd68e6244a55a48d549789ca#diff-8fb609018eccff10931645347515b8ecc194992cc4ef9e84ebdea87682dd50c3.

I know in general that the `core/types` API has been usually kinda stable and it's changed with care which I guess is the reason why these TxData methods were made private. But I can bring this up for discussion and if there was agreement on exporting them make a PR to address it.

**Comment by fedekunze** [comment]
Thanks @s1na, here's our PR to add support for `proto.Any` if you need more context: https://github.com/tharsis/ethermint/pull/220

**Comment by ligi** [comment]
Can you elaborate why you need to serialize tx.data and not the raw bytes of the transaction that already cares for the transaction type and has a spec (EIP)

**Comment by fjl** [comment]
We expose `TxData` for only one reason: making creation of `types.Transaction` from Go code more convenient. The methods of `TxData` are an internal implementation detail and will never be stable API. It's not a good idea to send these fields over protocol buffers. If your app needs to send/receive Ethereum transactions over protocol buffers, it should accept them as opaque binary data, which can be parsed by `Transaction.UnmarshalBinary`.
