### ISSUE TITLE
V3 keystore file field names (Crypto vs. crypto)

### ISSUE THREAD

**Issue by axic** [ethereum/go-ethereum#2316]
According to the wiki, all field names in JSON would be lowercase: https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

This is not the case with geth generated files, where the `crypto` field is written as `Crypto`. I think this is due to [this code](https://github.com/ethereum/go-ethereum/blob/e5532154a50114d5ffb1ffd850b746cab00cb899/crypto/key.go#L51-L56) lacking the `json:crypto` attribute.

**Comment by karalabe** [comment]
This was actually fixed a long time ago, just not pushed out to the 1.3.x branch: https://github.com/ethereum/go-ethereum/blob/develop/crypto/key.go#L54

**Comment by karalabe** [comment]
Here's the relevant commit/PR: https://github.com/ethereum/go-ethereum/pull/2056

**Comment by axic** [comment]
Great! Will it be released sometime?

**Comment by karalabe** [comment]
Two Wooks (TM) :))

No time set yet, but hopefully after the Homestead transition goes smoothly we'll lock it down and push it out asap.
