### ISSUE TITLE
Потрібно добавити місцезнаходження особи, що підтверджує певну дію, блок. Спростить можливість відстеження ланцюжка послідовності.

### ISSUE THREAD

**Issue by Pasitos** [ethereum/go-ethereum#23164]
Потрібно добавити місцезнаходження особи, що підтверджує певну дію, блок. Спростить можливість відстеження ланцюжка послідовності.
 Плюсом також буде ідентифікація особи.

_Originally posted by @Pasitos in https://github.com/ethereum/ethereum-org-website/pull/3267#discussion_r663884304_

**Comment by MariusVanDerWijden** [comment]
Please keep issues in english
