### ISSUE TITLE
Let set the IPC to global folder

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#2317]
Currently in the latest develop we change the IPC path based on the datadir. This makes not much sense as the Unix socket path should always be the same path, so any application can connect to any running node.

E.g. if you change your datadir to an external harddrive, the unix socket IPC wouldn't work from there anymore, due to OS restrictions.

So there is not much sense in moving the IPC path based on the datadir.

What came out of the idea to move it to `/tmp/ethereum.ipc` ?

**Comment by fjl** [comment]
I like this idea.

**Comment by karalabe** [comment]
I don't :P

This comes crumbling down when you want to run multiple instances on the same computer, which is further complicated when you have an instance running, want to develop on another and maybe run some tests concurrently which fire up the IPC. Most people will run geth with the defaults, so I don't think this is much of an issue, and if it is, then make sure the tools can handle a different path.

Having a global singleton master path is imho a very bad design decision. Imagine that I have a geth instance working for public apps, and a private instance. I forget by accident to explicitly set the IPC path too for the private instance, and all of a sudden all my apps poke around in my private chain.

I would much rather have sane defaults that play nice together with different scenarios.

**Comment by karalabe** [comment]
Also various platforms have a ton of restrictions on where you have permissions for what. Within the datadir is usually a safe starting bet that the correct user can access it, others cannot and that the user actually has permission to open a socket there.

There are linux distros that have limited access to `tmp`, I've seen OSX versions which use custom `tmp` folders for certain apps to sandbox them, it may not even be a bindable path. Android is again a very strange beast on this front.

Lets not dumb down geth to avoid having Mist implement a path selection :P

**Comment by frozeman** [comment]
Can you run two instances at the same time? wont they anyway interfere with each other on ports etc?

I see this more of usage perspective, how often you run multiple instances compared to how often people run testiest and want their dapps/mist etc to connect to it?

I think the latter is way more often, and people could simply set a custom ipcpath for the former 
edge case.

**Comment by fjl** [comment]
@karalabe In order to run multiple instances, you already need to set --port, --rpcport, --datadir to different values. Setting --ipcpath also doesn't make it worse. If you run multiple instances all the time and find it inconvenient we can make it easier in some other way (i.e. add flag `--instance <N>` that sets all the other flags).

**Comment by fjl** [comment]
I think `~/.web3/node.socket` could be a good location for the socket file. On Windows it would be `\.pipe\web3\node` or a similar name.

**Comment by fjl** [comment]
See #1812.
