### ISSUE TITLE
Estimated gas question

### ISSUE THREAD

**Issue by yp945** [ethereum/go-ethereum#23182]
Estimated gas canont give match gasLimit， 
I guess this is related to the internal transaction of the contract. According to estimated gas binary search algorithm, if internal transcation failed，but external transaction success. it will get a wrong gasLimit

**Comment by yp945** [comment]
This is my test contract  proxy contract delegate call target call 

target contract  code

`pragma solidity ^0.5.8;
contract Calculator {
    uint256 public calculateResult;
    
    function add(uint256 a, uint256 b) public returns (uint256) {
        for (uint256 i = 0; i < 5000; i++) {
            calculateResult += 100;
            assert(calculateResult >= a);
        }
        return calculateResult;
    }
}`

proxy contract  code 

`pragma solidity ^0.5.8;
contract Proxy1 {
    uint256 public calculateResult;
    
  
    event AddedValuesByDelegateCall(uint256 a, uint256 b, bool success);
    
    
    function addValuesWithDelegateCall(address calculator, uint256 a, uint256 b) public  {
        
        calculator.delegatecall.gas(3000000)(abi.encodeWithSignature("add(uint256,uint256)", a, b));
        
    }
    

}`

**Comment by yp945** [comment]
i use metamask and remix with rposten network , here is my tx 
https://ropsten.etherscan.io/tx/0xdc8d41b982c5c1d50bc45925c8b1505606a55e40dab9d574e3111d3c9530acf0

**Comment by karalabe** [comment]
It is a transaction's own problem to revert if an internal call fails. If the internal call failed but the outer call accepted that execution, than from our perspective, it's a good execution.
