### ISSUE TITLE
err="missing trie node" and "Snapshot extension registration failed"

### ISSUE THREAD

**Issue by sami3232** [ethereum/go-ethereum#23189]
#### System information

Geth version: `Geth version: 1.10.4-stable`
OS & Version: Ubuntu 20.04LTS

#### Expected behaviour
Having a node with less errors

#### Actual behaviour
I'm trying to launch a blockchain explorer named blockscout but when I launch the server on my private chain, I'm getting some issues that I don't really understand. I know it comes from geth but don't really know why they appeared.

One of the error I'm constantly having :
```
ERROR[07-10|15:11:52.946] Snapshot extension registration failed   peer=98998f1a err="peer connected on snap without compatible eth support"
```

Then it's looping with these messages. My node doesn't seems to find any peers. 

```
INFO [07-10|15:11:30.895] Looking for peers                        peercount=1 tried=108 static=0
INFO [07-10|15:11:41.167] Looking for peers                        peercount=0 tried=108 static=0
INFO [07-10|15:11:52.737] Looking for peers                        peercount=0 tried=71  static=0
```

Once I launch the blockscout server, I'm getting this warning:
```
WARN [07-10|15:15:36.794] Served eth_getBalance                    conn=127.0.0.1:38625 reqid=19 t="49.631µs"  err="missing trie node 432ccea7vb54e5e15b1ae7b96b84cc1ab7103o99687508a70749az472263c9f6 (path )"
WARN [07-10|15:15:36.794] Served eth_getBalance                    conn=127.0.0.1:38625 reqid=20 t="65.933µs"  err="missing trie node cd6919eae87618sa8dd3226176076ac99ec2687df702d67528e65g49e618e53 (path )"
```
It's looping too.

If you have any idea or if you know what can I change to fix my errors, I'll be glad to read your suggestions.

#### Others

Here is my genesis.json file:
```json
{
    "nonce": "0x0000000000000042",
    "timestamp": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x00",
    "gasLimit": "0x8000000",
    "difficulty": "0x040",
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x0000000000000000000000000000000000000333",
    "alloc": {},
    "config": {"chainId": 2021 , "homesteadBlock": 0, "eip155Block": 0, "eip158Block": 0, "eip150Block": 0}
}
```
Here are the flags I'm using for this node : 
```
geth --syncmode "full" --gcmode=archive --datadir ~aled/test --networkid 923822 --http --http.port "8545" --port 30303 --http.addr 0.0.0.0 --http.corsdomain "*" --http.api "debug,eth,net,web3,personal,miner,txpool" --http.vhosts="*" --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api "debug,eth,net,web3,personal,miner,txpool" --ws.origins "*" --nodiscover
```

**Comment by begetan** [comment]
This ERROR message means that your peer is not supporting the new snapshot sync feature enabled by default in version 1.10.4.  It is either outdated or not completed snapshot regeneration after the initial full sync was completed.

WARN message is about the number of the peers

**Comment by rjl493456442** [comment]
The reason for this log `err="peer connected on snap without compatible eth support"` is that some other clients try to connect with your node, with snap enabled but no eth protocol. It's because some clients rename the eth protocol to their own name. You can just ignore this error.

`missing trie node cd6919eae87618sa8dd3226176076ac99ec2687df702d67528e65g49e618e53 (path )"` it means your database is fired with the broken state. You may want to resync the node.

**Comment by sami3232** [comment]
Thank you guys for the quick reply, I'll check that and try resync my nodes
