### ISSUE TITLE
How to expand the size of an Ethereum network

### ISSUE THREAD

**Issue by lzszsd** [ethereum/go-ethereum#23187]
I am using Geth to develop a private chain. Every time I start the Geth Javascript console, the log in its directory will update information like this:

> geth : INFO [07-09|10:22:36.319] Maximum peer count                       ETH=25 LES=0 total=25

which I take as the allowed size of my chain. **However, the project I am working on involves more than 25 nodes.** How can I modify this default configuration? I have rummaged through the source code on https://github.com/ethereum/go-ethereum, but don't get much insight into the problem. 

I have tried putting forward this question at https://discord.gg/nthXNEv and at the Ethereum stack exchange at https://ethereum.stackexchange.com but failed due to some unknown error. Please help! @gravityblast @bts @shazow @fjl @sauliusgrigaitis

**Comment by shazow** [comment]
https://ethereum.stackexchange.com/questions/45807/can-max-peer-count-be-increased

**Comment by ligi** [comment]
thanks for answering @shazow

**Comment by fjl** [comment]
@lzszsd just to prevent a misunderstanding: the max peer count of one node is not the same as the max overall peer count in your network. There is no limit on the number of nodes in an Ethereum network. It is not recommended to raise the max peer count significantly. Raising it will not improve much.

**Comment by lzszsd** [comment]
@fjl Thank for clarifying. But is there much difference between "the peer count of one node" and "the overall peer count"? If all nodes in a network are on-line, then the difference between the two counts is 1. And what does "raising it will not improve much" mean? Can the max peer count be finally changed or not?
