### ISSUE TITLE
Retrieve signer address of clique network

### ISSUE THREAD

**Issue by saman-pasha** [ethereum/go-ethereum#23193]
I use ```client.BlockByNumber(context.Background(), blockNumber)``` to get block then use ```block.Coinbase().Hex()``` to get Coinbase but all the time it returns 0x0000... zero address. when i use ```geth attach PrivateNetwork``` i can get Coinbase by ```eth.coinbase```. How can I get Coinbase address"

**Comment by MariusVanDerWijden** [comment]
Are you using a clique network? In clique networks the coinbase is usually set to 0x00. The sealers address is in the extradata of the block

**Comment by saman-pasha** [comment]
Yes I use clique. My Coinbase is ```0x4fbf98afd5b068d6bfc1c7704d4a8b23147cba32``` and last ```block.Extra()``` was ```0xd883010a04846765746888676f312e31362e34856c696e7578000000000000000c51655c1934cf19f5fad344e7122587c7a75ca134b91c81533c9ca6af211cb97773112961b6eeb98555c1c6129cfc2459fce6a754e1a1aa8256e4dfa64ca97800``` How could I find my coinbase in extraData?

**Comment by MariusVanDerWijden** [comment]
Like this:
```
if len(header.Extra)-extraSeal < 0 {
		return common.Address{}, errors.New("invalid extra data in header")
	}
	signature := header.Extra[len(header.Extra)-extraSeal:]
	// Recover the public key and the Ethereum address
	pubkey, err := crypto.Ecrecover(SealHash(header).Bytes(), signature)
	if err != nil {
		return common.Address{}, err
	}
	var signer common.Address
	copy(signer[:], crypto.Keccak256(pubkey[1:])[12:])
	return signer, nil
	```
	
I have a PR implementing this as an API call here: https://github.com/ethereum/go-ethereum/pull/22987

**Comment by saman-pasha** [comment]
I had little change on your function to use it as a utility function
```
func getSigner(header *types.Header) (common.Address, error) {
	if header == nil {
		return common.Address{}, errors.New("could not find header")
	}
	if len(header.Extra) - crypto.SignatureLength < 0 {
		return common.Address{}, errors.New("invalid extra data in header")
	}
	signature := header.Extra[len(header.Extra) - crypto.SignatureLength:]
	// Recover the public key and the Ethereum address
	pubkey, err := crypto.Ecrecover(clique.SealHash(header).Bytes(), signature)
	if err != nil {
		return common.Address{}, err
	}
	var signer common.Address
	copy(signer[:], crypto.Keccak256(pubkey[1:])[12:])
	return signer, nil
}
```
...
```
blockSigner, err := getSigner(block.Header())
if err != nil {
	log.Println(err)
} else {
	log.Println(blockSigner.Hex())
}
```
...
It works correct.
Thanks a lot

**Comment by saman-pasha** [comment]
But I think the Issue should be open until they commit your function

**Comment by karalabe** [comment]
This has been merged onto master.

**Comment by karalabe** [comment]
Btw, if you want to use Go, please check `clique.Author`. That does what you're looking for.
