### ISSUE TITLE
geth 1.4-unstable RPC returns error when receiving null properties

### ISSUE THREAD

**Issue by slothbag** [ethereum/go-ethereum#2319]
If I create a tx with {gas: null, gasPrice: null} then geth 1.4-unstable returns an error, whereas in geth 1.3.x it works fine.

What's the desired behaviour?

**Comment by juanfranblanco** [comment]
:+1: 
I believe that RPC should allow null values passed as in previous versions..

**Comment by obscuren** [comment]
I agree that null is a valid value, however, null gas is not possible and should return error: insufficient intrinsic gas.

What's the error you're getting?

**Comment by slothbag** [comment]
If I remember rightly I was doing a eth_call tx so most the fields were null.. "to", "gas", "gasPrice", "value".. I was getting errors for pretty much every one of them.. account not long enough, gasPrice not a valid number etc

**Comment by juanfranblanco** [comment]
@obscuren null values should use the default value, ie gas nulll != 0. It means value not set.

**Comment by slothbag** [comment]
I'm getting what looks like a very similar error with geth 1.4.3

The call..
```
{"id":1,"jsonrpc":"2.0","method":"eth_call","params":[{"from":null,"to":"0x73cc8baf770e17af57c1519abac8708e75b7d6e9","gas":null,"gasPrice":null,"value":null,"data":"0x9d76ea58"},"latest"]}
```

The response..
```
Invalid address length, expected 40 got 4 bytes
```

Could be the "from" field.

**Comment by knocte** [comment]
I think I'm having the same problem as @slothbag in 1.4.4.

@bas-vk, why did you close this?

**Comment by slothbag** [comment]
to be fair bas-vk closed this a while back after the initial fix, I didn't discover the "from" field was still a problem until recently.  However I did log a new issue for this that just got closed unexpectedly #2579

**Comment by bas-vk** [comment]
Because the initial report was a question that indicated a bug that was solved in a merged PR. @slothbag added another unrelated comment after I closed this issue which should have been a new issue.

Since I did fix a bug with `eth_call` it would be nice if you could try this with develop and if it still occures create a new issue.

**Comment by knocte** [comment]
Thanks for the quick response guys.

@bas-vk what's the first geth version that has your fix?

**Comment by bas-vk** [comment]
1.4.5

**Comment by juanfranblanco** [comment]
I have tested and is working now, I have also put a fix in Nethereum to ignore null values as default encoding.
