### ISSUE TITLE
How to alter contract function or mapping with eth_call?

### ISSUE THREAD

**Issue by t-anyu** [ethereum/go-ethereum#23196]
Hey,

The main Geth documentation indicates that this should be possible, but couldn't figure it out.

I'm trying to "simulate" a call that requires token balance to be positive, otherwise reverts. Assumably I could do this by either changing contract's balance[account] mapping or overriding balanceOf function.

Could anyone guide how the eth_call's "State override set" should be formulated for this kind of action?

Thank_s !

DAMN I'm blind!

There's an override example on the documentation's bottom section.

Anyway, still, can I assume that state override set should be formulated like this:
{
    Contract address: { code: bytecode from compiler }
}

Now does the bytecode need to be full contract code? Or can I just inject partial code, for example just defining the override function or mapping?

Thanks

**Comment by MariusVanDerWijden** [comment]
You can override both the code and the storage of a contract with the overrides.
An example for it can be found here: https://github.com/ethereum/go-ethereum/blob/9624f92edef5e0a76a97efd302e983077acb6e35/ethclient/gethclient/gethclient_test.go#L297
I'll write up an example in js and put it in the docs

**Comment by MariusVanDerWijden** [comment]
Ahh nvm, there is already an example as you pointed out in the issue.
No you can not inject partial bytecode, you need to replace the full byte code (but you can replace certain storage slots, don't have to replace all of them)

**Comment by t-anyu** [comment]
Thanks!
