### ISSUE TITLE
Delete stale encoded object value in level db?

### ISSUE THREAD

**Issue by james-ray** [ethereum/go-ethereum#23201]
# Rationale

Why should this feature exist? 
The patriack trie uses prefix-tree to search the key, I think there are two scenarios:
1. the key is irrelevant to the data of the leaf node
2. the key is the hash of the encoded leaf node value
Is it possible to add a special bit flag for the second case, and it some field value in the leaf node changes, the whole old node can be deleted in DB.

What are the use-cases?

For example, there is a mapping in the contract:
mapping(address => Pet)) userPetMap;

struct Pet{
 uint256 petID;
 uint8 length;
 uint256 type;
 bytes name;
}

I don't know if my understanding is correct, I think the query needs two searches in the patriack tree,
first, the tree searches the address to find the leaf node, which is the hash of the pet struct instance.
second, the tree searches the hash to find the pet struct instance value.
If the pet grows bigger, we modify its length, the old object value and its hash still exist in DB, and I think we can delete the old hash and object in this case.

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by rjl493456442** [comment]
Now you can use the offline state pruner to delete the stale data. Check `geth snapshot prune-state -h` for more details.
I am working on the runtime state pruner but it's more complicated(and require the state scheme change) so it's not ready yet.
