### ISSUE TITLE
An error, request support

### ISSUE THREAD

**Issue by bitbeb** [ethereum/go-ethereum#23212]
https://geth.ethereum.org/docs/dapp/native-bindings

Transacting with an Ethereum contract

```
func main() {
// Create an IPC based RPC connection to a remote node and instantiate a contract binding
conn, err := ethclient.Dial("/home/karalabe/.ethereum/testnet/geth.ipc")
if err != nil {
log.Fatalf("Failed to connect to the Ethereum client: %v", err)
}
token, err := NewToken(common.HexToAddress("0x21e6fc92f93c8a1bb41e2be64b4e1f88a54d3576"), conn)
if err != nil {
log.Fatalf("Failed to instantiate a Token contract: %v", err)
}
// Create an authorized transactor and spend 1 unicorn
auth, err := bind.NewTransactor(strings.NewReader(key), "my awesome super secret password")
if err != nil {
log.Fatalf("Failed to create authorized transactor: %v", err)
}
tx, err := token.Transfer(auth, common.HexToAddress("0x0000000000000000000000000000000000000000"), big.NewInt(1))
if err != nil {
log.Fatalf("Failed to request token transfer: %v", err)
}
fmt.Printf("Transfer pending: 0x%x\n", tx.Hash())
}
```

I test and always make mistakes:

[root@iZt4n20guljct01a322mi6Z src]# go run main.go token.go
2021/07/15 10:21:06 Failed to request token transfer: net/http: nil Context

What is the reason? thank you!

**Comment by bitbeb** [comment]
func main() {
	// Create an IPC based RPC connection to a remote node and instantiate a contract binding
	conn, err := ethclient.Dial("/home/karalabe/.ethereum/testnet/geth.ipc")
	if err != nil {
		log.Fatalf("Failed to connect to the Ethereum client: %v", err)
	}
	token, err := NewToken(common.HexToAddress("0x21e6fc92f93c8a1bb41e2be64b4e1f88a54d3576"), conn)
	if err != nil {
		log.Fatalf("Failed to instantiate a Token contract: %v", err)
	}
	// Create an authorized transactor and spend 1 unicorn
	auth, err := bind.NewTransactor(strings.NewReader(key), "my awesome super secret password")
	if err != nil {
		log.Fatalf("Failed to create authorized transactor: %v", err)
	}
	tx, err := token.Transfer(auth, common.HexToAddress("0x0000000000000000000000000000000000000000"), big.NewInt(1))
	if err != nil {
		log.Fatalf("Failed to request token transfer: %v", err)
	}
	fmt.Printf("Transfer pending: 0x%x\n", tx.Hash())
}

**Comment by karalabe** [comment]
What version of Geth / bindings are you using? We fixed an issue in the latest release.

**Comment by bitbeb** [comment]
Hello, how can I correct this problem?
I'm using the previous version  V1.9+

**Comment by MariusVanDerWijden** [comment]
Update to the latest release 1.10.5. This issue was fixed in https://github.com/ethereum/go-ethereum/commit/c63c2d855e6febeb351fa190a442cb37f6609ca1
