### ISSUE TITLE
Always seeing bogus "Unclean shutdown detected" messages

### ISSUE THREAD

**Issue by SjonHortensius** [ethereum/go-ethereum#23232]
#### System information

Geth version: `Geth/v1.10.5-stable-33ca98ec/linux-amd64/go1.16.6`

#### Expected behaviour

Geth could log unclean shutdowns once (although the usefulness is debatable)

#### Actual behaviour

Geth keeps warning there have in the past been unclean shutdowns (even after clean shutdowns were done after that)

#### Steps to reproduce the behaviour

* have unclean shutdowns
* see them always when starting geth

#### Backtrace

````
Jun 28 16:25:57 machine geth: WARN [06-28|16:25:57.771] Unclean shutdown detected                booted=2021-06-05T19:19:46+0200 age=3w1d21h
Jun 28 16:25:57 machine geth: WARN [06-28|16:25:57.771] Unclean shutdown detected                booted=2021-06-19T10:14:57+0200 age=1w2d6h
...
Jul 19 12:10:42 machine geth[: INFO [07-19|12:10:42.484] Blockchain stopped
Jul 19 12:10:49 machine systemd[1]: geth.service: Deactivated successfully.
Jul 19 12:10:52 machine geth: WARN [07-19|12:10:52.873] Unclean shutdown detected                booted=2021-06-05T19:19:46+0200 age=1mo1w6d
Jul 19 12:10:52 machine geth: WARN [07-19|12:10:52.873] Unclean shutdown detected                booted=2021-06-19T10:14:57+0200 age=1mo1h55m

````

When submitting logs: please submit them as text and not screenshots.

**Comment by ligi** [comment]
> Geth could log unclean shutdowns once (although the usefulness is debatable)

why do you think the usefulness is debatable?

> Geth keeps warning there have in the past been unclean shutdowns (even after clean shutdowns were done after that)

a clean shutdown does not repair the problems arising from an unclean shutdown

**Comment by SjonHortensius** [comment]
> > Geth could log unclean shutdowns once (although the usefulness is debatable)
> 
> why do you think the usefulness is debatable?

I have never experienced a crash that was only observable through this message. Either something is wrong, and my logs show that it didn't shutdown properly so that was the cause - or something isn't wrong and `geth` works as expected. This message doesn't provide me with additional information.

> > Geth keeps warning there have in the past been unclean shutdowns (even after clean shutdowns were done after that)
> 
> a clean shutdown does not repair the problems arising from an unclean shutdown

Right. So I need to complete rebuild my database to get rid of this message even though everything works fine?

**Comment by ligi** [comment]
This log entry really helps us getting context on reports we get. Wondering why you have unclean shutdowns in the first place - can't you avoid them? And wouldn't avoiding them solve your issue also?

**Comment by SjonHortensius** [comment]
Okay - you are probably right. I falsely expected these errors to get cleared but I understand their use and I get why this was done intentional. I'll ignore them or rebuild my database to get rid of these.. Their cause isn't relevant to this issue - I caused them myself while testing some things

**Comment by newearthmartin** [comment]
> I falsely expected these errors to get cleared

That's a normal, healthy expectation. After everything is solved, **there should be no weird "problem sounding" messages in the logs.**

Seeing a message like this makes you wonder what's wrong and that's stressful, considering that geth is the foundation of the validator stack.

**Comment by hvtuananh** [comment]
> Wondering why you have unclean shutdowns in the first place - can't you avoid them?

Sometimes unclean shutdown is unavoidable without replacing or buying more hardware, e.g. OOM or power loss.
