### ISSUE TITLE
Error: connect EAGAIN  path/to/geth.ipc

### ISSUE THREAD

**Issue by yg0x01** [ethereum/go-ethereum#23236]
Hi. When I connect geth with ipc file for while, I got `Error: connect EAGAIN path/to/geth.ipc` error. 
What's this error message mean and how can I avoid it. Thx!

**Comment by ligi** [comment]
can you provide more details about your setup? OS, geth-version(s), ..

**Comment by yg0x01** [comment]
Sorry forgot providing details.

I used a i3.2xlarge EC2 instance with 8 vCPUs, 64GB Memory, 1.7T native NVME and 40G gp3 volume for hosting the operating system. The AMI was Amazon Linux 2 AMI (HVM), SSD Volume Type, in 64-bit (x86) arch.

geth version: bsc 1.1.0-beta

I think it because I have too many connections or the data transfer is too large for this IPC file But I'm not sure. Thanks for help.

**Comment by ligi** [comment]
does it also happen with a unmodified geth instance? If not please open the issue on the BSC repo

**Comment by yg0x01** [comment]
@ligi Sorry. I didn't test on eth mainnet with unmodified geth client. When I test it I will post the result here.

**Comment by holiman** [comment]
>  When I test it I will post the result here.

Please reopen if/when you do
