### ISSUE TITLE
Option to drop eth_sign/personal_sign prefiex

### ISSUE THREAD

**Issue by ex7ept** [ethereum/go-ethereum#23238]
# Rationale

We had lots of eth nodes and use them to generate address/account.
And these addresses would be also used in other private network/chain.

When we want to sign tx for other private chain, we need move the keystore-file from the corresponding eth node to private chain node. this operation is very unsafe. And some potential exception (such as   new-feature-module-logic or network/IO issue) may cause the move error, then tx sign error, .

So for now, we want to call eth node _sign api to sign tx, and broadcast the returned rawTx by corresponding private chain.
All our eth nodes are in our own network env, so no safe issue for us. 

And I found the code is deadly written "fmt.Sprintf("\x19Ethereum Signed Message:\n%d%s", len(data), string(data))" before sign. 

Shall I request to add some geth --option to make this prefix dropped ? 

(Also checked the code of eth_signTransaction, would only be able to sign tx for self-chain, since reply protection).
# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by ligi** [comment]
I do not think there should be an option to drop the prefix. The sign API should use that for protection. 
Maybe you want to using separate clef instances (for each chainID) pointing to the same keystore could be an option?

**Comment by ex7ept** [comment]
@ligi  Aho, We'd already used this kind of way, but that would take much to complete

**Comment by ligi** [comment]
please complete doing so - we decided we do not want this option
