### ISSUE TITLE
evm t8n  calculate difficulty

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#23249]
The current env format is 
```
{
   "currentCoinbase" : "0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
   "currentDifficulty" : "0x020000",
   "currentGasLimit" : "0x05f5e100",
   "currentNumber" : "0x01",
   "currentTimestamp" : "0x03e8",
   "previousHash" : "0xe729de3fec21e30bea3d56adb01ed14bc107273c2775f9355afb10f594a10d9e",
   "blockHashes" : {
       "0" : "0xe729de3fec21e30bea3d56adb01ed14bc107273c2775f9355afb10f594a10d9e"
   }
}
```

want to extend the following format to be acceptable (as well as the old one)
```
{
   "currentCoinbase" : "0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
   "parentDifficulty" : "0x020000",
   "currentGasLimit" : "0x05f5e100",
   "currentNumber" : "0x01",
   "parentTimestamp" : "0x03e7",
   "currentTimestamp" : "0x03e8",
   "previousHash" : "0xe729de3fec21e30bea3d56adb01ed14bc107273c2775f9355afb10f594a10d9e",
   "blockHashes" : {
       "0" : "0xe729de3fec21e30bea3d56adb01ed14bc107273c2775f9355afb10f594a10d9e"
   }
}
```

new fields: *parentDifficulty* instead of currentDifficulty
and *parentTimestamp*

the result file then
```
{
  "currentDifficulty" : "0x020001"
  "stateRoot": "0x1c99b01120e7a2fa1301b3505f20100e72362e5ac3f96854420e56ba8984d716",
  "txRoot": "0xb5eee60b45801179cbde3781b9a5dee9b3111554618c9cda3d6f7e351fd41e0b",
  "receiptRoot": "0x86ceb80cb6bef8fe4ac0f1c99409f67cb2554c4432f374e399b94884eb3e6562",
  "logsHash": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "receipts": [
  ]
}
```

would report the new difficulty calculated with geth formula  *currentDifficulty*

**Rationale**
To avoid point of failure when generating the tests. Currently retesteth calculates the difficulty, but retesteth difficulty formula might be wrong. Since we test the clients, it would make sense that retesteth asks t8ntool what geth evm thinks would be the new difficulty given parentTimestamp and parentDifficulty and currentTimestamp.

**Comment by holiman** [comment]
SGTM. So just to clarify even further, I'd propose: 

1. The `currentDifficulty` can be given as input. If so, goto 4, If not, then 
2. Verify `parentDifficulty`, `parentTimestamp` and `currentTimestamp` are present (otherwise fail), and 
3. Calculate the `currentDifficulty`. 
4. Continue the execution

And lastly, the output env _always_ provides the `currentDifficulty`, regardless of whether it was given or calculated.

**Comment by holiman** [comment]
Actually, there's one snag; the parent may or may not have uncles. And whether the parent has uncles, affects the difficulty.
