### ISSUE TITLE
Importing "go-ethereum/accounts/abi/bind" results in error "import cycle not allowed" when compiling Geth

### ISSUE THREAD

**Issue by m-e-r-k-l-e-root** [ethereum/go-ethereum#23246]
If I add `"github.com/ethereum/go-ethereum/accounts/abi/bind"` to the `Imports` section of the file `api.go` located within the path `go-ethereum/internal/ethapi/` (i.e. [api.go](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go)) then proceed to compile Geth (i.e. `make geth`) I receive the following error message:

```
package github.com/ethereum/go-ethereum/cmd/geth
        imports github.com/ethereum/go-ethereum/cmd/utils
        imports github.com/ethereum/go-ethereum/eth
        imports github.com/ethereum/go-ethereum/eth/ethconfig
        imports github.com/ethereum/go-ethereum/node
        imports github.com/ethereum/go-ethereum/accounts/external
        imports github.com/ethereum/go-ethereum/signer/core
        imports github.com/ethereum/go-ethereum/internal/ethapi
        imports github.com/ethereum/go-ethereum/accounts/abi/bind
        imports github.com/ethereum/go-ethereum/accounts/external: import cycle not allowed
```

I can't quite locate what would be causing the `import cycle not allowed` error, I would have assumed the error should have been `imported and not used: "bind"`

Either way this error is quite unfortunate being that I need to import `"github.com/ethereum/go-ethereum/accounts/abi/bind"` in `api.go` located within the path `go-ethereum/internal/ethapi/` in order to be able to interact with my smart contracts in my slightly modified version of Geth.

Any suggestion would be greatly appreciated thanks.

**Comment by MariusVanDerWijden** [comment]
Well golang disallows packages importing other packages that imports themselves (import cycle).
Importing `bind` in `ethapi` creates such a cycle because `node` imports `external`, `external` imports `ethapi`, `ethapi` imports `bind` and `bind` imports `external`.
You might need to create a new package for your smart contracts that will then be called from `ethapi`

**Comment by m-e-r-k-l-e-root** [comment]
@MariusVanDerWijden 

Thanks for the response.

So I've implemented what I think you were referring to, error seems to be the same (my apologies if there were any misunderstandings on my part), this is exactly what I tried:

Here is the contract I'm using for testing purposes, _Store.sol_:

```
pragma solidity ^0.5.16;

contract Store {
  event ItemSet(bytes32 key, bytes32 value);

  string public version;
  mapping (bytes32 => bytes32) public items;

  constructor(string memory _version) public {
    version = _version;
  }

  function setItem(bytes32 key, bytes32 value) external {
    items[key] = value;
    emit ItemSet(key, value);
  }
}
```
I use `solc --abi Store.sol > Store.abi` along with `solc --bin Store.sol > Store.bin` to generate _Store.abi_ & _Store.bin_ files for  _Store.sol_

I then use `./abigen --bin=Store.bin --abi=Store.abi --pkg=store --out=store.go` to generate _store.go_

Once I've generated _store.go_ I execute `mkdir $GOROOT/src/store/ && mv ./store.go $GOROOT/src/store/`

Then what I do is edit the _api.go_ file located within _go-ethereum/internal/ethapi/_ and add `"store"` into the `Imports` section of the _api.go_ (i.e. [api.go](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go))

Then, to compile geth I execute `go install ./cmd/geth`, but I receive this error:
```
package github.com/ethereum/go-ethereum/cmd/geth
        imports github.com/ethereum/go-ethereum/cmd/utils
        imports github.com/ethereum/go-ethereum/eth
        imports github.com/ethereum/go-ethereum/eth/ethconfig
        imports github.com/ethereum/go-ethereum/node
        imports github.com/ethereum/go-ethereum/accounts/external
        imports github.com/ethereum/go-ethereum/signer/core
        imports github.com/ethereum/go-ethereum/internal/ethapi
        imports store
        imports github.com/ethereum/go-ethereum/accounts/abi/bind
        imports github.com/ethereum/go-ethereum/accounts/external: import cycle not allowed
```

I was expecting the error to be: `imported and not used: "store"`

So, for further testing purposes I added `"store"` into the `Imports` section of the _main.go_ file (I removed all changes to _api.go_ for this test at this point) located within _/go-ethereum/cmd/geth/_ (i.e. [main.go](https://github.com/ethereum/go-ethereum/blob/master/cmd/geth/main.go)) and when I went to compile Geth it gave me the error I wanted and/or was expecting to see, i.e. `imported and not used: "store"`

Do you have any suggestions in regard to preventing this _import cycle_? I'm still as we speak trying additional approaches in regard to resolving this issue but as of now nothing has worked, any help and/or suggestions would be greatly appreciated.
