### ISSUE TITLE
Ledger wallet closed after a while on mac

### ISSUE THREAD

**Issue by s1na** [ethereum/go-ethereum#23243]
#### System information

Geth version: `f05419f`
OS & Version: OSX

#### Expected behaviour

Ledger connects and stays connected.

#### Actual behaviour

It connects successfully and starts deriving accounts. But fails abruptly with `hidapi: unknown failure`, after which point the wallet is closed. Failure is undeterministic, sometimes occurs after a few seconds, sometimes a bit later. Also when I disable the heartbeat loop it doesn't happen anymore. I thought it might be a data race with two routines wanting to use device at the same time or modifying the device object but couldn't find it. I'm gonna shelf this for now but creating this issue for documentation of the problem.

#### Steps to reproduce the behaviour

Connect ledger and start geth with `--usb`. Wait for a while and check `personal.listWallets` a few times to see the error.

**Comment by ligi** [comment]
next step - sina checks if it also happens with the TREZOR on his system

**Comment by holiman** [comment]
We updated the usb backends a while back, using much more recent libraries. Please reheck and re-open if this is still an issue
