### ISSUE TITLE
Runtime out of memory error in geth

### ISSUE THREAD

**Issue by osiz-blockchainapp** [ethereum/go-ethereum#23255]
Hi,

Geth version: 1.10.3-stable
OS & Version: Linux

Running geth node in AWS server. It runs maximum 1 day then it will produce "Runtime out of memory error"
How much memory it will take?
How to solve this issue?

**Comment by rjl493456442** [comment]
What's your machine spec? What's your command line setting to launch the node? Usually for mainnet it requires at least 8GB memory.

**Comment by osiz-blockchainapp** [comment]
> What's your machine spec? What's your command line setting to launch the node? Usually for mainnet it requires at least 8GB memory.

Hi, 
Running private geth node in AWS server.
**command**:
**Initialize genesis node**
geth --datadir ./node1 init ./genesis.json
**Running command**
 geth --datadir /node1 --rpc --rpcaddr 0.0.0.0  --networkid 10 --rpcport 8545 --rpccorsdomain "*"  --rpcapi 
 "eth,net,web3,personal,miner" --allow-insecure-unlock console
 
 My server storage is 8 GB

**Comment by rjl493456442** [comment]
There has a guide for inspecting the memory usage, maybe you can check it by yourself to see if there is memory leak.

https://github.com/ethereum/go-ethereum/issues/23195

**Comment by begetan** [comment]
@osiz-blockchainapp 

What is the hardware spec of your AWS machine (not the disk size)?

Testnets run fine on a 4GB RAM machine with parameter `--cache=1024` in most cases.

**Comment by osiz-blockchainapp** [comment]
> @osiz-blockchainapp
> 
> What is the hardware spec of your AWS machine (not the disk size)?
> 
> Testnets run fine on a 4GB RAM machine with parameter `--cache=1024` in most cases.

Hi,
Hardware spec: 4 CPU and 16GB RAM in AWS machine

**Comment by mohamedmansour** [comment]
I got the same thing on VM with 8GB of RAM but I had 3 Geth Instances, after I turned off one, I stopped getting OOM.

**Comment by MariusVanDerWijden** [comment]
We fixed a memleak in v.1.10.9 could you update to a newer version and see if the error still persists?
