### ISSUE TITLE
Rinkeby Faucet: No Ethereum address found to fund - Facebook

### ISSUE THREAD

**Issue by basharsalleh** [ethereum/go-ethereum#23253]
Rinkebey Faucet is not working with Facebook posts anymore.

<img width="1191" alt="Screen Shot 2021-07-23 at 8 31 50 AM" src="https://user-images.githubusercontent.com/57413417/126725014-fc862221-9be4-4d9d-acad-c5fdbf0dbeaf.png">

**Comment by tylerchambers** [comment]
I'm pretty sure this is just because the way that facebook is accessed is flaky. It's done by reading the mobile site instead of the graph API. 

Have you tried again / gotten it to work since your report?

**Comment by yhaibo1116** [comment]
Hello @tylerchambers 

Same issue here. May I also request ~15 ether at:
0xB4fbB252F14b5A76798dF52c41aA2738b98Ce382
Thank you so much.

![image](https://user-images.githubusercontent.com/86807042/135770504-633cf92a-1073-4f4b-bcff-ccf5c031dfc9.png)
![image](https://user-images.githubusercontent.com/86807042/135770516-ea7ad916-b854-4c5d-a69e-cf6c1687566a.png)

**Comment by 01kingsmus** [comment]
I need about 15 ether cause Twitter is not working in my country Nigeria
0x98593B7C03d72B626ceDE356c5da64D500ae19D3
pls.

**Comment by MariusVanDerWijden** [comment]
The faucet does not support facebook anymore (due to changes in their api)
