### ISSUE TITLE
Last block height is less than last block height in Etherscan

### ISSUE THREAD

**Issue by blockchen-admin** [ethereum/go-ethereum#23266]
Last block height is less than last block height in Etherscan

Synchronization is complete,
Why is it processed 1 block lower than Etherscan???

Disk performance is perfect.
It uses NVME SSDs.

Until a few days ago, the last block was processed normally.

**Comment by rjl493456442** [comment]
How many peers you have? You can check it via `geth --exec "admin.peers" attach <your ipc endpoint>`.
And if you find any interesting log, please post them here.

**Comment by blockchen-admin** [comment]
16 peers

**Comment by rjl493456442** [comment]
Can you check the running log? Do you find any interesting logs? It's hard for us to check the issue without enough information.

**Comment by holiman** [comment]
Issue seems stale, closing

**Comment by Jaysonmaldx** [comment]
Yes thank you
