### ISSUE TITLE
Remove rpccorsdomain and rpcapi

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#23267]
saw this in the logs of geth 1.10.6:

```
WARN [07-25|10:45:11.365] The flag --rpccorsdomain is deprecated and will be removed June 2021, please use --http.corsdomain 
WARN [07-25|10:45:11.365] The flag --rpcapi is deprecated and will be removed June 2021, please use --http.api 
```

we are past june - so this should be removed with the next version

**Comment by Zachinquarantine** [comment]
can this be assigned to me? I'm working on removing this at [Zachinquarantine/go-ethereum/remove-legacy-rpc](https://github.com/Zachinquarantine/go-ethereum/tree/remove-legacy-rpc)
