### ISSUE TITLE
Provide topic signature hash for contract events using `abigen`

### ISSUE THREAD

**Issue by benzsuankularb** [ethereum/go-ethereum#23269]
**Provide topic signature hash for contract events using `abigen`.**

Why should this feature exist?
We use `abigen` but can't use the generated code to filter event topics from `client.SubscribeFilterLogs`

What are the use-cases?
```
ethClient.SubscribeFilterLogs(
		context.Background(),
		ethereum.FilterQuery{
			Topics: [][]common.Hash{
				{
					Erc20ContractTransfer{}.ID, // Something like this
				},
			},
		},
		s.logChannel,
	)
```

**Comment by benzsuankularb** [comment]
No need for this feature much since we have the `WatchTransfer` generated method.

**Comment by MattKetmo** [comment]
fyi I've reopened same issue for a different use case (filtering many events) https://github.com/ethereum/go-ethereum/issues/25630
