### ISSUE TITLE
Is the `GasLimit` should be a fixed value after London hardfork?

### ISSUE THREAD

**Issue by Nanyan** [ethereum/go-ethereum#23268]
Hi, there

version: 1.10.6

According to the `CalcGasLimit1559` function:
```go
// CalcGasLimit1559 calculates the next block gas limit under 1559 rules.
func CalcGasLimit1559(parentGasLimit, desiredLimit uint64) uint64 {
	delta := parentGasLimit/params.GasLimitBoundDivisor - 1
	limit := parentGasLimit
	if desiredLimit < params.MinGasLimit {
		desiredLimit = params.MinGasLimit
	}
	// If we're outside our allowed gas range, we try to hone towards them
	if limit < desiredLimit {
		limit = parentGasLimit + delta
		if limit > desiredLimit {
			limit = desiredLimit
		}
		return limit
	}
	if limit > desiredLimit {
		limit = parentGasLimit - delta
		if limit < desiredLimit {
			limit = desiredLimit
		}
	}
	return limit
}
```

The returned `limit` should be eventually equal to `desiredLimit`, and then it will no longer change anymore.

So the block's `GasLimit` will be a fixed value once it hit the `config.GasCeil` :
```go
header.GasLimit = core.CalcGasLimit1559(parentGasLimit, w.config.GasCeil)
```

Is that the purpose by design?

**Comment by rjl493456442** [comment]
This GasLimit can be adjusted by the miners via `--miner.gaslimit`.

**Comment by Nanyan** [comment]
So if all miners use a same `gasLimit`, then it will be no any dynamic adjustment, no matter the network is busy or not. 

Does it a really better choice  then the old one with a range of [gasFloor, gasCeil] ?

**Comment by rjl493456442** [comment]
gasFloor is unnecessary complexity we think. I have a PR to remove the gasFloor flag. https://github.com/ethereum/go-ethereum/pull/23213

**Comment by rjl493456442** [comment]
Close it now. Feel free to reopen if you have any other thoughts.
