### ISSUE TITLE
hard fork: invalid block unknown ancestor

### ISSUE THREAD

**Issue by Dimple-Kanwar** [ethereum/go-ethereum#23272]
hi,
I already have a private network running and a lot of transaction has been done. Now, I want to undo some changes and modify few fields in genesis file. also wants to preserve previous blocks(old blockchain data). 
How can I achieve that? 
do we need to do hard fork or any other alternative? 
if hard fork is required then how can I do that? 
I tried some steps of hard fork but not able to import old blockchain state.

I am getting `invalid block 999: unknown ancestor` .
 block 999 was the latest block of old blockchain.

thanks!

**Comment by rjl493456442** [comment]
You can try to launch the new chain(with genesis modification and protocol rule changes) and re-send all the transactions. 
Close the issue since it's not relevant with go-ethereum.
