### ISSUE TITLE
Readme sync mode

### ISSUE THREAD

**Issue by dzid26** [ethereum/go-ethereum#23276]
I am new to geth.
It is pretty difficult to find true information about syncing mode (I think the behaviour was changing over the years). 
Could there be at least be a link to [this](https://geth.ethereum.org/docs/getting-started#sync-modes ) in Readme.md: ? 
I was trying `geth setmode --help`, which I don't think is supported. 

Also shouldn't [Readme](https://github.com/ethereum/go-ethereum/blame/master/README.md#L67) say that default syncmode is the _snap_ mode, not _fast_ anymore?

**Comment by ligi** [comment]
thanks - you are correct - the README was wrong here - fixed in #23282
Not yet sure about adding another link - the README is already quite long

**Comment by ligi** [comment]
wondering where you saw "geth setmode"
