### ISSUE TITLE
EIP1559 Transactions dropped from Mempool before confirmation. 

### ISSUE THREAD

**Issue by ChristianTucker** [ethereum/go-ethereum#23288]
#### System information

Geth version: `Version: 1.10.6-stable`
Parameters: `ExecStart=/usr/bin/geth --rinkeby --http --http.corsdomain '*'  --http.addr 0.0.0.0 --http.api admin,db,eth,miner,web3,net,personal,txpool --ws --ws.addr 0.0.0.0 --ws.api admin,db,eth,miner,web3,net,personal,txpool --ws.origins '*' --datadir /mnt/volume_nyc1_04/ethereum --txpool.globalslots 75000 --txpool.accountslots 64 --txpool.accountqueue 16 --txpool.globalqueue 5000 --txpool.lifetime 24h0m0s --maxpeers 250`
OS & Version: `Linux, Ubuntu Server 20.04 LTS`

#### Explain the issue
Transactions of type 2 (EIP1559) are broadcasted using the `web3.eth.subscribe('pendingTransactions'` event however they are "dropped" `getTransaction(hash)` returns null before they are confirmed. These transactions show in `rinkeby.etherscan.io` for awhile as pending before finally becoming marked as confirmed. Transaction for example of one that was dropped from our mempool but was confirmed. <https://rinkeby.etherscan.io/tx/0x3ecc9ff08ceb5b1e27a0ee637e8ddb886ab05548908cb77a4791639ee477d2b3>

This happens for every type 2 transaction.

#### Expected behaviour
Type 2 transactions should stay in the mempool until they are either confirmed as being dropped or included in a block. `getTransaction` shouldn't return `null` for valid transactions that the mempool was originally aware of.

#### Actual behaviour
Type 2 transactions are dropped from the mempool even when they're valid. 

#### Steps to reproduce the behaviour
using web3js..
```js
web3.eth.subscribe('pendingTransactions', (error, result) => {})
  .on('data', (hash) => {
    let tx = web3.eth.getTransaction(hash);
    console.log(tx != null); // true 
    setTimeout(() => {
      tx = web3.eth.getTransaction(hash);
      console.log(tx != null); // false
      // This transaction will still confirm. 
    }, 500);
  });
```

We don't run into this issue with any legacy transactions. We keep a database of transactions and associated data and remove them as they're dropped from the mempool.

**Comment by rjl493456442** [comment]
I tried your script and also sent a few 1559 transactions, but it works for me.

**Comment by ligi** [comment]
Can you provide more information about the transactions you are sending and maybe some of the geth log?

**Comment by MariusVanDerWijden** [comment]
It might be because you are sending a bunch of transactions that kick each other out of your local mempool?
Are you sending more than one transaction at a time?

**Comment by MariusVanDerWijden** [comment]
This issue got quite stale now. I'm going to close it, feel free to reopen if you still feel like 1559 transactions are dropped from the mempool regularly
