### ISSUE TITLE
Specify ethash folder in CLI

### ISSUE THREAD

**Issue by Tekarihoken** [ethereum/go-ethereum#2328]
Data directory can be specified using the datadir flag but the Ethash folder cannot be specified by the user.
For people that have a  small SSD with HomeDir on it it can become quickly an issue since this folder is growing very fast.

I have used a turnaround : creating a Sym-link but it is a quick and dirty solution.

**Comment by fjl** [comment]
A symlink is the official solution to this.

**Comment by karalabe** [comment]
With Geth 1.6 there will also be a flag to specify it. Currently it's `--ethash.dagdir`, though it may change until we finalize the release.
