### ISSUE TITLE
How can i get the Goerli Test ETH?

### ISSUE THREAD

**Issue by lpf763827726** [ethereum/go-ethereum#23281]
I have try to get more test ETH in [https://faucet.goerli.mudit.blog/](https://faucet.goerli.mudit.blog/) and [https://goerli-faucet.slock.it/](https://goerli-faucet.slock.it/), they are all not success

![2021-07-28_15-18](https://user-images.githubusercontent.com/43004977/127280853-e1292667-6362-4615-b495-fac5eac4bd1d.png)
![2021-07-28_15-19](https://user-images.githubusercontent.com/43004977/127280859-6f2c5476-c9ed-4392-afe0-64c31800af88.png)
![2021-07-28_15-20](https://user-images.githubusercontent.com/43004977/127280861-ff48addf-93b3-4f51-b358-2d4250ebeac3.png)

I have been try to connect VPN or not, all both not work

Is there arother way can i get the test ETH? i very need it to test RawTransaction, please get me some way or idea to get it

**Comment by rjl493456442** [comment]
Please open the issue in this repo https://github.com/blockchainsllc/goerli-faucet
It's not relevant with go-ethereum. Will close it now.

**Comment by ligi** [comment]
I contacted slock.it a while ago regarding the faucet - but more people pinging them could help. The faucet should also be converted to use EIP-1559. 
That said - I was just able to get funds from https://faucet.goerli.mudit.blog
But yea @rjl493456442 is correct - this is the wrong repo for this issue.

**Comment by lpf763827726** [comment]
oh, i am sorry i ask questions in the wrong repo, but i want to know where can i get more test ET in addition to these two methods

> That said - I was just able to get funds from https://faucet.goerli.mudit.blog

I've tried it, but i don't know why can't get it, i've been tweeting for a long time

**Comment by ligi** [comment]
https://goerli.etherscan.io/address/0xf60bb0461f09ac1dfe41c2fb927c05065e878f4a

**Comment by ligi** [comment]
just pasted in your tweet and it worked fine ..

**Comment by ligi** [comment]
ah - you need to put in the tweet URL - not the address

**Comment by ligi** [comment]
just saw in your screenshot you did that wrong

**Comment by ligi** [comment]
anyway you have funds now

**Comment by lpf763827726** [comment]
oh, ok, sorry, my mistake, and thanks your ETH so much
