### ISSUE TITLE
Comment unclear about what is deleted

### ISSUE THREAD

**Issue by noslav** [ethereum/go-ethereum#23298]
Hi, this comment line is unclear. What does it intend to delete? 
```
// If the snapshot is missing or the disk layer is broken, the entire `snapshot?` is deleted? 
```
https://github.com/ethereum/go-ethereum/blob/860184d54285738322ca697b1666040183e05e76/core/state/snapshot/snapshot.go#L172

**Comment by tylerchambers** [comment]
It looks like it's the snapshot that's deleted, then regenerated.

Can someone confirm? Would love to submit a quick PR for this one.

**Comment by rjl493456442** [comment]
@noslav @tylerchambers the comment is outdated. Now if the snapshot is incorrect and Geth will try to rebuild the correct one based on the "wrong" one by reusing most of the data, no deletion will happen again.
