### ISSUE TITLE
instantiate eth.EthAPIBackend from ethclient.Client?

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#23293]
hi, I want to invoke [TraceCall()](https://github.com/ethereum/go-ethereum/blob/fb8ea5993f466bd398d33a42a8273c9fc2bf1fb6/eth/tracers/api.go#L726) from my go program, to call this method, I need to instantiate [tracers.Backend](https://github.com/ethereum/go-ethereum/blob/fb8ea5993f466bd398d33a42a8273c9fc2bf1fb6/eth/tracers/api.go#L60) interface, and for that, I need to get [eth.EthAPIBackend](https://github.com/ethereum/go-ethereum/blob/fb8ea5993f466bd398d33a42a8273c9fc2bf1fb6/eth/api_backend.go#L43) which is one of the implementations of it.

but there's no function like `NewEthAPIBackend()`, how can I get it?

now I have [ethclient.Client](https://github.com/ethereum/go-ethereum/blob/fb8ea5993f466bd398d33a42a8273c9fc2bf1fb6/ethclient/ethclient.go#L35) in hand:

```go
	if client, err = ethclient.DialContext(context.Background(), config.App.Eth.Node); err != nil {
		logrus.Fatal( err)
	}
```

so back to the title, how do I instantiate [eth.EthAPIBackend](https://github.com/ethereum/go-ethereum/blob/fb8ea5993f466bd398d33a42a8273c9fc2bf1fb6/eth/api_backend.go#L43)  from  [ethclient.Client](https://github.com/ethereum/go-ethereum/blob/fb8ea5993f466bd398d33a42a8273c9fc2bf1fb6/ethclient/ethclient.go#L35)?

**Comment by fjl** [comment]
It's not possible to do what you are asking, because the API Backend and ethclient are two different things.
The API Backend is the server side, ethclient is the client side.

If you want to invoke tracing methods on the server, you need to call them through RPC. 

Create the RPC client like this:

```
client, err := rpc.DialContext(...)
if err != nil {
   // handle error
}
```

Now you can perform JSON-RPC calls:

```
type traceResult struct{
  Failed bool
  Gas uint64
  ReturnValue hexutil.Bytes
  StructLogs []vm.StructLog
}

var result traceResult
err := client.Call(&result, "debug_traceCall", ...)
if err != nil {
   // handle err
}
```

**Comment by fjl** [comment]
RPC documentation for this method is here: https://geth.ethereum.org/docs/rpc/ns-debug#debug_tracecall

**Comment by huahuayu** [comment]
> RPC documentation for this method is here: https://geth.ethereum.org/docs/rpc/ns-debug#debug_tracecall

thank you for your reply, I do read the document several times, but there's a table list go function to call it, that's why I ask

![image](https://user-images.githubusercontent.com/1725060/127498461-257d4705-71a8-4f65-b96f-10519024c376.png)

**Comment by fjl** [comment]
Sorry if this is confusing. The Go documentation in those tables is not accurate, it was auto-generated a long time ago.

**Comment by huahuayu** [comment]
doesn't matter, the documentation for geth, imo, is very good 👍
