### ISSUE TITLE
Fatal blockchain db error

### ISSUE THREAD

**Issue by josjo80** [ethereum/go-ethereum#2329]
I updated geth and now I keep getting the following error whenever I try to launch it in a terminal window.  I'm running OSX 10.10.3.

me:~ me$ geth console
I0312 16:27:45.225870     988 database.go:71] Alloted 16MB cache to /Users/me/Library/Ethereum/chaindata
Fatal: blockchain db err: read /Users/me/Library/Ethereum/chaindata/513486.ldb: input/output error

I have also tried to launch Mist version v0.5.1 but it will stall and crash.  Nothing is working now!

Please help!

**Comment by obscuren** [comment]
You'll need to redownload the blockchain. There seems to be some disk i/o issues that we cannot do anything about. Suggestion is that you delete the `chaindata` folder and resync (try `--fast` for a quick sync).

**Comment by obscuren** [comment]
It's likely a hardware error BTW.

**Comment by josjo80** [comment]
Thanks, Jeffrey.  It took me weeks to upload to that point so thanks for
the helpful hint on the quick sync.

**Comment by pciavald** [comment]
also had this error. I erased the whole 16GB folder, relaunched with --fast from the beginning, working like a charm.
A word of precision on the setup which had the problem : 
linux 4.2 / ubuntu mate 15.10 / geth 1.5.0-unstable (breaking happened with previous version)
~ on /dev/sda ext4 volume on SSD
~/.ethereum linked to the /dev/sdb Data HDD formatted in ntfs
