### ISSUE TITLE
human readable traceTransaction like etherscan with gethtrace2 option

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#23301]
hi, I try to trace tx by `traceTransaction`

```rpc
rpcClient.Call(&result, "debug_traceTransaction", ”$txHash")
```

It was successful, but the result is option code like this https://etherscan.io/vmtrace?txhash=0x2479b2880c5f49cfc786c7672356c7905e1c4fdd41c7a3b96251506606370efb, which is not readable. 

How can I get readable result like this https://etherscan.io/vmtrace?txhash=0x2479b2880c5f49cfc786c7672356c7905e1c4fdd41c7a3b96251506606370efb&type=gethtrace2 ?

**Comment by huahuayu** [comment]
I found here is the doc for it https://geth.ethereum.org/docs/dapp/tracing-filtered but can it be easier(with go)?

**Comment by rjl493456442** [comment]
You can use the builtin callTracer by passing the additional parameter `rpcClient.Call(&result, "debug_traceTransaction", ”$txHash", {"tracer": "callTracer"})`. Or you can investigate the js tracer a bit to customize it by yourselves.

**Comment by huahuayu** [comment]
> You can use the builtin callTracer by passing the additional parameter `rpcClient.Call(&result, "debug_traceTransaction", ”$txHash", {"tracer": "callTracer"})`. Or you can investigate the js tracer a bit to customize it by yourselves.

it works, thank you! @rjl493456442
