### ISSUE TITLE
admin.addPeer returns true but no peer is added

### ISSUE THREAD

**Issue by adligo** [ethereum/go-ethereum#2330]
Hi,

   I am trying to get a few geth instances on separate computers on a internal NAT network to talk to each other as peers with out success.   They are all on the same network i.e. 192.168.0.*, and I can ssh etc from the computers to each other.  

I see some strange info when I try;

> admin.nodeInfo
> The IP address in the enode and ip address field is NOT the IP address of the computer, but a IP of a router used by the computer on another network.   However I do see this;
> listenAddr: "[::]:30303",
> and the doc seems to indicate that [::] is the loopback 127.0.0.1.

I have tried substituting the correct ip address to create a enode URL so that I can do;

> admin.addPeer('enode://splat:IP:port')
> This returns true, however the following command returns an empty peer array;
> admin.peers
> []

I am simply trying to reduce network traffic, so that I can ACTUALLY USE MY INTERNET while mining in the following simple manor;
ISP  <-   Box A  <-  Box B  & C
In the above text diagram Box A would discover peers using the automated discovery, and Box B and C would connect to Box A to download blocks.

Is there any way to do this with geth?
It seems like a fairly simple and common Use-Case for optimizing network traffic for miners.
Large scale miners like Hashflare may want to expand on the model by having a few machines talk to public nodes, and most other mining machines talk to those few machines.

Also it seems that there should be a command line networking option to specify the IP address of the machine (used in admin.nodeInfo), if geth isn't going to use it by default.

Also, I think geth may be overstating it's hash rates significantly when large numbers are passed to 
--minerthreads.

Thanks,
Scott

**Comment by fjl** [comment]
The peer is added asynchronously.

**Comment by stiv-yakovenko** [comment]
I have the same problem and I don't know how to resolve it.

**Comment by AqeelKazmi** [comment]
#fjl How much time it takes???

**Comment by ChangWinde** [comment]
I have the same problem and I don't know how to resolve it.

**Comment by martinnaughton** [comment]
I had an issue. I was using the default ip address in the id which was 127.0.0.1 that means only nodes start on the same machine can talk to the node. Change the IP to machine that is running the other node. then they should talk to each other straight away. I had a node on my computer talking to a node on a raspberry pi. I change the ip address to one on the raspberry pi and they started talking.
`admin.addPeer('enode://splat:127.0.0.1:port')`

**Comment by martinnaughton** [comment]
I had the same issue. The issue was I was using the default ip address in the id which was 127.0.0.1 that means only nodes start on the same machine can talk to the node. It always says 127.0.0.1 when you run the command admin.nodeInfo. Change the IP to the machine that is running the node. then they should talk to each other straight away. I had a node on my computer talking to a node on a raspberry pi. I change the ip address to one on the raspberry pi and they started talking.
`admin.addPeer('enode://splat:127.0.0.1:port')`
