### ISSUE TITLE
"Head state missing, repairing

### ISSUE THREAD

**Issue by jayboy-mabushi** [ethereum/go-ethereum#23310]
My node was fully synced for some hours and then suddenly It disconnected and I got an error in the logs saying ""Head state missing, repairing" I checked geth, and it was active. Please assist

**Comment by jayboy-mabushi** [comment]
![image](https://user-images.githubusercontent.com/60149478/127775556-fc42ad2a-4a41-443f-a4af-d10e7c4d3055.png)

![image](https://user-images.githubusercontent.com/60149478/127775583-ccf206fd-a09c-453e-b0cd-397627511292.png)

**Comment by rjl493456442** [comment]
Looks like your node is restarting over and over again? Head repairing is common because of the unclean shutdown. But you are running the archive node, it shouldn't occur though.

**Comment by karalabe** [comment]
That's not a stock Geth node based on the variety of forks listed. As such, we can't support or debug it.

**Comment by jayboy-mabushi** [comment]
@r1cs how do you prevent this unclean shutdown? everytime that happens, it corrupts my db and creates and issue and I have to resync.

**Comment by jayboy-mabushi** [comment]
@rjl493456442 how do you prevent this unclean shutdown? everytime that happens, it corrupts my db and creates and issue and I have to resync.

**Comment by jayboy-mabushi** [comment]
@karalabe Please where can I find the stock geth? that might resolve all my issue.
