### ISSUE TITLE
Light client, estimating historic gas, "no suitable peers available"

### ISSUE THREAD

**Issue by xloem** [ethereum/go-ethereum#23313]
#### System information

Geth version: 1.10.6-stable
OS & Version: ubuntu 20.04

#### Expected behaviour
```
> tx =eth.getTransactionFromBlock('0xfddbc9d9a6155c54f18f83d230996366f35ead00741e082fadc71c0497f5a6ea', 83)
> eth.estimateGas({from:tx.from,to:tx.to,value:tx.value,nonce:tx.nonce,data:tx.input}, '0xfddbc9d9a6155c54f18f83d230996366f35ead00741e082fadc71c0497f5a6ea')
[a number]
```

#### Actual behaviour
```
> tx =eth.getTransactionFromBlock('0xfddbc9d9a6155c54f18f83d230996366f35ead00741e082fadc71c0497f5a6ea', 83)
> eth.estimateGas({from:tx.from,to:tx.to,value:tx.value,nonce:tx.nonce,data:tx.input}, '0xfddbc9d9a6155c54f18f83d230996366f35ead00741e082fadc71c0497f5a6ea')
Error: getDeleteStateObject (8688a84fcfd84d8f78020d0fc0b35987cc58911f) error: no suitable peers available
        at web3.js:6357:37(47)
        at web3.js:5091:62(37)
        at <eval>:1:16(20)
```

#### Steps to reproduce the behaviour

`--syncmode light`, enter above in console once connected

**Comment by karalabe** [comment]
You need to have connections to light servers. If you have no peers, there's nowhere to get the state from, so you can't estimate gas.

**Comment by karalabe** [comment]
Also, the state might have already been pruned by your peers if you ask for state data older than 15 minutes; even if you are well connected.

**Comment by xloem** [comment]
Yeah I'm well connected enough to download the historic transaction the estimate is of.  Thank you for the information on state pruning.

If you have time, is there any way to get historic state data with a light client?  Can I query peers for whether they prune?
