### ISSUE TITLE
eth.accounts does not error with index out of bounce: potentially dangerous results

### ISSUE THREAD

**Issue by MrChico** [ethereum/go-ethereum#2331]
calling eth.accounts with an index larger than the size of the array - 1 does not throw an error, only silently returns undefined. This can cause a very nasty behavior for a user that does a mistake:
```
> eth.sendTransaction({from:eth.coinbase, to: eth.accounts[1], value: 555})
I0313 19:03:37.571045   29036 xeth.go:1026] Tx(0x2ae07e94ab3490d0458cbd5c163b0c87d503f553b0ca5042114712c7186d571f) created: 0xf150a18638177831b71b7e0c91461b6c20303f21
"0x2ae07e94ab3490d0458cbd5c163b0c87d503f553b0ca5042114712c7186d571f"
```
In the example above I only have one element in eth.accounts, and so the transaction creates a new contract without any code and the ether is lost.
Check out what happpened to [this redditor](https://www.reddit.com/r/ethereum/comments/4a8c2h/geth_sent_the_transaction_to_the_wrong_address/)

**Comment by fjl** [comment]
The console implements JavaScript. Whether or not this quirky language was a good choice is anyone's guess, but array access in JavaScript does not throw for out of bound indices.

**Comment by MrChico** [comment]
Maybe scenarios like this could be avoided by not allowing the `to` field and the `data` field of a transaction both be null? Surely there is no point in allowing people to create empty contracts?

**Comment by karalabe** [comment]
@MrChico @fjl I was also pondering about this over the weekend as I think the point is valid: although a correct command, it makes no sense to create an empty contract that can be neither interacted with nor funds transferred from. Similarly to how we have special handling for the zero address, imho it would be valuable to add a special sanity check for contract creation too.

@obscuren Opinion?
