### ISSUE TITLE
why not obtain the gas and break the loop directly when gas estimation succeeds

### ISSUE THREAD

**Issue by kimroniny** [ethereum/go-ethereum#23321]
https://github.com/ethereum/go-ethereum/blob/82c508539939e025ad9f31aa784f6b4307afcbbb/internal/ethapi/api.go#L1072

why not obtain the gas and break the loop directly when gas estimation succeeds.

**Comment by rjl493456442** [comment]
Gas estimation is complicated since we try to give an accurate(as low as possible) result to users. So the binary search is applied here.

**Comment by kimroniny** [comment]
But is it necessary to continue when executable() succeeds? Is the binary search result gas not equal to the successful executable() result gas ?

**Comment by karalabe** [comment]
No, it's not. There are gas stipends (gas needed but not used during CALL descents), and gas refunds. Those make the final gas used amount not the same as needed to run the execution.
