### ISSUE TITLE
Ethereum blockchain size on mainnet

### ISSUE THREAD

**Issue by basvlanat** [ethereum/go-ethereum#23323]
Hello
We are using ethereum/client-go in the **mainnet**. We have one ethereum node that we started syncing about a year ago and gradually upgraded it from v1.9.x to **v1.10.6**, which takes up approximately **1.8TB** of disk space.
Recently we decided to sync the spare node immediately using **v1.10.6**, after the sync finished its size was **408GB**.
The question is, is the size of the occupied disk space of our spare node so normal (and what is the reason for its decrease) and can we start the synchronization again for the main node in order to save disk space?

**Comment by karalabe** [comment]
Geth does not have disk pruning implemented, so once some data is written to disk, it remains there.

While your node is running, the state is constantly garbage collected as long as it fits into RAM. But when it gets larger than the `--cache` allowance (25% of it actually), state starts to get flushed to disk to not overload the memory usage. That overflown stuff written to disk will forever stay there. Furthermore, Geth will do a full state flush after every 1h of block processing so if the process crashes, you have a checkpoint to resume from. These also stay forever on disk.

When you do a fresh sync, you are essentially pruning off all that historical spillage described above. It's completely safe to use a freshly synced node and not hold onto the old junk.

If you have snapshots generated on a node, you can prune it without doing a resync, but the node needs to be offline (`geth snapshot prune-state`).

**Comment by basvlanat** [comment]
thank you
