### ISSUE TITLE
console/console_test: channel operations found blocking forever during fuzzing

### ISSUE THREAD

**Issue by BurtonQin** [ethereum/go-ethereum#23330]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : 56e9001a1a8ddecc478943170b00207ef46109b9

#### Expected behaviour
The channel sending/receiving/select operations shall not block forever whatever the order of the concurrent messages.

#### Actual behaviour
We found 17 blocking issues by fuzzing the code from the entry point
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/console/console_test.go#L200
1.	Blocked at the sending operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/core/blockchain.go#L2292
The channel is created at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/core/blockchain.go#L2334-L2339
2.	Blocked at the two receiving operations at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/core/chain_indexer.go#L211-L217
The two channels are created at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/core/chain_indexer.go#L148-L149
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/core/chain_indexer.go#L109

3.	Blocked at the two receiving operations at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/core/chain_indexer.go#L311-L317
The two channels are created at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/core/chain_indexer.go#L108-L109
4.	Blocked at the `select` operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/eth/bloombits.go#L50-L54
5.	Blocked at the `select` operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/eth/downloader/api.go#L63-L69
6.	Blocked at the `select` operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/eth/downloader/statesync.go#L83-L90
7.	Blocked at the `select` operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/eth/fetcher/tx_fetcher.go#L355-L356
8.	Blocked at the `select` operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/eth/handler.go#L524-L534
9.	Blocked at the `select` operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/eth/protocols/eth/discovery.go#L48-L55
10.	Blocked at the `select` operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/eth/sync.go#L134-L153
11.	Blocked at the `select` operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/internal/jsre/jsre.go#L173-L176
12.	Blocked at the `select` operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/miner/worker.go#L454-L458
13.	Blocked at the `select` operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/p2p/dial.go#L243-L244
14.	Blocked at the `select` operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/p2p/server.go#L714-L715
15.	Blocked at the `select` operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/rpc/client.go#L561-L566
16.	Blocked at the receiving operation at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/rpc/server.go#L86-L88
17.	Blocked at the for range channel at
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/eth/handler.go#L512-L521

#### Steps to reproduce the behaviour
We found the blocking issues through a WIP Fuzzing project by system-pclub, PSU.

**Comment by gballet** [comment]
@BurtonQin thank you for reporting this. We need more information to reproduce this problem: what were the inputs that you used to find it? What is the protocol that you used? Are you jsut running the test repeatedly or are you modifying/instrumenting the code to figure this out?

**Comment by aridee** [comment]
Go-ethereum build​&&make​files

**Comment by songlh** [comment]
The problem is that `newTester()` can trigger a panic at [line 137](https://github.com/ethereum/go-ethereum/blob/master/console/console_test.go#L137), causing the defer in `TestInteractive()` to be skipped.
