### ISSUE TITLE
EIP1559 ETH burning

### ISSUE THREAD

**Issue by saman-pasha** [ethereum/go-ethereum#23338]
I have read some articles about EIP1559, there is an algorithm which burns ETH base fee for every block, I don't know how to issue new ones in Private Network. Is there any class or function in go ethereum which does that?

**Comment by karalabe** [comment]
ETH issuance is controlled by the consensus algorithm and the hard forks enabled on your private network. Ethash (PoW) issues ether per every block, Clique (PoA) does not. Burn are enabled only for network that enabled the London hard fork.

Geth does not support adding custom rules, so if you need own behavior, you'll need to code that up, but we don't have the capacity to support such endeavors.

**Comment by saman-pasha** [comment]
Thank you. You means that Clique Does not burn and issue or burn without issue? because I use Clique.

**Comment by karalabe** [comment]
London always burns, independent of Ethash or Clique. Clique does not issue.

**Comment by saman-pasha** [comment]
Really? What should I do after London burnt many ETH on my private network?
