### ISSUE TITLE
eth_getWork RPC call is missing block number of seed hash

### ISSUE THREAD

**Issue by jameshilliard** [ethereum/go-ethereum#2333]
The eth_getWork rpc call appears to be missing the block number of the seed hash needed to compute a DAG for mining. From reading the documentation I need two parameters to generate a DAG, a seed hash and the corresponding block number of that seed hash. Based on that the only way to generate a DAG is to make a separate RPC call such as an eth_blocknumber call and then use that to infer the block number of the seed hash, but that doesn't seem to be the right way to do this.

**Comment by sammy007** [comment]
If you are going to add block number as additional parameter for getWork response, please append in to array, not prepend for backward compatibility. Also would be cool to also get both number and difficulty from getBlockByNumber as part of getWork. Currently there is no way to get consistent result with 2 rpc calls.

**Comment by ppratscher** [comment]
I don't think the block number is required at all. You can infer the epoch for the dag from the seed hash itself, that's also how ethminer does it

**Comment by sammy007** [comment]
Epoch is epoch, I need a block number for logging.

**Comment by Visgean** [comment]
http://ethereum.stackexchange.com/questions/8341/pool-mining-how-is-dag-generation-possible-without-knowing-the-block-number if anybody knows please answer on SO.

**Comment by Visgean** [comment]
Another reason for implementing this feature is that Parity already has a 4th parameter. See https://github.com/ethcore/parity/wiki/JSONRPC-eth-module#eth_getwork
