### ISSUE TITLE
GPU Mining issue

### ISSUE THREAD

**Issue by adligo** [ethereum/go-ethereum#2334]
Hi,

  I have a card that has GPU mining issues that shouldn't as far as I can tell it has 4Gb RAM but geth only wants to use 1Gb RAM.   The gpuinfo and gpubench show as ok but when I mine I see;
 WARNING: DAG size (1392507008) larger than device max memory allocation size (1073741824).
You probably have to export GPU_MAX_ALLOC_PERCENT=95
Initialising device 0: GeForce GTX 760

   My environment variables look like this;
GPU_MAX_HEAP_SIZE=95
GO_OPENCL=true
GPU_MAX_ALLOC_PERCENT=95
export GPU_MAX_HEAP_SIZE GO_OPENCL GPU_MAX_ALLOC_PERCENT

Here are the outputs of gpuinfo and gpubench;
# geth gpuinfo
# ============ OpenCL Device Info =============

Platform id              0
Platform Name            Apple
Platform Vendor          Apple
Platform Version         OpenCL 1.2 (May 10 2015 19:38:45)
Platform Extensions      cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event
Platform Profile         FULL_PROFILE

Device OpenCL id         0
Device id for mining     0
Device Name              GeForce GTX 760
Vendor                   NVIDIA
Version                  OpenCL 1.2 
Driver version           10.4.2 310.41.35f01
Address bits             32
Max clock freq           1150
Global mem size          4294967296
Max constant buffer size 65536
Max mem alloc size       1073741824
Max compute units        6
Max work group size      1024
# Max work item sizes      [1024 1024 64]

Found 1 devices. Benchmark first GPU:       geth gpubench 0
Mine using all GPUs:                        geth --minegpu 0

geth gpubench 0
....
I0314 00:48:08.669196    1947 ethash.go:237] Done generating DAG for epoch 0, it took 3m46.828055013s
Initialising device 0: GeForce GTX 760
Starting benchmark (60 seconds)
hashes/s : 0
hashes/s : 0
hashes/s : 0
hashes/s : 0
hashes/s : 2752396
hashes/s : 2752396
hashes/s : 2752396
hashes/s : 2752396
hashes/s : 2752046
hashes/s : 2752046
hashes/s : 2752046
hashes/s : 2752046
hashes/s : 2751960
hashes/s : 2751960
hashes/s : 2751960
hashes/s : 2751960
hashes/s : 2752268
hashes/s : 2752268
hashes/s : 2752268
OK.

**Comment by fjl** [comment]
Support for GPU mining has been removed in geth 1.5.0
