### ISSUE TITLE
bn256.G2 points fail on in-place addition

### ISSUE THREAD

**Issue by coventry** [ethereum/go-ethereum#23346]
Note that this is not a security issue, since `bn256.G1.Add` is only used in `vm.runBn256Add`, and is not used in-place, there. Also, a [fix has been provided upstream](https://github.com/cloudflare/bn256/pull/12), and just hasn't been pulled in. My recommendation to fix this would be to make [these changes](https://github.com/cloudflare/bn256/pull/12/files) to to `go-ethereum`'s `cloudflare/bn256`.

A failing test is provided below, in the "Expected Behavior" section.

#### System information

Geth `version:` `geth version` => `1.15` (master) 
OS & Version: Windows/Linux/OSX
```
uname -a
Linux ubuntu-VirtualBox 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Commit hash : (if `develop`) `28ba686cb`

#### Expected behaviour

Following test of `bn256.G1` addition should pass:

```golang
func TestG2SelfAddition(t *testing.T) {
	s, _ := rand.Int(rand.Reader, Order)
	p := new(G2).ScalarBaseMult(s)
	if _, err := p.Unmarshal(p.Add(p, p).Marshal()); err != nil {
		t.Fatalf("p.Add(p, p) ∉ G₂: %v", err)
	}
}
```

#### Actual behaviour

```
ubuntu@ubuntu-VirtualBox:~/alien/go-ethereum/crypto/bn256/cloudflare$ go test -run  TestG2SelfAddition
--- FAIL: TestG2SelfAddition (0.00s)
    bn256_test.go:122: p.Add(p, p) ∉ G₂: bn256: coordinate exceeds modulus
FAIL
exit status 1
FAIL	github.com/ethereum/go-ethereum/crypto/bn256/cloudflare	0.005s
```

#### Steps to reproduce the behaviour

- Add the above test to `crypto/bn256/cloudflare/bn256_test.go` on `master`
- `go test -run  TestG2SelfAddition`

#### Backtrace

N/A

**Comment by holiman** [comment]
Yup, I agree. Would you mind making a PR with the change + testcase ? If not, that's fine too, we'll get it it ourselves eventually

**Comment by gballet** [comment]
So the issue wasn't just with the suggested fix, it came out of the unmarshalling code, which I have also updated.

**Comment by coventry** [comment]
Ah, sorry, I missed @holiman's request. I would have been happy to do that. :) Thanks for the fix, @gballet.
