### ISSUE TITLE
Geth v1.10.6 on full sync, archive mode is slow at around 1-2 blocks per minute

### ISSUE THREAD

**Issue by jithin03** [ethereum/go-ethereum#23342]
The current block in our node is around 12.3M. It takes around 1 minute to sync a new block. Is this normal? We have updated our GETH to stay aligned with the London fork. but at this slow rate, It would take months to reach the forking block. We are running it on a K8s (8 cores and 64 GB) cluster with an Azure premium SSD of 16TB attached. Attaching the Grafana [snapshot](https://snapshot.raintank.io/dashboard/snapshot/SIgYtW46RI4M6nXs1Hv7woCzbYlDAGTX) for reference.
These are my arguments `--cache=65536 --syncmode=full --gcmode=archive --datadir=/data/eth --nousb --maxpeers=20`.
I have seen people using `--snapshot=false`. Whats change does it make?  Suggestions to improve the rate of sync are highly appreciated!

**Comment by mulatinho** [comment]
I am experiencing the same issue, here are the flags we are using: `--ipcdisable --syncmode=full --cache=4096 --maxpeers=50 --nat=none --datadir=/data/backend --port=38336 --ws --ws.addr=0.0.0.0 --ws.port=8036 --http.api=web3,eth,net,txpool,debug --gcmode=archive --txlookuplimit=0` this is becoming a nighmare where I cant awake :~

**Comment by ArseniiPetrovich** [comment]
Hey, guys. We are experiencing the very same issues here with our 2 Geth nodes (1 full and 1 archive). What makes our situation even worse is that we missed the hardfork initially, and when we realized and updated we were 7k blocks behind.
Now it's 10k blocks behind. Is there any patch or something planned? Or should we reconfigure our nodes somehow?

Here is all my config info to debug:
https://gist.github.com/ArseniiPetrovich/c7f163394a531843f1d596a1d0c2e1ec


P.S. For now I noticed that if we restart Geth node, the situation getting better for 30 mins or something, so we used this [instruction](https://stackoverflow.com/questions/31055194/how-can-i-configure-a-systemd-service-to-restart-periodically) to setup a temporary solution that restart Geth each 30 minutes, but that is definitely is just a temporary workaround.

**Comment by jithin03** [comment]
I have enabled `--snapshot=false`, increased the `--cache`, and reduced the `--maxpeers`. Now I am getting a block processing time of around 5 seconds per block hence 10 blocks are synced per minute. I still believe it is slow compared to the hardware which is provided.

**Comment by ArseniiPetrovich** [comment]
Update. My idea with restart every 30 minutes worked, I catched up with the network, however there definitely should be a better way of doing that.

**Comment by karalabe** [comment]
@ArseniiPetrovich Did your 30 min restart work on the archive or the full node?

**Comment by karalabe** [comment]
@ArseniiPetrovich @jithin03 If we give you an influxdb metrics endpoint, would you mind configuring your node for a bit to push metrics to there so we might take a look as to what it's doing?

For full nodes with huge caches, the garbage collector might be hit. It should be visible on the metrics. For archive nodes I'm not so sure.

**Comment by jithin03** [comment]
@karalabe . Please find the Grafana [snapshot](https://snapshot.raintank.io/dashboard/snapshot/WctUa5b6lgKc0QvOCFW8ILVvqKd79i83) . I was able to get the block processing time to less than 5 seconds but  guess it is still slow compared to the hardware provisioned 
`--cache=65536 --syncmode=full --gcmode=archive --datadir=/data/eth --nousb --maxpeers=20 --snapshot=false`

**Comment by karalabe** [comment]
Most of the charts are empty for me (perhaps you only exported the visible charts?). The dashboard seems also older, I think this is our newest one: https://gist.githubusercontent.com/karalabe/5b4f2639d750f8925a49cd48817370df/raw/519be0cadc11e2f5362d5c2918999aa0e6d49ea0/geth.json

**Comment by jithin03** [comment]
@karalabe Does this work https://snapshot.raintank.io/dashboard/snapshot/ENg5Z32AgyI7Lk7Nn3b0upXJwy5Wu2j9. Thank you

**Comment by taxmeifyoucan** [comment]
I have similar issue with Geth archive node. After removing `--snapshot=false`, disk usage climbs to its limits and sync is very slow, never able to reach the tip.

**Comment by ArseniiPetrovich** [comment]
> @ArseniiPetrovich Did your 30 min restart work on the archive or the full node?

Both, actually. But Archive is still catching up with the speed of around 15k blocks per day (around 10 blocks per second)

**Comment by ArseniiPetrovich** [comment]
> @ArseniiPetrovich @jithin03 If we give you an influxdb metrics endpoint, would you mind configuring your node for a bit to push metrics to there so we might take a look as to what it's doing?
> 
> For full nodes with huge caches, the garbage collector might be hit. It should be visible on the metrics. For archive nodes I'm not so sure.

Let me check with the client and get back to you :)

**Comment by jithin03** [comment]
@ArseniiPetrovich  You meant 10 blocks per minute(15K per day), aren't you? 10 blocks per second =  864K blocks per day!!! Is that even possible?

**Comment by ArseniiPetrovich** [comment]
> @ArseniiPetrovich You meant 10 blocks per minute(15K per day), aren't you? 10 blocks per second = 864K blocks per day!!! Is that even possible?

Yeah, per minute, sorry :)

**Comment by ArseniiPetrovich** [comment]
@karalabe Please, provide the details, we are okay to send our Metrics to you.
My contact details:
arsenii.petrovich@altoros.com - email
@MrCommander - telegram

Please, let me know if this does not work for you and you prefer to chat via some other mean of communication ✌️

**Comment by jithin03** [comment]
> @karalabe Please, provide the details, we are okay to send our Metrics to you.
> My contact details:
> [arsenii.petrovich@altoros.com](mailto:arsenii.petrovich@altoros.com) - email
> @MrCommander - telegram
> 
> Please, let me know if this does not work for you and you prefer to chat via some other mean of communication ✌️

@ArseniiPetrovich Please let me know if you could improve the performance (greater than 10 blocks per minute)
Discord: jithin#7645

**Comment by karalabe** [comment]
@ArseniiPetrovich I've sent an email with the credentials.

**Comment by jithin03** [comment]
![image](https://user-images.githubusercontent.com/68288007/129514801-a11a7204-604e-49c2-84eb-24437fadaf37.png)
@karalabe As you can the IOPS and throughput is very low compared to the capability of the attached disk that supports 18000 IOPS and 750 MBps throughput.

**Comment by ArseniiPetrovich** [comment]
@karalabe Have you received my metrics? Any idea on what is going on there? :)

**Comment by ArseniiPetrovich** [comment]
@karalabe We recently started another node from snapshot and it seems it still sync VERY slow. Is there any tips so far?

**Comment by holiman** [comment]
@ArseniiPetrovich looking at your charts now. Here's the archive processing

![Screenshot 2021-11-04 at 19-46-46 Single Geth - Grafana](https://user-images.githubusercontent.com/142290/140401261-2b174251-2774-4635-a5be-8138f972cbeb.png)

What seems to be slow is storage read and account read. 

The full-node is faster than the archive: 
![Screenshot 2021-11-04 at 19-49-30 Dual Geth - Grafana](https://user-images.githubusercontent.com/142290/140401568-dd999cd2-7965-46fb-83d1-a1f2b6be5c7b.png)

But that's not surprising, a non-archive node has more data in memory, whereas the archive flushes to disk very often. Mem charts: 

![Screenshot 2021-11-04 at 19-50-19 Dual Geth - Grafana](https://user-images.githubusercontent.com/142290/140401726-59c61b47-363a-43e2-8e18-e26403d4f3de.png)

I can also see that you're not using snapshots -- so yeah, there's a _lot_ of disk lookups on a non-snapshot archive node, made even worse by the fact that your leveldb database is `9TB` for the archive.

I don't really see anything here which is a _bug_ per se. Running an archive node is extremely IO heavy. 

However, they're both way faster than 1-2 blocks per minute, as the title says -- the mean for the archive seems to be 1 block per second.

**Comment by holiman** [comment]
Oh yeah, sorry for not following up on this sooner, and thanks for configuring the nodes so we could investigate it bit closer.

**Comment by ArseniiPetrovich** [comment]
Hey, @holiman, thank you for taking a look there! Well, after the node is synced up there are no problems with them, and that is what you are seeing, the node behaves really well when synced. Do you happen to have the data for the period prior to full synchronization? I just don't think we are ready to force our node to fall back behind the chain once again to check the sync process.

Other questions:
1) If I enable snapshots - this will speed up the sync? Will the node remain archive in that case?
2) Are you saying that the bottleneck is the disk IOPS currently?

**Comment by j4ys0n** [comment]
Does this essentially come down to disk IOPS?

**Comment by holiman** [comment]
Closing this, it's stale by now
