### ISSUE TITLE
tests do not close all channels (rjeczalk/notify) 

### ISSUE THREAD

**Issue by charlesxsh** [ethereum/go-ethereum#23354]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Properly close/exit all channel and goroutine

#### Actual behaviour
During or at the end of the test `TestPasswordValidation` in file `signer/core/validation_test.go`

two blocking issue found at:
github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:36
```go
func (t *nonrecursiveTree) dispatch(c <-chan EventInfo) {
	for ei := range c {      <-------- line 36
		dbgprintf("dispatching %v on %q", ei.Event(), ei.Path())
		go func(ei EventInfo) {
			var nd node
```

github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:81
```go
func (t *nonrecursiveTree) internal(rec <-chan EventInfo) {
	for ei := range rec {    <---------- line 81
		t.rw.Lock()
		if ei.Event() == Remove {
			nd, err := t.root.Get(ei.Path())
```

The only usage of notify is in `accounts/keystore/watch.go`. Since  test `TestPasswordValidation ` does not explicitly create related resource, I assume it is created by the variables in its package `signer/core`.

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by ligi** [comment]
This is a behavior of the library and not a problem as we see it.
