### ISSUE TITLE
always crash when sync data

### ISSUE THREAD

**Issue by leafan** [ethereum/go-ethereum#23367]
hi,

when we do sync data, it will be panic after 1-2 hours, and always be this error:

INFO [08-09|05:03:30.827] Starting Geth on Ethereum mainnet...
INFO [08-09|05:03:30.827] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [08-09|05:03:30.830] Maximum peer count                       ETH=600 LES=0 total=600
WARN [08-09|05:03:30.830] The flag --rpcapi is deprecated and will be removed June 2021, please use --http.api
INFO [08-09|05:03:30.830] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [08-09|05:03:30.830] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x487e87]

goroutine 64615872 [running]:
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).NewPendingTransactionFilter.func1(0xc1a090b500, 0xc183877680, 0xc09c15cd50, 0xc000d96a80)
	github.com/ethereum/go-ethereum/eth/filters/api.go:128 +0x1bd
created by github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).NewPendingTransactionFilter
	github.com/ethereum/go-ethereum/eth/filters/api.go:124 +0x1bb

geth version: v1.1.0

Thanks.

**Comment by rjl493456442** [comment]
You say that you are using `geth version: v1.1.0`, is it `geth version: v1.10.0`?. 

Anyway can you upgrade to the latest version? If you are running the ethereum mainnet, v1.10.6 is required.

**Comment by leafan** [comment]
> You say that you are using `geth version: v1.1.0`, is it `geth version: v1.10.0`?.
> 
> Anyway can you upgrade to the latest version? If you are running the ethereum mainnet, v1.10.6 is required.

ok, thanks, will try.
