### ISSUE TITLE
Geth geth snapshot prune-state Fails on Windows

### ISSUE THREAD

**Issue by mtbitcoin** [ethereum/go-ethereum#23364]
There is a file permission issue when attempting to run prune on windows. The same command works with linux.

INFO [08-09|12:52:17.527] Iterating state snapshot                 accounts=142,211,936 slots=481,586,538 elapsed=24m16.894s eta=26.174s
INFO [08-09|12:52:25.535] Iterating state snapshot                 accounts=142,211,936 slots=483,658,037 elapsed=24m24.903s eta=16.735s
INFO [08-09|12:52:33.542] Iterating state snapshot                 accounts=142,211,936 slots=485,726,511 elapsed=24m32.909s eta=7.629s
INFO [08-09|12:52:41.129] Iterated snapshot                        accounts=142,211,936 slots=487,500,091 elapsed=24m40.496s
INFO [08-09|12:52:44.357] Writing state bloom to disk              name=C:\Users\Administrator\AppData\Local\Ethereum\geth\statebloom.0x465478226afe866cffe49903dde67846ccfcb175b6a0bb4444c1b4b507427193.bf.gz
ERROR[08-09|12:53:55.372] Failed to prune state                    err="sync C:\\Users\\Administrator\\AppData\\Local\\Ethereum\\geth\\statebloom.0x465478226afe866cffe49903dde67846ccfcb175b6a0bb4444c1b4b507427193.bf.gz.tmp: Access is denied."
sync C:\Users\Administrator\AppData\Local\Ethereum\geth\statebloom.0x465478226afe866cffe49903dde67846ccfcb175b6a0bb4444c1b4b507427193.bf.gz.tmp: Access is denied.

**Comment by karalabe** [comment]
Out of curiosity, what file system are you using? Just to make sure, it's NTFS + a 64 bit machine, right?

**Comment by mtbitcoin** [comment]
NTFS and 64 bit, so its not an OS limitation. This might be a permission issue 
![image](https://user-images.githubusercontent.com/8327464/128823094-ec2fee9e-e367-4c7b-84c2-740ddcfd02c8.png)

**Comment by karalabe** [comment]
Do you have any special things in your file system? Remote mappings? Redirections? Profiles syncing off of and onto some user server?

Based on the logs the file was written successfully. Then closed successfully. Afterwards when we try to open and sync the file, the sync operation fails. That seems very strange.

**Comment by karalabe** [comment]
Hmm, `Open` opens the file read only. Wondering if on Windows it's not allowed to call Sync on a read only file?

**Comment by mtbitcoin** [comment]
I am not familiar with geth but ...Line 93 ?

**Comment by karalabe** [comment]
Yeah, a similar issue was raised on some nodejs repo too, that readonly-sync works on maxos/linux, but not on Windows (https://github.com/nodejs/node/issues/3879). There they say a change to open for write does fix the issue. We can do that I guess.

**Comment by karalabe** [comment]
@mtbitcoin Could you check if the following diff fixes it for you?

```diff
diff --git a/core/state/pruner/bloom.go b/core/state/pruner/bloom.go
index 4aeeb176e..1cd03cf53 100644
--- a/core/state/pruner/bloom.go
+++ b/core/state/pruner/bloom.go
@@ -90,7 +90,7 @@ func (bloom *stateBloom) Commit(filename, tempname string) error {
                return err
        }
        // Ensure the file is synced to disk
-       f, err := os.Open(tempname)
+       f, err := os.OpenFile(tempname, os.O_RDWR, 0666)
        if err != nil {
                return err
        }
```

**Comment by mtbitcoin** [comment]
For credit, the line 93 file open was discovered and pointed out by Fudong who works on the BSC geth as we were running into similar issues there.

**Comment by holiman** [comment]
Technically, `Sync` does (potentially) modify the file, so it "makes sense" to open in in `rw` mode anyway.

**Comment by karalabe** [comment]
Can confirm that the fix still works on Linux. So it's down to a Windows confirm and we can ship it.

**Comment by karalabe** [comment]
> Technically, `Sync` does (potentially) modify the file, so it "makes sense" to open in in `rw` mode anyway.

Well, it doesn't in theory. In practice it updates the access time on Windows, and that's probably what breaks.
