### ISSUE TITLE
incorrect baseFee check in debug_traceCall

### ISSUE THREAD

**Issue by bgelb** [ethereum/go-ethereum#23377]
#### System information

Geth version: 1.10.6
OS & Version: Ubuntu 20.04
Commit hash : n/a

#### Expected behaviour

When I use debug_traceCall to simulate a call on top of base block N, I expect the maxFeePerGas in my simulated call to be checked against the baseFeePerGas of block N+1 (i.e. the block that would contain my simulated call if it were included in a block)

#### Actual behaviour

It appears that my simulated call has its maxFeePerGas checked against the baseFeePerGas of block N (i.e. the block I am executing the call on top of) not block N+1 (the block that would contain my call if it were included in a block).

In a case where the baseFeePerGas will decrease in the N+1 block, and the call args contain a maxFeePerGas that is greater than or equal to the block N+1 baseFeePerGas, but less than the block N baseFeePerGas, debug_traceCall will return an error indicating the maxFeePerGas in the call is smaller than the required baseFeePerGas.

Looking at the code, we can see that the baseFee of the base block (N) is used:
https://github.com/ethereum/go-ethereum/blob/686b2884ee3e17fed83c56f7f3515da2897e8d6e/eth/tracers/api.go#L758

This line probably needs to incorporate an invokation of CalcBaseFee:
https://github.com/ethereum/go-ethereum/blob/94451c2788295901c302c9bf5fa2f7b021c924e2/consensus/misc/eip1559.go#L55

#### Steps to reproduce the behaviour

set the maxFeePerGas in the call args being passed to debug_traceCall to be less than the baseFeePerGas of the block passed to debug_traceCall ("block N") but greater than or equal to the expected baseFeePerGas of the block which would contain the call if it were executed and included into a block ("block N+1").

**Comment by rjl493456442** [comment]
The debug_traceCall means do the tracing for call in the block X. It's the expected behavior.

**Comment by rjl493456442** [comment]
I opened the PR for fixing the doc https://github.com/ethereum/go-ethereum/pull/23378

**Comment by gballet** [comment]
#23378 merged

**Comment by bgelb** [comment]
Hmm. This seems odd. It's not very obvious to me what use case would desire that behavior, but perhaps I am just unaware of it. I generally think of a call as allowing the simulation of a function call. But I'm not sure of the concept of "within a block" or why that is useful. Any yet-to-be-executed function call would have to be placed into the next block after the current one.

Perhaps it would make sense to at least mirror the behavior of eth_call?

Per the code, it appears that eth_call does not do any checking of the maxFeePerGas:
https://github.com/ethereum/go-ethereum/blob/a879c42bd34e91a4e08c0247138c96957eca2b3f/internal/ethapi/api.go#L910

The "NoBaseFee" config disables the check, AIUI.

That would address the issue from my POV, and makes some amount of sense, since a call does not actually require fees in order to be executed.

**Comment by bgelb** [comment]
Upon thinking about it more, I think mirroring the behavior of eth_call really is the right behavior.

I should be able to do a call with maxFeePerGas set to 0. It doesn't make sense to require gas money in the wallet in order to execute a call, which doesn't modify on-chain state. This is currently true with eth_call (because of the NoBaseFee config field I mentioned above) and it should be true with debug_traceCall as well.

I believe the GetEVM call within debug_traceCall should also have the NoBaseFee field set to true.

**Comment by bgelb** [comment]
Created issue #23382 to follow up.
