### ISSUE TITLE
debug_traceCall should not require a non-zero maxFeePerGas value

### ISSUE THREAD

**Issue by bgelb** [ethereum/go-ethereum#23382]
This issue is a spin-off of issue #23377 

#### System information

Geth version: 1.10.6
OS & Version: Ubuntu 20.04
Commit hash : n/a

#### Expected behaviour

Below is an example eth_call invocation to read the name() getter in the WETH token:

>>> web3.provider.make_request('eth_call', [{'to' : '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', 'data': '0x06fdde03'}, hex(13005659)])
{
    'id': 8,
    'jsonrpc': "2.0",
    'result': "0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000d5772617070656420457468657200000000000000000000000000000000000000"
}

I would expect I should be able to call debug_traceCall with the same call args and get a trace of the call.

#### Actual behaviour

>>> web3.provider.make_request('debug_traceCall', [{'to' : '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', 'data': '0x06fdde03'}, hex(13005659)])
{
    'error': {
        'code': -32000,
        'message': "tracing failed: fee cap less than block base fee: address 0x0000000000000000000000000000000000000000, gasFeeCap: 0 baseFee: 127426603036"
    },
    'id': 11,
    'jsonrpc': "2.0",
    'result': {
        'structLogs': []
    }
}

To work around this issue, I must specify a maxFeePerGas larger than the baseFeePerGas of the specified block, e.g.:

>>> web3.provider.make_request('debug_traceCall', [{'to' : '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', 'data': '0x06fdde03', 'maxFeePerGas' : hex(500*10**9)}, hex(13005659)])
{
    'id': 12,
    'jsonrpc': "2.0",
    'result': {
        'failed': False,
        'gas': 24174,
        'returnValue': "0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000d5772617070656420457468657200000000000000000000000000000000000000",
        'structLogs': [
            {
                'depth': 1,
                'gas': 24978936,
                'gasCost': 3,
                'memory': [],
                'op': "PUSH1",
                'pc': 0,
                'stack': [],
                'storage': {
                }
            },
<snip>

...and then it works as expected. I don't believe it makes sense to require a non-zero maxFeePerGas on a call (and eth_call does not require it) so I don't believe debug_traceCall should require non-zero maxFeePerGas either.

#### Steps to reproduce the behaviour

See above.

**Comment by bgelb** [comment]
Also noting the documentation seems to confirm that specifying a gas price should be optional (though it has not been updated for EIP1559):

From: https://geth.ethereum.org/docs/rpc/ns-debug#debug_tracecall

Object - The transaction call object

from: DATA, 20 Bytes - (optional) The address the transaction is sent from.
to: DATA, 20 Bytes - The address the transaction is directed to.
gas: QUANTITY - (optional) Integer of the gas provided for the transaction execution. eth_call consumes zero gas, but this parameter may be needed by some executions.
gasPrice: QUANTITY - (optional) Integer of the gasPrice used for each paid gas <------------------------------- optional
value: QUANTITY - (optional) Integer of the value sent with this transaction
data: DATA - (optional) Hash of the method signature and encoded parameters. For details see Ethereum Contract ABI in the Solidity documentation

**Comment by rjl493456442** [comment]
@bgelb are you sure you are using the 1.10.6? I can't find the error `fee cap less than block base fee` in our codebase. And actually the basefee check is also disabled for `debug_traceCall`. Can you please double check your version?

**Comment by bgelb** [comment]
$ geth attach http://localhost:8545
Welcome to the Geth JavaScript console!

instance: Geth/v1.10.6-stable/linux-amd64/go1.14.2
coinbase: 0x7c3e6c2544e3e4462e44530e9cda5e745c831c0b
at block: 13007784 (Wed Aug 11 2021 20:01:19 GMT-0700 (PDT))
 modules: debug:1.0 eth:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

To exit, press ctrl-d
>
