### ISSUE TITLE
When querying with logs the results doesn't include the log timestamp, how to get it?

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#23386]
Sorry if this is not a good place to ask this, but didn't get any reply on discord.

When using a code like this shouldn't the struct also include the log timestamp?
And what is the reason to exclude it?
With this implementation does it mean that I would need to run new queries for each log by the TX hash to get the timestamps?

```
abi, err := abi.JSON(strings.NewReader(TellorABI))
	if err != nil {
		return nil, errors.Wrap(err, "parse abi")
	}

	// Just use nil for most of the variables, only using this object to call UnpackLog which only uses the abi.
	bar := bind.NewBoundContract(*contract.GetAddr(), abi, nil, nil, nil)

	header, err := client.HeaderByNumber(ctx, nil)
	if err != nil {
		return nil, errors.Wrap(err, "get latest eth block header")
	}

	blocksPerHour := float64(60*60) / tEthereum.BlockTime
	lookBackDelta := big.NewInt(int64(lookBackDuration.Hours() * blocksPerHour))
	startBlock := big.NewInt(0).Sub(header.Number, lookBackDelta)

	query := ethereum.FilterQuery{
		FromBlock: startBlock,
		ToBlock:   nil,
		Addresses: []common.Address{*contract.GetAddr()},
		Topics:    [][]common.Hash{{abi.Events["NewDispute"].ID}},
	}

	logs, err := client.FilterLogs(ctx, query)
	if err != nil {
		return nil, errors.Wrap(err, "get logs")
	}

	var unpackedLogs []*DisputeLog
	for _, logRaw := range logs {
		log := TellorNewDispute{}
		err := bar.UnpackLog(&log, "NewDispute", logRaw)
		if err != nil {
			return nil, errors.Wrap(err, "unpack event from logs")
		}

		logUnpacked, err := GetDisputeInfo(ctx, log.DisputeId, contract)
		if err != nil {
			return nil, errors.Wrap(err, "getting dispute details")
		}
		logUnpacked.TxHash = logRaw.TxHash
		unpackedLogs = append(unpackedLogs, logUnpacked)

	}
	return unpackedLogs, err
```

**Comment by krasi-georgiev** [comment]
Just noticed that even the transaction type doesn't expose time

**Comment by karalabe** [comment]
You could retrieve the block and get the timestamp from there?

**Comment by krasi-georgiev** [comment]
do you mean `BlockByHash` and then `types.Block.Time()`?

and do you know what is the reason to just not include it in the logs?

**Comment by s1na** [comment]
> not include it in the logs to avoid the extra query?

I'm guessing cause it's redundant data. The same question can be asked of every other block header field, but including them all in the logs seems a bit unnecessary.

**Comment by krasi-georgiev** [comment]
but for big queries this means 2x quriery count - first query the logs and then query the time for the logs.

**Comment by Sunset17** [comment]
> but for big queries this means 2x quriery count - first query the logs and then query the time for the logs.

I agree just show the time stamp

**Comment by holiman** [comment]
The logs doesn't have the time. If we want to serve time with the logs, then we need to lookup the time on the block in the database. 
Yes, you need to do 2x the query time, but otherwise, geth would _always_ internally have to do that extra lookup to serve a log.

**Comment by krasi-georgiev** [comment]
yep I get it, it is a tradeoff.

**Comment by Sunset17** [comment]
So I know this isn’t maybe the right place to ask but there are a lot of very smart people on here. So I was a idiot and got taken advantage of and let’s say lost 1.5 Etherium which is a lot of $ to me. So I told etherscan and they reached out to me via email and said yes there was a scammer and they put a lot of Etherium back out of the person who was bad. They sent me the chain or block and contract but I can’t seem to figure out how to put it in my wallet. I just want my share back. I think I did a good thing so other people can also get there’s back. Can I get a little help please
