### ISSUE TITLE
RPC with HTTPS support

### ISSUE THREAD

**Issue by axic** [ethereum/go-ethereum#2339]
Sorry if this was raised before.

Would it be possible to support HTTPS RPC?  Is there any reason not to?

My use case: I want to use a local node with a https based site. That is simply denied because of CORS rules (http vs https).

There is a simple call [ListenAndServeTLS](https://golang.org/pkg/net/http/#Server.ListenAndServeTLS) in the go http library, although it doesn't support the `Listener` argument as `Serve` does: https://github.com/ethereum/go-ethereum/blob/master/rpc/comms/http.go#L175-l190

**Comment by fjl** [comment]
If you want to use it through https, you'll need to set up a proxy.

**Comment by axic** [comment]
I understand that, but is that something I should require from a simple end user?

**Comment by fjl** [comment]
The hard part is configuring it. We'd need to provide all kinds of options (key, cert, ciphers, etc.) and constantly keep an eye on TLS security issues.

If you want to want to use a secure channel for communicating with a node on the same machine, you can use the IPC socket.
