### ISSUE TITLE
gethclient accesslist error when eth_createAccessList returns null storageKeys

### ISSUE THREAD

**Issue by VieYang** [ethereum/go-ethereum#23399]
#### System information

Geth version: `v1.10.6`
OS & Version: Linux
Git Commit: 576681f29b895dd39e559b7ba17fcd89b42e4833

#### Expected behaviour

use gethclient `CreateAccessList` to call `eth_createAccessList` and get the access list.

#### Actual behaviour

Just follow #23233, when eth_createAccessList returns null storageKeys, the gethclient can't handle it.

Then got the error:

```
missing required field 'storageKeys' for AccessTuple
```

#### Steps to reproduce the behaviour

call `eth_createAccessList` and it return `null` as storageKeys.

#### Backtrace

`core/types/gen_access_list.go` can't use `StorageKeys` as null: https://github.com/ethereum/go-ethereum/blob/0a68558e7e025afebf67b81bf48ecb8b0fa7c06d/core/types/gen_access_tuple.go#L38

**Comment by MariusVanDerWijden** [comment]
This should be solved in 1.10.7 in this commit: https://github.com/ethereum/go-ethereum/commit/2faf796d2a502ef6d3c02681a649bd3f41999ccc
as we don't return null storage keys anymore

**Comment by VieYang** [comment]
ok, thank you.
