### ISSUE TITLE
Cannot find package "github.com/ethereum/go-ethereum/ethereum"

### ISSUE THREAD

**Issue by hackappcom** [ethereum/go-ethereum#234]
root@slb-client1:~# uname -a
Linux slb-client1 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

root@slb-client1:~# export GOPATH=/home/user/gocode
root@slb-client1:~# go get -u github.com/ethereum/go-ethereum/ethereum
package github.com/ethereum/go-ethereum/ethereum
        imports github.com/ethereum/go-ethereum/ethereum
        imports github.com/ethereum/go-ethereum/ethereum: cannot find package "github.com/ethereum/go-ethereum/ethereum" in any of:
        /usr/lib/go/src/pkg/github.com/ethereum/go-ethereum/ethereum (from $GOROOT)
        /home/user/gocode/src/github.com/ethereum/go-ethereum/ethereum (from $GOPATH)

**Comment by zelig** [comment]
which version and branch? wait till later today you can use the new releasoid on the 
develop branch

**Comment by obscuren** [comment]
`go get github.com/ethereum/go-ethereum/cmd/ethereum`

**Comment by hackappcom** [comment]
thanks!
