### ISSUE TITLE
Goerli Authenticated Faucet:  No Ethereum Address Found

### ISSUE THREAD

**Issue by jsjfbj** [ethereum/go-ethereum#23403]
So I clearly have published a public post with a valid ethereum address, but it says no ethereum address found.
https://www.facebook.com/shijie.jiang.39142/posts/879906986240966

**Comment by MariusVanDerWijden** [comment]
THere's currently an issue with reading facebook posts as their API got a bit more restrictive.
For a quick fix you should use twitter to authenticate
