### ISSUE TITLE
Account balance and blockNumber disappear after restarting geth

### ISSUE THREAD

**Issue by MrWiffer** [ethereum/go-ethereum#23402]
#### System information

Geth version: `geth 1.10.7`
OS & Version: Linux, Ubuntu 18.04 LTS

#### Expected behaviour
When I use the command line `geth --nodiscover --identity "my etherum" --rpc --rpccorsdomain "*" --datadir ./data --port "30303" --rpcapi "db,eth,net,web3" --networkid 10 --allow-insecure-unlock console 2>>geth.log` to restart geth, the `eth.blockNumber()` should returns the block number I've digged out, and the balances of accounts should not be ZERO because I indeed `miner.start()` and `eth.sendTransaction()` first time.

#### Actual behaviour
Whenever I start geth the second time, there is the problem. 

#### Steps to reproduce the behaviour
1. Init with`geth --datadir ~/privatechain/data init genesis.json`;
2. Start geth with the commadn line I used above;
2. Create new accounts, like A(as coinbase) and B;
3. A dig out some new blocks, and send several ETH to B;
4. exit, and then restart. We will find the problem: eth.blockNumber() returns 0, but eth.getBlock(1 or 2 ...) returns proper block. And balances of accounts become 0.
#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
Make sure you are shutting down Geth gracefully. Otherwise the state is cache in memory and will be lost.

**Comment by holiman** [comment]
No response for two months, closing this. Feel free to reopen if it's still an issue. Also, please provide more logs, if so, of upstart and shutdown.
