### ISSUE TITLE
see

### ISSUE THREAD

**Issue by sirpenev** [ethereum/go-ethereum#23407]

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!

**Comment by Sunset17** [comment]
Ok so being taking advantage of and falsely broadcast all over YouTube and taking tens of thousands of dollars from people by scamming them isn't a real issue wow ok
