### ISSUE TITLE
eth.blockNumber 0 after geth update

### ISSUE THREAD

**Issue by bogdangainusa** [ethereum/go-ethereum#23405]
After updating geth from v.1.10.2 to v.1.10.6 geth eth.blockNumber is returning 0 all the time. Update was done more than 2 weeks before and before this eth.blockNumber was returned properly. 

Tried to restart geth, increase max peers and server specs but this didn't helped so far. 

`------------ GETH SYNCING PROGRESS
progress: 99.99915613018487 %
blocks left to parse: 110
current Block: 13035076 of 13035186

> eth.blockNumber;
0
> eth.syncing;
{
  currentBlock: 13035076,
  highestBlock: 13035187,
  knownStates: 1004481264,
  pulledStates: 1004319180,
  startingBlock: 13001938
}
> eth.pendingTransactions;
[]
`

Geth version: geth v.1.10.6
OS & Version: Debian 10

Expected behaviour: eth.blockNumber should return actual blockNumber
Actual behaviour: eth.blockNumber return 0 all the time
![11111](https://user-images.githubusercontent.com/13803843/129543447-a27cf2c2-4b28-49d0-b4ef-091b1fa6b2d3.png)

**Comment by aghamir** [comment]
I encounter the same issue. As I understand, this happens in `fast` mode. Moreover, [blockbook](https://github.com/trezor/blockbook/) will not work with `fast` mode as it returns blockNumber as zero.

**Comment by MariusVanDerWijden** [comment]
We only return the blocknumber for which we have the _full_ state. As long as you are not synced, the highest block that you have the full state for is the genesis block. So your node will always return 0. If you are full syncing it will return the blocknumber of your current head. But since you're fast syncing it returns 0.

**Comment by bogdangainusa** [comment]
@MariusVanDerWijden  Thanks for your response.

Before update we were running geth with -fast sync and sync was done => block was returned properly.
After update we didn't changed anything - fast sync was keep and blockchain was almost at latet block into network. However chaindata is still syncing for 2 weeks and reached ~ 1.6 TB so i think there should be some issue as it's keep syncing but never reaching latest block from network.

Question: As i know from the past times if we use -fast flag, it's used by geth only on first start when chaindata is empty. After this if we restart geth fast doesn't count anymore and blockchain is syncing in normal way. Please let me know if this behaviour was changed with this latest versions.

**Comment by MariusVanDerWijden** [comment]
No that behavior is still the same, once you synced up to the head, your node switches from fast to full sync (importing every block as it arrives). If you are behind the chain too much your node switches back to fast sync. Your node is currently pulling states so its not synced. You can try to use snap sync instead which is a bit faster or wait until fast sync completed. Once your node is synced and the snapshot is generated, you can also shutdown your node and run the prune operation which will take your node from 1.6 TB to ~500GB as it will delete a lot of unnecessary data.

**Comment by aghamir** [comment]
I think returning zero in blockNumber forces people to run `full` for certain usage(As example I mentioned running blockbook). As I know, the `fast` and the `full` must behave same in most cases. Returning blockNumber is essential for a lot of applications and this update forces people to use `full` mode.

**Comment by MariusVanDerWijden** [comment]
You can always use the following logic:
if blocknumber returns 0
use eth.syncing.highestBlock
