### ISSUE TITLE
How to get TX hashes from a block that matched a bloom filter?

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#23404]
I am trying to monitor all TX to a given function in a contract that failed to monitor the cost on these.
The approach I took is to subscribe to `client.SubscribeNewHead` and use bloom filter to filter only blocks that match a given event. Now I am wondering without sending a query for each function how to figure out what is the TX index in the block that matched the filter or another way to just get the TX hash of the TX of interest. Then can use a single call to just get the receipt and record the gas if the TX has failed.
I would be interested to know if there is another way or how to make my approach work.

```
subs, err := self.client.SubscribeNewHead(ctx, events)
..
...
case event := <-events:
	if event.Bloom.Test(abi.Events["NonceSubmitted"].ID.Bytes()) {
		rcpt,err := client.TransactionReceipt(?????)
	}

```

**Comment by Sunset17** [comment]
https://etherscan.io/address/0xb570fa0475ff85fa9e48bc810509056ee0409bab

**Comment by Sunset17** [comment]
0xfa65c321d63fc59563d14c55c5ee0f6c41b92c12c8b340f8aebed2744ec93c4f

**Comment by Sunset17** [comment]
https://etherscan.io/address/0xb570fa0475ff85fa9e48bc810509056ee0409bab

**Comment by krasi-georgiev** [comment]
ping :)

**Comment by krasi-georgiev** [comment]
I got it, you need to run another query to get the full block and match the TX function signature

```
block, err := self.client.BlockByHash(self.ctx, event.Hash())
for _, tx := range block.Transactions() {
	if len(tx.Data()) > 0 && bytes.Equal(tx.Data()[:4], abi.Methods["submitMiningSolution"].ID[:4])	
	{
       ....
	}
}
```

**Comment by krasi-georgiev** [comment]
re-opening as this is easy to break when people use custom function signatures.

Is there no way to get the logs that match a bloom filter without getting TX receipts for all TX in a block?

this is to save hundreds of calls to `eth_getTransactionReceipt` for each block

**Comment by krasi-georgiev** [comment]
ping

**Comment by krasi-georgiev** [comment]
ping

**Comment by Athayde3586** [comment]
I don't they belong to owner me

**Comment by jsvisa** [comment]
How about obtaining a filter for Event Logs (if the function emits Events), and then retrieving the receipts for those transactions instead of filtering with tx.input? Another advantage of this approach is that if the function is called within a contract, tx.input may not be able to filter it out.

**Comment by krasi-georgiev** [comment]
sorry, didn't understand, can you give an example code?

**Comment by jsvisa** [comment]
Let's say, if we are interested with [UniswapV2 Factory's `createPair` function](https://etherscan.io/address/0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f#code)

```
    function createPair(address tokenA, address tokenB) external returns (address pair) {
        require(tokenA != tokenB, 'UniswapV2: IDENTICAL_ADDRESSES');
        (address token0, address token1) = tokenA < tokenB ? (tokenA, tokenB) : (tokenB, tokenA);
        require(token0 != address(0), 'UniswapV2: ZERO_ADDRESS');
        require(getPair[token0][token1] == address(0), 'UniswapV2: PAIR_EXISTS'); // single check is sufficient
        bytes memory bytecode = type(UniswapV2Pair).creationCode;
        bytes32 salt = keccak256(abi.encodePacked(token0, token1));
        assembly {
            pair := create2(0, add(bytecode, 32), mload(bytecode), salt)
        }
        IUniswapV2Pair(pair).initialize(token0, token1);
        getPair[token0][token1] = pair;
        getPair[token1][token0] = pair; // populate mapping in the reverse direction
        allPairs.push(pair);
        emit PairCreated(token0, token1, pair, allPairs.length);
    })
```

And this function will emit `PairCreated(token0, token1, pair, allPairs.length)`  this event, so we can subscribe to this event:

1. register a new filter, the json rpc like below:


```json
{
  "jsonrpc": "2.0",
  "method": "eth_newFilter",
  "params": [
    {
      "topics": [
        "0x0d3648bd0f6ba80134a33ba9275ac585d9d315f0ad8355cddefde31afa28d0e9"
      ],
      "fromBlock": "latest",
      "toBlock": "latest",
      "address": [
        "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
      ]
    }
  ],
  "id": 0
}
```

hint: topic `0x0d3648bd0f6ba80134a33ba9275ac585d9d315f0ad8355cddefde31afa28d0e9` is the `sha3("PairCreated(address,address,address,uint256)")`

And the go-ethereum will return a filter id such as:


```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": "0xc8454563d79f4eae949af390fa1743af"
}
```

2. We keep iterating through this filter until we find the result that interests us. json rpc as below:

```
{
  "jsonrpc": "2.0",
  "method": "eth_getFilterChanges",
  "params": [
    "0xc8454563d79f4eae949af390fa1743af"
  ],
  "id": 1
}
```


And the python code as below:


<details>
  <summary>Python code</summary>

```python
import json
from web3 import Web3
import asyncio

# add your blockchain connection information
provider_uri = ""
web3 = Web3(Web3.HTTPProvider(provider_uri))

# uniswap address and abi
uniswap_router = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
uniswap_factory = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"

uniswap_factory_abi = json.loads(
    """
[{
  "anonymous": false,
  "inputs": [
    { "indexed": true, "internalType": "address", "name": "token0", "type": "address" },
    { "indexed": true, "internalType": "address", "name": "token1", "type": "address" },
    { "indexed": false, "internalType": "address", "name": "pair", "type": "address" },
    { "indexed": false, "internalType": "uint256", "name": "", "type": "uint256" }
  ],
  "name": "PairCreated",
  "type": "event"
}]
"""
)

contract = web3.eth.contract(
    address=Web3.toChecksumAddress(uniswap_factory),
    abi=uniswap_factory_abi,
)


# define function to handle events and print to the console
def handle_event(event):
    print(Web3.toJSON(event))


# asynchronous defined function to loop
# this loop sets up an event filter and is looking for new entires for the "PairCreated" event
# this loop runs on a poll interval
async def log_loop(event_filter, poll_interval):
    while True:
        for PairCreated in event_filter.get_new_entries():
            handle_event(PairCreated)
        await asyncio.sleep(poll_interval)


# when main is called
# create a filter for the latest block and look for the "PairCreated" event for the uniswap factory contract
# run an async loop
# try to run the log_loop function above every 2 seconds
def main():
    event_filter = contract.events.PairCreated.createFilter(fromBlock="latest")
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(asyncio.gather(log_loop(event_filter, 2)))
    finally:
        # close loop to free up system resources
        loop.close()


if __name__ == "__main__":
    main()
```
</details>

**Comment by krasi-georgiev** [comment]
Yes, but the question is how can you get the TX hash that emitted this event so you can query the cost of this TX?

**Comment by krasi-georgiev** [comment]
yes this is the original problem that I am trying to solve
