### ISSUE TITLE
why api does not compatible with the older one?

### ISSUE THREAD

**Issue by fyxemmmm** [ethereum/go-ethereum#23418]
Why  your API does not compatible with the older ones while getting the block hash？？
version 1.9.9 and the latest one.
get block by block number.  client version 1.9.9 gets the wrong data.

**Comment by MariusVanDerWijden** [comment]
Version 1.9.9 was released on Dec 6, 2019. Since then we changed a lot of API. 
GetBlockByNumber for example changed due to the London hardfork which introduced the basefee in the block header.

**Comment by ligi** [comment]
PS: you can now also follow changes to the RPC API here: https://github.com/ethereum/execution-apis - things are improving!
