### ISSUE TITLE
Adding an RPC timeout parameter

### ISSUE THREAD

**Issue by domohawk** [ethereum/go-ethereum#23416]
Currently the [5s RPC timeout is hardcoded](https://github.com/ethereum/go-ethereum/blob/d60cfd2604a4615078696da20d474828be65ab70/internal/ethapi/api.go#L975). If we were to add a command line param to configure it, where should the config live?
- [P2P Config](https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/node/config.go#L109) as RpcTimeout (applies to all of http/ws/etc)
- [Top-level backend config](https://github.com/ethereum/go-ethereum/blob/d60cfd2604a4615078696da20d474828be65ab70/eth/api_backend.go#L44)
- Somewhere else?

As for why this might be useful, I'm bootstrapping initial contract state in another process using a call() via local RPC. Fetching a uint256[1000000] memory via a call() takes just under 5s, usually.

**Comment by holiman** [comment]
> Can this be closed?

Three weeks ago.
1,2, 3 closing!
