### ISSUE TITLE
Should Header.BaseFee be in GWEI or WEI?

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#23431]
`client.SuggestGasTipCap(ctx)`  returns the `tipFee` in WEI (on rinkeby this was 1000000000) and when getting the the latest header the `BaseFee` there it is in GWEI
`header, err := self.client.HeaderByNumber(ctx, nil)`
`header.BaseFee` (on renkeby this was 8)

In other words, the denominator is different so wondering if this is by design or a bug?

**Comment by MariusVanDerWijden** [comment]
No the basefee is also in wei. The basefee on a network with a lot less than 50% full blocks will drop to 7 wei. So 8 wei is actually the correct basefee
