### ISSUE TITLE
Will upgrading Solidity cause the main chain to fork

### ISSUE THREAD

**Issue by basisblock** [ethereum/go-ethereum#23432]
May I ask A question? Our company has made A (A) new chain with ETH source code, but it has not been upgraded, only supporting solidity5.0 version. Now we want to support the higher version of Solidity6.0, which will lead to the main chain bifurcation

**Comment by rjl493456442** [comment]
Rebase your branch with latest Geth's master branch. You are supposed to maintain your stuff.

**Comment by MariusVanDerWijden** [comment]
Usually not, newer versions might use new opcodes that the old chain does not support though. So it would be best if you hardforked your chain to London which for example provides the BASEFEE opcode

**Comment by galaxy0x** [comment]
> 通常不会，新版本可能会使用旧链不支持的新操作码。因此，最好将您的链硬分叉到伦敦，例如提供 BASEFEE 操作码

Isn't this a fork?

**Comment by basisblock** [comment]
> Usually not, newer versions might use new opcodes that the old chain does not support though. So it would be best if you hardforked your chain to London which for example provides the BASEFEE opcode

If I don't consider the London chain, I only need to support 5.0 to 6.0, will it fork?

**Comment by galaxy0x** [comment]
> 通常不会，新版本可能会使用旧链不支持的新操作码。因此，最好将您的链硬分叉到伦敦，例如提供 BASEFEE 操作码

How to avoid forks？

**Comment by MariusVanDerWijden** [comment]
Changing solidity from 0.5 to 0.6 should work

**Comment by basisblock** [comment]
@MariusVanDerWijden The chain retains the same token and does not fork

**Comment by basisblock** [comment]
This will not lead to an EVM upgrade. Should other nodes also be upgraded
