### ISSUE TITLE
Miner is taking all ressources. CPU 100%

### ISSUE THREAD

**Issue by sami3232** [ethereum/go-ethereum#23447]
Hi, I'm struggling to find a way to reduce the consumption of my miner on full archive node. The problem is I don't really know how to do that.

#### System information

Geth version: `1.10.4`
OS & Version:  ubuntu 20.04LTS

#### Expected behaviour
Having a node mining on chain but with less cpu consumption.

#### Actual behaviour
All CPU at 100%. 

#### Steps to reproduce the behaviour
Here is the flags I used for launching geth : 
```
geth 
--http --http.addr "0.0.0.0" 
--port 30303 --http.port 8534 --http.corsdomain="*" --http.vhosts="*" 
--ws --ws.addr "0.0.0.0" --ws.port 8534 
--datadir ~/sidechain_data 
--networkid 888888888888 
--rpc.allow-unprotected-txs 
--syncmode "full" --gcmode=archive 
--http.api "debug,eth,net,web3,personal,miner,txpool" 
--ws.api "debug,eth,net,web3,personal,miner,txpool" --ws.origins "*" 
--mine --miner.etherbase 0x0123456789874563215abcdef --miner.threads=4
```
I set 4 threads to the miner but it seems that it's changing.
```
INFO Updated mining threads                   threads=1
INFO Updated mining threads                   threads=8

```
I have noticed that my node update the amount of thread  it's using is there a way to disable this option ?

**Comment by karalabe** [comment]
Are you sure your node is not exposed over the internat and someone maliciously using it to mine? There's no code in Geth to automatically switch mining threads. Do you have any more logs?

**Comment by sami3232** [comment]
Not sure at all but even with the nodiscover flag enabled, it takes all cpu. How can I check that my node isn't used by someone else ?

**Comment by meanming** [comment]
> Not sure at all but even with the nodiscover flag enabled, it takes all cpu. How can I check that my node isn't used by someone else ?

Simply use top command to check which process is comsuming the cpu first

**Comment by sami3232** [comment]
Yeah that's what I did before with htop command. Geth is the only process using more than 100% of CPU. I mean others are less than 1%...

**Comment by holiman** [comment]
`--http --http.addr "0.0.0.0" ` -- you're binding it to the public interface
`--rpc.allow-unprotected-txs ` -- you're allowing unlock operations
`--http.api "debug,eth,net,web3,personal,miner,txpool" ` -- and expose `personal` and `miner` and `debug` to the internet

Are you sure it's not exposed? 
> Not sure at all 

Well, with your blatantly unsafe config, you definitely should ensure that it's very very isolated. Anyone can do anything with that node, basically.

**Comment by holiman** [comment]
Maybe someone is setting the coinbase to something else, and then maximises the number of mining threads.

**Comment by holiman** [comment]
Closing this, probable cause identified and no response. Feel free to reopen if you have more information
