### ISSUE TITLE
Geth has been Looking for peers

### ISSUE THREAD

**Issue by CharlieWangA** [ethereum/go-ethereum#23458]
Start normal synchronization for the first time, after synchronization to 12964999, start Looking for peers all the time
<img width="9" alt="截屏2021-07-27 下午3 28 18" src="https://user-images.githubusercontent.com/49639433/130734090-2692a601-9c3c-461b-b5c0-0c90edeae25b.png">
<img width="177" alt="截屏2021-08-25 下午1 53 11" src="https://user-images.githubusercontent.com/49639433/130734110-5a963435-ae16-4f01-aa10-f12005e055da.png">

**Comment by CharlieWangA** [comment]
log.

<img width="1186" alt="截屏2021-08-25 下午1 53 27" src="https://user-images.githubusercontent.com/49639433/130734196-39a94948-f44e-44f8-9a5b-cef568a4539b.png">

**Comment by rjl493456442** [comment]
I guess you are using the old version Geth without london. Please upgrade your geth to latest version.

**Comment by humblecoder** [comment]
I'm having a similar issue.  After a bit of an initial sync on a fresh install, geth gets hung `Looking for peers`.  The command I'm using is as follows:

```
geth --datadir /usr/local/share/chain --nat=extip:my_ip_address --port forwarded_vpn_port --syncmode light --cache=1024 --http --metrics --maxpeers 30 --http.corsdomain "*" --networkid 1999
```

However, I'm stuck with `peercount=0` forever.  It never finds peers.

I've confirmed via a remote port checker that the VPN service is indeed forwarding the port to the exposed address and that the machine is in fact receiving it.  However, it still seems to get stuck checking for hours without success.  Am I, perhaps, missing a necessary option?
