### ISSUE TITLE
[swarm] remove [BZZ] tag from logs

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#2345]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)
#### Expected behaviour

remove the "[BZZ]" prefixing in the logs? We don't prefix log messages because they are contain the file and loc
#### Backtrace

```
[backtrace]
```

**Comment by fjl** [comment]
Fixed in #2965
