### ISSUE TITLE
Rinkeby Faucet: No Ethereum address found to fund

### ISSUE THREAD

**Issue by Jeremy-DX** [ethereum/go-ethereum#23478]
address is https://www.facebook.com/jeremy.liu.39750/posts/1230370547420596
I want to get 15eth but not works

**Comment by gary02** [comment]
same, https://www.facebook.com/garycatcathealth/posts/1285813665172742

**Comment by 01kingsmus** [comment]
I need about 15 ether cause Twitter is not working in my country Nigeria
0x98593B7C03d72B626ceDE356c5da64D500ae19D3
pls.

**Comment by hjandu01** [comment]
I keep getting this error using my twitter url, can you please fund my account 
0x6D6D0FC5713c6d4A7cec220Ef8d6E38CAF5BeE06

**Comment by MariusVanDerWijden** [comment]
closing. Facebook is unsupported by the faucet and the faucet is currently not working reliably anyway  (we're fixing it)
