### ISSUE TITLE
geth restarts from genesis at restart 

### ISSUE THREAD

**Issue by yujianFresh** [ethereum/go-ethereum#23477]
hi, everybody, i run private network in local node, it generate block well, however, when i restart the node, it generate from genesis block, full block data maybe miss. the log under here:

<img width="1029" alt="screenshot" src="https://user-images.githubusercontent.com/24457810/131061826-377f03d3-9af6-4d1f-b966-18aa475b4f91.png">

**Comment by holiman** [comment]
Please provide more info on how you start your node, and more logs. E.g. the first 100 lines or so after startup.

**Comment by holiman** [comment]
Seems you are working with a very small chain -- most recent fast block is `14`. The fast/snap sync modes don't work properly on such short chains, on failure, they want to roll back at least 64 blocks, probably more. I think the behaviour when restarting an incomplete sync on very short chain is a bit undefined, and not something we're going to investigate deeply. 

Feel free to reopen if you have more info (and a longer chain)
