### ISSUE TITLE
upgrade from 1.10.6 to 1.10.8 stucked at 13107648 block

### ISSUE THREAD

**Issue by bogerv** [ethereum/go-ethereum#23485]
geth1.10.6 node was stucked at 13107648, then update to geth 1.10.8 stilled stucked.
The blockhash (0x7263f1423866ab4054889fefcd7e9ba87e47e9c244ec155b57ffe9fbcb548952) is different with etherscan. how to revert the block data

**Comment by Davxyp** [comment]
Experiencing the same proble. I upgraded geth to version 1.10.8

```
{
  currentBlock: 13107649,
  highestBlock: 13113799,
  knownStates: 692690891,
  pulledStates: 692690891,
  startingBlock: 13111374
}
```

**Comment by bogerv** [comment]
After waiting a few hours, the latest block is synchronized.
