### ISSUE TITLE
t8ntool behavior on exception

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#23491]
Currently the t8ntool fails with error code providing no result file 
I suggest to still provide result file with an error message (--output.result)

# Rationale

I plan to feed all kinds of invalid data to t8ntool, but need feedback with an error message on what exactly went wrong. 
This is to find potential cases where t8ntool does not report an error when some of the input parameters is off bounds
like address  < or > of 20bytes, or values > 32
If I just check the return code, it is a potential false positive as I expect it fails but the tool might fail to another reason 

# Implementation

t8ntool should parse fields in input .jsons as big int and verify against ethereum protocol restrictions
in case of exception execution halts but the output file is still produced with exception string

**Comment by holiman** [comment]
Could you make an example of where it fails in a way you do not expect? It'll be easier to fix this if we have some examples of what you mean.

**Comment by winsvega** [comment]
Currently I get an error code and t8ntool execution aborted.

```
rlp: input string too long for uint64, decoding into (types.Transactions)[0](types.LegacyTx).Gas
Error: The command '/home/wins/.retesteth/default/start.sh --input.alloc /dev/shm/423ca3c5-4f6b-4145-9066-4d8565168fc6/alloc.json --input.txs /dev/shm/423ca3c5-4f6b-4145-9066-4d8565168fc6/txs.rlp --input.env /dev/shm/423ca3c5-4f6b-4145-9066-4d8565168fc6/env.json --state.fork Berlin --output.basedir /dev/shm/423ca3c5-4f6b-4145-9066-4d8565168fc6 --output.result out.json --output.alloc outAlloc.json' exited with 256 code. (stExample/bigInt, fork: Berlin, TrInfo: d: 0, g: 0, v: 0)
```

This happens when I send transaction rlp which is malformed. 
I suggest the tool treat such transaction as invalid and output unchanged pre state and error message on why the transaction is rejected. 

father more if the same issue happens when parsing env (block header) fields, it can also act as if it was rejecting the block, output the pre state unchanged.  with this I can test malicious blocks and transaction for the tool. 
but more so for HIVE  as this malicious fields are just being parsed by tool but on hive it would be represented as RLPs and imported in real environment simulation.

**Comment by holiman** [comment]
Can you provide the exact data? I don't know what's inside of `/dev/shm/423ca3c5-4f6b-4145-9066-4d8565168fc6/txs.rlp`
