### ISSUE TITLE
how to change clique consensus generate new block reward

### ISSUE THREAD

**Issue by yujianFresh** [ethereum/go-ethereum#23497]
hi everyone, now clique consensus have no new block reward, so how to change it have ?

**Comment by rjl493456442** [comment]
There is no such config for the clique block reward. But perhaps you can maintain your own fork by changing here https://github.com/ethereum/go-ethereum/blob/master/consensus/clique/clique.go#L571 

Example https://github.com/ethereum/go-ethereum/blob/master/consensus/ethash/consensus.go#L589
