### ISSUE TITLE
Online prunning

### ISSUE THREAD

**Issue by AhmadVatani** [ethereum/go-ethereum#23510]
Does Geth support online prunning??
I means, run prunning database while geth is running

**Comment by holiman** [comment]
Nope, other than the in-memory pruning we do before flushing to disk. But if it goes on disk, it's never prune (unless you do an offline pruning)

**Comment by AhmadVatani** [comment]
Is there any config for in-memory pruning??
You mean, I should download the whole data first and then do an offline pruning?
