### ISSUE TITLE
How to find the total transaction number sent to a smart contract?

### ISSUE THREAD

**Issue by HenryChe123** [ethereum/go-ethereum#23514]
How to find the total transaction number sent to a smart contract? Like what indicated by the red lines in the below figure cropped from an ethereum browser about details of a smart contract .

<img width="960" alt="屏幕截图 2021-09-01 143449" src="https://user-images.githubusercontent.com/89897998/131623707-747c0131-5c88-4e2c-9daf-1ec259b6b8cb.png">

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
