### ISSUE TITLE
is the faucet down again?

### ISSUE THREAD

**Issue by saicharan98** [ethereum/go-ethereum#23516]
i couldn't able to get test net eth from faucet, is it down? if so any idea when will it be back?
iam having a contract to deploy can anyone help me in transferring 10eth to this account: 0xc1341CE96F73f1616Db3bab267f06F1e2a76D502

@ligi can you help me with some eth?

**Comment by ligi** [comment]
I send you 4.2 - don't have so much anymore currently - you can deploy a lot of contracts with this.

**Comment by saicharan98** [comment]
received them thanks @ligi , any idea when will the faucet work?

**Comment by ligi** [comment]
should be soon - @holiman found the cause and there is a PR here #23519

**Comment by saicharan98** [comment]
ok thankyou
