### ISSUE TITLE
Epoch length in clique

### ISSUE THREAD

**Issue by osiz-blockchainapp** [ethereum/go-ethereum#23525]
Hi Everyone,
Running private node in geth. I define 'Epoch' as 30000 in genesis file, after reaching epoch length the mining will become stop.
What is the purpose of Epoch in genesis file?

Here is my genesis file:
{
  "config": {
    "chainId": 8, 
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "muirGlacierBlock": 0,
    "congress": { 
      "period": 3,  
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x0",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x1C9C380",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "alloc": {
       }
  }
}

**Comment by karalabe** [comment]
```
"congress": {
"period": 3,
"epoch": 30000
}
```

That's not a clique network. I've no idea what it is, but we can't debug custom external code.
