### ISSUE TITLE
Head state missing, always repairing

### ISSUE THREAD

**Issue by Atrovzhi** [ethereum/go-ethereum#23521]
I used geth 1.10.6 to sync mainnet, the command is here:

> nohup geth --syncmode "full" --port "10080" --cache=10240 --datadir /data1/eth00 --rpc --rpcapi db,eth,net,web3,personal,admin,miner --rpcport 8332 --rpcaddr 0.0.0.0 --rpccorsdomain "*"  --maxpeers 5  --maxpendpeers 5 --allow-insecure-unlock >> /data1/geth_output.log 2>&1 &

It was several days before, the node stopped syncing, the highest block number stopped at 13,107,650
To fix this problem, I updated geth to version 1.10.8, then the problem comes:

```
INFO [09-02|20:10:01.026] Disk storage enabled for ethash caches   dir=/data1/eth00/geth/ethash count=3
INFO [09-02|20:10:01.026] Disk storage enabled for ethash DAGs     dir=/root/.ethash            count=2
INFO [09-02|20:10:01.026] Initialising Ethereum protocol           network=1 dbversion=8
INFO [09-02|20:10:03.336] Loaded most recent local header          number=13,107,650 hash=5fdac7..2c1bc8 td=29,614,342,018,010,984,500,618 age=5d2h2m
INFO [09-02|20:10:03.336] Loaded most recent local full block      number=13,106,539 hash=dc5265..469486 td=29,605,455,730,625,869,182,141 age=6d3h16m
INFO [09-02|20:10:03.336] Loaded most recent local fast block      number=13,107,650 hash=5fdac7..2c1bc8 td=29,614,342,018,010,984,500,618 age=5d2h2m
WARN [09-02|20:10:03.337] Head state missing, repairing            number=13,106,539 hash=dc5265..469486 snaproot=efafe8..d7f9a2

```

I waited for more than 2 hours but it still kept repairing.
Should I wait for a longer time? Is this a bug? 
What can I do to solve the problem?

**Comment by karalabe** [comment]
Just to confirm, did you do a full sync initially or a fast/snap sync?

**Comment by karalabe** [comment]
Our hunch is that you did a fast/snap sync initially with an older version of Geth, and got stuck at a bad fork (there was an attack around the time of your full block). 

When you restarted explicitly in full sync mode, it started unrolling some blocks, but there's no state, so it ended up neeing to unroll to genesis.

If you indeed did snap/fast sync initially, you can run that again (i.e. don't specify --syncmode=full) to fix up the chain.

**Comment by Atrovzhi** [comment]
> Our hunch is that you did a fast/snap sync initially with an older version of Geth, and got stuck at a bad fork (there was an attack around the time of your full block).
> 
> When you restarted explicitly in full sync mode, it started unrolling some blocks, but there's no state, so it ended up neeing to unroll to genesis.
> 
> If you indeed did snap/fast sync initially, you can run that again (i.e. don't specify --syncmode=full) to fix up the chain.

I used full sync mode initially, and the command did not changed.
`nohup geth --syncmode "full" --port "10080" --cache=10240 --datadir /data1/eth00 --rpc --rpcapi db,eth,net,web3,personal,admin,miner --rpcport 8332 --rpcaddr 0.0.0.0 --rpccorsdomain "*" --maxpeers 5 --maxpendpeers 5 --allow-insecure-unlock >> /data1/geth_output.log 2>&1 &`
After I started and stopped using another directory to sync the data with fast mode, it can sync block data in full mode, but another problem (not sure if it's a bug) appeared that the block data can only sync up to blockheight 12, other block data can not be synced. If i restart the geth node, logs are shown below

> INFO [09-09|13:53:09.104] Initialising Ethereum protocol           network=1 dbversion=8
INFO [09-09|13:53:17.869] Loaded most recent local header          number=4,531,086 hash=4ea645..78b6d4 td=1,431,305,030,584,087,609,330 age=3y10mo2w
INFO [09-09|13:53:17.869] Loaded most recent local full block      number=12        hash=aac6b1..5dc88a td=222,685,158,039               age=2h20m49s
INFO [09-09|13:53:17.869] Loaded most recent local fast block      number=4,531,086 hash=4ea645..78b6d4 td=1,431,305,030,584,087,609,330 age=3y10mo2w
INFO [09-09|13:53:17.869] Loaded last fast-sync pivot marker       number=13,189,706
WARN [09-09|13:53:17.883] Head state missing, repairing            number=12         hash=aac6b1..5dc88a snaproot=efafe8..d7f9a2
INFO [09-09|13:53:17.898] Loaded most recent local header          number=4,531,086  hash=4ea645..78b6d4 td=1,431,305,030,584,087,609,330 age=3y10mo2w
INFO [09-09|13:53:17.898] Loaded most recent local full block      number=0          hash=d4e567..cb8fa3 td=17,179,869,184                age=52y5mo1w
INFO [09-09|13:53:17.899] Loaded most recent local fast block      number=12         hash=aac6b1..5dc88a td=222,685,158,039               age=2h20m49s
INFO [09-09|13:53:17.899] Loaded last fast-sync pivot marker       number=13,189,706
ERROR[09-09|13:53:17.899] Truncating ancient chain                 from=4,531,086 to=12
WARN [09-09|13:53:17.899] Rewinding blockchain                     target=12

**Comment by Quaternioneer** [comment]
@Atrovzhi, did you figure it out? I noticed I began having problems after adding `--rpc --rpccorsdomain=...`, and then I read this in the output:
`WARN [11-14|19:40:11.418] The flag --rpc is deprecated and will be removed June 2021, please use --http 
WARN [11-14|19:40:11.418] The flag --rpccorsdomain is deprecated and will be removed June 2021, please use --http.corsdomain`
I'm resyncing with http flags instead.

**Comment by Atrovzhi** [comment]
> @Atrovzhi, did you figure it out? I noticed I began having problems after adding `--rpc --rpccorsdomain=...`, and then I read this in the output: `WARN [11-14|19:40:11.418] The flag --rpc is deprecated and will be removed June 2021, please use --http WARN [11-14|19:40:11.418] The flag --rpccorsdomain is deprecated and will be removed June 2021, please use --http.corsdomain` I'm resyncing with http flags instead.

I used the version of 1.10.6 and 1.10.8, this version can still support --rpc flag. The problem happened when the syncing stopped syncing and I tried to upgrade the geth version. 
Now I'm resyncing the node using 1.10.12, and used `--http` flag, so it no longer troubles me.
I guess there may be some data crash so that the node not working correctly.And now I just want to figure out  why it happend.
Thank you all the same.

**Comment by Partoo** [comment]
same issue, how to solve it?

**Comment by MariusVanDerWijden** [comment]
This issue got quite stale over the years. I suspect that somehow the node wasn't shutdown cleanly and some data got fried. I'm going to close this for now, please reopen a new issue if you run into this again with a current version.
