### ISSUE TITLE
Node not keeping sync, giving constant warnings

### ISSUE THREAD

**Issue by jaydemyr** [ethereum/go-ethereum#23534]
Hello, I have tried to setup a full node on a ubuntu VPS, by installing ethereum through ubuntu ppa and running it.

The sync process is very inconsistent. From time to time it just stops adding new blocks, and gives lots of warnings

```
> WARN [09-05|21:32:39.066] Dropping unsynced node during sync       id=c17e0e45

ERROR[09-05|21:33:41.411] Snapshot extension registration failed   peer=a05e766c         err="peer connected on snap without compatible eth support"
WARN [09-05|21:34:07.051] Dropping unsynced node during sync       id=fd005eea1b3ea757 conn=inbound addr=13.115.75.55:22928    type=Geth/v1.9.11-stable-...
ERROR[09-05|21:34:15.378] Snapshot extension registration failed   peer=20dcc090         err="peer connected on snap without compatible eth support"
ERROR[09-05|21:34:19.666] Snapshot extension registration failed   peer=1d4fc8e3         err="peer connected on snap without compatible eth support"
ERROR[09-05|21:34:26.656] Snapshot extension registration failed   peer=8b297441         err="peer connected on snap without compatible eth support"
WARN [09-05|21:34:30.614] Dropping unsynced node during sync       id=d198ac2f33fb042d conn=dyndial addr=143.198.113.110:30303 type=Geth/v1.10.1-stable-...
WARN [09-05|21:34:40.038] Database compacting, degraded performance database=/root/.ethereum/geth/chaindata
ERROR[09-05|21:34:47.867] Snapshot extension registration failed   peer=b4ad7978         err="peer connected on snap without compatible eth support"
```

then it waits to resolve itself for a long time before continuing to sync blocks. "Dropping unsynced node" seems to be the big problem here.

Eventually it syncs. But once it does, it still seems to have some problem keeping up - eth.syncing will return false, but it's not synced properly, it's not seeing the new block data.

Important to note... my sync did not have issues before the last fork of geth client recently. It used to run just fine, what happened? Do I need to update something? I'm not sure, since I already downloaded latest version of ethereum from package manager, right? Or is that outdated already

Specs:
AMD Ryzen 5 3600 
64 GB DDR4 RAM
2x 512GB nvme ssd (combined with raid for just under 1tb storage drive)
1 gbit/s bandwidth

Geth
Version: 1.10.8-stable
Git Commit: 26675454bf93bf904be7a43cce6b3f550115ff90
Architecture: amd64
Go Version: go1.16.4
Operating System: linux

**Comment by rjl493456442** [comment]
`WARN [09-05|21:34:40.038] Database compacting, degraded performance database=/root/.ethereum/geth/chaindata
` your node is serving the heavy disk write load. 

Can you provide more logs? It's not enough for us to know the real issue.

**Comment by rjl493456442** [comment]
And also 1.10.8 is new enough to sync the ethereum mainnet.

**Comment by ligi** [comment]
Also it would be really helpful if you provide us with the flags you start geth with

**Comment by karalabe** [comment]
`WARN [09-05|21:34:40.038] Database compacting, degraded performance database=/root/.ethereum/geth/chaindata` means leveldb is shuffling the data around and everything is suspended from pretty much doing anything until it finishes. There's not much we can do, when you initially sync it throws a **lot** of data at your node so from time to time it suspends a bit to catch up.

The `Snapshot extension registration failed` is not that important, unfortunately Optimism is running nodes with `snap` but no `eth` protocol, so their nodes always try to connect and then we have to drop them. Annoying that they do this, but to prevent it we'll need a bit more data exposed via the discovery protocols.
