### ISSUE TITLE
How to run an ultra lightweight node just for monitoring txpool?

### ISSUE THREAD

**Issue by abitrolly** [ethereum/go-ethereum#23537]
The question is already asked on https://ethereum.stackexchange.com/questions/63642/how-to-get-live-mempool-transactions-whitout-full-blokchain and not answered.

Basically I want to run a node on a cheap VPS server with limited resource that will only give me standard API to request and query the state of `txpool` (how many transactions are there, which is the oldest one, etc.), WebSocket APIs for real-time tracking of transactions leaving and entering the pool, and real-time maintenance API to monitor CPU + memory usage to predict when my node is likely be killed with OOM error, or when it can't catch up with processing incoming transactions.

**Comment by MariusVanDerWijden** [comment]
It's not possible to run an ultraweight node without modifying the code.
You need to fork the code and figure out how to remove all non-txpool related functionality.
This is not something that we are going to support in go-ethereum though.

**Comment by yopoing** [comment]
> 

Hey bro, have you found a solution for this need? I also only pay attention to mempool.

**Comment by yopoing** [comment]
> @yopoing no, bro. Stopped working on it that day.

I also didn't find a solution unless modifying geth's code
