### ISSUE TITLE
Geth returns accounts outside the range with an AccountRange message (snapsync)

### ISSUE THREAD

**Issue by matkt** [ethereum/go-ethereum#23536]
#### System information

Geth
Version:1.10.9-unstable-f85cf722-20210831
Go Version: go1.14.2

#### Expected behaviour

This is related to the snapsync feature (AccountRange (0x01) message)

When Geth must send the accounts between a specific range it does not abort until the threshold is exceeded

For example with this range Geth will return this account `15fe21a58c543f2e3222d7b56672a8230072871c155caffe5199d4c657b987c8` 

>Start : 0000000000000000000000000000000000000000000000000000000000000000
Limit : 0fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

During my test there was no account in this range. For me in this case we have 0 account with only the proof of the startHash

#### Actual behaviour

Currently Geth returns the first account outside the range and also waits for the other nodes to behave the same way otherwise it returns an error "more entries available"

#### Steps to reproduce the behaviour

- Create a local testnet with this genesis

```json
{
    "config": {
        "chainId": 1981,
        "clique": {
          "period": 3,
          "epoch": 30000
        },
        "homesteadBlock": 0,
        "daoForkBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "constantinoplefixblock": 0
    },
    "difficulty": "0x400",
    "extraData":"0x0000000000000000000000000000000000000000000000000000000000000000b6f99ef9b72d00bfe65f589e276c90c12fecf18d0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "gasLimit":"0x1312D00",
    "alloc": {
        "fe3b557e8fb62b89f4916b721be55ceb828dbd73": {
          "privateKey": "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63",
          "balance": "90000000000000000000000"
        },
        "627306090abaB3A6e1400e9345bC60c78a8BEf57": {
          "privateKey": "c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
          "balance": "90000000000000000000000"
        },
        "f17f52151EbEF6C7334FAD080c5704D77216b732": {
          "privateKey": "ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f",
          "balance": "90000000000000000000000"
        },
        "b8c3bfFb71F76BeE2B2f81bdBC53Ad4C43e3f58E":{
          "privateKey": "daa230fc01f963d8694d9206504657bc58063dc7df9449b00c0026628fbdc50d",
          "balance": "90000000000000000000000"
        },
        "E196880719eBF05646D89C498f97d2722DE66799":{
          "privateKey": "e8fc2bec79911ea75c19bfb99f2b80f74587b283b984585e4efa3f50e633a6c9",
          "balance": "90000000000000000000000"
        }
    }
}
```

- Use this stateroot `0xffba60953a4dde508f482a5fbce54055e210b6f43f84edb618451b8d389e8ab4`

**Comment by holiman** [comment]
Can confirm: on the server side, we don't abort until we've exceeded the threshold: https://github.com/ethereum/go-ethereum/blob/master/eth/protocols/snap/handler.go#L195. 

I guess the question is why we demand the server to act that way.

I think there's a reason for that, but I'm not 100% sure why at the moment. We might have to either modify our implementation to be more according to spec, or update the spec (plus add the reasoning behind it) -- cc @karalabe .

**Comment by holiman** [comment]
Repro for geth: https://github.com/holiman/go-ethereum/commit/0375b2fb90ed73604391a7fc502ae909312fe453

**Comment by karalabe** [comment]
Hmm, the `Limit` fields are not even in the `snap/1` spec. I guess that was a later optimization and I forgot to add them, which might explain the funky behavior of requiring at least 1 returned item (since there was no end limit defined when I originally implemented snap).

**Comment by karalabe** [comment]
My guess is that I wanted to forbid returning no data for a request originally.

With the Limit extension, we might be able to allow empty replies with a non-existence limit proof. Guess it might have been one more corner case that I maybe didn't want to bother implementing?

**Comment by matkt** [comment]
Hi thanks for your feedback. So how we can move forward on that. Do we want to just update the documentation ?

**Comment by holiman** [comment]
Spec updated, closing this

**Comment by popeda97** [comment]
> #### System information
> Geth Version:1.10.9-unstable-f85cf722-20210831 Go Version: go1.14.2
> 
> #### Expected behaviour
> This is related to the snapsync feature (AccountRange (0x01) message)
> 
> When Geth must send the accounts between a specific range it does not abort until the threshold is exceeded
> 
> For example with this range Geth will return this account `15fe21a58c543f2e3222d7b56672a8230072871c155caffe5199d4c657b987c8`
> 
> > Start : 0000000000000000000000000000000000000000000000000000000000000000
> > Limit : 0fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
> 
> During my test there was no account in this range. For me in this case we have 0 account with only the proof of the startHash
> 
> #### Actual behaviour
> Currently Geth returns the first account outside the range and also waits for the other nodes to behave the same way otherwise it returns an error "more entries available"
> 
> #### Steps to reproduce the behaviour
> * Create a local testnet with this genesis
> 
> ```json
> {
>     "config": {
>         "chainId": 1981,
>         "clique": {
>           "period": 3,
>           "epoch": 30000
>         },
>         "homesteadBlock": 0,
>         "daoForkBlock": 0,
>         "eip150Block": 0,
>         "eip155Block": 0,
>         "eip158Block": 0,
>         "byzantiumBlock": 0,
>         "constantinopleBlock": 0,
>         "constantinoplefixblock": 0
>     },
>     "difficulty": "0x400",
>     "extraData":"0x0000000000000000000000000000000000000000000000000000000000000000b6f99ef9b72d00bfe65f589e276c90c12fecf18d0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
>     "gasLimit":"0x1312D00",
>     "alloc": {
>         "fe3b557e8fb62b89f4916b721be55ceb828dbd73": {
>           "privateKey": "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63",
>           "balance": "90000000000000000000000"
>         },
>         "627306090abaB3A6e1400e9345bC60c78a8BEf57": {
>           "privateKey": "c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
>           "balance": "90000000000000000000000"
>         },
>         "f17f52151EbEF6C7334FAD080c5704D77216b732": {
>           "privateKey": "ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f",
>           "balance": "90000000000000000000000"
>         },
>         "b8c3bfFb71F76BeE2B2f81bdBC53Ad4C43e3f58E":{
>           "privateKey": "daa230fc01f963d8694d9206504657bc58063dc7df9449b00c0026628fbdc50d",
>           "balance": "90000000000000000000000"
>         },
>         "E196880719eBF05646D89C498f97d2722DE66799":{
>           "privateKey": "e8fc2bec79911ea75c19bfb99f2b80f74587b283b984585e4efa3f50e633a6c9",
>           "balance": "90000000000000000000000"
>         }
>     }
> }
> ```
> 
>  * Use this stateroot `0xffba60953a4dde508f482a5fbce54055e210b6f43f84edb618451b8d389e8ab4`
