### ISSUE TITLE
Geth stops unexpectedly: Killed

### ISSUE THREAD

**Issue by EkremSel** [ethereum/go-ethereum#23539]
#### System information

Geth version: `1.10.8`
OS & Version: Linux/ Ubuntu 20.10
Commit hash : (if `develop`)

#### Expected behaviour
imported new chain segment

#### Actual behaviour
-killed

#### Steps to reproduce the behaviour
ses@ses:~$ sudo ./geth --http --syncmode snap --datadir.ancient /media/ses/'Yeni Birim'  
('Yeni- Birim') is an external drive

#### Backtrace

````
INFO [09-06|09:59:23.119] Imported new chain segment               blocks=17  txs=2907 mgas=249.348  elapsed=8.912s       mgasps=27.978  number=13,091,467 hash=d668ae..6887c6 age=1w5d5h   dirty=1022.89MiB
INFO [09-06|09:59:27.886] Generating state snapshot                root=f74dcb..45d4bc at=a73527..678c4d accounts=94,065,370 slots=326,320,214 storage=27.67GiB  elapsed=2h12m48.275s eta=1h10m31.397s
INFO [09-06|09:59:38.002] Generating state snapshot                root=f74dcb..45d4bc at=a736b5..05ab28 accounts=94,068,829 slots=326,324,826 storage=27.67GiB  elapsed=2h12m58.386s eta=1h10m36.326s
INFO [09-06|09:59:46.906] Generating state snapshot                root=f74dcb..45d4bc at=a736b5..113127 accounts=94,068,832 slots=326,324,826 storage=27.67GiB  elapsed=2h13m7.293s  eta=1h10m41.053s
Killed
````

When submitting logs: please submit them as text and not screenshots.

**Comment by MariusVanDerWijden** [comment]
What specs does your computer have? RAM?

**Comment by EkremSel** [comment]
total        used        free      shared  buff/cache   available
Mem:       16286252    11060024      162184       61988     5064044     4817336
Swap:       2097148     1899672      197476

**Comment by EkremSel** [comment]
total        used        free      shared  buff/cache   available
Mem:           15Gi        10Gi       157Mi        60Mi       4,8Gi       4,5Gi
Swap:         2,0Gi       1,8Gi       169Mi

**Comment by hdiass** [comment]
I'm having the same, no OOM.

**Comment by karalabe** [comment]
So, Geth by default runs with a cache allowance of 4GB, which translates into a memory usage of 6-8GB.

If your mem dump:

```
total        used        free      shared  buff/cache   available
Mem: 15Gi 10Gi 157Mi 60Mi 4,8Gi 4,5Gi
Swap: 2,0Gi 1,8Gi 169Mi
```

I assume you printed this after Geth was Killed (because otherwise the swap would be 0). Based on these numbers, you have something on your OS using 10GB of RAM, and you have 4.5 left for Geth. Geth will need more than that with default parameters, so when it tries to request more, the OS denies and kills it.

**Comment by EkremSel** [comment]
> So, Geth by default runs with a cache allowance of 4GB, which translates into a memory usage of 6-8GB.
> 
> If your mem dump:
> 
> ```
> total        used        free      shared  buff/cache   available
> Mem: 15Gi 10Gi 157Mi 60Mi 4,8Gi 4,5Gi
> Swap: 2,0Gi 1,8Gi 169Mi
> ```
> 
> I assume you printed this after Geth was Killed (because otherwise the swap would be 0). Based on these numbers, you have something on your OS using 10GB of RAM + 2GB swap, and you have 4.5 left for Geth. Geth will need more than that with default parameters, so when it tries to request more, the OS denies and kills it.

Thanks for the explanation. Although this has started happening after updating to 1.10.8 I had no issues previously.

**Comment by EkremSel** [comment]
Thanks for the explanation. Although this has started happening after updating to 1.10.8 I had no issues previously.

**Comment by EkremSel** [comment]
Here is the mem dump while geth is running,

free -h
              total        used        free      shared  buff/cache   available
Mem:           15Gi        10Gi       162Mi        64Mi       5,3Gi       5,0Gi
Swap:         2,0Gi       1,7Gi       327Mi

**Comment by EkremSel** [comment]
Would it have anything to do with block sizes being very large due to congestion (NFTs), so even 16GB of RAM is not sufficient??

**Comment by EkremSel** [comment]
This is the mem dump, get being run at least for an hour. The mem dump stays consistent here and geth will eventually kill the synch.

  total        used        free      shared  buff/cache   available
Mem:           15Gi        14Gi       173Mi        64Mi       1,3Gi       1,1Gi
Swap:         2,0Gi       2,0Gi          0B
