### ISSUE TITLE
syncmode: snap,  eth.blockNumber result is always 0x0

### ISSUE THREAD

**Issue by forencen** [ethereum/go-ethereum#23579]
Hi there,
After being running a mainnet Geth node for 10 of days, I get a block number which value is always zero when I execute eth_blockNumber rest RPC call   and  eth.blockNumber.

geth  (VERSION:1.10.8-stable-26675454) run command：
```
./geth  --rpcport 8545  --datadir /root/data  --rpc --rpcapi web3,eth,net,txpool,admin,personal,debug --rpcaddr 0.0.0.0 --cache 10240 --graphql --graphql.vhosts '*' --maxpeers 200
```

eth.syncing
```
{
  currentBlock: 13228938,
  highestBlock: 13229009,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 13226590
}
```
eth.blockNumber
```
0
```

```
# rpc request:
{
    "jsonrpc": "1.0",
    "id": 1,
    "method": "eth_blockNumber",
    "params": []
}

# rpc response:
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x0"
}

```

**Comment by MariusVanDerWijden** [comment]
`eth.blockNumber` always returns the block for which we have the full state available. Since you are still syncing, we don't have the complete state for any block, thus we return 0. This is expected behavior as stated in the json-rpc spec

**Comment by forencen** [comment]
> `eth.blockNumber` always returns the block for which we have the full state available. Since you are still syncing, we don't have the complete state for any block, thus we return 0. This is expected behavior as stated in the json-rpc spec

How to judge the synchronization is complete？ currentBlock== highestBlock？
