### ISSUE TITLE
Too many open files , leading to panic

### ISSUE THREAD

**Issue by azulmarino** [ethereum/go-ethereum#2358]
#### System information

Geth version: `1.3.5`
OS & Version: /OSX - El Capitan
Commit hash : (if `develop`)

#### Expected behaviour

Never exhausted open file count on previous version.
Are more resources being used ?

#### Actual behaviour

```text
#1152160 [257f7d2b / e9adf4fd]
I0315 08:38:58.796412    8257 downloader.go:267] Synchronisation failed: no peers to keep download active
I0315 08:39:09.079656    8257 blockchain.go:1251] imported 6 block(s) (0 queued 0 ignored) including 14 txs in 5.071856738s. #1152166 [9f1cf0bf / 349c5bae]
I0315 08:39:25.953231    8257 blockchain.go:1251] imported 26 block(s) (0 queued 0 ignored) including 108 txs in 16.860866201s. #1152192 [4fda4e6f / 80c21b78]
E0315 08:42:17.805896    8257 trie.go:309] Dangling hash node ref 3c356434386136366362383834633732316235633664396262383565663331633535663161326636386264636435656239316165313064653561623132356265633e20: open /Users/Dean/Library/Ethereum/chaindata/1406313.ldb: too many open files
E0315 08:42:17.805984    8257 trie.go:309] Dangling hash node ref 3c356434386136366362383834633732316235633664396262383565663331633535663161326636386264636435656239316165313064653561623132356265633e20: open /Users/Dean/Library/Ethereum/chaindata/1406313.ldb: too many open files
I0315 08:42:24.598658    8257 server.go:2161] http: Accept error: accept tcp 127.0.0.1:8545: accept: too many open files; retrying in 5ms
I0315 08:42:24.640457    8257 server.go:2161] http: Accept error: accept tcp 127.0.0.1:8545: accept: too many open files; retrying in 10ms
```

#### Backtrace

````

E0315 08:42:30.591436    8257 state_object.go:108] can't create account trie with root ccab66672ed1a6b84aed445efb59576417ffc887a7e3e9658736e784b72e789b: missing root node
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x415aad2]

goroutine 47 [running]:
panic(0x49c16a0, 0xc8200100d0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:464 +0x3e6
github.com/ethereum/go-ethereum/core/state.(*StateDB).GetStateObject(0xc8212e7980, 0xe4fcbbd9c420c20e, 0xa755aac026edceb4, 0xa0c0b878, 0x0)
	/private/tmp/ethereum20160303-33799-1typukk/src/github.com/ethereum/go-ethereum/core/state/statedb.go:242 +0x392
github.com/ethereum/go-ethereum/core/state.(*StateDB).Exist(0xc8212e7980, 0xe4fcbbd9c420c20e, 0xa755aac026edceb4, 0xa0c0b878, 0xc821cf7ae0)
	/private/tmp/ethereum20160303-33799-1typukk/src/github.com/ethereum/go-ethereum/core/state/statedb.go:105 +0x33
github.com/ethereum/go-ethereum/core.(*StateTransition).to(0xc8244990d8, 0x0, 0x0)
	/private/tmp/ethereum20160303-33799-1typukk/src/github.com/ethereum/go-ethereum/core/state_transition.go:149 +0xc6
github.com/ethereum/go-ethereum/core.(*StateTransition).transitionDb(0xc8244990d8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum20160303-33799-1typukk/src/github.com/ethereum/go-ethereum/core/state_transition.go:241 +0xa04
github.com/ethereum/go-ethereum/core.ApplyMessage(0x5f86308, 0xc8255c1b80, 0x5fc1200, 0xc824f85a70, 0xc822b0c5a0, 0x0, 0x0, 0x0, 0x4d2fc34, 0x0, ...)
	/private/tmp/ethereum20160303-33799-1typukk/src/github.com/ethereum/go-ethereum/core/state_transition.go:119 +0x1f7
github.com/ethereum/go-ethereum/core.ApplyTransaction(0xc8200b6280, 0xc822b0c5a0, 0xc8212e7980, 0xc821886240, 0xc824f85a70, 0xc8245920a0, 0xc8244995b0, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum20160303-33799-1typukk/src/github.com/ethereum/go-ethereum/core/state_processor.go:64 +0x228
github.com/ethereum/go-ethereum/miner.(*Work).commitTransaction(0xc823517800, 0xc824f85a70, 0xc8200b6280, 0xc822b0c5a0, 0x0, 0x0)
	/private/tmp/ethereum20160303-33799-1typukk/src/github.com/ethereum/go-ethereum/miner/worker.go:652 +0xa3
github.com/ethereum/go-ethereum/miner.(*Work).commitTransactions(0xc823517800, 0xc8231c9c00, 0x61, 0x61, 0xc820457fe0, 0xc8200b6280)
	/private/tmp/ethereum20160303-33799-1typukk/src/github.com/ethereum/go-ethereum/miner/worker.go:630 +0xc7e
github.com/ethereum/go-ethereum/miner.(*worker).commitNewWork(0xc8202dfb30)
	/private/tmp/ethereum20160303-33799-1typukk/src/github.com/ethereum/go-ethereum/miner/worker.go:531 +0xa5d
github.com/ethereum/go-ethereum/miner.(*worker).update(0xc8202dfb30)
	/private/tmp/ethereum20160303-33799-1typukk/src/github.com/ethereum/go-ethereum/miner/worker.go:237 +0x39a
created by github.com/ethereum/go-ethereum/miner.newWorker
	/private/tmp/ethereum20160303-33799-1typukk/src/github.com/ethereum/go-ethereum/miner/worker.go:141 +0x3c3
````

**Comment by fjl** [comment]
What is your --maxpeers setting?

**Comment by BenTuras** [comment]
I also run into this problem a lot. One of the things that I noticed is the number of files that appear to be opened 11(!) times?! With only one geth running(cut -c90- returns the name of the open file, sort -u sorts them unique):
$ lsof|grep geth|cut -c90-|sort|wc -l
473
$ lsof|grep geth|cut -c90-|sort -u|wc -l
41
I am running experiments on a local testnet with up to 4 nodes(N=1..4), each started like this:
$ geth --datadir=~/eth/6N --bootnodes ABC --verbosity 3 --networkid=311258 --port 3036N --rpc --rpcaddr 192.168.11.24 --rpcport 816N --mine --minerthreads=1 --etherbase=ABC --dev --nodiscover --genesis development_genesis.json --rpccorsdomain "*" console
(I left out the values(ABC above) for bootnodes and etherbase)

**Comment by karalabe** [comment]
@BenTuras If you're doing this for dev purposes, please try the latest develop branch of Geth. It should already have the file descriptor thing fixed. Also could you report back on whether it indeed fixes it for you or not?

**Comment by BenTuras** [comment]
$ git describe
v0.9.39-507-g506c927
# lsof|grep geth|cut -c93-|sort -u|wc -l
145
# lsof|grep geth|cut -c93-|sort|wc -l
3425
I am running:
ben      27075 27074 63 08:38 pts/17   00:24:41 /home/ben/go-ethereum/build/bin/geth --datadir=~/eth/61 --bootnodes ABC --verbosity 6 --networkid=311258 --port 30361 --rpc --rpcaddr 192.168.11.24 --rpcport 8161 --mine --minerthreads=1 --etherbase=DEF --nodiscover --dev --genesis development_genesis.json --rpccorsdomain "*" --maxpeers 248 console 2>> ~/eth/61.log
ben      27086 27085 72 08:38 pts/4    00:28:26 /home/ben/go-ethereum/build/bin/geth --datadir=~/eth/62 --bootnodes ABC --verbosity 6 --networkid=311258 --port 30362 --rpc --rpcaddr 192.168.11.24 --rpcport 8162 --mine --minerthreads=1 --etherbase=DEF --nodiscover --dev --genesis development_genesis.json --rpccorsdomain "*" --maxpeers 248 console 2>> ~/eth/62.log
ben      27097 27096 65 08:38 pts/19   00:25:30 /home/ben/go-ethereum/build/bin/geth --datadir=~/eth/63 --bootnodes ABC --verbosity 6 --networkid=311258 --port 30363 --rpc --rpcaddr 192.168.11.24 --rpcport 8163 --mine --minerthreads=1 --etherbase=DEF --nodiscover --dev --genesis development_genesis.json --rpccorsdomain "*" --maxpeers 248 console 2>> ~/eth/63.log

I have the log files if you're interested.

**Comment by karalabe** [comment]
You are on the stable branch (https://github.com/ethereum/go-ethereum/commit/506c9277911746dfbab0a585aee736bd3095f206), please check out `develop` and try that.

**Comment by BenTuras** [comment]
$ git describe
v0.9.39-745-ge189fb8
$ lsof|grep geth|cut -c93-|sort|wc -l
3108
$ lsof|grep geth|cut -c93-|sort -u|wc -l
190
$ lsof|grep "^geth"|cut -c93-|grep chaindata|sort -u|head -5
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/018745.ldb
ben/eth/61/chaindata/018780.ldb
ben/eth/61/chaindata/018781.ldb
ben/eth/61/chaindata/018790.ldb
$ lsof|grep "^geth"|cut -c93-|grep chaindata|grep ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb
ben/eth/61/chaindata/017846.ldb

**Comment by karalabe** [comment]
I just ran 

```
$ lsof -n|grep geth|grep chaindata|grep LOCK

geth      29911               karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29912         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29913         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29914         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29915         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29916         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29917         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29918         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29919         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29920         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29921         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29922         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29923         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29925         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29926         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29927         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29928         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29929         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29957         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29969         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29970         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29975         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 29977         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 30049         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 30050         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
geth      29911 30051         karalabe    3uW     REG                8,1         0    2005696 /home/karalabe/.ethereum/chaindata/LOCK
```

This gives an interesting insight: although it would seem that we have a ton of file descriptors open for the database lock, it wouldn't make much sense, as it's an exclusive lock. If you look at the file descriptor column, it reports to every single instance `3uW`, meaning that `lsof` is actually reporting the same file descriptor a ton of times.

Digging a bit deeper reveals that `lsof` is actually reporting file descriptors separately for every single OS thread within a process that has access to the descriptor. This is the second column of numbers in my dump. However, all those threads share the FD between them, so they are actually one and the same, not separate ones, only `lsfo` reports them as duplicate.

If I filter out lsof lines reported for individual threads and only leave those reported for the process itself (i.e. TID field empty, I filtered it containing my user as such), I get:

```
$ lsof -n|grep geth|grep chaindata|awk '$3 == "karalabe" {print $0}'|cut -c95-|sort|wc -l
1015

$ lsof -n|grep geth|grep chaindata|cut -c95-|sort -u|wc -l
1011
```

Which is the correct answer (minor diff due to geth running in the background and doing its stuff on the database). **Note, the reason my FD count is much higher than yours is because on develop we've got an update that raises the processes FD limit to avoid database thrashing. It's set to 1024.**

**Comment by azulmarino** [comment]
I haven't seen this again , be running virtually non-stop since my last update

ulimit -a 256

lsof -n|grep geth|grep chaindata|cut -c95-|sort -u|wc -l
      36
Deans-MacBook-Pro:eth-net-intelligence-api Dean$  lsof|grep geth|cut -c93-|sort|wc -l
      55

**Comment by anton44eg** [comment]
Have same problem on Linux. After homestead release geth node crashes every 5 days with "too many open files"

**Comment by fjl** [comment]
We have increased fd limits to 1028 on supported platforms starting with the 1.4 release.

**Comment by miohtama** [comment]
Still on testnet, Ubuntu 14.04, geth 1.4.12:

    I0921 14:45:35.972432 server.go:1934] http: Accept error: accept tcp 127.0.0.1:8545: accept4: too many open files; retrying in 1s
    I0921 14:45:36.993952 server.go:1934] http: Accept error: accept tcp 127.0.0.1:8545: accept4: too many open files; retrying in 1s
    I0921 14:45:38.005507 server.go:1934] http: Accept error: accept tcp 127.0.0.1:8545: accept4: too many open files; retrying in 1s

    VERSION:
       1.4.12-stable

**Comment by fjl** [comment]
@miohtama Can you post the log messages that are generated at startup? It should print out how many fds were allocated to the database.

**Comment by miohtama** [comment]
Here:
     
      I0921 16:42:14.250216 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/ubuntu/.ethereum/testnet/chaindata

**Comment by promethe42** [comment]
Got the same issue: I don't know why, but since yesterday my private chain (which is around block 95000) does this kind of errors:

```
I1106 08:16:20.383703 server.go:1934] http: Accept error: accept tcp 127.0.0.1:8545: accept4: too many open files; retrying in 5ms
```

Yet the number of file descriptors look OK to me:

```
root@laprimaire:~# lsof -p 12478 | grep localhost | wc -l
1704
```
```
root@laprimaire:~# cat /proc/32706/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             64058                64058                processes 
Max open files            2048                 4096                 files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       64058                64058                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us
```

**Comment by promethe42** [comment]
OK solved it.
The connections were kept alive because geth was super busy replying to some filters.
So I changed this:

```javascript
  const ballotEvent = contract.Ballot(
    {voter: address},
    {fromBlock: 0, toBlock: 'latest'}
  );
```

into this:

```javascript
  const blockNumber = await promise((cb)=>web3.eth.getBlockNumber(cb))();
  const ballotEvent = contract.Ballot(
    {voter: address},
    {fromBlock: blockNumber, toBlock: 'latest'}
  );
```

**Comment by miohtama** [comment]
Yeah. Looks like there is pathological behavior when geth is under stress (network being dos'ed?)

**Comment by eiabea** [comment]
Having the same issues on Debian. Synced the chain with an older version (afaik 1.4.x) without any troubles. On Debian i have to remove LOCK and a *.ldb file manually and restart geth about every hour.

instance: Geth/v1.5.2-stable-c8695209/linux/go1.7.3
Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux

**Comment by miohtama** [comment]
@eiabea Do you have excessive JSON-RPC traffic or what kind of usage you have for the node?

**Comment by eiabea** [comment]
Just trying to sync the chain

top
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                   
28300 eiabea    20   0 1717896 990.6m  11428 S  15.3 12.5   4:37.73 geth  
```
free -h
```
             total       used       free     shared    buffers     cached
Mem:          7.7G       7.5G       221M        28M       586M       2.1G
```
iotop
```
90% geth
```
geth - net
```
  listening: true,
  peerCount: 7,
  version: "1",
```

hope this gives an overview over my node

**Comment by eiabea** [comment]
I think i "fixed" it...

```
#!/bin/bash

while true; do 
	geth --fast --cache=512
	rm -rf /home/eiabea/.ethereum/geth/LOCK
done
```
