### ISSUE TITLE
Mainnet stop sync at block 13217655 and  CPU takes up 100%

### ISSUE THREAD

**Issue by tunglouis** [ethereum/go-ethereum#23581]
Hi there,
My fullnode running on mainnet fails at block 13217655 and CPU takes up 100% of server resources.
{
  currentBlock: 13217655,
  highestBlock: 13229278,
  knownStates: 755248282,
  pulledStates: 755248282,
  startingBlock: 13218749
}

#### System information

Geth version: `geth version 1.10.8`
OS & Version: Windows/Linux/OSX

**Comment by rjl493456442** [comment]
Your node is still syncing the state.

`CPU takes up 100% of server resources.` Can you share some running logs to see if something special happens?

**Comment by tunglouis** [comment]
![Screen Shot 2021-09-15 at 16 35 51](https://user-images.githubusercontent.com/10813839/133416893-484fea9b-6ad4-4f2d-a86f-9e3daa035e3b.png)![Screen Shot 2021-09-15 at 16 35 26](https://user-images.githubusercontent.com/10813839/133416902-a4bdfa66-abfb-41b4-b13c-cee30eb2f903.png)

My node syncs very slowly because CPU resources are full. I checked the log and found no errors
This is my logs.
![Screen Shot 2021-09-15 at 17 28 18](https://user-images.githubusercontent.com/10813839/133417380-5e3db6c2-d8e5-4b69-a3c1-986c156f3b12.png)

**Comment by rjl493456442** [comment]
Are you serving your own `eth_call` RPC requests? Or they just come from the internet?
Your node is not synced yet, I would recommend to not serve the rpc request at all. And if you expose the RPC via the HTTP, don't remember to set the `--http.corsdomain` to reject the random internet requests.
