### ISSUE TITLE
Why gave "geth.ipc" hardcoded in cmd/geth/consolecmd.go line 139 ?

### ISSUE THREAD

**Issue by Quaqmre** [ethereum/go-ethereum#23585]
I think "geth.ipc" can giving with config.IPCPath variable , Am I wrong ?

**Comment by verheesj** [comment]
> I think "geth.ipc" can giving with config.IPCPath variable , Am I wrong ?

When you execute `geth attach` you are not explicitly stating the path or the endpoint, thus it falls back to `/path/to/default/datadir/geth.ipc`

**Comment by Quaqmre** [comment]
Thank u for the given information , 👍
