### ISSUE TITLE
eth.syncing broken in snap sync

### ISSUE THREAD

**Issue by verheesj** [ethereum/go-ethereum#23584]
The `eth.syncing` is a bit broken in snap sync, it does not fill in the necessary infos. We need to fix that.

_Originally posted by @karalabe in https://github.com/ethereum/go-ethereum/issues/23553#issuecomment-915787544_

Can we discuss?

**Comment by ligi** [comment]
I initiated some discussion some time ago here: https://ethereum-magicians.org/t/improve-syncing-rpc-call/6994 - we should do it in magicians to agree on a standard for RPC here so client's do not diverge even more

**Comment by karalabe** [comment]
I have an open PR that will fix this. It's a lot of changes, so will take a while (it's a complete downloader overhaul).
