### ISSUE TITLE
Intranet machines use intranet ip to communicate

### ISSUE THREAD

**Issue by kaolula** [ethereum/go-ethereum#23596]
I have three Amazon EC2,they are all synchronized with Ethereum node data.
The machine information
|  Machine Name   | External network ip  | Internal network ip  |
|  ----  | ----  |----  |
| EC2-A  | 70.122.90.94 |192.168.1.1 |
| EC2-B  | 70.122.91.95 |192.168.1.2 |
| EC2-C  | 70.122.92.96|192.168.1.3|
> The i.P. information on the extranet is fake,Just for better description
EC2-A machine start script
```
./geth --config ./config.toml --nat=extip:192.168.1.1 --maxpeers 10000 
```
EC2-B machine start script
```
./geth --config ./config.toml --nat=extip:192.168.1.2--maxpeers 10000 
```
EC2-C machine start script
```
./geth --config ./config.toml --nat=extip:192.168.1.3--maxpeers 10000 
```

**Information for each node** 
EC2-A nodeino
```
  enode: "enode://f2b359dc15a673145c491474c2e7830fb5a3a5d652c770ab5d8d8ab96c58f483acc8b17e31f33926c77894ee1fc7560d5f6f65c99a75687fd3eb24716f51c2ee@192.168.1.1:30311",
  enr: "enr:-J24QLPie002uZ8ootd9oDOkaCGJoEd0eJwNV231Bm3idtM5FFqkTvuJxPxMbeWkv5Je16uV-ZpspB5K1I1-XstE7lUDg2V0aMfGhPw8preAgmlkgnY0gmlwhMCoARqJc2VjcDI1NmsxoQLys1ncFaZzFFxJFHTC54MPtaOl1lLHcKtdjYq5bFj0g4RzbmFwwIN0Y3CCdmeDdWRwgnZn",
  id: "b6fe3c28cc6a3eabd9ad5eab9047611faaea3a9650e9a2237b4f654bd89f6d7e",
  ip: "192.168.1.1",
  listenAddr: "[::]:30311",
```

EC2-B nodeino
```
  enode: "enode://4da3f4aa20ff15276c1faef532cf796f93f10d85164bf4ce16a73c8eaaab96e3d6f6af6581d9cf01410d717b9fd5b22ae4bc81706b53f252006bd9ba19a20567@192.168.1.2:30311",
  enr: "enr:-J24QOoMf8CjLdpcBNBbTAqVfNySlXdbXN8An2LikjJPKwDMfiSnVP1flxDc3jLnhI8DRb_TG_CUNn2ucr0IFdeZn3sDg2V0aMfGhPw8preAgmlkgnY0gmlwhMCoAR6Jc2VjcDI1NmsxoQNNo_SqIP8VJ2wfrvUyz3lvk_ENhRZL9M4WpzyOqquW44RzbmFwwIN0Y3CCdmeDdWRwgnZn",
  id: "8b87239184918b94013e32cb43b86a0458a4b7f3df8516af56629112fa48797e",
  ip: "192.168.1.2",
  listenAddr: "[::]:30311",
```

EC2-C nodeino
```
  enode: "enode://c86df17a43d969edd5c72d6709cbbd8af04899fc7da5ecd97dc7f9863be2edc6c3d32a0c14d1451114b3d328b3d11c9836ec136e9a32e08e00f4f38d09b6e03f@192.168.1.3:30311",
  enr: "enr:-J24QGn4cFBGMiTFjZlls83jCGz0woy1XU9DCgX9uZ292SqSU59gjd-W8ZUlYRTkIGxMiqqm8WNrpuxI_z64Od1BNhMDg2V0aMfGhPw8preAgmlkgnY0gmlwhMCoAQiJc2VjcDI1NmsxoQPIbfF6Q9lp7dXHLWcJy72K8EiZ_H2l7Nl9x_mGO-LtxoRzbmFwwIN0Y3CCdmeDdWRwgnZn",
  id: "073e9fe8072d90178f347a95bb65176ec017a9a6d6bc9af113afde480d118560",
  ip: "192.168.1.3",
  listenAddr: "[::]:30311",
```
![image](https://user-images.githubusercontent.com/11549225/133870947-1c6fcd8d-ff77-420c-bb5f-950a79f602d9.png)
These three machines can broadcast transactions on the intranet machine p2p.But I found that the node identity is the intranet ip, will this prevent other machines from connecting to our machine?

Can other nodes of the network be unable to link to my intranet node, but my intranet node can link to other nodes?
I found that my node connected to hundreds of peers.

_Originally posted by @wemem in https://github.com/ethereum/go-ethereum/issues/23583#issuecomment-922170771_

**Comment by verheesj** [comment]
**EC2-A, EC2-B, EC2-C**
If Internet connectivity is not required or all member nodes connect using well-known IPs, we strongly recommend setting up Geth to restrict peer-to-peer connectivity to an IP subnet. Doing so will further isolate your network and prevents cross-connecting with other blockchain networks in case your nodes are reachable from the Internet. Use the --netrestrict flag to configure a whitelist of IP networks:

> `geth <other-flags> --netrestrict 192.168.1.0/24`
> 
With the above setting, Geth will only allow connections from the 192.168.1.0/24 subnet (range: 192.168.1.1-192.168.1.255), and will not attempt to connect to other nodes outside of the set IP range.

**Comment by karalabe** [comment]
@wemem It's not relaly clear what you're trying to do. Whether you're trying to make your nodes not discoverable, or discoverable.

If you specify which IP to use as the `external IP` (`--nat=extip:192.168.1.1`), then Geth will advertise that. Outside nodes might have a harder time finding you, but if you at the same time ping other nodes you know about on your public interface, that information will leak out even if you don't explicitly advertise that (AFAIK). If you want others not to find you, you need to firewall the ports. If you want others to find you, advertising internal IPs as the external just makes things messy.

**Comment by wemem** [comment]
> @wemem It's not relaly clear what you're trying to do. Whether you're trying to make your nodes not discoverable, or discoverable.
> 
> If you specify which IP to use as the `external IP` (`--nat=extip:192.168.1.1`), then Geth will advertise that. Outside nodes might have a harder time finding you, but if you at the same time ping other nodes you know about on your public interface, that information will leak out even if you don't explicitly advertise that (AFAIK). If you want others not to find you, you need to firewall the ports. If you want others to find you, advertising internal IPs as the external just makes things messy.

I set --nat as the intranet ip, just to allow my machine to broadcast transactions through the intranet and receives transaction fast over the Intranet

**Comment by verheesj** [comment]
> > @wemem It's not relaly clear what you're trying to do. Whether you're trying to make your nodes not discoverable, or discoverable.
> > If you specify which IP to use as the `external IP` (`--nat=extip:192.168.1.1`), then Geth will advertise that. Outside nodes might have a harder time finding you, but if you at the same time ping other nodes you know about on your public interface, that information will leak out even if you don't explicitly advertise that (AFAIK). If you want others not to find you, you need to firewall the ports. If you want others to find you, advertising internal IPs as the external just makes things messy.
> 
> I set --nat as the intranet ip, just to allow my machine to broadcast transactions through the intranet and receives transaction fast over the Intranet.
> In fact, I found out that I can’t do it this way.Setting up an intranet may cause the transactions I accept to become slower

To prevent external connections you would use `--netrestrict 192.168.1.0/24` this would then restrict peers to your local network, preventing peers from the internet from connecting to them.

**Comment by verheesj** [comment]
duplicate issue #23583

**Comment by holiman** [comment]
Closing this, the issue description of what op is trying to achieve is vague, and answers have been given
