### ISSUE TITLE
Clef req.meta.scheme is NA even request from clef.ipc

### ISSUE THREAD

**Issue by fahadh4ilyas** [ethereum/go-ethereum#23593]
I'm trying to use clef as external signer and account manager. But, the problem is when I tried to set clef as geth signer, it keeps asking approval of list account even the rules already set like the example

```js
function ApproveListing(req) {
    if (req.meta.scheme == "ipc"){ return "Approve"}
}
``` 

As you see, list account is approved when the request is made from IPC and I connect geth to clef using this parameter

```
--signer=~/.clef/clef.ipc
```

I believe this means requests made from geth automatically from IPC, right? But, why clef keeps asking for approval for that request? When I check the value of `req.meta.scheme`, the result is `NA`. Why is that?

**Comment by xela274** [comment]
Uo

**Comment by xela274** [comment]
Yo

**Comment by s1na** [comment]
It seems like the IPC endpoint is not setting the scheme. Working on a fix
