### ISSUE TITLE
the method eth_protocolVersion does not exist/is not available

### ISSUE THREAD

**Issue by qasimraheem** [ethereum/go-ethereum#23598]
hi, i am using stable geth.

geth version Geth Version: 1.10.7-stable Architecture: amd64 Go Version: go1.16.6 Operating System: darwin GOPATH= GOROOT=go

i am having issues with calling the eth_protocolVersion :
postman error ==> "error": {
"code": -32601,
"message": "the method eth_protocolVersion does not exist/is not available"
}

i attached the geth console and printed all eth functions, where i am getting "protocolVersion: undefined"
i tried with building the geth of current master branch, getting the same issues.

INIT genesis file by :
geth --identity "dappslab" --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api txpool,admin,eth,net,web3,personal --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --ws.api txpool,admin,eth,net,web3,personal --graphql --graphql.corsdomain "*" --datadir /Users/$(whoami)/DappsChain/node1 --port 30303 --networkid 13936 init /Users/$(whoami)/DappsChain/Genesis.json

running geth by :
geth --identity "dappslab" --syncmode full --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api miner,txpool,admin,eth,net,web3,personal --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --ws.api miner,txpool,admin,eth,net,web3,personal --graphql --graphql.corsdomain "*" --datadir /Users/$(whoami)/DappsChain/node1 --port 30303 console

am i doing this wrong or the geth have bug or removed this function?

**Comment by MariusVanDerWijden** [comment]
Geth removed this function some time ago, see also the discussion at https://github.com/ethereum/go-ethereum/pull/22064
