### ISSUE TITLE
How to Run Faucet on private network on Ethereum local node

### ISSUE THREAD

**Issue by amaan-mohd** [ethereum/go-ethereum#23608]
Hi All,

We are struggling to run the Faucet on local private blockchain network and all the time we are not understanding to to execute the code mentioned in https://github.com/ethereum/go-ethereum/tree/master/cmd/faucet ?

Could please have any guideline or setup the docs for run the faucet on private blockchain network so that our developer can use test ether for development and integrations

@karalabe @holiman  I know you are the most experience person to help such issues, could you please help for the same.

is I am lacking somewhere or I can have some steps to execute the same ?

Please help with the same.

Do I need to run the same as make geth ? is there any way how I can run it

**Comment by s1na** [comment]
Please refer to the [doc](https://github.com/ethereum/go-ethereum/blob/master/cmd/faucet/README.md).

**Comment by amaan-mohd** [comment]
Hi There,

Sorry for the delay in response, I have read this document lots of time but still no clues how should I run the Faucet.

All the time getting an error when use Faucet --help  as below 

faucet --help
Usage : faucet <port> (--in|--out|--err|--fd N)+ [--once] [--verb(|ose)] [--quiet] [--unix] [--foreignport <port>] [--foreignhost <inet-addr>] [--localhost <inet-addr>] [--daemon] [--serial] [--shutdown (r|w)] [--pidfile fname] [--noreuseaddr] [--backlog n] -[i][o][e][#3[,4[,5...]]][v][1][q][u][d][s] [-p <foreign port>] [-h <foreign host>] [-H <local host>] command args


Is there any documents where I can see the command example for running it smoothly.

Many thanks in advance

**Comment by karalabe** [comment]
@amaan-mohd That's some other binary on your system. Nothing to do with our code.

**Comment by holiman** [comment]
@amaan-mohd try `which faucet`, it should tell you what you're actually executing
