### ISSUE TITLE
Geth stops unexpectedly : Killed

### ISSUE THREAD

**Issue by EkremSel** [ethereum/go-ethereum#23603]
System information
Geth version: 1.10.8
OS & Version: Linux/ Ubuntu 20.10'
16 Gi Ram
Commit hash : (if develop)

Expected behaviour
imported new chain segment

Actual behaviour
-killed

Steps to reproduce the behaviour
ses@ses:~$ sudo ./geth --http --syncmode snap --datadir.ancient /media/ses/'Yeni Birim'
('Yeni- Birim') is an external drive

Backtrace
INFO [09-06|09:59:23.119] Imported new chain segment               blocks=17  txs=2907 mgas=249.348  elapsed=8.912s       mgasps=27.978  number=13,091,467 hash=d668ae..6887c6 age=1w5d5h   dirty=1022.89MiB
INFO [09-06|09:59:27.886] Generating state snapshot                root=f74dcb..45d4bc at=a73527..678c4d accounts=94,065,370 slots=326,320,214 storage=27.67GiB  elapsed=2h12m48.275s eta=1h10m31.397s
INFO [09-06|09:59:38.002] Generating state snapshot                root=f74dcb..45d4bc at=a736b5..05ab28 accounts=94,068,829 slots=326,324,826 storage=27.67GiB  elapsed=2h12m58.386s eta=1h10m36.326s
INFO [09-06|09:59:46.906] Generating state snapshot                root=f74dcb..45d4bc at=a736b5..113127 accounts=94,068,832 slots=326,324,826 storage=27.67GiB  elapsed=2h13m7.293s  eta=1h10m41.053s
Killed

**Comment by EkremSel** [comment]
Here is the memdump geth running :

                    total        used        free      shared  buff/cache   available
Mem:           15Gi        12Gi       156Mi        72Mi       3,1Gi       2,8Gi
Swap:            0B          0B          0B

It seems geth is eating all the memory.

**Comment by s1na** [comment]
> Steps to reproduce the behaviour
ses@ses:~$ sudo ./geth --http --syncmode snap --datadir.ancient /media/ses/'Yeni Birim'
('Yeni- Birim') is an external drive

Normally you shouldn't need to run geth with `sudo`.

Also I see you have the `--http` flag on. Are you issuing some RPC calls that could potentially cause the crash?

**Comment by EkremSel** [comment]
@s1na 

I believe it is the linux oom procedure that is killing geth. Nope no rpc calls. 

5% is used by miner and the rest is geth. Other procedures memory usage is negligible.

**Comment by EkremSel** [comment]
When I removed sudo or --http flag the synch does not import new chain segments. However the memory seems to function normally. When I add sudo, it starts importing but eats up all the memory. This has started happening when upgraded to 1.10.8
