### ISSUE TITLE
Suggestion: JSON RPC API - no efficient way to control transactions remotely

### ISSUE THREAD

**Issue by mudpedal** [ethereum/go-ethereum#2360]
This is not a particular geth problem, but a problem with the rpc api in general.

I'm developing a service that will automatically submit transactions to geth, I've made my own driver lib that can also sign transactions and generate wallets and I just submit raw transactions by rpc.

One problem that I have is that there is no correct way to always detect a nonce before I sign a transaction.

- eth_getTransactionCount only returns mined transactions (not pending/queued)
- my service has to always predict nonce, which it can most of the time but some problems can arise
- if one of my transactions fail, others will remain queued if they have higher nonces, I cannot cancel them, they will remain hanging until I insert transactions before them

What I'm asking is that in order for geth/other ethereum clients to become better gateways for dapp services, it has to bring more to nonce deduction, since transactions can't be properly cancelled (they might reach other nodes)

My suggestions are:
- make rpc call be able to return what transactions are pending and what are queued, maybe even give a nonce recommendation for the next transaction for a wallet
- for more safety, you can create a model in which you send transactions to geth by they dont automatically get submitted, you are given a chance to either cancel them or approve them.

Thank you,
Andi

**Comment by karalabe** [comment]
As almost all methods, `eth_getTransactionCount` accepts a second optional parameter to specify the block number. This can also be `"pending"`, in the case of which you'll get back the pending nonce, not the current one.

**Comment by mudpedal** [comment]
Thank you, I entirely missed that.

**Comment by karalabe** [comment]
Cheers :)
