### ISSUE TITLE
EIP1559 mempool TX replacement condition 

### ISSUE THREAD

**Issue by pdyraga** [ethereum/go-ethereum#23616]
While working on adjusting the code increasing the gas price for transactions after EIP 1559 changes, we noticed that the transaction pool rejects to replace transactions if both `opts.GasTipCap` and `opts.GasFeeCap` are not higher than the previous values or if at least one of them is not higher than the previous value by at least 10%.

Let's say that my original transaction had `opts.GasTipCap = 10`, `head.BaseFee` was `20` so according to [this](https://github.com/ethereum/go-ethereum/blob/e28f713ada67af2380bd7052cb85b2e255a62a6a/accounts/abi/bind/base.go#L270-L273) formula`opts.GasFeeCap = 2 * 20 + 10 = 50`. Let's say no miner picked the transaction because other transactions had higher `opts.GasTipCap`, thus `opts.GasFeeCap` as well. 

After a few hours, I decide to increase the tip for miners and I see that `head.BaseFee` dropped to `5` but all other transactions in the pool have a pretty large `opts.GasTipCap` what makes my transaction still waiting. I decide to increase `opts.GasTipCap` to `30` and recalculate `opts.GasFeeCap = 2 * 5 + 30 = 45`. 

Now, we have a situation when miners can earn more for processing my transaction than before (10 vs 30) but the mempool rejects the replacement.

Isn't it a bug in the mempool implementation? We found [this](https://github.com/ethereum/go-ethereum/pull/22898/files#r636583352) comment in the original PR but there is no reasoning described why the current replacement condition is the best choice.

**Comment by karalabe** [comment]
Transactions require a total ordering. I.e. there must be some sorting which can unambiguously compare two transactions. This is needed to avoid SPAM attacks on the pool where some transactions push out one set, then another transaction pushes out the original pushers. That would allow an amplification attack where transactions are constantly being pushed out, rotating in a loop.

Requiring both tip and fee to be bumped by 10% is one such way that's easy to reason about. In general, the current pool construction tries to enforce that "promised" fees are never allowed to go down. That means each replacement tx (which ripples through the network) is more and more costly to the sender, so it's not worth it to keep pushing txs in.

**Comment by MariusVanDerWijden** [comment]
fixed the comment here: https://github.com/ethereum/go-ethereum/pull/23825
