### ISSUE TITLE
Improve eth syncing documentation

### ISSUE THREAD

**Issue by verheesj** [ethereum/go-ethereum#23617]
issue #23600

a `false` could also mean that you are not syncing and not synced up?

_Originally posted by @verheesj in https://github.com/ethereum/go-ethereum/pull/23600#discussion_r712848039_

**Comment by Gresliebear** [comment]
Exactly I am trying to set up geth node for development 

I am sitting here what does "state heal in progress" mean? well is the get node syncing ailed or corrupt?

**Comment by MariusVanDerWijden** [comment]
The snap sync will sync some not 100% correct state during initial sync (as the blockchain moves) so once we downloaded enough state we are going to heal that state (essentially downloading the missing pieces). State heal is part of the normal sync process

**Comment by karalabe** [comment]
I've merged the PR since it's better than the old text. Snap sync is indeed different and the pending downloader PR already changes it. The text can be fixed up once again once that's merged.
