### ISSUE TITLE
Geth 1.3.5 Blockchain not syncing to lastest while saying Syncing=False 

### ISSUE THREAD

**Issue by gregbkr** [ethereum/go-ethereum#2361]
#### System information

Geth version: 1.3.5
OS & Version: Ubuntu 14.04 (docker ethereum/client-go 1.3.5)
#### Expected behaviour

Geth is running since 1 week, and should be syncing to the last now block. 1 167 012
#### Actual behaviour

Geth is running, syncing status=False (which is wrong), and last updated block is 1 160 652. All transactions after that are pending, because we are on a late block.
#### Steps to reproduce the behaviour

Only happened once after the migration to 1.3.5 last week.
#### Backtrace

![capture](https://cloud.githubusercontent.com/assets/5642000/13851580/0cad4884-ec5f-11e5-800a-c14744e7fcf1.JPG)

```
[backtrace]
```
### Fix

I couldn't find a way to force the re-sync from geth.
So have to restart the container, and lost on the way all pending tx.
Looking for a way to avoid this in future.

Thank you for your help!
Greg.

**Comment by megahz2** [comment]
Same here,

"ctrl c" or multiple "ctrl c" advances geth to latest block but continually happens.
unable to mine solo since 1.3.5 

note: 
  -rpc rig = windows 7 vm running geth 1.3.5
 mining rig 1 windows 8.1 PC's running ethminer homestead 1.2.1
 mining rig 2 windows 7    PC's running ethminer homestead 1.2.1

Please address or advise, I miss solo mining.

Thank You for all that you do!!
Tony

**Comment by radfish** [comment]
I found that roughly every other time I restart geth it immediately sets eth.syncing to an object other than 'false', starts syncing, and makes progress. Roughly every other time, eth.syncing is false, and remains so even after hours of running geth. So, when restarting my node for whatever reason, I just keep restarting it until I hit the first case.

Geth/v1.4.4-stable-94ad694a/linux/go1.6.2
built from source on armv7h

**Comment by gregbkr** [comment]
Hello, I got again the same issue in production:
With version : 146, 148 and recently with 149.
Last occurrence happened yesterday, where geth stopped sync for hours until we restart it.

In short:
> at 22:38: it syncs block 1831106 .
> then nothing get sync.
> at 01:30 we send some tx  --> which gets in pending because geth is not sync.
> at 10:00 we restart and all is good again.

 I got in the logs:

```
July 6th 2016, 01:30:20.000	I0705 23:30:20.454049 eth/api.go:1193] Tx(0x78b107f9c23bb6a9...) to: 0x127c7ea82f53bc7e9e619b...
July 6th 2016, 01:30:20.000	2016-07-05 23:30:20,471 DEBG 'geth' stderr output:

July 5th 2016, 22:28:52.000	I0705 20:28:52.295561 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 8 txs in 14.434963003s. #1831106 [ee067b2b / ee067b2b]
July 5th 2016, 22:28:52.000	2016-07-05 20:28:52,295 DEBG 'geth' stderr output:
July 5th 2016, 22:28:27.000	I0705 20:28:27.718705 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 12.189006ms. #1831105 [50c4adfa / 50c4adfa]
July 5th 2016, 22:28:23.000	I0705 20:28:23.887456 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 8.140641ms. #1831104 [a10503dd / a10503dd]
July 5th 2016, 22:28:19.000	I0705 20:28:19.589386 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 7.092389ms. #1831103 [51a3a45c / 51a3a45c]
```

I saw I can use geth --verbosity=6, but seems like it generates lots of logs, and not sure if recommended for production, and when this will happen again. 

Got same geth on dev/staging without issue so far...

Thank you for any assistance.
Greg.

**Comment by gregbkr** [comment]
Hello,
Again same issue today, geth 1.4.10 stopped syncing.
```
August 18th 2016, 04:00:47.000	ethereum	I0818 02:00:47.732758 core/blockchain.go:963] imported 0 block(s) (0 queued 97 ignored) including 0 txs in 826.533488ms. #2060297 [60a75d19 / 716a3563]
August 18th 2016, 04:00:46.000	ethereum	I0818 02:00:46.491786 core/blockchain.go:963] imported 0 block(s) (0 queued 2 ignored) including 0 txs in 13.98311ms. #2060162 [0fa77512 / 737ea164]
August 18th 2016, 04:00:46.000	ethereum	I0818 02:00:46.892381 core/blockchain.go:963] imported 0 block(s) (0 queued 38 ignored) including 0 txs in 224.434135ms. #2060200 [52fb0be3 / 420bb568]
August 18th 2016, 04:00:46.000	ethereum	I0818 02:00:46.168098 core/blockchain.go:963] imported 0 block(s) (0 queued 3 ignored) including 0 txs in 17.807034ms. #2060160 [b399db4c / 2f267a7b]
August 18th 2016, 04:00:39.000	ethereum	I0818 02:00:39.633898 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 13.45657ms. #2091928 [d8257a94 / d8257a94]

```

Thank you for your help!
Greg.

**Comment by fjl** [comment]
@gregbkr please try geth 1.4.11

**Comment by gregbkr** [comment]
Again same problem today. --> I will try the 1.4.11 thx!
```
I0826 14:02:05.301702 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 44 txs in 83.639687ms. #2143493 [b9392ce4 / b9392ce4]
I0826 14:02:06.871712 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 211 txs in 426.075804ms. #2143493 [9df72509 / 9df72509]
I0826 14:02:31.320782 eth/downloader/queue.go:1019] Peer acd249eae4e7a5bb: header #2105469 [e3998d99] broke chain ancestry
I0826 14:02:32.477604 eth/downloader/queue.go:1019] Peer acd249eae4e7a5bb: header #2112984 [a74241e3] broke chain ancestry
I0826 14:02:33.668841 eth/downloader/queue.go:1019] Peer acd249eae4e7a5bb: header #2116765 [0285cf88] broke chain ancestry
I0826 14:02:34.179305 core/blockchain.go:963] imported 0 block(s) (0 queued 10 ignored) including 0 txs in 38.479044ms. #2104292 [f1cef4cb / 25ffb9e8]
I0826 14:02:34.813802 eth/downloader/queue.go:1019] Peer acd249eae4e7a5bb: header #2120997 [9b1ee576] broke chain ancestry
I0826 14:02:35.250505 core/blockchain.go:963] imported 0 block(s) (0 queued 15 ignored) including 0 txs in 90.510794ms. #2104307 [c18dc2d0 / 8c42e2b3]

```
