### ISSUE TITLE
Rinkeby Faucet not working

### ISSUE THREAD

**Issue by grossetti** [ethereum/go-ethereum#23611]
I heard someone here maintains the Rinkeby faucet, but it doesn't work.

#### System information

OS & Version: Linux
Browser : Chrome 93.0.4577.63 (Official Build) (64-bit) & Firefox 92.0 (64-bit)

#### Expected behaviour
I put the twitter link to the post
I select the amount from the dropdown
I see some button to submit

#### Actual behaviour
I put the twitter link to the post
I select the amount from the dropdown, it doesn't keep the choice and goes back to the initial value
I don't see a button either

#### Steps to reproduce the behaviour
Go to : https://faucet.rinkeby.io/
Put the twitter link to the post containing the wallet address
Try to select the amount from the dropdown

In the meantime, if someone could kindly send me some test ETH here so that I may continue developing/testing, it would be greatly appreciated! 0x1cE326Ddbe3159217Ce0c3a6C2fc873979600448

Cheers,
Gab

**Comment by vdemsky** [comment]
Please address. Having same issue.

**Comment by Austinhs** [comment]
Same issue

0xB63c946688D9a1b2EF1e2753c29aa67D4F3136F8

**Comment by logrusorgru** [comment]
Same

**Comment by karalabe** [comment]
It's online now.
