### ISSUE TITLE
GasLimit for pending block always wrong

### ISSUE THREAD

**Issue by Gdocal** [ethereum/go-ethereum#23627]
I am trying to check what will be the gas limit for the next block, I query pending block details via RPC for this.
Here is example of logs from my program
Current block number:13280098; gas limit: 30000000
Pending block number13280099; gas limit: 29970705 
-----Block number13280099 mined
Current block number: 13280099; gas limit: 30000000 
......

my geth configuration:
[Eth.Miner]
GasFloor = 8000000
GasCeil = 8000000

I tried to use my own private node, and alchemy node, both return the wrong numbers

**Comment by rjl493456442** [comment]
Gas limit can be adjusted by the miner with their own strategies. It's non realistic to estimate the pending block gaslimit.
Btw why do you need to guess the gasLimit?

**Comment by Gdocal** [comment]
So miners can use any gaslimit they want? There is no protocol rules? 

Why I need this, there is contract which force to call method with gas limit which fill 97% of block gas limit

**Comment by holiman** [comment]
> there is no protocol rules?

No, there are protocol rules, something like 1/1024th IIRC. Look into EIP [1559](https://eips.ethereum.org/EIPS/eip-1559):


		# check if the block changed the gas limit too much
		assert block.gas_limit < parent_gas_limit + parent_gas_limit // 1024, 'invalid block: gas limit increased too much'
		assert block.gas_limit > parent_gas_limit - parent_gas_limit // 1024, 'invalid block: gas limit decreased too much'

But the point is, we can't know if the miner will adjust it up or down or stay where it is.
