### ISSUE TITLE
How to check logs subscription status?

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#23639]
On occasions infura stops sending events on the web socket and need to resubscribe. Is there any way to check the web socket connection or the subscription status using the generated bindings of a contract?

https://community.infura.io/t/web3js-subscriptions-stop-firing-events-after-a-while-when-using-infura/2673/10

**Comment by krasi-georgiev** [comment]
hhm, or maybe this is a bug fixed in https://github.com/ethereum/go-ethereum/pull/23556

**Comment by fjl** [comment]
Please provide an example of the Go code you are using to access the infura websocket server.

**Comment by krasi-georgiev** [comment]
yes already upgraded and will reopen if the issue it still present
