### ISSUE TITLE
Elegant implement for struct address/hash db store

### ISSUE THREAD

**Issue by Betula-L** [ethereum/go-ethereum#23641]
# Rationale

Why should this feature exist?

Currently, using struct `address/hash` will store as 20/32bit (blob) in database which is hard to index and manage. 
![image](https://user-images.githubusercontent.com/6059935/134796256-c2a74b84-5e24-4325-bf65-45216cc5f370.png)
![image](https://user-images.githubusercontent.com/6059935/134797581-7ae34281-d899-4b87-8a1f-c50cecf86277.png)

# Implementation

Do you have ideas regarding the implementation of this feature?
1. Store address/hash as string rather than []byte.
2. Support Scan() both string and []byte.

Are you willing to implement this feature?
Yes.

**Comment by holiman** [comment]
Having addresses as `20` bytes of data is simple: there is no invalidness. Any `20` bytes can represent any address. If you instead use `44` bytes to represent a hex-encoded version of it, multiple errors must be handled: non-0x prefix, invalid hex-encoding. Plus it takes up more than double the space. 

It may also lead to ambiguity in parsing, e.g. an address scan of `0x112233445566778800`-- this is `20` bytes, but is it the address  `0x3078313132323333343435353636373738383939` or the address `0x00...112233445566778800` ? 

```
00000000: 3078 3131 3232 3333 3434 3535 3636 3737  0x11223344556677
00000010: 3838 3939                                8899
```
