### ISSUE TITLE
Geth installation on Windows 10

### ISSUE THREAD

**Issue by Gresliebear** [ethereum/go-ethereum#23647]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

Does anyone know? what is causing PATH not to automatically update? original length 1028 >1024?

![image](https://user-images.githubusercontent.com/13157730/134835258-0f77f843-ac8a-48cb-a3ff-c32fdebb4090.png)

Also Saving to Drive issues I set my execution drive to E:\ but its saving C:\ when syncing 

I cannot find the data to sync on C:\ to remove it

**Comment by verheesj** [comment]
> This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.
> 
> Does anyone know? what is causing PATH not to automatically update? original length 1028 >1024?
> 
> ![image](https://user-images.githubusercontent.com/13157730/134835258-0f77f843-ac8a-48cb-a3ff-c32fdebb4090.png)
> 
> Also Saving to Drive issues I set my execution drive to E:\ but its saving C:\ when syncing
> 
> I cannot find the data to sync on C:\ to remove it

In response to the 1028 > 1024 (unable to set path) - please can you confirm your operating system to allow me to look into this problem further?

Geth will utilize the origin of where it is situated. To overcome this, you need to specifically set the flag `--datadir` to the path you want the data to be situated.

**Comment by Gresliebear** [comment]
Windows 10?

**Comment by fjl** [comment]
This is a limitation in the installer framework (NSI) that we use. The maximum string length is 1024, so we cannot update the PATH environment variable. You will need to add it to the PATH yourself in system settings.
