### ISSUE TITLE
Geth crash on Ubuntu 14.04

### ISSUE THREAD

**Issue by scrawl** [ethereum/go-ethereum#2364]
#### System information

Geth
Version: 1.3.5
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go

Installed from ethereum stable PPA

OS & Version: Linux Ubuntu 14.04 64 bit
#### Steps to reproduce the behaviour

Left geth running over night to sync the blockchain. The crash happened after several hours somewhere near block 809187.
#### Backtrace

http://pastebin.com/N46QkFFd

**Comment by scrawl** [comment]
Happened again, crash while syncing. Backtrace:

http://pastebin.com/b5uT0j1f

**Comment by obscuren** [comment]
Thanks. We're looking in to this

**Comment by scrawl** [comment]
You're welcome. Should I post more stack traces if I get more crashing, or are these all the same?

**Comment by obscuren** [comment]
No I've found the issue. Thanks

**Comment by obscuren** [comment]
The highest chance for this to happen is during *sync*. The problem is a concurrent array access during execution.

**Comment by i-am-vivek** [comment]
Is this issue fixed? I got the same issue here. Is it because of RAM? Can you help me out ? @obscuren
