### ISSUE TITLE
evm t9n should reject transactions with low gasLimit

### ISSUE THREAD

**Issue by marioevz** [ethereum/go-ethereum#23668]
# Rationale

Why should this feature exist?
evm t9n is used on transaction tests and negative test cases where the transaction is properly formatted but the gasLimit is extremely low or even zero.
Currently test suite TransactionTests implies that the intrinsic transaction gas requirements must also be checked in order for the transaction to be considered valid.
The client is currently accepting these transactions, and the negative test cases incorrectly succeed.

E.g. in String10MbData test case (https://github.com/ethereum/tests/blob/develop/src/TransactionTestsFiller/ttData/String10MbDataFiller.json), reducing the gasLimit to zero results in the client not rejecting the transaction, even though the limit is lower than necessary for the transaction to be valid.

What are the use-cases?
Transaction negative test cases.

**Comment by winsvega** [comment]
A note from me. 

t9n does not check intrinsic gas. Our Transaction tests assume that transaction is invalid if it does not specify enough gas to cover its intrinsic costs. this is done to verify transaction intrinsic gas formulas on different clients. 

intrinsic gas = tx.base_cost + tx.data * tx_data_price 
and so on. for new transactions it also affects accessLists.

**Comment by winsvega** [comment]
Plus. would be nice to still have transaction hash for invalid rlps as the hash does not depend on transaction validity. 
when t9n return an error it can also return tr hash field with error.

**Comment by holiman** [comment]
I worked on this a bit today:https://github.com/holiman/go-ethereum/tree/fix_t9n_gascheck 

Need to add some tests for it, so no PR yet. However, I agree it limits the versatility if the tool doesn't show the hash/signer for a tx which has too low intrinsic gas.

**Comment by marioevz** [comment]
As I understand it, it would be useful for the test side to have a reference hash or identifier to pinpoint which input we sent caused which error, but @winsvega please correct me if I am misunderstanding the request.

**Comment by holiman** [comment]
Well,  as you point out; 
- The hash is different between legacy and typed, 
- for hashing a typed tx, the type byte is treated special. 

So in order to hash it correctly, one does need to parse it as a tx, not just feed the bytes into the hasher. Anyway, I'm skipping it for now, but I'm open to making modifications if there are things needed for building certain types of tests.
