### ISSUE TITLE
Rinkeby network. Error: cannot read property 'calls' of undefined in server-side tracer function 'fault'

### ISSUE THREAD

**Issue by enertom** [ethereum/go-ethereum#23660]
#### System information

Geth version: `"Geth/v1.10.9-stable-eae3b194/linux-amd64/go1.17.1`
OS & Version: Linux

Params: --rinkeby --syncmode full --gcmode=archive --snapshot=true

#### Actual behaviour

When i try to call the method debug_traceTransaction on Rinkeby network:

````
сurl -X POST -H "Content-Type: application/json" --data '{"method": "debug_traceTransaction","params": ["0xdf8f0fc660ccc30c7d41f2fffa4b582c629d59597fb981019f0415a82ea9d7cd",{ "tracer": "callTracer","timeout": "100s" }],"jsonrpc": "2.0","id": 1}' http://ip:port
````
i get the error - 
````
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"TypeError: cannot read property 'calls' of undefined    in server-side tracer function 'fault'"}}
````
#### Expected behaviour
Correct traced response from node

**Comment by nikashitsa** [comment]
I have same issue on Mainnet with partially executed transactions like this https://etherscan.io/tx/0xc3e19ca9c77ebe65b6ba927932ee6dcce69ae4eb324d8ecfac020f977a8eb5d3

**Comment by MariusVanDerWijden** [comment]
A quick workaround is to use `callTracerLegacy` instead of `callTracer` which will use the pre v.10.9. behavior

**Comment by enertom** [comment]
> A quick workaround is to use `callTracerLegacy` instead of `callTracer` which will use the pre v.10.9. behavior

@MariusVanDerWijden if i use `callTracerLegacy` tracer  instead of `callTracer` the node crashes

**Comment by MariusVanDerWijden** [comment]
That's weird. With what error message does it crash?
cc @s1na

**Comment by enertom** [comment]
node shutdown without any error

**Comment by s1na** [comment]
We found the original issue and will submit a fix today. But I haven't been able to reproduce the node crash using `callTracerLegacy` yet.

**Comment by enertom** [comment]
i have issue only on rinkeby

**Comment by enertom** [comment]
@s1na I built node from https://github.com/s1na/go-ethereum/tree/fix/call-tracer-fault : `TypeError: cannot read property 'calls'` is disappeared, but the error with shutdown doesn't disappear on rinkeby (tried with callTracerLegacy and callTracer).

**Comment by holiman** [comment]
> but the error with shutdown doesn't disappear on rinkeby (tried with callTracerLegacy and callTracer).

How much `reexec` are you using?

**Comment by holiman** [comment]
I've had the same crash when I tried it via docker, but it worked perfectly (both legacy and normal) on native geth.

**Comment by enertom** [comment]
> > but the error with shutdown doesn't disappear on rinkeby (tried with callTracerLegacy and callTracer).
> 
> How much `reexec` are you using?

I don't use `reexec`, i have full archive node `--gcmode=archive`

**Comment by enertom** [comment]
> I've had the same crash (without stacktrace) when I tried it via docker, but it worked perfectly (both legacy and normal) on native geth.

I tried without docker - it's working. Thanks for the temporary solution
