### ISSUE TITLE
How to Run Faucet on private network on Ethereum local node #23608

### ISSUE THREAD

**Issue by amaan-mohd** [ethereum/go-ethereum#23671]
Hi There,

Sorry for the delay in response, I have read this document lots of time but still no clues how should I run the Faucet.

All the time getting an error when use Faucet --help as below

faucet --help
Usage : faucet (--in|--out|--err|--fd N)+ [--once] [--verb(|ose)] [--quiet] [--unix] [--foreignport ] [--foreignhost ] [--localhost ] [--daemon] [--serial] [--shutdown (r|w)] [--pidfile fname] [--noreuseaddr] [--backlog n] -[i][o][e][#3[,4[,5...]]][v][1][q][u][d][s] [-p ] [-h ] [-H ] command args

Is there any documents where I can see the command example for running it smoothly?

Many thanks in advance

**Comment by holiman** [comment]
Answered here: https://github.com/ethereum/go-ethereum/issues/23608#issuecomment-932131494

**Comment by amaan-mohd** [comment]
Hi @holiman ,

The document is still not clear on how to execute the same.

Can you help us with the steps instructions
