### ISSUE TITLE
NoUSB in Clef

### ISSUE THREAD

**Issue by Zachinquarantine** [ethereum/go-ethereum#23680]
In Clef, the NoUSB flag is still used, and I'm working on a PR to remove it from the geth client, but if I remove the NoUSB flag from cmd/utils, that will completely break Clef. So, I guess my question is: is it safe to disable usb monitoring by default in Clef and give users time to update their configs, and then remove NoUSB there too a couple of releases later?

**Comment by holiman** [comment]
I would rather keep usb by default in clef. It can be moved to be a non-common flag though, living only in clef.
