### ISSUE TITLE
Memory leak on txpool priced urgent list

### ISSUE THREAD

**Issue by ferranbt** [ethereum/go-ethereum#23690]
#### System information

This behaviour was found on Polygon PoS (upstream v1.10.8) but I think it also affects Go-ethereum, London fork **is not** enabled yet in our chain.

#### Expected behaviour

Some nodes on the Polygon PoS network have been having OOM crashes lately since the London changes were upstreamed. On pprof we found out that much of the allocated memory was on transactions.

![image](https://user-images.githubusercontent.com/30872539/136337294-f466ab0c-6fa3-4fb7-9dd6-c68a10ccc5e9.png)

We though that the issue was either on:
- Transaction pool.
- Broadcast announcer.

This error was not reproducible and it would take at least a day to show up on the metrics. Some nodes even reported more than 100Gb of RAM because of this.

On the txpool we could not find any out of place metrics till we added (#23691) and we found this:

![image](https://user-images.githubusercontent.com/30872539/136338275-f13b7d3b-7f59-4130-9c5e-4dd640292335.png)

At some point, the size of the urgent list in the transaction pool starts to grow non-stop at the same time as the memory, this happens until the node runs out of memory (note that there are millions of transactions in the urgent list!). Besides, in the chart we can see that there are no more "reheap" metrics being emitted, which makes sense since that indicates that the urgent list is being cleaned.

In this node the max txpool size was on the 100k and all the transactions were inserted on the pool with the normal peer to peer gossip protocol.

IMHO, the problem is that under certain unknown circumstances, the txpool gets stuck and keeps adding new transactions into the urgent list without cleaning the old ones, this is, the Reheap method is not called anymore (no more reheap metrics).

However, if the London fork **is** enabled as in the Ethereum mainnet network, SetBaseFee is called periodically [here](https://github.com/ethereum/go-ethereum/blob/067084fedab1d50e224e40e6442a7740fc53611a/core/tx_pool.go#L1183) and the urgent list is cleaned automatically, that is why the Ethereum mainnet has not seen this issue so far. But, if London fork **is not** enabled as in Polygon PoS, this does not happen. We found a solution [here](https://github.com/maticnetwork/bor/pull/201) by calling Reheap if London is not enabled and we have not seen the problem so far.

Though I do not think there is a need for immediate action since we found a workaround (we can PR it if you guys want it) and the Ethereum mainnet will not likely find it on production I think it is good to keep in mind that there might be a memory leak on the priced list if not used correctly.

**Comment by bassoy** [comment]
Is there any update on this issue?

**Comment by MariusVanDerWijden** [comment]
It might have already been fixed by this: https://github.com/ethereum/go-ethereum/commit/067084fedab1d50e224e40e6442a7740fc53611a
I can not replicate it whatsoever

**Comment by holiman** [comment]
Since we've failed to repro, and believe it's already fixed, I'm closing this. Feel free to reopen (or open a new one) if the issue persists.
