### ISSUE TITLE
Ethereum RPC: curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by hackappcom** [ethereum/go-ethereum#237]
Hi, I'm trying to talk with node using RPC server and this manual https://github.com/ethereum/wiki/wiki/Generic-JSON-RPC
But after each request I  get nothing:

bright ~> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":null,"id":1}' http://localhost:8080 -vvv
* Rebuilt URL to: http://localhost:8080/
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> POST / HTTP/1.1
> User-Agent: curl/7.39.0
> Host: localhost:8080
> Accept: */*
> Content-Length: 62
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 62 out of 62 bytes
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server

Node logs:

[02:36:11 bright:~/go/bin]$./ethereum -loglevel=5 -rpc=true
2015/01/06 02:36:13 [CLI] Main address ee45de53b67964a4fdb9870b2f2bfa19807f0339
2015/01/06 02:36:13 [STATE] (+) 51ba59315b3a95761d0863b05ccc7a7f54703d99
2015/01/06 02:36:13 [STATE] (+) e4157b34ea9615cfbde6b4fda419828124b70c78
2015/01/06 02:36:13 [STATE] (+) b9c015918bdaba24b4ff057a92a3873d6eb201be
2015/01/06 02:36:13 [STATE] (+) 6c386a4b26f73c802f34673f7248bb118f97424a
2015/01/06 02:36:13 [STATE] (+) cd2a3d9f938e13cd947ec05abc7fe734df8dd826
2015/01/06 02:36:13 [STATE] (+) 2ef47100e0787b915105fd5e3f4ff6752079d5cb
2015/01/06 02:36:13 [STATE] (+) e6716f9544a56c530d868e4bfbacb172315bdead
2015/01/06 02:36:13 [STATE] (+) 1a26338f0d905e295fccb71fa9ea849ffa12aaf4
2015/01/06 02:36:13 [CHAIN] Last block (#0) 779b1b620b03c0fb24963e183d5e88e3dbe4484e3f6e2aa05942e3be7b48e179
2015/01/06 02:36:13 [CLI] Starting Ethereum(G)/v0.7.11/linux/go1.4
2015/01/06 02:36:13 [JSON] Starting JSON-RPC server
2015/01/06 02:36:13 [SERV] Ready and accepting connections
2015/01/06 02:36:13 [SERV] Retrieving seed nodes
2015/01/06 02:36:13 [SERV] Found DNS Go Peer: 54.72.69.180:30303
2015/01/06 02:36:13 [SERV] Found DNS Bootstrap Peer: 54.200.139.158:30303
2015/01/06 02:36:13 [SERV] Server started
2015/01/06 03:05:52 [JSON] Incoming request.

**Comment by obscuren** [comment]
That's because JSON RPC is over plain TCP/IP and not HTTP. We'll switch over to serving over http soon. See https://github.com/ethereum/go-ethereum/issues/238

**Comment by hackappcom** [comment]
Thanks!

**Comment by gregbkr** [comment]
Hello everyone,

I tried to understand your discussion but not sure if it is answering my issue. I got the same error: "curl: (52) Empty reply from server", but ONLY when the node is running in a container (maybe a docker only issue...?).

My commands:

    docker run -d --name=eth -v $PWD:/data -p 8545:8545 -p 30303:30303 ethereum/client-go --networkid 12011 --genesis /data/mygenesis.json --datadir  /data/data_node1 --nodiscover --rpc --rpcport 8545 --rpccorsdomain '"*"'

    curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' localhost:8545
    curl: (52) Empty reply from server

    docker exec eth curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' localhost:8545
    {"id":1,"jsonrpc":"2.0","result":["0x8dae714e9227258a1d5a15352a69ed3243a25e09","0xeb41741fdba96fe200a0427237893c97f887cdb5"]}

I can query from inside the container, but not from outside (port are indeed mapped -p 8545:8545).
Any help will be great!

Thanks a lot!
And very good week! ;-)
Greg.

**Comment by pulasthibandara** [comment]
For future reference: Docker running on Windows/mac, you would have to specify `--http.addr "0.0.0.0"` as docker runs on its own VM.
