### ISSUE TITLE
GETH randomly pauses in Windows 10, continues after keyboard input

### ISSUE THREAD

**Issue by justinf123** [ethereum/go-ethereum#23704]
#### System information

Geth version: 1.10.8-stable-26675454
OS & Version: Windows 10 Home 21H1 (64 Bit), 3Ghz, 32 GB RAM, multiple SSD's.

#### Expected behaviour

GETH run unattended, continuous operation.

#### Actual behaviour

Perhaps once every 24 - 48 hours, GETH completely pauses IE no screen output, external programs accessing GETH begin to timeout etc.

If I click on the GETH (DOS) window and hit return or ctrl+c GETH resumes again from the point it paused.
I have noted, this does not seem to occur when GETH is in the background (IE not actively being displayed on the screen).

#### Steps to reproduce the behaviour

I am starting GETH with the following command:

`"c:\Program Files\Geth\geth.exe" --ropsten --http --http.api eth,net,web3,personal,miner,admin,txpool,debug --http.corsdomain '*' --http.addr 127.0.0.1 --http.port 8545 --metrics --mine --syncmode "full" --miner.etherbase { my account } --datadir d:\Ethereum\ropsten\ --allow-insecure-unlock --maxpeers 9999 --maxpendpeers 9999 --whitelist 10920274=0xfd652086d220d506ae5b7cb80fde97d2f3f7028d346cc7d9d384a83d3d638532 --rpc.allow-unprotected-txs --txpool.globalslots=250000 --txpool.globalqueue=50000`

The issue occurs when the GETH window is being displayed on the screen.  The occurrence is random.

I appreciate this is difficult to reproduce, if you need verbose logs, please let me know how to create and I am happy to supply.

**Comment by secmask** [comment]
window powershell will pause the app in copy mode(square char appear indicator), which you may trigger when use mouse to click in side terminal window, keyboard input cancel copy mode, not sure this yours case but you can try

![image](https://user-images.githubusercontent.com/382284/148376356-a07143fc-5913-4673-8cdb-7a4d049994bb.png)
