### ISSUE TITLE
Missing logs in rpc eth_getLogs result.

### ISSUE THREAD

**Issue by debris** [ethereum/go-ethereum#2370]
#### System information

Geth version:

```
Geth
Version: 1.4.0-unstable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go
```

OS & Version:

```
Linux workhorse 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
#### Expected behaviour

rpc request `eth_getLogs` should return 1602 results

```
curl -X POST --data '{"id":8,"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock":"0x0","toBlock":"0xf0be2", "address": "0x33990122638b9132ca29c723bdf037f1a891a70c"}]}' -H "Content-Type: application/json" http://127.0.0.1:3030
```
#### Actual behaviour

it returned 1595 results, 7 logs are missing
#### Steps to reproduce the behaviour

run provided curl request on geth and parity and compare results.

```
parity -j
```

```
geth --rpc --rpcport "3030"
```

dumped logs and tiny script to compare then is also here:

https://github.com/debris/missing-logs

**Comment by obscuren** [comment]
Thanks for reporting. Have you by any chance tried `master` branch? In any case we'll look in to it.

**Comment by obscuren** [comment]
I ran this on the `master` and `develop` branch and it returns the same logs in the file `parity.json`. `develop` and `master` are also consistent with each other and I  was unable to reproduce the error you mention. Could you tell us more about your setup?

On a side node, @debris, the returned logs do not contain the canonical number representation as detailed in the spec. Numbers are noted as `0x1` and not `0x01`.

**Comment by karalabe** [comment]
@debris Also could you detail whether you interrupted sync or fast sync, whether it reported sync failures and continued afterwards? If something's missing on your end there's probably a bug, but it would be nice to know exactly what corner case managed to hit it.

**Comment by obscuren** [comment]
Ping @debris

**Comment by debris** [comment]
> Thanks for reporting. Have you by any chance tried master branch? In any case we'll look in to it.

No, I haven't but I can check.

> @debris Also could you detail whether you interrupted sync or fast sync, whether it reported sync failures and continued afterwards? If

I used fast sync. I did not pay attention if it reporting sync failures.

@obscuren , I will PM you and give you access to machine running this node.

**Comment by bobsummerwill** [comment]
Hey guys ... was this some transitional thing which has been resolved now?  @debris?

**Comment by debris** [comment]
I assume it's been resolved, cause I reported it ages ago
