### ISSUE TITLE
chain not synced beyond EIP-155 replay-protection fork block

### ISSUE THREAD

**Issue by texanraj** [ethereum/go-ethereum#23712]
#### System information

Geth version: `geth version`
geth version
Geth
Version: 1.10.8-stable
Git Commit: 26675454bf93bf904be7a43cce6b3f550115ff90
Architecture: amd64
Go Version: go1.16.7
Operating System: linux
GOPATH=
GOROOT=go

#### Expected behaviour
Geth should work fine but craps out all the time on Rocketpool

#### Actual behaviour
Geth FAILS on mainnet!

#### Steps to reproduce the behaviour
eth1_1           | WARN [10-11|21:45:27.250] Served eth_chainId                       conn=172.18.0.5:53932 reqid=2 t="18.89µs"  err="chain not synced beyond EIP-155 replay-protection fork block"
eth1_1           | INFO [10-11|21:45:33.422] Looking for peers                        peercount=0 tried=26 static=0
eth1_1           | WARN [10-11|21:45:42.249] Served eth_chainId                       conn=172.18.0.5:53932 reqid=2 t="24.971µs" err="chain not synced beyond EIP-155 replay-protection fork block"
eth1_1           | INFO [10-11|21:45:44.070] Looking for peers                        peercount=0 tried=26 static=0
eth1_1           | INFO [10-11|21:45:54.100] Looking for peers                        peercount=0 tried=34 static=0
eth1_1           | WARN [10-11|21:45:57.249] Served eth_chainId                       conn=172.18.0.5:53932 reqid=2 t="45.065µs" err="chain not synced beyond EIP-155 replay-protection fork block"
eth1_1           | INFO [10-11|21:46:04.174] Looking for peers                        peercount=1 tried=37 static=0
eth1_1           | INFO [10-11|21:46:04.219] Block synchronisation started
eth1_1           | CRIT [10-11|21:46:04.219] Failed to disable snapshots              err="leveldb: internal key \"\\xa1\\x10\\xde+\\x00\\xad\\xec\\x14bA#\\xbd\\xc9\\xf0\\xbc!\\xca\\xf8\\xf16*k@'\\xc8ʝ,\\\"c\\x12+\\x01\\xe5\\x8aL\\x06\\x00\\x00\\x00\\xf8B\\x9f \" corrupted: invalid type"

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
Your disk seems to be faulty or your database files corrupted by something external to Geth. You'll need to nuke the entire database and start over, though I'd check the disk for errors first, having corrupted content in the files means something is very wrong.
