### ISSUE TITLE
Node not keeping sync after Writing clean trie cache to disk

### ISSUE THREAD

**Issue by IamHuskar** [ethereum/go-ethereum#23724]
#### System information

Geth version: v1.10.8
OS & Version: Windows
Commit hash : 26675454bf93bf904be7a43cce6b3f550115ff90

#### Expected behaviour
keep sync 

#### Actual behaviour
after some hours (maybe 6~8 hours). node stop keeping sync

#### Steps to reproduce the behaviour

```
geth.exe --mine --miner.etherbase "xxxxxxxxxxxxxxxxxxxxxx" --syncmode "snap"  --port "30303" --cache=4096 --datadir f:/data/geth --ipcpath "\\.\pipe\geth.ipc" --maxpeers 999  --maxpendpeers 999  --http --ws --http.port 8545 --ws.port 8546 --ws.api "admin,debug,eth,net,web3,personal,clique,ethash,miner,rpc,txpool" --http.api "admin,debug,eth,net,web3,personal,clique,ethash,miner,rpc,txpool" 
```

I have some eth_call function(contract call) via http rpc at some point (maybe block_head_event or log event)
and I have some unclean shutdowns by ctrl+c

#### Backtrace

![1634099720(1)](https://user-images.githubusercontent.com/6307407/137067901-aa31d72f-a3a3-4555-b98b-6e36723863b3.png)
sorry I only have screenshots .  It shows:
```
Writing clean trie cache to disk                     02:56:01.749
Regenerated local transaction journal           02:56:01.750
about 20 minutes later
Snapshot extension registration failed         03:12:37.173
```

I search log string in source code 

```
// saveCache saves clean state cache to given directory path
// using specified CPU cores.
func (db *Database) saveCache(dir string, threads int) error {
	if db.cleans == nil {
		return nil
	}
	log.Info("Writing clean trie cache to disk", "path", dir, "threads", threads)

	start := time.Now()
	err := db.cleans.SaveToFileConcurrent(dir, threads)
	if err != nil {
		log.Error("Failed to persist clean trie cache", "error", err)
		return err
	}
	log.Info("Persisted the clean trie cache", "path", dir, "elapsed", common.PrettyDuration(time.Since(start)))
	return nil
}
```

"Persisted the clean trie cache" should follow "Writing clean trie cache to disk"

maybe SaveToFileConcurrent hang? or deadlock?

**Comment by IamHuskar** [comment]
and I have some unclean shutdowns by ctrl+c

**Comment by holiman** [comment]
Does the folder  'f:\data\geth\geth\triecache\` exist? What is the content? 
Example how it looks on one our our benchmarking nodes: 
```
 Oct 20 07:48:21 bench02.ethdevops.io geth INFO [10-20|05:48:21.521] Writing clean trie cache to disk path=/datadir/geth/geth/triecache threads=1
....
Oct 20 07:48:22 bench02.ethdevops.io geth INFO [10-20|05:48:22.762] Persisted the clean trie cache path=/datadir/geth/geth/triecache elapsed=1.240s 
```
It finished within a couple of seconds. 

What type of disk/fs is `f:` ? Is it an internal SSD/Nvme drive, or is it some external drive, such as a USB drive or a network drive?

One thing that might make this slower, is the following: 
The contents are first written to a temporary file, which most likely is _not_ `f:`: 
```
	if err := c.save(tmpDir, concurrency); err != nil {
		return fmt.Errorf("cannot save cache data to temporary dir %q: %s", tmpDir, err)
	}

```
Then a `os.Rename` is performed to swap out the 'real' file with the temporary one:
```
	if err := os.Rename(tmpDir, filePath); err != nil {
		return fmt.Errorf("cannot move temporary dir %q to %q: %s", tmpDir, filePath, err)
	}
``` 

AFAIC, the `rename` operation does not work across file system boundaries; **but** it should return an error if the rename operation fails. 
So last question -- could you check your os tempdir and see if it contains files with the prefix `fastcache.tmp.` ?

**Comment by IamHuskar** [comment]
> Does the folder 'f:\data\geth\geth\triecache` exist? What is the content? Example how it looks on one our our benchmarking nodes:
> 
> ```
>  Oct 20 07:48:21 bench02.ethdevops.io geth INFO [10-20|05:48:21.521] Writing clean trie cache to disk path=/datadir/geth/geth/triecache threads=1
> ....
> Oct 20 07:48:22 bench02.ethdevops.io geth INFO [10-20|05:48:22.762] Persisted the clean trie cache path=/datadir/geth/geth/triecache elapsed=1.240s 
> ```
> 
> It finished within a couple of seconds.
> 
> What type of disk/fs is `f:` ? Is it an internal SSD/Nvme drive, or is it some external drive, such as a USB drive or a network drive?
> 
> One thing that might make this slower, is the following: The contents are first written to a temporary file, which most likely is _not_ `f:`:
> 
> ```
> 	if err := c.save(tmpDir, concurrency); err != nil {
> 		return fmt.Errorf("cannot save cache data to temporary dir %q: %s", tmpDir, err)
> 	}
> ```
> 
> Then a `os.Rename` is performed to swap out the 'real' file with the temporary one:
> 
> ```
> 	if err := os.Rename(tmpDir, filePath); err != nil {
> 		return fmt.Errorf("cannot move temporary dir %q to %q: %s", tmpDir, filePath, err)
> 	}
> ```
> 
> AFAIC, the `rename` operation does not work across file system boundaries; **but** it should return an error if the rename operation fails. So last question -- could you check your os tempdir and see if it contains files with the prefix `fastcache.tmp.` ?
I copy the geth datadir from c: to f:
f:\data\geth\geth\triecache exist 
f: is internal SSD driver 

 I delete the whole directory and restart geth again. so I can't confirm that  whether  it contains files with the prefix `fastcache.tmp.` in my  os tempdir.
I will reply to you next time I encounter this problem

**Comment by guiltylelouch** [comment]
@holiman Same issue and i got stacks.
[stack.txt](https://github.com/ethereum/go-ethereum/files/7811794/stack.txt)

**Comment by guiltylelouch** [comment]
There two goroutine call runtime_SemacquireMutex， maybe deadlock here?

goroutine 24023987 [semacquire, 598 minutes]:
sync.runtime_SemacquireMutex(0xaa9, 0x30, 0x46a9d9)
	runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000dfcb60)
	sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	sync/mutex.go:81
sync.(*RWMutex).Lock(0xc000dfcad8)
	sync/rwmutex.go:111 +0x36
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc000dfc880, {0xc0a8ed4428, 0x1, 0x1})
	github.com/ethereum/go-ethereum/core/blockchain.go:1842 +0xb0a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc01cc57a40, {0xc0a8ed4420, 0x1, 0xc1480e4180})
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1805 +0x48a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc01cc57a40)
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1777 +0xaf
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1()
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:648 +0x70
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:648 +0x65
	
goroutine 24023080 [semacquire, 598 minutes]:
sync.runtime_SemacquireMutex(0x10, 0x8, 0x7)
	runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000dfcb60)
	sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	sync/mutex.go:81
sync.(*RWMutex).Lock(0xc000dfcad8)
	sync/rwmutex.go:111 +0x36
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc000dfc880, {0xc1b5a62a58, 0x1, 0x1})
	github.com/ethereum/go-ethereum/core/blockchain.go:1842 +0xb0a
github.com/ethereum/go-ethereum/eth.newHandler.func3({0xc1b5a62a58, 0xc1e05cc920, 0xb2e1e797d3e4f5b1})
	github.com/ethereum/go-ethereum/eth/handler.go:237 +0x5f8
github.com/ethereum/go-ethereum/eth/fetcher.(*BlockFetcher).importBlocks.func1()
	github.com/ethereum/go-ethereum/eth/fetcher/block_fetcher.go:858 +0x922
created by github.com/ethereum/go-ethereum/eth/fetcher.(*BlockFetcher).importBlocks
	github.com/ethereum/go-ethereum/eth/fetcher/block_fetcher.go:829 +0x40f
