### ISSUE TITLE
ropsten network. The height is inconsistent with the browser

### ISSUE THREAD

**Issue by Black52** [ethereum/go-ethereum#23734]
Why my Latest Blocks  always lower than the one on the browser
my:
> eth.syncing
{
  currentBlock: 503348,
  highestBlock: 11218360,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 0
}

https://ropsten.etherscan.io/:
Latest Blocks: 11226112

version: geth-linux-amd64-1.10.8

**Comment by holiman** [comment]
It's because you are syncing. Looks like a full sync, still in the 500K range. You might want to consider doing a regular (snap) sync instead

**Comment by holiman** [comment]
Yes, that's a bit odd. Those blocks import pretty quickly, around `10ms`, so they should be catching up pretty fast, but it's only importing blocks every once in a while, with 4-8 seconds in between.

**Comment by Black52** [comment]
> Yes, that's a bit odd. Those blocks import pretty quickly, around `10ms`, so they should be catching up pretty fast, but it's only importing blocks every once in a while, with 4-8 seconds in between.

Yes， But the display has been synchronized。But always 8000 short of the browser's latest height

**Comment by Black52** [comment]
> 所以，这不是处理速度问题：
> 
> ```
> INFO [10-14|18:08:42.733] Imported new chain segment               blocks=1       txs=9         mgas=4.105   elapsed=8.879ms     mgasps=462.315  number=11,219,232 hash=3b9f2c..1c422c dirty=10.75MiB
> INFO [10-14|18:08:50.787] Imported new chain segment               blocks=1       txs=4         mgas=0.590   elapsed=9.177ms     mgasps=64.277   number=11,219,233 hash=792427..2ed2cd dirty=10.72MiB
> INFO [10-14|18:09:31.066] Imported new chain segment               blocks=1       txs=15        mgas=0.869   elapsed=10.623ms    mgasps=81.774   number=11,219,234 hash=2f5e7c..c7880a dirty=10.68MiB
> INFO [10-14|18:09:44.475] Imported new chain segment               blocks=1       txs=7         mgas=1.774   elapsed=9.294ms     mgasps=190.906  number=11,219,235 hash=87876d..77345b dirty=10.69MiB
> INFO [10-14|18:09:51.021] Imported new chain segment               blocks=1       txs=5         mgas=0.591   elapsed=11.593ms    mgasps=50.983   number=11,219,236 hash=19a4ec..0e2a04 dirty=10.64MiB
> INFO [10-14|18:10:22.589] Imported new chain segment               blocks=1       txs=16        mgas=0.713   elapsed=14.691ms    mgasps=48.548   number=11,219,237 hash=a70464..b5a125 dirty=10.66MiB
> INFO [10-14|18:11:11.707] Imported new chain segment               blocks=1       txs=29        mgas=1.641   elapsed=14.644ms    mgasps=112.084  number=11,219,238 hash=a7e36d..b7d039 dirty=10.74MiB
> INFO [10-14|18:11:14.799] Imported new chain segment               blocks=1       txs=3         mgas=0.111   elapsed=8.162ms     mgasps=13.574   number=11,219,239 hash=7215c1..204499 dirty=10.70MiB
> INFO [10-14|18:12:06.416] Imported new chain segment               blocks=1       txs=21        mgas=0.852   elapsed=15.852ms    mgasps=53.718   number=11,219,240 hash=9c20e8..ae4c83 dirty=10.76MiB
> INFO [10-14|18:12:15.021] Imported new chain segment               blocks=1       txs=2         mgas=0.289   elapsed=13.930ms    mgasps=20.743   number=11,219,241 hash=154794..51ec00 dirty=10.78MiB
> INFO [10-14|18:12:39.460] Imported new chain segment               blocks=1       txs=11        mgas=4.901   elapsed=10.419ms    mgasps=470.356  number=11,219,242 hash=66d073..5add8f dirty=10.83MiB
> INFO [10-14|18:13:10.422] Imported new chain segment               blocks=1       txs=8         mgas=0.628   elapsed=9.119ms     mgasps=68.893   number=11,219,243 hash=496411..9f10fc dirty=10.84MiB
> INFO [10-14|18:13:22.600] Imported new chain segment               blocks=1       txs=8         mgas=0.659   elapsed=31.781ms    mgasps=20.727   number=11,219,244 hash=d89f91..339c9d dirty=10.73MiB
> INFO [10-14|18:13:28.520] Imported new chain segment               blocks=1       txs=2         mgas=0.097   elapsed=13.496ms    mgasps=7.223    number=11,219,245 hash=83660f..108254 dirty=10.68MiB
> INFO [10-14|18:13:28.535] Imported new chain segment               blocks=1       txs=0         mgas=0.000   elapsed=10.132ms    mgasps=0.000    number=11,219,246 hash=d4b3df..d12c4c dirty=10.65MiB
> INFO [10-14|18:13:45.426] Imported new chain segment               blocks=1       txs=7         mgas=0.419   elapsed=26.094ms    mgasps=16.057   number=11,219,247 hash=c74623..a4249d dirty=10.70MiB
> INFO [10-14|18:13:47.214] Imported new chain segment               blocks=1       txs=1         mgas=0.376   elapsed=12.843ms    mgasps=29.250   number=11,219,248 hash=bd0310..626b10 dirty=10.68MiB
> INFO [10-14|18:14:28.460] Imported new chain segment               blocks=1       txs=19        mgas=3.880   elapsed=17.989ms    mgasps=215.677  number=11,219,249 hash=54d5d4..a51269 dirty=10.84MiB
> INFO [10-14|18:14:29.686] Imported new chain segment               blocks=1       txs=0         mgas=0.000   elapsed=8.562ms     mgasps=0.000    number=11,219,250 hash=496bf1..c63af6 dirty=10.82MiB
> INFO [10-14|18:14:50.881] Imported new chain segment               blocks=1       txs=8         mgas=0.872   elapsed=12.267ms    mgasps=71.043   number=11,219,251 hash=acf5af..f7ef09 dirty=10.87MiB
> INFO [10-14|18:15:54.405] Imported new chain segment               blocks=1       txs=36        mgas=3.382   elapsed=94.754ms    mgasps=35.690   number=11,219,252 hash=7cdb00..55ecf1 age=1m3s       dirty=11.10MiB
> INFO [10-14|18:15:58.994] Imported new chain segment               blocks=1       txs=2         mgas=0.141   elapsed=15.460ms    mgasps=9.143    number=11,219,253 hash=6d358f..8a9d95 dirty=11.06MiB
> INFO [10-14|18:16:01.079] Imported new chain segment               blocks=1       txs=0         mgas=0.000   elapsed=8.078ms     mgasps=0.000    number=11,219,254 hash=181332..d3841a dirty=11.06MiB
> ```
> 
> 可能导致这种情况的一件事是，如果您的机器没有正确的时间。因此，如果您落后 8000 个区块，而区块时间为`14s`，那么您基本上总是落后 31 小时。Geth 不会导入一个块，除非它最多是`15m`在未来，所以如果你计算机上的日期滞后`31`几个小时，那就可以解释了。
> 
> 但是 OTOH，您日志中的时间戳并没有消失。但无论如何请检查一下。

My server system time is east 8：
# date -R
Fri, 15 Oct 2021 18:58:06 +0800

**Comment by dmitridr** [comment]
@Black52 I ran into a similar problem. Etherscan and what the geth client reported after syncing seemed to result in different top block heights. This is likely because Ropsten forked on block `10920274` and you ended up on the wrong fork, you can confirm which fork you are on by checking the hash of that block. The solution is in https://github.com/ethereum/go-ethereum/issues/23503

**Comment by Black52** [comment]
> @Black52我遇到了类似的问题。Etherscan 和 geth 客户端在同步后报告的内容似乎导致不同的顶部块高度。这很可能是因为 Ropsten 在区块上分叉，`10920274`并且您最终可能在错误的分叉上，您可以通过检查该区块的哈希来确认您在哪个分叉上。解决方案和正确的哈希列在[#23503 中](https://github.com/ethereum/go-ethereum/issues/23503)

Thank you very much. That solved my problem
