### ISSUE TITLE
eth vs geth on CPU mining bench inconsistency. ( most be a bug in either implementation).

### ISSUE THREAD

**Issue by smartbitcoin** [ethereum/go-ethereum#2374]
there was a ticket on eth++ which shows the cpu hashrate  inconsistency between c++ and go implements.
still now eth++ team still have no clue why it happens, so we doubt that it's a go eth 's bug.

the original ticket was here.
https://github.com/ethereum/webthree-umbrella/issues/288

wish go team can confirm where this inconsistency come from.

**Comment by obscuren** [comment]
Thanks for reporting this. CPU minimg (and especially the hash rate reporting) has very low priority. It might (and might very well not be) fixed *at some point*. If you require a fix I really suggest that you have a look yourself and try to patch it and send a PR. The code isn't that complicated
