### ISSUE TITLE
CRIT Failed to persist storage slots

### ISSUE THREAD

**Issue by pguardiario** [ethereum/go-ethereum#23759]
#### System information

Version: 1.10.10-stable
Git Commit: bb74230f2a93057b92bf58aab09c9438ce435f95    
Architecture: amd64
Go Version: go1.17.2
Operating System: linux
GOPATH=
GOROOT=go

#### Expected behaviour

Normal operation

#### Actual behaviour

geth crashes

#### Steps to reproduce the behaviour

geth --ws

#### Backtrace
```
CRIT [10-18|02:51:04.158] Failed to persist storage slots          err="write /root/.ethereum/geth/chaindata/000003.log: file too large"
```

**Comment by karalabe** [comment]
Check how much memory you allocated for caching, and if it's multi-gigabytes, make sure your file system supports storing that much data in a single file.
