### ISSUE TITLE
Sim backend returns 1 for SuggestGasPrice not Basefee

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum/go-ethereum#23752]
```go
// SuggestGasPrice implements ContractTransactor.SuggestGasPrice. Since the simulated
// chain doesn't have miners, we just return a gas price of 1 for any call.
func (b *SimulatedBackend) SuggestGasPrice(ctx context.Context) (*big.Int, error) {
	return big.NewInt(1), nil
}
```
-> Does not work post 1559, just return `pendingBlock.Header.Basefee` or something

**Comment by MariusVanDerWijden** [comment]
Sure!

**Comment by MariusVanDerWijden** [comment]
fixed

**Comment by deitch** [comment]
I just stumbled across this. Given that this is a simulated backend, how is the original base fee set? I am doing a simple chain creation and getting a base fee of some absurdly high number, something like 875000000.

What particularly threw me off was the function description:

> SuggestGasPrice implements ContractTransactor.SuggestGasPrice. Since the simulated chain doesn't have miners, we just return a gas price of 1 for any call.

That definitely is not 1.

I am not doing anything fancy, as simple as:

```go
	privateKey, err := crypto.GenerateKey()
	if err != nil {
		return nil, err
	}

	auth, err := bind.NewKeyedTransactorWithChainID(privateKey, big.NewInt(1337))
	if err != nil {
		return nil, err
	}

	balance := new(big.Int)
	balance.SetString("10000000000000000000", 10) // 10 eth in wei

	address := auth.From
	genesisAlloc := map[common.Address]core.GenesisAccount{
		address: {
			Balance: balance,
		},
	}

	blockGasLimit := uint64(4712388)
	client := backends.NewSimulatedBackend(genesisAlloc, blockGasLimit)
```

Stepping through, it looks like it creates it [here](https://github.com/ethereum/go-ethereum/blob/afe344bcf31bfb477a6e1ad5b862a70fc5c1a22b/accounts/abi/bind/backends/simulated.go#L78-L91) as part of `NewSimulatedBackendWithDatabase`, specifically as part of the `core.Genesis`, which has an option to set the `BaseFee` (but is unused here), which then is inherited in `core.NewBlockChain()`. I think.

```go
func NewSimulatedBackendWithDatabase(database ethdb.Database, alloc core.GenesisAlloc, gasLimit uint64) *SimulatedBackend {
	genesis := core.Genesis{Config: params.AllEthashProtocolChanges, GasLimit: gasLimit, Alloc: alloc}
	genesis.MustCommit(database)
	blockchain, _ := core.NewBlockChain(database, nil, genesis.Config, ethash.NewFaker(), vm.Config{}, nil, nil)

	backend := &SimulatedBackend{
		database:   database,
		blockchain: blockchain,
		config:     genesis.Config,
		events:     filters.NewEventSystem(&filterBackend{database, blockchain}, false),
	}
	backend.rollback(blockchain.CurrentBlock())
	return backend
}
```

Is this a bug in how `SuggestGasPrice()` works? Am I setting up the chain incorrectly? Or is it that it needs some option that is missing?
