### ISSUE TITLE
ERROR[10-18|21:46:35.250] Snapshot extension registration failed   peer=3246b006 err="peer connected on snap without compatible eth support"

### ISSUE THREAD

**Issue by garysdevil** [ethereum/go-ethereum#23767]
#### System information

Geth version: 1.10.9-stable
OS & Version: Linux (Linux version 5.4.0-84-generic (buildd@lgw01-amd64-050) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021)
execution: geth --datadir=/tank1/geth_Rinkeby/ethereumData/ --networkid 65535 --http --http.addr 0.0.0.0--http.port  9545 --ws --ws.addr 0.0.0.0 --ws.port 9544 --port 30303 --allow-insecure-unlock -http.corsdomain "*" --http.api eth,web3,personal,net,db,miner --rinkeby
#### Expected behaviour
Can sync block from network normally

#### Actual behaviour
```log
ERROR[10-18|21:56:14.904] Snapshot extension registration failed   peer=a4fc7232 err="peer connected on snap without compatible eth support"
INFO [10-18|21:56:20.501] Looking for peers                        peercount=1 tried=39 static=0
ERROR[10-18|21:56:20.501] Snapshot extension registration failed   peer=0257ce31 err="peer connected on snap without compatible eth support"
INFO [10-18|21:56:30.542] Looking for peers                        peercount=0 tried=37 static=0
INFO [10-18|21:56:40.542] Looking for peers                        peercount=1 tried=32 static=0
ERROR[10-18|21:56:46.665] Snapshot extension registration failed   peer=b3fcf00f err="peer connected on snap without compatible eth support"
INFO [10-18|21:56:50.768] Looking for peers                        peercount=0 tried=36 static=0
```

#### Steps to reproduce the behaviour
```bash
ip=0.0.0.0
geth --datadir=/tank1/geth_Rinkeby/ethereumData/ --networkid 65535 --http --http.addr ${ip} --http.port  9545 --ws --ws.addr ${ip} --ws.port 9544 --port 30303 --allow-insecure-unlock -http.corsdomain "*" --http.api eth,web3,personal,net,db,miner --rinkeby
```

#### Backtrace

````
[backtrace]
````

**Comment by gcsfred2** [comment]
> > Do you want to connect to the rinkeby network? If so the networkid for rinkeby is 4. The Snapshot extension registration error is because your peers misconfigured their nodes, not something you can do something about
> 
> How do I know that the rinkeby networked is 4?

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md#list-of-chain-ids
