### ISSUE TITLE
geth crashes on initial sync with `panic: runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by dlo** [ethereum/go-ethereum#23775]
#### System information

tldr: 

Geth Version: 1.10.10-stable
OS & Version: Linux 5.10.47
Commit hash: `bb74230f2a93057b92bf58aab09c9438ce435f95`

```
$ geth version
Geth
Version: 1.10.10-stable
Git Commit: bb74230f2a93057b92bf58aab09c9438ce435f95
Architecture: amd64
Go Version: go1.17.2
Operating System: linux
GOPATH=
GOROOT=go
```

```
$ uname -a
Linux a066a3ddc026 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 Linux
```

#### Expected behaviour

Geth syncs the blockchain without crashing.

#### Actual behaviour

Geth crashes with a runtime error.

#### Steps to reproduce the behaviour

Start geth with an empty data directory (`geth --mainnet --http`)

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xa657da]

goroutine 88430 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestorBinarySearch(0xc000196e00, 0xc048e64000, 0x1, 0xcd3d42, 0xffffffffffffffff)
      github.com/ethereum/go-ethereum/eth/downloader/downloader.go:966 +0x8da
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc000196e00, 0xc048e64000, 0x1e)
      github.com/ethereum/go-ethereum/eth/downloader/downloader.go:818 +0x2fb
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc000196e00, 0xc048e64000, {0xb, 0x86, 0x7c, 0xe, 0xa, 0xdd, 0x1c, 0x83, ...}, ...)
      github.com/ethereum/go-ethereum/eth/downloader/downloader.go:475 +0x4de
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0x205be60, {0xc017661c00, 0x7fc214252a10}, {0xb, 0x86, 0x7c, 0xe, 0xa, 0xdd, 0x1c, ...}, ...)
      github.com/ethereum/go-ethereum/eth/downloader/downloader.go:431 +0x4b0
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc000196e00, {0xc017661c00, 0x40}, {0xb, 0x86, 0x7c, 0xe, 0xa, 0xdd, 0x1c, ...}, ...)
      github.com/ethereum/go-ethereum/eth/downloader/downloader.go:326 +0x5c
github.com/ethereum/go-ethereum/eth.(*handler).doSync(0xc004342d00, 0xc0544f7440)
      github.com/ethereum/go-ethereum/eth/sync.go:230 +0x1fd
github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1()
      github.com/ethereum/go-ethereum/eth/sync.go:206 +0x29
created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
      github.com/ethereum/go-ethereum/eth/sync.go:206 +0xaf
````

**Comment by holiman** [comment]
Could you please provide the logs preceding that crash?

**Comment by dlo** [comment]
Update: this instance has now been running for days without a crash. I'll keep an eye on it.

**Comment by draven1099** [comment]
How did you fixed this? I'm also having the same issue

**Comment by draven1099** [comment]
![image](https://user-images.githubusercontent.com/93768661/140496529-0fe58aac-1b15-47b0-a7c7-1706b8c7a0ed.png)

**Comment by draven1099** [comment]
please help

**Comment by MariusVanDerWijden** [comment]
You have *a lot* of unclean shutdowns. It could be that one of those destroyed your data directory leaving your node in a bad state. The only good solution for you is to remove your data directory (usually .ethereum) and resync. (Just make sure to save the keystore if you have keys there)

**Comment by draven1099** [comment]
where can I find that data recovery?

**Comment by draven1099** [comment]
how can I remove my data directory sir?

**Comment by MariusVanDerWijden** [comment]
remove `%APPDATA%\Ethereum`, go to the explorer and type in `%APPDATA%` and delete the Ethereum folder

**Comment by MariusVanDerWijden** [comment]
Since it seems fixed at OP's side I'll close the issue. @dlo Please reopen if it comes up again

**Comment by dlo** [comment]
@MariusVanDerWijden Will do, I'm keeping the debugging statements in there until I see this happen again.

**Comment by dlo** [comment]
@draven1099 You can build a version of geth with the debugging statements I added if you want to dig in yourself. Here's the branch with the changes: https://github.com/dlo/go-ethereum/tree/2021-10-31-geth-debug/

**Comment by draven1099** [comment]
thank you.
