### ISSUE TITLE
network port 30303 could not be mapped: no UPnP or NAT-PMP router discovered

### ISSUE THREAD

**Issue by AugustoL** [ethereum/go-ethereum#2380]
#### System information

Geth version: `+1.3.5 Build from develop on commit https://github.com/ethereum/go-ethereum/commit/cfb3a8ea8f98ef5a31d9e4a84a66eb5857461a7b`
OS & Version: Linux
Commit hash : commit https://github.com/ethereum/go-ethereum/commit/cfb3a8ea8f98ef5a31d9e4a84a66eb5857461a7b
#### Expected behaviour

Not connecting to peers
#### Actual behaviour

Logging:
network port 30303 could not be mapped: no UPnP or NAT-PMP router discovered
#### Steps to reproduce the behaviour

Im using a custom networkid genesis, running a private network, all works great locally, but peers cant be find.

Same as: https://github.com/ethereum/go-ethereum/issues/890 (not fixed yet)

**Comment by ujwaliyer** [comment]
i am getting the same error. any ETA of the fix?

**Comment by fjl** [comment]
This message is harmless. Does your router have UPnP turned on?

**Comment by lunemec** [comment]
I had problems with Mikrotik router upnp. For some reason the geth could not create port forwarding via UPNP (it was enabled, because I have other apps using it).
I had to manually create 30303 port mapping in the router firewall.

I'm not sure if you want to explore this further...

**Comment by kiwina** [comment]
same here microtik dosnt get mapped

**Comment by Strydom** [comment]
I'm also having this problem on a private network. Trying to get peers to connect using the Bootnode but they're not connecting.

There are also people still responding to this thread #890 which has more detail around the problem

Nobody seems to be doing anything about it...

**Comment by fjl** [comment]
@karalabe says: UPnP discovery broadcast may get answered from a different IP than the one the broadcast was sent on. Some firewalls block those replies. We should listen to router announcements instead.
