### ISSUE TITLE
Migrate building and testing from Travis to Github Actions

### ISSUE THREAD

**Issue by willianpaixao** [ethereum/go-ethereum#23821]
# Rationale
### Why should this feature exist?
[Github Actions](https://docs.github.com/en/actions) is now the de facto tool for building, testing and publishing open source projects hosted in Github. It has integrations with the Github's UI and PR review process, giving more clarity and transparency about the builds and tests on every push or pull request.

Additionally, [Travis no longer has free credits in open source projects](https://www.travis-ci.com/pricing/), so this migration would reduce costs.

# Implementation
### Do you have ideas regarding the implementation of this feature?
Yes, it's essentially a translation from the current `.travis.yml` to one or a few smaller files in the `.github/workflow` directory, following Github's reference manuals. This [guide](https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-travis-ci-to-github-actions) is very helpful.

### Are you willing to implement this feature?
Yes, 100%. I just need to know if the feature is desired and the PR wold be accepted be the team.

**Comment by kaliubuntu0206** [comment]
@holiman So the in-house CI is now live?
