### ISSUE TITLE
Too many chain reorgs happenning too frequently in a proof of authority (clique) based private blockchain.

### ISSUE THREAD

**Issue by yoTex0** [ethereum/go-ethereum#23831]
I'm studying on Proof of Authority (Clique) based blockchains. I've setup private networks with 1 validator nodes few times, things really go well in 1 validator but when I add 2 / 3 validators in the network via clique.propose, lots of reorgs starts to happen. Sometime, reorg happens even 2-3 times every minute. Currently, I have a 3 validator based network with a block time of 5 seconds (tried longer block time such as 10sec and reorg still happens) and my geth version is 1.10.11.

It would be a great help for me if anyone can point me what can be the reason behind this reorgs and how to prevent it.

**Comment by holiman** [comment]
I think this is to be expected on a clique network.

**Comment by G33kNoob** [comment]
> I think this is to be expected on a clique network.

so this is not the bug? but the feature? 🤔
