### ISSUE TITLE
Rinkeby faucet down

### ISSUE THREAD

**Issue by jaybuidl** [ethereum/go-ethereum#23842]
https://faucet.rinkeby.io/

![image](https://user-images.githubusercontent.com/22213980/139695517-6dbd323b-d526-4e6f-95b6-61c3114036b1.png)

**Comment by jaybuidl** [comment]
It looks similar to #23572

**Comment by karalabe** [comment]
We're aware.

**Comment by guotie** [comment]
It's always down .......

unbelievable
