### ISSUE TITLE
In Kovan can't get the sender account in transaction messaage

### ISSUE THREAD

**Issue by pengsong96** [ethereum/go-ethereum#23854]
I want to use this code to get the sender account ,but I can't get the right message
msg, err := transaction.AsMessage(types.NewEIP155Signer(chainID), nil)
It maybe about Txn Type:2 (EIP-1559),but don't know hot to get the seander account

**Comment by pengsong96** [comment]
I don't use types.NewEIP155Signer(chainID)! The types.NewLondonSigner(chainID) is rigrht

**Comment by MariusVanDerWijden** [comment]
Yes, you need at least a `types.LondonSigner` to recover 1559 transactions
