### ISSUE TITLE
eth_getLogs request returns an error `failed to get logs for block`.

### ISSUE THREAD

**Issue by brg8** [ethereum/go-ethereum#23875]
#### System information

Geth version: `v1.10.11`
OS & Version: Linux
Commit hash : N/A

#### Expected behaviour

I expect the following request to return a non-error result.

```
curl localhost:8545 -X POST -H "Content-Type: application/json" -d '{"id": "someid","method": "eth_getLogs","jsonrpc": "2.0","params": [ { "fromBlock": "0xb45a", "toBlock": "0xb45a" } ]}'
```

#### Actual behaviour

It returns an error.

```
{"jsonrpc":"2.0","id":"someid","error":{"code":-32000,"message":"failed to get logs for block"}}
```

#### Steps to reproduce the behaviour

Run the provided curl against a geth node. Some bullets that might help:
- I have reproduced this on 10 separate archive nodes.
- Full nodes are hit or miss, some of them respond correctly.
- Parity/OE and Erigon nodes respond correctly.
- When I get the error, this appears in the geth logs:
```
ERROR[11-08|20:15:32.914] Invalid receipt array RLP                hash=4e3a37..5a1bdd err="rlp: expected input list for []*types.LogForStorage, decoding into ([]*rawdb.receiptLogs)[0](rawdb.storedReceiptRLP).Logs"
```
- If I add an address to the filters then I get a valid response:
```
curl localhost:8545 -X POST -H "Content-Type: application/json" -d '{"id": "someid","method": "eth_getLogs","jsonrpc": "2.0","params": [ { "fromBlock": "0xb45a", "toBlock": "0xb45a", "address": "0x1ad1C9CE861a072f843Eab9c070A52e295ad94B5" } ]}'
```
```
{"jsonrpc":"2.0","id":"someid","result":[]}
```

Thank you in advance for your help!

**Comment by noam-alchemy** [comment]
just tested on 1.10.12 as well and the issue is reproducible there as well.

**Comment by s1na** [comment]
Thanks for reporting the issue and the details. If I'm not mistaken this is caused by #23147 and affects really long-running nodes (2-3 years with no db reset) and specifically when querying logs of older blocks. The cause is that when implementing the optimization in #23147 I hadn't considered nodes that might have a legacy format for receipts in their freezer database. I'm working on a fix now.

**Comment by s1na** [comment]
Can you please try this branch and see if that solve the issue? https://github.com/s1na/go-ethereum/tree/fix/getlogs-legacy

**Comment by brg8** [comment]
@s1na Yes! That fixes it :)

**Comment by miohtama** [comment]
I just encountered this issue with `ethereum/client-go:v1.10.19`. 

I received one of the:

```
{'code': -32000, 'message': 'failed to get logs for block #14682553 (0x6d0a1e..590911)
```

Though could not repeat this yet. I wonder if there are other reasons why this get logs could fail.

**Comment by miohtama** [comment]
Upgraded to `ethereum/client-go:v1.10.21`, still getting the same error.

**Comment by mick-prysm** [comment]
A Prysm user is encountering this error here: https://discord.com/channels/476244492043812875/667761857209040916/1019616603542921236

Will update this with Geth version if/when provided.

**Comment by shibug** [comment]
> A Prysm user is encountering this error here: https://discord.com/channels/476244492043812875/667761857209040916/1019616603542921236
> 
> Will update this with Geth version if/when provided.

I am the one who is facing this issue.  My database was fast synced in the past 2 weeks using Geth 1.10.23.  So, no old parts here

**Comment by shibug** [comment]
I went through the [prysm checklist](https://docs.prylabs.network/docs/monitoring/checking-status) only #9 fails.  Here is the output:
`curl http://localhost:3500/eth/v1alpha1/node/eth1/connections
{"currentAddress":"http://localhost:8551","currentConnectionError":"failed to get logs for block #15510142 (0x367e14..8e5b43)","addresses":["http://localhost:8551"],"connectionErrors":[]}%
`

**Comment by TheCookieLab** [comment]
I'm another Prysm user seeing this error message on repeat:

![Failed to get Logs](https://user-images.githubusercontent.com/6332181/190699399-89d1e693-4e90-4d19-b714-6167e0d49630.PNG)

Geth (1.10.25+build28116+focal) is fully synced / not optimistic.

**Comment by shibug** [comment]
Someone should open this issue

**Comment by TheCookieLab** [comment]
This kept causing my Geth to eventually unsync. I deleted my chaindata and synced from scratch which resolved things permanently. If you are still experiencing this I would suggest you do the same.

**Comment by lymweb** [comment]
Yep, just like mine but on a different block

**Comment by holiman** [comment]
If this issue persists, please open a new ticket, and provide logs from your systems + version information.
