### ISSUE TITLE
pending debug_traceCall get error: required historical state unavailable (reexec=128)

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#23878]
## environment

geth version: 1.10.11-stable
Git Commit: 7231b3efb8095d3dd18d7164c3fa84d7705759d3

geth is synced to the latest block
```
/usr/local/bin/geth --syncmode=fast --datadir /data/eth/mainnet --http --http.api web3,eth,txpool,ethash,net,debug --http.corsdomain * --http.addr 0.0.0.0 --http.port 54102 --port 54103 --ws --ws.addr 0.0.0.0 --ws.origins * --ws.port 54104 --ws.api eth,net,web3,txpool,debug
```

## issue

firstly I subsrcibe newTx by 

```
client.RpcClient.EthSubscribe(context.Background(), ch, "newPendingTransactions")
```

then, for each newTx I use `debug_traceCall` with `pending` option to trace the tx execution.

but get `historical state unavailable (reexec=128)` error

since I use `pending` option, it's not debugging trace an old tx (which is older than 128 blocks) so I expected I can get the trace result successfully.

## how to reproduce

go.mod
```
require (
github.com/ethereum/go-ethereum v1.10.11
)
```

test code
```go
	logConfig := vm.LogConfig{EnableMemory: true, DisableStack: true, DisableStorage: true, EnableReturnData: false, Debug: false}
	err = client.RpcClient.CallContext(ctx, &result, "debug_traceCall", arg, "pending", &tracers.TraceConfig{LogConfig: &logConfig, Tracer: &tracerOpt})
```

get error
```
historical state unavailable (reexec=128)
```

**Comment by s1na** [comment]
I think what you want is to trace a pending transaction against the `latest` block, not `pending`. I.e. you want to know how the tx would execute as part of a (future) child of the last mined block.

That said I do get the same error when I try `traceCall` against `pending`. But not sure if there are any actual use-cases for that?

**Comment by huahuayu** [comment]
hi @s1na thanks for the reply, if you read the [debug_traceCall](https://geth.ethereum.org/docs/rpc/ns-debug#debug_tracecall) document, search `pending` you will find the example. Same as other blockNumber params, you can specify either blockNumber or `latest` or `pending` for that param. 

I think `pending` is more accurate so I use it. Another reason is I don't have archive node, I think doing it in pending stat doesn't need the historical state, so it's good for me. That's the use case.

What's more, if I use `pending` param in BSC `debug_traceCall` it's all good, no error. Since BSC is forked from ethereum, I think of course it will be work in ethereum, but I got `historical state unavailable (reexec=128)` error, so I am confused.

**Comment by karalabe** [comment]
Looking through the BSC code base, they have the exact same implementation for traceCall as we do, so I don't see how it would work for them.

I'm unsure though that how you're tying to do this is going to give you the result you're looking for. If you do a traceCall of a pending transaction on top of the pending block; that transaction might have already been included, so you tracing a call **on top** would be a double execution. I'd guess you're interested in the trace of the actually included tx in the pending block, not a double-call after the fact.

Also, the pending block is super volatile, are you sure you want to base anything on top of that?

**Comment by karalabe** [comment]
Couldn't you do `debug.traceBlockByNumber("pending")` if you are interested in the trace execution of transactions currently in the pending block? Or are you really wanting to trace **on top** of the pending transactions?

**Comment by huahuayu** [comment]
hi @karalabe I am working on MEV :), so I want to capture opportunities in mempool, I need the trace to be accurate and fast, the more the BETTER, so what's your suggestion, trace on pending tx or on the latest block?

I create a repo for reproduce, hope this helps https://github.com/huahuayu/trace-pending

**Comment by huahuayu** [comment]
Hi @karalabe have you tried it, it's 100% reproducible. Does it mean something broken during the recent update?

**Comment by piersy** [comment]
Hi @karalabe & @huahuayu, looking at the code I don't see how the trace call api could have ever worked for the pending block.

https://github.com/ethereum/go-ethereum/blob/7231b3efb8095d3dd18d7164c3fa84d7705759d3/eth/tracers/api.go#L792-L813

If the block is pending then `api.blockByNumber` will retrieve the snapshot block (pending block) from the miner, the state for that block (the snapshot state) is also held by the miner it hasn't been written to the chain as far as I'm aware. But then `TraceCall` proceeds to try and load the state for the block from the chain in `api.backend.StateAtBlock` and this can never work  because the chain hasn't had the snapshot block inserted yet. So then  the `historical state unavailable` error seems like a likely outcome.

**Comment by MariusVanDerWijden** [comment]
Will close this for now, if you still have issues with tracing on top of the pending block, please open a new issue. Thanks for reporting
