### ISSUE TITLE
Puppeth terminal fails to exit

### ISSUE THREAD

**Issue by dhananjay12** [ethereum/go-ethereum#23871]
I was setting up a private Ethereum node on MacOS for testing purpose, using `puppeth`.
To exit the puppeth interface using control + c, doesn't work for me.  Is there any other way to exit?

#### System information

Geth version: `1.10.11-stable`
OS & Version: macOS v 11.6.1

#### Expected behaviour
The terminal should exit anytime using `control+c`

#### Actual behaviour
Doesn't exit

#### Steps to reproduce the behaviour
Try puppeth on MacOS terminal.

Sample 
```
Specify your chain/network ID if you want an explicit one (default = random)
> 4224
INFO [11-08|16:03:48.583] Configured new genesis block 

What would you like to do? (default = stats)
 1. Show network stats
 2. Manage existing genesis
 3. Track new remote server
 4. Deploy network components
> 2

 1. Modify existing configurations
 2. Export genesis configurations
 3. Remove genesis configuration
> 2

Which folder to save the genesis specs into? (default = current)
  Will create chainskills.json, chainskills-aleth.json, chainskills-harmony.json, chainskills-parity.json
> 
INFO [11-08|16:04:07.878] Saved native genesis chain spec          path=chainskills.json
INFO [11-08|16:04:07.879] Saved genesis chain spec                 client=aleth path=chainskills-aleth.json
INFO [11-08|16:04:07.880] Saved genesis chain spec                 client=parity path=chainskills-parity.json
INFO [11-08|16:04:07.881] Saved genesis chain spec                 client=harmony path=chainskills-harmony.json

What would you like to do? (default = stats)
 1. Show network stats
 2. Manage existing genesis
 3. Track new remote server
 4. Deploy network components
> ^C
> ^C
> ^C
> ^C
```

**Comment by holiman** [comment]
In geth console, as in many other CLIs (e.g. python),  and, I suspect, puppeth, `ctrl-c` only resets the line, and`ctrl-d` exits. Does that work?

**Comment by dhananjay12** [comment]
Yes, `ctrl-d` that worked. Thanks.
I was following blogs (for [example](https://medium.com/hackernoon/hands-on-creating-your-own-local-private-geth-node-beginner-friendly-3d45902cc612)) for local setup and all say to use `ctrl-c`.
