### ISSUE TITLE
Why dev mode does not mine automatically?

### ISSUE THREAD

**Issue by masanaka** [ethereum/go-ethereum#23870]
I use dev mode for a long time, and it worked fine. 
But recently I updated the software, and delete old data folder to recreate whole data environment. I found the dev mode doesn't mine automatically whatever I set dev.period 0 or 1 or anything else. It just commit new mining work, and sealing paused, waiting for transactions, but never mine potential block.
I run geth on windows, does anybody has same problem with me?

**Comment by holiman** [comment]
Works for me, off latest `master`
```
$ geth --dev --dev.period 1  2>&1 | grep mined 
INFO [11-08|14:49:37.985] 🔨 mined potential block                  number=1 hash=0b4bd7..88bc84
INFO [11-08|14:49:38.000] 🔨 mined potential block                  number=2 hash=77527d..4161a5
INFO [11-08|14:49:39.001] 🔨 mined potential block                  number=3 hash=fb1781..d4aa21
INFO [11-08|14:49:40.002] 🔨 mined potential block                  number=4 hash=59cf62..f0b039
INFO [11-08|14:49:41.002] 🔨 mined potential block                  number=5 hash=e6ce08..3e107a
INFO [11-08|14:49:42.001] 🔨 mined potential block                  number=6 hash=bf7d8e..7dd898
```

**Comment by holiman** [comment]
Please provide your exact commandline args + logs about what is happening.

**Comment by masanaka** [comment]
@holiman 
I'm sorry, my description is wrong.
`--dev.period 1` works fine, mined per second.
But `--dev.period 0` does not work.
I submitted two transaction, and there was no "mined potential block". 
I use `geth --datadir test-chain-dir --http --http.port "8545" --http.api personal,eth,net,web3 --dev --dev.period 0`,
I checked the mining status, it returned true.
Is there anything wrong?  

C:\Program Files\Geth>geth --datadir test-chain-dir --http --http.port "8545" --http.api personal,eth,net,web3 --dev --dev.period 0
INFO [11-08|23:22:31.837] Starting Geth in ephemeral dev mode...
INFO [11-08|23:22:31.848] Maximum peer count                       ETH=50 LES=0 total=50
INFO [11-08|23:22:31.852] Set global gas cap                       cap=50,000,000
INFO [11-08|23:22:32.025] Using developer account                  address=0x5fb123af6882A23d28460b6921520B133b9EF9f1
INFO [11-08|23:22:32.027] Allocated cache and file handles         database="C:\\Program Files\\Geth\\test-chain-dir\\geth\\chaindata" cache=512.00MiB handles=8192
INFO [11-08|23:22:32.165] Opened ancient database                  database="C:\\Program Files\\Geth\\test-chain-dir\\geth\\chaindata\\ancient" readonly=false
INFO [11-08|23:22:32.167] Freezer shutting down
INFO [11-08|23:22:32.169] Allocated trie memory caches             clean=154.00MiB dirty=256.00MiB
INFO [11-08|23:22:32.171] Allocated cache and file handles         database="C:\\Program Files\\Geth\\test-chain-dir\\geth\\chaindata" cache=512.00MiB handles=8192
INFO [11-08|23:22:32.258] Opened ancient database                  database="C:\\Program Files\\Geth\\test-chain-dir\\geth\\chaindata\\ancient" readonly=false
INFO [11-08|23:22:32.260] Writing custom genesis block
INFO [11-08|23:22:32.263] Persisted trie from memory database      nodes=13 size=1.90KiB time=1.4872ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [11-08|23:22:32.266] Initialised chain configuration          config="{ChainID: 1337 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Berlin: 0, London: 0, Engine: clique}"
INFO [11-08|23:22:32.272] Initialising Ethereum protocol           network=1337 dbversion=<nil>
INFO [11-08|23:22:32.274] Loaded most recent local header          number=0 hash=782366..197cd5 td=1 age=52y7mo1w
INFO [11-08|23:22:32.276] Loaded most recent local full block      number=0 hash=782366..197cd5 td=1 age=52y7mo1w
INFO [11-08|23:22:32.277] Loaded most recent local fast block      number=0 hash=782366..197cd5 td=1 age=52y7mo1w
WARN [11-08|23:22:32.279] Failed to load snapshot, regenerating    err="missing or corrupted snapshot"
INFO [11-08|23:22:32.280] Rebuilding state snapshot
INFO [11-08|23:22:32.282] Resuming state snapshot generation       root=88d87e..6f7c90 accounts=0 slots=0 storage=0.00B elapsed=0s
INFO [11-08|23:22:32.283] Regenerated local transaction journal    transactions=0 accounts=0
INFO [11-08|23:22:32.285] Generated state snapshot                 accounts=10 slots=0 storage=412.00B elapsed=2.982ms
INFO [11-08|23:22:32.287] Stored checkpoint snapshot to disk       number=0 hash=782366..197cd5
INFO [11-08|23:22:32.290] Gasprice oracle is ignoring threshold set threshold=2
WARN [11-08|23:22:32.291] Error reading unclean shutdown markers   error="leveldb: not found"
INFO [11-08|23:22:32.292] Starting peer-to-peer node               instance=Geth/v1.10.11-stable-7231b3ef/windows-amd64/go1.17.2
WARN [11-08|23:22:32.294] P2P server will be useless, neither dialing nor listening
INFO [11-08|23:22:32.334] IPC endpoint opened                      url=\\.\pipe\geth.ipc
INFO [11-08|23:22:32.335] New local node record                    seq=1,636,384,952,334 id=9a4dde7f81250c50 ip=127.0.0.1 udp=0 tcp=0
INFO [11-08|23:22:32.340] HTTP server started                      endpoint=127.0.0.1:8545 prefix= cors= vhosts=localhost
INFO [11-08|23:22:32.344] Started P2P networking                   self=enode://b2256f2152d25d39b7c291c624bce97e5a9ece39543162af220cb6814cb3dd3c532915a28d82d823329f2e67fbd48d5272593b86cb120b6ba0be47964a95a132@127.0.0.1:0
INFO [11-08|23:22:32.346] Transaction pool price threshold updated price=1,000,000,000
INFO [11-08|23:22:32.350] Transaction pool price threshold updated price=1
INFO [11-08|23:22:32.351] Etherbase automatically configured       address=0x5fb123af6882A23d28460b6921520B133b9EF9f1
INFO [11-08|23:22:32.354] Sealing paused, waiting for transactions
INFO [11-08|23:22:32.353] Commit new mining work                   number=1 sealhash=ed7e99..f82b42 uncles=0 txs=0 gas=0 fees=0 elapsed=0s
INFO [11-08|23:23:07.419] Setting new local account                address=0x5fb123af6882A23d28460b6921520B133b9EF9f1
INFO [11-08|23:23:07.420] Submitted transaction                    hash=0xdd5aef0d232559569beb5263323e7dee960cbdf48a1326fa562efb20ce92a9e6 from=0x5fb123af6882A23d28460b6921520B133b9EF9f1 nonce=0 recipient=0x96dD0E7491191D141cf9DD34c6445FEe9218ad46 value=1,000,000,000,000,000,000,000
INFO [11-08|23:23:07.421] Commit new mining work                   number=1 sealhash=e6b2ab..783a0a uncles=0 txs=0 gas=0 fees=0 elapsed=0s
INFO [11-08|23:23:07.421] Sealing paused, waiting for transactions
INFO [11-08|23:23:19.520] Submitted transaction                    hash=0xca9e0b0112b493aeeca37cd7f7a0237d7edc73b492c743c5d6486aba8dc6a631 from=0x5fb123af6882A23d28460b6921520B133b9EF9f1 nonce=1 recipient=0x96dD0E7491191D141cf9DD34c6445FEe9218ad46 value=1,000,000,000,000,000,000,000
INFO [11-08|23:23:19.520] Commit new mining work                   number=1 sealhash=79ee86..0c2d51 uncles=0 txs=0 gas=0 fees=0 elapsed=0s
INFO [11-08|23:23:19.520] Sealing paused, waiting for transactions

**Comment by holiman** [comment]
Works for me:

```
$ geth --datadir /tmp/test-chain-dir --dev --dev.period 0 console
INFO [11-08|20:30:00.559] Starting Geth in ephemeral dev mode... 
INFO [11-08|20:30:00.560] Maximum peer count                       ETH=50 LES=0 total=50
INFO [11-08|20:30:00.560] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [11-08|20:30:00.561] Set global gas cap                       cap=50,000,000
INFO [11-08|20:30:00.731] Using developer account                  address=0x674e31173328A990f5fe25B631eF00dA0EDD8e84
INFO [11-08|20:30:00.731] Allocated cache and file handles         database=/tmp/test-chain-dir/geth/chaindata cache=512.00MiB handles=262,144
INFO [11-08|20:30:00.734] Opened ancient database                  database=/tmp/test-chain-dir/geth/chaindata/ancient readonly=false
INFO [11-08|20:30:00.734] Freezer shutting down 
INFO [11-08|20:30:00.735] Allocated trie memory caches             clean=154.00MiB dirty=256.00MiB
INFO [11-08|20:30:00.735] Allocated cache and file handles         database=/tmp/test-chain-dir/geth/chaindata cache=512.00MiB handles=262,144
INFO [11-08|20:30:00.754] Opened ancient database                  database=/tmp/test-chain-dir/geth/chaindata/ancient readonly=false
INFO [11-08|20:30:00.754] Writing custom genesis block 
INFO [11-08|20:30:00.754] Persisted trie from memory database      nodes=12 size=1.82KiB time="85.122µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [11-08|20:30:00.755] Initialised chain configuration          config="{ChainID: 1337 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Berlin: 0, London: 0, Arrow Glacier: <nil>, Engine: clique}"
INFO [11-08|20:30:00.755] Initialising Ethereum protocol           network=1337 dbversion=<nil>
INFO [11-08|20:30:00.755] Loaded most recent local header          number=0 hash=424a7b..52ebba td=1 age=52y7mo1w
INFO [11-08|20:30:00.755] Loaded most recent local full block      number=0 hash=424a7b..52ebba td=1 age=52y7mo1w
INFO [11-08|20:30:00.755] Loaded most recent local fast block      number=0 hash=424a7b..52ebba td=1 age=52y7mo1w
WARN [11-08|20:30:00.755] Failed to load snapshot, regenerating    err="missing or corrupted snapshot"
INFO [11-08|20:30:00.755] Rebuilding state snapshot 
INFO [11-08|20:30:00.756] Resuming state snapshot generation       root=95a337..214a44 accounts=0 slots=0 storage=0.00B elapsed="219.63µs"
INFO [11-08|20:30:00.756] Regenerated local transaction journal    transactions=0 accounts=0
INFO [11-08|20:30:00.756] Generated state snapshot                 accounts=10 slots=0 storage=412.00B elapsed="751.711µs"
INFO [11-08|20:30:00.756] Gasprice oracle is ignoring threshold set threshold=2
WARN [11-08|20:30:00.756] Error reading unclean shutdown markers   error="leveldb: not found"
INFO [11-08|20:30:00.756] Starting peer-to-peer node               instance=Geth/v1.10.13-unstable-045dfd15-20211108/linux-amd64/go1.17
WARN [11-08|20:30:00.756] P2P server will be useless, neither dialing nor listening 
INFO [11-08|20:30:00.757] Stored checkpoint snapshot to disk       number=0 hash=424a7b..52ebba
INFO [11-08|20:30:00.758] IPC endpoint opened                      url=/tmp/test-chain-dir/geth.ipc
INFO [11-08|20:30:00.758] Transaction pool price threshold updated price=1,000,000,000
INFO [11-08|20:30:00.758] Transaction pool price threshold updated price=1
INFO [11-08|20:30:00.758] Etherbase automatically configured       address=0x674e31173328A990f5fe25B631eF00dA0EDD8e84
INFO [11-08|20:30:00.759] New local node record                    seq=1,636,399,800,758 id=d2961aeea3e05a58 ip=127.0.0.1 udp=0 tcp=0
INFO [11-08|20:30:00.759] Started P2P networking                   self=enode://61ecd5af78d958b1c007dffe231708c1770cd44d6f546b554ba7d85488b0bda10b75837a98881b7c4168be76a8948a834e7cc0eb2e8a06dd38da86d96bb48ba6@127.0.0.1:0
INFO [11-08|20:30:00.759] Commit new mining work                   number=1 sealhash=a08c10..11e456 uncles=0 txs=0 gas=0 fees=0 elapsed="91.871µs"
WARN [11-08|20:30:00.759] Block sealing failed                     err="sealing paused while waiting for transactions"
Welcome to the Geth JavaScript console!

instance: Geth/v1.10.13-unstable-045dfd15-20211108/linux-amd64/go1.17
coinbase: 0x674e31173328a990f5fe25b631ef00da0edd8e84
at block: 0 (Thu Jan 01 1970 01:00:00 GMT+0100 (CET))
 datadir: /tmp/test-chain-dir
 modules: admin:1.0 clique:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

To exit, press ctrl-d or type exit
> eth.sendTransaction({from: eth.accounts[0], to:eth.accounts[0], value: 5})
INFO [11-08|20:30:24.466] Setting new local account                address=0x674e31173328A990f5fe25B631eF00dA0EDD8e84
INFO [11-08|20:30:24.466] Submitted transaction                    hash=0x8ed0b39ed064081968c34fe3bc39b051bfbe4812e6bc3beb704048d8c7bf1036 from=0x674e31173328A990f5fe25B631eF00dA0EDD8e84 nonce=0 recipient=0x674e31173328A990f5fe25B631eF00dA0EDD8e84 value=5
"0x8ed0b39ed064081968c34fe3bc39b051bfbe4812e6bc3beb704048d8c7bf1036"
> INFO [11-08|20:30:24.467] Commit new mining work                   number=1 sealhash=85e47b..964056 uncles=0 txs=1 gas=21000 fees=2.1e-14 elapsed="749.603µs"
INFO [11-08|20:30:24.468] Successfully sealed new block            number=1 sealhash=85e47b..964056 hash=b9fa6c..9d2b66 elapsed=1.363ms
INFO [11-08|20:30:24.468] 🔨 mined potential block                  number=1 hash=b9fa6c..9d2b66
INFO [11-08|20:30:24.469] Commit new mining work                   number=2 sealhash=0f864c..b7fd45 uncles=0 txs=0 gas=0     fees=0       elapsed="657.766µs"
WARN [11-08|20:30:24.469] Block sealing failed                     err="sealing paused while waiting for transactions"
```
Importantly, is that my node says `Commit new mining work                   number=1 sealhash=85e47b..964056 uncles=0 txs=1` (obs: `txs=1`), whereas your node says `Commit new mining work                   number=1 sealhash=e6b2ab..783a0a uncles=0 txs=0`. So for some reason, the tx you just submitted does not make it into the block. Which causes it to not mine. 

So, could you try the `--console` and then do what I did: `eth.sendTransaction({from: eth.accounts[0], to:eth.accounts[0], value: 5})` ?

**Comment by holiman** [comment]
Actually, I was able to repro it 
```
> eth.sendTransaction({ from:eth.accounts[0], to: eth.accounts[0] , value: 5, gasPrice: 0}) 
INFO [11-08|20:39:29.761] Setting new local account                address=0xB06E452cee834E295dd908aDd559cEd4Aa8C2955
INFO [11-08|20:39:29.762] Submitted transaction                    hash=0x50db9718cdf923fdbaac3aecf5afa4c038eeec66dfe47a2968afa7d0c9605306 from=0xB06E452cee834E295dd908aDd559cEd4Aa8C2955 nonce=0 recipient=0xB06E452cee834E295dd908aDd559cEd4Aa8C2955 value=5
INFO [11-08|20:39:29.762] Commit new mining work                   number=1 sealhash=b385b8..2c4f85 uncles=0 txs=0 gas=0 fees=0 elapsed="116.118µs"
WARN [11-08|20:39:29.762] Block sealing failed                     err="sealing paused while waiting for transactions"
"0x50db9718cdf923fdbaac3aecf5afa4c038eeec66dfe47a2968afa7d0c9605306"
```
.... by sending a 0-gasprice transaction. The  miner won't accept those, but for some reason it does give the miner a kick to start sealing. Do you send them with 0 gasPrice? 

It's a bit odd that it isn't rejected by the pool -- it shouldn't even be noticed by the miner, IMO.

**Comment by masanaka** [comment]
@holiman 
Oh, yes, yes, I always set 0-gasprice when I use dev mode.
I see, if the gas price is too low, I need to replace it with more gas price to let geth include it into block. Excellent feature.
Sorry wasted your time, it's my fault.
Thank you, thank you so much.
