### ISSUE TITLE
I need help to unlock CPU limit for GETH windows

### ISSUE THREAD

**Issue by blackerhot** [ethereum/go-ethereum#23876]
![image](https://user-images.githubusercontent.com/29283963/140875650-ee4b692e-81c8-4eb1-a34d-d034f4e8fd35.png)
My cpu usage is limit of 3% from 100% and It used only cpu 30, 31 (2 threads only), I suspect it cause 100 blocks behide always.
How should I config to unlock cpu limit to make it faster.

**Comment by blackerhot** [comment]
ps. ran geth with powershell by command + config. not sure should I move to other way ?

**Comment by karalabe** [comment]
Synchronization is not CPU bound, it's limited by your network latency. Also, you should be using the default sync (snap sync) not fast sync. The former is significantly faster; though at this point it might as well be worth to wait it out if you're so far along.

Ah, you're on BSC. Well, I've no idea how large that network is. They pushed their gas limits up to insane levels, told them it's gonna blow up eventually.
