### ISSUE TITLE
System down due to increased swap

### ISSUE THREAD

**Issue by mayumimayumi** [ethereum/go-ethereum#23887]
Geth version: `geth version` 1.10.08
Linux :ubuntu 18.04
Network: Mainnet

In geth version 1.10.08, the system sometimes went down due to increased swap.

I was able to recover by rebooting at that time, but it has happened several times.

This has not happened since 1.10.09. Has there been a fix?

**Comment by karalabe** [comment]
Our changelogs are in the release notes. If you feel like it, you can go back and skim through to see if anything impacted it. We're constantly making improvements, and I've no idea of the top of my head what changes went in over the last 2 months.
