### ISSUE TITLE
Simulated chain does not have DELEGATECALL in jump-table because of low block-numbers

### ISSUE THREAD

**Issue by androlo** [ethereum/go-ethereum#2388]
The block-numbers of the simulated chain are not high enough to qualify as homstead blocks, which means DELEGATECALL does not work.

**Comment by androlo** [comment]
Simple and obvious issue so felt data and output logs was not needed. I can say that the point where it breaks is at https://github.com/ethereum/go-ethereum/blob/master/core/vm/vm.go#L172. Modifying the jumptable to always include DELEGATECALL made the issue go away, and the contract ran succesfully.

**Comment by karalabe** [comment]
Good catch. I haven't considered the homestead transitioning in the simulator :D @obscuren has been working on modifying the `core` to allow configuring a few chain characteristics and also already started building a configuration capability to the simulated chain. Merging the fist PR needs a very thorough review but after that's done, we can probably soup up the simulated chain in a matter of hours. Will keep you posted on when this gets a real fix :)

**Comment by obscuren** [comment]
Addressed in linked PR. The `ChainMaker`, which is used by the generator, now uses a homestead block of `0` which means that `DELEGATECALL` can now be used.
