### ISSUE TITLE
 tx.AsMessage   error  `transaction type not supported`   and        Why I can not   get `from`  from   Transaction or    TransactionReceipt   immediate  ?  

### ISSUE THREAD

**Issue by wangruics** [ethereum/go-ethereum#23890]
`
 hash := "0xd05e781f1f864de1422f38962399a692b9b89fc4e107a8f062a1bfec35bc3f10"

	txHash  := common.HexToHash(hash)

	tx,_,_ :=  client.TransactionByHash(context.Background(),txHash)

	asMessage, e := tx.AsMessage(types.NewEIP155Signer(big.NewInt(int64(1))), tx.GasPrice())

	if e == nil {
		 log.Println(asMessage.From().String())
	}

	log.Println(e)

`

ERROR :   transaction type not supported

**Comment by rjl493456442** [comment]
You should use `types.LatestSignerForChainID()` instead of legacy EIP 155 signer.

**Comment by wangruics** [comment]
> You should use `types.LatestSignerForChainID()` instead of legacy EIP 155 signer.

Thanks, It is ok now!

**Comment by rahul-kinesis** [comment]
Does this work now?
