### ISSUE TITLE
cmd/geth: line editing doesn't work in Windows Docker Quickstart Shell

### ISSUE THREAD

**Issue by MidnightLightning** [ethereum/go-ethereum#2389]
#### System information

Geth Version: Docker (latest)
OS & Version: Windows
#### Expected behaviour

Pressing `TAB` in the Geth console does a tab completion
#### Actual behaviour

Pressing `TAB` inserts a tab character into the console input
#### Steps to reproduce the behaviour

Install Docker for Windows, and launch the Docker Quickstart shell. In that shell run:

```
docker run -td -p 8545:8545 -p 30303:30303 -m 4g --name geth ethereum/client-go
docker exec -it geth /usr/bin/geth attach
```

That drops you into the Geth console. Type `admi` and press `TAB`. Should auto-complete to `admin`; instead inserts a tab character.

Also, the up/down arrows do not cycle through command history, left/right arrow keys do not move the cursor around, and the delete key doesn't remove characters from the input (all of these just echo escape sequences to the input prompt).

**Comment by Trafalmadorian76** [comment]
I'm having the same issue in Cygwin.

**Comment by MidnightLightning** [comment]
This issue still remains; any chance of getting it looked at?

**Comment by FrankSzendzielarz** [comment]
Docker for Windows shell tab complete + command completion is working (2019).
