### ISSUE TITLE
block timestamp check

### ISSUE THREAD

**Issue by hahahahaiamdax** [ethereum/go-ethereum#23909]
the white paper in https://ethereum.org/zh/whitepaper/ say timestamp check mechanism in ethereum is：
**
The basic block validation algorithm in Ethereum is as follows:

Check if the previous block referenced exists and is valid.
Check that the timestamp of the block is greater than that of the referenced previous block and less than _15 minutes_ into the future
**
however ，code in GitHub （https://github.com/ethereum/go-ethereum/blob/32150f8aa9789e4c9aa91a59085011eb692ac8ad/consensus/ethash/consensus.go) say:
**
allowedFutureBlockTimeSeconds = int64(15)  
if header.Time > uint64(unixNow+allowedFutureBlockTimeSeconds) {
			return consensus.ErrF
**
one say 15 minutes, another say 15 seconds，which is right？Wish for your reply.

**Comment by holiman** [comment]
The actual yellow-paper is here: https://ethereum.github.io/yellowpaper/paper.pdf 
Afaik, there's no definition there about the vailidity of future blocks, or how timestamps should be verified. 
The 15s is the agreed-upon by node-implementors practical limit. If the block exceeeds this, then it will not be rejected per se, but just not imported right now -- it will be re-evaluated later on. 

Why is this? See https://github.com/ethereum/go-ethereum/pull/23761#discussion_r738785512 for some more info

> Currently, we have no strict (consensus) requirement about time. It's just a de-facto implementation choice, that the consensus engine will soft-reject headers too far in the future. Soft, in the sense that they're kept and attempted again later.
>
> One funky attack: if I can set the timestamp to whatever, then I can set it close to maxuint64, or max bigint, or whatever, and effectively halt ethereum, since nobody can mine a block with a timestamp exceeding mine. More effective probably, would be to not do that, but do it so a few thousand blocks can be mined on top of mine => more havoc.
