### ISSUE TITLE
High Memory Usage v1.10.12-stable

### ISSUE THREAD

**Issue by StakeNoob** [ethereum/go-ethereum#23907]
Geth version: 1.10.12-stable

OS & Version: Ubuntu

Experiencing unclean shutdowns from OOM every few hours because Geth keeps requiring more memory.  Following advice from a [prior thread](https://github.com/ethereum/go-ethereum/issues/23195) and have uploaded a memory scan with --pprof;  [here](https://github.com/StakeNoob/mem-scan/blob/main/mem%20scan)

Followed Somer Esat Guide, running Lighthouse.

![grep warn](https://user-images.githubusercontent.com/93400763/141697136-4d46d385-d181-4de7-a7ec-a16e7b042988.png)

**Comment by holiman** [comment]
What are the exact parameters you are  using to run the node? 
What are the hardware specs on the machine you're running it on?

**Comment by holiman** [comment]
Looks like the node has almost `2Gb` of transactions. ISTR we fixed something in the tx pool recently... investigating
```
big.Int                          27775312  1524.560 MB
types.DynamicFeeTx                2300551  1215.605 MB
trie.cachedNode                   1255759   801.626 MB
types.Transaction                 4598258   673.195 MB
types.LegacyTx                    2296672   622.265 MB
fastcache.Cache                         3   434.316 MB
```

**Comment by StakeNoob** [comment]
> What are the exact parameters you are using to run the node?
What info do I need to provide here?

> What are the hardware specs on the machine you're running it on?
16GB Hyper X Impact Ram 3200Mhz, 1Tb Nvme Samsung EVO, Asus PN50 NUC

**Comment by holiman** [comment]
> What info do I need to provide here?

`geth --foo --bar --bazon=500 ... `. You can omit anything personal, like etherbase or mining address or extip if you're using that.

**Comment by StakeNoob** [comment]
I get this;

`Incorrect Usage. flag provided but not defined: -foo`

**Comment by holiman** [comment]
What I mean is, what arguments are you using when you start geth?

**Comment by StakeNoob** [comment]
`ExecStart=geth --http --datadir /var/lib/goethereum --cache 2048 --maxpeers 30 --pprof`

**Comment by holiman** [comment]
It's a bit odd. Are you sure it's geth that's hogging the memory? Do you see the OOMreaper in the syslogs of the machine? If so, what does it say about the memory consumption of geth?
Just speculating -- but in case there are N processes each hogging M Gb of data, the OOMReaper can select any one of those to reap to get more memory.

**Comment by StakeNoob** [comment]
Does this help?

`dmesg -T | egrep -i 'killed process'
[Tue Nov 16 16:27:49 2021] Out of memory: Killed process 41248 (geth) total-vm:15623388kB, anon-rss:12596728kB, file-rss:0kB, shmem-rss:0kB, UID:1002 pgtables:26672kB oom_score_adj:0
[Tue Nov 16 19:27:43 2021] Out of memory: Killed process 42925 (geth) total-vm:16456596kB, anon-rss:12839812kB, file-rss:0kB, shmem-rss:0kB, UID:1002 pgtables:27640kB oom_score_adj:0
`
I follow very prescribed guides as staking was my first introduction to linux.  When I had less than 50gb to prune I got some help removing db manually on the discord - this is the only other variable outside of Somer Esat guide.  Other than that I don't know if a delay in updating might have created an issue?

**Comment by holiman** [comment]
> Does this help?

Yes, it shows (I think) that geth reached around `16G` before it was killed. The memprofile you uploaded shows nowhere nearly that much, but the `dmesg` makes it clear.

**Comment by holiman** [comment]
The scan provided doesn't really show anything out of the ordinary. This may be just because it was taken at a time when not much memory was allocated -- could you please try again, and see if you manage to take a memory dump at a point close to when it is going OOM?

**Comment by StakeNoob** [comment]
![new htop](https://user-images.githubusercontent.com/93400763/142662830-89d8cc26-1a0e-4f45-9b67-4bed996a9dee.png)
I waited until my RAM was nearly maxed when taking the scan,this was my htop just before. Not long after I got OOM.   I can still do another scan if you like, but the discrepancy doesn't seem right.

**Comment by holiman** [comment]
So, in the first screenshot, you have only included level `WARN` and above. Could you provide some more logs, with the lower levels included? 

>  I can still do another scan if you like, but the discrepancy doesn't seem right.

Doesn't sound like it will help, seems like the mem scanner is unable to locate the memory leak.

**Comment by StakeNoob** [comment]
![fail error grep](https://user-images.githubusercontent.com/93400763/143618853-416322de-b4ca-462e-ab4c-d744dcdddd58.png)
Helpful?

**Comment by holiman** [comment]
A bit, yes -- seems you are in the middle of a sync? Please provide the logs as text, without grepping for things.

**Comment by StakeNoob** [comment]
I've been trying a few things not quite sure how to get what you are after.  I tried this;

`curl -X POST localhost:8545 -H "Content-Type: application/json" --data-raw '{"jsonrpc":"2.0","method":"eth_syncing","id":1}'
{"jsonrpc":"2.0","id":1,"result":{"currentBlock":"0xc801c2","highestBlock":"0xd0ebc8","knownStates":"0x2c18346f","pulledStates":"0x2c18346f","startingBlock":"0xc87c0a"}}`

I can't find the log file, if it has left one.

**Comment by holiman** [comment]
I mean just the logs. `sudo journalctl -u geth --since=today`, and maybe pipe it into something you can upload to this ticket.

**Comment by StakeNoob** [comment]
Pasted in a repository [here](https://github.com/StakeNoob/Geth-Journalctl-Today/blob/8b3d3bf7f7629d0fa2b015556fd8a36b82e0fdb4/README.md)

**Comment by nevermoremining** [comment]
Interested in this bug as well, may be seeing the same issue. Geth “10.12 stable” runs for 1-3 days then crashes with OOM error. 

Trying to do a full sync and then operate as a node. Have tried increasing cache values ranging from 5-10GB but every few days it still crashes. (Geth limits to 5GB anyways)

Hardware is dedicated to only running Geth. Xeon 3.4GHz 6C/6T processor, 16GB of RAM, 8 TB SSD (dual 4GB in RAID 0). OS is Ubuntu Server 20.04, no GUI just command line.

**Comment by holiman** [comment]
@StakeNoob thanks, that helped a lot!

```
Nov 27 01:33:22 EthStaker geth[235026]: INFO [11-27|01:33:22.673] Loaded most recent local header          number=13,107,650 hash=5fdac7..2c1bc8 td=29,614,342,018,010,984,500,618 age=3mo15h25m
Nov 27 01:33:22 EthStaker geth[235026]: INFO [11-27|01:33:22.673] Loaded most recent local full block      number=13,107,650 hash=5fdac7..2c1bc8 td=29,614,342,018,010,984,500,618 age=3mo15h25m
Nov 27 01:33:22 EthStaker geth[235026]: INFO [11-27|01:33:22.673] Loaded most recent local fast block      number=13,107,650 hash=5fdac7..2c1bc8 td=29,614,342,018,010,984,500,618 age=3mo15h25m
```
So you have block `13107650`/`0x5fdac7...` as most recent, however, canonical block [13107650](https://etherscan.io/block/13107650) has hash `0x74d36a16e65fe50d90878e83d8be09f09f89482d8f981d6f86e65bf329f004d7`

Then it goes into a mode where it finds the (canonical?) chain, and starts to import that
```
Importing heavy sidechain segment        blocks=908 start=13,070,159 end=13,071,066
```

This means it will have to import `13107650 - 13070159 = 37491` blocks before the 'sidechain' will swap out the one you have. 

That's what it keeps doing until it goes OOM, and restarting again at the same point: 
```
Nov 27 04:13:24 EthStaker geth[236799]: INFO [11-27|04:13:24.175] Loaded most recent local header          number=13,107,650 hash=5fdac7..2c1bc8 td=29,614,342,018,010,984,500,618 age=3mo18h5m
Nov 27 04:13:24 EthStaker geth[236799]: INFO [11-27|04:13:24.175] Loaded most recent local full block      number=13,107,650 hash=5fdac7..2c1bc8 td=29,614,342,018,010,984,500,618 age=3mo18h5m
Nov 27 04:13:24 EthStaker geth[236799]: INFO [11-27|04:13:24.175] Loaded most recent local fast block      number=13,107,650 hash=5fdac7..2c1bc8 td=29,614,342,018,010,984,500,618 age=3mo18h5m
Nov 27 04:13:24 EthStaker geth[236799]: INFO [11-27|04:13:24.176] Loaded last fast-sync pivot marker       number=12,401,481
```

This looks really odd -- because on mainnet, I can't imagine that there exists any sidechain with `37K` valid blocks, so I'm very curious what happened here. 


In order to fix this, a couple of things can be done. Your pivot point is `12401481`, so there should be plenty of points to go back to before `13070159`. So doing a the following in a geth console would most likely solve the problem for you:
```
debug.setHead(13070159)
``` 
In order to do it 'cleanly' might be best to first stop geth, then start geth in non-peering mode (to not trigger a new sync)
```
geth <args> --nodiscover --maxpeers 0 console
...
$> debug.setHead(13070159)
```
That will make geth rewind, and you should be able to sync up properly afterwards. 


However, I'm a bit curious about what you actually have in your blockchain. If you would provide me with this blocks, I would be interested in investigating them. They can be extracted in RLP-form via this command:
```
geth export blocks.rlp 13070159 13107650
```
(and, of course, that needs to be done _before_ you rewind the chain)

**Comment by StakeNoob** [comment]
I don't know if this is what you expected, if there is a need for more tests I can hold off on rewind.

`INFO [11-29|16:59:40.402] Maximum peer count                       ETH=50 LES=0 total=50
INFO [11-29|16:59:40.403] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [11-29|16:59:40.406] Set global gas cap                       cap=50,000,000
INFO [11-29|16:59:40.406] Allocated cache and file handles         database=/home/henry/.ethereum/geth/chaindata cache=512.00MiB handles=524,288
INFO [11-29|16:59:40.500] Opened ancient database                  database=/home/henry/.ethereum/geth/chaindata/ancient readonly=false
INFO [11-29|16:59:40.506] Disk storage enabled for ethash caches   dir=/home/henry/.ethereum/geth/ethash count=3
INFO [11-29|16:59:40.506] Disk storage enabled for ethash DAGs     dir=/home/henry/.ethash               count=2
INFO [11-29|16:59:40.507] Loaded most recent local header          number=0 hash=d4e567..cb8fa3 td=17,179,869,184 age=52y8mo16h
INFO [11-29|16:59:40.507] Loaded most recent local full block      number=0 hash=d4e567..cb8fa3 td=17,179,869,184 age=52y8mo16h
INFO [11-29|16:59:40.507] Loaded most recent local fast block      number=0 hash=d4e567..cb8fa3 td=17,179,869,184 age=52y8mo16h
WARN [11-29|16:59:40.508] Loaded snapshot journal                  diskroot=d7f897..0f0544 diffs=missing
Fatal: Export error: block number 13107650 larger than head block 0`

**Comment by StakeNoob** [comment]
![eth block export](https://user-images.githubusercontent.com/93400763/143911405-5d951cb6-fbbd-4860-bc6c-0a620e46e245.png)

**Comment by holiman** [comment]
Yeah, when I wrote `<args>` I meant that things like datadir. In your case, I think you're using `/var/lib/goethereum/geth/` normally? If so: 

```
geth --datadir /var/lib/goethereum/geth/ export blocks.rlp 13070159 13107650
````

**Comment by StakeNoob** [comment]
![gethsethead](https://user-images.githubusercontent.com/93400763/144092719-28277f89-b216-45f0-85e8-83cb5fabcf15.png)
Done sudo systemctl stop geth, then ran into trouble with the debug command.

I exported the blocks, >3.3Gb. What is preferred recourse for you when too large for Github?

**Comment by holiman** [comment]
> I exported the blocks, >3.3Gb. What is preferred recourse for you when too large for Github?

Hm, I guess we don't actually need _all_ of that, perhaps it would be sufficient to peek at a few megabytes or so, and see what those blocks are. Perhaps you can upload a couple of megabytes from the beginning of it to github? 

Something like `cut -b 1-3000000 blocks.rlp > blocks.3mb.rlp`

**Comment by holiman** [comment]
Oh, and thanks for helping out with this, I appreciate it!

**Comment by holiman** [comment]
> then ran into trouble with the debug command.

Yes, my bad. It doesn't take integers, but hex strings. So `debug.setHead("0xc76f4f")` should work better

**Comment by StakeNoob** [comment]
So I entered 

`cut -b 1-3000000 blocks.rlp > blocks.3mb.rlp` like you said, but the file is 3.1GB!  So we need something much smaller, I tried knocking 2 zeros off, hope I haven't screwed up because the file size has not changed.  The number relates to a starting point rather than number of blocks being cut?

Man no problem, but it seems too early to assume that I'm actually helpful yet - lol!  Thanks for being patient with me.

**Comment by holiman** [comment]
Sorry, my bad again. Use this instead
```
head -c 3000000 blocks.rlp > blocks.3mb.rlp 
```

**Comment by StakeNoob** [comment]
Brilliant, thank you! [blocks3mb](https://github.com/StakeNoob/blocks3mb/blob/55e2f70dc53a2241d517392b6f16f837ec71734f/blocks.3mb.rlp)

So Geth rewound in like a minute, faster than I thought;

![geth rewind](https://user-images.githubusercontent.com/93400763/144494157-a18a5615-61de-4c0d-85bb-146d22176436.png)

Granted all is well I should sync properly if go back into peering mode.  Should I just journalctl start geth, edit system md file back to 30 peers if needed?

**Comment by StakeNoob** [comment]
Done sudo systemctl start geth, then sudo journalctl -fu geth.service shows this
![geth fail](https://user-images.githubusercontent.com/93400763/145104665-aa61f62c-7d72-4bb2-b248-a760b9e78354.png)
;

Unless I am missing something easy and you are happy enough with the blocks3mb then I think I might be tempted to remove db.

**Comment by StakeNoob** [comment]
I noticed someone recently had an issue with their pruned state getting a different directory from the guided install they used from Somer Esat.  I followed up on my set up which used same guide and noticed tmy chaindata has a different directory too.  Could this have a part in the OOM?  Somer Esat directory should be; 

`/var/lib/goethereum/geth/chaindata`

On the attached picture I have highlighted a different directory being used, which I assume would have been due to something similar happening when pruning;

![geth chain data](https://user-images.githubusercontent.com/93400763/145108860-43b7a6e7-aea9-40ad-a4fa-bdcc7b18d308.png)

**Comment by holiman** [comment]
Sorry, this slipped my mind. So the block export you did, it contained this: 
```
Block 13070159: 45f33e25f2c5e31eb9d3490ff78755c9d84d47ed5834d89ee0267a977385140b
Block 13070160: 4a0cbde19834f63464916805267f01db119eb5bd2f4101fd89858ca5c2691fe0
Block 13070161: f7fab075132239bfb225a96470e075821a7dae3c794a0840b6947287c077bafd
Block 13070162: 4200d205b0babeaa672a45dcaaa1a6232d77c3e84ef0f55d1c9ff3acaafc3b69
Block 13070163: d832f997d26938d43c640310f22e6aedae787ceee4402e0b76eb668cd075e64a
Block 13070164: 8dc50b1bfd1d09ba8fc793b49788b016d0adb69bea3c73edc6b7cd3ca0214618
Block 13070165: 571d427c713c82dd21d44769f696629ba0c34cdd65ae2e83c86be6b62509621b
Block 13070166: 0cf1b504cce1eac6a3ea9fee849c64be9e8e444b86288cc45d2babcb7c1ebada
Block 13070167: 1876a7538e4d87fbb6163a4e46ae78c6ab935fa44f818b829c4fe8e3b26426f5
Block 13070168: 91230f61f16ae2ddab75630674fa1e90c9ebd79baa168ad7538d0df7fd9bbfd9
Block 13070169: 3ec593ce3d3cb2d7142e6044135a1d8ba5cee467848702b1baca9a93ce476df2
Block 13070170: 9f03d75436b63c1a0f44820d30d81c7cf03fb42d6e02bd64f08a1d7884fea103
Block 13070171: 1779dffbf3d0b8a24765eb54a596c46f6f07b96745e50057d396fe12c32c7c07
Block 13070172: 8fd95e7042cd3f8ed0b4a70a73ebf75ac52c1549b537abe580ddc83816219733
Block 13070173: 737f1a9583dc8015d57fe36019c0ee23d912c4479aa6f13ce04e03cf1ef364bd
Block 13070174: 3bfa94467fee2cef447c5e16fee49acb1dde825726022884514fcceb6fa89c9b
Block 13070175: c646dac27cf2d3d346e10a6ce7825eb99347be6656255747367e20fa02dfbd10
Block 13070176: c3d2e332506e3cb7503d12ba3c2c52107b7456bb5a29ae3eb5e2f8a7e149bef3
Block 13070177: 6a2552289358748122488029a0c6bd5f0eb1af4cb2908479692ee824deacadcc
Block 13070178: c9cf639d5b90fa5f9f092135600b917f925349fcfb8ab6e1868bd21018a5c5f7
Block 13070179: 9a8a09933b9dc9648cdc25a7fd648ed4d167fabcc2282b47a7ad7bafb1ffab82
Block 13070180: 232a184846d65d88b29f57aecd764d494961155fca2da61441187b2539e99752
Block 13070181: 5fa9c0ff95008277417df6d1aa41ad10ff576eb3ff511a719bc66c192213c78b
Block 13070182: 9ac279c4f7e9e42a1e28b9a31962ca750efb3f5dbc8ffd09181d183c6d994f13
Block 13070183: 551c13a2a2379d960d464b8c2f89e7c967cdb1b05bb701a124e8dac03fd5f0b1
Block 13070184: b74bf50bfed5898be5d81656dace6e48e09035f211d2275fd5823bd0860157cf
Block 13070185: fd42de419af5f8ab7325a3fa9ac486c947ac1243d0b6ed6d193b5bb15ee6ac59
Block 13070186: aed6d7efaeab52cafae0ef08f12d8b763ccc3a29032bc6b7309f14a10908e79d
Block 13070187: 881c4ad0b75ecf9c4bced1d80ac024b84b96f23f89d9dd382461b2ea5aef9f94
Block 13070188: 6ade040b39fe7fcdc75206cf96a072aab7a9aef9c2de3d86fcfb4d061a300df2
Block 13070189: 742c194217915ac1664a5520192b3e6a9801616343c0875039b4ad07771661cf
Block 13070190: a766cc415ff32a9fb726a78c93d8734e448aec10644eaf6c164920063d94d6a3
Block 13070191: ab28382efca610cd87a42bfce54be03f0c3c808f443413d0e90e04bf13538bfe
Block 13070192: a85fda64e95ef46ce68582d55eb7e8bcb4d3891bede705ccfe2397c144a80ba7
Block 13070193: e453fd3e57b54e9b32e5fc4cf1d4141c425623f6170240648ff8c4f731d21da5
Block 13070194: ea2cd7b34cbe4c15806f5bf5c8043743d391e359911870e7c0aea5b7f11c7f5e
Block 13070195: 613bb2dae86cbc1c3247d60620117d04c189655000c428e40e3a693193628e8e
Block 13070196: 87fd8ee3656d3f5a9277d88fb0241ee24f3cce04e05d7981542051ab4ae696b8
```
Which seems to match the canon blocks (e.g. https://etherscan.io/block/13070159 and https://etherscan.io/block/13070160)

So it's indeed in a state where it already has the blocks, but nevertheless wants to re-import them as a sidechain. 
I don't think there's much more we can do.  

I don't know anything about any Somer Ersat guide, the default location for geth data is `~/.ethereum/...` . If you want to place it somewhere else, you need to use the `--datadir` switch. Also, did you do pruning? 

We normally don't recommend using journalctl to run geth, but if you do, you somehow need to configure it to give geth sufficient time to shut down (a couple of minutes).

**Comment by StakeNoob** [comment]
A good while ago when people's 1Tb first started to get full I had to do a manual removal of DB as I had less than <50Gb free storage. I got help from a mod on the EthStaker Discord.

I am not bothered about directories being different if it doesn't impact performance, just a point was made that it could create problems so I am just considering it as a possibility.

`So it's indeed in a state where it already has the blocks, but nevertheless wants to re-import them as a sidechain.
I don't think there's much more we can do.`

Interesting.  Since you say there is nothing we can do is there any advice you can offer here before this presumably gets closed?  Or anything I can understand about how/why Geth is behaving like this?  Thank you for help thus far.

**Comment by StakeNoob** [comment]
I get told that head does not match snapshot.


![head does not match snapshot](https://user-images.githubusercontent.com/93400763/145681309-d1331589-4e0d-4885-a6f4-6cd009eb937d.png)

**Comment by StakeNoob** [comment]
I removed geth db with flag set to /var/lib/goethereum/geth/chaindata.  It has rebuilt and synced correctly and no issues with OOM so far.  Going to close now, thanks!
