### ISSUE TITLE
Rinkeby faucet down again and again and again

### ISSUE THREAD

**Issue by guotie** [ethereum/go-ethereum#23903]
anybody can make it stable????

**Comment by hello0827** [comment]
Get nothing even I followed the instruction on faucet, and now I need to wait 3 days to test my contract...

**Comment by guotie** [comment]
https://twitter.com/zhusu/status/1462216210116853762

so, is he say the truth?

**Comment by oberstet** [comment]
not sure if this is the right repo to file this issue, but yeah, still broken - https://faucet.rinkeby.io/ as of now:

![Bildschirmfoto von 2021-12-06 12-36-27](https://user-images.githubusercontent.com/233340/144839423-df15ab3a-4ace-4e3f-9caa-234c67d5915c.png)

**Comment by oberstet** [comment]
https://faucets.chain.link/rinkeby does work .. gives 0.1 ETH and 10 LINK without any social media or email account

**Comment by marksatorrre** [comment]
It is down again. how can i get some rinkebey for my testing. Thanks

**Comment by hello0827** [comment]
> It is down again. how can i get some rinkebey for my testing. Thanks

https://faucets.chain.link/rinkeby

**Comment by jyturley** [comment]
I am getting the same issue described in #23742
`insufficient funds for gas * price +value`

**Comment by MariusVanDerWijden** [comment]
Really sorry about the rinkeby faucet being so unstable. Fortunately now rinkeby is deprecated so we decided to shut down the faucet. Will close, and sorry again!
