### ISSUE TITLE
Reduce log levels for certain messages

### ISSUE THREAD

**Issue by pyggie** [ethereum/go-ethereum#23908]
#### System information

Geth version: Version: 1.10.12-stable
OS & Version: Linux

#### Expected behaviour

An ERROR message in the logs should reveal a serious problem that the user should review.

#### Actual behaviour

Some ERROR messages are informational at best and are distracting to a user trying to monitor serious problems. Especially this common one:
```
ERROR[11-14|22:56:33.439] Snapshot extension registration failed   peer=xxxx err="peer connected on snap without compatible eth support"
```
A similar common example for WARN:
```
WARN [11-14|23:01:29.317] Checkpoint challenge timed out, dropping id=xxxx conn=inbound addr=...
```

**Comment by MariusVanDerWijden** [comment]
I agree that the log levels for certain log messages are not great right now.
We should put both snap without eth and checkpoint challenge to info since they come up rather often because of people forking geth for other chains

**Comment by karalabe** [comment]
Yes and no. They do signal that there's significant peer churn, which ENRs and the discovery protocol should have filtered out.
