### ISSUE TITLE
etherbase be changed to 0x1cffe... all the time

### ISSUE THREAD

**Issue by Atrovzhi** [ethereum/go-ethereum#23904]
#### System information

Geth version: `geth version` 1.10.12
OS & Version: Linux Ubuntu 18.04

#### Expected behaviour
      Once I start the eth node, and set the miner with "--miner --miner.etherbase 'MyAccount' ",the miner of node should always be MyAccount.

#### Actual behaviour
      The miner address was MyAccount initially, however, after about 2 minutes, the mineraddress was changed to "0x1cffe205e97976bb9d1ec006f5222360a89353e0". No matter how I reset the miner address to MyAccount, the miner address was always changed to 0x1cffe...
      It happens not only in public chain, but also in private chain. I used the version from 1.10.6 to 1.10.12, every version has the same problem.

#### Steps to reproduce the behaviour
      I used the start command 
`nohup   geth --syncmode "full" --port "30303" --cache=10240 --datadir MyDataDir --http --http.addr 0.0.0.0 --http.port 8545 --http.api debug,eth,net,web3,personal,admin,miner,txpool --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api eth,net,web3,personal,admin,miner,txpool --mine --miner.etherbase 'MyAddressHere' --allow-insecure-unlock --maxpeers 10  --maxpendpeers 10 >> MyDataDir/geth.log 2>&1 &`
      Also, geth command 
`miner.setEtherbase(eth.accounts[0])`
      The commands can work only about 2 minutes, and then the miner address was changed to 0x1cffe...

> > eth.coinbase
> "0x1cffe205e97976bb9d1ec006f5222360a89353e0"
> > miner.setEtherbase(eth.accounts[0])
> true
> > eth.coinbase
> "0xc3414..."
> > eth.coinbase
> "0x1cffe205e97976bb9d1ec006f5222360a89353e0"

**Comment by holiman** [comment]
A random hacker has found your publicallly exposed node and tries to get your rewards.1. You should not expose rpc to the internet (bind to 0.0.0.0).2. You should also not use allow-insecure-unlock unless you know _exactly_ what you're doing and why. There's a reason the argument is named insecure.

**Comment by Atrovzhi** [comment]
>  A random hacker has found your publicallly exposed node and tries to get your rewards.1. You should not expose rpc to the internet (bind to 0.0.0.0).2. You should also not use allow-insecure-unlock unless you know _exactly_ what you're doing and why. There's a reason the argument is named insecure.

Yes, you are right. I ignored that problem. 
Thanks.
