### ISSUE TITLE
No ethereum address found to fund on Rinkeby Authenticated Faucet

### ISSUE THREAD

**Issue by shobhit-stan** [ethereum/go-ethereum#23918]
My facebook post: https://www.facebook.com/100005057298505/posts/1955066701338554/

My account address: 0xA67b3b7F043f1FB5DE9a3F640aC2d921C6e08AD3

I tried with facebook and twitter both but didn't got any success. It's been a week now and I have also tried 3 different accounts with my friends. If this is an ongoing bug or something, please give me 15 ETH so that I can continue with my work or please help me fix any mistake I might have made in the process.

**Comment by ligi** [comment]
you might want to try the twitter auth method - that works better than the FB one

**Comment by shobhit-stan** [comment]
Now it worked with my twitter post: https://twitter.com/tuntun04018384/status/1461307499710074885

Thank you.
