### ISSUE TITLE
Big.Int should not be called by reference

### ISSUE THREAD

**Issue by winnie-byun** [ethereum/go-ethereum#23914]
I was looking for codes where the variables should be `const` but set as `var`.

For example, this code in `big.go` : 
```
var (
	Big1   = big.NewInt(1)
	Big2   = big.NewInt(2)
	Big3   = big.NewInt(3)
	Big0   = big.NewInt(0)
	Big32  = big.NewInt(32)
	Big256 = big.NewInt(256)
	Big257 = big.NewInt(257)
)
```

Calling `Set`, `Neg`, `Add`  on these variables could change the values.
```
func TestSet(t *testing.T) {
	x := Big1
	x.Set(big.NewInt(3))

	fmt.Println(Big1) // this prints 3
}

func TestNeg(t *testing.T) {
	x := Big1
	x.Neg(big.NewInt(3))

	fmt.Println(Big1) // this prints -3
}

func TestAdd(t *testing.T) {
	x := Big1
	x.Add(x, big.NewInt(5))

	fmt.Println(Big1) // this prints 6
}
```

This could effect the whole project if such code exist : 
```
	balance := stateDB.GetBalance(receiver) // this results in common.Big0 if receiver does not exist
	balance.Add(balance, amount)            // this could change the value of common.Big0
```

Shouldn't these codes be defined as get functions instead of `var`s? For example,
```
func Big1() *big.Int { return big.NewInt(1) }
func Big2() *big.Int { return big.NewInt(2) }
func Big3() *big.Int { return big.NewInt(3) }
..
```

**Comment by MariusVanDerWijden** [comment]
The idea behind defining these once is that it reduces the amount of allocations.
Your idea of defining them as functions would defeat the purpose as it would create a new allocation on each call.
You're right that they could be changed by `Set` etc. However we make sure not to do that in the code ever and to only use them as arguments to functions that don't modify them

**Comment by winnie-byun** [comment]
@MariusVanDerWijden How could you be sure that the arguments aren't changed? Is there a way to trace how they are used?

**Comment by holiman** [comment]
> How could you be sure that the arguments aren't changed?

Well, things like these are why it takes us sometimes very long time to review/merge PRs that are ostensibly very simple/small. We need to be meticulous, and yes, sometimes errors slip in.
