### ISSUE TITLE
Start Sepolia with Geth V1.10.12, explain the next steps

### ISSUE THREAD

**Issue by ProyectsX** [ethereum/go-ethereum#23917]
Hi i'm new to ethereum and i'm trying

 geth --sepolia

My node started without problems but I need to know the steps to follow until creating a dapp and supporting this project. (Eteherum)

There is a tutorial that you can send me please or follow this thread explaining step by step.

I have created this space on Gitter to share ideas and build step by step.

https://gitter.im/Sepolia-Ethereum/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by karalabe** [comment]
Hello,

  This issue tracker is mostly for discussing issues within the go-ethereum codebase. If you're looking for general discussions and/or questions about Ethereum, please head over to stack exchange. You'll find a lot more details about the DApp side of things and development on top in general.

https://ethereum.stackexchange.com/

Cheers.

**Comment by ProyectsX** [comment]
There is no record related to Sepolia on the page you send ...
