### ISSUE TITLE
How is the balance calculated

### ISSUE THREAD

**Issue by elylon1101** [ethereum/go-ethereum#23913]
https://ropsten.etherscan.io/address/0x925914D277CDd3ce2AF08408099712BDBb10DABA
![image](https://user-images.githubusercontent.com/54056210/141768242-8b620f3d-8252-431c-9afa-ebecc240409f.png)

Why are they not equal

**Comment by MariusVanDerWijden** [comment]
Internal transactions.
This has nothing to do with go-ethereum or ethereum itself, just with the way it is visualized by etherscan

**Comment by holiman** [comment]
You can go into each transaction (including internal), and for each transaction check how that transaction affected the state (e.g. balance). Example: 
![Screenshot 2021-11-15 at 12-03-33 Ropsten Transaction Hash (Txhash) Details Etherscan](https://user-images.githubusercontent.com/142290/141771267-b4860029-7892-4138-a557-00a0afd491ec.png)

Then you can get a more clear image of exactly how the balance changes. It does look a bit strange, but I haven't dived into it fully.
