### ISSUE TITLE
Transaction.GasPrice() is  error .  if transaction  is from  latest block .

### ISSUE THREAD

**Issue by wangruics** [ethereum/go-ethereum#23915]
```   
hash := "0x4923bf8bef127a0a988d598667560f2f334e48b84997dad1d89f07f49c486f42"
	txHash  := common.HexToHash(hash)
	tx,_,_ := client.TransactionByHash(context.Background(),txHash)
	log.Println(tx.GasPrice().String() , tx.Hash().String())
	//  tx.GasPrice()  IS  95657255940   NOT  66232681164

```

![TXT](https://user-images.githubusercontent.com/88173849/141770448-8bb6c8f6-221f-4be9-8eed-d4adae5b2e36.png)

**Comment by MariusVanDerWijden** [comment]
Oh you're correct, TxByHash returns the MaxFeePerGas not the GasPrice since the GasPrice is not set in the transaction object.

```go
	cl, err := ethclient.Dial("/home/matematik/.ethereum/geth.ipc")
	if err != nil {
		panic(err)
	}
	hash := "0x4923bf8bef127a0a988d598667560f2f334e48b84997dad1d89f07f49c486f42"
	txHash := common.HexToHash(hash)
	tx, _, _ := cl.Transa
```

```
(*types.Transaction)(0xc000092060)({
 inner: (*types.DynamicFeeTx)(0xc0000bc000)({
  ChainID: (*big.Int)(0xc00007c0e0)(1),
  Nonce: (uint64) 0,
  GasTipCap: (*big.Int)(0xc00007c0a0)(2500000000),
  GasFeeCap: (*big.Int)(0xc00007c080)(95657255940),
  Gas: (uint64) 329431,
  To: (*common.Address)(0xc00001c168)((len=20 cap=20) 0xb93Ca660aC25215256636736aa2Ee88A9a0c9f0D),
  Value: (*big.Int)(0xc00007c0c0)(10000000000000000),
  Data: ([]uint8) (len=4 cap=4) {
   00000000  12 49 c5 8b                                       |.I..|
  },
  AccessList: (types.AccessList) {
  },
  V: (*big.Int)(0xc00007c100)(1),
  R: (*big.Int)(0xc00007c120)(6501108409680924016493108103243441451555931408303484790430627811081883718745),
  S: (*big.Int)(0xc00007c140)(32378480534295158393913434061240601543923886428254301169089417470303197808096)
 }),
 time: (time.Time) 2021-11-15 12:35:19.001877205 +0100 CET m=+0.008143472,
 hash: (atomic.Value) {
  v: (interface {}) <nil>
 },
 size: (atomic.Value) {
  v: (interface {}) <nil>
 },
 from: (atomic.Value) {
  v: (types.sigCache) {
   signer: (*ethclient.senderFromServer)(0xc00001e200)({
    addr: (common.Address) (len=20 cap=20) 0x9b59d774A8b61c73C0cC41af7d96065eC91c1028,
    blockhash: (common.Hash) (len=32 cap=32) 0x1d8a08b734487967925a498182a71f99f9c6ec9482002b02f08a1b7b130eb069
   }),
   from: (common.Address) (len=20 cap=20) 0x9b59d774A8b61c73C0cC41af7d96065eC91c1028
  }
 }
})
```

**Comment by MariusVanDerWijden** [comment]
Hmm DynamicFeeTx type has no "actual gas used" field... might be good to add one

**Comment by wangruics** [comment]
> Hmm DynamicFeeTx type has no "actual gas used" field... might be good to add one

`
asMessage, e := tx.AsMessage(types.LatestSignerForChainID(big.NewInt(int64(CHAIN_ID))), block.BaseFee())
			if e == nil {
				log.Println(asMessage.GasPrice().String())
			}else{
				log.Println(e)
			}

`

AsMessage.GasPrice()  is  right  .        EIP-1559        
应该是伦敦升级之后变了 。

**Comment by holiman** [comment]
Oops, sorry, I deleted a comment erroneously

**Comment by holiman** [comment]
Triage discussion: 
So the node here _does_ return the actual effective `gasPrice` used during this transaction, but the ethclient marshals it into a types.Transaction. WHen marshalling that, it ignores the `gasPrice`, since it's not relevant -- it's only ever relevant in the context of the block where it was executed. 

@fjl will make some cleanup here.

**Comment by fjl** [comment]
Documentation improved in https://github.com/ethereum/go-ethereum/pull/23929

**Comment by fjl** [comment]
The problem is: `types.Transaction` does not know the effective gas price for EIP-1559 transactions. While the node returns the effective price via RPC, we ignore it for such transactions.

@wangruics You need to call `EffectiveGasTip` instead of `GasPrice` on the client side. This will give the correct value.

**Comment by sbrajchuk** [comment]
Have same problem.
@fjl Your solution not working.
For example:
network: etherium mainnet.
tx hash:  0xfc2a00cd6077111adb4367c61ef4c5f643bd02be4dd1bd7eeddd844068148a58
`EffectiveGasTip` returns `2000000000`

**Comment by fjl** [comment]
Sorry, I made a mistake. `EffectiveGasTip` does not have the basefee included, but it's technically included in the 'gas price'. So it's not a good solution.

**Comment by sbrajchuk** [comment]
In `EffectiveGasTip` I used `BaseFee` from the block of the transaction. 
`	hdr, err := blockchain.HeaderByHash(context.Background(), receipt.BlockHash)`
`	effectiveGas, err := tx.EffectiveGasTip(hdr.BaseFee)`

**Comment by fjl** [comment]
Yes, but it's still wrong. I explained my error here: https://github.com/ethereum/go-ethereum/pull/23929#issuecomment-974095122

Basically, we don't have a method that returns 1559 'effective gas price' on Transaction right now. We either need to add it, or explain how to compute it in the documentation of `Transaction.GasPrice`.
