### ISSUE TITLE
`t8n` spits out `receiptRoot`, but `types.Header` takes `receiptsRoot`

### ISSUE THREAD

**Issue by lightclient** [ethereum/go-ethereum#23921]
Seems like these should be the same? I can update if so.

**Comment by holiman** [comment]
@winsvega can we change this? heads-up, in case you're using this

**Comment by winsvega** [comment]
Renaming the field name is ok. I can adjust.

**Comment by lightclient** [comment]
@winsvega it's my favorite :)
