### ISSUE TITLE
Using external 1TB hard drive for the node

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#23923]
Hi! I just want to ask if I did the right thing on my node. Here's the things that I did.

1. I created a folder named "NODE" and installed geth app on my external HDD (D:)
2. I ran the node with geth --http --datadir D:\NODE command

I specifically wants to connect on Localhost:8545 on Metamask using Chain ID 1 and etherscan.io block explorer but it's not working.
When I tried to manually edit the information of Localhost network and change the Chain ID from 1337 to 1 so that I will be on mainnet network while using Localhost and etherscan.io for the Block Explorer, my ETH balance are not showing up. It seems like I am not connected to the mainnet.

Is there something wrong with the things that I've mentioned about how I ran my node? Please, help. Thank you.

**Comment by ligi** [comment]
You need to use a SSD - no HDD - a HDD is too slow to run a node.

**Comment by holiman** [comment]
> When I tried to manually edit the information of Localhost network and change the Chain ID from 1337 to 1 so that I will be on mainnet network while using Localhost and etherscan.io for the Block Explorer, my ETH balance are not showing up

It's very unclear to me what you are doing. By `localhost` you are talking about the interface on your "internet" networks, whereas "Chain ID" refers to something entirely different. Syncing geth on mainnet is just a matter of starting `geth` without any parameters, and letting it sync up. 

Which, as @ligi points out, may be undoable on an HDD.

**Comment by holiman** [comment]
Oh, original reported deleted the account, closing
