### ISSUE TITLE
Unable to snap sync a blockchain on AWS EFS as it has a hard limit of 32k open files

### ISSUE THREAD

**Issue by spullara** [ethereum/go-ethereum#23922]
#### System information
Geth
Version: 1.10.12-stable
Git Commit: 6c4dc6c38827296dec5a49a6ea25fd7f0eb4ac77
Git Commit Date: 20211108
Architecture: amd64
Go Version: go1.17.2
Operating System: linux
GOPATH=
GOROOT=go

#### Expected behaviour

Close files that aren't in use / have a settable limit

#### Actual behaviour

Every database file it opens stays open for the duration of the sync

#### Steps to reproduce the behaviour

Snap sync the blockchain on an AWS EFS volume

**Comment by plasticalligator** [comment]
**Expected behaviour**
For the software to function properly.

**Actual behaviour**
The software never functions properly.

**Steps to reproduce the behaviour**
Use the software.

**Comment by holiman** [comment]
The way file system limits work, is that we tell the OS to raise the limits for us. So we say e.g. "raise the ulimit to N", and the OS says "Ok, limit is now N". 
However, the OS also has filesystems, and in this case I guess it's a particular mount which interacts with the AWS EFS. And _that_ particular filesystem does not support N. So basically, the OS is fine with `N`, and doesn't give any error, but then later on, the filesystem complains that it cannot support N open filehandles. 

Using the libraries availalbe, we can't really handle this. The way to work around it is to `DatabaseHandles` in the toml config to limit this. 
```
[Eth]
DatabaseHandles = 32000
```

**Comment by holiman** [comment]
This has been answered and workaround posted, closing this. Feel free to reopen if you have an idea how we can improve this.

**Comment by barwod** [comment]
Hi,

When I added manualy this parameter to config.toml my nodes don't start. I got error:

"Fatal: /root/.ethereum/config.toml, line 13: field corresponding to `DatabaseHandles' in ethconfig.Config cannot be set through TOML"

My config.toml:
[Eth]
    NetworkId = 4
    SyncMode = "snap"
    EthDiscoveryURLs = ["enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.rinkeby.ethdisco.net"]
    SnapDiscoveryURLs = ["enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.rinkeby.ethdisco.net"]
    NoPruning = false
    NoPrefetch = false
    TxLookupLimit = 2350000
    LightPeers = 100
    UltraLightFraction = 75
    DatabaseCache = 512
    DatabaseFreezer = ""
    DatabaseHandles = 30000
    TrieCleanCache = 154
    TrieCleanCacheJournal = "triecache"
    TrieCleanCacheRejournal = 3600000000000
    TrieDirtyCache = 256
    TrieTimeout = 3600000000000
    SnapshotCache = 102
    Preimages = false
    EnablePreimageRecording = false
    RPCGasCap = 50000000
    RPCEVMTimeout = 5000000000
    RPCTxFeeCap = 1e+00
