### ISSUE TITLE
Get EOF when running personal.unlockAccount

### ISSUE THREAD

**Issue by andylockran** [ethereum/go-ethereum#2392]
#### System information

Geth version: `1.3.5`
OS & Version: Linux (Ubuntu stable ppa)
#### Expected behaviour

personal.unlockAccount to return a boolean (true/false)
#### Actual behaviour

persona.unlockAccount returns InvalidResponse
#### Steps to reproduce the behaviour

Run subsequent commands to force the error.
First discovered with random failures, steps above taken to force error reproduction.
#### Backtrace

```
➜  ~ » geth attach rpc:http://127.0.0.1:8545                                                                        1 ↵
instance: Geth/v1.3.5/linux/go1.5.1
modules: eth:1.0 miner:1.0 net:1.0 personal:1.0 web3:1.0
> acc = eth.accounts[1]
"0x4ca4640032fbdbfac87d0680ec937ade87519503"
> personal.unlockAccount(acc,"123456",10)
true
> personal.unlockAccount(acc,"123456",10)
Post http://127.0.0.1:8545: EOF
    at InvalidResponse (<anonymous>:-81662:-40)
    at send (<anonymous>:-156322:-40)
    at unlockAccount (<anonymous>:-133322:-40)
    at <anonymous>:1:1

> personal.unlockAccount(acc,"123456",10)
true
> personal.unlockAccount(acc,"123456",10)
true
> personal.unlockAccount(acc,"123456",10)
true
> personal.unlockAccount(acc,"123456",10)
true
> personal.unlockAccount(acc,"123456",10)
Post http://127.0.0.1:8545: EOF
    at InvalidResponse (<anonymous>:-81662:-40)
    at send (<anonymous>:-156322:-40)
    at unlockAccount (<anonymous>:-133322:-40)
    at <anonymous>:1:1

> personal.unlockAccount(acc,"123456",10)
Post http://127.0.0.1:8545: EOF
    at InvalidResponse (<anonymous>:-81662:-40)
    at send (<anonymous>:-156322:-40)
    at unlockAccount (<anonymous>:-133322:-40)
    at <anonymous>:1:1
```

**Comment by andylockran** [comment]
Additional Information:

This is the request/response in the stderror log:
```
I0330 13:14:55.768441   15478 mergedapi.go:61] personal_unlockAccount ["0x4ca4640032fbdbfac87d0680ec937ade87519503","123456",10]

I0330 13:15:11.528219   15478 types.go:106] Generated response: *shared.SuccessResponse &{%!s(float64=3) 2.0 %!s(bool=true)}

I0330 13:15:11.528790   15478 http.go:157] Sending payload: {
	"id": 3,
	"jsonrpc": "2.0",
	"result": true
```
This is what gets returned to the console:
```
> personal.unlockAccount(eth.accounts[1],"123456",10)
Post http://127.0.0.1:8545: EOF
    at InvalidResponse (<anonymous>:-81662:-52)
    at send (<anonymous>:-156322:-52)
    at unlockAccount (<anonymous>:-133322:-52)
    at <anonymous>:1:1
```

**Comment by bas-vk** [comment]
The problem is that it took ~16s to unlock the account. This causes the http request to time out. The computer geth is running on is either very slow or very busy. We could increase the timeout but this will not really solve the problem on even slower computers.

Geth has the `--lightkdf` argument. This will use a faster algorithm to unlock your keys (at a cost of reduced security margin). It was added for the situation geth would run in an environment with low cpu/memory resources.

**Comment by fjl** [comment]
Note that `--lightkdf` is not recommended and does not affect the speed of unlock for existing keys.
It reduces the strength of the scrypt KDF for new keys.

**Comment by andylockran** [comment]
What defines low cpu/memory resources?  I'll upgrade the AWS machine so that I can unlock accounts within a sensible timeout - where do I find details of these system requirements?

**Comment by andylockran** [comment]
Ok - have upgraded the AWS instance to a C4. level box (compute focused) and the speed is much improved.

However, I think there should be a bug open as surely the timeout should still return false.

**Comment by fjl** [comment]
The error happens because the HTTP connection is closed while waiting for a reply.

**Comment by andylockran** [comment]
Is that something that could be handled in the client?

**Comment by andylockran** [comment]
Also, then why do we sometimes get a failure after 10 secs and a success after 15?

**Comment by marlonmantilla** [comment]
If it helps someone else i was having this issue with an aws micro instance, after upgrading it to small the error goes away. So it's indeed a cpu/memory issue.
