### ISSUE TITLE
Geth ropsten invalid blocks count than on etherscan (split chain)

### ISSUE THREAD

**Issue by l4zygreed** [ethereum/go-ethereum#23930]
#### System information
Geth version: `1.10.12`
OS & Version: Linux

#### Expected behaviour
Can see transactions from `ropsten.etherscan.io` on node console

#### Actual behaviour
yesterday (two days ago node was alright) found that my test node have wrong amount of blocks than on etherscan.
restarted it few times on different versions (10.9 - 10.12), but it finds only ~2 peers in half of hour and doesn't rescan the chain.

also it's print to console
```
eth_1    | INFO [11-18|09:11:28.485] Looking for peers                        peercount=1 tried=54 static=0
eth_1    | INFO [11-18|09:11:38.529] Looking for peers                        peercount=1 tried=62 static=0
eth_1    | WARN [11-18|09:11:48.105] Head headers broke chain ordering        peer=c96397fa index=0 requested=11,363,724 received=11,448,384
eth_1    | WARN [11-18|09:11:48.105] Synchronisation failed, dropping peer    peer=c96397fad16bd7f808f08068c28853e55e28882e8ab779eb1a8df285a3cfe46e err="retrieved hash chain is invalid: head headers broke chain ordering"
eth_1    | INFO [11-18|09:11:48.534] Looking for peers                        peercount=1 tried=64 static=0
eth_1    | INFO [11-18|09:11:58.820] Looking for peers                        peercount=1 tried=46 static=0
eth_1    | INFO [11-18|09:12:08.861] Looking for peers                        peercount=1 tried=64 static=0
eth_1    | ERROR[11-18|09:12:17.050] Error in block freeze operation          err="block body missing, can't freeze block 10272196"
eth_1    | INFO [11-18|09:12:19.123] Looking for peers                        peercount=1 tried=39 static=0
eth_1    | INFO [11-18|09:12:29.123] Looking for peers                        peercount=1 tried=44 static=0
eth_1    | WARN [11-18|09:12:36.965] Served eth_call                        
```

`received=11,448,384` is actual correct block number on etherscan.
Node is fast synced, tried to get lowest avaible block via `getBlockByNumber` api, but now it also differs with etherscan info...

how can I fix this without deleting/rescanning all chain?

**Comment by lodotek** [comment]
What was your solution @l4zygreed ?

**Comment by l4zygreed** [comment]
just deleted and rescanned blockchain :/

**Comment by lodotek** [comment]
Fortunately somehow after trying several things I was able to get it synced without deleting/resyncing.
