### ISSUE TITLE
Can the boot node not do synchronization block work? When I build the test network

### ISSUE THREAD

**Issue by feiyiban** [ethereum/go-ethereum#23931]
A is the boot node, and B and C configure a as the boot node. Can block synchronization of a be turned off so that B and C can synchronize blocks through P2P with the help of a

**Comment by holiman** [comment]
Yes, `B` and `C` can sync fine even if you don't have `A` in the mix. It's just a discovery problem. And if `A` for some reason isn't a good sync partner, then `B` and `C` should still be able to find eachother through `A`.

**Comment by holiman** [comment]
But if the question is 'can I disable block synchronization from A`, then the answer is no, no such switch. However, it is theoretically possible to run the `cmd/bootnode` `bootnode` binary, which is just a node which provides capability for other peers to meet. We haven't really maintained the `bootnode` binary a lot, so I'm not 100% sure it works as expected.

**Comment by feiyiban** [comment]
thanks a lot
