### ISSUE TITLE
Feature Request: Health check cli using "geth doctor"

### ISSUE THREAD

**Issue by mohamedmansour** [ethereum/go-ethereum#23935]
# Rationale

Many node owners on discord are having problems with syncing or peer checking, and the answer is almost the same thing.  Doing something like `geth doctor`  would print out if:
- the disk drive is fast enough
- if peers can discover your node (opened port, etc)
- cpu core perf, if enough cores and bw is enough
- network speed test

This is inspired by Flutter, many people had problems running / installing it in the initial releases, and the devs created a beautiful plan called `flutter doctor` that makes sure the users system is good. Later, many companies, like Microsoft (Chromium) adopted this for internal devs too.

# Implementation

**Do you have ideas regarding the implementation of this feature?** 
I believe there are many go-lang libs for system profiling that we can use, I don't know from the top of my head.

**Are you willing to implement this feature?** 
Maybe ....

**Comment by holiman** [comment]
Something like this maybe? 
https://github.com/ethereum/go-ethereum/pull/21453

**Comment by mohamedmansour** [comment]
> Something like this maybe? 
> 
> https://github.com/ethereum/go-ethereum/pull/21453

That is a great start, if that is behind a flag like "geth doctor", then we can determine if that machine is good enough for it to sync before we actually start syncing.


Need doctor checks for cpu, disk speed, disk space, memory bw. This will help so many users who onboard geth

**Comment by holiman** [comment]
This feature request is old, and not picked up. I'll close it, if something like this is still wanted, then someone can open a new request.
