### ISSUE TITLE
Strange hang (or not) during state downloads

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#2394]
This is a cross post from the Mist repository. https://github.com/ethereum/mist/issues/444

---

OS: windows/amd64
Mist version: 0.5.2
Geth version 1.3.5

I've hit a very strange Mist sync issue. I've started up a 64bit Window build of Mist on a machine that never ever had any notion on Ethereum on it. It immediately found peers (it fluctuated between 11-12 peers all the time) and started the fast sync. After about 1 hour it finished the first phase which is downloading the chain itself. After that the whole thing just stalled and didn't seem to do anything. I've fast synced many times on the same network and state downloads always took a matter of minutes. Network connectivity wise the machine was mostly idling, from time to time a few kilobytes of traffic, usually none. The 11-12 peer count was still present. I killed the whole thing after another hour of stalling at that place. Sadly I didn't know that Mist dumps its own logs so I don't have them. Further I did try to attach to the node when it was running and it did report `syncing` but no details could be retrieved above that sadly. We should fix this as soon as we can.

**Comment by fjl** [comment]
There is no actionable content here. The content of this issue is: "fast sync failed once with geth 1.3.5".
