### ISSUE TITLE
EIP1559 raise gas & transaction fee saving

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#23942]
Q1: LegacyTx‘s `GasPrice` field now breaks into `GasTipCap`, `GasFeeCap` , and they value populate can refer to https://github.com/ethereum/go-ethereum/blob/e761255ba7e19ec7c380f008f9035da3caa77994/accounts/abi/bind/base.go#L234

The question is if I want to raise gas for faster including, should I raise `GasTipCap` alone or both `GasTipCap` and `GasFeeCap` ? At least 10%  increase?

Q2: Where are these tx fee saving comes from? (as showing in etherscan)

![image](https://user-images.githubusercontent.com/1725060/142749151-76bbb747-8640-4b28-a05a-b7dfd0cbe1b2.png)

**Comment by karalabe** [comment]
The transaction pool requires both values to be bumped.

As for the saving, I'm unsure how etherscan calculates it. My guess is that it assumes that you're willing to pay GasFeeCap in total for your tx, which in the case of legacy transactions would have been fully consumed, but with 1559, it may only be partially consumed depending on the base fee.

**Comment by huahuayu** [comment]
hi @karalabe thanks!

Could you please help clarify this:

originTx: 
- gasTipCap 10 gwei
- gasFeeCap 100 gwei

if I want to replace the tx, which is right?

- gasTipCap 11gwei
- gasFeeCap 110 gwei

or 

- gasTipCap 11gwei
- gasFeeCap 100 gwei (because every tx in same block pays the same, so no need to raise)

or 

- gasTipCap 11gwei
- gasFeeCap 100 gwei  + 1wei
