### ISSUE TITLE
Custom Wallet Name

### ISSUE THREAD

**Issue by HankFit247** [ethereum/go-ethereum#23953]
# Rationale
I'd like to have numerous Wallets, with easily identifiable names.  Rather than a bunch of UTC...   Then I wouldn't need to keep a manual directory record of the intended purpose of each wallet.

# Implementation
Create:
--walletname
personal.newAccount("notmyrealpassword") --walletname FriendlyWalletName

Are you willing to implement this feature?
Beyond the scope of my experience.

https://geth.ethereum.org/docs/interface/command-line-options

**Comment by holiman** [comment]
So there are two ways to go about this. 

1. Simply rename the files, locally. This solves (?) your problem. 
2. An idea I've had for a couple of years, but never got around to fixing. Having an additional meta-data storage, so you can attach metadata to wallets. These would be 'stub' files, which e..g contains a user-friendly name, but also, in the case of hardware wallets, can say things like "at derivation path xx/yy/zz, the key `myTestSigner` resides". 

The latter thing is quite a big project, and not something that we've prioritized. Our preferred wallet solution, `clef` still lacks a UI and afaik is not widely adopted, so I'm a bit hesitant to spend a lot of time on it until we have a better UI/UX.

**Comment by holiman** [comment]
It's not something in our short or mid-term plans, so I'll close this, as right now it's "wontfix"
