### ISSUE TITLE
flag provided but not defined: -rpc

### ISSUE THREAD

**Issue by sla-te** [ethereum/go-ethereum#23951]
```geth --gcmode archive --syncmode full --rpc ""  --rpcaddr 127.0.0.1 --rpcapi eth,web3,debug --datadir /ext/eth_chain```
gives ```flag provided but not defined: -rpc```

Im trying to setup geth on a dedicated server (linux) and make I can limit the IPs that can connect to it. Already digged through around 10 different guides but everything seems heavily outdated or incomplete.

**Comment by s1na** [comment]
The `--rpc` flag was deprecated in favor of `--http`. You also need to change `--rpcaddr` to `--http.addr` and `--rpcapi` to `--rpc.api`.

**Comment by sla-te** [comment]
Thank you for the quick reply, much appreciated. Which local wallet can I use to connect to the remote node and by passing these args im probably not yet setup to connect to it, could you advise an up to date guide that I could follow?
