### ISSUE TITLE
https://faucet.rinkeby.io/ Offline

### ISSUE THREAD

**Issue by markrosenbaum** [ethereum/go-ethereum#23958]
Hi,
I noticed that the Rinkeby faucet is down.
![Screenshot 2021-11-23 11 00 30 AM](https://user-images.githubusercontent.com/57112559/143059429-cd13f5e5-13de-4d9f-ac9a-c5361d6a4244.png)

Is it possable for anyone to send 5-7 Rinkeby ETH to 0x5A30e92350C61960Dbb8c7D6E9F9e1f6C487280B ASAP?

**Comment by omneuro** [comment]
Yea its been down for a while now, maybe someone with alot could spare us a few. 
It would be greatly appreciated, Address: 0x6CB7c969570a2FeFeAf5D3f05Cca7bEE08952faE

**Comment by karalabe** [comment]
We're aware, there are a few alternative faucets you can try:

- https://faucets.chain.link/rinkeby
- https://app.mycrypto.com/faucet

**Comment by botapierna** [comment]
neither of those faucets work
can someone send me 5 ETH on Rinkeby Testnet: 0x3C499B449BC28Eb4A1DBe933fFe71b33A2CbB327

**Comment by almodhesh** [comment]
an someone send me 5 ETH on Rinkeby Testnet:0x2Fcd0648A9646922d3523A23b0b7D6E68412Fc30

**Comment by Cyberdevil112** [comment]
Any one should help me with 0.5eth 
0xf517df11C15f3947E24b51e97d4c8b32B7190DAe

**Comment by manny-uncharted** [comment]
I'm getting an error stating insufficient gas fees. on the rinkeby test network. I currently need 10 ETH

**Comment by Driss68** [comment]
I don't have anything on my account If you want to help me, I would appreciate it 👍 
0xeDc716f46fFd82601043484274d766133BC7013f

**Comment by a5medHub** [comment]
try out these links: they also give test ETH:
https://faucet.paradigm.xyz/
https://rinkebyfaucet.com/
https://faucets.chain.link/rinkeby
