### ISSUE TITLE
Add SimulatedBackend configuration options

### ISSUE THREAD

**Issue by divergencetech** [ethereum/go-ethereum#23959]
# Rationale

The SimulatedBackend is used in testing so should be configurable in order to match a wide variety of situations. While the default values are almost always fit for purpose, niche use-cases require additional configuration. My particular use-case is Solidity code coverage with contracts instrumented by https://github.com/sc-forks/solidity-coverage. This requires access to the `vm.Config.Tracer` to inspect the opcode execution however the SimulatedBackend uses a zero-value `vm.Config{}` when instantiating its blockchain:

https://github.com/ethereum/go-ethereum/blob/6c4dc6c38827296dec5a49a6ea25fd7f0eb4ac77/accounts/abi/bind/backends/simulated.go#L81

Modifying the config via `SimulatedBackend().Blockchain().GetVMConfig()` doesn't seem to work, presumably because the Tracer has already been seen to be nil.

# Implementation

I am willing to implement the feature.

Any configuration directives can be exposed with variadic options ([example](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis)) that change the `NewSimulatedBackend*()` constructors in a backwards-compatible manner. This approach doesn't require a full suite of options to begin with so is quick to implement with a minimal set, but easy to extend later.

Example:

``` Go
// A config defines configuration directives for new SimulatedBackends.
// Its default value is defined in NewSimulatedBackendWithDatabase() and
// is modified with Options.
type config struct {
  vmConfig vm.Config
  …
}

// An Option configures a new SimulatedBackend.
type Option interface {
  update(*config)
}

func NewSimulatedBackendWithDatabase(database ethdb.Database, alloc core.GenesisAlloc, gasLimit uint64, opts ...Option) *SimulatedBackend {
  cfg := &config{
    vmConfig: vm.Config{}, // not technically needed as it's the zero value, but demonstrative
    … // all existing values
  }
  for _, o := range opts {
    o.update(cfg)
  }
  … // existing code, drawing from cfg
}

// WithVMConfig specifies the VM config used by a SimulatedBackend's underlying
// blockchain.
func WithVMConfig(cfg vm.Config) Option {
  return vmConfigOpt(cfg)
}

type vmConfigOpt vm.Config

func (o vmConfigOpt) update(cfg *config) {
  cfg.vmConfig = vm.Config(o)
}

// End user:
opt := backends.WithVMConfig(vm.Config{
…
})
sim := backends.NewSimulatedBackendWithDatabase(db, alloc, limit, opt)
// and existing code remains unchanged because opts are variadic
sim := backends.NewSimulatedBackendWithDatabase(db, alloc, limit)
```

**Comment by divergencetech** [comment]
I dug into the code and found that my assumptions were wrong so this is now obsolete. I needed to set `vm.Config.Debug` as well as provide a `Tracer`.

**Comment by deitch** [comment]
@divergencetech how did you set it and use it? Do you mind sharing an example? I have been struggling with figuring out why a contract call is not executing properly in the `SimulatedBackend`, debug tracing would (I presume) be helpful, but I cannot figure out how to set it.
