### ISSUE TITLE
RPC `Client` doesn't contain London hardfork methods

### ISSUE THREAD

**Issue by fedekunze** [ethereum/go-ethereum#23964]
# Rationale

`ethclient.Client` or `gethclient.Client` should contain the latest methods from the London hard fork (`eth_feeHistory`, `eth_resend`, `eth_fillTransaction`, etc)

**Why should this feature exist?**

go Clients should be able to call the new methods without having to implement a new client

**What are the use-cases?**

E2E and integration tests, APIs, support latest changes on the RPC server, etc

**Do you have ideas regarding the implementation of this feature?**

- Define a list of missing methods and where should they be implemented (gethclient or ethclient)
- Implement based on other references from the same package
- Test

**Are you willing to implement this feature?**

yes

**Comment by holiman** [comment]
I think the reasoning usually is that ethclient should contain mostly methods that are implemented broadly -- so it can be used equally against a nethermind/besu node, as with geth. Not sure if they support those methods..?

**Comment by fjl** [comment]
I think we should add them to gethclient first

**Comment by MariusVanDerWijden** [comment]
@fedekunze are you willing to implement these RPC calls in gethclient?

**Comment by MariusVanDerWijden** [comment]
The Ethclient has `eth_feeHistory` now. The other methods are not implemented in either ethclient or gethclient yet. I would argue that they are not used very often so it only makes sense to add them if someone really needs them and wants to provide the code for it.

**Comment by Tikaryan** [comment]
Hi @MariusVanDerWijden, Is this task still available, and if so, I would like to work on it.
Please let me know where can i get the list of all the clients that needs to be implemented for `geth`.

**Comment by Nouri11190** [comment]
up-for-grabs

**Comment by Nouri11190** [comment]
push the changes you made to the new header (Privasea.ai)

**Comment by charles-chenzz** [comment]
does this still under working in progress?

**Comment by fjl** [comment]
We will not add `eth_fillTransaction` to ethclient, because it has a different approach to transaction sending that requires you to construct the tx yourself on the client side. `eth_resend` is kind of deprecated (it's not even in the API spec).

**Comment by jonreiland** [comment]
Does this issue need work? If so, I'd like to take a stab at it by adding to the `gethclient`.

**Comment by lightclient** [comment]
I think it's okay to close this. `eth_feeHistory` was implemented and we won't implement the other two in `ethclient`.
