### ISSUE TITLE
core/vm: Better handling of static mode violation (ErrWriteProtection)

### ISSUE THREAD

**Issue by chfast** [ethereum/go-ethereum#23968]
Detection of static mode violation (`ErrWriteProtection`) should be handled by the affected instructions (`operation.writes`), not in the interpreter loop:

https://github.com/ethereum/go-ethereum/blob/66ee9422f56626dccc94b00762b8991c9b3195b0/core/vm/interpreter.go#L207-L217

1. Please confirm that `in.readOnly` can be true only when `in.evm.chainRules.IsByzantium`, so the condition `in.readOnly && in.evm.chainRules.IsByzantium` can be simplified.
2. Move this check to implementations of the affected instructions (e.g. `opCall()`, `opSstore()`).
3. Remove the check from the interpreter loop.
4. Remove `operation.writes` field.

This should land after #23952.

**Comment by holiman** [comment]
1. `in.readOnly` is only ever set from `StaticCall`, which was introduced in byzantium. So ACK on that.

**Comment by holiman** [comment]
Related observation: at that point in the code, we have both `readOnly` from the stack, and `in.readOnly` via pointer. Would probably be better to use `readOnly` instead of `in.readOnly` when checking the condition

**Comment by chfast** [comment]
> 1. `in.readOnly` is only ever set from `StaticCall`, which was introduced in byzantium. So ACK on that.

I confirmed that with `panic()` on State Tests.

**Comment by chfast** [comment]
As @axic noted, this will change the trace because the "readOnly" will be checked after "memory".

**Comment by holiman** [comment]
There's one thing though... IIRC, parity had a consensus issue, related to the order in which they did certain things. A 'forbidden' op was invoked, but with too few stack items. Depending on whether they errored on 'shallow stack' or 'write protected', they reverted back to the wrong scope. 
I don't recall the exact details, but might be something we need to have in mind when doing this. 

As for trace changing, I'm not sure that matters. The differential fuzzers don't care about the wording of the error messages.

**Comment by holiman** [comment]
> IIRC, parity had a consensus issue

It was this: https://github.com/openethereum/parity-ethereum/pull/6889/files 

So if the balance was too low, the create/call simply failed. So remained in the same scope, but with a `0` on the stack. Whereas it _should_ have dropped back one level. If we just move the check slightly into the ops themselves, that should be fine.

**Comment by holiman** [comment]
`write` ops

- SSTORE
- LOG0
- LOG1
- LOG2
- LOG3
- LOG4
- CREATE
- CREATE2
- SELFDESTRUCT

**Comment by axic** [comment]
> As @axic noted, this will change the trace because the "readOnly" will be checked after "memory".

My comment was also a bit more general, it changes the order of evaluation for these checks. We discussed order-of-evaluation questions as part of EIP-3860 (limit initcode), and found that for most of the cases state tests do not care about it.
