### ISSUE TITLE
Data Race in dialScheduler

### ISSUE THREAD

**Issue by BlockFuzz** [ethereum/go-ethereum#23965]
#### System information

Geth version: `1.10.9-unstable-9ada4a2e-20210910`
OS & Version: MacOS
Network: Private test net

#### Expected behaviour
node run normally

#### Actual behaviour
Data race in dialScheduler

#### Steps to reproduce the behaviour
1. setup a 10-node private geth nodes lcoally
2. setup a fuzzing node continually sending fuzzed messages to other 10 normal geth nodes.
3. After more than 24 hours fuzzing experiment, one of the geth node who is run in fast mode crashed down.
The running command for the node is `./build/bin/geth --identity "ETH-node10" --datadir "node10" --ethash.dagdir "node10" --port "30312" --maxpeers 15 --networkid 10086 --syncmode "fast" --bootnodes "enode://e71bec68f09c4b9567bd4575d855ea61b179b1d64e6f78c861ebddf3783178f95edaaf39647c1f792bc654d0931ad25415d50c25c437787183c0b0a32a76da85@127.0.0.1:0?discport=30301" --mine --miner.etherbase 0xd192415624a039b24ad571f96cb438de9f0556a7 --miner.threads 1 console`

#### Backtrace

![image](https://user-images.githubusercontent.com/93894333/143182989-5d719bef-4a8f-4131-b69d-b91be3765c30.png)

**Comment by holiman** [comment]
Yup, but this is a duplicate of https://github.com/ethereum/go-ethereum/issues/23430
