### ISSUE TITLE
signer/core can't compile to wasm due to unix constrains

### ISSUE THREAD

**Issue by goldbock** [ethereum/go-ethereum#23972]
#### System information

go-ethereum tip

#### Expected behaviour
compile to wasm

#### Actual behaviour
signer/core package does not compile to wasm

#### Steps to reproduce the behaviour
import "github.com/ethereum/go-ethereum/signer/core"

Use the signer/core to generate an EIP712Domain signature; 

#### Backtrace

````
      imports github.com/ethereum/go-ethereum/signer/core
        imports github.com/ethereum/go-ethereum/consensus/clique
        imports github.com/ethereum/go-ethereum/consensus
        imports github.com/ethereum/go-ethereum/core/state
        imports github.com/VictoriaMetrics/fastcache
        imports golang.org/x/sys/unix: build constraints exclude all Go files in /Users/x/go/pkg/mod/golang.org/x/sys@v0.0.0-20210910150752-751e447fb3d0/unix
````

I've used go-ethereum successfully in wasm environment for a while until I had to use EIP712Domain signature and import types from  "signer/core".  I've fixed the build tags on fast cache in https://github.com/VictoriaMetrics/fastcache/pull/62 but there seem to be other transitive dependencies such `leveldb` and `edsrzf/mmap-go` that require file locking. 

I believe the TypedData structs should perhaps be exported in a separate package so that the client can generate EIP712Domain signatures without importing (transitively) leveldb and other packages that require file synchronisation.

 A more broad scope would be to make the whole go-ethereum sdk wasm compatible ( https://github.com/ethereum/go-ethereum/issues/16192 ) but that's a different, bigger issue.

**Comment by holiman** [comment]
Yes, I guess we can move the `TypedData` to it's own package. Want to make a PR?

**Comment by goldbock** [comment]
I think it would be great if you do it... I will probably mess the package organisation. 

As a quick workaround I actually patched (in a brutal/poor way) several packages[0]  that throw errors on wasm compilation  to make sure that I won't hit unix constraints errors if I ever need to use other go-ethereum packages that have these dependencies.

[0]  go-ethereum/accounts/scwallet (disabled support in js)
goleveldb
prometheus-junkyard/tsdb
edsrzf/mmap-go
VictoriaMetrics/fastcache ( easy fix)

**Comment by fjl** [comment]
Seems to me like the package `signer/core/apitypes` is the ideal location for `TypedData`. We created this package specifically for types which are used by the RPC API, and it was created because of a similar dependency issue.
