### ISSUE TITLE
Transaction.AsMessage   error:  invalid transaction v, r, s values

### ISSUE THREAD

**Issue by wangruics** [ethereum/go-ethereum#23979]
tx : 0x570ce19176bd0002b04a9179309129bbdaf0c4252ffeb76aedbb038cdf662850    block_number: 46205

`func  TestTx(){

	txStr := "0x570ce19176bd0002b04a9179309129bbdaf0c4252ffeb76aedbb038cdf662850"
	transaction,_,err := client.TransactionByHash(context.Background(),common.HexToHash(txStr))
	if err!= nil{
		log.Fatal("get Transaction error")
	}

	block,err :=  client.BlockByNumber(context.Background(),big.NewInt(46205))
	if err != nil{
		log.Panic("get block error")
	}

	log.Println(transaction.Hash().String() , block.Number().String())
	log.Println(block.BaseFee()) // BaseFee is nil
	asMessage, e := transaction.AsMessage(types.LatestSignerForChainID(big.NewInt(1)), block.BaseFee())
	if e == nil {
		log.Println(asMessage.From())
		asMessage.GasPrice().String()
	}else{
		log.Println(e)  // here     invalid transaction v, r, s values
	}

}`

**Comment by karalabe** [comment]
Block 46205 is part of Frontier, which did not have chain-id based replay protection yet. That was introduced at a later fork. You'll need to use a `nil` chain ID to recover signatures up until block `#2675000` https://eips.ethereum.org/EIPS/eip-607

**Comment by wangruics** [comment]
> Block 46205 is part of Frontier, which did not have chain-id based replay protection yet. That was introduced at a later fork. You'll need to use a `nil` chain ID to recover signatures up until block `#2675000` https://eips.ethereum.org/EIPS/eip-607

`
asMessage, e := transaction.AsMessage(types.LatestSignerForChainID(nil),nil)
	if e == nil {
		log.Println(asMessage.From())
		asMessage.GasPrice().String()
	}else{
		log.Println(e)  // here     invalid transaction v, r, s values
	}

`

the  same  error   .

**Comment by karalabe** [comment]
Hmm, seems `LatestSignerForChainID` will at max go down until Homestead, but not Frontier. There are a few signatures that are valid in Frontier but not any more in Homestead. Could you try `types.MakeSigner(params.MainnetChainConfig, big.NewInt(46205))` to create the signer? That should also support Frontier signatures that were invalidated later https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction_signing.go#L40

**Comment by wangruics** [comment]
> 
` types.MakeSigner(params.MainnetChainConfig, big.NewInt(46205)) `
Thanks. It is ok, I  got the correct from of this transaction
