### ISSUE TITLE
Showing Faucet Offline

### ISSUE THREAD

**Issue by krixnaas** [ethereum/go-ethereum#23981]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.
![image](https://user-images.githubusercontent.com/14975723/143568511-9c34f9bb-4226-474a-90a2-1ffbe28ff29c.png)

**Comment by louiskwt** [comment]
<img width="1315" alt="Screenshot 2021-11-26 at 22 32 48" src="https://user-images.githubusercontent.com/33587343/143596192-a795dee8-c3f6-44ce-8fbb-92692a75db53.png">

I'm new to this, and I experienced the same issue here. Does anyone know why did it happen?

**Comment by holiman** [comment]
Sometimes, it's ofline. We're aware, and we're working at it. The faucet is a light-client, sometimes it doesn't have peers serving it content.
