### ISSUE TITLE
Before Byzantium there was no status , How can I now  the transaction before Byzantium  is success or  fail ?  

### ISSUE THREAD

**Issue by wangruics** [ethereum/go-ethereum#23980]
`  
	txStr := "0x570ce19176bd0002b04a9179309129bbdaf0c4252ffeb76aedbb038cdf662850"
	transaction,_,err := client.TransactionByHash(context.Background(),common.HexToHash(txStr))
	if err!= nil{
		log.Fatal("get Transaction error")
	}

	receipt,_ := client.TransactionReceipt(context.Background(),common.HexToHash(txStr))
	log.Println(receipt.Status)  // here status == 0
`

Before Byzantium there was no status .  How can I now  the transaction before Byzantium  is success or  fail ?  

#19879

**Comment by s1na** [comment]
AFAIK your best bet is to trace the transaction and see if the top-level call fails. But for that you'd probably need an archive node. In fact not being able to observe the status of a historical tx is why the status field was introduced in Byzantium as per the EIP [motivation](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-658.md).

**Comment by s1na** [comment]
Closing now. Please re-open if you still have questions regarding this.
