### ISSUE TITLE
ABI: `Arguments.Copy(v, values)` fails for `type(v) = struct` and `len(values) = 1`

### ISSUE THREAD

**Issue by matthiasgeihs** [ethereum/go-ethereum#24019]
#### Context

Location: https://github.com/ethereum/go-ethereum/blob/1fa91729f2a591df2baf2dc77e81711a6e61c028/accounts/abi/argument.go#L118
go-ethereum version: v1.10.12 (using go-ethereum as a go module)

#### Problem

When calling [`args.Copy(v, values)`](https://github.com/ethereum/go-ethereum/blob/1fa91729f2a591df2baf2dc77e81711a6e61c028/accounts/abi/argument.go#L118) with `len(values) == 1`, this function calls `args.copyAtomic(v, values[0])`.

If `v` is a struct, `args.copyAtomic` then calls `set(dst.Field(0), src)`, attempting to assign the value to the first field of the struct, whereas it should instead assign the value to the struct itself.

#### Steps to reproduce the behaviour

```go
package test

import (
	"testing"

	"github.com/ethereum/go-ethereum/accounts/abi"
)

type Frame struct {
	A, B uint64
}

var FrameType = func() abi.Type {
	t, err := abi.NewType(
		"tuple",
		"Frame",
		[]abi.ArgumentMarshaling{
			{Type: "uint64", Name: "A"},
			{Type: "uint64", Name: "B"},
		},
	)
	if err != nil {
		panic(err)
	}
	return t
}()

func TestPackUnpack(t *testing.T) {
	frameArgs := abi.Arguments{
		{Name: "Frame", Type: FrameType},
	}

	src := Frame{A: 0, B: 1}
	b, err := frameArgs.Pack(src)
	if err != nil {
		t.Errorf("Packing: %v", err)
	}

	values, err := frameArgs.Unpack(b)
	if err != nil {
		t.Errorf("unpacking: %v", err)
	}

	var dst Frame
	err = frameArgs.Copy(&dst, values)
	if err != nil {
		t.Errorf("copying: %v", err)
	}
}
```

**Comment by rjl493456442** [comment]
The copy function will move the decoded value into the content receiver. The receiver is expected to be a wrapper(e.g. a struct) and the fields in the struct correspond to the decoded value one-to-one. 

If there is only a single struct value, so the receiver is expected to be something like this:

```
type struct Result {
    F Frame
}
```

**Comment by rjl493456442** [comment]
Will close it now, feel free to reopen it if you still have the problem.

**Comment by matthiasgeihs** [comment]
OK, would be good to have the function documented accordingly. I think this is not obvious.
