### ISSUE TITLE
p2p/discover: vicious loop with local node inserted into kademlia table

### ISSUE THREAD

**Issue by christoph2806** [ethereum/go-ethereum#2401]
#### System information

Geth version: 
Version: 1.3.5
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: windows
GOPATH=
GOROOT=c:\go
OS & Version: Windows 7

#### Expected behaviour
Geth starts with empty blockchain and syncs up to the last best block.

#### Actual behaviour
Geth starts, syncs up to block 82656 and then looses connection to all peers. 
I watched geth syncing using the console and command admin.peers.
At the beginning, I have 5-9 active peers. After about 20minutes, the number of peers decreases, then only one peer is left, then 0 peers. Geth never recovers or finds new nodes afterwards.

If I install a file "static-nodes.json" (see below) in the datadir with some node addresses, geth succeeds in a full sync of the blockchain. 

#### Steps to reproduce the behaviour
Install Mist 0.5.2.
cd Ethereum-Wallet-win64-0-5-2\resources\node\geth
geth -verbosity "6" console 2>>log.txt

(a shortened log is attached, the original log is about 80MB).

#### Backtrace
n/a

[static-nodes.json.txt](https://github.com/ethereum/go-ethereum/files/198343/static-nodes.json.txt)
[log_short.txt](https://github.com/ethereum/go-ethereum/files/198331/log_short.txt)

**Comment by karalabe** [comment]
@fjl This may actually be the log we've been so keen on receiving.

They show that the node manages to place itself and itself only in its discovery table, which results in only asking itself for remote nodes, which seems to return itself again. This results in some weird scenario where the bootnodes aren't consulted any more and we constantly self-discover and self-connect.

At least this is the scenario that looks likely to me if you check that the single remaining node at the end of the log is actually the current node's enode ide (if you check the start of the log).

**Comment by fjl** [comment]
Thanks for the analysis. We should definitely fix this case (how did the local node even get into the table?). Before it goes into this loop though, it exhausts the cache of previously known nodes and receives very few replies. My guess is that machine time is in the past as well.
