### ISSUE TITLE
How to build an Ethereum private chain using POS consensus

### ISSUE THREAD

**Issue by katoyi120** [ethereum/go-ethereum#24015]
I want to use POS consensus to build my own private chain, who can tell me how to do it?

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
