### ISSUE TITLE
Geth “10.12 stable” runs for 1 day then crashes with OOM error

### ISSUE THREAD

**Issue by nevermoremining** [ethereum/go-ethereum#24020]
Geth will only run for 1 day trying to sync mainnet before erroring out with an OOM error. Blocks are syncing but memory slowly fills up. 

Trying to do a full sync and then operate as a node. Have tried increasing cache values ranging from 5-10GB but it still crashes. (Geth limits to 5GB anyways)

Hardware is dedicated to only running Geth. Xeon 3.4GHz 6C/6T processor, 16GB of RAM, 8 TB SSD (dual 4GB in RAID 0). OS is Ubuntu Server 20.04, no GUI just command line. Geth is only process run by user account.

Journalctl shows no errors related to Geth. 

Command Line Entry (via bash file): geth console —datadir “location” —cache 5285 —syncmode full —maxpeers 50

**Do I need more than 16GB physical RAM to run Geth on Mainnet?**

**Will this issue go away once node is fully synced? Just keep restarting it until it’s synced?**

Will add logs in a few mins.

_Originally posted by @nevermoremining in https://github.com/ethereum/go-ethereum/issues/23907#issuecomment-981150261_

*Edit to bold font for questions

**Comment by nevermoremining** [comment]
**dmesg -T |egrep -i "killed process"**
> [Wed Nov 24 11:23:43 2021] Out of memory: Killed process 1385 (geth) total-vm:20877136kB, anon-rss:14705788kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:31276kB oom_score_adj:0
> [Thu Nov 25 22:09:39 2021] Out of memory: Killed process 6744 (geth) total-vm:21935676kB, anon-rss:14621244kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:32604kB oom_score_adj:0
> [Sat Nov 27 08:46:17 2021] Out of memory: Killed process 9929 (geth) total-vm:21476796kB, anon-rss:14571092kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:32888kB oom_score_adj:0
> [Sun Nov 28 19:24:28 2021] Out of memory: Killed process 13877 (geth) total-vm:21406580kB, anon-rss:14526556kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:31648kB oom_score_adj:0
> [Mon Nov 29 17:38:49 2021] Out of memory: Killed process 15771 (geth) total-vm:21004412kB, anon-rss:14508364kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:31696kB oom_score_adj:0

**journalctl -u geth**
> -- Logs begin at Fri 2021-11-12 02:38:40 UTC, end at Tue 2021-11-30 02:26:58 UTC. --
> -- No entries --

Text Files
[Journalctl_Log_Output.txt](https://github.com/ethereum/go-ethereum/files/7622625/Journalctl_Log_Output.txt)
[grep_error.log](https://github.com/ethereum/go-ethereum/files/7622626/grep_error.log)

**Comment by holiman** [comment]
The logs you have provided doesn't contain much -- could you please provide the logs for the `geth` process? Since you're running the running the process via bash, the log output doesn't wind up in the journalctl.

**Comment by karalabe** [comment]
With default configs, the max memory usage of the master branch for a snap sync was 7GB and full sync still ongoing, but the max was 10GB. This with the default 4GB cache limits. My suggestion would be to they with the default 4GB and see how large memory use gets.

**Comment by nevermoremining** [comment]
> could you please provide the logs for the `geth` process?

Where are these logs stored for previous failures? Or do I need to add something like “2>> logfile.txt” to the Geth command and wait for a failure? Didn’t see logs in normal Ubuntu locations but could have missed them. Those 2>> logs say similar things though. Added a phone photo of the OOM message. The process just dies.

![654F56D8-261D-4595-82A9-E48A347012D9](https://user-images.githubusercontent.com/95189202/144044519-865f8e15-3a4b-42f3-8a1f-122d23c44865.jpeg)
(This one’s funny because it failed 2 mins after I checked it but I came back the next morning so lost some time…)


>(I'm at block 8.1M)

This started happening around 10M for me, I’m at 13.4M now, really close to sync’d.

**Comment by holiman** [comment]
> or do I need to add something like “2>> logfile.txt” 

Yup, something like that

**Comment by nevermoremining** [comment]
Running with the pipe output to file added, might finish the sync though before it fails again. The screenshot shows the same message at the bottom as what was in the dmesg log. 

Is it better to set a smaller Cache value in these situations or will memory leak always be a concern with how Geth utilizes RAM?  I figured with 16GB of physical RAM at least 8GB could be allocated as cache, but is it better to use the default 4GB cache size?

**Comment by nevermoremining** [comment]
Here is the log file from Geth, but I dont see anything out of the ordinary. Tested to make sure it was writing out, then initiated a new sync from the bash file, ran for about 10-11 hours before just closing with the same OOM error. 

[Geth_error_output.log](https://github.com/ethereum/go-ethereum/files/7629526/Geth_error_output.log)


Reinitiated the sync, but with only 2048 of Cache to try a different value.

**Comment by nevermoremining** [comment]
Just kept restarting the sync until it finished. Issue must have been allocating too large of a cache for 16Gb of physical RAM on the server. Not sure if better memory management could be implemented or if documentation could better define what cache value to use at various RAM amounts.
