### ISSUE TITLE
Error: invalid gas used

### ISSUE THREAD

**Issue by TonyHzr** [ethereum/go-ethereum#24037]
Error: invalid gas used (remote: 7979005 local: 7979332)

Geth version: 1.10.13

Block Number: 8262819

Block Hash: 0x1bdbbded4f50d074bef4683da452b5ed06a22caa00cc219dd6078690263c22fd

Transaction Hash: 0xb4acf2df75e7e798a86e9bd9874eb1bddd8f45e1a5618baad979d86d3083e86a

Expect usage by Txn is 54,904, but result is 55, 231

> 361: cumulative: 7815754 gas: 55231 contract: 0x0000000000000000000000000000000000000000 status: 0 tx: 0xb4acf2df75e7e798a86e9bd9874eb1bddd8f45e1a5618baad979d86d3083e86a logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:

**Comment by s1na** [comment]
I assume geth reported this as a bad block? Can you please post more logs surrounding the error and also the startup logs? specifically if there were unclean shutdowns

**Comment by TonyHzr** [comment]
Thank you very much for your reply. Forgive my confusing description, I was so anxious yesterday.

In fact, I am trying to run an archived node. I downloaded the original blocks data, including block header, transactions, uncles, from the infura due to network reasons and re-executed all blocks to get the world states of each block height. I have verified them through the block header hash and MPT root hash of transactions.

The following is the re-executed code omitting the part that reads the block. It started from the genesis block and worked to a block height of 8262818. However, the error described earlier occurred at that height of 8262819.

The content of the output indicates that the gas consumed for execution is different from that indicated in the block (that is 8262819). According to my observation, this happened in the 361st transaction: 7979332 - 7979005 = 55231 - 54904 = 327.

Among them, 7979332 is the gas consumed by my execution, 7979005 is the value indicated in the block, 55231 is the consumed gas of the 361st transaction by the execution, and 54904 is from the web etherscan.

And, in this block, only the 361st transaction failed to execute, I am not sure if the error is related to it.

What should I do to fix this error, thank you again for your help.


    // Initialize the genesis block
	chainConfig, genesisHash, genesisErr := core.SetupGenesisBlockWithOverride(chainDb, nil, ethconfig.Defaults.OverrideArrowGlacier)
	if _, ok := genesisErr.(*params.ConfigCompatError); genesisErr != nil && !ok {
		return genesisErr
	}

    // Initialize the eth config
	config := ethconfig.Defaults
	config.SnapshotCache = 0          
	config.Ethash.CachesInMem = 10    
	config.Ethash.CachesOnDisk = 15   
	config.Ethash.DatasetsInMem = 5   
	config.Ethash.DatasetsOnDisk = 10 
	config.DatabaseCache = 2048       
	config.TrieCleanCache = 512       
	config.NoPruning = true
	config.Ethash.CacheDir = filepath.Join(rootDir, geth, "ethash")
	config.Ethash.DatasetDir = filepath.Join(rootDir, geth, "ethash_DatasetDir")
	ethashConfig := config.Ethash

    // New an evm engine
	engine := ethash.New(ethash.Config{
		PowMode:          ethashConfig.PowMode,
		CacheDir:         config.Ethash.CacheDir,
		CachesInMem:      ethashConfig.CachesInMem,
		CachesOnDisk:     ethashConfig.CachesOnDisk,
		CachesLockMmap:   ethashConfig.CachesLockMmap,
		DatasetDir:       ethashConfig.DatasetDir,
		DatasetsInMem:    ethashConfig.DatasetsInMem,
		DatasetsOnDisk:   ethashConfig.DatasetsOnDisk,
		DatasetsLockMmap: ethashConfig.DatasetsLockMmap,
		NotifyFull:       ethashConfig.NotifyFull,
	}, config.Miner.Notify, config.Miner.Noverify)
	engine.SetThreads(-1) // Disable CPU mining

    // Initialize evm config
	vmConfig := vm.Config{
		EnablePreimageRecording: config.EnablePreimageRecording,
	}

	cacheConfig := &core.CacheConfig{
		TrieCleanLimit:      config.TrieCleanCache,
		TrieCleanJournal:    filepath.Join(rootDir, geth, "triecache"),
		TrieCleanRejournal:  config.TrieCleanCacheRejournal,
		TrieCleanNoPrefetch: config.NoPrefetch,
		TrieDirtyLimit:      config.TrieDirtyCache,
		TrieDirtyDisabled:   config.NoPruning,
		TrieTimeLimit:       config.TrieTimeout,
		SnapshotLimit:       config.SnapshotCache,
		Preimages:           config.Preimages,
	}

    // Initialize the BlochChain
	blockchain, err := core.NewBlockChain(chainDb, cacheConfig, chainConfig, engine, vmConfig, nil, &config.TxLookupLimit)
	if err != nil {
		return err
	}

    // Read blocks from the local database, then insert them into the blockchain
	for blocks := range blocksCh {
		_, err := blockchain.InsertChain(blocks)
		if err != nil {
			return err
		}
	}

	return nil

> INFO [12-03|20:10:00.144] Allocated cache and file handles         database=D:\ethereum-data\database\block cache=16.00MiB handles=16 readonly=true
> INFO [12-03|20:10:01.937] Allocated cache and file handles         database=D:\ethereum-data\geth\block            cache=1024.00MiB handles=64
> INFO [12-03|20:10:18.548] Disk storage enabled for ethash caches   dir=D:\ethereum-data\geth\ethash count=15
> INFO [12-03|20:10:18.548] Disk storage enabled for ethash DAGs     dir=D:\ethereum-data\geth\ethash_DatasetDir count=10
> INFO [12-03|20:10:19.407] Loaded most recent local header          number=8,262,798 hash=11a784..b155b1 td=11,263,920,799,902,470,277,371 age=2y4mo2w
> INFO [12-03|20:10:19.410] Loaded most recent local full block      number=8,262,818 hash=abceba..a6e6b3 td=11,263,964,860,786,644,365,862 age=2y4mo2w
> INFO [12-03|20:10:19.410] Loaded most recent local fast block      number=8,262,818 hash=abceba..a6e6b3 td=11,263,964,860,786,644,365,862 age=2y4mo2w
> INFO [12-03|20:10:19.792] Skip duplicated bad block                number=8,262,819 hash=1bdbbd..3c22fd
> ERROR[12-03|20:10:19.808]
> ########## BAD BLOCK #########
> Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Engine: ethash}
> 
> Number: 8262819
> Hash: 0x1bdbbded4f50d074bef4683da452b5ed06a22caa00cc219dd6078690263c22fd
>         0: cumulative: 21000 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x9043ad8ae274b8ade7854c71d03c053bfbfbfd290b5c9c4076cf54ae67ce5962 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:
>         ...
>         361: cumulative: 7815754 gas: 55231 contract: 0x0000000000000000000000000000000000000000 status: 0 tx: 0xb4acf2df75e7e798a86e9bd9874eb1bddd8f45e1a5618baad979d86d3083e86a logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:
>         ...
>         366: cumulative: 7979332 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x7d93afc481408aac39c3b8c7e8519a4657ffb568ce17c3d42705ac5d5bc61146 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:
>
>
> Error: invalid gas used (remote: 7979005 local: 7979332)
> ##############################

**Comment by TonyHzr** [comment]
> I assume geth reported this as a bad block? Can you please post more logs surrounding the error and also the startup logs? specifically if there were unclean shutdowns

Thanks for your reply, I added some information above

**Comment by holiman** [comment]
Normally, one could do somethink like this via `geth import`. which can take a bunch of blocks in rlp-form (just a dump of the rlp block, one after the other), instead of doing it programmatically, as you have done. 
The way you have done it, it's a bit hard to know whether you have handled the service shutdown correctly. When geth shuts down, there are a sequence of events that need to be performed, which we handle via deferred methods. If you have not followed the same sequence, it's fully possible that one of your previous shutdowns did not properly persist some of the trie data, leading to missing trie data, and finally to a bad block. 

But it's a bit hard to say for sure.

**Comment by TonyHzr** [comment]
> Normally, one could do somethink like this via `geth import`. which can take a bunch of blocks in rlp-form (just a dump of the rlp block, one after the other), instead of doing it programmatically, as you have done. The way you have done it, it's a bit hard to know whether you have handled the service shutdown correctly. When geth shuts down, there are a sequence of events that need to be performed, which we handle via deferred methods. If you have not followed the same sequence, it's fully possible that one of your previous shutdowns did not properly persist some of the trie data, leading to missing trie data, and finally to a bad block.
> 
> But it's a bit hard to say for sure.

Thank you for your reply.

I didn’t know about this feature `geth import` before, maybe I should give it a try.

But, is there a way to detect what trie data I’m missing now? It’s a waste of time to re-execute.

**Comment by holiman** [comment]
> But, is there a way to detect what trie data I’m missing now? It’s a waste of time to re-execute.

Yes, there is. Check out `geth snapshot traverse-state -h` 
```
traverse-state [command options] <root>

geth snapshot traverse-state <state-root>
will traverse the whole state from the given state root and will abort if any
referenced trie node or contract code is missing. This command can be used for
state integrity verification. The default checking target is the HEAD state.

It's also usable without snapshot enabled.

```

**Comment by holiman** [comment]
That will only find where the error is, it won't actually fix it for you. But theoretically it's pretty easy to fix with the new db commands -- one node could export the exact data you need, and you could import it. I might be able to help out with that, to try out the UX around the new exporters/importers a bit

**Comment by TonyHzr** [comment]
> That will only find where the error is, it won't actually fix it for you. But theoretically it's pretty easy to fix with the new db commands -- one node could export the exact data you need, and you could import it. I might be able to help out with that, to try out the UX around the new exporters/importers a bit

Thank you again. That's great news for me, I will try it now.

**Comment by MoGuGuai-hzr** [comment]
Hi, brother. I seem to locate this problem, but I don't know how and why it happened.

The error occurred on transaction `0xb4acf2df75e7e798a86e9bd9874eb1bddd8f45e1a5618baad979d86d3083e86a` in block `8262819`.

I found that this transaction uses `STATICCALL` to send some data to address `0x0000000000000000000000000000000000000001`, that is, the method `ecrecover` is called.

This method returns different results in different systems. 

In ubuntu, its results are as follows, which is exactly what we expect and consistent with the current results on Ethereum.
> ecrecover input: [187 96 219 168 155 3 169 4 121 177 81 151 52 171 4 70 63 107 57 13 239 31 227 245 37 152 194 136 190 12 160 188 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 28 175 213 44 44 157 70 98 170 123 13 188 240 91 160 47 101 215 183 32 89 157 103 110 15 33 90 222 137 70 187 65 238 26 171 201 10 15 215 197 247 232 145 134 173 164 40 30 36 208 100 103 222 129 78 22 77 104 166 49 40 31 50 80 147]
> ecrecover return: []
> ecrecover err: \<nil\>

Because some errors occurred in the process of executing method `ecrecover`: the return of the function `crypto.Ecrecover` is `recovery failed`.

But in windows, its results are as follows.
> ecrecover input: [187 96 219 168 155 3 169 4 121 177 81 151 52 171 4 70 63 107 57 13 239 31 227 245 37 152 194 136 190 12 160 188 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 28 175 213 44 44 157 70 98 170 123 13 188 240 91 160 47 101 215 183 32 89 157 103 110 15 33 90 222 137 70 187 65 238 26 171 201 10 15 215 197 247 232 145 134 173 164 40 30 36 208 100 103 222 129 78 22 77 104 166 49 40 31 50 80 147]
> ecrecover return: [0 0 0 0 0 0 0 0 0 0 0 0 63 23 241 150 43 54 228 145 179 10 64 178 64 88 73 229 151 186 95 181]
> ecrecover err: \<nil\>

No error occurred.

I noticed that CGO is used in the method `crypto.Ecrecover`, but I am not sure if the problem is caused by it.

And I must confess that the executable program in windows is obtained by using the following cross-compilation command on ubuntu, which may be the cause of the inconsistency:
> GOOS=windows GOARCH=amd64 env GO111MODULE=on go build -o ./build/bin ./my-geth

**Comment by MoGuGuai-hzr** [comment]
> @MoGuGuai-hzr could you please test #24387 ?

I seem to end up with it. This inconsistency error comes from a stupid operation of mine: when compiling the windows version, I used cross-compile, but did not specify the correct cross-compiler. The error no longer appears after using the cross compiler.

Thank you very much for your kind help.
