### ISSUE TITLE
online trie pruning

### ISSUE THREAD

**Issue by sbarratt** [ethereum/go-ethereum#24033]
# Rationale

currently pruning has to be done offline due to a file system lock on the database. the main source of non-ancient storage growth appears to be dangling or useless trie nodes. is there any way to delete those online as they become irrelevant?

# Implementation

i think some general discussion about the idea can spawn an implementation

**Comment by karalabe** [comment]
It's something actively worked on since forever, also by Gary who has open PRs about it. Closing this issue as it doesn't feel productive.
