### ISSUE TITLE
getting offline error in faucet

### ISSUE THREAD

**Issue by FadeXaltair** [ethereum/go-ethereum#24049]
I need some ether for testing m smart contracts 
id : https://twitter.com/HiteshRana0508/status/1466776221300113408

**Comment by BrainCoder** [comment]
This project does not maintain the faucet

have 0.25rEth anyways.

#close

**Comment by wolasss** [comment]
This faucet is constantly down. Why is it so hard to keep it online and what can we do as a community to help?

**Comment by ccolorado** [comment]
Any idea when the faucet can be operational? the app seems to have 8 days long queue ATM. 
Regards. 
We really need to refill our test env
Thanks in advance.

**Comment by dlarchikov** [comment]
> Any idea when the faucet can be operational? the app seems to have 8 days long queue ATM.
> Regards.
> We really need to refill our test env
> Thanks in advance.

Private chain containts single node.

**Comment by ccolorado** [comment]
> > Any idea when the faucet can be operational? the app seems to have 8 days long queue ATM.
> > Regards.
> > We really need to refill our test env
> > Thanks in advance.
> 
> Private chain contains a single node.

Thanks for the suggestion, already tried that, but it's not enough, chain needs to be accessible for other team members for FE integration. Integrate with a few AMM protocols deployed on testnet, and etherscan support.

**Comment by dlarchikov** [comment]
> > > Any idea when the faucet can be operational? the app seems to have 8 days long queue ATM.
> > > Regards.
> > > We really need to refill our test env
> > > Thanks in advance.
> > 
> > 
> > Private chain contains a single node.
> 
> Thanks for the suggestion, already tried that, but it's not enough, chain needs to be accessible for other team members for FE integration. Integrate with a few AMM protocols deployed on testnet, and etherscan support.

You can to try other testnets. Kovan, goerli. 
Goerly has [explorer](https://goerli.etherscan.io/) and [faucet](https://faucet.goerli.mudit.blog/)

**Comment by lioncho** [comment]
I need some rETH, It would be so appreciated who would send me.
https://twitter.com/chowin21/status/1478177026335191042

**Comment by ligi** [comment]
You can get some rinkeby from here: https://fauceth.komputing.org/?chain=4

**Comment by ligi** [comment]
also currently the rinkeby.io faucet seems to work
