### ISSUE TITLE
extra copy in trie hasher? not sure

### ISSUE THREAD

**Issue by elee1766** [ethereum/go-ethereum#24053]
hi ! i was reading this function and saw that there were two copies at the top 

https://github.com/ethereum/go-ethereum/blob/93f196c4b052983dd89d8ba749dcdc98a80cf69c/trie/hasher.go#L119-L122

i see that this function is currently being used in two places

https://github.com/ethereum/go-ethereum/blob/93f196c4b052983dd89d8ba749dcdc98a80cf69c/trie/hasher.go#L86-L94

and 

https://github.com/ethereum/go-ethereum/blob/93f196c4b052983dd89d8ba749dcdc98a80cf69c/trie/hasher.go#L200-L203

in neither of these cases, n seems to be used. can't we avoid a copy if we simply use n for the "cached" value? (cached = n, or just replacing variable altogether) it would be faster and also get rid of some gcs. in fact, in the second call the cached value isnt even used, so is it not possible in that case to avoid the copy all together?

i tried editing and removing the copies and the tests seemed to pass + benchmarks made some sense, but i'm not super familiar with the whole codebase yet so i could be just mistaken.

thanks!

**Comment by ligi** [comment]
Thanks for looking into it - there might be the option to save a copy here - but it will most likely not make a big impact and is so not really worth doing.
