### ISSUE TITLE
EF security/bounty PGP key has expired over 2 years ago

### ISSUE THREAD

**Issue by acud** [ethereum/go-ethereum#24055]
Hello,
I wanted to submit a vulnerability report and have inspected the `security policy` page at https://github.com/ethereum/go-ethereum/security/policy. The PGP keys published there have expired over two years ago:
```
pub   rsa4096 2016-11-11 [SC] [expired: 2019-11-11]
      AE96ED969E479B0084F3E17FE88D3334FA5F6A0A
uid           [ expired] Ethereum Foundation Security Team <security@ethereum.org>
uid           [ expired] Ethereum Foundation Bug Bounty <bounty@ethereum.org>
```

Are there any plans to renew the keys? Are vulnerabilities expected to be submitted in cleartext?

Thanks!

**Comment by holiman** [comment]
Yes, we'll fix that. In the meantime, it's perfectly fine to use the key.

**Comment by holiman** [comment]
Seems I already fixed it back when it expired, does this work for you? http://pgp.mit.edu/pks/lookup?op=vindex&search=0xE88D3334FA5F6A0A and in particular http://pgp.mit.edu/pks/lookup?op=get&search=0xE88D3334FA5F6A0A ?


If so, I think we just need to update the blob data on the policy page and bounty.ethereum.org.

**Comment by acud** [comment]
Thanks Martin, that worked. Updating the blobs would be nice, thanks!

**Comment by holiman** [comment]
Should be updated now!
