### ISSUE TITLE
geth Mining new fast speed

### ISSUE THREAD

**Issue by amengCow** [ethereum/go-ethereum#24052]
Hello, my dear, my geth client monitors the new block synchronization state. The timestamp of the block that is monitored is always about 3-40 seconds away from the timestamp of my local machine. Is this normal? If you want to mine The block speed is faster. What should I do? Should I upgrade my server configuration?
(I am using web3.js subscribe newBlockHeaders)
![image](https://user-images.githubusercontent.com/56863320/144714864-1cd62695-ac6e-4a04-8350-6d7291d4f8dd.png)

**Comment by YOUSU198** [comment]
What should we do, does a withdrawal exist

في السبت، ٤ كانون الأول ٢٠٢١ ٦:٢٣ م 尤元蒙 ***@***.***> كتب:

**Comment by holiman** [comment]
> Is this normal?

Yes, the timestamp is set when the miner _starts_ working on mining the block, so on average the time is 1 blocktime behind the wall clock once the solution is found.

**Comment by amengCow** [comment]
> 是的，时间戳是在矿工_开始_挖掘区块时设置的，因此一旦找到解决方案，平均时间比挂钟晚 1 个区块时间。

Goods, if you increase the synchronization speed, is it useful to increase the server configuration and set the peercount?
