### ISSUE TITLE
geth unable to sync pass block 13741224

### ISSUE THREAD

**Issue by tfwyimti** [ethereum/go-ethereum#24054]
#### System information

Geth version: instance=Geth/v1.10.13-stable-7a0c19f8/windows-amd64/go1.17.2
OS & Version: Windows

#### Issue
when trying to sync it gets to this point and it has a local hash that doesn't match the block hash so it "denies the block" and never gets past it. Drops the peer and keeps going....
I searched here 
https://etherscan.io/block/13741224
and it has a block with "unconventional ordering" but the hash and the merkle root that it receives seems to be valid, I don't know how it got to the local hash (a6321ad355c8dedbceb8ea274a2b421ae3f9478010c4aa85b0a198addffd08c9)

###log:
```
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Engine: ethash}

Number: 13741224
Hash: 0x26630d46e6b919f4b8a0839683d4b1b5e1e03523e224e002ccaabd3b3b624e11

(bunch of transactions in the block....)

Error: invalid merkle root (remote: 9427569c21c5df73d13056fe4b29ce9ccc4fb5590ba94c97e82233e66895c242 local: a6321ad355c8dedbceb8ea274a2b421ae3f9478010c4aa85b0a198addffd08c9)
##############################

```

**Comment by rjl493456442** [comment]
The database of your node might be fired already. Can you try `--snapshot=false` to disable snapshot first? Then it will use trie as the state accessor fallback. Or it's possible that both snapshot and trie are fired then you need to resync the node.

**Comment by holiman** [comment]
Assuming that this was a local problem and has since been resolved
