### ISSUE TITLE
需要帮助搭建该程序ETH/ETC矿池的联系微信:xserverx

### ISSUE THREAD

**Issue by bxstar** [ethereum/go-ethereum#24082]
有问题的，我可以出售我的时间，来协助您解决问题 。可以尝试联系我
If there is any problem, I can sell my time to help you solve the problem. You can try to contact me
wechat: xserverx
email: 276368949@qq.com
qq: 276368949

**Comment by Lucid36** [comment]
> 有问题的，我可以出售我的时间，来协助您解决问题 。可以尝试联系我
> If there is any problem, I can sell my time to help you solve the problem. You can try to contact me
> wechat: xserverx
> email: 276368949@qq.com
> qq: 276368949
