### ISSUE TITLE
statement about sync mode is unclear in README.md

### ISSUE THREAD

**Issue by james-chi** [ethereum/go-ethereum#24088]
From 'geth --help' output, there are four sync modes. And "fast" and "snap" are two of them:
> --syncmode value     ------     Blockchain sync mode ("fast", "full", "snap" or "light") (default: snap)

In the middle of README.md document,

>  so we can fast-sync quickly to the current state of the network. To do so:
> $ geth console

It means, 'geth console' will start fast-sync mode, I think.
And then very next statement confuses me.

> This command will:
> Start geth in snap sync mode 

Which one is correct? Fast or snap?

**Comment by fjl** [comment]
`snap` is correct.
