### ISSUE TITLE
value to contract invalid jump destination

### ISSUE THREAD

**Issue by feiyiban** [ethereum/go-ethereum#24094]
why i set value is not nil when "evm.Call" to report invalid jump destination;but i set value is zero "evm.Call" 
correct

**Comment by s1na** [comment]
Can you please provide more details? Are you referring to `eth_call` the rpc method or are you directly importing and calling `core/vm/evm.go:EVM.Call(...)`? Providing the transaction details and the non-nil `value` you pass in which results in `invalid jump destination` would be helpful for reproducing the issue.

**Comment by feiyiban** [comment]
xfsgo.StateTransition {gp: *xfsgo.GasPool {neg: false, abs: math/big.nat len: 1, cap: 1, [18446744073707051615]}, msg: xfsgo.Message(xfsgo.MessageImp) {to: xfsgo/common.Address [0,0,0,0,0,78,133,109,13,10,230,159,205,111,175,54,134,212,85,46,204,92,219,110,203], from: xfsgo/common.Address [1,29,132,203,246,208,84,174,187,218,128,212,191,96,69,77,230,57,224,32,69,0,1,246,123], nonce: 0, amount: *(*"math/big.Int")(0xc020fa5160), gasLimit: 2500000, gasPrice: *(*"math/big.Int")(0xc020fa50c0), isFake: true, data: []uint8 len: 68, cap: 144, [22,92,74,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...+4 more]}, gas: 2474344, gasPrice: *math/big.Int {neg: false, abs: math/big.nat len: 1, cap: 1, [10000000000]}, gasFeeCap: *math/big.Int nil, gasTipCap: *math/big.Int nil, initialGas: 2500000, value: *math/big.Int {neg: false, abs: math/big.nat len: 1, cap: 1, [2]}, data: []uint8 len: 68, cap: 144, [22,92,74,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...+4 more], state: xfsgo/vm.StateDB(*xfsgo.StateTree) *{root: []uint8 len: 32, cap: 32, [233,52,145,57,29,13,125,19,169,83,176,64,58,218,104,135,126,38,146,45,45,178,85,199,93,253,196,107,128,197,216,100], treeDB: xfsgo/storage/badger.IStorage(*xfsgo/storage/badger.Storage) ..., merkleTree: *(*"xfsgo/avlmerkle.Tree")(0xc017556420), objs: map[xfsgo/common.Address]*xfsgo.StateObj [...]}, evm: *xfsgo/vm.EVM {Context: (*"xfsgo/vm.BlockContext")(0xc000344a80), TxContext: (*"xfsgo/vm.TxContext")(0xc000344ae0), StateDB: xfsgo/vm.StateDB(*xfsgo.StateTree) ..., depth: 0, chainConfig: *xfsgo/params.ChainConfig nil, chainRules: (*"xfsgo/params.Rules")(0xc000344b28), Config: (*"xfsgo/vm.Config")(0xc000344b40), interpreter: *(*"xfsgo/vm.EVMInterpreter")(0xc0001ae400), abort: 0, callGasTemp: 0}}

**Comment by feiyiban** [comment]
I use it directly like eth_ Call instead of tx，then set value = 0 is ok，but value is not nil fail

**Comment by holiman** [comment]
`xfsgo.StateTransition ` does not look like our code. 
If you want us to answer questions, you need to provide more info about exactly what you are doing. Which typically would include either the exact RPC call parameters, _or_ example of code where you invoke go-ethereum as a library. 

I don't even know what that thing you pasted is -- I'm guessing it's debug output from some random points in the codebase?

**Comment by holiman** [comment]
Maybe you should file a ticket here instead https://github.com/xfs-network/xfsgo ?
