### ISSUE TITLE
Head state missing, repairing in go-eth 1.10.13 start up? 

### ISSUE THREAD

**Issue by keeper586** [ethereum/go-ethereum#24096]
After apply go-eth 1.10.13, it halts in the following line for several hours, is there any method to accelerate the start up process?

![image](https://user-images.githubusercontent.com/93892681/145680327-28411876-6c17-4758-8633-e52f7b8c928b.png)

**Comment by keeper586** [comment]
after about 10 hours waiting，it begins sync block。

**Comment by Lucid36** [comment]
> After apply go-eth 1.10.13, it halts in the following line for several hours, is there any method to accelerate the start up process?
> 
> ![image](https://user-images.githubusercontent.com/93892681/145680327-28411876-6c17-4758-8633-e52f7b8c928b.png)
>
