### ISSUE TITLE
tracing: memory output erroneously reports post-op memory size

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereum/go-ethereum#24109]
# Rationale

Currently, if you try to trace a transaction which MSTOREs something at an offset previously not written to, then the `debug_traceTransaction` will pad the memory with zeros. In the trace, usually the reported values are what happens *before* running the opcode. For instance, if the first opcode ran is a PUSH opcode, then the reported stack is empty. The next opcode, then the stack will have the single item just pushed on the stack. It is therefore strange that the memory is expanded before running the MSTORE opcode and it also does not reflect reality: if the current frame does not have enough gas to pay for the (quadratic) expansion gas costs of memory, then the memory is never expanded in the first place and the entire frame goes out-of-gas.

The current implementation violates [EIP-3155](https://eips.ethereum.org/EIPS/eip-3155), in particular this line: 

"The `stack`, `memory` and `memSize` are the values before *execution* of the op"

We found this behavior in an end-to-end test in [EthereumJS](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1553).

# Implementation

Report memory without expanding it in a trace in case of a `MSTORE` or `MSTORE8` opcode.

**Comment by holgerd77** [comment]
Will "cc" me in here. 🙂

**Comment by holiman** [comment]
With this diff 
```diff
diff --git a/core/vm/interpreter.go b/core/vm/interpreter.go
index 1660e3ce0f..5836d1cfba 100644
--- a/core/vm/interpreter.go
+++ b/core/vm/interpreter.go
@@ -221,14 +221,21 @@ func (in *EVMInterpreter) Run(contract *Contract, input []byte, readOnly bool) (
 			if err != nil || !contract.UseGas(dynamicCost) {
 				return nil, ErrOutOfGas
 			}
+			// Do the trace before memory is expanded
+			if in.cfg.Debug {
+				in.cfg.Tracer.CaptureState(pc, op, gasCopy, cost, callContext, in.returnData, in.evm.depth, err)
+				logged = true
+			}
 			if memorySize > 0 {
 				mem.Resize(memorySize)
 			}
+		} else {
+			if in.cfg.Debug {
+				in.cfg.Tracer.CaptureState(pc, op, gasCopy, cost, callContext, in.returnData, in.evm.depth, err)
+				logged = true
+			}
 		}
-		if in.cfg.Debug {
-			in.cfg.Tracer.CaptureState(pc, op, gasCopy, cost, callContext, in.returnData, in.evm.depth, err)
-			logged = true
-		}
+
 		// execute the operation
 		res, err = operation.execute(&pc, in, callContext)
 		if err != nil {
```
We get this result: 
```
$ go run . --code 60406040526001 --json run 
{"pc":0,"op":96,"gas":"0x2540be400","gasCost":"0x3","memory":"0x","memSize":0,"stack":[],"returnData":"0x","depth":1,"refund":0,"opName":"PUSH1","error":""}
{"pc":2,"op":96,"gas":"0x2540be3fd","gasCost":"0x3","memory":"0x","memSize":0,"stack":["0x40"],"returnData":"0x","depth":1,"refund":0,"opName":"PUSH1","error":""}
{"pc":4,"op":82,"gas":"0x2540be3fa","gasCost":"0xc","memory":"0x","memSize":0,"stack":["0x40","0x40"],"returnData":"0x","depth":1,"refund":0,"opName":"MSTORE","error":""}
{"pc":5,"op":96,"gas":"0x2540be3ee","gasCost":"0x3","memory":"0x","memSize":96,"stack":[],"returnData":"0x","depth":1,"refund":0,"opName":"PUSH1","error":""}
{"pc":7,"op":0,"gas":"0x2540be3eb","gasCost":"0x0","memory":"0x","memSize":96,"stack":["0x1"],"returnData":"0x","depth":1,"refund":0,"opName":"STOP","error":""}
```
Which on `master` returns this: 
```
$ go run . --code 60406040526001 --json run 
{"pc":0,"op":96,"gas":"0x2540be400","gasCost":"0x3","memory":"0x","memSize":0,"stack":[],"returnData":"0x","depth":1,"refund":0,"opName":"PUSH1","error":""}
{"pc":2,"op":96,"gas":"0x2540be3fd","gasCost":"0x3","memory":"0x","memSize":0,"stack":["0x40"],"returnData":"0x","depth":1,"refund":0,"opName":"PUSH1","error":""}
{"pc":4,"op":82,"gas":"0x2540be3fa","gasCost":"0xc","memory":"0x","memSize":96,"stack":["0x40","0x40"],"returnData":"0x","depth":1,"refund":0,"opName":"MSTORE","error":""}
{"pc":5,"op":96,"gas":"0x2540be3ee","gasCost":"0x3","memory":"0x","memSize":96,"stack":[],"returnData":"0x","depth":1,"refund":0,"opName":"PUSH1","error":""}
{"pc":7,"op":0,"gas":"0x2540be3eb","gasCost":"0x0","memory":"0x","memSize":96,"stack":["0x1"],"returnData":"0x","depth":1,"refund":0,"opName":"STOP","error":""}
```
Go-evmlab does not care about such a change, since it's not supported by all clients, so it won't cause any problems for that fuzzing-engine. How about your fuzzer, @MariusVanDerWijden ?

**Comment by MariusVanDerWijden** [comment]
Mine doesn't care either, it uses goevmlab to do the post-processing of traces

**Comment by holiman** [comment]
Let's wait and see what comes out of the https://github.com/ethereum/go-ethereum/pull/24113 , doing any change now might just become reverted when that goes in.
