### ISSUE TITLE
Rinkeby faucet offline for a couple of weeks

### ISSUE THREAD

**Issue by ccolorado** [ethereum/go-ethereum#24108]
Have been monitoring the faucet for some test ether for a couple of weeks. Haven't seen the faucet online for a while now. 
Unfortunately we need a whole lot more than the 0.1 eth other faucets give away for our tests and deployments.

**Comment by holiman** [comment]
Duplicate of #24049 (and probably a few more)

**Comment by ccolorado** [comment]
Any word on when the rinkeby faucet be back online?

**Comment by speqtovijay** [comment]
faucet server started but how start faucet web application with the goal of distributing small amounts of Ether in private and test networks please assisist me command?
