### ISSUE TITLE
ubuntu 14.04 and GETH does not find peers

### ISSUE THREAD

**Issue by rawsushi** [ethereum/go-ethereum#2410]
#### System informatio
Ubuntu 14.04 virgin install (to be used only for ETH MINING

Geth version: 
Geth
Version: 1.3.6
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go

Geth does not find peers and shuts down

Tried doing Geth --nat=none

https://gist.github.com/rawsushi/185c9d9ff00a63a3b76d8088021a049c

**Comment by karalabe** [comment]
Please synchronize your OS to an NTP server. Based on the logs your discovery packets are arriving with unexpected timestamps and are being discarded. The develop branch of Geth already warns you of such scenarios but we didn't backport it to stable yet.

**Comment by sujaydutta** [comment]
Check if the double quotes are replaced with smart quotes in the editor. I had similar issues, but after correcting the double quotes in the static-nodes.json, the peer nodes were discovered.

**Comment by wawrzek** [comment]
@karalabe I have similar problem, however my environment is a bit different. I have a private network with following set up

- I start two 'utility' nodes. 
- Manually connect them to each other (admin.addPeer()).
- After that I add public key of both of them to geth starting command on all other nodes (lets call them 'normal nodes') as parameters to the bootnode command line option.
- Start 'normal' nodes.

After that each 'norma;' node see 'utilty'/boot nodes, but not others. I would expect that over time all nodes will find each others via gossiping with 'utility' nodes.

ntpd is started on each machine, so time  should not be a problem.
