### ISSUE TITLE
Does Unsubscribe() close the heads channel passed when a subscription is created?

### ISSUE THREAD

**Issue by pinebit** [ethereum/go-ethereum#24116]
The interface is unclear about whether the subscription channel is being closed on Unsubscribe or not.
When I add an explicit `close(..)` right after `Unsubscribe()` it does panic, so I concluded the channel is being closed.
I would suggest to make this clear in the interface not just about the error channel, but also about the channel passed when a subscription is being created.

```
type Subscription interface {
	Err() <-chan error // returns the error channel
	Unsubscribe()      // cancels sending of events, closing the error channel
}
```

Thank you!

**Comment by ligi** [comment]
Can you let us know what panic you are getting exactly?

**Comment by holiman** [comment]
`Unsubscribe` does not `close` the channel, and neither should anything be sent over the channel after `Unsubscribe` -- so the scenario you describe is a bug. Could you provide some example code which reproduces the problem?

**Comment by pinebit** [comment]
Thank you for the quick response!
1. Create a channel that will be receiving heads: `headsCh := make(chan *eth.Heads)`
2. Subscribe to receive heads using this function:
```
// EthSubscribe registers a subscripion under the "eth" namespace.
func (c *Client) EthSubscribe(ctx context.Context, channel interface{}, args ...interface{}) (*ClientSubscription, error) {
	return c.Subscribe(ctx, "eth", channel, args...)
}

// here we are passing the channel we created in step 1
subscription, err := client.EthSubscribe(ctx, headsCh)
```
3. Call Unsubscribe(): `subscription.Unsubscribe()`
4. And try closing the channel `headsCh` right after `Unsubscribe()`
5. "panic: close on closed channel"

Usually the channel has to be closed by the producer, but it is fine if not - just need to clarify this in `EthSubscribe` contract, e.g. make it clear that it is closing or not closing the `channel` on Unsubscribe.

Now I started thinking there may be a bug in my code... However, what I am looking for is a confirmation and/or update the comment (function contract) to make this matter clear. 

Thank you very much!

**Comment by MariusVanDerWijden** [comment]
Looking through the code, there is no way that `Unsubscribe` will close the channel.
I set up a subscription like this, and it worked flawlessly. Did you correctly create the `headsCH` ? You said that it might be a bug in your code, so I'll close this for now. Feel free to reopen if the issue still persists

```go
import (
	"context"
	"testing"

	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/ethclient"
)

func getRealBackend() *ethclient.Client {
	cl, err := ethclient.Dial("ws://127.0.0.1:8546")
	if err != nil {
		panic(err)
	}
	return cl
}

func TestSubscribe(t *testing.T) {
	backend := getRealBackend()
	ch := make(chan *types.Header)
	sub, err := backend.SubscribeNewHead(context.Background(), ch)
	if err != nil {
		panic(err)
	}
	sub.Unsubscribe()
	close(ch)
}
```
