### ISSUE TITLE
Switch gcmode to archive after sync from Snap

### ISSUE THREAD

**Issue by radian-rgc** [ethereum/go-ethereum#24115]
Before i used gcmode full but now i want to switch it to archive, but i know i can't access to oldest data (a specific block).

For access to all blocks, i must Sync From Genesis Block ? if yes, can sync Geth via Snap ?

Thanks

**Comment by holiman** [comment]
For access to all _state_ belonging to old blocks, yes, you need to have had it running in `gcmode=archive` to have that state immediately accessible. 
If you ran a full-sync without specifying `gcmode=archive`, you can still obtain the state, by recomputing it from an earlier point (geth flushes the state every 2 hours of processing time). That's what the `reexec` parameter in the tracing configs it used for. 
If you ran a fast/snap-sync, you cannot obtain the state for any blocks prior to the pivot point. 

It's fine to stop geth, restart with `gcmode=archive`, and from then on it will not do any in-memory state pruning,  just flush every state to disk. 

If you want to know more about what blocks you have state for, you can use `debug.getAccessibleState(<from>,<to>)`. For example, to check the latest block you have state (on disk) for : `debug.getAccessibleState("latest", 0)`, and to check the earliest (ignore genesis): `debug.getAccessibleState(0, "latest")`

**Comment by radian-rgc** [comment]
Thanks @holiman , 
I ran a fast sync and all blocks synced by `gcmode=full`, and if now i add the `gcmode=archive`, just syncing the new blocks via `gcmode=archive`. but i want to sync all old blocks (or part of them. ex: last 2mil blocks.).

and also i use `debug.getAccessibleState(0, "latest")` but i get the below error:

`TypeError: Object has no member 'getAccessibleState'`
