### ISSUE TITLE
PendingCallContract no effect

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#24121]
## env

ropsten testnet

## test contract

```sol
//SPDX-License-Identifier: MIT
pragma solidity 0.8.4;

contract Vault {
    receive() external payable {
    }

    function ethBalance()external view returns (uint balance){
        return address(this).balance;
    }
}
```

## test process

step1: send 1 wei to contract, named it `tx1`
step2: sleep 1 second (but `tx1` is not mined yet)
step3: while `tx1` is still in pending status, use `ethBalance()`  with `bind.CallOpts{Pending: true}` to call, get the pending balance.

expected: `ethBalance()` result 1 wei
actually: result 0 wei

so if it's 0 wei it makes no difference with `bind.CallOpts{Pending: false}` to call

the related code is at https://github.com/ethereum/go-ethereum/blob/0ba0b81e54483978ab823665afb627ab4999db06/accounts/abi/bind/base.go#L168

**Comment by huahuayu** [comment]
hi @MariusVanDerWijden , have you try it?

**Comment by holiman** [comment]
The concept of the 'pending state' is always a bit hazy and undefined. Geth never did maintain a full post-state on "applying all pending transactions", it was always "post-state of applying roughly a block's worth of the best transactions available". 
Nowadays we only do it on demand. It's very much a YMMV type of feature. If you don't see a transaction? Well, that happens. Sorry

**Comment by holiman** [comment]
Yeah and sorry for taking so long to respond :)
