### ISSUE TITLE
Why the blockInfo of  miner was 0x00000...

### ISSUE THREAD

**Issue by fenQY** [ethereum/go-ethereum#24133]
Q:    when I run the geth with POA mode .    the blockInfo of miner was 0x0.

command:  
`nohup geth --datadir /www/blockchain/poa/node1 --networkid 1549  --syncmode full --gcmode archive --http --http.vhosts='*' --http.addr '0.0.0.0' --http.port 8545 --http.api 'net,debug,eth,web3,txpool,admin' --http.corsdomain '*' --ws --ws.addr '0.0.0.0' --ws.port 8546 --ws.api 'net,debug,eth,web3,txpool,admin' --ws.origins '*' --nodiscover --mine --unlock '0x0e14a878eE980ecC945a3128FF187161CC947d76' --password /www/blockchain/poa/.key --allow-insecure-unlock > run.log 2>&1 &`

blockInfo: 
 `{
  difficulty: 2,
  extraData: "0xd883010a0c846765746888676f312e31372e32856c696e7578000000000000004a1b26ca214619fde682731869ca4a52bf93e054f8a91114d314da73ea21ed6b03135ff530597126fd319932e3a69d8afb32c9be4b69809af77efa49a164e9ac01",
  gasLimit: 8000000,
  gasUsed: 0,
  hash: "0x5e844a2a6b241d18030fca56552a4248f82fd9660e34efbb7c5b9919b48a4733",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 707161,
  parentHash: "0x5c2065eec91cde9e9d887efe4cca1cf54b704f334ca5a5160cadc5b944da976b",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 609,
  stateRoot: "0x3c6cbcc06354267f913d1dc49d0c0535a7d32ba4693af21e1a46ebd9a4ec2459",
  timestamp: 1639989177,
  totalDifficulty: 1414323,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
`

**Comment by karalabe** [comment]
It's a `clique` network. That uses the `miner `field for something else. You can retrieve various information with `clique.getSnaphot(block_number)`. The `recents` field will contain the miners who signed the last few blocks.

Alternatively, you can retrieve the RLP encoded header of a block and recover the signature from that (then it doesn't even need to be a block know to the node): `clique.getSigner(debug.getHeaderRlp(block_number))`
