### ISSUE TITLE
Cannot get Ether from rinkeby faucet.

### ISSUE THREAD

**Issue by mgimza** [ethereum/go-ethereum#24137]
#### System information

Windows 10

#### Expected behaviour
The Rinkeby faucet generates the requested ether .

#### Actual behaviour
The Rinkeby facuet DOES NOT generate the requested ether .
Instead it reports the message  "no ethereum address found to fund."

#### Steps to reproduce the behaviour
1. Go to the URL https://www.rinkeby.io/#faucet
2. Paste in the text field    https://www.facebook.com/marek.gimza/posts/10159737912375429
3. Select 3 Ethers / 8 hours 

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by eax** [comment]
Same here for FB
https://www.facebook.com/ekrem.aksoy.798/posts/416711650184381
0xAe631d050B8f75B14357208EfEDC52c1707a2AC3
18.75 for 3 days

**Comment by Legeon** [comment]
If anyone can help by sending some ether for tests, thanks. 0xF46340AB394e040Bad29F0289C1035B9F5cFf6E2

**Comment by makemake-kbo** [comment]
this has nothing to do with geth

**Comment by mgimza** [comment]
Thanks makemake-kbo ....  
I cannot use the geth client as I cannot get any Ether from Rinkeby for testing.
Do you know to which group I need to direct my fault/request ?

**Comment by makemake-kbo** [comment]
> Thanks makemake-kbo ....  
> I cannot use the geth client as I cannot get any Ether from Rinkeby for testing.
> Do you know to which group I need to direct my fault/request ?
> 
> My main reason for placing my fault here:  https://github.com/ethereum/go-ethereum/issues/21166

You should contact the people behind the faucet and report the issue.
In the meantime you could always spin up your own private testnet 😉

**Comment by mgimza** [comment]
U R correct in that this is a rinkeby faucet issue.
I like the idea in running my own private testnet for my own purposes :)
I therefore close this ticket .
