### ISSUE TITLE
Geth node fails often

### ISSUE THREAD

**Issue by Neoblock8** [ethereum/go-ethereum#24130]
Hi,
  Running private geth node in server with 1TB and 16GB RAM. But it will fails often, after restart the block will generate from the beginning. How to overcome this issue?
  
 **Running Commands:**
 ./geth  --datadir data init <path_of_genesis>/genesis.json 
 ./geth --datadir data --networkid 1001  --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api "eth, net, web3, personal, miner, admin, debug" --allow-insecure-unlock --rpc.txfeecap 0 --cache=1024 console

**Comment by fomotrader** [comment]
Can you try to provide some logs, it's a bit hard to figure out what's wrong without seeing the logs. Could be anything
