### ISSUE TITLE
Bash autocompletion for Geth

### ISSUE THREAD

**Issue by willianpaixao** [ethereum/go-ethereum#24145]
# Rationale

### Why should this feature exist?
Geth has a huge number of [commands and options](https://geth.ethereum.org/docs/interface/command-line-options) to be passed. Some commands need arguments and sometimes it's complicated to say which order you need to provide.

A Bash completion script would give hints of what can be expected when pressing TAB.

### What are the use-cases?
Every Geth developer or beginner that often uses Geth's CLI.

# Implementation

Do you have ideas regarding the implementation of this feature?
Two approaches can be taken:

1. A new geth command is created, eg. `geth completion`, that dumps a completion script. When installing Geth, the uses adds `source <(geth completion)` to their `~/.bashrc` or runs `geth completion > /etc/bash_completion.d/geth`.
2. A completion script is written and included in this repository. Then the Geth documentation will guide the user to download the script and place it under ` ~/.bash_completion.d/geth` or `/etc/bash_completion.d/geth`. In this option, no Go source code will be changed.

Are you willing to implement this feature?
Yes.

# References

- [How to create a Bash completion script](https://opensource.com/article/18/3/creating-bash-completion-script)
- [An Introduction to Programmable Completion](https://tldp.org/LDP/abs/html/tabexpansion.html)
- [Programmable Completion Builtins](https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html)

**Comment by edualb** [comment]
I have been working on this Feature Request and I figured out that geth uses this library to manage the geth cli: 

gopkg.in/urfave/cli.v1

This library explains how could we do that with a bash script. I tried it yesterday and worked 🎉 . However it is necessary to run a script depend on your platform:

* Linux / MacOS - https://github.com/urfave/cli/blob/master/autocomplete/bash_autocomplete
* Windows - https://github.com/urfave/cli/blob/master/autocomplete/powershell_autocomplete.ps1

For that, I have been thinking include a tutorial page in `gh-page` explaning how you can configure your autocomplete depend on your platform. What you think guys?

**Comment by ligi** [comment]
I just tried it out on linux with bash and it is actually really nice - thanks for bringing this up!

![image](https://user-images.githubusercontent.com/111600/151687702-9b166c44-b30d-47d1-b4ca-ddd24dd825f0.png)

prepared it with #24313 - but would really appreciate if you do the tutorial as you offered.

**Comment by edualb** [comment]
@ligi Yeah, of course! I have some issues to solve this week but I will be available next week. If someone else would like to implement it this week be free, however, if no one implement it until there, I'll do that 😉

**Comment by ligi** [comment]
@edualb still interested in writing something?

**Comment by edualb** [comment]
@ligi Yeah! I am, but I have faced a problem when I tried to include a new page... I am on my job now and in the end of my shift I will put my issue here... If you can help I would be glad for that 💙

**Comment by ligi** [comment]
ya - LMK what problem you faced and I will try to find a way around it

**Comment by edualb** [comment]
@ligi sorry for my delay 🤐 

I realized that my docker had an old image and my `Bash Autocomplete` tutorial never worked hehe I just purge this image and tried again, everything worked well 🎉 

![image](https://user-images.githubusercontent.com/39157101/154172178-faa1c48f-0405-4e3c-9ee5-ef6678633a5a.png)

**Comment by fjl** [comment]
We now ship bash completions in the Ubuntu package.
