### ISSUE TITLE
Allow state override for debug_traceCall

### ISSUE THREAD

**Issue by alex88** [ethereum/go-ethereum#24149]
# Rationale

Why should this feature exist?
What are the use-cases?

I'm trying to execute a custom contract (that I compile locally) on the latest block.
I'm currently using eth_call, the problem with that is that I get a non very useful `{"code":-32000,"message":"execution reverted"}` error when there's a problem with the contract execution.

It seems there are no logs that can help understand what went wrong so I was hoping that debug_traceCall could lead me to a better error description while trying to achieve what eth_call does, however it doesn't support state overrides.

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

I might give it a try but I need some guidance as I'm not familiar with go nor with the project internals

**Comment by s1na** [comment]
TraceCall does support state overrides even though it's not well documented. E.g.:

`debug.traceCall({from: addr, to: zero, value: '0x1'}, 'latest', {'stateOverrides': {[addr]: {'balance': '0x0'}}})`

Closing the issue. Feel free to re-open if I misunderstood your request.

**Comment by s1na** [comment]
@huahuayu something you can try is simulate a call that transfers some erc20 token and trace it with `{ tracer: 'prestateTracer', tracerConfig: { diffMode: true }}`. Then you will see which storage slots changed.

**Comment by thaarok** [comment]
If you end up here while trying to figure out how to use stateOverride (like me), the required structure of `stateOverrides` is a bit different today:
```
{
  "jsonrpc": "2.0",
  "id": 3,
  "method": "debug_traceCall",
  "params": [
    {
      "to": "0x134e4c207ad5a13549de1ebf8d43c1f49b00ba94",
      "data": "0x4c3617e96f3b4ead9fd7284723ee00682332c467146cafd8c5187686f92be3a6",
    },
    "latest",
    {
      "stateOverrides": {
        "0x134e4c207ad5a13549de1ebf8d43c1f49b00ba94": {
          "nonce": null,
          "code": null,
          "balance": null,
          "state": null,
          "stateDiff": {
            "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc": "0x000000000000000000000000044378356f77650d674d1892f2e41520087ba10d"
          }
        }
      },
      "tracer": "callTracer"
    }
  ]
}
```
