### ISSUE TITLE
Allow GPU workers (EG: ethminer) to report hashrate

### ISSUE THREAD

**Issue by kris-nova** [ethereum/go-ethereum#24156]
# Rationale

Right now `geth` does not offer a hashrate metric for GPU work, only CPU work.

Given the state of ethereum and the mainnet blockchain any CPU work at this point is obsolete. 

Would it be possible to imagine a mechanism in which a subset of GPU miners could report their current hashrate back to a centralized `geth` process?
It would then be possible for `geth` to calculate a hashrate average or subset of hashrate averages over time. (Similar to how `/proc/loadavg` works on a handful of intervals.)

It wouldn't be impossible to build another tool outside the scope of `geth` that would accomplish the same goal. However I do think there is value in using `geth` to track this. I can also see how having miner metrics reported back into the `geth` tool breaks the entire "decentralized" model as this approach would be in favor of centralizing the metrics.

# Implementation

At a glance it seems we would need the following: 

 1. A standardized RPC in which GPU miners could report metrics back to `geth`
 2. Features plumbed through the various miners such as `ethminer` that would concurrently report the metrics over the new RPC.

# Considerations

Right now GPU miners connect to `geth` using [stratum](https://braiins.com/stratum-v2). My research leads me to believe that reporting GPU hashrate over stratum isn't currently supported (Maybe I am wrong? Maybe it should be supported?). 

This assumption is why I believe we would need a new RPC. The implications of this new RPC would be a new outbound connection from each of the miners back to `geth`. The amount of connections and TCP ports could add up quickly. This can be problematic as we learned with Kubernetes and its dependency on `iptables` to manage these bi-directional connections.

**Comment by fjl** [comment]
Hi,

if you see the need to report hashrate to geth, you can do it using the `ethhash_submitHashrate` RPC API method.

Source:

https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/consensus/ethash/api.go#L92

Example:

```
{"jsonrpc":"2.0", "id": 1, "method": "ethash_submitHashrate", "params": ["0xf3f3f3", "0x50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c"]}
```
