### ISSUE TITLE
'fast' mode disappeared

### ISSUE THREAD

**Issue by Detrous** [ethereum/go-ethereum#24155]
#### System information

Geth version: `Geth
Version: 1.10.14-stable
Git Commit: 11a3a35097ec493d71137c9bfa433bceeedff6c0
Architecture: amd64
Go Version: go1.17.5
Operating System: linux
GOPATH=
GOROOT=go`
OS & Version: Linux

#### Expected behaviour

`-syncmode "fast"` will start fast syncing

#### Actual behaviour

Error is indicated that fast mode does not exist

#### Steps to reproduce the behaviour

Run
`geth --snapshot=false --ropsten  --syncmode fast`

#### Backtrace

````
invalid value "fast" for flag -syncmode: unknown sync mode "fast", want "full", "snap" or "light"
````

Geth help

````
geth -h | grep syncmode


  --syncmode value                    Blockchain sync mode ("snap", "full" or "light") (default: snap)
````
When submitting logs: please submit them as text and not screenshots.

**Comment by ligi** [comment]
this is not actually a bug - we dropped `fast` mode - you should use snap now. Any reason you really need `fast`?

**Comment by Detrous** [comment]
I was confused that this option was gone. I didn't find any updates on this in the release notes and documentation, so I thought it was some kind of bug. I'll use the snap, thanks
