### ISSUE TITLE
abigen: using structs (tuple) in function params results Fatal: Failed to generate ABI binding

### ISSUE THREAD

**Issue by aiwowo1** [ethereum/go-ethereum#24154]
#### System information

Geth version: `geth version` 
go version go1.17.3
abigen version 1.10.8-unstable
solc version 0.8.10

OS & Version: Windows/Linux/OSX   
WSL 

Commit hash : (if `develop`)

#### Expected behaviour
it works properly when not using struct as the argument to pass in constructor. Since I need more than16 arguments that I would have "stack too deep" issue. 

#### Actual behaviour
I wrapped those argument as one struct to pass in to the constructor. I use solc 0.8.10 to compile the abi and bin files. 
Fatal: Failed to generate ABI binding: template: :71:120: executing "" at <bindtype .Type $structs>: error calling bindtype: runtime error: invalid memory address or nil pointer dereference

#### Steps to reproduce the behaviour

make a 18 parameters in a struct and use it to pass into the solidity contract constructor 
(example:)
```
            struct Params {
		      address _factory;
		      address _pool;
		      address payable _weth;
		      address  _token0;
		      address  _token1;
		      uint256 _a1;
		      uint256 _a2;
		      uint8  _a3;
		      uint8  _a4; 
		      uint8  _a5;
		      uint8  _a6;     
		      uint128  _a7;
	      }
	
           constructor( Params  memory params) {  }
```

and use solc 0.8.10 to compile the abi and bin.

run abigen.

**Comment by MariusVanDerWijden** [comment]
This should be fixed by this commit https://github.com/ethereum/go-ethereum/commit/b45931cc4ad406cfb0086bc2489e6cfa1a1025b1
Can you try with 1.10.14 again?
