### ISSUE TITLE
block timestamp is before than my transaction create time

### ISSUE THREAD

**Issue by junha-ahn** [ethereum/go-ethereum#24152]
So Simply Our Send workflow like this:
1. DB) inesrt transfer
2. wallet middleware) sign & broadcast (to my local Geth node) transaction 

so (in UTC)
- DB created_at: `15:00:40`
- sign start        : `15:01:04`
- block.timestamp: `14:59:24`

but the `block.timestamp` is `14:59:24` what is wrong? 
- I checked block timestamp in Etherscan and `eth_getBlockByHash` in my Geth node. 

### I read some articles. 

https://ethereum.org/en/whitepaper/#notes
- "Check that the timestamp of the block is greater than that of the previous blockfn. 2 and less than 2 hours into the future"

https://geth.ethereum.org/docs/interface/peer-to-peer
- "Your local time might be incorrect. An accurate clock is required to participate in the Ethereum network. Check your OS for how to resync your clock (example sudo ntpdate -s time.nist.gov) because even 12 seconds too fast can lead to 0 peers."

https://github.com/ethereum/go-ethereum/issues/21784
- "The block timestamp is set when the miner starts working on the block. So it will most likely be pretty close to the time when the previous block was propagated on the network. The header needs to be set before the pow-grinding starts."

### So I think

The network time is correct. and I checked my DB time, that is correct too.

So what is wrong with it? 

"The block timestamp is set when the miner starts working on the block" 
- I think mining starts when all transaction is ready in the miner's node (txpool), so can make `txRoot` and `blockHash`

**Comment by ligi** [comment]
Did this happen once or regularly?

> I think mining starts when all transaction is ready in the miner's node (txpool), so can make txRoot and blockHash

this assumption is wrong - mining starts and transactions can come in in between

**Comment by junha-ahn** [comment]
> Did this happen once or regularly?
I don't know for sure

> this assumption is wrong - mining starts and transactions can come in between

but we have to make `block hash` with a `previous hash` and `transaction root` which is Root of the transaction trie
And then, we can calculate `nonce`. (with `block hash`)

Am I misunderstanding?

**Comment by rjl493456442** [comment]
@junha-ahn we can always switch the mining block in flight, with the *exact same timestamp* but different tx list.

**Comment by holiman** [comment]
The header is created, transactions added (new tx root). 
The mining is started on that hash. 
Then, a bit later on, we do an update, to include new transactions. This changes the tx root hash, but we do _not_ update the header timestamp, because that would force us to reexecute all transactions already there (because the timestamp is obervable from the evm). 
So a block that takes a minute to mine will have a minute old timestamp, even though it can contain a transaction that was created one second before mining completed.

**Comment by holiman** [comment]
1. Yes
2. Yes
3. Yes
4. Yes

> Where did I start thinking wrong?

Your mental model is wrong. You think it's like when searching for a lost glove in the apartment: first you search the living-room, then the hallway, etc, and eventually you'll find it. And in this model, if you switch and suddenly starts looking for a sock instead, then the time spent was wasted, and you start again in the living-room. 

Consider instead that you're on the coast of australia, searching for a particular sort of sand-grain. There's a near-infinite search space, so it doesn't matter if you jump randomly across the coast or if you investigate one square millimeter at a time - it's not like you're accidentally going to pick the same grain for comparison again anyway.

Similarly, if you switch the grain of sand to another one, you don't have to re-examine the particular grains that you have already checked. The search just goes on.
