### ISSUE TITLE
Cryptomonedas estables

### ISSUE THREAD

**Issue by Matistunt** [ethereum/go-ethereum#24150]
Mi propuesta es más que nada crear o desarrollar una criptomoneda estable y así ethereum  revolucionaria el mercado no por ser innovador sino por ser una moneda que cambiaría toda nuestra actual manera de manejo y así no solo conseguiríamos inversores en nuestras moneda volátiles sino también en la moneda estable y si una falla, la otra estará como sustento para la empresa.

**Comment by MariusVanDerWijden** [comment]
This is rhe go-ethereum issue tracker. Please only use this for issues with this codebase
