### ISSUE TITLE
The next docker images will support multiarchitecture ?

### ISSUE THREAD

**Issue by tropicar** [ethereum/go-ethereum#24164]
The last docker version for the version v1.10.14 (https://hub.docker.com/layers/ethereum/client-go/v1.10.14/images/sha256-8228def01f74c11c0b4933759d06525148d85f6195015ceba7eccb5851c5daee?context=explore) does not support multiarchitecture as the previous ones. Will be the same for the next updates or was this an exceptional case?

**Comment by fjl** [comment]
It looks like the docker arm build has failed for the v1.10.14 release. I have restarted this job, let's see if it gets pushed this time.

**Comment by tropicar** [comment]
I have just checked in https://hub.docker.com/r/ethereum/client-go/tags and it seems there was not any update of the ethereum/client-go/v1.10.14 , does it take more time or does the arm build keep falling?
Thank you or the answer by the away

**Comment by fjl** [comment]
The Travis job that was supposed to push the arm image is this one: https://app.travis-ci.com/github/ethereum/go-ethereum/jobs/553379650

The build kept getting restarted yesterday without ever really starting. Seems like a bug in travis-ci.com scheduling. I keep clicking restart and hope it will finally decided to run this job.

**Comment by fjl** [comment]
v1.10.14 arm64 image is now published.
