### ISSUE TITLE
Mount a cloud disk to the GETH node, but the free space of the cloud disk occasionally increases

### ISSUE THREAD

**Issue by xubenao** [ethereum/go-ethereum#24162]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.
![image](https://user-images.githubusercontent.com/96728127/147471625-c41f868e-0b69-4b11-a606-c31d667552c5.png)
The /dev/vdb1 free space in the picture was 65GB last night, but now it is 66GB

**Comment by MariusVanDerWijden** [comment]
Yes, it is possible for geth to delete unused data or compress the database. We delete some old states as well as unindex (deleting the index) for transactions that are older than 1 year. Also leveldb will compress the data every now and then, which will result in less space used on disk
