### ISSUE TITLE
Declaring transaction type doesn't determine actual transaction type

### ISSUE THREAD

**Issue by DockBoss** [ethereum/go-ethereum#24179]
#### System information

Geth version: `1.10.14`
OS & Version: Windows

#### Expected behavior
When using eth_signTransacion or eth_sendTransaction declaring `"type": "0x2"` **should** use a type 2 transaction.

#### Actual behavior
The transaction type is determined by the pricing method. So when `gasPrice` is used the transaction will be a Legacy tx, and when `maxFeePerGas` and `maxPriorityFeePerGas` are used the transaction will be a type 2 tx.

#### Steps to reproduce the behavior
Sign or send a type 2 transaction with `gasPrice` instead of `MFPG` and `MPFPG` and it will actually be a Legacy tx.

**Comment by karalabe** [comment]
This seems to be the specced behavior. There's no such thing as `gasPrice` in typed transaction.

Also, there's no `type` field in the transaction sending API, so that just gets ignored.
