### ISSUE TITLE
Unable to compile geth with command "make all", shows error: command not found on windows 10.

### ISSUE THREAD

**Issue by varunponda** [ethereum/go-ethereum#24177]
I have successfully cloned the geth code from the repo. But I am unable to compile the geth code when I use the command: "make all"
It throws an error "command not found".

`HP@DESKTOP-GHGDISP MINGW64 ~
$ cd ethereum

HP@DESKTOP-GHGDISP MINGW64 ~/ethereum
$ ls
go-ethereum/

HP@DESKTOP-GHGDISP MINGW64 ~/ethereum
$ cd go-ethereum

HP@DESKTOP-GHGDISP MINGW64 ~/ethereum/go-ethereum (master)
$ ls
AUTHORS              build/      eth/           les/         rlp/
COPYING              circle.yml  ethclient/     light/       rpc/
COPYING.LESSER       cmd/        ethdb/         log/         signer/
Dockerfile           common/     ethstats/      metrics/     swarm/
Dockerfile.alltools  consensus/  event/         miner/       tests/
Makefile             console/    go.mod         mobile/      trie/
README.md            contracts/  go.sum         node/
SECURITY.md          core/       graphql/       oss-fuzz.sh
accounts/            crypto/     interfaces.go  p2p/
appveyor.yml         docs/       internal/      params/

HP@DESKTOP-GHGDISP MINGW64 ~/ethereum/go-ethereum (master)
$ make all
bash: make: command not found

HP@DESKTOP-GHGDISP MINGW64 ~/ethereum/go-ethereum (master)
$ make geth
bash: make: command not found

HP@DESKTOP-GHGDISP MINGW64 ~/ethereum/go-ethereum (master)
$
can someone please help me with this issue? Thanks.
`

**Comment by karalabe** [comment]
You don't need make and bash and whatnot on Windows. You can just use Go `go build ./cmd/geth`.
