### ISSUE TITLE
ETH Test fund fuacets are all down

### ISSUE THREAD

**Issue by Misbahu-web** [ethereum/go-ethereum#24183]
Can anyone help with 2 ETH on this test net?
0xd00634B22adAA771Be515527C33049dcfE6D0E3C
I could not find any faucet online.

**Comment by ligi** [comment]
was just sending you 2 - but seems rinkeby has some problem

**Comment by ligi** [comment]
hm - now rinkeby is unstuck - but it seems you have a lot of testnet ether ..

**Comment by OneNOnly1** [comment]
Hey guys, I used this android faucet app myself: https://play.google.com/store/apps/details?id=com.multifaucet.app and it saved me a lot of time, if you have an android device, I recommend you to try it out, hopefully it will cover your needsd

**Comment by kinsley911** [comment]
"0xd00634B22adAA771Be515527C33049dcfE6D0E3C" is hacker's address.
You seem infected by the clipboard hijacking virus.
Check your address carefully.

https://www.cryptoblacklist.io/en/ethereum-blacklist/
