### ISSUE TITLE
What version of golang is currently used to compile geth? Look at 1.15 used by go.mod, but some unit test compilation fails

### ISSUE THREAD

**Issue by cppfuns** [ethereum/go-ethereum#24184]
What version of golang is currently used to compile geth? Look at 1.15 used by go.mod, but some unit test compilation fails

https://github.com/ethereum/go-ethereum/blob/356bbe343a30789e77bb38f25983c8f2f2bfbb47/go.mod#L3

```
surou@bcskill_com go-ethereum % go test -v ./internal/cmdtest/test_cmd.go
go: downloading gotest.tools v2.2.0+incompatible
# command-line-arguments
internal/cmdtest/test_cmd.go:124:39: undefined: io.ReadAll
```

https://github.com/golang/go/issues/44568

**Comment by ligi** [comment]
1.16 and 1.17 are used - see https://github.com/ethereum/go-ethereum/blob/master/.travis.yml

**Comment by marshalys** [comment]
why go.mod version not change to 1.16 or 1.17?
