### ISSUE TITLE
why i  use web3j  rpc very slowly

### ISSUE THREAD

**Issue by lichegn** [ethereum/go-ethereum#24187]
geth version 1.10.14-stable-11a3a350

geth --syncmode=light --datadir=/mnt/data/.ethereum --cache=1024 --http --http.addr=0.0.0.0 --http.port=9999--port=10001 --http.corsdomain=* --http.api=eth,net,web3,admin,personal --allow-insecure-unlock console

use eth_getTransactionReceipt will cost 0.4s once

**Comment by s1na** [comment]
You're using the light client mode. Light clients don't store most chain data and state and will have to fetch them from light servers. This depends on network conditions and is typically slower. If latency is an issue you need to do a snap/full sync.

Feel free to re-open if that doesn't answer your question.
