### ISSUE TITLE
IPC filter creation returns always an Id of 0, RPC works as expected.

### ISSUE THREAD

**Issue by juanfranblanco** [ethereum/go-ethereum#2419]
#### System information

Geth version: `1.3.5`
OS & Version: Windows
Commit hash : 

#### Expected behaviour
IPC and RPC should be able to create filters using the same Json rpc request.

#### Actual behaviour
Rpc requests return a valid filter id, Ipc requests return always 0, other methods seem to work correctly hence  raising the issue.

#### Steps to reproduce the behaviour
As per above. This is spotted by testing / developing the .net api (Nethereum).

#### Backtrace

````
[backtrace]
````

**Comment by bas-vk** [comment]
What probably is happening is that you send the request to create the filter on different IPC connections. IPC connections are normally kept open unlike HTTP connections that are created and destroyed. Therefore filters are tight to the IPC connection, when the connection is closed the filters are removed too. If you create 2 filters over 2 IPC connections they would both have the filter id of 0x00 for that particular connection.

Simple test is to send 2 requests over the same connection, you would see that the first request would lead to a filter id of 0x00 and the second to 0x01.

This behaviour is changed in develop where a random non guessable filter id is returned. For example:
```
{
  "id": 73,
  "jsonrpc": "2.0",
  "result": "0x9100a56460f9cbf8a2f33adccab89f7d"
}
```
This prevents DApps to retrieves logs, or uninstall filters that they don't have created them self. After that filters are global and it works as you expects.

**Comment by juanfranblanco** [comment]
Many thanks, that was the issue. I will keep the connection open on the library until the next releases.
