### ISSUE TITLE
[Clef] Don't close process if trying to connect with wrong address

### ISSUE THREAD

**Issue by tmm360** [ethereum/go-ethereum#24203]
#### System information

I'm using Clef from Bee-Clef derivation with Docker. I've reported original issue here (https://github.com/ethersphere/bee-clef/issues/56), and I've been redirected on this repo.

#### Expected behaviour

When I try to ask to Clef an address, if the address is not recognized and error have to be reported, but process doesn't have to terminate.

#### Actual behaviour

The process terminate after the error {{Key does not exist}}.

#### Steps to reproduce the behaviour

I'm trying to use Bee-Clef with multiple addresses. For unknown issue, an address was not recognized, and this showed the issue.

#### Backtrace

````
INFO [01-02|23:28:23.208] Using stdin/stdout as UI-channel
INFO [01-02|23:28:23.778] Loaded 4byte database                    embeds=146,841 locals=8 local=/app/config/4byte.json
{"jsonrpc":"2.0","id":1,"method":"ui_onInputRequired","params":[{"title":"Master Password","prompt":"Please enter the password to decrypt the master seed","isPassword":true}]}
INFO [01-02|23:28:26.065] Rule engine configured                   file=/app/config/rules.js
INFO [01-02|23:28:26.065] Starting signer                          chainid=100 keystore=/app/data/keystore light-kdf=true advanced=false
INFO [01-02|23:28:26.094] HTTP endpoint opened                     url=http://[::]:8550/
{"jsonrpc":"2.0","method":"ui_onSignerStartup","params":[{"info":{"extapi_http":"http://[::]:8550/","extapi_ipc":"n/a","extapi_version":"6.1.0","intapi_version":"7.0.1"}}]}
INFO [01-02|23:28:28.593] Op approved
INFO [01-02|23:28:28.611] Op approved
INFO [01-02|23:28:29.362] Op approved
INFO [01-02|23:28:29.380] Op approved
WARN [01-02|23:28:29.380] Key does not exist                       key=0x *************MyEtherAddress***************
````
process killed here.

**Comment by karalabe** [comment]
Could you share exactly what and how you're running? How ar eyou requesting these keys from Clef?

**Comment by tmm360** [comment]
I was running bee-clef with docker-compose as this:

```
  bee-clef:
    image: ethersphere/clef:0.9.0
    environment:
      - CLEF_CHAINID=100
    networks:
      - bee-back
    volumes:
      - bee-clef-data:/app/data
    command: full
    restart: unless-stopped
```

so I was trying to connect with a swarm bee instance, with a service like this:

```
  bee1:
    image: ethersphere/bee:1.4.1
    restart: unless-stopped
    environment:
      - BEE_CLEF_SIGNER_ENABLE=true
      - BEE_CLEF_SIGNER_ENDPOINT=http://bee-clef:8550
      - BEE_DEBUG_API_ENABLE=true
      - BEE_GATEWAY_MODE=true
      - BEE_GLOBAL_PINNING_ENABLE=true
      - BEE_FULL_NODE=true
      - BEE_NETWORK_ID=1 #mainnet
      - BEE_PASSWORD=mypsw
      - BEE_SWAP_ENDPOINT=ws://nethermind-xdai:8545
    ports:
      - 1634:1634 #p2p
    networks:
      - bee-back
    volumes:
      - bee1-data:/home/bee/.bee
    command: start --clef-signer-ethereum-address=0x*************MyEtherAddress***************
    depends_on:
      - bee-clef
      - nethermind-xdai
```

when bee tries to connect to clef, if the address is recognized it works. If it is not recognized, the docker container restarts.
(Bee is also connected to a Nethermind instance synced on Gnosis Chain. Omitted because not relevant)

**Comment by holiman** [comment]
Clef does not exit/crash if something is attempted with an account that does not exist. It does, however, return a json rpc error. You're using ethersphere bee-clef, which afaict is wrapping clef with this script: https://github.com/ethersphere/bee-clef/blob/master/packaging/docker/entrypoint.sh . I suspect that this wrapper doesn't properly handle error conditions, which causes the docker script, and thus the docker image, to exit.

**Comment by holiman** [comment]
This has been answered in https://github.com/ethersphere/bee-clef/issues/56#issuecomment-1008350090 . If the password cannot be provided by the storage, clef sends a query to the next UI, to ask for the password. The bee-script does not handle the message coming over stdin, and exits.
