### ISSUE TITLE
I am a victim of token theft by hackers.I need help from the ethereum community. Can anyone help me post a post on ethereum's reddit forum.

### ISSUE THREAD

**Issue by blockchainer2** [ethereum/go-ethereum#24204]
I wrote a blog with detailed information about my theft, https://medium.com/@simith1122/hackers-stole-my-60-000-digital-currency-what-should-i-do-63da4fcf43c0

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
