### ISSUE TITLE
Geth 1.10.15 fails to sync with Ropsten

### ISSUE THREAD

**Issue by mdeliadi** [ethereum/go-ethereum#24202]
#### System information

Geth version: 1.10.15-stable
OS & Version: Debian GNU/Linux 9.6 (stretch)
Commit hash : 8be800ffa9c4992666e2620e0ab4725a1a83352b

#### Expected behaviour
Geth syncs with Ropsten.

#### Actual behaviour
Geth fails to sync with Ropsten, logging a lot of the following warnings:
- `Whitelist challenge timed out, dropping`
- `Synchronisation failed, dropping peer`
- `Synchronisation failed, retrying         err="shutting down"`

#### Steps to reproduce the behaviour
I've just updated Geth from 1.10.14-stable to 1.10.15-stable.

#### Backtrace
N/A

#### CLI options
`--ropsten --http --http.addr '0.0.0.0' --http.port 8545 --http.api eth,net,web3,personal,rpc --http.corsdomain '*' --http.vhosts '*' --ws --ws.port 8546 --port 30303 --txlookuplimit=0 --whitelist 6485846=0x43f0cd1e5b1f9c4d5cda26c240b59ee4f1b510d0a185aa8fd476d091b0097a80 --allow-insecure-unlock --rpc.allow-unprotected-txs --syncmode full`

**Comment by mdeliadi** [comment]
Update: Adding `--snapshot=false` doesn't change anything, still incapable of getting in sync, logging the same warnings/errors.

**Comment by jquesnelle** [comment]
We're seeing the same errors. For background, we've been using `--whitelist 10920274=0xfd652086d220d506ae5b7cb80fde97d2f3f7028d346cc7d9d384a83d3d638532` to get <1.10.15 to sync on Ropsten (to get off the bad fork being mined by old miners)

**Comment by karalabe** [comment]
Without logs as to see what Geth is outputting, we have no idea. Sync failures can occur now and agian, question is what happens in between.

**Comment by jquesnelle** [comment]
We see the errors from a 1.10.13 -> 1.10.15 upgrade (not a fully sync). The node was only 15 or so blocks behind; whatever time it took to stop, upgrade the binary, and restart. Switching back to 1.10.13 the node continues on fine, and back to 1.10.15 it immediately cannot sync.

On a side note, Ropsten is already in a pretty precarious position -- just a default sync, i.e. `geth --ropsten` will land you on an invalid fork. 

Here's the start of a the logs:
```
To exit, press ctrl-d or type exit
> INFO [01-06|14:12:34.945] Whitelist mismatch, dropping peer        id=43fef77b0f79cad2 conn=inbound number=10,920,274 hash=2fd63e..ced14f want=fd6520..638532
INFO [01-06|14:12:38.916] Block synchronisation started 
INFO [01-06|14:12:38.916] Mining aborted due to sync 
INFO [01-06|14:12:43.822] Looking for peers                        peercount=8 tried=31 static=0
INFO [01-06|14:12:53.889] Looking for peers                        peercount=18 tried=33 static=0
WARN [01-06|14:12:59.243] Whitelist challenge timed out, dropping  id=40b93e9a1d7d98cf conn=inbound addr=176.31.238.194:48338 type=Geth/v1.10.9-stable-...
WARN [01-06|14:12:59.586] Whitelist challenge timed out, dropping  id=8737ef9fa691365a conn=inbound addr=18.216.154.220:40452 type=Geth/v1.10.12-stable...
WARN [01-06|14:12:59.595] Whitelist challenge timed out, dropping  id=553e2f32386a8c63 conn=inbound addr=34.223.48.239:53346  type=Geth/v1.10.8-stable-...
```

It continues on like this for some time (about 5 minutes). Of note `net.peerCount` is high -- around 40 or so, but it does not import any blocks. Then, the log is spammed with:

```
WARN [01-06|14:18:08.687] Synchronisation failed, retrying         err="shutting down"
INFO [01-06|14:18:08.687] Mining aborted due to sync
WARN [01-06|14:18:08.687] Synchronisation failed, retrying         err="shutting down"
INFO [01-06|14:18:08.688] Mining aborted due to sync
WARN [01-06|14:18:08.688] Synchronisation failed, retrying         err="shutting down"
```

until the process is force-stopped

**Comment by mdeliadi** [comment]
The same happens to us, migrating from 1.10.13 to 1.10.15, the only difference is that we are on a full node. It's pretty hard to post some logs, because after bouncing back and fort between `Whitelist challenge timed out, dropping` and `Synchronisation failed, dropping peer` geth starts to spam `Synchronisation failed, retrying err="shutting down"` until the process is force-stopped - our logs collector counted 12 milions of log messages in less than one hour!

**Comment by Perlets9** [comment]
The same here with the same configuration 

`--whitelist 10920274=0xfd652086d220d506ae5b7cb80fde97d2f3f7028d346cc7d9d384a83d3d638532`

the `v1.10.13` works

**Comment by holiman** [comment]
Thanks for the reports. I believe #24210 solves this problem, please let us know if it does.

**Comment by karalabe** [comment]
This issue should be now fixed on master. It will land in the next stable release, but until then it would be nice if someone could verify that it indeed fixes it for you.

**Comment by jquesnelle** [comment]
> This issue should be now fixed on master. It will land in the next stable release, but until then it would be nice if someone could verify that it indeed fixes it for you.

1.10.15 + a cherry pick of #24210 syncs on Ropsten correctly 🙂

**Comment by MinwooJ** [comment]
> 1.10.15 + a cherry pick of #24210 syncs on Ropsten correctly 🙂
Will this version be released soon?

**Comment by karalabe** [comment]
It will probably follow out biweekly release schedule. So in 1-2 weeks.

**Comment by ryanschneider** [comment]
We just hit this issue too on Ropsten, I'll do the same cherry-pick tomorrow and verify.  What's odd is that we have 7 different node configurations that we run on Ropsten, six of them hit the issue but the 7th seems fine, as do all our Rinkeby and Goerli nodes, I'll look into it more tomorrow.

**Comment by MariusVanDerWijden** [comment]
Should be fixed in the upcoming release, please update.
If this is not fixed you can reopen this issue
