### ISSUE TITLE
skip unknown block execution without receipt (kintsugi-nimbus-geth)

### ISSUE THREAD

**Issue by SeaMonkey82** [ethereum/go-ethereum#24217]
#### System information

```
Geth
Version: 1.10.14-unstable
Git Commit: b71cbe04cf088dd852320b5968f407358257ca2e
Git Commit Date: 20220105
Architecture: amd64
Go Version: go1.17.5
Operating System: linux
GOPATH=
GOROOT=go
```

#### Expected behaviour
Sync

#### Actual behaviour
```
ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=2928eb..16445a number=144,632
WARN [01-09|13:16:16.587] Inserted known block                     number=144,633 hash=536748..a1a5fb uncles=0 txs=2    gas=55550   root=75cc96..ee5046
ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=536748..a1a5fb number=144,633
WARN [01-09|13:16:16.587] Inserted known block                     number=144,634 hash=2f95ee..903955 uncles=0 txs=0    gas=0       root=75cc96..ee5046
WARN [01-09|13:16:16.587] Inserted known block                     number=144,635 hash=82b7f3..6dddd7 uncles=0 txs=0    gas=0       root=75cc96..ee5046
WARN [01-09|13:16:16.587] Inserted known block                     number=144,636 hash=e5b52c..ed6999 uncles=0 txs=6    gas=166,650 root=a95aed..a87037
ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=e5b52c..ed6999 number=144,636
WARN [01-09|13:16:16.587] Inserted known block                     number=144,637 hash=9ccbd8..c3c0d6 uncles=0 txs=2    gas=55550   root=afba73..726dd8
ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=9ccbd8..c3c0d6 number=144,637
WARN [01-09|13:16:16.587] Inserted known block                     number=144,638 hash=5a6342..24ea27 uncles=0 txs=2    gas=55550   root=262123..86e3bb
ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=5a6342..24ea27 number=144,638
WARN [01-09|13:16:16.587] Inserted known block                     number=144,639 hash=ce194c..d056a0 uncles=0 txs=0    gas=0       root=262123..86e3bb
WARN [01-09|13:16:16.588] Inserted known block                     number=144,640 hash=4477e5..01f910 uncles=0 txs=4    gas=111,100 root=0f0c60..d3d12b
ERROR[01-09|13:16:16.588] Please file an issue, skip known block execution without receipt hash=4477e5..01f910 number=144,640
```

#### Steps to reproduce the behaviour
Sync nimbus-geth on kintsugi

**Comment by MariusVanDerWijden** [comment]
So this is a non-issue in the current implementation, but might become a problem in the future. If we import a known block, we might not have the receipts for them. In the current case, we will not import blocks as a sidechain without executing them. This is going to be changed in the future though. So if we have the block in a sidechain and now skip it, we need to be careful to also write the receipts when executing the sidechain.

**Comment by Rebka5** [comment]
Hello have you been able to sort out the issues

**Comment by Bezzat** [comment]
> #### Sistem bilgisi
> ```
> Geth
> Version: 1.10.14-unstable
> Git Commit: b71cbe04cf088dd852320b5968f407358257ca2e
> Git Commit Date: 20220105
> Architecture: amd64
> Go Version: go1.17.5
> Operating System: linux
> GOPATH=
> GOROOT=go
> ```
> 
> #### Beklenen davranış
> senkronizasyon
> 
> #### gerçek davranış
> ```
> ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=2928eb..16445a number=144,632
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,633 hash=536748..a1a5fb uncles=0 txs=2    gas=55550   root=75cc96..ee5046
> ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=536748..a1a5fb number=144,633
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,634 hash=2f95ee..903955 uncles=0 txs=0    gas=0       root=75cc96..ee5046
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,635 hash=82b7f3..6dddd7 uncles=0 txs=0    gas=0       root=75cc96..ee5046
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,636 hash=e5b52c..ed6999 uncles=0 txs=6    gas=166,650 root=a95aed..a87037
> ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=e5b52c..ed6999 number=144,636
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,637 hash=9ccbd8..c3c0d6 uncles=0 txs=2    gas=55550   root=afba73..726dd8
> ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=9ccbd8..c3c0d6 number=144,637
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,638 hash=5a6342..24ea27 uncles=0 txs=2    gas=55550   root=262123..86e3bb
> ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=5a6342..24ea27 number=144,638
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,639 hash=ce194c..d056a0 uncles=0 txs=0    gas=0       root=262123..86e3bb
> WARN [01-09|13:16:16.588] Inserted known block                     number=144,640 hash=4477e5..01f910 uncles=0 txs=4    gas=111,100 root=0f0c60..d3d12b
> ERROR[01-09|13:16:16.588] Please file an issue, skip known block execution without receipt hash=4477e5..01f910 number=144,640
> ```
> 
> #### Davranışı yeniden oluşturma adımları
> Nimbus-geth'i kintsugi'de senkronize et

**Comment by Bezzat** [comment]
> #### Sistem bilgisi
> ```
> Geth
> Version: 1.10.14-unstable
> Git Commit: b71cbe04cf088dd852320b5968f407358257ca2e
> Git Commit Date: 20220105
> Architecture: amd64
> Go Version: go1.17.5
> Operating System: linux
> GOPATH=
> GOROOT=go
> ```
> 
> #### Beklenen davranış
> senkronizasyon
> 
> #### gerçek davranış
> ```
> ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=2928eb..16445a number=144,632
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,633 hash=536748..a1a5fb uncles=0 txs=2    gas=55550   root=75cc96..ee5046
> ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=536748..a1a5fb number=144,633
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,634 hash=2f95ee..903955 uncles=0 txs=0    gas=0       root=75cc96..ee5046
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,635 hash=82b7f3..6dddd7 uncles=0 txs=0    gas=0       root=75cc96..ee5046
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,636 hash=e5b52c..ed6999 uncles=0 txs=6    gas=166,650 root=a95aed..a87037
> ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=e5b52c..ed6999 number=144,636
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,637 hash=9ccbd8..c3c0d6 uncles=0 txs=2    gas=55550   root=afba73..726dd8
> ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=9ccbd8..c3c0d6 number=144,637
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,638 hash=5a6342..24ea27 uncles=0 txs=2    gas=55550   root=262123..86e3bb
> ERROR[01-09|13:16:16.587] Please file an issue, skip known block execution without receipt hash=5a6342..24ea27 number=144,638
> WARN [01-09|13:16:16.587] Inserted known block                     number=144,639 hash=ce194c..d056a0 uncles=0 txs=0    gas=0       root=262123..86e3bb
> WARN [01-09|13:16:16.588] Inserted known block                     number=144,640 hash=4477e5..01f910 uncles=0 txs=4    gas=111,100 root=0f0c60..d3d12b
> ERROR[01-09|13:16:16.588] Please file an issue, skip known block execution without receipt hash=4477e5..01f910 number=144,640
> ```
> 
> #### Davranışı yeniden oluşturma adımları
> Nimbus-geth'i kintsugi'de senkronize et

**Comment by MariusVanDerWijden** [comment]
This issue is stale for a long time, will close. Please open a new issue if you see this log line. Thanks for reporting
