### ISSUE TITLE
ropsten share all is reject

### ISSUE THREAD

**Issue by wkx1003** [ethereum/go-ethereum#24214]
Why can nodes trade normally, but miner's share submission is suddenly rejected?  It was acceptable before.
![image](https://user-images.githubusercontent.com/43412713/148644993-55c83597-adaf-4c2e-a4ad-fad3256b9338.png)

**Comment by karalabe** [comment]
There's no notion of "shares" (I assume mining) in Geth. If you are using some pool, you'll need to take it up with them.

**Comment by wkx1003** [comment]
We built the ropsten and mainnet and pool ourselves. Mainnet is normal. The ropsten suddenly doesn't explode and lasts for half a month
