### ISSUE TITLE
Missing Windows 1.10.15 build 

### ISSUE THREAD

**Issue by PederG** [ethereum/go-ethereum#24216]
#### System information

Geth version: 1.10.15
OS & Version: Windows
Commit hash : (if `develop`)

#### Expected behaviour
Installer for Windows automatically added to https://geth.ethereum.org/downloads/ when a new stable version is released. 

#### Actual behaviour
Windows is missing binaries for the latest release. 

#### Steps to reproduce the behaviour
Visit https://geth.ethereum.org/downloads/

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
Thanks for the heads up, building now. The job got cancelled somehow, unsure by whom or by what process.

**Comment by karalabe** [comment]
Fixed now, thanks agian.
