### ISSUE TITLE
Block propagation latency in a private network

### ISSUE THREAD

**Issue by hma23** [ethereum/go-ethereum#24229]
Is there an ethereum geth command / procedure to measure the block propagation delay in a private blockchain with 5 nodes?

**Comment by ligi** [comment]
No there is not - do you want to write one?

**Comment by hma23** [comment]
Any pointers are highly appreciated. how to get the block start time and end times,etc

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
