### ISSUE TITLE
[swarm] rewrite swarm DNS 

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#2422]
@arachnid

#### Expected behaviour
given a domain <domain> registered with the swarm dns
bzz://<domain>/ resolves correclty 
the swarm/api calls likewise

#### Actual behaviour

* atm in the temp codebase the DNS is mocked out
* after with some discussion we decide to either forever or temporarily drop in-url versioning support as per `registar.VersionedRegistrar` and`common/registrar/ethreg/`

## Resources 
@arachnid

* https://www.reddit.com/r/ethereum/comments/4dan2g/official_registrars/
* old frontier guide: https://ethereum.gitbooks.io/frontier-guide/content/registrar_services.html
* the EIP is: ethereum/EIPs#26
* have a look at Gav's orig registrar code: https://github.com/ethereum/dapp-bin/tree/master/registrar
* doc howto do ABI bindings from within go and generate stubs: https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts
 *  a hint how to use it : https://github.com/ethereum/go-ethereum/blob/swarm/common/chequebook/cheque.go
*  the relevant swarm code entrypoint is: https://github.com/jaakmusic/go-ethereum/blob/jaak/swarm/api/dns.go
* mother issue: https://github.com/ethereum/go-ethereum/issues/2048
* usage: https://github.com/ethersphere/swarm/wiki/swarm#bzz-domain-names-registration-resolution
* version support as per https://github.com/ethersphere/swarm/wiki/swarm#changes-versions-rollback is now dropped

**Comment by fjl** [comment]
@zelig side note: you can remove parts of the issue template if they are not appropriate

**Comment by zelig** [comment]
implemented in a series of ENS PRs:

* https://github.com/ethereum/go-ethereum/pull/2879
* https://github.com/ethereum/go-ethereum/pull/2912
* https://github.com/ethereum/go-ethereum/pull/2903
* https://github.com/ethereum/go-ethereum/pull/2952
