### ISSUE TITLE
Is iOS build not supported anymore?

### ISSUE THREAD

**Issue by soharang** [ethereum/go-ethereum#24232]
Hello, 

When I visit https://geth.ethereum.org/downloads/, there is a iOS section and the latest build for iOS is still v1.10.3. 
Whereas, the latest build of android library is v1.10.15.

I tried to build iOS build with the latest build, referring to https://geth.ethereum.org/docs/install-and-build/cross-compile, but I cannot success.
Someone mentioned that the cross compiling with xgo does not support anymore in https://github.com/ethereum/go-ethereum/pull/23800.

So anyone can let me know what the current status for ios build of geth is?

Thank you.

**Comment by ligi** [comment]
There is currently a problem with it - but we try to bring it back

**Comment by ligi** [comment]
dup of #23785

**Comment by soharang** [comment]
@ligi Thanks for the response.
I hope it could be brought back soon.
