### ISSUE TITLE
Shorter chain is chosen in re-org when totalDifficulty is the same

### ISSUE THREAD

**Issue by guoyiteng** [ethereum/go-ethereum#24230]
Hi, I noticed that geth picked up the the shorter chain when totalDifficulty is the same in ForkChoice. May I ask why this is the case?
https://github.com/ethereum/go-ethereum/blob/master/core/forkchoice.go#L96
```
number, headNumber := header.Number.Uint64(), current.Number.Uint64()
```
Also the variable name `headerNumber` here is a bit confusing. I know this came from a recent refactor #23761 but it would be clearer if we can rename these two variables to something like `headerNumber, number`.

**Comment by rjl493456442** [comment]
Regarding the reason for choosing the block with lower number, maybe you can try to read the paper we linked here. 

And about the variable names, I think `number, headNumber` is better. `current` here refers to the local head header, and the `header` refers to a header given by a remote peer(so guarantee it can be the canonical chain head).
