### ISSUE TITLE
Remote peer dial errors

### ISSUE THREAD

**Issue by de-ltd** [ethereum/go-ethereum#24246]
Can someone please clear up exactly what the following peer errors are when dialling - and possible causes.

connection refused
EOF
Useless peer
i/o timeout

Thanks, just making sure i handle this correctly.

**Comment by holiman** [comment]
EOF is when the remote part just shuts down on us, maybe he kicked us off because we weren't what he was looking for. 
Useless peer is when we determine that the peer is useless -- maybe it's syncing (and we are too), or maybe it's starving us on data that we need during sync

**Comment by MariusVanDerWijden** [comment]
Connection refused: We can not make the connection or the remote peer has too many peers already
EOF: Connection was terminated 
Useless peer: If the peer can not deliver some useful data to us
I/o timeout: The connection times out (due to nw lag etc.)

**Comment by de-ltd** [comment]
Thanks!
