### ISSUE TITLE
Rinkeby is off-line 

### ISSUE THREAD

**Issue by Joshvico** [ethereum/go-ethereum#24240]
Hi,

I'm trying to claim the ETH for the test net through Rinkeby faucet but is offline. Since this is a very common problem. Does anybody know when it will back or the tool is not functioning anymore. 

This is my wallet in case somebody can send some:
0xc2Cc8BcB01b8bD413d87Da7B9094e32f72D9F8e0

Please assist, thank you in advance. 

Kind regards,
Josh

**Comment by ligi** [comment]
You can use: http://fauceth.komputing.org/

**Comment by marksatorrre** [comment]
How to get rinkeyby coz it is down now and I need to test my contract

**Comment by marksatorrre** [comment]
0x28a2D53C87a7F7D152c9448A8E31E4dAcD2E7e08   my wallet please send rinkeby thanks

**Comment by ligi** [comment]
https://fauceth.komputing.org/ works

**Comment by marksatorrre** [comment]
Great it was sent . How long till I get the eth ?   
  
  
  
  
Sent from Mobile
  

  
Sincerely,   
  

 Mark S     
  

  
  
>

**Comment by ligi** [comment]
it is there - once you get the dialog. I see it in your account

**Comment by marksatorrre** [comment]
Whats the New RPC URL and chain id coz its now showing yet here im my rinkeyby wallet on metagask

**Comment by ligi** [comment]
etherscan shows it - https://rinkeby.etherscan.io/address/0x28a2D53C87a7F7D152c9448A8E31E4dAcD2E7e08
so it must be a MM bug

**Comment by marksatorrre** [comment]
whats the rpc url and chain probably im using the wrong ones
