### ISSUE TITLE
cmd/geth: --rpcapi should start the HTTP interface

### ISSUE THREAD

**Issue by jacohend** [ethereum/go-ethereum#2424]
#### System information

Geth version: `1.3.6`
OS & Version: `4.4.0-12-generic #28-Ubuntu SMP Wed Mar 9 00:33:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux` 
Commit hash : bf324bd24be9036046e36c6248b2d7c31cce9eca

#### Expected behaviour

A response according to the JSON-RPC examples: https://github.com/ethereum/wiki/wiki/JSON-RPC

#### Actual behaviour

`curl: (52) Empty reply from server`

#### Steps to reproduce the behaviour

geth --rpcapi "db,eth,net,web3,personal"

curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' http://127.0.0.1:30303 

Also --rpcport doesn't seem to work either

This seems to be similar to what is reported in issue #1942

**Comment by fjl** [comment]
The default rpc endpoint is http://localhost:8545. Port 30303 is the p2p port.

```text
$ geth --rpc
<snip snip, lots of output here>
I0405 21:48:25.773144 node/node.go:290] IPC endpoint opened: /Users/fjl/Library/Ethereum/geth.ipc
I0405 21:48:25.775263 node/node.go:360] HTTP endpoint opened: http://localhost:8545

$ curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' http://127.0.0.1:8545
{"jsonrpc":"2.0","id":1,"result":"Geth/v1.4.0-unstable-4e3e9a6c/darwin/go1.6"}
```

**Comment by fjl** [comment]
Repurposing this issue to track the suggestion to start RPC interface XXX when --XXXapi is supplied.

**Comment by fjl** [comment]
@bas-vk what do you think?

**Comment by bas-vk** [comment]
Personally I'm not a big fan and think it makes more sense to have a clear separation between starting and configuration the enabled modules. But I have no strong feelings to change that.

**Comment by obscuren** [comment]
If we want to go down that road I'd say that we drop both `--ipcapi` and `--rpcapi` and move to a more uniform CLI api where the API is directly passed to `--ipc` and `--rpc` respectively.

**Comment by bas-vk** [comment]
You mean something like this?

```
geth --rpc        # would start HTTP interface with the default api's
geth --rpc a,b    # would start the HTTP interface with a and b enabled
```
I don't think this is supported in the cli package since it's really hard to figure out how to parse. E.g. `geth --rpc console` would add console to the rpc api's instead of executing the console command. Maybe there are other packages that allow for this.

**Comment by fjl** [comment]
Yes, that would indeed be a breaking change and it is impossible to parse a command line like this correctly.

**Comment by karalabe** [comment]
I also second that it's not really a good idea. There are quite a few RPC options, so why would `rpcapi` start the HTTP interface and why shouldn't `rpcport` start it, etc? So I really agree wit @bas-vk that enabling something and changing configs should really be done separately.

Adding a warning that "You seem to have changed HTTP/RPC configs but did not enable it" might we a worthwhile extension, but I'm not a big fan of these combo effects.
