### ISSUE TITLE
"known transaction" and "replacement transaction underpriced" error on private POA network using geth

### ISSUE THREAD

**Issue by nileshpanhale** [ethereum/go-ethereum#24245]
#### System information

Geth version: `1.10.8-stable`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

# Case : 
I have created a mining node using geth console with gasprice zero and POA consensus. Due to some changes, I need to redeploy our smart contract of token minting. After redeployment, I started to get 2 errors from the mining node for some transactions.
1. Error: Returned error: replacement transaction underpriced
2. Error: Returned error: known transaction 

# This is my geth node command - 
`geth --datadir node1/ --networkid 2021 --port 30303 --syncmode full --rpc --rpcport 9001 --allow-insecure-unlock --unlock node1/account.txt --password node1/password.txt --nodiscover --rpccorsdomain * --nat any --rpcapi personal,eth,net,web3,txpool,miner --ipcpath node1/geth.ipc --miner.gasprice 0 --mine`

# My minting function in JS - 

```javascript
async function mint(receiver, amt) {

    //to remove transaction replacement error, I have added 1 to nonce with pending transactions.
    let nonce = await web3.eth.getTransactionCount(owner, 'pending') + 1;

    const amount = web3.utils.toHex(amt);
    const mintFunction = contract.methods.mint(receiver, amount).encodeABI();
    const NetworkId = await web3.eth.net.getId();

    /**
    * Raw_transaction instance to specify all parameters for ethereumjs-tx Transation
    */
    const rawTx = {
        "from": owner,
        "to": contractAddr,
        "data": mintFunction,
        "nonce": nonce,
        "value": "0x00000000000000",
        "gasLimit": web3.utils.toHex(210000),
        "gasPrice": 00,
        "chainId": NetworkId
    };

    /**
     * @dev initiate transaction with Raw_trasansaction instance for ethereumjs-tx Transaction
     */
    let transaction = new ETx(rawTx, { common });

    /**
     * @dev sign the transaction with private key to change blockchain status
     */
    transaction.sign(pvt);

    /**
     * @dev send the signed transaction to smart contract
     */
    web3.eth.sendSignedTransaction('0x' + transaction.serialize().toString('hex'), (err, hash) => {
        if (err) {
            console.log(err);
        }
        else {
            console.log("Mint Transaction Hash : " + hash);
            console.log("Token minting successful.");
            return hash;
        }
    });
};
```
#### Expected behavior
Now with this, after every 5 sec new block will be minted by owner address. All transactions are signed only by owner's private key. The mining node is set to accept 0 gas fee. Transactions are signed and minted successfully. 

#### Actual behaviour
Some of the transactions are not confirmed due to "known transaction" error and some due to a "replacement transaction underpriced" error. Now I can't redeploy smart contract and can't stop mining node also, because its live on prod now. 

##PLEASE SUGGEST A FIRM SOLUTION TO THESE TWO ERRORS WITHOUT ANY CHANGE IN MINING NODE OR SMART CONTRACT.
I think there must be a solution in JS function which resolve these errors for me.

**Comment by holiman** [comment]
` web3.eth.getTransactionCount(owner, 'pending') + 1;` -- afaik, this method gets the current nonce, as in, the nonce for that address in the current state. 
It does not take into account the number of pending transactions you have. So if you perform three of these before a new block is minted, those three will have the same nonce, and only one of them will make it into a block. 

For a more robust version, you can keep track of the nonce on your side, and increase every time you submit a new transaction, and periodically (e.g. sometimes when a new block arrives or after a reorg) sync it with the chain. For an even more robust solution, maintain a map of nonce ->  unsigned transaction, so you can fix up errors due to dropped transactions.

**Comment by nileshpanhale** [comment]
> 

Thank you so much holiman for the reply. 
About nonce, for every transaction nonce is incremented by 1 automatically due to '+1' in getTransactionCount. now if I have to resolve this nonce repetition issue, what changes shall I do in mint function?
