### ISSUE TITLE
SimulatedBackend: Option for disabling base fee

### ISSUE THREAD

**Issue by matthiasgeihs** [ethereum/go-ethereum#24258]
# Rationale

For testing, it would be useful we could disable the base fee to have zero cost transactions. I have seen that `vm.Config` has an option for disabling the base fee, but this is not exposed via any of the `SimulatedBackend` constructors.

# Implementation

See above.

**Comment by karalabe** [comment]
I'm unsure that would be wise. The simulated backend is supposed to give you a realistic - albeit empty - chain. The base fee isn't going anywhere so ignoring it as if it didn't happen can only lead to bugs imho later.

**Comment by matthiasgeihs** [comment]
It would make it easier to test whether our payout logic works as expected, if we don't need to account for gas fees. Or is there another way to do that?

**Comment by holiman** [comment]
You can just use the tx receipt to figure how much the transaction cost, and figure it out from there?

**Comment by holiman** [comment]
If we were to modify this, so that you have london but no basefee, then I think it'll lead to internal inconsistencies -- because basefee can never ever be zero in post-london, and I think we have code which relies on this. So from our perspective it would just add weird bugs in odd places.

**Comment by matthiasgeihs** [comment]
There is actually a flag in the EVM config to disable the base fee. But it's not easily accessible from the oustide.

https://github.com/ethereum/go-ethereum/blob/abd49a6c482e8b5cddd021f15a5cc20a91504e22/core/vm/interpreter.go#L28-L37
