### ISSUE TITLE
debug_traceBlockByNumber does not accept "latest"

### ISSUE THREAD

**Issue by quickchase** [ethereum/go-ethereum#24264]
#### System information

Geth version: `v1.10.15`
OS & Version: Linux

#### Expected behaviour
Support "latest" as a valid input for blockNumber for debug_traceBlockByNumber? I'm not sure if this is really part of the spec or not, however, Nethermind does support this. Pretty much every other method that takes a block number takes "latest" (and "pending" for that matter, but 🤷 ) so maybe this is easy to implement?

#### Actual behaviour
`{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params"},"id":1}`

#### Steps to reproduce the behaviour
```
curl -H "Content-Type: application/json" -d '{"method":"debug_traceBlockByNumber","params":["latest"],"id":1,"jsonrpc":"2.0"}' http://localhost:8545
```

This may be a feature request and not a bug 🙂

**Comment by MariusVanDerWijden** [comment]
Weird, it works for me (on the console and via curl) and the code is written s.th. it should accept that.
```
curl -H "Content-Type: application/json" -d '{"method":"debug_traceBlockByNumber","params":["latest"],"id":1,"jsonrpc":"2.0"}' http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":[]}
```
I'm on v.10.16

**Comment by itcuihao** [comment]
Hi, An error occurred, what should I do?
```
sdev@:~$ curl -X POST -H "Content-Type: application/json" http://03-02-04:8545 --data '{"jsonrpc": "2.0", "id": 1, "method": "debug_traceBlockByNumber", "params": ["latest"]}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method debug_traceBlockByNumber does not exist/is not available"}}
```

**Comment by MysticRyuujin** [comment]
I will double check tomorrow against more nodes and versions.

@itcuihao your problem is PROBABLY that you don't have the debug namespace enabled in the cli flags.
