### ISSUE TITLE
eth_getFilter RPC returns error on develop

### ISSUE THREAD

**Issue by tinybike** [ethereum/go-ethereum#2426]
#### System information

Geth version: 1.4.0-unstable
OS & Version: Ubuntu Linux 14.04
Commit hash: 7e02105672cda92889a78db864a5701d78f45eb2

#### Expected behaviour

Successful creation of a new filter using RPC `eth_getFilter`.  The response I get on the master branch is:
```
{"id":1,"jsonrpc":"2.0","result":"0x0"}
```
(Subsequent new filter requests return `0x1`, `0x2`, etc., as expected.)

#### Actual behaviour

On the develop branch, `eth_getFilter` RPC request returns an error:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"invalid topic on index 0"}}
```

#### Steps to reproduce the behaviour

Start a local geth node on the develop branch.  For completeness' sake, here is the full command I used to start geth:
```
deploy@loopy:~$ geth --cache 2048 --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --maxpeers 64 --rpcapi eth,net,web3 --ipcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3 --testnet --etherbase 0x00bae5113ee9f252cceb0001205b88fad175461a --unlock 0x00bae5113ee9f252cceb0001205b88fad175461a --password ~/.ethereum/.password console
```
Then send the `eth_newFilter` RPC using curl:
```
deploy@loopy:~$ curl -X POST --data '{"id":1,"jsonrpc":"2.0","method":"eth_newFilter","params":[{"address":"0xf37626aa99f29a4afe7406e386f68cc77be2cb6e","topics":["updatePrice"]}]}' http://localhost:8545
```
This request works fine on master (returning the expected result above); however, on develop, it fails and returns the `-32602: invalid topic on index 0` error.

**Comment by bas-vk** [comment]
I'm actually a bit surprised that this "works" on master. The spec specifies that topics are 32 bytes long. I did a test with master and using an invalid topic does indeed create the filter but it matches topics incorrect.

Develop has a RPC implementation that does better input validation which rejects this input. I don't know how your event looks like. If it has no argument then you need to use something like:

`0x673a7e28e0c32ef7c9d62cc87ee5bc9ee0cb512937e54075b13c4d9770e98988 `

You can calculate this with:
`web3.sha3("updatePrice()")`

[More details can be found in the solidity tutorial.](https://solidity.readthedocs.org/en/latest/contracts.html#events)

**Comment by fjl** [comment]
The error message could be improved though.

**Comment by tinybike** [comment]
It does indeed work on master; we have been using it in practice to filter for `updatePrice` and `creationBlock` events in the Augur app.  It seems to match topics correctly, which is very strange if it's expecting to receive sha3("updatePrice()") and instead it's just receiving "updatePrice".  Examples: https://github.com/AugurProject/augur.js/blob/master/test/core/filters.js

Event definitions:
updatePrice: https://github.com/AugurProject/augur-core/blob/scaling/src/functions/buy%26sellShares.se#L31
creationBlock: https://github.com/AugurProject/augur-core/blob/scaling/src/functions/createMarket.se#L32

(These are Serpent contracts, but I assume Serpent and Solidity events compile to the same EVM code.)

**Comment by tinybike** [comment]
Hmm.  We're also filtering by contract address, and `updatePrice` is the only event on that contract, so that might be why the filter appears to work on master.

**Comment by bas-vk** [comment]
Yes, that is the reason.

**Comment by tinybike** [comment]
Okay, fixed our topics and all's well.  Thanks @bas-vk!
