### ISSUE TITLE
Invalid value returned by GasPrice() (+)

### ISSUE THREAD

**Issue by juggleru** [ethereum/go-ethereum#24267]
I'm trying to calculate transaction fee using go-ethereum. For that I'm getting transaction and check gas price and gas to multiply them. But gas price has a wrong value.

github.com/ethereum/go-ethereum v1.10.15

```
	tx, _, err := client.TransactionByHash(
		context.Background(),
		common.HexToHash("0xdb9cf08df128fba6d8d06a0b98d967939d7509f36956091e3ad498bda4b29907"))
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("Gas price:", tx.GasPrice())
```
Output:
```
Gas price: 172774404731
```

But if you look at the transaction on etherscan https://etherscan.io/tx/0xdb9cf08df128fba6d8d06a0b98d967939d7509f36956091e3ad498bda4b29907 you will see that received value is not Gas price (91572854766) but Max gas fee.

How to get correct Gas price for transaction?

**Comment by holiman** [comment]
The tx is a `type 2` transaction, which means the _effective_ gas price depends on the block -- it cannot be determined given only the transaction. 
Here's an example of how we pick it up in another place in the code (ethapi/api.go): 
```
		gasPrice := new(big.Int).Add(header.BaseFee, tx.EffectiveGasTipValue(header.BaseFee))
```
