### ISSUE TITLE
Can I download some specific trie node without full sync?

### ISSUE THREAD

**Issue by IamHuskar** [ethereum/go-ethereum#24265]
I don't want to do fully sync because it's so big. but when I want to do some trace in specific block. geth says missing trie node xxxxxx.
can I download some specific trie node without full sync?

**Comment by rjl493456442** [comment]
You can trace the block via light client. It will retrieve the needed state via the network. But light client can only retrieve the "latest 128 blocks" states from the network since historical states are dropped by default.

**Comment by holiman** [comment]
@rjl493456442 answered. Other possibilities exist, but it requires a custom client and some good luck to find a peer which has the state you need.
