### ISSUE TITLE
geth --dev --datadir data Fatal: Could not open database

### ISSUE THREAD

**Issue by memekas** [ethereum/go-ethereum#24279]
#### System information

Geth version: 1.10.16-unstable-bd615e0e-20220124
OS & Version: OSX 12.1
Commit hash : master - bd615e0e5fac73bcfe6861d49a5c6fe5906c4820
Arch: arm64 (Apple M1)

#### Expected behaviour
normal startup

#### Actual behaviour
```
$ ./build/bin/geth --datadir data/dev --dev
INFO [01-24|10:33:48.528] Starting Geth in ephemeral dev mode...
INFO [01-24|10:33:48.530] Maximum peer count                       ETH=50 LES=0 total=50
INFO [01-24|10:33:48.532] Set global gas cap                       cap=50,000,000
INFO [01-24|10:33:48.573] Using developer account                  address=0xB3B970d3C86933eD22AaF13eea21903737eDc7EA
INFO [01-24|10:33:48.573] Allocated cache and file handles         database=[MY_PATH]/go-ethereum/data/dev/geth/chaindata cache=512.00MiB handles=5120 readonly=true
Fatal: Could not open database: stat [MY_PATH]/go-ethereum/data/dev/geth/chaindata: no such file or directory
```
It creates a `datadir`:
```
$ tree data/dev
data/dev
├── geth
│   ├── LOCK
│   └── nodekey
└── keystore
    └── UTC--2022-01-24T07-27-04.750514000Z--b3b970d3c86933ed22aaf13eea21903737edc7ea
```

#### Steps to reproduce the behaviour

```
$ git clone https://github.com/ethereum/go-ethereum.git
$ cd go-ethereum
$ make geth
$ ./build/bin/geth --datadir data/dev --dev
```

i followed this instruction: https://geth.ethereum.org/docs/getting-started/dev-mode
It is possible that the reason is that the `readonly` flag appears:
```
INFO ... Allocated cache and file handles ... readonly=true
```
If i'm not wrong it sets here: https://github.com/ethereum/go-ethereum/blob/78636ee56856ef50299183dd04d02a3e7f555cbc/cmd/utils/flags.go#L1673-L1683

Is this normal behaviour?

**Comment by karalabe** [comment]
Thanks for the report. There was a bad comment in the code and someone reverted the database into read only mode due to it. Fixed now again.
