### ISSUE TITLE
Ask about Snap sync!

### ISSUE THREAD

**Issue by junha-ahn** [ethereum/go-ethereum#24272]
I understood that "Snap sync" downloads the "Snapshot Acceleration Structure" from another node on the network, effectively downloading the latest State (flat key-value store).

So, what happens to the memory structure of the existing Full Sync mode and the MPT State structure stored on the disk?

(1) The State structure of Full/Fast Sync mode stored in memory is **replaced** by the Snapshot In-memory layer.

(2) The existing MPT structure **disappears** in Level DB, and the snapshot persistent disk layer is stored.

(3) I heard that when Snap Sync Mode is completed, it switches to Full Sync mode, but will only the snapshot data structure continue to be stored (push)?

Is it right that I understood?

**Comment by karalabe** [comment]
(1, 2) Snap sync downloads the flat state and reconstructs the trie from that. Any existing trie data is left on disk as there's no harm (trie nodes are just hash-mapped data blobs, so having a few more entries doesn't matter).

The flat data chunks are also saved to disk (overwriting or extending whatever is already there; but generally snap is only used for initial sync, so there shouldn't be any previous leftover). In either case, once snap sync is done, the flat snapshot format is iterated and any errors fixed (it compares the content to the MPT, and if there's a mismatch, it regenerates that part of the snapshot). Thus after sync and snapshot fixup, both MPT and flat snapshot are correct.

(3) No, both MPT and snapshot will be maintained. The snapshot is used as an accelerator + serving to other nodes. The MPT is needed to calculate and verify the root hashes of the blocks.
