### ISSUE TITLE
Rinkeby faucet not work again 

### ISSUE THREAD

**Issue by loobj126** [ethereum/go-ethereum#24273]
![image](https://user-images.githubusercontent.com/80636231/150663745-48acc74d-59c9-4eff-a5e1-fe38ad4fc260.png)

The same issue here. Could you please assist if you have any spare ETH?
0x623CD18A2344476063Ee2f806EEdDdbcE9cd5499

**Comment by loobj126** [comment]
Could you please assist if you have any spare ETH?
0x623CD18A2344476063Ee2f806EEdDdbcE9cd5499

**Comment by ligi** [comment]
you can get rinkeby funds from here: https://fauceth.komputing.org/
