### ISSUE TITLE
Is a full node a requirement to broadcast transactions?

### ISSUE THREAD

**Issue by sunset1234321** [ethereum/go-ethereum#24287]
Sometimes I want to interact with some smart contract ( maybe a decentralized exchange like uni swap)

And I want my transaction to be confirmed __the fastest__.

But usually, we are relying on other full nodes to help us broadcast the transactions.

For example on uniswap trading website https://app.uniswap.org/#/swap  ,  it use  https://mainnet.infura.io/v3/xxxxxxxxxxxxxxxxx  as a provider. 

But the service is not guaranteed and it could delay your request to broadcast the transactions. 

So I am thinking whether building my own node will be better.

What node could broadcast transactions to miners?    Is __full node__ the only choice?

**Comment by karalabe** [comment]
A light client also works. Though I don't think you'll see a noticeable speedup vs infura. My guess is that you're trying to beat MEV miners, but that won't be possible since they will always sandwich other trades around yours to max their profits.
