### ISSUE TITLE
go-ethereum does not implement the EIP-1559 spec correctly

### ISSUE THREAD

**Issue by samsondav** [ethereum/go-ethereum#24284]
Reading the spec [here](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md
), it is indicated that FeeCap can be kept constant as the most that a client is willing to pay, and TipCap be manipulated to ensure timely inclusion.

However in practice that doesn't work.

Looking at [the code](https://github.com/ethereum/go-ethereum/blob/bff330335b94af3643ac2fb809793f77de3069d4/core/tx_list.go#L298) it appears that you _must_ bump both TipCap **and** FeeCap together or the transaction will be rejected.

This seems like a mistake. From my understanding, FeeCap is "the maximum I would ever be willing to pay for this transaction". 

### Expected behaviour

It should be possible to increase the TipCap while keeping FeeCap the same. In short, the following series of transactions should be ok:

`FeeCap: 10GWei, TipCap: 1Gwei`

Wait some time, it didn't get included yet. We want to bump to get faster inclusion but still ensure the maximum we can possibly pay is 10GWei.

`FeeCap: 10GWei, TipCap: 2GWei`

It should be accepted into the mempool.

### Actual behaviour

In practice the second transaction returns `replacement transaction underpriced` errors.

**Comment by karalabe** [comment]
In your example, if the basefee is say 9gwei, then it doesn't matter if you bumped the tip from 1 to 2, it's gonna end up with 1 in the end either way. The goal of requiring a bump on both was to avoid these kind of scenarios where is "seems" that you bumped the price, but you didn't really. Those are very hard to reason about and we don't really see the value in taking that risk. A replacement transaction pre-1559 needed a 10% bump overall. Post 1559 requiring a bump on both the total and the tip cap ensures that we retain the original behavior of actually paying more for a replacement and avoiding spam.

**Comment by samsondav** [comment]
@karalabe but that would be intentional? FeeCap is the total max you are willing to pay. I would expect it not to be mined at all if the base fee is 9GWei and the tip is 2GWei, it would get mined once base fee comes down
