### ISSUE TITLE
geth attach does not work on develop

### ISSUE THREAD

**Issue by tinybike** [ethereum/go-ethereum#2429]
#### System information

Geth version: 1.4.0-unstable
OS & Version: Ubuntu Linux 14.04
Commit hash : 7e02105672cda92889a78db864a5701d78f45eb2

#### Expected behaviour

`geth attach` should attach to a running geth instance via IPC.  On master it does this fine and presents me with the geth console.

#### Actual behaviour

On develop, I get the following error from `geth attach`:
```
Fatal: Unable to attach to geth: dial unix /home/deploy/.ethereum/geth.ipc: connect: connection refused
```

#### Steps to reproduce the behaviour

Start geth, then in another terminal, use `geth attach`.

**Comment by bobsummerwill** [comment]
Please can you also check this works for `eth`?

`geth-1.3.5` doesn't work.   `develop` used to work around Homestead.    We need to ensure that `geth attach` works for `eth` for the `1.4.0` release.   Thanks!

**Comment by bas-vk** [comment]
Could you post the permissions of the socket endpoint (and check if master and develop are different)? Are you running the node and the client with different users?

It would also be interesting to get the output of this command:
```
echo '{"id": 2, "method": "eth_blockNumber"}' | socat -T1 -,ignoreeof  UNIX-CONNECT:$HOME/.ethereum/geth.ipc
```

**Comment by tinybike** [comment]
Happy to report that `--unlock` is working fine for me this morning.  I'm not sure what changed (perhaps I just needed to restart geth?) but I'm updating the issue to reflect this.

Permissions are the same on master and develop:
```
jack@vent:~/.ethereum$ ls -l | grep ipc
srw------- 1 jack jack    0 Apr  5 15:25 geth.ipc
```
Node and client users are the same.  (User = `jack`, the owner of the socket file, in both cases.)

master:
```
(master) jack@vent:~$ echo '{"id": 2, "method": "eth_blockNumber"}' | socat -T1 -,ignoreeof  UNIX-CONNECT:$HOME/.ethereum/geth.ipc
{"id":2,"jsonrpc":"","result":"0xadb37"}
```

develop:
```
jack@vent:~$ echo '{"id": 2, "method": "eth_blockNumber"}' | socat -T1 -,ignoreeof  UNIX-CONNECT:$HOME/.ethereum/geth.ipc
2016/04/07 09:24:10 socat[30369] E connect(3, AF=1 "/home/jack/.ethereum/geth.ipc", 31): Connection refused
```

@bobsummerwill I'm happy to check, but I do not have eth installed at the moment.  What is the recommended way to install the most recent version of eth?  (It's no longer in the cpp-ethereum repo, correct?)

**Comment by tinybike** [comment]
Correction: `--unlock` only works in the geth console.  RPC commands fail with a -32000 account is locked error, even when the equivalent command issued from the console succeeds.

**Comment by bas-vk** [comment]
Could you start geth with `--vmodule "node/*=6,rpc/*=6"` and see if an error is logged when you connect? An interesting line would start be `IPC accept failed: <...>`.

Could you also check your system logfiles if there is some kind of error? It's really strange that 1.3 works and 1.4 not.

@bobsummerwill, is appears that this has nothing to do with `geth attach` since socat returns the exact same error. It looks like the node is unable to accept the connection for some reason to be determined. If you want we can test if geth 1.4 attach still works with eth. Ping me on gitter.

**Comment by bobsummerwill** [comment]
Thanks, @bas-vk.
Yeah - I can believe it's something very tangential.     I just want to ensure we do a quick test on that scenario before 1.4 releases.

**Comment by ethers** [comment]
will this be fixed for 1.4?

**Comment by obscuren** [comment]
Yes it will.

**Comment by bobsummerwill** [comment]
BTW - I can confirm that `geth attach` onto `eth` nodes is working just fine in RC1.   Hurrah!

**Comment by ethers** [comment]
@obscuren thanks.  could someone add the 1.4 label https://github.com/ethereum/go-ethereum/milestones/1.4.0 ?  (I don't have permission)

**Comment by tinybike** [comment]
`geth attach` works for me on the main network now, but I get the same error as before when I try and attach to a testnet geth node.

**Comment by tinybike** [comment]
Possibly it is not working on testnet because it is trying to connect to the socket file in `~/.ethereum`, rather than the one in `~/.ethereum/testnet`?  Specifying `--testnet` or `--ipcpath` don't seem to change this:
```
deploy@loopy:~$ geth --testnet --ipcpath ~/.ethereum/testnet/geth.ipc attach
Fatal: Unable to attach to geth: dial unix /home/deploy/.ethereum/geth.ipc: connect: connection refused
deploy@loopy:~$ geth --ipcpath ~/.ethereum/testnet/geth.ipc attach
Fatal: Unable to attach to geth: dial unix /home/deploy/.ethereum/geth.ipc: connect: connection refused
```

**Comment by tinybike** [comment]
The following command works:
```
geth attach ipc:/home/deploy/.ethereum/testnet/geth.ipc
```
Thanks @obscuren.  Suggestion: announce the syntax update incredibly loudly, or make it so the old `--ipcpath` syntax also works.

**Comment by obscuren** [comment]
I believe we used to check both paths @bas-vk. What happened to this feature?
