### ISSUE TITLE
Request for Read-Only Geth

### ISSUE THREAD

**Issue by hrthaowang** [ethereum/go-ethereum#24294]
### Rationale

We want to request an option for running geth in a read-only mode that supports fetching data from the ethereum by reading the raw level db file from the file system. This is useful for scaling the reads of the archived data.

![output-onlinepngtools](https://user-images.githubusercontent.com/98331735/151046895-8a21dc6b-de2d-4939-8279-9196f5d1926b.png)

Currently, if a user wants to read data from the Ethereum blockchain, he has to connect to the rpc endpoint (provided by alchemy, infura, or self-hosted nodes) and make a request. 

This does not scale well because of the bottleneck of the server end, because the server needs to handle all kinds of requests from clients. To support the increasing volume of reading, we need to have more geth nodes.
![arch2](https://user-images.githubusercontent.com/98331735/151045536-c284dfc1-f315-4aaf-b0de-54cc2072ca65.png)

![test](https://user-images.githubusercontent.com/98331735/151045563-eb7f5649-a73d-4e3f-ac74-ea53b495183e.png)

However, if we could create a read-only abstraction that could access the level db (on some file systems even remote) storing the blockchain data directly, then the client would not need to interact with the server to read data. 

If we want to increase the reading speed, we could intuitively add more clients and make all of the clients reading from the same copy of the database data.
Providing the read-only geth as an option makes the scaling of reading from Ethereum more intuitive and easier.

![test2](https://user-images.githubusercontent.com/98331735/151045605-d0d48da0-9936-4acb-8cad-b9c1c897b06c.png)

### Implementation

We could add a boolean variable `readOnly` for the `node.go` and `backend.go`. If that variable is set to be true, geth would remove local files locks and network connections (HTTP Endpoint, P2P, etc.). Therefore, we could have multiple clients reading from the same dataset concurrently. 

Here is a simple and unclean MVP of this functionality. https://github.com/hudson-trading/go-ethereum/pull/1. We understand that there is a lot of copy-pasted code, and we will reorganize the code later. We would like to discuss the possibility and option of developing read-only geth and get to know geth community's thoughts on this. 

Thank you!

**Comment by ligi** [comment]
This also came up before - but it is great that you work on a MVP and actually experiment on it. Could be a nice feature for some use-cases. Is levelDB handling multiple clients on the same DB well?

**Comment by karalabe** [comment]
Leveldb does not support reading with multiple concurrent processes. Also a lot of the data a Geth node has is cached in memory only during runtime. The only way to get a consistent data view is to query the node owning the database, which would make that node be the same bottleneck as before.

**Comment by karalabe** [comment]
I'm guessing you could make some sophisticated infrastructure to have multiple Geth nodes serve an intermediate caching layer that might store and serve some data without reaching into Geth. That's how Infura is doing it, but that seems something very different from what Geth's purpose is.

Even then, I think it would be mostly useful for archive node data; but if you use a live node that constantly mutates the chain and the state, it's quite hard to meaningfully sync the status of different Geth nodes across a single master writer.

I.e. it's not really in the scope of Geth to work on horizontal read-scalability.

**Comment by danielmh0** [comment]
@karalabe Leveldb does support multiple readers if there are no writers. We have a fully working prototype here, and it's proven very useful so far: https://github.com/hudson-trading/go-ethereum/pull/2/files (not yet fully cleaned/code-reviewed).

How we want to use this in practice: have a live archival node writing to local flash; shut it down every so often; rsync node state to a read-only networked file system (pretty cheap thanks to mostly unchanging sstables). Then you can have massively parallel reads on archival state, without implementing the EVM or building a fancy caching layer. Geth-as-a-library executes calls using the read-only network file system.
