### ISSUE TITLE
types.NewEIP155Signer(chainID).Sender(signedTx) returns wrong address

### ISSUE THREAD

**Issue by RickCastle2018** [ethereum/go-ethereum#24303]
#### System information

Geth version: go-ethereum library
OS & Version: Linux

#### Expected behaviour

`types.NewEIP155Signer(chainID).Sender(signedTx)` should return the same address as `crypto.PubkeyToAddress(privateKey.PublicKey)` returns.

#### Actual behaviour

`types.NewEIP155Signer(chainID).Sender(signedTx)` returns random (but always the same) address.

#### Steps to reproduce the behaviour
Run:

```go
privateKey, _ := crypto.GenerateKey()

nonce, _ := transactions.Client.PendingNonceAt(context.Background(), crypto.PubkeyToAddress(privateKey.PublicKey))
gasPrice, _ := transactions.Client.SuggestGasPrice(context.Background())
gasLimit := uint64(21000)
amount := big.NewInt(10000000)
var data []byte
tx := types.NewTransaction(nonce, common.HexToAddress("0xfee66065C536A28000CfECF272A351592DA8473d"), amount, gasLimit, gasPrice, data)
signedTx, _ := types.SignTx(tx, types.NewEIP155Signer(big.NewInt(1), privateKey)

fmt.Println(crypto.PubkeyToAddress(privateKey.PublicKey))
fmt.Println(types.NewEIP155Signer(big.NewInt(1)).Sender(signedTx))
```
You'll see that address on first output line (with which the tx was signed) is different from address on the second line.

**Comment by RickCastle2018** [comment]
Oh, sorry. I've messed up something. Everything is fine...

```go
package main

import (
	"context"
	"fmt"
	"log"
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind/backends"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
)

func main() {
	genesisAlloc := core.GenesisAlloc{}
	blockGasLimit := uint64(4712388)
	Client := backends.NewSimulatedBackend(genesisAlloc, blockGasLimit)

	privateKey, err := crypto.GenerateKey()
	if err != nil {
		log.Fatal(err)
	}

	nonce, err := Client.PendingNonceAt(context.Background(), crypto.PubkeyToAddress(privateKey.PublicKey))
	if err != nil {
		log.Fatal(err)
	}
	gasPrice, err := Client.SuggestGasPrice(context.Background())
	if err != nil {
		log.Fatal(err)
	}

	gasLimit := uint64(21000)
	amount := big.NewInt(10000000)
	var data []byte

	tx := types.NewTransaction(nonce, common.HexToAddress("0xfee66065C536A28000CfECF272A351592DA8473d"), amount, gasLimit, gasPrice, data)

	signedTx, err := types.SignTx(tx, types.NewEIP155Signer(big.NewInt(1)), privateKey)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(crypto.PubkeyToAddress(privateKey.PublicKey))
	fmt.Println(types.NewEIP155Signer(big.NewInt(1)).Sender(signedTx))
}

```

**Comment by holiman** [comment]
yeah, was just going to comment that this works fine for me:
```
func TestFoo(t *testing.T) {
	nonce := uint64(1)
	gasPrice := big.NewInt(10000)
	gasLimit := uint64(21000)
	amount := big.NewInt(10000000)
	var data []byte
	tx := types.NewTransaction(nonce, common.HexToAddress("0xfee66065C536A28000CfECF272A351592DA8473d"),
		amount, gasLimit, gasPrice, data)

	privateKey, _ := crypto.GenerateKey()
	signedTx, _ := types.SignTx(tx, types.NewEIP155Signer(big.NewInt(1)), privateKey)

	fmt.Println(crypto.PubkeyToAddress(privateKey.PublicKey))
	fmt.Println(types.NewEIP155Signer(big.NewInt(1)).Sender(signedTx))
}

```

**Comment by RickCastle2018** [comment]
@holiman Could you please answer one question? Can I consider V value of ESDSA signature always equal 1?

**Comment by holiman** [comment]
It's a bit outside my zone of comfort, but I think the answer is "No" -- it can be `0` or `1`, but depending on whether it's in canonical form or not, it can also be `27/28` on mainnet (different for other networks), if it's used for replay protection. 

What I mean by canonical form: The transaction `V` is  used for replay protection, but the actual `V` value that goes into the crypto libraries is 'canonicalized', and turned into `1` or `0`. 

I'm not really that crypto-savvy, so I may have gotten something wrong here.

**Comment by RickCastle2018** [comment]
> It's a bit outside my zone of comfort, but I think the answer is "No" -- it can be `0` or `1`, but depending on whether it's in canonical form or not, it can also be `27/28` on mainnet (different for other networks), if it's used for replay protection. 
> 
> What I mean by canonical form: The transaction `V` is  used for replay protection, but the actual `V` value that goes into the crypto libraries is 'canonicalized', and turned into `1` or `0`. 
> 
> I'm not really that crypto-savvy, so I may have gotten something wrong here.  

Thank you, now I understand it in general
