### ISSUE TITLE
clef not starting up - FS scan times

### ISSUE THREAD

**Issue by davidlp94** [ethereum/go-ethereum#24306]
#### System information

Geth version: 1.10.15-stable
OS & Version: Windows 10 64-bit
Commit hash : ?

#### Expected behaviour
following this guide : https://geth.ethereum.org/docs/getting-started
I typed" clef --keystore "C:\Users\dlpst\AppData\Local\Ethereum\keystore" --chainid 3"
Then, put in my password and got FS scan times repeated after IPC endpoint opened

#### Actual behaviour
FS scan times repeated
I've been trying to get this running for weeks - please help. I didn't think starting this up was this problematic.
Thank you. See code below!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#### Backtrace

```
dlpst@DESKTOP-2HEVIJ9 MINGW64 /c/Program Files/Geth
$ clef --keystore "C:\Users\dlpst\AppData\Local\Ethereum\keystore" --chainid 3

WARNING!

Clef is an account management tool. It may, like any software, contain bugs.

Please take care to
- backup your keystore files,
- verify that the keystore(s) can be opened with your password.

Clef is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE. See the GNU General Public License for more details.

Enter 'ok' to proceed:
> ok

INFO [01-28|13:10:29.661] Using CLI as UI-channel
INFO [01-28|13:10:29.779] Loaded 4byte database                    embeds=146,841 locals=0 local=./4byte-custom.json
## Master Password

Please enter the password to decrypt the master seed
>
-----------------------
INFO [01-28|13:10:34.682] Starting signer                          chainid=3 keystore=C:\Users\dlpst\AppData\Local\Ethereum\keystore light-kdf=false advanced=false
DEBUG[01-28|13:10:34.686] FS scan times                            list=0s set=0s diff=0s
DEBUG[01-28|13:10:34.713] Ledger support enabled
DEBUG[01-28|13:10:34.732] Trezor support enabled via HID
DEBUG[01-28|13:10:34.770] Trezor support enabled via WebUSB
INFO [01-28|13:10:34.775] Audit logs configured                    file=audit.log
DEBUG[01-28|13:10:34.782] IPCs registered                          namespaces=account
INFO [01-28|13:10:34.792] IPC endpoint opened                      url=\\.\pipe\clef.ipc
------- Signer info -------
* intapi_version : 7.0.1
* extapi_version : 6.1.0
* extapi_http : n/a
* extapi_ipc : \\.\pipe\clef.ipc
DEBUG[01-28|13:10:37.780] FS scan times                            list="826.6µs" set=0s diff=0s
DEBUG[01-28|13:10:40.787] FS scan times                            list=1.7327ms  set=0s diff=0s
DEBUG[01-28|13:10:43.794] FS scan times                            list="112.5µs" set="510.4µs" diff=0s
DEBUG[01-28|13:10:46.814] FS scan times                            list="212.8µs" set=0s        diff=0s
DEBUG[01-28|13:10:49.829] FS scan times                            list=1.1723ms  set=0s        diff=0s
DEBUG[01-28|13:10:52.846] FS scan times                            list="565.7µs" set=0s        diff=0s
DEBUG[01-28|13:10:55.855] FS scan times                            list=0s        set=0s        diff=0s
DEBUG[01-28|13:10:58.858] FS scan times                            list=0s        set=0s        diff=0s
DEBUG[01-28|13:11:01.867] FS scan times                            list="644µs"   set=0s        diff=0s
DEBUG[01-28|13:11:04.878] FS scan times                            list="137.2µs" set=0s        diff=0s
DEBUG[01-28|13:11:07.884] FS scan times                            list="546.7µs" set=0s        diff=0s
DEBUG[01-28|13:11:10.903] FS scan times                            list="124.4µs" set=0s        diff=0s
DEBUG[01-28|13:11:13.909] FS scan times                            list="649.7µs" set=0s        diff=0s
DEBUG[01-28|13:11:16.914] FS scan times                            list=0s        set=0s        diff=0s
DEBUG[01-28|13:11:19.919] FS scan times                            list=0s        set=0s        diff=0s
DEBUG[01-28|13:11:22.925] FS scan times                            list=0s        set=0s        diff=0s
DEBUG[01-28|13:11:25.939] FS scan times                            list=0s        set=0s        diff=0s
DEBUG[01-28|13:11:28.955] FS scan times                            list="544.5µs" set=0s        diff=0s
DEBUG[01-28|13:11:31.965] FS scan times                            list="109.7µs" set="511µs"   diff=0s
DEBUG[01-28|13:11:34.985] FS scan times                            list="504.6µs" set=0s        diff=0s
DEBUG[01-28|13:11:37.989] FS scan times                            list=0s        set="506.5µs" diff=0s
DEBUG[01-28|13:11:41.000] FS scan times                            list=0s        set=0s        diff=0s
DEBUG[01-28|13:11:44.010] FS scan times                            list=0s        set=0s        diff=0s
DEBUG[01-28|13:11:47.019] FS scan times                            list="543.1µs" set=0s        diff=0s
DEBUG[01-28|13:11:50.037] FS scan times                            list="580.8µs" set=0s        diff=0s
````

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
What are you expecting to happen? As far as I see it, Clef indeed did start up and is waiting for requests over the network or IPC.

**Comment by davidlp94** [comment]
> What are you expecting to happen? As far as I see it, Clef indeed did start up and is waiting for requests over the network or IPC.

Hi @karalabe thanks for the response. When I ran Clef, it was doing "FS scan times" for like 2-3 minutes then i stopped it. How long does that need to run for?

**Comment by karalabe** [comment]
That's just a debug log, not really important. It's started.

**Comment by karalabe** [comment]
@holiman Any particular reason for printing the file system scan times?

**Comment by davidlp94** [comment]
@karalabe thank you again for the response. so i just ran clef again and it just keeps on giving me that fs scan times message over and over again...according to the documentation; my next step is to run "geth --goerli --syncmode "light" --http --signer=<CLEF_LOCATION>/clef.ipc" from https://geth.ethereum.org/docs/getting-started......in this case i want to sync ropsten...but it isnt even allowing me to type anything as it just keeps on giving me that fs scan times message over and over againwhat am i doing wrong?

**Comment by davidlp94** [comment]
@karalabe any update to this sir? how long should FS scan times run for? i cannot type anything as it just repeats

**Comment by davidlp94** [comment]
@karalabe @holiman  any update to this? I really want to get this up and running

**Comment by holiman** [comment]
Clef is one process, geth is another. You need to run both. You've started clef, now open a new terminal and start geth

**Comment by davidlp94** [comment]
@holiman @karalabe awesome thanks! now can you help me please find where clef.ipc is? i searched my folder and only found clef.exe in my geth folder and go bin? nowhere else? I'm typing this command but getting this error:

"$ geth --ropsten --syncmode "snap" --http --signer="C:/Program Files/Geth/clef.ipc""

![image](https://user-images.githubusercontent.com/96163075/152089144-4857890c-c9ea-48bb-9200-45cc240caeed.png)

thanks in advance

**Comment by davidlp94** [comment]
@karalabe @holiman  it says that my clef url is "url=\\.\pipe\clef.ipc" ??? what does that mean? i cant find that anywhere. do i paste that in "<clef_location> in the command "geth --ropsten --syncmode "snap" --http --signer=<CLEF_LOCATION>/clef.ipc

**Comment by karalabe** [comment]
On windows the IPC endpoint does not look like a regular file, it has that weird path. `\\.\pipe\clef.ip`, just pass that to Geth.

**Comment by davidlp94** [comment]
@karalabe hi there. thank you - can you elaborate a bit? what exactly should i be typing in the clef location above? my geth path location? because that doesnt work. there is no clef.ipc in my geth path. Please let me know what i should type in "geth --ropsten --syncmode "snap" --http --signer=<CLEF_LOCATION>/clef.ipc"

thank you

**Comment by karalabe** [comment]
`\\.\pipe\clef.ipc`

**Comment by davidlp94** [comment]
I did that and still got an error? what am i ytping wrong @karalabe ? thanks in advance
![image](https://user-images.githubusercontent.com/96163075/152203681-52a4235a-09b8-47c7-98e3-0d7e673f6142.png)

**Comment by davidlp94** [comment]
I also tried the following @karalabe 
![image](https://user-images.githubusercontent.com/96163075/152203943-7f8bd361-f534-487c-bb8c-29713a288688.png)

**Comment by davidlp94** [comment]
@karalabe okay wow got it to work - i had to type "\\\.\pipe\clef.ipc" with three backslahes? not sure why - the full string should have been passed in the quotes. chain is now syncing thanks!

**Comment by davidlp94** [comment]
@karalabe @holiman hello again - following the documentation here but hitting an error on finding the balance for the wallet?/ it says the method eth_getBalance does not exist/is not avalable? I typed it exactly as it says in the docs? can i ask what am i doing wrong? what should i type instead? why is the instructions documents wrong? please and thank you....
![image](https://user-images.githubusercontent.com/96163075/152262205-4ccdc7cc-131e-40b7-b5c0-c3ee5408a22e.png)

**Comment by davidlp94** [comment]
@karalabe @holiman hey guys - appreciate the help here - can you provide guidance as to why the command exactly shown in the documents is gving me an error screenshotted above?

**Comment by davidlp94** [comment]
@karalabe @holiman hey there. Any idea why the above command isnt working?

**Comment by holiman** [comment]
@davidlp94 is that the `console` (as in `geth ...args.. console`) or the remote-console (as in `geth attach http://localhost:8545`)? If it's the latter, might be that you haven't exposed the `eth` rpc service? What modules does it say is available in the console welcome message?

**Comment by holiman** [comment]
Original issue (and most secondary issues?) answered, closing

**Comment by baibinghere** [comment]
> On windows the IPC endpoint does not look like a regular file, it has that weird path. `\\.\pipe\clef.ipc`, just pass that to Geth.

This should **definitely** be noted in the [documentation](https://geth.ethereum.org/docs/getting-started).
