### ISSUE TITLE
eth.sendTransaction :  Error: invalid sender

### ISSUE THREAD

**Issue by huluBrother** [ethereum/go-ethereum#24308]
I have a private chain, I run it 
```
geth --datadir ./data --networkid 9517 console 2> out.log
```

when I transacion, I got follow error,
```
> eth.sendTransaction({from:eth.accounts[0],to:"0x2027EBDFbAD5E527E5c7403db222ABe94E3Ab20d", value: web3.toWei(3,"ether")})
Error: invalid sender
	at web3.js:6365:37(47)
	at send (web3.js:5099:62(35))
	at <eval>:1:20(18)
```

geth version 
```
Version: 1.10.15-stable
Architecture: arm64
Go Version: go1.17.5
Operating System: darwin
GOPATH=
GOROOT=go
```

I need your help

**Comment by ligi** [comment]
can you show your genesis?

**Comment by karalabe** [comment]
There are a variety of upgrades made to Ethereum and some of them influence signatures. Although Geth will try to be somewhat backward compatible to old configs, there are only so far we can take that. Please make sure your chain has the published forks enabled.

**Comment by huluBrother** [comment]
> There are a variety of upgrades made to Ethereum and some of them influence signatures. Although Geth will try to be somewhat backward compatible to old configs, there are only so far we can take that. Please make sure your chain has the published forks enabled.



> can you show your genesis?

Happy New Years. 

I already know the reason. My `genesis.json` file is not fully written

**Comment by lukelu0520** [comment]
@huluBrother We got the same issue, hope to learn your working gensis.json, especially, the line you added to fix the issue. Thanks !
