### ISSUE TITLE
New location for legacy tests

### ISSUE THREAD

**Issue by Zachinquarantine** [ethereum/go-ethereum#24312]
In the version of [ethereum/tests](https://github.com/ethereum/tests/tree/develop) currently used by Geth, the legacy tests are stored as a folder in the main test repo. In the newest version, they are in a seperate repo ([ethereum/legacytests](https://github.com/ethereum/legacytests/tree/master)). This actually causes the CI [to fail](https://ci.appveyor.com/project/ethereum/go-ethereum/builds/42383846/job/s7k3tsgqhkao7ykd) when using the new version, which blocks PRs such as #23570, which relies on the new version of the tests repo.
Version used by Geth: 
![slika](https://user-images.githubusercontent.com/69423184/151682911-f08489ff-5462-44c4-92c2-3db6f64153e3.png)

New version:
![slika](https://user-images.githubusercontent.com/69423184/151682924-6e61d7ea-a7ac-4321-972d-85beb302c804.png)

I've found [the line](https://github.com/ethereum/go-ethereum/blob/master/tests/init_test.go#L40) that is causing this problem, but I don't know how to update it so it's pointing to a submodule and not a folder.

**Comment by holiman** [comment]
Yes, this is something we must fix. Not urgent, but definitely
