### ISSUE TITLE
Whitelist terms need to be changed 

### ISSUE THREAD

**Issue by antonio-fr** [ethereum/go-ethereum#24322]
Geth version: v1.10.15
OS & Version: All OS
Commit hash : 9da25c5db79afdfbbae8654144f3426777538b53

Following [this change](https://github.com/ethereum/go-ethereum/commit/523866c2ccbfd75ee88b309167cdba7311ba9695), the "white list" terms must be removed and changed, in order to avoid many protests and the growing social unrest. The Ethereum ecosystem already stepped in the right direction, but the path is not fully complete. This white list is offensive to some people and we empathize with those hurt by the use of that term. This terminology must be replaced. The tech industry should keep moving to a more inclusive, open culture, and this is an important step in this journey. While it takes time to make these changes now, it's a one-time engineering cost that will have lasting impacts, both internally and externally. We know inclusive language is just as much about how we code and what we build as it is about person-to-person interactions. I propose to change _Whitelist_ by _ApprovedList_ or _AllowList_.

See https://github.com/ethereum/go-ethereum/search?q=whitelist for a set of change required.

**Comment by karalabe** [comment]
If you have suggestions, feel free to explicitly suggest them for each use case in our code base in a backward compatible way. Neither AllowList not ApptovedList captures the semantics of Whitelist at many locations. I'm all for making things more inclusive, as long as they are accurate changes and not just virtue signalling.
