### ISSUE TITLE
eth_estimateGas doesn't honor gas parameter

### ISSUE THREAD

**Issue by deepakbnsl** [ethereum/go-ethereum#24329]
#### System information

Geth Version: 1.10.15-stable
Git Commit: 8be800ffa9c4992666e2620e0ab4725a1a83352b
Architecture: amd64
Go Version: go1.17.5
Operating System: linux

#### Expected behaviour

Should fail with "low gas error" since gas cap parameter specified has a low value.

#### Actual behaviour

Call succeeds with result much higher than specified gas cap in request.

#### Steps to reproduce the behaviour

{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_estimateGas",
  "params": [
    {
      "data": "0x313ce567",
      "to": "0x99d8a9c45b2eca8864373a26d1459e3dff1e17f3",
      "gas": "0x1"
    },
    "latest"
  ]
}

![image](https://user-images.githubusercontent.com/96074752/152253806-73ad3378-ba36-4b04-b025-2d0b78947a56.png)

For **comparison**, eth_call returns error for this scenario (shown below):

![image](https://user-images.githubusercontent.com/96074752/152261133-f1c84834-5320-407b-a5f0-efd9900b7847.png)
 

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
Currently if you specify less than 21000 it will just ignore it and revert to the block gas limit. Any particular reason for supplying 1 and expecting a meaningful failure?

**Comment by deepakbnsl** [comment]
Thanks @karalabe looking into it! I was using 1 just to test gas parameter. BTW, What is special about 21000 here?

**Comment by eliane345** [comment]
Desculpe pelo transtorno

**Comment by rjl493456442** [comment]
@deepakbnsl The minimal gas usage of ethereum transaction is 21,000.

**Comment by eliane345** [comment]
> #### System information
> 
> Geth Version: 1.10.15-stable
> Git Commit: 8be800ffa9c4992666e2620e0ab4725a1a83352b
> Architecture: amd64
> Go Version: go1.17.5
> Operating System: linux
> 
> #### Expected behaviour
> 
> Should fail with "low gas error" since gas cap parameter specified has a low value.
> 
> #### Actual behaviour
> 
> Call succeeds with result much higher than specified gas cap in request.
> 
> 
> #### Steps to reproduce the behaviour
> 
> {
>   "id": 1,
>   "jsonrpc": "2.0",
>   "method": "eth_estimateGas",
>   "params": [
>     {
>       "data": "0x313ce567",
>       "to": "0x99d8a9c45b2eca8864373a26d1459e3dff1e17f3",
>       "gas": "0x1"
>     },
>     "latest"
>   ]
> }
> 
> 
> ![image](https://user-images.githubusercontent.com/96074752/152253806-73ad3378-ba36-4b04-b025-2d0b78947a56.png)
> 
> 
> 
> 
> 
> For **comparison**, eth_call returns error for this scenario (shown below):
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/96074752/152261133-f1c84834-5320-407b-a5f0-efd9900b7847.png)
>  
> 
> #### Backtrace
> 
> ````
> [backtrace]
> ````
> 
> When submitting logs: please submit them as text and not screenshots.

Este email não explicando do que se trata exatamente
 E também não consigo ter acesso a ánenhum ganho não entrhdo7a
