### ISSUE TITLE
personal_unlockAccount does not work on develop

### ISSUE THREAD

**Issue by tinybike** [ethereum/go-ethereum#2433]
#### System information

Geth version: 1.4.0-unstable
OS & Version: Xubuntu 14.04
Commit hash : 7e02105672cda92889a78db864a5701d78f45eb2

#### Expected behaviour

```
{"jsonrpc":"2.0","id":5,"result":true}
```
(This is what happens on master.)

#### Actual behaviour

```
{"jsonrpc":"2.0","id":5,"error":{"code":-32602,"message":"json: cannot unmarshal string into Go value of type int"}}
```
(This is what happens on develop.)

#### Steps to reproduce the behaviour

```
$ geth --testnet --cache 2048 --rpc --rpcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --etherbase 0x15f6400a88fb320822b689607d425272bea2175f
$ curl -X POST --data '{"id":5,"jsonrpc":"2.0","method":"personal_unlockAccount","params":["0x15f6400a88fb320822b689607d425272bea2175f","0x6f68206869","0x1"]}' http://localhost:8545
```

**Comment by obscuren** [comment]
Thanks for reporting the issue. We'll look in to this asap.

**Comment by bas-vk** [comment]
This is addressed in https://github.com/ethereum/go-ethereum/pull/2359

**Comment by ethers** [comment]
#2359 has been merged to develop...  so this can be closed?

**Comment by fjl** [comment]
We will close it when the final release of geth 1.4 is out.
