### ISSUE TITLE
Sync modes - not clear

### ISSUE THREAD

**Issue by ronytesler** [ethereum/go-ethereum#24334]
from:
https://geth.ethereum.org/docs/getting-started

"Snap (Default): Same functionality as fast, but with a faster algorithm."

What do you mean by "as fast"? Should it be "as Full"?

**Comment by karalabe** [comment]
Fast sync was the previous generation sync algo. It has been removed altogether a couple releases ago. The docs should be updated not to mention fast sync any more.
