### ISSUE TITLE
Piping password for masterseed errors OEF

### ISSUE THREAD

**Issue by waifro** [ethereum/go-ethereum#24352]
similar issue of #21086 referencing to pull request #20960

#### System information
Ubuntu Server 20.04.3 LTS | amd64
geth version: 1.10.15-stable

#### Expected behaviour
When piping with different ways the password, it should start operating and decrypt the Master seed.

#### Actual behaviour
When piping with different ways the password, it prompts error `Failed to read password    error: EOF`

#### Steps to reproduce the behaviour
for sake of request here's few of the multiple ways i tried but without success.
- `{ echo "ok"; echo "password123"; } | clef` 
- `echo "ok\npassword123" | clef`
- `{ echo "ok"; echo "password123"; } | clef`
- `echo "password123" | clef --stdio-ui` 
( about the `stdio-ui` lacks of documentation, so i dont know how it should work. )

**Comment by holiman** [comment]
You should not use `stdio-ui`, unless you want to speak json-rpc with it. Try ` echo "password123" | clef --suppress-bootwarn` for your usecase. I think the case where you pipe two things like that doesn't work like you expect it to

**Comment by waifro** [comment]
Testing now with  `echo "password123" | clef --suppress-bootwarn` as you requested, seems to be working.
Correct me if im wrong, but from a totally not-an-expert view, suppressing warnings isn't a fix, isn't it?

**Comment by holiman** [comment]
It's not suppressing warnings in general, it just squelches the initial boot-up message/warning.
From a security PoW though, it's piping passwords is usually not great, and typically means you're doing something that might not be very secure. 
For programmatical interactions, e.g. if someone wants to build a nice UI for clef, it's better to use stdio-ui than trying to do interactions with json instead of the cli meant for humans.

**Comment by holiman** [comment]
> about the stdio-ui lacks of documentation

Docs here: 
https://github.com/ethereum/go-ethereum/tree/master/cmd/clef#ui-api

Changelog here: 
https://github.com/ethereum/go-ethereum/blob/master/cmd/clef/intapi_changelog.md

**Comment by waifro** [comment]
thankyou very much for the explanation. Since i couldn't find any source redirecting to the JSON-RPC (specially for the `stdio-ui`), i was looking for alternatives or more specifically, a secure way to unlock the masterseed. With the JSON-RPC looks good for my needs. 

Thankyou again ^^
