### ISSUE TITLE
fields["logs"] incorrectly set

### ISSUE THREAD

**Issue by nuliknol** [ethereum/go-ethereum#24368]
isn't this a bug?

internal/ethapi/api.go , line 1660
```
    if receipt.Logs == nil {
        fields["logs"] = [][]*types.Log{}
    }  
```
the fields["logs"] must be of type `[]*types.Log[]`, not `[][]*types.Log` , i.e. it must be single array, not double array:

as in receipt.go:

```
 type Receipt struct {
....
    Logs              []*Log `json:"logs"              gencodec:"required"`
....
}
```

this is in 1.10.15 (released code tarball)

**Comment by holiman** [comment]
Nice catch! It's indeed a bug, and it's been there at least 5 years. However, since the slice is empty, it doesn't matter what the type is, in this case. So it's wrong and we should fix it, but in practice it's of no consequence.
