### ISSUE TITLE
Wrong name of keystore folder

### ISSUE THREAD

**Issue by larspensjo** [ethereum/go-ethereum#2436]
#### System information

Geth version: 1.3.6
OS & Version: Ubuntu
Commit hash : master

#### Expected behaviour
```get account help``` Says that keys are stored in \<DATADIR\>/keystore.

#### Actual behaviour
```get account help``` Says that keys are stored in \<DATADIR\>/keys.

#### Steps to reproduce the behaviour
Run the command ```get account help```.

**Comment by obscuren** [comment]
Thank you. I can confirm this

**Comment by fjl** [comment]
I will fix it in #2284.

**Comment by fjl** [comment]
I forgot to make the change.

**Comment by obscuren** [comment]
@fjl was this addressed after all?
