### ISSUE TITLE
Documentation does not mention units in gensis block JSON

### ISSUE THREAD

**Issue by wbl** [ethereum/go-ethereum#24371]
I got bitten by this after my allowances were many orders of magnitude too low. It would be nice if for every value the unit was described in the documentation.

**Comment by holiman** [comment]
Sure, we might accept a clarification somewhere. In general, the entire codebase, a `value` always use the smallest possible unit: `wei`. I'll close this ticket though, but feel free to make a PR if there's anything in particular you think deserves clarification.

**Comment by wbl** [comment]
It's not just money, but also times.
