### ISSUE TITLE
GraphQL API should contain EIP-1559 London Hardfork methods

### ISSUE THREAD

**Issue by amyodov** [ethereum/go-ethereum#24386]
# Rationale

GraphQL API should contain everything necessary to create the transactions - such as, a GraphQL analog/endpoint to `eth_feeHistory`, but also probably other methods.

**Why should this feature exist?**
Without this, the GraphQL API is not feature-complete and does not let you to create the transactions in post-EIP-1559 way. No way to get the real estimate what gas to use.

**What are the use-cases?**
Using Geth through GraphQL only, without resorting to JSON-RPC.

# Implementation

**Do you have ideas regarding the implementation of this feature?**
No.

**Are you willing to implement this feature?**
No, but will happily test it out.

**Comment by s1na** [comment]
@amyodov can you try the script provided with #24452 to see if that fits your need?

**Comment by amyodov** [comment]
@s1na , I am not that much of a Gopher :( And our infrastructure (where geth GraphQL is used, and which helps me to notice various GraphQL inconsistencies and shortages) uses the geth releases only, not the self-built prereleases; so I have to wait till any next geth release to try any new GraphQL changes, unfortunately.
But I will definitely have a look at them and try to use them as soon as they are added.
