### ISSUE TITLE
Fresh install with 2TB external SSD giving `Low disk space` warning

### ISSUE THREAD

**Issue by humblecoder** [ethereum/go-ethereum#24390]
#### System information

Geth version: `1.10.15-stable`
OS & Version: `Ubuntu Server 21.10` `aarch64`
Hardware: `Raspberry Pi 4 (4GB)`

#### Expected behaviour
No warning

#### Actual behaviour
```Low disk space. Gracefully shutting down Geth to prevent database corruption.```

#### GETH launch command
```geth --datadir /media/ext2tb --nat=extip:$IP_ADDRESS --port 54123 --syncmode snap --cache=1024 --ws --ws.api eth,web3,debug,txpool,net,admin,debug --ws.origins "*"  --http.api eth,web3,debug,txpool,net,admin,debug --http --metrics --maxpeers 30 --light.maxpeers 30 --http.corsdomain "*" --http.vhosts "*" --mainnet```

#### Steps to reproduce the behaviour
- Install GETH on Raspberry Pi 4 (4GB), 32GB microSD
- Configure external 2TB SSD
- Mount SSD and adjust permissions accordingly
- GETH runs as expected and writes to external SSD until it hits seemingly random (very low `16GB, 30GB, 17GB`) storage amounts, eventually receiving the error:  ```Low disk space. Gracefully shutting down Geth to prevent database corruption.```

I've completely wiped and reconfigured 3 times today without resolution.  I've also tested multiple SSDs.  My hope is I'm simply missing a configuration piece.  Please advise.

**Comment by holiman** [comment]
What does `df -h` tell you? 
I suspect that `/media` is a folder on your root, and the disk low-space detector thus incorrectly bases the judgement on the remaining size of the root partition, regardless of the size on the ext2b partition.  
The detector isn't perfect (other problems may occur if your datadir is a network-attached partition, or softlinked), so if you just want to disable this functionality, use this: 
```
$ geth -h | grep .minfreedisk
  --datadir.minfreedisk value         Minimum free disk space in MB, once reached triggers auto shut down (default = --cache.gc converted to MB, 0 = disabled)
```
so just `geth ..args... --datadir.minfreedisk=0` and it should be ok.
