### ISSUE TITLE
Compilation failing due to change in Azure library

### ISSUE THREAD

**Issue by lovishpuri** [ethereum/go-ethereum#24396]
Compilation errors due to change in Azure library "github.com/Azure/azure-storage-blob-go/azblob"

In /build/ci.go : func doPurge()

Line 1241:    blobs[i].Name undefined (type invalid type has no field or method Name)

In /internal/build/azure.go

line 73:    BlobItem not declared by package 

And others ....

**Comment by karalabe** [comment]
The Geth + build dependencies are pinned in `go.mod` and verified in `go.sum`, so you shouldn't get a different version, unless your build command is somehow ignoring the module file. If you use an older version of Go please update or run with `GO111MODULE=on` env var.

**Comment by Raihan1y** [comment]
> Compilation errors due to change in Azure library "github.com/Azure/azure-storage-blob-go/azblob"
> 
> In /build/ci.go : func doPurge()
> 
> Line 1241: blobs[i].Name undefined (type invalid type has no field or method Name)
> 
> In /internal/build/azure.go
> 
> line 73: BlobItem not declared by package
> 
> And others ....

**Comment by karalabe** [comment]
The Azure libraries have been bumped to latest on master.
