### ISSUE TITLE
address generated via json-rpc ->personal_newAccount should be EIP-55 encoded

### ISSUE THREAD

**Issue by benbaley** [ethereum/go-ethereum#24406]
Wouldn't it be better to return the address with checksum？

**Comment by holiman** [comment]
Yes, I agree

**Comment by alexmylonas** [comment]
> @alexmylonas are working on this issue? if not please tell me then I can begin on your work :)

Yeap just pushed a commit addressing PR's feedback!

**Comment by makinje16** [comment]
Scrolling through "good first issues" and it looks like this issue was fixed with the merge of #26973. Can this be closed now?

**Comment by holiman** [comment]
> Can this be closed now?

Yup, thanks!
