### ISSUE TITLE
Payload status is `VALID` whilst `latestBlockHash` is `null`

### ISSUE THREAD

**Issue by paulhauner** [ethereum/go-ethereum#24404]
#### System information

This refers to @MariusVanDerWijden's repo: https://github.com/MariusVanDerWijden/go-ethereum/commit/af18ae1b488f05bd49ec7a6bcc40e525e35c9b19

I can't open an issue there, I hope it's appropriate here :pray: 

#### Expected behaviour

According to the [v1.0.0-alpha.6 api specs](https://github.com/ethereum/execution-apis/blob/v1.0.0-alpha.6/src/engine/specification.md), an EE should always include a non-null `latestValidHash` when issuing a VALID response to`engine_forkchoiceUpdatedV1`:

> {payloadStatus: {status: VALID, latestValidHash: forkchoiceState.headBlockHash, validationError: null}, payloadId: null} if the payload is deemed VALID and a build process hasn't been started
> {payloadStatus: {status: VALID, latestValidHash: forkchoiceState.headBlockHash, validationError: null}, payloadId: buildProcessId} if the payload is deemed VALID and the build process has begun.

#### Actual behaviour

From geth, I'm observing the following response (sorry about the weird Rust formatting):

```rust
{
    jsonrpc: "2.0",
    error: None,
    result: Object({
        "payloadId": Null,
        "payloadStatus": Object({
            "latestValidHash": Null,
            "status": String(
                "VALID",
            ),
            "validationError": Null,
        }),
    }),
    id: 1,
}
```

Basically, the problem is that `status == "VALID" && latestValidHash == null`.

I'm seeing this after we've:

- produced a payload
- run `notify_new_payload` for that payload
- run `notify_forkchoice_updated` for the hash from that payload.

I don't specifically need the `latestValidHash` here, I just thought you might want to know :)

#### Steps to reproduce the behaviour

Our integration tests are failing here: https://github.com/paulhauner/lighthouse/blob/21455917fe605338204076f1df9f75684444a283/testing/execution_engine_integration/src/test_rig.rs#L201

In the root of the lighthouse repo (on the above commit), run the tests with:

```
make test-exec-engine
```

Flip [this bool](https://github.com/paulhauner/lighthouse/blob/21455917fe605338204076f1df9f75684444a283/testing/execution_engine_integration/src/lib.rs#L12) to get geth logs in the test output.

**Comment by paulhauner** [comment]
Here's a snippet of the conversation between LH and geth:

```
to_geth = JsonRequestBody {
    jsonrpc: "2.0",
    method: "engine_newPayloadV1",
    params: Array([
        Object({
            "baseFeePerGas": String(
                "0x7",
            ),
            "blockHash": String(
                "0x4956256f2c2340bea6f6fe112922c3fe5d7b59d05936d27a190cd2290c979393",
            ),
            "blockNumber": String(
                "0x1",
            ),
            "extraData": String(
                "0x",
            ),
            "feeRecipient": String(
                "0x0000000000000000000000000000000000000001",
            ),
            "gasLimit": String(
                "0x1c95111",
            ),
            "gasUsed": String(
                "0x0",
            ),
            "logsBloom": String(
                "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
            ),
            "parentHash": String(
                "0x3b8fb240d288781d4aac94d3fd16809ee413bc99294a085798a589dae51ddd4a",
            ),
            "random": String(
                "0x0000000000000000000000000000000000000000000000000000000000000000",
            ),
            "receiptsRoot": String(
                "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
            ),
            "stateRoot": String(
                "0xca3149fa9e37db08d1cd49c9061db1002ef1cd58db2210f2115c8c989b2bdf45",
            ),
            "timestamp": String(
                "0x620c9c22",
            ),
            "transactions": Array([]),
        }),
    ]),
    id: 1,
}
```
```
from_geth = JsonResponseBody {
    jsonrpc: "2.0",
    error: None,
    result: Object({
        "latestValidHash": String(
            "0x4956256f2c2340bea6f6fe112922c3fe5d7b59d05936d27a190cd2290c979393",
        ),
        "status": String(
            "VALID",
        ),
        "validationError": Null,
    }),
    id: 1,
}
```
```
to_geth = JsonRequestBody {
    jsonrpc: "2.0",
    method: "engine_forkchoiceUpdatedV1",
    params: Array([
        Object({
            "finalizedBlockHash": String(
                "0x0000000000000000000000000000000000000000000000000000000000000000",
            ),
            "headBlockHash": String(
                "0x4956256f2c2340bea6f6fe112922c3fe5d7b59d05936d27a190cd2290c979393",
            ),
            "safeBlockHash": String(
                "0x4956256f2c2340bea6f6fe112922c3fe5d7b59d05936d27a190cd2290c979393",
            ),
        }),
        Null,
    ]),
    id: 1,
}
```
```
from_geth = JsonResponseBody {
    jsonrpc: "2.0",
    error: None,
    result: Object({
        "payloadId": Null,
        "payloadStatus": Object({
            "latestValidHash": Null,
            "status": String(
                "VALID",
            ),
            "validationError": Null,
        }),
    }),
    id: 1,
}
```

**Comment by MariusVanDerWijden** [comment]
Thanks for the report! I added a commit on top of `merge-kiln` which should fix this.
Could you rerun your tests?

**Comment by MariusVanDerWijden** [comment]
Hmm just tried to run your tests, but they still fail for me. Don't really know why, there shouldn't be a case where we return null anymore. How can I see the messages between geth and lh?

**Comment by paulhauner** [comment]
Oh great, thanks for that! I'll try our tests again, they're might not be using the correct version.

I'll post my findings here :)

**Comment by paulhauner** [comment]
Alrighty, your latest commit is passing on our end!

There were some other failures due to us expecting `SYNCING` but getting `ACCEPTED`. It doesn't really matter which of those we get, so I've just updated our tests to expect what you give us. It'll be interesting to see what other EE impls do when we introduce them. I suspect we'll just have to accept `SYNCING` or `ACCEPTED` in some scenarios :thinking: 

I think we can consider this issue resolved :tada: I'll close the issue, feel free to reopen if you like.
