### ISSUE TITLE
make: *** [geth] error 2

### ISSUE THREAD

**Issue by sirishkalidindi** [ethereum/go-ethereum#2442]
#### System information

Geth version: `geth version`
OS & Version: ubuntu 14.04
Commit hash : (if `develop`)

build/env.sh go install -v -ldflags '-X main.gitCommit=9e323d65b20c32ab1db40e8dde7172826e0e9c45' -tags opencl ./cmd/geth
github.com/codegangsta/cli
github.com/Gustav-Simonsson/go-opencl/cl
github.com/ethereum/go-ethereum/rlp
github.com/ethereum/go-ethereum/crypto/ecies
github.com/ethereum/go-ethereum/crypto/sha3
github.com/ethereum/go-ethereum/crypto/randentropy
github.com/ethereum/go-ethereum/common
github.com/ethereum/go-ethereum/crypto/secp256k1
github.com/pborman/uuid
golang.org/x/crypto/pbkdf2
golang.org/x/crypto/ripemd160
golang.org/x/crypto/scrypt
github.com/ethereum/go-ethereum/logger/glog
github.com/ethereum/go-ethereum/logger
github.com/ethereum/go-ethereum/params
github.com/hashicorp/golang-lru
github.com/rcrowley/go-metrics
github.com/syndtr/goleveldb/leveldb/util
github.com/syndtr/goleveldb/leveldb/cache
github.com/syndtr/goleveldb/leveldb/comparer
github.com/syndtr/goleveldb/leveldb/storage
github.com/syndtr/goleveldb/leveldb/errors
github.com/syndtr/goleveldb/leveldb/filter
github.com/syndtr/goleveldb/leveldb/iterator
github.com/syndtr/goleveldb/leveldb/journal
github.com/syndtr/goleveldb/leveldb/memdb
github.com/ethereum/go-ethereum/metrics
github.com/syndtr/goleveldb/leveldb/opt
github.com/syndtr/gosnappy/snappy
gopkg.in/karalabe/cookiejar.v2/collections/prque
github.com/ethereum/go-ethereum/event
github.com/syndtr/goleveldb/leveldb/table
gopkg.in/fatih/set.v0
github.com/huin/goupnp/httpu
github.com/syndtr/goleveldb/leveldb
# github.com/Gustav-Simonsson/go-opencl/cl
/usr/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status
github.com/huin/goupnp/scpd
github.com/huin/goupnp/soap
github.com/huin/goupnp/ssdp
golang.org/x/net/html/atom
golang.org/x/net/html
golang.org/x/text/transform
golang.org/x/text/encoding
golang.org/x/text/encoding/internal/identifier
golang.org/x/text/encoding/internal
golang.org/x/text/encoding/charmap
golang.org/x/text/encoding/japanese
github.com/ethereum/go-ethereum/ethdb
golang.org/x/text/encoding/korean
golang.org/x/text/encoding/simplifiedchinese
golang.org/x/text/encoding/traditionalchinese
golang.org/x/text/encoding/unicode
github.com/jackpal/go-nat-pmp
github.com/ethereum/go-ethereum/event/filter
github.com/robertkrimen/otto/file
github.com/robertkrimen/otto/token
github.com/robertkrimen/otto/ast
github.com/robertkrimen/otto/dbg
github.com/robertkrimen/otto/registry
github.com/ethereum/go-ethereum/rpc/shared
github.com/robertkrimen/otto/parser
github.com/ethereum/go-ethereum/rpc/codec
golang.org/x/net/html/charset
github.com/rs/cors
github.com/peterh/liner
github.com/huin/goupnp
github.com/robertkrimen/otto
github.com/huin/goupnp/dcps/internetgateway1
github.com/huin/goupnp/dcps/internetgateway2
github.com/mattn/go-isatty
github.com/shiena/ansicolor
github.com/fatih/color
github.com/mattn/go-runewidth
github.com/ethereum/go-ethereum/p2p/nat
github.com/nsf/termbox-go
github.com/gizak/termui
github.com/ethereum/go-ethereum/crypto
github.com/ethereum/go-ethereum/core/vm
github.com/ethereum/go-ethereum/trie
github.com/ethereum/go-ethereum/accounts
github.com/ethereum/go-ethereum/common/compiler
github.com/ethereum/go-ethereum/common/httpclient
github.com/ethereum/go-ethereum/p2p/discover
github.com/ethereum/go-ethereum/common/registrar
github.com/ethereum/go-ethereum/rpc/useragent
github.com/ethereum/go-ethereum/core/types
github.com/ethereum/go-ethereum/core/state
github.com/ethereum/go-ethereum/p2p
github.com/ethereum/go-ethereum/rpc/comms
github.com/ethereum/go-ethereum/pow
github.com/ethereum/go-ethereum/core
github.com/ethereum/go-ethereum/eth/downloader
github.com/ethereum/go-ethereum/jsre
github.com/ethereum/go-ethereum/whisper
github.com/ethereum/go-ethereum/eth/fetcher
github.com/ethereum/go-ethereum/eth/filters
make: *** [geth] Error 2

**Comment by karalabe** [comment]
If you want OpenCL GPU minding included (`--tags opencl`), you need the appropriate OpenCL libraries installed on your OS, as stated by the error message above:

```
/usr/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status
```
