### ISSUE TITLE
Rinkeby Faucet: No Ethereum address found to fund

### ISSUE THREAD

**Issue by srinivasmaguluri** [ethereum/go-ethereum#24429]
Hi, I'm having issues with requesting funds from Rinkeby Faucet using a facebook post. It keeps saying "No Ethereum address found to fund". I need the finds to learn solidity. Can someone please add 10 Ethers to the following address?

0x4d594109a723B70D39ea59b78e61c70D1C4f760d

**Comment by Rebka5** [comment]
Hello user have you been able to solve the issues

**Comment by srinivasmaguluri** [comment]
> Hello user have you been able to solve the issues

No, I'm still having issues.

**Comment by ligi** [comment]
you can use https://fauceth.komputing.org/

**Comment by srinivasmaguluri** [comment]
> you can use https://fauceth.komputing.org/

It worked, Thank you very much!
