### ISSUE TITLE
The `latest_block_hash` must be `null` when status is `SYNCING`

### ISSUE THREAD

**Issue by paulhauner** [ethereum/go-ethereum#24422]
#### System information

This refers to @MariusVanDerWijden's repo: https://github.com/MariusVanDerWijden/go-ethereum/commit/af18ae1b488f05bd49ec7a6bcc40e525e35c9b19

*Note: this is a similar but different issue to #24404.*

#### Expected behaviour

The [v1.0.0-alpha.6 api specs](https://github.com/ethereum/execution-apis/blob/v1.0.0-alpha.6/src/engine/specification.md) decares that a `new_payload` response must have `latestValidHash == null` when `status == SYNCING`:

> - {status: SYNCING, latestValidHash: null, validationError: null} if the payload extends the canonical chain and requisite data for its validation is missing

#### Actual behaviour

When syncing [`merge-devnet-4`](https://notes.ethereum.org/D5xK4XrmTb6MKGudf_hcrg?view) Lighthouse is giving me:

```
new_payload: response does not conform to engine API spec: PayloadStatusV1 { status: Syncing, latest_valid_hash: Some(0xa28d8d73e087a01d09d8cb806f60863652f30b6b6dfa4e0157501ff07d422399), validation_error: None }
```

It appears that Geth is sending a non-null `latestValidHash` with the SYNCING response.

#### Steps to reproduce the behaviour

I found this whilst syncing [`merge-devnet-4`](https://notes.ethereum.org/D5xK4XrmTb6MKGudf_hcrg?view) with Lighthouse on the `unstable` branch and Geth on `merge-kiln`.

It synced for a while at first, so I'm not exactly sure how to reproduce it. Happy to look into it more if you need :)

**Comment by MariusVanDerWijden** [comment]
Sorry for the delay, I fixed it now, please re-check with the latest commit

**Comment by paulhauner** [comment]
> Sorry for the delay, I fixed it now, please re-check with the latest commit

I can confirm this has been fixed.
