### ISSUE TITLE
Net_version 401 error

### ISSUE THREAD

**Issue by kornik1** [ethereum/go-ethereum#24435]
Hey, i'm doing an assessement for my job interview, although im new into the space.
I got this as a task and I'm not sure if i'm doing it the right way.

Client's query:

I'm getting 401 with the following request:

curl 'https://nd-123-456-789.p2pify.com/3c6e0b8a9c15224a8228b9a98ca1531d' -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"net_version","params":[],"id":0}'

After researching internet, i think it should go like this:

curl 'https://nd-123-456-789.p2pify.com/3c6e0b8a9c15224a8228b9a98ca1531d' -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":1}'

or
 
curl -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":1}'

Could anyone help or give any hints?

**Comment by s1na** [comment]
First you need to make sure the `net` namespace of the API is enabled (`--http.api "net,..."`), then you should add a `-X POST` to your first curl command. Like:

`curl -X POST "http://..." -H 'Content-Type: application/json' -d ...`
