### ISSUE TITLE
Rinkeby faucet is down

### ISSUE THREAD

**Issue by orszaczky** [ethereum/go-ethereum#24434]
Hey guys, 

This is a duplication of [#21375](https://github.com/ethereum/go-ethereum/issues/21375) which has been closed, but the problem apparently hasn't been resolved. Faucet seems to be constantly down. 

What does it take to fix this?
![88477212-60f7dc80-cf3e-11ea-9a43-77dd293fbf7d](https://user-images.githubusercontent.com/6184774/154842569-f1a11e38-8944-411d-b423-5d72c12d5cfa.png)

**Comment by Zachinquarantine** [comment]
While it's down, you can use https://fauceth.komputing.org/

**Comment by orszaczky** [comment]
> While it's down, you can use https://fauceth.komputing.org/

Thanks for the link, it's working, I really appreciate it. Can we add this link to the Rinkeby faucet page? We shouldn't have to open git issues for this.

Also this is not solving the permanent Rinkeby faucet issue. What is the root cause of the faucet being down all the time and what can we do to fix it?
