### ISSUE TITLE
Ubuntu package with version 1.10.16 for Ubuntu Impish is missing in the ppa repository

### ISSUE THREAD

**Issue by DimaStebaev** [ethereum/go-ethereum#24444]
#### System information

Geth version: `1.10.16`
OS & Version: Ubuntu 21.10 Implish

#### Expected behaviour

After execution of

```bash
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt-get update
sudo apt-get install ethereum
```

ethereum meta package must be installed

#### Actual behaviour

Package is not installed

```text
Package ethereum is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ethereum' has no installation candidate
```

There are list of packages in https://launchpad.net/~ethereum/+archive/ubuntu/ethereum :

Package | Version | Uploaded by
-- | -- | --
ethereum | 1.10.16+build27677+xenial | Geth CI                                      (2022-02-16)
ethereum | 1.10.16+build27677+trusty | Geth CI                                      (2022-02-16)
ethereum | 1.10.16+build27677+focal | Geth CI                                      (2022-02-16)
ethereum | 1.10.16+build27677+bionic | Geth CI                                      (2022-02-16)
ethereum | 1.10.15+build27627+hirsute | Geth CI                                      (2022-01-05)
ethereum | 1.10.6+build26970+groovy | Geth CI                                      (2021-07-22)

Implish is missing.

**Comment by fjl** [comment]
Hi, unfortunately we cannot publish release packages retroactively. It's a limitation of our build pipeline. The next geth release will also be published for Ubuntu Impish. For now, you can use geth-unstable.
