### ISSUE TITLE
No documentation on how to format ABI in to call, need help 

### ISSUE THREAD

**Issue by chromafunk** [ethereum/go-ethereum#24442]
can somebody explain ( I can't find this anywhere ) how to format the ABI or the part of the ABI I want to make on this call ?

```
// SPDX-License-Identifier: MIT


pragma solidity >=0.5.0;
pragma experimental ABIEncoderV2;

/// @title Multicall - Aggregate results from multiple read-only function calls
/// @author Michael Elliot <mike@makerdao.com>
/// @author Joshua Levine <joshua@makerdao.com>
/// @author Nick Johnson <arachnid@notdot.net>

contract Multicall {
    struct Call {
        address target;
        bytes callData;
    }
    function aggregate(Call[] memory calls) public returns (uint256 blockNumber, bytes[] memory returnData) {
        blockNumber = block.number;
        returnData = new bytes[](calls.length);
        for(uint256 i = 0; i < calls.length; i++) {
            (bool success, bytes memory ret) = calls[i].target.call(calls[i].callData);
            require(success);
            returnData[i] = ret;
        }
    }
    // Helper functions
    function getEthBalance(address addr) public view returns (uint256 balance) {
        balance = addr.balance;
    }
    function getBlockHash(uint256 blockNumber) public view returns (bytes32 blockHash) {
        blockHash = blockhash(blockNumber);
    }
    function getLastBlockHash() public view returns (bytes32 blockHash) {
        blockHash = blockhash(block.number - 1);
    }
    function getCurrentBlockTimestamp() public view returns (uint256 timestamp) {
        timestamp = block.timestamp;
    }
    function getCurrentBlockDifficulty() public view returns (uint256 difficulty) {
        difficulty = block.difficulty;
    }
    function getCurrentBlockGasLimit() public view returns (uint256 gaslimit) {
        gaslimit = block.gaslimit;
    }
    function getCurrentBlockCoinbase() public view returns (address coinbase) {
        coinbase = block.coinbase;
    }
}

```

```
new_multicall, err := mcfantom.NewMcfantom(strategy_config.Muticalladdress,client)
if err != nil {
log.Fatalf("Failed to instantiate a multicall address contract: %v", err)
}

hash,err := new_multicall.Aggregate()
```

I have generated the keyed TransactOpts object, and also created the ABI function file from the multicall contract above with abigen All of this is working correctly, butI can't call the contract and get the results because I don't know how to get the ABI string correctly formatted in the callData struct field

If I want to call getReserves, how do I format the ABI string correctly in to callData in order to complete the contract call execution ?

**Comment by MariusVanDerWijden** [comment]
The easiest way to do it is to use the json abi of the calls that should be produced to automatically pack (with abigen)
You can also manually pack the callData like this: (However that is prone to errors)
```go
func main() {
    AddressArr, err := abi.NewType("address[]", "", nil)
    if err != nil {
        panic(err)
    }
    Uint256, err := abi.NewType("uint256", "", nil)
    if err != nil {
        panic(err)
    }
    Bool, err := abi.NewType("bool", "", nil)
    if err != nil {
        panic(err)
    }
    args := abi.Arguments{
        {Type: AddressArr},
        {Type: Uint256},
        {Type: Bool},
    }
    enc, err := args.Pack(
        []common.Address{
            common.HexToAddress("0x3403D13dF08EDB7eB03758c0cC2F800315835B00"),
            common.HexToAddress("0x366A0Ee2F0d6D51E5Ca2a5f8E7edfD74D02F6B3e"),
        },
        big.NewInt(1135234),
        false,
    )
    if err != nil {
        panic(err)
    }
    fmt.Println(hex.EncodeToString(enc))
}
```

**Comment by karlschriek** [comment]
> The easiest way to do it is to use the json abi of the calls that should be produced to automatically pack (with abigen)

@MariusVanDerWijden Could you expand what you mean by this?

I am trying to solve a problem where I need to be able to input arbitrary `args` as a JSON array (i.e they are not strongly typed within the golang code) in a method call. As far as I can gather from digging into the `abi` code, I would need to do this as follows:

1. Unmarshall the input JSON string (as array of strings)
2. Cast the string inputs as "Go" types. Which means I would have to loop over the `args` and ABI `inputs` arrays and each time convert the (string) arg to the right ("Go") type. E.g. if the ABI type is `addresss` then I use `common.HexToAddress` to convert from string to address, if the ABI type is `uint256` then I use `big.NewInt` (together with SetString) to convert from string to big int.
3. Call `Pack` to convert from the "Go" types to the packed format.

Am I going to have to write 2. myself or is there some kind of tooling I can use for this? If I have to do it myself, is there an exhaustive list of types that I can reference somewhere?

Any other way that I could make this easier? The input JSON is under my control, so I can do pre-formatting if needed.
