### ISSUE TITLE
math.HexOrDecimal256 unmarshaling of chainId

### ISSUE THREAD

**Issue by frenkel26** [ethereum/go-ethereum#24441]
#### System information

Geth version: v1.10.15

#### Description

`math.HexOrDecimal256.UnmarshalText` expects a string, If we pass a number in the json object (i.e. without quotes), the unmarshalling results with 0.
`TypedDataDomain.ChainId` is `*math.HexOrDecimal256`, and it is common for applications to serialize the ChainId as a number rather than a bigInt string.

#### Expected behaviour

expected chainId:
`&{false [4]}`

#### Actual behaviour

got 0 instead:
`&{false []}`

#### Steps to reproduce the behaviour

using this JSON as input to json.Unmarshal (notice the `"chainId":4`)
`{"types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"Permit":[{"name":"owner","type":"address"},{"name":"spender","type":"address"},{"name":"value","type":"uint256"},{"name":"nonce","type":"uint256"},{"name":"deadline","type":"uint256"}]},"domain":{"name":"Uniswap","verifyingContract":"0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","chainId":4},"primaryType":"Permit","message":{"owner":"0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","spender":"0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","value":"0","nonce":0,"deadline":0}}`

**Comment by MariusVanDerWijden** [comment]
Due to the way our marshaling library works, we have to require strings for this.
You can always just cast your number into a string/hexstring (`4` to `"4"` or `"0x4"`)
We accept both decimal and hex strings

**Comment by Mewjaden** [comment]
types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"},{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"Permit":[{"name":"owner","type":"address"},{"name":"spender","type":"address"},{"name":"value","type":"uint256"},{"name":"nonce","type":"uint256"},{"name":"deadline","type":"uint256"}]},"primaryType":"Permit","domain":{"name":"USD Coin","chainId":1,"verifyingContract":"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48","version":"2"},"message":{"deadline":1656197119,"nonce":0,"spender":"0x1111111254fb6c44bac0bed2854e76f90643097d","owner":"0x1e4942b1a4fab51ec950e5cccc957497b37d1103","value":"115792089237316195423570985008687907853269984665640564039457584007913129639935"}}
