### ISSUE TITLE
How to use the "importRawKey" in go-ethereum function?

### ISSUE THREAD

**Issue by heliping** [ethereum/go-ethereum#24469]
I use golang to make a ethclient.
1. use keystore to create accounts local.
2. use remotely private chain to SendTransaction.
But the remotely  geth informed "invalid account".
so i use web3js command "importRawKey" to import account in private chain.
I want to do this by golang, but I only found the  "importRawKey" with internal pkg in go-ethereum, and can't use it.
How to solve that?

**Comment by rjl493456442** [comment]
Are you looking for this command ` geth account import`? 
Or you want to use some accounts online then you need to either unlock these accounts in console or use `--unlock` flag to unlock them during the setup.

**Comment by heliping** [comment]
I knew the console command for importRawkey function.---"web3.eth.personal.importRawKey(privateKey, password)"
But I want to do the unlock by golang sdk.

**Comment by rjl493456442** [comment]
You can extend the geth-sdk here https://github.com/ethereum/go-ethereum/tree/master/ethclient/gethclient by adding this `personal_importRawKey`.
