### ISSUE TITLE
undefined: state?

### ISSUE THREAD

**Issue by dvvvsh** [ethereum/go-ethereum#24466]
forgive me if I'm posting this in the wrong area, this happens, I've tried to google the issue elsewhere but I can't find anything. 
this is what happens when I enter "make geth"

jonathandoe@MacBook-Air-3 ~ % cd mev-geth && make geth && cd ..

env GO111MODULE=on go run build/ci.go install ./cmd/geth
# golang.org/x/crypto/sha3
../go/pkg/mod/golang.org/x/crypto@v0.0.0-20210322153248-0c34fe9e7dc2/sha3/xor_generic.go:12:22: undefined: state
../go/pkg/mod/golang.org/x/crypto@v0.0.0-20210322153248-0c34fe9e7dc2/sha3/xor_generic.go:23:24: undefined: state

**Comment by karalabe** [comment]
Can't really say, something seems to be off in your installation. This is a standard library and I can definitely say that the `state` is defined https://github.com/golang/crypto/blob/master/sha3/sha3.go#L23. Make sure you have a recent version of Go installed, perhaps some old one doesn't pull the correct dependencies?
