### ISSUE TITLE
TypeError:   web3 has no member 'isConnected'

### ISSUE THREAD

**Issue by huluBrother** [ethereum/go-ethereum#24480]
What should I do

The error as followed 

```
> web3.isConnected()
TypeError: Object has no member 'isConnected'
	at web3.js:2625:69(10)
	at <eval>:1:17(3)

> web3.isConnected
function()
> 
```

the geth version as followed
```
~ % geth version
Geth
Version: 1.10.15-stable
Architecture: arm64
Go Version: go1.17.5
Operating System: darwin
GOPATH=
GOROOT=go
```

**Comment by s1na** [comment]
Yes the console's provider doesn't support this. What are you trying to do? The console will throw an error for any method if it is not connected to a live node. You can also use `net.listening == true` which is used in `web3.isConnected`.

**Comment by huluBrother** [comment]
> 

could one pc  install two of geth node ？

**Comment by karalabe** [comment]
You can run any number of Geth nodes, but you will need to use a separate data directory, separate HTTP/WS port and separate IPC path (by default on Linux as it's in the datadir; but needs explicit setting in Windows). Also take care with disk IO, Geth on mainnet is very resource hog on initial sync especially, but even then when it's time to write, it can hit your disk.
