### ISSUE TITLE
Rinkeby Faucet Down

### ISSUE THREAD

**Issue by armadillo49** [ethereum/go-ethereum#24499]
Hello - I have been trying to get Rinkeby Test Network Ether via the faucet.rinkeby.io since 2022-02-28 into my MetaMask wallet via Public Twitter post of my Public Key Address. Nothing has shown up. I am seeing a pink banner on the faucet.rinkeby.io site saying "faucet offline" since 2022-03-01 I believe. I was able to get Ether via rinkebyfaucet.com and Kovan Test Network. I'm just making sure this is a not a Bug or is already a known Issue before reporting. Thanks!

**Comment by ligi** [comment]
> I'm just making sure this is a not a Bug or is already a known Issue before reporting.

unfortunately it is known

**Comment by muktibarak** [comment]
I am having exact same issue since yesterday.

**Comment by muktibarak** [comment]
I am having exact same issue since yesterday.
