### ISSUE TITLE
questions about block hashing

### ISSUE THREAD

**Issue by c0yax** [ethereum/go-ethereum#24495]
what I want to know is if there is a way to derive the hash of the next block?

**Comment by c0yax** [comment]
or, can the block hash of the ethereum, be calculated in advance

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!


but the answer will be "no"
