### ISSUE TITLE
tracers: opcode filtering for JS tracers

### ISSUE THREAD

**Issue by s1na** [ethereum/go-ethereum#24503]
**Why should this feature exist?**

There is a lot of overhead in calling from Go into JS via duktape. We can allow JS tracers to specify which opcodes they're interested in and have Geth only dispatch `CaptureState` events for those opcodes. Benchmarks are needed to see if the performance gain is worth it. Same needs to be done for the goja tracer (https://github.com/ethereum/go-ethereum/pull/23773) because there's no go-C context switch.

**What are the use-cases?**

E.g. the `prestateTracer`.

**Comment by holiman** [comment]
Any tracer where performance matters should be written as native one, IMO. I don't think we should pursue this
