### ISSUE TITLE
Is it even possible to sync an archive node anymore?

### ISSUE THREAD

**Issue by nolash** [ethereum/go-ethereum#24501]
`Using geth --syncmode fast --http --gcmode archive --datadir /var/lib/geth`

Reached the 12 million block mark rather fast,  but has since stalled in the same region for 3 weeks, and seems to be incrementing by one block every 2-3 seconds. At this rate, I'll be synced in half a year if im lucky.

Disk usage is currently at just under 1TB

I am running on an at the moment practically dedicated 24 core 2.40GHz 5gen intel cpu with SSD SATA and 32 G ram.

Is this really the expected benchmark, or am I doing something wrong?

**Comment by tynes** [comment]
How much memory is the process using? You should try using the `--cache` flag to increase the cache size

**Comment by rjl493456442** [comment]
You are running the archive node by setting the flag `--gcmode archive`. And also you are using fast sync for initial state sync `--syncmode fast` it means you won't have the historical state data until the initial sync is finished. Not sure it's your expected behavior.

And regarding the archive node, it will push a lot of state data into disk and even worse the flushed data will involve the database compaction with almost all stored data in disk. I don't have the latest performance number for archive node, but it's indeed very slow.

**Comment by holiman** [comment]
Personally, I think the best way to have archive node features is some version of this: https://github.com/ethereum/go-ethereum/issues/24461  . Having read-only geth instances, with moderate-size databases, to query for data would be a lot better than having everythiing served from a single node, with a _huge_ database, which also does a lot of writes.

**Comment by ayushya-chitransh** [comment]
Currently the archive node is using 10.1TB of diskspace for chaindata, out of which 347GB is being used by ancient folder. As per details I have been able to collect so far, it seems that this is the current size of database for other archive nodes as well. I am looking for ways to decrease the size by some settings or admin commands.

Please let me know if this is okay to track this here, or should we look into this in a separate issue tracker.

**Comment by AyushyaChitransh** [comment]
Currently the archive node is using 10.1TB of diskspace for chaindata, out of which 347GB is being used by ancient folder. As per details I have been able to collect so far, it seems that this is the current size of database for other archive nodes as well. I am looking for ways to decrease the size by some settings or admin commands.

Please let me know if this is okay to track this here, or should we look into this in a separate issue tracker.

**Comment by karalabe** [comment]
There's now way to do it. That's the data size. We're already super
aggressive

**Comment by holiman** [comment]
The snapshot data is verifiable to the header stateroot. Exactly what piece of proving/verification is it that you want to achieve?

**Comment by nolash** [comment]
I simply seek to be a custodian of the state of the network.

If its not possible to do using the node, then I guess the only other way is to download the actual data and fire a parallell process to make sure it checks out, while syncing the current state.

**Comment by nolash** [comment]
To attempt to clarify the use-case:

* I download the state snapshot from somewhere
* There is a tool that runs for half a year or whatever it takes, that results in true of false for whether the snapshot is valid.
* This tool can run independent of p2p or network activity.
