### ISSUE TITLE
tracers: tx-level hooks

### ISSUE THREAD

**Issue by s1na** [ethereum/go-ethereum#24502]
We have EVM-level hooks (`CaptureStart`, `CaptureEnd`) and call-level hooks (`CaptureEnter`, `CaptureExit`). I'm proposing adding something like `CaptureTxStart` and `CaptureTxEnd`.

**Why should this feature exist?**

This feature makes the following information easily available to tracers: start gas (or intrinsic cost), refund values, any pre-check errors and if we want tx fields.

edit: actually it's not possible to accurately compute the intrinsic cost now in tracers because they don't have access to the access list.

**What are the use-cases?**

Main reason I started thinking about this is in some of the tracers we have to compute the intrinsic cost & refund value (e.g. in the  [logger](https://github.com/ethereum/go-ethereum/pull/24326/commits/05e3e9a3e416f82da5007aa500a733ebced755ba)).

**Implementation**

Invoke the hooks here:

https://github.com/ethereum/go-ethereum/blob/8fddf27a989e246659fd018ea9be37b2b4f55326/core/state_transition.go#L275

**Comment by rjl493456442** [comment]
Is it possible to merge the `CaptureStart` and `CaptureEnter` for both call frame scope? Looks like the only difference right now is `CaptureStart` is for topmost call frame?

Or we keep it for backward compatibility concern?

**Comment by s1na** [comment]
> Is it possible to merge the CaptureStart and CaptureEnter for both call frame scope? Looks like the only difference right now is CaptureStart is for topmost call frame?

I agree it makes sense semantically to have CaptureEnter for all (including) topmost call frames, and move up captureStart to emit only tx-level relevant info. I think it'd need bigger changes in our tracers but I'm gonna give it some more thought.
