### ISSUE TITLE
Suggestion for RPC error codes

### ISSUE THREAD

**Issue by mudpedal** [ethereum/go-ethereum#2451]
Hello,

I recommend that the ethereum json rpc specification also receive proper errors for individual cases, at the moment the error codes are vague. A good ethereum driver will then be able to properly map errors, not just by comparing/analyzing error strings.

The only codes that exist at the moment are specified in rpc/shared/types.go and are too generic.
https://github.com/ethereum/wiki/wiki/JSON-RPC doesn't specify anything about rpc error codes.

Thank you,
Andrei Grigoriu

**Comment by fjl** [comment]
See https://github.com/ethereum/go-ethereum/issues/768.
