### ISSUE TITLE
debug.TraceCall() is in ethereum/go-ethereum ？ 

### ISSUE THREAD

**Issue by wangruics** [ethereum/go-ethereum#24520]
<html>
<body>

Client | Method invocation
-- | --
Go | debug.TraceCall(args ethapi.CallArgs, blockNrOrHash rpc.BlockNumberOrHash, config *TraceConfig) (*ExecutionResult, error)
Console | debug.traceCall(object, blockNrOrHash, [options])
RPC | {"method": "debug_traceCall", "params": [object, blockNrOrHash, {}]}

</body>
</html>

I found this doc, but  can not  find this method

**Comment by s1na** [comment]
You probably need to enable it when starting geth via the flag `--http.api "eth,debug"`

**Comment by Sengoku11** [comment]
But where is it in the repo?

**Comment by 18600294832** [comment]
i can't find this method . please tell me how to use in go client , show me code

**Comment by s1na** [comment]
I think you're referring to ethclient. This method is not available there. I agree it would be nice to have. I created this issue to track it: https://github.com/ethereum/go-ethereum/issues/28182

If anyone is willing to implement this please get in touch.
