### ISSUE TITLE
private network peer and miner don't connect with each other

### ISSUE THREAD

**Issue by huahuayu** [ethereum/go-ethereum#24557]
Hi, I want build a local ethereum development environment, I do it by run several nodes in docker, Basically I followed the official [private-net-toturial](https://geth.ethereum.org/docs/getting-started/private-net), for convenient I wrote some script in this [repo](https://github.com/huahuayu/ethereum-local-development-env). 

There's one problem, peer and miner don't connect with each other, although they share same bootnode.

I spent several hours tried to find the issue but failed, I can provide more info, logs for example, please help to check.

## Start nodes

```bash
git clone https://github.com/huahuayu/ethereum-local-development-env.git
cd ethereum-local-development-env
./start_all.sh
```

Check the containers

```bash
docker ps | grep eth
```

Node info summary

| node type | container name | enode                                   |
| --------- | -------------- | --------------------------------------- |
| bootnode  | eth-bootnode   | enode://$str@127.0.0.1:0?discport=30301 |
| fullnode  | eth-node1      | enode://$str@127.0.0.1:30697            |
| miner     | eth-miner1     | enode://$str@127.0.0.1:42983            |

All the node use same [genesis.json](https://github.com/huahuayu/ethereum-local-development-env/blob/master/genesis_file/eth/genesis.json) file.

## Expected

- [x] fullnode & miner can find and connect with each other, because they use same bootnode
- [x] miner start mining
- [x] fullnode keep syncing with miner

## Actually

Only 1 matchs

- [x] miner start mining

Fullnode can sense the highest block number change, but can't sync

Manually `admin.addPeer` not working too

## Check status

After a while (after the miner mined few blocks)

**miner**

Miner console `./attach.sh miner1`

```bash
> eth.syncing
false

> eth.blockNumber
100

> admin.peers
[]
```

**fullnode**

Fullnode console `./attach.sh node1`

```bash
> eth.syncing
{
  ...
  currentBlock: 0,
  highestBlock: 100,
  ...
}

> eth.blockNumber
0

> admin.peers
[]
```

## Logs

This is the logs keep printing in peer

```text
INFO [03-17|15:45:58.446] Looking for peers                        peercount=0 tried=21 static=0
INFO [03-17|15:46:08.483] Looking for peers                        peercount=0 tried=25 static=0
INFO [03-17|15:46:09.055] State heal in progress                   accounts=0@0.00B   slots=0@0.00B codes=0@0.00B nodes=0@0.00B pending=1
INFO [03-17|15:46:09.074] State heal in progress                   accounts=2@93.00B  slots=0@0.00B codes=0@0.00B nodes=3@314.00B pending=0
WARN [03-17|15:46:09.099] Invalid header encountered               number=1 hash=532397..e41f42 parent=1fe3fd..dcc5b0 err="bad DAO pro-fork extra-data"
WARN [03-17|15:46:09.104] Synchronisation failed, dropping peer    peer=90c51af323cee4bcc745d6f3888d1a935bbac7bea4d7113fe70ed72f5465855c err="retrieved hash chain is invalid: bad DAO pro-fork extra-data"
```

**Comment by karalabe** [comment]
Please delete the 

```
    "daoForkBlock": 0,
    "daoForkSupport": true,
```

fields from your genesis json.

This enabled the DAO fork, which requires special mining logic that has been deleted in Geth (since it's only relevant on mainnet, which forked 6 years ago).

**Comment by huahuayu** [comment]
@karalabe thank you! that's the case, just now I turn the flag to `false` it works, I went back to close the issue and found you replied :)
