### ISSUE TITLE
onlyOwner function Contract call, to withdraw ether

### ISSUE THREAD

**Issue by maestroh1git** [ethereum/go-ethereum#24559]
Hi guys
Super new to Go and Geth and Ethereum
I deployed a contract to deposit and withdraw ether(with functions modified to onlyOwner) to ropsten with remix
I tested it with hardhat-ethers and its great, i created a new wallet instance with the provider and private key( for the deployer), then called the onlyOwner function and viola! transaction successful.

trying to replicate in go-ethers, after binding the newTransactor with the privatekey, it says "Execution Reverted"
binding the newTransactor with another privateKey gives an "Ownable: caller is not owner" error, so the function is good, buut why isnt the original deployer private key working to call the method as the Owner(deployer)?
Thank you guys for shedding  light

**Comment by rjl493456442** [comment]
Not sure, please you have to submit the issue to `go-ethers` repo? It's not relevant with `go-ethereum`.

**Comment by crypt0inf0** [comment]
@maestroh1git here's the example,
```
// Smart contract instance to interact with
auth, err := bind.NewKeyedTransactorWithChainID(priv, chainID)
checkError(err)

instance, err := swap.NewSwap(deployedContractAddress, client)
checkError(err)

getBalance, err := instance.GetBalance(&bind.CallOpts{
    From: auth.From,
})
checkError(err)
fmt.Println(getBalance)
```
Ref: https://geth.ethereum.org/docs/dapp/native-bindings
