### ISSUE TITLE
cannot export metrics with properly key/value tag on ubuntu/influxdb

### ISSUE THREAD

**Issue by hadv** [ethereum/go-ethereum#24551]
When run `geth` with `--metrics` enable, It cannot export metrics with properly key/value tag on Ubuntu/InfluxDB. By default it should add key/value `"host=localhost"` for all the measurements.

#### System information

Geth version: `go-ethereum v1.10.15 stable`
OS & Version: Ubuntu 20.04 (LTS) x64, InfluxDB v1.6.4

#### Expected behaviour

Should add the key value tag when export metrics to InfluxDB as below when run `SHOW TAG VALUES WITH KEY = "host"` query on InfluxDB

```
...
name: geth.vflux/server/inactive/count.gauge
key  value
---  -----
host localhost
```

#### Actual behaviour

Show nothing due to no measurements with tag key="host"

#### Steps to reproduce the behaviour

1. create relevant InfluxDB database and user for `geth`
2. run geth with `--metrics` enable like below
```
geth --mainnet --metrics --metrics.influxdb --metrics.influxdb.database "geth" --metrics.influxdb.username "geth" --metrics.influxdb.password "geth"
```
3. using influxdb client to query the data by run below query
```
SHOW TAG VALUES WITH KEY = "host"
```

---
**N.B:** _If we run on `Debian 10 x64` then we get the expected behaviour correctly_ 

```
name: geth.vflux/server/inactive/count.gauge
key  value
---  -----
host localhost
```

**Comment by karalabe** [comment]
We're using Geth on Ubuntu on all our instances and they export the metrics just fine (though we do explicitly set to host tag to our hostnames). I can't really fathom what difference it might make if it's Ubuntu or Debian.

**Comment by hadv** [comment]
Okay, I will try to set the host tag explicitly on Ubuntu. Yes, it's so strange, don't know what is the difference between Ubuntu & Debian.

**Comment by hadv** [comment]
> We're using Geth on Ubuntu on all our instances and they export the metrics just fine (though we do explicitly set the host tag to our hostnames). I can't really fathom what difference it might make if it's Ubuntu or Debian.

I tried to run geth with `--metrics.influxdb.tags "host=geth"` option but still cannot query the metrics by host tag on `Ubuntu 20.04 (LTS) x64`; don't know what I'm doing wrong.

**Comment by holiman** [comment]
> don't know what I'm doing wrong.

Neither do we, unfortunately. We're successfully using geth on ubuntu and custom tags (e.g. host) without any problems, so I can't see that this is an error within go-ethereum. 

Please reopen if you find something which points towards geth doing something wrong.

**Comment by hadv** [comment]
> Neither do we, unfortunately. 

Okay, just my rhetorical question? 

> We're successfully using geth on ubuntu and custom tags (e.g. host) without any problems, so I can't see that this is an error within go-ethereum.

it seems the issue of InfluxDB version 1.6.4 on an Ubuntu 20.04 LTS? Why you can do it? 

https://github.com/influxdata/influxdb/issues/9953#issuecomment-643012845
