### ISSUE TITLE
Is there a way to start with --syncmode "light" when I downloaded Geth for MacOS?

### ISSUE THREAD

**Issue by Taewa** [ethereum/go-ethereum#24563]
Hi all,
I am a newbie on this field and trying to setting Geth on my local.
I am in a situation where I can't install Homebrew, so I have to rely on downloading from the official website ( https://geth.ethereum.org/downloads/ )

From the website, when I clicked the button " Geth 1.10.16 for macOS" and I downloaded "geth-darwin-amd64-1.10.16-20356e57".
And executed "geth" file.
Then, it seems like downloading all blocks and when it downloaded over 100Gb, I stopped since I don't have enough space.

I have seen that I can start with "Light node" with parameter `--syncmode "light"` but I can't find any info.

Is there any way to start with light node mode on MacOS?

Thanks in advance.

**Comment by fjl** [comment]
Hi, are you running geth by double-clicking the executable? If you do that, it will run the process with no options at all, and you won't be able to use it. You need to run it from the command-line instead.

Open Terminal.app and type `cd ` (space at the end), then drag the folder containing geth to the Terminal window. It will now say `cd /Users/.../Downloads/geth-.../` or something like that. Now press enter. This navigates your command-line into the correct directory.

Now run geth by typing the command `geth --syncmode light`. Press enter to run the command. You can quit it by hitting Ctrl-C.

**Comment by Taewa** [comment]
Hi @fjl 
Thank a lot for the solution. I was shocked that I didn't even think about that way.
