### ISSUE TITLE
Go build reports error on M1 chip Mac: warning: 'TARGET_OS_MAC' is not defined

### ISSUE THREAD

**Issue by 1270458160** [ethereum/go-ethereum#24565]
go build

# github.com/shirou/gopsutil/cpu
../../../go/pkg/mod/github.com/shirou/gopsutil@v2.19.12+incompatible/cpu/cpu_darwin_cgo.go:13:5: warning: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]

**Comment by rjl493456442** [comment]
Can you try the latest master branch? I used to have the similar issues but now they are gone.

**Comment by holiman** [comment]
```
$ cat go.mod | grep gops
        github.com/shirou/gopsutil v3.21.4-0.20210419000835-c7a38de76ee5+incompatible
```

**Comment by holiman** [comment]
You're on some old version (of geth) which has not up to date dependencies
