### ISSUE TITLE
failed to open trie tree

### ISSUE THREAD

**Issue by leeeddin** [ethereum/go-ethereum#24578]
#### System information

Geth version: `lastest`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour

failed with "execute revert"

#### Actual behaviour

failed with a lot of "failed to open trie tree"

log: 
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179457 t="61.657µs"               err="failed to open trie tree"               X-Forwarded-For=nil
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179457 t="61.157µs"               err="failed to open trie tree"
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179459 t="79.878µs"               err="failed to open trie tree"               X-Forwarded-For=nil
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179459 t="79.512µs"               err="failed to open trie tree"
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179461 t="65.063µs"               err="failed to open trie tree"               X-Forwarded-For=nil
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179461 t="64.628µs"               err="failed to open trie tree"
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179463 t="67.39µs"                err="failed to open trie tree"               X-Forwarded-For=nil
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179463 t="67.041µs"               err="failed to open trie tree"
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179465 t="67.622µs"               err="failed to open trie tree"               X-Forwarded-For=nil
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179465 t="67.056µs"               err="failed to open trie tree"
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179467 t="80.127µs"               err="failed to open trie tree"               X-Forwarded-For=nil
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179467 t="79.667µs"               err="failed to open trie tree"
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179469 t="76.944µs"               err="failed to open trie tree"               X-Forwarded-For=nil
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_getCode"                     reqid=179469 t="76.578µs"               err="failed to open trie tree"
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_call"                        reqid=179470 t="229.307µs"              err="execution reverted"                     X-Forwarded-For=nil
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_call"                        reqid=179470 t="229.009µs"              err="execution reverted"
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_call"                        reqid=179471 t="263.968µs"              err="execution reverted"                     X-Forwarded-For=nil
t=2022-03-24T04:16:24+0000 lvl=warn msg="Served eth_call"                        reqid=179471 t="263.317µs"              err="execution reverted"

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by leeeddin** [comment]
I'm coding in go and trying to request GetAmountsOut from a local full node.
This bug sometimes recurs, but it doesn't reappear steadily.

res_, err := PancakeRouter.GetAmountsOut(nil, amountIn, Path)

**Comment by rjl493456442** [comment]
I can't find this error `failed to open trie tree` in our codebase. Are you actually using Geth, Or some forks?

**Comment by leeeddin** [comment]
I'm using BSC chain copy version of geth
