### ISSUE TITLE
'noempty' flag in the "worker" structure stopped working in v1.10.16

### ISSUE THREAD

**Issue by 4hash** [ethereum/go-ethereum#24585]
#### System information

Geth version: Geth/v1.10.16-stable/linux-amd64/go1.16.5`
OS & Version: Ubuntu 20.04.2 LTS
Commit hash : (if `develop`)

#### Expected behaviour
To avoid mining empty blocks, I set 'noempty' flag to 1 in the "worker" structure in /miner/worker.go. This used to work.
// noempty is the flag used to control whether the feature of pre-seal empty
// block is enabled. The default value is false(pre-seal is enabled by default).

#### Actual behaviour
Stopped working starting from v1.10.16.

#### Steps to reproduce the behaviour
Set 'noempty' flag to 1 in the "worker" structure in /miner/worker.go, compile, start geth with --mine and check for "Commit new sealing work" with txs=0 in output.

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by rjl493456442** [comment]
I just tried it and it seems work. Just a reminder, `noempty` doesn't mean it will not generate empty mining block. For example if there is no transaction in pool, then the empty block is still created. But if you set it to `1`, it will alway avoid creating the "additional" empty mining block in advance.

**Comment by 4hash** [comment]
Thanks, seems like this is an issue with flashbots, reported to them.

**Comment by rjl493456442** [comment]
Cool, close it now and feel free to reopen it again.
