### ISSUE TITLE
About genesis.json

### ISSUE THREAD

**Issue by Ithandysun** [ethereum/go-ethereum#24584]
I'm trying to preset a token contract in the genesis file of private chain. May I ask how to fill in the code of alloc? Thank you

**Comment by rjl493456442** [comment]
You can use `puppeth` for creating the genesis file for your private network. But in order to pre-define your contract in genesis, it's getting a bit complicated. You need to config the `address`, `balance`, `runtime-code`, `nonce` fields properly manually.

**Comment by MariusVanDerWijden** [comment]
You need the deployed code of the contract (not the one that the solidity compiler produces which contains the initcode). Then you can just set it manually. Here's an example on how a genesis file with a predeployed contract can look like: https://github.com/eth-clients/merge-testnets/blob/main/kiln/genesis.json#L788

I'm not sure if we want to add this to the docs, its a very niche use case
