### ISSUE TITLE
Support non-changing difficulty

### ISSUE THREAD

**Issue by liadmord** [ethereum/go-ethereum#24580]
# Rationale

Why should this feature exist?
For many reasons people create their own private test network to test their applications, whether it is a contract, wallet or any other applications that use the blockchain.
 
What are the use-cases?
When testing blockchain related stuff that need to mine block repeatedly and they do not care about the actual process of the mining and only the applicative part of the blockchain the fact the the difficulty rises is slowing down the testing process and is not required.

Testing wallets for example.

# Implementation

Do you have ideas regarding the implementation of this feature?

I was thinking we can add this to the chain config as a boolean, something like "static_difficulty" (`params/config.go`)
and then inside the `CalcDifficulty` function in `conesnsus.go` we can check the config, and if the config contains the flag we will just return 0.

Are you willing to implement this feature?

Yes.

**Comment by s1na** [comment]
If you don't care about the mining aspect of the network and only the application you could set up a clique private network instead of PoW. See these docs: https://geth.ethereum.org/docs/interface/private-network
