### ISSUE TITLE
Always force quit the client

### ISSUE THREAD

**Issue by amengCow** [ethereum/go-ethereum#24596]
my geth is the latest version
The server is ubunt 8v 21g hard disk 1.5T bandwidth peak 25G
Start command geth --http --ws --maxpeers 35 --rpc.txfeecap 0

What makes me sad is that every half month or more he will force quit and I have no way of knowing what's going on in my server and what can be avoided
The log looks normal. After each forced exit, it needs to synchronize about 20,000 blocks. Is there any way to avoid it?

```
INFO [03-28|05:05:55.958] Imported new chain segment               blocks=1     txs=10        mgas=0.983   elapsed=26.435ms    mgasps=37.177   number=14,470,573 hash=0809df..1379ae dirty=1010.64MiB
INFO [03-28|05:05:55.960] Unindexed transactions                   blocks=1     txs=152       tail=12,120,574 elapsed=1.917ms
INFO [03-28|05:06:09.556] Imported new chain segment               blocks=1     txs=230       mgas=16.121  elapsed=106.680ms   mgasps=151.112  number=14,470,574 hash=de2482..3c4c7d dirty=1009.87MiB
INFO [03-28|05:06:09.559] Unindexed transactions                   blocks=1     txs=131       tail=12,120,575 elapsed=2.321ms
```

**Comment by rjl493456442** [comment]
Can you provide more information about "force quit"? Do you have any log for it?

**Comment by MariusVanDerWijden** [comment]
Might be an OOM, are you running any other software on that machine?

**Comment by amengCow** [comment]
> 

I checked the log of geth and there is no record

**Comment by amengCow** [comment]
> Might be an OOM, are you running any other software on that machine?
There is a nodejs process ,  low occupancy

**Comment by amengCow** [comment]
Guys, what's the best way?" i am very troubled

**Comment by holiman** [comment]
Check the `/var/log/syslog` or the `journalctl`, and see if there's any mention there about the oom-reaper harvesting the process.

**Comment by holiman** [comment]
Please also provide ~50 lines of logs around when it is killed and starts up. So the last parts before the kill, and the first part after the restart.

**Comment by holiman** [comment]
unanswered and getting stale, closing this
