### ISSUE TITLE
make: *** [geth] Error 1

### ISSUE THREAD

**Issue by wusw2** [ethereum/go-ethereum#24592]
#### System information

Geth version: `geth version`
OS & Version: OS

Hello.
When try to make geth take error....

sunshine_dywang@dywang223deMacBook-Air go-ethereum % make geth
env GO111MODULE=on go run build/ci.go install ./cmd/geth
go: github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0: Get "https://proxy.golang.org/github.com/%21azure/azure-sdk-for-go/sdk/storage/azblob/@v/v0.3.0.mod": dial tcp 172.217.160.113:443: i/o timeout
go: downloading github.com/cespare/cp v0.1.0
go: downloading github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.3.0
go: downloading golang.org/x/crypto v0.0.0-20210322153248-0c34fe9e7dc2
go: github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0: Get "https://proxy.golang.org/github.com/%21azure/azure-sdk-for-go/sdk/storage/azblob/@v/v0.3.0.mod": dial tcp 172.217.160.113:443: i/o timeout
make: *** [geth] Error 1

Where is the problem please？！！

**Comment by wusw2** [comment]
go version go1.18 
geth version 1.10.16

**Comment by eval-exec** [comment]
> #### System information
> Geth version: `geth version` OS & Version: OS
> 
> Hello. When try to make geth take error....
> 
> sunshine_dywang@dywang223deMacBook-Air go-ethereum % make geth env GO111MODULE=on go run build/ci.go install ./cmd/geth go: github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0: Get "https://proxy.golang.org/github.com/%21azure/azure-sdk-for-go/sdk/storage/azblob/@v/v0.3.0.mod": dial tcp 172.217.160.113:443: i/o timeout go: downloading github.com/cespare/cp v0.1.0 go: downloading github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.3.0 go: downloading golang.org/x/crypto v0.0.0-20210322153248-0c34fe9e7dc2 go: github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0: Get "https://proxy.golang.org/github.com/%21azure/azure-sdk-for-go/sdk/storage/azblob/@v/v0.3.0.mod": dial tcp 172.217.160.113:443: i/o timeout make: *** [geth] Error 1
> 
> Where is the problem please？！！

It seems that `GOPROXY` is not reachable

**Comment by wusw2** [comment]
> 

how to solve it??plz...

**Comment by rjl493456442** [comment]
https://goproxy.io/zh/
