### ISSUE TITLE
Syncmode snap, acting as Validator or sending requests to other nodes?

### ISSUE THREAD

**Issue by James19903** [ethereum/go-ethereum#24594]
System information
Geth version: v1.10.16
OS & Version: Linux Ubunutu

I am trying to build an ETH node to validate my transactions. I currently have GETH synced with mode SNAP.
1) Am I validating my own transactions with this SNAP mode or am I requesting this from other full nodes?? 
2) Does the --maxpeers value have an impact on the speed of validating transactions?
3) Is there anything else I can do to increase the speed of the validations?

```
Mar 27 18:57:59 Ubuntu-2004-focal-64-minimal-hwe geth[4531]: INFO [03-27|18:57:59.782] Unindexed transactions                   blocks=1  txs=168  tail=12,119,479 elapsed=1.210ms
Mar 27 18:58:22 Ubuntu-2004-focal-64-minimal-hwe geth[4531]: INFO [03-27|18:58:22.217] Imported new chain segment               blocks=1  txs=283  mgas=24.120  elapsed=76.537ms    mgasps=315.135 number=14,469,479 hash=8b4cc2..d22d4a dirty=61.20MiB
Mar 27 18:58:22 Ubuntu-2004-focal-64-minimal-hwe geth[4531]: INFO [03-27|18:58:22.218] Unindexed transactions                   blocks=1  txs=191  tail=12,119,480 elapsed="951.763µs"
Mar 27 18:58:41 Ubuntu-2004-focal-64-minimal-hwe geth[4531]: INFO [03-27|18:58:41.796] Imported new chain segment               blocks=1  txs=314  mgas=30.038  elapsed=90.210ms    mgasps=332.974 number=14,469,480 hash=167a86..8697c2 dirty=64.47MiB
Mar 27 18:58:41 Ubuntu-2004-focal-64-minimal-hwe geth[4531]: INFO [03-27|18:58:41.796] Unindexed transactions                   blocks=1  txs=150  tail=12,119,481 elapsed="551.389µs"
```

**Comment by rjl493456442** [comment]
You are running a Geth node for validating the blocks propagated over the network, not only your own transactions.

Flag `maxpeers` means the number of node connections it will maintain at most. Maintaining more peer nodes will increase system resource usage (network bandwidth, disk IO, CPU, etc.) to a certain extent to serve requests from peers. Of course, the advantage is that you can receive transactions and blocks from the network faster. If you connect a lot of peers, it will affect the efficiency of block processing to a certain extent.

**Comment by James19903** [comment]
Thank you for the reply!
