### ISSUE TITLE
High CPU & Optimization

### ISSUE THREAD

**Issue by James19903** [ethereum/go-ethereum#24607]
The node is fully synced and is running at around 88% CPU and 25% on an AX101 Hetzer Server. Compared to my GETH BSC Node, it is sitting at around 20% CPU. I am trying to optimize this node for speed (validating blocks) as I am using it as an RPC point.

Here are my GETH launch settings:
--datadir /home/chain/data --syncmode snap --http --http.addr localhost --http.port 8545 --ws --ws.addr localhost --ws.port 8546 --metrics --cache=64000 --maxpeers 100 --http.api eth,net,web3,txpool,debug --rpc.allow-unprotected-txs --txlookuplimit 0 --ws.origins * --ws.api eth,net,web3,txpool,debug

1) Are any of these settings hindering the speed and causing high cpu?
2) Is there anything I can change to increase the speed at which the node syncs with new blocks and validates transactions?
3) What is Data Freeze Chain Segment, is this slowing anything down? Can it be turned off?
4) Would disabling --snapshot= be beneficial to this?
5) Is this an accurate test:  Testing the speed of the block processing by comparing the timestamp I get in my terminal to the timestamp given here: https://etherscan.io/blocks?

Any advice is really appreciated, Thanks!!

**Comment by rjl493456442** [comment]
Normal chain processing will not cause that high CPU usage, and actually the resource usage is quite low only your node is synced. Are your node accepting RPC requests?

Chain freezing is a mechanism in Geth which moves the historical chain data from leveldb to ancient store. It shouldn't cause very high CPU usage.

Can you check if your node is generating the snapshot? If so some relevant logs will be printed. And it can be resource expensive.

**Comment by James19903** [comment]
> 

Thanks for the reply!
Yes my node is accepting RPC requests, --rpc.allow-unprotected-txs, I am using it as an RPC point for my transactions on MetaMask so I think I have to keep this on?
I believe that snapshot generating is turned on by default by this command  --snapshot [Enables snapshot-database mode (default = enable)], I will try turn that off aswell

**Comment by James19903** [comment]
> Disabling snapshot, if it's already finished generating, will definitely make the block processing **slower**. However, I'm not sure it's possible to disable snapshot anymore.



> Disabling snapshot, if it's already finished generating, will definitely make the block processing **slower**. However, I'm not sure it's possible to disable snapshot anymore.

Ok, I will not turn --snapshot off then, any idea's about the other settings for increasing block processing? 
--maxpeers 100 --rpc.allow-unprotected-txs --txlookuplimit 0

**Comment by James19903** [comment]
Added another question if anyone can help with that aswell:
Is this an accurate test: Testing the speed of the block processing by comparing the timestamp I get in my terminal to the timestamp given here: https://etherscan.io/blocks?

**Comment by holiman** [comment]
> Testing the speed of the block processing by comparing the timestamp I get in my terminal to the timestamp given here: 

No, it's not. The timestamp in a block is set the moment the miner starts mining on it, has nothing to do with your node. 

The most accurate measure of your block processing speed is the `mgas/s` that geth spits out. However, I suspect that what you're really after is not processing speed, but low latency for new head events... ? I.e: you want to obtain the most recent block as fast as possible. Is that correct?

**Comment by James19903** [comment]
> 

Correct (I think)

**Comment by James19903** [comment]
Still open to any suggestions :)

**Comment by MariusVanDerWijden** [comment]
Only way is to improve your location in the network by being connected to a lot of peers (which will increase cpu usage) and have high bandwith. Will close this issue now. There's no actionable items for go-ethereum. You might want to try the ethereum stackexchange (https://ethereum.stackexchange.com/) for advice on how to get the last little bit of speed out of your node
