### ISSUE TITLE
Geth Import should support importing PoS blocks

### ISSUE THREAD

**Issue by marioevz** [ethereum/go-ethereum#24601]
# Rationale

At the moment, using `geth import` for PoS blocks (blocks that happen after the Terminal Total Difficulty is reached) fails because the feature requires all imported blocks to have a non-zero `difficulty` value, which is not the case for PoS blocks, which all require 0 in the `difficulty` field.

Why should this feature exist?
This feature would aid testing in the `consensus` hive simulator, which currently attempts to import blocks in the `BlockchainTests` category of the `tests` repository.

What are the use-cases?
Importing blocks with non-zero difficulty after the TTD has been reached should still result in error.
PoS blocks with ommers should also fail, or non-zero Nonce.
These are test cases that cannot be tested through the Engine API since the payload does not contain these fields.

This feature was also mentioned in #24003

# Implementation

Do you have ideas regarding the implementation of this feature?
The import feature should be aware of the TerminalTotalDifficulty setting in the genesis, and act accordingly when doing the block imports.

Are you willing to implement this feature?

**Comment by rjl493456442** [comment]
I think it's a good feature request.

**Comment by holiman** [comment]
Some background: up until now, we've kind of treated `import` of rlp blocks as if the blocks were delivered from the network -- we do a full validation of the blocks. 

So now, we either need to change the model, and treat the `import` as if the imported blocks comes from the _trusted_ engine api. And that makes it easy/possible to test post-merge import -- but it makes it _difficult_ to test certain scenarios, like, if we want the import to reject post-merge blocks which are not coming from `engine`. 

Alternatives: 
- Import blocks as if they were from `engine`
- Provide `import` (normal) and add switch: `import --trusted`(engine) 

I'm leaning towards the second option.

**Comment by holiman** [comment]
> At the moment, using geth import for PoS blocks (blocks that happen after the Terminal Total Difficulty is reached) fails because the feature requires all imported blocks to have a non-zero difficulty value, which is not the case for PoS blocks, which all require 0 in the difficulty field.

Do you have an example rlp dump of such blocks, which fails the import?

**Comment by karalabe** [comment]
@holiman Isn't this case simply exporting and reimporting the blocks from a network post-merge? E.g. Kiln?

In that case once TTD is reached, we should just start accepting blocks without PoW IMHO. Nothing else we can do really.

**Comment by winsvega** [comment]
Does `geth import` rely on genesis.config? 

Thus the client can be initialized with TTD defined in genesis config. And geth import cobtinue to work as it was given the merge rules. (Stop accepting PoW blocks and start PoS)

Btw is it ignoring the nonce and mixhash for testing?

**Comment by marioevz** [comment]
> Do you have an example rlp dump of such blocks, which fails the import?

@holiman this is the blockchain test used to find the issue, it contains the rlp of the block:
https://github.com/ethereum/tests/blob/merge/BlockchainTests/GeneralStateTests/stExample/mergeTest.json

However the genesis does not contain the TerminalTotalDifficulty, this is added in the hive `consensus` simulator by setting `HIVE_TERMINAL_TOTAL_DIFFICULTY` to zero, which was triggered by this line in the `mergeTest.json`:
["network" : "Merge",](https://github.com/ethereum/tests/blob/6e9779f8a4d24a908089c0c9737564224fb5c11f/BlockchainTests/GeneralStateTests/stExample/mergeTest.json#L86)

**Comment by holiman** [comment]
@marioevz you don't happen to have the output from 
```
echo "Initializing database with genesis state..."
$geth $FLAGS init /genesis.json
```
i.e, the genesis that gets created... do you?

**Comment by holiman** [comment]
`HIVE_TERMINAL_TOTAL_DIFFICULTY` isn't defined in the go-ethereum client on hive, afaict.

**Comment by holiman** [comment]
Awesome, now I can repro it
```
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: <nil>, Berlin: 0, London: 0, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: 0, Engine: ethash}

Number: 1
Hash: 0x8ce374ca14f5c8f25f1a5731cf10e44f8f05ab6968a764fa9d13752e04796c94


Error: invalid difficulty: have 0, want 131072
##############################
 
```

**Comment by holiman** [comment]
@marioevz PTAL at https://github.com/ethereum/go-ethereum/pull/24620. I think the blocks are erroneously generated, not correctly calculating the basefee.
