### ISSUE TITLE
Syncmode and gcmode is being ignored.

### ISSUE THREAD

**Issue by dmgnflx99** [ethereum/go-ethereum#24600]
Hi,

Recently i added an explorer to my private POA network, however, it requires the syncmode to be full and the gcmode be archive.
From the above two pre-requisite I already met one with `--gcmode archive`,
I changed the --syncmode to full and restarted the node.

geth logs as the explorer trying to parse chain:

`WARN [03-28|13:49:03.596] Served debug_traceTransaction            conn=192.168.1.11:38058 reqid=0 t=42.807292ms err="required historical state unavailable (reexec=128)"
WARN [03-28|13:49:04.448] Served debug_traceTransaction            conn=192.168.1.11:38060 reqid=0 t=45.82722ms  err="required historical state unavailable (reexec=128)"
WARN [03-28|13:49:04.645] Served debug_traceTransaction            conn=192.168.1.11:38060 reqid=0 t=128.542628ms err="required historical state unavailable (reexec=128)"
WARN [03-28|13:49:04.810] Served eth_getCode                       conn=192.168.1.11:38056 reqid=0 t=12.867604ms  err="missing trie node 7a721e1cdba27c6b4d96cae337f0e2013972ac6d2ec7092c26cb3bcac5ec0e6d (path )"
WARN [03-28|13:49:04.829] Served eth_getCode                       conn=192.168.1.11:38054 reqid=0 t=30.219965ms  err="missing trie node 509e3c0a21a00d68aeb994e6c23355fd069fadd36dda33d47f5c48fee7fc2483 (path )"
WARN [03-28|13:49:04.832] Served eth_getCode                       conn=192.168.1.11:38056 reqid=1 t=22.12976ms   err="missing trie node c714bc1645599ea47dfd51a446e30913b7d983355b5da4f3cdb21a3b9b98c8d3 (path )"`

I can see geth is importing new segments. and commiting mining work.
`INFO [03-28|13:49:05.016] Imported new chain segment               blocks=1  txs=0 mgas=0.000 elapsed="323.988µs" mgasps=0.000 number=322299488 hash="ab246b…4edf0d" dirty=0.00B
INFO [03-28|13:49:05.017] Commit new mining work                   number=322299489 sealhash="2a3407…ae6f14" uncles=1 txs=0 gas=0 fees=0 elapsed="555.041µs"`

eth console about the sync:
`To exit, press ctrl-d
> eth.syncing
false`

Do i have to remove the database and reinit the genesis to apply the syncmode full to the node or should it work without it?

Thanks.

**Comment by s1na** [comment]
Yes if you didn't do full sync from the beginning you won't have the state for blocks before full sync was switched on. You'll need to clear the database and do a fresh full sync (re-initing genesis shouldn't be unnecessary).
