### ISSUE TITLE
Flag  is depricated

### ISSUE THREAD

**Issue by iktina** [ethereum/go-ethereum#24618]
#### System information

Geth version: `geth version 1.10.17`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Steps to reproduce the behaviour
go to https://geth.ethereum.org/docs/interface/peer-to-peer  and go to Custom Networks

It is also possible to run geth with a custom genesis block from a JSON file by supplying the --genesis flag.

Recept: https://ethereum.stackexchange.com/questions/2641/geth-init-what-are-the-arguments

#### Backtrace

 --genesis is deprecated. Switch to use 'geth init /path/to/file'
(This init parameter is new, in the develop branch version 1.4.0 )
````

````

When submitting logs: please submit them as text and not screenshots.

**Comment by MariusVanDerWijden** [comment]
You need to use `geth init /path/to/genesis.json`in order to import the genesis file. The `--genesis` parameter has been removed
