### ISSUE TITLE
--config Error

### ISSUE THREAD

**Issue by James19903** [ethereum/go-ethereum#24622]
Geth v1.18

Config File and geth launch settings do not match.

Here are my launch settings which I launch from a here: etc/systemd/system/geth.service
ExecStart=geth --datadir /home/chain/data --syncmode "snap" --http --http.addr localhost --http.port 1045 --ws --ws.addr localhost --ws.port 1046 --metrics --cache=64000 --ws.origins '*' --ws.api eth,net,web3,txpool,debug --maxpeers 150 --rpc.allow-unprotected-txs --txlookuplimit 0

When I do geth dumpconfig > config.toml, I get the settings below (left out most of it)

[Node]
DataDir = "/root/.ethereum"
IPCPath = "geth.ipc"
HTTPHost = ""
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth"]
WSHost = ""
WSPort = 8546
WSModules = ["net", "web3", "eth"]
GraphQLVirtualHosts = ["localhost"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false

**Comment by MariusVanDerWijden** [comment]
`geth dumpconfig`will dump the default config. You need to do 
```
geth dumpconfig --datadir /home/chain/data --syncmode "snap" --http --http.addr localhost --http.port 1045 --ws --ws.addr localhost --ws.port 1046 --cache=64000 --ws.origins '*' --ws.api eth,net,web3,txpool,debug --maxpeers 150 --rpc.allow-unprotected-txs --txlookuplimit 0
```
In order to dump your config
