### ISSUE TITLE
snapshot not old enough yet: need 128 more blocks

### ISSUE THREAD

**Issue by hebeillc** [ethereum/go-ethereum#24626]
Hi， i try to run 'geth snapshot prune-state --datadir /data/geth/ethereum/', it reported an error
```
INFO [04-01|17:48:29.116] Maximum peer count                       ETH=50 LES=0 total=50
INFO [04-01|17:48:29.116] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [04-01|17:48:29.117] Set global gas cap                       cap=25,000,000
INFO [04-01|17:48:29.118] Allocated cache and file handles         database=/data/geth/ethereum/geth/chaindata cache=408.00MiB handles=524,288
INFO [04-01|17:49:17.399] Opened ancient database                  database=/data/geth/ethereum/geth/chaindata/ancient readonly=false
INFO [04-01|17:49:17.480] Snapshot loaded                          diskRoot=919fcc..03b422 root=919fcc..03b422
INFO [04-01|17:49:18.436] Initialized state bloom                  size=2.00GiB
ERROR[04-01|17:49:18.628] Failed to prune state                    err="snapshot not old enough yet: need 128 more blocks"
snapshot not old enough yet: need 128 more blocks
```
How can I solve this problem? thanks

**Comment by MariusVanDerWijden** [comment]
You need to let the node run with the snapshot for a bit longer, otherwise we can not prune the trie

**Comment by rjl493456442** [comment]
@hebeillc It's not ethereum network. We don't know how to handle bsc situation. Close it now.

**Comment by bixia** [comment]
i encounter the same problem with ethereum mainnet. but i dont know how to run with snapshot? what this mean?

**Comment by MariusVanDerWijden** [comment]
The snapshot will be automatically generated for you. Your log should contain a bunch of `Generating state snapshot` log lines. You need to wait until the snapshot is fully generated until you can prune

**Comment by bixia** [comment]
do i need to switch the sync mode from full to snap? because currently, i choose the sync mode to be full. and it has been running for 2 month.
