### ISSUE TITLE
Feature: Downgrade `Snapshot extension registration failed` to `WARN`

### ISSUE THREAD

**Issue by yorickdowne** [ethereum/go-ethereum#24653]
# Rationale

Given that `ERROR[04-06|13:38:24.463] Snapshot extension registration failed   peer=2005b987 err="peer connected on snap without compatible eth support"` is a) common and b) not at all in the control of the operator, downgrading this message to `WARN` would simplify alerting.

Ideally, `ERROR` and `CRIT` logs are issued for things that are indeed an issue and under the control of the operator to do something about.

**Comment by holiman** [comment]
Ok, done: https://github.com/ethereum/go-ethereum/pull/24475
