### ISSUE TITLE
geth attach with --ipcpath always looks at default Ethereum dir

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#2465]
#### System information

Geth version: 1.4.0-unstable
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Used to attach and open a geth console (maybe version 1.3.6 worked)

#### Actual behaviour
Fatal: Unable to attach to geth: dial unix /home/user/.ethereum/geth.ipc: connect: no such file or directory

#### Steps to reproduce the behaviour
Run geth with datadir.  Make sure there is no default Ethereum dir.

geth --ipcpath ./geth.ipc attach

#### Backtrace

````
[backtrace]
````

**Comment by ethers** [comment]
dupe of #2429

**Comment by Charliethewind** [comment]
I met the same problem:
Fatal: Unable to attach to geth: dial unix /home/user/.ethereum/geth.ipc: connect: no such file or directory

**Comment by Charliethewind** [comment]
This helps: geth --ipcpath "./geth.ipc" attach

**Comment by jechol** [comment]
I met the same.

`geth --ipcpath ./geth.ipc attach`

`Fatal: Unable to attach to remote geth: dial unix /Users/xxx/Library/Ethereum/geth.ipc: connect: no such file or directory`

What should I do?

**Comment by helxsz** [comment]
I had the same error. how to solve it ?

**Comment by lmars** [comment]
You should pass the path as an argument to `geth attach` (so for example `geth attach ./geth.ipc`).
