### ISSUE TITLE
"unexpected type float64 for Long" error when run graphql with parameters of type Long

### ISSUE THREAD

**Issue by ngugcx** [ethereum/go-ethereum#24683]
#### System information

Geth version: `geth version`
```
/ # geth version
Geth
Version: 1.10.17-stable
Git Commit: 25c9b49fdb74931137431c24cf28d3c65f9420d2
Architecture: amd64
Go Version: go1.18
Operating System: linux
```
OS & Version: Windows/Linux/OSX
```
/ # uname -a
Linux 69c4dda6023d 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 Linux
```
Commit hash : (if `develop`)

#### Expected behaviour
```
curl 'http://localhost:8545/graphql' --data-raw $'{"query":"query blocks($from_: Long!, $to_: Long!) {  blocks(from: $from_, to: $to_) {    number    hash    timestamp  }}","variables":{"from_":14000000,"to_":14000001},"operationName":"blocks"}'
```
It should return the specified block info.

#### Actual behaviour
It returns:
```
{"errors":[{"message":"unexpected type float64 for Long"}],"data":{}}
```

#### Steps to reproduce the behaviour
Run geth as below:
```
geth --txlookuplimit=1000000 --http --http.addr=0.0.0.0 --http.api eth,net,web3 --http.corsdomain="*" --http.vhosts="*" --graphql --graphql.corsdomain="*" --graphql.vhosts="*" --ws --ws.addr=0.0.0.0 --ws.api eth,net,web3
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by Kantitad** [comment]
:[25c9b49fdb74931137431c24cf28d3c65f9420d2]


เมื่อ วันอังคารที่ 12 เมษายน ค.ศ. 2022, ngugcx ***@***.***>
เขียนว่า:

**Comment by ngugcx** [comment]
> 

What do you mean? Thanks.

**Comment by s1na** [comment]
Try sending the values as strings, i.e.:

`"variables":{"from_":"14000000","to_":"14000001"}`

**Comment by ngugcx** [comment]
> Try sending the values as strings, i.e.:
> 
> `"variables":{"from_":"14000000","to_":"14000001"}`

Yes, strings work.
Why integers are always parsed as float? JSON has integer type.

**Comment by s1na** [comment]
So interestingly this only happens when using variables. Embedding the value in the query itself works fine, e.g. `query block(num: 14000000) { hash }` works ok.
