### ISSUE TITLE
How to properly sign an Ethereum transaction?

### ISSUE THREAD

**Issue by ninaprod** [ethereum/go-ethereum#24687]
I'm learning Ethereum on GOlang. I work through Ganache GUI. I'm trying to make a transfer from 1 wallet to another, but I get an error at the stage of sending a transaction through the client. I think the problem is in the config where I sign the transaction. Tell me what config is needed for my transaction?

`tx := types.NewTx(&types.DynamicFeeTx{
    Nonce:     nonce,
    GasTipCap: gasTipCap,
    GasFeeCap: gasFeeCap,
    Gas:       gas,
    To:        &toAdress,
    Value:     value,
    Data:      data})

config, block := params.TestChainConfig, params.TestChainConfig.MuirGlacierBlock

signer := types.MakeSigner(config, block)

signedTx, err := types.SignTx(tx, signer, privateKey)
if err != nil {
    log.Fatal("Unable to sign TX")
}

if err != nil {
    log.Fatal("Unable to cast to raw txn")
}

err = client.SendTransaction(context.Background(), signedTx)

if err != nil {
    log.Fatal("Unable to submit transaction")
}

fmt.Printf("tx sent: %s", signedTx.Hash().Hex())`

**Comment by ninaprod** [comment]
`tx := types.NewTx(&types.DynamicFeeTx{
Nonce: nonce,
GasTipCap: gasTipCap,
GasFeeCap: gasFeeCap,
Gas: gas,
To: &toAdress,
Value: value,
Data: data})

config, block := params.TestChainConfig, params.TestChainConfig.MuirGlacierBlock

signer := types.MakeSigner(config, block)

signedTx, err := types.SignTx(tx, signer, privateKey)
if err != nil {
log.Fatal("Unable to sign TX")
}

if err != nil {
log.Fatal("Unable to cast to raw txn")
}

err = client.SendTransaction(context.Background(), signedTx)

if err != nil {
log.Fatal("Unable to submit transaction")
}

fmt.Printf("tx sent: %s", signedTx.Hash().Hex())`

**Comment by MariusVanDerWijden** [comment]
You are using the TestChainConfig to initiate the signer. Ganache probably uses a different config.
Easiest way to get a correct signer is `types.NewLondonSigner(chainid)` with the correct chainid.
Please use the stackexchange for these types of questions in the future: https://ethereum.stackexchange.com/

**Comment by ninaprod** [comment]
``> You are using the TestChainConfig to initiate the signer. Ganache probably uses a different config. Easiest way to get a correct signer is `types.NewLondonSigner(chainid)` with the correct chainid. Please use the stackexchange for these types of questions in the future: https://ethereum.stackexchange.com/

Not working :(


`	tx := types.NewTx(&types.DynamicFeeTx{
		Nonce:     nonce,
		GasTipCap: gasTipCap,
		GasFeeCap: gasFeeCap,
		Gas:       gas,
		To:        &toAdress,
		Value:     value,
		Data:      data})

	
	chainID, _ := client.ChainID(context.Background())
	signerTX := types.NewLondonSigner(chainID)
	fmt.Println("ChainID:", chainID)
	signedTx, err := types.SignTx(tx, signerTX, privateKey)
	if err != nil {
		log.Fatal("Unable to sign TX")
	}

	err = client.SendTransaction(context.Background(), signedTx)
	if err != nil {
		fmt.Println("Unable to submit transaction")
	}`
