### ISSUE TITLE
change password for an account

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#2468]
possible and worth adding to the roadmap?

**Comment by fjl** [comment]
Please be more specific. The password of an existing account can be changed through the CLI using `geth account update <address>`. Do you mean that it should be possible using the ["personal" API](https://github.com/ethereum/go-ethereum/wiki/Go-ethereum-management-API's#personal)?

**Comment by ethers** [comment]
I missed `geth account update`; I think that should work.  Thanks
