### ISSUE TITLE
You are using the TestChainConfig to initiate the signer. Ganache probably uses a different config.

### ISSUE THREAD

**Issue by ninaprod** [ethereum/go-ethereum#24688]
You are using the TestChainConfig to initiate the signer. Ganache probably uses a different config.
Easiest way to get a correct signer is `types.NewLondonSigner(chainid)` with the correct chainid.
Please use the stackexchange for these types of questions in the future: https://ethereum.stackexchange.com/

_Originally posted by @MariusVanDerWijden in https://github.com/ethereum/go-ethereum/issues/24687#issuecomment-1096755360_

**Comment by ninaprod** [comment]
> 

invalid remainder

**Comment by MariusVanDerWijden** [comment]
You mean invalid signer?

**Comment by rjl493456442** [comment]
Are you sending transactions to ganache? Do you enable the london forks by default in your simulation chain(perhaps ganache)?

**Comment by holiman** [comment]
stale, no response, closing
