### ISSUE TITLE
confusing about mining

### ISSUE THREAD

**Issue by xiao199301** [ethereum/go-ethereum#24695]
NAME:
   geth.exe - the go-ethereum command line interface

   Copyright 2013-2022 The go-ethereum Authors

VERSION:
   1.10.18-unstable

I want to know why our mining address is always over 180% effort for 4 consecutive blocks, and now the 5th block is still over 180% or no block? I want you to check the mining data for us, is there any problem? Because the submitted verification work is Invalid proof-of-work submitted 

console output log：

WARN [04-14|17:43:44.239] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:44.279] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:44.313] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:44.339] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:44.403] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:44.533] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed="513µs"   err="invalid proof-of-work"
WARN [04-14|17:43:44.546] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:44.550] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:44.647] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:44.687] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed="554.7µs" err="invalid proof-of-work"
WARN [04-14|17:43:44.752] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:44.775] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:44.809] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:44.872] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:44.892] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed="510.7µs" err="invalid proof-of-work"
WARN [04-14|17:43:44.946] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.042] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.127] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.173] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.213] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed="134.8µs" err="invalid proof-of-work"
WARN [04-14|17:43:45.265] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed="123.9µs" err="invalid proof-of-work"
WARN [04-14|17:43:45.387] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.431] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.445] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.562] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.568] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.577] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.720] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.755] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.823] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.827] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.829] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.831] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:45.912] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
INFO [04-14|17:43:45.962] Imported new chain segment               blocks=1  txs=321  mgas=29.929  elapsed=174.366ms mgasps=171.643  number=14,582,798 hash=150b23..751017 dirty=1023.13MiB
INFO [04-14|17:43:45.966] Commit new sealing work                  number=14,582,799 sealhash=939c5b..619572 uncles=0 txs=0    gas=0          fees=0               elapsed=0s
INFO [04-14|17:43:45.967] Unindexed transactions                   blocks=1  txs=192  tail=12,232,799 elapsed="998.1µs"
INFO [04-14|17:43:46.041] Commit new sealing work                  number=14,582,799 sealhash=eb25f9..048051 uncles=0 txs=34   gas=4,167,861  fees=0.01075861723   elapsed=75.311ms
WARN [04-14|17:43:46.209] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:46.252] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:46.411] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:46.418] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:46.456] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:46.508] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:46.531] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:46.572] Invalid proof-of-work submitted          sealhash=5569b0..931e97 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:46.682] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:46.764] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:46.787] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:46.798] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:46.918] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:47.000] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:47.115] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed="542.2µs" err="invalid proof-of-work"
WARN [04-14|17:43:47.282] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed="509.5µs" err="invalid proof-of-work"
WARN [04-14|17:43:47.378] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:47.392] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:47.437] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:47.753] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:47.792] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:47.836] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:48.032] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"
WARN [04-14|17:43:48.058] Invalid proof-of-work submitted          sealhash=eb25f9..048051 elapsed=0s        err="invalid proof-of-work"

**Comment by rjl493456442** [comment]
Your remote sealers are always submitting invalid proof-of-work solution, you may want to check your miners?

`over 180% effort for 4 consecutive blocks` what do you mean by this?

**Comment by xiao199301** [comment]
> Your remote sealers are always submitting invalid proof-of-work solution, you may want to check your miners?
> 
> `over 180% effort for 4 consecutive blocks` what do you mean by this?
Since the work sent to me by the mainnet is too difficult, I will split it, so I don’t know if the invalid submission will have computing power on the mainnet. I want to know if the work I submitted is useful on the mainnet? The first 3 blocks are normal, and the mining computing power of the last 4 blocks exceeds 180% of the normal difficulty. Now the fifth block has exceeded the difficulty by more than 260%. 

Is there any way to check my mining computing power on the mainnet?
