### ISSUE TITLE
Request transaction hash in ropsten network returns null？

### ISSUE THREAD

**Issue by ajaxcom** [ethereum/go-ethereum#24690]
Request transaction hash in ropsten network returns null？

--syncmode "light"

Do I need to download the full block to find the testnet transaction hash?

**Comment by ajaxcom** [comment]
![1649814918(1)](https://user-images.githubusercontent.com/29726828/163084185-f246f513-5482-466f-8a68-cb1323dffc29.png)
![1649814915(1)](https://user-images.githubusercontent.com/29726828/163084188-05152e91-0def-4230-b6bb-cf2f3ddcd669.png)

**Comment by rjl493456442** [comment]
Can you check the log in the Geth? I think there is no suitable peer(LES Server) can serve your request.

**Comment by ajaxcom** [comment]
All my return values are
![1649835753(1)](https://user-images.githubusercontent.com/29726828/163125588-23503aeb-55a3-4ddd-a377-a51d6c142c63.png)

Whether the parameter is missing at startup？

geth --datadir ./data --syncmode "light" --ropsten --http -http.port 3335 console

**Comment by rjl493456442** [comment]
Yeah, since light client relies on les server(normal full node) to serve the requests, but right now you have no suitable peers to do it.

You can check the connected peers by attaching the ipc, `geth attach <your-datadir>/geth.ipc`, then type `admin.peers.length`. 

But honestly it's not that easy to find the servers since the les serving is disabled by default.

**Comment by s1na** [comment]
> it's not that easy to find the servers since the les serving is disabled by default.

Specially for testnets I imagine. Unfortunately not much we can do about it. If you didn't have more luck in finding light servers I recommend using `--syncmode snap`. That takes much longer and needs more storage but you'll find peers to sync from and then you'll have all the data you'll need locally. Closing this issue for now.
