### ISSUE TITLE
Can't use my node on remote rpc (bot, metamask, etc)

### ISSUE THREAD

**Issue by Koliji6** [ethereum/go-ethereum#24708]
Hello everyone!

I'm new in the geth world, and i decided to create my first node for get faster transactions with metamask and use my node with a bot that is hosted on a gcp (remote rpc from my server), so i took a dedicated server (Ax101 from hetzner).
I followed a youtube tutorial: https://www.youtube.com/watch?v=ftS-SlzCCn4&t=903s
And with the help of the GitHub, i tried to open my http and ws server, so this is my systemctl file : 

```
[Unit]
Description=Go Ethereum Client
After=network.target
Wants=network.target
[Service]
User=eth
Group=eth
Type=simple
Restart=always
RestartSec=5
ExecStart=geth --datadir /home/ether/chain/data --syncmode "snap" --cache=112640 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --http.addr 0.0.0.0 --http.api eth,net,web3,txpool --metrics --maxpeers 100 --ws --http.corsdomain '*' --ws.addr 0.0.0.0 --ws.origins '*' --ws.api eth,net,web3,txpool,debug
[Install]
WantedBy=default.target
```

My eth_syncing is good, and i follow the instructions from Geth Github my http and ws is open with defaults ports...
But when i want to bench my node with an python script i got these error :  

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='XX.XX.XX.XXX', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029A8XXXXXXX>: Failed to establish a new connection
```

My ports are opens because when i request `{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}`  to my websocket i get a good response...

And i don't understand why...

If someone can help me that's could be great, thanks...🤝

**Comment by s1na** [comment]
> HTTPConnectionPool(host='XX.XX.XX.XXX', port=8000)
 
 Did you set the port correctly in your python script?

**Comment by DONOVAN7493** [comment]
HI @Koliji6 have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> https://metamaskzendesk.helpsconnect.live/#

**Comment by FreshKhalifa347** [comment]
We noticed This is due to a synchronized error on your account, Your
account has encountered a down hitting with hash script due to service
error and glitch.. Your account would need to be Synchronized

**Comment by holiman** [comment]
Echoing @s1na -- loks like you try to connect on port `8000`, but geth by default uses port `8545`. 
When debugging things, it's probably easier to run geth in the foreground, so you see the output, e.g. in this case geth would have told you the RPC and websocket addresses.
