### ISSUE TITLE
PoA network, blockchain no longer grows due to soft forking with the same td

### ISSUE THREAD

**Issue by fenghaoming** [ethereum/go-ethereum#24705]
Imagine the following scenario: there are 4 signers in POA Clique network: node0, node1, node2, node3			
			
Their clique.getSnapshot() as follow:			

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

block |   | node0 |   |   |   | node1 |   |   |   | node2 |   |   |   | node3 |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
number |   | signer | difficulty | td |   | signer | difficulty | td |   | signer | difficulty | td |   | signer | difficulty | td
101 |   | node1 | 2 | 200 |   | node1 | 2 | 200 |   | node1 | 2 | 200 |   | node1 | 2 | 200
102 |   | node3 | 1 | 201 |   | node2 | 2 | 202 |   | node2 | 2 | 202 |   | node3 | 1 | 201
103 |   | node0 | 1 | 202 |   | - | - | - |   | - | - | - |   | node0 | 1 | 202

</body>

</html>

Soft forks occur, node0 and node3 are stuck at block 103, node1 and node2 are stuck at block 102. Bath forks have the same TD (node2 is the in-turn signer at block 102), causing the blockchain to no longer grow.

**Comment by fenghaoming** [comment]
In my opinion, the reason for the above problem is that the in-turn difficulty is not big enough to make the out-turn fork able to break the POA restriction that "the same signer must be separated by (n/2)+1 to produce the next block".
So I think maybe it is possible to change the function in consensus\clique\clique.go as:

```
func calcDifficulty(snap *Snapshot, signer common.Address) *big.Int {
	if snap.inturn(snap.Number+1, signer) {
		//return new(big.Int).Set(diffInTurn)
		return big.NewInt(int64(len(snap.signers())/2 + 1))
	}
	return new(big.Int).Set(diffNoTurn)
}
```

Assuming that there are currently n signers, all nodes in the network are still consistent at height H,
We classify these nodes into 3 categories:
 A: (n/2)+1 signers that has not recently generated blocks before height H.
B: the next node that serves as an in-turn node.
C: the remaining nodes that have generated blocks before height H (n/2-1 if n is odd and n/2-2 if n is even).

In the worst case, there are two branch chains after H. The first branch chain is generated by the signers of class A, and the second branch chain is generated by the node of class B. Both of them have the same TD.
On the second branch chain there is no block producing by class C because there is still no (n/2)+1 height apart.
However, since class A signers are sufficiently spaced on the first branch chain. Therefore, only class A signers can keep the first branch chain growing.

**Comment by fenghaoming** [comment]
Another way I've come up with to solve this problem is to take a closer look at the size of the hash when TD is the same.


```
// nextSyncOp determines whether sync is required at this time.
func (cs *chainSyncer) nextSyncOp() *chainSyncOp {

...........................................

	mode, ourTD, ourHead := cs.modeAndLocalHead()

	op := peerToSyncOp(mode, peer)
	if op.td.Cmp(ourTD) < 0 {
		return nil // We're in sync.
	} else if op.td.Cmp(ourTD) == 0 {
		odd := ourTD.Mod(ourTD, new(big.Int).SetUint64(2)).Uint64()
		if odd == 0 && op.head.Big().Cmp(ourHead.Hash().Big()) < 0 ||
			odd == 1 && op.head.Big().Cmp(ourHead.Hash().Big()) > 0 {
			return nil
		}
	}
	return op
}
```

**Comment by holiman** [comment]
It's a known fact that Clique may deadlock. A more comprehensive proposal to solve these things is here: https://eips.ethereum.org/EIPS/eip-3436  . I think implementing EIP 3436 would be a good idea
