### ISSUE TITLE
Travis is showing "Page Not Found"

### ISSUE THREAD

**Issue by yadunandanbhat** [ethereum/go-ethereum#24706]
The Travis build page is showing page not found for the [link](https://www.travis-ci.com/ethereum/go-ethereum). And also the travis build badge is showing error. is that normal?

**Comment by MariusVanDerWijden** [comment]
We're currently migrating our ci pipeline away from travis to selfhosted builders. The travis builds have been broken for a while now

**Comment by yadunandanbhat** [comment]
Okay cool!
