### ISSUE TITLE
What format is the second parameter of eth_sign?

### ISSUE THREAD

**Issue by ajaxcom** [ethereum/go-ethereum#24716]
{"jsonrpc":"2.0","method":"eth_sign","params":["**", "0xdeadbeaf"],"id":1}

Here is an example

Ignoring the first parameter, what format is the second parameter?

{"jsonrpc":"2.0","method":"eth_sign","params":["**", "hello"],"id":1}

Should I convert "hello" to hex and concatenate 0x?

{"jsonrpc":"2.0","method":"eth_sign","params":["**", "0x68656c6c6f"],"id":1}

**Comment by karalabe** [comment]
The first parameter is the address to sign with and the second parameter is the data blob to sign?

**Comment by ajaxcom** [comment]
> 第一个参数是要签名的地址，第二个参数是要签名的数据块？
I noticed this formula 

sign(keccak256("\x19Ethereum Signed Message:\n" + len(message) + message)))

Sign a message with a formula?

the result as the second parameter

**Comment by s1na** [comment]
Yes the second parameter takes in a byte array in hex format (prefixed with `0x`). And it will use the formula you mentioned for signing.

> Should I convert "hello" to hex and concatenate 0x?

Yes. Or you can hash your message before feeding it into the `eth_sign` method.
