### ISSUE TITLE
--txpool.pricelimit is ignored. --miner.gasprice acts like --txpool.pricelimit

### ISSUE THREAD

**Issue by Anti83** [ethereum/go-ethereum#24718]
#### System information

Version: 1.10.17-stable
Git Commit: 25c9b49fdb74931137431c24cf28d3c65f9420d2
Architecture: amd64
Go Version: go1.18

#### Expected behaviour

1. Transactions with gasPrice above --txpool.pricelimit should get into txpool.
2. Transactions with gasPrice above --miner.gasprice should get into pending block(block being mined if --mine is specified).

If geth is started with --mine --txpool.pricelimit 1 --miner.gasprice 100000000000
Transactions with gasPrice above 1 will enter txpool.
Only transactions with gasPrice above 100000000000 will enter pending block.

#### Actual behaviour
If geth is started with --mine --txpool.pricelimit 1 --miner.gasprice 100000000000 , 
Only transactions with gasPrice above 100000000000 get into **txpool**.

So --miner.gasprice starts to act like --txpool.pricelimit
#### Steps to reproduce the behaviour
Start geth with --mine --txpool.pricelimit 1 --miner.gasprice 100000000000  and subscribe to "pendingTransactions"

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
This is intended, if you specify a gas limit for mining, that will be enforced on the pool too. This is mostly necessary to not do double accounting and enforce prices in two different locations. The txpool acts as the actual price filtering for the miner.
