### ISSUE TITLE
9 hours of sustained heavy disk read activity

### ISSUE THREAD

**Issue by mining-visualizer** [ethereum/go-ethereum#24728]
#### System information

Geth version: 1.10.18-unstable
OS & Version: Ubuntu 20.04
Commit hash : f0328f241b7c3def217b0c2dce1a1b297f979a37  (20220413)

Raspberry Pi, 8GB, 1TB Samsung SSD

I installed prometheus/grafana about a month ago and have been watching my geth node.  About 4 times now I have seen geth engage in sustained, fairly heavy (20-30 MB/s) disk read activity, for quite long periods of time (5-9 hours).

If this is a feature I am curious what geth is doing.  If this is a bug/issue, I would be happy to provide more information if I can.

![Screenshot 2022-04-20 193717](https://user-images.githubusercontent.com/30419645/164378034-850a59ee-224c-411e-a739-da0eed855163.png)

![Screenshot 2022-04-20 193753](https://user-images.githubusercontent.com/30419645/164378522-2a43c107-4fcb-4528-9da9-3d9f4ef65745.png)

**Comment by s1na** [comment]
If I were to guess someone is syncing from you.
