### ISSUE TITLE
Differentiate CREATE and CREATE2 opcodes in native tracers

### ISSUE THREAD

**Issue by evanzbitgo** [ethereum/go-ethereum#24727]
# Rationale
We want to differentiate CREATE and CREATE2 opcodes in native tracers. We can do that in JS tracers.

```
func (t *noopTracer) CaptureStart(env *vm.EVM, from common.Address, to common.Address, create bool, input []byte, gas uint64, value *big.Int) {
}
```
We only have a boolean parameter called `create` to indicate if it is CREATE2 or CREATE

Why should this feature exist?

What are the use-cases?
We want to differentiate CREATE and CREATE2 opcodes and have different handling mechanisms.

# Implementation

Do you have ideas regarding the implementation of this feature?
No
Are you willing to implement this feature?
Yes

**Comment by s1na** [comment]
`CaptureStart` is only called at the beginning of the transaction. The `create` flag indicates if its a create transaction (i.e. `tx.to` is empty) or not. I don't think create transactions can generate `CREATE2`-style addresses.

You should instead use `CaptureEnter` which is for every call frame (except topmost one). It has a `typ` parameter which you can check like `typ == vm.CREATE2`.

**Comment by evanzbitgo** [comment]
Oh, that makes perfect sense. The top-level trace does not map to an "actual" opcode thus it does not matter if it is CREATE or CREATE2.

Thank you, closing this issue.
