### ISSUE TITLE
eth: eth_call requires block as last parameter

### ISSUE THREAD

**Issue by datajerk** [ethereum/go-ethereum#2472]
#### System information

Geth version: 

```
Geth
Version: 1.4.0-unstable
Git Commit: 27116bd46cbc14a8eec9e1818945f1f10b9b834a
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.3
OS: linux
GOPATH=
GOROOT=/usr/lib/go
```

OS & Version: `Linux 6fc65e9ad3f4 4.1.8-hypriotos-v7+ #2 SMP PREEMPT Wed Sep 30 19:37:28 UTC 2015 armv7l GNU/Linux`

Commit hash : `27116bd46cbc14a8eec9e1818945f1f10b9b834a`

#### Expected behaviour (geth 1.3.5)

```
$ curl -sL http://127.0.0.1:8545 -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0xa6c80e03727bb386f0cbd62959d1f08bdc1dcc54","data":"0x75d74f39"}],"id":1}' | jq -r '.'
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": "0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001472616e646f6d206d657373616765203133373137000000000000000000000000"
}
```

#### Actual behaviour (geth 1.4 develop)

```
$ curl -sL http://127.0.0.1:8545 -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x4f227306c9a15bf656971b09663a1bf0d5de1cb5","data":"0x75d74f39"}],"id":1}' | jq -r '.'
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32602,
    "message": "invalid or missing value for params[1]"
  }
}
```

#### Steps to reproduce the behaviour

`eth_call`

#### Backtrace

````
[backtrace]
````

**Comment by obscuren** [comment]
Pling @bas-vk

**Comment by fjl** [comment]
The error occurs because the "default block parameter" is missing.
The spec doesn't say that it is optional, but I think it is more convenient
to default it to "latest".

**Comment by datajerk** [comment]
@fjl thanks!  I'll make sure all of our RPC code uses "latest" and retest.  Thanks.

**Comment by datajerk** [comment]
BTW I was going to test "latest", but then it was ~4am my time and I forgot before submitting issue.
