### ISSUE TITLE
Add `TotalDifficulty` to `types.Header`

### ISSUE THREAD

**Issue by nathanwiegand** [ethereum/go-ethereum#24732]
# Rationale

Why should this feature exist?
The JSON RPC client already exposes `totalDifficulty` but this field is missing from the Go ethclient since it unmarshals the response into `types.Header`.

What are the use-cases?

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by s1na** [comment]
Please refer to https://github.com/ethereum/go-ethereum/pull/24754#issuecomment-1108300063.
