### ISSUE TITLE
How to get transaction of pending using rpc?

### ISSUE THREAD

**Issue by huluBrother** [ethereum/go-ethereum#24737]
when using rpc access to peer of ethereum , I only found what as follow .
```
txpool
{
  content: {
    pending: {},
    queued: {}
  },
  inspect: {
    pending: {},
    queued: {}
  },
  status: {
    pending: 0,
    queued: 0
  },
  contentFrom: function(),
  getContent: function(callback),
  getInspect: function(callback),
  getStatus: function(callback)
}
```
How can I get transaction of pending?

**Comment by s1na** [comment]
Your txpool seems to be empty. It might be that you're still syncing. Various RPC methods can work with pending transactions. I can help you more if you give some more details on what you're trying to do. If you want to subscribe to new pending transactions you can use `eth_newPendingTransactionFilter`.

**Comment by c0yax** [comment]
> 

panic: no "eth_newPendingTransactionFilter" subscription in eth namespace

**Comment by c0yax** [comment]
it should be this 'newPendingTransactions'

**Comment by s1na** [comment]
Yes please see the [docs](https://geth.ethereum.org/docs/rpc/pubsub) for subscriptions. Closing the issue now, feel free to re-open if your issue wasn't resolved.
