### ISSUE TITLE
Geth won't run with the flag --miner.gasLimit 50000000

### ISSUE THREAD

**Issue by sandakersmann** [ethereum/go-ethereum#24746]
Got this error: 

`flag provided but not defined: -miner.gasLimit`

Must the value be in hex or something? People need to know how to vote the gas limit up or down after the merge.

**Comment by eval-exec** [comment]
What's your geth version?

**Comment by eval-exec** [comment]
```bash
❯ ./build/bin/geth -h | grep miner.gaslimit
  --miner.gaslimit value              Target gas ceiling for mined blocks (default: 8000000)
```

It's ` --miner.gaslimit` not ` --miner.gasLimit`
