### ISSUE TITLE
@rjl493456442 @mcdee yeah, having thought about it some more, i'm thinking to not bother with the hash tree root here and use the usual algorithm for determining the transaction hash

### ISSUE THREAD

**Issue by gaowhire** [ethereum/go-ethereum#24753]
@rjl493456442 @mcdee yeah, having thought about it some more, i'm thinking to not bother with the hash tree root here and use the usual algorithm for determining the transaction hash

_Originally posted by @ralexstokes in https://github.com/ethereum/go-ethereum/issues/24468#issuecomment-1055839753_

**Comment by rjl493456442** [comment]
Close it. Please keep the discussion under the original PR.
