### ISSUE TITLE
package github.com/ethereum/go-ethereum is not a main package

### ISSUE THREAD

**Issue by Imagine-Brian** [ethereum/go-ethereum#24756]
I used this command:
`go install github.com/ethereum/go-ethereum@v1.10.17` 
An error occurred
`package github.com/ethereum/go-ethereum is not a main package`
What should I do

**Comment by s1na** [comment]
If you want to install the geth binary (as opposed to getting the source code which you can do via `go get`) you should do the following:

```
go install github.com/ethereum/go-ethereum/cmd/geth@v1.10.17
```

See more installation methods here: https://geth.ethereum.org/docs/install-and-build/installing-geth

**Comment by Imagine-Brian** [comment]
Excuse me, sir.
I need to use ethclient in my golang code.

**Comment by Imagine-Brian** [comment]
> If you want to install the geth binary (as opposed to getting the source code which you can do via `go get`) you should do the following:
> 
> ```
> go install github.com/ethereum/go-ethereum/cmd/geth@v1.10.17
> ```
> 
> See more installation methods here: https://geth.ethereum.org/docs/install-and-build/installing-geth

Excuse me, sir.
I need to use ethclient in my golang code.

**Comment by jaho8** [comment]
go install github.com/ethereum/go-ethereum@v1.10.17
