### ISSUE TITLE
BPM and ETA on snap sync

### ISSUE THREAD

**Issue by morphex** [ethereum/go-ethereum#24778]
# Rationale

Why should this feature exist?

It's nice to see ca when the node is done syncing, and current performance.

What are the use-cases?

Client-side use of the node as a query and development server, in relation to this issue:

https://github.com/ethereum/go-ethereum/issues/24768

# Implementation

Do you have ideas regarding the implementation of this feature?

Should be fairly straightforward.

Are you willing to implement this feature?

No.  I have too much other stuff going on.

**Comment by karalabe** [comment]
Naps sync does log an ETA for the first phase:

```
INFO [04-29|12:56:32.924] State sync in progress                   synced=57.49% state=96.24GiB   accounts=99,870,455@22.70GiB slots=357,946,914@71.61GiB codes=342,879@1.94GiB    eta=2h4m56.981s
```

I.e. last field.

The healing phase is more problematic, as we don't know how much data changed i between (generally, the slower you sync, the more data that needs to be fixed). There's no way to put an ETA on this with the current protocol specs (and maintaining the ability would be prohibitively expensive with the trie).

But given the ETA for the state phase and the fairly good stability of the chain sync phase, it should give you a generally useful idea of when you node will be done. Probably not good enough for an automated process, but there you can keep watching the head to prevent firing RPC requests before it's done.

**Comment by morphex** [comment]
OK. I would think that a verbose and proper feedback to the user (sysadmin) would be good for Ethereum in general as well, as it is easier to know what's going on, and what needs to be fixed.

I think more than one person has been frustrated by the syncing process and lack of feedback, meaning less people are running a node than what there could have been. And nodes are a backbone and an important part of the security of Ethereum, aren't they?

**Comment by holiman** [comment]
It would be awesome to provide ETA on snap sync. We do what we can, which is better than what was possible with fast-sync, but it's still a phase towards the end which is simply not easily estimated. 

Kind of the only way to even _try_ to estimate it would be to build some very complex estimator based on heuristics over time, and it would still be a pretty large error-factor in it. 

I don't think this ticket is actionable (we know if the desire, we've heard it before, we agree, but we cannot fix it), so I'm closing this.
