### ISSUE TITLE
sendTx api_backend.go

### ISSUE THREAD

**Issue by berktaylan** [ethereum/go-ethereum#24774]
Hello,

Im new to Ethereum ecoysystem as well to golang, i was inspecting the codes

`func (b *EthAPIBackend) SendTx(ctx context.Context, signedTx *types.Transaction) error {
	return b.eth.txPool.AddLocal(signedTx)
}
`
And i see that function , im curious as i understand SendTx called with 2 variable, but only the second one ( signedTx ) used.
So why the ctx variable passed to this function ? Am i missing something ?

**Comment by rjl493456442** [comment]
Because we define the interface here https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/backend.go#L76 

This interface can be implemented by `ethBackend` and `lesBackend`. `ctx` is necessary for `lesBackend` so it's defined in interface, while in `ethBackend` it's not used.
