### ISSUE TITLE
rinkeby.io Faucet offline

### ISSUE THREAD

**Issue by ikubix** [ethereum/go-ethereum#24772]
It looks like Rinkeby is not working: Faucet Offline.

Is there another workaround?

Thanks!

**Comment by bansalraghav** [comment]
@ikubix 
I have tried a couple of other faucets in the last hour: 

1. https://faucets.chain.link/rinkeby - this will give you 0.1 eth every time and you can hit it multiple times. 
2. https://fauceth.komputing.org/ - this gave me 0.42 eth.
3. https://rinkebyfaucet.com/ - this will give you 0.5 eth if you signup with them.
