### ISSUE TITLE
unable to interact with one of my geth accounts

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#2479]
#### System information

Geth version: `1.4RC`
OS & Version: Windows/Linux/
Commit hash : (if `develop`)

I have been successfully using my coinbase account 
up until geth 1.35, recently I noticed that one of my accounts which just so happened to be my coinbase account was not showing up in my list of accounts after starting my geth node.

I know this to be the case because if I place the exact same keystore directory in an install of geth 1.35 I see my coinbase account just fine. When I place it in the more recent develop versions of 1.4 I do not see it in my list of accounts after I start the geth node.   

The only difference with this account is that it is contained in a subdirectory of the same account name inside the keystore directory. 

I am not sure if this has something to do with when the pre-frontier account keys were changed to a new format or not. I have had no problem using this key up until the past few weeks. 

I need to get it working as I have used it extensively for building contracts and other transactions.
This is NOT a password issue. I believe it to be a format issue. as I can see it and interact with that account in geth 1.35.

**Comment by fjl** [comment]
You will be able to use it by moving the file up one level (out of the subdirectory).

**Comment by rfikki** [comment]
Thanks, that fixed the issue. However I do notice that the account name is not in the same format as the others. It does not contain the UTC prefix. Should I do anything about that?

**Comment by fjl** [comment]
No. Restrictions on account file names have been removed in geth 1.4.

**Comment by rfikki** [comment]
Cool, thanks.
