### ISSUE TITLE
Ropsten network failed with geth:v1.10.17-1   

### ISSUE THREAD

**Issue by cramfrpark** [ethereum/go-ethereum#24797]
#### System information

Geth version: geth:v1.10.17-1   
OS & Version: ubuntu 20
Commit hash : (if `develop`)

#### Expected behaviour
```
INFO [04-10|22:54:35.141] Unindexed transactions                   blocks=1  txs=145  tail=12,210,742 elapsed=2.171ms
INFO [04-10|22:54:47.036] Deep froze chain segment                 blocks=7  elapsed=24.069ms    number=14,470,741 hash=584307..00361c
INFO [04-10|22:54:52.238] Imported new chain segment               blocks=1  txs=306  mgas=26.564  elapsed=474.666ms   mgasps=55.964  number=14,560,742 hash=92b5fb..a9fce3 dirty=765.98MiB
INFO [04-10|22:54:52.244] Unindexed transactions                   blocks=1  txs=148  tail=12,210,743 elapsed=5.888ms
INFO [04-10|22:54:55.568] Imported new chain segment               blocks=1  txs=30   mgas=3.453   elapsed=392.954ms   mgasps=8.788   number=14,560,743 hash=7a9656..abf569 dirty=765.63MiB
```

#### Actual behaviour
```
ERROR[04-30|16:50:53.580] Snapshot extension registration failed   peer=f077ef02 err="peer connected on snap without compatible eth support"
ERROR[04-30|16:50:54.743] Snapshot extension registration failed   peer=9d4f3150 err="peer connected on snap without compatible eth support"
ERROR[04-30|16:50:58.856] Snapshot extension registration failed   peer=a4da81c9 err="peer connected on snap without compatible eth support"
INFO [04-30|16:51:00.704] Looking for peers                        peercount=0 tried=41 static=0
ERROR[04-30|16:51:01.078] Snapshot extension registration failed   peer=d77a3ca8 err="peer connected on snap without compatible eth support"
WARN [04-30|16:51:08.236] Served eth_chainId                       conn=172.18.0.4:34060 reqid=42 duration="28.947µs" err="chain not synced beyond EIP-155 replay-protection fork block"
ERROR[04-30|16:51:10.411] Snapshot extension registration failed   peer=57f7ebfb err="peer connected on snap without compatible eth support"
INFO [04-30|16:51:10.705] Looking for peers                        peercount=0 tried=38 static=0
WARN [04-30|16:51:18.958] Synchronisation failed, dropping peer    peer=8e4f4ef764b1a149c1d9f3542478f025167d7a95441e849d97f0e4db6bd435c7 err=timeout
ERROR[04-30|16:51:19.934] Snapshot extension registration failed   peer=02c5bdde err="peer connected on snap without compatible eth support"
INFO [04-30|16:51:20.790] Looking for peers                        peercount=0 tried=40 static=0
```
#### Steps to reproduce the behaviour
View logs after updating geth to newer version. 

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by holiman** [comment]
How long did you let it run? 
What was the command line parameters? 

I suspect it just takes a while to find suitable peers on Ropsten.

**Comment by cramfrpark** [comment]
currently running for two days now. Command parameters :                "--graphql",
                "--graphql.vhosts",
                "*",
                "--keystore",
                "/config/keys",
                "--datadir",
                "/data",
                "--config",
                "/config/config.toml",
                "--identity",
                "test-eth-geth-ropsten-2",
                "--ropsten",
                "--http",
                "--http.addr",
                "0.0.0.0",
                "--http.port",
                "8545",
                "--http.corsdomain",
                "*",
                "--http.vhosts",
                "*",
                "--http.api",
                "admin,eth,net,web3,txpool,debug",
                "--ws",
                "--ws.addr",
                "0.0.0.0",
                "--ws.port",
                "8546",
                "--ws.origins",
                "*",
                "--ws.api",
                "eth,net,web3,txpool,debug",
                "--port",
                "30303",
                "--cache",
                "3072",
                "--whitelist",
                "10920274=0xfd652086d220d506ae5b7cb80fde97d2f3f7028d346cc7d9d384a83d3d638532",
                "--metrics",
                "--pprof",
                "--pprof.addr",
                "0.0.0.0",
                "--pprof.port",
                "6060"

**Comment by cramfrpark** [comment]
@holiman need any more info?

**Comment by karalabe** [comment]
https://github.com/ethereum/go-ethereum/pull/24505 renamed the `whitelist` flag, and at the same time broke the code, causing a wrong hash to be enforced. You can drop that whitelist for now, it's not really needed. Will get the flag fixed in the next release.

Thanks for reporting!
