### ISSUE TITLE
Geth Web3 Version

### ISSUE THREAD

**Issue by dongseopAdena** [ethereum/go-ethereum#24806]
Hello.

I tired to open node by using Geth.
And I used web3, but the version of web3 in Geth is too old, 0.20.1...

I would like to know how I can update the Web3 version > 1.0.0

Thank you

**Comment by s1na** [comment]
At this point it is very unlikely that the web3 version used in Geth changes. What are you trying to do that's not possible with the old version?

**Comment by karalabe** [comment]
The new versions of web3js don't support the original blocking mode of operation that the console requires. Switching to promises is very cumbersome in the console, where w only debug stuff and want to be able to chain commands after one another without having to add sugarcoating all over the place. As Sina said, it's not gonna happen.

However, at this point you should just run a nodejs console and attach to geth directly and you can have all the latest and greatest stuff available, there's no particular reason to use Geth's built in stuff if you're going the javascript way.
