### ISSUE TITLE
Don't see a vmodule list on wiki

### ISSUE THREAD

**Issue by wawrzek** [ethereum/go-ethereum#2480]
I cannot find a list of modules on wiki. Such a list would make debugging easier.

**Comment by fjl** [comment]
For geth 1.3.x, the --vmodule flag matches the basename of Go source files.

For geth 1.4.x and beyond, it matches Go package names instead. You can see
all messages from package p2p using `--vmodule=p2p=6` and all messages from
packages p2p, p2p/nat, p2p/discover using `--vmodule=p2p/*=6`.

The 'list of modules' is effectively what you can see in the file system.

**Comment by wawrzek** [comment]
@fjl That fine answer for a developer, but I represent a new way of people which might to come - operations. Cloning git repo and running something like **ls -1 p2p/**/*.go(.)** (in zsh) is not a big issue for me, but there will be people who don't how to do that, or might not be able to this. Also listing all go modules is not enough. You still don't know where to look.

**Comment by fjl** [comment]
You can always run with `--verbosity=6` to enable all messages that could possibly be printed.
`--vmodule` is a developer-centric option.

**Comment by wawrzek** [comment]
Thanks for prompt response. I 'm going to check --verbosity - also to check how much logs there will be.
