### ISSUE TITLE
Additional question related [Geth Web3 Version #24806]

### ISSUE THREAD

**Issue by dongseopAdena** [ethereum/go-ethereum#24809]
Thank you for your reply.
I have one more question about the process to run related to ([Geth Web3 Version #24806])

I downloaded web3 @1.7.3
![npm ls web3](https://user-images.githubusercontent.com/104830426/166612867-87194630-06d4-4311-9008-4841f82fb353.png)

PS C:\Users\DongSeop> npm ls web3
DongSeop@ C:\Users\DongSeop
├─┬ @myetherwallet/eth-token-balance@0.2.2
│ └── web3@1.7.3 deduped
└── web3@1.7.3

But once I run [geth attach ~], the version of web3 is changed. 

I did things bleow:
 1. First, open Vs code and Terminal (powershell)
 2. run geth  in the terminal(A)
 3. And open new terminal(B) and run [geth attach "my IPC Endpoin"]
 4. run [web3. version] 
     =>  > web3.version
{
  api: "0.20.1",
  ethereum: undefined,
  network: "1",
  node: "Geth/v1.10.17-stable-25c9b49f/windows-amd64/go1.18",
  whisper: undefined,

  getEthereum: function(callback),
  getNetwork: function(callback),
  getNode: function(callback),
  getWhisper: function(callback)
}

![image](https://user-images.githubusercontent.com/104830426/166612905-30c937c0-e045-412a-84a8-753300f705fb.png)

the result is like above one. 

Could you check the order of running is something wrong ?

Ultimately, I want to use "web3.eth.Contract" and "methods()".

Thank you.

**Comment by karalabe** [comment]
Geth attach uses our own built in version of web3.js, which is old. You need to attach from nodejs, not Geth if you want to use a latest version https://web3js.readthedocs.io/en/v1.7.3/getting-started.html
