### ISSUE TITLE
ethclient.Client should support for upcoming block definitions (safe, unsafe, finalized)

### ISSUE THREAD

**Issue by marioevz** [ethereum/go-ethereum#24829]
# Rationale

- Why should this feature exist?
Engine API has concept for `safe` and `finalized` payloads within the ForkchoiceUpdated directive.
The execution spec does not require yet that these blocks are made available through the JSON-RPC, but it has been suggested and discussed several times in the ACD calls for example.
The ethclient.Client now support `latest` (nil) and `pending` (-1), but it would be useful to also support these new block concepts.

- What are the use-cases?
For the end-user it would be helpful to have these available, but also for implementing tests in hive, we currently use the ethclient.Client module to obtain information from JSON-RPC, and part of the new tests for the Engine API require that we query for `safe` and  `finalized` (I am not sure of the state of `unsafe` but it has been mentioned).

# Implementation

- Do you have ideas regarding the implementation of this feature?
At the moment it would be simply a matter of adding the string definitions (`safe`, `finalized` and maybe `unsafe`) to this [function](https://github.com/ethereum/go-ethereum/blob/86d547707965685cef732aa28c15e6811ea98408/ethclient/gethclient/gethclient.go#L183), even if setting the block number parameter to any of these strings results in error, we could this way start preparing the tests for when the actual definitions are included in the spec.

- Are you willing to implement this feature?
Yes

**Comment by mkalinin** [comment]
`unsafe` isn't considered anymore, related PR has been updated recently https://github.com/ethereum/execution-apis/pull/200

**Comment by holiman** [comment]
The `ethclient` just needs to pass a string, @MariusVanDerWijden has a PR to fix this in the go-ethereum RPC layer instead
