### ISSUE TITLE
Error in private network single node mining for calling library function

### ISSUE THREAD

**Issue by IamSandipC** [ethereum/go-ethereum#2482]
#### System information

Geth version: 1.3.6 & 1.4.0
OS & Version: Windows
Commit hash : 
Any simple contract that calls a library function is deployed (example below). Whenever library function is called from the contract it throws error. However same works fine in any other mining - e.g Deployed to TestNet from Mist Browser, tested in test-rpc, tested in solidty browser javascript vm, tested in Mix debug blockchain.
#### Expected behaviour

Should work perfectly..and log the event Print.
#### Actual behaviour

Transaction is added in the blockchain. But no event is logged. For other contracts it does not update storage for the contract. Looking at the EVM log, there is an error "error": "Invalid opcode 44454c454741544543414c4c", **Exact same error with the same opcode 44454c454741544543414c4c happens for all the contract example and library call**
#### Steps to reproduce the behaviour
1. Created a solidity contract that uses a library. Tried this with multiple contract. here providing the simpler example.

```
library ConvertLib{
    function convert(uint amount,uint conversionRate) returns (uint convertedAmount)
    {
        return amount * conversionRate;
    }
}

contract MetaCoin {
    mapping (address => uint) balances;
    event Print(string str);
    function MetaCoin() {
        balances[tx.origin] = 10000;
    }

    function sendCoin(address receiver, uint amount) returns(bool sufficient) {
        if (balances[msg.sender] < amount) return false;
        balances[msg.sender] -= amount;
        balances[receiver] += amount;
        Print("hello");
        return true;
    }
    function getBalanceInEth(address addr) returns(uint){
                 Print("called");
        return ConvertLib.convert(getBalance(addr),2);
    }
    function getBalance(address addr) returns(uint) {
        return balances[addr];
    }
}

```
1. created a private single node blockchain using geth with following genesis

```
{
  "nonce": "0x0000000000000042",
  "timestamp": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x0",
  "gasLimit": "0x8000000",
  "difficulty": "0x4000",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x3333333333333333333333333333333333333333",
  "alloc": {
    "0x5c1c6d4befc3a9f25941943dfc387709829728a5": { "balance": "200000000000000000000" },
    "0xa50e23fd23d142db77fb7b53354688dbcbdd0fde": { "balance": "200000000000000000000" },
    "0xd6f911f30357209877a947ddf5a66a2ad208680c": { "balance": "000000000000000000000" }
  }
}
```

and using the following command:
start  geth.exe --genesis CustomGenesis.json --identity "MyTestNode1" --networkid 1234 --datadir "/Data/MyChain1" --rpc --rpcport "9090"  --rpccorsdomain "*"  --port "30303"  --nat "any"  --verbosity "3" 

unlocked the account, started mining.
1. Deployed the library. linked it properly with the contract byte code and deployed the contract. Called the  getBalanceInEth method using web3 library - getBalanceInEth.sendTransaction() API 
#### Backtrace

Here is the last few lines of EVM log:
 {
      "depth": 1,
      "error": "",
      "gas": 7,
      "gasCost": 3976883,
      "memory": [ "0000000000000000000000005c1c6d4befc3a9f25941943dfc387709829728a5", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "96e4ee3d00000000000000000000000000000000000000000000000000000000", "0000271000000000000000000000000000000000000000000000000000000000", "0000000200000000000000000000000000000000000000000000000000000000" ],
      "op": "DELEGATECALL",
      "pc": 398,
      "stack": [
        "000000000000000000000000000000000000000000000000000000007bd703e8",
        "00000000000000000000000000000000000000000000000000000000000000b1",
        "0000000000000000000000005c1c6d4befc3a9f25941943dfc387709829728a5",
        "0000000000000000000000000000000000000000000000000000000000000000",
        "0000000000000000000000001ea64b70d8b78dae5c913e54ea43c6422c8253e4",
        "0000000000000000000000000000000000000000000000000000000096e4ee3d",
        "00000000000000000000000000000000000000000000000000000000000000a4",
        "0000000000000000000000000000000000000000000000000000000000000020",
        "0000000000000000000000000000000000000000000000000000000000000060",
        "0000000000000000000000000000000000000000000000000000000000000044",
        "0000000000000000000000000000000000000000000000000000000000000060",
        "0000000000000000000000001ea64b70d8b78",
        "dae5c913e54ea43c6422c8253e4\", \"00000000000000000000000000000000000000000000000000000000003cae8b\"],",
        "storage",
        :
        { }
    },
    {
      "depth": 1,
      "error": "Invalid opcode 44454c454741544543414c4c",
      "gas": 7,
      "gasCost": 3976883,
      "memory": [ "0000000000000000000000005c1c6d4befc3a9f25941943dfc387709829728a5", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "96e4ee3d00000000000000000000000000000000000000000000000000000000", "0000271000000000000000000000000000000000000000000000000000000000", "0000000200000000000000000000000000000000000000000000000000000000" ],
      "op": "DELEGATECALL",
      "pc": 398,
      "stack": [
        "000000000000000000000000000000000000000000000000000000007bd703e8",
        "00000000000000000000000000000000000000000000000000000000000000b1",
        "0000000000000000000000005c1c6d4befc3a9f25941943dfc387709829728a5",
        "0000000000000000000000000000000000000000000000000000000000000000",
        "0000000000000000000000001ea64b70d8b78dae5c913e54ea43c6422c8253e4",
        "0000000000000000000000000000000000000000000000000000000096e4ee3d",
        "00000000000000000000000000000000000000000000000000000000000000a4",
        "0000000000000000000000000000000000000000000000000000000000000020",
        "0000000000000000000000000000000000000000000000000000000000000060",
        "0000000000000000000000000000000000000000000000000000000000000044",
        "0000000000000000000000000000000000000000000000000000000000000060",
        "0000000000000000000000001ea64b70d8b78",
        "dae5c913e54ea43c6422c8253e4\", \"00000000000000000000000000000000000000000000000000000000003cae8b\"],",
        "storage",
        :
        { }
    }

```
[backtrace]
```

**Comment by karalabe** [comment]
The issue is that a non initializes block number defaults the homestead transition to the mainnet's 1M+ block, so DELEGATECALL is not available until then. Although this works as intended and the correct genesis file would need per https://github.com/ethereum/go-ethereum/pull/2281

```
"config":
    "homesteadBlock": "0"
},
```

Maybe we should rather use zero as the default and not the mainnet transition to prevent people being surprised. @obscuren opinion?

**Comment by obscuren** [comment]
We've had a discussion about this and we've settled on the following:

All genesis blocks start with a `homesteadBlock: 0` *unless* the **hash** of the block matches *exactly* with the hardcoded genesis block, which then sets the `homesteadBlock: 1150000`.

**Comment by obscuren** [comment]
Please see linked PR :-)

**output:**

```
> {g.traceTransaction("0x19185b3809801e482c5becc055986ac3be0fed16c1a39684a0a76cfd2a466aa8")
{
  gas: 21063,
  returnValue: "",
  structLogs: [{
      depth: 1,
      error: "",
      gas: 178997,
      gasCost: 3,
      memory: null,
      op: "PUSH1",
      pc: 0,
      stack: [],
      storage: {}
  }, {
      depth: 1,
      error: "",
      gas: 178994,
      gasCost: 3,
      memory: null,
      op: "PUSH1",
      pc: 2,
      stack: ["0000000000000000000000000000000000000000000000000000000000000000"],
      storage: {}
  }, {
      depth: 1,
      error: "",
      gas: 178991,
      gasCost: 3,
      memory: null,
      op: "PUSH1",
      pc: 4,
      stack: ["0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000"],
      storage: {}
  }, {
      depth: 1,
      error: "",
      gas: 178988,
      gasCost: 3,
      memory: null,
      op: "PUSH1",
      pc: 6,
      stack: ["0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000"],
      storage: {}
  }, {
      depth: 1,
      error: "",
      gas: 178985,
      gasCost: 3,
      memory: null,
      op: "PUSH20",
      pc: 8,
      stack: ["0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000"],
      storage: {}
  }, {
      depth: 1,
      error: "",
      gas: 178982,
      gasCost: 3,
      memory: null,
      op: "PUSH2",
      pc: 29,
      stack: ["0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000001a66ab66f772e3ab3ca44c370830b74c46d2681b"],
      storage: {}
  }, {
      depth: 1,
      error: "",
      gas: 178980,
      gasCost: 2,
      memory: null,
      op: "GAS",
      pc: 32,
      stack: ["0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000001a66ab66f772e3ab3ca44c370830b74c46d2681b", "0000000000000000000000000000000000000000000000000000000000000fa0"],
      storage: {}
  }, {
      depth: 1,
      error: "",
      gas: 178977,
      gasCost: 3,
      memory: null,
      op: "SUB",
      pc: 33,
      stack: ["0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000001a66ab66f772e3ab3ca44c370830b74c46d2681b", "0000000000000000000000000000000000000000000000000000000000000fa0", "000000000000000000000000000000000000000000000000000000000002bb24"],
      storage: {}
  }, {
      depth: 1,
      error: "",
      gas: 3957,
      gasCost: 175020,
      memory: null,
      op: "DELEGATECALL",
      pc: 34,
      stack: ["0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000001a66ab66f772e3ab3ca44c370830b74c46d2681b", "000000000000000000000000000000000000000000000000000000000002ab84"],
      storage: {}
  }, {
      depth: 1,
      error: "",
      gas: 178937,
      gasCost: 0,
      memory: null,
      op: "STOP",
      pc: 35,
      stack: ["0000000000000000000000000000000000000000000000000000000000000001"],
      storage: {}
  }]
}
> eth.blockNumber
36
```

**Comment by thiagodelgado111** [comment]
I suppose I'm having the same problem reported before, adding the parameter below to my `genesis.json` fixes it?
```
"config":
    "homesteadBlock": "0"
}
```

## System information

Geth version: 1.4.3
OS info:  Mac OS X 10.11.4

## Expected behaviour
The library function call should send ether to an address

## Actual behaviour
Transaction is added to the blockchain but no event is logged/code is executed after the line that calls the library function. Removing the library function call the error is gone, Adding it back the error occurs again

(I got the same error: "Invalid opcode 44454c454741544543414c4c" as shown in the log lines below)


## Last few lines of TX trace
```
{
      depth: 1,
      error: "",
      gas: 7,
      gasCost: 3092662,
      memory: ["0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "0904dc0100000000000000000000000000000000000000000000000000000000", "00002710000000000000000000000000ab5d490d5bbd3fdb87093abde866abd7", "ff98bd420000000000000000000000009e0a8c3de8a4766a202ea715a9d9212a", "15591e4f00000000000000000000000000000000000000000000000000000000"],
      op: "DELEGATECALL",
      pc: 4951,
      stack: ["000000000000000000000000000000000000000000000000000000002f6da7bb", "00000000000000000000000000000000000000000000000000000000000000fb", "0000000000000000000000000000000000000000000000000000000000000000", "000000000000000000000000ab5d490d5bbd3fdb87093abde866abd7ff98bd42", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000002710", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000005a2e97d6f6b2b4f873448960d13a3a9ee136e1e1", "000000000000000000000000000000000000000000000000000000000904dc01", "00000000000000000000000000000000000000000000000000000000000000c4", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000000000000000000000000000000000000000000064", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000005a2e97d6f6b2b4f873448960d13a3a9ee136e1e1", "00000000000000000000000000000000000000000000000000000000002f308e"],
      storage: {}
  }, {
      depth: 1,
      error: "Invalid opcode 44454c454741544543414c4c",
      gas: 7,
      gasCost: 3092662,
      memory: ["0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "0904dc0100000000000000000000000000000000000000000000000000000000", "00002710000000000000000000000000ab5d490d5bbd3fdb87093abde866abd7", "ff98bd420000000000000000000000009e0a8c3de8a4766a202ea715a9d9212a", "15591e4f00000000000000000000000000000000000000000000000000000000"],
      op: "DELEGATECALL",
      pc: 4951,
      stack: ["000000000000000000000000000000000000000000000000000000002f6da7bb", "00000000000000000000000000000000000000000000000000000000000000fb", "0000000000000000000000000000000000000000000000000000000000000000", "000000000000000000000000ab5d490d5bbd3fdb87093abde866abd7ff98bd42", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000002710", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000005a2e97d6f6b2b4f873448960d13a3a9ee136e1e1", "000000000000000000000000000000000000000000000000000000000904dc01", "00000000000000000000000000000000000000000000000000000000000000c4", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000000000000000000000000000000000000000000064", "0000000000000000000000000000000000000000000000000000000000000060", "0000000000000000000000005a2e97d6f6b2b4f873448960d13a3a9ee136e1e1", "00000000000000000000000000000000000000000000000000000000002f308e"],
      storage: {}
  }
```

**Comment by obscuren** [comment]
Did you reset the chain?

**Comment by thiagodelgado111** [comment]
Sorry, I think I don't know what you mean. Do you mean running init again pointing to the updated `genesis.json` file?
