### ISSUE TITLE
Geth 1.10.17 fails to sync with Ropsten

### ISSUE THREAD

**Issue by mdeliadi** [ethereum/go-ethereum#24826]
#### System information

Geth version: 1.10.17-stable
OS & Version: Debian GNU/Linux 9.6 (stretch)
Commit hash : 25c9b49fdb74931137431c24cf28d3c65f9420d2

#### Expected behaviour
Geth syncs with Ropsten.

#### Actual behaviour
Geth fails to sync with Ropsten (it's been trying for more than three hours) logging the following error: `Snapshot extension registration failed err="peer connected on snap without compatible eth support"`.

#### Steps to reproduce the behaviour
I've updated Geth from 1.10.16-stable to 1.10.17-stable.

#### Backtrace
N/A

#### CLI options
`--ropsten --http --http.addr '0.0.0.0' --http.port 8545 --http.api eth,net,web3,personal,rpc --http.corsdomain '*' --http.vhosts '*' --ws --ws.port 8546 --port 30303 --txlookuplimit=0 --whitelist 6485846=0x43f0cd1e5b1f9c4d5cda26c240b59ee4f1b510d0a185aa8fd476d091b0097a80 --allow-insecure-unlock --rpc.allow-unprotected-txs --syncmode full`

**Comment by s1na** [comment]
This is fixed in https://github.com/ethereum/go-ethereum/pull/24817. You can wait for the next release or try it against master.

**Comment by xingyushu** [comment]
I met the same error in version 1.10.17,doyou solve the problem  now?
