### ISSUE TITLE
Peer discovery issue

### ISSUE THREAD

**Issue by de-ltd** [ethereum/go-ethereum#24833]
Hello,

I have 4 nodes in europe, all working fine with no issues on AWS. Code is slightly modified with some personal touches but nothing crazy.

I have just launched a new instance on AWS US-EAST-1 to run a node there and it will not look for peers, the discovery just isn't working in that region. I have had a node there weeks ago and it worked fine ( different instance type though ). I added a new prints and i can see the the discoveryV5 find the network IP, but beyond that it just doesn't seem to manage connections.

The bootstrap nodes used are taken from the live url provided by binance and injected into geth on startup ( as bootnodes and as static peers ), usually works flawlessly in other regions. 

Each static dial from the bootnodes results in EOF responses, constantly.

I thought it could be server time, but thats all synced now using amazons instructions so i am completely baffled as to what isnt working properly.

thanks in advance for any ideas.

**Comment by de-ltd** [comment]
Solved

**Comment by anthonyoliai** [comment]
Hi can I ask you how you got tuis solved? Im running several nodes in the same cluster for my private poa betwork but even if i provide the right ENRs to the non-bootnodes they do not look for peers at all.
