### ISSUE TITLE
Why your calc_Difficulty_Homestead is not concise with the one in Homestead YellowPaper?

### ISSUE THREAD

**Issue by efaysal** [ethereum/go-ethereum#2483]
It's unbelievable, the difficulty in a period of less than two months jumped from 10 Th to 30 Th. 
First your calculation is not the one in Homestead Yellw Paper, http://gavwood.com/paper.pdf 
why?

Adding that exponential perturbation is simply a madness, at the end of August 2016, the difficulty will reach 100 Th or more ... Something needs to be fixed.

**Comment by fjl** [comment]
```go
// the exponential factor, commonly refered to as "the bomb"
```
was added deliberately as an additional incentive for the switch to a Proof of Stake consensus algorithm.
