### ISSUE TITLE
about latest version

### ISSUE THREAD

**Issue by xmhlg** [ethereum/go-ethereum#24846]
Why is the latest version now 1.10.15? Do you want to go back to version 1.10.15 if you have already upgraded to 1.10.17?

**Comment by rjl493456442** [comment]
What do you mean "the latest version"? How do you install Geth? It's possible that the latest version is not submitted to some software management tool though.

**Comment by SergiFortunejack** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/87651606/167770762-3f305774-c755-4b06-845b-a59144ff6f0f.png">

**Comment by karalabe** [comment]
Seems to be a GitHub bug. Listing the tags will include all the newer ones too https://github.com/ethereum/go-ethereum/releases and accessing the release notes for those directly work:

- https://github.com/ethereum/go-ethereum/releases/tag/v1.10.16
- https://github.com/ethereum/go-ethereum/releases/tag/v1.10.17

Opened a ticket at GitHub, unsure when they'll fix it.

**Comment by karalabe** [comment]
Fixed by GitHub.
