### ISSUE TITLE
GETH responds {'code': -32000, 'message': 'replacement transaction underpriced'} 

### ISSUE THREAD

**Issue by kladkogex** [ethereum/go-ethereum#24852]
We see "replacement transaction underpriced" errors on multple geth nodes and on multiple validators after moving to EIP-1559.

We did not see this previously.

Happy to provide logs from particular validators.

**Comment by rjl493456442** [comment]
> after moving to EIP-1559.

We have moved to 1559 for a few years though. You should bump both feeTip and feeCap at least 10 percent for the new transaction. Check here for more detail https://github.com/ethereum/go-ethereum/blob/8a008ee0e6f08eb73407158a6ce2716d59ae40fc/core/tx_list.go#L281

Close it now, feel free to open again.
