### ISSUE TITLE
Old keystore formats are not working anymore in geth 1.4

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#2486]
#### System information

Geth version: 1.4
OS & Version: OSX
Commit hash : 8241fa5

In this latest version it doesn't detect old keyhole (folder) formats anymore. This brings a lot of inconvenience for people, as we have no way to import this old formats, nor a way to export them in an older version.

We definitely need to add a way to import those old formats, if we remove support for them..

**Comment by obscuren** [comment]
What do you mean by "old format"? We didn't change any format

**Comment by frozeman** [comment]
The old format was a folder with the key name and a file aside with the key name. This is working and "read" by geth in 1.3, but not in geth 1.4 anymore. See the screenshot for the formats.

<img width="544" alt="screen shot 2016-04-25 at 12 38 53" src="https://cloud.githubusercontent.com/assets/232662/14796537/b245705e-0ae2-11e6-86dd-3eaaad0748fd.png">

**Comment by rfikki** [comment]
I had this problem. Just move the key out of the folder and into the keystore main folder and restart the node.

**Comment by rfikki** [comment]
See this: https://github.com/ethereum/go-ethereum/issues/2479

**Comment by fjl** [comment]
The 'key file in subdirectory' storage scheme was changed in geth 0.9.36, before the Frontier release. The only people affected are those which still have Olympic keys in their store and did not update the password since then.

**Comment by fjl** [comment]
We have decided that this issue will be addressed by a note in the 1.4 release notes.
The workaround is to simply move the file out of the subdirectory.
