### ISSUE TITLE
Fatal: Error starting protocol stack: listen tcp :30303: bind: address already in use

### ISSUE THREAD

**Issue by oooomoooo** [ethereum/go-ethereum#24878]
I use docker to pull geth，
![T__249(IHR6UZF%)~)$WN8T](https://user-images.githubusercontent.com/92239221/168413045-26decdc0-1c6d-42d0-9199-78c9d4b3a8c2.png)
，Enter the container, start the private network, and report an error，
![RC8SY$GQ P61 A%37O8 8EP](https://user-images.githubusercontent.com/92239221/168413151-8e441aae-6692-4bc4-b6b3-c1cb2b44eec6.png)
Fatal: Error starting protocol stack: listen tcp :30303: bind: address already in use
，Please help me, I can't solve it

**Comment by wandhekarshubham10** [comment]
sir still it is giving same error

**Comment by Alessandro-Cavaliere** [comment]
> sir still it is giving same error at the first node0 geth --datadir ./ --maxpeers 100 --networkid 1441 --port 30333 console
> 
> and at the node1 geth --datadir ./ --networkid 1441 --port 30334 console
> 
> but still giving same error Fatal: Error starting protocol stack: listen tcp 127.0.0.1:8551: bind: address already in use
> 
> please help

You have to use the flag command --authrpc.port 8545 (for example for node1 and 8546 for example for node2) , because if you run two different nodes without specify this command, by default, geth sets the port 8551.
