### ISSUE TITLE
Mishandling of "geth init genesis.json"

### ISSUE THREAD

**Issue by martinhbramwell** [ethereum/go-ethereum#2487]
#### System information

Geth version  of  ppa:ethereum/ethereum-dev : 

    Version : 1.5.0-unstable
    Protocol Versions: [63 62 61]
    Network Id: 1
    Go Version: go1.6.1
    OS: linux
    GOPATH=
    GOROOT=/usr/lib/go-1.6

Geth version  of  ppa:ethereum/ethereum : 

    Version : 1.3.6
    Protocol Versions: [63 62 61]
    Network Id: 1
    Go Version: go1.6.1
    OS: linux
    GOPATH=
    GOROOT=/usr/lib/go-1.6

OS & Version: Xubuntu Xenial Xerus
Commit hash : (if `develop`) 

#### Expected behaviour

geth init /path/to/genesis.json  should initialize and exit

#### Actual behaviour

It connects to the public block chain and begins synchronization

#### Steps to reproduce the behaviour

It works as expected, if I install Ethereum with : 

     sudo add-apt-repository -y ppa:ethereum/ethereum-dev;
     sudo apt-get update;
     sudo apt-get install -y ethereum;

It misbehaves, if I install Ethereum with : 

     sudo add-apt-repository -y ppa:ethereum/ethereum;
     sudo apt-get update;
     sudo apt-get install -y ethereum;

The file `/etc/apt/sources.list.d/ethereum-ubuntu-ethereum-dev-xenial.list` contains ...

     deb http://ppa.launchpad.net/ethereum/ethereum-dev/ubuntu xenial main

**Comment by obscuren** [comment]
Geth 1.4 has not yet landed on `master` And won't be until the final release. Please see the [release candidate](https://github.com/ethereum/go-ethereum/releases/tag/v1.4.0) for binaries.

Closing as its not an issue.

**Comment by martinhbramwell** [comment]
If that's the case, then the deprecation of --genesis (with instructions to use --init) is premature and causes a lot of confusion.

**Comment by obscuren** [comment]
We are sorry for the confusion, but in our defense I did announce this. The deprecation will only be shown if you are on the 1.4 client. 

We keep the master branch as is so that if anything may be wrong with 1.4 we have something to fall back on.

**Comment by martinhbramwell** [comment]
Sorry.  I did not mean to bug you.   There was a Gitter discussion about the Xenial PPA that implied that the confusion would be cleared up.  I thought the released *non-dev* PPA was supposed to have the post-deprecation version, in which `--init` works. that's all.

**Comment by obscuren** [comment]
No worries :-) it's `init` btw, not `--init` i.e. A sub command and not a flag. Did you try that?

**Comment by martinhbramwell** [comment]
Yeah, just a typo. I do understand the difference.

If you are interested, I am nearly complete with a bash bootstrap kit for "one-touch" setup of a private test network for developers:  [GitHub > Gists > martinhbramwell > initializeEthereumTestNode.sh](https://gist.github.com/martinhbramwell/106709bde2ddd456c90599e4a3477615)

I intend to fork this repo, add the script and send a pull request.  If you think it would not be accepted, please let me know. I could just link to it from the Wiki.

**Comment by obscuren** [comment]
I appreciate the effort, however these scripts do generally not fit very well in the main repo. Adding these type of scripts means that we must maintain them and our expertise is certainly with not bash script :-)

Please do not take this personal, we certainly appreciate the effort you are putting in to this, but i do believe these sort of scripts belong elsewhere :-)

**Comment by tuytuy** [comment]
I still have this exact same issue, I havn't tried to install geth using the dev repo, has master been updated ? Is there another command to initialise a new chain ?
