### ISSUE TITLE
Native tracer on very old blocks

### ISSUE THREAD

**Issue by evanzbitgo** [ethereum/go-ethereum#24880]
I am using `debug_traceBlockByNumber` and `callTracer` to trace very old blocks. It is super fast at chainhead. However, it took 30 seconds to trace an old block (blocks in 2017). Are there any tricks to speed up the native tracer?

Node storage has been upgraded to NVMe, but it did not boost the performance

**Comment by s1na** [comment]
@evanzbitgo You'll see `Regenerating historical state` in the logs when issuing the tracing request and as Gary said that's probably what's taking the longest.

@rjl493456442 will we completely lose ability to trace very old blocks once the PBSS is in? :(

**Comment by rjl493456442** [comment]
@s1na We can construct the tracing state by applying the reverse diffs based on the state in disk. 

Good side:
Applying reverse diff is way more faster than re-execution

Bad side:
it's gonna be harder because the start point is fixed and you need to apply a lot if the block is super old
