### ISSUE TITLE
subscription queue overflow after a few minutes of listening for pending transactions

### ISSUE THREAD

**Issue by rtunazzz** [ethereum/go-ethereum#24889]
Hello there!

I'm fairly new to Go but not so new to Web3 and dApps. I am trying to create a simple transaction watcher that will notify a user about ongoing transactions from their address.

I've asked about this in both the [ETH stack exchange](https://ethereum.stackexchange.com/questions/127645/subscription-queue-overflow-error-after-a-few-minutes-of-being-subscribed-to-n) and discord but haven't received any responses. I've also tried to search around but unfortunately, I couldn't find anyone with a similar issue to mine.

The issue I'm having is - **after a couple of minutes (5-10mins usually) of runtime, I get hit with a `subscription queue overflow`**. Clearly, the subscription buffer is filled within those few minutes which raises that error but how is it possible that the buffer gets overflown even when I'm constantly looping over the channel and taking out new hashes?

Anyway, here's a code example:

```go
package main

import (
    "context"
    "log"
    "math/big"
    "strings"

    "github.com/ethereum/go-ethereum/common"
    "github.com/ethereum/go-ethereum/core/types"
    "github.com/ethereum/go-ethereum/ethclient"
    "github.com/ethereum/go-ethereum/rpc"
)

func main() {
    rpcUrl := "wss://eth-mainnet.alchemyapi.io/v2/xxx" // removed my full RPC url
    myAddress := "0x000" // removed my address

    // initialize clients
    client, _ := rpc.Dial(rpcUrl)
    ethClient, _ := ethclient.Dial(rpcUrl)
    chainID, _ := ethClient.NetworkID(context.Background())

    log.Printf("[%s] ETH Client initialized.", rpcUrl)

    // initialize hash channel and create subscription
    txCh := make(chan common.Hash)
    sub, _ := client.EthSubscribe(context.Background(), txCh, "newPendingTransactions")
    defer sub.Unsubscribe()

    log.Printf("Listening to pending transactions...")

    for {
        select {
        case err := <-sub.Err():
            // this here prints the subscription queue overflow after a couple of minutes
            log.Fatal("[SUBSCRIPTION] Fatal error:", err)
        case txHash := <-txCh:
            // initialize hash channel and create subscription
            tx, isPending, err := ethClient.TransactionByHash(context.Background(), txHash)
            if err != nil {
                log.Printf("[%s] Error while getting tx:%s\n", txHash, err)
                continue
            }
            log.Printf("[%d/%d] [SUBSCRIPTION] Received hash %s\n", len(txCh), cap(txCh), txHash)
            msg, err := tx.AsMessage(types.LatestSignerForChainID(chainID), big.NewInt(1))
            if err != nil {
                log.Fatal(isPending, err)
                continue
            }

            if strings.EqualFold(msg.From().Hex(), myAddress) {
                log.Printf("[%s] [%s] New outgoing transaction, target address: %s\n", myAddress, txHash, msg.To().Hex())
            }
        }
    }
}
```

**Comment by karalabe** [comment]
You are doing a query to retrieve each transaction, which takes time. My hunch is that pending transactions are announced faster than how you can pull them one-by-one via `ethClient.TransactionByHash`. You should try just printing the hashes for starters and see if there's some hang there.
