### ISSUE TITLE
Rejected peer before protocol handshake   err="connected to self"

### ISSUE THREAD

**Issue by anaskhalidgg** [ethereum/go-ethereum#24909]
We are currently running a private blockchain with 4 nodes, but it stops mining blocks 

#### System information

Geth version: `1.7.3`
OS & Version: Linux

#### Expected behaviour
Keep mining

#### Actual behaviour
Blockchain is frozen

#### Steps to reproduce the behaviour
running node launch script : 
```
nohup ./geth --syncmode "full" --txpool.lifetime 1200h0m0s --targetgaslimit "0xffffffffffffffff" --gasprice "0" --datadir "./data" --verbosity 5  --identity "TEST" --networkid "87965404" --nodiscover --password "password" --unlock "0" --port "30741"  --rpc  --rpcaddr "localhost" --rpcport "8545" --rpcapi "admin,eth,net,web3,miner" --rpccorsdomain "localhost" --minerthreads 1 --nat "any" --mine --maxpeers 10 2>> ./logs_geth &
```

#### Backtrace
````
TRACE[05-19|16:33:33] Rejected peer before protocol handshake  id="" addr="" conn=inbound    err="connected to self"
TRACE[05-19|16:33:33] Rejected peer before protocol handshake  id="" addr="" conn=staticdial err="connected to self"
````

**Comment by hsyodyssey** [comment]
Perhaps you could check the enode address of this four nodes. It looks like the node tried to connect itself during the P2P node discovery process.

https://github.com/ethereum/go-ethereum/blob/master/p2p/server.go#L811-L812

**Comment by karalabe** [comment]
That's a super old release, we can't support legacy code.
