### ISSUE TITLE
I'm going to write a program to get the balance

### ISSUE THREAD

**Issue by wq57885** [ethereum/go-ethereum#24903]
**Windows10, go1.18.2, Vscode, compile the simplest code** 
-------------------------------------------------------------------------------------------
package main

import (
	"chain/tool"
	"fmt"
	"log"

	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	_, err := ethclient.Dial("https://mainnet.infura.io")
	if err != nil {
		log.Fatal(err)
	}

}
-------------------------------------------------------------------------------------------
**display the following error message**
-------------------------------------------------------------------------------------------

Build Error: go build -o e:\Gopath\src\chain\__debug_bin.exe -gcflags all=-N -l .
# github.com/ethereum/go-ethereum/rpc
..\github.com\ethereum\go-ethereum\rpc\server.go:49:11: cannot use generic type mapset.Set[T comparable] without instantiation
..\github.com\ethereum\go-ethereum\rpc\server.go:54:69: cannot infer T (E:\Gopath\src\github.com\deckarep\golang-set\set.go:180:13)
..\github.com\ethereum\go-ethereum\rpc\websocket.go:72:26: cannot infer T (E:\Gopath\src\github.com\deckarep\golang-set\set.go:180:13)
..\github.com\ethereum\go-ethereum\rpc\websocket.go:125:37: cannot use generic type mapset.Set[T comparable] without instantiation (exit status 2)

**Comment by wq57885** [comment]
The question is in the go version? Or the type of system?

**Comment by karalabe** [comment]
You need to use the versions of the dependencies defined in the go-ethereum repo. Your code seems to pull latest versions of upstream packages, not the pinned ones. My guess is that you don't have go modules enabled and default to blindly pulling the latest version of all imports.

**Comment by karalabe** [comment]
:+1:

**Comment by seyedsalar** [comment]
> > You need to use the versions of the dependencies defined in the go-ethereum repo. Your code seems to pull latest versions of upstream packages, not the pinned ones. My guess is that you don't have go modules enabled and default to blindly pulling the latest version of all imports.
> 
> You're right. It's not convenient here, so i don't have go modules enabled. But I solved it, I switched golang-set back to 1.8.0 and everything is ok. thanks

how can i switch golang-set back to 1.8.0? i use "go get github.com/ethereum/go-ethereum/ethclient" and faced with this issue.
