### ISSUE TITLE
core/vm: provide temporary trace information through a new Trace function

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#2490]
After a short discussion with @arachnid about the current VM tracing functionality we figured that this process could be easily optimised. This would be very handy for applications that only require certain information at certain points in time (e.g. `CALL`).

At present the `AddStructLog` will _always_ copy `memory`, `stack` and `storage`. In addition to the current functionality a `Trace` function should be added which gives you a _temporary_ state of the VM without copying all the data. This should be significantly faster for operations where only certain op codes are of interest (e.g. stack information during `CALL`) and, if required, leaves the copying up to the implementer of this function.

**Comment by fjl** [comment]
Fix released in 1.5.0. ;)
