### ISSUE TITLE
truncateQueue method drops the newest txs rather than the oldest ones.

### ISSUE THREAD

**Issue by zhaochonghe** [ethereum/go-ethereum#24907]
https://github.com/ethereum/go-ethereum/blob/5c5ef6f16e4d50de337d95b2a3c8a0e9deb35dfa/core/tx_pool.go#L1462
According to its annotation, it seems to drop the oldest txs first when the length of queue is above the global queue limit.
https://github.com/ethereum/go-ethereum/blob/5c5ef6f16e4d50de337d95b2a3c8a0e9deb35dfa/core/tx_pool.go#L1483
But actually, it first drops the newest txs (the last element in `addresses`), since the elements in `addresses` are ordered from oldest to newest . Should it change to ` addr := addresses[0] ` ?

**Comment by holiman** [comment]
Indeed, can confirm. 
An alternative way to fix it would be to change the sorting to `sort.Sort(sort.Reverse(addresses))`

**Comment by holiman** [comment]
Fixed by #24908
