### ISSUE TITLE
geth cannot enable port 8545

### ISSUE THREAD

**Issue by hyithack** [ethereum/go-ethereum#24933]
geth cannot enable port 8545
start command:
```
nohup geth --syncmode "full" --mainnet  --datadir /eth/eth-01 --http --http.addr '0.0.0.0' --http.port 8545 --http.api "eth,net,web3,txpool" --http.corsdomain '*' --http.vhosts '*' --allow-insecure-unlock & > nohup.out
```

**Comment by s1na** [comment]
Can you also post the error you get?

**Comment by Help-desk10** [comment]
Kindly open this live chat to talk to the customer service directly on your crypto issue  https://direct.lc.chat/14157678/

**Comment by karalabe** [comment]
IF the issue is the port, there's a high chance something else is already holding that port (e.g. if the error message is something about "bind failed").
