### ISSUE TITLE
Limit cpu cores of geth gonna use ? 

### ISSUE THREAD

**Issue by berktaylan** [ethereum/go-ethereum#24938]
Hi, i think golang uses GOMAXPROCS(max) by default.

What if i want to run my geth to limit cpu cores i want to use ( 8 as example )

**Comment by MariusVanDerWijden** [comment]
You can set GOMAXPROCS as an environment variable afaik

**Comment by berktaylan** [comment]
> You can set GOMAXPROCS as an environment variable afaik

Hi, thanks for reply, im quite new so is there any example about it ? Can i set it from config file ?

**Comment by rjl493456442** [comment]
There is no config for it. Geth will use all the available CPU cores by default.
I would recommend to run Geth in docker, so that you can limit the resources(memory, cpu cores, etc) through it.

**Comment by karalabe** [comment]
You can also simply set the `GOMAXPROCS` env var as Marius said. E.g. when starting Geth

```
GOMAXPROCS=8 geth --goerli console
```

Though I agree with @rjl493456442 that it feels a bit artificial to limit it like that. Geth doesn't really "waste" CPU resources on anything, so limiting it will just prolong the same operations. Unsure what that gets you.
