### ISSUE TITLE
Wiki tutorial bug

### ISSUE THREAD

**Issue by i5on9i** [ethereum/go-ethereum#2494]
## Wiki page bug
This is simple wrong information of the Wiki. 
First, sorry but I didn't search for the same issue of this so if this is duplicated one, please delete this.

on the dev tutorial page
https://github.com/ethereum/go-ethereum/wiki/Setting-up-private-network-or-local-cluster

change the below command
>admin.nodeInfo.NodeUrl

to
>admin.nodeInfo.ecode

#### System information

Geth version: `geth 1.6.1`
OS & Version: Windows
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by fjl** [comment]
Thanks, fixed.
