### ISSUE TITLE
How to run a beacon-chain for Ropsten

### ISSUE THREAD

**Issue by masayil** [ethereum/go-ethereum#24959]
I select [Prysm](https://github.com/prysmaticlabs/prysm) as beacon-chain client.But I can't find any configuration files about the Ropsten .

Are these configuration files provided by the Prysm team?

**Comment by s1na** [comment]
Please open an issue on the Prysm repo. As for Geth, here are the instructions for the merge on Ropsten: https://geth.ethereum.org/docs/interface/merge
