### ISSUE TITLE
Allow Zero gas price transactions (no baseFee) for permissioned networks

### ISSUE THREAD

**Issue by vdamle** [ethereum/go-ethereum#24966]
# Rationale

> Why should this feature exist?

Permissioned chains are in use fairly widely. Most of these chains operate with a consensus mechanism such as Clique/POA, IBFT/QBFT (GoQuorum) and the clients allow **zero gas price transactions**. This works well in a pre-EIP1559 regime. However, EIP-1559 makes requirements and assumptions about transactions including a `baseFee` and this governs the rules for block validation, state transition and transaction inclusion which means that clients will [no longer mine transactions sent with zero gas price](https://github.com/ethereum/go-ethereum/blob/310f75163928f49151b668faee78f475a1da34ac/miner/worker.go#L1015-L1017). 

> What are the use-cases?

The primary use for the feature is in permissioned networks that operate on zero gas price transactions.

# Implementation

> Do you have ideas regarding the implementation of this feature?

Here are two possible ways to support such chains in a post EIP-1559 world:

* Do not include `londonBlock` in genesis config for new chains, or do not ever include `londonBlock` as a future block - The main concern I have with this approach is that there are other instances where the code assumes that having a block `B` in the genesis config presumes the presence of block `A` (where `A` <= `B` for when the hard fork was introduced on mainnet). So it seems very likely in the future that a future EIP that is added as a hard fork will presume that the chain is operating with `londonBlock` in effect -- or that the absence of `londonBlock` is an unexpected and invalid configuration which will result in bad blocks.

* Add a chain configuration to `Clique` (IBFT/QBFT or any other pluggable consensus could choose to do something similar) that specifies that the chain shall not consider `baseFee` and use that to determine whether to require or ignore base fee for picking transactions to include in a block, state validation, gas refunds etc.

> Are you willing to implement this feature?

Yes, I have a change that allows clients to accept and validate zero gas price transactions when running `clique/POA`.

**Comment by karalabe** [comment]
I don't thunk such a change will ever be accepted into the Geth codebase. Our aim is to be an Ethereum client first. Since Ethereum introduced the notion of base fees and the related dynamics + opcode, developers building on top have the assumption that the `BASEFEE` exists in the EVM or that type 1 transactions can be sent from wallets. Even if Geth supported 0 as the base fee, it would mean code and tooling would need to be made aware that some networks can have this quirk. Long term this would be one more tweak to always tiptoe around whilst maintaining Geth.

Opinions @holiman ?

**Comment by vdamle** [comment]
Thank you for your feedback, @karalabe . For consideration, I have raised a PR that implements the idea described. 

I see that currently https://github.com/ethereum/go-ethereum/blob/be9742721f56eb8bb7ebf4f6a03fb01b13a05408/params/config.go#L264-L269 indicates that `londonBlock` is not included in Clique as reference configuration. This lines up with the first option of `londonBlock` not being included/enabled. Is that a path/assumption that will be maintained over time?

**Comment by karalabe** [comment]
London is enabled in there.

**Comment by karalabe** [comment]
Closing with https://github.com/ethereum/go-ethereum/pull/24982#issuecomment-1139750000

**Comment by giskook** [comment]
> * Do not include `londonBlock` in genesis config for new chains, or do not ever include `londonBlock` as a future block - The main concern I have with this approach is that there are other instances where the code assumes that having a block `B` in the genesis config presumes the presence of block `A` (where `A` <= `B` for when the hard fork was introduced on mainnet). So it seems very likely in the future that a future EIP that is added as a hard fork will presume that the chain is operating with `londonBlock` in effect -- or that the absence of `londonBlock` is an unexpected and invalid configuration which will result in bad blocks.

@vdamle Hi, have you tried disable London block?
