### ISSUE TITLE
Where does sent transaction broadcasted to other peers

### ISSUE THREAD

**Issue by berktaylan** [ethereum/go-ethereum#24964]
Hello, i was inspecting the geth codes ( rpc api ) i was able to find sendrawtransaction , i can see it added to txpool at some functions but i cant see at which part my tx broadcasted to other nodes

**Comment by zeim839** [comment]
Are you referring to the [sendrawtransaction](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1700) in internal/ethapi? If so, then the function (i believe) is only for interfacing with the local node, which isn't broadcasted to other nodes. If you want to learn about broadcasting to other nodes, have a look around the RPC and P2P modules - see the [RCP call function](https://github.com/ethereum/go-ethereum/blob/master/rpc/client.go#L282) or [P2P messages](https://github.com/ethereum/go-ethereum/blob/master/p2p/message.go#L99). 

How you communicate with other nodes will depend largely on what sort of client you're running (or not) and where the message is going/coming from.

**Comment by berktaylan** [comment]
hi @zeim839 

so i mean after i use sendrawtransaction on my own node, on some part my node should broadcast my tx to other peers im connected to right ? I couldnt find the code block doing this job

**Comment by zeim839** [comment]
Could you post some of your code or a reference to the sendrawtransaction function?

**Comment by berktaylan** [comment]
So i didnt played witg geth yet dont have a code example yet .

Currently im signing my raw transaction on my end. What im trying to do sign 2 tx of my own with nonce and nonce+1 , and trying to fasten the enqueue. But no idea where should i check first. I couldnt find the part where does my tx broadcasted to all network after submitrawtransaction function. Thanks.

**Comment by zeim839** [comment]
I can't point you in the right direction If I don't know how or what you're using to sign and transmit transactions. If you're running an ethereum node, then your transaction is probably propagated via the P2P network; if you're using a web API or a light wallet, then your transaction is sent via JSON RPC. 

You're probably better off asking the discord server (see [here](https://discord.com/invite/nthXNEv)) or stackoverflow for help - github issues isn't the best place for these types of questions.

**Comment by holiman** [comment]
@berktaylan see https://github.com/ethereum/go-ethereum/search?q=broadcastTransactions 

This is what sends them out to the peers: https://github.com/ethereum/go-ethereum/blob/992151fa6d22726f46be345ede2e2917bf631613/eth/handler.go#L607 , called from here https://github.com/ethereum/go-ethereum/blob/992151fa6d22726f46be345ede2e2917bf631613/eth/handler.go#L659 , whenever new txs comes in over the channel. And they are placed on that channel when they make it into the pool, IIRC.

**Comment by berktaylan** [comment]
Thanks @holiman .

I think it broadcast the pool with my new signed tx.

What if i want to broadcast instantly the transaction newly signed by me and sent to my own node ?

Where should i inspect
