### ISSUE TITLE
when I send tx,I still got error:"Cannot submit unprotected transaction". what should I do?

### ISSUE THREAD

**Issue by csquan** [ethereum/go-ethereum#24969]
when I send tx,I still got error:"Cannot submit unprotected transaction".
what should I do? 
refer to "https://github.com/ethereum/go-ethereum/issues/24421",
this bug should not exist,my code is latest.

**Comment by csquan** [comment]
I use vesion 1.10.18

**Comment by csquan** [comment]
version 1.10.18 had already supprt EIP155,why my tx still refused by metis mainnet,reason:"Cannot submit unprotected transaction "

**Comment by csquan** [comment]
eth_sendRawTransaction in my app ,I know do not use  non-eip155 replay protected transaction,
But what should I do in my code?Usually I send tx will success,but this time send to metis mainnet got this error

**Comment by fjl** [comment]
If you are using `eth_sendRawTransaction`, it means your app creates and signs the transactions. You need to ensure that your app creates replay protected transactions.

Is your app written in Go? If so, does it use go-ethereum / ethclient?
