### ISSUE TITLE
Database has receipts with a legacy format

### ISSUE THREAD

**Issue by masayil** [ethereum/go-ethereum#24970]
**Q1:**
WARN [05-26|11:08:59.839] Database has receipts with a legacy format. Please run `geth db freezer-migrate`. 
This log appears on my archive nodes.
Do I have to execute this command?
**Q2:**
Is the deprecation of Rinkeby certain to happen in the future？

**Comment by Zachinquarantine** [comment]
> Is the deprecation of Rinkeby certain to happen in the future？

[Yes](https://twitter.com/peter_szilagyi/status/1484548996169408512).
