### ISSUE TITLE
stolen Luna coin from my terra wallet from another luna wallet

### ISSUE THREAD

**Issue by Weall100** [ethereum/go-ethereum#24989]
Hello ,
Someone stolen Luna coin from my terra wallet and transfer to another terra wallet , the coin still in his terra wallet .  .I  have attached screenshot for my terra wallet . I believe this happen when screenshot taken for airdrop because I got new Luna  v2 coin  
to_address
[terra1a2t22y8hxqqvksxvtam9ymukgze0e3hhuunly5](https://finder.terra.money/classic/address/terra1a2t22y8hxqqvksxvtam9ymukgze0e3hhuunly5)

from_address My wallet  address ,
[terra19chc6l0jss278qztl9xcuja39h0z0ghnkq48h3](https://finder.terra.money/classic/address/terra19chc6l0jss278qztl9xcuja39h0z0ghnkq48h3)

would  you mind if any Engineer help me and return my coin from this wallet terra1a2t22y8hxqqvksxvtam9ymukgze
![1](https://user-images.githubusercontent.com/106464235/170855947-55f6fc58-210b-4a4b-b22b-f12941a15bfa.PNG)
![2](https://user-images.githubusercontent.com/106464235/170855948-d2b2e88f-e344-4aad-9243-449d333ff9c1.PNG)
![3](https://user-images.githubusercontent.com/106464235/170855949-7816123c-fd71-4cec-9710-1fc293ae3ac4.PNG)
0e3hhuunly5
Your help is highly appreciated ,  Many Thanks & Kindly Regards ,

**Comment by MariusVanDerWijden** [comment]
This is the issue tracker for go-ethereum we can not answer any luna related questions

**Comment by Weall100** [comment]
Hello ,
Thank you so much ,
Hello Ethereum ,

Someone stolen Luna coin from my terra wallet and transfer to another terra wallet , the coin still in his terra wallet . would you mind to return the coin to my terra wallet .I  have attached screenshot for my terra wallet . I believe this happen when screenshot taken for airdrop because I got new Luna  v2 coin

Your help is highly appreciated ,

Many thanks & kindly Regards ,

Ahmed

________________________________

**Comment by mantas735** [comment]
terra1a2t22y8hxqqvksxvtam9ymukgze0e3hhuunly5 this ardres stolen my terra luna clasic on terra station

**Comment by Weall100** [comment]
Yes , correct same address of wallet stolen my coins

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by holiman** [comment]
This is the issue tracker for go-ethereum we can not answer any luna related questions


I'm locking this ticket
