### ISSUE TITLE
miner.start()A bug.

### ISSUE THREAD

**Issue by agcml** [ethereum/go-ethereum#24990]
#### System information

Geth version: `All`
OS & Version: Linux-debian
Cmmit hash : I don't understand English very well.Please see below. Thank you.

Hello, my client pops up the following error message when miner. Start,Please don't misunderstand my intention, I am a Chinese, so I can't understand these tips.

####Recent Operation

> eth.accounts                                                              ["0xab0ac52ada5d7c224fb222e1dd595b45d58511ba", "0x2079cf3ee5a0f02194b9a15bcfab702a49a79702"]                                                            > miner.start()                                                             INFO [05-29|15:32:17.954] Updated mining threads                   threads=4INFO [05-29|15:32:17.954] Transaction pool price threshold updated price=1000000000                                                                     null                                                                        > INFO [05-29|15:32:17.964] Commit new mining work                   number=1 sealhash=843056…0dc13e uncles=0 txs=0 gas=0 fees=0 elapsed=8.809ms        > INFO [05-29|15:32:21.028] Generating ethash verification cache     epoch=1 percentage=22 elapsed=3.044s                                               INFO [05-29|15:32:24.032] Generating ethash verification cache     epoch=1 percentage=42 elapsed=6.049s                                                 INFO [05-29|15:32:27.041] Generating ethash verification cache     epoch=1 percentage=62 elapsed=9.058s                                                 INFO [05-29|15:32:30.055] Generating ethash verification cache     epoch=1 percentage=84 elapsed=12.071s                                                INFO [05-29|15:32:32.510] Generated ethash verification cache      epoch=1 elapsed=14.526s                                                              ERROR[05-29|15:32:32.516] Failed to generate mapped ethash dataset epoch=1 err="cannot allocate memory"                                                 fatal error: unexpected signal during runtime execution                     [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3ed70]

####Error content.
Oh, I can't copy the whole content, but I can put pictures. If you want, I can release the specific information for you.
look:
![超级截屏_20220529_154531](https://user-images.githubusercontent.com/93650439/170857853-7ec5b073-17ea-49c1-b55f-c8d71b7693d0.png)

Words to you{Finally, thank you for your understanding.
Please don't misunderstand my intention, I am a Chinese, so I can't understand these tips.Finally, thank you.Finally, thank you for your
}

**Comment by agcml** [comment]
/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/json.go:144 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).readRequest(0x8b5aade0, 0xc2b3d8, 0x8b574210, 0x15efe01, 0x95bec8, 0x8babe240, 0xc28558, 0x8babe260, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:375 +0x34
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest(0x8b5aade0, 0xc28518, 0x8682a0d8, 0xc2b3d8, 0x8b574210, 0x0, 0x3, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:160 +0x230
github.com/ethereum/go-ethereum/rpc.(*Server).ServeCodec(0x8b5aade0, 0xc2b3d8, 0x8b574210, 0x3)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:216 +0x7c
created by github.com/ethereum/go-ethereum/rpc.DialInProc.func1
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/inproc.go:29 +0x90

goroutine 69 [select]:
github.com/ethereum/go-ethereum/rpc.(*Client).dispatch(0x86a19c00, 0xc2af50, 0x869e02d0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/client.go:507 +0x1d4
created by github.com/ethereum/go-ethereum/rpc.newClient
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/client.go:206 +0x234

goroutine 70 [select]:
net.(*pipe).read(0x869e02d0, 0x91808000, 0x200, 0x200, 0x0, 0x157cc0, 0x200)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/pipe.go:164 +0x130
net.(*pipe).Read(0x869e02d0, 0x91808000, 0x200, 0x200, 0x0, 0x200, 0x8ba38090)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/pipe.go:147 +0x34
encoding/json.(*Decoder).refill(0x8b590210, 0x4, 0x9)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/encoding/json/stream.go:159 +0xf8
encoding/json.(*Decoder).readValue(0x8b590210, 0x0, 0x0, 0xffffff)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/encoding/json/stream.go:134 +0x1f8
encoding/json.(*Decoder).Decode(0x8b590210, 0x8fc038, 0x8ba38070, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/encoding/json/stream.go:63 +0x54
github.com/ethereum/go-ethereum/rpc.(*Client).read.func1(0x9042b8, 0x8ba38080, 0x869e02d0, 0x847143c0, 0x869e02d0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/client.go:648 +0x58
github.com/ethereum/go-ethereum/rpc.(*Client).read(0x86a19c00, 0xc2af50, 0x869e02d0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/client.go:661 +0xf4
created by github.com/ethereum/go-ethereum/rpc.(*Client).dispatch
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/client.go:482 +0x40

goroutine 131 [select]:
net.(*pipe).read(0x8ba28640, 0x8682ec01, 0x5ff, 0x5ff, 0x8babc914, 0xa, 0x27)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/pipe.go:164 +0x130
net.(*pipe).Read(0x8ba28640, 0x8682ec01, 0x5ff, 0x5ff, 0x0, 0x271c4, 0x8bab7540)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/pipe.go:147 +0x34
encoding/json.(*Decoder).refill(0x8b32b4a0, 0xa, 0x9)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/encoding/json/stream.go:159 +0xf8
encoding/json.(*Decoder).readValue(0x8b32b4a0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/encoding/json/stream.go:134 +0x1f8
encoding/json.(*Decoder).Decode(0x8b32b4a0, 0x8fc038, 0x8bab62b0, 0x8ba2a6c0, 0x3b7a94)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/encoding/json/stream.go:63 +0x54
github.com/ethereum/go-ethereum/rpc.(*Client).read.func1(0x8ba2a6c0, 0x86c8bfc8, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/client.go:648 +0x58
github.com/ethereum/go-ethereum/rpc.(*Client).read(0x86b09140, 0xc2af50, 0x8ba28640, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/client.go:661 +0xf4
created by github.com/ethereum/go-ethereum/rpc.(*Client).dispatch
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/client.go:482 +0x40

goroutine 133 [select]:
github.com/ethereum/go-ethereum/vendor/github.com/peterh/liner.(*State).readNext(0x86a162d0, 0x9180bdbc, 0x2, 0x20, 0x9180bd3c)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/peterh/liner/input.go:137 +0x120
github.com/ethereum/go-ethereum/vendor/github.com/peterh/liner.(*State).PromptWithSuggestion(0x86a162d0, 0x9b888f, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/peterh/liner/line.go:637 +0x5e0
github.com/ethereum/go-ethereum/vendor/github.com/peterh/liner.(*State).Prompt(0x86a162d0, 0x9b888f, 0x2, 0x86901bd4, 0x8ba74a30, 0x8ba74a00, 0x765de0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/peterh/liner/line.go:581 +0x40
github.com/ethereum/go-ethereum/console.(*terminalPrompter).PromptInput(0x86c56060, 0x9b888f, 0x2, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/console/prompter.go:119 +0xa0
github.com/ethereum/go-ethereum/console.(*Console).Interactive.func1(0x86b09680, 0x8ba74a00, 0x869a1f60, 0x8baaa78c, 0x869a1f68)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/console/console.go:321 +0x5c
created by github.com/ethereum/go-ethereum/console.(*Console).Interactive
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/console/console.go:318 +0xc8

goroutine 151 [runnable]:
github.com/ethereum/go-ethereum/consensus/ethash.hashimotoFull.func1(0xcac6e5, 0x71a14908, 0x40, 0x3538fe0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:396 +0x6c
github.com/ethereum/go-ethereum/consensus/ethash.hashimoto(0x9180aefc, 0x20, 0x20, 0xf820d3d3, 0x34bec29, 0x3ffff880, 0x0, 0x9180ae40, 0x575498, 0x10d364, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:357 +0x2a8
github.com/ethereum/go-ethereum/consensus/ethash.hashimotoFull(0x3eef9008, 0xffffe20, 0xffffe20, 0x9180aefc, 0x20, 0x20, 0xf820d3d3, 0x34bec29, 0x93c4e060, 0x20, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:400 +0x98
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).mine(0x869d2b80, 0x9258ab90, 0x2, 0xf820d1b3, 0x34bec29, 0x927101c0, 0x92710200)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:165 +0x304
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).Seal.func1(0x926cf610, 0x869d2b80, 0x9258ab90, 0x927101c0, 0x92710200, 0x2, 0xf820d1b3, 0x34bec29)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:99 +0x70
created by github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).Seal
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:97 +0x174

goroutine 152 [runnable]:
github.com/ethereum/go-ethereum/consensus/ethash.hashimotoFull.func1(0x1dfc79, 0x466eae08, 0x40, 0xe2036a0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:396 +0x6c
github.com/ethereum/go-ethereum/consensus/ethash.hashimoto(0x8684fefc, 0x20, 0x20, 0xf7d2a7e, 0x1df8826f, 0x3ffff880, 0x0, 0x8684fe40, 0x575498, 0x10d364, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:357 +0x2a8
github.com/ethereum/go-ethereum/consensus/ethash.hashimotoFull(0x3eef9008, 0xffffe20, 0xffffe20, 0x8684fefc, 0x20, 0x20, 0xf7d2a7e, 0x1df8826f, 0x93bcd340, 0x20, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:400 +0x98
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).mine(0x869d2b80, 0x9258ab90, 0x3, 0xf7d285e, 0x1df8826f, 0x927101c0, 0x92710200)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:165 +0x304
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).Seal.func1(0x926cf610, 0x869d2b80, 0x9258ab90, 0x927101c0, 0x92710200, 0x3, 0xf7d285e, 0x1df8826f)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:99 +0x70
created by github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).Seal
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:97 +0x174

goroutine 153 [select]:
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).Seal.func2(0x92710180, 0x927101c0, 0x92710200, 0x868651c0, 0x869d2b80, 0x9258ab90, 0xc29e78, 0x8b53c000, 0x926cf610)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:105 +0x8c
created by github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).Seal
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:103 +0x1e4

goroutine 155 [runnable]:
github.com/ethereum/go-ethereum/consensus/ethash.generateCache.func2(0x927102c0, 0xc2b3a0, 0x92712950, 0x926cf6b8, 0x407f3, 0xe2e74717, 0xc09ce784, 0xd936c49e, 0x1, 0x15d9248)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:171 +0xb8
created by github.com/ethereum/go-ethereum/consensus/ethash.generateCache
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/algorithm.go:169 +0x1a8

**Comment by holiman** [comment]
You seem to be using an _ancient_ version of geth, built on `golang 1.11`. 
Please try with a more recent version, because we do not support very old version. 
Feel free to reopen if the problem persists.
