### ISSUE TITLE
Missing historical data in archive node on debug_traceTransaction call

### ISSUE THREAD

**Issue by torrentx** [ethereum/go-ethereum#24995]
I'm trying to run a trace on TransactionHash: 0xbec6f9215f21dba5e81d4d230d1c05e6fde870b2abaeefa6d738de3564c92bcb

And receiving the following error:
{"code":-32000,"message":"required historical state unavailable (reexec=128)"}

Running my node with the following command line: 
/usr/bin/geth --http --http.api=eth,web3,debug,txpool,net,admin,debug --ws --ws.api=eth,web3,debug,txpool,net,admin,debug --http.addr=0.0.0.0 --http.port=9456 --ws.addr=0.0.0.0 
--ws.port=9457 --mainnet --datadir=/ethdata/mainnet --http.vhosts=* --ws.origins=* --rpc.gascap=0 --rpc.txfeecap=0 --metrics --metrics.expensive --metrics.addr=0.0.0.0 --metrics.port=6061 
--port=30304 --syncmode=full --gcmode=archive --txlookuplimit=0

Version: 1.10.16

**Comment by s1na** [comment]
Did you do the archive sync from beginning or only switched to archive after some point?

**Comment by torrentx** [comment]
Same, No State Found

**Comment by holiman** [comment]
Would be interesting to see the db metadata, but I think that requires you to shut it down, and run something like 'geth db metadata' .

**Comment by rjl493456442** [comment]
well, looks like your database is empty. Are you sure you are using the right datadir?

**Comment by torrentx** [comment]
Would probably help to use the right one: 
![image](https://user-images.githubusercontent.com/479374/171643743-94817a0c-9f6c-454d-8175-f7dcf9b8b8e4.png)

**Comment by holiman** [comment]
This is really odd. Because, `debug_getAccessibleState(12615021, 0)`, or if you were to try e.g. `debug_getAccessibleState("latest", 0)` -- wil check every state root from latest to genesis, and stop at the first one which it can find in the database. 

So when you say that it `debug_getAccessibleState(12615021, 0)` reports back "No state found", then it means that there are not a single stateroot stored for those 12 million blocks. Which is very very odd indeed. 

But, can you please try `debug_getAccessibleState("latest", 0)` again, and paste the response here?

**Comment by torrentx** [comment]
debug_getAccessibleState("latest", 0) returns
Id = 366, Status = RanToCompletion, Method = "{null}", Result = "{\"jsonrpc\":\"2.0\",\"id\":67,\"result\":14921278}\n"10:22 AM 6/7/2022

**Comment by holiman** [comment]
I have a hunch now. But try `debug_getAccessibleState(0, "latest")`, and it should show you the first state that is accessible. And I suspect that it will say `14388179`, which is the `lastPivotNumber` in your metadata. 

Which implies that this node pivoted (syncmode snap or fast) , and did not sync block by block ( syncmode=full).

**Comment by cromaniuc** [comment]
@torrentx how did it go?

**Comment by PPianAIC** [comment]
@holiman I have the same problem. Here is my logs. I want to know how the debug model should run
> debug.getAccessibleState(0, "latest")
15537329
debug.traceTransaction("0xf978486bed72890591704ce0fe9d802d88b8f74a576b0e3593acfea89151b337", {"tracer": "callTracer"})
Error: required historical state unavailable (reexec=128)
        at web3.js:6365:9(45)
        at send (web3.js:5099:62(34))
        at <eval>:1:23(7)
### System information
> Geth
Version: 1.10.26-stable
Architecture: arm64
Go Version: go1.18.9
Operating System: linux
GOPATH=
GOROOT=go
### Command
./geth --datadir /data1/ethereum/ethereum/.ethereum --http --http.port 8454 --http.addr "0.0.0.0" --http.api eth,net,engine,admin,debug,txpool,web3,trace --ws --ws.addr "0.0.0.0" --ws.port 8456 --ws.origins "" --http.corsdomain "" --rpc.allow-unprotected-txs --txlookuplimit 0 --allow-insecure-unlock --maxpeers 1000 --gcmode archive --cache 56000 --authrpc.addr "0.0.0.0" --authrpc.port 8551 --authrpc.vhosts localhost --authrpc.jwtsecret /data1/ethereum/ethereum/consensus/prysm/jwt.hex

**Comment by s1na** [comment]
@PPianAIC The tx you want to trace is in block [11146795](https://etherscan.io/block/11146795). Can you check the result of:

```terminal
debug.getAccessibleStates(11146790, 11146796)
```

**Comment by holiman** [comment]
Closing this, stale + seems abandone
