### ISSUE TITLE
Is it recommended to upgrade the mainnet geth to v1.10.18?

### ISSUE THREAD

**Issue by vae520283995** [ethereum/go-ethereum#25003]
The release notes say it's mainly an update about the Ropsten network, do I need to upgrade the mainnet geth to v1.10.18?

**Comment by holiman** [comment]
Yes, we always recommend upgrading to the latest version. Do you _need_ to? No.

**Comment by vae520283995** [comment]
> Yes, we always recommend upgrading to the latest version. Do you _need_ to? No.

ok thank you

**Comment by vae520283995** [comment]
```
INFO [06-01|11:00:37.784] Imported new chain segment               blocks=13    txs=2482      mgas=207.257 elapsed=10.175s   mgasps=20.368 number=14,865,647 hash=545805..c78dfe age=3d1h45m  dirty=1022.75MiB
INFO [06-01|11:00:47.265] Imported new chain segment               blocks=9     txs=2467      mgas=176.042 elapsed=9.480s    mgasps=18.568 number=14,865,656 hash=32a2f3..5e60d0 age=3d1h43m  dirty=1023.47MiB
INFO [06-01|11:00:55.675] Imported new chain segment               blocks=14    txs=2050      mgas=186.113 elapsed=8.409s    mgasps=22.132 number=14,865,670 hash=fc97e8..fc642a age=3d1h40m  dirty=1018.35MiB
```
@holiman 
By the way, every time I restart geth, it lags days behind, what is the reason for this, and is there any way to quickly continue the sync?

**Comment by holiman** [comment]
That depends on how you restart it. If you kill it without giving it time to flush to disk, so called unclean shutdown, then this is expected.

**Comment by vae520283995** [comment]
> That depends on how you restart it. If you kill it without giving it time to flush to disk, so called unclean shutdown, then this is expected.

I use docker, by command docker restart

**Comment by holiman** [comment]
Docker doesn't by default give sufficent time. You need to use e.g. `-t 120` - beacause `docker stop` by default only allows 10s before hard-killing it https://docs.docker.com/engine/reference/commandline/stop/

**Comment by vae520283995** [comment]
> Docker doesn't by default give sufficent time. You need to use e.g. `-t 120` - beacause `docker stop` and `docker restart` by default only allows 10s before hard-killing it
> 
> https://docs.docker.com/engine/reference/commandline/stop/
> 
> https://docs.docker.com/engine/reference/commandline/restart/

thank you, this helped me a lot
