### ISSUE TITLE
1.4.0 (develop) does not report newBlockFilter changes

### ISSUE THREAD

**Issue by almindor** [ethereum/go-ethereum#2501]
#### System information

Geth version: 1.4.0
OS & Version: OSX El Capitan
Commit hash : 123aa659e4e2bdb9121f787ee8cd68acc9a4fe4c

#### Expected behaviour
Geth reports new blocks as they come in on a newBlockFilter's getFilterChanges call.

#### Actual behaviour
Geth reports "[]" all the time

#### Steps to reproduce the behaviour
Start geth, let it sync. Register a new block filter via RPC. Call getFilterChanges periodically and get [] all the time. Switch to 1.3.6 and it works, new blocks are reported.

**Comment by bas-vk** [comment]
Could you verify that new blocks are actually imported (check `eth_blockNumber` once a while)? If not `eth_getFilterChanges` will report `[]` until a block is imported. Also note, from version 1.4 the filter id format has changed. In previous version this was an increasing number `"0x0", "0x1", "0x2", ...`. That has been changed, it now returns a long random filter id.

```
> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_newBlockFilter","params":[],"id":73}' localhost:8545
{"jsonrpc":"2.0","id":73,"result":"0xa158ca25dc1600f767ff19355397d2d8"}

> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0xa158ca25dc1600f767ff19355397d2d8"],"id":73}' localhost:8545 --silent | jq -S .
{
  "id": 73,
  "jsonrpc": "2.0",
  "result": [
    "0x23d4f112c183d946c07b00b8f2b779e6e4d8f07ef3358dc0646d2ac95a743c39",
    "0xe3ecad54d1bbc717cd97ac2b21e8798542242942eaa8f8f8cabe125ca47d8fb2",
    "0x0012eda33a4568378ba9be6df3c62c223c2a21c10fc5a7e8a9931ef5e51b9f47",
    "0xf478615923a4cc8daa65fbff250efca1cbcd0c8a14ca0ab4d8a6639b31316b0a",
    "0x3283cb92113bf67920c2daf21b06dcc8577e7722d9403bdc22842a4b2d64c5fc",
    "0xddb9494caaa749ec160a5eab3d551308e19904d0c2c0d5086353a781de54b10c",
    "0x6d748a5d8242decb9f0f3bfbb19dcd308f6f5396ecac4b5abec26f871c2bfefc",
    "0xaec2fee568a978ea5be75969ae608d463c6d658a5e5a1f312c950a96b0ac23e1"
  ]
}
```
