### ISSUE TITLE
`debug_accountRange` missing preimages

### ISSUE THREAD

**Issue by lightclient** [ethereum/go-ethereum#25025]
It seems like every request I make with `debug_accountRange` results in a `WARN` message saying the preimages are missing.

```console
$ geth attach
> debug.accountRange("latest", "", 5, false, false)
{
  accounts: {},
  root: "daf1a97a5164a16873d01a7468716083657067b61b9248ad9d33035dc939fcf1"
}
```

```
INFO [06-04|08:04:05.582] Trie dumping started                     root=daf1a9..39fcf1
WARN [06-04|08:04:05.582] Dump incomplete due to missing preimages missing=10
INFO [06-04|08:04:05.582] Trie dumping complete                    accounts=0  elapsed="694.875µs"
```

**Comment by holiman** [comment]
We don't collect preimages by default.  Which might be worth changing.

**Comment by lightclient** [comment]
Ah yes okay, I see now with `--cache.preimages` it does work. I don't have enough context to weigh in on whether or not preimages should be collected by default, but it does feel like this method should return an error of some sort if the preimages are not found rather than a log.

**Comment by karalabe** [comment]
Preimages weighed 30+GB when we dropped them. Given that they are not used internally for anything, seems like a good thing to drop. We might want to collect them for the Verkle transition, but that's for a later time.

**Comment by karalabe** [comment]
> this method should return an error of some sort if the preimages are not found rather than a log.

I *think* the account dump is complete, only the addresses might be missing for those that don't have preimages. But the accounts themselves should still all be listed. So it's "complete" from an API perspective, just not all meta info is available (but you see that it's missing from the fact that they're not in there :P).
