### ISSUE TITLE
attach failed on testnet

### ISSUE THREAD

**Issue by arthew** [ethereum/go-ethereum#2502]
#### System information

Geth version: `1.4.0 RC`
OS & Version: Linux
Commit hash : (if `develop`)

when run geth attach
#### Expected behaviour

attach successfully
#### Actual behaviour

Exception shows that ./ethereum/geth.ipc cannot connect
#### Steps to reproduce the behaviour
1. start geth using testnet: geth --testnet
2. try attach using another process as: geth attach
#### Backtrace

After that, I try to make an soft link for geth.ipc on directory .ethereum/, and than it runs ok
ln -s ./testnet/geth.ipc geth.ipc

**Comment by obscuren** [comment]
We're looking in to making this easier. For now you can do the following: `geth attach ipc:/home/<username>/.ethereum/testnet/geth.ipc`.

**Comment by ryepdx** [comment]
The `--ipcpath` flag also does not appear to be working with `attach`.

@obscuren's suggestion worked for me, though.

**Comment by pipermerriam** [comment]
Worth noting that `geth attach ipc:~/Library/Ethereum/testnet/geth.ipc` doesn't work because the `~` is not expanded.  You need to do the full path ``geth attach ipc:/Users/<your_osx_username>/Library/Ethereum/testnet/geth.ipc`

**Comment by tymat** [comment]
Any progress on this?  Our automation scripts are breaking because of this.

**Comment by fjl** [comment]
@pipermerriam The ipc: prefix will no longer be required on the develop branch.

**Comment by GitDoggo** [comment]
how hard is it to check for geth.ipc in `/.ethereum` _AND_ in `/.ethereum/testnet` ?

**Comment by MaiaVictor** [comment]
@GitDoggo wondering the same. Anyone?

**Comment by eolszewski** [comment]
ethminer is refusing to look in /testnet for geth.ipc (i think) and i'm getting 
`JSON-RPC problem. Probably couldn't connect. Retrying in 1...`

The symlink trick worked for geth attach, but ethminer is still not working :/

**Comment by karalabe** [comment]
AFAIK ethminer uses HTTP RPC, not IPC. I.e. you need to allow RPC connections to geth (`--rpc`) to make ethminer connect to it. But that's a completely different topic from this thread.

Since `geth attach <path>` works and is pretty obvious, I see no reason to keep this issue open. Feel free to open a new issue if you have something in particular, but this thread got too convoluted already to follow a clear "problem".
