### ISSUE TITLE
Eip-1559 Transaction can't broadcast   rlp: expected input list for types.LegacyTx

### ISSUE THREAD

**Issue by 1b1og-com** [ethereum/go-ethereum#25027]
my transaction code
```
tx := types.NewTx(&types.DynamicFeeTx{
		ChainID:   big.NewInt(config.CHAIN_ID),
		Nonce:     nonce,
		GasTipCap: gasTipCap,
		GasFeeCap: gasFeeCap,
		Gas:       gas,
		To:        &toAddress,
		Value:     value,
		Data:      bytes,
		AccessList: nil,
	})

        chainConfig := params.MainnetChainConfig
	chainBlock := params.MainnetChainConfig.LondonBlock

	signer := types.MakeSigner(chainConfig, chainBlock)

	signTx, err := types.SignTx(tx, signer, privateKey)

        hash := signTx.Hash().Bytes()
	logrus.Printf("Signer Hash: 0x%x", hash)

	b, err := rlp.EncodeToBytes(signTx)
	if err != nil {
		return "", err
	}

	raw := fmt.Sprintf("raw: 0x%x", b)

```

when sendRawTransaction response error:
```
{
    "jsonrpc": "2.0",
    "id": 67,
    "error": {
        "code": -32000,
        "message": "rlp: expected input list for types.LegacyTx"
    }
}
```

**Comment by levinmy** [comment]
data, err := tx.MarshalBinary() 
hexutil.Encode(data)

**Comment by karalabe** [comment]
@1b1og-com Could you please check the error returned form `types.SignTx(tx, signer, privateKey)`

**Comment by 1b1og-com** [comment]
https://github.com/ethereum/go-ethereum/issues/25027#issuecomment-1147268011

**Comment by 1b1og-com** [comment]
cool

**Comment by ethermachine** [comment]
> 

I found this useful for decoding eip1559 txs..

I was trying another approach but it **generates an invalid raw tx string**
rawtx, _ := rlp.EncodeToBytes(&tx)
rawtx_string := hex.EncodeToString(rawtx)

**Comment by ethermachine** [comment]
> data, err := tx.MarshalBinary()
> hexutil.Encode(data)


I found this useful for decoding eip1559 txs..

I was trying another approach but it generates an invalid raw tx string
rawtx, _ := rlp.EncodeToBytes(&tx)
rawtx_string := hex.EncodeToString(rawtx)

**Comment by lightclient** [comment]
@ethermachine this is because EIP-2718 transactions _cannot_ be RLP encoded due to the type byte prefix at the beginning.

**Comment by ethermachine** [comment]
@lightclient thanks for the explanation, it makes sense now! 
I wasnt aware of eip2718 and that it included the tx type. I already wondered why the transaction type wasnt anymore present in the transaction attributes, but haven't investigated the reason, now i know
