### ISSUE TITLE
graphql endpoint doesn't obey http.vhosts

### ISSUE THREAD

**Issue by SLoeuillet** [ethereum/go-ethereum#25039]
#### System information

Geth version: 1.10.18
OS & Version: Linux Ubuntu 20.04
Commit hash : "Geth/v1.10.18-stable-de23cf91/linux-amd64/go1.18.1"

#### Expected behaviour
graphql endpoint should be queryable using specified http.vhosts like for RPC

#### Actual behaviour
"invalid host specified"

#### Steps to reproduce the behaviour
First node : --graphql --http --http.addr 'A.B.C.D' --http.vhosts 'geth.ethereum-mainnet.ovh.int.kaiko.com,geth00.ethereum-mainnet.ovh.int.kaiko.com'
Second node : --graphql --http --http.addr 'A.B.C.D' --http.vhosts 'geth.ethereum-mainnet.ovh.int.kaiko.com,geth01.ethereum-mainnet.ovh.int.kaiko.com'

Both nodes in DNS RR geth.ethereum-mainnet.ovh.int.kaiko.com

```
curl -X POST http://geth.ethereum-mainnet.ovh.int.kaiko.com:8545/graphql -H "Content-Type: application/json" --data '{ "query": "query txInfo { block(number:13870512) { hash number difficulty logsBloom nonce parent { hash } timestamp transactions { createdContract { address } cumulativeGasUsed from { address } gasUsed logs { account { address } data index topics } hash index to { address } status } number } }" }' 
```

Workaround, by specifying hostname as 'localhost' :

```
curl -X POST http://geth.ethereum-mainnet.ovh.int.kaiko.com:8545/graphql -H "Content-Type: application/json" --data '{ "query": "query txInfo { block(number:13870512) { hash number difficulty logsBloom nonce parent { hash } timestamp transactions { createdContract { address } cumulativeGasUsed from { address } gasUsed logs { account { address } data index topics } hash index to { address } status } number } }" }' -H "Host: localhost"
```

**Comment by karalabe** [comment]
It's `--graphql.vhosts`
