### ISSUE TITLE
There's no indication of how to confirm if transaction was successful.

### ISSUE THREAD

**Issue by hirohido** [ethereum/go-ethereum#25031]
It would be nice if there was indication on the documentation on how to confirm if a transaction was successful or not.

**Comment by s1na** [comment]
What do you mean by successful, if it was included in a block or it didn't fail with an error (no revert)? You can do `eth.getTransaction(<hash>)` to see if it was included in a block. And you can check `eth.getTransactionReceipt(<hash>)` which includes the `status` field.

**Comment by hirohido** [comment]
In my app, when i send a transaction, i sleep for ten seconds, then send  an eth.getTransaction(<hash>) request. My app needs to follow up with a transaction to see if it was included in a block and was mined without a revert. I'm trying to optimize it in a way that does not require a sleep and multiple eth.getTransaction(<hash>) calls.

**Comment by hirohido** [comment]
Awesome! Thanks a bunch!
