### ISSUE TITLE
Add difficulty and possibly totalDifficulty as metrics

### ISSUE THREAD

**Issue by willianpaixao** [ethereum/go-ethereum#25043]
# Rationale

While testing the merge in the Ropsten testnet, I tried to add current block _difficulty_ to my dashboards and realized this is not exposed. Such metric can be used to improve monitoring with tools like Prometheus and Alertmanager, alarms can be triggered upon thresholds set by the node operator and get notified.

Bonus if _totalDifficulty_ could also be exposed, since the monitoring tools can compare with _difficulty_.

**Comment by Adminhelpcenter** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/

**Comment by Baro1905** [comment]
25043

**Comment by kalverra** [comment]
+1 on this. I see that `Difficulty` is retrieved, but not `TotalDifficulty`. I haven't dug into it, but I'm assuming there's a more compelling reason than "we forgot to add it".

```go
type Header struct {
	ParentHash  common.Hash    `json:"parentHash"       gencodec:"required"`
	UncleHash   common.Hash    `json:"sha3Uncles"       gencodec:"required"`
	Coinbase    common.Address `json:"miner"`
	Root        common.Hash    `json:"stateRoot"        gencodec:"required"`
	TxHash      common.Hash    `json:"transactionsRoot" gencodec:"required"`
	ReceiptHash common.Hash    `json:"receiptsRoot"     gencodec:"required"`
	Bloom       Bloom          `json:"logsBloom"        gencodec:"required"`
	Difficulty  *big.Int       `json:"difficulty"       gencodec:"required"`
        // Add TotalDifficulty here
	Number      *big.Int       `json:"number"           gencodec:"required"`
	GasLimit    uint64         `json:"gasLimit"         gencodec:"required"`
	GasUsed     uint64         `json:"gasUsed"          gencodec:"required"`
	Time        uint64         `json:"timestamp"        gencodec:"required"`
	Extra       []byte         `json:"extraData"        gencodec:"required"`
	MixDigest   common.Hash    `json:"mixHash"`
	Nonce       BlockNonce     `json:"nonce"`
	// BaseFee was added by EIP-1559 and is ignored in legacy headers.
	BaseFee *big.Int `json:"baseFeePerGas" rlp:"optional"`
}
```

**Comment by MariusVanDerWijden** [comment]
`eth.getBlock("latest").totalDifficulty`

**Comment by willianpaixao** [comment]
Hey @MariusVanDerWijden (and @kalverra), I was referring to the metrics exposed on the http://geth:6060/debug/metrics/prometheus.

**Comment by willianpaixao** [comment]
Since the merge this issue is no longer relevant. Closing.
