### ISSUE TITLE
ropsten merge ttd (geth_block_transactions=0)

### ISSUE THREAD

**Issue by basvlanat** [ethereum/go-ethereum#25046]
Hello.
I have two nodes running on a ropsten v1.10.16 testnet running through a docker image ethereum/client-go. Today I noticed that transactions through monitoring stopped going.
![image](https://user-images.githubusercontent.com/60644692/172666963-4f4fcc6d-0fe3-4717-b96b-83a283aa8cec.png)

I read the news about the merger https://blog.ethereum.org/2022/06/03/ropsten-merge-ttd/. 
Did I understand correctly that it is necessary to update the docker image to version v1.10.18 and add the parameter  --override.terminaltotaldifficulty=50000000000000000 and restart my node?
If so, approximately after how long will the node be able to return to a working state?

**Commands on my node:**
      - --ropsten
      - --cache=1024
      - --nousb
      - --port=30303
      - --http 
      - --http.api=admin,debug,miner,txpool,personal,eth,net,web3
      - --http.port=8550
      - --http.addr=0.0.0.0 
      - --http.vhosts=*
      - --http.corsdomain=*
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
      - --graphql 
      - --graphql.vhosts=* 
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=admin,debug,miner,txpool,personal,eth,net,web3
      - --ws.origins=*
      - --rpc.allow-unprotected-txs
      - --cache=1024
      - --override.terminaltotaldifficulty=50000000000000000

**Comment by rjl493456442** [comment]
Ropsten is merged(switch to PoS), in order to keep sync with the network, you should also run a beacon node. 

Here is a simple guide for you. https://geth.ethereum.org/docs/interface/merge

**Comment by basvlanat** [comment]
Okay thanks.
If I understood everything correctly:
1. On the client-go I have to add the parameter --override.terminaltotaldifficulty=100000000000000000000000
2. I have to start the beacon node as described here by giving it the address of my  client-go 
For example
`docker run -it -v $HOME/.eth2:/data -v /path/to/genesis.ssz:/genesis/genesis.ssz -p 4000:4000 -p 13000:13000 -p 12000:12000/udp --name beacon-node \
  gcr.io/prysmaticlabs/prysm/beacon-chain:stable \
  --datadir=/data \
  --rpc-host=0.0.0.0 \
  --monitoring-host=0.0.0.0 \
  --http-web3provider=<YOUR_ETH_EXECUTION_NODE_ENDPOINT> \
  --genesis-state=/genesis/genesis.ssz \
  --prater`
  And should i run beacon on testnet --**prater**?
  
Is it true ??
