### ISSUE TITLE
always got "Unexpected trienode heal packet" for a long time when using snap sync for ropsten

### ISSUE THREAD

**Issue by shiziwen** [ethereum/go-ethereum#25041]
When I run geth node on ropsten, I always got the below error for a long time, and the sync block number is the same.

```
INFO [06-08|15:43:20.342] Imported new block headers               count=0    elapsed=7.995ms     number=12,308,105 hash=52ffbb..ee8ee8 age=1w5d13h    ignored=64
INFO [06-08|15:43:20.342] Legacy sync reached merge threshold      number=12,308,106 hash=a6fbe9..bdbf28 td=43,532,321,247,089,466 ttd=43,531,756,765,713,534
WARN [06-08|15:43:20.393] Unexpected trienode heal packet          peer=e923a3cb reqid=6,498,516,484,410,727,593


INFO [06-08|15:43:20.585] State heal in progress                   accounts=0@0.00B              slots=0@0.00B              codes=0@0.00B            nodes=5,456,266@2.70GiB    pending=4369
WARN [06-08|15:43:20.587] Unexpected trienode heal packet          peer=d9134bba reqid=1,209,038,508,775,278,217
WARN [06-08|15:43:20.604] Unexpected trienode heal packet          peer=98977ce4 reqid=3,426,627,561,803,637,272
INFO [06-08|15:43:20.642] Disabling direct-ancient mode            origin=12,308,041 ancient=11,370,495
WARN [06-08|15:43:20.660] Unexpected trienode heal packet          peer=9e6c9c81 reqid=4,699,916,736,640,905,528
WARN [06-08|15:43:20.670] Unexpected trienode heal packet          peer=b96c6d4f reqid=8,345,207,299,594,662,469
WARN [06-08|15:43:20.676] Unexpected trienode heal packet          peer=5b63712f reqid=9,036,773,175,743,647,285
WARN [06-08|15:43:20.682] Unexpected trienode heal packet          peer=3581c94f reqid=9,026,082,704,471,782,716
WARN [06-08|15:43:20.684] Unexpected trienode heal packet          peer=d8ba14d1 reqid=4,989,796,161,087,014,513
WARN [06-08|15:43:20.686] Unexpected trienode heal packet          peer=8de6cfff reqid=8,478,676,383,261,831,408
WARN [06-08|15:43:20.686] Unexpected trienode heal packet          peer=cb2bf0be reqid=8,100,761,671,062,976,675

```

The command is `geth-linux-amd64-1.10.18-de23cf91/geth --ropsten --override.terminaltotaldifficulty 100000000000000000000000 --authrpc.addr localhost --authrpc.port 9551 --authrpc.vhosts localhost --authrpc.jwtsecret /data1/ropsten/jwtsecret --syncmode "snap"  --datadir /data1/ropsten/datadir --cache 2048 --identity "ddblock"  --http  --http.api eth,net,web3   --http.vhosts="*"  --http.corsdomain "*" --http.port 9545 --port 40303 --http.addr 0.0.0.0`.

**Comment by holiman** [comment]
` --override.terminaltotaldifficulty 100000000000000000000000` -- this is good
`Legacy sync reached merge threshold      number=12,308,106` -- this is bad. It means that the switch above didn't work, and it thinks it's now in merge-mode.

The sync is in a kind of odd state, and you will need to restart the node for the override flag to go into effect.

**Comment by Adminhelpcenter** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/

**Comment by shiziwen** [comment]
Thank you,
Actually, after I restarted the node, it works.
