### ISSUE TITLE
Help Lost my Private key but ı have keystore

### ISSUE THREAD

**Issue by r00tkox** [ethereum/go-ethereum#25066]
#### System information

Geth version: `1.10.18-stable`
OS & Version: Linux (Ubuntu)/Windows 10

Hello Guys,

I have mew v2 json file. I want to convert this file to v3 utc via geth but I am getting an error, what should I do? i get the same error on windows 10 and linux (kali and ubuntu)

Geth Error: Fatal: Failed to load the private key: key file too short, want 64 hex characters

Method i tried: https://help.myetherwallet.com/en/articles/5449838-importing-a-v2-json-file

**Comment by holiman** [comment]
I think the instructions at MEW are wrong, the `account import` comand: "Import a private key into a new account". So it expects the input to be a 32-byte hex-encoded key. 

I think it would be better to use `geth account update` : 

>     geth account update <address>
> 
> Update an existing account.
>
> The account is saved in the newest version in encrypted format, you are prompted
> for a password to unlock the account and another to save the updated file.
> 
> This same command can therefore be used to migrate an account of a deprecated
> format to the newest format or change the password for an account.

So first just copy the v2 file into your keystore location, then update it.

**Comment by holiman** [comment]
We don't know what the MEW V2 file contains, or how it it structured. Geth has keystore v1 and v3 definitions, but as for V2 we're no idea. 
The documentation at MEW is wrong, and not very informative at all. 
There's not much we can do, but if you find more information about the "MEV V2 format" then we can look into it. For now, I'd open an issue at MEW instead. 
Closing this
