### ISSUE TITLE
nginx to cache eth_blocknumber

### ISSUE THREAD

**Issue by PDVJAM** [ethereum/go-ethereum#25062]
Hey everyone!
We're trying to create a geth node instead of using Infura. Has anyone tried to use nginx in front of geth (must be simple) AND cache eth_blocknumber requests (so nginx will return eth_blocknumber from the cache for several requests)? In theory in that case node can support more requests.

**Comment by badbitses** [comment]
I'm green but I wanna learn and  I can be very helpful.

**Comment by badbitses** [comment]
Back to point. .very good factoring...as a fact I see the math act. In 4th and 5th dims #, #+#, #×#, #^#, #x#

**Comment by badbitses** [comment]
The factoring of the blocks like the pyramids typical pyramid is actually a square at base...whereas there is a true pyramid has 4 sides 3 form the 4th. Though the 4th is illusory or rather created...it can stand as any side and be completed. That's the 4th dimension. Once it is itself factored. So the deviation becomes a 4 sided object

**Comment by karalabe** [comment]
Please ask questions on the Ethereum stack exchange https://ethereum.stackexchange.com/
