### ISSUE TITLE
Will the old blocks keep moving into the ancient dir during the Geth running?

### ISSUE THREAD

**Issue by cifer76** [ethereum/go-ethereum#25068]
After having read through the source code it seems only during the initial sync the old blocks(earlier than `anclientLimit`) will be put into the ancient dir, but I think it's not optimal, as the node running after full sync the old blocks should also be migrated into ancient automatically?

Maybe I overlooked from the source code, could you help clarify the behavior?

**Comment by holiman** [comment]
During sync, blocks are shoved directly into the ancientdb. While processing block by block (post-initial-sync), it gets migrated from time to time. Check out https://github.com/ethereum/go-ethereum/blob/master/core/rawdb/chain_freezer.go
