### ISSUE TITLE
Generics instantiation error using mapset.Set[T comparable] within rpc/server.go and rpc/websocket.go

### ISSUE THREAD

**Issue by th3outcast** [ethereum/go-ethereum#25065]
#### System information

Geth version: `1.10.3-stable`
OS & Version: Windows/Linux/OSX

#### Expected behaviour
Dial into an ethclient.

#### Actual behaviour
Generics instantiation errors.

#### Steps to reproduce the behaviour
Use the import:

````
import "github.com/ethereum/go-ethereum/ethclient"
````

#### Backtrace

````
# github.com/ethereum/go-ethereum/rpc
../../ethereum/go-ethereum/rpc/server.go:49:11: cannot use generic type mapset.Set[T comparable] without instantiation
../../ethereum/go-ethereum/rpc/server.go:55:69: cannot infer T (/home/zero/Documents/Go/src/github.com/deckarep/golang-set/set.go:180:13)
../../ethereum/go-ethereum/rpc/websocket.go:72:26: cannot infer T (/home/zero/Documents/Go/src/github.com/deckarep/golang-set/set.go:180:13)
../../ethereum/go-ethereum/rpc/websocket.go:125:37: cannot use generic type mapset.Set[T comparable] without instantiation
````

**Comment by th3outcast** [comment]
Issue caused by breaking changes to **github.com/deckarep/golang-set** v2.1.0 module dependency, works fine on previous v1.7.1.

**Comment by fjl** [comment]
There is nothing simple we can do here to fix this.

go-ethereum depends on golang-set v1.8.0. The new library version v2.x has an incompatible API, and using both at the same time seems not possible. We will not upgrade to the generics-based version of this library until next year.

What we could do is, remove the dependency and implement our own set using a map instead.

**Comment by deckarep** [comment]
@karalabe - hello I'm the original author of the golang-set module and purposely didn't want to have to maintain two separate API's going forward. The hope is that people eventually cut over to the generics implementation at some point.

With that being said, if there is a super solid reason to have two differing API's supported (generics and non-generics) I could be swayed to incorporate it if it really, really helps out the Ethereum project. 

But, my preference is to just have you upgrade to the generics version when the time comes. I also recognize that a project of this size might take longer to supporting generics.

Please let me know as I'm here to help!

-@deckarep

**Comment by fjl** [comment]
Yeah, we will just wait for a while and then change to the new version. go-ethereum has a policy to support the last two or even three Go versions, so we cannot start using generics until spring 2023.

**Comment by deckarep** [comment]
@fjl - sounds good if golang-set becomes an issue between now and than…just let me know!
