### ISSUE TITLE
Geth node does not fall into the correct chain of the ropsten test network

### ISSUE THREAD

**Issue by basvlanat** [ethereum/go-ethereum#25070]
Hello.
I have geth node version 1.10.18 running. After merging the networks and adding the parameter `--override.terminaltotaldifficulty=50000000000000000`. The logs keep repeating messages:
  | WARN [06-13|08:09:09.047] Local chain is post-merge, waiting for beacon client sync switch-over... 
  | INFO [06-13|08:09:09.153] Legacy sync reached merge threshold      number=12,357,771 hash=da871a..b1cd17 td=50,555,542,962,209,070 ttd=50,000,000,000,000,000
  | INFO [06-13|08:09:09.290] Legacy sync reached merge threshold      number=12,357,771 hash=da871a..b1cd17 td=50,555,542,962,209,070 ttd=50,000,000,000,000,000
  | INFO [06-13|08:09:09.476] Legacy sync reached merge threshold      number=12,357,771 hash=da871a..b1cd17 td=50,555,542,962,209,070 ttd=50,000,000,000,000,000

I read [here](https://geth.ethereum.org/docs/interface/merge) that now it is necessary to launch a beacon node, which, as a client, connects to the geth node. Launched it and synchronized. Beacon node logs, I don't see errors:
time="2022-06-13 11:11:12" level=info msg="Synced new block" block=0x6c5f826e... epoch=100520 finalizedEpoch=100518 finalizedRoot=0xc43e2016... prefix=blockchain slot=3216656
 time="2022-06-13 11:11:12" level=info msg="Finished applying state transition" attestations=68 prefix=blockchain slot=3216656 syncBitsCount=392
time="2022-06-13 11:11:36" level=info msg="Synced new block" block=0x4e55e0c1... epoch=100520 finalizedEpoch=100518 finalizedRoot=0xc43e2016... prefix=blockchain slot=3216658
time="2022-06-13 11:11:36" level=info msg="Finished applying state transition" attestations=128 prefix=blockchain slot=3216658 syncBitsCount=392
time="2022-06-13 11:11:49" level=info msg="Synced new block" block=0xe383afe1... epoch=100520 finalizedEpoch=100518 finalizedRoot=0xc43e2016... prefix=blockchain slot=3216659
time="2022-06-13 11:11:49" level=info msg="Finished applying state transition" attestations=102 prefix=blockchain slot=3216659 syncBitsCount=392
time="2022-06-13 11:11:56" level=error msg="Could not connect to execution client endpoint: could not make initial request to verify execution chain ID: wanted chain ID 5, got 3" prefix=powchain
time="2022-06-13 11:12:00" level=info msg="Synced new block" block=0xd72493d7... epoch=100520 finalizedEpoch=100518 finalizedRoot=0xc43e2016... prefix=blockchain slot=3216660
time="2022-06-13 11:12:00" level=info msg="Finished applying state transition" attestations=75 prefix=blockchain slot=3216660 syncBitsCount=390
time="2022-06-13 11:12:11" level=info msg="Peer summary" activePeers=40 inbound=0 outbound=40 prefix=p2p

**My geth node is running in docker like this:**
version: '3.9'
services:
  ETH-test-node:
    image: ethereum/client-go:v1.10.18
    hostname: eth-test-node
    volumes:
      - "/mnt/data0/ethereum-test-data/root2/:/root"
    command:
      - --ropsten
      - --cache=1024
      - --nousb
      - --port=30303
      - --http 
      - --http.api=admin,debug,miner,txpool,personal,eth,net,web3
      - --http.port=8550
      - --http.addr=0.0.0.0 
      - --http.vhosts=*
      - --http.corsdomain=*
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
      - --graphql 
      - --graphql.vhosts=* 
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=admin,debug,miner,txpool,personal,eth,net,web3
      - --ws.origins=*
      - --rpc.allow-unprotected-txs
      - --cache=1024 
      - --override.terminaltotaldifficulty=50000000000000000
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8550:8550
      - 8546:8546
      - 6060:6060

**My beacon node is running in docker like this:**
version: '3.7'
services:
  beacon-test-node:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v2.1.3-rc.3
    hostname: beacon-test-node
    volumes:
      - "/mnt/data0/beacon-test-node/data:/data"
      - "/mnt/data0/beacon-test-node/genesis/genesis.ssz:/genesis/genesis.ssz"
    command:
      - --datadir=/data
      - --rpc-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --http-web3provider=http://eth-test-node:8550
      - --genesis-state=/genesis/genesis.ssz
      - --terminal-total-difficulty-override=50000000000000000
      - --prater
      - --ropsten
      - --accept-terms-of-use
    ports:
      - 4000:4000
      - 13000:13000 
      - 12000:12000/udp

Please help me figure out what I did wrong?

**Comment by s1na** [comment]
I see this error in your logs: `Could not connect to execution client endpoint: could not make initial request to verify execution chain ID: wanted chain ID 5, got 3`. I think it's because you're passing `--prater` flag. Also I'm not sure if Prysm picks up the JWT secret that geth generates by default? you might need to pass that in.

**Comment by basvlanat** [comment]
@s1na  Thanks, I think I figured out my mistake.
But when I restart the node beacon sync with flag `--ropsten`, it fails to complete it.
```
version: '3.9'
services:
  beacon-test-node:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v2.1.3-rc.3
    hostname: beacon-test-node
    volumes:
      - "/mnt/data0/beacon-test-node/data1:/data"
      - "/mnt/data0/beacon-test-node/genesis1/genesis.ssz:/genesis/genesis.ssz"
    command:
      - --datadir=/data
      - --rpc-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --http-web3provider=http://eth-test-node:8550
      - --genesis-state=/genesis/genesis.ssz
      - --terminal-total-difficulty-override=50000000000000000
      - --ropsten
      - --accept-terms-of-use
    ports:
      - 4000:4000
      - 13000:13000 
      - 12000:12000/udp
```


 ```
time="2022-06-14 12:11:04" level=info msg="Processing block batch of size 61 starting from  0x8f1a6d3e... 65536/106255 - estimated time remaining 9m46s" blocksPerSecond=69.5 peers=5 prefix=initial-sync
 time="2022-06-14 12:11:04" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x56531606c0bd5a8055c0592c2e6f822bb11e3453c3ab7f44a0e932e76b076117 (in processBatchedBlocks, slot=65536)" prefix=initial-sync
time="2022-06-14 12:11:06" level=info msg="Processing block batch of size 63 starting from  0x5f121470... 65088/106255 - estimated time remaining 9m52s" blocksPerSecond=69.5 peers=5 prefix=initial-sync
time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="could not process block in batch: method not found: received an undefined ee error" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 50 starting from  0x7bc82575... 65152/106255 - estimated time remaining 13m11s" blocksPerSecond=52.0 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x7d3303ad6cf3dfbf55394fd50789a1616af25187984d3d56fd4fafc2f02694da (in processBatchedBlocks, slot=65152)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 49 starting from  0x4d81edfc... 65218/106255 - estimated time remaining 12m34s" blocksPerSecond=54.4 peers=4 prefix=initial-sync
time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x8d4e14afa8f31605b80c317c64852b9d2c25f1770bd80e20c659f2eb977f7b9b (in processBatchedBlocks, slot=65218)" prefix=initial-sync
 time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 57 starting from  0x67aba47f... 65280/106255 - estimated time remaining 11m55s" blocksPerSecond=57.2 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0xd99d8bd1860c47a1995458e09fa422ef7c42fed66575da26c17963e3d99af2e3 (in processBatchedBlocks, slot=65280)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 58 starting from  0x6bfc01f7... 65344/106255 - estimated time remaining 11m20s" blocksPerSecond=60.1 peers=4 prefix=initial-sync
time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x83ac86c72af236e3ce1a02d9261132d4e9a84faf64e3806178e15afc35d91221 (in processBatchedBlocks, slot=65344)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 62 starting from  0x6bc69414... 65408/106255 - estimated time remaining 10m45s" blocksPerSecond=63.2 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0xc374da4e750236af42eb4976412bfc1f96cbed3f07eac1938c42233c97c8442d (in processBatchedBlocks, slot=65408)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 63 starting from  0x19d6d017... 65472/106255 - estimated time remaining 10m14s" blocksPerSecond=66.4 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0xedacd662531617166bc7f0480812010c258d411b8bba2d359310276ec9b7adc7 (in processBatchedBlocks, slot=65472)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 61 starting from  0x8f1a6d3e... 65536/106255 - estimated time remaining 9m46s" blocksPerSecond=69.5 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x56531606c0bd5a8055c0592c2e6f822bb11e3453c3ab7f44a0e932e76b076117 (in processBatchedBlocks, slot=65536)" prefix=initial-sync
 time="2022-06-14 12:11:10" level=info msg="Connected to new endpoint: http://eth-test-node:8550" prefix=powchain

```
Please tell me how to get around this problem?

**Comment by MariusVanDerWijden** [comment]
You should ask on the prysm github about this issue: https://github.com/prysmaticlabs/prysm

**Comment by MariusVanDerWijden** [comment]
I'll close this issue for now, feel free to reopen if there is something we (geth) needs to do
