### ISSUE TITLE
Full-Sync slows heavily down after 2.3 million and does not speedup after

### ISSUE THREAD

**Issue by JamesTurkey** [ethereum/go-ethereum#25084]
#### System information

Geth version: `v1.10.18`
OS & Version: Ubuntu LTS 20.04
Commit hash : Stable v1.10.18

Additional specs: 16 GB RAM, 1.5TB SSD & 6 vCPUs

#### Expected behaviour

Run `geth --datadir /home/ubuntu/chain --syncmode "full" --cache=16000` after which the node slowly and steady syncs till the last few hundred blocks where it starts with state entries 

#### Actual behaviour

I ran `geth --datadir /home/ubuntu/chain --syncmode "full" --cache=16000` after which the first 2.3 million blocks went really fast, then the DOS attack (block 2.3m->block 2.7m) happened which slowed it heavily down. You would expect that after that it would speed up again but after reaching 3 million it has only been processing 10 blocks per second, I'm currently at 4.6M blocks and that has taken me 2 days, while the first 2 million blocks took me 3 hours.  

#### Steps to reproduce the behaviour

Run `geth --datadir /home/ubuntu/chain --syncmode "full" --cache=16000`

Wait a few hours till you're at 2.3 million, it'll slow down to only a very few blocks per second (if any at all).
12-15 hours later you're at 2.75 million blocks, it speeds up again to ~100 bps
Hit 3 million after which it slows down till an unknown block (1-10 bps steady)

#### Backtrace

`INFO [06-14|06:48:32.726] Unindexing transactions                  blocks=1000 txs=6584  total=2048 elapsed=2.389s`
`INFO [06-14|06:48:37.370] Unindexed transactions                   blocks=2048 txs=14152 tail=2,176,792 elapsed=7.033s`

This is what I see every 10-20 seconds on my console, which I did not see earlier, rest looks normal (just importing new chain segment 1-10 blcks each time it pops up & deep froze chain segment, but thats all normal as far as I know) 

I already tried to use another version, but this did only temporarily speed it up after which it slowed down extremely again.

**Comment by JamesTurkey** [comment]
> Full sync takes a lot of time, on the order of magnitude of a week+. Since full sync also prunes the state as it goes along, any particular reason for doing that instead of just snap syncing?

I hadn't that considered that. Forgive me, I'm running a snap sync now.

Can I ask one more additional question, how much storage should I calculate for a snap sync? I calculated for full 750GB, (1.2TB SSD) but how much would i need for a snap sync? 

Thank you for your reply.

**Comment by karalabe** [comment]
Snap sync requires about 500+GB currently on mainnet, so I'd go with 1TB to be on the safe side. Geth's pruning isn't the best for now, so it piles data quicker than it should.
