### ISSUE TITLE
Chain data completely wiped out after unclean shutdown

### ISSUE THREAD

**Issue by nuliknol** [ethereum/go-ethereum#25080]
Another year, and another bug in database consistency. Every year I have to report a new bug because someone can't read a book on database design and specially at the operating system level because you can't just `open()` and then `append()` data to a file (like you are doing in geth), that's not consistent.

This time I created a local chain, worked with it for a few days, then on Friday I just closed the terminal window with geth. On Monday when I start `geth` process again, the database (I had 63 blocks so far) is just wiped out completely. The log says it all:

![chainwipeout](https://user-images.githubusercontent.com/1125368/173465942-4e3f37f2-c24a-4246-960a-66793f65b57a.png)

After it wipes out all existing blocks, it just starts making new blocks from genesis (block 0) , like nothing happened.

**Comment by karalabe** [comment]
1. Drop the passive aggressive attitude if you want answers.
2. It works as expected, Geth keeps the recent state in memory for pruning purposes. If you crash Geth (i.e. kill the terminal and not shut it down gracefully), then Geth will lose the state data kept in memory and will need to roll the local chain back to a block which had the state (i.e. a proper shutdown).
