### ISSUE TITLE
mixhash not returned in the rpc

### ISSUE THREAD

**Issue by wanderer** [ethereum/go-ethereum#2508]
The mix hash is currently not returned in blocks in the RPC

**Comment by kumavis** [comment]
this is the only apart of the blockchain not available via RPC

**Comment by obscuren** [comment]
Yes, that's correct. The [RPC spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash) doesn't define the mix hash to be included in the response.

I'm unsure of this issue and what your intentions are (we do have that template - that you deleted - for a reason, you know :-p). Are you looking to change the RPC spec, did you think we implemented it incorrectly or submit a feature request? :-)

**Comment by wanderer** [comment]
>  Are you looking to change the RPC spec,  did you think we implemented it incorrectly or submit a feature request? :-)

Either works! Just as long as there is some way to get the mixhash :)

**Comment by fjl** [comment]
I need this too.

**Comment by fjl** [comment]
This has landed on develop.

**Comment by wanderer** [comment]
yay thanks @fjl

**Comment by fjl** [comment]
All the details are here: https://github.com/ethereum/go-ethereum/pull/2930/commits/b0d9f7372a04fa8f0ffc391f0997e2e062d465ef

You should now be able to reconstruct all consensus-related objects from RPC output values.

**Comment by kumavis** [comment]
good to close

**Comment by kumavis** [comment]
@fjl I think this can be closed now 👍

**Comment by fjl** [comment]
We will close it when geth 1.5 is released. The change is not in any release yet.

**Comment by kumavis** [comment]
oh woah! should be a pretty big changelog then : )
keep up the good work

**Comment by fjl** [comment]
Fix released in 1.5.0.

**Comment by kumavis** [comment]
yeeehaw!
