### ISSUE TITLE
is that right or wrong

### ISSUE THREAD

**Issue by Wolfiraq** [ethereum/go-ethereum#25093]
pls,, any one can tell me is it normaly showing like this ,,,

-----------------------------
INFO [06-14|20:23:39.568] Imported new chain segment               blocks=1     txs=309       mgas=29.928  elapsed=234.681ms    mgasps=127.527 number=14,963,642 hash=75f61e..416e60 dirty=1022.93MiB
INFO [06-14|20:23:39.570] Unindexed transactions                   blocks=1     txs=172       tail=12,613,643 elapsed=1.968ms
INFO [06-14|20:23:52.056] Imported new chain segment               blocks=1     txs=163       mgas=13.604  elapsed=163.495ms    mgasps=83.208  number=14,963,643 hash=5f5aef..648556 dirty=1020.55MiB
INFO [06-14|20:23:52.059] Unindexed transactions                   blocks=1     txs=228       tail=12,613,644 elapsed=2.623ms
INFO [06-14|20:24:37.527] Imported new chain segment               blocks=1     txs=370       mgas=29.854  elapsed=225.345ms    mgasps=132.483 number=14,963,644 hash=bc8ec6..e43bc7 dirty=1021.77MiB
INFO [06-14|20:24:37.530] Unindexed transactions                   blocks=1     txs=261       tail=12,613,645 elapsed=2.674ms
INFO [06-14|20:24:38.557] Deep froze chain segment                 blocks=3     elapsed=20.643ms     number=14,873,644 hash=fe287d..1d7e11
INFO [06-14|20:24:51.804] Imported new chain segment               blocks=1     txs=126       mgas=10.226  elapsed=94.003ms     mgasps=108.782 number=14,963,645 hash=601ecf..1049c3 dirty=1021.58MiB
INFO [06-14|20:24:51.806] Unindexed transactions                   blocks=1     txs=190       tail=12,613,646 elapsed=2.029ms
INFO [06-14|20:24:53.264] Imported new chain segment               blocks=1     txs=21        mgas=2.544   elapsed=46.292ms     mgasps=54.951  number=14,963,646 hash=bdf8f9..f38c3e dirty=1021.00MiB
INFO [06-14|20:24:53.268] Unindexed transactions                   blocks=1     txs=263       tail=12,613,647 elapsed=3.155ms
INFO [06-14|20:24:57.931] Imported new chain segment               blocks=1     txs=30        mgas=4.134   elapsed=59.160ms     mgasps=69.883  number=14,963,647 hash=d65287..3dc717 dirty=1020.04MiB
INFO [06-14|20:24:57.934] Unindexed transactions                   blocks=1     txs=239       tail=12,613,648 elapsed=2.919ms
INFO [06-14|20:24:58.954] Imported new chain segment               blocks=1     txs=97        mgas=6.550   elapsed=81.853ms     mgasps=80.024  number=14,963,648 hash=3a98dd..f55749 dirty=1018.72MiB
INFO [06-14|20:24:58.956] Unindexed transactions                   blocks=1     txs=166       tail=12,613,649 elapsed=1.858ms
INFO [06-14|20:25:02.469] Imported new chain segment               blocks=1     txs=15        mgas=1.002   elapsed=45.255ms     mgasps=22.134  number=14,963,649 hash=e5ff7c..d38554 dirty=1016.57MiB
----------------------------------------
thanx for all 
sys, linx , ubn. 20.4 cpu 6core 32gb ram 1T HD (oracle cloud node )

**Comment by MariusVanDerWijden** [comment]
That looks good to me... What do you think is wrong here?

**Comment by Wolfiraq** [comment]
> INFO [06-14|20:24:38.557] Deep froze chain segment blocks=3 elapsed=20.643ms number=14,873,644 hash=fe287d..1d7e11

thanks for replay ,,, and am see this info many time ,, is this should worry about it ??? thanks again

**Comment by MariusVanDerWijden** [comment]
No nothing to worry about, it just tells you that some old blocks are stored to the "freezer", basically for long-term storage. We can't access them as quickly as the unfreezed blocks
