### ISSUE TITLE
Why Geth choose merkle tree as the underlying structure for storing account state?

### ISSUE THREAD

**Issue by cifer76** [ethereum/go-ethereum#25092]
Hi I'm learning geth source code these days and a question keep lingering in my head: why geth use the merkle patricia tree as the underlying data structure for storing account state? As I known the merkle patricia tree is derived from merkle tree used in bitcoin to do efficient verification of a transaction against a block.

While in geth, there's no such verification need for the account state right? At least no need to persisting also the intermediate node right? So why did we choose to use it as well? as a tree-like structure occupies much more disk space than a plain db structure, and entails more disk I/Os to get the leaf node, which furthur caused the slow syncing process.

Maybe it's somewhat fundamental I didn't find much discussions on this topic in the community, I think a plain data structure is just for good, but may I know the initial consideration of the geth design and if I'm missing some important points?

**Comment by AusIV** [comment]
Geth does do verification of the account state trie. Every block includes the state root, and Geth verifies that its state root matches the state root of each block header after processing the transactions in it. Without storing the state trie, Geth would not be able to mine blocks, as it would not be able to determine the new state root after including transactions.

Additionally, light clients request state data from peers, and the responses include proofs of the data they've requested, which is only possible with the state trie.

**Comment by cifer76** [comment]
I see, thanks a lot
