### ISSUE TITLE
Big hashes in BlockHashes can fill process memory

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#251]
Block hashes have no size limit. Check hash size and kick of bad peers.

@zelig Do we currently have anything against random  hashes? (e.g., malicious peer continuously sending unknown hashes)

**Comment by fjl** [comment]
You can use an array type for hashes. The rlp decoder will reject inputs that do not fit into the array and return an appropriate error message.

```go
type message struct{
        ...
        Hash [32]byte
}
```

**Comment by obscuren** [comment]
Indeed. Second question still valid.

**Comment by zelig** [comment]
yes we do . ish . if a section of hashes 
- do not get all blocks from peers OR
- do not get a continuation (further parent hashes toward the known blockchain)
then after a fix time the chain is killed.  
I will make sure the peer supplying that section is expelled.

**Comment by zelig** [comment]
This is taken care of by conversion to common.Hash and by other measures
