### ISSUE TITLE
What is the purpose of fsMinFullBlocks?

### ISSUE THREAD

**Issue by piersy** [ethereum/go-ethereum#25100]
Technically this constant ensures that fast and snap sync nodes will have fully synced at least the last 64 blocks at the point at which a node considers itself synced, but why enforce this and why select 64 blocks as opposed to any other number?

https://github.com/ethereum/go-ethereum/blob/a907d7e81aaeea15d80b2d3209ad8e08e3bf49e0/eth/downloader/downloader.go#L59

**Comment by karalabe** [comment]
The reason was to pile enough PoW on top of a synced block so as to make it incredibly expensive for anyone to create a side chain that cannot be reorged out after sync.

**Comment by piersy** [comment]
Thanks @karalabe!
