### ISSUE TITLE
Enable parsing the return values of a contract method (similar to abi.ParseSelector)

### ISSUE THREAD

**Issue by teghnet** [ethereum/go-ethereum#25115]
# Rationale

The `abi.ParseSelector` function creates a valid JSON encoded ABI for selector calculation, but we could go one step further and enable creating a proper ABI for `abi.ABI.Unpack` method.

This would address most cases where we want to quickly call a single method on a contract.

`abi.ParseSignature("balanceOf(address)(uint256)")`

# Implementation

We could (1) simply export 
```golang
abi.parseIdentifier
abi.parseCompositeType
abi.assembleArgs
```
for external use.

or we might (2) add a `abi.ParseSignature` function that will have this extended logic

or we could just expand on the functionality of the existing `abi.ParseSelector` function in a backward compatible manner.

I am very much ready to implement any of those solutions.

**Comment by fjl** [comment]
We don't really want to add this in go-ethereum. A full function signature parser would be a lot of code, and might not always match the full Solidity feature set.

If you want this feature, and you are willing to implement it, I think it could be a good candidate for a stand-alone Go package. 'selector string' to 'ABI definition' transformation can be implemented without the rest of package abi. We could even put a reference to this package in the docs of our package abi.

**Comment by teghnet** [comment]
@fjl What I want to avoid is having to watch for changes in this parsing functions and update them in any external libs.

Is exporting 
```go
abi.parseIdentifier
abi.parseCompositeType
abi.assembleArgs
``` out of the question?
