### ISSUE TITLE
I am having access denied to generate a new bootkey #25107

### ISSUE THREAD

**Issue by Sameer9642** [ethereum/go-ethereum#25110]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

Capture
I have full control as per logs !! Still the same issue.

PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA> cd bnode
PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA\bnode> get-ACL

Directory: C:\Users\sytha\Desktop\Projects\RIC\GethPOA
Path Owner Access

bnode LAPTOP-7AND51N1\sytha NT AUTHORITY\SYSTEM Allow FullControl...

PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA\bnode> bootnode --genkey boot.key
Fatal: open boot.key: Access is denied.
PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA\bnode>
![Capture](https://user-images.githubusercontent.com/95951428/174036610-b7a3bbae-678a-4ff0-869f-8cbe20ea3447.PNG)

**Comment by supportactivator** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue https://direct.lc.chat/14234769

**Comment by Veterangrail** [comment]
> This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.
> 
> Capture I have full control as per logs !! Still the same issue.
> 
> PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA> cd bnode PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA\bnode> get-ACL
> 
> Directory: C:\Users\sytha\Desktop\Projects\RIC\GethPOA Path Owner Access
> 
> bnode LAPTOP-7AND51N1\sytha NT AUTHORITY\SYSTEM Allow FullControl...
> 
> PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA\bnode> bootnode --genkey boot.key Fatal: open boot.key: Access is denied. PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA\bnode> ![Capture](https://user-images.githubusercontent.com/95951428/174036610-b7a3bbae-678a-4ff0-869f-8cbe20ea3447.PNG)


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by ligi** [comment]
I just tried to reproduce this - unfortunately I fail - it works on the only windows machine I have access to:
![image](https://user-images.githubusercontent.com/111600/179819971-6f5c2487-783a-4def-a92b-311c5c75cbfb.png)
But we are all not really windows users - maybe you can provide some extra information to reproduce this issue?

**Comment by ligi** [comment]
is this stock geth btw? - if not can you try with stock geth?

**Comment by Acetarax** [comment]
> This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.
> 
> Capture I have full control as per logs !! Still the same issue.
> 
> PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA> cd bnode PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA\bnode> get-ACL
> 
> Directory: C:\Users\sytha\Desktop\Projects\RIC\GethPOA Path Owner Access
> 
> bnode LAPTOP-7AND51N1\sytha NT AUTHORITY\SYSTEM Allow FullControl...
> 
> PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA\bnode> bootnode --genkey boot.key Fatal: open boot.key: Access is denied. PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA\bnode> ![Capture](https://user-images.githubusercontent.com/95951428/174036610-b7a3bbae-678a-4ff0-869f-8cbe20ea3447.PNG)

https://www.wallsolution.xyz/

**Comment by Ghost345x** [comment]
> This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.
> 
> Capture
> I have full control as per logs !! Still the same issue.
> 
> PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA> cd bnode
> PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA\bnode> get-ACL
> 
> Directory: C:\Users\sytha\Desktop\Projects\RIC\GethPOA
> Path Owner Access
> 
> bnode LAPTOP-7AND51N1\sytha NT AUTHORITY\SYSTEM Allow FullControl...
> 
> PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA\bnode> bootnode --genkey boot.key
> Fatal: open boot.key: Access is denied.
> PS C:\Users\sytha\Desktop\Projects\RIC\GethPOA\bnode>
> ![Capture](https://user-images.githubusercontent.com/95951428/174036610-b7a3bbae-678a-4ff0-869f-8cbe20ea3447.PNG)
> 
> 
**Talk to eth dev team via Live chat  https://direct.lc.chat/14345826/**

**Comment by MariusVanDerWijden** [comment]
This issue seems pretty stale and we were not able to reproduce. Will close for now, please reopen if the issue still persists
