### ISSUE TITLE
Local chain is post-merge, waiting for beacon client sync switch-over...

### ISSUE THREAD

**Issue by Duanraudon** [ethereum/go-ethereum#25118]
I tried to start a ropsten node using the latest ethereum/client-go image. Why does the log keep reporting the following error?

![image](https://user-images.githubusercontent.com/34836995/174272178-cf1a1bae-2b40-4644-bf8b-d18e6202dbe1.png)

start command：
geth --syncmode "snap" --ropsten --datadir /opt/data --cache 4096 --identity "ddblock" --override.terminaltotaldifficulty 50000000000000000 --ws --ws.port 8545 --ws.api eth,net,web3 --ws.origins "*" --ws.addr 0.0.0.0 --http --http.api "eth,net,web3" --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.vhosts "*"

**Comment by Zachinquarantine** [comment]
In order to run a node on Proof-of-Stake networks such as Ropsten, you need to run a [Consensus](https://ethereum.org/en/developers/docs/nodes-and-clients/#consensus-clients) [client](https://ethereum.org/en/upgrades/get-involved/#clients) alongside your Geth node.

**Comment by peggy001** [comment]
the same problem of [geth].mine instruction is 
./geth.exe --datadir ~/.ropsten --ropsten --override.terminaltotaldifficulty 50000000000000000 --http --http.api "eth,debug,personal,net,web3" --http.vhosts="*" --http.corsdomain "*" --ws --ws.api "eth,web3,net"--authrpc.addr localhost --authrpc.port 8551 --authrpc.vhosts localhost 2>output.log

the other geth problem is it prints out chain not synced beyond EIP-155 reply-protection fork block. is this normal?

so i'm running [prysm] by:
./prysm.bat beacon-chain --genesis-state=C:\prysm213\merge-testnets\ropsten-beacon-chain\genesis.ssz --chain-config-file=C:\prysm213\merge-testnets\ropsten-beacon-chain\config.yaml --datadir eth2data --suggested-fee-recipient=0x67CDB8344FFCa7aaaeda9e7a4F4f1A9cb4D1FC64 --http-web3provider=http://localhost:8551 --bootstrap-node=enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk --jwt-secret=jwtsecret
(the jwtsecret is created by geth)
it prints out "error powchain :could not connect to execution client endpoint:could not make initial request to verify execution chain ID:chain not synced beyond EIP-155 reply-protection fork block"
even add --chain-id 3 ,it still doesnt work.

**Comment by peggy001** [comment]
> In order to run a node on Proof-of-Stake networks such as Ropsten, you need to run a [Consensus](https://ethereum.org/en/developers/docs/nodes-and-clients/#consensus-clients) [client](https://ethereum.org/en/upgrades/get-involved/#clients) alongside your Geth node.
the same problem of [geth].mine instruction is
./geth.exe --datadir ~/.ropsten --ropsten --override.terminaltotaldifficulty 50000000000000000 --http --http.api "eth,debug,personal,net,web3" --http.vhosts="" --http.corsdomain "" --ws --ws.api "eth,web3,net"--authrpc.addr localhost --authrpc.port 8551 --authrpc.vhosts localhost 2>output.log

the other geth problem is it prints out chain not synced beyond EIP-155 reply-protection fork block. is this normal?

so i'm running [prysm] by:
./prysm.bat beacon-chain --genesis-state=C:\prysm213\merge-testnets\ropsten-beacon-chain\genesis.ssz --chain-config-file=C:\prysm213\merge-testnets\ropsten-beacon-chain\config.yaml --datadir eth2data --suggested-fee-recipient=0x67CDB8344FFCa7aaaeda9e7a4F4f1A9cb4D1FC64 --http-web3provider=http://localhost:8551/ --bootstrap-node=enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk --jwt-secret=jwtsecret
(the jwtsecret is created by geth)
it prints out "error powchain :could not connect to execution client endpoint:could not make initial request to verify execution chain ID:chain not synced beyond EIP-155 reply-protection fork block"
even add --chain-id 3 ,it still doesnt work.

**Comment by Duanraudon** [comment]
Did you solve this problem please? If you solve it, please answer me.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ethereum/go-ethereum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月18日(星期六) 下午2:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ethereum/go-ethereum] Local chain is post-merge, waiting for beacon client sync switch-over... (Issue #25118)





  
In order to run a node on Proof-of-Stake networks such as Ropsten, you need to run a Consensus client alongside your Geth node.
 the same problem of [geth].mine instruction is
 ./geth.exe --datadir ~/.ropsten --ropsten --override.terminaltotaldifficulty 50000000000000000 --http --http.api "eth,debug,personal,net,web3" --http.vhosts="" --http.corsdomain "" --ws --ws.api "eth,web3,net"--authrpc.addr localhost --authrpc.port 8551 --authrpc.vhosts localhost 2&gt;output.log
  
the other geth problem is it prints out chain not synced beyond EIP-155 reply-protection fork block. is this normal?
 
so i'm running [prysm] by:
 ./prysm.bat beacon-chain --genesis-state=C:\prysm213\merge-testnets\ropsten-beacon-chain\genesis.ssz --chain-config-file=C:\prysm213\merge-testnets\ropsten-beacon-chain\config.yaml --datadir eth2data --suggested-fee-recipient=0x67CDB8344FFCa7aaaeda9e7a4F4f1A9cb4D1FC64 --http-web3provider=http://localhost:8551/ --bootstrap-node=enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk --jwt-secret=jwtsecret
 (the jwtsecret is created by geth)
 it prints out "error powchain :could not connect to execution client endpoint:could not make initial request to verify execution chain ID:chain not synced beyond EIP-155 reply-protection fork block"
 even add --chain-id 3 ,it still doesnt work.

**Comment by xhyumiracle** [comment]
@Duanraudon, follow the link @Zachinquarantine shared above should help solve this issue.
or, find practical instructions here: https://notes.ethereum.org/@launchpad/ropsten
or [here](https://github.com/xhyumiracle/eth2launch), a docker-compose file I just wrote for `sepolia` full node at post-merge stage. Although it's not for ropsten, you got the basic idea.

**Comment by PBnJELLEY** [comment]
> In order to run a node on Proof-of-Stake networks such as Ropsten, you need to run a [Consensus](https://ethereum.org/en/developers/docs/nodes-and-clients/#consensus-clients) [client](https://ethereum.org/en/upgrades/get-involved/#clients) alongside your Geth node.

I'm running with rocketpool and I have s

**Comment by PBnJELLEY** [comment]
> In order to run a node on Proof-of-Stake networks such as Ropsten, you need to run a [Consensus](https://ethereum.org/en/developers/docs/nodes-and-clients/#consensus-clients) [client](https://ethereum.org/en/upgrades/get-involved/#clients) alongside your Geth node.

I'm running my node with rockrtpool and I have a consensus client but I'm still getting the same error as above. Any suggestions?
