### ISSUE TITLE
Empfehlen Sie Ihren Freunden sich Pi Network anzuschließen

### ISSUE THREAD

**Issue by Mars7005** [ethereum/go-ethereum#25147]
Pi ist eine neue digitale Währung mit über 33 Millionen Mitglieder weltweit, die von Stanford-Absolventen entwickelt wurde. Um Ihre Pi zu beanspruchen, folgen Sie diesem Link https://minepi.com/4Fredoom und verwenden Sie meinen Benutzernamen (4Fredoom) als Einladungscode.

**Comment by MariusVanDerWijden** [comment]
Danke nein
