### ISSUE TITLE
Cannot enable authrpc on Sepolia

### ISSUE THREAD

**Issue by masayil** [ethereum/go-ethereum#25145]
command: `/root/geth --nousb --maxpeers 50 --cache=32000 --syncmode=full --datadir "/root/svc" --http.vhosts "*" --http --http.addr "0.0.0.0" --http.port "8115" --http.corsdomain "*" --ws --ws.addr "0.0.0.0" --ws.port "8116" --ws.origins "*" --http.api "eth,net,web3" --ws.api "eth,net,web3" --sepolia --graphql --graphql.vhosts "*" --graphql.corsdomain "*" --rpc.txfeecap 0 --port 32220 --txlookuplimit 0 --authrpc.addr 10.30.0.67 --authrpc.port 8551 --authrpc.vhosts "*" --authrpc.jwtsecret "/root/svc/jwtsecret"`

![image](https://user-images.githubusercontent.com/65291464/174937608-3527e8e8-6088-475d-96fc-53ac4b17c7a9.png)

**Comment by karalabe** [comment]
Sepollia is not yet configured for the merge. At least currently, opening the `authrpc` is only allowed if the network has a terminal total difficulty set. If you want to test with the current releases, you can fake a huge TTD via `--override.terminaltotaldifficulty`.

For the next release, we might want to consider exposing it if explicitly requested.

**Comment by karalabe** [comment]
Probably we'll always expose it from some release onward.
