### ISSUE TITLE
eth_getLogs return empty

### ISSUE THREAD

**Issue by simpleway2016** [ethereum/go-ethereum#25144]
#### System information

Geth version: 1.10.20-unstable
OS & Version: Linux
Commit hash : 01e5e9c2c3fa1cf7a9747148dca22d59ff9839b6

#### Expected behaviour
Several of my erc20 tranactions have been confirmed, eth_getLogs should return transaction log information

#### Actual behaviour
eth_getLogs returns :
`{"jsonrpc":"2.0","id":2,"result":[]}`

#### Steps to reproduce the behaviour
startup:
geth --http --http.port "18545" --http.api personal,db,eth,net,web3,admin --http.addr=0.0.0.0 --datadir ../eth-test/data --allow-insecure-unlock --port "30303" --mine --miner.threads=1 --networkid 7878

Request:
`{"id":2,"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock":"0x1","toBlock":"0x383","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]}]}`

**Comment by rjl493456442** [comment]
Are you sure the topic provided in the RPC call matches with your event? Or are you sure that you have logs fall in this chain range? There is no enough information for us to debug your issue.

**Comment by simpleway2016** [comment]
Maybe there is something wrong with the configuration. After deleting the data folder and reconfiguring the private node, it works normally
