### ISSUE TITLE
Docs: broken link in  go-ethereum/docs/_interface/mining.md  : FAQ-->faq

### ISSUE THREAD

**Issue by wyonghao** [ethereum/go-ethereum#25153]
In this page:
https://geth.ethereum.org/docs/interface/mining
Text "You’ll see something like the example output below – it’s a two stage process as described in much more detail in our [FAQ](https://geth.ethereum.org/docs/FAQ). " results in "Page not found!
It shall use lower case link below:
https://geth.ethereum.org/docs/faq
The server handles it is case sensitive.

**Comment by s1na** [comment]
Thanks for reporting. This page is being re-written as part of https://github.com/ethereum/go-ethereum/pull/25035 and the link you mentioned is removed.

**Comment by Veterangrail** [comment]
> In this page: https://geth.ethereum.org/docs/interface/mining Text "You’ll see something like the example output below – it’s a two stage process as described in much more detail in our [FAQ](https://geth.ethereum.org/docs/FAQ). " results in "Page not found! It shall use lower case link below: https://geth.ethereum.org/docs/faq The server handles it is case sensitive.


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by Veterangrail** [comment]
> In this page: https://geth.ethereum.org/docs/interface/mining Text "You’ll see something like the example output below – it’s a two stage process as described in much more detail in our [FAQ](https://geth.ethereum.org/docs/FAQ). " results in "Page not found! It shall use lower case link below: https://geth.ethereum.org/docs/faq The server handles it is case sensitive.


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by MariusVanDerWijden** [comment]
closing because fixed
