### ISSUE TITLE
Where can we find a list of java console commands with their usage explained?

### ISSUE THREAD

**Issue by tamaszl** [ethereum/go-ethereum#25160]
https://geth.ethereum.org/docs/interface/javascript-console
Seems like a popular request which nobody has a clue where to find the information from officially. All i could find was a stackexchange post
https://ethereum.stackexchange.com/questions/28703/full-list-of-geth-terminal-commands

**Comment by karalabe** [comment]
@lightclient is currently working on standardizing the `debug` namespace (and maybe some chain management namespace) and @s1na the `trace` namespace. That should help us move a step forward. We also want to gradually remove the `personal` one. This overall should get us to a fairly standardized place where most things are documented. I know this doesn't really help you now, but at least there's work being done :)

The best way it to start a Geth console and see what's available via pressing `tab` for namespavce completion and then method completion.
