### ISSUE TITLE
Geth error with Knoxjonesi (1.4.1) on submitting block

### ISSUE THREAD

**Issue by d57heinz** [ethereum/go-ethereum#2516]
#### System information

Geth version: `geth version`  
OS & Version: Windows/Linux/OSX    windows 10 64 
Commit hash : (if `develop`)

#### Expected behaviour
locked up on a submit block.  Proxy shows block was submittted and accepted .I wasnt watching when this happened but the block was submitted an hour ago and i feel thats when it crashed.

#### Actual behaviour

http://imgur.com/kPOpcY6

Now when i re open geth this is what it keeps spitting out

#### Steps to reproduce the behaviour
unknown 

#### Backtrace

````
[backtrace]
````

Best Regards
d57heinz
Doug

**Comment by d57heinz** [comment]
looking at the block chain it wasnt recognized at all.

**Comment by d57heinz** [comment]
seems by looking at the file it was created over 12 hours ago.  I saved it and deleted all the files after it including this file  the .ldb  will see if this corrects it and will keep an eye out.

**Comment by fjl** [comment]
The error indicates a corrupted database. Please resync.
