### ISSUE TITLE
Import IBFT 2.0 and QBFT consensus implementations from Quorum project

### ISSUE THREAD

**Issue by thorstenhirsch** [ethereum/go-ethereum#25178]
This request is relevant for private/consortium networks only.

# Rationale
The Quorum project has written IBFT 2.0 and QBFT implementations for geth, but so far I couldn't find a PR to merge that code upstream in the official geth. Are there any reservations against such a PR?

What are the use-cases?
DAML (daml.com) requires a consensus algorithm with immediate finality (e.g. IBFT 2.0 and QBFT). AFAIK only Hyperledger Besu's implementations are officially supported. However there's also an implementation for geth, which has been developed by the Quorum project. I don't know if Quorum is interested in DAML support, but I think it should be done upstream anyway to keep the differences between Quorum's geth and the official geth as small as possible.

# Implementation
https://github.com/ConsenSys/quorum/tree/master/consensus/istanbul

**Comment by lightclient** [comment]
I think this quote sums up the team's stance on supporting features for private networks atm:

> We don't have the capacity - nor willingness - to maintain code for non-Ethereum networks. - https://github.com/ethereum/go-ethereum/pull/24982#issuecomment-1139750000
