### ISSUE TITLE
Cannot synchronize ropsten v1.10.19

### ISSUE THREAD

**Issue by EWIT521** [ethereum/go-ethereum#25171]
#### System information

Geth version: `geth version`:v1.10.19
OS & Version: Linux
Commit hash : (if `develop`)

The version of :v1.10.19 with --ropsten  annot synchronize.

Here is the log：
INFO [06-25|07:53:49.963] Legacy sync reached merge threshold      number=12,350,713 hash=4e8451..5809f6 td=50,001,647,293,494,169 ttd=50,000,000,000,000,000
INFO [06-25|07:53:49.963] State sync in progress                   synced=62.64% state=42.19GiB accounts=26,344,188@5.66GiB slots=136,540,601@28.33GiB codes=1,575,742@8.21GiB eta=5m15.003s
INFO [06-25|07:53:49.964] Mining aborted due to sync
WARN [06-25|07:53:50.142] Unexpected bytecode packet               peer=b0445182 reqid=1,777,362,369,318,002,307
WARN [06-25|07:53:50.327] Unexpected account range packet          peer=b0445182 reqid=556,682,285,356,955,324
WARN [06-25|07:53:50.704] Unexpected account range packet          peer=139fa632 reqid=9,202,435,741,231,159,585
WARN [06-25|07:53:50.761] Unexpected bytecode packet               peer=139fa632 reqid=6,393,095,125,100,037,671
INFO [06-25|07:53:56.459] Disabling direct-ancient mode            origin=12,350,516 ancient=11,370,495
INFO [06-25|07:53:57.553] Imported new block headers               count=0   elapsed=9.379ms     number=12,350,712 hash=d3a581..1b1f0c age=2w2d15h  ignored=196
INFO [06-25|07:53:57.553] Legacy sync reached merge threshold      number=12,350,713 hash=4e8451..5809f6 td=50,001,647,293,494,169 ttd=50,000,000,000,000,000
INFO [06-25|07:53:57.553] State sync in progress                   synced=62.64% state=42.19GiB accounts=26,353,876@5.66GiB slots=136,540,601@28.33GiB codes=1,575,743@8.21GiB eta=5m7.414s
WARN [06-25|07:53:57.553] Local chain is post-merge, waiting for beacon client sync switch-over...
INFO [06-25|07:53:57.553] Mining aborted due to sync
INFO [06-25|07:53:57.553] Commit new sealing work                  number=1          sealhash=23f4ba..5975ff uncles=0 txs=0 gas=0 fees=0 elapsed="263.845µs"
WARN [06-25|07:53:57.567] Unexpected account range packet          peer=b0445182 reqid=8,998,325,401,379,634,607
WARN [06-25|07:53:57.567] Unexpected bytecode packet               peer=b0445182 reqid=2,591,547,784,263,352,395
WARN [06-25|07:53:57.583] Unexpected account range packet          peer=139fa632 reqid=4,405,550,200,340,081,909
WARN [06-25|07:53:57.862] Unexpected bytecode packet               peer=139fa632 reqid=2,325,098,990,163,256,066
INFO [06-25|07:54:04.043] Disabling direct-ancient mode            origin=12,350,516 ancient=11,370,495
INFO [06-25|07:54:05.141] Imported new block headers               count=0   elapsed=9.217ms     number=12,350,712 hash=d3a581..1b1f0c age=2w2d15h  ignored=196
INFO [06-25|07:54:05.141] Legacy sync reached merge threshold      number=12,350,713 hash=4e8451..5809f6 td=50,001,647,293,494,169 ttd=50,000,000,000,000,000
INFO [06-25|07:54:05.141] State sync in progress                   synced=62.64% state=42.19GiB accounts=26,356,031@5.66GiB slots=136,540,601@28.33GiB codes=1,575,743@8.21GiB eta=6m12.147s
WARN [06-25|07:54:05.141] Unexpected bytecode packet               peer=139fa632 reqid=1,021,589,096,845,415,262
INFO [06-25|07:54:05.141] Mining aborted due to sync
WARN [06-25|07:54:05.220] Unexpected account range packet          peer=b0445182 reqid=7,493,833,964,840,851,094
WARN [06-25|07:54:05.225] Unexpected bytecode packet               peer=b0445182 reqid=2,650,242,459,087,875,201
WARN [06-25|07:54:05.261] Unexpected account range packet          peer=139fa632 reqid=7,245,144,037,588,966,723
INFO [06-25|07:54:11.631] Disabling direct-ancient mode            origin=12,350,516 ancient=11,370,495
INFO [06-25|07:54:12.712] Imported new block headers               count=0   elapsed=9.609ms     number=12,350,712 hash=d3a581..1b1f0c age=2w2d15h  ignored=196

**Comment by karalabe** [comment]
`WARN [06-25|07:53:57.553] Local chain is post-merge, waiting for beacon client sync switch-over...`

Ropsten was merged together with it's beacon client. You need to run a beacon client sode-by-side from now on. https://blog.ethereum.org/2022/05/30/ropsten-merge-announcement/
