### ISSUE TITLE
Head state missing, repairing. How long does it take to repair on Raspberry Pi 4b

### ISSUE THREAD

**Issue by L-F-Escobar** [ethereum/go-ethereum#25184]
I accidentally unplugged my RPI 4b. Geth did not shut down properly. How long does it take to recover head state? Its been at it for about 30 minute. 

```
pi@raspberrypi:~ $ geth version
Geth
Version: 1.10.18-stable
Git Commit: de23cf910b814867d5c5d1ad6164835d79069638
Git Commit Date: 20220525
Architecture: arm64
Go Version: go1.18.1
Operating System: linux
GOPATH=/usr/local/go/bin
GOROOT=go
```

```
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
pi@raspberrypi:~ $ free -g
               total        used        free      shared  buff/cache   available
Mem:               7           2           0           0           5           5
Swap:             11           0          11
```

```
pi@raspberrypi:~ $ cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2835
Revision	: d03114
Serial		: 10000000799fd0da
Model		: Raspberry Pi 4 Model B Rev 1.4
```

![Screen Shot 2022-06-27 at 12 24 41 PM](https://user-images.githubusercontent.com/26371796/176020011-3423b5dc-d708-426b-bea8-500ea884fe60.png)

**Comment by rjl493456442** [comment]
It's pretty weird though. Your node stops at 7.9M, 3 years ago. Are you running full sync before? In this case an older existing state should be found easily.

**Comment by L-F-Escobar** [comment]
What is weird about that? That is where the node was before the RPI was unplugged. This is a full sync. Its been over an entire day now and its still "repairing"

**Comment by iKoala** [comment]
I have been maintaining Geth nodes for my company projects for over 2 years, "Head state missing" status can run over days or even weeks. It always happen when you restart nodes with ancient chain data. I suggest you to download the latest client and sync from scratch is a much better option. For your reference, I sync'ed a new node with Geth v1.10.19 client on AWS t3.xlarge EC2 instance within 12 hours two days ago.

**Comment by rjl493456442** [comment]
@L-F-Escobar What's the command for your previous run? 

The mechanism of repairing is: Geth will try to find an available state in disk and rewind the chain to that point in case the corresponding state of head block is missing. 
If you were running full sync `--syncmode full` previously, the older state in disk should be found pretty easily after a few minutes.

**Comment by karalabe** [comment]
@rjl493456442 Alternatively, it can also happen that he pruned his chain data some point in the past with `snapshot prune`. Either  way, if you rewound back to block 7M with no state present at all, you'll probably wind back to genesis and will try to do a full sync (gonna take weeks). At this point just resync with snap sync from scratch.

**Comment by L-F-Escobar** [comment]
@rjl493456442 I am running full sync mode. I am using geth as a service, here is my service file

```
## Geth Mainnet service file
[Unit]
Description=Geth Mainnet Node
After=network.target auditd.service
Wants=network.target

[Service]
WorkingDirectory=/home/pi/ethereum/data/mainnet
ExecStart=sudo /usr/local/bin/geth/geth --syncmode full --ethash.dagdir /home/pi/ethereum/data/mainnet/.ethash --datadir /home/pi/ethereum/data/mainnet/chaindata --datadir.ancient /home/pi/ethereum/data/mainnet/chaindata/ancient --ipcpath /home/pi/ethereum/data/mainnet/.eth/geth.ipc --verbosity 3 --trace /home/pi/ethereum/data/mainnet/.trace --port 30303 --metrics --mainnet
User=pi
Group=pi
Restart=always
RestartSec=15s

[Install]
WantedBy=multi-user.target
Alias=gethmainnet.service
```

@karalabe I did not prune the chainstate. Hail to the king, thanks for all your work good ser!



Last night the node started syncing again. Thank the gods! My node has been syncing for almost 4 weeks now, never imagined it would take this long. This is the newest model RPI 4b. 
I should point out im booting and running the pi from an SSD not a micro ssd card. I thought that would speed up the sync but its still a very slow painful process, imho at least. 

![Screen Shot 2022-06-29 at 10 51 01 AM](https://user-images.githubusercontent.com/26371796/176503310-3a6f0b87-a4c3-4f77-9af4-a1e80dd12d6e.png)



Thanks y'all for the input! Cheers!

**Comment by karalabe** [comment]
Based on your SS, it pretty much rolled back to genesis. Sycning from there will take forever. Just nuke it and snap sync from zero.

**Comment by L-F-Escobar** [comment]
So the node never started syncing again. Scrapping the whole thing till my multi thousand dollar hardware arrives in the mail.

Genuine question, what happens if the power goes out at my house?? Geth has to be fully synced again lol ??... 

I can see how bitcoin maximalist are born. Bitcoin is the only full node which can be synced on every day consumer hardware like the newest raspberry pi 4b. 

When you make Jameson Lopp look like a genius there is something wrong with your decentralization, leaving his tweet for posterity

https://twitter.com/lopp/status/911579827999735808

**Comment by L-F-Escobar** [comment]
How do I nuke this damn node doing as little dmg as possible? 



```
geth db removedb

```



?????

**Comment by L-F-Escobar** [comment]
Watch me destroy weeks of computational work

<img width="1440" alt="Screen Shot 2022-07-13 at 9 30 11 PM" src="https://user-images.githubusercontent.com/26371796/178899049-9e3c80ce-e71d-4af9-b28d-3ec8da43ab80.png">

**Comment by L-F-Escobar** [comment]
For all those reading this in the future, hope your node doesnt randomly lose power for w/e reason what so ever

**Comment by iKoala** [comment]
> For all those reading this in the future, hope your node doesnt randomly lose power for w/e reason what so ever

I have been maintaining Geth nodes for over 2 years and I really feel your pain.
All the docs and feedback do not tell how painful and the necessary skills/hardware to maintain long running, highly robust Geth nodes.
My company now maintains 4 Geth nodes with AWS EC2 instance for daily use and also paying 3rd party blockchain SaaS infrastructure as backup service to maintain 7x24 operations.
We also re-sync half of our nodes from scratch on every Geth release in case any problem occurs when we restart and upgrade our nodes. (which always happens 🤷‍♂️)

**Comment by dturner34** [comment]
It would be nice if there was an eta with these long running processes.

**Comment by defeedme** [comment]
you would think that would be a no-brainer! but of course now I'm in that boat it's taking over 40 hours now first time taking this long after a power failure...

**Comment by defeedme** [comment]
> > For all those reading this in the future, hope your node doesnt randomly lose power for w/e reason what so ever
> 
> I have been maintaining Geth nodes for over 2 years and I really feel your pain. All the docs and feedback do not tell how painful and the necessary skills/hardware to maintain long running, highly robust Geth nodes. My company now maintains 4 Geth nodes with AWS EC2 instance for daily use and also paying 3rd party blockchain SaaS infrastructure as backup service to maintain 7x24 operations. We also re-sync half of our nodes from scratch on every Geth release in case any problem occurs when we restart and upgrade our nodes. (which always happens 🤷‍♂️)

yup exactly what happened here - it's still syncing now 40 hours :( running windows geth since genesis - i've had power failure before but longest it ever took was about 6 hours..

**Comment by defeedme** [comment]
> Only 40 hours? haha thats rookie numbers. I always plan for a week of down time if I have to restart, days if I'm lucky. I had to set up multiple failover servers just in case one of them has an issue and I've been fortunate enough to not have to deal with everything failing at the same time yet. I don't understand how anyone can confidently run these things without failover.

I must of been one of the lucky ones lol - i've never been down more than 6 hours - this is very long for me.. I was told maybe I need to update my geth version.. currently running Geth/v1.10.23-stable-d901d853/windows-amd64/go1.18.5
also my get folder is 1tb - is that normal for windows? thanks!
