### ISSUE TITLE
"panic: reflect: call of reflect.Value.Elem on slice Value" in abi.go when calling bound contract method that returns 2 uint8 values

### ISSUE THREAD

**Issue by MethDamon** [ethereum/go-ethereum#2519]
#### System information

Geth version: `1.5.0-unstable`
OS & Version: OS X 10.11.3 (15D21)

#### Expected behaviour

Return two numbers from this contract method from a contract file created with abigen

Contract Method:

```go
// TemperatureRange is a free data retrieval call binding the contract method 0x22aab53a.
//
// Solidity: function temperatureRange() constant returns(uint8, uint8)
func (_TemperatureMeasurementA *TemperatureMeasurementACaller) TemperatureRange(opts *bind.CallOpts) (uint8, uint8, error) {
	var (
		ret0 = new(uint8)
		ret1 = new(uint8)
	)
	out := []interface{}{
		ret0,
		ret1,
	}
	err := _TemperatureMeasurementA.contract.Call(opts, out, "temperatureRange")
	value := reflect.ValueOf(out)
	typ := value.Type()
	fmt.Println(typ)
	return *ret0, *ret1, err
}
```

I call the method through the following session:

```go
	session := &TemperatureMeasurementASession {
		Contract: tmaContract,
		CallOpts: bind.CallOpts{
			Pending: false,
		},
		TransactOpts: bind.TransactOpts{
			From:     auth.From,
			Signer:   auth.Signer,
			GasLimit: big.NewInt(3141592),
		},
	}
```

With this code:

```go
	minTemp, maxTemp, err := session.TemperatureRange()
```

#### Actual behaviour

Panics (See backtrace)

#### Steps to reproduce the behaviour

1. Create a solidity contract with a constant method that returns two uint8 numbers (see method above)

2. Create abi file test.abi with browser solidity

3. Create binary code test.bin with browser solidity

4. Generate a contract binding file with the command:
`abigen --abi test.abi --pkg main --type TestContract --out test.go --bin test.bin`

5. Deploy the contract using go (https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts#deploying-contracts-to-ethereum)

6. Call the method using go

#### Backtrace

````
panic: reflect: call of reflect.Value.Elem on slice Value

goroutine 1 [running]:
panic(0x4489e20, 0xc8302da6a0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
reflect.Value.Elem(0x43cbf00, 0xc8302da560, 0x97, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:735 +0x228
github.com/ethereum/go-ethereum/accounts/abi.ABI.Unpack(0x0, 0x0, 0x0, 0xc8200f9860, 0x4, 0x4, 0x0, 0x0, 0x0, 0xc820296840, ...)
	/Users/tim/Documents/go_workspace/src/github.com/ethereum/go-ethereum/accounts/abi/abi.go:241 +0x18d
github.com/ethereum/go-ethereum/accounts/abi/bind.(*BoundContract).Call(0xc8200ee090, 0xc82029fef0, 0x43cbf00, 0xc8302da560, 0x45d0c40, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tim/Documents/go_workspace/src/github.com/ethereum/go-ethereum/accounts/abi/bind/base.go:108 +0x263
main.(*TemperatureMeasurementACaller).TemperatureRange(0xc8200b3a90, 0xc82029fef0, 0xc8302d6480, 0x0, 0x0)
	/Users/tim/Documents/go_workspace/src/eth_test/TemperatureMeasurementA.go:331 +0x1cd
main.(*TemperatureMeasurementASession).TemperatureRange(0xc82029fee8, 0xc8302d6480, 0x0, 0x0)
	/Users/tim/Documents/go_workspace/src/eth_test/TemperatureMeasurementA.go:342 +0x4a
main.main()
	/Users/tim/Documents/go_workspace/src/eth_test/main.go:128 +0xbf6
exit status 2
````

**Comment by karalabe** [comment]
@obscuren Could you please take a quick look. Perhaps it's easy to fix and we can get it into 1.4.

**Comment by karalabe** [comment]
@MethDamon Seems it was a small misunderstanding in what I thought was possible when writing the generator and what actually was suppoerted by the underlying abi parser :D. We're looking into fixing it now.

In the mean time, if you use named outputs in Solidity (i.e. just assign names for the return values), then Go will parse it into a struct and it will work fine.

**Comment by MethDamon** [comment]
@karalabe 
Nice, thank you very much for your effort!
