### ISSUE TITLE
My sync is lagging 1block behind the real Block.

### ISSUE THREAD

**Issue by Koliji6** [ethereum/go-ethereum#25196]
Hi guys,
I try to create an event listener for some ETH and BSC contracts, so I decided to be faster to create a node, one for ETH and one for BNB Chain, for the BNB chain a got no delay I have the event when the block is minted, but on my ETH node, I have a lot of delay! And I don't know why I would like to get the event of a new block when the block is minted... And I don't know why I received the information at block+1. Please check my screen to compare my "Imported new chain segment" time and the time when the block is mined it's always block+1.
![Untitled](https://user-images.githubusercontent.com/38420652/176430617-ed5bb177-dee4-4828-9be6-d6e509c02b6b.png)

Best regards,

**Comment by karalabe** [comment]
There's not really enough information to make heads or tails of this issue. Based on the logs, blocks are arriving normally without a delay. If you're seeing some delayed announcements, please explain what you're doing or ideally provide a repro that we could try out.

**Comment by Veterangrail** [comment]
> Hi guys, I try to create an event listener for some ETH and BSC contracts, so I decided to be faster to create a node, one for ETH and one for BNB Chain, for the BNB chain a got no delay I have the event when the block is minted, but on my ETH node, I have a lot of delay! And I don't know why I would like to get the event of a new block when the block is minted... And I don't know why I received the information at block+1. Please check my screen to compare my "Imported new chain segment" time and the time when the block is mined it's always block+1. ![Untitled](https://user-images.githubusercontent.com/38420652/176430617-ed5bb177-dee4-4828-9be6-d6e509c02b6b.png)
> 
> Best regards,


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by Acetarax** [comment]
> Hi guys, I try to create an event listener for some ETH and BSC contracts, so I decided to be faster to create a node, one for ETH and one for BNB Chain, for the BNB chain a got no delay I have the event when the block is minted, but on my ETH node, I have a lot of delay! And I don't know why I would like to get the event of a new block when the block is minted... And I don't know why I received the information at block+1. Please check my screen to compare my "Imported new chain segment" time and the time when the block is mined it's always block+1. ![Untitled](https://user-images.githubusercontent.com/38420652/176430617-ed5bb177-dee4-4828-9be6-d6e509c02b6b.png)
> 
> Best regards,

Make use of this https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by Acetarax** [comment]
> Hi guys, I try to create an event listener for some ETH and BSC contracts, so I decided to be faster to create a node, one for ETH and one for BNB Chain, for the BNB chain a got no delay I have the event when the block is minted, but on my ETH node, I have a lot of delay! And I don't know why I would like to get the event of a new block when the block is minted... And I don't know why I received the information at block+1. Please check my screen to compare my "Imported new chain segment" time and the time when the block is mined it's always block+1. ![Untitled](https://user-images.githubusercontent.com/38420652/176430617-ed5bb177-dee4-4828-9be6-d6e509c02b6b.png)
> 
> Best regards,

Make use of this https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by holiman** [comment]
This was tagged with need-more-info 2+ years ago, closing
