### ISSUE TITLE
geth account import flags no longer work

### ISSUE THREAD

**Issue by prestonvanloon** [ethereum/go-ethereum#25209]
#### System information

Geth version: version 1.10.20 @ commit 8f2416a89a3def6ec2c749d5afafbf2c9a18e3c8
OS & Version: linux
Commit hash : 8f2416a89a3def6ec2c749d5afafbf2c9a18e3c8

#### Expected behaviour

It works

#### Actual behaviour

```
Fatal: keyfile must be given as the only argument
exit status 1
```

#### Steps to reproduce the behaviour

```
go run ./cmd/geth account import /tmp/key --datadir=/tmp/eth --keystore=/tmp/keystore --password=/tmp/pass
```

#### Backtrace

````
Fatal: keyfile must be given as the only argument
exit status 1

````

When submitting logs: please submit them as text and not screenshots.

**Comment by prestonvanloon** [comment]
Probably caused by https://github.com/ethereum/go-ethereum/pull/24751

**Comment by fjl** [comment]
We cannot restore the previous behavior, unfortunately. It's a limitation of the cli library.
