### ISSUE TITLE
Demote `Snapshot extension registration failed` to `DEBUG` instead of `WARN`

### ISSUE THREAD

**Issue by Neurone** [ethereum/go-ethereum#25200]
I want to bring this conversation up again.

#24475 Changed the message from `ERROR` to `WARN`. I think this should be demoted to `DEBUG`.
I see many of these _warnings_ in the log, and I ignore them - someone doesn't? - so they are not _warnings_ anymore, just noise.

Because it's something related to other nodes, I cannot do anything about that. Is it correct?
Otherwise, how I should fix, or help to fix, those warnings?

**Comment by Neurone** [comment]
@ligi what do you think about this?

**Comment by karalabe** [comment]
This is caused - I think - by Optimism nodes who renamed the `eth` protocol in their network but not the `snap`. It's an issue that we're hitting these peers and we should fix it so the discovery does not give them back to us. Until then, it's unfortunately an issue in peering, even if harmless.

**Comment by Neurone** [comment]
> This is caused - I think - by Optimism nodes who renamed the `eth` protocol in their network but not the `snap`. It's an issue that we're hitting these peers and we should fix it so the discovery does not give them back to us. Until then, it's unfortunately an issue in peering, even if harmless.

Ok, I see. But if that's just a reminder for developers to address an issue, then it's a bit _too intrusive_ for the geth's common users to have it as a warning, even more, because it's actually harmless and they cannot do anything about that.

**Comment by kayagoban** [comment]
If it's harmless, why is it a Warning?
