### ISSUE TITLE
Reconnect to bootnodes if peer connection is lost

### ISSUE THREAD

**Issue by wbt** [ethereum/go-ethereum#25203]
#### System information

Geth version: 1.9.24-stable
OS & Version: Windows/Linux/OSX: Win10

#### Expected behaviour
When a node has no peers, it should retry the ones specified in the bootnodes parameter at startup.

#### Actual behaviour
When a node has no peers, it stays that way and ignores the fact that bootnodes specified at startup are online and available for reconnection.

#### Steps to reproduce the behaviour
1. Start a node to act as a bootnode on a nonstandard local chain and copy the enode address.
2. With that first node running, in a separate terminal (PowerShell) start another with the --bootnodes parameter as the quoted enode address from the prior step.
3. The second node will connect sync, etc. and act normally as expected. Let this run for a while.
4. Hibernate the machine overnight.
5. Bring the computer out of hibernation.
6. The second node will no longer have any peers/connection to the original bootnode, and will not be able to discover it. 
7. This will continue indefinitely.
8. Use CTRL+C to stop the second node, only.
9. Restart the second node using the exact same command as before.
10. The second node will again connect to the first and do catch-up resync, then stay connected until the next hibernate.

On further reflection, I think this may be a different issue than [#20630](https://github.com/ethereum/go-ethereum/issues/20630#issuecomment-854117596) because it's not about establishing the initial connection to a peer that's just not yet listening.

**Comment by rjl493456442** [comment]
Are you still using `1.9.24-stable`? It's pretty old though

**Comment by karalabe** [comment]
Defaulting connecting back to the bootnodes is not something we want as it's too heard to detect automatically when things don't worok (e.g. not enough peers) and it's too easy to overload the bootnodes.

However, interestingly a hibernation should not really affect your connectivity if a restart helps. That's a more interesting issue, as the bootnodes themselves should get added back to the local discovery table if nothing else is there. I.e. Seems you're hitting a bug.

**Comment by fjl** [comment]
To figure this out, we need the log files of the two nodes.

Specifically, we need the log at trace level after the hibernation. To get this, run the node (remember to capture the log output to a file), and after your computer wakes up, connect to it using `geth attach`, then run `debug.verbosity(5)`.

**Comment by wbt** [comment]
Not sure that "closed as completed" was fully appropriate.  I updated to the latest version and debug logs, but it's showing a lot of traffic that both distracts from the real issue and likely reveals more private data than I'd like.  I'm trying to figure out how to fully isolate the node via firewall settings so it's not connecting with as many random other peers, but haven't been able to prioritize completion of that just yet.
