### ISSUE TITLE
FreeBSD Compile Error cmd/utils/flags.go:554: undefined: raiseFdLimit cmd/utils/flags.go:557: undefined: getFdLimit

### ISSUE THREAD

**Issue by tymat** [ethereum/go-ethereum#2521]
#### System information

Geth version: `geth 1.4.1`
OS & Version: FreeBSD
Go Version: go1.6.1 freebsd/amd64

#### Expected behaviour

It should compile

#### Actual behaviour

It does not compile because of:

```
cmd/utils/flags.go:554: undefined: raiseFdLimit
cmd/utils/flags.go:557: undefined: getFdLimit
```

#### Steps to reproduce the behaviour

1. Get FreeBSD 10.1
2. Clone go-ethereum from git 
3. make all

#### Backtrace

````
# github.com/ethereum/go-ethereum/cmd/utils
cmd/utils/flags.go:554: undefined: raiseFdLimit
cmd/utils/flags.go:557: undefined: getFdLimit
*** Error code 2

Stop.
make: stopped in /usr/home/freebsd/go-ethereum
````

**Comment by karalabe** [comment]
@tymat Could you try https://github.com/ethereum/go-ethereum/pull/2529 ? We don't have a freebsd system to test it on.

**Comment by fjl** [comment]
I have actually tested it on FreeBSD btw ;)

‎

**Comment by karalabe** [comment]
Awesome! Merging
