### ISSUE TITLE
Temp files generated during DAG generation won't cleanup properly.

### ISSUE THREAD

**Issue by manoj398** [ethereum/go-ethereum#25227]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour
When old instances are cleaned up, here https://github.com/ethereum/go-ethereum/blob/de1cecb22e2a18ad70d4cb92bee122f4549c5b79/consensus/ethash/ethash.go#L279-L283

It won't consider any left out temp files generated during the process because they have a different name.

#### Expected behaviour
All files needs to be considered that were generated previously.

#### Steps to reproduce the behaviour
https://github.com/ethereum/go-ethereum/blob/de1cecb22e2a18ad70d4cb92bee122f4549c5b79/consensus/ethash/ethash.go#L133

Shutdown the node when DAG is being generated, The temp file generated with the `name + "." + randomInteger` would be left out. During the cleanup in the further runs, it won't be considered for removal. The cachecount flag doesn't count such files which is wrong. These files are generally in GBs and waste resources on disk.

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by Veterangrail** [comment]
> #### System information
> Geth version: `geth version` OS & Version: Windows/Linux/OSX Commit hash : (if `develop`)
> 
> #### Actual behaviour
> When old instances are cleaned up, here
> 
> https://github.com/ethereum/go-ethereum/blob/de1cecb22e2a18ad70d4cb92bee122f4549c5b79/consensus/ethash/ethash.go#L279-L283
> 
> It won't consider any left out temp files generated during the process because they have a different name.
> 
> #### Expected behaviour
> All files needs to be considered that were generated previously.
> 
> #### Steps to reproduce the behaviour
> https://github.com/ethereum/go-ethereum/blob/de1cecb22e2a18ad70d4cb92bee122f4549c5b79/consensus/ethash/ethash.go#L133
> 
> Shutdown the node when DAG is being generated, The temp file generated with the `name + "." + randomInteger` would be left out. During the cleanup in the further runs, it won't be considered for removal. The cachecount flag doesn't count such files which is wrong. These files are generally in GBs and waste resources on disk.
> 
> #### Backtrace
> ```
> [backtrace]
> ```
> 
> When submitting logs: please submit them as text and not screenshots.


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by Veterangrail** [comment]
> #### System information
> Geth version: `geth version` OS & Version: Windows/Linux/OSX Commit hash : (if `develop`)
> 
> #### Actual behaviour
> When old instances are cleaned up, here
> 
> https://github.com/ethereum/go-ethereum/blob/de1cecb22e2a18ad70d4cb92bee122f4549c5b79/consensus/ethash/ethash.go#L279-L283
> 
> It won't consider any left out temp files generated during the process because they have a different name.
> 
> #### Expected behaviour
> All files needs to be considered that were generated previously.
> 
> #### Steps to reproduce the behaviour
> https://github.com/ethereum/go-ethereum/blob/de1cecb22e2a18ad70d4cb92bee122f4549c5b79/consensus/ethash/ethash.go#L133
> 
> Shutdown the node when DAG is being generated, The temp file generated with the `name + "." + randomInteger` would be left out. During the cleanup in the further runs, it won't be considered for removal. The cachecount flag doesn't count such files which is wrong. These files are generally in GBs and waste resources on disk.
> 
> #### Backtrace
> ```
> [backtrace]
> ```
> 
> When submitting logs: please submit them as text and not screenshots.


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by Acetarax** [comment]
> #### System information
> Geth version: `geth version` OS & Version: Windows/Linux/OSX Commit hash : (if `develop`)
> 
> #### Actual behaviour
> When old instances are cleaned up, here
> 
> https://github.com/ethereum/go-ethereum/blob/de1cecb22e2a18ad70d4cb92bee122f4549c5b79/consensus/ethash/ethash.go#L279-L283
> 
> It won't consider any left out temp files generated during the process because they have a different name.
> 
> #### Expected behaviour
> All files needs to be considered that were generated previously.
> 
> #### Steps to reproduce the behaviour
> https://github.com/ethereum/go-ethereum/blob/de1cecb22e2a18ad70d4cb92bee122f4549c5b79/consensus/ethash/ethash.go#L133
> 
> Shutdown the node when DAG is being generated, The temp file generated with the `name + "." + randomInteger` would be left out. During the cleanup in the further runs, it won't be considered for removal. The cachecount flag doesn't count such files which is wrong. These files are generally in GBs and waste resources on disk.
> 
> #### Backtrace
> ```
> [backtrace]
> ```
> 
> When submitting logs: please submit them as text and not screenshots.

Make use of this https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by ligi** [comment]
yes - they should be deleted - would you make a PR to do so?
