### ISSUE TITLE
Not running after restart

### ISSUE THREAD

**Issue by j-dbooth** [ethereum/go-ethereum#25240]
Went to sleep lastnight and left my node to sync, woke up and Geth.exe was nowhere to be seen mustve crashed or something. Now restarting Geth with  "start geth.exe --datadir "G:\Geth"" just brings me here

```
-----------
INFO [07-05|10:27:09.023] Chain ID:  1 (mainnet)
INFO [07-05|10:27:09.025] Consensus: Ethash (proof-of-work)
INFO [07-05|10:27:09.026]
INFO [07-05|10:27:09.027] Pre-Merge hard forks:
INFO [07-05|10:27:09.028]  - Homestead:                   1150000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/homestead.md)
INFO [07-05|10:27:09.033]  - DAO Fork:                    1920000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/dao-fork.md)
INFO [07-05|10:27:09.038]  - Tangerine Whistle (EIP 150): 2463000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/tangerine-whistle.md)
INFO [07-05|10:27:09.043]  - Spurious Dragon/1 (EIP 155): 2675000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
INFO [07-05|10:27:09.047]  - Spurious Dragon/2 (EIP 158): 2675000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
INFO [07-05|10:27:09.052]  - Byzantium:                   4370000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/byzantium.md)
INFO [07-05|10:27:09.055]  - Constantinople:              7280000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/constantinople.md)
INFO [07-05|10:27:09.059]  - Petersburg:                  7280000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/petersburg.md)
INFO [07-05|10:27:09.066]  - Istanbul:                    9069000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/istanbul.md)
INFO [07-05|10:27:09.071]  - Muir Glacier:                9200000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/muir-glacier.md)
INFO [07-05|10:27:09.076]  - Berlin:                      12244000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/berlin.md)
INFO [07-05|10:27:09.081]  - London:                      12965000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/london.md)
INFO [07-05|10:27:09.087]  - Arrow Glacier:               13773000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/arrow-glacier.md)
INFO [07-05|10:27:09.092]  - Gray Glacier:                15050000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/gray-glacier.md)
INFO [07-05|10:27:09.097]
INFO [07-05|10:27:09.099] Merge not configured!
INFO [07-05|10:27:09.100]  - Hard-fork specification: https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md)
INFO [07-05|10:27:09.105] ---------------------------------------------------------------------------------------------------------------------------------------------------------
INFO [07-05|10:27:09.110]

```

I waited quite awhile longer and something quickly flashed mentioned unclean shutdown before closing the Geth.exe terminal.
Im deleting chaindata as im typing this and just gonna resync chain hopefully that fixes it

Nvm:
N̶o̶t̶h̶i̶n̶g̶s̶ h̶a̶p̶p̶e̶n̶s̶ a̶f̶t̶e̶r̶ t̶h̶i̶s̶, a̶n̶y̶b̶o̶d̶y̶ k̶n̶o̶w̶ w̶h̶y̶?̶

**Comment by malonehedges** [comment]
I'm also stuck since block 15090000

```
INFO [07-06|11:51:13.589] Skip duplicated bad block                number=15,090,000 hash=3adb58..cdd527
ERROR[07-06|11:51:13.589]
########## BAD BLOCK #########
Chain config: Chain ID:  1 (mainnet)
Consensus: Ethash (proof-of-work)

Pre-Merge hard forks:
 - Homestead:                   1150000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/homestead.md)
 - DAO Fork:                    1920000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/dao-fork.md)
 - Tangerine Whistle (EIP 150): 2463000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/tangerine-whistle.md)
 - Spurious Dragon/1 (EIP 155): 2675000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
 - Spurious Dragon/2 (EIP 158): 2675000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
 - Byzantium:                   4370000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/byzantium.md)
 - Constantinople:              7280000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/constantinople.md)
 - Petersburg:                  7280000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/petersburg.md)
 - Istanbul:                    9069000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/istanbul.md)
 - Muir Glacier:                9200000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/muir-glacier.md)
 - Berlin:                      12244000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/berlin.md)
 - London:                      12965000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/london.md)
 - Arrow Glacier:               13773000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/arrow-glacier.md)
 - Gray Glacier:                15050000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/gray-glacier.md)

Merge not configured!
 - Hard-fork specification: https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md)

Number: 15090000
Hash: 0x3adb58b249ef88687cb7f6645e87a26b8a2f8088d1509e29bac91407c9cdd527


Error: invalid mix digest
##############################

WARN [07-06|11:51:13.589] Synchronisation failed, dropping peer    peer=8490e1b31cdb0b65e0a87b1c41ce98109fe100d68877ae72fd7f8ebc6bcb6f38 err="retrieved hash chain is invalid: invalid mix digest"
```

**Comment by malonehedges** [comment]
I made a new issue because I'm not sure if your issue is the same as mine #25260

**Comment by fjl** [comment]
@j-dbooth let us know if your re-sync doesn't work.

**Comment by j-dbooth** [comment]
re-sync worked but then again i had to close geth with ctrl+c waited a few mins and then restarted using 
'start geth.exe --datadir "G:\Geth" --maxpeers "75" --cache "6144" --txpool.globalslots "60000" --txpool.globalqueue "4000"'
for some reason its given me same issue as before... i did stop the node yesterday a few times while it was still resyncing and it relaunched fine then

**Comment by j-dbooth** [comment]
`INFO [07-09|13:04:08.747] Starting Geth on Ethereum mainnet...
INFO [07-09|13:04:08.751] Maximum peer count                       ETH=75 LES=0 total=75
WARN [07-09|13:04:08.763] Sanitizing cache to Go's GC limits       provided=6144 updated=5436
INFO [07-09|13:04:08.767] Set global gas cap                       cap=50,000,000
INFO [07-09|13:04:08.771] Allocated trie memory caches             clean=815.00MiB dirty=1.33GiB
INFO [07-09|13:04:08.773] Allocated cache and file handles         database=G:\Geth\geth\chaindata cache=2.65GiB handles=8192
INFO [07-09|13:04:58.526] Opened ancient database                  database=G:\Geth\geth\chaindata\ancient readonly=false
INFO [07-09|13:04:58.633]
INFO [07-09|13:04:58.634] ---------------------------------------------------------------------------------------------------------------------------------------------------------
INFO [07-09|13:04:58.639] Chain ID:  1 (mainnet)
INFO [07-09|13:04:58.640] Consensus: Ethash (proof-of-work)
INFO [07-09|13:04:58.642]
INFO [07-09|13:04:58.642] Pre-Merge hard forks:
INFO [07-09|13:04:58.644]  - Homestead:                   1150000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/homestead.md)
INFO [07-09|13:04:58.648]  - DAO Fork:                    1920000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/dao-fork.md)
INFO [07-09|13:04:58.652]  - Tangerine Whistle (EIP 150): 2463000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/tangerine-whistle.md)
INFO [07-09|13:04:58.657]  - Spurious Dragon/1 (EIP 155): 2675000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
INFO [07-09|13:04:58.661]  - Spurious Dragon/2 (EIP 158): 2675000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
INFO [07-09|13:04:58.666]  - Byzantium:                   4370000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/byzantium.md)
INFO [07-09|13:04:58.670]  - Constantinople:              7280000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/constantinople.md)
INFO [07-09|13:04:58.675]  - Petersburg:                  7280000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/petersburg.md)
INFO [07-09|13:04:58.679]  - Istanbul:                    9069000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/istanbul.md)
INFO [07-09|13:04:58.683]  - Muir Glacier:                9200000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/muir-glacier.md)
INFO [07-09|13:04:58.688]  - Berlin:                      12244000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/berlin.md)
INFO [07-09|13:04:58.693]  - London:                      12965000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/london.md)
INFO [07-09|13:04:58.697]  - Arrow Glacier:               13773000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/arrow-glacier.md)
INFO [07-09|13:04:58.701]  - Gray Glacier:                15050000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/gray-glacier.md)
INFO [07-09|13:04:58.706]
INFO [07-09|13:04:58.707] Merge not configured!
INFO [07-09|13:04:58.708]  - Hard-fork specification: https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md)
INFO [07-09|13:04:58.712] ---------------------------------------------------------------------------------------------------------------------------------------------------------
INFO [07-09|13:04:58.717]`

**Comment by j-dbooth** [comment]
i also cant ipc into it either in this state

**Comment by j-dbooth** [comment]
it finally started just takes 30mins from there to actually launch fully... is this normal or should i swap out my external 1tb ssd? im running a ryzen 7 2700x with ddr4 3200Mhz 2x16GB RAM, cant see cpu or RAM being the issue tbh
