### ISSUE TITLE
debug_traceTransaction bug?

### ISSUE THREAD

**Issue by fairglu** [ethereum/go-ethereum#2525]
#### System information

Geth version: 1.5.0
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour

Should return execution trace as executed "normally"

#### Actual behaviour

Seems to return a different execution trace from the "normal" one

#### Steps to reproduce the behaviour

When invoked on tx 0xd8aaf9c7f3b5e2389e6899914d6421085e6d3b932fd427180dd7cdb67f83e18d it returns 64 steps with a CALL at step 52, however when the same tx is looked up on ether camp (https://live.ether.camp/transaction/d8aaf9c7f3b5e2/vmtrace#0) there are only 44 steps, and no CALL.

When querying the balance before & after the tx with eth_getBalance, the CALL does not seem present, which seems to hint that ether camp's trace would be correct, while debug_traceTransaction is not.

**Comment by fairglu** [comment]
Confirmed on just updated Geth/v1.5.0-unstable/linux/go1.5.1 from ppa:ethereum/ethereum-dev

**Comment by obscuren** [comment]
You are saying getBalance should have returned something different because the CALL also involved a value transfer?

**Comment by obscuren** [comment]
We found the issue, see linked commit. This will go in `1.4.2` today.

**Comment by fairglu** [comment]
Thanks!

At which time should the fix be on ppa:ethereum/ethereum-dev ? (will check asap)
