### ISSUE TITLE
Errors returned by a function are not checked

### ISSUE THREAD

**Issue by wjxin24** [ethereum/go-ethereum#25264]
Some functions may return an error value, however, the results of these functions are unchecked and unhandled in many cases, which may lead to potential problems.
For example, https://github.com/ethereum/go-ethereum/blob/e394d01f2a578765868355e98898bd17d3d076c1/core/types/block.go#L326
Here `Encode` may return an error, but the result of the function is unchecked. It may be safer to handle the possible error returned by the function first before continuing.

**Comment by karalabe** [comment]
RLP encoding can only fail if you try to encode something it cannot. A block is a consensus data structure (i.e. it doesn't change ever) and we know it can encode it. There's not much reason to check it here because there's nothing than can go wrong.
