### ISSUE TITLE
Pre-builds releases with a strange timestamp

### ISSUE THREAD

**Issue by bfgasparin** [ethereum/go-ethereum#25263]
#### System information

Geth version: `1.10.20`
OS & Version: Linux/OSX

When downloading the pre build  bundle from the website (`https://geth.ethereum.org/downloads/`) and extracting it using `tar` , the extracted directory has a strange timestamp `1970-01-01 00:00:00`. 

I tested using `v1.10.19` and `v1.10.20`, in both Linux and Mac OS systems, and got the same result. I initially though the downloaded file  was corrupted, but both md5 checksum and PGP verification matches. 

For instance, the md5sum used for the Linux 64x `v1.10.20` build  was `d1793b47659cb6b1bb753b6bae2792bb`. See details below.
 
Is that an issue when generating and compressing the pre-build files or should I be worried that the build is indeed corrupted?

#### Expected behaviour

```
$ tar xvf geth-linux-amd64-1.10.20-8f2416a8.tar.gz
geth-linux-amd64-1.10.20-8f2416a8/
geth-linux-amd64-1.10.20-8f2416a8/COPYING
geth-linux-amd64-1.10.20-8f2416a8/geth
```

#### Actual behaviour

```
$ tar xvf geth-linux-amd64-1.10.20-8f2416a8.tar.gz
geth-linux-amd64-1.10.20-8f2416a8/
geth-linux-amd64-1.10.20-8f2416a8/COPYING
geth-linux-amd64-1.10.20-8f2416a8/geth
tar: geth-linux-amd64-1.10.20-8f2416a8: implausibly old time stamp 1970-01-01 00:00:00

```

Note that `tar` notifies about the strange timestamp. 

Running `stat` in the extracted dir, we can see a strange Modify date.

```
$ stat geth-linux-amd64-1.10.20-8f2416a8
  File: 'geth-linux-amd64-1.10.20-8f2416a8'
  Size: 33        	Blocks: 0          IO Block: 4096   directory
Device: xxxxxxxx	Inode: xxxxxxxxxx     Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( 0001/user)   Gid: ( 0001/user)
Access: 2022-07-07 00:09:56.425842494 +0000
Modify: 1970-01-01 00:00:00.000000000 +0000
Change: 2022-07-07 00:09:56.757840594 +0000
 Birth: -
```

#### Steps to reproduce the behaviour

Just download the pre-build bundle from the download page (`https://geth.ethereum.org/downloads/`) and try to extract it.

**Comment by bfgasparin** [comment]
Any news on this?

**Comment by karalabe** [comment]
Thanks for the report, opened a PR to fix it.
