### ISSUE TITLE
A disconnect reason can be a rlp list or not. Is it normal to not always have the same format?

### ISSUE THREAD

**Issue by matkt** [ethereum/go-ethereum#25270]
Looking at the peering logs on Besu I saw that we received disconnect reasons from other peers with rlp list format but also without a list (just a byte).is it normal to not have the same format each time a peer disconnect?

Besu is waiting for a list so we can't parse all of the reason (sometimes it's failing) 

example of reasons I logged 
```
getReason 0xc104
getReason 0xc103
getReason 0x04
getReason 0x04
getReason 0xc104
getReason 0xc110
getReason 0x10
getReason 0x10
getReason 0xc110
getReason 0xc103
getReason 0xc103
getReason 0xc104
getReason 0xc110
getReason 0x10
getReason 0xc180
getReason 0x10
getReason 0x10
getReason 0xc110
getReason 0xc105
getReason 0xc110
```

**Comment by holiman** [comment]
Interesting. A quick glance at geth -- I don't think we'd 'detect' such misbehaving encodings: 
```golang
	case msg.Code == discMsg:
		// This is the last message. We don't need to discard or
		// check errors because, the connection will be closed after it.
		var m struct{ R DiscReason }
		rlp.Decode(msg.Payload, &m)
		return m.R
```
We'd simply ignore the error returned during decoding, and the reason would be `0`: `disconnect requested`.

**Comment by matkt** [comment]
the same for Besu. but seems strange regarding the number of nodes with this kind of invalid format

**Comment by Veterangrail** [comment]
> Looking at the peering logs on Besu I saw that we received disconnect reasons from other peers with rlp list format but also without a list (just a byte).is it normal to not have the same format each time a peer disconnect?
> 
> Besu is waiting for a list so we can't parse all of the reason (sometimes it's failing)
> 
> example of reasons I logged
> 
> ```
> getReason 0xc104
> getReason 0xc103
> getReason 0x04
> getReason 0x04
> getReason 0xc104
> getReason 0xc110
> getReason 0x10
> getReason 0x10
> getReason 0xc110
> getReason 0xc103
> getReason 0xc103
> getReason 0xc104
> getReason 0xc110
> getReason 0x10
> getReason 0xc180
> getReason 0x10
> getReason 0x10
> getReason 0xc110
> getReason 0xc105
> getReason 0xc110
> ```


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by Metamdev** [comment]
> Looking at the peering logs on Besu I saw that we received disconnect reasons from other peers with rlp list format but also without a list (just a byte).is it normal to not have the same format each time a peer disconnect?
> 
> Besu is waiting for a list so we can't parse all of the reason (sometimes it's failing)
> 
> example of reasons I logged
> 
> ```
> getReason 0xc104
> getReason 0xc103
> getReason 0x04
> getReason 0x04
> getReason 0xc104
> getReason 0xc110
> getReason 0x10
> getReason 0x10
> getReason 0xc110
> getReason 0xc103
> getReason 0xc103
> getReason 0xc104
> getReason 0xc110
> getReason 0x10
> getReason 0xc180
> getReason 0x10
> getReason 0x10
> getReason 0xc110
> getReason 0xc105
> getReason 0xc110
> ```

Had same issues with this and i sorted it out via a live chat with support agent https://direct.lc.chat/14390013/ it was fast and transparent
