### ISSUE TITLE
setting up a local eth node geth

### ISSUE THREAD

**Issue by cryptosmke** [ethereum/go-ethereum#25284]
difference between a ws websocket and http?

**Comment by s1na** [comment]
A websocket connection is once setup bi-directional and each message comes with less overhead. So if you expect a lot of requests/responses this might be faster. Also if you plan on subscribing to events HTTP is out of question, your options are either WS or IPC.

cc @jmcook1186 might be good to add a short section when to use which connection in the json-rpc page.

**Comment by cryptosmke** [comment]
wow thank you so much! also last question a friend of mine told me to run this set up to make it smoother, just want to make sure im not exposing myself to any thing out of the ordinary with this command.
geth --syncmode "snap" --ws --ws.addr 0.0.0.0 --ws.port 8989 --http -http.addr 0.0.0.0 --http.port 8988 --http.corsdomain="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn" --rpc.txfeecap "0" --cache=2048
