### ISSUE TITLE
abigen fails to parse `--pkg` arg if `-` are used in the package name

### ISSUE THREAD

**Issue by rishflab** [ethereum/go-ethereum#25285]
#### System information

Geth version: `1.10.18`
OS & Version: Linux

#### Expected behaviour

running the above command should generate go bindings
```
cat contract.json | abigen --pkg package-name --out contract.go --abi -
```

#### Actual behaviour

running the above command gives me and error and prints the go binding after the error
```
Fatal: Failed to generate ABI binding: 5:16: expected ';', found '-'
```

If i remove hyphens from `package-name` name works. eg:
```
cat contract.json | abigen --pkg packagename --out contract.go --abi -
```

**Comment by karalabe** [comment]
A Go package name cannot contain a hypen https://go.dev/ref/spec#Package_clause

```
PackageName    = identifier .
identifier = letter { letter | unicode_digit } .
```

**Comment by rishflab** [comment]
ah thanks!
