### ISSUE TITLE
Is there a way to test storage performance?

### ISSUE THREAD

**Issue by lurais** [ethereum/go-ethereum#25286]
hello ,is there a way to test storage performance of ethereum? Just like mysql benchmark guide or report ,eg:https://cloud.baidu.com/doc/RDS/s/Kjwvyzirr

**Comment by karalabe** [comment]
There have been benchmarks posted here and there, but it's kind of hard to create something realistic and useful. Tx types vary a lot and creating synthetic becnhmarks that just push one aspect of the system whilst ignoring all others is not too helpful to diagnose things.

TL;DR: No

**Comment by lurais** [comment]
The storage performance is not abusolutely related to the real specified tx types,so ,is that useful to test the storage performance only? for we can only concentrate on the storage performance without care about the tx types?

**Comment by lurais** [comment]
If we can judge the performance of the storage,we can easily make full use of the hardware,Just like the mysql guide?
