### ISSUE TITLE
geth set up command is this safe?

### ISSUE THREAD

**Issue by cryptosmke** [ethereum/go-ethereum#25297]
hey fam sorry for all the noob questions, one of my friends that is running one told me to run this to make it run smoothly. He's new  too so just want to make sure this command is safe not sure if this is ok and the command doesnt expose me to risk.

geth --syncmode "snap" --ws --ws.addr 0.0.0.0 --ws.port 8989 --http -http.addr 0.0.0.0 --http.port 8988 --http.corsdomain="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn" --rpc.txfeecap "0" --cache=4096

**Comment by lightclient** [comment]
I don't think you want the `--http.corsdomain` flag. Everything else seems fine.

**Comment by jwasinger** [comment]
But if he doesn't have the corsdomain flag that leaves the rpc apis completely accessible if the external network interface is exposed to the web?
