### ISSUE TITLE
How long does it take to do a full sync with the current geth version

### ISSUE THREAD

**Issue by victorkingi** [ethereum/go-ethereum#25291]
I have been using geth for a while now just tinkering and understanding the code but never got to try out a full sync. Does anyone know how long it will take to do a full sync with the current geth version on an acer nitro 5 laptop? Here are my specs:

Processor	Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz   2.30 GHz
Installed RAM	32.0 GB (31.8 GB usable)
System type	64-bit operating system, x64-based processor
NVIDIA GTX 1050 4GB vRAM

I was also planning on getting a 2TB NVMe SSD with the highest IOPS since I understand sync time is mainly impacted by I/O reads and writes rather than processor speed.

Any time estimates will be appreciated!

Thanks

**Comment by lightclient** [comment]
Should be around 8-12 days for full sync. Snap sync is much faster, less than a day.
