### ISSUE TITLE
local geth node

### ISSUE THREAD

**Issue by cryptosmke** [ethereum/go-ethereum#25294]
Im running a local geth node and i have a mint bot that does mints automatically when im not home, I checked the status on one my transaction and i got error code -3200 exceeds block gas limit. not sure if its because i tried sending  the transaction with more gwie than i normally do? not sure if theres a command to run to fix this. thanks everyone!

**Comment by jwasinger** [comment]
Your transaction is consuming more gas than the block limit you've configured allows.  You need to increase the gas limit.

**Comment by lightclient** [comment]
You can change the gas limit in the genesis block and/or configure `--miner.gaslimit`. It defaults to 30mm. Although I suspect there is something wrong with your bot, because a mint shouldn't take much more than a couple 100k gas.

**Comment by cryptosmke** [comment]
got it thanks so much! so just input?  --miner.gaslimit 
or do i have to set it higher not sure what would be a good limit that it should take not to get the same error. thank you for all your help

**Comment by lightclient** [comment]
Tbh I don't think you should be changing the block limit, but rather understanding why your execution is running up against it in the first place. It seems pretty unlikely that what you want to do can't be done under the current limit you are using.
