### ISSUE TITLE
Unable to validate EIP712 TypedData signer from a valid go-ethereum signed TypedData

### ISSUE THREAD

**Issue by IanDorion** [ethereum/go-ethereum#25301]
I'm having trouble verifying a valid go EIP712 signature in solidity.

Here is a link to the my question.

https://ethereum.stackexchange.com/questions/131756/verified-go-signature-fails-in-solidity-eip712-typeddata

I have tested and validate this signature with Ethers.
When signed with Ethers the contract validates it and V = 28

Reproduced with go and validated with go.
The contract failed to validate it and V = 27

Could a go-ethereum expert look at it please?

**Comment by Veterangrail** [comment]
> I'm having trouble verifying a valid go EIP712 signature in solidity.
> 
> Here is a link to the my question.
> 
> https://ethereum.stackexchange.com/questions/131756/verified-go-signature-fails-in-solidity-eip712-typeddata
> 
> I have tested and validate this signature with Ethers. When signed with Ethers the contract validates it and V = 28
> 
> Reproduced with go and validated with go. The contract failed to validate it and V = 27
> 
> Could a go-ethereum expert look at it please?


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by kabaluyot** [comment]
@IanDorion what's the fix of this issue?
