### ISSUE TITLE
On-disk DB structure large on initial sync until restart

### ISSUE THREAD

**Issue by yorickdowne** [ethereum/go-ethereum#25308]
#### System information

Geth version: `1.10.20`
OS & Version: Linux Ubuntu 22.04

#### Expected behaviour

After snap sync of mainnet, expected DB size around 560-570 GiB

#### Actual behaviour

After snap sync of mainnet, on-disk DB size is around 815 GiB

Restart Geth once, this reduces to around 780 GiB

Restart Geth a second time, this reduces to around 565 GiB

A third restart does not change on-disk size

I am unsure whether this is a bug or a feature. It certainly is unexpected, and not how Geth behaved in previous versions.

**Comment by oggy95** [comment]
Have a same issue. 
For me geth created many files, which removed after restart geth. Almost 200-300 Gb were removed after each restart.

Geth version `v1.10.20`
Geth command:
`geth --cache "2048" --datadir "/data/var/lib/ethereum_wallet/" --ipcpath="/data/tmp/sock_geth.ipc" --http.api eth,web3,personal  --http --http.addr "0.0.0.0" --http.port "8545" --syncmode "full" --ws --ws.addr "0.0.0.0" --ws.api eth,net,web3 --txpool.globalqueue 5000 --snapshot=false &>> /data/eth/var/log/ethereum.log`

**Comment by Veterangrail** [comment]
> #### System information
> Geth version: `1.10.20` OS & Version: Linux Ubuntu 22.04
> 
> #### Expected behaviour
> After snap sync of mainnet, expected DB size around 560-570 GiB
> 
> #### Actual behaviour
> After snap sync of mainnet, on-disk DB size is around 815 GiB
> 
> Restart Geth once, this reduces to around 780 GiB
> 
> Restart Geth a second time, this reduces to around 565 GiB
> 
> A third restart does not change on-disk size
> 
> I am unsure whether this is a bug or a feature. It certainly is unexpected, and not how Geth behaved in previous versions.


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by karalabe** [comment]
This was a bug in leveldb, we've downgraded to the previous good version in 1.10.21. Please update to that.
