### ISSUE TITLE
Private chain mining issue -- panic: ethash_full_new IO or memory error

### ISSUE THREAD

**Issue by ghost** [ethereum/go-ethereum#2530]
#### System information

Geth version: `geth 1.4.0`
OS & Version: Windows 10
#### Expected behaviour

I am trying to create a private network using the below command,

geth --genesis CustomGenesis.json --identity "GsNode" --mine --minerthreads 1 --datadir "C:\ethereum\chains\GsChain" --networkid 1900 --nodiscover --maxpeers 0 --verbosity 6 --etherbase 0x59A11EAceb3D7F1ab24447c054C90aab6E97182A --nat "any" console

where my genesis file is
{
    "nonce": "0x0000000000000042",
    "timestamp": "0x00",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x0",
    "gasLimit": "0x8000000",
    "difficulty": "0x400",
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "alloc": {"0x59A11EAceb3D7F1ab24447c054C90aab6E97182A":{"balance":"20000000000000000000"}}
}

But there some issue on mining creating DAG file

I am getting following error

C:\ethereum>geth --genesis CustomGenesis.json --identity "GsNode" --mine --minerthreads 1 --datadir "C:\ethereum\chains\GsChain" --networkid 1900 --nodiscover --maxpeers 0 --verbosity 6 --etherbase 0x59A11EAceb3D7F1ab24447c054C90aab6E97182A --nat "any" console
###### 
# 
# --genesis is deprecated. Switch to use 'geth init /path/to/file'
# 
###### 

I0509 16:49:01.040137 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to C:\ethereum\chains\GsChain\chaindata
I0509 16:49:01.129195 ethdb/database.go:169] closed db:C:\ethereum\chains\GsChain\chaindata
I0509 16:49:01.131194 accounts/addrcache.go:215] reloaded keys, cache has 1 accounts
I0509 16:49:01.132194 accounts/watch.go:74] now watching C:\ethereum\chains\GsChain\keystore
I0509 16:49:01.135197 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to C:\ethereum\chains\GsChain\chaindata
I0509 16:49:01.136198 accounts/addrcache.go:215] reloaded keys, cache has 1 accounts
I0509 16:49:01.173222 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to C:\ethereum\chains\GsChain\dapp
I0509 16:49:01.185230 eth/backend.go:169] Protocol Versions: [63 62 61], Network Id: 1900
I0509 16:49:01.187232 core/state/statedb.go:267] (+) 59a11eaceb3d7f1ab24447c054c90aab6e97182a
I0509 16:49:01.189232 core/state/state_object.go:160] 59a11eaceb3d7f1ab24447c054c90aab6e97182a: #0 20000000000000000000 (+ 20000000000000000000)
I0509 16:49:01.193235 core/genesis.go:92] Genesis block already in chain. Writing canonical number
I0509 16:49:01.196236 eth/backend.go:177] Successfully wrote custom genesis block: c648d0980cdcd82c41a259198c8062d6ba5baa1c47522850dad1a783c8349317
I0509 16:49:01.198237 eth/backend.go:198] Blockchain DB Version: 3
I0509 16:49:01.201241 core/blockchain.go:206] Last header: #0 [e148ad9c…] TD=1024
I0509 16:49:01.203241 core/blockchain.go:207] Last block: #0 [c648d098…] TD=1024
I0509 16:49:01.204244 core/blockchain.go:208] Fast block: #0 [c648d098…] TD=1024
I0509 16:49:01.207244 p2p/server.go:311] Starting Server
I0509 16:49:01.209247 eth/backend.go:449] Automatic pregeneration of ethash DAG ON (ethash dir: C:\Users\SAMSUNG\AppData\Ethash)
I0509 16:49:01.209247 node/node.go:261] InProc registered *node.PrivateAdminAPI under 'admin'
I0509 16:49:01.213248 node/node.go:261] InProc registered *node.PublicAdminAPI under 'admin'
I0509 16:49:01.215249 node/node.go:261] InProc registered *debug.HandlerT under 'debug'
I0509 16:49:01.217251 node/node.go:261] InProc registered *node.PublicDebugAPI under 'debug'
I0509 16:49:01.219252 node/node.go:261] InProc registered *node.PublicWeb3API under 'web3'
I0509 16:49:01.222253 node/node.go:261] InProc registered *eth.PublicEthereumAPI under 'eth'
I0509 16:49:01.225259 node/node.go:261] InProc registered *eth.PublicAccountAPI under 'eth'
I0509 16:49:01.227258 node/node.go:261] InProc registered *eth.PrivateAccountAPI under 'personal'
I0509 16:49:01.229259 node/node.go:261] InProc registered *eth.PublicBlockChainAPI under 'eth'
I0509 16:49:01.231261 node/node.go:261] InProc registered *eth.PublicTransactionPoolAPI under 'eth'
I0509 16:49:01.233261 node/node.go:261] InProc registered *eth.PublicMinerAPI under 'eth'
I0509 16:49:01.235263 node/node.go:261] InProc registered *downloader.PublicDownloaderAPI under 'eth'
I0509 16:49:01.238264 node/node.go:261] InProc registered *eth.PrivateMinerAPI under 'miner'
I0509 16:49:01.240267 node/node.go:261] InProc registered *eth.PublicTxPoolAPI under 'txpool'
I0509 16:49:01.243268 node/node.go:261] InProc registered *filters.PublicFilterAPI under 'eth'
I0509 16:49:01.245270 node/node.go:261] InProc registered *eth.PrivateAdminAPI under 'admin'
I0509 16:49:01.247271 node/node.go:261] InProc registered *eth.PublicDebugAPI under 'debug'
I0509 16:49:01.249272 node/node.go:261] InProc registered *eth.PrivateDebugAPI under 'debug'
I0509 16:49:01.251273 node/node.go:261] InProc registered *eth.PublicNetAPI under 'net'
I0509 16:49:01.253276 node/node.go:261] InProc registered *ethreg.PrivateRegistarAPI under 'admin'
I0509 16:49:01.256280 node/node.go:287] IPC registered *node.PrivateAdminAPI under 'admin'
I0509 16:49:01.259279 node/node.go:287] IPC registered *node.PublicAdminAPI under 'admin'
I0509 16:49:01.261281 node/node.go:287] IPC registered *debug.HandlerT under 'debug'
I0509 16:49:01.263280 node/node.go:287] IPC registered *node.PublicDebugAPI under 'debug'
I0509 16:49:01.264281 node/node.go:287] IPC registered *node.PublicWeb3API under 'web3'
I0509 16:49:01.266283 node/node.go:287] IPC registered *eth.PublicEthereumAPI under 'eth'
I0509 16:49:01.269286 node/node.go:287] IPC registered *eth.PublicAccountAPI under 'eth'
I0509 16:49:01.271286 node/node.go:287] IPC registered *eth.PrivateAccountAPI under 'personal'
I0509 16:49:01.273288 node/node.go:287] IPC registered *eth.PublicBlockChainAPI under 'eth'
I0509 16:49:01.209247 p2p/server.go:555] Listening on [::]:30303
I0509 16:49:01.212248 eth/backend.go:456] checking DAG (ethash dir: C:\Users\SAMSUNG\AppData\Ethash)
I0509 16:49:01.276290 node/node.go:287] IPC registered *eth.PublicTransactionPoolAPI under 'eth'
I0509 16:49:01.281293 node/node.go:287] IPC registered *eth.PublicMinerAPI under 'eth'
I0509 16:49:01.283295 node/node.go:287] IPC registered *downloader.PublicDownloaderAPI under 'eth'
I0509 16:49:01.286297 node/node.go:287] IPC registered *eth.PrivateMinerAPI under 'miner'
I0509 16:49:01.288297 node/node.go:287] IPC registered *eth.PublicTxPoolAPI under 'txpool'
I0509 16:49:01.290299 node/node.go:287] IPC registered *filters.PublicFilterAPI under 'eth'
I0509 16:49:01.292301 node/node.go:287] IPC registered *eth.PrivateAdminAPI under 'admin'
I0509 16:49:01.294301 node/node.go:287] IPC registered *eth.PublicDebugAPI under 'debug'
I0509 16:49:01.296303 node/node.go:287] IPC registered *eth.PrivateDebugAPI under 'debug'
I0509 16:49:01.298304 node/node.go:287] IPC registered *eth.PublicNetAPI under 'net'
I0509 16:49:01.300306 node/node.go:287] IPC registered *ethreg.PrivateRegistarAPI under 'admin'
I0509 16:49:01.303308 node/node.go:298] IPC endpoint opened: \.\pipe\geth.ipc
I0509 16:49:01.303308 miner/miner.go:119] Starting mining operation (CPU=1 TOT=2)
I0509 16:49:01.308313 core/state/state_object.go:160] 59a11eaceb3d7f1ab24447c054c90aab6e97182a: #0 25000000000000000000 (+ 5000000000000000000)
I0509 16:49:01.312313 miner/worker.go:565] commit new work on block 1 with 0 txs & 0 uncles. Took 5.0033ms
I0509 16:49:01.315315 miner/agent.go:118] (re)started agent[0]. mining...
I0509 16:49:01.317317 ethash.go:259] Generating DAG for epoch 0 (size 1073739904) (0000000000000000000000000000000000000000000000000000000000000000)
instance: Geth/v1.4.0-rc-8241fa52/windows/go1.6.1/GsNode
coinbase: 0x59a11eaceb3d7f1ab24447c054c90aab6e97182a
at block: 0 (Thu, 01 Jan 1970 05:30:00 IST)
 datadir: C:\ethereum\chains\GsChain

> I0509 16:49:03.143528 p2p/nat/nat.go:109] network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
> panic: ethash_full_new IO or memory error

 any one could help me?

Thanks,
Mufeed

**Comment by fjl** [comment]
This can't happen anymore because the ethash implementation was rewritten in Go ~10 months ago.
