### ISSUE TITLE
make: *** [Makefile:12: geth] Error 1

### ISSUE THREAD

**Issue by cosminmarina** [ethereum/go-ethereum#25317]
#### System information

Go version: `1.15.15`
OS & Version: Debian 11

When ```make geth```:

``` 
env GO111MODULE=on go run build/ci.go install ./cmd/geth
package command-line-arguments
	imports github.com/ethereum/go-ethereum/internal/build
	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
	imports github.com/Azure/azure-sdk-for-go/sdk/azcore: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.21.1
package command-line-arguments
	imports github.com/ethereum/go-ethereum/internal/build
	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
	imports github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime
	imports github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.21.1/internal/shared
package command-line-arguments
	imports github.com/ethereum/go-ethereum/internal/build
	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
	imports github.com/Azure/azure-sdk-for-go/sdk/azcore/policy: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.21.1/policy
package command-line-arguments
	imports github.com/ethereum/go-ethereum/internal/build
	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
	imports github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.21.1/streaming
package command-line-arguments
	imports github.com/ethereum/go-ethereum/internal/build
	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
	imports github.com/Azure/azure-sdk-for-go/sdk/azcore/to: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.21.1/to
package command-line-arguments
	imports github.com/ethereum/go-ethereum/internal/build
	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
	imports github.com/Azure/azure-sdk-for-go/sdk/internal/uuid: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/internal@v0.8.3/uuid
package command-line-arguments
	imports github.com/ethereum/go-ethereum/internal/build
	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/internal
make: *** [Makefile:12: geth] Error 1
```

Anyone know what's happening? It's my firts time trying to use Ethereum

**Comment by Veterangrail** [comment]
> #### System information
> Go version: `1.15.15` OS & Version: Debian 11
> 
> When `make geth`:
> 
> ```
> env GO111MODULE=on go run build/ci.go install ./cmd/geth
> package command-line-arguments
> 	imports github.com/ethereum/go-ethereum/internal/build
> 	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
> 	imports github.com/Azure/azure-sdk-for-go/sdk/azcore: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.21.1
> package command-line-arguments
> 	imports github.com/ethereum/go-ethereum/internal/build
> 	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
> 	imports github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime
> 	imports github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.21.1/internal/shared
> package command-line-arguments
> 	imports github.com/ethereum/go-ethereum/internal/build
> 	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
> 	imports github.com/Azure/azure-sdk-for-go/sdk/azcore/policy: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.21.1/policy
> package command-line-arguments
> 	imports github.com/ethereum/go-ethereum/internal/build
> 	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
> 	imports github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.21.1/streaming
> package command-line-arguments
> 	imports github.com/ethereum/go-ethereum/internal/build
> 	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
> 	imports github.com/Azure/azure-sdk-for-go/sdk/azcore/to: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.21.1/to
> package command-line-arguments
> 	imports github.com/ethereum/go-ethereum/internal/build
> 	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
> 	imports github.com/Azure/azure-sdk-for-go/sdk/internal/uuid: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/internal@v0.8.3/uuid
> package command-line-arguments
> 	imports github.com/ethereum/go-ethereum/internal/build
> 	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
> 	imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal: build constraints exclude all Go files in /home/cubanflow/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.3.0/internal
> make: *** [Makefile:12: geth] Error 1
> ```
> 
> Anyone know what's happening? It's my firts time trying to use Ethereum


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by ligi** [comment]
Please try with go 1.16 or later as documented here: https://github.com/ethereum/go-ethereum#building-the-source

**Comment by karalabe** [comment]
Only the latest 2 Go releases is ever supported (currently 1.17 and 1.18).
