### ISSUE TITLE
geth error code -3200

### ISSUE THREAD

**Issue by geth36** [ethereum/go-ethereum#25318]
Im running a local geth node to increase transactions speeds for nfts minting however there has been gas wars and i try to send the transaction with higher gas but i get that error code -3200 exceeds block gas limit. is there a command to fix this?

![gaslimit](https://user-images.githubusercontent.com/109111111/179426206-435ca71c-7459-4dfa-96f7-966e52c88793.jpeg)

**Comment by lightclient** [comment]
This means the transaction you're sending has a gas limit larger than the block gas limit. I recommend you look into your transaction generation logic and gas limit estimation and determine why the gas limit is so large.

**Comment by SomeGuyCalledBru** [comment]
> Im running a local geth node to increase transactions speeds for nfts minting however there has been gas wars and i try to send the transaction with higher gas but i get that error code -3200 exceeds block gas limit. is there a command to fix this?

Sounds like you want to raise your gas price/priority fee but you're raising your gas limit instead. Gas limit remains constant with the same transaction, does not give you "speed", and I don't see how a mint would use more than a few hundred K. 

Or, you're setting your gas price as the limit by accident.
