### ISSUE TITLE
Why does Geth checks 'prev' when create a new account?

### ISSUE THREAD

**Issue by joonha97** [ethereum/go-ethereum#25334]
I found that Geth checks if there is previous account when creating a new account (core>state>statedb.go>createObject()).
But I have no idea what is the case that the previous account exists.
In what case a 'prev' account exists in Ethereum?

Thank you!

**Comment by s1na** [comment]
Statedb is the in-memory cache layer over the state database. `prev` is an account that existed in the cache under the same address. `createObject` is called in `CreateAccount` which is used for creating a contract. As per the comment it's possible to compute the address of a contract being created before, sends funds to it in which case a state object will exist by the time a contract is gonna be created at that address. Note this won't be considered a collision. Collision is when either the existing account has nonce > 0 or non-empty code. Hope that answers your question.
