### ISSUE TITLE
want to start contribution

### ISSUE THREAD

**Issue by uvsingh2706** [ethereum/go-ethereum#25337]
hello dear contributors ,
i also want to start the contribution and right now i am new can you please give me some tips to start

**Comment by s1na** [comment]
Contributions are always welcome. You can try checking out the issues with labels [help wanted](https://github.com/ethereum/go-ethereum/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) or [good first issue](https://github.com/ethereum/go-ethereum/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

If you're considering a bigger change, please raise it in an issue before starting work on it. This way you'll get some feedback if it will be merged when implemented well.
