### ISSUE TITLE
Geth hanging while syncing blocks(attached logs)

### ISSUE THREAD

**Issue by gsj5** [ethereum/go-ethereum#2533]
#### System information

Version: 1.5.0-unstable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: Linux ip-172-31-11-69 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
#### Expected behaviour

geth continuously syncs 
#### Actual behaviour

Taking hours at a time to sync next set of blocks, even with 25 peers attached
#### Steps to reproduce the behaviour

Ran geth with nohup, which initially worked as expected, however, after an hour, it stopped syncing blocks.  Waited for 50 minutes without much joy, so attached to geth, and set debug.verbosity(6) to see what was going on. See attached logs of peer list and geth debug log for details.

[Downloads.zip](https://github.com/ethereum/go-ethereum/files/255596/Downloads.zip)

BTW, numerous past attempts at geth --fast has not worked either.
#### Backtrace

```
[backtrace]
```

**Comment by d57heinz** [comment]
on 1.5.0 you have to completely remove all contents of the blocks folder in order for the --fast sync to work.  at least in my experience.  And im on windows 10  Best Regards

**Comment by gsj5** [comment]
@d57heinz, thanks for the feedback.  Yes, I am aware of the explicit requirement to start fresh when using  geth --fast.  

I believe issue you're alluding might be similar to the one I reported few days ago at https://github.com/ethereum/go-ethereum/issues/2467.  After getting "empty head header set", last block# is reset and few minutes later fast sync says its complete, and disables itself.  Unfortunately, I haven't received any feedback on this issue and not sure if it actually is the root cause of my issues with fast syncing.

**Comment by rachimo34** [comment]
Hey guys 
I'm experiencing the same issue

Version: 1.4.4 stable
Protocol Versions: [63 62 61], Network Id: 1
Blockchain DB Version: 3
OS: OSX 10.10.5 

geth --fast
eth/handler.go:92] blockchain not empty, fast sync disabled
download few thousand block and then stop, then restart few hundreds than stop...
...restart to download few thousand and then I've got Synchronisation failed: peer is unknown or unhealthy or Peer 767df9f471999661 [blocks 0.00/s, receipts 0.00/s, states 0.00/s, lacking    0]: empty head header set...stop downloading...and then restart after a while
Any what can be the issue ?

**Comment by fjl** [comment]
The issue has been identified. Watch‎ #2569 for progress.
