### ISSUE TITLE
memory consumption keeps increasing and killed by OOM killer

### ISSUE THREAD

**Issue by bububut** [ethereum/go-ethereum#25347]
#### System information
Geth
Version: 1.10.19-stable
Git Commit: 23bee16208718975f9b9e012949b8d4ee1223108
Architecture: amd64
Go Version: go1.18.1
Operating System: linux, Ubuntu 20.04.4 LTS on AWS
commands: geth --datadir /data/geth/ --mainnet --syncmode "snap" --http --ws --signer /home/ubuntu/.clef/clef.ipc --cache 1024 

#### Actual behaviour

geth is up to latest block.
previously I used a 16GB memory instance on AWS and geth is killed by OOM killer for every 4~5 days.
then I switched to a 32GB instance and it keeps running for about 2 weeks. I noticed it's memory usage has been increasing by ~1G each day and now its ram usage is 25G

$ ps axo pid,size,comm|grep geth
2697 27649956 geth

What can I do to limit it's memory usage? Or what log should I look into to identify the problem

**Comment by MariusVanDerWijden** [comment]
Thank you for opening this issue! 
We have a couple of questions:
- How much traffic do you have via http/ws?
- Do you have clef running simultaneously? Otherwise the queries to clef would time out
- Could you run `geth attach --exec debug.writeMemProfile\(\"memprofile\"\)` on your node when it has allocated so much memory? This will create a file `memprofile` that we can take a look at

**Comment by bububut** [comment]
Thanks for your reply

1. very low traffic. I'm the only user. About 3 http rpc calls per block.
2. clef is running. But when I switch to the clef terminal, it's always waiting on "List Account request ...... Approve? [y/N]" prompt. I never react. Will that cause the problem?
3. geth is killed by OOM killer today. I can wait a couple days, then run the memprofile

**Comment by bububut** [comment]
Can I use geth without clef? I don't use clef to manage my accounts. I'm running it only because it's in the tutorial

**Comment by MariusVanDerWijden** [comment]
you absolutely can run geth without clef! Which tutorial are you referring to?

**Comment by bububut** [comment]
I was reading this one: [](https://geth.ethereum.org/docs/getting-started)
Thanks for your help! I'll run geth standalone and observe the memory situation

**Comment by MariusVanDerWijden** [comment]
cc @jmcook1186 seems like our tutorial is misleading users a bit into thinking they have to run clef, or open up the http ports. Should we maybe split the tutorial into two? "Running geth" and "Interacting with the blockchain via geth + clef" for example

**Comment by jmcook1186** [comment]
sure - we can split them out - I'll get on it this morning.

**Comment by weimumu** [comment]
@bububut I have the same problem, in a compute with 8GB RAM and geth --cache=1024;Is there any solution

**Comment by bububut** [comment]
> @bububut I have the same problem, in a compute with 8GB RAM and geth --cache=1024;Is there any solution

in my case it's pending on requests to clef as mentioned in this thread. And stop using clef solved the problem for me.
