### ISSUE TITLE
Geth http rpc and ipc, both out of sync and behaving strangely ?

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [ethereum/go-ethereum#25348]
I am using geth ( version 1.10.20-stable) with web3.py on Ubuntu 20.04

it was working fine

now, using IPC or HTTP Provider shows web3.isConnected() as True 

but something like wallet balances or account nonces are shown as zero

I am not sure what is going on and considered opening an issue the best avenue to finding a solution

**Comment by lightclient** [comment]
I recommend posting on https://ethereum.stackexchange.com for debugging help.
