### ISSUE TITLE
The new geth 1.4.2 is not giving me new work

### ISSUE THREAD

**Issue by mmitech** [ethereum/go-ethereum#2536]
```
Geth
Version: 1.4.2-stable-566af6ef
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=/home/netis/go
GOROOT=/opt/google/go
```

**geth is not giving me new work, this is giving me the same result all the time:**

`curl -X POST http://127.0.0.1:8545 -d '{"jsonrpc":"2.0","method":"eth_getWork","params":[],"id":0}'`

**Result** 

`{"jsonrpc":"2.0","id":0,"result":["0x650b11cffad9558068d3108cb3bd2ce9bfcdc6c759afe6c861914e02950157e6","0x95d53b63d0b531598853dfe1f1271a355a583c442d509d228ff92a2b0a0d801a","0x000000000007e93f53d50baa9721a56e06c7aefbc3ca99bd43d7a953631b336a"]}`

**Comment by fjl** [comment]
I can't reproduce this. Are you synced with the network?>

**Comment by obscuren** [comment]
After every block it gives me new work to work on. Are you sure you're fully synced / have any peers to sync with?

**Comment by mmitech** [comment]
Yes I am syncing, I can see it getting blocks in logs, a downgrade to 1.4.1 solved the problem right away.

I am not the only one having this issue, a couple of pool owners already complained about it [here](https://gitter.im/sammy007/open-ethereum-pool?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
