### ISSUE TITLE
Merge not configured!

### ISSUE THREAD

**Issue by newearthmartin** [ethereum/go-ethereum#25366]
I had to do a search on the internet and the discord channel to understand what `Merge not configured!` means. It seems that there is nothing to worry and it means that [the network does not have a TTD for the merge](https://discord.com/channels/482467812179181568/482467812816977921/990607676528558142). 

Please correct me if I'm wrong. 

If I'm not wrong, this is awful wording. **It gives the user the impression that they need to configure something.** The word configure is prompting the user to do something. If it is a message about the **state of the network**, this is not a configuration in Geth. 

**It should be clear that this is a message about the state of the network.**

**Comment by Zachinquarantine** [comment]
> it means that [the network does not have a TTD for the merge](https://discord.com/channels/482467812179181568/482467812816977921/990607676528558142)

AFAIK you are correct.


I've simplified this message in #25371.

**Comment by newearthmartin** [comment]
That's great, thanks! I'm sure many users will be relieved
