### ISSUE TITLE
Stuck in trouble, logging "Block state missing, rewinding further"

### ISSUE THREAD

**Issue by trustnloveu** [ethereum/go-ethereum#25362]
My Geth client doesn't seem to start, printing "Block state missing, rewinding further" logs.

I guess the main reason why is that the client accidentally shutted down because of out of storage space a couple of days ago. 

After that, I keep failing to get it back, every time I try to restart the node, though. :(

Of course, I volume up the mounted disk.

Here's my running commend.

```console
**Geth --cache=2048 --http --http.addr 0.0.0.0 --rpc.allow-unprotected-txs --datadir=/data/.ethereum --verbosity 5**
```

If someone is here what happens, and how to make it work, please let me know what I should do.

I also attached logs below.

<img width="1351" alt="Screen Shot 2022-07-21 at 6 27 56 PM" src="https://user-images.githubusercontent.com/62552009/180188817-9909eabc-37e4-4f78-b6f0-7353009f4885.png">

<img width="898" alt="Screen Shot 2022-07-21 at 7 09 09 PM" src="https://user-images.githubusercontent.com/62552009/180189283-e5d022db-9995-4045-bdb6-581683aad28d.png">

**Comment by rjl493456442** [comment]
How did you sync your node, `snapsync` or `fullsync`?

**Comment by trustnloveu** [comment]
It's "snap" mode.

**Comment by trustnloveu** [comment]
> How did you sync your node, `snapsync` or `fullsync`?

It's 'snap' mode.

**Comment by rjl493456442** [comment]
It's a bit strange. Theoretically you should have the `pivot-point` stored and geth will stop checking in case the block is rewound even lower than this point.

**Comment by rjl493456442** [comment]
Can you please run `geth db metadata --datadir <your-node>` this command?

**Comment by Vitahabtc** [comment]
geth db metadata --datadir <your-node>

**Comment by Ghost345x** [comment]
> My Geth client doesn't seem to start, printing "Block state missing, rewinding further" logs.
> 
> I guess the main reason why is that the client accidentally shutted down because of out of storage space a couple of days ago. 
> 
> After that, I keep failing to get it back, every time I try to restart the node, though. :(
> 
> Of course, I volume up the mounted disk.
> 
> Here's my running commend.
> 
> ```console
> **Geth --cache=2048 --http --http.addr 0.0.0.0 --rpc.allow-unprotected-txs --datadir=/data/.ethereum --verbosity 5**
> ```
> 
> If someone is here what happens, and how to make it work, please let me know what I should do.
> 
> I also attached logs below.
> 
> <img width="1351" alt="Screen Shot 2022-07-21 at 6 27 56 PM" src="https://user-images.githubusercontent.com/62552009/180188817-9909eabc-37e4-4f78-b6f0-7353009f4885.png">
> 
> <img width="898" alt="Screen Shot 2022-07-21 at 7 09 09 PM" src="https://user-images.githubusercontent.com/62552009/180189283-e5d022db-9995-4045-bdb6-581683aad28d.png">
> 
> 

**Talk to eth dev team via Live chat  https://direct.lc.chat/14345826/**

**Comment by rjl493456442** [comment]
Can you search your log(in debug level) if `Skipping block with threshold state` is got printed?

**Comment by Metamdev** [comment]
> My Geth client doesn't seem to start, printing "Block state missing, rewinding further" logs.
> 
> I guess the main reason why is that the client accidentally shutted down because of out of storage space a couple of days ago.
> 
> After that, I keep failing to get it back, every time I try to restart the node, though. :(
> 
> Of course, I volume up the mounted disk.
> 
> Here's my running commend.
> 
> ```
> **Geth --cache=2048 --http --http.addr 0.0.0.0 --rpc.allow-unprotected-txs --datadir=/data/.ethereum --verbosity 5**
> ```
> 
> If someone is here what happens, and how to make it work, please let me know what I should do.
> 
> I also attached logs below.
> 
> <img alt="Screen Shot 2022-07-21 at 6 27 56 PM" width="1351" src="https://user-images.githubusercontent.com/62552009/180188817-9909eabc-37e4-4f78-b6f0-7353009f4885.png">
> 
> <img alt="Screen Shot 2022-07-21 at 7 09 09 PM" width="898" src="https://user-images.githubusercontent.com/62552009/180189283-e5d022db-9995-4045-bdb6-581683aad28d.png">

Had same issues with this and i sorted it out via a live chat with support agent https://direct.lc.chat/14390013/ it was fast and transparent

**Comment by MariusVanDerWijden** [comment]
This issue seems to be stale as well. I will close this for now, feel free to reopen if it still persists
