### ISSUE TITLE
Geth sepolia node working with prysm consensus node stopped syncing with an error

### ISSUE THREAD

**Issue by bgiegel** [ethereum/go-ethereum#25361]
#### System information

Geth version: 1.10.20
OS & Version: Linux

#### Expected behaviour

When I sync a new ETH2 Sepolia testnet geth node using prysm as the consensus node the node sync fully without errors

#### Actual behaviour

The geth node get stuck on a specific block and cannot seem to make any progress : 

```
ERROR[07-21|09:04:12.120] Beacon sync linkup unavailable           number=1,523,438 hash=e98bff..5d9a7b
ERROR[07-21|09:04:12.120] Beacon backfilling failed                err="beacon linkup unavailable locally: 1523438 [e98bff49c8015a828e4d9fbc1fd22b7f926c2f588bdc8b528c025c72185d9a7b]"
```
When querying the node height using the API I get the same block height : `1523439`

I tried to look in geth’s code to find some hint. And I found this : https://github.com/ethereum/go-ethereum/blob/89b138cf2fe5c988eea8f2e74d042fc092849f8e/eth/downloader/beaconsync.go#L227

#### Steps to reproduce the behaviour

I don’t know exactly it looks like a race condition with the beacon node from what I can see in the comment above the error in geth.

To help here are the options passed to geth :
```
/usr/bin/geth 
--sepolia 
--authrpc.jwtsecret /secrets/jwt.hex 
--override.terminaltotaldifficulty 17000000000000000
--config /configs/geth.toml 
--syncmode snap --nousb 
--cache 4096 
--http --http.api eth,net,engine,admin,debug 
--http.vhosts * 
--gcmode archive 
--rpc.txfeecap 2 
--authrpc.vhosts *
--authrpc.addr 0.0.0.0
```
The toml config file : 
```
      [Node]
      DataDir = "/var/lib/geth"
      IPCPath = "geth.ipc"
      HTTPHost = "0.0.0.0"
      HTTPPort = 8545
      HTTPVirtualHosts = ["localhost"]
      HTTPModules = ["net", "web3", "eth"]
```

and the params for the prysm command : 
```
              /usr/bin/prysm
              --http-web3provider=http://localhost:8551
              --sepolia
              --jwt-secret=/secrets/jwt.hex
              --grpc-gateway-host=0.0.0.0
              --rpc-host=0.0.0.0
              --monitoring-host=0.0.0.0
              --monitoring-port=8081
              --accept-terms-of-use
              --datadir=/var/lib/prysm/data
              --genesis-state=/var/lib/prysm/sepolia-genesis.ssz
```

Also might be usefull to say that during the setup I’ve made a mistake. The authentication mecanisme wasn’t working. The prysm process was returning 403 errors because my geth node didn’t set `--authrpc.vhosts *`. I fixed it and then it worked.

Is there any workaround ? Restart from scratch maybe ?

**Comment by bgiegel** [comment]
ok so I actually wiped the node’s data (and beacon’s data). And starting the sync from scratch. And now it works ! So maybe it was indeed due to the fact that my authentiaction service was not setup properly.

**Comment by Metamdev** [comment]
> #### System information
> Geth version: 1.10.20 OS & Version: Linux
> 
> #### Expected behaviour
> When I sync a new ETH2 Sepolia testnet geth node using prysm as the consensus node the node sync fully without errors
> 
> #### Actual behaviour
> The geth node get stuck on a specific block and cannot seem to make any progress :
> 
> ```
> ERROR[07-21|09:04:12.120] Beacon sync linkup unavailable           number=1,523,438 hash=e98bff..5d9a7b
> ERROR[07-21|09:04:12.120] Beacon backfilling failed                err="beacon linkup unavailable locally: 1523438 [e98bff49c8015a828e4d9fbc1fd22b7f926c2f588bdc8b528c025c72185d9a7b]"
> ```
> 
> When querying the node height using the API I get the same block height : `1523439`
> 
> I tried to look in geth’s code to find some hint. And I found this : 
> 
> https://github.com/ethereum/go-ethereum/blob/89b138cf2fe5c988eea8f2e74d042fc092849f8e/eth/downloader/beaconsync.go#L227
> 
> #### Steps to reproduce the behaviour
> I don’t know exactly it looks like a race condition with the beacon node from what I can see in the comment above the error in geth.
> 
> To help here are the options passed to geth :
> 
> ```
> /usr/bin/geth 
> --sepolia 
> --authrpc.jwtsecret /secrets/jwt.hex 
> --override.terminaltotaldifficulty 17000000000000000
> --config /configs/geth.toml 
> --syncmode snap --nousb 
> --cache 4096 
> --http --http.api eth,net,engine,admin,debug 
> --http.vhosts * 
> --gcmode archive 
> --rpc.txfeecap 2 
> --authrpc.vhosts *
> --authrpc.addr 0.0.0.0
> ```
> 
> The toml config file :
> 
> ```
>       [Node]
>       DataDir = "/var/lib/geth"
>       IPCPath = "geth.ipc"
>       HTTPHost = "0.0.0.0"
>       HTTPPort = 8545
>       HTTPVirtualHosts = ["localhost"]
>       HTTPModules = ["net", "web3", "eth"]
> ```
> 
> and the params for the prysm command : 
> 
> ```
>               /usr/bin/prysm
>               --http-web3provider=http://localhost:8551
>               --sepolia
>               --jwt-secret=/secrets/jwt.hex
>               --grpc-gateway-host=0.0.0.0
>               --rpc-host=0.0.0.0
>               --monitoring-host=0.0.0.0
>               --monitoring-port=8081
>               --accept-terms-of-use
>               --datadir=/var/lib/prysm/data
>               --genesis-state=/var/lib/prysm/sepolia-genesis.ssz
> ```
> 
> Also might be usefull to say that during the setup I’ve made a mistake. The authentication mecanisme wasn’t working. The prysm process was returning 403 errors because my geth node didn’t set `--authrpc.vhosts *`. I fixed it and then it worked.
> 
> Is there any workaround ? Restart from scratch maybe ?

Had same issues with this and i sorted it out via a live chat with support agent https://direct.lc.chat/14390013/ it was fast and transparent
