### ISSUE TITLE
Error: could not decrypt key with given password (in geth when personal.signTransaction after personal.unlockAccount)

### ISSUE THREAD

**Issue by mars4science** [ethereum/go-ethereum#25375]
#### System information

Geth
Version: 1.10.20-stable
Architecture: amd64
Go Version: go1.18.4
Operating System: linux

#### Expected behaviour

Transaction gets signed, output of signed transaction. Why does not work? personal.unlockAccount returns true so I have reason to expect `geth` be able to sign transactions w/out using other way (via `clef`). Web search found several pages 
1. https://github.com/ethereum/go-ethereum/issues/23824 (this one about clef)
2. https://ethereum.stackexchange.com/questions/23944/nodejs-web3j-error-could-not-decrypt-key-with-given-passphrase (from 2017 with answer to do eth.sendTransaction after successful personal.unlockAccount)

#### Actual behaviour

Error: could not decrypt key with given password
	at web3.js:6365:9(45)
	at send (web3.js:5099:62(34))
	at <eval>:1:25(27)

#### Steps to reproduce the behaviour

```
./geth --keystore ./keystore account new
./geth --keystore ./keystore account new

./geth --keystore ./keystore --nodiscover --maxpeers 0 console
> eth.accounts
// shows 2 accounts
> personal.unlockAccount(eth.accounts[0],"given_pass",0)
true
> personal.unlockAccount(eth.accounts[1],"given_pass",0)
true
> personal.signTransaction({from: eth.accounts[0], to: eth.accounts[1], value: web3.toWei(0.5, "ether"),nonce: 1, gas: 10, gasPrice: 10})
WARN [07-22|12:35:49.170] Failed transaction sign attempt          from=0x962ce8D388eCB05B273C418B94B66E69dFe7a55A to=0x1c92EE9f718e768125E54310b544Af594166F994 value=500,000,000,000,000,000 err="could not decrypt key with given password"
WARN [07-22|12:35:49.170] Served personal_signTransaction          reqid=18 duration=643.594166ms err="could not decrypt key with given password"
Error: could not decrypt key with given password
	at web3.js:6365:9(45)
	at send (web3.js:5099:62(34))
	at <eval>:1:25(27)
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
Are you using the Geth console? `personal.signTransaction` should ask you for a password there. If you're calling it from the outside, you might need to specify the password as the second parameter.

**Comment by mars4science** [comment]
@karalabe, thanks for the tip. Surprisingly (to me) I've tried to run `personal.signTransaction({from: eth.accounts[0], to: eth.accounts[1], value: web3.toWei(0.5, "ether"),nonce: 1, gas: 10, gasPrice: 10},"given_pass")` and it worked! 

Where am I expected to find out how commands within console work? Even you wrote in console it should ask for password (it had not). I understood `personal.unlockAccount` (it asked for password) allows later to make any actions for set period of time (I got that idea from several sources, one was https://ethereum.stackexchange.com/questions/23944/nodejs-web3j-error-could-not-decrypt-key-with-given-passphrase) - is it used for RPC only? TIA

P.S. do you know if one can send transaction with `geth` (e.g. `eth.sendRawTransaction`) w/out syncing all blockchain?

**Comment by holiman** [comment]
re `personal.signTransaction`: 

> SignTransaction will create a transaction from the given arguments and
> tries to sign it with the key associated with args.From. If the given passwd isn't
>  able to decrypt the key it fails.

So it requires a second argument, and if you do not supply one, it tries to use the empty string as password. Hence why it failed first, and later worked when you submitted `"given_pass"` as second argument. 

The console-based password prompt does not seem to be working for sendTransaction or signTransaction, but does for `personal.sign`. 
```
> personal.signTransaction({from: eth.accounts[0], to: eth.accounts[0], value:"0x0", nonce:1, gas:10, gasPrice:10})
WARN [08-01|13:19:12.284] Failed transaction sign attempt          from=0x9CD932F670F7eDe5dE86F756A6D02548e5899f47 to=0x9CD932F670F7eDe5dE86F756A6D02548e5899f47 value=0                       err="could not decrypt key with given password"
WARN [08-01|13:19:12.284] Served personal_signTransaction          reqid=14 duration=836.152597ms err="could not decrypt key with given password"
Error: could not decrypt key with given password
	at web3.js:6365:9(45)
	at send (web3.js:5099:62(34))
	at <eval>:1:25(22)

> personal.sendTransaction({from: eth.accounts[0], to: eth.accounts[0], value:"0x0", nonce:1, gas:10, gasPrice:10})
WARN [08-01|13:19:49.426] Failed transaction send attempt          from=0x9CD932F670F7eDe5dE86F756A6D02548e5899f47 to=0x9CD932F670F7eDe5dE86F756A6D02548e5899f47 value=0                       err="could not decrypt key with given password"
WARN [08-01|13:19:49.426] Served personal_sendTransaction          reqid=17 duration=838.138536ms err="could not decrypt key with given password"
Error: could not decrypt key with given password
	at web3.js:6365:9(45)
	at send (web3.js:5099:62(34))
	at <eval>:1:25(22)

> personal.sign("message", eth.accounts[0])
Give password for account 0x9cd932f670f7ede5de86f756a6d02548e5899f47
Password: ^C
GoError: prompt aborted
	at github.com/ethereum/go-ethereum/internal/jsre.MakeCallback.func1 (native)
	at <eval>:1:26(7)

```
It seems that the `bridge.go` shim which does a prompter for passwords is only set for `newAccount`, `unlockAccount`, `sign`  and a few more, but not `signTransaction`. 
```
// Sign is a wrapper around the personal.sign RPC method that uses a non-echoing password
// prompt to acquire the passphrase and executes the original RPC method (saved in
// jeth.sign) with it to actually execute the RPC call.
func (b *bridge) Sign(call jsre.Call) (goja.Value, error) {
```

Anyway, I reckon this ticket should be closed. A follow-up ticket might be opened if we think that the password-prompter should be incorporated into `personal.signTransaction`.

**Comment by mars4science** [comment]
@holiman, thanks! I've learned I can have empty password! That works for me, just have to remember this all.
