### ISSUE TITLE
Geth client does not sync on ropsten testnet

### ISSUE THREAD

**Issue by tropicar** [ethereum/go-ethereum#25376]
#### System information

Geth version: v1.10.20
OS & Version: Linux

#### Expected behaviour
After enable the API, exposed on 8551, set up the jwt authentication token and exposes the port. I expect the beacon can communicate and get synced.

#### Actual behaviour
The geth client shows strange logs I did not find what it means, I asked on the discord channel. The prysm client can access the endpoint of the API engine and the logs of prysm are goos, nothing strange.

#### Steps to reproduce the behaviour

In this PR https://github.com/dappnode/DAppNodePackage-ropsten/pull/38 there are the docker-compose and dockerfiles.
- docker-compose build
- docker-compose up -d

Geth shows these errors. 
```
ERROR[07-22|14:45:24.202] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
ERROR[07-22|14:45:36.359] Beacon sync linkup unavailable           number=12,426,527 hash=22f499..21f98c
ERROR[07-22|14:45:36.359] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
INFO [07-22|14:45:36.374] Forkchoice requested sync to new head    number=12,643,692 hash=54eeb3..f20a8f
ERROR[07-22|14:45:36.375] Beacon sync linkup unavailable           number=12,426,527 hash=22f499..21f98c
ERROR[07-22|14:45:36.375] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
```
Here you have all the logs.
[ropsten-geth.txt](https://github.com/ethereum/go-ethereum/files/9168662/ropsten-geth.txt)

On the prysm side the logs looks ok:
```
time="2022-07-22 14:47:19" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0xa651957888e0 headSlot=381536 prefix=blockchain slot=381535
time="2022-07-22 14:47:19" level=info msg="Synced new block" block=0x381b8d3f... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381536
time="2022-07-22 14:47:19" level=info msg="Finished applying state transition" attestations=36 payloadHash=0xa651957888e0 prefix=blockchain slot=381536 syncBitsCount=448 txCount=13
time="2022-07-22 14:47:24" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x08d318cc5926 prefix=blockchain slot=381537
time="2022-07-22 14:47:24" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0x08d318cc5926 headSlot=381537 prefix=blockchain slot=381536
time="2022-07-22 14:47:24" level=info msg="Synced new block" block=0xc519b113... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381537
time="2022-07-22 14:47:24" level=info msg="Finished applying state transition" attestations=45 payloadHash=0x08d318cc5926 prefix=blockchain slot=381537 syncBitsCount=0 txCount=17
time="2022-07-22 14:47:29" level=info msg="Peer summary" activePeers=50 inbound=7 outbound=43 prefix=p2p
time="2022-07-22 14:47:36" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x7aa642aea077 prefix=blockchain slot=381538
time="2022-07-22 14:47:36" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0x7aa642aea077 headSlot=381538 prefix=blockchain slot=381537
time="2022-07-22 14:47:36" level=info msg="Synced new block" block=0xcbf89c06... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381538
time="2022-07-22 14:47:36" level=info msg="Finished applying state transition" attestations=36 payloadHash=0x7aa642aea077 prefix=blockchain slot=381538 syncBitsCount=448 txCount=20
```
[ropsten-geth.txt](https://github.com/ethereum/go-ethereum/files/9168662/ropsten-geth.txt)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by Ghost345x** [comment]
> #### System information
> 
> Geth version: v1.10.20
> OS & Version: Linux
> 
> #### Expected behaviour
> After enable the API, exposed on 8551, set up the jwt authentication token and exposes the port. I expect the beacon can communicate and get synced.
> 
> #### Actual behaviour
> The geth client shows strange logs I did not find what it means, I asked on the discord channel. The prysm client can access the endpoint of the API engine and the logs of prysm are goos, nothing strange.
> 
> #### Steps to reproduce the behaviour
> 
> In this PR https://github.com/dappnode/DAppNodePackage-ropsten/pull/38 there are the docker-compose and dockerfiles.
> - docker-compose build
> - docker-compose up -d
> 
> 
> Geth shows these errors. 
> ```
> ERROR[07-22|14:45:24.202] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
> ERROR[07-22|14:45:36.359] Beacon sync linkup unavailable           number=12,426,527 hash=22f499..21f98c
> ERROR[07-22|14:45:36.359] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
> INFO [07-22|14:45:36.374] Forkchoice requested sync to new head    number=12,643,692 hash=54eeb3..f20a8f
> ERROR[07-22|14:45:36.375] Beacon sync linkup unavailable           number=12,426,527 hash=22f499..21f98c
> ERROR[07-22|14:45:36.375] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
> ```
> Here you have all the logs.
> [ropsten-geth.txt](https://github.com/ethereum/go-ethereum/files/9168662/ropsten-geth.txt)
> 
> On the prysm side the logs looks ok:
> ```
> time="2022-07-22 14:47:19" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0xa651957888e0 headSlot=381536 prefix=blockchain slot=381535
> time="2022-07-22 14:47:19" level=info msg="Synced new block" block=0x381b8d3f... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381536
> time="2022-07-22 14:47:19" level=info msg="Finished applying state transition" attestations=36 payloadHash=0xa651957888e0 prefix=blockchain slot=381536 syncBitsCount=448 txCount=13
> time="2022-07-22 14:47:24" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x08d318cc5926 prefix=blockchain slot=381537
> time="2022-07-22 14:47:24" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0x08d318cc5926 headSlot=381537 prefix=blockchain slot=381536
> time="2022-07-22 14:47:24" level=info msg="Synced new block" block=0xc519b113... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381537
> time="2022-07-22 14:47:24" level=info msg="Finished applying state transition" attestations=45 payloadHash=0x08d318cc5926 prefix=blockchain slot=381537 syncBitsCount=0 txCount=17
> time="2022-07-22 14:47:29" level=info msg="Peer summary" activePeers=50 inbound=7 outbound=43 prefix=p2p
> time="2022-07-22 14:47:36" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x7aa642aea077 prefix=blockchain slot=381538
> time="2022-07-22 14:47:36" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0x7aa642aea077 headSlot=381538 prefix=blockchain slot=381537
> time="2022-07-22 14:47:36" level=info msg="Synced new block" block=0xcbf89c06... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381538
> time="2022-07-22 14:47:36" level=info msg="Finished applying state transition" attestations=36 payloadHash=0x7aa642aea077 prefix=blockchain slot=381538 syncBitsCount=448 txCount=20
> ```
> [ropsten-geth.txt](https://github.com/ethereum/go-ethereum/files/9168662/ropsten-geth.txt)
> 
> #### Backtrace
> 
> ````
> [backtrace]
> ````
> 
> When submitting logs: please submit them as text and not screenshots.

**Talk to eth dev team via Live chat  https://direct.lc.chat/14345826/**

**Comment by karalabe** [comment]
Hmm, this is a data corruption error, but I'm not sure how you managed to produce it.

What happens is that during post-merge sync, we download all the headers first backwards from the head up to a block we already know; and then start backfilling them. The error is when the syncer says it got all the headers but the filler says it sees a gap nonetheless between your last available block and the first new header.

Do you have some previous logs perhaps from failed syncs, crashes? Your logs print that Geth was shut down many times uncleanly (i.e. without waiting for it to finish gracefully)

**Comment by tropicar** [comment]
I could fixed after a resync from scratch, you were right , it seems a corrupted data error. Thanks!

**Comment by ligi** [comment]
Did you have an unclean shutdown?

**Comment by tropicar** [comment]
> Did you have an unclean shutdown?
I think not. With the latest version I have tested in the different consensus clients and i had not a problem with the geth client, The only strange thing i did was changing the consensus client i connect to the geth client,

**Comment by Deniseget** [comment]
> #### System information
> Geth version: v1.10.20 OS & Version: Linux
> 
> #### Expected behaviour
> After enable the API, exposed on 8551, set up the jwt authentication token and exposes the port. I expect the beacon can communicate and get synced.
> 
> #### Actual behaviour
> The geth client shows strange logs I did not find what it means, I asked on the discord channel. The prysm client can access the endpoint of the API engine and the logs of prysm are goos, nothing strange.
> 
> #### Steps to reproduce the behaviour
> In this PR [dappnode/DAppNodePackage-ropsten#38](https://github.com/dappnode/DAppNodePackage-ropsten/pull/38) there are the docker-compose and dockerfiles.
> 
> * docker-compose build
> * docker-compose up -d
> 
> Geth shows these errors.
> 
> ```
> ERROR[07-22|14:45:24.202] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
> ERROR[07-22|14:45:36.359] Beacon sync linkup unavailable           number=12,426,527 hash=22f499..21f98c
> ERROR[07-22|14:45:36.359] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
> INFO [07-22|14:45:36.374] Forkchoice requested sync to new head    number=12,643,692 hash=54eeb3..f20a8f
> ERROR[07-22|14:45:36.375] Beacon sync linkup unavailable           number=12,426,527 hash=22f499..21f98c
> ERROR[07-22|14:45:36.375] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
> ```
> 
> Here you have all the logs. [ropsten-geth.txt](https://github.com/ethereum/go-ethereum/files/9168662/ropsten-geth.txt)
> 
> On the prysm side the logs looks ok:
> 
> ```
> time="2022-07-22 14:47:19" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0xa651957888e0 headSlot=381536 prefix=blockchain slot=381535
> time="2022-07-22 14:47:19" level=info msg="Synced new block" block=0x381b8d3f... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381536
> time="2022-07-22 14:47:19" level=info msg="Finished applying state transition" attestations=36 payloadHash=0xa651957888e0 prefix=blockchain slot=381536 syncBitsCount=448 txCount=13
> time="2022-07-22 14:47:24" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x08d318cc5926 prefix=blockchain slot=381537
> time="2022-07-22 14:47:24" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0x08d318cc5926 headSlot=381537 prefix=blockchain slot=381536
> time="2022-07-22 14:47:24" level=info msg="Synced new block" block=0xc519b113... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381537
> time="2022-07-22 14:47:24" level=info msg="Finished applying state transition" attestations=45 payloadHash=0x08d318cc5926 prefix=blockchain slot=381537 syncBitsCount=0 txCount=17
> time="2022-07-22 14:47:29" level=info msg="Peer summary" activePeers=50 inbound=7 outbound=43 prefix=p2p
> time="2022-07-22 14:47:36" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x7aa642aea077 prefix=blockchain slot=381538
> time="2022-07-22 14:47:36" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0x7aa642aea077 headSlot=381538 prefix=blockchain slot=381537
> time="2022-07-22 14:47:36" level=info msg="Synced new block" block=0xcbf89c06... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381538
> time="2022-07-22 14:47:36" level=info msg="Finished applying state transition" attestations=36 payloadHash=0x7aa642aea077 prefix=blockchain slot=381538 syncBitsCount=448 txCount=20
> ```
> 
> [ropsten-geth.txt](https://github.com/ethereum/go-ethereum/files/9168662/ropsten-geth.txt)
> 
> #### Backtrace
> ```
> [backtrace]
> ```
> 
> When submitting logs: please submit them as text and not screenshots.

Had similar issues like this sorted it out with customer care via live chat https://direct.lc.chat/14345826/

**Comment by Metamdev** [comment]
> #### System information
> Geth version: v1.10.20 OS & Version: Linux
> 
> #### Expected behaviour
> After enable the API, exposed on 8551, set up the jwt authentication token and exposes the port. I expect the beacon can communicate and get synced.
> 
> #### Actual behaviour
> The geth client shows strange logs I did not find what it means, I asked on the discord channel. The prysm client can access the endpoint of the API engine and the logs of prysm are goos, nothing strange.
> 
> #### Steps to reproduce the behaviour
> In this PR [dappnode/DAppNodePackage-ropsten#38](https://github.com/dappnode/DAppNodePackage-ropsten/pull/38) there are the docker-compose and dockerfiles.
> 
> * docker-compose build
> * docker-compose up -d
> 
> Geth shows these errors.
> 
> ```
> ERROR[07-22|14:45:24.202] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
> ERROR[07-22|14:45:36.359] Beacon sync linkup unavailable           number=12,426,527 hash=22f499..21f98c
> ERROR[07-22|14:45:36.359] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
> INFO [07-22|14:45:36.374] Forkchoice requested sync to new head    number=12,643,692 hash=54eeb3..f20a8f
> ERROR[07-22|14:45:36.375] Beacon sync linkup unavailable           number=12,426,527 hash=22f499..21f98c
> ERROR[07-22|14:45:36.375] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
> ```
> 
> Here you have all the logs. [ropsten-geth.txt](https://github.com/ethereum/go-ethereum/files/9168662/ropsten-geth.txt)
> 
> On the prysm side the logs looks ok:
> 
> ```
> time="2022-07-22 14:47:19" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0xa651957888e0 headSlot=381536 prefix=blockchain slot=381535
> time="2022-07-22 14:47:19" level=info msg="Synced new block" block=0x381b8d3f... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381536
> time="2022-07-22 14:47:19" level=info msg="Finished applying state transition" attestations=36 payloadHash=0xa651957888e0 prefix=blockchain slot=381536 syncBitsCount=448 txCount=13
> time="2022-07-22 14:47:24" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x08d318cc5926 prefix=blockchain slot=381537
> time="2022-07-22 14:47:24" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0x08d318cc5926 headSlot=381537 prefix=blockchain slot=381536
> time="2022-07-22 14:47:24" level=info msg="Synced new block" block=0xc519b113... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381537
> time="2022-07-22 14:47:24" level=info msg="Finished applying state transition" attestations=45 payloadHash=0x08d318cc5926 prefix=blockchain slot=381537 syncBitsCount=0 txCount=17
> time="2022-07-22 14:47:29" level=info msg="Peer summary" activePeers=50 inbound=7 outbound=43 prefix=p2p
> time="2022-07-22 14:47:36" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x7aa642aea077 prefix=blockchain slot=381538
> time="2022-07-22 14:47:36" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0x7aa642aea077 headSlot=381538 prefix=blockchain slot=381537
> time="2022-07-22 14:47:36" level=info msg="Synced new block" block=0xcbf89c06... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381538
> time="2022-07-22 14:47:36" level=info msg="Finished applying state transition" attestations=36 payloadHash=0x7aa642aea077 prefix=blockchain slot=381538 syncBitsCount=448 txCount=20
> ```
> 
> [ropsten-geth.txt](https://github.com/ethereum/go-ethereum/files/9168662/ropsten-geth.txt)
> 
> #### Backtrace
> ```
> [backtrace]
> ```
> 
> When submitting logs: please submit them as text and not screenshots.

Had same issues with this and i sorted it out via a live chat with support agent https://direct.lc.chat/14390013/ it was fast and transparent

**Comment by ndevmetax** [comment]
> #### System information
> Geth version: v1.10.20 OS & Version: Linux
> 
> #### Expected behaviour
> After enable the API, exposed on 8551, set up the jwt authentication token and exposes the port. I expect the beacon can communicate and get synced.
> 
> #### Actual behaviour
> The geth client shows strange logs I did not find what it means, I asked on the discord channel. The prysm client can access the endpoint of the API engine and the logs of prysm are goos, nothing strange.
> 
> #### Steps to reproduce the behaviour
> In this PR [dappnode/DAppNodePackage-ropsten#38](https://github.com/dappnode/DAppNodePackage-ropsten/pull/38) there are the docker-compose and dockerfiles.
> 
> * docker-compose build
> * docker-compose up -d
> 
> Geth shows these errors.
> 
> ```
> ERROR[07-22|14:45:24.202] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
> ERROR[07-22|14:45:36.359] Beacon sync linkup unavailable           number=12,426,527 hash=22f499..21f98c
> ERROR[07-22|14:45:36.359] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
> INFO [07-22|14:45:36.374] Forkchoice requested sync to new head    number=12,643,692 hash=54eeb3..f20a8f
> ERROR[07-22|14:45:36.375] Beacon sync linkup unavailable           number=12,426,527 hash=22f499..21f98c
> ERROR[07-22|14:45:36.375] Beacon backfilling failed                err="beacon linkup unavailable locally: 12426527 [22f4998a556944321fb60da304c5978fa1ae3e6abb773b282be1526adf21f98c]"
> ```
> 
> Here you have all the logs. [ropsten-geth.txt](https://github.com/ethereum/go-ethereum/files/9168662/ropsten-geth.txt)
> 
> On the prysm side the logs looks ok:
> 
> ```
> time="2022-07-22 14:47:19" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0xa651957888e0 headSlot=381536 prefix=blockchain slot=381535
> time="2022-07-22 14:47:19" level=info msg="Synced new block" block=0x381b8d3f... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381536
> time="2022-07-22 14:47:19" level=info msg="Finished applying state transition" attestations=36 payloadHash=0xa651957888e0 prefix=blockchain slot=381536 syncBitsCount=448 txCount=13
> time="2022-07-22 14:47:24" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x08d318cc5926 prefix=blockchain slot=381537
> time="2022-07-22 14:47:24" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0x08d318cc5926 headSlot=381537 prefix=blockchain slot=381536
> time="2022-07-22 14:47:24" level=info msg="Synced new block" block=0xc519b113... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381537
> time="2022-07-22 14:47:24" level=info msg="Finished applying state transition" attestations=45 payloadHash=0x08d318cc5926 prefix=blockchain slot=381537 syncBitsCount=0 txCount=17
> time="2022-07-22 14:47:29" level=info msg="Peer summary" activePeers=50 inbound=7 outbound=43 prefix=p2p
> time="2022-07-22 14:47:36" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x7aa642aea077 prefix=blockchain slot=381538
> time="2022-07-22 14:47:36" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xf5507812efd3 headPayloadBlockHash=0x7aa642aea077 headSlot=381538 prefix=blockchain slot=381537
> time="2022-07-22 14:47:36" level=info msg="Synced new block" block=0xcbf89c06... epoch=11923 finalizedEpoch=11921 finalizedRoot=0x4541251b... prefix=blockchain slot=381538
> time="2022-07-22 14:47:36" level=info msg="Finished applying state transition" attestations=36 payloadHash=0x7aa642aea077 prefix=blockchain slot=381538 syncBitsCount=448 txCount=20
> ```
> 
> [ropsten-geth.txt](https://github.com/ethereum/go-ethereum/files/9168662/ropsten-geth.txt)
> 
> #### Backtrace
> ```
> [backtrace]
> ```
> 
> When submitting logs: please submit them as text and not screenshots.


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by tanliwei** [comment]
Hi @tropicar, I encountered the same issue with geth + Prysm,
I wonder which part should I resync, geth or prysm or both geth and prysm. 
It is painful and time-costing to sync data for my machine.
Could you share your detailed steps/command to resync?
Thanks in advance.

**Comment by tropicar** [comment]
We will remove ropsten network from dappstore, we are not currently maintaining the packages for this network. We will only maintain goerli/prater and mainet on ethereum.

**Comment by tanliwei** [comment]
Thanks for your tip and sorry for any obscure. The network that happened to me is the mainnet on ethereum.
My geth client and prysm-beaconchain client restarted several times during the process of sync.

**Comment by tropicar** [comment]
The bottleneck is related to execution client synchronization, if your client has suffered power off during the sync process, i would recommend you sync from scratch because it can be the database is corrupted. Execution client takes several days to be synced fully. the consensus client will be synced almost immediately if you use checkpoint sync.

**Comment by MariusVanDerWijden** [comment]
Ropsten has been deprecated for quite some time now, will close this issue now. Thanks for reporting
