### ISSUE TITLE
puppeth setup blockchain

### ISSUE THREAD

**Issue by cryptonana** [ethereum/go-ethereum#25386]
hello i use puppeth to setup own blockchain but any one tell me how i change name to my own coin means i want change ticker ETH with my own coin name like CAT how can i do please help me

**Comment by Ghost345x** [comment]
> hello i use puppeth to setup own blockchain but any one tell me how i change name to my own coin means i want change ticker ETH with my own coin name like CAT how can i do please help me

**Talk to eth dev team via Live chat  https://direct.lc.chat/14345826/**

**Comment by karalabe** [comment]
You can't :)

**Comment by cryptonana** [comment]
> You can't :)

why how ppl do it

**Comment by darkegn** [comment]
dude this is not a token but a blockchain chain here eth,etc you don't specify any name. You create a new blockchain chain with puppeth, this chain does not have a name in the internal structure, you can say it to the wallets in the external structure. rpc:rpc.yourcoinname  network:yourcoinname.network" blockhainNetwork = you coin name"
