### ISSUE TITLE
Geth Command failed 

### ISSUE THREAD

**Issue by lvgang214** [ethereum/go-ethereum#25393]
Start the testnet with geth，But it will show an error，invalid command: "go"，I have configured GO environment
Use geth version ，result as follows：
Geth
Version: 1.10.20-stable
Git Commit: 8f2416a89a3def6ec2c749d5afafbf2c9a18e3c8
Git Commit Date: 20220629
Architecture: amd64
Go Version: go1.18.1
Operating System: linux
GOPATH=/home/ubuntu/go
GOROOT=/usr/local/go

**Comment by MariusVanDerWijden** [comment]
Can you paste the command you use to start geth?

**Comment by lvgang214** [comment]
> Can you paste the command you use to start geth?

this command: geth --ropsten --datadir /home/ubuntu/.ropsten --maxpeers 250 --txpool.globalslots 1000 --mine  --miner.etherbase '0x***********56d' --miner.extradata 'MyMiningPool' --http --http.corsdomain * --http.addr Intranet IP --http.port 9999 --http.api admin,debug,eth,miner,net,personal,txpool,web3

**Comment by karalabe** [comment]
If `geth version` works, I don't see why your later command wouldn't. What's the output? I don't see where `go` could come from.

**Comment by lvgang214** [comment]
> If `geth version` works, I don't see why your later command wouldn't. What's the output? I don't see where `go` could come from.
the output is :invalid command: "go"

**Comment by karalabe** [comment]
That cannot be because nothing is starting `go`, something in your command is off

**Comment by karalabe** [comment]
I'm guessing you need to place the `*` in single quotes in `--http.corsdomain *`, otherwise it expands it with the files in your current folder.
