### ISSUE TITLE
I can't get geth to sync

### ISSUE THREAD

**Issue by GamerKurisu** [ethereum/go-ethereum#25396]
This is so frustrating, tried setting head back multiple times, still won't sync any further
![image](https://user-images.githubusercontent.com/44711880/180769621-f4318c41-9c40-4f1e-82fc-9f88f6df60bf.png)

#### System information

Geth version: `1.10.20`
OS & Version: Windows
Commit hash : (if `develop`)

#### Expected behaviour
to sync

#### Actual behaviour
won't sync past block 15199807, it states 15199808 is a bad block with merkle root error

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.
[issue.txt](https://github.com/ethereum/go-ethereum/files/9180756/issue.txt)

**Comment by GamerKurisu** [comment]
Error message I get is attached

**Comment by MariusVanDerWijden** [comment]
Hmm looks like a fried database, do you have unclean shutdown markers?

**Comment by GamerKurisu** [comment]
> 
Firstly thank you very much for reply, this is from the start, when I tried sethead before it was about 2w ago, could setting head to 1mo4w2d fix this?

![image](https://user-images.githubusercontent.com/44711880/180786029-55448cd8-edab-49ed-a360-92523c23659a.png)

**Comment by MariusVanDerWijden** [comment]
No a sethead can not fix a broken database, you need to remove the state database: `geth removedb` `y` `n`. This will remove the state but not the history. Then you need to resync the state

**Comment by ligi** [comment]
did you have an unclean shutdown?

**Comment by Deniseget** [comment]
> This is so frustrating, tried setting head back multiple times, still won't sync any further ![image](https://user-images.githubusercontent.com/44711880/180769621-f4318c41-9c40-4f1e-82fc-9f88f6df60bf.png)
> 
> #### System information
> Geth version: `1.10.20` OS & Version: Windows Commit hash : (if `develop`)
> 
> #### Expected behaviour
> to sync
> 
> #### Actual behaviour
> won't sync past block 15199807, it states 15199808 is a bad block with merkle root error
> 
> #### Steps to reproduce the behaviour
> #### Backtrace
> ```
> [backtrace]
> ```
> 
> When submitting logs: please submit them as text and not screenshots. [issue.txt](https://github.com/ethereum/go-ethereum/files/9180756/issue.txt)

Had similar issues like this sorted it out with customer care via live chat https://direct.lc.chat/14345826/

**Comment by bfgasparin** [comment]
Same issue with me. Th node is not syncing:

<img width="232" alt="image" src="https://user-images.githubusercontent.com/4076928/183224826-957b617f-8f84-4728-9757-053184592cda.png">


Also the node is constantly crashing and restart (almost every 5min). I can see a log of "unclean shutdowns detected" in the log.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/4076928/183224902-496a69af-4f55-488a-b8fc-2a74518b198a.png">


I can't figure out what is causing the node to crash.

Node version: v1.10.20.

I updated to v1.10.21 and same issue.

**Comment by bfgasparin** [comment]
@MariusVanDerWijden how to resync the state?

**Comment by bfgasparin** [comment]
I am pretty sure the node was working and syncing perfectly until 2 day ago. I know it synced until at least the block 15269251. But now, it shows the current block is 15242873 and get stuck, and crashing constantly every 5min.

Any idea what is happening? I thought initially it could be full HD storage, but the storage has a lot of available space.

**Comment by Metamdev** [comment]
> This is so frustrating, tried setting head back multiple times, still won't sync any further ![image](https://user-images.githubusercontent.com/44711880/180769621-f4318c41-9c40-4f1e-82fc-9f88f6df60bf.png)
> 
> #### System information
> Geth version: `1.10.20` OS & Version: Windows Commit hash : (if `develop`)
> 
> #### Expected behaviour
> to sync
> 
> #### Actual behaviour
> won't sync past block 15199807, it states 15199808 is a bad block with merkle root error
> 
> #### Steps to reproduce the behaviour
> #### Backtrace
> ```
> [backtrace]
> ```
> 
> When submitting logs: please submit them as text and not screenshots. [issue.txt](https://github.com/ethereum/go-ethereum/files/9180756/issue.txt)

Had same issues with this and i sorted it out via a live chat with support agent https://direct.lc.chat/14390013/ it was fast and transparent

**Comment by ndevmetax** [comment]
> This is so frustrating, tried setting head back multiple times, still won't sync any further ![image](https://user-images.githubusercontent.com/44711880/180769621-f4318c41-9c40-4f1e-82fc-9f88f6df60bf.png)
> 
> #### System information
> Geth version: `1.10.20` OS & Version: Windows Commit hash : (if `develop`)
> 
> #### Expected behaviour
> to sync
> 
> #### Actual behaviour
> won't sync past block 15199807, it states 15199808 is a bad block with merkle root error
> 
> #### Steps to reproduce the behaviour
> #### Backtrace
> ```
> [backtrace]
> ```
> 
> When submitting logs: please submit them as text and not screenshots. [issue.txt](https://github.com/ethereum/go-ethereum/files/9180756/issue.txt)


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by bfgasparin** [comment]
I could fix my issue. In my case, it was a memory issue. I had only 8GB of RAM initially. I moved to the node to a hardware with 16GB RAM and the node stopped crashing.

**Comment by MariusVanDerWijden** [comment]
This issue has also become pretty stale, esp since after the merge the sync mechanism is different. Please open another issue if this is still a problem
