### ISSUE TITLE
CPU usage trippelt after upgrade to v1.10.20

### ISSUE THREAD

**Issue by bert2002** [ethereum/go-ethereum#25404]
#### System information

```
# geth version
Geth
Version: 1.10.20-stable
Git Commit: 8f2416a89a3def6ec2c749d5afafbf2c9a18e3c8
Git Commit Date: 20220629
Architecture: amd64
Go Version: go1.18.1
Operating System: linux
GOPATH=
GOROOT=go
```

After the upgrade we are seeing the cpu usage increased threefold. Our `geth` nodes were running happily on 2-3 cores, but since the upgrade it is using more and more. It doubled the usage within a couple days which is odd. 
![Screenshot from 2022-07-26 10-00-56](https://user-images.githubusercontent.com/1042226/180909336-5ea3aa42-bb18-4668-aca6-7134637d1629.png)
This is the load average of 1m.

Please let me know what else I can provide to give more insights. This is a real problem for us :cry: 

Thanks,
bert

**Comment by karalabe** [comment]
There was a small regression in leveldb in 1.10.20, I'm unsure if this is caused by that or not. We're currently prepping to release 1.10.21, so you might want to check if that fixes it for you.

**Comment by bert2002** [comment]
Hi @karalabe, after ~5 days it normalized in mainnet now without any of our doing.
On ropsten we saw the same behavior, but downgraded after a couple of hours again and the load average was back to normal. A day later we upgraded ropsten to the latest again and we could not experience the same problem. It doesnt make sense to me, but maybe for you in regard to the regression?
We will try `1.20.21` on testnet when its out :)

**Comment by Deniseget** [comment]
> #### System information
> ```
> # geth version
> Geth
> Version: 1.10.20-stable
> Git Commit: 8f2416a89a3def6ec2c749d5afafbf2c9a18e3c8
> Git Commit Date: 20220629
> Architecture: amd64
> Go Version: go1.18.1
> Operating System: linux
> GOPATH=
> GOROOT=go
> ```
> 
> After the upgrade we are seeing the cpu usage increased threefold. Our `geth` nodes were running happily on 2-3 cores, but since the upgrade it is using more and more. It doubled the usage within a couple days which is odd. ![Screenshot from 2022-07-26 10-00-56](https://user-images.githubusercontent.com/1042226/180909336-5ea3aa42-bb18-4668-aca6-7134637d1629.png) This is the load average of 1m.
> 
> Please let me know what else I can provide to give more insights. This is a real problem for us 😢
> 
> Thanks, bert

Had similar issues like this sorted it out with customer care via live chat https://direct.lc.chat/14345826/

**Comment by karalabe** [comment]
Please check with current versions and report if anything feels off. Note, initially it might be a bit wonky as 1.10.20 might have accumulated some junk that .21 needs to clean up. Shouldn't persist more than a couple mins IMO.
