### ISSUE TITLE
i have a problem with  "go get github.com/ethereum/go-ethereum/ethclient"

### ISSUE THREAD

**Issue by seyedsalar** [ethereum/go-ethereum#25402]
#### System information

**Geth version: `latest version `
OS & Version: Linux ubuntu 22.04
Go version : go 1.18beta1**

when i run following code : " _go get github.com/ethereum/go-ethereum/ethclient_"

face with this error :

**github.com/ethereum/go-ethereum/rpc
src/github.com/ethereum/go-ethereum/rpc/server.go:49:11: cannot use generic type mapset.Set[T comparable] without instantiation
src/github.com/ethereum/go-ethereum/rpc/server.go:54:69: cannot infer T (/home/dramintoosi/go/src/github.com/deckarep/golang-set/set.go:180:13)
src/github.com/ethereum/go-ethereum/rpc/websocket.go:72:26: cannot infer T (/home/dramintoosi/go/src/github.com/deckarep/golang-set/set.go:180:13)
src/github.com/ethereum/go-ethereum/rpc/websocket.go:125:37: cannot use generic type mapset.Set[T comparable] without instantiation**

in https://github.com/ethereum/go-ethereum/issues/24903 talked about "switche golang-set back to 1.8.0", but i dont know how, when and where switch that? have "go get" any option for that?

**Comment by s1na** [comment]
I think you need to use [go modules](https://go.dev/blog/using-go-modules) as suggested in the ticket.

**Comment by karalabe** [comment]
If you're using ethclient as a library in your own project, please ensure your project is using Go modules (go mod init) and do the go get afterwards. You might need to add a version specified at the end (.e. @latest). Also Go 1.18 was released many months ago, you really should not use beta1 of it.

**Comment by seyedsalar** [comment]
My problem has been solved with manually replacement of deckarep/golang-set v1.7.1 with   default latest version of that in go-ethereum folder (in fact, v 2.1.0 cause this error).
