### ISSUE TITLE
RPC: eth_sign is broken on 1.4.3

### ISSUE THREAD

**Issue by sammy007** [ethereum/go-ethereum#2540]
#### System information

Geth version: `1.4.3`
OS & Version: OSX

#### Expected behaviour

{
  "id":1,
  "jsonrpc": "2.0",
  "result": "0x2ac19db245478a06032e69cdbd2b54e648b78431d0a47bd1fbab18f79f820ba407466e37adbe9e84541cab97ab7d290f4a64a5825c876d22109f3bf813254e8601"
}

https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign

#### Actual behaviour

{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"common: unmarshalJSON failed: hash must be exactly 32 bytes"}}

#### Steps to reproduce the behaviour

Upgraded to 1.4.3 from 1.3.6 curl -X POST http://127.0.0.1:8545 -d '{"jsonrpc":"2.0","method":"eth_sign","params":["0xd1ade25ccd3d550a7eb532ac759cac7be09c2719", "Schoolbus"],"id":1}'

**Comment by sammy007** [comment]
Ok I managed to sign by providing 32 bytes hash, please update example in wiki.

**Comment by zbalkic** [comment]
Still having the issue with signatures on 1.4+ 1.5+
Is there official fix for this?
