### ISSUE TITLE
puppeth nginx issue

### ISSUE THREAD

**Issue by cryptonana** [ethereum/go-ethereum#25409]
i setup new blockchain but problem is puppeth not create nginx for explorer and explorer no more work how can i fix this issue please help needit

**Comment by holiman** [comment]
Nobody can provide help if you do not provide context. Context can be, 
- what did you do? which commands did you run? 
- What happened? What did the logs say? 
- What exactly did not work as expected?

**Comment by cryptonana** [comment]
thanks for your reply i use puppeth to setup new chain with explorer ethstate and status but problem is i dont see puppeth setup nginx explorer not working and nginx not installed by puppeth

**Comment by karalabe** [comment]
Nginx requires virtual hosts (i.e. domains assigned). If you're doing everything via IP addresses, you can't multiplex multiple service on the same HTTP port. Should still work via ports directly though.

**Comment by karalabe** [comment]
I.e. there's no point to add ngingx if there are no vhosts/domains to use it. That's why it doesn't deploy it.

**Comment by cryptonana** [comment]
> Nginx requires virtual hosts (i.e. domains assigned). If you're doing everything via IP addresses, you can't multiplex multiple service on the same HTTP port. Should still work via ports directly though.

how can i assigned? domain, i use terminal to use puppeth

**Comment by cryptonana** [comment]
> I.e. there's no point to add ngingx if there are no vhosts/domains to use it. That's why it doesn't deploy it.

yes i use multiple services and nginx installed but explorer show "502 Bad Gateway" in browser
![Untitled-3](https://user-images.githubusercontent.com/40866572/181466905-0f7eb439-ffe1-4901-ba24-66fe1ce10e0d.png)

see this how can resolve

![Untitled-4](https://user-images.githubusercontent.com/40866572/181466958-9eac10ee-d8df-4116-ba9e-26f432d21cfe.png)

**Comment by karalabe** [comment]
Opening duplicate issues won't get is solved faster. please read up on virtual hosts, nginx, domains, etc
