### ISSUE TITLE
Impossible reorg

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum/go-ethereum#25412]
ERROR[07-25|21:20:40.667] Impossible reorg, please file an issue   oldnum=128 oldhash=d88ee3..e9638d oldblocks=0 newnum=128 newhash=d88ee3..e9638d newblocks=0

This pops up every now and then, reorg to current block, just ignore and don't print this line

**Comment by karalabe** [comment]
No no, don't ignore, that's just hiding the symptom. The reason we have that error is because it must not happen. If it happens something's wrong.

**Comment by Deniseget** [comment]
> ERROR[07-25|21:20:40.667] Impossible reorg, please file an issue oldnum=128 oldhash=d88ee3..e9638d oldblocks=0 newnum=128 newhash=d88ee3..e9638d newblocks=0
> 
> This pops up every now and then, reorg to current block, just ignore and don't print this line

Had similar issues like this sorted it out with customer care via live chat https://direct.lc.chat/14345826/
