### ISSUE TITLE
puppeth metamask firefox issue

### ISSUE THREAD

**Issue by cryptonana** [ethereum/go-ethereum#25429]
hello i face issue with metamask i create blockchain all working fine, in chrome i add rpc url with chainid in metamask its work fine but in firefox same method i apply its only show loading
![Untitled-5](https://user-images.githubusercontent.com/40866572/181518193-066d337d-fee6-4a87-b9e7-069107f3210d.png)

in firefox when i try to add chainid its show me this error but in chorm all work fine

![Untitled-7](https://user-images.githubusercontent.com/40866572/181524592-c0179be7-52a3-43e3-9739-520fc3ed6304.png)
can someone help me how to fix this issue

in chrome its work fine

![Untitled-6](https://user-images.githubusercontent.com/40866572/181523575-9f6b0022-68f6-4043-b307-b5179dd224ae.png)

**Comment by s1na** [comment]
That sounds like a metamask issue. Please file it in their repo.
