### ISSUE TITLE
Eth-merge: `eth_feeHistory` crashes when `finalized` block is passed

### ISSUE THREAD

**Issue by lorenzourb** [ethereum/go-ethereum#25420]
#### System information

Geth version: `Geth/v1.10.19-omnibus-1fd05ab6/linux-amd64/go1.18.3` our Infura geth fork
OS & Version: Linux
Commit hash : release

#### Expected behavior
Should return the feeHistory

#### Actual behaviour
Returns 
`{
   jsonrpc: '2.0',
      id: 1337,
      error: { code: -32000, message: 'method handler crashed' }
    }`

#### Steps to reproduce the behaviour
Called against our Infura/Sepolia Geth nodes with
`  {
 id: 1337,
      jsonrpc: '2.0',
      method: 'eth_feeHistory',
      params: [ '0x5', 'finalized', [] ]
    }`

**Comment by Deniseget** [comment]
> #### System information
> Geth version: `Geth/v1.10.19-omnibus-1fd05ab6/linux-amd64/go1.18.3` our Infura geth fork OS & Version: Linux Commit hash : release
> 
> #### Expected behavior
> Should return the feeHistory
> 
> #### Actual behaviour
> Returns `{ jsonrpc: '2.0', id: 1337, error: { code: -32000, message: 'method handler crashed' } }`
> 
> #### Steps to reproduce the behaviour
> Called against our Infura/Sepolia Geth nodes with ` { id: 1337, jsonrpc: '2.0', method: 'eth_feeHistory', params: [ '0x5', 'finalized', [] ] }`

Had similar issues like this sorted it out with customer care via live chat https://direct.lc.chat/14345826/
