### ISSUE TITLE
[puppeth] deployed explorer always response 502 bad gateway

### ISSUE THREAD

**Issue by atomdax** [ethereum/go-ethereum#25434]
System information

Geth version: Version: 1.10.21-stable Go Version: go1.18.4
OS & Version: Linux
Commit hash : (if develop)
Expected behaviour

Show explorer page
Actual behaviour

502 Bad Gateway
Steps to reproduce the behaviour

Deploy explorer with puppeth
Etc.

Node for explorer is successfully deploy, and shown in ethstats. i setup explorer via puppeth

![Untitled-8](https://user-images.githubusercontent.com/81478011/181648426-87b68957-c620-47d4-860e-e66c2bf7e9d8.png)

![Untitled-9](https://user-images.githubusercontent.com/81478011/181648495-15746055-8f7c-4536-ac25-58d268425481.png)

**Comment by karalabe** [comment]
nginx requires virtual hosts and domains. please google search it if you are not familiar with the concepts.

**Comment by cryptonana** [comment]
> nginx requires virtual hosts and domains. please google search it if you are not familiar with the concepts.

i already setup domain name still same issue come
![Untitled-2](https://user-images.githubusercontent.com/40866572/181757386-6bda155f-0c09-4411-a1b3-ee5096414b43.png)

**Comment by cjango** [comment]
is that ok？ i also have this problem
