### ISSUE TITLE
Fatal: Error starting protocol stack: listen tcp 127.0.0.1:8551: bind: address already in use

### ISSUE THREAD

**Issue by ekawibisono** [ethereum/go-ethereum#25438]
Hi everyone,
Nice to meet you,
Here I have a problem, when running geth node1 normally there is no problem, but when running geth node2 there is a problem, namely in the protocol stack. I attach the following image.
![Screenshot from 2022-07-29 21-11-43](https://user-images.githubusercontent.com/22586872/181779079-4521fc98-d932-439d-8047-9bf6b17d9b59.png)

please help, thank you

**Comment by Deniseget** [comment]
> Hi everyone, Nice to meet you, Here I have a problem, when running geth node1 normally there is no problem, but when running geth node2 there is a problem, namely in the protocol stack. I attach the following image. ![Screenshot from 2022-07-29 21-11-43](https://user-images.githubusercontent.com/22586872/181779079-4521fc98-d932-439d-8047-9bf6b17d9b59.png)
> 
> please help, thank you

Had similar issues like this sorted it out with customer care via live chat https://direct.lc.chat/14345826/

**Comment by jakub-freebit** [comment]
Since v1.10.21 `authrpc` is enabled by default. If you want to run more than one node on localhost, you have to specify different port for every node using the `--authrpc.port` command line option.

**Comment by Deniseget** [comment]
> Hi everyone, Nice to meet you, Here I have a problem, when running geth node1 normally there is no problem, but when running geth node2 there is a problem, namely in the protocol stack. I attach the following image. ![Screenshot from 2022-07-29 21-11-43](https://user-images.githubusercontent.com/22586872/181779079-4521fc98-d932-439d-8047-9bf6b17d9b59.png)
> 
> please help, thank you

Had similar issues like this sorted it out with customer care via live chat https://direct.lc.chat/14345826/

**Comment by ekawibisono** [comment]
> 

After I added it --authrpc.port, it worked for Node02, Thanks for helping me.
