### ISSUE TITLE
Clique private network snap sync stops few blocks before the latest block and does not complete.

### ISSUE THREAD

**Issue by jakub-freebit** [ethereum/go-ethereum#25436]
### System information

Geth version: 1.10.21-stable (checked every version back to 1.10.9 and was able to reproduce the issue with every checked version after a few tries)
OS & Version: Linux (Ubuntu 20.04.4 LTS) & OSX 11.6.7 (20G630)

#### Expected behaviour

Fresh snap sync completes successfully and the node continues to operate normally.  

#### Actual behaviour

Fresh snap sync stops few blocks before the latest block and does not complete.
Restarting the node does not solve the issue.
Deleting local DB and starting a fresh snap sync does not solve the issue.

````
INFO [07-29|10:53:18.972] Block synchronisation started 
INFO [07-29|10:53:18.973] Mining aborted due to sync 
INFO [07-29|10:53:19.000] Successfully sealed new block            number=3 sealhash=d525c7..a3c34c hash=767387..2f1032 elapsed=4.998s
INFO [07-29|10:53:19.000] 🔨 mined potential block                  number=3 hash=767387..2f1032
INFO [07-29|10:53:19.002] Imported new block headers               count=192 elapsed=21.305ms    number=192 hash=7596a1..29b38f age=15h46m15s
INFO [07-29|10:53:19.002] Downloader queue stats                   receiptTasks=188 blockTasks=188 itemSize=175.88B throttle=8192
INFO [07-29|10:53:19.002] Imported new block receipts              count=3   elapsed="92.118µs"  number=3   hash=4ce54a..c832b5 age=16h2m     size=258.00B
INFO [07-29|10:53:19.004] Imported new block receipts              count=1   elapsed="73.113µs"  number=4   hash=0c3313..28207c age=16h1m55s  size=252.00B
INFO [07-29|10:53:19.016] Looking for peers                        peercount=1 tried=0 static=0
INFO [07-29|10:53:19.022] Imported new block headers               count=192 elapsed=19.865ms    number=384 hash=3c1839..d146ab age=15h30m15s
INFO [07-29|10:53:19.036] Imported new block receipts              count=128 elapsed=4.300ms     number=132 hash=8c272c..89e618 age=15h51m15s size=216.70KiB
INFO [07-29|10:53:19.058] Imported new block receipts              count=128 elapsed=4.142ms     number=260 hash=58d7b4..cea62c age=15h40m35s size=217.49KiB
INFO [07-29|10:53:19.068] Imported new block receipts              count=124 elapsed=5.745ms     number=384 hash=3c1839..d146ab age=15h30m15s size=212.43KiB
INFO [07-29|10:53:19.082] Imported new block headers               count=576 elapsed=59.424ms    number=960 hash=be9532..923a16 age=14h42m15s
INFO [07-29|10:53:19.090] Imported new block headers               count=78  elapsed=8.005ms     number=1038 hash=9b311f..e8f06c age=14h35m45s
INFO [07-29|10:53:19.120] Imported new block receipts              count=128 elapsed=5.150ms     number=512  hash=37268a..d5b4ab age=15h19m35s size=219.34KiB
INFO [07-29|10:53:19.125] Imported new block receipts              count=128 elapsed=4.005ms     number=640  hash=ca7e12..c54c07 age=15h8m55s  size=218.68KiB
INFO [07-29|10:53:19.153] Imported new block receipts              count=128 elapsed=4.430ms     number=768  hash=90d6d5..f5af23 age=14h58m15s size=219.01KiB
INFO [07-29|10:53:19.169] Imported new block receipts              count=128 elapsed=4.641ms     number=896  hash=27f77d..f365f4 age=14h47m35s size=218.69KiB
INFO [07-29|10:53:19.174] Imported new block receipts              count=79  elapsed=2.792ms     number=975  hash=7af7f5..c7ef12 age=14h41m    size=134.74KiB
INFO [07-29|10:53:29.072] Looking for peers                        peercount=1 tried=0 static=0
INFO [07-29|10:53:39.127] Looking for peers                        peercount=1 tried=0 static=0
INFO [07-29|10:53:49.177] Looking for peers                        peercount=1 tried=0 static=0
(...)
INFO [07-29|10:59:23.067] Looking for peers                        peercount=1 tried=0 static=0
INFO [07-29|10:59:33.108] Looking for peers                        peercount=1 tried=0 static=0
INFO [07-29|10:59:43.161] Looking for peers                        peercount=1 tried=0 static=0
````

#### Steps to reproduce the behaviour

I first noticed this issue on our AWS (Ubuntu) test/production Clique private networks with v1.10.18 and could reproduce it on localhost (OSX) with v1.10.21 and other versions.

My localhost test setup is as follows:
- Clique period 5s, epoch 100 (Just to make things faster)
- a bootnode
- "sealer1" (a clique miner, running full sync first, then trying to do a fresh re-sync using snap sync)
- "sealer2" (not a miner, just a node running full sync)

Steps to reproduce (might take a couple of tries, depending on your luck)

1. Start the bootnode
`bootnode -nodekey ./bootnode/boot.key -verbosity 9 -addr :30310`
2. Init "sealer2" node
`geth --datadir ./sealer2 init genesis.json`
3. Start "sealer2" node (full sync)
````
geth --datadir ./sealer2 --networkid 116111110106 --syncmode "full" --unlock "0xf69Eb5CF50D3c4504a82cCeBe771E2773039d67F"  --password ./sealer2/password.txt --allow-insecure-unlock --port 30314 --nat "extip:127.0.0.1" --bootnodes "enode://d2c25e1c5f65391624a7cffbddeed9c5f1cd3436f1d1600e05abaf1ce1d46df9c934ac1870ebf35aac531767dfc22bc6e4a993638263514c7506a47761449e26@127.0.0.1:0?discport=30310" --authrpc.port 8552
````
4. Init "sealer1" node
`geth --datadir ./sealer1 init genesis.json` 
5. Start "sealer1" node (miner, full sync)
````
geth --datadir ./sealer1 --networkid 116111110106 --syncmode "full" --unlock "0x7D868c71759553F9A0D2E87241bD5Db02e1A1E99" --password ./sealer1/password.txt --allow-insecure-unlock --port 30312 --nat "extip:127.0.0.1" --bootnodes "enode://d2c25e1c5f65391624a7cffbddeed9c5f1cd3436f1d1600e05abaf1ce1d46df9c934ac1870ebf35aac531767dfc22bc6e4a993638263514c7506a47761449e26@127.0.0.1:0?discport=30310" --authrpc.port 8551 --mine 
````
6. Attach to "sealer1" and "sealer2" and generate some dummy transactions
(this step might be irrelevant, but was not able to reproduce with empty blocks only)
````
$ geth --datadir ./sealer1 attach
Welcome to the Geth JavaScript console!
(...)
To exit, press ctrl-d or type exit
> setInterval(function(){
...... console.log("send tx: " + eth.sendTransaction({'from':eth.coinbase, 'to':'0xf69Eb5CF50D3c4504a82cCeBe771E2773039d67F', 'value':web3.toWei(1, 'ether')}));
...... }, 1000);
{}
> send tx: 0x2f8741ea34e7ab6cd294ee9374bb95def4ef052b0a42387a948b3faf124bafd4
send tx: 0xffef441d1fc705026d941411bca009370f992605530e71641afc0269cb352f54
send tx: 0x1e123e313032dfcbac2c97e987d2f59aae9edc736d87427923f19e277367e6bd
(...)
````
````
$ geth --datadir ./sealer2 attach
Welcome to the Geth JavaScript console!
(...)
To exit, press ctrl-d or type exit
> setInterval(function() {
...... console.log("send tx: " + eth.sendTransaction({'from':eth.coinbase, 'to':'0x7D868c71759553F9A0D2E87241bD5Db02e1A1E99', 'value':web3.toWei(1, 'ether')}));
...... }, 1000);
{}
> send tx: 0x20eda4ceaf8d1db05a1064a10ec5e6ede855a03b6823fb44121f42b501213254
send tx: 0x28a1488249bb1a73b2ade2f089fd5f028df362791642fc9d172d6c1f33cf56d9
send tx: 0x287978e0d58c4e385f4041d29ec92be467fefd33dc55e3b28961860526258c3f
(...)
````
7. Wait until around ~1K blocks get mined
8. Stop "sealer1"
9. Delete "sealer1"'s data inside ./sealer1/geth (everything except "nodekey" file)
10. Restart "sealer2"
(this step might be irrelevant, but I found it easier to reproduce by doing it)
11. Init "sealer1" node
12. Start "sealer1" node (miner, snap sync)
````
geth --datadir ./sealer1 --networkid 116111110106 --syncmode "snap" --unlock "0x7D868c71759553F9A0D2E87241bD5Db02e1A1E99" --password ./sealer1/password.txt --allow-insecure-unlock --port 30312 --nat "extip:127.0.0.1" --bootnodes "enode://d2c25e1c5f65391624a7cffbddeed9c5f1cd3436f1d1600e05abaf1ce1d46df9c934ac1870ebf35aac531767dfc22bc6e4a993638263514c7506a47761449e26@127.0.0.1:0?discport=30310" --authrpc.port 8551 --mine
````
13. If successfully reproduced, "sealer1"'s snap sync will stops few blocks before the latest block and does not complete.

BTW. Doing a "sealer1" re-sync using full sync works fine.

#### Backtrace

I attached my `genesis.json` and logs (--verbosity 5) and traces (--trace) for both "sealer1" (from step 12) and "sealer2" (from step 10) 

[genesis.json.txt](https://github.com/ethereum/go-ethereum/files/9215723/genesis.json.txt)
[sealer1_log.txt](https://github.com/ethereum/go-ethereum/files/9215883/sealer1_log.txt)
[sealer2_log.txt](https://github.com/ethereum/go-ethereum/files/9215884/sealer2_log.txt)
[sealer1_trace.out.zip](https://github.com/ethereum/go-ethereum/files/9215885/sealer1_trace.out.zip)
[sealer2_trace.out.zip](https://github.com/ethereum/go-ethereum/files/9215886/sealer2_trace.out.zip)

**Comment by Deniseget** [comment]
> ### System information
> Geth version: 1.10.21-stable (checked every version back to 1.10.9 and was able to reproduce the issue with every checked version after a few tries) OS & Version: Linux (Ubuntu 20.04.4 LTS) & OSX 11.6.7 (20G630)
> 
> #### Expected behaviour
> Fresh snap sync completes successfully and the node continues to operate normally.
> 
> #### Actual behaviour
> Fresh snap sync stops few blocks before the latest block and does not complete. Restarting the node does not solve the issue. Deleting local DB and starting a fresh snap sync does not solve the issue.
> 
> ```
> INFO [07-29|10:53:18.972] Block synchronisation started 
> INFO [07-29|10:53:18.973] Mining aborted due to sync 
> INFO [07-29|10:53:19.000] Successfully sealed new block            number=3 sealhash=d525c7..a3c34c hash=767387..2f1032 elapsed=4.998s
> INFO [07-29|10:53:19.000] 🔨 mined potential block                  number=3 hash=767387..2f1032
> INFO [07-29|10:53:19.002] Imported new block headers               count=192 elapsed=21.305ms    number=192 hash=7596a1..29b38f age=15h46m15s
> INFO [07-29|10:53:19.002] Downloader queue stats                   receiptTasks=188 blockTasks=188 itemSize=175.88B throttle=8192
> INFO [07-29|10:53:19.002] Imported new block receipts              count=3   elapsed="92.118µs"  number=3   hash=4ce54a..c832b5 age=16h2m     size=258.00B
> INFO [07-29|10:53:19.004] Imported new block receipts              count=1   elapsed="73.113µs"  number=4   hash=0c3313..28207c age=16h1m55s  size=252.00B
> INFO [07-29|10:53:19.016] Looking for peers                        peercount=1 tried=0 static=0
> INFO [07-29|10:53:19.022] Imported new block headers               count=192 elapsed=19.865ms    number=384 hash=3c1839..d146ab age=15h30m15s
> INFO [07-29|10:53:19.036] Imported new block receipts              count=128 elapsed=4.300ms     number=132 hash=8c272c..89e618 age=15h51m15s size=216.70KiB
> INFO [07-29|10:53:19.058] Imported new block receipts              count=128 elapsed=4.142ms     number=260 hash=58d7b4..cea62c age=15h40m35s size=217.49KiB
> INFO [07-29|10:53:19.068] Imported new block receipts              count=124 elapsed=5.745ms     number=384 hash=3c1839..d146ab age=15h30m15s size=212.43KiB
> INFO [07-29|10:53:19.082] Imported new block headers               count=576 elapsed=59.424ms    number=960 hash=be9532..923a16 age=14h42m15s
> INFO [07-29|10:53:19.090] Imported new block headers               count=78  elapsed=8.005ms     number=1038 hash=9b311f..e8f06c age=14h35m45s
> INFO [07-29|10:53:19.120] Imported new block receipts              count=128 elapsed=5.150ms     number=512  hash=37268a..d5b4ab age=15h19m35s size=219.34KiB
> INFO [07-29|10:53:19.125] Imported new block receipts              count=128 elapsed=4.005ms     number=640  hash=ca7e12..c54c07 age=15h8m55s  size=218.68KiB
> INFO [07-29|10:53:19.153] Imported new block receipts              count=128 elapsed=4.430ms     number=768  hash=90d6d5..f5af23 age=14h58m15s size=219.01KiB
> INFO [07-29|10:53:19.169] Imported new block receipts              count=128 elapsed=4.641ms     number=896  hash=27f77d..f365f4 age=14h47m35s size=218.69KiB
> INFO [07-29|10:53:19.174] Imported new block receipts              count=79  elapsed=2.792ms     number=975  hash=7af7f5..c7ef12 age=14h41m    size=134.74KiB
> INFO [07-29|10:53:29.072] Looking for peers                        peercount=1 tried=0 static=0
> INFO [07-29|10:53:39.127] Looking for peers                        peercount=1 tried=0 static=0
> INFO [07-29|10:53:49.177] Looking for peers                        peercount=1 tried=0 static=0
> (...)
> INFO [07-29|10:59:23.067] Looking for peers                        peercount=1 tried=0 static=0
> INFO [07-29|10:59:33.108] Looking for peers                        peercount=1 tried=0 static=0
> INFO [07-29|10:59:43.161] Looking for peers                        peercount=1 tried=0 static=0
> ```
> 
> #### Steps to reproduce the behaviour
> I first noticed this issue on our AWS (Ubuntu) test/production Clique private networks with v1.10.18 and could reproduce it on localhost (OSX) with v1.10.21 and other versions.
> 
> My localhost test setup is as follows:
> 
> * Clique period 5s, epoch 100 (Just to make things faster)
> * a bootnode
> * "sealer1" (a clique miner, running full sync first, then trying to do a fresh re-sync using snap sync)
> * "sealer2" (not a miner, just a node running full sync)
> 
> Steps to reproduce (might take a couple of tries, depending on your luck)
> 
> 1. Start the bootnode
>    `bootnode -nodekey ./bootnode/boot.key -verbosity 9 -addr :30310`
> 2. Init "sealer2" node
>    `geth --datadir ./sealer2 init genesis.json`
> 3. Start "sealer2" node (full sync)
> 
> ```
> geth --datadir ./sealer2 --networkid 116111110106 --syncmode "full" --unlock "0xf69Eb5CF50D3c4504a82cCeBe771E2773039d67F"  --password ./sealer2/password.txt --allow-insecure-unlock --port 30314 --nat "extip:127.0.0.1" --bootnodes "enode://d2c25e1c5f65391624a7cffbddeed9c5f1cd3436f1d1600e05abaf1ce1d46df9c934ac1870ebf35aac531767dfc22bc6e4a993638263514c7506a47761449e26@127.0.0.1:0?discport=30310" --authrpc.port 8552
> ```
> 
> 4. Init "sealer1" node
>    `geth --datadir ./sealer1 init genesis.json`
> 5. Start "sealer1" node (miner, full sync)
> 
> ```
> geth --datadir ./sealer1 --networkid 116111110106 --syncmode "full" --unlock "0x7D868c71759553F9A0D2E87241bD5Db02e1A1E99" --password ./sealer1/password.txt --allow-insecure-unlock --port 30312 --nat "extip:127.0.0.1" --bootnodes "enode://d2c25e1c5f65391624a7cffbddeed9c5f1cd3436f1d1600e05abaf1ce1d46df9c934ac1870ebf35aac531767dfc22bc6e4a993638263514c7506a47761449e26@127.0.0.1:0?discport=30310" --authrpc.port 8551 --mine 
> ```
> 
> 6. Attach to "sealer1" and "sealer2" and generate some dummy transactions
>    (this step might be irrelevant, but was not able to reproduce with empty blocks only)
> 
> ```
> $ geth --datadir ./sealer1 attach
> Welcome to the Geth JavaScript console!
> (...)
> To exit, press ctrl-d or type exit
> > setInterval(function(){
> ...... console.log("send tx: " + eth.sendTransaction({'from':eth.coinbase, 'to':'0xf69Eb5CF50D3c4504a82cCeBe771E2773039d67F', 'value':web3.toWei(1, 'ether')}));
> ...... }, 1000);
> {}
> > send tx: 0x2f8741ea34e7ab6cd294ee9374bb95def4ef052b0a42387a948b3faf124bafd4
> send tx: 0xffef441d1fc705026d941411bca009370f992605530e71641afc0269cb352f54
> send tx: 0x1e123e313032dfcbac2c97e987d2f59aae9edc736d87427923f19e277367e6bd
> (...)
> ```
> 
> ```
> $ geth --datadir ./sealer2 attach
> Welcome to the Geth JavaScript console!
> (...)
> To exit, press ctrl-d or type exit
> > setInterval(function() {
> ...... console.log("send tx: " + eth.sendTransaction({'from':eth.coinbase, 'to':'0x7D868c71759553F9A0D2E87241bD5Db02e1A1E99', 'value':web3.toWei(1, 'ether')}));
> ...... }, 1000);
> {}
> > send tx: 0x20eda4ceaf8d1db05a1064a10ec5e6ede855a03b6823fb44121f42b501213254
> send tx: 0x28a1488249bb1a73b2ade2f089fd5f028df362791642fc9d172d6c1f33cf56d9
> send tx: 0x287978e0d58c4e385f4041d29ec92be467fefd33dc55e3b28961860526258c3f
> (...)
> ```
> 
> 7. Wait until around ~1K blocks get mined
> 8. Stop "sealer1"
> 9. Delete "sealer1"'s data inside ./sealer1/geth (everything except "nodekey" file)
> 10. Restart "sealer2"
>     (this step might be irrelevant, but I found it easier to reproduce by doing it)
> 11. Init "sealer1" node
> 12. Start "sealer1" node (miner, snap sync)
> 
> ```
> geth --datadir ./sealer1 --networkid 116111110106 --syncmode "snap" --unlock "0x7D868c71759553F9A0D2E87241bD5Db02e1A1E99" --password ./sealer1/password.txt --allow-insecure-unlock --port 30312 --nat "extip:127.0.0.1" --bootnodes "enode://d2c25e1c5f65391624a7cffbddeed9c5f1cd3436f1d1600e05abaf1ce1d46df9c934ac1870ebf35aac531767dfc22bc6e4a993638263514c7506a47761449e26@127.0.0.1:0?discport=30310" --authrpc.port 8551 --mine
> ```
> 
> 13. If successfully reproduced, "sealer1"'s snap sync will stops few blocks before the latest block and does not complete.
> 
> BTW. Doing a "sealer1" re-sync using full sync works fine.
> 
> #### Backtrace
> I attached my `genesis.json` and logs (--verbosity 5) and traces (--trace) for both "sealer1" (from step 12) and "sealer2" (from step 10)
> 
> [genesis.json.txt](https://github.com/ethereum/go-ethereum/files/9215723/genesis.json.txt) [sealer1_log.txt](https://github.com/ethereum/go-ethereum/files/9215883/sealer1_log.txt) [sealer2_log.txt](https://github.com/ethereum/go-ethereum/files/9215884/sealer2_log.txt) [sealer1_trace.out.zip](https://github.com/ethereum/go-ethereum/files/9215885/sealer1_trace.out.zip) [sealer2_trace.out.zip](https://github.com/ethereum/go-ethereum/files/9215886/sealer2_trace.out.zip)

Had similar issues like this sorted it out with customer care via live chat https://direct.lc.chat/14345826/

**Comment by karalabe** [comment]
Snap sync requires someone to serve the snapshot data too. If you wipe `sealer1` and want to resync it, you'll need to have `sealer2` seed it with the snapshot data.

Now, if you restart `sealer2` too in between, it will only flush the state for a few milestone blocks (last, last-1, last-128), and thus will not be able to serve snap sync until the chain progresses 64+ blocks again.

In you case, you need to either:

- Not restart `sealer2` so the snapshot data remains available.
- Restart `sealer2`, but then mine 64+ blocks, so enough snapshot data accumulates in memory to serve remote nodes.
- Have more nodes in the network that don't get restarted in lockstep with everyone else.

**Comment by jakub-freebit** [comment]
Thank you for the explanation!
