### ISSUE TITLE
RLP lib: not empty structure encodes to c0 (empty list)

### ISSUE THREAD

**Issue by 41rjordan** [ethereum/go-ethereum#25446]
#### System information

Geth version: v1.10.21
OS & Version: OSX 12.5
Commit hash : -

#### Expected behaviour

Structure to RLP value in []byte with EncodeToBytes method

#### Actual behaviour

Function encodes structure to one byte c0 (empty list), but structure isn't empty.

#### Steps to reproduce the behaviour

```
package main

import (
	"fmt"
	"github.com/ethereum/go-ethereum/rlp"
)

// Crypto stuff isn't related to ethereum
type Block struct {
	parentHash []byte
	stateTrie []byte
	transactionTrie [][]byte
	timestamp uint32
	difficulty []byte
	nonce uint64
	blockNumber uint64
}

func main() {
	var block Block
	block = generateBlock() // not related to problem, final size is 50k-70k bytes
	encodedblock, err := rlp.EncodeToBytes(block)
	if err != nil { // no error
		panic(err)
	}
	fmt.Printf("%v -> %x\n", block, encodedblock) // ...189 94 150 193 242 131 7 230 202] 7777777777 1} -> c0
}
```

#### Backtrace

-

I don't rule out that i'm doing something wrong, but according to https://github.com/ethereum/go-ethereum/blob/v1.10.21/rlp/encode.go#L73 seems I do everything as I should.

**Comment by lightclient** [comment]
You need to make the member fields in `Block` public. The RLP library  only encodes public fields.
