### ISSUE TITLE
geth how to open persistence

### ISSUE THREAD

**Issue by huifer** [ethereum/go-ethereum#25443]
I set up private ETH in my own environment, but after killing the process, the relevant data does not exist. What should I do。I have tried to execute the geth removedb command and restart creation, restart GEth, still cannot persist the data
Please help me. Thank you so much

**Comment by huifer** [comment]
1. create genesis.json file 
```json
{
  "config": {
    "chainId": 15,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "ethash": {}
  },
  "difficulty": "1",
  "gasLimit": "8000000",
  "alloc": {
    "7df9a875a174b3bc565e6424a0050ebc1b2d1d82": { "balance": "300000" },
    "f41c74c9ae680c1aa78f42e5647a62f353b7bdde": { "balance": "400000" }
  }
}

```
2.  run `geth --datadir data init genesis.json`
```
INFO [07-30|11:08:54.116] Maximum peer count                       ETH=50 LES=0 total=50
INFO [07-30|11:08:54.118] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [07-30|11:08:54.121] Set global gas cap                       cap=50,000,000
INFO [07-30|11:08:54.123] Allocated cache and file handles         database=/root/eth/dev/data/geth/chaindata cache=16.00MiB handles=16
INFO [07-30|11:08:54.147] Opened ancient database                  database=/root/eth/dev/data/geth/chaindata/ancient readonly=false
INFO [07-30|11:08:54.147] Writing custom genesis block 
INFO [07-30|11:08:54.147] Persisted trie from memory database      nodes=3 size=397.00B time="63.178µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [07-30|11:08:54.148] Successfully wrote genesis state         database=chaindata                         hash=c3638c..f97051
INFO [07-30|11:08:54.148] Allocated cache and file handles         database=/root/eth/dev/data/geth/lightchaindata cache=16.00MiB handles=16
INFO [07-30|11:08:54.167] Opened ancient database                  database=/root/eth/dev/data/geth/lightchaindata/ancient readonly=false
INFO [07-30|11:08:54.167] Writing custom genesis block 
INFO [07-30|11:08:54.168] Persisted trie from memory database      nodes=3 size=397.00B time="42.033µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [07-30|11:08:54.168] Successfully wrote genesis state         database=lightchaindata                         hash=c3638c..f97051

```

3. run `geth --datadir data --networkid 15 --http --http.api personal,eth,net,miner,web3 --http.addr 0.0.0.0 --allow-insecure-unlock --rpc.allow-unprotected-txs console` 

```
> personal.newAccount("123")
> miner.start(10)
> eth.getBalance(eth.accounts[0])
42000000000000000000
> exit
```
4. Exit and restart 
```
> eth.getBalance(eth.accounts[0])
42000000000000000000

```
5. run with nohup `nohup geth --datadir data --networkid 15 --http --http.api personal,eth,net,miner,web3 --http.addr 0.0.0.0 --allow-insecure-unlock --rpc.allow-unprotected-txs     &` 
6. `cd data `
7. `geth attach ipc:geth.ipc`
```
> eth.getBalance(eth.accounts[0])
42000000000000000000

```
8. kill geth 

```
ps -ef | grep geth 
root     14131 13983  2 11:12 pts/0    00:00:01 geth --datadir data --networkid 15 --http --http.api personal,eth,net,miner,web3 --http.addr 0.0.0.0 --allow-insecure-unlock --rpc.allow-unprotected-txs
kill -9 14131 
```
9.  restart `nohup geth --datadir data --networkid 15 --http --http.api personal,eth,net,miner,web3 --http.addr 0.0.0.0 --allow-insecure-unlock --rpc.allow-unprotected-txs     &` 
10. `cd data `
11. `geth attach ipc:geth.ipc`
```
> eth.getBalance(eth.accounts[0])
42000000000000000000

```

It's possible that after step 10 the data is zero

**Comment by karalabe** [comment]
You need to shut down Geth gracefully. Most of the state is kept in memory, if you just murder Geth, all that in-memory stuff is gone. Don't ever use `-9`. Use SIGINT or SIGTERM (unsure which one, possibly both work).

**Comment by hadesjaky** [comment]
How to gracefully close geth? Which command to use?

**Comment by hadesjaky** [comment]
> You need to shut down Geth gracefully. Most of the state is kept in memory, if you just murder Geth, all that in-memory stuff is gone. Don't ever use `-9`. Use SIGINT or SIGTERM (unsure which one, possibly both work).
How to gracefully close geth? Which command to use?

**Comment by karalabe** [comment]
> Use SIGINT or SIGTERM (unsure which one, possibly both work).
