### ISSUE TITLE
Speeding up the full node

### ISSUE THREAD

**Issue by kapisolec** [ethereum/go-ethereum#25440]
I was wondering if there is a certain config, flags or anything that I could launch or tweak my Ethereum fullnode that will speed it up in terms of transaction propagation and fetching mempool transactions. I built a sniper bot and as far as I can see it's really fast but not fast enough - there are bots that are always before me. I've optimized as much of my code as possible so basically only thing left is fullnode configuration.

**Comment by karalabe** [comment]
There's nothing to configure in Geth in this regard. My guess is that large MEV bundlers are running multiple, geographically distributed nodes to pick up on interesting transactions faster.
