### ISSUE TITLE
geth: Implement RFC-6979 (Deterministic Usage of ECDSA)

### ISSUE THREAD

**Issue by mars4science** [ethereum/go-ethereum#25447]
# Rationale

I've read due to faulty random generators collisions in choice of k value during signing with ECDSA might occur (resulting in potential for secret key recovery from signed transactions, see https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm#Security), same source claims that using https://www.rfc-editor.org/rfc/rfc6979.html when signing transaction prevents this issue.

# Implementation

Implementation might be in `geth` code replacing random k selection with one based on RFC-6979 or adding global option to choose random vs deterministic RFC-6979 based.

I want to help implementing this feature if provided help to locating signer code.

**Comment by tynes** [comment]
RFC-6979 is already used, see:
- https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/crypto/secp256k1/libsecp256k1/src/secp256k1.c#L341
- https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/crypto/secp256k1/libsecp256k1/src/modules/recovery/main_impl.h#L135

**Comment by lightclient** [comment]
Thanks for pointing that out @tynes!
