### ISSUE TITLE
Duplicate code in gomobile production

### ISSUE THREAD

**Issue by m-yukio** [ethereum/go-ethereum#25462]
The Go Ethereum Mobile API is AAR/Frameworked using Go Mobile.
For example, if the Go code generated by Go Contract Bindings is converted to AAR on Go Mobile in order to use your own contract on Mobile, the following files will be duplicated.

go/error.java
go/Seq.java
go/Universe.java
libgojni.so

**Comment by Metamdev** [comment]
> The Go Ethereum Mobile API is AAR/Frameworked using Go Mobile. For example, if the Go code generated by Go Contract Bindings is converted to AAR on Go Mobile in order to use your own contract on Mobile, the following files will be duplicated.
> 
> go/error.java go/Seq.java go/Universe.java libgojni.so

Had same issues with this and i sorted it out via a live chat with support agent https://direct.lc.chat/14390013/ it was fast and transparent

**Comment by ligi** [comment]
Can you please provide more information on what exactly do you do - ideally a project to reproduce the problem.

**Comment by holiman** [comment]
Stale, closing
