### ISSUE TITLE
Option to limit stack info in debug_traceTransaction ?

### ISSUE THREAD

**Issue by fairglu** [ethereum/go-ethereum#2546]
debug_traceTransaction has options to limit the output json size, but the stack is an all or nothing option, this is a request to allow limiting the number of stack entries reported in a json.

Rational is for some transactions that perform a lot of operations with a deep stack, the json can get enormous because of the duplicated stack, while only a few items will actually change between each op.

As illustration you can check the trace for 0x18490545bf3b4ba6c93e5848e7ad243d194a8e1b3a73a88421a3b8ac5a4a074c
it comes out at 168 MB with just stack enabled.

Disabling the stack entirely makes the trace not very useful because you then no longer know if some opcodes (like CALL) have succeeded or not.

**Comment by fjl** [comment]
See #2874 for a solution attempt.
