### ISSUE TITLE
Error Deploy Dashboard Step 5

### ISSUE THREAD

**Issue by ekawibisono** [ethereum/go-ethereum#25471]
hello team,

Here I want to ask, when I deploy the Dashboard via puppeth, in step 5 issue an error code,

here is the error code,
("Step 5/12 : ADD lorem-cpp.json /dashboard/lorem-cpp.json
Service 'dashboard' failed to build: ADD failed: file not found in build context or excluded by .dockerignore: stat lorem-cpp.json: file does not exist
ERROR[08-03|23:03:22.480] Failed to deploy dashboard container     err="Process exited with status 1")

and I attached the screenshot.
![image](https://user-images.githubusercontent.com/22586872/182728665-c21605f0-5a6f-4200-807e-8331a9b622a9.png)

Please help.

Thank you

Geth Version : 1.10.22-unstable

**Comment by ligi** [comment]
I would like to reproduce this - can you give me a link to the documentation you follow?

**Comment by ekawibisono** [comment]
> I would like to reproduce this - can you give me a link to the documentation you follow?

I Follow the guide this link : https://achintadas13.medium.com/setup-private-ethereum-network-poa-on-degital-ocean-using-puppeth-164b869567a2

**Comment by ekawibisono** [comment]
Hello team,

Any update team for this problem?

**Comment by Metamdev** [comment]
> hello team,
> 
> Here I want to ask, when I deploy the Dashboard via puppeth, in step 5 issue an error code,
> 
> here is the error code, ("Step 5/12 : ADD lorem-cpp.json /dashboard/lorem-cpp.json Service 'dashboard' failed to build: ADD failed: file not found in build context or excluded by .dockerignore: stat lorem-cpp.json: file does not exist ERROR[08-03|23:03:22.480] Failed to deploy dashboard container err="Process exited with status 1")
> 
> and I attached the screenshot. ![image](https://user-images.githubusercontent.com/22586872/182728665-c21605f0-5a6f-4200-807e-8331a9b622a9.png)
> 
> Please help.
> 
> Thank you
> 
> Geth Version : 1.10.22-unstable

Had same issues with this and i sorted it out via a live chat with support agent https://direct.lc.chat/14390013/ it was fast and transparent
