### ISSUE TITLE
[ethclient] invalid memory address or nil pointer dereference thrown when accessing string representation of To() address

### ISSUE THREAD

**Issue by hnord-vdx** [ethereum/go-ethereum#25479]
#### System information

Geth version: `N/A`
OS & Version: OSX

#### Expected behaviour

Ability to access `to` address without error being thrown

#### Actual behaviour

Sometimes a memory error is thrown when trying to access string representation of `to` address

#### Steps to reproduce the behaviour
``` Golang
package main

import (
        "context"
	"fmt"
        "math/big"
        "log"

	"github.com/ethereum/go-ethereum/ethclient"
)

var (
        ctx = context.Background()
        cl, _ = ethclient.Dial("rpc_url")
)

func main() {
	headerChan := make(chan *types.Header)
	cl.SubscribeNewHead(ctx, headerChan)
	for {
		if header, ok := <-headerChan; ok {
			processBlock(header.Number)
		}

	}
}

func processBlock(blockNr *big.Int) {
	blk, _ := cl.BlockByNumber(ctx, blockNr)

	txs := blk.Transactions()
        fmt.Printf(blockNr)
	for _, tx := range txs {
		tx.To().String() //! this sometimes throws
	}
}
```

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102c25600]
````

**Comment by rjl493456442** [comment]
You ignored all the errors which can be non-nil. 

Can you point out which line is panic?

**Comment by hnord-vdx** [comment]
I removed the error handling for readability. Its the last line that panics `tx.To().String()`, while if I just have `tx.To()` it doesn't panic. I tried calling `.Hex()`but that also panics. The thing is it only panics sometimes..

**Comment by hnord-vdx** [comment]
`To returns the recipient address of the transaction. For contract-creation transactions, To returns nil.` just saw this comment!
