### ISSUE TITLE
debug.traceTransaction running out of memory and crashing (6 GB+)

### ISSUE THREAD

**Issue by fairglu** [ethereum/go-ethereum#2547]
#### System information

Geth version: 1.5.0
OS & Version: Linux
#### Expected behaviour

debug.traceTransaction should not crash geth, but at least return an error.
#### Actual behaviour

It can consume all memory then crash geth
#### Steps to reproduce the behaviour

in the console run

`debug.traceTransaction('0x9b3d5c27071b5ed45bff4e3c48b97efd790e9455cef4c92748ac5e27f99d59da')`

It will also crash through the RPC API

Note that for the above transaction, even with storage, memory and stack disabled, execution is extremely slow, I am not even sure it completes (it has been running for almost 30 minutes here... still running).
According to ethercamp, the transaction has 201392 steps.

**Comment by obscuren** [comment]
Ouch. This is because of the following issues:

* JSON marshalling
* Each trace contains a copy of the data (storage, memory, stack)

We'll look in to making this more performant. No temporary solution.

**Comment by fairglu** [comment]
Redid some tests after a full reboot, and when storage/memory/stack are disabled, it manages to complete, though it takes some time.

Adding the stack limit option suggested in https://github.com/ethereum/go-ethereum/issues/2546 would probably help, but may not be enough for transactions with hundreds of tousandths of steps.

Another approach is detailed in https://github.com/ethereum/go-ethereum/issues/2550, and should allow tackling monster transactions with minimal changes to the API (just extra options, which should just affect logger.go AFAICT)

**Comment by fairglu** [comment]
Another partial solution could be to simply trim the leading zeroes for hex values, depending on transactions this can reduce json size by 30% to 90%.

**Comment by fairglu** [comment]
Did some more testing and hacking in logger.go, the automated JSON marshalling incurs a significant penalty. Of note is is the marshalling of empty values (f.i. empty storage when storage is disabled, empty error string), I have commented out the fields StructLog (rather than using the disableXxxx options), and it makes the trace much faster, so marshalling of empty fields is definitely not free.

**Comment by fjl** [comment]
@fairglu you can also try https://github.com/pquerna/ffjson to make serialising the trace faster. 
Would appreciate a PR if you have improvements ;).

We can also stream large traces as JSON-RPC notifications, although it will make the client side more complicated.

**Comment by fairglu** [comment]
@fjl my go-fu is limited, so my improvements are merely judiciously placed "//" :)

Most of the trouble comes from unnecessary overhead: streaming of empty strings, nulls, empty objects, leading zeroes, very deep stacks. So while faster marshalling could help, removing the overhead helps even more, I have been able to trace the monster txs (almost 500k steps for the larger ones) under 1 GB RAM after commenting out what I did not need, but those were ad-hoc changes.

Better than JSON-RPC notification would be ways to request just a subset explicitly (cf. https://github.com/ethereum/go-ethereum/issues/2550).

When the trace is for human analysis, you can only look at a subset anyway, and the rest can be fetched piecemeal when (and if) needed, provided you have some form of index or summary of the whole trace.
For automated analysis (my particular use case), I only look at the trace for some opcodes and depths. So in both cases, having all of the data at once is unnecessary, and the interesting tidbits can be anywhere in the trace.

So it is probably not as much a streaming problem as it is an "on demand" one.

**Comment by fairglu** [comment]
In case someone else faces the same problem, for the stack log, the simplest "fix" is to change in eth/api.go, formatLogs function, from

`formattedStructLogs[index].Stack[i] = fmt.Sprintf("%x", common.LeftPadBytes(stackValue.Bytes(), 32))`

to 

`formattedStructLogs[index].Stack[i] = fmt.Sprintf("%x", stackValue.Bytes())`

this removes the zero padding in the json for the stack values, which is easy to add back on the client side if you need it, and can drastically helps with json size without losing data.

Another more minor but still effective change is to concatenante the Op and Error fields, which allows removing the (typically empty) Error field from the json, untangling the concatenation is simple to handle client-side.
