### ISSUE TITLE
ropsten  eth.syncing is false but eth.blockNumber is not latest

### ISSUE THREAD

**Issue by lvgang214** [ethereum/go-ethereum#25484]
>eth.syncing
false
> eth.blockNumber
12443932
geth version
Geth
Version: 1.10.20-stable
Git Commit: 8f2416a89a3def6ec2c749d5afafbf2c9a18e3c8
Git Commit Date: 20220629
Architecture: amd64
Go Version: go1.18.1
Operating System: linux
GOPATH=/home/ubuntu/go
GOROOT=/usr/local/go

**Comment by Metamdev** [comment]
> eth.syncing { currentBlock: 12310531, healedBytecodeBytes: 40217559, healedBytecodes: 5678, healedTrienodeBytes: 558816344, healedTrienodes: 2691387, healingBytecode: 0, healingTrienodes: 1350, highestBlock: 12725351, startingBlock: 12098467, syncedAccountBytes: 9865387177, syncedAccounts: 409607295, syncedBytecodeBytes: 13297506055, syncedBytecodes: 2341970, syncedStorage: 253218104, syncedStorageBytes: 56901871759 }
> 
> > eth.syncing
> > {
> > currentBlock: 12314177,
> > healedBytecodeBytes: 40217559,
> > healedBytecodes: 5678,
> > healedTrienodeBytes: 559244501,
> > healedTrienodes: 2692757,
> > healingBytecode: 0,
> > healingTrienodes: 1,
> > highestBlock: 12443129,
> > startingBlock: 12098467,
> > syncedAccountBytes: 9865387177,
> > syncedAccounts: 409607295,
> > syncedBytecodeBytes: 13297506055,
> > syncedBytecodes: 2341970,
> > syncedStorage: 253218104,
> > syncedStorageBytes: 56901871759
> > }
> 
> why the highestBlock from 12725351 to 12443129？

Had same issues with this and i sorted it out via a live chat with support agent https://direct.lc.chat/14390013/ it was fast and transparent

**Comment by karalabe** [comment]
In Ropsten, you are still syncing in PoW mode, where the sync target is the highest difficulty seen in your peers. After you reach the merge point 12350000-ish, the sync will be directed by your beacon node. If you were to use master branch (or the next stable release `1.10.22`), thn sync would not even start until the beacon client says so.

I.e. 1. Everything's fine; 2. Sync in PoW will stop a bit later without a beacon client; 3. A beacon client will get you syncing further from that point.
