### ISSUE TITLE
authrpc.jwtsecret flag is not define in linux release

### ISSUE THREAD

**Issue by gilfoyle2021asc** [ethereum/go-ethereum#25482]
#### System information

Geth version: `Geth 1.10.21`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
./geth --help|grep authrpc.jwtsecret
    --authrpc.jwtsecret value

#### Actual behaviour
geth --help|grep authrpc.jwtsecret
show nothing
#### Steps to reproduce the behaviour
download [Geth 1.10.21](https://gethstore.blob.core.windows.net/builds/geth-darwin-amd64-1.10.21-67109427.tar.gz)
run 
geth --help|grep authrpc.jwtsecret
#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
Works for me.

```
$ geth --help | grep authrpc.jwtsecret
    --authrpc.jwtsecret value
```

Please make sure `geth` points to the correct version. If you've downloaded it from the archive and unpacked it, make sure you're actually running that version, not some other in your PATH on the system.
