### ISSUE TITLE
Geth RPC service consistency against other client implementations #1

### ISSUE THREAD

**Issue by JosephK95** [ethereum/go-ethereum#25495]
(Updated 22.08.11.)

Sorry, I moved the remaining parts of this report to the following link: https://github.com/ethereum/execution-apis/issues/286
Please check for the edit history to see my original report.

----------------------------------------------------------------------------------------------
Hi all,

I am working on a project that validates whether Geth behaves consistently to other Ethereum client implementations against RPC requests. 
(I will refer to the implementations as node A, B and C here.)

I would appreciate it if you can clarify whether the following results are intentional or require patches.

Thank you so much in advance and please let me know if there is anything necessary.

#### System information
Geth version: 1.10.21-stable
OS & Version: Ubuntu 20.04.4 LTS
Node.js / web3.js versions: v16.15.0 / v1.7.3

Q1. `getProtocolVersion` support
- (Geth) returns an error: "the method ... not available"
- (Node A,B,C) returns `"0x42"`

#### Steps to reproduce the behaviour
1. Please download all the .tar.gz files below.
[https://drive.google.com/file/d/1FGUpnQ4WvftxBi7qUp63G3SuhKc-Q1_z/view?usp=sharing](url)
[https://drive.google.com/file/d/1KKuie5iNWIqAdgjcqOSWryCgIpyqwblq/view?usp=sharing](url) 
[test_cases.tar.gz](https://github.com/ethereum/go-ethereum/files/9282485/test_cases.tar.gz)
2. Untar the downloaded .tar.gz files. They contain valid chain data and test cases that are semi-automatically generated by our project techniques.
3. Check out DATA_DIR and TC_FILE for your Q{n} from the description below.
4. Execute Geth binary with the following flags:
`geth --datadir DATA_DIR --http --http.api eth --networkid 15 --nodiscover --syncmode full --gcmode archive`
5. Execute the test case file: `node TC_FILE`

- Q1. data-geth-1 / TC_1659703347.js

**Comment by holiman** [comment]
Thank you for this and #25501. It might be that it will take some time for us to evaluate and address these discrepancies, but hard data and steps to reproduce is very useful. Thanks again!

**Comment by karalabe** [comment]
> Q2. Invalid block argument to getBlockTransactionCount
> 
> (Geth) returns null
> (Node B) returns an error: "Block ... could not be found"
> Q3. Invalid block argument to getPastLogs
> 
> (Geth) returns []
> (Node B) returns an error: "... could not be found"
> Q4. Invalid block argument to getTransactionFromBlock
> 
> (Geth) returns null
> (Node B) returns an error: "Block ... could not be found"
> Q5. Invalid block argument to getBlockUncleCount
> 
> (Geth) returns null
> (Node B) returns an error: "Block ... could not be found"
> Q6. Invalid block argument to getUncle
> 
> (Geth) returns null
> (Node B) returns an error: "Block ... could not be found"

These are deliberate decisions. The JSON RPC spec does not define error returns (neither code, nor string). As such, whenever the RPC returns an error, a programmer needs to take a look at it and figure out what's wrong.

E.g.

```
Error: invalid argument 0: hex string has length 40, want 64 for common.Hash
	at web3.js:6365:9(45)
	at send (web3.js:5099:62(34))
	at <eval>:1:29(4)
```

This above is a programming error and cannot be solved by the calling program, it needs a developer to take a look.

A block not being in the chain however is not a programming error, it's simply missing data (e.g. node not yet fully synced?). By returning `nil` we explicitly differentiate this fault condition (which is recoverable by the caller program) from the other fault conditions (which are not recoverable by the caller program).

**Comment by karalabe** [comment]
> Q7. Unknown account to getProof
> 
> (Geth) returns an account object
> (Node C) returns an error: "Account not found"

Geth's behavior is correct. A non-existence proof is required to "prove" that the account does not exist. Returning an error is non-verifiable.

**Comment by JosephK95** [comment]
Closing the issue as moved to the link above.
