### ISSUE TITLE
Missing transactions field in uncle block objects

### ISSUE THREAD

**Issue by JosephK95** [ethereum/go-ethereum#25507]
Hi all,

According to the Ethereum API specification, `transactions` field in block object is mandatory. However, it seems that Geth does not have the field when returning an uncle block object.
(Specification link: https://github.com/ethereum/execution-apis)

#### System information
Geth version: 1.10.21-stable
OS & Version: Ubuntu 20.04.4 LTS

#### Expected behaviour
Geth should return a block object of the following form:
<pre>
{
  ...
  timestamp: 1659702502,
  transactions: [],
  transactionsRoot: '0x40d6b6bd0d7dfd3b17e88badf51a075ff5196271d10a892acacfefeef549cf5a',
  uncles: []
}
</pre>

#### Actual behaviour
Geth returns a block object without `transactions` field:
<pre>
{
  ...
  timestamp: 1659702502,
  transactionsRoot: '0x40d6b6bd0d7dfd3b17e88badf51a075ff5196271d10a892acacfefeef549cf5a',
  uncles: []
}
</pre>

**Comment by tharunprabhakaran** [comment]
Can you provide the blockhash along the issues. Thanks

**Comment by holiman** [comment]
An uncle is not a `block`. An uncle is a `header`. Therefore, a block can contain N uncles. Whereas, if an uncle were a block, then a block containing uncles (blocks) would be a recursive definition. 
So it has a `transactionsRoot` (which is a header field), but does not have the actual `transactions` (which is a part of the block body)
