### ISSUE TITLE
New feature: specify which steps to trace for debug.traceTransaction 

### ISSUE THREAD

**Issue by fairglu** [ethereum/go-ethereum#2550]
This feature request is related to taming memory and complexity issues related to trace, more specifically https://github.com/ethereum/go-ethereum/issues/2547 and https://github.com/ethereum/go-ethereum/issues/2546

The idea would be that rather than making traceTransaction super-smart and super-optimized, it could be invoked multiple times to provide the relevant data.
1. you would invoke it a first time with a "light trace" option, and it would return just an array of opcodes (and maybe depth), the idea is to have something lightweight in terms of JSON
2. you would then call it again, specifying the steps (indexes in the previous array) for which you want trace, and it would return the full trace, as usual, but just for those steps, and nothing else

The VM could be run multiple times, no special optimization needed. This would allow for complex transactions with hundreds of thousandths of steps to be traced piecemeal (like 0x9b3d5c27071b5ed45bff4e3c48b97efd790e9455cef4c92748ac5e27f99d59da)

**Comment by fairglu** [comment]
For testing and illustration purposes, another transaction of interest is 0x8c9cbe0f379b40c6ad227dba93dd1cc2e2b5e762efe6e87e2fc0194a0de22cdd with 439304 steps.

**Comment by juanfranblanco** [comment]
Another example is this transaction in Morden 0x6f57f590de7eb319b9d785cb3e51d98e874e36006a468ca477d4c7f34ece9349 with 827363 steps, ideally it will be great to get the last step to validate if an error has occurred.

Had the same issue running out of memory.

**Comment by fjl** [comment]
You can do this with the new JS map/reduce tracing, which is part of geth 1.5.0. See https://github.com/ethereum/go-ethereum/wiki/Management-APIs#javascript-based-tracing for more information.
