### ISSUE TITLE
Geth RPC service consistency against other client implementations #2

### ISSUE THREAD

**Issue by JosephK95** [ethereum/go-ethereum#25501]
(Updated 22.08.11.)

Sorry, I moved this report to the following link: https://github.com/ethereum/execution-apis/issues/288
Please check for the edit history to see my original report.

**Comment by fjl** [comment]
We have test cases for RPC endpoints here: https://github.com/ethereum/execution-apis/tree/main/tests
Your tests should be added there.

@lightclient

**Comment by JosephK95** [comment]
Closing the issue as moved to the link above.
