### ISSUE TITLE
Reopened from the issue #25507

### ISSUE THREAD

**Issue by JosephK95** [ethereum/go-ethereum#25510]
(Reopened from the issue #25507)

Thanks for the response to the previous issue that I reported.
I agree that an uncle is not a block object, but what I pointed out was the "return value" of uncle-returning APIs.

For example, the Ethereum API specification requires `transactions` field in the returned objects of `eth_getUncleByBlockHashAndIndex` API.
(Reference: https://ethereum.org/ko/developers/docs/apis/json-rpc/#eth_getunclebyblockhashandindex)

I guess you included `uncles` field in the returned objects for the same reason although an omners list is not part of block header either. Also, all other client implementations include `transactions: []` entry in their returned objects.

I would appreciate it if you consider this issue again based on my explanations here.
Thanks.

#### System information
Geth version: 1.10.21-stable
OS & Version: Ubuntu 20.04.4 LTS

#### Expected behaviour
When `eth_getUncleByBlockHashAndIndex` is called, Geth should return an object of the following form:
<pre>
{
  ...
  timestamp: 1659702502,
  transactions: [],
  transactionsRoot: '0x40d6b6bd0d7dfd3b17e88badf51a075ff5196271d10a892acacfefeef549cf5a',
  uncles: []
}
</pre>

#### Actual behaviour
Geth returns an object without `transactions` field:
<pre>
{
  ...
  timestamp: 1659702502,
  transactionsRoot: '0x40d6b6bd0d7dfd3b17e88badf51a075ff5196271d10a892acacfefeef549cf5a',
  uncles: []
}
</pre>

**Comment by karalabe** [comment]
Geth's response is the correct one. Uncles do not maintain a list of transactions that are included (they are part of the block body, nto the header (which an uncle is)).

Returning `transactions: []` would imply that the block corresponding to the uncle contained no transactions, which is most probably false.

**Comment by karalabe** [comment]
Btw, the spec also has the note "Note: An uncle doesn't contain individual transactions." on the page you linked.
