### ISSUE TITLE
go-ethereum-(devel)

### ISSUE THREAD

**Issue by coltonfreeman26** [ethereum/go-ethereum#25514]
Good day all,

I am still fairly new to this DevOps realm so pardon this question.
We are building an image using the geth binary from the Consensys/Quorum project in Github (linux). Our scan tools are picking up a bunch of high and critical findings from the package github.com/ethereum/go-ethereum-(devel) and I was just curious as to what this package is. This is compiled with the geth binary so I am having trouble looking into this locally and have not been able to find anything about it google searching. Is it possible to shed some light on what this is or is there somewhere you can point me to read up more on it? 

W/r Colton

**Comment by karalabe** [comment]
Erm? Quorum is a fork of the go-ethereum codebase. Geth *is* `github.com/ethereum/go-ethereum`.

**Comment by karalabe** [comment]
Btw, no worries for the question... but it was indeed a curious question :) Live and learn
