### ISSUE TITLE
opcode TXGASPRICE vs GASPRICE

### ISSUE THREAD

**Issue by fairglu** [ethereum/go-ethereum#2553]
In core/vm/opcodes.go, opCodeToString maps the GASPRICE opcode to "TXGASPRICE", while the rest of the code (like stringToOp a few lines below) uses "GASPRICE", and the yellow paper lists it as "GASPRICE" as well.

This affects debug_traceTransaction output.

Is there a particular reason for it or is it a bug?

**Comment by karalabe** [comment]
@obscuren ?

**Comment by obscuren** [comment]
Thanks for reporting and sorry for the delay. You appear to have found an [ancient artefact](http://cdn.images.express.co.uk/img/dynamic/151/590x/secondary/Phone-Full-424267.jpg)!

Will fix (or bonus points for submitting a PR against `develop` ;-))

**Comment by benjaminbrent** [comment]
This bug also causes `disasm` to incorrectly output `TXGASPRICE` for 0x3A:

```shell
$ echo 3A | disasm          
3a
0      TXGASPRICE
```

I've submitted PR #3168 which fixes the string in `core/vm/opcodes.go`.

**Comment by fjl** [comment]
Fix released in 1.5.0.
