### ISSUE TITLE
personal_signTransaction improperly requires both maxFeePerGas and maxPriorityFeePerGas

### ISSUE THREAD

**Issue by hostgame** [ethereum/go-ethereum#25536]
#### System information

Version: 1.10.22-unstable
Git Commit: c4ab7d229117fdaa24292d84c1d450a727cb3e9f
Architecture: amd64
Go Version: go1.18.5
Operating System: linux

#### Expected behaviour
After calling JSON-RPC method `personal_signTransaction` with `maxFeePerGas` **or** `maxPriorityFeePerGas` I expect to get signed transaction:
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "raw": "...",
        "tx": {
            "type": "0x2",
            "nonce": "0x00",
            "gasPrice": null,
            "maxPriorityFeePerGas": "0x3b9aca00",
            "maxFeePerGas": "0x3b9aca00",
            "gas": "0x5208",
            "value": "0x3a98",
            "input": "0x",
            "v": "0x1",
            "r": "...",
            "s": "...",
            "to": "...",
            "chainId": "0x3039",
            "accessList": [],
            "hash": "..."
        }
    }
}
```

#### Actual behaviour
Instead I get error about missing gasPrice/maxFeePerGas/maxPriorityFeePerGas. If I specify **both** `maxFeePerGas` and `maxPriorityFeePerGas` I would get correct response with signed transaction.
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"missing gasPrice or maxFeePerGas/maxPriorityFeePerGas"}}
```

#### Steps to reproduce the behaviour
```
curl --location --request POST 'http://127.0.0.1:8545' \
--header 'Content-Type: application/json' \
--data-raw '{ 
    "jsonrpc": "2.0", 
    "method": "personal_signTransaction", 
    "params": [{ 
        "from": "<from address>", 
        "to": "<to address>", 
        "gas": "0x5208", 
        "value": "0x3a98",
        "maxFeePerGas": "0x3b9aca00",
        "nonce": "0x00" 
        }, "password"
    ], 
    "id": 1 
}'
```
https://github.com/ethereum/go-ethereum/blob/948e08d55bf185e4b80ca7a10d689cbfd3f7fcdd/internal/ethapi/api.go#L484
This line expects `gasPrice` or `maxFeePerGas` + `maxPriorityFeePerGas`. As far as I know `maxFeePerGas` or `maxPriorityFeePerGas` only is enough, isn't it?

**Comment by holiman** [comment]
> As far as I know maxFeePerGas or maxPriorityFeePerGas only is enough, isn't it?

Both `maxFeePerGas` or `maxPriorityFeePerGas` is required
OR
`gasPrice`
