### ISSUE TITLE
Geth/v1.10.21 Connect Bootnode Fail -2 

### ISSUE THREAD

**Issue by rrhlrmrr** [ethereum/go-ethereum#25554]
I dont find out reopen issue button.
So I re-question to @go-ethereum team. Thanks for your understanding in advance.

Ex-Tciket number is #25553

1. Boot-node Full status How can Sync with Ethereum-mainnet?

Best Regards
Yeon

**Comment by holiman** [comment]
Please don't open new tickets. The particular bootnode was full. Just wait it out
