### ISSUE TITLE
Why set 'ret' here rather than code?

### ISSUE THREAD

**Issue by SipengXie** [ethereum/go-ethereum#25562]
https://github.com/ethereum/go-ethereum/blob/0ce494b60cd00d70f1f9f2dd0b9bfbd76204168a/core/vm/evm.go#L472
sorry to bother you but I feel confused about here setCode with the 'ret' rather than the code.

**Comment by rjl493456442** [comment]
For contract deployment, the bootstrap code will be run(specified in transaction payload) and the returned code is the actual contract code without bootstrap part.
