### ISSUE TITLE
Why my chain data so huge (15T)

### ISSUE THREAD

**Issue by SharpCX** [ethereum/go-ethereum#25577]
My chain data folder is up to 15T

<img width="239" alt="image" src="https://user-images.githubusercontent.com/1694085/186132347-667950e0-ecc5-49bf-ab2d-24a77dcd76b7.png">

My start command is:

``` bash
./geth --syncmode full --datadir /data/ethereum_datadir --ethash.dagdir /data/ethereum_dagdir --http --http.port 18545 --http.addr 0.0.0.0 --ws --ws.port 18546 --ws.addr 0.0.0.0 --snapshot=false --maxpeers 50
```

**Comment by rjl493456442** [comment]
Which version you are using? If it's 1.10.20 it contains a bug in leveldb upstream which will bloat up your disk.

**Comment by c0deright** [comment]
If it's 1.10.20: Install 1.10.21 or 1.10.23 (but not 1.10.22) and restart geth. Geth will remove the not needed files and will free disk usage.

**Comment by rjl493456442** [comment]
@c0deright yes

**Comment by SharpCX** [comment]
> Which version are you using? If it's 1.10.20 it contains a bug in leveldb upstream which will bloat up your disk.

thank you~

**Comment by SharpCX** [comment]
> If it's 1.10.20: Install 1.10.21 or 1.10.23 (but not 1.10.22) and restart geth. Geth will remove the not needed files and will free disk usage. Please give feedback if it works :)

Thank you~
