### ISSUE TITLE
Release 1.10.22 Regression

### ISSUE THREAD

**Issue by luzianscherrer** [ethereum/go-ethereum#25579]
Since release 1.10.22 has been marked with a regression issue, could you please issue a quick statement for the following points:

- What is the recommended course of action when one has already upgraded?
- Would a downgrade to 1.10.21 be safe?
- How can one determine if the instance is affected by the issue?

**Comment by karalabe** [comment]
You can downgrade, yes. No other ideas for now.

**Comment by cybersi** [comment]
Happend to me this morning. Decided to downgrade to 1.10.21, deleted the database and resync. Is there a way to repair the local state if the corruption happens?

**Comment by MariusVanDerWijden** [comment]
Yes, you might be able to setHead to a block before you upgraded the node

**Comment by c0deright** [comment]
Do i need to issue the `setHead` command with v1.0.22 still running or do I have to upgrade to v1.0.23 first?

**Comment by karalabe** [comment]
Upgrade first

**Comment by c0deright** [comment]
Just for clarification: The `setHead` command will roll back the local blockchain and the state to the specified block as if geth didn't even see or know about the existence of all the blocks after that block that geth knew about right before the `setHead` command, right? Geth will then sync the "new" blocks as if geth was stopped for some days and needs to catch up to the chain head.
Is that correct?

**Comment by karalabe** [comment]
Exactly

**Comment by RisingPaw** [comment]
You can encounter missing trie issues with `setHead` and maybe (see #25589).

Might be safer to do `geth removedb` (keep ancient data) and resync the past week.

**Comment by c0deright** [comment]
The question is: Are these errors expected during resync and harmless or will the node be in a consistent state after full sync is done?

**Comment by karalabe** [comment]
If after setHead you are seeing missing trie node errors, then the db is fried beyond recovery and you shoudl resync (keep the ancients, delete all other files inside `chaindata`).
