### ISSUE TITLE
Multiarch is not included in the docker image of the v1.10.23 version

### ISSUE THREAD

**Issue by tropicar** [ethereum/go-ethereum#25587]
#### Expected behaviour
The https://hub.docker.com/layers/client-go/ethereum/client-go/v1.10.23/images/sha256-7037a88131da259016633908403ed52cce7dc4567f3b681d6a56b839a7979343?context=explore image for the v1.10.23 version does not include the multiarchitecture: amd and arm, it contain amd architecture. 

#### Actual behaviour

The image only is compatible with linux/amd64 architecture

#### Steps to reproduce the behaviour

You can check it out in https://hub.docker.com/layers/client-go/ethereum/client-go/v1.10.23/images/sha256-7037a88131da259016633908403ed52cce7dc4567f3b681d6a56b839a7979343?context=explore

**Comment by karalabe** [comment]
It is now. Docker hub seems to autobuild too beside our manual pushes (previously they stopped auto building). Please check again the tag (probably a different hash now).

**Comment by tropicar** [comment]
> It is now. Docker hub seems to autobuild too beside our manual pushes (previously they stopped auto building). Please check again the tag (probably a different hash now).
Yes, it is. thank you very much! 
https://hub.docker.com/layers/client-go/ethereum/client-go/v1.10.23/images/sha256-71a7d243ec058de882017772c2ea24151617a2fc31ef733b4e87085fcaef38fd?context=explore
