### ISSUE TITLE
Geth node accounts balances and contracts reset to 0 after 30,000 Blocks in POA private network

### ISSUE THREAD

**Issue by laronlineworld** [ethereum/go-ethereum#25597]
This is my geth node script

`geth --datadir /root/data/data/ --networkid 1567134 --bootnodes enode://44a383ff2c8a78da1131ac82a4513b34de177103017f07c42098c53aad43bc3fd99f62d72d827349eb503f0054fec7683a7db36fc65f9d1238950f70bc4dba97@0.0.0.0:0?discport=8545 --cache=4096 --syncmode=full --gcmode=archive --http --http.addr "0.0.0.0" --ws --ws.addr "0.0.0.0" --ws.port "8546" --allow-insecure-unlock --ws.origins "*" --http --allow-insecure-unlock --http.corsdomain "*" --http.vhosts "*" --http.api "db, eth, net, web3, personal" --http.port "8545" --nodiscover --unlock 0xF122afAf3BEdae6E062Aa18e892ed8c0C9****** --password /root/data/pass.txt --mine --miner.threads 2
`

 run my geth node yesterday and it reached 22,000 blocks yesterday. And then I open and check my node today, data was reset including balances, contracts and blocks now it 6,000.

Is there any problems related to this that already solved? I been running geth for almost 1 month and I encountered the same problem. balances and always gone and blocks are reset.

NOTE:IM RUNNING THIS GETH NODE USING VPS UBUNTU OS & THIS IS FOR PRIVATE BLOCKCHAIN NETWORK

**Comment by MariusVanDerWijden** [comment]
Maybe the network experienced a reorg? Do you have logs that contain  `reorg` or `rewinding blockchain` ?

**Comment by laronlineworld** [comment]
> Maybe the network experienced a reorg? Do you have logs that contain `reorg` or `rewinding blockchain` ?

where exactly I see that rewinding or reorg?

**Comment by MariusVanDerWijden** [comment]
Not in the chaindata logs, in the docker logs or however you start your node

**Comment by laronlineworld** [comment]
> Not in the chaindata logs, in the docker logs or however you start your node

I started is using geth.service

**Comment by holiman** [comment]
> I started is using geth.service.

The logs may be in `journalctl` or `/var/log/syslog` or something. This can't really be debugged/investigated without logs.

**Comment by MariusVanDerWijden** [comment]
This issue got quite stale now. I'm going to close it for now, feel free to reopen if the issue still persists
