### ISSUE TITLE
Async block creation post-merge

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum/go-ethereum#25599]
async block creation only creates one block rn and does not update the pending block when new transactions are rolling in

**Comment by allboxes** [comment]
This would be great to see soon after the merge.  
CLs that send early FCUs will have potentially empty or nearly empty blocks if they propose after a builder block or after CL that does a very late FCU.  

This might push more validators to centralize on builders or CLs with late FCU.

**Comment by MariusVanDerWijden** [comment]
fixed long time ago
