### ISSUE TITLE
geth website docs/interface/peer-to-peer refers to outdated method to set static/trusted nodes

### ISSUE THREAD

**Issue by SLoeuillet** [ethereum/go-ethereum#25593]
#### What docs says

https://geth.ethereum.org/docs/interface/peer-to-peer
Static nodes datadir/geth/static-nodes.json
Trusted nodes <datadir>/geth/trusted-nodes.json

#### What happens if we follow doc

```
Aug 24 11:46:33 geth01-ethereum-mainnet-eu geth[1666228]: {"lvl":"warn","msg":"Found deprecated node list file /var/lib/geth/geth/static-nodes.json, please use the TOML config file instead.","t":"2022-08-24T11:46:33.831828285Z"}
Aug 24 11:46:33 geth01-ethereum-mainnet-eu geth[1666228]: {"lvl":"warn","msg":"Found deprecated node list file /var/lib/geth/geth/trusted-nodes.json, please use the TOML config file instead.","t":"2022-08-24T11:46:33.83204279Z"}
```

Is there an up to date example somewhere ?

**Comment by s1na** [comment]
@jmcook1186 wanna take a stab at this?

**Comment by s1na** [comment]
The documentation was updated with the up-to-date way to set these nodes. In the TOML config file that you pass to geth there's a field for static and trusted nodes. See https://geth.ethereum.org/docs/interface/peer-to-peer#static-nodes.

**Comment by SLoeuillet** [comment]
Thanks
