### ISSUE TITLE
ethclient - replace nil pointer on *Transaction when null address with real address

### ISSUE THREAD

**Issue by 41rjordan** [ethereum/go-ethereum#25607]
## Disclaimer
This is more an improvement than a feature, but there is no template for type:improvement :/  
I hope it is not critical.

# Rationale

When you're calling `*Client.BlockByNumber` (/ethclient) and then calling `*Block.Transactions()` with return value, return value is Transactions type (/core/types), which is de-facto []*Transaction. It contains transactions in the chosen block. In turn, *Transaction type contain functions that return value, from, to fields pointers etc, with functions `.Value()`, `From()`, `.To()` respectively.  
In case of `.To()`, this function returns *common.address type (/common), which is in fact pointer to an address that is in "to" field in transaction. To get an actual address, you should call `*tx.To()`. However, [if transaction is contract creation/ether burn, that is, has null address (0x00...00), pointer returned by .To() function will be nil.  ](https://github.com/ethereum/go-ethereum/blob/36874b63a1b56eed2b8e4b47ccea0337920b84b8/core/types/transaction.go#L283)
This is not useful, because, e. g., if you're parsing transactions in block, you should call `if tx.To() == nil { to := common.HexToAddress("0x00...` for **every** transaction.

### How is it right now
```
for _, tx := range block.Transactions() {
    if tx.To() == nil {
        to := common.HexToAddress("0x0000000000000000000000000000000000000000") // or to use pre-defined null address
    } else {
        to := *tx.To() // if to call it while pointer is nil, it will obviously cause segfault
    }
    // do anything else
}
```

### How it could work

```
for _, tx := range block.Transactions() {
    to := *tx.To() // if address is 0x00...00, it will just return common.Address with full zero bytes, and you can do anything with ready address (e.g. .String() etc)
    // do anything else
}
```

Honestly, I can’t understand why it was implemented this way, but if there was a task to make a more readable check for a null address, a function like `.IsNullAddress()` would be reasonable to implement (and more easy-to-understand btw, e. g. anyone who will check source code of anything that uses geth as a library, but doesn't understand how geth library works, won't understand under what conditions could a null pointer be obtained at all)

# Implementation

If I'm not wrong, To() is [here](https://github.com/ethereum/go-ethereum/blob/36874b63a1b56eed2b8e4b47ccea0337920b84b8/core/types/transaction.go#L285). It uses [copyAddressPtr](https://github.com/ethereum/go-ethereum/blob/36874b63a1b56eed2b8e4b47ccea0337920b84b8/core/types/transaction.go#L647) function to make a pointer for an address (?). Here is the check for the null address. Implementation: just remove first "if" :)

transaction.go, line 648:

```
if a == nil {
		return nil
	}
```

### If it can't be changed
I am not suggesting that this should be changed at any cost. If this logic has a reason, ok (but, it would be cool if it'll be at least mentioned in docs). However, I would like to know, why does it work like that. I think that removing the assignment to null address of a nil pointer would be a useful improvement. **Thanks in advance for your response!**

**Comment by holiman** [comment]
A missing `to` means that the transaction is of a certain type: a `create`-transaction. The data is interpreted as constructor code, which when executed returns the contract bytecode to deploy. 
A missing `to` is therefore very much not the same thing as sending something to `0x00..00`, but something entirely different. It's not about what choices the go-ethereum devs have made in their codebase, it's a fundamental specification on ethereum transactions.

**Comment by holiman** [comment]
So, basically, if you blindly try to convert `to` into an address, you _should_ hit an error / panic, because you're doing it wrong.
