### ISSUE TITLE
Abigen sol

### ISSUE THREAD

**Issue by emrahsariboz** [ethereum/go-ethereum#25604]
Is abigen command removed "sol" flag? I was able to run 

`abigen --sol=contract.sol  --pkg=pkg --out=pkg/solidity_wrapper/token.go
`
but now I can't. I get error of **flag provided but not defined: -sol**

**Comment by ray-themedium** [comment]
yeap.
This is the commit to remove `solc` flag. 8541ddbd951370b2a42df8d82b0633ff0efeba12

note this : https://geth.ethereum.org/docs/dapp/native-bindings

**Comment by emrahsariboz** [comment]
This is not good. How to generate a single binding from a contract that has multiple contract in it?

**Comment by ray-themedium** [comment]
```
$ ls
Contract1.sol Contract2.sol Main.sol
---
import "./Contract1.sol";
import "./Contract2.sol";
Contract Main is Contract1, Contract2 {
   .
   .
   .
}
---

$ solc --abi Main.sol -o build
$ abigen --abi ./build/Main.abi --pkg main --type Main --out Main.go
```
Like this. 
Doesn't it work?

**Comment by emrahsariboz** [comment]
Not really. It still generates three different abi file which I have to pass one by one to abigen.

**Comment by rjl493456442** [comment]
Can you provide an example for your case? What's the relationship between your three abi files? Maybe only one is required for binding generation?

Theoretically you can use the output from solc compiler and pass it to abigen. It shouldn't break your pipeline at all.

**Comment by StEvUgnIn** [comment]
I can't produce abi with hardhat nor foundry... I tried to do it with `solc` but it doesn't find any dependency...

**Comment by davidqhr** [comment]
Try to use `combined-json`

**Comment by MariusVanDerWijden** [comment]
Yes we deprecated the -sol flag in abigen. Contracts need to be compiled with solc and we can consume the abi and bin files from that. Will close this issue for now, for advice on how to compile multiple contracts into a single abi, please consult the solidity compiler repository or the ethereum stack exchange.

**Comment by harpy-wings** [comment]
Just in case if any body have this issue with hardhat or foundry:
1. Flatten the contracts 
```sh
hardhat flatten >> main.sol
```
2. use `solc` to generate abi files.
```sh
solc --abi main.sol -o build
```
3. use `abigen` to generate go files
```sh
abigen --abi=./build/Foo.abi --pkg=mypackage --out=./mypackage.go
```
