### ISSUE TITLE
Miner Address  0x0000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by ekawibisono** [ethereum/go-ethereum#25608]
Hello All,

Can You help me,

After Run All Node, I Check the explorer miner address is 0x0000000000000000000000000000000000000000,
![Screenshot from 2022-08-26 15-00-05](https://user-images.githubusercontent.com/22586872/186858375-3c5f10d7-0226-4399-bc98-cf3e6bb07aa1.png)

How i Can Fix?.

Geth Version 1.7.0

**Comment by holiman** [comment]
`1.7.0` -  wow, that's old, september 2017: https://github.com/ethereum/go-ethereum/releases/tag/v1.7.0

You need to set the miner address. Probably `--etherbase` or -`--coinbase`. I don't recall the option in such an old version.

**Comment by ekawibisono** [comment]
I'm using the latest version, still the same problem with the miner address

**Comment by holiman** [comment]
Oh, I just saw difficulty=1. So it's clique? Then it's just an error on that explorer, it doesn't figure out the sealer correctly.

**Comment by ekawibisono** [comment]
Hello @holiman 

How i Can fix this?. i check the geth miner same 0x00000000000
![Screenshot from 2022-08-27 15-27-58](https://user-images.githubusercontent.com/22586872/187022139-d1b67776-6904-43f8-b8f4-2e61a3deeb47.png)

Geth Version 1.10.23
![Screenshot from 2022-08-27 15-28-38](https://user-images.githubusercontent.com/22586872/187022160-658e890d-1b9c-4514-9a39-018651c0147e.png)

**Comment by hsienfu** [comment]
I have the same issue.
```
Geth
Version: 1.10.23-stable
Git Commit: d901d85377c2c2f05f09f423c7d739c0feecd90a
Git Commit Date: 20220824
Architecture: amd64 
Go Version: go1.18.5 
Operating System: linux   
```

**Comment by holiman** [comment]
Use the clique api, a method called clique.getSealer (?) if I recall correctly

**Comment by hsienfu** [comment]
<img width="983" alt="image" src="https://user-images.githubusercontent.com/35683231/189488062-b2e83851-c8d9-4204-9238-442df17453cc.png">
`clique.getSigners() ` is correctly, `clique.getSigner()` has crashed.

**Comment by hsienfu** [comment]
> Oh, I just saw difficulty=1. So it's clique? Then it's just an error on that explorer, it doesn't figure out the sealer correctly.

Call `clique.getSigner('hash')` result is correctly.
