### ISSUE TITLE
Frequent unindexed transactions after fresh sync with 1.10.23

### ISSUE THREAD

**Issue by adamkoch** [ethereum/go-ethereum#25620]
#### System information
Geth version: 1.10.23
OS & Version: Ubuntu 22.04.1

#### Expected behaviour
No continual, frequent, "unindexed transactions" logging.

#### Actual behaviour
Continual logging of "unindexed transactions":
```
INFO [08-27|20:21:23.819] Imported new chain segment               blocks=1   txs=131   mgas=15.098  elapsed=145.835ms   mgasps=103.527 number=15,423,650 hash=de39ba..55d1b4 dirty=1014.00MiB
INFO [08-27|20:21:23.823] Unindexed transactions                   blocks=1   txs=162   tail=13,073,651 elapsed=3.336ms
INFO [08-27|20:21:24.640] Imported new chain segment               blocks=1   txs=27    mgas=2.244   elapsed=431.786ms   mgasps=5.198   number=15,423,651 hash=7aabee..c1952f dirty=1012.92MiB
INFO [08-27|20:21:24.663] Unindexed transactions                   blocks=1   txs=12    tail=13,073,652 elapsed=5.325ms
INFO [08-27|20:22:11.547] Imported new chain segment               blocks=1   txs=360   mgas=29.996  elapsed=237.176ms   mgasps=126.471 number=15,423,652 hash=b849cc..96d10f dirty=1016.07MiB
INFO [08-27|20:22:11.549] Unindexed transactions                   blocks=1   txs=108   tail=13,073,653 elapsed=1.504ms
INFO [08-27|20:22:15.671] Imported new chain segment               blocks=1   txs=149   mgas=15.289  elapsed=179.028ms   mgasps=85.403  number=15,423,653 hash=6c4846..5344b2 dirty=1015.71MiB
INFO [08-27|20:22:15.677] Unindexed transactions                   blocks=1   txs=397   tail=13,073,654 elapsed=4.897ms
INFO [08-27|20:22:18.911] Imported new chain segment               blocks=1   txs=110   mgas=18.883  elapsed=101.967ms   mgasps=185.191 number=15,423,654 hash=8d9a06..49ddd8 dirty=1015.96MiB
INFO [08-27|20:22:18.913] Unindexed transactions                   blocks=1   txs=229   tail=13,073,655 elapsed=2.120ms
INFO [08-27|20:22:25.106] Imported new chain segment               blocks=1   txs=74    mgas=6.257   elapsed=50.760ms    mgasps=123.267 number=15,423,655 hash=98a708..54cff0 dirty=1016.05MiB
INFO [08-27|20:22:25.107] Unindexed transactions                   blocks=1   txs=42    tail=13,073,656 elapsed="661.722µs"
INFO [08-27|20:22:27.042] Imported new chain segment               blocks=1   txs=19    mgas=1.446   elapsed=19.256ms    mgasps=75.108  number=15,423,656 hash=737d74..393304 dirty=1015.83MiB
INFO [08-27|20:22:27.042] Unindexed transactions                   blocks=1   txs=21    tail=13,073,657 elapsed="350.415µs"
INFO [08-27|20:22:29.595] Imported new chain segment               blocks=1   txs=32    mgas=6.210   elapsed=38.052ms    mgasps=163.185 number=15,423,657 hash=8f3e21..dc0f6b dirty=1015.37MiB
```

#### Steps to reproduce the behaviour
I was affected by the 1.10.22 bug, I tried to shift the head back to an earlier date but ran into similar errors to others. I decided to just do a complete resync so I removed all my data and started the resync. After about 12-14 hours it successfully caught up to the latest block and I see `Imported new chain segment` (as per above) that matches the latest block.

However, for every `Imported new chain segment` I also see a `Unindexed transactions` log. This has been happening for ~2 days now.

There are a few others in the Geth Discord who seem to have similar issues.

It seems Geth is still running ok but before I ran into the `1.10.22` bug I never saw this behavior before.

Also what is the meaning of `tail` within the `Unindexed transactions` logs? It seems to be a very old block number and it is very slowly slowly making progress (block is incrementing) but it's such slow progress I'm not sure it will ever catch up.

**Comment by adamkoch** [comment]
I also see similar logs in this comment:
https://github.com/ethereum/go-ethereum/issues/25589#issuecomment-1226214944

**Comment by Jor-Tech** [comment]
Having the exact same behavior in the Geth logs as @adamkoch and I did not do a full resync after the v1.10.22 bug, but used the setHead method.

**Comment by jamesmorgan** [comment]
Also seeing this after a fresh upgrade - its been resyncing from about 8 weeks ago, unsure of why this reindex process has started  as all I did was upgrade geth as normal. First output line is

```
Aug 27 14:00:11 moonshot geth[1401]: INFO [08-27|14:00:11.363] Imported new chain segment               blocks=18 txs=2492 mgas=237.368 elapsed=8.194s mgasps=28.965 number=15,049,901 hash=6dbed9..ebaf40 age=1mo4w3h dirty=27.27MiB
```

I also see a warning about the merge happening but it looks like its way off in the future e.g. 

```
Aug 27 13:58:50 moonshot geth[1401]: WARN [08-27|13:58:50.946] Merge is configured, but no beacon client seen. Please ensure you have one available before the transition arrives! eta=2mo3w6d
```
Is this in relation to the current sync state and not the current time?

**Comment by rjl493456442** [comment]
Geth will only keep the transaction indexes of the last year by default, specifically `2350000` blocks. And the background thread will wipe the indexes before this threshold, print the log as `Unindexed transactions ...`.

I think it's expected, I am just very curious why these logs never occur before. It's a very old feature we delivered long time ago.

**Comment by adamkoch** [comment]
@rjl493456442 thanks for the extra info. I thought it was saying "there are unindexed transactions" but what you're saying is this log is saying it removed an index for those old transactions. Looking at the code, none of it looks touched for ~2 years AFAICT.

Perhaps somehow the full resync caused the much older blocked to be indexed and now it has a backlog of old tx's to unindex. Unindexing seems very slow (around 10 seconds+ per block). However, as you mentioned, the default is about 1 year of blocks in the index, so theoretically it should stop around the 1 year mark.

For me, it's currently at block 13081084 so within a day or two it should get to -365 days. Will report back then.

**Comment by rjl493456442** [comment]
> none of it looks touched for ~2 years AFAICT.

You mean your node hasn't been upgraded for 2 years? How can it survive though.

> However, as you mentioned, the default is about 1 year of blocks in the index, so theoretically it should stop around the 1 year mark

Since new blocks are being built all the time, the unindexer will keep working to unindex the indices of block `HEAD-2350000`, it will never stop.

**Comment by adamkoch** [comment]
> You mean your node hasn't been upgraded for 2 years? How can it survive though.

No I mean the geth code for unindexing transactions ([here](https://github.com/ethereum/go-ethereum/blob/e44d6551c3c872584722c366c863381f7e91df91/core/rawdb/chain_iterator.go#L338) and [here](https://github.com/ethereum/go-ethereum/blob/e44d6551c3c872584722c366c863381f7e91df91/core/blockchain.go#L2331))

> Since new blocks are being built all the time, the unindexer will keep working to unindex the indices of block HEAD-2350000, it will never stop.

Ah yeh good point. I guess hopefully the unindexing can unindex quicker than new blocks arrive. Otherwise this will continue on forever :(

**Comment by adamkoch** [comment]
> Ah yeh good point. I guess hopefully the unindexing can unindex quicker than new blocks arrive. Otherwise this will continue on forever :(

One thing I noticed is that there is exactly one `unindexed log` message for every `imported new chain segment`. Even if the unindexing only takes 1-2 seconds, it's still 1:1 ratio. If this is the case, it really will never catch up. Do you think that's expected? Maybe that's why it's "stuck".

**Comment by adamkoch** [comment]
Just to confirm this. I looked at my logs from 4-5 days back and the unindexed logs were ~370 days behind. And today, it is still ~370  days behind. So it will never catch up.

**Comment by rjl493456442** [comment]
```
INFO [08-27|20:21:23.819] Imported new chain segment               blocks=1   txs=131   mgas=15.098  elapsed=145.835ms   mgasps=103.527 number=15,423,650 hash=de39ba..55d1b4 dirty=1014.00MiB
INFO [08-27|20:21:23.823] Unindexed transactions                   blocks=1   txs=162   tail=13,073,651 elapsed=3.336ms
```

Look at this log, you import a new block `15,423,650`, then geth will try to unindex block `15,423,650 - 2350000 = 13073650`, so it reports `tail=13,073,651`. It's correct.

The 1 year threshold is just the *estimation*. We use `2350000` blocks to roughly represent 1 year time.

**Comment by adamkoch** [comment]
Ah I see. So this logging is essentially working as intended as it's unindexing ~1 year old blocks as it moves forward at the head.

The question is, why isn't this something everyone sees in their logs? And why wasn't I see this previously before I re-sync'd from scratch? Could it be that for some users the older blocks are not indexed so no need to unindex?

**Comment by rjl493456442** [comment]
@adamkoch I am also wondering why you guys don't see this logs. Which version are you using previously? What's the command line flags you used for your previous setup?

**Comment by adamkoch** [comment]
I generally stay up-to-date with latest version (maybe within a week of release). I was previously on 1.10.22 and before that 1.10.21. That said, I'm not sure I never had any unindexed transaction logs, it's more I don't recall seeing them show this frequently (1:1 ratio with `imported new chain segment` log).

Just to confirm though - are we saying that having one `Unindexed transactions` log matched with one `Imported new chain segment` is 100% expected in a healthy geth node? Is this what everyone sees?

**Comment by rjl493456442** [comment]
> Just to confirm though - are we saying that having one Unindexed transactions log matched with one Imported new chain segment is 100% expected in a healthy geth node? Is this what everyone sees?

yes, once we have a new block, a old block will be triggered for unindexing, by default. Unless you explicitly set to keep full indices.

**Comment by adamkoch** [comment]
> yes, once we have a new block, a old block will be triggered for unindexing, by default. Unless you explicitly set to keep full indices.

Thanks for confirming. Closing this issue as it is WAI.
