### ISSUE TITLE
Can remotedb be used to serve rpcs

### ISSUE THREAD

**Issue by ianhe8x** [ethereum/go-ethereum#25625]
I noticed there is a new `--remotedb` argument in cli, and found the PR https://github.com/ethereum/go-ethereum/pull/24836

I'm quite interested in this idea of remotedb, because I'm looking for a way to scale my geth rpc service without too much additional storage costs, and remotedb looks a perfect solution for that. Though due to lack of documents I'm not sure if remotedb can be used in that way.

**Comment by s1na** [comment]
As of now it's not possible to serve RPC using remotedb. If your goal is to have one master node and a few slave nodes, you can try the light-client approach here. In the gist I use the tracing API, but it could work for other methods too.

https://gist.github.com/s1na/ab834d1af2c91b3f67ee9ea692efdf55
