### ISSUE TITLE
err the method engine_exchangeTransitionConfigurationV1 does not exist/os not available?

### ISSUE THREAD

**Issue by navy665180** [ethereum/go-ethereum#25622]
before i use getn 1.10.21,this ok,then i upgrade to 1.10.23,the DB changed to another folder .then i copy the DB（geth-chaindata） to the new folder，then geth skying,but err:err the method engine_exchangeTransitionConfigurationV1 does not exist/os not available?

i want ti know the mistake,
PC:window10

**Comment by karalabe** [comment]
The `engine` namespace is only exposed on the `authrpc` endpoint. It was available on HTTP briefly to allow easier beacon client interfacing and development, but that was unsecure. You'll need to point your beacon client to the authrpc port (and jwtsecret file) and the API should work.
