### ISSUE TITLE
Snapshot extension registration failed Geth- Go Ethereum

### ISSUE THREAD

**Issue by RaoFaizanAkram** [ethereum/go-ethereum#25631]
I was trying to Mine some Görli Testnet. It's been almost a week and i can't mine and sync the node. First I was syncing the node on CPU with CPU mining. The node synced completely after 3 days and eth.syncing was returning false. That means that my node is not syncing more or completely synced but then I realized that node is taking too much storage(One issue). The command I was using is

Geth --goerli --datadir "E:"

After syncing of complete node I start mining using,

geth attach ipc://./pipe/geth.ipc personal.newAccount() miner.setEtherbase(eth.accounts[0]) miner.start(8)

and it returns that Mining is aborted due to unsync. and eth.hashrate = 0 always. Then i used ubuntu on Aws server to save my Time and storage. I started to sync the node but getting error, showing me always "connecting to Peers" and this error,

Snapshot extension registration failed peer=0a807721 err="peer connected on snap without compatible eth support".

I am using this command: geth --goerli --datadir Ethereum/ --port=30303 --syncmode full --http --http.addr 'localhost' --http.port 8501 --http.api 'personal,db,eth,net,web3,txpool,miner' --networkid 5 --miner.gasprice '0' -unlock '0x98d692FB78583c4936B8CE7eF4F332191195B5FA' --password Ethereum/password.txt --mine --allow-insecure-unlock

Geth Version: 1.10.21-stable Git Commit: 671094279e8d27f4b4c3c94bf8b636c26b473976 Git Commit Date: 20220727 Architecture: amd64 Go Version: go1.18.4 Operating System: windows GOPATH= GOROOT=go Ubuntu on Aws server

Note: After starting the node on server i also tried to sync the node on my CPU. It is showing me the same error on my CPU and also on server.

A little help would be appreciated. Thank you!
![Screenshot (79)](https://user-images.githubusercontent.com/106604288/187373471-039c21e7-0d23-4280-bb72-580f3f9481de.png)

**Comment by karalabe** [comment]
You're missing quite a few important details.

Goerli was a PoA network originally. You can't CPU mine it, only authorized signers were able to produce blocks.

Currently Goerli has already passed the Merge with the Praeter beacaon chain, meaning it's driven by a consensus/beacon client. Setting up a post merge validtor is a bit more involved, you'll need to follow https://goerli.launchpad.ethereum.org/en/.

Even to sync post merge, you need to set up a beacon client side by side with Geth, as the beacon client will be the one driving the chain selection.

**Comment by karalabe** [comment]
Still more infos here: https://blog.ethereum.org/2022/07/27/goerli-prater-merge-announcement

**Comment by RaoFaizanAkram** [comment]
Thank you so much for your time and response. I want to know is it
possible for me to start mining on CPU with an Authorised signer? How can i
add it?
