### ISSUE TITLE
Contract creation for private network hangs

### ISSUE THREAD

**Issue by claravanstaden** [ethereum/go-ethereum#25633]
#### System information

Geth version: `1.10.23-stable`
OS & Version: Linux
Commit hash : N/A

#### Expected behaviour
When deploying a smart contract to the local geth node in a private network, contract creation succeeded. Last tested successfully with 1.10.18.

#### Actual behaviour
With Geth 1.10.23, contract creation just hangs and never completes.

#### Steps to reproduce the behaviour
Genesis.json
```
{
  "config": {
    "chainId": 15,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "muirGlacierBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0,
    "ethash": {},
    "terminalTotalDifficulty": 0
  },
  "difficulty": "0x9FFE0",
  "gasLimit": "80000000",
  "alloc": {
    "90A987B944Cb1dCcE5564e5FDeCD7a54D3de27Fe": {
      "balance": "100000000000000000000"
    },
    "Be68fC2d8249eb60bfCf0e71D5A0d2F2e292c4eD": {
      "balance": "100000000000000000000"
    },
    "89b4AB1eF20763630df9743ACF155865600daFF2": {
      "balance": "100000000000000000000"
    },
    "04E00e6D2e9Ea1E2AF553De02A5172120BFA5c3e": {
      "balance": "100000000000000000000"
    },
    "a255dC78C1510e2c1332fBAC2de848058f479CEE": {
      "balance": "100000000000000000000"
    },
    "ACbd24742b87c34dED607FB87b22401B2Ede167E": {
      "balance": "100000000000000000000"
    },
    "01F6749035e02205768f97e6f1d394Fb6769EC20": {
      "balance": "100000000000000000000"
    },
    "8b66D5499F52D6F1857084A61743dFCB9a712859": {
      "balance": "100000000000000000000"
    },
    "13e16C4e5787f878f98a610EB321170512b134D4": {
      "balance": "100000000000000000000"
    },
    "eEBFA6B9242A19f91a0463291A937a20e3355681": {
      "balance": "100000000000000000000"
    },
    "87D987206180B8f3807Dd90455606eEa85cdB87a": {
      "balance": "100000000000000000000"
    }
  }
}
```
Geth command
```
        geth init --datadir "$data_dir" "$output_dir/genesis.json"
        geth account import --datadir "$data_dir" --password /dev/null config/dev-example-key0.prv
        geth account import --datadir "$data_dir" --password /dev/null config/dev-example-key1.prv
        geth --vmdebug --datadir "$data_dir" --networkid 15 \
            --http --http.api debug,personal,eth,net,web3,txpool,engine,miner --ws --ws.api debug,eth,net,web3 \
            --rpc.allow-unprotected-txs --mine --miner.threads=1 \
            --miner.etherbase=0x0000000000000000000000000000000000000000 \
            --allow-insecure-unlock \
            --authrpc.jwtsecret config/jwtsecret \
            --unlock 0xBe68fC2d8249eb60bfCf0e71D5A0d2F2e292c4eD,0x89b4AB1eF20763630df9743ACF155865600daFF2 \
            --password /dev/null \
            --rpc.gascap 100000000 \
            --trace "$data_dir/trace" \
            --gcmode archive \
            --miner.gasprice=0 \
            > "$output_dir/geth.log" 2>&1 &
```
Start Geth `1.10.23` up with the following command and deploy any smart contract. Contract creation doesn't complete.

**Comment by karalabe** [comment]
You'll have to provide an example as to what doesn't succeed and logs as to what's happening. Your reports is much to vague to reasonable assess. Not for other reasons, but this surely works, so something seems to be off in your setup, that's what we need to find.

**Comment by claravanstaden** [comment]
Thanks for the response @karalabe! I compared the two version's logs but couldn't see anything useful there, both logs just show the contract was submitted for creation but nothing about it afterwards.

```
INFO [08-30|09:07:31.281] Submitted contract creation              hash=0x5f0e7e500d834c8a0d37bd9c3732a8a54948bc4eb21360406ae2490be55c45bf from=0xBe68fC2d8249eb60bfCf0e71D5A0d2F2e292c4eD nonce=0 contract=0x86D9aC0Bab011917f57B9E9607833b4340F9D4F8 value=0
```

I had a look at the release logs to see if there is something configuation-wise that could have affected this, but couldn't see anything relevant. Do you know if anything that could possibly affect this? Then I can debug it and get out of your hair. 😄

**Comment by claravanstaden** [comment]
After some further digging, it looks there is a problem between the consensus client and the execution client for my specific case. I am using Lodestar, and seeing some errors in their logs. I am chatting to them about it, but it looks like Lodestar gets invalid updates from `engine_forkchoiceUpdatedV1`.

It looks like [this condition](https://github.com/ChainSafe/lodestar/blob/db9450ba2ee4ac90469999450a16d143f6127961/packages/beacon-node/src/execution/engine/http.ts#L248) is triggered. Did anything chance in the `engine_forkchoiceUpdatedV1` `SYNCING` API spec implementation, by any chance?

**Comment by karalabe** [comment]
I have a hunch. Start Geth with `--syncmode=full`. By default it wants to snap sync and will refuse to mine a block until a sync cycle completes. But in your case, a brand new network, there's nothing to sync, so you'll have to nudge it to start processing/making blocks immediately.

**Comment by claravanstaden** [comment]
🙌 Amazing! It worked! Much appreciated, Peter.
