### ISSUE TITLE
invalid merkle root    Skip duplicated bad block

### ISSUE THREAD

**Issue by mafangtao** [ethereum/go-ethereum#25649]
when update from 10.22 -- > 10.23

```
Aug 31 15:11:14 ip-172-31-6-46 geth[714]: Error: invalid merkle root (remote: 612733f1af09236a97bb12d94dd21217b4b53fcf293110bdad541217e77e9fdf local: 2e56f789e7daaef21f546a31f5ae46332ec2f1200fd8d84dcf3f636ec3b8c5b1)
Aug 31 15:11:14 ip-172-31-6-46 geth[714]: ##############################
Aug 31 15:11:14 ip-172-31-6-46 geth[714]:  
Aug 31 15:11:14 ip-172-31-6-46 geth[714]: ERROR[08-31|15:11:14.938] Failed to retrieve beacon bounds for bad block reporting err="beacon sync not yet started"
Aug 31 15:11:14 ip-172-31-6-46 geth[714]: WARN [08-31|15:11:14.938] Synchronisation failed, dropping peer    peer=abd140b8515077071b8b19a561eb19d23fe7235ec43d13c0d55324ebf3fc7ced err="retrieved hash chain is invalid: invalid merkle root (remote: 612733f1af09236a97bb12d94dd21217b4b53fcf293110bdad541217e77e9fdf local: 2e56f789e7daaef21f546a31f5ae46332ec2f1200fd8d84dcf3f636ec3b8c5b1)"
Aug 31 15:11:20 ip-172-31-6-46 geth[714]: INFO [08-31|15:11:20.669] Looking for peers                        peercount=2 tried=35 static=0
Aug 31 15:11:25 ip-172-31-6-46 geth[714]: WARN [08-31|15:11:25.753] Trie prefetcher failed opening trie      root=1607f2..9b69a4 err="missing trie node 1607f241c92b7106787b33a3aea849464c8159c0560272f83c4c8edb4a9b69a4 (owner 0e83ee9276d1a698ef92281bf20fa38ce18a36b3faa442e74654d1b61535cfd1) (path ) <nil>"
Aug 31 15:11:25 ip-172-31-6-46 geth[714]: INFO [08-31|15:11:25.888] Skip duplicated bad block                number=15,441,988 hash=80b270..d68848
Aug 31 15:11:25 ip-172-31-6-46 geth[714]: ERROR[08-31|15:11:25.898]
Aug 31 15:11:25 ip-172-31-6-46 geth[714]: ########## BAD BLOCK #########
Aug 31 15:11:25 ip-172-31-6-46 geth[714]: Chain config: Chain ID:  1 (mainnet)
Aug 31 15:11:25 ip-172-31-6-46 geth[714]: Consensus: Beacon (proof-of-stake), merging from Ethash (proof-of-work)


Aug 31 15:11:25 ip-172-31-6-46 geth[714]:  - Network known to be merged: false
Aug 31 15:11:25 ip-172-31-6-46 geth[714]:  - Total terminal difficulty:  58750000000000000000000
Aug 31 15:11:25 ip-172-31-6-46 geth[714]:  - Merge netsplit block:       <nil>
Aug 31 15:11:25 ip-172-31-6-46 geth[714]: Number: 15441988
Aug 31 15:11:25 ip-172-31-6-46 geth[714]: Hash: 0x80b27076c47447bc3163849c36229bf9487dd38980cd1ff7f6b227cf47d68848
Aug 31 15:11:25 ip-172-31-6-46 geth[714]:          0: cumulative: 178761 gas: 178761 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x89dc4217de7f789c60bea22acc12420371abffaa75272e728a5d018030cb45f2 logs: [0xc0725ac2c0 0xc0725ac580 0xc0725ac8f0 0xc0725acbb0 0xc0725acd10 0xc0725ace70 0xc0725ad080] bloom: 00200000000000010080000080000000000000000000000000000000000000000004000000000000000000000200020002000000080000000000000000400000000000000000000008000008000000200000000000000000000000000000000000000000000000000000200020002040000000000000000000000010200000000000040000400000000000000000000000000000010000080000004100000000000000000000200000000000000000004000000000000000000000000000000000002002080000001000000000010000000000000402001000000000000000000000200000000000000000000000000000000000000000000000000000000000 state:
Aug 31 15:11:25 ip-172-31-6-46 geth[714]:          1: cumulative: 379364 gas: 200603 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x0eca2b5db9169aeb0e7ddd52f3916d1e2647ea093fa11db1fd5dd57829f5997b logs: [0xc0725adad0 0xc0725adce0 0xc06e014000 0xc06e014160 0xc06e0142c0 0xc06e014420 0xc06e014580 0xc06e014630] bloom: 00200000010800000000000080000000000008004000000000000000040000020000000008000000000008000200020002000000080020000000000000400000000000000000000808000008000000200000000000000000000000000000000000000000000000000000200000000040000000000000000000000010200800000000000000000000000000000000000000008000010000080000004100000000000000000000200000000000000000000000000000000000002008000008000000002002000000001000000000000000000000000000001000000000000040000000200000000000000010000000000000000000040000000000000000000000 state:
Aug 31 15:11:25 ip-172-31-6-46 geth[714]:          2: cumulative: 564324 gas: 184960 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xca1aa4741082fc1cb563b4a06b2ee477fac52bd36327a2dce1e25aa59a8ee3f1 logs: [0xc06e0146e0 0xc06e014790 0xc06e014840 0xc06e0149a0 0xc06e014a50 0xc06e014b00 0xc06e014bb0] bloom: 00200000000000000000000080000000000000000000000000800000000000040000000000000040000000000000000002000000080001000000000000000000000000000000000008080008000000200000000200020000000000000000000000020000000000000004080000000000000200000000000000000010000000000000000000000000100000000000002000000010010000080000004000000000000000000000200000100000000000000000000000000000000000000000000000000002000000000400000000000000000000000000081000000000000000000000200000002000000000000000000000000000000000000000000000180000 state:
Aug 31 15:11:25 ip-172-31-6-46 geth[714]:          3: cumulative: 701899 gas: 137575 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x81fc55d8fbda2f2330377b03070b94dea84101e3977919184c70bc53764f74b3 logs: [0xc06e014d10 0xc06e014e70 0xc06e014f20 0xc06e014fd0 0xc06e015080 0xc06e0151e0] bloom: 00200000010000000000000080000000000000000000000000800000040000040000000000000000000008000000000002000000080020000000000000000000000000000000000808000008000000200200000000020000000000000000000000000000000000000000000000000000000000000000000000000010000800000000000000000000000000000000002000000000010000080000004000000000000000000000200000000000000000000000000000000000002000000008000000000002000000000400000000000000000000000000081000000000000008000000200000002000000010000000000000000000000000000000000000000000 state:
Aug 31 15:11:25 ip-172-31-6-46 geth[714]:          4: cumulative: 798768 gas: 96869 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x56624761caa554c6388942948a008998b22f11433c8eb96ebd42a7884da4b068 logs: [0xc06e015340 0xc06e0153f0 0xc06e0154a0 0xc06e015600] bloom: 00200000000000000000000080000000000000000000004000000000000001000000000000000000000000000000000002000000080000000000000000000000000000000000000400000008000000200020000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000040000080000004000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000001000000000000000011000000008000000000002200000000000000008000022000000000000000000000000000000000000 state:
Aug 31 15:11:25 ip-172-31-6-46 geth[714]:          5: cumulative: 1060580 gas: 261812 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xccd4b2774cb3a500a6b73988560095160eed813dea98fb7bfab6475d481448a1 logs: [0xc06e0156b0 0xc06e015760 0xc06e015810 0xc06e0158c0 0xc06e015a20 0xc06e015ad0 0xc06e015b80 0xc06e015c30 0xc06e015ce0 0xc06e015d90 0xc06e015ef0 0xc06e0780b0 0xc06e078160 0xc06e078210] bloom: 002000000000000400000000800001000000000000000040000000000800030000000000000000000000400000000a0002000000080000000000000004000020000000000000200040000008000000200020000000000000100000004000000000000000000008000000000000000000000000001000001402000010000000000000000000000000000000000100000000000000044080080000014000000000040000010000000004010000001200000000000000000000000000000000000400000002200000000000002001000000000000000008011000000008000804000000200000000040000008000022000000000041000001000000000000000000 state:
Aug 31 15:11:25 ip-172-31-6-46 geth[714]:          6: cumulative: 1286254 gas: 225674 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xa21c9e5f4155ca717abdefddcbbaefafe2d6f2a1f3db2ea68be33e91a4943da1 logs: [0xc06e078370 0xc06e0784d0 0xc06e078580 0xc06e078630] bloom: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000002000400000000000000000000004080000000100100000000000000000000000000000001000000200000800000000000008000000200000000040000000100000200000000000008000000000000000800004000010000040000000000000000002000200000000010000000000000000000000000000100000000000000000000000000000020000000000000000080000000000000000000010000000040000a0008010000000000000000010000000000000000000000000000000000000000000 state:
Aug 31 15:11:25 ip-172-31-6-46 geth[714]:          7: cumulative: 1333460 gas: 47206 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xfd948e4e98e15f828210ecee9d49e9de65f3dd61d8ed1856ef1da84279a539ac logs: [0xc06e0786e0] bloom: 00000000000020008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000004020000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000400000000000000000000000100000000000010000000000000000000000000080000000000000000000000000000000000 state:

```

**Comment by rjl493456442** [comment]
Did you set head back to the point you upgraded to 1.10.22?

**Comment by mafangtao** [comment]
I return 1.10.22,not work ,still err

eth err block is 15441988 ,
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]: Number: 15441988
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]: Hash: 0x80b27076c47447bc3163849c36229bf9487dd38980cd1ff7f6b227cf47d68848

Error: invalid merkle root (remote: 612733f1af09236a97bb12d94dd21217b4b53fcf293110bdad541217e77e9fdf local: 2e56f789e7daaef21f546a31f5ae46332ec2f1200fd8d84dcf3f636ec3b8c5b1)




Sep 01 04:01:27 ip-172-31-6-46 geth[38561]: Error: invalid merkle root (remote: 612733f1af09236a97bb12d94dd21217b4b53fcf293110bdad541217e77e9fdf local: 2e56f789e7daaef21f546a31f5ae46332ec2f1200fd8d84dcf3f636ec3b8c5b1)
Sep 01 04:01:27 ip-172-31-6-46 geth[38561]: ##############################
Sep 01 04:01:27 ip-172-31-6-46 geth[38561]:  
Sep 01 04:01:27 ip-172-31-6-46 geth[38561]: ERROR[09-01|04:01:27.534] Failed to retrieve beacon bounds for bad block reporting err="beacon sync not yet started"
Sep 01 04:01:27 ip-172-31-6-46 geth[38561]: WARN [09-01|04:01:27.534] Synchronisation failed, dropping peer    peer=5f0ea683c460ccc94ead48a9f0991247009f46c971891bde8eacceb6ae3a2172 err="retrieved hash chain is invalid: invalid merkle root (remote: 612733f1af09236a97bb12d94dd21217b4b53fcf293110bdad541217e77e9fdf local: 2e56f789e7daaef21f546a31f5ae46332ec2f1200fd8d84dcf3f636ec3b8c5b1)"
Sep 01 04:01:28 ip-172-31-6-46 geth[38561]: INFO [09-01|04:01:28.266] Looking for peers                        peercount=1 tried=31 static=0
Sep 01 04:01:38 ip-172-31-6-46 geth[38561]: INFO [09-01|04:01:38.579] Looking for peers                        peercount=2 tried=32 static=0
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]: WARN [09-01|04:01:42.815] Trie prefetcher failed opening trie      root=1607f2..9b69a4 err="missing trie node 1607f241c92b7106787b33a3aea849464c8159c0560272f83c4c8edb4a9b69a4 (owner 0e83ee9276d1a698ef92281bf20fa38ce18a36b3faa442e74654d1b61535cfd1) (path ) <nil>"
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]: INFO [09-01|04:01:42.868] Skip duplicated bad block                number=15,441,988 hash=80b270..d68848
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]: ERROR[09-01|04:01:42.877]
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]: ########## BAD BLOCK #########
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]: Chain config: Chain ID:  1 (mainnet)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]: Consensus: Beacon (proof-of-stake), merging from Ethash (proof-of-work)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]: Pre-Merge hard forks:
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Homestead:                   1150000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/homestead.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - DAO Fork:                    1920000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/dao-fork.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Tangerine Whistle (EIP 150): 2463000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/tangerine-whistle.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Spurious Dragon/1 (EIP 155): 2675000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Spurious Dragon/2 (EIP 158): 2675000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Byzantium:                   4370000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/byzantium.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Constantinople:              7280000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/constantinople.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Petersburg:                  7280000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/petersburg.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Istanbul:                    9069000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/istanbul.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Muir Glacier:                9200000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/muir-glacier.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Berlin:                      12244000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/berlin.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - London:                      12965000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/london.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Arrow Glacier:               13773000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/arrow-glacier.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Gray Glacier:                15050000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/gray-glacier.md)
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]: Merge configured:
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Hard-fork specification:    https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Network known to be merged: false
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Total terminal difficulty:  58750000000000000000000
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:  - Merge netsplit block:       <nil>
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]: Number: 15441988
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]: Hash: 0x80b27076c47447bc3163849c36229bf9487dd38980cd1ff7f6b227cf47d68848
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:          0: cumulative: 178761 gas: 178761 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x89dc4217de7f789c60bea22acc12420371abffaa75272e728a5d018030cb45f2 logs: [0xc013c90e70 0xc013c90f20 0xc013c90fd0 0xc013c91ad0 0xc014879760 0xc014879810 0xc014879ef0] bloom: 00200000000000010080000080000000000000000000000000000000000000000004000000000000000000000200020002000000080000000000000000400000000000000000000008000008000000200000000000000000000000000000000000000000000000000000200020002040000000000000000000000010200000000000040000400000000000000000000000000000010000080000004100000000000000000000200000000000000000004000000000000000000000000000000000002002080000001000000000010000000000000402001000000000000000000000200000000000000000000000000000000000000000000000000000000000 state:
Sep 01 04:01:42 ip-172-31-6-46 geth[38561]:          1: cumulative: 379364 gas: 200603 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x0eca2b5db9169aeb0e7ddd52f3916d1e2647ea093fa11db1fd5dd57829f5997b logs: [0xc0000f6420 0xc0000f64d0 0xc0000f6580 0xc0000f6630 0xc0000f66e0 0xc0000f6790 0xc0000f6bb0 0xc0000f6c60] bloom: 00200000010800000000000080000000000008004000000000000000040000020000000008000000000008000200020002000000080020000000000000400000000000000000000808000008000000200000000000000000000000000000000000000000000000000000200000000040000000000000000000000010200800000000000000000000000000000000000000008000010000080000004100000000000000000000200000000000000000000000000000000000002008000008000000002002000000001000000000000000000000000000001000000000000040000000200000000000000010000000000000000000040000000000000000000000 state:

**Comment by rjl493456442** [comment]
Should be fixed by resetting head, or resync from scratch. Close it.
