### ISSUE TITLE
  unavailable="['debug']" available="[admin debug web3 eth txpool personal clique miner net]

### ISSUE THREAD

**Issue by jjhesk** [ethereum/go-ethereum#25647]
#### System information

Geth version: `geth version`  
instance: Geth/v1.10.17-stable-25c9b49f/linux-amd64/go1.18
at block: 271560 (Wed Aug 31 2022 21:59:25 GMT+0800 (CST))
 datadir: /mnt/kotnode/.ethereum
 modules: admin:1.0 clique:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

OS & Version: Windows/Linux/OSX LINUX CENTOS 8
Commit hash : (if `develop`)

I got my setup 
```
HTTP_ARGS="--http --http.port 8545 --http.corsdomain '*' --http.addr 0.0.0.0 --http.api  'debug,eth,web3,net,txpool,clique'"
#admin debug web3 eth txpool personal clique miner net
WS_ARGS="--ws --ws.api 'debug,eth,net,web3' --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins '*'"

#su ethnode -c $GETH --datadir $DATADIR --syncmode 'full' --gcmode archive --port 30311 --networkid $CHAIN_ID $HTTP_ARGS --ws --ws.api "eth,net,web3,debug,txpool" --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --bootnodes $ENODE $MINER_ARGS --allow-insecure-unlock --unlock $ETHACCOUNT --password $DATADIR/protectpass.txt 

nohup $GETH --datadir $DATADIR --syncmode 'full' --gcmode archive --port 30311 --networkid $CHAIN_ID $HTTP_ARGS $WS_ARGS --bootnodes $ENODE $MINER_ARGS --allow-insecure-unlock --unlock $ETHACCOUNT --password $DATADIR/protectpass.txt  --verbosity 1 > $DATADIR/block.log &
```

#### Actual behaviour

ERROR[08-31|21:52:21.214] Unavailable modules in HTTP API list     unavailable="['debug clique']" available="[admin debug web3 eth txpool personal clique miner net]"
ERROR[08-31|21:52:21.214] Unavailable modules in HTTP API list     unavailable="['debug web3']"   available="[admin debug web3 eth txpool personal clique miner net]"

**Comment by karalabe** [comment]
Your bash variable expansion is wrong, it passes the string with the quotation marks to Geth, not just the content. I.e. the flag is set to `'debug,eth,web3,net,txpool,clique'`, which when we parse the commas ends up with `'debug` (notice beginning quote) and `clique'` (notice end quote). Just drop the `'` marks altogether. The reason we've made the list comma separated instead of space separated is exactly to avoid weird variable expansion errors.
