### ISSUE TITLE
online pruning feature on ETH

### ISSUE THREAD

**Issue by masayil** [ethereum/go-ethereum#25659]
Is it possible to implement this feature on ETH?

**Comment by MariusVanDerWijden** [comment]
Yes, we are working on online pruning already, its a bit complicated though

**Comment by kai-zhong** [comment]
@MariusVanDerWijden come on. 

Disks can easily fill up over time. Every time you have to stop for pruning, it will have a certain impact on the running business. Hope to use online pruning soon.

By the way, I only run Geth for full synchronization, just to query block data, transaction data, etc. Do I need to install a consensus client?

**Comment by MariusVanDerWijden** [comment]
Yes you need to run a consensus client, even if you are not proposing blocks
