### ISSUE TITLE
1.4.3 miner panic

### ISSUE THREAD

**Issue by datajerk** [ethereum/go-ethereum#2565]
#### System information

Geth version:

```
Geth
Version: 1.4.3-stable-f213a9d8
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=
GOROOT=/usr/local/go
```

OS & Version: `Linux miner0 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 x86_64 x86_64 GNU/Linux`

Commit hash : (if `develop`)
#### Expected behaviour

Not crash.
#### Actual behaviour

```
I0512 18:12:19.712998 core/blockchain.go:959] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 22.963058ms. #125 [3e974935 / 3e974935]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x569474]

goroutine 92 [running]:
panic(0xe9bea0, 0xc82000e0a0)
        /tmp/go/src/runtime/panic.go:481 +0x3e6
math/big.(*Int).Cmp(0xc8205537c0, 0x0, 0xc82244e730)
        /tmp/go/src/math/big/int.go:314 +0x24
github.com/ethereum/go-ethereum/core.(*BlockChain).WriteBlock(0xc82244e700, 0xc8212d0000, 0xc82008ce00, 0x0, 0x0)
        /tmp/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:777 +0x30f
github.com/ethereum/go-ethereum/miner.(*worker).wait(0xc8203285a0)
        /tmp/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:287 +0xe21
created by github.com/ethereum/go-ethereum/miner.newWorker
        /tmp/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:150 +0x5a8
```
#### Steps to reproduce the behaviour

Start mining.  Random.
#### Backtrace

```
[backtrace]
```

**Comment by obscuren** [comment]
I've never seen this myself. Have you modified the code or did something out of the ordinary before this happened? Do you maybe more  details?

On a side note, I'm reworking the mining code.

**Comment by datajerk** [comment]
No code changes, private chain, options:

`--shh --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3 --nat extip:198.23.124.17 --identity miner0 --networkid 2659256549 --port 40401 --rpc --minerthreads 1 --mine --etherbase c328c01f960a09703510b929caab11c5b493e34b --bootnodes enode://a02bee7594cccac8146c2876090f66f41e736c1376292bb980ff088eb918951d4a966a559b42cc5b057c1d2b3b7cec9f382ffdea9dbca15dd569b872b500279d@198.23.124.17:40404`
