### ISSUE TITLE
ethminer can't find mining work in geth's rpc(8545)

### ISSUE THREAD

**Issue by zhongdonglin** [ethereum/go-ethereum#25665]
state:
     start geth： nohup geth --datadir data --http --http.addr 0.0.0.0 --http.api eth --miner.etherbase  ****** & > nohup.out
     start ethminer:    nohup ./ethminer -v 9 -U -P http://127.0.0.1:8545 & > nohup.out

question:
     ethminer log print:
          `ethminer 0.18.0
Build: linux/release/gnu

 i 09:26:21 ethminer Configured pool 127.0.0.1:8545
 i 09:26:21 ethminer Selected pool 127.0.0.1:8545
 i 09:26:21 ethminer Established connection to 127.0.0.1:8545
 i 09:26:21 ethminer Spinning up miners...
 i 09:26:21 ethminer  >> {"id":1,"jsonrpc":"2.0","method":"eth_getWork","params":[]}
cu 09:26:21 cuda-0   Using Pci Id : 01:00.0 NVIDIA GeForce RTX 3090 (Compute 8.6) Memory : 23.70 GB
 i 09:26:21 ethminer  << {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"no mining work available yet"}}
 X 09:26:21 ethminer Got code:-32000 message:no mining work available yet  from 127.0.0.1:8545
`

**Comment by rjl493456442** [comment]
You node just started and nothing is passed as the sealing task. So no mining work generated yet.
You can wait a bit and confirm that your node is synced.

**Comment by zhongdonglin** [comment]
ou....geth has been synced to the latest block of the chain.I started ethminer after the sync is complete

**Comment by rjl493456442** [comment]
did you enable mining? `--mine`

**Comment by zhongdonglin** [comment]
I've tried turning it enable, but geth doesn't start mining. It is worth mentioning here that ethming outputs "SIGSEGV encountered".

**Comment by rjl493456442** [comment]
Could you post some logs from Geth side?

**Comment by zhongdonglin** [comment]
`INFO [09-05|01:16:40.138]
INFO [09-05|01:16:40.138] Merge configured:
INFO [09-05|01:16:40.138]  - Hard-fork specification:    https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet
-upgrades/paris.md
INFO [09-05|01:16:40.138]  - Network known to be merged: false
INFO [09-05|01:16:40.138]  - Total terminal difficulty:  58750000000000000000000
INFO [09-05|01:16:40.138]  - Merge netsplit block:       <nil>
INFO [09-05|01:16:40.138] ---------------------------------------------------------------------------------------------------------------
------------------------------------------
INFO [09-05|01:16:40.138]
INFO [09-05|01:16:40.599] Disk storage enabled for ethash caches   dir=/geth/data/geth/ethash count=3
INFO [09-05|01:16:40.600] Disk storage enabled for ethash DAGs     dir=/home/test/.ethash     count=2
INFO [09-05|01:16:40.600] Initialising Ethereum protocol           network=1 dbversion=8
INFO [09-05|01:16:40.854] Loaded most recent local header          number=15,474,954 hash=3aaca3..5cef63 td=57,986,185,633,137,431,257,48
8 age=2m35s
INFO [09-05|01:16:40.854] Loaded most recent local full block      number=15,474,954 hash=3aaca3..5cef63 td=57,986,185,633,137,431,257,48
8 age=2m35s
INFO [09-05|01:16:40.854] Loaded most recent local fast block      number=15,474,954 hash=3aaca3..5cef63 td=57,986,185,633,137,431,257,488 age=2m35s
INFO [09-05|01:16:40.854] Loaded last fast-sync pivot marker       number=15,455,348
INFO [09-05|01:16:40.973] Loaded local transaction journal         transactions=0 dropped=0
INFO [09-05|01:16:40.973] Regenerated local transaction journal    transactions=0 accounts=0
WARN [09-05|01:16:40.973] Switch sync mode from snap sync to full sync
WARN [09-05|01:16:40.973] Chain pre-merge, sync via PoW (ensure beacon client is ready)
INFO [09-05|01:16:40.973] Gasprice oracle is ignoring threshold set threshold=2
WARN [09-05|01:16:40.974] Engine API enabled                       protocol=eth
INFO [09-05|01:16:40.974] Starting peer-to-peer node               instance=Geth/v1.10.23-stable-d901d853/linux-amd64/go1.18.5
INFO [09-05|01:16:41.026] New local node record                    seq=35 id=14432cdccc4e030c ip=127.0.0.1 udp=30303 tcp=30303
INFO [09-05|01:16:41.026] Started P2P networking                   self=enode://b0ccdf06d9a0e28a912815d7f4121b8e6c9785e08c096ff1afed74545f6b8048acf34249f91f4b7a2b3f36ff5e16077f757b6cb024a28360512598476aafa4e4@127.0.0.1:30303
INFO [09-05|01:16:41.027] IPC endpoint opened                      url=/geth/data/geth.ipc
INFO [09-05|01:16:41.027] Loaded JWT secret file                   path=/geth/data/geth/jwtsecret crc32=0x18e52e4c
INFO [09-05|01:16:41.028] HTTP server started                      endpoint=[::]:8545 auth=false prefix= cors=0.0.0.0 vhosts=localhost
INFO [09-05|01:16:41.028] WebSocket enabled                        url=ws://127.0.0.1:8551
INFO [09-05|01:16:41.028] HTTP server started                      endpoint=127.0.0.1:8551 auth=true  prefix= cors=localhost vhosts=localhost
INFO [09-05|01:16:41.028] Transaction pool price threshold updated price=0
INFO [09-05|01:16:41.029] Updated mining threads                   threads=0
INFO [09-05|01:16:41.029] Transaction pool price threshold updated price=1,000,000,000
INFO [09-05|01:16:41.030] Commit new sealing work                  number=15,474,955 sealhash=f4c1a0..2075ec uncles=0 txs=0 gas=0 fees=0 elapsed="822.701µs"
INFO [09-05|01:16:41.030] Commit new sealing work                  number=15,474,955 sealhash=f4c1a0..2075ec uncles=0 txs=0 gas=0 fees=0 elapsed="994.987µs"
INFO [09-05|01:16:48.797] New local node record                    seq=36 id=14432cdccc4e030c ip=219.134.169.215 udp=25611 tcp=30303
INFO [09-05|01:16:53.029] Looking for peers                        peercount=0 tried=21 static=0
INFO [09-05|01:17:03.033] Looking for peers                        peercount=0 tried=21 static=0
INFO [09-05|01:17:13.078] Looking for peers                        peercount=0 tried=34 static=0
WARN [09-05|01:17:16.018] Merge is configured, but no beacon client seen. Please ensure you have one available before the transition arrives! eta=1w4d15h
INFO [09-05|01:17:23.406] Looking for peers                        peercount=0 tried=31 static=0
INFO [09-05|01:17:33.437] Looking for peers                        peercount=0 tried=37 static=0
INFO [09-05|01:17:43.699] Looking for peers                        peercount=0 tried=28 static=0
WARN [09-05|01:17:48.230] Snapshot extension registration failed   peer=0f407da6 err="peer connected on snap without compatible eth support"
INFO [09-05|01:17:52.738] Block synchronisation started
INFO [09-05|01:17:52.738] Mining aborted due to sync
INFO [09-05|01:17:53.704] Looking for peers                        peercount=1 tried=32 static=0
INFO [09-05|01:17:54.399] Downloader queue stats                   receiptTasks=0 blockTasks=7 itemSize=11.13KiB throttle=8192
INFO [09-05|01:17:54.834] Imported new chain segment               blocks=1 txs=308 mgas=26.959 elapsed=434.200ms   mgasps=62.088 number=15,474,955 hash=756076..39e117 age=3m39s dirty=3.15MiB
INFO [09-05|01:17:54.834] Unindexed transactions                   blocks=1 txs=12  tail=13,124,956 elapsed="245.775µs"
INFO [09-05|01:17:55.801] Imported new chain segment               blocks=9 txs=1103 mgas=92.732 elapsed=915.436ms   mgasps=101.298 number=15,474,964 hash=e3849a..f04478 age=1m38s dirty=13.42MiB
INFO [09-05|01:17:55.811] Unindexed transactions                   blocks=9 txs=1343 tail=13,124,965 elapsed=9.218ms
INFO [09-05|01:17:56.662] Imported new chain segment               blocks=7 txs=1324 mgas=92.699 elapsed=860.716ms   mgasps=107.700 number=15,474,971 hash=ef3765..e1ca33 dirty=23.42MiB
INFO [09-05|01:17:56.666] Unindexed transactions                   blocks=7 txs=951  tail=13,124,972 elapsed=3.608ms
INFO [09-05|01:17:56.690] Commit new sealing work                  number=15,474,972 sealhash=736c59..0502ad uncles=0 txs=0    gas=0 fees=0 elapsed="199.596µs"
INFO [09-05|01:17:56.726] Commit new sealing work                  number=15,474,972 sealhash=65e6e3..9cc7f0 uncles=0 txs=20   gas=2,990,569 fees=0.04907912871 elapsed=36.303ms
INFO [09-05|01:17:59.738] Commit new sealing work                  number=15,474,972 sealhash=6f2f5c..c52280 uncles=0 txs=44   gas=6,083,461 fees=0.05777107543 elapsed=47.205ms
INFO [09-05|01:18:02.746] Commit new sealing work                  number=15,474,972 sealhash=14d058..6216cf uncles=0 txs=67   gas=9,010,438 fees=0.09027859838 elapsed=55.658ms
INFO [09-05|01:18:04.025] Looking for peers                        peercount=1 tried=29 static=0
INFO [09-05|01:18:05.426] Imported new chain segment               blocks=1 txs=224  mgas=26.963 elapsed=237.715ms   mgasps=113.426 number=15,474,972 hash=4aafe0..49cc01 dirty=25.67MiB
INFO [09-05|01:18:05.428] Unindexed transactions                   blocks=1 txs=100  tail=13,124,973 elapsed=1.146ms
INFO [09-05|01:18:05.428] Commit new sealing work                  number=15,474,973 sealhash=634074..c91caf uncles=0 txs=0    gas=0         fees=0             elapsed=1.206ms
INFO [09-05|01:18:05.521] Commit new sealing work                  number=15,474,973 sealhash=28f995..8d9e88 uncles=0 txs=34   gas=3,002,191 fees=0.008426030175 elapsed=94.795ms
INFO [09-05|01:18:08.480] Commit new sealing work                  number=15,474,973 sealhash=8ae0b1..3a9714 uncles=0 txs=66   gas=6,227,
037 fees=0.01855275007  elapsed=52.995ms
INFO [09-05|01:18:11.507] Commit new sealing work                  number=15,474,973 sealhash=3cc67b..34891c uncles=0 txs=93   gas=8,189,
421 fees=0.0285669687   elapsed=79.411ms
INFO [09-05|01:18:14.077] Looking for peers                        peercount=1 tried=36 static=0
INFO [09-05|01:18:14.507] Commit new sealing work                  number=15,474,973 sealhash=6e9521..7def6c uncles=0 txs=111  gas=11,929
,796 fees=0.04115637268  elapsed=78.812ms
INFO [09-05|01:18:17.509] Commit new sealing work                  number=15,474,973 sealhash=e59cbc..e21047 uncles=0 txs=128  gas=13,861
,830 fees=0.04688229116  elapsed=80.124ms
INFO [09-05|01:18:17.861] Imported new chain segment               blocks=1 txs=106  mgas=11.369 elapsed=135.996ms   mgasps=83.599  number=15,474,973 hash=b466d0..cb4630 dirty=26.94MiB
INFO [09-05|01:18:17.862] Unindexed transactions                   blocks=1 txs=38   tail=13,124,974 elapsed="839.173µs"
INFO [09-05|01:18:17.862] Commit new sealing work                  number=15,474,974 sealhash=da5ea8..e5360e uncles=0 txs=0    gas=0          fees=0              elapsed="849.644µs"
INFO [09-05|01:18:17.920] Commit new sealing work                  number=15,474,974 sealhash=ddb48e..795268 uncles=0 txs=29   gas=2,649,867  fees=0.00649307745  elapsed=59.353ms
INFO [09-05|01:18:20.896] Commit new sealing work                  number=15,474,974 sealhash=36dfb7..e757ea uncles=0 txs=41   gas=3,786,371  fees=0.009715803846 elapsed=34.322ms
INFO [09-05|01:18:23.918] Commit new sealing work                  number=15,474,974 sealhash=8e7728..223a00 uncles=0 txs=65   gas=6,203,295  fees=0.01988153514  elapsed=55.652ms
INFO [09-05|01:18:24.115] Looking for peers                        peercount=1 tried=37 static=0
INFO [09-05|01:18:26.922] Commit new sealing work                  number=15,474,974 sealhash=b64da3..dd24ba uncles=0 txs=93   gas=8,614,542  fees=0.02883801832  elapsed=58.989ms
INFO [09-05|01:18:29.944] Commit new sealing work                  number=15,474,974 sealhash=4e6736..36f1cb uncles=0 txs=112  gas=11,207,177 fees=0.0330723942   elapsed=80.992ms
INFO [09-05|01:18:32.940] Commit new sealing work                  number=15,474,974 sealhash=81b96c..c67ed9 uncles=0 txs=135  gas=13,373,555 fees=0.04107510061  elapsed=76.069ms
INFO [09-05|01:18:34.174] Looking for peers                        peercount=2 tried=35 static=0
WARN [09-05|01:20:12.821] Snapshot extension registration failed   peer=5271cee3 err="peer connected on snap without compatible eth support"
INFO [09-05|01:20:15.080] Commit new sealing work                  number=15,474,979 sealhash=f9cbb2..a3680f uncles=0 txs=350  gas=29,996,606 fees=0.1494418246   elapsed=104.502ms
INFO [09-05|01:20:18.082] Commit new sealing work                  number=15,474,979 sealhash=9d8495..64fa8b uncles=0 txs=348  gas=29,999,831 fees=0.152158896    elapsed=106.187ms
WARN [09-05|01:22:16.053] Merge is configured, but no beacon client seen. Please ensure you have one available before the transition arrives! eta=1w4d8h
INFO [09-05|01:22:16.246] Commit new sealing work                  number=15,474,990 sealhash=7f2071..53dd18 uncles=0 txs=230  gas=18,650,731 fees=0.05917797882  elapsed=83.782ms
INFO [09-05|01:22:19.250] Commit new sealing work                  number=15,474,990 sealhash=e8fdf2..5d9ac8 uncles=0 txs=247  gas=20,627,291 fees=0.06801491727  elapsed=87.327ms`

**Comment by zhongdonglin** [comment]
```
INFO [09-05|01:16:40.138]
INFO [09-05|01:16:40.138] Merge configured:
INFO [09-05|01:16:40.138] - Hard-fork specification: https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet
-upgrades/paris.md
INFO [09-05|01:16:40.138] - Network known to be merged: false
INFO [09-05|01:16:40.138] - Total terminal difficulty: 58750000000000000000000
INFO [09-05|01:16:40.138] - Merge netsplit block:
INFO [09-05|01:16:40.138] ---------------------------------------------------------------------------------------------------------------
INFO [09-05|01:16:40.138]
INFO [09-05|01:16:40.599] Disk storage enabled for ethash caches dir=/geth/data/geth/ethash count=3
INFO [09-05|01:16:40.600] Disk storage enabled for ethash DAGs dir=/home/test/.ethash count=2
INFO [09-05|01:16:40.600] Initialising Ethereum protocol network=1 dbversion=8
INFO [09-05|01:16:40.854] Loaded most recent local header number=15,474,954 hash=3aaca3..5cef63 td=57,986,185,633,137,431,257,48
8 age=2m35s
INFO [09-05|01:16:40.854] Loaded most recent local full block number=15,474,954 hash=3aaca3..5cef63 td=57,986,185,633,137,431,257,48
8 age=2m35s
INFO [09-05|01:16:40.854] Loaded most recent local fast block number=15,474,954 hash=3aaca3..5cef63 td=57,986,185,633,137,431,257,488 age=2m35s
INFO [09-05|01:16:40.854] Loaded last fast-sync pivot marker number=15,455,348
INFO [09-05|01:16:40.973] Loaded local transaction journal transactions=0 dropped=0
INFO [09-05|01:16:40.973] Regenerated local transaction journal transactions=0 accounts=0
WARN [09-05|01:16:40.973] Switch sync mode from snap sync to full sync
WARN [09-05|01:16:40.973] Chain pre-merge, sync via PoW (ensure beacon client is ready)
INFO [09-05|01:16:40.973] Gasprice oracle is ignoring threshold set threshold=2
WARN [09-05|01:16:40.974] Engine API enabled protocol=eth
INFO [09-05|01:16:40.974] Starting peer-to-peer node instance=Geth/v1.10.23-stable-d901d853/linux-amd64/go1.18.5
INFO [09-05|01:16:41.026] New local node record seq=35 id=14432cdccc4e030c ip=127.0.0.1 udp=30303 tcp=30303
INFO [09-05|01:16:41.026] Started P2P networking self=enode://b0ccdf06d9a0e28a912815d7f4121b8e6c9785e08c096ff1afed74545f6b8048acf34249f91f4b7a2b3f36ff5e16077f757b6cb024a28360512598476aafa4e4@127.0.0.1:30303
INFO [09-05|01:16:41.027] IPC endpoint opened url=/geth/data/geth.ipc
INFO [09-05|01:16:41.027] Loaded JWT secret file path=/geth/data/geth/jwtsecret crc32=0x18e52e4c
INFO [09-05|01:16:41.028] HTTP server started endpoint=[::]:8545 auth=false prefix= cors=0.0.0.0 vhosts=localhost
INFO [09-05|01:16:41.028] WebSocket enabled url=ws://127.0.0.1:8551
INFO [09-05|01:16:41.028] HTTP server started endpoint=127.0.0.1:8551 auth=true prefix= cors=localhost vhosts=localhost
INFO [09-05|01:16:41.028] Transaction pool price threshold updated price=0
INFO [09-05|01:16:41.029] Updated mining threads threads=0
INFO [09-05|01:16:41.029] Transaction pool price threshold updated price=1,000,000,000
INFO [09-05|01:16:41.030] Commit new sealing work number=15,474,955 sealhash=f4c1a0..2075ec uncles=0 txs=0 gas=0 fees=0 elapsed="822.701µs"
INFO [09-05|01:16:41.030] Commit new sealing work number=15,474,955 sealhash=f4c1a0..2075ec uncles=0 txs=0 gas=0 fees=0 elapsed="994.987µs"
INFO [09-05|01:16:48.797] New local node record seq=36 id=14432cdccc4e030c ip=219.134.169.215 udp=25611 tcp=30303
INFO [09-05|01:16:53.029] Looking for peers peercount=0 tried=21 static=0
INFO [09-05|01:17:03.033] Looking for peers peercount=0 tried=21 static=0
INFO [09-05|01:17:13.078] Looking for peers peercount=0 tried=34 static=0
WARN [09-05|01:17:16.018] Merge is configured, but no beacon client seen. Please ensure you have one available before the transition arrives! eta=1w4d15h
INFO [09-05|01:17:23.406] Looking for peers peercount=0 tried=31 static=0
INFO [09-05|01:17:33.437] Looking for peers peercount=0 tried=37 static=0
INFO [09-05|01:17:43.699] Looking for peers peercount=0 tried=28 static=0
WARN [09-05|01:17:48.230] Snapshot extension registration failed peer=0f407da6 err="peer connected on snap without compatible eth support"
INFO [09-05|01:17:52.738] Block synchronisation started
INFO [09-05|01:17:52.738] Mining aborted due to sync
INFO [09-05|01:17:53.704] Looking for peers peercount=1 tried=32 static=0
INFO [09-05|01:17:54.399] Downloader queue stats receiptTasks=0 blockTasks=7 itemSize=11.13KiB throttle=8192
INFO [09-05|01:17:54.834] Imported new chain segment blocks=1 txs=308 mgas=26.959 elapsed=434.200ms mgasps=62.088 number=15,474,955 hash=756076..39e117 age=3m39s dirty=3.15MiB
INFO [09-05|01:17:54.834] Unindexed transactions blocks=1 txs=12 tail=13,124,956 elapsed="245.775µs"
INFO [09-05|01:17:55.801] Imported new chain segment blocks=9 txs=1103 mgas=92.732 elapsed=915.436ms mgasps=101.298 number=15,474,964 hash=e3849a..f04478 age=1m38s dirty=13.42MiB
INFO [09-05|01:17:55.811] Unindexed transactions blocks=9 txs=1343 tail=13,124,965 elapsed=9.218ms
INFO [09-05|01:17:56.662] Imported new chain segment blocks=7 txs=1324 mgas=92.699 elapsed=860.716ms mgasps=107.700 number=15,474,971 hash=ef3765..e1ca33 dirty=23.42MiB
INFO [09-05|01:17:56.666] Unindexed transactions blocks=7 txs=951 tail=13,124,972 elapsed=3.608ms
INFO [09-05|01:17:56.690] Commit new sealing work number=15,474,972 sealhash=736c59..0502ad uncles=0 txs=0 gas=0 fees=0 elapsed="199.596µs"
INFO [09-05|01:17:56.726] Commit new sealing work number=15,474,972 sealhash=65e6e3..9cc7f0 uncles=0 txs=20 gas=2,990,569 fees=0.04907912871 elapsed=36.303ms
INFO [09-05|01:17:59.738] Commit new sealing work number=15,474,972 sealhash=6f2f5c..c52280 uncles=0 txs=44 gas=6,083,461 fees=0.05777107543 elapsed=47.205ms
INFO [09-05|01:18:02.746] Commit new sealing work number=15,474,972 sealhash=14d058..6216cf uncles=0 txs=67 gas=9,010,438 fees=0.09027859838 elapsed=55.658ms
INFO [09-05|01:18:04.025] Looking for peers peercount=1 tried=29 static=0
INFO [09-05|01:18:05.426] Imported new chain segment blocks=1 txs=224 mgas=26.963 elapsed=237.715ms mgasps=113.426 number=15,474,972 hash=4aafe0..49cc01 dirty=25.67MiB
INFO [09-05|01:18:05.428] Unindexed transactions blocks=1 txs=100 tail=13,124,973 elapsed=1.146ms
INFO [09-05|01:18:05.428] Commit new sealing work number=15,474,973 sealhash=634074..c91caf uncles=0 txs=0 gas=0 fees=0 elapsed=1.206ms
INFO [09-05|01:18:05.521] Commit new sealing work number=15,474,973 sealhash=28f995..8d9e88 uncles=0 txs=34 gas=3,002,191 fees=0.008426030175 elapsed=94.795ms
INFO [09-05|01:18:08.480] Commit new sealing work number=15,474,973 sealhash=8ae0b1..3a9714 uncles=0 txs=66 gas=6,227,
037 fees=0.01855275007 elapsed=52.995ms
INFO [09-05|01:18:11.507] Commit new sealing work number=15,474,973 sealhash=3cc67b..34891c uncles=0 txs=93 gas=8,189,
421 fees=0.0285669687 elapsed=79.411ms
INFO [09-05|01:18:14.077] Looking for peers peercount=1 tried=36 static=0
INFO [09-05|01:18:14.507] Commit new sealing work number=15,474,973 sealhash=6e9521..7def6c uncles=0 txs=111 gas=11,929
,796 fees=0.04115637268 elapsed=78.812ms
INFO [09-05|01:18:17.509] Commit new sealing work number=15,474,973 sealhash=e59cbc..e21047 uncles=0 txs=128 gas=13,861
,830 fees=0.04688229116 elapsed=80.124ms
INFO [09-05|01:18:17.861] Imported new chain segment blocks=1 txs=106 mgas=11.369 elapsed=135.996ms mgasps=83.599 number=15,474,973 hash=b466d0..cb4630 dirty=26.94MiB
INFO [09-05|01:18:17.862] Unindexed transactions blocks=1 txs=38 tail=13,124,974 elapsed="839.173µs"
INFO [09-05|01:18:17.862] Commit new sealing work number=15,474,974 sealhash=da5ea8..e5360e uncles=0 txs=0 gas=0 fees=0 elapsed="849.644µs"
INFO [09-05|01:18:17.920] Commit new sealing work number=15,474,974 sealhash=ddb48e..795268 uncles=0 txs=29 gas=2,649,867 fees=0.00649307745 elapsed=59.353ms
INFO [09-05|01:18:20.896] Commit new sealing work number=15,474,974 sealhash=36dfb7..e757ea uncles=0 txs=41 gas=3,786,371 fees=0.009715803846 elapsed=34.322ms
INFO [09-05|01:18:23.918] Commit new sealing work number=15,474,974 sealhash=8e7728..223a00 uncles=0 txs=65 gas=6,203,295 fees=0.01988153514 elapsed=55.652ms
INFO [09-05|01:18:24.115] Looking for peers peercount=1 tried=37 static=0
INFO [09-05|01:18:26.922] Commit new sealing work number=15,474,974 sealhash=b64da3..dd24ba uncles=0 txs=93 gas=8,614,542 fees=0.02883801832 elapsed=58.989ms
INFO [09-05|01:18:29.944] Commit new sealing work number=15,474,974 sealhash=4e6736..36f1cb uncles=0 txs=112 gas=11,207,177 fees=0.0330723942 elapsed=80.992ms
INFO [09-05|01:18:32.940] Commit new sealing work number=15,474,974 sealhash=81b96c..c67ed9 uncles=0 txs=135 gas=13,373,555 fees=0.04107510061 elapsed=76.069ms
INFO [09-05|01:18:34.174] Looking for peers peercount=2 tried=35 static=0
WARN [09-05|01:20:12.821] Snapshot extension registration failed peer=5271cee3 err="peer connected on snap without compatible eth support"
INFO [09-05|01:20:15.080] Commit new sealing work number=15,474,979 sealhash=f9cbb2..a3680f uncles=0 txs=350 gas=29,996,606 fees=0.1494418246 elapsed=104.502ms
INFO [09-05|01:20:18.082] Commit new sealing work number=15,474,979 sealhash=9d8495..64fa8b uncles=0 txs=348 gas=29,999,831 fees=0.152158896 elapsed=106.187ms
WARN [09-05|01:22:16.053] Merge is configured, but no beacon client seen. Please ensure you have one available before the transition arrives! eta=1w4d8h
INFO [09-05|01:22:16.246] Commit new sealing work number=15,474,990 sealhash=7f2071..53dd18 uncles=0 txs=230 gas=18,650,731 fees=0.05917797882 elapsed=83.782ms
INFO [09-05|01:22:19.250] Commit new sealing work number=15,474,990 sealhash=e8fdf2..5d9ac8 uncles=0 txs=247 gas=20,627,291 fees=0.06801491727 elapsed=87.327ms
```

**Comment by zhongdonglin** [comment]
```
ethminer 0.18.0
Build: linux/release/gnu

 i 01:17:40 ethminer Configured pool 127.0.0.1:8545
 i 01:17:40 ethminer Selected pool 127.0.0.1:8545
 i 01:17:40 ethminer Established connection to 127.0.0.1:8545
 i 01:17:40 ethminer Spinning up miners...
cu 01:17:40 cuda-0   Using Pci Id : 01:00.0 NVIDIA GeForce RTX 3090 (Compute 8.6) Memory : 23.70 GB
cu 01:17:40 cuda-1   Using Pci Id : 25:00.0 NVIDIA GeForce RTX 3090 (Compute 8.6) Memory : 23.70 GB
cu 01:17:40 cuda-2   Using Pci Id : 41:00.0 NVIDIA GeForce RTX 3090 (Compute 8.6) Memory : 23.70 GB
cu 01:17:40 cuda-3   Using Pci Id : 61:00.0 NVIDIA GeForce RTX 3090 (Compute 8.6) Memory : 23.70 GB
cu 01:17:40 cuda-4   Using Pci Id : 81:00.0 NVIDIA GeForce RTX 3090 (Compute 8.6) Memory : 23.70 GB
cu 01:17:40 cuda-5   Using Pci Id : a1:00.0 NVIDIA GeForce RTX 3090 (Compute 8.6) Memory : 23.70 GB
cu 01:17:40 cuda-6   Using Pci Id : c1:00.0 NVIDIA GeForce RTX 3090 (Compute 8.6) Memory : 23.70 GB
 i 01:17:40 ethminer  >> {"id":1,"jsonrpc":"2.0","method":"eth_getWork","params":[]}
cu 01:17:40 cuda-7   Using Pci Id : e1:00.0 NVIDIA GeForce RTX 3090 (Compute 8.6) Memory : 23.70 GB
 i 01:17:40 ethminer  << {"jsonrpc":"2.0","id":1,"result":["0xf4c1a093672f8d889505ebd30c638461f566833477b0d350438f53af5c2075ec","0xcaabe82951932ddcefbe9ea12a64318065938de739e157d7dfef97b95ae68abd","0x00000000000005d34bfd6b0e948fb39c8bb861eb30817f20ff23afaf8e69ee1a","0xec210b"]}
SIGSEGV encountered ...
stack trace:
backtrace() returned 18 addresses
./ethminer() [0x422af9]
/lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7fe26026d090]
./ethminer() [0x4b06b3]
./ethminer() [0x4b081f]
./ethminer() [0x47979a]
./ethminer() [0x479ca5]
./ethminer() [0x4a717b]
./ethminer() [0x4aaa41]
./ethminer() [0x4a9e54]
./ethminer() [0x4ab77d]
./ethminer() [0x4ab9b6]
./ethminer() [0x482f6e]
./ethminer() [0x42a2d0]
./ethminer() [0x773aaf]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7fe26058e609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fe260349133]
```

**Comment by zhongdonglin** [comment]
It seems that there is a sealing task, but when I use the nvidia-smi command to check the status of the graphics card, there is no graphics card in use

**Comment by zhongdonglin** [comment]
```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**Comment by rjl493456442** [comment]
` i 01:17:40 ethminer  << {"jsonrpc":"2.0","id":1,"result":["0xf4c1a093672f8d889505ebd30c638461f566833477b0d350438f53af5c2075ec","0xcaabe82951932ddcefbe9ea12a64318065938de739e157d7dfef97b95ae68abd","0x00000000000005d34bfd6b0e948fb39c8bb861eb30817f20ff23afaf8e69ee1a","0xec210b"]}
`
The sealing task is actually returned. Perhaps something wrong in ethminer?

**Comment by zhongdonglin** [comment]
I found out today that it seems to be a CUDA version problem, I am recompiling the 86 version because my CUDA is the latest 11.7
