### ISSUE TITLE
difference between TransactionsPacket and PooledTransactionsPacket

### ISSUE THREAD

**Issue by wangtsiao** [ethereum/go-ethereum#25673]
Hello, I am trying to understand the implementation in [eth/handler_eth.go](https://github.com/ethereum/go-ethereum/blob/9244d5cd61f3ea5a7645fdf2a1a96d53421e412f/eth/handler_eth.go), and I can not figure out what is the difference between `TransactionsPacket` and `PooledTransactionsPacket`? 

I found the only difference is at the third parameter of `h.txFetcher.Enqueue`.

 Can anyone give an explaination about this ? Appreciate.

**Comment by fjl** [comment]
`PooledTransactions` is the response to the `GetPooledTransactions` request. In comparison, the `Transactions` message is a push-style delivery of transactions.

You can find more information about this in the protocol spec: https://github.com/ethereum/devp2p/blob/master/caps/eth.md#transaction-exchange
