### ISSUE TITLE
eth_feeHistory crashes with "finalized" block specifier

### ISSUE THREAD

**Issue by jdevcs** [ethereum/go-ethereum#25671]
Geth method handler crashed on `getFeeHistory` with `finalized` tag:

`curl --location --request POST 'http://node.addr' \
--header 'Content-Type: application/json' \
--data-raw '{
    "method": "eth_feeHistory",
    "params": [
        "0x4",
        "finalized",
        [
            25,
            50,
            75
        ]
    ],
    "id": 1,
    "jsonrpc": "2.0"
}'`

returning
`{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "method handler crashed"
    }
}`

Geth version: `Geth/v1.10.21-omnibus-6399bbf3/linux-amd64/go1.18.4`

**Comment by jdevcs** [comment]
Tested on Goerli NW

**Comment by holiman** [comment]
Git bisect shows that was fixed as of a0b88ce869d6be243c6b1900d69b9401f2d2c092 , with #25442
