### ISSUE TITLE
GraphQL wrong Event Logs on querying Transactions

### ISSUE THREAD

**Issue by aters** [ethereum/go-ethereum#25699]
#### System information

Geth version: 1.10.23
OS & Version: Linux
Commit hash : -

Querying block->transactions->logs return event logs for whole block but should return for each transaction. It could be critical for someone who fetching transactions using graphQL and could lead to double-spends. On 1.10.21 node version it is working as expected.

#### Expected behaviour
When querying for the transactions in block using graphQL we should receive event logs only for the corresponding transactions. 

#### Actual behaviour
We are receiving event logs for ALL transactions in block for EACH transaction.

#### Steps to reproduce the behaviour
Make a graphQL query to the node: 
`{ 
    block(number:15484104) 
    { 
        transactions 
        { 
            hash 
            logs { account { address } topics data } 
        }
    }
}`

#### Backtrace

````
-
````

**Comment by fjl** [comment]
This issue is fixed in #25612, which is already merged to the master branch.
