### ISSUE TITLE
stop sync

### ISSUE THREAD

**Issue by brunokelo** [ethereum/go-ethereum#25697]
Hello, my node was syncing normally but since yesterday it has stopped and has the following message,

Error: invalid merkle root (remote: 69578135bc79d97e8298fb5ebe371bd652b348d2b022563b97bfe2af23c8cbfd location: f8894d979bc8cb4887bbd37e78076f56edb5a61c760cdb0bf0f0e)
###########################

Geth
Version: 1.10.22-stable
Git Commit: 2de49b04e56cf07f011d6d91f9d5c08847aabe8e
Architecture: amd64
Go Version: go1.18.5
Operating System: linux
GOPATH=
GOROOT=go

does anyone know what it could be?

thanks.

**Comment by ligi** [comment]
can you please provide more logs? Did you have a unclean shutdown?

**Comment by karalabe** [comment]
1.10.22 contained a bad version of leveldb. We've rolled it back in 1.10.23. You should update your geth node and the simplest is to resync, keeping the `ancients` folder intact (so you don't re-download that part). Sorry about this.
