### ISSUE TITLE
Failed to delete bloom bits              err="leveldb: closed"

### ISSUE THREAD

**Issue by coderbradlee** [ethereum/go-ethereum#25716]
hi：

when I start two geth in the same vm,there's error :
Failed to delete bloom bits              err="leveldb: closed"

I already split the datadir and dagdir to diffrent dir,any idea why this happens?

**Comment by coderbradlee** [comment]
http and ws port is diffrent of course

**Comment by rjl493456442** [comment]
Might be some data race when shutdown Geth. Will try to investigate it.

**Comment by coderbradlee** [comment]
> Might be some data race when shutdown Geth. Will try to investigate it.

Good point,I think maybe some hidden db path cannot config it

**Comment by holiman** [comment]
This seems abandoned. If this still is relevant, please reopen and supply the exact commands used to trigger the error.
