### ISSUE TITLE
debug_dumpBlock for specific addresses

### ISSUE THREAD

**Issue by kash1988** [ethereum/go-ethereum#25712]
System Information

Geth version: Geth/v1.10.23-stable-d901d853/linux-amd64/go1.18.5
OS & Version: Debian 11.3 Bullseye

Questions:

1. The `debug_dumpBlock` method is supposed to dump all addresses. Is there any way to get the same information for specific addresses instead? Besides that, it always returns 256 addresses for some reason. Does this method support paging?

2. The `debug_accountRange` method seems to support paging. What does it expect exactly as the "start" parameter? What kind of value is returned as "next" in the response? How is the ordering of addresses defined?

**Comment by lightclient** [comment]
* `debug_dumpBlock` does not support paging. It walks the trie at the block height and spits out every account.
* Does `debug_accountRange(N, addr, 1)` not provide the all the values you need?
* There is a hard-coded limit of 256 results for `debug_dumpBlock`. 
* For `debug_accountRange`, the start parameter is the first address in the range. If the address doesn't exist, it will traverse the trie for the next closest address. The third parameter is `maxResults` which declares how many results to return (also capped at 256). You can use those two in concert to provide pagination.
* The ordering of addresses is lexicographical.
