### ISSUE TITLE
DoS: geth gossiping "bad" (mainnet) nodes throughout a private network

### ISSUE THREAD

**Issue by michaelansel** [ethereum/go-ethereum#2571]
#### System information

Geth version: 1.4.3 and 1.4.4
OS & Version: Linux (Amazon AMI), OSX (El Cap)

EC2

```
$ geth version
Geth
Version: 1.4.3-stable-dd083aa3
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=
GOROOT=/opt/google/go
```

OSX

```
$ geth version
Geth
Version: 1.4.4-stable-fc0638f9
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.6.2/libexec
```
#### Expected behaviour

I launch a private network; discovery works between nodes on the private network; any interaction with a different network (different genesis block) or any otherwise-bad nodes is not relayed.

All nodes start up like this (public node bootstraps against itself to force not using compiled-in bootnodes):

``` bash
BOOTNODES=$(paste -sd',' - <<EOF
enode://901fb03fa5680615381f155f6c9c3dd867108d507a3384eeaf50b5e73179bc7f9025d966df188606b94cb3b5f6451df830b38b683005963af26d35941cc6a0d6@PUBLIC_IP:1337
enode://901fb03fa5680615381f155f6c9c3dd867108d507a3384eeaf50b5e73179bc7f9025d966df188606b94cb3b5f6451df830b38b683005963af26d35941cc6a0d6@PUBLIC_IP:1337
EOF
)

# Clear out node database
rm -rf "$HOME/darknet/data/nodes"

exec geth --datadir=$HOME/darknet/data --networkid 1337 --port 1337 --bootnodes="${BOOTNODES}" --verbosity 5
```
#### Actual behaviour

My single internet accessible node (EC2) accidentally connected to the public network (with my genesis block) at some point in the past. Now, every time I start up the public node, it is blasted with connections from the main network. My node records those nodes and gossips them on to my other private nodes. As a result, all nodes are constantly trying to connect to the public internet, which is both wasteful and sometimes a denial of service for those nodes (they get stuck working through all public nodes looking for my relatively small number of private nodes).
#### Steps to reproduce the behaviour

Let me know if you want to repro against my private network (I'd rather not publish all the details, but happy to share with the developers).
1. Set up a private network node (custom genesis block) with a public IP address and an internet-accessible Eth port
2. Launch geth WITHOUT bootnodes set (uses the compiled-in list) and then stop it
3. Clear out all memory of mainnet nodes: `rm -rf data/nodes`
4. Launch geth WITH bootnodes set (point to anything that isn't the internet; I pointed back at self)
5. Launch a second instance of geth WITH bootnodes set to the public IP in step 1/step 4 (this new node doesn't need to be internet accessible)
6. Watch as the node from step 5 picks up invalid nodes from the public node (step 1) and tries to connect to them. If you restart the node from step 5, notice that it spends an inordinate amount of time connecting to bad nodes and rarely makes it to the singular "good" node.
#### Backtrace

(no backtrace; I can collect logs if that would be helpful)

**Comment by michaelansel** [comment]
Did some more digging, and I think this is more an issue of geth falling back to the compiled-in seeds even when bootnodes is specified.

Best I can tell, my public node is getting "overloaded" (hitting the geth connection cap) by the mainnet and ignoring the discovery connection from my non-public node. After the non-public node sees all seeds fail ("no seeds found"), it appears to just give up and start dialing all the compiled-in seeds. Then, even though the non-public node was never able to successfully handshake with mainnet (different genesis block), it happily records all seen nodes and uses them as seeds on next restart, effectively locking the new non-public node out of the private network.

**My conclusion**: geth tries too damn hard to connect to the mainnet and won't accept that I want to run a private network with a separate peer discovery table.

I'm going to leave this open with the hopes that a dev can at least shed a little light on what is going on and classify it as "expected" or "bug". Any suggestions on "doing a full private network the right way" would be welcome.

**Comment by fjl** [comment]
Your conclusion is pretty much correct. The reason for this behaviour is that the discovery protocol doesn't distinguish between networks. We are working on a protocol change to make this work.

**Comment by michaelansel** [comment]
Thanks for the confirmation! Should I leave this open to connect with that work, or would you rather have it closed?

**Comment by michaelansel** [comment]
@fjl did this get fixed somewhere else, or is it still broken? Haven't had a chance to play with it in a while. I'll poke around and test it if I get some free time in the next couple weeks.

**Comment by cupaco** [comment]
Is there any Update on this? i am having exactly the same issue and i dont want to use firewall rules to prevent from scanning around.

**Comment by fjl** [comment]
We added a flag to white-list IP ranges for discovery to deal with this issue. Example:
If your private network nodes are on 192.168.0.1, 192.168.0.2, 192.168.0.3 you can use `geth --netrestrict 192.168.0.0/24` to restrict communication to that subnetwork.
