### ISSUE TITLE
The plans of the data storage 

### ISSUE THREAD

**Issue by lurais** [ethereum/go-ethereum#25717]
I'm curious about what you will do next in terms of data storage, because the current amount of data is relatively large, and the storage method of data will also affect the reading and writing performance. Then, where can I see the plans for these changes in time？

**Comment by s1na** [comment]
This is the next major change to the storage scheme. This will make it so the database doesn't grow ever-larger.

https://www.reddit.com/r/ethereum/comments/wpqmo1/comment/iki98rh
