### ISSUE TITLE
geth is returning wrong values in web3.py

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [ethereum/go-ethereum#25732]
![image](https://user-images.githubusercontent.com/30082863/189483709-1f7831fe-6667-415d-8b48-9afc60b4d789.png)

As can be seen in the image, every web3.py call i am making to geth returns nothing but 0 

even though the answer is not 0

i am running geth with lighthouse beacon client, please help me out here

**Comment by wanowners** [comment]
Read properly  that documents beaconscan... From that etherscan..

**Comment by SyedMuhamadYasir** [comment]
> Read properly that documents beaconscan... From that etherscan..


what

**Comment by lightclient** [comment]
@SyedMuhamadYasir can you verify your client has completed syncing? `eth_blockNumber` returns 0 until the client is fully synced.
