### ISSUE TITLE
What should we do to support PoS?

### ISSUE THREAD

**Issue by yasyzb** [ethereum/go-ethereum#25750]
Is v1.10.23 support pos when TTD arrived?
I have run a geth client, I want to know what should I do to support PoS?

**Comment by MariusVanDerWijden** [comment]
Yes v1.10.23 has PoS support build in. You will need to run a beaconchain client (prysm, lighthouse, teku,...) as well though. There's a good checklist here, explaining how to run a node after the merge on PoS: https://launchpad.ethereum.org/en/merge-readiness/

**Comment by yasyzb** [comment]
If I just use node to submit transaction, query transaction. Is Geth enough?

**Comment by yasyzb** [comment]
@MariusVanDerWijden

**Comment by MariusVanDerWijden** [comment]
No, you need both nodes to follow the chain. It's very unfortunate and might be changed in the future, but we weren't able to implement it in time for the merge
