### ISSUE TITLE
About The Merge

### ISSUE THREAD

**Issue by Ericalvin** [ethereum/go-ethereum#25756]
I have run a Geth client, and already update to v1.10.23, is this enough to merge ? or must run a beacon chain client, ex: prysm...?

**Comment by rjl493456442** [comment]
Yes v1.10.23 has PoS support build in. You will need to run a beaconchain client (prysm, lighthouse, teku,...) as well though. There's a good checklist here, explaining how to run a node after the merge on PoS: https://launchpad.ethereum.org/en/merge-readiness/

**Comment by Ericalvin** [comment]
@rjl493456442  Thank you.
