### ISSUE TITLE
Geth 1.10.23 fresh sync is broken for Post-Merge networks with error: Beacon client online, but never received consensus updates.

### ISSUE THREAD

**Issue by begetan** [ethereum/go-ethereum#25753]
#### System information

Geth version:
```
Version: 1.10.23-stable
Git Commit: d901d85377c2c2f05f09f423c7d739c0feecd90a
Git Commit Date: 20220824
Architecture: arm64
Go Version: go1.18.5
Operating System: linux
```
Prysm beacon-chain version:
```
beacon-chain version Prysm/v3.1.1/653ea3b030c3bb99aa3f3d95a8de9f4d6e147930. Built at: 2022-09-09 17:24:18+00:00
```

#### Expected behaviour
We expect system should start syncing from scratch both for Geth and Prysm beacon clients

#### Actual behaviour
Prysm is syncing: [log1](https://gist.github.com/begetan/ea935fe9c26a4a269d7458b0cfec37eb)
Geth is not able to sync: [log2](https://gist.github.com/begetan/10733dbd611fb85da61030677d2f315e)

Geth not able to sync with this error message:
`Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!` 

#### Steps to reproduce the behaviour

1. Configure geth with systemd unit
2. Configure prysm with systemd unit
3. Create jwt token
3. Start services:
```
systemctl enable geth.service --now
systemctl enable prysm.service --now

```
This issue is not fully repeatable. It may depend on the startup timings.
It occurs at  90% tries of deployment of Goerli and 50% of Ropsten deploynment. Mainnet is not affected at the moment, because this check is in Post-Merge code.

Another important thing, get in this status provides incorrect sync state:

```
curl -s -X POST -H "Content-Type:application/json" --data '{"jsonrpc":"2.0","method":"eth_syncing","id":1}' localhost:8545
{"jsonrpc":"2.0","id":1,"result":false}

du -shc /data/*
2.2M    /data/geth
4.0K    /data/jwtsecret
325M    /data/prysm
327M    total
```
You can see that geth data directory is empty at the moment of syncing=false report.  We didn't success to recover geth from dead-loop by restarting geth of prysm services. The only way to recover this situation is to replace geth with binary version 1.10.21

**Comment by fjl** [comment]
I have spoken to the Prysm developers about this, and they say: in your logs, Prysm is still syncing from genesis and it will take time to finish that. Once Prysm has finished syncing, it will deliver the ForkchoiceUpdated message to geth, and geth will start syncing then. It is recommended to use a checkpoint to speed up the beacon chain sync.

They are thinking about adding something in Prysm so that it will deliver the FcU request earlier in this scenario.

**Comment by vvvesss** [comment]
Lot of hours later, still the same..
Do you have any progress?

**Comment by holiman** [comment]
> Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!

So, that's geth telling you: "Hey, we see that the beacon client exists, that's great and all, but it is not telling us about the latest blocks, which is his/her job. Could you please check on that process and see that it's doing alright?"

So, you need to investigate the beacon node, and, if needed, reach out to those developers for support.

**Comment by donkarziavelli** [comment]
> > Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!
> 
> So, that's geth telling you: "Hey, we see that the beacon client exists, that's great and all, but it is not telling us about the latest blocks, which is his/her job. Could you please check on that process and see that it's doing alright?"
> 
> So, you need to investigate the beacon node, and, if needed, reach out to those developers for support.

so just to understand it correctly, post merge my CL has to be synced fully and than EL starts syncing?

**Comment by holiman** [comment]
>  post merge my CL has to be synced fully and than EL starts syncing?

That is correct.

**Comment by brentVCG** [comment]
@holiman - really appreciate all the knowledge you share. How long does it take to sync my CL? Is there a demarc or command I can run via Prysm to know this is completed?

**Comment by juroberttyb** [comment]
> @holiman - really appreciate all the knowledge you share. How long does it take to sync my CL? Is there a demarc or command I can run via Prysm to know this is completed?

For prysm, Synced new block and gradually growing epoch number may be the sign of syncing with the current chain.

**Comment by muse-terry** [comment]
@brentVCG It depends on the hardware, but it seems like it takes about a week just for beacon client synchronization

**Comment by yoontaeung** [comment]
@brentVCG It depends on the hardware, but it seems like it takes about a week just for beacon client synchronization.

**Comment by bitcoinbrisbane** [comment]
> @brentVCG It depends on the hardware, but it seems like it takes about a week just for beacon client synchronization.

Thanks for that.  I set one up yesterday, ill come back in a week :)

**Comment by sambarbarin** [comment]
> > @brentVCG It depends on the hardware, but it seems like it takes about a week just for beacon client synchronization.
> 
> Thanks for that. I set one up yesterday, ill come back in a week :)

Hi @bitcoinbrisbane, does it work after a week ? I have the same problem as you and i wish to to know if this is just a sync problem :)

**Comment by donkarziavelli** [comment]
> > > @brentVCG It depends on the hardware, but it seems like it takes about a week just for beacon client synchronization.
> > 
> > 
> > Thanks for that. I set one up yesterday, ill come back in a week :)
> 
> Hi @bitcoinbrisbane, does it work after a week ? I have the same problem as you and i wish to to know if this is just a sync problem :)

Which version of geth are you running? For me all the problems were gone when using the developer version (and a good SSD, first one had low IOPS). I think its 1.11.0? Synced in about four days using a Raspberrypi 4B.

**Comment by sambarbarin** [comment]
> 



> 



> donkarziavelli

I am running this version on a linux os. 

Geth
Version: 1.11.0-unstable
Git Commit: 55a92fa0a4570ac2bd1774c7f7d8c52311863e32
Architecture: amd64
Go Version: go1.19.2
Operating System: linux

I will wait a few days and see how it is going on with this

**Comment by yoontaeung** [comment]
It takes too much time, I did it with fast sync. It will only take about 10 minutes.

**Comment by bitcoinbrisbane** [comment]
> > > @brentVCG It depends on the hardware, but it seems like it takes about a week just for beacon client synchronization.
> > 
> > 
> > Thanks for that. I set one up yesterday, ill come back in a week :)
> 
> Hi @bitcoinbrisbane, does it work after a week ? I have the same problem as you and i wish to to know if this is just a sync problem :)

Been a few months now... Re visiting the thread.

**Comment by bitcoinbrisbane** [comment]
Still the same on a new VM.

```bash
-goerli --http --http.api eth,net,engine,admin --authrpc.jwtsecret /secrets/jwtsecret --datadir=/mnt/volume_syd1_01/geth_db --syncmode full
```

Or 

```bash
-goerli --http --http.api eth,net,engine,admin --authrpc.jwtsecret /secrets/jwtsecret --datadir=/mnt/volume_syd1_01/geth_db
```

![image](https://user-images.githubusercontent.com/8411406/221473825-1eca2282-d76a-49b9-927c-3fccdc3fa19c.png)

**Comment by bitcoinbrisbane** [comment]
instance=Geth/v1.11.2

**Comment by ereztdev** [comment]
I'm having the same issue

> It took too much time, I did it with fast sync. It will only take about 10 minutes.

Can you detail how you preformed fast sync?
I'm using Geth and lighthouse
