### ISSUE TITLE
Safe Head & Finalized Blocks Problem When Post-Merge

### ISSUE THREAD

**Issue by xux1217** [ethereum/go-ethereum#25766]
#### System information

Geth version: v1.10.23
prysm version: v3.1.1
OS & Version: linux
Commit hash : used official docker image(ethereum/client-go:v1.10.23 and gcr.io/prysmaticlabs/prysm/beacon-chain:v3.1.1)

#### Expected behaviour
the `safe head` should only a few seconds behind the latest block.
refer here: https://blog.ethereum.org/2021/11/29/how-the-merge-impacts-app-layer
![image](https://user-images.githubusercontent.com/9280285/190365576-b0ddbee9-9e64-409a-bb7b-854eeffe5c8e.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/9280285/190365909-132b330e-d35e-48db-8576-8f5aeea97d45.png)

I don't know why the result is different with the blob, and should it means that the confirmed block number should >= 80 ?

#### Steps to reproduce the behaviour
Just use these below commands.
```
eth.getBlock("safe").number - eth.getBlock("finalized").number

eth.getBlock("latest").number - eth.getBlock("safe").number
```

**Comment by MariusVanDerWijden** [comment]
This is not a bug in geth, we are just using the information that the CL client gives us. You should open the issue with the CL client that you're using
