### ISSUE TITLE
Already shutting down, interrupt more to panic

### ISSUE THREAD

**Issue by MareG76** [ethereum/go-ethereum#25775]
Geth version: 1.10.25
OS & Version: Windows 10

#### Expected behaviour
Almost every version of get lately gives me this problem, after hitting ctrl+c it just won't stop, some times I wait half an hour and nothing

#### Actual behaviour
It gives me "Already shutting down, interrupt more to panic" and when i interrupt it more I get this:
[https://pastebin.com/HpWBRxMp](url)

#### Steps to reproduce the behaviour
Try to stop geth on Windows 10 with ctrl+c

**Comment by holiman** [comment]
I think this should fix it 
```diff
diff --git a/eth/protocols/eth/dispatcher.go b/eth/protocols/eth/dispatcher.go
index 65a935d555..1486a70022 100644
--- a/eth/protocols/eth/dispatcher.go
+++ b/eth/protocols/eth/dispatcher.go
@@ -174,6 +174,8 @@ func (p *Peer) dispatchResponse(res *Response, metadata func() interface{}) erro
 				return <-res.Done // Response delivered, return any errors
 			case <-res.Req.cancel:
 				return nil // Request cancelled, silently discard response
+			case <-p.term:
+				return errDisconnected
 			}
 		}
 
```
