### ISSUE TITLE
About eth2.0 

### ISSUE THREAD

**Issue by kledgold** [ethereum/go-ethereum#25772]
Hello, the current geth version can only be synchronized to a height of 15537418. Is it because of the merger of ETH2.0? How can I use geth to synchronize eth2.0 data?

**Comment by osizadmin** [comment]
We also face same issue
Block number not update after 15537417
we have faced this issue in our lot of client server. 
Kindly help us.

**Comment by Sreeram1993** [comment]
> Hello, the current geth version can only be synchronized to a height of 15537418. Is it because of the merger of ETH2.0? How can I use geth to synchronize eth2.0 data?

Is your beacon chain sync complete ?

**Comment by karalabe** [comment]
You need to have a consensus (beacon) client running beside Geth and have it synced (you can use a checkpoint sync to do it within a few minutes). Post-merge, the chain is directed by the consensus client, so Get can't sync past the terminal pow block.
