### ISSUE TITLE
Ethereum mainnet syncing stuck at blocknumber 15537415 & showing syncing false

### ISSUE THREAD

**Issue by kartikswarnkar** [ethereum/go-ethereum#25771]
Ethereum blocknumber did not match with etherscan.io,
Syncing stuck at this block 15537415 and also showing syncing false.

#### Geth

Welcome to the Geth JavaScript console!
modules: admin:1.0 debug:1.0 eth:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

To exit, press ctrl-d or type exit
> eth.blockNumber
15537415
> eth.syncing
false
>

#### Version
I am using geth version  v1.10.23

Version details :
Geth/v1.10.23-stable-d901d853/linux-amd64/go1.18.5

#### startGeth.sh
nohup ./geth-final/geth   --syncmode light  --cache=1024  --http    --http.port "8545"   --datadir "/Mainnet/"   --authrpc.addr localhost   --authrpc.port "8551"   --authrpc.vhosts localhost  --authrpc.jwtsecret /tmp/jwtsecret  --http.api "db,eth,net,web3,debug,miner,admin,personal,txpool"  --allow-insecure-unlock  --networkid 1 &

Is there any configuration I need to change to keep the sync going?

**Comment by 1scrooge** [comment]
My node stuck too. But at 15537393 block
Geth version is 1.10.24
Prysm version os 3.1.1

**Comment by Sreeram1993** [comment]
Check the beacon node status and see if its completely synced. Once it's complete geth syncing will restart. This is what I have identified form my node.

**Comment by osizadmin** [comment]
We also face  same issue
Block number not update after 15537417
we have faced this issue in our lot of client 
Kindly help us

**Comment by sealbox** [comment]
What you have to do is to run geth 1.10.24 and prysm 3.1.1 and connect them together. However, I am still unable to do it right. Maybe you can find some useful information within my issue https://github.com/ethereum/go-ethereum/issues/25771

**Comment by aghamir** [comment]
Use lighthouse with checkpoint-url. This is the fastest way to sync your node.

**Comment by karalabe** [comment]
Please make sure you have a beacon client, that it's updated and that it's synced. If you have all these and it still doesn't work, please provide some logs.
