### ISSUE TITLE
Running geth with beacon chain

### ISSUE THREAD

**Issue by sealbox** [ethereum/go-ethereum#25778]
Hello,
I would like to get a clarification what is the relation between geth and so-called beacon node after merge? If I understood it correctly, geth is exchanging information with beacon chain in now and it requires beacon chain for syncing?

So I picked the prysm beacon chain implementation as it looked the easiest to run, but I cannot make it work.

My folder structure is as follows:

```
/home/eth
    /.ethereum # data
    /node # geth (1.10.24)
    /node_beacon # prysm (3.1.1)
```

I whitelisted all TCP, UDP ports required for running both and checked with  MX Toolbox that ports are discoverable (RPC and P2P for both geth and prysm).

I am running geth with following options:

```
/home/eth/node/build/bin/geth --cache=4096 --http --http.api eth,web3,net,engine,debug,personal --http.addr 0.0.0.0 --http.port 12001 --port 30303 --datadir=/home/eth/.ethereum --allow-insecure-unlock --rpc.allow-unprotected-txs --authrpc.addr 0.0.0.0 --authrpc.port 8551 --authrpc.vhosts 0.0.0.0 --authrpc.jwtsecret /home/eth/node_beacon/jwt.hex
```

I am running prysm with following options:

```
/home/eth/node_beacon/prysm.sh beacon-chain --datadir=/home/eth/.ethereum --http-web3provider=http://127.0.0.1:12001 --rpc-host=0.0.0.0 --monitoring-host=0.0.0.0 --execution-endpoint=http://127.0.0.1:8551 --accept-terms-of-use --jwt-secret=/home/eth/node_beacon/jwt.hex
```

And both services seem to start up and run fine, I do not get any errors. However, after they are setup it seems the geth waits for prysm while prysm waits for geth:

Those are the logs:

Geth:
```
WARN [09-15|22:52:53.139] Local chain is post-merge, waiting for beacon client sync switch-over...
INFO [09-15|22:50:49.891] Legacy sync reached merge threshold      number=15,537,419 hash=78c1c2..58cd79 td=58,750,256,312,486,924,353,244 ttd=58,750,000,000,000,000,000,000
```

Prysm:
```
time="2022-09-15 22:51:18" level=warning msg="Execution client is not syncing" prefix=powchain
time="2022-09-15 22:51:22" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
```

From the logs it seems to me that geth waits for prysm to start doing something, while prysm complaining the geth is not syncing anything? What am I doing wrong? It's really unclear to me how to setup both properly.

**Comment by rjl493456442** [comment]
Are you running the script for prysm? `/home/eth/node_beacon/prysm.sh`

From the log Geth is waiting signal from the beacon node while beacon node is not. Maybe prysm is the better place to ask the reason?

Personally I use lighthouse with this command

```
lighthouse beacon_node --execution-endpoint http://127.0.0.1:8551 --execution-jwt XXX --checkpoint-sync-url XXX --datadir ./beacon
```

You can specify a checkpoint sync URL for fast bootstrapping, otherwise can take some time to initial sync the beacon node.

**Comment by web3zhangxianxing** [comment]
Any solution? Came to the same problem that geth stuck at height of 15537419 before I started the beacon node. However, I thought geth might recover after beacon node finishes syncing, Prysm:
`time="2022-09-16 14:14:48" level=warning msg="Execution client is not syncing" prefix=powchain`
`time="2022-09-16 14:14:51" level=info msg="Processing block batch of size 64 starting from  0xa1ad0523... 1629616/4707072 - estimated time remaining 53h25m41s" blocksPerSecond=16.0 peers=39 prefix=initial-sync`

**Comment by GeassV** [comment]
Any solution? Came to the same problem that geth stuck at height of 15537419 before I started the beacon node. However, I thought geth might recover after the beacon node finishes syncing, Prysm:
`time="2022-09-16 14:14:48" level=warning msg="Execution client is not syncing" prefix=powchain`
`time="2022-09-16 14:14:51" level=info msg="Processing block batch of size 64 starting from  0xa1ad0523... 1629616/4707072 - estimated time remaining 53h25m41s" blocksPerSecond=16.0 peers=39 prefix=initial-sync`

**Comment by Sreeram1993** [comment]
@GeassV  As the message says your beacon node is not in sync, only once its in sync will the geth start resending. Had the same issue. You have to wait for the beacon node to sync.

**Comment by karalabe** [comment]
You can also use a checkpoint sync from e.g. Infura or another trusted beacon client to sync it within a few minutes.

**Comment by sealbox** [comment]
@karalabe don't you close my issue without answering the question. The geth is no longer standalone node so it needs the beacon to work properly. I do not see any documentation how to do properly on geth side and following prysm documentation I ma left around haning for not working sync. Answer the problem that was asked properly. You are just going closing all similar issues and yet, ppl have the same problem as me not able to find the proper answer. If you don't know just avoid this topic. Thanks!

**Comment by GeassV** [comment]
> You can also use a checkpoint sync from e.g. Infura or another trusted beacon client to sync it within a few minutes.

Thank you for the reminder. I rechecked the setting of checkpoint sync node and then used the official recommended one, which saved me dozens of hours. FYI: https://eth-clients.github.io/checkpoint-sync-endpoints/#mainnet

**Comment by woodydeck** [comment]
This issue should be reopened. There is zero documentation on how to do this. What a disgrace the merge is in terms of decentralization. It's not PoS bringing about less decentralization, it's the impossibility to do simple things like run a full node.

Shame on whomever doesn't understand this plight. I'm spending a day on this and nothing has worked, and there are no answers to be found. Just five beacon clients that all are poorly documented.

**Comment by karalabe** [comment]
https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/

**Comment by tpkeeper** [comment]
I also want to run geth with beacon node in local that is private network, but I can't find the doc

**Comment by lukelu0520** [comment]
same issue +1 Hope to make it simple in the near future as:
`geth --consensus <client name, s.t. prysm, lodestar, or a dummy one>`
