### ISSUE TITLE
 Running geth with beacon chain 

### ISSUE THREAD

**Issue by sealbox** [ethereum/go-ethereum#25786]
Hello,
I would like to get a clarification what is the relation between geth and so-called beacon node after merge? If I understood it correctly, geth is exchanging information with beacon chain in now and it requires beacon chain for syncing?

So I picked the prysm beacon chain implementation as it looked the easiest to run, but I cannot make it work.

My folder structure is as follows:

/home/eth
    /.ethereum # data
    /node # geth (1.10.24)
    /node_beacon # prysm (3.1.1)

I whitelisted all TCP, UDP ports required for running both and checked with MX Toolbox that ports are discoverable (RPC and P2P for both geth and prysm).

I am running geth with following options:

/home/eth/node/build/bin/geth --cache=4096 --http --http.api eth,web3,net,engine,debug,personal --http.addr 0.0.0.0 --http.port 12001 --port 30303 --datadir=/home/eth/.ethereum --allow-insecure-unlock --rpc.allow-unprotected-txs --authrpc.addr 0.0.0.0 --authrpc.port 8551 --authrpc.vhosts 0.0.0.0 --authrpc.jwtsecret /home/eth/node_beacon/jwt.hex

I am running prysm with following options:

/home/eth/node_beacon/prysm.sh beacon-chain --datadir=/home/eth/.ethereum --http-web3provider=http://127.0.0.1:12001 --rpc-host=0.0.0.0 --monitoring-host=0.0.0.0 --execution-endpoint=http://127.0.0.1:8551 --accept-terms-of-use --jwt-secret=/home/eth/node_beacon/jwt.hex

And both services seem to start up and run fine, I do not get any errors. However, after they are setup it seems the geth waits for prysm while prysm waits for geth:

Those are the logs:

Geth:

WARN [09-15|22:52:53.139] Local chain is post-merge, waiting for beacon client sync switch-over...
INFO [09-15|22:50:49.891] Legacy sync reached merge threshold      number=15,537,419 hash=78c1c2..58cd79 td=58,750,256,312,486,924,353,244 ttd=58,750,000,000,000,000,000,000

Prysm:

time="2022-09-15 22:51:18" level=warning msg="Execution client is not syncing" prefix=powchain
time="2022-09-15 22:51:22" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0

From the logs it seems to me that geth waits for prysm to start doing something, while prysm complaining the geth is not syncing anything? What am I doing wrong? It's really unclear to me how to setup both properly.

EDIT:

I already asked this in https://github.com/ethereum/go-ethereum/issues/25778 but @karalabe closed the issue unjustly without providing real answer, just a gimmicks without even providing example of that gimmick! Don't close my issue without answering the question. The geth is no longer standalone node so it needs the beacon to work properly. I do not see any documentation how to do properly on geth side and following prysm documentation I ma left around hanging for not working sync. Answer the problem that was asked properly. You are just going closing all similar issues and yet, ppl have the same problem as me not able to find the proper answer. If you don't know just avoid this topic karalabe. Thanks!

**Comment by hbernaciak** [comment]
My team is facing a similar issue. Does anyone have a solution on how to bring it up?

**Comment by karalabe** [comment]
Geth requires a consensus client to tell us what to sync. I cannot debug your consensus setup. If Prysm doesn't sync for you, take it up at the Prysm team. Why is your expectation that the Geth team should tell you how to run Prysm?

**Comment by karalabe** [comment]
Also, the only two logs you provided are

```
time="2022-09-15 22:51:18" level=warning msg="Execution client is not syncing" prefix=powchain
time="2022-09-15 22:51:22" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
```

1. Execution client is not syncing

Yes, we are not syncing because the consensus client didn't tell us what to sync. We need to update from the consensus side.

2. Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0

Seems to be pretty clear, your Prysm node has 0 peers. How do you expect it to sync with no peer connections?

**Comment by holiman** [comment]
You need both a CL and EL clients. The CL is the consensus "driver", telling EL what 'head' to sync from. This is a requirement for syncing. Thus, the CL needs to sync first. 


As @karalabe already pointed out (https://github.com/ethereum/go-ethereum/issues/25778#issuecomment-1249119349), 

> You can also use a checkpoint sync from e.g. Infura or another trusted beacon client to sync it within a few minutes.


This is the go-ethereum issue tracker, meant for us to track bugs/issues with go-ethereum. If you are looking for questions and answers regarding how to set up and operate nodes, then this is not the best forum. Stack Exchange might be better, and/or the geth discord. For questions related to CL clients like prysm, please turn to their channels/trackers/documentation.

**Comment by sealbox** [comment]
```
Seems to be pretty clear, your Prysm node has 0 peers. How do you expect it to sync with no peer connections?
```

And why do I still have 0 peer connections after having ports open and checked and everything being run as according to documentation? This is no issue related to prysm, but an issue related for running geth-prysm together. How do I know the bug is not on geth side?

Ok so it seems "integration" of geth with beacon, which is integral part of setting geth nowadays as on standalone it is useless is "outside of scope" for geth developers. What's next, will you tell me, that you don't do any testing across those vendors and just hope geth works correctly? Or that you don't care about those vendors and henceforth your own users that will have to run those two together and would like an answer from ppl like you with more experience on the subject? Pitiful approach for a node for a platform that wants to be leading smart contract platform. I got really disappointed from you today.

**Comment by karalabe** [comment]
> And why do I still have 0 peer connections after having ports open and checked and everything being run as according to documentation? 

Ask Prysm devs. Why do you expect me to know the answer why your setup or Prysm is off?

> This is no issue related to prysm, but an issue related for running geth-prysm together. How do I know the bug is not on geth side?

Because Geth has absolutely 0 to do with the beacon client's P2P network. It's a completely different thing altogether. The beacon/consensus client needs to have it's own network connection to it's counterpart peers. Why it cannot do that for you, I have no idea. You should probably raise the log levels in your Prysm node and see what's happening. Or you know, ask the Prsym devs how you could debug it further.

> What's next, will you tell me, that you don't do any testing across those vendors and just hope geth works correctly?

That is exactly true. Geth conforms to the spec and passes all the integration tests for it. We don't need to test how vendor Xs project Y works, because it's irrelevant. But in this specific case, your issue has nothing to do with integration, your beacon client setup if off somewhere, and you'll need to find it and figure it out. Based on your logs, the issue is that your beacon client does not have network connectivity. That's not on us.

> I got really disappointed from you today.

Sorry for not offering you live customer support for a different open source project than the one your complaining about. Both of which you get to use for free.

**Comment by karalabe** [comment]
Also, just for the record, all EL/CL client combinations are run by EF and are tested and known to work well together. We have live nodes of everything. And guess what, they work. So please stop whining and ask the Prysm devs if they have an idea why your setup is not syncing the beacon chain.

**Comment by sealbox** [comment]
```
Ask Prysm devs. Why do you expect me to know the answer why your setup or Prysm is off?
```

I assume geth developers did some practical acceptance tests with those vendors and may know something about the tweaks of each since geth community is older and bigger than those vendors, geth itself can no longer works standalone and it is multi-billion USD platform that it builds for, right? It is not university project aimed to get passing mark.

```
That is exactly true. Geth conforms to the spec and passes all the integration tests for it. We don't need to test how vendor Xs project Y works, because it's irrelevant. 
```

Ok then please tell me how to run functional geth node with that "spec" without any vendor? I would like to hear it.

```
Because Geth has absolutely 0 to do with the beacon client's P2P network. 
```

Ok then I do not need beacon right? It has zero to do with geth, so geth can work after merge in standalone mode right?

```
Also, just for the record, all EL/CL client combinations are run by EF and are tested and known to work well together. We have live nodes of everything.
```

Ok, cool, so you DO HAVE the differnt vendors setup. Then maybe you could help me with your experiene of running those nodes? Did you maybe get in the same issue as I did here?

**Comment by jpop32** [comment]
> Ok, cool, so you DO HAVE the differnt vendors setup. Then maybe you could help me with your experiene of running those nodes? Did you maybe get in the same issue as I did here?

Dude, you're asking an engine manufacturer why the satnav on your car doesn't work correctly. And get all entitled, huffy and hurt when they refuse to spend their scarce time in troubleshooting your issue. And, mind you, engine manufacturers that gave you the engine for free. So check your attitude and go ask for help somewhere appropriate.
