### ISSUE TITLE
以太坊分片发展——自动伸缩网状区块链

### ISSUE THREAD

**Issue by fanhai** [ethereum/go-ethereum#25783]
# Rationale

Why should this feature exist?
What are the use-cases?
多分片并行,区别于单链结构，应该像渔网一样，能够随着消息量的增多网口逐渐扩大，随着消息量的减少网口逐渐缩小，理论上渔网口可以无限扩大，也就是TPS可以逐步无限扩大。真正解决了区块链交易速度、交易容量问题。

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?
我已经实现了网状区块链分叉合并，并行出块保证一致性同时保证交易容量，目前测试 单分片也就是单账户串行tps 可达200/s ，多分片tps叠加。项目地址
https://github.com/asmbio/doc

**Comment by ruozia** [comment]
Wonderful!
