### ISSUE TITLE
Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain

### ISSUE THREAD

**Issue by axing1991** [ethereum/go-ethereum#25785]
#### System information
Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain

####device infomation
Version: 1.10.25-stable
Git Commit: 69568c554880b3567bace64f8848ff1be27d084d
Architecture: amd64
Go Version: go1.18.5
Operating System: linux

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by axing1991** [comment]
geth:
<img width="1027" alt="WX20220916-163414@2x" src="https://user-images.githubusercontent.com/12743125/190594581-8dd47a5d-d57d-449a-a621-fde0f58d89be.png">

eth2:
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/12743125/190594648-310df94a-ba5b-4422-b7d0-50f98b14bb8c.png">

**Comment by karalabe** [comment]
You'll need to wait for the consensus client to finish syncing. Based on your logs, it says it has 64h still to go. You can probably also use a checkpoint (eg. from infura) to sync it up to head fast.
