### ISSUE TITLE
cannot sync blocks

### ISSUE THREAD

**Issue by tongxurt** [ethereum/go-ethereum#25784]
#### System information

Geth version: `v1.10.25`
OS & Version: Linux

after run command : geth  --http --http.api web3,eth,n,debug --http.addr 0.0.0.0 --http.port 8545 --syncmode snap --gcmode archive  nothing found but this logs below and did not sync any block 

INFO [09-16|08:20:29.817] Looking for peers                        peercount=2 tried=24 static=0
INFO [09-16|08:20:40.149] Looking for peers                        peercount=1 tried=25 static=0
WARN [09-16|08:20:45.896] Served admin_peers                       conn=172.17.0.1:54288 reqid=1 duration="9.66µs"   err="the method admin_peers does not exist/is not available"
WARN [09-16|08:20:46.390] Served parity_netPeers                   conn=172.17.0.1:54288 reqid=1 duration="12.159µs" err="the method parity_netPeers does not exist/is not available"
WARN [09-16|08:20:48.584] Dropping unsynced node during sync       id=ef618c0997063d36 conn=dyndial          addr=95.217.88.31:30303 type=Geth/v1.10.23-stable...
INFO [09-16|08:20:50.482] Looking for peers                        peercount=1 tried=42 static=0
WARN [09-16|08:20:51.511] Dropping unsynced node during sync       id=ef6d430c3349163c conn=dyndial          addr=15.235.50.81:30303 type=Geth/v1.10.25-stable...
WARN [09-16|08:20:59.318] Dropping unsynced node during sync       id=ef250c16e97ec455 conn=dyndial          addr=96.80.156.253:30303 type=besu/v22.7.2/linux-x...
INFO [09-16|08:21:00.482] Looking for peers                        peercount=1 tried=36 static=0
INFO [09-16|08:21:10.482] Looking for peers                        peercount=1 tried=34 static=0
WARN [09-16|08:21:19.519] Snapshot extension registration failed   peer=d5a6c885 err="peer connected on snap without compatible eth support"
INFO [09-16|08:21:20.483] Looking for peers                        peercount=2 tried=32 static=0
WARN [09-16|08:21:24.791] Snapshot extension registration failed   peer=e118b10a err="peer connected on snap without compatible eth support"
WARN [09-16|08:21:30.570] Served admin_peers                       conn=172.17.0.1:42846 reqid=1 duration="7.85µs"   err="the method admin_peers does not exist/is not available"
INFO [09-16|08:21:30.659] Looking for peers                        peercount=2 tried=38 static=0
WARN [09-16|08:21:31.096] Served parity_netPeers                   conn=172.17.0.1:42846 reqid=1 duration="9.68µs"   err="the method parity_netPeers does not exist/is not available"
INFO [09-16|08:21:40.659] Looking for peers                        peercount=2 tried=36 static=0
INFO [09-16|08:21:50.659] Looking for peers                        peercount=2 tried=32 static=0
INFO [09-16|08:22:00.659] Looking for peers                        peercount=2 tried=34 static=0
WARN [09-16|08:22:02.970] Served admin_peers                       conn=172.17.0.1:34182 reqid=1 duration="7.04µs"   err="the method admin_peers does not exist/is not available"
WARN [09-16|08:22:03.590] Served parity_netPeers                   conn=172.17.0.1:34182 reqid=1 duration="9.62µs"   err="the method parity_netPeers does not exist/is not available"
INFO [09-16|08:22:10.992] Looking for peers                        peercount=2 tried=35 static=0
INFO [09-16|08:22:20.993] Looking for peers                        peercount=2 tried=36 static=0
WARN [09-16|08:22:22.489] Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
WARN [09-16|08:22:25.285] Served admin_peers                       conn=172.17.0.1:38926 reqid=1 duration="8.489µs"  err="the method admin_peers does not exist/is not available"
WARN [09-16|08:22:25.748] Served parity_netPeers                   conn=172.17.0.1:38926 reqid=1 duration="19.469µs" err="the method parity_netPeers does not exist/is not available"
WARN [09-16|08:23:08.526] Served admin_peers                       conn=172.17.0.1:58318 reqid=1 duration="9.399µs"  err="the method admin_peers does not exist/is not available"
WARN [09-16|08:23:09.021] Served parity_netPeers                   conn=172.17.0.1:58318 reqid=1 duration="7.27µs"   err="the method parity_netPeers does not exist/is not available"
WARN [09-16|08:23:15.817] Snapshot extension registration failed   peer=443df8b7 err="peer connected on snap without compatible eth support"
WARN [09-16|08:23:43.582] Snapshot extension registration failed   peer=d7df5085 err="peer connected on snap without compatible eth support"
WARN [09-16|08:23:53.136] Served admin_peers                       conn=172.17.0.1:60812 reqid=1 duration="8.8µs"    err="the method admin_peers does not exist/is not available"
WARN [09-16|08:23:53.855] Served admin_peers                       conn=172.17.0.1:46890 reqid=1 duration="10.009µs" err="the method admin_peers does not exist/is not available"
WARN [09-16|08:23:54.363] Served parity_netPeers                   conn=172.17.0.1:46890 reqid=1 duration="13.56µs"  err="the method parity_netPeers does not exist/is not available"
WARN [09-16|08:23:54.689] Served parity_netPeers                   conn=172.17.0.1:60812 reqid=1 duration="9.519µs"  err="the method parity_netPeers does not exist/is not available"
WARN [09-16|08:24:39.739] Served admin_peers                       conn=172.17.0.1:35458 reqid=1 duration="14.08µs"  err="the method admin_peers does not exist/is not available"
WARN [09-16|08:24:40.399] Served parity_netPeers                   conn=172.17.0.1:35458 reqid=1 duration="8.389µs"  err="the method parity_netPeers does not exist/is not available

**Comment by karalabe** [comment]
You need a consensus/beacon client running and connected to Geth. https://blog.ethereum.org/2022/08/24/mainnet-merge-announcement
