### ISSUE TITLE
signTransaction rpc

### ISSUE THREAD

**Issue by mongrim** [ethereum/go-ethereum#2578]
#### System information

Geth version: `geth 1.4.*`
OS & Version: Ubuntu 14

#### Expected behaviour

Return raw transaction along with transaction json data. After sending, transaction json representation stays the same.

#### Actual behaviour

In versions 1.4.0-1.4.3 signTransaction returns json like 
{
  raw: "0xf8658085051251fec083015f9094095a9ae02a321cc7a90c298788055c5dc335ddf680801ca061e4d07f1d0c03efc1869ed70d9c1d568757e8a26d3f98412f53c543bfeda949a07f489f8990ebb57afa1fa6db034fd638d82c261722dde2c1d109b0569525431d",
  tx: {
    data: ..,
    **from: "0x0000000000000000000000000000000000000000",**
    gas: ...,
    gasPrice: ...,
    hash: "0xe938b511610b45149c0cf09dd598f45f7afecf67ed5abb936df920a5e838661f",
    nonce: ...,
    to: ...
    value: ..
  }
}

When i send such transaction, it appears in pool with proper 'from' attribute and **different** hash. I know, that it is unofficial method, but it worked great in previous versions and I hope you will not just remove it or leave in such state.

**Comment by obscuren** [comment]
You have to specify `from` which will then prompt for a password and return you the signed transaction.
