### ISSUE TITLE
Problems with syncing after merging.Please launch one to follow the chain!

### ISSUE THREAD

**Issue by DUya98** [ethereum/go-ethereum#25791]
```
Sep 16 13:05:22 Ubuntu-2204-jammy-amd64-base geth[2980]: INFO [09-16|13:05:22.075] Looking for peers                        peercount=1 tried=27 static=0
Sep 16 13:05:26 Ubuntu-2204-jammy-amd64-base geth[2980]: WARN [09-16|13:05:26.407] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
Sep 16 13:05:32 Ubuntu-2204-jammy-amd64-base geth[2980]: INFO [09-16|13:05:32.113] Looking for peers                        peercount=2 tried=33 static=0
Sep 16 13:05:42 Ubuntu-2204-jammy-amd64-base geth[2980]: INFO [09-16|13:05:42.273] Looking for peers                        peercount=4 tried=31 static=0
Sep 16 13:05:52 Ubuntu-2204-jammy-amd64-base geth[2980]: INFO [09-16|13:05:52.409] Looking for peers                        peercount=4 tried=25 static=0
Sep 16 13:06:02 Ubuntu-2204-jammy-amd64-base geth[2980]: INFO [09-16|13:06:02.409] Looking for peers                        peercount=4 tried=34 static=0
Sep 16 13:06:12 Ubuntu-2204-jammy-amd64-base geth[2980]: INFO [09-16|13:06:12.742] Looking for peers                        peercount=4 tried=30 static=0
Sep 16 13:10:26 Ubuntu-2204-jammy-amd64-base geth[2980]: WARN [09-16|13:10:26.441] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
Sep 16 13:11:27 Ubuntu-2204-jammy-amd64-base geth[2980]: WARN [09-16|13:11:27.757] Snapshot extension registration failed   peer=11a2b5e0 err="peer connected on snap without compatible eth support"
Sep 16 13:11:32 Ubuntu-2204-jammy-amd64-base geth[2980]: WARN [09-16|13:11:32.593] Snapshot extension registration failed   peer=04dfa983 err="peer connected on snap without compatible eth support"
```
## Post-merge network, but no beacon client seen. Please launch one to follow the chain!

I can't get my node to start syncing and the above is the current log, is there any way to fix it please.
I just need a full node.

```shell
geth --datadir /home/chain/data --cache 64000 --pprof.addr 0.0.0.0 --pprof --http --http.addr 0.0.0.0 --http.corsdomain '*' --ws.addr 0.0.0.0 --ws.origins '*' --ws --ws.api eth,net,web3,txpool,debug  --rpc.txfeecap 0 --http.api eth,net,web3,txpool,debug,admin --rpc.allow-unprotected-txs --txlookuplimit 0  --maxpeers 200 --syncmode=full
```
These are my start-up instructions

**Comment by victorelec14** [comment]
try with "snap", the full i think is now the "archive"

> --syncmode=snap

**Comment by fjl** [comment]
Since The Merge has now happened on mainnet, you need to run a consensus client alongside geth. See this page for more information: https://geth.ethereum.org/docs/interface/consensus-clients

**Comment by wdcs-DastageerSayed** [comment]
@fjl Cannot find the page you mentioned,. can you provide me with the latest block

**Comment by schutau** [comment]
Have the same issue - has this been resolved?

**Comment by qraxiss** [comment]
> 

This page 404.

**Comment by qraxiss** [comment]
> @fjl Cannot find the page you mentioned,. can you provide me with the latest block

https://geth.ethereum.org/docs/getting-started/consensus-clients

**Comment by bitcoinbrisbane** [comment]
> @fjl Cannot find the page you mentioned,. can you provide me with the latest block

Same issue :(

**Comment by qraxiss** [comment]
> > @fjl Cannot find the page you mentioned,. can you provide me with the latest block
> 
> Same issue :(

Here is the link bro

https://geth.ethereum.org/docs/getting-started/consensus-clients

**Comment by koroteeww** [comment]
thank you guys! so the best way to sync geth on windows is following:
1) laucnh geth from console with parameters of http:
for example like this, paste in in console:

d:\ethd\geth.exe --http --datadir "d:\ethd" --authrpc.addr localhost --authrpc.port 8551 --authrpc.vhosts localhost

2) launch some of consensus clients with port of geth (8551) and dir of jwtsecret 
for example i used lighthouse:

d:\ethd\lighthouse.exe --datadir "d:\ethd\li" bn --execution-endpoint http://localhost:8551 --execution-jwt "d:\ethd\geth\jwtsecret" --checkpoint-sync-url "https://mainnet.checkpoint.sigp.io" --disable-deposit-contract-sync
