### ISSUE TITLE
Missing trie-nodes

### ISSUE THREAD

**Issue by sealbox** [ethereum/go-ethereum#25792]
Hello,
since nobody was able to solve my issue in https://github.com/ethereum/go-ethereum/issues/25786 not geth not prysm developers I decided to switch beacon client to something else. I used lightouse instead which seems to work fine both in normal sync mode and snapshot sync mode. I used snapshot sync because I need to have my production nodes up as soon as possible, and it seems the lightouse is synced and geth also is synced, however I am getting tons of following errors in geth (1.10.24) now:

```
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.089] Unhandled trie error: missing trie node ecc316f70d9b84c04d81d8574b2fca4f0c7f27b3ba37a50cc24acedef3adee99 (path 09) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.089] Unhandled trie error: missing trie node ecc316f70d9b84c04d81d8574b2fca4f0c7f27b3ba37a50cc24acedef3adee99 (path 09) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.103] Unhandled trie error: missing trie node cf192f3a2e8f4b4aedfdc90317e3585d39bfa040267e087e184b93a8dada1237 (path 06) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.103] Unhandled trie error: missing trie node cf192f3a2e8f4b4aedfdc90317e3585d39bfa040267e087e184b93a8dada1237 (path 06) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.145] Unhandled trie error: missing trie node ecc316f70d9b84c04d81d8574b2fca4f0c7f27b3ba37a50cc24acedef3adee99 (path 09) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.145] Unhandled trie error: missing trie node ecc316f70d9b84c04d81d8574b2fca4f0c7f27b3ba37a50cc24acedef3adee99 (path 09) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.159] Unhandled trie error: missing trie node 5ce8c545226c1560affe76b01f1c8a0880e3ad7eb4eb29c5370917b7fdacfc3f (path 0305) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.159] Unhandled trie error: missing trie node 5ce8c545226c1560affe76b01f1c8a0880e3ad7eb4eb29c5370917b7fdacfc3f (path 0305) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.162] Unhandled trie error: missing trie node ecc316f70d9b84c04d81d8574b2fca4f0c7f27b3ba37a50cc24acedef3adee99 (path 09) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.162] Unhandled trie error: missing trie node ecc316f70d9b84c04d81d8574b2fca4f0c7f27b3ba37a50cc24acedef3adee99 (path 09) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.163] Unhandled trie error: missing trie node e5dc9891f0662685dfe26a5b5d1f5e4873a353cd81cba63aefbe6b7602fe4c04 (path 04) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.163] Unhandled trie error: missing trie node e5dc9891f0662685dfe26a5b5d1f5e4873a353cd81cba63aefbe6b7602fe4c04 (path 04) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.180] Unhandled trie error: missing trie node e5dc9891f0662685dfe26a5b5d1f5e4873a353cd81cba63aefbe6b7602fe4c04 (path 04) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.180] Unhandled trie error: missing trie node e5dc9891f0662685dfe26a5b5d1f5e4873a353cd81cba63aefbe6b7602fe4c04 (path 04) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.183] Unhandled trie error: missing trie node 5ce8c545226c1560affe76b01f1c8a0880e3ad7eb4eb29c5370917b7fdacfc3f (path 0305) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.184] Unhandled trie error: missing trie node 5ce8c545226c1560affe76b01f1c8a0880e3ad7eb4eb29c5370917b7fdacfc3f (path 0305) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.198] Unhandled trie error: missing trie node 3861432a3ed0fc7c7f8a7b24e0ebe50c1879a33b0e8ce39ea23fd4a13aefa9c8 (path 0202) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.198] Unhandled trie error: missing trie node 3861432a3ed0fc7c7f8a7b24e0ebe50c1879a33b0e8ce39ea23fd4a13aefa9c8 (path 0202) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.201] Unhandled trie error: missing trie node f24175ddc6bfc4e51af628233a26844b2b08a7c48ee7c41328162c86278d5f96 (path 070105) <nil>
Sep 16 11:42:19 geth[10303]: ERROR[09-16|11:42:19.201] Unhandled trie error: missing trie node f24175ddc6bfc4e51af628233a26844b2b08a7c48ee7c41328162c86278d5f96 (path 070105) <nil>
```

I am not sure if this error is expected to happen? If it is, does it mean I am losing all archive data between merge and snapshot? The syncing is progressing and eth_blockNumber() increases.

**Comment by panicalways** [comment]
> This is the go-ethereum issue tracker, meant for us to track bugs/issues with go-ethereum. If you are looking for questions and answers regarding how to set up and operate nodes, then this is not the best forum. Stack Exchange might be better, and/or the geth discord.

Are you reading the answers?
Dozens of questions and answers come up just by searching for 'Unhandled trie error: missing trie node' on Google. Try them first, and in the process, if this seems to be a problem with the geth client itself, not with the user configuration, post it here.

**Comment by karalabe** [comment]
If you're node is progressing ok, just displaying these messages in the mean time, then everything's fine. There was a verkle tree WIP PR that added some error logs that were not real errors. The log was removed on the master branch already.

**Comment by sealbox** [comment]
@panicalways Dozens of questions and answers come up just by searching for 'Unhandled trie error: missing trie node' on Google.

Yes, and all of those questions and answers which I am familiar of, refer to Ethereum before merge update and before beacon was needed to be run. Those are outdated right now, so ty captain obvious for useless comment.

@karalabe ok, so this is expected to may happen then after merge and there is nothing to worry about. Thanks.

**Comment by v-pcode** [comment]
I was also getting this error while testing on the forknet of arbitrum.When balance of sender is zero for underlying token then get this error.Check the balance of account before making any transaction.

**Comment by pascaldekloe** [comment]
https://support.chainstack.com/hc/en-us/articles/4440543903257-EVM-node-returns-Missing-trie-node-
