### ISSUE TITLE
geth 1.4.4 does not allow "from" address to be null when using RPC eth_call

### ISSUE THREAD

**Issue by slothbag** [ethereum/go-ethereum#2579]
#### System information
Linux Ubuntu 64bit
Geth version: 1.4.4

#### Expected behaviour
As agreed in this https://github.com/ethereum/go-ethereum/issues/2319 closed issue, RPC should allow nulls.

#### Actual behaviour
RPC returns `Invalid address length, expected 40 got 4 bytes`

#### Steps to reproduce the behaviour
Call RPC with from: null

**Comment by obscuren** [comment]
How should `null` be interpreted?

**Comment by slothbag** [comment]
As per the previous issue, null should be considered the default / same as not been passed in.

**Comment by obscuren** [comment]
And then what?

**Comment by obscuren** [comment]
I think this is a bit of a non-issue. Please let us know what kind of problematic behaviour comes because of this and we will consider to re-open this issue if it's valid.

**Comment by slothbag** [comment]
I thought the previous issue which I linked to covered the history, but maybe not.

The c# web3 library Nethereum was working fine with geth-1.3.x branch, however with geth-1.4.x it broke because of a regression in the way geth handles nulls.  So a fix was deployed recently to 1.4.x that addresses most of these null values (see previous issue), however the same regression still exists for the `from` field.

So the desired outcome is, if I pass `from: null` geth does not return an error, it just treats `from` as have not been passed in at all and works.

I think Juan from Nethereum is going to change his library to support not sending the nulls, so it probably wont be an issue much longer.  But it does mean geth has had a partial fix put in place and the process for handling nulls is not standard across all the fields.

**Comment by se3000** [comment]
Nevermind, with the 'latest' param mentioned in https://github.com/ethereum/go-ethereum/issues/2472, this seems just as usable as before. Not mentioned in the wiki, I'll try to get a PR up to document that in the wiki for others.

**Comment by slothbag** [comment]
@se3000 this issue refers to the `from` property, not the `block` property.  Pretty sure they are separate issues.

**Comment by se3000** [comment]
@slothbag you're right. I think the `from` issue brought me here, and once I got that part I ran into the #2472 problem. Sorry for the confusion.
