### ISSUE TITLE
Dark/Night Mode - Add other theme

### ISSUE THREAD

**Issue by jcbm123143** [ethereum/go-ethereum#25800]
# Rationale

Why should this feature exist?
My Graphics Idea to make ETH's website colorful

What are the use-cases?
I am only concerned with people who are colorblind that these features can be used in the future

# Implementation

Do you have ideas regarding the implementation of this feature?
Yes

Are you willing to implement this feature?
Maybe

**Comment by s1na** [comment]
The geth website is being revamped at the moment. It will have dark mode as well. Thanks for raising the issue.
