### ISSUE TITLE
how to generate ketstore by giving

### ISSUE THREAD

**Issue by wonderfulLand** [ethereum/go-ethereum#25805]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

**Comment by wonderfulLand** [comment]
env:  geth
          os:  win11
question:  how to generate ketstore by giving hexPrivateKey?

**Comment by karalabe** [comment]
Geth has a command to import a private key from hex `geth account import`.

**Comment by wonderfulLand** [comment]
not use command.     I want to use golang code  import generate keystore by giving hexPriaveteKey

**Comment by wonderfulLand** [comment]
> not use command. I want to use golang code import generate keystore by giving hexPriaveteKey

not use command. I want to use golang code import generate keystore by giving hexPriaveteKey

**Comment by wonderfulLand** [comment]
> Geth has a command to import a private key from hex `geth account import`.


not use command. I want to use golang code import generate keystore by giving hexPriaveteKey
