### ISSUE TITLE
Head state missing

### ISSUE THREAD

**Issue by Ericalvin** [ethereum/go-ethereum#25811]
Hi all, 
i found my geth log say: 
`Head state missing, repairing            number=15,547,672 hash=720ec2..272a4a snaproot=a83778..60d5e4`

what happened with this ? and what should i do to recover ?

Thank you.

**Comment by rjl493456442** [comment]
Your node should have some unclean shutdown without persisting the nodes in memory. And in the next restart it needs to recover a proper/complete state.

Theoretically the recovery should be finished in a couple of minutes and re-insert blocks on top.

**Comment by Ericalvin** [comment]
> Your node should have some unclean shutdown without persisting the nodes in memory. And in the next restart it needs to recover a proper/complete state.
> 
> Theoretically the recovery should be finished in a couple of minutes and re-insert blocks on top.

Oh, I got that, so i just need  wait for auto recovery , but it been three hours.... is there have any other way to do ?

**Comment by rjl493456442** [comment]
Hmm, it's really weird. You ran snap-sync(default sync mode) for syncing your node right?

**Comment by karalabe** [comment]
Please share logs when you open issues like this. It's very hard to see what's happening. Also please share all the logs, not the the end, the interesting bits are usually a bit further in the past.

**Comment by Ericalvin** [comment]
@rjl493456442 Yes, i ues default sync mode, and  after many hours, it recovery finish, now is back normal... , many thanks.
@karalabe OK, next time will provide more log, thanks too.
