### ISSUE TITLE
Geth docker restart and resync from pow block. re sync from 15,537,172, while last synced number is 15,564,944.

### ISSUE THREAD

**Issue by lansehuiyi6** [ethereum/go-ethereum#25813]
I start geth node and prysm beacon-node on mainnet, both use docker, on AWS Elastic Container Service, both suddently restart, I don't know what caused it.

Then i find ETH node re sync from 15,537,172, while last synced number is 15,564,944.
And the sync speed is too slow .

INFO [09-19|03:47:47.959] ---------------------------------------------------------------------------------------------------------------------------------------------------------

INFO [09-19|03:47:47.959]

INFO [09-19|03:47:52.515] Disk storage enabled for ethash caches dir=/gethMainnetData/geth/ethash count=3

INFO [09-19|03:47:52.515] Disk storage enabled for ethash DAGs dir=/root/.ethash count=2

INFO [09-19|03:47:52.528] Initialising Ethereum protocol network=1 dbversion=8

INFO [09-19|03:47:54.511] Loaded most recent local header number=15,564,944 hash=d93ea0..aa8790 td=58,750,003,716,598,352,816,469 age=8m7s

INFO [09-19|03:47:54.513] Loaded most recent local full block number=15,564,944 hash=d93ea0..aa8790 td=58,750,003,716,598,352,816,469 age=8m7s

INFO [09-19|03:47:54.513] Loaded most recent local fast block number=15,564,944 hash=d93ea0..aa8790 td=58,750,003,716,598,352,816,469 age=8m7s

INFO [09-19|03:47:54.513] Loaded most recent local finalized block number=15,564,855 hash=dd5f9e..01ba17 td=58,750,003,716,598,352,816,469 age=25m55s

INFO [09-19|03:47:54.541] Loaded last fast-sync pivot marker number=15,425,434

WARN [09-19|03:47:54.546] Head state missing, repairing number=15,564,944 hash=d93ea0..aa8790 snaproot=121172..2a5c90

INFO [09-19|03:50:39.737] Loaded most recent local header number=15,564,944 hash=d93ea0..aa8790 td=58,750,003,716,598,352,816,469 age=10m52s

INFO [09-19|03:50:39.737] Loaded most recent local full block number=15,537,172 hash=06b5d0..ccc392 td=58,747,571,640,260,799,172,910 age=3d22h1s

INFO [09-19|03:50:39.737] Loaded most recent local fast block number=15,564,944 hash=d93ea0..aa8790 td=58,750,003,716,598,352,816,469 age=10m52s

INFO [09-19|03:50:39.737] Loaded most recent local finalized block number=15,564,855 hash=dd5f9e..01ba17 td=58,750,003,716,598,352,816,469 age=28m40s

INFO [09-19|03:50:39.737] Loaded last fast-sync pivot marker number=15,425,434

WARN [09-19|03:50:39.743] Enabling snapshot recovery chainhead=15,537,172 diskbase=15,564,719

WARN [09-19|03:50:39.747] Loaded snapshot journal diffs=missing

WARN [09-19|03:50:39.747] Snapshot is not continuous with chain snaproot=121172..2a5c90 chainroot=831423..082946

INFO [09-19|03:50:39.757] Setting new local account address=0x8FAeE769b0b2c4072EF11029B1AeDD5650145b9d

INFO [09-19|03:50:39.757] Loaded local transaction journal transactions=1 dropped=0

INFO [09-19|03:50:39.757] Regenerated local transaction journal transactions=1 accounts=1

WARN [09-19|03:50:39.757] Switch sync mode from snap sync to full sync

WARN [09-19|03:50:39.758] Chain pre-merge, sync via PoW (ensure beacon client is ready)

INFO [09-19|03:50:39.758] Gasprice oracle is ignoring threshold set threshold=2

WARN [09-19|03:50:39.758] Unclean shutdown detected booted=2022-08-26T06:35:34+0000 age=3w2d21h

WARN [09-19|03:50:39.758] Unclean shutdown detected booted=2022-09-19T03:36:13+0000 age=14m26s

WARN [09-19|03:50:39.758] Engine API enabled protocol=eth

INFO [09-19|03:50:39.762] Starting peer-to-peer node instance=Geth/v1.10.23-stable-d901d853/linux-amd64/go1.18.5

INFO [09-19|03:50:39.891] New local node record seq=1,661,486,804,259 id=6697872b43a56c38 ip=127.0.0.1 udp=30303 tcp=30303

INFO [09-19|03:50:39.891] Started P2P networking self=enode://26f1274579273f9e85bab796104a69de286c1a7708a399757ef1c68ea9546d324ee792350b832b71024b92230621cf65091cc1ea95d66936345869998585b39b@127.0.0.1:30303

INFO [09-19|03:50:39.895] IPC endpoint opened url=/gethMainnetData/geth.ipc

INFO [09-19|03:50:39.896] Loaded JWT secret file path=/gethMainnetData/jwt.hex crc32=0x6848607b

INFO [09-19|03:50:39.896] HTTP server started endpoint=[::]:26892 auth=false prefix= cors= vhosts=*

INFO [09-19|03:50:39.896] WebSocket enabled url=ws://[::]:8551

INFO [09-19|03:50:39.897] HTTP server started endpoint=[::]:8551 auth=true prefix= cors=localhost vhosts=*

WARN [09-19|03:50:41.376] Served eth_coinbase conn=195.123.222.16:48074 reqid=1 duration="66.62µs" err="etherbase must be explicitly specified"

WARN [09-19|03:50:41.425] Served eth_coinbase conn=195.123.222.16:48520 reqid=1 duration="45.12µs" err="etherbase must be explicitly specified"

WARN [09-19|03:50:41.533] Served eth_coinbase conn=195.123.222.16:48574 reqid=1 duration="41.09µs" err="etherbase must be explicitly specified"

WARN [09-19|03:50:41.647] Served eth_coinbase conn=195.123.222.16:55312 reqid=1 duration="39.22µs" err="etherbase must be explicitly specified"

WARN [09-19|03:50:41.660] Served eth_coinbase conn=195.123.222.16:55306 reqid=1 duration="86.29µs" err="etherbase must be explicitly specified"

WARN [09-19|03:50:41.661] Served eth_coinbase conn=195.123.222.16:55744 reqid=1 duration="26.21µs" err="etherbase must be explicitly specified"

WARN [09-19|03:50:41.760] Served eth_coinbase conn=195.123.222.16:57256 reqid=1 duration="37.089µs" err="etherbase must be explicitly specified"

WARN [09-19|03:50:41.783] Served eth_coinbase conn=195.123.222.16:57770 reqid=1 duration="38.98µs" err="etherbase must be explicitly specified"

WARN [09-19|03:50:42.075] Served eth_coinbase conn=195.123.222.16:60304 reqid=1 duration="30.411µs" err="etherbase must be explicitly specified"

WARN [09-19|03:50:42.596] Served miner_getHashrate conn=195.123.222.16:49386 reqid=1 duration="15.63µs" err="the method miner_getHashrate does not exist/is not available"

INFO [09-19|03:50:43.407] New local node record seq=1,661,486,804,260 id=6697872b43a56c38 ip=52.89.90.120 udp=30303 tcp=30303

**Comment by mohammadfarari1360** [comment]
Good

**Comment by karalabe** [comment]
Seems that you hard terminated Geth (`WARN [09-19|03:50:39.758] Unclean shutdown detected booted=2022-09-19T03:36:13+0000 age=14m26s`) without a graceful shutdown. That results in state kept in memory (GC) to be lost. In that case, Geth needs to go back to the point where it had a clean shutdown and rerun the blocks from there.

Please make sure things always terminate gracefully.
