### ISSUE TITLE
geth time 

### ISSUE THREAD

**Issue by Ericalvin** [ethereum/go-ethereum#25810]
Hi, every one,
I run prysm+geth on the same host, and my prysm log say:
`Unable to cache headers for execution client votes error=(1663488087 > 1663322891): provided time is later than the current eth1 head`

how to fix this ? thank you.

**Comment by ligaoman0306** [comment]
what do you it ？

**Comment by pepsi1k** [comment]
@Ericalvin how did you fix it?

**Comment by lymweb** [comment]
how did you fix it?

**Comment by pepsi1k** [comment]
@lymweb check v1.10.23, 
I had tried to make `sanpshot prune` and `debug.setHeader()` but nothing help me, so I decided to remove old execution datadir and now all works fine. After beacon-node had synced then it made merge on execution node.
Dont forget to update to latest version.

**Comment by Ericalvin** [comment]
@ligaoman0306 @pepsi1k @lymweb hi, it's because the EL not fully sync finish, so ~ actually... i do nothing , just wait the EL sync finish, then prysm log no longer show those log.

**Comment by thedannguyen** [comment]
I am sorry but what you mean EL fully sync?
I see my GETH node return
 > eth.syncing
false
but I still get the error:
curl http://localhost:8080/healthz
*execution.Service: ERROR, (1663856727 > 1663224162): provided time is later than the current eth1 head
*blockchain.Service: OK
*initialsync.Service: ERROR, syncing
*builder.Service: OK
*p2p.Service: OK
*attestations.Service: OK
*sync.Service: OK
*rpc.Service: ERROR, syncing
*gateway.Gateway: OK
*prometheus.Service: OK

**Comment by pepsi1k** [comment]
@Ericalvin no, my EL node was fully synced, before pos merge. Then I configured the beacon client and it was showing me exact the same message.
That because regression in release 1.10.22.

What I can say that my ropsten node even was not able to merge beacon chain because of this log.
So... After updating to 1.10.23+ and removing geth-chaindir it already working as suppose to be

**Comment by wzl521** [comment]
time="2024-03-05 12:31:16" level=warning msg="Unable to cache headers for execution client votes" error="(1709568087 > 1674447659): provided time is later than the current eth1 head" prefix=powchain
how to solve this problem?
