### ISSUE TITLE
We encounter missing trie node on block no : 15549596

### ISSUE THREAD

**Issue by eu09** [ethereum/go-ethereum#25815]
#### System information

Geth version: `1.10.23-stable`
OS & Version: Ubuntu Linux ( Docker ) 
Commit hash : (if `develop`)

Command to start  :    command: --mainnet --syncmode=snap --datadir /data --http --http.addr 0.0.0.0 --http.api eth,web3,net,debug,txpool --ws --ws.api eth,web3,net,debug,txpool --ws.addr 0.0.0.0 --ws.origins='*' --http.corsdomain='*' --http.vhosts='*' --rpc.allow-unprotected-txs --metrics
--metrics.expensive --metrics.influxdb --metrics.influxdb.endpoint='http://x.x.x.x:8086' --metrics.influxdb.username='xxx' --metrics.influxdb.password='xxxx' --metrics.influxdb.database='ethjp2-1' --cache 2048 --maxpeers 30 --authrpc.addr localhost --authrpc.port 8551 --authrpc.vhosts localhost --authrpc.jwtsecret /data/jwtsecret

The Beacon node we are using chainsafe/lodestar:latest. ( ENV YARN_VERSION=1.22.19)

#### Expected behaviour
We using the same content to request to infura.io nodes , 
it is response the result  "result": "0x45df0495a2d173e"

#### Actual behaviour
it is response the result  : 
missing trie node b3d6754bee2a89ec8f5a390ec5b474b1bee0108eb26500f556a8bec6e3db51c0 (path ) <nil>"

#### Steps to reproduce the behaviour
When we using the postman to make a below method request , 
{
    "jsonrpc": "2.0",
    "method": "eth_getBalance",
    "params": [
        "0xe41530b5f0a30b13cb027b94812f91742f3557d2",
        "0xB8F3A7"
    ],
    "id": 1
}

The endpoint response  :  response:
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "missing trie node 48fb5a41730d3101690d40e3933e55e6351c46a20de7cbdf9bb3a1ddadf107f8 (path ) <nil>"
    }
}

We check at the log of our goethereum , the message as below 
INFO [09-17|00:00:11.963] Imported new potential chain segment     blocks=1 txs=41   mgas=1.785  elapsed=50.589ms     mgasps=35.282   number=15,549,596 hash=4588d4..3c8af7 dirty=509.72MiB
INFO [09-17|00:00:12.072] Chain head was updated                   number=15,549,596 hash=4588d4..3c8af7 root=b3d675..db51c0 elapsed="954.406µs"

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by holiman** [comment]
You are requesting the balance for address `0xe41530b5f0a30b13cb027b94812f91742f3557d2`, at blocknumber `12M` 
```
>>> 0xB8F3A7
12120999
```
The stateroot for that block is `0x48fb5a41730d3101690d40e3933e55e6351c46a20de7cbdf9bb3a1ddadf107f8` (https://etherscan.io/block/12120999), so geth tries to look it up. However: 
```
"missing trie node 48fb5a41730d3101690d40e3933e55e6351c46a20de7cbdf9bb3a1ddadf107f8 (path ) "
```
You do not have the state for block `12120999`. This is to be expected, a snap-synced node will only ever have the most recent state, after the "pivot point" around the time the sync was performed.

**Comment by eu09** [comment]
Usually "pivot point" is how long , can we estiamate ?

**Comment by holiman** [comment]
The earliest point you can look up the state for, can be determined via: 

```
> debug.GetAccessibleState(1, "latest")
```

Generally, it's around the time when you completed the sync.
