### ISSUE TITLE
missing trie node exception on latest block

### ISSUE THREAD

**Issue by ktjooho** [ethereum/go-ethereum#25826]
1. geth version : 1.10.24.unstable(ecefab51888cce3ac7ee2d49c75c5df8618ff4d9)
2. description 
I got 'missing trie node exception' on latest block issue. Below is the sequence of what I tried. 
(1) Receive event logs from latest block(let say block number A)
(2) Request eth_call to call contract on block A to fetch some data which is mapping type storage data. 
(3) Returned 'missing trie node exception path (...)' message from the call
> missing trie node 288259a570829264e76b2c58d4369b5a94f086018dc4409d1d0131405c5d1975 (path )

Is it possible to occurred missing trie node exception on latest block.?? 
Some query to storage on which has no data(no key in the map)  would make missing trie node issue?

Thanks.

**Comment by holiman** [comment]
Since the path is empty, it means that the missing trie node is a root. Therefore, I would suspect that it's the stateRoot of the block you are trying to use, block `A`. If that is the case, then I would also suspect that block `A` recently became older than `128` blocks, and the root was garbage-collected.

**Comment by holiman** [comment]
Yup: https://etherscan.io/block/15572430 , block `15572430` has stateroot `0x288259a570829264e76b2c58d4369b5a94f086018dc4409d1d0131405c5d1975`. 

If it's indeed the `latest` block you are using, then it is indeed a bit odd that you would get this error. Could you provide some info on how you are invoking the calls?

**Comment by ktjooho** [comment]
It was my code issue.
```json
{"time":"2022-09-20T09:29:00.973Z", "msg":"Contract call error (protocol impl or pruned storage) : Returned error: missing trie node b04acd9b3393c76b27c89ed01002986f781ba8a6a97d0f2ed80c2d3f8fc0dcba (path ) <nil> - on 0x6c6Bc977E13Df9b0de53b251522280BB72383700,  request block: 15573632 , current block : 15573804)"}
```
eth_call api call was requested way late(some scheduling issue in my code). The above log shows request block is older than 128. 

Thanks!
