### ISSUE TITLE
Shanghai tracking issue

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum/go-ethereum#25820]
Shanghai is not fully specified yet, but it is good to track all ongoing efforts for shanghai:

| EIP | PR | Merged | 
| -- | -- | -- |
[EIP-3540: EVM Object Format (EOF) v1](https://eips.ethereum.org/EIPS/eip-3540) | https://github.com/ethereum/go-ethereum/pull/22958 |   |
[EIP-3651: Warm COINBASE](https://eips.ethereum.org/EIPS/eip-3651) | https://github.com/ethereum/go-ethereum/pull/25819|   |
[EIP-3670: EOF - Code Validation](https://eips.ethereum.org/EIPS/eip-3670) | https://github.com/ethereum/go-ethereum/pull/24090|   |
[EIP-3855: PUSH0 instruction](https://eips.ethereum.org/EIPS/eip-3855)|  https://github.com/ethereum/go-ethereum/pull/24039|  y  |
[EIP-3860: Limit and meter initcode](https://eips.ethereum.org/EIPS/eip-3860) | https://github.com/ethereum/go-ethereum/pull/23847|   |
[EIP-4895: Beacon chain push withdrawals as operations](https://eips.ethereum.org/EIPS/eip-4895)|   |
[EIP-4758: Deactivate SELFDESTRUCT](https://eips.ethereum.org/EIPS/eip-4758)| https://github.com/ethereum/go-ethereum/pull/25871 https://github.com/ethereum/go-ethereum/pull/24389 |

**Comment by ruozia** [comment]
The first time I knew

**Comment by tynes** [comment]
Can we get a `maybe-shanghai` label on https://github.com/ethereum/go-ethereum/pull/26003 please?

**Comment by s1na** [comment]
Version [v.11.5](https://github.com/ethereum/go-ethereum/releases/tag/v1.11.5) enabled Shanghai for mainnet nodes.  Closing the issue.
