### ISSUE TITLE
problem `connect: connection refused` in prysm and geth ethereum 2

### ISSUE THREAD

**Issue by kasrakhamesi** [ethereum/go-ethereum#25823]
hi , i have error when i want run prysm and geth

this is my error : 
[2022-09-19 23:30:20] ERROR powchain: Could not connect to execution endpoint error=Post "http://127.0.0.1:8551": dial tcp 195.248.241.207:8551: connect: connection refused: Post "http://127.0.0.1:8551": dial tcp 127.0.0.1:8551: connect: connection refused

i use docker to run prysm and geth together
i pull last geth & prysm in dockerhub

prysm docker document : https://docs.prylabs.network/docs/install/install-with-docker

prysm docker run command  =>  docker run -d -it  --network ethereum -p 4000:4000 -p 13000:13000 -p 12000:12000/udp --name beacon-node gcr.io/prysmaticlabs/prysm/beacon-chain:stable --datadir=/data --jwt-secret="MY JWT PATH" --rpc-host=0.0.0.0 --grpc-gateway-host=0.0.0.0 --monitoring-host=0.0.0.0 --suggested-fee-recipient="MY ETHER ADDRESS"--execution-endpoint=http://127.0.0.1:8551 --accept-terms-of-use

geth docker run command => docker run --name ethereum-node -d -p 8545:8545 -p 8551:8551 -p 8550:8550  --network ethereum -p 30303:30303 -p 8546:8546 -it ethereum/client-go --syncmode snap --http --http.api eth,net,engine,admin --http.rpcprefix=/ --http.corsdomain="*" --http.addr 0.0.0.0 --ws --ipcdisable --ws.addr 0.0.0.0 --ws.origins="*" --datadir /diskb/ethereum/chaindata --authrpc.jwtsecret "MY JWT TOKEN" --authrpc.port 8551 --authrpc.vhosts "*"

how can fix it ?

**Comment by karalabe** [comment]
`127.0.0.1` refers to the local machine. In the case of docker containers, it refers to the local container. When you start separate containers for Geth and Prysm, they will be as if they were separate VMs. `127.0.0.1` within each will refer to itself, not the other.

You need to configure the proper IP address to reach Geth. Since you seem to be placing the two hosts on the same docker network, I think you can also use the container name to reach Geth, you don't even need an IP (i.e. `--execution-endpoint=http://ethereum-node:8551`)

**Comment by kasrakhamesi** [comment]
> `127.0.0.1` refers to the local machine. In the case of docker containers, it refers to the local container. When you start separate containers for Geth and Prysm, they will be as if they were separate VMs. `127.0.0.1` within each will refer to itself, not the other.
> 
> You need to configure the proper IP address to reach Geth. Since you seem to be placing the two hosts on the same docker network, I think you can also use the container name to reach Geth, you don't even need an IP (i.e. `--execution-endpoint=http://ethereum-node:8551`)

I tried this too , but it didn't solve my problem :(

**Comment by dullerino** [comment]
What @karalabe said also applies to geth. 
By default `authrpc.addr` listening address is set to `127.0.0.1/localhost`. 
So you have to set `--authrpc.addr=172.18.0.2` or `--authrpc.addr=ethereum-node`.

**Comment by kasrakhamesi** [comment]
> What @karalabe said also applies to geth. By default `authrpc.addr` listening address is set to `127.0.0.1/localhost`. So you have to set `--authrpc.addr=172.18.0.2` or `--authrpc.addr=ethereum-node`.

solved, thanks <3

**Comment by jgresham** [comment]
For some, you may need to change `--authrpc.vhosts value` a "Comma separated list of virtual hostnames from which to accept requests (server enforced). Accepts '*' wildcard. (default: "localhost")"

I needed to add `host.docker.internal` and set to `localhost,host.docker.internal`

**Comment by MariusVanDerWijden** [comment]
Issue seems solved, will close

**Comment by dullerino** [comment]
> > What @karalabe said also applies to geth. By default `authrpc.addr` listening address is set to `127.0.0.1/localhost`. So you have to set `--authrpc.addr=172.18.0.2` or `--authrpc.addr=ethereum-node`.
> 
> hello , when i set authrpc.addr ethereum-node i received this error Fatal: Error starting protocol stack: listen tcp: lookup ethereum-node on 185.12.64.2:53: no such host
> 
> What should I do?

Your DNS cannot find an IP address for the name "ethereum-node". Try using the IP address of your Geth node or set the DNS name.
