### ISSUE TITLE
Unlock mechanism flaw mist opens 2 second unlock timout window.

### ISSUE THREAD

**Issue by pat-kim** [ethereum/go-ethereum#2584]
Geth version: All verions
OS & Version: All operating systems

**Expected behaviour:**

From user perspective API call communication between mist and geth scheme does not allow man in middle attack. 

**Actual behaviour:**
Mist calls geth in order to send tx with account unlocking for 2 second. Not likely other wallet singed tx itself and send before sending to the geth this allows man in middle attack via IPC and RPC while making a transaction by mist.   

**Steps to reproduce the behaviour:**
Simple batch script successfully hijack transaction to IPC with default mist and geth settings.
Refer the following video.

https://www.youtube.com/watch?v=PNSwFy__m-8

**Comment by bas-vk** [comment]
Addressed in https://github.com/ethereum/go-ethereum/pull/2564.
Will leave this open to prevent duplicates.
