### ISSUE TITLE
Can't switch from syncmode=snap to syncmode=full

### ISSUE THREAD

**Issue by enertom** [ethereum/go-ethereum#25840]
#### System information

Geth/v1.10.25-stable-69568c55/linux-amd64/go1.18.6

#### Expected behaviour
Switch to full syncmode.

#### Actual behaviour
Stayed in snap syncmode

#### Steps to reproduce the behaviour

Sync in syncmode=snap then swith syncmode to full.

#### Backtrace

````
INFO [09-21|13:16:29.445] Disk storage enabled for ethash caches   dir=/root/.ethereum/geth/ethash count=3
INFO [09-21|13:16:29.445] Disk storage enabled for ethash DAGs     dir=/root/.ethash               count=2
INFO [09-21|13:16:29.452] Initialising Ethereum protocol           network=1 dbversion=8
INFO [09-21|13:16:29.479] Loaded most recent local header          number=15,579,937 hash=801b08..8bcfc2 td=58,750,003,716,598,352,816,469 age=7h9m30s
INFO [09-21|13:16:29.480] Loaded most recent local full block      number=0          hash=d4e567..cb8fa3 td=17,179,869,184                 age=53y5mo3w
INFO [09-21|13:16:29.480] Loaded most recent local fast block      number=15,579,937 hash=801b08..8bcfc2 td=58,750,003,716,598,352,816,469 age=7h9m30s
INFO [09-21|13:16:29.483] Loaded last fast-sync pivot marker       number=15,581,878
INFO [09-21|13:16:29.908] Loaded local transaction journal         transactions=0 dropped=0
INFO [09-21|13:16:29.908] Regenerated local transaction journal    transactions=0 accounts=0
WARN [09-21|13:16:29.908] Switch sync mode from full sync to snap sync
````

How can i switch the mode as it was before?
Thanks!

**Comment by holiman** [comment]
Switching from snap to syncmode=full is not supported. Or, rather, the way to do it is to do `geth removebd` (delete all current data) and do a new sync `geth ... syncmode=full` from scratch. 

WHen doing this, you can unfortunately _not_ keep the ancients intact, but must delete them too. Ideally, geth would just import them locally, but that has not been implemented :(
