### ISSUE TITLE
Post Merge Geth as Execution Layer is not able to sync (Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!)

### ISSUE THREAD

**Issue by shishirhome** [ethereum/go-ethereum#25847]
Post Merge Geth as Execution Layer is not able to sync. 

`Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!
`
**Consensus Client:** - lighthouse --version
Lighthouse v3.1.0
BLS library: blst
SHA256 hardware acceleration: true
Specs: mainnet (true), minimal (false), gnosis (false)

**Consensus Client:** - Prysm
curl https://raw.githubusercontent.com/prysmaticlabs/prysm/master/prysm.sh --output prysm.sh && chmod +x prysm.sh

**Execution Client:** Geth version
Geth
Version: 1.10.25-stable
Architecture: amd64
Go Version: go1.19.1
Operating System: darwin

**Current State of CL:**
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/7489497/191662278-76eb0eb7-3045-42b2-9423-e7ee315a8816.png">

**Current State of EL:**

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/7489497/191664111-42de6096-98dd-4a2b-bb10-d52ed8fb9d77.png">

**Do we need wait for CL to catchup fully before we can connect our web3 to Geth EL?**

**Comment by s1na** [comment]
Yes the CL needs to sync. Check out lighthouse's [checkpoint sync](https://lighthouse-book.sigmaprime.io/checkpoint-sync.html) for a faster alternative.

**Comment by shishirhome** [comment]
Hi @karalabe @s1na thanks for the resolution. I am able to sync both my CL and EL by making a lighthouse bn --checkpoint-sync-url.

**Comment by ereztdev** [comment]
Hi, I have the same problem, just started with GETH , but where can I get a valid and trustless sync-url?
