### ISSUE TITLE
fuck ethereum

### ISSUE THREAD

**Issue by custom1337** [ethereum/go-ethereum#25858]
all my niggas hate ethereum
i would of been making tens of thousands per month if the merge didnt happen you guys are jewish

**Comment by pandaninjas** [comment]
> all my niggas hate ethereum i would of been making tens of thousands per month if the merge didnt happen you guys are jewish

Whatever will we do for the racist malware developer????

**Comment by custom1337** [comment]
nothing just saying

**Comment by corwintines** [comment]
> nothing just saying

🤡
