### ISSUE TITLE
Horizontal read-only slave scaling

### ISSUE THREAD

**Issue by pokrovskyy** [ethereum/go-ethereum#25857]
# Rationale

There are many use-cases when one may need to do complex calculations directly on the blockchain. However, in this case CPU is usually the bottleneck. So horizontal scaling to the rescue! But this places certain limitations - each node would have to be synced individually (takes time) and require a lot of disk space (expensive in context of scaling)

# Implementation Idea

It would have been great to have a way to connect read-only "slave" nodes to an external data volume maintained by a fully synced "master" node. That would allow stateful queries to such read-only slave nodes, effectively allowing to scale the geth cloud horizontally, so that the CPU is no longer the bottleneck. And growing/shrinking such cloud would be quick too (no sync needed) 

Note - the data volume can be mounted on the OS level (Samba / CIFS / whatever)

**Comment by holiman** [comment]
I think this is essentially the same as has been suggested before, e.g. in https://github.com/ethereum/go-ethereum/issues/24294 . 

While we agree that it indeed would be a useful feature, it's quite an undertaking and not something that is in the pipeline for our efforts at the moment.
