### ISSUE TITLE
Post-merge network, but no beacon client seen. Please launch one to follow the chain!

### ISSUE THREAD

**Issue by brainstormk** [ethereum/go-ethereum#25856]
I am running ethereum node (v1.10.25-stable) on ubuntu 20.04.
But geth is not syncing after block 15537419.
![image](https://user-images.githubusercontent.com/109654392/191994150-0f7fa6ca-0f7c-4fa2-8625-cd8ad8ce3d52.png)
![image](https://user-images.githubusercontent.com/109654392/191994432-755481f2-3032-43fd-9c60-a3452f0c65f0.png)
How can I fix this issue?
Thanks.

**Comment by rjl493456442** [comment]
You have to setup a beacon node for following the ethereum mainnet.

**Comment by brainstormk** [comment]
I have run beacon node with nimbus

**Comment by vinhtran91** [comment]
> But geth is not syncing after block 15537419.

HI. can you share document to run a beacon node ?

**Comment by rjl493456442** [comment]
https://geth.ethereum.org/docs/interface/consensus-clients
