### ISSUE TITLE
Keystore does not load with large amount of keys (using remote folder)

### ISSUE THREAD

**Issue by mesteve** [ethereum/go-ethereum#25852]
#### System information

Geth version: `1.10.25`
OS & Version: Linux

#### Expected behaviour
Load the entire remote keystore folder that we mounted on the machine using gcsfuse.

#### Actual behaviour
We just decided to upgrade geth from our old version (1.8.16) to the latest version (1.10.25). Everything runs fine except the fact that when we start our blockchain using the mounted storage hosting the keystore, it only starts loading 5 to 10 files then crashes.
It works perfectly with our old version (1.8.16) but does not load properly with the new one (1.10.25)
The error we get when we try to run the command (see command below) is -> No given key or address (but I don't think this error is actually reflective of the real problem)
The folder does contain the wallet we want to unlock but the problem is that prior unlocking the wallet, it does not load the entire remote folder.
Additional infos : with 2000 wallets in our remote keystore it works with 1.10.25, but with 6000+ it does not (but does with 1.8.16)

#### Steps to reproduce the behaviour
cmd : geth --datadir ./data --keystore ~/bucket-keystore/keystore --syncmode 'full' --miner.gastarget '9000000000000' --port 30310 --http --http.addr "10.132.0.3" --http.port 8501 --http.api 'personal,eth,net,web3,txpool,miner' --networkid 4242 --miner.gasprice '0' --miner.etherbase "XXXXXXXXX" --unlock "XXXXXXXXX" --allow-insecure-unlock  --mine console 2>>/tmp/node1.log 

The keystore is a mounted folder with gcsfuse using google cloud storage

#### Backtrace

See below the log of gcsfuse

````
gcs: 2022/09/22 19:29:27.964314 Req          0x1723e: <- StatObject("keystore/")
gcs: 2022/09/22 19:29:27.964575 Req          0x1723f: <- StatObject("keystore")
gcs: 2022/09/22 19:29:27.989783 Req          0x1723f: -> StatObject("keystore") (25.203681ms): not retrying StatObject("keystore"): gcs.NotFoundError: googleapi: Error 404: No such object: test-dev-private/keystore, notFound
gcs: 2022/09/22 19:29:27.991644 Req          0x1723e: -> StatObject("keystore/") (27.363649ms): OK
gcs: 2022/09/22 19:29:27.993212 Req          0x17240: <- ListObjects("keystore/")
gcs: 2022/09/22 19:29:28.291674 Req          0x17240: -> ListObjects("keystore/") (298.457259ms): OK
gcs: 2022/09/22 19:29:28.332148 Req          0x17241: <- ListObjects("keystore/")
gcs: 2022/09/22 19:29:28.402949 Req          0x17241: -> ListObjects("keystore/") (70.804791ms): OK
gcs: 2022/09/22 19:29:28.430886 Req          0x17242: <- StatObject("keystore/")
gcs: 2022/09/22 19:29:28.453508 Req          0x17242: -> StatObject("keystore/") (22.619107ms): OK
gcs: 2022/09/22 19:29:28.453801 Req          0x17243: <- StatObject("keystore/UTC--2018-11-13T21-13-59.453457226Z--0f921a41e37fb106598b8afa2dc8a21709463832")
gcs: 2022/09/22 19:29:28.475422 Req          0x17243: -> StatObject("keystore/UTC--2018-11-13T21-13-59.453457226Z--0f921a41e37fb106598b8afa2dc8a21709463832") (21.616633ms): OK
gcs: 2022/09/22 19:29:28.475914 Req          0x17244: <- StatObject("keystore/UTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483")
gcs: 2022/09/22 19:29:28.476031 Req          0x17244: -> StatObject("keystore/UTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483") (103.736µs): not retrying StatObject("keystore/UTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483"): Get "[https://storage.googleapis.com:443/storage/v1/b/test-dev-private/o/keystore%2FUTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483?projection=full](https://storage.googleapis.com/storage/v1/b/test-dev-private/o/keystore%2FUTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483?projection=full)": net/http: request canceled
2022/09/22 19:29:28.476060 LookUpInode: operation canceled, StatObject: not retrying StatObject("keystore/UTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483"): Get "[https://storage.googleapis.com:443/storage/v1/b/test-dev-private/o/keystore%2FUTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483?projection=full](https://storage.googleapis.com/storage/v1/b/test-dev-private/o/keystore%2FUTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483?projection=full)": net/http: request canceled
fuse: 2022/09/22 19:29:28.476104 *fuseops.LookUpInodeOp error: operation canceled
gcs: 2022/09/22 19:29:28.476438 Req          0x17245: <- StatObject("keystore/UTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483")
gcs: 2022/09/22 19:29:28.476520 Req          0x17245: -> StatObject("keystore/UTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483") (82.425µs): not retrying StatObject("keystore/UTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483"): Get "[https://storage.googleapis.com:443/storage/v1/b/test-dev-private/o/keystore%2FUTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483?projection=full](https://storage.googleapis.com/storage/v1/b/test-dev-private/o/keystore%2FUTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483?projection=full)": net/http: request canceled
2022/09/22 19:29:28.476553 LookUpInode: operation canceled, StatObject: not retrying StatObject("keystore/UTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483"): Get "[https://storage.googleapis.com:443/storage/v1/b/test-dev-private/o/keystore%2FUTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483?projection=full](https://storage.googleapis.com/storage/v1/b/test-dev-private/o/keystore%2FUTC--2018-11-13T21-14-10.562417446Z--98527ca208904af1116cac4437b62d1da0978483?projection=full)": net/http: request canceled
fuse: 2022/09/22 19:29:28.476579 *fuseops.LookUpInodeOp error: operation canceled
````

**Comment by holiman** [comment]
I see no reason why the behaviour would change, since the account/keystore codebase has been very stable. Most likely suspect I can think of would be that dependencies has changed, and of course the golang version. 

Anyway, you say "loading 5 to 10 files then crashes". Could you please provide some stacktraces from such a crash? And also some logs preceding the crash.

**Comment by holiman** [comment]
Tested using 10K keystores ( locally ) - worked fine. It scanned the keystores in ~15ms: 
```
TRACE[09-27|11:55:00.724] Started watching keystore folder         path=/home/user/tmp/manykeys/keystore
DEBUG[09-27|11:55:00.782] FS scan times                            list=13.592053ms set=38.916232ms diff=5.694102ms
TRACE[09-27|11:55:00.953] Handled keystore changes                 time=171.290214ms
```

**Comment by holiman** [comment]
These are the milestones for `1.9.13`: https://github.com/ethereum/go-ethereum/milestone/99?closed=1 . Nothing obvious that I could see. 

I assume you used the prebuilt binaries from download? I checked `1.9.12` and `1.9.13` for linux: 
```
[user@work tmp]$ ./geth-linux-amd64-1.9.13-cbc4ac26/geth version
Geth
Version: 1.9.13-stable
Git Commit: cbc4ac264e9671898bff6ec7e434da3eca4bd273
Git Commit Date: 20200416
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.2
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.14.2.linux.amd64
[user@work tmp]$ ./geth-linux-amd64-1.9.12-b6f1c8dc/geth version
Geth
Version: 1.9.12-stable
Git Commit: b6f1c8dcc058a936955eb8e5766e2962218924bc
Git Commit Date: 20200316
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.8
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.13.8.linux.amd64
```
So the go version was updated from `1.13.8` to `1.14.2`. 
One interesting experiment would be to compile `1.9.12` with `1.14.2`, or vice versa. But yeah, there are a lot of interesting experiments that can be done.

**Comment by holiman** [comment]
If you have docker on the machines, I could make a little program which lists a (remote) directory. Then you could compile+run it using the official golang docker images. Something like 

`docker run golang:latest run ./listing.go /my/remote/dir`
`docker run golang:v1.28.8 run ./listing.go /my/remote/dir`

I'll experiment a bit

**Comment by holiman** [comment]
> I had to use gcs_debug flag on gcsfuse in order to be able to see what is happening and why it does not load properly the keystore

Another interesting data-point would be to use a much smaller keystore, containing maybe `10` files. And do a listing with both the working and non-working, __and__ storing the gcsfuse detailed log. 

Then we could compare exactly what operations are performed, and in what order. That might tell us what has changed, and how we can work around it.

**Comment by holiman** [comment]
Hm, I was apparently deep into investigating this, but the reporter dropped it. So I guess this is no longer an issue, and I'll close it.
