### ISSUE TITLE
Geth syned error

### ISSUE THREAD

**Issue by Ericalvin** [ethereum/go-ethereum#25864]
Hi every one, 
My eth is use prysm+geth, and i found my prysm log say ERROR with:

```
[2022-09-26 02:54:24] ERROR powchain: Unable to process past deposit contract logs, perhaps your execution client is not fully synced error=no contract code at given address
[2022-09-26 02:54:36]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x5505ddd04433 slot=4778056
[2022-09-26 02:54:36]  INFO blockchain: Called fork choice updated with optimistic block finalizedPayloadBlockHash=0xbff17fc43eed headPayloadBlockHash=0x5505ddd04433 headSlot=4778056
[2022-09-26 02:54:36]  INFO blockchain: Synced new block block=0x245e7595... epoch=149314 finalizedEpoch=149312 finalizedRoot=0x714862c4... slot=4778056
[2022-09-26 02:54:36]  INFO blockchain: Finished applying state transition attestations=128 payloadHash=0x5505ddd04433 slot=4778056 syncBitsCount=506 txCount=250
[2022-09-26 02:54:48]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x8ec601757d8e slot=4778057
[2022-09-26 02:54:48]  INFO blockchain: Called fork choice updated with optimistic block finalizedPayloadBlockHash=0xbff17fc43eed headPayloadBlockHash=0x8ec601757d8e headSlot=4778057
```
```
[2022-09-26 02:54:24] ERROR powchain: Unable to process past deposit contract logs, perhaps your execution client is not fully synced error=no contract code at given address
```

but my geth is syned finish, below is geth log :

```
Sep 26 02:54:00  geth[6977]: INFO [09-26|02:54:00.464] Forkchoice requested sync to new head    number=15,614,690 hash=61ddb1..e7c79d
Sep 26 02:54:00  geth[6977]: INFO [09-26|02:54:00.606] Imported new block headers               count=1    elapsed="253.617µs" number=15,614,690 hash=61ddb1..e7c79d
Sep 26 02:54:12  geth[6977]: INFO [09-26|02:54:12.595] Forkchoice requested sync to new head    number=15,614,691 hash=457317..d3f43b
Sep 26 02:54:12  geth[6977]: INFO [09-26|02:54:12.610] Imported new block headers               count=1    elapsed="370.2µs"   number=15,614,691 hash=457317..d3f43b
Sep 26 02:54:12  geth[6977]: INFO [09-26|02:54:12.946] State heal in progress                   accounts=45257@2.46MiB    slots=32476@2.57MiB    codes=1664@12.35MiB nodes=12,848,736@3.55GiB pending=59713
Sep 26 02:54:21  geth[6977]: INFO [09-26|02:54:21.849] Downloader queue stats                   receiptTasks=0    blockTasks=0    itemSize=256.83KiB throttle=1021
Sep 26 02:54:23  geth[6977]: INFO [09-26|02:54:23.889] Forkchoice requested sync to new head    number=15,614,692 hash=ae9bef..7edd8b
Sep 26 02:54:24  geth[6977]: INFO [09-26|02:54:24.612] Imported new block headers               count=1    elapsed="204.985µs" number=15,614,692 hash=ae9bef..7edd8b

```

geth is follow the new block number, why prysm say not fully synced,  thank you.

**Comment by macrocan** [comment]
+1，same issue

**Comment by rjl493456442** [comment]
`Imported new block headers` Geth is still syncing, the state downloading is not finished.

You can obtain the syncing status via console:
- geth attach <datadir>/geth.ipc
- eth.syncing

Geth is not usable when the initial syncing is finished.

**Comment by kemorebiyyj** [comment]
my geth log show:

> INFO [04-18|13:46:24.444] Forkchoice requested sync to new head    number=17,071,592 hash=82917e..6fbd06 finalized=17,071,511
INFO [04-18|13:46:37.419] Forkchoice requested sync to new head    number=17,071,593 hash=2c85c3..ffdac9 finalized=17,071,511
INFO [04-18|13:46:47.872] Forkchoice requested sync to new head    number=17,071,594 hash=631d5b..aabe93 finalized=17,071,511
INFO [04-18|13:47:01.270] Forkchoice requested sync to new head    number=17,071,595 hash=1f23e0..5be847 finalized=17,071,511
INFO [04-18|13:47:12.413] Forkchoice requested sync to new head    number=17,071,596 hash=a46d05..a32206 finalized=17,071,511
INFO [04-18|13:47:25.104] Forkchoice requested sync to new head    number=17,071,597 hash=699871..e99684 finalized=17,071,511
INFO [04-18|13:47:37.165] Forkchoice requested sync to new head    number=17,071,598 hash=c7eabf..b148c2 finalized=17,071,511
INFO [04-18|13:47:48.358] Forkchoice requested sync to new head    number=17,071,599 hash=2425f0..135c3c finalized=17,071,511
INFO [04-18|13:48:01.671] Forkchoice requested sync to new head    number=17,071,600 hash=41d9a6..ce3b3c finalized=17,071,511
INFO [04-18|13:48:12.632] Forkchoice requested sync to new head    number=17,071,601 hash=922e52..44359b finalized=17,071,511
INFO [04-18|13:48:24.139] Forkchoice requested sync to new head    number=17,071,602 hash=c6281d..4cabcd finalized=17,071,511

my prysm logs shows:
time="2023-04-18 13:49:38" level=info msg="Peer summary" activePeers=45 inbound=0 outbound=45 prefix=p2p
time="2023-04-18 13:49:47" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x589cbbe47495 prefix=blockchain slot=6247747
time="2023-04-18 13:49:47" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0x386c89b6a7c4 headPayloadBlockHash=0x589cbbe47495 headSlot=6247747 prefix=blockchain
time="2023-04-18 13:49:47" level=info msg="Synced new block" block=0xc7bddce7... epoch=195242 finalizedEpoch=195240 finalizedRoot=0xa7ca6c1a... prefix=blockchain slot=6247747
time="2023-04-18 13:49:47" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x589cbbe47495 prefix=blockchain slot=6247747 syncBitsCount=505 txCount=100
time="2023-04-18 13:50:00" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x568b4ccfcd98 prefix=blockchain slot=6247748
time="2023-04-18 13:50:00" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0x386c89b6a7c4 headPayloadBlockHash=0x568b4ccfcd98 headSlot=6247748 prefix=blockchain
time="2023-04-18 13:50:00" level=info msg="Synced new block" block=0x16c17dc9... epoch=195242 finalizedEpoch=195240 finalizedRoot=0xa7ca6c1a... prefix=blockchain slot=6247748
time="2023-04-18 13:50:00" level=info msg="Finished applying state transition" attestations=65 payloadHash=0x568b4ccfcd98 prefix=blockchain slot=6247748 syncBitsCount=504 txCount=135

**Comment by kemorebiyyj** [comment]
today i use Geth + Prysm(checkpoint sync),but geth  client keeps showing " Forkchoice requested sync to new head    number=17,071,598 hash=c7eabf..b148c2 finalized=17,071,511" messages. When will it start syncing data?
anyone help,please.
my geth logs shows :

> INFO [04-18|13:47:37.165] Forkchoice requested sync to new head    number=17,071,598 hash=c7eabf..b148c2 finalized=17,071,511
INFO [04-18|13:47:48.358] Forkchoice requested sync to new head    number=17,071,599 hash=2425f0..135c3c finalized=17,071,511
INFO [04-18|13:48:01.671] Forkchoice requested sync to new head    number=17,071,600 hash=41d9a6..ce3b3c finalized=17,071,511
INFO [04-18|13:48:12.632] Forkchoice requested sync to new head    number=17,071,601 hash=922e52..44359b finalized=17,071,511
INFO [04-18|13:48:24.139] Forkchoice requested sync to new head    number=17,071,602 hash=c6281d..4cabcd finalized=17,071,511
INFO [04-18|13:48:36.207] Forkchoice requested sync to new head    number=17,071,603 hash=351e9c..be872f finalized=17,071,511
INFO [04-18|13:48:47.534] Forkchoice requested sync to new head    number=17,071,604 hash=28dd23..08ee75 finalized=17,071,511
INFO [04-18|13:49:02.179] Forkchoice requested sync to new head    number=17,071,605 hash=c13b69..aac07a finalized=17,071,511
INFO [04-18|13:49:13.463] Forkchoice requested sync to new head    number=17,071,606 hash=a118f8..37d721 finalized=17,071,542
INFO [04-18|13:49:24.958] Forkchoice requested sync to new head    number=17,071,607 hash=7c8645..ddf162 finalized=17,071,542
INFO [04-18|13:49:36.038] Forkchoice requested sync to new head    number=17,071,608 hash=7b1104..2b1bed finalized=17,071,542
INFO [04-18|13:49:47.967] Forkchoice requested sync to new head    number=17,071,609 hash=589cbb..9504c7 finalized=17,071,542
INFO [04-18|13:50:00.107] Forkchoice requested sync to new head    number=17,071,610 hash=568b4c..5a557a finalized=17,071,542


my prysm shows:

> time="2023-04-18 13:49:38" level=info msg="Peer summary" activePeers=45 inbound=0 outbound=45 prefix=p2p
time="2023-04-18 13:49:47" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x589cbbe47495 prefix=blockchain slot=6247747
time="2023-04-18 13:49:47" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0x386c89b6a7c4 headPayloadBlockHash=0x589cbbe47495 headSlot=6247747 prefix=blockchain
time="2023-04-18 13:49:47" level=info msg="Synced new block" block=0xc7bddce7... epoch=195242 finalizedEpoch=195240 finalizedRoot=0xa7ca6c1a... prefix=blockchain slot=6247747
time="2023-04-18 13:49:47" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x589cbbe47495 prefix=blockchain slot=6247747 syncBitsCount=505 txCount=100
time="2023-04-18 13:50:00" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x568b4ccfcd98 prefix=blockchain slot=6247748
time="2023-04-18 13:50:00" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0x386c89b6a7c4 headPayloadBlockHash=0x568b4ccfcd98 headSlot=6247748 prefix=blockchain
time="2023-04-18 13:50:00" level=info msg="Synced new block" block=0x16c17dc9... epoch=195242 finalizedEpoch=195240 finalizedRoot=0xa7ca6c1a... prefix=blockchain slot=6247748
time="2023-04-18 13:50:00" level=info msg="Finished applying state transition" attestations=65 payloadHash=0x568b4ccfcd98 prefix=blockchain slot=6247748 syncBitsCount=504 txCount=135

**Comment by kevgithub** [comment]
> today i use Geth + Prysm(checkpoint sync),but geth client keeps showing " Forkchoice requested sync to new head number=17,071,598 hash=c7eabf..b148c2 finalized=17,071,511" messages. When will it start syncing data? anyone help,please. my geth logs shows :
> 
> > INFO [04-18|13:47:37.165] Forkchoice requested sync to new head    number=17,071,598 hash=c7eabf..b148c2 finalized=17,071,511
> > INFO [04-18|13:47:48.358] Forkchoice requested sync to new head    number=17,071,599 hash=2425f0..135c3c finalized=17,071,511
> > INFO [04-18|13:48:01.671] Forkchoice requested sync to new head    number=17,071,600 hash=41d9a6..ce3b3c finalized=17,071,511
> > INFO [04-18|13:48:12.632] Forkchoice requested sync to new head    number=17,071,601 hash=922e52..44359b finalized=17,071,511
> > INFO [04-18|13:48:24.139] Forkchoice requested sync to new head    number=17,071,602 hash=c6281d..4cabcd finalized=17,071,511
> > INFO [04-18|13:48:36.207] Forkchoice requested sync to new head    number=17,071,603 hash=351e9c..be872f finalized=17,071,511
> > INFO [04-18|13:48:47.534] Forkchoice requested sync to new head    number=17,071,604 hash=28dd23..08ee75 finalized=17,071,511
> > INFO [04-18|13:49:02.179] Forkchoice requested sync to new head    number=17,071,605 hash=c13b69..aac07a finalized=17,071,511
> > INFO [04-18|13:49:13.463] Forkchoice requested sync to new head    number=17,071,606 hash=a118f8..37d721 finalized=17,071,542
> > INFO [04-18|13:49:24.958] Forkchoice requested sync to new head    number=17,071,607 hash=7c8645..ddf162 finalized=17,071,542
> > INFO [04-18|13:49:36.038] Forkchoice requested sync to new head    number=17,071,608 hash=7b1104..2b1bed finalized=17,071,542
> > INFO [04-18|13:49:47.967] Forkchoice requested sync to new head    number=17,071,609 hash=589cbb..9504c7 finalized=17,071,542
> > INFO [04-18|13:50:00.107] Forkchoice requested sync to new head    number=17,071,610 hash=568b4c..5a557a finalized=17,071,542
> 
> my prysm shows:
> 
> > time="2023-04-18 13:49:38" level=info msg="Peer summary" activePeers=45 inbound=0 outbound=45 prefix=p2p
> > time="2023-04-18 13:49:47" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x589cbbe47495 prefix=blockchain slot=6247747
> > time="2023-04-18 13:49:47" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0x386c89b6a7c4 headPayloadBlockHash=0x589cbbe47495 headSlot=6247747 prefix=blockchain
> > time="2023-04-18 13:49:47" level=info msg="Synced new block" block=0xc7bddce7... epoch=195242 finalizedEpoch=195240 finalizedRoot=0xa7ca6c1a... prefix=blockchain slot=6247747
> > time="2023-04-18 13:49:47" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x589cbbe47495 prefix=blockchain slot=6247747 syncBitsCount=505 txCount=100
> > time="2023-04-18 13:50:00" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x568b4ccfcd98 prefix=blockchain slot=6247748
> > time="2023-04-18 13:50:00" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0x386c89b6a7c4 headPayloadBlockHash=0x568b4ccfcd98 headSlot=6247748 prefix=blockchain
> > time="2023-04-18 13:50:00" level=info msg="Synced new block" block=0x16c17dc9... epoch=195242 finalizedEpoch=195240 finalizedRoot=0xa7ca6c1a... prefix=blockchain slot=6247748
> > time="2023-04-18 13:50:00" level=info msg="Finished applying state transition" attestations=65 payloadHash=0x568b4ccfcd98 prefix=blockchain slot=6247748 syncBitsCount=504 txCount=135

The same issue here, cant figure out if its normal behavior or bug!!!
