### ISSUE TITLE
block number not sync

### ISSUE THREAD

**Issue by osizadmin** [ethereum/go-ethereum#25866]
we have done the beacon chain upgrade in my server end. 

But Ethereum block number not sync fully. 

It showing 

> eth.syncing
{
  currentBlock: 15615735,
  healedBytecodeBytes: 1598113,
  healedBytecodes: 165,
  healedTrienodeBytes: 272026036,
  healedTrienodes: 938178,
  healingBytecode: 0,
  healingTrienodes: 1191,
  highestBlock: 15615852,
  startingBlock: 0,
  syncedAccountBytes: 45209604051,
  syncedAccounts: 187731817,
  syncedBytecodeBytes: 4448630704,
  syncedBytecodes: 678885,
  syncedStorage: 796440014,
  syncedStorageBytes: 170777119022
}

**eth.syncing.highestBlock - eth.syncing.currentBlock
109**

Let me know how to solve this issue.

**Comment by holiman** [comment]
Your ticket does not contain sufficient information. 
Missing: 

- Geth version number. 
- Logs from the sync process
- Start-up arguments

All we can say is; it appears to be syncing. During sync, it will 'bump' the latest block every ~15 minutes or so, during `pivot became stale, moving`.

**Comment by rjl493456442** [comment]
Your node is still downloading state data from network and you just need to be patient for it.

**Comment by osizadmin** [comment]
Geth version number.
Geth/v1.10.25-stable-69568c55/linux-amd64/go1.18.5

Logs from the sync process
Attached. 
![eth_log](https://user-images.githubusercontent.com/52325658/192212364-0d295d16-9156-4e60-bd1c-b97a19bedac2.png)


Start-up arguments

geth --http --http.api eth,net,engine,admin

**Comment by osizadmin** [comment]
@rjl493456442 - I am waiting for this sync more than 12 hours. But we not get the result. 

If i check the eth.blockNumber it showing 0.

**Comment by osizadmin** [comment]
@holiman @rjl493456442 - Till now we are facing same issue. Let me know how to resolve this issue.

Most of my clients/users has left from us for this issue happen.

**Comment by karalabe** [comment]
There's nothing wrong, it takes a while to heal the state, depending on how fast your initial sync was. The master branch has a few optimizations to make state healing faster if you want to run that. Otherwise you just have to wait it out.

**Comment by osizadmin** [comment]
@karalabe - I have updated the master branch. 

Geth/v1.11.0-unstable-bff84a99-20220927/linux-amd64/go1.16

we are facing same issue.
