### ISSUE TITLE
Retire les downloader

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/go-ethereum#25873]
LES downloader is a duplicated copy from eth/downloader. 

The intention for having it is for simplifying the development of eth66, beacon sync and etc. Now these mechanisms are already merged and it's time to adjust LES part for reusing the existent eth/downloader component.

Note, the sync mechanism of light client is being reworked by zsolt. We should try to be compatible with the new sync algorithm.

**Comment by s1na** [comment]
@rjl493456442 are there parts of this that are not fixed by https://github.com/ethereum/go-ethereum/pull/27737?
