### ISSUE TITLE
@karalabe - I have updated the master branch.

### ISSUE THREAD

**Issue by osizadmin** [ethereum/go-ethereum#25877]
@karalabe - I have updated the master branch. 

Geth/v1.11.0-unstable-bff84a99-20220927/linux-amd64/go1.16

we are facing same issue.

_Originally posted by @osizadmin in https://github.com/ethereum/go-ethereum/issues/25866#issuecomment-1259170512_

**Comment by holiman** [comment]
Please don't spam the issue tracker

**Comment by holiman** [comment]
> There's nothing wrong, it takes a while to heal the state, depending on how fast your initial sync was. 

... 

> you just have to wait it out.

**Comment by osizadmin** [comment]
I am waiting for this more than 2 days till now its not syncing.
