### ISSUE TITLE
Wrong link to docker image in release notes

### ISSUE THREAD

**Issue by fvictorio** [ethereum/go-ethereum#25882]
Sorry for removing the template, but I think this is a no-brainer.

The release notes use https://cloud.docker.com/u/ethereum/repository/docker/ethereum/client-go as the URL for the docker image, but that page asks you to log in. I believe you want to use https://hub.docker.com/r/ethereum/client-go/ instead.

**Comment by karalabe** [comment]
Huh, good catch. Unsure how that happened. Fixed the latest release so hopefully we'll keep using the correct URL from this point onward. Will not retrospectively change the release notes for past releases though. Thank you
