### ISSUE TITLE
On moving all files to external Hard Drive, Geth won't start

### ISSUE THREAD

**Issue by Squee451** [ethereum/go-ethereum#25887]
I have a 2 TB Sandisk Extreme SSD, and I moved all of my Prysm/Geth data to stake for Ethereum. After trying to start Geth on it, pointing to it as a data dir 

--geth --datadir=F:\Ethereum --cache==1892 --http -http.api eth, net, engine, admin, --authrpc.jwtsectre ../jwt.hex

After I do that, it completely freezes and sticks here. (see image). After 10 minutes, no progress is made. On my internal drives, it syncs fine. Any ideas?

![image](https://user-images.githubusercontent.com/47549154/192882477-88183123-5cea-4df6-8a82-7f7e9bc298f0.png)

**Comment by rjl493456442** [comment]
That's all the logs? If so could you please lower the log level to debug via `--verbosity 4` for catching more info.

**Comment by Squee451** [comment]
![image](https://user-images.githubusercontent.com/47549154/193149256-5d72a43c-091c-44d3-b750-7b6cfcbaea13.png)

**Comment by rjl493456442** [comment]
hmm, it's very weird. Maybe you can dump out the routines let's see where it's stuck at.

```
geth attach /path/to/geth.ipc --exec "debug.stacks()" > stacktrace.txt
```

**Comment by Squee451** [comment]
[stacktrace.txt](https://github.com/ethereum/go-ethereum/files/9689226/stacktrace.txt)

Here it is

**Comment by Squee451** [comment]
Anyone able to chck this stacktrace and help me out, I'd love to move to my external hard drive or figure out why it's not working...

**Comment by dot3x3q** [comment]
I'm having exactly this issue as well. Searched high and low for this scenario for hours. I'd very much like some input on how to solve this problem. Geth just hangs at exactly the same point as OPs initial screenshot. No error or anything.

**Comment by holiman** [comment]
I've been looking into that stack trace -- I don't see anything strange about it, really. It looks like it is indeed performing a sync, e.g. here is a routine processing a heal response: 
```
github.com/ethereum/go-ethereum/trie.(*Sync).ProcessNode(0xc046297540, {{0xc090bcc430, 0x3}, {0xc02c272d80, 0x214, 0x214}})
	github.com/ethereum/go-ethereum/trie/sync.go:310 +0x118
github.com/ethereum/go-ethereum/eth/protocols/snap.(*Syncer).processTrienodeHealResponse(0xc0000001e0, 0xc06d918f50)
	github.com/ethereum/go-ethereum/eth/protocols/snap/sync.go:2105 +0x38c
github.com/ethereum/go-ethereum/eth/protocols/snap.(*Syncer).Sync(0xc0000001e0, {0xf6, 0xb5, 0xc6, 0x93, 0xa3, 0x70, 0x4b, 0xd9, 0x3d, ...}, ...)
	github.com/ethereum/go-ethereum/eth/protocols/snap/sync.go:684 +0xdff
github.com/ethereum/go-ethereum/eth/downloader.(*stateSync).run(0xc0548e85a0)
	github.com/ethereum/go-ethereum/eth/downloader/statesync.go:107 +0x66
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).runStateSync
	github.com/ethereum/go-ethereum/eth/downloader/statesync.go:63 +0x12a
```
As for why it doesn't output things, that's really odd. After spitting out the chain config, it should spit out something like this: 

```
INFO [10-07|08:35:20.211]  - Merge netsplit block:       <nil> 
INFO [10-07|08:35:20.211] --------------------------------------------------------------------------------------------------------------------------------------------------------- 
INFO [10-07|08:35:20.211]  
INFO [10-07|08:35:20.212] Loaded most recent local header          number=0 hash=d4e567..cb8fa3 td=17,179,869,184 age=53y6mo1w
```
I specifically looked for a goroutine stuck somewhere along that path, but nope, found nothing. Are you sure the stack trace is from the stuck process that the screenshot comes from? 


@dot3x3q same goes for you, if you want to help, please provide a stacktrace

**Comment by Squee451** [comment]
I am sure that this is the stacktrace from the process. It says that the
full block is not recent enough and hangs..... How long should I leave it
running in that way for with the stacktrace?

**Comment by karalabe** [comment]
How did you connect your external drive? What tech?

**Comment by karalabe** [comment]
Can you screenshot the entire console window for us? Just want to make sure it's not in some "select" mode.

**Comment by ligi** [comment]
Can you also make a speed-test with your SSD? E.g. if your SSD is connected to an USB2.0 port it will be too slow and could be a reason for what you see.

**Comment by Squee451** [comment]
Hi, my sandisk is connected via a USB 3.0 port. I can do so with a speed test if you want. Should I run a speed test on it and proceed from there?  Can I continue syncing the existing node on my current harddrive and start a new GETH sync from my external harddrive?

**Comment by holiman** [comment]
This ticket seems stale -- it's been a year since any action. I assume that it was resolved, and that there's nothing more we can do here at this point. Feel free to reopen if that's not the case
