### ISSUE TITLE
How to implement curl jwt auth to JSON-RPC API

### ISSUE THREAD

**Issue by jugene** [ethereum/go-ethereum#25891]
Hello, please help.

Is there any example of curl auth to JSON-RPC API with JWT Token.
How to generate Bearer Token as I have only jwt secret. How to form enquiry. I thin
We have something like that

function jwt(string $payload, $secret): string
{
  $base64UrlHeader = toBase64Url(json_encode(['typ' => 'JWT', 'alg' => 'HS256']));
  $base64UrlPayload = toBase64Url($payload);
  $signature = hash_hmac('sha256', $base64UrlHeader . "." . $base64UrlPayload, $secret, true);
  $base64UrlSignature = toBase64Url($signature);

  return $base64UrlHeader . "." . $base64UrlPayload . "." . $base64UrlSignature;
}

function toBase64Url($data)
{
  return str_replace(['+', '/', '='], ['-', '_', ''], base64_encode($data));
}

$time = time();
$data = json_encode(["jsonrpc" => "2.0", "method" => "eth_syncing", "params" => [], "id" => 1]);
$jwt = jwt($data, 'here is jwt secret');

$query = 'curl -X POST --data ' . $data . '  localhost:8551 -H "Content-Type: application/json" -H "Authorization: Bearer ' . $jwt . '"';

After query we got - invalid signature error.

**Comment by holiman** [comment]
The only thing you are supposed to sign is the claim itself, not the payload.

**Comment by jugene** [comment]
Is there any example? I tried with script, but if i do manuallym for example here http://jwtbuilder.jamiekurtz.com/
try, using JWT secret and iat parametr. Still - invalid signature

**Comment by MariusVanDerWijden** [comment]
This is how we sign with the jwt secret: https://github.com/ethereum/go-ethereum/blob/master/node/jwt_auth.go

**Comment by stoooops** [comment]
I also wanted a basic `curl` script to test JWT authentication, so I wrote one.

Submitted to the `execution-api` docs as PR https://github.com/ethereum/execution-apis/pull/371

<hr/>

You can use the following script to test Authentication:

```bash
#!/bin/bash

# This script is used to test the JWT authentication scheme.
# It takes two arguments:
# 1. The file containing the JWT secret key
# 2. The URL to send the request to
#
# Examples:
# ./jwt.sh jwt.hex http://localhost:8551
# ./jwt.sh $DATA_DIR/geth/jwtsecret http://localhost:8551

set -e -u -o pipefail

# Get the JWT secret and URL from the command line
jwtsecretfile=$1
url=$2

# Construct the JWT header
JWT_HEADER=$(echo -n '{"typ":"JWT","alg":"HS256"}' | openssl base64 -e -A | tr '+' '-' | tr '/' '_' | tr -d '=')

# Read the secret key and convert to bytes
secret=$(cat $jwtsecretfile | cut -c 3-)
secretBytes=$(printf $secret | xxd -r -p)

# Construct the JWT payload with the iat claim and encode as base64
jwt_payload=$(echo -n "{\"iat\":$(date +%s)}" | openssl base64 -e -A | tr '+' '-' | tr '/' '_' | tr -d '=')

# Create the JWT claims
jwt_claims="$JWT_HEADER.$jwt_payload"

# Create the JWT signature
jwt_signature=$(echo -n "$jwt_claims" \
    | openssl dgst -sha256 -hmac "$secretBytes" -binary \
    | openssl base64 -e -A | tr '+' '-' | tr '/' '_' | tr -d '=')

# Create the JWT
jwt="$jwt_claims.$jwt_signature"

# Make the RPC request
data='{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
curl -s \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $jwt" \
    -d "$data" \
    $url
```

Run as:

```bash
./jwt.sh jwt.hex http://localhost:8551
```

where `jwt.hex` is the file containing the secret key. (e.g. $DATA_DIR/geth/jwtsecret)
