### ISSUE TITLE
Geth on CentOS/RedHat 6

### ISSUE THREAD

**Issue by wawrzek** [ethereum/go-ethereum#2590]
Geth doesn't work on CentOS/RedHat 6, because GLIBC is too old (2.12 vs. 2.14 require by geth). RedHat 6 is still in use in many potential enterprise adopters of a block chain.

ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

./geth
./geth: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./geth)

**Comment by karalabe** [comment]
I don't think we aim to build binaries ourselves to older platforms, however it should be pretty straightforward to build geth for it:

```
git clone https://github.com/ethereum/go-ethereum.git
cd go-ethereum
make geth
```

**Comment by wawrzek** [comment]
@karalabe that actually much easier than what I found on developers and it works.

**Comment by wawrzek** [comment]
One more question @karalabe - how do you tag release? - To make sure that build is equal current binary build.

**Comment by karalabe** [comment]
Not really sure I understand the question. `make geth` will embed the commit hash into the binary, and the version number is included as hard coded values in the source code.

**Comment by wawrzek** [comment]
I guess I want 'git reset --hard v1.4.4'

**Comment by jewes** [comment]
@wawrzek you may want to install glibc 2.14 on your machine, try this: https://stackoverflow.com/questions/35616650/how-to-upgrade-glibc-from-version-2-12-to-2-14-on-centos
