### ISSUE TITLE
Can't mine transaction in a private Ethereum network by Geth!

### ISSUE THREAD

**Issue by Alireza1994x** [ethereum/go-ethereum#25916]
There are two separated PCs on a private network and There is a Geth client on each PC, One for sending transactions (I call it Sender Geth), The other is for mining (I call it Miner Geth). The both operating system are Windows Server 2019. I have configed a private Ethereum network by these two nodes via Geth. Currently there is just one miner and the consensus is PoA. These two PCs are connected together and we can see that by Telnet. The communication protocol between these two Geths is Websocket based.

I run the Miner Geth via PowerShell by this command:

`geth --datadir <...> --identity "PrivateEthereum" --networkid <id1> --port <port1> --netrestrict <NetworkID/SubnetMask> --nat extip:<Miner PC IP> --ws --allow-insecure-unlock --ws.addr <Miner PC IP> --ws.port <port1> --ws.api eth,net,web3,personal,admin,miner --ws.origins "*" --mine --miner.threads 10`

And run the other by:

`geth --datadir <...> --identity "PrivateEthereum" --networkid <id1> --port <port2> --netrestrict <NetworkID/SubnetMask> --nat extip:<Sender PC IP> --ws --allow-insecure-unlock --ws.port <port2> --ws.addr <Sender PC IP> --ws.api eth,net,web3,personal,admin --ws.origins '*'`

The issue is this: Whenever I try send a transaction by Geth JavaScript console of Sender Geth, if:

Miner Geth is run on the other PC, No transaction and block mined and the sender Geth doesn't show nothing as result and when I stop Miner Geth, The expected transaction hash emerges on Sender Geth but not mined.

Miner Geth is not run on the other PC and I run the Sender Geth as miner, by the command mentioned above for Miner Geth, and send a transaction by Geth JavaScript console, The transaction and a new block is mined.

It seems if Miner Geth run on the sender PC there is no problem but if it run on another PC there is problem. Maybe they can't find each other despite they are in a network.

What is the problem? What is its solution? What is neglected that I forgot it? What should I do?

The config file (Genesis file):

{

     "config":{

        "chainId":1111,

        "homesteadBlock":0,

        "eip158Block":0,

        "eip155Block":0,

        "eip150Block":0,

        "byzantiumBlock":0,

        "constantinopleBlock":0,

        "petersburgBlock":0,

        "istanbulBlock":0,

        "berlinBlock":0,

        "londonBlock":0,

        "eip5133Block":0,
        "clique": {
                        "period": 5,
                "epoch": 30000
          }

    },

    "difficulty":"0x12c",

    "gasLimit":"0x6691b7",

    "extradata":"0x0000000000000000000000000000000000000000000000000000000000000000316714b85045dc3B4D4fFEDeba1B936D6f8a47fB0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",

    "alloc":{
    "0x316714b85045dc3B4D4fFEDeba1B936D6f8a47fB":{"balance":"90000000000000000000"},
    "0x62413091936Ada474999fB24816e394CFB648C27":{"balance":"40000000000000000000"}
    }

}
The first account is miner (Miner Geth) and the second account sends transactions (Sender Geth).

**Comment by Jezz12-cloud** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue
https://direct.lc.chat/14571264/

**Comment by karalabe** [comment]
Most probably they are not connected. Geth uses public bootnodes to search for peers, but they won't index internal IPs. Yo ueither need to set up your own bootnode, or perhaps specify one as the bootnode of the other on the CLI, or use `admin.addPeer`.
