### ISSUE TITLE
miner.hashrate undefined

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/go-ethereum#2591]
https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#minerhashrate

Looks like its moved to web3.eth.hashrate on geth 1.4.3

**Comment by bas-vk** [comment]
This was removed since it was a duplicate of `eth.hashrate` which is part of the official API.
This for reporting this, page has been updated.

**Comment by advectus** [comment]
@bas-vk @aakilfernandes I've updated the master branch of a new go-ethereum-wiki repo that I've created where there was mention of this deprecated miner.hashrate property. Maybe go-ethereum deserves it's own wiki repo - or if these doc contributions are handled another way, please let me know.

**Comment by roolo** [comment]
It is still here https://github.com/ethereum/go-ethereum/wiki/Mining
