### ISSUE TITLE
how to generate ketstore by giving hexPrivateKey in golang-code

### ISSUE THREAD

**Issue by wonderfulLand** [ethereum/go-ethereum#25925]
how to generate ketstore by giving hexPrivateKey in golang-code,  are you anyone know?

**Comment by karalabe** [comment]
https://pkg.go.dev/github.com/ethereum/go-ethereum@v1.10.25/accounts/keystore#KeyStore.ImportECDSA

**Comment by wonderfulLand** [comment]
> https://pkg.go.dev/github.com/ethereum/go-ethereum@v1.10.25/accounts/keystore#KeyStore.ImportECDSA

Your answer is from ecdsaPriKey generate keyStore.      
 Are you know，how generate keyStore from hexPrivateKeyString ?
thanks!!!
