### ISSUE TITLE
Testing finalization in a proof-of-stake local net

### ISSUE THREAD

**Issue by AaronKutch** [ethereum/go-ethereum#25935]
We have a bridge that uses RPC calls to `geth`, and we need to make absolutely sure that reorgs do not happen. We previously used `eth_getBlockByNumber` with `latest` plus 35 blocks, but after the merge it appears we should use `eth_getBlockByNumber` with `finalized` to be conservative. Our local tests currently initialize a genesis with "londonBlock" being the latest fork and `geth --nodiscover --mine ...` to start a local net that immediately seals blocks.

After looking at the source code, it appears I should want this in my genesis configuration:
```
      "homesteadBlock": 0,
      "eip150Block": 0,
      "eip155Block": 0,
      "eip158Block": 0,
      "byzantiumBlock": 0,
      "constantinopleBlock": 0,
      "petersburgBlock": 0,
      "istanbulBlock": 0,
      "muirGlacierBlock": 0,
      "berlinBlock": 0,
      "londonBlock": 0,
      "arrowGlacierBlock": 0,
      "grayGlacierBlock": 0,
      "terminalTotalDifficulty": 0, // note all three of these are required for the logs to show a successful merged state at genesis
      "terminalTotalDifficultyPassed": true,
      "mergeNetsplitBlock": 0,
```
When only making changes to include the forks up to the merge, the tests break by `geth` responding with transaction ids after 15 seconds as normal, but it does not create any new blocks. Querying with `finalized` always results in `null` with or without the changes.

I realized today that maybe we have been doing the local tests wrong and that the local instant sealing is happening simply because the node has no competition, and we should have used the `--dev` flag. However, `--dev` doesn't work for us because it seems to override the genesis and force pre-merge PoW behavior.

As an additional note, we do not want to wait for the standard 15 second block and 32 block epochs in local testing, so either there needs to be a PoS equivalent to the current `--mine` or `--dev` behavior that does immediate justification and finalization of blocks, or some way of customizing the periods.

**Comment by garyng2000** [comment]
yes, there needs to be a way to continue develop using private network yet have the 'ability' of the post-merge work, without the CL.

**Comment by holiman** [comment]
Two things: 

> geth --nodiscover --mine ... to start a local net that immediately seals blocks.

and

```
      "terminalTotalDifficulty": 0, // note all three of these are required for the logs to show a successful merged state at genesis
      "terminalTotalDifficultyPassed": true,
      "mergeNetsplitBlock": 0,
```
Are conflicting. On one hand, you're telling geth to mine, as if it's a regular clique/ethash network. On the other hand, you're telling geth that the TTD is passed - therefore the CL should direct things like block creation and validation. 

You need to decide either on keeping the old ways, or doing it in post-merge style, with an attendant CL infrastructure. 


> yes, there needs to be a way to continue develop using private network yet have the 'ability' of the post-merge work, without the CL.

That's simple, just don't configure the merge on the private network.

**Comment by garyng2000** [comment]
that is what I am doing for my private network. But let's say if there is another upgrade in the future where the feature changed, I can't keep on using 'pre-merge' setup, unless each individual upgrade is independent.

**Comment by holiman** [comment]
Right.. We maintain geth as an ethereum mainnet client. This means that we are happy to support non-ethereum-mainnet usecases  as best we can, but not if the cost of maintenance is too high. 

So yes, at some point, it may be the case that geth will either not support non-merged network, OR, as you point out, that geth does support non-merged networks, but does not support post-merge forks on such networks. 

I'm not saying that's a given, though, but I agree there's a chance it might happen. So, hope for the best but prepare for the worst, I guess :)

**Comment by garyng2000** [comment]
actually, the broader question is how one can setup a private network of both CL and EL. Testing/developing on testnets is extremely inefficient (getting the test ETH itself is difficult).

**Comment by holiman** [comment]
> actually, the broader question is how one can setup a private network of both CL and EL.

Right, I totally agree! And there have been some discussions about that, for example (IIUC) building a clique-based "CL client" which basically is a virtual CL inside of geth that directs geth via the beacon api endpoints (catalyst). 

We definitely need more tooling here. cc @protolambda @fjl  who have been part of the discussions

**Comment by AaronKutch** [comment]
> Are conflicting. On one hand, you're telling geth to mine, as if it's a regular clique/ethash network. On the other hand, you're telling geth that the TTD is passed - therefore the CL should direct things like block creation and validation.

Yes, I know that this is a conflict. I am just showing you how I used to set up tests. The point of this issue is that I can't find a way to do likewise quick tests with post-merge behavior. In most cases post-merge changes nothing about developer workflows, but the safety of our bridge is intimately connected with the finalization process. It seems the 'finalized' and 'safe' options are null until post merge.

**Comment by AaronKutch** [comment]
Most other Eth-compatible projects I have messed with have a very customizable '--dev' option, but geths current '--dev' just overrides the genesis with PoW-only assumptions. I think what I want is a third proof-of-stake option in the genesis besides the ethhash and clique options that allows me to customize the epochs, and some kind of '--dev-pos' flag that allows a single node network and does not override the genesis
