### ISSUE TITLE
synchronization problem 

### ISSUE THREAD

**Issue by electroneum57800** [ethereum/go-ethereum#25940]
Hello I have a problem with the synchronization of my node it puts me  Syncing: state healing in progress while it returns me the synced to 100%.

**Comment by electroneum57800** [comment]
I forgot to mention that I'm running on ubuntu 20.04 with geth 1.11.0

**Comment by electroneum57800** [comment]
logs 

`Oct 06 13:40:37 eth2 geth[43896]: INFO [10-06|13:40:37.507] Forkchoice requested sync to new head    number=15,688,823 hash=e6feee..000806
Oct 06 13:40:37 eth2 geth[43896]: WARN [10-06|13:40:37.986] Snapshot extension registration failed   peer=2df6ffae err="peer connected on snap without compatible eth support"
Oct 06 13:40:38 eth2 geth[43896]: INFO [10-06|13:40:38.945] Syncing: state healing in progress       accounts=6657@314.89KiB slots=4512@369.03KiB codes=15@103.87KiB nodes=62030@18.75MiB pending=30822
Oct 06 13:40:47 eth2 geth[43896]: INFO [10-06|13:40:47.067] Syncing: state healing in progress       accounts=6657@314.89KiB slots=4512@369.03KiB codes=15@103.87KiB nodes=62376@18.91MiB pending=33065
Oct 06 13:40:50 eth2 geth[43896]: INFO [10-06|13:40:50.614] Forkchoice requested sync to new head    number=15,688,824 hash=0b63b1..33f909
Oct 06 13:40:51 eth2 geth[43896]: INFO [10-06|13:40:51.846] Imported new block headers               count=1    elapsed="812.581µs" number=15,688,824 hash=0b63b1..33f909
Oct 06 13:40:52 eth2 geth[43896]: INFO [10-06|13:40:52.522] Downloader queue stats                   receiptTasks=0    blockTasks=0    itemSize=258.33KiB throttle=1015
Oct 06 13:40:56 eth2 geth[43896]: INFO [10-06|13:40:56.813] Syncing: state healing in progress       accounts=6660@315.01KiB slots=4512@369.03KiB codes=15@103.87KiB nodes=62734@19.07MiB pending=35467
Oct 06 13:41:00 eth2 geth[43896]: INFO [10-06|13:41:00.848] Imported new block headers               count=1    elapsed="951.282µs" number=15,688,825 hash=7e7b97..519c27
Oct 06 13:41:02 eth2 geth[43896]: INFO [10-06|13:41:02.283] Forkchoice requested sync to new head    number=15,688,825 hash=7e7b97..519c27
Oct 06 13:41:03 eth2 geth[43896]: WARN [10-06|13:41:03.110] Snapshot extension registration failed   peer=ad50fca5 err="peer connected on snap without compatible eth support"
Oct 06 13:41:04 eth2 geth[43896]: INFO [10-06|13:41:04.919] Syncing: state healing in progress       accounts=6679@315.89KiB slots=4512@369.03KiB codes=15@103.87KiB nodes=63004@19.18MiB pending=36632
Oct 06 13:41:12 eth2 geth[43896]: INFO [10-06|13:41:12.874] Imported new block headers               count=1    elapsed=24.044ms    number=15,688,826 hash=4dc59f..d040bf
Oct 06 13:41:13 eth2 geth[43896]: INFO [10-06|13:41:13.666] Syncing: state healing in progress       accounts=6696@316.62KiB slots=4512@369.03KiB codes=15@103.87KiB nodes=63159@19.23MiB pending=37002
Oct 06 13:41:22 eth2 geth[43896]: INFO [10-06|13:41:22.091] Syncing: state healing in progress       accounts=6723@317.83KiB slots=4512@369.03KiB codes=15@103.87KiB nodes=63390@19.32MiB pending=37774
Oct 06 13:41:26 eth2 geth[43896]: INFO [10-06|13:41:26.483] Forkchoice requested sync to new head    number=15,688,826 hash=4dc59f..d040bf
Oct 06 13:41:30 eth2 geth[43896]: INFO [10-06|13:41:30.235] Syncing: state healing in progress       accounts=6763@319.71KiB slots=4512@369.03KiB codes=15@103.87KiB nodes=63720@19.44MiB pending=38674
Oct 06 13:41:33 eth2 geth[43896]: WARN [10-06|13:41:33.886] Unexpected trienode heal packet          peer=22139e66 reqid=8,632,958,523,983,666,637
Oct 06 13:41:35 eth2 geth[43896]: WARN [10-06|13:41:35.881] Unexpected trienode heal packet          peer=cd3fc0ad reqid=8,499,672,213,794,161,259
Oct 06 13:41:38 eth2 geth[43896]: INFO [10-06|13:41:38.786] Syncing: state healing in progress       accounts=6838@323.02KiB slots=4512@369.03KiB codes=15@103.87KiB nodes=64152@19.58MiB pending=40003
Oct 06 13:41:41 eth2 geth[43896]: WARN [10-06|13:41:41.286] Snapshot extension registration failed   peer=d5a6c885 err="peer connected on snap without compatible eth support"
Oct 06 13:41:43 eth2 geth[43896]: WARN [10-06|13:41:43.681] Snapshot extension registration failed   peer=1d4ddff1 err="peer connected on snap without compatible eth support"
Oct 06 13:41:49 eth2 geth[43896]: INFO [10-06|13:41:49.862] Syncing: state healing in progress       accounts=6864@324.20KiB slots=4512@369.03KiB codes=15@103.87KiB nodes=64346@19.65MiB pending=40453
Oct 06 13:41:55 eth2 geth[43896]: WARN [10-06|13:41:55.336] Dropping unsynced node during sync       id=07854508dcea0ee1 conn=inbound addr=91.150.101.29:57526               type=erigon/v2022.10.1-de...
Oct 06 13:41:57 eth2 geth[43896]: INFO [10-06|13:41:57.865] Syncing: state healing in progress       accounts=6886@325.22KiB slots=4512@369.03KiB codes=15@103.87KiB nodes=64466@19.69MiB pending=40608
Oct 06 13:41:58 eth2 geth[43896]: WARN [10-06|13:41:58.646] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
Oct 06 13:42:07 eth2 geth[43896]: INFO [10-06|13:42:07.126] Syncing: state healing in progress       accounts=6914@326.58KiB slots=4512@369.03KiB codes=15@103.87KiB nodes=64682@19.76MiB pending=40942
Oct 06 13:42:15 eth2 geth[43896]: INFO [10-06|13:42:15.138] Syncing: state healing in progress       accounts=6949@328.21KiB slots=4512@369.03KiB codes=15@103.87KiB nodes=64912@19.85MiB pending=41340
Oct 06 13:42:21 eth2 geth[43896]: WARN [10-06|13:42:21.341] Unexpected trienode heal packet          peer=22139e66 reqid=6,223,270,059,214,419,931
Oct 06 13:42:23 eth2 geth[43896]: INFO [10-06|13:42:23.315] Syncing: state healing in progress       accounts=7020@331.49KiB slots=4512@369.03KiB codes=15@103.87KiB nodes=65213@19.95MiB pending=41751
Oct 06 13:42:31 eth2 geth[43896]: INFO [10-06|13:42:31.374] Syncing: state healing in progress       accounts=7077@334.14KiB slots=4513@369.11KiB codes=15@103.87KiB nodes=65523@20.03MiB pending=41851
Oct 06 13:42:39 eth2 geth[43896]: INFO [10-06|13:42:39.738] Syncing: state healing in progress       accounts=7133@336.84KiB slots=4514@369.20KiB codes=15@103.87KiB nodes=65803@20.11MiB pending=42010
Oct 06 13:42:48 eth2 geth[43896]: INFO [10-06|13:42:48.272] Syncing: state healing in progress       accounts=7274@343.88KiB slots=4517@369.46KiB codes=15@103.87KiB nodes=66227@20.19MiB pending=41944
Oct 06 13:42:57 eth2 geth[43896]: INFO [10-06|13:42:57.062] Syncing: state healing in progress       accounts=7355@347.74KiB slots=4520@369.68KiB codes=15@103.87KiB nodes=66560@20.27MiB pending=42107
Oct 06 13:43:05 eth2 geth[43896]: INFO [10-06|13:43:05.120] Syncing: state healing in progress       accounts=7423@351.22KiB slots=4523@369.93KiB codes=15@103.87KiB nodes=66870@20.36MiB pending=42505
Oct 06 13:43:13 eth2 geth[43896]: INFO [10-06|13:43:13.184] Syncing: state healing in progress       accounts=7496@354.68KiB slots=4524@369.99KiB codes=15@103.87KiB nodes=67158@20.45MiB pending=42721
Oct 06 13:43:21 eth2 geth[43896]: INFO [10-06|13:43:21.580] Syncing: state healing in progress       accounts=7552@357.20KiB slots=4530@370.47KiB codes=15@103.87KiB nodes=67347@20.50MiB pending=42750
Oct 06 13:43:30 eth2 geth[43896]: INFO [10-06|13:43:30.024] Syncing: state healing in progress       accounts=7613@360.16KiB slots=4534@370.80KiB codes=15@103.87KiB nodes=67575@20.56MiB pending=42830
Oct 06 13:43:41 eth2 geth[43896]: INFO [10-06|13:43:41.561] Syncing: state healing in progress       accounts=7685@363.46KiB slots=4538@371.10KiB codes=15@103.87KiB nodes=67854@20.63MiB pending=42866
Oct 06 13:43:46 eth2 geth[43896]: WARN [10-06|13:43:46.031] Unexpected bytecode heal packet          peer=19e50d20 reqid=3,915,860,588,657,533,581
Oct 06 13:43:46 eth2 geth[43896]: WARN [10-06|13:43:46.257] Snapshot extension registration failed   peer=1d4ddff1 err="peer connected on snap without compatible eth support"
Oct 06 13:43:51 eth2 geth[43896]: WARN [10-06|13:43:51.723] Snapshot extension registration failed   peer=04dfa983 err="peer connected on snap without compatible eth support"
Oct 06 13:43:52 eth2 geth[43896]: INFO [10-06|13:43:52.204] Syncing: state healing in progress       accounts=7731@365.73KiB slots=4546@371.81KiB codes=15@103.87KiB nodes=68078@20.69MiB pending=42907
Oct 06 13:43:56 eth2 geth[43896]: WARN [10-06|13:43:56.573] Unexpected bytecode heal packet          peer=d2c99d8e reqid=2,560,263,480,639,527,602
Oct 06 13:43:57 eth2 geth[43896]: WARN [10-06|13:43:57.613] Dropping unsynced node during sync       id=cba6a7dcaa653650 conn=inbound addr=34.106.232.46:38038               type=Geth/vv1.10.17-stabl...
Oct 06 13:44:00 eth2 geth[43896]: INFO [10-06|13:44:00.694] Syncing: state healing in progress       accounts=7776@367.81KiB slots=4548@371.98KiB codes=15@103.87KiB nodes=68287@20.75MiB pending=43078
Oct 06 13:44:09 eth2 geth[43896]: INFO [10-06|13:44:09.247] Syncing: state healing in progress       accounts=7838@370.78KiB slots=4553@372.42KiB codes=17@120.51KiB nodes=68520@20.81MiB pending=43112
Oct 06 13:44:17 eth2 geth[43896]: INFO [10-06|13:44:17.637] Syncing: state healing in progress       accounts=7934@375.49KiB slots=4562@373.18KiB codes=17@120.51KiB nodes=68817@20.89MiB pending=43051
Oct 06 13:44:21 eth2 geth[43896]: WARN [10-06|13:44:21.477] Unexpected trienode heal packet          peer=22139e66 reqid=3,549,825,333,891,434,259
Oct 06 13:44:23 eth2 geth[43896]: WARN [10-06|13:44:23.829] Unexpected trienode heal packet          peer=c76e7cf8 reqid=1,183,132,388,101,573,162
Oct 06 13:44:24 eth2 geth[43896]: WARN [10-06|13:44:24.877] Snapshot extension registration failed   peer=685a4d4f err="peer connected on snap without compatible eth support"
Oct 06 13:44:25 eth2 geth[43896]: INFO [10-06|13:44:25.647] Syncing: state healing in progress       accounts=8016@379.46KiB slots=4567@373.61KiB codes=17@120.51KiB nodes=69130@20.96MiB pending=43127
Oct 06 13:44:27 eth2 geth[43896]: WARN [10-06|13:44:27.091] Checkpoint challenge timed out, dropping id=fc936edcc17456d2 conn=inbound addr=95.217.38.104:50303               type=Geth/v1.1.1
Oct 06 13:44:27 eth2 geth[43896]: WARN [10-06|13:44:27.287] Snapshot extension registration failed   peer=35ba3061 err="peer connected on snap without compatible eth support"
Oct 06 13:44:34 eth2 geth[43896]: INFO [10-06|13:44:34.408] Syncing: state healing in progress       accounts=8093@383.24KiB slots=4570@373.84KiB codes=17@120.51KiB nodes=69503@21.08MiB pending=43493
Oct 06 13:44:42 eth2 geth[43896]: INFO [10-06|13:44:42.562] Syncing: state healing in progress       accounts=8148@385.72KiB slots=4575@374.21KiB codes=17@120.51KiB nodes=69835@21.19MiB pending=44033
Oct 06 13:44:50 eth2 geth[43896]: INFO [10-06|13:44:50.771] Syncing: state healing in progress       accounts=8181@387.23KiB slots=4584@374.90KiB codes=17@120.51KiB nodes=70005@21.24MiB pending=44228
Oct 06 13:44:53 eth2 geth[43896]: WARN [10-06|13:44:53.767] Unexpected bytecode heal packet          peer=ee6ccb2f reqid=7,737,525,279,977,707,866
Oct 06 13:44:55 eth2 geth[43896]: WARN [10-06|13:44:55.818] Snapshot extension registration failed   peer=3fef0e1f err="peer connected on snap without compatible eth support"
Oct 06 13:44:59 eth2 geth[43896]: INFO [10-06|13:44:59.223] Syncing: state healing in progress       accounts=8211@388.69KiB slots=4596@375.89KiB codes=17@120.51KiB nodes=70189@21.30MiB pending=44417
Oct 06 13:45:06 eth2 geth[43896]: WARN [10-06|13:45:06.017] Snapshot extension registration failed   peer=a05e766c err="peer connected on snap without compatible eth support"
Oct 06 13:45:08 eth2 geth[43896]: INFO [10-06|13:45:08.677] Syncing: state healing in progress       accounts=8372@396.48KiB slots=4609@376.85KiB codes=19@148.48KiB nodes=70639@21.42MiB pending=44564`

**Comment by holiman** [comment]
```
INFO [10-06|13:45:08.677] Syncing: state healing in progress       accounts=8372@396.48KiB slots=4609@376.85KiB codes=19@148.48KiB nodes=70639@21.42MiB pending=44564
```
It is syncing -- it has managed to sync only 70K nodes, totalling 21Mb. This is a very low figure, usually somewhere in the millions are needed to finish the heal-phase. 

Where does it say `synced to 100%` ? How long was it since you started the geth process?

**Comment by electroneum57800** [comment]
I've just checked the value of nodes is slowly increasing I'm currently at 126K

**Comment by holiman** [comment]
`age=1m8s` --this means that the block header it just imported is `1m8s` old. That doesn't mean that the sync is 'done', only that it just moved the so called "pivot block" ahead to a very recent block. 

Can you provide a log where it says something about `100%`?
How long was it since you started the geth process?

**Comment by electroneum57800** [comment]
Oct 06 12:58:51 eth2 geth[5017]: INFO [10-06|12:58:51.372] Syncing: state download in progress      synced=100.00% state=208.12GiB accounts=190,842,054@42.28GiB slots=808,518,456@161.60GiB codes=690,193@4.23GiB    eta=-2m13.607s

**Comment by electroneum57800** [comment]
I restarted for the last time the service Oct 06 13:09:10 eth2 geth[43896]: INFO [10-06|13:09:10.503] Block synchronisation started

**Comment by holiman** [comment]
Ah, ok. 
So, the logs are a bit confusing. See https://geth.ethereum.org/docs/interface/sync-modes 
It's kind of :

1.    download and verify headers
2.a   download block bodies and receipts.
2.b  In parallel, download raw state data and build state trie
3 .   heal state trie to account for newly arriving data


The `Syncing: state download in progress` is `2.b`, it reached 100% at `12:58`. So that phase is done. 

After that, it commenced with `Syncing: state healing` (which is `3`). It is progressing nicely, give it some hours, sometimes up to 12 hours of healing. Just let it be. 

If you need to provide more logs in the future, use triple-backticks to style a chunk of text.

**Comment by holiman** [comment]
Feel free to reopen if it doesn't work out

**Comment by electroneum57800** [comment]
ok thanks I'll see an update tomorrow morning and keep you informed

**Comment by electroneum57800** [comment]
hello little point on the situation the node is currently at nodes=2,255,712 would it be possible to accelerate this step I have another node that works as needed
