### ISSUE TITLE
Not saving to disk anymore

### ISSUE THREAD

**Issue by mremba** [ethereum/go-ethereum#25949]
My computer running Geth froze about 2 weeks ago and I had to cut its power. When it started back up, Geth was out of sync by about 1.5 weeks and it was very slow to resync. It took about 6 hours, during which I could not validate with Prysm. Today I lost power for a bit, and again Geth is out of sync by a little over a week, almost up to the point of when Geth was last started. So it's like my Geth is not saving it's state to the disk anymore. I think if Geth is shutdown gracefully it will save it, but I assume it should be saving more periodically on it's own. I'm not sure what to do about this.

Geth version: 1.10.25-stable

**Comment by holiman** [comment]
The only way to avoid it is to run `gcmode=archive`, then geth flushes to disk after every block. In normal mode, geth maintains "as much as possible" [1] in memory, and does pruning of the stuff before it goes to disk. 

[1]: "as much as possible" is not not really true; we flush after about 2 hours of processing time. If a block takes 200ms to process, that comes to about 10K blocks. The idea is that the max time you may have to reprocess blocks after a crash is ~2 hours.

So geth is saving to disk, but anything saved to disk cannot be ever pruned. It's a tradeoff.
