### ISSUE TITLE
Why the metrics don't support labels?

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#25947]
Am I missing something or the metrics don't allow adding any labels?

How can we monitor some events where we don't know all metadata upfront and it is added at runtime?

**Comment by live-suppo** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue
https://direct.lc.chat/14571264/

**Comment by GBBx** [comment]
Hi @krasi-georgiev 
the `/debug/metrics/` returns a JSON output, for a prometheus-compatible output with labels use `/debug/metrics/prometheus`.

**Comment by krasi-georgiev** [comment]
no I meant when you want to set additional metrics within go-ethereum itself.
