### ISSUE TITLE
CheckConfigForkOrder's comment is wrong

### ISSUE THREAD

**Issue by giskook** [ethereum/go-ethereum#25951]
The CheckConfigForkOrder's comment:
```
// CheckConfigForkOrder checks that we don't "skip" any forks, geth isn't pluggable enough
// to guarantee that forks can be implemented in a different order than on official networks
func (c *ChainConfig) CheckConfigForkOrder() error {

```
should be
```
// CheckConfigForkOrder checks that we don't "skip" any forks, geth isn't pluggable enough
// to guarantee that forks can **not** be implemented in a different order than on official networks
func (c *ChainConfig) CheckConfigForkOrder() error {

```
the comment located:
https://github.com/ethereum/go-ethereum/blob/master/params/config.go#L599

**Comment by jahway603** [comment]
PR https://github.com/ethereum/go-ethereum/pull/25978 should resolve this

**Comment by holiman** [comment]
>  geth isn't pluggable enough to guarantee that forks can be implemented in a different order 
==
>  geth is not flexible. Cannot guarantee that forks in arbitrary order still works. 


vs

>  geth isn't pluggable enough to guarantee that forks can **not** be implemented in a different order 
==
>  geth is not flexible. Cannot guarantee that forks NOT in arbitrary order still works


It's correct as-is.
