### ISSUE TITLE
synchronization problem "Syncing: state healing in progress"

### ISSUE THREAD

**Issue by electroneum57800** [ethereum/go-ethereum#25959]
hello my node is now synchronized since 72h and I am currently at 

`Oct 10 09:27:21 eth2 geth[43896]: INFO [10-10|09:27:21.825] Syncing: state healing in progress       accounts=2,246,237@112.08MiB slots=5,715,542@412.07MiB codes=3239@23.46MiB  nodes=26,437,771@6.58GiB   pending=53972`

I can do what I can to hope one day to synchronize

**Comment by electroneum57800** [comment]
iostat -d -x -m 5


Device            r/s     rMB/s   rrqm/s  %rrqm r_await rareq-sz     w/s     wMB/s   wrqm/s  %wrqm w_await wareq-sz     d/s     dMB/s   drqm/s  %drqm d_await dareq-sz     f/s f_await  aqu-sz  %util
loop0            0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.00   0.00
sda            577.80      5.47    11.00   1.87    2.75     9.69   18.20      3.63     9.00  33.09    3.11   204.22    0.00      0.00     0.00   0.00    0.00     0.00    1.20    2.50    1.65  98.88

**Comment by holiman** [comment]
If I'm reading it right, you have disk _read_ at `5.47 MB/s`, and write at `3.63 MB/s`. Those speeds are comparable to if your disk is attached via usb 1.1. Which is to say, that is a very slow disk. If it is an SSD, it's extremely deteriorated -- SSDs tend to do that over time. 

I don't think you will ever complete a sync on that disk. 

You could also try this, to get a "second opinion" on the write-speed. :
```
dd if=/dev/zero of=./tmp_output conv=fdatasync bs=384k count=1k; rm ./tmp_output
```

**Comment by electroneum57800** [comment]
` dd if=/dev/zero of=./tmp_output conv=fdatasync bs=384k count=1k; rm ./tmp_output
1024+0 records in
1024+0 records out
402653184 bytes (403 MB, 384 MiB) copied, 16.9534 s, 23.8 MB/s`

**Comment by holiman** [comment]
That's a _bit_ better -but still pretty bad. It managed to write at 23.8 MB/s, which is still comparable to a usb-attached external drive. What type of disk are you using?

**Comment by electroneum57800** [comment]
normally after the supplier it is a disk 1 tb in hdd

**Comment by holiman** [comment]
I see. Well, for quite some time now, syncing on an hdd has been "basically not supported'" - the disk speed required to perform a sync won't be reached on an hdd. You need a faster disk, I'd recommend and NVMe ssd disk. You can use an hdd tor `--ancientdir`, i.e. where geth stores some of the not-so-hot data, which is somehwere around 400GB which doesn't need to sit on the 'fast' disk. 

The model says `QEMU HARDDISK` - which sounds to me like it's a virtual emulated disk ? Meaning, hard to say what's the actual backing storage. 

But doesn't really matter -- it's not sufficient. Not much more to investigate here, I'll close this.
