### ISSUE TITLE
eth_submitWork returns false on valid work item

### ISSUE THREAD

**Issue by ppratscher** [ethereum/go-ethereum#2596]
#### System information

Geth version: v1.4.4-stable-94ad694a
OS & Version: Linux
Commit hash : (if `develop`)

During mining sometimes geth return false when submitting work via eth_submitWork. The geth log does not print the submitted work at all, neither "Block xxx mined" nor "Work was submitted for xxx but no pending work found" can be seen in the log output. The work solution is simply discarded by geth without any reason.

**Comment by ppratscher** [comment]
This issue does not occur on v1.3.6 (just tested for 12 hours).

**Comment by karalabe** [comment]
@bas-vk Could you take a look at this if you have the time?

**Comment by ppratscher** [comment]
On v1.3.6 I see a similar behavior only that eth_submitWork returns true but geth prints the following error message:
```
I0524 11:55:31.340694    4523 worker.go:295] Invalid header on mined block: nonce for #1575385 [ccf92232eda42498f57bb07ad9aebfc2e40712ed491059721a118fbe61295cf8…] is invalid (got 13364320432927586209)
```

This is the corresponding work package submitted to geth:
```
HashNoNonce: 0x3e984873aa2644807751a0a0152cccac2f362a71f7208fd75815d66c667d81ac
MixHash: 0x6a0200867b25d65afb97951668cab214a5c91afe089a59f1c7ee32fd5b7bfedc
SeedHash: 0xcad4f4a99ad327de63b019b0116d93d299bf8ab65cdb0f56a94b9532d1c460ae
Nonce: 0x07847af45d2e9c73
Block difficulty: 0x25897c28c791
```

According to ethminer this solution is valid:
```
ethminer -w 0x3e984873aa2644807751a0a0152cccac2f362a71f7208fd75815d66c667d81ac 0xcad4f4a99ad327de63b019b0116d93d299bf8ab65cdb0f56a94b9532d1c460ae 0x25897c28c791 0x07847af45d2e9c73
VALID :-)
00000000000587a6ef65abb11af7198b9041394affe51ba83ab15e0641f19312 < 000000000006d1e6d47f06e61315e2d17fa5b43784f6e34a810e8e15674a5419
  where 000000000006d1e6d47f06e61315e2d17fa5b43784f6e34a810e8e15674a5419 = 2^256 / 41272423794577
  and 00000000000587a6ef65abb11af7198b9041394affe51ba83ab15e0641f19312 = ethash(3e984873aa2644807751a0a0152cccac2f362a71f7208fd75815d66c667d81ac, 07847af45d2e9c73)
  with seed as cad4f4a99ad327de63b019b0116d93d299bf8ab65cdb0f56a94b9532d1c460ae
(mixHash = 6a0200867b25d65afb97951668cab214a5c91afe089a59f1c7ee32fd5b7bfedc)
SHA3( light(seed) ) = 35ded12eecf2ce2e8da2e15c06d463aae9b84cb2530a00b932e4bbc484cde353
```

**Comment by bas-vk** [comment]
@karalabe will take a look at it.

**Comment by ppratscher** [comment]
I did some more digging:
eth_submitWork returns occasionally false on both http and ipc RPC requests

I added some trace output at the beginning of [api.go#L203](https://github.com/ethereum/go-ethereum/blob/master/eth/api.go#L203). When the issue happens the function is not called at all! I assume the problem is somewhere in the RPC implementation itself.

**Comment by bas-vk** [comment]
Could you run geth with the following options `geth --vmodule rpc=6,eth=6`, capture the log and post it when you encounter this problem?

**Comment by ppratscher** [comment]
Sorry for the troubles, found the issue on my end of the table ;)
