### ISSUE TITLE
Documentation for upgrading geth full node to see beacon chain - where is it?

### ISSUE THREAD

**Issue by woodydeck** [ethereum/go-ethereum#25976]
There is currently no acceptable documentation on geth or in the five different beacon clients. https://geth.ethereum.org/docs/interface/consensus-clients is completely useless besides shipping you to various poorly documented projects without answers to much of anything.

All I need to do is start syncing the post-merge chain so I can make the complex web3 queries my data products depend on. Why is this so hard?

I fully synced my full node on an external drive. I just want to ideally run one client that references past chain data. Nobody has explained if this will be possible, or if it is now. I've been through thousands of videos and articles relating to the merge, and it all seems impossible. How the heck are people supposed to use Ethereum in this condition?

**Comment by holiman** [comment]
If you think e.g https://lighthouse-book.sigmaprime.io/ is poorly documented, well, I don't know what to say. 

> I just want to ideally run one client that references past chain data. Nobody has explained if this will be possible, or if it is now. 

Not possible. The documentation basically everywhere, and in the geth process logs, and on our discord, says that you need geth _and_ a beacon node. A.k.a an EL-client and a CL-client. I think it's the single most explained fact about the merge, that node operators now need to run two clients.

**Comment by woodydeck** [comment]
> https://lighthouse-book.sigmaprime.io/

Yes. That is an example of poor documentation. If this were a side project, ok fine, talk to the developer and help contribute. There's no answer to what I want to do, no attempt to understand the end user, and a complete disregard of decentralization here.

Closing valid tickets is not going to help. The idea to be language neutral seems good in theory, in practice it is like voting for candidates under socialism. Every single beacon client sucks in a slightly different way. It's not a real choice.

Lodestar is the best beacon client. It works - sort of, and the devs are responsive, unlike here, where everyone knows it all and thinks people are going to continue to run full nodes. Might as well say something nice. I know people are trying, but ignorance is running high now.

I've been here since 2016, I'm now out. My nodes are not coming back up. Please reference this 'annoying' ticket in the future when things go a lot worse than anyone OG expected. This is a prime example of hubris.

I wish I wish wrong here. I'm used to being wrong. I still could be wrong, but it sure doesn't seem like it. Best of luck.
