### ISSUE TITLE
What files should be deleted from disk in order to run new geth from snapshot?

### ISSUE THREAD

**Issue by Aracki** [ethereum/go-ethereum#25981]
I want to run a new geth based on the disk snapshot of the whole home directory of the previously running full-archive node.

In geth's home directory there is other stuff than `chaindata/` dir. I understand `nodekey` file should be deleted, so geth autogenerate a new one in order not to confuse p2p network that the node already exist in the network.

But what about other files/folders, do I need to delete some of those as well to speed up booting new geth?

**Comment by holiman** [comment]
Use `geth <args> removedb`, this is a command for exactly that, so people don't have to delete files themselves. 
The `<args>` is used if you have the datadir at a non-default location, so for example you could do `geth --datadir /foo/bar/bazonk removedb` 

The command will ask you if it should delete 
1. The state database. Select yes
2. The ancient database. This is the block bodies, receipts, headers etc. You can leave them intact, and not have to download ~400G from the network. 
3. The LES database .You can select yes to delete that.
