### ISSUE TITLE
ABI: merge several ABI objects to produce a single ABI object

### ISSUE THREAD

**Issue by simon-saliba** [ethereum/go-ethereum#25989]
# Rationale

It is sometimes useful to create a single ABI object from several different ABI objects by merging distinct fields and preserving one copy of the overlapping fields. The current alternative to do it is to merge the json objects together and then converting into an abi object.
It would look something like this: `func (abi *ABI) FromABIs(abis []*ABI) error`

# Implementation

I can implement the feature.

**Comment by Atharv181** [comment]
By using the array of pointers?

**Comment by holiman** [comment]
I'm sceptical. Merging the json is doable by hand, whereas merging the abi is less straight-forward. Even figuring out that it's possible is a threshold. I don't think this feature will be used enough to warrant it.

**Comment by rjl493456442** [comment]
Can you elaborate the use cases for merging the bindings together?

Personally I feel it's cleaner to have separate bindings for different contracts. The variable name conflicts usually can be resolved by specifying different type name of binding.
