### ISSUE TITLE
Building from source builds geth only, and not the other utilities

### ISSUE THREAD

**Issue by giacecco** [ethereum/go-ethereum#2599]
#### System information

Geth version: 1.4.4-stable-8ea3c88e
OS & Version: Linux (Fedora 23)

#### Expected behaviour

After building completes, the ```build/bin``` folder contains all go-ethereum utilities: ```geth```, ```bootnode```, ```evm```, ```disasm```, ```rlpdump``` and ```ethtest```.

#### Actual behaviour

The ```build/bin``` folder contains ```geth``` only.

#### Steps to reproduce the behaviour

Download the latest source and build as from instructions at https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu .

**Comment by karalabe** [comment]
`make all`? :P

**Comment by giacecco** [comment]
@karalabe I apologise, I was sure I had tried that :-(
