### ISSUE TITLE
What is the STACK TRIE for?

### ISSUE THREAD

**Issue by joonha97** [ethereum/go-ethereum#26005]
Hello, 

I am looking inside the Snap Sync process and found that the state/storage trie rebuilding process is accelerated by serialized leaf node insertion called "Stack Trie update". And I have 3 questions about the stack trie utilization.

### _**1. Is the Stack trie faster than a normal trie?**_
I understood that stack trie commits every left child that won't be touched again in the middle of the update process.
But is it really time-efficient? 
When I tried to compare the stack trie rebuilding time to the normal trie rebuilding time (including the time for trie commit and db commit), what I found is that the stack trie was much slower than the normal trie.
(I inserted sorted keys to both tries.)

### _**2. Why does Snap Sync use the Stack Trie?**_
Is it for the time-efficiency or the memory-efficiency?
To the best of my knowledge, the stack trie seems slower than the normal trie.
Then why did the snap sync choose the stack trie?
Is it because the stack trie fits the concurrent syncing?
If then, would it really be faster? But then, why does it commit in the middle of the trie update process?
Or is it just because the stack trie consumes less memory?

### **_3. Is the reason why the incoming snapshot is sorted to use the Stack Trie?_**
I understood that the incoming snap data is sorted and this perfectly fits the stack trie update.
Is this sorting just for the stack trie update?

_(code below is for the normal trie update)_
```
normalTrie, _ = trie.NewSecure(common.Hash{}, trie.NewDatabase(diskdb_out_normal))

// inject the data
RebuildNormalTrieStarts := time.Now().UnixNano() / int64(time.Millisecond)
for i, enc := range accounts {
	data := new(types.StateAccount)
	addr := common.BytesToAddress(enc) // BytesToAddress() turns last 20 bytes into addr
	
        if err := rlp.DecodeBytes(enc, data); err != nil {
		log.Error("Failed to decode state object", "addr", addr, "err", err)
	}

	acc, _ := rlp.EncodeToBytes(data)
       
        // don't worry, we handled key hashing!
	if err := normalTrie.TryUpdate(keys[i][:], acc); err != nil {
		s.setError(fmt.Errorf("updateStateObject (%x) error: %v", addr[:], err))
	}
}

// commit
var root common.Hash
if root, _, err = normalTrie.Commit(nil); err != nil {
	fmt.Println("normalTrie.Commit error !!")
}
normalTrie.Database().Commit(root, false, nil)

RebuildNormalTrieEnds := time.Now().UnixNano() / int64(time.Millisecond)
```

_(and the code below is for the stack trie update)_
```
stackTr := trie.NewStackTrie(diskdb_out_stack.NewBatch())

// inject the data
RebuildStackTrieStarts := time.Now().UnixNano() / int64(time.Millisecond)
for index, key := range keys {
	stackTr.TryUpdate(key[:], accounts[index])
}

RebuildStackTrieEnds := time.Now().UnixNano() / int64(time.Millisecond)
```

Can anyone be so kind and give me a hint?
Thanks you so much!

**Comment by holiman** [comment]
1. In most cases, yes

See https://github.com/ethereum/go-ethereum/pull/21407#issuecomment-694874776 . On small sets, it's probably slower. On larger sets, the stacktrie memory consumption is basically constant -- it can build a trie of infinity elements using a few hundred nodes. A regular trie blows up, so a lot of resources are spent on allocation and gc. 

> what I found is that the stack trie was much slower than the normal trie.

Interesting. If you show me what you did I can see if there's any obvious flaw. 


2. Why does Snap Sync use the Stack Trie?

> Is it for the time-efficiency or the memory-efficiency?

Yes, both. But mostly memory. 

3. Is the reason why the incoming snapshot is sorted to use the Stack Trie?

> I understood that the incoming snap data is sorted and this perfectly fits the stack trie update. Is this sorting just for the stack trie update?

Nope, it's the other way around. Since the values are sorted, we saw that we could make a more memory-efficient trie evaluation of the values.

**Comment by joonha97** [comment]
Thank you so much for your reply, @holiman !

I tried to estimate the time by the code below.
[[statedb.go](https://github.com/joonha97/rebuild-ethereum-state-trie/blob/main/statedb.go)](https://github.com/joonha97/rebuild-ethereum-state-trie/blob/main/statedb.go)
It is really simple code that just updates standard/stack trie by injecting the key-value pairs.

There were much more accounts than [#21407](https://github.com/ethereum/go-ethereum/pull/21407#issuecomment-694874776), I injected more than **_1M_** key-value pairs in increasing order.
And as the number of key-value pairs increased, the time difference widened.
(Stack Trie was slower...)

I tried but could not find what the problem is...
Can you help me?
Thank you!

**Comment by joonha97** [comment]
To both tries, I inserted data sorted by its key.

**Comment by holiman** [comment]
> There were much more accounts than https://github.com/ethereum/go-ethereum/pull/21407#issuecomment-694874776, I  injected more than 1M key-value pairs in increasing order.
And as the number of key-value pairs increased, the time difference widened.
(Stack Trie was slower..... when injected 4039894 key-value pairs,
standard trie takes about 30000 ms and stack trie takes 90000 ms.)

1M key-value leafs means that the normal trie is holding somewhere between 1-2M nodes in memory. This might be fine:ish for a one-off benchmark when your computer is not doing much else, and you have RAM to spare. Qurious though: I'm not sure you actually do any writes in either of the two cases

```golang
		normalTr, _ := trie.New(common.Hash{}, trie.NewDatabase(diskdb_out_normal))
```
The trie will flush to a trie.Database, but I don't think you are ever making that flush to disk. 

```golang
		stackTr := trie.NewStackTrie(diskdb_out_stack.NewBatch())
```
And the stacktrie writes to a batch, but I don't think the batch is actually flushed? Also, I think your code is not based off of latest geth, so I'm not sure what the semantics of your code is. For example, Commit now returns the modified nodeset. 


Also, I think a better approach is to use golang's built-in benchmark-tests.

**Comment by joonha97** [comment]
Thank you so much for the reply again, @holiman !

I flushed the normal trie by the code below.
And I checked that my target disk's size has been increased.
```
if root, _, err = normalTr.Commit(nil); err != nil {
	fmt.Println("normalTr.Commit error !!")
}
normalTr.Database().Commit(root, false, nil)
```

And I thought I was flushing by stackTrie's TryUpdate() containing the code below(current geth version!)
```
st.val = hasher.hashData(encodedNode)
if st.db != nil {
        // TODO! Is it safe to Put the slice here?
        // Do all db implementations copy the value provided?
        st.db.Put(st.val, encodedNode)
}
```
Should I do something else to flush the stackTrie?

Sorry for bothering you several times....
Thank you so much!

**Comment by holiman** [comment]
> Should I do something else to flush the stackTrie?

Something like this:

```golang
batch := diskdb_out_stack.NewBatch()
...
batch.Write()
```

**Comment by joonha97** [comment]
omg, yes I have omitted that..... Thank you! @holiman 

But what I still cannot understand is :
I thought the stack trie accelerate the trie update by concurrent db flushing, but it seems not. 

What makes the stack trie faster than the normal trie if I have enough RAM...?

Thanks a lot....😭

**Comment by holiman** [comment]
The stacktrie is serial. Some parallelization can be achieved, by flushing the batch in parallel with the stacktrie inserts happening. 
The normal trie can be parallelized more, for example it's possible to let 8 goroutines traverse different subtries. That's what the hasher does, it spinds up several routines and just descends down different paths.  

> In general, what makes the stack trie faster than the normal trie if I have enough RAM...?

If RAM is not an issue, and garbage-collection is not an issue (i.e: happens after the test), then stacktrie is not inherently faster, I think.

**Comment by joonha97** [comment]
I flushed the batch in parallel with the stackTrie insertion and accomplished a wonderful performance increase of the stack trie exactly what I wanted!

And I clearly understood what you let me know, stackTrie performs similarly to the normal trie updates by multi goroutines!

With all my heart, thank you my savior, @holiman

**Comment by holiman** [comment]
You're welcome. Take a bit of care, though, when flushing a batch in a parallel routine, you need to do it so that you don't have race conditions. E.g. by swapping out the batch for a new batch, and shipping the "full" batch to to a routine that calls Write. Or something like that.

**Comment by joonha97** [comment]
I'll keep that in mind. Thank you for the kind advice! 👍
