### ISSUE TITLE
geth 1.11 unstable version JSON-RPC request error

### ISSUE THREAD

**Issue by talhabekci** [ethereum/go-ethereum#26024]
When I make a request to geth over JSON-RPC with php `{"jsonrpc":"2.0","id":1,"error":{"code":-32600,"message":"invalid request"}}` I get this error. There was no such problem when I using geth 1.10.xx stable version before, but when I switched to geth 1.11.xx unstable version, I started getting this error.
I have shared how I made the request.
![Ekran Resmi 2022-10-21 15 49 44](https://user-images.githubusercontent.com/58186555/197199657-a9b173b6-73d9-4555-8f8c-26ed370820bf.png)

**Comment by MariusVanDerWijden** [comment]
I believe we removed the account management with 1.11, so eth_accounts is not supported anymore

**Comment by MariusVanDerWijden** [comment]
Ah wait nvm might not actually be merged yet. I'll investigate later

**Comment by talhabekci** [comment]
> I believe we removed the account management with 1.11, so eth_accounts is not supported anymore

But all methods return the same error

**Comment by holiman** [comment]
Nothing re accounts removed yet. Just a ticket opened for discussion

**Comment by karalabe** [comment]
Could you try via the console `curl` and if it does not work please paste us a command that does not work? It's a bit hard for us to repro this from a .php screenshot.

**Comment by talhabekci** [comment]
> Could you try via the console `curl` and if it does not work please paste us a command that does not work? It's a bit hard for us to repro this from a .php screenshot.

I tried via console but not worked.

function request ($method, $params, $id) {
    if(!$init = curl_init()){
        return ["result" => NULL, "error" => ["code" => NULL, "message" => "Initalize a cURL session"]];
    }

    $options = [
        CURLOPT_PROTOCOLS => CURLPROTO_HTTP,
        CURLOPT_URL => "192.168.1.50",
        CURLOPT_PORT => "8545",
        CURLOPT_RETURNTRANSFER => TRUE,
        CURLOPT_HTTPHEADER => ["Content-Type: application/json"],
        CURLOPT_POST => TRUE,
        CURLOPT_POSTFIELDS => json_encode(["method" => $method, "params" => $params, "id" => $id])
    ];

    if (!curl_setopt_array($init, $options)) {
        return ["result" => NULL, "error" => ["code" => NULL, "message" => "Set multiple options for a cURL transfer"]];
    }

    if (!$exec = curl_exec($init)) {
        return ["result" => NULL, "error" => ["code" => NULL, "message" => "Perform a cURL session"]];
    }

    curl_close($init);
    return json_decode($exec, TRUE);

}

$request = request("eth_getBalance", ["0x5303a6604BDc36C83DD0F9B173CA415D4140374A", "latest"], 1);
echo json_encode($request);

**Comment by ligi** [comment]
cab you provide the command you used on the console to try and that failed?

**Comment by jsvisa** [comment]
Seems you are missing `"jsonrpc":"2.0",` in 

```
CURLOPT_POSTFIELDS => json_encode(["method" => $method, "params" => $params, "id" => $id])
```

**Comment by s1na** [comment]
> Seems you are missing "jsonrpc":"2.0"

I will close as I believe this is the issue.
