### ISSUE TITLE
Syncing issue after process killed

### ISSUE THREAD

**Issue by srt180** [ethereum/go-ethereum#26039]
I've got the syncing issue before, `Syncing: state healing in progress`, and I fixed this by `geth removedb` and restart from scratch, and it works well.
I run geth in docker. The problem is, after I stop the container and rerun the container with the volume of the datadir, I got the syncing issue again `Syncing: state healing in progress`.
Should I kill the process elegently? And how?

**Comment by holiman** [comment]
>  Should I kill the process elegently? And how?

Yes, always. That's the most common error people do. Use a larger timeout, e..g `docket stop -t 120 <geth-container>`

**Comment by holiman** [comment]
However, people have been complaining about that, but I've never seen logs from it -- and it should not be able to happen: being in sync, then restarting, then getting "State healing in progress". If you have logs showing that, it would be interesting to see.

**Comment by srt180** [comment]
I cleaned the logs... Here is what I did:
1. I run geth synced in docker, and I noticed I forgot one command option from my code, then I stop and rm the container and recreate the container
2. It has no `State healing in progress` logs, but it synced slowsly, the metrics of `geth.chain/head/header.gauge`, `geth.chain/head/receipt.gauge`, `geth.chain/head/block.gauge` was all same but stale, about 20k blocks behind.
3. I restart the container again, and I got `State healing in progress`

I wish this will help.
