### ISSUE TITLE
Erroneous comparison in api.go

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#2604]
https://github.com/ethereum/go-ethereum/blob/290e851f57f5d27a1d5f0f7ad784c836e017c337/eth/api.go#L1106

	fields := map[string]interface{}{
		"root":              common.Bytes2Hex(receipt.PostState),
		"blockHash":         txBlock,
		"blockNumber":       rpc.NewHexNumber(blockIndex),
		"transactionHash":   txHash,
		"transactionIndex":  rpc.NewHexNumber(index),
		"from":              from,
		"to":                tx.To(),
		"gasUsed":           rpc.NewHexNumber(receipt.GasUsed),
		"cumulativeGasUsed": rpc.NewHexNumber(receipt.CumulativeGasUsed),
		"contractAddress":   nil,
		"logs":              receipt.Logs,
	}

	if receipt.Logs == nil {
		fields["logs"] = []vm.Logs{}
	}

The check `if receipt.Logs == nil` will always be false. I'd give you a PR if I knew 100% what the correct way to fix it was. For Go-code, I'm better at reading than writing... :)

Found through DAST-check.

**Comment by bas-vk** [comment]
Why is this check always false and what is a DAST-check?

**Comment by holiman** [comment]
Sorry, meant SAST: Static Analysis Security Testing, but actually just an automated code scanning with 'go tools vet ...'

I'm no go-expert, but I interpret the output as Logs being a method, not an attribute. As if the intention was Logs() but parenthesis got dropped.

**Comment by bas-vk** [comment]
In go these attributes are called fields and this is intentional :).

`types.Receipt.Logs` is a slice of Log pointers. Slices can be nil or of [0, ...] length. In this case if `Logs` is nil there are no logs and in that case we return an empty array of logs in the RPC interface instead of JSON null or omitting the log field entirely.

**Comment by holiman** [comment]
Sorry for wasting your time. I thought that the `go tools vet` was more reliable.
