### ISSUE TITLE
tracer accessed out of bound memory while debug_traceTransaction

### ISSUE THREAD

**Issue by uniwswap** [ethereum/go-ethereum#26062]
#### System information

Geth version: 1.10.23-stabl
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
for debug_traceTransaction it should not go out of memory and revert data

#### Actual behaviour
`tracer accessed out of bound memory` while calling debug_traceTransaction

#### Steps to reproduce the behaviour
I am implementing it with blockscout explorer

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by holiman** [comment]
I think this is already fixed in `master`, via https://github.com/ethereum/go-ethereum/pull/25213

**Comment by MariusVanDerWijden** [comment]
I'm going to close this, if the issue still persists I'll reopen it again, please check with the current master. Thanks for submitting!
