### ISSUE TITLE
Feature request: Command line flag to stop client before running out of disk space

### ISSUE THREAD

**Issue by dankrad** [ethereum/go-ethereum#26061]
Currently go-ethereum keeps running until it is out of disk space. However pruning requires about 40GB of extra disk space, so this is not reasonable behaviour. It should automatically stop before there is not enough disk space available for pruning.

I suggest adding a command line flag that specifies the available space at which geth automatically shuts down to allow the user to prune. I would also suggest setting it to a reasonable default like 40 GB, so users don't get trapped as it happens now: go-ethereum just keeps running until the disk is full, at which point pruning becomes impossible.

**Comment by holiman** [comment]
Also, pruning doesn't really get impossible. It ought to be possible to do a workaround: delete all "finished" ancient-files, do the pruning, and then restore them from some other installation somewhere.

**Comment by dankrad** [comment]
This switch should then just be set to default to 40 GB, so that a user running the default config will not run out of space to prune their node.

> It ought to be possible to do a workaround: delete all "finished" ancient-files, do the pruning, and then restore them from some other installation somewhere.
This is terrible UX, and isn't documented anywhere!

**Comment by MariusVanDerWijden** [comment]
Closing this for now. We detect a full disk already and have a command `--datadir.minfreedisk` to configure the detection limit. With PBSS pruning is not a big problem anymore and it will become even less of an issue with history expiry in the future.
