### ISSUE TITLE
Geth prune consistently Killed

### ISSUE THREAD

**Issue by arielmelendez** [ethereum/go-ethereum#26065]
geth info:
Version: 1.11.0-unstable
Git Commit: ada603fab5c854b36a1d7d9af0ba5aeeafa49d15
Git Commit Date: 20220916
Architecture: amd64
Go Version: go1.19.1
Operating System: linux (Ubuntu 20.04.5 LTS - focal)

Attempted running a geth prune on a 1000GB NVMe drive with ~38GB in remaining storage space. I killed the geth process and waited a few minutes for a graceful exit (though I neglected to actually double check). I ran the prune command on my data-dir. Within a few minutes, I received logs like the following, ending with `Killed` and no other message:

```
tmpfs              814824      1052    813772   1% /run
ERROR[10-29|04:49:34.069] Error in block freeze operation          err="block receipts missing, can't freeze block 15624205"
ERROR[10-29|04:50:34.067] Error in block freeze operation          err="block receipts missing, can't freeze block 15624205"
ERROR[10-29|04:51:34.079] Error in block freeze operation          err="block receipts missing, can't freeze block 15624205"
ERROR[10-29|04:52:34.068] Error in block freeze operation          err="block receipts missing, can't freeze block 15624205"
ERROR[10-29|04:53:34.068] Error in block freeze operation          err="block receipts missing, can't freeze block 15624205"
ERROR[10-29|04:54:34.068] Error in block freeze operation          err="block receipts missing, can't freeze block 15624205"
ERROR[10-29|04:55:34.088] Error in block freeze operation          err="block receipts missing, can't freeze block 15624205"
INFO [10-29|04:55:43.307] Pruning state data                       nodes=1 size=564.00B elapsed=12m7.036s eta=1h7m1.526s
INFO [10-29|04:55:51.311] Pruning state data                       nodes=1,075,917 size=396.83MiB elapsed=12m15.039s eta=1h7m3.971s
INFO [10-29|04:55:59.316] Pruning state data                       nodes=2,051,690 size=757.08MiB elapsed=12m23.045s eta=1h7m9.998s
INFO [10-29|04:56:07.325] Pruning state data                       nodes=3,027,201 size=1.09GiB   elapsed=12m31.053s eta=1h7m15.874s
INFO [10-29|04:56:15.333] Pruning state data                       nodes=3,956,312 size=1.43GiB   elapsed=12m39.062s eta=1h7m23.249s
INFO [10-29|04:56:23.333] Pruning state data                       nodes=4,979,120 size=1.79GiB   elapsed=12m47.062s eta=1h7m26.891s
INFO [10-29|04:56:31.334] Pruning state data                       nodes=5,993,691 size=2.16GiB   elapsed=12m55.062s eta=1h7m30.654s
ERROR[10-29|04:56:34.094] Error in block freeze operation          err="block receipts missing, can't freeze block 15624205"
INFO [10-29|04:56:39.336] Pruning state data                       nodes=6,871,600 size=2.48GiB   elapsed=13m3.064s  eta=1h7m39.322s
INFO [10-29|04:56:47.341] Pruning state data                       nodes=7,748,973 size=2.79GiB   elapsed=13m11.069s eta=1h7m47.76s
INFO [10-29|04:56:55.348] Pruning state data                       nodes=8,696,527 size=3.14GiB   elapsed=13m19.076s eta=1h7m53.437s
INFO [10-29|04:57:03.355] Pruning state data                       nodes=9,662,247 size=3.48GiB   elapsed=13m27.083s eta=1h7m58.194s
INFO [10-29|04:57:11.361] Pruning state data                       nodes=10,650,597 size=3.84GiB   elapsed=13m35.089s eta=1h8m1.951s
Killed
```
The error lines appeared periodically throughout the process, but it continued without termination. But termination did later come after seemingly ordinary `Pruning state data` logs.

I reran the command a number of times to see if any other clues would present themselves or whether the process might be flaky and simply complete. In each of the subsequent runs, I noticed logs with a warning like "The clean trie cache is not found.", "... delete it after pruning...", but again the process continued without termination for a while.

Concerned that I'd let my disk get too full to complete a pruning, I expanded the cloud server's block storage another 300GB just to be sure, but the same premature process termination behavior continues to occur without obvious crash logs.

**Comment by holiman** [comment]
Could you check the syslog? Typically journalctl or /var/log/syslog , depending on system. Check for the OOM-reaper, it probably killed the process due to memory getting low.

**Comment by MariusVanDerWijden** [comment]
This has been stale for a while and holiman's suggestion to check the logs and see if an OOM occurred would probably show the issue. Would be good to see if we can reduce the memory consumption while pruning a bit, I looked around the code a bit but didn't find any obvious quick fixes

**Comment by holiman** [comment]
Seems abandoned
