### ISSUE TITLE
How Go-Ethereum maintain log files?

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#26081]

**Comment by holiman** [comment]
It does not. Many other tools exist to help maintain log files - deamons that to log rotation, compression, or for that matter cloud-integration via syslog. There are a lot of ways people want their logs, so geth just does the bare minimum: spit out he logs on `stderr`. We also have the option to configure machine-readable logs (json-formatted), but that's about it. After that, it's up to the user to build.
