### ISSUE TITLE
Clique-based CL "client"

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#26099]
We need an external library/binary, which should do the same thing that the beacon chain does. But it should use clique to sign the blocks. 

It is sort of a "mini-go-ethereum" which doesn't have transaction processing, but does have block relaying and gossip, and can do snap-sync and process headers (and blocks?). It then uses the clique-info from the headers to drive an "EL-client" . 

The block relay is not enabled post-POS, so we need some additional subprotocol to pass the blocks around.

**Comment by rjl493456442** [comment]
Looks like this idea is abandoned. Close it now.
