### ISSUE TITLE
eth_getLogs missing logs for latest block

### ISSUE THREAD

**Issue by r1cs** [ethereum/go-ethereum#26098]
#### Expected behaviour
I have a service syncing logs(such as [1,2,3,...] consequent number) to latest block.
In my old logic, it only sync to confirmed height(latest height - 20), and it works fine.
But when I try to sync to lates height, logs in latest block may missing.After a while,I can get logs at that block, it seems that sometion async happen when get logs?

```
number := eth_blockNumber
curl --request POST \
     --url https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161 \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
     "id": 1,
     "jsonrpc": "2.0",
     "method": "eth_getLogs",
     "params": [
          {
               "address": xxx,
               "fromBlock": number,
               "toBlock": number,
                "topics":xxxx
          }
     ]
}
```

By the way, I'm using get_logs by abi, and this happen only  trying to get logs in `latest` block, and when it confired, after 20 block,i can get the logs. 

Ret: specific logs
'

#### Actual behaviour
nothing found

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by ligi** [comment]
Did you try with geth directly also? Or did you see the problem always with infura?

**Comment by quickchase** [comment]
Probably Related: #26101

**Comment by r1cs** [comment]
Maybe becaused of the load balancing of RPC server, But why not notice me that My get_logs' end params is larger than local highest state.

**Comment by gballet** [comment]
We can not provide a guarantee up to `latest`, because there can be reorgs.
