### ISSUE TITLE
Events Post blocks

### ISSUE THREAD

**Issue by ebuchman** [ethereum/go-ethereum#261]
I recall in the old ethreactor, if a channel was blocked while trying to post on it (ie. there was no receiver waiting with a <- chan), the channel would be skipped (an error message came along with this). 

This no longer seems to be the behaviour. Is this intended? or should we add the 
```
default:
  logger.Debugf("subscribing channel %d to event %s blocked. skipping\n", i, event.Name)
```
back to the switch statement?

**Comment by fjl** [comment]
This is intended. The idea behind this was that synchronous messaging is easier to reason about. With the current design, there are never any pending events stuck in a queue somewhere. 
You can use the event system as a synchronization device. =

**Comment by fjl** [comment]
If you have a need for asynchronous posting of events use `go mux.Post(...)`.
