### ISSUE TITLE
Who can help me to explain why the error is reported when using curl? Thank you

### ISSUE THREAD

**Issue by lalLAL95828** [ethereum/go-ethereum#26102]
![image](https://user-images.githubusercontent.com/16337280/199906474-8dd0e13e-c16b-4c5d-b389-f6a1908c0001.png)

**Comment by juanmaroni** [comment]
Have you tried:
- URL as "http://localhost:8551"?
- Escaping double quotes? As:
`"{\"jsonrpc\":\"2.0\",\"method\":\"eth_accounts\",\"params\":[],\"id\":1}"`

**Comment by MariusVanDerWijden** [comment]
Looks like a curl issue not an issue with geth

**Comment by holiman** [comment]
Actually, the problem is that `localhost:8551` is not a URL. That's what curl is telling you: `URL using bad/illegal format or missing URL`. As @juanmaroni points out, you need to include the protocol, `http://`
