### ISSUE TITLE
password on eth wallet 0.7.3. doesnt work

### ISSUE THREAD

**Issue by Drummz** [ethereum/go-ethereum#2610]
Node type: geth/eth
OS: osx
Network type: main/test
Mist version: 0.7.3

i already tried to sync my wallet a few times and after i dont know 20 times wallet synced.
But when i tried to send some eth on another address it was writen first that it couldnt connect with the nodes...ok... but after that problem my pasword didn't work anymore. I have pass which i created on the beginning but it doesnt work...

Any expirience with that?

**Comment by karalabe** [comment]
@luclu Can you pick this up? :)

**Comment by luclu** [comment]
@Drummz could you please reopen this issue on the mist repository ([link](https://github.com/ethereum/mist/issues)) - as that one is more appropriate regarding your problem. :)

**Comment by Drummz** [comment]
thanks guys!

**Comment by karalabe** [comment]
Closing this. Please reopen if it turns out to be an issue with Geth.
