### ISSUE TITLE
How to get metadata from deployed contract?

### ISSUE THREAD

**Issue by nicwhitts** [ethereum/go-ethereum#26117]
If i have deployed a contract using the bindings. How can i get the metadata (like generated with solc or truffle) that was used for the exact contract deployed?

Is there a cache somewhere i can find this?

**Comment by rjl493456442** [comment]
I think the metadata you mentioned refers to `bin` and `abi`?

These information is passed by users which generated by compiler, the binding code will include them, e.g. https://github.com/ethereum/go-ethereum/blob/master/contracts/checkpointoracle/contract/oracle.go#L30

**Comment by nicwhitts** [comment]
I believe it’s different. For an exact match for source code verification the keccak256 values need to be correct. 

Reference: 
https://docs.soliditylang.org/en/v0.8.16/metadata.html

I have attempted to compile the same contracts that are used to generate the go bindings. But the keccak256 values are always different. Resulting in failed exact match (I need exact match)

**Comment by MariusVanDerWijden** [comment]
You can not get the metadata from a deployed contract I think. The metadata contains the natspec and compiler version etc. This information is not stored on chain.
