### ISSUE TITLE
admin.addPeer() does not return `true` and does not add new user

### ISSUE THREAD

**Issue by Gelassen** [ethereum/go-ethereum#26125]
Probably it is an issue with misconfiguration, but in this case you might consider the question as a commitment to improve documentation - there is not enough official docs regarding how to setup a private chain. 

I was in process of setting up a new private chain when faced with issue on the stage of linkin two extra nodes with the boot node: 
```
>admin.addPeer(enode://64dccd02d5d1166cfb4913f0d0c164dff2b9c61fd55182461010569e15319c7ff5cb4dc8b502e441c38c80ae1b42c2cc95c7e170ed973bb0353d766669c5447c@127.0.0.1:2001")
... 
```
As I understand from comments over the web, instead of this three dots the command should return 'true' in the positive scenario. Anyway the command ```net.peerCount``` returns zero - there is no added peer to the running chain. 

I have look through similar issues here, but this issue seems different. 

**Steps to reproduce:** 
 
1. Create folders for 3 nodes
2. Create accounts in nodes: 

`$geth --datadir ./node1/data account new`

3. Generate genesis block:

`$puppeth`

4. Export chain configuration: 

`$puppeth (reselect option 2. Manage existing genesis)`

5. Initialize all nodes with chain config: 

```
$geth --datadir ./node1/data init <chain config>.json
$geth --datadir ./node2/data init <chain config>.json
$geth --datadir ./node3/data init <chain config>.json
```

6. Start nodes: 
```

$geth --datadir ./node1/data --port 2001 (default authrpc.port 8551)
$geth --datadir ./node2/data --port 2002 --authrpc.port 8552
$geth --datadir ./node3/data --port 2003 --authrpc.port 8553
```

7. Link all nodes with a main one: 

```
$geth attach ipc:node1/data/geth.ipc
$admin.nodeInfo.enode
(reply would be something similar to "enode://64dccd02d5d1166cfb4913f0d0c164dff2b9c61fd55182461010569e15319c7ff5cb4dc8b502e441c38c80ae1b42c2cc95c7e170ed973bb0353d766669c5447c@195.178.22.21:2001?discport=39805")
$geth attach ipc:node2/data/geth.ipc
$admin.addPeer(enode://64dccd02d5d1166cfb4913f0d0c164dff2b9c61fd55182461010569e15319c7ff5cb4dc8b502e441c38c80ae1b42c2cc95c7e170ed973bb0353d766669c5447c@127.0.0.1:2001")
```

Environment:
Virtual Machine with Ubunut 20.04, all nodes are instantiated on this virtual machine.
Geth instance: instance: Geth/v1.10.26-stable-e5eb32ac/linux-amd64/go1.18.5

**Comment by Gelassen** [comment]
I was able to add new peer. I started from the first node and was able to get 'true' response from the ```admin.addPeer()``` command. However the root cause of the issue is not clear.

**Comment by holiman** [comment]
The three dots means that the prompt is not finished. Your example, but I removed some characters:
```
admin.addPeer(enode://64d...7c@127.0.0.1:2001")
... 
```
So you missed the starting `"` before `enode`.
