### ISSUE TITLE
Geth fails to shutdown in 90s, is killed by systemd

### ISSUE THREAD

**Issue by dankrad** [ethereum/go-ethereum#26131]
#### System information

Geth version: 1.10.23
CL client & version: lighthouse@3.1.0-aa022f4
OS & Version: Linux (ubuntu 20.04)

#### Expected behaviour

Should shutdown within 90s and write snapshot

#### Actual behaviour

From the logs, it looks like it just "forgot" about the shutdown and started looking for peers again. It was killed after 90s by systemd, after which it detected an unclean shutdown and started re-syncing the last 10 days.

#### Steps to reproduce the behaviour

???

#### Backtrace

````
Nov 07 23:18:00 kettenbruch geth[22593]: INFO [11-07|23:18:00.595] Imported new potential chain segment     blocks=1  txs=124   mgas=12.250  elapsed=70.809ms     mgasps=173.005  number=15,921,081 hash=76ac75..9fef22 dirty=255.09MiB
Nov 07 23:18:00 kettenbruch geth[22593]: INFO [11-07|23:18:00.722] Chain head was updated                   number=15,921,081 hash=76ac75..9fef22 root=2fe12a..97ffd5 elapsed=9.338835ms
Nov 07 23:18:00 kettenbruch geth[22593]: INFO [11-07|23:18:00.726] Unindexed transactions                   blocks=1  txs=135   tail=13,571,082 elapsed=4.025ms
Nov 07 23:18:05 kettenbruch systemd[1]: Stopping geth.service...
Nov 07 23:18:06 kettenbruch geth[22593]: INFO [11-07|23:18:06.002] Got interrupt, shutting down...
Nov 07 23:18:06 kettenbruch geth[22593]: WARN [11-07|23:18:06.139] HTTP server graceful shutdown timed out
Nov 07 23:18:06 kettenbruch geth[22593]: INFO [11-07|23:18:06.139] HTTP server stopped                      endpoint=178.63.1.154:41314
Nov 07 23:18:06 kettenbruch geth[22593]: INFO [11-07|23:18:06.150] IPC endpoint closed                      url=/home/ethereum/ssd/geth-datadir/geth.ipc
Nov 07 23:18:16 kettenbruch geth[22593]: INFO [11-07|23:18:16.338] Looking for peers                        peercount=2  tried=149 static=0
Nov 07 23:18:26 kettenbruch geth[22593]: INFO [11-07|23:18:26.340] Looking for peers                        peercount=1  tried=170 static=0
Nov 07 23:18:32 kettenbruch geth[22593]: WARN [11-07|23:18:32.125] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!
Nov 07 23:18:36 kettenbruch geth[22593]: INFO [11-07|23:18:36.393] Looking for peers                        peercount=2  tried=166 static=0
Nov 07 23:18:46 kettenbruch geth[22593]: INFO [11-07|23:18:46.622] Looking for peers                        peercount=2  tried=153 static=0
Nov 07 23:18:54 kettenbruch geth[22593]: WARN [11-07|23:18:54.333] Snapshot extension registration failed   peer=ef7c914b err="peer connected on snap without compatible eth support"
Nov 07 23:18:56 kettenbruch geth[22593]: INFO [11-07|23:18:56.622] Looking for peers                        peercount=1  tried=125 static=0
Nov 07 23:19:06 kettenbruch geth[22593]: INFO [11-07|23:19:06.644] Looking for peers                        peercount=2  tried=170 static=0
Nov 07 23:19:14 kettenbruch geth[22593]: WARN [11-07|23:19:14.676] Snapshot extension registration failed   peer=43ba740c err="peer connected on snap without compatible eth support"
Nov 07 23:19:16 kettenbruch geth[22593]: INFO [11-07|23:19:16.665] Looking for peers                        peercount=1  tried=136 static=0
Nov 07 23:19:24 kettenbruch geth[22593]: WARN [11-07|23:19:24.421] Snapshot extension registration failed   peer=43ba740c err="peer connected on snap without compatible eth support"
Nov 07 23:19:26 kettenbruch geth[22593]: INFO [11-07|23:19:26.723] Looking for peers                        peercount=1  tried=95  static=0
Nov 07 23:19:29 kettenbruch geth[22593]: WARN [11-07|23:19:29.139] Snapshot extension registration failed   peer=ce89f279 err="peer connected on snap without compatible eth support"
Nov 07 23:19:36 kettenbruch systemd[1]: geth.service: State 'stop-sigterm' timed out. Killing.
Nov 07 23:19:36 kettenbruch systemd[1]: geth.service: Killing process 22593 (geth) with signal SIGKILL.
Nov 07 23:19:36 kettenbruch systemd[1]: geth.service: Main process exited, code=killed, status=9/KILL
Nov 07 23:19:36 kettenbruch systemd[1]: geth.service: Failed with result 'timeout'.
Nov 07 23:19:36 kettenbruch systemd[1]: Stopped geth.service.
Nov 07 23:19:36 kettenbruch systemd[1]: Started geth.service.
````

When submitting logs: please submit them as text and not screenshots.

**Comment by yorickdowne** [comment]
This isn’t a bug, it’s slow storage. Give it more time to shut down. See https://gist.github.com/yorickdowne/27d4a96174562377d86e4df5d8de654f

The longer Geth has been running, the longer it takes to shut down. Disk speed and cache size also come into it.

**Comment by holiman** [comment]
There might, or might not be a bug here. Usually, geth shuts down within `90s`, however a 2-3 minutes is a safer choice. 
From time to time, we have experienced shutdown-hangs, and once we do, we try to fix them asap, because those are pretty nasty. As far as I know, there's no such bug in 1.10.23, so for now I'll assume it's just a case of "it took longer than 90s"

> it looks like it just "forgot" about the shutdown and started looking for peers again

Well, it doesn't. It's just different processes. 

Both @dankrad and @YurGa777: if you can repro this (with _long_ timeout), it would be super-great if you can make the final-kill signal be a `SIGTRAP` -- because then we get the stacktrace, which is precisely what we need in order to figure out where it got stuck in the shutdown process.

**Comment by antondlr** [comment]
I can attest that there's definitely something going on here, not just storage speed related. 
In my case I didn't see systemd kill it since I run containers which were -as far as systemd is concerned- properly stopped (finishing in ~20s). 

This is on a fresh node w/ v1.10.26 which would unclean-shutdown every time (9 times out of 9 restarts/reboots). 
Downgraded to v1.10.24, then v1.10.25, now back on v1.10.26 and the issue seems to be miraculously gone.

**Comment by holiman** [comment]
> edit; turns out I was sending a SIGKILL after 10s, instead of waiting 


I assume this is not happening any more. Closing
