### ISSUE TITLE
"SubscribeFullPendingTransactions" function not available on gethclient go package.

### ISSUE THREAD

**Issue by degengalahad** [ethereum/go-ethereum#26134]
#### System information

Gethclient version: v1.10.26
CL client & version: lighthouse
OS & Version: OSX
Commit hash : latest

#### Expected behaviour
Expected to be able to use the mentioned function on my go code.

#### Actual behaviour
The function is not available on the official gethclient package: https://pkg.go.dev/github.com/ethereum/go-ethereum@v1.10.26/ethclient/gethclient

#### Steps to reproduce the behaviour
Check out the go package (https://pkg.go.dev/github.com/ethereum/go-ethereum@v1.10.26/ethclient/gethclient) and see that the function is not there.

**Comment by s1na** [comment]
That function hasn't been released yet. It's set for the v1.11.0 milestone (https://github.com/ethereum/go-ethereum/pull/25186). Please wait for the release or use `master`.

**Comment by degengalahad** [comment]
Thank you.
