### ISSUE TITLE
"too many arguments, want at most 1" error when using "SubscribeFullPendingTransactions" function.

### ISSUE THREAD

**Issue by degengalahad** [ethereum/go-ethereum#26143]
#### System information

Geth version: master
CL client & version:lighthouse
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour
Expected to use the "SubscribeFullPendingTransactions" function.

#### Actual behaviour
It gives the error: "too many arguments, want at most 1" which in my opinion makes no sense cause the function in the gethclient.go package recieves to arguments: 

```
func (ec *Client) SubscribeFullPendingTransactions(ctx context.Context, ch chan<- *types.Transaction) (*rpc.ClientSubscription, error) {
	return ec.c.EthSubscribe(ctx, ch, "newPendingTransactions", true)
}
```
#### Steps to reproduce the behaviour
Try to use the function "SubscribeFullPendingTransactions", this is an example of my code: 
```

gethClient := gethclient.New(rpcClient)

	fmt.Println("Connected")

	hash := make(chan *types.Transaction)

	sub, err := gethClient.SubscribeFullPendingTransactions(context.Background(), hash)
	if err != nil {
		log.Fatal(err)
	}
```
Thank you.

**Comment by s1na** [comment]
I can't reproduce this issue. Are you sure the running node is also on `master`?

**Comment by degengalahad** [comment]
Mmmm, I'm using quicknode, I didn't know the version the node was running had an impact, I thought it was dependant on the golang code.

**Comment by degengalahad** [comment]
Just submitted a ticket to quicknode to see if they're using master

**Comment by degengalahad** [comment]
Yep my node runs on the latest stable version, not master, shame.
