### ISSUE TITLE
SimulatedBackend doesn't allow creating a beacon chain

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#26148]
bacause of this line will allways return an error, there is no way to bypass this check so can't create a beacon simulated backend.

https://github.com/ethereum/go-ethereum/blob/093b2ac32ac96fdf89cd80ca8fe40cb9c9fc8f49/consensus/beacon/consensus.go#L426

**Comment by rjl493456442** [comment]
Can you explain a bit more about this issue? What's the problem you are facing?

**Comment by krasi-georgiev** [comment]
I am testing coinbase balance changes and when running the simulator for every produced block the coinbase is rewarded 2eth which is not in line with the current consensus.

**Comment by MariusVanDerWijden** [comment]
Yeah it's currently not possible to start the SimulatedBackend with a `Chainconfig` other than `params.AllEthashProtocolChanges` and `ethash.NewFaker`
