### ISSUE TITLE
eth.blockNumber  always returns 0!

### ISSUE THREAD

**Issue by gitloverr** [ethereum/go-ethereum#26145]
hi everyone,

My node, as my Geth log seems synced. But eth.blockNumber returns 0 on `**Geth version 1.10.25 & 1.10.26**`

 > eth.blockNumber
0

My Geth logs : 

`
INFO [11-09|11:38:36.710] Forkchoice requested sync to new head    number=15,931,333 hash=4ff3d9..e45642
INFO [11-09|11:38:39.198] State heal in progress                   accounts=25239@1.37MiB    slots=55348@4.14MiB   codes=193@1.08MiB    nodes=1,226,304@328.91MiB pending=20781
INFO [11-09|11:38:39.246] Imported new block headers               count=1    elapsed="664.758µs" number=15,931,333 hash=4ff3d9..e45642
INFO [11-09|11:38:47.306] State heal in progress                   accounts=25239@1.37MiB    slots=56935@4.26MiB   codes=193@1.08MiB    nodes=1,231,495@330.14MiB pending=19510
INFO [11-09|11:38:47.367] Forkchoice requested sync to new head    number=15,931,334 hash=0d76ec..9f72cf
INFO [11-09|11:38:48.248] Imported new block headers               count=1    elapsed="217.043µs" number=15,931,334 hash=0d76ec..9f72cf
INFO [11-09|11:38:55.630] State heal in progress                   accounts=25239@1.37MiB    slots=58684@4.40MiB   codes=193@1.08MiB    nodes=1,236,835@331.32MiB pending=18066
INFO [11-09|11:39:00.126] Forkchoice requested sync to new head    number=15,931,335 hash=712553..74ffc1
INFO [11-09|11:39:00.251] Imported new block headers               count=1    elapsed=1.125ms     number=15,931,335 hash=712553..74ffc1
INFO [11-09|11:39:04.168] State heal in progress                   accounts=25374@1.38MiB    slots=60720@4.55MiB   codes=193@1.08MiB    nodes=1,242,757@332.52MiB pending=15676
INFO [11-09|11:39:12.667] State heal in progress                   accounts=25541@1.39MiB    slots=62017@4.65MiB   codes=193@1.08MiB    nodes=1,247,670@333.73MiB pending=14917
INFO [11-09|11:39:12.835] Forkchoice requested sync to new head    number=15,931,336 hash=c40ab3..e15f5b
INFO [11-09|11:39:15.252] Imported new block headers               count=1    elapsed="290.913µs" number=15,931,336 hash=c40ab3..e15f5b
INFO [11-09|11:39:15.892] Downloader queue stats                   receiptTasks=0    blockTasks=0    itemSize=272.71KiB throttle=962
INFO [11-09|11:39:21.011] State heal in progress                   accounts=25873@1.41MiB    slots=62793@4.71MiB   codes=193@1.08MiB    nodes
`
the node seems synced but not

how do I solve this problem?
thank u

**Comment by s1na** [comment]
Your node hasn't finished syncing. State heal phase is still part of the syncing process. See https://geth.ethereum.org/docs/interface/logs#syncing
