### ISSUE TITLE
Fatal: Error starting protocol stack: listen unix /mnt/f/Quorum1/quorumofficial/QBFT-Network/Node-0/data/geth.ipc: bind: operation not supported

### ISSUE THREAD

**Issue by cse-amarjeet** [ethereum/go-ethereum#26147]
I am trying to create a private network using Quorum (here is the link of Docs that I am following:- https://consensys.net/docs/goquorum/en/latest/tutorials/private-network/create-qbft-network/ ) 

Till step 5 ("Initialize nodes") works fine, but in step 6 when I run this command 

( geth --datadir data --networkid 1337 --nodiscover --verbosity 5 --syncmode full --istanbul.blockperiod 5 --mine --miner.threads 1 --miner.gasprice 0 --emitcheckpoints --http --http.addr 127.0.0.1 --http.port 22000 --http.corsdomain "*" --http.vhosts "*" --ws --ws.addr 127.0.0.1 --ws.port 32000 --ws.origins "*" --http.api admin,eth,debug,miner,net,txpool,personal,web3,istanbul --ws.api admin,eth,debug,miner,net,txpool,personal,web3,istanbul --unlock ${ADDRESS} --allow-insecure-unlock --password ./data/keystore/accountPassword --port 30300 )

I am getting this error (Incorrect Usage. flag provided but not defined: -istanbul.blockperiod) 
![image](https://user-images.githubusercontent.com/93990485/200834178-bd3b708e-2e5d-4c56-acf8-691a7b420e81.png)

then I removed (-istanbul.blockperiod) flag then I run then again and I got this error ((Incorrect Usage. flag provided but not defined: -emitcheckpoints):

![image](https://user-images.githubusercontent.com/93990485/200835376-35205831-b7dd-405a-84df-872809dfe2f6.png)

then I removed  "-emitcheckpoints" flag and run then I got this: 
(Fatal: Error starting protocol stack: listen unix /mnt/f/Quorum1/quorumofficial/QBFT-Network/Node-0/data/geth.ipc: bind: operation not supported)

I don't know where I made the mistake and how to solve This, but I need help, I am not able to figure it out.
any help would be appreciated!!

**Comment by s1na** [comment]
Please create the issue on quorum's [repo](https://github.com/ConsenSys/quorum). They have a fork of Geth. Go-ethereum doesn't have the flag you mentioned.
