### ISSUE TITLE
Old geth clients consuming all my available upload bandwidth

### ISSUE THREAD

**Issue by slothbag** [ethereum/go-ethereum#2616]
#### System information
Ubuntu 14.04 Linux 64bit.

Geth version: 1.4.5
OS & Version: Linux

#### Expected behaviour
testnet usually consumes around 5KB/sec for both up and download

#### Actual behaviour
When connecting to certain peers upload is shooting up to maximum upload bandwith

#### Steps to reproduce the behaviour
Watch your network stats

I have blocked these peers with firewall rules, but it would great to whitelist peer versions via config or CLI args.

**Comment by karalabe** [comment]
This usually means someone's trying to sync from you. The eth protocol is a tit-for-tat. You sync from others, others sync from you. Although older clients pulled a bit more from one select master peer, there's not much protection we can do at this point. With Geth 1.4.6 released this shouldn't be a problem much more as clients upgrade. We can consider additional capping options if this becomes an issue, but I'd rather not introduce artificial caps as it's a whole new can or worms that we really don't want to maintain currently.
