### ISSUE TITLE
When the `noempty` flag useful and what are the consequence of removing it

### ISSUE THREAD

**Issue by guenoledc** [ethereum/go-ethereum#26161]
I have done numerous research on this repo and internet and discord channel and could not figure out this question

I am developing a variation of the consensus Engine and found out that there is a `noempty` parameter that is used in `worker.go` 
 `commitWork()` function.    

There is also the `Worker.noempty` atomic int to control globally this behaviour but it is set by default to true except for development network.

These parameter seem to mean that when the value provided is `false` and `0` an empty block [gets prepared @L1134](https://github.com/ethereum/go-ethereum/blob/6d55908347cac7463dd6a2cb236f30ec26c9a121/miner/worker.go#L1134) but not saved in the state. But few [lines later @L1166](https://github.com/ethereum/go-ethereum/blob/6d55908347cac7463dd6a2cb236f30ec26c9a121/miner/worker.go#L1166) a normal block with whatever available transactions present in the pool (possibly none) gets created and saved in the state.

I found @rjl493456442 comment :

> Just a reminder, noempty doesn't mean it will not generate empty mining block. For example if there is no transaction in pool, then the empty block is still created. But if you set it to 1, it will alway avoid creating the "additional" empty mining block in advance.

Can anyone explain the reason for creating an "additional" empty block with this piece of code and the implication of removing it ? 

For my work the consequence is that the `Engine.FinalizeAndAssemble()` function is called twice for no apparent reason and create extra load.

I have also raised the question on Discord https://discord.com/channels/482467812179181568/482467812816977921/1040613621492875346

**Comment by guenoledc** [comment]
@holiman thanks for this quick feedback

So in a Clique consensus context, this functionality becomes irrelevant, right ?

**Comment by guenoledc** [comment]
@holiman @rjl493456442 

If I change the `Miner.New()` in `miner.go` as follow would that make the core developper ok ?

```golang

func New(eth Backend, config *Config, chainConfig *params.ChainConfig, mux *event.TypeMux, engine consensus.Engine, isLocalBlock func(header *types.Header) bool) *Miner {
	miner := &Miner{
		eth:     eth,
		mux:     mux,
		engine:  engine,
		exitCh:  make(chan struct{}),
		startCh: make(chan common.Address),
		stopCh:  make(chan struct{}),
		worker:  newWorker(config, chainConfig, engine, eth, mux, isLocalBlock, true),
	}

	if _, ok := miner.engine.(consensus.PoW); !ok {
		// We are not in the PoW engine so we don't need the preseal capacity
		miner.DisablePreseal()
	}

	miner.wg.Add(1)
	go miner.update()
	return miner
}
```

**Comment by guenoledc** [comment]
I see, but the challenge is high ☺️

Not knowing enough the mechanics of early GPU processing nor the impact of the Merge on the code, I feel I won't be able.

Thanks anyhow for responding and maybe we'll talk later on this subject or another when my work is done.

**Comment by guenoledc** [comment]
And what about in `backend.go` instead of changing the Miner constructor?

```golang
func (s *Ethereum) StartMining(threads int) error {
...
		var cli *clique.Clique
...
		if cli != nil {
			s.miner.DisablePreseal() // Added here to deactivate the preseal function for clique as it is not needed
			wallet, err := s.accountManager.Find(accounts.Account{Address: eb})
			if wallet == nil || err != nil {
				log.Error("Etherbase account unavailable locally", "err", err)
				return fmt.Errorf("signer missing: %v", err)
			}
			cli.Authorize(eb, wallet.SignData)
		}


....
}
```

**Comment by rjl493456442** [comment]
@guenoledc Yeah, You can explicitly disable "pre-sealing" via call `miner. DisablePreseal` as you did in your own project. But we don't want to include the change to our codebase, since this part of logic needs to be rewrote a bit anyway.

**Comment by guenoledc** [comment]
Hello @rjl493456442 

thanks for the feedback.

Could you also clarify how your team will manage change proposal (say I want to propose an additional consensus derived from clique but keeping clique in the codebase) ?

**Comment by holiman** [comment]
> Could you also clarify how your team will manage change proposal 

Hard to say without a concrete proposal, but generally, we are averse to accepting maintainance overhead, e.g. in the form of code complexity, purely for the benefit of non-ethereum-mainnet downstream projects.

**Comment by guenoledc** [comment]
>  in the form of code complexity, purely for the benefit of non-ethereum-mainnet downstream projects.
I see then I suppose, given that our work intend to be used in a // network running over a modified clique, your don't want this in your codebase (understandable)

So what we should do is maintain a fork of your repo and whenever you do a release merge it with our repo to benefit from the latest fixes on the EVM, network protocol etc.

Right ?
