### ISSUE TITLE
Remove or Replace Dependency on github.com/rjeczalik/notify

### ISSUE THREAD

**Issue by kalverra** [ethereum/go-ethereum#26168]
#### System information

```
❯ geth version
Geth
Version: 1.10.26-stable
Architecture: amd64
Go Version: go1.19.3
Operating System: darwin
```

#### Expected behavior

Develop a project that uses geth as a dependency on a Mac with no errors.

#### Actual behavior

I have a couple of projects that utilize geth as a package, and my main dev environment is on a Mac. Since the latest Mac update, running tests in these projects have produced the below error.

```
cgo-gcc-prolog:217:2: warning: 'FSEventStreamScheduleWithRunLoop' is deprecated: first deprecated in macOS 13.0 - Use FSEventStreamSetDispatchQueue instead. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:1138:1: note: 'FSEventStreamScheduleWithRunLoop' has been explicitly marked deprecated here
```

It seems this error is produced from the [github.com/rjeczalik/notify](http://github.com/rjeczalik/notify) package. There is [an issue](https://github.com/rjeczalik/notify/issues/212) filed, but the project's latest commit was Aug 9, 2021. 

```
❯ go mod why github.com/rjeczalik/notify
# github.com/rjeczalik/notify
github.com/kalverra/crazed-nft-fans/client
github.com/ethereum/go-ethereum/accounts/abi/bind
github.com/ethereum/go-ethereum/accounts/keystore
github.com/rjeczalik/notify
```

#### Steps to reproduce the behaviour

Run tests on any project that uses geth on the latest MacOS update.

**Comment by Donabbaskid** [comment]
> #### System information
> ```
> ❯ geth version
> Geth
> Version: 1.10.26-stable
> Architecture: amd64
> Go Version: go1.19.3
> Operating System: darwin
> ```
> 
> #### Expected behavior
> Develop a project that uses geth as a dependency on a Mac with no errors.
> 
> #### Actual behavior
> I have a couple of projects that utilize geth as a package, and my main dev environment is on a Mac. Since the latest Mac update, running tests in these projects have produced the below error.
> 
> ```
> cgo-gcc-prolog:217:2: warning: 'FSEventStreamScheduleWithRunLoop' is deprecated: first deprecated in macOS 13.0 - Use FSEventStreamSetDispatchQueue instead. [-Wdeprecated-declarations]
> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:1138:1: note: 'FSEventStreamScheduleWithRunLoop' has been explicitly marked deprecated here
> ```
> 
> It seems this error is produced from the [github.com/rjeczalik/notify](https://github.com/rjeczalik/notify) package. There is [an issue](https://github.com/rjeczalik/notify/issues/212) filed, but the project's latest commit was Aug 9, 2021.
> 
> ```
> ❯ go mod why github.com/rjeczalik/notify
> # github.com/rjeczalik/notify
> github.com/kalverra/crazed-nft-fans/client
> github.com/ethereum/go-ethereum/accounts/abi/bind
> github.com/ethereum/go-ethereum/accounts/keystore
> github.com/rjeczalik/notify
> ```
> 
> #### Steps to reproduce the behaviour
> Run tests on any project that uses geth on the latest MacOS update.
https://github.com/ethereum/go-ethereum/issues/26168#issue-1446542873

**Comment by holiman** [comment]
Interesting. It seems syncthing has switched to use github.com/fsnotify/fsnotify, so that might be a good alternative.

**Comment by yantianlei** [comment]
Yes, I tried to modify this project and found that there are many changes, and I am not very familiar with it.

**Comment by smart-t** [comment]
@holiman since I noticed you merged this in the master. I was wondering when the will be tagged? In v1.10.26 I found the reference to the old lib ([link](https://github.com/ethereum/go-ethereum/blob/v1.10.26/go.mod#L50)). Maybe it is me not familiar with your release process?

**Comment by rootulp** [comment]
Since https://github.com/ethereum/go-ethereum/pull/26176 has the milestone [1.11.0](https://github.com/ethereum/go-ethereum/milestone/136), I expect this change to be released in 1.11.0 @smart-t

**Comment by montanaflynn** [comment]
While waiting for 1.11.0 to release a quick fix is to upgrade https://github.com/rjeczalik/notify to `v0.9.3` with:

`go get -u github.com/rjeczalik/notify@v0.9.3`

**Comment by Donabbaskid** [comment]
On Thu, Jan 26, 2023, 4:21 AM Montana Flynn ***@***.***>
wrote:

> While waiting for 1.11.0 to release a quick fix is to upgrade https://g
> <https://github.com/rjeczalik/notify>
>


ithub.com/rjeczalik/notify <https://github.com/rjeczalik/notify> to v0.9.3
