### ISSUE TITLE
IPv6 network support in nat extip doesn't work correctly

### ISSUE THREAD

**Issue by ritave** [ethereum/go-ethereum#26165]
My router assigns me both a local IPv4 address and a public IPv6 one. There's no ability to forwards ports, and so I want to use the IPv6 address as my node location.

That address is publicly accessible as tested using ssh from external location. Yet when I ask geth to use it, it doesn't work as expected and can't connect to any peers.

Address in this issue is randomized.

#### System information

Geth version: `geth version`
```
Geth
Version: 1.10.25-stable
Architecture: amd64
Go Version: go1.19.3
Operating System: linux
GOPATH=
GOROOT=
```

CL client & version: None
OS & Version: `Linux 6.0.7 NixOS from 22.05.4055.fa842715565-x86_64`

#### Expected behaviour

`geth -nat=extip:ff16:90c4:d2b0:fec4:c16b:e1c5:d4ae:46e2` results in IPv6 address used for connections.

#### Actual behaviour

`geth -nat=extip:ff16:90c4:d2b0:fec4:c16b:e1c5:d4ae:46e2` set both `admin.nodeInfo.ip` and `admin.nodeInfo.enode` default to `127.0.0.1` address

**Comment by ritave** [comment]
Ps. I confirm the port 30303 is open and visible from outside.

**Comment by ritave** [comment]
Ok, the issue was that geth can't sync historic blocks without consensus client. With both working in tandem it works perfectly.

The current Ethereum launchpad doesn't reflect those requirements - my assumption was that I could run geth to sync while I set-up the rest of the system. I'd appreciate more clear documentation / errors that geth won't do anything without a consensus client.

**Comment by MariusVanDerWijden** [comment]
Original issue seems okay now. There are a few issues already asking about more documentation for running without a cl client, so I'm going to close this
