### ISSUE TITLE
Automation of private chain nodes deployment

### ISSUE THREAD

**Issue by Gelassen** [ethereum/go-ethereum#26166]
I am working on automation of private chain nodes deployment. By link below you could find my scenario, shell script and current issues. 
https://unix.stackexchange.com/questions/724525/custom-scenario-for-linux-shell-script

There is [a popular question](https://ethereum.stackexchange.com/questions/28703/full-list-of-geth-terminal-command) about a comprehensive overview of Geth API and its abilities, but [JSON RPC API's section in the official documentation](https://geth.ethereum.org/docs/rpc/serverhttps://geth.ethereum.org/docs/rpc/server) looks like the most complete overview of the API. Unfortunately, it doesn't clarify my current issue. 

What I would like to do is automate this part: 

```
$geth attach ipc:node1/data/geth.ipc
$admin.nodeInfo.enode
(reply would be something similar to "enode://64dccd02d5d1166cfb4913f0d0c164dff2b9c61fd55182461010569e15319c7ff5cb4dc8b502e441c38c80ae1b42c2cc95c7e170ed973bb0353d766669c5447c@195.178.22.21:2001?discport=39805")
$geth attach ipc:node2/data/geth.ipc
$admin.addPeer("enode://64dccd02d5d1166cfb4913f0d0c164dff2b9c61fd55182461010569e15319c7ff5cb4dc8b502e441c38c80ae1b42c2cc95c7e170ed973bb0353d766669c5447c@127.0.0.1:2001")
```    
The issue is how to get ```enode``` value from one **geth node's JS console** and put it another one **geth node's console**. Initially I thought to write it into the temp file from one console and read this temp file from another one console, but **geth node's JS console** seems doesn't able to operate with files based on API overview by link above. 

I found out ```geth``` also supports HTTP request from node, if it is able to return ```enode``` value then my automation task would be just running ```curl``` command. Unfortunately, I do not see any existing use cases of interaction with ```admin.nodeInfo.enode``` and ```admin.addPeer(<enode value>)``` over http. Is it possible at all? 

What would be the best option to solve this task? API description like API method, request example, response example would be good to see in docs or at least here. 

Thank you.

**Comment by Gelassen** [comment]
Actually there is a doc which covers piece of requested information: 
https://geth.ethereum.org/docs/rpc/ns-admin#admin_nodeinfo

However I have an issue to execute it properly: 

```
One console: $geth --http --http.port 2001 --http.api admin,personal,eth,net,web3  --datadir ./node1/data
Another console: $curl -X GET http://127.0.0.1:8551 -H "Content-Type: application/json" --data '{"jsonrpc":"2.0", "method":"admin_nodeInfo"}'
```

Curl command tells me 'missing token'. It seems ```curl``` related, not ```geth```, error, but the only token ```curl``` should require is auth token which ```geth``` doesn't require for this request.

**Comment by Gelassen** [comment]
Thank you for spotted a typo in the console command! I'll try it when finish with current task.

**Comment by fjl** [comment]
If you are trying to set up a network of connected nodes with e.g. ansible, you can also pre-generate the node keys and corresponding enode endpoints using the `devp2p` tool.

To create a key, use `devp2p key generate node1.key`. This writes a private key to the file `node1.key`. 

Then you can create the p2p endpoint using `devp2p key to-enr -ip 1.2.3.4 -udp 30303 -tcp 30303 node1.key`. This command outputs a string that can be passed to `addPeer` or the `--bootnodes` flag of geth.

**Comment by Gelassen** [comment]
Thank you for sharing. By `devp2p` do you mean [this one](https://github.com/ethereum/devp2p)? It tells it is a set of protocols, somewhere in docs I noticed it is used as a command, but didn't get any more information about its proper installation and usage. 

```Ansible``` is a modern and powerful instrument, but it adds extra time to learning curve to release in production a project as a whole. If it would be necessary I will switch on it, for now bash script still fits well despite on it is also my first experience with it.

My current issue is I can not receive a response from command: 

```
curl -X GET http://127.0.0.1:2001 -H "Content-Type: application/json" --data '{"jsonrpc":"2.0", "method":"admin_nodeInfo"}'
```
when my node is running:
```
 geth --http --http.port 2001 --http.api admin,personal,eth,net,web3  --datadir ./node1/data
```

This command is just executed and that's it. 

Later this node info should be sent on node probably like this (haven't found it covered in the docs): 
```
$curl -X POST http://127.0.0.1:2001 -H "Content-Type:application/json" --data '{"jsonrpc": "2.0", "method":"admin_addPeer", "params":["enode://64dccd02d5d1166cfb4913f0d0c164dff2b9c61fd55182461010569e15319c7ff5cb4dc8b502e441c38c80ae1b42c2cc95c7e170ed973bb0353d766669c5447c@127.0.0.1:2001"]}' 

Could you please help me with either with devp2p installation and execution documentation or make all this required steps by rpc calls via curl?

**Comment by s1na** [comment]
You need to add an ID to your request, e.g. `{"jsonrpc":"2.0", "id": 1, "method":"admin_nodeInfo"}`

**Comment by Gelassen** [comment]
Thank you, I had got a response when id was passed.

**Comment by s1na** [comment]
Can I close the issue or do you need more help?

**Comment by fjl** [comment]
@Gelassen Regarding the `devp2p` tool: I meant the executable which is shipped as part of go-ethereum. You can build it using `make all` in go-ethereum. The tool will then be available as `build/bin/devp2p`.

**Comment by Gelassen** [comment]
@s1na, could you please leave it open a bit longer? This piece of code haven't automated yet and it would be good to have an open issue to clarify some points in case of any.

@fjl, thank you for details. Current [documentations says](https://geth.ethereum.org/docs/install-and-build/installing-geth) there is an option to do ```geth``` installation over PPA's and I used this way at the beginning. Now I read it also should install ```devp2p```:

> Then, to install the stable version of go-ethereum:

sudo apt-get update
sudo apt-get install ethereum

Or, alternatively the develop version:

sudo apt-get update
sudo apt-get install ethereum-unstable

These commands install the core Geth software and the following developer tools: clef, devp2p, abigen, bootnode, evm, rlpdump and puppeth. The binaries for each of these tools are saved in /usr/local/bin/. 

However I don't see any packages in ``` /usr/local/bin/```. I use clean VM and stable ```ethereum version```.  ```ethereum-unstable``` might provide it. 

I return back to it when the first approach ends wouldn't be effective.

**Comment by fjl** [comment]
I think the commands are installed in `/usr/bin` by the PPA package.

**Comment by Gelassen** [comment]
I have an issue with RPC ```add_Peer``` command. The response is:
```
geth invalid enode: missing 'enr:' prefix for base64-encoded record
```
The curl command looks as:
```
node1_endpoint="${node1_enode_id}@${NODE_IP}:${NODE2_PORT}"

echo "${node1_endpoint}"

curl -X POST http://$NODE_IP:$NODE2_PORT -H "Content-Type:application/json" --data '{"jsonrpc": "2.0", "method":"admin_addPeer", "id":1, "params":["$node1_endpoint"]}'
```

where is ```node`_endpoint``` is: 
```
enode://34d0344eacfdc2b80fcce4f787c74846851623ca57c7becbaf2102e95f36fe429a2aa2e6778de72fc0a66929565ee874292d9d88eaf05ed2cacde3202f568bf2@127.0.0.1:2001
``` 
Quick research shows this error response is usually referred to missed ```enode``` prefix, but as you see ```enode``` prefix is correct. 

Do you see an issue here? My WIP with bash script is [available here](https://gist.github.com/Gelassen/2815de4bcf4275ab992e1dd5dc022248) for reference.

**Comment by fjl** [comment]
It's a shell quoting issue in your script. You are trying to put the reference `$node1_endpoint` into a single-quoted string in your curl command.

**Comment by Gelassen** [comment]
Thank you for all your help with my issue. I understand.
