### ISSUE TITLE
docs: todo remove stale cross-compile info

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#26175]
Confusing/stale  page: https://geth.ethereum.org/docs/install-and-build/cross-compile
More context info: https://github.com/ethereum/go-ethereum/issues/26170

**Comment by holiman** [comment]
cc @jmcook1186

**Comment by MariusVanDerWijden** [comment]
closed by https://github.com/ethereum/go-ethereum/pull/26204
