### ISSUE TITLE
Unable to cross-compile Geth on Ubuntu

### ISSUE THREAD

**Issue by BohemiaLai** [ethereum/go-ethereum#26170]
I was trying to complile Geth for Windows platform, and an error keeping my fail to compile in Build.

Wasn't sure what went wrong, can anyone can advice me on this? thanks.

Following the steps in the below for the instruction that I followed.
https://geth.ethereum.org/docs/install-and-build/cross-compile

xgo --deps=https://gmplib.org/download/gmp/gmp-6.0.0a.tar.bz2  \ github.com/ethereum/go-ethereum/cmd/geth
Checking docker installation...
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.3
 Git commit:        20.10.12-0ubuntu4
 Built:             Mon Mar  7 17:10:06 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.3
  Git commit:       20.10.12-0ubuntu4
  Built:            Mon Mar  7 15:57:50 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu3
  GitCommit:        
 runc:
  Version:          1.1.0-0ubuntu1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:  

go: finding github.com/russross/blackfriday/v2 v2.1.0
go: finding github.com/influxdata/line-protocol v0.0.0-20210311194329-9aa0e372d097
go: finding github.com/deepmap/oapi-codegen v1.8.2
go: finding golang.org/x/sync v0.0.0-20220722155255-886fb9371eb4
go: finding golang.org/x/net v0.1.0
go: finding golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: finding github.com/opentracing/opentracing-go v1.1.0
go: finding gopkg.in/yaml.v2 v2.4.0
build github.com/ethereum/go-ethereum/cmd/geth: cannot load embed: malformed module path "embed": missing dot in first path element
2022/11/13 02:50:20 Failed to cross compile package: exit status 1.

**Comment by holiman** [comment]
The docs at https://geth.ethereum.org/docs/install-and-build/cross-compile describes how to use @karalbe's [xgo](https://github.com/karalabe/xgo) to cross-compile. However, xgo has been archived, and is now readonly. Last change was in 2019, when Go `1.13` was the latest. So it's pretty safe to say that xgo cross compiler is outdated, and by extension the cross-compilation pages you were looking at. 

Regarding how to cross-compile nowadays, I think @fjl or @karalabe might offer insights.

**Comment by BohemiaLai** [comment]
appreciate your reply and hope @fjl or @karalabe can advise me on this

**Comment by fjl** [comment]
For cross-compilation to a Linux target from a Linux host, you can use our ci tool. Here's how we do it for ARM

```
sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-arm-linux-gnueabi libc6-dev-armel-cross gcc-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-aarch64-linux-gnu libc6-dev-arm64-cross

go run build/ci.go install -dlgo -arch arm -cc arm-linux-gnueabi-gcc
```

The `-dlgo` flag is optional. If you use it, a recent version of Go will be downloaded and used for compilation.

**Comment by BohemiaLai** [comment]
> For cross-compilation to a Linux target from a Linux host, you can use our ci tool. Here's how we do it for ARM
> 
> ```
> sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-arm-linux-gnueabi libc6-dev-armel-cross gcc-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-aarch64-linux-gnu libc6-dev-arm64-cross
> 
> go run build/ci.go install -dlgo -arch arm -cc arm-linux-gnueabi-gcc
> ```
> 
> The `-dlgo` flag is optional. If you use it, a recent version of Go will be downloaded and used for compilation.

Thanks and can you also share the script for compile windows platform too?

Moreover, do you know if I can use the same ci too to compile other geth folk like matic and ftm chain?

**Comment by fjl** [comment]
> Moreover, do you know if I can use the same ci too to compile other geth folk like matic and ftm chain?

We have no way of cross-compiling binaries for Windows on a non-Windows host at this time. Compilation to OS different from host with ci.go is not tested/implemented. You can try your luck with modifying ci.go and using a MinGW toolchain.

> Moreover, do you know if I can use the same ci too to compile other geth folk like matic and ftm chain?

build/ci.go is provided in the go-ethereum repository for the purpose of building this project. If another project is forked from go-ethereum, they may or may not provide this script. We cannot give any guarantees about other projects.

**Comment by fjl** [comment]
We compile it on Windows.
