### ISSUE TITLE
docs: network ID is not chain ID

### ISSUE THREAD

**Issue by darren** [ethereum/go-ethereum#26188]
https://github.com/ethereum/go-ethereum/blob/ae42148093fdfd72749ff3dda2b986cef543510f/ethclient/ethclient.go#L323-L335

[EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) introduced using the chain ID as part of the transaction signing process to protect against transaction replay attacks.

 network ID is not necessarily the same as chain ID (eg: ganache),  I think the doc here is somewhat misleading.

**Comment by ligi** [comment]
I agree - this is misleading - changed in #26189
