### ISSUE TITLE
Warn : Served eth_sendRawTransaction | insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by ekawibisono** [ethereum/go-ethereum#26185]
Hello,
Please help, I'm having problems with my geth, when I run it, a warning appears like the image below, I've been looking for the problem but can't find it.

Please help

![Screenshot 2022-11-15 203404](https://user-images.githubusercontent.com/22586872/201935407-de0c1f9b-88a4-4c7b-ba74-0fab5ba04f80.png)

I Using Geth Version 1.10.26

This manual Build me

> geth 	--datadir=node1/ \
> 	    --syncmode 'full' \
> 		--port 30310 \
> 		--networkid 14093 \
> 		--http \
> 		--http.addr 0.0.0.0 \
> 		--http.corsdomain '*' \
> 		--http.port 8545 \
> 		--http.vhosts '*' \
> 		--http.api admin,eth,miner,net,txpool,personal,web3,debug \
>         --ws.api eth,net,web3,debug,txpool \
>         --ws \
>         --ws.addr 0.0.0.0 \
>         --ws.port 8455 \
>         --ws.origins '*' \
> 		--mine \
>         --miner.gasprice 1000000000 \
> 		--miner.gaslimit 8000000 \
> 		--cache 1024 \
> 		--verbosity 3 \
> 		--allow-insecure-unlock \
> 		--unlock "xxxxx" \
> 		--password password.txt

**Comment by ekawibisono** [comment]
Served eth_sendRawTransaction            conn=139.99.90.122:25620 reqid=6781354291429 duration="374.261µs" err="insufficient funds for gas * price + value"

**Comment by ligi** [comment]
seems someone used the RPC to send a raw transaction that is invalid - I see no actionable change that could be done here - what do you suggest?

**Comment by ekawibisono** [comment]
> seems someone used the RPC to send a raw transaction that is invalid - I see no change that could be done here - what do you suggest?

So yesterday I checked and it turns out that it was my geth account that caused such a problem, but after that it's still the same, for now I'm still trying to start over again, maybe any suggestions from you?

**Comment by ekawibisono** [comment]
![image](https://user-images.githubusercontent.com/22586872/202236646-1172dd2f-1116-4533-a355-cd350dcc7ae7.png)
After finishing with this problem, I got a new problem, which is an error in the transaction block as shown above, can anyone help?

**Comment by ekawibisono** [comment]
![image](https://user-images.githubusercontent.com/22586872/202301794-fd1682f0-062c-43d5-af31-ba8ae9888448.png)

I found another problem, namely eth_call, so when I want to make a token transaction it suddenly appears as drawn, can anyone help me?

**Comment by ekawibisono** [comment]
@holiman Can you tell me how to make an ABI file of the contract?

**Comment by holiman** [comment]
The compiler generates the abi output. You tell it to compile a solidity-file, and it has various output options. It's not my field of expertise, however. 

You probably want to checkout the `UniswapV2Router` documentation, and there you will probably find what the error is.

**Comment by ekawibisono** [comment]
@holiman I've compiled UniswapV2Router, but the results are still the same, and the error still occurs.

![image](https://user-images.githubusercontent.com/22586872/202487912-22ab8f54-b365-499f-9b95-d138fd2b2075.png)
