### ISSUE TITLE
Synchronization error

### ISSUE THREAD

**Issue by panicape** [ethereum/go-ethereum#2619]
Geth version: `v1.5.0-unstable`
OS & Version: Ubuntu15.10

I had to stop synchronization but when i try to start again the node, it doesn't do anything, so i remove the blockchain to let the node to creat it again and it doesn't do anything, it only says that it starts from a Block to sychronize but in fact the blockchain is empty, how can i fix both things?

**Comment by karalabe** [comment]
Please try with the latest 1.4.6 release. It received a full sync overhaul. Should be a lot stabler. I'd also suggest syncing using `geth --fast`.

**Comment by panicape** [comment]
Hi, thanks for the help, it was some blocking policies of the network, i tried again outside the place i was trying to do it and it started to synchronize again
