### ISSUE TITLE
Inconsistent hashes for DynamicFeeTx transactions (core/types)

### ISSUE THREAD

**Issue by ArnaudBrousseau** [ethereum/go-ethereum#26199]
#### System information
OS & Version: OSX
Commit hash : `add337e0f7bad02f3cf535c66cd31f252b0b5c99` (latest master)

#### In short, what's wrong?
When attempting to compute a tx hash for `DynamicFeeTx` transactions (for signing purposes), the two methods available (transaction.Hash, signer.Hash(tx)) aren't yielding the same hashes. The (subtle) difference(s) in the hashes' pre-images makes me believe this is a bug rather than intended behavior, but please let me know if that's not the case!

#### Steps to reproduce

I've written a small failing test to capture this:
```diff
diff --git a/core/types/transaction_test.go b/core/types/transaction_test.go
index 4b96c6b91..bc939d2eb 100644
--- a/core/types/transaction_test.go
+++ b/core/types/transaction_test.go
@@ -532,6 +532,31 @@ func assertEqual(orig *Transaction, cpy *Transaction) error {
 	return nil
 }
 
+func TestHashConsistencyForDynamicFeeTx(t *testing.T) {
+	to := common.HexToAddress("0x40f008f4c17075EFcA092aE650655f6693AECEd0")
+
+	tx := NewTx(&DynamicFeeTx{
+		ChainID:   big.NewInt(1),
+		Nonce:     0,
+		GasTipCap: big.NewInt(1000000000),
+		GasFeeCap: big.NewInt(1000000000),
+		Gas:       21000,
+		To:        &to,
+		Value:     big.NewInt(50000000000000000),
+	})
+
+	signer := NewLondonSigner(tx.ChainId())
+	signerHash := fmt.Sprintf("%02x", signer.Hash(tx).Bytes())
+	txHash := fmt.Sprintf("%02x", tx.Hash().Bytes())
+
+	if signerHash != txHash {
+		t.Errorf("hashes do not match: signer.Hash(tx) (%s) != tx.Hash() (%s)", signerHash, txHash)
+	}
+
+	// FIXME! This test is failing with:
+	// hashes do not match: signer.Hash(tx) (a1b1869ac0c5e3b26d98f2aaf29e7d973d80bc71c6d3deb7550838e28d48d700) != tx.Hash() (66c7075fdbac0dcd08c9d8fc2d981fb4791702247d38d2d5f5a9a917a38089a6)
+}
+
 func TestTransactionSizes(t *testing.T) {
 	signer := NewLondonSigner(big.NewInt(123))
 	key, _ := crypto.HexToECDSA("b71c71a67e1177ad4e901695e1b4b9ee17ae16c6668d313eac2f96dbcda3f291")
```

#### More details / speculation
Taking the failing test output values as an example, we have:
|        | `signer.Hash(tx)` | `tx.Hash()` |
|---|----|----|
| hash value | `a1b1869ac0c5e3b26d98f2aaf29e7d973d80bc71c6d3deb7550838e28d48d700` | `66c7075fdbac0dcd08c9d8fc2d981fb4791702247d38d2d5f5a9a917a38089a6` | 
| pre-image |  `02ee0180843b9aca00843b9aca008252089440f008f4c17075efca092ae650655f6693aeced087b1a2bc2ec5000080c0` | `02f10180843b9aca00843b9aca008252089440f008f4c17075efca092ae650655f6693aeced087b1a2bc2ec5000080c0808080` |
| source | [londonSigner.Hash](https://github.com/ethereum/go-ethereum/blob/a007ab786cc0feaf304d767af9f4e3fc4eb79d72/core/types/transaction_signing.go#L220-L237) | [transaction.Hash](https://github.com/ethereum/go-ethereum/blob/c4a662176ec11b9d5718904ccefee753637ab377/core/types/transaction.go#L360-L373) |

(to double-check the pre-images in the table above, head to https://emn178.github.io/online-tools/keccak_256.html)

The two differences in the hashes' pre-images are:
* The tx hash pre-image ends with extra 3 bytes ("808080") -> I believe this encodes 3 extra signature-related values: r=0, s=0, v=0
* tx hash starts with `02f1`, vs  `02ee` vs `02f1` -> explained by the above: `f1` = `ee` + 3 in hex (we have 3 extra values/bytes to RLP encode: r, s, and v)

Last note: speculating, but I'd bet `signer.Hash(tx)` is the correct hash to use. The `tx.Hash()` pre-image seems fishy with the last 3 bytes (`808080`) encoding a non-existent signature.

**Comment by holiman** [comment]
This was an interesting case. 
My repro
```
func TestFoo(t *testing.T) {
	tx := NewTx(&DynamicFeeTx{
		ChainID:   big.NewInt(1),
		Nonce:     0,
		GasTipCap: big.NewInt(100),
		GasFeeCap: big.NewInt(100),
		Gas:       100,
		To:        nil,
		Value:     big.NewInt(100),
	})
	signer := NewLondonSigner(tx.ChainId())
	fmt.Printf("hash: %v\n", signer.Hash(tx))
	fmt.Printf("hash: %v\n", tx.Hash())
}
```

So, looking at what actually goes into the rlp-encoding of the hashes,
```
prefixedRlpHash 2 c90180646464806480c0
hash: 0x1ddfb87615d4ad987d213a43adbcc61db1d0a46d00286588475cd9ed6294ca89
prefixedRlpHash 2 cc0180646464806480c0808080
hash: 0x52c70c2aedc3e19731cf46bc6390fc86cc8952b9e200c2f68446452d1f266296
```
So the  `signer.Hash` uses `c90180646464806480c0, the `tx.Hash` uses `cc0180646464806480c0808080`. 

Looking at the method docs for `signer.Hash` reveals: 

> Hash returns 'signature hash', i.e. the transaction hash that is signed by the
> private key. This hash does not uniquely identify the transaction.


The hash _that is signed_ does not include the `v`, `r`, `s` - values, since those are what is added by the signing function. Whereas, the `tx.Hash` encompasses _all_ the fields, including the ones containing the signature.

**Comment by ArnaudBrousseau** [comment]
@holiman thanks for looking into this! I agree with you: the hash of an unsigned transaction should not be based on a pre-image which includes `v`, `r`, `s`. The current APIs have too many sharp edges IMO:
* `signer.Hash`: correct hash to be signed by a remote signer. _Signing this hash will result in a valid transaction!_ ✅ 
* `tx.Hash()`: incorrect from the POV of a remote signer. Is this hash useful for unsigned transactions? I can see the use case for a **signed** transaction, but for an unsigned transaction, it's weird to include nullified `r`, `s`, and `v` values in the RLP encoding used to compute the hash. _Signing this hash results in an invalid signature!_ 🔴 
* `tx.MarshalBinary()`: also incorrect from the POV of a remote signer, since it yields the pre-image of `tx.Hash()` (`02cc0180646464806480c0808080` in your minimal repro). In other words, if I take this value, apply keccak256 on it, I get `tx.Hash()`, not `signer.Hash()`. _Signing this results in an invalid signature!_ 🔴 

Assuming `tx.Hash()` and `tx.MarshalBinary()` have use-cases for unsigned payloads as-they-are (I'm being generous), I find myself missing a `signer.HashPreImage(...)` method. Something that yields `02c90180646464806480c0` (the payload to sign). That's precious for a remote signer (compared to a hash) because this payload can be decoded, and context information can be inferred from it (destination, amount for example)

The best I can come up with right now to get the "payload to sign" from an unsigned transaction:
```
func HashPreImage(unsignedTx *Transaction) {
    innerRLP, _ := rlp.EncodeToBytes(
        []interface{}{
            tx.ChainId(),
            tx.Nonce(),
            tx.GasTipCap(),
            tx.GasFeeCap(),
            tx.Gas(),
            tx.To(),
            tx.Value(),
            tx.Data(),
            tx.AccessList(),
        },
    )
    hashPreImage := []byte{tx.Type()}
    hashPreImage = append(hashPreImage, innerRLP...)
    return hashPreImage
}
```

What do you think? Is there a better way to accomplish what I want to do here? Worth a PR to add this method to the different signers?
