### ISSUE TITLE
Unable to sync - NewPayloadV1: inserting block failed error="invalid gas used (remote: 20098221 local: 20110095)" 

### ISSUE THREAD

**Issue by 5a3ee** [ethereum/go-ethereum#26205]
#### System information

Geth
Version: 1.10.26-stable
Git Commit: e5eb32acee19cc9fca6a03b10283b7484246b15a
Architecture: amd64
Go Version: go1.18.5
Operating System: linux
GOPATH=
GOROOT=go

Linux 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Lighthouse v3.2.1-6d5a2b5
BLS library: blst-modern
SHA256 hardware acceleration: false
Specs: mainnet (true), minimal (false), gnosis (true)

#### Expected behaviour

Syncing should happen without errors. Issue without action from my part 24 hours ago. Restarted eth and lighthouse beacon and validator without success. 

Restarting geth makes it look for peers again, but I cannot see from the logs that it ever starts syncing. I have 41 (tried 43) peers currently - shouldn't it start syncing with that many? 

`eth.syncing` returns `false`. 

#### Actual behaviour

Unable to sync.
#### Steps to reproduce the behaviour

Start Geth.

[out.log](https://github.com/ethereum/go-ethereum/files/10030855/out.log)

**Comment by rjl493456442** [comment]
Your consensus client is pushing an invalid payload to you. Maybe it's some issues in consensus layer client. Can you share a bit more logs from Geth side?

**Comment by holiman** [comment]
No response, closing this.
