### ISSUE TITLE
How to make Geth sync faster with consensus layer?

### ISSUE THREAD

**Issue by FahdW** [ethereum/go-ethereum#26209]
With the introduction of consensus layer my Geth never stops syncing and i am unable to query the latest block from it. Prior to merge it was working fine but now when I try and sync it just never gives the correct latest block. Always returning 0

Geth 1.10.23 
I have been syncing since pre merge, it just never catches up

**Comment by rjl493456442** [comment]
You may want to upgrade your Geth to the latest stable version(v.1.10.26) which we introduce some changes for improving sync. And there is nothing relevant with consensus layer regarding with the sync speed. CL only issues an event for triggering the sync and then Geth is responsible for the remaining procedure.

**Comment by rjl493456442** [comment]
Yes, and please put some logs here in case it's still not working.

**Comment by MariusVanDerWijden** [comment]
This seems fixed, syncmode=full on mainnet is very slow and you will always see block 0 as latest block until the node is fully synced in snap sync
