### ISSUE TITLE
Error in block freeze operation

### ISSUE THREAD

**Issue by wns-link** [ethereum/go-ethereum#26206]
#### System information

Geth version: `geth 1.10.26`
CL client & version: lighthouse v3.2.1
OS & Version: Linux Debian 10

geth_1         | INFO [11-17|12:52:24.377] Generating state snapshot                root=887ca2..bf0ca8 in=0062c1..a40ae4 at=160c1b..a4b6c0 accounts=278,273 slots=1,409,905 storage=114.17MiB dangling=0 elapsed=7m31.616s  eta=118h29m3.28s          
geth_1         | WARN [11-17|12:52:28.526] Truncating freezer table                 database=/root/geth/chaindata/ancient table=headers  items=14,630,885 limit=14,603,461                                                                             
geth_1         | WARN [11-17|12:52:28.527] Truncating freezer table                 database=/root/geth/chaindata/ancient table=bodies   items=14,633,417 limit=14,603,461                                                                             
geth_1         | WARN [11-17|12:52:28.608] Truncating freezer table                 database=/root/geth/chaindata/ancient table=receipts items=14,633,365 limit=14,603,461                                                                             
geth_1         | ERROR[11-17|12:52:28.650] Error in block freeze operation          err="block receipts missing, can't freeze block 14633459"

**Comment by s1na** [comment]
Possibly duplicate of https://github.com/ethereum/go-ethereum/issues/26091, https://github.com/ethereum/go-ethereum/issues/25960, and https://github.com/ethereum/go-ethereum/issues/25913.

**Comment by ziadghali2** [comment]
how to reproduce this issue

**Comment by wns-link** [comment]
> how to reproduce this issue

It should be related to the abnormal exit. Re-synchronizing from 0 did not find this problem

**Comment by fjl** [comment]
Also possibly related:  #22374
