### ISSUE TITLE
sync bug?

### ISSUE THREAD

**Issue by csquan** [ethereum/go-ethereum#26226]
refer to :
suppose node A-validator,node B-sync node ,
B sync from A,A stop at height 200 but B is running.
A rollback at height 100(use export 0-100 and import),when A is start up ,
what happened to A sync behavior?
I have done test to citify that A will sync from B get blocks 100-200,
but that blocks is rollbacked, I do not want blocks 100-200
is sync bug here?

**Comment by fjl** [comment]
Please explain your question in more detail.
