### ISSUE TITLE
missing trie node after prune?

### ISSUE THREAD

**Issue by csquan** [ethereum/go-ethereum#26233]
I have get error "missing trie node" after prune successful when I start miner.
does prune does some damage to db?

**Comment by csquan** [comment]
Geth version: 1.10.25
OS & Version: OSX
prune is ok, but when I start mine, error happened:"missing trie node "

**Comment by rjl493456442** [comment]
Can you elaborate how do you prune your node? Is `geth snapshot prune-state` or some other commands?

And can you post some post-pruning logs here?

**Comment by csquan** [comment]
csquan@csquandeMacBook-Pro testchain1 % ./geth --datadir ./data1  snapshot prune-state
INFO [11-22|16:40:34.982] Maximum peer count                       ETH=50 LES=0 total=50
INFO [11-22|16:40:34.984] Set global gas cap                       cap=50,000,000
INFO [11-22|16:40:34.984] Allocated cache and file handles         database=/Users/csquan/testchain1/data1/geth/chaindata cache=512.00MiB handles=5120
INFO [11-22|16:40:35.121] Opened ancient database                  database=/Users/csquan/testchain1/data1/geth/chaindata/ancient/chain readonly=false
INFO [11-22|16:40:35.135] Initialized state bloom                  size=2.00GiB
INFO [11-22|16:40:35.136] Selecting bottom-most difflayer as the pruning target root=a8aa74..4733b4 height=1166
INFO [11-22|16:40:35.138] Deleted trie clean cache                 path=/Users/csquan/testchain1/data1/geth/triecache
INFO [11-22|16:40:35.138] Iterating state snapshot                 accounts=0 slots=0 elapsed="238.708µs"
INFO [11-22|16:40:35.139] Iterated snapshot                        accounts=2 elapsed="624.458µs"
INFO [11-22|16:40:35.139] Writing state bloom to disk              name=/Users/csquan/testchain1/data1/geth/statebloom.0xa8aa74cb76434001e2c7c0a09da82a0efe2f762349cd5b40ece7d44c2f4733b4.bf.gz
INFO [11-22|16:40:47.639] State bloom filter committed             name=/Users/csquan/testchain1/data1/geth/statebloom.0xa8aa74cb76434001e2c7c0a09da82a0efe2f762349cd5b40ece7d44c2f4733b4.bf.gz
INFO [11-22|16:40:47.656] Pruned state data                        nodes=4133 size=431.19KiB elapsed=17.159ms
INFO [11-22|16:40:47.657] State pruning successful                 pruned=431.19KiB elapsed=12.519s

**Comment by rjl493456442** [comment]
Please also provide the log with "missing trie node" errors after restart.

**Comment by holiman** [comment]
> In this case, it would be relevant to provide logs from both the pruning-session, **and the session which reports the missing trie node errors.**

**Comment by csquan** [comment]
> miner.start()
INFO [11-25|15:13:04.521] Transaction pool price threshold updated price=1,000,000,000
null
> ERROR[11-25|15:13:04.521] Failed to mint the block                 err="missing trie node 0x1de9e9d89e088166a7303546eb550cf00dd3d4174a5fc8480c51e79f2fc72462 (owner \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00epoch)"

**Comment by holiman** [comment]
"Failed to mint the block" is not an error message that go-ethereum has. 

Perhaps you are using one of these: https://github.com/search?p=3&q=%22Failed+to+mint+the+block%22&type=Code  ?

**Comment by csquan** [comment]
I run prune after gracely stop command"./geth  --datadir ./data2  --ipcdisable --port 61910  -authrpc.port 8551 --syncmode=snap console",it seems some error
csquan@csquandeMacBook-Pro testprune % ./geth --datadir ./data2  snapshot prune-state
INFO [11-25|15:46:15.645] Maximum peer count                       ETH=50 LES=0 total=50
INFO [11-25|15:46:15.647] Set global gas cap                       cap=50,000,000
INFO [11-25|15:46:15.648] Allocated cache and file handles         database="/Users/csquan/testprune/data2\u00a0/geth/chaindata" cache=512.00MiB handles=5120
INFO [11-25|15:46:15.752] Opened ancient database                  database="/Users/csquan/testprune/data2\u00a0/geth/chaindata/ancient/chain" readonly=false
ERROR[11-25|15:46:15.753] Failed to open snapshot tree             err="Failed to load head block"
INFO [11-25|15:46:15.753] Freezer shutting down 
Failed to load head block

**Comment by holiman** [comment]
Ah, so it's your own fork: https://github.com/csquan/dpos_ethereum/blob/8108441f39aae7457e3f3f5f119c95f849b3a881/miner/worker.go#L220 ? 

You have a downstream fork of go-ethereum, and you are experiencing issues with that fork. It's not very nice to file reports with go-ethereum, and pretend that you are using our code (version `1.10.25`), when in fact you are not, making us spend time trying to figure out your problems for you.

We do not provide support for downstream forks.
