### ISSUE TITLE
sync stuck at IPC endpoint opened

### ISSUE THREAD

**Issue by ZhidanDeng** [ethereum/go-ethereum#26239]
I try to sync with full mode, but stuck at IPC endpoint opened
![image](https://user-images.githubusercontent.com/89714583/203472218-d1658010-c473-4505-a76a-3f233d00eafa.png)

it stuck a whole night and I got something this morning like this:
![image](https://user-images.githubusercontent.com/89714583/203473906-a2739ac2-2b53-4a97-be22-1fdf85976102.png)

then I try the '--verbosity 4' to get details:
![image](https://user-images.githubusercontent.com/89714583/203472327-efc80770-e024-4adf-938e-a08acced47c3.png)

What should I do to make it work？Thanks in advance.

**Comment by holiman** [comment]
I'm not sure what version you are using, but it says nothing about TTD block or the merge, so I'm guessing it's a fairly old version?

Nowadays, you need a CL client to 'guide' the EL (geth) about what block is the head block. 

Please see https://geth.ethereum.org/docs/interface/consensus-clients
-----------------
ps. For `syncmode=full`, it is _possible_ to sync without a CL node, by providing a head-block yourself. But that's probably _not_ what you want to do. 
```
$ geth --help | grep target
    --synctarget value            
          File for containing the hex-encoded block-rlp as sync target(dev feature)
```
