### ISSUE TITLE
not sync

### ISSUE THREAD

**Issue by blcokchina110** [ethereum/go-ethereum#26230]
![image](https://user-images.githubusercontent.com/99483895/203227176-f7d9515f-673f-4339-aadb-0ca5d154afbd.png)

Dropping unsynced node during sync  , not syncing!!

**Comment by s1na** [comment]
Do you have a beacon client and is it synced? Please see https://geth.ethereum.org/docs/interface/consensus-clients

**Comment by holiman** [comment]
> Please see https://geth.ethereum.org/docs/interface/consensus-clients
