### ISSUE TITLE
Metrics not starting

### ISSUE THREAD

**Issue by quickchase** [ethereum/go-ethereum#26244]
#### System information

```
Geth
Version: 1.10.26-stable
Git Commit: e5eb32acee19cc9fca6a03b10283b7484246b15a
Architecture: amd64
Go Version: go1.18.6
Operating System: linux
GOPATH=
GOROOT=go
```

Built from source via `git checkout v1.10.26`

#### Expected behaviour
Metrics server starts

#### Actual behaviour
Metrics server does not start

#### Steps to reproduce the behaviour
I'm running a Goerli node and my systemd file contains this:
```
--metrics --metrics.port=6060 --pprof --pprof.port=6061
```

Then, check the listening ports:
```
# netstat -lnp | grep 606
tcp        0      0 127.0.0.1:6061          0.0.0.0:*               LISTEN      45045/geth
```

I have tried changing the port, I have tried changing the `--metrics.addr`, I also tried removing the pprof thinking maybe there's a conflict, but no matter what I do, there's no indication that the metrics server is running in the logs, and the port is never opened.

#### Backtrace
No logs related to Metrics show up

**Comment by holiman** [comment]
I think you need to also use `--metrics`

**Comment by holiman** [comment]
So, apparently
```
INFO [11-23|20:37:47.717] whoa                                     ctx.IsSet(MetricsHTTPFlag.Name)=false ctx.String(MetricsHTTPFlag.Name)=127.0.0.1
```
Even though the `value` is set ( by default), to `127.0.0.1`, the `IsSet` operation fails.

**Comment by holiman** [comment]
A workaround is to use `--metrics.addr`: 

```
geth --dev --metrics --metrics.port=6060 --metrics.addr=127.0.0.1
```

**Comment by quickchase** [comment]
> A workaround is to use `--metrics.addr`:
> 
> ```
> geth --dev --metrics --metrics.port=6060 --metrics.addr=127.0.0.1
> ```

Are you sure it's working, I swear I tried that and it did not work

> I have tried changing the --metrics.addr

But I'm afk, so will check soon.

**Comment by holiman** [comment]
The `--metrics.addr` has a  "default" value of `127.0.0.1`, however, that's not quite true. Geth internally requires that the flag is explicitly set as command line param, otherwise ignores it. 

Since metrics can be exported in several ways -- most commonly an external e.g. influx database, geth does not default to exposing them over `127.0.0.1`, even though the `geth -h` indicates that. 

So the fix is to supply the `--metrics.addr` argument. On our side, we need to fix so we do not fool users by pretending that the parameter is already set by default.

**Comment by quickchase** [comment]
Guys, I set:
```
--metrics --metrics.port=6060 --metrics.addr=127.0.0.1
```

netstat still does not show port 6060 listening...

**Comment by fjl** [comment]
It works for me:

```
~/d/e/s/g/e/go-ethereum >> ./build/bin/geth --metrics --metrics.addr 127.0.0.1
INFO [11-27|13:19:48.983] Starting Geth on Ethereum mainnet...
INFO [11-27|13:19:48.984] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [11-27|13:19:48.984] Enabling metrics collection
INFO [11-27|13:19:48.984] Enabling stand-alone metrics HTTP endpoint address=127.0.0.1:6060
INFO [11-27|13:19:48.984] Starting metrics server                  addr=http://127.0.0.1:6060/debug/metrics
```

**Comment by fjl** [comment]
Can you post your full command line please?

**Comment by thevops** [comment]
I had a similar issue. I tried to map variables from format: `<param_name>:<param_value>` to: `--<param_name>:<param_value>`.
But there are some parameters without values e.g. `--metrics`, so I used `true` as value.
It works for all other parameters except for metrics.
I had to change it and pass `--metrics`, but not `--metrics=true`.

**Comment by fjl** [comment]
I see. This happens because the metrics package enables itself by scanning the command line for this flag.
