### ISSUE TITLE
PendingBlockNumber  in DoEstimateGas is bug?

### ISSUE THREAD

**Issue by csquan** [ethereum/go-ethereum#26249]
```
Geth version: 1.10.25
OS & Version: OSX
```

code:
```
pendingBlockNr := rpc.BlockNumberOrHashWithNumber(rpc.PendingBlockNumber)
estimated, err := DoEstimateGas(ctx, b, callArgs, pendingBlockNr, b.RPCGasCap())
```

I start several nodes to run a private network, everything is fine.
when I use first to do tx of an account, it always error:"insufficient...",but it have money which I had check in  getBalance().
then I get the break point,I think rpc.PendingBlockNumber is not right here?
because getbalance is right which use rpc.latestblockNumber

**Comment by csquan** [comment]
It become fine when restart .I have met every time ,is that bug?

**Comment by csquan** [comment]
PendingBlockNumber   = BlockNumber(-2)
LatestBlockNumber    = BlockNumber(-1)
eth use PendingBlockNumber do DoEstimateGas,which may different from actual banlance.
In my case,getBalnace() use LatestBlockNumber get no-zero balance,but use PendingBlockNumber in DoEstimateGas get zero balance, this happened in certain first times,it's ok when it restart.

**Comment by holiman** [comment]
Is this really geth? If so, please provide the first 50 lines of upstart logs, so we can see which exact version it is.  If it's a downstream fork, please close.

**Comment by dbadoy** [comment]
I don't know the history, but the two variable about PendingBlockNumber are different.
So, If you want data about pending block, use like below
```go
// bad
pendingBlockNr := rpc.BlockNumberOrHashWithNumber(rpc.PendingBlockNumber)

// correct
pendingBlockNr := rpc.BlockNumberOrHashWithNumber(big.NewInt(-1))
```

In rpc modules,
```go
const (
	SafeBlockNumber      = BlockNumber(-4)
	FinalizedBlockNumber = BlockNumber(-3)
	PendingBlockNumber   = BlockNumber(-2)
	LatestBlockNumber    = BlockNumber(-1)
	EarliestBlockNumber  = BlockNumber(0)
)
```

And ethclient
```go
func toBlockNumArg(number *big.Int) string {
	if number == nil {
		return "latest"
	}
	pending := big.NewInt(-1)
	if number.Cmp(pending) == 0 {
		return "pending"
	}
	finalized := big.NewInt(int64(rpc.FinalizedBlockNumber))
	if number.Cmp(finalized) == 0 {
		return "finalized"
	}
	safe := big.NewInt(int64(rpc.SafeBlockNumber))
	if number.Cmp(safe) == 0 {
		return "safe"
	}
	return hexutil.EncodeBig(number)
}
```

**Comment by holiman** [comment]
> Is this really geth? If so, please provide the first 50 lines of upstart logs, so we can see which exact version it is. If it's a downstream fork, please close.

.... sounds of silence ... 

I'm closing
