### ISSUE TITLE
HTTP-RPC server enabled by default on MacOS

### ISSUE THREAD

**Issue by jiahongchao** [ethereum/go-ethereum#26259]
#### System information

Geth version: `1.10.26-stable`
OS & Version: OSX

#### Expected behaviour
HTTP-RPC server disabled

#### Actual behaviour
HTTP-RPC server enabled

#### Steps to reproduce the behaviour
Just run 'geth'
Document states that "--http" defaults to false, but  HTTP-RPC server is started.

**Comment by token01** [comment]
do you have  to do Consider to update your version of the RPC?

**Comment by s1na** [comment]
Are you referring to this log?

```
HTTP server started                      endpoint=127.0.0.1:8551 auth=true prefix= cors=localhost vhosts=localhost
```

If so that's an API required for normal operations of geth and to communicate with a consensus client. But the JSON-RPC API should be disabled (default port is 8545).

**Comment by fjl** [comment]
Geth starts a server for the engine API by default, because it is required to connect the client with the consensus-layer.

**Comment by jiahongchao** [comment]
> Are you referring to this log?
> 
> ```
> HTTP server started                      endpoint=127.0.0.1:8551 auth=true prefix= cors=localhost vhosts=localhost
> ```
> 
> If so that's an API required for normal operations of geth and to communicate with a consensus client. But the JSON-RPC API should be disabled (default port is 8545).

Got it, I thought it was HTTP server controlled by '--http' config.
