### ISSUE TITLE
  need to connect go ethereum in my tools which working RPC with python config. ini file, 

### ISSUE THREAD

**Issue by tamazib243** [ethereum/go-ethereum#26260]
hello when i try to connect to geth my rpc config.ini file i got error, ,, IPC / RPC error: 403 ,, and ,, error: no suitable peers available'}} ,, how i can solve which command can i use ? thanks

**Comment by ligi** [comment]
You need to provide more details. 
e.g. do you use light client? Which chain? ..

**Comment by tamazib243** [comment]
Yes,i used light client, anyway i got error goerli and mainnet

**Comment by ligi** [comment]
duplicate of #25623

**Comment by tamazib243** [comment]
![image](https://user-images.githubusercontent.com/34917942/204121866-5fff0879-deb8-49ab-b462-587cc37a5a03.png)

**Comment by tamazib243** [comment]
I will explain how this tool works, I tested this on ganache, this tool sends the transaction automatically, Without any consent, only by command... Now I want to test goerli and mainnet, It also receives calls in the back.. I want to do the same on the mainnet via go ethereum

**Comment by ligi** [comment]
you cannot use light mode for now

**Comment by tamazib243** [comment]
> you cannot use light mode for now

What can I use instead? Can i use --syncmode fast?
