### ISSUE TITLE
accounts/abi: Large Variability in ABI Pack() timing

### ISSUE THREAD

**Issue by FeurJak** [ethereum/go-ethereum#26264]
Seeing large variability in the time it takes to construct input data for a contract function via Pack() from the ABI package. 

I'm seeing it jump between 100us to >500ms to >1ms for a repeated run of constructing the same input data, i.e.: 

 Packing took: 126us
 Packing took: 127us
 Packing took: 121us
 Packing took: 131us
 Packing took: 122us
 Packing took: 123us
 Packing took: 311us
 Packing took: 547us
 Packing took: 416us
 Packing took: 427us
 Packing took: 4814us
 
 Anyone has any idea of the cause of this? ABI Pack is currently a bottleneck for what i'm building.

**Comment by fjl** [comment]
Please provide a [Go benchmark function](https://pkg.go.dev/testing#hdr-Benchmarks) that reproduces your case, if possible.

**Comment by holiman** [comment]
For go-ethereum in general, having a large variance on abi.Pack is not enough of an issue to warrant a ticket. If you do want to improve the situation, you're free to repro it with a benchmark, and maybe a PR fixing any underlying causes that you find.
