### ISSUE TITLE
README: bootnode documentation outdated

### ISSUE THREAD

**Issue by howard-repos** [ethereum/go-ethereum#26263]
In https://github.com/ethereum/go-ethereum, it states that `You could also use a full-fledged geth node as a bootnode, but it's the less recommended way.`

When I run bootnode  command, it said `We recommend using a regular node as bootstrap node for production deployments.`

What is the recommended way?

**Comment by ligi** [comment]
I think both suggest correctly that you usually should not run a bootnode

**Comment by jiahongchao** [comment]
> 

We are establishing a private network, so maybe we need a bootnode in our LAN.

**Comment by holiman** [comment]
>  We recommend using a regular node as bootstrap node for production deployments.

> We are establishing a private network, so maybe we need a bootnode in our LAN.

What we mean is, you should not run the binary `cmd/bootnode` as your bootnode, but run a regular `cmd/geth` as your bootnode.
