### ISSUE TITLE
how connect in rpc file go ethereum 

### ISSUE THREAD

**Issue by tamazib243** [ethereum/go-ethereum#26262]
i try much more time to connect rpc my geth, i got it cant run ,,syncmode light,, okay but can i used --syncmode fast? or how i connect in my rpc file , to be read from the geth side, also see the config.ini file, i am worked in ganache and working well my tools but cant run in geth my tools, please someone give me full comand which comand can i runing and what can i past in my config ini file, i mean local host and port

**Comment by ligi** [comment]
Please help to keep this issue-tracker clean and only for real issues with go-ethereum. For questions please go to http://ethereum.stackexchange.com

If the issue-tracker gets littered with questions - it is really hard to keep track of real issues. So I am sorry to close this issue - but feel free to answer here with the link to your question on stackexchange. Thanks!
