### ISSUE TITLE
Geth full sync does not find peers

### ISSUE THREAD

**Issue by ZhidanDeng** [ethereum/go-ethereum#26271]
Hi, everyone. I am new to geth. I am trying to run full node on Ethereum mainnet; however, I believe geth doesn't sync. I started the GETH client with:
`geth -syncmode full -http -authrpc.jwtsecret jwt.hex`

And I started the prysm with a Checkpoint Sync Endpoint:
`./prysm.sh beacon-chain --checkpoint-sync-url=https://sync.invis.tools --genesis-beacon-api-url=https://sync.invis.tools  --execution-endpoint=http://localhost:8551 --jwt-secret=/path/to/jwt.hex >> prysm.log `
(By the way,
```
OS: Ubuntu
geth version is 1.10.26
prysm version is 3.1.2
```
)
I Checked the `slot` and `state_root` which matched. 
Prysm shows:
![image](https://user-images.githubusercontent.com/89714583/204295816-11d436e8-b5be-4ef1-a0e5-afb46ee45dc7.png)

Geth shows:
![image](https://user-images.githubusercontent.com/89714583/204296322-03ae4af5-31cf-48f6-9fff-1dde925876b9.png)

Should I just wait? Thanks in advance.

**Comment by ZhidanDeng** [comment]
![image](https://user-images.githubusercontent.com/89714583/204419321-203b59eb-e464-44fd-b25c-b31a97a47c94.png)
It seems that CL has caught up  but geth still doesnt sync

**Comment by ZhidanDeng** [comment]
geth repeats 'looking for peers',I try with verbosity 4 to get details
![image](https://user-images.githubusercontent.com/89714583/204488811-8f1f7004-fe89-4f17-86b5-1a5c3fcccf0c.png)

**Comment by rjl493456442** [comment]
Something irrelevant, you are running full-sync which will take 2 weeks to finish on mainnet.
You can run snap-sync(the default sync mode) instead, which will also fetch all necessary data for you, but just not re-process all historic blocks.

**Comment by rjl493456442** [comment]
The disconnection reason is `disconnect requested`. Perhaps @fjl has some ideas?

**Comment by ZhidanDeng** [comment]
> Something irrelevant, you are running full-sync which will take 2 weeks to finish on mainnet. You can run snap-sync(the default sync mode) instead, which will also fetch all necessary data for you, but just not re-process all historic blocks.

Thanks for replying. What I want to do is re-process the historic blocks, replaying historic transcations(Research topic needs).So I guess I have to run full-sync. Is there a way that I can make it work?

**Comment by fjl** [comment]
@ZhidanDeng Is the command-line you posted, `geth -syncmode full -http -authrpc.jwtsecret jwt.hex`, the complete command you are using to run geth? Or are you passing other flags to it as well?

**Comment by ZhidanDeng** [comment]
> @ZhidanDeng Is the command-line you posted, `geth -syncmode full -http -authrpc.jwtsecret jwt.hex`, the complete command you are using to run geth? Or are you passing other flags to it as well?

It is the complete command I use to run geth.

**Comment by lxex** [comment]
> geth repeats 'looking for peers',I try with verbosity 4 to get details. ![image](https://user-images.githubusercontent.com/89714583/204488811-8f1f7004-fe89-4f17-86b5-1a5c3fcccf0c.png) my firewall configues as follow: ![image](https://user-images.githubusercontent.com/89714583/204489782-31901c3f-8300-41cc-be31-96d6bb97aa3d.png)

this view shows that target peer is erigon which is not full and maybe have big difference with geth.
I have a idea to use `admin.peers` find the proper peers for you and write to `static-nodes.json`. geth will try to connect to the static peers after startup.  In addition, You should remove the useless peer all the time.

**Comment by holiman** [comment]
This issue seems stale, and for the most part people seem able to find peers. I'm going to close this, but feel free to reopen if you are still having peer issues

**Comment by holiman** [comment]
Hey wait, btw, what is the default on that firewall. If it is default deny you are going to have problems. Because if someone contacts you on _your_ `tcp:30303`, then their source will be some random port. And you will send a to e.g  `tcp:12391`. If you have default deny on outgoing, that will be blocked.
