### ISSUE TITLE
How to sync data fast?

### ISSUE THREAD

**Issue by lxex** [ethereum/go-ethereum#26273]
Ethereum: master, last day
Operation: windows 10
hardware: 16g RAM, 8T SSD

I run geth of master two days and get the following cycle log.
start command: 
`geth --datadir=E:\\ethrun\\mainnet\\data --syncmode=snap --verbosity=2 --cache=6000`

log:

```
WARN [11-28|21:34:09.092] Checkpoint challenge timed out, dropping id=bdfa6602f579b499 conn=dyndial addr=34.202.193.18:30303  type=Geth/v1.10.26-stable...
WARN [11-28|21:34:18.862] Dropping unsynced node during sync       id=04aa99493d206cbb conn=dyndial addr=13.245.149.112:30303 type=Geth/v1.10.17-stable...
WARN [11-28|21:34:36.773] Dropping unsynced node during sync       id=0fa6d03f8ae1921e conn=dyndial addr=198.244.213.51:30304 type=Geth/v1.10.17-stable...
WARN [11-28|21:36:42.676] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [11-28|21:41:42.936] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [11-28|21:46:43.231] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [11-28|21:51:43.564] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [11-28|21:56:43.862] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [11-28|22:01:44.133] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [11-28|22:06:44.451] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [11-28|22:11:44.679] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [11-28|22:15:48.351] Checkpoint challenge timed out, dropping id=1a8f6dc2279f063e conn=dyndial addr=3.225.199.99:30303   type=Geth/v1.10.26-stable...
WARN [11-28|22:16:44.970] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [11-28|22:18:29.333] Snapshot extension registration failed   peer=a20727fa err="peer connected on snap without compatible eth support"
INFO [11-28|22:20:58.766] Writing clean trie cache to disk         path=E:\ethrun\mainnet\data4\geth\triecache threads=1
INFO [11-28|22:20:58.775] Regenerated local transaction journal    transactions=0 accounts=0
INFO [11-28|22:20:58.813] Persisted the clean trie cache           path=E:\ethrun\mainnet\data4\geth\triecache elapsed=45.939ms
WARN [11-28|22:21:45.257] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [11-28|22:23:21.836] Dropping unsynced node during sync       id=6a18b9fed9156dab conn=dyndial addr=144.91.116.158:30303 type=Geth/v1.10.3-stable-...
WARN [11-28|22:23:59.953] Snapshot extension registration failed   peer=6a0bcd3f err="peer connected on snap without compatible eth support"
WARN [11-28|22:24:44.048] Dropping unsynced node during sync       id=638c30470a01b8cb conn=dyndial addr=135.181.118.50:30303 type=Geth/v1.10.13-stable...
WARN [11-28|22:26:45.531] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [11-28|22:28:24.710] Snapshot extension registration failed   peer=04dfa983 err="peer connected on snap without compatible eth support"
WARN [11-28|22:31:24.142] Checkpoint challenge timed out, dropping id=6e09001d3d549505 conn=dyndial addr=18.179.46.45:30303   type=Geth/v1.10.25-stable...
WARN [11-28|22:31:45.765] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [11-28|22:34:26.554] Snapshot extension registration failed   peer=f25d90f5 err="peer connected on snap without compatible eth support"
WARN [11-28|22:36:44.604] Checkpoint challenge timed out, dropping id=6e09001d3d549505 conn=dyndial addr=18.179.46.45:30303   type=Geth/v1.10.25-stable...
WARN [11-28|22:36:46.045] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [11-28|22:36:56.471] Snapshot extension registration failed   peer=6a0bcd3f err="peer connected on snap without compatible eth support"
WARN [11-28|22:41:46.392] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
```

**Comment by ZhidanDeng** [comment]
you need a consensus client(like prysm) to 'guide' geth to sync

**Comment by lxex** [comment]
> you need a consensus client(like prysm) to 'guide' geth to sync
@ZhidanDeng Thanks, I run prysm and get some errors log

Geth log:
INFO [11-29|10:20:58.808] Persisted the clean trie cache           path=E:\ethrun\mainnet\data4\geth\triecache elapsed=38.552ms
WARN [11-29|10:22:28.042] Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!

Prysm log: 
[2022-11-29 10:20:43]  INFO initial-sync: Processing block batch of size 64 starting from  0x576ba46e... 63168/5238701 - estimated time remaining 16h13m1s blocksPerSecond=88.7 peers=38
_[2022-11-29 10:20:48] ERROR powchain: Unable to process past deposit contract logs, perhaps your execution client is not fully synced error=no contract code at given address_
[2022-11-29 10:21:03]  INFO p2p: Peer summary activePeers=44 inbound=0 outbound=44
[2022-11-29 10:21:06]  INFO initial-sync: Processing block batch of size 63 starting from  0x4dd9d0bd... 63232/5238703 - estimated time remaining 456h23m26s blocksPerSecond=3.1 peers=44
[2022-11-29 10:21:06]  INFO initial-sync: Processing block batch of size 62 starting from  0xbed1912b... 63296/5238703 - estimated time remaining 230h1m5s blocksPerSecond=6.2 peers=44

**Comment by lxex** [comment]
I just want to sync data, is this correct?

**Comment by ZhidanDeng** [comment]
> I just want to sync data, is this correct?

Yes,you have to wait days till prysm completely sync.But you can use a checkpoint sync endpoint to speed up the process.
(https://mainnet-checkpoint-sync.attestant.io/)

**Comment by lxex** [comment]
@ZhidanDeng Thanks very much.  I kill prysm and start up with the checkpoint (https://mainnet-checkpoint-sync.attestant.io/).

**Comment by ZhidanDeng** [comment]
> @ZhidanDeng Thanks very much. I kill prysm and start up with the checkpoint (https://mainnet-checkpoint-sync.attestant.io/).
You are welcome.I want to do the same thing you do.But I stuck at the next step,please let me know your follow up.Good luck

**Comment by lxex** [comment]
> > @ZhidanDeng Thanks very much. I kill prysm and start up with the checkpoint (https://mainnet-checkpoint-sync.attestant.io/).
> > You are welcome.I want to do the same thing you do.But I stuck at the next step,please let me know your follow up.Good luck

Yeah, the chaindata increasing quickly.

**Comment by rjl493456442** [comment]
@ZhidanDeng is correct and I will close this ticket.

**Comment by ZhidanDeng** [comment]
> > > @ZhidanDeng Thanks very much. I kill prysm and start up with the checkpoint (https://mainnet-checkpoint-sync.attestant.io/).
> > > You are welcome.I want to do the same thing you do.But I stuck at the next step,please let me know your follow up.Good luck
> 
> Yeah, the chaindata increasing quickly.

Can you run geth with --syncmode full? Casuse I stuck here. Geth dose not sync, and repeat 'looking for peers'

**Comment by lxex** [comment]
@ZhidanDeng Hi, brother
I have synced the snap block completed.

Half hour ago:
> eth.syncing
{
  currentBlock: 16093875,
  healedBytecodeBytes: 5397885,
  healedBytecodes: 675,
  healedTrienodeBytes: 1246315439,
  healedTrienodes: 5151718,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 16093936,
  startingBlock: 0,
  syncedAccountBytes: 47300243377,
  syncedAccounts: 195488135,
  syncedBytecodeBytes: 5041079154,
  syncedBytecodes: 753400,
  syncedStorage: 886202372,
  syncedStorageBytes: 190130026688
}

Now:
> eth.syncing
false
> eth.blockNumber
16094080
What you stucked? If you need pls let me know.

**Comment by ZhidanDeng** [comment]
> @ZhidanDeng Hi, brother I have synced the snap of block data completly.
> 
> Half hour ago:
> 
> > eth.syncing
> > {
> > currentBlock: 16093875,
> > healedBytecodeBytes: 5397885,
> > healedBytecodes: 675,
> > healedTrienodeBytes: 1246315439,
> > healedTrienodes: 5151718,
> > healingBytecode: 0,
> > healingTrienodes: 0,
> > highestBlock: 16093936,
> > startingBlock: 0,
> > syncedAccountBytes: 47300243377,
> > syncedAccounts: 195488135,
> > syncedBytecodeBytes: 5041079154,
> > syncedBytecodes: 753400,
> > syncedStorage: 886202372,
> > syncedStorageBytes: 190130026688
> > }
> 
> Now:
> 
> > eth.syncing
> > false
> > eth.blockNumber
> > 16094080
> 
> chaindata size: 681GB
> 
> What you stucked? If you need pls let me know.

wow, congrats and thanks. Here is my [issue.](https://github.com/ethereum/go-ethereum/issues/26271) 
I am not sure is it normal ? Or should I just wait

**Comment by klayT-11** [comment]
> 你需要一个共识客户端（如 prysm）来“引导”geth 同步

是通过JWT令牌引导同步的吗 我刚接触有点不懂
