### ISSUE TITLE
[core] use an interface for statedb  in  `ApplyTransaction` to allow mocking in tests

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#26278]
# Rationale

Why should this feature exist?
 - allow external use with adapters and mocking for the tests

What are the use-cases?
 - to allow state simulation tests without bootstrapping a full blockchain component. 

# Implementation

Do you have ideas regarding the implementation of this feature?
 - yes

Are you willing to implement this feature?
 - yes

**Comment by krasi-georgiev** [comment]
@holiman any objections to this change?

**Comment by holiman** [comment]
Not off the top of my head, no
