### ISSUE TITLE
puppeth: deprecated flag in bash start file

### ISSUE THREAD

**Issue by gianlucamazza** [ethereum/go-ethereum#26282]
It seems that the current puppeth tool it uses an unsupported flag:
`Incorrect Usage. flag provided but not defined: -miner.gastarget`

the command line is in geth.sh file

docker services they fail while trying to boot up

----
Geth
Version: 1.10.26-stable
Architecture: amd64
Go Version: go1.19.3

**Comment by gianlucamazza** [comment]
I see the file has been modified here but my version is outdated
https://github.com/ethereum/go-ethereum/commit/15b4a4bf2ef44605264dab15ca6006f643d36c5e

**Comment by fjl** [comment]
I hope you could resolve your issue by updating your puppeth installation.

**Comment by gianlucamazza** [comment]
installing geth from sources fixed it, thank you
