### ISSUE TITLE
Add Shanghai Fork to `evm t8n`

### ISSUE THREAD

**Issue by marioevz** [ethereum/go-ethereum#26287]
# Rationale

Although not finalized yet, it would be great to have the fork available in `evm t8n` with the EIPs that almost certainly will make it into the cut (perhaps 3651, 3855, 3860?).

I've been manually adding it locally for testing but I think it should be available by default.

# Implementation

Add it into the `Forks` map in `tests/init.go`, plus tests.

**Comment by MariusVanDerWijden** [comment]
closed by https://github.com/ethereum/go-ethereum/pull/26458
