### ISSUE TITLE
`evm.depth` can reach 1025

### ISSUE THREAD

**Issue by lightsing** [ethereum/go-ethereum#26288]
#### System information

Geth version: N/A
CL client & version: N/A
OS & Version: ALL
Commit hash : c1aa1db69e74c71f251fc83cf7c120b4d0222728

#### Expected behaviour

maxium possible depth is 1024

#### Actual behaviour

maxium possible depth is 1025

#### Steps to reproduce the behaviour

```
PUSH32 0x7f602060006000376000600060206000600060003561ffff5a03f10000000000
PUSH1 0x0
MSTORE
PUSH32 0x0060005260206000F30000000000000000000000000000000000000000000000
PUSH1 0x20
MSTORE
PUSH1 0x40
PUSH1 0x0
PUSH1 0x0
CREATE
DUP1
PUSH1 0x40
MSTORE
PUSH1 0x0 // retSize
PUSH1 0x0 // retOffset
PUSH1 0x20 // argSize
PUSH1 0x40 // argOffset
PUSH1 0x0 // Value
DUP6
PUSH2 0xFF
GAS
SUB
CALL
```

#### Backtrace

[trace.json.gz](https://github.com/ethereum/go-ethereum/files/10138141/trace.json.gz)

#### Reason

1. depth check pass when `evm.depth == 1024`
    https://github.com/ethereum/go-ethereum/blob/c1aa1db69e74c71f251fc83cf7c120b4d0222728/core/vm/evm.go#L170
2. subcontext starts
    https://github.com/ethereum/go-ethereum/blob/c1aa1db69e74c71f251fc83cf7c120b4d0222728/core/vm/evm.go#L228
3. depth increase and now `evm.depth == 1025`
    https://github.com/ethereum/go-ethereum/blob/c1aa1db69e74c71f251fc83cf7c120b4d0222728/core/vm/interpreter.go#L114
4. subsequent call attempt will now fail since `evm.depth > int(params.CallCreateDepth)`

#### Suggest Fix

Change `evm.depth > int(params.CallCreateDepth)` to `evm.depth >= int(params.CallCreateDepth)`

**Comment by holiman** [comment]
See https://github.com/ethereum/go-ethereum/pull/26289#issuecomment-1335097463

**Comment by DreamWuGit** [comment]
@holiman  it can reach the 1025 but not revert, for call in 1025 depth , just push zero result to the stack and resume run others' remaining op codes  you can refer to trace file [trace.json.gz](https://github.com/ethereum/go-ethereum/files/10138141/trace.json.gz) attached to this issue 
```
{
        "pc": 25,
        "op": "CALL",
        "gas": 991802549,
        "gas_cost": 976305636,
        "refund": 0,
        "depth": 1025,
        "error": null,
        "stack": [
            "0",
            "0",
            "20",
            "0",
            "0",
            "ed59714e286e0058f3160cc1bc7506e6f06add3c",
            "3b1cb4b9"
        ],
        "memory": "000000000000000000000000ed59714e286e0058f3160cc1bc7506e6f06add3c",
        "storage": {}
    },
    {
        "pc": 26,
        "op": "STOP",
        "gas": 991802449,
        "gas_cost": 0,
        "refund": 0,
        "depth": 1025,
        "error": null,
        "stack": [
            "0"
        ],
        "memory": "000000000000000000000000ed59714e286e0058f3160cc1bc7506e6f06add3c",
        "storage": {}
    },
```
