### ISSUE TITLE
Where are the tokenomics of ETH native token defined?

### ISSUE THREAD

**Issue by timosarkar** [ethereum/go-ethereum#26294]
Currently trying to setup a ethereum based private chain. I want to change the native token ETH to a custom one. Where in the codebase is the tokenomics defined? Just in genesis.json or are the tokenomics ruled over a separate ERC20 contract?

Thanks for your support

**Comment by timosarkar** [comment]
BSC for example.: Forked ethereum and added BNB. Is it configured over an ERC20 which is indexed in the 4byte db?

**Comment by karalabe** [comment]
The Ether rules are part of the protocol specs and hard forks. Geth does not have a way to configure them or modify them.

**Comment by timosarkar** [comment]
Sorry for opening this again. Where are the protocol speccs defined?
