### ISSUE TITLE
`rlpHash` doesn't return expected hash

### ISSUE THREAD

**Issue by TmLev** [ethereum/go-ethereum#26292]
#### Expected behaviour

I'm fetching transaction by its hash and comparing original hash with hash of the received transaction.

Hashes must be equal.

#### Actual behaviour

They differ when interacting with [Meter](https://meter.io/):

```log
2022/12/02 18:59:16 BSC:
2022/12/02 18:59:16 original tx hash:  0xb72a06e15ccf3af1283d71f66abff02cdc4c023f673203f2c319538d96bdf50c
2022/12/02 18:59:16 tx hash from node: 0xb72a06e15ccf3af1283d71f66abff02cdc4c023f673203f2c319538d96bdf50c
2022/12/02 18:59:17 Meter:
2022/12/02 18:59:17 original tx hash:  0x37656fc5eb232510cb47b2db7b90fe0763d6ebbc2ef0578409a6aac3ae24dcf5
2022/12/02 18:59:17 tx hash from node: 0x1476a74942ce0326f667955838bb3213530aad7b22fa801c816ca17c2300b84b
```

#### Steps to reproduce the behaviour

Here's the MRE: https://github.com/TmLev/go-ethereum-rlphash-repro

<details>
  <summary>Here's how to request transaction via `curl`</summary>
  
  ```shell
  curl -H "Content-Type: application/json" -X POST \
      --data '{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0x37656fc5eb232510cb47b2db7b90fe0763d6ebbc2ef0578409a6aac3ae24dcf5"],"id":0}' \
      https://rpc.meter.io
  ```
  ```log
  {
    "jsonrpc": "2.0",
    "result": {
      "hash": "0x37656fc5eb232510cb47b2db7b90fe0763d6ebbc2ef0578409a6aac3ae24dcf5",
      "nonce": "0xdc1e3978",
      "blockHash": "0x01d68657a0a9c760756b86626ec02b03c5a03b60b001175e9124ae780a7ac201",
      "blockNumber": "0x1d68657",
      "transactionIndex": "0x0",
      "from": "0x4021fc4306c61f56b354be72896c95d80c458fd6",
      "to": "0x18232c46a19f803d2b29c73dd78d194245ab96d4",
      "value": "0x0",
      "gas": "0xd7a24",
      "gasPrice": "0x1",
      "input": "0x84c3e951000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000003e900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000005fa41671c48e3c951afc30816947126ccc8c162effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000000000005fa41671c48e3c951afc30816947126ccc8c162e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000000",
      "r": "0x3e8f58ae2b604d94a488cb9c59353d58a95538055be1822ed6d433e4d4cf535b",
      "s": "0x7ee8da896f27e9245cea6ac850626193f45500ea0d2004fe848348887feb2c4d",
      "v": "0xc7"
    },
    "id": 0
  }
  ```
</details>

#### Comment

Both BSC and Meter use `LegacyTx` for which `rlpHash(tx.inner)` is called when accessing `tx.Hash()`. The output differs between those chains.

I suspect this may happen because of the Meter response, though I'm not sure which piece of the response leads to the observed difference.

#### System information

Geth version: -
CL client & version: go-ethereum@v1.10.16
OS & Version: MacOS X 12.4

**Comment by TmLev** [comment]
I think so, yes
https://scan.meter.io/tx/0x37656fc5eb232510cb47b2db7b90fe0763d6ebbc2ef0578409a6aac3ae24dcf5

**Comment by TmLev** [comment]
Yes, the transaction is from Meter fork chain.

> It might be possible that some extra fields are ignored by ethclient because they are not defined in ethereum.

I see. So I should probably take it up to Meter developers?

**Comment by holiman** [comment]
We don't support non-ethereum chains

**Comment by rjl493456442** [comment]
> I see, thanks. So I should probably take it up to Meter developers?

Yes please.

> I was also curious why .Hash() computes hash from scratch when it's present in the response from blockchain node?

Don't trust, verify it?
