### ISSUE TITLE
State healing never finishes

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/go-ethereum#26295]
#### System information

Geth version:
```
Version: 1.11.0-unstable
Git Commit: 1b8a392153b39fbbde17536c730d96510e57341f
Git Commit Date: 20221128
```
CL client & version: `Lighthouse v3.2.1-6d5a2b5`
OS & Version: Ubuntu 22.10

I got the same issue on version `1.10.26`.

#### Expected behaviour

The state healing phase during mainnet sync should finish after some time, according to [this message](https://discord.com/channels/595666850260713488/1014177210560696330/1016594796854382652) on Discord from half a year ago in ~3h.

#### Actual behaviour

State healing has been going on for ~36h, regularly logging the following message:

```
Syncing: state healing in progress       accounts=1,215,001@63.58MiB   slots=6,202,681@449.59MiB   codes=1501@11.21MiB   nodes=19,827,850@4.31GiB   pending=19955
```

CPU load is at 25%, memory usage at 70% of 8GB. This is a mainnet sync starting from an empty database.

**Comment by yorickdowne** [comment]
That's not a bug. This may be a lack of IOPS in the storage. Take a look at the storage you have and, if possible, improve IOPS - allocate more if cloud or get a better model if hardware.

**Comment by yorickdowne** [comment]
What's the make/model of that drive?

An ETA can't be given because state is a moving target. Geth had an ETA at one point and it was wildly inaccurate, so they removed it.
