### ISSUE TITLE
Document for "Private Networks" should be updated

### ISSUE THREAD

**Issue by jiahongchao** [ethereum/go-ethereum#26303]
In https://geth.ethereum.org/docs/interface/private-network, there is an example to setup private network on one machine. Document states that
`./geth --datadir node1 --port 30306 --bootnodes enode://f7aba85ba369923bffd3438b4c8fde6b1f02b1c23ea0aac825ed7eac38e6230e5cadcf868e73b0e28710f4c9f685ca71a86a4911461637ae9ab2bd852939b77f@127.0.0.1:0?discport=30305  --networkid 123454321 --unlock 0xC1B2c0dFD381e6aC08f34816172d6343Decbb12b --password node1/password.txt`

but this only changed one port to 30306, however new version clients will also open port 8551 which will cause conflicts.
So document may need to tell users to change port for 8551

**Comment by MariusVanDerWijden** [comment]
`--authrpc.port 8552`

**Comment by jmcook1186** [comment]
thanks, now fixed.
