### ISSUE TITLE
Cannot use function sign secp256k1

### ISSUE THREAD

**Issue by lexuantruong0402** [ethereum/go-ethereum#26306]
i installed github.com/ethereum/go-ethereum/crypto/secp256k1
but when trying to use Sign function there is an error
![image](https://user-images.githubusercontent.com/17667288/205628610-ced0906e-9877-4e26-aeed-11867862ee80.png)
please help me

**Comment by mohammadfarari1360** [comment]
Hello good dear

**Comment by fjl** [comment]
Please use [`crypto.Sign`](https://pkg.go.dev/github.com/ethereum/go-ethereum/crypto#Sign) instead of package secp256k1. The secp256k1 package may not be available in all environments and only works when cgo is supported.
