### ISSUE TITLE
Geth console client: do not create history file with system-wide read permission

### ISSUE THREAD

**Issue by malandante** [ethereum/go-ethereum#2631]
#### System information

Geth version: 1.4.5
OS & Version: Linux Ubuntu 14.04 LTS

#### Expected behaviour
When history file is created, it should be done with only owner read and write permission (600)

#### Actual behaviour
History file is created with 775 permission.

#### Steps to reproduce the behaviour
Delete the history file. Run geth attach. Type a few commands. Exit. Check with ls -l .ethereum/history

**Comment by obscuren** [comment]
Thanks for the report. We will address this!

**Comment by malandante** [comment]
My pleasure

**Comment by bas-vk** [comment]
Fixed in https://github.com/ethereum/go-ethereum/pull/2535

**Comment by karalabe** [comment]
Fixed and released in 1.4.6.
