### ISSUE TITLE
Duplicated transaction hash on ETH/ETC

### ISSUE THREAD

**Issue by mszczepanik1337** [ethereum/go-ethereum#26316]
Hi,

i just found that some tx hashes are duplicated on Ethereum and Ethereum classic network. Few years ago, after a hardfork there was issue with replay attacks, but i think it was fixed in 2017. 

Example transaction hash -> 0x8577d2ce7e033ea14517296b9a0f9879265701741e990f15de6a56b42eadb708

This transaction has same addresses from -> to, same value, same timestamp, just asset is different.
https://blockscout.com/etc/mainnet/tx/0x8577d2ce7e033ea14517296b9a0f9879265701741e990f15de6a56b42eadb708
https://etherscan.io/tx/0x8577d2ce7e033ea14517296b9a0f9879265701741e990f15de6a56b42eadb708

Could someone explain how is it possible?

**Comment by holiman** [comment]
Reason being that this is a legacy transaction, where replay protection is implemented by incorporating the chain id into an existing field. For legacy transctions, doing so is not mandatory - as opposed to newer types where the chain id is it's own explicit field. 

So someone intentionally made a replayable transaction and put on both networks. 
![Screenshot 2022-12-06 at 11-33-09 Ethereum Transaction Hash (Txhash) Details Etherscan](https://user-images.githubusercontent.com/142290/205887844-070ead29-9fef-432f-91f0-f95e7859d5bf.png)
