### ISSUE TITLE
Unable to start a full sync node and archive gb

### ISSUE THREAD

**Issue by adaki2004** [ethereum/go-ethereum#26318]
#### System information

Geth version: Tried with docker images latest, v.1.10.1, v.1.7.3
CL client & version: 3 nodes (configured from the above image by inheriting from the original Docker image) running in a docker compose. 3 nodes configured as: bootnode, minernode, rpc endpoint.
OS & Version: OSX
Commit hash :

#### Expected behaviour
geth can interpret `--syncmode "full"` and `--gcmode archive` command line options+flags.

#### Actual behaviour

1. Problem:
When a docker container with the image is created, supplying it with the above mentioned parameters (`--syncmode "full"` and `--gcmode archive`) will not work. It says geth not found.

This is the exact error log i see:
`/bin/sh: [geth: not found`

2. Probem:
When i exclude the 2 params from the Dockerfile (`--syncmode "full"` and `--gcmode archive`) geth starts properly. But when i want to call `geth --syncmode "full"` within the container's terminal , it says: 

```
geth --syncnode "fast"
Incorrect Usage. flag provided but not defined: -syncnode
...+ the whole HELP ...
```

#### Steps to reproduce the behaviour

1. Problem:
Dockerfile
```
FROM ethereum/client-go:latest

COPY genesis.json /tmp

RUN geth init /tmp/genesis.json
RUN rm -f ~/.ethereum/geth/nodekey
RUN echo PWD > /tmp/password
RUN geth account new --password /tmp/password
RUN rm -f /tmp/password

ENTRYPOINT ["geth" "--rpcaddr" "0.0.0.0" "--rpcvhosts" "*" "--syncmode" "full" "--gcmode" "archive"]
```

After that see the container.

2. Problem:
Dockerfile
```

FROM ethereum/client-go:latest

COPY genesis.json /tmp

RUN geth init /tmp/genesis.json
RUN rm -f ~/.ethereum/geth/nodekey
RUN echo PWD > /tmp/password
RUN geth account new --password /tmp/password
RUN rm -f /tmp/password

ENTRYPOINT ["geth" "--rpcaddr" "0.0.0.0" "--rpcvhosts"]
```

After that try to set the synymode within the container.

#### Backtrace

````
/bin/sh: [geth: not found
````

```
geth --syncnode "fast"
Incorrect Usage. flag provided but not defined: -syncnode
...+ the whole HELP ...
```

For a genesis.json file, please see this content:
```
{
    "config": {
      "chainId": 1214,
      "homesteadBlock":0,
      "eip150Block": 0,
      "eip155Block": 0,
      "eip158Block": 0,
      "byzantiumBlock": 0,
      "constantinopleBlock": 0,
      "petersburgBlock": 0,
      "ethash": {}
    },
    "difficulty": "1",
    "gasLimit": "12000000",
    "alloc": {}
}
```

Could you please give me a hint how could i start a full sync, archive node ? I would like to use it with blockscout and it seems blockscount needs a full sync node.
Thanks in advance,
Dani

**Comment by MariusVanDerWijden** [comment]
It's `--syncmode` instead of `--syncnode`

**Comment by adaki2004** [comment]
Yes sorry, a typo on the console only from myside. (See in Dockerfile -> it's correct there. Issue exists.)

**Comment by mozgoo** [comment]
`ENTRYPOINT` and `CMD` have a different syntax
You need to use a comma as a separator like `ENTRYPOINT ["geth", "version"]`
https://docs.docker.com/engine/reference/builder/#entrypoint

**Comment by mozgoo** [comment]
try to use `ENTRYPOINT ["geth", "--rpcaddr=0.0.0.0", "--rpcvhosts=*", "--syncmode=full", "--gcmode=archive"]`

**Comment by mozgoo** [comment]
also, use `--http --http.addr=0.0.0.0 --http.vhosts=*`

**Comment by adaki2004** [comment]
Exactly same behavior.. :( 

`Incorrect Usage. flag provided but not defined: -rpcaddr`

**Comment by karalabe** [comment]
There's no `rpcaddr` flag, it's called `http.addr`.

**Comment by adaki2004** [comment]
Thank you ! It works ;) Tho help message is not so helpful in this context, but anyhow thanks again.
