### ISSUE TITLE
error: "too many arguments, want at most 1" when trying to pass new fullTx parameter in eth_subscribe

### ISSUE THREAD

**Issue by slightly-above-average-coder** [ethereum/go-ethereum#26323]
System information
Geth version: v1.10.26-stable
CL client & version: lighthouse@v3.1.2-01e84b7
OS & Version: Linux Ubuntu
Commit hash : (if develop)

Ive been trying to use the new fullTx parameter added on [5b1a04b](https://github.com/ethereum/go-ethereum/commit/5b1a04b9c749d804b51159fe12246c56de8515c1) but its not accepting it for some reason.

Im sending via websockets:

`{ jsonrpc: '2.0',method: 'eth_subscribe',params:['newPendingTransactions',true],id: 1}`

And should be getting the full transaction details instead of the hash.

But getting the error:

`{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"too many arguments, want at most 1"}`

If I send

`{ jsonrpc: '2.0',method: 'eth_subscribe',params:['newPendingTransactions'],id: 1}`

I get the TX hashes normally as per the old implementation.

Anything Im missing here?

**Comment by holiman** [comment]
> Anything Im missing here?

Yes, it's in `master` but not in `1.10.26`
