### ISSUE TITLE
A question about GAS

### ISSUE THREAD

**Issue by TinyCoolrain** [ethereum/go-ethereum#26331]
I have created a private chain, which is now running. I want to raise the GAS or GAS Price of all transactions, so that MetaMask can automatically bid higher to get more ETH consumption. Is there any solution,Thanks to those who answered and participated in the discussion

**Comment by karalabe** [comment]
You can set the gas price for mining via `miner.gasprice`. The basefee (part that gets burned) rises and lowers automatically with block fullness, so unless you make maaaaany txs non stop, it will stay around 7 wei.
