### ISSUE TITLE
Panic runtime error

### ISSUE THREAD

**Issue by amaioli** [ethereum/go-ethereum#26342]
Hi, when this code run sometime at runtime I got a invalid memory error on follow instruction:

fmt.Println("Transaction Value:", *result.To())

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6bfbdb]

-----------------------------------------------------------------------------------------------------------------------------

package main

import (
	"context"
	"fmt"
	"log"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/rpc"
)

func main() {
	// Connect to an Ethereum node using WebSockets

	client, err := rpc.DialWebsocket(context.Background(), "xxx", "/websocket")
	if err != nil {

		log.Fatal(err)
	}

	txs := make(chan *common.Hash)
	sub, _ := client.EthSubscribe(context.Background(), txs, "newPendingTransactions")

	result := types.Transaction{}

	for {
		select {
		case tx := <-txs:

			err = client.CallContext(context.Background(), &result, "eth_getTransactionByHash", tx)
			if err != nil {
				log.Fatal(err)
			}

			fmt.Println("Transaction Value:", *result.To())

		case err := <-sub.Err():
			log.Fatal(err)
		}
	}
}

**Comment by holiman** [comment]
Please see https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction.go#L283
