### ISSUE TITLE
[question]: how many blocks will be moved into the freezer database? does it depends on FullImmutabilityThreshold?

### ISSUE THREAD

**Issue by shiziwen** [ethereum/go-ethereum#26358]
Hi, from the doc https://blog.ethereum.org/2019/07/10/geth-v1-9-0, it mentions "Blocks and receipts that are older than a cutoff threshold (3 epochs) are moved out of LevelDB into a custom freezer database, that is backed by a handful of append-only flat files. ". 
So does it means the blocks are older than 3 epochs which is 3*32 = 96 blocks will be moved into the freezer database? 96 is too small, does it?

But I also find the argument FullImmutabilityThreshold? what does it mean? By default, it is set to 90000.

**Comment by karalabe** [comment]
3 PoW epochs, 90K blocks.
