### ISSUE TITLE
Update Getting Started Docs with Info on Consensus Clients

### ISSUE THREAD

**Issue by EvanPiro** [ethereum/go-ethereum#26370]
# Rationale

Why should this feature exist?

In order to get through the [Getting Started docs](https://github.com/ethereum/go-ethereum/blob/gh-pages/docs/_getting-started/index.md), the user needs to know about Consensus Clients and how to run them in tandem with Geth. 

What are the use-cases?

Users going through the docs will run into the following error when running geth on goerli:
```
WARN [12-18|14:15:59.972] Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
```
To get past this error, the docs should provide info on installing and running a consensus client.

# Implementation

Do you have ideas regarding the implementation of this feature?

Not yet, but I'm currently figuring it out.

Are you willing to implement this feature?

I'd like to help document this as soon as I can figure how best to do it.

**Comment by MariusVanDerWijden** [comment]
The website is located on the `website` branch, you can just open a PR against that

**Comment by jmcook1186** [comment]
We also have the dedicated [`Consensus Clients`](https://geth.ethereum.org/docs/getting-started/consensus-clients) page that covers this. It is linked in the second paragraph in [`Getting Started`](https://geth.ethereum.org/docs/getting-started).

**Comment by jmcook1186** [comment]
Closing as no changes needed at the moment. Please feel free to open a new PR against `website` if you want to suggest improvements to the existing copy.
