### ISSUE TITLE
miner: extra data is zeroed post-merge, shouldn't be

### ISSUE THREAD

**Issue by quickchase** [ethereum/go-ethereum#26376]
I run a bunch of validators on Goerli and all of the blocks that are not mev-boosted have null (0x) extradata fields.

Its my understanding that geth is the block producer and the block producer sets the extradata field.

According to help, by default extradata is set to the client version, but even manually adding `--miner.extradata` doesn't seem to change the extradata of the proposed blocks.

Is this a geth problem or a Lighthouse problem (my CL is Lighthouse)?

**Comment by karalabe** [comment]
Thanks for the report! It is indeed a bug. I think the field was meant to be used for something else which got changed after all and we didn't revert it back to the old behavior. Will look into it and fix.

**Comment by karalabe** [comment]
CC @mkalinin, the execution payload *can* and *should* contain our own graffiti, right? Do you know why it was zeroed out while implementing the merge a year ago?
