### ISSUE TITLE
Are there plans to upgrade to golang 1.19?

### ISSUE THREAD

**Issue by 0x416e746f6e** [ethereum/go-ethereum#26378]
Go 1.19 has `GOMEMLIMIT` that might help to control memory utilisation with better precision.  Are there plans to upgrade towards it?

**Comment by MariusVanDerWijden** [comment]
At some point, yes. We upgraded the ci and docker to 1.19 already. The min version in go.mod is still 1.18 though

**Comment by 0x416e746f6e** [comment]
Thanks @MariusVanDerWijden.
