### ISSUE TITLE
Unknown transactions in Block Explorer

### ISSUE THREAD

**Issue by ekawibisono** [ethereum/go-ethereum#26389]
Hello,
I have a problem that is there is a transaction that we don't know about and suddenly moved all tokens to this address 0x123456f6Ed06F81eb1Edc6fccE34414E2C21fE5c, even though we haven't created Web3 Access or Dapps yet. Is this a phishing address?

Geth Version : 1.10.26

Run Geth : 
> geth 	--datadir=node1/ \
> 	    --syncmode 'full' \
> 		--port 30310 \
> 		--networkid xxxxx \
> 		--http \
> 		--http.addr 0.0.0.0 \
> 		--http.corsdomain '*' \
> 		--http.port 8545 \
> 		--http.vhosts '*' \
> 		--http.api admin,eth,miner,net,txpool,web3,debug,personal \
>         --ws.api eth,net,web3,debug,txpool \
>         --ws \
>         --ws.addr 0.0.0.0 \
>         --ws.port 8455 \
>         --ws.origins '*' \
>         --authrpc.addr 0.0.0.0 \
>         --authrpc.port 8551 \
> 		--bootnodes "enode://9aa581bc00647a28949bdfc8fae73a1381eaf6b28af00f18b276c0de3b22c1468372b2fcc428a9a1fa46aa1a89e3b7bf66441825bbc630fabc2b5215f2dab94c@127.0.0.1:0?discport=30305" \
> 		--mine \
>         --miner.gasprice 1000000000 \
> 		--cache 4096 \
> 		--verbosity 3 >> eth1.txt \
>         --snapshot=false \
> 		--allow-insecure-unlock \
> 		--unlock "xxxx9E04" \
> 		--password password.txt 

![Screenshot 2022-12-28 140359](https://user-images.githubusercontent.com/22586872/209772256-ba3eea11-63be-474c-a01f-5d08d7b62255.png)

**Comment by ekawibisono** [comment]
![image](https://user-images.githubusercontent.com/22586872/209776004-c3b7167d-9910-436c-a46a-30d6f7e610c8.png)

When I run getch, there is a color like in the picture, is this really phishing?

**Comment by karalabe** [comment]
Please never expose your APIs to the public internet. Bots are actively scanning addresses and trying to connect to them and both sweep addresses as well as try to mine / change mining addresses.

**Comment by ekawibisono** [comment]
@karalabe then How to fix it? do you have to remove the http.api command?

**Comment by holiman** [comment]
@ekawibisono you are _actively_ configuring the node to be "free for all". 

` --allow-insecure-unlock  --unlock "xxxx9E04" --password password.txt --http.addr 0.0.0.0 --http.api admin,eth,miner,net,txpool,web3,debug,personal `. 

Those arguments can be translated into:

> I want geth to be publically available to the internet (`--http.addr 0.0.0.0 --http.api admin,eth,miner,net,txpool,web3,debug,personal`) , and I want my account ".xxx9e04" to be unlocked (`--unlock "xxxx9E04" --password password.txt`), so anyone can sign transactions from it without using a password. And yes, I am aware that this is insecure, but please go ahead anyway (`--allow-insecure-unlock`).

**Comment by ekawibisono** [comment]
@holiman and then what is the correct configuration?

**Comment by holiman** [comment]
Well, start from `geth` and only add what you need. Hard for me to say what you need. I suppose there was some reason you added all those flags? They have the effect described above - if you don't want that, then don't use them.

**Comment by ekawibisono** [comment]
Any solution orther?

**Comment by karalabe** [comment]
I'm sorry, but you're not really helping us here. We've told you that the configs you used are insecure, told you which ones are problematic and why. We have no idea what you're trying to do or what your setup is. Start without any flags and only add things you need and make sure they don't expose your node to the internet.

Exposing anything on `0.0.0.0` is very bad unless you have some other firewall / network in front. We don't know what your setup is and as such ca't help you more really.
