### ISSUE TITLE
How can reconfig a PoA based private Etherem without stop Geth and run it again?

### ISSUE THREAD

**Issue by AlirezaEthDev** [ethereum/go-ethereum#26398]
As I've experienced so far, for reconfiguring a private Ethereum based on PoA, we should stop the running Geth, modify the genesis file, then init and run Geth again. Is there a way that we can reconfigure it without these steps? I mean is there a way to reconfigure while Geth is running such that there is no need for stopping it?

**Comment by MariusVanDerWijden** [comment]
No, there's no way to modify the config without restarting the node. The config is read in the beginning and stuff is stored and modified based on the config all over the place which makes it hard to change it on the fly
