### ISSUE TITLE
geth fast sync restarts at end of blockchain

### ISSUE THREAD

**Issue by adsmaniotto** [ethereum/go-ethereum#2639]
#### System information

I'm running Mist version 0.7.4 on Windows 10. 

#### Expected behaviour

I have been trying for over a week to sync the blockchain using fast sync but have been running into an issue where the sync appears to restart itself when there's only a few thousand blocks left to go. It appears to roll back a couple thousands headers around  Block 1606908, and then starts the sync again with a new peer (albiet at a much slower speed).

![geth fast sync cmd](https://cloud.githubusercontent.com/assets/7211130/15654162/6310967c-2657-11e6-84c5-7ee27a2192a5.png)

The issue seems related to Issue #2469. Is there any available workaround? The fast sync command below took 8 hours to get near the end before the restart.

#### Backtrace

````
geth --fast --cache=1024 --jitvm
````

**Comment by karalabe** [comment]
Try latest develop, or if your adventurous try https://github.com/ethereum/go-ethereum/pull/2630. I get fast sync in 25-30 mins flat (albeit on a 200mbit link). The PR I mentioned could especially help on poorer connections.

**Comment by karalabe** [comment]
This sync issue should be solved by our 1.4.6 release. Please check with that and report if it's still broken for you.

**Comment by hynese** [comment]
I hope it's appropriate for me to re-open this.

I'm on 1.4.6 on Ubuntu 16.04

When I delete ~/.ethereum/chaindata/*

And re-start geth:

`geth --fast console`

Days pass...

Everything fine...

Then I Ctrl+D in geth.

A few moments later I restart:

`geth --fast console`

fast sync is disabled! I have to delete everything in chaindata and restart...

```
I0621 23:19:28.560522 core/blockchain.go:208] Fast block: #1747043 [bd2635c4…] TD=29636013546513671717
I0621 23:19:28.578204 eth/handler.go:110] **blockchain not empty, fast sync disabled**
I0621 23:19:28.581229 p2p/server.go:313] Starting Server
```

**Comment by fjl** [comment]
That's intended. Fast sync runs only once for security reasons.

**Comment by fjl** [comment]
This issue was specifically about a bug where fast sync would restart a normal sync from block zero just after completing.

**Comment by hynese** [comment]
Apologies for confusing the issue. Thanks for explaining about the one-time fast sync'ing for security reasons. Very helpful information.

**Comment by ModGrip** [comment]
How do I know when fast sync has completed? Appears to still be running at higher than the current block number. "Processed 3660436" currently and rising.

**Comment by Arthur111** [comment]
> That's intended. Fast sync runs only once for security reasons.

fast sync must be disabled when the first time its sync.
Until its not sync the first time --fast must stay enabled.
Like this you can restart as you  want until its sync for the first time.
