### ISSUE TITLE
I always see Looking for peers in geth

### ISSUE THREAD

**Issue by raz0r007** [ethereum/go-ethereum#26399]
Hi,
**Geth 1.10.26** is not working on my **Linux** and I would like to know if the problem is mine or not.
I was able to sync blocks until 2 months ago but after that Geth gets stuck in "Looking for peers" forever...

<img width="607" alt="Screenshot 2022-12-31 at 16 36 32" src="https://user-images.githubusercontent.com/31778602/210144628-f507351c-1769-40f1-b710-0340f8645efd.png">

I wanted to know if anyone else had this problem.
I'm running geth in light mode: **./geth --syncmode light**

I have these ports enabled: 
30303/tcp
30303/udp
30304/tcp
30304/udp
8546/tcp

I also tried to remove the db and resync again: **./geth removedb --datadir=~/.ethereum**
...but the problem persists. I can sync some blocks up to 2-3 months ago and then it gets stuck...

Any idea?

**Comment by vehicles4real** [comment]
It's the brave browser and I don't really use chrome anymore

**Comment by raz0r007** [comment]
I'm sorry @vehicles4real I have no idea what you are talking about. I'm not running geth in a browser, but on Linux/ubuntu (command line).

**Comment by MariusVanDerWijden** [comment]
There are very little light servers out there, so it is hard to find peers with a light client. Also light client support is kinda broken after the merge. Zsolt is working on a new update for fixing the light client

**Comment by raz0r007** [comment]
@MariusVanDerWijden thank you so much for your answer.
3 questions:
1) I don't have enough space on my hard disk to do a full sync (I only have 300gb available). Is light-mode the only alternative currently ?
2) Is there an estimated date to fix it ?
3) What alternative do you suggest I do ? I tried to add peers manually using **admin.addPeer** but it doesn't work. After adding these peers I still see "Looking for peers" in the console (I searched for these pairs on public websites and they were all synced).

Thanks

**Comment by MariusVanDerWijden** [comment]
1) yes light mode is the only alternative with geth. I think nethermind has a syncmode that uses less than 300gb
2) No not yet, it will take some more time I think. Maybe @zsfelfoldi can weigh in here
3) You need peers that have the light server enabled, not many people do that, so its very unlikely to find someone. You could run a full node on another machine, with `--light.server 200` which starts serving light clients with 2 cores

**Comment by raz0r007** [comment]
That's a good idea, create my own light node and use it :)
However, if you know any public website to search for synced light nodes maybe it can be useful for me.
I only know this web: https://ethernodes.org but I can't see if the node supports light mode or not. So.. maybe that's the reason why **admin.addPeer** doesn't work for me (maybe I added nodes without supporting light mode).

**Comment by 0xpanicError** [comment]
> 1. yes light mode is the only alternative with geth. I think nethermind has a syncmode that uses less than 300gb
> 2. No not yet, it will take some more time I think. Maybe @zsfelfoldi can weigh in here
> 3. You need peers that have the light server enabled, not many people do that, so its very unlikely to find someone. You could run a full node on another machine, with `--light.server 200` which starts serving light clients with 2 cores

How many light clients can a single full node with light server enabled serve?
