### ISSUE TITLE
geth evm t8n report errors 

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#26397]
Currently if I crush t8n tool I get the following:

```
ERROR(10): failed unmarshaling env file: json: cannot unmarshal hex number > 64 bits into Go struct field stEnv.withdrawals of type hexutil.Uint64
Error: The command '/home/wins/.retesteth/default/start.sh --state.fork Shanghai --state.reward 0 --state.chainid 1 --input.alloc /dev/shm/bb68f808-345c-4771-947b-6f15a311dc8f/alloc.json --input.txs /dev/shm/bb68f808-345c-4771-947b-6f15a311dc8f/txs.rlp --input.env /dev/shm/bb68f808-345c-4771-947b-6f15a311dc8f/env.json --output.basedir /dev/shm/bb68f808-345c-4771-947b-6f15a311dc8f --output.result out.json --output.alloc outAlloc.json' exited with 2560 code. (EIPTests/bc4895-withdrawals/withdrawalsIndexBounds_Shanghai, fork: Shanghai, chain: default, block: 2)
```

But the error comes to stderr. would be nice to have an option to logout this error into a file like --output.errorlog 
Since I have ethereumjs implemented t8n tool as an RPC srvice, I can't neceserraly get stderr from it. 

I actually catch many errors by myself thus I am no testing the transition tool, but forge tests in a hope that hive will catch it. I doubt many people track hive now when t8n tool becomes more adopted. 
we don't have that many errors catched like this. mostly the blockchain building errors which t8n tool does not report, but I would like to introduce more fuzz-like bugs in the test for t8ntool to really stress it on inputs

**Comment by holiman** [comment]
The error codes are well defined: https://github.com/ethereum/go-ethereum/tree/master/cmd/evm#io-errors-10-20Just catch a non-zero exit, should be pretty simple?

**Comment by winsvega** [comment]
The command exit with code 2560

**Comment by MariusVanDerWijden** [comment]
Are you sure, looking at the code we only ever return the following errors: 
```	
ErrorEVM              = 2
	ErrorConfig           = 3
	ErrorMissingBlockhash = 4

	ErrorJson = 10
	ErrorIO   = 11
	ErrorRlp  = 12
```

**Comment by holiman** [comment]
IIRC, this was a false positive, the error-code came from some middleware script
