### ISSUE TITLE
Vendor all consensus critical dependencies

### ISSUE THREAD

**Issue by ebuchman** [ethereum/go-ethereum#264]
In the name of avoiding something like: http://sourceforge.net/p/bitcoin/mailman/message/33221963/

- [x] sha3
- [x] secp256k1
- [x] leveldb

Anything else?

**Comment by obscuren** [comment]
Agreed. They'll be merged in the repo

**Comment by obscuren** [comment]
Fixed in https://github.com/ethereum/go-ethereum/commit/4df2e1ef5c20ebd7004a595de7e6a032699106ad

`leveldb` not locked, unnecessary.

**Comment by ebuchman** [comment]
Sorry, what do you mean not locked? My concern was leveldb could introduce some minor change such that when new users `go get` they spawn a consensus fork. It doesn't have to be in the `go-ethereum` repo but would be good to keep it in `ethereum/leveldb` the way bitcoin core has `bitcoin/leveldb`. Just a precaution. Maybe it's over zealous.

**Comment by obscuren** [comment]
I'd say over zealous ;-) if you've an example on how this fork could come to exist I'm happy to reconsider.

**Comment by ebuchman** [comment]
So I don't have an example of a fork but I did stumble across the following:
https://github.com/bitcoin/bitcoin/issues/2770
and the bounty that resulted:
https://bitcointalk.org/index.php?topic=337294.0;all
and Greg Maxwell's point: 
`If a new version of LevelDB has changed in ways we don't understand, then those changes could result in chain forking.`
Of course that's probably the logic that led to the client crashing in the first place, since Mac users didn't grab the update. But every time a new user installs the software with `go get` it will pull the latest leveldb. Imagine someone bribes Jeff Dean, or Google starts a chain and modifies leveldb for it, or even maliciously. I don't think this should be taken lightly, especially since it requires nothing but a path change on our part. Of course we need to occasionally merge upstream leveldb changes, btu only after they are reviewed, a task which will we share with others in the cryptoecosystem (bitcoin in particular). 

It doesn't have to be in `go-ethereum`, but at least under the github `ethereum` organization.

**Comment by obscuren** [comment]
> Imagine someone bribes Jeff Dean, or Google starts a chain and modifies leveldb for it, or even maliciously.

Is valid enough for me. Will be locked.

**Comment by zelig** [comment]
full list of packages not under our control.
we totally should replicate fix versions of them under go-ethereum/vendor or sth

bitbucket.org/kardianos/osext
code.google.com/p/go.crypto
code.google.com/p/go.net 
github.com/rakyll/globalconf 
github.com/rakyll/goini
github.com/syndtr/goleveldb 
github.com/syndtr/gosnappy 
github.com/jackpal/go-nat-pmp
gopkg.in/fatih/set.v0 
github.com/robertkrimen/otto 
gopkg.in/qml.v1
github.com/howeyc/fsnotify

**Comment by ebuchman** [comment]
Nice work Victor. How'd you generate that?

Most of those do not appear consensus critical, so I'm not as concerned. Leveldb, networking stuff, and crypto definitely. I guess its good practice to vendor everything anyways though.

**Comment by fjl** [comment]
We might as well consider using Godep.

**Comment by fjl** [comment]
One might argue that Go compiler/runtime/stdlib are as "concensus critical" as leveldb. Should we fork Go? What if ethdev wants to start a blockchain fork? So many questions...

**Comment by ebuchman** [comment]
I'm starting to think we should fork Go and Github, too, just for good measure. Might as well just rewrite the whole operating system stack while we're at it :(

**Comment by tgerring** [comment]
+1 to explore using godep for more predictable builds

**Comment by tgerring** [comment]
Dependencies are now versioned with godep in commit 702218008ee2b6d708d6b2821cdef80736bb3224

To install godep, run `go get github.com/tools/godep`
To restore dependencies to committed versions, run `godep restore`

To update dependencies (new dependency or updated version), run `godep save ./...`
Make sure to add & commit folder `Godeps`
