### ISSUE TITLE
Ability to remove spam coins / nft’s without interacting with contract.

### ISSUE THREAD

**Issue by DesignPixelZ** [ethereum/go-ethereum#26408]
# Rationale

Why should this feature exist?
More and more people are getting scammed this way. They see the scam tokens, they want to remove it the from the wallet and when doing so they accept the contract without even noticing and get their wallets drained.

What are the use-cases?
Main use cases is to “keep your wallets clean” without interacting with token contracts.
# Implementation

Do you have ideas regarding the implementation of this feature?
Implementing should be hard, we need to bypass contract approval only if we decide to directly burn said tokens by sending them to null address. So, it shouldn’t affect anything and is more like a “opt out” feature.

Are you willing to implement this feature?
I would if I could, I’m not a programer, I don’t know how to code. i’m rising awareness as this seems to be a huge problem nowadays.

**Comment by karalabe** [comment]
This is unfortunately out of the scope of this repo. We're building the platform / network of Ethereum. Contracts and wallets are above and independent of us.

**Comment by DesignPixelZ** [comment]
> This is unfortunately out of the scope of this repo. We're building the platform / network of Ethereum. Contracts and wallets are above and independent of us.

I disagre, it’s a problem at network level / platform level if you can’t get rid of an airdroped scam token without interacting with the contract. Adding an option to directly remove them without having to interact with the wallet should be added to avoid scams.
