### ISSUE TITLE
Add clef importraw to its RPC methods

### ISSUE THREAD

**Issue by ferjep** [ethereum/go-ethereum#26405]
# Rationale

Why should this feature exist?
- Allow importing external wallets using RPC
What are the use-cases?
- Creating the same wallet for multiple nodes in different Ethereum compatible blockchains in runtime. 
Wallet could be created locally and imported to clef via RPC to each signer for each node (e.g ETH, BSC).

# Implementation

Do you have ideas regarding the implementation of this feature?
- Same as the other methods, I guess
Are you willing to implement this feature?
- I could, but I was fast reading the code and couldn't get how it works. I'm not a Go dev tho

**Comment by holiman** [comment]
Clef will not handle secret data on the public api. 
I think we already have it on the internal api.
