### ISSUE TITLE
Document --cache.preimages 

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum/go-ethereum#26403]
As discussed in https://github.com/ethereum/go-ethereum/issues/25638 calling `debug_getModifiedAccountsByNumber` can fail with `missing trie node` if we request accounts where the preimages have been deleted already. This can be solved with `--cache.preimages`. We should add some more documentation to the website about this. cc @jmcook1186

**Comment by jmcook1186** [comment]
addressed in #26436
