### ISSUE TITLE
Cannot Backup Database

### ISSUE THREAD

**Issue by ekawibisono** [ethereum/go-ethereum#26401]
Hello,

I want to backup my Database node, but an error like the picture shows. What are the correct steps for backing up the database?
![image](https://user-images.githubusercontent.com/22586872/210159645-c8f97b51-cb2f-4c6f-b1b2-ac1690249d5c.png)

Please help.

**Comment by bayuanderas** [comment]
Anjir

bayuanderas

Pada tanggal Min, 1 Jan 2023 09.48, Ekacitta Wibisono <
***@***.***> menulis:

**Comment by ekawibisono** [comment]
i'm sorry, problem has solved to thread link this
https://github.com/ethereum/go-ethereum/issues/2773
`geth export --datadir "directory" --syncmode "full" --cache 2048 backup.rlp fromBlockNumber toBlockNumber
rm directory/geth
geth --datadir "directory" init genesis.json
geth import backup.rlp --datadir "directory" --syncmode "full" --cache 2048`

**Comment by vehicles4real** [comment]
Okay what exactly do you want me to do?

**Comment by ekawibisono** [comment]
> 

I just want to back up data, but have got the solution. sorry if disturbing

**Comment by vehicles4real** [comment]
Mega app it's red with a M it gives you 50 gd free storage.
