### ISSUE TITLE
Allow searching logs in pending transactions

### ISSUE THREAD

**Issue by ethernomad** [ethereum/go-ethereum#2640]
#### System information

Geth version: 1.5.0-unstable-ab664c7e
OS & Version: Windows/Linux/OSX
#### Expected behaviour

The JSON-RPC api suggests that it should be possible to set up a filter for logs in pending transactions using `pending` for `toBlock`: 
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter
#### Actual behaviour

Only logs in confirmed transactions can be found.
#### Steps to reproduce the behaviour

Broadcast a transaction that creates a log. Keep searching for the log with toBlock: pending. It will only appear when the transaction is confirmed.

**Comment by fjl** [comment]
@bas-vk I think this is fixed on develop

**Comment by ethernomad** [comment]
Just tried develop and this doesn't work yet.

It also needs to be possible to get a transaction receipt for unconfirmed transactions.

**Comment by ethernomad** [comment]
FYI this is working on Parity.

**Comment by bas-vk** [comment]
@ethernomad, I'm currently working on this.
