### ISSUE TITLE
[website] Update READMEs for website branches

### ISSUE THREAD

**Issue by samajammin** [ethereum/go-ethereum#26417]
README should be updated to make sense here:
https://github.com/ethereum/go-ethereum/tree/website
Currently it looks a bit unprofessional with misc links to private docs

We should include info on:
- The tech stack (like we do here: https://github.com/ethereum/blog#tech-stack)
- How to edit a page
- How to add a page

**Comment by jmcook1186** [comment]
addressed in #26442 and #26430
