### ISSUE TITLE
[website] [BUG] Custom scrollbar styles

### ISSUE THREAD

**Issue by corwintines** [ethereum/go-ethereum#26416]
Custom scrollbar styles are only working on chrome based browsers. These also need to work in Firefox as well.

<img width="488" alt="Screen Shot 2022-10-09 at 9 08 04 AM" src="https://user-images.githubusercontent.com/15589226/194764405-a7409628-7bd9-47c5-a603-0ebd465e26b2.png">

**Comment by jmcook1186** [comment]
closing - might get reopened later
