### ISSUE TITLE
[website] Flick to light mode when open a search'ed page

### ISSUE THREAD

**Issue by nloureiro** [ethereum/go-ethereum#26422]
When I do a search in dark mode and click on a search result the UI goes to light mode really quickly and back to dark mode again.

this causes the sense of a Flickr screen

https://user-images.githubusercontent.com/1120748/208495135-168983ce-7854-46cb-b553-5f524e3c22d9.mov

**Comment by holiman** [comment]
Yeah, it's not "light mode" then "dark mode", it's "some default black/white mode" and then it loads the selected mode.

**Comment by nhsz** [comment]
Note: investigate if this issue is related with https://github.com/chakra-ui/chakra-ui/issues/6727

**Comment by nhsz** [comment]
Fixed by #26516
