### ISSUE TITLE
Memo: investigate why the trie iterator mutates the trie

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#2642]
The trie in theory should be a read only immutable data structure. However, by commenting out this line: https://github.com/ethereum/go-ethereum/blob/develop/trie/trie.go#L538 (which should arguably save quite a few allocs), the trie iterator tests fail. This seems to conclude that the iterator manages to modify the trie and/or reuse some buffers in a way that should not be allowed. This could point to an interesting issue and should definitely be investigate. In the mean time the current code does a copy to ensure that no strange thing will occur, even if only the iterator is buggy.

PS: Please don't close this issue until it's sorted out.

**Comment by fjl** [comment]
Trie keys are no longer shared since the conversion to pointer nodes.
