### ISSUE TITLE
[website] [UX IMPROVEMENT] Make the header and Left navigation sticky 

### ISSUE THREAD

**Issue by nloureiro** [ethereum/go-ethereum#26424]
To improve the navigation experience on the different pages, the header and left navigation should be sticky to the browser window.

This is a design good practice that is used in almost all Devdocs websites.

Header: Add background color and make it fixed on desktop and mobile

Left Navigation: Add background color,  make it fixed on desktop and mobile, and add overflow to scroll when the content doesn't fit the screen vertically.

Use-case example, using devtools in the browser to produce these screencasts

https://user-images.githubusercontent.com/1120748/208143113-5398b77d-0c09-442d-9db7-32b23f19f84a.mov

https://user-images.githubusercontent.com/1120748/208143251-f1f8f4c9-bd12-4b7c-b28c-e598918ce0b9.mov

cautions to the top border on the left navigation
![Screen Shot 2022-12-16 04 19 39 PM](https://user-images.githubusercontent.com/1120748/208142638-7c42a9f8-0a80-4591-a2aa-0a8054729d9a.png)

The content going under the header is on purpose.
![Screen Shot 2022-12-16 04 25 13 PM](https://user-images.githubusercontent.com/1120748/208144245-8538c6fa-53f7-483b-808f-94b746474d42.png)

**Comment by nloureiro** [comment]
> Could add a `filter: blur(x);` on the background so the text blurs as it rolls underneath

Yes, let's  go for:
backgournd transparency of 0.9
background blur of 10px

![Screen Shot 2023-04-04 12 11 25 AM](https://user-images.githubusercontent.com/1120748/229774416-5202ea64-9559-4272-af90-969cec4e56cd.png)

desktop > https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=3112%3A22484&t=CAOVt8xbTCnKymwI-1
mobile version > https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=2857%3A21520&t=CAOVt8xbTCnKymwI-1

**Comment by nhsz** [comment]
We've decided to abandon this feature for now as it needs further discussion/planning (both design & implementation) on how to deal with the layout refactor needed to implement this properly. Could be considered in future plannings for Geth site v2 iteration.

**Comment by Hektoreth** [comment]
I use phone all i have here ... I now is hard work with me bad language
sory i AM welder pc for me  magic any repozytories.. i now for 99 % is easy
I work with difrent specializarion please tray undorstand me

pon., 17 kwi 2023, 16:40 użytkownik Nicolás Quiroz ***@***.***>
napisał:
