### ISSUE TITLE
is there a way to found every contract deployed on chain ?

### ISSUE THREAD

**Issue by SharinganKazekage** [ethereum/go-ethereum#26431]
hello is there a way to found every contract of erc20 for exemple that has been deployed ? if yes how could i make this ? Thanks !

**Comment by karalabe** [comment]
We have a `debug` method that can iterate over a range of accounts and return their contents: https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugaccountrange . You could use that to fetch all accounts and their deployed bytecodes. You'd need to go through the bytecodes yourself and check if it conforms to the ERC20 spec (whether the methods are available or not). I'm assume there are libraries out there that can help in that aspect (ethers.js comes to mind and the 4byte database).
