### ISSUE TITLE
how to get contract function by transaction input？

### ISSUE THREAD

**Issue by laxpio** [ethereum/go-ethereum#2643]
#### System information

Geth version: `geth version`  1.3.6
OS & Version: Linux  
Commit hash : (if `develop`)

has the transaction info and contract address,but forget the abi,
it would get the abi or function by transaction input?

**Comment by karalabe** [comment]
There's no way to recover the ABI from the contract. Method signatures are hashed and only the first 4 bytes used by the contract, there isn't really a meaningful way to recover the signature from 4 bytes of hash data.
