### ISSUE TITLE
admin.saveinfo(contract.info) fail

### ISSUE THREAD

**Issue by laxpio** [ethereum/go-ethereum#2644]
#### System information

Geth version: 1.3.6
OS & Version: Linux
Commit hash : (if `develop`)

#### Actual behaviour
admin.saveinfo(contract.info,filename) fail,
error info: could not decode, json: cannot unmarshal string into Go value of type compiler.ContractInfo

#### Steps to reproduce the behaviour
do as url: https://github.com/ethereum/go-ethereum/wiki/Contracts-and-Transactions

source = "contract test { function multiply(uint a) returns(uint d) { return a * 7; } }"
// compile with solc
contract = eth.compile.solidity(source).test
// create contract object
var MyContract = eth.contract(contract.info.abiDefinition)
// extracts info from contract, save the json serialisation in the given file, 
contenthash = admin.saveInfo(contract.info, "~/dapps/shared/contracts/test/info.json")//fail in this step

#### Backtrace

````
[backtrace]
````

**Comment by zelig** [comment]
This is no longer supported and a module for code verification will come, see https://github.com/ethereum/solidity/pull/645
