### ISSUE TITLE
Issues with full archive sync with DB compaction

### ISSUE THREAD

**Issue by imulmat4** [ethereum/go-ethereum#26444]
#### System information

Geth version: `geth version`
1.10.26
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
lighthouse:3.2.1 
OS & Version: Windows/Linux/OSX
Ubuntu 22.04.1
Commit hash : (if `develop`)

#### Expected behavior
Sync without ~1-2Hr DB compaction times

#### Actual behaviour
I am seeing 2 hours of syncing followed by 1-2 hours of DB compaction. Which is making syncing so much slower than it has to be.

#### Steps to reproduce the behaviour
I am syncing a full archive node from genesis. My node has 128GB of RAM and 32 CPUs. The SSD that has my chaindata on it is an AWS EBS IO2 with 64k IOPS which should be more than enough. MY Geth Command line args are as follows:
--syncmode full --gcmode archive --mainnet --cache 102400 --maxpeers 100 --http --http.api personal,eth,net,web3,debug --ws --graphql --datadir /data/geth  --authrpc.addr localhost --authrpc.port 8551 --authrpc.vhosts localhost --ws.port 8546 --ws.api personal,eth,net,web3,txpool,debug -http.addr 0.0.0.0 -http.vhosts '*'geth --ws --ws.port 8546 --ws.origins "*" -ws.addr 0.0.0.0 --metrics --pprof --metrics.addr 127.0.0.1

Please let me know if I am missing anything here. One thing that I do notice is that despite me setting my cache to 100Gbs I dont see my memory consumption anyting close to that and it seems like things are single threaded???

#### Backtrace

````
[backtrace]
WARN [01-06|14:01:35.342] Snapshot extension registration failed   peer=92a3f6f8 err="peer connected on snap without compatible eth support"
WARN [01-06|14:02:03.732] Database compacting, degraded performance database=/data/geth/geth/chaindata
INFO [01-06|14:02:59.222] Writing clean trie cache to disk         path=/data/geth/geth/triecache threads=1
INFO [01-06|14:02:59.223] Regenerated local transaction journal    transactions=0 accounts=0
WARN [01-06|14:03:03.740] Database compacting, degraded performance database=/data/geth/geth/chaindata
INFO [01-06|14:03:16.590] Persisted the clean trie cache           path=/data/geth/geth/triecache elapsed=17.368s
WARN [01-06|14:04:03.746] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:05:03.754] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:06:03.761] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:07:03.770] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:08:03.778] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:09:03.783] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:10:03.792] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:11:03.799] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:12:03.804] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:13:03.809] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:14:03.814] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:15:03.825] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:16:03.832] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:17:03.840] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:18:03.847] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:19:03.853] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:20:03.863] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:21:03.872] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:22:03.880] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:23:03.887] Database compacting, degraded performance database=/data/geth/geth/chaindata
WARN [01-06|14:24:03.896] Database compacting, degraded performance database=/data/geth/geth/chaindata
INFO [01-06|14:24:32.935] Imported new chain segment               blocks=8  txs=1231  mgas=99.857  elapsed=1h33m39.488s mgasps=0.018   number=11,127,583 hash=92c3ce..02dbd9 age=2y2mo3w  dirty=0.00B

````

When submitting logs: please submit them as text and not screenshots.

**Comment by jsvisa** [comment]
Maybe you can increase the `WriteL0SlowdownTrigger` and `WriteL0PauseTrigger`, which will reduces the frequency of compression, eg: https://github.com/ethereum/go-ethereum/compare/master...jsvisa:go-ethereum:feature/optimize-leveldb

```go
		options.WriteL0SlowdownTrigger = 1024
		options.WriteL0PauseTrigger = 2048
```

**Comment by imulmat4** [comment]
Update:
I have switched to a Storage optimized node in AWS and using local NVME storage (i3en.6xlarge	24	192	2 x 7500 NVMe SSD) I have both my drives in a raid0 config and still seeing terrible performance with level DB. Are there any options to give geth/levelDB more resources? My node has 187 GB of ram and I am allocating 150 of it to the cache and still seeing terrible sync times.

**Comment by imulmat4** [comment]
@jsvisa That totally helped! Thanks so much
