### ISSUE TITLE
Invalid merkle root - on two separate servers, latest release

### ISSUE THREAD

**Issue by quakemmo** [ethereum/go-ethereum#26449]
#### System information

Geth version: `1.10.26`
CL client & version: lighthouse/nimbus/prysm@v3.1.2
OS & Version: Debian Linux 11, 128 GB of RAM, 6 TB SSD, i5 cpu
Commit hash :

#### Expected behaviour
Sync and keep running fine

#### Actual behaviour
Every few days, the fully synced node gets the invalid merkle root error, then quits keeping up with the network. I run TWO separate identical nodes on two different physical servers, it happens about once every 4-5 days to either one or the other. I then have to rewind with setHead a few thousand blocks back, or fully resync from scratch (if setHead doesn't help).

#### Steps to reproduce the behaviour
Launch cmdline:
```./geth --mainnet --http --http.api admin,eth,net,web3,txpool,personal,les,debug --http.corsdomain * --http.addr 0.0.0.0 --http.port 8546 --http.vhosts=* --port 0 --nat none --syncmode=snap --snapshot=false --maxpeers=100 --authrpc.jwtsecret /home/geth/jwt.hex```

#### Backtrace

````
         145: cumulative: 29861364 gas: 346913 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x292f63c6755db640be00a1cc24a932cfb07c87020e177c25d34b02570228c59b logs: [0xc09f035290 0xc09f035340 0xc09f0353f0 0xc09f0354a0] bloom: 00000000002000000000000000000000000000000000000000000100000000000880000010000000000000000008000000000000000100000000000000000000000000000000000000000008000000000000000000000800001000000000100000800000020000000000000000000800000000000000000000000010000000000000000000000000000200000000000000000000000000000000000010000000000000800000000000000000000000000000000000000020000000000000000000000002000000000008000000000000004000000200000000000000000020000000000001000000000000000000000040000000400000000000000000000000 state:
         146: cumulative: 29882364 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x83a34446328f830c14b8be9805d8282d267f9ad1f78e235bb6c2c103580ecedd logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:
         147: cumulative: 29929044 gas: 46680 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x6ed50f3567535635ebc9256906ae6963a648992991c7997af8f9cbbab649331d logs: [0xc09f035550] bloom: 00000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000008000002000000000000000000000000000040000000000000000000000040001000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000200000000000000000000200800000000000000000000000000000000000000000000000000000000 state:
         148: cumulative: 29950099 gas: 21055 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xa43b611f3a49750eefaa367ef1a7d6c0e193a4800b03c187f0bce9195206d5a6 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:


Error: invalid merkle root (remote: 6a203ae01ed15655c731a325e321f8a80791dc33324527399483e9308c4e28d0 local: 65cbf4ac72763e224058b0ebd1370fd8f7191e841753766927d28efe1e76333e)
##############################

WARN [01-08|09:42:37.129] NewPayloadV1: inserting block failed     error="invalid merkle root (remote: 6a203ae01ed15655c731a325e321f8a80791dc33324527399483e9308c4e28d0 local: 65cbf4ac72763e224058b0ebd1370fd8f7191e841753766927d28efe1e76333e)"

````

When submitting logs: please submit them as text and not screenshots.

**Comment by rjl493456442** [comment]
Feels like your database is corrupted. Do you have any unclean shutdown? (You can see it from startup logs)
 
`--snapshot=false` snapshot is disabled by you, so it's irrelevant with snapshot, only with trie itself.

You can check if your state database is fired by `geth snapshot traverse-state --datadir <your dir>`, but it will take probably the entire day to finish, or capture the corrupted state early.

**Comment by quakemmo** [comment]
There were no unclean shutdowns or any shutdowns at all.

Both nodes run properly for days, then one will have the invalid merkle root problem, and require massive amounts of massaging to start working again, sometimes setHead'ing back a little, sometimes a lot, sometimes requiring a DB wipe and resync from scratch.

**Comment by holiman** [comment]
Since you use `--snapshot=false `, you are running on 'raw trie', not using the snapshot acceleration structure. This means that any corruption should be pretty simple to find, we can just iterate the trie from the top, and see if it is indeed intact. 

I assume that it is not: some node is missing, and when a block is executed, the missing node causes the execution to see an account as "not existing" while in fact it does exist. 

And we do already have just a diagnostic command. `geth snapshot traverse-state`. 

Running that  will take quite some time, but after that we should know a bit more about the error.

**Comment by holiman** [comment]
This seems abandoned, closing
