### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by fzzr-** [ethereum/go-ethereum#2645]
#### System information

Geth Version: 1.4.4-stable-fc0638f9
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: darwin
OS & Version: OSX 10.11.5 (15F34)
#### Expected behaviour

Normal startup.
#### Actual behaviour

Crash at start, after network-interface connected.
#### Steps to reproduce the behaviour
1. No one network-interface connected (no access to the Network)
2. Wi-Fi network-interface turned on but not connected
3. Run the Mist
4. Wi-Fi connected (full access to the Network)
5. Crash when "Starting Ethereum node..." ![screen shot 2016-06-01 at 19 44 59](https://cloud.githubusercontent.com/assets/888526/15717840/d3dd781e-2839-11e6-8f6f-f17ca501b02f.png)
#### Backtrace

```
Node type: geth
Network: main
Platform: darwin

...I0601 19:34:41.674460   77218 database.go:71] Alloted 433MB cache to /Users/fzzr/Library/Ethereum/chaindata
I0601 19:34:43.481086   77218 database.go:71] Alloted 78MB cache to /Users/fzzr/Library/Ethereum/dapp
I0601 19:34:43.490474   77218 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0601 19:34:43.496802   77218 backend.go:362] Blockchain DB Version: 3
I0601 19:34:43.532746   77218 blockchain.go:214] Last header: #390796 [4b4d54fa…] TD=1959807436544906688
I0601 19:34:43.532800   77218 blockchain.go:215] Last block: #390796 [4b4d54fa…] TD=1959807436544906688
I0601 19:34:43.532819   77218 blockchain.go:216] Fast block: #390796 [4b4d54fa…] TD=1959807436544906688
I0601 19:34:43.535568   77218 handler.go:92] blockchain not empty, fast sync disabled
I0601 19:34:43.554377   77218 cmd.go:114] Starting Geth/v1.3.5/darwin/go1.5.1
I0601 19:34:43.562638   77218 server.go:311] Starting Server
```

**Comment by fjl** [comment]
Closing because this is a very old issue and is likely resolved in a later version.

**Comment by fzzr-** [comment]
I agree.
