### ISSUE TITLE
Add an `--exit-at` flag under Ethereum options

### ISSUE THREAD

**Issue by kamikazechaser** [ethereum/go-ethereum#26464]
# Rationale

Related to #24461

When setting up multiple sets of archive nodes each with their own range, it can be useful to stop a full node sync once a certain block target is reached.

**What are the use-cases?**

Setting up multiple archive node sets or "refreshing" archive node data.

# Implementation

**Do you have ideas regarding the implementation of this feature?**

I was thinking that the `--exit-at` flag should only be activated by the existing `--exitwhensynced` flag. The goroutine already listens for downloaded done block events and another if statement can be added to check if downloadedDoneBlock >= exitAtBlock and close the stack.

**Are you willing to implement this feature?**

Yes

**Comment by MariusVanDerWijden** [comment]
This became a bit easier after the merge. You could just ask geth to sync to a certain head in full sync. I believe @rjl493456442 already worked on something like this

**Comment by holiman** [comment]
Yep, can be achieved with this flag. With this option, you don't need a CL client either. It uses a "virtual" CL client which only ever feeds the given block to the EL. 

I don't know how geth behaves if the block is very early, before the merge. 
```
$ geth -h | grep target
    --synctarget value            
          File for containing the hex-encoded block-rlp as sync target(dev feature)
```
