### ISSUE TITLE
Bring back the --logfile flag

### ISSUE THREAD

**Issue by Firescar96** [ethereum/go-ethereum#2646]
#### System information

Geth version: 1.4.5-stable-a269a713
OS & Version: Debian
Commit hash : master
#### Expected behaviour

Log output to the provided file
#### Actual behaviour

The `js` command consumes all following output including my `2>> /path/to/file` and geth throws an error.
#### Steps to reproduce the behaviour

`geth js randomFile.js 2 >> /dev/null`
#### Backtrace

```
geth js randomFile.js 2 >> /dev/null                                                 1 ↵
I0601 22:37:08.089129 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/firescar96/.ethereum/chaindata
I0601 22:37:08.165794 ethdb/database.go:169] closed db:/home/firescar96/.ethereum/chaindata
I0601 22:37:08.166195 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/firescar96/.ethereum/chaindata
I0601 22:37:08.235254 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /home/firescar96/.ethereum/dapp
I0601 22:37:08.238660 eth/backend.go:172] Protocol Versions: [63 62 61], Network Id: 1
I0601 22:37:08.238819 eth/backend.go:201] Blockchain DB Version: 3
I0601 22:37:08.240278 core/blockchain.go:206] Last header: #1199583 [3576934b…] TD=10344961585528197150
I0601 22:37:08.240310 core/blockchain.go:207] Last block: #1199583 [3576934b…] TD=10344961585528197150
I0601 22:37:08.240323 core/blockchain.go:208] Fast block: #1199583 [3576934b…] TD=10344961585528197150
I0601 22:37:08.241728 p2p/server.go:311] Starting Server
I0601 22:37:10.201443 p2p/discover/udp.go:217] Listening, enode://4cac3b3c8b6ae089150d6ca5e968e5fb7175d47556f70f2e19d49417e4273bba666227d35d28feca962694cee0ad02585f6a3326386ab5fa1b622ace4ed822a6@[::]:30303
I0601 22:37:10.201755 p2p/server.go:554] Listening on [::]:30303
I0601 22:37:10.202169 node/node.go:298] IPC endpoint opened: /home/firescar96/.ethereum/geth.ipc
Fatal: JavaScript Error: open randomFile.js: no such file or directory
```

I believe this could be solved easily by reinstating the `--logfile` flag.

**Comment by Firescar96** [comment]
I submitted a pull request to address this: https://github.com/ethereum/go-ethereum/pull/2658

**Comment by fjl** [comment]
You can use `geth js somefile.js 2>/dev/null` to run without output.
If you want to log to a file, use `geth js somefile.js 2>/path/to/logfile.txt`.

**Comment by Firescar96** [comment]
What's the purpose of the number?

**Comment by fjl** [comment]
The number is part of shell syntax and redirects the 'standard error' stream (file descriptor no. 2).
All geth log output goes to stderr. We have chosen this setup because it is easier to handle when you want to run geth as a daemon through systemd or supervisord.

**Comment by fjl** [comment]
You are not the first person that is confused about our logging. I will address this by writing a wiki page.

**Comment by Firescar96** [comment]
Can you post a link when you finish?

**Comment by fjl** [comment]
Yes. Didn't find the time to do it yet.

**Comment by Firescar96** [comment]
Here is my use case, I'm using meteor for a visualization and need to start a geth instance on the server upon user request. I need the log output sent to a file and it's helpful for debugging to simultaneously send output to the console. 

I've been using my fork so far because it's easy to do there:

```javascript
let cmd = spawn('geth', ['--datadir=' + gethInstanceConfig.datadir, '--dev',
    '--logfile=' + gethInstanceConfig.logfile, '--port=' + gethInstanceConfig.port,
    '--rpc', '--rpcport=' + gethInstanceConfig.rpcport, 
    '--rpcaddr=' + gethInstanceConfig.rpcaddr, '--rpcapi=' + 
    gethInstanceConfig.rpcapi, '--networkid=' + gethInstanceConfig.networkid,
    '--rpccorsdomain=' + gethInstanceConfig.rpccorsdomain, '--unlock=0',
    '--password=' + gethInstanceConfig.password,
    '--bootnodes=' + gethInstanceConfig.bootnodes,
    '--maxpeers=' + gethInstanceConfig.maxpeers, 'js', gethInstanceConfig.js]);
```

I can still get both stdout and stderr using this method:

```javascript
cmd.stdout.on('data', (data) => {
  console.log(data.toString());
});
cmd.stderr.on('data', (err) => {
  console.error(err.toString());
});
```

but the best I've been able to come up with for ethereum/go-ethereum/develop is this broken code, which for some reason won't obey the pipe and log to the file.

```javascript
let cmd = spawn('geth', ['--datadir=' + gethInstanceConfig.datadir,
    '--port=' + gethInstanceConfig.port, '--rpc', '--rpcport=' +
    gethInstanceConfig.rpcport, '--rpcaddr=' + gethInstanceConfig.rpcaddr, '--rpcapi=' +
    gethInstanceConfig.rpcapi, '--networkid=' + gethInstanceConfig.networkid,
    '--rpccorsdomain=' + gethInstanceConfig.rpccorsdomain, '--unlock=0',
    '--password=' + gethInstanceConfig.password,
    '--maxpeers=' + gethInstanceConfig.maxpeers, 
    'js ' + gethInstanceConfig.js, '| tee', '-a', gethInstanceConfig.logfile]);
```

the strange thing is if I get the command being run from `ps aux | grep geth` and run it directly in the terminal everything works fine.

**Comment by Firescar96** [comment]
stalebot is right

**Comment by aqt01** [comment]
My use case is for docker. Actually I'm unable to create logfile using "2>> /path/to/file" from docker-compose.yml. I tried setting it on `entrypoint` and `command` with no results because docker understand it as an argument. Any ideas?
