### ISSUE TITLE
[website]: expand docs images on click

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/go-ethereum#26478]
Can we make images expand to fill the screen on-click? Right now images such as this one:

https://geth.ethereum.org/images/docs/grafana.png

are hard to see in their embedded size.

**Comment by nhsz** [comment]
any reference on how this should work?

**Comment by jmcook1186** [comment]
an example could be this from ethreum.org: you click on the embedded image and it opens full screen

https://ethereum.org/en/developers/docs/blocks/#why-blocks
