### ISSUE TITLE
[website]: update font sizes in LH side navigation

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/go-ethereum#26477]
Fonts in headings in LHS menu are slightly too large.
@nloureiro please confirm the size they should be changed to

**Comment by nhsz** [comment]
applies to this menu?

<img width="324" alt="Screen Shot 2023-02-01 at 18 15 23" src="https://user-images.githubusercontent.com/948922/216165005-d6992e86-6945-472f-a6b0-69721ce1cb39.png">

cc @nloureiro
