### ISSUE TITLE
logsBloom is null on pending blocks

### ISSUE THREAD

**Issue by ppratscher** [ethereum/go-ethereum#2648]
#### System information

Geth version: Lastest develop
OS & Version: Linux
Commit hash : N/A
#### Expected behaviour

geth should return the actual value of the logsBloom field of the pending block from the eth.getBlock("pending") call.
#### Actual behaviour

geth returns null in the logsBloom field

Rationale:
In order to calculate the HashNoNonce() value of the pending block the logsBloom field is required and is currently not provided by the RPC call. Without this value it is impossible for an external miner to check if the hash he is currently mining on really corresponds to a given block (prove of honesty during mining).

**Comment by fjl** [comment]
There is a conflict between this issue and #884 (which is old). I don't know what the right thing to do is.

@ppratscher what is the use case here? Where would the external miner ask for the pending block?
One cannot assume that the pending state is the same on every node so the only reasonable place to ask at is the pool that gave out the hash.

**Comment by ppratscher** [comment]
It can be used by miners to check the honesty of the pool. The pool provides the block hash and the corresponding pending block (which includes the pools coinbase address). The miners can then independently calculate the HashNoNonce from the given pending block and compare it to the block hash they are mining on.

In my opinion eth.getBlock("pending") should return the same information that is used to calculate the HashNoNonce value and not arbitrarily null some fields if they are used internally.
