### ISSUE TITLE
Is there a way to change the block hashing method of private Etherem?

### ISSUE THREAD

**Issue by AlirezaEthDev** [ethereum/go-ethereum#26499]
As all we know, Ethereum hashes blocks by Keccak-256 and this method used in private Ethereum too. Now, if we need to use Keccak-512 for hashing blocks in a PoA private Ethereum (For our project), what is the solution? Is it possible to change the hashing method? Can has a private Ethereum a hash method rather than what Ethereum mainnet has?

**Comment by rjl493456442** [comment]
You need to fork go-ethereum and apply the change you need. We can't do too much in this case.

**Comment by AlirezaEthDev** [comment]
@rjl493456442  Thanks, Do you mean fork Geth software or the PoA private network? If you mean Geth, Where is the Geth source code available and how can I get it?

**Comment by holiman** [comment]
> Can a private Ethereum have a hash method rather than what Ethereum mainnet has?

Yes, of course.

> Is it possible to change the hashing method? 

Yes, but you need to code it up yourself, and replace every single location in the code where the hashing is referenced. 

> Now, if we need to use Keccak-512 for hashing blocks in a PoA private Ethereum (For our project), what is the solution? 

It's a major programming task of doing all that work.  

> If you mean Geth, Where is the Geth source code available and how can I get it (I mean the subprogram that is related to hashing blocks)?

It's _here_. This is the go-ethereum repository. You will have to get your hands dirty and figure out for yourself what needs to be changed where. Good luck!

**Comment by AlirezaEthDev** [comment]
@holiman Thank you so much.
