### ISSUE TITLE
dont want empty block

### ISSUE THREAD

**Issue by cjango** [ethereum/go-ethereum#26511]
In private network, use Clique ,I don't want seal block,when there is no transactions.How can i do?

**Comment by cjango** [comment]
when i set in genesis.json
```
    "clique": {
      "period": 0,
      "epoch": 30000
    }
```
it cant sealing

**Comment by s1na** [comment]
You can communicate with the node via a script that keeps the miner disabled unless there are pending transactions. See the answer here: https://ethereum.stackexchange.com/questions/3151/how-to-make-miner-to-mine-only-when-there-are-pending-transactions/3152#3152

Save the script as a JS file and run:

```console
./build/bin/geth --datadir clique-data --preload mine.js attach
```

**Comment by cjango** [comment]
thank you.
