### ISSUE TITLE
How to enable trace_* related API?

### ISSUE THREAD

**Issue by YuXiaoCoder** [ethereum/go-ethereum#26528]
#### System information

Geth version: `1.10.26-stable`
CL client & version: `Prysm/v3.2.0/3d6d0a12dd189abcd2cfbba1c3d56505a1dd595c`
OS & Version: Linux

#### Expected behaviour
The trace_transaction method can be used normally to be compatible with other clients

#### Actual behaviour
{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method trace_transaction does not exist/is not available"}}

#### Steps to reproduce the behaviour
curl -X POST -H 'content-type:application/json' --data '{"jsonrpc": "2.0", "method": "trace_transaction","params": ["0x4c253746668dca6ac3f7b9bc18248b558a95b5fc881d140872c2dff984d344a7"],"id": 1}' http://127.0.0.1:8545

#### Backtrace

````
/opt/ethmain/core/geth --datadir=/mnt/ethmain/node/geth --networkid=1 --mainnet --syncmode=full --gcmode=archive --ipcdisable --http --http.addr=0.0.0.0 --http.port=8545 --http.vhosts=* --http.api=admin,eth,net,engine,web3,personal,debug,txpool,rpc --port=30303 --verbosity=3 --cache=4096 --config=/mnt/ethmain/conf/geth.toml --authrpc.addr=0.0.0.0 --authrpc.port=8551 --authrpc.vhosts=* --authrpc.jwtsecret=/mnt/ethmain/node/jwt.hex
````

**Comment by karalabe** [comment]
The `trace` namespace is not a standardized one. There are attempts by @s1na to standardize one and get is implemented by all clients. Until then, Geth's tracers are in `debug_`.
