### ISSUE TITLE
# github.com/ethereum/go-ethereum/crypto/secp256k1 cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%

### ISSUE THREAD

**Issue by werniq** [ethereum/go-ethereum#26533]
Good day, I've installed Geth and Mingw compiler, but still have thit problem. What should I do?

**Comment by hletrd** [comment]
Did you add the MinGW bin directory(probably C:\mingw\bin in default setup) to the PATH environment variable?

**Comment by werniq** [comment]
No, I don't. Could you please explain how can I achieve this?

**Comment by hletrd** [comment]
You may follow the instructions here: https://stackoverflow.com/questions/5733220/how-do-i-add-the-mingw-bin-directory-to-my-system-path
