### ISSUE TITLE
[website] redirects not working

### ISSUE THREAD

**Issue by corwintines** [ethereum/go-ethereum#26538]
Discovered through a broken link in: https://github.com/ethereum/ethereum-org-website/pull/9268

#### System information
Using brave on a Mac, but this happens on any system.

#### Expected behaviour
An example from above PR
1 - user goes to https://geth.ethereum.org/docs/clef/introduction
2 - user gets redirected properly to https://geth.ethereum.org/docs/tools/clef/introduction

#### Actual behaviour
1 - User goes to https://geth.ethereum.org/docs/clef/introduction
2 - 404 page

**Comment by corwintines** [comment]
Potential to look into. Do we need to do redirects the Netlify way like we do on ethereum.org?

**Comment by Tamrot** [comment]
hi @corwintines go to the [official page](url) to initiate a chat with an agent on a live chat to report this issue for review and for further assistance via [Ether support](http://ethersupport.org)
