### ISSUE TITLE
Support content type 'text/plain' for HTTP based JSON-RPC requests 

### ISSUE THREAD

**Issue by tolga-coplu** [ethereum/go-ethereum#26547]
As far as I investigated `go-etheretum` supports the following `content-types` in HTTP based JSON-RPC requests ([referred code](https://github.com/ethereum/go-ethereum/blob/59a48e0289b1a7470a8285e665cab12b29117a70/rpc/http.go#L41)) 
- application/json
- application/json-rpc
- application/jsonrequest

 `ethers-io/erhers.js` seems to add support for `text/plain` `content-type` with its new version 6. Related code line https://github.com/ethers-io/ethers.js/blob/v6/src.ts/utils/fetch.ts#L221. When I run client test with the `ethers` v6_beta, I receive `Error: server response 415 Unsupported Media Type`. 

When `text/plain` added to [acceptedContentTypes](https://github.com/ethereum/go-ethereum/blob/59a48e0289b1a7470a8285e665cab12b29117a70/rpc/http.go#L41) slice, the issue is resolved.

My question is  -> Is this a reasonable change for go-ethereum ecosystem to support other client libraries? 

Test code to reproduce the issue. 
Please first install the ethers v6_beta version.
`npm install ethers@6.0.0-beta-exports.10`
 
Then, set the environment/url and run a simple request. 

`import { ethers } from 'ethers'`
`  (async () => {`
`    const provider = new ethers.JsonRpcProvider(env)`
`    const block = await provider.getBlock('latest')`
`    console.log('block', block)`
`  })();`

**Comment by holiman** [comment]
I don't see any reason why geth would accept/respond on text/plain queries for json-rpc requests. 

@ricmoo is that accurate^ ? Please shed some light on this..

**Comment by ricmoo** [comment]
This has already been [fixed](https://github.com/ethers-io/ethers.js/commit/e55a87ad4c355743fd68c88e21e92d46b1c92694) in the v6 beta branch. It was a consequence of how the new FetchRequest works and how it was used, but it was definitely a bug.

I don’t think it makes too sense to add, as it is east for clients to “do the right thing”. The only reason I sometimes wish it was more flexible is when using curl, but this seems like a fairly weak reason. :)

**Comment by holiman** [comment]
Thanks for the quick response @ricmoo !
Closing
