### ISSUE TITLE
Geth Reboots with geth.service: Failed with result 'signal'.

### ISSUE THREAD

**Issue by KrisSodroski** [ethereum/go-ethereum#26546]
#### System information

Geth
Version: 1.10.26-stable
Git Commit: e5eb32acee19cc9fca6a03b10283b7484246b15a
Architecture: amd64
Go Version: go1.18.5
Operating System: linux
GOPATH=
GOROOT=go

Since a couple months ago, geth has been randomly restarting with 

`geth.service: Failed with result 'signal'.` 

I cannot figure out why it is happening.  Teku seems to hum along no issue, and the error logs don't show anything except that it was killed for some reason.

After this happens, geth is always in an unclean state, and my node goes down for 3 hours or so.  

Any help is much appreciated

Error Log:
[geth-signal.txt](https://github.com/ethereum/go-ethereum/files/10494316/geth-signal.txt)

Disagnostics, though, these are just teku diagnostics if I'm not mistaken:
![image](https://user-images.githubusercontent.com/75279046/214429717-730f5295-a370-4171-8a1f-88d4ff8fbcf5.png)

![image](https://user-images.githubusercontent.com/75279046/214429894-527fe407-03c2-4db3-95fc-86c9db6d3ffd.png)

**Comment by holiman** [comment]
```
Jan 24 14:20:57 broli systemd[1]: geth.service: Main process exited, code=killed, status=9/KILL
```
So, something on your system is sending signal `9` ,or `SIGKILL` to the process, killing it. I can't say what it is, perhaps the OOM-reaper? If you peruse your system logs around the time this is happening, they should tell you more. 

If you are using geth via docker, and have set docker memory limits, that's a possible cause too. Either way, I'm pretty certain that the cause is a signal sent from externally, this is not geth itself crashing.

**Comment by KrisSodroski** [comment]
Thanks for taking a look @holiman. 

I'm not using a docker container.  I'm running on the base operating system.  

It happened again this morning, and I was able to isolate all the logs around that time.  This maybe looks like a ram issue to me?  It seems to fail allocation maybe?  

I have 16gb, maybe that's not enough these days.  What are your thoughts?

[geth2.txt](https://github.com/ethereum/go-ethereum/files/10536961/geth2.txt)

**Comment by holiman** [comment]
The logs say:

broli kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/geth.service,task=geth,pid=23622,uid=1001 Jan 30 09:54:57 broli kernel: Out of memory: Killed process 23622 (geth) total-vm:13865544kB, anon-rss:8877648kB, file-rss:0kB, shmem-rss:0kB, UID:1001 pgtables:21252kB oom_score_adj:0 Jan 30 09:54:59 broli systemd[1]: geth.service: Main process exited, code=killed, status=9/KILL Jan 30 09:54:59 broli systemd[1]: geth.service: Failed with result 'signal'.

**Comment by KrisSodroski** [comment]
Yeah, I bought some more ram.  Ty for taking a look.
