### ISSUE TITLE
Fetching block info on some L2 chains fails

### ISSUE THREAD

**Issue by rokn** [ethereum/go-ethereum#26542]
#### System information

Geth version: v1.10.25
OS & Version: OSX (probably will reproduce on all)

#### Expected behaviour
When fetching info for a block with `client.BlockByNumber` fails on some L2 chains with:
`transaction type not supported` as the lib fails to parse the transaction types which are not 0, 1 or 2. For example this block on Optimism Goerli testnet:
https://goerli-optimism.etherscan.io/txs?block=4567220
I've tested this on Optimism and Arbitrum testnets and they both fail for the same reason.

#### Actual behaviour
Fetch the block correctly without failing.

#### Steps to reproduce the behaviour
A minimal example:
```go
func main() {
	rpc := "https://goerli.optimism.io"
	client, err := ethclient.Dial(rpc)
	if err != nil {
		log.Fatal(err.Error())
	}
	log.Printf("Connected with chain at %s\n", rpc)
	block, err := client.BlockByNumber(context.Background(), big.NewInt(4061225))
	tx, _ := client.TransactionReceipt(context.Background(), common.HexToHash("0x05165a474a7a6386be0232fce515c793875e91e958133f673588db509dc5ece8"))
	log.Println(tx.Type)
	if err != nil {
		log.Println(err)
		return
	}

	log.Println(block.Time())
	return
}
```

**Comment by holiman** [comment]
The transaction is from `0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001` -- an optimism system address. So yeah, the transaction is a special type which is not supported by Ethereum Mainnet. And geth is an ethereum mainnet client, and we do not have the capacity to suppor a lot of the sidechain/subchain/l2-chain custom things.

**Comment by ybina** [comment]
replace your ethereum repository to OffchainLabs in your go.mod, then problem solved

`replace github.com/ethereum/go-ethereum v1.12.2 => github.com/OffchainLabs/go-ethereum v0.0.0-20230822203130-9a31b6205dba`

![image](https://github.com/ethereum/go-ethereum/assets/93298258/f62b0373-5c03-409c-b139-a3f8d6ea45f8)
