### ISSUE TITLE
Add tap command for brew installing solc 

### ISSUE THREAD

**Issue by laboon** [ethereum/go-ethereum#2654]
#### System information

Geth version: N/A
OS & Version: OSX 10.11 (El Capitan)
Commit hash : N/A

In the wiki, the Contract-Tutorial.md file (https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial) does not mention that you should tap ethereum/ethereum before installing cpp-ethereum.  Without doing this, an error appears.

The line "brew tap ethereum/ethereum" should be added before the line "brew install cpp-ethereum" on the wiki page.

If ethereum/ethereum has not previously been tapped, then that repo will be added.  If it has already been tapped, the command does not do anything.  Therefore, no matter what the state of the brew system, including this command should cause no problems for people, but will solve the problem of somebo
#### Expected behaviour

==> Installing cpp-ethereum from ethereum/ethereum
==> Tapping homebrew/versions
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-versions'...
...
#### Actual behaviour

Error: No available formula with the name "cpp-ethereum" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
#### Steps to reproduce the behaviour
1. Precondition: ethereum/ethereum has not been tapped
2. Execution steps: Run "brew install cpp-ethereum"
#### Backtrace

N/A

**Comment by ted-piotrowski** [comment]
Referring to:
[https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial#install-solc-on-mac-osx](https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial#install-solc-on-mac-osx)

The solc compiler is no longer located with in cpp-ethereum. The correct command should be. 

```
brew install solidity
```

As the comment above explains, `ethereum/ethereum` needs to be tapped prior to install.

**Comment by fjl** [comment]
fixed
