### ISSUE TITLE
Can I change the Consensus functionality of allowing every node to become a singer/ validator in our blockchain network? after cloning Ethereum from github

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#26557]
Hello! 

Currently, I am trying to add the functionality of Clique PoA to my own network called test poa in which my focus is on the addition of a new consensus engine for my test network called test poa.

Thanks!

**Comment by karalabe** [comment]
I mean, you are free to change the consensus on your fork however you'd like, but we don't have the capacity to offer support on such endeavors. Consensus engines generally are very brittle and each decision behind every behavior was carefully thought over. Making deep changes will most probably draw after itself significant consequences that you'll need to evaluate yourself.
