### ISSUE TITLE
failure - can't build merkle tree

### ISSUE THREAD

**Issue by rashley60** [ethereum/go-ethereum#26551]
Geth version: 1.10.26
CL client & version: e.g. lighthouse 3.3.0
OS & Version: Linux Debian 11

system has been synced and running with lighthouse since just before the merge. out of the blue last night, geth started failing with this error. 

```
Jan 25 07:11:34 haro geth[704]: Hash: 0xbf9e140599e92ab6225050519cea8848088779489586d91312e549f11b0ad637
Jan 25 07:11:34 haro geth[704]:          0: cumulative: 145158 gas: 145158 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x1a57a9e74c518e6117bc524467a18d26c42aa33cdc71fd729fa4927c4edf7dd5 logs: [0xc06e9aa000 0xc06e9aa0b0 0xc06e9aa160] bloom: 00000002000000000040000000000000000000000000000000000000000000000000000000080000000000000000000002000000080020010000000000000000000000000000000800000008000000000000000000000000000000000000040000000000000000000000100000000000000000000000000000000010000800000000000000000000000000000000000000000000000000000000000000000000000000002000020000000000800000000000000000000000000000020010001000000002000000000000000008000000000000000000000000000000000000080000200000000000000000000000000000000000000000000000000200000000 state:
...
Jan 25 07:11:34 haro geth[704]:          214: cumulative: 16562326 gas: 22111 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xfed4a67d0619dc5d452f21fd97bcaa457ee0fabe69b815ba27fb6b6b7a8a4185 logs: [0xc06fa3a0b0] bloom: 00000000000000000000000000000000000100004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000 state:
Jan 25 07:11:34 haro geth[704]: Error: invalid merkle root (remote: a028edf8e15795bb8c292e0b977020f5e65cd0be93000e83c4f42599056574bf local: 0a7d5797d8cf598e51fdb8d6f3ac4492c0a2e5386002e4046f9a407d9807eb75)
Jan 25 07:11:34 haro geth[704]: ##############################
Jan 25 07:11:34 haro geth[704]:  
Jan 25 07:11:34 haro geth[704]: WARN [01-25|07:11:34.889] NewPayloadV1: inserting block failed     error="invalid merkle root (remote: a028edf8e15795bb8c292e0b977020f5e65cd0be93000e83c4f42599056574bf local: 0a7d5797d8cf598e51fdb8d6f3ac4492c0a2e5386002e4046f9a407d9807eb75)
```

The service file I'm using to set this up is;
```
[Unit]
Description=Geth Execution Client (Mainnet)
After=network.target
Wants=network.target

[Service]
User=geth
Group=geth
Type=simple
Restart=always
RestartSec=5
ExecStart=/usr/local/bin/geth --mainnet --datadir /var/lib/geth --authrpc.jwtsecret /var/lib/jwtsecret/jwt.hex

[Install]
WantedBy=default.target

```

**Comment by rashley60** [comment]
I should say, after restarting the machine, geth failed with the error. I don't know what the original error was.

**Comment by MariusVanDerWijden** [comment]
Hmm that could be because of a fried disk. Could you try to check your disk?
Do you have `unclean shutdowns` when you started up the node?

**Comment by rashley60** [comment]
> Hmm that could be because of a fried disk. Could you try to check your disk? Do you have `unclean shutdowns` when you started up the node?

I do recall seeing an 'unclean shutdown' sometime during my mad dash toward fixing this. I'll do a bit of disk detecting but I'm probably going to rm the data dir and use a checkpoint sync to see if that corrects things.

**Comment by holiman** [comment]
RestartSec=5


If this means what I think it does, it is too low. You should give geth at least 2 minutes gracetime to exit.

**Comment by rashley60** [comment]
> RestartSec=5 If this means what I think it does, it is too low. You should give geth at least 2 minutes gracetime to exit.

I'll change that to 120 right away. 

BTW I'm resigned to the fact that I'm headed to resyncing from scratch after checking disk health. I'm thinking checkpoint sync is the way to go since I don't want to wait another 4 or 5 days.

**Comment by rashley60** [comment]
> Hmm that could be because of a fried disk. Could you try to check your disk? Do you have `unclean shutdowns` when you started up the node?

smartctl -a /dev/dsa2 show no errors. I think the disk is ok.

**Comment by rashley60** [comment]
I did a checkpoint sync with my CL and restarted geth 24 hours ago. It still hasn't started syncing. It still shows the invalid merkle tree with the same remote and local values. I think I'm going to need to blow the datadir away and start from scratch. Grrr..

**Comment by holiman** [comment]
> I think I'm going to need to blow the datadir away and start from scratch. Grrr..

Just do `geth <args> removedb` and then answer `n` (no) when it asks whether to delete the ancients. If you leave them in place, you save ~400 GB download. 

> 1.10.26

I'd recommend using `master` instead.

**Comment by holiman** [comment]
> It still hasn't started syncing. It still shows the invalid merkle tree with the same remote and local values.

Yeah that's not going to change. It will not "heal" itself, that much I can guarantee. Resync

**Comment by holiman** [comment]
Not much further to do here, closing
