### ISSUE TITLE
Found deprecated node list file /home/ethereum/.ethereum/geth/static-nodes.json, please use the TOML config file instead.

### ISSUE THREAD

**Issue by navy665180** [ethereum/go-ethereum#26558]
#### System information
i am in china and run a validator at home ,when i start geth ,it :looking for peers for hours.then ,i copied  static-nodes.json ,to the`/home/ethereum/.ethereum/geth` . and restart geth .it warn:
```
Found deprecated node list file /home/ethereum/.ethereum/geth/static-nodes.json, please use the TOML config file instead
```
.   ad go on looking for peers.
i can't find how to solve it.

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by holiman** [comment]
The `static-nodes.json` is deprecated, meaning we will cease support for that in the future. 
If you want to keep using the static peer-nodes in your file, you need to move them to a config (toml) file. See https://geth.ethereum.org/docs/fundamentals/peer-to-peer#static-nodes

Example: 
```toml
StaticNodes = ["enode://f4642fa65af50cfdea8fa7414a5def7bb7991478b768e296f5e4a54e8b995de102e0ceae2e826f293c481b5325f89be6d207b003382e18a8ecba66fbaf6416c0@33.4.2.1:30303"]
```
