### ISSUE TITLE
Concurrent RPC calls cause ephemeral port exhaustion

### ISSUE THREAD

**Issue by SuchJitter** [ethereum/go-ethereum#26578]
When using multiple goroutines to fetch data from the RPC using go ethereum, all ports start to get used, until no ports are available. Is there some sort of keepAlive or reusing of tcp connections?

error:

Post "http://xxx.xxx.xx.xxx:8545": dial tcp xxx.xxx.xx.xxx:8545: connect: cannot assign requested address

**Comment by s1na** [comment]
You must be issuing a loot of RPC requests! There is an option to batch requests. They will be however processed serially within Geth. The way you do it is put all the json-rpc request objects in a list, i.e. `[{ id: "", method: ""...}]`. Also see https://geth.ethereum.org/docs/interacting-with-geth/rpc/batch

**Comment by karalabe** [comment]
Use websockets, that will leave the connection open for followup requests.
