### ISSUE TITLE
hello, I get this error during installation, you don't know what the problém is

### ISSUE THREAD

**Issue by david739** [ethereum/go-ethereum#26594]
hello, I get this error during installation, you don't know what the problém is

go: finding github.com/cespare/cp v0.1.0
go: finding golang.org/x/crypto v0.0.0-20210921155107-089bfa567519
go: finding github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.3.0
build github.com/Azure/azure-sdk-for-go/sdk/azcore: cannot load github.com/Azure/azure-sdk-for-go/sdk/azcore: no Go source files
make: *** [Makefile:12: geth] Error 1

**Comment by rjl493456442** [comment]
Perhaps try to build directly? `go install ./cmd/geth`
