### ISSUE TITLE
Feature request: ability to prune the old ancient blockchain data

### ISSUE THREAD

**Issue by jsvisa** [ethereum/go-ethereum#26596]
# Rationale

I'm running a new snap-sync node, after the syncing progress, found the local chaindata consuming 800+GB, and half of the disk is used to store the ancient data:

```bash
$ du --max-depth=1 -h data/geth/chaindata
422G    data/geth/chaindata/ancient
830G    data/geth/chaindata
```

The old ancient data is useless in most cases, so if we support the ancient data pruning, we can use fewer disks. 

# Implementation

Seems the [binance smartchain](https://github.com/bnb-chain/bsc) has supported this feature(merged in [#543](https://github.com/bnb-chain/bsc/pull/543)) maybe we can backport this feature into go-ethereum. 

```bash
$ ./bin/bsc snapshot prune-block --help
prune-block [command options]

geth offline prune-block for block data in ancientdb.
The amount of blocks expected for remaining after prune can be specified via block-amount-reserved in this command,
will prune and only remain the specified amount of old block data in ancientdb.
the brief workflow is to backup the the number of this specified amount blocks backward in original ancientdb
into new ancient_backup, then delete the original ancientdb dir and rename the ancient_backup to original one for replacement,
finally assemble the statedb and new ancientDb together.
The purpose of doing it is because the block data will be moved into the ancient store when it
becomes old enough(exceed the Threshold 90000), the disk usage will be very large over time, and is occupied mainly by ancientDb,
so it's very necessary to do block data prune, this feature will handle it.


ETHEREUM OPTIONS:
                                      --datadir value                       Data directory for the databases and keystore (default: "/home/amber/.ethereum")
                                      --datadir.ancient value               Data directory for ancient chain segments (default = inside chaindata, '${datadir}/geth/chaindata/ancient/')
                                      --block-amount-reserved value         Sets the expected remained amount of blocks for offline block prune (default: 0)
                                      --triesInMemory value                 The layer of tries trees that keep in memory (default: 128)
                                      --check-snapshot-with-mpt             Enable checking between snapshot and MPT
```

**Comment by rjl493456442** [comment]
There is an EIP for it https://eips.ethereum.org/EIPS/eip-4444, the challenge of it is how can we have a strong guarantee that the dropped historical chain data can still be retrievable. I believe this challenge is not resolved yet.

While as a short-term solution, you can specify the ancient directory to a HDD-based location, it's still performant enough but kind of cheaper to use HDD.

**Comment by nuliknol** [comment]
@rjl493456442 you are right, geth needs to distinguish between an HDD and SSD since these storage devices are completely different. An SSD will lose data over years of no-access (NAND flash leaks charged particles over time), but HDD will have it permanently stored since the mechanics of storing mechanism is based on magnetism. If you store archived blocks on SSD, in about 2 years the data will be lost. If you store it on HDD, it can last 10 to 20 years. Software must treat each storage device accordingly
