### ISSUE TITLE
Feature request: add an argument to alter the default TriesInMemory

### ISSUE THREAD

**Issue by jsvisa** [ethereum/go-ethereum#26598]
# Rationale

Currently Tries to keep in memory are hardcoded to 128: https://github.com/ethereum/go-ethereum/blob/793f0f9ec860f6f51e0cec943a268c10863097c7/core/blockchain.go#L99
In some cases, we need more states for full-node(eg: 1024), but no need to run an archive node, so if the value can be altered by the command line, it's more usable.

similar issue: https://github.com/ethereum/go-ethereum/issues/20625

**Comment by holiman** [comment]
Here be dragons. 

A user who is power-user enough to know the consequences of tuning this knob is also knowledgeable enough to modify the code and recompile. 

If we expose these internal intricate details as easily modifiable parameters, we just open up for people shooting themselves in the feet.
