### ISSUE TITLE
Yosemite dmg image

### ISSUE THREAD

**Issue by joeykrug** [ethereum/go-ethereum#266]
The go client Mist dmg doesn't run on Yosemite.  It simply exits out immediately after clicking on it --- installing with brew works

**Comment by obscuren** [comment]
Odd. I have Yosemite myself and it seems to open fine. Where did you download the the `.dmg` from?

**Comment by scottzer0** [comment]
i downloaded it from: http://build.ethdev.com/builds/OSX%20Go%20develop%20branch/latest/app/

the app packages opens and then quit immediately.  is there some logging i can dig into from this package?

**Comment by obscuren** [comment]
Confirmed. The auto builds don't seem to be working.

**Comment by jorisbontje** [comment]
This is the error message that I see when opening Mist.app from the console:
```
$ /Applications/Mist.app/Contents/MacOS/Mist
2015/01/26 11:29:17 [CLI] Main address da69bd525e82c34995827d649f3ee07c503c34e7
2015/01/26 11:29:27 [CHAIN] Last block (#0) 779b1b620b03c0fb24963e183d5e88e3dbe4484e3f6e2aa05942e3be7b48e179
ETH stack took 10.010417371s
2015/01/26 11:29:27 [GUI] Starting GUI
2015/01/26 11:29:27 [CLI] Starting Mist/v0.7.9/darwin/go1.4
2015/01/26 11:29:27 [SERV] Ready and accepting connections
2015/01/26 11:29:27 [JSRE] started
2015/01/26 11:29:27 [GUI] asset not found: you can set an alternative asset path on the command line using option 'asset_path' file:////Applications/Mist.app/Contents/Resources/qml/main.qml.:1 module "QtQuick" plugin "qtquick2plugin" not found
panic: file:////Applications/Mist.app/Contents/Resources/qml/main.qml.:1 module "QtQuick" plugin "qtquick2plugin" not found
...
```

**Comment by jorisbontje** [comment]
As commented by @arkpar:
```
Hi, we have the same problem with mix here. It is basicly described here: http://qt-project.org/forums/viewthread/50118
The script linked there resolves it. It should be run after macdeployqt
Here is a link to the script: http://dshav.com/apps/script.sh
```

**Comment by caktux** [comment]
@scottzer0 That link is no longer the latest, new one probably has the same problem though: http://build.ethdev.com/builds/OSX%20Go%20develop%20branch/Mist-OSX-latest.dmg

**Comment by caktux** [comment]
The good latest dmg actually seem to work

**Comment by caktux** [comment]
See ethereum/go-build#9
