### ISSUE TITLE
debug_traceblockbyhash does not return calls array i.e. []callframe

### ISSUE THREAD

**Issue by Haider-Ali-DS** [ethereum/go-ethereum#26600]
#### System information

Geth version: 
```
Version: 1.10.26-stable
Architecture: amd64
Go Version: go1.19.3
Operating System: darwin
```

OS & Version: OSX

#### Expected behaviour
```
Array [
    Object {
        "result": Object {
            "calls": [...],
            "from": String("0x18650f136a0d8a6851a73099aa3f63c89957e1c7"),
            "gas": String("0x0"),
            "gasUsed": String("0x0"),
            "input": String("0x"),
            "output": String("0x"),
            "to": String("0xe8e4eda875a66734120769f85675c6426cd73e5a"),
            "type": String("CALL"),
            "value": String("0x2b5e3af16b1880000"),
        },
    },
]
```

#### Actual behaviour
```
Array [
    Object {
        "result": Object {
            "from": String("0x18650f136a0d8a6851a73099aa3f63c89957e1c7"),
            "gas": String("0x0"),
            "gasUsed": String("0x0"),
            "input": String("0x"),
            "output": String("0x"),
            "to": String("0xe8e4eda875a66734120769f85675c6426cd73e5a"),
            "type": String("CALL"),
            "value": String("0x2b5e3af16b1880000"),
        },
    },
]
```

#### Steps to reproduce the behaviour
* Ran geth in dev mode `geth --dev --http --http.api eth,debug,admin,txpool,web3`
* made a transaction after attaching geth 
* `eth.sendTransaction({from: eth.coinbase, to: "0xe8E4edA875a66734120769F85675c6426cD73e5a", value: web3.toWei(50, "ether")})`
* tried to hit rpc `debug_traceblockbyhash` with `block_hash` and tracer as
```
{ 
            "tracer": "callTracer"
}
```

but not able to get calls array in response

**Comment by s1na** [comment]
Your transaction is a simple eth transfer which doesn't have subcalls. The `calls` fields is omitted when it is empty. If you try on a block with contract execution containing calls you should get the expected result. Please re-open the issue if that's not the case.
