### ISSUE TITLE
[website]: add warning to downloads page re IoS and Android

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/go-ethereum#26601]
IoS and Android are [no longer supported](https://github.com/ethereum/go-ethereum/pull/26599) - the historical downloads can stay (i.e. no changes to downloads table) for now, but we need a warning note on the page to alert people to the fact that no new builds will be provided for these platforms.

e.g. `<Note> Please note that Geth no longer releases builds for IoS or Android.
IoS and Android builds available on this page are archival and are not consistent with current Geth
</Note>`

tagging @nloureiro in case this needs some design consideration.

the PR to remove mobile related code from the geth repo is already merged.

**Comment by nhsz** [comment]
Fixed by #26605
