### ISSUE TITLE
Synchronisation failed: no peers to keep download active

### ISSUE THREAD

**Issue by wainersec** [ethereum/go-ethereum#2661]
#### System information
Geth
Version: 1.4.5-stable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.6

#### Expected behaviour
 Blockchain should synchronize continuously.

#### Actual behaviour

After arround 10 minutes of blockchain synchronizing it stucks with the following message:
I0604 20:40:24.547415 eth/downloader/downloader.go:278] Synchronisation failed: no peers to keep download active

If I leave it there, it downloads just a few blocks every a few hours/several minutes (eg. 100 blocks per hour) If I exit geth and start it again I get it to synchronize at a rate of 256 blocks every 15/20 seconds (I thinks this is normal rate?) So to download Blockchain I'm closing and starting geth everty 10 minutes aprox

#### Steps to reproduce the behaviour
geth console

#### Backtrace

````
[backtrace]
````

**Comment by emiruz** [comment]
+1

Same issue. Hangs after a short while, downloads a few blocks in progressively longer intervals. It's been running 2 days now ... 

System: Ubuntu 14.04, 2 Core, running on Linode but also tried on EC2 and laptop
Command: geth
Installation:
apt-get install -y software-properties-common
add-apt-repository -y ppa:ethereum/ethereum-qt
add-apt-repository -y ppa:ethereum/ethereum
add-apt-repository -y ppa:ethereum/ethereum-dev
apt-get update
apt-get install -y ethereum

**Comment by karalabe** [comment]
We have a new release imminent (i.e. in a couple hours) that should drastically address sync issues.

**Comment by emiruz** [comment]
You guys know that the ubuntu ppa installs geth 1.5.0-unstable?

**Comment by karalabe** [comment]
@emiruz If you have the develop PPA (`ethereum/ethereum-dev`) enabled, yes, of course. The plain stable PPA (`ethereum/ethereum`) should not install 1.5. And given that 1.5 isn't listed at https://launchpad.net/~ethereum/+archive/ubuntu/ethereum, I'm going to go with you having develop snapshots enabled. Please double check.

PS: The sync issue should be solved by our 1.4.6 release. Closing.
