### ISSUE TITLE
The block height is always 0

### ISSUE THREAD

**Issue by DavidRomy** [ethereum/go-ethereum#26613]
hi:
Why after I use the merged geth startup node to connect to the goerli network, the block height is always 0, and the data size under the block directory chaindata also keeps unchanged. Check the log and report "Snapshot extension registration failed" error?

-------------------
geth Version: 1.10.26-stable

start command：geth --goerli --datadir ./data --ws --ws.port 8546 --ws.addr 0.0.0.0 --ws.api eth,net,web3 --http --http.addr 0.0.0.0 --http.port 8545 --http.api db,eth,net,web3,admin,personal,miner

**Comment by karalabe** [comment]
You'll need to provide some specific output logs, otherwise we have no idea what's happening.

Did you set up your beacon (consensus) node for Goerli? The network merged, so Geth alone is not enough any more to connect to it.

**Comment by DavidRomy** [comment]
> You'll need to provide some specific output logs, otherwise we have no idea what's happening.
> 
> Did you set up your beacon (consensus) node for Goerli? The network merged, so Geth alone is not enough any more to connect to it.

Yes, thank you, does geth start to synchronize blocks after the synchronization of the beacon chain is completed?

**Comment by rjl493456442** [comment]
Yes. Geth needs the signal from consensus layer to start sync.
