### ISSUE TITLE
How to automatically start Geth when Microsoft Windows starts?

### ISSUE THREAD

**Issue by AlirezaEthDev** [ethereum/go-ethereum#26626]
I need a solution to config or set up my Geth so that whenever the operating system restarted, Geth automatically run again by the same config and initial commands and automatically it be synced to the network . Is it possible? and what should I do?

Geth version: 1.10.23-d901d853
OS: Windows Server 2019

**Comment by SpiceTank1** [comment]
Hello guys , I'm a designer looking for work for my agency - get in touch if you have work for us !
@fredrikparker ( LinkedIn , Telegram ) freddy@aadu.agency

**Comment by karalabe** [comment]
That's not really a go-ethereum issue (e.g. I think non of us use Windows to easily have someone answer it). I'd guess searching a bit on Google for auto starting apps on Windows should be a good starting point.

**Comment by AlirezaEthDev** [comment]
@karalabe 
I did and I know how to automatically start Windows apps, But I don't know how to automatically run Geth with the same command that Geth was run via before Windows restarting.
