### ISSUE TITLE
input/output error

### ISSUE THREAD

**Issue by zhuga** [ethereum/go-ethereum#2662]
Node type: geth
Network: main
Platform: linux (Architecure x64)

...I0604 21:47:22.081625 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to /home/user/.ethereum/chaindata
Fatal: Could not open database: open /home/user/.ethereum/chaindata/MANIFEST-577745: input/output error

**Comment by AlbieC** [comment]
I'm a newbie to this myself, but it could be that you another instance of geth already running that you are unaware of ? I saw this same thing with me last night.

**Comment by fjl** [comment]
@zhuga did this resolve eventually?
