### ISSUE TITLE
How can recharge account balance without reconfig GoEthereum In a PoA private network?

### ISSUE THREAD

**Issue by AlirezaEthDev** [ethereum/go-ethereum#26639]
As we know, In a PoA private Ethereum network, There is a genesis file and the balance of each account is determined there and the network is live based on this config. Now, What should we do if we need to recharge some accounts' balance in such a way that there is no need to reconfig so the network continues to operate and no interruptions occur?

Geth version: 1.10.23-d901d853

OS: Windows Server 2019

**Comment by s1na** [comment]
AFAIK this is not possible without reconfiguration. You can send ether to the account you want from one of the validators that's earning eth.
