### ISSUE TITLE
debug_traceBlockByHash is not working with reexec

### ISSUE THREAD

**Issue by imnotanoob** [ethereum/go-ethereum#26636]
#### System information

Geth version: `1.10.24` (full mode with snap sync)
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0

#### Expected behaviour
When we call:
At time of writing, currently at block: `16579899`

Trying to traceBlockByHash of block `16578586`

(around 1300 blocks behind)

```
curl --request POST   --url http://127.0.0.1:8546/   --header 'content-type: application/json'   --data '{"method":"debug_traceBlockByHash","params":["0x1fd1fd6935ecc874fa99ba6a4706003f9ac4134eed6f1dd6886c4263129003f0", {"tracer": "callTracer", "reexec": 12000 }], "jsonrpc":"2.0", "id": 0}'
```

For it to take time, but return back the trace.

#### Actual behaviour
`{"jsonrpc":"2.0","id":0,"error":{"code":-32000,"message":"required historical state unavailable (reexec=12000)"}}` 

Returned required historical state is unavailable. 

As a sanity check we used getAccessibleState:

```
curl -X POST -H "Content-Type: application/json" http://localhost:8546/ --data '{"jsonrpc": "2.0", "id": 42, "method": "debug_getAccessibleState", "params": ["earliest", "latest"]}'
{"jsonrpc":"2.0","id":42,"result":16386258}
```

As you can see this block is much below the block we are trying to trace. Yet it still does not work

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by s1na** [comment]
The last state persisted by your node is that of block 16386258. `reexec` means how many blocks is geth allowed to go back from the block that will be traced to find a persisted state. In this case 12000 is not enough. You will need to provide a number higher than 192328.

**Comment by imnotanoob** [comment]
> The last state persisted by your node is that of block 16386258. `reexec` means how many blocks is geth allowed to go back from the block that will be traced to find a persisted state. In this case 12000 is not enough. You will need to provide a number higher than 192328.

How did you know to choose `192328`?

**Comment by s1na** [comment]
You want to trace block `16578586` and the last persisted state is `16386258`. That means the node will have to re-execute `16578586 - 16386258` blocks to produce the desired state.

**Comment by imnotanoob** [comment]
Thank you very much.
