### ISSUE TITLE
00 prefixed addresses leading to an error.

### ISSUE THREAD

**Issue by slawomir-pryczek** [ethereum/go-ethereum#26643]
Hi Guys, can you please check this bug report https://github.com/web3p/rlp/issues/27 and explain how geth is handling RLP encoded addresses with leading 00's removed? Trying to find source of this error when dealing with 0x00 prefixed wallets.

rlp: input string too short for common.Address, decoding into (types.DynamicFeeTx).To

Seems when im signing transaction using geth it'll leave 00's in the address. Eg. destination address is
0x00f0cb2ed033f72b4a1e14948860e197aa2ee988

Geth will keep it in the transacion. PHP/RLP will convert this address to 0xf0cb2ed033f72b4a1e14948860e197aa2ee988

Thanks

**Comment by holiman** [comment]
>  patch to remove leading 0's from strings. 

An address is not a `string`, it's a fixed-length (`20`) byte array. 

The canonical encoding of address does not allow you to trim stuff.
