### ISSUE TITLE
How can I handle error code from geth?

### ISSUE THREAD

**Issue by hyerim-gn** [ethereum/go-ethereum#26640]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

I am develop blockchain + api server. 
so I should handle ethereum node error code. (nonce invalid or insuffient fund etc..)
but, go-ethreuem error codes are not perfect defined. 
sometimes go-ethereum return errors.New("something") like this.

so I am hard to tracking error code. 
And  If I search all error code and add handling the error codes. 
but I can't test unittest situation. because it is different real node return error code to backends.NewSimulatedBackend one. 

how can I handle error code from geth ? and how can I test expected error code in my testcode ?

**Comment by karalabe** [comment]
It's not very clear what part you're using and want to handle.

If you're trying to use the JSON RPC specs, the best source is https://ethereum.github.io/execution-apis/api-documentation/ , the returns are well defined, but the various error types have no designated error codes unfortunately. There have been some efforts to spec it better, but there's not much inclination to invest the time to standardize error codes across clients, so it's a bit hard. You could try and nudge people to do it tho' :)

If you're using the Go packages directly, that's a bit of an interesting issue as the internals constantly evolve. New EIPs constantly add new functionality and new potential validation errors. It's not the easiest to keep tracking them beyond "error or no error". We try to make the messages meaningful for the user, but they might not be easy to consume for a program. There are always `errors.Is` comparisons with public error types, but you'd still need to surf the code if you want to react to all. Maybe if you're only interested in a couple specific errors (e.g. invalid nonce, insufficient balance) you could use that.'

**Comment by hyerim-gn** [comment]
Thank you for your answer. @karalabe 
I trying to handle the JSON RPC error code(e.g. invalid nonce, insufficient balance). 
I was wondering if I didn't know how or if there was no way(`no way` means I need to surf the code and add specific error handling api by api). 
Your reply helped me understand the situation a lot.
Again, thank you for your kindness :-)
