### ISSUE TITLE
Withdrawal JSON should include "recipient" not "address"

### ISSUE THREAD

**Issue by ryanschneider** [ethereum/go-ethereum#26657]
https://github.com/ethereum/go-ethereum/blob/77380b9629e4f679778ce9de037ffdaf9c925238/core/types/withdrawal.go#L34

According to the spec the correct payload is `"recipient"` not `"address"`:

https://github.com/ethereum/execution-apis/blob/main/src/schemas/withdrawal.yaml#L16

/cc @lightclient

**Comment by mcdee** [comment]
Note that the consensus specs use `address`  so this looks like a mistake in the execution API rather than here.

https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#withdrawal

**Comment by ryanschneider** [comment]
Ya looking at EIP-4895 as well the term `address` is used there too, so I agree it's probably the EL spec that needs an update, I'll open an issue there too.
