### ISSUE TITLE
Can I get transaction logs of my address?

### ISSUE THREAD

**Issue by sithu-go** [ethereum/go-ethereum#26663]
```go
	filter := ethereum.FilterQuery{
		Addresses: []common.Address{},
	}
	address := common.HexToAddress("0x46A1CE3138F8501b55A448e8f4EdA09C5393A962")
	filter.Addresses = append(filter.Addresses, address)

	logs, err := client.FilterLogs(context.Background(), filter)
	if err != nil {
		log.Fatal(err)
	}
```

but in my knowledge, "FilterLogs"  can only filter contract address.
can I use FilterLogs to get my transactions?
If not, how can I get my transaction logs?

**Comment by rjl493456442** [comment]
Geth does not maintain these indexes
- list of transactions whose caller is the specified account 
- list of transactions whose callee is the specified account 

These indexes should be/can be easily tracked by some external indexing tools.
