### ISSUE TITLE
does `eth_getTransactionReceipt` return stale receipt?

### ISSUE THREAD

**Issue by shunjizhan** [ethereum/go-ethereum#26668]
if the block that contains the receipt is no longer in the best chain, does `eth_getTransactionReceipt` return `null` or the receipt? 

Let's say the receipt is in `block1fork`
```
block0 - block1  - block2 - block3
     \
       - block1fork
```

**Comment by rjl493456442** [comment]
> does eth_getTransactionReceipt return null or the receipt?

Return `null`.

Technically, Geth will only maintain the transaction lookup for canonical chain, this will cause non-canonical chain receipts to be not accessible, even the side chain receipts is existent.

**Comment by alokeutpal** [comment]
I can't bear so much trouble and there is no solution to the problem. Totally ignorant about this. I don't know if I can recover them at all

**Comment by alokeutpal** [comment]
I can't bear so much trouble and there is no solution to the problem. Totally ignorant about this. I don't know if I can recover them at all

**Comment by shunjizhan** [comment]
gotcha thanks for your clarification!
