### ISSUE TITLE
Feature: Restrict the methods to be run via JSON RPC

### ISSUE THREAD

**Issue by hermanjunge** [ethereum/go-ethereum#2667]
For example, I want to run my `geth` with some sort of `config-file.yaml`

```
allowedMethods
  - eth_GetBalance
```

My options for having this feature (so far, as I just read the code for 1 hour), in order from most to less hacky:
- Fork `geth` everytime it has a new release, and mess up with the service registration.
- Put some node.js / golang proxy, read the request body and perform the restriction.
- Ask you guys if you would be interested in this feature and auto-assign it.

Please people, do point me to the right way to discuss this feature. I consider it not trivial (nor frivolous), as it impacts my job as sysadmin of geth nodes.

CC: @kumavis @flyswatter @Firescar96

**Comment by karalabe** [comment]
Just dumping a design of something we started working at at a certain point but never actually got around to fully finish. Possible long term we'd like to take the APIs in this direction: https://gist.github.com/karalabe/cdbb0fc93ef75e8afc8f (discussion starter only).

**Comment by hermanjunge** [comment]
Good. Please @karalabe Let me know how I can help on this one. I want to join the dev team. Focus on sysadmin related issues.
