### ISSUE TITLE
Cannot compile latest master 03585ed, fails with "undefined: atomic.Pointer" (golang1.19 required now?)

### ISSUE THREAD

**Issue by J-A-M-E-5** [ethereum/go-ethereum#26679]
Looks like Atomic Pointer are new feature in golang1.19, which means current Ubuntu unsupported out of the box. So need to fix README which currently states "Building geth requires both a Go (version 1.18 or later)".

#### System information

OS & Version: Linux
Commit hash : 03585ed7a932a6002569c382ab1d3b8d62819b07

#### Expected behaviour
Compiles. Was working a few days ago. make clean doesn't fix. 

#### Actual behaviour
```
$ make geth
env GO111MODULE=on go run build/ci.go install ./cmd/geth
>>> /usr/lib/go-1.18/bin/go build -ldflags "-X github.com/ethereum/go-ethereum/internal/version.gitCommit=03585ed7a932a6002569c382ab1d3b8d62819b07 -X github.com/ethereum/go-ethereum/internal/version.gitDate=20230213 -extldflags '-Wl,-z,stack-size=0x800000'" -tags urfave_cli_no_docs -trimpath -v -o /home/jm/src/geth/build/bin/geth ./cmd/geth
github.com/ethereum/go-ethereum/eth/filters
# github.com/ethereum/go-ethereum/eth/filters
eth/filters/filter_system.go:98:14: undefined: atomic.Pointer
util.go:48: exit status 2
exit status 1
make: *** [Makefile:12: geth] Error 1

$ go version
go version go1.18.1 linux/amd64

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

$ uname -a
Linux server3 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Francesreid** [comment]
I don't really understand what the whole problem is , what have I done Wrong?  Mrs F S Reid

**Comment by Francesreid** [comment]
HI What is the problem with the crypto, there was a report made on it , I
smdont know what's going on FSReid

**Comment by Francesreid** [comment]
Thanks for that anyway Mrs F S Reid

**Comment by s1na** [comment]
I mistakenly introduced a Go v1.19 feature into the codebase thinking it was already introduced before. Please either upgrade your golang to v1.19 or use this branch as a quickfix, which reverts the commit in question. https://github.com/ethereum/go-ethereum/pull/26686

**Comment by Francesreid** [comment]
Okay thanks
