### ISSUE TITLE
console color broken

### ISSUE THREAD

**Issue by xakepp35** [ethereum/go-ethereum#2668]
#### System information

Geth version: `Geth/v1.4.6-stable/windows/go1.6.2`
OS & Version: Windows

#### Expected behaviour
console has colored output before version update

#### Actual behaviour
now it prints escape characters and has only gray color, like
←[91m(anonymous): Line 2:1 Unexpected end of input←[0m

#### Steps to reproduce the behaviour
unpack geth-1.4.6, launch, type "admin." press return
compare console output visually to that of geth-1.4.5

**Comment by karalabe** [comment]
Thanks for reporting this, really appreciate it. I've managed to reproduce the error, will fix this asap.

**Comment by 5chdn** [comment]
Is this related? http://ethereum.stackexchange.com/questions/6253/87

**Comment by xakepp35** [comment]
issue is fixed in geth 1.4.7
