### ISSUE TITLE
A node sync issue on BSC, could Ethereum has the same issue?

### ISSUE THREAD

**Issue by setunapo** [ethereum/go-ethereum#26695]
There is a bug in the downloader module: a malicious peer could claim a wrong future TD value.
Then the connected nodes would always try to sync with it, since `peerWithHighestTD()` would return the malicious peer.
And of course the sync attempt will fail to get the future block, and download procedure will be stuck.

For more detail, you may refer: https://forum.bnbchain.org/t/about-recent-feb-2023-node-sync-issue-sidechain-written-to-disk/759

**Comment by rjl493456442** [comment]
We don't have the capacity to deal with issues in *other projects*. 

There is no `TotalDifficulty` notion in ethereum anymore. It will never happen to ethereum.
