### ISSUE TITLE
Importing of presale keys

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#267]
A user of Mist / Go client should be able to import a presale key given the key file and password. Importing a key stores it in the configured key store.

**Comment by Gustav-Simonsson** [comment]
This adds 
```go
func ImportPreSaleKey(keyStore KeyStore2, keyJSON []byte, password string) (*Key, error)
```
https://github.com/ethereum/go-ethereum/pull/268

**Comment by obscuren** [comment]
Implemented
