### ISSUE TITLE
Fatal: no network preset provided.  no exisiting genesis in the default datadir

### ISSUE THREAD

**Issue by tardigralice** [ethereum/go-ethereum#26728]
#### System information

Geth version: 1.11.1
CL client & version: prysm
OS & Version: Liunx ubuntu 20.04
Commit hash : (if `develop`)

#### Expected behaviour
/home/eth/geth dumpgenesis > genesis.json
dumping genesis.json without error , like i always did until 1.11.0 without any issue

#### Actual behaviour

/home/eth/geth dumpgenesis > genesis.json
INFO [02-19|20:13:51.020] Maximum peer count                       ETH=50 LES=0 total=50
INFO [02-19|20:13:51.021] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [02-19|20:13:51.025] Set global gas cap                       cap=50,000,000
INFO [02-19|20:13:51.027] Using leveldb as the backing database
INFO [02-19|20:13:51.027] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=16.00MiB handles=16 readonly=true
INFO [02-19|20:13:51.027] Using leveldb as the backing database
INFO [02-19|20:13:51.027] Allocated cache and file handles         database=/root/.ethereum/geth/lightchaindata cache=16.00MiB handles=16 readonly=true
Fatal: no network preset provided.  no exisiting genesis in the default datadir

#### Steps to reproduce the behaviour
download geth 1.11.1 on /home/eth/
then 
/home/eth/geth dumpgenesis > genesis.json

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
This should be fixed on master and will land in 1.11.2.
