### ISSUE TITLE
NewPendingTransactionFilter has breaking changes since v1.11.0

### ISSUE THREAD

**Issue by zzh1996** [ethereum/go-ethereum#26725]
#### System information

Geth version: `v1.11.0` `v1.11.1`

#### Expected behaviour

After calling `eth_newPendingTransactionFilter`, `eth_getFilterChanges` should return tx hashes.

#### Actual behaviour

After calling `eth_newPendingTransactionFilter`, `eth_getFilterChanges` returns `types.Transaction`, which is not backward compatible. This breaks a lot of existing applications.

The proper implementation may be adding a new RPC method or adding a new param to the existing RPC method (just like `newPendingTransactions` in `eth_subscribe`). Also, `RPCTransaction` is better than `types.Transaction` since the former has sender address.

#### Steps to reproduce the behaviour

First call `eth_newPendingTransactionFilter` and then call `eth_getFilterChanges`.

**Comment by karalabe** [comment]
This has been fixed on master, sorry for the breakage. Will be released as 1.11.2 later today.
