### ISSUE TITLE
ethapi: add txpool_contentTo RPC method

### ISSUE THREAD

**Issue by yopoing** [ethereum/go-ethereum#26737]
I am very glad that the txpool_contentFrom method has been supported so far, which can filter the transactions in the memory pool according to the from address, but it will be more useful to add the txpool_contentTo RPC method. In many cases, it is necessary to filter the transactions in the memory pool according to the to address. I really hope to add this interface, thanks!

**Comment by karalabe** [comment]
I don't think that's really useful. Transactions can have arbitrary nestings and I'd assume you'd be interested in all txs that touch a contract, not only those that directly call into a contract on the topmost call. We can't give you all the nested calls without executing the code, and even then it would depend on the order, so it wouldn't really be meaningful either.
