### ISSUE TITLE
Unable to update to 1.11.1 Focal via PPA

### ISSUE THREAD

**Issue by cam-schultz** [ethereum/go-ethereum#26735]
#### System information

Geth version: `1.11.1`
OS & Version: Ubuntu 20.04 Focal

#### Expected behaviour
```
apt update
apt install ethereum=1.11.1+build28333+focal
```
#### Actual behaviour
```
apt-cache policy ethereum
```
shows
```
ethereum:
  Installed: (none)
  Candidate: 1.11.0+build28324+focal
  Version table:
     1.11.0+build28324+focal 500
        500 http://ppa.launchpad.net/ethereum/ethereum/ubuntu focal/main amd64 Packages
```

The [launchpad repository](https://launchpad.net/~ethereum/+archive/ubuntu/ethereum) lists the 1.11.1 package as available for focal, but going to the [sources list](http://ppa.launchpad.net/ethereum/ethereum/ubuntu/pool/main/e/ethereum/) reveals the required `deb64` package for my system is not present.

**Comment by holiman** [comment]
We've been having some problems with ppa uploads, but it should be fine now. Please check again, and/or clarify what file it is that seems to be missing. Isn't this the one you're searching for ? 
![Screenshot 2023-02-20 at 15-23-41 Index of _ethereum_ethereum_ubuntu_pool_main_e_ethereum](https://user-images.githubusercontent.com/142290/220132973-b15cd57a-e0c3-4834-97e3-35ea02167b4d.png)

**Comment by cam-schultz** [comment]
Sorry, I could have been more clear. The files I'm expecting to see would be `ethereum_1.11.1+build28333+focal.deb`. I only see the `*.dsc` and `*.tar.xz` files for that package.

**Comment by karalabe** [comment]
@holiman We fixed the unstable builds, but we need to push a stable version to have the fix propagate to stables. Perhaps we can do it tomorrow.

**Comment by karalabe** [comment]
Launchpad was fixed, will push a new stable version today.
