### ISSUE TITLE
How to shorten the retention time of transactions in the mempool？

### ISSUE THREAD

**Issue by yopoing** [ethereum/go-ethereum#26738]
Transactions in the mempool are stored for a long time, and some transactions even exceed two weeks. Is there any configuration parameter that can shorten the storage time of unconfirmed transactions in the transaction pool?

**Comment by karalabe** [comment]
The txpool is not configurable in it's current incarnation. Eventually if we ever rewrite to a disk backed one we might have some more flags. For now it keeps the best ones, even if they don't ever get mined due to even better ones in front.
