### ISSUE TITLE
Bad block #765093 and invalid receipt root hash

### ISSUE THREAD

**Issue by nerdatwork** [ethereum/go-ethereum#2674]
22:21:05.609485 core/blockchain.go:1128] Bad block #765093 (0x822fc789edd3
c76328b5a7866b1972625dbbab22b73a97328921c0ec84dae367)
E0608
22:21:05.609485 core/blockchain.go:1129] invalid receipt root hash.received=628ec6857748ad819977b4b67fc22f363abb49ac57f6ea873df8b4dbdacac2f6
calculated=c41d8d53b62090c3cee5ea70c581241e95dbe5e4c7a2b1d46611ded27edc7559
I0608 
22:21:05.609485 eth/downloader/downloader.go:299] Synchronisation failed:
invalid receipt root hash. received=628ec6857748ad819977b4b67fc22f363abb49ac57f6
ea873df8b4dbdacac2f6 calculated=c41d8d53b62090c3cee5ea70c581241e95dbe5e4c7a2b1d4
6611ded27edc7559

I am stuck at this and I do not understand what to do. I am extremely new to this so please help.

Geth
Version: 1.4.6-stable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: windows
GOPATH=
GOROOT=c:\go

**Comment by Kojee** [comment]
Does it always give you this error while syncing or not? Tried restarting geth?

**Comment by nerdatwork** [comment]
Yes have restarted geth more than 5 times and every time I get this error.

**Comment by obscuren** [comment]
Has your system previously crashed?

**Comment by nerdatwork** [comment]
Yes it did

**Comment by Kojee** [comment]
Have you tried making a clean sync, deleting the whole blockchain?

**Comment by nerdatwork** [comment]
After 4th attempt I was able to start mining. I did a clean sync, deleted all of the folders and started it again. I thought I would get some pointers in avoiding that since it took 3 hours to fast sync. I am trying to CPU mine with my i7 but I dont seem to be getting anywhere at the moment. Ran the setup for 2 hours and checked balance using java console. Its the big ole ZERO. 
Any tips are much appreciated and I will then close this thread :)

**Comment by Kojee** [comment]
Mining solo with a CPU,  even if a powerful one, won't give you any gains. 
You should try joining a pool,  but I don't know if cpu mining can be applied to pools in the same way as  gpu mining does.

**Comment by Kojee** [comment]
Try dwarf pool, but there are many others. A quick search on Google will surely give you plenty of options

**Comment by nerdatwork** [comment]
Thank you @Kojee @obscuren

**Comment by karalabe** [comment]
@nerdatwork My i7 can crunch out about 11MH, the network is around 3.7TH, so with an i7, you have 1/336363 chance to find a block. Or inversely 1 block every 58.39 days (statistically).

**Comment by nerdatwork** [comment]
@karalabe Wow that is very insightful. Forgive my novice curiosity but could you elaborate the setup. Is it having i7 mine 24/hrs a day. How long should I CPU mine so as not to overheat my processor ? Thank you in advance :+1:
