### ISSUE TITLE
Tests failing on 1.11.2

### ISSUE THREAD

**Issue by ABastionOfSanity** [ethereum/go-ethereum#26759]
#### System information

[***]$ uname -a
Linux fedora 6.1.10-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Feb  6 23:56:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[***]$ go version
go version go1.19.2 linux/amd64

commit 73b01f40ceb6bcb6f9f44c2a3d6f963b40452b47 (HEAD -> v1.11.2_fresh, origin/v1.11.2_fresh, origin/geth_main/v1.11.2, geth_main/v1.11.2)
Author: Péter Szilágyi <peterke@gmail.com>
Date:   Wed Feb 22 14:23:51 2023 +0200

    params: release Geth v1.11.2

> params/version.go

#### Expected behaviour
Tests pass locally as they do in CI.

#### Actual behaviour
Tests fail locally.  Previous releases have not had issue.

> --- FAIL: TestSequentialRead (0.00s)
>     freezer_table_test.go:899: AppendRaw(0, ...) returned error: the append operation is out-order: have 0 want 30
> --- FAIL: TestSequentialReadByteLimit (0.00s)
>     freezer_table_test.go:960: AppendRaw(0, ...) returned error: the append operation is out-order: have 0 want 30
> --- FAIL: TestFreezerReadonly (0.00s)
>     freezer_table_test.go:1032: AppendRaw(0, ...) returned error: the append operation is out-order: have 0 want 8
> --- FAIL: TestRandom (0.00s)
>     freezer_table_test.go:1287: random test iteration 1 failed: ([]interface {}) (len=1 cap=1) {
>          (rawdb.randTest) (len=50 cap=67) {
>           (rawdb.randTestStep) {
>            op: (int) 2,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 7,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (*errors.errorString)(0xc0002989f0)(mismatch on retrieved values [[0 0 0 0 0 0 0 9] [0 0 0 0 0 0 0 10] [0 0 0 0 0 0 0 11]] [])
>           },
>           (rawdb.randTestStep) {
>            op: (int) 1,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 6,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 1,
>            items: ([]uint64) (len=2 cap=2) {
>             (uint64) 0,
>             (uint64) 1
>            },
>            blobs: ([][]uint8) (len=2 cap=2) {
>             ([]uint8) (len=8 cap=8) {
>              00000000  00 00 00 00 00 00 00 00                           |........|
>             },
>             ([]uint8) (len=8 cap=8) {
>              00000000  00 00 00 00 00 00 00 01                           |........|
>             }
>            },
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 5,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 4,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 0,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 3,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 4,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 2,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 5,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 1,
>            items: ([]uint64) (len=2 cap=2) {
>             (uint64) 0,
>             (uint64) 1
>            },
>            blobs: ([][]uint8) (len=2 cap=2) {
>             ([]uint8) (len=8 cap=8) {
>              00000000  00 00 00 00 00 00 00 00                           |........|
>             },
>             ([]uint8) (len=8 cap=8) {
>              00000000  00 00 00 00 00 00 00 01                           |........|
>             }
>            },
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 4,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 6,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 3,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 4,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 3,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 3,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 1,
>            items: ([]uint64) (len=1 cap=1) {
>             (uint64) 0
>            },
>            blobs: ([][]uint8) (len=1 cap=1) {
>             ([]uint8) (len=8 cap=8) {
>              00000000  00 00 00 00 00 00 00 00                           |........|
>             }
>            },
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 2,
>            items: ([]uint64) (len=1 cap=1) {
>             (uint64) 0
>            },
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 5,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 1,
>            items: ([]uint64) (len=2 cap=2) {
>             (uint64) 1,
>             (uint64) 2
>            },
>            blobs: ([][]uint8) (len=2 cap=2) {
>             ([]uint8) (len=8 cap=8) {
>              00000000  00 00 00 00 00 00 00 01                           |........|
>             },
>             ([]uint8) (len=8 cap=8) {
>              00000000  00 00 00 00 00 00 00 02                           |........|
>             }
>            },
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 4,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 0,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 6,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 6,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 5,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 5,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 1,
>            items: ([]uint64) (len=2 cap=2) {
>             (uint64) 0,
>             (uint64) 1
>            },
>            blobs: ([][]uint8) (len=2 cap=2) {
>             ([]uint8) (len=8 cap=8) {
>              00000000  00 00 00 00 00 00 00 00                           |........|
>             },
>             ([]uint8) (len=8 cap=8) {
>              00000000  00 00 00 00 00 00 00 01                           |........|
>             }
>            },
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 5,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 4,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 6,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 3,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 1,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 0,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 5,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 7,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 4,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 7,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 3,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 2,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 7,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 0,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 1,
>            items: ([]uint64) (len=2 cap=2) {
>             (uint64) 0,
>             (uint64) 1
>            },
>            blobs: ([][]uint8) (len=2 cap=2) {
>             ([]uint8) (len=8 cap=8) {
>              00000000  00 00 00 00 00 00 00 00                           |........|
>             },
>             ([]uint8) (len=8 cap=8) {
>              00000000  00 00 00 00 00 00 00 01                           |........|
>             }
>            },
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 1,
>            items: ([]uint64) (len=1 cap=1) {
>             (uint64) 2
>            },
>            blobs: ([][]uint8) (len=1 cap=1) {
>             ([]uint8) (len=8 cap=8) {
>              00000000  00 00 00 00 00 00 00 02                           |........|
>             }
>            },
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 1,
>            items: ([]uint64) (len=1 cap=1) {
>             (uint64) 3
>            },
>            blobs: ([][]uint8) (len=1 cap=1) {
>             ([]uint8) (len=8 cap=8) {
>              00000000  00 00 00 00 00 00 00 03                           |........|
>             }
>            },
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 4,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 5,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           },
>           (rawdb.randTestStep) {
>            op: (int) 0,
>            items: ([]uint64) <nil>,
>            blobs: ([][]uint8) <nil>,
>            target: (uint64) 0,
>            err: (error) <nil>
>           }
>          }
>         }
> 
> Version 1 count 7, deleted 0, hidden 0
> | number | fileno | offset |
> |--------|--------|--------|
> |  000   |  000   |  020   | 
> |  001   |  000   |  040   | 
> |  002   |  001   |  020   | 
> |  003   |  001   |  040   | 
> |  004   |  002   |  020   | 
> |  005   |  002   |  040   | 
> |  006   |  003   |  020   | 
> |--------------------------|
> 
> 
> Version 1 count 7, deleted 0, hidden 1
> | number | fileno | offset |
> |--------|--------|--------|
> |  000   |  000   |  020   | 
> |  001   |  000   |  040   | 
> |  002   |  001   |  020   | 
> |  003   |  001   |  040   | 
> |  004   |  002   |  020   | 
> |  005   |  002   |  040   | 
> |  006   |  003   |  020   | 
> |--------------------------|
> 
> FAIL
> FAIL	github.com/ethereum/go-ethereum/core/rawdb	0.248s
> 

#### Steps to reproduce the behaviour

Clean checkout of above SHA on dev system described above:
[michael@fedora go-ethereum]$ go run build/ci.go test

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
```
$ go test ./core/rawdb/...
ok  	github.com/ethereum/go-ethereum/core/rawdb	5.270s
```

Works for us? Please check your Go installation, something seems to be off at your end IMO.

**Comment by karalabe** [comment]
Downgraded to your version of Go just to sanity check, still everything works:

```

```
$ go version
go version go1.19.2 linux/amd64
```
$ go test ./core/rawdb/...
ok  	github.com/ethereum/go-ethereum/core/rawdb	7.163s
```
