### ISSUE TITLE
Feature: Redis as database engine (instead/along of LevelDB)

### ISSUE THREAD

**Issue by begrossi** [ethereum/go-ethereum#26754]
# Rationale

Using a disk-based database engine like leveldb or peeble is not practical when using it on k8s pods, that normally do not have writable and durable filesystems. Using a remote key/value database like Redis is most effective in this use-case.
Old [issue for Redis](https://github.com/ethereum/go-ethereum/issues/2690) has already been opened before and closed without any solution.

# Implementation

I already implemented the solution, and it should be revised (PR soon), using `db.engine` flag (created for `peeble` usage) to select Redis as the engine. The code is createtd on `rawdb` package, using `ethdb.KeyValueStore` interface.

**Comment by StEvUgnIn** [comment]
Why adding Redis instead of Riak? https://pkg.go.dev/github.com/basho/riak-go-client

**Comment by holiman** [comment]
The PR is interesting, but I don't see any need to have a ticket open as well. Let's keep the discussion on the PR
