### ISSUE TITLE
Package compilation for s390x architecture

### ISSUE THREAD

**Issue by meta-lite** [ethereum/go-ethereum#26760]
I am currently working on a project utilizing an IBM Mainframe for blockchain education at a public university. We want to teach Geth on this computer, but I can't seem to find a package compiled for s390 architecture. Can devs offer any info or support?

**Comment by karalabe** [comment]
Why don't you just built it yourself? I don't think we'll provide pre-built binaries just for the occasional user every 5 years.

**Comment by karalabe** [comment]
If Geth does not compile on the architecture we can definitely investigate, but that's as far as we'll go really.

**Comment by meta-lite** [comment]
I have made some unsuccessful attempts at this, but I will give it another pass and update with any notable errors

**Comment by meta-lite** [comment]
After installing Makefile via apt and cloning the geth repo, I am met with this error

<img width="845" alt="Screenshot 2023-03-01 at 4 09 18 PM" src="https://user-images.githubusercontent.com/104095033/222276552-af46595f-19ca-441b-bdb1-a2a3acba0680.png">

**Comment by karalabe** [comment]
Please install a newer version of Go. You system seems to have Go 1.10,
which is 5 years old. Please install Go 1.20.
