### ISSUE TITLE
how to modify the consensus engine code to achieve the desired changes in the unauthorized signer logic.

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#26761]
Hi!

Can anyone guide me on how can modify the Clique Consensus engine code to change the unauthorized signer logic for allowing every node to become a singer/ validator and what changes will require for it?

Thanks!

**Comment by karalabe** [comment]
Sorry, designing a consensus algorithm takes a lot of time. Clique balances a lot of possible attacks to be somewhat safe ans useful. We can't help in designing a new consensus algo. Allowing anyone to sign needs some form of spam protection that you'd need to figure out yourself.

**Comment by AsadullahSoomro** [comment]
Hi @karalabe 
Is it possible to modify the existing code of Clique's fixed length of signers without using propose API and without assigning extra data in JSON file.

**Comment by holiman** [comment]
You can do anything by modifying the code. However, we're not keen on spending time helping you with such non-ethereum-related changes, so you are pretty much on your own. 
We simply don't have the time/resources to help out with that, we're focused on Ethereum.

**Comment by AsadullahSoomro** [comment]
Okay, thanks for your reply.
