### ISSUE TITLE
How to fix the genesis.json configuration issue?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ethereum/go-ethereum#26767]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

Hi,
I want to set up a private chain with geth. The following is my genesis.json file:
{
    "config": {
        "chainId": 15,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "difficulty": "0x400",
    "gasLimit": "0x2100000",
    "alloc": {
        "0x6BD0dE2A9569e4DE77087bCF1dA39D24929552cF": 
         { "balance": "0x1337000000000000000000" }     
    }
}

But when I run the following command, I got error messages:
D:\GETH>geth -datadir D:\GETH init D:\GETH\genesis.json
INFO [02-25|23:49:44.203] Maximum peer count                       ETH=50 LES=0 total=50
INFO [02-25|23:49:44.215] Set global gas cap                       cap=50,000,000
INFO [02-25|23:49:44.215] Using leveldb as the backing database
INFO [02-25|23:49:44.215] Allocated cache and file handles         database=D:\GETH\geth\chaindata cache=16.00MiB handles=16
INFO [02-25|23:49:44.335] Using LevelDB as the backing database
INFO [02-25|23:49:44.618] Opened ancient database                  database=D:\GETH\geth\chaindata\ancient/chain readonly=false
INFO [02-25|23:49:44.623] Writing custom genesis block
Fatal: Failed to write genesis block: unsupported fork ordering: eip150Block not enabled, but eip155Block enabled at block 0

How can I fix this issue?
Thanks!

**Comment by hadv** [comment]
@zydjohnHotmail As error log also metioned, your genesis json config file is missing `    "eip150Block": 0,`
It should be like below I think

```
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
```

**Comment by zydjohnHotmail** [comment]
Hi,
Thank you for your help.  I changed my gensis.json file according to your advice, and it works,
Thank you very much!
