### ISSUE TITLE
Puppeth has delete ?

### ISSUE THREAD

**Issue by ekawibisono** [ethereum/go-ethereum#26798]
Hello, I want to ask. Puppeth has been removed from Geth? after I did the go-ethereum build, I saw that there was no puppet in the bin, right? Is this a new update?
![image](https://user-images.githubusercontent.com/22586872/222633915-cc1530a2-2231-49ba-ab21-c8fcb79d0481.png)

**Comment by ekawibisono** [comment]
Sorry in advance, after I read it turns out that puppeth has been removed since January 2023.
![image](https://user-images.githubusercontent.com/22586872/222634188-189d8a07-a64b-43fe-bb90-d099dde0b94d.png)

https://geth.ethereum.org/docs/tools/puppeth

**Comment by pintileialex** [comment]
and meanwhile how with operate now? what help ?!
