### ISSUE TITLE
in `worker.commitTransaction` should also revert the gas pool when err is not nil and the TX is not added to the state

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#26791]
https://github.com/ethereum/go-ethereum/blob/master/miner/worker.go#L863-L875

for example in this code the when `core.ApplyTransaction` returns an error the pool will be reduced where in fact the tx is not added to the state.

**Comment by rjl493456442** [comment]
Thanks for catching it. I think it's a valid issue. 
The gas allowance will be wasted by invalid transactions which will result in less transactions be included.
