### ISSUE TITLE
Can you help me how to change the symbol from ETH to XCR. 

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#26807]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

**Comment by AsadullahSoomro** [comment]
how to change the symbol from ETH to XCR

**Comment by MariusVanDerWijden** [comment]
No, please don't spam this repository
