### ISSUE TITLE
`eth_getLogs` logic to filter events in failed tx

### ISSUE THREAD

**Issue by graykode** [ethereum/go-ethereum#26818]
I'm looking for code in this repo which implements the `eth_getLogs` logic to filter events in failed transactions.
Could you provide an explanation of how it works in the code?

**Comment by rjl493456442** [comment]
Failed transaction has no events/logs saved in blockchain.

**Comment by s1na** [comment]
Normally you shouldn't need logs for failed transactions. However if it is a failed tx that is mined in a block, you can use `debug.traceTransaction(<hash>, { tracer: "callTracer", tracerConfig: { withLogs: true } })` in the console (or similar with RPC) which will return the logs emitted during tx in addition to all the calls and their results.
