### ISSUE TITLE
EthClient.BlockByHash stopped working on 1.11.2

### ISSUE THREAD

**Issue by tclemos** [ethereum/go-ethereum#26816]
#### System information

Geth version: `1.11.2`

#### Expected behaviour
return `ethereum.NotFound` error

#### Actual behaviour
panic with nil reference

#### Steps to reproduce the behaviour
call `ethclient.BlockByHash` with a block hash that `doesn't exist` in the blockchain

This is the PR that introduced the error: https://github.com/ethereum/go-ethereum/pull/26723

I've added a comment to the PR explaining the problem.

**Comment by fjl** [comment]
Fixed in https://github.com/ethereum/go-ethereum/pull/26817
