### ISSUE TITLE
What is the technical details about concurrently calls to a smart contract to set a variable's state?

### ISSUE THREAD

**Issue by chenweiyj** [ethereum/go-ethereum#26821]
I have got a question about concurrently calls to a smart contract. If there are two users call a smart contract to set the same variable's state simultaneously, how does miners process them and what is the final consistency of the smart contract?

**Comment by karalabe** [comment]
There's no concurrency. Transactions are ordered in a block and are executed sequentially one after the other.

**Comment by chenweiyj** [comment]
@karalabe Yes, there's no concurrency, but transactions are ordered. But if `userA` set `variable1 = 1`, and `userB` set `variable1 = 2`, when two miners arrange these two transactions not in the same order, the final state of `variable1` might be different. That is `minerA` arranges `transactionA` before `transactionB`, and `variable1` will eventually be 2, whereas `minerB` arranges `transactionB` before `transactionA`, and `variable1` will eventually be 1. The final state of `variable1` will be inconsistent.
