### ISSUE TITLE
Possible memory leak scenario in priceHeap

### ISSUE THREAD

**Issue by nothingmin** [ethereum/go-ethereum#26826]
#### System information

Geth version: `1.10`

#### Expected behaviour
Transactions in urgent priceHeap is removed

#### Actual behaviour
Transactions in urgent priceHeap is not removed

Heap
```
ALL                            20535535  1790.480 MB
big.Int                        12794665   761.690 MB
types.Transaction               2558461   447.726 MB  // It is not cache since I set BodyCacheLimit and BlockCacheLimit to 1 
types.LegacyTx                  2558461   214.715 MB
memdb.DB                              2   147.751 MB
common.Address                  2558461    48.799 MB
table.block                          70    35.193 MB
types.Receipt                     53398    22.407 MB
v2.Filter                           230    22.326 MB
core.txPricedList                     1    19.695 MB
```

txpool
```
{
  pending: 4371,
  queued: 537
}
````
you can see we have large too large txPricedList even we don't have that much transactions in txpool.

#### Steps to reproduce the behaviour
1. LondonHardFork is not applied
2. Set large GlobalSlots, GlobalQueue in TxPoolConfig that mempool is not full

#### reason
These are the ways the transactions in urgent priceHeap that are not in txpool is removed.
1. `Reheap()`
2. `Discard(slots int, force bool)`
4. `Underpriced(tx *types.Transaction)`
In case of function `Discard `and `Underpriced`, It's not executed if tx pool is not full.
And `Reheap ` is not executed when LondonHardFork is applied because `SetBaseFee` is not executed.
Therefore urgent in txPriceList is never get flushed

**Comment by holiman** [comment]
>  And Reheap is not executed when LondonHardFork is applied because SetBaseFee is not executed.

That's not quite true, we also call it from `Removed`. And `Removed` tracks the amount of stales, so even if the pool never becomes full, if there's a lot of transaction-churn, the stale-counter will still work
```

// Removed notifies the prices transaction list that an old transaction dropped
// from the pool. The list will just keep a counter of stale objects and update
// the heap if a large enough ratio of transactions go stale.
func (l *pricedList) Removed(count int) {
	// Bump the stale counter, but exit if still too low (< 25%)
	stales := atomic.AddInt64(&l.stales, int64(count))
	if int(stales) <= (len(l.urgent.list)+len(l.floating.list))/4 {
		return
	}
	// Seems we've reached a critical number of stale transactions, reheap
	l.Reheap()
}
```

**Comment by MariusVanDerWijden** [comment]
Hmm since this only happens when London is not activated, I don't think we need to fix it atm. After London the priceHeap is reheaped after every block, so the memory is not leaked for long
