### ISSUE TITLE
How to use the ws endpoint on 8551?

### ISSUE THREAD

**Issue by TennisBowling** [ethereum/go-ethereum#26836]
Geth seems to open a ws endpoint on the same port as the auth http server, 8551.
```
HTTP server started                      endpoint=[::]:8545 auth=false prefix= cors=* vhosts=*
WebSocket enabled                        url=ws://[::]:8546
WebSocket enabled                        url=ws://[::]:8551
HTTP server started                      endpoint=[::]:8551 auth=true  prefix= cors=localhost vhosts=0.0.0.0
```
but there seems to be no doc on how to provide authentication to it. I can't seem to use it as i would the 8556 either.

**Comment by sbtobb** [comment]
I think it is connected to the consensus node
[doc](https://geth.ethereum.org/docs/getting-started/consensus-clients#consensus-clients)

**Comment by MariusVanDerWijden** [comment]
Yep, as @sbtobb linked. The authenticated port provides the engine API to the consensus layer client. It should not be used for other RPC. You can specify the secret for it via `--jwt.secret`. This secret needs to be shared between EL and CL

**Comment by TennisBowling** [comment]
Yes, I know. I'm trying to lower CL:EL latency by using websockets, I'm just interested in how to provide the token when connecting to the websocket.

**Comment by lightclient** [comment]
@TennisBowling see the authentication spec for the engine api. You need to submit a ws upgrade request with the JWT.

**Comment by NCKDCOK** [comment]
How do I close a port when I start a node and I can't start a second port because this 8551 port is occupied
