### ISSUE TITLE
Swarm doesn't respond on POST to /bzz-raw: #17457

### ISSUE THREAD

**Issue by alice22foster** [ethereum/go-ethereum#26837]
**####****** System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by rjl493456442** [comment]
Sorry swarm team has moved to another organization https://github.com/ethersphere It's not relevant with go-ethereum anymore. Please open ticket there!

**Comment by vinioleg2015zem** [comment]
> **####****** System information
> 
> Geth version: `geth version`
> CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
> OS & Version: Windows/Linux/OSX
> Commit hash : (if `develop`)
> 
> #### Expected behaviour
> 
> 
> #### Actual behaviour
> 
> 
> #### Steps to reproduce the behaviour
> 
> 
> #### Backtrace
> 
> ````
> [backtrace]
> ````
> 
> When submitting logs: please submit them as text and not screenshots.
>
