### ISSUE TITLE
clef: Programatically create new accounts and store their password in the Clef vault

### ISSUE THREAD

**Issue by roosemberth** [ethereum/go-ethereum#26832]
I'm not sure whether this may be a bug or a feature request; I'm looking to move away from `personal_*` methods in geth's RPC to using clef. My use-case is as follows:

- I create a new eth account using `personal_newAccount`. A different password is generated for each account.
- Funds are sent to the address of the generated account.
- At some moment, I decide this account will no-longer receive funds.
- I send all of the account funds to some fixed address.

This procedure is completely non-interactive.

I'm now migrating to clef. After reading the clef documentation, I understand the following needs to happen:

- Use the `account_new` RPC method to generate new eth accounts.
- Create a rule file, enroll it using `clef attest ...`, which approves calls to `account_new` and `account_signTransaction` adequately.
- For every new account, call `clef setpw ${account address}` to store the account password in the Clef vault.

What is unclear to me is the following:

- How do I programatically provide the account password?

  From what I gather, I need to write a wrapper application that launches clef with `--stdio-ui`, and provides a password upon `ui_onInputRequired` when the message contains `Please enter a password for the new account to be created`. This seems rather brittle and from what I understand unsupported.

- How do I avoid race-conditions between storing the password and an RPC requiring access to the account password? This is currently unlikely since funds are typically collected a couple minutes after the account is created, but I can imagine this procedure envolving to require signing some data using the new account before funds are received.

An alternative would be for me not needing to generate and provide a password for as long as the credentials were automatically added to the Clef vault. I did not see this in the documentation, so I assume this is not possible. Moreover, it's unclear whether a filesystem snapshot is sufficient to backup the Clef vault.

Bonus question:

- How do I remove no-longer used accounts? After collecting all funds in the account there's no reason to keep the account around. There seems to be no methods to remove ~~credentials from the Clef vault nor~~ accounts from Clef itself. (Edit: `clef delpw` removes credentials from the Clef vault).

**Comment by holiman** [comment]
You should probably not use the `clef` binary for this usecase, but rather perhaps use the underlying packages as libraries for your own tool.

**Comment by karalabe** [comment]
Your use case seems to be very specific and relatively small in scope. Is there a specific reason you would want to use a full blown "wallet" (clef) for this vs. using go-ethereum as a library and just manage the keys yourself?

**Comment by roosemberth** [comment]
Thanks for your reply.

> Is there a specific reason you would want to use a full blown "wallet" (clef) [vs] manage the keys yourself?

Reduce development time, given that clef was the suggested migration path. Developing software responsible for handling keys takes significantly more time.

That said, we've since developed a custom alternative. Feel free to close the issue if you decide this is not a feature set you'd like to support.

**Comment by holiman** [comment]
Thanks for getting back to us about it! Closing

**Comment by jurijus01** [comment]
In no way this is "very specific and relatively small in scope".

This malarkey with manual approval of everything makes it impossible to:
1) run Clef as a service
2) allow users to a website to create Ethereum accounts themselves

Please re-open.

**Comment by namiloh** [comment]
Do you want to run a server where "users of a website" create ethereum accounts? 
That does not sound like a usecase we want to endorse. 

Users should create their own accounts locally. "Not your keys, not your crypto".

**Comment by jurijus01** [comment]
Do you want to rather endorse Ethereum or it's competitors?
