### ISSUE TITLE
I can't import my wallet

### ISSUE THREAD

**Issue by CamTosh** [ethereum/go-ethereum#2684]
I'm using the  ```geth wallet import wallet```, after typing the _correct_ PassPhrase I have this error 
> ```Fatal: invalid character 'ù' looking for beginning of value```

**Comment by karalabe** [comment]
What version of Geth are you using?

**Comment by CamTosh** [comment]
1.4.5-stable

**Comment by karalabe** [comment]
@fjl Could you please take a look into this?

**Comment by fjl** [comment]
The message sounds like the key file contains invalid JSON. Note that the file is not parsed before entering the passphrase. Obviously you cannot give us your key file. Please try decoding the file as JSON using a scripting language [jq](https://stedolan.github.io/jq/).

**Comment by CamTosh** [comment]
I think it's the scp moved who changed the file encoding, I try with rsync

**Comment by fjl** [comment]
Can we close this then?

**Comment by CamTosh** [comment]
No, I have export the file one more time and I have the same error, I try jq

**Comment by fjl** [comment]
So the file "wallet" is valid JSON.
I checked the code and I'm not sure how this error could happen if the file is valid.

**Comment by CamTosh** [comment]
I have use ```geth export fichier.json```

**Comment by karalabe** [comment]
`geth export` exports the blockchain, not an account. If you want to load the account from another machine, just copy over the key file from that other machine into the new one's keystore folder. It should pick it up immediately.

**Comment by CamTosh** [comment]
Oh, it's done, thx for your time !
