### ISSUE TITLE
High CPU usage on version 1.11.3

### ISSUE THREAD

**Issue by begetan** [ethereum/go-ethereum#26855]
#### System information

```
geth version
Geth
Version: 1.11.3-stable
Git Commit: 5ed08c4735c9d034fface08e4c400f1bd1ba8318
Git Commit Date: 20230307
Architecture: amd64
Go Version: go1.20.2
Operating System: linux

```
CL client & version:
```
beacon-chain --version
beacon-chain version Prysm/v3.2.0/3d6d0a12dd189abcd2cfbba1c3d56505a1dd595c. Built at: 2022-12-15 23:40:50+00:00

```
OS & Version: 
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

```

#### Issue
After upgrade from version 1.10.xx to 1.11.3 cpu utilization is significantly higher both for Mainnet and Goerli network
Restart may help sometimes, but it goes to high usage value back. Prysm beacon usage is fare below 50% of a single core.

I want also to notice high outgoing networok traffic correlated with the CPU utilization which continues for days. 

This is stat for Goerli on i5-7500 CPU.

![Screenshot 2023-03-10 at 16 10 57](https://user-images.githubusercontent.com/17225934/224352239-b25c656e-9ec8-4f1b-a60a-e8dfbe513b71.png)

**Comment by MariusVanDerWijden** [comment]
We know, fix is incoming

**Comment by nuliknol** [comment]
@MariusVanDerWijden what is the commit to fix the issue?

**Comment by MariusVanDerWijden** [comment]
This was the fix: https://github.com/ethereum/go-ethereum/pull/26907
