### ISSUE TITLE
Goerli node problem

### ISSUE THREAD

**Issue by kugimiya530** [ethereum/go-ethereum#26868]
Hi i am using Geth 1.11.4  and lighthouse 3.5.1

and after launch geth and lighthouse the geth keep showing

WARN [03-13|06:09:49.601] Served engine_exchangeTransitionConfigurationV1 conn=127.0.0.1:45668 reqid=1 duration="84µs" err="invalid ttd: execution 10790000 consensus 0xc70d808a128d7380000"

and not sync。 how can i solve this   please!

**Comment by kugimiya530** [comment]
for reference

lighthouse

./lighthouse bn --network goerli --http --execution-endpoint http://localhost:8551 --execution-jwt /tmp/jwtsecret
   
Geth

./geth --datadir ./node --cache 32000 --goerli --rpc.allow-unprotected-txs --txlookuplimit 0 --http --http.api eth,net,web3,txpool --http.vhosts '*' --ws  --ws.origins '*' --ws.api eth,net,web3,txpool,debug --snapshot=true --syncmode=full --rpc.txfeecap 0 --maxpeers 1111 --ipcpath /geth.ipc --nousb --port 30303 --discovery.port 30303  --authrpc.addr localhost --authrpc.port 8551 --authrpc.vhosts localhost --authrpc.jwtsecret /tmp/jwtsecret

**Comment by rjl493456442** [comment]
`0xc70d808a128d7380000` consensus layer definitely has a wrong ttd configuration. Perhaps you should open the ticket in lighthouse repo.

**Comment by kugimiya530** [comment]
yes.... after using prysm i solved , lol
