### ISSUE TITLE
`t8n` tool behaves differently for different unsupported transaction types

### ISSUE THREAD

**Issue by gurukamath** [ethereum/go-ethereum#26861]
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: OSX
Commit hash : `master` (789de23d16045190af3ace2276ea3957190e869b)

#### Expected behaviour
When a `1559` transaction is passed to a fork prior to `London`, the `t8n` tool does not quit with an error. It also outputs the `alloc.json` and `results.json` with the unsupported transaction in the `rejected` list.

However, if an `AccessListTransaction` is passed to a fork prior to `Berlin`, the tool quits and no `alloc.json` and `result.json` are written.

#### Actual behaviour
The behaviour should probably be the same since the issue is similar.

#### Steps to reproduce the behaviour

1559 Transaction

```
./evm t8n --input.alloc testdata/10/alloc.json --input.env testdata/10/env.json --input.txs testdata/10/txs.json --state.fork Frontier
```

```
WARN [03-11|10:15:38.265] rejected tx                              index=0 hash=88980f..206701 error="transaction type not supported"
WARN [03-11|10:15:38.265] rejected tx                              index=1 hash=d7bf38..757582 error="transaction type not supported"
WARN [03-11|10:15:38.265] rejected tx                              index=2 hash=503082..4923db error="transaction type not supported"
WARN [03-11|10:15:38.265] rejected tx                              index=3 hash=db07bf..ede1e8 error="transaction type not supported"
INFO [03-11|10:15:38.265] Trie dumping started                     root=cb88fe..096060
INFO [03-11|10:15:38.265] Trie dumping complete                    accounts=4 elapsed="42.834µs"
INFO [03-11|10:15:38.265] Wrote file                               file=alloc.json
INFO [03-11|10:15:38.266] Wrote file                               file=result.json
```

`AccessListTransaction`

```
./evm t8n --input.alloc testdata/8/alloc.json --input.env testdata/8/env.json --input.txs testdata/8/txs.json --state.fork Frontier
```

```
ERROR(10): failed signing transactions: ERROR(10): tx 0: failed to sign tx: transaction type not supported
```

**Comment by holiman** [comment]
No, I think the difference is if you sign it yourself or ask t8n to sign it. If you ask t8n to sign it for you, it uses the latest signer for that fork. And thus fails to sign it.

**Comment by gurukamath** [comment]
Thank you. I missed this distinction.
