### ISSUE TITLE
Where is genesis.json for Mainnet?

### ISSUE THREAD

**Issue by 5ylar** [ethereum/go-ethereum#26889]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

**Comment by s1na** [comment]
The genesis configuration for mainnet are included in the code. You can see it here: https://github.com/ethereum/go-ethereum/blob/6bc68f8d94b359e08beefa2b6006e5ad003519f9/core/genesis.go#L522.
