### ISSUE TITLE
Why delete a child of a parent while dereferencing only when its reference count is zero?

### ISSUE THREAD

**Issue by jongrun** [ethereum/go-ethereum#26884]
https://github.com/ethereum/go-ethereum/blob/e5eb32acee19cc9fca6a03b10283b7484246b15a/trie/database.go#L505-L506
@karalabe  When a child is dereferenced from a parent, it is no longer a child of the parent. So why not delete it directly but only when its reference count is zero?

**Comment by holiman** [comment]
I don't follow. But the reference count is a count of "how many objects reference me". As long as a non-zero number references to X are held, we cannot delete X.

**Comment by jongrun** [comment]
> I don't follow. But the reference count is a count of "how many objects reference me". As long as a non-zero number references to X are held, we cannot delete X.

I don't mean that we delete the X node in dirty, but only delete the child item in the map `node.children`. The reason is that the node is no longer the child of the parent if it is dereferenced, no matter how many objects reference it.

**Comment by karalabe** [comment]
There's a meta-parent (0x00) that references all live root hashes of account tries. Previously on Clique and newly on post-merge mainnet too we can have 2 state tries have the same root, in which case we can have 2 references going from 0x00 to 0xchild. Dereferencing one should not dereference the other.
