### ISSUE TITLE
Release 1.11.4 not available in Launchpad PPA

### ISSUE THREAD

**Issue by torfbolt** [ethereum/go-ethereum#26886]
#### Expected behaviour

Released binaries are pushed to https://launchpad.net/~ethereum/+archive/ubuntu/ethereum

#### Actual behaviour

The latest available binary version is 1.11.3

#### Steps to reproduce the behaviour

1. Go to https://launchpad.net/~ethereum/+archive/ubuntu/ethereum
2. Observe that only ethereum-unstable builds are at verion 1.11.4, the release builds are still at 1.11.3

**Comment by torfbolt** [comment]
Could this be related to https://github.com/ethereum/go-ethereum/commit/df027995437d84ae8f0476a1be42a3dba64edae1 ?

**Comment by Austindgk232** [comment]
``

**Comment by c0deright** [comment]
Please investigate. We had to switch to `ethereum-unstable` for v1.11.4 and would like to switch back to `ethereum` (stable).

**Comment by c0deright** [comment]
@aribo latest in `ethereum-unstable` is v1.11.4

Looks like 1.11.5 isn't packaged yet.

**Comment by aribo** [comment]
It seems so. Would you recommend to install unstable versions?

**Comment by c0deright** [comment]
It's just the name - the v1.11.4 in unstable is the same v1.11.4 released some days ago.

The name tag "unstable" ist is just wrong since this repo doesn't release unstable builds, see https://github.com/ethereum/go-ethereum/releases

**Comment by karalabe** [comment]
For some weird reason the front page of the PPA is cached on an old listing and very rarely it prints the build status, most often not. Will check on it in a bit to see if it gets it's act together.

**Comment by torfbolt** [comment]
Looks good now.

**Comment by c0deright** [comment]
Perfect, thanks!
