### ISSUE TITLE
Block hash inconsistency starts from this block 8656123

### ISSUE THREAD

**Issue by caiyangwei** [ethereum/go-ethereum#26892]
![image](https://user-images.githubusercontent.com/30101744/225268327-f0023e6f-4d0c-4a38-ab34-ac3ea309b23b.png)

**Comment by holiman** [comment]
Please provide textual info, and/or the hashes in text form, and/or link to etherscan so we can check what block that is.

**Comment by levinmy** [comment]
![image](https://user-images.githubusercontent.com/87064179/225274630-37bdf693-4f9e-4a23-a52b-eed7ff7794b9.png)
![image](https://user-images.githubusercontent.com/87064179/225274848-f76833d7-21c7-4eb9-9bf7-c538bcf574b8.png)

goerli testnet
github.com/ethereum/go-ethereum v1.10.26

**Comment by levinmy** [comment]
![image](https://user-images.githubusercontent.com/87064179/225276635-b9eb32b6-5638-4fc4-a1fa-a8231602404c.png)
![image](https://user-images.githubusercontent.com/87064179/225276684-34ae41a2-9289-45bd-b273-ac0746468453.png)

**Comment by holiman** [comment]
https://goerli.etherscan.io/block/8656123 - -hash is `0x4fed6603f749a4bd18a5e3cd21922327a18b20167d084e9e25a36e0a3ffcb334`. 

https://blog.ethereum.org/2023/03/08/goerli-shapella-announcement 

> Withdrawals are coming! The Shapella network upgrade will activate on the Goerli network at epoch 162304, scheduled for 10:25:36 PM UTC on Mar. 14, 2023

So the block/header changed yesterday, and vresion `1.10.26` is not recent enough to handle that.

**Comment by caiyangwei** [comment]
I have tried to use different node providers, which is the same problem.
infura
getblock
quicknode  1.11.4 Geth

Does v1.11.4 not solve this problem

**Comment by holiman** [comment]
@caiyangwei what version of geth are you using? 

In our ticket template we have this section:
```
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)
```
It makes things easier to debug if we have that info, such as `geth version`, hence why we put it into the template.

**Comment by caiyangwei** [comment]
@holiman 
I use the node service of a third-party provider, and the client info displayed is v1.11.4 (quicknode)，but I am not sure whether the version they display is correct， I cannot log in to the server to view the installed Geth version。

![image](https://user-images.githubusercontent.com/30101744/225299649-22840de7-4234-42c3-bcc6-e8006190b489.png)

**Comment by caiyangwei** [comment]
`// GetBlockByHash returns the given full block.
// https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getblockbyhash
func (ec ETHClient) GetBlockByHash(ctx context.Context) (block *types.Block, err error) {

	end := startSpan(ctx, "GetBlockByHash")
	defer end()

	blockHash := common.HexToHash("0x4fed6603f749a4bd18a5e3cd21922327a18b20167d084e9e25a36e0a3ffcb334")

	fmt.Printf("old_blockHash: %s\n", blockHash.Hex())
	if block, err = ec.gethClient.BlockByHash(ctx, blockHash); err != nil {
		err = errors.WithStack(err)
	}

	fmt.Printf("new_blockHash: %s\n", block.Hash().Hex())
	return
}`

**Comment by caiyangwei** [comment]
`
// GetBlockByHash returns the given full block.
// https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getblockbyhash
func (ec ETHClient) GetBlockByHash(ctx context.Context) (block *types.Block, err error) {

	end := startSpan(ctx, "GetBlockByHash")
	defer end()

	blockHash := common.HexToHash("0x4fed6603f749a4bd18a5e3cd21922327a18b20167d084e9e25a36e0a3ffcb334")

	fmt.Printf("blockHash: %s\n", blockHash.Hex())
	if block, err = ec.gethClient.BlockByHash(ctx, blockHash); err != nil {
		err = errors.WithStack(err)
	}

	fmt.Printf("blockHash: %s\n", block.Hash().Hex())
	return
}
`

![image](https://user-images.githubusercontent.com/30101744/225305754-5c7c37f4-2508-42dd-9efa-0de01731dc00.png)

I use this method “BlockByHash” to obtain block details，There should be no difference between the ”blockHash“ printed twice

**Comment by holiman** [comment]
I'm wondering about `ec.gethClient`. What is `gethClient`? Is it the package `ethclient/gethlient` in go-ethereum repository, and if so, what is the commit-hash of the code?

**Comment by caiyangwei** [comment]
Sorry, I found a problem. I used github.com/etherem/go-etherum v1.10.26
