### ISSUE TITLE
-32000, future transaction tries to replace pending

### ISSUE THREAD

**Issue by xihucuyu888** [ethereum/go-ethereum#26890]
node error: {-32000, future transaction tries to replace pending}
I send 2 txs with nonce 0 and 1 to the geth simultaneously and the node return this error, why?

**Comment by starwill** [comment]
I have the same error，when send transaction with nonce- n success，send nonce- n+1 will return this error after geth client upgrade

**Comment by MariusVanDerWijden** [comment]
This is the new rule added in 1.11.4, A future transaction can not be added to the tx pool if it would replace pending transactions. This is a safety mechanism. Is this happening with transactions that you send via `eth_sendRawTransaction`?

**Comment by MariusVanDerWijden** [comment]
Okay I looked through the code, seems we check this for local transactions as well. I think we can skip this check for local transactions

**Comment by karalabe** [comment]
There is a slight race if you submit multiple transactions currently. Transaction N enters the pool but will be marked as executable a bit later (hundreds of millisecs I think), in which time N+1 might be rejected. The quick and dirty solution currently it to wait a bit before subsequent nonce submissions. We'll make the above mentioned protection a bit smarter not to have this bug in the next release.

**Comment by swoonai** [comment]
This is happening widespread.

**Comment by MariusVanDerWijden** [comment]
@swoonai Please update to the newest release v.1.11.5

**Comment by zk-Lumi** [comment]
For what it's worth +1 for Matter Labs team

**Comment by miohtama** [comment]
I have observed this issue as well

- It happens with SaaS RPC providers like Alchemy
- It happens because a series of `eth_sendRawTransaction` calls are incorrectly routed to multiple RPC backends
- These RPC backends are not correctly sync in each other, and some of the backends are missing the prior broadcast

One solution: Switch to more hiqh quality RPC service provieder

**Comment by Archethect** [comment]
> For what it's worth +1 for Matter Labs team, still an issue

Experiencing it as well using ZK Stack!

**Comment by pheix** [comment]
Got this error using Alchemy

**Comment by nmalzieu** [comment]
Got this error using `eth_sendRawTransaction` on the base sequencer, sending many tx (with increasing nonce) in a row!
