### ISSUE TITLE
How can I speed up my geth ws server to get the trasaction more quickly?

### ISSUE THREAD

**Issue by James1847** [ethereum/go-ethereum#26905]
Here is my server configruration: 
1\ location: Tencent cloud - Hongkong
2\ 32G RAM,  2T  SSD
3\ I bought quicknode rpc, but my own is slower than quicknode for almost 2 seconds

**Comment by holiman** [comment]
> slower than quicknode for almost 2 seconds

What metric are you using to determine speed? How are you measuring?

**Comment by James1847** [comment]
I used two program to subscribe pending transactions at same time, one is using QuickNode wss RPC  and the other using mine geth ws RPC, same pending transaction hash will always appear on the QuickNode program, and almost 1 or 2 seconds later, the other  program using geth will get the that hash

**Comment by James1847** [comment]
> 

I used two program to subscribe pending transactions at same time, one is using QuickNode wss RPC  and the other using mine geth ws RPC, same pending transaction hash will always appear on the QuickNode program, and almost 1 or 2 seconds later, the other  program using geth will get the that hash

**Comment by 0x0elliot** [comment]
spit balling here, and definitely not the easiest solution, but i wonder if maybe you can listen to the levelDB changes that geth makes in chaindata?

**Comment by holiman** [comment]
IF we had a magic bullet to speed up the geth ws server, we would have applied it already. If you come up with something, let us know! Closing
