### ISSUE TITLE
What a misleading information?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ethereum/go-ethereum#26900]
I can see this:

This document has been moved to the Geth documentation site:

https://geth.ethereum.org/docs/install-and-build/installing-geth#run-inside-docker-container

And if I click on the above link, I got 404, page not exist!

**Comment by s1na** [comment]
The Geth website was redone recently and unfortunately existing links broke. Where did you see that link? I will go and fix it. The new link is https://geth.ethereum.org/docs/getting-started/installing-geth#docker-container.

It is not misleading information, rather simply outdated link. Your tone is not appreciated. You're welcome to submit a fix when you see an issue. It is an open source code.
