### ISSUE TITLE
Goerli  out of memory

### ISSUE THREAD

**Issue by sundafa** [ethereum/go-ethereum#26904]
#### System information

Geth version: v1.11.4
CL client & version: e.g. lighthouse and prysm
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Stable memory usage

#### Actual behaviour
The memory rises sharply every 3 hours, and the service is killed due to insufficient memory

#### Steps to reproduce the behaviour
none

#### Backtrace

````
The run log looks like everything is ok
````

In specific cases, only the picture display is more intuitive

![image](https://user-images.githubusercontent.com/24621599/225552076-e976f7f1-b248-4533-aa68-e26830868b73.png)

**Comment by rjl493456442** [comment]
Can you share the command line flags for starting Geth?

**Comment by sundafa** [comment]
@rjl493456442 
```
${nodeServiceDir}/bin/geth --goerli --syncmode snap --gcmode=full --datadir ${nodeServiceDir}/geth/ --rpc.evmtimeout='10s' --snapshot=false --light.maxpeers=0 --http.vhosts=* --http.corsdomain=* --http --http.addr ${listeningAddr} --http.api eth,net,web3,debug,trace,txpool --ws.api=eth,net,web3,debug,trace,txpool --ws --ws.addr ${listeningAddr} --metrics --metrics.addr localhost --port 31030 --http.port 31031 --ws.port 31032 --authrpc.port 31033 --metrics.port 31035
```

**Comment by JAVAN000B** [comment]
I also have the same problem. After updating to v1.11.3, my geth on goerli kept running out of memory, and  I am wondering if we can set some flags when lauching geth to avoid this.

**Comment by MariusVanDerWijden** [comment]
There was an attack happening on goerli that uses a lot of memory/cpu. Updating to v1.11.4 or higher should mitigate the attack

**Comment by JAVAN000B** [comment]
I think I find the answer why my geth kept running huge RAM and then killed by system. I added --maxpeer 1000 when launcing geth.  When I last check my node, it already connected 337 other geths. Never expected these connections are such resource consuming things.(about 4gb) Can we estimated how much ram will be consumed per connection, as I found this is not counted by pprof. When I looked localhost:6060/memsize, it is different from what I found on `top`

**Comment by fjl** [comment]
> Can we estimated how much ram will be consumed per connection, as I found this is not counted by pprof.

This is very hard to estimate. But I would say, 1000 peers is way too much. You won't gain anything from having so many. Maybe reduce it to 100 or so.

> localhost:6060/memsize, it is different from what I found on top

Note that memsize cannot not show all memory used. It is more like a debugging tool for geth developers.
