### ISSUE TITLE
TransactionByHash `from` field not found 

### ISSUE THREAD

**Issue by 0xfaceDEFI** [ethereum/go-ethereum#26915]
use `TransactionByHash` method can not get `from` field.

is there any way to get the `from` field from the pending tx ?

**Comment by jsvisa** [comment]
Do you mean the transactions in the txpool? if so, you can get those transaction via `txpool_content`

**Comment by panicalways** [comment]
```go
func calcFrom(tx *types.Transaction) common.Address {
	msg, err := tx.AsMessage(types.LatestSignerForChainID(tx.ChainId()), nil)
	if err != nil {
		panic(err)
	}

	return msg.From()
}
```

**Comment by panicalways** [comment]
In latest version
```go
func calcFrom(tx *types.Transaction) common.Address {
	msg, err := core.TransactionToMessage(tx, types.LatestSignerForChainID(tx.ChainId()), nil)
	if err != nil {
		panic(err)
	}

	return msg.From()
}
```

**Comment by s1na** [comment]
I can't reproduce this issue. Here's getting a pending tx by its hash. You can see it has a `from` field:

```terminal
> eth.getTransaction('0xb615a9c52e7d619784a621f36405462cc31051bec712d26c2d49abc0e2ad7af8')
{
  blockHash: null,
  blockNumber: null,
  chainId: "0x1",
  from: "0xff1e76c528f4d94093d727323f0c55944d8d2dcd",
  gas: 21000,
  gasPrice: 14391756805,
  hash: "0xb615a9c52e7d619784a621f36405462cc31051bec712d26c2d49abc0e2ad7af8",
  input: "0x",
  nonce: 3,
  r: "0x9c86fdc4328a6e1cca31c07d1663394e5b075737f74cac0495a6e63e9ff1c5d3",
  s: "0x6a2260d544e9440a77e2a0d29404c8b0b9003689019f28521dadcbf8f1bbd69c",
  to: "0x52a258ed593c793251a89bfd36cae158ee9fc4f8",
  transactionIndex: null,
  type: "0x0",
  v: "0x26",
  value: 67001000000000000
}
```

**Comment by fjl** [comment]
So here's how to get the sender for a pending transaction:

```go
signer := types.LatestSignerForChainID(chainid)

tx, err := c.TransactionByHash(context.Background(), txhash)
if err != nil {
    return err
}
sender, err := types.Sender(signer, tx)
if err != nil {
    return err
}
fmt.Println("tx sender:", sender)
```

**Comment by 0xfaceDEFI** [comment]
> 

ths bro . not it worked for me

**Comment by Sledro** [comment]
> @panicalways Please do not use `core.TransactionToMessage` to compute the sender. Use [`types.Sender`](https://pkg.go.dev/github.com/ethereum/go-ethereum/core/types#Sender) instead!

Hey, just curious as to why we shouldn't do it this way?

**Comment by fjl** [comment]
It's better to use `types.Sender` because it's the official API function to get the transaction sender. Converting the transaction to `core.Message` will also just call `types.Sender` and then compute some other fields as well, which you do not need if all you care about is the sender address.
