### ISSUE TITLE
the method personal_unlockAccount does not exist/is not available

### ISSUE THREAD

**Issue by cisan86** [ethereum/go-ethereum#26916]
when i use web3.personal.unlockAccount(), it shows Error: the method personal_unlockAccount does not exist/is not available

**Comment by holiman** [comment]
See release-notes for 1.11.0 https://github.com/ethereum/go-ethereum/releases/tag/v1.11.0: 

> The `personal` RPC namespace is now deprecated. In order to interact with personal APIs, you need to specifically allow it via the `--rpc.enabledeprecatedpersonal` command-line flag.
