### ISSUE TITLE
geth in windows requires unix style path in datadir option

### ISSUE THREAD

**Issue by varunamrutiya** [ethereum/go-ethereum#2692]
While using the `--datadir` option with geth (latest windows build) , It requires entry of file path as `geth.exe --datadir="C:/blockchain/"` while it should have file path in windows style. The `geth help` gave and example like `C:\xxx\xxx` which is a contradiction. btw when providing file path as `--datadir="C:\blockchain\" ` gave an error. Seems like it requires unix styled path entry.

(Note: notice the forward and the backwards slash )

**Comment by Kojee** [comment]
I tried the command `geth --datadir "C:\Users\Marco\AppData\Roaming\Ethereum"` wich was suggested in geth --help, and it gave no errors.
I even tried using `geth --datadir="C:\Users\Marco\AppData\Roaming\Ethereum"` with the = sign before the option and it gave no error too.
Can you report the error that geth gives you?

**Comment by karalabe** [comment]
Could you also tell us the Geth version and also where you got the binary from? (I.e. stable build from the release page, build servers or the cross builds)?

**Comment by varunamrutiya** [comment]
This are the errors.

```
F:\geth>geth.exe version
Geth
Version: 1.4.6-stable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: windows
GOPATH=
GOROOT=c:\go


F:\geth>geth.exe --datadir "H:\blockchain\"
I0615 14:27:41.321977 ethdb/database.go:82] Alloted 128MB cache and 1024 file ha
ndles to H:\blockchain"\chaindata
Fatal: Could not open database: GetFileAttributesEx H:\blockchain"\chaindata: Th
e filename, directory name, or volume label syntax is incorrect.
Fatal: Could not open database: GetFileAttributesEx H:\blockchain"\chaindata: Th
e filename, directory name, or volume label syntax is incorrect.


F:\geth>geth.exe --datadir "H:/blockchain/"
I0615 14:28:00.716867 ethdb/database.go:82] Alloted 128MB cache and 1024 file ha
ndles to H:\blockchain\chaindata
I0615 14:28:46.477842 ethdb/database.go:169] closed db:H:\blockchain\chaindata
I0615 14:28:46.478842 cmd/utils/flags.go:601] WARNING: No etherbase set and no a
ccounts found as default
I0615 14:28:46.484842 ethdb/database.go:82] Alloted 128MB cache and 1024 file ha
ndles to H:\blockchain\chaindata
I0615 14:28:46.754857 ethdb/database.go:82] Alloted 16MB cache and 16 file handl
es to H:\blockchain\dapp
I0615 14:28:46.814861 eth/backend.go:172] Protocol Versions: [63 62 61], Network
 Id: 1
I0615 14:28:46.872864 eth/backend.go:201] Blockchain DB Version: 3
I0615 14:28:46.882865 core/blockchain.go:206] Last header: #1703390 [3db9c098.]
TD=27490137819777274469
I0615 14:28:46.882865 core/blockchain.go:207] Last block: #1703390 [3db9c098.] T
D=27490137819777274469
I0615 14:28:46.883865 core/blockchain.go:208] Fast block: #1703390 [3db9c098.] T
D=27490137819777274469
I0615 14:28:47.044874 p2p/server.go:313] Starting Server
```

Try using some other drive letter.

**Comment by bas-vk** [comment]
This is probably caused by the console.

`geth>geth.exe --datadir "H:\blockchain\"` translates to a datadir in of `H:/blockchain"` which is invalid. You have 2 options:
1. `geth>geth.exe --datadir "H:\blockchain"`
2. `geth>geth.exe --datadir "H:\blockchain\\"`

Both have the same semantics.

**Comment by bas-vk** [comment]
@varunamrutiya, if you confirm that was the issue, and if so close the issue?

**Comment by Neurone** [comment]
I use Windows too, and I confirm this is not a geth problem. With the Windows console (like in many other shell and programming languages) you use \" as the escape character when you want actually insert a _double quote character_ inside a string, and the string itself is delimited by double quotes.

So writing `--datadir="H:\Blockchain\"` you are actually passing `H:\Blockchain"` as parameter. You can avoid that behavior removing both double quote:

`F:\geth>geth.exe --datadir H:\blockchain\`

Note that you can do this because in your case there are no spaces in the datadir path.

**Comment by varunamrutiya** [comment]
Found the issue, I was adding the extra backslash at the end which was not needed like 
`F:\geth>geth.exe --datdir "H:\blockchain\" `  removing it solved the issue.
                                                                ^
