### ISSUE TITLE
Can we prune the stale state offline by iterating a recent trie if snapshot is not open?

### ISSUE THREAD

**Issue by jongrun** [ethereum/go-ethereum#26943]
@rjl493456442 It‘s more efficient pruning the stale state offline by iterating the snapshot. But if performance is put aside, is it feasible to prune by iterating a recent trie.
https://github.com/ethereum/go-ethereum/blob/b3f43c89b3b884d5d0b8e1a239847f54a291a19b/core/state/pruner/pruner.go#L64-L81

**Comment by rjl493456442** [comment]
@jongrun It's feasible to iterate the target state by trie, but it's just extremely slow(10x slower).

There are multiple reasons for the huge performance difference between trie and snapshot:
- trie nodes are stored by hash in database with no space locality, reads them out will involve huge read amplification
- all the internal trie nodes must be resolved first in order to access the state
- snapshot data are stored in order in disk, iterate them out is fast with good space locality
- snapshot data can be iterated directly without reading any internal trie nodes

It's the main reason we choose snapshot as the entry point.

**Comment by jongrun** [comment]
> @jongrun It's feasible to iterate the target state by trie, but it's just extremely slow(10x slower).
> 
> There are multiple reasons for the huge performance difference between trie and snapshot:
> 
> * trie nodes are stored by hash in database with no space locality, reads them out will involve huge read amplification
> * all the internal trie nodes must be resolved first in order to access the state
> * snapshot data are stored in order in disk, iterate them out is fast with good space locality
> * snapshot data can be iterated directly without reading any internal trie nodes
> 
> It's the main reason we choose snapshot as the entry point.

At present, we have no choice to use the target trie to prune when the snapshot is not open.
Snapshot can accelerate data reading but is also requires more space. If someone have no demand on reading performance but low space occupation is more important for him, he may close the snapshot, which make pruning impossible. Why is there no option to prune by iterating the target trie.

**Comment by holiman** [comment]
> If someone have no demand on reading performance but low space occupation
>  Why is there no option to prune by iterating the target trie.

Because if the constraints are: 
- We have all the time in the world (doesn't matter if it takes months to sync, or weeks to prune), 
- But we are so limited on disk that we cannot take an ~30 % overhead using snapshots

Then those constraints do not match most real-world situations, and we target common users, not nice usecases.

**Comment by jongrun** [comment]
If pruning by snapshot takes 2 hours, then 10x is 20 hours. If we prune periodically, e.g. one time per month, the cost is tolerable.
Or in other words, before the snapshot released, why don't we prune the database by a target trie, but resync? Is it more time-consuming than resyncing?

**Comment by rjl493456442** [comment]
@jongrun Offline pruner will be deprecated soonish. We will ship path-based storage scheme and encourage people to use it as default, in which the stale data is pruned by default. 

So we don't pay too much attention to the existent pruner, but focus one the new scheme instead.

**Comment by jongrun** [comment]
@rjl493456442 Is there any describtion or discuss about the path-based storage scheme you refered? And when is this feature scheduled for release? Is the issue [Trie pruning v9000](https://github.com/ethereum/go-ethereum/issues/23427) relevant?

**Comment by jongrun** [comment]
> @jongrun Offline pruner will be deprecated soonish. We will ship path-based storage scheme and encourage people to use it as default, in which the stale data is pruned by default.
> 
> So we don't pay too much attention to the existent pruner, but focus one the new scheme instead.

@rjl493456442 Is there any describtion or discuss about the path-based storage scheme you refered? And when is this feature scheduled for release? Is the issue https://github.com/ethereum/go-ethereum/issues/23427 relevant?

By the way, what is the recommended way to prune data before the new storage scheme releases, prune by snapshot or resync?

**Comment by rjl493456442** [comment]
We are actively working on the path-based storage one https://github.com/ethereum/go-ethereum/pull/25963/, need reviews still.

If you don't maintain snapshot, just resync, otherwise you can run this tool. Iterating trie directly will take more than a day which can be even slower than resync.

**Comment by jongrun** [comment]
> 

Great work! Is the issue https://github.com/ethereum/go-ethereum/issues/23427 has the same or similar idea? Or it is another direction?

**Comment by jongrun** [comment]
@rjl493456442 Can we archive states for the last N months only?
In current version, we have two extreme options:
- either run archive node with ALL historical states
- or full node with only recent state (last 128 blocks in momery for mini reorg)

But in archive node case, some too-old states (e.g. 3 months ago) may not be used in most cases. Is there any solution to store states for only the last N months or last N blocks? Looking forward to your reply.

related issue: https://github.com/ethereum/go-ethereum/issues/26981
