### ISSUE TITLE
Geth sync in full mode is extremely slow

### ISSUE THREAD

**Issue by rbartoli** [ethereum/go-ethereum#26942]
I've previously synced geth in full mode on a Windows 10 desktop pc. 

The specs are:
- Intel i7 9700k
- 16GB RAM
- 2TB NVME (Samsung 970 EVO Plus)

I'm launching geth with the following options:
`geth.exe --syncmode full --datadir Z:\BLOCKCHAINS\ETHEREUM-GETH --ws --ws.api eth,net,web3 --authrpc.jwtsecret token\jwt.hex  --maxpeers 50 --snapshot=false --cache 8192`

I've now reinstalled the OS from scratch, Windows 11 Pro, done standard optimisation, and I get this syncing speed in blocks per second:
```
60% ETA: 82725 minutes @ 3.4bps
60% ETA: 61144 minutes @ 4.6bps
60% ETA: 62503 minutes @ 4.5bps
60% ETA: 57401 minutes @ 4.9bps
60% ETA: 47672 minutes @ 5.9bps
60% ETA: 52086 minutes @ 5.4bps
60% ETA: 65410 minutes @ 4.3bps
60% ETA: 63924 minutes @ 4.4bps
60% ETA: 68601 minutes @ 4.1bps
60% ETA: 56253 minutes @ 5bps
60% ETA: 65410 minutes @ 4.3bps
60% ETA: 51139 minutes @ 5.5bps
60% ETA: 50226 minutes @ 5.6bps
60% ETA: 55150 minutes @ 5.1bps
60% ETA: 50226 minutes @ 5.6bps
60% ETA: 53069 minutes @ 5.3bps
```
It feels way slower than before. I say feels because I haven't got the same measurement from when I was running this on Windows 10.

Is this normal? Am I doing something wrong?

**Comment by gballet** [comment]
Is `Z:` a local disk? Iirc, windows tends to allocate these letters for network drives, and if this is the case, then following the chain in `fullsync` mode will be quite slow.

As a general rule, if you disable the snapshot and run fullsync, it will be slower as well.

Could you provide a sample output of the sync? I'm looking for lines that say "Imported new chain segment".

**Comment by karalabe** [comment]
5 blocks per second is realistic-ish, processing a mainnet block when in sync takes about 150ms. I don't know what the speed was at block 10M though.

Though, why are you full syncing? I mean, if you want to verify the chain just for kicks, sure. Otherwise snap sync would get you done in half a day.

**Comment by rbartoli** [comment]
@karalabe Thanks for answering.

> 5 blocks per second is realistic-ish, processing a mainnet block when in sync takes about 150ms. I don't know what the speed was at block 10M though.

Sounds good, mainly wanted to check that there was no speed issue with Windows 11.

> Though, why are you full syncing? I mean, if you want to verify the chain just for kicks, sure. Otherwise snap sync would get you done in half a day.

Just wanted to experiment with it, no particular reason.
