### ISSUE TITLE
RPC Filter APIs for processing events dont work well with the need to read from committed blocks

### ISSUE THREAD

**Issue by dabooz** [ethereum/go-ethereum#2695]
#### System information

Geth version: all
OS & Version: all
Commit hash : 
#### Expected behaviour

This is really a design problem with the RPC API, not specific to the go implementation. If this issue needs to be forwarded to another issue repo, please let me know how and where.

In order to observe stable contract state and a stable event streams, eth apps need to be sure that they only read from committed blocks. This usually means reading from blocks not newer than a small number of blocks from the top of the chain. This makes the eth_getFilterChanges() API useless, eth_getFilterLogs() is all you need since the end block has to be fixed, and can never be "latest". Further, since the blocks that a given filter instance reads from are not modifiable, eth apps that process event streams must constantly obtain new filters to cover the new blocks as they are created over time. This is harder than it needs to be for eth apps. If there were an API to create a filter that read to the latest-x (where x is the number of committed blocks you want), then we could use a single filter with eth_getFilterChanges to see stable event streams without having to throw away and re-obtain new filters every few blocks.
#### Backtrace

```
[backtrace]
```

**Comment by frozeman** [comment]
I don't really follow your description. why is `eth_getFilterChanges('latest', 'latest')` a bad idea to get incoming blocks and its events?

we already added that your also get notified about revisions. You now get logs with `removed: true` if it was removed due to a fork

**Comment by phleemac** [comment]
@frozeman Could you please give more details about the `removed: true` field?  I couldn't find any mentions of it in the [https://github.com/ethereum/wiki/wiki/JSON-RPC](https://github.com/ethereum/wiki/wiki/JSON-RPC)

Another discrepancy is the `tag` field from `eth_getFilterChanges`.  It is mentioned in the wiki page but not in the actual result I've got using Geth:

> Geth
> Version: 1.4.7-stable-667a386d
> Protocol Versions: [63 62 61]
> Network Id: 1
> Go Version: go1.6.2
> OS: linux
> GOPATH=
> GOROOT=/opt/google/go
>

**Comment by dabooz** [comment]
@frozeman 
A dapp that is working from an event stream becomes exponentially difficult to write if it has to have compensation logic to deal with the fact that an event which it thought occurred in the past actually never occurred at all.

My point about eth_getFilterChanges is this:
If the dapp needs to have a stable event stream (i.e. events dont go away because forks are resolved before events are surfaced to the event handler in the dapp), then the only choice is to NOT read events from blocks that are newer than some x number of blocks from the top of the chain. Usually this is 5 blocks. The only filter API which allows me to read up to a specific block is getFilterLogs() with a start and end block where end is obviously never latest. As time moves on, new blocks are added to the chain and the old end is no longer the end. The end is now whatever the new top is minus 5 blocks is. But my filter stops at the old end, so now I have to throw away that filter and create a new one that covers the new blocks, ending 5 from the top. I would read the events again with getFilterLogs(). This pattern continues forever. Notice that I dont use getFilterChanges(), that's why I say it's useless. I can't use it at all because it always ends at latest. Latest is very hard for dapps to deal with. What I really want is an API like getFIlterChanges() where the end block is dynamically managed for me (it's not latest, it's latest minus x where x is something I specify, probably 5). In doing this, I can avoid throwing away filters all the time and creating new ones. I will have less code to manage as a dapp.
