### ISSUE TITLE
1.4.6 not available on Homebrew

### ISSUE THREAD

**Issue by mttkay** [ethereum/go-ethereum#2696]
It appears that the 1.4.6 release hasn't been synced to Homebrew yet.

Related question: http://ethereum.stackexchange.com/questions/5942/install-geth-1-4-6-on-mac

**Comment by karalabe** [comment]
We're pushing out 1.4.7 in an hour or so. That contains a test suite fix that was choking the homebrew builds. Hopefully it will be available asap.

**Comment by mttkay** [comment]
Fantastic, thanks!
