### ISSUE TITLE
Unable to `go get github.com/ethereum/go-ethereum/p2p/discv5`

### ISSUE THREAD

**Issue by visualbasic6** [ethereum/go-ethereum#26966]
Hi,

I can't perform `go get github.com/ethereum/go-ethereum/p2p/discv5` or find any documentation about any updated packages.

```
root@1986:~/test/5# go get github.com/ethereum/go-ethereum/p2p/discv5
go: module github.com/ethereum/go-ethereum@upgrade found (v1.11.5), but does not contain package github.com/ethereum/go-ethereum/p2p/discv5
```

What's up?

Thanks!

**Comment by lightclient** [comment]
This package was deleted in 2020 https://github.com/ethereum/go-ethereum/pull/21940. Please use `ithub.com/ethereum/go-ethereum/p2p/discover`.
