### ISSUE TITLE
private-network page returns 404

### ISSUE THREAD

**Issue by fildenisov** [ethereum/go-ethereum#26979]
#### System information
OS & Version: any

#### Expected behaviour
I can open and read https://geth.ethereum.org/docs/interface/private-network in browser

#### Actual behaviour
https://geth.ethereum.org/docs/interface/private-network return 404

#### Steps to reproduce the behaviour
open https://geth.ethereum.org/docs/interface/private-network in your browser

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/49239587/227719866-f11ea200-c556-4d29-adf6-d82495694811.png">

**Comment by rjl493456442** [comment]
The content has be moved to this location:

https://geth.ethereum.org/docs/fundamentals/private-network

Where did you find the URL(https://geth.ethereum.org/docs/interface/private-network)? We should fix it.
