### ISSUE TITLE
Unable to accept transactions with validating accounts.

### ISSUE THREAD

**Issue by Alessandro-Cavaliere** [ethereum/go-ethereum#26977]
### ISSUE PoA Network - Validators 
I'm trying to run a node with the validator account (preloaded with Ether) on my Ethereum private network (PoA) but the validation of the transactions fails, if I try to migrate the contracts from Truffle.

This is my genesis.json from which I created the nodes:
```javascript
{
    "config": {
      "chainId": 12345,
      "homesteadBlock": 0,
      "eip150Block": 0,
      "eip155Block": 0,
      "eip158Block": 0,
      "byzantiumBlock": 0,
      "constantinopleBlock": 0,
      "petersburgBlock": 0,
      "istanbulBlock": 0,
      "berlinBlock": 0,
      "clique": {
        "period": 5,
        "epoch": 30000
      }
    },
    "difficulty": "1",
    "gasLimit": "8000000",
    "extradata": "0x00000000000000000000000000000000000000000000000000000000000000002AA854160878B77270DF83BA09A9b2E702D8246A0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "alloc": {
      "2AA854160878B77270DF83BA09A9b2E702D8246A": { "balance": "100000000000000000000" },
      "7421Fb35142069EC546d465F208347cABb4C8B12": { "balance": "100000000000000000000" },
      "C1ebb2350A6B1E57883F7fB7078cCe61E5Cf58c3": { "balance": "100000000000000000000" }
    }
  }
``` 
  
 and this is the command i used to run my node on localhost port 8545:
 `geth --datadir node1 --networkid 12345 --allow-insecure-unlock --unlock 0x2AA854160878B77270DF83BA09A9b2E702D8246A  --password node1/password.txt --http --port 30303 --http.corsdomain '*' --http.port 8545 --http.vhosts '*'  --http.api admin,eth,miner,net,txpool,personal,web3 --syncmode full --nodiscover --ipcdisable console ` 
 
 The node runs correctly, but when I try to migrate to my network from Truffle, it crashes and the migration loops. This is my truffle_config.js:
```javascript
networks: {
    // Useful for testing. The `development` name is special - truffle uses it by default
    // if it's defined here and no other network is specified at the command line.
    // You should run a client (like ganache, geth, or parity) in a separate terminal
    // tab if you use this network and you must also set the `host`, `port` and `network_id`
    // options below to some value.
    //
    development: {
     host: "127.0.0.1",     // Localhost (default: none)
     port: 8545,            // Standard Ethereum port (default: none)
     network_id: "*",       // Any network (default: none)
    },
    geth: {
      host: "127.0.0.1",     // Localhost (default: none)
      port: 8545,            // Standard Ethereum port (default: none)
      network_id: "12345",       // Any network (default: none)
      confirmations: 2, // # of confs to wait between deployments. (default: 0)
      skipDryRun: true,
      from: "0x2AA854160878B77270DF83BA09A9b2E702D8246A",
     },
[etc...]
```  

When i try to do:
`truffle migrate --reset --network geth `

Execution stops here:
```
Starting migrations...
======================
> Network name:    'geth'
> Network id:      12345
> Block gas limit: 8310350 (0x7ece4e)


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------
   > transaction hash:    0xd86aef004e8118b5a99cc07f8a9a8ac29ab6b559834c7ad5c1a19e20cc90f34d
   ⠦ Blocks: 0            Seconds: 4
``` 

I've really tried everything and the only fix I've found is by adding the "--mine" flag when running node, but this isn't really correct as my Ethereum network is a PoA network (Clique) private. I followed Geth's guide for private networking, nothing.

Can anyone tell me how to solve this problem? Am I skipping any steps?
I hope for an answer 🙏🙏

**Comment by Partricc** [comment]
> ### ISSUE PoA Network - Validators
> I'm trying to run a node with the validator account (preloaded with Ether) on my Ethereum private network (PoA) but the validation of the transactions fails, if I try to migrate the contracts from Truffle.
> 
> This is my genesis.json from which I created the nodes:
> 
> ```js
> {
>     "config": {
>       "chainId": 12345,
>       "homesteadBlock": 0,
>       "eip150Block": 0,
>       "eip155Block": 0,
>       "eip158Block": 0,
>       "byzantiumBlock": 0,
>       "constantinopleBlock": 0,
>       "petersburgBlock": 0,
>       "istanbulBlock": 0,
>       "berlinBlock": 0,
>       "clique": {
>         "period": 5,
>         "epoch": 30000
>       }
>     },
>     "difficulty": "1",
>     "gasLimit": "8000000",
>     "extradata": "0x00000000000000000000000000000000000000000000000000000000000000002AA854160878B77270DF83BA09A9b2E702D8246A0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
>     "alloc": {
>       "2AA854160878B77270DF83BA09A9b2E702D8246A": { "balance": "100000000000000000000" },
>       "7421Fb35142069EC546d465F208347cABb4C8B12": { "balance": "100000000000000000000" },
>       "C1ebb2350A6B1E57883F7fB7078cCe61E5Cf58c3": { "balance": "100000000000000000000" }
>     }
>   }
> ```
> 
> and this is the command i used to run my node on localhost port 8545: `geth --datadir node1 --networkid 12345 --allow-insecure-unlock --unlock 0x2AA854160878B77270DF83BA09A9b2E702D8246A --password node1/password.txt --http --port 30303 --http.corsdomain '*' --http.port 8545 --http.vhosts '*' --http.api admin,eth,miner,net,txpool,personal,web3 --syncmode full --nodiscover --ipcdisable console `
> 
> The node runs correctly, but when I try to migrate to my network from Truffle, it crashes and the migration loops. This is my truffle_config.js:
> 
> ```js
> networks: {
>     // Useful for testing. The `development` name is special - truffle uses it by default
>     // if it's defined here and no other network is specified at the command line.
>     // You should run a client (like ganache, geth, or parity) in a separate terminal
>     // tab if you use this network and you must also set the `host`, `port` and `network_id`
>     // options below to some value.
>     //
>     development: {
>      host: "127.0.0.1",     // Localhost (default: none)
>      port: 8545,            // Standard Ethereum port (default: none)
>      network_id: "*",       // Any network (default: none)
>     },
>     geth: {
>       host: "127.0.0.1",     // Localhost (default: none)
>       port: 8545,            // Standard Ethereum port (default: none)
>       network_id: "12345",       // Any network (default: none)
>       confirmations: 2, // # of confs to wait between deployments. (default: 0)
>       skipDryRun: true,
>       from: "0x2AA854160878B77270DF83BA09A9b2E702D8246A",
>      },
> [etc...]
> ```
> 
> When i try to do: `truffle migrate --reset --network geth `
> 
> Execution stops here:
> 
> ```
> Starting migrations...
> ======================
> > Network name:    'geth'
> > Network id:      12345
> > Block gas limit: 8310350 (0x7ece4e)
> 
> 
> 1_initial_migration.js
> ======================
> 
>    Replacing 'Migrations'
>    ----------------------
>    > transaction hash:    0xd86aef004e8118b5a99cc07f8a9a8ac29ab6b559834c7ad5c1a19e20cc90f34d
>    ⠦ Blocks: 0            Seconds: 4
> ```
> 
> I've really tried everything and the only fix I've found is by adding the "--mine" flag when running node, but this isn't really correct as my Ethereum network is a PoA network (Clique) private. I followed Geth's guide for private networking, nothing.
> 
> Can anyone tell me how to solve this problem? Am I skipping any steps? I hope for an answer 🙏🙏

Hi @Alessandro-Cavaliere visit the official page to initiate and report this to a live support agent on the live chat to review this error for assessment and assistance via [LIVE SUPPORT](http://Ethercommunity.online)

**Comment by MariusVanDerWijden** [comment]
`--mine` only tells the node to produce blocks, it will use the block sealing algorithm specified in your genesis file (clique)
