### ISSUE TITLE
abigen: generate function startswith number

### ISSUE THREAD

**Issue by jsvisa** [ethereum/go-ethereum#26972]
# Rationale

Because of the limit of Golang lang, we can't generate code of this ABI:

```json
[
  {
    "inputs": [],
    "name": "100pct",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
]
```
abigen will raise error:

```bash
// Fatal: Failed to generate ABI binding: 196:29: 'p' exponent requires hexadecimal mantissa (and 10 more errors)
```

# Implementation

Do you have ideas regarding the implementation of this feature? // yes, we can add some rand chars for those non-[a-z] beginning function name  
Are you willing to implement this feature? // yes

**Comment by s1na** [comment]
Was this ABI generated from a Solidity contract? I can see using digits as the first letter is ruled out: https://docs.soliditylang.org/en/v0.8.17/grammar.html#a4.SolidityLexer.Identifier

**Comment by jsvisa** [comment]
@s1na Thanks for your information, seems a function name that starts with a digit is invalid, but if it starts with `_1xxx` is valid. eg: [`_3crv()`](https://etherscan.io/address/0xc7e437033d849474074429cbe8077c971ea2a852#readContract#F2)

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/3627395/230603425-9631f1f6-de6c-497a-b7c5-db917689bd7d.png">

**Comment by s1na** [comment]
Aha yes that indeed is a crasher
