### ISSUE TITLE
geth mainnet cannot start to sync

### ISSUE THREAD

**Issue by Nickie11** [ethereum/go-ethereum#26983]
I run the geth on Ubuntu, command as ./build/bin/geth --datadir /home/eth_data --syncmode snap console --port 57366.
The geth always runs like looking for peers and new local node record, and the peerCount only stays at 0,1,2. That's odd, and need I run the prysm consensus server?

**Comment by MariusVanDerWijden** [comment]
Yes you need to run a consensus layer client (prysm, lighthouse,...). Maybe your firewall blocks the connections?
