### ISSUE TITLE
evm: smart-contracts: unexpected bad integer values

### ISSUE THREAD

**Issue by edurbrito** [ethereum/go-ethereum#27009]
#### System information

By running the `geth version` command:

Version: 1.9.25-stable
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.19.7
Operating System: linux (actually running on an OpenWrt image, inside QEMU x86_64 with kvm)
GOPATH=
GOROOT=

I am running an Ethereum private network with the clique PoA consensus algorithm, with multiple nodes as signers, and others as clients.

#### Actual behaviour

This code exists within a very simple smart contract:

```
    int public count;

    // Function to get the current count
    function get() public view returns (int) {
        return count;
    }

    // Function to increment count by 1
    function inc() public {
        count += 1;
    }

    // Function to decrement count by 1
    function dec() public {
        // This function will fail if count = 0
        count -= 1;
    }
```

However, any call to this smart contract, more specifically to the `get()` function, always returns the value `-7.2143235047287905055446557179996963579510840293502015264854422142075635965924e+76` for the `count` variable.

Similar smart contracts, for example, with unsigned `uintXXX` variables would give me `4.3648854190028290368124427828690944273759144372138548774602369232303076466716e+76`.

There is something fundamentally wrong (probably with the whole system, maybe some system level dependency missing?) that I cannot uncover the cause.
The rest of the network operations work just fine, the blockchain is up and running, generating blocks and accepting usual transactions.

**Comment by holiman** [comment]
@edurbrito are you getting these results when using the console, or in other circumstances? If the former, then it's probably a duplicate

**Comment by edurbrito** [comment]
@holiman I tried both using the console and using `curl` (after parsing the hex output, I get the same weird value).

**Comment by holiman** [comment]
> `Version: 1.9.25-stable`

Oh, I didn't see that until now. So, that version is 2+ years, https://github.com/ethereum/go-ethereum/releases/tag/v1.9.25, released in Dec 2020. It is most definitely not capable of following mainnet, and furthermore, we will not investigate issues on such old versions. 
In most cases, it is just a waste of time which leads to finding out that the issue was fixed "a year ago". So closing
