### ISSUE TITLE
I want to develop a new chain based on go-ethereum and I need some help!

### ISSUE THREAD

**Issue by aoeng** [ethereum/go-ethereum#27005]
### There are currently several modifications:
1. Set the Gas consumed by all ETH transactions to 0,yes ,free
2. Set the gas consumption of officially certified contracts to 0, yes, Official certification and free
3. Using TRON's Reward Mechanism,yes,Vote to elect 12 super nodes, and each package super node will share 1ETH equally

and now ,I just modified the first,But I don't know if it's correct
```golang
// internal/ethapi/api.go=>DoEstimateGas
dataStr := args.Data.String()
if dataStr == "0x" && args.To != nil {
	return 0, nil
}
// core/state_transition.go => IntrinsicGas
if dataLen ==  0 and !isContractCreation {
        gas = 0
}
```
seems to be working fine!

but the other two i have no idea! can anyone help?

**Comment by holiman** [comment]
Sorry, but the go-ethereum maintainers cannot help out in custom forks, and the repo is not a notice-board for devs working on other projects.
