### ISSUE TITLE
Cannot Connect Bootnodes Using Other Machine

### ISSUE THREAD

**Issue by avenbreaks** [ethereum/go-ethereum#27017]
Getting error on bootnode, connect using other machine, and running with costumize chain.  my peer is not stable, i am running 2 geth nodes on 1 server and 2 beacon nodes, while adding bootnode to other machine it is not responding cannot connect, `admin.peers []`  but other bootnodes connect to my chain (sometimes). 

Api : http.api=admin,eth,net,web3,personal

GETH Log:
```
INFO [03-31|03:09:42.286] Looking for peers peercount=3 tried=105 static=0
INFO [03-31|03:09:51.322] Entered PoS stage
```

CL Log:
`Execution engine call failed            error: ServerMessage { code: -32000, message: "invalid terminal block hash" }, service: exec 
`

Manual Add Bootnode Peer:
`admin.addPeer("enode://809290e21b4eb6c376c23a5afd7e9f55a44e669f7e17f3512fe1f53d39b0cb4da699377861c5d2f3fdd6cd8039e4d9b03bc56d3cf0972f27d4e0a367a26a1a86@147.75.71.217:30303")`

```
net.listening = true
net. peerCount = 3
```

## Expected
connected to and part of the main peer on other machines, and can connect to the consensus layer and then download all the blocks that have been made

**Comment by avenbreaks** [comment]
before i used manual addpeer it worked fine, but after i restarted the server and i want to reconnect it cant happen, any suggestions for this? @holiman 

I blocked ports 30303/tcp & 30303/udp because when I checked using telnet it was connected but when I opened the telnet port it didn't respond

**Comment by holiman** [comment]
I have a really hard time following here. 

> Getting error on bootnode

Is it `geth` or the binary `bootnode`? What is the error? 

> while adding bootnode to other machine it is not responding cannot connect, admin.peers [] but other bootnodes connect to my chain (sometimes).

I don't understand that sentence. 

```
Execution engine call failed            error: ServerMessage { code: -32000, message: "invalid terminal block hash" }, service: exec  
```
This^ is something completely different, it's an error indicating a chain misconfiguration. Might, or might not be related to your peering-problems: nodes use something called forkid to distinguish between peers that are compatible or not. So a misconfig on the forks can lead to peering-problems. 

> I blocked ports 30303/tcp & 30303/udp because when I checked using telnet it was connected but when I opened the telnet port it didn't respond

You blocked the `30303` ports? Then how do you expected them to be able to peer??

And what parameters are you using? What version?
