### ISSUE TITLE
`eth.compile.solidity` fails with solc version 0.3.5

### ISSUE THREAD

**Issue by xavierlepretre** [ethereum/go-ethereum#2703]
#### System information

Geth version: 1.5.0-unstable
OS & Version: Ubuntu Trusty x86_64
Commit hash : 

#### Expected behaviour
In Geth console, when calling `eth.compile.solidity("contract Test{}")` we should see the compiled code.
This is ok with solc version 0.3.4.

#### Actual behaviour
With solc version 0.3.5:
```
solc: exit status 1
Unknown exception during compilation.

    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:22
```

#### Steps to reproduce the behaviour
Launch `geth console`, launch `eth.compile.solidity("contract Test{}")`.

#### Backtrace

````
[backtrace]
````

**Comment by fjl** [comment]
I am fixing this right now but it will take a bit to get the into a release.
You can downgrade solc as a workaround.

**Comment by xavierlepretre** [comment]
I tried downgrading solc but could not. The following commands did not get it down to 0.3.4:

```sh
apt-get remove libethereum solc
apt-get install libethereum=1.2.8-SNAPSHOT--20160612-f169b0d~trusty-0ubuntu1
apt-get install solc=1.2.8-SNAPSHOT--20160612-f169b0d~trusty-0ubuntu1
```

**Comment by AsifPS** [comment]
I'm running into the same issue, is there any way to downgrade solidity compiler properly and get this working?

**Comment by fjl** [comment]
Looking at https://github.com/ethereum/solidity/issues/651, the issue is already fixed upstream. The next solidity release will contain this fix and it will work again. Sorry for the inconvenience.

**Comment by AnthonyAkentiev** [comment]
Got same thing. Waiting for the solution. Thank you!

**Comment by hermanjunge** [comment]
Please @fjl let us know when the new version will be in the ubuntu repository. The repository does not contain the older ones :/

**Comment by mattdf** [comment]
For anyone who wants a temporary workaround, you can clone this repo: https://github.com/mattdf/solidity-static and do a build in docker, then copy the solc file to your install. It makes a statically compiled build of solc so it should work on most distros.

**Comment by kayagoban** [comment]
OSX El capitan seems to not like the docker build.  Any options for me?

**Comment by xavierlepretre** [comment]
@kayagoban It worked like a charm in an Ubuntu VM. Docker on a VM :D

**Comment by hermanjunge** [comment]
Errr, Very late to the party, but I just `apt-get install`'ed `solc` and `0.3.5` is working nice. In case you want to close guys :-)

**Comment by xavierlepretre** [comment]
Works fine with me too:

```sh
$ sudo apt-cache policy solc
solc:
  Installed: 1.2.9-SNAPSHOT--20160629-6a05dd7~wily-0ubuntu1
  Candidate: 1.2.9-SNAPSHOT--20160629-6a05dd7~wily-0ubuntu1
  Version table:
 *** 1.2.9-SNAPSHOT--20160629-6a05dd7~wily-0ubuntu1 0
        500 http://ppa.launchpad.net/ethereum/ethereum-dev/ubuntu/ wily/main amd64 Packages
        500 http://ppa.launchpad.net/ethereum/ethereum/ubuntu/ wily/main amd64 Packages
        100 /var/lib/dpkg/status
$ echo "" | solc
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.3.5-0/RelWithDebInfo-Linux/g++/Interpreter
```
