### ISSUE TITLE
Peer connection lifecycle

### ISSUE THREAD

**Issue by 0x090909** [ethereum/go-ethereum#27034]
Good morning all,

Ive been studying the source code the other night and I want to be sure I understood correctly the peer lifecycle.

1. Peer gets discovered by p2p level protocol. ?? `which handler/file manages that`
2. Peer is ready for protocol handshake and `runEthPeer` is invoked in `eth/handler.go`
3. Peer is connected and local node starts to exchange information with it.
4. is there any other step that I am missing?

I want to calculate statistics for each connected peer and constatly update them as the peer communicates with my node, in order to detect ddos and spam based on custom metrics.

**Comment by fjl** [comment]
> Peer gets discovered by p2p level protocol. ?? which handler/file manages that

This is handled by packages p2p/discover and p2p/dnsdisc. The p2p.Server pulls peer candidate nodes from these systems and attempts to create connections to them.

> is there any other step that I am missing?

Not really.

For your project, you should look mostly into packages eth and eth/protocols/eth.
