### ISSUE TITLE
Drop miner.gastarget

### ISSUE THREAD

**Issue by anhnh131** [ethereum/go-ethereum#27044]
The `miner.gastarget` flag was deprecated from Geth version 1.10.7 and fully removed from version 1.11.0, after post London.
But, if don't apply London hardfork and still want to use Geth v1.11.0, Can change it to another flag?

**Comment by karalabe** [comment]
Geth will always follow the Ethereum roadmap and will gradually sunset things that are not needed any more. Don't rely on features that are not active on mainnet, they will probably go away as fast as we can get rid of them. It's just code that needs maintenance but there's no live usage (so it would bitrot and fail eventually anyway).
