### ISSUE TITLE
[Question] How to determine if specific address is a contract?

### ISSUE THREAD

**Issue by gituser** [ethereum/go-ethereum#2704]
Hi.

Is there any possibility to determine if relevant address is a contract?

We've ran into issue, where sending to particular address fails, because:

* address is a contract address
* we set fixed amount of gas: 21000 
* contract requires more gas at some point.

After sending to that address we got the amount back except gas costs (0.00042 ETH).

What we need is just to check if this address is used as a contract and alert user that sending to that address is not possible. Is there any mechanism for this?

Thanks.

EDIT: nvm, found:
eth.getCode returns byte-compiled code for addresses involved in contracts, for regular addresses it returns just '0x'.

**Comment by yupasik** [comment]
I'm interesting in it too
