### ISSUE TITLE
Peer delivering stale transactions

### ISSUE THREAD

**Issue by extradz** [ethereum/go-ethereum#27042]
After update geth last update,  i have now this error "Peer delivering stale transactions"
spamming my logs.

what can i do ?
`
Apr 03 21:44:00 Ubuntu-2004-focal-64-minimal bash[1192007]: WARN [04-03|21:44:00.589] Peer delivering stale transactions       peer=ce18211edaa7fdc1a4e56c76b08705e7dd992280dcc8f267c391e50211ffe3b7 rejected=117
Apr 03 21:44:01 Ubuntu-2004-focal-64-minimal bash[1192007]: WARN [04-03|21:44:01.080] Peer delivering stale transactions       peer=ce18211edaa7fdc1a4e56c76b08705e7dd992280dcc8f267c391e50211ffe3b7 rejected=124
Apr 03 21:44:01 Ubuntu-2004-focal-64-minimal bash[1192007]: WARN [04-03|21:44:01.294] Peer delivering stale transactions       peer=ce18211edaa7fdc1a4e56c76b08705e7dd992280dcc8f267c391e50211ffe3b7 rejected=115
Apr 03 21:44:01 Ubuntu-2004-focal-64-minimal bash[1192007]: WARN [04-03|21:44:01.368] Peer delivering stale transactions       peer=087fbf32dfb4eb7967f831072049c9de92386deb4c4e708424e2297ea71eda96 rejected=128
Apr 03 21:44:01 Ubuntu-2004-focal-64-minimal bash[1192007]: WARN [04-03|21:44:01.576] Peer delivering stale transactions       peer=596574dd8adfc5a4e8aa0a1bb6fa870fda0ddeb94c774f852f42f80ae17d3ae1 rejected=128
Apr 03 21:44:01 Ubuntu-2004-focal-64-minimal bash[1192007]: WARN [04-03|21:44:01.579] Peer delivering stale transactions       peer=087fbf32dfb4eb7967f831072049c9de92386deb4c4e708424e2297ea71eda96 rejected=126
Apr 03 21:44:01 Ubuntu-2004-focal-64-minimal bash[1192007]: WARN [04-03|21:44:01.648] Peer delivering stale transactions       peer=ce18211edaa7fdc1a4e56c76b08705e7dd992280dcc8f267c391e50211ffe3b7 rejected=124
Apr 03 21:44:01 Ubuntu-2004-focal-64-minimal bash[1192007]: WARN [04-03|21:44:01.796] Peer delivering stale transactions       peer=596574dd8adfc5a4e8aa0a1bb6fa870fda0ddeb94c774f852f42f80ae17d3ae1 rejected=128
Apr 03 21:44:01 Ubuntu-2004-focal-64-minimal bash[1192007]: WARN [04-03|21:44:01.865] Peer delivering stale transactions       peer=ce18211edaa7fdc1a4e56c76b08705e7dd992280dcc8f267c391e50211ffe3b7 rejected=118
Apr 03 21:44:02 Ubuntu-2004-focal-64-minimal bash[1192007]: WARN [04-03|21:44:02.220] Peer delivering stale transactions       peer=ce18211edaa7fdc1a4e56c76b08705e7dd992280dcc8f267c391e50211ffe3b7 rejected=121
Apr 03 21:44:02 Ubuntu-2004-focal-64-minimal bash[1192007]: WARN [04-03|21:44:02.436] Peer delivering stale transactions       peer=ce18211edaa7fdc1a4e56c76b08705e7dd992280dcc8f267c391e50211ffe3b7 rejected=119
Apr 03 21:44:02 Ubuntu-2004-focal-64-minimal bash[1192007]: WARN [04-03|21:44:02.794] Peer delivering stale transactions       peer=ce18211edaa7fdc1a4e56c76b08705e7dd992280dcc8f267c391e50211ffe3b7 rejected=115
Apr 03 21:44:03 Ubuntu-2004-focal-64-minimal bash[1192007]: WARN [04-03|21:44:03.012] Peer delivering stale transactions       peer=ce18211edaa7fdc1a4e56c76b08705e7dd992280dcc8f267c391e50211ffe3b7 rejected=122`

**Comment by holiman** [comment]
I deleted a scam-message. Don't fall for it

**Comment by holiman** [comment]
> After update geth last update, i have now this error "Peer delivering stale transactions"
spamming my logs.

Well, it's usually an indication that either you, or that peer, is not quite synced. It will be fine eventually.
