### ISSUE TITLE
[Docs] sleep method does not exist

### ISSUE THREAD

**Issue by mttkay** [ethereum/go-ethereum#2705]
The wiki documents a `sleep` method as part of the management APIs: https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#sleep

However, using geth 1.4.7, no such method exists:

```
> sleep
ReferenceError: 'sleep' is not defined
    at <anonymous>:1:1
```

**Comment by bas-vk** [comment]
Thx for reporting, I have updated the documentation.
It is now `admin.sleep(nSeconds)`.
