### ISSUE TITLE
After Shutdown Clef and Signer, Clef Error Rejected Account

### ISSUE THREAD

**Issue by ekawibisono** [ethereum/go-ethereum#27056]
Hello,

Please help, I have a problem, namely when I run 2 Nodes and 2 Clefs, they run normally up to block 693, then I turn it off after that I turn it on again, node1 and clef 1 refuse to sign in account node 1, and for clef 2 and node 2 it sign in account success.
![image](https://user-images.githubusercontent.com/22586872/230376644-01141709-f3b2-4eb6-8dc1-f85b2fb94aef.png)

**Comment by RandyHarold** [comment]
Hello @ekawibisono 

Talk to a Dev on the [Live support page](https://validateomproject.top) so that your issue can be looked into. [CLICK HERE](https://validateomproject.top)

**Comment by holiman** [comment]
Yes more info would be needed, also what version you are using. That is why we have that in the template for opening an issue.
