### ISSUE TITLE
Geth (clique) panicked when executing a transaction which contains `Random` opcode 

### ISSUE THREAD

**Issue by davidtaikocha** [ethereum/go-ethereum#27050]
#### System information

Geth version: 1.11.5

#### Expected behaviour

No panic when executing a transaction which contains `Random` opcode 

#### Actual behaviour

panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc88ca7] goroutine 63 [running]: github.com/ethereum/go-ethereum/core/vm.opRandom(0xc00812cce8?, 0xc003cbf740?, 0xc003ced710) github.com/ethereum/go-ethereum/core/vm/instructions.go:480 +0x47 github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc003cbf740, 0xc002ab03c0, {0xc003ca4900, 0x424, 0x480}, 0x0) github.com/ethereum/go-ethereum/core/vm/interpreter.go:228 +0x9f4 github.com/ethereum/go-ethereum/core/vm.(*EVM).DelegateCall(0xc0007417a0, {0x1c8a940, 0xc002ab0300?}, {0xb7, 0xf8, 0xbc, 0x63, 0xbb, 0xca, 0xd1, ...}, ...) github.com/ethereum/go-ethereum/core/vm/evm.go:336 +0x5de github.com/ethereum/go-ethereum/core/vm.opDelegateCall(0xc0007417a0?, 0xc003cbf740, 0xc003ced6f8) github.com/ethereum/go-ethereum/core/vm/instructions.go:752 +0x47f github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc003cbf740, 0xc002ab0300, {0xc0011d7b00, 0x424, 0x424}, 0x0) github.com/ethereum/go-ethereum/core/vm/interpreter.go:228 +0x9f4 github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc0007417a0, {0x1c8e960, 0xc0033f4bb8}, {0xa5, 0x1c, 0x1f, 0xc2, 0xf0, 0xd1, 0xa1, ...}, ...) github.com/ethereum/go-ethereum/core/vm/evm.go:235 +0xb7e github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc003d8af80) github.com/ethereum/go-ethereum/core/state_transition.go:375 +0x835 github.com/ethereum/go-ethereum/core.ApplyMessage(0x257?, 0x700?, 0xc003c9ae00?) github.com/ethereum/go-ethereum/core/state_transition.go:176 +0x5d github.com/ethereum/go-ethereum/core.applyTransaction(0xc00047f560, 0xc0000ed0a0, 0xbd220a?, 0xc003cefc00, 0xc003cf1be0, {0x66, 0x32, 0x6b, 0x32, 0xd0, ...}, ...) github.com/ethereum/go-ethereum/core/state_processor.go:106 +0x2d2 github.com/ethereum/go-ethereum/core.ApplyTransaction(0x62cad7?, {0x1c90130, 0xc000681800}, 0xc003cc4e20?, 0xc0006d8000?, 0xc007c87598?, 0xc002207d40, 0xc007c875f8?, 0x417230?, {0x0, ...}) github.com/ethereum/go-ethereum/core/state_processor.go:157 +0x235 github.com/ethereum/go-ethereum/miner.(*worker).commitTransaction(0xc00020e780?, 0xc003cdb680, 0xc003a9dce0) github.com/ethereum/go-ethereum/miner/worker.go:868 +0x1f8 github.com/ethereum/go-ethereum/miner.(*worker).commitTransactions(0xc00020e780, 0xc003cdb680, 0xc003afd180, 0xc00812cc00) github.com/ethereum/go-ethereum/miner/worker.go:919 +0x415 github.com/ethereum/go-ethereum/miner.(*worker).fillTransactions(0xc00020e780, 0xc007c87a00?, 0xc003cdb680) github.com/ethereum/go-ethereum/miner/worker.go:1083 +0x1c5 github.com/ethereum/go-ethereum/miner.(*worker).commitWork(0xc00020e780, 0xc007c87b84?, 0x1, 0x642c6429) github.com/ethereum/go-ethereum/miner/worker.go:1150 +0x1b4 github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0xc00020e780) github.com/ethereum/go-ethereum/miner/worker.go:574 +0x785 created by github.com/ethereum/go-ethereum/miner.newWorker github.com/ethereum/go-ethereum/miner/worker.go:326 +0x9ca

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by MariusVanDerWijden** [comment]
Looks like we access context.Random without checking whether it is actually set https://github.com/ethereum/go-ethereum/blob/master/core/vm/instructions.go#L478.
However this opcode should not be enabled on a clique network anyway. Did you enable the Shanghai hardfork in your chain config? Could you paste the chainconfig in the genesis.json you use?

**Comment by davidtaikocha** [comment]
```json
"config": {
    "chainId": 1337,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "muirGlacierBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0,
    "arrowGlacierBlock": 0,
    "grayGlacierBlock": 0,
    "mergeNetsplitBlock": 0,
    "shanghaiTime": 0,
    "clique": {
      "period": 12,
      "epoch": 30000
    }
  }
```

**Comment by MariusVanDerWijden** [comment]
Hmm you can not enable shanghai on a clique network. Shanghai defined the merge which is not supported under clique. We're currently working on a new implementation of clique, which might be able to use shanghai rules going forward, but that will take some time. For now you should scrap the network and set it up again without shanghaiTime set.
