### ISSUE TITLE
EncodeRLP of type Receipt not working

### ISSUE THREAD

**Issue by LAMOUR0913** [ethereum/go-ethereum#27062]
#### System information

Geth version: `1.11.5`

I am in the process of redoing the receiptRoot in the block.
Below is my first writing.
```go
                 receiptRLP := new(bytes.Buffer)
		err := receipt.EncodeRLP(receiptRLP)
		if err != nil {
			fmt.Println("err", err)
			return
		}
		keyRLPTemp, _ := rlp.EncodeToBytes(uint(i))
		trie.Update(keyRLPTemp, receiptRLP.Bytes())
```
But I had a problem calculating the receiptRoot, and the results were inconsistent with the expected results.
I know that in the calculation receiptRoot and transactionsRoot, the only difference is that the value updated to trie is different.

I believe my thinking is right, so I try to use the original method to reconstruct receiptRoot.
```go
        hasher := trie.NewStackTrie(nil)
        var receipts []*types.Receipt
	for i := 0; i < block.Transactions().Len(); i++ {
		transactionRLP := new(bytes.Buffer)
		block.Transactions().EncodeIndex(i, transactionRLP)
		receipt, _ := client.TransactionReceipt(context.Background(), crypto.Keccak256Hash(transactionRLP.Bytes()))
		receipts = append(receipts, receipt)
	}
       resultReceipt := types.DeriveSha(types.Receipts(receipts), hasher)
       fmt.Println("resultReceipt", resultReceipt)
```

Very good, the results are in line with expectations.
After searching, my first writing method called method `EncodeRLP` of class `Receipt`. The second writing method calls the`EncodeIndex` method of class `Receipts`. Although the operation is the same, the specific implementation of the method is different.
```go
// Receipts RLP 
// encoding of specific elements in a receipt array
func (rs Receipts) EncodeIndex(i int, w *bytes.Buffer) {
	r := rs[i]
	data := &receiptRLP{r.statusEncoding(), r.CumulativeGasUsed, r.Bloom, r.Logs}
	switch r.Type {
	case LegacyTxType:
		rlp.Encode(w, data)
	case AccessListTxType:
		w.WriteByte(AccessListTxType)
		rlp.Encode(w, data)
	case DynamicFeeTxType:
		w.WriteByte(DynamicFeeTxType)
		rlp.Encode(w, data)
	default:
		// For unsupported types, write nothing. Since this is for
		// DeriveSha, the error will be caught matching the derived hash
		// to the block.
	}
}

// Receipt
func (r *Receipt) EncodeRLP(w io.Writer) error {
	data := &receiptRLP{r.statusEncoding(), r.CumulativeGasUsed, r.Bloom, r.Logs}
	if r.Type == LegacyTxType {
		return rlp.Encode(w, data)
	}
	buf := encodeBufferPool.Get().(*bytes.Buffer)
	defer encodeBufferPool.Put(buf)
	buf.Reset()
	if err := r.encodeTyped(data, buf); err != nil {
		return err
	}
	return rlp.Encode(w, buf.Bytes())
}
```

Obviously, only the processing logic of type `LegacyTxType` is added to the method `EncodeRLP`, so that both are the same operation, but the results are inconsistent.

**Comment by s1na** [comment]
Please use `receipt.MarshalBinary`, this one covers other tx types too. The reason a new method was needed is that tx and receipt encoding of new tx types might not be necessarily simple RLP and is left up to the types to decide.
