### ISSUE TITLE
flag provided but not defined: -bzzaccount

### ISSUE THREAD

**Issue by bo2k3** [ethereum/go-ethereum#2706]
#### System information

Geth version: 1.4.5-stable
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour

geth executes and runs

#### Actual behaviour

geth throws an error that -bzzaccount flag is provided but not defined
#### Steps to reproduce the behaviour

geth --datadir=./tmp/2207/data/02   --identity=02   --bzzaccount=a0cxxxx --bzzport=8602   --port=31102   --unlock=a0cxxxx   --password=<(echo -n 02)   --rpc --rpcport=8202 --rpccorsdomain='*' --networkid 2207 192.168.x.x -mine

#### Backtrace

````
[backtrace]
````
If anyone would know why --bzzaccount throws an error, that would be cool.
Thanks

**Comment by karalabe** [comment]
Swarm is only available on an experimental branch `swarm`. It is not part of neither the stable releases nor the develop releases.

**Comment by bo2k3** [comment]
Ok, thanks for the swift reply. Anything i can do to overcome this issue?
