### ISSUE TITLE
Missing sync committee signature for the block at slot 6160347

### ISSUE THREAD

**Issue by jamescrypto1** [ethereum/go-ethereum#27079]
#### System information

OS & Version: Linux

#### Description 
We have identified a missing sync committee signature for the block at slot 6160347. 

Both our self-written code and the Beaconcha website report the same issue. This could potentially be a bug in the light client code.

#### Expected behaviour

A valid sync committee signature that passes the threashold should be present for the block at slot 6160347.

#### Actual behaviour

The sync committee signature is missing for the block at slot 6160347.

#### Steps to reproduce the behaviour

Visit the block page at https://www.beaconcha.in/slot/6160347
Observe that the sync committee signature is missing
Notice that the sync committee signature is also missing in the fetched data

When submitting logs: please submit them as text and not screenshots.

#### Additional information

Similar problem has been observed on multiple blocks: https://www.beaconcha.in/slot/6160351, https://www.beaconcha.in/slot/6160373, https://www.beaconcha.in/slot/6160417

**Comment by Progy46** [comment]
Based on the information you provided, it seems that there is a missing sync committee signature for the block at slot 6160347. This could potentially be a bug in the light client code.

To fix this issue, you may need to investigate the light client code to determine why the sync committee signature is missing. You can start by reviewing the code that is responsible for collecting and verifying the sync committee signatures, and checking for any potential bugs or errors.

You can also try running the light client code in a test environment and comparing the results to those obtained from the Beaconcha website. This may help you identify any discrepancies or errors in the code that are causing the missing sync committee signatures.

Once you have identified the cause of the issue, you can work on implementing a fix in the light client code. This may involve modifying the code to correctly collect and verify the sync committee signatures, or fixing any bugs or errors that are causing the issue.

It is also important to keep in mind that this issue may not be limited to just the block at slot 6160347, and that similar problems have been observed on multiple blocks. Therefore, it is important to thoroughly test and verify any changes you make to the code to ensure that they fix the issue across all affected blocks.

**Comment by karalabe** [comment]
You'll need to investigate this issue consensus side. Geth is only responsible for the EVM executions post-merge. Also, the Geth light client is non-operable since the merge, so oyu may be referring to something else. Either way, consensus side debug :)

**Comment by jamescrypto1** [comment]
> You'll need to investigate this issue consensus side. Geth is only responsible for the EVM executions post-merge. Also, the Geth light client is non-operable since the merge, so oyu may be referring to something else. Either way, consensus side debug :)

How to contact consensus people in this case?
