### ISSUE TITLE
Include version in exported metrics

### ISSUE THREAD

**Issue by jakubgs** [ethereum/go-ethereum#27088]
# Rationale

Most software that exports metrics, exports also a special metric which provides software version.

Here's an example from [Nimbus Beacon Node](https://github.com/status-im/nimbus-eth2):
```sh
 > curl -s http://localhost:9200/metrics | grep '^version'
version{version="v23.3.2-6c0d75-stateofus",commit="6c0d75"} 1.0
version_created{version="v23.3.2-6c0d75-stateofus",commit="6c0d75"} 1680679179.0
```
This allows for easy tracking of current deployed version as well as version changes over time:

![image](https://user-images.githubusercontent.com/2212681/231417409-e192a1bc-ae15-4048-8d13-abe10318c8ca.png)

# Implementation

An example of how this can be implemented when using `prometheus/client_golang` can be found here:

* https://github.com/prometheus/client_golang/issues/693

**Comment by Progy46** [comment]
That's a great suggestion. Including a metric that provides software version information can be very useful for tracking the current deployed version as well as version changes over time. 

To implement this using `prometheus/client_golang`, you can use the `prometheus.NewBuildInfoCollector()` function to create a new collector for the `_build_info` metric. This collector will automatically gather information about the software version and commit hash, and expose it as a metric that can be scraped by Prometheus.

Here's an example of how you can use this function to create a new collector:

```
import (
    "github.com/prometheus/client_golang/prometheus"
    "github.com/prometheus/client_golang/prometheus/promauto"
)

func main() {
    // Create a new collector for the _build_info metric
    buildInfo := prometheus.NewBuildInfoCollector()
    // Register the collector with the default registry
    prometheus.MustRegister(buildInfo)

    // Your application code here
}
```

Once you have registered the `_build_info` collector, you should be able to see the metric in the Prometheus UI and use it to track the software version over time.

In the context of the code you provided, `prometheus` refers to the `prometheus/client_golang` library, which is a Go client library for Prometheus. This library provides a set of functions and types that make it easy to instrument your Go code and expose metrics to Prometheus.

By using this library, you can create custom metrics, collect data from your application, and expose it to Prometheus for monitoring and alerting. The library provides a simple and intuitive API for creating and registering metrics, and it integrates seamlessly with the Prometheus server.

`Prometheus is a monitoring and alerting toolkit that is widely used in the industry to monitor and collect metrics from various systems. It is an open-source project that provides a powerful query language, a flexible data model, and a web UI for visualizing and alerting on metrics`.

**Comment by jakubgs** [comment]
It does appear that `go-ethereum` does indeed use `client_golang` library:
https://github.com/ethereum/go-ethereum/blob/4a9fa31450d3cdcea84735b68cd5a0a8450473f8/go.mod#L111

So that makes this simpler.

**Comment by holiman** [comment]
Related: https://github.com/ethereum/go-ethereum/pull/24877 

The `NewBuildInfoCollector()` is interesting, but I don't see exactly how that `prometheus.Collector` thingy fits into the pipeline, personally.

**Comment by holiman** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/24877
