### ISSUE TITLE
Does debug_traceBlockByHash need archival mode?

### ISSUE THREAD

**Issue by imnotanoob** [ethereum/go-ethereum#27081]
If we are only tracing very new blocks (< 128 blocks far away), does geth need archival mode?

In general for tracing, does it ever need to go farther than 128 blocks?

**Comment by rjl493456442** [comment]
> If we are only tracing very new blocks (< 128 blocks far away), does geth need archival mode?

Geth will keep the latest 128 blocks by default, so yes archive node is not required.

> In general for tracing, does it ever need to go farther than 128 blocks?

It depends on the requirement. People may want to trace historic blocks to build e.g. chain explorer.
