### ISSUE TITLE
"--bootnodes" option doesn't work (private network)

### ISSUE THREAD

**Issue by wawrzek** [ethereum/go-ethereum#2708]
#### System information

Geth version:  Geth/v1.3.6/linux/go1.5.1
OS & Version: Linux (Ubuntu 14.04)

#### Expected behaviour
Nodes specify in 'bootnodes' are added during geth start

#### Actual behaviour
Nodes are not added.

#### Steps to reproduce the behaviour
I have following command with 2 bootnodes provided, however they are not added to during boot up:

`geth --genesis /geth/seed.json --bootnodes enode://XXX@10.10.10.10:30303 enode:/YYY@10.10.10.100:30303 --rpc --rpcaddr 0.0.0.0 --rpcport 8080 --rpccorsdomain * --ipcpath /geth/geth.ipc --datadir /geth/chain --port 30303 --autodag --networkid  12121212 --metrics --verbosity 5
`

**Comment by wawrzek** [comment]
I've done further investigation. Updated version to latest available in Ubuntu (instance: Geth/v1.4.7-stable/linux/go1.5.1) and bootnodes doesn't understand proper bootnode definition.

I start geth with:

`geth --genesis seed.json --bootnodes enode://3ac93fcb61bab53e35b0319800e23e0b1708856ccf6142f01784e5d13310887dfec2f95f7bb6b50b1fb2cc5bff1b0ebd0ee187c6ca7e8ac2f868b28b95008610@10.0.1.4:30303 enode://b1401f1fa9f0e10bffb59e7632c637827a036707731803a577fb60d45d320bcc0f1077d7043ed90b7ac168ee69a1aa9fbf46a1737bad5786d67260a119be1fa1@10.0.1.5:30303
`


grep for Bootstrap shows:

`I0623 10:12:09.024329 cmd/utils/flags.go:486] Bootstrap URL enode://3ac93fcb61bab53e35b0319800e23e0b1708856ccf6142f01784e5d13310887dfec2f95f7bb6b50b1fb2cc5bff1b0ebd0ee187c6ca7e8ac2f868b28b95008610@10.0.1.4:30303 enode://b1401f1fa9f0e10bffb59e7632c637827a036707731803a577fb60d45d320bcc0f1077d7043ed90b7ac168ee69a1aa9fbf46a1737bad5786d67260a119be1fa1@10.0.1.5:30303: invalid host: too many colons in address 10.0.1.4:30303 enode:`

Seems that geth doesn't understand spaces. In case of one bootnodes I got another error

`I0623 10:23:26.194967 p2p/discover/database.go:183] failed to retrieve node 3ac93fcb61bab53e35b0319800e23e0b1708856ccf6142f01784e5d13310887dfec2f95f7bb6b50b1fb2cc5bff1b0ebd0ee187c6ca7e8ac2f868b28b95008610: leveldb: not found` 

and there is no nodes.

**Comment by karalabe** [comment]
```
$ geth --help | grep bootnodes

  --bootnodes value	Comma separated enode URLs for P2P discovery bootstrap
```

;)

**Comment by wawrzek** [comment]
@karalabe thanks for the response. 

a) That means that documentation is wrong. There is nothing about ',' in here:
https://github.com/ethereum/go-ethereum/wiki/Connecting-to-the-network

b) doesn't explain why bootnets doesn't work when only one node is specify. Second error message about leveldb.

c) adding ',' works only if there is not spaces - that very silly 
`enode://XXX@YYY:ZZZ, enode:/AAA@BBB:CCC` 
doesn't work but 
`enode://XXX@YYY:ZZZ,enode:/AAA@BBB:CCC`
doesn't work in other way. 

There is no peers (so the result is the same as with one node):
`> admin.peers
[]`

**Comment by karalabe** [comment]
a) Thanks, fixed.
b) That's just a debug log that the specific discovery node has never been encountered before.
c) The whole point is to not have space which evaluate to separate arguments/flags and are extremely brittle in scripts with variable expansions.

**Comment by wawrzek** [comment]
Thanks for update. Now, why my node doesn't see any peers? Anything I can find in debug?

**Comment by karalabe** [comment]
@fjl Could you please jump in with a debug log level argument to display logs pertaining to these connectivity issues?

**Comment by wawrzek** [comment]
BTW. I bump verbosity up to 6.

**Comment by wawrzek** [comment]
I wonder if there any relation to issue [2727](https://github.com/ethereum/go-ethereum/issues/2727).

**Comment by wawrzek** [comment]
@karalabe there is another place with not update documentation: https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

**Comment by wawrzek** [comment]
@karalabe Could you add 'Private Network' label please.
@fjl any chance to point what to debug?

**Comment by wawrzek** [comment]
I see '--bootnodes' works in 1.4.11.

**Comment by andrefernandes** [comment]
I know this is closed, but I get the same problem using the ethereum/client-do Docker image. Looks like "--bootnodes" is ignored, and geth version is 1.4.11-stable.

**Comment by tcsekhar** [comment]
Wow, its over a year and I'm having the same issue..

**Comment by xuxiao415** [comment]
today, Geth/v1.7.3-unstable/linux-amd64/go1.9.1 has the same issue.

**Comment by karalabe** [comment]
What doesn't work? We re constantly using this on the Rinkeby testnet and other private network too. It works. Unless you provide any details, there's no way for us to help you.

**Comment by ahester57** [comment]
Maybe each node needs its own unique datadir? I'm not 100% on that but mine have separate datadirs and a proper static-nodes.json in each datadir and they connect to each other fine.

**Comment by holiman** [comment]
There are a lot of things that can go wrong here. Some things to look into are

* Are the ports correctly opened between the docker containers? Can you (e.g. via wireshark) ensure that they can reach eachother? 
* Can you increase the verbosity-level on the second machine? The `debug` loglevel contains a lot of information on the p2p layer.

**Comment by skitzofrenicdev** [comment]
Skitzo

**Comment by Twanaar** [comment]
For info, using static nodes works, 
You can configure permanent static nodes by putting something like the following into <datadir>/geth/static-nodes.json

[
  "enode://f4642fa65af50cfdea8fa7414a5def7bb7991478b768e296f5e4a54e8b995de102e0ceae2e826f293c481b5325f89be6d207b003382e18a8ecba66fbaf6416c0@33.4.2.1:30303",
  "enode://pubkey@ip:port"
]

**Comment by ahester57** [comment]
[Here](https://github.com/ahester57/private-chain) is a collection of scripts for running a private network using go-ethereum. For adding bootnodes, check out the scripts ```get_enodes.sh``` and ```copy_static_nodes.sh```.

They will essentially start and stop each node, grabbing the enode of each and writing them to a file, ```enode/new_static_nodes.json```.

**Comment by Bitmaudit** [comment]
I've this error:
Fatal: Error starting protocol stack: bad bootstrap node "enode://c7c7c4905b29c81a36907937261c2b2523b48e60dbef489ac329aedbc5d19910921f84603d3255621b0928d8262327dff0855ce95f66bb88a2a401d0884d1c80@[::]:30301": invalid IP (multicast/unspecified)

the file Dockerfile was specific another (different enode, the right!):

enode://0df98758a40a58db0ec6c4db14f9241dcf3fec37b0bdb08720de369da0ea1631a3f55717135518a9dea25c8854554f4ccddb33c8d5402130fcbca76fe8d74249@5.189.165.78:30301 

the error report an enode used in yhe past! how do fix?
