### ISSUE TITLE
cmd/devp2p: crawler : same amount of 'removed' and 'ignored(recent)' node when logging

### ISSUE THREAD

**Issue by 0x00Duke** [ethereum/go-ethereum#27090]
#### System information

Geth version: 1.11.5-stable
OS & Version: Windows/Linux/OSX
Commit hash : 2d89ec8fa7acee48aea6096b3dee47f740e595b1

#### Expected behaviour
log the right amount of ignored(recent) nodes

#### Actual behaviour
log the amount of removed node instead

#### Steps to reproduce the behaviour
run the crawler 

#### Backtrace

````
added=22336 updated=191,327 removed=21031 ignored(recent)=21031 ignored(incompatible)=381,541
````

This is caused by the usage of the wrong variable in the code

**Comment by holiman** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/27089
