### ISSUE TITLE
Prysm initial-sync

### ISSUE THREAD

**Issue by Ericalvin** [ethereum/go-ethereum#27093]
Hi, every one,
I run Prysm+Geth on the same host.
Prysm version: use docker latest release
Geth version: v1.11.5

and I found below error:

Geth log say
```
Apr 13 06:25:10 ip-10-218-25-212 geth[1135]: WARN [04-13|06:25:10.690] Served engine_newPayloadV2               reqid=63588   duration="18.83µs"   err="the method engine_newPayloadV2 does not exist/is not available"
Apr 13 06:25:23 ip-10-218-25-212 geth[1135]: WARN [04-13|06:25:23.291] Served engine_newPayloadV2               reqid=63590   duration="15.62µs"   err="the method engine_newPayloadV2 does not exist/is not available"
Apr 13 06:26:08 ip-10-218-25-212 geth[1135]: WARN [04-13|06:26:08.964] Served engine_newPayloadV2               reqid=63594   duration="16.62µs"   err="the method engine_newPayloadV2 does not exist/is not available"
Apr 13 06:26:23 ip-10-218-25-212 geth[1135]: WARN [04-13|06:26:23.278] Served engine_newPayloadV2               reqid=63596   duration="21.19µs"   err="the method engine_newPayloadV2 does not exist/is not available"
Apr 13 06:26:37 ip-10-218-25-212 geth[1135]: WARN [04-13|06:26:37.682] Served engine_newPayloadV2               reqid=63598   duration="13.92µs"   err="the method engine_newPayloadV2 does not exist/is not available"
Apr 13 06:26:51 ip-10-218-25-212 geth[1135]: WARN [04-13|06:26:51.696] Served engine_newPayloadV2               reqid=63600   duration="15.74µs"   err="the method engine_newPayloadV2 does not exist/is not available"
Apr 13 06:27:05 ip-10-218-25-212 geth[1135]: WARN [04-13|06:27:05.482] Served engine_newPayloadV2               reqid=63602   duration="15.7µs"    err="the method engine_newPayloadV2 does not exist/is not available"
Apr 13 06:27:21 ip-10-218-25-212 geth[1135]: WARN [04-13|06:27:21.286] Served engine_newPayloadV2               reqid=63604   duration="21.5µs"    err="the method engine_newPayloadV2 does not exist/is not available"
Apr 13 06:27:34 ip-10-218-25-212 geth[1135]: WARN [04-13|06:27:34.079] Served engine_newPayloadV2               reqid=63606   duration="22.9µs"    err="the method engine_newPayloadV2 does not exist/is not available"
Apr 13 06:27:47 ip-10-218-25-212 geth[1135]: WARN [04-13|06:27:47.177] Served engine_newPayloadV2               reqid=63608   duration="21.56µs"   err="the method engine_newPayloadV2 does not exist/is not available"
Apr 13 06:27:59 ip-10-218-25-212 geth[1135]: WARN [04-13|06:27:59.986] Previously seen beacon client is offline. Please ensure it is operational to follow the chain!

```
Prysm log say:

```
[2023-04-13 03:58:37]  WARN initial-sync: Block is not processed error=could not process block: could not validate new payload: method not found: received an undefined execution engine error
[2023-04-13 03:58:37]  INFO initial-sync: Processing block 0x1ddd3ede... 6209568/6211191 - estimated time remaining 1m21s blocksPerSecond=20.0 peers=40
[2023-04-13 03:58:37]  INFO initial-sync: Processing block 0x92a13e7c... 6209600/6211191 - estimated time remaining 1m14s blocksPerSecond=21.4 peers=40
[2023-04-13 03:58:37]  INFO initial-sync: Processing block 0xdd370f3c... 6209632/6211191 - estimated time remaining 1m8s blocksPerSecond=22.7 peers=40
[2023-04-13 03:58:37]  WARN initial-sync: Range is not processed error=Range had no valid blocks to process
[2023-04-13 03:58:37]  INFO initial-sync: Processing block 0x3ad66142... 6209664/6211191 - estimated time remaining 1m3s blocksPerSecond=24.0 peers=40
[2023-04-13 03:58:37]  INFO initial-sync: Processing block 0x4555def2... 6209696/6211191 - estimated time remaining 58s blocksPerSecond=25.4 peers=40
[2023-04-13 03:58:37]  WARN initial-sync: Range is not processed error=Range had no valid blocks to process
[2023-04-13 03:58:37]  INFO initial-sync: Processing block 0x8f173bf0... 6209760/6211191 - estimated time remaining 51s blocksPerSecond=28.1 peers=40
[2023-04-13 03:58:37]  WARN initial-sync: Range is not processed error=Range had no valid blocks to process

```

how to fix this ? or just waiting for sync finish? thank you.

**Comment by rjl493456442** [comment]
`Apr 13 06:26:51 ip-10-218-25-212 geth[1135]: WARN [04-13|06:26:51.696] Served engine_newPayloadV2               reqid=63600   duration="15.74µs"   err="the method engine_newPayloadV2 does not exist/is not available"
`

Please double check you have upgraded the Geth to the latest version. Looks like it's not without method `engine_newPayloadV2` available.

**Comment by Progy46** [comment]
🌑 It looks like the error is related to a missing method called engine_newPayloadV2. This could be due to a number of reasons, such as a misconfiguration in your Prysm or Geth setup or a bug in the software.

To fix this issue, you can try the following steps:

1. Update your Prysm and Geth versions to the latest releases: Make sure you are using the latest version of Prysm and Geth, as newer versions may have bug fixes or improvements that can help resolve the issue.

2. Check your Prysm and Geth configurations: Ensure that your Prysm and Geth configurations are correct and that they are communicating with each other properly. Check the logs for any errors or warnings related to the configuration.

3. Restart your Prysm and Geth nodes: Sometimes, restarting your Prysm and Geth nodes can help resolve the issue. Try stopping and starting both nodes and see if that helps.

4. Wait for the synchronization to finish: If none of the above steps work, you can try waiting for the synchronization to finish. Sometimes, the issue may resolve itself over time.

If the issue persists, you can try contacting the Prysm or Geth support teams for further assistance. They may be able to provide additional insights or solutions to help you resolve the issue.

**Comment by Hektoreth** [comment]
Ok

**Comment by SubmitCode** [comment]
I have the exact same problem. I am getting the following 

`
Apr 24 11:04:30 deepAI geth[3134]: WARN [04-24|11:04:30.311] Ignoring already known beacon payload    number=17,034,867 hash=26ded6..0aaa56 age=1w4d10h
Apr 24 11:04:30 deepAI geth[3134]: WARN [04-24|11:04:30.338] Ignoring already known beacon payload    number=17,034,868 hash=8514dc..801f63 age=1w4d10h
Apr 24 11:04:30 deepAI geth[3134]: WARN [04-24|11:04:30.345] Ignoring already known beacon payload    number=17,034,869 hash=c2558f..d85d8f age=1w4d10h
Apr 24 11:04:30 deepAI geth[3134]: WARN [04-24|11:04:30.368] Served engine_newPayloadV2               conn=127.0.0.1:42558 reqid=36 duration="18.214µs" err="the method engine_newPayloadV2 does not exist/is not available"
Apr 24 11:04:44 deepAI geth[3134]: WARN [04-24|11:04:44.762] Ignoring already known beacon payload    number=17,034,838 hash=6c3742..d54198 age=1w4d10h
Apr 24 11:04:44 deepAI geth[3134]: WARN [04-24|11:04:44.768] Ignoring already known beacon payload    number=17,034,839 hash=fdd82c..84c887 age=1w4d10h
Apr 24 11:04:44 deepAI geth[3134]: WARN [04-24|11:04:44.780] Ignoring already known beacon payload    number=17,034,840 hash=2eeb7a..c91cd8 age=1w4d10h
Apr 24 11:04:44 deepAI geth[3134]: WARN [04-24|11:04:44.800] Ignoring already known beacon payload    number=17,034,841 hash=f88042..015a59 age=1w4d10h

`


I am working with 
`
Geth
Version: 1.10.25-stable
Git Commit: 69568c554880b3567bace64f8848ff1be27d084d
Architecture: amd64
Go Version: go1.18.5
Operating System: linux
GOPATH=
GOROOT=go
`

`Latest Prysm version is v4.0.3.`

**Comment by holiman** [comment]
I meant original report by @Ericalvin  :)
