### ISSUE TITLE
How to unlock account for sendTransaction?

### ISSUE THREAD

**Issue by aoeng** [ethereum/go-ethereum#27094]
```
Version: 1.11.6-unstable
Architecture: amd64
Go Version: go1.20.3
Operating System: linux
GOPATH=
GOROOT=
```
I use `geth account new --datadir data`  create a account!

I don't know how to unlock my account to trade without restarting geth!Because there is no personal module!

**Comment by 20221100k** [comment]
> 个人命名空间已弃用 （ [#26390 ](https://github.com/ethereum/go-ethereum/pull/26390)）。考虑改用 [Clef ](https://geth.ethereum.org/docs/fundamentals/account-management) 或 [EthSigner ](https://docs.ethsigner.consensys.net)。这些程序可以为您签名 tx 并将其发送给 geth。

how can i get clef ? I already had geth1.11.6 in windows

**Comment by jsvisa** [comment]
@20221100k https://geth.ethereum.org/docs/tools/clef/introduction
