### ISSUE TITLE
Mist Wallet 0.7.5 Connection error

### ISSUE THREAD

**Issue by gfunksound** [ethereum/go-ethereum#2709]
Hi all, I just downloaded the latest wallet 0.7.5, but when I try to open it on mac, it says I have a connection error and that I cannot connect to the network. I get this:

Node type: geth
Network: main
Platform: darwin (Architecure x64)

...I0617 09:21:25.409995 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to /Users/justinwu/Library/Ethereum/chaindata
I0617 09:21:28.667326 ethdb/database.go:169] closed db:/Users/justinwu/Library/Ethereum/chaindata
I0617 09:21:28.768504 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to /Users/justinwu/Library/Ethereum/chaindata
I0617 09:21:29.343207 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /Users/justinwu/Library/Ethereum/dapp

I also used homebrew to update brew and then unlink my old Ethereum 1.4.5 and installed the new Geth 1.4.7 but it still gives this error when opening Mist. 

Any thoughts?
#### System information

Geth version: `geth version`
OS & Version: OSX
Commit hash : (if `develop`)
#### Backtrace

```
[backtrace]
```

**Comment by Samyoul** [comment]
I have this exact error, but for 64bit Windows 7.

### Version 0.7.6

## Error Screenshot

![screenshot 2016-07-02 15 18 41](https://cloud.githubusercontent.com/assets/5702426/16540792/6609b068-4068-11e6-968a-ee1f5fd9d13f.png)

## Log

> =============== Jul 2, 2016 (BST) ===============
14:32:24.746718 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
14:32:24.759719 version@stat F·[] S·0B[] Sc·[]
14:32:24.759719 db@open opening
14:32:24.760719 journal@recovery F·1
14:32:24.761719 journal@recovery recovering @52
14:32:24.764719 version@stat F·[] S·0B[] Sc·[]
14:32:24.769720 db@janitor F·2 G·0
14:32:24.769720 db@open done T·10.0006ms
=============== Jul 2, 2016 (BST) ===============
15:15:15.721319 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
15:15:15.792323 version@stat F·[] S·0B[] Sc·[]
15:15:15.792323 db@open opening
15:15:15.792323 journal@recovery F·1
15:15:15.793323 journal@recovery recovering @54
15:15:15.794323 version@stat F·[] S·0B[] Sc·[]
15:15:15.796323 db@janitor F·2 G·0
15:15:15.796323 db@open done T·4.0002ms

## Steps to Reproduce

Double click Ethereum-Wallet.exe . Error appears when trying to connect to network.

Seems to happen when Mist is unexpectedly terminated, or if the OS unexpected terminates.

**Comment by fjl** [comment]
We can't do anything about this issue because there is no visible error in the message. My guess is that this was a Mist issue.
