### ISSUE TITLE
Error: no suitable peers available

### ISSUE THREAD

**Issue by madhan5447** [ethereum/go-ethereum#27117]
The following error occurs while submitting requests to GetBalance:

Error: getDeleteStateObject (b02a90bcb447736bde2cbca4102d49dc6f727f7b) error: no suitable peers available
	at web3.js:6365:9(45)
	at send (web3.js:5099:62(34))
	at <eval>:1:20(5)

Geth version : Geth/v1.1.23-48aaee69/linux-amd64/go1.19.8

> net.peerCount
142

Please provide a solution for this problem.

**Comment by holiman** [comment]
I know this is a closed issue, but since you reached out to me on Discord I'll comment anyway. 

There is no `1.1.23` release, nor any `48aaee69` commit. 
Well, there is on bsc: https://github.com/bnb-chain/bsc/commit/48aaee69 . 
We (go-ethereum) do not offer support for the BSC chain.
