### ISSUE TITLE
Withdrawals JSON spec discrepancies

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#27129]
This is not solely a geth-bug, but I'll file it here since it's my home turf. 

The withdrawals for EL is specified here: https://ethereum.github.io/execution-apis/api-documentation/ . 
![Screenshot 2023-04-20 at 15-11-39 https __ethereum github io](https://user-images.githubusercontent.com/142290/233448106-93e55515-e22e-45ea-8396-5c41d2ad057a.png)

Notably, 
- all four fields are on `string`-form, 
- and the validator index json-name is `validatorIndex` (camelcased). 

--- 

The go-ethereum definition is here: https://github.com/ethereum/go-ethereum/blame/master/core/types/withdrawal.go#L31

```golang
type Withdrawal struct {
	Index     uint64         `json:"index"`          // monotonically increasing identifier issued by consensus layer
	Validator uint64         `json:"validatorIndex"` // index of validator associated with withdrawal
	Address   common.Address `json:"address"`        // target address for withdrawn ether
	Amount    uint64         `json:"amount"`         // value of withdrawal in Gwei
}
```

Notably: 
- Three of the fields are pure `uint64`. (Turning it into `math.HexOrDecimal64` would make them compliant, I think)

--- 

I don't really know where the CL definition lives. But here's how `prysm`, `lodestar` and `lighthoues` returns them:

```
$ source ~/.headers && curl -H "$HDR1" -H "$HDR2" https://prysm.mainnet.ethpandaops.io/eth/v2/beacon/blocks/head 2>/dev/null | jq ".data .message .body .execution_payload .withdrawals[0]"
{
  "index": "870957",
  "validator_index": "154725",
  "address": "0x09d220b5ea3d69071471d78843d624dfdf49922d",
  "amount": "12063443"
}

[user@work ~]$ source ~/.headers && curl -H "$HDR1" -H "$HDR2" https://lodestar.mainnet.ethpandaops.io/eth/v2/beacon/blocks/head 2>/dev/null | jq ".data .message .body .execution_payload .withdrawals[0]"
{
  "index": "871053",
  "validator_index": "154831",
  "address": "0xd69017b743d5656a31551df7b4c3e2f63709640b",
  "amount": "12021368"
}
[user@work ~]$ source ~/.headers && curl -H "$HDR1" -H "$HDR2" https://lighthouse.mainnet.ethpandaops.io/eth/v2/beacon/blocks/head 2>/dev/null | jq ".data .message .body .execution_payload .withdrawals[0]"
{
  "index": "871101",
  "validator_index": "154879",
  "address": "0x0395da7fec51a54ef0046903d729c06edc70afdf",
  "amount": "12168373"
}

```
Notably, 
- All fields are strings (like the EL spec)
- The validator index is not camel-cased, but `validator_index`. 

-----

Suggestion:

- We (go-ethereum) should change to accept ints on string-form. 
- The EL spec should change `validatorIndex`->`validator_index`
  - We (go-ethereum) and other ELs should apply the change.

cc @MariusVanDerWijden @marioevz

**Comment by siladu** [comment]
I think what you might be suggesting amounts to aligning the engine API and/or eth_ API format with the beacon API format, rather than correcting a single field.

**Comment by holiman** [comment]
I believed that the discrepancy `validator_index` != `validatorIndex` was due to some oversight. I didn't consider that camelcase of "the standard" in EL json-rpc (it is, right?), and vice-versa in CL land. If so, I guess that's a valid reason, though my personal preference would be to break the norm and use `validator_index` in El.

The reason I picked this up, is because I have a little tool called `factor`, which can be used to relay canon-block info from a CL to an EL, using exposed http endpoints. That is, fetching latest block, feed to EL. 

For the conversion, I thus had to define a second `clWithDrawal` type and iterate+convert between the two, just to pass from one to the other. Despite them representing the exact same structure. 

https://github.com/holiman/factor/pull/2/files#diff-fae3e6133490758f44967d974676cc3b0213ea320243223e0e1cbe0f842e7d20R99

----

And the second thing I am saying is that I think go-ethereum erroneously only accepts `int`, not `string-based ints` in e.g. amount.

**Comment by lightclient** [comment]
Right, so it was defined to be camel case despite the CL definition because it is the canonical style of the EL JSON-RPC. We have gone to relatively [great lengths](https://github.com/ethereum/execution-apis/blob/main/src/engine/paris.md#executionpayloadv1) to retain it on the engine API even though many of the fields / objects are also defined in CL objects. Unless there is a very compelling reason to deviate, I think we should retain consistency across the JSON-RPC.

> Three of the fields are pure uint64. (Turning it into math.HexOrDecimal64 would make them compliant, I think)

Are you saying we should use `math.HexOrDecimal64` so that we can support decimal-over-string like the beacon API? We currently have [`withdrawalMarshaling`](https://github.com/ethereum/go-ethereum/blame/master/core/types/withdrawal.go#L39-L43) which uses `hexutil.Uint64` when marshaling to and from  JSON. This is the chosen `uint64` type for all other consensus objects over JSON-RPC.

**Comment by holiman** [comment]
> Are you saying we should use math.HexOrDecimal64 so that we can support decimal-over-string like the beacon API? 


No, so we can support it like the EL spec says -- see image I posted in the top.

**Comment by holiman** [comment]
Ah, sorry my bad. Guess we can close this then. Thanks for the responses!
