### ISSUE TITLE
Is there a tool to convert database to pebble?

### ISSUE THREAD

**Issue by lurais** [ethereum/go-ethereum#27133]
hello , If I want to use the db engine "pebble" , shall I convert the current db to pebble? Or is it ok to change to pebble and continue to use current db?

**Comment by rjl493456442** [comment]
This is no such tool to make the conversion. You have to resync your node from scratch with pebble enabled.
But you can keep the ancient folder, remove others and reuse it by specifying `--datadir.ancient`.

**Comment by holiman** [comment]
I think you don't have to specify the `--datadir.ancient`, just wipe the leveldb `geth ... removedb`, then answer `n` when it asks about deleting ancients. And then restart with pebble as the backend, and it "should just work"

**Comment by lurais** [comment]
> This is no such tool to make the conversion _yet_. You have to resync your node from scratch with pebble enabled. But you can keep the ancient folder, remove others and reuse it by specifying `--datadir.ancient`.

Will that means a lot of time to wait?

**Comment by holiman** [comment]
Yes, sync typically takes 8-24 hours or so

**Comment by lurais** [comment]
> Yes, sync typically takes 8-24 hours or so

Does that means sync the full data only takes 8-24 hours?

**Comment by holiman** [comment]
I don't know what you are asking. If you do a default sync, it typically takes 8-24 hours, in some cases a couple of days, it depends primarily on the speed of your ssd  Having the ancients already saves time and a couple of hundred GB download data.
