### ISSUE TITLE
Request: --refuseToRelay 0xADDRESS and --refuseToRelayOracle 0xADDRESS

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/go-ethereum#2713]
Each node operator should have the ability to refuse to relay transactions or blocks they do not individually wish to relay. This could be for moral, legal, or personal reasons.

--refuseToRelay 0xADDRESS has two effects
1. If a transaction alters the value of 0xADDRESS, it should not be relayed to peers
2. If a block alters the value of 0xADDRESS, it should not be added to the chain, but not relayed to peers
3. After X number of blocks have been added to a block that alters 0xADDRESS (assuming its on the GHOST chain) this refusal to relay expires. In essence, the node accepts its refusal was a failure

--refuseToRelayOracle 0xADDRESS has the same effect as --refuseToRelay, however it watches a smart contract for a list of addresses which would be refused

**Comment by julian1** [comment]
Features like this are a dream for governments and regulators. Courts can be empowered with the power to issue injunctions at miners to censor any transactions they wish.

**Comment by aakilfernandes** [comment]
If its illegal to relay transaction X, its illegal whether or not this flag exists. This does not change the legal burden of node operators in any way.

Any court that has had the right to injunction/censor has had that roght since day 0.
