### ISSUE TITLE
Issue with the debug_traceCall

### ISSUE THREAD

**Issue by kushagra2jindal** [ethereum/go-ethereum#27148]
I am trying to use debug_traceCall using jsonrpc but every time I am getting this issue 
`The method debug_traceCall does not exist/is not available`

I am running GETH in my local with the following command - 
`geth --http.api="eth,net,web3,debug" attach http://localhost:8545/`

And the Ganache is started in 8545 as 
`ganache --miner.blockTime=20 --miner.blockGasLimit=6000000000 --logging.debug=true`

Can you please guide me on what I am doing wrong?

**Comment by s1na** [comment]
That is a Ganache issue. Maybe they don't support `debug_traceCall`? Btw `--http.api` is a no-op when attaching.
