### ISSUE TITLE
How to increase the synchronization speed of archive nodes

### ISSUE THREAD

**Issue by harveyff** [ethereum/go-ethereum#27165]
Hi guys,

Thank you for your great work,

I'm currently syncing the eth mainnet archive node, and I'm wondering how to increase the sync speed, I synced once before and it took about 20 days. How can this speed be accelerated? 

I would be very grateful if you have any helpful advice.

My machine configuration is AWS Ubuntu LTS 20, 32 cores, 128G memory, 32000 IOPS, and sufficient bandwidth.

It runs with k8s.

Run command:

```
   exec geth --datadir=/data --config=/config/geth.toml  --port=30303
              --syncmode=full --gcmode=archive  --snapshot=false --http
              --http.addr=0.0.0.0 --http.port=8545 --http.vhosts=*
              --http.corsdomain=* --ws --ws.addr=0.0.0.0 --ws.port=8546
              --ws.origins=*  --metrics --metrics.addr=0.0.0.0
              --metrics.port=6060 
              --authrpc.jwtsecret="/jwt/node_beacon/jwt.hex" 
              --authrpc.port=8551  --authrpc.vhosts=* --cache=20000
```

**Comment by dreadedhamish** [comment]
> Processing all the blocks and writing all that data takes a very long time.

He has cache set at 20000. Would bumping that up help, or is it diminishing returns after a point?
I came across this issue while investigating ideal cache sizes, but haven't found any good documentation. Is there data around for cache size?
