### ISSUE TITLE
solc crashes without 'export LC_ALL=C'

### ISSUE THREAD

**Issue by AnthonyAkentiev** [ethereum/go-ethereum#2716]
#### System information

Geth version: 1.5.0-unstable
OS & Version: Ubuntu 14.04.4

#### Expected behaviour
Solc must run normally.

#### Actual behaviour
It crashes and generates core file.

#### Steps to reproduce the behaviour

```bash
ubuntu@xxx:~/$ locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
C
C.UTF-8
en_US.utf8
POSIX

ubuntu@xxx:~/$ solc SomeContract.sol
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)
```

Then i added 'export LC_ALL=C' and everything went normally.

**Comment by fjl** [comment]
Please report this at https://github.com/ethereum/solidity
