### ISSUE TITLE
TxPool with invalid pending transactions

### ISSUE THREAD

**Issue by LLDay** [ethereum/go-ethereum#27179]
#### System information

Geth version: 1.10.26-stable
OS & Version: Linux

#### Expected behaviour

Incoming transactions can pass all validation checks in TxPool, but they may not pass `preCheck` stage. These transactions should be removed from TxPool.

#### Actual behaviour

A transaction that has not passed `StateTransition.preCheck` stage, remains pending until it is replaced with another transaction from the same sender or dropped by timeout.

#### Steps to reproduce the behaviour

I started private PoA network, and explicitly added a new test check to the `state_transition.go` file.

```go
func (st *StateTransition) preCheck() error {
    if st.msg.Value().Uint64() == 100 {
        return fmt.Errorf("ERROR")
    }
    ...
}
```

Now all transactions with `value` == 100 are invalid. But TxPool keeps these transactions.

````
> from = "0x01ef19058ea7449853d9dc297237ec5664caeb2e"
"0x01ef19058ea7449853d9dc297237ec5664caeb2e"
> to = "0xffffffffffffffffffffffffffffffffffffffff"
"0xffffffffffffffffffffffffffffffffffffffff"
> web3.eth.sendTransaction({from, to, value: 101, gas: 21000})
"0xfc416c055b02946ccf1adc6cb766d379693f6a871b0cd9a773871e351b53fea3"
> web3.eth.sendTransaction({from, to, value: 101, gas: 21000})
"0xf87c282d0279c182fe36b8521894cc52b1b6f8759656e7661863fc8ff97825ff"
> web3.eth.sendTransaction({from, to, value: 100, gas: 21000})
"0x0832dc24ca954942f5beaf4af843aa77e0301392e37a5b0a42759ae066e91968"
> web3.eth.sendTransaction({from, to, value: 101, gas: 21000})
"0x4e3c5756fe189ff2096e584410851ca812cf62ad27dc7eff83ed3147a88dd843"
> web3.eth.getBalance(to)

202
> web3.eth.pendingTransactions
[{
    accessList: [],
    blockHash: null,
    blockNumber: null,
    chainId: "0xecd3b",
    from: "0x01ef19058ea7449853d9dc297237ec5664caeb2e",
    gas: 21000,
    gasPrice: 2750000000,
    hash: "0x0832dc24ca954942f5beaf4af843aa77e0301392e37a5b0a42759ae066e91968",
    input: "0x",
    maxFeePerGas: 2750000000,
    maxPriorityFeePerGas: 1000000000,
    nonce: 2,
    r: "0x5119ea994fb1ecae6ca7f8896b36d51eaa663cc7e3e00fc2b79963735c89aac5",
    s: "0x3001d41681a2aecf9168c7914651edaa0bdd9c9b530d0b2c5ae5bdf4c58fd97b",
    to: "0xffffffffffffffffffffffffffffffffffffffff",
    transactionIndex: null,
    type: "0x2",
    v: "0x0",
    value: 100
}, {
    accessList: [],
    blockHash: null,
    blockNumber: null,
    chainId: "0xecd3b",
    from: "0x01ef19058ea7449853d9dc297237ec5664caeb2e",
    gas: 21000,
    gasPrice: 2531250000,
    hash: "0x4e3c5756fe189ff2096e584410851ca812cf62ad27dc7eff83ed3147a88dd843",
    input: "0x",
    maxFeePerGas: 2531250000,
    maxPriorityFeePerGas: 1000000000,
    nonce: 3,
    r: "0x930de51913cd4f368ba92f75f63d4d4d8fcfc6e008974ef2b268a711c3c3d618",
    s: "0x41ed5df9e26e856234da0ed0645abc0ed345c94ed7ddc47ac998176a340d7105",
    to: "0xffffffffffffffffffffffffffffffffffffffff",
    transactionIndex: null,
    type: "0x2",
    v: "0x1",
    value: 101
}]
````

**Comment by MariusVanDerWijden** [comment]
Thanks for reporting, however I don't think that transactions should need to pass the `preCheck` to be in the txpool.
The `preCheck` is highly dependent on the current state and current block. The `preCheck` does the following verifications:
- `Nonce` is correct
- `GasFeeCap` and `GasTipCap` are correct
- `BuyGas()` which verifies that the sender has enough gas to pay for the transaction

The txpool already contains checks for the nonce and for the gas, so those checks are duplicated (we need both anyway though). The 1559 checks are highly dependent on the current basefee. If we reject transactions based on that, we might reject transactions that become valid later on.
