### ISSUE TITLE
"Go Contract Bindings" is still wrong

### ISSUE THREAD

**Issue by Adrian-618** [ethereum/go-ethereum#27207]
As mentioned in #3726 , the [tutorial ](https://geth.ethereum.org/docs/developers/dapp-developer/native-bindings#deploying-contracts) is still using 
`	// Create an IPC based RPC connection to a remote node and an authorized transactor
	conn, err := rpc.NewIPCClient("/home/go-ethereum/goerli/geth.ipc")`
which is deprecated. Also there seems to be no clear document mentioning this update 5 years ago.
This should be changed to `conn, err := ethclient.Dial("")`

**Comment by Adrian-618** [comment]
Other things worth noticing:
In both the https://goethereumbook.org/en/ and https://geth.ethereum.org/ (I'm not sure if any of them is unofficial but they are good documents) the transaction signer WITHOUT ChainID is used in code samples, such as the code I mentioned above and [here](https://goethereumbook.org/en/smart-contract-deploy/).

at least in my version,  all these functions are deprecated and will result in error: only replay-protected (EIP-155) transactions allowed over RPC
This can be checked in /go-ethereum/accounts/abi/bind/auth.go
It would be the best to revise the tutorial, so it's easier for new learners (like me) to do the right things :)

**Comment by holiman** [comment]
If you find some concrete errors in geth.ethereum.org re signing (or anything else), feel free to open a ticket or post a PR to fix it. Thanks!
