### ISSUE TITLE
replace the 0x to G1  prefix

### ISSUE THREAD

**Issue by poonam8077** [ethereum/go-ethereum#27203]
hello team 
 i am replace  0x prefix to G1 in go-ethereum code after that create  account and  create genesis file, after that 
run the private node . Checked one by one methods of geth.ipc but i was facing issues in two methods getblock and get blockByNumber.

eth.getBlock(1,true)
{
  difficulty: 2,
  extraData: "0xd883010b02846765746888676f312e32302e31856c696e757800000000000000fd77bd610ab18382481a8466648ecfe0c8aed00ade6002665ed51e0f7f9b6c652f16c6ee9524e677a72300bb704c1d968d117f72e4036afb45c57362504a8e0601",
  gasLimit: 4704588,
  gasUsed: 0,
  hash: "0x8c5bcff9185ec8d3a3e64f559fb6111f0689a6d2f041bae3f0e3986cd0de34da",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 1,
  parentHash: "0xbda31fa6f3ef0e891fd8cea849adf53cec3dfc347ffb19e1f0a192be0b4099d2",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7a

in 0x prefix this method work properly but i replace 0x to G1 it's through error

 G.getBlock(G1,true)
ReferenceError: G1 is not defined
	at <eval>:1:12(3)

> G.getBlock(0)
Error: invalid argument 0: hex string without G1 prefix
	at web3.js:6365:9(45)
	at send (web3.js:5099:62(34))
	at <eval>:1:11(4)

> G.getBlock(0)
Error: invalid argument 0: hex string without G1 prefix
	at web3.js:6365:9(45)
	at send (web3.js:5099:62(34))
	at <eval>:1:11(4)

> G.getBlock(G10,true)
ReferenceError: G10 is not defined
	at <eval>:1:12(3)

> G.getBlock("G10",true)
Error: invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type common.Hash
	at web3.js:6365:9(45)
	at send (web3.js:5099:62(34))
	at <eval>:1:11(5)
Kindly help me to resolve this issue asap
Thanks and regards 
Poonam Singh

**Comment by Rednator** [comment]
> hello team i am replace 0x prefix to G1 in go-ethereum code after that create account and create genesis file, after that run the private node . Checked one by one methods of geth.ipc but i was facing issues in two methods getblock and get blockByNumber.
> 
> eth.getBlock(1,true) { difficulty: 2, extraData: "0xd883010b02846765746888676f312e32302e31856c696e757800000000000000fd77bd610ab18382481a8466648ecfe0c8aed00ade6002665ed51e0f7f9b6c652f16c6ee9524e677a72300bb704c1d968d117f72e4036afb45c57362504a8e0601", gasLimit: 4704588, gasUsed: 0, hash: "0x8c5bcff9185ec8d3a3e64f559fb6111f0689a6d2f041bae3f0e3986cd0de34da", logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", miner: "0x0000000000000000000000000000000000000000", mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000", nonce: "0x0000000000000000", number: 1, parentHash: "0xbda31fa6f3ef0e891fd8cea849adf53cec3dfc347ffb19e1f0a192be0b4099d2", receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", sha3Uncles: "0x1dcc4de8dec75d7a
> 
> in 0x prefix this method work properly but i replace 0x to G1 it's through error
> 
> G.getBlock(G1,true) ReferenceError: G1 is not defined at :1:12(3)
> 
> > G.getBlock(0)
> > Error: invalid argument 0: hex string without G1 prefix
> > at web3.js:6365:9(45)
> > at send (web3.js:5099:62(34))
> > at :1:11(4)
> 
> > G.getBlock(0)
> > Error: invalid argument 0: hex string without G1 prefix
> > at web3.js:6365:9(45)
> > at send (web3.js:5099:62(34))
> > at :1:11(4)
> 
> > G.getBlock(G10,true)
> > ReferenceError: G10 is not defined
> > at :1:12(3)
> 
> > G.getBlock("G10",true)
> > Error: invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type common.Hash
> > at web3.js:6365:9(45)
> > at send (web3.js:5099:62(34))
> > at :1:11(5)
> > Kindly help me to resolve this issue asap
> > Thanks and regards
> > Poonam Singh

Hi @poonam8077 visit the official Ethereum page to initiate a chat with an official agent on a live chat support to report this for review and for further assistance via [Ethereum Support](Helpdeskether.online)

**Comment by karalabe** [comment]
`0x` is not a random prefix, it means hexadecimal in computer world. You cannot replace it.

**Comment by Poonam911** [comment]
> `0x` is not a random prefix, it means hexadecimal in computer world. You cannot replace it.

hello karalabe 
 how to change address prefix in our private blockchain 
kindly help me 
thanks and regards
Poonam Singh
