### ISSUE TITLE
PendingBlockNumber has different values across modules

### ISSUE THREAD

**Issue by georgercarder** [ethereum/go-ethereum#27205]
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

In ethclient toBlockNumArg(rpc.PendingBlockNumber) would return "pending"

#### Actual behaviour

Gives error `err invalid argument 0: hex string without 0x prefix`
this is because in rpc.PendingBlockNumber is -2 rpc.type.go:68
but in ethclient's internal function toBlockNumArg, "pending == -1" ethclient/ethclient.go:588

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by s1na** [comment]
That does look strange on first glance indeed. But it doesn't explain the error you're getting. Which method were you using and what were the parameters when you got that error?

**Comment by georgercarder** [comment]
The method was (ec *Client) FilterLogs
Params:
fromBlock := new(big.Int).SetInt64(rpc.PendingBlockNumber)
toBlock := fromBlock
topic := gthCrypto.Keccak256([]byte("MYEXAMPLETOPIC"))
topics := []common.Hash{common.BytesToHash(topic)}
topicss := [][]common.Hash{topics}

context.Background()
q := FilterQuery{nil, fromBlock, toBlock, nil, topicss}

I'm not too concerned now with debugging my implementation since I got it working by setting 
fromBlock := new(big.Int).SetInt64(-1)
toBlock := fromBlock

but hopefully pointing out that PendingBlockNumber being different across modules will be useful and save others debugging time.

**Comment by willpiam** [comment]
I'm trying to connect to a local node running in dev mode. My truffle tests run but fail on the afterEach hook. Even if my tests are empty. I get the same error message you provided: `  invalid argument 0: hex string without 0x prefix`. I do not get these errors when connected to ganache. Is there a known work around I can take advantage of? Is there some way of configuring the genesis json file?

**Comment by s1na** [comment]
Fixed by #27219. Thanks for reporting!
