### ISSUE TITLE
personal_newAccount does not exist/is not available 

### ISSUE THREAD

**Issue by 362228416** [ethereum/go-ethereum#2723]
```
web3.personal.newAccount('123456', function(e, res){
	console.log(e, res)
});
```
output 
```
The method personal_newAccount does not exist/is not available] undefine
```

**Comment by karalabe** [comment]
Are you running with code from the Geth console or from an external JavaScript environment? If you connect an external environment to Geth via the HTTP-RPC interface, by default the `personal` namespace is not available due to security considerations.

**Comment by 362228416** [comment]
How to start ?

**Comment by 362228416** [comment]
I need use rpc call newAccount 、 sendTransaction .. api , how to ?

**Comment by 362228416** [comment]
It is done.

**Comment by omkarkhair** [comment]
Can you please elaborate on how this was done?

**Comment by karalabe** [comment]
If you want to use the `personal` namespace, either do if from the Geth console or attach to Geth via an IPC connection that's assumed to be secure. Anything else is irresponsible :P

**Comment by geek96** [comment]
Run your node with `--rpc ` and ` --rpcapi personal,web3` flags.

i.e. `geth --dev --rpcapi personal,web3,eth `

You may need to add `--rpccorsdomain "<your-domain>"`, in case you are using web3 in the web.

`geth --dev --rpcapi personal,web3,eth --rpccorsdomain "your-domain"`

**Comment by mclrk** [comment]
I want to have two computers: 1 that hosts my web application and 1 that hosts my GETH node.  Is there a safe way to have the web app make rpc calls to the geth node?  I want the web app to have accesss to the "personal" api.

**Comment by 362228416** [comment]
@mclrk  Limit network access, use firewall to restrict IP, or nginx reverse proxy, and configure HTTP basic

**Comment by junnyxi** [comment]
after startup， there is a brief： 
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 shh:1.0 txpool:1.0 web3:1.0

so，the command will be：
 ./geth --rpc --rpcport 19910 --rpcapi personal,web3,eth,net --datadir testNet --dev console 2>> test.log

**Comment by agiratech-guru** [comment]
@junnyxi  how to get some Faucet coins for that address
