### ISSUE TITLE
How to fork the mainnet programmatically and perform simulated transaction on forked state

### ISSUE THREAD

**Issue by Thankgod20** [ethereum/go-ethereum#27234]
I am having a hard time figuring out how to temporarily fork the mainnet state and perform a simulated transaction with it 

      import (
	      "context"
	      "fmt"
	      "log"
	      "math/big"
	      "github.com/ethereum/go-ethereum/accounts/abi/bind"
	      "github.com/ethereum/go-ethereum/accounts/abi/bind/backends"
	      "github.com/ethereum/go-ethereum/common"
	      "github.com/ethereum/go-ethereum/core"
	      "github.com/ethereum/go-ethereum/core/types"
	      "github.com/ethereum/go-ethereum/crypto" )

     func main() {
	  privateKey, err := crypto.GenerateKey()
	  if err != nil {
		  log.Fatal(err)
	}

	auth := bind.NewKeyedTransactor(privateKey)

	balance := new(big.Int)
	balance.SetString("10000000000000000000", 10) // 10 eth in wei

	address := auth.From
	genesisAlloc := map[common.Address]core.GenesisAccount{
		address: {
			Balance: balance,
		},
	}
	//clz, err := ethclient.Dial("https://mainnet.infura.io/v3/<your-project-id>")
	if err != nil {
		fmt.Printf("Error connecting to Ethereum node: %v\n", err)
		return
	}

	blockGasLimit := uint64(4712388)
	client := backends.NewSimulatedBackend(genesisAlloc, blockGasLimit)

	fromAddress := auth.From
	nonce, err := client.PendingNonceAt(context.Background(), fromAddress)
	if err != nil {
		log.Fatal(err)
	}

	value := big.NewInt(1000000000000000000) // in wei (1 eth)
	gasLimit := uint64(21000)                // in units
	gasPrice, err := client.SuggestGasPrice(context.Background())
	if err != nil {
		log.Fatal(err)
	}

	toAddress := common.HexToAddress("0x4592d8f8d7b001e72cb26a73e4fa1806a51ac79d")
	var data []byte
	tx := types.NewTransaction(nonce, toAddress, value, gasLimit, gasPrice, data)
	signedTx, err := types.SignTx(tx, types.HomesteadSigner{}, privateKey)
	if err != nil {
		log.Fatal(err)
	}

	err = client.SendTransaction(context.Background(), signedTx)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("tx sent: %s\n", signedTx.Hash().Hex()) // tx sent: 0xec3ceb05642c61d33fa6c951b54080d1953ac8227be81e7b5e4e2cfed69eeb51

	client.Commit()

	receipt, err := client.TransactionReceipt(context.Background(), signedTx.Hash())
	if err != nil {
		log.Fatal(err)
	}
	if receipt == nil {
		log.Fatal("receipt is nil. Forgot to commit?")
	}

	fmt.Printf("status: %v\n", receipt.Status) // status: 1
}
`

Any guidance will be appriciated

**Comment by lightclient** [comment]
If you want to perform a single call against mainnet state, you can simply use the `eth_call` JSON-RPC and it will execute the call against the state.

**Comment by karalabe** [comment]
There's no way in Geth to fork off of an existing state in memory and keep operating on it. You can execute calls against the current / recent state as Matt mentioned, and you can also optionally override some state slots/accounts if that helps debugging. But there is no way to fork off and operate on it onwards.
