### ISSUE TITLE
goroutine leak in console_test.go

### ISSUE THREAD

**Issue by hhheiaenia** [ethereum/go-ethereum#27247]
I got some leak information in my IDE when running TestInteractive(), is this due to missing cleanup  some errors when handling branch.
![image](https://github.com/ethereum/go-ethereum/assets/133205928/87610f0e-1a92-4f96-82e6-7bde4e816388)

**Comment by fjl** [comment]
These goroutines are the 'global' worker pool for transaction signature verification. There is no mechanism to shut them down, but only up to GOMAXPROCS goroutines of this type will be created.
