### ISSUE TITLE
Why most recent block always zero?

### ISSUE THREAD

**Issue by prajnastra** [ethereum/go-ethereum#27242]
I am trying to run a evm based chain. But the most recent block is always zero and also it is not syncing. 
![screenshot-20230510-124149Z-selected](https://github.com/ethereum/go-ethereum/assets/55863324/2fdd15bf-ed4a-4680-a714-add1a52b0169)

**Comment by holiman** [comment]
What consensus engine are you using?

**Comment by prajnastra** [comment]
I have checked using geth console and it is showing false

**Comment by karalabe** [comment]
Without showing us logs at to what your node is doing we cannot guess.
