### ISSUE TITLE
  How long will kzg be able to complete open source

### ISSUE THREAD

**Issue by big-dreamer-png** [ethereum/go-ethereum#27259]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

**Comment by rjl493456442** [comment]
What do you mean by `complete open source`? There are a couple of open-sourced kzg implementations.

In terms of `complete`, do you mean when these libraries will be used by ethereum client?
