### ISSUE TITLE
init geth t8n kzg on demand only

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#27258]
# Rationale

With recent kzg introduction some kzg logic gets initiated with each t8n call that significantly reduce the performance on all the tests that doesn't need it

# Implementation

Investigate if it's possible to run kzg startup logic in t8n only on those tests that request it. (Ex. 4844 tests)

**Comment by karalabe** [comment]
This is fixed on master

**Comment by karalabe** [comment]
I mean it was never broken on master AFAIK, only for --ckzg

**Comment by winsvega** [comment]
yes running the tests with geth t8n now 6000 seconds vs 2500 previously
