### ISSUE TITLE
SubscribeFullPendingTransactions fails to unmarshal txs to Transaction type

### ISSUE THREAD

**Issue by popfendi** [ethereum/go-ethereum#27267]
#### System information

Geth version: `v1.11.6`
OS & Version: Linux

#### Expected behaviour
Pending transactions would be streamed to channel as *types.Transaction

#### Actual behaviour
json unmarshal error

#### Steps to reproduce the behaviour
I tried this with an alchemy node & and a local ganache environment, both produced the same result.
here's my code:

```
var mempool chan *types.Transaction = make(chan *types.Transaction)
var c *ethclient.Client

func main() {
	rpcClient, rpcErr := rpc.Dial("ws://localhost:8545")

	if rpcErr != nil {
		panic(rpcErr)
	}

	c = ethclient.NewClient(rpcClient)
	subToMempool(gethclient.New(rpcClient))
}

func subToMempool(client *gethclient.Client) {

	sub, err := client.SubscribeFullPendingTransactions(context.Background(), mempool)
	if err != nil {
		//log error
		return
	}

	fmt.Println("subbed", sub)

	for {
		select {
		case err := <-sub.Err():
			fmt.Println(err)
		case tx := <-mempool:
			fmt.Println(tx.Hash().Hex())
		}
	}

}
```

#### Backtrace

````
json: cannot unmarshal string into Go value of type types.txJSON
````

When submitting logs: please submit them as text and not screenshots.

**Comment by s1na** [comment]
I'm guessing alchemy and ganache don't support this recent feature. It should work on a local geth node.

**Comment by popfendi** [comment]
this sounds about right, I'll have to find a workaround for now. Thanks for the help.

**Comment by tarik0** [comment]
The error happens because of this line;

```
var mempool chan *types.Transaction = make(chan *types.Transaction)
```

It should be an `*common.Hash` channel not `*types.Transaction`. This is not a bug, just a silly error

**Comment by s1na** [comment]
FYI there are 2 methods. `SubscribePendingTransactions` which indeed only returns the tx hashes. And then there is `SubscribeFullPendingTransactions` which should return whole transaction object `*types.Transaction`. You are subscribing to full transactions in the script you shared above. So I still believe the provider has not implemented this feature. If you only need hashes might as well use the `SubscribePendingTransactions` method, at least there will be no surprise in the future.
