### ISSUE TITLE
about the TrieCleanCacheRejournal and the config.toml

### ISSUE THREAD

**Issue by shiziwen** [ethereum/go-ethereum#27278]
Hi,
what is the TrieCleanCacheRejournal mean? and what is the default value?

Is there any example of config.toml for the best practice?

I have run some geth nodes and didn't use the config.toml, but I find I also can use it to run the nodes, so is there any example and explanation of the config?

**Comment by rjl493456442** [comment]
Geth has this mechanism to dump out clean trie nodes cache with a specific interval.  The dumped out file can be used to fast-warm cache in next restart, and the default interval is 1 hour.

It's the tutorial about using config file in geth https://geth.ethereum.org/docs/fundamentals/config-files
