### ISSUE TITLE
setDecoded should not allow negative number for the tx value

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#27275]
When `NewTx` allows creating a TX with e negative value this causes a panic in the `FinalizeAndAssemble` 

```
panic: rlp: cannot encode negative big.Int
```

To replicate
Create a TX with a negative value to a new account
The TX will pass all checks
A new account will be created with a negative balance

The change
```

// NewTx creates a new transaction.
func NewTx(inner TxData) *Transaction {
	tx := new(Transaction)
	tx.setDecoded(inner.copy(), 0)
	return tx
}


// setDecoded sets the inner transaction and size after decoding.
func (tx *Transaction) setDecoded(inner TxData, size uint64) {
	if inner.value().Sign() < 0 {
		panic("transaction value cannot be negative")
	}
	tx.inner = inner
	tx.time = time.Now()
	if size > 0 {
		tx.size.Store(size)
	}
}
```

**Comment by karalabe** [comment]
Why would you create a negative transaction?

RLP cannot represent negative numbers so anything arriving over the network will surely be positive, the RPC should also check that values are not negative.

I mean, sure, you can construct an invalid transaction from Go code, but why would you do that and why should we handle deliberately bad code?

**Comment by karalabe** [comment]
We don't really believe in defensive programming where every single method validates every parameter. The process boundary (network, file system, etc) are the places where you need to ensure that data validity checks are done, but after you're inside the program, the invariants should hold.

**Comment by lthibault** [comment]
@karalabe We're hitting this issue as well.  Your point about having a clearly-delineated validation boundary makes sense, but is this specific failure case actually checked somewhere?  It seems to be slipping through existing validation measures.

**Comment by MariusVanDerWijden** [comment]
How are you hitting this case? Transactions over the wire and over rpc should not be able to have negative numbers for the txvalue? Do you have a link to how you are using `NewTx`?

**Comment by lthibault** [comment]
@MariusVanDerWijden To be exact:  we are encountering a panic in `(s *StateDB) updateStateObject`.  My best (albeit unconfirmed) guess is that an incoming transaction occasionally has a negative value that isn't caught by the validation pipeline.

I'll keep you appraised of our investigation, of course.
