### ISSUE TITLE
Node flag to turn off transaction overdraft protection

### ISSUE THREAD

**Issue by evanzbitgo** [ethereum/go-ethereum#27274]
# Rationale
The introduction of transaction overdraft protection has created challenges in certain automated transaction broadcasting scenarios, including my company. Our process involves generating a significant number of transactions and submitting them to our internal node's txpool. Our approach is to keep all pending transactions in the txpool, even if the fee address doesn't have enough balance, as we can add funds to the fee address later if needed. We encounter situations where we need to replace a pending transaction with a lower nonce. However, the overdraft protection feature initially rejects these replacement transactions, leading to manual intervention to resolve the issues.

Why should this feature exist?
For users with in-house nodes, they could have the flexibility to turn off this specific protection.

What are the use-cases?
See above

# Implementation

Do you have ideas regarding the implementation of this feature?
Adding a node config flag
Are you willing to implement this feature?
Yes

**Comment by Georgezhang714** [comment]
> # Rationale
> The introduction of transaction overdraft protection has created challenges in certain automated transaction broadcasting scenarios, including my company. Our process involves generating a significant number of transactions and submitting them to our internal node's txpool. Our approach is to keep all pending transactions in the txpool, even if the fee address doesn't have enough balance, as we can add funds to the fee address later if needed. We encounter situations where we need to replace a pending transaction with a lower nonce. However, the overdraft protection feature initially rejects these replacement transactions, leading to manual intervention to resolve the issues.
> 
> Why should this feature exist? For users with in-house nodes, they could have the flexibility to turn off this specific protection.
> 
> What are the use-cases? See above
> 
> # Implementation
> Do you have ideas regarding the implementation of this feature? Adding a node config flag Are you willing to implement this feature? Yes

Feature

**Comment by holiman** [comment]
It is hard for us to evaluate proposals in text-form. If you have a ready PR, it's easier to look at the code and judge if the maintenance overhead is worth it. 

In this specific case, I would _guess_ that we would not accept it. The usecase sounds very niche, and our main focus is maintaining an ethereum mainnet clients. At times, we accept modifications for non-ethereum-mainnet downstream usecases though, if they are elegant and/or minimal enough. 

I'll close this ticket, feel free to open a PR with the proposed changes (but yeah, don't hope too much :) )
