### ISSUE TITLE
why the static reward of 15537393 is zero?

### ISSUE THREAD

**Issue by shiziwen** [ethereum/go-ethereum#27280]
Hi, the post merge is from 15537394, but why the static reward of 15537393 is zero?

For the 15537393, the total difficulty is 58750003716598352816469 which is larger than 58_750_000_000_000_000_000_000 which is defined as the Terminal Total Difficulty for mainnet.

And according to the codes as below, from 15537394, will be treated as the post merge.

```
// IsTTDReached checks if the TotalTerminalDifficulty has been surpassed on the `parentHash` block.
// It depends on the parentHash already being stored in the database.
// If the parentHash is not stored in the database a UnknownAncestor error is returned.
func IsTTDReached(chain consensus.ChainHeaderReader, parentHash common.Hash, parentNumber uint64) (bool, error) {
	if chain.Config().TerminalTotalDifficulty == nil {
		return false, nil
	}
	td := chain.GetTd(parentHash, parentNumber)
	if td == nil {
		return false, consensus.ErrUnknownAncestor
	}
	return td.Cmp(chain.Config().TerminalTotalDifficulty) >= 0, nil
}
```

But why the static reward of 15537393 is 0?
<img width="1117" alt="image" src="https://github.com/ethereum/go-ethereum/assets/1405245/f429ad2b-70a1-42f2-994c-96ec7b1a54f8">

**Comment by lightclient** [comment]
The reason is that `IsTTDReached` is used more to determine what the difficulty / nonce of the block should be, where `isPoSHeader` is used to determine if the general PoS logic should be applied. The first block that passes `isPoSHeader` is considered the `TRANSITION_BLOCK` per EIP-3675 and must not pay the standard block reward.

You can see it used here during `Finalize`: https://github.com/ethereum/go-ethereum/blob/d46f69dc7a71e0f203a197064ed556a6f283d9e4/consensus/beacon/consensus.go#L339

**Comment by shiziwen** [comment]
@lightclient  Thanks for your reply.

But I think differently with you.
I think for the block 15537393, there also exists 2 eth as the mining reward.
And there is a bug for the etherscan.

I have get the balance for the miner 0x829bd824b016326a401d083b33d092293333a830.
for block  15537392, its balance is 0x3da14b0b9deb906a78, which is 1136873784532532226680L.
for block  15537393, its balance is 0x3f6023464bf1ceef3b, which is 1169072334587521068859L.

balance_delta: 32198550054988842179L.

And in the block 15537393，Transfer 30.198550054898867892 ETH From 0x76d312...A08a222D To F2Pool Old(0x829bd824b016326a401d083b33d092293333a830).

So, the reward of the miner is 32198550054988842179 / 1000000000000000000.0 - 30.198550054898867892
= 2.000000000089976, which includes the static reward(2ETH) + tx_fee_reward.

So, for the block 15537393, there also has 2ETH reward as the PoW static reward.
