### ISSUE TITLE
Unable to Sync Full Node

### ISSUE THREAD

**Issue by AusIV** [ethereum/go-ethereum#27307]
#### System information

Geth
Version: 1.11.6-stable
Git Commit: ea9e62ca3db5c33aa7438ebf39c189afd53c6bf8
Git Commit Date: 20230420
Architecture: arm64
Go Version: go1.20.3
Operating System: linux
GOPATH=
GOROOT=

#### Expected behaviour

I'm running

```
geth --datadir=/var/lib/ethereum/geth/ --snapshot=false --syncmode=full --gcmode=archive
```
along with lighthouse:

```
sudo ./lighthouse bn --network=sepolia --execution-jwt=/var/lib/ethereum/geth/geth/jwtsecret --execution-endpoint=http://localhost:8551
```

Expecting to make a Sepolia archive node.

#### Actual behaviour

Instead, I get a bunch of messages like:

> WARN [05-19|19:02:46.315] Forkchoice requested unknown head        hash=844162..defe31

But I'm still on block 0 with no forward progress. I have peers, including other nodes of my own that I know to be synced, but I never get a "Block synchronization started" message or anything else to indicate that block processing is taking place.

**Comment by rjl493456442** [comment]
`--network=sepolia` for beacon and `mainnet` for geth

**Comment by AusIV** [comment]
Sorry, I inadvertently left out the `--sepolia` flag in my Geth command line parameters, but even if it is there, it will not sync.
