### ISSUE TITLE
Missing Trie Node errors during upgrade from 1.11.5 to 1.11.6

### ISSUE THREAD

**Issue by quickchase** [ethereum/go-ethereum#27300]
We have observed that during upgrades from 1.11.5 to 1.11.6 the nodes seem to incur some sort of state gap where, after they are restarted on the new version, they will start to throw `missing trie node` errors for requests to recent, but not latest, block numbers (i.e. 50-70 blocks behind the tip).

I have never before experienced this issue when upgrading geth nodes, but during the rollout of the update for Goerli, Sepolia, and Mainnet we have seen this behavior for 1.11.6 across many many nodes in our infrastructure.

The nodes are still leveldb, if that helps.

**Comment by karalabe** [comment]
Hmmm, I'm unsure if this is an issue.

Geth keeps trie nodes for the latest 128 blocks in RAM. On shutdown, three states are flushed (HEAD, HEAD-1 and HEAD-128), the rest discarded. On startup, you will as such not have the states for anything else apart from these 3. Then you start applying blocks on top, and will gradually end up having state for everything once you process 128 blocks.

If your update/restart lasts less than the time it takes to produce 128 blocks, then upon restart you will run the new blocks (say 80) leading to have the state for those, but for 80->128, you will have gaps until another 48 blocks are produced by the network.

Is this perhaps what you are seeing?

**Comment by quickchase** [comment]
Yeah, that sounds like it might be the problem we are facing here. Will have to think of a way to not serve traffic for ~128 blocks after startup.
