### ISSUE TITLE
panic: internal error: can't find reason for requirement on github.com/hashicorp/golang-lru@v0.5.4

### ISSUE THREAD

**Issue by acashmoney** [ethereum/go-ethereum#27316]
#### System information

Geth version: `1.10.19-stable`
Go Version: `go1.20.4`
Operating System: `darwin`
Architecture: `arm64`
GOPATH: `Not Set`
GOROOT: `go`

#### Expected behaviour

Expected to download all the dependencies and packages for `go-ethereum` using the command `go get -d github.com/ethereum/go-ethereum/...`.

#### Actual behaviour

Received a panic error during module resolution. The error is related to the module `github.com/hashicorp/golang-lru@v0.5.4`.

```
panic: internal error: can't find reason for requirement on github.com/hashicorp/golang-lru@v0.5.4

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0x140011c01a0, 0x1f}, {0x140000291a6, 0x6}})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0xc4
cmd/go/internal/modget.(*resolver).updateBuildList(0x14000282000, {0x105419498, 0x140000280d0}, {0x0, 0x0, 0x0})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x41c
cmd/go/internal/modget.(*resolver).applyUpgrades(0x14000282000, {0x105419498, 0x140000280d0}, {0x0?, 0x0, 0x10572bde0?})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1312 +0x31c
cmd/go/internal/modget.runGet({0x105419498, 0x140000280d0}, 0x1400002a5a0?, {0x1400001e0b0, 0x1, 0x1})
	/usr/local/go/src/cmd/go/internal/modget/get.go:351 +0x3c8
main.invoke(0x10571e3c0, {0x1400001e090, 0x3, 0x3})
	/usr/local/go/src/cmd/go/main.go:225 +0x37c
main.main()
	/usr/local/go/src/cmd/go/main.go:179 +0x7cc
```

#### Steps to reproduce the behaviour

1. Ensure Go version is `1.20.4` and Geth version is `1.10.19-stable`.
2. Run the command `go get -d github.com/ethereum/go-ethereum/...`.
3. Observe the panic error.

**Comment by karalabe** [comment]
That Geth version is a year old. I'm unsure what the issue might be, perhaps on arm64 some library was missing? Either way really, we can't go back and debug old releases, so please use the latest.

That said, this issue originates from Go internally, and it's not a simple error with something not being found rather some strange internal error (panic), so something it very wrong with your setup in the first place. Perhaps make sure your internet connection is stable and itsn't timing out on go get operations. If it persists - and happens with latest Geth - yoiu'll probably need to open an upstream issue in Go.
