### ISSUE TITLE
Windows Geth Requires UPnP turned on, but AlethZero and Mac connect fine on same network

### ISSUE THREAD

**Issue by NickBenedict** [ethereum/go-ethereum#2732]
When I run Geth from CLI on mac and when I run AlethZero the network connects and I'm able to download the blockchain, but when I run geth from windows CLI I get the following error:

Starting Server
nat.go:349] Listening on [::]:30303
nat.go:94] network port 30303 could not be mapped : no UPnP or NAT-PMP router discovered
cmd.go53] Shutting Down ....

This seems odd as odd as the pc can connect to the eth network to get blockchain using AlethZero but no from the CLI.

Thanks,
Nick

**Comment by karalabe** [comment]
This is strange. Shouldn't quite just because UPnP doesn't find such a router. It should still continue NATed. What Geth version are you using? Perhaps try with `--nat=none`?

**Comment by NickBenedict** [comment]
Thanks for the reply.

That helped in that geth no longer throws an error, but the blockchain doesn't start downloading.

Geth-Win-64-20150508152915-0.9.17-60--c8fc4ce is the download that I'm using.

**Comment by fjl** [comment]
Whoa, that's a really old release (from May of last year!). Please upgrade to [Geth 1.4.8](https://github.com/ethereum/go-ethereum/releases).

**Comment by NickBenedict** [comment]
Thanks, not sure where i ended up grabbing that one from.  I'll get the latest and retry.

**Comment by NickBenedict** [comment]
Yup, that did it.  One of _THOSE_ moments. 

Thanks Again!
