### ISSUE TITLE
How to run private Blockchain Geth test with two different machines Like Server and Client.

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#27342]
Hello,

I successfully tested the CVC-Testnet on two local machines using static nodes having Static IP addresses. 

However, I'm facing connectivity issues while configuring the second node on the AWS Ubuntu machine from my local Ubuntu machine.

Despite reviewing the configuration, checking ports, and ensuring firewall rules, I haven't resolved the issue. 

Your guidance and suggestions would be greatly appreciated.

**Comment by q9f** [comment]
Have you checked the networking section on the docs here: https://geth.ethereum.org/docs/fundamentals/private-network

Specifically, setting an external IP for the ENR? `--nat extip:172.16.254.4`

**Comment by holiman** [comment]
> However, I'm facing connectivity issues while configuring the second node on the AWS Ubuntu machine from my local Ubuntu machine.

It would make sense to include details about your connectivity issues in this ticket, if you want help. 

> Despite reviewing the configuration, checking ports, and ensuring firewall rules, I haven't resolved the issue.

Similarly, please add the configuration + command line parameters on the ticket. 


Without information, there's not much anyone can do to help you.

**Comment by lightclient** [comment]
Closing as there has been no additional information provided by OP.
