### ISSUE TITLE
eth/tracers: output only logs event with logTracer

### ISSUE THREAD

**Issue by tiennampham23** [ethereum/go-ethereum#27341]
# Rationale

Why should this feature exist?
Currently, we have `callTracer` with the option `withLog`. The result is the call frames with the logs inside each frame. Now I want to get the only logs, I need to recursive the result of the tracer and get the logs. It's not necessary.

What are the use-cases?

# Implementation
I want to create a new tracer named by `logTracer` to get the event logs. Maybe it will be duplicated some code with `callTracer` but the result is different.

The output looks like:
```json
[
  {
    "address": "0x350e0ffc780a6a75b44cc52e1ff9092870668945",
    "topics": [
      "0xcacb62d8acea4678658eb5dc4aaa889b34d893b967c96a5f8c066e6549fa3f42"
    ],
    "data": "0x000000000000000000000000000000000000000000000000000000000000034100000000000000000000000000000000000000000000000000000000000000390000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003fcb0342353c541e210013aaddc2e740b9a33d08fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefefe0000000000000000000000000000000000000000000000000011c37937e08000"
  },
  {
    "address": "0x350e0ffc780a6a75b44cc52e1ff9092870668945",
    "topics": [
      "0xcacb62d8acea4678658eb5dc4aaa889b34d893b967c96a5f8c066e6549fa3f42"
    ],
    "data": "0x00000000000000000000000000000000000000000000000000000000000002ff00000000000000000000000000000000000000000000000000000000000000360000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003fcb0342353c541e210013aaddc2e740b9a33d08fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdfdfd0000000000000000000000000000000000000000000000000011c37937e08000"
  }
]
```

Do you have ideas regarding the implementation of this feature?
I only need to get the logs events instead of the all call frames.
Are you willing to implement this feature?
Yes

**Comment by tiennampham23** [comment]
@holiman @s1na PTAL

**Comment by tiennampham23** [comment]
@s1na No, I want to get only the logs with a tracer. And `callTracer` with `withLog` params return to me a recursive call with the logs inside each call frame.

I don't need the call frames and only need the logs. And I don't care which call frame emitted that event.

**Comment by s1na** [comment]
@tiennampham23 Aah I see, you are using `debug_traceCall` to get the logs when simulating a transaction, not when tracing a mined transaction. Is that right?

It should be easy to write a custom `logTracer` for yourself. Have a look at this documentation: https://geth.ethereum.org/docs/developers/evm-tracing/custom-tracer#custom-go-tracing. I'm happy to answer any questions.

The reason I would be against merging this upstream is that we're planning to add `eth_multicall` soon which is like `eth_call` but also returns the logs (and more).

**Comment by tiennampham23** [comment]
For `debug_traceTransaction` return the full call frames with the logs when I passed the `withLog` params. And I need to recursive the call frames to get the logs inside it.

I want to return full the flattened logs in the response body.

**Comment by tiennampham23** [comment]
@s1na yes, thank you. I can create a custom trace, but I need to run the node by myself to use it. I want to merge it into this source by default to use with some node providers.

**Comment by tiennampham23** [comment]
@s1na yes I am using `debug_traceTransaction` to trace my transaction and get the logs from it.
