### ISSUE TITLE
I want to address the Enode issue where the address changes dynamically when running geth

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#27359]
I explored a solution involving the boot node but encountered unexpected results.
Recognized the importance of a stable Enode configuration as a unique identifier for the Geth node.
Can Anyone help me to modify the Enode configuration within the geth code to achieve the desired stability?
To set it statis Enode.

**Comment by AsadullahSoomro** [comment]
Yes, I want static enode can suggest me

**Comment by AsadullahSoomro** [comment]
@lightclient,  
Yes, I want static enode can suggest to me

**Comment by lightclient** [comment]
Please [generate a node key](https://geth.ethereum.org/docs/tools/devp2p) and use `--nodekey` flag.

**Comment by AsadullahSoomro** [comment]
I want static enode I am trying to fix the Enode because whenever we are running geth it will change Enode address dynamically

**Comment by AsadullahSoomro** [comment]
Every time it is changing when I run node
