### ISSUE TITLE
Keep generating new blocks, even without transaction.

### ISSUE THREAD

**Issue by Haider-Ali-DS** [ethereum/go-ethereum#27354]
Hey, i want my geth node to keep generating blocks when without any new transactions, maybe empty blocks just to keep number going.

i used following command to run geth.

`geth --dev`

**Comment by q9f** [comment]
If pedantic block times and empty blocks are important, you can run a Clique network with a single validator:

https://geth.ethereum.org/docs/fundamentals/private-network
