### ISSUE TITLE
local geth --dev network with shanghai evm support

### ISSUE THREAD

**Issue by q9f** [ethereum/go-ethereum#27365]
# Rationale

Why should this feature exist?
* Tooling expects a Shanghai EVM target
* Mainnet and all testnets feature a Shanghai EVM target
* However, the local devnets based on Clique/Ethash cannot easily support Shanghai

What are the use-cases?
* Run code and test applications targeting Shanghai on a local devnet
* Use Geth to run tests targeting Shanghai in CI

# Implementation

Do you have ideas regarding the implementation of this feature?
* Either create a FakeShanghai config that does not include withdrawals that can be applied to non-beacon consensus engine
* Or create a FakeBeacon consensus that allows us to run a local devnet with beacon consensus (and Shanghai)

Are you willing to implement this feature?
* Honestly, I think this would be a good first issue. Not sure, I'm the one though! 😊 
* ref  #27360

**Comment by s1na** [comment]
Jared is working on a dev mode that is post-merge and uses the engine API #27327 for block building.

**Comment by antazoey** [comment]
ah ok, I believe I am also hitting this... I am getting invalid opcode PUSH0 when I compile with shanghai (using vyper)

**Comment by q9f** [comment]
> ah ok, I believe I am also hitting this... I am getting invalid opcode PUSH0 when I compile with shanghai (using vyper)

Yes, exactly.

**Comment by holiman** [comment]
Done, with https://github.com/ethereum/go-ethereum/pull/27327

**Comment by antazoey** [comment]
Is there a way to have this work when not using the `--dev` option (like for custom dev networks)?

**Comment by s1na** [comment]
@antazoey In your place I'd look at [Kurtosis](https://docs.kurtosis.com). They make it easy to spin up PoS testnets.

**Comment by rmlearney-digicatapult** [comment]
@s1na What if our network needs to be PoA?

**Comment by antazoey** [comment]
I am having better luck these days with PoA... The thing I was missing was setting `"shanghaiTime": 0` in my genesis config.
