### ISSUE TITLE
`evm blocktest` does not seem to output traces when `--debug` or `--json` are passed

### ISSUE THREAD

**Issue by d-xo** [ethereum/go-ethereum#27363]
#### System information

Geth version: 1.11.6-stable
OS & Version: Linux

#### Expected behaviour

If I run `evm --json statetest` and pass a state test json, then `evm` will output per opcode traces, however running `evm --json blocktest` outputs nothing. The same is true when using `--debug` instead of `--json`. I would expect to be able to get json traces for both state and blockchain tests.

#### Actual behaviour

`evm --json blocktest <FILE>` and `evm --debug blocktest <FILE>` output nothing

#### Steps to reproduce the behaviour

`evm --json blocktest <TEST_FILE>`

**Comment by holiman** [comment]
```
[user@work go-ethereum]$ evm --json statetest  ./foo.txt
invalid character '\x1b' looking for beginning of value
[user@work go-ethereum]$ evm --json blocktest ./foo.txt
No help topic for 'blocktest'
```
There is no `blocktest` command. If you pass a blockchain test json to the `statetest` command, it will probably parse a statetest which is mostly empty, so no state transition to perform and no output to show.

**Comment by d-xo** [comment]
There has been an `evm blocktest` since 1.11.0 I believe? https://github.com/ethereum/go-ethereum/pull/26526.

Certainly it is present in the go-ethereum 1.11.6 I have installed locally:

```
> evm blocktest --help
NAME:
   evm blocktest - executes the given blockchain tests

USAGE:
   evm blocktest [command options] <file>

OPTIONS:

    --help, -h                     (default: false)
          show help
```

**Comment by holiman** [comment]
Oh, maybe I tested with some old version. Will recheck/reopen!
