### ISSUE TITLE
Why do nodes often hang up when using the poa private chain built by geth?

### ISSUE THREAD

**Issue by Ten163** [ethereum/go-ethereum#27375]
geth
Version: `1.11.6-stable`
```
Linux iZwz97in5tf7l9wjfmrhffZ 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
4 cores 8g memory
```
./geth --networkid 61002 --cache 4096 --nodiscover --syncmode full --maxpeers 300  --allow-insecure-unlock --unlock 0 --password password.txt --miner.etherbase 0x22eee1c10ab2a20fa2b24dbcfdcb3d00eea26ed8 --mine
```
Is there something wrong with the commands I enabled? Often when the network is running, only a certain node will hang up.
Thank you so much.

**Comment by holiman** [comment]
I suppose most of the nodes you find are mainnet nodes, and  you have `networkid 61002`. They are not compatible with you, and will hang up. Is that not what you expect?

**Comment by karalabe** [comment]
What does "hang up" mean? I'm not entire clear what you're seeing.

**Comment by Ten163** [comment]
> I suppose most of the nodes you find are mainnet nodes, and you have `networkid 61002`. They are not compatible with you, and will hang up. Is that not what you expect?

Yes, my own private chain network id is 61002, and there are 3 verification nodes on the private chain network, but when the transaction volume is sent to the node, the memory of the node will continue to increase, which will eventually lead to oom. At startup, I've added --cache 4096, but it doesn't seem to have any effect!

**Comment by Ten163** [comment]
> What does "hang up" mean? I'm not entire clear what you're seeing.

As the node receives more transactions, the memory of the node will continue to increase, eventually leading to oom

**Comment by Ten163** [comment]
And, when the node is killed, the node will fall behind a lot of blocks, because I use --syncmode full synchronization, so it seems very slow, about 1 second to synchronize a block. Is this normal?

The latest block is around 249,220

Node restarted after being killed log ：

INFO [06-02|15:46:33.770] Imported new chain segment               number=215,008 hash=361b09..e36b11 blocks=12   txs=851 mgas=223.730 elapsed=8.397s      mgasps=26.642 age=3d23h1m  dirty=510.68MiB
INFO [06-02|15:46:42.154] Imported new chain segment               number=215,020 hash=8d815f..322aa6 blocks=12   txs=872 mgas=229.258 elapsed=8.383s      mgasps=27.345 age=3d22h59m dirty=510.60MiB
INFO [06-02|15:46:50.783] Imported new chain segment               number=215,030 hash=67a5c0..c0bbfd blocks=10   txs=768 mgas=201.908 elapsed=8.628s      mgasps=23.399 age=3d22h57m dirty=510.60MiB
INFO [06-02|15:46:58.948] Imported new chain segment               number=215,040 hash=8a7f54..fae5f7 blocks=10   txs=747 mgas=203.921 elapsed=8.165s      mgasps=24.975 age=3d22h56m dirty=510.72MiB
INFO [06-02|15:47:07.055] Imported new chain segment               number=215,051 hash=e87aae..e5595a blocks=11   txs=812 mgas=217.210 elapsed=8.107s      mgasps=26.791 age=3d22h54m dirty=510.56MiB
INFO [06-02|15:47:15.463] Imported new chain segment               number=215,062 hash=934679..f4f8c5 blocks=11   txs=781 mgas=217.180 elapsed=8.407s      mgasps=25.832 age=3d22h52m dirty=510.36MiB
INFO [06-02|15:47:23.753] Imported new chain segment               number=215,073 hash=209ac9..c23f3e blocks=11   txs=801 mgas=224.932 elapsed=8.289s      mgasps=27.133 age=3d22h51m dirty=511.04MiB
INFO [06-02|15:47:32.122] Imported new chain segment               number=215,084 hash=d32100..fe0a7c blocks=11   txs=757 mgas=213.443 elapsed=8.369s      mgasps=25.504 age=3d22h49m dirty=510.61MiB
INFO [06-02|15:47:40.701] Imported new chain segment               number=215,095 hash=7b3783..a362d9 blocks=11   txs=822 mgas=231.211 elapsed=8.579s      mgasps=26.950 age=3d22h47m dirty=510.56MiB

**Comment by holiman** [comment]
An OOM crash should ideally print out a stacktrace, which may (or may not) show what the culprit is. 
Alternatively, you might need to use the `--metrics` and chart out the system metrics, such as number of goroutines and stuff, so we can see more what happens memory-wise.

**Comment by holiman** [comment]
Seems abandoned
