### ISSUE TITLE
Out of memory: Killed process (geth)

### ISSUE THREAD

**Issue by soouCc** [ethereum/go-ethereum#27378]
#### System information

Geth version: `1.11.6`
lighthouse
OS & Version: Linux

Memory: 16gb

./geth --mainnet  
--datadir "/data/eth/ethereum" 
--http --http.api="eth,net,engine,admin,txpool,web3" 
--http.corsdomain=* 
--http.addr="0.0.0.0" 
--http.vhosts=* 
 --ws  
--ws.addr="0.0.0.0"   
--ws.api="eth,net,engine,admin,txpool,web3" 
--ws.origins=*

geth has been running normally for some time, and the supervisor used to start geth has often gone Out of memory in the past few weeks

![image](https://github.com/ethereum/go-ethereum/assets/26320031/6d22e7e0-acd1-4708-8bee-baa2eaa24059)
Out of memory: Killed process 448883 (geth) total-vm:12671280kB, anon-rss:8240552kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:19660kB oom_score_adj:0

**Comment by holiman** [comment]
`12671280kB` ~  `12671MB` ~ `12.6GB`. That's not extreme, if you do indeed have`16Gb`. Are you also running lighthouse  or some other 'heavy' process on the same machine?

**Comment by soouCc** [comment]
> `12671280kB` ~ `12671MB` ~ `12.6GB`. That's not extreme, if you do indeed have`16Gb`. Are you also running lighthouse or some other 'heavy' process on the same machine?

total_vm      rss pgtables_bytes swapents oom_score_adj name
7031574  1361206 44621824        0             0 lighthouse
3167820  2060138 20131840        0             0 geth

Yes,  There is lighthouse running, which is also taking up a lot of memory

**Comment by soouCc** [comment]
Is there any way to reduce the memory, otherwise, always out of memory。

**Comment by holiman** [comment]
> Is there any way to reduce the memory, otherwise, always out of memory。

Theoretically, you can specify `--cache` to try to set it lower, but running both geth and lighthouse mainnet on `16GB` ram is probably going to be problematic.

**Comment by holiman** [comment]
If you want to run a proper producton system, you should increase your ram. You could also try e.g. Nimbus CL client, which supposedly is a bit more light on RAM.
