### ISSUE TITLE
Bad block finding efficiency from v1.4.6 and above.

### ISSUE THREAD

**Issue by miningpoolhub** [ethereum/go-ethereum#2737]
#### System information

Geth version: v1.4.6 ~ v1.4.8
OS & Version: Linux Ubuntu 64 14.04.4 LTS
Commit hash : 98be7cd (from master)
#### Expected behaviour

Pool have to find block efficiently.
#### Actual behaviour

Inefficient than before.
#### Steps to reproduce the behaviour

Just run wallets above v1.4.5 and mine.
v1.4.5 works fine. v1.4.6 and above results really bad luck of finding block.

I'm running a pool. miningpoolhub.com
About 1~2% of total share, more than 100 blocks are found from our pool daily.
I hesitated to submit this issue because it is hard to reproduce, hard to simulate, hard to prove also.

Ethereum with v1.4.5 ran fine, but from v1.4.6, block finding luck(efficiency) dropped more than 10%. I believe it's related to some changes about network sync which is included in v1.4.6
I tried v1.4.6 several times before, v1.4.8 again few hours ago and found that something really affects bad luck everytime I try. This doesn't seem to be just normal bad luck, but I can see significant changes.

I still can't prove the issue. I see fine logs, fine wallet working. Overall pool statistics is the only thing I can judge the efficiency.
Do you have any idea about this?

**Comment by 9600-** [comment]
Operating four geographically distributed ETH pools on different circuits across all. 
Am having constant GETH crashes 24 hours after activating the soft fork voting. 

It's been a hassle to keep things running. 
See #2747 for more info and trace.

**Comment by clintar** [comment]
Can you maybe run some testnet tests with both versions to see if there is anything there?
