### ISSUE TITLE
Authenticated API call question, invalid signature.

### ISSUE THREAD

**Issue by 0xJungleMonkey** [ethereum/go-ethereum#27380]
Hello, I am trying to make an authenticated api call. 
This is my command to run geth : 
``` bash
geth --http --http.api eth,net,engine,admin --authrpc.jwtsecret /Path/to/jwt.hex
```
But I still can do API calls without the JWT secert on port 8545 
However on port 8551, even I used the right JWT secret and payload to generate the JWTtoken,  node is running, still get 401 unauthorized error because of invalid signature. 
Can anybody help explain what is happening?

**Comment by karalabe** [comment]
Port 8545 is not authenticated, the authrpc does not affect it.

Wrt 8551, can't really say what you're doing wrong. We have 5 execution clients and 4 consensus clients that can cross talk correctly using the JWT mechanism, so you must be missing something somewhere. Can't really say without any code or logs or errors or nothing.

**Comment by holiman** [comment]
Re JWT, are you trying to communicate with the 8551 interface _yourself_ , or are you having problems making your CL client communicate with it?

**Comment by karalabe** [comment]
If you are using a beacon client, they should just work as long as you point both the consensus and execution client to the same JWT secret file. For outside/direct calls, @jwasinger will post an example - hopefully.

**Comment by jwasinger** [comment]
@0xJungleMonkey this is an example which uses `curl` to invoke an engine API method: https://github.com/jwasinger/geth-jwt-example
