### ISSUE TITLE
potential data race in p2p/dial.go

### ISSUE THREAD

**Issue by lobottt** [ethereum/go-ethereum#27388]
It seems to be a potential data race. Specifically, there are two conflicting operations on the field "dest", where the read operation at: p2p/dail.go:413, and the write operation at: p2p/dail.go:517 A data race may occur when the two functions where the two operations are located are called in parallel.

**Comment by fjl** [comment]
This is a known issue, see here: https://github.com/ethereum/go-ethereum/issues/23430
