### ISSUE TITLE
--db.backend isn't supported

### ISSUE THREAD

**Issue by Neozaru** [ethereum/go-ethereum#27390]
#### System information

Geth version: v.1.12.0 (compiled locally)
OS & Version: Debian 10
Commit hash : (if `develop`)

#### Expected behaviour
`--db.backend` option to force `geth` to use `leveldb` or `pebble`

#### Actual behaviour
`flag provided but not defined: -db.backend`

#### Steps to reproduce the behaviour
Add `--db.backend leveldb` or `--db.backend pebble` to command

**Context:**
I have been running `geth` for month in this "emergency" machine. I always compile locally. I fetched `v1.12.0` and `make geth`. Now I want to switch to `pebble` DB to know what the state size and ancient size will be with this new DB system.
I used
`geth removedb`
Then removed `.ethereum` folder completely to start from a fresh sync.
Then tried to use `--db.backend pebble` to make sure `geth` will use the new DB system (which is the point of removing all my state).

Goals of opening this issue:
1. Report the inconsistent behavior vs. what is documented at https://github.com/ethereum/go-ethereum/releases/tag/v1.12.0
2. Finding a way to switch my locally compiled `geth` to `pebble` and finding a way to ensure that my current state is using `pebble` and not `leveldb`.

Thanks in advance.

**Comment by Neozaru** [comment]
Looking twice I can see that `db.engine` and not `db.backend` can be used: (https://github.com/karalabe/go-ethereum/blob/ba9cdf2257a3edfe7799d0eb7f53835c48faace5/cmd/utils/flags.go#L102-L107)

So I guess the "bug" is only in the release notes.

That solves (1).

**Comment by karalabe** [comment]
Sorry, will fix the release notes. Thanks for calling out!

**Comment by karalabe** [comment]
Updated
