### ISSUE TITLE
Should struct `diffLayer`  be exposed？

### ISSUE THREAD

**Issue by joohhnnn** [ethereum/go-ethereum#27399]
I would like to discuss the possibility of exposing the difflayer to allow external querying of the differences between specific blocks. This feature would enable me to quickly identify the exact data changes made in each block. Additionally, it would eliminate the need to use the `NewStateSync()` _(core/state/sync.go)_ method to iterate through my own trie when synchronizing snapshots, thereby achieving faster synchronization.

I believe that exposing the difflayer would provide significant benefits in terms of efficiency and data analysis. It would greatly enhance the ability to track and understand the modifications made in each block.

**Implementation**
Are you willing to implement this feature?
yes

**Comment by karalabe** [comment]
diffLayer is a very internal part of snapshots and we really don't want to provide an API to it. Currently the snapshot tree ensures thread safety and everything and I don't want to think about another entry point. Also Gary's doing a lot of overhauls around this part of the code, so perhaps we should wait until that's in and then reconsider?

**Comment by joohhnnn** [comment]
> diffLayer is a very internal part of snapshots and we really don't want to provide an API to it. Currently the snapshot tree ensures thread safety and everything and I don't want to think about another entry point. Also Gary's doing a lot of overhauls around this part of the code, so perhaps we should wait until that's in and then reconsider?

sure thing
