### ISSUE TITLE
[website]: Move website code to new repository

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/go-ethereum#27403]
It might be good to move the website code out of `go-ethereum/website` and into a separate repository.

## The problem

The rationale is that it would better support open source contributions from the community. Under the current arrangement, builds fail for PRs from any forked copy of the repository. The same issue affects preview deploys, which fail for PRs from forks, making community contributions hard to review. 

## The solution

1) Move the website code out of `go-ethereum/website` and into a separate repo. There is already a repository, `geth-website` that was used for early website development under the Ethereum project space that we could use.

2) Swap the repo over in Netlify.

3) Update contribution guideline on the website and the `go-ethereum` README to direct contributors to the new repo.

4) Archive or delete the `website` branch in `go-ethereum` if you want to.

## The downside

Website issues and PRs will be in a separate board to the Geth source code. Probably some users will continue to use the -go-ethereum` boards for website issues for a while.

**Comment by holiman** [comment]
This has been approved, we don't need to keep it open. IF/when the website folks wants to move it, go ahead :)
