### ISSUE TITLE
What does "trie_memcache_commit_nodes" exactly mean?

### ISSUE THREAD

**Issue by Aracki** [ethereum/go-ethereum#27408]
I have two nodes running in different clouds. When I compare their `trie_memcache_clean_hit` I see that:

* First node is having baseline of ~3-4k writes per second
* Second one having baseline of ~80-100k writes per second

Both nodes have exactly the same configuration. I couldn't find documentation on what this metric represent, so I can better understanding how this difference is even possible?

**Comment by rjl493456442** [comment]
`trie_memcache_clean_hit ` metric means the number of trie nodes be flushed into disk per second.

**Comment by rjl493456442** [comment]
Can you provide some logs from the second node? Feel like it's generating snapshot. 
Or `State in memory for too long, committing` like this.

**Comment by Aracki** [comment]
Yes, it seems the node with bigger baseline having "Generating state snapshot" logs all the time.

**Comment by rjl493456442** [comment]
Close it now. Feel free to reopen if the number is still not correct after generation.
