### ISSUE TITLE
rpc call eth_blocknumber out of sync

### ISSUE THREAD

**Issue by pedrobranco** [ethereum/go-ethereum#2741]
#### System information

Geth version: Geth
Version: 1.4.5-stable-a269a713
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: linux

When I receive a block notification (via filter polling) I've called eth_getTransactionByHash ( web3.js getTransaction() ) for each transaction hash.
In the middle I call eth_blockNumber ( web3.js [getBlockNumber()](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethblocknumber) ) to calculate the confirmations number.

Here's the pseudo-code:
```javascript
web3.eth = Promise.promisifyAll(web3.eth);

const tx = yield web3.eth.getTransactionAsync('0x123');

let confirmations  = 0;

if (tx.blockNumber !== null) {
  const blockNumber = yield web3.eth.getBlockNumberAsync();
  confirmations  = blockNumber - tx.blockNumber + 1;
}
```
#### Expected behaviour
The variable **confirmations** is greater or equal than 0 for every confirmed transaction. 

#### Actual behaviour
The variable **confirmations** in some point returns **-1**. 
Maybe eth_blocknumber call is out of sync?

#### Steps to reproduce the behaviour
I can't reproduce this problem, it just happens sometimes.

#### Backtrace
Not available.

**Comment by bas-vk** [comment]
Due to chain reorganisations transactions can end up in different blocks then the first time you retrieve the block number. In rare cases the block number of the canonical chain can actually decrease.

**Comment by pedrobranco** [comment]
@bas-vk Thanks for the help. 
Makes sense that we should have a confirmations number in the JSON response of getTransactionByHash? Or there's a reason not to have?

**Comment by bas-vk** [comment]
You mean the response of `eth_getTransactionByHash` should return a confirmation count?

I don't think this is good idea since it can give a false sense of accuracy. The fundamental problem remains, if you call this methods 2 times the results may vary. The longer you wait the more (relative) accurate the confirmation count will be.

**Comment by pedrobranco** [comment]
@bas-vk Thanks for the explanation. I'm closing this issue.
