### ISSUE TITLE
Caller gas above allowance, capping  

### ISSUE THREAD

**Issue by imranmehdi5511** [ethereum/go-ethereum#27433]
#### System information
Ubuntu Desktop 23.04 AMD

Geth version: `geth version`
Geth
Version: 1.11.6-stable
Git Commit: ea9e62ca3db5c33aa7438ebf39c189afd53c6bf8
Architecture: amd64
Go Version: go1.20.3
Operating System: linux
GOPATH=
GOROOT=

CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
private blockchain
OS & Version: Linux Ubuntu 23.04

Commit hash : (if `develop`)

#### Expected behaviour
Transaction goes through
#### Actual behaviour
Gas exceeded error

#### Steps to reproduce the behaviour
running private blockchain and doing dummy transaction after mining

#### Backtrace
clef accepts the transaction, geth gives error cap exceeded when it comes to transaction
````
[backtrace]
````
Private blockchain

When submitting logs: please submit them as text and not screenshots.

Logs:

Geth:
```
WARN [06-07|16:12:54.948] Caller gas above allowance, capping      requested=2,485,875,683 cap=50,000,000
INFO [06-07|16:13:04.268] Submitted transaction                    hash=0x50f0d826baa539e2a985dbe1989aa31e6b5db41c6d2f4f1a9a85e392cbed277a from=0x21963Cce0BEDDe7706062B2b2128EADB26e33C4A nonce=3 recipient=0x58E444396F5b4267cB385B3eD75310B38051eB92 value=1

```
Clef:
```
Additional HTTP header data, provided by the external caller:
	User-Agent: ""
	Origin: ""
-------------------------------------------
Approve? [y/N]:
> y
## Account password

Please enter the password for account 0x21963Cce0BEDDe7706062B2b2128EADB26e33C4A
> 
-----------------------
Transaction signed:
 {
    "type": "0x0",
    "nonce": "0x3",
    "gasPrice": "0x3b9aca00",
    "maxPriorityFeePerGas": null,
    "maxFeePerGas": null,
    "gas": "0x5208",
    "value": "0x1",
    "input": "0x",
    "v": "0x3d8d",
    "r": "0x4de46caf052ba3d2ba323a43fab0f5964a245d7a7598d8ba4ae2b6d4a6346a88",
    "s": "0x34bac7c6c0c6ff6ee3d43c204911c0d4fdaa3fc511a315d7717678c290c8c657",
    "to": "0x58e444396f5b4267cb385b3ed75310b38051eb92",
    "hash": "0x50f0d826baa539e2a985dbe1989aa31e6b5db41c6d2f4f1a9a85e392cbed277a"
  }
```

**Comment by holiman** [comment]
The message about exceeds gas cap is because someone (you?) is trying to do an eth_call using `2,4` Billion gas, over RPC. A call with that amount of gas can be a denial-of-service, so the RPC limits it to 50M. I don't think it's related to the transaction there.

**Comment by imranmehdi5511** [comment]
Also getting this error Failed to open wallet                    url=extapi:///home/imran/etherpriva..      err="operation not supported on external signers"

**Comment by imranmehdi5511** [comment]
I am trying to start clef with private blockchain but get this error

**Comment by holiman** [comment]
You are getting some warnings and error-messages in the log output. 

Aside from that, what is the problem? Like, are transactions that you submit not being included in blocks?

**Comment by imranmehdi5511** [comment]
yes they are not being updated, like i sent some fake ether from account a to account b but the account balance didnt change and i get this error.

**Comment by imranmehdi5511** [comment]
> The message about exceeds gas cap is because someone (you?) is trying to do an eth_call using `2,4` Billion gas, over RPC. A call with that amount of gas can be a denial-of-service, so the RPC limits it to 50M. I don't think it's related to the transaction there.

so how do i make the call with lower gas?

**Comment by imranmehdi5511** [comment]
set the gas by setting it in the command or it will go to maximum, you can set it to even 1,

eth.sendTransaction({from:'0x21963cce0bedde7706062b2b2128eadb26e33c4a', to:'0x58e444396f5b4267cb385b3ed75310b38051eb92', value: web3.toWei(0.05, "ether"), gas:21000});

After that mine for new blocks.

Once the transaction is added and new block is generated,

Stop the mining and get the transaction receipt

eth.getTransactionReceipt("0xd1224ae09517a5f8760d5337e6de98fe437fced94041e5e5b3c8577adabb4f60")
{
  blockHash: "0x8e3871b6dabdc5d4b8294d02f2de3834dc459aeecb27e316e29ea772653b319d",
  blockNumber: 423,
  contractAddress: null,
  cumulativeGasUsed: 189000,
  effectiveGasPrice: 1000000000,
  from: "0x21963cce0bedde7706062b2b2128eadb26e33c4a",
  gasUsed: 21000,
  logs: [],
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  status: "0x1",
  to: "0x58e444396f5b4267cb385b3ed75310b38051eb92",
  transactionHash: "0xd1224ae09517a5f8760d5337e6de98fe437fced94041e5e5b3c8577adabb4f60",
  transactionIndex: 8,
  type: "0x0"
}
> 


Problem solved.
