### ISSUE TITLE
Cannot connect to localhost:8551 for geth private blockchain[BUG]

### ISSUE THREAD

**Issue by imranmehdi5511** [ethereum/go-ethereum#27437]
#### System information
Ubuntu Desktop 23.04
Geth version: `geth version`
Latest
OS & Version: Ubuntu 23.04 Linux

#### Expected behaviour
localhost should show webpage

#### Actual behaviour
token missing

#### Steps to reproduce the behaviour
ran private geth blockchain 

![image](https://github.com/ethereum/go-ethereum/assets/74496936/58e52688-b3d8-434e-80bd-19eb08460066)

**Comment by karalabe** [comment]
It's an authenticated RPC endpoint, you need to have JWT tokens https://jwt.io/

**Comment by imranmehdi5511** [comment]
It is not working for private blockchain
