### ISSUE TITLE
Do you have some tool to analyze the storage of the data space?

### ISSUE THREAD

**Issue by lurais** [ethereum/go-ethereum#27441]
Hello , I want to analyze the storage of the data space in eth, and want to know percentage of each part,do you have some chart or some tool to do that?

**Comment by holiman** [comment]
Check out `geth db inspect` (cannot be executed simultaneously as another geth is running)

**Comment by holiman** [comment]
Example output: https://github.com/ethereum/go-ethereum/pull/25896#issue-1391842360
