### ISSUE TITLE
eth_getFilterChanges returns null

### ISSUE THREAD

**Issue by phleemac** [ethereum/go-ethereum#2746]
#### System information

Geth version: `1.4.7-stable-667a386d`
OS & Version: Linux
#### Expected behaviour

In testnet:
1. `curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock":"0x127518","toBlock":"0x1281c3","address":"0xd41dc0fcc7b58e6fbd4f45055ec541fec1a299af","topics":[null,"0x000000000000000000000000a24d28d30ee9711149241510ce66e8791a8043fa"]}],"id":1}' http://localhost:8545`
2. `curl -X POST --data '{"jsonrpc":"2.0","method":"eth_newFilter","params":[{"fromBlock":"0x127518","toBlock":"0x1281c3","address":"0xd41dc0fcc7b58e6fbd4f45055ec541fec1a299af","topics":[null,"0x000000000000000000000000a24d28d30ee9711149241510ce66e8791a8043fa"]}],"id":1}' http://localhost:8545` 
3. `curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getFilterChanges","params":[<filter id from #2>],"id":2}' http://localhost:8545`

Expected:
1. returns 4 log records
2. returns filter id
3. returns the same 4 log records as (1)
#### Actual behaviour
1. returns 4 log records
2. returns filter id
3. returns: `{"jsonrpc":"2.0","id":2,"result":null}`

**Comment by tymat** [comment]
getFilterChanges only gives you the changes... you want to use getFilterLogs instead

**Comment by phleemac** [comment]
@tymat thanks for the reply.  So, the sequence of calls should be
1. `newFilter` -> `getFilterLogs` -> `getFilterChanges` -> `getFilterChanges`...
rather than
2. `newFilter` -> `getFilterChanges` -> `getFilterChanges`...
correct?

Even if that's the case, shouldn't `getFilterChanges` returns empty array (as stated in [https://github.com/ethereum/wiki/wiki/JSON-RPC](https://github.com/ethereum/wiki/wiki/JSON-RPC) ) rather than null?

I've also tested:
3. `newBlockFilter` -> `getFilterChanges` -> `getFilterChanges`...

and got the expected behaviour i.e. first `getFilterChanges` returns array of blocks since `newBlockFilter` and subsequent `getFilterChanges` returns empty array until there is new block.

**Comment by bas-vk** [comment]
It depends on what you are trying to do.

- If you want to fetch logs that are already imported then use `getFilterLogs`.
- If you want to monitor a contract and listen for new logs then you should poll with `getFilterChanges`.

Regarding the `null`, that is indeed an error and it should return an empty array. This has been solved in a new version of the filter package.

**Comment by fjl** [comment]
Should be resolved with 1.5.0.
