### ISSUE TITLE
Add RPC endpoint getBalancesChangesInBlock

### ISSUE THREAD

**Issue by twilightrus** [ethereum/go-ethereum#27469]
Add RPC endpoint getBalancesChangesInBlock like erigon: https://github.com/ledgerwatch/erigon/pull/4609

**Comment by karalabe** [comment]
We have a `debug.GetModifiedAccountsByHash` (/ByBlock). That will return a list of addresses changed in a block, but do note you can only do this for blocks that we have the trie for (i.e. last 128 blocks).

We may or may not expand on this in the future, but there are no plans for now.

**Comment by twilightrus** [comment]
> We have a `debug.GetModifiedAccountsByHash` (/ByBlock). That will return a list of addresses changed in a block, but do note you can only do this for blocks that we have the trie for (i.e. last 128 blocks).
> 
> We may or may not expand on this in the future, but there are no plans for now.

I think this is a useful API. I need it in order to quickly check for changes to my addresses (about 1 million). Please add as soon as possible with the possibility of using archive blocks.
