### ISSUE TITLE
Unpacking indexed arguments of an event log dynamically

### ISSUE THREAD

**Issue by yaziciahmet** [ethereum/go-ethereum#27499]
I am trying to parse the logs of a contract in a fully dynamic manner. Meaning that the only thing I have is the abi of the contract, and the filter query to filter out logs. I would like to parse the returned events dynamically. Here is my attempt so far:

```
func (c *Client) getHistoricalEvents(abiStr string, filterQuery ethereum.FilterQuery) ([]map[string]any, error) {
    contractAbi, err := abi.JSON(strings.NewReader(abiStr))
	if err != nil {
		return nil, err
	}

	logs, err := c.client.FilterLogs(c.ctx, filterQuery)
	if err != nil {
		return nil, err
	}

	
	var events []map[string]any
	for _, log := range logs {
		event := map[string]any{}
		for _, evInfo := range contractAbi.Events {
			if evInfo.ID.Hex() != log.Topics[0].Hex() {
				continue
			}

			if err := contractAbi.UnpackIntoMap(event, evInfo.Name, log.Data); err != nil {
				return nil, err
			}

			indexedArgCount := 0
			for _, arg := range evInfo.Inputs {
				if arg.Indexed {
					// i + 1 index due to first topic being function signature
					indexedArgCount += 1
					event[arg.Name] = log.Topics[indexedArgCount].Hex()
				}
			}

			break
		}

		events = append(events, event)
	}

	return events, nil
}

```

What I am doing above as steps is simply following:
1. Convert and validate that the provided abi is valid
2. Filter logs by the provided filter query
3. Iterate over returned logs
4. Find which event signature matches the log
5. Unpack the log.Data into map, as stated in the docs, this only unpacks the unindexed arguments
6. Range over the input arguments, and add indexed arguments to the map as well

There is one thing I want to do. In the loop where I range over the arguments to add the indexed variables into map as well, I add the variables as hex values. I would much prefer if I was able to get the type of the value and do a proper conversion, and set it to the map that way. I see that type Argument has `Type.GetType()` function which returns reflect.Type, but I am not sure how can I utilize that. So my question in a nutshell is, how can I unpack the indexed arguments with types, and not just have the hex value of them?

Thanks for any type of help!

**Comment by yaziciahmet** [comment]
Yes, but the thing is, I want to be able to do this in a dynamic manner. With the application I am building, the contract is provided as user input and I have no way of knowing into what struct I should unpack to. That is why I am using `UnpackIntoMap` in the first place. But that function only unpacks nonindexed arguments. Hence, I am going over `evInfo.Inputs`, and matching the indexed arguments with their respective index in the `log.Topics` slice. But I don't have any type information with this way. I only have the hex value, and I don't know how can I ensure and convert to its corresponding data type.

**Comment by jsvisa** [comment]
@yaziciahmet you can use `abi.ParseTopicsIntoMap` to parse the topics https://github.com/ethereum/go-ethereum/blob/8358293a569823616fff55b87b98355f68083dc0/accounts/abi/topics.go#L124-L129

and here is an example:

```go
package main

import (
	"bytes"
	"fmt"
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
)

var jsonEventTransfer = []byte(`[
{
  "anonymous": false,
  "inputs": [
    { "indexed": true, "name": "from", "type": "address" },
    { "indexed": true, "name": "to", "type": "address" },
    { "indexed": false, "name": "value", "type": "uint256" }
  ],
  "name": "Transfer",
  "type": "event"
}
]
`)

func main() {
	contractAbi, err := abi.JSON(bytes.NewReader(jsonEventTransfer))
	if err != nil {
		panic(err)
	}

	i2h := func(i int) common.Hash { return common.BigToHash(big.NewInt(int64(i))) }

	// Transfer(address indexed from, address indexed to, uint256 value);
	topic := common.HexToHash("0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef")
	log := types.Log{Topics: []common.Hash{topic, i2h(2), i2h(1)}, Data: i2h(11).Bytes()}

	event := map[string]any{}
	for _, evInfo := range contractAbi.Events {
		if evInfo.ID.Hex() != log.Topics[0].Hex() {
			continue
		}

		indexed := make([]abi.Argument, 0)
		for _, input := range evInfo.Inputs {
			if input.Indexed {
				indexed = append(indexed, input)
			}
		}

		// parse topics without event name
		if err := abi.ParseTopicsIntoMap(event, indexed, log.Topics[1:]); err != nil {
			panic(err)
		}
                // parse data
		if err := contractAbi.UnpackIntoMap(event, evInfo.Name, log.Data); err != nil {
			panic(err)
		}

		break
	}

	fmt.Println(event)
}
```

**Comment by yaziciahmet** [comment]
Exactly what I was looking for, thank you very much!
