### ISSUE TITLE
[crash] fatal error: runtime: cannot map pages in arena address space

### ISSUE THREAD

**Issue by luclu** [ethereum/go-ethereum#2751]
#### System information

Geth version: `geth 1.4.7`
OS & Version: Windows 7 x64
#### Actual behaviour

Crashed while sending via Mist `0.7.6`. 
#### Backtrace

```
runtime: VirtualAlloc of 268435456 bytes failed with errno=487
fatal error: runtime: cannot map pages in arena address space
```

https://gist.github.com/luclu/19d38a3b62b90fb23721083b642d5d47

**Comment by karalabe** [comment]
What Go version was this Geth built? Could you please check via `geth version`?

**Comment by karalabe** [comment]
Are you sure this was running the 64 bit binaries and not 32 bit ones?

**Comment by hackneyb** [comment]
I have the same issue after about an hour of running geth in command line.. so far just synchronizing blocks.  32 bit windows 8.1.  Happens reliably.  

VERSION:
   1.4.10-stable-5f55d95a

I0914 18:49:14.540649 core/blockchain.go:963] imported 2048 block(s) (0 queued 0 ignored) including 3857 txs in 3m44.7704976s. #760398 [2c7ef1ef / a56a33a9]
I0914 18:50:13.193704 eth/handler.go:295] Peer c572ee5cce9bfe7c [eth/63]: timed out DAO fork-check, dropping
I0914 18:50:46.928400 eth/handler.go:295] Peer 991aa11d7aa1cc4c [eth/63]: timed out DAO fork-check, dropping
runtime: VirtualAlloc of 100663296 bytes failed with errno=487
fatal error: runtime: cannot map pages in arena address space
