### ISSUE TITLE
RPC methods not working after syncing reached 100%

### ISSUE THREAD

**Issue by shivraj001** [ethereum/go-ethereum#27526]
#### System information

Geth version: `1.12.0`
CL client & version: prysm@v1.0.0
OS & Version: Linux

#### Expected behaviour
eth.blocknumber - should show current block height 
eth.accounts - should show all the accounts 

#### Actual behaviour

> eth.blockNumber
0
> eth.accounts
[]
> 

execution-geth-1 | INFO [06-21|09:36:01.858] Syncing: chain download in progress      synced=100.00% chain=496.26GiB headers=17,527,184@7.94GiB bodies=17,526,367@340.17GiB receipts=17,526,367@148.15GiB eta=2h19m37.733s
execution-geth-1 | INFO [06-21|09:36:06.538] Syncing: state healing in progress       accounts=292,000@15.26MiB slots=525,647@39.80MiB codes=5452@38.62MiB nodes=37,083,718@9.61GiB pending=2758
execution-geth-1 | WARN [06-21|09:36:06.685] Unexpected trienode heal packet          peer=8c54b643 reqid=8,660,430,172,362,375,972
execution-geth-1 | WARN [06-21|09:36:06.694] Unexpected trienode heal packet          peer=6b36f791 reqid=6,412,860,644,555,985,575
execution-geth-1 | WARN [06-21|09:36:06.699] Unexpected trienode heal packet          peer=715d3645 reqid=8,913,701,575,317,039,768
execution-geth-1 | WARN [06-21|09:36:06.700] Unexpected trienode heal packet          peer=9c3622ef reqid=3,623,348,476,507,868,339
execution-geth-1 | WARN [06-21|09:36:06.731] Unexpected trienode heal packet          peer=daef9a77 reqid=5,380,161,137,533,838,116
execution-geth-1 | WARN [06-21|09:36:06.777] Unexpected trienode heal packet          peer=95c20924 reqid=6,343,749,980,534,419,747
execution-geth-1 | WARN [06-21|09:36:06.782] Unexpected trienode heal packet          peer=692ab416 reqid=8,266,059,890,683,097,072
execution-geth-1 | WARN [06-21|09:36:06.785] Unexpected trienode heal packet          peer=77d6798f reqid=2,188,054,193,697,169,132
execution-geth-1 | WARN [06-21|09:36:06.826] Unexpected trienode heal packet          peer=98caaca1 reqid=968,560,278,550,331,964
execution-geth-1 | WARN [06-21|09:36:06.898] Unexpected trienode heal packet          peer=d4604660 reqid=4,498,942,524,728,413,404
execution-geth-1 | INFO [06-21|09:36:10.541] Syncing: chain download in progress      synced=100.00% chain=496.26GiB headers=17,527,184@7.94GiB bodies=17,527,118@340.17GiB receipts=17,527,118@148.15GiB eta=10m21.296s
execution-geth-1 | INFO [06-21|09:36:13.842] Forkchoice requested sync to new head    number=17,527,185 hash=2529c1..fa101a finalized=17,527,108
execution-geth-1 | INFO [06-21|09:36:18.548] Syncing: chain download in progress      synced=100.00% chain=496.26GiB headers=17,527,185@7.94GiB bodies=17,527,118@340.17GiB receipts=17,527,118@148.15GiB eta=10m30.768s
execution-geth-1 | INFO [06-21|09:36:18.589] Syncing: state healing in progress       accounts=292,000@15.26MiB slots=525,647@39.80MiB codes=5452@38.62MiB nodes=37,083,948@9.61GiB pending=3660
execution-geth-1 | INFO [06-21|09:36:24.508] Forkchoice requested sync to new head    number=17,527,186 hash=ce1c17..43cda7 finalized=17,527,108
execution-geth-1 | INFO [06-21|09:36:26.552] Syncing: chain download in progress      synced=100.00% chain=496.26GiB headers=17,527,186@7.94GiB bodies=17,527,118@340.17GiB receipts=17,527,118@148.15GiB eta=10m40.242s
execution-geth-1 | INFO [06-21|09:36:32.596] Syncing: state healing in progress       accounts=292,000@15.26MiB slots=525,647@39.80MiB codes=5452@38.62MiB nodes=37,084,165@9.61GiB pending=6775
execution-geth-1 | INFO [06-21|09:36:34.562] Syncing: chain download in progress      synced=100.00% chain=496.26GiB headers=17,527,186@7.94GiB bodies=17,527,118@340.17GiB receipts=17,527,118@148.15GiB eta=10m40.301s
execution-geth-1 | INFO [06-21|09:36:36.652] Forkchoice requested sync to new head    number=17,527,187 hash=1a95a5..b6598c finalized=17,527,108
execution-geth-1 | INFO [06-21|09:36:41.399] Syncing: state healing in progress       accounts=292,000@15.26MiB slots=525,647@39.80MiB codes=5452@38.62MiB nodes=37,084,372@9.61GiB pending=9387
execution-geth-1 | INFO [06-21|09:36:42.567] Syncing: chain download in progress      synced=100.00% chain=496.26GiB headers=17,527,187@7.94GiB bodies=17,527,118@340.17GiB receipts=17,527,118@148.15GiB eta=10m49.778s

It looks like execution client syncing has reached 100%, but rpc methods are not working. Its been more then a day now.
it is happening while running Ethereum mainnet full node  
Can someone help here ? any sort of suggestions or guide is appreciated

**Comment by s1na** [comment]
Your node is still in sync. I agree the 100% is confusing :) but you will stop seeing those messages altogether when it is actually in sync. Another hint is that `eta=10m49.778s` is non-zero.

**Comment by shivraj001** [comment]
thanks @s1na  for clarification
