### ISSUE TITLE
Post smart contract call transaction using geth with clef signer cause an error [validation failed: Transaction contains data, but the ABI signature could not be found: signature 202d347f not found]

### ISSUE THREAD

**Issue by AT19947** [ethereum/go-ethereum#27528]
#### System information

Version: 1.11.5-stable
Git Commit: a38f4108571d1a144dc3cf3faf8990430d109bc4        
Git Commit Date: 20230321
Architecture: amd64
Go Version: go1.20.2
Operating System: Windows

Error message:
validation failed: Transaction contains data, but the ABI signature could not be found: signature 202d347f not found

#### Smart contract code:

    // SPDX-License-Identifier: MIT
    pragma solidity <0.9.0;
    
    contract HelloWorld {
    
        string public helloSentence;
        
        constructor() {
            helloSentence = "Hello World!";
        }
    
        function sayHello() public view returns (string memory) {
            return helloSentence;
        }
    
        function setHelloSentence(string memory sentence) public {
            helloSentence = sentence;
        }
    }

#### js code to call the smartcontarct method:

    const { Web3 } = require("web3"); 
    const SMART_CONTRACT_ABI = [
    {
      inputs: [],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      inputs: [],
      name: "helloSentence",
      outputs: [
        {
          internalType: "string",
          name: "",
          type: "string",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "sayHello",
      outputs: [
        {
          internalType: "string",
          name: "",
          type: "string",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "string",
          name: "sentence",
          type: "string",
        },
      ],
      name: "setHelloSentence",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    ];
  
     const web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:55008"));
     const contract = new web3.eth.Contract(SMART_CONTRACT_ABI,"0xEdAd9FcE55Fa7D6719E0f1CbC1678Bc6BD2B5A98");
  
    web3.eth.sendTransaction(
    {
      from: "0x4aa49d0566cad80ab4e63c3b63b90b89696560f4",
      to: "0xEdAd9FcE55Fa7D6719E0f1CbC1678Bc6BD2B5A98",
      data: contract.methods.setHelloSentence("test").encodeABI(),
    },
    function (err, transactionHash) {
      if (!err) console.log(transactionHash + " success");
    }
    )

**Comment by akefhabbal-qu** [comment]
I am getting same error

**Comment by joohhnnn** [comment]
use --advance to start clef or add selector field https://github.com/ethereum/go-ethereum/issues/27524

**Comment by AT19947** [comment]
It works after adding the **--advanced** flag to start clef command, Thanks @joohhnnn.
