### ISSUE TITLE
Possible bug in transaction RLP parsing

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#27529]
The python team report that on this transaction 
`retesteth -t GeneralStateTests/stTransactionTest -- --singletest ValueOverflow --verbosity RPC --clients default --singlenet Merge`
t8n inputs:
https://drive.google.com/file/d/1WpZz9k0o5DZX70AWE98gFNhgijoiNL6H/view?usp=sharing

live web trace:
http://retesteth.ethdevops.io/web/index.php?gtests=stTransactionTest&singletest=ValueOverflow&clients=t8ntool&snetwork=Merge&vmtrace=none&verbosity=RPC&trd=&trg=&trv=

The geth t8n is given a malicious tx rlp with value field over 256 bit value. and it seems it still tries to calculate the gas/price requirements for the execution and report that not enough funds in the senders account. 
Instead it must throw transaction parse error or smth. becaues the value field is not allowed to be that high.

**Comment by lightclient** [comment]
This isn't really an RLP parsing error, more a JSON unmarshaling error? Still, I see with the blob txs, we're now using `uint256` instead of `big.Int`. Not sure we can change the other txs types at this point as it would break anyone using those types.

It does feel a bit wonky to have two different big int libraries for different txs. I don't know the best way to resolve this. Ultimately it isn't problematic in practice because the balance check will always fail.

**Comment by holiman** [comment]
The tx is provided in rlp, not json

**Comment by lightclient** [comment]
Ah I see now, the JSON print out is just convenience. Rest of the questions still hold though I think.

**Comment by karalabe** [comment]
> It does feel a bit wonky to have two different big int libraries for different txs. 

My goal is to switch everything over in Geth to uint256 gradnually, just gotta start somewhere.

**Comment by MariusVanDerWijden** [comment]
It looks like the checks in the t8ntool are in a different order than actual execution, see https://github.com/ethereum/go-ethereum/blob/8bbb16b70ef4a9e732745aac104525a6f16306d6/cmd/evm/internal/t8ntool/transaction.go#L155

**Comment by holiman** [comment]
Isn't that related only to 'evm transaction', not 'evm transition'?

**Comment by holiman** [comment]
> Instead it must throw transaction parse error or smth. becaues the value field is not allowed to be that high.

I don't think it is correct to call it an "rlp parsing" error. As far as I know, there's no "dynamic but max 256 bit" field in rlp, it's either dynamic-size or fixed. The cap at `256` bits is thus on the layer above rlp.

**Comment by amritabithi** [comment]
Could a simple fix possibly be to disable the creation of external entities when anything is being parsed that came in over the network?

ie.

`factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);`
