### ISSUE TITLE
Add Forced Sign Option to account_signTransaction in Clef Module

### ISSUE THREAD

**Issue by joohhnnn** [ethereum/go-ethereum#27524]
# Rationale
Add Forced Sign Option to account_signTransaction in Clef Module When Method Selector Is Unknown and Not in 4byte Database

I've run into a specific situation that I think could be improved.

Currently, when using the `account_signTransaction` function in the Clef module, if the function's method selector is not known and it's also not in the 4byte database, the transaction will not be signed. This makes it difficult to interact with new contracts whose ABIs are not in the 4byte database.

Moreover, maintaining the 4byte.json library can be challenging due to the growing number of contracts and the fact that not all contracts are open source. https://github.com/ethereum/go-ethereum/pull/27504#issuecomment-1596372148

To enhance the usability and versatility of the Clef module, I propose to add a new feature that allows a transaction to be forcibly signed, even if the method selector is unknown and not in the 4byte database.

# Implementation

Do you have ideas regarding the implementation of this feature?
Add a new API, for example, `forceSignTransaction()`, or add a string handler for the signTransaction method where the input 'force' is passed to the 'selector' field to indicate a forced signing.
Are you willing to implement this feature?
Yes

**Comment by holiman** [comment]
You can just start clef in --advanced mode, then you get the option to continue despite warnings

**Comment by joohhnnn** [comment]
> You can just start clef in --advanced mode, then you get the option to continue despite warnings

aha , found It, cool!!
