### ISSUE TITLE
should we make CREATE/CREATE2  have some gasRefund if the codeHash already exist.

### ISSUE THREAD

**Issue by joohhnnn** [ethereum/go-ethereum#27546]
This discussion could potentially lead to a new EIP (if there isn't an existing EIP with the same content). When a new contract is created, if the contract's codeHash already exists, the node will reuse the same code. In this case, would it be possible to provide a gas refund to the deployer?

**Comment by lightclient** [comment]
This isn't really the right place for this type of discussion. You should create a post on https://ethereum-magicians.org.
