### ISSUE TITLE
Why is the expected recovery id for Bitcoin style signatures (<4) as opposed to ETH signatures (27 or 28)

### ISSUE THREAD

**Issue by CarsonCase** [ethereum/go-ethereum#27542]
https://github.com/ethereum/go-ethereum/blob/699243f8ae870fa2ddbc5cb919fda85313e4684a/crypto/secp256k1/secp256.go#L171C15-L171C15

I am working on validating a Metamask signature using Ecrecover and am confused as to why the Ecrecover function expects the v signature value to be <4. Perhaps I'm missing something but it seems that we would want it to be expecting 27 or 28? Maybe someone can help correct me or point me in the right direction, or let me know if this is a somehow overlooked problem.

**Comment by MariusVanDerWijden** [comment]
Geth uses the same library for signature recovery as bitcoin, so all signatures need to be modified to match the crypto library. You can see this step in the ecrecover precompile here: https://github.com/ethereum/go-ethereum/blob/8bbb16b70ef4a9e732745aac104525a6f16306d6/core/vm/contracts.go#L197

For the future, please address these questions to the ethereum stack exchange: https://ethereum.stackexchange.com/, we would like to keep the issue tracker focused on bugs in geth
