### ISSUE TITLE
abigen not supporting interface types as arguments

### ISSUE THREAD

**Issue by pyropy** [ethereum/go-ethereum#27551]
Seems like abigen does not support interface types. When trying to generate code for following ABI I get this error `Fatal: Failed to generate ABI binding: unsupported arg type: ICvx`

```json
[{"inputs":[{"internalType":"uint256","name":"_amount","type":"uint256"}],"name":"ConvertCrvToCvx","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"cvx","outputs":[{"internalType":"contract ICvx","name":"","type":"ICvx"}],"stateMutability":"view","type":"function"}]
```

Is there some way around this?

**Comment by jsvisa** [comment]
Are you given abigen the inner contract type(`ICVx`) of `{"internalType":"contract ICvx","name":"","type":"ICvx"}`

**Comment by jsvisa** [comment]
You need the contract interface of `ICVx`
