### ISSUE TITLE
Loose peers every 5 to 7 days

### ISSUE THREAD

**Issue by tunerooster** [ethereum/go-ethereum#27569]
#### System information

Geth version: `geth version`

Version: 1.12.0-stable
Architecture: amd64
Go Version: go1.19
Operating System: linux
GOPATH=
GOROOT=

CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0

prysm - beacon-chain-v4.0.6-linux-amd64

OS & Version: Windows/Linux/OSX

Linux u59 5.15.7-gentoo #7 SMP Tue Jan 25 20:44:26 MST 2022 x86_64 Intel(R) Celeron(R) N5095 @ 2.00GHz GenuineIntel GNU/Linux

#### Expected behaviour

Keep peer count normal.

#### Actual behaviour

I loose peers after geth runs for 5 to 7 days and reboot to fix.

#### Steps to reproduce the behaviour

Just start geth and wait.

**DESCRIPTION:** 

Every 5 to 7 days I discover (through my grafana dashboard) that my peer count is too low (like under 10).  It is usually around 45 when operating normally.

I usually just reboot to fix it.  This causes "Slots behind" to go up and it takes 10 - 15 minutes to recover.  I would like to determine what is causing the loss of peers.  Can you suggest how I might troubleshoot this?

This has been happening for months, but I am only now posting this, hoping it would be fixed in the several releases I have installed since it started happening.  I do not recall exactly when it first started happening (i.e., what version).  It was running for almost a year without this happening.

Please advise...  THANKS!

**Comment by lightclient** [comment]
Could you share some logs of your client? Ideally showing your client going from more than enough peers to below the threshold of peers to print the msg "Looking for peers". If you could also enable debug logging for p2p with the flag `--log.vmodule="p2p=4"`, that may help us figure out why it is failing to connect to peers. And a screenshot of your grafana dashboard if you have it.

**Comment by tunerooster** [comment]
OK.  Should I restart geth now like this?
```
/usr/bin/geth --log.vmodule="p2p=4" --http --datadir /mnt/crypto/.ethereum --authrpc.jwtsecret=/mnt/crypto/.ethereum/keystore/jwt.hex
```
It will mean waiting a week or so before it happens again.  I will get the logs and screen shot then.

Thanks for your help!

**Comment by lightclient** [comment]
You can actually activate a higher log level using `geth attach`

```console
$ geth attach --datadir /mnt/crypto/.ethereum

Welcome to the Geth JavaScript console!
> debug.vmodule("p2p=4")

--

but yes, if you can update this issue with more information when you have it we can take a look. Thanks.

**Comment by tunerooster** [comment]
Well, it's been 2 weeks and the problem has not recurred.  I have made changes to my firewall, like a updated kernel, for other purposes, but I have no idea if that is what fixed it.  In any case, I am closing this issue.  If it happens again, I will reopen it.

Thanks for your willingness to help!
