### ISSUE TITLE
miner.start() no longer works.

### ISSUE THREAD

**Issue by quakemmo** [ethereum/go-ethereum#27607]
#### System information

Geth version: `Geth/v1.12.0-stable-e501b3b0/linux-amd64/go1.20.3`
CL client & version: none
OS & Version: Debian 12
Commit hash : github release

#### Expected behaviour
Starts mining.

#### Actual behaviour
```> miner.start();
Error: too many arguments, want at most 0
	at web3.js:6365:9(39)
	at send (web3.js:5099:62(29))
	at <eval>:1:12(2)

> 
```

#### Steps to reproduce the behaviour
Run a clique single node network. Type miner.stop() - it works. Type miner.start() - error.

#### Backtrace

````
Error: too many arguments, want at most 0
	at web3.js:6365:9(39)
	at send (web3.js:5099:62(29))
	at <eval>:1:12(2)

````

When submitting logs: please submit them as text and not screenshots.

**Comment by lightclient** [comment]
`miner.start()` no longer accepts "threads" as a parameter as of #27178. So you should call it with no arguments.

**Comment by lightclient** [comment]
@jmcook1186 if you have a chance could you update this in the geth docs please?

**Comment by quakemmo** [comment]
@lightclient I get the error even when calling miner.start() without any arguments! Please reopen the issue.

**Comment by lightclient** [comment]
@quakemmo apologies, I ran `miner.start()` on master, I see now you are `v1.12.0`. This was fixed in https://github.com/ethereum/go-ethereum/pull/27400. Thanks

**Comment by taoli-ax** [comment]
I got same error, how to solve this problem? how to start miner
