### ISSUE TITLE
Tech debt: remove the full/light split accman service dependency

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#2760]
The full/light node API split PR https://github.com/ethereum/go-ethereum/pull/2159 separated out account/key management to its own node service. This is not a good decision because it makes setting up Ethereum nodes from client libraries much more complex and unwarranted.

The account manager service needs to be moved back cleanly into the Ethereum services and not stand as a standalone service.

**Comment by fjl** [comment]
The API split is only on develop so I'm closing this issue now.
