### ISSUE TITLE
Missing data of the transaction from Null: 0x000…000 to Null: 0x000…000 on Polygon

### ISSUE THREAD

**Issue by tmanh17** [ethereum/go-ethereum#27624]
I am trying to collect all logs (transfer events) of Block [44197728](https://polygonscan.com/block/44197728) on Polygon

It's able to return all logs/transactions except data of the transaction
https://polygonscan.com/tx/0xb02686734494f5a1455c43d2dd1dc739f40134bf621efcf65f335930baba40c7

The transaction and 3 transfer events were missing (see the below image).
<img width="1166" alt="image" src="https://github.com/ethereum/go-ethereum/assets/29015535/47d2ccde-652d-4f29-bfaf-8e57c0fa1299">

Could anyone give me instructions to collect logs (transfer events) of [the above transaction](https://polygonscan.com/tx/0xb02686734494f5a1455c43d2dd1dc739f40134bf621efcf65f335930baba40c7), please?

### Reproduce:
```
import (
        "github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/rpc"
)
```
Try to use the following filter to get logs.
```
filter := ethereum.FilterQuery{
	FromBlock: big.NewInt(int64(fromBlock)),
	ToBlock:   big.NewInt(int64(toBlock)),
	Topics:    make([][]common.Hash, 0),
}
```
```
rpc.BatchElem{
	Method: "eth_getLogs",
	Args: []interface{}{
		filterArg,
	},
	Result: &logs,
}
```
Where filterArg is formalized from filter to 
```filterArg=map[fromBlock:0x2a26760 toBlock:0x2a26760 topics:[]]```

Thank you

**Comment by rjl493456442** [comment]
Please open the ticket in polygon repo.
