### ISSUE TITLE
websocket read/write timeouts and ping interval should be customizable

### ISSUE THREAD

**Issue by jshufro** [ethereum/go-ethereum#27627]
I'm curious why these are asymmetric: https://github.com/ethereum/go-ethereum/blob/master/rpc/websocket.go#L38-L40
It seems to me writing and reading should have similar timeouts- an external service communicating with geth over a websocket will suffer the same limitations writing over the socket as reading from it, no?

Beyond that, I wish they were configurable on an instance of `websocketCodec` and that configurability was bubbled up into [ethclient](https://pkg.go.dev/github.com/ethereum/go-ethereum/ethclient)

I run a service that holds open an event subscription, and while I've dealt with needing to reconnect gracefully, it happens a bit too often for my linking, so it'd be nice if it could be tuned.

ethclient itself doesn't need the options, as it exposes its underlying [rpc.Client](https://pkg.go.dev/github.com/ethereum/go-ethereum@v1.12.0/rpc#Client)... which has nice support for custom http timeouts via `DialHTTPWithClient`, but no support for custom websocket ping timeouts/intervals

# Rationale

Why should this feature exist?

- It will improve the flexibility of the ethclient library

What are the use-cases?

- Not all hardware is created equal, and a 5/30 second write/read timeout may thrash on certain platforms 

# Implementation

Do you have ideas regarding the implementation of this feature?

 - yes, perhaps similar to how an http.Client can be passed in, a websocket.Conn can be exposed up to the rpc.Client abstraction upon creation, or a partially instantiated one can be passed down

Are you willing to implement this feature?

... yeah ok

**Comment by lightclient** [comment]
Since Felix is the original author, I'll defer to him as to why the read/write timeouts are not symmetric. I'm not sure.

--

As for implementing the change I think it could make sense to add more websocket configuration parameters to `rpc.clientConfig`. Right now we accept a dialer from the upstream package, but since the keep-alive functionality is in our websocket-jsonCodec wrapper, it isn't expressive enough. Based on #21126 I don't think we will expose the websocket conn outright.

**Comment by holiman** [comment]
As for why they are not symmetric: write is a local operation, pushing stuff into a websocket frame and ship off. Read timeout (pong) depends on the remote part doing something, therefore that deadline is longer.

**Comment by karalabe** [comment]
Making these configurable is not really meaningful. In all scenarios it should take semi-instant to do the transfers. Both 5 and 30 secs is a crazy long time. It's just about not implying anything about the remote implementation with the long timeout.

**Comment by jshufro** [comment]
I have a heatmap of how often I see i/o timeouts reported by my websocket connection:
![image](https://github.com/ethereum/go-ethereum/assets/116244/ea35d13e-4a55-42ee-a158-10077fc88323)
(please disregard the node names, the connection is between a go application and geth)

I was hoping to see if an increased timeout helped the lodestar node, but I'm guessing something else is wrong. You're right, in that 30 seconds should be plenty, considering the application and geth are cotenant. I suppose I can build the application with a fork of the library and try to figure out what's going on here that way, though.

**Comment by jshufro** [comment]
Well I have a theory.

`websocketCodec`'s `pingLoop` sets a WriteDeadline, writes a message, then sets a s read deadline:
```golang
			wc.conn.SetWriteDeadline(time.Now().Add(wsPingWriteTimeout))
			wc.conn.WriteMessage(websocket.PingMessage, nil)
			wc.conn.SetReadDeadline(time.Now().Add(wsPongTimeout))
```

After the pong is received, it clears the read deadline:
```
	conn.SetPongHandler(func(appData string) error {
		conn.SetReadDeadline(time.Time{})
		return nil
	})
```

Now, this order of operations seems fine:
1. writeJson
2. pingLoop
namely because `writeJson` will defer the ping by resetting the timer and clear the timer's channel

however, this order:
1. pingLoop
2. writeJson
3. writeJson
4. ...

can race.

Specifically, pingLoop sets a non-0 ReadDeadline... the net.Conn docs say
```
	// SetReadDeadline sets the deadline for future Read calls
	// and any currently-blocked Read call.
	// A zero value for t means Read will not time out.
```

writeJson doesn't set a read deadline, only a write deadline, so a writeJson that happens after pingLoop sets the read deadline will be subject to the same deadline.

it seems to me that you can't just set a new deadline in writeJson, because the deadline can get indefinitely postponed (specifically if the pong is currently-blocked), though it may be eventually-consistent. One possible fix would be to hold open a mutex until the pong is received or times out, which can delay a write that will ultimately succeed, but should only be a problem on mostly-idle connections.
