### ISSUE TITLE
ambiguous import: found package github.com/btcsuite/btcd/chaincfg/chainhash in multiple modules

### ISSUE THREAD

**Issue by yangyile1990** [ethereum/go-ethereum#27622]
github.com/ethereum/go-ethereum v1.12.0

go mod tidy
chain-imp/imp/impeth imports
        github.com/ethereum/go-ethereum/accounts/abi/bind imports
        github.com/ethereum/go-ethereum/crypto imports
        github.com/btcsuite/btcd/btcec/v2/ecdsa tested by
        github.com/btcsuite/btcd/btcec/v2/ecdsa.test imports
        github.com/btcsuite/btcd/chaincfg/chainhash: ambiguous import: found package github.com/btcsuite/btcd/chaincfg/chainhash in multiple modules:
        github.com/btcsuite/btcd v0.20.1-beta (/Users/admin/Documents/work/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/chaincfg/chainhash)
        github.com/btcsuite/btcd/chaincfg/chainhash v1.0.1 (/Users/admin/Documents/work/go/pkg/mod/github.com/btcsuite/btcd/chaincfg/chainhash@v1.0.1)

**Comment by karalabe** [comment]
Not sure what the issue is, could you elborate?
