### ISSUE TITLE
Please make a question post for this title: "Is the entire Ethereum Virtual Machine (EVM) embedded in Geth written in Go, or is C++ used as well?"

### ISSUE THREAD

**Issue by AlirezaEthDev** [ethereum/go-ethereum#27632]
I'm planning to implement a custom public Ethereum blockchain and modify the EVM. I'm wondering what programming language is used to write the EVM embedded in Geth and whether C++ is used as well. Can anyone clarify this for me?

**Comment by MariusVanDerWijden** [comment]
It's written in go, you can find it here: https://github.com/ethereum/go-ethereum/tree/master/core/vm
