### ISSUE TITLE
[POA] Get block gas limit in the each node

### ISSUE THREAD

**Issue by anhnh131** [ethereum/go-ethereum#27639]
[Private Network]-[POA]. The block gas limit can be adjusted after launch using the `--miner.gaslimit` command-line flag. But, we can not get this config ( gaslimit ) through API. Is there any way to do that?

**Comment by chenjia404** [comment]
You can view the blocks mine by this node, you can see  gaslimit

**Comment by anhnh131** [comment]
@chenjia404 Hi, It means the gas limit of the block? but I think that doesn't gas limit config from the command line.
https://github.com/ethereum/go-ethereum/blob/6ca3ef9a7b7ebf3ed0004cfdca0c7a27a38c28e7/core/block_validator.go#L149-L170

**Comment by chenjia404** [comment]
yes, gaslimit  not gastarget

**Comment by anhnh131** [comment]
But I think that isn't the gas limit config from the command `--miner.gaslimit` .
The block gas limit in each block was calculated the same below, right? It depends on `parentGasLimit` and `desiredLimit`
https://github.com/ethereum/go-ethereum/blob/6ca3ef9a7b7ebf3ed0004cfdca0c7a27a38c28e7/core/block_validator.go#L149-L170

**Comment by lightclient** [comment]
I'm not really sure how useful it is to expose the local miner's current gas limit target from the RPC level. Current gas limits can be ascertained by just seeing a recent block. Can you motivate this use case?

**Comment by anhnh131** [comment]
> 
Yes, but what if the block gas limit config is different between node miners?

**Comment by lightclient** [comment]
It's up to each miner to decide their gas limit target. If miners differ, the gas limit will just oscillate according to protocol rules.

**Comment by anhnh131** [comment]
> It's up to each miner to decide their gas limit target. If miners differ, the gas limit will just oscillate according to protocol rules.
yes, so I think the gas limit in each block might be different from the gas limit config in miner nodes.

**Comment by lightclient** [comment]
I recommend developing a solution for your network that meets your needs. You can create custom APIs to guess what other miner's gas limits are based on how they affect the limit or you could create a mechanism for sharing that information amongst miners. But these are not features that we will likely support. I hope you understand. Thanks.
