### ISSUE TITLE
Blockchain transactions confirmation error

### ISSUE THREAD

**Issue by tkb2501** [ethereum/go-ethereum#27640]
Hi Team,

We have a quorum BC network, where we have 2 VMs each with 1 validator and 1 member quorum node apart from one RPC node.

Till few hours back our network was working fine but some time before because of the temp memory issue in one of the VM, we are not able to process transactions in Blockchain network. So, after resolving the memory issue we have restarted our docker containers in that VM.

After restarting, quorum nodes gets in sync with rest of the quorum nodes, now when we are processing our transactions then those transactions are getting into the memory pool(i.e. pending state). We have around 60 txns in the memory pool and our Blockchain network is not able to build new blocks for these transactions.

How can we process those pending transactions so that doesn't stop our network in Block generation for further transactions. Can someone please help with this issue.

**Comment by kehiy** [comment]
are you runing go-ethereum?

**Comment by tkb2501** [comment]
Yes, we are running docker based geth nodes for validators and member nodes.

**Comment by lightclient** [comment]
What version of geth? Commit hash? Can you share some logs showing the issue?

**Comment by tkb2501** [comment]
We are using 1.10.2 version for geth:

Version: 1.10.2-stable
Git Commit: e5b930e8e9a6ff043b3e71a4e3b852280fe413f0
Quorum Version: 22.7.0

Logs from member node :

```
INFO [07-04|04:15:23.169] Commit new mining work                   number=26210 sealhash="abff59…2445ca" uncles=0 txs=20 gas=411595011 fees=0 elapsed=3.029s
INFO [07-04|04:15:24.529] Submitted transaction                    hash=0xb5ddac4a858152b306e337e565cf0e4cc9f08070b3e08432192f93d630ab21e5 from=0x09532cfe222FeDfdf14D7FA662E890Aa7486D8B3 nonce=420 recipient=0xA4cF608b222f783B96dcF8Ff8e888080832642D0 value=0
INFO [07-04|04:15:24.529] QUORUM-CHECKPOINT                        name=TX-CREATED   tx=0xb5ddac4a858152b306e337e565cf0e4cc9f08070b3e08432192f93d630ab21e5 to=0xA4cF608b222f783B96dcF8Ff8e888080832642D0
INFO [07-04|04:15:26.179] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0x69a764fd6dd988d997eee947952ae73ce5cb68714e64770d5713187e89cd1402 time=34.450642ms
INFO [07-04|04:15:26.321] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0xe4ba5eefe326dd0f24ed88fbd0678ff7a20d644b3e0e1961b3be5e751b7a2eee time=10.271442ms
INFO [07-04|04:15:26.330] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0xc86ba73ce466bf4ca0f142819f3fc962755a2103a4ba919b70dd266b195192fb time=9.133738ms
INFO [07-04|04:15:26.340] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0x1206d1f711501980cbad363c58b0d475bfff3f494c02287beefe37d94b1a48bd time=9.357638ms
INFO [07-04|04:15:26.349] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0xccd4f54fb18dd0dc66793a688caa2003ee9ea5e876c553871bb76b6ee4b1de6e time=9.265738ms
INFO [07-04|04:15:26.369] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0xa99ea508c5d8cc85e48582533f9e76723b4b22b1c18f5f3be213cbd0d34a128e time=11.005745ms
INFO [07-04|04:15:26.390] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0x5d92dab1d7de9f1f12e8a6d1e6bdd33d4607e24cd566b79ac294ec374c1c646f time=9.962542ms
INFO [07-04|04:15:26.400] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0x8eb6a3dc0bf0b730e23489db472daa07af6f8dea9ba3c6060cf51a20a754f052 time=9.466039ms
INFO [07-04|04:15:26.409] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0x47422d604764a46e89c593c15b6e2f7fd23429cd07b71afc25e8976f236841ce time=9.190638ms
INFO [07-04|04:15:26.418] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0x94d058e81fe5e9101dd87c3f56626beb92b453d54b6057534faaea9b01049d79 time=9.231438ms
INFO [07-04|04:15:26.427] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0x5761b62a9855d121f4e5e4adade6315213a420899ba7c086617cf68027b286ab time=9.077037ms
INFO [07-04|04:15:26.437] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0xf1a58e6e59b74a9cdb7c47422eaba1d68d99ebca14f453a665e6cde82dac1248 time=9.267839ms
INFO [07-04|04:15:26.679] Commit new mining work                   number=26210 sealhash="614552…bb304d" uncles=0 txs=20 gas=411595011 fees=0 elapsed=535.428ms

```
Validator logs:

` QBFT: Correctly decoded SignedRoundChangePayload p="RoundChange {seq=26210, round=5, pr=<nil>, pv=0x0000000000000000000000000000000000000000000000000000000000000000}"
INFO [07-04|04:37:09.690] QBFT: Correctly decoded SignedRoundChangePayload p="RoundChange {seq=26210, round=5, pr=<nil>, pv=0x0000000000000000000000000000000000000000000000000000000000000000}"
ERROR[07-04|04:37:09.690] QBFT: Error List() Signed Payload        err="rlp: end of list"
INFO [07-04|04:37:09.698] QBFT: handle PRE-PREPARE message         address=0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
INFO [07-04|04:37:09.705] QBFT: accepted PRE-PREPARE message       address=0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
INFO [07-04|04:37:09.705] QBFT: changed state                      address=0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX current.round=5 current.sequence=26210 old.state="Accept request" new.state=Preprepared
INFO [07-04|04:37:09.705] QBFT: broadcast PREPARE message          address=0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX current.round=5 current.sequence=26210 state=Preprepared      msg.code=19 msg.source=0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX msg.round=5 msg.sequence=26210 payload=0xf869e58XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX572ad392cd9846baa7fd34c816300
ERROR[07-04|04:37:09.710] QBFT: Error List() Signed Payload        err="rlp: end of list"
INFO [07-04|04:43:49.366] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0x81319a8c901bec04d759ddec9fb9b8e3eb731bd04e369e2bb7b073dc5aa55cb9 time=57.960484ms
INFO [07-04|04:43:49.452] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0xa84b5e75a7fa88577f4bf6599c82df56d79ee5ee4ead63ebe766613b80c1cc22 time=86.31322ms
INFO [07-04|04:43:49.628] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0x993d40660d5719b2893691ad23cfaea52311c276f1df3214cd2f1622c707a16b time=175.872377ms
INFO [07-04|04:43:49.692] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0x12927586494fc53e2607b6dced929c7c06965532051a34b9c9f1946e89fd587d time=64.114057ms
INFO [07-04|04:43:49.694] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0xc15af40acaee27f714029fa548757e26eb9bfdd88280fe57e134cc052cc5a944 time=1.149314ms
INFO [07-04|04:43:49.745] QUORUM-CHECKPOINT                        name=TX-COMPLETED tx=0xe4ba5eefe326dd0f24ed88fbd0678ff7a20d644b3e0e1961b3be5e751b7a2eee time=50.947802ms`

These are some of the error logs from member and validator nodes.

**Comment by rjl493456442** [comment]
Sorry, we are not capable for investigating issues of geth-based forks. Please open the issue in the right repo.
