### ISSUE TITLE
setting interaction between Clef and Ceth via Named Pipes 

### ISSUE THREAD

**Issue by OneOneExe** [ethereum/go-ethereum#27642]
OS: Windows 11

Setting interaction between Clef and Ceth via Named Pipes 

In accordance with the instructions from https://geth.ethereum.org/docs/getting-started
enter commands sequentially:
1. In cmd:
clef --keystore geth-tutorial/keystore --configdir geth-tutorial/clef --chainid 11155111
2. In a separate cmd:
geth --sepolia --datadir geth-tutorial --authrpc.addr localhost --authrpc.port 8551 --authrpc.vhosts localhost --authrpc.jwtsecret geth-tutorial/jwtsecret --http --http.api eth,net --signer=geth-tutorial/clef/clef.ipc --http

Finally Geth reports:
Fatal: Failed to set account manager backends: error connecting to external signer: Invalid pipe address 'geth-tutorial/clef/clef.ipc'.

What am I doing wrong?

**Comment by s1na** [comment]
Hm are you using the Windows subsystem for linux? otherwise you probably need the paths to use `\` instead of `/`.

**Comment by OneOneExe** [comment]
This  instructions https://geth.ethereum.org/docs/getting-started only for linux? I'm beginer. Thanks for comment

**Comment by fjl** [comment]
Named pipe names have to start with `\\.\pipe`. So you could set it to `\\.pipe\clef.ipc` to make it work. Sorry this isn't documented, it is pretty rare that people try to actually use Geth on Windows, even though it is supported.

**Comment by stackkrocket** [comment]
> This instructions https://geth.ethereum.org/docs/getting-started only for linux? I'm beginer. Thanks for comment. i changed "/" to "\ " but: Fatal: Failed to set account manager backends: error connecting to external signer: Invalid pipe address 'geth-tutorial\clef\clef.ipc'.

You coul replace  `--signer=geth-tutorial/clef/clef.ipc`  with `--signer=\\.\pipe\clef.ipc`. I think for some reason, the pipe address provided in the tutorial can no longer be reached. At least, this worked for me. And it makes sense because this `\\.\pipe\clef.ipc`  is the pipe address when you start the clef client.
