### ISSUE TITLE
Error with `--miner.threads` flag in Geth v1.12.0.

### ISSUE THREAD

**Issue by AlirezaEthDev** [ethereum/go-ethereum#27657]
When attempting to run Geth as a signer node for a private Ethereum network using the command 

`geth --datadir C:\Users\...\Local --cache 256 --identity "PrivateEthereum" --networkid 1234 --port 30300 --netrestrict 123.54.123.0/24 --nat extip:123.54.123.24 --ws --allow-insecure-unlock --ws.addr 123.54.123.24 --ws.port 8551 --ws.api eth,net,web3,personal,admin,miner --ws.origins "*" --mine --miner.threads 10 --miner.etherbase <address>`

 with Geth v1.12.0, the following error is thrown: 

"flag provided but not defined: -miner.threads".

#### System information

Geth version: 1.12.0
OS & Version: Windows Server 2019

#### Expected behaviour
The Geth node should start mining with 10 parallel mining threads.

#### Actual behaviour
The error "flag provided but not defined: -miner.threads" is thrown.

#### Steps to reproduce the behaviour

1. Install Geth v1.12.0.
2. Run the command: 
`geth --datadir C:\Users\...\Local --cache 256 --identity "PrivateEthereum" --networkid 1234 --port 30300 --netrestrict 123.54.123.0/24 --nat extip:123.54.123.24 --ws --allow-insecure-unlock --ws.addr 123.54.123.24 --ws.port 8551 --ws.api eth,net,web3,personal,admin,miner --ws.origins "*" --mine --miner.threads 10 --miner.etherbase <address>`

**Comment by lightclient** [comment]
`ethash` mining was removed in v1.12.0. I recommend downgrading to an earlier version of geth.

**Comment by AlirezaEthDev** [comment]
> `ethash` mining was removed in v1.12.0. I recommend downgrading to an earlier version of geth.

Yes, I should do that. Why did Geth core dev team remove it?

**Comment by lightclient** [comment]
Ethereum moved to proof-of-stake last year, it is no longer needed.

**Comment by AlirezaEthDev** [comment]
> Ethereum moved to proof-of-stake last year, it is no longer needed.

So, How can I run a signer node for a private Ethereum?

**Comment by AlirezaEthDev** [comment]
> `ethash` mining was removed in v1.12.0. I recommend downgrading to an earlier version of geth.

After downgrading to version 1.11.4, which was the previous version used without the issue, the same error occurred again.
