### ISSUE TITLE
Add a custom function in the private blockchain

### ISSUE THREAD

**Issue by SlayeR6889** [ethereum/go-ethereum#27656]
I want to add a function required but I am unable to do so

**Comment by s1na** [comment]
We need a bit more information to be able to help you.

I think what you mean is you'd like to add a new method to the API in your own fork of geth. You can take a look for example at `internal/ethapi/api.go` where some of the existing methods are defined. You'd then need to add the new method also to `internal/web3ext/web3ext.go` to have it available in the console.

**Comment by SlayeR6889** [comment]
actually i am trying to make a batch of 25 transactions on the private blockchain and i am unable to add this method in geth
