### ISSUE TITLE
Auto update function

### ISSUE THREAD

**Issue by chenjia404** [ethereum/go-ethereum#27666]
# Rationale

Many administrators often forget to update geth, resulting in version differences and inability to synchronize. I suggest adding 2 parameter optimizations.
-update Update latest stable version from https://github.com/ethereum/go-ethereum/releases , verify Signature.
-auto-update , the parameter is the seconds for regular updates, the default is 86400 * 7, if this function is added, it may take 2 processes.
I suggest that we introduce -update first to help administrators update more conveniently.

# Implementation
First check https://github.com/ethereum/go-ethereum/releases , if there is an update, then download the file and signature form https://gethstore.blob.core.windows.net/builds/, verify the signature, update.

I can implement this feature.

**Comment by holiman** [comment]
We've thought about this from time to time over the years, and generally come to the conclusion that we do not want this. 

- Auto-update means that _we_ are taking executive decisions into people's operations. They might have staking-operations running with a lot of money. We're not comfortable making the call when to update that. 
- All updates do not work seamlessly. If an auto-update goes wrong, and the node fails to start up after an update, an automatic update migth cause the whole geth-fleet to go down _simultaneously_. If we have an incremental manual roll-out, the failure mode is less simultaneous.

**Comment by holiman** [comment]
There are lots of things to consider here, also, a lot of people run via docker. In some ways, docker already provides "manual auto-update", so us adding it explicitly to geth just makes things even more complicated. 

Doing it via docker is something like: 
```
docker stop -t120 geth && docker pull ethereum/client-go:latest && docker start geth
```
