### ISSUE TITLE
Introduce Solution for Pending/Stuck TXs on ETH Network?

### ISSUE THREAD

**Issue by danzee1** [ethereum/go-ethereum#27661]
Dear Team,

Over the years, one issue which is really frustrating but seems like ETH Team has not resolved it and its causing issues for lot of users is about Pending Transactions. 

I will just request the ETH Team to consider introducing any solution for that as Tx just stuck in Mempool due to Low gas fees and remain there for may be even years. Thus not letting the Users to do any activity within his account. 

My Tx on ETH is stuck for more than 25 hours now & funds are stuck. Will be happy If ETH can change this experience?

**Note: Talking about the users who tried to "Cancel" Pending Tx but were not able to Cancel Pending Tx or even replace it.** 

Best Regards,

**Comment by karalabe** [comment]
You can always resend the transaction with higher fees. There's no "stuck" notion. If a tx is too cheap vs other transactions, it will just wait until prices go down enough. If a very long time passes, it could happen that it's flushed out of pools. In both cases, resending it with bumped fees will make it go through.
