### ISSUE TITLE
Private PoA connecting to random public nodes

### ISSUE THREAD

**Issue by petrkr** [ethereum/go-ethereum#27668]
If you create private PoA blockchain by using init genesis and then you are using --netrestrict, by documentation on https://geth.ethereum.org/docs/fundamentals/private-network is written part `With the above setting, Geth will only allow connections from the 172.16.254.0/24 subnet, and will not attempt to connect to other nodes outside of the set IP range.`
But if I will use this --netrestrict, it stops write to console tried peers, but still there are lots of connections on firewall, so I consider this flag does not work, thus it is bug.

#### System information

Geth
Version: 1.12.0-stable
Git Commit: e501b3b05db8e169f67dc78b7b59bc352b3c638d
Git Commit Date: 20230525
Architecture: amd64
Go Version: go1.20.3
Operating System: linux

#### Expected behaviour
Do not make any outgoing connections except addPeer ones (or local perimeter specified by --netrestrict)

#### Actual behaviour
Even --netrestrict is set to private network like 192.168.1.0/24 there are many outgoing connections somewhere to internet on port 30303

#### Steps to reproduce the behaviour
geth init genesis.json
geth --networkid 12345 --netrestrict 192.168.1.0/24 --nat none

check tcpdump / wireshark

**Comment by chenjia404** [comment]
Are other nodes trying to connect to you? This flag is to control the local not to connect to other nodes.

**Comment by petrkr** [comment]
Other nodes can not connect to me, because it's behind NAT and firewall. But local node trying to connect to some external nodes.
But workaround seems to be create config.toml and remove Bootnodes. But still I think flag should stop connecting even to boot nodes, especially if --networkid is specified and there is 99% chance, those stock boot nodes will NOT have that networkid chain

```
[Node.P2P]
BootstrapNodes = []
BootstrapNodesV5 = []
```

**Comment by lightclient** [comment]
It looks like the problematic line is here: https://github.com/ethereum/go-ethereum/blob/af8b138c1a4362bd3c9892ceefec8e4ca2128f58/p2p/discover/table.go#L324

The nursery is essentially the bootnodes. So these nodes are added to the table and then that allows the table to start looking for peers, which is likely the traffic you're seeing.

I'm not sure the proper way to resolve this. Maybe the most straightforward thing to do is to have `netrestrict` check the seed nodes before they're added to the table in the first place.
