### ISSUE TITLE
[POA] Clique.discard seem not working

### ISSUE THREAD

**Issue by anhnh131** [ethereum/go-ethereum#27689]
I try using `clique.discard` API but seems it only removes data in the proposals variable.
It doesn't remove votes in the `tally` of `snapshot`.
Furthermore, after calling the `discard` API, the vote is still counted.

**Comment by karalabe** [comment]
Yes, discard can only affect your own vote going forward. Your node stops voting, but the already cast votes are still accounted. The votes are part of the chain, you can't undo them.

**Comment by anhnh131** [comment]
@karalabe Yes. I got it. 
Btw, when the validator reached a block, it will commit propose (get from proposals variable of this node) to the chain, right? 
Ex with 5 address: (address 1,2,...5) with address 1,2,3 is a validator, and follow these steps:
- address 1,2,3 vote address 4 -> validators (it means they call propose API with auth: true)
- address 2,3,4 vote address 4  from validator -> none (it means auth: false). 
After that, address 4 isn't a validator. But in the chain, we have a proposed vote address 4 -> validators (it is committed by address 1 ). Do you think this is a problem?
