### ISSUE TITLE
Geth crash after syncing

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#2768]
#### System information

Geth version: `1.4.7`
OS & Version: OSX
Commit hash : 9d558f5 (@bas-vk filter branch)

Node crashed after syncing: https://gist.github.com/frozeman/0edc7ce89c3e92052c02cde86829ec18

**Comment by karalabe** [comment]
This was 1.4.8, and the reason we reverted all commits from it. Please update :P
