### ISSUE TITLE
working on private network 

### ISSUE THREAD

**Issue by poonam8077** [ethereum/go-ethereum#27707]
Hii team 
I hope you are doing well
i am facing some issue in private blockchain.i have changed the address prefix like 0x to G1. i successfully create the account address with prefix G1("G11380dd6e02d08970097bba4d813ff6bc97f12d22") ,and i test all the methods of eth worked properly but 
i was facing issue send transaction  so pls seen in the below
eth.getBalance("G11380dD6E02D08970097Bba4d813ff6bc97F12D22")
9.04625697166532776746648320380374280103671755200316906558262375061821325312e+74
get balance method work properly
get block work 

1. eth.sendTransaction({from: "G11380dD6E02D08970097Bba4d813ff6bc97F12D22", to: "G1A65FD60e64D260fBAEDFf354066331acB53FFf7c", value: "0x5f5e100"})
Error: invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go struct field TransactionArgs.value of type *hexutil.Big
	at web3.js:6370:9(45)
	at send (web3.js:5103:63(34))
	at <eval>:1:20(10)
2.  eth.sendTransaction({from: "G11380dD6E02D08970097Bba4d813ff6bc97F12D22", to: "G1A65FD60e64D260fBAEDFf354066331acB53FFf7c", value: "0x" + (0x100000000).toString(16) })
Error: invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go struct field TransactionArgs.value of type *hexutil.Big
	at web3.js:6370:9(45)
	at send (web3.js:5103:63(34))
	at <eval>:1:20(16)

3..eth.sendTransaction({from: "G11380dD6E02D08970097Bba4d813ff6bc97F12D22", to: "G1A65FD60e64D260fBAEDFf354066331acB53FFf7c", value: 100000000})
Error: invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go struct field TransactionArgs.value of type *hexutil.Big
	at web3.js:6370:9(45)
	at send (web3.js:5103:63(34))
	at <eval>:1:20(10)

4. eth.sendTransaction({from: "G11380dD6E02D08970097Bba4d813ff6bc97F12D22", to: "G1A65FD60e64D260fBAEDFf354066331acB53FFf7c", value: 0x100000000})
Error: invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go struct field TransactionArgs.value of type *hexutil.Big
	at web3.js:6370:9(45)
	at send (web3.js:5103:63(34))
	at <eval>:1:20(10)

but i was facing issue in send transaction 
Kindly help me asap 
Thanks and regards
Poonam Singh

**Comment by s1na** [comment]
Hi Poonam. This issue tracker is for the go-ethereum project. If you have made arbitrary changes to the code I'm afraid we cannot help you.

A `0x` prefixed string should work for the value field of `sendTransaction`. See my repro result below:

```terminal
> eth.sendTransaction({ from: eth.accounts[0], to: eth.accounts[0], value: '0x100' })
INFO [07-12|15:19:31.920] Setting new local account                address=0x46f090b09ef646B16e39611AFd415C06380991a2
INFO [07-12|15:19:31.921] Submitted transaction                    hash=0x14b3d8082e04fbe53650303da181304edd00c0f5614f4b90b821cc0d20909836 from=0x46f090b09ef646B16e39611AFd415C06380991a2 nonce=0 recipient=0x46f090b09ef646B16e39611AFd415C06380991a2 value=256
```

**Comment by poonam8077** [comment]
Hii @s1na 

>  eth.sendTransaction({ from: eth.accounts[0], to: eth.accounts[0], value: '0x100' })
Error: invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go struct field TransactionArgs.value of type *hexutil.Big
	at web3.js:6370:9(45)
	at send (web3.js:5103:63(34))
	at <eval>:1:21(16)

>  eth.sendTransaction({ from: eth.accounts[0], to: eth.accounts[0]})
"G13281982153f4ec0587cd2123cbd27684d6f2b7455ebbf0dfd0cc25719c671077"

still i am facing same issue. i was not passing params value,its successfully executed but if i am passing value params its through error
