### ISSUE TITLE
EXTREMELY slow sync

### ISSUE THREAD

**Issue by chaddybox026** [ethereum/go-ethereum#2770]
#### System information

Geth version: `geth version 1.4.9`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Problem

I started my geth without and options or arguments

And I recieve this:

I0701 18:48:51.686644 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/main/.ethereum/chaindata
I0701 18:48:56.572815 ethdb/database.go:169] closed db:/home/main/.ethereum/chaindata
I0701 18:48:56.574293 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/main/.ethereum/chaindata
I0701 18:48:56.700996 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /home/main/.ethereum/dapp
I0701 18:48:56.800111 eth/backend.go:172] Protocol Versions: [63 62 61], Network Id: 1
I0701 18:48:56.800519 eth/backend.go:201] Blockchain DB Version: 3
I0701 18:48:56.804463 core/blockchain.go:206] Last header: #1196934 [db8e19bb…] TD=10292133573541425005
I0701 18:48:56.804509 core/blockchain.go:207] Last block: #1196934 [db8e19bb…] TD=10292133573541425005
I0701 18:48:56.804533 core/blockchain.go:208] Fast block: #1196934 [db8e19bb…] TD=10292133573541425005
I0701 18:48:56.833602 eth/handler.go:110] blockchain not empty, fast sync disabled
I0701 18:48:56.840109 p2p/server.go:313] Starting Server
I0701 18:48:57.053366 p2p/discover/udp.go:217] Listening, enode://0f005eb44bb4364ec02b334c40bc891a012a47ac2552ccfe0a2c0b236283cb9e5ae9b8b1788de5ecb035d63cef47d50bbfbaf927b302a5c30e029f5e4b86c028@[::]:30303
I0701 18:48:57.053601 p2p/server.go:556] Listening on [::]:30303
I0701 18:48:57.054766 node/node.go:296] IPC endpoint opened: /home/main/.ethereum/geth.ipc
I0701 18:50:37.053830 eth/downloader/downloader.go:320] Block synchronisation started
I0701 18:50:40.088185 core/blockchain.go:964] imported 6 block(s) (0 queued 0 ignored) including 5 txs in 1.405163585s. #1196940 [87c57317 / af28ce25]
I0701 18:51:49.094881 core/blockchain.go:964] imported 784 block(s) (0 queued 0 ignored) including 5378 txs in 1m8.994761936s. #1197724 [cebc0e6b / 275c84bc]
I0701 18:55:18.951833 core/blockchain.go:964] imported 2048 block(s) (0 queued 0 ignored) including 9405 txs in 3m29.789288181s. #1199772 [336440c6 / da55b8bb]
I0701 18:56:48.641096 core/blockchain.go:964] imported 2048 block(s) (0 queued 0 ignored) including 10487 txs in 1m29.682694397s. #1201820 [589d69bb / 841ced42]

The blocks load fine but it take and EXTREMELY long time to load. I've downloaded 2048 blocks in a matter of seconds before, but I don't know why its taking so long. I don't know if this a bug or not.

Please help.

**Comment by varunamrutiya** [comment]
Try adding some options like `--cache` , `--lightkdf` , `--maxpeers`  ,`--jitvm` these might improve performance, otherwise download the whole blockchain with `--fast` option will finish in a few hours.

**Comment by karalabe** [comment]
Seems you are on a magnetic drive (HDD), and doing a full sync on that takes a ton of time. Please do a fast sync from scratch and see how that goes:

 * Back up your `chaindata` folder so you don't lose any progress
 * Run `geth --fast`

It should sync very fast.
