### ISSUE TITLE
"panic: invalid transaction v, r, s values" for valid transaction

### ISSUE THREAD

**Issue by ethissue** [ethereum/go-ethereum#27714]
#### System information

Geth version: v1.12.0 as library
CL client & version: -
OS & Version: Linux & macOS
Commit hash : v1.12.0

#### Expected behaviour

A valid transaction stored in a block on the mainnet should be parseable.

#### Actual behaviour

```client.getTransactionByHash``` panics for a valid transaction stored in a block on the mainnet with ```panic: invalid transaction v, r, s values```

Same thing happens for this particular transaction with the popular ethers.js library, [this](https://github.com/ethers-io/ethers.js/issues/4223) issue.

#### Steps to reproduce the behaviour

Complete, ready to run copy-paste code:

```sh
#!/bin/sh

# SET TMP PROJECT PATH
TMP_PATH=/tmp/ethissue

# CREATE CLEAN TMP PROJECT WITH VERSION TO BE TESTED
rm -rf $TMP_PATH
mkdir -p $TMP_PATH
cd $TMP_PATH
go mod init ethissue

# WRITE TEST SCRIPT
cat <<EOF > "${TMP_PATH}/main.go"
package main

import (
  "context"
  "fmt"

  "github.com/ethereum/go-ethereum/common"
  "github.com/ethereum/go-ethereum/core/types"
  "github.com/ethereum/go-ethereum/ethclient"
)

func main() {
  client, _ := ethclient.Dial("https://eth.llamarpc.com")

  // previous transaction in relation to the bad tx (block 100,019)
  goodTxBefore, _, err := client.TransactionByHash(context.Background(), common.HexToHash("0x6d837b8496d4ae6bfad610e6647cc66faa2d1f3676f2fca24174c1c7cc1bb233"))
  if err != nil {
    panic(err)
  }
  sender, err := types.Sender(types.LatestSignerForChainID(goodTxBefore.ChainId()), goodTxBefore)
  if err != nil {
    panic(err)
  }
  fmt.Println(sender)

  // next transaction in relation to the bad tx (block 100,031)
  goodTxAfter, _, err := client.TransactionByHash(context.Background(), common.HexToHash("0x92fd0b59813c1ed4ee485414a9545edfb701fc1e81ed252e00484895637c4a3f"))
  if err != nil {
    panic(err)
  }
  sender, err = types.Sender(types.LatestSignerForChainID(goodTxAfter.ChainId()), goodTxAfter)
  if err != nil {
    panic(err)
  }
  fmt.Println(sender)

  // bad transaction (block 100,023)
  badTxBetween2goodTxes, _, err := client.TransactionByHash(context.Background(), common.HexToHash("0xce8a2163e2563c7fc783371985fff9fd8194d7e27c4be1adb06520ca2e816e9a"))
  if err != nil {
    panic(err)
  }
  sender, err = types.Sender(types.LatestSignerForChainID(badTxBetween2goodTxes.ChainId()), badTxBetween2goodTxes)
  if err != nil {
    panic(err)
  }
  fmt.Println(sender)
}
EOF

# FETCH DEPS
go get

# RUN AND INSPECT OUTPUT
go run "${TMP_PATH}/main.go"

```

#### Backtrace

````
github.com/ethereum/go-ethereum/core/types.recoverPlain (/gopath/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/core/types/transaction_signing.go:564)
github.com/ethereum/go-ethereum/core/types.HomesteadSigner.Sender (/gopath/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/core/types/transaction_signing.go:501)
github.com/ethereum/go-ethereum/core/types.eip2930Signer.Sender (/gopath/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/core/types/transaction_signing.go:335)
github.com/ethereum/go-ethereum/core/types.londonSigner.Sender (/gopath/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/core/types/transaction_signing.go:260)
github.com/ethereum/go-ethereum/core/types.cancunSigner.Sender (/gopath/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/core/types/transaction_signing.go:192)
github.com/ethereum/go-ethereum/core/types.(*cancunSigner).Sender (:1)
github.com/ethereum/go-ethereum/core/types.Sender (/gopath/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/core/types/transaction_signing.go:147)
main.safeBlockArchiver (/project/scraper/safeblockarchiver.go:77)
````

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
Seems your source data is corrupted if both Geth and Ethers complains that it's bad? Please send us the RLP encoded transaction so we may take a look.

**Comment by karalabe** [comment]
Ah, your code is runnable as is, will take a look.

**Comment by karalabe** [comment]
Ok, I now kind of understand where the issue comes from.

`types.LatestSignerForChainID` will create the latest supported signer with the caveat that if you do provide a chain ID, it will be the latest hard fork, and if you don't, it will be the latest that still operated on non-replay protected transactions (Homestead). In either case however, it will never be a Frontier signer.

Now, the quirk is that in Frontier (the initial Ethereum release), there was an ambiguity in the signatures and 2 different signatures could be valid for certain txs. That wasn't really an issue in itself, but it was annoying that the same tx could have 2 hashes based on how it's signed, so the signature scheme was fixed in Homestead to only allow one of the two possible variations.

This specific signature has the "wrong" variation that is valid in Frontier (the phase the chain is in during the inclusion block), but is invalid in Homestead on onward (the signer that LatestSignerForChainID constructs).

Now how to fix this? Well, if you know which block a specific transaction belongs to, you could use `types.MakeSigner`, which will not blindly try to guess a most permissive signer, rather will use the once requested for the specific block.

If you don't know, it's a bit interesting, we'll have to consider whether to swap out the behavior of this method to use the Frontier signer perhaps, but unsure what the implications are, so will get back on that (cc @fjl @holiman).

**Comment by fjl** [comment]
The `TransactionSender` method of ethclient can be used to work around this.

**Comment by ethissue** [comment]
> Ok, I now kind of understand where the issue comes from.
> 
> `types.LatestSignerForChainID` will create the latest supported signer with the caveat that if you do provide a chain ID, it will be the latest hard fork, and if you don't, it will be the latest that still operated on non-replay protected transactions (Homestead). In either case however, it will never be a Frontier signer.
> 
> Now, the quirk is that in Frontier (the initial Ethereum release), there was an ambiguity in the signatures and 2 different signatures could be valid for certain txs. That wasn't really an issue in itself, but it was annoying that the same tx could have 2 hashes based on how it's signed, so the signature scheme was fixed in Homestead to only allow one of the two possible variations.
> 
> This specific signature has the "wrong" variation that is valid in Frontier (the phase the chain is in during the inclusion block), but is invalid in Homestead on onward (the signer that LatestSignerForChainID constructs).
> 
> Now how to fix this? Well, if you know which block a specific transaction belongs to, you could use `types.MakeSigner`, which will not blindly try to guess a most permissive signer, rather will use the one requested for the specific block.
> 
> If you don't know, it's a bit interesting, we'll have to consider whether to swap out the behavior of this method to use the Frontier signer perhaps, but unsure what the implications are, so will get back on that (cc @fjl @holiman).

Thank you for the details @karalabe .

Maybe adding another function like ```types.SenderOfTxInBlock(tx, blockHeight)``` which also takes the blockHeight as a param. Then based on that and the chainID of the TX the sender can be precisely calculated without errors like this, as the correct signer can be determined based on these two params.

**Comment by karalabe** [comment]
> Maybe adding another function like types.SenderOfTxInBlock(tx, blockHeight) which also takes the blockHeight as a param.

That's what `types.MakeSinger` does. It takes the chain config (which contains the fork definitions so it knows what forks happend at which height) and a block number (for pre-merge forks) and a block timestamp (for post-merge forks).

**Comment by samuelmonday699** [comment]
I need everything to done successfully
