### ISSUE TITLE
"Transaction w/ invalid nonce" error from eth_call RPC on develop branch

### ISSUE THREAD

**Issue by tinybike** [ethereum/go-ethereum#2771]
#### System information

Geth version: `1.5.0-unstable-3af101cc`
OS & Version: Ubuntu Linux 14.04
Commit hash : 3af101ccc1f304af5df803608ebdaaeb85eb0c79

#### Expected behaviour
On commit fd4e161497156a5d12fd8712f41574bc7fb20404:
```json
{"jsonrpc":"2.0","id":12,"result":"0x000000000000000000000000000000000000000000000000000000000000000d"}
```

#### Actual behaviour
On latest develop:
```json
{"jsonrpc":"2.0","id":13,"error":{"code":-32000,"message":"Transaction w/ invalid nonce. tx=0  state=1144538)"}}
```

#### Steps to reproduce the behaviour
This happens on the latest develop geth whenever I submit an `eth_call` request.  Here is a simple example (no parameters):
```json
{"id":12,"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0x7c0d52faab596c08f484e3478aebc6205f3f5d8c","to":"0x52af2540e03b0d0b73e3c7843c236e82ed959ac6","data":"0x175c6322","gas":"0x2fd618"},"latest"]}
```

**Comment by Smithgift** [comment]
I can confirm this, as I've ran into the same thing on 1.5.0-unstable (I'm not sure what hash.)

**Comment by readevalprint** [comment]
I also just ran into this on geth `1.5.0-unstable`

**Comment by karalabe** [comment]
@zsfelfoldi Seem your light client API split broke this. Please take a look.
@bas-vk Could you perhaps pinch in on where this error could be?

**Comment by 0mkara** [comment]
I also run into same problem

`Uncaught Error: Transaction w/ invalid nonce. tx=0  state=1)`

```
At .../node_modules/web3/lib/web3/requestmanager.js:61

Error: Transaction w/ invalid nonce. tx=0  state=1)
```

**Comment by petermunnings** [comment]
Getting exactly the same error as 0mkara - same line in requestmanager.js

**Comment by petermunnings** [comment]
Here are the parameters in that method:


data:  
`{ method: 'eth_call',
  params: 
   [ { to: '0x471d0cab1e5103b5f251053af2eda8b2dcc768be',
       data: '0x70a08231000000000000000000000000bd4ad51c3c66ce402bb3b4c3c353303c5df7a96c',
       from: undefined },
     'latest' ],
  callback: undefined }
`

payload:  
`{ jsonrpc: '2.0',
  method: 'eth_call',
  params: 
   [ { to: '0x471d0cab1e5103b5f251053af2eda8b2dcc768be',
       data: '0x70a08231000000000000000000000000bd4ad51c3c66ce402bb3b4c3c353303c5df7a96c',
       from: undefined },
     'latest' ],
  id: 4 }`

result:  
`{ jsonrpc: '2.0',
  id: 4,
  error: 
   { code: -32000,
     message: 'Transaction w/ invalid nonce. tx=0  state=1)' } }`

**Comment by petermunnings** [comment]
for now I've rolled back to 1.4.9 and the problem doesn't exist in that version.

**Comment by karalabe** [comment]
Fixed and merged on develop.
