### ISSUE TITLE
Type 1 and type 2 transactions have `yParity`, not `v`

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/go-ethereum#27727]
https://github.com/ethereum/go-ethereum/blob/34d507215951fb3f4a5983b65e127577989a6db8/internal/ethapi/api.go#L1375

Geth currently is returning transactions that have a `v` value even when that doesn't make sense.  EIP-2930 and EIP-1559 declare a `yParity` property on those transactions which is defined as "The parity (0 for even, 1 for odd) of the y-value of a secp256k1 signature."  `v` is not defined anywhere in either of those EIPs and what one might put in a variable called `v` is incredibly ambiguous as it could be any of:
1. yParity + 27
2. yParity + 35 + 2 * chainId
3. yParity (what I think geth is doing)

While I advocate for fixing the source code to use `yParity` instead of `v` for type 1 and 2 transactions internally so the code is more readable and follows the specification closer, what actually matters here is that the JSON-RPC should be including a `yParity` in any transaction response with a type 1 or type 2 transaction.

For backward compatibility, it seems reasonable to continue to include a `v` value that contains whatever it contains now, with perhaps some plan (or not) to eventually remove it.

**Comment by anti-fjl** [comment]
This is such an important bug report. Why wasn't this found earlier? Would love to fix this ASAP..

**Comment by fjl** [comment]
Go ahead then!

**Comment by anti-fjl** [comment]
Would love to, but I'm off-code on this issue...
