### ISSUE TITLE
Gradual release of Ether after the Hard-fork

### ISSUE THREAD

**Issue by infamousrev** [ethereum/go-ethereum#2772]
One important community discussion point is to determine in what way we should give the DAO token holders back their Ether.

Releasing 11,538,166 Ether all at the same time on the market has never been tested before. However gradual release of funds has been the way miners introduce to the market ever since Ethereum was created.

If we release all the tokens in one big lump sum then we will see a huge and sudden supply shock on the market.

Maybe it would be a better idea if we release the funds very gradually, what if for example we put all the funds in a smart-contract, but limit the withdrawal rate to 5 Ether per newly mined block. That way the supply will be spaced out at the same rate as regular mining supply increase.

The coding required for this should only be one line of code, so it does not introduce any added risks.

This means with 11,538,166 Ether needed to be distributed it will take 2,307,633 blocks, this will take about 374 days, so roughly 1 year.

This would mean that someone with 12000 DAO tokens would be able to claim his 120 Eth back in instalments of about 10 Ether per month, or about 0.3 Ether per day.

For the long term investors among Dao holders this hold will not make any difference, but for the panic sellers it would greatly reduce the selling load.

I think with a release model like this the miners are much more likely to vote in favour of the hardfork because the risk of a supply shock will be migrated.

It will simply be something like:

maxwithdrawal = ((blocknumber-startingblocknumber)x5x(UserEther/11538166))-PreviousWithdrawalbyUser;

so Imagine someone has 120 total Ether in the contract, and tries to withdrawal after 1 month (185142 blocks):

185142x5x(120/11538166)-0 = 9.627630595711658

So the user can withdrawal approximately 10 Ether per month

**Comment by chuckb** [comment]
The idea is laudable, but DTH had 30% of their ether stolen in a matter hours.  To spool out the return of the stolen ether over the course of a year is completely arbitrary.  If this was implemented, I would not support the hard fork (and I am a DTH).  Let's just get this done.  KISS.

**Comment by fjl** [comment]
This is a protocol governance issue which we cannot decide on here.
