### ISSUE TITLE
geth export does not work

### ISSUE THREAD

**Issue by hievan2016** [ethereum/go-ethereum#2773]
This is an re-opened issue, the original post is at https://github.com/ethereum/go-ethereum/issues/2749

System information

        Geth
        Version: 1.4.5-stable-27df30f3
        Protocol Versions: [63 62 61]
        Network Id: 1
        Go Version: go1.5.4
        OS: linux

Expected behaviour

        geth export dumps chain from datadir to filename

Actual behaviour

        /mnt/vdb/ethereum_code/go-ethereum/build/bin/geth export aaa 0 100
        I0628 21:27:58.306040 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/ubuntu/.ethereum/chaindata
        I0628 21:27:58.338974 core/blockchain.go:206] Last header: #0 [d4e56740…] TD=17179869184
        I0628 21:27:58.339041 core/blockchain.go:207] Last block: #0 [d4e56740…] TD=17179869184
        I0628 21:27:58.339059 core/blockchain.go:208] Fast block: #0 [d4e56740…] TD=17179869184
        I0628 21:27:58.339132 cmd/utils/cmd.go:199] Exporting blockchain toaaa
        I0628 21:27:58.339207 core/blockchain.go:401] exporting 101 blocks...
        Fatal: Export error: export failed on #1: not found

        ------>>> specified block range does not work

        ubuntu@VM-14-43-ubuntu:/mnt/vdb/hdchain$ /mnt/vd12jb/ethereum_code/go-ethereum/build/bin/geth export aaa
        I0628 21:29:16.788478 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/ubuntu/.ethereum/chaindata
        I0628 21:29:16.834694 core/blockchain.go:206] Last header: #0 [d4e56740…] TD=17179869184
        I0628 21:29:16.852534 core/blockchain.go:207] Last block: #0 [d4e56740…] TD=17179869184
        I0628 21:29:16.852608 core/blockchain.go:208] Fast block: #0 [d4e56740…] TD=17179869184
        I0628 21:29:16.852700 cmd/utils/cmd.go:185] Exporting blockchain toaaa
        I0628 21:29:16.852788 core/blockchain.go:401] exporting 1 blocks...
        I0628 21:29:16.853113 cmd/utils/cmd.go:194] Exported blockchain toaaa
        Export done in 3.063256msubuntu

        @VM-14-43-ubuntu:/mnt/vdb/hdchain$ ll aaa
        -rwxrwxr-x 1 ubuntu ubuntu 540 Jun 28 21:29 aaa*

        ------>>> if block range is not specified, seems only one block is exported, while there are over 10000 blocks.

        **seems we cannot specify the datadir when running 'geth export', I got error when doing that**

        ./geth export backup 0 100 --datadir /mnt/vdb/hdchain/data
        Incorrect Usage.

        export [arguments...]
        ...

        **There should be some other blocks in the blockchain, I can see them from the console**

        eth.getBlock(1)
        {
        difficulty: 4,
        extraData: "0xd783010405844765746887676f312e352e34856c696e7578",
        gasLimit: 2249600790429697,
        gasUsed: 0,
        hash: "0x64e4340b048ccef5c1af02bce3fd9b9b5173d49e90d7ff797e979004bfe0d624",
        logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        miner: "0xbeea68bdaf616ce3aaa4152e836130c26ff84d0d",
        nonce: "0x4d89933f0101028c",
        number: 1,
        parentHash: "0x94fc65c38695cfbe9904ba8b0eda2581c603b7818a2e2c4a57634aebeb649943",
        receiptRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
        sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
        size: 536,
        stateRoot: "0x9e6e6f29a3294f6529fd05096c460d86345c8246b331b8fa269f9d638e37f159",
        timestamp: 1467532641,
        totalDifficulty: 8,
        transactions: [],
        transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
        uncles: []
        }

Reproduce

        geth export start_block end_block

-------------------------------- Previous comments from karalabe --------------------------------

The logs state that your chain is empty:

        I0628 21:29:16.834694 core/blockchain.go:206] Last header: #0 [d4e56740…] TD=17179869184
        I0628 21:29:16.852534 core/blockchain.go:207] Last block: #0 [d4e56740…] TD=17179869184
        I0628 21:29:16.852608 core/blockchain.go:208] Fast block: #0 [d4e56740…] TD=17179869184

Hence why export can only export the genesis block. There doesn't seem to be anything else in there. Please check that you try to export from the correct data directory.

Closing as works as intended. Please reopen with more information if you believe there still is an issue and not just a slight user (datadir) error.

**Comment by karalabe** [comment]
Please use `./geth  --datadir /mnt/vdb/hdchain/data export backup 0 100`. The datadir option follows `geth`, not the entire command. This should eventually be fixed but it's an oddity of a CLI package we used.

**Comment by hievan2016** [comment]
Thanks Karalade's suggestion, I finally got this work by specifying the --datadir option, and the 'geth export' cannot started when geth instance is running, I have to shutdown geth and then run 'geth export', this is not good for the production system, it's better to support **online expor**t.

**Comment by arjandeboer** [comment]
I have about the same problem. geth outputs last header based on given datadir, but is unable to make the export

geth -datadir F:\ETHEREUM\ETHERDATA\Ethereum\chaindata export blockchaindump

I0920 16:26:41.849082 core/blockchain.go:206] Last header: #2293285 [7d2a2603…] TD=63004693871838862574
I0920 16:26:41.851082 core/blockchain.go:207] Last block: #2293285 [7d2a2603…] TD=63004693871838862574
I0920 16:26:41.856084 core/blockchain.go:208] Fast block: #2293285 [7d2a2603…] TD=63004693871838862574
I0920 16:26:41.861096 cmd/utils/cmd.go:185] Exporting blockchain to c:\csv\beep
I0920 16:26:41.864094 core/blockchain.go:401] exporting 2293286 blocks...
Fatal: Export error: export failed on #1: not found

Fatal: Export error: export failed on #1: not found

**Comment by karalabe** [comment]
The datadir is the entire folder, not the chain data folder. Drop the last element from your path.

**Comment by arjandeboer** [comment]
tnx for your reply, but
geth -datadir C:\Users\Arjan\AppData\Roaming\Ethereum export exportchaindatafile

I tried this already.
output:
I0921 08:20:27.356379 core/blockchain.go:206] Last header: #2294745 [4f1ee483…] TD=63112799212725133700
I0921 08:20:27.359379 core/blockchain.go:207] Last block: #2294745 [4f1ee483…] TD=63112799212725133700
I0921 08:20:27.362381 core/blockchain.go:208] Fast block: #2294745 [4f1ee483…] TD=63112799212725133700
I0921 08:20:27.366381 cmd/utils/cmd.go:185] Exporting blockchain to exportchaindata21092016
I0921 08:20:27.370384 core/blockchain.go:401] exporting 2294746 blocks...
Fatal: Export error: export failed on #1: not found

Fatal: Export error: export failed on #1: not found

On testnet, when i run export -testnet, even without specifying the datadir the export does succeed.

**Comment by balajipachai** [comment]
This worked for me:

```
geth export --datadir "directory" --syncmode "full" --cache 2048 backup.rlp fromBlockNumber toBlockNumber

rm directory/geth

geth --datadir "directory" init genesis.json

geth import backup.rlp --datadir "directory" --syncmode "full" --cache 2048
```

- directory : The directory where geth and key are located after Genesis is initialized
- fromBlockNumber: Backup will start from this block number
- toBlockNumber: Backup will be taken up this block

Example:

```
geth export --datadir "test" --syncmode "full" --cache 2048 backup.rlp 0 30100

rm test/geth

geth --datadir "test" init genesis.json

geth import backup.rlp --datadir "test" --syncmode "full" --cache 2048

```

[Reference](https://www.programmersought.com/article/92704972607/)
