### ISSUE TITLE
geth Nvidia GPU support without OpenCL

### ISSUE THREAD

**Issue by satindergrewal** [ethereum/go-ethereum#2774]
#### System information

Device: [NVIDIA TX1, with A57 ARM64 chip](http://www.nvidia.com/object/jetson-tx1-module.html)
Geth version:
```shell
ubuntu@tegra-ubuntu:~/go-ethereum/build/bin$ ./geth version
Geth
Version: 1.4.9-stable-b7e3dfc5
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=/home/ubuntu/go
GOROOT=/home/ubuntu/goroot
```
OS & Version: Linux, Ubuntu 14.04 LTS, ARM64
```shell$ uname -a
Linux tegra-ubuntu 3.10.96-tegra #1 SMP PREEMPT Tue May 17 16:29:05 PDT 2016 aarch64 aarch64 aarch64 GNU/Linux```
Commit hash : (if `develop`)

#### Expected behaviour


#### Actual behaviour
```shell
ubuntu@tegra-ubuntu:~/go-ethereum/build/bin$ ./geth gpuinfo
=============================================
============ OpenCL Device Info =============
=============================================
Plaform error (check your OpenCL installation): cl: error -1001
```

#### Backtrace

````
[backtrace]
````

I made a descriptive post on my efforts to install & troubleshoot geth issues in relation to test geth GPU mining abilities on Nvidia TX1 at [Ethereum StackExchange post](http://ethereum.stackexchange.com/questions/6771/geth-opencl-disabled-set-go-opencl-and-re-build-to-enable).

Can it be possible to enable Geth to mine without having OpenCL on system? If it's not currently supported, can other libs be supported to enable mining through them like OpenGL, CUDA etc.?

Because I found OpenCL support is not made available for NVIDIA TX1 and TK1 boards. I'm not sure about other boards or platforms, but just wondering if the same could be possible in case there's no possibility to have OpenCL running on system and an alternative is supported.

Ref links about OpenCL for TX1 and TK1. [Link1](https://devtalk.nvidia.com/default/topic/899013/jetson-tx1/tegra-x1-opencl-support/), [Link2](https://devtalk.nvidia.com/default/topic/935508/opencl-support-in-jetson-tk1-and-jetson-tx1-development-board/)

Thanks

**Comment by karalabe** [comment]
The official Ethereum [ethash](https://github.com/ethereum/ethash) implementation only supports OpenCL based GPU mining. As Ethereum targets switching from PoW mining to PoS, there's not much incentive for the Foundation to expend on further fine tuning the mining algos, especially as it's beneficial to miners only, not the ecosystem in general.

However, as far as I know miners have indeed picked up the task to maintain their own miner implementation that has all the bells and whistles they themselves need, porting cpp-ethereum over to CUDA too https://github.com/Genoil/cpp-ethereum. You might want to check out this project.

Lastly given that C++ will probably outperform Go on pure miner hashrate, and that miners already operate using Geth for the node and `ethminer` for the number cruncher, there's little value to even maintain the GPU miner in the Geth codebase, as there's noone to maintain it. We'll always retain the CPU miner as it's needed for private networks, but a private net doesn't need GPU mining and the mainnet already has better alternatives.
