### ISSUE TITLE
how to setup enode with domain?

### ISSUE THREAD

**Issue by haidarabdillah** [ethereum/go-ethereum#27769]
i want to use this 
`"enode://c35c3ec90a8a51fd5703594c6303382f3ae6b2ecb9589bab2c04b3794f2bc3fc2631dabb0c08af795787a6c004d8f532230ae6e9925cbbefb0b28b79295d615f@mydomain.dev.example.net:30301"`

like on hyperledger besu, in besu i use --Xdns-enabled true, is this feature available on private ethereum ? and how to seup it

**Comment by jsvisa** [comment]
```bash
geth --help |grep node

    --bootnodes value
          Comma separated enode URLs for P2P discovery bootstrap
```

**Comment by haidarabdillah** [comment]
i mean in params/botnodes.go
or in private 
`./geth --datadir node1 --port 30306 --bootnodes enode://f7aba85ba369923bffd3438b4c8fde6b1f02b1c23ea0aac825ed7eac38e6230e5cadcf868e73b0e28710f4c9f685ca71a86a4911461637ae9ab2bd852939b77f@127.0.0.1:0?discport=30305  --networkid 123454321 --unlock 0xC1B2c0dFD381e6aC08f34816172d6343Decbb12b --password node1/password.txt --authrpc.port 8551`

when i change to domain i got this error 

```
CRIT [07-25|14:51:12.288] Bootstrap URL invalid    enode=enrtree://xxx@domain.example err="missing 'enr:' prefix for base64-encoded record"
```

**Comment by jsvisa** [comment]
AFAIK, geth uses the system's DNS resolver, seems you pass `mydomain.dev.example.net` to geth's cmdline, and got a `no such host` error? If so, seems your system can't resolve the DNS record of `mydomain.dev.example.net`, you need to config a valid DNS resolve(eg: in `/etc/resolv.conf`)

**Comment by karalabe** [comment]
I can use for example www.google.com as the domain, so DNS resolution works. You'll need to ensure that your machine can resolve the domain itself before asking Geth to do it. 

Try `nslookup` and see what it says.

**Comment by haidarabdillah** [comment]
CRIT [07-25|19:55:42.292] Bootstrap URL invalid  enode=enode://ccccccc@google.com err="invalid port"

tried using google.com without port is error invalid port? after added port is succces, so we can use port forwading? usually im use nginx to reverse proxy (in bitcoin rpc)
