### ISSUE TITLE
miner.start() is not working 

### ISSUE THREAD

**Issue by HEGADE** [ethereum/go-ethereum#27761]
#### System information

Geth version: ` v1.12.0`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version:  Linux-ubuntu

#### Behavior 

trying to run the miner.start() but it gave me the error saying "Error: too many arguments, want at most 0",
I have given 0 arguments in miner.start()

#### Steps to reproduce the behaviour
just try to execute the miner.start() inside the console

**Comment by lightclient** [comment]
Duplicate #27607.
