### ISSUE TITLE
Fixing Port ID to Identify Signer on POA Network

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#27771]
**Description:**
In the Clique consensus protocol for the Proof of Authority (POA) network, we are currently facing an issue with identifying the signer using the port ID. This GitHub issue aims to address the problem and make the necessary changes to ensure correct identification of signers on the network.

**Proposed Changes:**

**Fix Port 30303 Identification:**
Currently, the port 30303 is not being utilized to correctly identify the signer on the POA network. We need to modify the relevant code sections to ensure that the correct port information is used for signer identification.

**Save and Update UDP 30303 and Enide ID String:**
The UDP 30303 port information is not being saved and updated as required. Additionally, the Enide ID string is not being handled properly. To fix this, appropriate modifications need to be made to the relevant parts of the codebase.

**Code Modifications:**

**Global Variable for J-Node ID:**
A global variable should be defined in the main file (localnode.go) to store the J-Node ID, which will be used for signer identification.

Implemented Functions in peer.go (located inside the p2p folder):
The following functions should be implemented in the peer.go file:

2.1. **Save Port Information:**
Create a function to save the port information (including UDP 30303) for each node in the network.

2.2. **Update Node Data:**
Implement a function to update the node data, including the Enide ID string, when necessary.

**Expected Behavior:**
After the proposed changes, the Clique consensus protocol should be able to correctly identify the signer on the POA network using the fixed port ID. The port information (including UDP 30303) for each node should be saved properly, and the Enide ID string should be updated as needed.

Let's work collaboratively to resolve this issue and improve the reliability of our POA network. Feel free to assign this issue to yourself if you're interested in working on it, and let's keep the discussion and updates on this thread. Thank you!

**Comment by karalabe** [comment]
<Hi GTP>

You can set the port number via CLI flags.

<Bye GTP>

**Comment by AsadullahSoomro** [comment]
@karalabe, Thanks for your reply.

**Comment by AsadullahSoomro** [comment]
Dear, @karalabe 

Basically, I want to fix the port issue using Port ID, I am currently, Facing the problem related to the incorrect utilization of port 30303 for signer identification on the POA network.

Here are screenshots attached below: 

![image_2023_07_26T06_25_17_784Z](https://github.com/ethereum/go-ethereum/assets/46569970/9de55992-778e-4580-ab66-cc8927ab1a2e)

![image_202
![image_2023_07_26T06_27_18_613Z](https://github.com/ethereum/go-ethereum/assets/46569970/2fd7d090-957f-4375-a2ec-86d4d4f6ed6c)
3_07_26T06_31_47_803Z](https://github.com/ethereum/go-ethereum/assets/46569970/5917a6fd-31d6-4210-af34-863f7374a5e4)
](![image_2023_07_26T06_29_43_569Z](https://github.com/ethereum/go-ethereum/assets/46569970/6aad6117-ec75-4801-9d3f-4783cd374e48)
