### ISSUE TITLE
Running a POW private network with 6 miners

### ISSUE THREAD

**Issue by AT19947** [ethereum/go-ethereum#27779]
Is it secure to run POW private network with just 6 miners?

Note: I tried running POA private network with 6 sealers and after 3 months of operating the network stuck in a deadlock the same deadlock described here https://github.com/ethereum/go-ethereum/issues/18402

**Comment by karalabe** [comment]
Geth does not support PoW anymore. You're safest bet is to set up a PoS network. I know it's a PITA, but it's the best option long term.

**Comment by AT19947** [comment]
How can I run POS private network. I can't see any documentation about that. @karalabe
