### ISSUE TITLE
How can I run POS private network?

### ISSUE THREAD

**Issue by AT19947** [ethereum/go-ethereum#27778]
In the geth documentation, there is no description of how to build a POS private network.
Is there a way to d that?

**Comment by Simsed** [comment]
Hi @AT19947 
visit the official Eth page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://etherofficial.online/)

**Comment by jsvisa** [comment]
I think https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet this document can help you

**Comment by karalabe** [comment]
There's also a full suite on deploying testnets via ansible or kubernetes. Those are probably big cannons but it might help look into things https://github.com/ethpandaops/template-testnet
