### ISSUE TITLE
legacy transaction is not supported

### ISSUE THREAD

**Issue by jrlee1204** [ethereum/go-ethereum#27775]
**code**

```
tx := types.NewTransaction(nonce, contractAddress, amount, gasLimit, gasPrice, data)
chainID, err := client.NetworkID(context.Background())
signedTx, err := types.SignTx(tx, types.LatestSignerForChainID(chainID), privateKey)
err = client.SendTransaction(context.Background(), signedTx)
```

when I use this code call contract, it's error: legacy transaction is not supported

**Comment by karalabe** [comment]
What node are you connecting to? Which of the many lines above fail?

Such an error message does not exist in Geth (please copy paste the actual error message if different). Perhaps some other node you're connecting to is rejecting the transaction?

**Comment by jrlee1204** [comment]
> What node are you connecting to? Which of the many lines above fail?
> 
> Such an error message does not exist in Geth (please copy paste the actual error message if different). Perhaps some other node you're connecting to is rejecting the transaction?

I connecting to filecoin test network, but now I have solved it, Replace types.NewTx with types.NewTransaction.

thanks

**Comment by Yaadyindia** [comment]
Hey how u fix the error ???  We face same issue 
![Screenshot_20240320_200020_Orbit Vault](https://github.com/ethereum/go-ethereum/assets/95498045/7a094c13-349d-4369-996e-642a48add110)

**Comment by jrlee1204** [comment]
> Hey how u fix the error ??? We face same issue ![Screenshot_20240320_200020_Orbit Vault](https://private-user-images.githubusercontent.com/95498045/314545108-7a094c13-349d-4369-996e-642a48add110.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NDY0ODIsIm5iZiI6MTcxMDk0NjE4MiwicGF0aCI6Ii85NTQ5ODA0NS8zMTQ1NDUxMDgtN2EwOTRjMTMtMzQ5ZC00MzY5LTk5NmUtNjQyYTQ4YWRkMTEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDE0NDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MTU2Zjk0NTQzZWFiOTEzYWYyYjdhZGIwMWZjMDUzNDA5ZjU0MGZiYThlYjBiMDYyODBlMjc1NDllOGE3ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KDF086FRQPQE654OsB1eq5qwiC-tQ-sRICVfub6u2Jc)

I replace types.NewTx with types.NewTransaction solved this error, you can try it.

**Comment by Yaadyindia** [comment]
Bbro please can u elaborate?? We developed a filechain wallet app but getting that error

**Comment by Thomassdevv** [comment]
> > What node are you connecting to? Which of the many lines above fail?
> > Such an error message does not exist in Geth (please copy paste the actual error message if different). Perhaps some other node you're connecting to is rejecting the transaction?
> 
> I connecting to filecoin test network, but now I have solved it, Replace types.NewTx with types.NewTransaction.
> 
> thanks

I want you to help us in our Android app...
Can you please help us...
How to connect with you other than GitHub ?
