### ISSUE TITLE
What is the impact of executing debug.setHead on the transactions?

### ISSUE THREAD

**Issue by AT19947** [ethereum/go-ethereum#27773]
The blockchain reaches block 50 and it's containing a transaction, If I execute this debug.setHead(49) What will happen to the transaction that is mined in block 50?

**Comment by lightclient** [comment]
It will delete those transactions from disk.

**Comment by akefhabbal-qu** [comment]
Shouldn't it roll back the transactions form the block 50? Wouldn't it affect the state?

**Comment by lightclient** [comment]
The state is reverted to the state at block 49.

**Comment by akefhabbal-qu** [comment]
What happen to the transactions in block 50? @lightclient

**Comment by jsvisa** [comment]
as the block were deleted, so txs also removed.
