### ISSUE TITLE
Fixing Port Issues in Private Blockchain Nodes: Troubleshooting Dynamic Port Allocation for Signer Node Identification

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#27777]
Dear, @karalabe,

I'm currently facing an issue with the port configuration. Whenever I run the other node privately, the port tends to change. Sometimes, the local port changes, and other times, the remote port changes automatically. I've attempted using the '--nat=extip' command, but the issue persists. Can you please help me understand the root cause of this problem?

The IP remains the same, but the port keeps changing. I've noticed that the port number varies, and my objective is to differentiate between the signer node and other peer nodes. The IP and port change occasionally, making it challenging to identify the signer node accurately. Even the ID changes after the node's initial setup, which further complicates the matter.

I suspect that the Go-Lang package used in the 'Geth initialize' process might be employing some mechanism that dynamically changes the ports. Alternatively, this could be a policy of dynamic port allocation that isn't explicitly defined in the code. I've also tried using the built-in '--nat=extip' code, but the issue remains unresolved. Essentially, my goal is to initialize the signer node when setting up the blockchain network, but the changing IP and port numbers are causing difficulties.

I've observed that the port changes for every number and isn't specific to one node. Even when I view the port, it occasionally changes for other nodes as well. As of now, I'm struggling to correctly identify the signer node, mainly focusing on the ID and port. While the IP address (127.0.0.1) remains constant, the changing port number poses a challenge in determining the signer node.

Here are screenshots attached below:

![image_2023_07_26T06_31_47_803Z](https://github.com/ethereum/go-ethereum/assets/46569970/f80df7cb-aeea-4bd7-9dd9-412b7d44324a)
![image_2023_07_26T06_29_43_569Z](https://github.com/ethereum/go-ethereum/assets/46569970/3c61e1c7-ca49-46b4-ac65-b45cdee6b84f)
![image_2023_07_26T06_27_18_613Z](https://github.com/ethereum/go-ethereum/assets/46569970/c76148eb-5147-40aa-bb4e-1230cdd80944)
![image_2023_07_26T06_25_17_784Z](https://github.com/ethereum/go-ethereum/assets/46569970/e93d6d49-c012-49a0-8d3b-824960a851a9)

**Comment by karalabe** [comment]
That's how TCP works. You can set the listener port number where other peers will connect to. Every single TCP (network) connection will have a random different outbound port number allocated by the OS. You cannot set the outbound port number because each TCP connection will need it's own one.

**Comment by AsadullahSoomro** [comment]
@karalabe, Thanks for your reply.
