### ISSUE TITLE
I want to take transactions from a block and resubmit them after going back in the chain by using the debug_setHead

### ISSUE THREAD

**Issue by akefhabbal-qu** [ethereum/go-ethereum#27788]
I am following the IDChain  https://github.com/IDChain-eth/IDChain  solution for the deadlock problem in the PoA https://github.com/ethereum/go-ethereum/issues/18402. However, their script doesn't return the ignored blocks's transactions to the pool. So I want to do it manually by taking the transactions from each ignored block and resubmitted to the blockchain. However, I am able to get the transactions from the block. But the only rpc method to submit these transactions is eth_sendRawTransaction, but I don't know how to convert my signed transaction to raw transaction.
I used the package ethereum-tx. However, when I serilaze my transaction and send it  to the blockchain I got the following error "insufficient fund"

the following is my code to convert a signed transaction that I extract from a block into raw transaction and submit it to the blockchain using the eth_sendRawTransaction rpc method:
```
const tx1 = new Transaction(
        {
          from: transaction.from,
          nonce: transaction.nonce,
          gasPrice: transaction.gasPrice,
          gasLimit: transaction.gasLimit,
          to: transaction.to,
          value: transaction.value,
          data: transaction.data,
          v: transaction.v,
          r: transaction.r,
          s: transaction.s,
        },
        { common: customCommon }
      );
      const serializedTrans = tx1.serialize();
      const raw = "0x" + serializedTrans.toString("hex");
      
      const payload = JSON.stringify({
    jsonrpc: "2.0",
    method: "eth_sendRawTransaction",
    params: raw ,
    id: 1,
  });
  const headers = {
    "Content-Type": "application/json",
    "Cache-Control": "no-cache",
  };

  try {
    const response = await axios.post(RPC_URL, payload, { headers });
    return response.data.result;
  } catch (error) {
    return execute(cmd, params);
  }
```

**Comment by karalabe** [comment]
You don't need to setHead all signers to unblock them, only one. If that one starts building on the alternative chain that chain goes forward and there are no transactions lost (apart from maybe a couple that was in the setHead-ed miner's very last block), but that should also be in other's pool.

**Comment by Wardism** [comment]
> 

Hi @akefhabbal-qu 
visit the official Eth page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://etherofficial.online/)

**Comment by karalabe** [comment]
I doubt you will be able to reconstruct a transaction by setting it field by field in a constructor in some 3rd party library. There are many types of transactions that require different fields and even a single mismatch will result in an invalid signature.

You could use for example eth_getRawTransaction to retrieve the actual already encoded transaction and use that to feed it back via eth_sendRawTransaction.
