### ISSUE TITLE
Error during sync - pebble: keys must be added in strictly increasing order

### ISSUE THREAD

**Issue by dimsome** [ethereum/go-ethereum#27782]
#### System information

Geth version: v1.12.0
CL client & version: Lighthouse 4.3.0
OS & Version:  Ubuntu 22.04.2 LTS

#### Expected behaviour

Sync normal with no error

#### Actual behaviour

During syncing of Geth received the following error: `keys must be added in strictly increasing order`

Becomes unresponsive to shuwdown requests. 

#### Steps to reproduce the behaviour

No Idea how to reproduce and if syncing from genesis would result in the same. 

#### Backtrace

````
geth_1              | 2023/07/26 10:16:31 background error: pebble: keys must be added in strictly increasing order: o7$\xf3\x95\x00\xf0\xa0\xa8\xae\x8b\xd2\x06s\xc6\xc6\x15=\xf9 \x82\x03,\x93\x91\xc7\xec\x030\xd8<\xd9-Q$\x1d\x1fk\xc3JT\xac\x89p\x1a\x02\xda\x80\x16\xbb/\xbd\xa0\xfa\xe0\x0a\xb4(\xc7K\xcca\xb2\x1a\x1f#2915913148,SET, o7$\xf3\x95\x00\xf0\xa0\xa8\xae\x8b\xd2\x06s\xc6\xc6\x15=\xf9 \x82\x03,\x93\x91\xc7\xec\x030\xd8<\xd9-A$%\xac@L\x1a\x13\xefU\xa6>\xc1\x18S\xaa\x17Jm\xcd\xe0Lh)\xd5\xc3\x16r\x8b2\xd4y#2915913149,SET
````

**Comment by Simsed** [comment]
Hi @dimsome 
visit the official Eth page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://etherofficial.online/)

**Comment by rjl493456442** [comment]
It's an error from Pebble

> if syncing from genesis would result in the same.

What do you mean result will be same, the same error will be found in case of a fresh new sync?

**Comment by karalabe** [comment]
We'll try to update our Pebble dependency, it's half a year old anyway, hopefully that will help in the future. Definitely not something originating from Geth.

**Comment by potuz** [comment]
Being hit by the same error trying to sync a node from ancient. The node becomes unresposive and times out on the Engine API so it evens blocks the beacon client from syncing.

**Comment by holiman** [comment]
This issue is stale, and we've since then upgraded pebble
