### ISSUE TITLE
geth t8n support cancun fork

### ISSUE THREAD

**Issue by winsvega** [ethereum/go-ethereum#27783]
it looks like geth t8n still does not calculate 

in t8n reponse file 
"currentExcessDataGas" 
"currentDataGasUsed"
in env t8n file
"parentExcessDataGas" (to calculate the formula) or "currentExcessDataGas" (to set the value without formula)
"parentDataGasUsed"  (to calculate the formula) or "currentDataGasUsed" (to set the value without formula)

**Comment by holiman** [comment]
Mostly implemented in https://github.com/ethereum/go-ethereum/pull/27796. However...
Should `currentExcessDataGas` be the value that was used during this block (that is, given as input or calculated using the parent values), or should it be the values to be used for a future child block?

**Comment by holiman** [comment]
Please check it out, I think it behaves logically now
