### ISSUE TITLE
how to add more information about the network 

### ISSUE THREAD

**Issue by HEGADE** [ethereum/go-ethereum#27795]
hi, i want to add the network name, and network currency symbol for the geth node, so if use the corresponding RPC URL in Metamask, the network name and currency symbol should be gathered from the RPC URL.
thank you

**Comment by jsvisa** [comment]
AFAIK, this is metamask's feature, not geth or other ethereum clients

**Comment by HEGADE** [comment]
> 

Does this mean, i can't set network name using geth?

**Comment by karalabe** [comment]
Yes

**Comment by HEGADE** [comment]
if we can't set the currency symbol how would a user know the default token symbol of the network or do we need to send the information to Metamask, saying this is the default token for this network
