### ISSUE TITLE
crypto: manipulated signature still pass the verification 

### ISSUE THREAD

**Issue by xumy29** [ethereum/go-ethereum#27802]
#### System information

Go-ethereum version: v1.10.17
OS & Version: macOS Monterey 12.4

#### Code
```go
package main

import (
	"fmt"

	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/crypto"
)

var (
	privateKeyHex string = "0406fd4b37b0fef67a4cd1ca447452a0fbe81ec972e8437c2d278614295d2412"
	testmsg              = hexutil.MustDecode("0xce0677bb30baa8cf067c88db9811f4333d131bf8bcf12fe7065d211dce971008")
)

func SignHash(hash []byte) []byte {
	privateKey, err := crypto.HexToECDSA(privateKeyHex)
	if err != nil {
		fmt.Println("Error converting private key:", err)
		return []byte{}
	}
	sig, err := crypto.Sign(hash, privateKey)
	if err != nil {
		fmt.Println("Error sign: ", err)
		return []byte{}
	}

	return sig
}

func VerifySignature(msgHash []byte, sig []byte) bool {
	// manipulate sig for test
	fmt.Printf("original sig: %v\n", sig)
	sig[5] = 0
	sig[35] = 0
	sig[40] = 0
	sig[44] = 0
	fmt.Printf("manipulated sig: %v\n", sig)

	// recover pubkey
	pubKeyBytes, err := crypto.Ecrecover(msgHash, sig)
	if err != nil {
		fmt.Printf("ecrecover err: %v\n", err)
	}

	valid := crypto.VerifySignature(pubKeyBytes, msgHash, sig[:len(sig)-1])

	return valid
}

func main() {
	sig := SignHash(testmsg)
	if VerifySignature(testmsg, sig) {
		fmt.Printf("verify pass.\n")
	} else {
		fmt.Printf("verify doesn't pass.\n")
	}
}

```
#### Expected behaviour
When manipulating several bytes of the signature, the verification should not pass.

#### Actual behaviour
The verification still pass.

#### Steps to reproduce the behaviour
run the code.

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by jwasinger** [comment]
When you manipulate the signature like this, the result of ecrecover is not the same public key as the one that corresponds to the original signature.

**Comment by xumy29** [comment]
@jwasinger Thanks for reply. Yeah I know that the pubkey will change. 

My confusion is why `crypto.VerifySignature` still returns true. Is it correct that when `crypto.Ecrecover` returns no error, `crypto.VerifySignature` will always return true? If it is, there's no need to call `crypto.VerifySignature`.

**Comment by xumy29** [comment]
I think I‘ve figured it out. `crypto.Ecrecover` is called when the expected pubkey is unknown and expected address known, while `crypto.VerifySignature` is called when one wants to verify if the provided pubkey signed the msgHash.
