### ISSUE TITLE
make geth  error  error: 'for' loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by 953446** [ethereum/go-ethereum#27807]
#### System information

Geth version: `V1.12.0`
CL client & version: [[e.g. lighthouse/nimCL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0bus/prysm@v1.0.0]()](https://github.com/ethereum/go-ethereum/releases/tag/v1.12.0)
OS & Version: Linux centos7.9
golang Version : 1.20.4

![image](https://github.com/ethereum/go-ethereum/assets/128539227/73df79e0-8e65-4031-bb24-a26185254627)

**Comment by jsvisa** [comment]
Seems like your gcc/g++ version is to low(maybe prior to 5.0.0). Could you please check it

**Comment by MAJKYTHEBOSS** [comment]
> Seems like your gcc/g++ version is to low(maybe prior to 5.0.0). Could you please check it

Nah it was just originally mine and stolen of my phone old Samsung 12A

**Comment by 953446** [comment]
> 

updata to gcc12  ok
