### ISSUE TITLE
Tech debt: drop GPU miner support

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#2780]
Reasons:
- GPU mining needs OpenCL libraries, so it requires custom local builds and isn't portable.
- Mining in general is more suited to C++, where it's also arguable easier (Geth + ethminer).
- There's already a semi-established project for mining https://github.com/Genoil/cpp-ethereum.
- Private networks can be run on CPU mining, no need for the GPU complexity and mess.
- There's no one to maintain the OpenCL miner so if anything breaks, it's a waste to fix it.
- The OpenCL dependency makes a mess of the Go vendoring as it adds weird build tags.

**Comment by fjl** [comment]
GPU mining is removed in 1.5.0.
