### ISSUE TITLE
Is the synchronization speed of geth related to the single-core performance of the CPU?

### ISSUE THREAD

**Issue by chenlaoyao0523** [ethereum/go-ethereum#27809]
I have two machines, one CPU is 5900HX, and the other is E2683. I found that the synchronization speed of 5900HX is almost three times that of E2683.

**Comment by chenlaoyao0523** [comment]
5900HX: 8 core
E2683: 16 core, but just use 4-6 core

**Comment by jsvisa** [comment]
Which synchronization mode are you running? If you are syncing with `full`(`--syncmode=full`), then the transactions were executed in serial, so the higher the cpu frequency, the faster the synchronization

**Comment by chenlaoyao0523** [comment]
snap

**Comment by karalabe** [comment]
Snap sync is mostly network latency and bandwidth bound. Whilst there is some CPU limitation too on receipt decoding (quite heavy), it should not be a too determining factor on overall sync time.

**Comment by chenlaoyao0523** [comment]
This is also where I am confused. but, the CPU single-core performance is indeed quite different. After all, one is 5900HX and the other is E2683. There is a 2-fold difference in performance.

**Comment by chenlaoyao0523** [comment]
My two machines are under the same router, there should be no difference in bandwidth

**Comment by chenlaoyao0523** [comment]
@karalabe

**Comment by chenlaoyao0523** [comment]
Or is there any test tool to test it? @karalabe
