### ISSUE TITLE
Allow state override on eth_estimateGas

### ISSUE THREAD

**Issue by antonydenyer** [ethereum/go-ethereum#27800]
# Rationale

Currently, you can not perform an `eth_estimateGas` on something that isn't in the 'correct' state as the evm will, correctly, return an error. For example, on an erc20 you may wish to send an `approve` followed by a `transfer` call. You can estimate gas for the `approve` but not the `transfer`. 

# Implementation

Add an additional parameter to the end of the request in the same way `eth_call` does. 
Are you willing to implement this feature? Yes

**Comment by s1na** [comment]
Hi @antonydenyer. I think it makes sense to add these overrides, and probably the block overrides which have recently been added to `eth_call` as well.

You indicated you're willing to implement this feature. I'd personally welcome your contribution and can gladly review it.

**Comment by ftarantuviez** [comment]
I think this should be added to the documentation too?

https://geth.ethereum.org/docs/interacting-with-geth/rpc/objects#state-override-set

Right now only considers `eth_call` and `eth_simulateV1`:

```
The state override set is an optional address-to-state mapping, used in eth_call and eth_simulateV1, where each entry specifies some state to be ephemerally overridden prior to executing the call. Each address maps to an object containing:
```

**Comment by s1na** [comment]
@ftarantuviez PRs are welcome
