### ISSUE TITLE
Client fails to parse zkSync blocks

### ISSUE THREAD

**Issue by DanielSolomon** [ethereum/go-ethereum#27817]
#### System information

Geth version: `v1.2.0`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: OSX Ventura 13.4.1 (c) 
Commit hash : -

#### Expected behaviour

Being able to parse blocks using go-ethereum client on zkSync chain.

#### Actual behaviour

Failed to parse blocks using go-ethereum client on zkSync chain.

#### Steps to reproduce the behaviour

A short Golang program to reproduce the issue:
```
package main

import (
	"context"
	"fmt"
	"math/big"

	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	ctx := context.Background()
	blockNumber := big.NewInt(9966250)

	client, err := ethclient.Dial("https://mainnet.era.zksync.io/")
	if err != nil {
		fmt.Printf("Error dialing: %v\n", err)
		return
	}

	block, err := client.BlockByNumber(ctx, blockNumber)
	if err != nil {
		fmt.Printf("Error getting block: %v\n", err)
		return
	}

	fmt.Printf("Got block with %d transactions.\n", len(block.Transactions()))
}
```
* Running go run main.go, outputs: Error getting block: `invalid transaction v, r, s values`.

**Comment by karalabe** [comment]
I would assume zkSync transactions are different than Ethereum ones?

**Comment by DanielSolomon** [comment]
Ack, thought they preserved compatibility with Eth blocks, sorry for wasting your time.
