### ISSUE TITLE
 Retrieving Full Hash Values from Log Messages

### ISSUE THREAD

**Issue by achakhalyan** [ethereum/go-ethereum#27852]
Dear Geth Support Team,

I am working on a project that requires monitoring specific log entries related to rejected transactions in a Geth node. While analyzing the logs, I noticed that the hash values are truncated, and I am only able to retrieve a part of the hash` (e.g., "e8cb6a..fc4198").`

My current use case demands the full hash value for further processing and analysis. I have explored the available verbosity levels and other configurations but have not found a way to change the log format to include the complete hash values.

Here is an example log entry that I am working with:
`TRACE[08-01|10:07:12.751] Possible uncle rejected hash=e8cb6a..fc4198 reason="ignore uncle for beacon block"`

Could you please advise if there is an existing configuration option or method to include the full hash values in the log messages? If not, would it be possible to consider this as a feature request or provide guidance on how to achieve this requirement?

I appreciate your assistance and look forward to hearing from you. Please let me know if you need any additional information or context to assist with this inquiry.

Best regards,
Armen
armen@gap600.com

**Comment by karalabe** [comment]
The code for the log format is here: https://github.com/ethereum/go-ethereum/blob/master/common/types.go#L85

This pretty printing is only active for the "terminal" log format. You can log in other formats where this truncation will not happen, e.g. in `logfmt` format:

```
geth --log.format=logfmt
```

**Comment by achakhalyan** [comment]
not started node - flag provided but not defined: -log.format

**Comment by karalabe** [comment]
Make sure you have a recent version of Geth

**Comment by achakhalyan** [comment]
Geth
Version: 1.11.5-stable
Git Commit: a38f4108571d1a144dc3cf3faf8990430d109bc4
Architecture: amd64
Go Version: go1.20.2
Operating System: linux
geth --help 

result for logs 
`LOGGING AND DEBUGGING

    --fakepow                      (default: false)
          Disables proof-of-work verification

    --log.backtrace value
          Request a stack trace at a specific logging statement (e.g. "block.go:271")

    --log.debug                    (default: false)
          Prepends log messages with call-site location (file and line number)

    --log.file value
          Write logs to a file

    --log.json                     (default: false)
          Format logs with JSON

    --nocompaction                 (default: false)
          Disables db compaction after import

    --pprof                        (default: false)
          Enable the pprof HTTP server

    --pprof.addr value             (default: "127.0.0.1")
          pprof HTTP server listening interface

    --pprof.blockprofilerate value (default: 0)
          Turn on block profiling with the given rate

    --pprof.cpuprofile value
          Write CPU profile to the given file

    --pprof.memprofilerate value   (default: 524288)
          Turn on memory profiling with the given rate

    --pprof.port value             (default: 6060)
          pprof HTTP server listening port

    --remotedb value
          URL for remote database

    --trace value
          Write execution trace to the given file

    --verbosity value              (default: 3)
          Logging verbosity: 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail

    --vmodule value
          Per-module verbosity: comma-separated list of <pattern>=<level> (e.g.
          eth/*=5,p2p=4)

   METRICS AND STATS`

**Comment by jsvisa** [comment]
@achakhalyan you need geth >= 1.11.6, as `--log.logfmt` is merged in https://github.com/ethereum/go-ethereum/pull/26970

**Comment by achakhalyan** [comment]
oy ok its the latest update, thanks.

**Comment by achakhalyan** [comment]
Dear Geth Support Team,

Thank you for getting back to me so quickly about the truncated hash values in log messages. I would greatly appreciate your guidance on using the logfmt format.

I'd like to inquire further about the specific types of log entries that are printed when a transaction is rejected or replaced by the go-Ethereum node. Could you provide detailed information on the following aspects?

1. What are the different scenarios under which a transaction might be rejected or replaced by the go-Ethereum node, and how are these events logged?
2. Are there any specific log levels or configurations that need to be set to monitor these particular events? If so, please provide guidance on how to enable them.

Understanding these aspects will greatly assist me in analyzing and troubleshooting related issues in my project. Your expertise and support are invaluable to me.

Thank you once again, and I look forward to hearing from you soon.

**Comment by jsvisa** [comment]
First of all, I'm not the Geth Support Team :), I'm just a member of the community and Gether.

> when a transaction is rejected or replaced by

If you mean the tx in txpool by replaced, I think there will be no logs.
But if you mean a tx rejected by ChainReorg, AFAIK there will only be a log in block level. If you want to track the transaction rejected or replaced, I think you you can subscribe the `NewPendingTransactions`, ref https://geth.ethereum.org/docs/interacting-with-geth/rpc/pubsub
