### ISSUE TITLE
Issue while performing transactions on Private Ethereum Blockchain using geth

### ISSUE THREAD

**Issue by LifnaJos** [ethereum/go-ethereum#27850]
I was following the steps described in the page provided for [Private Networks in Go-Ethereum](https://geth.ethereum.org/docs/fundamentals/private-network ) website. 

As per the instructions, I updated the **genesis.json** file by updating the extradata and the balances of my accounts to make sure that sufficient balance is there.
**genesis.json**

```
{
  "config": {
    "chainId": 12345,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "muirGlacierBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0,
    "arrowGlacierBlock": 0,
    "grayGlacierBlock": 0,
    "clique": {
      "period": 5,
      "epoch": 30000
    }
  },
  "difficulty": "1",
  "gasLimit": "800000000",
  "extradata": "0x0000000000000000000000000000000000000000000000000000000000000000**2EC436918AfE50376b0a7454f6E0987fF0eFECbb**0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "alloc": {
    "**2EC436918AfE50376b0a7454f6E0987fF0eFECbb**": { "balance": "100000000000000000000000" },
    "**629B332FBBCAE2eB49da020dA66fa8f4faB11EFb**": { "balance": "120000000000000000000000" }
  }
}
```

**All the steps were executed except the last step, where we transfer funds between accounts on different nodes.** 

On the 4th Terminal, JavaScript Console was attached to node 1 and executed the following instructions : 

```
> eth.accounts
["0x2ec436918afe50376b0a7454f6e0987ff0efecbb"]

I checked the account balances of both accounts:

> web3.fromWei(eth.getBalance("0x2ec436918afe50376b0a7454f6e0987ff0efecbb"), "ether")
100000

> web3.fromWei(eth.getBalance("0x629B332FBBCAE2eB49da020dA66fa8f4faB11EFb"), "ether")
120000

> eth.sendTransaction({from:"0x2ec436918afe50376b0a7454f6e0987ff0efecbb", to:"0x629B332FBBCAE2eB49da020dA66fa8f4faB11EFb", value: web3.toWei(10, "ether")})
"**0x3f2a05266d9685ea626512e4c743c02ee7fbe5ba5555b21cac29d2187eb9d42b**"
```

When the fund transfer was made, it showed that it is successful. But, when I checked the balances of the sccounts, they are unaltered.

```
> web3.fromWei(eth.getBalance("0x2ec436918afe50376b0a7454f6e0987ff0efecbb"), "ether")
100000
> web3.fromWei(eth.getBalance("0x629B332FBBCAE2eB49da020dA66fa8f4faB11EFb"), "ether")
120000
```

I went to the Terminal where node 1 is running, there was a warning as follows: 

```
WARN [08-04|12:44:11.698] Caller gas above allowance, capping      requested=799,218,751 cap=50,000,000
INFO [08-04|12:44:11.702] Setting new local account                address=0x2EC436918AfE50376b0a7454f6E0987fF0eFECbb
INFO [08-04|12:44:11.702] Submitted transaction                    hash=**0x3f2a05266d9685ea626512e4c743c02ee7fbe5ba5555b21cac29d2187eb9d42b** from=0x2EC436918AfE50376b0a7454f6E0987fF0eFECbb nonce=0 recipient=0x629B332FBBCAE2eB49da020dA66fa8f4faB11EFb value=10,000,000,000,000,000,000
```

Please help me to fix this issue!!!

**Comment by jsvisa** [comment]
1. Which geth version are you running?
2. What are the geth's startup command line arguments?
3. Do you know if this transaction be mined into the block? you can check with `eth.getTransaction` to check with it.

**Comment by LifnaJos** [comment]
Thank you for your response.

I just followed the steps to setup a Private Ethereum Blockchain using Geth
as provided by the
https://geth.ethereum.org/docs/fundamentals/private-network#end-to-end-example
<https://geth.ethereum.org/docs/fundamentals/private-network#end-to-end-example>
I was able to perform all the steps, except mining the transactions and
getting the updates on account of the peers in the network.

I shall share the document prepared
<https://docs.google.com/document/d/1V6S-p0251YpflzFO488GCt03MhyNyOZbFyzYlRa9pvo/edit?usp=sharing>as
a part of the lab experiment prepared.

Please guide me through the process to mine the blocks in the network.

Thanking you
Lifna C S
+91-9969268243

**Comment by jsvisa** [comment]
You need start either node1 or node2 with ‘—mine —-mine.etherbase xyz’ and xyz in your case is 0x 2EC436918AfE50376b0a7454f6E0987fF0eFECbb

**Comment by LifnaJos** [comment]
I tried performing the same. I am getting an error message as the
attachment.

*Terminal 1 : *bootnode -nodekey boot.key -verbosity 9 -addr :30305
enode://
***@***.***:0?discport=30305

*Terminal 2 :* geth --datadir node1 --port 30306 --bootnodes enode://
***@***.***:0?discport=30305
--networkid 123454321 --unlock 0x3563FDF2b29d6b397C6D4bB17713aB26aB819Ead
--password node1/password --authrpc.port 8553

*Terminal 3 : * geth --datadir node2 --port 30307 --bootnodes enode://
***@***.***:0?discport=30305
--networkid 123454321 --unlock 0x7a515B5c53B0600072Cc928394D3520b63f5c867
--password node2/password --authrpc.port 8552

*Terminal 4 : * geth attach node1/geth.ipc

*Terminal 5 : * geth --miner.etherbase
'0x3563FDF2b29d6b397C6D4bB17713aB26aB819Ead' --mine

Please guide me where I went wrong.

**Comment by rjl493456442** [comment]
I believe you are running with clique engine, `2EC436918AfE50376b0a7454f6E0987fF0eFECbb` it's the address of your configured signer.

In order to pack transactions, your node with signer attached should enable mining explicitly by `--mine`.

e.g.

```
geth --datadir node1 --port 30306 --bootnodes enode://***@***.***:0?discport=30305
--networkid 123454321 --unlock 2EC436918AfE50376b0a7454f6E0987fF0eFECbb
--password pwd--authrpc.port 8553 --mine
```

**Comment by LifnaJos** [comment]
Thank you very much.

geth --datadir node1 --port 30306 --bootnodes enode://
***@***.***:0?discport=30305
--networkid 123454321 --unlock 0x2EC436918AfE50376b0a7454f6E0987fF0eFECbb
--password node1/password --authrpc.port 8551 -*-miner.etherbase
0x2EC436918AfE50376b0a7454f6E0987fF0eFECbb --mine*

I was able to successfully perform transactions.

**Comment by LifnaJos** [comment]
Thank you for supporting me to fix the issue

**Comment by muskan808** [comment]
if i want to run cron for sendtransaction, then how to do this

**Comment by jsvisa** [comment]
> if i want to run cron for sendtransaction, then how to do this

Just send the transaction with a client sdk, eg web3.py or ether.js
