### ISSUE TITLE
[POA] How to unvote proposal in Clique

### ISSUE THREAD

**Issue by anhnh131** [ethereum/go-ethereum#27879]
I try to vote for an address to the validator, but after that, I can not unvote it.
My network has 2 validators, 
- Vote is against the validator2 (set auth: `false`)

![Screenshot 2023-08-08 at 10 46 12](https://github.com/ethereum/go-ethereum/assets/43759289/9abe29f9-7b6d-466d-ba96-518497a30856)

- Unvote by sending auth `true`, but the `tally` doesn't change in the next block.

![Screenshot 2023-08-08 at 10 51 26](https://github.com/ethereum/go-ethereum/assets/43759289/adc098e1-7b9d-43a3-b148-9fd3967194cb)

How to unvote in Clique?

**Comment by karalabe** [comment]
There's no way to unvote, but votes get automatically dropped when crossing the epoch (30K block) boundary, so you can just wait that many blocks and it will drop out.
