### ISSUE TITLE
does the enode of a node change over time?

### ISSUE THREAD

**Issue by akefhabbal-qu** [ethereum/go-ethereum#27881]
I have a private network that works on PoA and after two months of running this network I figured out that one of the nodes had changed its enode.
What are the configurations that change the enode?

**Comment by jwasinger** [comment]
Geth does not change p2p enode keys while running.  When a p2p private key is not explicitly provided in the configuration, the node generates a random one upon startup.

Was your Geth instance restarted at any point (perhaps you are running it inside a Docker container with auto-restart enabled)?

**Comment by akefhabbal-qu** [comment]
I am restarting it for sure. But does the restart affects it? usually when I restart it I still get the same enode.

**Comment by jwasinger** [comment]
The private key for the miner is unrelated.

Sorry, my explanation was actually incorrect.  If you start Geth using a datadir that is empty and don't provide a p2p private key in the config, it will generate one for you.

So it's likely that you wiped your datadir at some point which caused the enode to change.

**Comment by akefhabbal-qu** [comment]
I didn't change anything with datadir I just restarted the node.

**Comment by jsvisa** [comment]
@akefhabbal-qu so what's the startup command and argument of your geth node?

**Comment by akefhabbal-qu** [comment]
geth --port 3003 --networkid 2002--datadir data --http --authrpc.port "55033" --http.api 'web3,eth,net,d,clique,debug,personal,miner,txpool,admin' --http.addr localhost --http.corsdomain '*' 2>>eth.log --http.port 55023 --nodiscover --miner.etherbase "0x2e74ee271ab78bcd1bd46ead008f5196f569f4d9" --signer=//./pipe/clef.ipc --mine console @jsvisa jsvisa

**Comment by holiman** [comment]
> Geth does not change p2p enode keys while running.

ticket answered
