### ISSUE TITLE
Logging Details for Rejected or Replaced Transactions in go-Ethereum

### ISSUE THREAD

**Issue by achakhalyan** [ethereum/go-ethereum#27889]
Dear Geth Support Team,

I'd like to inquire further about the specific types of log entries that are printed when a transaction is rejected or replaced by the go-Ethereum node. Could you provide detailed information on the following aspects?

What are the different scenarios under which a transaction might be rejected or replaced by the go-Ethereum node, and how are these events logged?

1. Are there any specific log levels or configurations that need to be set to monitor these particular events? If so, please provide guidance on how to enable them.
2. Understanding these aspects will greatly assist me in analyzing and troubleshooting related issues in my project. Your expertise and support are invaluable to me.
3. Please provide an example of a log response for replace and rejected transactions - specifically log responses for mempool activity, and block inclusion as well.

Thank you once again, and I look forward to hearing from you soon.

**Comment by karalabe** [comment]
There are no API guarantees on what we log and how. Most of our logs are for debugging purposes and maybe user informing. You can raise the log level to debug or trace for the transaction pool to get more logs, but it's gonna be immensely verbose. (--vmodule=txpool=5)

**Comment by achakhalyan** [comment]
@karalabe Thank you for your response. I attempted to raise the log level using the `--vmodule=txpool=5` command, but I received an error message saying `invalid boolean value "txpool=5" for -vmdebug: parse error`. Could you please clarify the correct way to enable the verbose logging for transaction pool? Your assistance is greatly appreciated!
