### ISSUE TITLE
ethClient.BlockNumber() has no counterpart in backend.SimulatedBackend

### ISSUE THREAD

**Issue by randomshinichi** [ethereum/go-ethereum#27888]
# Rationale
Why should this feature exist?
SimulatedBackend should be a drop-in replacement for ethClient for testing.

What are the use-cases?
Testing!

# Implementation
Please? :D thanks in advance

**Comment by jwasinger** [comment]
I don't think it's needed:

`SimulatedBackend` exposes the `core.BlockChain` type via `BlockChain()`.  `core.BlockChain` has a `CurrentHeader` method that can be used to get the canonical block header which contains the block number.
