### ISSUE TITLE
could not load export data: no export data for "github.com/ethereum/go-ethereum/metrics"

### ISSUE THREAD

**Issue by yangyile1990** [ethereum/go-ethereum#27897]
golangci-lint run
WARN [runner] Can't run linter goanalysis_metalinter: buildir: failed to load package metrics: could not load export data: no export data for "github.com/ethereum/go-ethereum/metrics" 
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: buildir: failed to load package metrics: could not load export data: no export data for "github.com/ethereum/go-ethereum/metrics"

**Comment by yangyile1990** [comment]
Cannot use 'namedMetric.less' (type func(namedMetric, namedMetric) bool) as the type func(a namedMetric, b namedMetric) int

**Comment by yangyile1990** [comment]
slices.SortFunc(namedMetrics, namedMetric.less)

func SortFunc[S ~[]E, E any](x S, cmp func(a, b E) int) {
	n := len(x)
	pdqsortCmpFunc(x, 0, n, bits.Len(uint(n)), cmp)
}

func (m namedMetric) less(other namedMetric) bool {
	return m.name < other.name
}

**Comment by karalabe** [comment]
I assume your dependencies are wonky. Make sure you have the versions we depend on if you use go-ethereum as a library.

**Comment by yangyile1990** [comment]
But i don't know the reason.
my mod is:

github.com/ethereum/go-ethereum v1.12.1

golang.org/x/exp v0.0.0-20230810033253-352e893a4cad // indirect

then it failed.

**Comment by karalabe** [comment]
Do you have other deps too? Maybe something pulls in a newer version of the exp?

**Comment by karalabe** [comment]
Checked it out, and our dep for exp is `v0.0.0-20230515195305-f3d0a9c9a5cc`, if I update to your version it indeed fails. Seems you have some other thing that forces the update?

**Comment by karalabe** [comment]
Yeah, the upstream golang/x/ext broke their API signatures. They ack in in the commit that it's going to be nasty, but that's life. Anyway, opened a PR above to update out dependency too and fix all the broken code.

**Comment by yangyile1990** [comment]
thank you.
