### ISSUE TITLE
v1.12.1 breaking on below code

### ISSUE THREAD

**Issue by verzth** [ethereum/go-ethereum#27894]
/go/pkg/mod/github.com/ethereum/go-ethereum@v1.12.1/metrics/writer.go:27:32: type func(m namedMetric, other namedMetric) bool of namedMetric.less does not match inferred type func(a namedMetric, b namedMetric) int for func(a E, b E) int

/go/pkg/mod/github.com/ethereum/go-ethereum@v1.12.1/accounts/keystore/account_cache.go:197:32: type func(a accounts.Account, b accounts.Account) bool of byURL does not match inferred type func(a accounts.Account, b accounts.Account) int for func(a E, b E) int

**Comment by jsvisa** [comment]
Which Golang version are you using, under 1.20?

**Comment by verzth** [comment]
I'm using docker golang:1.20.3-alpine and go.mod 1.20

**Comment by verzth** [comment]
everything ok when i downgrade it to v1.12.0

**Comment by verzth** [comment]
I think i found out the problem, here is the problem

You're using library `golang.org/x/exp/slices`, and when it call func `slices.SortFunc` it need func with return type `int`
but in your code line such as 

metrics/writer.go:95 -> called on line 27
```go
func (m namedMetric) less(other namedMetric) bool {
	return m.name < other.name
}
```

accounts/keystore/account_cache.go:43 -> called on line 197
```go
// byURL defines the sorting order for accounts.
func byURL(a, b accounts.Account) bool {
	return a.URL.Cmp(b.URL) < 0
}
```

it returns bool

may be it because you're using golang experimental feature which would be matters in some go versions, better not using it for now

**Comment by karalabe** [comment]
Shouldn't matter what we use as long as the dependency versions match.

Are you using go-ethereum as a library? Perhaps you pull in one of the deps at a different version and not what we use?

**Comment by karalabe** [comment]
You'll need to show us how to repro this thing, because as far as I'm concerned, it's a dependency version mismatch on your end. Happy to look into it more if I know what to run that fails.

**Comment by jsvisa** [comment]
> and when it call func slices.SortFunc it need func with return type int

In go-ethereum we use https://pkg.go.dev/golang.org/x/exp@v0.0.0-20230515195305-f3d0a9c9a5cc/slices this version, as @karalabe mentioned, this version maybe differ to yours

**Comment by verzth** [comment]
thank you for the information, may be i have some dependency conflict

**Comment by loleg** [comment]
Same issue on go 1.20.6 and go-ethereum v1.12.1
I had to upgrade x/exp with this command as a workaround:
`go get golang.org/x/exp@v0.0.0-20230515195305-f3d0a9c9a5cc`

**Comment by acashmoney** [comment]
Ran into a similar issue with the `exp` module running `go version go1.20.4 darwin/arm64` with geth v1.12.0

**Previous version:** `golang.org/x/exp v0.0.0-20230321023759-10a507213a29`
**Geth specified version:** `golang.org/x/exp v0.0.0-20230905200255-921286631fa9`

After installing geth, previously functioning code breaks due to the dependency conflict. However, downgrading to the previous module version fixes the issue.

```
go get golang.org/x/exp@v0.0.0-20230321023759-10a507213a29
```
