### ISSUE TITLE
Improve peer-to-peer connectivity

### ISSUE THREAD

**Issue by J1a-wei** [ethereum/go-ethereum#27893]
Hi team, I have an idea. We have deployed multiple Geth  nodes, and we have spent a lot of time and network costs for synchronization. 
For this cluster, is it possible to enable them to automatically discover each other and prioritize the use of the local network for data retrieval? This way, it would accelerate network speed and avoid incurring additional network costs. 
Alternatively, can we have only one node actively participating in P2P while the other nodes only download without uploading? Is this idea feasible?

**Comment by dubuqingfeng** [comment]
Also interested in this.

**Comment by lightclient** [comment]
>  is it possible to enable them to automatically discover each other and prioritize the use of the local network for data retrieval?

This would require a different discovery mechanism than using `discv4` or DNS discovery and the use case is pretty niche. I don't think it is something we would support. You can easily start geth without discovery and manually add local peers if you want to rely more heavily on them.

> Alternatively, can we have only one node actively participating in P2P while the other nodes only download without uploading? Is this idea feasible?

This goes against the idea of fairness in the p2p. If we have many potential leechers on the network, we would have to consider different ways of metering their behavior so they don't suck a large portion of any individual node's resources.
