### ISSUE TITLE
Jammy PPA Build Failed

### ISSUE THREAD

**Issue by jwgstr** [ethereum/go-ethereum#27906]
#### Expected behaviour
geth 1.12.1 available to install via ppa

#### Actual behaviour
Some PPA builds are failing, specifically the Jammy (latest LTS Ubuntu)1.12.1 build: 
https://launchpad.net/~ethereum/+archive/ubuntu/ethereum/+packages
https://launchpad.net/~ethereum/+archive/ubuntu/ethereum/+build/26494803

May be related to this confusing Go behavior: 
https://github.com/golang/go/issues/57529

#### Backtrace
https://launchpadlibrarian.net/681343154/buildlog_ubuntu-jammy-amd64.ethereum_1.12.1+build28788+jammy_BUILDING.txt.gz

**Comment by jwgstr** [comment]
Release of 1.12.2 seems to have fixed the Jammy builds.  

As noted as a possibility in the release notes Trusty builds 
continue to fail.

**Comment by karalabe** [comment]
Trusty does not support arm64, otherwise the rest should be building fine.
