### ISSUE TITLE
New Prometheus metrics for blobpool are not formatted correctly.

### ISSUE THREAD

**Issue by imulmat4** [ethereum/go-ethereum#27900]
#### System information

Geth version: `1.12.1`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OS1.12.
Commit hash : (if `develop`)

#### Expected behaviour
Prometheus metrics are formatted in the correct format with underscores and not hyphens. 

#### Actual behaviour
All the new blobpool metircs have a - and that breaks all the Prometheus scrapers since prometheus doesnt support hyphen metric names. Error I am getting:
Error reading metrics for "http://127.0.0.1:6000/debug/metrics/prometheus": reading text format failed: text format parsing error in line 66: invalid metric name in comment

#### Steps to reproduce the behaviour
Just run geth on version 1.12.1

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by imulmat4** [comment]
I opened https://github.com/ethereum/go-ethereum/pull/27901 which should fix the above, but not sure if I am missing more context

**Comment by karalabe** [comment]
Thanks PR looked good.
