### ISSUE TITLE
I am trying to verify and publish my smart contract but am having issues;

### ISSUE THREAD

**Issue by troysean** [ethereum/go-ethereum#27912]
Compiler debug log:
 Error! Unable to generate Contract Bytecode and ABI
 Found the following ContractName(s) in source code : SafeMath, SimpleToken
 But we were unable to locate a matching bytecode (err_code_2)

any help is appreciated

**Comment by troysean** [comment]
using Remix.
lauching to goerli.

**Comment by MariusVanDerWijden** [comment]
Please use the stackexchange https://ethereum.stackexchange.com/ and keep this issue tracker to go-ethereum specific issues.
