### ISSUE TITLE
I am trying to verify and publish my smart contract but am having issues;

### ISSUE THREAD

**Issue by troysean** [ethereum/go-ethereum#27911]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

**Comment by MariusVanDerWijden** [comment]
Please use the stackexchange https://ethereum.stackexchange.com/ and keep this issue tracker to go-ethereum specific issues.
