### ISSUE TITLE
Is it possible to customize genesis.json in Dev mode?

### ISSUE THREAD

**Issue by zxsimba** [ethereum/go-ethereum#27922]

**Comment by wighawag** [comment]
I am in need for custom genesis and want to use something like the --dev mode, but there is no documentation in how to achieve that

it seems I need to set the miner.etherbase and unlock it but I get 

```
Account unlock with HTTP access is forbidden!
```

any way around this ?

Note that in v.1.11.6 I used to provide my own genesis with `--dev` and it worked without any issue

**Comment by jwasinger** [comment]
> it seems I need to set the miner.etherbase and unlock it

why do you need to set the etherbase?

The etherbase is set by default to the prefunded account, which is unlocked so you can make transactions originating from it using `eth_sendTransaction`.

**Comment by wighawag** [comment]
geth asked me to specify it when I added `--mine `

**Comment by jwasinger** [comment]
You don't need to specify `--mine`.  `--dev` will mine blocks as soon as it receives transactions.  it will mine blocks at a regular interval if you specify a value for `--dev.period`

**Comment by wighawag** [comment]
As I said, I cant use `--dev` anymore with a custom genesis. it used to work but not anymore

Alternatively if you could provide as documentation, a docker-compose.yml that setup a private network where we can customize genesis, that would really good. keep needing to update mine as geth version changes

**Comment by wighawag** [comment]
FYI, managed to update my docker-compose.yml file to use the 3 node setup described in [your doc](https://geth.ethereum.org/docs/fundamentals/private-network )

This might be helpful to others, the docker-compose.yml allow you to specify your custom genesis

it uses a bootnode a miner node and an rpc node

See: https://github.com/wighawag/ethereum-lan-node/blob/0c3f6e50a2fb9f899a71ecf0d504140efe24fa21/docker-compose.yml

It works but would love to have the same thing as --dev with only one node running

**Comment by jwasinger** [comment]
So as it turns out, it is possible to use a custom genesis in dev mode.  You can adapt from this example genesis:
```
{
  "config": {
    "chainId": 1337,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "muirGlacierBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0,
    "arrowGlacierBlock": 0,
    "grayGlacierBlock": 0,
    "shanghaiTime": 0,
    "terminalTotalDifficulty": 0,
    "terminalTotalDifficultyPassed": true,
    "isDev": true
  },
  "nonce": "0x0",
  "timestamp": "0x0",
  "extraData": "0x",
  "gasLimit": "0xaf79e0",
  "difficulty": "0x0",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "0000000000000000000000000000000000000001": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000002": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000003": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000004": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000005": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000006": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000007": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000008": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000009": {
      "balance": "0x1"
    },
    "000000000000000000000000000000000000aaaa": {
      "code": "0x58585454",
      "balance": "0x3",
      "nonce": "0x1"
    },
    "a94f5374fce5edbc8e2a8697c15331677e6ebf0b": {
      "balance": "0x100000000000000"
    },
    "d81278831c41455f4fc09aa5bdb16d2b17be7f4f": {
      "balance": "0xfffffffffffffffffffffffffffffffffffffffffffffffffefffffffffffff4"
    },
    "0000000000000000000000000000000000000010": {
      "balance": "0x1"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "baseFeePerGas": "0x3b9aca00",
  "excessBlobGas": null,
  "blobGasUsed": null
}
```

Note that `"terminalTotalDifficultyPassed": true` is strictly required.  In order not to encounter any weird edge-cases or undefined behavior, I recommend to enable all pre-merge hard-forks and not remove any of the precompiled address allocations from the configuration.  Otherwise, configure as you see fit.

There will be some additional docs about this (pending review/merge).  However, the workflow is the same as it would be normally.

@wighawag regarding your error `Account unlock with HTTP access is forbidden!`,  you need to use the `--allow-insecure-unlock` flag.

**Comment by wighawag** [comment]
Thanks @jwasinger I confirm it works and with that I can even get the post merge hardfork in like your example show.

Are you intending to keep that level of customizability ? 

You mentioned [in your comment above](https://github.com/ethereum/go-ethereum/issues/27922#issuecomment-1677431151) that you do not want to support it. Did the fact that it works today changed your mind ?

Personally, I just need the ability to allocate balances and chainId, but configuring forks and gas fee might be usefull to

**Comment by jwasinger** [comment]
> You mentioned https://github.com/ethereum/go-ethereum/issues/27922#issuecomment-1677431151 that you do not want to support it. Did the fact that it works today changed your mind ?

I said that because 1) I didn't realize it was previously supported and 2) I thought that there would be too much potential for undefined edge-case behavior with genesis mis-configuration (e.g. someone disabling PoS and/or setting some weird fork activation configuration).

I'm now leaning towards allowing customizable genesis configurations and validating at startup that proof-of-stake and pre-merge EIPs are enabled at genesis.
