### ISSUE TITLE
Support for events in Go bindings

### ISSUE THREAD

**Issue by murrekatt** [ethereum/go-ethereum#2792]
It would be great to have support for events in the Go bindings to easily watch needed events.

[In the docs it is only mentioned it is waiting for some RPC pub/sub changes](https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts) but maybe these are already available?

Is this feature being worked on or discussed?

I am aware it is possible to get logs and thus events either with polling or subscription over JSON RPC.

**Comment by karalabe** [comment]
It's waiting for a new RPC client implementation from @fjl . When that is merged in, we can properly use subscriptions to get the event logs and I can finally implement this for Native DApps :)

**Comment by murrekatt** [comment]
@karalabe @fjl any schedule for this or place to follow/discuss the work?

**Comment by fjl** [comment]
The RPC client is currently in review, see #2808

**Comment by fjl** [comment]
See #2900

**Comment by johnweldon** [comment]
I see 
 * #2900 was closed, and apparently not replaced.
 * #2798 was closed in favour of #2885 and merged.
 * #2808 was merged.

What remains?  Just abigen updates?  I don't see an abigen issue addressing events (other than this one).

**Comment by fjl** [comment]
This issue is still open, so the work is not done yet. @awishformore told me he is still working on this. If he isn't, me or @karalabe will step in and do it. Either way this is part of the 1.5 milestone and we all want it, so it'll happen.

**Comment by awishformore** [comment]
I will start working on this again this weekend. Had a couple of rough weeks.

**Comment by markya0616** [comment]
Any updates about this PR? We really need this feature! Thanks.

**Comment by awishformore** [comment]
I dropped the ball on this one, just couldn't find the time anymore. Not sure on the current status.

**Comment by alanchchen** [comment]
@karalabe, @fjl  
Any update about this feature?
Not sure if there is something I can do but I'm willing to help this.

**Comment by coreyog** [comment]
Is this expected to be out in 1.6.6? We're multiple versions ahead of the target milestone of this issue.

**Comment by yurako97** [comment]
When we can wait, this feature will be released ?

**Comment by robert-zaremba** [comment]
Is there any workaround for this? How can I get the events in Go without waiting for this release?

**Comment by fjl** [comment]
Work to add event decoding is going on in ethereum/go-ethereum#14743

**Comment by murrekatt** [comment]
@fjl @karalabe what's the status of this? I see 1.7.0 is the milestone and that is already released. Thanks for an update!

**Comment by lewgun** [comment]
@fjl @karalabe what's the status of this?  Thanks for an update!

**Comment by karalabe** [comment]
It's on master

**Comment by karalabe** [comment]
:sparkles:
