### ISSUE TITLE
txlimitlookup not work

### ISSUE THREAD

**Issue by knightowen** [ethereum/go-ethereum#27934]
#### System information

Geth version: `geth 1.12.2`
OS: linux
first launch on new machine with txlimitlookup=0

#### Expected behaviour
index old transactions 

#### Actual behaviour
not ever begn indexing if first launch geth with txlimitlookup=0

at line #2341 in core/blockchain.go
if tail == nil 
change to 
if tail == nil || *tail == 0

then it works. 

this is a slight change so didn't make a pull request. someone can fix this if convenient

**Comment by jsvisa** [comment]
After v1.12.1, the arg `--txlookuplimit` will be deprecated, use `--history.transactions` instead

**Comment by rjl493456442** [comment]
As @jsvisa said, `--txlookuplimit ` will be deprecated and please use `--history.transactions`. Also the original `txlookuplimit` is restored in https://github.com/ethereum/go-ethereum/pull/27917 and should be still usable for a couple of months.
