### ISSUE TITLE
Receipt of reverted deployment transaction has a non-null contract address

### ISSUE THREAD

**Issue by fvictorio** [ethereum/go-ethereum#27937]
If you send a deployment and the transaction reverts, the receipt of that transaction has a non-null `contractAddress`. I don't know if this is intended behavior or if it's a bug.

### Reproduction

1. Send a deployment transaction with this data: `0x6080604052348015600f57600080fd5b506000601a57600080fd5b603f8060276000396000f3fe6080604052600080fdfea2646970667358221220e30f63f383b7791836a8f2022e0baac71c054a6385e97dd23846be98a2dcceb364736f6c63430008110033`. This is just an empty contract whose constructor only has a `require(false);` statement.
2. Get the receipt of this transaction. The `status` should be 0, but you'll see that there is a non-null `contractAddress`.
3. Get the code of that address. It should be `0x`.

**Comment by jwasinger** [comment]
Out of curiosity, how are you sending the creation tx?  If the tx reverts, it won't be included in the chain so there won't be a tx receipt.

**Comment by fvictorio** [comment]
> If the tx reverts, it won't be included in the chain

Reverted transactions are included. Perhaps you are sending it with something that auto-estimates the gas limit, and that's what fails? Try setting an explicit gas limit.

**Comment by jwasinger** [comment]
Okay.  IMO it's totally consistent that the transaction receipt for a failed contract deployment contains the contract address.  There's no reason to change this.

**Comment by Abdulrahman2274** [comment]
> إذا قمت بإرسال نشر وتم إرجاع المعاملة ، فسيكون استلام هذه المعاملة غير فارغ `contractAddress`. لا أعرف ما إذا كان هذا هو السلوك المقصود أم أنه خطأ.
> 
> ### التكاثر
> 1. أرسل معاملة نشر بهذه البيانات `0x6080604052348015600f57600080fd5b506000601a57600080fd5b603f8060276000396000f3fe6080604052600080fdfea2646970667358221220e30f63f383b7791836a8f2022e0baac71c054a6385e97dd23846be98a2dcceb364736f6c63430008110033`:. هذا مجرد عقد فارغ لا يمتلك المُنشئ سوى `require(false);`بيان.
> 2. احصل على إيصال هذه الصفقة. يجب أن تكون القيمة `status`0 ، لكنك سترى أن هناك قيمة غير خالية `contractAddress`.
> 3. احصل على رمز هذا العنوان. يجب أن يكون `0x`.

TMHSmhCQ2qU7cLoJnX4haK2zzdPMTbXrtS

**Comment by Abdulrahman2274** [comment]
TMHSmhCQ2qU7cLoJnX4haK2zzdPMTbXrtS

**Comment by Abdulrahman2274** [comment]
> 

> TMHSmhCQ2qU7cLoJnX4haK2zzdPMTbXrtS[TMHSmhCQ2qU7cLoJnX4haK2zzdPMTbXrtS]() `
