### ISSUE TITLE
What affects geth sync speed?

### ISSUE THREAD

**Issue by zerochl** [ethereum/go-ethereum#27936]
I have two machines with the same network.But the CPU of the machine is different, one will be AMD5900HX, the other is E5 2683V4, and the memory is DDR4.
This is what you see so far:
AMD5900HX:
`
INFO [08-16|15:43:25.266] Imported new potential chain segment     number=17,925,976 hash=96ba74..c31813 blocks=1          txs=106           mgas=11.112  elapsed=68.281ms      mgasps=162.740  dirty=1021.37MiB
INFO [08-16|15:43:25.294] Chain head was updated                   number=17,925,976 hash=96ba74..c31813 root=217362..de93b1 elapsed=2.14068ms
`
E52683V4:
`
INFO [08-16|03:43:25.444] Imported new potential chain segment     number=17,925,976 hash=96ba74..c31813 blocks=1  txs=106  mgas=11.112  elapsed=93.466ms     mgasps=118.888 dirty=1021.37MiB
INFO [08-16|03:43:25.494] Chain head was updated                   number=17,925,976 hash=96ba74..c31813 root=217362..de93b1 elapsed=6.208965ms
`
Obviously, the machine speed of 5900HX is 178ms faster than that of E5 2683V4.

So I went to check the situation of peers and found that the number of peers is the same.

Is the problem caused by CPU performance?

**Comment by MariusVanDerWijden** [comment]
Sync speed is heavily dependent on diskIO, bandwith and which peers your node connects to. Your nodes are already synced, block import speed depends on CPU and diskIO mainly

**Comment by karalabe** [comment]
It also depends on what is cached in memory, which can also depend on what transactions your node seen in the network (they might or might not get executed into a pending block). There are many many many variables that might make a block do less or more disk reads. But in general it boils down to IO ops.
