### ISSUE TITLE
Release v.1.12.2 doesn't build

### ISSUE THREAD

**Issue by karmops** [ethereum/go-ethereum#27949]
#### System information

![image](https://github.com/ethereum/go-ethereum/assets/111905706/62f6cbb7-d33e-40ee-983d-74f17213d976)

![image](https://github.com/ethereum/go-ethereum/assets/111905706/83a071c3-d181-460e-b0f0-892e053fb678)

```log
# github.com/ethereum/go-ethereum/ethdb/pebble
/go/pkg/mod/github.com/ethereum/go-ethereum@v1.12.2/ethdb/pebble/pebble.go:579:10: assignment mismatch: 1 variable but d.db.NewIter returns 2 values
```

you need to upgrade to `go-Ethereum v1.12.2` alongside the latest version of `pebble v0.0.0-20230817205902-856ed3647f60`, then just an ordinary build, and that's it.

**Comment by karmops** [comment]
related pull request: https://github.com/ethereum/go-ethereum/pull/27927

**Comment by rjl493456442** [comment]
We didn't upgrade pebble in v.1.12.2 release, so please use legacy pebble version in v.1.12.2 instead, or fix the build issues by yourself (e.g. run #27927)
