### ISSUE TITLE
devp2p discv4 crawl does NOT WORK

### ISSUE THREAD

**Issue by zjuujz8021** [ethereum/go-ethereum#27942]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : v1.12.1

#### Expected behaviour
Crawl ethereum nodes

#### Actual behaviour
No results, only repeated:
INFO [08-17|14:37:11.202] Crawling in progress                     added=0 updated=0 removed=0 ignored(recent)=0 ignored(incompatible)=0

#### Steps to reproduce the behaviour
cmd:
./build/bin/devp2p discv4 crawl -timeout 30m all-nodes.json

**Comment by zjuujz8021** [comment]
I ran on aws-us-east

**Comment by holiman** [comment]
How long did you let it run? 

If you start with a file containing some nodes, to bootstrap it, thing start happening pretty quickly
I tested by downloading the `all.json` from the public crawler repo: https://github.com/ethereum/discv4-dns-lists/blob/master/all.json  

```
$ go run  .  --verbosity 5 discv4  crawl -timeout 30m   all.json 
INFO [08-17|09:47:04.063] New local node record                    seq=1,692,258,424,061 id=95f50fe6df2a1ad9 ip=127.0.0.1 udp=41419 tcp=0
TRACE[08-17|09:47:04.087] >> PING/v4                               id=000dc3409b215fe6 addr=157.254.200.148:30311 err=nil
TRACE[08-17|09:47:04.087] >> PING/v4                               id=001f01c2cec56fbc addr=18.130.245.73:30303   err=nil
...
INFO [08-17|09:47:04.201] New local node record                    seq=1,692,258,424,062 id=95f50fe6df2a1ad9 ip=212.85.71.121 udp=41419 tcp=0

```

**Comment by zjuujz8021** [comment]
In fact 30m. But I start with an empty file. Should I start with with some specified bootnodes?

**Comment by ucwong** [comment]
Run with ```--verbosity 5``` to see more details

**Comment by holiman** [comment]
> Should I start with with some specified bootnodes?

Well, if you some nodes to start with, it will find other nodes faster. If there are none, I'm not sure what it does. @fjl do you know how it goes about finding peers if there is no `all.json` input file to start with? Does it use e.g. predefined bootnodes or dns ..?
