### ISSUE TITLE
go: github.com/ethereum/go-ethereum@latest (v1.12.2) indirectly requires github.com/kataras/iris/v12@v12.2.0-beta5: reading github.com/kataras/iris/go.mod at revision v12.2.0-beta5: unknown revision v12.2.0-beta5

### ISSUE THREAD

**Issue by GalaxySciTech** [ethereum/go-ethereum#27943]
go get github.com/ethereum/go-ethereum@latest error
go: github.com/ethereum/go-ethereum@latest (v1.12.2) indirectly requires github.com/kataras/iris/v12@v12.2.0-beta5: reading github.com/kataras/iris/go.mod at revision v12.2.0-beta5: unknown revision v12.2.0-beta5

**Comment by jsvisa** [comment]
Can't reproduce this issue, maybe related to go proxy?

btw, my go proxy is `GOPROXY="https://goproxy.cn/,direct"`

**Comment by GalaxySciTech** [comment]
i have used  `go env -w GOPROXY=direct`

**Comment by karalabe** [comment]
go-ethereum does not have a dependency (either direct or indirect) on that project. https://github.com/ethereum/go-ethereum/blob/release/1.12/go.mod

**Comment by adriangarrote-zh** [comment]
Hey guys! I am experiencing this error on my side as well. 
I think it has indeed an indirect dependency with that failing project version. 

It is a dependency for sentry-go@v0.18.0
` go mod graph | grep kataras/iris      
github.com/getsentry/sentry-go@v0.18.0 github.com/kataras/iris/v12@v12.2.0-beta5`

which is a dependency for go-ethereum
`go mod graph | grep sentry-go@v0.18.0
github.com/ethereum/go-ethereum@v1.12.2 github.com/getsentry/sentry-go@v0.18.0`

Could you please reconsider opening this issue and fixing it? @karalabe @GalaxySciTech 
thank you!!

**Comment by Etherdrake** [comment]
Currently experiencing this issue as well on a fresh Fedora 39 install. 

`go: github.com/ethereum/go-ethereum@v1.13.2 requires
	github.com/getsentry/sentry-go@v0.18.0 requires
	github.com/kataras/iris/v12@v12.2.0-beta5: reading github.com/kataras/iris/go.mod at revision v12.2.0-beta5: unknown revision v12.2.0-beta5
make: *** [Makefile:36: install] Error 1`

Please consider re-opening this issue @karalabe  @GalaxySciTech.

**Comment by fearlesschenc** [comment]
Experiencing this issue as well, it turns out the dependency graph is:

github.com/cockroachdb/pebble@v1.1.0
github.com/cockroachdb/errors v1.11.1
github.com/getsentry/sentry-go@v0.18.0
github.com/kataras/iris/v12@v12.2.0-beta5

While v12.2.0-beta5 is not exist, since sentry-go@v0.20.0 this problem is fixed. Currently bypass this issue with replace in go.mod, but we should fix this.
