### ISSUE TITLE
Stuck syncing

### ISSUE THREAD

**Issue by Ololosha100501** [ethereum/go-ethereum#27959]
Hello there! Guys from prysm said I should talk with you. (https://github.com/prysmaticlabs/prysm/issues/12762)

So. Running Geth 1.12.0 and Prysm 4.0.7
And this bundle worked perfect before the last week. Tonight was the third time it stucked.

Logs are in attachments.
[geth log.txt](https://github.com/prysmaticlabs/prysm/files/12393118/geth.log.txt)
[prysm log.txt](https://github.com/prysmaticlabs/prysm/files/12393119/prysm.log.txt)

All started in prysm at 03:52:36 - WARN p2p: Attestation is too old to broadcast, discarding it. Current Slot: 7145661 , Attestation Slot: 7145628

But node still worked. Worked for almost an hour, though there was a lot of old attestation warnings.

Then at 04:45:52 geth started to say Ignoring already known beacon payload number=17,959,321 hash=a1fae9..88f259 age=17s
And this is all it sayed for next 3.5 hours.

At this time prysm sayed either WARN initial-sync: Block is not processed error=could not notify the engine of the new payload: timeout from http.Client: received an undefined execution engine error or WARN initial-sync: Range is not processed error=Range had no valid blocks to process

Within this time there was a lot of peers connected.

My setup:
AMD Ryzen 5 5600G
32 GB RAM
Windows 10 x64

**Comment by MariusVanDerWijden** [comment]
Ignoring already known beacon block means that we already seen and executed that block. Most likely a prysm issue, they seem to give us older blocks over and over again

**Comment by Ololosha100501** [comment]
> Ignoring already known beacon block means that we already seen and executed that block. Most likely a prysm issue, they seem to give us older blocks over and over again

Can you guys just talk with each other? They said it's geth issue.

**Comment by holiman** [comment]
> They said it's geth issue. 

Is there any ticket on their issue tracker that you can link us to?

**Comment by Ololosha100501** [comment]
And again
[Geth logs.txt](https://github.com/ethereum/go-ethereum/files/12447808/Geth.logs.txt)
[Prysm logs.txt](https://github.com/ethereum/go-ethereum/files/12447809/Prysm.logs.txt)

**Comment by chengzx98** [comment]
> 再次 [Gethlogs.txt ](https://github.com/ethereum/go-ethereum/files/12447808/Geth.logs.txt) [Prysmlogs.txt](https://github.com/ethereum/go-ethereum/files/12447809/Prysm.logs.txt)
Hello, I have the same problem as you in the past few days. My prysm version: v4.1.1 geth version: 1.13.5. Have you solved it?

**Comment by holiman** [comment]
This bug report is very old, I'll assume it's not a problem anymore
