### ISSUE TITLE
 do you have a relatively simple and suitable alliance chain recommendation?

### ISSUE THREAD

**Issue by digitalinformation** [ethereum/go-ethereum#27960]
Hello, I have recently been doing blockchain privacy protection based on Trusted Execution Environment (SGX), if you choose a consortium chain, do you have a relatively simple and suitable alliance chain recommendation?Is fisco bcos likely to be combined with SGX? Is it easy to develop

**Comment by holiman** [comment]
This is go-ethereum, an implementation of Ethereum. The focus here is Ethereum, nothing else
