### ISSUE TITLE
error "Transaction w/ invalid nonce." 

### ISSUE THREAD

**Issue by ageyev** [ethereum/go-ethereum#2796]
#### System information

Geth version: Geth/v1.5.0-unstable/linux/go1.5.1
OS & Version: Linux - Ubuntu 16.04/14.04
Commit hash : 

#### Expected behaviour
call public variable from JS console, 
see: http://ethereum.stackexchange.com/questions/6957/transaction-w-invalid-nonce

#### Actual behaviour
error "Transaction w/ invalid nonce." 

#### Steps to reproduce the behaviour

see: http://ethereum.stackexchange.com/questions/6957/transaction-w-invalid-nonce 

#### Backtrace

````
Transaction w/ invalid nonce. tx=0 state=3) 
````
The same code works fine on Geth/v1.4.9-stable/linux/go1.5.1

**Comment by karalabe** [comment]
Fixed.
