### ISSUE TITLE
EL warning : the method engine_newPayloadV2 does not exist/is not available?

### ISSUE THREAD

**Issue by kevgithub** [ethereum/go-ethereum#27996]
I builded a node with **mev-geth & prysm** and get those warnings:

mev-geth warning:

```
WARN [08-24|11:08:36.295] Served engine_newPayloadV2               conn=127.0.0.1:62081 reqid=6 duration="16.544µs" err="the method engine_newPayloadV2 does not exist/is not available"
```

prysm warning:

```
[2023-08-24 11:12:08]  WARN initial-sync: Skip processing batched blocks error=could not process block in batch: method not found: received an undefined execution engine error

```

and mev-geth version, I checked the geth version is 1.13.0

```
Geth
Version: 1.10.23-stable
```

prysm version:

```
Prysm/v4.0.8/0ca3644057e27966a446051fe3bc3389a1add54e. Built at: 2023-08-22 18:24:27+00:00
```

also here's what I use to start clients:
```
./prysm.sh beacon-chain --execution-endpoint=http://localhost:8551 --jwt-secret=/Users/.../jwt.hex --datadir=/Users/.../data --checkpoint-sync-url=https://beaconstate.ethstaker.cc/ --genesis-beacon-api-url=https://beaconstate.ethstaker.cc/

./mev-geth/build/bin/geth --http --http.api eth,net,engine,admin --authrpc.jwtsecret /Users/.../jwt.hex --datadir /Users/.../data/
```
If I remove the checkpoint url and warning disappeared, I tried every checkpoint nodes on [https://eth-clients.github.io/checkpoint-sync-endpoints/#mainnet](url) and gave me the same warning, is there any solution on that? or do I need to worry about those warnings?
Thanx

**Comment by rjl493456442** [comment]
> received an undefined execution engine error

You are using mev-geth, but not geth right? I guess mev-geth returns some customized engine error, not sure what we can do here.

**Comment by kevgithub** [comment]
> 
I dont think this is a customized warning form mev-geth, base on this reply: `https://github.com/ethereum/go-ethereum/issues/27093#issuecomment-1519707289`, version of geth < 1.11.5 is the reason why those warning happened, which the latest of mev-geth version is 1.10, all I want to know is should I ignore that warning? 
Also I even wanna try to sync with geth + prysm, after syncing finished maybe I can simply switch geth to mev-geth to run, but I m not sure if that would be ok

**Comment by rjl493456442** [comment]
> WARN [08-24|11:08:36.295] Served engine_newPayloadV2               conn=127.0.0.1:62081 reqid=6 duration="16.544µs" err="the method engine_newPayloadV2 does not exist/is not available"


It said this function is not present, while it's available in Geth. Maybe you are running wrong mev-geth version? Or please open a ticket in their repo?

**Comment by kevgithub** [comment]
> I've already done this but no one has replied to me, I apologize if thers's any disturb, one last question, is it possible to complete the sync with the official geth+prysm, and then switch the geth to flashbot mev-geth to run,...

**Comment by kevgithub** [comment]
> > WARN [08-24|11:08:36.295] Served engine_newPayloadV2               conn=127.0.0.1:62081 reqid=6 duration="16.544µs" err="the method engine_newPayloadV2 does not exist/is not available"
> 
> It said this function is not present, while it's available in Geth. Maybe you are running wrong mev-geth version? Or please open a ticket in their repo?

 I've already done this but no one has replied to me, I apologize if thers's any disturb, one last question, is it possible to complete the sync with the official geth+prysm, and then switch the geth to flashbot mev-geth to run,...

**Comment by karalabe** [comment]
We have no idea how mev-geth works, so :D You're on your own here, it's a different project.
