### ISSUE TITLE
How to reduce the size of elapsed and increase the synchronization speed

### ISSUE THREAD

**Issue by zerochl** [ethereum/go-ethereum#27997]
`
INFO [08-23|23:39:00.253] Imported new potential chain segment     number=17,981,934 hash=4d0bb0..12307f blocks=1    txs=106       mgas=10.605 elapsed=94.972ms    mgasps=111.667 dirty=147.85MiB

INFO [08-23|23:39:00.319] Chain head was updated                   number=17,981,934 hash=4d0bb0..12307f root=8a4996..7e331b elapsed=6.76451ms
`
elapsed This parameter is related to the network and hard disk or to the CPU?

**Comment by rjl493456442** [comment]
The execution efficiency depends on various factors, e.g. CPU, disk. It's not that relevant with network.

`elapsed=94.972ms` for a mainnet block is acceptable, unless you have some special performance requirement.
