### ISSUE TITLE
Some transactions  stuck in pool with enough gas price (in a private network)

### ISSUE THREAD

**Issue by aweneagle** [ethereum/go-ethereum#28018]
#### System information
Geth version: v1.101200.0
OS & Version: Linux

#### Background:
We built a private network, in which we deployed a set of geth nodes as p2p layer( which we called p2p nodes ) before miner nodes for high availability. All transactions go to the p2p nodes first, then broadcasted to the miner nodes later.

#### Expected behavior
All transactions with enough price and correct nonce should be mined when the miner's pool is empty and gas price goes down.

#### Actual behavior
Some transactions are stuck in the p2p node's pool forever after a traffic jam.

#### Steps to reproduce the behavior
1. Prepare some addresses (let's say 100k+)
2. Send transactions between them, in a high throughput(say 4k+/s tps), and keep it for a while (say 30mins)
3. Make sure to trigger the traffic jam. (By watching meter indicated whether the miner's pool size has reach the limit or not)
4. After the load testing finished, there might be some transactions stuck in the p2p nodes forever.

We found the root cause here :
they are caught in this [underpriced buffer](https://github.com/ethereum/go-ethereum/blob/master/eth/fetcher/tx_fetcher.go#L306). After adding a frequent cleaner to this buffer, the blocking issue disappeared.

When the traffic is jamming, some transactions may be rejected as 'underpriced', and might be rejected forever even the chain's gas price has went down, unless other 'underpriced' transaction replace it. it's seems unfair.

So, i am wondering that, maybe we should make this buffer cleared frequently?

**Comment by MariusVanDerWijden** [comment]
Yeah I think thats a good point, we kinda have to decide between dos resistance and ux here. Will discuss in our next triage
