### ISSUE TITLE
Question about rewinding blockchain head block

### ISSUE THREAD

**Issue by nothingmin** [ethereum/go-ethereum#28020]
On geth startup, geth rewind the blockchain until geth finds t**he head block that has corresponding state**.

```
// Rewind the fast block in a simpleton way to the target head
if currentSnapBlock := bc.CurrentSnapBlock(); currentSnapBlock != nil && header.Number.Uint64() < currentSnapBlock.Number.Uint64() {
	newHeadSnapBlock := bc.GetBlock(header.Hash(), header.Number.Uint64())
	// If either blocks reached nil, reset to the genesis state
	if newHeadSnapBlock == nil {
		newHeadSnapBlock = bc.genesisBlock
	}
	rawdb.WriteHeadFastBlockHash(db, newHeadSnapBlock.Hash())

	// Degrade the chain markers if they are explicitly reverted.
	// In theory we should update all in-memory markers in the
	// last step, however the direction of SetHead is from high
	// to low, so it's safe the update in-memory markers directly.
	bc.currentSnapBlock.Store(newHeadSnapBlock.Header())
	headFastBlockGauge.Update(int64(newHeadSnapBlock.NumberU64()))
}
```

So I thought that currentSnapBlock (which used in snapshot-sync) should be rewound too like head block does.
However, geth **does not rewind currentSnapBlock**.
I'm wondering why geth does not rewound the currentSnapBlock.

**Comment by rjl493456442** [comment]
The term "currentSnapBlock" refers to a specific block within the chain, complete with various components like associated receipts. However, it's important to note that the presence of the "currentSnapBlock" doesn't necessarily imply the existence of the corresponding state.

The objective of chain rewinding is to locate a block in the chain that possesses an associated state that is present. Once such a block is identified, the rewinding procedure retags that block as "HEAD BLOCK". This action effectively rewinds the state of the chain to a prior point.

It's worth highlighting that during this rewinding process, the segments of the chain above the "HEAD BLOCK" are retained. As a result, there is no reason to change the "HEAD SNAP BLOCK" flag.

**Comment by nothingmin** [comment]
To double check, if "currentSnapBlock" is set to specific block you already have components like transactions, block and receipts. Is that mean you can regenerate state for the height?

**Comment by rjl493456442** [comment]
> Is that mean you can regenerate state for the height?

Theoretically yes, you can rewind the chain to *below* this height and re-execute the blocks afterwards, so that you will get the state.

In practice, the cost for regenerating the state for a specific block is very high. Archive node is recommended in case the state availability is expected.

**Comment by nothingmin** [comment]
Beside Archive node, should I get sync from another node to get the latest state?

Actually, My problem happened in private network, one of my node can not sync from another nodes since its currentSnapBlock is same with another nodes(so that tdd is same with another nodes). 
It was not a serious problem since It resolved when the other nodes generates block for higher height.
I was just wondering whether is is intended or not
