### ISSUE TITLE
abigen incorrect uint32/big.Int bindings

### ISSUE THREAD

**Issue by rusenask** [ethereum/go-ethereum#2802]
#### System information

Geth version: 1.3.6
OS & Version: OSX
Commit hash : 9e323d65b20c32ab1db40e8dde7172826e0e9c45
#### Expected behaviour

On solidity contract I have "uint32 []" type, when abigen creates Go bindings - they are also "[]uint32" type on Go side. Even though it looks like it should work - the actual type of the data coming from the chain is of type " []*big.Int". 
#### Actual behaviour

When executing contract function from Go side - getting unmarshal error. Once I modify generated code myself (change types from []uint32 to []*big.Int) - everything works fine. 
I could look at it myself if someone gave me directions where to look, thanks.
#### Steps to reproduce the behaviour
1. Create a contract that returns " returns( uint32 [] yourList)  "
2. Create binding with abigen.
3. Execute that function. 
#### Backtrace

```
abi: cannot unmarshal []*big.Int in to []uint32
```

**Comment by karalabe** [comment]
I remember an issue like this being fixed a while ago. I'm guessing it was also merged in on the 1.4.x branches. Perhaps you should update to 1.4.9 and see with that? Although if you're using Native DApps I assume you use some develop sources already as 1.3.6 didn't have them at all. Please update your geth sources and retry.

**Comment by tbocek** [comment]
I had the same issue and I think I fixed it here: 

https://github.com/tbocek/go-ethereum/commit/04c5fb69fa8ff9b8d3b898a3aba132e77ea4bee7
https://github.com/tbocek/go-ethereum/commit/04c5fb69fa8ff9b8d3b898a3aba132e77ea4bee7

Can you check if that makes sense, and then I can submit a pull request

**Comment by tbocek** [comment]
Just upgraded to 1.5.x (current master) and still got the same isssue:

Failed to report temperatures: abi: cannot unmarshal []*big.Int in to []uint32. I'll submit a pull request
