### ISSUE TITLE
Unintended change in behavior for state copy/commit between v1.12.0 and v1.12.1

### ISSUE THREAD

**Issue by wuestholz** [ethereum/go-ethereum#28022]
#### System information

Geth version:  v1.12.1 and v1.12.2

#### Expected behaviour

When I run the following code snippet, I expect both printed balances (that is, `b1` and `b2`) to be 42:

```golang
db := rawdb.NewMemoryDatabase()
st1, _ := state.New(common.Hash{}, state.NewDatabaseWithConfig(db, &trie.Config{Preimages: true}), nil)
addr := common.HexToAddress("0xaaaa")
bal := big.NewInt(42)
st1.SetBalance(addr, bal)
useCommit := true
if useCommit {
	block := uint64(0)
	deleteEmptyObjects := false
	_, commitErr := st1.Commit(block, deleteEmptyObjects)
	if commitErr != nil {
		return
	}
}
b1 := st1.GetBalance(addr)
fmt.Printf("b1: %v\n", b1)
st2 := st1.Copy()
b2 := st2.GetBalance(addr)
fmt.Printf("b2: %v\n", b2)
```

This used to be the behavior for version v1.12.0. Specifically, for version v1.12.0, the following code snippet prints 42 twice:

```golang
db := rawdb.NewMemoryDatabase()
st1, _ := state.New(common.Hash{}, state.NewDatabaseWithConfig(db, &trie.Config{Preimages: true}), nil)
addr := common.HexToAddress("0xaaaa")
bal := big.NewInt(42)
st1.SetBalance(addr, bal)
useCommit := true
if useCommit {
	deleteEmptyObjects := false
	_, commitErr := st1.Commit(deleteEmptyObjects)
	if commitErr != nil {
		return
	}
}
b1 := st1.GetBalance(addr)
fmt.Printf("b1: %v\n", b1)
st2 := st1.Copy()
b2 := st2.GetBalance(addr)
fmt.Printf("b2: %v\n", b2)
```

#### Actual behaviour

In version v1.12.1 (and v1.12.2), the first code snippet prints the following:

```golang
b1: 42
b2: 0
```

Is this an intended change in behavior? Or is this a regression due to changes related to the new storage scheme?

Note that the output does not change between the two versions if I set `useCommit` to false.

#### Steps to reproduce the behaviour

Run the above code snippet for v1.12.0 (second snippet) and v1.12.1 (first snippet) and compare the output.

**Comment by rjl493456442** [comment]
We have made modifications to the statedb that require a shift in how it operates. Following a commit, the functionality of the statedb undergoes a significant change. It's important to note that the mutations made within the account trie and storage tries, becomes invisible after the commit. To continue working with the post-commit states, it becomes necessary to instantiate a new statedb instance, configuring it with a fresh root and an updated database.


You might naturally have a couple of questions stemming from this:

**Accurate GetBalance result after commit**: Despite the adjustments, the GetBalance function continues to provide accurate results even after a commit. This can be attributed to the fact that the account data relevant to the GetBalance operation is cached within the statedb instance. Consequently, the cached data remains accessible and usable even after a commit, enabling GetBalance to function as expected.

**Limitations of Deep-Copied Committed Statedb**: On the other hand, attempts to leverage a deep-copied version of the statedb post-commit yield unsatisfactory results. The rationale behind this is that the deep copy process does not copy the cached account data(specifically, the stateObjects map). As a result, any modifications or mutations that were made during the commit are not observable via the copied statedb, leading to discrepancies and a lack of visibility into these changes through the trie structure.

**Comment by wuestholz** [comment]
@rjl493456442 Thanks for the reply and clarification!

Would the following rewrite of the code accurately replicate the old behavior?

```golang
db := rawdb.NewMemoryDatabase()
st1, _ := state.New(common.Hash{}, state.NewDatabaseWithConfig(db, &trie.Config{Preimages: true}), nil)
addr := common.HexToAddress("0xaaaa")
bal := big.NewInt(42)
st1.SetBalance(addr, bal)
useCommit := true
if useCommit {
	block := uint64(0)
	deleteEmptyObjects := false
	commitRoot, commitErr := st1.Commit(block, deleteEmptyObjects)
	if commitErr != nil {
		return
	}
	st1, _ = state.New(commitRoot, st1.Database(), nil)
}
b1 := st1.GetBalance(addr)
fmt.Printf("b1: %v\n", b1)
st2 := st1.Copy()
b2 := st2.GetBalance(addr)
fmt.Printf("b2: %v\n", b2)
```

This prints 42 twice, but I'm not quite sure if that's what you were suggesting.

**Comment by rjl493456442** [comment]
It's correct, you re-create a new statedb after commit.

**Comment by wuestholz** [comment]
@rjl493456442 Thanks for confirming! Do you expect the rewritten code (that is, replacing all commits with commits that are followed by new state creations) to be significantly less efficient (with respect to memory and CPU usage)?

The rewritten code seems less efficient to me, but I don't have an intuitive understanding of what's going on under the hood. If it is less efficient I've also considered reducing the number of commit operations in my codebase (for instance, by replacing them with calls to `IntermediateRoot` where possible). However, I don't quite understand what operations require a commited state and have run into weird bugs in the past that were magically fixed by a commit operation... (Note that I'm only using in-memory databases in my codebase.) Could you perhaps give me some pointers?

**Comment by rjl493456442** [comment]
Fundamentally, the final step of a state transition is the "Commit" phase, during which all pending state mutations are flushed to the underlying trie database.

A state transition aligns with a block's execution process. This entails establishing a statedb using the state root of the parent block, executing all transactions sequentially, and end in the invocation of the "Commit" phase. In the mean time, "IntermediateRoot" can be invoked arbitrary times, which just compute the state root at that point without flushing any mutations to database.

Regarding the efficiency, I don't think there is a huge overhead by re-creating a new statedb. All the newly mutated data will be cached in the trie database level, reading data from memory is a lot faster than disk read.

**Comment by wuestholz** [comment]
@rjl493456442 Thanks a lot!

Would it be accurate to say that commiting serves two main purposes, namly (1) flushing the current state to persistent storage (typically disk) and (2) snapshotting the current state by assigning a state root that can be referred to in later operations (for instance, when processing the next block)?

In my use case, I'm primarily executing a few transactions (possibly from different blocks) on a state that easily fits into memory. So, it seems like the first purpose is not really needed. The second purpose seems to be only needed for dumping the state (say, the final state after executing a few transactions) by commiting the state and using a trie iterator to dump all the accounts. I'm wondering if I can avoid such commits by using `DumpToCollector` (which seems to work directly on the underlying trie) on the (non-commited) state instead of commiting, opening the trie, and iterating, etc. What do you think?

**Comment by rjl493456442** [comment]
I think it's possible to iterate states by using `DumpToCollector ` without commit. But honestly commit won't cause too much.

**Comment by wuestholz** [comment]
Thanks! I'll probably need to run some experiments first, but I'll let you know if more questions pop up.

**Comment by rjl493456442** [comment]
I will just close this ticket. Feel free to reopen a new one!
