### ISSUE TITLE
Fatal: Unable to attach to remote geth: dial unix /home/bsc/.ethereum/geth.ipc: connect: connection refused

### ISSUE THREAD

**Issue by cexland** [ethereum/go-ethereum#28038]
Getting "Fatal: Unable to attach to remote geth: dial unix /home/bsc/.ethereum/geth.ipc: connect: connection refused" when running ./geth_linux attach

**Comment by holiman** [comment]
Well, this is not a bsc support channel, but if I were you I'd check the permissions on it 
```
ls -la /home/bsc/.ethereum/geth.ipc
```
And also check what groups you're in
```
groups
```
