### ISSUE TITLE
github.com/ethereum/go-ethereum@latest (v1.12.2) indirectly requires unknown version github.com/kataras/iris/v12@v12.2.0-beta5

### ISSUE THREAD

**Issue by adriangarrote-zh** [ethereum/go-ethereum#28036]
Hey guys! I am experiencing this error on my side as well. 
I think it has indeed an indirect dependency with that failing project version. 

It is a dependency for sentry-go@v0.18.0
` go mod graph | grep kataras/iris      
github.com/getsentry/sentry-go@v0.18.0 github.com/kataras/iris/v12@v12.2.0-beta5`

which is a dependency for go-ethereum
`go mod graph | grep sentry-go@v0.18.0
github.com/ethereum/go-ethereum@v1.12.2 github.com/getsentry/sentry-go@v0.18.0`

_Originally posted by @adriangarrote-zh in https://github.com/ethereum/go-ethereum/issues/27943#issuecomment-1700800229_

**Comment by karalabe** [comment]
Very strange, no idea how that dep ended up in our codebase. Seems it originated from some pebble code, but can't find the version either. Regenerating all the indirect deps now, should fix it. Please check the master branch afterwards.

**Comment by adriangarrote-zh** [comment]
it fixed the issue, thanks sir! @karalabe
