### ISSUE TITLE
Abigen reuses nonce

### ISSUE THREAD

**Issue by pieroarkana** [ethereum/go-ethereum#28045]
#### System information

Geth version: 1.12.2-stable-bed84606
CL client & version: ethereum APU, github.com/ethereum/go-ethereum v1.10.26
OS & Version: Linux Fedora release 38 (Thirty Eight)
Commit hash : (if `develop`)

solc version 0.8.8
abigen version 1.12.2-stable-bed84606

#### Expected behaviour
We have a smart contract called C1 which uses another smart contract called RoleLib:

`using RoleLib for uint8;`

We compile it with solc:

`solc --combined-json abi,bin ./solidity/c1/C1.sol -o deploy/c1 --base-path .`

and then generate the deployer with abigen:
abigen --combined-json=./deploy/c1/combined.json --pkg=c1 --out=deploy/c1/C1.go``

which produces the following code, which obviously reuses the nonce in auth:

```
func DeployC1(auth *bind.TransactOpts, backend bind.ContractBackend) (common.Address, *types.Transaction, *C1, error) {
parsed, err := C1MetaData.GetAbi()
if err != nil {
    return common.Address{}, nil, nil, err
}
if parsed == nil {
    return common.Address{}, nil, nil, errors.New("GetABI returned nil")
}

roleLibAddr, _, _, _ := DeployRoleLib(auth, backend)
C1Bin = strings.ReplaceAll(C1Bin, "__$3897a2e8704322a01bd00e453622dcaf8a$__", roleLibAddr.String()[2:])

address, tx, contract, err := bind.DeployContract(auth, *parsed, common.FromHex(C1Bin), backend)
if err != nil {
    return common.Address{}, nil, nil, err
}
return address, tx, &C1{C1Caller: C1Caller{contract: contract}, C1Transactor: C1Transactor{contract: contract}, C1Filterer: C1Filterer{contract: contract}}, nil

}
```

The expected behavior is that we call DeployC1 and the contract gets deployed

#### Actual behaviour
The actual behavior is that we get this error from the node:

`the tx doesn't have the correct nonce. account has nonce of: 4 tx has nonce of: 3`

#### Steps to reproduce the behaviour

call DeployC1 (or try to deploy any contract that uses another contract

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by Deacon77** [comment]
897998

**Comment by jsvisa** [comment]
Please provide the content `C1.sol` and `RoleLib`, so other people can reproduce it.

**Comment by jsvisa** [comment]
Please provide the content `C1.sol` and `RoleLib`, so other people can reproduce it.
