### ISSUE TITLE
How to run full archive Geth to sync from the beginning?

### ISSUE THREAD

**Issue by Aracki** [ethereum/go-ethereum#28050]
I've started `v1.12.0` Geth with following flags:
```
            "--mainnet",
            "--datadir=/root/.ethereum/mainnet-geth",
            "--syncmode=full",
            "--gcmode=archive",
            "--cache=65536",
            "--http",
            "--http.addr=0.0.0.0",
            "--http.corsdomain=*",
            "--http.vhosts=*",
            "--http.port=8545",
            "--http.api=engine,eth,net,web3,admin,debug,personal,txpool",
            "--ws",
            "--ws.addr=0.0.0.0",
            "--ws.origins=*",
            "--ws.port=8546",
            "--ws.api=engine,eth,net,web3,admin,debug,personal,miner,txpool",
            "--port=30303",
            "--txlookuplimit=0",
            "--rpc.allow-unprotected-txs",
            "--cache.preimages",
            "--authrpc.port=8551",
            "--authrpc.jwtsecret=/root/.ethereum/jwt.secret",
```

In the logs I can see:

> New local node record lines

started from *seq=1,692,800,175,905*, and after 7 days it's *seq=1,692,800,176,877*.

Also I'm getting warnings:
> Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!

I am running lighthouse also, but it's latest beacon slot at the moment is 3,463,520 (out of 7mil currently on chain).

Does it mean I need to wait for Lighthouse to be in sync with the network or I need to run Geth with some special flags in order to tell it to sync blocks which happened before The Merge?

**Comment by yorickdowne** [comment]
Lighthouse needs to be synced. This takes a few days. You can checkpoint sync Lighthouse and tell it to backfill back to genesis so it is an archive, and Geth can start sync sooner.

**Comment by holiman** [comment]
> Lighthouse needs to be synced.

Actually, if you are doing a block by block sync, you do not _need_ a CL node until towards the end. 
```
    --synctarget value            
          File for containing the hex-encoded block-rlp as sync target(dev feature)
```
It is possible to just specify a synctarget, and geth will "pretend" that a CL gave it that target, and it will sync towards it. Only when we do state-sync (snap-sync) do we need regular updates in order to move the pivot-block forward, but moving the target forward is not needed when doing a block by block sync. 

But yeah, it's a bit non-userfriendly-UX, so it's probably simpler to just use a synced CL.
