### ISSUE TITLE
background error: pebble/table: invalid table (bad magic number)

### ISSUE THREAD

**Issue by rayn316** [ethereum/go-ethereum#28057]
#### System information

Geth version: geth version 1.12.2-stable-bed84606
CL client & version: e.g. lighthouse@v4.3.0-dfcb336
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Normal sync

#### Actual behaviour
1. At around block height 8619871, the node seems to stop syncing, the lighthouse looks broken, when I resync the lighthouse, the goerli log is not synced and keeps printing this error
2. Before using debug.setHead(hex) to set to 1000 blocks and after restarting, the node still prints this error, but at the synchronization block height

#### Steps to reproduce the behaviour
Run this command to sync the goerli archive node from scratch
```
serviceName=goerli-archive
listeningAddr='0.0.0.0'
serviceCmd="/node/archive/goerli/bin/geth --datadir /node/archive/goerli/geth --goerli --syncmode='full' --gcmode=archive --rpc.evmtimeout='10s' --txlookuplimit=0 --rpc.gascap=600000000 --light.maxpeers=0 --http.vhosts=* --http.corsdomain=* --http --http.addr ${listeningAddr} --http.api eth,net,web3,debug,trace,txpool --ws.api=eth,net,web3,debug,trace,txpool --ws --ws.addr ${listeningAddr} --port 21030 --http.port 21031 --ws.port 21032 --authrpc.port 21033"


serviceName=goerli-archive-bn
serviceCmd="/node/archive/goerli/bin/lighthouse bn -d /node/archive/goerli/lighthouse --network goerli --execution-endpoint 'http://127.0.0.1:21033' --execution-jwt '/node/archive/goerli/geth/geth/jwtsecret' --checkpoint-sync-url=https://sync-goerli.beaconcha.in --port 21039 --http --http-port 21037"
```

#### Backtrace

````
Sep 04 07:31:10 geth[2006631]: 2023/09/04 07:31:10 background error: pebble/table: invalid table (bad magic number)
````

When submitting logs: please submit them as text and not screenshots.

**Comment by jsvisa** [comment]
Seems like the sstable in pebble is corrupted, ref https://github.com/cockroachdb/pebble/issues/181

Did this issue arise after you forced geth to restart(eg: `kill -9`)

**Comment by sundafa** [comment]
Maybe, look at the service status, there is an error log in ln, but the goerli data is damaged first
It may be that it takes up too much memory and is killed.

**Comment by holiman** [comment]
> Maybe, look at the service status, there is an error log in ln, but the goerli data is damaged first

Have you made the log files available somewhere?

**Comment by sundafa** [comment]
After checking the system situation, it seems that the system is stuck and then automatically restarts the system, causing data corruption.
@holiman

**Comment by holiman** [comment]
> it seems that the system is stuck and then automatically restarts the system, causing data corruption.

Well, geth can only shutdown, the "automatically restarts the system" is done by whatever solution you have implemented on your end. 

The root cause here was a data-corruption _below_ geth, as in, not the geth-data but in the actual files maintained by the database-engine. Nothing we can do from our side. Most likely culprit is a damaged/deteriorated disk.
