### ISSUE TITLE
How to know my Geth node is syncing the latest block with other peers?

### ISSUE THREAD

**Issue by tiennampham23** [ethereum/go-ethereum#28061]
I run my own Geth, but sometimes I stop it and re-run after that. I have my own customized subscribe `newHead` on my Geth to know the latest block.
But when syncing with other peers, `newHead` will emit the old block( vs. the current state of the blockchain, compared with other nodes).

What's the function that describes the latest block in my node with each other? If I know that, I can ignore the old block that was emitted by the subscription.

**Comment by jsvisa** [comment]
> newHead will emit the old block vs. the current state of the blockchain(compared with other nodes).

Could this be due to a ChainReorg?

> What's the function that describes the latest block in my node with each other

AFAIK, `eth_blockNumber` returns your latest block numbrer

**Comment by tiennampham23** [comment]
No, my question is:
- The current block of the global state(from other nodes) is X
- My latest block is X - 5

The head subscription will emit the block from X - 4 to catch up with the global latest block. When I ask this question, I don't know how to check whether X-4 is the latest state on the global state or not.

Currently, I believe that I can make use of the block_time alongside the current timestamp. The block_time must be in the range from now() - 12 to now()
