### ISSUE TITLE
abigen doesn't support imports

### ISSUE THREAD

**Issue by Arachnid** [ethereum/go-ethereum#2806]
Because abigen invokes the solidity compiler by passing a string, the compiler has no path to work with for imports. It'd be really useful if it supported imports relative to the directory of the root contract being compiled.

**Comment by zelig** [comment]
+1

**Comment by fjl** [comment]
I already have the code changes for this, will submit shortly.

**Comment by fjl** [comment]
Fix released in 1.5.0.
