### ISSUE TITLE
`eth_call` sent with field not in the API specification

### ISSUE THREAD

**Issue by nisdas** [ethereum/go-ethereum#28077]
#### System information

Geth version: `1.12.2`
CL client & version: `Prysm v4.0.8`
OS & Version: Linux

#### Expected behaviour

According to https://github.com/ethereum/execution-apis/blob/main/src/schemas/transaction.yaml#L25 each `eth_call` message 
sent using geth's bindings should be representing input data as `input` in the json output. 

#### Actual behaviour

However this is currently not the case, this is instead still represented using `data` via the ethclient bindings. 
https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go#L622

Any call message parameters will be represented with `data` instead of `input`. 

#### Steps to reproduce the behaviour

An example of this is over here: https://github.com/prysmaticlabs/prysm/issues/12850

Prysm uses the ethclient bindings to make contract calls to the deposit contract. This has lead to compatibility 
issues with nethermind as they have had to revert a change in order to remain compatible with prysm. 

#### Backtrace

N.A

**Comment by holiman** [comment]
I agree, 'input' is The Way. 

Refs: https://github.com/ethereum/go-ethereum/issues/15628
https://github.com/ethereum/go-ethereum/blob/master/signer/core/apitypes/types.go#L93
