### ISSUE TITLE
Strange peer address in a private network

### ISSUE THREAD

**Issue by wawrzek** [ethereum/go-ethereum#2807]
#### System information

Geth version: `geth 1.4.9`
OS & Version: Linux - Ubuntu 16.04 LTS
Commit hash : (if `develop`)

#### Problem description
In a privet network occasionally (at least once in two different networks) we noticed 'broken' peer addresses, as in first line before.  

```
I0712 11:13:07.108367 eth/fetcher/fetcher.go:750] Peer ;+��: parent []30663236663563643930393337653564] of block #901 [ed3cf850…] unknown
I0712 11:13:07.108441 eth/fetcher/fetcher.go:731] Peer 0f26f5cd90937e5d: queued block #901 [40c1d93a…], total 1
```

**Comment by karalabe** [comment]
Oops, the log message formatting is off. https://github.com/ethereum/go-ethereum/blob/master/eth/fetcher/fetcher.go#L750 The block hash and peer parameters are mixed up, hence the weird log. Thanks for reporting this, will fix.

**Comment by karalabe** [comment]
Fixed on develop.
