### ISSUE TITLE
Disable CORS by default

### ISSUE THREAD

**Issue by kumavis** [ethereum/go-ethereum#281]
CORS support is necessary to access from the browser. However, it exposes the rpc to any website you visit. This is a security risk.

**Comment by tgerring** [comment]
Relates to #331

**Comment by frozeman** [comment]
I agree, when we release, the CORS  headers should only allow localhost connections (for development and swarm dapp).

**Comment by obscuren** [comment]
CORS will be enabled in Mist by default. CORS will be disabled in the CLI by default. The CORS header will be settable through a command line flag

https://github.com/ethereum/go-ethereum/issues/394

**Comment by frozeman** [comment]
Though CORS are no real security, as its only enforced by the browser the user uses.

**Comment by kumavis** [comment]
@frozeman yes good point

**Comment by tgerring** [comment]
Superseded by #394
