### ISSUE TITLE
JSONLogger emitting two lines on opcode failure

### ISSUE THREAD

**Issue by s1na** [ethereum/go-ethereum#28128]
As you can see at the end of this trace, we emit an event before opcode execution (notice the weird opcode name too).However operation exec fails and we emit a fault event with the error. This is unnecessary and is incompatible with the spec from [execution-specs](https://github.com/ethereum/execution-specs). I think we should change this logic, remove `CaptureFault` and emit `CaptureState` after opcode execution (while keeping the values such as memory, stack to pre-execution values).

```
{"pc":0,"op":127,"gas":"0x54364e77","gasCost":"0x3","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH32"}
{"pc":33,"op":68,"gas":"0x54364e74","gasCost":"0x2","memSize":0,"stack":["0x0"],"depth":1,"refund":0,"opName":"DIFFICULTY"}
{"pc":34,"op":127,"gas":"0x54364e72","gasCost":"0x3","memSize":0,"stack":["0x0","0x20000"],"depth":1,"refund":0,"opName":"PUSH32"}
{"pc":67,"op":127,"gas":"0x54364e6f","gasCost":"0x3","memSize":0,"stack":["0x0","0x20000","0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"],"depth":1,"refund":0,"opName":"PUSH32"}
{"pc":100,"op":127,"gas":"0x54364e6c","gasCost":"0x3","memSize":0,"stack":["0x0","0x20000","0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","0x1"],"depth":1,"refund":0,"opName":"PUSH32"}
{"pc":133,"op":127,"gas":"0x54364e69","gasCost":"0x3","memSize":0,"stack":["0x0","0x20000","0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","0x1","0x1"],"depth":1,"refund":0,"opName":"PUSH32"}
{"pc":166,"op":127,"gas":"0x54364e66","gasCost":"0x3","memSize":0,"stack":["0x0","0x20000","0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","0x1","0x1","0x0"],"depth":1,"refund":0,"opName":"PUSH32"}
{"pc":199,"op":127,"gas":"0x54364e63","gasCost":"0x3","memSize":0,"stack":["0x0","0x20000","0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","0x1","0x1","0x0","0x945304eb96065b2a98b57a48a06ae28d285a71b5"],"depth":1,"refund":0,"opName":"PUSH32"}
{"pc":232,"op":18,"gas":"0x54364e60","gasCost":"0x3","memSize":0,"stack":["0x0","0x20000","0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","0x1","0x1","0x0","0x945304eb96065b2a98b57a48a06ae28d285a71b5","0x10000000000000000000000000000000000000000"],"depth":1,"refund":0,"opName":"SLT"}
{"pc":233,"op":49,"gas":"0x54364e5d","gasCost":"0xa28","memSize":0,"stack":["0x0","0x20000","0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","0x1","0x1","0x0","0x0"],"depth":1,"refund":0,"opName":"BALANCE"}
{"pc":234,"op":182,"gas":"0x54364435","gasCost":"0x0","memSize":0,"stack":["0x0","0x20000","0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","0x1","0x1","0x0","0x0"],"depth":1,"refund":0,"opName":"opcode 0xb6 not defined"}
{"pc":234,"op":182,"gas":"0x54364435","gasCost":"0x0","memSize":0,"stack":["0x0","0x20000","0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","0x1","0x1","0x0","0x0"],"depth":1,"refund":0,"opName":"opcode 0xb6 not defined","error":"invalid opcode: opcode 0xb6 not defined"}
{"output":"","gasUsed":"0x54364e77","error":"invalid opcode: opcode 0xb6 not defined"}
```

While creating this ticket I also noticed that the StructLogger is not emitting a fault event at all. So it's not possible to capture the opcode error.

A separate issue (this ticket is a braindump of discussion with Guru from execution specs) is even on an opcode validation error where no gas is charged we're emitting the static cost of the opcode.

**Edit:** after discussion we decided NOT to modify these behaviors. The only outstanding item of this ticket is to fix the structLogger not emitting a fault event issue.

**Comment by holiman** [comment]
This is known, and consumers need to deal with it. For example, the goevmlab fuzzer-engine does it here: https://github.com/holiman/goevmlab/blob/master/evms/geth.go#L137 . For the record, Nimbus-eth1 has a similar quirk: https://github.com/holiman/goevmlab/pull/104#issuecomment-1703761097. 

I think we can close this as "wontfix", BUT, if you have some neat solution to this problem, then sure, we can get it fixed.   

> I think we should change this logic, remove CaptureFault and emit CaptureState after opcode execution (while keeping the values such as memory, stack to pre-execution values).

Maybe, can't really say until I've played with it a bit. 

> While creating this ticket I also noticed that the StructLogger is not emitting a fault event at all. So it's not possible to capture the opcode error.

Sounds like a bug, yes. 


> A separate issue s even on an opcode validation error where no gas is charged we're emitting the static cost of the opcode.

I don't follow. When does "no gas is charged" ever occur?

**Comment by gurukamath** [comment]
> I don't follow. When does "no gas is charged" ever occur?

I'm not sure if "no gas is charged" is the right way to put it but the concrete example I had in mind is one where `stack underflow` happens in an opcode and we are unable to calculate the actual gas cost of the opcode. In such cases, the geth trace emits the static gas part, even though the evm errors before we actually get to charging the gas.

**Comment by holiman** [comment]
Right -- yes, there are a lot of cases where we are unable to, or it's not even meaningful to speak about gas cost. In many of those cases, we only know the static cost. 

For example an `MSTORE` which would cause allocation in terabytes, or uint overflow during gas calculation. There's no point in geth trying to determine whether the cost is `n` or `m` bazillion. 

I personally don't consider it behaviour in need of fixing.

**Comment by s1na** [comment]
> I think we can close this as "wontfix", BUT, if you have some neat solution to this problem, then sure, we can get it fixed.

@holiman right so the idea I was considering at first has the serious drawback we will need to copy stack, memory and return data on every opcode. But, it is possible to fix this in the logger itself, wdyt? https://github.com/s1na/go-ethereum/commit/1bfc8763a376144b59bd938e517f1be8426601ca

Re gas cost on stack validation error, I think we should emit 0 and the diff is very simple. But not a hill I will die on:

```patch
diff --git a/core/vm/interpreter.go b/core/vm/interpreter.go
index 873337850e..41d4fa2691 100644
--- a/core/vm/interpreter.go
+++ b/core/vm/interpreter.go
@@ -172,19 +172,19 @@ func (in *EVMInterpreter) Run(contract *Contract, input []byte, readOnly bool) (
 	for {
 		if debug {
 			// Capture pre-execution values for tracing.
-			logged, pcCopy, gasCopy = false, pc, contract.Gas
+			logged, pcCopy, gasCopy, cost = false, pc, contract.Gas, 0
 		}
 		// Get the operation from the jump table and validate the stack to ensure there are
 		// enough stack items available to perform the operation.
 		op = contract.GetOp(pc)
 		operation := in.table[op]
-		cost = operation.constantGas // For tracing
 		// Validate stack
 		if sLen := stack.len(); sLen < operation.minStack {
 			return nil, &ErrStackUnderflow{stackLen: sLen, required: operation.minStack}
 		} else if sLen > operation.maxStack {
 			return nil, &ErrStackOverflow{stackLen: sLen, limit: operation.maxStack}
 		}
+		cost = operation.constantGas // For tracing
 		if !contract.UseGas(cost) {
 			return nil, ErrOutOfGas
 		}
```

**Comment by holiman** [comment]
@s1na the fix there addresses the secondary problem, the "we output wrong (static only) gas in some scenarios". However, I wouldn't call it "fixing" it, because it still output the wrong gas: now it outputs `0` gas, which is always wrong, whereas previously it would only be wrong for opcodes which have a dynamic part.

**Comment by holiman** [comment]
Ok, I missed the linked commit when I commented. Hm, neat idea, but also kind of quirky in the way that the logger is one step behind all the time.

**Comment by s1na** [comment]
This was discussed on standup and it was decided it won't be fixed for now. If we emit the execution error in the same event it means we will be mixing pre-execution and post-execution results in one event. Also it's easy for callers to check for this condition. If a PC is being repeated on 2 consecutive lines an error during execution has happened.
