### ISSUE TITLE
Are txs received through eth_sendRawTransaction local? Enforcing min gas price in miner.

### ISSUE THREAD

**Issue by jp-imx** [ethereum/go-ethereum#28125]
It seems like [api_backend.go](https://github.com/ethereum/go-ethereum/blob/master/eth/api_backend.go#L284-L286) marks transactions coming from [SendRawTransaction](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1940-L1946) as `local`. 

The side-effect of this is that the [legacypool](https://github.com/ethereum/go-ethereum/blob/master/core/txpool/legacypool/legacypool.go#L588-L590) sets the `MinTip` to zero, before calling the validation logic, so it's not possible to enforce a minimum gas price in the miner.

**Comment by holiman** [comment]
Answer here: https://github.com/ethereum/go-ethereum/pull/28138#issuecomment-1722809575

**Comment by jp-imx** [comment]
@holiman for visibility I added [this comment](https://github.com/ethereum/go-ethereum/pull/28138#issuecomment-1780331031).
