### ISSUE TITLE
v1.13.0 ignores snapshot flag

### ISSUE THREAD

**Issue by schonex** [ethereum/go-ethereum#28131]
#### System information

geth v1.13.0
Linux

#### Expected behaviour
`--snapshot=false` disables snapshotting

#### Actual behaviour
It is ignored since default sync mode is now snap and that causes the snapshot flag to be overridden 

#### Steps to reproduce the behaviour
`--snapshot=false`

on the other hand
`--syncmode full --snapshot=false` stops snapshotting

**Comment by rjl493456442** [comment]
Yes, it's expected. I think we have this logic for a few years tho.

**Comment by karalabe** [comment]
You don't want to rely on setting snapshotting to false, it's going away soon.
