### ISSUE TITLE
Better out of gas error message

### ISSUE THREAD

**Issue by miohtama** [ethereum/go-ethereum#28136]
# Rationale

GoEthereum reports "not enough gas" as

```
{'code': -32000, 'message': 'insufficient funds for gas * price + value'}
```

This is one of the most popular error messages new blockchain developers face. ethereum.stackexchange.com alone has more than 350 questions on the topic. However, because of the vagueness of the error message, it is hard to tell what's wrong.

Based on the good error message examples of Rust, etc. it should be pretty straightforward to make this error message friendlier, telling users more on the underlying reason of the problem and how to fix it.

## Why should this feature exist?

Make it easier for Dapp developers to enter the industry.

## What are the use-cases?

Developers can self-solve problems instead of need to ask for help.

# Implementation

Mode this error message to tell

- What is the sufficient amount of gas GoEthereum expects
- What is the available gas money on the account

Example:

```
{'code': -32000, 'message': 'Not enough ETH to send transactions. Need 0.00123 ETH, the account has 0.00123 ETH. Transaction value is 0 ETH. Gas price is 14 Gwei. The formula used to calculate the required amount is gas * price + value. '}
```

**Comment by GlacialFlower7** [comment]
Yes. I a fed up with this obscure issue, and not even sure it really means what the message says. Can devs please do something?

**Comment by jsvisa** [comment]
Which go-ethereum version are you running, I think this feature is implemented after [v1.12.1](https://github.com/ethereum/go-ethereum/releases/tag/v1.12.1)

**Comment by miohtama** [comment]
@jsvisa Interesting, looks like I was too late to order!

**Comment by 0x0elliot** [comment]
++!

**Comment by holiman** [comment]
Seems fixed already
