### ISSUE TITLE
backends.NewSimulatedBackend does not support PUSH0

### ISSUE THREAD

**Issue by ARR552** [ethereum/go-ethereum#28144]
#### System information

Geth version: `v1.13.1`
OS & Version: Linux

#### Expected behaviour
Using this code
```
Import (
"github.com/0xPolygonHermez/zkevm-node/etherman/smartcontracts/mockverifier"
"github.com/ethereum/go-ethereum/accounts/abi/bind/backends"
"github.com/ethereum/go-ethereum/common"
"github.com/ethereum/go-ethereum/core"
)
```
```
genesisAlloc := map[common.Address]core.GenesisAccount{
		address: {
			Balance: balance,
		},
	}
	blockGasLimit := uint64(999999999999999999)
client := backends.NewSimulatedBackend(genesisAlloc, blockGasLimit)
rollupVerifierAddr, _, _, err := mockverifier.DeployMockverifier(auth, client)
if err != nil {
		log.Fatal(err)
}
```
This code should work but seems the backends doesn't support the opcode PUSH0

#### Actual behaviour

The current behaviour is an error that says:
```
 invalid opcode: PUSH0
```

**Comment by MariusVanDerWijden** [comment]
Yes, the simulated backend is kinda stuck pre-merge. We thought about refactoring the simulated backend at some point to use the post-merge architecture

**Comment by arnaubennassar** [comment]
This is still a problem on `v1.14.5`

**Comment by MariusVanDerWijden** [comment]
Hmm thats weird, simulatedbackend should be post-merge now
