### ISSUE TITLE
[Path Scheme] - Importing new chain segment insanely slow, can't repro

### ISSUE THREAD

**Issue by SjonHortensius** [ethereum/go-ethereum#28143]
#### System information

Geth version: `1.13.1-stable`
CL client & version: lighthouse
OS & Version: archLinux

#### Expected behaviour
Geth should be able to follow the chain

#### Actual behaviour
After upgrading to 1.13.1 the "imported new chain segment" is insanely slow. Where I normally see 200+ mgasps, it is now down to `0.2` - `0.8` leading to geth being unable to keep up. The cpu usage is also high - up to spikes of `2200%`

#### Backtrace

````
Imported new potential chain segment     number=18,161,486 hash=4849f9..274fca blocks=1 txs=134 mgas=20.869 elapsed=26.068s    mgasps=0.801 age=10m48s snapdiffs=8.20MiB triediffs=169.68MiB triedirty=39.13MiB
Chain head was updated                   number=18,161,485 hash=3232ef..9a2634 root=9d7f24..5b7632 elapsed=2.962453ms age=11m
Ignoring already known beacon payload    number=18,161,486 hash=4849f9..274fca age=10m48s
Ignoring already known beacon payload    number=18,161,486 hash=4849f9..274fca age=10m48s
Ignoring already known beacon payload    number=18,161,486 hash=4849f9..274fca age=10m48s
Imported new potential chain segment     number=18,161,487 hash=518405..0fd51d blocks=1 txs=98  mgas=10.133 elapsed=14.449s    mgasps=0.701 age=10m51s snapdiffs=8.23MiB triediffs=169.80MiB triedirty=39.35MiB
Ignoring already known beacon payload    number=18,161,487 hash=518405..0fd51d age=10m51s
Chain head was updated                   number=18,161,486 hash=4849f9..274fca root=1f994e..2121fc elapsed=4.587233ms age=11m3s
Imported new potential chain segment     number=18,161,488 hash=32412a..9d8e8e blocks=1 txs=141 mgas=12.713 elapsed=23.759s    mgasps=0.535 age=11m3s  snapdiffs=8.25MiB triediffs=168.32MiB triedirty=40.46MiB
Ignoring already known beacon payload    number=18,161,488 hash=32412a..9d8e8e age=11m3s
Ignoring already known beacon payload    number=18,161,488 hash=32412a..9d8e8e age=11m3s
Chain head was updated                   number=18,161,487 hash=518405..0fd51d root=f12e31..858a1e elapsed=6.297384ms age=11m15s
Peer delivering stale transactions       peer=d03b204073583ec80a47d4b36e97be355a4e32312fdf219def3af78aadf0ef11 rejected=47
Snapshot extension registration failed   peer=f50109e1 err="peer connected on snap without compatible eth support"
Peer delivering stale transactions       peer=d03b204073583ec80a47d4b36e97be355a4e32312fdf219def3af78aadf0ef11 rejected=43
Peer delivering stale transactions       peer=d03b204073583ec80a47d4b36e97be355a4e32312fdf219def3af78aadf0ef11 rejected=47
````

downgrading to `1.13.0` fixes the issue for me

**Comment by rjl493456442** [comment]
What state scheme you are using?

**Comment by SjonHortensius** [comment]
this is with pbss enabled, I forgot to mention that

**Comment by karalabe** [comment]
Please attach a Geth console to your node (`geth attach` or `geth attach path-to-your-geth.ipc-file` if you stored your datadir on a non-default location), and please run `debug.cpuProfile("geth.cpu", 60)`. Wait 60 seconds and when it says `Done writing CPU profile                 dump=geth.cpu`, please attach that for us?

**Comment by karalabe** [comment]
I've seen it happen to my node in the middle of the night, but it suddenly fixed itself after 3 hours and I can't reproduce it. No idea where it might originate from.

**Comment by karalabe** [comment]
@SjonHortensius Did the downgrade fit it though, or simply a restart?

**Comment by SjonHortensius** [comment]
I'll upgrade and restart - see if it happens again so I can hopefully get a cpuProfile - thanks for the hint

**Comment by karalabe** [comment]
Was only the first block slow, or the following too? Could you try to get us that cpu profile?

**Comment by SjonHortensius** [comment]
@karalabe yes I'm running the new version hoping for the same problem. The log I posted was from the first occurrence, yesterday.

After that first block I see hundreds of `Peer delivering stale transactions` and then the second block is just as slow:
```
[09-18|09:55:42.005] Imported new potential chain segment     number=18,161,468 hash=c2c898..20bb13 blocks=1 txs=105 mgas=29.950 elapsed=2m27.173s mgasps=0.204 age=3m43s snapdiffs=6.57MiB triediffs=172.14MiB triedirty=30.65MiB
```

**Comment by fjl** [comment]
The `tried` counter is not cumulative, it reports the attempts since the last log message.

**Comment by karalabe** [comment]
@SjonHortensius Did it ever happen again?

**Comment by SjonHortensius** [comment]
I've setup monitoring on all my nodes, but unfortunately this hasn't happened again. It must have been caused by an external factor which I haven't found yet

Would you prefer closing this issue for now? I'll reopen it if I successfully get a cpuProfile to look at

**Comment by karalabe** [comment]
No no, it did happen to me too, so leave it open IMO.

**Comment by karalabe** [comment]
Been investigating this for 3 days straight now. There's a fairly long thread about it here: https://github.com/cockroachdb/pebble/issues/2945.

It *seems* the issue might originate from Pebble, since we also upgraded it in 1.13. I've bumped Pebble up to latest version in geth master to see if that also hits it. I personally couldn't yet trigger it, but lets see. Just an FYI if this happens again.

**Comment by SjonHortensius** [comment]
I can confirm your observation in the related issue that the problem only occurs when freshly starting the instance. It is fairly reproducible by restart geth until it fails, I think ~ 50% of the starts fail for me

**Comment by karalabe** [comment]
@SjonHortensius Could you try running Geth master branch and see if it still reproduces with it? I couldn't hit the issue again on my setup.

**Comment by SjonHortensius** [comment]
@karalabe I'm unable to reproduce this with master. Do you intend to find out what specific change in pebble might have caused this?
