### ISSUE TITLE
Memory leak in archive node v1.13.1

### ISSUE THREAD

**Issue by gleb498** [ethereum/go-ethereum#28156]
#### System information

Geth version: v1.13.1
CL client & version: lighthouse@v4.4.1
OS & Version: Linux
RAM: 40GB
CPU(s): 12

#### Problem
In archive node mode (mainnet), RAM leaks and the node process crashes. We detected this problem based on Grafana statistics. Node crashes ones a day. Here are the node launch parameters:
```
 ["geth", "--metrics", "--metrics.port=6060", "--metrics.expensive", "--metrics.addr=0.0.0.0",
"--authrpc.addr=0.0.0.0","--authrpc.port","8551", "--authrpc.vhosts=*", "--syncmode", "full",
"--http", "--http.addr", "0.0.0.0", "--http.port", "63115",
"--http.api","eth,web3,personal,debug,net,admin", 
"--ws", "--ws.origins=*", "--ws.addr=0.0.0.0", "--ws.port=63116", "--ws.api", "eth,web3,personal,debug,net,admin",
 "--datadir", "/data/ethereum", "--datadir.minfreedisk", "300",  "--cache=16384", "--snapshot=false",
"--port", "33332", "--gcmode=archive", "--maxpeers=100"]
```

**Comment by MariusVanDerWijden** [comment]
Could you do a `debug.writeMemProfile()` when you notice the memory ticking up? 
Do you have some graphs from grafana?

**Comment by gleb498** [comment]
@MariusVanDerWijden yes, we have one
![image](https://github.com/ethereum/go-ethereum/assets/20151819/2ff7a035-1010-4f20-a262-409e94a7bbb5)

**Comment by gleb498** [comment]
and there is a memprofile as a result of debug_writeMemProfile
[memprofile.log](https://github.com/ethereum/go-ethereum/files/12738518/memprofile.log)

**Comment by MariusVanDerWijden** [comment]
Do you have snapshots disabled?

**Comment by MariusVanDerWijden** [comment]
It looks like ~1.2GB is because someone is tracing transactions on your node

**Comment by gleb498** [comment]
Could you please tell how we can read this memprofile file? Which utility should I use? It would be very useful for analysis

**Comment by MariusVanDerWijden** [comment]
`go tool pprof memprofile.log`

**Comment by holiman** [comment]
> It looks like ~1.2GB is because someone is tracing transactions on your node
