### ISSUE TITLE
How to run a private Geth blockchain test on two separate machines (Server and Client) using a bootnode

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#28188]
Hello,

I successfully tested the Clique PoA Geth on two local machines using static nodes having Static IP addresses.

However, I'm facing connectivity issues while configuring the second node on the AWS Ubuntu machine from my local Ubuntu machine.

Despite reviewing the configuration, checking ports, and ensuring firewall rules, I haven't resolved the issue.

Your guidance and suggestions would be greatly appreciated.

**Comment by jwasinger** [comment]
Please run your setup using maximum log verbosity for p2p by adding `--vmodule="p2p=5"` on both nodes, filter for log output containing the static IP addresses that you are trying to connect to, and report back what appears.

**Comment by MariusVanDerWijden** [comment]
The latest geth master does not support Clique anymore. Will close this for now. Thanks for reporting!
