### ISSUE TITLE
Trie Benchmarks Break invariant of trie

### ISSUE THREAD

**Issue by aaronbuchwald** [ethereum/go-ethereum#28214]
The current trie benchmarks in geth: https://github.com/ethereum/go-ethereum/blob/master/trie/trie_test.go#L630-L635 allocate a single byte array to use as the key and value when constructing a trie.

The key is then overwritten every time to a different value. However, the trie assumes that after a byte slice is passed in it should not be modified by the caller.

As an example, modifying `benchUpdate` to add the following correctness check causes the benchmark to fail:

```
	trie := NewEmpty(triedb)
	k := make([]byte, 32)
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		e.PutUint64(k, uint64(i))
		trie.MustUpdate(k, k)
	}

	k2 := make([]byte, 32)
	res, err := trie.Get(k2)
	if err != nil {
		b.Fatal(err)
	}
	if !bytes.Equal(res, k2) {
		b.Fatal("unexpected")
	}
```

checking that the key equals the value should pass because every call to `MustUpdate` passed in the same key and value argument.

**Comment by aaronbuchwald** [comment]
Planning to make a PR to fix this and look around at more relevant benchmarks in the trie code, so if there are any other changes you'd suggest or want, happy to help out here while looking around.

**Comment by chiraggargappyhigh** [comment]
Hi @aaronbuchwald , can u please review this [PR](https://github.com/ethereum/go-ethereum/pull/28221), I have suggested a solution.

**Comment by DeVil2O** [comment]
Hi @aaronbuchwald , can u please review this [PR](https://github.com/ethereum/go-ethereum/pull/28221), I have suggested a solution.

**Comment by aaronbuchwald** [comment]
Thanks @DeVil2O , that change LGTM, the same behavior is present in `benchGet` as well if you want to provide the fix there too.

I am working on a change to the benchmarks as well and put my work up here: https://github.com/aaronbuchwald/go-ethereum/commit/9322d227f9ebcf597881938debe6f921854df97e.

Unfortunately, the triedb code only supports insertion via `Update` which requires that all of the updates are correct accounts / storage tries.

I think this design choice is intended to ensure the API only allows correctly formatted data to be inserted into the triedb, but makes it a bit more difficult to test it for randomly generated values inserted into the trie in this case.

Going to keep working on this and try to support the following benchmark cases:

- benchmark getting k keys from a trie of size n
- benchmark putting k keys into a trie of size n

DB IO will be the bottleneck, so these benchmarks should provide an approximation of how many total DB reads are necessary. Then if you have a reasonable estimate of the latency for a DB read on a given system, it should give you a good estimate of the expected latency to get/update k keys in a trie of size n.

**Comment by aaronbuchwald** [comment]
It would also be very interesting to either come up with a formula for the expected number of trie node reads when updating k keys in a trie of size n, or since as I understand it a closed form formula for that may be difficult a simulation that helps approximate the expected number of trie node reads that will be needed.

Assuming the keys are randomly distributed, log_b(n) * k (depth * k) should be a good upper bound approximation, but I'm still curious if there's a straightforward, closer approximation.

**Comment by aaronbuchwald** [comment]
Closed by https://github.com/ethereum/go-ethereum/pull/28221
