### ISSUE TITLE
Manipulating block.timestamp of the next block when running in Dev mode.

### ISSUE THREAD

**Issue by ankurdubey521** [ethereum/go-ethereum#28229]
I've been using geth in `--dev` mode for testing some of my smart contracts with hardhat that require the support of the `debug_traceCall` RPC with the JS Tracer. 
With the hardhat node, I'm able to use the `evm_increaseTime` [RPC](https://hardhat.org/hardhat-network/docs/reference#evm_increasetime) to increment the timestamp of the next block, and I wanted to understand if this is possible in geth.

I didn't find anything in the `debug_` namespace which could do this. I was considering incrementing the system instead and seeing if geth applies the same to the next block, but since I'm running geth in a docker container the system time of the container is linked to the host's system time which cannot be manipulated by the container easily.

Here's how I'm launching geth for reference:
```
FROM ethereum/client-go:latest
ENTRYPOINT geth \
      --http.vhosts '*,localhost,host.docker.internal' \
      --http \
      --http.api personal,eth,net,web3,debug \
      --http.corsdomain '*' \
      --http.addr "0.0.0.0" \
      --nodiscover --maxpeers 0 --mine \
      --networkid 1337 \
      --dev \
      --allow-insecure-unlock \
      --rpc.allow-unprotected-txs \
      --dev.gaslimit 200000000 \
 ```

**Comment by karalabe** [comment]
We have a simulated backend that can support various operations, alas from Go. The dev chain is really more of a quick and dirty thing that just works. We don't want to expand the API to make it a test runner.

**Comment by ankurdubey521** [comment]
I see, could you please share documentation or some reference to the simulated backend?

**Comment by MariusVanDerWijden** [comment]
The simulated backend can be found here: https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/backends/simulated.go
Again as @karalabe said, its purpose is to be used from go to build unit tests for smart contracts
