### ISSUE TITLE
high disk usage when using pebble

### ISSUE THREAD

**Issue by nothingmin** [ethereum/go-ethereum#28248]
#### System information

Geth version: `1.13.2`
OS & Version: [**Raspberry Pi OS (64-bit)**]

#### Expected behaviour
I'm building a private network using raspberry pi 4 B.
I follwed documentation https://geth.ethereum.org/docs/fundamentals/private-network

#### Actual behaviour
problem is when i started geth it used too many disk space.
![image](https://github.com/ethereum/go-ethereum/assets/67548026/8bebfb9b-5da4-4fd1-ac16-2f317d363bb4)
As you see **./geth/chaindata** uses too much disk space.
So I investigated **./geth/chaindata** using `ls -alh` command.
![image](https://github.com/ethereum/go-ethereum/assets/67548026/ab4bcd4d-fa48-4f1a-8cda-af7129196243)
As you see, actual file size is very small(less than 1MB). But the disk usage is high(141MB)

#### Steps to reproduce the behaviour
commands used to build the network is as below.
```

./geth --datadir data --networkid 12345 --nat extip:192.168.0.23 --unlock 0x0d3B7BF41ba67ab1675e31348E78AaE4B43dd26F --mine --miner.etherbase=0x0d3B7BF41ba67ab1675e31348E78AaE4B43dd26F

./geth --datadir data --networkid 12345 --port 30303 --bootnodes enode://07d88d56af00ffcad18966218efef3e58a4745f9ab3b3f78b12f0a0f0340b46c2020033c33666ea3d9a0599b5ef9b36d3bf03c8d83305d8bad3cadf316fb82cf@192.168.0.23:30303

```
+  **When I used leveldb as db.engine disk usage become normal**

**Comment by karalabe** [comment]
I'm guessing Pebble pre-allocates some things for journalling earlier. I wouldn't really concern myself for a few hundred megabytes of space. That's not really a relevant thing.
