### ISSUE TITLE
Documentation missing for history.state?

### ISSUE THREAD

**Issue by quickchase** [ethereum/go-ethereum#28247]
Looking at running a full archive node of Geth using the new PBS, coming from 1.12.2 going to 1.13.2 and while I read the blog post for 1.13.0 the `--history` flags appear to be undocumented.

Typically to run a full archive node we need `--gcmode=archive` and `--syncmode=full`

In addition to that we'd usually want `--txlookuplimit=0` - seeing the latest release this is now aliased to `--history.transactions` which is fine.

However, `history.state` seems undocumented and I do not know just based on the description if I need to set this, or how it impacts the node.

```bash
    --history.state value               (default: 90000)                   ($GETH_HISTORY_STATE)
          Number of recent blocks to retain state history for (default = 90,000 blocks, 0
          = entire chain)
```

My gut tells me I want to set this to `0` for a full archive node but exactly what this does, especially in relation to `gcmode=archive`

**Comment by karalabe** [comment]
The path scheme does not support archive mode yet.

**Comment by karalabe** [comment]
When support will land, yes, you'll need to set the history.state to 0. The gcmode flag is relevant only in hash scheme, we'll add some warning logs to make sure people use them correctly. But we need to ship support first.

**Comment by quickchase** [comment]
Thanks, one last question: is `--history.state` relevant to hash storage or not? Does this imply that the typical "128 blocks" pruning changes in PBS to be a configurable number?

**Comment by kaliubuntu0206** [comment]
@karalabe @quickchase Would it be possible to query historic calls or debug tracers when I use the flag?

**Comment by kaliubuntu0206** [comment]
Some issue related https://github.com/ethereum-optimism/op-geth/issues/178, I am looking for an option that could enable tracing beyond 128 blocks
