### ISSUE TITLE
ERROR[10-03|11:17:06.197] Discovery v5 is not initialized

### ISSUE THREAD

**Issue by alexisdavidson** [ethereum/go-ethereum#28240]
#### System information

Geth version: latest
CL client & version: light
OS & Version: Ubuntu
Commit hash : (if `develop`)

#### Expected behaviour
trying to sync the node with geth --datadir ~/ethereum --syncmode "light" --http --http.addr IP --http.port 8545 --http.api eth,net,web3,debug --http.corsdomain "*"

#### Actual behaviour
ERROR[10-03|11:17:06.197] Discovery v5 is not initialized

**Comment by karalabe** [comment]
Light client does not work since the merge. The whole thing needs to be reimplemented form scratch and we don't have much capacity going into it.

**Comment by nandaniagraqwal432** [comment]
is there any other way to run a light node by geth?

**Comment by alexisdavidson** [comment]
Are there syncmode alternatives to run nodes on lower storage capacities?

**Comment by hovanhoa** [comment]
any way to bypass this one?

**Comment by barresoft** [comment]
Here is the "light" mode remove commit....

[commit](https://github.com/ethereum/go-ethereum/commit/bdf5e388ca0d1e6f5e227ba52481fe6b7667ec4d)
