### ISSUE TITLE
Private blockchain is not working

### ISSUE THREAD

**Issue by TrustNobodySaltandSugarLookTheSame** [ethereum/go-ethereum#28251]
I have been testing using latest geth version and I don't understand why its not working fully.

geth version: 1.13.2
using guide: https://geth.ethereum.org/docs/fundamentals/private-network

genesis.json:

```
{
  "config": {
    "chainId": 97197,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "muirGlacierBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0,
    "arrowGlacierBlock": 0,
    "grayGlacierBlock": 0,
    "clique": {
      "period": 5,
      "epoch": 30000
    }
  },
  "difficulty": "1",
  "gasLimit": "800000000",
  "extradata": "0x00000000000000000000000000000000000000000000000000000000000000003177de278886C632d5B519269CB97B91960f2737a6f95a5807fcfC3834fFaf315A0C3f9a0c3497Ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "alloc": {
    "0x3177de278886C632d5B519269CB97B91960f2737": { "balance": "10000000000000000000000000" },
    "0xa6f95a5807fcfC3834fFaf315A0C3f9a0c3497Ff": { "balance": "10000000000000000000000000" }
  }
}
```

To reproduce:
Create 2 accounts for both node1 & node2
After:
```
geth init --datadir node1 genesis.json
geth init --datadir node2 genesis.json
```

```
bootnode -genkey boot.key
bootnode -nodekey boot.key -addr :30305
```

```geth --datadir node1 --port 30306 --bootnodes enode://7f6670c46d4cf34eb7fe50b914ef3953da468a13efe85f63a8acbe2a24311777d904424a5b7a3c37c6483070ed390e9a105b526938c4c41c8788d4422708b2e7@127.0.0.1:0?discport=30305  --networkid 97197 --unlock 0x3177de278886C632d5B519269CB97B91960f2737 --password node1/password.txt --authrpc.port 8551```

```geth --datadir node2 --port 30307 --bootnodes enode://7f6670c46d4cf34eb7fe50b914ef3953da468a13efe85f63a8acbe2a24311777d904424a5b7a3c37c6483070ed390e9a105b526938c4c41c8788d4422708b2e7@127.0.0.1:0?discport=30305 --networkid 97197 --unlock 0xa6f95a5807fcfC3834fFaf315A0C3f9a0c3497Ff --password node2/password.txt --authrpc.port 8552```

Both nodes show this after running:
`Looking for peers                        peercount=1 tried=0 static=0`

Then:
`geth attach node1/geth.ipc`

`eth.getBalance(eth.accounts[0])`
//Balance is showing fine here

```
eth.sendTransaction({
  to: '0x8119c8E0651e6599a0a1E6408CB8a68e1FFC86D8',
  from: eth.accounts[0],
  value: 1000000000000000000
});
```
//it returns tx hash

Issue:
When I check the balance again using  `eth.getBalance(eth.accounts[0])`
it shows the same like nothing has been sent... why the transaction is not being mined?
Checking the window running the first node it shows details of the transaction but that's about it.

What is wrong here? Did I miss something excuse my brain.

**Comment by karalabe** [comment]
You also need to run a signer, otherwise there's nobody that actually creates the blocks.

If you want to just test stuff on a single machine, you can run geth in --dev mode, that is a single-everything-inlcuded chain.

If you want to set up a private network that's going to be longer lives, I'd recommend looking into setting up a full PoS network. We will be sunsetting Clique soon.

**Comment by alcor146** [comment]
Could you give us more information on setting up a private network @karalabe ? The official documentation proposes 2 sollutions: ETH POW which is already deprecated and Clique which you are saying its getting deprecated soon.
