### ISSUE TITLE
Make Client use an rpc.Client interface instead of struct so that I can write an instrumented client

### ISSUE THREAD

**Issue by samlaf** [ethereum/go-ethereum#28267]
# Rationale

I need to make an instrumented eth client to export prometheus metrics counting the number calls to each `eth_` method.
This should be easy but it ends up being pretty hard because geth's ethclient wraps a rpc.Client struct instead of an interface.
```
type Client struct {
	c *rpc.Client
}
```

# Implementation

If the Client took an interface instead of `rpc.Client`, I could just implement an instrumented rpc.Client that would wrap geth's rpc.Client and change CallContext to wrap CallContext and increase the prometheus metric counts. (and same for BatchCallContext)

```
client := &Client{c: &MyRpcClient{...})
type MyRpcClient struct {
   *rpc.Client
   rpcRequestTotal *prometheus.CounterVec
}

func (c *Client) CallContext(ctx context.Context, result interface{}, method string, args ...interface{}) error {
   c.rpcRequestsTotal.With(prometheus.Labels{"method": method}).Inc()
   return c.Client.CallContext(ctx, result, method, args...)
}

However I can't do it like this right now because rpc.Client is not an interface, so I have to instead wrap the geth Client above all of this, and reimplement every single call individually to be instrumented (instead of just having to wrap CallContext and CallBatchContext).

Is there an interface somewhere for the rpc Client? Could we change the Client to use that instead if so? If not, I could write and submit a PR.

**Comment by karalabe** [comment]
CC @fjl 

The internal client is kind of internal, so we could turn it into an interface and provide a new constructor to initialize it.

**Comment by fjl** [comment]
The interface between ethclient and the RPC client is ~5 methods, some of them having a hairy signature. It's not the most ideal solution to put an interface there.

I think it might be better to add a call hook into `rpc.Client` instead. We could find other uses for that, logging all calls for example.

**Comment by samlaf** [comment]
I don't see the problem with having a complex interface if it's only going to be used by the few people who need it anyways.
But hook would work as well I guess.
