### ISSUE TITLE
missing trie node

### ISSUE THREAD

**Issue by ardevd** [ethereum/go-ethereum#28265]
Tried resyncing my node with PBSS and it's seemingly running fine. Currently healing, however, during the sync (and still ongoing during healing) I get the following message printed repeatedly and consistently.

```
WARN [10-05|21:52:32.359] Served eth_call conn=172.20.0.4:48570 reqid=3 duration="73.178µs"  err="missing trie node d7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544 (path ) state 0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544 is not available"
```

Is this something I can safely ignore or dos it pose an actual issue I need to deal with?

**Comment by karalabe** [comment]
You can ignore it during sync. I'm unsure wether it's your beacon client or something else doing calls against your node, but until sync finishes, the state is not usable, so it's going to complain.

**Comment by ardevd** [comment]
Thanks. The warning went away after the sync was complete.
