### ISSUE TITLE
Geth snapshot dump 

### ISSUE THREAD

**Issue by cesarhuret** [ethereum/go-ethereum#28263]
With geth snapshot dump, how can you dump a snapshot where they keys are equal to the account's address (or linked to the account's address) instead of the hash of the slimAccount struct?
Alternatively, if there's a simpler way I'm missing, how can you dump the stateDB for a given block? We want to use the vmenv.Call method to replay transactions locally, using geth as a go library, and need the full chain state on a given block to do that.

**Comment by karalabe** [comment]
The keys in a dump are the hash of the account address.

**Comment by s1na** [comment]
> Alternatively, if there's a simpler way I'm missing, how can you dump the stateDB for a given block? We want to use the vmenv.Call method to replay transactions locally, using geth as a go library, and need the full chain state on a given block to do that.

If you don't need proofs for the data you receive you can take a look at the `prestateTracer`. You can do something like:

```terminal
debug.traceTransaction(<txhash>, { tracer: 'prestateTracer' })
```

It will give you the prestate for a tx. Now if you repeat for all txes of a block in order and keep the earlier versions for each account then you have yourself a prestate for the block.

Note that we are implementing `eth_getRequiredBlockState` which gives you all the information to re-execute a block locally together with the state proofs. So stay tuned for that.

**Comment by cesarhuret** [comment]
> Note that we are implementing eth_getRequiredBlockState which gives you all the information to re-execute a block locally together with the state proofs. So stay tuned for that.
Nice, is there any issue/branch for it?
