### ISSUE TITLE
debug_seedHash Documentation should be removed

### ISSUE THREAD

**Issue by pajicf** [ethereum/go-ethereum#28281]
# The issue
There's a method in debug namespace that seems like no longer exists in the current codebase and should probably be removed from the documentation if so.
# Details
Looking at the debug_ namespace documentation, the [debug_seedHash](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugseedhash) still exists but it seems like it's legacy from PoW era removed in May.
<img width="609" alt="Screenshot 2023-10-08 at 10 35 15" src="https://github.com/ethereum/go-ethereum/assets/42151917/93928d86-cb82-48df-93c2-c12b44950efc">

The commit I believe removed it from the client is [dde2da0](https://github.com/ethereum/go-ethereum/commit/dde2da0efb8e9a1812f470bc43254134cd1f8cc0) in `internal/ethapi/api.go` file. (At the moment of the commit)

<img width="1247" alt="Screenshot 2023-10-08 at 10 37 32" src="https://github.com/ethereum/go-ethereum/assets/42151917/08a471b5-195e-4f4c-9e50-cccb680e846d">

**Comment by pajicf** [comment]
@lightclient Can you take a look at this as well? :)

**Comment by holiman** [comment]
fixed by https://github.com/ethereum/go-ethereum/pull/28289
