### ISSUE TITLE
debug_stopGoTrace Documentation, mistake in method invocation example

### ISSUE THREAD

**Issue by pajicf** [ethereum/go-ethereum#28288]
# The issue
There's a mistake in the invocation example of `debug_stopGoTrace` for console.

# Details
Looking at the debug_ namespace documentation, the [debug_stopGoTrace](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugstopgotrace) console method being invoked is `debug_startGoTrace` instead of `debug_stopGoTrace`

<img width="557" alt="Screenshot 2023-10-09 at 09 52 19" src="https://github.com/ethereum/go-ethereum/assets/42151917/5fa50796-194c-4777-bfda-ee8a9013153b">

**Comment by pajicf** [comment]
@lightclient Can you take a look here as well? :)

**Comment by holiman** [comment]
fixed in #28289
