### ISSUE TITLE
Ethereum data directory path hardwired to C:\Users\user\AppData\Roaming\Ethereum

### ISSUE THREAD

**Issue by ConsentDevelopment** [ethereum/go-ethereum#2828]
#### System information

Geth version: 1.4.10 and below
OS & Version: Windows 10 64bit
Commit hash : (if `develop`)
#### Expected behaviour

Geth should respect the correct OS roaming path and not default to the C: drive.
#### Actual behaviour

Ethereum blockchain data is being written to C:\Users\user\AppData\Roaming\Ethereum even when the OS location had moved.
#### Steps to reproduce the behaviour

The blockchain data was taking a lot of room on my C: drive so I changed the location of the path C:\Users\user\AppData\Roaming (which contains the Ethereum data folder for the blockchain data) to D:\Roaming.

When I start the wallet there is a error message that it cannot find the node and so it begins to download the whole blockchain again to the path C:\Users\user\AppData\Roaming\Ethereum

As the blockchain will get bigger and bigger a lot of people will want to move the data folder to a bigger drive as the C drive is to small and has all the OS programs and data.
#### Backtrace

```
[backtrace]
```

**Comment by luclu** [comment]
Linking Mist [issue](https://github.com/ethereum/mist/issues/927):
> You are right. Currently geth will [query](https://github.com/ethereum/go-ethereum/blob/290e851f57f5d27a1d5f0f7ad784c836e017c337/common/defaults.go#L36-L41) the user's home directory and expands to it: 
```javascript
home := HomeDir()
filepath.Join(home, "AppData", "Roaming", "Ethereum")
```

**Comment by karalabe** [comment]
This is a known issue, but not that big since you can always manually point geth to a data directory of your choice with `--datadir D:\Ethereum` for example.

**Comment by ConsentDevelopment** [comment]
That is a good solution but most people will not know automatically unless they do a bit of research and people who have moved the OS roaming location will see that Geth is still using the default OS roaming location.

A lot of laptops / PCs these days have small C: SSD drives so moving the default OS roaming location will be commonplace.

**Comment by fjl** [comment]
Just noting: we have also received requests to move the chain to AppData\Local instead.

**Comment by ConsentDevelopment** [comment]
AppData\Local is also fine as long as Geth respects the OS location path of the folder.

**Comment by dattanchu** [comment]
In Ethereum Wallet app in Windows, on Install, the user can now choose the location of the chaindata.

**Comment by Cryt1c** [comment]
Is there a way to change the default datadir through config so that it persists?

**Comment by karalabe** [comment]
`--datadir=your_favorite_folder`

**Comment by Cryt1c** [comment]
Thanks, I know about the CLI parameter but is there a way to persist this in a config file or something comparable?

**Comment by cwallwor** [comment]
Download geth on to second drive. Then you can create a link to another directory with:    mklink /D C:\Users\Name\AppData\Roaming\Ethereum G:\Ethereum   Then run geth from g:\
