### ISSUE TITLE
The export command is not working "geth export my-file.rlp". Unable to take backup. 

### ISSUE THREAD

**Issue by SirajChaudhary** [ethereum/go-ethereum#28292]
#### System information

Geth version: `1.13.1`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Linux
Commit hash : (if `develop`)

#### Actual behaviour
The export command is not working "geth export my-file.rlp"

The export command giving following error
**ERROR[10-09|13:58:46.986] Failed to commit trie from trie database err="pebble: read-only"**

![image](https://github.com/ethereum/go-ethereum/assets/76120970/f887c6e3-bbef-45d0-a5e9-e7bac58096be)

#### Steps to reproduce the behaviour
geth export my-file.rlp

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by holiman** [comment]
It seems like you don't have anything to back up, it tries to write a genesis there, since it does not find any existing database. 
If you normally provide `--datadir` argument, you need to provie the same argument to the `export` command.

**Comment by SirajChaudhary** [comment]
> It seems like you don't have anything to back up, it tries to write a genesis there, since it does not find any existing database. If you normally provide `--datadir` argument, you need to provie the same argument to the `export` command.

Yes. It working now and I'm able to take backup (export) after adding this parameter --datadir

Interestingly this parameter wasn't require in the geth version 1.10

Thank you Holiman :)

**Comment by holiman** [comment]
> Interestingly this parameter wasn't required in the geth version 1.10

Yes it was. But glad that it worked!
