### ISSUE TITLE
Why don't return error ?

### ISSUE THREAD

**Issue by bnovil** [ethereum/go-ethereum#28301]
I'm reading source code and notice TODOs at line 301 and 305. Why just log a warn instead of returning error? And can we return error now?  

https://github.com/ethereum/go-ethereum/blob/08326794e8069835b519217e1d2195f667398748/eth/protocols/eth/handlers.go#L290-L306

**Comment by Cognacy** [comment]
Hi @bnovil are you able to fix error?

**Comment by lightclient** [comment]
Usually we want to be careful when adding errors to the p2p handlers as they often go up the stack and cause us to disconnect. Better to log initially to ensure the mechanism works correctly than to release into the wild only to find an issue peers unable to retain connections.

The execution layer no longer announces blocks though so this code isn't really used. I don't think we will fix.

**Comment by bnovil** [comment]
@lightclient  thanks for explaining!
