### ISSUE TITLE
Please add oppose DAO flag to the --help command

### ISSUE THREAD

**Issue by whatisgravity** [ethereum/go-ethereum#2830]
I would prefer an alternate client, it is the obvious choice to give people real choice. Anything else is the "tyranny of the default".

If you can not be bothered do that, can you at least properly document it? It is not even in the --help command and it should be in bold at the top of the README after release.

I will assume it was an oversight that this was not included but it should obviously be included and properly documented in the README while the decisions are being made. 

You may find it hard to believe but some of us actually want a platform to run unstoppable applications and it seems the organization that raised funds under this premise is now doing their best to make this hard as possible.

**Comment by julian1** [comment]
It's there,

```
:~/geth-1.4.10$ ./geth --help | grep DAO
  --support-dao-fork    Updates the chain rules to support the DAO hard-fork
  --oppose-dao-fork     Updates the chain rules to oppose the DAO hard-fork
```

**Comment by obscuren** [comment]
Additionally it shows you on startup very prominently that you are either on the fork, or not.

You may also use any previous version of geth to oppose the hard fork without any flags.
