### ISSUE TITLE
Library contract method failing

### ISSUE THREAD

**Issue by brendan87** [ethereum/go-ethereum#2831]
#### System information
Geth version: 1.5.0
OS & Version: Windows 10
Interface - chriseth's browser-solidity (implements web3)

#### Expected behaviour
Call simple library function to update a simple storage variable.

#### Actual behaviour
Gas required exceeds limit: 50000000

#### Steps to reproduce the behaviour
Contract 1:
```
import "./test2.sol";

contract test1 {
    uint8 stor1;
    function runLibFunc () {
        stor1 = test2.foo();
    }
}
```

Contract 2:
```
library test2 {
    function foo () constant returns (uint8) {
        return 2;
    }
}
```

Once test1 is deployed, run 'runLibFunc()'.

###Comments
Not sure if this is an interface (web3) issue or geth

**Comment by bas-vk** [comment]
You probably run geth with the `--dev` option to create a private network? In that case use the init subcommand to create a private chain. Instructions can be found in the [wiki](https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options#init). Or use the testnet.

The problem is that this code uses the delegatecall which is added in the homestead release. The `--dev` flag uses the homestead block number of the mainnet which is 1150000. Any transaction before this block will encounter an invalid opcode consumes, all gas and all state changes are reverted.

@obscuren, initially I thought there was an invalid opcode but it turns out I had a pre homestead copy of the yellow paper.  Instead of setting the homestead block for the development chain can we drop the entire `--dev` flag in favor of the init subcommand?

**Comment by brendan87** [comment]
Thanks @bas-vk. Apologies for not providing more information on the geth environment. I wasn't using the --dev option - I am running geth using the following command line args:

```
geth init genesis.json 
geth --identity "finhausTestNode150" --rpc --rpcport "8777" --rpccorsdomain "*" --datadir "D:\EthereumTestNode\data" --port "30303" --maxpeers 0 --nodiscover --ipcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --rpcapi "db,eth,net,web3" --autodag --networkid 1150 --nat "any" console
```

Where genesis is as follows:
```
{
    "nonce": "0x0000000000000042",
    "timestamp": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x0",
    "gasLimit": "0x8000000",
    "difficulty": "0x400",
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x3333333333333333333333333333333333333333",
    "alloc": {
    }
}
```

**Comment by bas-vk** [comment]
That is actually the same issue. The genesis config file supports a config section. Currently the only thing you can configure is the homestead block number. If you don't specify it, it will be defaulted to the mainnet number which is 1150000. So basically your contract will work after this block.

Try the following genesis file:

```
{
   "config":{
      "homesteadBlock":"5"
   },
   "nonce":"0x0000000000000042",
   "timestamp":"0x0",
   "parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000",
   "extraData":"0x0",
   "gasLimit":"0x8000000",
   "difficulty":"0x400",
   "mixhash":"0x0000000000000000000000000000000000000000000000000000000000000000",
   "coinbase":"0x3333333333333333333333333333333333333333",
   "alloc":{

   }
}
```
If the contract is deployed in block <5 it will give the gas limit problem. 
Deployed in block >= 5 it should work as intended.

**Comment by brendan87** [comment]
I managed to get geth to accept the new genesis file after changing the config section to:
```
"config":{
      "homesteadBlock": 5
   }
```
(It didn't like the quotation marks around the 5)
However, I still encounter the same gas limit problem (or, if setting the function to a constant function in Contract 1, nothing is returned).
Do you think there could be any issues with updating the genesis file on an existing chain?

**Comment by bas-vk** [comment]
Not sure what you mean with updating the genesis file on an existing chain?

Normally if you modify the genesis block you should create a fresh private chain. This is just the homestead block number, so the genesis block should look the same. I *think* you can just rewrite the genesis block into an existing chain but I'm not sure.

I just tried your example library/contract and it runs fine with a fresh chain. `runLibFunc` should not return anything. If you want to verify if `stor1` is updated retrieve its storage.

From the geth console:

```
> eth.getStorageAt(contractAddress, "0x0")
"0x0000000000000000000000000000000000000000000000000000000000000000"
```
call `runLibFunc` in a transaction, after the transaction is mined the storage should be 2.
```
> eth.getStorageAt(contractAddress, "0x0")
"0x0000000000000000000000000000000000000000000000000000000000000002"
```

**Comment by brendan87** [comment]
That's cool. I'll close it if you can get it running - it must be something on my end. I have been trying to test it on a new chain but I can't get the new chain to mine anything sadly.

**Comment by avatar-lavventura** [comment]
I am having same trouble with my Private Ethereum Blockchain. I have done @bas-vk suggestions but I am still facing with same error. Could you able to help me on my case?
