### ISSUE TITLE
Stdin  for inputs in t8n evm is not working as expected

### ISSUE THREAD

**Issue by Vikram710** [ethereum/go-ethereum#28310]
`./evm t8n --state.fork=London --input.alloc=stdin --input.txs=$dir/txs.json --input.env=$dir/env.json --output.result=stdout --output.alloc=stdout --state.reward=100 --state.chainid=1 `
paste the allloc data

`echo "$json_data" |  ./evm t8n --state.fork=London --input.alloc=stdin --input.txs=$dir/txs.json --input.env=$dir/env.json --output.result=stdout --output.alloc=stdout --state.reward=100 --state.chainid=1`

If i am not wrong this should work right?  instead my transactions are getting rejected with 
`{
        "index": 0,
        "error": "nonce too high: address 0x447bF33F7c7C925eb7674bCF590AeD4Aa57e656b, tx: 5637 state: 0"
      },`
this clearly means that the stdin input is not being used as the file version of the same command gives expected output

Please do let me know if  I am doing this right or is it a bug in t8n input reader ?

**Comment by lightclient** [comment]
I don't know what is in `$json_data` so I can't really say what the issue is. You do need to ensure that if you use `stdin` the value is wrapped in another object with the name of the object. E.g.

```
{
  "alloc": {
    "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b": {
      "balance": "0x016345785d8a0000",
      "code": "0x",
      "nonce": "0x00",
      "storage": {}
    },
    "0x000F3df6D732807Ef1319fB7B8bB8522d0Beac02": {
      "balance": "0x1",
      "code": "0x3373fffffffffffffffffffffffffffffffffffffffe14604457602036146024575f5ffd5b620180005f350680545f35146037575f5ffd5b6201800001545f5260205ff35b6201800042064281555f359062018000015500",
      "nonce": "0x00",
      "storage": {}
    }
  }
}
```

not

```
{
  "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b" : {
    "balance" : "0x016345785d8a0000",
    "code" : "0x",
    "nonce" : "0x00",
    "storage" : {
    }
  },
  "0x000F3df6D732807Ef1319fB7B8bB8522d0Beac02" : {
    "balance" : "0x1",
    "code" : "0x3373fffffffffffffffffffffffffffffffffffffffe14604457602036146024575f5ffd5b620180005f350680545f35146037575f5ffd5b6201800001545f5260205ff35b6201800042064281555f359062018000015500",
    "nonce" : "0x00",
    "storage" : {
    }
  }
}
```

The error seems to indicate your alloc is not being read (assuming the alloc initializes the account's nonce to be certain value).

**Comment by holiman** [comment]
Yes let's see an `echo "$json_data" ` and perhaps an `echo "$json_data"  | jq . ` so we know what we're dealing with

**Comment by Vikram710** [comment]
Thanks a lot the json structure change works.

this was my json
`json_data='{"0x447bf33f7c7c925eb7674bcf590aed4aa57e656b":{"balance":"0x10000000000","nonce":"0x1605"}}'`
changing it to 
`json_data='{"alloc":{"0x447bf33f7c7c925eb7674bcf590aed4aa57e656b":{"balance":"0x10000000000","nonce":"0x1605"}}}'` works

**Comment by lightclient** [comment]
Great, thanks for letting us know.
