### ISSUE TITLE
Request: Remove --oppose-dao-fork extradata validation

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/go-ethereum#2832]
Hey, it looks like --opoose-dao-fork actually implements a hard fork by refusing to process blocks between 192000 and 192010 if they contain the wrong extradata.

https://github.com/ethereum/go-ethereum/blob/5f55d95aea433ef97c48ae927835d833772350de/core/dao.go#L52-L54

Nodes running geth 1.4.10 will actually end up on a different fork than geth 1.4.9 if even one block in the range contains a spoofed extra-data

**Comment by aakilfernandes** [comment]
Nick Johnson has corrected me. This is a soft fork, however unless it gets 51% of the hashpower behind it it behaves like a hard fork.

**Comment by EtherTyper** [comment]
@aakilfernandes The soft fork between release 1.4.9 and 1.4.10 with the `--oppose-dao-fork` flag enabled is intentional. Check the 1.4.10 release notes.

> Please note, fast sync and light clients do not verify state transitions, only perform header validations and PoW checks. As such, a fork unaware client (i.e. non-updated one) will always fast-sync to the longest chain, as it doesn't have the necessary information on what to look for in the headers. _Even if you oppose the fork, please update so your client knows what chain to avoid._

**Comment by aakilfernandes** [comment]
I'm aware its intentional. However it potentially causes a split between two different clients who expect to be on the same chain. This is not acceptable.

**Comment by aakilfernandes** [comment]
This is especially relevant since hashpower is being used to determine the winner of this fork. If only 49% of hashpower is on 1.4.10, the "don't fork" chain will appear to have half the haspower it actually has.

**Comment by gillhofer** [comment]
Could we please have a statement from a developer!

**Comment by EtherTyper** [comment]
Officials like @obscuren are being inconsistent, suggesting usage of the v1.4.9 chain in messages on the GitHub Issue tracker, in place of the intended v1.4.10 `--oppose-dao-fork` flag. #2830 

> Additionally it shows you on startup very prominently that you are either on the fork, or not.

> You may also use any previous version of geth to oppose the hard fork without any flags.

**Comment by dskloet** [comment]
A soft fork should never be introduced without a voting threshold. Otherwise you have a large risk of many orphaned blocks. Is this an attack on the original chain?

**Comment by fjl** [comment]
Just to clarify: this issue was closed because the HF transition is over now and the soft fork did not happen.

**Comment by gillhofer** [comment]
I don't get it. The chain is still alive and is used.

**Comment by dskloet** [comment]
This bug could have caused a 3 chain but that didn't happen.

**Comment by daira** [comment]
Indeed, but why was the risk ignored?

**Comment by fjl** [comment]
As stated above, we added the extra validation to ensure that fast sync and light clients work correctly on the non-HF chain even though they do not perform full block validation (i.e. do not process all state transitions).

@daira I agree that this was a risky move, but the risk was calculated.
