### ISSUE TITLE
Log parsing via block iterating overwhelms the node, is this normal ? 

### ISSUE THREAD

**Issue by JourneyToSilius** [ethereum/go-ethereum#28339]
I use a Goroutine to iterate over blocks with ranged filter queries, batching the chunks. But it doesn't matter how many chunks I use in the routine, there is a moment the node keeps on taking all the CPU and it keeps on going like this even when exiting the program. Is this normal behavior ? It seems that even if you do a blocking routine ( to wait for the node to process the calls ) it gets overwhelmed and it crashes. Summarizing : what is the correct way to massively parse logs without killing the node?

**Comment by s1na** [comment]
Just so I understand your issue better: you have geth running and you are issuing many parallel queries to `eth_getLogs` from a client (possibly ethclient)?

**Comment by holiman** [comment]
Please provide more exact documentation about what you are doing; preferrably code which can be used to reproduce the problem. But at least we need to know what methods you are invoking, and how you are invoking them (what parameters? serially or parallel? How much parallel?).

**Comment by holiman** [comment]
Seems abandoned
