### ISSUE TITLE
Please fix the flaky test

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/go-ethereum#28369]
```
--- FAIL: TestClientWebsocketPing (1.77s)
    websocket_test.go:232: client subscribe error: context deadline exceeded
FAIL
```

This test case is flaky and can fail on our CI occasionally. Sounds like a good starter task if anyone wants to do some contributions.

**Comment by bnovil** [comment]
Context timeout is only 1s. I'd like to make a PR to fix it.

**Comment by stackkrocket** [comment]
> Context timeout is only 1s. I'd like to make a PR to fix it.

How much of a difference do you think a 10-sec timeout will make as opposed to 5 seconds?

**Comment by stackkrocket** [comment]
> > Context timeout is only 1s. I'd like to make a PR to fix it.
> 
> How much of a difference do you think a 10-sec timeout will make as opposed to 5 seconds?

I just read @holiman reply to first suggested fix of 5s and I know now how much difference 10s will make!

**Comment by holiman** [comment]
In a lot of cases, changing a timeout from 1s to 5s in a test is totally fine, e.g. if we're waiting for an event, and in most cases it takes sub-second but in some cases takes longer. Changing the timeout then doesn't really affect the execution-time. 

However, we also have these cases, where adding N seconds makes the test take exactly N seconds longer.

**Comment by stackkrocket** [comment]
"However, we have these cases, where adding N seconds makes the test take exactly N seconds longer".

And I guess this holds true when the network request completes before the timeout. Hence the need for a more granular value. 

I've learnt something new today!!
