### ISSUE TITLE
eth_estimateGas difference in 12 gas

### ISSUE THREAD

**Issue by DmytroShalaiev** [ethereum/go-ethereum#28377]
Please help

why is there a difference in 12 gas?

curl https://docs-demo.quiknode.pro/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_estimateGas","params":[{"from":"0xBA43667BC19636d0855C61e06E3a4e2925e96433","to":"0xdAC17F958D2ee523a2206206994597C13D831ec7","data":"0xa9059cbb0000000000000000000000000e508400c4e18eb98ee8dedba26e3521921b3d120000000000000000000000000000000000000000000000000000000000000001"}],"id":1,"jsonrpc":"2.0"}'

  curl https://docs-demo.quiknode.pro/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_estimateGas","params":[{"from":"0xBA43667BC19636d0855C61e06E3a4e2925e96433","to":"0xdAC17F958D2ee523a2206206994597C13D831ec7","data":"0xa9059cbb0000000000000000000000000e6c034e846cdfba37d3683b78cbaa89f67fd8520000000000000000000000000000000000000000000000000000000000000001"}],"id":1,"jsonrpc":"2.0"}'

The only difference in calls is account addresses in data.

new account addresses* with zero tx's

0x0e508400C4e18Eb98EE8dEDbA26e3521921b3D12
0x0E6C034E846cdfba37D3683B78CBaa89f67Fd852

**Comment by lightclient** [comment]
The first address has a zero byte and the second does not. Zero bytes cost 4, non-zero cost 16. The difference being 12.

**Comment by DmytroShalaiev** [comment]
Thanks so much for your quick response. Please, maybe you have any docs/links on info where I can read about it.

As result, when I use estimation gasLimit (for tx where on 12 gas less) tx will fail => out of energy error :(
That's why opened this issue.
First of all to understand the difference 
Secon one why tx with estimated gas will fail ( I checked op codes usage between two tx's and it's really not enough 12 gas for completion)

Thank you

**Comment by DmytroShalaiev** [comment]
I tested not with USDT on eth. But result with estimation same (differs on 12 gas)

https://bscscan.com/tx/0xdfa80bc15554d2a9e23394fecdcea28d7843ef86635210f4eaf39b69ef9d658f
https://bscscan.com/tx/0x0a94535c0fa2118a8ecd34b75f533faa106358ac5370771becda4526b858b85e
