### ISSUE TITLE
What's the limitation of RPC call a geth client can handle

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/go-ethereum#2837]
i try to get blockchain information via rpc, while i got some ConnectionError when the concurrency is high

```
raceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "crawler.py", line 84, in worker
    self.parse_block(block_id)
  File "crawler.py", line 96, in parse_block
    self._parse_block_by_number(id)
  File "crawler.py", line 99, in _parse_block_by_number
    blk = self.client.call(METHOD_GET_BLOCK_BY_NUMBER, id, include_transaction)
  File "/usr/local/lib/python2.7/site-packages/pyethapp/rpc_client.py", line 334, in call
    reply = self.transport.send_message(request.serialize())
  File "/usr/local/lib/python2.7/site-packages/tinyrpc/transports/http.py", line 28, in send_message
    r = requests.post(self.endpoint, data=message, **self.request_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='121.201.29.105', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1031b4390>: Failed to establish a new connection: [Errno 60] Operation timed out',))
<Greenlet at 0x1030eb190: <bound method Crawler.worker of <__main__.Crawler object at 0x104754110>>(4738)> failed with ConnectionError
```

how can i fix it. Is there any RPC concurrency setting i can modify to increase the concurrency a client can handle?

**Comment by bas-vk** [comment]
There are no RPC settings to configure RPC performance. Maybe you can boost performance a bit with some general go parameters but I doubt this will make a huge difference.

Could you give some load numbers or share your test?

**Comment by rjl493456442** [comment]
i start 4 processes together and each of them has about 100 coroutines, the error mentioned above will occur, however , when i start 2 processes only, it can be much better(no error occur).
i'm confused because a server writed by go it's performance should be great. 
So i want konw is anybody else meet this problem

**Comment by rjl493456442** [comment]
Is there to much connections  and the connections number exceed the server limit ? In another way , should i use long connection rather than short connection to fix it ?

**Comment by bas-vk** [comment]
If 2 processes work and 4 not then there is a real change that you are hitting some kind of a limit. The question is, is it fair what you are demanding of the system? Based on the information you provided it's not possible to determine this. If all of the 400 coroutines can make concurrent requests this can cause quite a load and over-stress the system.

The RPC server doesn't enforce a connection limit. Any limits are imposed by the OS. If you hit these limits you should find something in the logs.

Try to measure resource load (cpu, mem, disk usage) and check if the OS is limiting resources that geth requires. For instance, on linux you can use cgroups to limit the amount of resources a process can take.

**Comment by bas-vk** [comment]
@rjl493456442, if this is still an issue please give an update with more information.
Otherwise I will close this (or feel free to close it yourself).

**Comment by rjl493456442** [comment]
Actually, i didn't figure out the reason right now. But i think the OS performance might is the main reason.
