### ISSUE TITLE
EIP-3607 Implementation

### ISSUE THREAD

**Issue by pcaversaccio** [ethereum/go-ethereum#28374]
Currently, geth implements [EIP-3607](https://eips.ethereum.org/EIPS/eip-3607) (a.k.a. reject transactions from senders with deployed code) as [follows](https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L283-L288):

```go
// Make sure the sender is an EOA
codeHash := st.state.GetCodeHash(msg.From)
if codeHash != (common.Hash{}) && codeHash != types.EmptyCodeHash {
	return fmt.Errorf("%w: address %v, codehash: %s", ErrSenderNoEOA,
		msg.From.Hex(), codeHash)
}
```

I'm having a hard time in understanding why `codeHash` is checked against the zero hash `common.Hash` as this is not required by EIP-3607. Can you maybe enlighten me 😄?

**Comment by holiman** [comment]
`codeHash` is a `common.Hash`, not a pointer. As such, the `null`-value for it is `(common.Hash{})` -- the empty hash, 20 zeroes. 

If the lookup ` st.state.GetCodeHash(msg.From)` fails, then by necessity the return value is the zero-hash. This lookup could fail for any number or reasons. 

In general, whenever we deal with a `common.Hash`, we need to check it against the empty hash, much as we would check any pointer type if it is `nil`.
