### ISSUE TITLE
Archive goerli node fails to start after upgrading to 1.13.4 -  MemTableSize (4.0GB) must be < 4.0GB

### ISSUE THREAD

**Issue by y-f-u** [ethereum/go-ethereum#28384]
#### System information

Geth
Version: 1.13.4-stable
Git Commit: 3f907d6a6f6de09cff1360ed529126765939851d
CL client & version: prysm/beacon-chain:v4.0.8
Architecture: amd64
OS version: linux ubuntu docker
Go Version: go1.21.3

#### Expected behaviour

Running below command
```
geth --goerli --db.engine pebble --http --http.addr 0.0.0.0 --http.vhosts * --http.api eth,admin,txpool,debug,net,web3 --rpc.evmtimeout 1m --ws --ws.addr 0.0.0.0 --ws.origins * --ws.api eth,admin,txpool,debug,net,web3 --graphql --syncmode full --gcmode archive --cache 131072 --cache.preimages --datadir.ancient /root/.ethereum/ancient --maxpeers 128 --txlookuplimit 0 --metrics
```

Goerli archive node using pebble starts normally after upgrading to 1.13.4.

#### Actual behaviour

Goerli archive node using pebble failed to start after upgrading to 1.13.4, The error is:

```
    2023-10-19T15:22:35.621008159Z 2023/10/19 15:22:35 Fatal: Failed to register the Ethereum service: MemTableSize (4.0GB) must be < 4.0GB
```
The same command with same data starts successfully with 1.13.2

#### Steps to reproduce the behaviour

- A fully synced goerli archive node using pebble using 1.13.2
- upgrade geth to 1.13.4
- run `geth --goerli --db.engine pebble --http --http.addr 0.0.0.0 --http.vhosts * --http.api eth,admin,txpool,debug,net,web3 --rpc.evmtimeout 1m --ws --ws.addr 0.0.0.0 --ws.origins * --ws.api eth,admin,txpool,debug,net,web3 --graphql --syncmode full --gcmode archive --cache 131072 --cache.preimages --datadir.ancient /root/.ethereum/ancient --maxpeers 128 --txlookuplimit 0 --metrics`

**Comment by karalabe** [comment]
@rjl493456442 I think we should cap it in our code for now to fix the releases and leave a TODO to revert when/if it lands upstream. I'm unsure when that happens and would be nice to unblock us in the mean time.
