### ISSUE TITLE
Missing sender address on the transaction on core/types/transaction.go

### ISSUE THREAD

**Issue by niranjanshr13** [ethereum/go-ethereum#28385]
# Rationale

Why should this feature exist?
So, can access who is the sender in the transaction.

What are the use-cases?
it is missing on the code, why query it, it is necessary who is the sender. the code only provide who is recipient address.

# Implementation

Do you have ideas regarding the implementation of this feature?
Yes, just need a "From" function similar to "To" in the code.

Are you willing to implement this feature?
Sure.

**Comment by karalabe** [comment]
The sender can be derived from the signature. https://pkg.go.dev/github.com/ethereum/go-ethereum/core/types#Sender
