### ISSUE TITLE
Remove dev ppa?

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/go-ethereum#2838]
Hey, not sure if this is intential or not, but the installation instructions for ubuntu include a development ppa

https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu

**Comment by wawrzek** [comment]
I agree - that silly.

**Comment by fjl** [comment]
For  the geth 1.5 release, the development version will become a separate package (ethereum-unstable, geth-unstable, ...) in the same PPA.

**Comment by fjl** [comment]
This is now done. `ethereum-unstable` packages will be published to the main PPA from now on.
