### ISSUE TITLE
Guys, I have a question about SubscribeFilterLogs

### ISSUE THREAD

**Issue by ljlong0908** [ethereum/go-ethereum#28395]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.
`package main

import (
	"context"
	"fmt"
	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/ethclient"
	"log"
)

func main() {
	client, err := ethclient.Dial("wss://xx")
	if err != nil {
		log.Fatal(err)
	}
	contractAddress := common.HexToAddress("xxx")
	query := ethereum.FilterQuery{
		Addresses: []common.Address{contractAddress},
	}
	logs := make(chan types.Log)
	sub, err := client.SubscribeFilterLogs(context.Background(), query, logs)
	if err != nil {
		log.Fatal(err)
	}
	for {
		select {
		case err := <-sub.Err():
			log.Fatal(err)
		case vLog := <-logs:
			fmt.Println(vLog) // pointer to event log
		}
	}
}
`
**err: websocket: close 1006 (abnormal closure): unexpected EOF**

With the above code, an error will be reported after 1 minute or so, has anyone encountered it？thanks

**Comment by zcpua** [comment]
How did you solve this problem?
