### ISSUE TITLE
Unknown peers error

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#28392]
**Description:**

I am experiencing an issue where my node is unable to connect to other nodes in the network. I am seeing the following error message in the logs:

"
**Error: unknown peer**
"

I have tried using both Elastic IPs and Static IPs, but the problem persists. I am wondering if there is anything else I can do to fix this issue.

I have attached a screenshot of the error message.
![image](https://github.com/ethereum/go-ethereum/assets/46569970/6af660ec-a029-4503-b2eb-f3132399d0ba)
![image](https://github.com/ethereum/go-ethereum/assets/46569970/595816fa-cbfc-450d-9903-7e904033013e)

**Comment by holiman** [comment]
dup https://github.com/ethereum/go-ethereum/issues/28391
