### ISSUE TITLE
JIT VM Error report. Consensus issues.

### ISSUE THREAD

**Issue by JonConnington** [ethereum/go-ethereum#2839]
#### System information

Geth version: `Dao relese`
OS & Version: Windows
Commit hash : (if `develop`)

#### Expected behaviour
Syncs

#### Actual behaviour
Consensus error

#### Steps to reproduce the behaviour
Started with empty database hour before the fork. Stoped syncy an hour after. Restarted bus issue persists. Geth told me to report it somewhere so here I am.

#### Backtrace

````
[backtrace]
````

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

\Desktop\geth.exe --support-dao-fork
I0721 01:09:36.208644 cmd/utils/flags.go:678] You're one of the lucky few that will try out the JIT VM (random). If you get a consensus failure please be so kind to report this incident with the block hash that failed. You can switch to the regular VM by setting --jitvm=false
I0721 01:09:36.212655 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to 

I0721 01:09:36.640287 cmd/utils/flags.go:842] ------------------------------------------------------------------------------------------------
I0721 01:09:36.642323 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!
I0721 01:09:36.643325 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0721 01:09:36.645330 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0721 01:09:36.647306 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------
I0721 01:09:36.654326 ethdb/database.go:169] closed 
I0721 01:09:36.669248 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to 
I0721 01:09:36.809542 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to
I0721 01:09:36.819544 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0721 01:09:36.822553 eth/backend.go:201] Blockchain DB Version: 3
I0721 01:09:36.824549 core/blockchain.go:206] Last header: #65535 [fbd10bce…] TD=74628733770047273
I0721 01:09:36.826553 core/blockchain.go:207] Last block: #1750348 [f3c309aa…] TD=29799787353193366401
I0721 01:09:36.827556 core/blockchain.go:208] Fast block: #65535 [fbd10bce…] TD=74628733770047273
I0721 01:09:36.830590 p2p/server.go:313] Starting Server
I0721 01:09:36.871261 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using NAT-PMP(192.168.0.1)
I0721 01:09:36.880518 p2p/discover/udp.go:217] Listening, enode://c1f3e56540622012e14ce92564a9060048dc581b96dcac4732bf2e6e8dcfb8acecab7546a305af6324dbb28312f98952e403f422aef25fe4e2235d8d4fcc9bc8@
I0721 01:09:36.885532 p2p/server.go:556] Listening on [::]:30303
I0721 01:09:36.885532 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc
I0721 01:09:36.922630 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(192.168.0.1)
I0721 01:10:06.886540 eth/downloader/downloader.go:320] Block synchronisation started
I0721 01:10:16.776570 eth/handler.go:295] Peer a979fb575495b8d6 [eth/63]: timed out DAO fork-check, dropping
E0721 01:11:41.678696 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:11:41.681704 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:11:41.684211 trie/secure_trie.go:94] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:11:41.686758 core/blockchain.go:1127] Bad block #1750350 (0xc46a14656b6ab1ff74042cbd2955376fc1ad5007ec0209cc5fc9078f7782fd8d)
E0721 01:11:41.689265 core/blockchain.go:1128]     invalid merkle root: header=32be9e54965d6b413a4b99fc26e2bdf6a713826740918659ab7c1f1e0bf844b6 computed=ed716925579e3a7d4cac79b3bc7bc2e7701b055ad8c82602645e29e912c37ebc
E0721 01:11:50.413755 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:11:50.426810 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:11:50.433811 trie/secure_trie.go:94] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:11:50.438824 core/blockchain.go:1127] Bad block #1750350 (0xc46a14656b6ab1ff74042cbd2955376fc1ad5007ec0209cc5fc9078f7782fd8d)
E0721 01:11:50.442360 core/blockchain.go:1128]     invalid merkle root: header=32be9e54965d6b413a4b99fc26e2bdf6a713826740918659ab7c1f1e0bf844b6 computed=ed716925579e3a7d4cac79b3bc7bc2e7701b055ad8c82602645e29e912c37ebc
E0721 01:12:14.053034 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:12:14.060053 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:12:14.069076 trie/secure_trie.go:94] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:12:14.077097 core/blockchain.go:1127] Bad block #1750350 (0xc46a14656b6ab1ff74042cbd2955376fc1ad5007ec0209cc5fc9078f7782fd8d)
E0721 01:12:14.080105 core/blockchain.go:1128]     invalid merkle root: header=32be9e54965d6b413a4b99fc26e2bdf6a713826740918659ab7c1f1e0bf844b6 computed=ed716925579e3a7d4cac79b3bc7bc2e7701b055ad8c82602645e29e912c37ebc
I0721 01:12:21.248734 eth/handler.go:295] Peer 759a4a30abe23931 [eth/63]: timed out DAO fork-check, dropping
I0721 01:12:29.823962 eth/handler.go:295] Peer 2b4ae107c2fbd1ba [eth/63]: timed out DAO fork-check, dropping
E0721 01:13:37.723070 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:13:37.731566 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:13:37.750616 trie/secure_trie.go:94] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:13:37.756632 core/blockchain.go:1127] Bad block #1750350 (0xc46a14656b6ab1ff74042cbd2955376fc1ad5007ec0209cc5fc9078f7782fd8d)
E0721 01:13:37.768664 core/blockchain.go:1128]     invalid merkle root: header=32be9e54965d6b413a4b99fc26e2bdf6a713826740918659ab7c1f1e0bf844b6 computed=ed716925579e3a7d4cac79b3bc7bc2e7701b055ad8c82602645e29e912c37ebc
E0721 01:14:04.796235 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:14:04.804255 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:14:04.809295 trie/secure_trie.go:94] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:14:04.814307 core/blockchain.go:1127] Bad block #1750350 (0xc46a14656b6ab1ff74042cbd2955376fc1ad5007ec0209cc5fc9078f7782fd8d)
E0721 01:14:04.819323 core/blockchain.go:1128]     invalid merkle root: header=32be9e54965d6b413a4b99fc26e2bdf6a713826740918659ab7c1f1e0bf844b6 computed=ed716925579e3a7d4cac79b3bc7bc2e7701b055ad8c82602645e29e912c37ebc
E0721 01:14:28.103499 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:14:28.118040 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:14:28.125058 trie/secure_trie.go:94] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:14:28.131074 core/blockchain.go:1127] Bad block #1750350 (0xc46a14656b6ab1ff74042cbd2955376fc1ad5007ec0209cc5fc9078f7782fd8d)
E0721 01:14:28.137090 core/blockchain.go:1128]     invalid merkle root: header=32be9e54965d6b413a4b99fc26e2bdf6a713826740918659ab7c1f1e0bf844b6 computed=ed716925579e3a7d4cac79b3bc7bc2e7701b055ad8c82602645e29e912c37ebc
I0721 01:15:09.581532 eth/handler.go:295] Peer cdca50b09fd1cac4 [eth/63]: timed out DAO fork-check, dropping
I0721 01:16:15.887695 eth/handler.go:295] Peer 59170e9302795400 [eth/63]: timed out DAO fork-check, dropping
E0721 01:16:25.974062 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:16:25.977069 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:16:25.997122 trie/secure_trie.go:94] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:16:26.023200 core/blockchain.go:1127] Bad block #1750350 (0xc46a14656b6ab1ff74042cbd2955376fc1ad5007ec0209cc5fc9078f7782fd8d)
E0721 01:16:26.028213 core/blockchain.go:1128]     invalid merkle root: header=32be9e54965d6b413a4b99fc26e2bdf6a713826740918659ab7c1f1e0bf844b6 computed=ed716925579e3a7d4cac79b3bc7bc2e7701b055ad8c82602645e29e912c37ebc
E0721 01:16:29.098241 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:16:29.106293 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:16:29.114282 trie/secure_trie.go:94] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:16:29.121805 core/blockchain.go:1127] Bad block #1750350 (0xc46a14656b6ab1ff74042cbd2955376fc1ad5007ec0209cc5fc9078f7782fd8d)
E0721 01:16:29.128352 core/blockchain.go:1128]     invalid merkle root: header=32be9e54965d6b413a4b99fc26e2bdf6a713826740918659ab7c1f1e0bf844b6 computed=ed716925579e3a7d4cac79b3bc7bc2e7701b055ad8c82602645e29e912c37ebc
I0721 01:16:37.483722 eth/downloader/downloader.go:1081] Peer 737122ec74741c15 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 18.02290929s]: empty head header set
E0721 01:16:55.719078 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:16:55.721083 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:16:55.724091 trie/secure_trie.go:94] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:16:55.727100 core/blockchain.go:1127] Bad block #1750350 (0xc46a14656b6ab1ff74042cbd2955376fc1ad5007ec0209cc5fc9078f7782fd8d)
E0721 01:16:55.732122 core/blockchain.go:1128]     invalid merkle root: header=32be9e54965d6b413a4b99fc26e2bdf6a713826740918659ab7c1f1e0bf844b6 computed=ed716925579e3a7d4cac79b3bc7bc2e7701b055ad8c82602645e29e912c37ebc
E0721 01:17:00.346690 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:17:00.350713 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:17:00.354713 trie/secure_trie.go:94] Unhandled trie error: Missing trie node 59806ded0e5a592f87d9a9df28f2e9524466070765998d1491d0d766f02e414f
E0721 01:17:00.356712 core/blockchain.go:1127] Bad block #1750350 (0xc46a14656b6ab1ff74042cbd2955376fc1ad5007ec0209cc5fc9078f7782fd8d)
E0721 01:17:00.359736 core/blockchain.go:1128]     invalid merkle root: header=32be9e54965d6b413a4b99fc26e2bdf6a713826740918659ab7c1f1e0bf844b6 computed=ed716925579e3a7d4cac79b3bc7bc2e7701b055ad8c82602645e29e912c37ebc

**Comment by fjl** [comment]
This looks like a DB corruption issue.

**Comment by fjl** [comment]
Merged into #2289
