### ISSUE TITLE
Unknown peers error

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#28391]
**Description:**

I am experiencing an issue where my node is unable to connect to other nodes in the network. I am seeing the following error message in the logs:

**"
Error: unknown peer
"**

I have tried using both Elastic IPs and Static IPs, but the problem persists. I am wondering if there is anything else I can do to fix this issue.

I have attached a screenshot of the error message.
![image](https://github.com/ethereum/go-ethereum/assets/46569970/1e7faab0-9796-4930-b674-cc20eccbb298)

**Comment by holiman** [comment]
What parameters are you using to run geth? What geth-version?
Also, you managed to screenshot so the actual `err` was omitted. If possible, try to copy-paste the text instead of screenshotting.

**Comment by AsadullahSoomro** [comment]
How to fix it. I tried changing the port of the boot node, but it didn't work, and it is quite challenging. 

I attempted various solutions, such as adjusting firewall rules and permitting specific TCP and UDP ports after that I also closed the ICMP PING rule on the AWS Server Console Inside the inbound rules.
 
 ./bootnode -nodekey "./boot.key" --verbosity 7 -addr "0.0.0.0:30301" --nat extip:3.131.42.160
 
 I am using geth version v1.10.23-unstable/Linux-amd64/ and Go version go1.20.9

 

> ./bootnode -nodekey "./boot.key" --verbosity 5 -addr "172.31.18.182:30301" --nat extip:3.131.42.160
enode://510f449a79b1fc76f1b8277af495647205f55429143dc629f9d0817ad5a3e673bd8edcc58caeda6c82b6b672dd9e8348eba72bad52b414e4be220b409df55ebb@3.131.42.160:0?discport=30301
Note: you're using cmd/bootnode, a developer tool.
We recommend using a regular node as bootstrap node for production deployments.
INFO [10-20|11:37:51.444] Mapped network port                      proto=udp extport=30301 intport=30301 interface=ExtIP(3.131.42.160)
INFO [10-20|11:37:51.446] New local node record                    seq=1,697,801,871,446 id=7da3ba01c43eded4 ip=<nil> udp=0 tcp=0
TRACE[10-20|11:38:09.250] << PING/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374 err=nil
TRACE[10-20|11:38:09.250] >> PONG/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374 err=nil
TRACE[10-20|11:38:09.250] >> PING/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374 err=nil
TRACE[10-20|11:38:09.300] << PONG/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374 err=nil
TRACE[10-20|11:38:10.830] << PING/v4                               id=d7bc5814e21a242a addr=191.96.150.226:42586 err=nil
TRACE[10-20|11:38:10.830] >> PONG/v4                               id=d7bc5814e21a242a addr=191.96.150.226:42586 err=nil
TRACE[10-20|11:38:10.830] >> PING/v4                               id=d7bc5814e21a242a addr=191.96.150.226:42586 err=nil
TRACE[10-20|11:38:10.933] << PONG/v4                               id=d7bc5814e21a242a addr=191.96.150.226:42586 err=nil
TRACE[10-20|11:38:11.434] << FINDNODE/v4                           id=d7bc5814e21a242a addr=191.96.150.226:42586 err=nil
TRACE[10-20|11:38:11.434] >> NEIGHBORS/v4                          id=d7bc5814e21a242a addr=191.96.150.226:42586 err=nil
TRACE[10-20|11:38:12.060] >> PING/v4                               id=d7bc5814e21a242a addr=191.96.150.226:42586 err=nil
TRACE[10-20|11:38:12.164] << PONG/v4                               id=d7bc5814e21a242a addr=191.96.150.226:42586 err=nil
TRACE[10-20|11:38:12.164] >> ENRREQUEST/v4                         id=d7bc5814e21a242a addr=191.96.150.226:42586 err=nil
TRACE[10-20|11:38:12.267] << ENRRESPONSE/v4                        id=d7bc5814e21a242a addr=191.96.150.226:42586 err=nil
DEBUG[10-20|11:38:12.267] Revalidated node                         b=16 id=d7bc5814e21a242a checks=1
TRACE[10-20|11:38:15.032] << PING/v4                               id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
TRACE[10-20|11:38:15.032] >> PONG/v4                               id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
TRACE[10-20|11:38:15.032] >> PING/v4                               id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
TRACE[10-20|11:38:15.266] << PONG/v4                               id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
TRACE[10-20|11:38:15.766] << FINDNODE/v4                           id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
TRACE[10-20|11:38:15.767] >> NEIGHBORS/v4                          id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
TRACE[10-20|11:38:16.941] << FINDNODE/v4                           id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:38:16.941] >> NEIGHBORS/v4                          id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:38:17.324] >> PING/v4                               id=d7bc5814e21a242a addr=91.137.64.112:30303   err=nil
DEBUG[10-20|11:38:17.825] Removed dead node                        b=16 id=d7bc5814e21a242a ip=91.137.64.112 checks=1
TRACE[10-20|11:38:17.940] >> PING/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:38:17.991] << PONG/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:38:17.991] >> ENRREQUEST/v4                         id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:38:18.042] << ENRRESPONSE/v4                        id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
DEBUG[10-20|11:38:18.042] Revalidated node                         b=13 id=6c20d4b82b99310c checks=1
TRACE[10-20|11:38:20.895] >> PING/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:38:20.945] << PONG/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
DEBUG[10-20|11:38:20.945] Revalidated node                         b=13 id=6c20d4b82b99310c checks=2
TRACE[10-20|11:38:21.801] >> PING/v4                               id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
TRACE[10-20|11:38:22.031] << PONG/v4                               id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
TRACE[10-20|11:38:22.031] >> ENRREQUEST/v4                         id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
TRACE[10-20|11:38:22.261] << ENRRESPONSE/v4                        id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
DEBUG[10-20|11:38:22.261] Revalidated node                         b=16 id=dfe42bb5a196be3e checks=1
TRACE[10-20|11:38:24.200] >> PING/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:38:24.250] << PONG/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
DEBUG[10-20|11:38:24.250] Revalidated node                         b=13 id=6c20d4b82b99310c checks=3
TRACE[10-20|11:38:27.009] << PING/v4                               id=b743a5f5d6d04cf9 addr=89.187.168.120:30008  err=nil
TRACE[10-20|11:38:27.010] >> PONG/v4                               id=b743a5f5d6d04cf9 addr=89.187.168.120:30008  err=nil
TRACE[10-20|11:38:27.010] >> PING/v4                               id=b743a5f5d6d04cf9 addr=89.187.168.120:30008  err=nil
TRACE[10-20|11:38:27.119] << PONG/v4                               id=b743a5f5d6d04cf9 addr=89.187.168.120:30008  err=nil
TRACE[10-20|11:38:27.618] << FINDNODE/v4                           id=b743a5f5d6d04cf9 addr=89.187.168.120:30008  err=nil
TRACE[10-20|11:38:27.618] >> NEIGHBORS/v4                          id=b743a5f5d6d04cf9 addr=89.187.168.120:30008  err=nil
TRACE[10-20|11:38:29.517] << PING/v4                               id=f498b997af43070b addr=37.19.218.193:30020   err=nil
TRACE[10-20|11:38:29.517] >> PONG/v4                               id=f498b997af43070b addr=37.19.218.193:30020   err=nil
TRACE[10-20|11:38:29.517] >> PING/v4                               id=f498b997af43070b addr=37.19.218.193:30020   err=nil
TRACE[10-20|11:38:29.653] << PONG/v4                               id=f498b997af43070b addr=37.19.218.193:30020   err=nil
TRACE[10-20|11:38:30.154] << FINDNODE/v4                           id=f498b997af43070b addr=37.19.218.193:30020   err=nil
TRACE[10-20|11:38:30.154] >> NEIGHBORS/v4                          id=f498b997af43070b addr=37.19.218.193:30020   err=nil
TRACE[10-20|11:38:32.275] >> PING/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:38:32.326] << PONG/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
DEBUG[10-20|11:38:32.326] Revalidated node                         b=13 id=6c20d4b82b99310c checks=4
TRACE[10-20|11:38:41.117] >> PING/v4                               id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
TRACE[10-20|11:38:41.348] << PONG/v4                               id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
DEBUG[10-20|11:38:41.348] Revalidated node                         b=16 id=dfe42bb5a196be3e checks=2
TRACE[10-20|11:38:47.568] << PING/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:38:47.568] >> PONG/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:38:47.569] >> PING/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:38:47.605] << PONG/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:38:47.605] << ENRREQUEST/v4                         id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:38:47.605] >> ENRRESPONSE/v4                        id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:38:49.719] >> PING/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:38:49.769] << PONG/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
DEBUG[10-20|11:38:49.769] Revalidated node                         b=13 id=6c20d4b82b99310c checks=5
TRACE[10-20|11:38:55.548] >> PING/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:38:55.599] << PONG/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
DEBUG[10-20|11:38:55.599] Revalidated node                         b=13 id=6c20d4b82b99310c checks=6
TRACE[10-20|11:39:04.638] >> PING/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:39:04.688] << PONG/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
DEBUG[10-20|11:39:04.688] Revalidated node                         b=13 id=6c20d4b82b99310c checks=7
TRACE[10-20|11:39:06.578] >> PING/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:39:06.611] << PONG/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
DEBUG[10-20|11:39:06.611] Revalidated node                         b=12 id=72bb3bb8df9eb9dc checks=1
TRACE[10-20|11:39:11.154] >> PING/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
DEBUG[10-20|11:39:11.187] Revalidated node                         b=12 id=72bb3bb8df9eb9dc checks=2
TRACE[10-20|11:39:11.187] << PONG/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:39:12.611] << PING/v4                               id=bee4512bdddeb7a2 addr=34.246.37.47:30311    err=nil
TRACE[10-20|11:39:12.611] >> PONG/v4                               id=bee4512bdddeb7a2 addr=34.246.37.47:30311    err=nil
TRACE[10-20|11:39:12.611] >> PING/v4                               id=bee4512bdddeb7a2 addr=34.246.37.47:30311    err=nil
TRACE[10-20|11:39:12.690] << PONG/v4                               id=bee4512bdddeb7a2 addr=34.246.37.47:30311    err=nil
TRACE[10-20|11:39:12.691] << PING/v4                               id=bee4512bdddeb7a2 addr=34.246.37.47:30311    err=nil
TRACE[10-20|11:39:12.691] >> PONG/v4                               id=bee4512bdddeb7a2 addr=34.246.37.47:30311    err=nil
TRACE[10-20|11:39:13.188] << ENRREQUEST/v4                         id=bee4512bdddeb7a2 addr=34.246.37.47:30311    err=nil
TRACE[10-20|11:39:13.189] >> ENRRESPONSE/v4                        id=bee4512bdddeb7a2 addr=34.246.37.47:30311    err=nil
TRACE[10-20|11:39:13.268] << ENRREQUEST/v4                         id=bee4512bdddeb7a2 addr=34.246.37.47:30311    err=nil
TRACE[10-20|11:39:13.268] >> ENRRESPONSE/v4                        id=bee4512bdddeb7a2 addr=34.246.37.47:30311    err=nil
TRACE[10-20|11:39:15.612] << FINDNODE/v4                           id=bee4512bdddeb7a2 addr=34.246.37.47:30311    err=nil
TRACE[10-20|11:39:15.612] >> NEIGHBORS/v4                          id=bee4512bdddeb7a2 addr=34.246.37.47:30311    err=nil
TRACE[10-20|11:39:16.483] >> PING/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:39:16.520] << PONG/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
DEBUG[10-20|11:39:16.520] Revalidated node                         b=12 id=72bb3bb8df9eb9dc checks=3
TRACE[10-20|11:39:16.741] >> PING/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:39:16.791] << PONG/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
DEBUG[10-20|11:39:16.792] Revalidated node                         b=13 id=6c20d4b82b99310c checks=8
TRACE[10-20|11:39:17.870] << PING/v4                               id=9af2b267570a3d4b addr=139.59.27.114:30303   err=nil
TRACE[10-20|11:39:17.871] >> PONG/v4                               id=9af2b267570a3d4b addr=139.59.27.114:30303   err=nil
TRACE[10-20|11:39:17.871] >> PING/v4                               id=9af2b267570a3d4b addr=139.59.27.114:30303   err=nil
TRACE[10-20|11:39:18.103] << PONG/v4                               id=9af2b267570a3d4b addr=139.59.27.114:30303   err=nil
TRACE[10-20|11:39:18.603] << FINDNODE/v4                           id=9af2b267570a3d4b addr=139.59.27.114:30303   err=nil
TRACE[10-20|11:39:18.603] >> NEIGHBORS/v4                          id=9af2b267570a3d4b addr=139.59.27.114:30303   err=nil
TRACE[10-20|11:39:20.856] << PING/v4                               id=91f5c7e5cabe05cf addr=184.23.212.125:30303  err=nil
TRACE[10-20|11:39:20.856] >> PONG/v4                               id=91f5c7e5cabe05cf addr=184.23.212.125:30303  err=nil
TRACE[10-20|11:39:20.856] >> PING/v4                               id=91f5c7e5cabe05cf addr=184.23.212.125:30303  err=nil
TRACE[10-20|11:39:20.927] << PONG/v4                               id=91f5c7e5cabe05cf addr=184.23.212.125:30303  err=nil
TRACE[10-20|11:39:21.436] << FINDNODE/v4                           id=91f5c7e5cabe05cf addr=184.23.212.125:30303  err=nil
TRACE[10-20|11:39:21.436] >> NEIGHBORS/v4                          id=91f5c7e5cabe05cf addr=184.23.212.125:30303  err=nil
TRACE[10-20|11:39:23.478] >> PING/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:39:23.513] << PONG/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
DEBUG[10-20|11:39:23.513] Revalidated node                         b=12 id=72bb3bb8df9eb9dc checks=4
TRACE[10-20|11:39:29.690] << PING/v4                               id=f4f722bc6381f723 addr=89.233.104.43:30303   err=nil
TRACE[10-20|11:39:29.691] >> PONG/v4                               id=f4f722bc6381f723 addr=89.233.104.43:30303   err=nil
TRACE[10-20|11:39:29.691] >> PING/v4                               id=f4f722bc6381f723 addr=89.233.104.43:30303   err=nil
INFO [10-20|11:39:29.852] New local node record                    seq=1,697,801,871,447 id=7da3ba01c43eded4 ip=3.131.42.160  udp=30301 tcp=0
TRACE[10-20|11:39:29.852] << PONG/v4                               id=f4f722bc6381f723 addr=89.233.104.43:30303   err=nil
TRACE[10-20|11:39:29.852] << ENRREQUEST/v4                         id=f4f722bc6381f723 addr=89.233.104.43:30303   err=nil
TRACE[10-20|11:39:29.852] >> ENRRESPONSE/v4                        id=f4f722bc6381f723 addr=89.233.104.43:30303   err=nil
TRACE[10-20|11:39:31.176] >> PING/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:39:31.227] << PONG/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
DEBUG[10-20|11:39:31.227] Revalidated node                         b=13 id=6c20d4b82b99310c checks=9
TRACE[10-20|11:39:32.391] >> PING/v4                               id=b743a5f5d6d04cf9 addr=89.187.168.120:30008  err=nil
DEBUG[10-20|11:39:32.892] Removed dead node                        b=16 id=b743a5f5d6d04cf9 ip=89.187.168.120 checks=0
TRACE[10-20|11:39:38.750] >> PING/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
TRACE[10-20|11:39:38.801] << PONG/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
DEBUG[10-20|11:39:38.801] Revalidated node                         b=13 id=6c20d4b82b99310c checks=10
TRACE[10-20|11:39:45.051] >> PING/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
DEBUG[10-20|11:39:45.084] Revalidated node                         b=12 id=72bb3bb8df9eb9dc checks=5
TRACE[10-20|11:39:45.084] << PONG/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:39:45.084] << ENRREQUEST/v4                         id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:39:45.084] >> ENRRESPONSE/v4                        id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:39:51.318] >> PING/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
DEBUG[10-20|11:39:51.362] Revalidated node                         b=12 id=72bb3bb8df9eb9dc checks=6
TRACE[10-20|11:39:51.362] << PONG/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:39:52.702] >> PING/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
TRACE[10-20|11:39:52.736] << PONG/v4                               id=72bb3bb8df9eb9dc addr=69.174.135.203:39570  err=nil
DEBUG[10-20|11:39:52.736] Revalidated node                         b=12 id=72bb3bb8df9eb9dc checks=7
TRACE[10-20|11:39:56.926] << FINDNODE/v4                           id=d7bc5814e21a242a addr=191.96.150.226:42586  err=nil
TRACE[10-20|11:39:56.927] >> NEIGHBORS/v4                          id=d7bc5814e21a242a addr=191.96.150.226:42586  err=nil
TRACE[10-20|11:40:00.634] >> PING/v4                               id=f498b997af43070b addr=37.19.218.193:30020   err=nil
TRACE[10-20|11:40:00.769] << PONG/v4                               id=f498b997af43070b addr=37.19.218.193:30020   err=nil
TRACE[10-20|11:40:00.770] >> ENRREQUEST/v4                         id=f498b997af43070b addr=37.19.218.193:30020   err=nil
TRACE[10-20|11:40:00.905] << ENRRESPONSE/v4                        id=f498b997af43070b addr=37.19.218.193:30020   err=nil
DEBUG[10-20|11:40:00.905] Revalidated node                         b=16 id=f498b997af43070b checks=1
TRACE[10-20|11:40:06.181] >> PING/v4                               id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
TRACE[10-20|11:40:06.409] << PONG/v4                               id=dfe42bb5a196be3e addr=206.189.131.178:30303 err=nil
DEBUG[10-20|11:40:06.409] Revalidated node                         b=16 id=dfe42bb5a196be3e checks=3
TRACE[10-20|11:40:10.435] >> PING/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=nil
DEBUG[10-20|11:40:10.485] Revalidated node                         b=13 id=6c20d4b82b99310c checks=11
TRACE[10-20|11:40:10.485] << PONG/v4                               id=6c20d4b82b99310c addr=100.20.109.236:30374  err=ni

 
![image](https://github.com/ethereum/go-ethereum/assets/46569970/320ee8fb-135b-49ae-8a2a-6985e1d00136)

**Comment by AsadullahSoomro** [comment]
![image (20)](https://github.com/ethereum/go-ethereum/assets/46569970/fac85654-b5a7-472d-8d69-7df2a0bba7c5)
![image (20)](https://github.com/ethereum/go-ethereum/assets/46569970/65284bf7-c26f-4633-a99f-210457ef7670)

**Comment by AsadullahSoomro** [comment]
![image (22)](https://github.com/ethereum/go-ethereum/assets/46569970/879292bd-6cac-4d3e-9e1e-a31ab788c6d0)

**Comment by AsadullahSoomro** [comment]
![image (21)](https://github.com/ethereum/go-ethereum/assets/46569970/5376950b-4f4d-4de3-8aeb-23cc7d1f91ec)

**Comment by AsadullahSoomro** [comment]
@holiman  Please check the above parameters and attached Screenshots:

**Comment by AsadullahSoomro** [comment]
Dear @holiman, I am trying to connect dynamically other nodes with Bootnode, otherwise we use static IPs.

**Comment by AsadullahSoomro** [comment]
So, I am currently exploring methods to prevent connections with unknown peers so that our node connection can be faster and more stable and try to change the port of the boot node to remove the unknown peers that can slow down our boot node and make it less stable as mentioned below: 
![image (23)](https://github.com/ethereum/go-ethereum/assets/46569970/1531189e-5aec-4d15-8bc9-a9bd675ab266)

**Comment by AsadullahSoomro** [comment]
Dear @holiman, 

I am trying to connect the Geth node to the boot node, but I am getting unknown peers and flying peers. I am trying to connect to other nodes dynamically with Bootnode, but otherwise, we use static IPs.

**Comment by holiman** [comment]
Please do not post any more screenshots. Instead, try to formulate what you want to achieve. Examples could be 

- I am trying to sync the ethereum mainnet, or 
- I am trying to set up a private network, using `n` nodes and a `bootnode`. 

Take a few minutes to collect your thoughts and the relevant information.

**Comment by holiman** [comment]
> Take a few minutes to collect your thoughts and the relevant information.

A few minutes passed, seems abandoned.
