### ISSUE TITLE
Corrupted state results in bad block

### ISSUE THREAD

**Issue by 18600294832** [ethereum/go-ethereum#28390]
this is my geth log 

> ERROR[10-20|15:46:24.495] 
########## BAD BLOCK #########
Block: 18390139 (0x3ce244823125147f0227916efb4e10e404f4765cc37e4347dcc31b0750275a27)
Error: invalid merkle root (remote: 1927976a6302f04579fafade9d2350454a4236a59c368af05a854c142b2c8c51 local: 11bf8ead4fc9cf3d3297456e5b94272df48f7b776a01ba22f49e37771f685e6e) dberr: %!w(<nil>)
Platform: geth (devel) go1.19.5 amd64 linux
VCS: f39aeeaa-20230616
Chain config: &params.ChainConfig{ChainID:1, HomesteadBlock:1150000, DAOForkBlock:1920000, DAOForkSupport:true, EIP150Block:2463000, EIP150Hash:0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0, EIP155Block:2675000, EIP158Block:2675000, ByzantiumBlock:4370000, ConstantinopleBlock:7280000, PetersburgBlock:7280000, IstanbulBlock:9069000, MuirGlacierBlock:9200000, BerlinBlock:12244000, LondonBlock:12965000, ArrowGlacierBlock:13773000, GrayGlacierBlock:15050000, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc000048298), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), TerminalTotalDifficulty:58750000000000000000000, TerminalTotalDifficultyPassed:true, Ethash:(*params.EthashConfig)(0x2b45800), Clique:(*params.CliqueConfig)(nil)}
Receipts: 
  0: cumulative: 48051 gas: 48051 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x8bff80b6acc595fec7ed74b191e87133ec64b13e47f8606f5f236fb117842343 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: 
  1: cumulative: 190334 gas: 142283 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x439a71c550935e8c43e0736022a22245554168c1f04b3e33f0ce321548fd9c09 logs: [0xc1c8466210 0xc1c84666e0 0xc1c8466840] bloom: 00000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000002000000080020000000040000000000000000000000000800000208000000000000000000040000000000000000000000080000000002000000000000000000020000000000000000000010000800000020000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000800000000000000000000000000000000000000002000000000000000000000000000000000400000000000000000000000000200000000000000000000000000000200000000000000000000000000000 state: 
  2: cumulative: 291598 gas: 101264 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xee323c3de0357d716a0976b834f29682e8fe3c2cc4f5d2a6ff10013319674bc8 logs: [0xc1c8466e70 0xc1c8467340 0xc1c84676b0 0xc1c8467810] bloom: 0020000000000000000000048000000000100000000000000001000000000000000000000000000000000000000000000200000008000000000000000000000000400000000000000000000c000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000004000000004000000000000000000000000001080000004000000000000800000000000000000000200000000000000000000000000000000000000000000002000000000000000000000000000800000000001000000400000020000000200000000000000000000008000000000000000000000000000000000000 state: 
  3: cumulative: 462121 gas: 170523 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x728bd6fec00ba3bbb2ab4b3d022de41da8accee145a7dcc466f836e5ba3d8451 logs: [0xc1c8467970 0xc1c8467b80 0xc1c8467ce0 0xc1c8467e40 0xc1c4f5e000 0xc1c4f5e8f0] bloom: 00200000000000040200000080000000000000000000000000080000000000000000000000004000000000000000000002000000080200000000004000000000002000080000000000000008000000200000000000000000040000008020000000000000000000040000000000000000000000000000000000000010000000000000000000000000000000000000000000000001000000080002104000000000000000000000000000000000000000000040000000000000000000000000000000000002000000000000001000000000000000000000001000000000000000000000200000000020000000008000000000001000000000400000000000000000 state: 
  4: cumulative: 483121 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x1da690de7d22757253d6d44478522df8ddf1b203b5b8c69c022084937d9d186d logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: 
  5: cumulative: 689726 gas: 206605 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x4d5ae63e85086700e200ec5a949a9af6b116477acd904f19e5911c135358069d logs: [0xc1c4f5ebb0 0xc1c4f5efd0 0xc1c4f5f4a0 0xc1c4f5f970 0xc1c4f5fad0 0xc1c4f5fc30 0xc1c4f5fd90 0xc1c4f5fef0 0xc1c9228630 0xc1c92289a0 0xc1c9229760] bloom: 002010000000000000000000800010000040000000000000000000002000000000000000004000040000000000000000020000400800000000000000002000000004004000000000080000080000002000000001000000000000000000000005000080000000000000008000000000000000000001000000100040100000000000800000000000080000000000000000000000004300000a0000004000000000020000600000200000000000000000000000000000000000010000000000010000000002000800000000000000000000000020004000001000000000000000480010200000000000000002000000010000005000000000000000000000000000 state: 
  ..........
##############################
 
WARN [10-20|15:46:24.495] NewPayloadV1: inserting block failed     error="invalid merkle root (remote: 1927976a6302f04579fafade9d2350454a4236a59c368af05a854c142b2c8c51 local: 11bf8ead4fc9cf3d3297456e5b94272df48f7b776a01ba22f49e37771f685e6e) dberr: %!w(<nil>)"
WARN [10-20|15:47:44.615] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=128
WARN [10-20|15:47:44.867] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=128
WARN [10-20|15:47:45.101] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=110
WARN [10-20|15:47:45.665] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=128
WARN [10-20|15:47:45.901] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=128
WARN [10-20|15:47:46.134] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=85
WARN [10-20|15:47:46.647] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=128
WARN [10-20|15:47:46.880] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=126
WARN [10-20|15:47:47.102] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=60
WARN [10-20|15:47:47.728] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=128
WARN [10-20|15:47:47.972] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=127
WARN [10-20|15:47:48.199] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=94
WARN [10-20|15:47:48.937] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=128
WARN [10-20|15:47:49.174] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=128
WARN [10-20|15:47:49.390] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=56
WARN [10-20|15:47:49.951] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=127
WARN [10-20|15:47:50.182] Peer delivering stale transactions       peer=fa8eebafbe71b5f56e9f2d9a74a0bc8c473ef696c262c66cd7d6aecd3d67475e rejected=128

WARN [10-20|16:07:24.036] Snapshot extension registration failed   peer=1d4fc8e3 err="peer connected on snap without compatible eth support"
WARN [10-20|16:07:40.942] Snapshot extension registration failed   peer=1d4ddff1 err="peer connected on snap without compatible eth support"
WARN [10-20|16:10:02.834] Peer delivering stale transactions       peer=3445697be2a892f725f0e0b0bcef4d2aeff1eb190deef3e64a0ec9fc3f8b3027 rejected=128
WARN [10-20|16:10:03.066] Peer delivering stale transactions       peer=3445697be2a892f725f0e0b0bcef4d2aeff1eb190deef3e64a0ec9fc3f8b3027 rejected=128
WARN [10-20|16:12:55.807] Peer delivering stale transactions       
WARN [10-20|16:15:54.709] Snapshot extension registration failed   peer=3d249168 err="peer connected on snap without compatible eth support"
WARN [10-20|16:15:58.667] Peer delivering stale transactions       peer=3445697be2a892f725f0e0b0bcef4d2aeff1eb190deef3e64a0ec9fc3f8b3027 rejected=128
WARN [10-20|16:16:09.662] Peer delivering stale transactions       peer=3445697be2a892f725f0e0b0bcef4d2aeff1eb190deef3e64a0ec9fc3f8b3027 rejected=110
WARN [10-20|16:20:22.211] Snapshot extension registration failed   peer=450a16c3 err="peer connected on snap without compatible eth support"
WARN [10-20|16:28:26.342] Peer delivering stale transactions       
WARN [10-20|16:30:58.354] Too many bad block import attempt, trying number=18,390,139 hash=3ce244..275a27
INFO [10-20|16:30:58.444] Skip duplicated bad block                number=18,390,139 hash=3ce244..275a27
ERROR[10-20|16:30:58.447] 
########## BAD BLOCK #########
Block: 18390139 (0x3ce244823125147f0227916efb4e10e404f4765cc37e4347dcc31b0750275a27)
Error: invalid merkle root (remote: 1927976a6302f04579fafade9d2350454a4236a59c368af05a854c142b2c8c51 local: 11bf8ead4fc9cf3d3297456e5b94272df48f7b776a01ba22f49e37771f685e6e) dberr: %!w(<nil>)
Platform: geth (devel) go1.19.5 amd64 linux
VCS: f39aeeaa-20230616
Chain config: &params.ChainConfig{ChainID:1, HomesteadBlock:1150000, DAOForkBlock:1920000, DAOForkSupport:true, EIP150Block:2463000, EIP150Hash:0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0, EIP155Block:2675000, EIP158Block:2675000, ByzantiumBlock:4370000, ConstantinopleBlock:7280000, PetersburgBlock:7280000, IstanbulBlock:9069000, MuirGlacierBlock:9200000, BerlinBlock:12244000, LondonBlock:12965000, ArrowGlacierBlock:13773000, GrayGlacierBlock:15050000, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc000048298), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), TerminalTotalDifficulty:58750000000000000000000, TerminalTotalDifficultyPassed:true, Ethash:(*params.EthashConfig)(0x2b45800), Clique:(*params.CliqueConfig)(nil)}
Receipts: 
  0: cumulative: 48051 gas: 48051 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x8bff80b6acc595fec7ed74b191e87133ec64b13e47f8606f5f236fb117842343 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: 
  1: cumulative: 190334 gas: 142283 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x439a71c550935e8c43e0736022a22245554168c1f04b3e33f0ce321548fd9c09 logs: [0xc326384580 0xc326384630 0xc3263846e0] bloom: 00000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000002000000080020000000040000000000000000000000000800000208000000000000000000040000000000000000000000080000000002000000000000000000020000000000000000000010000800000020000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000800000000000000000000000000000000000000002000000000000000000000000000000000400000000000000000000000000200000000000000000000000000000200000000000000000000000000000 state: 
  2: cumulative: 291598 gas: 101264 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xee323c3de0357d716a0976b834f29682e8fe3c2cc4f5d2a6ff10013319674bc8 logs: [0xc3263848f0 0xc3263849a0 0xc326384a50 0xc326384b00] bloom: 0020000000000000000000048000000000100000000000000001000000000000000000000000000000000000000000000200000008000000000000000000000000400000000000000000000c000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000004000000004000000000000000000000000001080000004000000000000800000000000000000000200000000000000000000000000000000000000000000002000000000000000000000000000800000000001000000400000020000000200000000000000000000008000000000000000000000000000000000000 state: 
 
##############################
 
WARN [10-20|16:30:58.447] NewPayloadV1: inserting block failed     error="invalid merkle root (remote: 1927976a6302f04579fafade9d2350454a4236a59c368af05a854c142b2c8c51 local: 11bf8ead4fc9cf3d3297456e5b94272df48f7b776a01ba22f49e37771f685e6e) dberr: %!w(<nil>)"
INFO [10-20|16:31:10.086] Writing clean trie cache to disk         path=/home/data/geth/triecache              threads=1
INFO [10-20|16:31:10.088] Regenerated local transaction journal    transactions=0 accounts=0
INFO [10-20|16:31:14.398] Persisted the clean trie cache           path=/home/data/geth/triecache              elapsed=4.311s
WARN [10-20|16:37:02.087] Snapshot extension registration failed   peer=291b513a err="peer connected on snap without compatible eth support"
WARN [10-20|16:37:34.620] Peer delivering stale transactions       peer=58ea165a0f96fa25e3c372aaf5b54a12d24c5489ddbd650b195dea0db4d0e7a9 rejected=52

WARN [10-20|16:43:47.817] Snapshot extension registration failed   peer=04199d53 err="peer connected on snap without compatible eth support"
WARN [10-20|16:44:21.436] Snapshot extension registration failed   peer=4ba692d3 err="peer connected on snap without compatible eth support"

**Comment by MartyMari** [comment]
Hello, have you resolve this issue?
Error is with the block?

**Comment by MariusVanDerWijden** [comment]
@18600294832 Your best bet to fix this is to resync your node.
You can drop the state with `geth removedb` and then type `y` `n` `y`. This will leave the ancients intact, so you don't need to download as much data

**Comment by holiman** [comment]
Answered, seems abandoned
