### ISSUE TITLE
problem about "Error: gas required exceeds allowance (0)"

### ISSUE THREAD

**Issue by lpx-single** [ethereum/go-ethereum#28433]
#### System information

`Geth: 1.13.5-unstable`
`Architecture: amd64`
`Go Version: go1.21.3`
`Operating System: linux`

#### Expected behaviour
I am a beginner in learning ethereum and I want to set up a private chain with multiple pcs through Geth. I gradually follow the official documentation(https://geth.ethereum.org/docs/fundamentals/private-network, End-to-end example part) to build the network on two virtual machine(two nodes) on VMware Workstation 16+. I hope those two nodes can send tokens to each other just like the document finally implements.

#### Actual behaviour
When I type `admin.peers()`, it can return the details of another node, so it seems the two nodes are connected. 
![image](https://github.com/ethereum/go-ethereum/assets/75900633/d909aaab-ac18-48a3-9713-85cd933fef0a)

Each node has 500000 Wei allocated in genesis.json. However, when I type
`eth.sendTransaction({to: another node's address, from: eth.accounts[0], value: 25000})`,
it fails with error:
![image](https://github.com/ethereum/go-ethereum/assets/75900633/de77163b-8d1b-4e7b-ab2e-8c57a8c7d7c5)
And also,  according to the document, the bootnode's terminal should display the discover process like:
`INFO [05-13|15:50:03.645] New local node record                    seq=1,652,453,403,645 id=a2d37f4a7d515b3a ip=nil udp=0 tcp=0`
`TRACE[05-13|16:15:49.228]  PING/v4                               id=f1364e6d060c4625 addr=127.0.0.1:30306 err=nil`
`TRACE[05-13|16:15:49.229]  PONG/v4                               id=f1364e6d060c4625 addr=127.0.0.1:30306 err=nil`
`TRACE[05-13|16:15:49.229]  PING/v4                               id=f1364e6d060c4625 addr=127.0.0.1:30306 err=nil`
`TRACE[05-13|16:15:49.230]  PONG/v4                               id=f1364e6d060c4625 addr=127.0.0.1:30306 err=nil`
`…`
However, my bootnode terminal only show the first line:
`INFO [05-13|15:50:03.645] New local node record                    seq=1,652,453,403,645 id=a2d37f4a7d515b3a ip=nil udp=0 tcp=0`
I am not sure if it is ok.

**Comment by MariusVanDerWijden** [comment]
> I am not sure if it is ok. 
Yes thats okay your log level is info while the tutorial has log level trace (just outputs more benign logs)

Is 0xd82... a smart contract? You should give yourself way more money than just 500.000 wei

**Comment by larsberge** [comment]
I also still get the same error:

`Error: gas required exceeds allowance (0)`

 even after https://github.com/ethereum/go-ethereum/issues/28450
