### ISSUE TITLE
Disk I/O hammering

### ISSUE THREAD

**Issue by hdiedrich** [ethereum/go-ethereum#2843]
#### System information

Geth version: `1.4.x+`
OS & Version: `Linux/OSX`
Commit hash: n/a

#### Expected behaviour

Use harddisk I/O consciously.

#### Actual behaviour

Harddisks seem to be slammed in spikes for no discernible reason for fully synched client.

![disk-io](https://cloud.githubusercontent.com/assets/246863/17020450/eb7ec53e-4f41-11e6-9e6e-1508fde10804.png)

#### Steps to reproduce the behaviour

Any geth client in mainnet.

**Comment by obscuren** [comment]
Thanks for the report. This is a known issue and we are working on a solution.

Reason why the disk is getting hammered is due to the random look ups that need to be done when reading blocks, state and other relevant information. 

The `develop` branch already contains 1 part of the solution where keys of blocks are logically ordered by leveldb. The state trie key optimization is still being worked on by @karalabe.

**Comment by hdiedrich** [comment]
Cool, thanks! Maybe #2841 will make a difference as it reduces background block validations load.

**Comment by slothbag** [comment]
Trying to sync from a few weeks behind with a mechanical HDD is painfully slow.  You can see the Disk IO both read and write maxed out.

Looking forward to the fix :)

**Comment by TbLtzk** [comment]
I see the very same behavior now with geth 1.5.3 on Windows 10. Didn't have problems with 1.4.18 but had to upgrade because of the dissense with parity.

**Comment by lostmsu** [comment]
@fjl the issue is still there. geth does ~10MB/s read and 10MB/s write constantly on my machine. Surely there should be some trick to avoid that. More caching?

**Comment by got3nks** [comment]
We are seeing very high I/O usage of over 10Mb/s both write and read too.

`
Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.2
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
`

**Comment by karalabe** [comment]
Leveldb occasionally compacts the db in the background. That can take quite
some time and disk io. We're trying to figure out some new database schema
to reduce these, but no short term trick I'm afraid.

**Comment by TAiS46** [comment]
```
Total DISK READ :      40.96 M/s | Total DISK WRITE :      38.57 M/s
Actual DISK READ:      40.96 M/s | Actual DISK WRITE:      40.69 M/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
28235 be/4 ubuntu     11.22 M/s    5.09 M/s  0.00 % 55.52 % geth --cache=4024
28237 be/4 ubuntu     17.44 M/s   20.56 M/s  0.00 % 19.00 % geth --cache=4024
28234 be/4 ubuntu     10.83 M/s   12.37 M/s  0.00 % 15.26 % geth --cache=4024
28238 be/4 ubuntu    921.97 K/s    0.00 B/s  0.00 %  6.94 % geth --cache=4024
```

we need a fix for this!
