### ISSUE TITLE
SimulatedBackend doesn't match ethereum interface and ethclient

### ISSUE THREAD

**Issue by s1na** [ethereum/go-ethereum#28431]
As far as I understand the goal is that the interfaces defined [here](https://github.com/ethereum/go-ethereum/blob/master/interfaces.go) match that of ethclient and SimulatedBackend so it's easy to swap out a real node RPC server with a simulated blockchain. However there are currently a few differences preventing this:

- `PendingBalanceAt`, `PendingStorageAt` and `PendingTransactionCount` are not defined on the simulated backend
- `SubscribePendingTransactions` is part of the interfaces, but it is not defined on the simulated backend. Also it is defined on gethclient, not directly on ethclient.

**Comment by bnovil** [comment]
I have the same thought. It seems better that `SimulatedBackend` implements the interface `PendingStateReader`.
