### ISSUE TITLE
End-to-end example of private network is missing signer

### ISSUE THREAD

**Issue by jakezhu9** [ethereum/go-ethereum#28450]
I am trying to build a private network, and I find that in the [end-to-end example](https://geth.ethereum.org/docs/fundamentals/private-network#end-to-end-example), nothing is mentioned about the signers, which results in blocks not being created and the transactions in the document failing (error message: gas required exceeds allowance(0)).

I also find #28433 and #28251, which seem to be happening because of this.

we should make it more clearly

**Comment by fjl** [comment]
Thanks for fixing!
