### ISSUE TITLE
Management APIs contains invalid information

### ISSUE THREAD

**Issue by ThePiachu** [ethereum/go-ethereum#2845]
I recently tried to implement [`personal_sendTransaction`](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_sendtransaction) JSON RPC method from the Management APIs wiki page. However, I kept constantly getting errors of `The method personal_sendTransaction does not exist/is not available`. I then stumbled upon [this discussion](https://github.com/ethereum/EIPs/issues/113) and found out that the correct method name is now `personal_signAndSendTransaction`. The Management APIs wiki should be updated to reflect that.

Also, while we're on that page, under `List of management APIs`, the main link to the `personal` section is `https://github.com/ethereum/go-ethereum/wiki/personal`, while it should be `https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal`.

**Comment by karalabe** [comment]
Thanks for reporting these! I've fixed the second issue with the wrong link.

@bas-vk Could you look into the first part of this issue? I'm not sure how the API evolved so can't say which version is correct.

**Comment by bas-vk** [comment]
The old name is `personal_signAndSendTransaction`, the new name is `personal_sendTransaction`. The PR that renames this function is still pending: https://github.com/ethereum/go-ethereum/pull/2712. Would be nice if that can get merged.

**Comment by karalabe** [comment]
@bas-vk I've merged that PR in, thanks!

@ThePiachu I've updated the wiki to feature the correct version on current develop and also mentioned in a note that prior to Geth 1.5, it's `personal_signAndSendTransaction`.
