### ISSUE TITLE
Version 1.13.4 detected as a malicious file

### ISSUE THREAD

**Issue by peonante** [ethereum/go-ethereum#28452]
Why is version 1.13.4 detected as a malicious file? I tried downloading the last 5 versions, actually it only happens with the latter 
i mean from here https://geth.ethereum.org/downloads

**Comment by karalabe** [comment]
Which file specifically? What OS? What program detects it as malicious?

**Comment by peonante** [comment]
Windows 11 Pro 22H2

Windows Defender:
**App**: geth-windows-amd64-1.13.4-3f907d6a.exe

**Trojan**:Win32/Vigorf.A

**webfile**: C:\Users\user\Downloads\geth-windows-amd64-1.13.4-3f907d6a.exe|https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.13.4-3f907d6a.exe|pid:12528,ProcessStart:133427992842351789

**Comment by Oguidan** [comment]
@peonante geth surely want to acces some files or memories protected by Windows

**Comment by peonante** [comment]
> @peonante geth surely want to acces some files or memories protected by Windows

so can I rest easy? I found it strange that it is the only version with this problem

**Comment by Oguidan** [comment]
@peonante, a malicious file, can be a file trying to gain unauthorized access to your computer system. This means a harmless file can be considered a malicious file by an antivirus. Or similarities in code or behavior between legitimate and malicious software. Also, don't forget that we are dealing with blockchain here. Programs can try to gain unauthorized access to your computer system. Surely, there is an update that caused this.

**Comment by Oguidan** [comment]
@peonante, a malicious file, can be a file trying to gain unauthorized access to your computer system. This means a harmless file can be considered a malicious file by an antivirus. Or similarities in code or behavior between legitimate and malicious software. Also, don't forget that we are dealing with blockchain here. Programs can try to gain unauthorized access to your computer system. Surely, there is an update that caused this.

**Comment by karalabe** [comment]
https://www.virustotal.com/gui/file/b146894b320f6b165cc8b1bad27f9421279bff22af549ea28c050000d74ec653 seems to be clean by most vendors, just one flags it with some weird tag...
