### ISSUE TITLE
Node stuck with Unindexing Transactions, State Healing, Unexpected Trienode Heal Packet, Stale Transactions

### ISSUE THREAD

**Issue by crypto-date** [ethereum/go-ethereum#28465]
#### System information

Geth version: v1.13.4
CL client & version: lodestar 1.10.0
OS & Version:/Linux/ 
Commit hash : (if `develop`)

#### Expected behaviour
Node syncs

#### Actual behaviour
6 days of trying to sync. Running Rocketpool under the hood.  Hardware is a NUC with 2 tb  SSD w/ 32gb ram that worked fine until a bug in Nethermind forced us to change clients to Geth. What can we do? Is this a race condition that will never resolve? Node is stuck with the following logs:
`
rocketpool_eth1  | INFO [11-04|16:59:05.990] Unindexing transactions                  blocks=6,416,113 txs=1,126,361,179 total=6,727,009 elapsed=15h47m26.003s
rocketpool_eth1  | INFO [11-04|16:59:07.697] Syncing: chain download in progress      synced=100.00% chain=604.37GiB headers=18,500,015@8.50GiB bodies=18,499,944@430.35GiB receipts=18,499,944@165.52GiB eta=10m57.120s
rocketpool_eth1  | INFO [11-04|16:59:13.790] Forkchoice requested sync to new head    number=18,500,016 hash=f73fc7..bc0ec5 finalized=18,499,930
rocketpool_eth1  | INFO [11-04|16:59:14.212] Unindexing transactions                  blocks=6,416,283 txs=1,126,387,522 total=6,727,009 elapsed=15h47m34.225s
rocketpool_eth1  | INFO [11-04|16:59:15.701] Syncing: chain download in progress      synced=100.00% chain=604.37GiB headers=18,500,015@8.50GiB bodies=18,499,944@430.35GiB receipts=18,499,944@165.52GiB eta=11m6.441s
rocketpool_eth1  | INFO [11-04|16:59:16.305] Syncing: state healing in progress       accounts=376,686@19.26MiB slots=621,465@47.22MiB codes=4225@31.53MiB nodes=21,560,807@5.32GiB pending=5587
rocketpool_eth1  | INFO [11-04|16:59:22.338] Unindexing transactions                  blocks=6,416,441 txs=1,126,412,129 total=6,727,009 elapsed=15h47m42.351s
rocketpool_eth1  | INFO [11-04|16:59:23.705] Syncing: chain download in progress      synced=100.00% chain=604.37GiB headers=18,500,016@8.50GiB bodies=18,499,944@430.35GiB receipts=18,499,944@165.52GiB eta=11m6.507s
rocketpool_eth1  | INFO [11-04|16:59:27.809] Forkchoice requested sync to new head    number=18,500,017 hash=bc7d35..bbe2c6 finalized=18,499,930
rocketpool_eth1  | INFO [11-04|16:59:30.379] Unindexing transactions                  blocks=6,416,637 txs=1,126,441,597 total=6,727,009 elapsed=15h47m50.392s
rocketpool_eth1  | INFO [11-04|16:59:31.710] Syncing: chain download in progress      synced=100.00% chain=604.37GiB headers=18,500,017@8.50GiB bodies=18,499,944@430.35GiB receipts=18,499,944@165.52GiB eta=11m15.831s
rocketpool_eth1  | INFO [11-04|16:59:38.621] Unindexing transactions                  blocks=6,416,817 txs=1,126,469,613 total=6,727,009 elapsed=15h47m58.634s
rocketpool_eth1  | INFO [11-04|16:59:39.715] Syncing: chain download in progress      synced=100.00% chain=604.37GiB headers=18,500,017@8.50GiB bodies=18,499,944@430.35GiB receipts=18,499,944@165.52GiB eta=11m25.157s
rocketpool_eth1  | INFO [11-04|16:59:40.055] Forkchoice requested sync to new head    number=18,500,018 hash=ad44bb..9b38e6 finalized=18,499,930
rocketpool_eth1  | INFO [11-04|16:59:47.721] Syncing: chain download in progress      synced=100.00% chain=604.37GiB headers=18,500,018@8.50GiB bodies=18,499,944@430.35GiB receipts=18,499,944@165.52GiB eta=11m25.225s
rocketpool_eth1  | INFO [11-04|16:59:50.238] Unindexing transactions                  blocks=6,417,000 txs=1,126,497,107 total=6,727,009 elapsed=15h48m10.251s
rocketpool_eth1  | INFO [11-04|16:59:51.364] Forkchoice requested sync to new head    number=18,500,019 hash=e0a4a1..e47060 finalized=18,499,930
rocketpool_eth1  | WARN [11-04|16:59:53.834] Peer delivering stale transactions       peer=4c1692d2ba758f07726fa0bc1718bb77c1212c44a300871de904467163b4fd1d rejected=95
rocketpool_eth1  | WARN [11-04|16:59:54.183] Peer delivering stale transactions       peer=ce421451fcc722dd40f0c4b7f1875bc1e89ca172557e2aa8767bd8c0a97d79e4 rejected=97
rocketpool_eth1  | INFO [11-04|16:59:55.736] Syncing: chain download in progress      synced=100.00% chain=604.37GiB headers=18,500,019@8.50GiB bodies=18,499,944@430.35GiB receipts=18,499,944@165.52GiB eta=11m34.554s
rocketpool_eth1  | INFO [11-04|17:00:00.940] Unindexing transactions                  blocks=6,419,000 txs=1,126,786,248 total=6,727,009 elapsed=15h48m20.953s
rocketpool_eth1  | WARN [11-04|17:00:01.957] Peer delivering stale transactions       peer=4c1692d2ba758f07726fa0bc1718bb77c1212c44a300871de904467163b4fd1d rejected=94
rocketpool_eth1  | WARN [11-04|17:00:01.989] Peer delivering stale transactions       peer=ce421451fcc722dd40f0c4b7f1875bc1e89ca172557e2aa8767bd8c0a97d79e4 rejected=45
rocketpool_eth1  | INFO [11-04|17:00:02.928] Syncing: state healing in progress       accounts=376,686@19.26MiB slots=621,465@47.22MiB codes=4225@31.53MiB nodes=21,561,187@5.32GiB pending=10783
rocketpool_eth1  | INFO [11-04|17:00:03.741] Syncing: chain download in progress      synced=100.00% chain=604.37GiB headers=18,500,019@8.50GiB bodies=18,499,944@430.35GiB receipts=18,499,944@165.52GiB eta=11m34.622s
rocketpool_eth1  | INFO [11-04|17:00:10.047] Unindexing transactions                  blocks=6,420,000 txs=1,126,929,076 total=6,727,009 elapsed=15h48m30.060s
rocketpool_eth1  | WARN [11-04|17:00:10.684] Peer delivering stale transactions       peer=4c1692d2ba758f07726fa0bc1718bb77c1212c44a300871de904467163b4fd1d rejected=94
rocketpool_eth1  | INFO [11-04|17:00:11.746] Syncing: chain download in progress      synced=100.00% chain=604.37GiB headers=18,500,019@8.50GiB bodies=18,499,944@430.35GiB receipts=18,499,944@165.52GiB eta=11m34.691s
rocketpool_eth1  | WARN [11-04|17:00:11.961] Unexpected trienode heal packet          peer=6b36f791 reqid=2,153,649,152,678,430,492
rocketpool_eth1  | INFO [11-04|17:00:11.961] Syncing: state healing in progress       accounts=376,686@19.26MiB slots=621,465@47.22MiB codes=4225@31.53MiB nodes=21,561,187@5.32GiB pending=10783
rocketpool_eth1  | INFO [11-04|17:00:12.804] Forkchoice requested sync to new head    number=18,500,020 hash=833fdb..6fdf04 finalized=18,499,930
rocketpool_eth1  | INFO [11-04|17:00:19.077] Unindexing transactions                  blocks=6,421,000 txs=1,127,076,346 total=6,727,009 elapsed=15h48m39.090s
rocketpool_eth1  | INFO [11-04|17:00:19.751] Syncing: chain download in progress      synced=100.00% chain=604.37GiB headers=18,500,020@8.50GiB bodies=18,499,944@430.35GiB receipts=18,499,944@165.52GiB eta=11m44.024s
rocketpool_eth1  | WARN [11-04|17:00:21.869] Peer delivering stale transactions       peer=4c1692d2ba758f07726fa0bc1718bb77c1212c44a300871de904467163b4fd1d rejected=91
`
#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by crypto-date** [comment]
Well, I waited it out and it finally resolved.

**Comment by marlboroman81** [comment]
I have similar behavior with stale transactions.
It looks like storm of stale transactions from my peers. During that storm my node becomes **extremely slow** (I've measured it).
Perhaps this is done with malicious intent. But there's **no mechanism to ban that peers** which delivering a lot of stale transactions.
That storm can last for a tens of minutes, and my node becomes almost unusable at that time :(
![geth_stale_1](https://github.com/ethereum/go-ethereum/assets/14112719/71500185-f518-4dc5-9bc0-ba252d49ddf7)
