### ISSUE TITLE
Outdated "bitchin' trick"

### ISSUE THREAD

**Issue by area** [ethereum/go-ethereum#2846]
The useless parameter passed to `miner.stop` in the 'mine only when there are transactions' trick [here](https://github.com/ethereum/go-ethereum/wiki/bitchin-tricks) - which is described as optional in [the documentation](https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#minerstop) - now appears to be mandatory:

```
> miner.stop(1)
Invalid number of input parameters
    at web3.js:3109:20
    at web3.js:4922:15
    at web3.js:4965:5
    at web3.js:4989:23
    at <anonymous>:1:1

> miner.stop()
true
```

**Comment by bas-vk** [comment]
I have updated the docs, thx for reporting this.
The thread count parameter is actually not mandatory but has been removed.

**Comment by area** [comment]
Huh, yeah, I'm meant that. Not sure why I typed what I did 😕
