### ISSUE TITLE
draining miner wallet

### ISSUE THREAD

**Issue by rupamharod1** [ethereum/go-ethereum#28476]
I am addressing a recurring issue with my blockchain node1, which serves as a critical miner in the network. This node is consistently experiencing fund depletion. Additionally, this node is linked to an HTTP interface, making it essential to monitor and troubleshoot the issue effectively. The ongoing depletion of funds from this miner is a significant concern, and I will explore the potential causes and solutions to ensure the sustained operation and profitability of this essential blockchain node

**Comment by karalabe** [comment]
Don't expose your node to the internet. The HTTP API is not meant as a public facing thing. If you need remote access to it, set up tunnels through SSH or other authenticated means.

**Comment by rupamharod1** [comment]
Thank you
