### ISSUE TITLE
Don't expose your node to the internet. The HTTP API is not meant as a public facing thing. If you need remote access to it, set up tunnels through SSH or other authenticated means.

### ISSUE THREAD

**Issue by rupamharod1** [ethereum/go-ethereum#28477]
Don't expose your node to the internet. The HTTP API is not meant as a public facing thing. If you need remote access to it, set up tunnels through SSH or other authenticated means.

_Originally posted by @karalabe in https://github.com/ethereum/go-ethereum/issues/28476#issuecomment-1798328667_

but we already set it up with https rpc

**Comment by karalabe** [comment]
RPC nodes should not have any accounts on them and you should restrict it to only expose the `eth` namespace.

**Comment by rupamharod1** [comment]
you mean 
./geth --datadir node1 --port 30306 --bootnodes enode://f7aba85ba369923bffd3438b4c8fde6b1f02b1c23ea0aac825ed7eac38e6230e5cadcf868e73b0e28710f4c9f685ca71a86a4911461637ae9ab2bd852939b77f@127.0.0.1:0?discport=30305  --networkid 123454321 --unlock 0xC1B2c0dFD381e6aC08f34816172d6343Decbb12b --password node1/password.txt --authrpc.port 8551 

--unlock and --mine flag should not be there to RPC node

**Comment by rupamharod1** [comment]
> RPC nodes should not have any accounts on them and you should restrict it to only expose the `eth` namespace.

can you please elaborate how command will look like
