### ISSUE TITLE
no transactions from goerli

### ISSUE THREAD

**Issue by peonante** [ethereum/go-ethereum#28478]
Greetings,
I can't understand why I can't get any information from the goerli network, while on the mainnet yes, I use geth v1.13.4 and prysm

this works:
```

geth --http --http.api eth,web3,net,txpool --ws --ws.api eth,web3,net,txpool --miner.etherbase 0x0000000000000000000000000000000000000001

//
   status: {
     pending: 1x,
     queued: 1x
   },

```
this does not work:

```
geth --goerli --http --http.api eth,web3,net,txpool --ws --ws.api eth,web3,net,txpool --miner.etherbase 0x000000000000000000000000000000000000001

//
   status: {
     pending: 0,
     queued: 0
   },
```

**Comment by Cognacy** [comment]
Are you still having this same issues?

**Comment by holiman** [comment]
Please provide logs of what your node doing. 
Also, please note `goerli` is deprecated in favour of `holesky`

**Comment by peonante** [comment]
I was using an old hard disk, perhaps too slow?

I purchased a latest generation Samsung SSD and it seems to work properly now.

I haven't changed the controls.

**Comment by lightclient** [comment]
Please reopen if you're able to reproduce this issue. Thanks!
