### ISSUE TITLE
> RPC nodes should not have any accounts on them and you should restrict it to only expose the `eth` namespace.

### ISSUE THREAD

**Issue by rupamharod1** [ethereum/go-ethereum#28485]
> RPC nodes should not have any accounts on them and you should restrict it to only expose the `eth` namespace.

can you please elaborate how command will be

_Originally posted by @rupamharod1 in https://github.com/ethereum/go-ethereum/issues/28477#issuecomment-1799294566_

**Comment by holiman** [comment]
> not have any accounts

simply: do not have any keystores on the machine
> only expose 'eth'

`--http.api=eth`
