### ISSUE TITLE
Geth commands don't seem to be working. 

### ISSUE THREAD

**Issue by Jsimpki** [ethereum/go-ethereum#2849]
I've only just got Geth today. However I can't use the web3 commands to see my balance at all. I try and it tells me that the command is neither a registered internal or external command. 

web3.fromWei(eth.getBalance(eth.coinbase), "ether")

**Comment by wawrzek** [comment]
How do you run it?

**Comment by bas-vk** [comment]
Based on the error you got my guess is that you type this command not in a geth console.
There is a wiki [page](https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console) with instructions how to start geth with the console.

**Comment by fjl** [comment]
timed out
