### ISSUE TITLE
Light client roadmap: implement "blsync" tool

### ISSUE THREAD

**Issue by zsfelfoldi** [ethereum/go-ethereum#28493]
Status: implemented, needs review + merge
Relevant branches:

- `CommitteeChain` data structure
	- https://github.com/zsfelfoldi/go-ethereum/tree/committee_chain
	- https://github.com/ethereum/go-ethereum/pull/27766
- `blsync` tool without finalized head feature
	- https://github.com/zsfelfoldi/go-ethereum/tree/blsync-nofinal4
		- REST API client side implementation
		- request/sync mechanism
		- flags, parameters
		- main logic (retrieve head blocks, call engine API)
- `blsync` tool with finalized head feature
	- https://github.com/zsfelfoldi/go-ethereum/tree/blsync-final4
		- beacon state API endpoint client side
		- autodetect whether a suitable API is available
		- fetch finalized beacon head and beacon -> EL head hash associations
		- add correct finalized EL head to engine API calls when available

**Comment by s1na** [comment]
I think this can be closed?
