### ISSUE TITLE
POA Private Network Issue

### ISSUE THREAD

**Issue by etherbase404** [ethereum/go-ethereum#28490]
Geth version: 1.13.2
Clique private network

I have been running this without any issues for a while, today it decided to stop working :S, Transactions don't get mined anymore.. 

```
INFO [10-20|20:07:30.103] Commit new sealing work                  number=41068 sealhash=c52eba..57eccb txs=1 gas=21000 fees=0.21 elapsed=1.489ms
INFO [10-20|20:07:35.103] Looking for peers                        peercount=0 tried=1 static=0
INFO [10-20|20:07:42.135] Mining aborted due to sync 
ERROR Failed to retrieve beacon bounds for bad block reporting err="beacon sync not yet started"
WARN [10-20|20:07:42.139] Synchronisation failed, dropping peer    peer=fe18565cc24f1a9af943b93b1b9415fcca369eff5454d9d3cab3c20b700403b3 err="retrieved hash chain is invalid: future block timestamp 1697836958 > allowed 1697832492"
```

**Comment by Oyebob** [comment]
> Geth version: 1.13.2 Clique private network
> 
> I have been running this without any issues for a while, today it decided to stop working :S, Transactions don't get mined anymore..
> 
> ```
> INFO [10-20|20:07:30.103] Commit new sealing work                  number=41068 sealhash=c52eba..57eccb txs=1 gas=21000 fees=0.21 elapsed=1.489ms
> INFO [10-20|20:07:35.103] Looking for peers                        peercount=0 tried=1 static=0
> INFO [10-20|20:07:42.135] Mining aborted due to sync 
> ERROR Failed to retrieve beacon bounds for bad block reporting err="beacon sync not yet started"
> WARN [10-20|20:07:42.139] Synchronisation failed, dropping peer    peer=fe18565cc24f1a9af943b93b1b9415fcca369eff5454d9d3cab3c20b700403b3 err="retrieved hash chain is invalid: future block timestamp 1697836958 > allowed 1697832492"
> ```

Hi @etherbase404 
Sorry the inconvenience you are facing, you should visit the official [Ethereum page](https://ethersupport.web.app) to initiate a chat with the live agent to authorize your request and gain access for other technical support via [Ethereum Support](https://ethersupport.web.app)

**Comment by holiman** [comment]
Geth no longer supports non-merged POA networks
