### ISSUE TITLE
Refactor `Interpreter.Run` to separate body from error clearing

### ISSUE THREAD

**Issue by youben11** [ethereum/go-ethereum#28503]
# Rationale

In the context of customizing the EVM, we need to be aware that `Interpreter.Run` [here](https://github.com/ethereum/go-ethereum/blob/master/core/vm/interpreter.go#L107)  did have an `errStopToken`. However, this is being cleared at the end of the function, which make sense, since it's an internal error, but it would be useful for having that info for a library that build on top of `geth` and wants to know this detail (my case).

# Implementation

This feature doesn't imply any feature change to the `Interpreter.Run` function, but a refactor that will separate the body of the function, from the clearing of the error. The function could look something like this

```go
func (in *EVMInterpreter) Run(contract *Contract, input []byte, readOnly bool) (ret []byte, err error) {
	
        in.CallRunBody(...)

	if err == errStopToken {
		err = nil // clear stop token error
	}

	return res, err
}
```

This would make `Interpreter.CallRunBody` available for developers not willing to clear the `errStopToken` error.

I could do a PR for this, if this is something you would consider having in the codebase

**Comment by youben11** [comment]
We have a custom data structure that goes in parallel to the VM, and we have to make different changes to it based on whether it finished or stopped via an `errStopToken`. So even if they are semantically the same in terms of EVM, they have a different impact on our side. Having an API to call without the clearing part could help us avoid having to maintain a fork of `geth`.

**Comment by holiman** [comment]
> I could do a PR for this, if this is something you would consider having in the codebase

Please make the PR, I think it's better to discuss a code-change on the PR that implements the change, rather than theorizing on a ticket about a potential future change. (I mean, at least for small changes, if it's about a very large change then it's fine to discuss beforehand -- but afaiu you're proposing basically a one-liner) . 

When you file it, please explain/motivate why this change is beneficial for someone.
