### ISSUE TITLE
execution reverted when using v1.13.x

### ISSUE THREAD

**Issue by robertchar92** [ethereum/go-ethereum#28500]
i'm trying to get erc20 token balance using balanceOf from smart contract i keep getting error "execution reverted" when using v1.13.x but after i downgrade it to v1.12.2 it's work.

`
        client, err := ethclient.Dial("https://endpoints.omniatech.io/v1/bsc/testnet/public")
        if err != nil {
	        log.Println("Failed to connect to ethclient", err)
        }

        tokenAddress := common.HexToAddress(contractAddress)
	instance, err := erc20_contract.NewErc20Contract(tokenAddress, client)
	if err != nil {
		log.Println("Failed to get initialize smart contract", err)
	}

	address := common.HexToAddress(walletAddress)
	balance, err := instance.BalanceOf(&bind.CallOpts{}, address)
	if err != nil {
		log.Println("Failed to get token balance from client", err)
	}
`

Smart Contract 
`
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

contract ERC20 {
    string public name = ""; // Add the name of your token here
    string public symbol = ""; // Add the symbol of your token here
    uint8 public decimals = 0; // Update the number of decimals as per your token

    mapping(address => uint256) private balances;
    mapping(address => mapping(address => uint256)) private allowed;
    uint256 private _totalSupply;

    constructor(uint256 initialSupply) {
        _totalSupply = initialSupply * 10 ** uint256(decimals);
        balances[msg.sender] = _totalSupply;
    }

    function totalSupply() public view returns (uint256) {
        return _totalSupply;
    }

    function balanceOf(address tokenOwner) public view returns (uint256 balance) {
        return balances[tokenOwner];
    }

    function allowance(address tokenOwner, address spender) public view returns (uint256 remaining) {
        return allowed[tokenOwner][spender];
    }

    function transfer(address to, uint256 tokens) public returns (bool success) {
        require(to != address(0), "Invalid address");
        require(balances[msg.sender] >= tokens, "Insufficient balance");

        balances[msg.sender] -= tokens;
        balances[to] += tokens;
        emit Transfer(msg.sender, to, tokens);
        return true;
    }

    function approve(address spender, uint256 tokens) public returns (bool success) {
        allowed[msg.sender][spender] = tokens;
        emit Approval(msg.sender, spender, tokens);
        return true;
    }

    function transferFrom(address from, address to, uint256 tokens) public returns (bool success) {
        require(from != address(0), "Invalid address");
        require(to != address(0), "Invalid address");
        require(balances[from] >= tokens, "Insufficient balance");
        require(allowed[from][msg.sender] >= tokens, "Allowance exceeded");

        balances[from] -= tokens;
        balances[to] += tokens;
        allowed[from][msg.sender] -= tokens;
        emit Transfer(from, to, tokens);
        return true;
    }

    event Transfer(address indexed from, address indexed to, uint256 tokens);
    event Approval(address indexed tokenOwner, address indexed spender, uint256 tokens);
}

`

it's there something i need to change to use v1.13.x?

**Comment by jsvisa** [comment]
Which token and holder address are you running

**Comment by robertchar92** [comment]
this is contract address for token Mock USDT
"0xff554674c40a2b3f6cd1d825e9d6f07518196605"

and for wallet/holder address i'm using generated address from this code 
`key, err := crypto.GenerateKey()
	if err != nil {
		log.Println(err)
		err := errors.ErrUnprocessableEntity
		err.Message = "Failed to create wallet address"
		return nil, err
	}

	privateKey := (*ecdsa.PrivateKey)(key)
	publicKey := privateKey.Public()
	publicKeyECDSA, ok := publicKey.(*ecdsa.PublicKey)
	if !ok {
		log.Println("error casting public key to ECDSA")
	}

	address := crypto.PubkeyToAddress(*publicKeyECDSA)

	var res WalletResponse

	res.WalletAddress = address.Hex()
	res.PrivateKey = hex.EncodeToString(crypto.FromECDSA(privateKey))`

this is example generated wallet address
"0x6838f2584b0dE46B1B8CF9a7e8cf3DE6a1d6C79d"

**Comment by jwasinger** [comment]
> https://endpoints.omniatech.io/v1/bsc/testnet/public

This is not the proper repository for BSC-related issues.  You should go and file an issue at https://github.com/bnb-chain/bsc
