### ISSUE TITLE
About POA private Ethereum network and Clique Algorithm

### ISSUE THREAD

**Issue by Rabishop** [ethereum/go-ethereum#28515]
**Background:** My assignment involves deploying a private Ethereum chain with three nodes, utilizing the Clique consensus algorithm. The three nodes also serve as validators responsible for signing. I've created three virtual instances on GCE, set up three nodes using Geth, and managed node passwords with Clef. The addresses of these three nodes are recorded in genesis.json, appointed as validators, and assigned a certain amount of tokens.

However, I made a mistake when creating the second node, resulting in the loss of the second node's password. Consequently, the second node is unable to perform its signing duties.

**Questions:**

1. Can I continue to seal blocks with only two signers? (I've attempted this, and it seems not possible. Nodes 1 and 3 both inform me that they need to wait for other nodes. My understanding is that, based on the Clique algorithm, at least three nodes are required to start sealing new blocks.)

2. Can I create a new node and use `clique.propose(address, auth)` to grant the new node signing permissions, allowing the blockchain to seal new blocks? (When attempting to add a new node to the chain with two existing nodes, I encountered the following issue.)

   ```
   WARN [11-12|21:04:40.719] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
   ```

3. This is an unrelated question, but I would appreciate your help. While reviewing the documentation, I found the following command:

   ```
   geth --datadir ./ddir --signer ./clef/clef.ipc --mine
   ```

   If I execute it directly, I get the following error:

   ```
   ERROR[11-12|21:11:34.675] Cannot start mining without etherbase    err="etherbase must be explicitly specified"
   Fatal: Failed to start mining: etherbase missing: etherbase must be explicitly specified
   ```

   This confuses me because the POA algorithm doesn't require mining. Should I add an `etherbase` or just remove `--mine`? What is the difference between the two?

**Comment by Azizzzss** [comment]
yes you should type the   --miner.etherbase  which will be ignored by the launch ipc that you launch

**Comment by holiman** [comment]
1. Clique is defined here: https://eips.ethereum.org/EIPS/eip-225 

> To ensure malicious signers (loss of signing key) cannot wreck havoc in the network, each signer is allowed to sign maximum one out of SIGNER_LIMIT consecutive blocks. 
> SIGNER_LIMIT: Number of consecutive blocks out of which a signer may only sign one.

>    Must be floor(SIGNER_COUNT / 2) + 1 to enforce majority consensus on a chain.


So, each signer is allowed to sign maxinum one out of 2 blocks. Should be fine with two out of three. 

2. Yes, if blocks are produced
3. You need to specify what address to use for sealing blocks, a.k.a mining. 

However, most of this is moot. Geth no longer supports pure POA chains, only  merged POA chains.
