### ISSUE TITLE
tx.From() is forbidden,what kind of function can use instead of it

### ISSUE THREAD

**Issue by shen-shui** [ethereum/go-ethereum#28554]
tx.From() is forbidden,what kind of function can use instead of it

**Comment by jwasinger** [comment]
You can construct a [signer](https://github.com/ethereum/go-ethereum/blob/c8a22020287e0260e2310a1b91a1aa9b795ca445/core/types/transaction_signing.go#L40) and use the `Signer.Sender` method to get the tx sender.

**Comment by jwasinger** [comment]
You can construct a

**Comment by shen-shui** [comment]
EIP155Signer := types.NewEIP155Signer(tx.ChainId())
		from, err1 := types.Sender(EIP155Signer, tx)
		if err1 != nil {
			xlog.CtxErrorf(ctx, "Failed to get sender address: %v", err1)
			return err
		}
		fromHex := from.Hex()
		
		
		I use this to get the tx sender but have the question:transaction type not supported,ethereum mainnet use EIP-155,right?
