### ISSUE TITLE
cancunSigner Hash() inclusion of blob/sidecar?

### ISSUE THREAD

**Issue by emailtovamos** [ethereum/go-ethereum#28563]
Why does the cancunSigner not include blob or sidecar? 

https://github.com/ethereum/go-ethereum/blob/460cc1673e583512cd83843ac2ab0186f0ddf1ab/core/types/transaction_signing.go#L226

How else the blob actually ends up in the pool or in the node once someone sends a blob transaction?

**Comment by karalabe** [comment]
Blob transactions have a field for that, called [BlobHashes](https://github.com/ethereum/go-ethereum/blob/master/core/types/tx_blob.go#L43).

**Comment by karalabe** [comment]
The blobs themselves are not part of the transaction, only their commitments are.
