### ISSUE TITLE
uint256: switch over the statedb package from big.Int to uint256.Int

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#28578]
We've built the uint256 library a long time ago, but never really got around to using it outside of the EVM. This is a shame, as the library is more performant than big.Int as well as more "correct", as in we don't need to special case overflows and negative numbers.

Whilst it might be non-trivial to switch certain parts of Geth over while keeping backwards compatibility, one place that might be less gnarly is the statedb internals. We kind of expect that some things might leak out, but statedb is not really something many people use API wise and it might help to do some cleanups there.

**Comment by Rene27132** [comment]
Fix

**Comment by holiman** [comment]
Done!
