### ISSUE TITLE
How to correctly calculate P95 for geth nodes?

### ISSUE THREAD

**Issue by Aracki** [ethereum/go-ethereum#28574]
We have metrics such as:
```
rpc_duration_all {quantile="0.5"} 159167.5
rpc_duration_all {quantile="0.75"} 583009.5
rpc_duration_all {quantile="0.95"} 4.652806199999995e+06
rpc_duration_all {quantile="0.99"} 9.18621095900001e+07
rpc_duration_all {quantile="0.999"} 4.71983917509e+08
rpc_duration_all {quantile="0.9999"} 4.72092548e+08
```

Those numbers seem very high for me, does it means we have to divide this with counter like this?

```
sum by (pod) (rate(rpc_duration_all{quantile='0.95', pod="$network-0"}[5m]))
/
sum by (pod) (rate(rpc_duration_all_count{pod="$network-0"}[5m]))
```

**Comment by karalabe** [comment]
The time should be nanoseconds, already averaged, no need to divide by anything.

**Comment by Aracki** [comment]
@karalabe Are you 100% sure it's nanoseconds, in our case it makes more sense if it'd be microsecond...?

**Comment by karalabe** [comment]
Positive https://github.com/ethereum/go-ethereum/blob/master/metrics/timer.go#L113
