### ISSUE TITLE
uint256: switch over the legacy txpool from big.Int to uint256.Int

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#28577]
We've built the uint256 library a long time ago, but never really got around to using it outside of the EVM. This is a shame, as the library is more performant than big.Int as well as more "correct", as in we don't need to special case overflows and negative numbers.

Whilst it might be non-trivial to switch certain parts of Geth over while keeping backwards compatibility, one place that might be easier is the txpool/legacytxpool internals. That should not ripple across our code at all, but should help make progress on the switchover effort.

**Comment by holiman** [comment]
Done in $28606
