### ISSUE TITLE
Possible account spoofing when calling constant methods

### ISSUE THREAD

**Issue by brendan87** [ethereum/go-ethereum#2859]
#### System information

Geth version: `1.5.0`
OS & Version: Windows 10

#### Expected behaviour
Calling a constant contract method without specifying 'from' address should either return an error or use some default address, such as '0x0'

#### Actual behaviour
The method executes with 'msg.sender' set to the first keystore's address in the node wallet, or '0x0' if no keystores are present.

#### Steps to reproduce the behaviour
Use 'eth_call' with no 'from' address specified, on a constant method.
e.g.
```
contract foo {
    function bar () constant returns (address) {
        return msg.sender;
    }
}
```

**Comment by karalabe** [comment]
Constant methods can't really change anything, so there's not much you can spoof. Am I perhaps missing something?

**Comment by brendan87** [comment]
It's true you can't change anything, and technically due to the visibility of the blockchain, there's no data that could be hidden from a user. Technically, I guess there's no real problem with it. I just thought it was odd that it would run code on behalf of another address. I'll close it anyway.
