### ISSUE TITLE
Windows Defender reporting trojan in Geth-Win64-20160606144531-1.4.6-0f036f6.zip

### ISSUE THREAD

**Issue by skiqh** [ethereum/go-ethereum#2860]
Windows Defender just reported that it found the trojan "**Win32/Rundas!plock**" in an older version of geth.exe on my system. Downloading the zip file containing that very version (1.4.6, url:  https://github.com/ethereum/go-ethereum/releases/download/v1.4.6/Geth-Win64-20160606144531-1.4.6-0f036f6.zip; sha-1: 906e489c8e0248efafc697b2080b250d7df5c706), Windows Defender makes the same report (deleting the file in the process, however). After wgetting the zip file into a temporary folder and manually pointing WD to its download directory, once again it reports having found a trojan. Also, I haven't checked any other download yet.

Since I could not readily find any checksum of the zip file in the releases section of github, I cannot confirm the file has not been altered during the download; so I'm putting this out there for someone else to confirm or refute this (hoping for the latter, in which case I expect this issue to be closed).

**Comment by karalabe** [comment]
Submitting the file to VirusTotal results in the following hits: https://www.virustotal.com/en/file/fa28fee8584d054694f58d4a00e7d72ffe303eadd821d7f46bbf31020bb3e1e6/analysis/1469454668/ , all of which are false positives detecting Go 1.6.2 https://github.com/golang/go/issues/16292 (seems it was used by some virus and the AVs became overzealous and banned the entire Go for it).

**Comment by skiqh** [comment]
Alright: after another update to WD's definition files, no hits are being reported anymore. Closing.
