### ISSUE TITLE
Getting error when using miner.start(1) command in the geth javascript console using UBUNTU 20.04.6 and Geth Version: 1.13.5

### ISSUE THREAD

**Issue by aizazahmaad** [ethereum/go-ethereum#28611]
I am trying to set up a private network on Ethereum. To start mining for coins the command:
> miner.start(1)
Error: Invalid number of input parameters to RPC method
        at web3.js:5026:9(11)
        at web3.js:5069:22(20)
        at send (web3.js:5093:39(11))
        at <eval>:1:12(3)
I am getting error. What might be the issue here?

**Comment by karalabe** [comment]
Don't pass a parameter. Originally it was meant as a way to control the CPU threads, but in a post-PoW world, there's no notion of threading or anything like that any more.

Also, you're using it on a private Clique network? For PoS chains, you don't need to start the miner any more either, it's controlled via the engine API through the consensus client.

**Comment by aizazahmaad** [comment]
yes, I am running it on my local Operating system. I guess I am following an old document, can you provide a reference to follow?

**Comment by aizazahmaad** [comment]
> Don't pass a parameter. Originally it was meant as a way to control the CPU threads, but in a post-PoW world, there's no notion of threading or anything like that any more.
> 
> Also, you're using it on a private Clique network? For PoS chains, you don't need to start the miner any more either, it's controlled via the engine API through the consensus client.

yes, I am running it on my local Operating system. I guess I am following an old document, can you provide a reference to follow?

**Comment by MariusVanDerWijden** [comment]
You can use `miner.start()` or follow our tutorial. Closing this for now
