### ISSUE TITLE
The internal transactions obtained by debug_traceTransaction are not detailed enough

### ISSUE THREAD

**Issue by a5868519** [ethereum/go-ethereum#28639]
debug.traceTransaction('0x55faa64c2bfd26f53d55b868fb06b60ae208e832353e2da7c058d84149ab904b', { tracer: 'callTracer', tracerConfig: { withLog: true } })
{
  calls: [{
      from: "0x8cdd488363de72635b55bb263cc4c29041e6aa1a",
      gas: "0x6b3ccd",
      gasUsed: "0xbb8",
      input: "0xf840aaffb72e632dba991e27ee598aa75c849a10ac904b65f38c40b84d6e3dd6000000000000000000000000000000000000000000000000000000000000001c74771964af5c8c769db2dfb3634f5932bc53a817903061f7bb359cdff6d709cc6878039e0e4a298ebcf96d7633500efdfb2589f534ba15c3fd75dc8cefdcedce",
      output: "0x000000000000000000000000abcc7736c42713cd40ae8c2915c3b3dcdef6b83d",
      to: "0x0000000000000000000000000000000000000001",
      type: "STATICCALL"
  }, {
      calls: [{...}],
      from: "0x8cdd488363de72635b55bb263cc4c29041e6aa1a",
      gas: "0x6aea39",
      gasUsed: "0x61f1c8",
      input: "0xd76fad23a36136b088122ed58d0a74f546c4aa5ff9d11fabd9fd9e0adaf156367ef0ae598cdd488363de72635b55bb263cc4c29041e6aa1aaa45c2f7fa98c580295e749e000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000006a0000000000000000000000000b411dd8040412b8a8b07acf217a54c97d0ee59cb0000000000000000000000007a250d5630b4cf539739df2c5dacb4c659f2488d000000000000000000000000663a5c229c09b049e36dcc11a9b0d4a8eb9db2140000000000000000000000008cdd488363de72635b55bb263cc4c29041e6aa1a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000003a000000000000000000000000000000000000000000000000000000000000005800000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f785065742e7465636820546f6b656e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000045850455400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000006fc23ac00000000000000000000000000000000000000000000000000000000059682f0000000000000000000000000000000000000000000000000000000000165a0bc000000000000000000000000000000000000000000000000000000000011e1a3000000000000000000000000000000000000000000000000000000000011e1a300000000000000000000000000000000000000000000000000000000000000001f00000000000000000000000000000000000000000000000000000000bbf81e00000000000000000000000000b411dd8040412b8a8b07acf217a54c97d0ee59cb000000000000000000000000b411dd8040412b8a8b07acf217a54c97d0ee59cb000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000005dc00000000000000000000000000000000000000000000000000000000000005dc000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000960000000000000000000000000000000000000000000000000000000000000096000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000c38b26f66de36be2307c199b22bf2fd486763c55000000000000000000000000de3ff2a50bd1ba1bd6a608ea0138946dddf595bc0000000000000000000000000000000000000000000000000000000000000032000000000000000000000000000000000000000000000000000000000000003200000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      output: "0x0000000000000000000000004856dec69cd5d1b7f29de1a957038cf0b0876bfc",
      to: "0xa5f1144a270f532792b3525fc836e5d06ef0cbb8",
      type: "CALL",
      value: "0x0"
  }, {
      calls: [{...}, {...}, {...}, {...}],
      from: "0x8cdd488363de72635b55bb263cc4c29041e6aa1a",
      gas: "0xa6306",
      gasUsed: "0xa3146",
      input: "0x93bf5705000000000000000000000000000000000000000000000000016345785d8a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      logs: [{...}, {...}, {...}],
      to: "0x4856dec69cd5d1b7f29de1a957038cf0b0876bfc",
      type: "CALL",
      value: "0xf43fc2c04ee0000"
  }],
  from: "0xb411dd8040412b8a8b07acf217a54c97d0ee59cb",
  gas: "0x6d8a89",
  gasUsed: "0x6bfaed",
  input: "0x6e3fa5d100000000000000000000000000000000000000000000000000000000000000c08cdd488363de72635b55bb263cc4c29041e6aa1aaa45c2f7fa98c580295e749e00000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000720000000000000000000000000000000000000000000000000016345785d8a000000000000000000000000000000000000000000000000000002c68af0bb140000000000000000000000000000000000000000000000000000000000000000002430313863333530362d623338382d623162352d303066362d62346139323563666433663600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000004e00000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f785065742e7465636820546f6b656e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000045850455400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000006fc23ac00000000000000000000000000000000000000000000000000000000059682f0000000000000000000000000000000000000000000000000000000000165a0bc000000000000000000000000000000000000000000000000000000000011e1a3000000000000000000000000000000000000000000000000000000000011e1a300000000000000000000000000000000000000000000000000000000000000001f00000000000000000000000000000000000000000000000000000000bbf81e00000000000000000000000000b411dd8040412b8a8b07acf217a54c97d0ee59cb000000000000000000000000b411dd8040412b8a8b07acf217a54c97d0ee59cb000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000005dc00000000000000000000000000000000000000000000000000000000000005dc000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000960000000000000000000000000000000000000000000000000000000000000096000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000c38b26f66de36be2307c199b22bf2fd486763c55000000000000000000000000de3ff2a50bd1ba1bd6a608ea0138946dddf595bc0000000000000000000000000000000000000000000000000000000000000032000000000000000000000000000000000000000000000000000000000000003200000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000003e80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000656dd5fba349e78f7d0261fdb37b3233a1e8ba8d9a2919560a5711abb4e0f28c6fa817f70000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000004174771964af5c8c769db2dfb3634f5932bc53a817903061f7bb359cdff6d709cc6878039e0e4a298ebcf96d7633500efdfb2589f534ba15c3fd75dc8cefdcedce1c00000000000000000000000000000000000000000000000000000000000000",
  logs: [{
      address: "0x8cdd488363de72635b55bb263cc4c29041e6aa1a",
      data: "0x00000000000000000000000000000000000000000000000000000000000000c00000000000000000000000004856dec69cd5d1b7f29de1a957038cf0b0876bfc00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000002430313863333530362d623338382d623162352d303066362d62346139323563666433663600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f785065742e7465636820546f6b656e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004585045540000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006a0000000000000000000000000b411dd8040412b8a8b07acf217a54c97d0ee59cb0000000000000000000000007a250d5630b4cf539739df2c5dacb4c659f2488d000000000000000000000000663a5c229c09b049e36dcc11a9b0d4a8eb9db2140000000000000000000000008cdd488363de72635b55bb263cc4c29041e6aa1a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000003a000000000000000000000000000000000000000000000000000000000000005800000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f785065742e7465636820546f6b656e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000045850455400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000006fc23ac00000000000000000000000000000000000000000000000000000000059682f0000000000000000000000000000000000000000000000000000000000165a0bc000000000000000000000000000000000000000000000000000000000011e1a3000000000000000000000000000000000000000000000000000000000011e1a300000000000000000000000000000000000000000000000000000000000000001f00000000000000000000000000000000000000000000000000000000bbf81e00000000000000000000000000b411dd8040412b8a8b07acf217a54c97d0ee59cb000000000000000000000000b411dd8040412b8a8b07acf217a54c97d0ee59cb000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000005dc00000000000000000000000000000000000000000000000000000000000005dc000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000960000000000000000000000000000000000000000000000000000000000000096000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000c38b26f66de36be2307c199b22bf2fd486763c55000000000000000000000000de3ff2a50bd1ba1bd6a608ea0138946dddf595bc0000000000000000000000000000000000000000000000000000000000000032000000000000000000000000000000000000000000000000000000000000003200000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      position: "0x3",
      topics: ["0xf65d3a11fa2b7663a8d9ddb6a63494bf4b09240815636a0332849a3179a000c9", "0x000000000000000000000000b411dd8040412b8a8b07acf217a54c97d0ee59cb"]
  }],
  output: "0x0000000000000000000000004856dec69cd5d1b7f29de1a957038cf0b0876bfc",
  to: "0x8cdd488363de72635b55bb263cc4c29041e6aa1a",
  type: "CALL",
  value: "0x120a871cc0020000"
[1.txt](https://github.com/ethereum/go-ethereum/files/13548407/1.txt)

**Comment by jwasinger** [comment]
What missing information do you want?

**Comment by a5868519** [comment]
I need detailed insider trading information, like parity trace.



---Original---
From: ***@***.***&gt;
Date: Tue, Dec 5, 2023 02:30 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ethereum/go-ethereum] The internal transactions obtained bydebug_traceTransaction are not detailed enough (Issue #28639)




 
What missing information do you want?

**Comment by jwasinger** [comment]
the `flatCallTracer` implements parity-style call tracing.

**Comment by holiman** [comment]
If you want to file a proper ticket, then make sure to use the space to describe what it is you find lacking, and detail what you would want more, in some detail.
