### ISSUE TITLE
tracing: investigate indexing

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#28644]
This is a satellite issue with #28643. If we were to store live traces within Geth, then do we want to enable some form of querying of the data? The quick answer is why not, it would be fun to be able to serve queries like "retrieve all ether receipt transactions", but it can get very complex very quick:

- Indexing inbound transactions is kind of simple with the call traces (omitting the implementation details for now), but most of the DeFi stuff uses WETH, not ETH directly. So it might not be that interesting in itself.
- Indexing ERC20 opens a huge can of worms, where the DApp layer stuff creeps into the protocol layer code.
- Even if we were to make an ERC20 indexer, then why not make an NFT indexer, etc; the list keeps on growing.

At the end of the day, Geth *must* be precise. The more DApp layer stuff we try to cover, the more ambiguity we introduce (what happens with half-baked implementations of ERC20, what happens with malicious contracts, etc). It feels to *me* that we should not try to compete with explorers and similar tools. We should give them a way to access the data, but now start to do their job.

**Comment by hsyodyssey** [comment]
Thanks, team; this would be super helpful in many ways. Our current method for those fine-grained data queries is to export all Geth data to a relational database (PostgreSQL so far). It would be wonderful to have a geth-native way to query data at a fine-grained level👍.
