### ISSUE TITLE
Should there be an option to include golang debug metrics?

### ISSUE THREAD

**Issue by Aracki** [ethereum/go-ethereum#28647]
From packages like `runtime, runtime/debug` we could expose go default metrics like:
* `go_info`
* `go_threads`
* `go_goroutines`
* `go_gc_duration_seconds`

Should there be an option to enable this via geth flag?

I see some references in [go-ethereum/metrics/debug.go](https://github.com/ethereum/go-ethereum/blob/master/metrics/debug.go) file, but those are not exposed via the port we use for all other metrics.

**Comment by sifisKoen** [comment]
Hello, :smile: 
Do you think that this issue can be solved by a new comer in the topic? Of Geth and blockchain? But I am willing to learn and try to help with this issue

**Comment by holiman** [comment]
These are already exposed, e.g https://github.com/ethereum/go-ethereum/blob/master/metrics/metrics.go#L156

**Comment by fjl** [comment]
If you want all Go runtime debug information, it be exposed with `geth --pprof`. It starts the standard pprof server.

Goroutine count, threads, etc. are exposed as metrics for Prometheus/InfluxDB.
