### ISSUE TITLE
flag provided but not defined: -genkey

### ISSUE THREAD

**Issue by 0xmoncif213** [ethereum/go-ethereum#28651]
#### System information

Geth version: `geth version 1.13.5-unstable-55b483d8-20231206`
OS & Version: Linux 5.15.138-1-MANJARO x86_64

#### Expected behaviour
I'm running the command `bootnode -genkey boot.key`. The command must generate a key for the bootnode inside the working directory.

#### Actual behaviour

`flag provided but not defined: -genkey`

#### Steps to reproduce the behaviour

`bootnode -genkey boot.key`

**Comment by holiman** [comment]
Could you show the full thing? as in, copy-paste everything from the prompt to the error-message?

**Comment by holiman** [comment]
So, you didn't paste everything "from the prompt", but anyway, from what you did paste, I would hazard to guess that you do not invoke the `bootnode` binary, but rather the `geth` binary.

**Comment by holiman** [comment]
So, https://geth.ethereum.org/downloads does not yet list the build of today, `55b483d8-20231206`, because they're pushed nightly. So where did you download this from? Or did you build yourself?

**Comment by 0xmoncif213** [comment]
I clone it from Aur (Archlinux user repository) https://aur.archlinux.org/geth-git.git.
Then build it using `makepkg -si`

**Comment by fjl** [comment]
There's a bug in the PKGBUILD script, it installs the geth binary under a several names. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=geth-git#n47

This line should copy build/bin/bootnode instead. 

@5chdn can you fix it please

**Comment by 0xmoncif213** [comment]
Thank you for your assistance @fjl 
 and @holiman .
