### ISSUE TITLE
In line 93 of the abi.getArguments method in the abi.go file, method.Outputs cannot obtain data.

### ISSUE THREAD

**Issue by walker061** [ethereum/go-ethereum#28672]
#### System information

Geth version: `1.13.5`
CL client & version: No
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
```
map[amount:460129971903447085424 recipient:0x4982085C9e2F89F2eCb8131Eca71aFAD896e89CB]
```

#### Actual behaviour

Error:

```
abi: improperly encoded boolean value
```

#### Steps to reproduce the behaviour
```
func (abi ABI) getArguments(name string, data []byte) (Arguments, error) {
	// since there can't be naming collisions with contracts and events,
	// we need to decide whether we're calling a method or an event
	var args Arguments
	if method, ok := abi.Methods[name]; ok {
		if len(data)%32 != 0 {
			return nil, fmt.Errorf("abi: improperly formatted output: %q - Bytes: %+v", data, data)
		}
		args = method.Outputs
	}
	if event, ok := abi.Events[name]; ok {
		args = event.Inputs
	}
	if args == nil {
		return nil, fmt.Errorf("abi: could not locate named method or event: %s", name)
	}
	return args, nil
}
```
Modified: `method.Outputs` ->`method.Inputs`
```
func (abi ABI) getArguments(name string, data []byte) (Arguments, error) {
	// since there can't be naming collisions with contracts and events,
	// we need to decide whether we're calling a method or an event
	var args Arguments
	if method, ok := abi.Methods[name]; ok {
		if len(data)%32 != 0 {
			return nil, fmt.Errorf("abi: improperly formatted output: %q - Bytes: %+v", data, data)
		}
		args = method.Inputs
	}
	if event, ok := abi.Events[name]; ok {
		args = event.Inputs
	}
	if args == nil {
		return nil, fmt.Errorf("abi: could not locate named method or event: %s", name)
	}
	return args, nil
}
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

Sorry, my English is not good. I can only provide you with so much information for the time being. After I tried to modify it, I can get the data normally.

**Comment by Cognacy** [comment]
@tdy6284 Are you able to fix this issue?

**Comment by MariusVanDerWijden** [comment]
The fix you're proposing does not fix the issue. This method tries to decode the `output` of a method. You're replacing it to use the `input`. Do you have an example of the abi that you are using?

**Comment by holiman** [comment]
After looking into this, it does look like this is an error. `args = method.Outputs` doesn't make sense to me, it should be `args = method.Inputs` -- we're trying to match the provided data to the method arguments (inputs) here. 

OTOH, we do have a test `TestUnpackMethodIntoMap` which starts failing/panicing if I change it. So it does appear that it's intentionally the way it is. I'll mark this for triage, to hear what others say.
