### ISSUE TITLE
make geth make (e=2): The system cannot find the file specified.

### ISSUE THREAD

**Issue by heat9070** [ethereum/go-ethereum#28680]
I tried to run make geth I get back this error

```
env GO111MODULE=on go run build/ci.go install ./cmd/geth
process_begin: CreateProcess(NULL, env GO111MODULE=on go run build/ci.go install ./cmd/geth, ...) 
failed.
**make (e=2): The system cannot find the file specified.
make: *** [geth] Error 2**
```

Although when I run this command, it runs fine
```
go run build/ci.go install ./cmd/geth
```

My installed go version
go version go1.21.5 windows/amd64

The idea that I need to build geth on branch `release/1.10`

Any ideas?

**Comment by ArpitKRS** [comment]
Please /assign this issue to me and let's discuss over it.

**Comment by holiman** [comment]
The branch `release/1.10` is roughly a year old. We don't usually support old code, and seeing as you already _can_ compile it, I don't think it's worth having an open ticket investigating exactly why the `make` command does not seem to work for you.

ps. `make geth` does work for me though, on `go version go1.21.1 linux/amd64` and `release/1.10`.

**Comment by heat9070** [comment]
Nothing useful here

**Comment by heat9070** [comment]
Wasted my time writing this, I don't recommend using this channel

**Comment by holiman** [comment]
Well.

You posted about a problem, to which you already had a work-around.  
The problem seems to affect only a one-year-old release.
The problem did not appear, when I tried to repro it using the steps you had posted. 

How much time would you expect me to spend on pursuing this?

**Comment by heat9070** [comment]
make geth is not working, this is a bug on the platform, you did provide nothing, for instance change the branch to some other branch (I need a branch with pow enabled), another answer would be -for instance- we have faced this make geth issue before on windows, you would refer to this ticket.

Nothing provided, nothing
