### ISSUE TITLE
Allow to customize MIN_BLOB_GASPRICE as runtime config

### ISSUE THREAD

**Issue by dapplion** [ethereum/go-ethereum#28688]
# Rationale

it would be very useful for testing to be able to set `MIN_BLOB_GASPRICE` in a per-network value, instead of hardcoded to 1 to simulate higher gas regimes without the need of +1000 of blocks.

# Implementation

Read MIN_BLOB_GASPRICE from genesis file else default to 1

CC: @MariusVanDerWijden

**Comment by karalabe** [comment]
We don't want to add network specific params to the genesis. We always rejected those ideas.
