### ISSUE TITLE
switching from 1.11.5 to 1.13.5 break client.SendTransaction to a smart contract as it send ETH

### ISSUE THREAD

**Issue by mangronewmark** [ethereum/go-ethereum#28684]
We have a code that use the client.SendTransaction to interact with a smart contract.

with 1.11.5 everything works, switching to 1.13.5 we receive an error from the smart contract as if we sent it ETH.
the error is catched by the receive() function implemented in the smart contract (that doesn not accept ETH).

switching back to 1.11.5 with the same code there is no such error.

the error appear with both a view function or a write function or even accessing a public variable.

What has changed between 1.11.5 and 1.13.5 that could lead to such break? some obscure default?

**Comment by holiman** [comment]
Please provide more details about specifically how you use it

**Comment by mangronewmark** [comment]
The test is using hardhat but the same error has been proven on polygon and ethereum testnet

we call 
`ethclient.Client.CallContract(context.Background() , msg, nil)`

where msg is 


```
msg := ethereum.CallMsg{
		From:     0x0000000000000000000000000000000000000000,
		To:        0xB5AE3e2883934457cb593793f034b401867e1372,
		Gas:       0x0,
		GasPrice:  0,
		GasFeeCap: 0,
		GasTipCap: 0,
		Value:     0,
		Data:      []uint8{0x72, 0x84, 0xe4, 0x16},
	}
```

printing msg in the log results in this

`ethereum.CallMsg{From:0x0000000000000000000000000000000000000000, To:0xB5AE3e2883934457cb593793f034b401867e1372, Gas:0x0, GasPrice:0, GasFeeCap:0, GasTipCap:0, Value:0, Data:[]uint8{0x72, 0x84, 0xe4, 0x16}, AccessList:types.AccessList(nil)}`

the response is

>  Error: VM Exception while processing transaction: revert This contract does not accept token"

(that is the message in the solidity contract throw by


    receive() external payable {
        revert("This contract does not accept token");
    }



just switching in go.mod 
github.com/ethereum/go-ethereum v1.13.5
with
github.com/ethereum/go-ethereum v1.11.5

and it worrks

**Comment by mangronewmark** [comment]
in hardhat the log say 
```
eth_call
  Contract call:           <UnrecognizedContract>
  From:                    0x0000000000000000000000000000000000000000
  To:                      0xb5ae3e2883934457cb593793f034b401867e1372

  Error: VM Exception while processing transaction: revert This contract does not accept token
      at <UnrecognizedContract>.<unknown> (0xb5ae3e2883934457cb593793f034b401867e1372)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at HardhatNode.runCall (/usr/src/app/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:420:20)
      at EthModule._callAction (/usr/src/app/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:345:9)
      at HardhatNetworkProvider._sendWithLogging (/usr/src/app/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:119:22)
      at HardhatNetworkProvider.request (/usr/src/app/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:99:18)
      at JsonRpcHandler._handleRequest (/usr/src/app/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
```

**Comment by mangronewmark** [comment]
We tried also putting the from with the signing address and the result is the same (the from is not required on a view/pure function). 
just as a complete test

ime="2023-12-15T13:43:44Z" level=info msg="[tm_postgresql.go][NewTmRepo]#L117 Connecting to Postgres\n" context=default logtype=Info timestamp=1702647824
DATA ethereum.CallMsg{From:0x959FD7Ef9089B7142B6B908Dc3A8af7Aa8ff0FA1, To:0xB5AE3e2883934457cb593793f034b401867e1372, Gas:0x0, GasPrice:0, GasFeeCap:0, GasTipCap:0, Value:0, Data:[]uint8{0x72, 0x84, 0xe4, 0x16}, AccessList:types.AccessList(nil)}

**Comment by holiman** [comment]
`Data:[]uint8{0x72, 0x84, 0xe4, 0x16}` == `0x7284e416` == [`description()`](https://www.4byte.directory/signatures/?bytes4_signature=0x7284e416) . Quirky. 

Anyyway, I suspect that the change is that geth perhaps parses solidity error messages better, which we did not earlier. Have a vague recollection about that. If so, it's just that we're now showing it to you, instead of just failing. Not sure.

**Comment by mangronewmark** [comment]
description is the name of the public variable.
the weird thing is that with 1.11.5 i get the actual result, so the blockchain reply the correct value.
with this instead it think some ETH was sent as value portion even if 0 was included.

my only guess is that before value was not sent at all if it was 0, now is sent as 0 and for some reason the hardhat node (and polygon and eth nodes) believe 0 is a value and pass it to the smart contract triggering the receive function. is the only explanation i can think of

**Comment by holiman** [comment]
Is it the backend you are switching between `1.11.5`<->`1.13.5` or is it the client implementation?

**Comment by mangronewmark** [comment]
just the client, i don't run a geth node myself, i'm using infura to connect to public blockchain and hardhat for testing gluwa/hardhat-dev:latest docker

**Comment by mangronewmark** [comment]
I just tested 1.12.2 and it works
then 1.13.0 .1 .2 .3 .4 .5 all broken

**Comment by mangronewmark** [comment]
looking at the diff of 1.12.2 and 1.13.0

```

func toCallArg(msg ethereum.CallMsg) interface{} {
	arg := map[string]interface{}{
		"from": msg.From,
		"to":   msg.To,
	}
	if len(msg.Data) > 0 {
		arg["data"] = hexutil.Bytes(msg.Data)
		arg["input"] = hexutil.Bytes(msg.Data)
```

seems the only change that could affect the client, Value is not actually changed, but could be that it change in some way the transaction padding?

**Comment by mangronewmark** [comment]
i tested back, and the problem is not happening with mumbai polygon or eth testnet, so it's related to hardhat only.

the version we are using is 2 years old. so we will update that, still, it's a weird behaviour

**Comment by mangronewmark** [comment]
confirmed, with new hardhat it works
