### ISSUE TITLE
Improved wiki code for checkAllBalances()

### ISSUE THREAD

**Issue by lungj** [ethereum/go-ethereum#2869]
This is a pull request for the wiki since I can't put a pull request for the wiki using the regular "Pull requests" tab. In my fork of the wiki at https://github.com/lungj/go-ethereum-wiki, I've made some changes to the `checkAllBalances()` code posted to https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts:

 * 11ace24 -- Improves code style for legibility.
 * d0adcb4 -- Fixes formatting of output when more than 10 accounts are displayed.
 * 3a91afa -- Shows the total balance for all accounts.

**Comment by bas-vk** [comment]
Thx, wiki page updated.
