### ISSUE TITLE
rlp encoding of a struct yields an empty encoded list (0xc0)

### ISSUE THREAD

**Issue by Retamogordo** [ethereum/go-ethereum#28698]
Hi,
I'm trying to wrap my head around the RLP encoder.
This code yields 0xc0:
```go
type Foo struct {
	nonce uint64;
}
// snip
foo := Foo { 
	nonce: uint64(79), 
}
rlp, _ := rlp.EncodeToBytes(foo)
fmt.Printf("%X\n", rlp)
```
If I add more fields to the struct, the result is the same.
The package documentation states: "Struct values are encoded as an RLP list of all their encoded public fields."
Apparently I'm missing something very basic here.
What am I doing wrong?

**Comment by holiman** [comment]
> something very basic here.

Yes, that something is the fact that fields in all lower-case, like `nonce`, are private. And thus an encoder/decoder cannot "see" the fields. They're basically non-existant, as far as the encoder knows. 

You need to name it `Nonce` instead.
