### ISSUE TITLE
The response of calling eth_subscribe method at a Geth instance is missing withdrawals and size fields in the result

### ISSUE THREAD

**Issue by aditjosh** [ethereum/go-ethereum#28700]
The **withdrawals** field was added in EIP-4895: https://eips.ethereum.org/EIPS/eip-4895#new-field-in-the-execution-payload-withdrawals. However, the response we get from a websocket call (to a Geth snap instance) for the "eth_subscribe" method, does not contain the withdrawals field in the result.

**result.size** is another field that used to be present but is now missing.

#### System information

Geth version: v1.13.5
CL client & version: lighthouse v4.5.0-modern
OS & Version: Ubuntu 22.04.3 LTS (Release 22.04)
Commit hash : (if `develop`)

#### Expected behaviour
Sample response:

> 

    "jsonrpc": "2.0",
    "method": "eth_subscription",
    "params": {
        "result": {
            "baseFeePerGas": "xxxxx",
            "difficulty": "0x0",
            "extraData": "xxxxx",
            "gasLimit": "xxxxx",
            "gasUsed": "xxxxx",
            "hash": "xxxxx",
            "logsBloom": "xxxxx",
            "miner": "xxxxx",
            "mixHash": "xxxxx",
            "nonce": "xxxxx",
            "number": "xxxxx",
            "parentHash": "xxxxx",
            "receiptsRoot": "xxxxx",
            "sha3Uncles": "xxxxx",
            "size": "xxxxx",
            "stateRoot": "0xxxxxx",
            "timestamp": "xxxxx",
            "transactionsRoot": "xxxxx",
            "withdrawals": [
                {
                    "index": "0xxxxxx",
                    "validatorIndex": "0xxxxxx",
                    "address": "0xxxxxx",
                    "amount": "0xxxxxx"
                },
                {
                    "index": "0xxxxxx",
                    "validatorIndex": "0xxxxxx",
                    "address": "0xxxxxx",
                    "amount": "0xxxxxx"
                },
                {
                    "index": "0xxxxxx",
                    "validatorIndex": "0xxxxxx",
                    "address": "0xxxxxx",
                    "amount": "0xxxxxx"
                }
                ],
            "withdrawalsRoot": "0xxxxxxxx"
        },
        "subscription": "0xxxxxx"
    }

#### Actual behaviour
**result.size** and **result.withdrawals** fields are not present in the response.

> 
   "jsonrpc":"2.0",
   "method":"eth_subscription",
   "params":{
      "subscription":"0xxxxxx",
      "result": {
         "parentHash":"0xxxxxx",
          "sha3Uncles":"0xxxxxx",
          "miner":"0xxxxxx",
          "stateRoot":"0xxxxxx",
          "transactionsRoot":"0xxxxxx",
          "receiptsRoot":"0xxxxxx",
          "logsBloom":"0xxxxxx",
          "difficulty":"0xxxxxx",
          "number":"0xxxxxx",
          "gasLimit":"0xxxxxx",
          "gasUsed":"00xxxxxx",
          "timestamp":"0xxxxxx",
          "extraData":"0xxxxxx",
          "mixHash":"0xxxxxx",
          "nonce":"0x0000000000000000",
          "baseFeePerGas":"0xxxxxx",
          "withdrawalsRoot":"0xxxxxx",
          "blobGasUsed":0xxxxxx,
          "excessBlobGas":0xxxxxx,
          "parentBeaconBlockRoot":0xxxxxx,
          "hash":"0xxxxxx"
          }
   }
  

#### Steps to reproduce the behaviour
Send the following websocket call to Geth execution client (Snap client):

`wscat -c wss://<geth_host>:<port> -w 30 -x '{"jsonrpc":"2.0","id": 1, "method": "eth_subscribe", "params": ["newHeads"]}' | tee -a newHeads.jsonl`

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by MariusVanDerWijden** [comment]
Withdrawals are not part of the header, they are part of the block. Why do you expect them to be returned via eth_subscribe?

**Comment by rjl493456442** [comment]
As @MariusVanDerWijden said, `withdrawal` is not part of the header which shouldn't be included in the response. 

Wrt the `result.size` you said, are you sure Geth did return it? It's not part of the header definition in Geth.

**Comment by aditjosh** [comment]
Apologies, my mistake for looking at the response of the incorrect method. I confirm that both size and withdrawals are returned in eth_getBlockByHash. I will close this issue.

**Comment by aditjosh** [comment]
Closing as this is not a bug.
