### ISSUE TITLE
When querying Parity VM Trace Transaction, it was found that the gasused value of the first transaction returned by the interface was inconsistent with that of the browser.

### ISSUE THREAD

**Issue by hanzhenlong1314** [ethereum/go-ethereum#28714]
Browser results：https://cn.etherscan.com/vmtrace?txhash=0xbba36a1c9b214f1a661c94d2b14bdf40f2d69c21ef0719fd2c394190aa9df6b7&type=parity
![image](https://github.com/ethereum/go-ethereum/assets/25896081/c38a03d1-e5dc-436e-9c0d-02383e8a06b0)
The result of the interface：curl --location 'http://127.0.0.1:8803' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "method": "debug_traceTransaction",
    "params": [
        "0xbba36a1c9b214f1a661c94d2b14bdf40f2d69c21ef0719fd2c394190aa9df6b7",
        {
            "tracer": "flatCallTracer",
            "limit":2
        }
    ],
    "id": 1
}'
**the result :   The gasused of the first transaction is   "gasUsed":"0x5b9e7" ==375271,**
{
    "jsonrpc":"2.0",
    "id":1,
    "result":[
        {
            "action":{
                "callType":"call",
                "from":"0x9dd2b9983e3f9cfdc302478d8554460071d8c1ea",
                "gas":"0x7ec06",
                "input":"0x3593564c000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000006583dcf300000000000000000000000000000000000000000000000000000000000000030a080c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000160000000000000000000000000d9adfb67381d392c6e9671f64cdd9014bfcd74f2000000000000000000000000ffffffffffffffffffffffffffffffffffffffff0000000000000000000000000000000000000000000000000000000065ab67a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003fc91a3afd70395cd496c647d5a6cc9d4b2b7fad000000000000000000000000000000000000000000000000000000006583e1a800000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000041cf407ad71cdc15d398d748888fd9ec0264a7dbfce66a2a1aa2ea04dab090ebc0711b0284442932ecaae327f39a949b02ffae819e909cb8c83480f2a021e0813d1b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000053805f4bf1b1d9a901400000000000000000000000000000000000000000000000001359457918be49900000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000d9adfb67381d392c6e9671f64cdd9014bfcd74f2000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000012c4e4d62f4f8cb",
                "to":"0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad",
                "value":"0x0"
            },
            "blockHash":"0x2181089e0f59bf21ba0517aa7ceeab474d93c9924e96fd675eb737173d96f4f0",
            "blockNumber":18832456,
            "result":{
                "gasUsed":"0x5b9e7",
                "output":"0x"
            },
            "subtraces":10,
            "traceAddress":[

            ],
            "transactionHash":"0xbba36a1c9b214f1a661c94d2b14bdf40f2d69c21ef0719fd2c394190aa9df6b7",
            "transactionPosition":119,
            "type":"call"
        }

,
        {
            "action":{
                "callType":"call",
                "from":"0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad",
                "gas":"0x7a5de",
                "input":"0x2b67b5700000000000000000000000009dd2b9983e3f9cfdc302478d8554460071d8c1ea000000000000000000000000d9adfb67381d392c6e9671f64cdd9014bfcd74f2000000000000000000000000ffffffffffffffffffffffffffffffffffffffff0000000000000000000000000000000000000000000000000000000065ab67a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003fc91a3afd70395cd496c647d5a6cc9d4b2b7fad000000000000000000000000000000000000000000000000000000006583e1a800000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000041cf407ad71cdc15d398d748888fd9ec0264a7dbfce66a2a1aa2ea04dab090ebc0711b0284442932ecaae327f39a949b02ffae819e909cb8c83480f2a021e0813d1b00000000000000000000000000000000000000000000000000000000000000",
                "to":"0x000000000022d473030f116ddee9f6b43ac78ba3",
                "value":"0x0"
            },
            "blockHash":"0x2181089e0f59bf21ba0517aa7ceeab474d93c9924e96fd675eb737173d96f4f0",
            "blockNumber":18832456,
            "result":{
                "gasUsed":"0x7842",
                "output":"0x"
            },
            "subtraces":0,
            "traceAddress":[
                0
            ],
            "transactionHash":"0xbba36a1c9b214f1a661c94d2b14bdf40f2d69c21ef0719fd2c394190aa9df6b7",
            "transactionPosition":119,
            "type":"call"
        }
    ]
}

**Comment by jsvisa** [comment]
The result of etherscan are from Party's, which is not rigorous, while in geth, we set the root trace's gasUsed to tx.gasUsed.

**Comment by hanzhenlong1314** [comment]
****

> The result of etherscan are from Party's, which is not rigorous, while in geth, we set the root trace's gasUsed to tx.gasUsed.

This means that there is no problem with querying this interface, right? @jsvisa

**Comment by jsvisa** [comment]
yes

**Comment by hanzhenlong1314** [comment]
> yes

got it,thanks
