### ISSUE TITLE
what is java equvavelnt to go-ethereum ABI 

### ISSUE THREAD

**Issue by begemot63** [ethereum/go-ethereum#28723]
Our application is written using go-ethereum . We rely on few packages  from https://github.com/ethereum/go-ethereum/blob/master/accounts/abi:
 https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/method.go
 https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/abi.go
 https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/argument.go
....
 
 Now we are moving to java. What is a java package and classes which  would an equivalent  to these GoLang  go-ethereum implementation?

**Comment by rjl493456442** [comment]
Maybe [besu](https://github.com/hyperledger/besu) is a good candidate.

I will close the issue as it's not in the scope of go-ethereum.
