### ISSUE TITLE
how to implement abi.encode in golang?

### ISSUE THREAD

**Issue by sez256** [ethereum/go-ethereum#28729]
I have a question. I know abi.Pack function is similar to implement the below code but Pack function has no prefix to add `keccak256("delegate(address sender,string amount, string to)")`
```abi.encode( keccak256("delegate(address sender,string amount, string to)"), sender, amount, to )```

**Comment by fxfactorial** [comment]
what do you mean prefix

**Comment by rjl493456442** [comment]
You can use [abigen](https://github.com/ethereum/go-ethereum/tree/master/cmd/abigen) to automatically generate the golang bindings for you. There you have all the functionalities you need to interact with contract.

**Comment by sez256** [comment]
👍 , it's implemented, I got hash of the eip712 signed transaction and extracted transaction signer using cryto.Ecrecover, but the result is not the same.
```
pbBytes, err := crypto.Ecrecover(hash.Bytes(), signature)
	fmt.Println(string(pbBytes), err)
	pubKey, err := crypto.UnmarshalPubkey(pbBytes)

	if err != nil {
		fmt.Println("eip712 err", err)
		return false
	}

	// Derive the signer's address from the public key
	signerAddress := crypto.PubkeyToAddress(*pubKey)

	fmt.Println("signer addr:", signerAddress.Hex())
	fmt.Println("sender addr:", sender.Hex())
```
signer addr: 0xbdA44571019C8cf81Ff5e79413fD5994D493Ed88
sender addr: 0xE7692627006C90b5fc26Fc99Bac3b205b1B7036B
what is the reason?
https://github.com/apurbapokharel/EIP712Example/blob/master/contracts/SimpleStorage.sol#L15C8-L15C8
I tried to implement the below solidity function in golang, transaction has result is the same with the solidity hash result(tested).
But signer address is differ.
