### ISSUE TITLE
console: eth.filter does not trigger on Geth 1.5.0

### ISSUE THREAD

**Issue by coeniebeyers** [ethereum/go-ethereum#2872]
My version of geth:
$ geth version
Geth
Version: 1.5.0-unstable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go

The following does not work in the repl:
eth.filter("latest", function(err, block) {console.log("New Block!") });

Reverting to version 1.4.10-stable fixed the issue:
$ geth version
Geth
Version: 1.4.10-stable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go

**Comment by fjl** [comment]
I have seen this too. Investigating.
