### ISSUE TITLE
geth private network configure

### ISSUE THREAD

**Issue by KevinTMitnick** [ethereum/go-ethereum#28737]
Hello, I used geth (1.13.0 table) to set up a private network，and found that only the set cosinbase is not effective, and there is only one transaction in a block, which causes slow transaction packaging when I use scripts for batch transfers. How to solve this problem

**Comment by MariusVanDerWijden** [comment]
It's not easy to debug this without more information. You seem to be able to mine blocks, so somehow the coinbase should be set. I assume you are using clique. With clique you can not change the coinbase via `setEtherbase`, you can only change it if you change the signing key.

Regarding your second issue, not being able to mine multiple transactions in a block. Are you sending multiple transactions from the same account or different accounts? Do you have any log outputs for your batch sending? Are you setting the nonces correctly in your script?

**Comment by phpmac** [comment]
What's the latest situation? Can multiple nodes be synchronized?

**Comment by MariusVanDerWijden** [comment]
The latest geth master does not support Clique anymore. Will close this for now. Thanks for reporting!
