### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by joy4eg** [ethereum/go-ethereum#28740]
#### System information
Version v1.13.8

#### Expected behaviour
```golang
import (
    "errors"

    "github.com/ethereum/go-ethereum/core"
    "github.com/ethereum/go-ethereum/ethclient"
)

client, err := ethclient.DialContext(ctx, endpoint)
...
_, err := client.SendTransaction(...)
if errors.Is(err, core.ErrInsufficientFunds) {
    // Some logic goes here.
}
```

#### Actual behaviour
```golang
_, err := client.SendTransaction(...) // err = insufficient funds for gas * price + value: balance A, queued cost B, tx cost C, overshot D
if errors.Is(err, core.ErrInsufficientFunds) { // <--- always FALSE here.
    // Some logic goes here.
}
```

It looks like that RPC client returns errors from a node as-is. Just a string:
```golang
        // &rpc.jsonrpcMessage{Version:"2.0", ID:json.RawMessage{0x33}, Method:"", Params:json.RawMessage(nil), Error:(*rpc.jsonError)(0xc000940e70), Result:json.RawMessage(nil)} --> {"jsonrpc":"2.0","id":3,"error":{"code":-32000,"message":"insufficient funds for gas * price + value: balance A, queued cost B, tx cost C, overshot D"}}
	resp := batchresp[0]
	switch {
	case resp.Error != nil:
		return resp.Error // <--- Error message.
	case len(resp.Result) == 0:
		return ErrNoResult
	default:
		if result == nil {
			return nil
		}
		return json.Unmarshal(resp.Result, result)
	}
```
In that way, it's impossible to check the error code/message using pre-defined `core.ErrXXX` constants, which makes error handling painful and confusing.

**Comment by rjl493456442** [comment]
Ethclient is a SDK can interact with any ethereum client which implements the standard JSONRPC spec.

Checking error with error type is a very golang-specific thing, so we recommend you to handle the error by using error code and error message.

**Comment by joy4eg** [comment]
>Checking error with error type is a very golang-specific thing, so we recommend you to handle the error by using error code and error message.

Well, in that case, it would be nice to have a note about this behavior/approach somewhere in the documentation.

**Comment by fjl** [comment]
The underlying issue is that package core is not a stable API. It's basically an internal package that implements the Ethereum protocol. The exposed API surface of core is there for Geth to use, but we don't promise it will be stable.

Package ethclient IS a stable API for users to consume however. So I understand your frustration with navigating this mix of public and non-public functionality.

**Comment by fjl** [comment]
We are unfortunately not at a point where the errors from tx validation are forwarded to clients as JSON-RPC error codes. Work toward more error codes is ongoing.
