### ISSUE TITLE
--syncmode snap eth_getTransactionReceipt cannot obtain early TransactionReceipt

### ISSUE THREAD

**Issue by enet2006** [ethereum/go-ethereum#28746]
--syncmode snap eth_getTransactionReceipt cannot obtain early TransactionReceipt？

**Comment by rjl493456442** [comment]
Geth will only keep the transaction indexes for the latest `2350000` blocks, roughly 1 year time.

If you want to access some transactions/receipts at early days, please change the index setting and Geth will automatically re-generate the indexes for you. But please keep in mind that transaction indexes are non-trivial and will uses lots of storage space.


e.g. 
`--history.transactions 5000000`
