### ISSUE TITLE
How can I decode the data in eip712-signed transaction in golang?

### ISSUE THREAD

**Issue by sez256** [ethereum/go-ethereum#28742]
How can I send eip712-signed transaction in frontend and decode it in golang?
How can I decode the struct (that includes bool, string, string array, int array, struct...) in golang?

**Comment by fjl** [comment]
@holiman can answer this

**Comment by sez256** [comment]
Thanks. @holiman, how can I decode the struct in data field of eip712-signed transaction?
I know data field is consist of v, r, s, sender, struct.
how can I decode the struct that includes arrays and struct?

**Comment by holiman** [comment]
Use [`TypedData`](https://github.com/ethereum/go-ethereum/blob/master/signer/core/apitypes/types.go#L199)

**Comment by sez256** [comment]
> Use [`TypedData`](https://github.com/ethereum/go-ethereum/blob/master/signer/core/apitypes/types.go#L199)

could you explain more details?

**Comment by holiman** [comment]
Please explain to me what it is that you want to do. I don't understand. For example: Do you want to programatically take a piece of hexdata input, where the input represents signed eip-712 data? 

There's no such thing as a eip-712 transaction. Eip 712 is a format for signed data, which is a _payload_ of a transaction.

**Comment by sez256** [comment]
how can I decode the eip712 formatted tx.data? how can I get the function name, params from tx.data?

**Comment by holiman** [comment]
Most likely you cannot. A signature is just a small thing, signing a hash which is just a hash of the entire struct that represents the eip-712 data. So if you only have that, you are out of luck. 

I really can't answer any better unless you provide more info about what data you have.

**Comment by sez256** [comment]
make sense. thanks.
