### ISSUE TITLE
geth does not start after upgrading from 1.3.5. to 1.4.10 

### ISSUE THREAD

**Issue by SethVgr** [ethereum/go-ethereum#2875]
## Checklist
- [done ] built geth 1.4.10
- [done ] installed it over previous version (1.3.5.) (`sudo cp geth /usr/bin/geth`)

## System/environment

- OS: debian 8.3 Jessie x64, kernel version 3.16.0-4-amd64, virtual machine, running on VirtualBox, host machine Win7 x64, NAT network settings used

## Expected behaviour
**geth** should be able to launch given the following command line arguments:

`geth --datadir "./datadir" --networkid 100 --rpcapi eth,web3,personal --rpc --maxpeers 0 init "genesis.json" --etherbase "0x0000000000000000000000000000000000000000" --mine --minerthreads 3`

## Observed behaviour
**geth** throws an error:

```
Incorrect Usage.

init [arguments...]

The init command initialises a new genesis block and definition for the network.
This is a destructive action and changes the network in which you will be
participating.


flag provided but not defined: -etherbase
```

Also tried launching **geth** with the init command and its arguments on the last position:

`geth --datadir "./datadir" --etherbase "0x0000000000000000000000000000000000000000" --mine --minerthreads 3 --networkid 100 --rpcapi eth,web3,personal --rpc --maxpeers 0 init "genesis.json" `

 which outputs the following:

```
I0727 12:29:08.531439 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to single_bootstrap_node_geth/chaindata
I0727 12:29:08.663983 core/genesis.go:92] Genesis block already in chain. Writing canonical number
I0727 12:29:08.665008 cmd/geth/main.go:299] successfully wrote genesis block and/or chain rule set: 2279317df6aed704d8d46771ed06fbe4b7a935f7005d341b091b7957bc374def
```

and **geth** does not start mining.

**Comment by bas-vk** [comment]
I don't know why the previous version that you used worked with this set of flags. Probably because the init subcommand was not fully implemented. 1.3.5 is really old. In geth 1.4.x your command line flags are odd.

The [init](https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options#init) subcommand is used to create a chain with a custom genesis block and is usually not used with flags apart from the datadir flag.

If you just want to start geth (on the mainnet) and let it mine drop the init subcommand. Your command would look like (replace `--etherbase "0x..."` with something that you own):

```
geth --datadir "./datadir" --etherbase "0x0000000000000000000000000000000000000000" --mine --minerthreads 3 --rpcapi eth,web3,personal --rpc
```
You might want to look at the `--support-dao-fork` and `--oppose-dao-fork` flags.

If you want to create a private network. Follow the instructions on the wiki for the init subcommand and after you created the custom chain start geth with a datadir pointing to the custom chain datadir.

**Comment by SethVgr** [comment]
Thanks. I did manage to get it running on a private test net by running:

`geth --datadir "data_dir" init "genesis.json"`

and then launching with:

`geth --datadir "data_dir" --mine --minerthreads 3 --networkid 13 --rpcapi eth,web3,personal --rpc --maxpeers 0 `

 **geth** starts mining:

```
I0728 04:00:12.289151 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to data_dir/chaindata
I0728 04:00:12.397333 ethdb/database.go:169] closed data_dir/chaindata
I0728 04:00:12.414075 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to data_dir/chaindata
I0728 04:00:12.493681 eth/backend.go:621] upgrading db log bloom bins
I0728 04:00:12.494120 eth/backend.go:629] upgrade completed in 451.405µs
I0728 04:00:12.494465 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to data_dir/dapp
I0728 04:00:12.513689 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 13
I0728 04:00:12.513976 eth/backend.go:201] Blockchain DB Version: 3
I0728 04:00:12.515930 core/blockchain.go:206] Last header: #0 [23812aaa…] TD=256
I0728 04:00:12.516065 core/blockchain.go:207] Last block: #0 [23812aaa…] TD=256
I0728 04:00:12.516132 core/blockchain.go:208] Fast block: #0 [23812aaa…] TD=256
I0728 04:00:12.519883 p2p/server.go:313] Starting Server
I0728 04:00:15.109229 p2p/discover/udp.go:217] Listening, enode://449870522cf99663f642a60e84e191ca30af45c5fa0c6fbb199d8967dd268f7c3c09a8fb42720a84c0bb8a984a31d01b4255f5d56f0c6eb98b498f111c52c7bb@[::]:30303
I0728 04:00:15.111252 eth/backend.go:454] Automatic pregeneration of ethash DAG ON (ethash dir: /home/user/.ethash)
I0728 04:00:15.111370 p2p/server.go:556] Listening on [::]:30303
I0728 04:00:15.112044 eth/backend.go:461] checking DAG (ethash dir: /home/user/.ethash)
I0728 04:00:15.151132 node/node.go:296] IPC endpoint opened: data_dir/geth.ipc
I0728 04:00:15.195940 node/node.go:366] HTTP endpoint opened: http://localhost:8545
I0728 04:00:15.196123 miner/miner.go:119] Starting mining operation (CPU=1 TOT=2)
I0728 04:00:15.197119 miner/worker.go:573] commit new work on block 1 with 0 txs & 0 uncles. Took 863.195µs
I0728 04:00:15.197251 ethash.go:259] Generating DAG for epoch 0 (size 1073739904) (0000000000000000000000000000000000000000000000000000000000000000)
I0728 04:00:17.619117 ethash.go:276] Done generating DAG for epoch 0, it took 2.421872731s
I0728 04:01:27.849348 miner/worker.go:339] 🔨  Mined block (#1 / 40857370). Wait 5 blocks for confirmation
I0728 04:01:27.850663 miner/worker.go:573] commit new work on block 2 with 0 txs & 0 uncles. Took 1.087017ms
I0728 04:01:27.851682 miner/worker.go:573] commit new work on block 2 with 0 txs & 0 uncles. Took 805.394µs
I0728 04:01:31.725157 miner/worker.go:339] 🔨  Mined block (#2 / 9c48d944). Wait 5 blocks for confirmation
I0728 04:01:31.725710 miner/worker.go:573] commit new work on block 3 with 0 txs & 0 uncles. Took 388.348µs
```

The problem is that the IPC endpoint `data_dir/geth.ipc` is not reachable; running:

`geth --ipcpath "$data_dir/geth.ipc" attach`

gives:

`Fatal: Unable to attach to remote geth: dial unix /home/user/.ethereum/geth.ipc: connection refused`

Changing the arguments:

`geth attach data_dir/geth.ipc`

gives:

`Fatal: Unable to attach to remote geth: invalid endpoint`

**Comment by imifos** [comment]
Above, you are (maybe unintentionally) mixing up $data_dir, data_dir and ./data_dir. What happens when you specify an absolute path like "/opt/ethereum/data_dir" everywhere?

**Comment by SethVgr** [comment]
No, the actual directory is always "data_dir" (I use a bash script to launch geth).

**Comment by bas-vk** [comment]
According to the logs the IPC endpoint is opened:
`I0728 04:00:15.151132 node/node.go:296] IPC endpoint opened: data_dir/geth.ipc`.

You do an attach without the underscore in data_dir:
`geth attach datadir/geth.ipc`

Try `geth attach data_dir/geth.ipc`. Attaching should work with relative paths.

**Comment by SethVgr** [comment]
Thanks, I've managed to set it accordingly.
