### ISSUE TITLE
Can't query an older transaction

### ISSUE THREAD

**Issue by J1a-wei** [ethereum/go-ethereum#28756]
### Question
I attempted to query an older transaction from Jul-12-2017 01:57:47 PM +UTC, but 'geth' returned null, which strikes me as odd. [Here is the link to the transaction on etherscan.io](https://etherscan.io/tx/0xb31f87312b1131e9fe8344f2b21be8d3deed73a4ac218e6a25912b0481888cee).

The command I used was:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0xb31f87312b1131e9fe8344f2b21be8d3deed73a4ac218e6a25912b0481888cee"],"id":1}' http://localhost:8599
And the response received was:

{"jsonrpc":"2.0","id":1,"result":null}
```
My Geth version is v1.13.4. Here are the startup parameters:
```
geth -
-authrpc.jwtsecret=/secret/jwtsecret 
--authrpc.addr=0.0.0.0 
--authrpc.port=8551
--authrpc.vhosts=* 
--http
--http.addr=0.0.0.0 
--http.port=8599 
--http.vhosts=* 
--http.api=web3,eth,net,engine,debug 
--datadir=/data/ethereum  
--mainnet 
--syncmode=snap
--db.engine=leveldb
--txlookuplimit=0
```

**Comment by MariusVanDerWijden** [comment]
Did you add `--txlookuplimit` after you synced or was it enabled during sync as well?

**Comment by J1a-wei** [comment]
I found out that I needed to add this option after google and didn't re-sync. So it needs to be re-synchronised yes?  @MariusVanDerWijden

**Comment by rjl493456442** [comment]
@J1a-wei You can change the `--txlookuplimit ` (e.g. --txlookuplimit 0), Geth will automatically regenerate the missing indexes for you.
