### ISSUE TITLE
Why does geth sign ECDSA signatures with v values of 0/1 instead of 27/27

### ISSUE THREAD

**Issue by samlaf** [ethereum/go-ethereum#28757]
My geth generated signatures were not getting accepted by my smart contract, and realized that our smart contract uses the openzeppelin [ECDSA library](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/04cb0141442074f321a7983c9472dd79d5a5cc76/contracts/utils/cryptography/ECDSA.sol#L135) which states
```
Appendix F in the Ethereum Yellow paper (https://ethereum.github.io/yellowpaper/paper.pdf), 
defines the valid range for s in (301): 0 < s < secp256k1n ÷ 2 + 1, and for v in (302): v ∈ {27, 28}.
[...]
If your library also generates signatures with 0/1 for v instead 27/28, 
add 27 to v to accept these malleable signatures as well.
```
and I noticed that [geth uses 0/1 for v](https://github.com/ethereum/go-ethereum/blob/2365d7796854744e8ba185dda855357e8fb9c292/crypto/signature_cgo.go#L55):
```
The produced signature is in the [R || S || V] format where V is 0 or 1.
```

Is there a reason for geth not following the whitepaper?

**Comment by lightclient** [comment]
`crypto.Sign` provides plain ECDSA operations. The 27/28 value is a standard in Ethereum, carried over from bitcoin. It has nothing to do with ECDSA. You will need to manually modify the V value of the returned signature to match the format you desire (either 27/28 or EIP-155).

**Comment by samlaf** [comment]
Thanks! Indeed colleague showed me https://twitter.com/pcaversaccio/status/1671488928262529031
