### ISSUE TITLE
Fix error logging as "error" not "eror

### ISSUE THREAD

**Issue by alex067** [ethereum/go-ethereum#28768]
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
When parsing through logs for errors, there is an inconsistency between the log level vs. standards. See: https://github.com/ethereum/go-ethereum/blob/master/log/logger.go 

```
	case slog.LevelError:
		return "eror"
```

#### Actual behaviour
The expected behavior is log levels follow standard levels and errors be logged as "error" as opposed to "eror." For example, the `LevelAlignedString` properly assigns `slog.LevelError` as `ERROR` however `LevelString` is assigning it as `eror`

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by rjl493456442** [comment]
@jwasinger Is it a typo? Please take a look.
