### ISSUE TITLE
Use request rpc eth_getTransactionReceipt. The request content is empty. Wait for a while and request again and the return will be normal.

### ISSUE THREAD

**Issue by rayn316** [ethereum/go-ethereum#28789]
#### System information

Geth version: v1.13.8
CL client & version: lighthouse@v4.5.0
OS & Version: Linux
Commit hash : (if `develop`)

#### Actual behaviour
Errors occur when using json-rpc request methods `eth_getTransactionReceipt` and `eth_getBlockReceipts`
`eth_getTransactionReceipt` returns empty when a request occurs, and returns to normal after a while.
`eth_getBlockReceipts` appears to return the wrong number of txs, but wait for a while and it will be the same as other nodes.

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by rjl493456442** [comment]
My hunch is your node was still indexing the transaction in the background and the associated index becomes available after a while.

Both `eth_getTransactionReceipt ` and `eth_getBlockReceipts ` need the index for serving RPC.
