### ISSUE TITLE
No `miner_hashrate` RPC method

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/go-ethereum#2881]
#### System information

Geth version: `geth version 1.4.10`
OS & Version: OSX

#### Expected behaviour

https://github.com/ethereum/go-ethereum/wiki/Management-APIs#miner_hashrate

When I call the `miner_hashrate` method over RPC I expect to get back the current hashrate.

#### Actual behaviour

Instead I get this error

I have ensured that the `miner` interface is enable in the available `geth` apis and that I can access the other `miner_` RPC methods.

#### Steps to reproduce the behaviour

Attempt to make the JSON-RPC call

#### Backtrace

```javascript
{'code': -32601, 'message': 'The method miner_hashrate does not exist/is not available'}
```

**Comment by bas-vk** [comment]
Try `eth_hashrate`. This method was redundant and therefore removed. Will update the docs.

**Comment by pipermerriam** [comment]
Thanks for the info.  I was somewhat assuming that was the case.
