### ISSUE TITLE
Unstable block generation rate of Ethereum private chain

### ISSUE THREAD

**Issue by lpx-single** [ethereum/go-ethereum#28828]
Hi, everyone. I recently built an Ethereum private chain(clique) with two nodes.  I want to measure the block rate of this private chain. The genesis file is as follows:
```
{
  "config": {
    "chainId": 53783,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "muirGlacierBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0,
    "arrowGlacierBlock": 0,
    "grayGlacierBlock": 0,
    "clique": {
      "period": 0,
      "epoch": 30000
    }
  },
  "difficulty": "1",
  "gasLimit": "80000000000000",
  "extradata": "0x0000000000000000000000000000000000000000000000000000000000000000111111111111111111111111111111111111111122222222222222222222222222222222222222220000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "alloc": {
    "1111111111111111111111111111111111111111": { "balance": "500000000000000000000" },
    "2222222222222222222222222222222222222222": { "balance": "500000000000000000000" }
  }
}
```

The topology of the private chain is as follows:
![topology](https://github.com/ethereum/go-ethereum/assets/75900633/937990c0-0418-4f2e-98b7-75bac4edc688)
My idea is as follows: let Node1(server1) frequently initiate transactions to Node2(server2) for a certain period of time, I used the following code on server1 to achieve this behaviour:
```
i = 1
nonce = 0
while (i == 1) {
  eth.sendTransaction({
    from: eth.accounts[0],                                   //node1
    to: '0x2222222222222222222222222222222222222222',        //node2
    value: 10,
    nonce: nonce++
    })
  for (let j = 0; j < 30000; ++j) {
  }
}
```
Then I count the block generation rate per minute during this period, and then obtain the block generation rate of the private chain.

However, when I repeated the experiment, I found that the block rate fluctuated greatly for each experiment. Sometimes, the private chain generates blocks smoothly and records a smaller number of transactions per block. Sometimes, the block production speed of the private chain fluctuates greatly, and blocks that record a large number of transactions and are produced slowly appear frequently. In the first case, the block output rate is faster and the second case has a slower rate.

My questions are: 1) Why do the same experiments in the same experimental environment lead to different block generation situations. Is this a normal phenomenon?2) If this is normal, is there any way to more accurately measure the block production rate of the private chain I built?

*More details:*
***experiment enviroment:***
```
Geth
Version: 1.13.5-stable
Git Commit: 916d6a441a866cb618ae826c220866de118899f7
Architecture: amd64
Go Version: go1.21.4
Operating System: linux
GOPATH=
GOROOT=
```
***Running private minners command:***
```
geth --datadir node1 --port 30306 --bootnodes enode://410cccae8f204f84f5415d80dbf888ee76ddc59550846ccb9839e38ab285597c7fff7ddfd7200d0e7fb34e3018b87eee4d392c6ee0165f62adec40546fe3bd02@192.168.50.11:0?discport=30305 --networkid 53783 --unlock 0x1111111111111111111111111111111111111111 --password node1/password.txt --authrpc.port 8551 --mine --miner.etherbase 0x1111111111111111111111111111111111111111
```

**Comment by holiman** [comment]
>  let Node1(server1) frequently initiate transactions to Node2(server2) 

This does not make sense. You do not make transactions to another node, a transaction goes from one `address` to another `address`. Just because one of them (or both) coincide with the coinbase used at the nodes, it doesn't affect anything. 

I guess the big question is what the sealing engine does. Is it one miner sealers sealing all blocks, or are you using two sealers, where they have to take turns? The former can spit out blocks at a high rate. 

Regardless, the question you are investigating is not of general interest, since it's highly artificial: very far from production ethereum (different topology, different consensus-engine, different payloads etc), so I'll close this ticket.
