### ISSUE TITLE
Wiki: Add example for Docker volumes

### ISSUE THREAD

**Issue by yep** [ethereum/go-ethereum#2883]
Please update the [Running in Docker](https://github.com/ethereum/go-ethereum/wiki/Running-in-Docker) wiki page to contain instructions on how to use Docker volumes to persist blockchain data between container restarts.

I made a proposal how the wiki page could be changed, see  [this commit](https://github.com/yep/go-ethereum-wiki/commit/f32a42a655159802fea03f13780e5a461c194438)

That is, I'd like to add the following markdown
```
To persist downloaded blockchain data between container starts, use Docker [data volumes](https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume). Replace `/path/on/host` with the location you want to store the data in.

    docker run -it -p 30303:30303 -v /path/on/host:/root/.ethereum ethereum/client-go

In addition to the container based on [Ubuntu](http://www.ubuntu.com) (158 MB), there is a smaller image using [Alpine Linux](https://alpinelinux.org) (35 MB). To use the alpine [tag](https://hub.docker.com/r/ethereum/client-go/tags), replace `ethereum/client-go` with `ethereum/client-go:alpine` in the examples above.
```

which is rendered like this:

To persist downloaded blockchain data between container starts, use Docker [data volumes](https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume). Replace `/path/on/host` with the location you want to store the data in.
 
 ```shell
 docker run -it -p 30303:30303 -v /path/on/host:/root/.ethereum ethereum/client-go
 ```
 
In addition to the container based on [Ubuntu](http://www.ubuntu.com) (158 MB), there is a smaller image using [Alpine Linux](https://alpinelinux.org) (35 MB). To use the alpine [tag](https://hub.docker.com/r/ethereum/client-go/tags), replace `ethereum/client-go` with `ethereum/client-go:alpine` in the examples above.

**Comment by fjl** [comment]
Done
