### ISSUE TITLE
EthClient.BlockByNumber(),returns a error : missing required field 'maxFeePerBlobGas' for txdata

### ISSUE THREAD

**Issue by wangzai292** [ethereum/go-ethereum#28841]
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
I want to get the information of the block based on the block number，blockNum is 10398995、10398996
I expect to get the translation information of the block

#### Actual behaviour

but it returns an error  
if dec.MaxFeePerBlobGas == nil {
			return errors.New("missing required field 'maxFeePerBlobGas' for txdata")
		}
in releases 1.13.10 transaction_marshalling.go      line   349 - line 351

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by wangzai292** [comment]
To add another important point, this is what happened on the goerli test chain

**Comment by holiman** [comment]
Interesting. Seems like the backend delivers a blob-transaction without delivering the `maxFeePerBlobGas`, thereby causing decoding-errors in `ethclient`.

**Comment by rjl493456442** [comment]
How do you retrieve the block? Are you requesting it from a local Geth node via JSONPRC? Or you are using the ethclient with a remote backend?

**Comment by holiman** [comment]
Using geth attach against a goerli node
```
WARN [01-19|15:01:33.292] Server does not support method rpc_modules, using default API list.
Welcome to the Geth JavaScript console!

instance: EmeraldDshackle/0.14.0
coinbase: 0x0000000000000000000000000000000000000000
at block: 10399877 (Fri Jan 19 2024 15:01:00 GMT+0100 (CET))
...

> res = eth.getBlockByNumber(10398995, true)
> res.transactions.forEach(function(tx) { console.log(tx.type) } )
0x2
0x2
0x2
0x2
0x2
0x2
0x2
0x2
0x2
0x2
0x2
0x2
0x2
0x2
0x2
0x0
0x0
0x0
0x0
0x0
0x0
0x0
0x0
0x0
0x0
> res = eth.getBlockByNumber(10398996, true)
> res.transactions.forEach(function(tx) { console.log(tx.type) } )
0x2
0x3
0x2
...
> res.transactions[1]
{
  accessList: [],
  blobVersionedHashes: ["0x01b58d21a04dd655aa4bdb4164d793e804645d43c536c847eef21a768f5764b3", "0x01883a634024c636e8ff9180e9085327bb260d347334552a16e8a20a4f17217d", "0x016316f61a259aa607096440fc3eeb90356e079be01975d2fb18347bd50df33c"],
  blockHash: "0x3a0da99dcde3b9304d298de36336da55876a2ed3ea6e990c50440a819a2f94a3",
  blockNumber: "0x9ead14",
  chainId: "0x5",
  from: "0x9602c1658284eac6d09ebe0b740cc64dc5eb5d3e",
  gas: "0x5208",
  gasPrice: "0x165a0bc09",
  hash: "0x699c2c31aed3358b6159d806a23c43d7289742c79c6d5cdeb02630261a6cc053",
  input: "0x",
  maxFeePerBlobGas: "0x8bb2c97000",
  maxFeePerGas: "0x8bb2c97000",
  maxPriorityFeePerGas: "0x165a0bc00",
  nonce: "0x47c",
  r: "0x94665417f190c8e0abb3c519c28fa377a4a833d12d989d2a6653b9996f197713",
  s: "0x12027e3dc435c2b0506bc911f4bb798ee1c508e56998620eeedd430d051f5b0d",
  to: "0x184a8b43dace281e8afd9aeb143f81396fa73ce7",
  transactionIndex: "0x1",
  type: "0x3",
  v: "0x1",
  value: "0x0",
  yParity: "0x1"
}

```
Seems to be there

**Comment by holiman** [comment]
```
> res.transactions.forEach(function(tx) { if(tx.type == "0x3"){ console.log("tx.maxFeePerBlobGas: "+tx.maxFeePerBlobGas) } } )
tx.maxFeePerBlobGas: 0x8bb2c97000
tx.maxFeePerBlobGas: 0x2e90edd000
tx.maxFeePerBlobGas: 0x2e90edd000
```

**Comment by agostbiro** [comment]
I can repro with Alchemy, but not with Infura. Example repro:

```
curl --request POST \
     --url https://eth-goerli.g.alchemy.com/v2/docs-demo \
     --header 'origin: https://docs.alchemy.com' \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_getTransactionByHash",
  "params": [
    "0x5f9672ef1e8988be1023c27620f41f41f7f675aea59d557bdffb6b4366ea5134"
  ]
}
' | jq .result.maxFeePerBlobGas
```

Should print `"0x8bb2c97000"`, but instead it prints `null`.

**Comment by wangzai292** [comment]
> How do you retrieve the block? Are you requesting it from a local Geth node via JSONPRC? Or you are using the ethclient with a remote backend?
> 
> Edit, ah you mentioned it's ethclient. What backend are you using? alchemy works for me.

yes, I read from local lighthouse client via jsonRPC

**Comment by wangzai292** [comment]
> Interesting. Seems like the backend delivers a blob-transaction without delivering the `maxFeePerBlobGas`, thereby causing decoding-errors in `ethclient`.

But this is a query for block number information, not a transaction.

**Comment by wangzai292** [comment]
> instead

I am using archemy’s remote rpc node

**Comment by wangzai292** [comment]
> How do you retrieve the block? Are you requesting it from a local Geth node via JSONPRC? Or you are using the ethclient with a remote backend?
> 
> Edit, ah you mentioned it's ethclient. What backend are you using? alchemy works for me.

I am using archemy’s remote rpc node.

**Comment by wangzai292** [comment]
> I can repro with Alchemy, but not with Infura. Example repro:
> 
> ```
> curl --request POST \
>      --url https://eth-goerli.g.alchemy.com/v2/docs-demo \
>      --header 'origin: https://docs.alchemy.com' \
>      --header 'accept: application/json' \
>      --header 'content-type: application/json' \
>      --data '
> {
>   "id": 1,
>   "jsonrpc": "2.0",
>   "method": "eth_getTransactionByHash",
>   "params": [
>     "0x5f9672ef1e8988be1023c27620f41f41f7f675aea59d557bdffb6b4366ea5134"
>   ]
> }
> ' | jq .result.maxFeePerBlobGas
> ```
> 
> Should print `"0x8bb2c97000"`, but instead it prints `null`.

Yeah, I'm using archemy's remote rpc node，and this error will occur.

**Comment by NorutoSDK** [comment]
Hahaha Ethereum Not Working ? WHO SATOSHI NEW ?

**Comment by Metal-joker** [comment]
Wired, I', also using alchemy's remote rpc node on goerli, same error occurs. but alchemy dashboard says request success

**Comment by rjl493456442** [comment]
I can repro locally with this script 

```go

package main

import (
	"context"
	"fmt"
	"math/big"
	"os"

	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/log"
)

func newProvider(url string) *ethclient.Client {
	client, err := ethclient.Dial(url)
	if err != nil {
		log.Crit("Failed to setup client", "error", err)
	}
	return client
}

func main() {
	client := newProvider("https://eth-goerli.g.alchemy.com/v2/MY_TOKEN")
	block, err := client.BlockByNumber(context.Background(), big.NewInt(10398996))
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	for _, tx := range block.Transactions() {
		fmt.Println("Txhash", tx.Hash())
	}
}
```

The transaction `0x699c2c31aed3358b6159d806a23c43d7289742c79c6d5cdeb02630261a6cc053` in this block is a blob tx, but the `maxFeePerBlobGas` field is missing ( not returned by alchemy ).

**Comment by egonspace** [comment]
Maybe it depends on rpc server. I tried it for blockpi node and i got a result successfully.
