### ISSUE TITLE
Run new PoS Public Ethereum network.

### ISSUE THREAD

**Issue by KP-Universe** [ethereum/go-ethereum#28848]
I want to create a blockchain network with a different name by changing the chain ID of Ethereum's PoS system. Is there a way to start over from the Genesis block? I couldn't find any reference materials in the Geth Documentation or Ethereum Documentation...

**Comment by lightclient** [comment]
You'll have to create beacon network and drive geth with a consensus client. You might checkout something like this: https://github.com/ethpandaops/template-devnets

Creating private PoS networks are much more involved than before though.

**Comment by KP-Universe** [comment]
> You'll have to create beacon network and drive geth with a consensus client. You might checkout something like this: https://github.com/ethpandaops/template-devnets
> 
> Creating private PoS networks are much more involved than before though.

Thank you for that information I'll try it!!
