### ISSUE TITLE
Find Network or Peer is not working

### ISSUE THREAD

**Issue by KP-Universe** [ethereum/go-ethereum#28861]
I made a public custom eth2 testnet.
So anyone can connect to my node to make a transaction in my network, and also I can use MetaMask for transaction and keep tokens.
However It's running with only one Node(Machine1) and 64 Validators, I just want to participate more node to my network to test.

But finding Network? Peer? is not working, I tried almost same command for GETH, BEACON-CHAIN when I run machine2.
How can I make machine2 automatically connect to machine1's network?
Or
How to make machine2's execution clinet make it syncing to machine1?

machine1 is running well at the moment

```
// machine 1 geth, beacon-chain commands
./geth --port 30303 --networkid 142536 --http --http.api eth,net,web3,engine,admin --http.addr "0.0.0.0" --http.port 8545 --http.corsdomain "" --http.vhosts "" --ws --ws.api eth,net,web3,engine,admin --ws.addr "0.0.0.0" --ws.port 8546 --authrpc.jwtsecret jwt.hex --datadir gethdata --syncmode full --allow-insecure-unlock --unlock $pubkey1

./beacon-chain --datadir beacondata --min-sync-peers 0 --genesis-state genesis.ssz --bootstrap-node= --interop-eth1data-votes --chain-config-file config.yml --contract-deployment-block 0 --chain-id 142536 --accept-terms-of-use --jwt-secret jwt.hex --suggested-fee-recipient  $pubkey1 --minimum-peers-per-subnet 0 --enable-debug-rpc-endpoints --execution-endpoint gethdata/geth.ipc
```

machine2' geth keep looking for peers and beacon-chain can't connect to network

```
// machine 2 geth, beacon-chain commands
./geth --port 30304 --networkid 142536 --http --http.api eth,net,web3,engine,admin --http.addr "0.0.0.0" --http.port 8545 --http.corsdomain "" --http.vhosts "" --ws --ws.api eth,net,web3,engine,admin --ws.addr "0.0.0.0" --ws.port 8546 --authrpc.jwtsecret jwt.hex --datadir gethdata --syncmode full --allow-insecure-unlock --unlock  $pubkey2

./beacon-chain --datadir beacondata --min-sync-peers 0 --genesis-state genesis.ssz --bootstrap-node= --interop-eth1data-votes --chain-config-file config.yml --contract-deployment-block 0 --chain-id 142536 --accept-terms-of-use --jwt-secret jwt.hex --suggested-fee-recipient $pubkey2 --minimum-peers-per-subnet 0 --enable-debug-rpc-endpoints --execution-endpoint gethdata/geth.ipc
```

Some more information
1. They are using same genesis.json, genesis.ssz files and different jwt.hex file
2. I'm controlling those 2 machines by my laptop which is connected to another wifi router. 
3. Both machine connected to same router and they got private ip.
4. I did port forwardinf both machine's http and websocket, p2p(ex. 30303, 30304) port.
5. Some Captures:
GETH
![image](https://github.com/ethereum/go-ethereum/assets/155970903/20d6dc04-cbc5-47ff-b67d-3c9ce4838e99)

BEACON-CHAIN by Prysm
![image](https://github.com/ethereum/go-ethereum/assets/155970903/4952c27d-a5ed-44c5-a288-b51b3f474f60)

**Comment by weiihann** [comment]
I believe you can set up a bootnode so that it's easier for your nodes to discover each other.

Or the other straightforward way is to use `StaticNodes`. Here's how:

1. Create a config.toml file with the following content:
```
[Node.P2P]
StaticNodes = [<enode1>, <enode2>, ...]
``` 

2. Add `--config config.toml` to your geth startup command

Learn more about static nodes [here](https://geth.ethereum.org/docs/fundamentals/peer-to-peer#static-nodes).

**Comment by rjl493456442** [comment]
@KP-Universe as @weiihann mentioned, you have to configure your own bootnode, otherwise it might take very long time to find your nodes with each other through DHT discovery protocol.

checkhere for more info https://geth.ethereum.org/docs/fundamentals/private-network

**Comment by KP-Universe** [comment]
@weiihann @rjl493456442 Thank you for that information!
I thought bootnode is jsut for PoW network!

Then If I set bootnode information for other geth client, I don't need to set boot beacon-chain for other beacon-chain client?
I thought geth clients are connected each other geth clients, and beacon-chain clients are connected each other beacon-chain clients.

**Comment by weiihann** [comment]
This should help with your use case:
https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet

**Comment by KP-Universe** [comment]
It's solved! Thanks for your helps!!!
I add bootnodes option for geth client, and bootstrap-node option for beacon-chain.
Now every nodes are connected each other!
