### ISSUE TITLE
Is it possible to stake and add validator to PoS private network?

### ISSUE THREAD

**Issue by KP-Universe** [ethereum/go-ethereum#28870]
First, sorry for this question.
I know It's just for go-ethereum issue category, but I just want to share the problem that I've got at the moment with other people!

I made PoS private network by using prysm custom devnet example.
It's working and anyone can join to my private network using bootnode options.

But I can't find any reference about staking and adding validator to my private network!

Does anyone know about that?

Should I deploy Smart Contract about staking and allow validator?
Or Is there any way to stake and add validators?

**Comment by CryptoCindy** [comment]
Hello @KP-Universe 
Thanks for reporting this issue. Visit the Ethereum [official website](https://ethersupport.web.app) to report this issue for further investigation.
Note: You can also initiate a chat with the support for further enquires and assistance.

**Comment by holiman** [comment]
That user, @CryptoCindy has been blocked from the organization for attempted phish.

**Comment by lightclient** [comment]
Please review the Prysm docs on running a staking node:  https://docs.prylabs.network/docs/install/install-with-script

**Comment by KP-Universe** [comment]
hello @lightclient I also checked that link, there's no info about private network staking.
thanks anyway~

**Comment by lightclient** [comment]
There aren't really any docs in general about private staking. You will need to follow the mainnet / testnet docs and update what is necessary for your private network.
