### ISSUE TITLE
Ethclient Log Subscription - Indefinite events on error channel after Unsubscribe()

### ISSUE THREAD

**Issue by vdamle** [ethereum/go-ethereum#28871]
#### System information

Geth version: `v1.13.7`
CL client & version: N/A (reporting a bug in the library)
OS & Version: Linux
Commit hash : N/A

#### Expected behaviour

After calling `Unsubscribe()` on a `ClientSubscription`, the caller expects to receive [one notification](https://github.com/ethereum/go-ethereum/blob/master/interfaces.go#L38-L42) on the error channel.

#### Actual behaviour

For a `ClientSubscription` that is setup on a websocket instance of `ethclient` to  [SubscribeFilterLogs](https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go#L437), after a call to `Unsubscribe()`, a loop to consume the error channel receives events indefinitely.

One interesting point, this behavior only occurs when using `SubscribeFilterLogs` and does not occur for [SubscribeNewHead](https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go#L337).

#### Steps to reproduce the behaviour

See sample program below (websocket URL has been removed for obvious reasons, one can reproduce this by connecting to any node's websocket interface). We'd expect to see one occurrence of `error received on subscription`, but it's logged indefinitely.

```
package main

import (
	"context"
	"sync"
	"time"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/rpc"
	"go.uber.org/zap"
)

var log *zap.SugaredLogger

var (
	websocketURL = ""
)

func InitLogger() {
	logger, _ := zap.NewProduction()
	defer logger.Sync() // flushes buffer, if any
	log = logger.Sugar()
}

func processLogs(sub ethereum.Subscription, logNotif chan types.Log) {
	for {
		select {
		case <-sub.Err():
			log.Error("error received on subscription")
		case contractLog := <-logNotif:
			log.Info("Received log with topics from subscription", "topics", contractLog.Topics)
		}
	}
}

func main() {

	InitLogger()
	log.Info("Connecting to node url")

	ctx := context.Background()

	connWS, err := rpc.DialWebsocket(ctx, websocketURL, "")
	if err != nil {
		log.Errorf("Unable to create websocket connection to NODE url", err)
	}
	wsClient := ethclient.NewClient(connWS)

	// setup a subscription
	// v3 pool contracts for ETH/USDC and DAI/USDC
	addresses := []common.Address{
		common.HexToAddress("0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"),
		common.HexToAddress("0x5777d92f208679db4b9778590fa3cab3ac9e2168"),
	}

	topics := []common.Hash{}
	filterTopics := [][]common.Hash{}
	eventSignatures := []string{
		"Swap(address,address,int256,int256,uint160,uint128,int24)",
	}
	for _, e := range eventSignatures {
		topics = append(topics, crypto.Keccak256Hash([]byte(e)))
	}
	filterTopics = append(filterTopics, topics)

	filterQuery := ethereum.FilterQuery{
		Topics:    filterTopics,
		Addresses: addresses,
	}

	logNotif := make(chan types.Log)

	sub, err := wsClient.SubscribeFilterLogs(context.Background(), filterQuery, logNotif)
	if err != nil {
		log.Errorf("unable to subscribe for filter logs: %s", err)
	}

	var wg sync.WaitGroup
	wg.Add(1)
	go processLogs(sub, logNotif)

	// unsubscribe after a few seconds
	time.Sleep(10 * time.Second)
	log.Info("Unsubscribe from log subscription")
	sub.Unsubscribe()

	// do other stuff
	time.Sleep(10 * time.Second)
	wg.Done()
}
```

#### Backtrace

N/A

**Comment by lindlof** [comment]
> After calling Unsubscribe() on a ClientSubscription, the caller expects to receive [one notification](https://github.com/ethereum/go-ethereum/blob/master/interfaces.go#L38-L42) on the error channel.

No error value is expected to be returned from the channel because of `Unsubscribe()`. A single value with an `error` instance is sent to the channel if an error occurs.

> For a ClientSubscription that is setup on a websocket instance of ethclient to [SubscribeFilterLogs](https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go#L437), after a call to Unsubscribe(), a loop to consume the error channel receives events indefinitely.

`Unsubscribe()` documents that the error channel will be closed. When Golang channel is closed it always returns zero value immediately. Looping over a closed channel like this will produce an infinite loop.

> One interesting point, this behavior only occurs when using SubscribeFilterLogs and does not occur for [SubscribeNewHead](https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go#L337).

To me it's producing the same behavior with `SubscribeNewHead`.

**Comment by fjl** [comment]
@vdamle your `processLogs` loop needs to exit on the first message received from the error channel.
