### ISSUE TITLE
Why was UDP closed in the latest update?

### ISSUE THREAD

**Issue by Phoenix1969** [ethereum/go-ethereum#28883]
Peers connecting has become horrible since the last update and i noticed the closed connection. it is effecting the entire network.
Why and what are we supposed to do about it?

**Comment by lightclient** [comment]
Can you provide more information on the issue you are seeing? What version of go-ethereum did you notice the issue first? I don't believe there were any modifications to the p2p module in the release 1.13.11.

**Comment by Phoenix1969** [comment]
apologies were running etclabscore

**Comment by Phoenix1969** [comment]
closed
