### ISSUE TITLE
the method net_version does not exist/is not available

### ISSUE THREAD

**Issue by zychappy** [ethereum/go-ethereum#28891]
the version https://github.com/ethereum/go-ethereum/releases/tag/v1.13.11
running in sepolia testnet reports some err like below:

geth: WARN [01-28|18:09:10.951] Served net_version     
duration="5.879µs" err="the method net_version does not exist/is not available"

is it alright?

**Comment by karalabe** [comment]
Did you manually set `--http.api`?

**Comment by holiman** [comment]
What are the cli options that you are using to run your node?
