### ISSUE TITLE
Recovering a Private POA Node.

### ISSUE THREAD

**Issue by askhmza** [ethereum/go-ethereum#28898]
### Description

I am attempting to recover and run a Proof of Authority (POA) node to access transactions and blocks. The node belonged to a private network that was shutdown 6 months ago. However, I'm encountering an issue where the geth node seems to be truncating the freeze table and rewinding the blockchain unexpectedly.

### Environment

- Geth version: [1.13.11-stable]
- OS & Version: [Linux]
- Command used to start Geth: 
- > geth --datadir ./data/ --verbosity=4 --http --http.api personal,db,eth,net,web3,txpool,admin,debug,clique,miner --maxpeers 0 --nodiscover --syncmode full`

### Expected Behavior

I expect the node to recover and load properly without truncating the blockchain data.

### Actual Behavior

- The log indicates that the most recent local block is loaded but then shows a warning: `Head state missing, repairing`.
- It proceeds to freeze deep chain segments but eventually throws an error indicating that it's truncating the ancient chain and rewinding the blockchain to a much earlier block.
- The relevant log output is as follows:

```
INFO [01-31|05:09:19.552] Loaded most recent local block number=5,978,750 hash=854870..6ec366 td=8,814,092 age=9mo1w2d
WARN [01-31|05:09:19.552] Head state missing, repairing number=5,978,750 hash=854870..6ec366
DEBUG[01-31|05:09:20.983] Deep froze chain segment                 blocks=30001 elapsed=3.343s number=60001     hash=5e9c3e..b13527
DEBUG[01-31|05:09:24.544] Deep froze chain segment                 blocks=30001 elapsed=3.561s number=90002     hash=8fd586..69fe72
...
DEBUG[01-31|05:12:32.375] Deep froze chain segment                 blocks=30001 elapsed=1.099s number=2,970,098 hash=d831f9..aa4de9
DEBUG[01-31|05:12:32.375] Current full block not old enough to freeze number=119       hash=989956..ac47c8 delay=90000
DEBUG[01-31|05:12:32.375] Current full block not old enough to freeze number=119       hash=989956..ac47c8 delay=90000
...
INFO [01-31|05:16:13.560] Loaded most recent local header          number=5,885,197 hash=17b24b..9d2659 td=6,403,134 age=9mo1w2d
INFO [01-31|05:16:13.560] Loaded most recent local block           number=119       hash=989956..ac47c8 td=207       age=4y9mo2w
INFO [01-31|05:16:13.560] Loaded most recent local snap block      number=5,885,197 hash=17b24b..9d2659 td=6,403,134 age=9mo1w2d
ERROR[01-31|04:59:46.093] Truncating ancient chain from=5,885,197 to=119
WARN [01-31|04:59:46.093] Rewinding blockchain to block target=119
DEBUG[01-31|04:59:46.093] Truncating freezer table                 database=/home/blockchain/data/geth/chaindata/ancient/chain table=diffs items=5,885,198 limit=5,885,197
DEBUG[01-31|04:59:46.095] Truncating freezer table                 database=/home/blockchain/data/geth/chaindata/ancient/chain table=headers items=5,885,198 limit=5,885,197
DEBUG[01-31|04:59:46.097] Truncating freezer table                 database=/home/blockchain/data/geth/chaindata/ancient/chain table=hashes items=5,885,198 limit=5,885,197
D
```

Any insights or guidance on how to resolve this issue would be greatly appreciated, as I need to recover the node to access historical transactions and blocks.

Thank you in advance for your help!

**Comment by karalabe** [comment]
Seems the node was not shut down properly prior to (I assume) backing up the whole thing. The recovery mechanism kind of assumes that there will be other nodes to recover data from, so it's a bit aggressive.

Now, given that (I assume) you have a backup to play with, one option you could try is to copy the ancients folder only into a new datadir (or copy the whole thing and delete chaindata) and then run Geth in full sync mode (--syncmode=full). I am actually unsure what will happen, whether it will consume the ancients or nuke them back to genesis. But it's a cheap attempt to try.

A more complicated approach is to attach to the freezer directly from Go and export the blocks that you can later geth import, but let's go there if the easy approach fails.

**Comment by askhmza** [comment]
Hey @karalabe, Thank you for the response. 
Unfortunately, I do not have a proper backup. What I do have is the `datadir` of the blockchain.
Here's the folder structure of it.
```
blockchain/data/
blockchain/data/keystore/
blockchain/data/geth/
blockchain/data/geth/lightchaindata/
blockchain/data/geth/nodes/
blockchain/data/geth/chaindata/
```
As you can see, its missing the ancient folder
The `chaindata` folder has a bunch of ldb files with 
```
total 3.9G
..
..
2.1M Jul 25  2023 030470.ldb
2.1M Jul 25  2023 030471.ldb
2.1M Jul 25  2023 030472.ldb
172K Jul 25  2023 030473.ldb
16 Mar  1  2023 CURRENT
16 Mar  1  2023 CURRENT.bak
0 Mar  1  2023 LOCK
631K Jul 25  2023 LOG
1.1M Mar  2  2023 LOG.old
3.4M Jul 25  2023 MANIFEST-000004
```

**Comment by askhmza** [comment]
Hey @karalabe, we have solved this issue!

**Comment by Timmy-Cai** [comment]
> Hey @karalabe, we have solved this issue! Thanks


I also found the same problem in the POA network. A lot of data was lost. How did you solve it in the end?

**Comment by bakerpearl** [comment]
**Sylvester G. Bryant, a reputable expert in fund recovery, can be reached for assistance at [Yt7cracker@gmail.com](mailto:Yt7cracker@gmail.com) or on Instagram under the handle Yt7crackersz. Clients who have fallen victim to scams can rely on his unwavering reliability and trustworthiness when it comes to the retrieval of their stolen funds. With a proven track record of successfully recovering scammed funds, Sylvester G. Bryant stands out as a competent professional in the realm of financial restitution. His dedication and expertise make him a top choice for those seeking swift and effective resolution to such unfortunate situations.**
