### ISSUE TITLE
syncing stuck on sepolia after upgrading v1.13.11

### ISSUE THREAD

**Issue by cryptocifer** [ethereum/go-ethereum#28899]
beacon chain reports
```
beacon  | time="2024-01-31 05:52:17" level=warning msg="Execution client is not syncing" prefix=powchain
beacon  | time="2024-01-31 05:52:31" level=warning msg="Execution client is not syncing" prefix=powchain
```

while execution said:
```
geth  | INFO [01-31|05:43:07.007] Looking for peers                        peercount=2 tried=55 static=0
geth  | WARN [01-31|05:43:15.063] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!
```

geth: v1.13.11
beacon prysm: v4.2.1

**Comment by rjl493456442** [comment]
`Beacon client online, but no consensus updates received in a while`

Looks like there is no event sent from consensus client. Geth needs to be driven by these events for syncing.

**Comment by Brindrajsinh-Chauhan** [comment]
Seeing similar issue, the node is not moving ahead with the synchronization process
See these logs for a almost 24 hours. Finalized is moving up but not sure if it should take this long to start syncing back.
```
INFO [01-31|14:37:48.940] Forkchoice requested sync to new head    number=5,191,293 hash=578707..081dd7 finalized=5,191,207
INFO [01-31|14:38:00.524] Forkchoice requested sync to new head    number=5,191,294 hash=16ba39..6ca73a finalized=5,191,207
```

**Comment by ArturDolzan** [comment]
Same issue

**Comment by niso1985** [comment]
I solved the problem by changing the prysm version from 4.2.0 to 4.2.1.

**Comment by ivan-pohosov** [comment]
Some updates?

**Comment by rjl493456442** [comment]
Restart the consensus client could probably help

**Comment by holiman** [comment]
Geth is at the mercy of the beacon client here. Not much EL can do without directions from CL, so we're going to have to blame them :)

**Comment by lil0uuu** [comment]
I'm also encountering this issue. This keeps happening (daily) recently
