### ISSUE TITLE
cmd/devp2p: Bootnodes are not populated when using `crawl` subcommand

### ISSUE THREAD

**Issue by ryanschneider** [ethereum/go-ethereum#28897]
If I run:

```
go build ./cmd/devp2p && ./devp2p discv5 crawl /tmp/nodes.json
INFO [01-30|15:50:42.862] New local node record                    seq=1,706,658,642,861 id=66355c79f58631fc ip=127.0.0.1 udp=57825 tcp=0
no input nodes to start crawling
```

However, the readme seems to indicate that it should work w/ an empty nodeset.

I traced the issue down to this block:

https://github.com/ethereum/go-ethereum/blame/eaac53ec383342fa6ef9c333659d40f7c5dac108/cmd/devp2p/discv4cmd.go#L271

```golang
	if commandHasFlag(ctx, bootnodesFlag) {
		bn, err := parseBootnodes(ctx)
		if err != nil {
			exit(err)
		}
		cfg.Bootnodes = bn
	}
```

The issue is that `parseBootnodes` is only called if `--bootnodes` flag is set, but that's also where the standard bootnodes are parsed.  Removing the `if commandHasFlag` check "fixes" the issue and allows me to start crawling, but I'm not sure if that breaks some other command.  I see this changed was introduced some time ago in https://github.com/ethereum/go-ethereum/pull/20094 so it seems like it's been in this state for quite awhile, so I'm not sure how actively maintained/used this tool is.

**Comment by fjl** [comment]
The tool is actively maintained! The behavior looks like a bug in CLI parsing logic. The crawl command accepts the --bootnodes flag, so it should be detected.
