### ISSUE TITLE
Transactions in the Mempool

### ISSUE THREAD

**Issue by thehood1** [ethereum/go-ethereum#28904]
I analyzed my node mempool for one hour. Only 60% TX included in blocks(during this one hour) appeared in my node mempool. Why I don't see other 40%??? Node configuration? Hardware? Any ideas?

Thanks

**Comment by lightclient** [comment]
Many txs are submitted directly to builders via private mempools, so you will not see the txs before they end up in a block.

**Comment by thehood1** [comment]
Is it possible that 40% are submitted via private mempools, that is too much?
