### ISSUE TITLE
Windows download has a security issue

### ISSUE THREAD

**Issue by vmmunoza** [ethereum/go-ethereum#28909]
![GFQTIi4XMAA5Ohw](https://github.com/ethereum/go-ethereum/assets/53861440/9df3d824-1ce4-4482-8063-ec6c331fd51c)

**Comment by MariusVanDerWijden** [comment]
Where did you get the exe from?

**Comment by karalabe** [comment]
Which security suite flagged it? Sometimes Windows is picky with P2P programs, and sometimes it's picky with crypto programs too. 

E.g. https://www.virustotal.com/gui/file/84f1fdf1be48dc26beaa7e53976dcb34e74488af42855fba4d9d5d915a5b5f6a

The latest Geth Windows installer is reported clean by all but one software.

**Comment by MariusVanDerWijden** [comment]
@fredriksvantes  send it to the Ikarus team in order to get it removed from their site
