### ISSUE TITLE
Geth(1.13.11) EVM is not support tload and tstore

### ISSUE THREAD

**Issue by Subway2023** [ethereum/go-ethereum#28926]
# command
go-ethereum-1.13.11/build/bin/evm --debug --json --code "??" --input  "??" run

# result
{"output":"","gasUsed":"0x2540be400","error":"invalid opcode: TSTORE"}

**Comment by karalabe** [comment]
TSTORE has not yet hit mainnet, so it is not enabled by default in any utility. You *may* be able to specify a custom genesis.json via `--prestate` with a config field that enables the Cancun hard fork to have it working.

**Comment by MariusVanDerWijden** [comment]
We will set the CancunTime here: https://github.com/ethereum/go-ethereum/blob/253447a4f5e5f7f65c0605d490360bb58fb5f8e0/params/config.go#L169 once the cancun hardfork is enabled on mainnet. You could do that for testing purposes beforehand on your local fork
