### ISSUE TITLE
All Gas is swallowed when fail to call PrecompiledContract and return error is not ErrExecutionReverted

### ISSUE THREAD

**Issue by buddh0** [ethereum/go-ethereum#28930]
<img width="649" alt="image" src="https://github.com/ethereum/go-ethereum/assets/7995985/4c2c2c2f-0f19-4da4-befb-85873d1e4445">

Is it by design or a bug？
even fail to call PrecompiledContract, just cost RequiredGas is better IMO

**Comment by holiman** [comment]
Yes, it is by design. That's very common in the ethereum vm specification, an error consumes all remaining gas.
