### ISSUE TITLE
Cant upload disable

### ISSUE THREAD

**Issue by Blldog** [ethereum/go-ethereum#28937]
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by rjl493456442** [comment]
Your ticket has no useful information. Please rework it if you do have something to report.
