### ISSUE TITLE
Question about snap sync mode

### ISSUE THREAD

**Issue by JourneyToSilius** [ethereum/go-ethereum#28941]
As I understand it, snap sync is a "checkpoint" sync that syncs a full node. But does it sync the same data that a full sync syncs in terms of usability ? I'm going to sync a full node today and need to know if I need to sync the node in full sync or snap sync mode. As I commented on the other question, I need data since genesis so it's going to be a non-pruned full node with `--history.transactions=0`

**Comment by karalabe** [comment]
A snap synced and full synced node produce the equivalent result, yes. All the past blocks and receipts are available and the recent contract state is available.

**Comment by JourneyToSilius** [comment]
Thanks for clarifying ! Do you know an estimate of disk size with the flag `history.transactions=0` compared to a default settings one ?

**Comment by karalabe** [comment]
Unfortunately I do not.

FWIW, we'd also recommend you use the path state scheme (--state.scheme=path). It will be the default soon, and that one is both faster as well as can prune the old state as the chain progresses vs. the current default hash leaves a lot of junk behind.

**Comment by JourneyToSilius** [comment]
thank you for the detailed information, I'm closing this
