### ISSUE TITLE
debug.processBlock() not working: incomplete dubug API or problem in the wiki?

### ISSUE THREAD

**Issue by lyricalpolymath** [ethereum/go-ethereum#2894]
Hi
I'm trying to use the debug.processBlock() API but I get a warning telling me that it is not a function.
**is the API still active?**

I've found this method it the ["Javascript Console" wiki page](https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#debugprocessblock) 

however , I've seen in the ["management APIs" wiki page](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug) that the command doesn't appear anymore

#### System information
Geth version: `1.4.10-stable-5f55d95a`
OS & Version: OSX

I was trying to see if there was an API to force the redownload of a single block that was downloaded with the --fast option.

**Comment by bas-vk** [comment]
The debug API is still available only this method was removed.

There is no API to force the redownload of a single block. There is `debug.setHead(blockNum)`. That will "rollback" the chain to the given blocknumber and starts synchronising from that block. But it's not officially supported and there are problems with it that can corrupt your chain. In that case you need to resync from scratch.

**Comment by lyricalpolymath** [comment]
thanks for explaining it. maybe the api should be removed from the the wiki too then.
