### ISSUE TITLE
OOM kills geth frequently

### ISSUE THREAD

**Issue by SipengXie** [ethereum/go-ethereum#28967]
Trying to run an archive node using geth and prysm, but the OOM frequently kills the processes.
```
Feb 10 08:41:55 ecs-ce45 kernel: Out of memory: Kill process 26802 (beacon-chain-v4) score 562 or sacrifice child
Feb 10 09:07:46 ecs-ce45 kernel: Out of memory: Kill process 27191 (geth) score 506 or sacrifice child
Feb 10 09:59:57 ecs-ce45 kernel: Out of memory: Kill process 28013 (geth) score 560 or sacrifice child
Feb 10 11:05:39 ecs-ce45 kernel: Out of memory: Kill process 29265 (geth) score 560 or sacrifice child
```
```
              total        used        free      shared  buff/cache   available
Mem:          15884       11987         288         768        3607        2798
Swap:             0           0           0
```
The startup commands are:
```
geth \\
--mainnet  \\
--datadir $DATADIR  \\
--syncmode full \\
--gcmode archive  \\
--cache 4096 \\
--cache.gc 0 \\
--cache.snapshot 20 \\
--cache.trie 30 \\
--authrpc.vhosts="localhost"   \\
--authrpc.jwtsecret=$JWTPATH
```
and
```
./prysm.sh beacon-chain \\
--mainnet \\
--datadir $DATADIRCONSENSUS \\
--execution-endpoint=$ENDPOINT \\
 --jwt-secret=$JWTPATH  \\
--checkpoint-sync-url=https://sync.invis.tools 
```
Corresponding information:
```
Version: 1.13.11-stable
Git Commit: 8f7eb9ccd99ee47721a7bfde494d6da28de4cd8e
Git Commit Date: 20240124
Architecture: amd64
Go Version: go1.21.6
Operating System: linux
```

**Comment by flowac** [comment]
Can you try changing the cache 4096 to something smaller and remove other cache options?
When is the memory usage taken? Is that the typical case? Before OOM? After OOM?

**Comment by SipengXie** [comment]
The memory usage is taken after OOM, now I will try to change 4096 to 2048.

**Comment by holiman** [comment]
You will not be able to run an archive node + beacon on `16G`, with geth at `4G`. Geth will occasionally exceed it's `--cache` limit, and you need some margin on the machine to account for that.

**Comment by SipengXie** [comment]
Is it safe to set the cache to a lower value?

**Comment by holiman** [comment]
Depends on what you mean. If you set a too low value, geth will not always respect that value.

**Comment by SipengXie** [comment]
How much memory is required to run Geth in archive mode along with a beacon node?

**Comment by karalabe** [comment]
An archive node will need over 12-13TB of NVMe disk space. So even if you would manage to sync with 16GB or ram, it's quite a lot of load on your disk if you can't cache database stuff. We don't really have enough information to give a more meaningful answer, but perhaps think over exactly what you need (archive node vs non-archive node) and if you do need an archive, perhaps investigate how much disk space such a thing uses nowdays and what hardware others are running it on.
