### ISSUE TITLE
Unexpected overflow for BlobTxType

### ISSUE THREAD

**Issue by dthuering** [ethereum/go-ethereum#28969]
#### System information

Geth version: `n/a`
CL client & version: v1.12.2 / v1.13.12
OS & Version: Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

`BlobTxType` is processed correctly.

#### Actual behaviour

Errors are reported when calling `uint256.FromBig((*big.Int)(dec.R))` as it reports an overflow. 
Also opened an issue with the uint256 library. https://github.com/holiman/uint256/issues/147

#### Steps to reproduce the behaviour

Running Orchestrate tx-listener on Sepolia.

#### Backtrace

Logging the value that would return the error.

````
INFO   [0007] (tx-listener.session.ethereum.hook): block processed  block_number=5263607 chain=4b0aed40-c2da-44b1-9396-50233910590e owner_id= tenant_id=_
'r' value overflows uint256: 0xb75685b724028d4cc66bd8ff0aa46b6e4721842ac1f7f4880563b581dcfb2ee
's' value overflows uint256: 0x4cdd5a8417fa2c49aa472b8e079e01f276120089ea0c7b27df4533193876abed
'v' value overflows uint256: 0x1
'r' value overflows uint256: 0x241bff69a5506e1a26543b97b22854ec556f822b71627a3136f245e05b98fda9
's' value overflows uint256: 0x7a8ee9210af64eee6e3a15b331ea7d491d3d983f93d52b06f97282a050a9e973
'v' value overflows uint256: 0x1
````

When submitting logs: please submit them as text and not screenshots.

**Comment by dthuering** [comment]
The error occurs here https://github.com/ethereum/go-ethereum/blob/v1.12.2/core/types/transaction_marshalling.go#L380

Called from here: `json.Unmarshal(raw, body)`

Logging `R` shows `0x48af56a5b932526622d3327d8d7ece0af50a6191fbe28faa1eb5f75341da3c2f`, but I can't find it in the JSON.

[breaking_block.json](https://github.com/ethereum/go-ethereum/files/14232500/breaking_block.json)

**Comment by dthuering** [comment]
For some reason, only the new `BlobTxType` uses the _uint256_ library but the other types do not?
https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction_marshalling.go#L202

What is the reason for that?

**Comment by dthuering** [comment]
Could debug it a bit more and here is one of the transactions causing the error.

`'r' value overflows uint256`

```
{
    "accessList":
    [],
    "blobVersionedHashes":
    [
        "0x01885b468c85ed93df7e9a2aa9d2ccb1b12f2f92b8bd97b491220115dbb4c42e",
        "0x0119fb0903a0ccbaef1e960b2855286833b2bd4d2ffcc936123d740af18af301",
        "0x01f4d237e7a2ce0820d2bdd126339b50fe213320cf3a8179c182e93da1c49d97"
    ],
    "blockHash": "0xcddac2bfd1b865cea1fbec08a062edfbb11c79082428ae96bd79aae212985a1a",
    "blockNumber": "0x505111",
    "chainId": "0xaa36a7",
    "from": "0x1803c760451dc8da8935c7b7e47e1c60910e6986",
    "gas": "0x5208",
    "gasPrice": "0x86a6c1f1",
    "hash": "0xd38fc04c23c0e2a1f1d5e556ea88364e4e6895edd650a732314dc227fa8c16a0",
    "input": "0x",
    "maxFeePerBlobGas": "0x4a817c800",
    "maxFeePerGas": "0x2e90edd000",
    "maxPriorityFeePerGas": "0x77359400",
    "nonce": "0x1ba4",
    "r": "0x3889748695fa97b33be6d5e1550e55ef3b5090899814f961d14d998f40f7ff43",
    "s": "0x4ede62a43b546734c5353c0fb1728f0bf308a9bfdd84424652a0b40c95f31a8",
    "to": "0x4f56ffc63c28b72f79b02e91f11a4707bac4043c",
    "transactionIndex": "0x17",
    "type": "0x3",
    "v": "0x1",
    "value": "0x0",
    "yParity": "0x1"
}
```

**Comment by flowac** [comment]
> For some reason, only the new `BlobTxType` uses the _uint256_ library but the other types do not? https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction_marshalling.go#L202
> 
> What is the reason for that?

I looked at the source of the library at:
https://github.com/holiman/uint256/blob/f24ed59bea89c23941cf073aeb3f702514f3b371/conversion.go#L203

It will give overflow exception if the input is larger than int256.
This means if dec.R at:
https://github.com/ethereum/go-ethereum/blob/f1c27c286ea2d0e110a507e5749e92d0a6144f08/core/types/transaction_marshalling.go#L385
exceeds int256 then it fails. I don't see any functions for handling uint256 in that library.

**Comment by holiman** [comment]
Fixed on master

https://github.com/ethereum/go-ethereum/compare/v1.12.2...v1.13.12#diff-77719ae57e7e6c3e0cac05fa12c6c5f2e5f9bc810c034d1446de2414c36d9210

**Comment by holiman** [comment]
See https://github.com/holiman/uint256/issues/147#issuecomment-1938136811
