### ISSUE TITLE
Seeking Community Input: Changing Executable Names in Geth Project 

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#28972]
Hello GitHub Community,

I hope this message finds you well. I'm reaching out to provide an update on some recent developments in our project and to seek your valuable input.

Recently, I've been working diligently on changing executable names and enhancing the functionality of the terminal node running in our project. I am using the Clique PoA(Proof-of-Authority) Consensus Algorithm using geth.

Specifically, I've conducted a thorough analysis of these requests and have initiated the necessary changes. My primary focus is on renaming the executable file to better reflect the project's goals and direction.

As part of this effort, I examined the makefile to locate where executable file names are defined. I attempted modifications to incorporate the new name "AnyName" instead of the existing "geth". During this process, I also identified other relevant files, such as a ci.go file path, which contain functions crucial for updating names.

Despite my efforts, I'm still in the process of pinpointing the exact code required to change the executable file name. This task remains a work in progress, and I'm actively seeking insights and suggestions from the community to ensure a smooth transition.

Your expertise and feedback are highly valued, and I would greatly appreciate any insights or suggestions you may have regarding this endeavor. Please feel free to share your thoughts, ideas, or any relevant experiences with me.

Thank you for your continued support and collaboration. I look forward to hearing from you soon.

Best regards,

Asadullah Soomro.

**Comment by holiman** [comment]
1. Change `cmd/geth` into `cmd/whatever`.  Build with `go build cmd/whatever`
2. (optional) Change `geth` -> `whatever` in Makefile

**Comment by AsadullahSoomro** [comment]
@holiman, holiman, Thanks for the reply. I am currently checking it and will let you know once it is done. Thanks again.
