### ISSUE TITLE
confusing comment in blob priority explanation

### ISSUE THREAD

**Issue by bkellerman** [ethereum/go-ethereum#28977]
Is `delta-basefee` supposed to be a difference(subtraction operation) or a is `-basefee` a qualifier of the type of `delta`?

If it's a qualifier,  this comment is confusing as it appears to be a subtraction. I don't see a subtraction in the code. Maybe use an underscore?

`priority = min(delta-basefee, delta-blobfee)`

https://github.com/ethereum/go-ethereum/blob/f1c27c286ea2d0e110a507e5749e92d0a6144f08/core/txpool/blobpool/blobpool.go#L271

**Comment by ababyprogrammer** [comment]
This is my question, too.

**Comment by bkellerman** [comment]
PR https://github.com/ethereum/go-ethereum/pull/28981
