### ISSUE TITLE
All sealing work stopped

### ISSUE THREAD

**Issue by alex-bratu** [ethereum/go-ethereum#29002]
#### System information

Geth version: `1.13.12-stable`
OS & Version: Debian 11

#### Expected behaviour
A private POA network with clique protocol that seals new blocks.

#### Actual behaviour
All sealing work stopped and all the nodes give the same logs:

```
" Ancient blocks frozen already            number=4,754,682 hash=92372a..de4bec frozen=4,664,683"
" Couldn't get external IP                 err="no UPnP or NAT-PMP router discovered"  interface="UPnP or NAT-PMP" "
" Couldn't add port mapping                proto=TCP extport=30311 intport=30311 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered" "
```

Before this behavior geth 1.10.4 was installed and worked fine. I tried to update the cilent to the newest version but I get the same "error". 
Here is a section of the genesis file:
 
"homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "clique": {
      "period": 6,

I have a lot of transactions and I really need the data, so I cant just reset all the chain.

**Comment by rjl493456442** [comment]
Can you provide a bit more logs? 

`Ancient blocks frozen already` it's expected and should be a debug level log.

**Comment by alex-bratu** [comment]
-- Journal begins at Thu 2024-02-01 00:59:46 EET. --
Feb 19 09:17:12 01-Blockchain-National-STS bash[295166]: DEBUG[02-19|09:17:12.712] Couldn't add port mapping                proto=TCP extport=30311 intport=30311 interface="UPnP or NAT-PMP
" err="no UPnP or NAT-PMP router discovered"
Feb 19 09:17:52 01-Blockchain-National-STS bash[295166]: DEBUG[02-19|09:17:52.720] Ancient blocks frozen already            number=4,754,682 hash=92372a..de4bec frozen=4,664,683
Feb 19 09:18:52 01-Blockchain-National-STS bash[295166]: DEBUG[02-19|09:18:52.721] Ancient blocks frozen already            number=4,754,682 hash=92372a..de4bec frozen=4,664,683
Feb 19 09:19:12 01-Blockchain-National-STS bash[295166]: DEBUG[02-19|09:19:12.713] Couldn't get external IP                 err="no UPnP or NAT-PMP router discovered"  interface="UPnP or N
AT-PMP"
Feb 19 09:19:12 01-Blockchain-National-STS bash[295166]: DEBUG[02-19|09:19:12.713] Couldn't add port mapping                proto=TCP extport=30311 intport=30311 interface="UPnP or NAT-PMP
" err="no UPnP or NAT-PMP router discovered"
Feb 19 09:19:52 01-Blockchain-National-STS bash[295166]: DEBUG[02-19|09:19:52.721] Ancient blocks frozen already            number=4,754,682 hash=92372a..de4bec frozen=4,664,683
Feb 19 09:20:52 01-Blockchain-National-STS bash[295166]: DEBUG[02-19|09:20:52.721] Ancient blocks frozen already            number=4,754,682 hash=92372a..de4bec frozen=4,664,683
Feb 19 09:21:12 01-Blockchain-National-STS bash[295166]: DEBUG[02-19|09:21:12.714] Couldn't get external IP                 err="no UPnP or NAT-PMP router discovered"  interface="UPnP or N
AT-PMP"
Feb 19 09:21:12 01-Blockchain-National-STS bash[295166]: DEBUG[02-19|09:21:12.714] Couldn't add port mapping                proto=TCP extport=30311 intport=30311 interface="UPnP or NAT-PMP
" err="no UPnP or NAT-PMP router discovered"
Feb 19 09:21:52 01-Blockchain-National-STS bash[295166]: DEBUG[02-19|09:21:52.722] Ancient blocks frozen already            number=4,754,682 hash=92372a..de4bec frozen=4,664,683

**Comment by sellodayat** [comment]
555
