### ISSUE TITLE
https://github.com/ethereum/go-ethereum/tree/v1.13.12 Could you please tell me if this is a forced upgrade?

### ISSUE THREAD

**Issue by astrid19981112** [ethereum/go-ethereum#29030]
https://github.com/ethereum/go-ethereum/tree/v1.13.12 Could you please tell me if this is a forced upgrade?

**Comment by rjl493456442** [comment]
This release enables the cancun fork for mainnet, so yes it's a forced upgrade.

Although we will make a new release pretty soon for some quick fixes. I would recommend you to wait that one!

**Comment by astrid19981112** [comment]
Okay, thank you. Can you add a copy in front of the announcement later to explain whether a forced upgrade is required?
