### ISSUE TITLE
How to convert []byte to string

### ISSUE THREAD

**Issue by trybye** [ethereum/go-ethereum#29044]
[] byte : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 8 82 65 87 32 68 69 70 73 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 
it's token's name ` RAW DEFI`,How to filter unuseful chars?

**Comment by rjl493456442** [comment]
You should probably use abi library to decode the value.

Although I have no idea why's your question.

**Comment by trybye** [comment]
> You should probably use abi library to decode the value.
> 
> Although I have no idea why's your question.

```
bytesDateName, err := tokenABI.Pack("name")
	if err != nil {
		fmt.Println(err)
		return err
	}

	bytesName, err := client.CallContract(context.Background(), ethereum.CallMsg{
		From: common.HexToAddress(from),
		To:   &toContract,

		Data: bytesDateName,
	}, nil)
	if err != nil {
		//fmt.Println(err)
		return err
	}
```
I use static call methods
