### ISSUE TITLE
Use proper extension for linux release .xz

### ISSUE THREAD

**Issue by kenshyx** [ethereum/go-ethereum#2904]
#### System information

Geth version: 1.4.10
OS & Version: Linux

#### Expected behaviour
Hello, I've seen that you changed the archive format.
```
$ file geth-Linux64-20160716160600-1.4.10-5f55d95.tar.bz2
geth-Linux64-20160716160600-1.4.10-5f55d95.tar.bz2: XZ compressed data
```
Before this version:
```
$ file geth-Linux64-20160629125400-1.4.9-b7e3dfc.tar.bz2 
geth-Linux64-20160629125400-1.4.9-b7e3dfc.tar.bz2: bzip2 compressed data, block size = 900k
```
I'm using github release as download source in my dapp and it would be great if it would have consistency between format and extension.
#### Actual behaviour
```
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by karalabe** [comment]
Sorry about that. It was probably an error at my side when I packed up the binary for the GitHub page. Hopefully we'll release a next version of Geth in the coming days and I'll double check that the compression is correct.

**Comment by karalabe** [comment]
The current 1.4.11 version should be properly bz2 again. Sorry about the messup.
