### ISSUE TITLE
What  is  the recommended replacement of the j s  option?

### ISSUE THREAD

**Issue by zengh-cropty** [ethereum/go-ethereum#29055]
We were using the js together with a --preload to run geth in a private network using docker.
The main use-case was to mine blocks only when a transaction exists
(Similar to this https://ethereum.stackexchange.com/questions/3151/how-to-make-miner-to-mine-only-when-there-are-pending-transactions and this https://github.com/niksmac/ethereum-scripts/blob/master/src/mining-only-new-txs.js)
But now that the js is deprecated how can we achieve the same?
The only option we found so far, was to run console and use --preload.
Unfortunately, this requires us to also allow tty+std_open in docker which we would like to avoid.
Is there any way to do this?

**Comment by holiman** [comment]
> this requires us to also allow tty+std_open in docker which we would like to avoid.

Why does it require you to do that? That sounds like a bug to me. What happens if you don't ?

**Comment by s1na** [comment]
ACtually the flag we have for it is `--exec`. It will execute the script and return without needing tty. However you have to write the script without callbacks. It `--exec` will not wait for callbacks to finish.
