### ISSUE TITLE
I'm failing to import a testnet blockchain binary file (Bad block #1)

### ISSUE THREAD

**Issue by jjmr007** [ethereum/go-ethereum#2905]
#### System information

Geth version: `1.4.7`
OS & Version: Windows 7

#### Expected behaviour

Import testnet blockchain from a binary file to the testnet database

#### Actual behaviour

Geth preloads the default genesis block. The process ends in the block #1.

#### Steps to reproduce the behaviour

My first try was:

`geth --testnet import ~testnetblockchain.bin`

And geth gave me back:

> I0811 23:59:37.301085 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to C:\Users\MultiEBD\AppData\Roaming\Ethereum\testnet\chaindata
I0811 23:59:37.742111 core/headerchain.go:94] WARNING: Wrote default ethereum genesis block
I0811 23:59:37.742111 core/blockchain.go:206] Last header: #0 [d4e56740.] TD=17179869184
I0811 23:59:37.742111 core/blockchain.go:207] Last block: #0 [d4e56740.] TD=17179869184
I0811 23:59:37.742111 core/blockchain.go:208] Fast block: #0 [d4e56740.] TD=17179869184
I0811 23:59:37.742111 cmd/utils/cmd.go:123] Importing blockchain H:\RESPALDOS\CRYPTO\Ethereum\test11082016.bin
E0811 23:59:38.888176 core/blockchain.go:1128] Bad block #1 (0xad47413137a753b2061ad9b484bf7b0fc061f654b951b562218e9f66505be6ce)
E0811 23:59:38.888176 core/blockchain.go:1129]     Block's parent unknown 0cd786a2425d16f152c658316c423e6ce1181e15c3295826d7c9904cba9ce303
I0811 23:59:38.888176 ethdb/database.go:169] closed db:C:\Users\MultiEBD\AppData\Roaming\Ethereum\testnet\chaindata
Fatal: Import error: invalid block 2500: Block's parent unknown 0cd786a2425d16f152c658316c423e6ce1181e15c3295826d7c9904cba9ce303
Fatal: Import error: invalid block 2500: Block's parent unknown 0cd786a2425d16f152c658316c423e6ce1181e15c3295826d7c9904cba9ce303

Now, `0cd786a2425d16f152c658316c423e6ce1181e15c3295826d7c9904cba9ce303` is the right hash of the MORDEN genesis block. So I thought that I just needed the [genesis.json](https://github.com/ethereum/homestead-guide/blob/master/source/network/test-networks.rst)

My second try was:

`geth --testnet init genesis.json`

And geth gave me: `successfully wrote genesis block and/or chain rule set: c31c07282c5f803da583b8b65f3aa0b5cce411f3ffa6ae11c5e0adb3e057ef4a`

then I try again:

`geth --testnet import ~testnetblockchain.bin`

And geth gave me back:

> I0811 23:29:00.224011 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to C:\Users\MultiEBD\AppData\Roaming\Ethereum\testnet\chaindata
I0811 23:29:00.605032 core/blockchain.go:206] Last header: #0 [c31c0728.] TD=131072
I0811 23:29:00.605032 core/blockchain.go:207] Last block: #0 [c31c0728.] TD=131072
I0811 23:29:00.605032 core/blockchain.go:208] Fast block: #0 [c31c0728.] TD=131072
I0811 23:29:00.605032 cmd/utils/cmd.go:123] Importing blockchain H:\RESPALDOS\CRYPTO\Ethereum\test11082016.bin
E0811 23:29:01.764099 core/blockchain.go:1128] Bad block #1 (0xad47413137a753b2061ad9b484bf7b0fc061f654b951b562218e9f66505be6ce)
E0811 23:29:01.796101 core/blockchain.go:1129]     Block's parent unknown 0cd786a2425d16f152c658316c423e6ce1181e15c3295826d7c9904cba9ce303
I0811 23:29:01.845103 ethdb/database.go:169] closed db:C:\Users\MultiEBD\AppData\Roaming\Ethereum\testnet\chaindata
Fatal: Import error: invalid block 2500: Block's parent unknown 0cd786a2425d16f152c658316c423e6ce1181e15c3295826d7c9904cba9ce303
Fatal: Import error: invalid block 2500: Block's parent unknown 0cd786a2425d16f152c658316c423e6ce1181e15c3295826d7c9904cba9ce303

And I don't know what I'm doing wrong.
May be I need the right MORDEN genesis.json file yet.
Or may be that I need to use some geth command to tell it not to write the default genesis block in the chaindata, but import it from the testnetblockchain file I have.

Any suggestion?

Thanks =)

**Comment by Hellsegga** [comment]
Here is what I understand from the code:
- the `import` command ignores the testnet flag and loads the default genesis block (for the production network), and then of course when it tries to import testnet blocks on top of the prod genesis block it fails
- using the `init` command would work, but there is a small problem here: when testnet is initialized (for instance if you run `geth --testnet`), it does 2 things: it loads the genesis block but it also sets the initial transaction nonce (http://ethereum.stackexchange.com/questions/3215/testnet-first-transaction-nonce), which the `init` command does not seem to do. This nonce makes it into the state trie root because of the allocations made in the genesis file, and since the state trie root is included in the block header it results in a different block hash and thus running `import` after `init` for testnet blocks fails

I'll see if I can propose a fix for this.

**Comment by karalabe** [comment]
Thanks for this. I also notices while developing hive for the fork but didn't have time to fix it. Thanks also for the detailed analysis :)

**Comment by jjmr007** [comment]
Thank you!

**Comment by karalabe** [comment]
Closing as fixed on develop :)
