### ISSUE TITLE
Ethereum gas fees....high? Or just okay?

### ISSUE THREAD

**Issue by Thatngga** [ethereum/go-ethereum#29064]
Greetings,
I have been always marveled as to why ethereum is the only crypto project with "outrageous gas fees, asked slot of people who I consider to be more learned than me in the crypto space, but I still haven't gotten a satisfying answer....
I would appreciate a feedback thank you

**Comment by MalackforReal** [comment]
Hi

**Comment by karalabe** [comment]
That's out of the scope of this repo really. FWIW, L2s are the current best idea for scaling Ethereum where fees are significantly lower and the upcoming hard fork in 2 weeks will further make L2s significantly cheaper. There's no immediate solution to make L1 cheaper without problematic state issues, but there's also less need as long as L2s can do their thing.
