### ISSUE TITLE
Expose TxIndexingErr in the ethclient API

### ISSUE THREAD

**Issue by pavelnikolov** [ethereum/go-ethereum#29063]
# Background
My team uses the Go Ethereum client and the client's implementation is forcing us to write non-idiomatic Go code. For example, we invoke the [TransactionReceipt](https://github.com/ethereum/go-ethereum/blob/93c541ad563124e81d125c7ebe78938175229b2e/ethclient/ethclient.go#L307-L314) method of the `ethclient.Client`. This simple method looks like this:

```go
// TransactionReceipt returns the receipt of a transaction by transaction hash.
// Note that the receipt is not available for pending transactions.
func (ec *Client) TransactionReceipt(ctx context.Context, txHash common.Hash) (*types.Receipt, error) {
	var r *types.Receipt
	err := ec.c.CallContext(ctx, &r, "eth_getTransactionReceipt", txHash)
	if err == nil && r == nil {
		return nil, ethereum.NotFound
	}
	return r, err
}

```
It is just a wrapper around `eth_getTransactionReceipt`. After reading [the docs](https://ethereum.org/en/developers/docs/apis/json-rpc#eth_gettransactionreceipt) I found this:
> Returns Object - A transaction receipt object, or null when no receipt was found

The documentation doesn't say anything about the error that gets returned though. In our code we want to differentiate between a transaction that was not found and a pending one (i.e. when the rpc client returns a [TxIndexingError](https://github.com/ethereum/go-ethereum/blob/93c541ad563124e81d125c7ebe78938175229b2e/internal/ethapi/errors.go#L61)) . However, this is impossible using `errors.Is` because that error is defined inside of the `internal` package of this repo and therefore we are not allowed to access it. This is in turn forces us to do checks like:
```go
if strings.Contains(err.Error(), "transaction indexing is in progress") {
```
`ethclient` does a good job with the `ethereum.NotFound` error and we can beautifully check in our code, like below: 
```go
errors.Is(err, ethereum.NotFound)
```
# Expected behavior
After calling `TransactionReceipt` method and getting an error the caller should be able to check the error type like this:
```go
    if errors.Is(err, ethereum.NotFound) {
         // handle not found
    } else if errors.Is(err, ethclient.TxIndexingError) {
        // handle pending
    } else {
        // handle unknown error
    }
```

# Proposed solution

Make the `TxIndexingErr` public in the `ethclient` package. Or alternatively define `ethereum.Pending` error. This way we can use [the Go-idiomatic way of error testing](https://go.dev/blog/go1.13-errors#customizing-error-tests-with-is-and-as-methods).
This would not be a breaking change and would allow users of the API to distinguish between different error types without having to use string comparisons.

**Comment by rjl493456442** [comment]
Could you please try `ethapi.TxIndexingError`?

**Comment by karalabe** [comment]
Translating errors across the RPC would require at minimum errors codes being specced for the API, which they aren't unfortunately.

**Comment by s1na** [comment]
@pavelnikolov nooo you should at least use geth's GraphQL API!! 😄

**Comment by karalabe** [comment]
Unfortunately have to close this. Standardising the errors codes if the only way out that I see and that's not an effort people really prioritise.
