### ISSUE TITLE
The memory preallocated for WriteBatch is always smaller than the actual size in nodebuffer

### ISSUE THREAD

**Issue by Fynnss** [ethereum/go-ethereum#29061]
#### System information

Geth version:  1.13
CL client & version: none
OS & Version: Windows/Linux/OSX
Commit hash : master

#### Expected behaviour

https://github.com/ethereum/go-ethereum/blob/b87b9b45331f87fb1da379c5f17a81ebc3738c6e/triedb/pathdb/nodebuffer.go#L209-L236

Pre-allocated memory to avoid re-allocated.

#### Actual behaviour

The calculated size in Nodebuffer is actually slightly smaller than the actual size, which can result in large memory re-allocate(256M+) during the batch.Put process, affecting performance.

#### Steps to reproduce the behaviour

add detailed log to reproduce

```
log.Debug("Persisted pathdb nodes", "nodes", len(b.nodes), "pre-bytes", common.StorageSize(b.size), "bytes", common.StorageSize(size), "elapsed", common.PrettyDuration(time.Since(start)))
```

#### Backtrace

none.

**Comment by rjl493456442** [comment]
We construct the entire database key as we fulfill the write batch, including the database prefix and the storage owner prefix which are not counted in size. We need to twist the size a bit.
