### ISSUE TITLE
Supporting signed transaction in eth_sendTransaction

### ISSUE THREAD

**Issue by colinlyguo** [ethereum/go-ethereum#29075]
# Rationale

`eth_sendTransaction` with signature (e.g., a JSON string with valid `v`, `r`, `s`, `yParity` fields), it would be useful to let the node relay signed transactions without running a local node with a signer.

Of course, it can also be achieved using `eth_sendRawTransaction`, but curl command of `eth_sendTransaction` is more readable than `eth_sendRawTransaction`.

# Implementation

Do you have ideas regarding the implementation of this feature?
Add signature checks before https://github.com/ethereum/go-ethereum/blob/93c541ad563124e81d125c7ebe78938175229b2e/internal/ethapi/api.go#L1799 and https://github.com/ethereum/go-ethereum/blob/93c541ad563124e81d125c7ebe78938175229b2e/internal/ethapi/api.go#L478.

Are you willing to implement this feature? Y.

**Comment by jwasinger** [comment]
The arguments of `eth_sendTransaction` can't be changed because it will break backwards-compatibility.  also, in my opinion the rationale of making the API call more readable for curl is not a strong enough reason to warrant a new method.
