### ISSUE TITLE
Differences in write option between leveldb and pebble.

### ISSUE THREAD

**Issue by will-2012** [ethereum/go-ethereum#29088]
LevelDB write option in `ethdb/leveldb/leveldb.go`:
```go
// Put inserts the given value into the key-value store.
func (db *Database) Put(key []byte, value []byte) error {
	return db.db.Put(key, value, nil)
}
```
PebbleDB write option in `ethdb/pebble/pebble.go`:
```go
// Put inserts the given value into the key-value store.
func (d *Database) Put(key []byte, value []byte) error {
	d.quitLock.RLock()
	defer d.quitLock.RUnlock()
	if d.closed {
		return pebble.ErrClosed
	}
	return d.db.Set(key, value, d.writeOptions)
}
```

The option is not specified in leveldb engine, the default writing mode is async, And the option is specified in pebble engine, the default writing mode is sync. Please correct me if I understand wrong.

**Comment by karalabe** [comment]
Leveldb was kind of left in for legacy purposes until everyone migrates over to Pebble. Whilst there's no particular reason to forcefully drop LevelDB, we also stopped maintaining it. The upstream project (go-eveldb) was abandoned, the latest upstream code is unstable, they stopped accepting out fixes. At this point we just can't really care about it any more.

**Comment by will-2012** [comment]
https://github.com/ethereum/go-ethereum/pull/27615
