### ISSUE TITLE
Mist won't install with Homebrew

### ISSUE THREAD

**Issue by joeykrug** [ethereum/go-ethereum#291]
I get the following error:

MacBook-Pro:augur-serpent joeykrug2$ brew install go-ethereum
==> Installing go-ethereum from caktux/homebrew-ethereum
==> Cloning https://github.com/ethereum/go-ethereum.git
Updating /Library/Caches/Homebrew/go-ethereum--git
==> Checking out branch master
==> go env
==> go get -v -u -d github.com/ethereum/go-ethereum/ethereum
package github.com/ethereum/go-ethereum/ethereum
	imports github.com/ethereum/go-ethereum/ethereum
	imports github.com/ethereum/go-ethereum/ethereum: cannot find package "github.com/ethereum/go-ethereum/ethereum" in any of:
	/usr/local/opt/go/libexec/src/github.com/ethereum/go-ethereum/ethereum (from $GOROOT)
	/private/tmp/go-ethereum-fH5uch/src/github.com/ethereum/go-ethereum/ethereum (from $GOPATH)

**Comment by tgerring** [comment]
It looks like the build script for the Homebrew channel is old, as `github.com/ethereum/go-ethereum/ethereum` was moved some time ago.

This issue will probably get more attention over at https://github.com/ethereum/homebrew-ethereum/issues. In the meantime, [manual build on Mac](https://github.com/ethereum/go-ethereum/wiki/Building-Instructions-for-Mac#option-2-manual-installation) is relatively simple if you'd like to give it a try.

**Comment by joeykrug** [comment]
Cool will close & make an issue there

**Comment by caktux** [comment]
That was fixed a while back, you just had to `brew update`.
