### ISSUE TITLE
How to get contract error messages from the Geth level

### ISSUE THREAD

**Issue by SipengXie** [ethereum/go-ethereum#29112]
``` solidity
pragma solidity >=0.7.0 <0.9.0;
contract Keccak {
    constructor () {
        require(1==2,"bad");
    }
```
When I run this code on Geth, the transaction reverts without any return data or logs. How to get the string "bad"  from Geth?

**Comment by karalabe** [comment]
You can trace the transaction to get the revert reason (for example with the call_tracer).

**Comment by SipengXie** [comment]
So is the tracer of geth responsible for the revert reason?
