### ISSUE TITLE
how exports my private key

### ISSUE THREAD

**Issue by 362228416** [ethereum/go-ethereum#2911]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
I use personal.newAccount('123123'), and address is 57fefd0a96d7d58ef3b7e0cb31383496a795e789, how convert to private key?? geth client has command?

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
There is no way to export the unencrypted private key. The encrypted one is stored in your data directory in the `keystore` folder, which has a standardized format that all clients should be able to handle. Just try to load that into another client and you should be fine.
