### ISSUE TITLE
Running PoA Clique

### ISSUE THREAD

**Issue by etherbase404** [ethereum/go-ethereum#29111]
Hi Karalabe, Is it possible to run Geth PoA Clique as private network in production mode? I mean the bootnode being run properly in that mode?

More Answers needed on this:
- Is it possible to reduce the block time below 1 second?
- Is it possible to have fee less transactions? (Sending transactions with gas limit & gas price 0)
- Is it possible to add more signers once the chain is run or only at start

Can those things be edited? how?

**Comment by karalabe** [comment]
We are close to removing Clique support from Geth. You'll need to run a proper PoS chain to use Geth in the future.

**Comment by etherbase404** [comment]
I totally understand Clique support will be removed from Geth but are those things asked possible? I don't want to connect to mainnet :/ Do you guys provide technical support services for third parties? can that be made possible? Thanks Peter.
