### ISSUE TITLE
Post-merge network, but no beacon client seen. Please launch one to follow the chain!

### ISSUE THREAD

**Issue by qstrrrr** [ethereum/go-ethereum#29138]
Hi Guys, I try to get my node working with the following:
geth \
--datadir $HOME/geth-linea-data \
--networkid 59144 \
--rpc.allow-unprotected-txs \
--txpool.accountqueue 50000 \
--txpool.globalqueue 50000 \
--txpool.globalslots 50000 \
--txpool.pricelimit 1000000 \
--txpool.pricebump 1 \
--txpool.nolocals \
--http --http.addr '127.0.0.1' --http.port 8545 --http.corsdomain '*' --http.api 'web3,eth,txpool,net' --http.vhosts='*' \
--ws --ws.addr '127.0.0.1' --ws.port 8546 --ws.origins '*' --ws.api 'web3,eth,txpool,net' \
--bootnodes "enode://ca2f06aa93728e2883ff02b0c2076329e475fe667a48035b4f77711ea41a73cf6cb2ff232804c49538ad77794185d83295b57ddd2be79eefc50a9dd5c48bbb2e@3.23.106.165:30303,enode://eef91d714494a1ceb6e06e5ce96fe5d7d25d3701b2d2e68c042b33d5fa0e4bf134116e06947b3f40b0f22db08f104504dd2e5c790d8bcbb6bfb1b7f4f85313ec@3.133.179.213:30303,enode://cfd472842582c422c7c98b0f2d04c6bf21d1afb2c767f72b032f7ea89c03a7abdaf4855b7cb2dc9ae7509836064ba8d817572cf7421ba106ac87857836fa1d1b@3.145.12.13:30303" \
--syncmode full \
--metrics \
--verbosity 3

And i receive :
WARN [03-01|14:47:47.153] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [03-01|14:52:47.192] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [03-01|14:57:47.267] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [03-01|15:02:47.305] Post-merge network, but no beacon client seen. Please launch one to follow the chain!

Any ideas what to do?

**Comment by MariusVanDerWijden** [comment]
You need a consensus client like prysm or lighthouse in addition to geth. There are a bunch of tutorials on the internet on how to set it up

**Comment by rjl493456442** [comment]
Check the [doc](https://geth.ethereum.org/docs/getting-started/consensus-clients) for more details!
