### ISSUE TITLE
Geth client prompts warning when starting “Head state missing, repairing ”

### ISSUE THREAD

**Issue by 0xZonh** [ethereum/go-ethereum#29133]
Due to unknown reasons, the node machine was down and stopped running for a long time. Today I tried to start Geth. The console showed the warning log "Head state missing, repairing number=10,460,369 hash=b0791e..b3f0b5 snaproot=023a90..91fcaf". Next, I started Geth. time command

`geth --goerli --syncmode=fast --http --http.api "eth,net,web3,engine" --ws --ws.api "eth,net,web3,engine" --ws.origins "* " --authrpc.vhosts="localhost" --authrpc.jwtsecret=${xxx} --db.engine=pebble --rpc.enabledeprecatedpersonal.`

Check other documents. The default synchronization method of geth is snap mode. How long will it take for the node to return to normal? Or do I need to change the sync mode to full

geth version:
![image](https://github.com/ethereum/go-ethereum/assets/110391762/4c7ce592-71d8-4666-b135-9af93e50b4d1)

geth logs:
![image](https://github.com/ethereum/go-ethereum/assets/110391762/0e757fca-e3d3-455a-ace9-4428a322ce54)

**Comment by weiihann** [comment]
If I recall correctly, the Goerli network is already deprecated. So try with other testnets like Holesky.

**Comment by 0xZonh** [comment]
> If I recall correctly, the Goerli network is already deprecated. So try with other testnets like Holesky.

ha? Is there any corresponding documentation?

**Comment by weiihann** [comment]
What are you trying to do?

**Comment by karalabe** [comment]
Head state missing usually means an unclean shutdown. With the block receipts error, it kind of feels soemthing got borked pretty well. Iád maybe suggest a resync at this point.

FWIW, you should probably resync with the master branch which by default uses `path` database scheme, which is not so susceptible to state loss during crashes.
