### ISSUE TITLE
Fatal: Failed to register the Ethereum service: snap sync not supported with snapshots disabled

### ISSUE THREAD

**Issue by Adewagold** [ethereum/go-ethereum#29164]
I am currently trying to upgrade our geth node to V1.13.13 but it's failing to start based on this log. The syncmode used before now is set to full in the config.toml file 
```
geth.toml: |
            [Eth]
            NetworkId = 5
            SyncMode = "full"
```
I would like to know if there's a missing flag required for this node or if simply setting the syncmode to snap will resume syncing. As you can see in the logs below, we have some existing blocks up to `10,386,881`.

```
WARN [03-05|00:35:52.523] Switch sync mode from full sync to snap sync reason="snap sync incomplete"
5-3-2024 00:35:52.523
Fatal: Failed to register the Ethereum service: snap sync not supported with snapshots disabled
5-3-2024 00:35:52.523
Fatal: Failed to register the Ethereum service: snap sync not supported with snapshots disabled
5-3-2024 00:35:52.486
INFO [03-05|00:35:52.486] Regenerated local transaction journal transactions=0 accounts=0
5-3-2024 00:35:52.485
INFO [03-05|00:35:52.485] Loaded most recent local snap block number=10,386,881 hash=33a214..e3a06a td=10,790,000 age=1mo2w3d
```

**Comment by rjl493456442** [comment]
You have to enable the snapshot. My hunch is you might disabled the snapshot in your config somehow as it's enabled by default. You can choose to add `--snapshot=true` in your command line flags.
