### ISSUE TITLE
apitypes.SendTxArgs hasn't been updated with 4844 fields

### ISSUE THREAD

**Issue by Tristan-Wilson** [ethereum/go-ethereum#29161]
# Rationale

There is a comment on `apitypes.SendTxArgs` saying that it has its fields manually synced with `ethapi.TransactionArgs` but it is missing the blob-related fields:

* https://github.com/ethereum/go-ethereum/blob/ca473b81cbe4a96cde4e8424c49b15ab304787bb/signer/core/apitypes/types.go#L82
* https://github.com/ethereum/go-ethereum/blob/ca473b81cbe4a96cde4e8424c49b15ab304787bb/internal/ethapi/transaction_args.go#L67

# Implementation

Do you have ideas regarding the implementation of this feature? 
Yes

Are you willing to implement this feature? 
Sure, but I'm not sure if it just as simple as copying the fields or if there is more to it than that.

**Comment by s1na** [comment]
Fixed by #28976

**Comment by fjl** [comment]
It's in now, and fix was released in v1.14
