### ISSUE TITLE
goerli node we deployed is stuck at height 10641185

### ISSUE THREAD

**Issue by hanzhenlong1314** [ethereum/go-ethereum#29173]
Hello, the height of the goerli node we deployed is stuck at height 10641185. We have upgraded the version to v1.13.14 and the consensus layer to https://github.com/prysmaticlabs/prysm/releases/tag/v5.0.0, but currently The altitude has not been restored, and the execution layer shows that the peer cannot be found.

**Comment by rjl493456442** [comment]
Can you share the logs from geth?

> the execution layer shows that the peer cannot be found.

probably it need to take a while for finding peers.

**Comment by hanzhenlong1314** [comment]
> Can you share the logs from geth?
> 
> > the execution layer shows that the peer cannot be found.
> 
> probably it need to take a while for finding peers.
Hello, but the node has not been synchronized for more than two hours. This is the log.   
prysm log：
![image](https://github.com/ethereum/go-ethereum/assets/25896081/a13a2038-e63b-4ec6-b400-83a8cc749643)
Execution layer log：
![image](https://github.com/ethereum/go-ethereum/assets/25896081/71e918ed-840e-4397-ac9c-69b8f9a00889)

**Comment by rjl493456442** [comment]
You can try to restart your beacon client.

**Comment by junghyun0783** [comment]
@hanzhenlong1314 
I have the same symptoms. Has it been resolved?
I am also restarting the beacon after upgrading the geth version. It doesn't work yet. Has it been resolved?

**Comment by hanzhenlong1314** [comment]
> You can try to restart your beacon client.

I restarted the beacon node, but it seems to have no effect

**Comment by junghyun0783** [comment]
@rjl493456442 
Both beacon and geth are up to date.
But it doesn't work. Why is this happening?

**Comment by rjl493456442** [comment]
It's actually not the issue of geth. Geth is waiting the signals from the beacon node while beacon node regards the geth as unusable. Probably we should open the ticket in prysm's repo?

**Comment by MariusVanDerWijden** [comment]
Goerli is deprecated and a lot of stakers have stopped running their node, thus there is a lot of confusion about the correct chain for beacon nodes. I think this issue results from jitters on the beacon chain and is not an execution layer issue

**Comment by hanzhenlong1314** [comment]
![image](https://github.com/ethereum/go-ethereum/assets/25896081/e58530b2-cc99-4159-83f1-814851483a5c)
I see that all three RPCs are good and the height is normal, which is very strange.

**Comment by junghyun0783** [comment]
So, should we just wait?
Is there any solution?

**Comment by hanzhenlong1314** [comment]
> @rjl493456442 Can I change the geth version to "Geth 1.14.0"? Let's give it a try.

@junghyun0783 hello, have you solved this problem?

**Comment by junghyun0783** [comment]
@rjl493456442 
No... it doesn't solve it....
Have you solved it...
Even upgrading the version did not solve the problem.

**Comment by hanzhenlong1314** [comment]
I downgraded prysm to v4.2.1 but it didn't work https://github.com/prysmaticlabs/prysm/releases/tag/v4.2.1

**Comment by junghyun0783** [comment]
@hanzhenlong1314 
Have you tried downgrading to version 4.2.0?

**Comment by hanzhenlong1314** [comment]
> @hanzhenlong1314 Have you tried downgrading to version 4.2.0? Give it a try~ It seems like it might work, right? Block count increases.

hello,Have your nodes been synchronized after switching to version 4.2.0?

**Comment by junghyun0783** [comment]
@hanzhenlong1314 
hello!
No... synchronization was in progress but stopped at block 10,641,470...
I don't know why.

**Comment by 0xZonh** [comment]
I had the same problem but my height was 10,641,327... I have also restarted geth and prysm clients, but synchronization stops every time it reaches 10,641,327.

**Comment by junghyun0783** [comment]
@0xZonh 
A new version has been released from prysm.
Please proceed after upgrading the version.
Once synchronization is in progress.

**Comment by hanzhenlong1314** [comment]
> @0xZonh A new version has been released from prysm. Please proceed after upgrading the version. Once synchronization is in progress.

got it,thanks

**Comment by rjl493456442** [comment]
Looks like upgrading the beacon node should resolve the issue! Feel free to reopen a new one if this issue shows up again.
