### ISSUE TITLE
Please tell us your node information! 

### ISSUE THREAD

**Issue by junghyun0783** [ethereum/go-ethereum#29182]
The Goerli testnet is currently not running.

I am currently running Ethereum Goerli with geth 1.13.14 and prysm 5.0.0. But now synchronization has stopped at block 10641185.
Anyone running a testnet with Ethereum Goerli?
Can you tell me the geth version and prysm version?

**Comment by 0xZonh** [comment]
I have the same problem. I upgraded geth client 1.13.14 and prysm client 5.0.0. The synchronization stopped when it reached height 10,641,327... I restarted geth and prysm client, but it didn't solve the problem. Every time Synchronization will stop when reaching 10,641,327.

**Comment by junghyun0783** [comment]
@0xZonh 
It's not a geth problem. It's a prysm problem.
Please proceed after upgrading to https://github.com/prysmaticlabs/prysm/releases/tag/v5.0.1-rc.3.
Once synchronization is in progress.
