### ISSUE TITLE
geth version > v1.13.14 (docker "latest" tag) doesn't start with Clique POA.

### ISSUE THREAD

**Issue by lesaux** [ethereum/go-ethereum#29194]
Geth v1.13.14 starts fine with a clique POA genesis configuration.

Geth "latest" docker images fails to start with the same configuration with the following error log:

```
Fatal: Failed to register the Ethereum service: only PoS networks are supported, please transition old ones with Geth v1.13.x
```

**Comment by karalabe** [comment]
It's literally in the error mesage.

Geth v1.13.14 drops support for non-PoS networks. You need to "merge" your Clique chain into a PoS one to be able to use Geth v1.14 and going forward.

We dropped PoW one year ago and promised that PoA will also go within half a year. Took us a bit longer, but it's gone now.

https://twitter.com/peter_szilagyi/status/1651593996483870724

**Comment by congmucc** [comment]
> It's literally in the error mesage.
> 
> Geth v1.13.14 drops support for non-PoS networks. You need to "merge" your Clique chain into a PoS one to be able to use Geth v1.14 and going forward.
> 
> We dropped PoW one year ago and promised that PoA will also go within half a year. Took us a bit longer, but it's gone now.
> 
> https://twitter.com/peter_szilagyi/status/1651593996483870724

I'm a web3 beginner and I want to know how to run a private chain with pos, I use the relevant command here to run but it always doesn't work

```
{
  "config": {
    "chainId": 8888,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0
  },
  "alloc": {
    "0x0000000000000000000000000000000000000001": {
      "balance": "111111111"
    },
    "0x0000000000000000000000000000000000000002": {
      "balance": "222222222"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "difficulty": "0x20000",
  "extraData": "",
  "gasLimit": "0x2fefd8",
  "nonce": "0x0000000000000042",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}
```

```cmd
geth --datadir "data" init genesis.json
```

```cmd
geth --datadir data --networkid 8888 console 2>geth.log
```

He always gets an error like this: 'Fatal: Failed to register the Ethereum service: only PoS networks are supported, please transition old ones with Geth v1.13.x'

**Comment by congmucc** [comment]
> It's literally in the error mesage.
> 
> Geth v1.13.14 drops support for non-PoS networks. You need to "merge" your Clique chain into a PoS one to be able to use Geth v1.14 and going forward.
> 
> We dropped PoW one year ago and promised that PoA will also go within half a year. Took us a bit longer, but it's gone now.
> 
> https://twitter.com/peter_szilagyi/status/1651593996483870724



> It's literally in the error mesage.
> 
> Geth v1.13.14 drops support for non-PoS networks. You need to "merge" your Clique chain into a PoS one to be able to use Geth v1.14 and going forward.
> 
> We dropped PoW one year ago and promised that PoA will also go within half a year. Took us a bit longer, but it's gone now.
> 
> https://twitter.com/peter_szilagyi/status/1651593996483870724

I don't know how the latest version works
