### ISSUE TITLE
Steep increase in fork-check drops

### ISSUE THREAD

**Issue by aliensyntax** [ethereum/go-ethereum#2919]
I'm running Ubuntu 15.10-Wily and just recently updated from `geth 1.4.10` to `1.4.11` using the PPA. I've since noticed a steep increase in the number of dropped headers. I believe there may have been an issue with the PPA since  `geth --version` still indicates `v.1.4.10`. Is this output normal?

> I0818 18:50:31.884866 eth/downloader/downloader.go:320] Block synchronisation started
> I0818 18:50:32.896199 eth/handler.go:295] Peer 3806e6f2b68b6e8b [eth/63]: timed out DAO fork-check, dropping
> I0818 18:50:39.919580 eth/handler.go:295] Peer 572f095edd2ac0a5 [eth/63]: timed out DAO fork-check, dropping
> I0818 18:51:00.852308 eth/handler.go:295] Peer 522af88b556fe141 [eth/63]: timed out DAO fork-check, dropping
> I0818 18:51:16.013747 eth/handler.go:295] Peer 10cf6efefbc9b652 [eth/63]: timed out DAO fork-check, dropping
> I0818 18:52:19.672551 eth/handler.go:295] Peer a7127e452ba14ac5 [eth/63]: timed out DAO fork-check, dropping
> I0818 18:52:43.396504 eth/handler.go:295] Peer c3c1f2be429e6165 [eth/63]: timed out DAO fork-check, dropping
> I0818 18:52:58.259490 eth/handler.go:295] Peer c4ad79d819531f7f [eth/63]: timed out DAO fork-check, dropping
> I0818 18:53:05.222797 eth/handler.go:295] Peer 3806e6f2b68b6e8b [eth/63]: timed out DAO fork-check, dropping
> I0818 18:53:28.767124 eth/handler.go:295] Peer 28bcec2b42d99733 [eth/63]: timed out DAO fork-check, dropping
> I0818 18:53:40.496210 eth/handler.go:295] Peer 22eece380d7b4c75 [eth/63]: timed out DAO fork-check, dropping
> I0818 18:54:19.850285 eth/handler.go:295] Peer 4dc9f19d8f1b36d9 [eth/63]: timed out DAO fork-check, dropping
> I0818 18:55:14.358316 eth/handler.go:295] Peer a327e0abb331228e [eth/63]: timed out DAO fork-check, dropping
> I0818 18:55:49.491847 eth/handler.go:295] Peer 28bcec2b42d99733 [eth/63]: timed out DAO fork-check, dropping
> I0818 18:55:53.040303 eth/handler.go:295] Peer 6cb867ef9041ffc2 [eth/63]: timed out DAO fork-check, dropping
> I0818 18:55:58.158325 eth/handler.go:295] Peer 3c6b4c0d66bb38a2 [eth/63]: timed out DAO fork-check, dropping
> I0818 18:56:02.375265 core/blockchain.go:963] imported 384 block(s) (0 queued 0 ignored) including 3368 txs in 4m41.676630496s. #2084826 [d77eef62 / bbd3640f]
> I0818 18:58:13.703071 eth/handler.go:295] Peer 129a1bb1e3beb1b6 [eth/63]: timed out DAO fork-check, dropping
> I0818 18:59:21.694157 eth/handler.go:295] Peer 22f1931c0eeaaee7 [eth/63]: timed out DAO fork-check, dropping
> I0818 18:59:35.022993 eth/handler.go:295] Peer c609fafc8330605d [eth/63]: timed out DAO fork-check, dropping
> I0818 19:02:25.668324 eth/handler.go:295] Peer 7603e0ec309a49e3 [eth/63]: timed out DAO fork-check, dropping
> I0818 19:02:32.836338 eth/handler.go:295] Peer 4dc9f19d8f1b36d9 [eth/63]: timed out DAO fork-check, dropping
> I0818 19:02:33.490357 eth/handler.go:295] Peer 841504372d703341 [eth/63]: timed out DAO fork-check, dropping
> I0818 19:04:09.267878 eth/handler.go:295] Peer c3c1f2be429e6165 [eth/63]: timed out DAO fork-check, dropping
> I0818 19:04:53.033874 eth/handler.go:295] Peer 8bd0489d4580f336 [eth/63]: timed out DAO fork-check, dropping
> I0818 19:05:21.430902 eth/handler.go:295] Peer 583f0f3cabc41c9d [eth/63]: timed out DAO fork-check, dropping
> I0818 19:06:49.660920 eth/handler.go:295] Peer 77bd664e89c44b8e [eth/63]: timed out DAO fork-check, dropping
> I0818 19:08:11.211791 eth/handler.go:295] Peer cd6ce85feeb5c1af [eth/63]: timed out DAO fork-check, dropping
> I0818 19:18:51.573434 core/blockchain.go:963] imported 2048 block(s) (0 queued 0 ignored) including 12797 txs in 22m48.980800991s. #2086874 [8ec46cd5 / 8ab656ca]

**Comment by karalabe** [comment]
Are you sure you updated correctly? I just looked up the Ethereum PPA (https://launchpad.net/~ethereum/+archive/ubuntu/ethereum/+packages) and manually downloaded the latest build for Wiley (https://launchpad.net/~ethereum/+archive/ubuntu/ethereum/+build/10633656) and I get the correct version strings:

```
$ ./geth version
Geth
Version: 1.4.11-stable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.5.1
OS: linux
```

**Comment by aliensyntax** [comment]
Turns out I had to fix a conflict in my apt sources. Initially, I flagged `--force-yes` for `apt-get upgrade`. I assume this is what introduced the unusual behavior. After reapplying the PPA and obtaining the same version strings as you, the fork-checks have returned to their expected frequency.

**Comment by karalabe** [comment]
Awesome :) Closing then :)
