### ISSUE TITLE
GasPrice and EffectiveGasPrice

### ISSUE THREAD

**Issue by JourneyToSilius** [ethereum/go-ethereum#29202]
I have read that EffectiveGasPrice appeared after the London fork in 2021

In the tx object, does Gasprice stops being populated after 2021 and EffectiveGasPrice is used instead, or are both filled regardless ?
If both are filled, are both the same value or are they different values ?

**Comment by fjl** [comment]
Legacy transactions have a fixed `GasPrice`. This is still true today.

The London fork introduced support for a new transaction type, it's called the 'dynamic-fee transaction' in geth. For these transactions, the true gas price is determined at the time of execution, and the *effective* gas price is stored in the *transaction receipt*.
