### ISSUE TITLE
Validate txs inside a new block from other nodes.

### ISSUE THREAD

**Issue by ObscureLin** [ethereum/go-ethereum#29211]
I was wondering which part of the Geth client's codebase implements the validation of new blocks from other nodes by executing its transactions inside. I checked the /core/block_validator.go, it seems not to execute the txs. Thanks for your help.

**Comment by karalabe** [comment]
core/state_transition.go

**Comment by ObscureLin** [comment]
Thank you, but what I meant to ask about was the path of function calls. Today, as I reread the code, I found that whether it's a block mined locally or received from other nodes, it goes through the `block_fetcher` in the `eth` package to call the `blockchain.insertChain`, which in turn calls `Process` to execute transactions. This issue is solved now, thanks a lot. 👍 💯
