### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c cd /go-ethereum && go run build/ci.go install -static ./cmd/geth" did not complete successfully

### ISSUE THREAD

**Issue by wzl521** [ethereum/go-ethereum#29239]
ERROR: failed to solve: process "/bin/sh -c cd /go-ethereum && go run build/ci.go install -static ./cmd/geth" did not complete successfully！
I modified the code of geth, and when I tried to rebuild the image, I encountered the error mentioned above. How can I resolve this?

**Comment by karalabe** [comment]
You didn't give us any error messages, so there's nothing we can see or say.
