### ISSUE TITLE
Lost peer connections after 1 month

### ISSUE THREAD

**Issue by Firescar96** [ethereum/go-ethereum#2925]
#### System information

Geth version: `1.4.10` and `1.4.11`
OS & Version: geth docker running on coreos on a vm in azure
`docker run --rm --net host -ti <username>/geth:1.4.11`

#### Expected behaviour
Geth uses the bootstrap nodes to find and maintain connections to peers on a variety of ports. It reaches `--maxpeers=25` within a couple minutes and stays there.

#### Actual behaviour
Geth quickly gets 1-3 peers on startup, and over the course of at least an hour slowly makes it's way to 13 peers. Then within a month (but sometimes as little as a couple days) the peer count drops to 0 and geth has to be restarted to resync. The exact peers in the list after restart differs, but there is never more than 13 and they are almost exclusively on remote port 30303.

#### Steps to reproduce the behaviour
This may not actually be an issue, my setup on azure (details to follow) may be incompatible with the indended behaviour of geth. If it is an issue, then it's not just a bug in just geth, ipfs/p2p is also using an implementation of Kademlia and appears to have the same trouble. Although, there are differences in how many peers are found, what port they are found on, and how long before they are all lost.

##### Azure VM setup
The vm is running on azure without a public ip address. All outbound connections are allowed, so the initial connection into the network works. Additionally, when I give the vm a public IP geth runs just fine and doesn't lose peers over time, but without the public ip it does not. If possible it's preferable to run the node without a public ip to mitigate hacks.

But I'm not sure if that's any more secure than using a public ip and setting azure to block all inbound connections on ports other than 30303 (which geth is listening on).

**Comment by fjl** [comment]
> but there is never more than 13

This is because the max number of peers is split equally into 'accepted' and 'dialed' connections. Since nobody can connect to you, you won't get any more connections.

> Then within a month (but sometimes as little as a couple days) the peer count drops to 0

This sounds like a real issue.

Please be aware that UDP connectivity needs to work, did you open UDP as well?

**Comment by Firescar96** [comment]
UDP and TCP are both open in the azure network security group.

Do you have any thoughts to using a public IP and blocking all the other inbound ports?

**Comment by fjl** [comment]
I don't think there is anything special about the initial search. I'll have to think about this a bit.

> Do you have any thoughts to using a public IP and blocking all the other inbound ports?

I would recommend using a public IP.

**Comment by karalabe** [comment]
1.4.11 does include quite a few sync fixes which could affect peer anomalies. You be nice if you could do a `debug.vmodule("downloader=6")` the next time when you drop to zero and wait a bit for logs. I'm really curious what might be causing this but I've no way to repro them.

**Comment by Firescar96** [comment]
Geth 1.4.10 was pretty bad. I thought I tried geth 1.4.11 earlier, but didn't update properly. We are now running 1.4.11 with a public IP and trialing a few 1.4.11 instances behind a NAT. I'll let you know how it goes in a month.

**Comment by Firescar96** [comment]
The nodes are stable, gethv1.4.11 fixed the problem.Thanks.
CC @hermanjunge
