### ISSUE TITLE
It's been over 5 hours since we left Cancun. It no longer syncs at all.

### ISSUE THREAD

**Issue by h6dworker** [ethereum/go-ethereum#29250]
#### System information

Geth Version: 1.13.14-stable

Latest Prysm version is v5.0.1. Beacon chain is up to date. 

#### Expected behaviour
/bin/bash /home/intel/consensus/prysm/prysm.sh beacon-chain \
        --datadir=/mnt/Beacon/eth2 \
        --execution-endpoint=/mnt/Samsung/ethereum/geth.ipc \
        --suggested-fee-recipient=0x655fa8459044a0aaab594cc05577497750c53dc5

ExecStart=/usr/bin/geth \
        --http \
        --http.port 8545 \
        --http.addr 192.168.201.34 \
        --datadir "/mnt/Samsung/ethereum" \
        --http.api eth,net,engine,admin,web3,personal

#### Backtrace

````
 3月 14 05:31:53 i5giga34 geth[3532920]: WARN [03-14|05:31:53.027] Served engine_newPayloadV2               reqid=36015 duration="91.499μs"  err="Invalid parameters"                     errdata="{Error:can't use newPayloadV2 post-cancun}"
 3月 14 05:32:17 i5giga34 geth[3532920]: INFO [03-14|05:32:17.569] NAT mapped port                          proto=TCP extport=14047 intport=30303 interface="UPNP IGDv1-IP1"
 3月 14 05:32:17 i5giga34 geth[3532920]: INFO [03-14|05:32:17.977] NAT mapped port                          proto=UDP extport=10186 intport=30303 interface="UPNP IGDv1-IP1"
 3月 14 05:32:31 i5giga34 geth[3532920]: WARN [03-14|05:32:31.998] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!
````

When submitting logs: please submit them as text and not screenshots.
It's been over 5 hours since we left Cancun.
It no longer syncs at all.

**Comment by h6dworker** [comment]
self resolved
I restarted Prysm and synced
It broke when I restarted geth first

**Comment by echo-ethan** [comment]
@h6dworker we met the same issue as yours, have you already resolved that issue?

**Comment by rjl493456442** [comment]
` 3月 14 05:31:53 i5giga34 geth[3532920]: WARN [03-14|05:31:53.027] Served engine_newPayloadV2               reqid=36015 duration="91.499μs"  err="Invalid parameters"                     errdata="{Error:can't use newPayloadV2 post-cancun}"
`

This legacy function `newPayloadV2` is not expected to be used by beacon client. So it's non an issue of Geth. Close it.

**Comment by h6dworker** [comment]
solved. Sorry for making such a fuss.
 It's a prism problem. 

thank you.
