### ISSUE TITLE
if somone facing issues in installing i made list of coammands and you are good

### ISSUE THREAD

**Issue by aaravs11** [ethereum/go-ethereum#29274]
sudo add-apt-repository -y ppa:ethereum/ethereum && sudo apt-get update && sudo apt-get install ethereum unzip screen -y && sudo apt-get upgrade geth -y && sudo add-apt-repository --yes ppa:nethermindeth/nethermind && sudo apt-get install nethermind -y

echo -e "1\n" | curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh && \
source "$HOME/.cargo/env" && \
sudo apt update && sudo apt install -y git gcc g++ make cmake pkg-config llvm-dev libclang-dev clang && \
git clone https://github.com/sigp/lighthouse.git && \
cd lighthouse && \
git checkout stable && \
make

cd ..

screen -S aaravgeth -dm sh -c 'geth --http --http.port 8546 --authrpc.addr localhost --authrpc.port 8552 --authrpc.vhosts localhost --authrpc.jwtsecret geth-tutorial/jwtsecret --port 30304; exec bash' && \
screen -S clef -dm sh -c 'clef --keystore geth-tutorial/keystore --configdir geth-tutorial/clef --chainid 1 --nousb; exec bash' && \
screen -S nether -dm sh -c 'nethermind -c mainnet; exec bash' && \
screen -S light -dm sh -c 'lighthouse bn --network mainnet --execution-endpoint http://localhost:8552 --execution-jwt /root/geth-tutorial/jwtsecret --checkpoint-sync-url https://mainnet.checkpoint.sigp.io --disable-deposit-contract-sync; exec bash'

just run this 4 commands 1 by 1 and you are good

**Comment by rjl493456442** [comment]
You can submit a pull request to our doc branch if you think something can be improved.
