### ISSUE TITLE
Ethereum full node is syncing but not able to get latest block using web3

### ISSUE THREAD

**Issue by Parmanand0712** [ethereum/go-ethereum#29272]
Hello,
the Ethereum full node are syncing on the AWS server using https://github.com/ethereum/go-ethereum.git on master branch and started geth using

./build/bin/geth --datadir /media/ebs2/ --http --http.api eth,net,engine,admin --authrpc.jwtsecret ~/jwtsecret.txt --http.port 8545 --http.addr 0.0.0.0 --http.corsdomain '' --http.vhosts '' --ws --ws.addr 0.0.0.0 --ws.port 8546

now node is syncing with latest block
0GiB eta=1m12.471s
INFO [03-15|14:35:27.909] Syncing: state healing in progress       accounts=688,940@31.82MiB slots=1,055,411@80.12MiB codes=1227@8.61MiB nodes=9,536,689@1.97GiB    pending=28046
INFO [03-15|14:35:35.055] Syncing: chain download in progress      synced=100.00% chain=717.14GiB headers=19,440,978@9.01GiB bodies=19,440,863@526.43GiB receipts=19,440,863@181.70GiB eta=1m12.511s
INFO [03-15|14:35:35.940] Syncing: state healing in progress       accounts=690,093@31.87MiB slots=1,056,715@80.22MiB codes=1228@8.61MiB nodes=9,544,270@1.97GiB    pending=37388
INFO [03-15|14:35:37.112] Forkchoice requested sync to new head    number=19,440,979 hash=e7f116..624a6e finalized=19,440,908
INFO [03-15|14:35:43.058] Syncing: chain download in progress      synced=100.00% chain=717.14GiB headers=19,440,979@9.01GiB bodies=19,440,863@526.43GiB receipts=19,440,863@181.70GiB eta=1m13.183s
INFO [03-15|14:35:44.067] Syncing: state healing in progress       accounts=691,473@31.93MiB slots=1,057,203@80.26MiB codes=1232@8.64MiB nodes=9,550,919@1.97GiB    pending=37913
INFO [03-15|14:35:49.109] Forkchoice requested sync to new head    number=19,440,980 hash=d97ec1..05f536 finalized=19,440,908
INFO [03-15|14:35:51.060] Syncing: chain download in progress      synced=100.00% chain=717.14GiB headers=19,440,980@9.01GiB bodies=19,440,863@526.43GiB receipts=19,440,863@181.70GiB eta=1m13.854s
INFO [03-15|14:35:52.174] Syncing: state healing in progress       accounts=693,387@32.02MiB slots=1,058,498@80.36MiB codes=1233@8.65MiB nodes=9,559,381@1.97GiB    pending=37402

but when i am fetching latest block using web3 then number is coming 0
$ cat index.js 
var Web3 = require('web3');
var web3 = new Web3('http://localhost:8545');

web3.eth.getBlock('latest').then(console.log); 
$ node index.js 
{
  difficulty: '17179869184',
  extraData: '0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa',
  gasLimit: 5000,
  gasUsed: 0,
  hash: '0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3',
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  miner: '0x0000000000000000000000000000000000000000',
  mixHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
  nonce: '0x0000000000000042',
  number: 0,
  parentHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
  receiptsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
  size: 540,
  stateRoot: '0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544',
  timestamp: 0,
  totalDifficulty: '17179869184',
  transactions: [],
  transactionsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  uncles: []
}
kindly help me on this
why number: 0 is coming at place of latest block

**Comment by weiihann** [comment]
Your node isn't fully synced completely yet. Notice that there's this `Syncing: state healing in progress` log. Once you see something like `Imported new chain segment` log, then you may try again.

**Comment by Parmanand0712** [comment]
Thanks
