### ISSUE TITLE
Impossible to build due to type error in crypto/kzg4844

### ISSUE THREAD

**Issue by OkudenCyrilDever** [ethereum/go-ethereum#29271]
#### System information

Geth version: `v1.13.14`
OS & Version: OSX

#### Expected behaviour
Build normally from command line or Docker build.

#### Actual behaviour
Returns 4 errors such `cannot use (gokzg4844.Blob)(blob) (value of type gokzg4844.Blob) as *gokzg4844.Blob value in argument to context.BlobToKZGCommitment` and fails.

#### Steps to reproduce the behaviour
`go build` using any library with go-ethereum@v1.13.14 latest dependency

#### Backtrace

````
# github.com/ethereum/go-ethereum/crypto/kzg4844
../../../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.14/crypto/kzg4844/kzg4844_gokzg.go:52:49: cannot use (gokzg4844.Blob)(blob) (value of type gokzg4844.Blob) as *gokzg4844.Blob value in argument to context.BlobToKZGCommitment
../../../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.14/crypto/kzg4844/kzg4844_gokzg.go:64:47: cannot use (gokzg4844.Blob)(blob) (value of type gokzg4844.Blob) as *gokzg4844.Blob value in argument to context.ComputeKZGProof
../../../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.14/crypto/kzg4844/kzg4844_gokzg.go:86:44: cannot use (gokzg4844.Blob)(blob) (value of type gokzg4844.Blob) as *gokzg4844.Blob value in argument to context.ComputeBlobKZGProof
../../../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.14/crypto/kzg4844/kzg4844_gokzg.go:97:36: cannot use (gokzg4844.Blob)(blob) (value of type gokzg4844.Blob) as *gokzg4844.Blob value in argument to context.VerifyBlobKZGProof
````

**Comment by cyrildever** [comment]
This is quite urgent because I'm stuck because of this error that didn't appear yesterday.

**Comment by namiloh** [comment]
Are you using latest by commit or v1.13.14? 
Show relevant part of your go.mod please

**Comment by OkudenCyrilDever** [comment]
With regard to `go-ethereum`, this is the go.mod:
```
github.com/ethereum/go-ethereum v1.13.14 // indirect
```
And this is the go.sum:
```
github.com/ethereum/c-kzg-4844 v0.3.1/go.mod h1:VewdlzQmpT5QSrVhbBuGoCdFJkpaJlO1aQputP83wc0=
github.com/ethereum/c-kzg-4844 v0.4.0/go.mod h1:VewdlzQmpT5QSrVhbBuGoCdFJkpaJlO1aQputP83wc0=
github.com/ethereum/c-kzg-4844 v1.0.0 h1:0X1LBXxaEtYD9xsyj9B9ctQEZIpnvVDeoBx8aHEwTNA=
github.com/ethereum/c-kzg-4844 v1.0.0/go.mod h1:VewdlzQmpT5QSrVhbBuGoCdFJkpaJlO1aQputP83wc0=
github.com/ethereum/go-ethereum v1.10.26/go.mod h1:EYFyF19u3ezGLD4RqOkLq+ZCXzYbLoNDdZlMt7kyKFg=
github.com/ethereum/go-ethereum v1.13.2/go.mod h1:gkQ5Ygi64ZBh9M/4iXY1R8WqoNCx1Ey0CkYn2BD4/fw=
github.com/ethereum/go-ethereum v1.13.5/go.mod h1:yMTu38GSuyxaYzQMViqNmQ1s3cE84abZexQmTgenWk0=
github.com/ethereum/go-ethereum v1.13.11/go.mod h1:gFtlVORuUcT+UUIcJ/veCNjkuOSujCi338uSHJrYAew=
github.com/ethereum/go-ethereum v1.13.14 h1:EwiY3FZP94derMCIam1iW4HFVrSgIcpsu0HwTQtm6CQ=
github.com/ethereum/go-ethereum v1.13.14/go.mod h1:TN8ZiHrdJwSe8Cb6x+p0hs5CxhJZPbqB7hHkaUXcmIU=
```

**Comment by namiloh** [comment]
I think you need to either
- use the latest geth, so upgrade the dependency to be by hash
- or downgrade the c-kzg dependency, to 0.4.0 again. 

Upgrading geth might be tricky, if it is an indirect dependency. Mind sharing more details about the project?

**Comment by OkudenCyrilDever** [comment]
I'm actually using a cascade of custom libraries that starts using go-ethereum for its crypto features. One of the sub-project is helping redact documents with a custom Feistel cipher implementation. The project I use was working perfectly well yesterday night, and I didn't do anything but building it this morning to run a Docker instance. Hence my surprise...
Could you elaborate on which hash I should use / what should I put in my upper lib in this cascade of libraries? I have no trouble updating them all if need be, but as it's time-consuming I wouldn't want to make it before I'm sure it works.

By the way, the use of the 0.4.0 version in c-kzg seems to be the thing, because my [original library](https://github.com/cyrildever/go-utls) is indeed using. What I don't understand is why the v1.0.0 appears downstream?

**Comment by holiman** [comment]
go-ethereum after commit https://github.com/ethereum/go-ethereum/commit/d5bacfa4def558a4c7b261c1a9fbfdbfc295e491, which merged https://github.com/ethereum/go-ethereum/pull/29050 uses `c-kzg` `1.0.0`. This is a breaking change.

As for why you suddenly started using `1.0.0`, I have no idea. The dependency ought to remain on `0.4.0`. Unless some other dependency pulls in `1.0.0`. I'm not sure.

**Comment by OkudenCyrilDever** [comment]
I've checked all my dependencies and, as I couldn't figure out why `1.0.0` was popping up in my downstream lib, I totally rebuilt it step-by-step, making sure the `0.4.0` stays. It worked out well, so my problem is solved. Nonetheless, the errors I got remains a bit worrying to me in the eventuality I'd want to move go-ethereum version up.
Thanks to you all for your precious help.

**Comment by namiloh** [comment]
Next release will be 1.14.0, it will use c-kzg 1.0.0 and should be no problem with the dependencies. 

"should" :)
