### ISSUE TITLE
transaction type not supported

### ISSUE THREAD

**Issue by BeckWS** [ethereum/go-ethereum#29289]
#### System information

Geth version: v1.13.14
CL client & version: prysm@v5.0.1
OS & Version: Linux
Commit hash : 

#### Expected behaviour
BlockByNumber returns block info

#### Actual behaviour
return error transaction type not supported

#### Steps to reproduce the behaviour
Using ethereum/go-ethereum in a go project, go-ethereum version is v1.10.26. When calling BlockByNumber from the client, it returns error. And the block number is close to the Cancun upgrade.

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by rjl493456442** [comment]
> go-ethereum version is v1.10.26

Your go-ethereum library is pretty old. It can't decode the latest introduced transaction types(e.g. blobtx). Please upgrade your dependency first.

**Comment by yigithancolak** [comment]
@rjl493456442 Hello. I am trying to use methods like BlockByNumber for Arbitrum Sepolia chain and it throws "transaction type not supported" error. It wans't the problem for bsc and bsc testnet chains. My system should work for both arbitrum and bsc. How can i handle this problem.
