### ISSUE TITLE
I would like to ask, has the gorilla test network been stopped? There are no new block updates in the block explorer.

### ISSUE THREAD

**Issue by astrid19981112** [ethereum/go-ethereum#29342]
I would like to ask, has the gorilla test network been stopped? There are no new block updates in the block explorer.

https://goerli.etherscan.io/

**Comment by learnerLj** [comment]
Yes, see: https://blog.ethereum.org/2023/11/30/goerli-lts-update
> That said, as of this writing, [nearly all Goerli validators](https://grafana.observability.ethpandaops.io/dashboard/snapshot/fwALK9PEe7CLEOO81lma5bT6k7jq7Gcs?orgId=0&from=1707927490905&to=1710519490905), which were run altruistically by various community members, have already been shut down. Goerli users & developers should therefore migrate to Sepolia or Holesky as soon as possible.

> In the coming months, [Goerli](https://goerli.net/), Ethereum's first multi-client testnet, will stop being supported by client and EF testing teams. The Dencun network upgrade will be the last one implemented on the network.
Either three months after the Goerli Dencun activation, or one month after the Dencun mainnet activation, whichever comes later, teams will begin exiting their validators [1]. Anyone relying on Goerli as a stable testnet should migrate elsewhere prior to this.
