### ISSUE TITLE
Sign transactions for other chainIds using Geth local keystore files

### ISSUE THREAD

**Issue by mvcastellari** [ethereum/go-ethereum#29352]
We have a running Geth node on main network, with chainId = 1 and we would like to use this node as well to sign (just sign) transactions using the same keystore but for another chainIds (Polygon (0x89) in this case). What is the best way to achieve this?

I've tried calling the method "personal_signTransaction" with the custom parameter "chainId" but it gives me the error: "chainId does not match node's (have=137, want=1)".

Any helps will be appreciated.

**Comment by jyap808** [comment]
Copy the keystore files over to your Polygon node with ChainID 137.

Or use a SDK library and code up the solution.

**Comment by MariusVanDerWijden** [comment]
Yep, its a security measure that you can not sign transactions for other chainids from your node. I don't think we should allow for this use case, copying the keystore to your polygon node or coding a solution is your best bet.
