### ISSUE TITLE
Synchronization does not proceed. please help me!

### ISSUE THREAD

**Issue by junghyun0783** [ethereum/go-ethereum#29350]
I'm currently trying to run the Ethereum "sepolia" testnet, but initialization and synchronization are not working. I don't think it's a prysm problem.
Currently running through docker, the container creation command is as follows.

```
docker run -itd --name eth_testnet --log-opt max-size=10m --log-opt max-file=3 --network medalla -v D:\docker\container\testnet\eth\sepolia:/root -v D:\docker\container\testnet\eth\sepolia.ethereumdata:/data -p 40021:8545 -p 40022:8546 -p 40023:30303/udp -p 40024:30303/tcp ethereum/client-go:v1.13.14 --sepolia --port 30301 --datadir "/data" --http --http.addr "0.0.0.0" --http.api admin,eth,debug,net,txpool,personal,web3,engine --http.vhosts "" --http.corsdomain "" --authrpc.addr "eth_testnet" --authrpc.port 8551 --authrpc.vhosts "*" --authrpc.jwtsecret /root/jwt_sepolia.hex --syncmode "snap" --snapshot=true
```

what's the problem?...

**Comment by junghyun0783** [comment]
eth_syncing's result

{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "currentBlock": "0x0",
        "healedBytecodeBytes": "0x0",
        "healedBytecodes": "0x0",
        "healedTrienodeBytes": "0x0",
        "healedTrienodes": "0x0",
        "healingBytecode": "0x0",
        "healingTrienodes": "0x0",
        "highestBlock": "0x0",
        "startingBlock": "0x0",
        "syncedAccountBytes": "0x0",
        "syncedAccounts": "0x0",
        "syncedBytecodeBytes": "0x0",
        "syncedBytecodes": "0x0",
        "syncedStorage": "0x0",
        "syncedStorageBytes": "0x0",
        "txIndexFinishedBlocks": "0x0",
        "txIndexRemainingBlocks": "0x1"
    }
}

**Comment by jyap808** [comment]
Error in the logs "no beacon client seen."

Your EL and CL nodes aren't connected and communicating with each other. Fix that issue.

Beacon note looks to by syncing fine.

**Comment by rjl493456442** [comment]
@jyap808 said, you have to setup the connection between the EL and CL nodes correctly.

From the beacon log I can tell is beacon client is not synced yet. You can probably use checkpoint sync feature to fasten the bootstrap stage. https://eth-clients.github.io/checkpoint-sync-endpoints/
