### ISSUE TITLE
while geth is syncing a fresh blockchain with --rpc and --fast, eth_blockNumber() always returns zero

### ISSUE THREAD

**Issue by paulohm2** [ethereum/go-ethereum#2936]
#### System information

Geth version: ` 1.5.0-unstable`
OS & Version: Linux

#### Expected behaviour
calling geth RPC while blockchain is syncing should return at least some well known info, like the blockchain block numbers (eth_blockNumber()).

#### Actual behaviour
eth_blockNumber() returns 0 (zero) until blockchain is fully synced. then it starts to return the correct number.

#### Steps to reproduce the behaviour
1) invoke geth --rpc --fast without a full block chain
2) invoke a python console and ..

>>> import json
>>> import urllib
>>> import urllib2
>>> import pprint
>>> from ethjsonrpc import EthJsonRpc
>>> c = EthJsonRpc('127.0.0.1', 8545)
>>> print c.eth_blockNumber()
0

**Comment by karalabe** [comment]
This works as intended. During fast sync Geth is only downloading the blocks, but not processing them, so although it has the blocks it doesn't have the associated state with it. Concurrently it is also downloading the state for the head block (not intermediate ones up to that point). So during fast sync we have "stateless blocks" and "blockless states". When fast sync completes, these two things join, forming the "statefull-blockfull-chain" :) Up to this point all the data is unusable, so reporting anything other than 0 would be a lie.

During sync you could look at the `eth.syncing` endpoint, which returns the current sync progress. Based on that you can display proper UI stuff if you need it (or simply have a proper guess for yourself).

**Comment by yaoyu26** [comment]
the answer help me, good job!
