### ISSUE TITLE
how I fetch the block data?

### ISSUE THREAD

**Issue by wzl521** [ethereum/go-ethereum#29361]
I wrote code locally to fetch block information from here, but why can't I retrieve any information? the code is follow:
![image](https://github.com/ethereum/go-ethereum/assets/63525530/bb3b3eab-19d2-496e-8cc3-e5756823d0ff)

**Comment by rjl493456442** [comment]
`NewBlockMsg` handling is already deprecated in our codebase, as block propagation is disallowed after The Merge.

We don't really know what's the issue of your instrumental code, can't do anything with it unfortunately.

**Comment by wzl521** [comment]
> `NewBlockMsg`我们的代码库中已弃用处理，因为合并后不允许块传播。 我认为这是您的工具代码从未被调用的主要原因。
> 
> 否则，我们真的不知道您的工具代码有什么问题，不幸的是无法对其执行任何操作。

Where do I need to fetch the latest block?Has the method handleNewPooledTransactionHashes also been deprecated?And this method is also can not fetch the latest transcation
![image](https://github.com/ethereum/go-ethereum/assets/63525530/8a7d1dd1-d1ad-42e8-af21-71a55f69c065)

**Comment by rjl493456442** [comment]
`handleNewPooledTransactionHashes` It's not deprecated.

> Where do I need to fetch the latest block 

You can use subscription feature to subscribe both chain head and pending transactions. Check https://geth.ethereum.org/docs/interacting-with-geth/rpc/pubsub for more information.
