### ISSUE TITLE
Received a new mined block, but with some fields of tx missing.

### ISSUE THREAD

**Issue by ObscureLin** [ethereum/go-ethereum#29379]
I am using go-ethereum-1.11.2 source code. And I added some fields to the Transaction Structure as the following image shows.
![image](https://github.com/ethereum/go-ethereum/assets/55263831/6f05ae8c-a1df-475d-8742-42cc18461125)

Further, I read the code, and I assigned values to these fields before miner writes new block to StateDB.
```
        Assasign value to fields.......................
	// Commit block and state to database.
			_, err := w.chain.WriteBlockAndSetHead(block, receipts, logs, task.state, true)
			if err != nil {
``` 
Then I checked the block before sending it to the peers in function 
`func (p *Peer) SendNewBlock(block *types.Block, td *big.Int) error `, the value of these fields were correct.
But very interesting thing happened when other nodes(peers) heard the new block in 
` func handleNewBlock(backend Backend, msg Decoder, peer *Peer) error` after ` msg.Decode(ann) `, these fields of  Transaction Structure inside the block were not assigned (initial value).
I am puzzled and look forward to your assistance.

**Comment by rjl493456442** [comment]
The block will be encoded before sending out and the block will be decoded from the received blob in another node.
You have to modify the block encoder/decoder to survive your customized tx fields.

**Comment by ObscureLin** [comment]
Could you provide me with some hints, such as which specific files and code segments need to be modified. Very appreciate!

**Comment by ObscureLin** [comment]
> Could you provide me with some hints, such as which specific files and code segments need to be modified. I thought RLP already can encode/decode uint64 type. Very appreciate!

https://github.com/ethereum/go-ethereum/issues/29379#issuecomment-2024966796
