### ISSUE TITLE
Is the Ethereum node I am running normal?

### ISSUE THREAD

**Issue by junghyun0783** [ethereum/go-ethereum#29374]
We are currently creating and running a new sepolia testnet node.
However, when calling eth_blockNumber RPC
{
     "jsonrpc": "2.0",
     "id": "1",
     "result": "0x0"
}
You will receive the results.

Can I confirm that the EL and CL I am currently running are operating normally?
Let me show you the log.

![47](https://github.com/ethereum/go-ethereum/assets/25001497/902c54d4-6466-4354-8ae5-02655544d435)

If I wait a little longer, will the result I want be an RPC?
Please experts help me...

**Comment by rjl493456442** [comment]
Your Geth node is still syncing.

```
However, when calling eth_blockNumber RPC
{
"jsonrpc": "2.0",
"id": "1",
"result": "0x0"
}
You will receive the results.
```

Yes Geth will respond you a chain head even during the state sync stage, although the head is 0. You can use `eth_syncing` RPC to determine the sync progress.

**Comment by junghyun0783** [comment]
@rjl493456442 
Thank you for your kind reply.
This is the result of eth_syncing.
Is there anything wrong?
If all goes well, when will “eth_blockNumber” be called?

{
    "jsonrpc": "2.0",
    "id": "1",
    "result": {
        "currentBlock": "0x172633",
        "healedBytecodeBytes": "0x0",
        "healedBytecodes": "0x0",
        "healedTrienodeBytes": "0x0",
        "healedTrienodes": "0x0",
        "healingBytecode": "0x0",
        "healingTrienodes": "0x0",
        "highestBlock": "0x172674",
        "startingBlock": "0x0",
        "syncedAccountBytes": "0x0",
        "syncedAccounts": "0x0",
        "syncedBytecodeBytes": "0x0",
        "syncedBytecodes": "0x0",
        "syncedStorage": "0x0",
        "syncedStorageBytes": "0x0",
        "txIndexFinishedBlocks": "0x0",
        "txIndexRemainingBlocks": "0x1"
    }
}
