### ISSUE TITLE
Why eth_blockNumber RPC result value is "0x0"?!??

### ISSUE THREAD

**Issue by junghyun0783** [ethereum/go-ethereum#29389]
Why eth_blockNumber RPC result value is "0x0"?!??

Currently synchronizing the sepolia testnet is in progress.
Currently prysm is in the process of being initialized (8%).
The client has received approximately 1.57 million blocks.
For reference, syncmode is "snap".

I understand that the eth_blockNumber RPC cannot be viewed because synchronization is in progress.
So when will I be able to view it?
The result continues to be “0x0”.

When will I be able to view it?

![48](https://github.com/ethereum/go-ethereum/assets/25001497/9e20c32e-fde4-48eb-aaa4-0732bd49845c)

Additionally, How long does it usually take to synchronize the sepolia testnet?

**Comment by rjl493456442** [comment]
You can use `eth_syncing` rpc endpoint to checkout the sync progress. 

It should be sufficient for your case although it's not super reliable (`false` will also returned if the sync process is not started).

**Comment by rjl493456442** [comment]
You can also interact with geth via console

```
geth attach <your-ipc-path>

> eth.syncing
{
  currentBlock: 16648942,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 19431887,
  startingBlock: 11463394,
  syncedAccountBytes: 0,
  syncedAccounts: 0,
  syncedBytecodeBytes: 0,
  syncedBytecodes: 0,
  syncedStorage: 0,
  syncedStorageBytes: 0,
  txIndexFinishedBlocks: 2350000,
  txIndexRemainingBlocks: 0
}
```
