### ISSUE TITLE
How to decode/encode new designed field in block Structure?

### ISSUE THREAD

**Issue by ObscureLin** [ethereum/go-ethereum#29394]
The block will be encoded before sending out and the block will be decoded from the received blob in another node.
You have to modify the block encoder/decoder to survive your customized tx fields.

_Originally posted by @rjl493456442 in https://github.com/ethereum/go-ethereum/issues/29379#issuecomment-2024966796_

Could you provide me with some hints, such as which specific files and code segments need to be modified. I thought RLP already could handle uint64 type field. Very appreciate!

**Comment by rjl493456442** [comment]
Encoder: https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction.go#L106
Decoder: https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction.go#L139

You can check out the transaction encoder/decoder above. You probably need to define your own encoder/decoder for customized transaction fields.
