### ISSUE TITLE
Console history only partially retained

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#2939]
The console doesn't seem to retain history for commands that fail. This is annoying because if I have a line that's longer than the width of my terminal, Geth console will only display part of it, so I can't just copy paste and fix my error.

Similarly, for some reason Geth didn't retain a `contract.new` call for me. It was a huge line so maybe it hit some limit in some package and got discarded, but it's still an unfortunate thing we should fix.

**Comment by ethernomad** [comment]
For me no new commands are being saved at all. It's really annoying.

**Comment by RichardH92** [comment]
Is this still an issue that needs to be fixed?
