### ISSUE TITLE
error is not validated in Bytes.go

### ISSUE THREAD

**Issue by aktech297** [ethereum/go-ethereum#29403]
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

Error validation is missing

#### Steps to reproduce the behaviour

https://github.com/ethereum/go-ethereum/blob/a3829178af6cec64d6def9131b9340a3328cc4fc/common/bytes.go#L79-L82

#### Backtrace

````
[backtrace]
````

https://github.com/ethereum/go-ethereum/blob/a3829178af6cec64d6def9131b9340a3328cc4fc/common/bytes.go#L79-L82

In above code block, the error code code it not used.

**Comment by aktech297** [comment]
I need time to understand the complete code flow.. But I wanted to ask this since it is very easy to find.

**Comment by DavidKorochik** [comment]
@aktech297 From looking at the usage of this util function, looks like enough errors are being handled before the decode operation.
Imo if you'll add an error handling, it can break backwards compatibility in some places of I'm not wrong.

**Comment by aktech297** [comment]
Hi @DavidKorochik 
Thanks for your kind response.

what are the possible ways to trigger this functionality ? what would happen if we fork as it is  ?

**Comment by karalabe** [comment]
Yeah, those methods are more of some legacy leftovers. We're not using them in live code, only in tests. All live code uses `hexutil`. Ideally the tests using these should be updated and the methods nuked out.
