### ISSUE TITLE
Panic of `geth`.

### ISSUE THREAD

**Issue by MathieuDutSik** [ethereum/go-ethereum#29425]
#### System information

Geth version: `1.13.14-stable`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour

I would expect a clean error when the input is wrong. Now what is exactly the error and what I should get, I do not know.

#### Actual behaviour

I obtained the following: ```
[backtrace]
panic: ethash (pow) sealing not supported any more

goroutine 4338 [running]:
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).Seal(0xc0004ea080?, {0xc000936000?, 0xc000936108?}, 0xc000936000?, 0x38b8dc0?, 0xcfc413c73a215b45?)
	github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:84 +0x25
github.com/ethereum/go-ethereum/consensus/beacon.(*Beacon).Seal(0xc0006c6c10, {0x103b68e68, 0xc000454c08}, 0xc0008ca280, 0xc00033e600, 0xc000934000)
	github.com/ethereum/go-ethereum/consensus/beacon/consensus.go:400 +0x8d
github.com/ethereum/go-ethereum/miner.(*worker).taskLoop(0xc000223208)
	github.com/ethereum/go-ethereum/miner/worker.go:635 +0x2fd
created by github.com/ethereum/go-ethereum/miner.newWorker in goroutine 1
	github.com/ethereum/go-ethereum/miner/worker.go:297 +0x94b
```

No matter the input, the program should not have any panic.

#### Steps to reproduce the behaviour

Following the steps of theThe following can be done to get the error:
https://www.linkedin.com/pulse/create-you-private-ethereum-blockchain-ashwin-kolhe/

#### Backtrace

The backtrace is above. The point is that we should not have any backtrace.

**Comment by rjl493456442** [comment]
Proof-of-work is no longer supported by the ethereum protocol, please switch to Proof-of-stake instead.

**Comment by Talhaarain150** [comment]
> #### System information
> Geth version: `1.13.14-stable` CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0 OS & Version: OSX Commit hash : (if `develop`)
> 
> #### Expected behaviour
> I would expect a clean error when the input is wrong. Now what is exactly the error and what I should get, I do not know.
> 
> #### Actual behaviour
> I obtained the following: ``` [backtrace] panic: 0x44a6f3dd509d687f4234a5417425b5bdc548018d (pow) sealing not supported any more
> 
>  4338 [running]: github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).Seal(0xc0004ea080?, {0xc000936000?, 0xc000936108?}, 0xc000936000?, 0x38b8dc0?, 0xcfc413c73a215b45?) github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:84 +0x25 github.com/ethereum/go-ethereum/consensus/beacon.(*Beacon).Seal(0xc0006c6c10, {0x103b68e68, 0xc000454c08}, 0xc0008ca280, 0xc00033e600, 0xc000934000) github.com/ethereum/go-ethereum/consensus/beacon/consensus.go:400 +0x8d github.com/ethereum/go-ethereum/miner.(*wor).taskLoop(0xc000223208) github.com/ethereum/go-ethereum/miner/worker.go:635 +0x2fd created by github.com/ethereum/go-ethereum/miner.newWorker in  github.com/ethereum/go-ethereum/miner/worker.go:297 +0x94b
> 
> ```
> 
> No matter the input, the program should not have any panic.
> 
> #### Steps to reproduce the behaviour
> 
> Following the steps of 0x44a6f3dd509d687f4234a5417425b5bdc548018d following can be done to get the error:
> https://www.linkedin.com/pulse/create-you-private-ethereum-blockchain-ashwin-kolhe/
> 
> #### Backtrace
> 
> The backtrace is above. The point is that we should not have any backtracker.
> ```

**Comment by MathieuDutSik** [comment]
But sill a panic cannot be considered a reasonable outcome of a program.

**Comment by karalabe** [comment]
Fair enough. That said, this should not happen on the master branch any more because even the mining code was deleted, so you will never be able to even trigger mining in the next release.
