### ISSUE TITLE
Geth transactions broadcast 

### ISSUE THREAD

**Issue by nerdynaman** [ethereum/go-ethereum#29447]
Can someone please confirm the raw transaction I see  in Geth (eth.getRawTransaction) is the same transaction that goes over the network. As whenever I generate a new transaction via Geth node and observe the outgoing packets on Wireshark the packet that corresponds to transaction generated show different data size as compared with raw transaction size

**Comment by Talhaarain150** [comment]
> Can someone please confirm the raw transaction I see in Geth (eth.getRawTransaction) is the same transaction that goes over the network. As whenever I generate a new transaction via Geth node and observe the outgoing packets on Wireshark the packet that corresponds to transaction generated show different data size as compared with raw transaction size

**Comment by karalabe** [comment]
The network packets are enveloped via devp2p, there's snappy encoding of the envelopes. The transactions are sometimes broadcast sometimes only announced.

The raw transaction is indeed the same as goes over the network, but there's a lot more happening on the networking which might make the size not be 1-to-1.
