### ISSUE TITLE
please. When will the result value output the desired value instead of 0x0?

### ISSUE THREAD

**Issue by junghyun0783** [ethereum/go-ethereum#29442]
hello.
I really want to hear the answer I want.
This is the current result when calling eth_syncing RPC.
![49](https://github.com/ethereum/go-ethereum/assets/25001497/91fd08f7-f17b-4f0f-b3ed-645d1b7ae04f)

When calling eth_blockNumber RPC, the result value continues to be 0x0.
What I want is when the result value will be output as a block number rather than 0x0. I kept asking this, but he gave me a different answer and said "close".
please. When will the result value output the desired value instead of 0x0?

**Comment by MariusVanDerWijden** [comment]
Once the initial sync is done, `eth.syncing` will return false, then `eth.getBlockByNumber("latest")` will return the latest block.
Your initial sync is not fully done (even if it says 100% in your logs), we wait for the consensus layer to switch to a non-optimistic block, but it seems like the CL has not enough peers for that. Maybe try restarting your consensus layer node (bottom left)

**Comment by junghyun0783** [comment]
@MariusVanDerWijden 
First of all, thank you for your kind response.
As you said, I ran CL and EL again.
This is the call result of the eth_syncing RPC.

```
{
     "jsonrpc": "2.0",
     "id": "1",
     "result": {
         "currentBlock": "0x2b7021",
         "healedBytecodeBytes": "0x0",
         "healedBytecodes": "0x0",
         "healedTrienodeBytes": "0x0",
         "healedTrienodes": "0x0",
         "healingBytecode": "0x0",
         "healingTrienodes": "0x0",
         "highestBlock": "0x2b7062",
         "startingBlock": "0x2b6dec",
         "syncedAccountBytes": "0x0",
         "syncedAccounts": "0x0",
         "syncedBytecodeBytes": "0x0",
         "syncedBytecodes": "0x0",
         "syncedStorage": "0x0",
         "syncedStorageBytes": "0x0",
         "txIndexFinishedBlocks": "0x0",
         "txIndexRemainingBlocks": "0x1"
     }
}
```

However, it seems like blocks continue to be received from CL.
The currentBlock value continues to increase in real time.

However, the eth_blockNumber value is still 0x0.
I am curious why the result value is 0x0.

**Comment by rjl493456442** [comment]
Non-zero number will only be returned by `eth_blockNumber` iff the sync is fully done.

**Comment by junghyun0783** [comment]
@rjl493456442 
First of all, thank you for your reply.
Should all synchronizations be completed even though syncmode is "snap"?

**Comment by rjl493456442** [comment]
Exactly

Thanks and Best regards Gary rong


junghyun0783 ***@***.***>于2024年4月3日 周三下午3:40写道：

**Comment by junghyun0783** [comment]
The initialization process is complete.
Even after two days, get_blockNumber is currently returning 0x0.
It seems like all initialization and synchronization has been completed, but why does it still return 0x0?...
Here is the command for your reference.

![why](https://github.com/ethereum/go-ethereum/assets/25001497/fa0116ea-e878-498c-96ee-77e34673a8ec)

`cmd /k geth --sepolia -syncmode "snap" --http.api admin,eth,debug,net,txpool,personal,web3,engine -datadir ".\dataSepolia" -http --http.port 20201 --http.addr 0.0.0.0 --nat "any"  --rpc.allow-unprotected-txs --snapshot=false -ipcdisable --authrpc.jwtsecret ../consensus/jwt_sepolia.hex --authrpc.vhosts="*" --authrpc.addr=0.0.0.0`


`prysm.bat beacon-chain --execution-endpoint=http://localhost:8551 --sepolia --datadir=./prysm_data_sepolia --jwt-secret=../jwt_sepolia.hex --rpc-host=0.0.0.0 --grpc-gateway-host=0.0.0.0 --genesis-state=sepolia_genesis.ssz --suggested-fee-recipient=0x67CDB8344FFCa7aaaeda9e7a4F4f1A9cb4D1FC64`

**Comment by holiman** [comment]
You're only connected to one peer, and geth is busy trying to sync state. Having only one peers makes it go very slow (its not even certain that the singular peer you have is capable of serving state). Your node is starving, and unable to progress in the sync

**Comment by junghyun0783** [comment]
![image](https://github.com/ethereum/go-ethereum/assets/25001497/645ef0dc-1ba2-445f-a32b-5bd050086e4e)

**Comment by fjl** [comment]
It can also be related to the fact that Sepolia is not a very active network with fewer peers?

**Comment by junghyun0783** [comment]
@fjl 
thank you! it is complete~
