### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zemse** [ethereum/go-ethereum#29440]
#### System information

Geth version: `master`
CL client & version: none
OS & Version: OSX
Commit hash : [0bd03db](https://github.com/ethereum/go-ethereum/commit/0bd03dbc5597175d79067270c0710604cba489cf)

#### Expected behaviour

Running [this code](https://github.com/zemse/zkevm-circuits/blob/bc7ae855e113b7178d9bf7820634bcc6cda95f15/geth-utils/lib/lib.go#L26) should provide the execution results, however, it triggers the following error

#### Actual behaviour

I get a runtime error when generating the trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x101632fc4]

goroutine 17 [running, locked to thread]:
github.com/ethereum/go-ethereum/eth/tracers/logger.(*StructLogger).OnOpcode(0x140000d2c60, 0x0, 0x60, 0xef038, 0x3, {0x1021d3788, 0x1400000f5a8}, {0x0, 0x0, 0x101621e6c?}, ...)
        /Users/sohamzemse/go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.5-0.20240402092557-0bd03dbc5597/eth/tracers/logger/logger.go:214 +0x644
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0x14000058180, 0x14000438000, {0x10283ac60, 0x0, 0x0}, 0x0)
        /Users/sohamzemse/go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.5-0.20240402092557-0bd03dbc5597/core/vm/interpreter.go:280 +0x850
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0x14000000c60, {0x1021c9d20, 0x1400003ed38}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        /Users/sohamzemse/go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.5-0.20240402092557-0bd03dbc5597/core/vm/evm.go:223 +0x670
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0x1400042b590)
        /Users/sohamzemse/go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.5-0.20240402092557-0bd03dbc5597/core/state_transition.go:436 +0x5f8
github.com/ethereum/go-ethereum/core.ApplyMessage(0x1021c2fb8?, 0x1021c2fc0?, 0x1400041c610?)
        /Users/sohamzemse/go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.5-0.20240402092557-0bd03dbc5597/core/state_transition.go:184 +0x4c
main/gethutil.Trace({0x140000323c0, {0x10283ac60, 0x0, 0x0}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...})
        /Users/sohamzemse/Workspace/opensource/external/pse/zkevm-circuits/geth-utils/gethutil/trace.go:240 +0xe1c
main.CreateTrace(0x134009800)
        /Users/sohamzemse/Workspace/opensource/external/pse/zkevm-circuits/geth-utils/lib/lib.go:26 +0xc8
error: test failed, to rerun pass `-p bus-mapping --lib`

Caused by:
  process didn't exit successfully: `/Users/sohamzemse/Workspace/opensource/external/pse/zkevm-circuits/target/debug/deps/bus_mapping-478e5a5effdf5d89 tload` (signal: 6, SIGABRT: process abort signal)
```

#### Additional information

The runtime is successful on a historical geth version (1.11.5). However I need geth with support for the recent hardfork, and I tried using multiple versions from 1.13.12 onwards but running into the issue https://github.com/ethereum/go-ethereum/issues/29271, however using the latest commit on master builds successfully (but the above mentioned runtime error is caused).

**Comment by s1na** [comment]
It's not great to re-write the execution logic, but I'm sure you have your reasons. Anyway there was a change to how we do tracing (#29189). This part of the code needs updating:

https://github.com/zemse/zkevm-circuits/blob/16507249d0e1cd0e5fd0fa0139872d9d5389fb9c/geth-utils/gethutil/trace.go#L231-L251

You will need a couple of changes in there. Most notably you should try to use `core.ApplyTransactionWithEVM`. That will invoke the required `OnTxStart` and `OnTxEnd` events.

**Comment by zemse** [comment]
Thanks for the pointers I got this working!

**Comment by zemse** [comment]
Hi @s1na,

My implementation has some issues, some tests in the zkevm project failed with this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102e4cb5c]

goroutine 17 [running, locked to thread]:
main/gethutil.Trace({0x140002dcfc0, {0x10405aca0, 0x0, 0x0}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...})
        /path/pse/zkevm-circuits/geth-utils/gethutil/trace.go:254 +0xe4c
main.CreateTrace(0x13f00c800)
        /path/pse/zkevm-circuits/geth-utils/lib/lib.go:26 +0xc8
```

Relevant links:
- execution logic line that is triggering the panic: [zkevm-circuits/geth-utils/gethutil/trace.go#L254](https://github.com/zemse/zkevm-circuits/blob/75c95a7bb6fc53024afc4527f9a2d68d9037fb2c/geth-utils/gethutil/trace.go#L254)
- test case deploying a huge contract which is triggering the panic [zkevm-circuits/bus-mapping/src/circuit_input_builder/tracer_tests.rs#L1037-L1053](https://github.com/zemse/zkevm-circuits/blob/75c95a7bb6fc53024afc4527f9a2d68d9037fb2c/bus-mapping/src/circuit_input_builder/tracer_tests.rs#L1037-L1053)

The execution logic ran successfully in some positive test cases I checked, which made me think it works perfectly.

Is there any obvious bug in the execution logic that you see?

 What is your telegram handle?
