### ISSUE TITLE
Disable "OK" user input on Clef Startup

### ISSUE THREAD

**Issue by jurijus01** [ethereum/go-ethereum#29468]
# Rationale
Who is going to guarantee Clef process will never crash? 

#Why should this feature exist? What are the use-cases?

Need to run Ethereum node without 24h supervision. Can't administer it 24h to be able to manually restart Clef if and when it crashes. Need systemd service to get Clef back up.

# Implementation
Your input goes here. 
.service file made for Clef fails to start due to user input needed (see the pic)
![failed](https://github.com/ethereum/go-ethereum/assets/32413052/8abc62d2-19ed-49ce-8ea7-8ae04d4519b1)

Do you have ideas regarding the implementation of this feature?
#Are you willing to implement this feature?
Absolutely!

Kind regards,
Yuri

**Comment by fuelmessenger** [comment]
:sparkles: Thanks to the community, there's an estimated bounty value of **$54.50 USD** for a successful merge request of this issue via contributions such as **4.875 UNI** tokens. Happy coding :grinning:
Details and T&Cs at [joinfuel.io](https://joinfuel.io)

**Comment by namiloh** [comment]
Use `--suppress-bootwarn`

Something like that, don't recall exactly.

**Comment by holiman** [comment]
PSA: @fuelmessenger is not anything we're familiar with , might be a scam, so I'll delete those posts

**Comment by karalabe** [comment]
If there's a flag, it's enough of a solution imo.

**Comment by michaelwklein** [comment]
Hi @holiman thanks for moderating the repository. @joinfuel is a project that assigns rewards to GitHub issues, developers simply to connect their GitHub via joinfuel.io to obtain the rewards. Is there someone we can talk to in Developer relations to have these comments approved?
