### ISSUE TITLE
Client exits without error when trying to connect to private network

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/go-ethereum#2947]
#### System information

Geth version: `1.4.11-stable-fed692f6`
OS & Version: OSX El Capitan

#### Expected behaviour
 Should startup and connect to private network

#### Actual behaviour
Shuts down without error

#### Steps to reproduce the behaviour
geth --rpc --rpcaddr 127.0.0.1 --rpcport 8101 --rpccorsdomain http://127.0.0.1:8000 --datadir datadir/development/ --keystore config/development/keystore/ --networkid 5473 --unlock 42c35b6c220d570bd8898a540406e0b026479f7b --password config/development/password --nodiscover --verbosity 6 --maxpeers 1 js peer.js

peer.js: https://gist.github.com/aakilfernandes/9150026a58c96c850ffa0d6b02d65ba5

#### Backtrace
https://gist.github.com/aakilfernandes/3aed9e472453719b7fdede2bc3d843b6

**Comment by aakilfernandes** [comment]
As the backtrace shows, I'm able to connect to my peer however my client then shuts down for some unkown reason (a client quit message is sent)

**Comment by aakilfernandes** [comment]
I should add, I'm fully able to connect and sync with the public network

**Comment by fjl** [comment]
Does it work with the develop branch?

**Comment by karalabe** [comment]
You're command ran the `js` subcommand. That works by executing the specified script and exiting afterwards. If you want your node to execute the script and continue running you'll need to do `geth --preload peer.js console`.
