### ISSUE TITLE
`ethereum.CallMsg` should use `Input` instead of `Data`

### ISSUE THREAD

**Issue by lightclient** [ethereum/go-ethereum#29484]
> [ethereum.CallMsg](https://github.com/ethereum/go-ethereum/blob/7aafad2233b676b7beaf56e89f82360704d669d0/interfaces.go#L152) should also have it as Input probably.

repost from https://github.com/ethereum/execution-apis/issues/507#issuecomment-2041055440 by @Amit0617

**Comment by Amit0617** [comment]
> I sometimes see people use `ethereum.CallMsg` as an argument value in RPC calls.

Exactly my concern. I felt it would be more natural using `ethereum.CallMsg` directly so that with upcoming changes and new EIPs (and hence new key value pairs getting added to it) nothing needs to be copied and pasted.

**Comment by Issalk** [comment]
> > [ethereum.CallMsg](https://github.com/ethereum/go-ethereum/blob/7aafad2233b676b7beaf56e89f82360704d669d0/interfaces.go#L152) should also have it as Input probably.
> 
> repost from [ethereum/execution-apis#507 (comment)](https://github.com/ethereum/execution-apis/issues/507#issuecomment-2041055440) by [@Amit0617](https://github.com/Amit0617)
