### ISSUE TITLE
Geth stuck on startup 

### ISSUE THREAD

**Issue by bogdangainusa** [ethereum/go-ethereum#29486]
Geth stuck on startup

```
Apr 08 07:05:08 ip-172-31-41-172 systemd[1]: Started Geth service.
Apr 08 07:05:08 ip-172-31-41-172 geth[446]: INFO [04-08|07:05:08.885] Starting Geth on Ethereum mainnet...
Apr 08 07:05:08 ip-172-31-41-172 geth[446]: INFO [04-08|07:05:08.892] Maximum peer count                       ETH=50 total=50
Apr 08 07:05:08 ip-172-31-41-172 geth[446]: INFO [04-08|07:05:08.894] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
Apr 08 07:05:08 ip-172-31-41-172 geth[446]: TRACE[04-08|07:05:08.902] Started watching keystore folder         path=/home/cryptodaemon/.ethereum/keystore folder=/home/cryptodaemon/.ethereum/keystore
Apr 08 07:05:20 ip-172-31-41-172 geth[446]: TRACE[04-08|07:05:20.962] Ignoring file on account scan            path=/home/cryptodaemon/.ethereum/keystore/.UTC--2024-04-04T14-28-24.497252240Z--xxx>
Apr 08 07:05:20 ip-172-31-41-172 geth[446]: TRACE[04-08|07:05:20.962] Ignoring file on account scan            path=/home/cryptodaemon/.ethereum/keystore/.UTC--2024-04-04T14-28-24.829514325Z--xxx>
Apr 08 07:05:20 ip-172-31-41-172 geth[446]: TRACE[04-08|07:05:20.962] Ignoring file on account scan            path=/home/cryptodaemon/.ethereum/keystore/.UTC--2024-04-04T14-28-25.607800810Z--xxx>
Apr 08 07:05:29 ip-172-31-41-172 geth[446]: DEBUG[04-08|07:05:29.803] FS scan times                            list=12.060091844s set=8.239615889s diff=601.528285ms
```

#### System information

Geth version:  `[Altaaya (v1.13.14)](https://github.com/ethereum/go-ethereum/releases/tag/v1.13.14) `
CL client & version: prysm@v5.0.3
OS & Version: Linux

**Comment by MariusVanDerWijden** [comment]
Do you have a lot of keys in your keystore?

**Comment by fearlesschenc** [comment]
@bogdangainusa what's the command you use to start geth

**Comment by bogdangainusa** [comment]
@MariusVanDerWijden  I think issue is related to number of keys. Currently i have around 600.000 keystores. 
After around 20 minutes geth started to work

**Comment by MariusVanDerWijden** [comment]
Yes, this is expected since we need to decrypt every keystore and get the public key for every private key that is stored. Theres not much we can do here. You should consider moving keys to different instances or just take the 20 min startup hit

**Comment by holiman** [comment]
You could also use `clef` to handle the keystores. It would still take 20 minutes, but you wouldn't have to restart it. That is, of course, depending on your usecase: whether clef can do what you want or not. I assume you want to sign transactions, so you'd have to store the keys the clef secrets. I have no idea how well clef behaves with 600K keys: probably not great. 

Sorry, your usecase is so unusual that you'd be better off putting together a custom backend for managing the keys, which is what I guess all the exchanges have done. Geth related tools are more geared towards common users and usecases.
