### ISSUE TITLE
RPC id can be string according to JSONRPC specification

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#295]
with request:
```
POST / HTTP/1.1
Host: 127.0.0.1:8080
Content-Length: 106
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.5.1 CPython/2.7.8 Darwin/14.1.0
Connection: keep-alive
content-type: application/json

{"params": null, "jsonrpc": "2.0", "id": "5b659f5e-7a16-458b-9456-ce528e967229", 
"method": "eth_coinbase"}
```

error:
```
2015/02/06 10:34:46 [RPC] Error decoding JSON:  json: cannot unmarshal string into Go value
of type int
```

however according to http://www.jsonrpc.org/specification#request_object

> **id**
>  An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If   it is not included it is assumed to be a notification. The value SHOULD normally not be Null [1] and   Numbers SHOULD NOT contain fractional parts [2]

**Comment by tgerring** [comment]
Fix merged in ef6c7bd726f78e4134d207b58f1efe504bbad40e
