### ISSUE TITLE
"Syncing: state healing in progress" went on for a long time

### ISSUE THREAD

**Issue by FuxingGG** [ethereum/go-ethereum#29524]
```
INFO [04-13|08:36:03.124] Syncing: state healing in progress       accounts=22880@1.07MiB        slots=4479@378.16KiB          codes=21@64.85KiB        nodes=138,598@44.04MiB pending=38886
INFO [04-13|08:36:03.599] Syncing: chain download in progress      synced=100.00% chain=734.37GiB headers=19,643,130@9.13GiB bodies=19,643,025@539.27GiB receipts=19,643,025@185.97GiB eta=1.822s
INFO [04-13|08:36:11.219] Syncing: state healing in progress       accounts=23049@1.07MiB        slots=4482@378.42KiB          codes=21@64.85KiB        nodes=139,004@44.11MiB pending=38791
INFO [04-13|08:36:11.604] Syncing: chain download in progress      synced=100.00% chain=734.37GiB headers=19,643,130@9.13GiB bodies=19,643,025@539.27GiB receipts=19,643,025@185.97GiB eta=1.822s
```

How long does it usually take？

and the  "eta=1.822s" in  "Syncing: chain download in progress" will never be 0

**Comment by FuxingGG** [comment]
geth version 1.13.14-stable-2bd6bd01

**Comment by rjl493456442** [comment]
In the sync procedure, there are two categories of data being downloaded: (a) state data and (b) chain segment data.

As the log indicates, your chain data is almost synced up, while the state data is still in the healing stage with pending=38886 ongoing requests.

You have to wait until both categories are fully synced up.

**Comment by FuxingGG** [comment]
But both have been like this for days

**Comment by junghyun0783** [comment]
@FuxingGG 
hello...
I have been suffering from the same symptoms for several days.
Has synchronization completed?
If synchronization is in progress...
Is it possible to share geth and prysm commands?

Here is my geth log for reference.
```
INFO [04-23|11:48:05.209] Syncing: state healing in progress       accounts=41156@2.61MiB    slots=156,041@11.96MiB codes=34099@141.61MiB nodes=6,339,832@1.28GiB pending=10071
INFO [04-23|11:48:06.839] Syncing: chain download in progress      synced=100.00% chain=26.98GiB headers=5,757,294@1.27GiB bodies=5,757,174@21.91GiB receipts=5,757,174@3.80GiB eta=24m21.882s
INFO [04-23|11:48:14.846] Syncing: chain download in progress      synced=100.00% chain=26.98GiB headers=5,757,295@1.27GiB bodies=5,757,174@21.91GiB receipts=5,757,174@3.80GiB eta=24m36.006s
INFO [04-23|11:48:15.086] Syncing: state healing in progress       accounts=41355@2.62MiB    slots=156,118@11.97MiB codes=34114@141.68MiB nodes=6,340,624@1.28GiB pending=10096
```

**Comment by FuxingGG** [comment]
> @FuxingGG hello... I have been suffering from the same symptoms for several days. Has synchronization completed? If synchronization is in progress... Is it possible to share geth and prysm commands?
> 
> Here is my geth log for reference.
> 
> ```
> INFO [04-23|11:48:05.209] Syncing: state healing in progress       accounts=41156@2.61MiB    slots=156,041@11.96MiB codes=34099@141.61MiB nodes=6,339,832@1.28GiB pending=10071
> INFO [04-23|11:48:06.839] Syncing: chain download in progress      synced=100.00% chain=26.98GiB headers=5,757,294@1.27GiB bodies=5,757,174@21.91GiB receipts=5,757,174@3.80GiB eta=24m21.882s
> INFO [04-23|11:48:14.846] Syncing: chain download in progress      synced=100.00% chain=26.98GiB headers=5,757,295@1.27GiB bodies=5,757,174@21.91GiB receipts=5,757,174@3.80GiB eta=24m36.006s
> INFO [04-23|11:48:15.086] Syncing: state healing in progress       accounts=41355@2.62MiB    slots=156,118@11.97MiB codes=34114@141.68MiB nodes=6,340,624@1.28GiB pending=10096
> ```

I have solved this problem by replacing the SSD. After I replaced the SSD, I copied the entire folder and re-ran the same commands, and healing ended in about a few hours.
my commands:
sudo geth  --cache 32768 --datadir /media/pengyun/data2/fx/ETH/ethereum/execution --http --http.addr 0.0.0.0   --http.api "eth,net,engine,web3" --ws --ws.addr 0.0.0.0  --ws.api "eth,net,engine,web3"  --txlookuplimit 0  --rpc.gascap 0  --rpc.txfeecap 0 --authrpc.addr 0.0.0.0  --authrpc.port 8551  --authrpc.vhosts localhost --authrpc.jwtsecret /media/pengyun/data2/fx/ETH/secrets/jwt.hex --rpc.allow-unprotected-txs --maxpeers 2000

sudo ./prysm.sh beacon-chain --execution-endpoint=http://localhost:8551 --mainnet --jwt-secret=/media/pengyun/data2/fx/ETH/secrets/jwt.hex --checkpoint-sync-url=https://beaconstate.info --genesis-beacon-api-url=https://beaconstate.info --datadir /media/pengyun/data2/fx/ETH/ethereum/consensus

**Comment by junghyun0783** [comment]
@FuxingGG 
Ah, I see! Thank you for your kind reply!
Even though I am currently using the sepolia testnet, synchronization is taking too long.
Before, when I used goerli, it worked quickly...
Does sepolia itself originally aim for SSD specifications?

**Comment by junghyun0783** [comment]
@FuxingGG 
thank!! i try it!~
