### ISSUE TITLE
Beacon root contract in dev mode and private chains

### ISSUE THREAD

**Issue by s1na** [ethereum/go-ethereum#29539]
[EIP-4788](https://eips.ethereum.org/EIPS/eip-4788) introduces a system contract which is deployed as a normal contract to the state. However it is required for networks which have the Cancun fork enabled. It is a bug when a dev chain or private chain with Cancun enabled is deployed and it is missing the beacon root contract.

For dev-mode, we should add the beacon root contract to the [genesis alloc](https://github.com/ethereum/go-ethereum/blob/3705acd1a97b2cc9bbb092b326a9d8cfbc42037a/core/genesis.go#L576). As for private chain, IMO the least we should do is refuse `geth init` in case Cancun is enabled and the genesis alloc is missing the beacon root code at the correct address.

**Comment by SeungjinPark2** [comment]
Based on my research, in dev-mode the block creation process is done by [simulated-beacon's sealing block](https://github.com/ethereum/go-ethereum/blob/master/eth/catalyst/simulated_beacon_api.go#L46l).
And I could check while sealing block, it raises error `WARN [04-17|05:36:43.458] Error performing sealing work            err="Invalid parameters"`.
The main reason was [here](https://github.com/ethereum/go-ethereum/blob/master/eth/catalyst/api.go#L479).
I'm not sure but it seems that we need to implement proper sealing process of post Cancun.

**Comment by holiman** [comment]
Sorry, I forgot there was still a task to do here (add the beacon root contract to the [genesis alloc](https://github.com/ethereum/go-ethereum/blob/3705acd1a97b2cc9bbb092b326a9d8cfbc42037a/core/genesis.go#L576).)

**Comment by 0xbeny** [comment]
> Hi @holiman can I work on this?
WIP, The PR is finishing soon :)

**Comment by 0xbeny** [comment]
Kindly find the implementation here: #29655
