### ISSUE TITLE
fatal error: unexpected signal during runtime execution when making DAG

### ISSUE THREAD

**Issue by hievan2016** [ethereum/go-ethereum#2954]
#### System information

Version: 1.4.7-stable-667a386d
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.4
OS: linux
GOPATH=
GOROOT=/usr/local/go

#### Expected behaviour

Geth run without crash

#### Actual behaviour

We changed the source code to use fix difficulty (0x10000), and then set up a private network with 
4 nodes, most nodes crashed after 1 day with this error.

#### Backtrace

I0827 04:31:50.098895 p2p/dial.go:263] dial tcp 119.29.100.149:30303 (9ec854079457)
I0827 04:31:50.100814 p2p/server.go:590] Accepted conn 119.29.100.149:35512
I0827 04:31:50.102899 p2p/server.go:628] inbound conn 9ec85407945703fa 119.29.100.149:35512 failed checkpoint posthandshake: Connected to self
I0827 04:31:50.103716 p2p/server.go:628] static dial conn 9ec85407945703fa 119.29.100.149:30303 failed checkpoint posthandshake: Connected to self
I0827 04:31:50.533155 eth/downloader/downloader.go:1942] Quality of service: rtt 2s, conf 1.000, ttl 6.000006s
I0827 04:31:52.533328 eth/downloader/downloader.go:1942] Quality of service: rtt 2s, conf 1.000, ttl 6.000006s
fatal error: unexpected signal during runtime execution
[signal 0x7 code=0x2 addr=0x7f9b83567000 pc=0xc1a1f6]

runtime stack:
runtime.throw(0x110a0a0, 0x2a)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 58 [syscall, locked to thread]:
runtime.cgocall(0xc17c50, 0xc8208e3a38, 0x7f9b00000000)
        /usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc8208e39d0 sp=0xc8208e39a0
github.com/ethereum/ethash._Cfunc_ethash_full_new_internal(0x7f9b840008e0, 0xa8628b54d9ec0d29, 0xc86f3888a94503d6, 0xf608404895bca64b, 0x63e5f30e16932f36, 0x407fff80, 0x7f9b840008c0, 0xc1b310, 0x0)
        ??:0 +0x3d fp=0xc8208e3a38 sp=0xc8208e39d0
github.com/ethereum/ethash.(*dag).generate.func1()
        /mnt/vdb/ethereum_code/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:271 +0x453 fp=0xc8208e3bf0 sp=0xc8208e3a38
sync.(*Once).Do(0xc826490d60, 0xc8208e3c28)
        /usr/local/go/src/sync/once.go:44 +0xe4 fp=0xc8208e3c18 sp=0xc8208e3bf0
github.com/ethereum/ethash.(*dag).generate(0xc826490d40)
        /mnt/vdb/ethereum_code/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:277 +0x45 fp=0xc8208e3c40 sp=0xc8208e3c18
github.com/ethereum/ethash.MakeDAG(0x7530, 0x0, 0x0, 0x0, 0x0)
        /mnt/vdb/ethereum_code/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:303 +0x1f5 fp=0xc8208e3cf8 sp=0xc8208e3c40
github.com/ethereum/go-ethereum/eth.(*Ethereum).StartAutoDAG.func1(0xc8202e8120)
        /mnt/vdb/ethereum_code/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:474 +0x9ce fp=0xc8208e3f98 sp=0xc8208e3cf8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc8208e3fa0 sp=0xc8208e3f98
created by github.com/ethereum/go-ethereum/eth.(*Ethereum).StartAutoDAG
        /mnt/vdb/ethereum_code/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:489 +0x48

**Comment by karalabe** [comment]
Without providing the exact modifications you made to the ethash code, I don't see how we could figure out what goes wrong. Also tbh, it's a bit odd that you report an issue that only happens with your modifications. My gut feeling is that the bug is somewhere in your modified code :)
