### ISSUE TITLE
problem with on-demand block generation in new geth versions

### ISSUE THREAD

**Issue by zxsimba** [ethereum/go-ethereum#29540]
#### System information

Geth version: 1.13.14
OS & Version: Linux

#### Expected behaviour
geth generates blocks on demand and fast

#### Actual behaviour
I got this error in geth dev mode:

"Current full block not old enough to freeze number"

which apparently contradicts on-demand block generation

I think that this error should not be raised in dev mode

#### Steps to reproduce the behaviour
write a script to send many transactions in parallel 

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by rjl493456442** [comment]
Can you please share a bit more logs?

**Comment by zxsimba** [comment]
eth-node-1  | DEBUG[04-15|11:55:10.556] Current full block not old enough to freeze number=224       hash=92bd72..dac24b delay=90000
eth-node-1  | DEBUG[04-15|11:55:25.783] Executing EVM call finished              runtime="319.933µs"
eth-node-1  | TRACE[04-15|11:55:25.824] Pooled new future transaction            hash=589cb9..b83721 from=0x90F79bf6EB2c4f870365E785982E1f101E93b906 to=0x5FbDB2315678afecb367f032d93F642f64180aa3
eth-node-1  | INFO [04-15|11:55:25.824] Submitted transaction                    hash=0x589cb9608f162e632c9dae5b3e6433ca30a232f352cca38a7c9f874e9cb83721 from=0x90F79bf6EB2c4f870365E785982E1f101E93b906 nonce=17 recipient=0x5FbDB2315678afecb367f032d93F642f64180aa3 value=0
eth-node-1  | DEBUG[04-15|11:55:30.571] Transaction pool status report           executable=2 queued=9 stales=0
eth-node-1  | DEBUG[04-15|11:56:10.556] Current full block not old enough to freeze number=224       hash=92bd72..dac24b delay=90000
eth-node-1  | DEBUG[04-15|11:56:10.648] Couldn't get external IP                 err="no UPnP or NAT-PMP router discovered" interface="UPnP or NAT-PMP"
eth-node-1  | DEBUG[04-15|11:56:25.944] Executing EVM call finished              runtime="63.509µs"
eth-node-1  | DEBUG[04-15|11:57:10.556] Current full block not old enough to freeze number=224       hash=92bd72..dac24b delay=90000
eth-node-1  | DEBUG[04-15|11:58:10.556] Current full block not old enough to freeze number=224       hash=92bd72..dac24b delay=90000
eth-node-1  | DEBUG[04-15|11:58:10.648] Couldn't get external IP                 err="no UPnP or NAT-PMP router discovered" interface="UPnP or NAT-PMP"
eth-node-1  | DEBUG[04-15|11:58:25.952] Executing EVM call finished              runtime="99.423µs"
eth-node-1  | DEBUG[04-15|11:59:10.556] Current full block not old enough to freeze number=224       hash=92bd72..dac24b delay=90000

**Comment by zxsimba** [comment]
`
eth-node-1  | DEBUG[04-15|11:55:10.556] Current full block not old enough to freeze number=224       hash=92bd72..dac24b delay=90000
eth-node-1  | DEBUG[04-15|11:55:25.783] Executing EVM call finished              runtime="319.933µs"
eth-node-1  | TRACE[04-15|11:55:25.824] Pooled new future transaction            hash=589cb9..b83721 from=0x90F79bf6EB2c4f870365E785982E1f101E93b906 to=0x5FbDB2315678afecb367f032d93F642f64180aa3
eth-node-1  | INFO [04-15|11:55:25.824] Submitted transaction                    hash=0x589cb9608f162e632c9dae5b3e6433ca30a232f352cca38a7c9f874e9cb83721 from=0x90F79bf6EB2c4f870365E785982E1f101E93b906 nonce=17 recipient=0x5FbDB2315678afecb367f032d93F642f64180aa3 value=0
eth-node-1  | DEBUG[04-15|11:55:30.571] Transaction pool status report           executable=2 queued=9 stales=0
eth-node-1  | DEBUG[04-15|11:56:10.556] Current full block not old enough to freeze number=224       hash=92bd72..dac24b delay=90000
eth-node-1  | DEBUG[04-15|11:56:10.648] Couldn't get external IP                 err="no UPnP or NAT-PMP router discovered" interface="UPnP or NAT-PMP"
eth-node-1  | DEBUG[04-15|11:56:25.944] Executing EVM call finished              runtime="63.509µs"
eth-node-1  | DEBUG[04-15|11:57:10.556] Current full block not old enough to freeze number=224       hash=92bd72..dac24b delay=90000
eth-node-1  | DEBUG[04-15|11:58:10.556] Current full block not old enough to freeze number=224       hash=92bd72..dac24b delay=90000
eth-node-1  | DEBUG[04-15|11:58:10.648] Couldn't get external IP                 err="no UPnP or NAT-PMP router discovered" interface="UPnP or NAT-PMP"
eth-node-1  | DEBUG[04-15|11:58:25.952] Executing EVM call finished              runtime="99.423µs"
eth-node-1  | DEBUG[04-15|11:59:10.556] Current full block not old enough to freeze number=224       hash=92bd72..dac24b delay=90000
`

**Comment by rjl493456442** [comment]
> Current full block not old enough to freeze

it's a debug level log and it's printed as expected

> geth generates blocks on demand and fast

Looks like your block is not created even with newly submitted transaction. Could you please share the commend for launching geth?

**Comment by zxsimba** [comment]
Thanks, we pass following command line arguments to geth:

```
      --rpc.txfeecap 360
      --nodiscover
      --maxpeers 0
      --dev
      --datadir .
      --port 30306
      --networkid 4444
      --unlock 0xFe2CcaE8462198801938A207dFdA3c65c525809d
      --password password.txt
      --authrpc.port 8546
      --mine
      --miner.etherbase 0xFe2CcaE8462198801938A207dFdA3c65c525809d
      --http
      --http.addr '0.0.0.0'
      --http.port 8545
      --http.vhosts '*'
      --http.api admin,eth,miner,net,txpool,debug,web3
      --allow-insecure-unlock
      --ipcpath "/sock/geth.ipc"
      --verbosity 3
```

**Comment by fjl** [comment]
```
eth-node-1  | TRACE[04-15|11:55:25.824] Pooled new future transaction            hash=589cb9..b83721 from=0x90F79bf6EB2c4f870365E785982E1f101E93b906 to=0x5FbDB2315678afecb367f032d93F642f64180aa3
eth-node-1  | INFO [04-15|11:55:25.824] Submitted transaction                    hash=0x589cb9608f162e632c9dae5b3e6433ca30a232f352cca38a7c9f874e9cb83721 from=0x90F79bf6EB2c4f870365E785982E1f101E93b906 nonce=17 recipient=0x5FbDB2315678afecb367f032d93F642f64180aa3 value=0
```

From these log messages, it is apparent that the tx you sent to the node has a nonce in the future. It can therefore not be included in a block, and geth will not produce a block until you send a tx to fill the nonce gap.

```
eth-node-1  | DEBUG[04-15|11:58:10.556] Current full block not old enough to freeze number=224       hash=92bd72..dac24b delay=90000
```

This is an internal message and it is not related to your problem.
