### ISSUE TITLE
Sepolia static peers congested

### ISSUE THREAD

**Issue by keithchew** [ethereum/go-ethereum#29547]
Using devp2p, I tested the peers in SepoliaBootnodes defined in bootnodes.go. All the peers often respond with too many peers connected, indicating that these peers are online but just overloaded!

Are there plans to increase the number of static peers?

**Comment by Eisenhower1986** [comment]
The devp2p protocol used in the Ethereum code does connect to a predefined set of bootstrap nodes, which are used to discover other nodes in the network. Regarding the number and types of nodes, the Ethereum development team will conduct regular evaluation and adjustments to ensure the stability and performance of the network. Increasing the number of static peers may increase network stability, but may also increase load and complexity in the network.
