### ISSUE TITLE
Processing error for `debug_traceBlockByNumber` requests

### ISSUE THREAD

**Issue by thetroyharris** [ethereum/go-ethereum#29546]
#### System information

Geth version: `geth version 1.13.12-stable-02eb36af`
CL client & version: `Prysm @ v4.2.1`
OS & Version: `Linux`
Commit hash : 

#### Expected behaviour
- Return my `debug_traceBlockByNumber` requests and not throw the `execution timeout` error

#### Actual behaviour
- Returning `error: execution timeout` when processing a large number of `debug_traceBlockByNumber` requests even when passed `--rpc.evmtimeout 0` 
- I also have `RPCEVMTimeout=0` line in the config file

#### Steps to reproduce the behaviour
- I was submitting `debug_traceBlockByNumber` requests for a block range of around 200,000 blocks via [cryo](https://github.com/paradigmxyz/cryo)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by s1na** [comment]
Please pass in timeout as a parameter to `debug_traceBlockByNumber(blockNum, { timeout: '1h' })`.

**Comment by s1na** [comment]
Assuming that solved the issue, will close.
