### ISSUE TITLE
Get rid of genesis/terminalTotalDifficultyPassed

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#29555]
Since Geth v1.14 can only run in post-merge mode, we can just assume that all networks are like that and don't even bother with checking? Tho perhaps we can leave the flag in the genesis for a major version and then remove it? Needs a bit of thought.

**Comment by karalabe** [comment]
Just a small triage update. We kind of all agree to remove this field, but maybe wait 1-2-3 small releases just to have time to phase out pre-merge networks.

**Comment by karalabe** [comment]
Support for non merge networks is being dropped in 1.14 (https://github.com/ethereum/go-ethereum/pull/29169), so this issue should be "fixed" in light of that timing wise.

**Comment by s1na** [comment]
Consensus on triage seems to be that the issue has marinated and now this field can be removed.

**Comment by jwasinger** [comment]
This was done in https://github.com/ethereum/go-ethereum/pull/30609
