### ISSUE TITLE
Incorrect receipt for the tx 0x8b21c385f137ce75b3f2b0ee84040b629208d5037d0101d23c8bd2ce98e3a89b

### ISSUE THREAD

**Issue by AlbertMakhortov** [ethereum/go-ethereum#29550]
Ethereum sepolia

#### System information

Geth version: v1.13.11
CL client & version: nimbus amd64-v24.2.0
OS & Version: linux

#### Expected behaviour
when requesting  eth_getTransactionReceipt for 0x8b21c385f137ce75b3f2b0ee84040b629208d5037d0101d23c8bd2ce98e3a89b
expected transactionIndex is 0x26

#### Actual behaviour
transactionIndex in response is 0x14
full response:
```
{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x5b9878a504a93085ae7b240d511d7b7eb64058925fb42dd6470bed9f61341973","blockNumber":"0x56b2d0","contractAddress":null,"cumulativeGasUsed":"0xadc32","effectiveGasPrice":"0xee9ab034","from":"0x3c352ea32dfbb757ccdf4b457e52daf6ecc21917","gasUsed":"0x5208","logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","status":"0x1","to":"0xe078fca4af16626da5f71875f87d891f1b932ad4","transactionHash":"0x7cb724246409190caa7789a29a652948a920ab4d9ed1e0df5aaa9fe615f20564","transactionIndex":"0x14","type":"0x0"}}
```
We cannot reproduce this issue right now, because it was fixed by restarting the node, but the problem has arisen not for the first time, and we want to understand what is causing it

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by rjl493456442** [comment]
Probably the block with same transaction set but different order?

**Comment by namiloh** [comment]
Then the blockhash would mismatch. Unless I have misunderstood the bug

**Comment by rjl493456442** [comment]
Right, the transactionRoot will be different.

**Comment by rjl493456442** [comment]
```
{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x5b9878a504a93085ae7b240d511d7b7eb64058925fb42dd6470bed9f61341973","blockNumber":"0x56b2d0","contractAddress":null,"cumulativeGasUsed":"0xadc32","effectiveGasPrice":"0xee9ab034","from":"0x3c352ea32dfbb757ccdf4b457e52daf6ecc21917","gasUsed":"0x5208","logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","status":"0x1","to":"0xe078fca4af16626da5f71875f87d891f1b932ad4","transactionHash":"0x7cb724246409190caa7789a29a652948a920ab4d9ed1e0df5aaa9fe615f20564","transactionIndex":"0x14","type":"0x0"}}
```

Apparently the responded transaction hash is `0x7cb724246409190caa7789a29a652948a920ab4d9ed1e0df5aaa9fe615f20564`, located at the correct position `0x14`.

@AlbertMakhortov could you please restart your geth node and then retrieve the receipt? Just want to confirm it's relevant with a bug we have already fixed.

**Comment by AlbertMakhortov** [comment]
@rjl493456442 we have restarted the node, and it helped 
but we want to understand what caused it in the first place, because it is not the first time it happened

**Comment by avinashbo** [comment]
> Just want to confirm it's relevant with a bug we have already fixed.

@rjl493456442 Can you please point me to this bug/fix?

**Comment by holiman** [comment]
Bug: https://github.com/ethereum/go-ethereum/issues/29261
Fix: https://github.com/ethereum/go-ethereum/pull/29343
