### ISSUE TITLE
gcmode=archive with state.scheme=path

### ISSUE THREAD

**Issue by sergerad** [ethereum/go-ethereum#29558]
# Rationale

### Why should this feature exist?

Missing component of the path-based state scheme. Mentioned that it will be worked upon: https://blog.ethereum.org/2023/09/12/geth-v1-13-0
> For archive node operators, the new data model will be compatible with archive nodes (and will bring the same amazing database sizes as Erigon or Reth), but needs a bit more work before it can be enabled.

### What are the use-cases?

Path based state scheme with state archival.

# Implementation

### Do you have ideas regarding the implementation of this feature?

Not at this stage. Raising issue to ask the question where this feature is at (can't see other issues). If it is already in development or not?

Does `--history.state=0` and `--history.transactions=0` have the same effect as `--gcmode=archive` for path scheme?

### Are you willing to implement this feature?

Yes, happy to contribute.

**Comment by rjl493456442** [comment]
It's in development!

In path scheme, `--gcmode=archive` doesn't really work as the archive node is not shipped yet. In theory, `--gcmode=archive` will set `--history.state=0` and `--history.transaction=0` for you.

**Comment by sergerad** [comment]
Thanks @rjl493456442 do you have an ETA on this being complete? Are there any pieces of work we can help with?

Regarding:
> In theory, --gcmode=archive will set --history.state=0 and --history.transaction=0 for you.

The state history field seems to be fed directly into the pathdb logic so would expect those history flags to cause some behaviour change, whereas gcmode=archive is completely ignored. Do you know if having history.state=0 has similar effect to an archive?

**Comment by karalabe** [comment]
There's no ETA for now, sorry. But we're chugging towards it.
