### ISSUE TITLE
Pipes Closed

### ISSUE THREAD

**Issue by RobbieRich** [ethereum/go-ethereum#2957]
#### System information

Geth version: 1.4.11
OS & Version: Windows 10
Commit hash : 18Mh

Hello there Mining friends , got this message at the end , first three days no more progress in my geth rpc , however mining going good , and then The pipes are closed ... Does anyone know what this means and what i should do  and above that Mining Ops is still going on ....Below is what my rpc is saying to me ... Specially the end is interesting .... It is in Dutch , but means that the pipes are closing ...
And should i just close geth and start anew one ...
Thank you all and May the mining be Strong !

I0825 15:19:14.185155 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 110 txs in 129.0075ms. #2137206 [e4f1492a / e4f1492a]
I0825 15:19:14.493172 miner/worker.go:573] commit new work on block 2137207 with 47 txs & 0 uncles. Took 306.0181ms
I0825 15:19:39.488604 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 43 txs in 45.0032ms. #2137207 [d8d49707 / d8d49707]
I0825 15:19:39.912628 miner/worker.go:573] commit new work on block 2137208 with 181 txs & 0 uncles. Took 421.0239ms
I0825 15:19:50.665243 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 177 txs in 237.0138ms. #2137208 [6362cdf7 / 6362cdf7]
I0825 15:19:50.802251 miner/worker.go:573] commit new work on block 2137209 with 83 txs & 0 uncles. Took 134.0069ms
I0825 15:19:53.365398 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 83 txs in 94.0055ms. #2137209 [74315504 / 74315504]
I0825 15:19:53.475404 miner/worker.go:573] commit new work on block 2137210 with 18 txs & 0 uncles. Took 107.0056ms
I0825 15:20:24.323171 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 15.9994ms. #2137210 [5b7265cd / 5b7265cd]
I0825 15:20:24.872203 miner/worker.go:573] commit new work on block 2137211 with 213 txs & 0 uncles. Took 547.0315ms
I0828 20:16:04.778699 rpc/server.go:376] De pipes wordt gesloten.
I0828 20:16:04.781700 rpc/server.go:376] De pipes wordt gesloten.

**Comment by fjl** [comment]
@bas-vk please look

**Comment by RobbieRich** [comment]
ok I did and dont know what i am looking at , or how this answers my question , sorry bout that ... please specify the link ... Thanks any how for the answer !!!

**Comment by fjl** [comment]
I meant that the GitHub user @bas-vk, who is a go-ethereum member, should please look at this issue.

**Comment by samlavery** [comment]
Do you still get blocks, if so you are probably fine, if not, check your peer count.  If your peers are 0, something is closing your tcp sockets, like a router or firewall.

**Comment by RobbieRich** [comment]
Dear Sam , thanks for the reply , not sure about the blocks , cause hashing with 20Mh s , but peers are 0 , so started the geth again !hope i am doing everything right though , get a lot of peer time-outs though , dropping due dao fork or so …

 

Van: Sam Lavery [mailto:notifications@github.com] 
Verzonden: vrijdag 9 september 2016 1:33
Aan: ethereum/go-ethereum <go-ethereum@noreply.github.com>
CC: RobbieRich <defamilieschoemaker@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [ethereum/go-ethereum] Pipes Closed (#2957)

 

Do you still get blocks, if so you are probably fine, if not, check your peer count. If your peers are 0, something is closing your tcp sockets, like a router or firewall.

**Comment by bas-vk** [comment]
A search on the internet on `De pipes wordt gesloten.` seems to suggest that the client has closed the connection as you mentioned. In this case geth tried to write a RPC response back to the client but fails with this error.

One thing that looks odd is the long time gap of almost 5 hours between the error and the last moment everything seems to work fine (or perhaps these are the 3 days). Did you remove some logs? Did geth responded when you attach the console to it?

Also, please check you geth version. Geth 1.4.11 prints the first log at a different line number.

**Comment by RobbieRich** [comment]
Dear Bas , thought it was odd indeed and have not removed any logs , that i know off ! not sure what you mean by attaching geth tot he console ?

When i start up get hit always starts up correct i think , no errors of any kind …

Greetings Robbie

 

Van: bas-vk [mailto:notifications@github.com] 
Verzonden: vrijdag 9 september 2016 9:53
Aan: ethereum/go-ethereum <go-ethereum@noreply.github.com>
CC: RobbieRich <defamilieschoemaker@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [ethereum/go-ethereum] Pipes Closed (#2957)

 

A search on the internet on De pipes wordt gesloten. seems to suggest that the client has closed the connection as you mentioned. In this case geth tried to write a RPC response back to the client but fails with this error.

One thing that looks odd is the long time gap of almost 5 hours between the error and the last moment everything seems to work fine (or perhaps these are the 3 days). Did you remove some logs? Did geth responded when you attach the console to it?

Also, please check you geth version. Geth 1.4.11 prints the first log at a different line number.

**Comment by RobbieRich** [comment]
He there Bas , getting new problems now , see below , had trouble finidng peers and bad blocks , so saw this , 

 

 

 

 

C:\>geth --nat=none

I0910 07:37:04.645973 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to C:\Users\FSTBeneden\AppData\Roaming\Ethereum\chaindata

I0910 07:37:05.361916 cmd/utils/flags.go:842] ------------------------------------------------------------------------------------------------

I0910 07:37:05.364916 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!

I0910 07:37:05.367916 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.

I0910 07:37:05.370917 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!

I0910 07:37:05.373917 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------

I0910 07:37:05.377917 ethdb/database.go:169] closed db:C:\Users\FSTBeneden\AppData\Roaming\Ethereum\chaindata

I0910 07:37:05.386918 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to C:\Users\FSTBeneden\AppData\Roaming\Ethereum\chaindata

I0910 07:37:05.882946 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to C:\Users\FSTBeneden\AppData\Roaming\Ethereum\dapp

I0910 07:37:05.908948 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1

I0910 07:37:05.910948 eth/backend.go:201] Blockchain DB Version: 3

I0910 07:37:05.914948 core/blockchain.go:206] Last header: #2231922 [20909b0b…] TD=58626708318703335014

I0910 07:37:05.917948 core/blockchain.go:207] Last block: #2231922 [20909b0b…] TD=58626708318703335014

I0910 07:37:05.920948 core/blockchain.go:208] Fast block: #2231922 [20909b0b…] TD=58626708318703335014

I0910 07:37:05.926949 p2p/server.go:313] Starting Server

I0910 07:37:05.997953 p2p/discover/udp.go:217] Listening, enode://e2228f30dd81ed8f99107d8887c23121805beae279105da40a6076a29d2fa7f626af3a4d00ac667e19b69024721b85d8f431f5db916a0cea86d2fbf3f411160b@[::]:30303

I0910 07:37:06.004953 p2p/server.go:556] Listening on [::]:30303

I0910 07:37:06.005953 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc

I0910 07:37:29.129277 eth/downloader/downloader.go:320] Block synchronisation started

I0910 07:37:32.475469 eth/handler.go:295] Peer 4a3b8690c2ba9bb7 [eth/63]: timed out DAO fork-check, dropping

I0910 07:37:36.038673 eth/downloader/downloader.go:1087] Peer a979fb575495b8d6 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: head header set (item 0) broke chain ordering: requested 1919809, got 2231936

I0910 07:37:43.564104 eth/handler.go:295] Peer ae2775270e97dabb [eth/63]: timed out DAO fork-check, dropping

I0910 07:37:44.041131 eth/handler.go:295] Peer 07943c6c079090eb [eth/63]: timed out DAO fork-check, dropping

I0910 07:37:57.945927 eth/downloader/downloader.go:1087] Peer 1118980bf48b0a36 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: head header set (item 0) broke chain ordering: requested 1919809, got 2231936

I0910 07:38:06.946443 eth/downloader/downloader.go:1087] Peer a979fb575495b8d6 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: head header set (item 0) broke chain ordering: requested 1919809, got 2231938

I0910 07:38:41.572425 eth/downloader/downloader.go:1087] Peer 1118980bf48b0a36 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: head header set (item 0) broke chain ordering: requested 1919809, got 2231939

I0910 07:38:47.113743 eth/handler.go:295] Peer b110c79ca7bef1d3 [eth/63]: timed out DAO fork-check, dropping

I0910 07:39:18.684594 eth/handler.go:295] Peer 1118980bf48b0a36 [eth/63]: timed out DAO fork-check, dropping

I0910 07:39:22.593818 eth/handler.go:295] Peer de471bccee3d0422 [eth/63]: timed out DAO fork-check, dropping

I0910 07:39:50.270403 eth/downloader/downloader.go:1087] Peer 1118980bf48b0a36 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: head header set (item 0) broke chain ordering: requested 1919809, got 2231944

I0910 07:39:58.763889 core/blockchain.go:963] imported 3 block(s) (0 queued 0 ignored) including 5 txs in 2.4801419s. #2231925 [69fb306c / 617086ae]

I0910 07:39:59.235917 core/blockchain.go:963] imported 20 block(s) (0 queued 0 ignored) including 157 txs in 466.027ms. #2231945 [b6c8b336 / 823817f1]

Greetings andd thanks again … Robbie

Van: bas-vk [mailto:notifications@github.com] 
Verzonden: vrijdag 9 september 2016 9:53
Aan: ethereum/go-ethereum <go-ethereum@noreply.github.com>
CC: RobbieRich <defamilieschoemaker@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [ethereum/go-ethereum] Pipes Closed (#2957)

 

A search on the internet on De pipes wordt gesloten. seems to suggest that the client has closed the connection as you mentioned. In this case geth tried to write a RPC response back to the client but fails with this error.

One thing that looks odd is the long time gap of almost 5 hours between the error and the last moment everything seems to work fine (or perhaps these are the 3 days). Did you remove some logs? Did geth responded when you attach the console to it?

Also, please check you geth version. Geth 1.4.11 prints the first log at a different line number.

**Comment by samlavery** [comment]
All that matters is this line ```
I0910 07:39:59.235917 core/blockchain.go:963] imported 20 block(s) (0 queued 0 ignored) including 157 txs in 466.027ms. #2231945 [b6c8b336 / 823817f1]
``` it looks like you have connectivity and it's working.  You may be on the wrong fork tho...

**Comment by RobbieRich** [comment]
Thanks for your reaction ! And thought i was on the support dao fork … why do you think i am on the wrong one ? Anyway super thanks again ! Robbie

 

Van: Sam Lavery [mailto:notifications@github.com] 
Verzonden: maandag 12 september 2016 23:59
Aan: ethereum/go-ethereum <go-ethereum@noreply.github.com>
CC: RobbieRich <defamilieschoemaker@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [ethereum/go-ethereum] Pipes Closed (#2957)

 

All that matters is this line 
I0910 07:39:59.235917 core/blockchain.go:963] imported 20 block(s) (0 queued 0 ignored) including 157 txs in 466.027ms. #2231945 [b6c8b336 / 823817f1]
it looks like you have connectivity and it's working. You may be on the wrong fork tho...

**Comment by bas-vk** [comment]
You are on the correct fork and everything seems to work. I don't think there is an issue anymore? If not, could you close this? Make sure you have the latest version.
