### ISSUE TITLE
Geth v1.13.15 not available on the PPA on Ubuntu 18.04 (bionic)

### ISSUE THREAD

**Issue by remyroy** [ethereum/go-ethereum#29576]
#### System information

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

#### Expected behaviour

Running these commands should install the latest Geth version (v1.13.15 as of today) on a clean Ubuntu 18.04 (bionic) installation.

```
sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt update -y
sudo apt install -y geth
sudo apt-cache policy geth
```

Here is the result:
```
geth:
  Installed: 1.13.14+build29502+bionic
  Candidate: 1.13.14+build29502+bionic
  Version table:
 *** 1.13.14+build29502+bionic 500
        500 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```
```
$ geth --version
geth version 1.13.14-stable-2bd6bd01
```

#### Actual behaviour

Version 1.13.14 is the latest version available from the PPA on Ubuntu 18.04 (bionic)

#### Steps to reproduce the behaviour

1. Install Ubuntu 18.04 (bionic) in a VM
2. Run the commands above
3. Notice that version 1.13.14 is installed

**Comment by karalabe** [comment]
I've starting to have concerns about Launchpad/PPA. It's the many-th time where a build fails with a missing file, only to restart it and succeed (doh, the file is there). Seems there's some clusterfuck in Launchpad.

Either way, requested a rebuild, it succeeded, should be pushed now - or soon.
