### ISSUE TITLE
How to use other erc20 tokens as gas burn 

### ISSUE THREAD

**Issue by starlzy** [ethereum/go-ethereum#29582]
Hi,
please help me for this

How to use other erc20 tokens as gas burn on op chain

**Comment by MariusVanDerWijden** [comment]
The gas refund mechanism was removed/nerfed in order to prevent gas tokens.
This is not the right place to ask questions like this, please only use this issue trackers for issues relating to go-ethereum, you can use the stackexchange https://ethereum.stackexchange.com/ for general questions
