### ISSUE TITLE
Synchronization is complete, but get_blockNumber returns 0x0.

### ISSUE THREAD

**Issue by junghyun0783** [ethereum/go-ethereum#29585]
hello.
I really want to hear the answer I want.
This is the current result when calling eth_syncing RPC.
When calling eth_blockNumber RPC, the result value continues to be 0x0.
What I want is when the result value will be output as a block number rather than 0x0. I kept asking this, but he gave me a different answer and said "close".
please. When will the result value output the desired value instead of 0x0?

The initialization process is complete.
Even after two days, get_blockNumber is currently returning 0x0.
It seems like all initialization and synchronization has been completed, but why does it still return 0x0?...
Here is the command for your reference.

`cmd /k geth --sepolia -syncmode "snap" --http.api admin,eth,debug,net,txpool,personal,web3,engine -datadir ".\dataSepolia" -http --http.port 20201 --http.addr 0.0.0.0 --nat "any"  --rpc.allow-unprotected-txs --snapshot=false -ipcdisable --authrpc.jwtsecret ../consensus/jwt_sepolia.hex --authrpc.vhosts="*" --authrpc.addr=0.0.0.0`

`prysm.bat beacon-chain --execution-endpoint=http://localhost:8551 --sepolia --datadir=./prysm_data_sepolia --jwt-secret=../jwt_sepolia.hex --rpc-host=0.0.0.0 --grpc-gateway-host=0.0.0.0 --genesis-state=sepolia_genesis.ssz --suggested-fee-recipient=0x67CDB8344FFCa7aaaeda9e7a4F4f1A9cb4D1FC64`

Is there anything that needs to be modified in the geth command or CL command?

![image](https://github.com/ethereum/go-ethereum/assets/25001497/d11eeaa2-d212-4952-b7a2-40f4d9c78194)

**Comment by karalabe** [comment]
In your first screenshot you can see "state heal in progress". On the third on it also says in "healingTrieNodes" that it's still pulling some data from the network.
