### ISSUE TITLE
Evm t8n testcase is outdated

### ISSUE THREAD

**Issue by yerke26** [ethereum/go-ethereum#29608]
Evm t8n tool has outdated [testcase](https://github.com/ethereum/go-ethereum/blob/master/cmd/evm/testdata/29).
[This contract](https://github.com/ethereum/go-ethereum/blob/master/cmd/evm/testdata/29/alloc.json#L11) has HISTORY_BUFFER_LENGTH = 98304 (which is outdated), but now it has been updated to HISTORY_BUFFER_LENGTH=8191. (https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4788.md#specification)
Please update also the [result](https://github.com/ethereum/go-ethereum/blob/master/cmd/evm/testdata/29/exp.json)

**Comment by lightclient** [comment]
@yerke26 wanna take a stab at it?

**Comment by holiman** [comment]
feel free to open a PR if you want to change it
