### ISSUE TITLE
MakeSigner returns a London signer because IsCancun is false

### ISSUE THREAD

**Issue by redmaner** [ethereum/go-ethereum#29605]
#### System information

Geth version: `geth version` 1.13.5

#### Expected behaviour
When using the `types.MakeSigner` API to get a new signer for the chain on Sepolia network using `params.SepoliaChainConfig` expect a CancunSigner to be returned to handle blob transactions. Like this one: https://sepolia.etherscan.io/tx/0x92c9841af622875f0e58181f53c23edd8fc6793dbc47e6806218bf2e6efda806

#### Actual behaviour
When using the `types.MakeSigner` API for latest blocks on sepolia it returns the LondonSigner instead, which doesn't support blob transactions. It looks like https://github.com/ethereum/go-ethereum/blob/v1.13.15/params/config.go#L808 fails, because `params.SepoliaChainConfig.cancunTime` is `nil` instead of pointer to `0`.

Is this expected behaviour? I would expect Sepolia to always return a CancunSigner. 

**Edit:**
Same error applies to `params.MainnetChainConfig`

**Comment by fjl** [comment]
As far as I can see, the `CancunTime` of `params.SepoliaChainConfig` is not `nil`. https://github.com/ethereum/go-ethereum/blob/243cde0f54e407ba52c570295886083d6e7d651e/params/config.go#L111

**Comment by fjl** [comment]
Please check your go-ethereum version.
