### ISSUE TITLE
syncedStorage and healingTrienodes are not reduced. Why won't it decrease?

### ISSUE THREAD

**Issue by junghyun0783** [ethereum/go-ethereum#29607]
hello.....
My current version is as follows.
**geth version v1.13.14
prysm version v5.0.3**
--sepolia is running,
Initialization is complete.
I have a question.
eth_syncing RPC.

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "currentBlock": "0x57c7a6",
        "healedBytecodeBytes": "0x3cc8231",
        "healedBytecodes": "0x3435",
        "healedTrienodeBytes": "0x229ff3f2",
        "healedTrienodes": "0x2553a3",
        "healingBytecode": "0x0",
        "healingTrienodes": "0x454",
        "highestBlock": "0x57c7fc",
        "startingBlock": "0x57c574",
        "syncedAccountBytes": "0x1a666ccfa",
        "syncedAccounts": "0x1b94141",
        "syncedBytecodeBytes": "0x1f0ae410d",
        "syncedBytecodes": "0x13422c",
        "syncedStorage": "0x10d857e6",
        "syncedStorageBytes": "0xe382f4c2b",
        "txIndexFinishedBlocks": "0xffffffffffa89444",
        "txIndexRemainingBlocks": "0x0"
    }
}
```

Looking at the content, "healingTrienodes" does not decrease even after several hours.
Of course, “syncedStorage” is not decreasing either.
What is the problem?....Please help...
I want to end synchronization.

These are the geth and prysm commands for reference.

`geth --sepolia -syncmode "snap" --http.api admin,eth,debug,net,txpool,personal,web3,engine -datadir ".\dataSepolia" -http --http.port 20201 --http.addr 0.0.0.0 --nat "any"  --rpc.allow-unprotected-txs --snapshot=false -ipcdisable --authrpc.jwtsecret ../consensus/jwt_sepolia.hex --authrpc.vhosts="*" --authrpc.addr=0.0.0.0`

`beacon-chain --execution-endpoint=http://localhost:8551 --sepolia --datadir=./prysm_data_sepolia --jwt-secret=../jwt_sepolia.hex --rpc-host=0.0.0.0 --grpc-gateway-host=0.0.0.0 --genesis-state=sepolia_genesis.ssz --suggested-fee-recipient=0x67CDB8344FFCa7aaaeda9e7a4F4f1A9cb4D1FC64`

**Comment by holiman** [comment]
`healingTrienodes` is basically the progress of iterating down a huge tree. It's performing tasks, but also discovering new tasks as we progress down the tree. 
The idea is that eventually we finish all tasks, and right before the end it will go down towards zero.

**Comment by holiman** [comment]
If your computer (mainly IO, disk) is too slow, it won't ever complete sync. The state of ethereum is mutating _while you are syncing_. If the rate of change is higher than the rate of your sync, then you'll never complete.

**Comment by holiman** [comment]
Answered
