### ISSUE TITLE
swarm merge to develop 

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#2961]
# This issue helps track PRs leading to swarm merge into develop

This issue tracks the PRs necessary for swarm to be fully merged into develop
@fjl @obscuren 
- [x] https://github.com/ethereum/go-ethereum/pull/2930
- [x] https://github.com/ethereum/go-ethereum/pull/2926
- [x] https://github.com/ethereum/go-ethereum/pull/2952, https://github.com/ethereum/go-ethereum/pull/2963, https://github.com/ethereum/go-ethereum/pull/2972
- [x] https://github.com/ethereum/go-ethereum/pull/2922, https://github.com/ethereum/go-ethereum/pull/2683, https://github.com/ethereum/go-ethereum/pull/2958, https://github.com/ethereum/go-ethereum/pull/2964
- [x] https://github.com/ethereum/go-ethereum/pull/2956
- [x] https://github.com/ethereum/go-ethereum/pull/2965
- [x] https://github.com/ethereum/go-ethereum/pull/2914
- [x] https://github.com/ethereum/go-ethereum/pull/3108
- [x] cmd/bzzd - swarm daemonification https://github.com/ethereum/go-ethereum/pull/3247

**Comment by nagydani** [comment]
Is this simply a reference ticket with a TODO list?

**Comment by fjl** [comment]
done ;)

**Comment by zelig** [comment]
Swarm integration is now complete :)
