### ISSUE TITLE
 Having trouble syncing a new node with Clique PoA Geth? It seems like there might be an issue with peer connections. Any suggestions?

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#29664]
I am using Clique PoA geth When I tried to install a NEW node it's not working. it does not sync with the network. My current node is still working fine. On the synchronization of the new nodes 

I am using geth version v1.10.23-unstable 

Initially, I encountered these errors during new node synchronization.

- Warning: "Downloader queue stats"
- Warning: "Sync Failed, Dropping Peer"
- Error: "Retrieved hash chain is invalid: no peers available or all tried for download"
- Error: "Peer is unknown or unhealthy"
- Error: "Timeout"
- Error: "Pending request exists for joining peer"
- Error: "Expired request does not exist"
![image](https://github.com/ethereum/go-ethereum/assets/46569970/29e920be-2490-440e-9901-bac36798a7a9)

**Comment by karalabe** [comment]
Unfortunately we won't be able to help here. That version of Geth is very old (2 years) and we are constantly fixing things, so we can't really investigate code that is so far off our current status. Also additionally, we've just dropped Clique support altogether (forward syncing and mining) from mainline Geth and only post-merge networks are supported going forward.

**Comment by AsadullahSoomro** [comment]
@karalabe, Can this problem be fixed by using the newest stable version of Geth?
