### ISSUE TITLE
Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!

### ISSUE THREAD

**Issue by Z-fly** [ethereum/go-ethereum#29668]
![image](https://github.com/ethereum/go-ethereum/assets/10470892/96c54e03-03c1-40e0-9d60-b5989c5e19b8)

How to fix？

**Comment by Z-fly** [comment]
![image](https://github.com/ethereum/go-ethereum/assets/10470892/dfa0a112-dcac-48d5-aa10-4d52651ea977)
Paysm

**Comment by rjl493456442** [comment]
Your beacon client hasn't sent necessary consensus events for a while. Looks like your beacon client is still in initial-sync stage. You can probably try the *checkpoint sync* for fast bootstrap (https://eth-clients.github.io/checkpoint-sync-endpoints/).

**Comment by lyfsn** [comment]
Your Prism can't connect to other peers, check your firewall configuration.

**Comment by s1na** [comment]
I don't think this is a Geth issue. Closing.
