### ISSUE TITLE
eth_newFilter returns filter id in 'UNFORMATTED DATA' format

### ISSUE THREAD

**Issue by phleemac** [ethereum/go-ethereum#2966]
#### System information

Geth version: `geth 1.5.0-unstable`
OS & Version: Linux
#### Expected behaviour

According to doc https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter the return type of the filter id is 'QUANTITY'

And according to https://github.com/ethereum/wiki/wiki/JSON-RPC#output-hex-values 'QUANTITY' type should have no leading zeros

> WRONG: 0x0400 (no leading zeroes allowed)

So, I expected filter id from eth_newFilter to have no leading zeros
#### Actual behaviour

However, eth_newFilter sometimes return value with leading zero (e.g. 0x041e94c24c378a254f7faf8d29492479)

And after converting this filter id into valid QUANTITY format (i.e. leading zeros removed), the eth_getFilterChanges always returns nothing.

**Comment by bas-vk** [comment]
@phleemac thx for reporting this. This is fixed in the PR.

**Comment by fjl** [comment]
Fix released in 1.5.0.
