### ISSUE TITLE
Does Geth version 1.14.0 support the --syncmode fast option?

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#29679]
![image](https://github.com/ethereum/go-ethereum/assets/46569970/fa50f9c6-ac78-4ceb-8277-b063bfe75f59)

![image](https://github.com/ethereum/go-ethereum/assets/46569970/3b253248-4ed9-404d-ab47-49704c020640)

**Comment by karalabe** [comment]
Geth v.1.14 supports snap sync. However, Geth 1.14 does not work with non-merged networks any more.

**Comment by AsadullahSoomro** [comment]
Can bad blocks stop synchronization from working?
