### ISSUE TITLE
Apt on Ubuntu Jammy can't see the 1.14 version, can't upgrade

### ISSUE THREAD

**Issue by d-sfounis** [ethereum/go-ethereum#29675]
#### System information

Geth version: `1.13.15`
CL client & version: e.g. lighthouse@latest
OS & Version: Ubuntu Server 22.04 (Jammy)

#### Expected behaviour
`sudo apt update` then `sudo apt upgrade` should get `ethereum 1.14` for Jammy.

#### Actual behaviour
`apt` cannot upgrade `ethereum` to 1.14, the latest version it sees is still 1.13.15.

Here's the launchpad content link: http://ppa.launchpadcontent.net/ethereum/ethereum/ubuntu/pool/main/e/ethereum/

amd64-jammy .deb files are missing for `ethereum 1.14`, probably why `apt` can't match my release version with the respective package version.

**Comment by d-sfounis** [comment]
Just noticed, the PPA has builds failing:
https://launchpad.net/~ethereum/+archive/ubuntu/ethereum/+packages

**Comment by karalabe** [comment]
Yes, this was fixed on master already, but unfortunately we can't backport it into 1.14 any more. The issue was that we switched to a newer Go version and PPA can't build that, so we needed to add some extra build steps in between. We'll push a new release either this week or early next week and that will pick up 1.14.1

**Comment by winksaville** [comment]
@karalab, may I suggest that this information be added to announcements on Discord and other places that new versions are announced. If you casually look at the [PPA](https://launchpad.net/~ethereum/+archive/ubuntu/ethereum) it looks fine, it's not until you [view package details](https://launchpad.net/~ethereum/+archive/ubuntu/ethereum/+packages) you see the failure.
