### ISSUE TITLE
How can I create a POS Private Network by Geth 1.14.0？

### ISSUE THREAD

**Issue by STASWIT** [ethereum/go-ethereum#29671]
In Geth 1.14.0, it could not support POA private network anymore. However, none of document talk about create a POS Private Network. How can I do if I want to use the newest geth for private network?

**Comment by weiihann** [comment]
This [doc](https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet) from Prysm might be helpful.

Alternatively, you might want to look into [Kurtosis](https://github.com/kurtosis-tech/ethereum-package).
