### ISSUE TITLE
Unexpected response  in case of method debug_traceBlockByHash after upgrade to go-ethereum: v1.14.0

### ISSUE THREAD

**Issue by radoslav-dyulgerov** [ethereum/go-ethereum#29676]
#### System information

Geth version: ` `go-ethereum: v1.14.0
CL client & version: prysm@v5.0.2
OS & Version: Linux/
Commit hash : (if `develop`)

#### Actual behaviour
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "tracing failed: insufficient funds for gas * price + value: address 0xdf99A0839818B3f120EBAC9B73f82B617Dc6A555 have 61122619715444668 want 74363312441006965"
    }
}
```

#### Steps to reproduce the behaviour

Make a call (example below):
```json
{
    "jsonrpc": "2.0",
    "method": "debug_traceBlockByHash",
    "params": [
        "0x683b2d38f36806709da5f925adac285bd2cbed10e58669dc8ef5ac2164d3f58a",
        {
            "tracer": "callTracer",
            "tracerConfig": {
                "onlyTopCall": false,
                "withLog": false
            },
            "disableStorage": true,
            "disableStack": true
        }
    ],
    "id": 1
}
```

The issue is only observed when tracing  below blocks:
height: 19755425, hash: '0xdd0ac10044f0254bdb4a2d6ddb314cc7825dfb07474fc7f3dfc94f31c4616d5e'
height: 19755134, hash: '0x683b2d38f36806709da5f925adac285bd2cbed10e58669dc8ef5ac2164d3f58a'

Downgrade to previous version fixed the issue:

geth --version
geth version 1.13.15-stable-c5ba367e

So the issue is only observed in v1.14.0 for specific blocks.

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by holiman** [comment]
Interesting. 

In both those blocks [19755425](https://etherscan.io/txs?block=19755425) and [19755134](https://etherscan.io/txs?block=19755134), the address `0xdf99A0839818B3f120EBAC9B73f82B617Dc6A555` has the last transaction (first shown on the etherscan listing).

So I assume that this is the MEV payout.

**Comment by sokiaoba** [comment]
Having the same issue with v1.14.0
