### ISSUE TITLE
CI/PPA: fix noble packages

### ISSUE THREAD

**Issue by totoCZ** [ethereum/go-ethereum#29674]
https://launchpad.net/~ethereum/+archive/ubuntu/ethereum/+packages

You have failed builds and 1.14 for noble is missing.

**Comment by d-sfounis** [comment]
Seconding this, no .deb files for Ubuntu Jammy either, I'm stuck at version 1.13.15 and apt won't see the update.

**Comment by karalabe** [comment]
This was fixed on master (unstable). https://github.com/ethereum/go-ethereum/pull/29647 Will be incldued in the next release. Unfortunately we can't fix the source bundle for 1.14

**Comment by totoCZ** [comment]
@karalabe 
https://launchpad.net/~ethereum/+archive/ubuntu/ethereum/+packages

No builds on noble
