### ISSUE TITLE
Is it possible for geth to be written in such a away to prevent data corruption upon power outage?

### ISSUE THREAD

**Issue by traitran44** [ethereum/go-ethereum#29687]
I live in a stormy area, and have been experiencing power outage every couple days or so. I noticed every time the power went out, the geth database also went with it which require me to remove the entire db. Given what I experienced so far with geth, in a hypothetical event of mass power outage, surely most if not all of the database will be corrupted. Should this be a safety/security concern? If not, why not?

**Comment by rjl493456442** [comment]
Could you provide a bit more logs after power outage? Theoretically geth should be able to recover from the power outage. Your information will be beneficial for our investigation.

**Comment by holiman** [comment]
Answered by @rjl493456442 on the same day, but seems abandoned by op. Closing
