### ISSUE TITLE
Geth v1.14.0 not available on the PPA on Ubuntu 18.04 (bionic)

### ISSUE THREAD

**Issue by corooobal** [ethereum/go-ethereum#29680]
The Release build on [Ubuntu 18.04 (bionic) has failed for the amd64 version of v1.14.0](https://launchpad.net/~ethereum/+archive/ubuntu/ethereum/+packages).
It looks pretty similar to [issue #29576](https://github.com/ethereum/go-ethereum/issues/29576).

Could you pleas have a look? 

###############

System information
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

Expected behaviour
Running these commands should install the latest Geth version (v1.14.0 as of today) on a clean Ubuntu 18.04 (bionic) installation.

sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt update -y
sudo apt install -y geth
sudo apt-cache policy geth

Here is the result:
geth:
  Installed: 1.13.15+build29734+bionic
  Candidate: 1.13.15+build29734+bionic
  Version table:
 *** 1.13.15+build29734+bionic 500
        500 http://ppa.launchpadcontent.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

$ geth --version
geth version 1.13.15-stable-c5ba367e

Actual behaviour
Version 1.13.15 is the latest version available from the PPA on Ubuntu 18.04 (bionic)

Steps to reproduce the behaviour
Install Ubuntu 18.04 (bionic) in a VM
Run the commands above
Notice that version 1.13.15 is installed

**Comment by karalabe** [comment]
PPA failed to build Go 1.22. We've fixed it, but it needs a new release since the source bundle needs to be changes. Will be done in 1.14.1
