### ISSUE TITLE
internal/ethapi: crash casued by no limits for rewardPercentiles at interface FeeHistory

### ISSUE THREAD

**Issue by buddh0** [ethereum/go-ethereum#29709]
there is no number limit for rewardPercentiles
when `maxBlockHistory` set to 1024,
then set 600k element(limited by rpc requtest size)  in rewardPercentiles to call FeeHistory
the node will crash, for too many memory need.

maybe only a few nodes set `maxBlockHistory` such a big number,
but I think It's better to limit the number of rewardPercentiles to defend attack.
so, please check this PR [eth/gasprice: add query limit for FeeHistory to defend DDOS attack](https://github.com/ethereum/go-ethereum/pull/29644) again, thx.

**Comment by karalabe** [comment]
Merged, thx
