### ISSUE TITLE
Geth v1.14.2 not available on the PPA on Ubuntu 22.04 (jammy) 

### ISSUE THREAD

**Issue by CarlBeek** [ethereum/go-ethereum#29743]
As was raised in #29680 for v1.14.0, v1.14.2 is still not available on the Ubuntu PPA. Aparently the fix mentioned in https://github.com/ethereum/go-ethereum/issues/29680#issuecomment-2082768084 didn't resolve the issue.

```
# apt-cache policy geth
geth:
  Installed: 1.13.15+build29734+jammy
  Candidate: 1.13.15+build29734+jammy
  Version table:
 *** 1.13.15+build29734+jammy 500
        500 https://ppa.launchpadcontent.net/ethereum/ethereum/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by RLaptev** [comment]
Same for v1.14.2

**Comment by CarlBeek** [comment]
Sorry, I meant v1.14.2, I've updated the issue

**Comment by RommelTJ** [comment]
None of the latest packages are building per https://launchpad.net/~ethereum/+archive/ubuntu/ethereum/+packages.

**Comment by karalabe** [comment]
We know, that's why we haven't announced a new release yet. Pushing a 3rd try this morningm.

**Comment by karalabe** [comment]
1.14.3 is now on the PPA

**Comment by CarlBeek** [comment]
Thanks for the quick fix @karalabe!
