### ISSUE TITLE
Unauthorized access to the wallet balance on the node

### ISSUE THREAD

**Issue by Pamenarti** [ethereum/go-ethereum#29751]
#### System information

Geth version: ` Geth/Node-1/v1.13.15-stable-c5ba367e/linux-amd64/go1.21.5`
OS & Version: `Ubuntu 20.04.6 LTS`

### start parameters

Node1
```
geth	        --datadir=node1/ \
                --identity 'Node-1' \
		--syncmode 'full' \
		--gcmode=archive \
		--port 40411 \
		--networkid xxxx \
		--http \
		--http.addr 0.0.0.0 \
		--http.corsdomain '*' \
		--http.port 9547 \
		--http.vhosts '*' \
		--http.api eth,txpool,debug,web3,net,personal,admin \
		--ws \
                --ws.addr 0.0.0.0 \
		--ws.port 9457 \
		--ws.origins '*' \
		--ws.api eth,txpool,debug,web3,net,personal \
		--authrpc.vhosts '*' \
		--authrpc.port 8555 \
		--authrpc.jwtsecret=/home/agr9/testnet-pos/generator-genesis/output/jwt/jwtsecret \
		--mine \
		--cache=1028 \
		--miner.etherbase "0x4a03xxxxxxx" \
		--unlock "0x4a03bA36xxxxxxxxxx" \
		--password pass.txt \
		--allow-insecure-unlock \
		--snapshot=false \
		--cache.preimages \
		--crypto.kzg=gokzg \
		--rpc.allow-unprotected-txs \
		--nat extip:xxxxxxxxxxx
```
Node1
```
geth 	        --datadir=node2/ \
                --identity 'Node-2' \
		--syncmode 'full' \
		--gcmode=archive \
		--port 40420 \
		--networkid xxxx \
		--http \
		--http.addr 0.0.0.0 \
		--http.corsdomain '*' \
		--http.port 9546 \
		--http.vhosts '*' \
		--http.api eth,txpool,debug,web3,net,personal,admin \
		--ws \
                --ws.addr 0.0.0.0 \
                --ws.port 9456 \
                --ws.origins '*' \
		--ws.api eth,txpool,debug,web3,net,personal \
		--authrpc.vhosts '*' \
		--authrpc.port 8553 \
		--authrpc.jwtsecret=/home/agr9/testnet-pos/generator-genesis/output/jwt/jwtsecret \
		--bootnodes enode://xxxxxxxxxxxxxxx@xxxxxxxxxxxx:40411 \
		--mine \
		--cache=1028 \
		--miner.etherbase "0xEDFd79xxxxxxxxxxxx" \
		--unlock "0xEDFd790598FBxxxxxxxxxxxx" \
		--password pass.txt \
		--allow-insecure-unlock \
                --snapshot=false \
	        --cache.preimages \
                --crypto.kzg=gokzg \
		--rpc.allow-unprotected-txs
```

node1/geth/nodes/LOG
[LOG.log](https://github.com/ethereum/go-ethereum/files/15278654/LOG.log)
node2/geth/nodes/LOG
[LOG.log](https://github.com/ethereum/go-ethereum/files/15278661/LOG.log)

 I can send the balance in the node wallet without any authority using Curl & RPC on a different server or local server. Isn't this a security weakness?
https://github.com/ethereum/go-ethereum/assets/48421452/c0b2d79a-11c3-482c-b47d-50b0bb929e50
https://github.com/ethereum/go-ethereum/assets/48421452/e9323dea-90fd-4c27-a337-47623773d7ca

#### Backtrace

````
> eth.getBalance("0x4a03ba364cf0a095e2f064700c614371dfaf4447")
668472997679310935

> eth.coinbase
"0x4a03ba364cf0a095e2f064700c614371dfaf4447"
> exit

````
https://scan.agrotest.online/tx/0x45ec664db5a3581c3c1aeb56ca384c0fd6a4fe0378f583a54dca173ca4f9dea2

note: I can explain the test method. With private message

**Comment by holiman** [comment]
> I can send the balance in the node wallet without any authority 


```
		--unlock "0x4a03bA36xxxxxxxxxx" \
		--password pass.txt \
		--allow-insecure-unlock \
```

Well. You explicitly configured the node to unlock that account, with your password, and even added the switch to allow the totally insecure unlock operation, despite having it exposed over http `0.0.0.0` (public internet address). 

It just does what you told it to do.

**Comment by Pamenarti** [comment]
I could not see a warning that they should not be used in the starting parameter for RPC security. I think it is necessary to add to the narratives as a guides. Otherwise, projects will not take attention and will be victims.

In the RPC nodes, it is necessary to warn `--allow-insecure-unlock`, `--unlock`, `--password` should not be used.


I think this ticket should remain open.

Thank you for interesting.
