### ISSUE TITLE
Rate limit for faucet

### ISSUE THREAD

**Issue by emailtovamos** [ethereum/go-ethereum#29783]
# Rationale

Currently I see no provision to rate limit in case of DOS attack on faucet. Please correct me if I am wrong. 

# Implementation

There should be rate limiting mechanism in place to ensure the faucet resources don't get maxed up in an ip decides to send lots of requests per second.

**Comment by karalabe** [comment]
We dropped out faucet code many years ago, so unsure which faucet you're referring to.

**Comment by weiihann** [comment]
For those who are looking to implement a faucet, this [repo](https://github.com/pk910/PoWFaucet
) might be helpful.
