### ISSUE TITLE
Is Freezer a real memory mapped struct?

### ISSUE THREAD

**Issue by Shawn-Huang-Tron** [ethereum/go-ethereum#29793]
I see the description above Freezer: 
https://github.com/ethereum/go-ethereum/blob/v1.13.14/core/rawdb/freezer.go#L57

```
// Freezer is a memory mapped append-only database to store immutable ordered
// data into flat files:
//
//   - The append-only nature ensures that disk writes are minimized.
//   - The memory mapping ensures we can max out system memory for caching without
//     reserving it for go-ethereum. This would also reduce the memory requirements
//     of Geth, and thus also GC overhead.
```
I checked all of the code about Freezer, but I can't find the memory-mapping-related function. 
Instead, I find that it seems like just write into os.File ? https://github.com/ethereum/go-ethereum/blob/v1.13.14/core/rawdb/freezer_batch.go#L187

**Comment by namiloh** [comment]
That's odd indeed. Nothing memory-mapped about it
