### ISSUE TITLE
Maybe Clock Drift on Windows

### ISSUE THREAD

**Issue by TokenairdropOrg** [ethereum/go-ethereum#29803]
#### System information

Geth version: `11403`
CL client & version: prysm@v5.0.3
OS & Version: Windows
Commit hash : (if `develop`)

#### Expected behaviour
The number of Peers should maintain a dynamic balance

#### Actual behaviour
After running for a period of time, the number of Peers begins to decline unilaterally.

#### Steps to reproduce the behaviour
run geth 11403 + prysm 503 on windows server 2012

#### Backtrace

````
I think the unilateral decline of Peers should be caused by the software not handling the clock drift problem well. This event occurred after Geth was updated to version 11403, and recurred three times. My clock server is time.windows.com (system default)
````

![image](https://github.com/ethereum/go-ethereum/assets/79444537/e6d2917b-505d-44f3-9215-d57578653399)

**Comment by karalabe** [comment]
This seems to be a beacon client dashboard, so I'm guessing you'll need to open the issue against Prysm.
