### ISSUE TITLE
Geth v1.13.15 no longer available in PPA?

### ISSUE THREAD

**Issue by xinbenlv** [ethereum/go-ethereum#29808]
Hi, I am trying to install on Ubuntu Geth v1.13.15 and it turns out https://launchpad.net/~ethereum only has v1.14.3, am I looking at the right place? I am trying to just create a local Clique testnet and wondering if it's currently still available?

**Comment by karalabe** [comment]
Launchpad doesn't maintain old versions of Geth. You'll either need to build it yourself, or you can get a prebuilt binary from https://geth.ethereum.org/downloads (or docker has all the old versions tagged, or should have).
