### ISSUE TITLE
ATTENTION!This page does not represent the entire state of the ethereum network - listing a node on this page is a voluntary process.

### ISSUE THREAD

**Issue by PlamJ** [ethereum/go-ethereum#2981]
Getting the below error in the localhost:3000 page,

ATTENTION!This page does not represent the entire state of the ethereum network - listing a node on this page is a voluntary process.

Have followed the steps as mentioned in the document. The steps are:
1. git clone https://github.com/cubedro/eth-netstats
2. cd eth-netstats
3. npm install
4. WS_SECRET=<chosen_secret> npm start (after this step the terminal is stagnant)

Then tried opening the localhost:3000 page but getting the error.

**Comment by karalabe** [comment]
This is not an error, it's simply the way how netstats works. Nodes need to voluntarily report data (which they don't by defualt), so the data available is only partial, as the warning states. It's just a memo so people are aware that the network may be significantly larger than those being reported.

**Comment by trungtt1981** [comment]
How can I make the nodes voluntarily report data??? I wanna see the nodes return data

**Comment by TrevorOakley** [comment]
Was there an answer to this? I have the same issue.

**Comment by M-Hammad-Ali** [comment]
> This is not an error, it's simply the way how netstats works. Nodes need to voluntarily report data (which they don't by defualt), so the data available is only partial, as the warning states. It's just a memo so people are aware that the network may be significantly larger than those being reported.

How to solve this issue? I am also getting this when running npm.

**Comment by samanshahmohamadi** [comment]
I have same issue. Is it about `wsapi` options on running geth node? How we could make a node to report data?

**Comment by karalabe** [comment]
There's an `--ethstats` flag where you can specify the stats server and the auth credentials.

**Comment by samanshahmohamadi** [comment]
> There's an `--ethstats` flag where you can specify the stats server and the auth credentials.

Thank you, I will test it.

**Comment by dev-intellisoft** [comment]
I'm have the same issue? any solution?
