### ISSUE TITLE
Out Of GasLimit PoA

### ISSUE THREAD

**Issue by avenbreaks** [ethereum/go-ethereum#29815]
We wanted to implement the pancakeswap fork contract on our PoA network but after execution using Remix we got this notification: 

Internal JSON-RPC error.
You may want to cautiously increase the gas limit if the transaction went out of gas.

**Comment by avenbreaks** [comment]
@rjl493456442

**Comment by avenbreaks** [comment]
can help ? setup :

```
    --mine=true \
    --miner.etherbase="0xxxxxxxxxxxxxxxxx" \
    --miner.extradata="0xxxxxxxxxxxxxxxxx" \
    --miner.gaslimit=30000000 \
    --miner.gasprice=0 \
    --miner.recommit=2s \
    --miner.newpayload-timeout=2s \
    --gpo.blocks=20 \
    --gpo.ignoreprice=2 \
    --gpo.maxprice=500000000000 \
    --gpo.percentile=60 \
    --txpool.accountqueue=64 \
    --txpool.accountslots=16 \
    --txpool.globalqueue=1024 \
    --txpool.globalslots=5120 \
    --txpool.lifetime=0h5m0s \
    --txpool.nolocals \
    --txlookuplimit=0 \
```

**Comment by nikhilve99** [comment]
Hi,

I am also facing the same problem, have u got any solution ?

**Comment by s1na** [comment]
Which version are you using? PoA support was recently removed from go-ethereum.
Although that does not explain why the node itself is fine and only you get error when sending RPC requests. Can you check remix logs and see what was the request that errored?

**Comment by lightclient** [comment]
Please reopen if you are able to produce some logs of the issue. Thanks!
