### ISSUE TITLE
i am not sure about the reason for adding it here, after this change we will be serving 8192 blocks with the BLOCKHASH opCode, Also, this variable is not used in the EIP anywhere.

### ISSUE THREAD

**Issue by Mortiemi** [ethereum/go-ethereum#29845]
i am not sure about the reason for adding it here, after this change we will be serving 8192 blocks with the BLOCKHASH opCode, Also, this variable is not used in the EIP anywhere.

_Originally posted by @tanishqjasoria in https://github.com/ethereum/EIPs/pull/8578#discussion_r1606945792_

**Comment by rjl493456442** [comment]
Please move the discussion into the EIP ticket
