### ISSUE TITLE
Documentation for config is outdated 

### ISSUE THREAD

**Issue by alex067** [ethereum/go-ethereum#29855]
#### System information

Geth version: `1.13.15-stable`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
The config-files documentation seems to be out dated for the latest version of geth. See: https://geth.ethereum.org/docs/fundamentals/config-files 

It's claiming the attribute `UltraLightFraction` is valid however the latest geth client will throw out an error if this attribute is provided `field 'UltraLightFraction' is not defined in ethconfig.Config`

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by s1na** [comment]
Yeah we dropped the LES from geth I suppose that broke the config. PRs are welcome against the [website](https://github.com/ethereum/go-ethereum/tree/website) branch.

**Comment by lukaszsamson** [comment]
This page is also not relevant anymore https://geth.ethereum.org/docs/fundamentals/les

**Comment by lightclient** [comment]
I think this is fixed now.
