### ISSUE TITLE
ethereum node panic.

### ISSUE THREAD

**Issue by NathanHo1024** [ethereum/go-ethereum#29860]
hi. sir. i got a panic in my ethereum node. i wonder what's happen?  the ethereum docker version : ethereum/client-go:latest . image id : 651587b0bf93
![Uploading image.png…]()

**Comment by rjl493456442** [comment]
Could you please provide the panic log? Your image is not resolved.

**Comment by NathanHo1024** [comment]
> Could you please provide the panic log? Your image is not resolved.
ok，

panic: moveToList("fast" - "slow"): node 524d07ba7d306c095c933d942982d9ae8c629e89548faae7d5e24a5801958cc not in source list
goroutine 24755 [running]
github. com/ethereum/go-ethereum/p2p/discover.(*tableRevalidation). moveToList(0x1a882817, 0xc01b6a4128, Oxc01b6a40f0, 0xc0390e76d0, 0x9c86701b3cd53,
{0x2011f20, 0xc01b6a40b0})
github.com/ethereum/go-ethereum/p2p/discover/table_reval.go:174 +0x16e
github.com/ethereum/go-ethereum/p2p/discover.(*tableRevalidation). handleResponse(0xc016a40f0, 0xc01b6a4008, {0xc039076d0?, 0x07, Oxc01b6a40f0?,
17})
github.com/ethereum/go-ethereum/p2p/discover/table_reval.go:158 +0x465
github. com/ethereum/go-ethereum/p2p/discover.(*Table).loop(0xc01b6a4008)
github. com/ethereum/go-ethereum/p2p/discover/table.go:376 +0x72d
created by github.com/ethereum/go-ethereum/p2p/discover.ListenV4 in goroutine 1
github.com/ethereum/go-ethereum/p2p/discover/v4_udp.go:150 +0x3a8

**Comment by lilasxie** [comment]
I'm wondering why we should panic here.
https://github.com/ethereum/go-ethereum/blob/master/p2p/discover/table_reval.go#L173~L175
```go
if !source.remove(n) {
	panic(fmt.Errorf("moveToList(%q -> %q): node %v not in source list", source.name, dest.name, n.ID()))
}
```
If the source list doesn't contain the node, just leave an unexpected warning log will that be ok?

**Comment by NathanHo1024** [comment]
> I'm wondering why we should panic here. https://github.com/ethereum/go-ethereum/blob/master/p2p/discover/table_reval.go#L173~L175
> 
> ```go
> if !source.remove(n) {
> 	panic(fmt.Errorf("moveToList(%q -> %q): node %v not in source list", source.name, dest.name, n.ID()))
> }
> ```
> 
> If the source list doesn't contain the node, just leave an unexpected warning log will that be ok?

so i need change the source code and rebuild again?

**Comment by rjl493456442** [comment]
@NathanHo1024 Please wait a bit, we will investigate the reason for panic. 

As now, you could downgrade your node to latest release https://github.com/ethereum/go-ethereum/releases/tag/v1.14.3
It should work without issue.

**Comment by NathanHo1024** [comment]
> @NathanHo1024 Please wait a bit, we will investigate the panic.
> 
> As now, you could downgrade your node to latest release https://github.com/ethereum/go-ethereum/releases/tag/v1.14.3 It should work without issue.

ok, thanks. bro.
