### ISSUE TITLE
how to get Ether from testnet

### ISSUE THREAD

**Issue by cheershendtco** [ethereum/go-ethereum#2986]
#### System information

Geth
Version: 1.5.0-unstable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go

#### Expected behaviour
I wanna get Ether in testnet and make a transaction send Ether to another.

#### Actual behaviour
I don`t know how to get Ether from testnet.

#### Steps to reproduce the behaviour

I run this command on my ubuntu
geth --testnet --rpc --rpcapi "db,eth,net,web3,personal" --solc "~/Downloads/cpp-ethereum-develop/solc.exe" console

and 
eth.getBalance(eth.coinbase)
which is 0
how do I get Ether from testnet

Thanks

**Comment by bas-vk** [comment]
I'm not aware of a faucet for the testnet but there might be one. You have 2 options:
1. ask, visit https://gitter.im/ethereum/go-ethereum and ask if someone can send you some.
2. try to mine it, on the testnet this is still feasible. Wait for your node to sync and start the miner: `miner.start()`.
