### ISSUE TITLE
add support for rpc endpoint eth_callBundle

### ISSUE THREAD

**Issue by monperrus** [ethereum/go-ethereum#29862]
# Rationale

It would be useful to add support for a new RPC endpoint `eth_callBundle` that supports speculatively study of the execution of a sequence of transactions.

What are the use-cases?
- Research, to study what-if scenarios on past blocks, what if this transaction had come first in the past?  (eg what if a white hat counter transaction had been included before the attacker one?)
- MEV, this is the first historically known usage of `eth_callbundle`

Known existing implementations:
- In mev-geth, see https://github.com/flashbots/mev-geth (unmaintained) and https://github.com/NaliFinance/mev-geth (maintained) 
- In Reth, see https://github.com/paradigmxyz/reth/issues/3518
- In Erigon, see [doc](https://github.com/ledgerwatch/erigon/blob/d5a1725c0b51a5e576fd20af00d04b8d50e94ca0/cmd/rpcdaemon/README.md?plain=1#L286), yet with [a different API](https://github.com/ledgerwatch/erigon/issues/3487)

See a draft implementation at <https://github.com/ethereum/go-ethereum/compare/release/1.14...NaliFinance:mev-geth:release/1.14>

# Implementation of eth_callBundle

`eth_callBundle` can be used to simulate a bundle of transactions against a specific block number, including simulating a bundle at the top of the next block. The `eth_callBundle` RPC has the following payload format:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "eth_callBundle",
  "params": [
    {
      txs,               // Array[String], A list of signed transactions to execute in an atomic bundle
      blockNumber,       // String, a hex encoded block number for which this bundle is valid on
      stateBlockNumber,  // String, either a hex encoded number or a block tag for which state to base this simulation on. Can use "latest"
      timestamp,         // (Optional) Number, the timestamp to use for this bundle simulation, in seconds since the unix epoch
    }
  ]
}
```

example:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "eth_callBundle",
  "params": [
    {
      "txs": ["0x123abc...", "0x456def..."],
      "blockNumber": "0xb63dcd",
      "stateBlockNumber": "latest",
      "timestamp": 1615920932
    }
  ]
}
```

example response:

```json
{
  "jsonrpc": "2.0",
  "id": "123",
  "result": {
    "bundleGasPrice": "476190476193",
    "bundleHash": "0x73b1e258c7a42fd0230b2fd05529c5d4b6fcb66c227783f8bece8aeacdd1db2e",
    "coinbaseDiff": "20000000000126000",
    "ethSentToCoinbase": "20000000000000000",
    "gasFees": "126000",
    "results": [
      {
        "coinbaseDiff": "10000000000063000",
        "ethSentToCoinbase": "10000000000000000",
        "fromAddress": "0x02A727155aeF8609c9f7F2179b2a1f560B39F5A0",
        "gasFees": "63000",
        "gasPrice": "476190476193",
        "gasUsed": 21000,
        "toAddress": "0x73625f59CAdc5009Cb458B751b3E7b6b48C06f2C",
        "txHash": "0x669b4704a7d993a946cdd6e2f95233f308ce0c4649d2e04944e8299efcaa098a",
        "value": "0x"
      },
      {
        "coinbaseDiff": "10000000000063000",
        "ethSentToCoinbase": "10000000000000000",
        "fromAddress": "0x02A727155aeF8609c9f7F2179b2a1f560B39F5A0",
        "gasFees": "63000",
        "gasPrice": "476190476193",
        "gasUsed": 21000,
        "toAddress": "0x73625f59CAdc5009Cb458B751b3E7b6b48C06f2C",
        "txHash": "0xa839ee83465657cac01adc1d50d96c1b586ed498120a84a64749c0034b4f19fa",
        "value": "0x"
      }
    ],
    "stateBlockNumber": 5221585,
    "totalGasUsed": 42000
  }
}
```

**Comment by rjl493456442** [comment]
Sina is working on an alternative of it, check out https://github.com/ethereum/go-ethereum/pull/27720 for more information

**Comment by s1na** [comment]
Right I believe #27720 should be able to serve this use-case. From what I understand what you're proposing takes already mined transactions as input. eth_simulateV1 does not do that, it takes call args as in eth_call. But that's just a matter of doing `eth_getTransactionByHash` and passing the fields to `eth_simulateV1`.

**Comment by monperrus** [comment]
> Right I believe https://github.com/ethereum/go-ethereum/pull/27720 should be able to serve this use-case

great!

> From what I understand what you're proposing takes already mined transactions as input

any valid transaction can be given as input to eth_callBundle, not only already mined ones.

**Comment by fjl** [comment]
We will not add `eth_callBundle` because the standardized alternative `eth_simulateV1` is being worked on, and will satisfy the same use cases as `callBundle`.

**Comment by monperrus** [comment]
ack.

for the record, the current work on eth_simulateV1 lives at https://github.com/ethereum/execution-apis/pull/484
