### ISSUE TITLE
Is the node id in the documentation outdated?

### ISSUE THREAD

**Issue by wanwiset25** [ethereum/go-ethereum#29863]
In the docs it seems like the 'id' field is taken from the 'enode' representation
https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-admin
<img width="781" alt="Screenshot 2024-05-28 at 12 25 36" src="https://github.com/ethereum/go-ethereum/assets/62221586/843fb516-c788-490e-a22c-ffd1ea2d8665">
<img width="779" alt="Screenshot 2024-05-28 at 12 26 17" src="https://github.com/ethereum/go-ethereum/assets/62221586/70b00067-ad9b-4bae-8f9c-e24d14ea9cfd">

In the current version the 'id' field is a short string.
<img width="625" alt="Screenshot 2024-05-28 at 12 28 55" src="https://github.com/ethereum/go-ethereum/assets/62221586/1ef2e816-e724-4c17-b3ec-2dd972cfabf8">
<img width="650" alt="Screenshot 2024-05-28 at 12 30 35" src="https://github.com/ethereum/go-ethereum/assets/62221586/477c980b-09a5-425c-adf8-884e6be7ccf2">

**Comment by karalabe** [comment]
The part in the enode url is the public key. The ID (looking it up in our code) is the KEccak256 hash of the pubkey. Not entirely sure why this was preferable, I guess it's shorter and unique anyway. I don't think there's any guarantee as to what the ID would be, apart of unique across peers.

Maybe @fjl knows why this is the hash specfically?

**Comment by karalabe** [comment]
So, @fjl said that he made the change when rolling out ENRs. In theory the node ID in the discovery protocol is also the hash (used by everyone else), but there's really no real harm if other clients use a different mapping. Either way, the examples originate from a very old doc of Geth, should probably be updated. If anyone wants to open a PR to do so, more than welcome.

**Comment by wanwiset25** [comment]
Thank you @karalabe.
I'm happy to raise the PR, please find it here: https://github.com/ethereum/go-ethereum/pull/29920
