### ISSUE TITLE
How to sent Ether from Ethereum Wallet to eth.coinbase

### ISSUE THREAD

**Issue by cheershendtco** [ethereum/go-ethereum#2987]
#### System information

Geth
Version: 1.5.0-unstable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go

I use eth.coinbase to check my address
which is
"0xe81a668bd17d7e81b6badc47cbb339506493d025"

and I send Ether from Ethereum Wallet on windows OS to this address.
and I check the result from 
https://testnet.etherscan.io/address/0xe81a668bd17d7e81b6badc47cbb339506493d025

after that I > eth.getBalance(eth.coinbase)
but my account still is 0

Plz help me 
Thanks

**Comment by bas-vk** [comment]
Currently the address has 4 incoming transactions and 6 ether. If geth isn't synced it might not have processed the blocks with these transactions and thus you won't see the balance updated on your local node. It also can take some time before your transaction is processed.
