### ISSUE TITLE
how to import account from Ethereum Wallet

### ISSUE THREAD

**Issue by cheershendtco** [ethereum/go-ethereum#2988]
#### System information
Geth
Version: 1.5.0-unstable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go

#### Steps to reproduce the behaviour

I export account from  Ethereum Wallet
this file look like this
{"address":"c8edeb20dfb59ef196cf0515e9acc74c4fa3ad77","crypto":{"cipher":"aes-128-ctr","ciphertext":"XXX","cipherparams":{"iv":"XXX"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"XXX"},"mac":"XXX"},"id":"XXX","version":3}

I use geth account import key
but
Fatal: Failed to load the private key: encoding/hex: invalid byte: U+007B '{'

Plz help me
Thanks.

**Comment by karalabe** [comment]
Just copy it into your keystore folder. Import is meant to load an unencrypted private key. You have a nice final encrypted key file so just copy :)

**Comment by bas-vk** [comment]
What ^^ said, the keystore directories are:
mainnet: $HOME/.ethereum/keystore
testnet: $HOME/.ethereum/testnet/keystore

**Comment by nitinsurana** [comment]
I'm writing a utility so it has to import using the command only. Seems like the issue still ain't fixed cause I'm getting exactly the same error.

**Comment by MarceloFCandido** [comment]
What @nitinsurana proposed could be a good feature.
