### ISSUE TITLE
Unexpected trie missing in prefetcher

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/go-ethereum#29880]
Geth will occasionally report this kind of log during the full sync.

```
ERROR[05-30|10:43:55.896] Prefetcher missed to load trie           owner=000000..000000 root=223db5..e44945
```

It denotes the specific account trie is not scheduled for prefetching, but it's required for state rehashing.

**Comment by karalabe** [comment]
This tuned out to be post-merge but pre-withdrawals when there's an empty block with no txs, so the account trie never gets prefetched. So no issue, but scary warning.

**Comment by holiman** [comment]
https://etherscan.io/block/15537454

**Comment by karalabe** [comment]
I guess the fix would be to *always* inject a prefetch() call for the account trie whenever we create a statedb / start a prefetcher. It's a bit overkill, but it's cleaner than trying to be smart about avoiding accessing the account trie in statedb.Commit.

**Comment by wawrzek** [comment]
I can consistently repeat the issue using the latest docker image in the https://github.com/ivy-net/iv1 (or any other derivative of https://github.com/OffchainLabs/eth-pos-devnet).
