### ISSUE TITLE
eth_getFilterChanges do not work after geth restart

### ISSUE THREAD

**Issue by paradise** [ethereum/go-ethereum#2989]
Geth version: 1.4.11-stable
OS & Version: Ubuntu

I use .NET library Nethereum to communicate with geth. I create  contract with one event and create filter for this event. It is written that filters are permanent, so I store it hex address and trying to get filter changes (eth_getFilterChanges). 
For some time it works fine, but when I restart my geth node new filter changes don't appear. So after restarting I can get all logs (eth_getFilterLogs), but can't get only new changes. Because of this, I have to recreate my filter, and get changes by new filter hex.

**Comment by bas-vk** [comment]
Filters are stored in memory. If you restart geth these filters are lost and you need to recreate the filter and poll with the new one. This is true for `eth_getFilterChanges` and `eth_getFilterLogs`. Exception is `eth_getLogs` that doesn't accept a filter id but instead the full criteria. This method won't give you the changes but all (stored) logs that match the given criteria.

> It is written that filters are permanent

Where did you find this?

**Comment by paradise** [comment]
So, if I understand right, `eth_getLogs` will always return all logs from the start ? Can I specify blockStart-blockEnd for `eth_getLogs` ? 
Another question - is there any correct way to handle situation, when my geth restarts (for example virtual machine restarted), so that my server app will understand, that it should recreate in-memoty filter ?

**Comment by fjl** [comment]
> So, if I understand right, eth_getLogs will always return all logs from the start ? Can I specify blockStart-blockEnd for eth_getLogs ? 

See https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter for documentation.

> , so that my server app will understand, that it should recreate in-memoty filter ?

You can try recreating the filter when gethFilterChanges returns an error.

**Comment by paradise** [comment]
But it does not return error, it returns en empty array, if filter is missing.
