### ISSUE TITLE
The block generation speed of geth's POW private chain is too fast. 4 blocks may be generated in 1 second. Then the server disk quickly increases in size. The server is shut down directly or the process is exited, resulting in data loss. How to solve this problem?

### ISSUE THREAD

**Issue by phpmac** [ethereum/go-ethereum#29905]
The block generation speed of geth's POW private chain is too fast. 4 blocks may be generated in 1 second. Then the server disk quickly increases in size. The server is shut down directly or the process is exited, resulting in data loss. How to solve this problem?

I don’t want to build poa. Is there any way to solve the problem of disk and data loss using pow? If you want to limit the block generation time, how about if there is a transaction, the block will be generated, but if there is no transaction, there will be no need to generate the block? ? Or something else.

There is always a problem with multi-node synchronization of geth private chain. It will synchronize to a part and then synchronize again. How to solve it? Have you encountered anyone?

Several problems encountered affected:

1. The block generation speed is too fast - causing other nodes to be unable to synchronize (may be forked)
2. The disk usage is too large - even empty blocks without transactions can take up a lot of disk space
3. Data loss caused by server shutdown and abnormal process exit - the official mainnet also has this problem, right? It can only be solved through multi-node synchronization, right?

**Comment by rjl493456442** [comment]
Ethash is no longer supported by Geth

I feel like this is a ticket generated by AI. Close it

**Comment by phpmac** [comment]
> Member

Oh oh oh, I'm not an AI, I'm a real person!
