### ISSUE TITLE
eth_getFilterChanges does not return error if filter is missing

### ISSUE THREAD

**Issue by paradise** [ethereum/go-ethereum#2991]
Geth version: 1.4.11-stable
OS & Version: Ubuntu
#### Expected behaviour

eth_getFilterChanges should return error if filter is missing.
#### Actual behaviour

As written here https://github.com/ethereum/go-ethereum/issues/2989#issuecomment-246003403 eth_getFilterChanges should return error if filter is missing in memory, so I can handle this error and create new filter, but if there is no filter in memory (you can try random filter hex) method still returns empty array, not error.
#### Steps to reproduce the behaviour

Request eth_getFilterChanges with random filter hex.

**Comment by bas-vk** [comment]
The spec doesn't specify anything about errors and therefore returning an empty array was a deliberate choice (I *think* other clients do the same thing). Since this behavior is currently not standardized you cannot rely on it when your DApp is run against different nodes.

**Comment by fjl** [comment]
I think the idea behind this design change was to make it harder to guess valid filter IDs. Since we now use longer hex IDs, adding an error sounds like a good solution.
