### ISSUE TITLE
error: Latest filled block is not available

### ISSUE THREAD

**Issue by NathanHo1024** [ethereum/go-ethereum#29910]
it happen error: Latest filled block is not available when i restart sync my node. 
i wonder what's going on?

the geth-docker version: Geth/v1.14.4-unstable-d4b81f0e/linux-amd64/go1.22.3
and the beacon-docker version: Prysm/v5.0.3/b08e69112716a4e0d0bfcf345e95696f0f42ba6b

**Comment by karalabe** [comment]
You'll need to share some logs, otherwise we have no idea what might be happening.

**Comment by NathanHo1024** [comment]
> You'll need to share some logs, otherwise we have no idea what might be happening.

INFO [06-03|08:55:00.236] Imported new potential chain segment     number=20,010,236 hash=83737c..4aedb8 blocks=1         txs=181         mgas=14.589  elapsed=212.070ms    mgasps=68.794 snapdiffs=342.25KiB triediffs=196.26MiB triedirty=25.64MiB
INFO [06-03|08:55:00.554] Chain head was updated                   number=20,010,236 hash=83737c..4aedb8 root=c7c9ae..c1db56 elapsed=3.078795ms
WARN [06-03|08:55:01.787] Blob transaction swapped out by signer   from=0x415c8893D514F9BC5211d36eEDA4183226b84AA7 nonce=80373     id=268,435,459
INFO [06-03|08:55:02.532] Got interrupt, shutting down...
INFO [06-03|08:55:02.532] HTTP server stopped                      endpoint=[::]:29900
INFO [06-03|08:55:02.532] HTTP server stopped                      endpoint=[::]:29910
INFO [06-03|08:55:02.532] HTTP server stopped                      endpoint=[::]:8551
INFO [06-03|08:55:02.533] IPC endpoint closed                      url=/root/.ethereum/geth.ipc
INFO [06-03|08:55:05.810] Ethereum protocol stopped
INFO [06-03|08:55:05.811] Transaction pool stopped
INFO [06-03|08:55:05.817] Aborting state snapshot generation       root=a52ab2..69e9fa at=3f32d7..9c47a9 accounts=60,949,855           slots=329,227,233             storage=26.55GiB   dangling=0 elapsed=46m8.005s    eta=2h20m44.419s
INFO [06-03|08:55:05.817] Journalling in-progress snapshot         root=a52ab2..69e9fa at=3f32d7..9c47a9 accounts=60,949,855           slots=329,227,233             storage=26.55GiB   dangling=0 elapsed=46m8.005s    eta=2h20m44.419s
INFO [06-03|08:55:05.820] Persisting dirty state to disk           head=20,010,236 root=c7c9ae..c1db56 layers=168
INFO [06-03|08:55:06.900] Persisted dirty state to disk            size=210.25MiB elapsed=1.079s
INFO [06-03|08:55:06.900] Blockchain stopped


it just Stopped very suddenly。 and i don't know what's going on with my node?

**Comment by rjl493456442** [comment]
`INFO [06-03|08:55:02.532] Got interrupt, shutting down...`

Looks like you stopped the node manually

**Comment by rjl493456442** [comment]
`Latest filled block is not available ` Please share the logs with this error report

**Comment by NathanHo1024** [comment]
> `Latest filled block is not available ` Please share the logs with this error report

i was re-sync my node again, so the logs is dismiss. sry.

**Comment by lightclient** [comment]
@NathanHo1024 please reopen this if you encounter the issue again and are able to produce some logs around the event. It's not possible for us to diagnosis the issue without. Thanks!
