### ISSUE TITLE
Offline cache for github worker

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#29925]
We have a github action and a dedicated worker for it to run tests fast... but the thing caches Go build files into GitHub (uploading and downlaoding 3.5GB), so it takes 8 minutes to start the tester, 20 secs to test and 8 minutes to stop the tester. Crazy. We need to make the tester cache locally, since our dedicated builder is a unique snowflake.

Also should enable race detector runs on it.

**Comment by sisco0** [comment]
Is there any specific Github Actions Workflow YAML file that you would like to consider? I could only find `go.yml`.
I would suggest modifying the Workflow YAML file. Default paths of interest are `~/.cache/go-build` and `$GOPATH/pkg/mod`. Might be more paths are of interest.

For developers who are not maintainers of this repository, I would suggest performing a personal fork and test over it.

**Comment by gballet** [comment]
@karalabe @parithosh had something in the pipe to solve this. Not sure what the current state is.

Basically, the cache is big because it's never cleared. It should be cleared more often.

**Comment by parithosh** [comment]
cc @elasticroentgen , How/when do we want to migrate the geth github actions runner into your infra?

**Comment by elasticroentgen** [comment]
as stated on our devops ticket https://github.com/ethereum/devops/issues/1507 i've set up a potential solution for this, but never received feedback on it. If it works as expected (see the linked issue) i can assist in making the switch.
