### ISSUE TITLE
FinalizedBlockTag is existent but the corresponding block/header is missing

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/go-ethereum#29937]
The error log ` Number of finalized block is missing` is reported after an unexpected outage.

**Comment by AungThuSoe24** [comment]
GET /api/v5/asset/balances

**Comment by fjl** [comment]
We have investigated this error and it's harmless. The error should be kept as a reminder.

**Comment by cosmicnet** [comment]
I had this error. After reading this post and others I just ignored it and it seemed to go away after a while. However, I just did a prune and restarted geth and now the error has come back.
