### ISSUE TITLE
Private network instructions don't work on geth 1.14

### ISSUE THREAD

**Issue by mdesousa** [ethereum/go-ethereum#29940]
#### System information

Geth version: `1.14.4`
OS & Version: OSX

#### Expected behaviour

You should be able to follow the instructions in the [Private Networks](https://geth.ethereum.org/docs/fundamentals/private-network) page

#### Actual behaviour

You get an error when you try to start the client

```
Fatal: Failed to register the Ethereum service: only PoS networks are supported, please transition old ones with Geth v1.13.x
```

**Comment by parametprame** [comment]
You should either attempt to downgrade your Geth version to 1.13.15 or refer to this link: https://github.com/ethereum/go-ethereum/issues/29194 for further assistance.
