### ISSUE TITLE
Add PR rules to developers' guide

### ISSUE THREAD

**Issue by BabyHalimao** [ethereum/go-ethereum#29976]
According to [comments](https://github.com/ethereum/go-ethereum/pull/29971#issuecomment-2160763263) from @karalabe 

I think we can add these rules somewhere like [developers' guide](https://geth.ethereum.org/docs/developers/geth-developer/dev-guide), to make them more clearly

**Comment by joey1123455** [comment]
Hello I just started working on this

**Comment by BabyHalimao** [comment]
This should be talk with team first，not for now

**Comment by fjl** [comment]
We decided not to add this information to the README for now
