### ISSUE TITLE
go-ethereum points to old sentry version.

### ISSUE THREAD

**Issue by atemafac-nd** [ethereum/go-ethereum#29984]
The latest go-ethereum tag points to old/bad sentry version. In go.mod file, this require project github.com/getsentry/sentry-go is tag to v0.18.0 and the latest tag is v0.28.1 (with updated dependencies).

**Comment by rjl493456442** [comment]
We don't update the dependency frequently, unless there is a major change or bug fix which is important for us.

Free reopen the ticket if you think there are indeed something urgent!

**Comment by atemafac-nd** [comment]
I get this dependency issue when trying to build an image.

- go-ethereum points to sentry-go v0.18.0 project
- the issue is that version of sentry-go v0.18.0 needs/points to katara-iris v12.2.0-beta5. this beta version does not exist
- the newer versions of sentry-go does not point to functioning katara-iris version

error message below

`#9 726.8 go: github.com/ethereum/go-ethereum@v1.13.2 requires
#9 726.8 	github.com/getsentry/sentry-go@v0.18.0 requires
#9 726.8 	github.com/kataras/iris/v12@v12.2.0-beta5: reading github.com/kataras/iris/go.mod at revision v12.2.0-beta5: unknown revision v12.2.0-beta5
#9 726.8 make: *** [build] Error 1`

**Comment by rjl493456442** [comment]
We don't have any issue for docker image building. Could you please share the build command?

**Comment by karalabe** [comment]
The issue here is that sentry is pulled in by Pebble. Whilst pebble did hit this issue and they did update their errors package in https://github.com/cockroachdb/errors/pull/137, they have not made a release to their main pebble code, so we can't point to a fresher pebble dep for now.

**Comment by karalabe** [comment]
Was fixed upstream, opened a PR against Geth to fix it ourselves too.
