### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by almindor** [ethereum/go-ethereum#3004]
#### System information

Geth version: `1.4.11-stable`
OS & Version: Ubuntu Linux 64bit
Commit hash : N/A

#### Expected behaviour
Geth runs, syncs and eats normal amount of RAM

#### Actual behaviour
Geth runs, starts to sync and gets killed by OOM killer because it goes over 2GB of RAM usage real fast.

#### Steps to reproduce the behaviour
Run geth with no options is enough

#### Backtrace
Memory output from geth before getting killed
[mem.out.gz](https://github.com/ethereum/go-ethereum/files/478990/mem.out.gz)

**Comment by karalabe** [comment]
There was an attack on the Geth EVM implementation. A fixed was released as Geth 1.4.12. Please update.
