### ISSUE TITLE
miner.start() have some trouble

### ISSUE THREAD

**Issue by eka051103** [ethereum/go-ethereum#30041]
I am a beginner who has only been learning for a few days
my ubuntu version : 24.02
geth version  : 1.14.5-stable
When I install geth and configure the genesis.json file
{
  "config": {
  "chainId": 15,
  "homesteadBlock": 0,
  "eip150Block": 0,
  "eip155Block": 0,
  "eip158Block": 0,
  "byzantiumBlock": 0,
  "constantinopleBlock": 0,
  "petersburgBlock": 0,
  "istanbulBlock": 0,
  "berlinBlock": 0,
  "londonBlock": 0
},
  "difficulty": "1",
  "gasLimit": "8000000",
  "alloc": {}
}
geth init genesis.json
I started geth using:
geth  --rpc.enabledeprecatedpersonal  --http.apipersonal,eth,net,web3,miner --mine console

Afterwards, I created an account using the personal.newAccount( ) command, set the password to unlock the account, and when I entered mine. start (1), his error message was:
miner.start(1)
TypeError: Object has no member 'start'
at <eval>:1:12(3)

plz help!!

**Comment by karalabe** [comment]
Geth v1.14 and later only support proof-of-stake networks, where you need a beacon chain along the execution chain. You'll need to look into Kurtosis for example on setting up PoS testnets.

**Comment by eka051103** [comment]
> Geth v1.14 and later only support proof-of-stake networks, where you need a beacon chain along the execution chain. You'll need to look into Kurtosis for example on setting up PoS testnets.

thank you for your answer. can you tell me how to operate
