### ISSUE TITLE
Gomobile for android / ios

### ISSUE THREAD

**Issue by gedw99** [ethereum/go-ethereum#3005]
Hey everyone,

Really love what this project represents.

Etherium is using jsonrpc, and so it's possible to build mobile apps for etherium using golang !!
This is a good reuse of the code.

Has anyone tried this yet ? I would prefer to build it with a web GUI, and gomobile, so that as much code as possible is shared between the Android and IOS  builds.

Sorry to ask this on github,...

**Comment by karalabe** [comment]
Wait until tomorrow ;) (decvon day2, talk from 12:15 ;) )

**Comment by gedw99** [comment]
@karalabe Hey Peter

Wow now i am really curious...

**Comment by gedw99** [comment]
https://ethereumfoundation.org/devcon/?session=25-import-geth-ethereum-from-go-and-beyond

?

**Comment by fjl** [comment]
Yes, that's the talk he meant ;)
Slides are here: https://ethereum.karalabe.com/talks/2016-devcon.html#1

**Comment by phillyfan1138** [comment]
I'm trying to follow the code as linked in https://github.com/ethereum/go-ethereum/wiki/Mobile-Clients:-Libraries-and-Inproc-Ethereum-Nodes but I can't seem to get the code to work.  I'm not great at Android development; is there an example of this code in a larger project so I can see the context?

**Comment by phillyfan1138** [comment]
Never mind I think I got it working.

**Comment by phillyfan1138** [comment]
Ok after carefully reviewing the slides I have another question: how does one generate the java contract code?  I can generate go code just fine following the instructions in https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts.

**Comment by fjl** [comment]
We have plans to add Java support to abigen, but it's not there yet.

**Comment by phillyfan1138** [comment]
Ah cool.  I'll just edit the generated go code I guess.

**Comment by karalabe** [comment]
It's in the mobile pr

**Comment by fjl** [comment]
"the mobile PR" is https://github.com/ethereum/go-ethereum/pull/2977

**Comment by phillyfan1138** [comment]
Thanks everyone I got the java code generated.  There were some errors but they were easily fixed.

I'm now struggling to connect to the testnet though.  I followed the guide in https://github.com/ethereum/wiki/wiki/Morden but it keeps hanging at the "syncing" portion.  This is my code:
`
Enodes nodes = new Enodes(1);
NodeConfig config = new NodeConfig();
try {
            nodes.set(0,         Geth.newEnode("enode://e58d5e26b3b630496ec640f2530f3e7fa8a8c7dfe79d9e9c4aac80e3730132b869c852d3125204ab35bb1b1951f6f2d40996c1034fd8c5a69b383ee337f02ddc@92.51.165.126:30303"));
            config.setBootstrapNodes(nodes);
            config.setEthereumChainConfig(Geth.getTestnetChainConfig());
            config.setEthereumGenesis(Geth.getTestnetGenesis());
            config.setEthereumTestnetNonces(true);
            config.setEthereumNetworkID(2);
            config.setMaxPeers(25);
 } 
catch (Exception e) {
            e.printStackTrace();
}
return config;
`

If this isn't the right place to ask these questions let me know where I should ask them instead.  Thanks!

**Comment by ligi** [comment]
@phillyfan1138 
how long did you wait? You might want to try this enode: enode://b8d29479eb403aa190ecc45157c74535a4015e00a4162a45a7d5e5110d4bf025bff3a65267d086d937a9bf5f45b08329bac6b1029f28eef3337411f38ec9bf81@162.243.63.248:30303

perhaps http://ethereum.stackexchange.com is a better place for questions?
