### ISSUE TITLE
out of gas?

### ISSUE THREAD

**Issue by daniel-lucio** [ethereum/go-ethereum#3011]
Hi, I am getting this:
I0919 03:15:43.861550 core/state_transition.go:258] VM call err: Out of gas

When I start geth, i sync only once, and then I start getting this message. ANd I am stuck, is this a bug or big mistake of my part?

#### System information

Geth version: 1.4.12
OS & Version: Linux
#### Expected behaviour
Sync the block chain

#### Actual behaviour
Stuck syncing

#### Backtrace

````
[backtrace]
````

**Comment by bas-vk** [comment]
Your node is executing transactions against its local state. If a transaction doesn't have enough gas it will be aborted and any state changes are reverted. This is normal behavior and should normally not lead to a node that stops synching.

2 days ago there was an security problem that causes geth nodes to crash. You have the patched version but during that time the number of nodes dropped significantly. That might explain why you had synchronization issues 2 days ago. Is your node still not synchronizing?

**Comment by daniel-lucio** [comment]
Hi, my node syncs, but suddenly 4 hrs ago, it is syncing very very slow. 1 or 2 blocks each 5 minutes.

**Comment by bas-vk** [comment]
That is probably caused by a new simular attack. You can read more details [here](https://blog.ethereum.org/2016/09/22/transaction-spam-attack-next-steps/).
The team is working on a solution.
