### ISSUE TITLE
I want to set up a node quickly, do you have a snapshot？

### ISSUE THREAD

**Issue by dg123lzk** [ethereum/go-ethereum#30114]
I want to set up a node quickly, do you have a snapshot？

**Comment by rjl493456442** [comment]
Nope, you have to either run snap sync or full sync to bootstrap your node from scratch. Checkout https://geth.ethereum.org/docs/fundamentals/sync-modes and https://geth.ethereum.org/docs/getting-started/consensus-clients for more details
