### ISSUE TITLE
Fatal: Failed to register the Ethereum service: only PoS networks are supported, please transition old ones with Geth v1.13.x 

### ISSUE THREAD

**Issue by congmucc** [ethereum/go-ethereum#30120]
I'm a beginner, I just want to build a private chain locally, but I need pos to build, I found a lot of tutorials, like issues, blogs, gethDoc, but the tutorials are very old or haven't been found, how can I make the program work. I want to implement a way that can be compiled in remix and can be packaged natively, here are my commands and genesis.
![image](https://github.com/ethereum/go-ethereum/assets/123617755/9d519cbd-160b-42dc-afd2-0b6d3bc8e492)

```json
{
  "config": {
    "chainId": 8888,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "berlinBlock": 0,
    "clique": {
      "period": 5,
      "epoch": 30000
    }
  },
  "difficulty": "1",
  "gasLimit": "8000000",
  "extradata": "0x00000000000000000000000000000000000000000000000000000000000000007df9a875a174b3bc565e6424a0050ebc1b2d1d820000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "alloc": {
    "7df9a875a174b3bc565e6424a0050ebc1b2d1d82": { "balance": "300000" },
    "f41c74c9ae680c1aa78f42e5647a62f353b7bdde": { "balance": "400000" }
  }
}
```

```cmd
geth --datadir "data" init genesis.json
```

```cmd
geth --datadir data --networkid 8888 console 2>geth.log
```
There's no network set up here, I know that, but I couldn't use an earlier version before, so I wanted to ask.

**Comment by luleigreat** [comment]
@congmucc

**Comment by congmucc** [comment]
> @congmucc

thank you! It worked for me.

**Comment by congmucc** [comment]
> Did you solve the problem?

yeah

**Comment by Elitewebdigitals** [comment]
u got the solution?

**Comment by congmucc** [comment]
> u got the solution?

I used foundry. Geth doesn't work well.
