### ISSUE TITLE
I'm need web3 dev

### ISSUE THREAD

**Issue by olivereth** [ethereum/go-ethereum#30124]
Greetings everyone, our team is looking for employees. We need Web3 developers, Nft artists, beta testers, managers, advertisers. We are ready to pay from 10.000$ per month. All you need is a computer, a couple free hours a day and a desire to work. Also we have good bonuses, career growth, friendly team. Our company has a certificate, before starting work is made prepayment. If you are interested, then write to me in private messages.
My contacts:
telegram: @web3oliver
discord: ethereum033

**Comment by MariusVanDerWijden** [comment]
This is not the place to advertise your startup.
