### ISSUE TITLE
Generate a vendor/dependency tarball alongside releases

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/go-ethereum#30136]
# Rationale

Gentoo (and maybe other source-based distros) benefits from easy access to a tarball of dependencies. See [Writing go Ebuilds: Packaging the dependencies](https://wiki.gentoo.org/wiki/Writing_go_Ebuilds#Packaging_the_dependencies).

# Implementation

Generating the tarball is pretty trivial:

```bash
$ GOMODCACHE="${PWD}"/go-mod go mod download -modcacherw -x
$ tar --create --auto-compress --file go-ethereum-1.14.6-deps.tar.xz go-mod
```

Would need to be added to whatever your release process is, and the tarball would need to be hosted somewhere.

**Comment by karalabe** [comment]
FWIW we already do this for the PPA builds: https://github.com/ethereum/go-ethereum/blob/master/build/ci.go#L866

That said, I don't think hosting that data in a standalone package makes much sense for us, it just leaks out gentoo specifics into our downloads page. Also PPA is a painful enough annoyance we're only supporting for legacy reasons, definitely don't want to add more distros to support.

If you want to push geth into a gentoo package manager, you'll need some custom code anyway to pull some package bundle and make it gentoo-ish, so why not prep the dep sources then yourself?

**Comment by SamWilsn** [comment]
> we already do this for the PPA builds

That would probably work for me! Do you happen to know if PPAs publish a deb-src repo?

> If you want to push geth into a gentoo package manager, you'll need some custom code anyway to pull some package bundle and make it gentoo-ish, so why not prep the dep sources then yourself?

Geth is [already packaged](https://packages.gentoo.org/packages/net-p2p/go-ethereum) for Gentoo. I was hoping to remove a manual step.

**Comment by karalabe** [comment]
Source files are published on launchpad, yes https://launchpad.net/~ethereum/+archive/ubuntu/ethereum/+packages

**Comment by SamWilsn** [comment]
Wasn't too painful to use the PPA instead. We'll see if the Gentoo maintainers like it!

https://github.com/gentoo/gentoo/pull/37502/files
