### ISSUE TITLE
Sepolia synchronization progress stops

### ISSUE THREAD

**Issue by junghyun0783** [ethereum/go-ethereum#30144]
hello.

Suddenly, the Sepolia node that was working fine is not synchronizing.

geth version: v1.14.6
prysm version: v5.0.4

please. Why doesn't something that was going well suddenly work?

![58](https://github.com/ethereum/go-ethereum/assets/25001497/f1b9ee44-8fe6-4218-9d73-b624e00adf19)

**Comment by rjl493456442** [comment]
Geth is waiting the signal from the prysm. Please open the issue in their repo.
