### ISSUE TITLE
Error when trying to set the compiler path

### ISSUE THREAD

**Issue by Dvisacker** [ethereum/go-ethereum#3015]
Hey everyone, newbie here, so go easy please. Not sure if this is the right place to post about this by the way, but couldn't figure it out.

So i'm trying to run a private chain for development and the current issue I am having is setting the compiler. Solc is installed but apparently not in the path. Here are the logs :

`admin.setSolc("/usr/local/bin/solc")`

And here is the error i get : 

`exec: "/usr/local/bin/solc": permission denied
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:1`

I tried to give read and write permissions to this folder but could not get it to work. Not sure what permissions the error message is actually about. Any ideas about that ?

Thanks in advance

**Comment by bas-vk** [comment]
> I tried to give read and write permissions to this folder but could not get it to work.

Permissions on the directory level are for something else. Maybe `/usr/local/bin/solc` points to the directory where solc is installed? In that case you get the permission denied error.

Could you give the output of:
1. file /usr/local/bin/solc
2. ls -l /usr/local/bin/solc

**Comment by fjl** [comment]
Is this issue resolved?

**Comment by fjl** [comment]
@Dvisacker ping

**Comment by hzxscyq** [comment]
```
hzxscyq@ubuntu:~$ file /usr/local/bin/solc
/usr/local/bin/solc: symbolic link to ../lib/node_modules/solc-cli/dist/index.js
hzxscyq@ubuntu:~$ ls -l /usr/local/bin/solc
lrwxrwxrwx 1 root root 42 Oct  9 10:10 /usr/local/bin/solc -> ../lib/node_modules/solc-cli/dist/index.js
```
I have the same issue and this is my output

**Comment by LucKjy** [comment]
you can try       admin.setSolc("/usr/local/bin/solcjs")

**Comment by u2** [comment]
The same as #2944

**Comment by fjl** [comment]
solc from npm cannot be used with geth.
