### ISSUE TITLE
crypto.HexToECDSA: request to make it accept "0x" prefixed private key strings

### ISSUE THREAD

**Issue by samlaf** [ethereum/go-ethereum#30163]
# Rationale

Is there any reason why currently [HexToECDSA](https://github.com/ethereum/go-ethereum/blob/71210b0630e4f8dd2e7bcc7c39424fb2382e4f00/crypto/crypto.go#L192) errors when passed a 0x prefixed private key?

This is kind of a burden for us and leads to a lot of bugs because for eg anvil private keys are returned with 0x prefixes, so copy pasting that into our configs often leads to bugs, so much so that we had to create our own [wrapper around HexToECDSA](https://github.com/Layr-Labs/eigencert/blob/0917089b76b84b5d2430829012bd1e66c22411ed/common/crypto/ecdsa.go#L11).

# Implementation

On the other hand, [common.HexToAddress](https://github.com/ethereum/go-ethereum/blob/71210b0630e4f8dd2e7bcc7c39424fb2382e4f00/common/types.go#L229) does call `FromHex()` to remove the 0x prefix for addresses.

Is there a reason why `FromHex()` is not called in the private key function, but it is in the address function? 

If not, can I make a PR to add this to HexToECDSA?

**Comment by gballet** [comment]
`common.Hex*` are deprecated and we will slowly remove them. Use `hexutil` instead.

**Comment by samlaf** [comment]
@gballet why do you think it should be strict? This change is fully backward compatible and won't break any old code.
