### ISSUE TITLE
When will the patch be released?

### ISSUE THREAD

**Issue by junghyun0783** [ethereum/go-ethereum#30164]
hello.
I have a question.
I would like to know in advance before the geth version is patched.
Is there a schedule that lets me know when the patch will be available?
I think there is definitely an Ethereum schedule.
Please provide a site or link.

We plan to prepare in advance before the patch is implemented.

**Comment by s1na** [comment]
There is no pre-determined schedule for the releases. *Usually* there is a maintenance release every 2-4 weeks. But, don't count on it. The rule of thumb is: ship it when it's ready.

With the exception of security releases. They are usually pre-announced. Please follow [@go_ethereum](https://x.com/go_ethereum) on X, or join the discord #announcements channel: https://discord.gg/sTuyVXpf
