### ISSUE TITLE
handshake failing when peering into geth using a custom go client

### ISSUE THREAD

**Issue by visualbasic6** [ethereum/go-ethereum#30179]
hi,

is geth broken, or poorly documented? i need alien brains itt

**observe**: https://asciinema.org/a/668514

**specifically**:
```
[2024-07-17 17:24:26] [INFO] 🔵 Handshake completed successfully                                                                              
[2024-07-17 17:24:26] [TRACE] 🔍 Sending message: code=2, payload=c101                                                                        
[2024-07-17 17:24:26] [ERROR] 🔴 Connection error: connection closed by peer. Retrying in 5 seconds...                                        
```

after performing the rlpx handshake, the `hello` and `status` message exchanges in that order, 'completing' the handshake results in a remote disconnection by the geth node it's supposed to be peering into. I've tried to connect and instantly request block headers, and ping/pong for an idle connection, etc. - i've tried pretty much everything.

if anyone can point me in the right direction i'd appreciate that. unable to sign up for stackexchange - but heard some rumors of a discord channel called #protocol_fellowship (or something to that effect) but i have no idea if they're actually able to help.

that's why i'm opening this issue and trying to contact geth programmers directly.

**source**: https://pastebin.com/raw/05yc16w6 (ai assisted)

**how to run**:
```
snap install go --classic
go run whatever_you_saved_it_as.go
```

what do i do after handshaking? insta-requesting headers or pongs is just disconnecting. and is it even handshaking correctly? 🤔

as you can see here - it's failing after the handshake is complete, or "complete" - idk yet

[![asciicast](https://asciinema.org/a/668514.svg)](https://asciinema.org/a/668514)
do you see the last 3 lines? do you see?

![image](https://github.com/user-attachments/assets/d05c3155-1192-4b93-9712-a37d110fde0d)

any help would be appreciated. this is a geth issue and definitely not some variant of cunningham's law.

thanks,
[x.com/123456](https://x.com/123456)

**Comment by lightclient** [comment]
Please take a look at the example here for how to peer with another client over devp2p: https://github.com/ethereum/go-ethereum/blob/master/cmd/devp2p/internal/ethtest/conn.go

If you find a specific issue, feel free to open a new issue detailing it.

**Comment by visualbasic6** [comment]
based - that worked

https://asciinema.org/a/668587
