### ISSUE TITLE
Latest version 0.8.3 been compromised? Checksum not match

### ISSUE THREAD

**Issue by mbbyc** [ethereum/go-ethereum#3017]
#### System information

Geth version: `0.8.3`
OS & Version: Windows

I ran SHA checksum and get different checksum code per the website:

sha256sum.exe "Ethereum.Wallet.Setup.0.8.3.exe.zip"
f965f5050408e78fca28da060366619a13e94f3f7270c2f1cd49c30dad08840d *Ethereum.Wallet.Setup.0.8.3.exe.zip

According to the site the checksum should be:
a2ce520c6fec7196332517b9e094e6e1bb4652bdb25b1b73afc002d9db49411a  ./dist_wallet/release/Ethereum Wallet Setup 0.8.3-ia32.exe.zip
fce23a5445c041556622ea1588c1bca5a20bb32c0f1796398bbae7b71f93f1e0  ./dist_wallet/release/Ethereum Wallet Setup 0.8.3.exe.zip
227ee182165932c240a0fc4e7d7504d8320eaf94743879c690c72cc4f713fda7  ./dist_wallet/release/Ethereum Wallet-0.8.3-ia32.deb
bd102641a5c9b91b9e4616ed5910510ef9fd0604e13ce96f54c00c7620bdd927  ./dist_wallet/release/Ethereum Wallet-0.8.3.deb
b5fba40142090010e34f2fad332e481c63af19eb857d74370cf3eab3475a6f7a  ./dist_wallet/release/Ethereum Wallet-0.8.3.dmg

Please help to confirm the situation.

#### Backtrace

````
[backtrace]
````

**Comment by evertonfraga** [comment]
@mbbyc this is fixed. Head to Mist release page for updated checksums.
