### ISSUE TITLE
EIP-712 typed data validation does not support fixed size arrays

### ISSUE THREAD

**Issue by mdymalla** [ethereum/go-ethereum#30183]
#### System information

Geth version: `latest (1.14.7)`

#### Expected behaviour

Encoding a typed data struct should support fixed size arrays as EIP-712 specifies, _Arrays are either fixed size or dynamic and denoted by Type[n] or Type[] respectively_.

#### Actual behaviour

Encoding a typed data struct fails validation if a fixed size array is referenced

#### Steps to reproduce the behaviour

declare a `TypedData` variable:
```
typedData := TypedData{
		Types: Types{
			"BulkOrder": []Type{
				{Name: "tree", Type: "OrderComponents[2][2]"},
			},
			"OrderComponents": []Type{
				{Name: "offerer", Type: "address"},
				{Name: "amount", Type: "uint8"},
			},
			"EIP712Domain": []Type{
				{Name: "name", Type: "string"},
				{Name: "version", Type: "string"},
				{Name: "chainId", Type: "uint8"},
				{Name: "verifyingContract", Type: "address"},
			},
		},
		PrimaryType: "BulkOrder",
		Domain: TypedDataDomain{
			VerifyingContract: "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC",
		},
		Message: TypedDataMessage{},
}
```

call `EncodeData` method on the variable:
```
typedData.EncodeData("EIP712Domain", typedData.Domain.Map(), 1)
```

**Comment by holiman** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/30175 (thank you!)
