### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by behazin** [ethereum/go-ethereum#3020]
I get time out in geth.

![geth-time-out](https://cloud.githubusercontent.com/assets/210366/18709533/7e686bb0-800d-11e6-8534-f6e2c36e43e6.PNG)

**Comment by bas-vk** [comment]
Don't worry, this is just a peer not responding fast enough.
It will be dropped after the timeout.

**Comment by behazin** [comment]
But it take 7 hour and it stil time out
