### ISSUE TITLE
When the IP address included in the ENR is a multicast address, the Node information is discarded. But Why?

### ISSUE THREAD

**Issue by thinkAfCod** [ethereum/go-ethereum#30215]
After parsing the node information from the ENR, to check the validity of the IP address.
```
func newNodeWithID(r *enr.Record, id ID) *Node {
	n := &Node{r: *r, id: id}
	// Set the preferred endpoint.
	// Here we decide between IPv4 and IPv6, choosing the 'most global' address.
	var ip4 netip.Addr
	var ip6 netip.Addr
	n.Load((*enr.IPv4Addr)(&ip4))
	n.Load((*enr.IPv6Addr)(&ip6))
	valid4 := validIP(ip4)
	valid6 := validIP(ip6)
	switch {
	case valid4 && valid6:
		if localityScore(ip4) >= localityScore(ip6) {
			n.setIP4(ip4)
		} else {
			n.setIP6(ip6)
		}
	case valid4:
		n.setIP4(ip4)
	case valid6:
		n.setIP6(ip6)
	}
	return n
}
```

Not only is the IP validity checked, but it is also checked whether the IP is a multicast address. 
```
func validIP(ip netip.Addr) bool {
	return ip.IsValid() && !ip.IsMulticast()
}
```
If the IP is a multicast address, the validIP method will return false.And this Node's IP attribute will not be initialized, and in subsequent processes, this Node will be discarded.

Why can't nodes using multicast addresses be added to the Ethereum network?

**Comment by fjl** [comment]
They cannot be added because Ethereum uses unicast only. Allowing multicast addresses could create additional unwanted traffic triggered by an attacker.
