### ISSUE TITLE
abigen transact function should return unsigned tx if no signer found

### ISSUE THREAD

**Issue by shrimalmadhur** [ethereum/go-ethereum#30233]
# Rationale

Currently https://github.com/ethereum/go-ethereum/blob/f94baab238a64895e78034522092e935628c6c74/accounts/abi/bind/base.go#L416-L425

when in the transact opt if there's no signer it returns an error. But we have this flag `noSend` which decides whether to send this tx or not. In terms of usage I believe if `noSend` is true and if `Signer` is not present, it should just return the raw unsigned tx back instead of error

Why should this feature exist?
It's a great feature where users want to to use smart contract bindings to create tx but sign and send it themselves.

What are the use-cases?
- A user want to create a smart contract unsigned transaction which they will sign and send themselves

# Implementation

Do you have ideas regarding the implementation of this feature?
Yes. It's would be quite simple to move code around to achieve these this feature

Are you willing to implement this feature?
Yes

**Comment by lightclient** [comment]
Hi thanks for your concern. I noted in your PR that it is already possible to return a raw transaction by using a mock signer. Please see that comment for more information: https://github.com/ethereum/go-ethereum/pull/30235#issuecomment-2263609871
