### ISSUE TITLE
oSUICIDE opcode

### ISSUE THREAD

**Issue by sekomer** [ethereum/go-ethereum#30240]
hi, I was tweaking around initial commits of Ethereum(or [ethereal](https://github.com/ethereum/go-ethereum/commit/98811f11e5d7ccf6e053b46b9ca2ed897140ce47) :D), I encountered an interesting opcode, which is 
```go
"SUICIDE":    "255", // 0xff
```
its on the parsing.go file of the initial commit, https://github.com/ethereum/go-ethereum/blob/5db3335dce766bd679c54ea44f6df08a7ff74762/parsing.go#L50

I wonder what was the purpose of this opcode, thanks :)

cc: @obscuren

**Comment by lightclient** [comment]
`SUICIDE` was renamed to `SELFDESTRUCT` with [EIP-6](https://eips.ethereum.org/EIPS/eip-6)
