### ISSUE TITLE
the pivot in fast synchronization

### ISSUE THREAD

**Issue by xuyi33333** [ethereum/go-ethereum#30244]
I would like to ask if there is a method to obtain the **state** corresponding to a specific block height while using **fast** mode synchronization, rather than obtaining the state at the **pivot**. In other words, is there a way to adjust the **pivot** value to specify the location of the **state**？

**Comment by rezababaeeeiii** [comment]
30224

**Comment by rjl493456442** [comment]
It's impossible. 

The P2P network will retain the states of only the most recent 128 blocks, with no assurance that older states will be retrievable. It's the reason the pivot state is always chosen dynamically.
