### ISSUE TITLE
Gas estimation failed with unknown To address

### ISSUE THREAD

**Issue by whiskyfrenzy** [ethereum/go-ethereum#30262]
I'm getting gas estimation errors leading to my transactions not going through. Here is the error message:

`Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":256,\"error\":{\"code\":3,\"message\":\"execution reverted\",\"data\":\"0x\"}}", error={"code":3,"data":"0x"}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"from\":\"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266\",\"to\":\"0x2ce1F0e20C1f69E9d9AEA83b25F0cEB69e2AA2b5\",\"data\":\"0x2fe69784000000000000000000000000000000000000000000000000000bd342d3875ed9000000000000000000000000d9e1ce17f2641f24ae83637ab66a2cca9c378b9f\",\"value\":\"0x0\",\"type\":\"0x2\",\"maxFeePerGas\":\"0x60f7b0ba\"},\"latest\"],\"id\":256,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://127.0.0.1:1234", code=SERVER_ERROR, version=web/5.7.1)`

I read a similar problem on https://ethereum.stackexchange.com/questions/86646/go-ethereum-estimategas-errors that the "To" field was an unknown address and making sure a valid "To" address is defined will solve this issue. However, I'm not defining this "To" address anywhere in my code.

My question - is **0x2ce1F0e20C1f69E9d9AEA83b25F0cEB69e2AA2b5** coming from Geth? Perhaps its used as a default value when no "To" address is defined? If so, what should this "To" address be?

**Comment by jwasinger** [comment]
When no `to` address is defined, the contract is treated as a contract creation transaction.  The address `0x2ce1F0e20C1f69E9d9AEA83b25F0cEB69e2AA2b5` is derived by hashing the sender address with current nonce.

The error `execution reverted` indicates to me that either:
* the contract creation init code caused an execution error.
or:
* there was not enough gas to execute the contract creation transaction.

I would lean towards it being the former.
