### ISSUE TITLE
Geth sync hangs continuously

### ISSUE THREAD

**Issue by iFA88** [ethereum/go-ethereum#3029]
Some block synchronization is very slow, sometimes takes 10 minute only one block.
If you check the gist, you can see the secund and third 'imported' log with a huge different.
After the first syncing process the geth has worked ~2 days good.
On 22. 9. has anything started and the block sync has slowed down so much, that the geth have put himself to 'syncing' status until i shut him down.
Today ( 23. 9. ) have realized the problem, and I have connected to the console and have checked the eth.syncing command:
```
{
  currentBlock: 2306923,
  highestBlock: 2311008,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 2306818
}
```
Geth has fell behind with many block during syncing. Then i have applied 'debug.vmodule("downloader=6")' command and created a GIST with the shorted log:
https://gist.github.com/iFA88/3b4ffa9e15c16c34c000d8c5f2bf4f26

I use Geth/v1.5.0-unstable-c8d6efd6/linux/go1.7 on debian Jessie.

**Comment by dylanmckendry** [comment]
I am having a very similar issues. I believe it is to do with these attacks. Normally my node runs fine (like no issues for a month), but with these attacks it is even slower than yours. Right now the node is 17 hours behind the network...

From the looks of it these attacks are causing "~50,000 disk fetches needed to process the transaction" (https://blog.ethereum.org/2016/09/22/transaction-spam-attack-next-steps/). Which is the massive issue for my geth node as it is running in Azure using the persistent network disk which I believe is really slow for many disk read and writes... Still trying out a few things like using the local non-persistent disk, just to see if it helps. If you deleted the data directory and use fast sync I believe you could skip those transactions but if it happens again you will be in the same place... That is what I did in the pervious attack.

**Comment by iFA88** [comment]
Thank you very much!
