### ISSUE TITLE
WARN [08-13|09:24:49.278] Served engine_forkchoiceUpdatedV3

### ISSUE THREAD

**Issue by junghyun0783** [ethereum/go-ethereum#30294]
We are currently running the Ethereum mainnet.

![geth](https://github.com/user-attachments/assets/93fb7954-a7a3-4b72-9ccd-67a5254d6fc0)

"WARN [08-13|09:24:36.658] Ignoring payload with missing parent number=20,518,789 hash=5a10ec..178898 parent=6b6a0f..4fee1c reason="beacon syncer reorging"

"WARN [08-13|09:24:49.278] Served engine_forkchoiceUpdatedV3 conn=172.18.0.3:39310 reqid=6 duration="151.392µs" err="beacon syncer reorging"

This log keeps coming up.
Why is this log coming up?
Is there any point where it could be a problem while running?

**Comment by MariusVanDerWijden** [comment]
Looks like your node is full syncing at the moment. You are at block ~5M from ~20M. Do you want to explicitly full sync?

**Comment by junghyun0783** [comment]
@MariusVanDerWijden 
hey~ 
Thank you for your kind reply.
Yes, that's right. I set sync-mode to "full".
If this is the mainnet, how much capacity will it take up?
Are archive mode and full mode different? Are they the same mode?

**Comment by chanderprakash20** [comment]
Full Sync Mode: Ideal for most users, with manageable disk usage (~500-700 GB), and suitable for interacting with the current blockchain state without historical data.
    Archive Mode: Necessary for specific use cases involving historical data, with very high disk usage (~10+ TB), and more demanding on hardware resources.

@junghyun0783

**Comment by MariusVanDerWijden** [comment]
They are different, archive node will store all historical state, thus +20TB of data.
The full node will prune all historical states away after verifying them, but most people sync their full node via snap sync (--syncmode snap) which also produces a full node, but its way faster (~10 hours compared to multiple days)

**Comment by chanderprakash20** [comment]
@junghyun0783 
you have any follow up question I can help you

**Comment by junghyun0783** [comment]
@MariusVanDerWijden 
Syncmode is currently full, but if I change it to snap and run it, will there be any problems with the node?
