### ISSUE TITLE
A lot of pending transactions, eth.resend doesn't work

### ISSUE THREAD

**Issue by Atrides** [ethereum/go-ethereum#3031]
#### System information

Geth version: 1.4.12-stable
OS & Version: Linux
#### Expected behaviour

Some transactions are pending and not send(?) to network.

"eth.resend" doesn't work, even with big gasprice:

> eth.resend(eth.pendingTransactions[0], 20000000000)
> Gas price too low for acceptance
>     at web3.js:3119:20
>     at web3.js:6023:15
>     at web3.js:4995:36
>     at <anonymous>:1:1
> 
> eth.resend(eth.pendingTransactions[0], 5000000000000, 90000)
> Gas price too low for acceptance
>     at web3.js:3119:20
>     at web3.js:6023:15
>     at web3.js:4995:36
>     at <anonymous>:1:1
> 
> eth.resend(eth.pendingTransactions[0], 5000000000000)
> Gas price too low for acceptance
>     at web3.js:3119:20
>     at web3.js:6023:15
>     at web3.js:4995:36
>     at <anonymous>:1:1

Checked in parity client on other server, transaction not known.

**Comment by Atrides** [comment]
That was because of queue in ethereum network.
But strange that cannot be resend again.

**Comment by fjl** [comment]
Fix released in 1.5.0.
