### ISSUE TITLE
`vcs.modified=true` on downloadable artefacts

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#30324]
Discovered by @vivi365

Downloading the official binaries, it seems that only the first (`geth-linux-amd64`) is built with a 'clean' vcs. Later on, the buildinfo reports that the filesystem is modified, thus to some degree tainting the builds. 

```
[user@work tmp]$ strings geth-linux-amd64-1.14.8-a9523b64/geth | grep "vcs.modified="
build	vcs.modified=false
build	vcs.modified=false
[user@work tmp]$ strings geth-linux-arm6-1.14.8-a9523b64/geth | grep "vcs.modified="
build	vcs.modified=true
build	vcs.modified=true
[user@work tmp]$ strings geth-linux-386-1.14.8-a9523b64/geth | grep "vcs.modified="
build	vcs.modified=true
build	vcs.modified=true
```

This is probably due to binaries being added to `build/bin`. It's not correct behaviour, and it makes reproducible builds (for other than `geth-linux-amd64`) harder to achieve.

**Comment by vivi365** [comment]
Right, since `/build/bin` is untracked it should not affect the `vcs.modified` field 

[Here](https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/load/pkg.go;drc=27093581b2828a2752a6d2711def09517eb2513b;l=2496) go sets `vcs.modified` to Uncommitted

Which is set through `git log` [here](https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/vcs/vcs.go;drc=27093581b2828a2752a6d2711def09517eb2513b;l=333)

**Comment by holiman** [comment]
Found it 
```
ser@debian-work:~/workspace/go-ethereum$ go run build/ci.go archive -type tar 
geth-linux-amd64-1.14.9-unstable-8486722d.tar.gz
   + COPYING
   + geth
geth-alltools-linux-amd64-1.14.9-unstable-8486722d.tar.gz
   + COPYING
   + abigen
   + bootnode
   + evm
   + geth
   + rlpdump
   + clef
user@debian-work:~/workspace/go-ethereum$ git status 
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	geth-alltools-linux-amd64-1.14.9-unstable-8486722d.tar.gz
	geth-linux-amd64-1.14.9-unstable-8486722d.tar.gz

nothing added to commit but untracked files present (use "git add" to track)
```
I must've been to fast first time I trie. So it's the upload-bundler which creates some artefacts in the repo root.
