### ISSUE TITLE
Research Project related to geth 

### ISSUE THREAD

**Issue by chanderprakash20** [ethereum/go-ethereum#30330]
Hi team I want to contribute research to geth could please connect and share interesting project related data technique of ethereum.I have good expereince in research could anyone their team connect with me .

**Comment by holiman** [comment]
Thanks for the show of interest, but it's not really something that is handled over a ticket. If you want to dive into Ethereum research in general, please see https://ethresear.ch/ and/or https://ethereum-magicians.org/ . 
If you want to contribute to go-ethereum, please look into tickets or PRs. If you have an idea of something you want to look into, you could possibly open a ticket to discuss the idea / implementation.

**Comment by chanderprakash20** [comment]
hi where I can find about ancient data technique could please tell about it where I can find research paper I do not find on these forums

**Comment by holiman** [comment]
Most of the stuff we do in go-ethereum isn't based on research papers, but rather discussions on and around PRs and tickets. Most canonical documentation is the code, or comments. `go-ethereum`, the software project, is programmer-driven, whereas the Ethereum protocol in a wider perspective is driven more by research from whitepapers and forum discussions.

**Comment by holiman** [comment]
> If you want to dive into Ethereum research in general, please see https://ethresear.ch/ and/or https://ethereum-magicians.org/ .
