### ISSUE TITLE
Is it normal that RPC provider will return error message but transaction is actually successful?

### ISSUE THREAD

**Issue by AlvinLow0725** [ethereum/go-ethereum#30341]
I am currently new here at blockchain. I am currently using a subscribed private rpc ankr and Moralis. So, it is normal that rpc will return us some errors but transaction still manages to be made successfully at bscscan? It does not cause error everytime, it happens randomly. Sometime I get Internal JSON RPC error, Already Existed: already known and etc. If that's the case, how should I handle the situation, other than switching to other provider? I have an issue when user makes withdrawal, frontend will show the error message based on the response from the rpc provider but the transaction is actually successful. Therefore, the amount of the user's wallet dAPP doesn't deduct as the function will only trigger when the rpc response message return is successful.

Here's my code

    const { gasPrice, maxPriorityFeePerGas } = await getCurrentGasPrices();
    const maxFeePerGas = gasPrice + maxPriorityFeePerGas;

    const amount = formData.amount;
    const value = ethers.parseEther(amount);
    const wallet = new ethers.Wallet(formData.secretKey, provider);
    let tempErrorData = "";
    let errorLongData = "";

    const txnInfo = await wallet.populateTransaction({
        to: userProfile.wallet_address,
        value: value,
        gasLimit: 21000,
        maxFeePerGas,
        maxPriorityFeePerGas,
        timeout: 500
    }).catch(error => {
        errorLongData = error;
        console.error("Populate 1 Error", error);
        const parsedEthersError = getParsedEthersError(error);
        console.log("parsedEthersError", parsedEthersError);
        tempErrorData = parsedEthersError.context;
    });

    let tx = await wallet.sendTransaction(txnInfo)
        .catch(error => {
            errorLongData = error;
            console.error("error", error);
            const parsedEthersError = getParsedEthersError(error);
            console.log("parsedEthersError", parsedEthersError);
            tempErrorData = parsedEthersError.context;
        });

    console.log("TX", tx);

**Comment by vargab95** [comment]
I have the same problem using private ankr nodes. I get "Returned error: ALREADY_EXISTS: already known" errors randomly on both ethereum and bsc nodes, while the transaction is successful according to bscscan and etherscan.

**Comment by vargab95** [comment]
After reading your ticket, I did some investigation. In my system, the ALREADY_EXISTS error was first detected at 2024-08-14T17:18:06.960Z. I checked my ankr endpoint by using the following command.
```
▶ curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' https://rpc.ankr.com/eth/ 
{"id":67,"jsonrpc":"2.0","result":"erigon/2.60.6/linux-amd64/go1.21.6"}
```
As you see it returned that ankr uses the Erigon ETH implementation version 2.60.6. That version was released at 2024-08-14T09:33:39Z. So maybe it's rather a potential ticket against the erigon project, but correct me if I'm wrong.

**Comment by AlvinLow0725** [comment]
@vargab95 Hi, possible as well from your investigation as I have never encountered this issue before using this private ankr RPC. It only happens since last week. I am currently using other provider now for my DAPP, but the stability and reliability of the RPC still needs to be investigated.

**Comment by AlvinLow0725** [comment]
@karalabe In terms of my DApp side react based on events fired from the chain, may I know how should I get the events from the chain? Currently I am using the api provided by BSC Scan to detect the transaction log from the wallet by comparing nonce ID for around 30 seconds after making transaction. Is this an ideal way for handling this situation? Or is there any better way? Thank you.

**Comment by karalabe** [comment]
@AlvinLow0725 If your transaction emits events, you could subscribe to those events and then you'd get a notification from your RPC provider when the event hits. If you don't emit events, or just want to see in general if it worked or not, you could subscribe to chain head events and then see if the tx was included (kind of like how you do it, just perhaps checking for a nonce only is not the best because it could have been replaced; probvably better to check for the tx hash specifically).

**Comment by AlvinLow0725** [comment]
@karalabe Hi, basically based on what you mean on subscribe to chain head events, it means that it is like a web socket which will keep running at background to do checking. Is this the example to handle it?

`const Web3 = require('web3');

// Initialize Web3 with an RPC provider
const web3 = new Web3('https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID');

// Subscribe to new block headers
web3.eth.subscribe('newBlockHeaders', (error, blockHeader) => {
    if (error) {
        console.error('Error subscribing to new block headers:', error);
        return;
    }

    console.log('New block received. Block number:', blockHeader.number);

    // Fetch the full block by its number
    web3.eth.getBlock(blockHeader.number, true).then(async (block) => {
        if (block && block.transactions) {
            // Loop through all transactions in the block
            for (let tx of block.transactions) {
                try {
                    // Fetch the transaction receipt
                    const receipt = await web3.eth.getTransactionReceipt(tx.hash);
                    
                    if (receipt && receipt.status === false) {
                        console.log('Failed transaction detected:', tx.hash);
                        // Handle the failed transaction (e.g., log, alert user, etc.)
                    }
                } catch (err) {
                    console.error('Error fetching transaction receipt:', err);
                }
            }
        }
    }).catch(err => {
        console.error('Error fetching block:', err);
    });
});
`

**Comment by vargab95** [comment]
An additional test result. It is maybe helpful for someone. On ankr private nodes it definitely comes randomly with non-repeated transactions (without "the same tx given twice"). I retested the same code with non-ankr / non-erigon public nodes and the problem did not occur anymore.
