### ISSUE TITLE
Go-ethereum ignores database read errors causing invalid state to be computed

### ISSUE THREAD

**Issue by PlasmaPower** [ethereum/go-ethereum#30383]
In many places in `rawdb`, go-ethereum ignores database errors, and treats them equivalently to the key not existing. For instance, I believe we hit this issue with `ReadAccountSnapshot`, which has the same return value if an account doesn't exist or if a database error was hit, e.g. failing to read a file or "too many open files": https://github.com/ethereum/go-ethereum/blob/922eb033d3553d97907506d08fdb1e0ccdc5bead/core/rawdb/accessors_snapshot.go#L75-L79

This can cause an invalid state to be computed, in the case of a miner/staker potentially proposing an invalid state. This database error is not tracked in the statedb's `dbErr` field, which would prevent the commit. Instead, the incorrect empty account data is cached at the callsite to ReadAccountSnapshot and treated as the account not existing in state: https://github.com/ethereum/go-ethereum/blob/922eb033d3553d97907506d08fdb1e0ccdc5bead/core/state/snapshot/disklayer.go#L120-L121

In the circumstance we hit this, we were at the limit of open files on the system on a pebbledb database, and I believe a `ReadAccountSnapshot` read failed due to this, causing go-ethereum to think an account didn't have any balance when it actually did. However, the state commit of the invalid state succeeded, probably because it was committing state in-memory or to a database file that was already open, and eventually some files got closed and the database recovered albeit with invalid state.

That's not to say this is the only example where a database error could cause go-ethereum to produce invalid state. I suspect there are many other potential causes of database errors and potentially other rawdb accessors which can silently fail and lead to invalid state being computed. While most callers of rawdb accessors seem to correctly treat an empty return value as an error, it's hard to track, because the rawdb accessors throw away the error and instead rely on the caller to realize something's wrong.

I'd recommend rawdb accessors either use the database's `Has` method (and require it not error, unlike the current rawdb accessors checking if a key exists or not) or check the error from `Get` with something like `errors.Is(err, leveldb.ErrNotFound) || errors.Is(err, pebble.ErrNotFound) || errors.Is(err, memorydb.ErrMemorydbNotFound)` and return an error to the caller if it's an unexpected error not in that list.

**Comment by karalabe** [comment]
This is a known issue, but also it's something we deliberately left as is. If a database error occures, there's absolutely nothing we can do. It's an exceptional scenario that Geth cannot ever recover from.

Option 1 is to just crash. However, if the error is temporary (e.g. file descriptor issue), then it could happen that it can self-recover when that issue mitigates. As such, it might be better to just go on and hope for the best. That was our reasoning.

AFAIK a file descriptor issue point to a deeper issue with your setup where something external is exhausing them (e.g. shooting a lot of RPC requests, each on a new HTTP connection).

I don't think we want to introduce a lot of error handling to database reads since there's nothing we can do to act on the errors.

**Comment by PlasmaPower** [comment]
I generally agree, but continuing on with incorrect state seems like the worst possible outcome. I think the ideal outcome would be to temporarily return an error from block production similar to how statedb's dbErr returns an error from Commit, but I get not wanting to complicate the code with additional error handling. That said, in the case of ReadAccountSnapshot, it seems like there's already a good opportunity to return an error at the ReadAccountSnapshot callsite in AccountRLP. The function is already setup to be fallible due to other issues like ErrSnapshotStale. In general, if it isn't possible to produce an error cleanly, crashing seems better than using incorrect state that won't cause an error.

**Comment by holiman** [comment]
I agree with @karalabe , let's keep it as is
