### ISSUE TITLE
p2p: nodeid must be static between sessions

### ISSUE THREAD

**Issue by subtly** [ethereum/go-ethereum#304]
The local node alias (private key), nodes, and peers MUST be saved and restored between sessions (network state file/database). 

The alias can be reset by manually deleting network state file/database. An option to reset alias from UI or CLI is NOT recommended; doing so resets the client's network and downgrades the nodes security by clearing it's ability to evaluate network trust.

Dependencies:
* kademlia: maliciousness is inverse to availability
* peer reputation
* peer connection strategy

Effects:
* reduces network churn
* reduces convergence overhead from major network power events (splits)
* tofu: trust on first-use
* [future] reduced overhead for DHT

**Comment by fjl** [comment]
It is now static.
