### ISSUE TITLE
Is there a one-to-one correspondence between an Ethereum execution layer node and an Ethereum consensus layer node？

### ISSUE THREAD

**Issue by TayC710** [ethereum/go-ethereum#30407]
I want to know if there is a one-to-one correspondence between an Ethereum execution layer node and an Ethereum consensus layer node, and if so, how it is implemented; If not, will there be a one to many or many to one situation？
```[tasklist]
### Tasks
```

**Comment by karalabe** [comment]
Unsure what you mean.

Currently one CL can use only one EL at a time, though any CL can use any EL (via the engine api). 

If you mean whether one client of a type could use multiple other type at the same time, then:

- I don't think there will ever be a way for multiple CLs to use a single EL.
- For a single CL to use multiple ELs, I have a proposal https://gist.github.com/karalabe/47c906f0ab4fdc5b8b791b74f084e5f9, which doesn't run full fledged ELs, rather just the important bits.
