### ISSUE TITLE
Support Delve debugger

### ISSUE THREAD

**Issue by fabiobozzo** [ethereum/go-ethereum#30406]
# Rationale
## Why should this feature exist?
The ability to debug test environments remotely is crucial for developers who need to diagnose and fix issues in a distributed development setup. By adding support for the Delve debugger in the Docker images, we can provide a more robust and flexible debugging experience. This feature will enable developers to attach a debugger to running containers, inspect the state of the application, and step through code execution in real-time.

## What are the use-cases?
- Remote Debugging: Developers can debug applications running in Docker containers from their local development environment.
- Enhanced Development Workflow: Simplifies the process of diagnosing issues in complex distributed systems by allowing real-time inspection and debugging.
- Improved Testing: Facilitates debugging of test environments, making it easier to identify and resolve issues during the testing phase.

# Implementation
## Do you have ideas regarding the implementation of this feature?
Yes, the implementation involves the following steps:

### Dockerfile Modification:
```
Install the Delve debugger in the Dockerfile.alltools.
Expose the default network port for Delve (4000).
```
### Build Script Update:
```
Add a new optional Docker image tag (debug) in build/ci.go.
Include the necessary build arguments to enable Delve for remote debugging.
```
## Are you willing to implement this feature?
Yes, I have already implemented the feature and submitted a PR for review: https://github.com/ethereum/go-ethereum/pull/30373

**Comment by jwasinger** [comment]
Given there are no changes to the codebase, I think you should build this feature into a custom image rather than integrating it here.
