### ISSUE TITLE
I want to receive them in archive mode.

### ISSUE THREAD

**Issue by junghyun0783** [ethereum/go-ethereum#30403]
I'm trying to run it in "snap" mode and then run it in "full" archive mode.
Can I continue to receive the existing blocks?
Or do I have to receive the blocks again?

I'm currently running a node in sepolia snap mode.
But I want to run it in "full archive" mode in snap.
Can I continue to receive the blocks by just changing -syncmode "full" --gcmode archive in config?

The photo below is the log after changing to full archive mode. Originally, it was received well when it was "snap", but currently, synchronization is not progressing.
![60](https://github.com/user-attachments/assets/73d5bf22-a7cd-4956-a89b-56990238f0be)

I desperately need the help of experts.

**Comment by junghyun0783** [comment]
This is the geth command.
`prysm.bat beacon-chain --execution-endpoint=http://localhost:8551 --sepolia --datadir=./prysm_data_sepolia --jwt-secret=../jwt_sepolia.hex --rpc-host=0.0.0.0 --grpc-gateway-host=0.0.0.0 --genesis-state=sepolia_genesis.ssz --suggested-fee-recipient=0x67CDB8344FFCa7aaaeda9e7a4F4f1A9cb4D1FC64`

**Comment by Titi68730** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by MariusVanDerWijden** [comment]
It looks like Prysm can't talk to Geth because of some issue with the JWT
