### ISSUE TITLE
bootnode works for local nodes but not for nodes from another machine

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [ethereum/go-ethereum#30420]
Hi, i am trying to work with the built-in bootnode (dev bootnode) in geth,

while the nodes on the **SAME PHYSICAL MACHINE** (lets say node A) can easily find each other with the bootnode

i run into an issue, when i try to connect a node that is present on a DIFFERENT PHYSICAL MACHINE (lets say node B),

that node cannot connect to this bootnode on Node A, even though i have used **extip** parameter to bind the bootnode to the public ip, with node 30301

here's the screenshot of the error given by the bootnode logs,

![image](https://github.com/user-attachments/assets/219f7541-61d5-4fd4-8972-140342a7c7b5)

how can i resolve Bad discv4 packet error (and what does "too small" indicate?)

**Comment by holiman** [comment]
Are `node A` and `node B` on the same local network? Or are they both behind separate natted networks? 
Please provide some details about your network setup.

**Comment by gballet** [comment]
Could you please also give us the public ips and ports?

**Comment by holiman** [comment]
Seems abandoned. Feel free to reopen if you have want to follow up with more information
