### ISSUE TITLE
RPM for CentOS 6 and 7 

### ISSUE THREAD

**Issue by daniel-lucio** [ethereum/go-ethereum#3042]
http://inside-out.xyz/technology/go-ethereum-1-4-13-rpm-for-centos-6-7.html

**Comment by fjl** [comment]
It's nice that you are providing RPMs. Can you share the package definition with us? Maybe we can add it to our build process.

We maintain a PPA on launchpad.net for Ubuntu deb packages. Is there a similar service that we could use to build and host packages for CentOS?

**Comment by daniel-lucio** [comment]
There is no a similar think like PPA in the Centos world, each one does what he wants to do (that's why there are many repos).
I made the RPM's for Mageia as well
http://svnweb.mageia.org/packages/cauldron/go-ethereum/current/

**Comment by probonopd** [comment]
With an [AppImage](http://appimage.org/), go-ethereum could be packaged once and could run on many Linux distributions, without the need for any installation.

**Comment by karalabe** [comment]
@probonopd Go binaries are statically linked. You can copy the same binary to any linux distro and it will run fine, no need for packaging with anything, just a single copy.

**Comment by probonopd** [comment]
@karalabe wow didn't know that, that's awesome! Thanks.
