### ISSUE TITLE
1.14.9 container image wasn't built

### ISSUE THREAD

**Issue by nazar-pc** [ethereum/go-ethereum#30469]
Docker Hub still doesn't have `v1.14.9` tag, the closest that exists is `v1.14.9-amd64`, but no `v1.14.9-arm64` build and no universal `v1.14.9` either.

**Comment by corverroos** [comment]
@holiman , just to confirm, the `v1.14.9` tag still hasn't been pushed. We can't upgrade to this version, we are blocked.

**Comment by emelbardis** [comment]
Same issue for just now released v1.14.10. Is this by design?

**Comment by corverroos** [comment]
@holiman @rjl493456442 most docker images for v1.14.10 are still missing. We are still blocked at v1.14.8 and cannot upgrade.

**Comment by holiman** [comment]
Yes, arm-images for docker are missing. We are aware, unfortunately we haven't been able to find a workaround.

Either the infra-provider where we run our builds need to fix their shit, or we need to switch backend. We were hoping for the former.

**Comment by jclapis** [comment]
This is a blocker for us as well.

**Comment by holiman** [comment]
We have now switched the way the docker images are built, in https://github.com/ethereum/go-ethereum/pull/30530. 

This means that we have now published the following: 

[alltools-latest](https://hub.docker.com/layers/ethereum/client-go/alltools-latest/images/sha256-b898b798882241aadfed6e9f63e959c704226478967a0309043f11c7c6be2438?context=explore)
[latest](https://hub.docker.com/layers/ethereum/client-go/latest/images/sha256-915d408c51905c36e5a003a7367aa0325c57bbf31595ed3da1a7046023d6ef4b?context=explore)

We will likely push a new `stable` (a.k.a `v1.14.11`) and `release-1.14` pretty soon, if for no other reason than to populate those docker images.

The `-amd64` and `-arm64` - tagged versions  **will no longer be maintained** (likely deleted to ensure that people don't become stuck on them unknowningly): 
- `alltools-latest-amd64`, `alltools-latest-arm64` -> **`alltools-latest`**
- `latest-amd64`,`latest-arm64` -> **`latest`**
- `v1.14.10-amd64`, `v1.14.10-arm64` -> **`v1.14.10`**

**Comment by nazar-pc** [comment]
1.14.11 works as expected, thanks everyone!
