### ISSUE TITLE
Ethereum Geth Node Sync Not Starting

### ISSUE THREAD

**Issue by datacoder-io** [ethereum/go-ethereum#30489]
I'm running a Geth node with the following configuration to sync using Snap Sync and WebSocket/HTTP-RPC for monitoring:

```
geth --syncmode snap \
     --gcmode full \
     --datadir data \
     --cache 4096 \
     --http \
     --http.addr 0.0.0.0 \
     --http.port 8545 \
     --http.api eth,net,web3,txpool,debug \
     --http.corsdomain "*" \
     --http.vhosts "*" \
     --ws \
     --ws.addr 0.0.0.0 \
     --ws.port 8546 \
     --ws.api eth,net,web3,txpool,debug \
     --ws.origins "*" \
     --maxpeers 50 \
     --txpool.globalslots 2048 \
     --txpool.globalqueue 4096 \
     --txpool.rejournal "30m" \
     --txlookuplimit 0 \
     --verbosity 3 \
     --ipcdisable
```

After starting Geth, the sync process does not seem to start. The logs show that the node starts up successfully but does not seem to progress with syncing the blockchain. Below are the logs when the node is first launched:

```
INFO [09-21|23:14:26.758] Loaded most recent local block           number=0 hash=d4e567..cb8fa3 td=17,179,869,184 age=55y6mo1w
INFO [09-21|23:14:26.759] Initialized transaction indexer          range="entire chain"
INFO [09-21|23:14:26.759] Loaded local transaction journal         transactions=0 dropped=0
INFO [09-21|23:14:26.775] Enabled snap sync                        head=0 hash=d4e567..cb8fa3
INFO [09-21|23:14:26.775] Gasprice oracle is ignoring threshold set threshold=2
WARN [09-21|23:14:26.776] Engine API enabled                       protocol=eth
INFO [09-21|23:14:26.776] Starting peer-to-peer node               instance=Geth/v1.14.9-stable-c350d3ac/linux-amd64/go1.23.1
INFO [09-21|23:14:26.847] New local node record                    seq=1,726,956,145,488 id=5a2e614b275d4012 ip=127.0.0.1 udp=30303 tcp=30303
INFO [09-21|23:14:26.902] Started P2P networking                   self=enode://6a21b36b8905d09d984d7d18676a9c602b3ffe41953b985a99496fdb09a2891397f33e87e4126251c6cfadb276f87830af475f543bc925816e3c3f57f00fb0e@127.0.0.1:30303
INFO [09-21|23:14:26.902] Loaded JWT secret file                   path=/tron_node/eth/data/geth/jwtsecret crc32=0xf76ebc33
INFO [09-21|23:14:26.903] HTTP server started                      endpoint=[::]:8545 auth=false prefix= cors=* vhosts=*
INFO [09-21|23:14:26.903] WebSocket enabled                        url=ws://[::]:8546
INFO [09-21|23:14:26.903] WebSocket enabled                        url=ws://127.0.0.1:8551
INFO [09-21|23:14:26.903] HTTP server started                      endpoint=127.0.0.1:8551 auth=true  prefix= cors=localhost vhosts=localhost
INFO [09-21|23:14:30.444] New local node record                    seq=1,726,956,145,489 id=5a2e614b275d4012 ip=192.155.100.161 udp=30303 tcp=30303
INFO [09-21|23:14:37.086] Looking for peers                        peercount=1 tried=301 static=0
INFO [09-21|23:14:47.144] Looking for peers                        peercount=1 tried=113 static=0
INFO [09-21|23:14:57.155] Looking for peers                        peercount=1 tried=144 static=0
WARN [09-21|23:15:01.776] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
INFO [09-21|23:15:07.260] Looking for peers                        peercount=1 tried=198 static=0
INFO [09-21|23:15:17.282] Looking for peers                        peercount=2 tried=221 static=0
INFO [09-21|23:15:27.288] Looking for peers                        peercount=3 tried=284 static=0
INFO [09-21|23:15:37.336] Looking for peers                        peercount=4 tried=267 static=0
INFO [09-21|23:15:57.427] Looking for peers                        peercount=3 tried=176 static=0
INFO [09-21|23:16:07.593] Looking for peers                        peercount=5 tried=144 static=0
WARN [09-21|23:20:01.810] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
```

Any help on this would be appreciated!

**Comment by Maliksb11** [comment]
Have a nice day 🥰

**Comment by Maliksb11** [comment]
> I'm running a Geth node with the following configuration to sync using Snap Sync and WebSocket/HTTP-RPC for monitoring:
> 
> ```
> geth --syncmode snap \
>      --gcmode full \
>      --datadir data \
>      --cache 4096 \
>      --http \
>      --http.addr 0.0.0.0 \
>      --http.port 8545 \
>      --http.api eth,net,web3,txpool,debug \
>      --http.corsdomain "*" \
>      --http.vhosts "*" \
>      --ws \
>      --ws.addr 0.0.0.0 \
>      --ws.port 8546 \
>      --ws.api eth,net,web3,txpool,debug \
>      --ws.origins "*" \
>      --maxpeers 50 \
>      --txpool.globalslots 2048 \
>      --txpool.globalqueue 4096 \
>      --txpool.rejournal "30m" \
>      --txlookuplimit 0 \
>      --verbosity 3 \
>      --ipcdisable
> ```
> 
> After starting Geth, the sync process does not seem to start. The logs show that the node starts up successfully but does not seem to progress with syncing the blockchain. Below are the logs when the node is first launched:
> 
> ```
> INFO [09-21|23:14:26.758] Loaded most recent local block           number=0 hash=d4e567..cb8fa3 td=17,179,869,184 age=55y6mo1w
> INFO [09-21|23:14:26.759] Initialized transaction indexer          range="entire chain"
> INFO [09-21|23:14:26.759] Loaded local transaction journal         transactions=0 dropped=0
> INFO [09-21|23:14:26.775] Enabled snap sync                        head=0 hash=d4e567..cb8fa3
> INFO [09-21|23:14:26.775] Gasprice oracle is ignoring threshold set threshold=2
> WARN [09-21|23:14:26.776] Engine API enabled                       protocol=eth
> INFO [09-21|23:14:26.776] Starting peer-to-peer node               instance=Geth/v1.14.9-stable-c350d3ac/linux-amd64/go1.23.1
> INFO [09-21|23:14:26.847] New local node record                    seq=1,726,956,145,488 id=5a2e614b275d4012 ip=127.0.0.1 udp=30303 tcp=30303
> INFO [09-21|23:14:26.902] Started P2P networking                   self=enode://6a21b36b8905d09d984d7d18676a9c602b3ffe41953b985a99496fdb09a2891397f33e87e4126251c6cfadb276f87830af475f543bc925816e3c3f57f00fb0e@127.0.0.1:30303
> INFO [09-21|23:14:26.902] Loaded JWT secret file                   path=/tron_node/eth/data/geth/jwtsecret crc32=0xf76ebc33
> INFO [09-21|23:14:26.903] HTTP server started                      endpoint=[::]:8545 auth=false prefix= cors=* vhosts=*
> INFO [09-21|23:14:26.903] WebSocket enabled                        url=ws://[::]:8546
> INFO [09-21|23:14:26.903] WebSocket enabled                        url=ws://127.0.0.1:8551
> INFO [09-21|23:14:26.903] HTTP server started                      endpoint=127.0.0.1:8551 auth=true  prefix= cors=localhost vhosts=localhost
> INFO [09-21|23:14:30.444] New local node record                    seq=1,726,956,145,489 id=5a2e614b275d4012 ip=192.155.100.161 udp=30303 tcp=30303
> INFO [09-21|23:14:37.086] Looking for peers                        peercount=1 tried=301 static=0
> INFO [09-21|23:14:47.144] Looking for peers                        peercount=1 tried=113 static=0
> INFO [09-21|23:14:57.155] Looking for peers                        peercount=1 tried=144 static=0
> WARN [09-21|23:15:01.776] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
> INFO [09-21|23:15:07.260] Looking for peers                        peercount=1 tried=198 static=0
> INFO [09-21|23:15:17.282] Looking for peers                        peercount=2 tried=221 static=0
> INFO [09-21|23:15:27.288] Looking for peers                        peercount=3 tried=284 static=0
> INFO [09-21|23:15:37.336] Looking for peers                        peercount=4 tried=267 static=0
> INFO [09-21|23:15:57.427] Looking for peers                        peercount=3 tried=176 static=0
> INFO [09-21|23:16:07.593] Looking for peers                        peercount=5 tried=144 static=0
> WARN [09-21|23:20:01.810] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
> ```
> 
> Any help on this would be appreciated!

**Comment by holiman** [comment]
```
WARN [09-21|23:20:01.810] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
```
This means that you are missing a CL-client, which is needed to direct geth. See https://geth.ethereum.org/docs/getting-started/consensus-clients for more info
