### ISSUE TITLE
Into the Woods (1.4.13) not syncing

### ISSUE THREAD

**Issue by woodaxed** [ethereum/go-ethereum#3049]
#### System information

Geth version: `geth version`1.4.13
OS & Version: Windows 7

wallet still going very slow  im stuck at Downloading block 2,333,116 of 2,334,953
its been like that for some hours now 
any advice  and please keep it simple im not a dev or programmer

#### Backtrace

````
[backtrace]
````

**Comment by lodos2005** [comment]
i got same issue,

https://github.com/ethereum/go-ethereum/issues/3044


`I0927 17:10:16.716256 ethdb/database.go:169] closed db:/root/.ethereum/chaindata
I0927 17:10:16.718002 ethdb/database.go:82] Alloted 1024MB cache and 1024 file handles to /root/.ethereum/chaindata
I0927 17:10:16.806137 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /root/.ethereum/dapp
I0927 17:10:16.814927 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0927 17:10:16.815745 eth/backend.go:201] Blockchain DB Version: 3
I0927 17:10:16.820965 core/blockchain.go:214] Last header: #2336231 [6c120b2e…] TD=66198927053045338164
I0927 17:10:16.821047 core/blockchain.go:215] Last block: #2335726 [146f19c7…] TD=66164307637598534655
I0927 17:10:16.821075 core/blockchain.go:216] Fast block: #2334735 [ffbe206e…] TD=66093263729668263183
I0927 17:10:16.823791 p2p/server.go:313] Starting Server
I0927 17:10:18.746682 p2p/discover/udp.go:217] Listening, enode://0c3ca14bfb22d08b8ccc6608678dfa44161465b394d8e900ce36edd3d8d10582d1f052a60e4387b3dd60f610b4d36eefc564cf5963fd87c164a94293349376a9@[::]:30303
I0927 17:10:18.748598 node/node.go:366] HTTP endpoint opened: http://localhost:8545
I0927 17:10:18.855784 p2p/server.go:556] Listening on [::]:30303
I0927 17:10:18.856396 node/node.go:296] IPC endpoint opened: /root/.ethereum/geth.ipc
I0927 17:10:34.576972 eth/downloader/downloader.go:319] Block synchronisation started
I0927 17:11:28.503158 core/blockchain.go:970] imported 2 block(s) (0 queued 0 ignored) including 6 txs in 52.748059407s. #2335728 [9aaf4d7f / 69575fc3]
I0927 17:12:20.009024 eth/handler.go:290] Peer 375263aab51ff29f [eth/63]: timed out DAO fork-check, dropping
I0927 17:12:57.118781 eth/handler.go:290] Peer c609fafc8330605d [eth/63]: timed out DAO fork-check, dropping
I0927 17:13:14.986661 eth/handler.go:290] Peer f1c805444334f4eb [eth/63]: timed out DAO fork-check, dropping
I0927 17:14:18.230240 eth/handler.go:290] Peer e9dbe77df4867ccb [eth/63]: timed out DAO fork-check, dropping
I0927 17:14:51.141341 eth/handler.go:290] Peer 6491824efd666143 [eth/63]: timed out DAO fork-check, dropping`



`# geth version
Geth
Version: 1.4.13-stable-8f0db697
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go
`

**Comment by darksh1ne** [comment]
The same issue. Syncing is VERY slow. It took 2 hours to update local data from 2287782 to 2287801 block. However, the file system is actively and constantly being used.

**$ geth** 
I0926 20:36:59.267543 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/ethereum/.ethereum/chaindata
I0926 20:37:06.220593 cmd/utils/flags.go:842] ------------------------------------------------------------------------------------------------
I0926 20:37:06.220630 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!
I0926 20:37:06.220645 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0926 20:37:06.220663 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0926 20:37:06.220677 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------
I0926 20:37:06.220908 ethdb/database.go:169] closed db:/home/ethereum/.ethereum/chaindata
I0926 20:37:06.267906 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/ethereum/.ethereum/chaindata
I0926 20:37:06.997884 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /home/ethereum/.ethereum/dapp
I0926 20:37:07.140863 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0926 20:37:07.168265 eth/backend.go:201] Blockchain DB Version: 3
I0926 20:37:07.236076 core/blockchain.go:214] Last header: #2287801 [0a2ff757…] TD=62623083444799844282
I0926 20:37:07.236122 core/blockchain.go:215] Last block: #2287801 [0a2ff757…] TD=62623083444799844282
I0926 20:37:07.236143 core/blockchain.go:216] Fast block: #2287801 [0a2ff757…] TD=62623083444799844282
I0926 20:37:07.285827 p2p/server.go:313] Starting Server
I0926 20:37:07.710101 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-IP1
I0926 20:37:08.296045 p2p/discover/udp.go:217] Listening, enode://f60935efbad70f4ba42bca2553b6264529e842851f7965e453ca8fed0a7799abf815b7dfed12227c284a08be94f7d7c8778a636f5f24eed7278537bbc3568708@109.86.129.159:30303
I0926 20:37:08.298007 p2p/server.go:556] Listening on [::]:30303
I0926 20:37:08.298085 node/node.go:296] IPC endpoint opened: /home/ethereum/.ethereum/geth.ipc
I0926 20:37:08.303104 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-IP1
I0926 20:37:18.297186 eth/downloader/downloader.go:319] Block synchronisation started
I0926 20:37:41.306945 eth/handler.go:290] Peer 24a0e954bad23171 [eth/63]: timed out DAO fork-check, dropping
I0926 20:39:02.258721 eth/handler.go:290] Peer 9cdd171d8ad51c60 [eth/63]: timed out DAO fork-check, dropping
I0926 20:39:34.423292 eth/handler.go:290] Peer 8138d9a2b9e64082 [eth/63]: timed out DAO fork-check, dropping
...
I0926 21:03:09.006397 eth/handler.go:290] Peer 154a60d6d7c92f45 [eth/63]: timed out DAO fork-check, dropping
I0926 22:26:01.046598 eth/handler.go:290] Peer 37087b795cc9518b [eth/63]: timed out DAO fork-check, dropping
...

The time zone for logs above is UTC+3.

**$ geth version**
Geth
Version: 1.4.13-stable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6
OS: linux
GOPATH=
GOROOT=/usr/lib/go

**Comment by Mordong** [comment]
looks all Ok
Win 10 64-bit
wallet 0.8.3
geth 1.4.13

![clipboard01](https://cloud.githubusercontent.com/assets/17006970/18885210/56336704-84f3-11e6-9fcc-de1e94673817.jpg)

**Comment by northscope** [comment]
Updated the latest geth and its still slow to sync on the testnet. Been 4 days downloading latest blocks, never going sync up at this speed.

```
...headerchain.go:297] imported 0 header(s) (576 ignored) in 68.696846ms. #1690173 [5ee814be… / 9b7f0cff…]
I0928 07:08:22.899042 eth/downloader/downloader.go:948] imported 245 state entries in 43.938568167s: processed 20551, pending at least 1694
I0928 07:08:54.474349 eth/downloader/downloader.go:948] imported 214 state entries in 59.583655534s: processed 20765, pending at least 2193
I0928 07:09:29.944359 eth/downloader/downloader.go:948] imported 283 state entries in 1m49.531913476s: processed 21048, pending at least 3330
I0928 07:09:57.455763 eth/downloader/downloader.go:948] imported 384 state entries in 32.755355968s: processed 21432, pending at least 5678
I0928 07:10:01.145354 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
I0928 07:11:00.494734 eth/downloader/downloader.go:648] Peer 4eabb9f637fb497a [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 13.483844878s]: potential rewrite attack: #638037 [b5386ad5…] <= #1598844 limit
```

**Comment by marienuac** [comment]
not syncing up for me etherengine

**Comment by karalabe** [comment]
There was another attack, again targeting a different part of Geth. We'll be releasing a fix for it this morning.

**Comment by jjangg96** [comment]
I'm waiting for new version.

**Comment by etherx-dev** [comment]
which morning will it be released? it's nearly afternoon here in UK.

**Comment by karalabe** [comment]
https://github.com/ethereum/go-ethereum/releases/tag/v1.4.14

**Comment by attila-lendvai** [comment]
i'm running on 1.4.14 and my client is crashing a couple of minutes after startup and prints backtraces. there are still some "Synchronisation failed: block download canceled (requested)" before it crashes.

BTW, why doesn't geth print the version number at startup into the logs?

**Comment by obscuren** [comment]
@attila-lendvai Could you open a new issue with the crash log?

**Comment by fjl** [comment]
@attila-lendvai develop branch prints the version on startup, so it'll start happening in geth 1.5.

**Comment by marienuac** [comment]
1.4.14 ran overnight with no crashing and still synced up. however it is using 2gb ram and a large amount of cpu, is this normal?

**Comment by attila-lendvai** [comment]
cannot right now, but i'll get back to this later.

until then: my machine has 2 GB of ram, so that may be an issue. it used to work fine up until summer. now i wanted to restart it, i updated geth, and it didn't work.

**Comment by fjl** [comment]
It's ok if geth uses 100% CPU during sync. It should not use 100% for extended periods of time after syncing is complete.

Using 2GB memory sounds not right. You can help investigate this by creating a CPU profile as follows:

In the geth console:
```text
> debug.cpuProfile("~/geth.cpu", 300)
# note: this will hang for 300s and then return
>
```

Then, in the shell:

```text
$ go tool pprof --svg /path/to/geth ~/geth.cpu > ~/geth.cpu.svg
```

Then upload the SVG somewhere.

**Comment by attila-lendvai** [comment]
@obscuren i tried a few times, but unfortunately today it just quits without printing anything.

here's the end of my last run:

```
I1001 02:02:14.751678 eth/handler.go:290] Peer 3064b52be7c469ae [eth/63]: timed out DAO fork-check, dropping
I1001 02:02:14.752067 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
I1001 02:04:04.664910 eth/handler.go:290] Peer 8b8844fc89a48f36 [eth/63]: timed out DAO fork-check, dropping
I1001 02:06:56.009035 eth/handler.go:290] Peer 921cf8e4c345fe8d [eth/63]: timed out DAO fork-check, dropping
I1001 02:06:56.009864 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
I1001 02:07:52.923755 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
I1001 02:09:01.959075 eth/handler.go:290] Peer aaba351652a2c6eb [eth/63]: timed out DAO fork-check, dropping
I1001 02:09:01.959919 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
I1001 02:15:14.632116 eth/handler.go:290] Peer 60b0db5ce33bbcf4 [eth/63]: timed out DAO fork-check, dropping
I1001 02:15:47.161314 eth/handler.go:290] Peer 7ced285d49b21e03 [eth/63]: timed out DAO fork-check, dropping
I1001 02:16:38.978352 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
I1001 02:16:49.303242 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
$ 
```

it doesn't sync a single block. my on-disk state is about 2 month lagging behind.

**Comment by fjl** [comment]
Geth v1.4.16 has been released today and should fix the syncing issues.
