### ISSUE TITLE
P2P Version Mismatch: Require protocol 2, received 3

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/go-ethereum#305]
I did a git clone of the latest dev branch, then built cmd/ethereum successfully on Ubuntu 14.01.
After: ethereum -rpc -mine
Everything starts up fine but I get this at the end of the startup, and no connection with the testnet.
[P2P 5.1.83.141:30303] protocol "" error: P2P Version Mismatch: Require protocol 2, received 3

Is this a problem with my build or does the other peer just have protocol 3 while I have 2?

**Comment by tgerring** [comment]
Hello, I was able to reproduce your error as described. I believe the node at 5.1.83.141 is built from C++ and has an updated networking stack, resulting in the version mismatch. go-ethereum should receive this update soon per issue #240. If you want to know when this is merged to develop, you can watch for updates on PR #292

**Comment by SilentCicero** [comment]
I figured as much considering P2P changes on the CPP end, just glad to hear its not my build. Will Go-eth still work with no peers, i.e. a private chain deal? I need it for JS HTTPSync testing.

**Comment by tgerring** [comment]
Yes, you can run a private chain in go-ethereum with no peers by supplying `-seednodes=""`on start. Note, however, that this parameter will change once the updated P2P code is merged.

**Comment by SilentCicero** [comment]
Cheers, I'll use that for now.

**Comment by subtly** [comment]
This may have been premature for the cpp client however the protocol version is incompatible so the bump was warranted; specifically, the Peers and GetPeers packets are no longer supported. @SilentCicero The Go and c++ clients are upgrading network code in parallel -- a bit of a bumpy ride while we work out nuances of updating the network protocol.

**Comment by SilentCicero** [comment]
To be expected, I'll use caution with p2p errors, I'll stick to private chains for now while that end gets worked out.

**Comment by fjl** [comment]
New p2p code has been merged. There might still be issues with cpp-ethereum compatibility.
