### ISSUE TITLE
which version or commit is used for Pectra-devnet-3 ? 

### ISSUE THREAD

**Issue by NathanBSC** [ethereum/go-ethereum#30519]
sorry to post question here, I have check discord, but have no answer.

I find that the [eip-7702 code PR](https://github.com/ethereum/go-ethereum/pull/30078) not merged into master

I checked to this PR and to run the spec test , using version [pectra-devnet-3@v1.5.0](https://github.com/ethereum/execution-spec-tests/releases/tag/pectra-devnet-3%40v1.5.0)
```
go test -run TestExecutionSpecState -v
```
there are many failed cases
<img width="991" alt="Screenshot 2024-09-27 at 16 04 42" src="https://github.com/user-attachments/assets/148f418e-2e13-45ef-9b0b-b4a8b7bc984f">

so if geth supports pectra-devnet-3, which version or commit is used for Pectra-devnet-3 ?

**Comment by s1na** [comment]
https://github.com/lightclient/go-ethereum/tree/prague-devnet-3

**Comment by buddh0** [comment]
> https://github.com/lightclient/go-ethereum/tree/prague-devnet-3

thx!
