### ISSUE TITLE
eth_getLogs fails to get logs

### ISSUE THREAD

**Issue by danalchemy** [ethereum/go-ethereum#30516]
#### System information

Geth version: `v1.14.9-amd64`
CL client & version: `prysm@v5.0.4`
OS & Version: Linux
Commit hash : N/A

#### Expected behaviour
This request should return an empty array
```
curl --location 'localhost:8545' --header 'Content-Type: application/json' --data '{
    "method": "eth_getLogs",
    "params": [
        {
            "blockHash": "0x2acd4a70f418203eb43b3731a4fe96927e1c109a6a8e2c3d8d21d6d9af8f66db"
        }
    ],
    "id": 1,
    "jsonrpc": "2.0"
}'
```

#### Actual behaviour
It returns
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"failed to get logs for block #1022389 (0x2acd4a..8f66db)"}}
```

#### Steps to reproduce the behaviour
Issue this request to geth
```
curl --location 'localhost:8545' --header 'Content-Type: application/json' --data '{
    "method": "eth_getLogs",
    "params": [
        {
            "blockHash": "0x2acd4a70f418203eb43b3731a4fe96927e1c109a6a8e2c3d8d21d6d9af8f66db"
        }
    ],
    "id": 1,
    "jsonrpc": "2.0"
}'
```

#### Backtrace

````
ERROR[09-19|17:53:52.290] Invalid receipt array RLP                hash=2acd4a..8f66db err="rlp: expected input list for []*types.Log, decoding into ([]*rawdb.receiptLogs)[0](rawdb.storedReceiptRLP).Logs"
WARN [09-19|17:53:52.290] Served eth_getLogs                       conn=127.0.0.1:57742 reqid=1 duration="261.545µs" err="failed to get logs for block #1022389 (0x2acd4a..8f66db)"
````

When submitting logs: please submit them as text and not screenshots.

**Comment by case-hub** [comment]
Hello @danalchemy 
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)

**Comment by s1na** [comment]
Similar to #30470.

**Comment by s1na** [comment]
Can you please try eth_getBlockReceipts(hash) and report the result?

**Comment by danalchemy** [comment]
Closing issue in favour of: Similar to https://github.com/ethereum/go-ethereum/issues/30470.
