### ISSUE TITLE
ethereum/client-go:v1.14.10 has not been published to Docker Hub

### ISSUE THREAD

**Issue by Thegaram** [ethereum/go-ethereum#30529]
#### System information

N/A

#### Expected behaviour

Previously all releases were published as multi-arch images using their release version, example: [ethereum/client-go:v1.14.8](https://hub.docker.com/layers/ethereum/client-go/v1.14.8/images/sha256-6984151dd453e64e659eb94cd9860696ce10d7ecb59ee9bd76ccf1093d8e05a5?context=explore).

#### Actual behaviour

There is no `ethereum/client-go:v1.14.10` image published (only [v1.14.10-amd64](https://hub.docker.com/r/ethereum/client-go/tags?name=v1.14.10)).

#### Steps to reproduce the behaviour

N/A

#### Backtrace

N/A

**Comment by holiman** [comment]
This is a known issue, see https://github.com/ethereum/go-ethereum/issues/30469#issuecomment-2382224535

We're working on it, both via getting travisci to get their platforms in order, and alternatively via building in a different way without needing to do it on an arm platform: https://github.com/ethereum/go-ethereum/pull/30528 .
