### ISSUE TITLE
Different filesystems for /var/lib/ethereum/chaindata

### ISSUE THREAD

**Issue by daniel-lucio** [ethereum/go-ethereum#3052]
Is it my imagination or performance using tmpfs is better than using directly the hard disk? My understanding is that with tmpfs, a partial (or all) filesystem is in ram another part in HD, this is quite faster than having all in HD.

Please comment.

**Comment by fjl** [comment]
Yes it would be faster, but the DB would not be persisted between OS restarts.

**Comment by daniel-lucio** [comment]
I know, exporting/importing will be implemented.

**Comment by fjl** [comment]
Are you considering to implement this?

**Comment by daniel-lucio** [comment]
Already done, so far seems it runs stable.

**Comment by daniel-lucio** [comment]
I will review how brtfs performs too.
