### ISSUE TITLE
Private BlockChain with two nodes : How to access smart contract using another node.

### ISSUE THREAD

**Issue by capamaster** [ethereum/go-ethereum#3054]
#### System information

Geth version: `geth version` -- 1.4.13-stable
OS & Version: Windows/Linux/OSX -- Linux 14.04 trusty
Commit hash : (if `develop`)

#### Actual behaviour
To get the return value from deployed smart contract.

#### Steps to reproduce the behaviour
1. Created Miner node and simple node using geth in two different terminal. Also private network is  created and simple ether transfer is done.
2. From miner node : 
    contract of "contract test { function multiply(uint a) returns(uint d) { return a * 7; } }" created,         deployed on private blockchain. Received receipt and checked the contract address.
3. How to access the contract from simple node ?

#### Backtrace

````
[backtrace]
````

**Comment by capamaster** [comment]
Hi ,
Ok...Got it.. 
Used ABI and contract address and send through eth.contract(ABI).at(contract address)

**Comment by SurajKohli** [comment]
Within a private network is there a way to access the contract deployed on **node1** from a different  **node2** using the contract address ?
Why do we need to explicitly mention ABI again?

Any links to explain private ethereum network in detail would also be helpful!

Thanks in advance for any help!
