### ISSUE TITLE
Transaction processing in mempool

### ISSUE THREAD

**Issue by junghyun0783** [ethereum/go-ethereum#30556]
I found one problem while conducting a transfer test with sepolia.

After the transaction entered the mempool, the transaction was not registered in the block because the fee was low or the block synchronization did not follow.

I have a question here.
In this case, if I keep the nonce value the same but increase the fee value and retransmit it... will the existing transaction not pay the fee value?
The new transaction is replaced and registered in the block, and the fee value of the existing transaction does not have to be paid?

I would like the experts' answers.

**Comment by karalabe** [comment]
Only one transaction per nonce is valid. If you submitted multiple ones differently priced, whatever ends up in the block, the rest immediately become impossible to add.

**Comment by junghyun0783** [comment]
@karalabe 
Yes, I know.
But I'm talking about when you want to change a transaction that's in the mempool.
If you change the fee value of a transaction that's in the mempool, you don't have to pay the fee value of the existing transaction, right?

**Comment by holiman** [comment]
The answer still holds: Only one transaction per nonce is valid.

So if one of them is accepted, the other is not. It is thus impossible to pay for two transactions with the same nonce. 

> If you change the fee value of a transaction that's in the mempool, you don't have to pay the fee value of the existing transaction, right?

Yes

**Comment by junghyun0783** [comment]
@holiman 
thank you very much!!!!!
