### ISSUE TITLE
Setting mempool expiration period on my node

### ISSUE THREAD

**Issue by junghyun0783** [ethereum/go-ethereum#30566]
Is it possible to set the transaction expiration period of the mempool on the node I am operating?
It is said that it is possible to set it with Chat GPT.
**"ex) geth --txpool.lifetime 24h"**
If I set the transaction expiration period like this,
Will the pending transaction be removed from the mempool after 24 hours?

I will wait for the experts' answers.
Thank you.

**Comment by batu3H** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by MariusVanDerWijden** [comment]
Yes, you can set `--txpool.lifetime 24h` (the default is 3 hours), this will affect all queued transactions that are non-local. It will not affect transactions that you send yourself and it will not affect transactions that are technically executable. Only nonce-gapped transactions are affected by it
