### ISSUE TITLE
High CPU usage at start (1.4.14)

### ISSUE THREAD

**Issue by ntpeters** [ethereum/go-ethereum#3057]
#### System information

Geth version: `1.4.14`
OS & Version: macOS Sierra
Commit hash : geth-1.4.14-prerelease-f88bca7-darwin-10.6-amd64
Hardware:
-     Macbook Pro (2015)
-     Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
-     16GB RAM

#### Expected behaviour
Typically geth doesn't use an exessive amount CPU for me, and never sits at 100% usage for a length of time. Infrequent usage spikes are the most I usually see.

#### Actual behaviour
I was previously running `1.4.13` and when I executed `1.4.14` I was only about 100 blocks behind. My CPU usage went to 100% until geth caught up to the current block, then went back to normal

It also went up to a little over 3.5GB memory usage during this time then settled back down, and is currently at 1.6GB. I can't comment on if this was too out of the norm for me, as I don't remember memory usage on `1.4.13`. (I have 16GB memory, so out of the norm memory utilization doesn't alert me like CPU utilization does)

#### Steps to reproduce the behaviour
Ran with: `--cache 2048 --targetgaslimit 1500000 --gasprice 20000000000 console`

#### Backtrace
N/A

**Comment by karalabe** [comment]
I think that is understandable. Processing blocks is usually computationally intensive, so as long as it settles down when sync finishes I think it's natural. As for the memory usage, given that you allowed 2GB cache, a 3.5GB usage is normal as Go's garbage collector runs when total memory reaches 2x the previous used memory (this is planned to be addressed in Go 1.8).

**Comment by ntpeters** [comment]
Okay, that makes sense. I've also been running it on and off all day, and let it get a bit behind before relaunching again. Every time it settled back down to normal, so I'll close this.
