### ISSUE TITLE
[RPC-HTTP] Error: Method not implemented eth_defaultBlock

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/go-ethereum#306]
No biggie but I got this error after running cmd/mist/assets/examples/info.html in my ethereum -rpc CLI. I suppose rpc eth_defaultBlock is not implemented yet? Also, the ethereum.js and bignum.min.js needs to be updated in cmd/mist/ext as the older one will throw contract object 'undefined function' JS errors.

**Comment by tgerring** [comment]
Currently, eth_defaultBlock is not implemented. The full list of messages is at https://github.com/ethereum/wiki/wiki/JSON-RPC and but go-ethereum implementation only handles the following: https://github.com/ethereum/go-ethereum/blob/develop/rpc/packages.go#L345-L479

To implement this call properly, the `xeth` package will probably need to be extended to include all state operations and have them wrapped in the `rpc` package.
