### ISSUE TITLE
Third-party contribution request #devnet #testnet #private network

### ISSUE THREAD

**Issue by ccmlm** [ethereum/go-ethereum#30605]
> Third-party contribution request #devnet #testnet #private network

**Hello everyone,** 

**I wrote a very powerful ETH devnet/testnet management system: [https://github.com/PolyhedraZK/nbnet](https://github.com/PolyhedraZK/nbnet).** 

Compared with the currently well-known kurtosis-based approach, my solution has many advantages.

- Kurtosis is a nice and general platform, but not designed specifically for ETH
- Kurtosis currently has many problems, such as the widely criticized problem of imperfect restart and data retention issues
- Kurtosis uses a self-tailored starlark language instead of a general language, which is not conducive to users understanding the internal logic
- Kurtosis's ETH devnet solution provides very simple functions. If it is used to research the ETH architecture or source code in depth in practice , developers still need to invest a lot of extra time
- Kurtosis force users to use docker or k8s, which is a disaster for people who are code-clean.
- ...

Many of the problems mentioned or not mentioned above have been well solved in my project. I believe that this project will have a positive impact on the technical iteration and testing of the ETH community.

I hope you will take some time to check my project.

**If you think it is valuable, please consider including my project information in your documentation(the devnet or private network section, etc.).**

I will continue to maintain this project for a long time.

Thank you very much

**Comment by MariusVanDerWijden** [comment]
This is the wrong place to advertise your project, try maybe the ethereum stack exchange or twitter or farcaster or the R&D Discord
