### ISSUE TITLE
Intermittent missing 'to' field in eth_getTransactionByHash response for recent contract creations on Optimism Mainnet

### ISSUE THREAD

**Issue by cshintov** [ethereum/go-ethereum#30610]
#### Expected behaviour

When querying recent contract creation transactions via `eth_getTransactionByHash`, the `to` field should always be present in the response, with a `null` value for contract creations.

#### Actual behaviour

The `to` field is sometimes missing from the response for recent contract creation transactions. The field appears correctly (as `null`) when querying again after a few minutes.

#### Steps to reproduce the behaviour

1. Observe a contract creation transaction on Optimism Mainnet.
2. Immediately query the transaction using `eth_getTransactionByHash`.
3. Note that the `to` field is missing from the response.
4. Wait for a few minutes (approximately 5-10 minutes).
5. Query the same transaction again using `eth_getTransactionByHash`.
6. Observe that the `to` field is now present with a `null` value.

Example:
- Affected blocks range: 126647700 to 126647748
- Example transaction hash: 0x43c713b640309fd7c28c61f5ad3f4e0c34404519b5171670e646b7a5c22b620a

#### System information

      op-geth: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101408.0
      node: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.9.1

**Comment by jwasinger** [comment]
Please open this on the [op-geth](https://github.com/ethereum-optimism/op-geth) repo.  This repo is not the proper place for optimism issues.
