### ISSUE TITLE
Support fixed sized arrays for primitive and custom types to fully comply with EIP 712 specification

### ISSUE THREAD

**Issue by naveen-imtb** [ethereum/go-ethereum#30619]
# Rationale

The [EIP-712](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md) specification supports fixed size and dynamic sized arrays.

From the spec,

> The reference types are arrays and structs. Arrays are either fixed size or dynamic and denoted by Type[n] or Type[] respectively. Structs are references to other structs by their name. The standard supports recursive struct types.

Unfortunately go-ethereum in its current form doesn't fully comply with the [EIP-712](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md) standard because the signer module currently doesn't support encoding fixed size array datatypes.

# Implementation
Are you willing to implement this feature? Yes

**Comment by batu3H** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
