### ISSUE TITLE
Fields with type `common.Address` is not checksummed in json rpc request

### ISSUE THREAD

**Issue by mmsqe** [ethereum/go-ethereum#30618]
#### System information

Geth version: `geth 1.14.12-unstable`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: OSX
Commit hash : https://github.com/ethereum/go-ethereum/commit/afea3bd49c85a174de52ff42c1c98e8ee9413023

#### Expected behaviour

fields with type `common.Address` should be checksummed after JSON marshalling

#### Actual behaviour

fields with type `common.Address` are in lowercase

#### Steps to reproduce the behaviour

call `eth_getBlockByNumber` with height `0x14044b3`

https://github.com/ethereum/go-ethereum/blob/afea3bd49c85a174de52ff42c1c98e8ee9413023/common/types.go#L328 
Can we use `a.checksumHex()` here?

When submitting logs: please submit them as text and not screenshots.

**Comment by lightclient** [comment]
Consumers of the RPC should decide to show checksummed addresses to users. I don't really see a purpose for this and would prefer to not implement.
