### ISSUE TITLE
How to generate Globalregistrar on the private blockchain

### ISSUE THREAD

**Issue by capamaster** [ethereum/go-ethereum#3061]
#### System information

Geth version: `geth version` 
1.4.13-stable

OS & Version: Windows/Linux/OSX
Linux Ubuntu Trusty

Commit hash : (if `develop`)

 #### Steps to reproduce the behaviour

globalRegistrarAddr = admin.setGlobalRegistrar("", primary);
hashRegAddr = admin.setHashReg("", primary);
urlHintAddr = admin.setUrlHint("", primary);

--- On Mine whether this globalRegistrarAddr will get generated or need to set some address in above commands ?

registrar = GlobalRegistrar.at(globalRegistrarAddr);

>ReferenceError: 'GlobalRegistrar' is not defined

Kindly help.

Reference : 
https://ethereum.gitbooks.io/frontier-guide/content/registrar_services.html

#### Backtrace

````
[backtrace]
````

**Comment by bas-vk** [comment]
This registrar is deprecated and didn't got any attention lately so it probably won't work. It will be removed in the future. You might want to take a look at https://github.com/ethereum/EIPs/issues/137.
