### ISSUE TITLE
If I restart Geth?

### ISSUE THREAD

**Issue by daniel-lucio** [ethereum/go-ethereum#3063]
Big question.......... lets say I am doing solo mining. And Usually I delay 8 days per block. 
If at day number 4 I restart geth, all the work done is lost and i start from day 0 again, or it is saved somewhere in the ~/.ethereum directory?

**Comment by fjl** [comment]
> And Usually I delay 8 days per block

Can you explain what you mean by that?

**Comment by daniel-lucio** [comment]
It means my rigb does a block each 8 days

**Comment by fjl** [comment]
The miner restarts the search every 12s when a new block is released. So there should be no danger in restarting geth if you need to.

**Comment by daniel-lucio** [comment]
Thank you!
