### ISSUE TITLE
Custom rpc.Client in ethclient.Client

### ISSUE THREAD

**Issue by LucasALLOIN** [ethereum/go-ethereum#30630]
# Rationale

This proposal aims to allow developers to use a custom `rpc.Client` without the need to re-implement all the methods of `ethclient.Client`. Recently, I required this functionality to automatically intercept all `rpc.CallContext` calls and add custom features, without having to replicate the same implementation across all functions called by the client.

# Implementation

To achieve this, I plan to create an interface that will be used within the `ethclient.Client` struct. I will handle the implementation myself.

If you have any further requests or suggestions, please feel free to reach out.

**Comment by lightclient** [comment]
repost from #30631 https://github.com/ethereum/go-ethereum/pull/30631#issuecomment-2423991409

> you should use DialHTTPWithClient and pass a custom http.Client with the logging you desire.

**Comment by batu3H** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
