### ISSUE TITLE
Typo in release note for Sentry Omega (v1.10.23)

### ISSUE THREAD

**Issue by SatpalSandhu61** [ethereum/go-ethereum#30664]
There is a typo in the release note for [Sentry Omega (v1.10.23)](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.23).
Under the `Merge EIPs` section, it shows the incorrect EIP number for EIP-4399 (although the hyperlink is correct), i.e.:

[EIP-4339](https://eips.ethereum.org/EIPS/eip-4399): Supplant DIFFICULTY opcode with PREVRANDAO

Instead of:

[EIP-4399](https://eips.ethereum.org/EIPS/eip-4399): Supplant DIFFICULTY opcode with PREVRANDAO

It's only a minor thing, but it means you can't search the release notes to check when the EIP number was released.

Thanks.

**Comment by holiman** [comment]
Thanks, fixed!
