### ISSUE TITLE
Geth. Problem with sync

### ISSUE THREAD

**Issue by aspirecoin** [ethereum/go-ethereum#3069]
#### System information

Geth version: `geth version`
OS & Version: Windows and Linux
Commit hash : (if `develop`)

have problem with sync..
Geth (1.4.13). Worked fine until 2364270 unit. Then began to long to sync new units and lose peers. Now is already 3 hours 2364273\2365470 and can not resume until the end

on linux node too.
Can you help me?
I try resync but its notworking(

**Comment by aspirecoin** [comment]
I1002 14:48:22.396831 eth/handler.go:290] Peer de471bccee3d0422 [eth/63]: timed out DAO fork-check, dropping
I1002 14:48:31.117058 eth/handler.go:290] Peer 6a83da8312f3c579 [eth/63]: timed out DAO fork-check, dropping
I1002 14:48:41.369932 eth/handler.go:290] Peer 1118980bf48b0a36 [eth/63]: timed out DAO fork-check, dropping
I1002 14:50:15.222137 eth/handler.go:290] Peer de471bccee3d0422 [eth/63]: timed out DAO fork-check, dropping
I1002 14:51:34.966670 eth/handler.go:290] Peer de471bccee3d0422 [eth/63]: timed out DAO fork-check, dropping
I1002 14:51:35.482518 eth/handler.go:290] Peer 1118980bf48b0a36 [eth/63]: timed out DAO fork-check, dropping
I1002 14:51:56.099509 eth/handler.go:290] Peer 5c2467334961bad8 [eth/63]: timed out DAO fork-check, dropping
I1002 14:51:56.236455 eth/handler.go:290] Peer 1b7b67b06425da03 [eth/63]: timed out DAO fork-check, dropping
I1002 14:53:27.155369 eth/handler.go:290] Peer 1118980bf48b0a36 [eth/63]: timed out DAO fork-check, dropping
I1002 14:53:59.316386 eth/handler.go:290] Peer 1118980bf48b0a36 [eth/63]: timed out DAO fork-check, dropping
I1002 14:54:21.705913 eth/handler.go:290] Peer 335bc9e2955d7e3d [eth/63]: timed out DAO fork-check, dropping
I1002 14:55:34.972847 eth/handler.go:290] Peer 1118980bf48b0a36 [eth/63]: timed out DAO fork-check, dropping

**Comment by Mordong** [comment]
same problem with 90% CPU used

**Comment by aspirecoin** [comment]
and how fix?

**Comment by fjl** [comment]
Please try geth 1.4.14, which fixes some of the perf issues uncovered by the recent DoS attacks.

**Comment by aspirecoin** [comment]
i try, dont working too

**Comment by aspirecoin** [comment]
geth bad download new blocks.

**Comment by ivands** [comment]
Still same issue for 1.5.0+1069SNAPSHOT20160919190719trusty-0ubuntu1

**Comment by karalabe** [comment]
Please update, it's seriously outdated (compared to the current DoS attacks and deployed fixes) :)

**Comment by Mordong** [comment]
any links to download fixes?

**Comment by karalabe** [comment]
Ubuntu and osx should be installable via PPAs/homebrew (they are also available from the release page https://github.com/ethereum/go-ethereum/releases/tag/v1.4.15). For other platforms, we have the cross builds at https://www.reddit.com/r/ethereum/comments/55muig/geth_1415_come_at_me_bro_dos_fixes/d8bwz0h

**Comment by marienuac** [comment]
windows ???

**Comment by porobov** [comment]
Got the same issue for Geth v. 1.4.15 on Ubuntu 14.04. Keep recieving "timed out DAO fork check.." Another issue is that Geth needs about 15-20 minutes to close after Ctrl-C.

**Comment by lodos2005** [comment]
# geth version
Geth
Version: 1.4.15-stable-cb7d7d3d

> I1004 00:21:44.421841 eth/downloader/downloader.go:319] Block synchronisation started
I1004 00:21:59.605667 eth/handler.go:290] Peer a979fb575495b8d6 [eth/63]: timed out DAO fork-check, dropping
I1004 00:22:00.517672 eth/handler.go:290] Peer de471bccee3d0422 [eth/63]: timed out DAO fork-check, dropping
I1004 00:22:04.057250 core/blockchain.go:975] imported 5 block(s) (0 queued 0 ignored) including 13 txs in 4.336717856s. #2371784 [68daa7c1 / 1d4f5172]
I1004 00:22:32.113528 eth/handler.go:290] Peer a979fb575495b8d6 [eth/63]: timed out DAO fork-check, dropping
I1004 00:22:46.315516 eth/handler.go:290] Peer 537138248fb17084 [eth/63]: timed out DAO fork-check, dropping
I1004 00:23:00.789332 eth/handler.go:290] Peer 65990d8e0a1b4d63 [eth/63]: timed out DAO fork-check, dropping
I1004 00:24:15.697072 eth/handler.go:290] Peer 65990d8e0a1b4d63 [eth/63]: timed out DAO fork-check, dropping
I1004 00:24:46.369654 eth/handler.go:290] Peer 38a7cd6d59c31d49 [eth/63]: timed out DAO fork-check, dropping

same issue like @porobov

sync too slow, just 1-10 blocks sync with start every restart geth, but after a while get "timed out DAO fork check, dropping"

**Comment by marienuac** [comment]
`timed out DAO fork-check, dropping` is normal ur ganna get alot of that. there are hundreds if not thousands of nodes stuck in limbo cause of the attacks.

**Comment by porobov** [comment]
@marienuac yes about a week ago those nodes made sync process very slow, but nevertheless possible. Now there is even no chance to catch up with the network. As I mentioned above it is just 20 blocks in 2 hours.

**Comment by ivands** [comment]
After installing 1.5.0+1082SNAPSHOT20161003084035trusty-0ubuntu1 we can't seem to get past blocknumber 2376500.
The node restarts automatically every minute after receiving the following error.
"fatal error: runtime: out of memory"

Server has 4G's of memory tho.

**Comment by karalabe** [comment]
New attack, we're prepping a fix

**Comment by xPakrikx** [comment]
ok waiting for fix :|

**Comment by fjl** [comment]
Geth v1.4.16 has been released today and should fix the syncing issues. The fixes are also on the develop branch so if you are using that you can just `git pull` and rebuild.
