### ISSUE TITLE
ethclient evm_call return the revert result

### ISSUE THREAD

**Issue by boying52** [ethereum/go-ethereum#30697]
I'd like to try test of Evm, I got the problem about this:
<img width="1279" alt="image" src="https://github.com/user-attachments/assets/569bf7f7-ef83-4b9f-9cbb-7f4dabd165f0">
I set the storage at the 8th solt, uint112 ,uint112,uinit32=8,9,10,and their hex is 0x000000000000000000000000000800000000000000000000000000090000000a，but I got the revert Result after I run the evmcall
<img width="1494" alt="image" src="https://github.com/user-attachments/assets/3ee42aab-82f3-4753-884b-a238775b3cd5">
The result expect :0x000000000000000000000000000800000000000000000000000000090000000a
and I took the deploycode of uniswapv2pair of mainnet for running "getReserves()", I also check the code:
<img width="1118" alt="image" src="https://github.com/user-attachments/assets/b3a3921e-a9b9-40a6-affb-bb0b4a6a0152">
the Uniswap2Pair address is  0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc in https://etherscan.io/

**Comment by boying52** [comment]
yes, i  read revm yesterday！so，I started to learn this stuff。I mean why the result didn't come out sequence

**Comment by fjl** [comment]
The result is the return data of the contract. In case of revert, the return data is the revert reason.
