### ISSUE TITLE
Handling Off-Turn Blocks due to Network Latency

### ISSUE THREAD

**Issue by mukul3097** [ethereum/go-ethereum#30700]
Summary:
On October 2nd, we encountered an issue where our Geth-based BSC node provided an incorrect hash for a particular block number due to an off-turn block arriving earlier than the in-turn block. After troubleshooting, it was confirmed that the off-turn block was pruned after a few days (~3 days for Geth/Erigon-2, ~1 hour for Erigon-3). However, during this window, the off-turn block was accessible, leading to discrepancies in the responses from different nodes that either imported or did not import the off-turn block.

Details:
• Block Hash in Question: 0x12238a082141e92706eceb937e3f050d815fecbaad4d592bde591a071a769615
• Block Number: 42712474
• Chain Segment Details:
   • In-turn Block: 0xb9c31696c7da15e4e6d5afafdf545d8031487cf5bf940ea73360ba40c2e14adf
   •.   Off-turn Block: 0x12238a082141e92706eceb937e3f050d815fecbaad4d592bde591a071a769615

This off-turn block was broadcasted and imported but pruned later. In nodes that imported this block, querying eth_getBlockByHash during this time window returned the off-turn block details instead of the expected null result.

Request:
We would like to request guidance or a more efficient method to handle such off-turn blocks to avoid discrepancies in the block data. Specifically, should there be:
1. A mechanism to prevent off-turn blocks from being imported in the first place when the in-turn block is available?
2. An alert system or validation to quickly identify and reject such blocks to avoid them being served as valid data to RPC requests?

We understand that off-turn blocks may result from network latencies, but these discrepancies can cause confusion and inconsistency in block data across nodes.

Thank you for your attention to this matter. We look forward to your insights.

**Comment by jwasinger** [comment]
Issues tracked on this repo are for Geth as it pertains to the Ethereum network, not forks for alternative chains.  Please raise the issue on the Geth bsc fork repo.
