### ISSUE TITLE
How does the node respond and recovers to internet outages ?

### ISSUE THREAD

**Issue by journeytosilius** [ethereum/go-ethereum#30721]
In the case the internet goes off, and then comes back, does the node recovers and gets the blocks missed block by block sequentially ?
Asking what is the procedure since I am listening to it via RPC and need to know how to manage a situation like this. 

I have an app that listens to new headers on the other side, will the node recover and do block by block sequentially and the RPC listener will receive these blocks as well on a sequential manner, or do I need to prepare a recovery method ?

Thanks

**Comment by MariusVanDerWijden** [comment]
Yes once a node is synced, it will process the blocks sequentially 
Please refer to the ethereum stack exchange for similar questions in the future: ethereum.stackexchange.com
