### ISSUE TITLE
When supplying `--bench` and `--debug` flags to `evm` tool, only output trace for a single run instead of every benchmark iteration

### ISSUE THREAD

**Issue by jwasinger** [ethereum/go-ethereum#30789]

**Comment by holiman** [comment]
I don't know... I mean, give it crap combo of commands, you get what you deserve. Might be that the user (who in this case is not a general user, most likely one of us) wants to benchmark the json marshalling. Then it would be annoying to be second-guessed by the code, disabling your tracers.

**Comment by jwasinger** [comment]
Okay, let's just leave it as-is then.
