### ISSUE TITLE
CORS Max-Age is not set resulting in 2 requests for each command on Firefox

### ISSUE THREAD

**Issue by ethernomad** [ethereum/go-ethereum#3079]
Currently every RPC command is 2 requests. First the OPTIONS pre-flight and then the actual request. By setting CORS Max-Age to 10 minutes the number of requests can be cut in half. For high latency connections to the node, this has significant performance improvements.

http://stackoverflow.com/questions/17432982/should-i-expect-options-preflight-with-all-cors-requests

For example to load Etherparty block explorer with a remote node takes 1 min:

![screenshot from 2016-10-03 19-01-36](https://cloud.githubusercontent.com/assets/161566/19036726/e0f2ee76-899b-11e6-9591-e920572b43ac.png)

**Comment by ethernomad** [comment]
With CORS Max-Age to 10 minutes it is twice as fast:

![screenshot from 2016-10-03 19-16-59](https://cloud.githubusercontent.com/assets/161566/19037015/136dc798-899e-11e6-9ff1-4edcc1045876.png)

**Comment by bas-vk** [comment]
I think your (closed) PR is fine, only 1 hour was a bit too long. I would opt for 10 minutes.

Btw, which browser did you use? Chrome caches by default CORS settings for 5 seconds and I expect other browsers to do something similar.

**Comment by ethernomad** [comment]
This was Firefox. I'll try Chrome.

**Comment by ethernomad** [comment]
Yeah it doesn't make any difference on Chrome.

Before:
![screenshot from 2016-10-03 20-14-57](https://cloud.githubusercontent.com/assets/161566/19038540/29dad068-89a6-11e6-8706-091d48a754e8.png)

After:
![screenshot from 2016-10-03 20-08-25](https://cloud.githubusercontent.com/assets/161566/19038551/34d8adb4-89a6-11e6-850e-68a733c93cb8.png)
