### ISSUE TITLE
1.4.15 for windows?

### ISSUE THREAD

**Issue by CaptainSkywave** [ethereum/go-ethereum#3080]
..will you also make a version of 1.4.15 for windows?
..or is that not necessary?

**Comment by karalabe** [comment]
Please grab one from https://www.reddit.com/r/ethereum/comments/55muig/geth_1415_come_at_me_bro_dos_fixes/d8bwz0h

**Comment by CaptainSkywave** [comment]
Thank you :)

**Comment by karalabe** [comment]
:) :+1:
