### ISSUE TITLE
How to get the storage of specified address and slot when call debug_traceBlockByNumber with custom js tracer?

### ISSUE THREAD

**Issue by rekyyang** [ethereum/go-ethereum#30819]
For some reason, I want to get the storage of specified address and slot when I trace blocks with custom js tracer(in step function). I tried to pass the string like '0x0000000.....0000' as the input params of db.getState, but the node return the error msg as invalid buffer type at step, so I want to know how to build the js-tracer to record and return the storage of specified address and slot.

this is my failed attemp:
```
curl --location 'http://localhost:8545' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "debug_traceBlockByNumber",
    "params": [
        "latest",
        {
            "tracer": "{retVal:[],step:function(log,db){this.retVal.push(db.getState(0x6f82d895e223dde65da28a8bbd14f3ef79cbf3b8,0x00000000000000000000000000000000000000000000000000000000000000cd))},fault:function(log,db){this.retVal.push('\''FAULT: '\''+JSON.stringify(log))},result:function(ctx,db){return this.retVal}}"
        }
    ]
}'
```

the error msg is:
```
{.........error":"invalid buffer type at step (\u003ceval\u003e:1:51(10))    in server-side tracer function 'step'"......}
```

the chain is Sepolia

**Comment by s1na** [comment]
You're missing quotation marks around the hex strings. Try if that fixes it.

**Comment by MariusVanDerWijden** [comment]
I'm closing this for now, please reopen @rekyyang if @s1na's suggestion is not working
