### ISSUE TITLE
Is it possible to set up a fully functional private GoEthereum network with a Proof of Stake consensus mechanism without using Kurtosis or other wrappers?

### ISSUE THREAD

**Issue by ThomasAqu1nas** [ethereum/go-ethereum#30817]
I need to test and compare the performance, load capacity, and speed of block validation/mining in a geth network using different consensus mechanisms: PoW, PoS, and PoA.

Setting up a PoW Ethash or PoA Clique network is straightforward based on the documentation.
However, when it comes to setting up a private geth network with a PoS consensus mechanism, the documentation suggests using the Kurtosis wrapper, which relies on code from the repository: https://github.com/ethpandaops/ethereum-package, rather than directly using the geth source code.

I would like to know if it's possible to configure a private network directly with a PoS consensus mechanism and generate a genesis config for this network.

**Comment by weiihann** [comment]
https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet
this might help

**Comment by ThomasAqu1nas** [comment]
> https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet
> 
> this might help

In Devnet, the database is destroyed after the node is disconnected

**Comment by ThomasAqu1nas** [comment]
> It's not possible to set up a proof-of-stake network with geth only. You can use `geth --dev` to set up a quick dev chain. If you specify the datadir (`--datadir`) the database will not be destroyed once the node is shut down.
> 
> You can always set up a network without kurtosis, but its more complicated, since you need to set up a lot of stuff manually

How about this guide that @weihan sent me. It seems to be in this section: https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet#manual-setup-built-from-source
the procedure for deploying the pos network is specified.

**Comment by MariusVanDerWijden** [comment]
I hope that the Tutorial you found will help you run your benchmarks. I will close this for now, thanks!
