### ISSUE TITLE
v1.4.15 has still problems block hanged on 23766xx 

### ISSUE THREAD

**Issue by trustfarm-dev** [ethereum/go-ethereum#3083]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

v1.4.15 - Ubuntu 14.04
#### Expected behaviour
4 geth mining nodes.
Blocksync hanged around 2376717 ,  2376501 , 2376483 , 2376681 
#### Actual behaviour
on this time etherscan.io latest blockheight : 2377150

#### Backtrace

````
[backtrace]
````

**Comment by luclu** [comment]
Related: https://github.com/ethereum/mist/issues/1254

> On block 2376500 geth (1.4.15) taking any available RAM memory and crashing

**Comment by jjangg96** [comment]
Is it kind of another DDOS?

**Comment by trustfarm-dev** [comment]
@jjangg96  yes. It may be.

**Comment by Gustav-Simonsson** [comment]
https://www.reddit.com/r/ethereum/comments/55s085/geth_nodes_under_attack_again_we_are_actively/

**Comment by etherx-dev** [comment]
"come at me bro" lol, maybe get more creative with naming releases. sick of this shit.

**Comment by marienuac** [comment]
any fix yet or ???

**Comment by expsam** [comment]
https://twitter.com/jeffehh/status/783432655626964992

**Comment by vivek0** [comment]
Confirmed seems stuck at #2376500

```
I1005 07:47:22.129315 core/blockchain.go:214] Last header: #2376500 [6424ea5c…] TD=69418447161679106568
I1005 07:47:22.129348 core/blockchain.go:215] Last block: #2376500 [6424ea5c…] TD=69418447161679106568
I1005 07:47:22.129364 core/blockchain.go:216] Fast block: #2376500 [6424ea5c…] TD=69418447161679106568

```

**Comment by fjl** [comment]
Geth v1.4.16 has been released today and should fix the syncing issues.
