### ISSUE TITLE
eth.getBlock() returns receiptRoot instead of receiptsRoot

### ISSUE THREAD

**Issue by gituser** [ethereum/go-ethereum#3084]
#### System information

Geth version: `geth 1.4.15`
OS & Version: Linux
Commit hash : (if `develop`)
#### Expected behaviour

According to spec here - https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash geth should return on eth.getBlock() call `receiptsRoot` instead of `receiptRoot`.
#### Actual behaviour

eth.getBlock returns `receiptRoot`, a typo i guess?
#### Steps to reproduce the behaviour

run eth.getBlock(2323232) on geth's console or any other block.

Related issue from parity: https://github.com/ethcore/parity/issues/2401

**Comment by bas-vk** [comment]
Thx for reporting this, fixed in the referenced PR.

**Comment by fjl** [comment]
Fix released in 1.5.0.
