### ISSUE TITLE
Is it possible to enable saving more state ?

### ISSUE THREAD

**Issue by journeytosilius** [ethereum/go-ethereum#30875]
Wanted to know if it can be configured to save the last, say 10K blocks of state instead of 128 blocks ?

**Comment by rjl493456442** [comment]
What’s your use case for retaining the last 10K states? If it’s primarily for handling RPC requests, an archive node would be a better option.

We already support hash-mode archive nodes. You can enable it after the initial sync is complete, allowing Geth to persist all states into the database.

We’re also developing a path-mode archive node, which is much more lightweight than the current implementation. Once released, the storage requirements for running an archive node will be significantly reduced.
