### ISSUE TITLE
v1.4.15 unable to continue syncing due to "panic: runtime error: index out of range"

### ISSUE THREAD

**Issue by attila-lendvai** [ethereum/go-ethereum#3087]
Geth version: 
```
Geth
Version: 1.4.15-stable-cb7d7d3d
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.5.1
OS: linux

GOPATH=
GOROOT=/usr/lib/go
```
OS & Version: 
```
Linux foo 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

#### Actual behaviour
syncing is stuck and eventually crashes, reproducibly.

#### Backtrace

see the attachment below. please note that it's a script that restarts geth automatically, so it's the log of multiple invocations.

[geth.log.txt](https://github.com/ethereum/go-ethereum/files/510647/geth.log.txt)

**Comment by fjl** [comment]
This is fixed in Geth 1.4.16 (and on the develop branch). Thank you!
