### ISSUE TITLE
About poa Private chain v1.10

### ISSUE THREAD

**Issue by ljb943** [ethereum/go-ethereum#30883]
Help My private chain stop and start again as shown below

INFO [12-09|22:21:43.725] Initialising Ethereum protocol           network=1 dbversion=8
INFO [12-09|22:21:43.725] Loaded most recent local header          number=1,840,288 hash=0004e5..f39c9d td=3,682,353 age=10h29m58s
INFO [12-09|22:21:43.725] Loaded most recent local full block      number=1,840,288 hash=0004e5..f39c9d td=3,682,353 age=10h29m58s
INFO [12-09|22:21:43.725] Loaded most recent local fast block      number=1,840,288 hash=0004e5..f39c9d td=3,682,353 age=10h29m58s
INFO [12-09|22:21:43.726] Loaded last fast-sync pivot marker       number=1,236,268
WARN [12-09|22:21:43.726] Head state missing, repairing            number=1,840,288 hash=0004e5..f39c9d snaproot=d8bbfd..0d1ac4

**Comment by ljb943** [comment]
I don't know why he wants to roll back to 1236268, which will cause me to lose a lot of data

**Comment by rjl493456442** [comment]
Do you have any unclean shutdown? Geth will lose the in-memory states if unclean shutdown occurs, an additional state recovery procedure will be scheduled if so in the next startup.

**Comment by ljb943** [comment]
> Do you have any unclean shutdown? Geth will lose the in-memory states if unclean shutdown occurs, an additional state recovery procedure will be scheduled if so in the next startup.

Yes, my server suddenly stopped, and when I found it and started up again, the above problem occurred. Is there any way to solve it?

**Comment by MariusVanDerWijden** [comment]
Not really, it rolls back the chain and goes from there. If there is another node in the network, it will sync back up again.
Not much we can do about it, sorry!
