### ISSUE TITLE
Why does VerifyRangeProof reject empty range proofs when entries exist after the range?

### ISSUE THREAD

**Issue by weiihann** [ethereum/go-ethereum#30890]
I'm trying to understand the design decision behind `VerifyRangeProof`'s handling of empty ranges.

Currently, when verifying a range proof with empty keys/values, `VerifyRangeProof` returns an error if there are any entries after the range.

For example, given a trie with keys from `0-4` and `16-1000`. The range `5-15` is empty, and `VerifyRangeProof` will return an error. Here's the test code snippet that I've written for this case:

<details>
<summary>Code Snippet</summary>

```
func gappedTrie(n int) (*Trie, map[string]*kv) {
	trie := NewEmpty(newTestDatabase(rawdb.NewMemoryDatabase(), rawdb.HashScheme))
	vals := make(map[string]*kv)
	max := uint64(0xffffffffffffffff)
	for i := uint64(0); i < uint64(n); i++ {
		value := make([]byte, 32)
		key := make([]byte, 32)
		binary.LittleEndian.PutUint64(key, i)
		binary.LittleEndian.PutUint64(value, i-max)
		elem := &kv{key, value, false}
		if i >= 5 && i <= 15 {
			vals[string(elem.k)] = elem
			continue
		}

		// value := &kv{common.LeftPadBytes([]byte{i}, 32), []byte{i}, false}
		trie.MustUpdate(elem.k, elem.v)
	}
	return trie, vals
}

func TestEmptyRangeProofMiddle(t *testing.T) {
	trie, vals := gappedTrie(1000)
	var entries []*kv
	for _, kv := range vals {
		entries = append(entries, kv)
	}
	slices.SortFunc(entries, (*kv).cmp)

	proof := memorydb.New()
	if err := trie.Prove(entries[0].k, proof); err != nil {
		t.Fatalf("Failed to prove the first node %v", err)
	}

	_, err := VerifyRangeProof(trie.Hash(), entries[0].k, nil, nil, proof)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
}
``` 
</details>

Questions:
1. Why was this restriction implemented? Is it related to snap sync's protocol requirements?
2. How should snap sync handle cases where we need to prove a specific range is empty but entries exist after that range?
3. Is this behavior intended to ensure that empty proofs specifically signal "end of data" rather than "this range is empty"?

Would appreciate any insights into the reasoning behind this design decision.

**Comment by holiman** [comment]
Well, when iterating the trie / snapshot to deliver data, one typically iterates past the end. And so loads the element outside the range. So we might aswell deliver that, even if it's outside the range. 

If we were to _not_ deliver that, we'd instead have to provide a proof that the range was empty. And doing so would likely include the same element anyway, but it would reside in the proofs, instead of in the keys. (Or am I misthinking now?)

1. So yes, it's a practical consideration for snap sync responses. 
2. Provide the element outside the range, iirc. 
3. Don't understand the question.

**Comment by weiihann** [comment]
Ah I looked at the [specs](https://github.com/ethereum/devp2p/blob/master/caps/snap.md#getaccountrange-0x00) again, and it says:

>  If no accounts exist between startingHash and limitHash, then the first (if any) account after limitHash must be provided.

So it is a snap sync specification detail.

Thanks a lot for answering my question!
