### ISSUE TITLE
Swarm upload via HTTP POST returns incorrect hash on slow network connections.

### ISSUE THREAD

**Issue by homotopycolimit** [ethereum/go-ethereum#3091]
#### System information

Geth version: `1.5.0-unstable-4dc45770` (swarm branch)
OS & Version: Ubuntu 16.04
#### Expected behaviour

I upload a file to my swarm node using http proxy. I expect to get back the swarm-root-hash of the file.
`cat /path/to/large/file | curl -X POST -d @- http://localhost:32200/bzzr:/ && echo`
should always return the same hash. 
#### Actual behaviour

When the network is slow, I get a different incorrect hash every time.
#### Steps to reproduce the behaviour

I had to simulate a network delay on localhost to get this to work.
`sudo tc qdisc add dev lo root handle 1:0 netem delay 100msec`

and then do

`for i in 1 2 3 4 5 6 7 8 9 0; do cat /path/to/large/file | curl -X POST -d @- http://192.168.1.125:32200/bzzr:/ && echo; done` 

you will get 10 different hashes.

you can reset your network using
`sudo tc qdisc del dev lo root`

**Comment by fjl** [comment]
Maybe it's ignoring errors?

@nagydani @zelig This issue is for you.

**Comment by zelig** [comment]
this has been fixed in 1.5.0 #3132 #3108
