### ISSUE TITLE
Legacy sync reached merge threshold

### ISSUE THREAD

**Issue by aobalv123** [ethereum/go-ethereum#30922]
Hi, I suddenly got an error when syncing my data.
![screenshot-20241217-191728](https://github.com/user-attachments/assets/3c081ff5-bdd6-41af-9893-72c57197461e)

**Comment by fjl** [comment]
Please update your Geth node to the latest version. Also please be aware that you need to run a consensus layer node to follow the chain. See this page for more information: https://ethereum.org/en/developers/docs/nodes-and-clients/node-architecture/

**Comment by aobalv123** [comment]
I am currently building ethw. Does it also require a consensus layer?

**Comment by rjl493456442** [comment]
Not sure what is ethw. If you are referring the legacy PoW-eth, then it's definitely not supported by go-ethereum anymore. Go-ethereum can only support Proof-of-stake (and proof-of-authority for testing).
