### ISSUE TITLE
How to transfer file over the private blockchain

### ISSUE THREAD

**Issue by capamaster** [ethereum/go-ethereum#3095]
#### System information

Geth version: `geth version`
~> Geth 1.4.13-stable

OS & Version: Windows/Linux/OSX

Linux Ubuntnu 14.04

Commit hash : (if `develop`)
#### Steps to reproduce the behaviour

Steps followed from this frontier.

https://ethereum.gitbooks.io/frontier-guide/content/registrar_services.html

The problem is finding the global registrar.

Kindly provide another way for the same.

```
[backtrace]
```

**Comment by fjl** [comment]
Two things you should know about the registrar from the frontier guide: 

1. The contract and API that is described in the frontier guide is no longer officially supported. We have removed the API in the development version of geth.
2. To access a registrar contract you need to deploy it on your blockchain and set the address somehow.

Does that answer your question?

**Comment by capamaster** [comment]
Thanks. 
What is this registrar contract and how to deploy it? 
Could you please share any reference.

**Comment by capamaster** [comment]
will this work ?
MyContract.new({from: primaryAccount, data: contract.code}, function(error, contract){
  if(!error && contract.address) {
    // calculates the content hash and registers it with the code hash in `HashReg`
    // it uses address to send the transaction.
    // returns the content hash that we use to register a url
    admin.register(primaryAccount, contract.address, contenthash)
    // here you deploy ~/dapps/shared/contracts/test/info.json to a url
    admin.registerUrl(primaryAccount, hash, url)
  }
});
