### ISSUE TITLE
How should I build an ETH RPC node to replace Infura without mining?

### ISSUE THREAD

**Issue by huixingaidiqiu** [ethereum/go-ethereum#30965]
I tried the command:
geth --http --http.addr 0.0.0.0 --http.port 8545 --http.api web3,eth,net --datadir "D:\Ethereum" --networkid 1 --syncmode "snap" --http.corsdomain "*"
But I waited for several hours and he didn't synchronize the data. With 50 connections, there was no problem of not being able to connect, but he just didn't synchronize. The hard drive has 2T space

**Comment by rjl493456442** [comment]
You need to setup a consensus client to trigger the sync. Checkout https://geth.ethereum.org/docs/getting-started/consensus-clients for more details.
