### ISSUE TITLE
how to execute a contract on peer node in ethereum private network ?

### ISSUE THREAD

**Issue by akigaikwad** [ethereum/go-ethereum#3096]
Hi,
I have set up a private network with one node on Linux virtual machine and one is my local windows pc .
I have done the peer adding . and I could see peer is added when I do a admin.peers on both the node.
lets call two machines as machine A and machine B.
I have created a contract which will store a number on machine A ,
here is the contract code [copied from internet ] and deployment steps 

1)storeSrc = "contract SimpleStorage { uint storedData; function set(uint x) { storedData = x; } function get() constant returns (uint retVal) { return storedData; } }"

2)storeCompiled = web3.eth.compile.solidity(storeSrc)

3)storeContract = web3.eth.contract(storeCompiled.SimpleStorage.info.abiDefinition);
 
  4)store = storeContract.new({from:web3.eth.accounts[0], data: storeCompiled.SimpleStorage.code, gas: 300000}, function(e, contract){
      if(!e) {
        if(!contract.address) {
         console.log("Contract transaction send: TransactionHash: " + contract.transactionHash + " waiting to be mined...");
       } else {
         console.log("Contract mined! Address: " + contract.address);
         console.log(contract);
       }
     }
})

with following steps I could easily deploy the contract on machine A and was able to execute its as well.

now since I have machine B as a added peer ideally I should be able to access this contract with its address .
but inorder to access the contract function I have to do following steps -

1) storeSrc = "contract SimpleStorage { uint storedData; function set(uint x) { storedData = x; } function get() constant returns (uint retVal) { return storedData; } }"

2) storeCompiled = web3.eth.compile.solidity(storeSrc)

3)storeContract = web3.eth.contract(storeCompiled.SimpleStorage.info.abiDefinition);

4)store = storeContract.at("contract address")

SO MY QUESTION HERE IS CAN  I DEPLOY THIS ON MACHINE B WITHOUT DOING STEP 1,2,3 ?
IS THERE ANY WAY TO AVOID STEP 1,2,3 AND DIRECTLY ACCESS THE CONTRACT USING ITS ADDRESS??
 

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by fjl** [comment]
The ABI definition is not stored on the blockchain. A deployed contract is an EVM byte code program and you have to know the ABI of the contract to interact with it.

Usually your software interacts with a small number of known contracts and you can just put the ABI definition JSON into your software source code. In your case you would take the ABI JSON (`storeCompiled.SimpleStorage.info.abiDefinition`) from step (2) on machine A and move it to machine B.

**Comment by akigaikwad** [comment]
Thanks Felix.............................but in my case if I want store the abi def in block chain what are the steps that I have to follow ...because I dont want to repeat the steps 2,3 and then use "at" for refereing to the contract.....

Regards,
Akshay
