### ISSUE TITLE
Missing RPC methods

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#310]
- [ ] `web3.eth.transaction`
- [ ] `web3.eth.uncle`
- [ ] `web3.eth.defaultBlock`

**Comment by obscuren** [comment]
https://github.com/ethereum/go-ethereum/issues/306

**Comment by tgerring** [comment]
#341

**Comment by frozeman** [comment]
Ok i list it here:

[] Object {code: -32603, message: "Error: Method not implemented eth_uninstallFilter"}

**Comment by tgerring** [comment]
Below is a list of [RPC methods](https://github.com/ethereum/wiki/wiki/JSON-RPC/c00b1bc6c5a26f626ad2a9a6c1d57296e370daae) currently responding (correctly or not) in the [Go client](https://github.com/ethereum/go-ethereum/blob/26d58e0446521f725616b5a5d1b9d1ac04837f00/rpc/packages.go#L371):

- [x] web3_sha3
- [x] eth_coinbase
- [ ] eth_setCoinbase
- [x] eth_listening
- [ ] eth_setListening
- [x] eth_mining
- [ ] eth_setMining
- [x] eth_gasPrice
- [x] eth_accounts
- [x] eth_peerCount
- [ ] eth_defaultBlock
- [ ] eth_setDefaultBlock
- [x] eth_number
- [x] eth_balanceAt
- [x] eth_stateAt
- [x] eth_storageAt
- [x] eth_countAt
- [ ] eth_transactionCountByHash
- [ ] eth_transactionCountByNumber
- [ ] eth_uncleCountByHash
- [ ] eth_uncleCountByNumber
- [x] eth_codeAt
- [x] eth_transact
- [x] eth_call
- [ ] eth_flush
- [x] eth_blockByHash
- [x] eth_blockByNumber
- [ ] eth_transactionByHash
- [ ] eth_transactionByNumber
- [ ] eth_uncleByHash
- [ ] eth_uncleByNumber
- [ ] eth_compilers
- [ ] eth_lll
- [ ] eth_solidity
- [ ] eth_serpent
- [x] eth_newFilter
- [x] eth_newFilterString
- [ ] eth_uninstallFilter
- [x] eth_changed
- [x] eth_filterLogs
- [ ] eth_logs
- [ ] eth_getWork
- [ ] eth_submitWork
- [x] db_put
- [x] db_get
- [ ] db_putString
- [ ] db_getString
- [x] shh_post
- [x] shh_newIdentity
- [x] shh_haveIdentity
- [ ] shh_newGroup
- [ ] shh_addToGroup
- [x] shh_newFilter
- [ ] shh_uninstallFilter
- [x] shh_changed
- [x] shh_getMessages

Additionally, the following messages are in the Go client, but not in the RPC specification as of the time of writing:

- eth_register
- eth_unregister
- eth_watchTx

**Comment by frozeman** [comment]
Additonally some of the methods returns e.g. logs and watches shoudl contain the block `number`.

**Comment by frozeman** [comment]
Self reminder to look into it with gustav:

- filterLogs doesn't seem to work for events/logs

**Comment by thapakazi** [comment]
*I am getting this weird msg*: `The method eth_logs does not exist/is not available`
Do we have issue filtering event logs. I am following this example 

https://github.com/miguelmota/ethereum-development-with-go-book/blob/082005828d9647ac6ecd2684a340e55f7b91f692/code/event_subscribe.go#L21-L29 
```go
	query := ethereum.FilterQuery{
		Addresses: []common.Address{contractAddress},
	}


	logs := make(chan types.Log)
	sub, err := client.SubscribeFilterLogs(context.Background(), query, logs)
	if err != nil {
		log.Fatal(err)
	}
```
/cc @frozeman
