### ISSUE TITLE
Can somebody share 681950. 681951. 681952. 681953.ldb?

### ISSUE THREAD

**Issue by FlepNL** [ethereum/go-ethereum#3101]
#### System information

Geth version: 1.4.14 && 1.4.15
OS & Version: Windows 10

#### Expected behaviour
Download the full blockchain smoothly when running geth to download the full blockchain.

#### Actual behaviour
Geth can't download blocknr 2376961. It keeps hanging at 'timed out DAO fork check - dropping' or crashes full out.
restarting multiple times, at different places / ISP's, with / without VPN, resyncing internet time, all didn't help.
I see get downloading all the ldb's later than 681950, but because it can't download the 681950, I can't get through.

#### Steps to reproduce the behaviour
Download the full blockchain afresh and see it hang around the mentioned block.

Quick solution:
If somebody could share 681950. 681951. 681952. 681953.ldb, I can add these ldb's manually and help Geth get through this tricky spot on the chain.
(not an elegant solution, but it's a temporary workaround. I know you guys are working hard on solving this issue).

Thanks!!

**Comment by Arachnid** [comment]
Please download geth 1.4.16, which resolves all current and past DoS issues.

**Comment by FlepNL** [comment]
that was fast, downloading and testing, thanks!
