### ISSUE TITLE
installing solc - `which solc` returns nothing. 

### ISSUE THREAD

**Issue by samnet** [ethereum/go-ethereum#3103]
Hello (complete noob here):

I am trying to get solc, using https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial#using-an-online-compiler as a guide. 
I first did 
`brew install cpp-ethereum`
`brew linkapps cpp-ethereum`
`which solc`
The brew install seems to have worked, but `which solc` returned nothing. 

I thence tried another way (compiling from source):
`git clone https://github.com/ethereum/cpp-ethereum.git`
`mkdir cpp-ethereum/build`
`cd cpp-ethereum/build`
`cmake -DJSONRPC=OFF -DMINER=OFF -DETHKEY=OFF -DSERPENT=OFF -DGUI=OFF -DTESTS=OFF -DJSCONSOLE=OFF ..`
`make -j4 `
`make install`
`which solc`

Again, apart from some warnings, no error popped up. But again, unfortunately, `which solc`returns nothing. Looking for a directory called solc also returns nothing.

**So I failed to install solc. How can I do that?** 

Something else surprises me. I installed Truffle. Using `truffle test` on the mock contract Truffle provides works all right, i.e., i believe the contract is compiled. I thought Truffle used solc to compiler contracts... without solc on my system, how comes Truffle can compile? 

Rgds

#### System information
**Geth version:** 
Version: 1.4.16-stable-68815256
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.1
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.7.1/libexec
**OS & Version:** OSX el capitan

**Comment by fjl** [comment]
solidity is no longer part of the cpp-ethereum package. You can install it using `brew install solidity`.
