### ISSUE TITLE
Geth 1.5.0-unstable crashes

### ISSUE THREAD

**Issue by FlepNL** [ethereum/go-ethereum#3105]
#### System information

Geth version: 1.5.0-unstable
OS & Version: Windows 10
Commit hash : (if `develop`)
#### Expected behaviour

1.5.0 would continue syncing the chain, where 1.4.14 was stopped (in my case at block 2376961).
#### Actual behaviour

It started with upgrading and converting database. At the step converting 200000 canonical numbers.... it crashed
#### Steps to reproduce the behaviour

download blockchain with 1.4.14, when it hangs, upgrade to 1.5

**Output from geth.exe**

D:\geth>geth1416.exe --datadir="EthereumFast" --rpc --nat=none --verbosity=4 --cache=3072
I1007 19:32:14.377917 ethdb/database.go:80] Allotted 3072MB cache and 1024 file handles to EthereumFast\chaindata
I1007 19:32:18.549359 ethdb/database.go:167] closed db:EthereumFast\chaindata
I1007 19:32:18.551361 cmd/geth/main.go:300] instance: Geth/1.5.0-unstable/go1.6.2/windows
I1007 19:32:18.553363 ethdb/database.go:80] Allotted 3072MB cache and 1024 file handles to EthereumFast\chaindata
I1007 19:32:19.088274 eth/db_upgrade.go:53] Upgrading chain database to use sequential keys
I1007 19:32:19.496738 eth/db_upgrade.go:346] upgrading db log bloom bins
I1007 19:46:49.905673 eth/db_upgrade.go:109] converting 100000 canonical numbers...
I1007 20:07:44.328214 eth/db_upgrade.go:109] converting 200000 canonical numbers...
runtime: VirtualAlloc of 1048576 bytes failed with errno=1455
fatal error: runtime: cannot map pages in arena address space

runtime stack:
runtime.throw(0x11cae80, 0x30)
        C:/Go/src/runtime/panic.go:547 +0x97
runtime.sysMap(0xc2d92a0000, 0x100000, 0x5f6fb01, 0x1875f18)
        C:/Go/src/runtime/mem_windows.go:116 +0x114
runtime.(_mheap).sysAlloc(0x185aa20, 0x100000, 0x0)
        C:/Go/src/runtime/malloc.go:429 +0x198
runtime.(_mheap).grow(0x185aa20, 0x8, 0x0)
        C:/Go/src/runtime/mheap.go:651 +0x6a
runtime.(_mheap).allocSpanLocked(0x185aa20, 0x1, 0x75c3688)
        C:/Go/src/runtime/mheap.go:553 +0x4fd
runtime.(_mheap).alloc_m(0x185aa20, 0x1, 0x11, 0x75c3688)
        C:/Go/src/runtime/mheap.go:437 +0x127
runtime.(_mheap).alloc.func1()
        C:/Go/src/runtime/mheap.go:502 +0x48
runtime.systemstack(0x5f6fd10)
        C:/Go/src/runtime/asm_amd64.s:307 +0xb5
runtime.(_mheap).alloc(0x185aa20, 0x1, 0x10000000011, 0x42675d)
        C:/Go/src/runtime/mheap.go:503 +0x6a
runtime.(_mcentral).grow(0x185c460, 0x0)
        C:/Go/src/runtime/mcentral.go:209 +0x9a
runtime.(_mcentral).cacheSpan(0x185c460, 0xc0e11fd9f0)
        C:/Go/src/runtime/mcentral.go:89 +0x484
runtime.(*mcache).refill(0x180000, 0xc000000011, 0xc084712570)
        C:/Go/src/runtime/mcache.go:119 +0xda
runtime.mallocgc.func2()
        C:/Go/src/runtime/malloc.go:642 +0x32
runtime.systemstack(0xc082012000)
        C:/Go/src/runtime/asm_amd64.s:291 +0x7e
runtime.mstart()
        C:/Go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
        C:/Go/src/runtime/asm_amd64.s:245 fp=0xc0847123a0 sp=0xc084712398
runtime.mallocgc(0x100, 0x0, 0x3, 0x18738d0)
        C:/Go/src/runtime/malloc.go:643 +0x8a8 fp=0xc084712478 sp=0xc0847123a0
runtime.rawmem(0x100, 0xc29284948f)
        C:/Go/src/runtime/malloc.go:809 +0x39 fp=0xc0847124a0 sp=0xc084712478
runtime.growslice(0xce66e0, 0x18738d0, 0x0, 0x0, 0x100, 0x0, 0x0, 0x0)
        C:/Go/src/runtime/slice.go:95 +0x23a fp=0xc084712510 sp=0xc0847124a0
runtime.growslice_n(0xce66e0, 0x18738d0, 0x0, 0x0, 0x100, 0x0, 0x0, 0x0)
        C:/Go/src/runtime/slice.go:44 +0xce fp=0xc084712568 sp=0xc084712510
github.com/syndtr/goleveldb/leveldb.(_DB).get(0xc08208d680, 0x0, 0x0, 0x0, 0x0, 0xc2d9299230, 0x19, 0x30, 0xb5b7c6a, 0x0, ...)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:769 +0x61e fp=0xc0847126c0 sp=0xc084712568
github.com/syndtr/goleveldb/leveldb.(_DB).Get(0xc08208d680, 0xc2d9299230, 0x19, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:840 +0x17f fp=0xc084712770 sp=0xc0847126c0
github.com/ethereum/go-ethereum/ethdb.(_LDBDatabase).Get(0xc082224000, 0xc2d9299230, 0x19, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/ethdb/database.go:123 +0x138 fp=0xc084712828 sp=0xc084712770
github.com/ethereum/go-ethereum/core.WriteMipmapBloom(0x2371a88, 0xc082224000, 0x901d4, 0x0, 0x0, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/core/database_util.go:551 +0x133 fp=0xc084712b90 sp=0xc084712828
github.com/ethereum/go-ethereum/eth.addMipmapBloomBins(0x2371a88, 0xc082224000, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/eth/db_upgrade.go:352 +0x6ae fp=0xc084712da8 sp=0xc084712b90
github.com/ethereum/go-ethereum/eth.New(0xc084aca6c0, 0xc084534700, 0x429458, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/eth/backend.go:174 +0x4a9 fp=0xc084713028 sp=0xc084712da8
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService.func1(0xc084aca6c0, 0x0, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:723 +0x4d fp=0xc084713070 sp=0xc084713028
github.com/ethereum/go-ethereum/node.(_Node).Start(0xc08226bb80, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/node/node.go:179 +0x469 fp=0xc084713378 sp=0xc084713070
github.com/ethereum/go-ethereum/cmd/utils.StartNode(0xc08226bb80)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:66 +0x34 fp=0xc0847133f0 sp=0xc084713378
main.startNode(0xc08227ac80, 0xc08226bb80)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:303 +0x26d fp=0xc0847135e8 sp=0xc0847133f0
main.geth(0xc08227ac80, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:231 +0x51 fp=0xc084713608 sp=0xc0847135e8
runtime.call32(0xc0823dc700, 0x12d9878, 0xc08225fd60, 0x800000018)
        C:/Go/src/runtime/asm_amd64.s:472 +0x45 fp=0xc084713630 sp=0xc084713608
reflect.Value.call(0xd75480, 0x12d9878, 0x13, 0x101f888, 0x4, 0xc084713b10, 0x1, 0x1, 0x0, 0x0, ...)
        C:/Go/src/reflect/value.go:435 +0x1214 fp=0xc084713980 sp=0xc084713630
reflect.Value.Call(0xd75480, 0x12d9878, 0x13, 0xc084713b10, 0x1, 0x1, 0x0, 0x0, 0x0)
        C:/Go/src/reflect/value.go:303 +0xb8 fp=0xc0847139e0 sp=0xc084713980
gopkg.in/urfave/cli%2ev1.HandleAction(0xd75480, 0x12d9878, 0xc08227ac80, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/gopkg.in/urfave/cli.v1/app.go:480 +0x2f5 fp=0xc084713b98 sp=0xc0847139e0
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc08208c600, 0xc08202c180, 0x6, 0x6, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/gopkg.in/urfave/cli.v1/app.go:241 +0xb0c fp=0xc084713e98 sp=0xc084713b98
main.main()
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:220 +0x5a fp=0xc084713f40 sp=0xc084713e98
runtime.main()
        C:/Go/src/runtime/proc.go:188 +0x27e fp=0xc084713f90 sp=0xc084713f40
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc084713f98 sp=0xc084713f90

goroutine 17 [syscall, 186 minutes, locked to thread]:
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [select, 186 minutes]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/logger/sys.go:81 +0x62c
created by github.com/ethereum/go-ethereum/logger.init.1
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/logger/sys.go:60 +0x32

goroutine 6 [chan receive]:
github.com/ethereum/go-ethereum/logger/glog.(*loggingT).flushDaemon(0x1854fe0)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:931 +0x6e
created by github.com/ethereum/go-ethereum/logger/glog.init.1
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:460 +0x76

goroutine 7 [chan receive, 186 minutes]:
github.com/rjeczalik/notify.(*recursiveTree).dispatch(0xc08200a730)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/rjeczalik/notify/tree_recursive.go:125 +0x67
created by github.com/rjeczalik/notify.newRecursiveTree
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/rjeczalik/notify/tree_recursive.go:119 +0x2b8

goroutine 8 [syscall, 186 minutes]:
os/signal.signal_recv(0x0)
        C:/Go/src/runtime/sigqueue.go:116 +0x139
os/signal.loop()
        C:/Go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
        C:/Go/src/os/signal/signal_unix.go:28 +0x3e

goroutine 10 [syscall, 186 minutes, locked to thread]:
syscall.Syscall6(0x7ffb0d3ad5c0, 0x5, 0x298, 0xc0823e3f60, 0xc0823e3f64, 0xc0823e3f70, 0xffffffff, 0x0, 0x0, 0x0, ...)
        C:/Go/src/runtime/syscall_windows.go:174 +0x5c
syscall.GetQueuedCompletionStatus(0x298, 0xc0823e3f60, 0xc0823e3f64, 0xc0823e3f70, 0xffffffff, 0x0, 0x0)
        C:/Go/src/syscall/zsyscall_windows.go:529 +0xb1
github.com/rjeczalik/notify.(_readdcw).loop(0xc082008a80)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_readdcw.go:325 +0x70
created by github.com/rjeczalik/notify.(_readdcw).lazyinit
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_readdcw.go:314 +0x17a

goroutine 35 [select, 186 minutes]:
github.com/ethereum/go-ethereum/accounts.(_watcher).loop(0xc08225fec0)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/accounts/watch.go:91 +0x7a2
created by github.com/ethereum/go-ethereum/accounts.(_watcher).start
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/accounts/watch.go:53 +0x59

goroutine 41 [runnable, locked to thread]:
syscall.Syscall6(0x7ffb0d3bdcc0, 0x5, 0xdc0, 0xc0828e7148, 0x40, 0xc08243368c, 0x0, 0x0, 0x30000000, 0xc1fea09c60, ...)
        C:/Go/src/runtime/syscall_windows.go:174 +0x5c
syscall.WriteFile(0xdc0, 0xc0828e7148, 0x40, 0x4f10, 0xc08243368c, 0x0, 0x0, 0x0)
        C:/Go/src/syscall/zsyscall_windows.go:302 +0xe4
syscall.Write(0xdc0, 0xc0828e7148, 0x40, 0x4f10, 0x4f0a, 0x0, 0x0)
        C:/Go/src/syscall/syscall_windows.go:325 +0x76
os.(_File).write(0xc0e946f218, 0xc0828e7148, 0x40, 0x4f10, 0x0, 0x0, 0x0)
        C:/Go/src/os/file_windows.go:400 +0x153
os.(_File).Write(0xc0e946f218, 0xc0828e7148, 0x40, 0x4f10, 0x0, 0x0, 0x0)
        C:/Go/src/os/file.go:136 +0x97
github.com/syndtr/goleveldb/leveldb/journal.(_Writer).writePending(0xc0828e4000)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/journal/journal.go:414 +0xe0
github.com/syndtr/goleveldb/leveldb/journal.(_Writer).Flush(0xc0828e4000, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/journal/journal.go:433 +0x43
github.com/syndtr/goleveldb/leveldb.(_DB).writeJournal(0xc08208d680, 0xc0e0c3b900, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:25 +0x135
github.com/syndtr/goleveldb/leveldb.(_DB).Write(0xc08208d680, 0xc0e0c3b900, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:244 +0xa26
github.com/syndtr/goleveldb/leveldb.(_DB).Put(0xc08208d680, 0xc2c2a56d60, 0xa, 0x10, 0xc0d8d10c20, 0x20, 0x20, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:269 +0xb4
github.com/ethereum/go-ethereum/ethdb.(_LDBDatabase).Put(0xc082224000, 0xc2c2a56d60, 0xa, 0x10, 0xc0d8d10c20, 0x20, 0x20, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/ethdb/database.go:113 +0x180
github.com/ethereum/go-ethereum/eth.upgradeSequentialCanonicalNumbers(0x2371a88, 0xc082224000, 0xc082433f38, 0x0, 0x0, 0xc0823dfc00)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/eth/db_upgrade.go:114 +0x6a3
github.com/ethereum/go-ethereum/eth.upgradeSequentialKeys.func1(0xc0828ae840, 0x2371a88, 0xc082224000, 0xc0828ae8a0)
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/eth/db_upgrade.go:68 +0x86
created by github.com/ethereum/go-ethereum/eth.upgradeSequentialKeys
        D:/builds/geth_win32/build-go-win-develop/go/src/github.com/ethereum/go-ethereum/eth/db_upgrade.go:83 +0x2ba

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc082246000)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x2a5
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x277

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc08208d680)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0x554
created by github.com/syndtr/goleveldb/leveldb.openDB
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:141 +0x6e1

goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc08208d680)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:97 +0x153
created by github.com/syndtr/goleveldb/leveldb.openDB
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:142 +0x703

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(_DB).pauseCompaction(0xc08208d680, 0xc1fcb03860)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:644 +0xf9
github.com/syndtr/goleveldb/leveldb.(_DB).tCompaction(0xc08208d680)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:807 +0x7cb
created by github.com/syndtr/goleveldb/leveldb.openDB
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:148 +0x907

goroutine 16 [runnable]:
github.com/golang/snappy.emitLiteral(0xc2be369502, 0x1407, 0x1407, 0xc28a549500, 0x16, 0x1231, 0x5)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/golang/snappy/encode.go:17
github.com/golang/snappy.Encode(0xc2be369500, 0x1409, 0x1409, 0xc28a549500, 0x10d5, 0x1231, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/golang/snappy/encode.go:132 +0x490
github.com/syndtr/goleveldb/leveldb/table.(_Writer).writeBlock(0xc26cd09200, 0xc26cd09258, 0x2, 0x0, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:170 +0x1d9
github.com/syndtr/goleveldb/leveldb/table.(_Writer).finishBlock(0xc26cd09200, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:221 +0x7c
github.com/syndtr/goleveldb/leveldb/table.(_Writer).Append(0xc26cd09200, 0xc0a19e114c, 0x24, 0x15178eb4, 0xc0a19e1170, 0x100, 0x15178e90, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:254 +0x478
github.com/syndtr/goleveldb/leveldb.(_tWriter).append(0xc1fcb03aa0, 0xc0a19e114c, 0x24, 0x15178eb4, 0xc0a19e1170, 0x100, 0x15178e90, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table.go:488 +0x2f2
github.com/syndtr/goleveldb/leveldb.(_tOps).createFrom(0xc084acae10, 0x1b46e88, 0xc28d0f3e80, 0x0, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table.go:329 +0x1cc
github.com/syndtr/goleveldb/leveldb.(_session).flushMemdb(0xc082068210, 0xc28e29e280, 0xc0820f00e0, 0x0, 0x0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/session_compaction.go:27 +0x193
github.com/syndtr/goleveldb/leveldb.(_DB).memCompaction.func1(0xc0e90d6cd0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:304 +0x98
github.com/syndtr/goleveldb/leveldb.(_compactionTransactFunc).run(0xc0e90d6cc0, 0xc0e90d6cd0, 0x0, 0x0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:241 +0x3d
github.com/syndtr/goleveldb/leveldb.(_DB).compactionTransact(0xc08208d680, 0x104d840, 0xb, 0x6a1d878, 0xc0e90d6cc0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:185 +0x282
github.com/syndtr/goleveldb/leveldb.(_DB).compactionTransactFunc(0xc08208d680, 0x104d840, 0xb, 0xc0e6b2cc90, 0xc0e8a482a0)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:252 +0xc5
github.com/syndtr/goleveldb/leveldb.(_DB).memCompaction(0xc08208d680)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:315 +0x53d
github.com/syndtr/goleveldb/leveldb.(_DB).mCompaction(0xc08208d680)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:755 +0x187
created by github.com/syndtr/goleveldb/leveldb.openDB
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:149 +0x929

goroutine 50 [select, 186 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc08208d680)
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x1aa
created by github.com/syndtr/goleveldb/leveldb.openDB
        D:/builds/geth_win32/build-go-win-develop/build/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:150 +0x94b

D:\geth>geth1416.exe --datadir="EthereumFast" --rpc --nat=none --verbosity=4 --cache=3072

**Comment by fjl** [comment]
You are running geth 1.5.0. Where did you download the binary?

**Comment by FlepNL** [comment]
here, on the GitHub.com site > Code-tab >  Automated Development Builds > Windows 64 

https://build.ethdev.com/builds/Windows%20Go%20develop%20branch/Geth-Win64-latest.zip

**Comment by FlepNL** [comment]
When running geth1.4.16, I get the following 'chain db corrupt' error:

D:\geth>geth1416.exe --datadir="EthereumFast" --cache=2048 --rpc --nat=none --verbosity=4
I1008 11:58:43.151474 ethdb/database.go:83] Alloted 2048MB cache and 1024 file handles to EthereumFast\chaindata
I1008 12:00:05.326871 cmd/utils/flags.go:830] ------------------------------------------------------------------------------------------------
I1008 12:00:05.332876 cmd/utils/flags.go:831] Geth is currently configured to SUPPORT the DAO hard-fork!
I1008 12:00:05.335878 cmd/utils/flags.go:832] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I1008 12:00:05.340885 cmd/utils/flags.go:833] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I1008 12:00:05.344888 cmd/utils/flags.go:834] ------------------------------------------------------------------------------------------------
I1008 12:00:05.360917 ethdb/database.go:171] closed db:EthereumFast\chaindata
I1008 12:00:05.409124 ethdb/database.go:83] Alloted 2048MB cache and 1024 file handles to EthereumFast\chaindata
I1008 12:00:05.916876 eth/backend.go:621] upgrading db log bloom bins
Fatal: Error starting protocol stack: chain db corrupted. Could not find block 0.

**Comment by fjl** [comment]
Please remove `EthereumFast\chaindata` folder and sync again. The crash has corrupted your database.

**Comment by fjl** [comment]
1.5.0 is released now. Please report any issues with the upgrade.
