### ISSUE TITLE
geth 1.4.16 not syncing now

### ISSUE THREAD

**Issue by simontfs** [ethereum/go-ethereum#3106]
#### System information

Geth version: `1.4.16`
OS & Version: Windows 7 64bit

#### Expected behaviour
geth should be syncing with the new version currently 1.4.16

#### Actual behaviour
mist running with geth 1.4.16 no syncing no peers/seeds and stuck on 2,392,031 for hours and hours now

**Comment by ethernomad** [comment]
This is the commit that breaks syncing for me: https://github.com/ethereum/go-ethereum/commit/afecb93e2e6b8350ca9fe8c93e5e32b4c3c7b857

**Comment by trustfarm-dev** [comment]
@simontfs I've experience several hangon syncing.
and then, restart geth then synchronize well.

**Comment by karalabe** [comment]
Usually it's syncing, just slowly. Please update to 1.4.18. It will still take a lot of time to crunch through the hugely wasteful blocks the attacker fed into the blockchain, but there should be more regular progress reports. Alternatively you could do a fast sync from scratch (delete `chaindata`) after updating Geth to avoid pulling in most of the junk the attacker shoved into the blockchain.
