### ISSUE TITLE
Keystore folder location

### ISSUE THREAD

**Issue by simontfs** [ethereum/go-ethereum#3107]
Keystore folder has moved from Appdata\Roaming\Ethereum to Appdata\Roaming\Mist\

Is this a permanent move? if so, the Ethereum wallet accounts>Backup>Accounts .... points to the wrong location (it still points to AppData\Roaming\Ethereum) 

Also unless the keystore folder iscopied from AppData\Roaming\Ethereum  to AppData\Roaming\Mist\
,  Ethereum wallet version 0.8.4 tells you that no account has been made.  Once keystore folder has been copied over from old location to new location Ethereum wallet recognises it.

**Comment by karalabe** [comment]
Please open an issue about this in the Mist repo. Geth has not changed the location of keystores ever, so if Mist moved them around, they should provide the necessary migration tools.
