### ISSUE TITLE
Remove web3.db

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#311]
Remove `web3.db` in favour of `localStorage`

**Comment by eddieoz** [comment]
Was web3.db removed?

Inside console:
> web3.db
{
  getHex: function(),
  getString: function(),
  putHex: function(),
  putString: function()
}
> web3.db.putString('testDB', 'key', 'myString')
The method db_putString does not exist/is not available
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:1
> web3.db.putHex('testDB', 'key', web3.fromAscii('myString'))
The method db_putHex does not exist/is not available
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:1
> web3.db.getString('testDB', 'key')
The method db_getString does not exist/is not available
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:1
> web3.db.getHex('testDB', 'key')
The method db_getHex does not exist/is not available
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:1
> web3.version
{
  api: "0.15.3",
  ethereum: "0x3f",
  network: "3535",
  node: "Geth/v1.4.4-stable-fc0638f9/darwin/go1.6.2",
  whisper: "0x2",

Regards,
Edilson

**Comment by fjl** [comment]
Yes, it has beene removed in geth 1.4. You are actually the first person to notice that.

**Comment by eddieoz** [comment]
Thanks! I came to this topic because Im looking for a way to persist whisper identities without using a dapp.

Best regards,
Edilson
