### ISSUE TITLE
Geth 1.4.16 txpool crash

### ISSUE THREAD

**Issue by sch7** [ethereum/go-ethereum#3110]
#### System information

Geth version: 1.4.16
OS & Version: Ubuntu 16.04

#### Actual behaviour

Crash

#### Steps to reproduce the behaviour

Just crashed after two days

#### Backtrace

It was much longer but I don't have more history on a screen, only a lot of such backtraces:

goroutine 4742500 [select, 34 minutes]:
github.com/ethereum/go-ethereum/event.(*muxsub).deliver(0xc8322a8900, 0xc8e77f6f60)
        /home/fjl/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/event/event.go:217 +0x1c2
github.com/ethereum/go-ethereum/event.(*TypeMux).Post(0xc8201199b0, 0xe88f60, 0xca3c57acf0, 0x0, 0x0)
        /home/fjl/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/event/event.go:108 +0x2ce
created by github.com/ethereum/go-ethereum/core.(*TxPool).addTx
        /home/fjl/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:334 +0x165

**Comment by karalabe** [comment]
I'm assuming the issue was an OOM caused by the hugely bloated state the attacker made. Please update to 1.4.18.
