### ISSUE TITLE
not clear how to switch from classic to regular eth chain

### ISSUE THREAD

**Issue by jpritikin** [ethereum/go-ethereum#3113]
#### System information

Version: 1.5.0-unstable (1.4.16-4fced097)
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go

#### Expected behaviour
I sync'd the eth classic chain. I expected to be able to trash the chain and re-sync the regular eth chain.

#### Actual behaviour
The -support-dao-fork option is no longer supported. I tried to sync the regular eth chain and got eth classic instead. How do I switch back?

#### Steps to reproduce the behaviour
geth --support-dao-fork

**Comment by fjl** [comment]
Resyncing with develop branch should land you on the non-classic chain.

> I tried to sync the regular eth chain and got eth classic instead.

Which commands did you use?

**Comment by jpritikin** [comment]
On Sun, Oct 09, 2016 at 01:45:31PM -0700, Felix Lange wrote:
>    Resyncing with develop branch should land you on the non-classic chain.
> 
>      I tried to sync the regular eth chain and got eth classic instead.
> 
>    Which commands did you use?

geth --fast

Maybe an old config.rlp was sitting in ~/.ethereum?

-- 
Joshua N. Pritikin, Ph.D.
Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
PO Box 980126
800 E Leigh St, Biotech One, Suite 1-133
Richmond, VA 23219
http://people.virginia.edu/~jnp3bc

**Comment by karalabe** [comment]
There's no way to switch from ETC to ETH apart from doing a sync from scratch. Please delete your `chaindata` folder and start a new run of `geth --fast`. Please make sure you're using a release from the upstream Ethereum account and not some ETC version that has the DAO fork removed.

**Comment by jpritikin** [comment]
On Sun, Oct 16, 2016 at 03:27:43AM -0700, P�ter Szil�gyi wrote:
>    There's no way to switch from ETC to ETH apart from doing a sync from
>    scratch. Please delete your chaindata folder and start a new run of
>    geth --fast. Please make sure you're using a release from the upstream
>    Ethereum account and not some ETC version that has the DAO fork
>    removed.

Can you make 'geth removedb' also remove the config.rlp file? I think 
that's the only part that confused me.

Thanks.

**Comment by fjl** [comment]
We don't use config.rlp. This file is created by cpp-ethereum.

**Comment by jpritikin** [comment]
On Sun, Oct 16, 2016 at 11:57:50AM -0700, Felix Lange wrote:
>    We don't use config.rlp. This file is created by cpp-ethereum.

Don't you store whether to support or oppose the DAO fork somewhere?

**Comment by fjl** [comment]
It's stored in the chain database.

**Comment by jpritikin** [comment]
OK, I guess I misdiagnosed my experience. Oh well, I did get the correct fork sync'd. Thanks.
