### ISSUE TITLE
Fast sync stopped prematurely

### ISSUE THREAD

**Issue by ntpeters** [ethereum/go-ethereum#3123]
#### System information

Geth version: `1.4.17`
OS & Version: macOS 10.12
Commit hash : 1.4.17 release, installed via brew

#### Expected behaviour
If I understand correctly, fast sync should sync up to the current block, or very close to it.

#### Actual behaviour
Fast sync stopped a little over 20k blocks short of current, then began syncing blocks normally.

#### Steps to reproduce the behaviour
Renamed chaindata folder, then:
```
geth --cache 2048 --targetgaslimit 1500000 --gasprice 20000000000 --fast console
```

#### Backtrace

Relevant portion:
````
I1011 09:43:09.778752 eth/downloader/downloader.go:948] imported 20 state entries in 991.818µs: processed 48094, pending at least 0
I1011 09:43:09.780735 core/blockchain.go:764] imported 0 receipt(s) (1 ignored) in 1.861911ms. #2381660 [9bfe42d9… / 9bfe42d9…]
I1011 09:43:09.780790 core/blockchain.go:280] committed block #2381660 [9bfe42d9…] as new head
I1011 09:45:41.888635 core/blockchain.go:975] imported 1360 block(s) (0 queued 0 ignored) including 10066 txs in 2m32.097889432s. #2383020 [809e6c2b / 7482ec9c]
I1011 09:45:41.888678 eth/sync.go:189] fast sync complete, auto disabling
I1011 09:46:08.735346 core/blockchain.go:975] imported 11 block(s) (0 queued 0 ignored) including 42 txs in 1.727839453s. #2383031 [258fc924 / ed84ef1b]
````

**Comment by karalabe** [comment]
In theory yes. But when fast sync starts, it picks the best peer and syncs to that peer's head. If all your peers during fast sync startup are behind the actual head, you'll get to something that's older. If the network is healthy this would be semi impossible, but with the current attacks and many non upgraded nodes, it happens from time to time that all your peers are behind so fast sync will only get you that far, not to the latest block.

**Comment by ntpeters** [comment]
Got it, that makes sense. It just seemed odd when I saw it stop that far behind. Thanks for the explanation. Closing.
