### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by tom-seddon** [ethereum/go-ethereum#3125]
#### System information

Geth version:

Geth
Version: 1.4.17-stable-5a6008e0
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.1
OS: darwin
GOPATH=/Users/tom/go
GOROOT=/Users/tom/usr/go

OS & Version: OS X El Capitan 10.11.6

Commit hash : (if `develop`)
#### Expected behaviour

Doesn't crash.
#### Actual behaviour

Did crash.
#### Steps to reproduce the behaviour

Unsure - I requested a REP transfer from the Ethereum wallet and left my PC doing its thing. Then when I got back geth had crashed. (Sorry, I know this is a crap bug report... I'm only filing it because it printed a voluminous stack trace that might help somebody)
#### Backtrace

[gistfile1.txt](https://github.com/ethereum/go-ethereum/files/522796/gistfile1.txt)

**Comment by fjl** [comment]
Thanks. This is a recent regression. We will fix this for the next release.

**Comment by fjl** [comment]
Fixed by #3162

**Comment by fjl** [comment]
Fix released in 1.5.0.
