### ISSUE TITLE
`attach` does not respect non-default `--datadir`

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/go-ethereum#3127]
I am running the latest geth on Ubuntu 15.04 x64 from the released binary:
I start geth via
```
$ geth --datadir=~/ethDataDir-2016-10-10/ console
```
Then I open a new terminal and attempt to attach to the primary geth session but unfortunately get an error:
```
$ geth attach
Fatal: Unable to attach to remote geth: dial unix /home/someone/.ethereum/geth.ipc: connect: no such file or directory
```
I expected it to attach and give me a second Ethereum console. It seems that `attach` does not respect the `--datadir`: I get the same error even when attempting to tell it where to look for that `geth.ipc` file:
```
$ geth --datadir=~/ethDataDir-2016-10-10 attach
Fatal: Unable to attach to remote geth: dial unix /home/someone/.ethereum/geth.ipc: connect: no such file or directory
```
The specified datadir does have the expected `geth.ipc` file:
```
$ ls ~/ethDataDir-2016-10-10
chaindata  dapp  geth.ipc  history  nodekey  nodes
```

Version info:
```
$ geth version
Geth
Version: 1.4.17-stable-5a6008e0
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.1
OS: linux
GOPATH=/home/someone
GOROOT=/usr/lib/go-1.7
```

**Comment by Arachnid** [comment]
To specify the socket to connect to for attach, supply it as an argument after `attach`, not using `--datadir`:

    geth attach ipc:/home/someone/ethDataDir-2016-10-10/geth.ipc

**Comment by ethernomad** [comment]
I found I had to do it like this:
```
geth attach ~/.link-geth/geth.ipc
```

Not that in `develop` all nodes can share a single datadir: https://github.com/ethereum/go-ethereum/pull/2914

**Comment by fjl** [comment]
Support for `geth attach --datadir=...` was added in ethereum/go-ethereum#15517
