### ISSUE TITLE
Sign releases, tags and binaries for trusted & secure distribution

### ISSUE THREAD

**Issue by brutuscat** [ethereum/go-ethereum#3137]
Hi guys, thank you for the great work you are doing on the miner! 

I was thinking that it would really helpful and would add a lot trust (when running a binary) if you could sign the releases, the tags and the binaries that you ship:
- [Git Tools - Signing Your Work](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work)
- [Signing tags using GPG
  ](https://help.github.com/articles/signing-tags-using-gpg/)
- [example to create and sign Github releases](https://wiki.debian.org/Creating%20signed%20GitHub%20releases) 

Keep it coming!

**Comment by fjl** [comment]
Release archives are now signed using GPG keys.
