### ISSUE TITLE
Geth fails to broadcast transaction

### ISSUE THREAD

**Issue by Joter85** [ethereum/go-ethereum#3147]
Geth version: Geth/v1.4.18-stable-ef9265d0/windows/go1.7.1
OS & Version: Windows Server 2012 R2

For the last 12 hours we are no longer able to send transactions. 

When we execute eth.sendTransaction function we get result with transaction id, but that transaction is never included in blockchain. 

Example transaction form attached log is 0x64a25caa7cc4e859a428e9f4d6801153105a88486c93eda1e98bf572f58ec439 which we can't find in blockchain. 

As you can see bellow we are connected to 27 peers:

```
> net
{
  listening: true,
  peerCount: 27,
  version: "1",
  getListening: function(callback),
  getPeerCount: function(callback),
  getVersion: function(callback)
}
>
```

[geth.txt](https://github.com/ethereum/go-ethereum/files/531798/geth.txt)

**Comment by fjl** [comment]
Please try resending the transaction with higher gas price.

**Comment by Joter85** [comment]
We don't define gas amount or price, so as I read from documentation it should be determined by geth?

**Comment by fjl** [comment]
Yes the price is determined by geth if you don't specify it explicitly.

**Comment by Joter85** [comment]
But it could be determined wrong?

On Oct 16, 2016 21:49, "Felix Lange" <notifications@github.com> wrote:

>

> Yes the price is determined by geth if you don't specify it explicitly.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
<https://github.com/ethereum/go-ethereum/issues/3147#issuecomment-254069766>,
or mute the thread

**Comment by fjl** [comment]
The gas price assigned by geth is a recommendation that may or may not work well. Whether or not the transaction gets included depends on network conditions dictated by miners. Raising the gas price of your transactions should lead to getting them included faster because miners usually prioritise transactions with higher gas price.

**Comment by Joter85** [comment]
Ok thanks. What about transactions that were already send and weren't
included in blockchain. How long are they still valid for miners? If we
resend same transaction again with higher gas is it possible that both
transactions get included in blockchain?

**Comment by BillyBurns** [comment]
JOTER stop sending eth withdrawls you did double send I received 81 ether twice

**Comment by fjl** [comment]
Every transaction has a nonce. You can resend a certain transaction by sending another transaction with the same nonce. Only one of them will be included.

**Comment by Joter85** [comment]
How can we list all transactions that were send from our node and are waiting to be included in blockchain? Or how can we delete all transactions that still wait for miners?

**Comment by fjl** [comment]
You can check the last nonce for which a transaction was included in a block with the `eth_getTransactionCount` RPC call. If you just want to check your local pool you can use `txpool_content`.

Note that there is no way to delete transactions that have already been propagated to the network.

**Comment by BillyBurns** [comment]
Joter can you come in chat and say last 4 of the address so I know this email is from you

**Comment by Joter85** [comment]
Ok thanks for help. Seems there are no more pending transactions in txpool.

**Comment by fjl** [comment]
But are they mined into the blockchain?

**Comment by Joter85** [comment]
Don't see them in etherscan...

**Comment by fjl** [comment]
OK. Did you try sending the same transaction with higher gas price? Again, you can find the last nonce that was mined into a block using `eth_getTransactionCount`. In the geth console, use `eth.getTransactionCount(address)`. If the transactions are sent by software it is advisable to manage acount nonces explicitly so you can resend transactions as necessary.

**Comment by Joter85** [comment]
Yes. Gonna store account nonce from now on, so we can easy resend if required....

**Comment by christynelson467** [comment]
I stumbled across something that said while trying to make space in file. if this is something I did by all means take your gas.  I  don't know how to identify myself or claim transaction.  I followed a email.  I  hope I'm not putting mysel in debt here

**Comment by christynelson467** [comment]
please remove what ever code idk how
