### ISSUE TITLE
Geth testnet is syncing rarely

### ISSUE THREAD

**Issue by paradise** [ethereum/go-ethereum#3148]
#### System information

Geth version: `1.4.18`
OS & Version: Windows

#### Expected behaviour
Geth should sync every block

#### Actual behaviour
Geth is syncing every 20-30 blocks. 

My problem is that my geth after last updates stopped to sync every block. It is always running, but for example, when I see on https://testnet.etherscan.io/ that last block number was 1779810, my local geth node `eth.blockNumber` returns 1779789. `eth.syncing` is false. After some time geth becomes synced, but then it again hangs on one block, while in etherscan I see that a lot of new blocks are mined.

**Comment by paradise** [comment]
I started geth with verbosity = 3 and saw this (it repeats infinitely):
`I1016 21:41:45.357170 eth/downloader/downloader.go:611] Peer 03a3fef607ecdbc6 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 16.237147854s]: head header set (item 0) broke chain ordering: requested 1779708, got 1779723`
`I1016 21:41:54.273184 eth/downloader/downloader.go:611] Peer 03a3fef607ecdbc6 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 16.237147854s]: head header set (item 0) broke chain ordering: requested 1779708, got 1779723`
`I1016 21:41:56.492110 eth/downloader/downloader.go:611] Peer 03a3fef607ecdbc6 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 16.237147854s]: head header set (item 0) broke chain ordering: requested 1779708, got 1779723`
`I1016 21:41:59.380885 eth/downloader/downloader.go:611] Peer 03a3fef607ecdbc6 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 16.237147854s]: head header set (item 0) broke chain ordering: requested 1779708, got 1779723`
`I1016 21:42:01.915264 eth/downloader/downloader.go:611] Peer 03a3fef607ecdbc6 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 16.237147854s]: head header set (item 0) broke chain ordering: requested 1779708, got 1779723`
`I1016 21:42:04.794681 eth/downloader/downloader.go:611] Peer 03a3fef607ecdbc6 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 16.237147854s]: head header set (item 0) broke chain ordering: requested 1779708, got 1779723`
`I1016 21:42:10.380490 eth/downloader/downloader.go:611] Peer 03a3fef607ecdbc6 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 16.237147854s]: head header set (item 0) broke chain ordering: requested 1779708, got 1779723`
`I1016 21:42:15.359465 eth/downloader/downloader.go:611] Peer 03a3fef607ecdbc6 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 16.237147854s]: head header set (item 0) broke chain ordering: requested 1779708, got 1779723`
`I1016 21:42:18.765056 eth/downloader/downloader.go:611] Peer 03a3fef607ecdbc6 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 16.237147854s]: head header set (item 0) broke chain ordering: requested 1779708, got 1779723`

**Comment by resurtm** [comment]
@paradise I'm having testnet syncing issues too: #3146

**Comment by resurtm** [comment]
@paradise Why did you close that? What was the issue after all?
