### ISSUE TITLE
geth won't sync past block 2457000

### ISSUE THREAD

**Issue by Crypto2** [ethereum/go-ethereum#3151]
I'm using the latest Ubuntu ppa build of geth and it's stopped syncing with this error message:

E1017 17:09:50.914147 core/blockchain.go:1180] Bad block #2457001 (0xe0a37b04e0e4c12c4bcbae510a5a7128a293e06cafd410a3013b9d68cc2de305)
E1017 17:09:50.914171 core/blockchain.go:1181]     GasLimit reached. Have 129397 gas, transaction requires 132650

Have tried with both JitVM on and off since it was showing a warning about possible sync issues but same result either way.

Version info:

Geth
Version: 1.5.0-unstable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.6

**Comment by obscuren** [comment]
Could you update your repo (`develop`) branch and try again?

**Comment by Crypto2** [comment]
It says there are no updates available. These are the 2 repo lines I have:
deb http://ppa.launchpad.net/ethereum/ethereum-dev/ubuntu xenial main
deb http://ppa.launchpad.net/ethereum/ethereum/ubuntu xenial main

**Comment by obscuren** [comment]
Would you be OK building from source and try that out instead of the dep package? If you can please follow the instruction listed on [this](https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu#building-from-source) wiki page.

**Comment by Crypto2** [comment]
Compile from source is running now, it's redownloading the whole blockchain for some reason so it will be a while before I know if it worked or not. Will report back.

**Comment by Lucky7111** [comment]
I use also geth 1.14.8 do not sync at 2.422.521 - leave it work but over one hour nothing

**Comment by Crypto2** [comment]
Using the self-compiled version it has gotten past 2457000 this time; just sucks waiting for the full resync.

**Comment by Crypto2** [comment]
It's started doing it again now on block 2480673:
E1021 16:23:35.606096 core/blockchain.go:1170] Bad block #2480673 (0x1dd4d8747356e5a0b8e870b6853234152a8ddb7170ddef8afb16b9c9307b362a)
E1021 16:23:35.606123 core/blockchain.go:1171]     gas used error (403185 / 383485)
