### ISSUE TITLE
estimateGas always yields 1 eth when method throws an exception

### ISSUE THREAD

**Issue by juliosan** [ethereum/go-ethereum#3152]
#### System information

Geth version: 1.5.0-unstable-89ba380b
OS & Version: OSX
#### Expected behaviour
- estimateGas should return the actual amount of gas used when calling a method. However this is not the case when the method throws an exception
#### Actual behaviour
- estimateGas always returns 50000000 units of gas when the method call throws an exception. At a gas price of 20000000000, estimateGas always yields 1 eth, which is unrealistic. One would expect to get the actual gas consumption, which is not zero when the method is called and throws an exception 
#### Steps to reproduce the behaviour
- Create a method in a contract that throws. Call estimateGas and evaluate result.
  Hint: 50000000 seems to be the initialization value for gas-related variables in geth's implementation: https://github.com/ethereum/go-ethereum/blob/master/eth/api.go
  Seems that the exception throwing interrupts the gas estimation process
#### Backtrace

```
[backtrace]
```

**Comment by karalabe** [comment]
A `throw` always consumes all available gas. That's how the EVM works. 50M is an arbitrary upper limit, but it can be anything, a `throw` will still consume it all.
