### ISSUE TITLE
estimateGas is broken for contract calls after hardfork

### ISSUE THREAD

**Issue by NGB86** [ethereum/go-ethereum#3163]
estimateGas always returns 50000000 of gas (0x02faf080) for contracts afters hard fork.

Here is my example for REP tokens: 
`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{ 
from: '0xcb2ceba7566f70e1e92a28934453951d2dfaff3b',
to: '0x48c80f1f4d53d5951e5d5438b54cba84f29f32a5',
gasPrice: '0x072339d12b',
data: '0xa9059cbb000000000000000000000000a125753da48115281fdbf01ee0c95176799aca9e0000000000000000000000000000000000000000000000008ac7230489e80000' }
],"id":1}'`

**Comment by vbecas** [comment]
Same for me (running latest version 1.4.18 version)! 

eth3.augur.net running Geth/v1.5.0-unstable-6952fe3a/linux/go1.5.1 works fine
