### ISSUE TITLE
RPC connect remote server get Connection Refused err

### ISSUE THREAD

**Issue by VenusHu** [ethereum/go-ethereum#3169]
#### System information

Geth version: 1.5.0
OS & Version: Ubuntu 14.04

I use hooked web3 to connect my remote server by RPC, but get err: Connection refused.

app.js:5319 OPTIONS http://xxx:8545/ net::ERR_CONNECTION_REFUSED
i.sendAsync @ app.js:5319
finishedWithRewrite @ hooked-web3-provider.js:89
rewritePayloads @ hooked-web3-provider.js:109
next @ hooked-web3-provider.js:119
rewritePayloads @ hooked-web3-provider.js:124
sendAsync @ hooked-web3-provider.js:98
s.sendAsync @ app.js:5319
e @ app.js:5319s.call @ app.js:5319
refreshBalance @ app.js:44083
window.onload @ app.js:44149

**Comment by karalabe** [comment]
Is your node reachable? Try using some simple command line tool to check it. My guess is that your firewall is blocking somewhere. Btw, it's very unhealthy to expose an RPC channel over the internet.

**Comment by VenusHu** [comment]
thank you for your help! i solved my problem by setting --rpcaddr='0.0.0.0'

**Comment by bas-vk** [comment]
Okay, as karalabe mentioned, be very careful with exposing your RPC interface to the world.
If you have your accounts unlocked they can be abused from the outside, e.g. you could loose your ether or someone can impersonate you.
