### ISSUE TITLE
Invalid nonce during mining

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#317]
During mining and creating / receiving transactions it sometimes happens that an `agent` broadcasts an invalid nonce. This is caused by a delay in a `close(chan)` which should stop / reset the `agent` from mining. The nonce that's broadcasted back to the `worker` is one with an old `block.hash` which results in an invalid nonce.

For example:
```
[miner 0] ->          mine on 0xaa...c1
[tx 1 comes in] ->    work out new state ...
[miner 0] ->          finds nonce [broadcast]
[worked out state] -> new block 0x23..a8
[miner 0] ->          set nonce (using 0xaa..c1) to [ new block 0x23..a8 ]
[verify] ->            invalid
```

**Comment by jorisbontje** [comment]
This pretty much happens all the time for me, making it impossible to mine transactions. Can I assist in providing any additional information to help resolve this?

**Comment by maran** [comment]
I think this should be resolved by now.

**Comment by jorisbontje** [comment]
Yes, not seeing this anymore in 8620dc0

**Comment by jorisbontje** [comment]
Correction, this is back:
```
2015/03/23 09:32:18 [CHAIN] INVALID block #14486 (b0e56177)
2015/03/23 09:32:18 [CHAIN] Block's nonce is invalid (= 2a4bfb9eee6abc97)
2015/03/23 09:32:18 [MINER] committing new work with 0 txs
2015/03/23 09:32:19 [XETH] Contract addr 87b815f4c7189a4e7cc61e6084f755f225afa0ea
```

**Comment by jorisbontje** [comment]
How should I get around these errors? Mining is stuck on this block.

**Comment by obscuren** [comment]
Delete your dag

**Comment by zelig** [comment]
@jorisbontje can you confirm if this is still an issue?

**Comment by jorisbontje** [comment]
@zelig haven't seen this recently
