### ISSUE TITLE
Geth dont exist from sync status while syncing morden network

### ISSUE THREAD

**Issue by iFA88** [ethereum/go-ethereum#3170]
Geth version: `Geth/v1.5.0-unstable-6952fe3a/linux/go1.7`
OS & Version: Linux Debian Jessie

I'm synced with the `Morden` network, but the geth do not exists from the syncing status. I have tried resync and few times restarting the client but i have every time the same result. The client thinks that we have much more blocks than reality.

I have tried parity 1.4.0 unstable, but has the completely same issue.

```
> eth.syncing
{
  currentBlock: 1787866,
  highestBlock: 1789152,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 1782999
}
```

```
> admin.peers.forEach(function(a){console.log('client:'+a.name);})
client:Ethereum(J)/v1.3.6/Linux/Release/Java/Dev
client:Geth/v1.5.0-unstable-6952fe3a/linux/go1.5.1
client:Geth/v1.4.17-stable-5a6008e0/linux/go1.7.1
client:Geth/v1.4.18-stable/linux/go1.5.1
client:Geth/v1.4.18-stable/linux/go1.5.1
client:Geth/v1.5.0-unstable-084a8ece/linux/go1.6.2
client:Geth/v1.5.0-unstable/linux/go1.5.1
client:Parity/v1.3.8-beta-e0778fc-20161015/x86_64-linux-gnu/rustc1.12.0
client:Geth/v1.4.10-stable/windows/go1.6.2
client:Geth/v1.4.18-stable-c72f5459/linux/go1.6
client:Geth/v1.4.12-stable-421df866/darwin/go1.7.1
client:Parity/v1.4.0-unstable-cceca91-20161015/x86_64-linux-gnu/rustc1.12.0
client:Geth/v1.4.18-stable-c72f5459/windows/go1.7
client:Geth/v1.4.18-stable/linux/go1.5.1
client:Geth/v1.5.0-unstable-b19b7c39/linux/go1.5.3
client:Parity/v1.3.8-beta-e0778fc-20161015/x86_64-linux-gnu/rustc1.12.0
client:Geth/v1.4.18-stable-c72f5459/windows/go1.7
client:Geth/v1.4.18-stable-c72f5459/linux/go1.7
client:Parity/v1.3.8-beta/x86_64-linux-gnu/rustc1.12.0
client:Parity/v1.3.8-beta/x86_64-linux-gnu/rustc1.12.0
client:Geth/v1.4.18-stable/linux/go1.5.1/EtherMiner_#K160320
client:Geth/v1.4.16-stable-68815256/linux/go1.7
client:Geth/v1.4.18-stable-c72f5459/darwin/go1.7
client:Geth/v1.4.18-stable/linux/go1.5.1
client:Geth/v1.4.18-stable/linux/go1.6.2
```

More logs:
https://gist.github.com/iFA88/2c3c536b5c3163f00562e8dd629a7e3c
I have activated `debug.vmodule("downloader=6")` at the ends.

**Comment by bas-vk** [comment]
> I'm synced with the Morden network, but the geth do not exists from the syncing status.

Could you explain what you mean?

> The client thinks that we have much more blocks than reality.

These numbers don't look odd to me?

**Comment by karalabe** [comment]
Yeah, so I kind of figured it out. The reason geth things we have much more blocks, is because someone actually mined a ton of blocks (3000+) on the non forked testnet. This causes fast sync to always try to sync to that chain, fail, drop the offending peer, try again. But since there are a ton of peers still persisting the old non forked testnet, there's always someone feeding junk.

This could have been avoided with a similar protective measure that we did for the dao fork, but I haven't considered it since it was obvious the main network would move forward to the fork. I didn't think the testnet would have issues with old miners.

**Comment by karalabe** [comment]
This issue should be fixed on develop now. May require a resync from zero if you got on the wrong chain before.
