### ISSUE TITLE
geth EIP 158 state clearing not effective for geth 1.4.18?

### ISSUE THREAD

**Issue by crossed1000** [ethereum/go-ethereum#3171]
#### Linux Ubuntu 16.0.1 LTS

Geth version: Note 7 1.4.18
OS & Version: Linux
Commit hash : N/a

#### Expected behaviour
States cleared, clean chain. 

#### Actual behaviour
States from DDoS still exist, chain size over 30gb. 

#### Steps to reproduce the behaviour
geth --fast from scratch

#### Backtrace
n/a
````
[backtrace]
````

Does anyone know when the EIP 158 will be effective for geth?

**Comment by karalabe** [comment]
EIP 158 is a future fork, to be announced. Even after that it will take time to clean up the state.
