### ISSUE TITLE
Geth mainnet syncing

### ISSUE THREAD

**Issue by paradise** [ethereum/go-ethereum#3181]
#### System information

Geth version: `v1.4.18-stable`
OS & Version: Linux

My geth node is syncing so slowly. Current block number is 2474698. New blocks appear faster than my node syncs. How can I solve this problem ?

`I1020 11:35:55.602922 core/blockchain.go:1001] imported 1 block(s) (0 queued 0 ignored) including 9 txs in 4m12.773601029s. #2469133 [1f93f1cb / 1f93f1cb]`
`I1020 11:41:43.213326 core/blockchain.go:1001] imported 2 block(s) (0 queued 0 ignored) including 28 txs in 5m47.610421721s. #2469135 [1f93f1cb / b139ee49]`
`I1020 11:46:58.341262 core/blockchain.go:1001] imported 3 block(s) (0 queued 0 ignored) including 44 txs in 5m15.127932881s. #2469138 [b139ee49 / 9fbe6857]`
`I1020 11:53:20.010623 core/blockchain.go:1001] imported 1 block(s) (0 queued 0 ignored) including 25 txs in 6m21.669364978s. #2469139 [9fbe6857 / 4029fecd]`
`I1020 11:59:15.411517 core/blockchain.go:1001] imported 9 block(s) (0 queued 0 ignored) including 58 txs in 5m55.400893262s. #2469148 [4029fecd / f7edc0c8]`

My `net` info
`
{
  listening: true,
  peerCount: 12,
  version: "1",
  getListening: function(callback),
  getPeerCount: function(callback),
  getVersion: function(callback)
}
`

**Comment by fjl** [comment]
We are aware of this issue and are looking for a solution at this time.

**Comment by paradise** [comment]
But how other nodes work ? Maybe somebody knows any solution ?

**Comment by karalabe** [comment]
Fast sync from scratch, use `--cache=1024` and run on top of an SSD. These allow geth to run smoothly.

**Comment by mista66** [comment]
@karalabe 

> Fast sync from scratch, use --cache=1024 and run on top of an SSD. These allow geth to run smoothly.

Tried this on several nodes none will sync seems to get stuck in a loop

**Comment by karalabe** [comment]
What is the loop? Fast sync needs to download about 30M state entries, that's quite a lot. Are you sure you wanted for it to finish?

**Comment by paradise** [comment]
I should run "geth --fast --cache 1024" until my node is synced, and then run "geth --cache 1024" ? So, in other words, first I run with `--fast`, and after sync I should remove this flag ?

**Comment by paradise** [comment]
suddenly my node become synced very fast (without resyncing and without `--fast`), have you fixed something ?
