### ISSUE TITLE
10000000000 vs 1000000000 - gas limit for the evm != GasLimit() ?

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/go-ethereum#3187]
Should these two be the same perhaps?

10000000000 vs 
1000000000

```
GasFlag = cli.StringFlag{
    Name:  "gas",
    Usage: "gas limit for the evm",
    Value: "10000000000",
}
```

https://github.com/ethereum/go-ethereum/commit/00ba7487079e42b4f73d084f3b13621332b40725#L58-L62

```
func (self *VMEnv) GasLimit() *big.Int        { return big.NewInt(1000000000) }
```

https://github.com/ethereum/go-ethereum/commit/00ba7487079e42b4f73d084f3b13621332b40725#L242

**Comment by obscuren** [comment]
No, not necessarily
