### ISSUE TITLE
mist: can't paste dapp address

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#319]
In the input field "type the address of any dapp you want", I can't paste any dapp address from the clipboard.

mist/v0.8.3/darwin/go1.4.1
commit 2c3a014

**Comment by tgerring** [comment]
I believe this is a problem with Qt5.4 and will require some custom QML events to fix

**Comment by alexvandesande** [comment]
Yes. This is a priority, I'm looking into it.

**Comment by frewsxcv** [comment]
Can confirm this issue as well

`Mist/v0.8.5/darwin/go1.4.2` with `qt 5.4.0`

**Comment by jorisbontje** [comment]
closing as mist is gone
