### ISSUE TITLE
pthread_create failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#3190]
#### System information

Geth version: `1.4.18`
OS & Version: Ubuntu 14.04

Crash reported by user. 

Some more system info: 

`cat /proc/sys/kernel/threads-max ; ulimit -s -u -v -n`

```
stack size              (kbytes, -s) 8192
max user processes              (-u) 128302
virtual memory          (kbytes, -v) unlimited
open files                      (-n) 1024
```

#### Backtrace

Full trace at
http://pastebin.com/9mUmHQ54

```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7ff6df718c37 m=2
 
goroutine 0 [idle]:
 
goroutine 1 [chan receive, 1715 minutes]:
github.com/ethereum/go-ethereum/node.(*Node).Wait(0xc82023ca00)
    /home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:492 +0x93
main.geth(0xc8203d0b40, 0x0, 0x0)
    /home/ubuntu/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:272 +0xf2
```

**Comment by axelay** [comment]
It went bang again - http://pastebin.com/YDB8WZc0

I increased the limits liks so:
`cat /proc/sys/kernel/threads-max ; ulimit -s -u -v -n`

`stack size              (kbytes, -s) 8192
max user processes              (-u) 128302
virtual memory          (kbytes, -v) unlimited
open files                      (-n) 100000
`

**Comment by fjl** [comment]
This seems to be an issue with Go 1.5. Are you using the PPA?

**Comment by axelay** [comment]
Built Geth from the source if that's what you mean

**Comment by fjl** [comment]
Which version of Go are you using?

**Comment by fjl** [comment]
You can check using `go version`.

**Comment by axelay** [comment]
I was in the middle of Ubuntu upgrade from 14.04 to 16.04
go version go1.6.2 linux/amd64

**Comment by fjl** [comment]
Please ensure that geth is compiled with Go 1.6 or ideally Go 1.7 and report whether it crashes again. We have not seen this failure before and from looking at the https://github.com/golang/go issue tracker it looks like this should be resolved in 1.6.

**Comment by axelay** [comment]
To be safe I have recompiled on Ubuntu 16.04 - Go 1.6.2
It is now running and I will let you know if any further crashes occur.

Thanks

**Comment by bas-vk** [comment]
I guess there are no crashes anymore after the recompile?
In that case could you close the issue?

**Comment by axelay** [comment]
So far so good - feel free to close
