### ISSUE TITLE
VMTests not updated after EIP150 fork

### ISSUE THREAD

**Issue by SergioDemianLerner** [ethereum/go-ethereum#3191]
A new set of VMTests JSON tests should be included, being created by the ethereum-cpp utility app. The current test set should make VMTests fail.
For instance, the test BALANCE0 in vmEnvironmentalInfoTest.json does not take into a count the re-pricing of the BALANCE opcode in EIP150.

Am I correct?

**Comment by obscuren** [comment]
The have been updated. Different branch. All tests pass.

Thanks for pointing it out though :-)

On 10/21, Sergio wrote:
> A new set of VMTests JSON tests should be included, being created by the ethereum-cpp utility app. The current test set should make VMTests fail.
> For instance, the test BALANCE0 in vmEnvironmentalInfoTest.json does not take into a count the re-pricing of the BALANCE opcode in EIP150.
> 
> Am I correct?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ethereum/go-ethereum/issues/3191

-- 
PGP Key ID = 85BE4B0C
PGP Fingerprint = EF8F A45D 7698 A065 F1AB  3D5C A676 6F71 85BE 4B0C
