### ISSUE TITLE
Add a client bindings for the JSON-RPC API.

### ISSUE THREAD

**Issue by stevenroose** [ethereum/go-ethereum#3197]
Currently, Geth serves the JSON-RPC API, but there is no way to query the API it serves using Go bindings.

Make the analogy with [btcd](https://github.com/btcsuite/btcd) that has API bindings in  [btcrpcclient](https://github.com/btcsuite/btcrpcclient).

Currently, there is a rudimentary implementation of this [here](https://github.com/FactomProject/EthereumAPI), but I believe the Ethereum project should be maintainig the bindings together with the API.

**Comment by karalabe** [comment]
Go 1.5 comes with a client implementation :)

**Comment by fjl** [comment]
The client that will ship with the 1.5 release is currently on the develop branch. You can find it in [package ethclient](https://github.com/ethereum/go-ethereum/tree/develop/ethclient).
