### ISSUE TITLE
Mining on private network not working

### ISSUE THREAD

**Issue by eyesonlyhack** [ethereum/go-ethereum#3199]
#### System information

Geth version: 1.4.18-stable
OS & Version: Ubuntu 14.04 (server edition, terminal only, no desktop)
#### Expected behaviour

Create a private network using geth within a virtual machine (VirtualBox). Setup an account and start the mining process. Should be able to mine blocks every second or two. 
#### Actual behaviour

However, mining hangs or is extremely slow. Hash-rate below 20 and is not able to mine blocks at all. 
#### Steps to reproduce the behaviour

The problem was related to a low allocation of RAM for the virtual machine. I used 800MB ram memory for virtual machine allocation. I reallocated 2GB of ram and mining worked perfectly.

Not sure how to fix this issue. Maybe a warning during the mining process that the memory allocation is too low. This will save many people a lot of pain and frustration trying to figure out what is wrong.

**Comment by AugustoL** [comment]
@eyesonlyhack can you share your genesis.json file? You can set the difficulty for the network there.

**Comment by eyesonlyhack** [comment]
The difficulty was not the problem. Here is my genesis file:

{
  "alloc": { },
  "nonce": "0x0000000000000042",
  "difficulty": "0x00400",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "timestamp": "0x00",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
  "gasLimit": "0x4c4b40"
}

**Comment by sshasan** [comment]
Hey! I also have the same Issue, I am also not able to mine when I create private network.

**Comment by 9607835** [comment]
Same issue, 681 MiB available memory, genisis.json->difficulty=0, yet each block takes ~30 minutes to mine.  The time to create each block never decreases, waiting over the weekend for adjustments to take place results in no noticeable improvement.

Only solution that has yet to work has been to do:

`sed -i 's/return CalcDifficulty(chain.Config(), time, parent)/return big.NewInt(2)/' ./go-ethereum/consensus/ethash/consensus.go`

by recompiling geth with a forced difficulty of "2", blocks now commit at a ridiculous rate of one block per second.

Conclusions:

- my platform is more than capable of mining blocks at a fast rate (thus memory is NOT the problem)
- geth has a serious bug in difficulty calculations

**Comment by holiman** [comment]
There's no such thing as difficulty 0, the minimum difficulty is `0x2000`. The difficulty calculation formula is undefined for lower values, so it's better to use PoA network in these circumstances.
