### ISSUE TITLE
Mist segfault

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#320]
If i try to type in `http://localhost:3000` in the app catalog url bar, it crashes with the following error:
(latest develop commit)

```js
a42a6d25d244ee2b3c099d3d49a6a97be0075880da66e61f5ea6a92f20b00822e142d2de68d1ca4336423816eecfd423ead012d1cb4874b9e996e7fd0dd70e354b1c58a4ac9977da65badc02b67d141c569ffc151ffe606f0cd83f24305fd782bdaf71d8
2015/02/16 15:23:27 [P2P Server] Encryption Handshake with 208.52.168.126:30303 failed: unexpected EOF
2015/02/16 15:23:27 [P2P Server] Encryption Handshake with 208.52.168.126:30303 failed: unexpected EOF
2015/02/16 15:23:27 [P2P Server] Encryption Handshake with 208.52.168.126:30303 failed: unexpected EOF
2015/02/16 15:23:27 [P2P Server] Encryption Handshake with 208.52.168.126:30303 failed: unexpected EOF
2015/02/16 15:23:46 catalog.qml:116: NavigationRequested: http://localhost:3000/ navigationType=0
2015/02/16 15:23:46 main.qml.:124: requested: localhost:3000
2015/02/16 15:23:46 main.qml.:130: exists: ethereum-dapp-catalog.meteor.com
[1]    5223 segmentation fault  mist
```

**Comment by obscuren** [comment]
When this happens again, please dump the OS X crash log

**Comment by alexvandesande** [comment]
I have the same issue. I open mist, click on any Ðapp in the catalog and it crashes. Log:


➜  mist git:(develop) mist
2015/02/16 18:22:19 [CHAIN] Last block (#0) c9cb614fddd89b3bc6e2f0ed1f8e58e8a0d826612a607a6151be6f39c991a941 TD=0
2015/02/16 18:22:19 [CLI] Main address 971669a0eab0f5e41dd2418c36e2d79e030f092e
2015/02/16 18:22:19 [RPC-HTTP] Starting RPC-HTTP server on port 8545
ETH stack took 9.819655ms
2015/02/16 18:22:19 [GUI] Starting GUI
2015/02/16 18:22:19 [CLI] Starting  Mist/v0.8.3/darwin/go1.4.1
2015/02/16 18:22:19 [P2P Server] Starting Server
2015/02/16 18:22:19 [P2P Server] Listening on [::]:30303
2015/02/16 18:22:19 [JSRE] started
2015/02/16 18:22:20 catalog.qml:116: NavigationRequested: http://ethereum-dapp-catalog.meteor.com/ navigationType=1
2015/02/16 18:22:21 [P2P NAT] mapping error: no devices discovered
2015/02/16 18:22:21 [P2P NAT] mapping error: no devices discovered
2015/02/16 18:22:21 [P2P Discovery] Listening,  enode://45bb19456cefadd1bb0769d52912ae3fd4efbc0ccf44296c08d4340be5ea40362719a1f5c37c4364ef473c738c1e18f21fb5be66cb74c0fae574451cb947981d@[::]:30303
2015/02/16 18:22:21 [Blockpool] Started
2015/02/16 18:22:21 [SHH] Whisper started
2015/02/16 18:22:21 [SERV] Server started
2015/02/16 18:22:22 catalog.qml:116: NavigationRequested: http://ethereum-dapp-whisper-client.meteor.com/chat/amsteam navigationType=0
2015/02/16 18:22:22 main.qml.:124: requested: ethereum-dapp-whisper-client.meteor.com
2015/02/16 18:22:22 main.qml.:130: exists: ethereum-dapp-catalog.meteor.com
[1]    40862 segmentation fault  mist
➜  mist git:(develop)

**Comment by tgerring** [comment]
My Mac crash log at https://gist.github.com/tgerring/58fbde1e93e00bdeaca4

**Comment by alexvandesande** [comment]
Here's my crash log: https://gist.github.com/alexvandesande/b6814023e1ad3f49f46d

If I comment out 
import QtWebEngine.experimental 1.0
and 
experimental.settings.javascriptCanAccessClipboard: true
experimental.settings.localContentCanAccessRemoteUrls: true

Then I can open new windows without any problem. Taylor doesn't reproduce this exact behaviour..

**Comment by obscuren** [comment]
Issue has been fixed in https://github.com/ethereum/go-ethereum/commit/7fc9b5b3f9ca0111cc4bc1b2a6b4bb2eccd3e048
