### ISSUE TITLE
ethclient.TransactionByHash: "too many params, want 1 got 2"

### ISSUE THREAD

**Issue by stevenroose** [ethereum/go-ethereum#3203]
#### System information

Geth version: develop branch
OS & Version: Arch Linux
Commit hash : 77560730099546b0a861754cf38abcb1140ecdc5

The method `ethclient.Client.TransactionByHash()` always responds with an error: "too many params, want 1 got 2".

The [RPC method](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionbyhash) takes one, while `TransactionByHash` also [hands a boolean value](https://github.com/ethereum/go-ethereum/blob/5bb517355e292b50d81b4abf28cb741712c13a7e/ethclient/ethclient.go#L148).

**Comment by fjl** [comment]
Fix released in 1.5.0.
