### ISSUE TITLE
how to check an eth address is valid ?

### ISSUE THREAD

**Issue by xuzhiping7** [ethereum/go-ethereum#3205]
i haven't found the api to check an eth-address is valid ~

have the func like bitcoin-core of "bool ValidateAddress(address)" ?

**Comment by karalabe** [comment]
Ethereum addresses are plain 20 bytes, anything can be in them. Since it's hard to reason about them, programs represent them as 40 character long hex strings. So every `0x<40 hex character>` is a valid Ethereum address.

**Comment by karalabe** [comment]
In the Geth 1.5 codebase if you create a common.Address form a hex string I'd imagine it would validate it's length.

**Comment by xuzhiping7** [comment]
ok ~ i see

**Comment by xuzhiping7** [comment]
hello karalabe ~

i sent some eth to an address of "0x4961aC1d43B6249bc998D611F33d42B54E31712E"

why it return me the error msg :

error":{"code":-32602,"message":"Invalid address length, expected 40 got 41 bytes"}}

i can check this address on chain:
https://etherchain.org/account/0x4961aC1d43B6249bc998D611F33d42B54E31712E%20

**Comment by karalabe** [comment]
The link you sent contains a space at the end (encoded %20). Perhaps you also inserted a space at the end of the address?

**Comment by xuzhiping7** [comment]
oh ~~ i know ~~thanks  again .

i would have a try ~!

**Comment by qyvlik** [comment]
Use this `^0x[a-fA-F0-9]{40}$`~

**Comment by TriAnMan** [comment]
@xuzhiping7 you can validate an CRC for your address
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md

**Comment by raisty** [comment]
Nice module: https://github.com/cilphex/ethereum-address/blob/master/index.js

**Comment by adyliu** [comment]
Java checker of ethereum address
https://gist.github.com/adyliu/6c5ff4d41aa0177da55f4b8b1703f54a
