### ISSUE TITLE
Fast sync reverting to regular or fast sync downloading all the blocks from the beginning

### ISSUE THREAD

**Issue by pencilvester** [ethereum/go-ethereum#3206]
#### System information

Geth version: geth version 1.4.18
OS & Version: OSX 10.12.1
Commit hash : (if `develop`)
#### Expected behaviour

After attempting a fast sync, and downloading the block receipts, headers, etc. and reaching the end of the chain, only the last blocks of the chain should be downloaded to complete the fast sync and thus, having an online node without the entire chain downloaded and spending relatively less time during the sync than with the normal sync 
#### Actual behaviour

After downloading the block receipts, headers, etc. and reaching the end of the chain (I compared it continuously to the best block in https://ethstats.net/), there was never a console output that suggested that synchronization was complete. Instead the console output started to show every block was getting downloaded starting from #2.

 I discussed this on reddit and was asked to report it here as a bug. I attach a picture of the console outputs I got:

![image](https://cloud.githubusercontent.com/assets/23082678/19737877/87d9c4fa-9bb5-11e6-8c6b-a43513a1ff76.png)
![image](https://cloud.githubusercontent.com/assets/23082678/19737886/8fae6c62-9bb5-11e6-8dd7-021ddd7feb2a.png)
#### Steps to reproduce the behaviour

~/Library/Application Support/Mist/binaries/Geth/unpacked/geth --cache 1024 --fast console
#### Backtrace

```
[backtrace]
```

**Comment by marienuac** [comment]
mine does the same thing... it just reset twice......

**Comment by karalabe** [comment]
Yes, apparently the state bloat is so huge that is always aborts eventually at the end if you don't have a very strong internet connection, which leads to geth considering it's being fed a malicious state. I'll expand this attack detection so it's more robust and doesn't give up so easily.

**Comment by marienuac** [comment]
is it possible to eventually muscle threw the ddos blocks eventually? or are all blocks since 2,3xx,xxx until now considered ddos.... i have skylake con ssd hombre

**Comment by holiman** [comment]
Yes, it's possible to slog through the attack-blocks. I've done it with a HDD, went really slow for a while, but got through it eventually. I have 32 gig ram also, which helps.
