### ISSUE TITLE
Why I have so many "malicious websites protection" warnings from Malwarebytes when I use geth wit Mist wallet?

### ISSUE THREAD

**Issue by Nogreedy** [ethereum/go-ethereum#3217]
Geth version: geth 1.14.18
OS & Version: Windows 10/64 bits

Hello,
Why I receive so many "malicious websites protection" warnings from Malwarebytes each time I use geth with Ethereum Mist wallet?

![geth-problemes-malwarebytes](https://cloud.githubusercontent.com/assets/6340683/19863765/ce384ac8-9f95-11e6-9170-0909c284f089.JPG)

![malwarebytes2](https://cloud.githubusercontent.com/assets/6340683/19863870/2ff1e512-9f96-11e6-8d2b-8fce313e14f3.JPG)

Thank you for your answer

**Comment by fjl** [comment]
geth connects to other nodes on the Ethereum peer-to-peer network. Your firewall seems to think that these are malicious connections. Please configure your firewall to accept those connections.

**Comment by marienuac** [comment]
every new geth is always suspicious by AV/antimalware, i submit mine to avast then next day or so it runs fine without needed to be excluded.
