### ISSUE TITLE
RPC eth_codeAt always returning '0x'

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#322]
After creating a contract and waiting for it to be mined:
```
2015/02/17 09:09:17 [XETH] Contract addr 4bb87064ef8cdc8b3d0d8701da492aca1f80828c
```

Requesting the code using `eth_codeAt`:
```
{'params': ['0x4bb87064ef8cdc8b3d0d8701da492aca1f80828c'], 'jsonrpc': '2.0', 'id': '8cc8af04-0220-4fad-a41f-ad5f4fc1b5c6', 'method': 'eth_codeAt'}
```

Result:
```
{u'jsonrpc': u'2.0', u'id': u'19fd44e1-2fd2-466a-b462-e30e0eada2e4', u'result': u'0x'}
```

Instead I would expect to get the code back, as documented on https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_codeat

**Comment by obscuren** [comment]
Seems to work fine here. Please double check

```
> eth.codeAt("0x6ED357A6E27559DE6E465C5D3153E241D34D6601")
<- "0x60e060020a6000350480637bb98a681461002b578063d0679d3414610039578063e3d670d71461004d57005b610033610126565b60006000f35b610047600435602435610062565b60006000f35b610058600435610104565b8060005260206000f35b80600033600160a060020a0316600052602052604060002054101561008657610100565b80600033600160a060020a0316600052602052604060002090815403908190555080600083600160a060020a0316600052602052604060002090815401908190555033600160a060020a0316600052806020527ff11e547d796cc64acdf758e7cee90439494fd886a19159454aa61e473fdbafef60406000a15b5050565b6000600082600160a060020a03166000526020526040600020549050919050565b5b60008156"
```

**Comment by jorisbontje** [comment]
Nope, still returning nothing (both with RPC and JS console), full logs:
https://gist.github.com/jorisbontje/2a49a3e85b0c1b125e90#file-ethereum-log

**Comment by obscuren** [comment]
In your trace I couldn't see any code being executed (and returned for address `4a09e4cc58e2cca132f9eb92e2887f132665d78e`) which would result in `0x`. Could this be that you're using `code` instead of `data` when supplying transaction arguments?

I'd advocate for this to be removed and use a single field. If that's the case try again using the `data` attribute

**Comment by obscuren** [comment]
I've added the `code` field in https://github.com/ethereum/go-ethereum/commit/7fc9b5b3f9ca0111cc4bc1b2a6b4bb2eccd3e048

**Comment by jorisbontje** [comment]
Works!
