### ISSUE TITLE
Synch with Ethereum Wallet 0.8.7 nevers finishes on  testnet

### ISSUE THREAD

**Issue by rahulg01** [ethereum/go-ethereum#3220]
#### System information

Geth version: `geth version` - 1.4.18-stable-c72f5459
OS & Version: Windows/Linux/OSX - Windows 10
Commit hash : (if `develop`)

#### Expected behaviour
After Ethereum Wallet(Mist) is installed, it should synch the entire blockchain.

#### Actual behaviour
The synch of entire blockchain never finishes on testnet. Tried below options:-
1) Synching it using geth console via following command:-
geth --testnet --datadir C:\Users\Rags\AppData\Roaming\Ethereum --fast --maxpeers 100 --maxpendpeers 100
2) Tried debug.setHead(1821134), but this also didn't worked.

#### Steps to reproduce the behaviour
Install "Ethereum Wallet" Version 0.8.7 and switch to TestNet. It will synch quickly until few thousand blocks are remaining. After that synching stops and we start seeing below errors in the logs. The new blocks which are created they keep on accumulating. 

#### Backtrace
E1101 17:09:20.563291 core/blockchain.go:1170] Bad block #1821134 (0xeb20b6bf51e819eed7dfeecd140b4cdb331dd7d837ae00862328b1d5b05a3a26)
E1101 17:09:20.563291 core/blockchain.go:1171]     gas used error (216168 / 219768)
I1101 17:09:22.906489 eth/downloader/downloader.go:298] Synchronisation failed: block header download canceled (requested)
I1101 17:09:29.601229 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
I1101 17:09:42.138081 eth/downloader/downloader.go:298] Synchronisation failed: block header download canceled (requested)
I1101 17:09:42.799123 eth/downloader/downloader.go:298] Synchronisation failed: block header download canceled (requested)
I1101 17:09:44.618820 eth/downloader/downloader.go:298] Synchronisation failed: block download canceled (requested)
I1101 17:09:45.596496 eth/downloader/downloader.go:298] Synchronisation failed: block header download canceled (requested)
E1101 17:09:57.124890 core/blockchain.go:1170] Bad block #1821134 (0xeb20b6bf51e819eed7dfeecd140b4cdb331dd7d837ae00862328b1d5b05a3a26)
E1101 17:09:57.124890 core/blockchain.go:1171]     gas used error (216168 / 219768)
I1101 17:10:00.063585 eth/downloader/downloader.go:298] Synchronisation failed: block header download canceled (requested)
I1101 17:10:08.317330 eth/downloader/downloader.go:298] Synchronisation failed: block header download canceled (requested)
I1101 17:10:16.635739 eth/downloader/downloader.go:298] Synchronisation failed: block header download canceled (requested)
I1101 17:10:24.011185 eth/downloader/downloader.go:298] Synchronisation failed: block header download canceled (requested)
I1101 17:10:26.101487 eth/downloader/downloader.go:298] Synchronisation failed: peer is unknown or unhealthy
E1101 17:10:30.524313 core/blockchain.go:1170] Bad block #1821134 (0xeb20b6bf51e819eed7dfeecd140b4cdb331dd7d837ae00862328b1d5b05a3a26)
E1101 17:10:30.524313 core/blockchain.go:1171]     gas used error (216168 / 219768)

**Comment by karalabe** [comment]
We are aware of this issue. After the fork someone pushed the old chain on the testnet by a lot, causing fast sync to pick that as the most difficult opposed to the forked version (there was no chain protection implemented as in the dao fork).

Current develop already syncs correctly to the good chain. If you are experimenting on the testnet only I'd suggest using that. Alternatively you can either full sinc the testnet with the stable branch (i.e. without --fast), or we'll be releasing a new version of stable to fix this possibly today, maybe tomorrow.
