### ISSUE TITLE
ethclient: missing mixHash in JSON block header

### ISSUE THREAD

**Issue by stevenroose** [ethereum/go-ethereum#3230]
#### System information

Geth version: develop branch
OS & Version: Arch Linux
Commit hash : ed2bc7fbe9a30c1861cffdd7d0fd570847a2ae0c

#### Expected behaviour
`ethclient.HeaderByNumber` should return a `*types.Header` instance

#### Actual behaviour
JSON unmarshal error: `missing mixHash in JSON block header`

**Comment by fjl** [comment]
You get this error because the server did not return all required fields.

**Comment by stevenroose** [comment]
Can this be because of an inconsistency between Parity's and Geth's JSON 
API?

**Comment by fjl** [comment]
The only server implementation that returns this field is geth 1.5.0, which is not released yet. If you are using parity please ask them to include this field in API responses.

**Comment by fjl** [comment]
This is now fixed in the parity master branch, closing.

**Comment by stevenroose** [comment]
I seem to have bumped into this again. Just started using stable Parity.

**Comment by dtco-kimi** [comment]
I have the same issue also. @stevenroose  would you mind reopen this issue again? Thanks.
Parity version: v2.0.3-beta-a0a2bed-20180831

**Comment by stevenroose** [comment]
@dtco-kimi I don't have reopen permissions, sorry. You should ask @fjl

**Comment by pstehlik** [comment]
It seems like this problem only occurs when using Parity against Kovan (POA chain). There, the field is not returned. When running Parity against ropsten it actually returns the field.
Contrary to that, geth returns `0x0` in the `mixHash` field when running against Rinkeby (also POA) thus allowing clients to rely on the field always being there.

It would be great if the go-ethereum ethclient would gracefully ignore the field not being present. I don't know if there's an easy way to distinguish between POA/POW chains and only error out when interacting with a POW chain and the field is missing. That could be a good solution.

**Comment by TwinbrotherPro** [comment]
Having the same Issue with my own POA (Parity) Network. Would be glad if the suggestion of pstehlik could be somehow implemented :)

**Comment by TwinbrotherPro** [comment]
As I am writing this I really think I should not post this, but as a quick fix you can just modify those lines in the json unmarshaller in https://github.com/ethereum/go-ethereum/blob/master/core/types/gen_header_json.go .

```
	// if dec.MixDigest == nil {
	// 	return errors.New("missing required field 'mixHash' for Header")
	// }
	if dec.MixDigest != nil {
		h.MixDigest = *dec.MixDigest
	}
	// if dec.Nonce == nil {
	// 	return errors.New("missing required field 'nonce' for Header")
	// }
	if dec.Nonce != nil {
		h.Nonce = *dec.Nonce
	}
```

A better way would be of having the possibility of creating a header type just for a POA chain which does not require Nonce and MixDigest. But I am still not in the code, yet so there might be a better way to solve this.
