### ISSUE TITLE
debug_traceTransaction not show 'out of gas'

### ISSUE THREAD

**Issue by zhumingu** [ethereum/go-ethereum#3233]
https://etherscan.io/tx/0xaee761811a9d4957faca2e01eaea806e0de9c738f91b1fb8c9e1f963a7c3a506
when run debug_traceTransaction by rpc, the result is that:
{
  "gas":21000,
  "returnValue":"",
  "structLogs":[{
      "pc":0,
      "op":"PUSH1",
      "gas":0,
      "gasCost":3,
      "depth":1,
      "error":{},
      "stack":[],
      "memory":null,
      "storage":{}
  }]
}

how can I get the run trace?

**Comment by holiman** [comment]
@Arachnid, PTAL at if this is any use to you: https://github.com/ethereum/go-ethereum/blob/286ec5df40d3707a7a2c98d49c8d324372ed29c2/internal/ethapi/tracer.go#L350
