### ISSUE TITLE
`constant` functions should not be subject to gas limit and block gas limit

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/go-ethereum#3237]
It seems that even `constant` functions are subject to the default gas limit (and probably also to the block gas limit, but I did not test that). This does not make sense to me. On my local node I should be able to spam myself as much as I choose to. If we waived the gas limit for constant functions, I could e.g. iterate arbitrarily long arrays. 

EDIT: I know that for iterating long random data I should probably rather use events and logs. But that would limit it to the access from the same contract which is fairly limiting.

**Comment by bellaj** [comment]
The compiler does not enforce yet that a constant method is not modifying state.
so the limitation should be set.

**Comment by SCBuergel** [comment]
@bellaj Would you have an issue for that? Would be nice to link this one there so that we can check again/get reminded once the compiler does enforce it.

**Comment by ethernomad** [comment]
You don't need to run constant functions in a transaction. This means there is no gas limit.

**Comment by SCBuergel** [comment]
>there is no gas limit

@ethernomad that is what I thought as well. But it turns out that is wrong (for most implementations at least), see also [my stackexchange question](http://ethereum.stackexchange.com/questions/9824/solidity-can-constant-functions-be-arbitrarily-complex).

**Comment by ethernomad** [comment]
This is just a bug in browser-solidity: https://github.com/ethereum/browser-solidity/issues/300

Constant calls not called in a transaction are free and have no limit, however this will change with the light client.

**Comment by karalabe** [comment]
Geth by default sets a gas limit of 50M if you don't specify anything as a protective measure to avoid a malicious/buggy contract causing infinite loops. You can however specify the `gas` parameter of the call as high as you want.
