### ISSUE TITLE
What's the difference between CanonStatTy, SplitStatTy, and SideStatTy?

### ISSUE THREAD

**Issue by bailantaotao** [ethereum/go-ethereum#3249]
Hi there,

I found that the variable will be used when a block try to insert transactions.
But i don't understand the difference about CanonStatTy, SplitStatTy, and SideStatTy.
I have read wiki, but it's not more information in there.
Can anyone tell me the details?

**Comment by obscuren** [comment]
Canon = Block made it in to the canonical chain
Split = Chain split, moving to new heavy chain
Side = Uncle block

**Comment by bailantaotao** [comment]
thanks! 👍
