### ISSUE TITLE
Windows: not getting new blocks (stuck at 2609182)

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/go-ethereum#3254]
I am running the latest geth 1.4.18 from github release binary on Windows 7. I synced the chain initially via `geth --fast console` and realized that my geth seems to get to know about updated blocks only very rarely despite the fact that geth is chatting a lot about incoming blocks, so this does not seem to be a connectivity issue. I am checking for new blocks via `web3.eth.blockNumer` and that number stayed constant for a very long time despite new blocks showing up in the console, see exemple below. The same behavior persists now that I am running it without `--fast`, actually it seems worse because I dont see any new blockNumber anymore:
```
> web3.eth.blockNumber
2609182
> I1111 21:59:08.754610 core/blockchain.go:1001] imported 163 block(s) (0 queued
 0 ignored) including 126 txs in 8.0125174s. #80574 [5e66bdd6 / fc3bb229]
I1111 21:59:16.758126 core/blockchain.go:1001] imported 636 block(s) (0 queued 0
 ignored) including 497 txs in 8.0035163s. #81210 [fc3bb229 / bfd7ca5a]
I1111 21:59:24.892659 core/blockchain.go:1001] imported 579 block(s) (0 queued 0
 ignored) including 350 txs in 8.134533s. #81789 [bfd7ca5a / c9dddebd]
I1111 21:59:32.909177 core/blockchain.go:1001] imported 654 block(s) (0 queued 0
 ignored) including 257 txs in 8.016518s. #82443 [c9dddebd / d612896f]
I1111 21:59:33.039693 core/blockchain.go:1001] imported 16 block(s) (0 queued 0
ignored) including 10 txs in 130.5165ms. #82459 [d612896f / a89a8504]
> web3.eth.blockNumber
2609182
```

**Comment by SCBuergel** [comment]
While looking more closely, there are two issues:

1. When restarting geth without `--fast` it seems to be re-loading the entire chain?!
2. Despite the fact that I was just on block 82459 (as reported by console output above), `web3.eth.blockNumber` still thought that I was on block 2609182.

Related to https://github.com/ethereum/go-ethereum/issues/3206 ?

**Comment by obscuren** [comment]
Closing. Please reopen if this issue persists.
