### ISSUE TITLE
proposal of setting private key path

### ISSUE THREAD

**Issue by franklili3** [ethereum/go-ethereum#3261]
Private key is the most important file, hacker usually steal the private key. So for the security of ether, I suggest setting private key path in the geth, user can set U disk as the path of private key. After user extracts U disk, there is no private key in the computer, so hacker can not steal the private key.#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
I totally support this. See https://github.com/ethereum/go-ethereum/issues/2691

**Comment by holiman** [comment]
Actually, there is already. See https://github.com/ethereum/go-ethereum/blob/master/cmd/utils/flags.go#L112 . 
```
ETHEREUM OPTIONS:
  --datadir "/home/martin/.ethereum"	Data directory for the databases and keystore
  --keystore 				Directory for the keystore (default = inside the datadir)
```

Close issue?

**Comment by karalabe** [comment]
Yep, this was added possibly in 1.5.
