### ISSUE TITLE
ethclient: "missing required JSON transaction signature fields"

### ISSUE THREAD

**Issue by stevenroose** [ethereum/go-ethereum#3269]
#### System information
OS & Version: Arch Linux
Commit hash : ca73dea3b9bcdf3b5424b5c48c70817439e2e304

#### Expected behaviour
`ethclient.Client.GetTransactionByHash(hash)` returns a Transaction object

#### Actual behaviour
Throws "missing required JSON transaction signature fields"

#### Steps to reproduce the behaviour
Fire up a JSON RPC API server that is compatible with [the JSON API specification](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionbyhash) and call the `eth_getTransactionByHash` method with an existing transaction hash.

---------------------

It appears that the develop branch is breaking compatibility with the API spec. Or is there a renewed version of the spec that I'm not aware of that develop is following?

**Comment by fjl** [comment]
Which server are you using.

**Comment by fjl** [comment]
ethclient needs the `v`, `r`, `s` fields in order to be able to reconstruct complete transactions. These fields are returned by geth 1.5.0 or later as well as parity on the master branch.

**Comment by fjl** [comment]
Can you dump the RPC response? This could also be an issue on our end.

**Comment by stevenroose** [comment]
I'm using the latest Parity (made a report [here](https://github.com/ethcore/parity/issues/3158#issuecomment-260654372) as well).

However, the API spec I mentioned does not include the r, s and v fields, so either way a server following the spec is no longer supported in v1.5.

**Comment by stevenroose** [comment]
It seems to be `ethclient.BlockByNumber(context, nil)` throwing the exception. I can't access the JSON, but I can give this:
```json
> eth.getBlock('latest')
{
  author: "0xf3b9d2c81f2b24b0fa0acaaa865b7d9ced5fc2fb",
  difficulty: 71064143929134,
  extraData: "0x426974436c756220455448204d696e696e6720506f6f6c",
  gasLimit: 2000000,
  gasUsed: 63000,
  hash: "0xecb7972419884252986933ee844c68de5ec75ceb00c6a6c01f3074bd88c89f0b",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0xf3b9d2c81f2b24b0fa0acaaa865b7d9ced5fc2fb",
  mixHash: "0x8d40e4549a66475d2b5bdcb9a8368122c82649547c2c72fb852d1c41421652ea",
  nonce: "0x9236f25b0277336d",
  number: 2632024,
  parentHash: "0x6903fbcca8c2aaa289b3b24978b4edc16a97e3635897605cfeddae2f6fb8770c",
  receiptsRoot: "0xcbd47d5efae69167bca8f00d668bdcb303f5202c4bcff292736f68bb3eb6884d",
  sealFields: ["0x8d40e4549a66475d2b5bdcb9a8368122c82649547c2c72fb852d1c41421652ea", "0x9236f25b0277336d"],
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 883,
  stateRoot: "0x01f401e8131ee051aa8666ffa277e34226cd7a79bfadb0c295a596341d8e8f75",
  timestamp: 1479220305,
  totalDifficulty: 90167044428100108886,
  transactions: ["0x2edbb63c97d33867d2772d5960577f7edf415e9d19c4530fe40850e8a21fae6a", "0xd92be3b3eeb6b5febb73bf466bd01e0afd897e31020f0d271035a3777c042fa5", "0xedb4ba74c9cf0b5811cd979e7cd2ddfe02dc8a3e46b0629da21e8bd06b568eba"],
  transactionsRoot: "0xfc669abb62188a8a51fc3951c41e746cfa01a1439d5e183ef9a1514e3c3ddf70",
  uncles: []
}
```

**Comment by stevenroose** [comment]
Btw, Geth v1.5.0 still advertises the same version of the API: 
`modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 shh:1.0 txpool:1.0 web3:1.0`

This should definitively change if breaking changes are made..

**Comment by fjl** [comment]
Looks like they will backport the fix soon.

**Comment by stevenroose** [comment]
@fjl Well, there are still issues regarding Geth and ethclient not following any specification whatsoever. As long as Geth keeps making changes without documenting a new spec, I guess ethclient will never be compatible with Parity..

**Comment by tjayrush** [comment]
I summarized seven differences between 'geth' and Parity and the documentation in this issue: https://github.com/ethereum/go-ethereum/issues/3339. I did tests against about 1,000 randomly selected blocks and found only the noted differences.

**Comment by stevenroose** [comment]
@obscuren Is this issue resolved?
