### ISSUE TITLE
Fatal: Error starting protocol stack: Missing trie node x

### ISSUE THREAD

**Issue by MitchK** [ethereum/go-ethereum#3276]
```
Geth
Version: 1.4.18-stable-c72f5459
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: darwin
GOPATH=/Users/user/go
GOROOT=/usr/local/Cellar/go/1.7.3/libexec
```

We intend to test Geth in High-Availability, but the current stability of running Geth is holding us back from doing so. Our developers complain daily about corrupted ```chaindata``` directories. We are currently on Morden network. 

Currently there are no real solutions than simply wiping out ```chaindata``` and re-downloading the whole history again. 

We keep getting errors like this (on daemon startup): 
```
Fatal: Error starting protocol stack: Missing trie node d55642bf147fcb9c74800d967d595065b01ba6766fb822344d87c87356e5fe4d
```
How can we practically prevent corruption in the first place and if it happens, how can we recover from it?

**Comment by awesomehimanshu** [comment]
I am also getting same issue

**Comment by holiman** [comment]
What is the underlying filesystem?

**Comment by bitcoinbrisbane** [comment]
Also now getting this issue.  My chain is stored on USB exFat on MacOS

**Comment by bitcoinbrisbane** [comment]
I fixed mine by removing chaindata folder.

**Comment by fjl** [comment]
Closing because this is old and likely resolved in some way or the other.
