### ISSUE TITLE
1.5.0 compile eror

### ISSUE THREAD

**Issue by BorilloB** [ethereum/go-ethereum#3277]
#### System information

OS & Version: Windows/Linux/OSX Ubuntu 14.04.5 LTS
go version go1.5.1 linux/amd64

#### Steps to reproduce the behaviour

/go-ethereum-1.5.0# make geth
build/env.sh go run build/ci.go install ./cmd/geth
internal/build/azure.go:23:2: cannot find package "github.com/Azure/azure-sdk-for-go/storage" in any of:
	/usr/lib/go/src/github.com/Azure/azure-sdk-for-go/storage (from $GOROOT)
	/go-ethereum-1.5.0/build/_workspace/src/github.com/Azure/azure-sdk-for-go/storage (from $GOPATH)
internal/build/pgp.go:27:2: cannot find package "golang.org/x/crypto/openpgp" in any of:
	/usr/lib/go/src/golang.org/x/crypto/openpgp (from $GOROOT)
	/go-ethereum-1.5.0/build/_workspace/src/golang.org/x/crypto/openpgp (from $GOPATH)
make: *** [geth] Error 1

**Comment by fjl** [comment]
This should now be fixer on master and will go into the next release.

**Comment by BorilloB** [comment]
confirm.
close.

**Comment by Kojee** [comment]
I'm having the same problem on my raspberry pi B:
 sudo make geth
build/env.sh go run build/ci.go install ./cmd/geth
build/_workspace/src/github.com/ethereum/go-ethereum/internal/build/azure.go:23:2: cannot find package "github.com/Azure/azure-sdk-for-go/storage" in any of:
        /usr/lib/go/src/pkg/github.com/Azure/azure-sdk-for-go/storage (from $GOROOT)
        /home/pi/go-ethereum/build/_workspace/src/github.com/Azure/azure-sdk-for-go/storage (from $GOPATH)
build/_workspace/src/github.com/ethereum/go-ethereum/internal/build/pgp.go:27:2: cannot find package "golang.org/x/crypto/openpgp" in any of:
        /usr/lib/go/src/pkg/golang.org/x/crypto/openpgp (from $GOROOT)
        /home/pi/go-ethereum/build/_workspace/src/golang.org/x/crypto/openpgp (from $GOPATH)
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 1

**Comment by karalabe** [comment]
What version of Geth are you building? Please post the commit hash.

**Comment by Kojee** [comment]
I reinstalled my raspbian because I messed with golang installations.
Now i get this error:
 sudo make geth
build/env.sh go run build/ci.go install ./cmd/geth
build/env.sh: 31: exec: go: not found
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 127

Where do I find the commit hash?

**Comment by tuytuy** [comment]
@Kojee have you found a solution to this ?

**Comment by karalabe** [comment]
> build/env.sh: 31: exec: go: not found

Apparently you don't have Go installed? If you want to build Geth you'll need to do that yourself. Otherwise why not grab a pre-built binary from https://geth.ethereum.org/downloads/ ?

**Comment by Kojee** [comment]
Yeah I solved it using a pre builth geth binary, sorry for not clarifying earlier.
At the time of the problem the download page https://geth.ethereum.org/downloads/ couldn't load.

**Comment by EasonWang01** [comment]
Hi,could I ask if I already install golang https://www.digitalocean.com/community/tutorials/how-to-install-go-1-6-on-ubuntu-14-04

why it still got this error,thanks.

**Comment by EasonWang01** [comment]
After I manual `go get github.com/Azure/azure-sdk-for-go/storage` 

`git clone  https://github.com/Azure/azure-sdk-for-go.git` then put it into` /usr/lib/go/src/pkg`

But another error happend...

<img width="973" alt="2017-03-07 11 16 07" src="https://cloud.githubusercontent.com/assets/11001914/23662943/1aa895b6-038c-11e7-8e5c-c2ad60c8102c.png">


<img width="970" alt="2017-03-07 11 16 17" src="https://cloud.githubusercontent.com/assets/11001914/23662949/1df90458-038c-11e7-9289-770f22302882.png">

**Comment by grmpz** [comment]
FWIW to anyone hitting this thread - I had this issue with Mint 17.3 (Ubuntu 14.04) and go 1.5.  Upgrading go to 1.7.5 fixed all the issues

**Comment by karalabe** [comment]
Go 1.5 required the GO15VENDOREXPERIMENT env var to be set to 1. (Alternatively typing 'make geth' would have set it automatically). Please note, Geth 1.6 raised the minimum requirements for Go to 1.7

**Comment by littleskunk** [comment]
I have the same problem. I followed the guide and used Go 1.7.3. Later I updated to Go 1.8. Always the same error message.
```
root@ethereum:~/go-ethereum# make geth
build/env.sh go run build/ci.go install ./cmd/geth
build/_workspace/src/github.com/ethereum/go-ethereum/internal/build/azure.go:23:2: cannot find package "github.com/Azure/azure-sdk-for-go/storage" in any of:
        /usr/lib/go/src/pkg/github.com/Azure/azure-sdk-for-go/storage (from $GOROOT)
        /root/go-ethereum/build/_workspace/src/github.com/Azure/azure-sdk-for-go/storage (from $GOPATH)
build/_workspace/src/github.com/ethereum/go-ethereum/internal/build/pgp.go:27:2: cannot find package "golang.org/x/crypto/openpgp" in any of:
        /usr/lib/go/src/pkg/golang.org/x/crypto/openpgp (from $GOROOT)
        /root/go-ethereum/build/_workspace/src/golang.org/x/crypto/openpgp (from $GOPATH)
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 1
```

**Comment by neerajkumarjha** [comment]
I fix the problem on ubuntu.
1. Open /home/.bashrc file
2. add the GO lang path 
export GOROOT=/usr/local/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH\
3. save the file
4. Open new tab 
5. navigate to go-etherium folder
6. run the command "make geth "

**Comment by abdusamed91** [comment]
I'm having the same issue on Ubuntu 16.04 when I try to do `make geth` The following error is thrown at me:
```

~/go/src/github.com/ethereum/go-ethereum$ make geth
build/env.sh go run build/ci.go install ./cmd/geth
# github.com/ethereum/go-ethereum/vendor/github.com/Azure/azure-pipeline-go/pipeline
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:49: r.GetBody undefined (type Request has no field or method GetBody)
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:58: undefined: http.NoBody
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:59: r.GetBody undefined (type Request has no field or method GetBody)
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:60: undefined: http.NoBody
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:95: undefined: http.NoBody
vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:107: undefined: http.NoBody
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 2
```

I'm updated my `~/.bashrc` with all the environmental table set for $GOROOT, $GOPATH & PATH. `go1.7.x` is tar'ed at `/usr/local/`

**Comment by karalabe** [comment]
Go 1.8.0 is the current minimum as far as I know.
