### ISSUE TITLE
eth_estimateGas returns incorrect amount for transactions with refunds

### ISSUE THREAD

**Issue by ethernomad** [ethereum/go-ethereum#3282]
For transactions that do not perform any storage clears, eth_estimateGas is always correct. If I call a transaction with storage clears with the gas amount provided by estimateGas I get the intrinsic gas too low error.

I thought this had been fixed here: https://github.com/ethereum/go-ethereum/issues/2395 but it seems to have returned.

**Comment by karalabe** [comment]
We did fix some cases but also realized that there are certain cases where it's not possible to estimate the real correct price apart from trial and error. It's a feature we'll probably implement to do a binary search based estimator. It would take more time to estimate (shouldn't matter honestly) but at least should always be correct.
