### ISSUE TITLE
Editing required for abigen for Java and runtime error for big.Int after editing.

### ISSUE THREAD

**Issue by phillyfan1138** [ethereum/go-ethereum#3286]
#### System information

Geth version: `1.5.0`
OS & Version: Windows
Commit hash : a672eae3d12359d79e39733ff80a2acf5728cf9b

#### Expected behaviour
Java class generated by abigen

#### Actual behaviour
The Java class requires modification to compile (changing the constructor and the "final" class variables) .  There is a runtime error `abi: cannot unmarshal *big.Int in to []interface {}`

#### Steps to reproduce the behaviour
abigen --abi MyAbi.abi --pkg main --lang java --out MyContract.java

**Comment by karalabe** [comment]
Hmm, must have missed something. Could you post a tiny contract that fails (so I can add it to automated tests and ensure we don't break again?)

**Comment by phillyfan1138** [comment]
When using the binary code the generator works 
`abigen --abi MyAbi.abi --bin MyContract.bin --pkg main --lang java --out MyContract.java`

A simple contract that fails when just using the abi:

`
contract MyContract{
    uint256 constant public myConstant=100000000000000000;
    address public owner;
    function MyContract(){ //owner is creator of contract
      owner=msg.sender;
    }
    function kill() {
      selfdestruct(owner); // Makes contract inactive, returns funds
    }
    function () {
        throw; // throw reverts state to before call
    }
}
`

**Comment by phillyfan1138** [comment]
Oh, the import `import org.ethereum.geth.internal.*;` still gives me an error as well.
