### ISSUE TITLE
Synchronisation failed: block download canceled (requested)

### ISSUE THREAD

**Issue by eut** [ethereum/go-ethereum#3287]
#### System information

Geth version: 1.5.0-stable-c3c58eb6
OS & Version: Linux (Ubuntu 16.04.1 amd64)
Commit hash : (if `develop`)

I1117 12:44:47.756138 eth/downloader/downloader.go:305] Synchronisation failed: block download canceled (requested)
I1117 12:44:50.653579 eth/downloader/downloader.go:305] Synchronisation failed: block download canceled (requested)
I1117 12:44:52.262909 eth/downloader/downloader.go:305] Synchronisation failed: block download canceled (requested)
I1117 12:44:54.408239 eth/downloader/downloader.go:305] Synchronisation failed: block download canceled (requested)
I1117 12:44:55.381471 eth/downloader/downloader.go:305] Synchronisation failed: block download canceled (requested)
I1117 12:44:56.020328 eth/downloader/downloader.go:305] Synchronisation failed: block download canceled (requested)

**Comment by SinErgy84** [comment]
Same here, but going on testnet.
Additional error: 
E1117 09:29:28.270271 core/blockchain.go:1212] Bad block #1783000 (0xf376243aeff1f256d970714c3de9fd78fa4e63cf63e32a51fe1169e375d98145)
 E1117 09:29:28.270299 core/blockchain.go:1213]     gas used error (219768 / 216168)

**Comment by egalano** [comment]
I'm still seeing this issue on testnet with geth 1.5.2 when I try to do a from scratch full sync.

**Comment by ropod7** [comment]
After 1.5.2 update everything goes well, but now:

Bad block #1885001 (0x46db90ca5d96b46b5ea570dfc781f7dd5faff732d25beaeab9a8bffb97ed20d2)
gas used error (376814 / 386014)
Bad block #1885001 (0x46db90ca5d96b46b5ea570dfc781f7dd5faff732d25beaeab9a8bffb97ed20d2)
gas used error (376814 / 386014)
Peer 768480fcc2900737: header #1885160 [a5cd5abd…] broke chain ancestry
Bad block #1885074 (0x83e64c4db99031a74d3d3b4a164018915063a5540713b3b637a24b4a3034dc3f)
invalid receipt root hash. received=ee6b110128bf174765fa0bff4f2148141bb223ee25c51a09bda1e0f08b7befbe calculated=c67500fbc44704935be6e0f2fe0e8f596a2636626609196feb889bebe83d37ee
Bad block #1885001 (0x46db90ca5d96b46b5ea570dfc781f7dd5faff732d25beaeab9a8bffb97ed20d2)
gas used error (376814 / 386014)

Resync interrupts on the same place. I can't working. ((

**Comment by ropod7** [comment]
3 times resync, no way. Both nodes same result.

**Comment by obscuren** [comment]
We are aware of this issue. Parity and Geth together destroyed the network. We're looking in to rebooting the testnet.

Update will follow.

**Comment by holiman** [comment]
So there are actually several issues; post-fork is fixed, but we don't know the reason for blockerrors at block `1783000`. 

@SinErgy84 , if you still haven't switched to Ropsten, could you try to start the client again with `loglevel=6` and paste relevant logs here. That way, we'd be able to see the receipts from the transactions of that block, which would help analyse the issue.

**Comment by spencermoran0** [comment]
this is happening to me with davey jones  locker update
