### ISSUE TITLE
ethclient: imports crypto/secp256k1

### ISSUE THREAD

**Issue by slothbag** [ethereum/go-ethereum#3289]
I'm trying out the new ethclient library to talk to a Geth RPC.. however when importing the github.com/ethereum/go-ethereum/ethclient package it in turn pulls in a bunch of packages including crypto/secp256k1.

This package requires gcc to compile which is a huge overhead for a simple JSON RPC client library especially on Windows where gcc support is not great,

Is it possible to remove that dependency?

**Comment by fjl** [comment]
One way to fix this would be to move types.Signer and associated code to package crypto. I'll do that if @obscuren agrees. 
 
  Original Message  
Show Details

**Comment by obscuren** [comment]
Ack

**Comment by fjl** [comment]
I have looked into this and it will require more changes:

* `Log` needs to move from `core/vm` to core/types
* `Signer` needs to move to package crypto

To remove the dependency on leveldb, DeriveSha needs to move to package core.

**Comment by slothbag** [comment]
I don't know enough about this, but what about some sort of dummy package that only imports the bare minimum for a RPC client?  Or perhaps a script that removes the crypto imports just for building an EthClient based app?

**Comment by slothbag** [comment]
So I went and installed GCC on windows and can compile the dependencies, but the problem now is each `go build` tries to compile the C code and slows down the process.

**Comment by karalabe** [comment]
Go build doesn't cache the results. Use `go install`, that will save all object files into your GOPATH so subsequent builds will be fast.

**Comment by slothbag** [comment]
I just updated to the latest go-ethereum and tried to compile without gcc and getting the same secp256k1 induced missing gcc error.

Is this on the roadmap for being addressed?

**Comment by karalabe** [comment]
Transaction signing needs to be moved out of the types package before we can get rid of the secp256k1 dependency from ethclient. It is on the roadmap for Geth 1.6, to be released in 2-3 weeks.

**Comment by fjl** [comment]
This is not stale.

**Comment by dherbst** [comment]
I think d78ad226c26c84635c60fad233de9e6e438a5599 resolved this, didn't it?
