### ISSUE TITLE
SEC-2 RPC services do not require authentication

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#329]
Any attacker with access to an RPC interface can perform sensitive operations in the context of the user without authenticating.

**Comment by frozeman** [comment]
the user confirmation windows and restriction of CORS headers to localhost should work for the beginning.

**Comment by obscuren** [comment]
Non issue. CORS is localhost and with NAT-SPEC in place there's no fooling around without the users explicit authorisation.
