### ISSUE TITLE
cmd/bzzd: "Manifest 1ff07d81 is malformed: unexpected end of JSON input"

### ISSUE THREAD

**Issue by paulperegud** [ethereum/go-ethereum#3307]
#### System information

Geth version: Version: 1.5.1-stable
OS & Version: Linux, Ubuntu 16.04.1 LTS

#### Expected behaviour
`wget -O - "http://localhost:8500/bzz:/1ff07d819f3c35674c4effc1072de7c8efcb9fb27cc77781f53b990d6b28eb0f"`
produces contents of "github.com/ethereum/go-ethereum/README.md" file. 
URL comes from http://swarm-guide.readthedocs.io/en/latest/usage.html#using-a-local-swarm-instance

#### Actual behaviour
```
$ wget -O - "http://localhost:8500/bzz:/1ff07d819f3c35674c4effc1072de7c8efcb9fb27cc77781f53b990d6b28eb0f/"
--2016-11-18 13:09:32--  http://localhost:8500/bzz:/1ff07d819f3c35674c4effc1072de7c8efcb9fb27cc77781f53b990d6b28eb0f/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8500... connected.
HTTP request sent, awaiting response... 400 Bad Request
2016-11-18 13:09:35 ERROR 400: Bad Request
```

bzz.log entry is produced:
`I1118 13:09:35.982637 swarm/api/api.go:148] loadManifestTrie error: Manifest 1ff07d81 is malformed: unexpected end of JSON input`

#### Steps to reproduce the behaviour
Add any file to bzzd/geth instance A. Attempt to download it using bzzd/geth instance B.

**Comment by maran** [comment]
Did you actually upload the readme file again? There is no telling that the hash from the example is still around and if you upload it again it's quite possible you will have a different hash.

**Comment by paulperegud** [comment]
I got the same behavior with three different files I've tried to upload on machine A and download on machine B. Both are running same version of geth (v1.5.1, compiled from repo tag) and both were fully synchronized. bzzd used one account on first machine and other on second, both with non-zero ETH balance.

**Comment by homotopycolimit** [comment]
paul, I am in the process of writing the documentation. 
The example you cite is only one day old :) Thank you for joining in.

Can you try something for me:
I am currently trying to write up how to properly connect up nodes. Maybe your nodes are not connected to each other. So can you try to do the download on the same host that you performed the upload on. Does that work?

**Comment by paulperegud** [comment]
Yes, I can download from the same node I was doing uploading at.

**Comment by paulperegud** [comment]
@maran I've tried to download README.md reuploaded by you.
```
$ wget -O - "http://localhost:8500/bzz:/b41b0bcd7cb5b3527cc8a5ee8223276a20bbc0bfd4af5cb492faa3264673e928"
--2016-11-18 14:38:19--  http://localhost:8500/bzz:/b41b0bcd7cb5b3527cc8a5ee8223276a20bbc0bfd4af5cb492faa3264673e928
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8500... connected.
HTTP request sent, awaiting response... 302 Found
Location: /bzz:/b41b0bcd7cb5b3527cc8a5ee8223276a20bbc0bfd4af5cb492faa3264673e928/ [following]
--2016-11-18 14:38:19--  http://localhost:8500/bzz:/b41b0bcd7cb5b3527cc8a5ee8223276a20bbc0bfd4af5cb492faa3264673e928/
Reusing existing connection to localhost:8500.
HTTP request sent, awaiting response... 400 Bad Request
2016-11-18 14:38:22 ERROR 400: Bad Request.
```

**Comment by paulperegud** [comment]
Update:

```
$ wget -O - "http://localhost:8500/bzz:/b41b0bcd7cb5b3527cc8a5ee8223276a20bbc0bfd4af5cb492faa3264673e928" > README.md
--2016-11-18 15:24:22--  http://localhost:8500/bzz:/b41b0bcd7cb5b3527cc8a5ee8223276a20bbc0bfd4af5cb492faa3264673e928
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8500... connected.
HTTP request sent, awaiting response... 302 Found
Location: /bzz:/b41b0bcd7cb5b3527cc8a5ee8223276a20bbc0bfd4af5cb492faa3264673e928/ [following]
--2016-11-18 15:24:22--  http://localhost:8500/bzz:/b41b0bcd7cb5b3527cc8a5ee8223276a20bbc0bfd4af5cb492faa3264673e928/
Reusing existing connection to localhost:8500.
HTTP request sent, awaiting response... 200 OK
Length: 16731 (16K) []
Saving to: ‘STDOUT’

-                                                         100%[===================================================================================================================================>]  16,34K  --.-KB/s    in 0s      

2016-11-18 15:24:22 (67,3 MB/s) - written to stdout [16731/16731]
```

**Comment by paulperegud** [comment]
It seems that this is an combination of following things:
1) low timeouts for retrieval (should probably be increased)
2) bad wording of a message (timeout is a timeout)

I suggest closing this issue.

**Comment by fjl** [comment]
I would like to repurpose this issue so it tracks the bad error message experience instead. I've been hit by this myself.

It would be nice if the HTTP endpoint returned a better, distinguishable message if 

* a timeout is reached while fetching content from the network
* the content was loaded but does not look like a manifest
* the content does not exist at all (maybe thats already handled, didn't check)

**Comment by homotopycolimit** [comment]
I have some more info on the "seeker can't seek" error message. 
It comes from https://golang.org/src/net/http/fs.go where it tells us that "seeker can't seek"
quote:  is returned by ServeContent's sizeFunc when the content doesn't seek properly. The underlying Seeker's error text isn't included in the sizeFunc reply so it's not sent over HTTP to end users.

I rewrote my local fs.go so that errors are passed through and I got: "seek from the end requires rootchunk for size. call Size first"
This is interesting in as much swarm uses the size (which is part of the info in the root chunk)  to enable seeking from the end, while in fs.go:
"ServeContent uses a seek to the end of the content to determine its size."


either way I think there was a timeout happening in the background because I found messages in my logs of the form "DPA.Get: 7246109f request time out".

I'll keep digging.

**Comment by fjl** [comment]
A bit more about timeouts: Not sure what the current value is, but you can make it very long and abort when the client connection goes away using a Context.

```go
import "golang.org/x/net/context"

// In your handler:
const defaultTimeout = 40 * time.Second
ctx, cancel := context.WithTimeout(req.Context(), defaultTimeout)
defer cancel()
value, err := doTheFetch(ctx, ...)
```

**Comment by homotopycolimit** [comment]
Here is a loglevel 6 output of bzzd when the HTTP interface just shows 'Manifest 7b822279 is malformed: unexpected end of JSON input'

```
I1207 20:37:34.302841 swarm/api/manifest.go:55] manifest lookup key: '7b822279'.
I1207 20:37:34.302982 swarm/storage/dpa.go:139] dpa: retrieve loop : chunk 7b822279
I1207 20:37:34.302997 swarm/storage/netstore.go:123] NetStore.Get: 7b82227929d8e484fdda280476c2e17e1c972d172fa3489aa7b2798a762438db hit on an existing request
I1207 20:37:37.303224 swarm/storage/dpa.go:213] DPA.Get: 7b822279 request time out 
I1207 20:37:37.303248 swarm/storage/dpa.go:142] chunk 7b822279 not found
I1207 20:37:37.303270 swarm/api/manifest.go:75] Manifest 7b822279 retrieved
I1207 20:37:37.303289 swarm/api/manifest.go:80] Manifest 7b822279 is malformed: unexpected end of JSON input
I1207 20:37:37.303299 swarm/api/api.go:148] loadManifestTrie error: Manifest 7b822279 is malformed: unexpected end of JSON input
I1207 20:37:37.303314 swarm/api/http/server.go:214] Manifest 7b822279 is malformed: unexpected end of JSON input
```

**Comment by homotopycolimit** [comment]
I have two suggestions.

1. "unexpected end of JSON iput"

In manifest.go, the readManifest function calls `size, err := manifestReader.Size(quitC)` but never checks the error. If there was an error determining the manifest size (eg chunk not found) the returned size is 0. The readManifest function the continues with a size of 0 until it stumbles at Unmarshalling the expected JSON.

Suggestion: func readManifest should begin something like this:
```
	size, err := manifestReader.Size(quitC)
        if err !=0 { // or if size == 0
                   glog.V(logger.Detail).Infof("Manifest %v not found.", hash.Log())
                   return
        }
```

2. Seeker can't seek. 
Instead of giving the error "seek from end requires rootchunk for size, call size first", the lazyChunkReader.Seek function should simply call Size in this scenario.. Example:
```
func (s *LazyChunkReader) Seek(offset int64, whence int) (int64, error) {
	switch whence {
...
...
		if s.chunk == nil { //
                        quitC := make(chan bool)
			_, err := s.Size(quitC)
			if err != nil {
				return 0, fmt.Errorf("seek from the end requires rootchunk for size. call to size failed: %v", err.Error())
			}
		}
```
