### ISSUE TITLE
SEC-4 JSON RPC interface allows all origins

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#331]
The JSON RPC server whitelists all origins in its cross origin resource header configuration: https://github.com/ethereum/go-ethereum/blob/develop/rpc/http/server.go#L89

This configuration bypasses cross origin request protections built in to most modern browsers. For example, it will allow an attacker to originate a transaction via the RPC interface if a user loads a malicious web page.

**RECOMMENDATION:**
Only whitelist trusted domains that are required for RPC interaction.

**Comment by kumavis** [comment]
What origins do we expect to talk to the RPC?
localhost is a likely one, maybe `*.ethereum.org`? That would be risky if an XSS vuln was found.
