### ISSUE TITLE
Download page fails on IE

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#3310]
[From reddit](https://www.reddit.com/r/ethereum/comments/5dlvle/geth_v152_cry_uncle_fixes_a_regression_full/da5nm5z/)

> We'll look into fixing the buttons so they don't link to builds which don't exist yet.

btw: not sure whether related to the change you were planning to implement, but I think the new "Retrieving packages from release server" code does not work with the combination {Internet Explorer 11 + Sophos}. IE hangs there forever now; whereas Firefox handles it just fine.

**Comment by karalabe** [comment]
Could someone double check this? There was a fix pushed out for some older borwsers? MAybe that was the issue for OP too?

**Comment by obscuren** [comment]
Any update on this? Can we close this down?

**Comment by ankitPagalGuy** [comment]
<img width="1439" alt="screen shot 2017-10-15 at 2 57 29 am" src="https://user-images.githubusercontent.com/17823488/31579470-afa7f000-b154-11e7-9bba-92ed41fc1a51.png">
facing a similar situation , can anyone help ?

**Comment by lancanshire** [comment]
i have the same problem. anyone can help?
![tim 20180306161404](https://user-images.githubusercontent.com/30017817/37021115-6d94caba-2159-11e8-9d5f-28762ca49948.png)

**Comment by ccpwcn** [comment]
disable your browser plugins for advertisement, adblock, adblock plus, 广告终结者 ect., then refresh you browser page(hot key F5).

**Comment by holiman** [comment]
@FrankSzendzielarz can you test this on internet exploder?

**Comment by adamschmideg** [comment]
A reason seems to be that IE is missing the `string.endswith` method.

**Comment by FrankSzendzielarz** [comment]
This works on IE 11 Win 10 no problem.
