### ISSUE TITLE
web3_sha3 method over RPC always returns the same hash for non-hex-encoded strings

### ISSUE THREAD

**Issue by ana0** [ethereum/go-ethereum#3314]
#### System information

Geth version: 1.5.2
OS & Version: Windows

#### Expected behaviour

When calling the web3_sha3 method over jsonrpc, I would expect it to return the same hash as calling web3.sha3() in the console, and for that hash to be the correct hash of the data that was sent.  

#### Actual behaviour

web3_sha3 over jsonrpc returns 

`0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`

no matter what string it is called with, but returns an accurate hash when it's called with a hex-encoded string.  

This is the same as issue [#1158](https://github.com/ethereum/go-ethereum/issues/1158) but over rpc.

#### Steps to reproduce the behaviour

Start geth with rpc enabled and use curl or something similar to make a json rpc call:

`curl -X POST --data '{"jsonrpc":"2.0","method":"web3_sha3","params":["baz(uint32,bool)"],"id":64}'`

Compare with another similar call:

`curl -X POST --data '{"jsonrpc":"2.0","method":"web3_sha3","params":["bar(fixed128x128[2])"],"id":64}'`

And finally with hex data, `"62617A2875696E7433322C626F6F6C29"` is `"baz(uint32,bool)"` in hex:

`curl -X POST --data '{"jsonrpc":"2.0","method":"web3_sha3","params":["62617A2875696E7433322C626F6F6C29"],"id":64}'`

#### Comments

I've taken a look through the source, and I'm fairly sure I know where/why this is happening - I'd be happy to look into fixing it.  I just want to check that this isn't esoteric behaviour with some purpose I don't know about.  

If this is intentional, might be nice to add something about this to the documentation.  Thanks!

**Comment by bas-vk** [comment]
According to the spec this method accepts a string. The implementation currently expects the input to be hex encoded and tries to decode it. If that fails it ignores the error en calculates the hash over an empty string.

I think it makes more sense to only accept hex encoded data instead of plain strings so an update. This actually what geth and parity currently does. I will update the spec and improve error handling.
