### ISSUE TITLE
Building Geth 1.4.19 with Chocolatey - Godep error

### ISSUE THREAD

**Issue by agnewpickens** [ethereum/go-ethereum#3316]
IBM Thinkcentre tower with 2.8GHz processor and 8GB RAM

Geth version: 1.4.19
OS & Version: Windows 7 Pro
Commit hash : (if `develop`)

#### Ran through all steps in the 1.4 Geth series wiki again and received identical error

![__godep error](https://cloud.githubusercontent.com/assets/18013756/20468595/1947ff92-af66-11e6-8838-49a43941dff7.PNG)

**Comment by fjl** [comment]
Please switch to the `release/1.4` branch before compiling.

    git checkout release/1.4

**Comment by agnewpickens** [comment]
thanks, will try that

**Comment by agnewpickens** [comment]
do I do that from the src geth directory or from my command user?

**Comment by fjl** [comment]
Please run that in `C:\Users\Wagner\src\github.com\ethereum\go-ethereum`.

**Comment by agnewpickens** [comment]
okey dokels

**Comment by agnewpickens** [comment]
what next, it has been pointed to geth 1.4, do another go get github.com/tools/godep?

**Comment by agnewpickens** [comment]
or try godep go install again?

**Comment by fjl** [comment]
It should work without another `go get` because you already have godep. Maybe try 

    godep go install -v ./...

**Comment by agnewpickens** [comment]
OK, it is compiling

**Comment by agnewpickens** [comment]
Might want to add that missing step to the wiki

**Comment by agnewpickens** [comment]
![___godeps disabled](https://cloud.githubusercontent.com/assets/18013756/20468725/8dcb65ec-af67-11e6-94f5-c34f8d09ab1f.PNG)


Godeps says it is disabled, did Geth 1.4.19 compile?  And if so where can I find it?

**Comment by fjl** [comment]
You can ignore the warning. The real error is that gcc is missing.

**Comment by fjl** [comment]
Did you install mingw?

**Comment by agnewpickens** [comment]
Yes I did, did all three choco installs.

**Comment by agnewpickens** [comment]
Geth is extracting Geth 1.4.19 stuff right now

**Comment by fjl** [comment]
Sorry, then I'm not sure what the problem is. `choco install mingw` puts gcc into PATH for me.

**Comment by fjl** [comment]
I'll upload geth 1.4.19 binaries in a few hours.

**Comment by agnewpickens** [comment]
Opened a command window in win-builds and is extracting stuff.  I ahd winbuilds open

**Comment by agnewpickens** [comment]
It said it had trouble downloading an external package after mingw install, failed 1, downloaded 0/1, GCC may have beern in that install.  Appreciate your help and look forward to builds of 1.4.19.  Not quite ready to make jump to 1.5 Geth series.  Plus 419 is my area code, :smile:

**Comment by agnewpickens** [comment]
Maybe having win-builds open tied up the GCC package, going to close it and try again

**Comment by agnewpickens** [comment]
Nope, will just wait for the build.  Thanks.  At least I got to resharpen some of my DOS command line skills.

**Comment by agnewpickens** [comment]
Was able to get choco install to download mingw package that failed after doing a manual install of MinGW on my tower.  I modified the wiki instructions you gave me to include the 1.4 release install command and everything went fine until it came time to compile build.  see 1st picture for commands I used.  I did not do the mkdir command since it already existed.
![____missing geth pkgs build](https://cloud.githubusercontent.com/assets/18013756/20501396/bc6edab4-b007-11e6-9903-10483b896fc0.PNG)

**Comment by agnewpickens** [comment]
These next 3 pictures show the rest of the pkgs godep go install -v ./... was unable to find in geth directory.
![___missing geth pkgs build 2](https://cloud.githubusercontent.com/assets/18013756/20501430/eae3d840-b007-11e6-8c50-71cebf359717.PNG)
![___missinjg geth pkga build 3](https://cloud.githubusercontent.com/assets/18013756/20501438/f092aa0a-b007-11e6-9907-84d1add3549a.PNG)
![___missing geth pkgs build 4](https://cloud.githubusercontent.com/assets/18013756/20501447/f6af4b46-b007-11e6-9221-5ed8063d1d92.PNG)

**Comment by agnewpickens** [comment]
grabbed the Geth 1.4.19 source file from go-ethereum release page, I substituted it for the one that Chocolatey fetched and now the build is going through without missing packages.

**Comment by agnewpickens** [comment]
You can see in this picture the build is compiling without error so far.  It looks like I have my Geth 1.4.19 build.
![____geth godep build success](https://cloud.githubusercontent.com/assets/18013756/20501921/da45d5ae-b009-11e6-928f-a16bfa28dc71.PNG)

**Comment by fjl** [comment]
Great. Please open another issue if there are any further problems.
