### ISSUE TITLE
Chained delegatecall causes exception (Bad jump destination)

### ISSUE THREAD

**Issue by tcimoli** [ethereum/go-ethereum#3318]
#### System information

Geth version: 1.5.2+build7930+xenial
OS & Version: Ubuntu 16.04
Solidity 0.4.2

#### Expected behaviour
When invoking function `invokeLibrary` of contract Bob, field `result` is expected to update to value `6`, due to a double `delegatecall` invocation.

#### Actual behaviour
I have tried to execute the transaction both via Wallet and  via geth, but either way the transaction throws exception. 
Here you can find Ropsten Testnet's transaction id:
0xd49138857b3d678cae37d44fac2faa351ed293348136814506ba57bea8d58ad5
With error message:
Warning! Error encountered during contract execution [Bad jump destination] 

#### Steps to reproduce the behaviour
1)Deploy contracts `Bob`, `Set` and `ChainedSet`.
2)Inject addresses using `setLibrary` so that Bob points to Set and Set points to ChainedSet.
3) Run Bob's `invokeLibrary` function

[dynLib_chained_32.txt](https://github.com/ethereum/go-ethereum/files/604215/dynLib_chained_32.txt)

Thank you.

**Comment by fjl** [comment]
This looks like an issue with the contract. @obscuren can you confirm that this is not a geth issue?

**Comment by holiman** [comment]
That's a contract issue. Bad Jump Destination is solidity mechanism used to implement `throw` . 

Also, the `delegatecall` cannot see instance-variables on other instances, just the code. So when you call `invokeLibrary()` on Bob, it calls `version` on `addr`, which is set. Then (still Bob) `delegatecall`:s `chainedVersion` on `addr` - but hey, `addr` for `Bob` is `Set`, not `ChainedSet`.
