### ISSUE TITLE
Could not coonect to node during installation in test net . 

### ISSUE THREAD

**Issue by mycripto11116** [ethereum/go-ethereum#3319]
While instaling Mist i get this issue ...Could you please help.

I tried reinsatalling several times but the same error message kept coming.

![screen shot 2016-11-22 at 8 36 36 am](https://cloud.githubusercontent.com/assets/23392662/20509719/b646366c-b090-11e6-9605-33d59b858876.png)

**Comment by bas-vk** [comment]
According to this issue https://github.com/syndtr/goleveldb/issues/104 the filesystem is corrupt.
If that is the case the only solution is to resync from scratch.
