### ISSUE TITLE
web3 getTransactionReceipt does not return a receipt if tx is pending

### ISSUE THREAD

**Issue by wighawag** [ethereum/go-ethereum#3323]
According to the spec and parity, getTransactionReceipt should return a receipt for pending tx (in that case the blockNumber and blockHash won't be defined though)

currently geth is returning null for pending tx 

This is not as expected and remove a way to access details such as gas usage for pending tx :

see : https://github.com/ethcore/parity/issues/3569

**Comment by bas-vk** [comment]
As you already mentioned in the parity issue, according to the official RPC spec there is no receipt for pending transactions. This restriction was documented before the launch of the network and almost immediately after the getTransactionReceipt was described for the first time. Afaik there is nothing wrong here.

I believe the light client has no concept of pending state. If we add support for pending receipt `eth_getTransactionReceipt` would behave different for a full and light client which is confusing.

@zsfelfoldi, @fjl, can you elaborate a bit on this?

**Comment by fjl** [comment]
I can confirm that getTransactionReceipt does not work for all transactions with the light client.
It should work for transactions that were sent through the same node.

**Comment by wighawag** [comment]
Ok, thanks for the info. I ll report back to parity then :)

**Comment by obscuren** [comment]
Looking at the responses in the linked issue, Parity doesn't seem interested in fixing their issue but rather turn it around by telling the official spec and an implementation has a bug. I'm closing this down as this is a non-issue.
