### ISSUE TITLE
Geth doesn't pick nodes from static-nodes.json, while admin.addPeer works for the same nodes

### ISSUE THREAD

**Issue by whereismynodes** [ethereum/go-ethereum#3329]
#### System information

Geth version: 1.5.2
OS & Version: Linux

#### Expected behaviour
when running
` geth --nodiscover`
geth will use the nodes from `~/.ethereum/static-nodes.json` (worked in all the previous versions)

#### Actual behaviour

Doesn't start sync, doesn't even try to connect to nodes (as seen with `--verbosity 6`). Do start sync when the same nodes added with `admin.addPeer()`

**Comment by fjl** [comment]
I think this was fixed by #3300, which is merged master branch.

**Comment by fjl** [comment]
@whereismynodes does it work with the 1.5.3 release?

**Comment by whereismynodes** [comment]
Didn't try 1.5.3, installed 1.5.4 and it works
