### ISSUE TITLE
ethclient: FilterLogs treats FilterQuery properties disjunctive

### ISSUE THREAD

**Issue by stevenroose** [ethereum/go-ethereum#3330]
When doing this example query:
```go
eth.FilterLogs(context.TODO(), ethereum.FilterQuery{
	FromBlock: 1,
	ToBlock: 1000000,
	Addresses: []common.Address{common.HexToAddress("0xF6866B2339890110907f2d275C5152C188640Dd6")},
	Topics: [][]common.Hash{{common.HexToHash("0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef")}},
})
```

The resulting logs are both all logs **involving the specified address OR involving the given topic**. This makes no sense to me, it should be  **involving the specified address AND involving the given topic**.

**Comment by obscuren** [comment]
You state correct, it should be an **AND** operation. Will look in to this.

**Comment by obscuren** [comment]
Clarification: `(addr_1 || addr_2 || addr_n) && (topic_1 && (topic_2 || topic_3) && topic_4)`

**Comment by stevenroose** [comment]
Yeah, I just have a set of addresses (which are of course disjunctive) and
one topic that should be conjunctive to the addresses.

`(addr_1 || addr_2 || addr_n) && topic_1`

**Comment by obscuren** [comment]
We've identified the issue. Addresses aren't properly passed over to the remote client. @fjl is working on a fix.

**Comment by stevenroose** [comment]
Great!
