### ISSUE TITLE
ethclient: "invalid memory address or nil pointer dereference" in BlockByNumber

### ISSUE THREAD

**Issue by stevenroose** [ethereum/go-ethereum#3331]
I have a program running that regularly checks for new blocks and looks for interesting transactions in it and for some reason at some points it panics.

Tell me if I can provide more information. I'm on commit 2c802399c3ebae86af6609c5c0a13058c1017810
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6371b7]

goroutine 23 [running]:
panic(0x81d960, 0xc42000c120)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/core/types.CopyHeader(0x0, 0xc4203ae380)
	/home/steven/gocode/src/github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/core/types/block.go:315 +0x57
github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/core/types.(*Block).WithBody(0xc4202d5320, 0xc420402a80, 0x1c, 0x1c, 0xc42044c290, 0x2, 0x2, 0x0)
	/home/steven/gocode/src/github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/core/types/block.go:453 +0x1f9
github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/ethclient.(*Client).getBlock(0xc4200f00b0, 0x7f415bcf1128, 0xc42000c608, 0x8a0aec, 0x14, 0xc4205a9560, 0x2, 0x2, 0xc420563d80, 0xc420563d80, ...)
	/home/steven/gocode/src/github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/ethclient/ethclient.go:127 +0x767
github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/ethclient.(*Client).BlockByNumber(0xc4200f00b0, 0x7f415bcf1128, 0xc42000c608, 0x0, 0xc42000c608, 0x0, 0x0)
	/home/steven/gocode/src/github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/ethclient/ethclient.go:69 +0x14e
main.(*TokenNotifier).run(0xc420202ae0, 0x28e411)
	/home/steven/gocode/src/github.com/san-lab/gastracker/tokennotifier.go:65 +0x28d
created by main.StartTokenNotifier
	/home/steven/gocode/src/github.com/san-lab/gastracker/tokennotifier.go:47 +0x2b2
```
```
2016/11/23 15:50:12 No new blocks, sleeping...
2016/11/23 15:50:14 No new blocks, sleeping...
2016/11/23 15:50:16 No new blocks, sleeping...
2016/11/23 15:50:18 No new blocks, sleeping...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x62d187]

goroutine 14 [running]:
panic(0x813080, 0xc42000c120)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/core/types.CopyHeader(0x0, 0xc420030a18)
	/home/steven/gocode/src/github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/core/types/block.go:315 +0x57
github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/core/types.(*Block).WithBody(0xc42177c1b0, 0xc4203d3020, 0x1, 0x4, 0xc4203eefa0, 0x2, 0x2, 0x0)
	/home/steven/gocode/src/github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/core/types/block.go:453 +0x1f9
github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/ethclient.(*Client).getBlock(0xc4200302a8, 0x7f9df7b16168, 0xc42000c608, 0x895623, 0x14, 0xc4203baa00, 0x2, 0x2, 0xc4218bbd78, 0xc4218bbd78, ...)
	/home/steven/gocode/src/github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/ethclient/ethclient.go:127 +0x767
github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/ethclient.(*Client).BlockByNumber(0xc4200302a8, 0x7f9df7b16168, 0xc42000c608, 0x0, 0xc42000c608, 0x0, 0x0)
	/home/steven/gocode/src/github.com/san-lab/gastracker/vendor/github.com/ethereum/go-ethereum/ethclient/ethclient.go:69 +0x14e
main.(*TokenNotifier).run(0xc4201c57a0, 0x28e6ed)
	/home/steven/gocode/src/github.com/san-lab/gastracker/tokennotifier.go:65 +0x28d
created by main.StartTokenNotifier
	/home/steven/gocode/src/github.com/san-lab/gastracker/tokennotifier.go:47 +0x2b2
```

**Comment by fjl** [comment]
I cannot reproduce this (with geth as server). Can you provide the GetBlockByNumber invocation that you did and tell me which implementation you use as the server?

**Comment by stevenroose** [comment]
I'm not entirely sure, but I think I narrowed it down to a `*tx.To()` call on a tx with this `tx.String()`: https://gist.github.com/stevenroose/3bd16aba8cfbac4cfd67d5ebc3ec6ac7

**Comment by bas-vk** [comment]
I believe I have seen this issue during the development of the hive rpc test suite and already got a path for it. When I'm back home tomorrow I will look into it.

**Comment by stevenroose** [comment]
It happens consistently at the same point in time.

**Comment by stevenroose** [comment]
So I guess this is what happens:

- everywhere `common.Address` is used, so no reference
- because contract creation transactions, you want to return `nil`, so you change the signature of `tx.To()` to `*common.Address` in order to be able to return `nil`
- however, all code around geth is designed to work with `common.Address`, so the logical reaction is to automatically dereference the `*common.Address` return
- it appears that it is `nil`, so it panics

Note that there is no documentation of the possible `nil` return.

My suggestion would be one of those, in order of most preferred first
- change the signature back to returning `common.Address` and add an `error` return value to make it clear to developers that there are cases that they should not expect an address
- clearly document that the method might return `nil` and in what cases it does that

**Comment by stevenroose** [comment]
I implemented the second one in #3366 because it does not break the API.

**Comment by fjl** [comment]
The crash in CopyHeader is not caused by tx.To() returning nil. It seems to be an issue with a particular Block. Can you log the block number for your requests and provide a block number on which Client.BlockByNumber is crashing?

**Comment by fjl** [comment]
The issue seems to be that eth_getUncleByBlockHashAndIndex returns null for a valid index.

**Comment by stevenroose** [comment]
The gist contains the transaction it used to crash on. However it was due to a dereference of a nil `*common.Address` which I didn't expect due to it not being documented. So I documented the method in #3366
