### ISSUE TITLE
v1.5.3 build err

### ISSUE THREAD

**Issue by shen-xianpeng** [ethereum/go-ethereum#3344]
centos 7

#make geth
build/env.sh go run build/ci.go install ./cmd/geth
util.go:94: git for-each-ref --points-at=HEAD --count=1 --format=%(refname:short) refs/tags: exit status 129
error: unknown option `points-at=HEAD'
usage: git for-each-ref [options] [<pattern>]

    -s, --shell           quote placeholders suitably for shells
    -p, --perl            quote placeholders suitably for perl
    --python              quote placeholders suitably for python
    --tcl                 quote placeholders suitably for tcl

    --count <n>           show only <n> matched refs
    --format <format>     format to use for the output
    --sort <key>          field name to sort on

exit status 1
make: *** [geth] Error 1

how to solve this problem

**Comment by romanick** [comment]
I have this bug too.

**Comment by romanick** [comment]
Problem can be resolved by updating your git to v2
Instructions:
http://askubuntu.com/questions/571549/git-1-7-9-5-upgrade-to-current-release-of-git-2-x-on-ubuntu-12-04

**Comment by shen-xianpeng** [comment]
solved, Thanks

**Comment by farazdagi** [comment]
- duplicate: https://github.com/ethereum/go-ethereum/issues/3342
- @shen-xianpeng consider closing the issue (since it is resolved)

**Comment by fjl** [comment]
I'll fix this on master branch. We need a git command that prints the current tag. If someone
has a suggestion for a command that works with git 1.x, please shout. ;)
