### ISSUE TITLE
Swarm: CORS during Đapp development

### ISSUE THREAD

**Issue by maran** [ethereum/go-ethereum#3350]
I've been prototyping a Đapp that will be hosted on Swarm that will interact with Swarm heavily itself. However during development I've run into a few things that could be improved to help smooth out the development cycle of Swarm powered Đapps.

When you open a Swarm hosted Đapp via Swarm (by using localhost:8500/bzz:/HASH) CORS is obviously not a problem since any interaction that that Đapp will have with the Swarm proxy will happen on the same domain.

However during the development of your Đapp you (probably?) won't be running it through Swarm. There are a couple of options that I currently consider during development.

1. You are using running and developing your Đapp in a browser directly from your local storage using the file:// protocol.

2. You are running your Đapp through a webserver that can do as much as simply serving static files such as Python's SimpleHTTPServer or a more elaborate packaging pipeline with asset compiling and hot-reloading.

Right now interacting with the Swarm from these two options is a bit of a problem. I see the following solutions.

**Specifying the CORS domain for the Swarm proxy**

This solution would be an addition to the bbzd codebase and would work for case 2. This code should work the same as the code in Geth and should probably not pose too much of a problem.

**Allow a folder's static content to be served by the Swarm proxy**

This solution would be an other addition to the bbzd codebase and should work for case 1.  I envision a `--dev-folder` flag which bbzd would serve at http://localhost:8500/dev. This would solve any CORS problems.

There are also a few workarounds that don't require any code changes for those who want to work around this problem: 

* Have a local web-server in case 2 proxy pass requests from a custom URI to your local Swarm proxy.

* Disable web security on your local browser since this is the only thing enforcing CORS to begin with.

Please let me know if any of these ideas would be a good candidate to be implemented in to Swarm and I will see what I can do.

**Comment by fjl** [comment]
I like the "cors flag for bzzd" proposal.

**Comment by zelig** [comment]
fixed in #3388
