### ISSUE TITLE
abigen java setters/constructor doesn't work on mobile

### ISSUE THREAD

**Issue by Penait1** [ethereum/go-ethereum#3371]
#### System information

Geth version: `1.5.2`
OS & Version: Android 6.0
Commit hash : (if `develop`)

#### Expected behaviour
When I want to deploy a contract on mobile I want to pass a string to the constructor like so: 
contract = CompanyContract.deploy(transactionOptions, this.ethereumClient, "test@gmail.com");

With test@gmail.com as the required parameter for the constructor. It should deploy my contract and use the parameter to init a variable.

#### Actual behaviour
It throws abi: go.Universe$proxyerror: `` abi: cannot use invalid as type string as argument and won't deploy the contract.

Also, if I try to do args.get(0).getString() after setting the string, it will crash. I tried doing that since I wanted to check if it actually set the string in the interface, but it doesn't work...

My code is like this:

```
Interfaces args = Geth.newInterfaces(1);
args.set(0, Geth.newInterface()); args.get(0).setString(companyEmail);
```

#### Steps to reproduce the behaviour
1. Create a contract with a constructor argument (for example, a string)
2. Generate the java class with abigen for the contract.
3. Try deploying the contract on Android. When you pass a string to the constructor it will generate the exception mentioned above.

**Comment by aesopwonder** [comment]
Anything on this issue? I have a very similar ABI exception

**Comment by Penait1** [comment]
I found a workaround a while ago for this if I remember correctly, but you need to tackle another 1000 problems after that. We abandoned the lite client completely since it doesn't seem to have much progress with resolving all the Android issues.

**Comment by aesopwonder** [comment]
Thanks for the response. For my project I do not necessarily need a full light client. I just need to interact with simple getter and setter on the blockchain (not deplolying anything via mobile). Could you possibly post your workaround?

**Comment by aesopwonder** [comment]
I would sincerely appreciate it, as I have already sunk weeks into this project.

**Comment by Penait1** [comment]
This is how I got it working with deploying a contract while using constructor arguments:

```
Interfaces args = Geth.newInterfaces(3);
args.set(0, Geth.newInterface()); args.get(0).setAddresses(mTransporters);
args.set(1, Geth.newInterface()); args.get(1).setBigInts(mFees);
args.set(2, Geth.newInterface()); args.get(2).setString(jsonString);
return new TradelaneContract(Geth.deployContract(auth, ABI, BYTECODE, client, args));
```
It is relevant since I had the same issue while deploying a contract with constructor arguments. I noticed that while debugging if I called args.get(0).getString() or something, it crashed my application. With this strategy I actually retrieved the value while debugging and deploying worked (Although I got an out of gas exception).

You could try the same strategy with the getters and setters, however I'm not sure it will work and my memory is a bit rusty since it's a while ago. I hope it works for you, because the next issue I ran into was a out of gas exception on the contract, and if you don't have to deploy it via mobile it hopefully works OK. Good luck!

**Comment by aesopwonder** [comment]
Thanks for the reply :) I'm curious if setString() needs to be in JSON format or not. I am attempting to set a string as well
//Setter String to Test Contract
Interfaces params = Geth.newInterfaces(1);
Interface anInterface = Geth.newInterface();
anInterface.setString("Test String");
params.set(0,anInterface);
return contract.transact(opts, "set_s", params);

**Comment by Penait1** [comment]
I don't think it has to be. The variable name is a bit confusing, but in my implementation we saved a JSON string into the string (Don't ask, I know it's bad...), so that's the only reason it's called 'JsonString'. Forgot to change that for you to avoid confusion. Should be able to put a normal string in there.
