### ISSUE TITLE
Feature request, RPC interface: debug_getStorageAt

### ISSUE THREAD

**Issue by chriseth** [ethereum/go-ethereum#3374]
For debugging purposes, it would be nice to query the full storage (or a segment of it) of a specific account at the start of a certain transaction in order to display the raw storage contents or the values of certain variables (which might be arrays):

RPC endpoint name: `debug_storageAt`
Parameter 1: `blockHashOrNumber`: string - hex encoded block hash or block number
Parameter 2: `txIndex`: integer - transaction index inside the block
Parameter 3: `address`: string - hex encoded contract address
Parameter 4: `begin`: string - hex encoded storage key range start
Parameter 5: `end`: string - hex encoded storage key range end (inclusive)
Parameter 6: `maxResults`: integer - max number of storage keys in the result

The call should return:

```
{
  complete: true, // if true, contains all storage keys inside the range with nonzero value
  storage: {
    "0x1234...34": "0x324232",
    ...
  }
}
```

The number of elements in the storage object should not exceed `maxResults`. If the range has more than `maxResults` nonzero elements in the database, the `maxResults` elements with smallest keys should be returned.

Before returning the storage results, the backend should consider the initial state of the given block and apply the effects of the first `txIndex` transactions of the block. `txIndex` is permitted to be negative, which has the same result as being zero. It is also permitted to be equal or larger than the number of transactions in the block, in which case the final state of the block is considered.

If the block hash is unknown or storage contents are unavailable, flag an RPC error.

**Comment by chriseth** [comment]
Is it possible to return the actual number of (nonzero-valued) elements in the range? It might be useful, but I guess that would be hard to do, right?

**Comment by cdetrio** [comment]
This feature was added in https://github.com/ethereum/go-ethereum/pull/14350.
