### ISSUE TITLE
Swarm: flag provided but not defined: -bzznoswap

### ISSUE THREAD

**Issue by jesuscript** [ethereum/go-ethereum#3375]
Documentation issue

#### System information

Geth version: `geth version`
```
Geth
Version: 1.5.0-unstable-ab664c7e
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: darwin
GOPATH=/Users/megatv/go
GOROOT=/usr/local/Cellar/go/1.6.2/libexec
```

OS & Version: OSX

Second command in https://swarm-guide.readthedocs.io/en/latest/runninganode.html#swarm-in-singleton-mode fails with `flag provided but not defined: -bzznoswap`. Perhaps the flag has been renamed and swap is disabled by default. Remove the conflicting flag from the docs?

also, the  first command needs `--ipcpath $DATADIR/geth.ipc \`

**Comment by fjl** [comment]
Thanks. It has been renamed to `--swap` in the 1.5.4 release.

> also, the first command needs --ipcpath $DATADIR/geth.ipc \

Which command, and what happens if this flag is not present?

**Comment by jesuscript** [comment]
the `./geth` command in https://swarm-guide.readthedocs.io/en/latest/runninganode.html#swarm-in-singleton-mode . In my case, if the IPC path is not set explicitly, the geth.ipc file gets created in the default datadir (~/.ethereum)

**Comment by zelig** [comment]
thanks @jesuscript the documentation needs updating

**Comment by zelig** [comment]
we updated the docs. thanks
