### ISSUE TITLE
RFC: Go API handling of missing items

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#3379]
This is a design question about the top-level Go API. What should API methods return if an
item (block, header, transaction, receipt) does not exist? Package ethclient returns `nil`
for the item and `nil` as the error, mirroring the RPC API.

The decision here will make its way into docs, examples, etc.

### To err or not to err

```go
head, err := client.BlockByHash(ctx, common.Hash{})
// head and err are nil
```

This looks fine at first because the non-existence of an item is a special condition that
isn't necessarily an error. But it's also easy to forget and can lead to crash-prone code
because each call must check for a nil result before using it.

An alternative solution to this is to return a non-nil error in case of non-existence.
Callers already assume that the result is not useable if the error is non-nil, which would
protect against accidental crashes where the check is missing. But it's still useful to be
able to check for this specific error (similar to `io.EOF`).

### What should the error look like

Assuming that we want to add an error for non-existence, these are our options.
 Since the API is defined as a set of interfaces and users of the API should avoid depending
on a specific implementation, the error must be defined in the top-level ethereum package.

#### ethereum.NotFound

```go
package ethereum

var NotFound = errors.New("not found")
```

This is the simplest way, mirroring `io.EOF` directly. It's easy to use:

```go
head, err := client.BlockByHash(ctx, common.Hash{})
if err != nil && err != ethereum.NotFound {
     ... 
}
// head might still be nil, but the check is explicit.
```

#### NotFound method on error

```go
package ethereum

type NotFound interface{
    NotFound() bool
}
```

This error is more cumbersome to check for, but allows placing contextual information
into the error (i.e. the message can be different depending on the implementation and
type of item).

```go
head, err := client.BlockByHash(ctx, common.Hash{})
if enf, ok := err.(ethereum.NotFound); ok && enf.NotFound() {
     // now you know
} else if err != nil {
     fmt.Println("oops", err)
}
```

This might seem pointless, but can be useful if the error is handled further up
the call stack. The standard [net package uses this style](https://godoc.org/net#Error) for special conditions.

We can even get the easy syntax back with a helper function:

```go
head, err := client.BlockByHash(ctx, common.Hash{})
if err != nil && !ethereum.IsNotFound(err) {
     ... 
}
// head might still be nil, but the check is explicit.
```

### What should it be then?

Please provide feedback and tell me about your preferred choice.

**Comment by Arachnid** [comment]
I prefer `ethereum.NotFound`, personally; as you observe, this mirrors `EOF`, and also how `leveldb` handles nonexistent keys.

**Comment by fjl** [comment]
@Arachnid sorry I was still editing, please check now

**Comment by bas-vk** [comment]
I dislike the net interface solution.

It is possible that a requested resource is actually on the network but the node cannot access it at the time. In that situation returning `nil` describes that situation the best. But I can see this leading to crashes. Therefore I'm slightly in favor of `ethereum.NotFound`.
