### ISSUE TITLE
swarm uploader should take optonal argument to to empty path

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#3380]
#### System information

Geth version: 1.5

#### Expected behaviour

$ bzzup --default /path/to/index.html --recursive
123abc....

should assign path/to/index.html to the empty path resulting in 
bzzi://123abc..../
to resolve to that.

#### Actual behaviour

when uploading a directory to swarm, bzzup does not currently assign anything to the root, ie. 
creates no manifest entry with empty path that would then map the roothash or domain to a content
(similar to index.html -> "" rewrite rules

**Comment by homotopycolimit** [comment]
I just saw this. I wrote a similar issue about (optionally) generating an index.html whenever we do not specify one ourselves:
https://github.com/ethereum/go-ethereum/issues/3401
