### ISSUE TITLE
Missing "error" value for debug_traceTransaction

### ISSUE THREAD

**Issue by mtbitcoin** [ethereum/go-ethereum#3381]
This appears related to https://github.com/ethereum/go-ethereum/issues/3233

The result of the debug_traceTransaction for transactions with errors now returns '{}' instead of the actual error

{
"gas":21000,
"returnValue":"",
"structLogs":[{
"pc":0,
"op":"PUSH1",
"gas":0,
"gasCost":3,
"depth":1,
"error":{},  <--- missing error description/text
"stack":[],
"memory":null,
"storage":{}
}]
}

**Comment by 3esmit** [comment]
Blockchain explorer need this to show rinkeby transaction error.
