### ISSUE TITLE
Homebrew package missing bzz* commands

### ISSUE THREAD

**Issue by axic** [ethereum/go-ethereum#3395]
The homebrew package is missing the bzz* commands. Would it be possible to include them?

**Comment by zelig** [comment]
@karalabe @fjl ?

**Comment by zelig** [comment]
@axic is this still an issue?

**Comment by axic** [comment]
@zelig it is, but took matters into my hand 😉

**Comment by axic** [comment]
This is obsolete now, as these commands are replaced by the single `swarm` command.
