### ISSUE TITLE
how does geth nodes coordinate with each other if they have different time setting (question)

### ISSUE THREAD

**Issue by hievan2016** [ethereum/go-ethereum#3396]
If some peers has different time settings, seems they will stop and tell clients to sync the time, right?

In this case, can they still get the txs to process from other peers?

**Comment by karalabe** [comment]
The discovery protocol is time dependent. This was added as a protective measure. Hence if the clocks are not synced to a maximum of ~30 second drift from each other, the nodes will never find each other, so they will not be able to do any data exchanges.

Manually adding one peer to the other (or configuring via a static peer) might get over this limitation. Although I agree that having the concept of time in the protocol is ugly, it's not something easy to get rid of.

**Comment by hievan2016** [comment]
Thanks for your explanations!
