### ISSUE TITLE
bzzup: trailing slash breaks uploader

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#3397]
when endpoint is specified via the `bzzapi` options, trailing slash should be ignored.
Currently a non-semantic slash misbehaves, and an incorrect manifest is output.

```
./bzzup --bzzapi http://swarm-gateways.net/ ballot.sol.meta
uploading file ballot.sol.meta (1391 bytes)
uploading manifest
{
  "entries": [
    {}
  ]
}
```

**Comment by jmozah** [comment]
https://github.com/ethereum/go-ethereum/pull/3414
