### ISSUE TITLE
bzzup: output confusing

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#3398]
bzzup output is very confusing 
it says it uploaded a manifest that is displayed but it does not represent a manifest just an adhoc json structure with hash corresponding to the uploaded manifest. the entry is the entry in that manifest

Desired output in both recursive and file case is just the hash and nothing else

**Comment by homotopycolimit** [comment]
> Desired output in both recursive and file case is just the hash and nothing else

maybe with an option to output the manifest as json file

**Comment by fjl** [comment]
I added the JSON output so that users could see which files were uploaded in recursive mode
and refer to them using bzzr URLs. The output is informational and does not represent a real
manifest. Would it make sense to document it in this way?

**Comment by homotopycolimit** [comment]
> The output is informational and does not represent a real manifest

in this case would it not be better to format it for humans directly? why use JSON notation?

What I had meant was more of a "--output=manifest.json" as an option to save the manifest file locally (again for informational purposes). This may be redundant if we have better default output information.

**Comment by fjl** [comment]
I want to note that I'm not arguing against any change to bzzup output.
I used JSON as output format because it's possible to machine-transform it if desired (using [jq](https://stedolan.github.io/jq/) or similar tools. Pretty-printed JSON is pretty readable for humans
too.
