### ISSUE TITLE
Implement bounded 256 bit int

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#340]
https://github.com/jonasnick/eth-neg-value-tx is calling for fixed size integers. The first implementation of this package will use the `x = x & 1 << 256 - 1` to limit all operations.
- [ ] Create a new package with bounded arithmetic
  - [x] `Add` / `Sub` / `Mul` / `Div` / `Mod`
  - [x] `Set` / `SetString`
  - [x] `Uint` / `Int`
  - [x] `Cmp`
- [ ] Replace `big.Int` through out the implementation
- [ ] Support new package in `rlp.Read / Write`

**Comment by Ch3ck** [comment]
Hi @obscuren I'm interested in working on this feature. What else is required at the moment?
