### ISSUE TITLE
bzzd should have attach and account subcommands

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#3400]
in order to be fully self-contained in a docker container bzzd command should provide subcommands, crucially account and attach 

ideally the bzzup and bzzhash commands should also be reworked as subcommands
and probably the executable should just be named swarm
@fjl?

**Comment by fjl** [comment]
IMHO bzzd should not have an account subcommand. The long term idea on my end is to remove reliance on the keystore from bzzd. Users should supply a key file or let bzzd generate the swarm account key. It already accepts a key file and you can use that to set up an instance in docker. 

I have similar feelings about attach: if you want to attach you can use geth attach or node.js. Adding bzzd attach just adds one more feature that we need to preserve. We already regret having geth attach.

Merging executables is your choice but I kind of like the separation personally.

**Comment by homotopycolimit** [comment]
>  or let bzzd generate the swarm account key

yeah. I think that's mainly the idea.

> I have similar feelings about attach

Attach is useful for injecting commands in a running docker container. Right now for our testnet swarm on azure we include the geth executable in the containers for the sole reason of being able to inject commands with "geth --exec='cmd' attach ipc:/path/bzzd.ipc 
Wouldn't it be nice if we could do that without geth?
