### ISSUE TITLE
Non-working URL in project home page

### ISSUE THREAD

**Issue by wiseeker** [ethereum/go-ethereum#3404]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Home page of this project under section "Download Stable Binaries" is sending users to https://geth.ethereum.org/download/. But, this page is a 404.

#### Actual behaviour
Link should send users to a working page where stable binary can be downloaded.

#### Steps to reproduce the behaviour
1. Visit project home page (https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows)
2. Click on https://geth.ethereum.org/download/ url

#### Backtrace

````
[backtrace]
````

**Comment by fjl** [comment]
Thanks, fixed.
