### ISSUE TITLE
Geth binary install killed Windows PATH

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#3406]
#### System information

Geth version: v1.5.4
OS & Version: Windows 10 Pro x64 (Version	10.0.14393 Build 14393)

#### Expected behaviour
Append PATH

#### Actual behaviour
Overwrite PATH

#### Steps to reproduce the behaviour
Download and install:
https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.5.4-b70acf3c.exe

I ran the exe for install, installed to "C:\Ethereum\Geth" and now my Windows System PATH is configured as "C:\Ethereum\Geth"

**Comment by fjl** [comment]
Sorry. We'll fix it for the next release.
