### ISSUE TITLE
Transactions between two nodes hosted on the same machine

### ISSUE THREAD

**Issue by avi613** [ethereum/go-ethereum#3409]
#### System information

Geth version: 1.5.4-stable
OS & Version: Windows 10

#### Expected behaviour
When I create two nodes **on two different hosts**, i can send ethers from one node to the other.
Now when I create two nodes **on the same host**, i expect to be able to send ether from noe node to the other.

#### Actual behaviour
When the two nodes are hosted on the same machine, i fail to send ethers from one to the other.

Questions:
1. is this an exptected behaviour?
2. if yes, why?

**Comment by bas-vk** [comment]
There should not be a difference but there are some caveats. I assume you are setting up a private network.

First thing to check is that both nodes are connected. If not set up a boot node or add them manually with `admin.addPeer(enode)`.

Second, if only 1 of the nodes is mining and the transaction was sent from the other node there is a known issue that transaction are not accepted by the miner. Nodes start by default under the assumption they are not synchronized with the network. When not synchronized the node won't accept transactions since these transaction might already be included in the chain. After a node has imported a block from the network it assumes its synchronized and starts accepting transaction. Solution for now is to enable mining on both nodes.

**Comment by avi613** [comment]
Great!

Thx for your feedback!

**Comment by avi613** [comment]
@bas-vk 

I've tried what you suggested. I run two nodes on the same host. I start mining with say node 1. However, when i start mining node 2, I'm getting a nasty "panic" message, stating an out of memory exception.

Here is how I run the nodes:

First I initiate a node

```
geth -verbosity 3 --datadir="./data/01" init genesis.json console 2>> .\data\01\private_block_01.log
```

Then I actually run it

```
geth -verbosity 3 --datadir="./data/01" --networkid 7412 --ipcdisable --port 30301 console 2>> .\data\01\private_block_01.log
```

The second node is ran the same way on a different port (30302).

Node 2 just stops when i start mining.

Here is the exception I get:

```
I1214 17:41:31.700437 vendor/github.com/ethereum/ethash/ethash.go:259] Generating DAG for epoch 0 (size 1073739904) (0000000000000000000000000000000000000000000000000000000000000000)
panic: ethash_full_new IO or memory error

goroutine 163 [running]:
panic(0xc47cc0, 0xc043c36a50)
	C:/go/src/runtime/panic.go:500 +0x1af
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash.(*dag).generate.func1()
	C:/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash/ethash.go:273 +0x695
sync.(*Once).Do(0xc043c15ba0, 0xc0422d5be0)
	C:/go/src/sync/once.go:44 +0xe2
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash.(*dag).generate(0xc043c15b80)
	C:/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash/ethash.go:277 +0x53
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash.(*Full).getDAG(0xc042295410, 0x254, 0xc042362668)
	C:/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash/ethash.go:333 +0xa7
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash.(*Full).Search(0xc042295410, 0x1378600, 0xc0440a41b0, 0xc043c97260, 0x1, 0x0, 0x0, 0x0, 0x0)
	C:/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash/ethash.go:338 +0x7b
github.com/ethereum/go-ethereum/miner.(*CpuAgent).mine(0xc043c5c6e0, 0xc04225c0e0, 0xc043c97260)
	C:/gopath/src/github.com/ethereum/go-ethereum/miner/agent.go:113 +0x13d
created by github.com/ethereum/go-ethereum/miner.(*CpuAgent).update
	C:/gopath/src/github.com/ethereum/go-ethereum/miner/agent.go:82 +0x15a
```

I've seen on github that it's a known issue.

Any idea?

**Comment by obscuren** [comment]
It's likely that your system does not have memory for the DAG (requires 2gb).
