### ISSUE TITLE
Command line option --vmodule doesn't override --verbosity value

### ISSUE THREAD

**Issue by zuuner** [ethereum/go-ethereum#3418]
#### System information
Geth version: 
Version: 1.5.4-stable
Git Commit: b70acf3c5bd335d8dedc2a5aa6eff05c4c32105e
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7
OS: linux

#### Expected behaviour
When --verbosity set to 6 then user should be able to silence some modules with --vmodule <pattern>=<level> , where level < 6

#### Actual behaviour
higher --verbosity value seems to override --vmodule's lower value

#### Steps to reproduce the behaviour
geth --verbosity 6 --vmodule core/tx_pool*=3

**Comment by fjl** [comment]
This is intended behaviour so far. The highest level always wins. Implementing the logic you want is possible, but would make glog even more complicated than it already is.
