### ISSUE TITLE
SEC-7 Negative Value Transactions

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#342]
https://github.com/jonasnick/eth-neg-value-tx

https://github.com/ethereum/go-ethereum/blob/develop/vm/vm.go#L675

Related issue: https://github.com/ethereum/go-ethereum/issues/340

**Comment by obscuren** [comment]
Partially fixed in: https://github.com/ethereum/go-ethereum/commit/655e94259765b02454df93205a30a271103de5a0

WIP arith: https://github.com/ethereum/go-ethereum/issues/340

**Comment by Gustav-Simonsson** [comment]
Re-opening since the fixes for this are still WIP. Let's keep it open until we have the relevant types / types validations fully fixed including working tests.

**Comment by obscuren** [comment]
Even though the fix is not optimal, this issue is fixed
