### ISSUE TITLE
Bitchin' tricks - error in script on wiki page

### ISSUE THREAD

**Issue by mjackson001** [ethereum/go-ethereum#3420]
On the wiki for this project, the script for mining only when there are transactions fails sometimes, particularly when running 'truffle migrate'.  It can be fixed for the truffle case by changing the line:

if (eth.getBlock("pending").transactions.length > 0) {

to:

if (eth.pendingTransactions.length > 0) {

The former call returns 0 sometimes even when eth.pendingTransactions.length > 0.

The URL is here: https://github.com/ethereum/go-ethereum/wiki/bitchin-tricks

**Comment by fjl** [comment]
Thanks, updated.
