### ISSUE TITLE
No Access-Control-Allow-Origin in the RPC response

### ISSUE THREAD

**Issue by louisabraham** [ethereum/go-ethereum#3422]
#### System information
    Geth
    Version: 1.5.4-stable
    Protocol Versions: [63 62]
    Network Id: 1
    Go Version: go1.7.3
    OS: linux
    GOPATH=
    GOROOT=/usr/lib/go

#### Expected behaviour
Have a Access-Control-Allow-Origin header according to the `--rpccorsdomain` parameter.

#### Actual behaviour
No such header.

#### Steps to reproduce the behaviour
Launch the RPC interface, then make a GET or POST request.

#### Backtrace

See the question on [StackExchange](http://ethereum.stackexchange.com/questions/10622/why-is-access-control-allow-origin-not-in-the-response-headers)

**Comment by louisabraham** [comment]
There is in fact no issue. Thanks Badr Bellaj!

**Comment by bellaj** [comment]
you are welcome 👍
