### ISSUE TITLE
Probleme synchronisation

### ISSUE THREAD

**Issue by cchouse** [ethereum/go-ethereum#3443]
Hello,

I installed GO ETHEREUM on Ubuntu 16.04 lts but the synchronization does not move anymore from block 2283333 could you help me?

**Comment by obscuren** [comment]
Which version of `geth` are you running? (`geth version`)

**Comment by cchouse** [comment]
Hello 

I've used this tuto to install GO 

https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu

**Comment by fjl** [comment]
Please run `geth version` and post the output here.
