### ISSUE TITLE
swarm config file options take precedence over command line arguments

### ISSUE THREAD

**Issue by nagydani** [ethereum/go-ethereum#3444]
this is a potential [volunteer pickup task](https://github.com/ethereum/go-ethereum/labels/I)

#### System information

Geth version: 1.5.5
OS & Version: Linux

#### Expected behaviour

In case of differing numbers after ```--bzznetworkid``` command line argument and ```NetworkID``` 
field in ```config.json```, the one in the command line should be used.

#### Actual behaviour

The network id in configuration cannot be overridden on the command line.

#### Steps to reproduce the behaviour

Start ```swarm``` with one network id and then start it with another. Observe that in both cases, the first network id is used.

**Comment by nolash** [comment]
See if this fixes it? [https://github.com/nolash/go-ethereum/commit/b520d7caa5f8a3307559db245974f0243b7908fd](https://github.com/nolash/go-ethereum/commit/b520d7caa5f8a3307559db245974f0243b7908fd)

**Comment by nolash** [comment]
Ah, resolved already I see. Never mind then.

**Comment by jmozah** [comment]
aahhh.. i accidently deleted my repo which had my original pull req... giving it again.
