### ISSUE TITLE
error pages support for swarm http API

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#3447]
current error messages are largely a relic from prePOC codebase.
We need to support error pages (possibly branded).

chunker join and connection errors should all be coded.
The http api matches the code with an http status code (may need non-standard)
and serves the corresponding error page in the manifest 
falling back to an errors manifest specified via flag 
or falling back to error pages in the code 

The error pages should respect Accept headers

* [ ] error types spec
* [ ] error types -> status codes spec
* [ ] error types represented within swarm manifest
* [ ] formats types represented within swarm manifest
* [ ] implement format/status/source driven error handling
* [ ] implement error types in depo (should wait for network rewrite https://github.com/ethereum/go-ethereum/issues/2960)
* [ ] proper documentation

**Comment by zelig** [comment]
http://swarm-gateways.net/bzz:/880c31fd0221a1f65281e0c08b0e524aa360b74b91046dc97829e5ace599f37b/
"chunk 0-4096 not found"
and the raw version: http://swarm-gateways.net/bzzr:/880c31fd0221a1f65281e0c08b0e524aa360b74b91046dc97829e5ace599f37b/
"swarm-gateways.net unexpectedly closed the connection.
ERR_CONTENT_LENGTH_MISMATCH"

http://swarm-gateways.net/bzz:/6f9ae10774b767d80074d6d95d29e2a233c9767a61c37fcb375a1362df0254cb/
"Manifest 6f9ae107 is malformed: unexpected end of JSON input"
and the raw version: http://swarm-gateways.net/bzzr:/6f9ae10774b767d80074d6d95d29e2a233c9767a61c37fcb375a1362df0254cb?content_type=text/plain
seeker can't seek

**Comment by homotopycolimit** [comment]
we no longer have "seeker can't seek" and "unexpected end of JSON input" but we still need better errors for:

 * Manifest entry for '' not found
 * Manifest not found (is it a retrieval error or an ENS error?)
 * ERR_INCOMPLETE_CHUNKED_ENCODING -- what is this and why do we keep getting it?
 * ERR_CONTENT_LENGTH_MISMATCH -- why do we get this?
