### ISSUE TITLE
swarm default value --bzznetworkid incorrect

### ISSUE THREAD

**Issue by nolash** [ethereum/go-ethereum#3456]
#### System information

Geth version: `1.5.6-unstable`
OS & Version: Linux 4.4.0-45-generic

#### Expected behaviour

Invoking swarm without --bzznetworkid flag should select network 3, as defined by default in swarm --help.
(note that my config.json in $DATADIR says NetworkId 3)

#### Actual behaviour

Log outputs:
I1216 12:58:18.345522 errs/errors.go:98] [BZZ] ERROR: NetworkId mismatch: 322 (!= 3)

#### Steps to reproduce the behaviour

Invoke swarm with and without --bzznetworkid 3

**Comment by zelig** [comment]
the error line shows REMOTE (!= LOCAL) so it seems there are people running nodes with 322 as networkid (i guess trying out private swarms) and you cannot connect to them.
I close as there is no bug other than the documentation maybe being ambiguous

**Comment by fjl** [comment]
It's probably related to https://github.com/ethereum/go-ethereum/issues/3444
