### ISSUE TITLE
Ubuntu PPA: Wrong swarm dependency installed on Ubuntu 16.04

### ISSUE THREAD

**Issue by d10r** [ethereum/go-ethereum#3457]
#### System information

Geth version: 1.5.5-stable
OS & Version: Ubuntu 16.04.1 LTS
Using the PPA https://launchpad.net/~ethereum/+archive/ubuntu/ethereum

#### Expected behaviour

The latest run of `apt upgrade` should have installed the swarm package.

#### Actual behaviour

Another package named "swarm" was installed: http://packages.ubuntu.com/xenial/swarm

#### Solution

My understanding of the [Debian policy](https://www.debian.org/doc/debian-policy/ch-binary.html) is that the only solution is to find another name for the package.

**Comment by 5chdn** [comment]
Just want to say that `swarm` is the name of the binary in ArchLinux when installing `geth`.

- https://www.archlinux.org/packages/community/x86_64/geth/

It might be that the maintainer (ping @tensor5, is that you?) is not aware that 

    install -Dm755 -t "${pkgdir}"/usr/bin build/bin/*

also installs the `swarm` binary. That said, the `geth` package is in community repository, while the _agent-based models_ `swarm` is _just_ in user repository, so way down in the hierarchy.

**Comment by tensor5** [comment]
@5chdn, yes I'm aware that the geth package installs the `swarm` binary;  I wasn't aware that there is a swarm package in AUR, but it still has zero votes, so chances it will go in [community] soon are low.

**Comment by linagee** [comment]
Same here. Ubuntu 16.04 also. Forced the correct .deb in place, but still kinda of a gotcha for anyone who doesn't know what's going on with their packages.

Solved by going here: http://ppa.launchpad.net/ethereum/ethereum/ubuntu/pool/main/e/ethereum/

Download the correct swarm .deb file that matches your go-ethereum.

`sudo dpkg -i swarm_1.6.0+build9491+xenial_amd64.deb`

You should see a line like: "Unpacking swarm (1.6.0+build9491+xenial) over (2.1.6-1) ..."

I'm sure this can be fixed with some sort of Debian pinning magic or just change the package name to an unused name.

**Comment by karalabe** [comment]
I think we've asked @zelig to address this a few times. I'll try to sort this out for 1.6.1. It's unfortunate that there's the name clash, but it's something we have to rename unfortunately.

**Comment by lmars** [comment]
I think the `swarm` package should be renamed to `ethereum-swarm`.

**Comment by lmars** [comment]
We (the Swarm team) would like to rename the Swarm Ubuntu package to `ethereum-swarm` to avoid this conflict.

@karalabe what is needed to make this change?

/cc @zelig

**Comment by 5chdn** [comment]
Hm... `eswarm` maybe?

**Comment by nonsense** [comment]
`swarm` package has been renamed to `ethereum-swarm`.

However we kept the name of the binary `swarm`, so in case you have had `swarm` debian package installed, you would have to first uninstall it, in order to use `ethereum-swarm`.

**Comment by nonsense** [comment]
Additional discussions at https://github.com/ethereum/go-ethereum/issues/17295 and https://github.com/ethereum/go-ethereum/issues/17305
