### ISSUE TITLE
windows:go-ethereum compile failed

### ISSUE THREAD

**Issue by maiiz** [ethereum/go-ethereum#3458]
#### System information

OS & Version: Windows 10 x64

#### Expected behaviour
```
package main
        imports github.com/ethereum/go-ethereum/internal/build: use of internal package not allowed
```

#### Actual behaviour

compile success like linux only with make command

#### Steps to reproduce the behaviour

1. download the source code.
2. do like the `build/env.sh` set the  environment variable

my environment variable below
```
GO15VENDOREXPERIMENT=1
GOROOT=C:\GO
GOPATH=e:\go-ethereum\build\_workspace
```

3. run command in the Makefile
```
 go run build/ci.go install cmd/geth
```

4. show like this
```
package main
        imports github.com/ethereum/go-ethereum/internal/build: use of internal package not allowed
```

**Comment by fjl** [comment]
Please use the [compile instructions for Windows](https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows) as documented on the wiki.

**Comment by maiiz** [comment]
@fjl
i do as the wiki,but not work
```
interfaces.go:27:2: cannot find package "golang.org/x/net/context" in any of:
        C:\Users\maiiz\src\github.com\ethereum\go-ethereum\vendor\golang.org\x\net\context (vendor tree)
        C:\tools\go\src\golang.org\x\net\context (from $GOROOT)
        C:\Users\maiiz\src\golang.org\x\net\context (from $GOPATH)
```
only i do this before
```
go get -u -v golang.org/x/net/context
```
so the ` instructions for Windows` should add this command

and i also have question, i want debug go-ethereum. not just compile, but i don't find the doc...

**Comment by aminnagpure** [comment]
> Please use the [compile instructions for Windows](https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows) as documented on the wiki.

that has nothing important, i checked it and tried to compile but i get error 
backend.go:38:2: use of internal package github.com/ethereum/go-ethereum/internal/ethapi not allowed
exit status 1

**Comment by dillonharlessNHRMC** [comment]
I can't figure this out... @aminnagpure did you ever get it working?

**Comment by FrankSzendzielarz** [comment]
I am now hitting this issue. Can't identify what changed...
