### ISSUE TITLE
Swarm default output is far too verbose 

### ISSUE THREAD

**Issue by homotopycolimit** [ethereum/go-ethereum#3461]
In default verbosity, the swarm daemon produces a torrent of useless information.
Especially the "bzz.hive" kademlia table takes up too much space in the logs.

Suggestions: Change the log-level in kademlia.go. The Kademlia routing table should be at the level of debug information:
```
@@ -117,7 +117,7 @@ func (self *Kademlia) DBCount() int {
 // On is the entry point called when a new nodes is added
 // unsafe in that node is not checked to be already active node (to be called once)
 func (self *Kademlia) On(node Node, cb func(*NodeRecord, Node) error) (err error) {
-       glog.V(logger.Warn).Infof("%v", self)
+       glog.V(logger.Debug).Infof("%v", self)
        defer self.lock.Unlock()
        self.lock.Lock()
 ```

**Comment by gbalint** [comment]
@homotopycolimit this is already solved in https://github.com/ethereum/go-ethereum/pull/3787

IMHO it can be closed.
