### ISSUE TITLE
swarm: trouble loading manifest entries whose key ends in a slash '/'

### ISSUE THREAD

**Issue by homotopycolimit** [ethereum/go-ethereum#3467]
#### Expected behaviour
If a manifest has an entry for 'path/' and its hash is HASH, I should be able to retrieve entry for path/ by accessing:
localhost:8500/bzz:/HASH/path/

#### Actual behaviour

I get the error message: Manifest entry for 'path' not found.

#### Steps to reproduce the behaviour
Try it out on http://localhost:8500/bzz:/81a7cbc7fa2467e3a4efd0c9f590f5c4c1abaf396e50bb3bd0ca7e4aba7f22de/js/

You can see that the manifest has a 'js/' entry by loading it directly:
http://localhost:8500/bzzr:/81a7cbc7fa2467e3a4efd0c9f590f5c4c1abaf396e50bb3bd0ca7e4aba7f22de/?content_type=text/plain

**Comment by homotopycolimit** [comment]
Notes from gitter discussion on the difference between URLs ending in / and ones that don't

```
we had other problems where if we called localhost:8500/theswarm.eth the site
wouldn't work while calling it as localhost:8500/theswarm.eth/ did work ...
the problem was that relative URLs in the html would be interpreted differently in both cases.
The solution was for swarm to always add a trailing / in the URL bar.
Since then we cannot distinguish [between URLs ending in / and ones without] .
[...]
We could change the default entry property in a manifest. Instead of saying what the
empty path should resolve to, we say what the empty path should redirect to
(another entry in the same manifest).
So that the empty path can redirect to /index.html
of course a manifest could have an empty entry '' and an entry for '/' .... but I suppose that's ok
```

So. **Suggestion:** The default (i.e. empty-key) entry in a Manifest should not resolve to a hash but to another entry in the manifest. The http interface should treat this as a 302 redirect. 
`{"path":"", "target":"/index.html","type":"redirect"}`

**Suggestion 2:** The default upload functions on the console and `swarm up` should add an entry for '/' which functions in (almost) the same way as the empty-path entry. [I say almost because here we don't need it to be a redirect, we just need it to load the other entry directly.] 
`{"path":"/", "target":"/index.html","type":"direct"}`

**Comment by holisticode** [comment]
I believe this issue has been resolved? @homotopycolimit

**Comment by homotopycolimit** [comment]
I don't know. I know a lot of '/' handling has changed, but I also know that '/' handling keeps coming up over and over as a problem.
I think @jmozah might know more.

**Comment by nonsense** [comment]
@homotopycolimit I think this is working as expected now.
