### ISSUE TITLE
Error message inaccurate when querying future block.

### ISSUE THREAD

**Issue by danfinlay** [ethereum/go-ethereum#3483]
#### System information

Geth version: 1.5.5
OS & Version: Linux (Infura)
Commit hash : Not Sure

#### Expected behaviour

When querying items like `eth_getBalance` or `eth_getTransactionCount` with a block number in the future, I would expect either the `latest` state, or an error.

#### Actual behaviour

the returned value seems mal-formed:
`{"jsonrpc":"2.0","id":1482348034196178,"result":"\u003cnil\u003e"}`

#### Steps to reproduce the behaviour

```
curl 'http://127.0.0.1:8545' -H 'Origin: http://localhost:7357' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Referer: http://localhost:7357/development/test.html' -H 'Connection: keep-alive' --data-binary '{"id":14834196178,"jsonrpc":"2.0","params":["0xf414ca28e61abc7ad7d9b09a2c10de6573cc41ee","0x990799"],"method":"eth_getBalance"}' —compressed
```

#### Backtrace

I'm not sure what this means, I was using a remote node (Infura), I don't have console output for this command.

#### Other Notes

[Parity also seems to be behaving oddly for this edge case](https://github.com/ethcore/parity/issues/3939), might be a nice opportunity to coordinate a consistent behavior for it.

Originally discovered [through MetaMask](https://github.com/MetaMask/metamask-plugin/issues/945).

**Comment by shbli** [comment]
What I found out is that

in headerchain.go line 379 is actually true and returning nil
	if hash == (common.Hash{}) {
		return nil
	}

I am still figuring out how to return an error here, I am not sure how to create a proper error message if someone can point out, otherwise I'll keep looking
