### ISSUE TITLE
swarm download subcommand to implement recursive directory download from manifests

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#3489]
In the spirit of moving away from RPC API for swarm we are putting functionality either to command line or http proxy.

Recursive download to a directory (traversing a manifest) is provided by RPC `bzz.donwload`
the implementation of the downloader is https://github.com/ethereum/go-ethereum/blob/master/swarm/api/filesystem.go#L178

Since access to the local filesystem should not be allowed via HTTP, download to local disk should be supported via the `swarm down` subcommand.

also see the effort in #3488

**Comment by nolash** [comment]
@zelig I could have a look at this, but I'm not able to make another fork, and the one I made is tied up with the first PR. Could you give me a quick nudge whether it's ok I start to work on this, and we can fix the fork/PR protocol once the other one is freed up?

**Comment by lmars** [comment]
The current plan is to expose a tar stream from the HTTP API, leading to something like:

```
$ swarm down | tar -x -C some/dir
```

This then delegates things like preserving on-disk file permissions to `tar`, and you can then also just use `curl`:

```
$ curl -H "Accept: application/x-tar" <gateway>/bzz:/<manifest> | tar -x -C some/dir
```

We need to do some prerequisite work to add more file metadata to manifest entries (i.e. size, timestamps etc.).

We should also consider accepting a tar stream as a way to upload directory trees, for example:

```
$ tar -c -C some/dir | curl -X POST -H "Content-Type: application/x-tar" --data-binary @- <gateway>/bzzr:/
```

**Comment by zelig** [comment]
@lmars as we  discussed, this is a very good plan. I would love to see this implented ;)

**Comment by lmars** [comment]
The API is in place to make this possible (you can download a manifest as a tarball using an `Accept: application/x-tar` HTTP header), someone just needs to implement `swarm download`.

Given this is a feature rather than a bug, perhaps it should be moved over to ethersphere?

/cc @gbalint

**Comment by gbalint** [comment]
@lmars I agree, see: https://github.com/ethersphere/go-ethereum/issues/320
