### ISSUE TITLE
Homestead gas reprice fork hash mismatch

### ISSUE THREAD

**Issue by hievan2016** [ethereum/go-ethereum#3497]
#### System information

Geth Version: 1.5.4-stable
Git Commit: b70acf3c5bd335d8dedc2a5aa6eff05c4c32105e
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.5.4
OS: Linux ubuntu 14.04

#### Expected behaviour

Succeed to sync with the latest public network

#### Actual behaviour

Blockchain sync failed with following error.

BTW, this issues is said to be fixed in v1.5.2, however, it still showed up for geth v1.5.4

  This release fixes a regression that caused geth to fail to full sync past the previous (EIP150) hard fork at block number 2463000."

  URL : https://github.com/ethereum/go-ethereum/releases/tag/v1.5.2

I1215 03:56:06.416640 core/blockchain.go:1047] imported 13 blocks,    27 txs (  0.938 Mg) in    9.180s ( 0.102 Mg/s). #2459860 [8fed2f6b… / 3185e82d…]
I1215 03:56:06.509813 core/blockchain.go:1047] imported 32 blocks,    48 txs (  0.887 Mg) in  93.172ms ( 9.518 Mg/s). #2459892 [3185e82d… / 30f83b95…]
I1215 03:56:14.816718 core/blockchain.go:1047] imported 729 blocks,  1392 txs ( 40.176 Mg) in    8.000s ( 5.022 Mg/s). #2460621 [2bfc6a5b… / 55cfcfab…]
I1215 03:56:22.721189 core/blockchain.go:1047] imported 1319 blocks,  4160 txs (121.831 Mg) in    7.904s (15.413 Mg/s). #2461940 [55cfcfab… / 29cd9988…]
E1215 03:56:28.686381 core/blockchain.go:1231]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: false EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}

Number: 2463000
Hash: 0x329733afbd38dc2a5af78f3a57f7f8fc39ecfa06f4a0441261ca831d13f360f5

Error: Homestead gas reprice fork hash mismatch: have 0x329733afbd38dc2a5af78f3a57f7f8fc39ecfa06f4a0441261ca831d13f360f5, want 0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0
##############################
E1215 03:56:31.135102 core/blockchain.go:1231]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: false EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}

Number: 2463000
Hash: 0x329733afbd38dc2a5af78f3a57f7f8fc39ecfa06f4a0441261ca831d13f360f5

Error: Homestead gas reprice fork hash mismatch: have 0x329733afbd38dc2a5af78f3a57f7f8fc39ecfa06f4a0441261ca831d13f360f5, want 0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0
##############################
E1215 03:56:40.550595 core/blockchain.go:1231]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: false EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}

Number: 2463000
Hash: 0x329733afbd38dc2a5af78f3a57f7f8fc39ecfa06f4a0441261ca831d13f360f5

Error: Homestead gas reprice fork hash mismatch: have 0x329733afbd38dc2a5af78f3a57f7f8fc39ecfa06f4a0441261ca831d13f360f5, want 0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0
##############################
E1215 03:56:42.586866 core/blockchain.go:1231]
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: false EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}

Number: 2463000
Hash: 0x329733afbd38dc2a5af78f3a57f7f8fc39ecfa06f4a0441261ca831d13f360f5

#### Steps to reproduce the behaviour

Build a geth of version 1.5.4, and sync using this cmd

/home/hdchain_dir/geth --datadir=/home/hdchain_dir/data  --rpc --oppose-dao-fork --rpccorsdomain="*"  

#### Backtrace

````
[backtrace]
````

**Comment by dbblackdiamond** [comment]
I almost the same issue as @hievan2016 . We are running a private chain and mining stopped today as we reached block 2463000 with this error message ` Invalid header on mined block: Homestead gas reprice fork hash mismatch: have 0x88afff5e99d7851bc0a88b5786db0dfe0f0346c9363646797fbb88ec1cbee5e4, want 0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0` . I am running 1.5.8-stable and the command to start geth is `go-ethereum/build/bin/geth --nodiscover --cache=4096 --rpc --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "db,eth,net,web3,personal,debug,txpool" console`.

Any idea?
