### ISSUE TITLE
Swarm: need tools to update/manipulate manifests

### ISSUE THREAD

**Issue by homotopycolimit** [ethereum/go-ethereum#3498]
Swarm manifests are easily created using the `bzz.upload` and `swarm up` commands. 

They are however very difficult to update / manipulate. Currently, if I want to fix a typo on a swarm website, I will fix the typo, then re-upload the offending html file and all the javascript, css, images, videos, pdfs and other assets contained in the site. 

What we need is a tool that makes it easy to:

Update an entry in a manifest.
Add an entry to a manifest.
Remove an entry from a manifest.

Note also that this may require recursively changing sub-manifests.

**Comment by homotopycolimit** [comment]
I'm imagining something like:
`swarm update MANIFEST set KEY HASH`
`swarm update MANIFEST add KEY HASH`
`swarm update MANIFEST remove KEY`

Also, special care should be taken when updating the default entry... If the default entry has the same hash as index.html, we should always update both together.

**Comment by jmozah** [comment]
1) original: http://localhost:8500/bzzr:/effc43b825047839840578a14b45f8f3237be4cc10c0c47c76090f19c7918f24?content_type=text/plain
2) added a new entry:
http://localhost:8500/bzzr:/d117141d0d301bde4bb7ccff71df5725bbd24234ae85ead4260f25004c373906/?content_type=text/plain
3) modified the hash of added entry
http://localhost:8500/bzzr:/3b5a992bd2283017e25a953b9c4eb450d2e81b5ca497e931e90ba1cd23a5887e/?content_type=text/plain
4) removed the added entry:
http://localhost:8500/bzzr:/effc43b825047839840578a14b45f8f3237be4cc10c0c47c76090f19c7918f24/?content_type=text/plain

**Comment by jmozah** [comment]
https://github.com/jmozah/go-ethereum/commit/18bf7ba0238f069162b62e945065e9e6e7ef2fad

**Comment by jmozah** [comment]
https://github.com/ethereum/go-ethereum/pull/3572

**Comment by jmozah** [comment]
Added recursive manifest manipulation

-------------------------------------
1)  Create a Manifest 
http://localhost:8500/bzzr:/a1fcb74734626e98af0122edb9f68e0e3f09c237bf6f3b41294fd545f339343a?content_type=text/plain
2) Add a field
http://localhost:8500/bzzr:/7d990cac9f6274fa47a900c1da9e36dfa5d3388078bad4f8719be033a133cd65?content_type=text/plain
3) Delete the same fields
http://localhost:8500/bzzr:/7686e29aed6ac35a22b1aecffe1c71797a2b7d83fa6f3d9405970ad4fe6080c4?content_type=text/plain

Now 1 and 3 should be equal.. but 1 is having "status" field extra...

**Comment by jmozah** [comment]
New [pull request](https://github.com/ethereum/go-ethereum/pull/3645) added
 - made as 1 commit
 - commit message as per repo rules
 - tested and added recursive links
