### ISSUE TITLE
swarm: implement status page and upload page etc.

### ISSUE THREAD

**Issue by homotopycolimit** [ethereum/go-ethereum#3499]
In the spirit of moving more functionality into the http interface, swarm should implement the following:

- `localhost:8500/version` -- showing swarm version information
- `localhost:8500/favicon.ico` -- returning the swarm favicon. (/favicon.ico is the most common not-found request)
- `localhost:8500/status`  -- showing status information, connected peers, storage space used etc.

Further more, in the would-be-nice category:
- `localhost:8500/up` -- web interface for uploading / managing content (i.e. the http version of `swarm up`)
- `localhost:8500/admin` -- admin interface to change things like maxpeers, BucketSize, ethapi, SWAP settings etc. etc.

**Comment by homotopycolimit** [comment]
moreover, we should have a special page for '/' i.e. localhost:8500/ and not just an error message.

**Comment by jmozah** [comment]
Along the same lines...some page to show local files in swarm, their chunk details etc will be great

**Comment by zelig** [comment]
I support this.

@fjl wanted to implement a health page (basically your status, which is better name i think). Not sure where its at.

I would prefer to keep all these suggestions as separate issues. 
They all have different problems and use cases. Especially the up and admin UIs.

But most importantly, I would like a principled solution here. 
* My first idea would be to go along the lines of https://github.com/ethereum/go-ethereum/issues/3447 to support branded gateways.
* the server should be format sensitive (respect the Accept header). 
The client should only support json structured output 
* a command line option can be supplied pointing to a local directory or a manifest hash, which is then used to render the htmls. 
* by default it would just render json as text for html requests.

**Comment by homotopycolimit** [comment]
@zelig I believe there are two different issues here. 
One issue is to format error pages coming from requests to bzz or bzzr requests --- things like 404s and "Manifest entry for X not found" (and the related question of rendering manifests as discussed in comments here https://github.com/ethereum/go-ethereum/issues/3401)

The other issue does not concern errors from accessing any bzz:/X url but instead constitute *additional* pages the http interface can provide such as /status and /admin
I agree that there are all separate, but perhaps the first PR could provide basic scaffolding for such pages in general, i.e. the part than any special pages must have in common like: "catch special URL requests and pass them to appropriate handler functions". Along with dummy implementations of some (like /admin ), basic implementation of others (like /status) and full implementations of others (/version and /favicon.ico).

Then later specialised PRs would replace the dummy and placeholder pages with ones that have more polish/functionality.

Does that make sense? Admittedly maybe the workflow as it appears in my head is not actually the most practical for people with experience. All feedback welcome :)

**Comment by zelig** [comment]
I support this.

@fjl wanted to implement a health page (basically your status, which is better name i think). Not sure where its at.

I would prefer to keep all these suggestions as separate issues. 
They all have different problems and use cases. Especially the up and admin UIs.

But most importantly, I would like a principled solution here. 
* My first idea would be to go along the lines of https://github.com/ethereum/go-ethereum/issues/3447 to support branded gateways.
* the server should be format sensitive (respect the Accept header). 
The client should only support json structured output 
* a command line option can be supplied pointing to a local directory or a manifest hash, which is then used to render the htmls. 
* by default it would just render json as text for html requests.

**Comment by zelig** [comment]
@homotopycolimit
I agree they are two different issues, i am just saying i would like a parallel solution in terms of confgurability of what is displayed and format sensitivity of requests.
Lets break down this into appropriate smaller issues.

**Comment by holisticode** [comment]
Swarm handles incoming messages checking the scheme (bzz, bzzi, bzzr). In this context there is the notion of "invalid scheme". In order to address the above proposals, probably either we need to abandon the notion of "invalid scheme" (or we'd first have to check that a provided request URI contains a handled action (`version`, `status`), or we could introduce a new scheme, e.g `bzzl` (bzz local), in order to keep this general behavior @lmars @homotopycolimit @zelig

**Comment by holisticode** [comment]
A few other options I could think of:
* Check the request URI **before** parsing the URI for the scheme (breaks current flow a bit)
* Introduce a separate socket endpoing (e.g. 8051) for things like `status`, `admin` and `up` (

Another question: should there be some authentication for "write" endpoints like `admin` and `up`?

**Comment by lmars** [comment]
Given there are many different use cases, it may be worth implementing this as some form of handler / plugin system.

For example, either on the command line or in the config, you can register "handlers" which are separate programs listening on their own TCP or Unix sockets which can intercept and handle HTTP requests to the gateway:

```
swarm \
  --http-handler /status:http://localhost:8000 \
  --http-handler /admin:~/.ethereum/bzz-admin.ipc
```

then, going to `/status` will get forwarded to `http://localhost:8000` and `/admin` to the Unix socket `~/.ethereum/bzz-admin.ipc`.

Another option is to register paths to programs, and they are booted and there is some standard API for handing over requests to them:

```
swarm \
  --http-handler /status:/usr/local/bin/swarm-status-daemon \
  --http-handler /admin:/usr/local/bin/swarm-admin-daemon
```

I'm just trying to design something that is flexible enough that different people can have different status / admin / branded pages on their gateway without needing to fork the swarm codebase.

**Comment by justelad** [comment]
closing in favour of:
https://github.com/ethersphere/go-ethereum/issues/159
https://github.com/ethersphere/go-ethereum/issues/158
