### ISSUE TITLE
Fast sync does not import logs

### ISSUE THREAD

**Issue by ethernomad** [ethereum/go-ethereum#3500]
#### System information

Geth
Version: 1.5.5-stable
Git Commit: ff07d54843ea7ed9997c420d216b4c007f9c80c3
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.7

#### Expected behaviour

After performing a fast sync old logs should be available.

In the original pull request https://github.com/ethereum/go-ethereum/pull/1889 says:

> The resulting databases contain the entire blockchain (all blocks, all uncles, all transactions), every transaction receipt and generated logs, and the entire state trie of the head 1024 blocks. This allows a fast synced node to act as a full archive node from all intents and purposes.

#### Actual behaviour

Logs from blocks that were imported via the "fast" method are not available.

This is a major disadvantage to fast sync. Can it be made an option?

Thanks

**Comment by slothbag** [comment]
Just stumbled across the same issue.  Couldn't find out why Geth did not have earlier logs but Parity did.. turns out once I removed the DB and resync'd without --fast I then had all the logs.

**Comment by karalabe** [comment]
They should definitely be available. If not, something's broken. I'll look into it.

**Comment by bas-vk** [comment]
Maybe there is some kind of relation with https://github.com/ethereum/go-ethereum/issues/3502. On my local machine I get all logs independent if the node was synced with fast sync or not.

**Comment by fjl** [comment]
@ethernomad in https://github.com/ethereum/go-ethereum/issues/3563#issuecomment-273250721, you linked to a reddit post claiming that logs are missing after fast sync. Did you open this issue speculatively? Can you verify that running `geth --fast` imports logs correctly on your machine?
