### ISSUE TITLE
Empty BlockchainHead returned

### ISSUE THREAD

**Issue by safeith** [ethereum/go-ethereum#3504]
I run Ethereum with this command

geth --fast --cache=512 --unlock dae251a771a980028b2c6b11f1da34785c035cb5 --password /root/password --rpc

And run btcrelay-fetchd with this command

python fetchd.py -s 0xdae251a771a980028b2c6b11f1da34785c035cb5 -r 0x41f274c0023f83391de4e0733c609df5a124c3d4 -n btc --rpcPort 8545 --fetch -d --gasPrice 200000000000

But i get this out put

fetchd using PyEPM 1.0.2
feeVTX: 0
feeRecipient: 0xdae251a771a980028b2c6b11f1da34785c035cb5
Empty BlockchainHead returned.
Retry in 1min

I am using Ubuntu 16.04.1 LTS, Installed Ethereum form PPA

Best Regards

**Comment by bas-vk** [comment]
I saw that you also created an issue in the btcrelay-fetchd repo. If the people behind btcrelay can explain what is causing this error and if its caused by geth please update the issue so we can take a look.

**Comment by safeith** [comment]
no body answered in  btcrelay-fetchd but i found this comment in it that i think help

-----------------
    # loop in case contract stored correct HEAD, but reorg in *Ethereum* chain
    # so that contract lost the correct HEAD.  we try 3 times since it would
    # be quite unlucky for 5 Ethereum reorgs to coincide with storing the
   # non-orphaned Bitcoin block
------------------------
Then I think problem can be from Ethereum

**Comment by bas-vk** [comment]
There is a gitter channel https://gitter.im/ethereum/btcrelay where you can ask for help.
It would help if they can explain what is causing this and if its indeed an issue with geth.
