### ISSUE TITLE
Mobile client not working - Permission denied

### ISSUE THREAD

**Issue by nandinicbit1981** [ethereum/go-ethereum#3509]
#### System information

I followed the documentation :
https://github.com/ethereum/go-ethereum/wiki/Mobile-Clients:-Libraries-and-Inproc-Ethereum-Nodes
Geth version: `1.5.0`
OS & Version: Android
Commit hash : 

#### Expected behaviour
Should be able to see the logs as mentioned above

#### Actual behaviour
01-03 15:04:53.268 2993-2993/ether.shop.ethpocandroid W/System.err: java.lang.Exception: listen udp :0: socket: permission denied
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at go.Seq.throwException(Seq.java:52)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at org.ethereum.geth.Node.start(Native Method)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at ether.shop.ethpocandroid.MainActivity.onCreate(MainActivity.java:31)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at android.app.Activity.performCreate(Activity.java:6237)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at android.os.Looper.loop(Looper.java:148)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-03 15:04:53.269 2993-2993/ether.shop.ethpocandroid W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-03 15:04:53.278 2993-3169/ether.shop.ethpocandroid D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true

#### Backtrace

````
[backtrace]
````

**Comment by nandinicbit1981** [comment]
Fixed by adding internet permissions

**Comment by karalabe** [comment]
You might want to take a look at https://github.com/ethereum/go-ethereum/wiki/Mobile%3A-Introduction
