### ISSUE TITLE
Presale wallet import reports wrong balance

### ISSUE THREAD

**Issue by onepremise** [ethereum/go-ethereum#3513]
I've never been able to import my presale wallet. I've got a long thread via email from helpdesk@ethereum.org. Everything went through Ethan, but I can no longer reach him or anybody else there for help. I opened a ticket a while back with mist and waited for a fix, but it never worked:

https://github.com/ethereum/mist/issues/1053

I tried importing directly from geth as well. I encountered no issues:

geth-darwin-amd64-1.5.5-ff07d548$ ./geth wallet import ~/Downloads/ethereum
ethereum-wallet-1d5a74fb6e85780fb741d13a8677d99fe7e726f1 (1).json  ethereum_wallet_backup (1).json                                    
ethereum-wallet-1d5a74fb6e85780fb741d13a8677d99fe7e726f1.json      ethereum_wallet_backup.json                                        
geth-darwin-amd64-1.5.5-ff07d548$ ./geth wallet import ~/Downloads/ethereum
ethereum-wallet-1d5a74fb6e85780fb741d13a8677d99fe7e726f1 (1).json  ethereum_wallet_backup (1).json                                    
ethereum-wallet-1d5a74fb6e85780fb741d13a8677d99fe7e726f1.json      ethereum_wallet_backup.json                                        geth-darwin-amd64-1.5.5-ff07d548 $ ./geth wallet import ~/Downloads/ethereum-wallet-1d5a74fb6e85780fb741d13a8677d99fe7e726f1.json 
Passphrase: 
Address: {1d5a74fb6e85780fb741d13a8677d99fe7e726f1}

#### System information

Geth version: `1.5.5`
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour

should read a positive balance of Ether.

#### Actual behaviour

Reports 0.00 Ether.

#### Backtrace

````
[backtrace]
````

It seems there could be a possibility that my funds were never transferred. Like I said early, I had a long thread of emails a while back with the initial presale. Once I started having problems trying the import, they stopped responding. I even contacted Ethan directly. However, he only responded once to my email, saying he would look into it, and them I never heard back from him again. I don't know what else to do at this point.

**Comment by Souptacular** [comment]
I am working on this. If you haven't already, you will be receiving an email from me.
