### ISSUE TITLE
Error in this wiki page: https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts

### ISSUE THREAD

**Issue by dbblackdiamond** [ethereum/go-ethereum#3520]
#### System information

Geth version: 1.5.5 stable
OS & Version: Linux
Commit hash :  Don't know

#### Issue
I am trying to deploy a contract from an application written in Go and I have tried to follow this wiki: https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts

but it doesn't work. A number of functions don't seem to exist anymore, such as the NewRPCBackend and NewIPCClient. NewIPCClient seems to have been replaced with DialIPC, but I can't figure out what the NewRPCBackend function has been replaced with. The wiki should probably be updated with the new functions.

Thanks a lot,
Bertrand.

**Comment by karalabe** [comment]
Yeah, we're aware of some out of date infos. I'll try to split this page up too in a similar way as the mobile APIs to add more infos.

**Comment by ChristianKniep** [comment]
Hey there, same problem here.
I repaced `NewIPCClient` with `rpc.Dial(".ethereum/geth.ipc")`, but I fall as well over `backends.NewRPCBackend(conn)`. 

Kinda stuck here, any solution yet?

Thx for your work; fun to hack with... :)

**Comment by dbblackdiamond** [comment]
Hi @ChristianKniep,

`backends.NewRPCBackend(conn)` is now actually implemented as part of the `ethclient` structure/object.  The way to get it to work is to run `client = ethclient.Dial("http://x.x.x.x:8545")` and then pass the `client` value to your contract constructor function as the `ethclient.Client` implements `bind.ContractBackend`. I hope it makes sense. If not, please share your code and I'll show you how to make it work.

**Comment by cp2017** [comment]
Hola @dbblackdiamond,

I want to subscribe to the event of a contract that is called when a certain contract is called.
```
pragma solidity ^0.4.0;

contract monitorContract {
    
    struct monitorInfo {
        address buyerAddress;  // could change this into other address
        bytes32 serviceUrl;
    }
    
    uint public monitorInfoCount;
    
    mapping(uint => monitorInfo) public monitorResults;
    
    event newMonitorRecord(address buyerAddress, bytes32 url);
    
    function monitor (address buyerAddress, bytes32 url) returns (uint monitorIndex) {
        monitorInfoCount += 1;
        monitorResults[monitorInfoCount].buyerAddress = buyerAddress;
        monitorResults[monitorInfoCount].serviceUrl = url;
        newMonitorRecord(buyerAddress, url);
        return monitorInfoCount;
    }
}
```
I want to mimic what is done here: https://github.com/cp2017/monitoring-event-listener

**Comment by ChristianKniep** [comment]
Hola @dbblackdiamond,

I want to subscribe to the event of a contract that is called when a certain contract is called.
```
pragma solidity ^0.4.0;

contract monitorContract {
    
    struct monitorInfo {
        address buyerAddress;  // could change this into other address
        bytes32 serviceUrl;
    }
    
    uint public monitorInfoCount;
    
    mapping(uint => monitorInfo) public monitorResults;
    
    event newMonitorRecord(address buyerAddress, bytes32 url);
    
    function monitor (address buyerAddress, bytes32 url) returns (uint monitorIndex) {
        monitorInfoCount += 1;
        monitorResults[monitorInfoCount].buyerAddress = buyerAddress;
        monitorResults[monitorInfoCount].serviceUrl = url;
        newMonitorRecord(buyerAddress, url);
        return monitorInfoCount;
    }
}
```
I want to mimic what is done here: https://github.com/cp2017/monitoring-event-listener

**Comment by dbblackdiamond** [comment]
@ChristianKniep : i don't know how to subscribe to events from a Go program. That is on my to-do list for next. I first looked into this as I wanted to interact with a smart contract directly from Go, without having to use the javascript interface, but I haven't figured out how to subscribe to events yet.

**Comment by fjl** [comment]
Events are not supported yet. We're working on it.

**Comment by Freyert** [comment]
Apparently client does not implement bind.ContractBackend anymore? 
```
./main.go:96:60: cannot use conn (type *ethclient.Client) as type bind.ContractBackend in argument to tparty.NewOwnership:
	*ethclient.Client does not implement bind.ContractBackend (wrong type for CallContract method)
		have CallContract(context.Context, "github.com/ethereum/go-ethereum".CallMsg, *big.Int) ([]byte, error)
		want CallContract(context.Context, "boomertasks/vendor/github.com/ethereum/go-ethereum".CallMsg, *big.Int) ([]byte, error)
```

**Comment by lmars** [comment]
@Freyert it looks like you have a vendoring issue, have you vendored the go-ethereum code? I'm also not sure this should be discussed on this closed issue, perhaps the Ethereum stack exchange at https://ethereum.stackexchange.com would be more appropriate.
