### ISSUE TITLE
1.5.5 geth.exe for Windows is reporting malware: Trojan Win32/Mefurac.E!cl

### ISSUE THREAD

**Issue by ericmaino** [ethereum/go-ethereum#3527]
This was tested on two separate Windows 10 machines. One was a brand new clean one.

I also verified the zip file that was downloaded matched the hash published on the site.

URL: https://gethstore.blob.core.windows.net/builds/geth-windows-386-1.5.5-ff07d548.zip
Windows Version: Windows.10.1607
Windows Defender Version: 1.233.4114.0
Malware Reported: Trojan Win32/Mefurac.E!cl
https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fMefurac.E!cl&threatid=2147712355&enterprise=1

Interestingly if the file is downloaded and scanned explicitly it reports no virus, but the moment the file is accessed, geth --help or even making another copy of the file it reports having the virus.

I'm working to follow up with the Windows Defender team to see if they can shed any more light on this.

I realized there has been a high number false positives and hoping this is one of them, but wanted to have the report for future reference.

**Comment by karalabe** [comment]
I replied both in the public channel but will do here too that none of 55 virus scanners on virus total flag this as containing anything malicious https://www.virustotal.com/en/file/3ed0beb6a27bcdc34aa4a0580b2c76d45c67f4614b535ed63447037ddcd4fc44/analysis/1483697209/

Given that only Microsoft's scanner reports this issues, which is famous for false positives on various networking open source projects (e.g. https://github.com/qbittorrent/qBittorrent/issues/6044), I think this is safe to close/ignore.

It would be nice to ping microsoft that their scanner is flagging badly once again, but I don't seem to be able to find an open submission form to send them issue reports regarding the scanner. Their "submit file" site just tells me "Validation of your Software Assurance ID is pending", so I can't even get to the point to send it to them for correction. If anyone else can get hold of Microsoft to fix their buggy scanner, it would be nice to get rid of this error.

**Comment by karalabe** [comment]
Ok, managed to submit the file to Microsoft and their website also reports it clean: https://www.microsoft.com/en-us/security/portal/submission/SubmissionHistory.aspx?SubmissionId=e4a18575-1a40-4196-86f6-64a16ce55ccf

**Comment by karalabe** [comment]
Closing as being reported clean by Microsoft: https://www.microsoft.com/security/portal/submission/submissionhistory.aspx?SubmissionId=E4A18575-1A40-4196-86F6-64A16CE55CCF

**Comment by ericmaino** [comment]
Figured this would be the result, but wanted to be sure we had a record.
