### ISSUE TITLE
Improve compilation error reporting

### ISSUE THREAD

**Issue by 4c656554** [ethereum/go-ethereum#3528]
#### System information

Geth version: `geth version`

Geth
Version: 1.5.3-stable
Git Commit: 978737f5d51ee4e60c00afb0c4ac8784b2faa059
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: windows7

#### Expected behaviour

On compilation of erroneous code, geth does not inform user of compilation error. 

See this question http://ethereum.stackexchange.com/q/11186/820

#### Actual behaviour

Gives this error:

```
Error: Invalid JSON RPC response: {"error":{"code":-32603,"json: cannot unmarshal array into Go value of type string":"json: cannot unmarshal array into Go value of type string"},"id":11,"version":"2.0"}
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:4  
```

This should report the compilation error:

`:1:1: Warning: Source file does not specify required compiler version!Consider adding \"pragma solidity ^0.4.4\ncontract UnitCounter {mapping (address => uint256) public UnitsFrom;uint256 public TotalUnits;function SubmitUnits(uint256 Units) {UnitsFrom[msg.sender] = Units;TotalUnits += Units;}}\n^-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^\n"`

See answer:

http://ethereum.stackexchange.com/a/11213/820

#### Steps to reproduce the behaviour

```
contract UnitCounter {
    mapping (address => uint256) public UnitsFrom;
    uint256 public TotalUnits;

    function submitUnits(uint256 Units) {
        UnitsFrom[msg.sender] = Units;
        TotalUnits += Units;
    }
}
```

After running testrpc and connecting:

`testrpc -a 1000`

attach a geth cosole

`geth attach rpc:http://localhost:8545`

do the following:

```
> eth.getCompilers()
["solidity"]
> co=eth.compile.solidity("contract UnitCounter {mapping (address => uint256) public UnitsFrom;uint256 public TotalUnits;function SubmitUnits(uint256 Units) {UnitsFrom[msg.sender] = Units;TotalUnits += Units;}}")
```

#### Backtrace

````
[backtrace]
````

**Comment by fjl** [comment]
There are two parts to this issue:

The go-ethereum bug is that invalid JSON-RPC errors are created. This is fixed in the above PR.

The testrpc response for your `eth.compile.solidity` contains a non-string error message.
[This is invalid](http://www.jsonrpc.org/specification#error_object) and should be fixed in testrpc.

```json
{
  "id": 9,
  "jsonrpc": "2.0",
  "error": {
    "message": [
      ":1:1: Warning: Source file does not specify required compiler version!Consider adding \"pragma solidity ^0.4.6\ncontract UnitCounter {mapping (address => uint256) public UnitsFrom;uint256 public TotalUnits;function SubmitUnits(uint256 Units) {UnitsFrom[msg.sender] = Units;TotalUnits += Units;}}\n^-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^\n"
    ],
    "code": -32000
  }
}
```
