### ISSUE TITLE
swarm: mount a swarm manifest as a local filesystem using fuse 

### ISSUE THREAD

**Issue by jmozah** [ethereum/go-ethereum#3539]
a manifest (referenced by a url) should be mountable as a local filesystem using fuse.

**Comment by jmozah** [comment]
I am thinking on the lines of 

swarm mount HASH <mount point>
swarm umount <mount point>

ls       - should expose the tree as in the manifest paths
cat     - use GET to read contents of file
mkdir - add path to manifest
rmdir -  remove path from manifest
touch - upload the file and add path to manifest
rm     -  remove  path from manifest  

Question: should we allow makedir?

**Comment by DigitalA1** [comment]
makedir 👍  @jmozah

**Comment by jmozah** [comment]
This issue supports only read only support. #3751 tracks the write support

**Comment by fjl** [comment]
This is now done as of #3690
