### ISSUE TITLE
Comma-separated bootnodes no longer work

### ISSUE THREAD

**Issue by iwooden** [ethereum/go-ethereum#3547]
#### System information
Geth version: Version: 1.5.6-stable
Git Commit: 2a609af51873204c940a9b2a7215e6b5a97b0656
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.7

OS & Version: Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

#### Expected behaviour
Geth should accept a comma-separated bootnode string on startup. This worked fine up to and including geth 1.5.5. From geth --help:

--bootnodes value     Comma separated enode URLs for P2P discovery bootstrap

#### Actual behaviour
Geth no longer accepts comma separated bootnode strings, and complains about "too many colons in address".

#### Steps to reproduce the behaviour
Start geth, providing a valid comma-separated string of enode URLs:

geth --bootnodes enode://9532d7d8139d6f37579b50602c88432fab2c8027e6a89064debc4efe8264438818ed49a6ab7daf9c5f6b72764628cd9587447fd3775e253866fa7c2e39ef2772@10.0.0.4:30303,enode://f850d2590127e2437c3aa3d7fbc1643e9cfc3a6023b6b5d80565f7f42452254b8729f6f6c1662058aee45f5a55c2b37e9bcde62f6448c9901dab0a6836f7425f@10.0.1.4:30303 --networkid 10101010

The following output is returned:
I0110 19:51:26.174157 cmd/utils/flags.go:499] Bootstrap URL enode://9532d7d8139d6f37579b50602c88432fab2c8027e6a89064debc4efe8264438818ed49a6ab7daf9c5f6b72764628cd9587447fd3775e253866fa7c2e39ef2772@10.0.0.4:30303,enode://f850d2590127e2437c3aa3d7fbc1643e9cfc3a6023b6b5d80565f7f42452254b8729f6f6c1662058aee45f5a55c2b37e9bcde62f6448c9901dab0a6836f7425f@10.0.1.4:30303: invalid host: too many colons in address 10.0.0.4:30303,enode:
I0110 19:51:26.174503 cmd/utils/flags.go:519] Bootstrap URL enode://9532d7d8139d6f37579b50602c88432fab2c8027e6a89064debc4efe8264438818ed49a6ab7daf9c5f6b72764628cd9587447fd3775e253866fa7c2e39ef2772@10.0.0.4:30303,enode://f850d2590127e2437c3aa3d7fbc1643e9cfc3a6023b6b5d80565f7f42452254b8729f6f6c1662058aee45f5a55c2b37e9bcde62f6448c9901dab0a6836f7425f@10.0.1.4:30303: invalid host: too many colons in address 10.0.0.4:30303,enode:

I believe this break occured due to [this commit](https://github.com/ethereum/go-ethereum/commit/8f9daaa3ba71c3b6bdcc24adfdc987e6f3a2e184), specifically the changes to cmd/utils/flags.go .

**Comment by fjl** [comment]
You're right, that change broke it. A quick workaround is to use multiple --bootnodes

**Comment by fjl** [comment]
Fixed in the PR above

**Comment by iwooden** [comment]
Great, thanks for the quick response!
