### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by awesomehimanshu** [ethereum/go-ethereum#3552]
#### System information

Geth version: `geth version` 1.5.6
OS & Version: Linux

#### Expected behaviour

It should excute all the transaction

#### Actual behaviour

**fatal error: runtime: out of memory**

runtime stack:
runtime.throw(0xddfde1, 0x16)
	/usr/lib/go-1.7/src/runtime/panic.go:566 +0x95
runtime.sysMap(0xc7e4f00000, 0x10000000, 0xc421e18d00, 0x16c70f8)
	/usr/lib/go-1.7/src/runtime/mem_linux.go:219 +0x1d0
runtime.(*mheap).sysAlloc(0x16acd20, 0x10000000, 0x0)
	/usr/lib/go-1.7/src/runtime/malloc.go:407 +0x37a
runtime.(*mheap).grow(0x16acd20, 0x8000, 0x0)
	/usr/lib/go-1.7/src/runtime/mheap.go:726 +0x62
runtime.(*mheap).allocSpanLocked(0x16acd20, 0x8000, 0x300000001)
	/usr/lib/go-1.7/src/runtime/mheap.go:630 +0x4f2
runtime.(*mheap).alloc_m(0x16acd20, 0x8000, 0x100000000, 0x7fe7b408daa8)
	/usr/lib/go-1.7/src/runtime/mheap.go:515 +0xe0
runtime.(*mheap).alloc.func1()
	/usr/lib/go-1.7/src/runtime/mheap.go:579 +0x4b
runtime.systemstack(0x7fe6f97b1dd8)
	/usr/lib/go-1.7/src/runtime/asm_amd64.s:314 +0xab
runtime.(*mheap).alloc(0x16acd20, 0x8000, 0x10100000000, 0x43711e)
	/usr/lib/go-1.7/src/runtime/mheap.go:580 +0x73
runtime.largeAlloc(0x10000000, 0x469101, 0xc7b077a000)
	/usr/lib/go-1.7/src/runtime/malloc.go:774 +0x93
runtime.mallocgc.func1()
	/usr/lib/go-1.7/src/runtime/malloc.go:669 +0x3e
runtime.systemstack(0xc420022a00)
	/usr/lib/go-1.7/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/lib/go-1.7/src/runtime/proc.go:1079

goroutine 1455 [running]:
runtime.systemstack_switch()
	/usr/lib/go-1.7/src/runtime/asm_amd64.s:252 fp=0xc439398ac0 sp=0xc439398ab8
runtime.mallocgc(0x10000000, 0xc717c0, 0xc42e950401, 0xc43ad9b000)
	/usr/lib/go-1.7/src/runtime/malloc.go:670 +0x903 fp=0xc439398b60 sp=0xc439398ac0
runtime.makeslice(0xc717c0, 0x4000000, 0x4000000, 0xc43ad9b000, 0x200, 0x200)
	/usr/lib/go-1.7/src/runtime/slice.go:57 +0x7b fp=0xc439398bb8 sp=0xc439398b60
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt.Key(0xc421deb978, 0x8, 0x8, 0xc43dfb3fc0, 0x20, 0x20, 0x40000, 0x8, 0x1, 0x20, ...)
	/build/ethereum-HffdpG/ethereum-1.5.6+build8452+trusty/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt/scrypt.go:235 +0x152 fp=0xc439398c88 sp=0xc439398bb8
github.com/ethereum/go-ethereum/accounts.getKDFKey(0xc421da24a0, 0xb, 0xc43b1d7180, 0x40, 0xc43fb3afc0, 0x20, 0xc421da2478, 0x6, 0xc421dd8f30, 0xc42e9503c0, ...)
	/build/ethereum-HffdpG/ethereum-1.5.6+build8452+trusty/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/key_store_passphrase.go:281 +0x90b fp=0xc439398e60 sp=0xc439398c88
github.com/ethereum/go-ethereum/accounts.decryptKeyV3(0xc421e41e00, 0xc421ef02a8, 0x8, 0xc3fc80, 0xc421e41e00, 0x0, 0x0, 0xc421e18d00, 0xc43de63040, 0xc421da00c0, ...)
	/build/ethereum-HffdpG/ethereum-1.5.6+build8452+trusty/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/key_store_passphrase.go:218 +0x339 fp=0xc439398fc8 sp=0xc439398e60
github.com/ethereum/go-ethereum/accounts.DecryptKey(0xc43de66c00, 0x1eb, 0x3eb, 0xc421ef02a8, 0x8, 0x0, 0x0, 0x21da00c0)
	/build/ethereum-HffdpG/ethereum-1.5.6+build8452+trusty/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/key_store_passphrase.go:179 +0x220 fp=0xc439399098 sp=0xc439398fc8
github.com/ethereum/go-ethereum/accounts.keyStorePassphrase.GetKey(0xc420449400, 0x40, 0x40000, 0x1, 0xe3c969202541699e, 0x4e28f0fb99d4df4b, 0x4e28f0fb77ad1f50, 0xc4200b7170, 0x8e, 0xc421ef02a8, ...)
	/build/ethereum-HffdpG/ethereum-1.5.6+build8452+trusty/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/key_store_passphrase.go:81 +0x9c fp=0xc439399140 sp=0xc439399098
github.com/ethereum/go-ethereum/accounts.(*keyStorePassphrase).GetKey(0xc420460000, 0xe3c969202541699e, 0x4e28f0fb99d4df4b, 0x77ad1f50, 0xc4200b7170, 0x8e, 0xc4
#### Backtrace

````
[backtrace]
````

**Comment by miohtama** [comment]
Does your system have enough RAM to run geth?

**Comment by awesomehimanshu** [comment]
I have 8 gb ram , 4 core processer . and i have run 50 transaction in geth in an instant .

**Comment by miohtama** [comment]
Can you check what is the process RAM usage before it crashes e.g. using `top` or `htop`? I assume you run 64-bit operating system?

**Comment by karalabe** [comment]
Are you running 50 concurrent transactions via `personal.sendTransaction`?

That API needs to decrypt your private key for every transaction, so 50 concurrent transactions would mean 50 concurrent decryptions. By default the keystore uses a strong cryptography, requiring about 1 second of processing time to unlock a key and about 256MB memory to do it. So unlocking 50 keys concurrently would need 12.8GB of memory.

**Comment by karalabe** [comment]
If you need to push in transactions at such a high rate, there are two alternatives you can do:

 * The first is to unlock your account in the keystore via `personal_unlockAccount` and then use `eth_sendTransaction` to use already unlocked accounts. This way your decrypted key is cached within Geth and all subsequent transactions can reuse it without needing to constantly decrypt it. **This however means that you need to take care that your node is not accessible from the outside, since anyone with access to the API can call `eth_sendTransaction` without providing a password.**
 * A better way is if you do key management and transaction signing client side within your own software, and only submit the already signed raw transaction to Geth.

**Comment by awesomehimanshu** [comment]
@karalabe . that what i was asking from many days . I was running transaction in contract (30  transaction in a second) . The whole system was getting hang . Is there is any other function which take so much of memory of system like `personal_unlockAccount `. How can i unlock the account then ? and how many transaction per second can be achieve in private ethereum blockchain ?  Thanks @karalabe . It works

**Comment by fjl** [comment]
OOM with many concurrent calls to personal_sendTransaction is a known issue. You can keep discussing here if you want.
