### ISSUE TITLE
eth_submitwork inconsistent with spec

### ISSUE THREAD

**Issue by phleemac** [ethereum/go-ethereum#3557]
#### System information

Geth version: `1.5.6-stable-2a609af5`
OS & Version: Linux 4.4.0-59-generic Ubuntu x86_64

#### Expected behaviour

According to spec https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_submitwork all three params are of type DATA, thus hex value with leading zero should be considered valid.  Thus,

`curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_submitWork","params":["0x0000000000000001","0x1111111111111111111111111111111111111111111111111111111111111111","0x2222222222222222222222222222222222222222222222222222222222222222"],"id":1}' localhost:8545`

should return:

`{"jsonrpc":"2.0","id":1,"result":false}`

#### Actual behaviour

it returns:

`{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"invalid argument 0: hex number has leading zero digits after 0x"}}`

#### Steps to reproduce the behaviour

`curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_submitWork","params":["0x0000000000000001","0x1111111111111111111111111111111111111111111111111111111111111111","0x2222222222222222222222222222222222222222222222222222222222222222"],"id":1}' localhost:8545`

**Comment by fjl** [comment]
You're right. Should we require that the input is exactly 8 bytes long?

**Comment by phleemac** [comment]
@fjl I think so, according to spec.
