### ISSUE TITLE
 Light client can't submit transactions and stops syncing after

### ISSUE THREAD

**Issue by cenotaph** [ethereum/go-ethereum#3562]
#### System information

Geth version: 1.5.6
OS & Version: Ubunt 16.04
Commit hash : (if `develop`)

#### Expected behaviour
With Geth 1.5.5 in light mode (which I love, thank you!), we could submit contract transactions (mostly minting or deleting our ERC-20 tokens). Just as normal, and they would be mined, and everything would be great.

#### Actual behaviour
After upgrading to 1.5.6, when a transaction is submitted, a transaction hash is returned, but geth stops syncing and the transaction is never mined. Geth essentially freezes - no more syncing updates in the logs, and the blockNumber is frozen. The transaction stays in the pending pool until geth is restarted, at which point the transaction is lost.

#### Steps to reproduce the behaviour
I have tried several times with different transactions. Have downgraded back to geth 1.5.5 for the time being.

**Comment by fjl** [comment]
Please capture goroutine stacks after submitting the transaction (when it hangs).
You can do that by attaching to geth

```text
geth attach
```

then run this JS function

```text
> debug.stacks()
```

**Comment by zsfelfoldi** [comment]
fixed in https://github.com/ethereum/go-ethereum/pull/3568

**Comment by cenotaph** [comment]
Thanks so much! Fixed before I even had a chance to dump stacks. :)
