### ISSUE TITLE
swarm: upload via process substition fails

### ISSUE THREAD

**Issue by nolash** [ethereum/go-ethereum#3564]
#### System information

Geth version: `1.5.6-unstable`
OS & Version: Linux Mint Sarah (Ubuntu 16.04)
Commit hash : b5a100b859213dbb7d4545ce53dabab398b4191e

#### Expected behaviour

swarm up <(echo foobar) should upload content of temporary file and return hash

#### Actual behaviour

$ swarm up <(echo foobar)
I0114 00:27:42.432630 upload.go:171] uploading file /dev/fd/63 (0 bytes)
I0114 00:27:42.440675 upload.go:70] upload failed: bad status: 400 Bad Request

#### Steps to reproduce the behaviour

issue swarm up <(echo foobar) in terminal

#### Backtrace

````
I0114 00:28:05.671449 swarm/api/http/server.go:83] HTTP POST request URL: '/bzzr:/', Host: '', Path: '/bzzr:/', Referer: '', Accept: ''
I0114 00:28:05.671480 swarm/api/http/server.go:89] BZZ request URI: '/bzzr:/'
I0114 00:28:05.671544 swarm/api/http/server.go:115] [BZZ] Swarm: POST request over protocol /bzzr:/ '' received.
````

**Comment by zelig** [comment]
@nolash unfortunately we need to os.stat the file size for swarm upload so `<(..)` process file descriptors won't work. closing as wont fix
