### ISSUE TITLE
Download page fail to load resources

### ISSUE THREAD

**Issue by eromoe** [ethereum/go-ethereum#3565]
I want to download windows version, but this page https://geth.ethereum.org/downloads/
 always get error fail to load resources.

**Comment by sathishvj** [comment]
+1 yup, I'm seeing this too now.  The website after that is entirely non responding.

**Comment by gibsongibbz** [comment]
seeing the same thing

**Comment by sathishvj** [comment]
worked for me a while ago.

**Comment by karalabe** [comment]
Hmmm, it does work for me currently. Perhaps there was a fluke at Azure (which is hosting our binaries)? Could you check again and report if you're still seeing an issue?

**Comment by sathishvj** [comment]
works fine for me now.
(it is slow though, as it used to be)

**Comment by karalabe** [comment]
It probably accumulated a lot of files to report. I'll try deleting the old develop builds to make it faster again. Will close this issue if it works. Cheers.

**Comment by karalabe** [comment]
Now it should be a lot faster :)

**Comment by eromoe** [comment]
works fine now.
