### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by ungarscool1** [ethereum/go-ethereum#3567]
#### System information

Geth version: `geth latest`
OS & Version: Raspbian 8
Commit hash : unkiwn

#### Log ####

pi@raspberrypi:~/go-ethereum $ sudo make all
build/env.sh go run build/ci.go install
build/env.sh: 31: exec: go: not found
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 127

**Comment by karalabe** [comment]
You need to have Go installed to build Geth. However if you're running on an RPI, perhaps you're better off with downloading a pre-built binary from our downloads page: https://geth.ethereum.org/downloads/
