### ISSUE TITLE
geth returns wrong transfer value

### ISSUE THREAD

**Issue by btcid** [ethereum/go-ethereum#3569]
#### System information

Geth version: Geth/v1.5.6-stable-2a609af5/linux/go1.7.3
OS & Version: Linux
Commit hash : 2a609af5

#### Expected behaviour
Amount transfered should be: 0x8**0**A7F2C1BCC396C00 or 148.33032435 Ether
references: 
https://etherscan.io/tx/0xc6c124f6c2d2730024d1047abbfecd069024d56319f961fed04719f0d813a254
https://etherchain.org/tx/0xc6c124f6c2d2730024d1047abbfecd069024d56319f961fed04719f0d813a254

#### Actual behaviour
It gives: 0x8a7f2c1bcc396c00 or 9.979743797178364 Ether

hex value missing one digit of zero after 0x8

#### Steps to reproduce the behaviour
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0xc6c124f6c2d2730024d1047abbfecd069024d56319f961fed04719f0d813a254"],"id":1}' localhost:8545
or
eth.getTransaction('0xc6c124f6c2d2730024d1047abbfecd069024d56319f961fed04719f0d813a254');

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Thank you very much for reporting it! Fixed on master, a hotfix will be released shortly!

**Comment by fjl** [comment]
Fixed in #3570
