### ISSUE TITLE
Remove serpent-go

### ISSUE THREAD

**Issue by tgerring** [ethereum/go-ethereum#357]
[script_windows.go](https://github.com/ethereum/go-ethereum/blob/develop/ethutil/script_windows.go) always returns `nil, nil` instead of calling to serpent-go

**Comment by maran** [comment]
I couldn't get serpent-go to build on windows previously, perhaps that explains `nil, nil` returns

**Comment by tgerring** [comment]
@obscuren Is this something we should attempt to improve or remove in light of Solidity as the primary language?

**Comment by obscuren** [comment]
Indeed removed. Compilation / deployment should be handled in another client (e.g. Mix)
