### ISSUE TITLE
Could not load file: .../assets/ext/bignumber.min.js

### ISSUE THREAD

**Issue by caktux** [ethereum/go-ethereum#358]
Probably only when installing from brew, getting `Could not load file: src/github.com/ethereum/go-ethereum/cmd/mist/assets/ext/bignumber.min.js`
Is it possible to include it like the other assets?

**Comment by obscuren** [comment]
Hmm. It is included. Maybe a copy fail by go-build?

**Comment by caktux** [comment]
This is using brew, not the .dmg built with go-build. The `mist/assets` gets installed in /usr/local/opt/go-ethereum/Resources` which works perfectly for every other assets, probably because of the way they get loaded.

**Comment by fjl** [comment]
cmd/mist is no more.
