### ISSUE TITLE
Error: Difficulty check failed for header

### ISSUE THREAD

**Issue by awesomehimanshu** [ethereum/go-ethereum#3590]
#### System information

Geth version: `geth version` 1.5.7
OS & Version: Ubuntu 14.10

#### Actual behaviour

```text
Error: Difficulty check failed for header (remote: 131072 local: 16384)
##############################
E0119 10:39:44.709328 core/blockchain.go:1232] 
########## BAD BLOCK #########
Chain config: {ChainID: 0 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: <nil> EIP158: <nil>}

Number: 1
Hash: 0x2e5345be979fb360c693eed39107d2a4eb56314b6f66f66f385849d17c51b6d2


Error: Difficulty check failed for header (remote: 131072 local: 16384)
##############################
```

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
You may never go with the difficulty below 131072 as specified by the protocol parameters. https://github.com/ethereum/go-ethereum/blob/master/params/protocol_params.go#L59 . Please make sure your genesis block's difficulty is at least this large.

**Comment by awesomehimanshu** [comment]
I solved that

**Comment by kevinaquick** [comment]
We are getting something similar on our private network of 5 nodes. 4 are quite happy and are syncing and mining away but the 5th drops nodes and has got stuck at block 1149999. With the error:

Error: Difficulty check failed for header (remote: 5469336 local: 5466666)
##############################
E0130 10:29:06.915614 core/blockchain.go:1249] 
########## BAD BLOCK #########
Chain config: {ChainID: 0 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: <nil> EIP158: <nil>}

Number: 1150000
Hash: 0x7ff9f6b81f63e0c80ac57718239c71aef69c1a48d0ff73d9f3ab080a40d596b3


Any ideas why that should be the case!

**Comment by karalabe** [comment]
1150000 is the homestead transition number. Apparently some of your nodes were configured to transition into homestead, while other not. Looking at the report above, the node that's failing is not configured to do so.

Is your private network old? Strange that you are running one with Frontier specs. You'll need to `geth init` your 5th node to the same chain configuration as the remainder of the nodes are using. Take your genesis json that you run your network with, add a `config` field to it containing the chain configuration of your majority nodes, and do a `geth init genesis.json` on your minority node to update it's rules according to the majority one.

PS: Please make a backup of your data directory before doing this just in case something goes wrong.

**Comment by kevinaquick** [comment]
Wow thanks for the very fast feedback - I will start investigating as you suggest!

**Comment by kevinaquick** [comment]
We now have the troublesome node back in sync with the rest of our private network. 

Just in case it helps anyone else...

Yes the network has been running for quite a while i.e. 1 year. The genesis.json is identical on all the nodes of the network. The machine that had the problem was the most recent to be added (2 or 3 months ago?). The genesis.json did not specify a blocknumber for the homestead transition (and as identical on all nodes this is the case across our private network). For whatever reason our chain had the transition block set as 1150000 (a default set in the code? which from what Peter said was the blocknumber set on the live public network?) this number was reached for our chain just a week or two ago and presumably triggered the problem on our troublesome node.

What has seemed to solve the issue was to add the following to the genesis.json on the node that would not sync

    "config": {
        "homesteadBlock": 1150000
    }

**Comment by amitOodles** [comment]
Peter, firstly i got this issue 

> ########## BAD BLOCK #########
Chain config: {ChainID: 0 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: <nil> EIP158: <nil>}
Number: 5
Hash: 0x1664247a1df06d9652c9fdc2792c7ce72172cbf951ac3bcb44975256df37124e
Error: Difficulty check failed for header (remote: 131264 local: 131200)

then made changes to the genesis file and set the minimum difficulty to 

> "difficulty": "0x020001",

so the minimum difficulty became 131073 and created new data directories with the new Genesis file. But even after that at a certain block number , i got the following issue -

> Chain config: {ChainID: 0 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: <nil> EIP158: <nil>}
Number: 17
Hash: 0x34b647515dc62878d916b0fd72bbd1f0fb35b32ea1a19cd9611c8fab8a754463
Error: Difficulty check failed for header (remote: 132032 local: 131968)

What am i doing wrong now ?
