### ISSUE TITLE
issue in go-ethereum version 1.5.7 in contract creation

### ISSUE THREAD

**Issue by awesomehimanshu** [ethereum/go-ethereum#3598]
#### System information

Geth version: `geth version` 1.5.7
OS & Version: ubuntu
Commit hash : (if `develop`)

issue in go-ethereum version 1.5.7
whe i run contract in 1.5.4 is able to execute the contract but 1.5.7 is not able to excute the contract says
Error: The contract code couldn't be stored, please check your gas amount . 

````

**Comment by dbblackdiamond** [comment]
@awesomehimanshu : you should check the amount of gas you provide to the transaction creating your contract.
