### ISSUE TITLE
swarm --recursive up failes on directories that contain linked(aliesed) files

### ISSUE THREAD

**Issue by him2him2** [ethereum/go-ethereum#3601]
#### System information

Geth Version: 1.5.8-unstable
Protocol Versions: [63 62]
Go Version: go1.7.4
OS: linux

Swarm Version: 0.2
Go Version: go1.7.4
OS: linux

#### Expected behaviour
When using the swarm command swarm --recursive up /direcrtory that contains linked(aliesed) files the links should resolve.

#### Actual behaviour
The upload process fails because the content length is set to the file system link size and the content of the upload body is set to the linked to file, creating a ContentLength/Body Length mismatch, producing the following error:

I0122 20:17:25.999399 upload.go:195] uploading file ngprogress/1.1.2/ngProgress.js (13 bytes) and adding path ngprogress/1.1.2/ngProgress.js

I0122 20:17:25.999522 upload.go:67] Put http://127.0.0.1:8500/bzz:/3257223060b22aadd6364292dffb44009f6eba767516c978961970af07e3e9ff/ngprogress/1.1.2/ngProgress.js:  **http: ContentLength=13 with Body length 10141**

This is the directory being uploaded:
$ ls -la
total 24
drwxrwxr-x  2 ron ron  4096 Jan 22 19:51 .
drwxrwxr-x 17 ron ron  4096 Jan 22 19:51 ..
-rw-rw-r--  1 ron ron 10141 Jan 22 19:33 ngprogress.js
lrwxrwxrwx  1 ron ron    13 Jan 22 19:51 ngProgress.js -> ngprogress.js
-rw-rw-r--  1 ron ron  3856 Jan 22 19:33 ngprogress.min.js
lrwxrwxrwx  1 ron ron    17 Jan 22 19:51 ngProgress.min.js -> ngprogress.min.js

#### Steps to reproduce the behaviour
swarm --recursive up /direcrtory that contains linked(aliesed) files

#### Backtrace

````

I0122 20:17:25.999399 upload.go:195] uploading file ngprogress/1.1.2/ngProgress.js (13 bytes) and adding path ngprogress/1.1.2/ngProgress.js

I0122 20:17:25.999522 upload.go:67] Put http://127.0.0.1:8500/bzz:/3257223060b22aadd6364292dffb44009f6eba767516c978961970af07e3e9ff/ngprogress/1.1.2/ngProgress.js: 
http: ContentLength=13 with Body length 10141



````

**Comment by zelig** [comment]
a quick fix will take the length of the file referenced by the link if the orig path is within the uploadedd dir tree.

long term, relative-path links should translate to redirects back and forth even if broken
while absolute path links should be ignored with a warning

**Comment by lmars** [comment]
This is no longer an issue:

```
$ ls -l
total 8
lrwxr-xr-x 1 lmars lmars 7 Mar  8 14:19 bar.txt -> foo.txt
-rw-r--r-- 1 lmars lmars 5 Mar  8 14:18 foo.txt

$ swarm --recursive up .
5b1508b55acd0feb9a74e53cc326f7fa964b490953ef60b15ff8530b05ff9053

$ curl http://localhost:8500/bzz:/5b1508b55acd0feb9a74e53cc326f7fa964b490953ef60b15ff8530b05ff9053/foo.txt
data

$ curl http://localhost:8500/bzz:/5b1508b55acd0feb9a74e53cc326f7fa964b490953ef60b15ff8530b05ff9053/bar.txt
data
```

**Comment by homotopycolimit** [comment]
user@eth-work:~$ mkdir  uploadtest
user@eth-work:~$ cd uploadtest
user@eth-work:~/uploadtest$ echo "one" > file1
user@eth-work:~/uploadtest$ ln file1 file2
user@eth-work:~/uploadtest$ ln -s file1 file3
user@eth-work:~/uploadtest$ ls -l
total 8
-rw-r--r-- 2 user user 4 Aug  8 18:47 file1
-rw-r--r-- 2 user user 4 Aug  8 18:47 file2
lrwxrwxrwx 1 user user 5 Aug  8 18:47 file3 -> file1

user@eth-work:~$ swarm --recursive up /home/user/uploadtest/
9200062ff5f4c9cf9fee77e396f8e7db6b1ad1fcbd4492b34377aba2e2c82f98
