### ISSUE TITLE
Swarm: Panic when swarm is started with invalid ethapi

### ISSUE THREAD

**Issue by jmozah** [ethereum/go-ethereum#3608]
#### System information

Geth version: 
Version: 1.5.8-unstable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3

OS & Version: Linux

Commit hash : (if `develop`)

#### Expected behaviour
should not panic when swarm is started and peers are not reachable

#### Actual behaviour
Looks like ens calls a contract even if there is not ethapi 
http://pastebin.com/XmN92Rxg

#### Steps to reproduce the behaviour
start swam with  -- ethapi "" (double quotes with no space in between)

#### Backtrace
I0126 12:35:17.118746 swarm/api/http/server.go:88] Swarm HTTP proxy started on localhost::8500
I0126 12:35:17.118921 node/node.go:341] IPC endpoint opened: /home/zahoor/BZZ/testnet/bzzd.ipc
I0126 12:35:20.118824 swarm/network/hive.go:165] no peer
I0126 12:35:23.118793 swarm/network/hive.go:165] no peer
I0126 12:35:26.118780 swarm/network/hive.go:165] no peer
I0126 12:35:26.824851 server.go:2317] http: panic serving 127.0.0.1:55932: runtime error: invalid memory address or nil pointer dereference
goroutine 611 [running]:
net/http.(*conn).serve.func1(0xc421345080)
    /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xb0d140, 0xc420010130)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/ethereum/go-ethereum/ethclient.(*Client).CallContract(0x0, 0x7f9c05f16088, 0xc420010c68, 0x0, 0x0, 0x0, 0xc42000c480, 0x0, 0x0, 0x0, ...)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/ethclient/ethclient.go:370 +0x2a9
github.com/ethereum/go-ethereum/accounts/abi/bind.(*BoundContract).Call(0xc42000c480, 0xc4203d0a18, 0xb84c80, 0xc42136de40, 0xbdd0ed, 0x8, 0xc4215490a0, 0x1, 0x1, 0x20, ...)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/accounts/abi/bind/base.go:131 +0x4cb
github.com/ethereum/go-ethereum/contracts/ens/contract.(*ENSCaller).Resolver(0xc4202559f0, 0xc4203d0a18, 0xc4179ee6870e681f, 0x861bce7c700ae86b, 0x40b571a616a726d7, 0xc2172c5657eb13cb, 0x0, 0x0, 0x0, 0xc421549188, ...)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/contracts/ens/contract/ens.go:195 +0x14d
github.com/ethereum/go-ethereum/contracts/ens/contract.(*ENSSession).Resolver(0xc4203d0a10, 0xc4179ee6870e681f, 0x861bce7c700ae86b, 0x40b571a616a726d7, 0xc2172c5657eb13cb, 0x0, 0x0, 0xc400000000, 0xc42136dca0, 0xc42136dc80)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/contracts/ens/contract/ens.go:203 +0x84
github.com/ethereum/go-ethereum/contracts/ens.(*ENS).getResolver(0xc42025d5e0, 0xc4179ee6870e681f, 0x861bce7c700ae86b, 0x40b571a616a726d7, 0xc2172c5657eb13cb, 0xc2172c5657eb13cb, 0x10, 0xc421348d20)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/contracts/ens/ens.go:100 +0x58
github.com/ethereum/go-ethereum/contracts/ens.(*ENS).Resolve(0xc42025d5e0, 0xc4204e5bd0, 0xc, 0x0, 0x0, 0x0, 0x0, 0x7f9c05dd1bc0, 0x0)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/contracts/ens/ens.go:137 +0xde
github.com/ethereum/go-ethereum/swarm/api.(*Api).Resolve(0xc42025d600, 0xc4204e5bd0, 0xc, 0x1, 0x0, 0x0, 0x10, 0x8, 0x8)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/swarm/api/api.go:81 +0x21c
github.com/ethereum/go-ethereum/swarm/api.(*Api).parseAndResolve(0xc42025d600, 0xc4204e5bd0, 0xc, 0xc421549501, 0x70405d, 0xc42025f160, 0x0, 0x0, 0x0, 0x1, ...)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/swarm/api/api.go:116 +0xa6
github.com/ethereum/go-ethereum/swarm/api.(*Api).Get(0xc42025d600, 0xc4204e5bd0, 0xc, 0xc421549901, 0x1, 0x1, 0xc, 0xc420dab040, 0x2, 0xc4207616c0, ...)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/swarm/api/api.go:143 +0x69
github.com/ethereum/go-ethereum/swarm/api/http.handler(0x1224e20, 0xc42158e0d0, 0xc4212d8780, 0xc42025d600)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/swarm/api/http/server.go:237 +0x10a1
github.com/ethereum/go-ethereum/swarm/api/http.StartHttpServer.func1(0x1224e20, 0xc42158e0d0, 0xc4212d8780)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/swarm/api/http/server.go:74 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420494090, 0x1224e20, 0xc42158e0d0, 0xc4212d8780)
    /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201dc8a0, 0x1224e20, 0xc42158e0d0, 0xc4212d8780)
    /usr/local/go/src/net/http/server.go:2022 +0x7f
github.com/ethereum/go-ethereum/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1224e20, 0xc42158e0d0, 0xc4212d8780)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rs/cors/cors.go:190 +0xe9
net/http.HandlerFunc.ServeHTTP(0xc4200a60e0, 0x1224e20, 0xc42158e0d0, 0xc4212d8780)
    /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc420294580, 0x1224e20, 0xc42158e0d0, 0xc4212d8780)
    /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc421345080, 0x1225ce0, 0xc42133bc80)
    /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2293 +0x44d
I0126 12:35:29.118745 swarm/network/hive.go:165] no peer
I0126 12:35:32.118731 swarm/network/hive.go:165] no peer
I0126 12:35:35.118781 swarm/network/hive.go:165] no peer
I0126 12:35:38.118769 swarm/network/hive.go:165] no peer

**Comment by zelig** [comment]
thanks @jmozah . not sure if availability of peers have anything to do with this but indeed the bug issaa
