### ISSUE TITLE
cmd/utils: External use of library when using cli module

### ISSUE THREAD

**Issue by nolash** [ethereum/go-ethereum#3616]
#### System information

Geth version: `1.5.4`
OS & Version: Windows/Linux/OSX

#### Expected behaviour

It should be possible to build an application generating executables like cmd/swarm and cmd/geth, without needing to have the application files in the ethereum directory structure; in other words using the ethereum files as a library.

#### Actual behaviour

Because of the use of vendoring, the `cmd/utils/flags.go` file compiles the `gopkg.in/urfave/cli.v1` package with some internal go symbol name hardwired to the path of the vendored package. 

When another application seeks to use the `cli.v1` package, compilation fails because the symbol names don't match (see *backtrace* below):

If the `gopkg.in/urfave/cli.v1` is moved from **/vendor/** to **$GOPATH**, the issue disappears.

If however the package is *REMOVED*, and `go get` is used to retrieve the package instead, code can compile, but when run the utils.app.Run() method cryptically fails (second backtrace), likely due to compatibility problems between ethereum and newer versions of the cli.v1 package.

#### Steps to reproduce the behaviour

Copy cmd/swarm/* and edit main.go to make a custom application. Place this file outside the ethereum tree, and try to compile.

#### Backtrace

````
cannot use []"gopkg.in/urfave/cli.v1".Flag literal (type []"gopkg.in/urfave/cli.v1".Flag) as type []"github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1".Flag in assignment

````

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x620161]

goroutine 1 [running]:
panic(0xc59380, 0xc8200101a0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
flag.(*FlagSet).Var(0xc8202b49c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/flag/flag.go:766 +0x51
gopkg.in/urfave/cli%2ev1.GenericFlag.ApplyWithError.func1(0x0, 0x0)
	/home/lash/programming/projects/go/src/gopkg.in/urfave/cli.v1/flag.go:128 +0xa6
gopkg.in/urfave/cli%2ev1.eachName(0x0, 0x0, 0xc820051968)
	/home/lash/programming/projects/go/src/gopkg.in/urfave/cli.v1/flag.go:94 +0x11f
gopkg.in/urfave/cli%2ev1.GenericFlag.ApplyWithError(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8202b49c0, ...)
	/home/lash/programming/projects/go/src/gopkg.in/urfave/cli.v1/flag.go:129 +0x444
github.com/ethereum/go-ethereum/cmd/utils.(*DirectoryFlag).ApplyWithError(0xc8200b45a0, 0xc8202b49c0, 0x0, 0x0)
	<autogenerated>:1 +0x5c
gopkg.in/urfave/cli%2ev1.flagSet(0x7fffcf03f48c, 0x4, 0xc8202a5440, 0x1d, 0x24, 0x8, 0x0, 0x0)
	/home/lash/programming/projects/go/src/gopkg.in/urfave/cli.v1/flag.go:80 +0x1ac
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc8200c1380, 0xc820094000, 0x5, 0x5, 0x0, 0x0)
	/home/lash/programming/projects/go/src/gopkg.in/urfave/cli.v1/app.go:181 +0x14c
main.main()
	/home/lash/programming/projects/go/src/github.com/SOMEAPP/cmd/META/main.go:103 +0x53
````

**Comment by zelig** [comment]
thanks @nolash 
I'm afraid we may not prioritise support for using anything under cmd as part of using the package as a lib.
These convenience methods just serve as illustrations how to wrap code.

That said if you can make it work in a way which fixes your side of things I think we will defo consider your changes.

**Comment by karalabe** [comment]
We welcome contributions that make the library nicer to use, but as Viktor mentioned above, the contents of `cmd` is not part of the library (they are even licensed GPL versus LGPL for the remainder of the codebase). Please do not rely on any feature from that folder for your own projects, rather use the remainder only.

I'm writing up a guide on how to do that, but since the codebase is still evolving (especially regarding events and accounts at the moment), it cannot progress as fast as I'd like.
