### ISSUE TITLE
cmd/geth: js to rpc mappings in webext3js are hardcoded

### ISSUE THREAD

**Issue by nolash** [ethereum/go-ethereum#3617]
#### System information

Geth version: `1.5.4`
OS & Version: Windows/Linux/OSX

#### Expected behaviour

When defining a RPC interface, the geth console should learn and implement its function calls from a source definable from the application defining the RPC.

#### Actual behaviour

The file `internal/web3ext/web3ext.js` must be manually edited to map js console function calls to RPC methods.

**Comment by zelig** [comment]
this is a change i welcome but note my comment on #3616 the attached consoles are considered opinionated interfacted which support particular packages. 

A somewhat nicer refactor of the attach console code may bring us both some benefit. See
 @fjl fix in here https://github.com/ethereum/go-ethereum/pull/3602/commits/0cc138ab0ef89d0ae7aa51a4cdab15ada9830fb5
