### ISSUE TITLE
Signing and verifying do not produce correct results

### ISSUE THREAD

**Issue by florian-besser** [ethereum/go-ethereum#3621]
#### System information

Geth version: `geth version`
Version: 1.5.8-unstable
Git Commit: c46c41eae35e3083090e5806932fc5076e53e37c
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.4
OS: linux
GOPATH=
GOROOT=/usr/local/go
OS & Version: LUbuntu 16.10

#### Expected behaviour

Execute the following on the Geth cli:
```
var msg = "foobar";
var msgHash = web3.sha3(msg);
var sig = web3.eth.sign(web3.eth.defaultAccount, msgHash);
var r = sig.slice(0, 66)
var s = '0x' + sig.slice(66, 130)
var v = '0x' + sig.slice(130)
v = web3.toDecimal(v)
```

Expect:
`web3.eth.defaultAccount == auth.verify.call(msgHash, v, r, s)`

Where "auth" is an instance of the contract:
```

contract Auth {      
    function verify( bytes32 hash, uint8 v, bytes32 r, bytes32 s) constant returns(address retAddr) {
        retAddr = ecrecover(hash, v, r, s);
    }
}
```

#### Actual behaviour

String returned by verify does NOT match the account which was used for signing the hash

#### Steps to reproduce the behaviour

See above

#### Backtrace

````
None, no exception
````

**Comment by karalabe** [comment]
Please read this thread https://github.com/ethereum/go-ethereum/pull/2940. The docs on the wiki apparently need to be updated. @holiman could you perhaps update the wiki to add the details and logic behind the prepended text?

**Comment by bas-vk** [comment]
See:
https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_sign
https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_ecrecover

**Comment by bas-vk** [comment]
@holiman 👍

**Comment by ethLouise** [comment]
I've the same problem , I sign with personal.sign in geth then I test with personal.ecrecover it works fine, it returns the right address, but when I try with solidity it return a wrong address !! can you tell me why please!

**Comment by chompomonim** [comment]
@ethLouise And one year later I have same problem :( Have you found any solution for that?
