### ISSUE TITLE
API documentation missing

### ISSUE THREAD

**Issue by florian-besser** [ethereum/go-ethereum#3622]
#### System information

Geth version:
Version: 1.5.8-unstable
Git Commit: c46c41eae35e3083090e5806932fc5076e53e37c
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.4
OS: linux
GOPATH=
GOROOT=/usr/local/go
OS & Version: Lubuntu 16.10

#### Expected behaviour

The "personal" API documentation should document the existing function "ecRecover":
https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal

```
> web3.personal.ecRecover
function()
```

#### Actual behaviour

No documentation found.
Additionally, ecRecover does not behave like Solidity ecrecover, which one might expect without documentation.

#### Steps to reproduce the behaviour

Click on the link.

#### Backtrace

````
None
````

**Comment by bas-vk** [comment]
I have added descriptions to the docs.

See https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_sign
and https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_ecrecover
