### ISSUE TITLE
SEC-9 Encapsulate slice access to reduce risk of mem access bugs

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#363]
Example: https://github.com/ethereum/go-ethereum/blob/develop/vm/vm.go#L859

Let's encapsulate this type of slice access with e.g. PeekN(n uint).

**STATUS: OPEN**

**Comment by fjl** [comment]
Can you go into details about this?
What do you want to prevent here?

**Comment by obscuren** [comment]
This has been discussed and will not change (for optimisation reasons). A comment will be appropriate.
