### ISSUE TITLE
les: unresponsive server up until sync is done

### ISSUE THREAD

**Issue by farazdagi** [ethereum/go-ethereum#3639]
#### System information

Geth version: 1.5.8-stable
OS & Version: OSX
Commit hash : `f58fb322`

#### Expected behavior
- RPC server is expected to be available during header syncing

#### Actual behaviour
- Everything blocks up until sync is done

#### Steps to reproduce the behaviour
- While this issue was first found when we tried to run `eth.*` commands using web3, this issue can be reproduced in console as well
- Basically, `geth --light --testnet console`, then once sync starts, you cannot call any commands (they block), you can't event dump `eth` object by typing `eth ENTER`:
![image](https://cloud.githubusercontent.com/assets/188194/22584495/bb724020-ea03-11e6-96e5-09a97f1c1fc5.png)

#### More Notes
- the issue is introduced by this commit: https://github.com/ethereum/go-ethereum/pull/3413/commits/c57c54ce96628aeb6345776310123a80593f0143 (I've tested code prior to that commit - no blocking exists there)
- the very same or really similar issue was already accepted and fix was provided by https://github.com/ethereum/go-ethereum/pull/3607. From description of that PR:
> removes the mechanism which delayed starting the LES server side protocol until ETH was fully synced. This mechanism solved a problem that does not exist anymore, clients now check server's reported head before sending requests and choose a server that can actually serve it. At the same time it caused other problems, like not starting LES server at all when the node was mining alone on a private net. Also, not starting the protocol stalled connections to other LES servers through ETH, even though they did not want to do anything with each other through LES.
- probably some aspects of the problem are solved with that PR, but the problem reported in this issue (that's blocking calls to `eth` - using RPC, via console or web3) is still there

#### Severity
- This issue is really severe. Blocking/delaying light client server up until full sync (especially on mobile devices where we use LES, and where sync is a bit slower) is huge concern, as it prevents users from using our app up until sync is done

**Comment by jarradh** [comment]
Related PR #3660

**Comment by karalabe** [comment]
Should be fixed on 1.6.0.
