### ISSUE TITLE
Where can I download an old version of Geth before the latest hard fork?

### ISSUE THREAD

**Issue by LiyanJin** [ethereum/go-ethereum#3647]
For some reasons, I need an old version Geth , for example v1.4.0 and so on, as long as which is before the latest hard fork.
So ,Where can I find and download them?
Any idea?

**Comment by bas-vk** [comment]
We offer binaries on https://geth.ethereum.org/downloads/. Geth 1.4.0 is the oldest release offered. Otherwise you can build geth from an old commit.

**Comment by LiyanJin** [comment]
TX so much!
I get the binary I want by your suggestion.

**Comment by LiyanJin** [comment]
Hi, bas-vk
I downloaded the binary , geth-darwin-amd64-1.4.18-ef9265d0-20161015111715.tar from the website. And then I run
`$ tar -xvzf geth-darwin-amd64-1.4.18-ef9265d0-20161015111715.tar`
`$ cd geth-darwin-amd64-1.4.18-ef9265d0`
`$ make geth`
but there is error 
`make: Nothing to be done for `geth'.`
Any idea?

**Comment by obscuren** [comment]
Seems make does not seem to work for that version. Please either use a binary (find them on the GH release pages) or use latest. Another option is to set up go (easy) and use `go build`.

**Comment by LiyanJin** [comment]
Hi, Obscuren
Thank you so much.
Your suggestion works well for me!
