### ISSUE TITLE
Problem with Mist loading libQt5WebEngine.so.5

### ISSUE THREAD

**Issue by noflag** [ethereum/go-ethereum#366]
mist: error while loading shared libraries: libQt5WebEngine.so.5: cannot open shared object file: No such file or directory

linux/amd64, latest dev ppa version.

**Comment by maran** [comment]
Which QT version do you have installed? Please note you require 5.4.

**Comment by noflag** [comment]
i have the ppa for opt-qt54-trusty installed and everything updated, is there a way to check manually?

**Comment by noflag** [comment]
qt54base is already the newest version.
qt54base set to manually installed.

**Comment by noflag** [comment]
QT_SELECT="default"
QTTOOLDIR="/usr/lib/x86_64-linux-gnu/qt5/bin"
QTLIBDIR="/usr/lib/x86_64-linux-gnu"

**Comment by noflag** [comment]
Ok, it changed. New issue: mist: symbol lookup error: /opt/qt54/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZN21QAbstractConcatenable14appendLatin1ToEPKciP5QChar

**Comment by caktux** [comment]
Can you try doing `export LD_LIBRARY_PATH=/opt/qt54/lib` and report back?

**Comment by noflag** [comment]
That worked! Thanks! How do I make it permanent?

**Comment by caktux** [comment]
Put it in `~/.bashrc` :)

**Comment by tgerring** [comment]
This will append it to your ~/.bash_profile ;)

`echo "export LD_LIBRARY_PATH=/opt/qt54/lib" >> ~/.bash_profile`
