### ISSUE TITLE
No ethereum available. Except in etherscan

### ISSUE THREAD

**Issue by kingburrito666** [ethereum/go-ethereum#3666]
#### System information
``````
Version: `0.8.9`
OS & Version: osx
Node type: `eth/geth(default)`
``````
I have multiple transactions into my account. My ethereum wallet shows that I still have 0 ether. **I've been everywhere** and **tried everything** to solve this problem. It's been 26 days since my first transaction which displays that it _did_ go through, but doesn't show up in my account at all. My account is here:
[https://etherscan.io/address/0x516976ce81751ebe077ca01c57b97c9665b0e10b](url)
Please help me, i've contacted coinbase, ethereum-support, and... reddit. 

-My console: **something's wrong?**
![screenshot 2017-02-12 16 26 17](https://cloud.githubusercontent.com/assets/17525596/22867612/33b4fa4e-f140-11e6-9d11-c66046907fe9.png)

- Log files 
[logs.zip](https://github.com/ethereum/mist/files/769792/logs.zip)
(will send ethereum to helper) 

````
[backtrace]
````
I do not know what backtrace is.
Again: **WILL SEND ETHER TO HELPER**

**Comment by obscuren** [comment]
It's likely that your node isn't up to date. What block is it reporting at?

**Comment by karalabe** [comment]
Closing as assuming mist was not synced.
