### ISSUE TITLE
no UPnP or NAT-PMP router discovered

### ISSUE THREAD

**Issue by ogurcan** [ethereum/go-ethereum#3669]
#### System information

Geth version: 1.5.7-stable
OS & Version: Ubuntu 16.04 and OSX 10.12.3
Commit hash : (if `develop`)

#### Expected behaviour

The mining to start.

#### Actual behaviour

Geth is unable to find neither UPnP nor NAT-PMP router discovered and the mining doesn't start. I am verifying by checking the balance of the `eth.coinbase`. I tried two different computer with two different OSs.

#### Steps to reproduce the behaviour

Follow the steps given [here](https://github.com/ogurcan/blockchain/blob/master/ethereum/doc/Setting%20Up%20a%20Local%20Private%20Test%20Network%20with%20One%20Node.md#setting-up-a-local-private-test-network-with-one-node). When you come to the [mining step](https://github.com/ogurcan/blockchain/blob/master/ethereum/doc/Setting%20Up%20a%20Local%20Private%20Test%20Network%20with%20One%20Node.md#start-ethereum-mining), normally it works in my computer at home. However, at work it doesn't work. I guess it is about the network restrictions here but I don't know what to do or what to demand from the networking management guys. Or may be there is a workaround for restricted networks, but I don't know.

#### Backtrace

First I am seeing the messages below somewhere between the messages after I start `geth`.

``` bash
...
I0213 14:36:18.796569 p2p/nat/nat.go:105] deleting port mapping: tcp 30301 -> 30301 (ethereum p2p) using UPnP or NAT-PMP
I0213 14:36:18.796627 p2p/server.go:493] <-quit: spinning down
I0213 14:36:18.796625 p2p/server.go:636] Read error: accept tcp [::]:30301: use of closed network connection
I0213 14:36:18.796651 p2p/server.go:569] ignoring 0 pending tasks at spindown
...
```

And then after I execute the command `miner.start` on the attached console, I am seeing the following messages.

```  bash
...
I0213 14:51:25.236610 eth/downloader/downloader.go:1474] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0213 14:51:45.240652 eth/downloader/downloader.go:1474] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0213 14:52:05.244611 eth/downloader/downloader.go:1474] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0213 14:52:25.248686 eth/downloader/downloader.go:1474] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0213 14:52:45.252487 eth/downloader/downloader.go:1474] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0213 14:53:05.254211 eth/downloader/downloader.go:1474] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0213 14:53:25.144634 p2p/nat/nat.go:120] refresh port mapping tcp:30301 -> 30301 (ethereum p2p) using UPnP or NAT-PMP
I0213 14:53:25.144659 p2p/nat/nat.go:122] network port tcp:30301 could not be mapped: no UPnP or NAT-PMP router discovered
I0213 14:53:25.259442 eth/downloader/downloader.go:1474] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0213 14:53:45.264628 eth/downloader/downloader.go:1474] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0213 14:54:05.269811 eth/downloader/downloader.go:1474] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0213 14:54:25.272559 eth/downloader/downloader.go:1474] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0213 14:54:45.276506 eth/downloader/downloader.go:1474] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
...
````

**Comment by ogurcan** [comment]
Hi all, I realized that the message `I0213 14:38:27.250273 p2p/nat/nat.go:109] network port tcp:30301 could not be mapped: no UPnP or NAT-PMP router discovered` is not actually making problem. However, before I executed `miner.start` and it was not working. Now I am doing `miner.start(8)` and it working fine. Is there any recommended usage of this `miner.start` function?

**Comment by fjl** [comment]
`miner.start` doesn't do anything because it returns a JavaScript function object. `miner.start(N)` invokes it ;)
