### ISSUE TITLE
FreeBSD builds broken by gousb

### ISSUE THREAD

**Issue by tymat** [ethereum/go-ethereum#3677]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

`make all` should compile

#### Actual behaviour

```
# github.com/ethereum/go-ethereum/vendor/github.com/karalabe/gousb/usb
In file included from vendor/github.com/karalabe/gousb/usb/config.go:21:
../internal/libusb/libusb/libusbi.h:319:2: error: unknown type name 'POLL_NFDS_TYPE'
        POLL_NFDS_TYPE pollfds_cnt;
        ^
../internal/libusb/libusb/libusbi.h:1071:23: error: unknown type name 'POLL_NFDS_TYPE'
                struct pollfd *fds, POLL_NFDS_TYPE nfds, int num_ready);
                                    ^
```

#### Steps to reproduce the behaviour

Compile geth on FreeBSD 11.0

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
I'm switching over to a HID based approach to hardware wallet, which will only need libusb on linux, and will not depend on it on any other platform. Will ping this issue when the PR is up.
