### ISSUE TITLE
Why IPC peer can't connect RPC peer

### ISSUE THREAD

**Issue by EasonWang01** [ethereum/go-ethereum#3678]
#### System information

Geth version: `geth version`
OS & Version: OSX
Commit hash : (if `develop`)

#### Steps to reproduce the behaviour

IPC peer
```
geth --ipcpath ~/Library/Ethereum/geth1.ipc --datadir "./privatechain3" --networkid 1234 --port="33333" console
```

RPC peer

```
geth  --ipcdisable --rpc --rpcport 8103 --datadir "./privatechain/02" --networkid 123 --rpcapi="db,eth,net,web3,personal" --nodiscover  --port=30308 --rpccorsdomain="*"  console 
```

they both init by the same genesis.json

but IPC peer connect to IPC peers and  RPC peer to RPC peer all good.Why no RPC to IPC?

Another question is https://github.com/ethereum/go-ethereum/wiki/Setting-up-private-network-or-local-cluster

it says

>the ipc endpoint is unique or the ipc interface is disabled

Why it says that?Beacuse I can connect both IPC peer with the same IPC endpoint.

**Comment by bas-vk** [comment]
Your network id's differ.

IPC and HTTP (RPC) endpoints have nothing todo with nodes connecting to each other. Its the endpoint that a client can connect to and communicatie with the node.

**Comment by EasonWang01** [comment]
thanks I found it,but do you know the second question?
And why the private netword will auto find stranger rather then the local peers?
I must add peers manual.

**Comment by bas-vk** [comment]
> the ipc endpoint is unique or the ipc interface is disabled

On unix/osx geth uses unix sockets and on Windows named pipes. These sockets/pipes need to be unique for the same reason you cannot save 2 different files with the same filename in the same directory.

Probably your private network nodes find other nodes through the default bootnodes. This is not a problem. Your nodes won't sync with any of these other nodes. If you set up a multi node private network I recommend setting up a a custom bootnode so you don't have to manually add peers.

**Comment by EasonWang01** [comment]
But if the bootnode shutdown and we didn't notice will new add peer will not able to join the network?

**Comment by EasonWang01** [comment]
Is ethereum using UDP broadcast or multicast ?why there are default bootnodes exist?
What is the ethereum  broadcast method that can reach others on the internet?

**Comment by Hellsegga** [comment]
> But if the bootnode shutdown and we didn't notice will new add peer not able to join the network?

If the node has never connected to the network before it will not know of any peers except for the bootnodes you specify, so if those are down it will not be able to join the network. For fault tolerance you can have several bootnodes running in different locations and feed the full list of bootnodes to the new nodes you start (which is what the public network does, those bootnodes being hardcoded in the client)

> Is ethereum using UDP broadcast or multicast ?

The discovery protocol uses UDP.  Make sure the bootnodes are reachable over the network.

**Comment by rPavan55** [comment]
How to sync Geth and testRPC private nodes locally?

I have setup 2 nodes, 1 on testRPC and the other on geth(using cmd and mist).

**How to sync both the nodes** so that I can write a crowdfunding smartcontract for the accounts in both the private nodes to contribute?
