### ISSUE TITLE
confusing error message when specifying defaultBlock for call()

### ISSUE THREAD

**Issue by chafey** [ethereum/go-ethereum#3689]
#### System information

Geth version: 1.5.7-stable
OS & Version: OSX

#### Expected behaviour

Invoking call on contract with defaultBlock set to block before contract was instantiated should give a clear error - something like "Error: Contract was created after specified block number"

#### Actual behaviour

Confusing error message : "Error: new BigNumber() not a base 16 number:" 

#### Steps to reproduce the behaviour

1) Deploy contract that has a public getter (constant) and setter for a property and note the block number it was created on (e.g. 300):
```
pragma solidity ^0.4.2;

contract Test {

  string public name;

  function SetName(string _name) {
    name = _name;
  }
}
```

2) Try invoking call for the getter on a block # before it was instantiated:
```
  test.name.call(299); // error
```

#### Backtrace

````
Error: new BigNumber() not a base 16 number: 
    at raise (web3.js:14632:29)
    at web3.js:14620:33
    at BigNumber (web3.js:13667:28)
    at web3.js:1110:23
    at web3.js:1634:20
    at web3.js:826:16
    at map (<native code>)
    at web3.js:825:12
    at web3.js:4004:18
````

**Comment by bas-vk** [comment]
I'm not that familiar with web3.js but I assume that `test.name.call(299)` calls the name method in block 299? From what I make of the error its look likes web3 expects the block number as a string in hex notation. But @frozeman could probably confirm this.

**Comment by chafey** [comment]
Correct - test.name.call(299) "gets" the value of name on block 299.  In this case, the smart contract instance was created after block 299 so it doesn't exist and the error is confusing.  It works as expected when using block numbers after the smart contract is created

**Comment by fjl** [comment]
This is a web3.js issue.
