### ISSUE TITLE
Connection to geth via "geth attach" and "geth console" result in conflicting number of peers reported as connected (admin.peers)

### ISSUE THREAD

**Issue by dunff2k** [ethereum/go-ethereum#3695]
#### System information

Geth version: `1.5.9-stable`
OS & Version: Ubuntu Server 16.04
Commit hash : (if `develop`)

#### Expected behaviour
`admin.peers` should display the same number of peers irrespective of using `geth attach` or `geth console` to bring up the terminal.

#### Actual behaviour
While manually adding peers to my private ethereum cluster: `admin.peers` displays a reduced number of peers if I connect to the node via `geth attach`.

#### Steps to reproduce the behaviour
1. Create 2 Ethereum nodes: x,y (in my work, x and y are VMs).
2. Successfully add y as a peer to x.
3. Open a terminal on y and connect to node using `geth console` check `admin.peers` to get result (i). Should be 1.
4. launch a new terminal window and use `geth attach` to connect to node y. Check `admin.peers` to get result (ii). Should be 1.
5. Compare result (i) and result (ii)

#### Backtrace

````
[backtrace]
````
``

**Comment by bas-vk** [comment]
`attach` and `console` both use the exact same RPC methods. Are you absolutely sure that `geth attach` connects to one of the nodes in the private cluster? You can verify this by comparing the enodes.

```
> admin.nodeInfo.enode
"enode://822869eaf38eed83e77865b398dc622652f2510c2b29ea6151189871beebd33072b08fb6513f1001920f3c23aa2d188e0961ab9a48144bd10906426451a148db@[::]:21000"
```
