### ISSUE TITLE
gasPrice RPC gives back number instead of HEX

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#370]
The docs state it should return a HEX, though it returns a number as string:
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gasprice

**Comment by tgerring** [comment]
Currently is reporting the value from string const at https://github.com/ethereum/go-ethereum/blob/483d96a89d68023360d211ab329400f4b960fe48/rpc/packages.go#L29

**Comment by frozeman** [comment]
Currently:

```js
{
"id":73,
"jsonrpc":"2.0",
"result":"100000000"
}
```

expect:
```js
{
"id":73,
"jsonrpc":"2.0",
"result":"0x09184e72a000"
}
```

**Comment by maran** [comment]
What's the benefit of giving the result in hex? Wouldn't it make more sense to change the specification to show it in base 10?

**Comment by tgerring** [comment]
I think some of the "hex result" might have to do with lack of large number support in JavaScript. Maybe @debris could provide some insight?

**Comment by maran** [comment]
I thought we were using bignumber.js to work around that.

**Comment by frozeman** [comment]
its the big number i guess. in ethereum js the hex is change into a big number.

**Comment by debris** [comment]
bignumber.js can handle decimal numbers in strings as well. The real issue is that we have differences in cpp && go ethereum json-rpc api. Go is already returning hex for balance rpc method. Let's unify this && return hex for all value related properties.
