### ISSUE TITLE
For every 30000 block the geth stop mining for 20 minutes 

### ISSUE THREAD

**Issue by himanshuoodles** [ethereum/go-ethereum#3710]
#### System information

Geth version: `geth version` 1.5.7
OS & Version: ubuntu
Commit hash : (if `develop`)

Why geth is not mining , Is there is any way that it doesn't stop ?

I know it make DAG file for the blockchain that why it stop but if i wait for making DAG file the transaction remined unmined for more then 15 minutes untill DAG is created. PLease suggest solution .

**Comment by karalabe** [comment]
There is a flag `--autodag` which will generate the next DAG in advance so that when the miner reaches the epoch switch, the next one will be already available. Could you check whether that solves your issue?

**Comment by himanshuoodles** [comment]
THanks @karalabe  . I have set  that will close this question when i test that.

**Comment by karalabe** [comment]
:+1:

**Comment by karalabe** [comment]
Closing this. Please reopen if the issue persists.

**Comment by himanshuoodles** [comment]
No --autodag doesn't work .

**Comment by himanshuoodles** [comment]
MY miner stoped at 270000

**Comment by karalabe** [comment]
Could you try with latest develop? I've rewritten the entire ethash implementation in Go. Should sort out all these issues now.
