### ISSUE TITLE
BAD BLOCK 3192500, Error: invalid chaid id for signer

### ISSUE THREAD

**Issue by porobov** [ethereum/go-ethereum#3714]
#### System information

Geth version: 1.5.5-stable-ff07d548
OS & Version: Linux

#### Actual behaviour

Keep getting BAD BLOCK record while syncing

#### Steps to reproduce the behaviour

Restarted my node about a week ago.

#### Backtrace

````
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}

Number: 3192500
Hash: 0xeeed4011c996d7e1b82c675fdbadc210e5e75a74a4f4a685237373a23fae1542


Error: invalid chaid id for signer
##############################
I0227 08:41:15.405551 core/blockchain.go:1047] imported 1 blocks,     0 txs (  0.000 Mg) in   9.641ms ( 0.000 Mg/s). #3259281 [82051ee8…]
E0227 08:41:15.735068 core/blockchain.go:1232] 
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}

Number: 3192500
Hash: 0xeeed4011c996d7e1b82c675fdbadc210e5e75a74a4f4a685237373a23fae1542


Error: invalid chaid id for signer
##############################

````

**Comment by karalabe** [comment]
Given that you have

```
I0227 08:41:15.405551 core/blockchain.go:1047] imported 1 blocks,     0 txs (  0.000 Mg) in   9.641ms ( 0.000 Mg/s). #3259281 [82051ee8…]
```

It means you are in sync with the network and everything's fine, but someone's sending around invalid blocks in the network.

**Comment by karalabe** [comment]
You can just ignore the error as long as you are in sync, some poor miner will hopefully realize that he's mining junk (or the person propagating it) and stop. If this keeps up being annoying I can try to add some code to avoid reporting the same blocks multiple times.

**Comment by porobov** [comment]
@karalabe got it! Thank you! 

Yes, I think it is a great idea to make this message less .. persistant. It is quite frustrating!)) 

Have a great day!
