### ISSUE TITLE
Incorrect gasLimit set when solidity contract setting uint to zero

### ISSUE THREAD

**Issue by fabioberger** [ethereum/go-ethereum#3719]
This issue is the same as the one discussed in this [browser-solidity issue](https://github.com/ethereum/browser-solidity/issues/368).

#### System information

Geth version: `1.6.0`
OS & Version: OSX

#### Expected behaviour
Expected contract call resulting in uint being set to zero to execute without the base fee exceeding the gas limit. When calling `Transfer` in the Zeppelin-solidity [StandardToken.sol](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/StandardToken.sol) contract with `_value` equal to `balances[msg.sender]`, the gasLimit set by Geth was 20957, insufficient to complete the transaction.

#### Actual behaviour
Expected the contract call to succeed. Artificially setting the gasLimit to 50957 made the transaction complete without issue.

#### Steps to reproduce the behaviour

- Deploy the Zeppelin-solidity [StandardToken.sol](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/StandardToken.sol) contract.
- Using the [Geth contract bindings](https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts), write a test that transfers 5000 tokens to an account. Then, transfer those 5000 tokens back to the initial account (this zeroes out the balance of this account).
- Start [testrpc](https://github.com/ethereumjs/testrpc) in terminal.
- Run the test and observe that the second call to `transfer` fails.

**Note:** Hardcoding the gasLimit to 50957 on line 212 in `go-ethereum/accounts/abi/bind/base.go` fixes the issue.

**Comment by karalabe** [comment]
Are you running a frontier or homestead chain? My bet is that the former.

**Comment by fabioberger** [comment]
I just pulled master, ran `make all` and re-ran `./build/bin/abigen` and still have the issue. 

When running `./build/bin/geth` I get the following info:

```
INFO [02-27|21:49:19] instance:Geth/v1.6.0-unstable-dc0a006c/darwin/go1.7.1
INFO [02-27|21:49:19] Protocol Versions: [63 62], Network Id: 1
INFO [02-27|21:49:19] Chain config:{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}
```

**Comment by fabioberger** [comment]
It turns out the go-ethereum `ethclient` calls `eth_estimateGas` on the locally running node (in my case this was testrpc, not geth) and testrpc is miscalculating the gas costs since it does not use the binary search approach.

Sorry for the false alarm!

**Comment by karalabe** [comment]
The is nonetheless an issue in Geth too, but that only happens with gas estimation before the homestead transition. That is due to a protocol anomaly in Frontier, where a failed contract deploy (i.e. not enough gas to store the result) only consumed the gas up to (but before) the failing instruction, but not all of it. Our estimator doesn't handle this case well.
