### ISSUE TITLE
"Go bindings to Ethereum Contracts" is wrong

### ISSUE THREAD

**Issue by coreyog** [ethereum/go-ethereum#3726]
#### System information
Geth version: `1.5.9-stable'
OS & Version: Windows 10 x64

#### Expected behaviour
Following the guide at [Native DApps: Go bindings to Ethereum Contracts](https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts) would allow my applications to connect and interact with a smart contract using Go.

#### Actual behaviour
`rpc.NewIPCClient` doesn't exist but I can get around it using `rpc.Dial`, `backends.NewRPCBackend` doesn't exist and I can't find a suitable alternative.

#### Steps to reproduce the behaviour
Follow the guide at https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts

**Comment by karalabe** [comment]
We are rewroking the APIs and it wasn't finalized yet. You should be able to use `ethclient.Dial()`, and plug the result in as the backend.

**Comment by fjl** [comment]
The wiki page is updated now.

**Comment by xanderdunn** [comment]
The [Deploying contracts to Ethereum](https://github.com/ethereum/go-ethereum/wiki/Native-DApps:-Go-bindings-to-Ethereum-contracts#deploying-contracts-to-ethereum) example still references `rpc. NewIPCClient`.
