### ISSUE TITLE
out-of-date examples on Contract Tutorial wiki page

### ISSUE THREAD

**Issue by cdetrio** [ethereum/go-ethereum#3732]
Readers [still expect](https://gitter.im/ethereum/solidity?at=58b6cfc4f1a33b6275662ae4) that go-ethereum/wiki is up-to-date, but the [Contract Tutorial](https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial) examples do not work since the solidity code does not have the `payable` modifier where needed.

**Comment by karalabe** [comment]
I'd really like to delete all those pages. Since solidity is has a proper documentation, I don't want to maintain Solidity tutorial on the go-ethereum repo.

@obscuren @fjl ?

**Comment by fjl** [comment]
@cdetrio Can you tell me what needs to change? I would like to keep the pages for now, but they need to be right.
