### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#3733]
#### System information

Geth version: `geth version`
INFO [03-01|15:55:12] instance:Geth/GETH DEVELOP ROPSTEN/v1.6.0-unstable-c52ab932/windows/go1.8 

OS & Version: Windows/Linux/OSX
Windows 64bit

Commit hash : (if `develop`)
INFO [03-01|15:55:12] Successfully wrote custom genesis block: 41941023680923e0fe4d74a34bdac8141f2540e3ae90623718e47d66d1ca4a2d 
INFO [03-01|15:55:12] upgrading db log bloom bins 
INFO [03-01|15:55:12] upgrade completed in0s 
INFO [03-01|15:55:12] Protocol Versions: [63 62], Network Id: 3 
INFO [03-01|15:55:12] Chain config:{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10} 
INFO [03-01|15:55:12] Loaded most recent local header          number=0 hash=419410â€¦ca4a2d td=1048576
INFO [03-01|15:55:12] Loaded most recent local full block      number=0 hash=419410â€¦ca4a2d td=1048576
INFO [03-01|15:55:12] Loaded most recent local fast block      number=0 hash=419410â€¦ca4a2d td=1048576

#### Actual behaviour
panic: runtime error: index out of range

goroutine 16 [running]:
github.com/ethereum/go-ethereum/core.(*BlockChain).reorg(0xc042491500, 0xc04cde82d0, 0xc075c26750, 0x5688a3925709fa00, 0x8d2a8f8636c6321e)
	C:/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1153 +0x1c55
github.com/ethereum/go-ethereum/core.(*BlockChain).WriteBlock(0xc042491500, 0xc075c26750, 0xc0421d4e00, 0x0, 0x0)
	C:/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:838 +0x889
github.com/ethereum/go-ethereum/miner.(*worker).wait(0xc042423200)
	C:/gopath/src/github.com/ethereum/go-ethereum/miner/worker.go:298 +0x586
created by github.com/ethereum/go-ethereum/miner.newWorker
	C:/gopath/src/github.com/ethereum/go-ethereum/miner/worker.go:146 +0x4d4

#### Steps to reproduce the behaviour
miner.start(2) 
After running for a few hours this panic occurs.

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Woah, nice. Will look into it. Thx for reporting.

**Comment by karalabe** [comment]
Can you send me some logs from before the crash? It seems that a new logging method is crashing, but I'm unsure what scenario could have lead to it.

**Comment by karalabe** [comment]
The only scenario I can see from the code if an already existing block is being attempted to be written twice after one another. It may be some bug in the miner. I'll keep looking tomorrow :)

**Comment by rfikki** [comment]
@karalabe 
Unfortunately I was running with the default verbosity at the time of the crash:
The info prior to the crash is not helpful as you can see below:

 
INFO [03-02|00:54:59] Imported new chain segment               blocks=1   txs=0   mgas=0.000  elapsed=7.503ms   mgasps=0.000   number=619241 hash=780870â€¦c1feab
INFO [03-02|00:54:59] commit new work on block 619242 with 0 txs & 1 uncles. Took 996.8Âµs
 
INFO [03-02|00:55:21] Imported new chain segment               blocks=1   txs=0   mgas=0.000  elapsed=11.499ms  mgasps=0.000   number=619242 hash=00a9e3â€¦30c1cf
INFO [03-02|00:55:21] commit new work on block 619243 with 1 txs & 0 uncles. Took 5.0007ms
 
INFO [03-02|00:55:32] Imported new chain segment               blocks=1   txs=1   mgas=0.025  elapsed=8.500ms   mgasps=2.997   number=619243 hash=15e651â€¦b9e85f
INFO [03-02|00:55:32] commit new work on block 619244 with 0 txs & 0 uncles. Took 999.8Âµs
 
INFO [03-02|00:55:32] ðŸ”—  mined block #619238 [cbd60cdfâ€¦] reached canonical chain 
INFO [03-02|00:55:38] Imported new chain segment               blocks=1   txs=0   mgas=0.000  elapsed=10.999ms  mgasps=0.000   number=619244 hash=5a491aâ€¦37108b
INFO [03-02|00:55:38] commit new work on block 619245 with 0 txs & 0 uncles. Took 500.3Âµs
 
INFO [03-02|00:55:45] Imported new chain segment               blocks=1   txs=0   mgas=0.000  elapsed=7.002ms   mgasps=0.000   number=619245 hash=985e97â€¦01076d
INFO [03-02|00:55:45] commit new work on block 619246 with 0 txs & 0 uncles. Took 499.1Âµs
 
INFO [03-02|00:55:58] Imported new chain segment               blocks=1   txs=0   mgas=0.000  elapsed=16.000ms  mgasps=0.000   number=619246 hash=825312â€¦99229e
INFO [03-02|00:55:58] commit new work on block 619247 with 0 txs & 0 uncles. Took 500Âµs
 
INFO [03-02|00:57:01] Imported new chain segment               blocks=1   txs=0   mgas=0.000  elapsed=6.000ms   mgasps=0.000   number=619247 hash=33a0e0â€¦e050df
INFO [03-02|00:57:01] commit new work on block 619248 with 3 txs & 0 uncles. Took 3.4994ms
 
INFO [03-02|00:57:18] Imported new chain segment               blocks=1   txs=3   mgas=0.067  elapsed=12.501ms  mgasps=5.392   number=619248 hash=bcd271â€¦a9b0fc
INFO [03-02|00:57:18] commit new work on block 619249 with 1 txs & 0 uncles. Took 3.0007ms
 
INFO [03-02|00:57:23] ðŸ”¨  mined potential block #619249 [3ecdcf7fâ€¦], waiting for 5 blocks to confirm 
INFO [03-02|00:57:23] commit new work on block 619250 with 0 txs & 0 uncles. Took 1.0011ms
 
panic: runtime error: index out of range

goroutine 16 [running]:
github.com/ethereum/go-ethereum/core.(*BlockChain).reorg(0xc042491500, 0xc04cde82d0, 0xc075c26750, 0x5688a3925709fa00, 0x8d2a8f8636c6321e)
	C:/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1153 +0x1c55
github.com/ethereum/go-ethereum/core.(*BlockChain).WriteBlock(0xc042491500, 0xc075c26750, 0xc0421d4e00, 0x0, 0x0)
	C:/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:838 +0x889
github.com/ethereum/go-ethereum/miner.(*worker).wait(0xc042423200)
	C:/gopath/src/github.com/ethereum/go-ethereum/miner/worker.go:298 +0x586
created by github.com/ethereum/go-ethereum/miner.newWorker
	C:/gopath/src/github.com/ethereum/go-ethereum/miner/worker.go:146 +0x4d4

**Comment by rfikki** [comment]
I changed verbosity to 6 and it happened again, hopefully this provides the needed info:
	Coinbase:	    3e8a2d7bbaeed188dd4aa5fcc8cbd4d80d835ae0
	Root:		    75f41fadc30457821cc3f5be9e8675ae97da5392d765583a2c78e2a19f9a370b
	TxSha		    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	ReceiptSha:	    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	Bloom:		    00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
	Difficulty:	    8095891
	Number:		    623880
	GasLimit:	    4712388
	GasUsed:	    0
	Time:		    1488501662
	Extra:		    Ùƒ	„geth‡go1.7.4‡windows
	MixDigest:      cc6a55b986f965f72dcfcdbab5db51d81c92d406a5b37c54719d097584405ccd
	Nonce:		    052985bc7c8bee31
]
Transactions:
[]
Uncles:
[Header(5c1f2c0418195f1f7889893d77a2eb16202e6433a51a945e3f20550f50cd8f78):
[
	ParentHash:	    1aff951f0ddf0e87c5687cb6896f67e1b4212732e27ae77c17a6b976913a0cab
	UncleHash:	    1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
	Coinbase:	    5cc37a404fdf8e6ad905993ea4e2fcb160621a42
	Root:		    44d13cda74e7d0f0b415e28d545521af165d27265de2f3758be8ead23383305c
	TxSha		    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	ReceiptSha:	    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	Bloom:		    00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
	Difficulty:	    8115657
	Number:		    623878
	GasLimit:	    4712388
	GasUsed:	    0
	Time:		    1488501577
	Extra:		    Ùƒ„geth‡go1.7.4‡windows
	MixDigest:      3a5ffad5c7fc23c4c00a49ea54103efc39a730e7537050932732b141031f0302
	Nonce:		    09bdbb6c6fd0fdbb
]]
}
 
INFO [03-02|18:42:27] commit new work on block 623884 with 1 txs & 0 uncles. Took 2.5004ms
 
DEBUG[03-02|18:42:27] (re)started agent[7]. mining...
 
TRACE[03-02|18:42:27] propagated block b804de3f to 2 peers in 2562047h47m16.854775807s 
TRACE[03-02|18:42:27] Processed block #623883, base price is 18181818181
 
DEBUG[03-02|18:42:27] (re)started agent[6]. mining...
 
DEBUG[03-02|18:42:27] Trie cache stats after commit            misses=77098 unloads=38
panic: runtime error: index out of range

goroutine 52 [running]:
github.com/ethereum/go-ethereum/core.(*BlockChain).reorg(0xc042638000, 0xc0a466a000, 0xc0a2644000, 0xad7ca23fd8168400, 0xa8ce6d73f05e81a1)
	C:/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1153 +0x1c55
github.com/ethereum/go-ethereum/core.(*BlockChain).WriteBlock(0xc042638000, 0xc0a2644000, 0xc042a1bf00, 0x0, 0x0)
	C:/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:838 +0x889
github.com/ethereum/go-ethereum/miner.(*worker).wait(0xc042b078c0)
	C:/gopath/src/github.com/ethereum/go-ethereum/miner/worker.go:298 +0x586
created by github.com/ethereum/go-ethereum/miner.newWorker
	C:/gopath/src/github.com/ethereum/go-ethereum/miner/worker.go:146 +0x4d4

**Comment by karalabe** [comment]
Could you try running with this? https://github.com/ethereum/go-ethereum/pull/3738

The crash is trivial, but I'm curious what's triggering it. This should print a red `ERROR` log if it hits that corner case that crashed the logger previously.

**Comment by mathcrypto** [comment]
I get same error each time i run geth as well

**Comment by karalabe** [comment]
@mathcrypto Could you please provide some logs, and also a Geth version number, OS details etc? Would be nice if you opened a new issue with it btw. Please make sure you're at Geth 1.6.5 too.

**Comment by mathcrypto** [comment]
this is the version Version: 1.5.9-unstable
Git Commit: fa99986143fe3dec08cdffcff9185e3700719edd
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.5
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.7.5/libexec

**Comment by mathcrypto** [comment]
should i change to version 1.6.5?

**Comment by mathcrypto** [comment]
@karalabe i have opened this issue #14614

**Comment by kciryt** [comment]
I have been getting the same issue when mining on ropsten overnight.  I am using the geth binary that was built from source.  Here is the info:

Geth
Version: 1.8.0-unstable
Git Commit: 3f40b22dac9cb36fdf2baacf4789a52adbb611fd
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.8


Things work fine, then:

`INFO [01-16|00:57:35] Commit new mining work                   number=2465606 txs=27  uncles=0 elapsed=19.225ms
INFO [01-16|00:57:42] Imported new chain segment               blocks=1 txs=24  mgas=2.277 elapsed=28.703ms  mgasps=79.313  number=2465606 hash=b38653…2e518c
INFO [01-16|00:57:42] Commit new mining work                   number=2465607 txs=17  uncles=0 elapsed=3.286ms
INFO [01-16|00:57:43] Imported new chain segment               blocks=1 txs=13  mgas=1.217 elapsed=32.142ms  mgasps=37.861  number=2465605 hash=957412…b2f232
INFO [01-16|00:57:47] Imported new chain segment               blocks=1 txs=6   mgas=0.317 elapsed=27.669ms  mgasps=11.441  number=2465607 hash=8d7a29…a1133b
INFO [01-16|00:57:47] Commit new mining work                   number=2465608 txs=19  uncles=1 elapsed=23.415ms
INFO [01-16|00:58:09] Imported new chain segment               blocks=1 txs=8   mgas=0.383 elapsed=58.261ms  mgasps=6.572   number=2465608 hash=271c60…d50cb3
INFO [01-16|00:58:09] Commit new mining work                   number=2465609 txs=27  uncles=0 elapsed=30.863ms
INFO [01-16|00:58:10] Imported new chain segment               blocks=1 txs=6   mgas=0.317 elapsed=21.112ms  mgasps=14.994  number=2465607 hash=44ba9f…a8dd96
panic: runtime error: index out of range
fatal error: panic on system stack

runtime stack:
runtime.throw(0x103e5e7, 0x15)
	/usr/lib/go-1.8/src/runtime/panic.go:596 +0x95
panic(0xedb000, 0x18c90d0)
	/usr/lib/go-1.8/src/runtime/panic.go:420 +0x7d6
runtime.panicindex()
	/usr/lib/go-1.8/src/runtime/panic.go:28 +0x5e
runtime.scanobject(0x80c46ae0ebd0, 0xc420024b28)
	/usr/lib/go-1.8/src/runtime/mgcmark.go:1256 +0x373
runtime.gcDrainN(0xc420024b28, 0xe040, 0x7fa74c7d02f8)
	/usr/lib/go-1.8/src/runtime/mgcmark.go:1174 +0x138
runtime.gcAssistAlloc1(0xc421fd8000, 0xe040)
	/usr/lib/go-1.8/src/runtime/mgcmark.go:545 +0x127
runtime.gcAssistAlloc.func1()
	/usr/lib/go-1.8/src/runtime/mgcmark.go:459 +0x33
runtime.systemstack(0xc420028600)
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
	/usr/lib/go-1.8/src/runtime/proc.go:1132

goroutine 1492697 [GC assist marking]:
runtime.systemstack_switch()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:281 fp=0xc428010a08 sp=0xc428010a00
runtime.gcAssistAlloc(0xc421fd8000)
	/usr/lib/go-1.8/src/runtime/mgcmark.go:462 +0x144 fp=0xc428010a48 sp=0xc428010a08
runtime.mallocgc(0x40, 0xe7f9a0, 0xc4283e2901, 0xc42ce38540)
	/usr/lib/go-1.8/src/runtime/malloc.go:596 +0x9d7 fp=0xc428010ae8 sp=0xc428010a48
runtime.makeslice(0xe7f9a0, 0x4, 0x8, 0xa654de, 0xc428010d28, 0x20)
	/usr/lib/go-1.8/src/runtime/slice.go:54 +0x7b fp=0xc428010b38 sp=0xc428010ae8
math/big.nat.setBytes(0x0, 0x0, 0x0, 0xc42ce38580, 0x20, 0x20, 0x20, 0x20, 0xc42ce384e0)
	/usr/lib/go-1.8/src/math/big/nat.go:1206 +0x150 fp=0xc428010b78 sp=0xc428010b38
math/big.(*Int).SetBytes(0xc428010e78, 0xc42ce38580, 0x20, 0x20, 0x20)
	/usr/lib/go-1.8/src/math/big/int.go:388 +0x63 fp=0xc428010bd0 sp=0xc428010b78
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).mine(0xc4200a64d0, 0xc45579f8c0, 0x0, 0x6c0cd3aedf3c893d, 0xc43061daa0, 0xc43061db00)
	/home/tyrick/dev/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:131 +0x4d9 fp=0xc428010f68 sp=0xc428010bd0
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).Seal.func1(0xc422358320, 0xc4200a64d0, 0xc45579f8c0, 0xc43061daa0, 0xc43061db00, 0x0, 0x6c0cd3aedf3c893d)
	/home/tyrick/dev/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:72 +0x87 fp=0xc428010fa8 sp=0xc428010f68
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc428010fb0 sp=0xc428010fa8
created by github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).Seal
	/home/tyrick/dev/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:73 +0x1e0

goroutine 1 [select, 159 minutes]:
`

I am attaching a log file as well.

[geth_mining_crash.txt](https://github.com/ethereum/go-ethereum/files/1635640/geth_mining_crash.txt)
