### ISSUE TITLE
Failure to parse custom genesis with big balance

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/go-ethereum#3734]
#### System information

Geth version: `Latest master`
OS & Version: Linux
Commit hash : 82e7c1d1241737fd0ae9b25e0f20857b8597b148

#### Expected behaviour

So far I have been using [this](https://gist.github.com/LefterisJP/d88cd2e7cdeef7b977960cdc805ee645) custom genesis json file with raiden and it was parsed fine in our tests.

#### Actual behaviour

Right now I am getting:
```
Fatal: failed to write genesis block: invalid balance for account 0xf0ef4707cdcf650f349cf664f2013f583484a3fb: "115792089237316195423570985008687907853269984665640564039457584007913129639936"
```

#### Steps to reproduce the behaviour

Just try to run geth with the provided genesis file

```
build/bin/geth --datadir ~/TEMP --networkid 1337 --fakepow init ~/TEMP/custom_genesis.json 
```
#### Extra notes:

I believe it has something to do with [this](https://github.com/ethereum/go-ethereum/commit/5c8fe28b725bd9b128edceae3215132ea741641b ) commit and most probably [this](https://github.com/ethereum/go-ethereum/pull/3699/files#diff-a1e94285d52758dbc393935ecc513efeR33) function.

**Comment by fjl** [comment]
115792089237316195423570985008687907853269984665640564039457584007913129639936 is 2 ^ 256, which is larger than 256 bits. I added protection against using values larger than 256 bits because they may not behave correctly in the EVM.

**Comment by fjl** [comment]
I would recommend using 2^256 - 1 as the balance.

**Comment by LefterisJP** [comment]
@fjl  Thanks Felix. Did not think of checking for the number of bits before opening the issue. Regardless thanks to your sanity check we found a bug in pyethereum.

**Comment by fjl** [comment]
The error message will improve shortly (I'm refactoring the genesis block parser).
