### ISSUE TITLE
Make RPC transaction options, value, gas and gasPrice accept a HEX value

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#374]
I'm not sure what are the current accept values, as the RPC docs don't state any. See https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_transact

To unify the ethereum.js we need the rpc endpoint accept HEX values for `gas`, `gasPrice` and `value`. Ethereuem.js will then convert integers and big num to the correct HEX value so its send to the RPC endpoint in HEX.

**Comment by tgerring** [comment]
What happens when you pass hex now?

What about integer?

**Comment by frozeman** [comment]
i don't know its silent , i get no response back anyway i guess

we can't use integer, as js can't handle very big numbers

**Comment by tgerring** [comment]
>  i get no response back anyway i guess

What input give you no response? Is there an error? Does the program crash?

**Comment by tgerring** [comment]
Here are calls to eth_transact with a gasPrice specified as a number, a number as string, and as a hex as string. For me, an integer was not accepted as valid ("Error: Could not decode arguments"), which appears to conflict with the problem you're having--or the problem isn't clear.

Number:
`$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_transact","params":[{"code":"0x600160008035811a818181146012578301005b601b6001356025565b8060005260206000f25b600060078202905091905056","gasPrice":10000000000000}],"id":1}' http://localhost:8080`
`{"id":1,"jsonrpc":"2.0","error":{"code":-32603,"message":"Error: Could not decode arguments: Error: Could not decode arguments"}}`

Number as string:
`$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_transact","params":[{"code":"0x600160008035811a818181146012578301005b601b6001356025565b8060005260206000f25b600060078202905091905056","gasPrice":"10000000000000"}],"id":1}' http://localhost:8080`
`{"id":1,"jsonrpc":"2.0","result":"0xe61f14e80fa518fbebc0f0648f20f77fc83e69f8"}`

Hex as string:
`$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_transact","params":[{"code":"0x600160008035811a818181146012578301005b601b6001356025565b8060005260206000f25b600060078202905091905056","gasPrice":"0x09184e72a000"}],"id":1}' http://localhost:8080`
`{"id":1,"jsonrpc":"2.0","result":"0xd5ca43952334c1402e69c67b5cd1e25ddade32e6"}`

**Comment by frozeman** [comment]
did the transaction was mined? because i didn't for me. therefore i thought the wrong interpreted gasPrice is the problem.

I will look with gustav tomorrow at it.

**Comment by obscuren** [comment]
@frozeman please confirm
