### ISSUE TITLE
truffle migrate on private network doesnot return

### ISSUE THREAD

**Issue by shikhahere** [ethereum/go-ethereum#3747]
#### System information

Geth version: Version: 1.5.9`
OS & Version:Linux (Ubuntu) - 
Commit hash : (if `develop`)

#### Expected behaviour
Truffle migrate is done successfully.

#### Actual behaviour
When truffle migrate is executed, on private geth it just gets stuck and doesnot return.
Geth Configuration:
geth --datadir ~/.ethereum/net42 init ~/Documents/genesis42.json
# Run this every time you start your Geth "42"
geth --datadir ~/.ethereum/net42 --networkid 42 --rpc --rpcport 8545 --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "eth,net,web3" console
~                                                                  

The transaction is always in pending state, and never gets completed.
I have tried quite a lot of options, but nothing really works, the geth node is mining, eth.mining returnd true

````

**Comment by night18** [comment]
You can use `miner.start()` on you Geth console, and make sure the account is unlocked and the port is same as the port in truffle.js
