### ISSUE TITLE
--light switch changes behavior of filters (eth_newFilter/eth_getFilterChanges)

### ISSUE THREAD

**Issue by paulperegud** [ethereum/go-ethereum#3752]
#### System information

Geth version: 
Version: 1.5.9-stable
Git Commit: a07539fb88db7231d18db918ed7a6a4e32f97450
Protocol Versions: [63 62]
OS & Version: Linux

#### Expected behavior
If from_block="latest", to_block="latest" are specified when creating filter, logs returned when polling with eth_getFilterChanges should contain meaningful blockHash and blockNumber.

#### Actual behavior
blockHash and blockNumber are null; "latest" value of from_block and to_block parameters is ignored

#### Steps to reproduce the behavior
1) run `geth --light`
2) create a new filter with eth_newFilter, with from_block="latest" and to_block="latest"
3) poll for incoming transactions with eth_getFilterChanges
4) observe that blockHash is null and blockNumber is null

#### Logs of communication between geth and web3.py
https://gist.github.com/paulperegud/5b75aa2499ab3813331952cd7f28b7f2

**Comment by karalabe** [comment]
As far as I know the light client doesn't yet support filters, but @zsfelfoldi please correct me.

**Comment by paulperegud** [comment]
@karalabe @zsfelfoldi As far as I can see, filters do work to some extent in light client. They work a little bit differently, erasing distinction between mined and not-yet-mined transactions.

**Comment by zsfelfoldi** [comment]
@paulperegud light client does support filters but it is still experimental, so it may have problems. I will look into why blockHash and blockNumber are null. Btw the logs generated by not-yet-mined (pending) transactions are not visible to the light client. There might be a solution to this in the future, I am doing some planning right now. Do you need pending logs for your application?

**Comment by paulperegud** [comment]
@zsfelfoldi No, I'm perfectly happy with having only logs of mined transactions. I don't need pending logs.

**Comment by Llorx** [comment]
I have a node running so I can connect to it via WebSockets and subscribe to `newPendingTransactions` and `newHeads` and do `eth_getTransactionByHash` and `eth_getBlockByNumber` calls, nothing more. If I understood correctly this issue, I'm not going to receive `newPendingTransactions` events, right?

Will the transactions be emitted to any other event (because of no distinction between pending and no pending, for example)? As far as I understand, I don't need to entire blockchain to receive the events.

**Comment by sraka1** [comment]
@zsfelfoldi any updates on this issue? Plans to support `newPendingTransactions` in `--light` mode? PRs accepted?
