### ISSUE TITLE
Adding enodes manually issue

### ISSUE THREAD

**Issue by RanenLiu** [ethereum/go-ethereum#3758]
#### System information

Geth version: `1.6.0-unstable-11539030`
OS & Version: Ubuntu
Commit hash : (if `develop`)

#### Expected behaviour
no prompt and the command execute successfully

#### Actual behaviour
Fatal: Unable to attach to remote geth: dial unix /tmp/BZZ/1488952776/bzzd.ipc: connect: connection refused

#### Steps to reproduce the behaviour
I want to learn swarm and when I run geth command as below, It didn't work. I did it as following:
1.build the datadir:
    DATADIR=/tmp/BZZ/`date +%s`
2.Create a new account with --testnet:
    geth --datadir $DATADIR --testnet account new
3.Adding enodes manually with geth command:
    geth --exec='admin.addPeer("enode://9ce417169fe509edd1bec381dacdae65ef16f395135c4ad79f8286a263ad58226be3ae0b1dc619edaa2c5420c2aed4bb22571fdac0453a37e2bfee5efe51c67c@13.74.157.139:30399")' attach ipc:$DATADIR/bzzd.ipc
prompt：the enode referenced page https://swarm-guide.readthedocs.io/en/latest/runninganode.html#adding-enodes-manually 

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
If you run geth, that will open the `geth.ipc` socket, whereas in your code you are trying to attach to `bzzd.ipc`

**Comment by RanenLiu** [comment]
@karalabe Yeah. But I saw the command in [https://swarm-guide.readthedocs.io/en/latest/runninganode.html#adding-enodes-manually](url), that's why I attached bzzd.ipc. 
Shoud I attach the geth.ipc instead of the bzzd.ipc?

**Comment by RanenLiu** [comment]
@karalabe And I replaced bzzd.ipc with geth.ipc but it still can't work. It's really strange.

**Comment by RanenLiu** [comment]
I solved it.
I found that I didn't run the geth command after I created the new account, so admin.addPeer can't find the geth.ipc or bzzd.ipc. That is why I can't get the expected result.
Thanks very much. @karalabe
