### ISSUE TITLE
Slow sync around block #588800 at ropsten testnet

### ISSUE THREAD

**Issue by infsaulo** [ethereum/go-ethereum#3761]
#### System information

Geth version: `1.5.9-stable`
OS & Version: Linux

#### Expected behaviour

I would expect to sync in a reasonable pace.

#### Actual behaviour

Taking a long time to sync testnet ropsten since blocks higher than #500000. Around 0.7Mg/s.

I'm running in a Ubuntu 16.04 server with 18GB of RAM memory, and basically I noticed the syncing process of my geth client has gotten really slow, importing 1 block per time at the pace above mentioned. 

The command I'm using is:
`geth --networkid 3 --rpc --rpcaddr "0.0.0.0" --rpcapi eth,web3,debug --ws --wsaddr "0.0.0.0" --wsorigins "*" --wsapi eth,web3,debug --cache=1024 --fast --jitvm`

Is there any specific reason why this is happening?

**Comment by fjl** [comment]
The ropsten network was attacked by spammers. We don't have an immediate solution, but there will be a non-PoW testnet that can't be attacked like this in the near future.
