### ISSUE TITLE
core/vm: use uint64 instead of *big.Int in tracer

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#3765]
Since the chance to `uint64` gas instructions over `*big.Int` the tracer got left behind and still requires `*big.Int`s as argument. The interpreter [is](https://github.com/ethereum/go-ethereum/blob/master/core/vm/interpreter.go#L121) [still](https://github.com/ethereum/go-ethereum/blob/master/core/vm/interpreter.go#L180) "converting" the `uint64` to `*big.Int` every time a trace log is emitted. This should be fixed.

**Comment by fjl** [comment]
Fixed title because "tracer" is not a package.
