### ISSUE TITLE
eth.getBlock('latest') doesn’t return anything when `geth --light` is synchronizing

### ISSUE THREAD

**Issue by kenshyx** [ethereum/go-ethereum#3767]
#### System information

Geth version: `1.5.9`
OS & Version: Ubuntu 16.04
Commit hash : (if `develop`)

#### Expected behaviour
It should return a value.

#### Actual behaviour
It hangs until geth is fully synchronized.

#### Steps to reproduce the behaviour
Start a fresh sync from 0 for `geth --light` then `geth attach` and run `eth.getBlock('latest')`.

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
It should definitely not hang. I think it's a bug already being addressed by @zsfelfoldi .

**Comment by zsfelfoldi** [comment]
Please try https://github.com/ethereum/go-ethereum/pull/3660

**Comment by fjl** [comment]
Tracked by https://github.com/ethereum/go-ethereum/issues/3639
