### ISSUE TITLE
BUG :: If I create account by personal_importRawKey then on every 2 transaction one keystore file is generated

### ISSUE THREAD

**Issue by himanshuoodles** [ethereum/go-ethereum#3768]
#### System information

Geth version: `geth version` 1.5.7
OS & Version: Linux
Commit hash : (if `develop`)

Every time address is written but keystore file is generated after every 2 account creation , 1 keystore file is not generated. Means one accounts file is not generated and next account file is generated . Suppose i send 100 hit of account creation 50 keystore file are generated but address is generated for all.
require('crypto').randomBytes(32, function(err, buffer) {
privateKey = buffer.toString('hex');
var headers = {

            'Content-Type': 'application/json'
        }

        var options = {
            url: "http://localhost:8000",
            method: 'POST',
            headers: headers
        }

        var req = http.request(options, function(res) {
            console.log('Status: ' + res.statusCode);
            console.log('Headers: ' + JSON.stringify(res.headers));
            res.setEncoding('utf8');
            res.on('data', function(body) {
                console.log('Body: ' + body);
                let response =JSON.parse(body);
                domain.User.query().insert({
                    email: recordObj.email,
                    ethPassword: recordObj.ethPassword,
                    accountAddress: response.result,
                    privateKey: privateKey
                }).then(function(data) {
                    console.log("Inserted data: ", data);
                    var databaseReturn = data;
                    resData.address = body;
                    resData.message = "Successfully account created"
                    callback(null, resData);
                });
            });
        });
        req.on('error', function(e) {
            callback(e, null);
            console.log('problem with request: ' + e.message);
        });
        // write data to request body
        let writeData = '{"jsonrpc": "2.0","method": "personal_importRawKey",  "params": ["' + privateKey + '","' + recordObj.ethPassword + '"],"id": 1  }';
        console.log(privateKey + " " + writeData)
        req.write(writeData);
        req.end();``

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Could you try testing this with Geth 1.5.9, or even the 1.6.0 develop builds? I've put in quite a lot of changes in 1.5.9 into account management, so would be nice to know if you see a similar behavior there too or not.

**Comment by himanshuoodles** [comment]
I confirm same behavior in in 1.6 as well as . and --autodag tag is also not working in 1.6 .

**Comment by himanshuoodles** [comment]
Please tell me where to look for change or debug in code , i will look it

**Comment by karalabe** [comment]
Autodag was removed. It is the default behavior. Will look into the
accounts.

**Comment by himanshuoodles** [comment]
Any progress .?

**Comment by bas-vk** [comment]
Based on your example I assume you are talking about `personal_importRawKey` and not account creation `personal_newAccount`? I tried to reproduce the problem with the following script.

```
#!/usr/bin/env sh

for i in {1..10}
do
	key=`head -c10 </dev/urandom|xxd -p -u`
	curl --data '{"jsonrpc": "2.0","method": "personal_importRawKey",  "params": ["'$key'","my passwd"],"id": '$i'}' localhost:8545
done
```

After the script finished the keystore contains all imported keys.
Could you clarify what you trying to do, perhaps give a couple of example requests?

**Comment by himanshuoodles** [comment]
Yes I am talking about personal_importRawKey . THis issue is when i do personal_importRawKey

**Comment by himanshuoodles** [comment]
Yes this script  is running fine now . Let me try what is was doing , then i will revert

**Comment by himanshuoodles** [comment]
working fine . If i get the test case i will ping here.
