### ISSUE TITLE
slow blockchain download

### ISSUE THREAD

**Issue by rPman** [ethereum/go-ethereum#3771]
Geth version: 1.5.9-stable-a07539fb (ubuntu xenial ppa:ethereum/ethereum)
OS & Version: ubuntu xenial

8Gb ram, entire for blockchain (ext4 data=writeback tested too) 3tb hdd toshuba 5600rpm, 

atop: DSK | sdd | busy 101% |  read 6760 |write 1406 | KiB/r 52 | KiB/w 244 | MBr/s 5.73  |MBw/s 5.60| avq     2.79 avio 7.27 ms |

~30sec per block, too slow (924540 blocks would downloaded in 1 year)

p.s. when used faster cpu,  ssd and 10Gb ram, also tested --cache 1024/8192, - speed increased 4x max, too slow yet
example log http://pastebin.com/nxd7mKLa

upd. using bcache with 51Gb ssd cache, --block=4k, sequential_cutoff=0, congested_read_threshold_us=0, congested_write_threshold_us=0 (~70mb/s cache load) give to me good result - **6.57 seconds per block** - ~3 month

**Comment by ubunteroz** [comment]
Are you trying to synchronize with testnet?

**Comment by rPman** [comment]
no i am not, i need a main ethereum blockchain to gather some data statistics and playing with btcrelay

**Comment by rPman** [comment]
upd. using bcache with 51Gb ssd cache, --writeback, have no changes to speed 
me also tested tmpfs withpage file to that ssd (.ethereum blockchain ~70Gb), also give to me no effect.

**Comment by fjl** [comment]
Slow full sync performance around the DoS attack is a known issue. We're still working on it ;)
