### ISSUE TITLE
geth --dev console: unable to deploy contract

### ISSUE THREAD

**Issue by DSofter** [ethereum/go-ethereum#3774]
#### System information

Geth version: `geth version`
```
Geth
Version: 1.5.9-stable
Git Commit: a07539fb88db7231d18db918ed7a6a4e32f97450
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.8/libexec
```
OS & Version: OSX

#### Expected behaviour
Something like this:
```
Contract mined! address: 0xdaa24d02bad7e9d6a80106db164bad9399a0423e
```

#### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/1687829/23584828/ab895e8e-0121-11e7-823f-5dde7ef4b9eb.png)

#### Steps to reproduce the behaviour
I know this comes up a lot, maybe I'm missing something here. I'm trying to get my hello world program running on dev net, and these are the steps I followed (according to https://ethereum.org/greeter):

```
pragma solidity ^0.4.9;

contract greeter {
    address owner;
    /* define variable greeting of the type string */
    string greeting;

    /* this runs when the contract is executed */
    function greeter(string _greeting) public {
        greeting = _greeting;
    }

    /* main function */
    function greet() constant returns (string) {
        return greeting;
    }
    
    /* this function is executed at initialization and sets the owner of the contract */
    function mortal() { owner = msg.sender; }

    /* Function to recover the funds on the contract */
    function kill() { if (msg.sender == owner) selfdestruct(owner); }
}
```

I got the compiled code from the online compiler: 
![image](https://cloud.githubusercontent.com/assets/1687829/23584826/9200d366-0121-11e7-80ae-70789af1a272.png)

Executed this with `loadScript` under `geth --dev console` and got this:
![image](https://cloud.githubusercontent.com/assets/1687829/23584828/ab895e8e-0121-11e7-823f-5dde7ef4b9eb.png)

which is not what the tutorial described `Contract mined! address: ...`.

I went ahead and assumed the `0x98ee3bbf859259c4092ec13d5ef90d3a77d24e54` returned is the contract address and ran the following code:
```js
var abi = [{"constant":false,"inputs":[],"name":"kill","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"greet","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":false,"inputs":[],"name":"mortal","outputs":[],"payable":false,"type":"function"},{"inputs":[{"name":"_greeting","type":"string"}],"payable":false,"type":"constructor"}];
var greeter = eth.contract(abi).at('0x98ee3bbf859259c4092ec13d5ef90d3a77d24e54');
greeter.greet();
```
and this is what I got:
![image](https://cloud.githubusercontent.com/assets/1687829/23584841/53c01d7c-0122-11e7-8d9f-4e36d1970a16.png)

Anything I'm missing?

**Comment by bas-vk** [comment]
There have been changes in web3 that is loaded into the console. This example *might* be outdated, @frozeman could you comment?

You can check if the contract was deployed successful by retrieving the source, `eth.getCode("0x98ee3bbf859259c4092ec13d5ef90d3a77d24e54")`. If you get '0x' something went wrong. I just deployed the greeter contract on the testnet and for me the snippet worked.

**Comment by DSofter** [comment]
@bas-vk I finally got my greeter running. `eth.getCode` returns me this:
```
"0x60606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806341c0e1b514610051578063cfae321714610063578063f1eae25c146100fc575bfe5b341561005957fe5b61006161010e565b005b341561006b57fe5b6100736101a2565b60405180806020018281038252838181518152602001915080519060200190808383600083146100c2575b8051825260208311156100c25760208201915060208101905060208303925061009e565b505050905090810190601f1680156100ee5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b341561010457fe5b61010c61024b565b005b600060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141561019f57600060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16ff5b5b565b6101aa61028f565b60018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156102405780601f1061021557610100808354040283529160200191610240565b820191906000526020600020905b81548152906001019060200180831161022357829003601f168201915b505050505090505b90565b33600060006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505b565b6020604051908101604052806000815250905600a165627a7a72305820ad9501427a12bbf3ba329ea61e9cdff1d36062516779da2e48c52240b6434fa50029"
```

When you said 
>  If you get '0x' something went wrong.
You mean "0x" not something starting with "0x" right?
