### ISSUE TITLE
standard_init_linux.go:178: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by manishlamichhane** [ethereum/go-ethereum#3775]
When I try to run the JSON RPC command, docker spits out this message in the console.

`standard_init_linux.go:178: exec user process caused "exec format error" `

I tried it with both Alpine and Latest image. Both have the same results.

`docker run -it -p 8545:8545 -p 30303:30303 ethereum/client-go --rpc --rpcaddr "0.0.0.0"`

is the command.

UPDATE: I was using a Raspberry PI 3.

**Comment by pabloesm** [comment]
From a Stackoverflow [question](http://stackoverflow.com/questions/42885538/raspberry-pi-docker-error-standard-init-linux-go178-exec-user-process-caused/42886112#42886112):


> Raspberries use ARM and not x86_64 processors. You can only run images created for that architecture. Try searching for ARM or ARMv7 on docker hub. There is a Debian image for ARM I know of but there must be others as well.
> 
> The underlying issue is that the binary format used by ARM is not compatible with x86_64, which is the architecture used by most desktop and server systems.

**Comment by IgorGanapolsky** [comment]
@pabloesm That is exactly the situation.  This issue can now be closed.

**Comment by manishlamichhane** [comment]
@pabloesm  I wasn't using the ARM image and now I understood that was the problem. Thanks for the reply!

**Comment by pabloesm** [comment]
Yes, I had the same issue... You're welcome, it's a pleasure to be helpful!
