### ISSUE TITLE
Feature req.: "make uninstall"

### ISSUE THREAD

**Issue by giacecco** [ethereum/go-ethereum#3785]
#### System information

Geth version: 1.5.4
OS & Version: Linux (Fedora 25)

#### Expected behaviour

```make uninstall``` should remove go-ethereum from the system and leave it clean.

#### Actual behaviour

```
$ sudo make uninstall
make: *** No rule to make target 'uninstall'.  Stop.
$
```

Alternatively, please share what files are installed where when doing ```make install```. Thanks.

**Comment by fjl** [comment]
We don't have an `install` target and don't want to add one at this time. Installing geth means copying one executable to a directory of your choice. There is no need for a script to automate this.
