### ISSUE TITLE
geth 1.5.9 is slower than geth 1.5.7 and 1.5.5

### ISSUE THREAD

**Issue by himanshuoodles** [ethereum/go-ethereum#3788]
#### System information

Geth version: `geth version` 1.5.9
OS & Version: Linux
Commit hash : (if `develop`)

I am creating a contract with geth 1.5.9 that transaction hash return average time is 450 ms while by previous version it was less than 40 ms . Why any reason for that ?

**Comment by karalabe** [comment]
Could you post your contract (or a sample one) that reproduces this behavior?

**Comment by karalabe** [comment]
Closing as not enough information to verify. Feel free to provide a repro contract for us to test and I'll reopen.
