### ISSUE TITLE
eth_compilers, eth_compileSolidity are gone in go-ethereum 1.6.0

### ISSUE THREAD

**Issue by beatrizsanchez** [ethereum/go-ethereum#3793]
#### System information

Geth version: v1.6.0-unstable-6d038e76/linux/go1.7.3
OS & Version: Linux/Ubuntu 16.04.1 LTS (x86_64)
Commit hash : 6d038e76

#### Expected behaviour
Running `eth.getCompilers()` in the geth console should return an array of compilers `['solidity']` that could even be empty ( `[]` )

#### Actual behaviour
The command returns `Error: The method eth_getCompilers does not exist/is not available` but I have started the node with `--ipcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3"` and I am able to run other `eth` commands. I was actually trying to execute the command via RPC with `web3j` and was getting an error then realized it didn't work in the console either.

```
> eth.compile
{
  lll: function(),
  serpent: function(),
  solidity: function()
}

```
#### Steps to reproduce the behaviour

1. Attach the console to a running node with -ipc enabled
2. Run `eth.getCompilers()`
3. If no compilers are installed you should get `[]`, not an error message

**Comment by fjl** [comment]
compiling via RPC has been removed in #3740 (see https://github.com/ethereum/EIPs/issues/209 for why). We will bring it back under a different method name if there is sufficient user demand. You're the second person to complain about it within 2 days, so it looks like there is demand.

**Comment by fjl** [comment]
Leaving this open so other people can find this issue and raise their voice here.

**Comment by beatrizsanchez** [comment]
@fjl, Thanks for the info. It would be convenient to have it on RPC but I have the issue as well on IPC, any idea why?

**Comment by fjl** [comment]
When I say RPC I mean the IPC endpoint too. The methods have been *removed* by the linked PR.

**Comment by hynese** [comment]
This feature is really useful. Can we please have the compilers available?

**Comment by mavstronaut** [comment]
Eth.compile is a great feature!

**Comment by islandBilly** [comment]
I too think eth.compile is a great feature, and it was an important part of my Dapp, so that people could generate a simple contract from a web form, compile and deploy it, all without knowledge of Solididty or the need to use Mist.

**Comment by kunalbansal92** [comment]
Updated my project due to this issue https://github.com/ethereum/solidity/issues/1708, And now :/

**Comment by vyorkin** [comment]
Also voting for bringing it back, at least we should update the official docs and tutorials

**Comment by RomanKrakowiak** [comment]
Living exactly the same situation as the comment above from vyorkin. Newcomer, confused by outdated official tutorial. 
~~also, please update the private network genesis block specifications in the official documentation please :p~~

**Comment by michiels** [comment]
Either way, the docs/website should reflect the latest state I think :) On this page https://www.ethereum.org/greeter it still assumes you're using solc.

**Comment by ropod7** [comment]
eth_compileSolidity, or analogue should be available over RPC . Please.

**Comment by GregoryFenn** [comment]
If the old console command has to go, can we not just replace it with a similarly named function that calls a solidity compiler? It just seems sensible that it's there. Or at least, make a tutorial for writing and making solidity apps that people can follow.

I was trying to hard to learn how to use geth or ethereum or anything. All the introductions I can find use Solidity [1]. This system is hard enough to follow or install as it is without all the documentation leading us down dead ends after DAYS AND DAYS of trying to install compilers that apparently don't exist now. So how are we meant to make or deploy smart contracts? This crypto tool has amazing potential but the impossibility of learning how to use or interact with it is terrible. 

I can run geth as a fast node on my windows 10 machine, and I have a command-line solc compiler on my MacBook. But I don't seem to be able to get both at once! 

Windows10: For example chocolaty now doesn't work, despite tutorials telling me its by far the easiest way to get solc on Windows. If instead I run ">npm install -g solc" ([2]) it seems to work but then when I run ">solc" it just says it's not recognised as a command, program or batch file. 
Running ">npm install solc" I get a series of warnings, starting with "npm WARN enoent ENOENT: no such file or directory, open 'LocalDir/package.json'".

MacBook: I think solc is working in Terminal, but without a tutorial I'm stuck with rookie errors in even compiling the "Hello World" of [1]. I describe this issue below in-between the 8 astrices.

[1] https://ethereum.org/greeter#getting-other-people-to-interact-with-your-code 
[2] https://solidity.readthedocs.io/en/develop/installing-solidity.html

********
/* Rookie error with compiling my first solidity program. */
SolidityProjects$ cat helloWorld.sol
pragma solidity ^0.4.1

contract mortal {
    /* Define variable owner of the type address*/
    address owner;

    /* this function is executed at initialization and sets the owner of the contract */
    function mortal() { owner = msg.sender; }

    /* Function to recover the funds on the contract */
    function kill() { if (msg.sender == owner) selfdestruct(owner); }
}

contract greeter is mortal {
    /* define variable greeting of the type string */
    string greeting;

    /* this runs when the contract is executed */
    function greeter(string _greeting) public {
        greeting = _greeting;
    }

    /* main function */
    function greet() constant returns (string) {
        return greeting;
    }
}

SolidityProjects$ solc helloWorld.sol 
helloWorld.sol:8:5: Error: Expected import directive or contract definition.
    function mortal() { owner = msg.sender; }
    ^
SolidityProjects$ 

********

**Comment by alphaqiu** [comment]
Sorry, but how to adding my contract into the gethereum in version of geth 1.6.0?

**Comment by jw122** [comment]
The [greeter tutorial](https://www.ethereum.org/greeter) (and the token, crowdfunding ones) is not yet updated for the changes in 1.6.0. 

It makes it harder for people who are trying to learn Ethereum to compile and run contracts. Please fix/advise

**Comment by KGutierrezTome** [comment]
Please bring back the old command line-compilers, they were very useful for testing

**Comment by dkhatter** [comment]
I too think eth.compile is a great feature, please bring it back to the latest version.

**Comment by temores** [comment]
many documents tutoriaIs, etc. point to command line compilers this change breaks them,I too spent DAYS trying to make this work. Please bring it back

**Comment by nakkapeddi** [comment]
Hi all,

Perhaps the following will help you.

To get a feeling of Solidity (not sure how up to date it is, but will give you an idea of syntax):
https://learnxinyminutes.com/docs/solidity/

In order to get the "Hello World" smart contract to work, you need to compile it with solc like so:
`solc -o output --bin --ast --asm test.sol`

where test.sol contains:
`
pragma solidity ^0.4.1;
contract mortal {
    /* Define variable owner of the type address*/
        address owner;

            /* this function is executed at initialization and sets the owner of the contract */
                function mortal() { owner = msg.sender; }

                    /* Function to recover the funds on the contract */
                        function kill() { if (msg.sender == owner) selfdestruct(owner); }
                        }

                        contract greeter is mortal {
                            /* define variable greeting of the type string */
                                string greeting;

                                    /* this runs when the contract is executed */
                                        function greeter(string _greeting) public {
                                                greeting = _greeting;
                                                    }

                                                        /* main function */
                                                            function greet() constant returns (string) {
                                                                    return greeting;
                                                                        }
                                                                        }
`

"output" can be an arbitrary directory on your machine. For more info, go here:

http://solidity.readthedocs.io/en/develop/using-the-compiler.html

Ignore the formatting, as I copied it from @GregoryFenn; the solidity lexer ignores whitespace so it doesn't matter. This will compile your contract.

**Comment by k26dr** [comment]
I use eth.compile.solidity for a custom deploy script, it was very useful, please bring back.

**Comment by bl4ck5un** [comment]
So how should I deploy contract via geth then?

**Comment by Tectract** [comment]
We're having downstream issues now because of this. Can you put those functions back, please?

**Comment by brobits** [comment]
[Ethereum.org's own greeter example is out of date now](https://www.ethereum.org/greeter), should update the docs to demonstrate the steps to compiling if these functions aren't restored

**Comment by Tectract** [comment]
This cost me two days of work to work-around. I don't understand why you guys would intentionally make it harder to compile smart-contracts. We're compiling client-side now...

**Comment by k26dr** [comment]
Since a lot of people are saying they're having a hard time finding a workaround. Here's a code snippet that will get you the same result without `eth.compile.solidity`

```
var fs = require('fs');
var exec = require('child_process').execSync;

exec(`solc --bin --abi --optimize -o bin contract.sol`);

var abi = fs.readFileSync('bin/contract.sol:Contract.abi');
var compiled = '0x' + fs.readFileSync("bin/Contract.bin");
```

**Comment by Tectract** [comment]
This solution won't work under react, and it also requires you to have solc installed locally. It won't work with metamask against ethereum mainnet, either. 

Here's my solution, see the full code at: www.github.com/tectract/ethdeployer

in the top-level .html file of my create-react-app:

```
    <script src="./browser-solc.min.js" type="text/javascript"></script>
```

and then in the code:

```
function loadWeb3() {
   let web3Injected = window.web3;
   if(typeof web3Injected !== 'undefined'){
     console.log("saw injected web3!");
     web3 = new Web3(web3Injected.currentProvider);
   } else {
     console.log("did not see web3 injected!");
     web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
     //console.debug(web3.eth.accounts);
   }
}
```

**Comment by k26dr** [comment]
Correct, my script is for server-side compilation via Node, it will not work client side.

**Comment by Tectract** [comment]
My script works completely client-side :) Totally standalone and no solc install required. Works against testrpc or against mainnet via metamask plugin. 

Also see: www.github.com/tectract/ethereum-demo-tools, and www.enledger.io/ethereum-demo-tools, www.enledger.io/EthDeployer

Note I'm linking against this minified, browserified version of browser-solc.min.js:

https://github.com/ericxtang/browser-solc

Cheers~

**Comment by adimarco** [comment]
Whether or not the compiler functionality is added back to `geth`, **please** update the documentation to reflect something that actually works.  

As it stands right now, all of the documentation most important to newcomers is horribly broken, and the path to getting a "hello world" smart contract up and running currently goes through this github thread complaining that nothing works.  That's not a way to attract more users.

**Comment by t2048** [comment]
Been writing C/C++ for 20 years, Node.JS for about a year, ended up here because all of the "write your first ethereum contract" tutorials don't work. Nice one guys. Guess I'll just waste a ton of time figuring it out.

**Comment by Tectract** [comment]
Hi there. This might help you along your way :)

https://blockgeeks.com/guides/how-to-learn-solidity/

**Comment by t2048** [comment]
@Tectract thank you!

**Comment by najmasor** [comment]
I also use eth.compile for different projects and would like to have the feature back...

**Comment by kwaazaar** [comment]
I find it very unprofessional that after two months, no one on the Ethereum team bothered to update the greeter-sample.

**Comment by Tectract** [comment]
I was angry about this at first, but then I realized that browser-solc usage is a fundamentally better solution for browser compilation, because it requires neither server-side nor client-side solc installation. 

The docs could be updated though, for sure.

**Comment by iwat** [comment]
This is stupid, bring it back or fix the tutorial.

**Comment by parunach** [comment]
If an important feature like this is changed, all relevant documents, tutorials, tests etc MUST be updated. One must address, "What is the work around for this?". Otherwise, few can use this.

**Comment by KellerL** [comment]
We would like to have the compile function back too! A colleague and I spend two complete days just to figure out that the function doesn’t work. @parunach I completely agree with you. What is the alternative to compile now?

**Comment by KidA001** [comment]
Developer here who is interested in learning about creating applications with ethereum. Every tutorial I've walked through is broken in some way, ended up here after following https://medium.com/@mvmurthy/full-stack-hello-world-voting-ethereum-dapp-tutorial-part-1-40d2d0d807c2 which seemed like a solid tutorial until it threw an error on `eth_compileSolidity`

It's going to be hard for the ethereum community to continue to gain support if there aren't any solid tutorials and if the org's own tutorials are borked...

**Comment by Tectract** [comment]
My tutorial works, I use client-side compilation. 

https://blockgeeks.com/guides/how-to-learn-solidity/

You can also simply use the EthDeployer with Metamask plugin:

http://www.enledger.io/EthDeployer

**Comment by 2cool4games** [comment]
I don't know if the changes compiling "with testrpc" makes compatibility problems with the Metamask Extension. 

I'm following a course on Pluralsight called Blockchain Fundamentals, and I'm having problems on the last two videos. A user posted a comment saying that something broke the compatibility of the course in some way. That's at least how I interpreted it. 

I'm trying to run the files that my instructor provided in the course, and everything compiles, migrates, and npm dev's through. But I get a spinning wheel in metamask when I'm trying to create a new smart contract in the course. 

I don't know if this is anything related to this, but I know for a fact that being a Smart Contract / Blockchain developer is a select field right now. So saying I'm waiting for the demand of developers to come, is kind of weird. While there is so little content on these subjects of developing a Cryptocurrency and Smart Contract. It's not like mainstream C++.

**Comment by Tectract** [comment]
related issue, they introduced a BUG this week in the solidity compiler...

https://github.com/ethereum/solidity/issues/2550

**Comment by Tectract** [comment]
@2cool4games Did you actually connect Metamask to the mainnet? If you are running a localhost node / testrpc node, you can just turn metamask off and the EthDeployer should connect to your local node and run just fine without metamask.

**Comment by KellerL** [comment]
@Tectract Thanks a lot! You really helped me. It works with truffle on the TestRPC. However it migrates for ages on my own private network, unfortunately I had to cancel it. Is it normal that it takes so long?

**Comment by Tectract** [comment]
Thanks for this response. As noted above, right now there is a bug in the solidity compiler which throws erroneous warnings, and can prevent EthDeployer from working, temporarily until that bug is fixed either upstream or in EthDeployer itself (downstream). Are you seeing compiler warnings?

Otherwise, can you open the web console and report back on whether any errors are being kicked in the javascript console?

cheers~

**Comment by Tectract** [comment]
@KellerL you can alos try connecting to your localhost node VIA metamask, that might help you compile / deploy on your localhost node :)

**Comment by 2cool4games** [comment]
@Tectract I am really happy that you have responded to my post. I really really appreciate it!   (￣▽￣)ノ

Yea, I am using testrpc with metamask. In my "Blockchain Fundamentals Course" I also used Ethereum Blockchain Deployments too. I don't know whether to consider it a private or a public Blockchain. I think it's a Private Blockchain accessible to the internet. 

I ran my Ethereum Smart contract with testrpc on localhost 8080. I ran both the instructor's and my code, and both didn't work. I just had a spinning wheel in both of them, and it says in Metamask "Contract Published (Failed)"... Everything went correctly in his video, when he used Metamask in the video. Maybe the update did break something, or I'm doing something wrong. 

I just seen a spinning circle in Metamask that never ended. 

Thanks again :)

Sebastian.

**Comment by Tectract** [comment]
The default port should be 8545, not 8080...

**Comment by 2cool4games** [comment]
@Tectract 

My testRPC is on port 8545. And when I truffle compile, migrate, and npm run dev it runs the instructor's code on port 8080 (localhost:8080). 

Do you want the error messages from Metamask or Powershell? I would like to provide you the error messages, but I don't know where to look for them / which ones to share. 

Also if you want to take a look at my instructors code here's a link: https://drive.google.com/open?id=0B_-lAAL1mo__U0lHM2V3cGgtSzA ... I am looking particularly at folder FoodSafe_WithCreateContract Folder. 

Thank you! Have a awesome day!

Sebastian

**Comment by Tectract** [comment]
please open the browser "developer console", you should see some stuff going through there in the javascript console. Possibly useful error messages :)

**Comment by ucfyao** [comment]
oh，my god 。I see a lot of tutorials using this！The official docs and tutorials！！！

**Comment by juniway** [comment]
Please update the wiki documents

**Comment by Tectract** [comment]
EthDeployer updated to ignore (sometimes erroneous) warning messages from solc. Working again:

https://www.enledger.io/ethDeployer/

See: https://github.com/ethereum/solidity/issues/2525#issuecomment-314742767

**Comment by 2cool4games** [comment]
@Tectract I upgraded the Geth version, and I'm still having problems with Metamask. It's doing the same thing as before. I am trying to take pictures of the "Developer Console", on the actual Metamask window, and the Create Smart Contract Page. 

I am going to try to update truffle too. I don't know if that will help or not. I'm not entirely sure. 

Thanks for all the help Tectract! 

Sebastian

**Comment by Tectract** [comment]
Sounds like a metamask problem, I suggest you start a ticket here: https://github.com/MetaMask/metamask-plugin/issues

This thread is for the issue of solc not being included in the ethereum node ;)

**Comment by Akki9326** [comment]
Not able to compile solidity code. any work around, please. I am trying with this method.
`web3.eth.compile.solidity(source)`

> The method eth_compileSolidity does not exist/is not available

**Comment by Tectract** [comment]
See here for working client-side code for solc compilation:

https://github.com/Tectract/EthDeployer/blob/master/src/Deploy.js

**Comment by Remi-Tuy** [comment]
I have still not found any viable solution...
This is a joke, how can they disable a function that so many people use ....

**Comment by Tectract** [comment]
Did you look at the links I posted?

**Comment by snissn** [comment]
FYI i get this error in the ethereum wallet when trying to a deploy a contract through the wallet (https://wallet.ethereum.org/deploy-contract)

**Comment by hdiedrich** [comment]
Thanks @k26dr - I think the "contract.sol:" in the `fs.readFileSync` path should go. 

Wouldn't that work with solcjs? That's way faster to install.

**Comment by k26dr** [comment]
@hdiedrich The way the solc compiler operates on Linux, that's what works for me. I already had solc installed so I used that method. I haven't looked into solcjs

**Comment by andyl** [comment]
so this tutorial has been broken for FIVE MONTHS ??  can it be ??

**Comment by Tectract** [comment]
You should start a ticket about fixing the tutorial, maybe. This one is about getting the compiling back into Geth, or figuring out workarounds for people. See my tutorial linked above. It still works.

**Comment by mikemilano** [comment]
More human hours wasted here. I agree, if it can't be fixed, fix the tutorial or add an a warning that it's outdated at least.

**Comment by trevorbroad** [comment]
mine as well weigh in here... I too am now encountering this issue. I'm sure the Ethereum team is busy and all, but outdated docs and tutorials for new devs learning a new language and platform is just bad form. Please update the tutorial or compiler

**Comment by trevorbroad** [comment]
The tutorial has a workaround listed under "USING THE ONLINE COMPILER"

It's definitely not as slick as I imagine the compile function was, but it will get you through the tutorial

**Comment by n0-m4d** [comment]
a working tutorial is essential!

**Comment by Tectract** [comment]
For the time being, please see how I compile solidity code CLIENT-SIDE, using web3 and browser-solc, here:

https://blockgeeks.com/guides/how-to-learn-solidity/

Until they resolve the issue of solc not being included in Geth, browser-solc is the way to go.

**Comment by spawn66336** [comment]
Because geth deprecated the command-line compiler interface after version 1.6, I was puzzled for a long time.I wrote a simple tutorial to describe how to compile and deploy a contract after geth1.6. 
Hope this tutorial will help you.
[Depoly contract on the private chain](http://blog.csdn.net/weixin_40401264/article/details/78136346)

**Comment by zioalex** [comment]
Please update the HelloWorld documentation to reflect how it is today.

**Comment by pranoygn** [comment]
As of now you can use the following command which generated .abi and .bin files which can be loaded using loadScript() locally 

solc -o . --bin --abi <your_file.sol>

**Comment by tRosJan** [comment]
I am still trying to understand why this was removed. The least you could do is update all documents to reflect changes. Thanks

**Comment by carlosotgz** [comment]
Add 1 hour to the pile of wasted human hours!

**Comment by mingard** [comment]
+1

**Comment by educob** [comment]
This is a nightmare. Nothing works.
Every solution I try fails.
Thanks ethereum people for that crap docu and stupid changes.

**Comment by katopz** [comment]
So this is why https://github.com/ethereum/web3.js/blob/develop/example/contract.html#L20 not work am I right?

**Comment by trevorbroad** [comment]
Anyone having difficulty compiling their code, download the Ethereum Wallet. In the Contracts tab, in the Deploy New Contract feature there's a function to compile your contract before uploading it to the Blockchain.

**Comment by bellsrik** [comment]
How to download the ethereum wallet? There is no option to download it. When are these guys going to update the documentation?

**Comment by zachgoll** [comment]
7 months later and still no eth.compile() function nor an update on the tutorial.  #bringbacketh.compile()
![screen shot 2017-11-02 at 4 59 22 pm](https://user-images.githubusercontent.com/16676157/32354642-97f1fb42-bff8-11e7-818d-f35298f37215.png)

**Comment by trevorbroad** [comment]
@zachgoll I commented above, use the compiler in Ethereum Wallet

**Comment by meoknu** [comment]
i demand for it

**Comment by magicliang** [comment]
I haven't read through all along this  thread, but, I have to say that, the SDKs of Java/.Net CLR, always provide compiler with runtime together. I thought it is practical standard for programming  runtime. And a lot of document is out-of-date,  if you remove this important feature, can you just push an update of doc at the same time? This is like a distributed transaction  failure causing inconsistency.

**Comment by RoguePlanetoid** [comment]
Seems odd to remove something that the tutorials depend on, what is the work around for this, to get started with a contract have to start somewhere, if can't get a Hello World example to work because of this it makes it hard to get going

**Comment by zachgoll** [comment]
WORKAROUND: https://www.youtube.com/watch?v=cRg2m2A2NGM

**Comment by temirov** [comment]
Anyone knows where is the source code of this page: https://www.ethereum.org/greeter and who can fix the glaring error? cc: @vbuterin

**Comment by frewinchristopher** [comment]
Working update as of 4th December 2017:

Alright everyone... let's _calm down_... languages like C++ (and respective communities) have been around for decades, Solidity has been around for years... the newest version at that, for just _months_. Plus, the Ethereum core team [is literally 3 people](https://www.ethereum.org/foundation). Sheesh, give 'em a break.

With that said, all you need for the greeter example to compile is the `solc` command line tool:

`npm install -g solc`

Then, you can use the command line tool from `solc` to compile to binary:

***NOTE: on the commandline, the command is `solcjs` _NOT_ `solc`!

`solcjs --bin --abi --optimize -o bin hello_world.sol`

(I named my solidity file `hello_world.sol`)

And **pit pat piffy wing wong wang just like that<sup>1</sup>**, you've got your compiled binaries and contract ABIs in the folder `bin/`:

```
hello_world_sol_greeter.bin
hello_world_sol_greeter.abi
hello_world_sol_mortal.bin
hello_world_sol_mortal.abi
```

BONUS: to get perfect linting for the code (the original example will compile just fine, but with warnings), add `public` to the top two functions and the last function, and `pragma` on the first line. The final code then looks like this:

```
pragma solidity ^0.4.19;

contract mortal {
  /* Define variable owner of the type address */
  address owner;

  /* This function is executed at initilization and sets the owner of the contract */
  function mortal() public { owner = msg.sender; }

  /* Function to recover the funds on the contract */
  function kill() public { if (msg.sender == owner) selfdestruct(owner); }
}

contract greeter is mortal {
  /* Define variable gretting of the type string */
  string greeting;

  /* This runs when the contract is executed */
  function greeter(string _greeting) public {
    greeting = _greeting;
  }

  /* Main function */
  function greet() public constant returns (string) {
    return greeting;
  }
}
```

1. :joy: Anyone get [the reference?](https://bitcointalk.org/index.php?topic=375643.0)

**Comment by nfrankel** [comment]
Note that the official site [still documents the method](https://ethereum.gitbooks.io/frontier-guide/content/web3.html#web3ethgetcompilers), though.

**Comment by hamzadiaz** [comment]
Please bring back the feature, it's very useful for any kind of projects

**Comment by adriadrop** [comment]
Internet is full of examples with eth_compileSolidity used in compile function, so now every newbie trying to learn from examples on the web is failing. Some people just think its all about the code and can't think outside the box, it's not about the code but its about the people so whoever orchestrated this change has failed. You should first find out how people are using something you are about to change and how much are they using it and then carefully plan how to change it and also inform people where change is about to happen to change the code. This is not a way how to treat an open source project of this importance or maybe it is but it just sucks for community.

**Comment by VoR0220** [comment]
These are from the days when the compiler was coupled to the RPC layer...which imho is a big no no. But we had a big EIP discussion about this...someone feel free to take up the charge on the EIP.

**Comment by GregoryFenn** [comment]
I'm giving up entirely on Ethereum. It was a nice idea but it's become just another cryptocurrency like bitcoin and wasted its chance to be a great distrubuted computing language due to infuriating barriers to entry. I'm a moderaderly good python, C++ and C# programmer and have a PhD in Cyber Security, but for the life of me I can't get to grips with this ruddy software. Come back when you've got a working and accessible API to write and deploy DAPPs, add funds, check balances and search and use other DAPPs.

**Comment by Tectract** [comment]
please see how I compile solidity code CLIENT-SIDE, using web3 and browser-solc, here:

https://blockgeeks.com/guides/how-to-learn-solidity/

relevant source code is here:

https://github.com/Tectract/EthDeployer/blob/master/src/Deploy.js

This should be the standard until solc is added back into GETH, if ever, imho. My article was recently translated to Chinese too :)

**Comment by Tectract** [comment]
If you just need to compile and deploy a contract, you can use the tool I wrote, running here:

https://www.enledger.io/EthDeployer/

Using Metamask and Chrome. It's not flawless, but I did recently updated it to handle deployment of ERC20 contracts.

**Comment by Gallaecio** [comment]
If the method is not supposed to exist, it should probably not be mentioned at https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial

**Comment by avatar-lavventura** [comment]
Is this normal:

```
> eth.getCompilers()
Error: The method eth_getCompilers does not exist/is not available
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```

**Comment by ibigbug** [comment]
> If the method is not supposed to exist, it should probably not be mentioned at https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial

And probably the official doc: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_compilesolidity ?
a little bit frastrated :(

**Comment by karalabe** [comment]
https://github.com/ethereum/EIPs/issues/209
