### ISSUE TITLE
SHA256 mismatch when installing Solidity with Homebrew

### ISSUE THREAD

**Issue by beatrizsanchez** [ethereum/go-ethereum#3796]
#### System information

OS & Version: OSX (10.12.3)

#### Actual behaviour
Running :
```
brew tap ethereum/ethereum
brew install solidity
```
returns 
```
Error: SHA256 mismatch
Expected: 542a0613f700ff2bd58932307c96a89a702541eb84c8c6bfe3817e70df55ac24
Actual: a1103f91d240101a90c9bec5243f2436563d3772c4571a352ea7bc21de8706d1
```

I was following [these](https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial) instructions. I am not sure if it is a brew issue, but since I have already updated, upgraded and cleaned it up I think it might not be so.

**Comment by fjl** [comment]
We can't fix track this here because it's not related to go-ethereum.

**Comment by fjl** [comment]
Please reopen this in the https://github.com/ethereum/homebrew-ethereum repo.

**Comment by beatrizsanchez** [comment]
Thanks! I didn't really know where to ask. Apparently it has been open for a few days now https://github.com/ethereum/homebrew-ethereum/issues/106
