### ISSUE TITLE
mist not connecting to network

### ISSUE THREAD

**Issue by noflag** [ethereum/go-ethereum#380]
I've had it running for a while, it's not showing any peers or downloading the blockchain. Does anyone have online peers I can add manually? Port 30303 is forwarded.

**Comment by obscuren** [comment]
The peer discovery protocol should automatically connect to peers (and bootstrap nodes). When you restart Mist does it connect to something?

**Comment by noflag** [comment]
No, no connections. Here is the command-line output

mist
+++ genesis +++
Root: 7e204dc9cfb7acdf062ff0b8052f7fcb0b7e6593754773967932ce458d134af3
Hash: 32d9162f861a01bc8274e70b3cdb9d688fd7d8566f2f8c25cf1a882f244081c4
2015/02/24 13:57:53 [CHAIN] Last block (#0) 32d9162f861a01bc8274e70b3cdb9d688fd7d8566f2f8c25cf1a882f244081c4 TD=0
2015/02/24 13:57:53 [CLI] Main address c7c9ffd105dda8b27b5f46df3109fa77761581a8
2015/02/24 13:57:53 [RPC-HTTP] Starting RPC-HTTP server on port 8545
ETH stack took 279.532571ms
2015/02/24 13:57:53 [CLI] Starting  Mist/v0.9.0/linux/go1.2.1
2015/02/24 13:57:53 [GUI] Starting GUI
2015/02/24 13:57:53 [P2P Server] Starting Server
2015/02/24 13:57:53 [JSRE] Could not load file: src/github.com/ethereum/go-ethereum/cmd/mist/assets/ext/bignumber.min.js
2015/02/24 13:57:53 [JSRE] started
2015/02/24 13:57:55 [P2P NAT] mapping error: no devices discovered
2015/02/24 13:57:55 [P2P Discovery] Listening,  enode://32d464e4213657675ef4dab68c03ff64fb59fdd25706e2c7f0d765134fb6ae61aa8c21214597e8cd80ec10373d9f78771b1893654b9c4981402ba2802f4a76dc@108.38.20.16:30303
2015/02/24 13:57:55 [Blockpool] Started
2015/02/24 13:57:55 [SHH] Whisper started
2015/02/24 13:57:55 [P2P Server] Listening on [::]:30303
2015/02/24 13:57:55 [SERV] Server started
2015/02/24 13:57:57 [P2P NAT] mapping error: goupnp: SOAP request got HTTP 500 Internal Server Error
2015/02/24 13:58:04 catalog.qml:87: :20:"loaded?"
2015/02/24 13:58:04 browser.qml:461: :20:"loaded?"
2015/02/24 13:58:55 [MINER] committing new work with 0 txs
2015/02/24 13:58:55 [MINER] (re)started agent[0]. mining...
2015/02/24 13:58:55 [MINER] (re)started agent[1]. mining...
2015/02/24 13:58:55 [MINER] (re)started agent[2]. mining...
2015/02/24 13:58:55 [MINER] (re)started agent[3]. mining...
2015/02/24 13:59:06 [JSRE] stopped
2015/02/24 13:59:06 [GUI] Stopped
2015/02/24 13:59:06 [TXP] Stopped
2015/02/24 13:59:06 [Blockpool] Stopping...
2015/02/24 13:59:06 [RPC-HTTP] Shutdown RPC-HTTP server
2015/02/24 13:59:06 [RPC-HTTP] Error on RPC-HTTP interface: accept tcp 127.0.0.1:8545: use of closed network connection
2015/02/24 13:59:06 [Blockpool] Stopped
2015/02/24 13:59:06 [SERV] Server stopped

**Comment by noflag** [comment]
I'd like test with manually adding peers if someone can post some

**Comment by tgerring** [comment]
Are you able to connect to peer `enode://6cdd090303f394a1cac34ecc9f7cda18127eafa2a3a06de39f6d920b0e583e062a7362097c7c65ee490a758b442acd5c80c6fce4b148c6a391e946b45131365b@54.169.166.226:30303` ?

**Comment by noflag** [comment]
no effect

**Comment by alexvandesande** [comment]
I have the same issue. Also tried connecting to taylor's node.

Here's the output of command line: https://gist.github.com/alexvandesande/fb272b51c00366f75040

I am behind a single "technicolor" router right now, but not a VPN. Yesterday I was using that router + airport base station and had the same issues.

**Comment by tgerring** [comment]
I rebuilt the Go bootnode (54.169.166.226) using latest from develop, however I'm still getting "Connection refused" when trying to connect from local Mist installation.

The log on the server is being added to, so it seems it's making some connections.

**Comment by fjl** [comment]
> Port 30303 is forwarded.

Do you forward the port manually in your router configuration?

In this case, could you try running with `-nat extip:<YOUR IP>` on the 
command line?

**Comment by fjl** [comment]
"Connection refused" is ok for the Go bootnode. It does not accept TCP connections.

**Comment by noflag** [comment]
I used -nat, i'm showing one peer but they blockchain isn't downloading yet

**Comment by noflag** [comment]
it seems to only download blocks while i'm mining. still only one peer. manually adding the one above didn't work

**Comment by obscuren** [comment]
@felix progress?

**Comment by noflag** [comment]
I fixed a problem with the qt5.4.1 repo not workin but there's no improvement

**Comment by noflag** [comment]
It starts working with both extip and external port are set via command line

**Comment by obscuren** [comment]
Could you try latest `develop` branch?

**Comment by noflag** [comment]
I can't get it to compile, running this script: https://gist.github.com/tgerring/d4ab3f1672ed91a53c6c

when running "go restore" it segfaults

**Comment by tgerring** [comment]
Should that be `godep restore` ?

**Comment by noflag** [comment]
yeah, thats what i did

**Comment by noflag** [comment]
it looks like those instructions on the wiki are outdated. i'm using the dev ppa now, i'll start a new issue
