### ISSUE TITLE
Return "VM error" in core.ApplyMessage

### ISSUE THREAD

**Issue by wuestholz** [ethereum/go-ethereum#3804]
Currently, `core.ApplyMessage` only returns the "consensus error". It would be useful to also return the "VM error". This would require a minor change in `core.ApplyMessage`, `core.TransitionDb` and their callers. I'd be happy to make those changes. Are there any concerns about making such a change?

**Comment by karalabe** [comment]
@obscuren any feedback on this?

I'm guessing that would be a different error path (i.e. not the same error return as consensus errors for obvious reasons). It might be a useful thing for the gas estimation too.

**Comment by nazilover** [comment]
Skip to content
This repository

    Pull requests
    Issues
    Gist

    @nazilover

471
3,327

    1,170

ethereum/go-ethereum
Code
Issues 278
Pull requests 42
Projects 4
Wiki
Pulse
Graphs
Labels
Milestones

    Unlock account from other Node
    #3821 opened 8 hours ago by EasonWang01
    2
    Signed transaction printing could crash
    #3819 opened a day ago by adriamb
    1
    pow: failed to generate mapped ethash cache "FlushFileBuffers: The handle is invalid."
    #3815 opened 2 days ago by rfikki
    @karalabe
    Return "VM error" in core.ApplyMessage
    #3804 opened 4 days ago by wuestholz
    1
    solc exit status 1 must provide a file
    #3799 opened 6 days ago by friends110110
    1
    eth_compilers, eth_compileSolidity are gone in go-ethereum 1.6.0
    #3793 opened 8 days ago by beatrizsanchez
    5
    geth crashes on launch "Killed: 9"
    #3792 opened 8 days ago by davidvartan
    1
    core/state: unreasonable logic when change state object's property
    #3791 opened 8 days ago by rjl493456442
    4
    Android Light client fails to connect private network
    #3789 opened 9 days ago by sumanxp
    @zsfelfoldi
    1
    geth 1.5.9 is slower than geth 1.5.7 and 1.5.5
    #3788 opened 9 days ago by himanshuoodles
    1
    geth --dev console: unable to deploy contract
    #3774 opened 13 days ago by DSofter
    @frozeman
    1
    feat: Find transaction by contract address
    #3769 opened 16 days ago by dan-turner
    BUG :: If I create account by personal_importRawKey then on every 2 transaction one keystore file is generated
    #3768 opened 16 days ago by himanshuoodles
    5
    --light switch changes behavior of filters (eth_newFilter/eth_getFilterChanges)
    #3752 opened 19 days ago by paulperegud
    @zsfelfoldi
    4
    swarm: write support for fuse mount feature swarm
    #3751 opened 20 days ago by jmozah
    @jmozah
    truffle migrate on private network doesnot return
    #3747 opened 20 days ago by shikhahere
    1
    out-of-date examples on Contract Tutorial wiki page
    #3732 opened 24 days ago by cdetrio
    2
    OpenWRT install go-ethereum
    #3724 opened 25 days ago by EasonWang01
    15
    For every 30000 block the geth stop mining for 20 minutes
    #3710 opened 29 days ago by himanshuoodles
    7
    Geth not broadcasting transactions and not mining pending transactions on private network
    #3694 opened on Feb 21 by lococholo
    7
    debug.setHead() expects a hex not dec
    #3691 opened on Feb 20 by hrishikeshio
    3
    Why IPC peer can't connect RPC peer
    #3678 opened on Feb 16 by EasonWang01
    6
    About find private network peers
    #3676 opened on Feb 15 by EasonWang01
    2
    Potential regression in event listing
    #3663 opened on Feb 11 by jvah
    1
    Value: "0x" Decoded: Failed to decode output: Error: Invalid offset: 0 bug
    #3653 opened on Feb 7 by hrishikeshio 1.5.9
    @bas-vk
    6

ProTip! Add no:assignee to see everything that’s not assigned.

    Contact GitHub API Training Shop Blog About 

    © 2017 GitHub, Inc. Terms Privacy Security Status Help

**Comment by wuestholz** [comment]
@karalabe @obscuren Yes, these seem to be different errors. I have created a PR here that should implement that change: https://github.com/ethereum/go-ethereum/pull/13844. It would be great if you could have a look.

**Comment by obscuren** [comment]
`ApplyMessage` should not be returning Virtual Machine errors. If you want to get virtual machine level errors you should be using the `runtime` package instead.

May I ask why you need VM errors, perhaps I can point you in the right direction.

**Comment by obscuren** [comment]
`ApplyMessage` errors are, as you correctly pointed out, **consensus errors only** for obvious reasons. If an error is returned by `ApplyMessage` we can safely assume that applying the transaction will result in invalid state transition.

Going your suggested route means that this assumption no longer holds. We'd have to check for errors (types) to figure out whether the returned error is a consensus error or merely an EVM returned error. This is tedious and error prone.

**Comment by wuestholz** [comment]
@obscuren Thank you very much for the clarification. I was using the `runtime` package so far by invoking `evm.Call` or `evm.Create` directly. However, `core.ApplyMessage` seems to also provide some additional features, such as checking for consensus errors and performing refunds. That's why I was tempted to reuse that existing functionality. Is there similar such functionality in the `runtime` package or would it make sense to move that functionality there?

**Comment by obscuren** [comment]
`Call` and `Create` in package `runtime` are explicit functions, `ApplyMessage` on the other hand is dynamic (it does whatever the message/tx tells it to) + some other functionality. That functionality doesn't really belong in the `runtime` package.

If you really need EVM errors *and* need all of the functionality provided by the state transition model you're out of luck I'm afraid.

I've been thinking about this, though not specifically this issue but rather EVM errors in general; another approach would be to collect all errors generated during the runtime of the EVM (including sub-calls) and expose them through an API. So for example instead of using `ApplyMessage` directly you'd "reimplement" it:

```go
st := core.NewStateTransition(evm, msg, gp)
st.TransitionDb()
errors := st.EVM().Errors()
```

*(please note `st.EVM().Errors()` doesn't exist`)*

`errors` would then contain all of the errors generated during the runtime of the virtual machine.

You are welcome to implement this but please bear in mind that this may not have a negative impact on the runtime (within a 1.5% margin). You may compare implementations using `go test ./tests -run=- -bench . -benchmem` and can compare results by redirecting the output of `go test` to a file and use the `benchcmp` tool. My workflow usually:

```sh
# hack
$ git commit -am "tmp"
# subsequent changes will: git commit --amend --no-edit
$ go test ./tests -run=- -bench . -benchmem > /tmp/new.txt
$ git checkout HEAD^1
$ go test ./tests -run=- -bench . -benchmem > /tmp/old.txt
$ benchcmp /tmp/old.txt /tmp/new.txt
# results
```

Hope this helps.

**Comment by wuestholz** [comment]
@obscuren Thank you very much for elaborating and for the suggestions!

I re-read your earlier comment and I'm not quite sure I understand your reasoning completely. In my PR I added a separate return value for the VM error. It seems like this shouldn't be too tedious for a caller. In particular, one would not need to look at the types of errors to distinguish between the two types of issues (i.e., consensus vs. VM execution). Do I miss something?

Note that, for now, I only want to know if the outermost call resulted in an error. An alternative design would store that error in a field of `StateTransition`. For instance, that would involve changing the following code (in `TransitionDb`):

```
if vmerr != nil {
		log.Debug("VM returned with error", "err", err)
```

to something like this:

```
if vmerr != nil {
		log.Debug("VM returned with error", "err", err)
                self.vmerr = vmerr
```

Would you prefer that design?

I'd be happy to make those changes.

**Comment by obscuren** [comment]
> It seems like this shouldn't be too tedious for a caller. In particular, one would not need to look at the types of errors to distinguish between the two types of issues (i.e., consensus vs. VM execution). Do I miss something?

we loose the simple assumption that errors indicate invalid state transition (i.e. consensus failure). With your proposal we add technical debt to a critical part of the system.

Image that you'd have to do

```go
err := core.ApplyMessage(...)
if err != nil && err != SomeVMError {
     panic("oh noes")
}
```

In every part of the code which calls `ApplyMessage`. This is a problem for maintaining in the long run as it's easy to *just* dismiss that error in future calls not to mention external contributors and API users. It also sets to bar for what is "acceptable" to return as error, basically anything. Imagine having to do:

```go
err := core.ApplyMessage(...)
if err != nil && (err != VmErrorOne || err != VMErrorTwo || err != ...) { /* ... */ }
```

This will become a maintenance hell and I'm willing to bet that at some point will result in erroneous code. 

What we have to understand here is that the errors returned by the EVM usually don't matter to the state transition -- with the exception of the very first *balance error* -- and that the transition may carry on.

Unfortunately I'd have to object to the second proposal as well. VM errors really should not be kept by the `StateTransition` and feels very hacky.

Do you see a problem with my earlier proposal?

**Comment by wuestholz** [comment]
@obscuren Thank you very much for the detailed explanation. I fully agree with what you are saying about a solution that "mixes" different errors in a single return value. However, that's not what I had in mind.

Both solutions that I proposed clearly separate the two types of errors by either returning them via two different return values or by exposing the VM error via a separate getter on `StateTransition` (e.g., `VMErrorLastMessage()`. Your code snippets would, for instance, look like this:

```
err, vmerr := core.ApplyMessage(...)
if err != nil {
     panic("oh noes")
}
if vmerr != SomeVMError {
    ...
}
```

Note, that it would probably be better to change the order of the two types or errors (e.g., `err, vmerr`  to `vmerr, err` in the above snippet) to communicate more clearly that `err` is critical for this API and should not be ignored. The VM error can then be seen as additional information that some clients may find useful, just like the gas used or the return value of the call. Would that make more sense to you?

**Comment by wuestholz** [comment]
@obscuren About your earlier proposal: it seems it would require some extra bookkeeping to know if any of the errors is the outermost one (i.e., there could be many inner errors that are handled while not resulting in a failure of the outermost call). Other than that and the potential performance impact I don't see an issue. My alternative proposal is in some sense inspired by it since it only keeps track of the outermost error, which avoids the performance penalty. Would that be fine with you if the getter for accessing that error would be in `st.EVM()`?

**Comment by fjl** [comment]
This is now implemented, though not quite in the same way.
