### ISSUE TITLE
error 32600, EOF, when using `echo ${json} |nc -U ${datadir}/geth.ipc`

### ISSUE THREAD

**Issue by dindinw** [ethereum/go-ethereum#3810]
#### System information
Geth
Version: 1.5.9-stable
Git Commit: a07539fb88db7231d18db918ed7a6a4e32f97450
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.4
OS: darwin

#### Expected behaviour
the `echo ${json} |nc -U ${datadir}/geth.ipc` should answer json method call. 

#### Actual behaviour
error message `{"jsonrpc":"2.0","error":{"code":-32600,"message":"EOF"}}`

#### Steps to reproduce the behaviour
```
$ nc -U ~/Library/Ethereum/geth.ipc
{"jsonrpc":"2.0","method":"rpc_modules","params":[],"id":1}
{"jsonrpc":"2.0","id":1,"result":{"admin":"1.0","debug":"1.0","eth":"1.0","miner":"1.0","net":"1.0","personal":"1.0","rpc":"1.0","txpool":"1.0","web3":"1.0"}}
^C
$ echo '{"jsonrpc":"2.0","method":"rpc_modules","params":[],"id":1}' |nc -U ~/Library/Ethereum/geth.ipc
{"jsonrpc":"2.0","error":{"code":-32600,"message":"EOF"}}
```

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Thanks for reporting!
