### ISSUE TITLE
update https://github.com/ethereum/go-ethereum/wiki/Management-APIs

### ISSUE THREAD

**Issue by dindinw** [ethereum/go-ethereum#3811]
`echo '{"jsonrpc":"2.0","method":"modules","params":[],"id":1}' | nc -U $datadir/geth.ipc`
should be
`echo '{"jsonrpc":"2.0","method":"rpc_modules","params":[],"id":1}' | nc -U $datadir/geth.ipc`

`modoles` will get a error message `The method modules_ does not exist/is not available`

**Comment by fjl** [comment]
done, thanks.
