### ISSUE TITLE
pow: failed to generate mapped ethash cache "FlushFileBuffers: The handle is invalid."

### ISSUE THREAD

**Issue by rfikki** [ethereum/go-ethereum#3815]
#### System information
Windows 64bit
INFO [03-23|17:41:35] instance:Geth/GETH DEVELOP ROPSTEN/v1.6.0-unstable-8771c306/windows/go1.8 
INFO [03-23|17:41:35] Allocated cache and file handles         database=C:\\projects\\ethereum_develop_ropsten\\testnet_data\\testnet\\geth\\chaindata cache=1024 handles=1024
INFO [03-23|17:41:35] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10}"
INFO [03-23|17:41:35] Disk storage enabled for ethash caches   dir=C:\\projects\\ethereum_develop_ropsten\\testnet_data\\testnet\\geth\\ethash count=3
INFO [03-23|17:41:35] Disk storage enabled for ethash DAGs     dir=C:\\Users\\Rocky\\AppData\\Ethash                                           count=2
INFO [03-23|17:41:35] Initialising Ethereum protocol           versions="[63 62]" network=3
INFO [03-23|17:41:35] Loaded most recent local header          number=746567 hash=ded604â€¦9725ca td=203907048383631
INFO [03-23|17:41:35] Loaded most recent local full block      number=746567 hash=ded604â€¦9725ca td=203907048383631
INFO [03-23|17:41:35] Loaded most recent local fast block      number=746567 hash=ded604â€¦9725ca td=203907048383631
WARN [03-23|17:41:35] Blockchain not empty, fast sync disabled 
INFO [03-23|17:41:35] Starting P2P networking 

#### Expected behaviour
No Error Message

#### Actual behaviour
ERROR[03-23|17:41:39] Failed to generate mapped ethash cache   epoch=25 err="FlushFileBuffers: The handle is invalid."

#### Steps to reproduce the behaviour
Run Geth!!!

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
Turned out to be an upstream bug in the memory mapping library we use. However even with fixing it there was an error on windows as it cannot rename open files (opposed to Linux and macOS), so I've reworked so it closes/renames/reopens. This should solve both issues (as an explicit flush is no longer necessary). Will push in a moment.

**Comment by rfikki** [comment]
Thanks for the fix.
