### ISSUE TITLE
Signed transaction printing could crash

### ISSUE THREAD

**Issue by adriamb** [ethereum/go-ethereum#3819]
I'm doing some hacks with geth, a panic was generated and I've been investigating a litte...

deriveSigner (core/types/transaction.go#L43) does not set the `chainIdMul` field,

`return EIP155Signer{chainId: deriveChainId(V)}`

and this field is requiered in PublicKey(tx *Transaction)  (core/types/transaction_signing.go#L139)

`V := byte(new(big.Int).Sub(tx.data.V, s.chainIdMul).Uint64() - 35)`

The stack trace for that is:

  Transaction.String()
  -> deriveSigner()
  -> Sender(signer Signer, tx *Transaction) 
  ---> EIP155Signer.PublicKey(tx *Transaction)

so, changing deriveSigner to:

`return NewEIP155Signer(deriveChainId(V))`

solves the issue.

I don't know it has some effect on production enviroments, nonetheless maybe
maintainers could check it.

**Comment by fjl** [comment]
Thanks!
