### ISSUE TITLE
mist aggressive webcache

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#386]
mist webcache persistence seems to be very aggressive; even persisted after restarts and removing ~/.ethereum

I would expect this to be more in line with cache in regular webbrowsers, or atleast have a way to clear cache

**Comment by tgerring** [comment]
@jorisbontje Just want to confirm that you're on Linux when removing `~/.ethereum`?

OS-specific data directories were implemented in https://github.com/ethereum/go-ethereum/pull/368 in case you're testing on a Mac (or Windows :scream_cat:)

**Comment by obscuren** [comment]
What do you mean by aggressive? Editing a web page and hitting refresh doesn't keep it in cache, it changes. Same goes for resources (JavaScript (files), images, etc)

**Comment by jorisbontje** [comment]
@tgerring yeah, I am deleting `~/Library/Ethereum/`.
@obscuren Let me show you: https://www.youtube.com/watch?v=hN3GXxgEXW0

**Comment by obscuren** [comment]
Right click -> reload is a default Qt chromium menu and doesn't work in 5.4 (it simply doesn't reload). Right click is bugged to begin with because it screws up the UI (fix WIP). Reloading by clicking in the URL bar and hit enter works fine as far as I can tell.

**Comment by jorisbontje** [comment]
@obscuren clicking the URL bar works only sometimes... http://youtu.be/hN3GXxgEXW0?t=1m49s

**Comment by obscuren** [comment]
right click is bugged. It locks up the ui to focus on the render engine. Don't right click and will work. 

Working on a fix for right click

**Comment by jorisbontje** [comment]
closing as mist is gone

**Comment by bellaj** [comment]
https://github.com/ethereum/mist/issues/418
