### ISSUE TITLE
SEC-11 Uncle validation does not correctly implement is-kin property

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#387]
The yellow paper equation 131 defines the "is-kin" property. Currently this is not correctly implemented, in the AccumulateRewards function at https://github.com/ethereum/go-ethereum/blob/develop/core/block_processor.go#L280

Specifically, it must check that the uncle hash is not one of the ancestors.

Also: the AccumulateRewards function accepts uncles which are siblings - share the same parent hash as the current block.

**Comment by obscuren** [comment]
Add

```go
ancestors.Has(uncle.Hash())
```
