### ISSUE TITLE
SEC-12 Block header validation function does not validate gas limit

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#389]
Rather than validating the gas limit value in the block header, a new value is calculated _for_ the block according to equation 39 in the yellow paper, and then this value is set to the gas pool available for the subsequent processing of transactions in the block.

https://github.com/ethereum/go-ethereum/commit/b155b9d80b1cb921c52c20e296f27039de3b069b**

**Comment by Gustav-Simonsson** [comment]
Re-opening since https://github.com/ethereum/go-ethereum/commit/ee0a1bec6c3ce942e51265535961ac6a745d33eb  since it does not match current version of YP with regards to a block header's canonical gas limit.

Specifically, it does not implement the equality check of a block header's canonical gas limit in the block header validity function as specified in equations 40, 41 and 46.

**Comment by obscuren** [comment]
We've defined looser gas limit validation. See https://ethereum.etherpad.mozilla.org/106 (8)

**Comment by Gustav-Simonsson** [comment]
https://github.com/ethereum/tests should be updated with the new algorithm. YP still needs an update though, will make a PR for it.

**Comment by Gustav-Simonsson** [comment]
This is still regressed; the new algorithm implementation calculates the value **for** the incoming block, rather than validating the block against the calculated value.
