### ISSUE TITLE
The PPA for Qt in the Ubuntu build instructions is offline

### ISSUE THREAD

**Issue by secret-bitcoin-login** [ethereum/go-ethereum#390]
The PPA referred to on this [Qt build page](https://github.com/ethereum/go-ethereum/wiki/Building-Qt) for installing the MIST browser under Ubuntu 14.04 is down (404 Error). It prevents the installation script [provided here under Automatic Build](https://github.com/ethereum/go-ethereum/wiki/Instructions-for-getting-the-Go-implementation-of-Ethereum-and-the-Mist-browser-installed-on-Ubuntu-14.04-%28trusty%29) from running. It's obvious that Ethereum devs don't control the PPA, but it might be necessary to find a replacement.

The linked PPA is: ppa:beineri/opt-qt54-trusty

[This is a link to the non-responsive PPA](http://ppa.launchpad.net/beineri/opt-qt54-trusty/ubuntu/).

**Comment by secret-bitcoin-login** [comment]
Found the problem with a little more poking. It has been migrated to a new version number - the correct PPA is ppa:beineri/opt-qt541-trusty

**Comment by tgerring** [comment]
Hello! Yes, the PPA location was migrated for the minor version bump. We're in the process of updating the docs, thanks for noticing this :smile:

**Comment by secret-bitcoin-login** [comment]
I just saw the update.. I see the page has been updated, and I assume you'll update the script as well. Thanks for being so responsive!

**Comment by tgerring** [comment]
Script updated in https://gist.github.com/tgerring/41275735ebb057b58ea8/a4b3c06bee8bab0364003a204747ddc31708c71d
Wiki updated in https://github.com/ethereum/go-ethereum/wiki/Building-Qt/5641ac55c22801b9c06996ae0095034d153663aa
