### ISSUE TITLE
no success mining

### ISSUE THREAD

**Issue by cslarson** [ethereum/go-ethereum#393]
on a clean install of mist (rm -rf ~/.ethereum /go* then run install script) i am able to connect to about 7 peers and approximately 1800 blocks are downloaded. the problem i'm having is that i seem unable to successfully be rewarded when mining, and am unable to test my dapp with mist because i don't have any ether. also, when i'm mining, blocks are processed and appended to my chain but i'm assuming they're blocks that weren't mined by me because haven't received a reward, though the block count only seems to go up when i'm mining. 
as an alternative solution, with alethzero i found it useful to use a private chain. are there directions on using a private chain with mist?
![mist](https://cloud.githubusercontent.com/assets/900470/6390689/530b1c7c-bda6-11e4-8e7d-5e229b20896b.png)

occasionally something like the following happens:
```
2015/02/26 10:58:26 [CHAIN] block #1887 process failed (fd84fe09)
2015/02/26 10:58:26 [CHAIN] BLOCK(fd84fe096faa8a3d42a74a1128a64698faad4cd157d23b411b98ee13f7deede8): Size: 311.00 B TD: <nil> {
NoNonce: 555efc6655845aad7bbe57d37d6882da5bf91713c46556e01bf70f1d010fb8e7
Header:
[

	ParentHash:	    1753986081bad50824bfd3a2865ed92abb28a44813a202744c5b1d4f317b0fc7
	UncleHash:	    1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
	Coinbase:	    09eec44487f5cebd1d1736d677fdbf07a38ea7d2
	Root:		    aeeede8fc7f87f4d94363a02a665fea5e39fadbbd6e874c56194c5c92878f75e
	TxSha		    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	ReceiptSha:	    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	Bloom:		    00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
	Difficulty:	    789476
	Number:		    1887
	GasLimit:	    157810
	GasUsed:	    0
	Time:		    1424948299
	Extra:		    
	Nonce:		    84a9719fcd7fee4740d82aad4607a70cbf3beebd268ddb94e69125b83f049f49

]
Transactions:
[]
Uncles:
[]
}

2015/02/26 10:58:26 [CHAIN] invalid merkle root. received=aeeede8fc7f87f4d94363a02a665fea5e39fadbbd6e874c56194c5c92878f75e got=a7cb2d509d096f1e04ba2645c8c5e34c122d7feba28c83a52850d2b92a8b82a9
```

**Comment by drcode** [comment]
Don't have your answers, but I think that the command line flag "-seed=false" is equivalent to private chain mining.

**Comment by obscuren** [comment]
The block issue has been fixed on the latest master and develop branch.

**Comment by jorisbontje** [comment]
not really.

**Comment by cslarson** [comment]
@drcode doesn't seem to work:
```
mist -seed=false -asset_path=$GOPATH/src/github.com/ethereum/go-ethereum/cmd/mist/assets
```
yields:
```
flag provided but not defined: -seed
```

**Comment by tgerring** [comment]
`bootnodes` is the param, but currently `-bootnodes=""` loads the default nodes, rather than not connecting to any

@fjl Can the param be updated to use default nodes when not supplied and no nodes when an empty string is passed?

**Comment by zelig** [comment]
If you do not wish to connect to any nodes, then use the `-maxpeer=0` parameter.
if you cannot listen (because of router/firewall etc), then `dial=false` option should do it too.

**Comment by cslarson** [comment]
neither maxpeer nor dial work for me. `-maxpeer=0` yeilds;
```
2015/02/27 18:47:31 [CLI] Fatal:  Server.MaxPeers must be > 0
```
and `dial=false` gives:
```
flag provided but not defined: -dial
```

**Comment by obscuren** [comment]
@jorisbontje Do elaborate. 

I've just re-checked current chain with both `master` and `develop` and both are working fine and catching up

**Comment by jorisbontje** [comment]
I am running `ethereum -rpc=true -loglevel=5 -mine=true`
go-ethereum version cdb77f0
I have 0% cpu load
There are no mining related msgs in the logs; only p2p, rpc and blockpool

(Note that `eth_mining` still returns `false` when running the CLI node even with the `-mine=true` argument  #323)

**Comment by obscuren** [comment]
https://github.com/ethereum/go-ethereum/commit/65cad14f9b27db396d036f47814d4843d947ac43 https://github.com/ethereum/go-ethereum/commit/fdf939a6f9b5360d76415c7118969d92af2774f9 should fix these issues
