### ISSUE TITLE
OSX - Mist shows outdated version numbers

### ISSUE THREAD

**Issue by kumavis** [ethereum/go-ethereum#395]
This is pretty minor, but felt it should be on our radar.

Installer shows POC6
![image](https://cloud.githubusercontent.com/assets/1474978/6397861/9da98b2e-bd9c-11e4-87cf-cb85dbf952d8.png)

`Mist.app` Shows POC5
![image](https://cloud.githubusercontent.com/assets/1474978/6397794/3685e71c-bd9c-11e4-8cc1-6a565cb8ac28.png)

**Comment by tgerring** [comment]
Looks like the image was updated in b4de14758964614b6955118164b8916a4c393475

The POC5 string is now updated to POC8 via 44eb6209833adc993dcdec74a8cf3592eeffa4fa

**Comment by kumavis** [comment]
@tgerring I'm getting my builds from here https://build.ethdev.com/builds/OSX%20Go%20develop%20branch/
Are these out of date?

**Comment by tgerring** [comment]
Pinging @caktux for above question about build server

There is a plan to merge the go-build repo (where this issue should _really_ have been opened :wink: ) into go-ethereum proper.

**Comment by kumavis** [comment]
Was not aware of the separate repo, makes sense

**Comment by caktux** [comment]
https://build.ethdev.com/builds/OSX%20Go%20develop%20branch/Mist-OSX-latest.dmg should have the right image and tag

**Comment by kumavis** [comment]
unless theres some weird caching going on...
![image](https://cloud.githubusercontent.com/assets/1474978/6398323/b07f55d2-bd9f-11e4-8b23-b520ae94d138.png)

**Comment by caktux** [comment]
uhm.. symlink is ok.. `Mist-OSX-latest.dmg -> Mist-OSX-20150226110835-0.8.5-54-a1c830c.dmg`

**Comment by kumavis** [comment]
`Mist-OSX-20150226110835-0.8.5-54-a1c830c.dmg` looks like this, so the problem goes deeper:

![image](https://cloud.githubusercontent.com/assets/1474978/6398494/e0de298c-bda0-11e4-987d-a0c2ee8638f5.png)

**Comment by kumavis** [comment]
If its just the background image this isnt a big deal but i suspect I'm getting old builds

**Comment by kumavis** [comment]
is the `a1c830c` a hash of the build or the latest git commit?

**Comment by caktux** [comment]
Of the git commit of go-ethereum, you can see the last build report and which commit hash was used here: https://build.ethdev.com/builders/OSX%20Go%20develop%20branch/builds/-1

**Comment by kumavis** [comment]
continued on https://github.com/ethereum/go-build/issues/11
