### ISSUE TITLE
Database version mismatch, resolution suggestion incorrect

### ISSUE THREAD

**Issue by kumavis** [ethereum/go-ethereum#397]
on OSX, when running `open /Applications/Mist.app/Contents/MacOS/Mist` in a situation where you get a  `Database version mismatch`, it suggests you to `rm -rf ~/.ethereum/database`. This does not resolve the issue. `rm -rf ~/.ethereum/` does resolve the issue, but may be overly destructive.

**Comment by obscuren** [comment]
Thanks. Do a `rm -rf ~/Library/Ethereum/database`

**Comment by zelig** [comment]
this won't cut it, the db dir is called blockchain :)

**Comment by obscuren** [comment]
@zelig feel free to fix
