### ISSUE TITLE
First run of Mist crashes

### ISSUE THREAD

**Issue by caktux** [ethereum/go-ethereum#399]
Since it also seems that we can't start `Mist.app/Contents/MacOS/Mist` on the first run, it's difficult to provide more debug information. That being said, when everything else is in order, Mist only opens on the second try and after.

**Comment by obscuren** [comment]
To be sure, when running the executable (MacOS) the first time the terminal produces also no output?

**Comment by caktux** [comment]
The app needs to be approved to run first, and so nothing gets executed unless it's started from the `.app`, hence the difficulty in getting debug information. I'll see if I can around this by codesigning it.

**Comment by maran** [comment]
I had no trouble running this directly via `/Applications/Mist.app/Contents/MacOS/Mist` even the first time. 

However, opening it officially by double clicking it does indeed result in a crash/closure of the app. I think I remember something like this happening on earlier builds as well. I will see if I can find out more.
