### ISSUE TITLE
Go Ethereum CLI Client always mines empty blocks

### ISSUE THREAD

**Issue by drcode** [ethereum/go-ethereum#400]
Hi, I'm running the latest code on develop. If I send over a new contract via the RPC interface and then run a private chain (seed=false) The contract is received by the client and I can then send transactions to the contract which behave correctly, but the contract is never mined (nor are any of the other transactions sent to the contract) After a new block is mined, the contract appears to be wiped out and gone... If I disable mining on the other hand, the contract lives indefinitely and can be used indefinitely (but of course still remains unmined)

Below is my output. Note where it says "[XETH] Contract addr ..." when I send over the contract. However, it never appears any of the subsequent mined blocks, they all have zero transactions. In fact, I have NEVER seen a block with a transaction in the CLI ethereum client when I'm mining, at least on a solo chain. (I am using GAS=50000 and GASPRICE=5 to create the contract)

ethereum -seed=false -rpc -mine 
2015/02/26 19:29:11 [CHAIN] Last block (#4307) 98454392b6f08b69253e5d78d444fe2973dcee9e4e457d98b0874f19857f196a TD=641912077
<nil>
2015/02/26 19:29:11 [CLI] Main address 07c97b1921df46300d316b9cf8ab18440527b0c0
2015/02/26 19:29:11 [CLI] Start mining
2015/02/26 19:29:11 [MINER] Starting mining operations
2015/02/26 19:29:11 [CLI] Starting Ethereum(G)/v0.8.2/linux/go1.2.1
2015/02/26 19:29:11 [P2P Server] Starting Server
2015/02/26 19:29:11 [RPC-HTTP] Starting RPC-HTTP server on port 8080
2015/02/26 19:29:11 [Blockpool] Started
2015/02/26 19:29:11 [SHH] Whisper started
2015/02/26 19:29:11 [P2P Server] Listening on [::]:30303
2015/02/26 19:29:11 [P2P Server] Attempting to map port 30303 with UPNP
2015/02/26 19:29:11 [SERV] Server started
2015/02/26 19:29:11 [MINER] Mining on block. Includes 0 transactions
2015/02/26 19:29:12 [POW] Hashing @ 7 khash
2015/02/26 19:29:13 [POW] Hashing @ 7 khash
2015/02/26 19:29:14 [POW] Hashing @ 7 khash
2015/02/26 19:29:15 [POW] Hashing @ 7 khash
2015/02/26 19:29:16 [POW] Hashing @ 7 khash
2015/02/26 19:29:17 [POW] Hashing @ 7 khash
2015/02/26 19:29:18 [POW] Hashing @ 7 khash
2015/02/26 19:29:19 [POW] Hashing @ 7 khash
2015/02/26 19:29:20 [POW] Hashing @ 7 khash
2015/02/26 19:29:21 [POW] Breaking from mining
2015/02/26 19:29:21 [MINER] Mining on block. Includes 0 transactions
2015/02/26 19:29:21 [XETH] Contract addr 8d1db117a1b0389e45822c3917992b9ad03b018d
2015/02/26 19:29:21 [RPC] Sending payload: {"id":1,"jsonrpc":"2.0","error":false,"result":"0x8d1db117a1b0389e45822c3917992b9ad03b018d"}
2015/02/26 19:29:21 [RPC] Sending payload: {"id":2,"jsonrpc":"2.0","error":false,"result":"0x07c97b1921df46300d316b9cf8ab18440527b0c0"}
2015/02/26 19:29:21 [RPC] Sending payload: {"id":3,"jsonrpc":"2.0","error":false,"result":"0xa87430ba828fb1335f3b729d36f6a11029dc4389b4deab030c0f73a2ad30e737"}
2015/02/26 19:29:21 [RPC] Sending payload: {"id":4,"jsonrpc":"2.0","error":false,"result":"0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"}
2015/02/26 19:29:21 [P2P Server] Port mapping error: write udp4: i/o timeout
2015/02/26 19:29:22 [CHAIN] processed block #4308 (6011bc1b...)
2015/02/26 19:29:22 [MINER] 🔨  Mined block 6011bc1b307481461e1084c4d794328ea9ef0119158010856348094ec1f3c53b
2015/02/26 19:29:22 [MINER] Mining on block. Includes 0 transactions
2015/02/26 19:29:22 [MINER] BLOCK(6011bc1b307481461e1084c4d794328ea9ef0119158010856348094ec1f3c53b): Size: 279.00 B TD: 642060506 {
Header:
[

	ParentHash:	    98454392b6f08b69253e5d78d444fe2973dcee9e4e457d98b0874f19857f196a
	UncleHash:	    
	Coinbase:	    07c97b1921df46300d316b9cf8ab18440527b0c0
	Root:		    e2078456a576a0011042aeb35cf5fe7a032b425215f51d96cef15fba43cf481b
	TxSha		    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	ReceiptSha:	    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	Bloom:		    00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
	Difficulty:	    148429
	Number:		    4308
	GasLimit:	    125000
	GasUsed:	    0
	Time:		    1425000561
	Extra:		    
	Nonce:		    fd53caa49fc82df80fc0b1f2777561a3af28d8f096c020731d4253429a49e24e

]
Transactions:
[]
Uncles:
[]
}

2015/02/26 19:29:22 [MINER] Mining on block. Includes 0 transactions
2015/02/26 19:29:22 [CHAIN] processed block #4309 (da866b69...)
2015/02/26 19:29:22 [MINER] 🔨  Mined block da866b697b69b41c8bca53586dabede30e4a1335f00ef6c8b7cac4591f8fae11
2015/02/26 19:29:22 [MINER] BLOCK(da866b697b69b41c8bca53586dabede30e4a1335f00ef6c8b7cac4591f8fae11): Size: 279.00 B TD: 642209079 {
Header:
[

	ParentHash:	    6011bc1b307481461e1084c4d794328ea9ef0119158010856348094ec1f3c53b
	UncleHash:	    
	Coinbase:	    07c97b1921df46300d316b9cf8ab18440527b0c0
	Root:		    56dcbafc646b7ec4fbff3fa099bb00cc83e509f0d24c45c2a8041fae9e01e4ea
	TxSha		    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	ReceiptSha:	    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	Bloom:		    00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
	Difficulty:	    148573
	Number:		    4309
	GasLimit:	    125000
	GasUsed:	    0
	Time:		    1425000562
	Extra:		    
	Nonce:		    a7de0ad26f9d486ee1e4cd902b8d14670d2f7003057f18fd969850d2f55c19ed

]
Transactions:
[]
Uncles:
[]
}

2015/02/26 19:29:22 [MINER] Mining on block. Includes 0 transactions
2015/02/26 19:29:22 [POW] Breaking from mining
2015/02/26 19:29:22 [POW] Breaking from mining
2015/02/26 19:29:22 [MINER] Mining on block. Includes 0 transactions
2015/02/26 19:29:23 [POW] Hashing @ 8 khash
2015/02/26 19:29:24 [POW] Hashing @ 7 khash
2015/02/26 19:29:24 [CHAIN] processed block #4310 (72c361a1...)
2015/02/26 19:29:24 [MINER] 🔨  Mined block 72c361a163ff5a29965c141af59c3dfac5be9755f058ae3c3fd849025693f78b
2015/02/26 19:29:24 [MINER] BLOCK(72c361a163ff5a29965c141af59c3dfac5be9755f058ae3c3fd849025693f78b): Size: 279.00 B TD: 642357797 {
Header:
[

	ParentHash:	    da866b697b69b41c8bca53586dabede30e4a1335f00ef6c8b7cac4591f8fae11
	UncleHash:	    
	Coinbase:	    07c97b1921df46300d316b9cf8ab18440527b0c0
	Root:		    25eb9b555b4c7b69079de495e8082754ab5deae6be53163d936bdb44c3fd7eb6
	TxSha		    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	ReceiptSha:	    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	Bloom:		    00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
	Difficulty:	    148718
	Number:		    4310
	GasLimit:	    125000
	GasUsed:	    0
	Time:		    1425000562
	Extra:		    
	Nonce:		    768e9dd03880c92ff5a0dbaf98a32381ed1eed0f932d48b3c0ba2e5115678ca9

]
Transactions:
[]
Uncles:
[]
}

2015/02/26 19:29:24 [MINER] Mining on block. Includes 0 transactions
2015/02/26 19:29:24 [MINER] Mining on block. Includes 0 transactions
2015/02/26 19:29:25 [POW] Hashing @ 7 khash
2015/02/26 19:29:25 [POW] Hashing @ 7 khash
2015/02/26 19:29:26 [POW] Hashing @ 7 khash
2015/02/26 19:29:26 [POW] Hashing @ 7 khash
2015/02/26 19:29:27 [POW] Hashing @ 7 khash
2015/02/26 19:29:27 [POW] Hashing @ 7 khash
2015/02/26 19:29:28 [CHAIN] processed block #4311 (787e77dc...)
2015/02/26 19:29:28 [POW] Breaking from mining
2015/02/26 19:29:28 [MINER] 🔨  Mined block 787e77dc36574b6ef083ce63dce4bb11e139729c183c9f57dc7c5a28f7cc811f
2015/02/26 19:29:28 [MINER] BLOCK(787e77dc36574b6ef083ce63dce4bb11e139729c183c9f57dc7c5a28f7cc811f): Size: 279.00 B TD: 642506660 {
Header:
[

	ParentHash:	    72c361a163ff5a29965c141af59c3dfac5be9755f058ae3c3fd849025693f78b
	UncleHash:	    
	Coinbase:	    07c97b1921df46300d316b9cf8ab18440527b0c0
	Root:		    8e79ca6e8209901739f5e65084ad076b5698f070010e44aded03681c8b3eaa69
	TxSha		    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	ReceiptSha:	    56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
	Bloom:		    00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
	Difficulty:	    148863
	Number:		    4311
	GasLimit:	    125000
	GasUsed:	    0
	Time:		    1425000564
	Extra:		    
	Nonce:		    3ce3fc715d71695b4ca67cd26610a64b0d81848bb9af640f59d67a4e369398ef

]
Transactions:
[]
Uncles:
[]
}

2015/02/26 19:29:28 [MINER] Mining on block. Includes 0 transactions
2015/02/26 19:29:28 [MINER] Mining on block. Includes 0 transactions
2015/02/26 19:29:29 [POW] Hashing @ 7 khash
2015/02/26 19:29:29 [POW] Hashing @ 7 khash
2015/02/26 19:29:30 [POW] Hashing @ 7 khash
2015/02/26 19:29:30 [POW] Hashing @ 7 khash
2015/02/26 19:29:31 [POW] Hashing @ 7 khash
2015/02/26 19:29:31 [POW] Hashing @ 7 khash
2015/02/26 19:29:32 [POW] Hashing @ 7 khash
2015/02/26 19:29:32 [POW] Hashing @ 7 khash
2015/02/26 19:29:33 [POW] Hashing @ 7 khash
2015/02/26 19:29:33 [POW] Hashing @ 7 khash
2015/02/26 19:29:34 [POW] Hashing @ 7 khash
2015/02/26 19:29:34 [POW] Hashing @ 7 khash
2015/02/26 19:29:35 [POW] Hashing @ 7 khash
2015/02/26 19:29:35 [POW] Hashing @ 7 khash
2015/02/26 19:29:36 [POW] Hashing @ 7 khash
2015/02/26 19:29:36 [POW] Hashing @ 7 khash
2015/02/26 19:29:37 [POW] Hashing @ 7 khash
2015/02/26 19:29:37 [POW] Hashing @ 7 khash
2015/02/26 19:29:38 [POW] Hashing @ 7 khash
2015/02/26 19:29:38 [POW] Hashing @ 7 khash

**Comment by obscuren** [comment]
You are not running develop. This is an old version.

**Comment by drcode** [comment]
Apologies- I'll be more careful making sure my builds are uptodate in the future before posting.

**Comment by obscuren** [comment]
No problem :-)
