### ISSUE TITLE
Add support for block tests

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#414]
Support for these tests: https://github.com/ethereum/tests/blob/develop/BlockTests/blValidBlockTest.json

Branch: https://github.com/Gustav-Simonsson/go-ethereum/tree/add_blockchain_tests2

Status: When running https://github.com/ethereum/tests/blob/develop/BlockTests/bcValidBlockTest.json the seedhash used by Go is not the one in the given block header, but the one from the preceding block, in this case the genesis block.

This mismatch of seedhash causes a mismatch in the generated ethash cache, giving different result of PoW verification which is logged as a PoW nonce mismatch.

This could be a problem with the pow.Chainmanager state, and may only apply to the actual blocktests and not when running the Go client in general.

**Comment by Gustav-Simonsson** [comment]
https://github.com/ethereum/go-ethereum/pull/426

**Comment by Gustav-Simonsson** [comment]
Update: Current progress is we have consensus up until PoW nonce.

**Comment by Gustav-Simonsson** [comment]
Update: with changes now merged into develop, we still get a mismatch on the PoW nonce. Debugging shows that all values passed to ethash_light is same as C++ except for the actual cache.

While C++ develop branch works with BlockTests/blValidBlockTest.json SimpleTx, it has a pending PR waiting with changes to ethash: https://github.com/ethereum/cpp-ethereum/pull/1304

The branch (918c1cd7998767d455876dd760094a47638a7340) in that PR is not currently building:

[17/03/15 13:44:49] Gustav Simonsson: [ 24%] Building CXX object libethcore/CMakeFiles/ethcore.dir/ProofOfWork.cpp.o
/home/gs/eth/cpp-ethereum/libethcore/Ethasher.cpp: In static member function ‘static bool dev::eth::Ethasher::verify(const dev::eth::BlockInfo&)’:
/home/gs/eth/cpp-ethereum/libethcore/Ethasher.cpp:104:24: error: ‘ETHASH_EPOCH_LENGTH’ was not declared in this scope
  if (_header.number >= ETHASH_EPOCH_LENGTH * 2048)
                        ^
/home/gs/eth/cpp-ethereum/libethcore/Ethasher.cpp:113:2: error: ‘ethash_quick_hash’ was not declared in this scope
  );
  ^
make[2]: *** [libethcore/CMakeFiles/ethcore.dir/Ethasher.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

Suggestion is to wait for C++ PR to be merged and the tests updated accordingly before we update Go (again).

**Comment by Gustav-Simonsson** [comment]
Update: We now have bcValidBlockTest.json "SimpleTx" passing block header validations (insert of the block works). However, the "dataTx" test in the same file runs into a gas validation:
```bash
2015/03/20 04:38:12 [BLOCK] TX err: out of gas! require 20000, have 2870
```

**Comment by Gustav-Simonsson** [comment]
Update: PR which adds post state validations, disables network and adds RPC flag: https://github.com/ethereum/go-ethereum/pull/537

We have a regression from last Friday in bcValidBlockTest.json "SimpleTx" :  
```bash
> ./ethereum blocktest /home/gs/eth/tests/BlockTests/bcValidBlockTest.json SimpleTx r
2015/03/21 20:30:42 [SERV] Protocol Version: 58, Network Id: 0
2015/03/21 20:30:42 [CHAIN] Last block (#0) fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca TD=0
2015/03/21 20:30:42 [POW] Making Cache
2015/03/21 20:30:44 [POW] Took: 1.411470917s
2015/03/21 20:30:44 [POW] Making Cache
2015/03/21 20:30:45 [POW] Took: 1.440854539s
2015/03/21 20:30:45 [CHAIN] INVALID block #1 (3d3e8a3b)
2015/03/21 20:30:45 [CHAIN] Difficulty check failed for block 131072, 131008
Fatal: Block Test load error: Difficulty check failed for block 131072, 131008

```

**Comment by obscuren** [comment]
All tests currently pass in `bcValidBlockTest` `JS_API`
