### ISSUE TITLE
SEC-14 single DB lookup table for all objects pose consensus security risk

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#416]
chain blocks and other things in global state are stored in a single LevelDB table called "blockchain"

An attacker can reference objects stored in the DB by putting the hash of the key in a block, e.g. a malicious miner can put a parent hash in an advertised block which is the hash of a key of another object in the DB, causing the Go client to fetch it.

This attack vector can lead to consensus forks due to unexpected behavior when an attacker forces reference to objects in invalid contexts.

Fix: use separate LevelDB table for each object type

**STATUS: OPEN**

**Comment by obscuren** [comment]
- [ ] State db
- [ ] Block db
- [ ] Settings db
- [ ] User settings?
