### ISSUE TITLE
SEC-15 Parent issue for all invalid data structures & missing type validations

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#417]
Currently there are several opportunities for an attacker to advertise Ethereum data structures not conforming to the yellow paper specs. For example, by advertising a coinbase address longer than 32 bytes, an attacker can cause a contract using the coinbase op code to execute a negative value transaction, similar to https://github.com/ethereum/go-ethereum/issues/342

Fix: Enforce strict one-to-one mapping between types defined in the yellow paper and the Go types. All block chain / consensus related code should operate only on these types. E.g. strict length validation for all data types and clearly encapsulate operations on them to get better confidence for semantic completeness.

See https://github.com/ethereum/go-ethereum/issues/501

**Comment by obscuren** [comment]
Fixed with `common.Hash` and `common.Address`
