### ISSUE TITLE
SEC-17 VM out of memory DoS

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#419]
An attacker can cause the Go client to to crash with Out of Memory exception by e.g. contract code pushing a large enough value on the stack.

While the gas costs for this should provide enough economic incentive to discourage contract code pushing very large values on the stack, we should enforce a limit to be absolutely sure this cannot happen.

Fix: Add a hard gas limit resulting in maximum slice allocation of e.g. 256MB.

**Comment by obscuren** [comment]
Stack has been limited to `1024`
