### ISSUE TITLE
Mining on Mist should not be a boolean on/off choice, rather a sliding scale.

### ISSUE THREAD

**Issue by alexvandesande** [ethereum/go-ethereum#424]
The eth.miner() object in mist only has the option stop() and start(), with no way currently to set how much mining your machine should do. In practice it means that it's currently only capable of two states: "off" and "turn all your computer fans to desperate mode".

The mining/network dashboard already supports a sliding scale in the interface, I only need a way to do that in go.

**Comment by maran** [comment]
`How much mining your machine should do`. Defined how? 

There is an option to set the amount of threads being used. Defaulting to the total amount of cores in your system. Perhaps you can leverage that with a slider? The max would be max amount of cores and the bottom 0 cores.

**Comment by alexvandesande** [comment]
The number of threads being used is good enough for me. Where can I access that in mist?

**Comment by alexvandesande** [comment]
Thanks taylor. I'll wait on that.

**Comment by tgerring** [comment]
@alexvandesande I don't know that my PR is the best way to handle it, but I thought it might poke the bear enough to move the conversation along. I know system-testing team had at one point requested similar type of controls

**Comment by alexvandesande** [comment]
Well, if your PR goes throught, I'll adapt my code to support it.
