### ISSUE TITLE
Contract function returning 0x for up to 20s after the contract was created

### ISSUE THREAD

**Issue by davidhq** [ethereum/go-ethereum#436]
Code: https://gist.github.com/davidhq/b051fdd308181a82bc73

What happens: http://cl.ly/image/3A0U3A1G2d0u

I ran the client with `ethereum -rpc=true -rpcport=8090 -dial=false -mine=true`

go-ethereum: stable 0.8.6-54, devel 0.8.6-54

**Comment by obscuren** [comment]
When a contract is created it takes a couple seconds to be mined. This means that within the time of creation and mined the contract isn't actually on the state yet unless you specify a different `defaultBlock`.

`defaultBlock` is defaulted to `-1` which means last block. When a transaction is created it's applied on the `0`ed block until it's mined which makes the `0`ed block the `-1` block, etc.

Is this the case?

**Comment by ralph-pichler** [comment]
After further tests I've found that the error happens if the contract is too big. Every call fails if the contract is bigger than 7616 bytes and everything works if it is less than that.

Here are 2 examples: https://gist.github.com/ralph-pichler/2147cbc3d31b308ec921

One is small enough too work, while the other is just too big and every call will fail.

**Comment by obscuren** [comment]
Not enough balance in the account to pay for the creation of the contract?

**Comment by ralph-pichler** [comment]
Doesn't work, even after mining several hundred blocks. Also I got the byte number wrong. The issues already start around 950 bytes not 7600. Also the contract is successfully created. The address is returned. It's just the calls afterwards that don't work.

**Comment by ralph-pichler** [comment]
Also the exact same example works flawlessly on cpp-ethereum. So its probably not a problem with the code or the js bindings.

**Comment by ralph-pichler** [comment]
Ok, problem solved. Turns out the contract creation did indeed run out of gas. It seems go-ethereum has a lower default gas amount than cpp-ethereum.
