### ISSUE TITLE
User action processes

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#439]
Some `Interface` needs to exist to query for user actions such as

- [x] Password input https://github.com/ethereum/go-ethereum/issues/338
- [x] Confirmation dialog https://github.com/ethereum/go-ethereum/issues/337

This relates to NatSpec (https://github.com/ethereum/go-ethereum/issues/486) & accounts (https://github.com/ethereum/go-ethereum/issues/280)

**Comment by zelig** [comment]
js console done, moved from frontier, added mist
