### ISSUE TITLE
Correct subdirectory used for keys and use os.Remove instead of RemoveAll

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#443]
The keys should be in a sub-directory in the datadir, and also usage of os.Remove instead of RemoveAll is better in case the key address is ever empty, to avoid accidentally deleting the whole (sub) directory.

**Comment by fjl** [comment]
The keys are now in `<datadir>/keys`.

**Comment by Gustav-Simonsson** [comment]
Re-opening since it still uses os.RemoveAll

**Comment by zelig** [comment]
fixed in #796
