### ISSUE TITLE
Unlock accounts from the command line

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#452]
`--unlock addr:pwd` or something similar

**Comment by fjl** [comment]
Please don't pass password on the command line. The command line args can be read by anyone.
Would be better to read the passphrases for the given accounts on startup.

**Comment by jorisbontje** [comment]
Insisting on user keyboard input on startup prevents `ethereum` to be used as daemon.

**Comment by obscuren** [comment]
Can't. These things can run like daemons. If you'd like to use this you'll have to do it on something that it's secure. 

It could be added in addition, but not just by it self

**Comment by fjl** [comment]
The way other tools handle this is by daemonizing after the password has been read. I think this is how nginx does it if the SSL server key is password protected.

But you are right in general, user input is not possible when running e.g. from an init script.
