### ISSUE TITLE
crash on mining in mist

### ISSUE THREAD

**Issue by kobigurk** [ethereum/go-ethereum#455]
mist crashes when trying to mine - either through the network panel or the mining panel.
this is the error log : http://goo.gl/QPvrqt 

ubuntu on develop

**Comment by obscuren** [comment]
I've just pushed to develop with a bunch of fixes. Could you check if the error persists?

**Comment by kobigurk** [comment]
still there, same error it seems.

**Comment by kobigurk** [comment]
I *guess* it's related to the fact I don't find any peers to connect to - if it helps to test it.

**Comment by kobigurk** [comment]
still happens - with blocks.

**Comment by obscuren** [comment]
Could you re-upload a pastie with the crash log. It has expired :-/

**Comment by kobigurk** [comment]
works now! generating DAG, and everything.

**Comment by obscuren** [comment]
Thanks
