### ISSUE TITLE
SEC-19 ECDSA recovery id (V) is casted from uint64 to single byte

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#456]
V can be treated as an integer everywhere it is used in the Go code, which avoids possibility of truncation of high bytes when casting from uint64 to (a single) byte.

See YP Appendix F.

**Comment by obscuren** [comment]
An integer in go is not a single byte. It's either `int32` or `int64` depending on the host. `V` should always be a single `byte`. I'll change the implementation to take a `byte` rather than an `uint64`.
