### ISSUE TITLE
SEC-20 VM program counter overflow

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#457]
The VM program counter is currently an uint64 in Go client, and it's size is unspecified in the YP.

In order to avoid consensus failure with regards to overflow semantics of program counter, the size must be specified in YP and then implemented in Go.

We discussed defining the size to 256 bits.

**Comment by obscuren** [comment]
We haven't settled on 256 bit, it was suggested. Gas costs will simply too high if it wants to overflow 64bit.

**Comment by obscuren** [comment]
@Gustav-Simonsson this issue should - if it hasn't already - also be created for the YP to specify a size for the PC.

**Comment by obscuren** [comment]
2^64 will be sufficient. Won't overflow.

**Comment by Gustav-Simonsson** [comment]
YP commit defining 256 bit: https://github.com/ethereum/yellowpaper/commit/4722ab5fa303d61ab0c37e1e9848963d461f2957
