### ISSUE TITLE
HMAC-SHA256 not used for KDF

### ISSUE THREAD

**Issue by romanman** [ethereum/go-ethereum#461]
Hey Guys , 

We have question regarding ECIES.  
It looks like  the KDF doesn't use 
HMAC-SHA256 at all, it just uses 
the plain SHA256 hash. 

We also see that:  HMAC is used but 
for the messageTag and not for the KDF
as expected by standard.

https://github.com/ethereum/go-ethereum/blob/develop/crypto/ecies/ecies.go#L232

is it by design or a missed bug ? 

 @obscuren  @fjl @subtly @devrandom

Thanks in advance
Roman

**Comment by devrandom** [comment]
@romanman - my apologies, looks like I misread the NIST standard.  It does specify the plain hash after all, so the current KDF implementation looks fine.

**Comment by romanman** [comment]
ok sounds like our own mess , closing this
