### ISSUE TITLE
RPC 

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#466]
In this thread i will add a comment per bug, as this are mostly minor issues.

**Comment by frozeman** [comment]
1. `eth_accounts` returns an empty array and `eth_coinbase` "0x"

**Comment by frozeman** [comment]
2. `eth_getBalance` should return an error when no/wrong parameter(s) are passed like: (message can differ, but the code should stay the same)

```js
{"error":{"code":-32602,"message":"INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised"},"id":2,"jsonrpc":"2.0"}
```

**Comment by frozeman** [comment]
3. 
- `eth_newBlockFilter`
- `eth_newFilter`
- `shh_newFilter`
- `eth_uninstallFilter`
- `shh_uninstallFilter`

should return error code -32602, but it returns -32603

**Comment by frozeman** [comment]
4
- `shh_newFilter`

returns number not HEX

**Comment by frozeman** [comment]
5
Timeout created filter and auto uninstall them after 10min of no eth/shh_getFilterChanges requests.
(prevent filter memeory leack)

**Comment by frozeman** [comment]
6
CPP allows reusing of filter IDs, means when i uninstall a filter the id is free again and will be reused for the next installed filter. Im not sure if thats better or worse, please lets discuss this.

**Comment by tgerring** [comment]
With the exception of item 1, I think most of these issues have been addressed.

@frozeman This situation occurs when the accounts have not been initialised. Can we write the tests to WARN when accounts array is empty and coinbase is nil/zero? We should be able to handle these situations without being explicit errors

**Comment by obscuren** [comment]
Re-open if there any pending issues left with the RPC
