### ISSUE TITLE
add support for transaction tests

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/go-ethereum#468]
as found in https://github.com/ethereum/tests/tree/develop/TransactionTests
and described here: https://github.com/ethereum/tests/wiki/Transaction-Tests

**Comment by Gustav-Simonsson** [comment]
Branch: https://github.com/Gustav-Simonsson/go-ethereum/tree/add_transaction_tests

Several tests do not pass in Go, these questions needs to be resolved:

* Why is gasLimit hex in some tests and number in others? e.g. https://github.com/ethereum/tests/blob/develop/TransactionTests/ttTransactionTest.json#L10 and https://github.com/ethereum/tests/blob/develop/TransactionTests/ttTransactionTest.json#L305
* Should this test pass? https://github.com/ethereum/tests/blob/develop/TransactionTests/ttTransactionTest.json#L201
* Is this test meant to pass? https://github.com/ethereum/tests/blob/develop/TransactionTests/ttTransactionTest.json#L222
* The hexadecimal notation for the s value has 35 characters, so it’s not recognised as valid hex by the Go hex decoder. On the wiki it says that invalid txs will not have the sender and transaction object, though this test has those.
* Same with this one, it seems to be an invalid tx but it has sender and transaction objects: https://github.com/ethereum/tests/blob/develop/TransactionTests/ttTransactionTest.json#L41

**Comment by zelig** [comment]
#689 #730 
@Gustav-Simonsson anything left from this?

**Comment by obscuren** [comment]
They all need to pass before closing this issue

**Comment by Gustav-Simonsson** [comment]
All tx test passes.
