### ISSUE TITLE
can't go install mist (ui_lib)

### ISSUE THREAD

**Issue by kobigurk** [ethereum/go-ethereum#469]
I get :
./ui_lib.go:152: self.XEth.Execute undefined (type *xeth.XEth has no field or method Execute)
./ui_lib.go:158: not enough arguments to return

commit d11fab

**Comment by tgerring** [comment]
XEth.Execute was removed in 2273155e7e325a2a6a940fffae7e9f6744b2ec22

@obscuren Assuming ./ui_lib.go:152 be changed to .Call() ?

**Comment by obscuren** [comment]
doh. Careless removal

**Comment by kobigurk** [comment]
seems solved!
