### ISSUE TITLE
Fatal: Unlock account failed 'read ~/Library/Ethereum/keys: is a directory'

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#472]
with `develop` commit 11390a9:
```
$ rm -rf ~/Library/Ethereum/
$ ethereum account new
The new account will be encrypted with a passphrase.
Please enter a passphrase now.
Passphrase: <bla>
Repeat Passphrase: <bla>
Address: 0x214eb547fcbb367724bb98b6c9e1a46986a4a522
$ ethereum -mine=true -rpc=true -rpcport=8080 -unlock=0x214eb547fcbb367724bb98b6c9e1a46986a4a522:bla
Welcome to the FRONTIER
2015/03/12 20:47:19 [CHAIN] Last block (#0) b5d6d8402156c5c1dfadaa4b87c676b5bcadb17ef9bc8e939606daaa0d35f55d TD=0
2015/03/12 20:47:19 Making Cache
2015/03/12 20:47:19 Took: 78.501352ms
2015/03/12 20:47:19 [CLI] Starting  Ethereum(G)/v0.9.0/darwin/go1.4.2
2015/03/12 20:47:19 [P2P Server] Starting Server
2015/03/12 20:47:21 ssdp: got unexpected search target result "hnap:GatewayWithWiFi"
2015/03/12 20:47:21 ssdp: got unexpected search target result "hnap:GatewayWithWiFi"
2015/03/12 20:47:21 ssdp: got unexpected search target result "hnap:GatewayWithWiFi"
2015/03/12 20:47:21 [P2P NAT] mapping error: no devices discovered
2015/03/12 20:47:21 [P2P Discovery] Listening,  enode://cc62b85f3390e1e8493099b192e8e498d00ddbb078d6f29ccc92c1dab4f46bda5a66892048f09946c86dd7bd5b62ad32a663ae4eee2127f13de4693f998b6b37@10.0.0.1:30303
2015/03/12 20:47:21 [Blockpool] Started
2015/03/12 20:47:21 [SHH] Whisper started
2015/03/12 20:47:21 [P2P Server] Listening on [::]:30303
2015/03/12 20:47:21 [SERV] Server started
Fatal: Unlock account failed 'read /Users/username/Library/Ethereum/keys: is a directory'
*** [ 20:47:34 | main ] Closing state DB
*** [ 20:47:34 | main ] Closing blockchain DB
```

**Comment by maran** [comment]
The address should be supplied to unlock without the leading 0x in this case.

@obscuren Can I add a little check to see wether 0x is given or not so both formats work?

**Comment by tgerring** [comment]
+1 to additionally supporting "0x" format. There are some scattered "fromHex" convenience methods around that could be duplicated

**Comment by obscuren** [comment]
But of course

**Comment by drcode** [comment]
Hi, so after I do this correctly (AFAIK) I'm still getting an error in ethereum.js when I connect through the rpc of "could not unlock sender account"... any suggestions on what I'm doing wrong or what I'm missing? Do I need to supply the password somehow from the ethereum.js side?

**Comment by obscuren** [comment]
@drcode start ethereum with unlocked account like so: `ethereum --unlock address:password --rpc`. Mist is going to come with it's own handler and will be implemented asap.

**Comment by drcode** [comment]
Hi @obscuren, I've already been following those steps and still get "could not unlock sender account" from the javascript side.

However, it seems to be working fine for others and I'm changing focus right now to UI work anyways, so I'll just check back in a couple of weeks and try again- Thanks for all your great work on this awesome program!

**Comment by obscuren** [comment]
That's odd. Are you sure you're on the latest `develop`? There was a time where we didn't have the `--unlock` flag.

**Comment by scottzer0** [comment]
i'm getting the same problem as drcode.  using the devel (0.9.1) version via homebrew

**Comment by drcode** [comment]
@scottzer0, make sure your javascript sendTransaction functions all have a "from" field. I think you're running an older build of ethereumjs that is missing the more helpful error message taylor recently added about the "from" field.
