### ISSUE TITLE
Differences from SEC 1 in ethereum ECIES

### ISSUE THREAD

**Issue by devrandom** [ethereum/go-ethereum#473]
I wanted to list the differences from SEC 1 that I found while working on ECIES for ethereumj.  SEC 1 says:
- IV should be all zeros and should not be transmitted (see section 3.8 discussion about IV/ICB)
- IV should not be part of MAC (message tag) computation
- also noticed an extra hash of the MAC key in the go-ethereum implementation

I believe that the reason SEC 1 recommends constant IV is that the ephemeral key is used only once, so use of a random IV is superfluous.

The changes don't seem to introduce any weakness, just curious about the motivation.

( @romanman )

**Comment by romanman** [comment]
@obscuren : I know you are busy, but in a moment  you not can 
you comment on this please or refer to somebody in your team.

**Comment by fjl** [comment]
I will have a look at it later,

**Comment by Gustav-Simonsson** [comment]
@romanman Hi! Apologies for the late reply - we've been so busy with other parts of Ethereum lately :)

Section 3.8 in SEC 1 Version 2.0 specifies zeroed IV for TDES in CBC mode and for AES in CBC and CTR modes, but it does not specify what IV value to use for plain XOR CTR.

The Go implementation uses XOR CTR: https://github.com/ethereum/go-ethereum/blob/develop/crypto/ecies/ecies.go#L193

You're right that IV should not be transmitted as part of the ciphertext, as specified in SEC 1.

While the IV value is not specified for XOR CTR, it's implied it cannot be random if it should not be transmitted as part of the ciphertext, as then the other party cannot know it.

If it's non-random, we can set it to the zeroed value defined for AES in CTR mode.

It's correct that IV should not be part of the message to take MAC over, defined as concatenation of ciphertext and "SharedInfo2" in section 5.1.3 step 8.

The extra hashing of the MAC key is indeed not specified in SEC 1 and so can be removed.

Pull request: https://github.com/ethereum/go-ethereum/pull/847

@fjl @subtly Please review - if this is correct C++ would also need to be updated to be compatible.

**Comment by subtly** [comment]
@romanman @Gustav-Simonsson This stems from adopting the go ecies package. This would go well with the adoption of libsecp256k1 multiply within ecies. Would be good to ping the upstream author about that as well.

**Comment by enuoCM** [comment]
What's the status of this issue now? So we cannot make ecies work between ethereumj and go-etherum now?

**Comment by jian1098** [comment]
I got an error “panic: got null header for uncle 0 of block 1458046c19b4c0e388db6cb7d09c3da6a8a88e75ccf9f027196c2732d43c9b6b” when i run 'range block.Transactions()'，what should  i do when it happen????

**Comment by lelikalf** [comment]
type

**Comment by fjl** [comment]
It's way too late to align ECIES used in Ethereum p2p with any standard. New APIs for encryption have been proposed for the RPC interface but we haven't implemented them yet.
