### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#475]
with `develop` 80592f2

creating trivial contract https://github.com/jorisbontje/sleth/blob/master/contracts/simple.se with hex code `336000556001600155604f8060146000396063567c01000000000000000000000000000000000000000000000000000000006000350463119fbbd48114156036576001600154016001555b63ea66cf6d811415604d5760015460405260206040f35b505b6000f3`

via rpc:
```
{'params': [{'gas': '0xc350', 'from': '0x48574ed8323453c2c5deaebc69eb068c1cc516fa', 'data': '0x336000556001600155604f8060146000396063567c01000000000000000000000000000000000000000000000000000000006000350463119fbbd48114156036576001600154016001555b63ea66cf6d811415604d5760015460405260206040f35b505b6000f3', 'value': '0x0', 'gasPrice': '0x9184e72a000'}], 'jsonrpc': '2.0', 'id': '32f0bbc8-3068-4d29-b2b6-017bab3eca89', 'method': 'eth_sendTransaction'}
```
result:
```
{u'jsonrpc': u'2.0', u'id': u'32f0bbc8-3068-4d29-b2b6-017bab3eca89', u'result': u'0x0357af2a54e4ce1b2f7d151218a28bb6d22a4c2a'}
```

ethereum started with:
```
$ ethereum -mine=true -rpc=true -rpcport=8080 --unlock=48574ed8323453c2c5deaebc69eb068c1cc516fa:bla
```

now in the `ethereum` logs:
```
2015/03/13 12:16:21 [XETH] Contract addr 0357af2a54e4ce1b2f7d151218a28bb6d22a4c2a
2015/03/13 12:16:22 [MINER] Hash rate: 91 Khash
2015/03/13 12:16:24 [MINER] Hash rate: 92 Khash
2015/03/13 12:16:25 [CHAIN] processed block #1070 (7207c80e...)
2015/03/13 12:16:25 [MINER] committing new work with 1 txs
2015/03/13 12:16:25 [MINER] (re)started agent[0]. mining...
2015/03/13 12:16:26 [MINER] Hash rate: 84 Khash
2015/03/13 12:16:28 [MINER] Hash rate: 90 Khash
2015/03/13 12:16:30 [MINER] Hash rate: 91 Khash
2015/03/13 12:16:32 [MINER] Hash rate: 91 Khash
2015/03/13 12:16:33 [BLOCK] TX err: out of gas! require 20000, have 4033
2015/03/13 12:16:33 [CHAIN] processed block #1071 (76a59ed5...)
2015/03/13 12:16:33 [MINER] committing new work with 0 txs
2015/03/13 12:16:33 [MINER] (re)started agent[0]. mining...
```

Why would it run out of gas, since I am providing `0xc350` = 50000 gas upon creation?

Edit: turns out that this 'required' amount of 20000 doesn't apply to the complete TX, but a specific action part of it. The error message can be clarified to reflect this.

**Comment by obscuren** [comment]
Contracts are expensive. `GasCreate` for example is already `32000` gas, a `GasStoreAdd` is `20000`.

**Comment by obscuren** [comment]
For a full list of gas (changes) see https://github.com/ethereum/go-ethereum/blob/develop/vm/common.go#L36

**Comment by jorisbontje** [comment]
Another error message that is unclear:
```
[MINER] GasLimit error. Max 500000, transaction would take it to 301246
```

**Comment by jorisbontje** [comment]
Also getting these errors a lot, which look problematic but might be harmless?
```
[CHAIN] Block timestamp equal or less than previous block (1426247835 - 1426247835)
```

And:
```
[MINER] Nonce err. Is 9, expected 7
```

**Comment by obscuren** [comment]
The time stamp issue is because the difficulty is very low for the current test net. It means you mined 2 blocks within a second (the protocol doesn't allow this). 

Regarding the nonce error, i'll have a look in to that.

**Comment by obscuren** [comment]
- [ ] Nonce errors
- [ ] Tx removal errors
- [ ] Block validation errors
    - [ ] Prev time
    - [ ] Nonce errors
    - [ ] Uncle errors
