### ISSUE TITLE
fatal error: QtCore/5.2.1/QtCore/private/qmetaobject_p.h

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/go-ethereum#480]
Fresh Ubuntu VMWare 14. Is this error because of the switch to godep for dependencies?

$ go get github.com/ethereum/go-ethereum/cmd/mist
#github.com/obscuren/qml
In file included from go/src/github.com/obscuren/qml/cpp/govalue.h:7:0,
                 from go/src/github.com/obscuren/qml/cpp/capi.cpp:10,
                 from go/src/github.com/obscuren/qml/all.cpp:2:
./cpp/private/qmetaobject_p.h:2:51: fatal error: QtCore/5.2.1/QtCore/private/qmetaobject_p.h: No such file or directory
 #include QT_PRIVATE_HEADER(QtCore,qmetaobject_p.h)
                                                   ^
compilation terminated.

**Comment by obscuren** [comment]
`mist` depends on `Qt5.4`. See https://github.com/ethereum/go-ethereum/wiki/Building-Instructions-for-Ubuntu

**Comment by maran** [comment]
It seems you are using QT 5.2 please upgrade to 5.4 and let me know if that works.
