### ISSUE TITLE
NatSpec integration

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#486]
- [x] integrate natspec: call natspec.New().Notice from xeth frontend.ConirmTransaction callbacks: js console  
- [x] natspec: implement transaction->codeaddress->codehash lookup
- [x] url resolver (implement codehash->natspecreg->contenthash lookup)
- [x] url resolver (implement contenthash->url-hint->url lookup)
- [x] transport layer: implement actual url fetcher (no local content caching for now) 
- [x] passing transaction, abi doc, method and notice to natspec.js
- [x] rework Natspec initialise to only take transaction and decode/fetch and cache everything internally--
- [x] NOT include NatSpecReg and URLHint contracts to genesis block, but make it deployable
- [x] end-to-end test 
- [x] Contract metadata doc wiki https://github.com/ethereum/wiki/wiki/Contract-Metadata-Docs-%28NatSpec,-ABI%29
- [x] command line flag to control natspec
- [x] add utils to natspec.js and update
- [ ] implement urlhint contract to take urls longer than 32 byte in a single transaction [backlogged]
- [ ] update NatSpec spec wikis: #758 
 https://github.com/ethereum/wiki/wiki/Registrar-ABI, 
 ** https://github.com/ethereum/wiki/wiki/NatSpec-Determination
 ** https://github.com/ethereum/wiki/wiki/NatSpec-Example
 ** https://github.com/ethereum/wiki/wiki/URL-Hint-Protocol
 ** https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format
 ** links

**Comment by fjl** [comment]
Don't know exactly what you are planning, but I think natspec should not call the Frontend interface. The frontend (mist/js repl) should call natspec to render the text that it displays to the user.

**Comment by zelig** [comment]
Sure not. 
NatSpec should be called from xeth backend Transact. 
Frontend Interface's ConfirmTransaction should take string argument not transaction.
This is what Jeff and I settled on.

**Comment by fjl** [comment]
But what if the frontend wants to show more info? Why even bother rendering the natspec for the noninteractive frontend?�

**Comment by zelig** [comment]
NatSpec is meant standardise the way transaction confirmation is specified.
What is the usecase you have in mind? 
Not sure what you mean by noninteractive frontend, if the environment is non-interactive, xeth will be constructed with nil Frontend. In which case NatSpec will indeed not bother rendering

**Comment by obscuren** [comment]
The process is as follows

1. Grab NatSpec description & ABI
2. `natspec.New(tx, abi, desc)`
3. Grab the result from natspec
4. Pass the result to `Frontend`

**Comment by fjl** [comment]
‎When we introduced the ConfirmTransaction function in the Frontend interface, the reasoning was that the input data for natspec is a transaction. Frontends may choose to render natspec (and have the necessary data) but don't need to. 

What if there is no natspec template for a transaction? What is the confirmation string in this case?

Mist could also show a "more info" button on the confirmation that displays the raw transaction (e.g. in a table view).  That wouldn't be possible if all it gets is a string to display.

**Comment by obscuren** [comment]
> ‎When we introduced the ConfirmTransaction function in the Frontend interface, the reasoning was that the input data for natspec is a transaction.

Even better. We pass the transaction and let the implementation (i.e. Mist, CLI, RPC) decide what to do.

> What if there is no natspec template for a transaction? What is the confirmation string in this case?

Some default.

> Mist could also show a "more info" button on the confirmation that displays the raw transaction (e.g. in a table view).  That wouldn't be possible if all it gets is a string to display. 

I like that idea.

At the moment mist has low prio. We'll first do an implementation for the CLI / RPC. We'll also need a `--skip-confirmations` flag.

**Comment by zelig** [comment]
right, tx arg should stay then, cool, natspec string additional arg ?

**Comment by obscuren** [comment]
I don't see why if the implementor decides (e.g. it sets up natspec)

**Comment by zelig** [comment]
#668
