### ISSUE TITLE
deb builds for Ubuntu won't work by themselves

### ISSUE THREAD

**Issue by caktux** [ethereum/go-ethereum#487]
Since the `ethereum-qt` PPA is required, those links are misleading and will only lead to confusion for users. PPA instructions should be used instead.

**Comment by obscuren** [comment]
This is for the links on the https://github.com/ethereum/go-ethereum/blob/develop/README.md ?

**Comment by caktux** [comment]
Yep, not sure what you'd prefer there, the instructions or linking to them

**Comment by obscuren** [comment]
A link I guess :-)

**Comment by zelig** [comment]
@fjl would you pls consider this?

**Comment by fjl** [comment]
Build instructions have been updated a while ago and now refer to the PPA.
