### ISSUE TITLE
RPC: filter latest not triggered

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#492]
Running the following filter in ethereum.js doesn't trigger any callback on `go-ethereum`. However it works fine with `cpp-ethereum`:

```
web3.eth.filter('latest').watch(function(res) {console.log(res)});
```

I would expect running filter with `latest` to watch for changes on the latest block as specified on https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter

go-ethereum develop commit 0b8f66e
ethereum.js develop commit de5de9eec878e3eb6b0f8b8684463ce7fb50f990

Starting ethereum with:
```
ethereum -mine=true -rpc=true -rpcport=8080 --unlock=0x0b30af04d96bfb672de96d3b25e30b4eb9ff3ed0:bla
```

**Comment by tgerring** [comment]
Added support for "latest" and "pending" in commit 5757f547a6339c770a6d85ad067107d34878858f. This hasn't yet been merged into develop

**Comment by jorisbontje** [comment]
`latest` works now.
