### ISSUE TITLE
Implement eth_getWork, eth_submitWork RPC methods

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#493]
These methods are needed for the GPU miner (and mining farms in general).
The external mining process will poll the RPC interface using `eth_getWork` and
hash away. If a sufficiently low nonce is found, they will submit it using `eth_submitWork`.

**Comment by tgerring** [comment]
These methods are implemented and merged into develop with the agent that Jeff wrote.
See https://github.com/ethereum/go-ethereum/blob/develop/rpc/api.go#L312-L320

**Comment by obscuren** [comment]
Fixed
