### ISSUE TITLE
p2p: add a full-stack unit test

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#494]
There should be a unit test that runs multiple instances of `p2p.Server` against each other with
one or more protocols. It is important to have such a test because most of the unit tests
in package `p2p` check things in isolation. In the past, several bugs have been found that were
not triggered by the unit tests because the 'production' setup isn't covered a lot.

**Comment by obscuren** [comment]
Can this be closed?

**Comment by fjl** [comment]
We still need such a test (haven't had the time to write one yet). Would also be nice to convert the [p2p developer tutorial](https://github.com/ethereum/go-ethereum/wiki/Peer-to-Peer) to a Godoc example.
