### ISSUE TITLE
p2p/discover: switch to sha3 in distance calculation

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#495]
This is a necessary change that we have been discussing for a long time.
Node IDs (which are serialized EC public keys) are not uniformly distributed
and are therefore not a good basis for measuring distances.

The new measure will be:

    dist(x, y) = sha(x) ^ sha(y)

**Comment by keks** [comment]
I created PR #540, but it's not done yet.

**Comment by zelig** [comment]
@fjl status on this?

**Comment by fjl** [comment]
This has been implemented in #791.
