### ISSUE TITLE
SEC-28 Add validations to Go EC recover utility function

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#505]
https://github.com/ethereum/go-ethereum/blob/develop/vm/address.go#L64

Remove the defer and handle all possible errors within the function.
Verify expected length of signature before slicing.
Verify value of the v parameter before appending it.

**Comment by ebuchman** [comment]
How do I run the vm tests?

**Comment by obscuren** [comment]
GH auto-close functionality closed this.

**Comment by obscuren** [comment]
YP input should be checked for 128 byte correctness

**Comment by Gustav-Simonsson** [comment]
Looks like we only applied V value check for txs in the tx pool.

This fix adds full validations of v, r and s values before we call libsecp256k1 for both txs in blocks and in tx pool: https://github.com/ethereum/go-ethereum/pull/1166
