### ISSUE TITLE
SEC-29 Go zero values for missing struct fields in RLP decoding causes caller to panic

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#506]
https://github.com/ethereum/go-ethereum/blob/develop/rlp/decode.go#L343

If a field of a struct does not have a value in the decoded data, the decoder will set the field to the Go zero value for that field's type.

If it's a pointer, it's set to nil, which will cause a nil pointer deference later on.

This can be triggered remotely by sending an empty array as payload in a NewBlockMsg.

EDIT: As explained by @fjl the fix should be in the code calling the RLP decoder and not in the RLP decoder itself.

**Comment by fjl** [comment]
The RLP decoder is working as intended in this case. If an input list contains less than the reqired number of elements, the remaining struct fields are set to their zero value.

The eth protocol layer should reject messages if the content is not valid.

**Comment by zelig** [comment]
correct. I'll fix this

**Comment by obscuren** [comment]
@zelig @fjl status?

**Comment by fjl** [comment]
@zelig will take care of adding more validation to the eth protocol. We have also discussed changing the decoder so it can never produce nil pointers unless they are actually wanted. This would be a bigger change.

**Comment by obscuren** [comment]
https://github.com/ethereum/go-ethereum/pull/588
