### ISSUE TITLE
SEC-30 Unsigned tx handled as tx from the zero address

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#507]
If a signature is invalid nil is returned at https://github.com/ethereum/go-ethereum/blob/develop/core/types/transaction.go#L120

This propagates up to address conversion, generating the zero (but valid) 0x0000000000000000000000000000000000000000 address. If this address was previously sent some wei it can be spent by an unsigned tx, causing a consensus failure.

Fix: reject all txs with invalid signatures.

**Comment by obscuren** [comment]
Invalid txs are now rejected => https://github.com/ethereum/go-ethereum/blob/develop/core/types/transaction.go#L79

**Comment by Gustav-Simonsson** [comment]
While error is returned by From() not all callers are checking it.

**Comment by Gustav-Simonsson** [comment]
Fix: https://github.com/ethereum/go-ethereum/pull/1167
