### ISSUE TITLE
ubuntu address after new account

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#508]
```
ethereum account new
The new account will be encrypted with a passphrase.
Please enter a passphrase now.
Passphrase: 
Repeat Passphrase: 
Address: 0x320xad0x270x650x3e0x4d0xf50xd80x170x280xd10x6d0x8e0x250x1f0xee0x340xf50x3d0x30
```
I believe I'm on 22893b7  (apt-get update and apt-get install ethereum).  The address has extra 0x throughout.

**Comment by maran** [comment]
Are you on a i686 version of Ubuntu by any chance?

**Comment by jorisbontje** [comment]
on a 32 bit Ubuntu 14.04 VM:
```
adminuser@adminuser-VirtualBox:~/go/src/github.com/ethereum/go-ethereum/common$ go test
# github.com/ethereum/go-ethereum/common
./bytes_test.go:81: constant 920987656789 overflows int
FAIL	github.com/ethereum/go-ethereum/common [build failed]
```

**Comment by obscuren** [comment]
Right. On 32 bit systems `len(int)` is 4 bytes. A simple fix would be `data2 := int64(920987656789)`

**Comment by maran** [comment]
This will fix the test but it won't fix the underlying error reported by the OP I think.

**Comment by jorisbontje** [comment]
Just managed to reproduced this on a fresh installation on Ubuntu 14.10 VM with there latest ethereum-dev PPA

**Comment by obscuren** [comment]
This has long been fixed. If the issue pops up again, re-open.
