### ISSUE TITLE
--maxpeers 0 should be considered valid input.

### ISSUE THREAD

**Issue by AFDudley** [ethereum/go-ethereum#510]
Ideally, this could be used to indicate a local testnet, instead this is the error:
$ docker run -it ethereum/client-go --maxpeers 0
Welcome to the FRONTIER
2015/03/17 08:46:04 [CHAIN] Last block (#0) fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca TD=0
2015/03/17 08:46:04 [POW] Making Cache
2015/03/17 08:46:06 [POW] Took: 1.639890298s
2015/03/17 08:46:06 [CLI] Starting  Ethereum(G)/v0.9.0/linux/go1.4.2
2015/03/17 08:46:06 [P2P Server] Starting Server
Fatal: Server.MaxPeers must be > 0

**Comment by zelig** [comment]
will fix as part of https://github.com/ethereum/go-ethereum/pull/485

**Comment by AFDudley** [comment]
Thanks.
