### ISSUE TITLE
RPC eth_call consumes gas / has side effects

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#513]
When running `eth_call` it seems to consume gas, if you do this often enough it results in the rpc error `out of gas! require 20, have 12`. Expected is that the gas for a `call` isn't actually consumed and I should be able to run it thousands of times without side effects.

minimal viable test (create contract and then run multiply 1000 times):
https://gist.github.com/jorisbontje/27164bc6b5537ac7c7f7

running ethereum `develop` commit 22893b7ac925c49168c119f293ea8befc3aff5cc with:
```
./ethereum -rpc -rpcport=8080 -unlock=0x0b30af04d96bfb672de96d3b25e30b4eb9ff3ed0:bla -mine
```

**Comment by SilentCicero** [comment]
Getting the same error, ```out of gas! require 3, have 0``` I burned through thousands of test eth just making a few calls.

**Comment by obscuren** [comment]
Fixed by https://github.com/ethereum/go-ethereum/pull/616
