### ISSUE TITLE
SEC-32 VM memory Set function panic when memory is empty (0)

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#515]
https://github.com/ethereum/go-ethereum/blob/develop/vm/memory.go#L16

If len(m.store) is 0 then the unit64 will overflow and lenSize will be 2^64 -1.

Fix: Change comparison to uint64(len(m.store))

**Comment by obscuren** [comment]
Memory will never be or above `2^64`

**Comment by obscuren** [comment]
Memory is always scaled prior to setting the memory.
