### ISSUE TITLE
LLL storage mapping

### ISSUE THREAD

**Issue by ckeenan** [ethereum/go-ethereum#516]
I compiled a simple LLL contract
```
{
    [[0x0]] 1
}
```
To the bytecode: 6001600155. Using the latest go develop branch client, this produces a contract with storage:

{ '0xb10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf6': '0x01' }

When I was expecting {'0x0' : '0x01'}

**Comment by obscuren** [comment]
Because of how the trie works that key you're seeing is actually the `sha3(key)`. `getStorage` will be deprecated.

The "right" way would be to store an additional k/v which maps that `sha3(key) / key`. Low priority unfortunately.

**Comment by ckeenan** [comment]
OK thank you, that's very helpful
