### ISSUE TITLE
tx failed, transaction will be removed

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#519]
I captured loglevel5:
`2015/03/17 19:50:59 [MINER] TX (4146cbcd) failed. Transaction will be removed`

http://pastebin.com/Vg5CzcSG
The failed is at the bottom.

When the tx is run again, it succeeds.

**Comment by ethers** [comment]
This was found on develop commit 3ea99f9

**Comment by ethers** [comment]
With PR #543 here's the error:
`[MINER] TX (c05b349e) failed, will be removed: Transaction w/ invalid nonce (7 / 8)`
Looks related to #317  ?

**Comment by ethers** [comment]
In case helpful, here is a very short, standard log showing 2 instances of invalid nonce: http://pastebin.com/yMPZrFyj

**Comment by ethers** [comment]
A tx that transferred ether from one account to another account,  was removed due to invalid nonce:
`2015/03/20 20:51:42 [MINER] TX (b54b72e9) failed, will be removed: Transaction w/ invalid nonce (16 / 17)`
However, the balances of the accounts were NOT reverted.  If tx failed, I would expect that any state changes it causes, would also be reverted.

**Comment by ethers** [comment]
~~519 could be more serious; I added: A tx that transferred ether from one account to another account, was removed due to invalid nonce:
2015/03/20 20:51:42 [MINER] TX (b54b72e9) failed, will be removed: Transaction w/ invalid nonce (16 / 17)
However, the balances of the accounts were NOT reverted. If tx failed, I would expect that any state changes it causes, would also be reverted.~~

I had sent similar tx via frontend+ethereum.js and didn't see the balance updates, usually after
`[MINER] committing new work with 1 txs` the balance would update via jsonrpc.  Now, have to wait until the next `[MINER] committing new work with 0 txs` to see the balance update.  It was these balance updates that I misattributed as being caused by the tx invalid nonce above.

**Comment by obscuren** [comment]
Do you have sample sendTransaction data I can use to replicate this? Or does this happen with the most basic Txs?

**Comment by obscuren** [comment]
I've tried to fire some transactions myself but it I can't seem to reproduce the error you're having. Could you please provide me with same samples? Could you also retry using the conversion branch?

**Comment by ethers** [comment]
I will try on conversion branch.
For now, to repro consistently I use pyepm https://github.com/etherex/pyepm and this yaml
https://github.com/ethers/dapp-bin/blob/btcrelay/btcrelay/zGo-testBulkDeploy.yaml

With Go cli running, it is "pyepm -a <your Go unlocked account> zGo-testBulkDeploy.yaml"

**Comment by ethers** [comment]
On conversion branch, looks like it still happens `[MINER] TX (39b66ba4) failed, will be removed: Transaction w/ invalid nonce (14 / 0)`

Here's more log which has quite a bit of data and hopefully helps:
http://pastebin.com/vAXbA7Tk

**Comment by obscuren** [comment]
I think I've found the issue and fixed in https://github.com/ethereum/go-ethereum/commit/c28116cb3b485f01aba852fdc9559a2495db6654

Could you try again?

**Comment by ethers** [comment]
looks fixed on e88a29a

**Comment by samoclay** [comment]
Hey guys, I got something similar on a transaction I made on a recent ICO
https://etherscan.io/tx/0x6ed7aca844244dca2d6d34f8bdb10aaf208971c1164ff08aa6d7c4b9abb00ddc
Im not sure what this means though?
