### ISSUE TITLE
fatal error: unexpected signal during runtime execution on Windows 64bit

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/go-ethereum#524]
Running the develop Eth CLI after godep build/install on Windows 64bit, I get this.

$ ethereum
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x8711bd]

runtime stack:
invalid spdelta 0x8711b4 0x8711bd 0x185b35 -1
runtime.gothrow(0xa6efc8, 0x2a)
        c:/go/src/runtime/panic.go:503 +0x67
runtime.sigpanic()
        c:/go/src/runtime/os_windows.go:36 +0x53
invalid spdelta 0x8711b4 0x8711bd 0x185b35 -1
secp256k1_start()
        ?:0 +0x9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x8713cc, 0x12da3f80, 0x0)
        c:/go/src/runtime/cgocall.go:130 +0xbc fp=0x12da3f70 sp=0x12da3f58
github.com/ethereum/go-ethereum/crypto/secp256k1._Cfunc_secp256k1_start()
        github.com/ethereum/go-ethereum/crypto/secp256k1/_obj/_cgo_gotypes.go:56
 +0x3f fp=0x12da3f80 sp=0x12da3f70
github.com/ethereum/go-ethereum/crypto/secp256k1.init┬╖1()
        C:/GoProjects/src/github.com/ethereum/go-ethereum/crypto/secp256k1/secp2
56.go:41 +0x1e fp=0x12da3f84 sp=0x12da3f80
github.com/ethereum/go-ethereum/crypto/secp256k1.init()
        C:/GoProjects/src/github.com/ethereum/go-ethereum/crypto/secp256k1/secp2
56.go:306 +0x4e fp=0x12da3f88 sp=0x12da3f84
github.com/ethereum/go-ethereum/core/types.init()
        C:/GoProjects/src/github.com/ethereum/go-ethereum/core/types/transaction
.go:234 +0x3f fp=0x12da3f8c sp=0x12da3f88
github.com/ethereum/go-ethereum/pow.init()
        C:/GoProjects/src/github.com/ethereum/go-ethereum/pow/pow.go:8 +0x3f fp=
0x12da3f90 sp=0x12da3f8c
github.com/ethereum/ethash.init()
        c:/GoProjects/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/
github.com/ethereum/ethash/ethash.go:437 +0x45 fp=0x12da3fb4 sp=0x12da3f90
main.init()
        C:/GoProjects/src/github.com/ethereum/go-ethereum/cmd/ethereum/main.go:3
73 +0x4a fp=0x12da3fcc sp=0x12da3fb4
runtime.main()
        c:/go/src/runtime/proc.go:58 +0xbd fp=0x12da3ff0 sp=0x12da3fcc
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1 fp=0x12da3ff4 sp=0x12da3ff0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1

goroutine 5 [select]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
        C:/GoProjects/src/github.com/ethereum/go-ethereum/logger/sys.go:41 +0x56
2
created by github.com/ethereum/go-ethereum/logger.init┬╖1
        C:/GoProjects/src/github.com/ethereum/go-ethereum/logger/sys.go:20 +0x25

**Comment by obscuren** [comment]
The win64 binaries should once again work. Please re-open if the issue persists
