### ISSUE TITLE
getting json-rpc message response of "could not unlock sender account"

### ISSUE THREAD

**Issue by scottzer0** [ethereum/go-ethereum#525]
after creating a new account from ethereum (cli) and running ethereum:
```
ethereum --rpc --rpcport=8080 --unlock=0x77e5254b5a9e24b7075493c505508541027cde7f:test
```
ethereum starts up and successfully does NOT complain about the account (it does if anything in that address:password is off), i still get the following response trying to do a simple eth_sendTransaction:
```javascript
{
	"id": 1,
	"jsonrpc": "2.0",
	"error": {
		"code": -32603,
		"message": "could not unlock sender account"
}
```
here's my curl POST:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"data": "0x...'"}],"id":1}' http://localhost:8080
```

not alone:
   https://forum.ethereum.org/discussion/1930/could-not-unlock-sender-account

**Comment by fjl** [comment]
Do you supply the "from" ‎parameter in your sendTransaction call?

**Comment by scottzer0** [comment]
i do not.  perhaps that's the issue.  i've been using cpp eth and only setting the data.  i also don't think ethereum.js supplies the 'from' though.

**Comment by fjl** [comment]
We will add a better error message for this case. Collecting RPC user feedback: Do you find it reasonable to require a from a‎ddress for all transactions?

**Comment by scottzer0** [comment]
seems to me, if multiple addresses exist, the user should be responsible to clear up the ambiguity, else just always use the first if unspecified.

**Comment by scottzer0** [comment]
followup: does go-ethereum support eth_filter?  this was working in cpp-eth, but doesn't seem to fire in go-ethereum:
```javascript
web3.eth.filter('latest').watch(function(data) {
   console.log(data);
});
```

**Comment by scottzer0** [comment]
it would also be nice to know in the clients STDOUT, why a sendTransaction failed (out of gas, block gas limit etc)...

**Comment by tgerring** [comment]
Added "From" field validation with message in commit 8b20c3cc976a149c64ef0ac2cabbe49e93ba739d

**Comment by obscuren** [comment]
A default should **never** be used. It adds additional complexity to the code. Extra complexity means higher risk. Higher risk = bad :-)

**Comment by obscuren** [comment]
Closing issue
