### ISSUE TITLE
JS console sendTransaction: TypeError: Cannot access member 'length' of undefined

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#534]
```
> web3.eth.sendTransaction({from:'0x0fc777ef94716795338c4a7ac205c7b20221599e', to:'0x47d33b27bb249a2dbab4c0612bf9cdf4c1950855', value: 1000})
TypeError: Cannot access member 'length' of undefined
```

this is on `develop` branch commit 4f5b362bda862b0d77583491d5e04193148a9349

**Comment by frozeman** [comment]
Thats an ethereum.js bug. i fixed it in https://github.com/frozeman/ethereum.js/commit/0f640da579119f95f9b3ba22f433e1bb58f58112

**Comment by obscuren** [comment]
Awesome, thanks :-)

**Comment by obscuren** [comment]
This has also been fixed in https://github.com/ethereum/go-ethereum/commit/fcacfabe1959c4aff6a63cb4e275f65328660601
