### ISSUE TITLE
"topics" key should be used instead of "topic"

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#544]
OBSERVED
With Go cli commit 4f5b362, filter.watch is returning an object with key "topic".  
```
Object {address: "0x12393873e2d12de2f9ec7bf51803356e49eb922f", topic: Array[1], data: "0x0000000000000000000000000000000000000000000000000000000000000001", number: 16268}
```

EXPECTED is to follow cpp and https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter and use the plural key name "topics".

**Comment by obscuren** [comment]
Has been fixed.
