### ISSUE TITLE
will Go CLI support bytesXX?

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/go-ethereum#549]
I figure everything compiles down to the same hex. But I cant figure out if the contracts I create in the Solidity Browser Compiler (which now use bytes32 instead of string32) will still work with Eth.js -> Go CLI POC9. Will there be some temporary compatibility issues here as POC9 develops? (Also, Eth.js is still using the stringXX term, which may add to this problem).

**Comment by tgerring** [comment]
The RPC spec dictates that a hexstring of the code or data can be passed in to [eth_sendTransaction](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction). This hexstring format ("0x2e345f678a") is used for many parameters, with ethereum.js handling the conversion for numbers. See [JavaScript API](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction) for more info.

**Comment by obscuren** [comment]
What's the exact issue here? If there's no real issue please close this issue :-) Feel free to bug us with question on => [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/ethereum/go-ethereum?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by SilentCicero** [comment]
@obscuren will do, the problem is most likely to do with Ethereum.js and not Go. Apologies, forgot to close.
