### ISSUE TITLE
The PPA is missing qtwebengine dependencies

### ISSUE THREAD

**Issue by secret-bitcoin-login** [ethereum/go-ethereum#554]
The Mist build from the PPA as recent as version 0.9.2 is missing qml-module-qtwebengine as a dependency. When added, mist does run for a brief time before crashing with a runtime error: "invalid memory address or nil pointer dereference".

for those who are still trying to figure out what to do, you can install the dependency with:
sudo apt-get install qml-module-qtwebengine

Installing the package resolves the following errors upon launching mist:

2015/03/23 17:54:55 [GUI] error:  file:////usr/share/mist/qml/views/catalog.qml:5 module "QtWebEngine" is not installed
file:////usr/share/mist/qml/views/catalog.qml:6 module "QtWebEngine.experimental" is not installed
file:////usr/share/mist/qml/views/catalog.qml:5 module "QtWebEngine" is not installed
file:////usr/share/mist/qml/views/catalog.qml:6 module "QtWebEngine.experimental" is not installed

2015/03/23 17:54:55 [GUI] error:  file:////usr/share/mist/qml/views/browser.qml:5 module "QtWebEngine" is not installed
file:////usr/share/mist/qml/views/browser.qml:6 module "QtWebEngine.experimental" is not installed
file:////usr/share/mist/qml/views/browser.qml:5 module "QtWebEngine" is not installed
file:////usr/share/mist/qml/views/browser.qml:6 module "QtWebEngine.experimental" is not installed

**Comment by obscuren** [comment]
Thanks @caktux will probably be interested in this

**Comment by caktux** [comment]
Fixed, next build will be installing it, thanks for reporting this!

**Comment by caktux** [comment]
Also fixed in release builds PPA for 0.8.6, which in turn removes the placeholder `ethereum-gui` package and makes the `mist` package available, so the release and dev PPAs now use consistent package names.

**Comment by obscuren** [comment]
Thanks!
