### ISSUE TITLE
Move DAG file handling to ethash

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#555]
I'm assuming there's a better location than /tmp/dag

Also will Go and C++ be able to share the same dag located at ~/.ethash ?

**Comment by obscuren** [comment]
Go and C++ will share the same DAG. The current DAG file is only temporarily and file handling will move to the ethash package it self.

**Comment by obscuren** [comment]
https://github.com/ethereum/go-ethereum/issues/757
