### ISSUE TITLE
Multiple instances of ethereum --mine do not sync to the same block number

### ISSUE THREAD

**Issue by secret-bitcoin-login** [ethereum/go-ethereum#556]
I shared this on reddit recently but didn't get much of a response, and it's still a concern that I have and don't really understand.

I am playing with three ethereum installations 0.9.2 (from the PPA) on fresh ubuntu 14.10. They have identical configurations and all are stand alone machines. When I launch the miner I have assigned each machine to it's own external port.

The issue is that after several minutes or hours of mining, the block ID's do not seem to line up - in some cases being hundreds of blocks between the highest and lowest block ID. I have occasionally watched a catch-up process, but this doesn't seem to be aggressive enough to solve the issue.

My primary concern is based on my experience with bitcoin which suggests that it is very important for all miners to be in close sync. This could be a misunderstanding regarding the way ethereum is intended to operate.

Please see the screenshots. They include two sets of screen sessions from each of the three instances (six total images).

One group was taken at 8:35 pm and you can see the following block ID's:
#39507
#30451
#30479

The second group of images was taken after I stopped and restarted each of the instances and let them run for 20 minutes:

#39550
#30516
#30562

(Imgur album is a redundant image library for what's shared below: https://imgur.com/a/k2qEN)

![screenshot from 2015-03-23 21 07 01](https://cloud.githubusercontent.com/assets/7463078/6794611/07fd3bc4-d1a2-11e4-8ee6-edf3d01fd854.png)
![screenshot from 2015-03-23 21 06 56](https://cloud.githubusercontent.com/assets/7463078/6794613/07ff85c8-d1a2-11e4-8990-96264a6fa306.png)
![screenshot from 2015-03-23 21 06 22](https://cloud.githubusercontent.com/assets/7463078/6794612/07ff8410-d1a2-11e4-886c-7a7508c38b86.png)
![screenshot from 2015-03-23 20 35 55](https://cloud.githubusercontent.com/assets/7463078/6794614/0806f718-d1a2-11e4-80b6-64846556277f.png)
![screenshot from 2015-03-23 20 35 52](https://cloud.githubusercontent.com/assets/7463078/6794616/081348e2-d1a2-11e4-9d50-b5e1cb48eed1.png)
![screenshot from 2015-03-23 20 35 47](https://cloud.githubusercontent.com/assets/7463078/6794615/0811bb62-d1a2-11e4-91e6-42c4c78af5b2.png)

**Comment by zelig** [comment]
but are you sure they are connnected to each other at all? could you give the command line you started them with?

**Comment by obscuren** [comment]
I've been playing with this last night and syncing should now work again (given that there's a "healthy" network).

**Comment by secret-bitcoin-login** [comment]
I didn't connect the nodes directly together. I started them with:

ethereum --mine --port 3030{3..6}

**Comment by zelig** [comment]
if you want to connect local instances, instructions are here https://github.com/ethereum/go-ethereum/wiki/Setting-up-private-network-or-local-cluster/

as for syncing, please try develop. Note that multiple mining instances share the same dag, so it will only work if they are guaranteed to be in the same epoch. at least until #555 is fixed.
