### ISSUE TITLE
admin.startRPC() doesn't seem to work

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#557]
trying to start the RPC from the console gives me:

```js
> admin.startRPC(8545)
Can't listen on 8545:0: listen tcp 0.0.33.97:0: bind: can't assign requested addressfalse
```

**Comment by tgerring** [comment]
Does it work if you start directly from the CLI? i.e. is this a console issue or more general?

**Comment by zelig** [comment]
yes the spec incorrectly says `admin.startRPC(portNumber)` but it should be 
`admin.startRPC(ipAddress, portNumber)`

**Comment by zelig** [comment]
fixed by updated wiki https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console
