### ISSUE TITLE
RPC "could not decode, FromBlock is not a string"

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#566]
Here's the request
{"jsonrpc":"2.0","method":"eth_newFilter","params":[{"fromBlock":null,"toBlock":null,"address":"0x78435654885ad4f4e57476fe146d69390d504ba1"}],"id":2}

CPP handles it but Go develop 505f1fb responds with
```
{
	"id": 2,
	"jsonrpc": "2.0",
	"error": {
		"code": -32602,
		"message": "could not decode, FromBlock is not a string"
	}
}
```

fwiw, docs say "fromBlock" with lower case "f" instead of "FromBlock" capitalized in error message.

In case needed, here is the simple call being made.  (ethereum.js develop b78dffa is used)
web3.eth.filter({'address': gExchangeContractAddr}).watch(function(res) {
  console.log('@@@ gExchangeContractAddr filter')
  console.log(res)
});
where var gExchangeContractAddr = '0x78435654885ad4f4e57476fe146d69390d504ba1'; // Go

**Comment by obscuren** [comment]
Error messages are derived from the fields defined in go (they are UpperCamelCased). We could remove fields that are set to `null` (not sure why you do this?).

**Comment by obscuren** [comment]
@tgerring Maybe drop `null` fields?

**Comment by ethers** [comment]
ethereum.js is the one that created the response and set fromBlock and toBlock to null

**Comment by tgerring** [comment]
@obscuren The options need to make it into a `core.Filter`. We can handle nulls as nil if we use a pointer to int64, otherwise we'll probably need some logic in `core/filter.go` that allows it to ignore certain fields.

**Comment by obscuren** [comment]
It's fixed in ethereum.js. string values, integers, etc, should not be set to `null`. They are now either implicit or explicit undefined.
