### ISSUE TITLE
Network connections not working

### ISSUE THREAD

**Issue by noflag** [ethereum/go-ethereum#569]
This has been an issue for a bunch of recent dev releases. 

My IP and port are open

I'm running with mist --nat extip:96.229.x.x --port "30303"

Sometimes it connects to one peer ( 5.1.83.226:30303 ) but the blockchain doesn't download

Here's my CLI output. Lots of "Invalid PoW" messages. 
https://gist.github.com/noflag/df74733ad2085420df4e

**Comment by obscuren** [comment]
You're seeing a lot of `Invalid PoW` because the peer (5.1.83.226:30303) still has an old version of the DAG & ethereum.
