### ISSUE TITLE
RPC needs tighter definition and consistency with C++ and Go

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#575]
Some discrepancies b/w cpp and Go RPC

- eth_getCode cpp returns 0x, Go returns 0x0

Following is for eth_getStorageAt
- cpp can return data when the index is specified as 0xf or 0x0f; Go only returns the data for 0x0f
- cpp can return data when the index is specified as 0x100 or 0x0100; Go only returns the data for 0x0100

**Comment by ethers** [comment]
another one for eth_getStorageAt, when nothing in storage, cpp returns 0x00, Go returns "" (empty)

**Comment by tgerring** [comment]
@frozeman Is working on a test suite that will test all clients for compatibility over at https://github.com/ethereum/rpc-tests

We are working on being able to load arbitrary blocks & state such that we can expect exact output form any specific call.

**Comment by ethers** [comment]
RPC wiki also has `  "result": "0x1" // 1` and it should be 0x10 // 16 for consistency with cpp and Go (since Go uses even number nibbles)

**Comment by tgerring** [comment]
@ethers can you re-check you're results? latest changes merged into develop pass rpc-tests and include formatting changes

**Comment by ethers** [comment]
thanks I think it is better.
The RPC wiki still needs review and fixes, example:
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_flush has no explanation

**Comment by obscuren** [comment]
Ok thanks. Closing! :-)
