### ISSUE TITLE
Can't build geth on Windows

### ISSUE THREAD

**Issue by maran** [ethereum/go-ethereum#591]
Windows builds for geth are currently not working (using f23529c5cde47f713ada745629a7bdc8e1506fa7)

```
PS C:\godev\src\github.com\ethereum\go-ethereum\cmd\geth> godep go install
c:\godev\pkg\windows_amd64/github.com/ethereum/go-ethereum/crypto/secp256k1.a(_all.o): duplicate symbol reference: _wass
ert in both github.com/ethereum/ethash(.text) and github.com/ethereum/go-ethereum/crypto/secp256k1(.text)
```

When bypassing godep and using latest master from ethash I get this instead:

```
c:\godev\src\github.com\ethereum\ethash\ethash.go:88: cannot use paramsAndCache.params.cache_size (type C.uint64_t) as t
ype C.size_t in argument to _Cfunc__CMalloc
c:\godev\src\github.com\ethereum\ethash\ethash.go:121: cannot use p.params.full_size (type C.uint64_t) as type C.size_t
in argument to _Cfunc__CMalloc
```
I have no clue why this is and it did work at one point. 

If anybody wants to setup a Windows VM to test there are some pointers:

1. Install Git and Mercurial
2. Install Golang from https://storage.googleapis.com/golang/go1.4.2.windows-amd64.msi
3. Install winbuilds from http://win-builds.org/1.5.0/win-builds-1.5.0.exe to c:\winbuilds
4. Run win builds here I just remove a few big dependencies like QT and GTK which I know aren't needed an exactly list would be preferable but you can't remove deps after so it's hard to track down.
5. Setup environment paths add `GOROOT` to c:\go and `GOPATH` to c:\godev (you are free to pick this one) setup `PATH` to %PATH%;%GOROOT%/bin;%GOPATH%/bin;c:\winbuilds\bin
6. Open a terminal and install godep first: `go get -u github.com/tools/godep`
7. Open a terminal and install ethereum `go get -d -u github.com/ethereum/go-ethereum/geth`
8. Try building ethereum with go dep, navigate to `c:\godev\src\github.com\ethereum\go-ethereum\geth `and issue `git checkout develop` and `godep go install`.
9. If you want to build from an other branch bypass godep go install for `go install` and checkout the dependencies manually.

**Comment by LefterisJP** [comment]
I am working on it.

**Comment by obscuren** [comment]
The `C.size_t` errors are fixed in https://github.com/ethereum/ethash/pull/20

**Comment by LefterisJP** [comment]
@maran I have tested building with msvc and it works and the tests pass. I have not yet been able to manage to build with mingw due to lack of time. Can you try to see if you can build nowthat the `size_t` errors are fixed?

**Comment by maran** [comment]
Thanks @LefterisJP ! I can indeed get past the malloc problems again but still stuck with:

```
# github.com/ethereum/go-ethereum/cmd/geth
c:\godev\pkg\windows_amd64/github.com/ethereum/go-ethereum/crypto/secp256k1.a(_all.o): duplicate symbol reference: _wass
ert in both github.com/ethereum/ethash(.text) and github.com/ethereum/go-ethereum/crypto/secp256k1(.text)
```

Not sure this is a problem with Ethash though.

**Comment by tgerring** [comment]
@maran Does that error resolve if you clear out the $GOPATH/pkg directory?

**Comment by maran** [comment]
@tgerring Nope, sadly not.

**Comment by fjl** [comment]
I have successfully built and run current develop (f047699afb) using a 32bit MinGW toolchain on Windows 8.1. It did require a few fixes in some of our Go packages (will submit a PR tomorrow) but the linking error did not show up. 

Will try 64bit MSVC tomorrow.

**Comment by maran** [comment]
That's awesome @fjl. I checked it last on monday and d9b37b6 was after that so the timeline could fit. Thanks for the effort I will verify it on the build VM.

**Comment by debris** [comment]
There is nice continues integration tool for windows - appveyor. It's quite similar to Travis.

[.yml](https://github.com/ethereum/go-ethereum/compare/develop...debris:develop), [appveyor](https://ci.appveyor.com/project/debris/go-ethereum)

**Comment by tgerring** [comment]
@maran Have you had luck getting the build to work on Windows now?

**Comment by maran** [comment]
Sorry @tgerring for the late reply I was on holiday.

I just tried building develop at fa729a0c55aa4b00c2ac33d0fcee8acabed2f737 and it is working successfully using a simple `godep go install` 

For mining I think ethereum/ethash#13 still needs to be merged but I am not sure if somebody else fixed this already, a quick scan did not seemed like it did.

**Comment by tgerring** [comment]
Even if we're waiting on some changes for ethash, if Windows build is working, it sounds ready for integration with buildbot and this issue can be closed?

**Comment by maran** [comment]
Yes :)

**Comment by rahul25890** [comment]
When i am trying to finalize set up for geth  with commmand "godep go install"
it says : 
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
godep: go exit status 2

How can i fix that problem

**Comment by maran** [comment]
Make sure you download the 64 bit version of Go.

**Comment by rahul25890** [comment]
i have downloaded from here 
"https://storage.googleapis.com/golang/go1.4.2.windows-amd64.msi"

and it is 64 bit

**Comment by maran** [comment]
Sorry, I might to say you should use a [64bit mingw version](http://mingw-w64.org/doku.php)
