### ISSUE TITLE
SEC-33 New gas limit validation not handling when block's gas limit is lower than parent

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#595]
If the block's gas limit is lower than the parent's, the check will pass even if the diff is greater than parent's block limit divided by 1024.

https://github.com/ethereum/go-ethereum/blob/develop/core/block_processor.go#L263

If **a** is negative here, which happens if block's gas limit < parent's gas limit, then the comparison will always pass, allowing that gas limit.

This is fixed by taking the absolute value of block's gas limit subtracted by parent's gas limit: https://github.com/ethereum/go-ethereum/pull/594

This also makes the comparison check that the diff is strictly smaller than the allowed value, according to (8) in https://ethereum.etherpad.mozilla.org/106?

**Comment by obscuren** [comment]
https://github.com/ethereum/go-ethereum/pull/594
