### ISSUE TITLE
SEC-34 Add check for minGasLimit in new gas limit validation

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#597]
minGasLimit should be read from https://github.com/ethereum/common/blob/master/params.json and ~~verified in the new gas limit validation at https://github.com/ethereum/go-ethereum/blob/develop/core/block_processor.go#L263~~

Otherwise there if gas limit becomes less than 1024 it can never be changed again due to the new validation rules.

**Comment by obscuren** [comment]
https://github.com/ethereum/go-ethereum/pull/594

**Comment by Gustav-Simonsson** [comment]
Added: https://github.com/ethereum/go-ethereum/blob/develop/core/block_processor.go#L271
