### ISSUE TITLE
SEC-40 common/rlp.go Encode integer overflow

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#603]
At https://github.com/ethereum/go-ethereum/blob/develop/common/rlp.go#L135 a uint64 is converted to int64. This will overflow for values above 0x7FFFFFFFFFFFFFFF (https://golang.org/ref/spec#Numeric_types)

This can for example happen if the PoW nonce is big enough: https://github.com/ethereum/go-ethereum/blob/develop/core/state/state_object.go#L331

After the int64 encoding, the value is then converted to a big.Int, and .Bytes() called on it, which will convert a negative number to a positive one as it returns the absolute value: https://golang.org/pkg/math/big/#Int.Bytes

Negative numbers is not a problem for RLP encoding though, as we never have negative numbers in the layer of the protocol that encodes integers using RLP.

**Comment by obscuren** [comment]
`common.Encode` is no longer used for encoding anything other than the trie. Closing this.
