### ISSUE TITLE
SEC-41 Peer TD in NewBlockMsg not verified

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#604]
When a NewBlockMsg message is handled, it's TD field is compared to the current best peer, and if the TD is higher this peer is set as best peer, if it's not the best already.

The TD is not verified, allowing a malicious peer to become the best peer by advertising a high TD.

The TD field can be removed from the NewBlockMsg type and instead be calculated from the received block, after PoW and other initial validations are done.

https://github.com/ethereum/go-ethereum/blob/develop/eth/protocol.go#L292
https://github.com/ethereum/go-ethereum/blob/develop/blockpool/peers.go#L270

**Comment by zelig** [comment]
Unfortunately, the TD of a head block can only be calculated once the block  is connected to the blockchain, ie after we downloaded the entire chain leading to this head. Our best bet to achieve this is to follow the chain back by requesting blockhashes from the best peer. 
Therefore we need to rely on the advertised TD. 
To mitigate against a malicious peer misadvertising a higher TD, we calculate the TD on insertion and match it to the td advertised by the peer. If there is a mismatch, the peer is suspended. 
So, we check the TD at the earliest possible occasion. https://github.com/ethereum/go-ethereum/blob/develop/blockpool/section.go#L150
If initial PoW checking proves insufficient against malicious peer invalid "infinite" chains, we could apply a voting scheme, ie. requiring X percent of peers to agree on the root block  of the best peer's head section. However this may prove too restrictive if connectivity is sparse.

**Comment by obscuren** [comment]
This actually being verified now. Closing.
