### ISSUE TITLE
SEC-42 Don't Panic

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#605]
Don't Panic... at https://github.com/ethereum/ethash/blob/master/ethash.go#L379  when a 0 difficulty value is received, by avoiding it entirely by sanitizing the input data to ethash.

All block data should be verified to be well-formed before sending to ethash. This includes difficulty, block number, nonce and block hash.

**Comment by obscuren** [comment]
I'm going to close this issue because it's not really relevant. The title should be "Update ETHASH", which there already is a PR for.
