### ISSUE TITLE
RPC: "eth_getTransactionByHash" returns a transaction with empty blockHash and blockNumber

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#608]
sending:

```
{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0x99ab199e1f1ab9d5a08373c4e693d5a71a3ac65d52da5430581ed8b74d5b940a"],"id":4540}
```

Returns me the transaction but with the following `blockHash`, `blockNumber` and `transactionIndex` (?):

```js
{
	"id": 4540,
	"jsonrpc": "2.0",
	"result": {
		"hash": "0x99ab199e1f1ab9d5a08373c4e693d5a71a3ac65d52da5430581ed8b74d5b940a",
		"nonce": "0x0",
		"blockHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"blockNumber": "0x0",
		"transactionIndex": "0x0",
		"from": "0x8b09e3535d27ad599d984fd63b1578b6f068f01b",
		"to": "0x8b09e3535d27ad599d984fd63b1578b6f068f01b",
		"value": "0x2710",
		"gas": "0x0186a0",
		"gasPrice": "0x015f90",
		"input": "0x0"
	}
}
```

The transactions are correctly returned using `eth_getTransactionByBlockHashAndIndex ` and when inside a block with `eth_getBlock` and second parameter `true`.

**Comment by frozeman** [comment]
For you taylor: I would expect it to look like this:

```js
{
	"id": 4541,
	"jsonrpc": "2.0",
	"result": {
		"hash": "0x99ab199e1f1ab9d5a08373c4e693d5a71a3ac65d52da5430581ed8b74d5b940a",
		"nonce": "0x0",
		"blockHash": "0xf447117e1b694ffbeeb43dbe2160549e30adf5da0b8250f9357038c51b907dcd",
		"blockNumber": "0x02de",
		"transactionIndex": "0x0",
		"from": "0x8b09e3535d27ad599d984fd63b1578b6f068f01b",
		"to": "0x8b09e3535d27ad599d984fd63b1578b6f068f01b",
		"value": "0x2710",
		"gas": "0x0186a0",
		"gasPrice": "0x015f90",
		"input": "0x0"
	}
}
```

**Comment by frozeman** [comment]
additionally should `input` be `0x`

**Comment by frozeman** [comment]
and if the tx is pending `blockNumber`, `blockHash` and `transactionIndex` should be `null`

**Comment by tgerring** [comment]
The missing values are due to the block context being unavailable at the "transaction" level. In the case of `eth_getTransactionByBlockHashAndIndex ` and `eth_getBlock `, the block is known and details can be added to the transaction.

Somehow, the RPC needs to be able to look up a transaction hash and return the block number it is contained in. This information can be then added to the output.

**Comment by tgerring** [comment]
@frozeman does this still occur after commit 86ba743?
