### ISSUE TITLE
Read (gas) defaults from JSON settings file

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#617]
Defaults should be read from https://github.com/ethereum/common/blob/master/params.json

- [x] create generator for defaults file and output to `core/defaults.go` https://github.com/ethereum/go-ethereum/commit/d3e86f9208d775ee8020d5583d0aac8f3cfb52b2
- [x] replace values using the values from the defaults file

**Comment by Gustav-Simonsson** [comment]
PR: https://github.com/ethereum/go-ethereum/pull/623

**Comment by obscuren** [comment]
:+1:
