### ISSUE TITLE
Fix whisper pow error

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#621]
Whisper is throwing a lot of `invalid pow provided for envelope` errors probably due to an invalid `common.Hash` conversion.

**Comment by zelig** [comment]
@obscuren @karalabe this has been fixed right?

**Comment by karalabe** [comment]
I think this has either been solved, or completely worked around when I went through whisper. We can close it and eventually reopen if it happens again (whenever Whisper gets into scope again).
