### ISSUE TITLE
possible crash?

### ISSUE THREAD

**Issue by simenfd** [ethereum/go-ethereum#630]
Got this while running the latest snapshot and mining. Thought it might be of use?

2015/04/02 18:41:31 [MINER] Hash rate: 4 Khash                                                                   
2015/04/02 18:41:32 [MINER] Hash rate: 10 Khash
2015/04/02 18:41:32 [MINER] Hash rate: 10 Khash
2015/04/02 18:41:33 [CHAIN] processed block #15550 (0 TXs 0 UNCs) (597f71b1...)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x651661]

goroutine 1438 [running]:
github.com/ethereum/go-ethereum/core.(*BlockProcessor).Process(0xc209603420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/xxx/golang/src/github.com/ethereum/go-ethereum/core/block_processor.go:149 +0x111
github.com/ethereum/go-ethereum/core.(*ChainManager).InsertChain(0xc209606000, 0xc298268260, 0x1, 0x1, 0x0, 0x0)
        /home/xxx/golang/src/github.com/ethereum/go-ethereum/core/chain_manager.go:444 +0x14b
github.com/ethereum/go-ethereum/core.*ChainManager.InsertChain·fm(0xc298268260, 0x1, 0x1, 0x0, 0x0)
        /home/xxx/golang/src/github.com/ethereum/go-ethereum/eth/backend.go:206 +0x57
github.com/ethereum/go-ethereum/blockpool.(*peer).getBlockHashes(0xc20cbdc900, 0x0)
        /home/xxx/golang/src/github.com/ethereum/go-ethereum/blockpool/peers.go:465 +0x294
github.com/ethereum/go-ethereum/blockpool.(*peer).run(0xc20cbdc900)
        /home/xxx/golang/src/github.com/ethereum/go-ethereum/blockpool/peers.go:552 +0x4f6
github.com/ethereum/go-ethereum/blockpool.func·006()
        /home/xxx/golang/src/github.com/ethereum/go-ethereum/blockpool/peers.go:350 +0x38
created by github.com/ethereum/go-ethereum/blockpool.(*BlockPool).switchPeer
        /home/xxx/golang/src/github.com/ethereum/go-ethereum/blockpool/peers.go:355 +0x4e6

**Comment by obscuren** [comment]
Thanks! Will look in to it

**Comment by zelig** [comment]
could be related to and fixed by #627 ?

**Comment by obscuren** [comment]
`nil` blocks are passed from the `BlockPool` to the `BlockProcessor` somehow.

**Comment by obscuren** [comment]
I think has been fixed. Please reopen if issue persists after #627
