### ISSUE TITLE
How to import private key from Alethzero ?

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#634]
https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts says
The keyfile is assumed to contain an unencrypted private key in canonical EC
raw bytes format.

From the (hex) private key obtained in Alethzero, how to create this keyfile that Go can import?  Can the wiki be updated?

**Comment by obscuren** [comment]
> @ethers: i pasted the hex private key that AZ told me into a file and when i ran geth account import it created a very different address

**Comment by ethers** [comment]
converting the hex to bytes and writing it to a file worked for me.  i'm closing this and recommending #635
