### ISSUE TITLE
Allow import of hex private key

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#635]
https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts says
The keyfile is assumed to contain an unencrypted private key in canonical EC
raw bytes format.

Can support for importing a hex private key be added?  Alethzero uses hex, and hex is a common format that users may be more familiar with than "canonical EC raw bytes format"

**Comment by obscuren** [comment]
Yes agreed. Hex is the way to go
