### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by simenfd** [ethereum/go-ethereum#637]
I am adding this one as well for you to consider. 
file:geth, 18461912 bytes,  builddate: 03.04.2015 01:56, built from develop branch

2015/04/03 01:53:31 [Blockpool] [ece5de7f-ece5de7f] insert 1 blocks [ece5de7f/ece5de7f] into blockchain
2015/04/03 01:53:31 [CHAIN] processed block #17819 (0 TXs 0 UNCs) (ece5de7f...)
2015/04/03 01:53:31 [Blockpool] [0e0df5ec-0e0df5ec] insert 1 blocks [0e0df5ec/0e0df5ec] into blockchain
2015/04/03 01:53:31 [CHAIN] processed block #17820 (0 TXs 0 UNCs) (0e0df5ec...)
2015/04/03 01:53:31 [Blockpool] [80ff7d8b-80ff7d8b] insert 1 blocks [80ff7d8b/80ff7d8b] into blockchain
2015/04/03 01:53:31 [CHAIN] processed block #17821 (0 TXs 0 UNCs) (80ff7d8b...)
2015/04/03 01:53:31 [Blockpool] [fdf29ad6-fdf29ad6] insert 1 blocks [fdf29ad6/fdf29ad6] into blockchain
2015/04/03 01:53:31 [CHAIN] processed block #17822 (0 TXs 0 UNCs) (fdf29ad6...)
2015/04/03 01:53:31 [Blockpool] [52abacfd-52abacfd] insert 1 blocks [52abacfd/52abacfd] into blockchain
2015/04/03 01:53:31 [CHAIN] processed block #17823 (0 TXs 0 UNCs) (52abacfd...)
2015/04/03 01:53:51 [Peer 4b453cdcc9e7ffe9 54.174.127.93:53159] Peer is [eth] capable (60/0). TD=17839723589 H=52abacfd
2015/04/03 01:54:01 [CHAIN] processed block #17824 (0 TXs 0 UNCs) (ef717e6a...)
2015/04/03 01:54:08 [Peer 4af1f47ac8e99c66 54.174.254.175:54396] Peer is [eth] capable (60/0). TD=17840961301 H=ef717e6a
2015/04/03 01:54:09 [CHAIN] processed block #17825 (0 TXs 0 UNCs) (8ccc9798...)
2015/04/03 01:54:13 [CHAIN] processed block #17826 (0 TXs 0 UNCs) (02626677...)
panic: close of closed channel

goroutine 9915 [running]:
github.com/ethereum/go-ethereum/blockpool.(*BlockPool).switchPeer(0xc20a2e4000, 0xc20b099d40, 0xc20b098a20)
	/home/xxx/golang/src/github.com/ethereum/go-ethereum/blockpool/peers.go:333 +0x195
github.com/ethereum/go-ethereum/blockpool.(*peers).addPeer(0xc20ac872c0, 0xc20b16ebc0, 0xeff4faa31db2eb93, 0x42f6bc78a8d017b9, 0xf1797b58c27e048a, 0xb871115b98b3d8f2, 0xc20a24f3f0, 0x10, 0xc2085b4490, 0xc2085b44a0, ...)
	/home/xxx/golang/src/github.com/ethereum/go-ethereum/blockpool/peers.go:280 +0x116d
github.com/ethereum/go-ethereum/blockpool.(*BlockPool).AddPeer(0xc20a2e4000, 0xc20b16ebc0, 0xeff4faa31db2eb93, 0x42f6bc78a8d017b9, 0xf1797b58c27e048a, 0xb871115b98b3d8f2, 0xc20a24f3f0, 0x10, 0xc2085b4490, 0xc2085b44a0, ...)
	/home/xxx/golang/src/github.com/ethereum/go-ethereum/blockpool/blockpool.go:335 +0x86
github.com/ethereum/go-ethereum/eth.(*ethProtocol).handle(0xc20af8dce0, 0x0, 0x0)
	/home/xxx/golang/src/github.com/ethereum/go-ethereum/eth/protocol.go:301 +0x292f
github.com/ethereum/go-ethereum/eth.runEthProtocol(0x3c, 0x0, 0x7f840c60fab0, 0xc209c2a180, 0x7f840c60fae0, 0xc208112180, 0x7f840c60fb18, 0xc20a2e4000, 0xc20a7392c0, 0x7f840c616418, ...)
	/home/xxx/golang/src/github.com/ethereum/go-ethereum/eth/protocol.go:160 +0x5e2
github.com/ethereum/go-ethereum/eth.func·002(0xc20a7392c0, 0x7f840c616418, 0xc20a6d27d0, 0x0, 0x0)
	/home/xxx/golang/src/github.com/ethereum/go-ethereum/eth/protocol.go:122 +0xa3
github.com/ethereum/go-ethereum/p2p.func·004()
	/home/xxx/golang/src/github.com/ethereum/go-ethereum/p2p/peer.go:242 +0x88
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
	/home/xxx/golang/src/github.com/ethereum/go-ethereum/p2p/peer.go:254 +0x2ad

goroutine 1 [chan receive, 14 minutes]:
main.run(0xc2080dc000)
	/home/xxx/golang/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:270 +0x1cf
github.com/codegangsta/cli.(*App).Run(0xc2080f0000, 0xc20800a000, 0x1, 0x1, 0x0, 0x0)
	/home/xxx/golang/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:182 +0xe5c
main.main()
	/home/xxx/golang/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:253 +0x80

goroutine 5 [runnable]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
	/home/xxx/golang/src/github.com/ethereum/go-ethereum/logger/sys.go:65 +0x6d1
created by github.com/ethereum/go-ethereum/logger.init·1
	/home/xxx/golang/src/github.com/ethereum/go-ethereum/logger/sys.go:44 +0x25

goroutine 17 [syscall, 14 minutes, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

**Comment by zelig** [comment]
i thi fixed by https://github.com/ethereum/go-ethereum/commit/5cb1b41440209b03a1c5ec6c639207fd336e67e3 -> #627 
can you confirm you built before this fix?

**Comment by simenfd** [comment]
I am quite sure. We can close this for now.
