### ISSUE TITLE
CLI option to reset the chain

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#643]
This is a suggestion for #639  because "keys" is inside the datadir,  and resetting the chain isn't as simple as rm -rf datadir.
cpp eth CLI has:     -K,--kill-blockchain  First kill the blockchain.

**Comment by obscuren** [comment]
resetting the chain is really as simple as `rm -rf path/to/ethereum/blockchain`

**Comment by ethers** [comment]
thanks @obscuren I added that to a wiki: https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options/a9744b3b54c22c8e99dd2d291e2901f3972d0506

**Comment by obscuren** [comment]
Cheers
