### ISSUE TITLE
Always "Breaking from mining"

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#646]
develop ac473a8

Ran Geth with mining (and default logging level).  For over 30 minutes, the only logs are "Breaking from mining" except for the occasional ``[P2P NAT] mapping error: no devices discovered``
Is Geth actually doing some mining, or it's unable to because new blocks are being produced too quickly?

```
2015/04/04 18:05:08 [POW] Making Cache
2015/04/04 18:05:09 [POW] Took: 1.089541915s
2015/04/04 18:05:09 [POW] Retrieving DAG
2015/04/04 18:05:10 [POW] Took: 837.225652ms
2015/04/04 18:05:11 [POW] Breaking from mining
2015/04/04 18:05:11 [POW] Breaking from mining
2015/04/04 18:05:11 [POW] Breaking from mining
2015/04/04 18:05:22 [POW] Breaking from mining
2015/04/04 18:05:22 [POW] Breaking from mining
and so on
2015/04/04 18:29:57 [POW] Breaking from mining
2015/04/04 18:29:57 [POW] Breaking from mining
```

**Comment by obscuren** [comment]
https://github.com/ethereum/go-ethereum/commit/3040296beb3a8ca991b738a83df0af7bddde2ac6
