### ISSUE TITLE
geth hangs when trying to get peerCount via JSON-RPC

### ISSUE THREAD

**Issue by cubedro** [ethereum/go-ethereum#649]
After a while geth won't return any result when trying to get peerCount:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":3}' localhost:8545
```

It just hangs without returning any result.

**Comment by tgerring** [comment]
Any idea how long it takes for this condition to occur? I've written a small program that will ping the RPC for peerCount every 5 seconds in hopes of seeing a certain time or request limit trigger the problem.

Gist of program here: https://gist.github.com/tgerring/1393feff35a2132462be

**Comment by tgerring** [comment]
Ran the above for about 3.5 hours and didn't seem to hang geth.

**Comment by tgerring** [comment]
@cubedro Does this issue persist or can it be closed?

**Comment by cubedro** [comment]
It can be closed. Issue fixed.
