### ISSUE TITLE
every 15 min "goupnp: SOAP request got HTTP 500 Internal Server Error"

### ISSUE THREAD

**Issue by aperseghin** [ethereum/go-ethereum#651]
this happens every 15 min , I have my ports forwarded so there is no reason to keep trying to use upnp to map them every 15 min. I know its not actually causing an issue with my connection, but it seems like something that should not happen 

```
2015/04/06 11:30:10 [P2P NAT] mapping error: goupnp: SOAP request got HTTP 500 Internal Server Error
2015/04/06 11:30:11 [P2P NAT] mapping error: goupnp: SOAP request got HTTP 500 Internal Server Error
2015/04/06 11:45:10 [P2P NAT] mapping error: goupnp: SOAP request got HTTP 500 Internal Server Error
2015/04/06 11:45:11 [P2P NAT] mapping error: goupnp: SOAP request got HTTP 500 Internal Server Error
2015/04/06 12:00:11 [P2P NAT] mapping error: goupnp: SOAP request got HTTP 500 Internal Server Error
2015/04/06 12:00:11 [P2P NAT] mapping error: goupnp: SOAP request got HTTP 500 Internal Server Error
```

**Comment by aperseghin** [comment]
ok rather than failing every 15 min, it should have a maximum fault number (like 4[aka 1hour]) before it no longer maps 

proposed fix
```
const (
	mapTimeout        = 20 * time.Minute
	mapUpdateInterval = 15 * time.Minute
        mapFailureLimit = 4
-------------------------------------------------
//this will also need to be changed to check for failure limit
	refresh := time.NewTimer(mapUpdateInterval)
		defer func() {
			refresh.Stop()
			log.Debugf("Deleting port mapping: %s %d -> %d (%s) using %s\n", protocol, extport, intport, name, m)
```

**Comment by fjl** [comment]
‎The reason why it is useful to retry ad infinitum inside of nat.Map is that your laptop might suddenly enter a network where the port is not mapped and mapping it actually succeeds. We will have some code in the future that recognizes network changes and triggers router (re)discovery. If you have ‎the port mapped manually, use "--nat extip:<IP>:<port>" to make it skip UPNP and announce your mapped port.

**Comment by obscuren** [comment]
Non issue and will not be changed. As @fjl already said we do not know if you switch network. It should **always** try, there's no harm in it.
