### ISSUE TITLE
uncle and block transaction count should accept "latest", "pending" and "earliest" as parameters

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#654]
Marek implemented the possibility for `"latest"` (last minded block), `"pending"` (pending) and `"earliest"` (genisis block) for the following RPC methods:

- `eth_getUncleCountByBlockNumber`
- `eth_getUncleCountByBlockHash`
- `eth_getBlockTransactionCountByHash`
- `eth_getBlockTransactionCountByNumber`

He  sadly didn't put this as for debate, but integrated it already into ethereum.js as well and c++.
It makes sense to check for example for the number of pending transactions.

So i guess it makes sense if we integrate this behaviour as well.

I already add tests for it in the rpc-tests.

**Comment by obscuren** [comment]
This should be fixed on `develop` now

**Comment by tgerring** [comment]
These are implemented for "ByNumber"

"ByHash" should not accept non-hash arguments

**Comment by obscuren** [comment]
@frozeman retest and close accordingly

**Comment by tgerring** [comment]
@frozeman Can this issue be closed?
