### ISSUE TITLE
Broken link for detailed go build instructions

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/go-ethereum#661]
The README.md file states:

"For prerequisites and detailed build instructions please see the [Wiki](https://github.com/ethereum/go-ethereum/wiki/Building-Ethereum(Go))"

The link to https://github.com/ethereum/go-ethereum/wiki/Building-Ethereum(Go) is broken.

**Comment by maran** [comment]
Sorry the correct link should probably be: https://github.com/ethereum/go-ethereum/wiki/Building-Ethereum

**Comment by obscuren** [comment]
PR? :+1:

**Comment by zelig** [comment]
fixed in https://github.com/arboreum/go-ethereum/commit/59a7405a8072b735472de885c33c2a82fcf7a162
