### ISSUE TITLE
creating two contracts with the same address

### ISSUE THREAD

**Issue by debris** [ethereum/go-ethereum#664]
Tested on mac 10.9, 7c0a18edb58c46a68bdf524dc2bf3e7edf61dba2
Probably one of the transactions was not processed properly, but there was no error log.

Scenario:
1. I've created 7 contracts.
2. Then started mining
3. Created few more.

Two contracts had the same address. 

```bash
2015/04/08 11:45:15 [XETH] Contract addr a427bba22be20e3475faac3c9771f08778859bb3
2015/04/08 11:59:59 [XETH] Contract addr a427bba22be20e3475faac3c9771f08778859bb3
```

screenshot:

![screen shot 2015-04-08 at 12 02 36](https://cloud.githubusercontent.com/assets/2613714/7043185/f89b151e-dde7-11e4-8eb1-66105eaefda5.png)

**Comment by obscuren** [comment]
Did `a427b` fail maybe?

**Comment by debris** [comment]
Probably...

**Comment by obscuren** [comment]
Then it's reasonable it created the same contract w/ the same address :-) Please re-open if you do encounter it again.
