### ISSUE TITLE
admin.unlock timeout issue

### ISSUE THREAD

**Issue by debris** [ethereum/go-ethereum#665]
Tested on mac 10.9, 7c0a18edb58c46a68bdf524dc2bf3e7edf61dba2
According to [wiki](https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#adminunlock)

```javascript
admin.unlock('0x833b8ed5a2957e5b050ba6539efa66cb67165eec', '1234', 1000 * 60 * 10) // unlock for 10 mins
```

should unlock account for 10 minutes. For me it was unlocked for at least 45 minutes. I was making transactions through JSONRPC api.

screenshot:
![screen shot 2015-04-08 at 12 02 36](https://cloud.githubusercontent.com/assets/2613714/7043287/cc37647c-dde8-11e4-85ba-b9e41231cf2b.png)

**Comment by zelig** [comment]
@debris the wiki says "timeout in seconds", you put 600000 seconds :)
