### ISSUE TITLE
geth console should log attempt of transaction on locked account

### ISSUE THREAD

**Issue by debris** [ethereum/go-ethereum#666]
when account is unlocked, we can see the log:

```
2015/04/08 12:54:34 [XETH] Contract addr 05c5c33cb8c4c287ca7cfb26a4dff57a57afeb33
```

but there is no log for failed attempt of transaction on locked account. It would be great if we could have something like:

```
2015/04/08 12:54:34 [RPC] Transaction failed. Could not unlock sender account
```

**Comment by obscuren** [comment]
https://github.com/ethereum/go-ethereum/issues/662

**Comment by obscuren** [comment]
Err sorry. Mistake

**Comment by obscuren** [comment]
Been thinking about this and I disagree that the geth log should output you the error message. The interface should take care of in or output (good or bad). You create a transaction through the RPC and the RPC returns you an error. Callers take care of error handling so you should deal with the error

![l5qkp3bcssnawtnnw-0wzej5uud1qgygu4x90ll-qbe](https://cloud.githubusercontent.com/assets/6264126/7053102/1e87e694-de33-11e4-8e12-6da11f11c667.png)

If a transaction is being created from the `geth console` it will display an error message there.
