### ISSUE TITLE
rpc filter issues

### ISSUE THREAD

**Issue by debris** [ethereum/go-ethereum#669]
Tested on mac 10.9, 7c0a18edb58c46a68bdf524dc2bf3e7edf61dba2

### Note
You can use [eth-event-tests](https://github.com/debris/eth-event-tests) repository to reproduce these issues faster

### overview

I've been playing with go rpc filters recently, and found few issues:

- [ ] Filtering events, by passing an address does not work. [Details in address_issue](#address_issue)
- [ ] When node is not mining, events are 'not saved'. [Details in mining_issue](#mining_issue)
- [ ] Passing `earliest` as `fromBlock` doesn't work, but it should. [Details in earliest_issue](#earliest_issue)

#### address_issue
- Filtering events, by passing an address does not work. Scenario:
  - create contract
  - mine
  - call contract function, which triggers an event
  - call to eth_getLogs returns empty array

request:

```json
{
  "jsonrpc": "2.0",
  "method": "eth_getLogs",
  "params": [
    {
      "fromBlock": "0x0",
      "address": "0xfa606d6c3737862698a00c5b76679c87561be7b8"
    }
  ],
  "id": 1
}
```

response:

```json
{
	"id": 1,
	"jsonrpc": "2.0",
	"result": []
}
```

#### mining_issue
- When node is not mining, events are 'not saved'. Scenario:
  - create contract
  - mine
  - stop mining
  - call contract function, which triggers an event
  - call contract function, which triggers an event
  - start mining
  - call to eth_getLogs returns empty array

#### earliest_issue
- Minor issue. Passing `earliest` as `fromBlock` doesn't work, but it should. See [wiki](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter)

**Comment by tgerring** [comment]
@debris Please split these into discrete issues so they can be addressed.

For example, addressing your 3rd point, can you describe how you determine this? I have a unit test that appears to disagree with you at https://github.com/ethereum/go-ethereum/blob/6284604b52e075e454e61f2933cadaaf9ded364b/rpc/args_test.go#L1370-L1391

**Comment by tgerring** [comment]
For issue 2, " Filtering events, by passing an address does not work."

It seems that passing an address works fine. Unit tests here: https://github.com/ethereum/go-ethereum/blob/6284604b52e075e454e61f2933cadaaf9ded364b/rpc/args_test.go#L1258-L1368

IS the issue that the address isn't being respected when registering or filtering the logs?

**Comment by debris** [comment]
@tgerring ok, I will split

**Comment by debris** [comment]
> IS the issue that the address isn't being respected when registering or filtering the logs?

yes

**Comment by frozeman** [comment]
the address is a duplicate of #629

**Comment by debris** [comment]
> the address issue is a duplicate of #629

yes, i will not split this one

**Comment by debris** [comment]
> For example, addressing your 3rd point, can you describe how you determine this? I have a unit test that appears to disagree with you at https://github.com/ethereum/go-ethereum/blob/6284604b52e075e454e61f2933cadaaf9ded364b/rpc/args_test.go#L1370-L1391

@tgerring I've pulled latest develop and it's working. Thanks

**Comment by debris** [comment]
I will close this issue and create new only for 2nd.
