### ISSUE TITLE
When node is not mining, events are 'not saved'.

### ISSUE THREAD

**Issue by debris** [ethereum/go-ethereum#670]
Tested on mac 10.9, 7c0a18edb58c46a68bdf524dc2bf3e7edf61dba2

**You can use [eth-event-tests](https://github.com/debris/eth-event-tests) repository to reproduce these issues faster**

- When node is not mining, events are 'not saved'. Scenario:
  - create contract
  - mine
  - stop mining
  - call contract function, which triggers an event
  - call contract function, which triggers an event
  - start mining
  - call to eth_getLogs returns empty array

*tested on private network*

eth_getLogs request:

```json
{
  "jsonrpc": "2.0",
  "method": "eth_getLogs",
  "params": [
    {
      "fromBlock": "earliest",
      "topics": [
        "bcdfe0d5b27dd186282e187525415c57ea3077c34efb39148111e4d342e7ab0e"
      ]
    }
  ],
  "id": 1
}
```

**Comment by obscuren** [comment]
Not sure what you mean with "not saved"

**Comment by debris** [comment]
It seems like these transactions were not executed properly. More specifically, logs which should be created by these transactions do not exist. It happens only when I'm on the **private** network and there are not any nodes mining at the time of sending transaction.

**Comment by obscuren** [comment]
I'm not sure I understand. Is this an issue or this not an issue?
