### ISSUE TITLE
Ethash crashes during epoch switch

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#683]
```
geth(8527,0xb0499000) malloc: *** error for object 0xc28cba2008: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fff94076866
signal arrived during cgo execution
``` 

see full trace here: https://gist.github.com/zelig/932c47aa6f9166c12292
not sure if the new epoch has something to do with this, but it happened when the node was on block #59999

When restarted the client in mining mode, the same crash happens. 
I had to restart without mining, then switch it on after a bit.

**Comment by obscuren** [comment]
Waiting on `ethash` to be up to date. This is an issue with `ethash` it self.

**Comment by obscuren** [comment]
https://github.com/ethereum/ethash/commit/10ade058724e92166ba388a1408bd4073bcbf865
