### ISSUE TITLE
suggestion: miner should only start after it has synced the blockchain

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#684]
On develop ec9fbf0

To repro, stop Geth and wait for further blocks to be added to the chain.
Then run Geth with mining: observe the log and see that Geth immediately starts mining from it's old chain instead of waiting to mine on the "current/longest" chain.

I believe this is also the cause of issues such as #683, #645

**Comment by obscuren** [comment]
[09/04/15 23:38:36] J Chow: ok i agree impossible to know; so maybe a suggestion is to
[09/04/15 23:39:07] J Chow: check every few seconds how many blocks are getting synced, and when the number starts decreasing, mining could start

**Comment by obscuren** [comment]
I'm going to leave it to the user to determine whether it should mine or not. A person is a better judge then a computer program in this case:

* Miner A wants to mine on the network
* Malicious miner B starts propagating fake blocks to miner A
* Miner A receives malicious blocks and waits with mining (Catching up ...)
* Miner B continues mining on the true chain
* Miner B gets the moolah
* Miner A is sad :-(
