### ISSUE TITLE
`geth': free(): invalid pointer: 0x000000c29ca16008

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#685]
On develop ec9fbf0

My Geth has been offline for around a day.  I started Geth with mining.  Geth crashed with following log:
https://gist.github.com/ethers/77146833be0ee89e9532

(I think some suggestion like #684 could help minimize occurrences of this issue)

**Comment by obscuren** [comment]
Fixed in https://github.com/ethereum/ethash/commit/10ade058724e92166ba388a1408bd4073bcbf865
