### ISSUE TITLE
Eventer blocked by miner 

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#697]
latest geth develop
caught up from 0 while generating DAGs for mining .
after a while eventer blocked and not sending ChainHeadEvent,
as a consequence the remaining miner threads are mining on block #53xxx while current head was actually #73xxx
blockpool is well behaved this time .

issue similar or same as #681 

candidates:
miner worker is blocking sending on nil channel https://gist.github.com/zelig/47aac65c5828a9dddfa3#file-gistfile1-txt-L238
miner worker deadlocks on mutex https://gist.github.com/zelig/47aac65c5828a9dddfa3#file-gistfile1-txt-L1262 and https://gist.github.com/zelig/47aac65c5828a9dddfa3#file-gistfile1-txt-L1462

stacktrace:
https://gist.github.com/zelig/47aac65c5828a9dddfa3

**Comment by obscuren** [comment]
This is reproducible by catching up for 0 and starting mining (even though not caught up)?

**Comment by obscuren** [comment]
This has been addressed and fixed last week. Please re-open if issue persists
