### ISSUE TITLE
Account Visibility Param for CLI

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/go-ethereum#699]
What if I only want specific accounts visible to DApps, would it be worth it to have a CLI param for this? Perhaps something like: 'geth --visible="0,3,4"' (where 0, 3, 4 are accounts 0, 3 and 4). The reason is that some DApps will have full access to all user accounts, some users may not want specific accounts to be in anyway related to others that they own (i.e. they have some private and some public accounts). This is mainly a practical privacy concern.

**Comment by obscuren** [comment]
Yep. Mist will allow such things in the future:

```
+--[ account management ] ---------------------------+
|               Account a   Account b   Account c    |
| MyCool dapp     [x]         [x]          [ ]       |
| Casino X        [ ]         [ ]          [x]       |
| Etc             [ ]         [x]          [x]       |
|                                                    |
|                                  [ kk save it ]    |
+----------------------------------------------------+
```

(Yes, I'm a sucker for ASCII interfaces)

**Comment by zelig** [comment]
:+1:

**Comment by SilentCicero** [comment]
+1, new product venture: Mist ASCII?

**Comment by obscuren** [comment]
Been playing around with https://github.com/gizak/termui - maybe someday ...

**Comment by fjl** [comment]
Mist now has [its own repo](https://github.com/ethereum/mist) and includes this feature as a button on the address bar.
