### ISSUE TITLE
Panic on shutdown

### ISSUE THREAD

**Issue by simenfd** [ethereum/go-ethereum#707]
Minor issue, running 
commit 61db7a71dd809a003b5c899398b02945c04890c9
Merge: f047699 406feee
Author: Jeffrey Wilcke <jeffrey@ethereum.org>
Date:   Sat Apr 11 10:46:34 2015 +0200

On CTRL-C:

I0413 21:03:49.048665   30909 chain_manager.go:544] imported 1 block(s) 0 queued in 4.413396ms. #90508 [6baf3d29 / 6baf3d29]
I0413 21:03:59.997333   30909 chain_manager.go:544] imported 1 block(s) 0 queued in 5.669108ms. #90509 [3539ddfe / 3539ddfe]
I0413 21:04:03.834688   30909 chain_manager.go:544] imported 1 block(s) 0 queued in 4.034872ms. #90510 [c3e7d720 / c3e7d720]
^CI0413 21:04:31.443043   30909 cmd.go:53] Shutting down (interrupt) ... 
I0413 21:04:31.443179   30909 transaction_pool.go:219] TX Pool stopped
I0413 21:04:31.469081   30909 backend.go:423] Server stopped
2015/04/13 21:04:31 [Blockpool] Stopping...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7f1f7a]

goroutine 55 [running]:
github.com/ethereum/go-ethereum/blockpool.func·001()
        /home/xxx/Godevelop/src/github.com/ethereum/go-ethereum/blockpool/blockpool.go:253 +0x4ea
created by github.com/ethereum/go-ethereum/blockpool.(*BlockPool).Start
        /home/xxx/Godevelop/src/github.com/ethereum/go-ethereum/blockpool/blockpool.go:268 +0x7fd

goroutine 1 [runnable]:
main.run(0xc20807a540)
        /home/xxx/Godevelop/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:277 +0x188
github.com/codegangsta/cli.(*App).Run(0xc2080d6000, 0xc20800a000, 0x1, 0x1, 0x0, 0x0)
        /home/xxx/Godevelop/src/github.com/codegangsta/cli/app.go:182 +0xe5c
main.main()
        /home/xxx/Godevelop/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:261 +0xc7

**Comment by zelig** [comment]
thx legit. will fix. see also #672

**Comment by zelig** [comment]
fixed = obsoleted by new downloader
