### ISSUE TITLE
Geth js console not parsing a string

### ISSUE THREAD

**Issue by joeykrug** [ethereum/go-ethereum#710]
So I have a contract with a function and signature:  
```def createEvent(branch, description:str, expDate, minValue, maxValue, numOutcomes):```

Then I try to call this function using geth console: 
``` contract.call({"from": coinbase}).createEvent(1010101, "test", 97000, 0, 1, 2).toNumber();```

And I get the following error:
```parser does not support type: string
    at <unknown>
    at <unknown>
    at <unknown>
    at <unknown>
    at createEvent (<anonymous>:-10733:-91)
    at <anonymous>:1:1```

**Comment by bas-vk** [comment]
I'm unable to reproduce this issue. One thing I notice is that you are passing the description string as is. Please try something as:

`var desc = web3.fromAscii("test");`
`contract.call({"from": coinbase}).createEvent(1010101, desc, 9700, 0, 1, 2).toNumber();`

Search for ascii on this page https://github.com/ethereum/wiki/wiki/JavaScript-API and you will find a to and from method to convert to and from the ethereum representation of strings.

**Comment by joeykrug** [comment]
Test case below; tried the fromAscii thing & still getting this error

``` def roflcopter(lol: str):
  return(1)
```

```var evm = '0x61006c8061000e60003961007a56600060ff537c01000000000000000000000000000000000000000000000000000000006000350463634ccf2081141561006a57602460043580806020015990590160009052818152602081019050905060405280826040513780820191505050600160e052602060e0f35b505b6000f3';
var coinbase = eth.coinbase
var gas_amount = 1000000
var address = eth.sendTransaction({from: coinbase, gas: gas_amount, code: evm});
var desc = [{"name": "roflcopter(string)","type": "function","inputs": [{ "name": "lol", "type": "string" }],"outputs": [{ "name": "out", "type": "int256" }]}];
var Contract = web3.eth.contract(desc);
contract = new Contract(address);
var description = web3.fromAscii("test");
contract.call({"from": coinbase}).roflcopter(description).toNumber();```

**Comment by obscuren** [comment]
Cheers

**Comment by obscuren** [comment]
@debris 

```
> contract.call({"from": coinbase}).roflcopter(description).toNumber();
parser does not support type: byte32
    at <unknown>
    at <unknown>
    at <unknown>
    at <unknown>
    at roflcopter (<anonymous>:-10733:-70)
    at <anonymous>:1:1
```

any idea?

**Comment by chriseth** [comment]
The reason might be that `string` is not an ABI type anymore, it was replaced by `bytes` (dynamic length) and `bytes0`, ..., `bytes32`.

**Comment by obscuren** [comment]
That's it. Cheers

**Comment by joeykrug** [comment]
How does this work with serpent?  Serpent still has strings as a type --- should I just convert to a byte array or...?

**Comment by tinybike** [comment]
Would also like to know the answer with this.  Almost all our contracts (written in Serpent) are broken until this is fixed.

**Comment by tinybike** [comment]
If nothing else, is it possible to restore the `string` type?  We wrote quite a bit of code that depends on this.

**Comment by joeykrug** [comment]
Seems this is a serpent issue --- no need to restore string, figured out the problem & gonna take it to serpent page

**Comment by chriseth** [comment]
A quick fix should be to replace "string" types  by "bytes" in the ABI description JSON:
```
var desc = [{"name": "roflcopter(string)","type": "function","inputs": [{ "name": "lol", "type": "bytes" }],"outputs": [{ "name": "out", "type": "int256" }]}];
```
Note that the `string` in the name is not replaced.
