### ISSUE TITLE
Mining error: incorrect total difficulty

### ISSUE THREAD

**Issue by tinybike** [ethereum/go-ethereum#712]
I'm running geth v. 0.9.9 (installed from ppa) on two Ubuntu 14.04 machines.  On one machine mining with `geth --rpc --mine` works beautifully.  On the other, when I start the miner I get this error (many many times):
```
I0414 03:32:03.649881    4723 chain_manager.go:548] imported 1 block(s) 0 queued in 7.320234ms. #95935 [06983bf4 / 06983bf4]
I0414 03:32:03.649972    4723 errors.go:82] [Blockpool] ERROR: Incorrect Total Difficulty: on block 6331366534313131 291935194085 =?= 279304343289
```
I tried deleting `/tmp/dag` but after generating the new DAG I get the same error again.  I just re-deleted `/tmp/dag` and this time also deleted `blockchain`, `extra`, and `state` directories from `~/.ethereum` and am now waiting for the DAG to regenerate.

**Comment by obscuren** [comment]
It's fine, you've got nothing to worry about. Operation is normal 

@zelig please get rid of that error message :-)

**Comment by tinybike** [comment]
Great, thanks for the heads-up.  Should we leave this open until the error message is deleted?

**Comment by obscuren** [comment]
Yup. Leave open until @zelig has addressed this

**Comment by zelig** [comment]
see #706 for some background. 
I want to leave this warning in though but maybe report only once per batch insert and suspend peer (demote and remember not to promote) but not disconnect. OK?

**Comment by zelig** [comment]
believe its fixed in https://github.com/ethereum/go-ethereum/commit/72d065d49102dd07c929d1e147186604c5e4ab05
