### ISSUE TITLE
ERROR: Idle too long

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/go-ethereum#713]
I finally got `geth` installed on Mac OS X. I can get one peer (`web3.net.peerCount`) but get the following message without any blocks downloading:

```
I0414 21:00:26.416117    5377 errors.go:82] [Blockpool] ERROR: Idle too long: timed out without providing new blocks (td: 293580293984, head: cedaabec)...quitting
I0414 21:00:26.416289    5377 peers.go:360] addPeer: no suitable peers found
```

**Comment by zelig** [comment]
This sounds legit behaviour. You get this error when the peer is ... well idle too long, we expect best peers to keep sending blocks.
The fact that you do not find more peers could be because most are saturated with many connections.
Anyhow, closing as non-issue.
