### ISSUE TITLE
What does "mapping error" mean?

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/go-ethereum#716]
When I launch `geth`, I get:

```
5420 nat.go:94] mapping error: no devices discovered
```

What does that mean?

**Comment by zelig** [comment]
It means p2p network layer's NAT module does not find your router and won't be able to map your port for listening and accepting inbound peers or get external IP. 
If you know better or mapped manually, use the `-nat` command line option.

Outbound connections are not affected, provided your network is fine, you can connect to the ethereum nodes. 

I recommend using IRC, skype, gitter or forum for generic questions and keep Github issues for bugs and feature requests.
