### ISSUE TITLE
Manually add peer

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/go-ethereum#717]
How can I manually add a peer, if I know their IP address (e.g. from [here](http://eth-netstats.herokuapp.com/)).

I've had a look in the JS API, but can't find anything.

**Comment by zelig** [comment]
I'm afraid IP is not enough, you need the node's NodeID. We are using the enode format that incorporates this in a url. 
Using that url, you can connect via console command: 
https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#adminsuggestpeer
or 
CLI parameter `bootnodes` which takes a whitespace separated list of enode urls. 
https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

I recommend using IRC, skype, gitter or forum for generic questions and keep Github issues for bugs and feature requests.
