### ISSUE TITLE
Incorrect version number in JS API

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/go-ethereum#722]
`web3.version.network` (the "The network protocol version.") returns 0, despite the initial boot message:

```
I0415 08:30:08.043643    5567 backend.go:184] Protocol Version: 60
```

**Comment by zelig** [comment]
try `web3.version.ethereum`
Justin case you missed this https://github.com/ethereum/wiki/wiki/JavaScript-API#web3versionethereum

We do generally slack on dox but @frozeman is KING 

What may not be well explained is that there is a network id (indicating separate chains and networks).
Testnet and live will be different network IDs for instance while both could be connected to a by nodes potentially running the same protocol version.

Network ID can also be used to set up isolated 'private' networks. https://github.com/ethereum/go-ethereum/wiki/Setting-up-private-network-or-local-cluster
