### ISSUE TITLE
ChainSplitEvent not posted

### ISSUE THREAD

**Issue by bas-vk** [ethereum/go-ethereum#735]
In case a new block with a higher TD and lower block number is inserted into the ChainManager a ChainSplitEvent is generated. The chainmanager queues events for performance reasons and adds the event to a queue. This event is later overriden with a ChainEvent and thus never posted and handled.

https://github.com/ethereum/go-ethereum/blob/develop/core/chain_manager.go#L512
https://github.com/ethereum/go-ethereum/blob/develop/core/chain_manager.go#L529

**Comment by zelig** [comment]
@obscuren  has this not been fixed yet? looks quite obsolete
