### ISSUE TITLE
eh_version should be renamed to eth_protocolVersion

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#737]

**Comment by tgerring** [comment]
Directly conflicts with #714

**Comment by obscuren** [comment]
Come on .. again? I changed this 4 times now.

**Comment by frozeman** [comment]
haha. gav changed it. It wasn't me. i would have been fine with `eth_version`.
Cpp has it implemented and web3.js uses it now to and the rcp-tests, so i guess you guys have take the hit now.

**Comment by tgerring** [comment]
@frozeman Title says "eh_version", but I am assuming this is meant to be "eh_version" since there is no link to documentation or examples provided.

**Comment by frozeman** [comment]
auto correct sorry.
But you seem to be joking. You know exactly what to do here and its a 1 line fix waiting since 5 days. And i wrote that to you personally probably 2 weeks ago when gav wanted to change it.

Anyway don't want to fight here ;)

I guess you know what to change right?

**Comment by tgerring** [comment]
Hi @frozeman did you see the linked PR #784 above? I believe that fixes the reported issue

**Comment by frozeman** [comment]
No i didn't thanks ;)
