### ISSUE TITLE
Calling a contract method on a non-contract address returns "0x00" should be "0x"

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#739]

**Comment by tgerring** [comment]
Closing this issue as it does not contain an example or any helpful information to debug the problem.

**Comment by frozeman** [comment]
Ok for you, try:

```
{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x6295ee1b4f6dd65047762f924ecd367c17eabf8f","data":"0x343a875d"},"0x0"],"id":6}
```

**Comment by tgerring** [comment]
This issue still does not have minimum info:

* expected
* actual
* steps to reproduce

**Comment by frozeman** [comment]
The title states the actual and expected: `returns "0x00" should be "0x"`

The curl call will give you back "0x00". I think its a simple to test case and spending half an hour to write up some detailed description etc. doesn't make a difference here, as its a one liner to test.

**Comment by tgerring** [comment]
Making the call
```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x6295ee1b4f6dd65047762f924ecd367c17eabf8f","data":"0x343a875d"},"0x0"],"id":1}' http://127.0.0.1:8545
```
Returns
```
{
	"id": 1,
	"jsonrpc": "2.0",
	"result": "0x00"
}
```

Expected
```
{
	"id": 1,
	"jsonrpc": "2.0",
	"result": "0x"
}
```

**Comment by frozeman** [comment]
cool thanks. Is it in progress now?

**Comment by tgerring** [comment]
@frozeman Can you confirm what I pasted above is indeed what you're seeing on your end? I don't have a counter examples to base it off of right now, so I'm making guesses

**Comment by frozeman** [comment]
Yes thats what i got. Let me check again...yes still the same:

```
{
	"id": 4,
	"jsonrpc": "2.0",
	"result": "0x00"
}
```

This also applies when calling a address with a contract, but with the wrong abi (one of a non existing function).

**Comment by frozeman** [comment]
Here as an js example:

```js
// correct call
web3.eth.call({"to":"0x6295ee1b4f6dd65047762f924ecd367c17eabf8f","data":"0x343a875d"})
"0x0000000000000000000000000000000000000000000000000000000000000008"

// wrong abi
web3.eth.call({"to":"0x6295ee1b4f6dd65047762f924ecd367c17eabf8f","data":"0x343a875dd"})
"0x00"

// wrong address
web3.eth.call({"to":"0x6295ee1b4f6dd65047762f924ecd367c17edbf8f","data":"0x343a875d"})
"0x00"
```
