### ISSUE TITLE
label unsupported RPC calls in Frontier

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#740]
RPC calls that Geth isn't supporting for Frontier, should be listed somewhere and/or mentioned in the RPC wiki.

Here's an example:
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_compilesolidity

(We have docs like the web3.js sample that use compileSolidity and people may try with Geth)

**Comment by obscuren** [comment]
Before attempting to compile https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getcompilers should be checked

**Comment by tgerring** [comment]
The following RPC calls are currently coded to return "Not Implemented" errors:
* eth_flush (no longer see this in JSON RPC docs--can be removed?)
* eth_compileSolidity (not supported for Frontier)
* eth_compileLLL (not supported for Frontier)
* eth_compileSerpent (not supported for Frontier)
* shh_newGroup (lacking sufficient documentation)
* shh_addToGroup (lacking sufficient documentation)

@frozeman Can you confirm the above?

**Comment by zelig** [comment]
eth_compileSolidity is gonna be supported #774

**Comment by frozeman** [comment]
i think `flush` was removed by gav.
i can confirm the other, plus the `register` and `unregister` functions, which were only add to the js docs, but never to the RPC.

all other should work, though i never testes `get/submitWork`

**Comment by tgerring** [comment]
eth_flush removed in https://github.com/tgerring/go-ethereum/tree/50536b947d9a5d489f8a53df7c3f13548099d9dc
Privionary support for eth_register and eth_unregister added in https://github.com/tgerring/go-ethereum/commit/0eff352c8d1ce22b3d0375207bebc24555a05e30 but it doesn't seem much is done with the values aside from simply tracking them.

**Comment by obscuren** [comment]
`eth_register` and `eth_unregister` will be used in the foreseeable future.

**Comment by tgerring** [comment]
Documentation has been greatly improved as has support for compiler calls, so I'm closing this issue for now. Please open new issues for eth_register/eth_unregister or anything else that needs addressing
