### ISSUE TITLE
contract call is not using the "from" parameter

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#742]
Geth develop 4020258 and web3.js develop 271b00f

Run Geth and unlock a specific account (not the primary account), call this addrA.

Have a contract foo() that returns transaction ORIGIN.

Do the standard stuff to set up the contract (https://github.com/ethereum/web3.js/blob/develop/example/contract.html#L45-L48)

Now call:
``contract.call({from: <addrA>}).foo()``

EXPECTED
addrA

OBSERVED
another address (perhaps the address of the Geth primary account)
contract call is not using the "from" parameter

**Comment by zelig** [comment]
I'm afraid this is the correct Or at least intended behaviour. Unlocking has nothing to do with default sender. Do you think this is confusing? 


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by ethers** [comment]
I want call() to use the account that I have unlocked.  So I pass that as the "from" parameter to call().  Shouldn't that work ?

Or if we forget about unlocking, I pass X as "from" parameter to call().  Shouldn't call() now use X as the sender?

**Comment by fjl** [comment]
Passing `from` to call should work. The account does not need to be unlocked.

**Comment by ethers** [comment]
@fjl Thanks for clarifying.  This issue is indeed about "Passing from to call should work and use it as the sender."

(Switching to sendTransaction worked as expected and used the "from" parameter)

**Comment by fjl** [comment]
@frozeman please add an RPC test for this if possible.

**Comment by zelig** [comment]
sorry for my earlier reply, my phone didnt display <addr> (probably thinking it was a tag)? funny so I thought you left it out and expected unlocked address to be default sender :)

**Comment by ethers** [comment]
works and thanks for the quick fix!
