### ISSUE TITLE
No RPC access control?

### ISSUE THREAD

**Issue by drupalnomad** [ethereum/go-ethereum#745]
It's possible to unlock an account at startup  with --unlock, but it doesn't there doesn't seem to be any access control on the wire. With bitcoin you have a username and password as part of the connection uri.

**Comment by obscuren** [comment]
We do not allow unlocking of accounts through the JSON RPC for security reasons. If you'd like to unlock accounts during runtime consider using `geth console` which enabled the interactive JavaScript environment and execute `admin.unlock(<address>)`

**Comment by fjl** [comment]
I think @drupalnomad is referring to HTTP-level authentication for the RPC interface. AFAIK we are not planning to add that for the Frontier release, but it is certainly possible to implement.
