### ISSUE TITLE
Panic: saved dag from future epoch

### ISSUE THREAD

**Issue by tinybike** [ethereum/go-ethereum#752]
I'm seeing the following panic when I attempt to mine with geth (specific command used was `geth --rpc --mine --rpccorsdomain "http://127.0.0.1:8545" --unlock primary console`):
```
I0420 01:04:30.712834   17500 ethash.go:198] Retrieving DAG
2015/04/20 01:04:42 [Peer cf2336ebf5c5cf92 92.51.165.126:34098] broadcast failed: use of closed network connection
2015/04/20 01:05:10 [Peer cf2336ebf5c5cf92 92.51.165.126:34405] broadcast failed: use of closed network connection
panic: Saved DAG in '/tmp/dag' reports to be from future epoch 3 (current epoch is 2)
```
This is followed by a flood of text from the individual goroutines: http://tinybike.com/log/geth_4-20-2015.log.  This is on a fresh install of geth 0.9.10 on Ubuntu 14.04 (from the PPA), and has happened several times, on two different machines.

**Comment by fjl** [comment]
ethash (the library that implements the mining algorithm) is being made more robust right now. we're sorry for the inconvenience, the situation will improve (hopefully) this week.
