### ISSUE TITLE
Invalid block #120000

### ISSUE THREAD

**Issue by veox** [ethereum/go-ethereum#767]
I've been having this with `geth` for a week or so now. Updated to latest 
4ddbf81e74e90bd476c1bd8c7729581d2affe065, but issue persists. Deleting `blockchain` dir results in sync up to same block, then same failure.

```
I0421 16:14:31.517255    2553 chain_manager.go:484] INVALID block #120000 (c1f89a60)
I0421 16:14:31.517522    2553 chain_manager.go:485] Block's nonce is invalid (= 6cc84cffff07800d)
I0421 16:14:31.517828    2553 errors.go:82] [Blockpool] ERROR: Invalid block: Block's nonce is invalid (= 6cc84cffff07800d)
I0421 16:14:31.518096    2553 section.go:142] invalid block 439afc8f6f738b848981385aead63f68c669611b705b9981d6d940a873349a8d
```

**Comment by obscuren** [comment]
You need to update ethash. Make sure that you `git clone github.com/ethereum/go-ethereum` and use `godep go install`. If that still fails do a `godep restore github.com/ethereum/ethash` and build again.
