### ISSUE TITLE
Natto integration into jsre

### ISSUE THREAD

**Issue by zsfelfoldi** [ethereum/go-ethereum#772]
The event loop works with otto/jsre, but I had to remove a poll loop from ethereum.js because the event loop doesn't return while a timer is running:

RequestManager.prototype.poll = function () {
    this.timeout = setTimeout(this.poll.bind(this), c.ETH_POLLING_TIMEOUT);

We probably don't need polling when using otto provider; the proper version of ethereum.js has to be modified and included in ethereum_js.go.

**Comment by zsfelfoldi** [comment]
https://github.com/ethereum/go-ethereum/pull/771

**Comment by karalabe** [comment]
ethereum.js doesn't exist anymore. It was renamed to web3.js and contains quite a lot of fixes + updates so someone might want to play around with pulling web3.js in and dumping the old ethereum.js.

**Comment by fjl** [comment]
Implemented in #771
