### ISSUE TITLE
Invalid pointer error while mining

### ISSUE THREAD

**Issue by tinybike** [ethereum/go-ethereum#775]
I received the following error on two mining geth nodes (my laptop and server), which crashed geth in both cases:
```
*** Error in `geth': free(): invalid pointer: 0x000000c29cda6008 ***
SIGABRT: abort
PC=0x7fbbcc88fcc9
signal arrived during cgo execution
```
I posted the full log at https://gist.github.com/tinybike/0985b8ede7e350052136.

I'm running the latest geth Ubuntu build available from the PPA.  @fldrog also reported experiencing this error.  (Immediately following the error, http://eth-netstats.herokuapp.com/ reported 0 mining geth nodes -- possibly they all crashed? -- and 2 mining eth nodes.)

I restarted geth (without the miner) and it ran smoothly.  After re-building the DAG, it's running ok again with the miner on; will update this issue if this error happens again.

**Comment by fjl** [comment]
We are improving the mining algorithm so it crashes less. See #757.
