### ISSUE TITLE
RPC: implement 'latest' and 'pending' as possible blockNumber arg

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#777]
The following RPC methods need to support `earliest`,  `latest` and `pending` (internally 0, -1, -2)

* [ ] `eth_getBlockByNumber`
* [x] `eth_getUncleByBlockNumberAndIndex`
* [x] `eth_getTransactionByBlockNumberAndIndex`
* [x] `eth_getBlockTransactionCountByNumber`
* [x] `eth_getUncleCountByBlockNumber`
* [ ] RPC tests @frozeman 
* [x] RPC spec change on wiki #758

(partially?) fixes #675 with 

    eth.getBlock("pending", true).transactions

@ethers

**Comment by tgerring** [comment]
See #783 for fix to GetBlockByNumberArgs (eth_getBlockByNumber)

The other three methods already accept magic words "pending", "latest", "earliest" as demonstrated in the additional tests in the PR as far as I can tell, which is why it's important to add actual example calls and results.

**Comment by tgerring** [comment]
Just to clarify, would like @frozeman or @zelig to confirm that the following already accept magic words or provide an example to demonstrate that this is not the case:

* eth_getBlockTransactionCountByNumber
* eth_getTransactionByBlockNumberAndIndex
* eth_getUncleByBlockNumberAndIndex

**Comment by frozeman** [comment]
i will write up some test tomorrow.

**Comment by zelig** [comment]
confirmed, i tried `getBlock` only, and since was not documented i jusstwent with incorrect assumptions, apologies

**Comment by frozeman** [comment]
I marked the above functions, which i tested manually. Though with the block tests not running depending on #788  i'll have to wait to make real tests. Seems ok so far.

Ian still unsure about uncles in pending state though.

**Comment by obscuren** [comment]
Ok, closing issue
