### ISSUE TITLE
Empty account on Mac

### ISSUE THREAD

**Issue by lexansoft** [ethereum/go-ethereum#795]
I found the problem with empty account. On Mac if you open a folder in Finder, it creates a hidden file .DS_Store. For some reason geth misinterprets it as an empty key. See bellow.

I think the problem is somewhere around crypto/key_store_plain.go:122

nduserca312:~ alexn$ ls -a ~/Library/Ethereum/keys/
.						.DS_Store
..						ccd5b5c052fee58d1489104e2d18d4416bde3969

nduserca312:~ alexn$ geth account list
Welcome to the FRONTIER
Address: {}
Address: {ccd5b5c052fee58d1489104e2d18d4416bde3969}

nduserca312:~ alexn$ rm ~/Library/Ethereum/keys/.DS_Store 

nduserca312:~ alexn$ geth account list
Welcome to the FRONTIER
Address: {ccd5b5c052fee58d1489104e2d18d4416bde3969}
nduserca312:~ alexn$

**Comment by Gustav-Simonsson** [comment]
Fix: https://github.com/ethereum/go-ethereum/pull/796

**Comment by Gustav-Simonsson** [comment]
Btw, if looking into internal Ethereum directories, please use a proper tool such as http://man7.org/linux/man-pages/man1/ls.1.html instead of enterprise tools which create files in viewed directories.

**Comment by fjl** [comment]
http://arno.org/arnotify/2006/10/on-the-origins-of-ds_store/

**Comment by obscuren** [comment]
Fixed in https://github.com/ethereum/go-ethereum/pull/796
