### ISSUE TITLE
Wrong logging of tx (or worse)

### ISSUE THREAD

**Issue by lexansoft** [ethereum/go-ethereum#798]
I am sending a transaction to geth and see this in log:
39470 xeth.go:689] Tx(a746be551daf0a5e6841c97dc45fd48d061ede27efe749f970699e43e9d6abcb) to: &3ed80ae8d09f65d7f8246a34ac91f4ac756a8cdc
What is this “&” before the address? Could it cause the problem. I checked the code, it should not be there...

**Comment by fjl** [comment]
‎The & is printed because the recipient address is a pointer. You don't need to worry about it.

**Comment by tgerring** [comment]
Changing line xeth.go:689 to the following will update the formatting to 0x prepend:
```
glog.V(logger.Info).Infof("Tx(%x) to: %v\n", tx.Hash(), common.ToHex(tx.To().Bytes()))
```
Results in
```
I0423 16:39:07.034921   37158 xeth.go:689] Tx(d311ff2bf933269137d93574381438a7038edc082c1a801374cb259f6a206b2a) to: 0xf4dd5c3794f1fd0cdc0327a83aa472609c806e99
```

**Comment by obscuren** [comment]
I'm closing this issue since it's a non-issue.
