### ISSUE TITLE
update web3.js from 0.2.4 to 0.3.2

### ISSUE THREAD

**Issue by debris** [ethereum/go-ethereum#799]
geth is currently using version 0.2.4. It would be good to update it.
0.3.2 contains a bunch of [bug fixes](https://github.com/ethereum/web3.js).

**Comment by obscuren** [comment]
https://github.com/ethereum/go-ethereum/pull/800

**Comment by debris** [comment]
:+1:

**Comment by tgerring** [comment]
@debris is this issue good to close?
