### ISSUE TITLE
The pending block should return null for some properties

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#806]
Currently the pending block looks as follows:

```js
"{
  "number": 33,
  "hash": "0xddbde8715485d343640ce8cbe9d7c162a4ddce25949f289add4c2b08e4bc7e23",
  "parentHash": "0x9189026494323cd572434e5acc21b36c9304558ba23b54d4ecadd0f4967797e6",
  "nonce": "0x0000000000000000",
  "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  "stateRoot": "0x54dda68af07643f68739a6e9612ad157a26ae7e2ce81f77842bb5835fbcde583",
  "miner": "0x0000000000000000000000000000000000000000",
  "difficulty": "132480",
  "totalDifficulty": "0",
  "size": 511,
  "extraData": "0x",
  "gasLimit": 3141592,
  "gasUsed": 0,
  "timestamp": 1429872279,
  "transactions": [],
  "uncles": []
}"
```

It would be good to return `null` for the following properties, so that developers can better test against pending blocks (and also to be consistent with pending logs):

For the block:
- miner
- logsBloom
- nonce

**Comment by obscuren** [comment]
No. miner must be 20 bytes. Nonce bust be 8 bytes. logs bloom must be 512 bytes.

**Comment by frozeman** [comment]
sure, buts its not there at all, right?

according to specs, we also want logs to send null for `blockNumber`, `blockHash` as i thought that the block is not defined yet (but seems now so)

Imagine you want to test if the block you got from somewhere is a pending block. Then you would need to write:

```js
if(block.miner !== '0x0000000000000000000000000000000000000000')
    ...
// better would be
if(!block.miner)
   ...
```

**Comment by obscuren** [comment]
Indeed. An address in ethereum is exactly 20 bytes. The examples are simply wrong.

If you need to test if a block is pending you fix that in another way

```javascript
eth.watch("pending").function(block???) {
    block.pending = true
    doSomethingWithTheBlock(block);
})

function doSomethingwithTheBlock(block) {
     if( block.pending ) {
           // something
     }
}
```

**Comment by frozeman** [comment]
But what if you don't know where the block came from, means you never watched it in the first place, but you need to analyse it?

**Comment by obscuren** [comment]
> don't know where the block came from

What?

You always know where tho block comes from because you request it (or is given to you by a callback)
