### ISSUE TITLE
What is goupnp?

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/go-ethereum#809]
I'm getting the following error:

```
nat.go:94] mapping error: goupnp: SOAP request got HTTP 500 Internal Server Error
```

How can I fix this?

**Comment by tgerring** [comment]
This is related to mapping ports on your router to facilitate connectivity to other nodes. The error indicates an unsuccessful attempt and can be safely ignored.

**Comment by fjl** [comment]
Damn, I still need to fix this message.

**Comment by ajunge** [comment]
Oh. I had the same issue. Didn't know if my client is connecting or not. How can I check if it is connected?

**Comment by ajunge** [comment]
./geth console
> net

**Comment by ajunge** [comment]
> net
{
  listening: true,
  peerCount: 10
}

shows I'm connected

**Comment by obscuren** [comment]
@ajunge you're fine.

(go)unpnp is the UPnP provider for the go language. The error message is a bit confusing. The "error" you're seeing is just telling you it couldn't set up port forwarding. This can happen for several reasons:

* You don't have a router which supports UPnP
* Someone else on your network is using UPnP on that port
* Someone (including yourself) has port forwarding manually enabled

**Comment by ajunge** [comment]
Maybe it should change from an "error" to a "warning" ?

**Comment by fjl** [comment]
This is now displayed as a friendlier warning.

**Comment by ajunge** [comment]
Thanx
