### ISSUE TITLE
Problem at block 120.000

### ISSUE THREAD

**Issue by simenfd** [ethereum/go-ethereum#811]
Leaving it up to you to decide if this is a bug or not.  This message keeps repeating over and over again:

I0425 10:23:50.570805    2253 chain_manager.go:542] uncle[0](dba6c868) header invalid: Block's nonce is invalid (= 6cc84cffff07800d)
I0425 10:24:20.736839    2253 ethash.go:94] Making cache
I0425 10:24:21.983800    2253 ethash.go:99] Took: 1.246900321s
I0425 10:24:21.987494    2253 chain_manager.go:541] INVALID block #120000 (c1f89a6062fb57dcace0752cf1c20b01aefbdd18273942103e2a561b741a0211)
I0425 10:24:21.987539    2253 chain_manager.go:542] uncle[0](dba6c868) header invalid: Block's nonce is invalid (= 6cc84cffff07800d)

**Comment by obscuren** [comment]
This used to be an issue in an older version. What are you currently running (`geth version`)?

**Comment by danielnovy** [comment]
I'm having the same issue. My geth client is stuck on block #60.000. Geth Version: 0.9.11, Ubuntu 14.04, kernel 3.18.3-031803-generic. 
INVALID block #60000 (445b060791c703cb5...)
Block's nonce is invalid (= 24a1aceff...)

**Comment by bas-vk** [comment]
If you build geth from source could you try the following and report if that solves your problem:
`cd $GOPATH/src/github.com/ethereum/go-ethereum/cmd/geth`
`godep restore`
`go build && go install`

**Comment by simenfd** [comment]
I was running the bleeding edge.  The problem was solved by the 'godep restore' it seems....  I was just building without doing the restore
