### ISSUE TITLE
rpc/jeth.go provider should also implement sendAsync method

### ISSUE THREAD

**Issue by debris** [ethereum/go-ethereum#814]
Provider should also implement method `sendAsync`. As a reference you can look at [web3.js HttpProvider](https://github.com/ethereum/web3.js/blob/master/lib/web3/httpprovider.js)

Reported in issue [#184](https://github.com/ethereum/web3.js/issues/184) in web3.js repo.

**Comment by zsfelfoldi** [comment]
I'm working on this at the moment.

**Comment by zsfelfoldi** [comment]
https://github.com/ethereum/go-ethereum/pull/771 will implement this.

**Comment by zelig** [comment]
fixed in #771
