### ISSUE TITLE
p2p/discover: RLP encode/decode loses discovery-port information

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#815]
Currently the RLP encoder drops the `Node.DiscPort` field, and during decoding it injects the `TCPPort` into the `DiscPort`: https://github.com/ethereum/go-ethereum/blob/develop/p2p/discover/node.go#L125

It should be a trivial fix (Go side), but I don't know if simply refactoring `rpcNode` has outside effects too, like screwing up the discovery protocol wire format, or only touches the `udp` packet. @fjl Any input on this?

**Comment by fjl** [comment]
Not a bug. The v3 protocol doesn't carry two ports.
