### ISSUE TITLE
Add private key import to the blocktest loading

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#816]
The RPC blocktest file has now private keys for the pre-state-accounts add: https://github.com/ethereum/tests/blob/develop/BlockTests/bcRPC_API_Test.json#L1254

Please make the following changes to the importer
- import the privatekey for every account in the `pre` state, which has the privateKey property
- make sure those private keys are unlocked, so no need to unlock them before

This is important so that the RPC tests are able to send transactions and test agains the pending state.

**Comment by Gustav-Simonsson** [comment]
https://github.com/ethereum/go-ethereum/pull/818
