### ISSUE TITLE
use sensible defaults for "fromBlock/toBlock" when calling eth_newFilter and those parameters are not given.

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#823]
I asked @debris and will let you know what are the defaults in CPP.

The following would be necessary if `toBlock` or `fromBlock` is not specified in the filter options.

Though from my perspective the following makes sense to get always the latest logs, without the past ones (for getFilterChanges and getFilterLogs)

- `fromBlock`: `"latest"`
- `toBlock`: `"latest"`

If one wants to have all past ones, he can set `fromBlock: 0`.

**Comment by tgerring** [comment]
Could you revise the subject to be more specific with the actual goal, i.e. set sensible defaults for fromBlock/toBlock when calling eth_newFilter

It's not entirely clear what work needs to be done and there are no examples to demonstrate if the reader isn't clear.

**Comment by frozeman** [comment]
Actually was already specified to default `"latest"` for both:

https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter

**Comment by tgerring** [comment]
A test case for defaults is here: https://github.com/ethereum/go-ethereum/blob/764e81bf12bc45b00cec7db216e72d6396cf0c13/rpc/args_test.go#L1327-L1372

Both Earliest (fromBlock) and Latest (toBlock) are set to -1 (latest) when omitted. Is this not the expected functionality?

**Comment by frozeman** [comment]
hm, yes. I just didn't got any.
The problem was then maybe the wallet contract, which i'm working with and which is not really sending the logs its supposed to.

Could you check that your test pass fine?

**Comment by tgerring** [comment]
The tests pass on [Travis](https://travis-ci.org/ethereum/go-ethereum/builds) and locally.

**Comment by frozeman** [comment]
Nice! Thanks!
