### ISSUE TITLE
INVALID block #XXXXX (To update your chains please READ)

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#826]
#### Fix

* wait for https://github.com/ethereum/go-ethereum/pull/825 (**merged!**)
* update to latest `develop`
* run `geth console` and type `admin.debug.setHead(eth.getBlock(<INSERT NUMBER> - 1).parentHash)`

After this point it's still possible to receive `INVALID` block messages. This is not an issue. You're receiving blocks from another chain which are simply incorrect.

**Comment by simenfd** [comment]
Only updating to latest develop didn't work, but the temp fix solved it.

**Comment by jorisbontje** [comment]
Is this the same issue as:
```
I0429 11:48:57.099087   81278 chain_manager.go:537] INVALID block #199543 (3be89f562891b615a332a969c904e872fc526205d14c53cf4c3965a67621705b)
I0429 11:48:57.099111   81278 chain_manager.go:538] gas used error (91834 / 91971)
```
?

**Comment by obscuren** [comment]
It is

**Comment by obscuren** [comment]
#825 has been merged.

**Comment by tgerring** [comment]
@obscuren Is this issue sufficiently addressed to close out?

**Comment by obscuren** [comment]
Closed. There's another Uncle issue
