### ISSUE TITLE
Error in `geth': free(): invalid pointer: 0x000000c28c686008

### ISSUE THREAD

**Issue by hensleyl** [ethereum/go-ethereum#837]
This occurred while idling at the geth console.  Mining was active.  Running "ethereum-0.9.13+457SNAPSHOT20150429115414trusty"

Here's the last bit of the output from stderr:

```
rax     0x0
rbx     0x45
rcx     0xffffffffffffffff
rdx     0x6
rdi     0x3994
rsi     0x3998
rbp     0x7f995b5f1dc0
rsp     0x7f995b5f1a28
r8      0x3830303638366338
r9      0x0
r10     0x8
r11     0x202
r12     0x7f995b5f1bd0
r13     0x7
r14     0x45
r15     0x7
rip     0x7f99617e8cc9
rflags  0x202
cs      0x33
fs      0x0
gs      0x0
```

**Comment by karalabe** [comment]
That's not really helpful. Could you do paste a full dump?

**Comment by hensleyl** [comment]
What you meant by "full dump" is not clear.  I'm attaching the full stderr output for a run of "geth --mine" that exited with the exact same error.  

https://gist.github.com/hensleyl/81184175141f2b5f9e47

Let me know if you need any of the files from the .ethereum directory.

**Comment by obscuren** [comment]
We're currently reworking the ethash API and go bridge. PR is here https://github.com/ethereum/go-ethereum/pull/808. Hang in tight! :-)

**Comment by fjl** [comment]
new ethash has been merged.
