### ISSUE TITLE
p2p/discover: node database followup issues

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#838]
The node database implemented in #793 has some issues that need to be resolved:

* The database manages to pick up the local node (`Table.self`) under some conditions.  
  This should not happen. If the expiration (or the seed query) finds a node with the local ID,
  it should drop it.
* There needs to be a way to disable the seeding process from the command line.

**Comment by obscuren** [comment]
@fjl @karalabe update or close please

**Comment by karalabe** [comment]
I'll try and sort these out today.
