### ISSUE TITLE
fatal error: runtime: out of memory just after generating DAG causes complete system freeze

### ISSUE THREAD

**Issue by asdfasdfasdfasdfljkl** [ethereum/go-ethereum#844]
Hay, I am running xubuntu 14.04. 

I installed geth  0.9.14

with :

sudo add-apt-repository ppa:ethereum/ethereum-qt
sudo add-apt-repository ppa:ethereum/ethereum
sudo add-apt-repository ppa:ethereum/ethereum-dev
sudo apt-get sudo apt-get install ethereum

The problem I do 
admin.newAccount()
then enter a passphase i have used before. 

Then i do 
admin.miner.start()

This creates the DAG and then trows error fatal error: runtime: out of memory. 
 
My whole system crashes and I have to do a hard reboot. Log file below. I tried the same thing inside docker and it crashed the same way. I think other people have the same error https://www.reddit.com/r/ethereum/comments/346kgz/want_to_play_with_the_frontier_prerelease_help_me/cqszrm0

I0429 16:26:45.753031    2751 backend.go:193] Protocol Version: 60, Network Id: 0
I0429 16:26:45.753095    2751 backend.go:203] Blockchain DB Version: 2
I0429 16:26:45.754015    2751 chain_manager.go:229] Last block (#76411) fdcbb6e032aed4a3b7a990de282ae486d0dbe9f1b9e8ec1c87651f21209caf35 TD=155428025781
I0429 16:26:46.136692    2751 ethash.go:94] Making cache for epoch: 2 (76411) (510e4e770828ddbf7f7b00ab00a9f6adaf81c0dc9cc85f1f8249c256942d61d9)
I0429 16:26:47.247561    2751 ethash.go:99] Took: 1.110743461s
I0429 16:26:47.251588    2751 cmd.go:116] Starting  Geth/v0.9.12/linux/go1.4.2
I0429 16:26:47.251666    2751 server.go:187] Starting Server
I0429 16:26:47.840267    2751 nat.go:94] mapping error: no devices discovered
I0429 16:26:47.895532    2751 udp.go:157] Listening, enode://6c21430f118dbc3e98324a0a3757b08ce67d3d6661cc1c82df82b839e924bc586a3979a0d9bc06c715d02e5bc8d6c4cc02ec99813469c86d83a24efccbdd3428@92.51.228.149:30303
I0429 16:26:47.895811    2751 backend.go:403] Server started
I0429 16:26:47.895822    2751 server.go:310] Listening on [::]:30303
I0429 16:26:59.896306    2751 handler.go:167] Synchronisation attempt using a979fb575495b8d6 TD=1875192154121
I0429 16:27:22.700510    2751 ethash.go:94] Making cache for epoch: 2 (76411) (510e4e770828ddbf7f7b00ab00a9f6adaf81c0dc9cc85f1f8249c256942d61d9)
I0429 16:27:23.925413    2751 ethash.go:99] Took: 1.22461629s
I0429 16:27:23.925471    2751 ethash.go:198] Retrieving DAG
I0429 16:27:23.925501    2751 ethash.go:203] No DAG found. Generating new DAG in '/tmp/dag' (this takes a while)...
I0429 16:27:28.925711    2751 ethash.go:136] ... still generating DAG (5.00013411) ...
I0429 16:27:33.925718    2751 ethash.go:136] ... still generating DAG (10.000140806) ...
I0429 16:27:38.925693    2751 ethash.go:136] ... still generating DAG (15.000115876) ...
I0429 16:27:43.925675    2751 ethash.go:136] ... still generating DAG (20.000095336) ...
I0429 16:27:48.925675    2751 ethash.go:136] ... still generating DAG (25.000094001) ...
I0429 16:27:53.925673    2751 ethash.go:136] ... still generating DAG (30.0000957) ...
I0429 16:27:58.925709    2751 ethash.go:136] ... still generating DAG (35.000130266) ...
I0429 16:28:03.925692    2751 ethash.go:136] ... still generating DAG (40.000114266) ...
I0429 16:28:08.925723    2751 ethash.go:136] ... still generating DAG (45.00014249) ...
I0429 16:28:13.925622    2751 ethash.go:136] ... still generating DAG (50.000045783) ...
I0429 16:28:18.925671    2751 ethash.go:136] ... still generating DAG (55.000093027) ...
I0429 16:28:23.925696    2751 ethash.go:136] ... still generating DAG (60.000116505) ...
I0429 16:28:28.925695    2751 ethash.go:136] ... still generating DAG (65.000115787) ...
I0429 16:28:33.925674    2751 ethash.go:136] ... still generating DAG (70.000097079) ...
I0429 16:28:38.925694    2751 ethash.go:136] ... still generating DAG (75.000115367) ...
I0429 16:28:43.925694    2751 ethash.go:136] ... still generating DAG (80.000116089) ...
I0429 16:28:48.925675    2751 ethash.go:136] ... still generating DAG (85.000096342) ...
I0429 16:28:53.925694    2751 ethash.go:136] ... still generating DAG (90.000110219) ...
I0429 16:28:58.925686    2751 ethash.go:136] ... still generating DAG (95.000108444) ...
I0429 16:29:03.925698    2751 ethash.go:136] ... still generating DAG (100.000122835) ...
I0429 16:29:08.925687    2751 ethash.go:136] ... still generating DAG (105.000106688) ...
I0429 16:29:13.925675    2751 ethash.go:136] ... still generating DAG (110.000096119) ...
I0429 16:29:18.925696    2751 ethash.go:136] ... still generating DAG (115.000117424) ...
I0429 16:29:23.925690    2751 ethash.go:136] ... still generating DAG (120.000112787) ...
I0429 16:29:28.925697    2751 ethash.go:136] ... still generating DAG (125.000119519) ...
I0429 16:29:33.925691    2751 ethash.go:136] ... still generating DAG (130.000113262) ...
I0429 16:29:38.925689    2751 ethash.go:136] ... still generating DAG (135.000107141) ...
I0429 16:29:43.925693    2751 ethash.go:136] ... still generating DAG (140.000114845) ...
I0429 16:29:48.925712    2751 ethash.go:136] ... still generating DAG (145.000133727) ...
I0429 16:29:53.925668    2751 ethash.go:136] ... still generating DAG (150.000090742) ...
I0429 16:29:58.925670    2751 ethash.go:136] ... still generating DAG (155.000094634) ...
I0429 16:30:03.925685    2751 ethash.go:136] ... still generating DAG (160.000107282) ...
I0429 16:30:08.925693    2751 ethash.go:136] ... still generating DAG (165.000115) ...
I0429 16:30:13.925696    2751 ethash.go:136] ... still generating DAG (170.000116269) ...
I0429 16:30:18.925709    2751 ethash.go:136] ... still generating DAG (175.000129245) ...
I0429 16:30:23.925684    2751 ethash.go:136] ... still generating DAG (180.000104454) ...
I0429 16:30:28.925659    2751 ethash.go:136] ... still generating DAG (185.000082551) ...
I0429 16:30:33.925679    2751 ethash.go:136] ... still generating DAG (190.000101747) ...
I0429 16:30:38.925705    2751 ethash.go:136] ... still generating DAG (195.00012338) ...
I0429 16:30:43.925692    2751 ethash.go:136] ... still generating DAG (200.000114818) ...
I0429 16:30:48.925696    2751 ethash.go:136] ... still generating DAG (205.000117612) ...
I0429 16:30:53.925665    2751 ethash.go:136] ... still generating DAG (210.00008953) ...
I0429 16:30:58.925697    2751 ethash.go:136] ... still generating DAG (215.000117626) ...
I0429 16:31:03.925695    2751 ethash.go:136] ... still generating DAG (220.000116028) ...
I0429 16:31:08.925707    2751 ethash.go:136] ... still generating DAG (225.000125977) ...
I0429 16:31:13.925671    2751 ethash.go:136] ... still generating DAG (230.00009419) ...
I0429 16:31:18.925694    2751 ethash.go:136] ... still generating DAG (235.000115469) ...
I0429 16:31:23.925695    2751 ethash.go:136] ... still generating DAG (240.000115954) ...
I0429 16:31:24.565568    2751 chain_manager.go:537] INVALID block #76412 (3ad49695f4a7ce3a39d486f2372d7ff60a7189e80b1b38d8cb3cff264600af73)
I0429 16:31:24.565633    2751 chain_manager.go:538] Transaction w/ invalid nonce. tx=1175  state=0)
I0429 16:31:28.925682    2751 ethash.go:136] ... still generating DAG (245.000106396) ...
I0429 16:31:33.925685    2751 ethash.go:136] ... still generating DAG (250.00010726) ...
I0429 16:31:38.925684    2751 ethash.go:136] ... still generating DAG (255.000106752) ...
I0429 16:31:43.925686    2751 ethash.go:136] ... still generating DAG (260.000107366) ...
I0429 16:31:48.925686    2751 ethash.go:136] ... still generating DAG (265.000109325) ...
I0429 16:31:53.925688    2751 ethash.go:136] ... still generating DAG (270.000109165) ...
I0429 16:31:58.925686    2751 ethash.go:136] ... still generating DAG (275.000108906) ...
I0429 16:32:03.925692    2751 ethash.go:136] ... still generating DAG (280.000113372) ...
I0429 16:32:08.925687    2751 ethash.go:136] ... still generating DAG (285.000109215) ...
I0429 16:32:13.925686    2751 ethash.go:136] ... still generating DAG (290.000109406) ...
I0429 16:32:18.925689    2751 ethash.go:136] ... still generating DAG (295.000111299) ...
I0429 16:32:23.925683    2751 ethash.go:136] ... still generating DAG (300.000106708) ...
I0429 16:32:28.925693    2751 ethash.go:136] ... still generating DAG (305.000113483) ...
I0429 16:32:33.925694    2751 ethash.go:136] ... still generating DAG (310.000115236) ...
I0429 16:32:38.925684    2751 ethash.go:136] ... still generating DAG (315.000106859) ...
I0429 16:32:43.925686    2751 ethash.go:136] ... still generating DAG (320.000108884) ...
I0429 16:32:48.925685    2751 ethash.go:136] ... still generating DAG (325.000107381) ...
I0429 16:32:53.925689    2751 ethash.go:136] ... still generating DAG (330.000112156) ...
I0429 16:32:58.925682    2751 ethash.go:136] ... still generating DAG (335.000104841) ...
I0429 16:33:03.925663    2751 ethash.go:136] ... still generating DAG (340.000083404) ...
I0429 16:33:08.925671    2751 ethash.go:136] ... still generating DAG (345.000092569) ...
I0429 16:33:13.925663    2751 ethash.go:136] ... still generating DAG (350.00008322) ...
I0429 16:33:18.925669    2751 ethash.go:136] ... still generating DAG (355.000090971) ...
I0429 16:33:23.925662    2751 ethash.go:136] ... still generating DAG (360.000083779) ...
I0429 16:33:28.925688    2751 ethash.go:136] ... still generating DAG (365.000111187) ...
I0429 16:33:33.925686    2751 ethash.go:136] ... still generating DAG (370.000109268) ...
I0429 16:33:38.925685    2751 ethash.go:136] ... still generating DAG (375.00010866) ...
I0429 16:33:41.332730    2751 ethash.go:138] ... DAG generation completed ...
I0429 16:33:52.847944    2751 ethash.go:243] Took: 6m28.922434345s
I0429 16:33:53.123860    2751 worker.go:324] commit new work on block 76412 with 0 txs & 0 uncles
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0xc2798a0000, 0x100000, 0x0, 0x1365298)
	/usr/lib/go/src/runtime/mem_linux.c:149 +0x98
runtime.MHeap_SysAlloc(0x136a980, 0x100000, 0x458402)
	/usr/lib/go/src/runtime/malloc.c:284 +0x124
runtime.MHeap_Alloc(0x136a980, 0x1, 0x23c4010000000003, 0x43664e)
	/usr/lib/go/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x1371618, 0x467eb5)
	/usr/lib/go/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x7f995f932000, 0x3, 0x310)
	/usr/lib/go/src/runtime/mcache.c:90 +0xa0

goroutine 217 [running]:
runtime.switchtoM()
	/usr/lib/go/src/runtime/asm_amd64.s:198 fp=0xc20816fc38 sp=0xc20816fc30
runtime.mallocgc(0x20, 0xb6e040, 0xc200000000, 0x20)
	/usr/lib/go/src/runtime/malloc.go:178 +0x849 fp=0xc20816fce8 sp=0xc20816fc38
runtime.newobject(0xb6e040, 0xc20da0e400)
	/usr/lib/go/src/runtime/malloc.go:353 +0x49 fp=0xc20816fd10 sp=0xc20816fce8
github.com/ethereum/go-ethereum/common.Bytes2Big(0xc27989dfe0, 0x20, 0x20, 0x20)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/common/big.go:42 +0x2a fp=0xc20816fd48 sp=0xc20816fd10
github.com/ethereum/ethash.(*Ethash).Search(0xc20bd960a0, 0x7f994c32c0c8, 0xc21479e0a0, 0xc20af98000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:341 +0x4af fp=0xc20816fec0 sp=0xc20816fd48
github.com/ethereum/go-ethereum/miner.(*CpuMiner).mine(0xc20aec4a00, 0xc21479e0a0)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/miner/agent.go:88 +0x23c fp=0xc20816ffd0 sp=0xc20816fec0
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20816ffd8 sp=0xc20816ffd0
created by github.com/ethereum/go-ethereum/miner.(*CpuMiner).update
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/miner/agent.go:59 +0x133

goroutine 1 [select]:
github.com/peterh/liner.(*State).readNext(0xc20a573440, 0x0, 0x0, 0x0, 0x0)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/peterh/liner/input.go:140 +0x2a1d
github.com/peterh/liner.(*State).Prompt(0xc20a573440, 0xc2f150, 0x2, 0x0, 0x0, 0x0, 0x0)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/peterh/liner/line.go:494 +0x443
main.(*jsre).interactive(0xc20a774640)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/geth/js.go:182 +0x72
main.console(0xc2080821c0)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:301 +0x232
github.com/codegangsta/cli.Command.Run(0xc42d10, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd4ceb0, 0x30, 0xed5010, ...)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc20807c000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:177 +0xdf6
main.main()
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:273 +0x15e

goroutine 6 [select, 8 minutes]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:65 +0x6d1
created by github.com/ethereum/go-ethereum/logger.init·1
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:44 +0x25

goroutine 7 [chan receive]:
github.com/ethereum/go-ethereum/logger/glog.(*loggingT).flushDaemon(0x1359380)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:897 +0x78
created by github.com/ethereum/go-ethereum/logger/glog.init·1
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:428 +0x77

goroutine 17 [syscall, 8 minutes, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 9 [syscall, 8 minutes]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 262 [select]:
github.com/ethereum/go-ethereum/miner.(*CpuMiner).update(0xc20aec4a00)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/miner/agent.go:53 +0x1e1
created by github.com/ethereum/go-ethereum/miner.(*CpuMiner).Start
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/miner/agent.go:47 +0xed

goroutine 92 [runnable]:
net.(*conn).SetReadDeadline(0xc20ac9e0a8, 0xeccd2f157, 0x1b2a2223, 0x1358b40, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:165
github.com/ethereum/go-ethereum/p2p.(*netWrapper).ReadMsg(0xc20a54a900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/message.go:109 +0x13d
github.com/ethereum/go-ethereum/p2p.(*Peer).readLoop(0xc20b437e60, 0xc20b437f20)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/peer.go:175 +0x8a
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/p2p/peer.go:119 +0x97

goroutine 22 [select, 8 minutes]:
github.com/ethereum/go-ethereum/event/filter.(*FilterManager).filterLoop(0xc20adbf280)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/event/filter/eth_filter.go:74 +0x7e1
created by github.com/ethereum/go-ethereum/event/filter.(*FilterManager).Start
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/event/filter/eth_filter.go:31 +0x32

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc208082380)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x24c

goroutine 34 [chan receive, 8 minutes]:
github.com/ethereum/go-ethereum/logger.sysLoop(0x7f995f944ef0, 0xc2080e7f90, 0xc208158000, 0xc20800b980)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:101 +0x5a
created by github.com/ethereum/go-ethereum/logger.func·001
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:61 +0x176

goroutine 12 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc2081b0000)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x48c
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x849

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc2081b0000)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x863

goroutine 14 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc2081b0000)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:812 +0x858
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x8a7

goroutine 15 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc2081b0000)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x8c1

goroutine 16 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc2081b0000)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x8db

goroutine 50 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc208082620)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x24c

goroutine 51 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc20818e2c0)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x48c
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x849

goroutine 52 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc20818e2c0)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x863

goroutine 53 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc20818e2c0)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:812 +0x858
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x8a7

goroutine 54 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc20818e2c0)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x8c1

goroutine 55 [select, 10 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc20818e2c0)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x8db

goroutine 56 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc2080828c0)
	/build/buildd/ethereum-0.9.12+455SNAPSHOT20150428112055trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e

**Comment by obscuren** [comment]
https://github.com/ethereum/go-ethereum/issues/844
