### ISSUE TITLE
Build error on Ubuntu 15.04

### ISSUE THREAD

**Issue by drupalnomad** [ethereum/go-ethereum#849]
```
build/env.sh go install -v -ldflags '-X main.gitCommit 3fef60190384106af390dd23a65384b9cc6e4a28' ./cmd/geth
github.com/syndtr/goleveldb/leveldb/errors
# github.com/syndtr/goleveldb/leveldb/errors
build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/errors/errors.go:32: undefined: storage.FileInfo
Makefile:9: recipe for target 'geth' failed
make: *** [geth] Error 2
```

**Comment by drupalnomad** [comment]
Solution is 
    rm -rf Godeps/_workspace/pkg/

See https://gitter.im/ethereum/go-ethereum/archives/2015/04/29

**Comment by fjl** [comment]
`make clean` should also get rid of this error.

**Comment by anthony-cros** [comment]
This didn't solve the issue for me... see https://gist.github.com/anthony-cros/e9403a083a10d52e2123 (I also tried the rm -rf Godeps/_workspace/pkg/ way)

**Comment by anthony-cros** [comment]
I was informed on the gitter chat that updating go to >1.4 should take care of the problem I had with atomic.Value (see gist above)
