### ISSUE TITLE
eth_getFilterLogs returns logs in reversed order

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#855]
When you call `eth_getFilterLogs` and you get a bunch of logs back, they are ordered from the latest to the oldest one. 

They should be ordered from the oldest to the latest one though.
CPP does it and its also more logical.

In web3.js we call `eth_getFilterLogs` before polling with `eth_getFilterChanges`. So currently using go as node the order you get is for example:

- log from block 200
- log from block 150
- log from block 30
- (start now polling for new logs)
- log from block 210
- log from block 240

CPP has it the other way around and its also more logical going from oldest to newest.

**Comment by obscuren** [comment]
I consider this to be none-blocking for frontier (and also an `enhancement`)
