### ISSUE TITLE
eth_call out of gas error

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#871]
on develop 97c3735   (also exists on ac85fdc)

Made an eth_call and even though I may have an error, the message seems quite wrong, far too much gas :)

```
out of gas! require 3612280225790976582461931861288885324590164670069202199790484065153309219572500707503572111756242230030079122341283045340758458638962424178888632023, have 89108
```

```
I0506 18:56:42.525352   29362 api.go:42] eth_call [{"to":"0x2cc3640eb432574e79ed488500b102930110e4c1","data":"0xc6605beb7301b595279ece985f0c415e420e425451fcf7f684fcce087ba14d10ffec112100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000008000000000000000082ccf8f1557c5d40b21edabb18d2d691cfbf87118bac7254b39fa6c39b99683ac8f456721b270786c627ecb246700888315991877024b9839ceb25811bcf8338941f173ce5965cba608306543afd08c446e0351d2e82ca50a3355d8406df7f35feae4db17fbb7902765dea3a554e30c09f5c90735b99daa9711c5efab5d310b49be61c039e6c611d84556645f724c8f9b7a4193e0ae1b87e970737453b169e0508208fb55e20a83794905dfa655cddfa6572bdbe1c3cfcb76539cd92a2947b140b646e899d437ed604089ca58b02f9995bf2e66957521bd49b282ac2bcf2656c2a968b69b807c02e3d71252477ff9cedd3f8a16a4e30dd5ac6dd553f393d1b7694ae168e8f5efeba8db4c3b000c2d9bf5205dd19f96c08a8"},"latest"]
I0506 18:56:42.526592   29362 http.go:130] Generated response: *rpc.RpcErrorResponse &{%!s(float64=17) 2.0 %!s(*rpc.RpcErrorObject=&{-32603 out of gas! require 3612280225790976582461931861288885324590164670069202199790484065153309219572500707503572111756242230030079122341283045340758458638962424178888632023, have 89108})}
I0506 18:56:42.526673   29362 http.go:141] Sending payload: {
	"id": 17,
	"jsonrpc": "2.0",
	"error": {
		"code": -32603,
		"message": "out of gas! require 3612280225790976582461931861288885324590164670069202199790484065153309219572500707503572111756242230030079122341283045340758458638962424178888632023, have 89108"
	}
}
```

**Comment by obscuren** [comment]
This is not an issue. It actually goes OOG.

Observe: (you can do this too with `--vmdebug`)
```
I0507 19:31:34.172447   27990 vm.go:898] (pc) 3911 -o- PUSH1          (m) 6016 (s) 5    (g) 3   (89130) => 0x20
I0507 19:31:34.172468   27990 vm.go:898] (pc) 3913 -o- ADD            (m) 6016 (s) 6    (g) 3   (89127) 43518676163453082806895263226915120380703664781237217333174797439826703557664 + 32 = 43518676163453082806895263226915120380703664781237217333174797439826703557696
I0507 19:31:34.172486   27990 vm.go:898] (pc) 3914 -o- MSIZE          (m) 6016 (s) 5    (g) 2   (89124)
I0507 19:31:34.172503   27990 vm.go:898] (pc) 3915 -o- SWAP1          (m) 6016 (s) 6    (g) 3   (89122) => [2]
I0507 19:31:34.172515   27990 vm.go:898] (pc) 3916 -o- MSIZE          (m) 6016 (s) 6    (g) 2   (89119)
I0507 19:31:34.172531   27990 vm.go:898] (pc) 3917 -o- ADD            (m) 6016 (s) 7    (g) 3   (89117) 43518676163453082806895263226915120380703664781237217333174797439826703557696 + 6016 = 43518676163453082806895263226915120380703664781237217333174797439826703563712
I0507 19:31:34.172549   27990 vm.go:898] (pc) 3918 -o- PUSH1          (m) 6016 (s) 6    (g) 3   (89114) => 0x00
I0507 19:31:34.172566   27990 vm.go:898] (pc) 3920 -o- SWAP1          (m) 6016 (s) 7    (g) 3   (89111) => [2]
I0507 19:31:34.172591   27990 vm.go:898] (pc) 3921 -o- MSTORE         (m) 6016 (s) 7    (g) 3612280225790976582461931861288885324590164670069202199790484065153309219572500707503572111756242230030079122341283045340758458638962424178888632023 (89108)
I0507 19:31:34.172610   27990 vm.go:898]  out of gas! require 3612280225790976582461931861288885324590164670069202199790484065153309219572500707503572111756242230030079122341283045340758458638962424178888632023, have 89108
```

Pay close attention to the `ADD`

**Comment by ethers** [comment]
The OOG will be resolved via https://github.com/ethereum/web3.js/issues/194

The prior ABI data that web3.js was sending and was not oog was:
0xc6605beb00000000000000000000000000000000000000000000000000000000000000087301b595279ece985f0c415e420e425451fcf7f684fcce087ba14d10ffec11210000000000000000000000000000000000000000000000000000000000000001000000000000000082ccf8f1557c5d40b21edabb18d2d691cfbf87118bac7254b39fa6c39b99683ac8f456721b270786c627ecb246700888315991877024b9839ceb25811bcf8338941f173ce5965cba608306543afd08c446e0351d2e82ca50a3355d8406df7f35feae4db17fbb7902765dea3a554e30c09f5c90735b99daa9711c5efab5d310b49be61c039e6c611d84556645f724c8f9b7a4193e0ae1b87e970737453b169e0508208fb55e20a83794905dfa655cddfa6572bdbe1c3cfcb76539cd92a2947b140b646e899d437ed604089ca58b02f9995bf2e66957521bd49b282ac2bcf2656c2a968b69b807c02e3d71252477ff9cedd3f8a16a4e30dd5ac6dd553f393d1b7694ae168e8f5efeba8db4c3b000c2d9bf5205dd19f96c08a8

Current ABI data being sent that leads to OOG is:
0xc6605beb7301b595279ece985f0c415e420e425451fcf7f684fcce087ba14d10ffec112100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000008000000000000000082ccf8f1557c5d40b21edabb18d2d691cfbf87118bac7254b39fa6c39b99683ac8f456721b270786c627ecb246700888315991877024b9839ceb25811bcf8338941f173ce5965cba608306543afd08c446e0351d2e82ca50a3355d8406df7f35feae4db17fbb7902765dea3a554e30c09f5c90735b99daa9711c5efab5d310b49be61c039e6c611d84556645f724c8f9b7a4193e0ae1b87e970737453b169e0508208fb55e20a83794905dfa655cddfa6572bdbe1c3cfcb76539cd92a2947b140b646e899d437ed604089ca58b02f9995bf2e66957521bd49b282ac2bcf2656c2a968b69b807c02e3d71252477ff9cedd3f8a16a4e30dd5ac6dd553f393d1b7694ae168e8f5efeba8db4c3b000c2d9bf5205dd19f96c08a8
