### ISSUE TITLE
eth_getBlockByNumber does not have size and totalDifficulty

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#879]
develop ac85fdc

From the long link at #878 
Geth eth_getBlockByNumber is not returning the size and totalDifficulty in its json result object.

Here's the long link for completeness:
http://tlrobinson.net/projects/javascript-fun/jsondiff/#%7B%22d%22%3A%7B%22a%22%3A%22%7B%5Cn%20%20%5C%22result%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22uncles%5C%22%3A%20%5B%5Cn%20%20%20%20%20%20%5C%220x03a23f145adc361a1cb5c91f1904e8577aa92952993524473000af5de9ad966d%5C%22%5Cn%20%20%20%20%5D%2C%5Cn%20%20%20%20%5C%22transactions%5C%22%3A%20%5B%5Cn%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20%5C%22input%5C%22%3A%20%5C%220x8f6b104c00000000000000000000000000000000000000000000000000000000000002067301b595279ece985f0c415e420e425451fcf7f684fcce087ba14d10ffec112100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000008000000000000000082ccf8f1557c5d40b21edabb18d2d691cfbf87118bac72540000000000000000000000000a6d622f333d9c3b9c9a5c34e3de554d76ce40613031303030303030303134646666343035306463656531363637326534386437353563366464323564333234343932623565613330366638356133616232336234646632366531366539303030303030303038633439333034363032323130306362366463393131656630626165306162306536323635613435663235653038316663376561343937353531376339663834386638326263326238306139303930323231303065333066623662623466623634663431346333353165643361626165643734393162386630623162396263643735323836303336646638626661626333656135303134313034623730353734303036343235623631383637643263626238646537633236303935666263303062613430343162303631636637356238353639396362326234343963363735383734316636343061646666613335363430363633323631306566623236376362316566613034343263323037303539646437666436353265656166666666666666663032303034396439373130323030303030303139373661393134363163663561663762623834333438646633666436393536373265353363376435623366336462393838616333303630316330633036303030303030313937366139313466643465643131346566383564333530643664343065643366366463323337343366386639396334383861633030303030303030b39fa6c39b99683ac8f456721b270786c627ecb246700888315991877024b9839ceb25811bcf8338941f173ce5965cba608306543afd08c446e0351d2e82ca50a3355d8406df7f35feae4db17fbb7902765dea3a554e30c09f5c90735b99daa9711c5efab5d310b49be61c039e6c611d84556645f724c8f9b7a4193e0ae1b87e970737453b169e0508208fb55e20a83794905dfa655cddfa6572bdbe1c3cfcb76539cd92a2947b140b646e899d437ed604089ca58b02f9995bf2e66957521bd49b282ac2bcf2656c2a968b69b807c02e3d71252477ff9cedd3f8a16a4e30dd5ac6dd553f393d1b7694ae168e8f5efeba8db4c3b000c2d9bf5205dd19f96c08a8%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22gasPrice%5C%22%3A%20%5C%220x9184e72a000%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22gas%5C%22%3A%20%5C%220x2dc6b6%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22hash%5C%22%3A%20%5C%220xe9e181276fdb6c09da5398fc9ceedd095c95bc0b73df556be3031e3bb203fa64%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22nonce%5C%22%3A%20%5C%220x16a5%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22blockHash%5C%22%3A%20%5C%220xced8c6e7d2e4d2e7577b0100892b3d999f4cb91f655d6b661f7ca9ece927f236%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22blockNumber%5C%22%3A%20%5C%220x42f68%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22transactionIndex%5C%22%3A%20%5C%220x0%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22from%5C%22%3A%20%5C%220xcd2a3d9f938e13cd947ec05abc7fe734df8dd826%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22to%5C%22%3A%20%5C%220xb61662398570293e4f0d25525e2b3002b7fe0836%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22value%5C%22%3A%20%5C%220x0%5C%22%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%5D%2C%5Cn%20%20%20%20%5C%22stateRoot%5C%22%3A%20%5C%220x79655272697b71859b7f62f05e2fdd308accf8c49b8fb8424c6aacde00651ff0%5C%22%2C%5Cn%20%20%20%20%5C%22transactionsRoot%5C%22%3A%20%5C%220x351e1c50613983d0b228729841e93c74fc5c89318d200fd05cb06b6b828fa4d1%5C%22%2C%5Cn%20%20%20%20%5C%22logsBloom%5C%22%3A%20%5C%220x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000%5C%22%2C%5Cn%20%20%20%20%5C%22sha3Uncles%5C%22%3A%20%5C%220xd00e5aab030abc498fd50962c3d05de8e3712daffb76d17c4f1935023248e02d%5C%22%2C%5Cn%20%20%20%20%5C%22nonce%5C%22%3A%20%5C%220x000000000eb9d453%5C%22%2C%5Cn%20%20%20%20%5C%22parentHash%5C%22%3A%20%5C%220xfd36a3477cd73dcaf13196352cfc0c409628312a127ab346c2117a836e280d2c%5C%22%2C%5Cn%20%20%20%20%5C%22hash%5C%22%3A%20%5C%220xced8c6e7d2e4d2e7577b0100892b3d999f4cb91f655d6b661f7ca9ece927f236%5C%22%2C%5Cn%20%20%20%20%5C%22number%5C%22%3A%20%5C%220x42f68%5C%22%2C%5Cn%20%20%20%20%5C%22miner%5C%22%3A%20%5C%220x5690aa8347b53382237c2c37db1158a80c9483d5%5C%22%2C%5Cn%20%20%20%20%5C%22difficulty%5C%22%3A%20%5C%220x1a1b95e8%5C%22%2C%5Cn%20%20%20%20%5C%22totalDifficulty%5C%22%3A%20%5C%220x96f9b6d74c1%5C%22%2C%5Cn%20%20%20%20%5C%22size%5C%22%3A%20%5C%220x83f%5C%22%2C%5Cn%20%20%20%20%5C%22extraData%5C%22%3A%20%5C%220x%5C%22%2C%5Cn%20%20%20%20%5C%22gasLimit%5C%22%3A%20%5C%220x2fefd8%5C%22%2C%5Cn%20%20%20%20%5C%22gasUsed%5C%22%3A%20%5C%220x2dc6b6%5C%22%2C%5Cn%20%20%20%20%5C%22timestamp%5C%22%3A%20%5C%220x554be4c6%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22jsonrpc%5C%22%3A%20%5C%222.0%5C%22%2C%5Cn%20%20%5C%22id%5C%22%3A%201%5Cn%7D%5Cn%22%2C%22b%22%3A%22%7B%5Cn%20%20%5C%22result%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22uncles%5C%22%3A%20%5B%5Cn%20%20%20%20%20%20%5C%220x03a23f145adc361a1cb5c91f1904e8577aa92952993524473000af5de9ad966d%5C%22%5Cn%20%20%20%20%5D%2C%5Cn%20%20%20%20%5C%22transactionsRoot%5C%22%3A%20%5C%220x351e1c50613983d0b228729841e93c74fc5c89318d200fd05cb06b6b828fa4d1%5C%22%2C%5Cn%20%20%20%20%5C%22transactions%5C%22%3A%20%5B%5Cn%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20%5C%22value%5C%22%3A%20%5C%220x0%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22transactionIndex%5C%22%3A%20%5C%220x0%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22to%5C%22%3A%20%5C%220xb61662398570293e4f0d25525e2b3002b7fe0836%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22blockHash%5C%22%3A%20%5C%220xced8c6e7d2e4d2e7577b0100892b3d999f4cb91f655d6b661f7ca9ece927f236%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22blockNumber%5C%22%3A%20%5C%220x42f68%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22from%5C%22%3A%20%5C%220xcd2a3d9f938e13cd947ec05abc7fe734df8dd826%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22gas%5C%22%3A%20%5C%220x2dc6b6%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22gasPrice%5C%22%3A%20%5C%220x9184e72a000%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22hash%5C%22%3A%20%5C%220x427f8ade19056f47473b254ba2767b595b1987d3bb4ccb51410efeaa8a530978%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22input%5C%22%3A%20%5C%220x8f6b104c00000000000000000000000000000000000000000000000000000000000002067301b595279ece985f0c415e420e425451fcf7f684fcce087ba14d10ffec112100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000008000000000000000082ccf8f1557c5d40b21edabb18d2d691cfbf87118bac72540000000000000000000000000a6d622f333d9c3b9c9a5c34e3de554d76ce40613031303030303030303134646666343035306463656531363637326534386437353563366464323564333234343932623565613330366638356133616232336234646632366531366539303030303030303038633439333034363032323130306362366463393131656630626165306162306536323635613435663235653038316663376561343937353531376339663834386638326263326238306139303930323231303065333066623662623466623634663431346333353165643361626165643734393162386630623162396263643735323836303336646638626661626333656135303134313034623730353734303036343235623631383637643263626238646537633236303935666263303062613430343162303631636637356238353639396362326234343963363735383734316636343061646666613335363430363633323631306566623236376362316566613034343263323037303539646437666436353265656166666666666666663032303034396439373130323030303030303139373661393134363163663561663762623834333438646633666436393536373265353363376435623366336462393838616333303630316330633036303030303030313937366139313466643465643131346566383564333530643664343065643366366463323337343366386639396334383861633030303030303030b39fa6c39b99683ac8f456721b270786c627ecb246700888315991877024b9839ceb25811bcf8338941f173ce5965cba608306543afd08c446e0351d2e82ca50a3355d8406df7f35feae4db17fbb7902765dea3a554e30c09f5c90735b99daa9711c5efab5d310b49be61c039e6c611d84556645f724c8f9b7a4193e0ae1b87e970737453b169e0508208fb55e20a83794905dfa655cddfa6572bdbe1c3cfcb76539cd92a2947b140b646e899d437ed604089ca58b02f9995bf2e66957521bd49b282ac2bcf2656c2a968b69b807c02e3d71252477ff9cedd3f8a16a4e30dd5ac6dd553f393d1b7694ae168e8f5efeba8db4c3b000c2d9bf5205dd19f96c08a8%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22nonce%5C%22%3A%20%5C%220x16a5%5C%22%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%5D%2C%5Cn%20%20%20%20%5C%22timestamp%5C%22%3A%20%5C%220x554be4c6%5C%22%2C%5Cn%20%20%20%20%5C%22stateRoot%5C%22%3A%20%5C%220x79655272697b71859b7f62f05e2fdd308accf8c49b8fb8424c6aacde00651ff0%5C%22%2C%5Cn%20%20%20%20%5C%22sha3Uncles%5C%22%3A%20%5C%220xd00e5aab030abc498fd50962c3d05de8e3712daffb76d17c4f1935023248e02d%5C%22%2C%5Cn%20%20%20%20%5C%22parentHash%5C%22%3A%20%5C%220xfd36a3477cd73dcaf13196352cfc0c409628312a127ab346c2117a836e280d2c%5C%22%2C%5Cn%20%20%20%20%5C%22number%5C%22%3A%20%5C%220x42f68%5C%22%2C%5Cn%20%20%20%20%5C%22difficulty%5C%22%3A%20%5C%220x1a1b95e8%5C%22%2C%5Cn%20%20%20%20%5C%22extraData%5C%22%3A%20%5C%220x%5C%22%2C%5Cn%20%20%20%20%5C%22gasLimit%5C%22%3A%20%5C%220x2fefd8%5C%22%2C%5Cn%20%20%20%20%5C%22gasUsed%5C%22%3A%20%5C%220x2dc6b6%5C%22%2C%5Cn%20%20%20%20%5C%22hash%5C%22%3A%20%5C%220xced8c6e7d2e4d2e7577b0100892b3d999f4cb91f655d6b661f7ca9ece927f236%5C%22%2C%5Cn%20%20%20%20%5C%22logsBloom%5C%22%3A%20%5C%220x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000%5C%22%2C%5Cn%20%20%20%20%5C%22miner%5C%22%3A%20%5C%220x5690aa8347b53382237c2c37db1158a80c9483d5%5C%22%2C%5Cn%20%20%20%20%5C%22nonce%5C%22%3A%20%5C%220x000000000eb9d453%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22jsonrpc%5C%22%3A%20%5C%222.0%5C%22%2C%5Cn%20%20%5C%22id%5C%22%3A%201%5Cn%7D%5Cn%22%7D%7D

**Comment by tgerring** [comment]
I believe this is no longer an issue? Can you confirm @ethers?

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x42f68",true],"id":1}' http://127.0.01:8545
```


```
{
	"id": 1,
	"jsonrpc": "2.0",
	"result": {
		"number": "0x42f68",
		"hash": "0xced8c6e7d2e4d2e7577b0100892b3d999f4cb91f655d6b661f7ca9ece927f236",
		"parentHash": "0xfd36a3477cd73dcaf13196352cfc0c409628312a127ab346c2117a836e280d2c",
		"nonce": "0x000000000eb9d453",
		"sha3Uncles": "0xd00e5aab030abc498fd50962c3d05de8e3712daffb76d17c4f1935023248e02d",
		"logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
		"transactionsRoot": "0x351e1c50613983d0b228729841e93c74fc5c89318d200fd05cb06b6b828fa4d1",
		"stateRoot": "0x79655272697b71859b7f62f05e2fdd308accf8c49b8fb8424c6aacde00651ff0",
		"miner": "0x5690aa8347b53382237c2c37db1158a80c9483d5",
		"difficulty": "0x1a1b95e8",
		"totalDifficulty": "0x96f9b6d74c1",
		"size": "0x83f",
		"extraData": "0x",
		"gasLimit": "0x2fefd8",
		"gasUsed": "0x2dc6b6",
		"timestamp": "0x554be4c6",
		"transactions": [
			{
				"hash": "0xe9e181276fdb6c09da5398fc9ceedd095c95bc0b73df556be3031e3bb203fa64",
				"nonce": "0x16a5",
				"blockHash": "0xced8c6e7d2e4d2e7577b0100892b3d999f4cb91f655d6b661f7ca9ece927f236",
				"blockNumber": "0x42f68",
				"transactionIndex": "0x0",
				"from": "0xcd2a3d9f938e13cd947ec05abc7fe734df8dd826",
				"to": "0xb61662398570293e4f0d25525e2b3002b7fe0836",
				"value": "0x0",
				"gas": "0x2dc6b6",
				"gasPrice": "0x9184e72a000",
				"input": "0x8f6b104c00000000000000000000000000000000000000000000000000000000000002067301b595279ece985f0c415e420e425451fcf7f684fcce087ba14d10ffec112100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000008000000000000000082ccf8f1557c5d40b21edabb18d2d691cfbf87118bac72540000000000000000000000000a6d622f333d9c3b9c9a5c34e3de554d76ce40613031303030303030303134646666343035306463656531363637326534386437353563366464323564333234343932623565613330366638356133616232336234646632366531366539303030303030303038633439333034363032323130306362366463393131656630626165306162306536323635613435663235653038316663376561343937353531376339663834386638326263326238306139303930323231303065333066623662623466623634663431346333353165643361626165643734393162386630623162396263643735323836303336646638626661626333656135303134313034623730353734303036343235623631383637643263626238646537633236303935666263303062613430343162303631636637356238353639396362326234343963363735383734316636343061646666613335363430363633323631306566623236376362316566613034343263323037303539646437666436353265656166666666666666663032303034396439373130323030303030303139373661393134363163663561663762623834333438646633666436393536373265353363376435623366336462393838616333303630316330633036303030303030313937366139313466643465643131346566383564333530643664343065643366366463323337343366386639396334383861633030303030303030b39fa6c39b99683ac8f456721b270786c627ecb246700888315991877024b9839ceb25811bcf8338941f173ce5965cba608306543afd08c446e0351d2e82ca50a3355d8406df7f35feae4db17fbb7902765dea3a554e30c09f5c90735b99daa9711c5efab5d310b49be61c039e6c611d84556645f724c8f9b7a4193e0ae1b87e970737453b169e0508208fb55e20a83794905dfa655cddfa6572bdbe1c3cfcb76539cd92a2947b140b646e899d437ed604089ca58b02f9995bf2e66957521bd49b282ac2bcf2656c2a968b69b807c02e3d71252477ff9cedd3f8a16a4e30dd5ac6dd553f393d1b7694ae168e8f5efeba8db4c3b000c2d9bf5205dd19f96c08a8"
			}
		],
		"uncles": [
			"0x03a23f145adc361a1cb5c91f1904e8577aa92952993524473000af5de9ad966d"
		]
	}
}
```

**Comment by ethers** [comment]
Geth good thanks
