### ISSUE TITLE
Accept error: accept tcp 127.0.0.1:8545: too many open files

### ISSUE THREAD

**Issue by scottzer0** [ethereum/go-ethereum#880]
I'm getting this error in the geth output when doing a series of RPC calls from my html5 client:

```2015/05/07 19:18:38 http: Accept error: accept tcp 127.0.0.1:8545: too many open files; retrying in 1s```

It's not consistent and I can usually resolve and successfully make rpc calls again after i stop/start geth.

**Comment by joeykrug** [comment]
I'm also getting a similar error, not when making RPC calls, but simply when downloading blocks after my chain's been out of sync for a while:

```I0507 20:48:11.272114   36411 chain_manager.go:559] INVALID block #266388 (f7a927e59ad6f3f3c436490ca8e4b89a26797f9abfb1ac7b73f63fcd5efed702)
I0507 20:48:11.272143   36411 chain_manager.go:560] gas used error (193580 / 218580)
I0507 20:48:31.335462   36411 backend.go:462] error: flush blockDb: open /Users/joeykrug2/Library/Ethereum/blockchain/001693.log: too many open files```

**Comment by arhuaco** [comment]
I just got this issue.

When I quit the console printed this:
unable to open history file: open /home/len/.ethereum/history: too many open files

This is how it started (in the log): http://pastebin.com/uwePfQQ1

If there are some desirable debug options that help, please let me know.

**Comment by obscuren** [comment]
A fix is incoming for the too many files open.
