### ISSUE TITLE
Use libsecp256k1 for scalar mult in ECDH in ECIES

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#883]
Profiling of a running Go node shows that we spend a significant amount of CPU time in the EC scalar multiplication used when deriving the shared secret in ECDH in ECIES for the encrypted handshake: https://github.com/ethereum/devp2p/blob/master/rlpx.md#encrypted-handshake

The idea is that we should be able to replace the Go code for this multiplication with libsecp256k1 which is highly optimized for this operations.

See: https://github.com/ethereum/go-ethereum/blob/develop/crypto/curve.go#L182
And: https://github.com/bitcoin/secp256k1/blob/master/src/ecmult.h

First attempt at integrating this: https://github.com/Gustav-Simonsson/go-ethereum/tree/scalar_mult

Why the result is different for the same input is unknown - could be we're using the library wrong somehow.

**Comment by Gustav-Simonsson** [comment]
There is now a PR which adds ECDH at the API level: https://github.com/bitcoin/secp256k1/pull/252  Once it's merged we should be able to use it for ECDH in ECIES.

**Comment by obscuren** [comment]
Sure. Let's integrate that post frontier

**Comment by fjl** [comment]
This is now done on develop.
