### ISSUE TITLE
Return null for some properties in pending logs and transactions and blocks

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#884]
The following properties, should return with `null`:
- `blockHash` (Log, Transaction)
- `blockNumber` (Log, Transaction)
- `transactionIndex` (Log, Transaction)
- `logIndex` (Log)
- `hash` (Block)
- `number` (Block)
- `logsBloom` (Block)
- `miner` (Block)
- `nonce` (Block)

when retrieving _pending_ **transactions**, **logs** or **blocks** through:
- `eth_getBlockByNumber` (when using parameter `["pending"]`)
- `eth_getTransactionByHash`
- `eth_getFilterChanges` (created with `eth_newFilter` and `eth_newPendingTransactionFilter`)
- `eth_getFilterLogs` (created with `eth_newFilter` and `eth_newPendingTransactionFilter`)

**Comment by frozeman** [comment]
To be discussed: wether pending blocks should also return `null` for `hash` and `number`, as the hash depends on the nonce, which is unclear (?) at the time.

**Comment by tgerring** [comment]
Can you add some extra information to clarify when this should happen? An example response of when and when not the results should be null would be helpful.

**Comment by frozeman** [comment]
Actually the above should be clear:

..when retrieving pending transactions, logs or blocks. So example request could be:

- eth_getBlockByNumber (when using parameter ["pending"])
```
{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["pending",false],"id":3}
```

- eth_getTransactionByHash (provide a hash of a pending transaction, e.g. create one immedieately before with sendTransaction)
```
{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from":"0x1233","to":"0x1234","value":"0xb"}],"id":5}

{jsonrpc: "2.0", method: "eth_getTransactionByHash", params: ["0x1234"], id: 6}
```

- eth_getFilterChanges (created with eth_newFilter and eth_newPendingTransactionFilter)
```
{jsonrpc: "2.0", method: "eth_newPendingTransactionFilter", params: [], id: 6}
{"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x0"],"id":10}

// or
{"jsonrpc":"2.0","method":"eth_newFilter","params":[{"topics":[],"fromBlock":"0x0","toBlock":"pending"}],"id":87}
{"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x1"],"id":10}
```
- eth_getFilterLogs (created with eth_newPendingTransactionFilter) (not sure, if that should work, as pending transactions are always recent, its currently undefined)


For the above you obviously need to fill in the correct return values in the following calls.

**Comment by tgerring** [comment]
Hi Fabian,

Thanks for the call examples, but I was looking for some responses. ("An example response of when and when not the results should be null would be helpful.")

What values are currently being returned when you expect null?

**Comment by frozeman** [comment]
The following are the values right now when pending, which should be `null`, when the tx, log or block is pending

- blockHash: '0x00000000...'
- blockNumber: 0
- transactionIndex: 0
- logIndex: 0
- hash: '0x0000...'
- number: 0
- logsBloom: '0x0000...'
- miner: '0x0000...'
- nonce: '0x0000...'

**Comment by frozeman** [comment]
e.g. a pending block:

```js
{
  "number": 344042,
  "hash": "0x8aa91e68e87aa06abc63d226a927f22316b317d36148b79194d348912de74a13",
  "parentHash": "0xc47b17681624f6884ba1268276a8a08477cbcff9c1be230d3190ff6854d8cace",
  "nonce": "0x0000000000000000",
  "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  "stateRoot": "0x39bee47c6e922fe5f9a3c90a2e2881d5048b45c2ec1b72889fe6334c3b3dcea4",
  "miner": "0x0000000000000000000000000000000000000000",
  "difficulty": "3163036277",
  "totalDifficulty": "0",
  "size": 515,
  "extraData": "0x",
  "gasLimit": 3141592,
  "gasUsed": 0,
  "timestamp": 1431701647,
  "transactions": [],
  "uncles": []
}
```

**Comment by tgerring** [comment]
Here's sample output for eth_getBlockByNumber:

```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["pending",false],"id":3}' http://127.0.0.1:8545
{
	"id": 3,
	"jsonrpc": "2.0",
	"result": {
		"number": null,
		"hash": null,
		"parentHash": "0x18e7adb0ad9d0f18a797548c842014e85d3221c001dd896ca7a2abefc7c4e267",
		"nonce": null,
		"sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
		"logsBloom": null,
		"transactionsRoot": "0x9a9c760d0f5d608da7e5c080d3aacad87127ad07cda397d6943bd95e1c959b28",
		"stateRoot": "0xafeb6b7ee731a6e970a4fe310c71b200feeb9ee1952c0107b52c17a2c98fdcbf",
		"miner": null,
		"difficulty": "0x1c6989659",
		"totalDifficulty": "0x0",
		"size": "0x2dd",
		"extraData": "0x",
		"gasLimit": "0x2fefd8",
		"gasUsed": "0x0",
		"timestamp": "0x5559f3b4",
		"transactions": [
			"0x3703b554cf1c75444a6044de1ffef6e0bad32d1d6a16f3295081914f7a992fe8",
			"0x582797dbb43699e442a5cf8865677424dc46cee5969d595fc251fbd3fdb62ea8"
		],
		"uncles": []
	}
}
```

I think the other need some more discussion or clarification. For example, `eth_newPendingTransactionFilter` triggers a list of transaction hashes to be returned, so I don't see how anything can be nulled here when requesting the results through `eth_getFilterChanges`. Am I misunderstanding?

**Comment by frozeman** [comment]
looks good.

You right `eth_newPendingTransactionFilter ` don't make sense, it should only be `eth_getTransactionByHash ` if its a pending transaction. But for logs it still makes sense, if they are produced even in pending states

**Comment by tgerring** [comment]
So again, can you please clarify when and what needs to be null? This is my current best guess:

* eth_getBlockByNumber when param "pending"
  * block hash
  * block number
  * miner address
  * nonce
  * logs bloom
* eth_getTransactionByHash when transaction is in the transaction pool, not a block
  * block hash
  * block number
  * tx index
* eth_getFilterChanges/eth_getFilterLogs when filter is created by eth_newFilter (a log filter) and ???? are there certain params that matter?
  * log index
  * tx index
  * block hash
  * block number

**Comment by frozeman** [comment]
You're very correct. i listed those already in a comment above, but your list looks way nicer ;)

The `eth_getFilterChanges/eth_getFilterLogs` only when specifying a new filter with option `toBlock: 'pending'` and the log returned is a pending log.

I am not sure if one specifies  `toBlock: 'pending'`, whether it should return logs twice, once generated in pending state and once when minded. I would think only logs generated in pending state should be returned. `getFilterLogs`, should still return you previous logs (including currently pending logs (is that possible ?)).

Logs get the null fields only when generated in pending state, not when mined already.

**Comment by tgerring** [comment]
`eth_getTransactionByHash` output when pending:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from":"0xd1ade25ccd3d550a7eb532ac759cac7be09c2719","t":"0xe470b1a7d2c9c5c6f03bbaa8fa20db6d404a0c32","value":"0xcc0290"}],"id":5}' http://127.0.0.1:8545
{
	"id": 5,
	"jsonrpc": "2.0",
	"result": "0xd62fb64dbd7e2c509d03908b258c2590919ebca39da3d9b31807011f9198d97e"
}
$ curl -X POST --data '{"jsonrpc": "2.0", "method": "eth_getTransactionByHash", "params": ["0xd62fb64dbd7e2c509d03908b258c2590919ebca39d3d9b31807011f9198d97e"], "id": 6}' http://127.0.0.1:8545
{
	"id": 6,
	"jsonrpc": "2.0",
	"result": {
		"hash": "0xd62fb64dbd7e2c509d03908b258c2590919ebca39da3d9b31807011f9198d97e",
		"nonce": "0xd",
		"blockHash": null,
		"blockNumber": null,
		"transactionIndex": null,
		"from": "0xd1ade25ccd3d550a7eb532ac759cac7be09c2719",
		"to": "0xe470b1a7d2c9c5c6f03bbaa8fa20db6d404a0c32",
		"value": "0xcc0290",
		"gas": "0x15f90",
		"gasPrice": "0x9184e72a000",
		"input": "0x"
	}
}
```

After mined:
```
$ curl -X POST --data '{"jsonrpc": "2.0", "method": "eth_getTransactionByHash", "params": ["0xd62fb64dbd7e2c509d03908b258c2590919ebca39d3d9b31807011f9198d97e"], "id": 6}' http://127.0.0.1:8545
{
	"id": 6,
	"jsonrpc": "2.0",
	"result": {
		"hash": "0xd62fb64dbd7e2c509d03908b258c2590919ebca39da3d9b31807011f9198d97e",
		"nonce": "0xd",
		"blockHash": "0x59c7ab2177d23ef5e276398ec368f2f1e33498d808279b6d92369f08ac7c2738",
		"blockNumber": "0x5b8ce",
		"transactionIndex": "0x0",
		"from": "0xd1ade25ccd3d550a7eb532ac759cac7be09c2719",
		"to": "0xe470b1a7d2c9c5c6f03bbaa8fa20db6d404a0c32",
		"value": "0xcc0290",
		"gas": "0x15f90",
		"gasPrice": "0x9184e72a000",
		"input": "0x"
	}
}
```

**Comment by frozeman** [comment]
:+1:

**Comment by frozeman** [comment]
additional `to` can be `null` if its a contract creation transaction

**Comment by tgerring** [comment]
@frozeman Can you provide a sample output of the filter logs as they currently exist and an example of how they should output when toBlock is `pending`?

**Comment by frozeman** [comment]
i can't as it depends on #852 and #851

**Comment by tgerring** [comment]
Changes tracked in branch at https://github.com/tgerring/go-ethereum/tree/issue884

@obscuren This issue is blocked. Have you had a chance to look into the pending logs?

**Comment by tgerring** [comment]
#1036 merged addresses `eth_getBlockByNumber` and `eth_getTransactionByHash` but will require an additional PR to address the filter calls

**Comment by frozeman** [comment]
Just checked with the latest develop:

In pending blocks `number` i still `0` (which would refer to the genesis block).

As well as pending transactions, which come in blocks (e.g. using `{jsonrpc: "2.0", method: "eth_getBlockByNumber", params: ["pending", true], id: 45}` or `{jsonrpc: "2.0", method: "eth_getTransactionByHash", params: ["0x124.."], id: 46}`) have `blockNumber`, `blockHash` and `transactionIndex` set, instead of being `null`.

**Comment by frozeman** [comment]
Was this addressed?

**Comment by fjl** [comment]
Don't know. But it's really old and nobody looks these issues.

**Comment by frozeman** [comment]
That doesn't make them go away ;) I would like to keep it open, as its important.

**Comment by fjl** [comment]
What is still to do here?

**Comment by frozeman** [comment]
"In pending blocks number i still 0 (which would refer to the genesis block).

As well as pending transactions, which come in blocks (e.g. using {jsonrpc: "2.0", method: "eth_getBlockByNumber", params: ["pending", true], id: 45} or {jsonrpc: "2.0", method: "eth_getTransactionByHash", params: ["0x124.."], id: 46}) have blockNumber, blockHash and transactionIndex set, instead of being null."

**Comment by frozeman** [comment]
So the output for `eth_blockByNumber` param: 'pending', has `0` as block number, not 0. as well as the other stuff.

Though i didn't check that in a while. can do.

**Comment by tgerring** [comment]
Maybe relates to #1702

**Comment by chfast** [comment]
There might be a regression in this area.

I have a Python code that was checking if `blockHash` is null in `eth_getTransactionByHash`. In version 1.4.9 it returns `0x000000...`. `blockNumber` is null as it should be.

**Comment by fjl** [comment]
Closed by #3717

**Comment by chfast** [comment]
Wow. It was an old one.

**Comment by Noisyfox** [comment]
This shouldn't be closed sine the blockHash is still '0x00000...' instead of null when calling `eth_getTransactionByHash` with pending transactions.
