### ISSUE TITLE
Geth not requiring required parameters with eth_call

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#886]
develop c8fc4ce

Per spec https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_call "from" and "quantity|tag" are required.  cpp does require the values, but Geth makes assumptions and returns a response.

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{
"to": "0x5f556780ddb00cacc26977d199dae86bf6294495",
"data": "0x2394872"
}],"id":1}' http://localhost:8545
{
	"id": 1,
	"jsonrpc": "2.0",
	"result": "0x0000000000000000000000000000000000000000000000000000000000056be2"
}
```

**Comment by obscuren** [comment]
Neither are required for call.

**Comment by frozeman** [comment]
The second default block parameter should be required. (I will add a test for that)
The RPC tests use only `to` and `data` all other fields are optional.

**Comment by frozeman** [comment]
Ok just tested it. The second parameter in go is not required, though it should be. Its not a problem just inconsistent with the the docs. @obscuren should i create an issue for that?

**Comment by tgerring** [comment]
Why is the second parameter required here when we currently supply "latest" as a reasonable default value?

**Comment by frozeman** [comment]
It is required by the specs. we can give a default value, but then we have to do that for all functions and state it in the RPC docs.

**Comment by tgerring** [comment]
Default block param was optional as far as I understood it, as it was once not even existing as part of the RPC. Before the assumption would have been "latest" as it was the only version of the state available.

In this case, the specs are too rigid as most people will want these calls to execute against the "latest" state, which is a safe default.

**Comment by frozeman** [comment]
sure, ok then i update the docs.

**Comment by frozeman** [comment]
I talked to marek and he says that in the JSONRPC standard there are no optional params. And Cpp can't implement it, as the library they are using is following standards.

So i won't update the docs and we should fix it in go, or leave it as an optional not documented feature (?)
