### ISSUE TITLE
geth 0.9.18 can't generate DAG 

### ISSUE THREAD

**Issue by wuehler** [ethereum/go-ethereum#889]
Just fired up Olympic and geth can't make it through DAG generation. It gets to about 80 or 90% then starts over again.. it's done this 4 times now. In earlier versions I was able to start mining..

Fresh build on Ubuntu 14.04 (AWS)
Geth/v0.9.18/linux/go1.4.2

Ideas?

I0509 15:08:34.163918   10297 ethash.go:213] Still generating DAG: 90%
I0509 15:08:34.266338   10297 ethash.go:213] Still generating DAG: 9%
I0509 15:08:35.792043   10297 ethash.go:213] Still generating DAG: 91%
I0509 15:08:35.887732   10297 ethash.go:213] Still generating DAG: 10%
I0509 15:08:37.412614   10297 ethash.go:213] Still generating DAG: 92%
I0509 15:08:37.495731   10297 ethash.go:213] Still generating DAG: 11%
I0509 15:08:39.040182   10297 ethash.go:213] Still generating DAG: 93%
I0509 15:08:39.108496   10297 ethash.go:213] Still generating DAG: 12%
I0509 15:08:41.153458   10297 ethash.go:213] Still generating DAG: 13%
I0509 15:08:41.766231   10297 ethash.go:213] Still generating DAG: 94%

**Comment by fjl** [comment]
@LefterisJP might know.

**Comment by wuehler** [comment]
It's resolved now.. I expanded the root partition and was a little more patient and the DAG generated fine.

**Comment by LefterisJP** [comment]
Interesting. We should definitely provide some better form of message if there is not enough size in the disk.
