### ISSUE TITLE
Block and mining mismatch

### ISSUE THREAD

**Issue by simenfd** [ethereum/go-ethereum#895]
Why mine #291665 when current block is 291872?  Is this correct?
This is running the latest windows binaries for olympic. (Geth-Win64-20150509111402-0.9.18-60--e289b0a.7z)

I0510 02:13:00.205548   36940 chain_manager.go:628] imported 0 block(s) (0 queued 1 ignored) in 10.4775741s. #291871 [bfc064d4 / b
fc064d4]
I0510 02:13:00.826702   36940 chain_manager.go:628] imported 0 block(s) (0 queued 1 ignored) in 8.273035s. #291870 [9a42c384 / 9a4
2c384]
I0510 02:13:00.837704   36940 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 5.1342632s. #291665 [ee8e244b / ee
8e244b]
I0510 02:13:00.847707   36940 worker.go:204] ??  Mined block #291665
I0510 02:13:00.848707   36940 worker.go:355] commit new work on block 291872 with 0 txs & 0 uncles
I0510 02:13:03.324315   36940 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 1.963482s. #291872 [e7841787 / e78
41787]
I0510 02:13:07.144254   36940 chain_manager.go:628] imported 0 block(s) (0 queued 1 ignored) in 0. #291871 [bfc064d4 / bfc064d4]
I0510 02:13:12.343532   36940 worker.go:355] commit new work on block 291873 with 1 txs & 0 uncles
I0510 02:13:30.659033   36940 chain_manager.go:628] imported 0 block(s) (0 queued 1 ignored) in 13.8604072s. #291873 [1c362e39 / 1
c362e39]

**Comment by obscuren** [comment]
Appears one thread was stuck on an old block. Seems to resume fine afterwards: `commit new work on block 291873`

**Comment by karalabe** [comment]
The miner was reworked a bit and we also found a similar issue that we've fixed in #1031. I believe this should be fixed. Please reopen if you encounter it again.
