### ISSUE TITLE
Mining fails after Importing Ethersale wallet - even with the creation of new accounts and wallets

### ISSUE THREAD

**Issue by vinc456** [ethereum/go-ethereum#896]
Sorry, I realize this is something of a mess but this issue should be logged somewhere. I will look into this cleaning up. I copied and pasted directly from the go-ethereum channel but Gitter may have some export functionality I am unaware of.

When trying to mine I am encountering the error" I0510 00:37:05.925616 18500 backend.go:371] Cannot start mining without etherbase address: no accounts found
" However I have imported the ethwallet.json file generated from the pyethsaletool. I also see something about using a coinbase wallet. How does a coinbase wallet relate to the one generated by the pyethsaletool?
Doesn't a coinbase wallet hold bitcoin?
obscuren an hour ago  
if you’ve successfully imported your ethwallet.json file that should be fine. If you type eth.accounts in the console (run with geth console) what does it show you?
vinc456 an hour ago  
['0x29558c79b32865d1d21b5ebc942d995dd20e3ccd', '0x51185a57571f17e8c517255efeb76979aa7f85db', '0xdbdbd435cb5227e868ef4405559b1693b85b80c9' ]
obscuren an hour ago  
and when you type admin.miner.start() it says can’t mine without account?
vinc456 an hour ago  
true
obscuren an hour ago  
even after restarting the client?
vinc456 an hour ago  
That is the output of admin.miner.start()
I've been using geth, not geth console. I'm not sure what you mean by restarting the client.
obscuren an hour ago  
i meant just stop / start geth
vinc456 an hour ago  
I just opened a new instance of geth console , typed admin.miner.start() and the console prints "true"
obscuren an hour ago  
oh
that’s good
vinc456 an hour ago  
I might have been a tad impatient, it looks like it's generating a DAG for epoch 0 now.
I'll let it run for a while and hopefully it'll be able to mine ether. I am still thoroughly confused about the pyethsaletool wallet vs a coinbase one. Are they equivalent? The pyethsaletool generated some kind of intermediate bitcoin wallet and had the following warning:
"Note that the Ether sale is over, so any purchases made using this method are essentially donations to EthSuisse. This code is only kept online for the benefit of other projects and for individuals wishing to learn how the encryption on their wallet works"
Does that mean that I should create a coinbase one and use that instead? That way I can keep mined ether instead of donating it.
vinc456 an hour ago  
I could take the bitcoin wallet address from coinbase and replace the "btcaddr" pyethsaletool generated ethwallet.json. But that could also break things. Anyways will fiddle around once the DAG is generated/complete.
obscuren an hour ago  
So you don’t have to use your sale wallet
in fact i would recommend not to
if you need an account do one of the following:
geth account new
start geth console and type admin.newAccount()
The pre sale wallet can be used once frontier is released
vinc456 37 minutes ago  
I created a new account but still have the following errors when attempting to mine: I0510 00:56:58.276759 18876 backend.go:371] Cannot start mining without etherbase address: no accounts found
Fatal: Cannot start mining without etherbase address: no accounts found
Does this look like a problem with the account, the wallet, or something else altogether?
obscuren 36 minutes ago  
you’re not by any chance starting thi client with —datadir /a/b/c/path ?
vinc456 36 minutes ago  
Nope, no options are being passed.
obscuren 36 minutes ago  
what does geth account list output?
vinc456 35 minutes ago  
Welcome to the
FRONTIER
Primary #0: {29558c79b32865d1d21b5ebc942d995dd20e3ccd}
Account #1: {307788eb6c6c02c1c9c404ce7ffbd66ae72aeb78}
Account #2: {51185a57571f17e8c517255efeb76979aa7f85db}
Account #3: {dbdbd435cb5227e868ef4405559b1693b85b80c9}
obscuren 35 minutes ago  
curious
vinc456 34 minutes ago  
ubuntu@eth-test-1:~/geth$ geth account new # seemed to create a new primary
Welcome to the
FRONTIER
Your new account is locked with a password. Please give a password. Do not forget this password.
Passphrase:
Repeat Passphrase:
Address: {307788eb6c6c02c1c9c404ce7ffbd66ae72aeb78} # this looks like account 1
obscuren 33 minutes ago  
yeah but it shouldn’t give you no accounts error
because you clearly do have some accounts
vinc456 33 minutes ago  
Will having a docker install conflict with the Ubuntu package?
obscuren 32 minutes ago  
i don’t think so
could you remove your .ethereum/keys folder?
Assuming you’re not using it right now
vinc456 30 minutes ago  
Removed the keys, started 'geth', let it run for a bit before closing and trying to mine. Same error.
obscuren 29 minutes ago  
ok cool
now geth account new
vinc456 29 minutes ago  
But now when I geth account there is a new error: "Fatal: Could not list accounts: no keys in store". Will do that now.
Created the new account and the new errors are as follows: I0510 01:09:36.869265 19150 backend.go:371] Cannot start mining without etherbase address: no accounts found
Fatal: Cannot start mining without etherbase address: no accounts found
Fatal: Cannot start mining without etherbase address: no accounts found
obscuren 26 minutes ago  
hrm
Ok please create an issue and i’ll address it asap
vinc456 26 minutes ago  
I might start a new clean VM instance and try again without docker.
obscuren 26 minutes ago  
for now you can do `geth —etherbase <address you’d like to use> —mine
or that
I’m off for bed now. Good night 
vinc456 24 minutes ago  
Where should I open the issue?
Thanks for your help.
obscuren 23 minutes ago  
https://github.com/ethereum/go-ethereum/issues
Please add that you’ve imported your ether sale wallet and that mining failed after that (this is correct, right?)
The more details the easier it will hopefully be to debug 
vinc456 22 minutes ago  
The pyethsale tool was probably not meant to be used . I'm not a bitcoin miner so I don't have a good grasp of how wallets are used. I didn't realize that creating an account also created a wallet. Yes that is correct.
Not meant to be used after the ethersale.
had ended.
Have a good night.

**Comment by vinc456** [comment]
Let me know if there are any particular details you would like to see. I will probably destroy this vm instance and start anew with a fresh clean system soon. I don't have exact steps to reproduce but perhaps the pyethsaletool should not be used for wallet generation.

**Comment by obscuren** [comment]
This is enough, cheers :-)

**Comment by zelig** [comment]
I am not able to reproduce thisz

**Comment by obscuren** [comment]
Re open if still an issue
