### ISSUE TITLE
admin.miner.start argument not used

### ISSUE THREAD

**Issue by larspensjo** [ethereum/go-ethereum#897]
From the console, I did "admin.miner.stop()", and then "admin.miner.start(7)". This gives a 100% CPU load (running Windows 8.1). After stop again, and then "admin.miner.start(1)", I still get 100% load. It seems it doesn't matter what value I use as argument.

It is a Core I7, with 4x2 threads.

```
$ ./geth version

   Welcome to the
      FRONTIER

Geth
Version: 0.9.18
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2
OS: windows
```

**Comment by larspensjo** [comment]
If I use the argument "--minerthreads", I can control the number of threads. It is also clearly visible in the hashrate. But the "admin.miner.start" always reverts to the number of threads taken from this flag.

**Comment by veox** [comment]
This is a known issue, documented [here](https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#adminminerstart).
