### ISSUE TITLE
 (Fatal: file missing) go-ethereum and cpp-ethereum are sharing the same .ethereum folder

### ISSUE THREAD

**Issue by stephantual** [ethereum/go-ethereum#898]
This one stumps me:

Installed Geth using the PPA at:
https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu

Ran Geth once (upnp errors, but able to create account)

Tried to run Mist
```
Fatal: file missing
Fatal: file missing
```

Tried to run geth again:
```
Fatal: file missing
Fatal: file missing

sudo apt-get remove ethereum
sudo apt-get remove ethereum

geth

Fatal: file missing
Fatal: file missing
```

**Comment by obscuren** [comment]
I think this is caused by a shared folder of `go` and `cpp`. Could you check if you have an `.ethereum` folder? If so could you (re)move it and restart `geth`

**Comment by stephantual** [comment]
You're correct - they both share ~.ethereum, and using both clients make it fail.  See https://github.com/ethereum/cpp-ethereum/issues/1846

**Comment by fjl** [comment]
I don't think we will change the folder name any time soon.
