### ISSUE TITLE
.ethash is not stored under --datadir

### ISSUE THREAD

**Issue by jpritikin** [ethereum/go-ethereum#900]
I'd really prefer to put datadir (all ethereum related files) outside of my home directory.

**Comment by tgerring** [comment]
Just to clarify, is the behaviour you're expecting that ethash folder follows the `--datadir` param?

What OS and Geth version are you running?

**Comment by jpritikin** [comment]
> Just to clarify, is the behaviour you're expecting that ethash folder follows the --datadir param?

I don't know exactly where it should go, but I'd like a command line option to tell geth where to store all its stuff, including .ethash. For example, suppose I get a separate Ethereum hard drive that will have nothing on it except Ethereum stuff and I want to keep the OS and home directory on my regular hard drive.

> What OS and Geth version are you running?

Tanglu Linux amd64 (similar to Debian). Geth v0.9.18 built from source.

**Comment by tgerring** [comment]
This doesn't address the Ethash data location directly, but I added a note to https://github.com/ethereum/go-ethereum/wiki/Backup-&-restore about `--datadir`

**Comment by larspensjo** [comment]
Running on Windows, I also have the problem where ethash remains (silently) in my home folder, even when I use the --datadir flag. This is a problem as I am using a small SSD for C:.

I would expect ethash to also be saved in the folder specified by --datadir. Maybe the ethash data is temporary, which means it could use a name/subfolder that indicates the temporary nature.

**Comment by obscuren** [comment]
We use `~/.ethash` folder so that all clients can make use of the same DAG and you don't have to recreate this DAG for Go & CPP separately. Closing

**Comment by jpritikin** [comment]
Fair enough. You might want to document somewhere that the .ethash directory can be a symbolic link.

**Comment by obscuren** [comment]
Fair enough :-)

**Comment by tgerring** [comment]
Added a note to https://github.com/ethereum/go-ethereum/wiki/Backup-&-restore about location and symlinks

**Comment by dangerousbeans** [comment]
This is maybe a bit awkward for those of us who are both mining on main net and on a local testnet. Right now I have all my GPU's creating ether/warmth and my CPU churning along to mine development blocks, so it'd be good if I can keep the two geth instances separate

**Comment by aberaud** [comment]
@obscuren Thanks for the clarification. This makes sense, however the case where multiple clients connect to different blockchains is not handled.

A solution may be to add a separate optional geth param to specify the ethash directory, such as `--ethashdir`.

**Comment by nyetwurk** [comment]
> the case where multiple clients connect to different blockchains is not handled.

Exactly this. Please consider removing the wontfix tag.
