### ISSUE TITLE
Geth/v0.9.19/darwin/go1.4 - Errors

### ISSUE THREAD

**Issue by jmiehau** [ethereum/go-ethereum#903]
At OS X Yosemite, trying to connect to the blockchain

Last login: Sun May 10 16:15:36 on ttys001
/Users/xx/Downloads/geth\ 2 ; exit;
iMac-de-xx:~ xx$ /Users/xx/Downloads/geth\ 2 ; exit;

   Welcome to the
      FRONTIER

I0510 16:18:30.933057   19165 backend.go:236] Protocol Version: 60, Network Id: 0
I0510 16:18:30.933090   19165 backend.go:246] Blockchain DB Version: 2
I0510 16:18:30.933994   19165 chain_manager.go:235] Last block (#74240) 3ae52b3dc3964c60269ce3796b5a90dda79c9a85b00e6d58c507afc8a3b93861 TD=136666539714
I0510 16:18:31.385410   19165 cmd.go:107] Starting  Geth/v0.9.19/darwin/go1.4
I0510 16:18:31.385495   19165 server.go:209] Starting Server
I0510 16:18:41.489045   19165 nat.go:94] network port 30303 could not be mapped: no UPnP or NAT-PMP router discovered
I0510 16:18:41.951137   19165 udp.go:189] Listening, enode://fdc9a2345e5677d3b3db0065450caa864ee2f7044dce18616e6552584f7654b8a1ec9326787217939a84695f72d98f7a29996174aad4c1566a1dad5593b885b1@192.167.1.10:30303
I0510 16:18:41.951256   19165 backend.go:450] Server started
I0510 16:18:41.951240   19165 server.go:349] Listening on [::]:30303
I0510 16:19:10.753570   19165 worker.go:292] transaction(e13c49ca) below gas price (<90% ask price). All sequential txs from this address(1e77db8f) will fail
I0510 16:19:10.753819   19165 worker.go:292] transaction(2df5969e) below gas price (<90% ask price). All sequential txs from this address(1e77db8f) will fail
I0510 16:19:10.754297   19165 worker.go:292] transaction(e13c49ca) below gas price (<90% ask price). All sequential txs from this address(1e77db8f) will fail
I0510 16:19:10.754512   19165 worker.go:292] transaction(2df5969e) below gas price (<90% ask price). All sequential txs from this address(1e77db8f) will fail

**Comment by tgerring** [comment]
Is the client itself crashing or simply outputting the errors above?

If a crash, can you paste the resulting stack dump or link it via a Gist/Pastebin?

**Comment by jmiehau** [comment]
@Tgerring,  Outputting the errors above. 
Already I changed the title.

**Comment by tgerring** [comment]
Possibly related to #902

**Comment by obscuren** [comment]
Not an error. Just an informative message
