### ISSUE TITLE
Synchronisation failed: pending items in queue

### ISSUE THREAD

**Issue by avdoshyn** [ethereum/go-ethereum#904]
http://prntscr.com/73o0cj

I0510 17:22:40.298594    2764 sync.go:103] Synchronisation failed: pending items in queue

Win7, Geth-Win64-20150510014018-0.9.19-60--7d69679

**Comment by larspensjo** [comment]
I get the same problems, and it seems it never manage to synchronize. I have the following lines repeated for ever:

	I0510 12:44:29.545211    7364 chain_manager.go:558] INVALID block #295558 (b6541bbe32505f68fa58b276353dd1836ea49831f31113977bf8e6a9e8c3f06c)
	I0510 12:44:29.545211    7364 chain_manager.go:559] Block's parent unknown cd065595f8d3c8a4789eb8e4ef14d3fb08c898b130c463f5791909611447d3e4
	I0510 12:44:31.323898    7364 sync.go:100] Synchronisation failed: pending items in queue

**Comment by obscuren** [comment]
> I0510 12:44:31.323898    7364 sync.go:100] Synchronisation failed: pending items in queue

non-issue. It "failed" because there's already a synching process ongoing.

> I0510 12:44:29.545211    7364 chain_manager.go:558] INVALID block #295558 (b6541bbe32505f68fa58b276353dd1836ea49831f31113977bf8e6a9e8c3f06c)

is a real issue. Working on it.
