### ISSUE TITLE
Miner does not stop

### ISSUE THREAD

**Issue by arhuaco** [ethereum/go-ethereum#905]
Perhaps I am doing something wrong.

    > admin.miner.hashrate()
    48
    > admin.miner.stop()
    true
    > admin.miner.stop()
    true

Wait a bit..

    > admin.miner.hashrate()
    56

**Comment by larspensjo** [comment]
Functions return 'true' if they succeed. That means you succeeded to halt the mining. You can verify by doing ```admin.miner.hashrate()``` after you stop mining. It should report 0.

**Comment by Azulan** [comment]
Same issue on Win7x64. Geth becomes unresponsive after giving stop command also.

**Comment by obscuren** [comment]
@zelig could you have a look at this please?

**Comment by zelig** [comment]
@obscuren  so this is sorted right ?

**Comment by obscuren** [comment]
I haven't encountered it anymore

**Comment by arhuaco** [comment]
This time "stop" worked for me. I updated geth a few hours ago.

**Comment by tgerring** [comment]
I've been starting and stopping mining on both my Mac and Windows without a problem now, so I'm closing this issue. Please re-open if the problem persists
