### ISSUE TITLE
Too low gasprice locks up the account

### ISSUE THREAD

**Issue by christianlundkvist** [ethereum/go-ethereum#906]
If I send a contract creation transaction with too low gasprice I get a constant stream of messages like below:
```
I0510 13:40:04.116700    7120 worker.go:292] transaction(d4360ae8) below gas price (<90% ask price). All sequential txs from this address(e3884bdd) will fail
I0510 13:40:07.119271    7120 worker.go:292] transaction(d4360ae8) below gas price (<90% ask price). All sequential txs from this address(e3884bdd) will fail
I0510 13:40:13.122628    7120 worker.go:292] transaction(d4360ae8) below gas price (<90% ask price). All sequential txs from this address(e3884bdd) will fail
```
This seems to continue until the transaction is eventually included in a block, but it locks the account until then. It seems that a transaction with a suffiiently low fee would lock up the account indefinitely (mine was eventually included in a block after several minutes).

**Comment by christianlundkvist** [comment]
A way to fix this problem might be to resend the transaction with the same nonce and a higher fee. I'll update and close if this indeed fixes the problem.

**Comment by christianlundkvist** [comment]
Resending the (contract creation) transaction with the same nonce is not working either. I resent with the same nonce and 10 szabo as transaction fee. This transaction should have been picked up by miners but seems to be blocked.

The updated transaction is

`0xdb1a1a38e12d523615dd930107d578f6749724913a60788d021d494cace96286`

and the original one is

`0x148b2be6ee5ea7fe2d4abb774676552d361d0f7f8747d5954cd594d40dac4b02`

**Comment by obscuren** [comment]
you can resend your transaction:

```
var tx = eth.pendingTransactions()[ TRANSACTION_INDEX ]
eth.resend(tx, newGasPrice)
```

**Comment by christianlundkvist** [comment]
@obscuren Thanks, didn't know about that! Is that exposed through the JSON RPC interface? Didn't see it in the documentation. I'll try it out when I get home and update accordingly.

**Comment by obscuren** [comment]
It's not in the RPC. It's an addition only available through `geth console`

**Comment by christianlundkvist** [comment]
Got it, I'll run it through the console. Thanks again Jeff!

**Comment by christianlundkvist** [comment]
I tried using `resend(tx, gasPrice)`, it doesn't get rid of the transaction with too low gas.

**Comment by obscuren** [comment]
It doesn't get rid of **all** transactions with too low gas. It should only get rid of the transaction which you supplied in the argument.

Please note that doing the following will still not work:

```
#1 gas: 1
#2 gas: 1
#4 gas: 1

resend(#2, 10 szabo)
```

This because #1 can not be processed and transactions need to be processed in order (due to their nonces). Is this what you mean what happened?

**Comment by christianlundkvist** [comment]
No, what happened was
```
#1 gas: 1

resend(#1, 10 szabo)
```
which did not get rid of #1. I was still unable to use the account. Hopefully #908 will fix it though! :)

**Comment by obscuren** [comment]
No that most certainly won't. This is a different issue. 

When you resend tx #1 it should always delete the old one and recreate the new one with a different gas price.

**Comment by christianlundkvist** [comment]
@obscuren So what happened was that `eth.pendingTransactions()` showed the transaction with the low gasprice (only one TX). I then did `resend(tx, '10000000000000')`, and when running `eth.pendingTransactions()` again it now shows only the transaction with the higher gasprice. However, that transaction seemed to be blocked also because I was still getting the messages about subsequent transactions will fail, and the contract was not created on the blockchain.

**Comment by christianlundkvist** [comment]
I thought that the problem resolved itself right now, but actually the original transaction
```
0x47931874a5c4a64b3009e36985c85e308c8c00a2c98b18a823c1d9a827a0c9cd
```
(with low gasprice) got included in a block which seemed to remove the resent transaction (with higher gasprice) from the pending transaction queue.
