### ISSUE TITLE
Synchronization Failed

### ISSUE THREAD

**Issue by reignbeau** [ethereum/go-ethereum#907]
I updated and downloaded the blockchain successfully but couldn't mine. I made changes these changes to my router.

> UPnP is on
> Port Forwarding is on.

This resulted in the following errors and I could no longer import blocks. I am currently using the following settings.

> build/bin/geth -mine -minerthreads 4 -maxpeers 16 -nat any

and get the following errors.

> I0510 11:48:30.268262    2152 backend.go:450] Server started
> I0510 11:48:45.593999    2152 chain_manager.go:558] INVALID block #295176 (ffa9e51dbe996b11f3d5f6a5bc2bf9caa6bf4ab7559383f7b355e064c78ea864)
> I0510 11:48:45.594031    2152 chain_manager.go:559] invalid merkle root. received=47b33b71de5e3eebee351dfe26194fba36bc07fa7176f177e87aa2a17a073a59 got=7099f5b8cbe7fc54456b95d45f21380fd7bd80b2db6318943acd34fe9b9a8774
> I0510 11:48:45.594066    2152 sync.go:103] Synchronisation failed: block downloading cancelled (requested)

And then new problem just now while writing this, I started getting this message in addition to others. I assume this means that my node is being blocked due to being buggy.

> I0510 11:50:12.784277    2152 sync.go:103] Synchronisation failed: no peers available or all peers tried for block download process peers avaialable = 11. total peers = 13. hashes needed = 0

![screenshot from 2015-05-10 12 01 45](https://cloud.githubusercontent.com/assets/12384173/7555811/76a1f33c-f70c-11e4-8335-be6eff317562.png)

I've tested and gotten the same error on both my Windows install as well as Ubuntu install. I'm going to tinker around with my Router some more and keep you updated.

**Comment by tgerring** [comment]
Perhaps related to #868 
What version of geth are you running?

**Comment by reignbeau** [comment]
Running Olympic release. Updatedb seems to have fixed the synchronization failure, but still can't mine yet.
