### ISSUE TITLE
Connected but unable to mine

### ISSUE THREAD

**Issue by reignbeau** [ethereum/go-ethereum#912]
I've connected to the network and can import blocks as they are generated, however, when Geth tries to commit new work on a block, nothing happens. I was expecting to be getting some kind of error message to tell me where I went wrong but I can't find where the problem is.

![mining](https://cloud.githubusercontent.com/assets/12384173/7561766/91dae72c-f783-11e4-9130-73decd3aeef8.png)

**Comment by obscuren** [comment]
It's just mining but you're not finding blocks. Keep trying! :-)

> commit new work ....
