### ISSUE TITLE
eth_getWork starts mining

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#916]
when calling the `eth_getWork` RPC method, the node starts mining.

This is unexpected behaviour and can be be used as an attack vektor.

**Comment by frozeman** [comment]
So it still starts mining, but now auto setting the threads to 0?
Looks like a hack to me :P

**Comment by frozeman** [comment]
Additionally does the first call to `eth_getWork` return empty results, as it first need to start the miner:

```js
web3.eth.getWork()
["", "", ""]
web3.eth.getWork()
["0x083461b6e139df6b1ac2aefd6d0ae9ed8f806fbdae2cb4da6074e6cc0fa78b01", "0x9b2baad7528ecec612c5751a6bd525905892d7892e155c3b05e61363154a940b", "0x00000010f90e0722483014401065c08da3de6a14fc51677179c69d7e8fd4b09a"]
```

This is not ideal, as you will always have to call it twice, to be sure you get the data.

**Comment by obscuren** [comment]
A hack? No. Dig in the logic of the miner if you're curious but please don't cast opinions where you can't have one.
