### ISSUE TITLE
eth_getWork returns non HEX strings

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#917]
`eth_getWork` returns non strings for the last two byte arrays, which don't start with `0x`:

send:
```js
{jsonrpc: "2.0", method: "eth_getWork", params: [], id: 881}
```
 Result:
```js
{
	"id": 881,
	"jsonrpc": "2.0",
	"result": [
		"0xc2aae9392f94b76bf423389298893b709086763539cc0c280833ed82eff31aaf",
		"9b2baad7528ecec612c5751a6bd525905892d7892e155c3b05e61363154a940b",
		"0eaf4a0bac531d9c14b2398be48ec32f8d0c1708335d89862c7bf91e9a"
	]
}
```

The last two return values should start with `0x`.
Additionally the last value is not a 32 bytes boundary condition, it has less than 32 bytes (should be padded?)

Please see the specs for details: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getwork

**Comment by tgerring** [comment]
Fix to remote agent miner made in 8e77f81586e00553362eb48f3702ea8039839c40
