### ISSUE TITLE
State DB returns invalid balance for account 0x0000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by tgerring** [ethereum/go-ethereum#919]
For address `0x0000000000000000000000000000000000000000`

A balance of 1000000000000000000000441362886000000014600 is returned in core/state/statedb.go

However, it seems that 0 should be returned

**Comment by tgerring** [comment]
This occurs in `func (self *StateDB) GetBalance(addr common.Address) *big.Int` and relates to https://github.com/ethereum/web3.js/issues/197

**Comment by obscuren** [comment]
This is correct. Someone send that amount to the zero address.
