### ISSUE TITLE
geth/mist stuck on block #299599, will not download remainder of chain

### ISSUE THREAD

**Issue by mike80439** [ethereum/go-ethereum#921]
I0511 08:39:51.427396   75645 chain_manager.go:558] INVALID block #299600 (6217958a88f2f668740988eb8b29eea31bb6152c6fc1129a93a5ee44156a1604)
I0511 08:39:51.427428   75645 chain_manager.go:559] invalid merkle root. received=5b27a330c2a39380116670f46b32d502d8a29a9dc80aa471a8e479298698c7bc got=7099f5b8cbe7fc54456b95d45f21380fd7bd80b2db6318943acd34fe9b9a8774
I0511 08:39:51.427479   75645 sync.go:103] Synchronisation failed: block downloading cancelled (requested)

**Comment by obscuren** [comment]
Thanks. I'm aware of this one. Unfortunately you need to update to either latest develop or wait for a new release (today) and run `geth upgradedb` afterwards.

**Comment by reignbeau** [comment]
I had the same issue, For windows, I had to manually delete the block chain to force a re-download.

in Windows Command Prompt (In start menu, all programs tab, accessories folder)
> C:\users\owner\appdata\roaming\ethereum
> del blockchain

in Ubuntu, it was much easier.
> Geth Upgradedb

**Comment by obscuren** [comment]
This should be fixed on https://github.com/ethereum/go-ethereum/releases/tag/v0.9.20
