### ISSUE TITLE
Sync stuck

### ISSUE THREAD

**Issue by Quiark** [ethereum/go-ethereum#922]
I remember making a contract, sending some transactions (possibly incorrectly) and then blockchain sync got stuck
` 14 sync.go:100] Synchronisation failed: pending items in queue`

which should not be an issue but it has been like that for over 20 mins.

I`m stuck at block 
```
> eth.getBlock('latest')
{
  transactionsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  stateRoot: '0xdb390058772d6af871335b9f8152805049b96468096d6950b5712ff4b4f9481e',
  difficulty: '286254463',
  size: 515,
  transactions: [ ],
  number: 303634,
  extraData: '0x',
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
  miner: '0x5690aa8347b53382237c2c37db1158a80c9483d5',
  totalDifficulty: '21511977842916',
  nonce: '0x000000000d66c381',
  parentHash: '0x14bfdb96c5e40049a244c0546fadba9e0888871f9f562f4e2f6ef560baa3512b',
  gasLimit: 3141592,
  gasUsed: 0,
  timestamp: 1431352063,
  uncles: [ ],
  hash: '0x61fda4d5349f75b781c5b3b997b89a86c4254987f401ffeaf2bfaf4a4017b926'
}
```

Version:
 'Geth/v0.9.18/linux/go1.4.2'

Full log:
https://gist.github.com/Quiark/a3a2981fd4a21a1d5b95

**Comment by karalabe** [comment]
Ah, and there it is:

```
I0511 15:41:25.288333      33 chain_manager.go:558] INVALID block #303635 (62901c6341ec7aed94c8bb8ea87f2fdd6e5baeaef165aec7e741517e8db08961)
```

This is a duplicate of https://github.com/ethereum/go-ethereum/issues/921, the issue is that the downloader doesn't abort the synchronization if an invalid block is found, but since the invalid block is "missing" from the chain, the rest will not get incorporated. I believe @obscuren had a patch already in the latest develop branch and should be also released today. Follow his advice from the above issue report (and do report if it worked or not :) )

**Comment by Quiark** [comment]
Updated geth, redownloaded blockchain, seems ok.
