### ISSUE TITLE
Proposal: report hashrate in base units of hashes/second

### ISSUE THREAD

**Issue by veox** [ethereum/go-ethereum#923]
Currently `eth-netstats` displays wrong info for `go-ethereum` clients, off by a factor of 1000. C++ clients seem to report in hashes/second.

**Comment by obscuren** [comment]
That's correct. We've got it wrong. We **will** fix this.

**Comment by tgerring** [comment]
Is this something you want fixed in the RPC layer (i.e. multiply KH/s by 1000) or is Gus working on this in conjunction with the improved hashrate reporting?

**Comment by obscuren** [comment]
@Gustav-Simonsson is working on this. The RPC is fine. It assumes to get correct data (but isn't receiving the correct data). Ethash should simply return h/s.

**Comment by zelig** [comment]
we already have this in the docs as H/s so we better fix it

**Comment by Gustav-Simonsson** [comment]
https://github.com/ethereum/go-ethereum/pull/961

**Comment by tgerring** [comment]
This issue should be fixed now. Please re-open if you still see erratic rates.
