### ISSUE TITLE
Mist crash

### ISSUE THREAD

**Issue by mike80439** [ethereum/go-ethereum#927]
OSX Yosemite, 16GB, Retina

http://pastebin.com/sws9ZNKt

**Comment by karalabe** [comment]
Could you please specify the version number of geth? Some fixes have gone into the downloader 1-2 days ago so it might be already fixed (but even if it's not, I don't know which operation is crashing since I don't know the version of the download code I should be matching with the stack trace).

**Comment by mike80439** [comment]
This happened before I updated yesterday (Tuesday 12th).  Now is says 0.9.20. Sorry, I'll be more careful
to post all the information.

brew update
brew upgrade
brew reinstall ethereum --devel --successful --with-gui

**Comment by karalabe** [comment]
Does it still crash, or it is stable now?

**Comment by karalabe** [comment]
We managed to reproduce this locally, a fix is proposed at #954. Will check if the fix actually solves the problem correctly and push afterwards.

**Comment by karalabe** [comment]
Fixed in #954.
