### ISSUE TITLE
Add eth_estimateGas method

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#930]
I talked to christian and gavin yesterday and they both agree that we should have a method which can estimate the gas usage of a transaction, without sending and using up the gas.

This method is now described in the specs: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_estimategas

I already started a branch, but with my limited understanding of the EVM its very hard to get the gas used out of it: https://github.com/frozeman/go-ethereum/tree/estimateGas

I basically create the method `eth_estimateGas`:

```js
case "eth_estimateGas":
		args := new(CallArgs)
		if err := json.Unmarshal(req.Params, &args); err != nil {
			return err
		}

		// this need to return the gas used instead of bytes
		v, err := api.xethAtStateNum(-1).Call(args.From, args.To, args.Value.String(), args.Gas.String(), args.GasPrice.String(), args.Data)
		if err != nil {
			return err
		}

                // this also needs to be changed, depending on the return value
		if v == "0x0" {
			*reply = nil
		} else {
			*reply = newHexNum(big.NewInt(v).Bytes())
		}
```

I could trace the EVM down to https://github.com/frozeman/go-ethereum/blob/estimateGas/core/execution.go#L45

But i have no idea how to return the used gas instead of the VM output. @obscuren could you give me a hint?

**Comment by obscuren** [comment]
Don't worry, i'll fix this for you :-)
