### ISSUE TITLE
geth as farm server doesn't report correct hashrate

### ISSUE THREAD

**Issue by Genoil** [ethereum/go-ethereum#931]
I've got a node set up as farm server (Genoil's node on stats.ethdev.com) with a local Windows PC running ++ethminer at roughly 13MH/s. At the time of writing the issue, I've mined 10 of the last 40 blocks. Nevertheless, my hashrate shows up as 0KH/s.

**Comment by obscuren** [comment]
That's because geth doesn't know know anything about the external miner's hash rate.
