### ISSUE TITLE
Can't build geth from source using v0.9.18 on Mint

### ISSUE THREAD

**Issue by anthony-cros** [ethereum/go-ethereum#934]
Trying to follow https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu's "Building from source" and getting errors:

in stderr:
```
make: *** [geth] Error 2
```

in stdout:
```
In file included from ./secp256k1/src/num_impl.h:17:0,
                 from ./secp256k1/src/secp256k1.c:12,
                 from secp256.go:11:
./secp256k1/src/num_gmp_impl.h:25:13: error: 'secp256k1_num_copy' defined but not used [-Werror=unused-function]
 static void secp256k1_num_copy(secp256k1_num_t *r, const secp256k1_num_t *a) {
             ^
...
cc1: all warnings being treated as errors
```

I simply ran:
```
$ sudo apt-get install -y build-essential libgmp3-dev golang
$ git clone https://github.com/ethereum/go-ethereum
$ cd go-ethereum
$ make geth
```

I'm actually on Linux Mint, I know it's not supported per se, but I just want to make sure it doesn't denote a more serious issue:

```
$ uname -a
Linux barry 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```

I would try and change that *-Werror flag* but I can't seem to find where it's set!

See full logs at: https://gist.github.com/anthony-cros/16dcd43742af7efc7ccb

**Comment by obscuren** [comment]
try `CFLAGS="-Wno-error" make geth`

**Comment by anthony-cros** [comment]
Thanks, but it didn't seem to get picked up (I also tried "export" first) :(

**Comment by bas-vk** [comment]
secp256k1 is an external dependency and uses very strict compiler flags.
Could you try to build it manually and report if that succeeds?

The source can be found on `https://github.com/bitcoin/secp256k1`, just follow the build instructions.

**Comment by anthony-cros** [comment]
Hi @bas-vk , sorry what do you mean by "manually"? I'm using "make" so it's as manual as I know how to build :)

**Comment by tgerring** [comment]
@anthony-cros I think he's asking to follow the [secp256k1 build steps](https://github.com/bitcoin/secp256k1#build-steps)

**Comment by anthony-cros** [comment]
Hmm, interesting... I was able to run "make geth" successfully on a docker container... I was trying to recreate the problem first. The initial post happened on an amazon instance, so maybe that's what's changed, unless the latest develop contains a workaround?

**Comment by obscuren** [comment]
Nothing on develop has changed. Could you close this issue if it's fixed?

**Comment by anthony-cros** [comment]
Sure, it must have been something to do with the amazon instance setup, but I can't reproduce it easily
