### ISSUE TITLE
geth does not seem to be mining on private chain.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/go-ethereum#935]
This is the specific command I am using:
`geth --datadir eth0 --maxpeers 0 --networkid [redacted] --natspec --mine console`
Doing either this, or manually starting through admin.miner.start() will result in the DAG eventually being generated or loaded, but it will not do anything else. No blocks are mined. admin.miner.hashrate() says the hashrate is zero, and top running in another terminal shows too little CPU activity than if it was really mining.

**Comment by obscuren** [comment]
Got some logs?

**Comment by Smithgift** [comment]
Ran geth for at least a minute in a new datadir with a new network id. Here's what it said:
http://pastebin.com/JxdLYdNy

**Comment by Smithgift** [comment]
N.B. Geth had previously mined just fine on one of these private chains. The last time it successfully mined was, according to the timestamp, Sun, 03 May 2015 01:35:12 GMT. I wasn't mining continuously (that's actually block 3), but that still provides a theoretical lower limit in time for when it broke.

**Comment by Smithgift** [comment]
I realize this computer has only 2 GB of RAM. Whether or not this just because of lack of RAM, I don't think it's worth it to mine on this. Closing.
