### ISSUE TITLE
crash while syncing with network

### ISSUE THREAD

**Issue by iurimatias** [ethereum/go-ethereum#936]
I0512 12:08:31.898419   42470 chain_manager.go:628] imported 128 block(s) (0 queued 0 ignored) in 482.339993ms. #110976 [5af2df94 / c8d7daab]
I0512 12:08:33.398931   42470 chain_manager.go:628] imported 128 block(s) (0 queued 0 ignored) in 481.913878ms. #111104 [dfcc4af7 / c6190d22]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x447077e]

goroutine 397 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*peer).promote(0x0)
        /private/tmp/ethereum20150511-96374-1t0ptgk/src/github.com/ethereum/go-ethereum/eth/downloader/peer.go:104 +0x8e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).startFetchingBlocks(0xc209655d50, 0xc209730540, 0x0, 0x0)
        /private/tmp/ethereum20150511-96374-1t0ptgk/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:368 +0x765
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).getFromPeer(0xc209655d50, 0xc209730540, 0xd3f04186b1fbec3, 0xc04eba086eeacf13, 0x2a4a96e51dca2516, 0x5639769934b7069f, 0x403d800, 0x0, 0x0)
        /private/tmp/ethereum20150511-96374-1t0ptgk/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:191 +0x2d9
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc209655d50, 0xc21aad3500, 0x10, 0xd3f04186b1fbec3, 0xc04eba086eeacf13, 0x2a4a96e51dca2516, 0x5639769934b7069f, 0x0, 0x0)
        /private/tmp/ethereum20150511-96374-1t0ptgk/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:151 +0x229

**Comment by obscuren** [comment]
This has been addressed on `develop`. Release incoming today :-)

**Comment by Quiark** [comment]
happened to me too
https://gist.github.com/Quiark/ea8002e4dd52f1e3afc4

**Comment by karalabe** [comment]
@Quiark Your issue is different from this report. It has been fixed 3 days ago by #954.
@iurimatias This was fixed as far as I know in #915.

 Please update to latest develop or wait for a new release (though update would probably be simpler).
