### ISSUE TITLE
mined the same block two times

### ISSUE THREAD

**Issue by avdoshyn** [ethereum/go-ethereum#938]
I0512 21:39:47.047406    5368 worker.go:355] commit new work on block 313694 with 0 txs & 0 uncles
I0512 21:40:11.045778    5368 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 11.0006ms. #313687 [3a1991af / 3a1991af]
I0512 21:40:11.047779    5368 worker.go:204] ??  Mined block #313687
I0512 21:40:12.057836    5368 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 997.057ms. #313694 [adab2b54 / adab2b54]
I0512 21:40:18.148185    5368 worker.go:355] commit new work on block 313695 with 0 txs & 0 uncles
I0512 21:40:18.148185    5368 chain_manager.go:628] imported 0 block(s) (0 queued 1 ignored) in 0. #313687 [3a1991af / 3a1991af]
I0512 21:40:18.173186    5368 worker.go:204] ??  Mined block #313687
I0512 21:40:27.083696    5368 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 7.0004ms. #313695 [13e9b63d / 13e9b63d]
I0512 21:40:29.386828    5368 worker.go:355] commit new work on block 313696 with 1 txs & 0 uncles
I0512 21:40:44.306681    5368 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 978.056ms. #313696 [d719a4b3 / d719a4b3]
I0512 21:40:45.441746    5368 worker.go:355] commit new work on block 313697 with 0 txs & 0 uncles

is it ok?

**Comment by obscuren** [comment]
Yep, that's possible since it's multithreaded. If you look carefully you'll spot that both of the blocks have different hashes:

**adab2b54**
```
I0512 21:40:11.047779 5368 worker.go:204] ?? Mined block #313687
I0512 21:40:12.057836 5368 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 997.057ms. #313694 [adab2b54 / adab2b54]
```

**13e9b63d**
```
I0512 21:40:18.173186 5368 worker.go:204] ?? Mined block #313687
I0512 21:40:27.083696 5368 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 7.0004ms. #313695 [13e9b63d / 13e9b63d]
```
