### ISSUE TITLE
geth --mine stuck at "24160 chain_manager.go:628] imported 256 block(s)"

### ISSUE THREAD

**Issue by binhnguyen3000** [ethereum/go-ethereum#939]
On Ubuntu, my geth first mining run seems to be in a loop below. Does anyone see the same issue?

I0512 15:45:40.163188   24160 worker.go:226] 🔨  Mined block #52
I0512 15:45:41.159289   24160 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 5.273625ms. #52 [a7a8e808 / a7a8e808]
I0512 15:45:41.159572   24160 worker.go:226] 🔨  Mined block #52
I0512 15:46:29.422794   24160 chain_manager.go:580] Split detected. New head #52 (85310f80) TD=7029145, was #52 (1e4a1e64) TD=7028067
I0512 15:46:30.405401   24160 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 1.214784311s. #256 [110bd75c / 5eda8721]
I0512 15:46:31.582860   24160 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 1.177348029s. #512 [db
...
I0512 15:52:30.204008   24160 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 4.782888666s. #55040 [daa4dbf9 / dbf78148]
I0512 15:52:37.929488   24160 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 7.725356824s. #55296 [1f47476b / 007085c6]
I0512 15:52:43.983869   24160 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 6.054251641s. #55552 [f9a0ccb1 / 51b641d1]

**Comment by obscuren** [comment]
I'm not seeing a loop. If you're referring to the two blocks (#52) having the same number, that's possible due to multithreaded mining. They are different blocks though
