### ISSUE TITLE
One of my geth console died while mining

### ISSUE THREAD

**Issue by anthony-cros** [ethereum/go-ethereum#940]
All the others are fine, somehow this one keeps dying, see log at: https://gist.github.com/anthony-cros/e79ab51aced97a6d054e

**Comment by karalabe** [comment]
Does this happen consistently over multiple runs? Does it mine for a while and only crash afterwards? Geth version?

**Comment by obscuren** [comment]
Which version of geth?

**Comment by drupalnomad** [comment]
I an getting the same bug on ubuntu. I am not mining. http://pastebin.com/gcuEbfJR

**Comment by holiman** [comment]
I also got this

	I0513 14:06:42.470316    4698 worker.go:226] 🔨  Mined block #14200
	I0513 14:06:42.478105    4698 worker.go:337] commit new work on block 14201 with 0 txs & 0 uncles
	panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xb code=0x1 addr=0x0 pc=0x50445a]

	goroutine 3564 [running]:
	github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
		/build/buildd/ethereum-0.9.20+493SNAPSHOT20150512172414trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/types/block.go:319 +0xca
	github.com/ethereum/go-ethereum/core.(*ChainManager).InsertChain(0xc208e5e1e0, 0xc20c47a000, 0x100, 0x400, 0x0, 0x0, 0x0)
		/build/buildd/ethereum-0.9.20+493SNAPSHOT20150512172414trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/chain_manager.go:575 +0x130b
	github.com/ethereum/go-ethereum/eth.(*ProtocolManager).processBlocks(0xc20a8dc900, 0x0, 0x0)
		/build/buildd/ethereum-0.9.20+493SNAPSHOT20150512172414trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/sync.go:64 +0x371
	created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).update
		/build/buildd/ethereum-0.9.20+493SNAPSHOT20150512172414trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/sync.go:39 +0x317
		
	goroutine 1 [select]:
	gith

Full dump at [pastebin](http://pastebin.com/3qUtKNaL)

**Comment by holiman** [comment]
... And another one. The mining goes fine for a while, then *boom* 
[Dump at pastebin](http://pastebin.com/iPf8VG43)

**Comment by holiman** [comment]
Scratch that, it happens even when I'm not mining:

	#geth console

	   Welcome to the
	      FRONTIER

	I0513 14:22:47.646245    6022 backend.go:239] Protocol Version: 60, Network Id: 0
	I0513 14:22:47.646339    6022 backend.go:249] Blockchain DB Version: 2
	I0513 14:22:47.648058    6022 chain_manager.go:235] Last block (#14233) 8433c6f9013b485046fbfca8bc76e1114402ae28c5e757439d645afa628c4801 TD=10438439508
	I0513 14:22:47.972350    6022 cmd.go:107] Starting  Geth/v0.9.20/linux/go1.4.2
	I0513 14:22:47.972453    6022 server.go:209] Starting Server
	I0513 14:22:49.701920    6022 nat.go:94] network port 30303 could not be mapped: no UPnP or NAT-PMP router discovered
	I0513 14:22:49.718982    6022 udp.go:189] Listening, enode://db8c84ba62cc9bb6317a105cab9155ca7243f420f8d2215178613dba7e3532d0394713331b356a94905e9069d63e507bdf4e9d559d502915f4ba493e00dcb2d2@[::]:30303
	I0513 14:22:49.719067    6022 backend.go:456] Server started
	I0513 14:22:49.719069    6022 server.go:349] Listening on [::]:30303
	I0513 14:22:49.719105    6022 nat.go:94] network port 30303 could not be mapped: no UPnP or NAT-PMP router discovered
	> loadScript("eth.js")
	true
	> cAB()
	  eth.accounts[0]: 0x371c7e8b63c36d042ae0c829daf7db31f37031ce 	balance: 188.671875 ether
	undefined
	> panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xb code=0x1 addr=0x0 pc=0x50445a]

	goroutine 2048 [running]:
	github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
		/build/buildd/ethereum-0.9.20+493SNAPSHOT20150512172414trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/types/block.go:319 +0xca
	github.com/ethereum/go-ethereum/core.(*ChainManager).InsertChain(0xc2085e6690, 0xc20c388000, 0x100, 0x400, 0x0, 0x0, 0x0)
		/build/buildd/ethereum-0.9.20+493SNAPSHOT20150512172414trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/chain_manager.go:575 +0x130b
	github.com/ethereum/go-ethereum/eth.(*ProtocolManager).processBlocks(0xc208d31d40, 0x0, 0x0)
		/build/buildd/ethereum-0.9.20+493SNAPSHOT20150512172414trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/sync.go:64 +0x371
	created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).update
		/build/buildd/ethereum-0.9.20+493SNAPSHOT20150512172414trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/sync.go:39 +0x317


Full dump in [pastebin](http://pastebin.com/cAsQu4s1)

**Comment by anthony-cros** [comment]
> Does this happen consistently over multiple runs?

Yes it did

> Which version of geth?

I believe this was the very latest release (0.9.20) but I'll have to check (90% sure though)

**Comment by holiman** [comment]
I tried updating to the latest shiny new in the PPA (`ethereum-0.9.20+495SNAPSHOT20150513110249trusty` instead of `ethereum-0.9.20+493SNAPSHOT20150512172414trusty`). 

Result:

	> panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xb code=0x1 addr=0x0 pc=0x50455a]

	goroutine 1189 [running]:
	github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
		/build/buildd/ethereum-0.9.20+495SNAPSHOT20150513110249trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/types/block.go:319 +0xca
	github.com/ethereum/go-ethereum/core.(*ChainManager).InsertChain(0xc2082041e0, 0xc2255dc800, 0x100, 0x100, 0x0, 0x0, 0x0)
		/build/buildd/ethereum-0.9.20+495SNAPSHOT20150513110249trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/chain_manager.go:575 +0x130b
	github.com/ethereum/go-ethereum/eth.(*ProtocolManager).processBlocks(0xc209b8c0c0, 0x0, 0x0)
		/build/buildd/ethereum-0.9.20+495SNAPSHOT20150513110249trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/sync.go:64 +0x371
	created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).update
		/build/buildd/ethereum-0.9.20+495SNAPSHOT20150513110249trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/sync.go:39 +0x317



Here's the [dump](http://pastebin.com/3g7C6kTt)

**Comment by holiman** [comment]
@anthony-cros it's displayed in the crash dump (from your dump): 

    github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
	/build/buildd/ethereum-0.9.20+19trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/types/block.go:319 +0xca

You ran version `0.9.20+19`

**Comment by anthony-cros** [comment]
@holiman cool, thanks!

**Comment by obscuren** [comment]
Did you run the same chain with `0.9.19`?

**Comment by holiman** [comment]
As for me; I started experimenting with it yesterday, so haven't run any other version than the two variants of `0.9.20` above.

**Comment by anthony-cros** [comment]
@obscuren it's possible, I don't quite remember... Would they be incompatible?

**Comment by obscuren** [comment]
@anthony-cros there was a problem in pre .20 which could possibly cause this error.

**Comment by holiman** [comment]
How do I 'reset' my computer; would it be back from 'scratch' if I removed the `.ethereum` and/or `.ethash` directories? Or is there something else I should do to try to get it working again? I have a feeling that something is corrupt, and I'd like to try resetting whatever states/databases I have locally. Oh and I have no local wallets that I care about, so that's not a concern..

**Comment by obscuren** [comment]
If you're on OS X remove `~/Library/Ethereum/blockchain` or on linux `~/.ethereum/blockchain`. Or do a `geth upgradedb`

**Comment by anthony-cros** [comment]
Another instance of it: https://gist.github.com/anthony-cros/bf6fce90f2f6e5c94f7d, or a different problem (not sure)?

**Comment by holiman** [comment]
@obscuren thanks, I've upgraded the db, let's see if it happens again. 

On a sidenote, in case it makes any difference: before I ran `geth` normally, I tested with `geth --networkid='-1234'` as specified in the docs to test with my own network. 

Oh, and now it crashed again. Here's the main parts of the dump.. 

	#geth upgradedb

	   Welcome to the
	      FRONTIER

	Upgrade blockchain DB
	I0514 21:45:02.280471    4843 backend.go:239] Protocol Version: 60, Network Id: 0
	I0514 21:45:02.280499    4843 backend.go:249] Blockchain DB Version: 2
	I0514 21:45:02.281894    4843 chain_manager.go:235] Last block (#14233) 8433c6f9013b485046fbfca8bc76e1114402ae28c5e757439d645afa628c4801 TD=10438439508
	exporting blockchain '/home/martin/.ethereum/blockchain_2_2015-05-14_21:45:02.chain'
	I0514 21:45:02.604362    4843 chain_manager.go:335] exporting 14233 blocks...
	exported blockchain
	I0514 21:45:03.452455    4843 database.go:125] flushed and closed db: /home/martin/.ethereum/blockchain
	I0514 21:45:03.452817    4843 database.go:125] flushed and closed db: /home/martin/.ethereum/state
	I0514 21:45:03.452906    4843 database.go:125] flushed and closed db: /home/martin/.ethereum/extra
	I0514 21:45:03.502265    4843 backend.go:239] Protocol Version: 60, Network Id: 0
	I0514 21:45:03.502290    4843 backend.go:249] Blockchain DB Version: 2
	I0514 21:45:03.503541    4843 chain_manager.go:235] Last block (#0) fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca TD=0
	importing blockchain '/home/martin/.ethereum/blockchain_2_2015-05-14_21:45:02.chain'
	I0514 21:45:12.986157    4843 chain_manager.go:628] imported 2499 block(s) (0 queued 1 ignored) in 9.466909915s. #2499 [fd4af92a / a1918400]
	I0514 21:45:21.390158    4843 chain_manager.go:628] imported 2500 block(s) (0 queued 0 ignored) in 8.394349091s. #4999 [58cd3a67 / 8ee55473]
	I0514 21:45:29.704553    4843 chain_manager.go:628] imported 2500 block(s) (0 queued 0 ignored) in 8.304256236s. #7499 [820aa786 / 97b2ea25]
	I0514 21:45:38.264527    4843 chain_manager.go:628] imported 2500 block(s) (0 queued 0 ignored) in 8.549470934s. #9999 [c1f42b41 / 869b44a5]
	I0514 21:45:47.101758    4843 chain_manager.go:628] imported 2500 block(s) (0 queued 0 ignored) in 8.816913908s. #12499 [74ce0822 / 8e1aecff]
	I0514 21:45:53.180250    4843 chain_manager.go:628] imported 1734 block(s) (0 queued 0 ignored) in 6.071464174s. #14233 [822170e1 / 8433c6f9]
	imported 14234 blocks
	I0514 21:45:53.334265    4843 database.go:125] flushed and closed db: /home/martin/.ethereum/blockchain
	I0514 21:45:53.671333    4843 database.go:125] flushed and closed db: /home/martin/.ethereum/state
	I0514 21:45:53.671412    4843 database.go:125] flushed and closed db: /home/martin/.ethereum/extra
	Import finished
	[~]
	#geth 

	   Welcome to the
	      FRONTIER

	I0514 21:52:26.124702    4973 backend.go:239] Protocol Version: 60, Network Id: 0
	I0514 21:52:26.124767    4973 backend.go:249] Blockchain DB Version: 2
	I0514 21:52:26.125583    4973 chain_manager.go:235] Last block (#14233) 8433c6f9013b485046fbfca8bc76e1114402ae28c5e757439d645afa628c4801 TD=10438439508
	I0514 21:52:26.411606    4973 cmd.go:107] Starting  Geth/v0.9.20/linux/go1.4.2
	I0514 21:52:26.411709    4973 server.go:209] Starting Server
	I0514 21:52:27.788468    4973 nat.go:94] network port 30303 could not be mapped: no UPnP or NAT-PMP router discovered
	I0514 21:52:27.831043    4973 udp.go:189] Listening, enode://db8c84ba62cc9bb6317a105cab9155ca7243f420f8d2215178613dba7e3532d0394713331b356a94905e9069d63e507bdf4e9d559d502915f4ba493e00dcb2d2@[::]:30303
	I0514 21:52:27.831192    4973 backend.go:456] Server started
	I0514 21:52:27.831182    4973 server.go:349] Listening on [::]:30303
	I0514 21:52:27.831206    4973 nat.go:94] network port 30303 could not be mapped: no UPnP or NAT-PMP router discovered
	I0514 21:53:48.851539    4973 chain_manager.go:628] imported 128 block(s) (0 queued 0 ignored) in 1.504695694s. #14208 [647bba9a / eea93301]
	panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xb code=0x1 addr=0x0 pc=0x50455a]

	goroutine 771 [running]:
	github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
		/build/buildd/ethereum-0.9.20+495SNAPSHOT20150513110249trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/types/block.go:319 +0xca
	github.com/ethereum/go-ethereum/core.(*ChainManager).InsertChain(0xc2087161e0, 0xc2080ff000, 0x100, 0x200, 0x0, 0x0, 0x0)
		/build/buildd/ethereum-0.9.20+495SNAPSHOT20150513110249trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/core/chain_manager.go:575 +0x130b
	github.com/ethereum/go-ethereum/eth.(*ProtocolManager).processBlocks(0xc209bdc840, 0x0, 0x0)
		/build/buildd/ethereum-0.9.20+495SNAPSHOT20150513110249trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/sync.go:64 +0x371
	created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).update
		/build/buildd/ethereum-0.9.20+495SNAPSHOT20150513110249trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/eth/sync.go:39 +0x317

	goroutine 1 [chan receive, 1 minutes]:

**Comment by karalabe** [comment]
@anthony-cros Your crash was fixed yesterday by https://github.com/ethereum/go-ethereum/pull/954, please update to latest develop.

**Comment by holiman** [comment]
To be precise, the crash that was fixed was the latest one that @anthony-cros reported, within fetchHashes. The other issue in `Hash()` from `InsertChain` is something else..

**Comment by karalabe** [comment]
Yeah, that's what I've said :D :P

**Comment by anthony-cros** [comment]
@karalabe thanks, but I can't seem to build (see https://github.com/ethereum/go-ethereum/issues/934) so I have to stick to PPA for now.

The one difference with my latest comment above is that I was able to successfully restart it this time (which wasn't the case with my original post). Note also that geth in that case geth was in "-rpc" mode and ethminer was GPU mining for it. I know ethminer is on the cpp side, but I wouldn't expect it to crash geth. That's what makes me wonder if it could be another issue maybe (note that it doesn't block me since I successfully restarted geth/ethminer)

**Comment by holiman** [comment]
@anthony-cros yes, your latest issue is another issue altogether, occurring at a different place. Also, it's been fixed. Let's try to keep this issue on the originally reported bug: where stack traces begin like this:

    github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)

**Comment by holiman** [comment]
I've looked a bit into this. I built form source, instead, and made a modification:

	func (self *Block) Hash() common.Hash {
		if (self == nil){
			fmt.Printf("Self is nil!")
		}

		if (self.HeaderHash != common.Hash{}) {
			return self.HeaderHash
		} else {
			return self.header.Hash()
		}
	}

Result:

	I0515 10:27:24.958539   15759 chain_manager.go:621] imported 128 block(s) (0 queued 0 ignored) in 1.44289754s. #14208 [647bba9a / eea93301]
Self is nil!panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x505f27]

goroutine 1607 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
	/home/martin/workspace/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/types/block.go:325 +0x127

So, this is the caller:

			if block.Td.Cmp(self.td) > 0 {
				// Check for chain forks. If H(block.num - 1) != block.parent, we're on a fork and need to do some merging
				if previous := self.getBlockByNumber(block.NumberU64() - 1); previous.Hash() != block.ParentHash() {

So what happens is that `self.getBlockByNumber(block.NumberU64() - 1)` sets `previous` to nil. Let's lok at that: 

		// non blocking version
	func (self *ChainManager) getBlockByNumber(num uint64) *types.Block {
		key, _ := self.blockDb.Get(append(blockNumPre, big.NewInt(int64(num)).Bytes()...))
		if len(key) == 0 {
			return nil
		}

		return self.GetBlock(common.BytesToHash(key))
	}

So I made a modified version:

	// non blocking version
	func (self *ChainManager) getBlockByNumber(num uint64) *types.Block {
		key, _ := self.blockDb.Get(append(blockNumPre, big.NewInt(int64(num)).Bytes()...))
		if len(key) == 0 {
			fmt.Printf("len(key) == 0 for block %d", num)
			return nil
		}

		return self.GetBlock(common.BytesToHash(key))
	}

And here's the output:

	I0515 10:41:43.166615   16100 downloader.go:130] Block synchronisation started
	len(key) == 0 for block 14238Self is nil!panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xb code=0x1 addr=0x0 pc=0x505f27]

	goroutine 666 [running]:
	github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
		/home/martin/workspace/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/types/block.go:325 +0x127
	github.com/ethereum/go-ethereum/core.(*ChainManager).InsertChain(0xc208e641e0, 0xc211bf2000, 0x100, 0x400, 0x0, 0x0, 0x0)

Specifically, of note: `len(key) == 0 for block 14238`. Let me know what I can do to help resolve this...

**Comment by holiman** [comment]
Oh, and I also checked the error message returned from `self.blockDb.Get`; it is `leveldb: not found`

**Comment by holiman** [comment]
I did some more digging, doing some printouts:

			self.mu.Lock()
			{
				cblock := self.currentBlock
				// Write block to database. Eventually we'll have to improve on this and throw away blocks that are
				// not in the canonical chain.
				glog.V(logger.Error).Infof("[%v] inserting block #%d (%d TXs %d UNCs) (%x...) block.Td=%d self.td=%d\n", time.Now().UnixNano(), block.Number(), len(block.Transactions()), len(block.Uncles()), block.Hash().Bytes()[0:4], block.Td,self.td)
				self.write(block)

				// Compare the TD of the last known block in the canonical chain to make sure it's greater.
				// At this point it's possible that a different chain (fork) becomes the new canonical chain.
				if block.Td.Cmp(self.td) > 0 {
					// Check for chain forks. If H(block.num - 1) != block.parent, we're on a fork and need to do some merging
					if previous := self.getBlockByNumber(block.NumberU64() - 1); previous.Hash() != block.ParentHash() {
						// during split we merge two different chains and create the new canonical chain
						self.merge(previous, block)

						queue[i] = ChainSplitEvent{block, logs}
						queueEvent.splitCount++
					}

					self.setTotalDifficulty(block.Td)
					self.insert(block)

					jsonlogger.LogJson(&logger.EthChainNewHead{
						BlockHash:     block.Hash().Hex(),
						BlockNumber:   block.Number(),
						ChainHeadHash: cblock.Hash().Hex(),
						BlockPrevHash: block.ParentHash().Hex(),
					})

					self.setTransState(state.New(block.Root(), self.stateDb))
					self.txState.SetState(state.New(block.Root(), self.stateDb))

					queue[i] = ChainEvent{block, logs}
					queueEvent.canonicalCount++

	//				if glog.V(logger.Info) {
						glog.V(logger.Error).Infof("[%v] inserted block #%d (%d TXs %d UNCs) (%x...)\n", time.Now().UnixNano(), block.Number(), len(block.Transactions()), len(block.Uncles()), block.Hash().Bytes()[0:4])
	//				}
				} else {
	//				if glog.V(logger.Detail) {
						glog.V(logger.Error).Infof("inserted forked block #%d (TD=%v) (%d TXs %d UNCs) (%x...)\n", block.Number(), block.Difficulty(), len(block.Transactions()), len(block.Uncles()), block.Hash().Bytes()[0:4])
	//				}

					queue[i] = ChainSideEvent{block, logs}
					queueEvent.sideCount++
				}
				self.futureBlocks.Delete(block.Hash())
			}


Here is the output:


	I0515 12:45:04.611897   20956 chain_manager.go:612] inserted forked block #14237 (TD=1019264) (0 TXs 0 UNCs) (f105a56f...)
	I0515 12:45:04.614939   20956 chain_manager.go:576] [1431686704614925081] inserting block #14238 (0 TXs 0 UNCs) (cc918e20...) block.Td=10437970478 self.td=10438439508
	I0515 12:45:04.615051   20956 chain_manager.go:612] inserted forked block #14238 (TD=1018767) (0 TXs 0 UNCs) (cc918e20...)
	I0515 12:45:04.618514   20956 chain_manager.go:576] [1431686704618493880] inserting block #14239 (0 TXs 0 UNCs) (5eab10c8...) block.Td=10438988748 self.td=10438439508
	I0515 12:45:04.618667   20956 chain_manager.go:436] len(key) == 0 for block 14238 :leveldb: not found
	Self is nil!panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xb code=0x1 addr=0x0 pc=0x505f27]

	goroutine 1692 [running]:
	github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
		/home/martin/workspace/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/types/block.go:325 +0x127
	github.com/ethereum/go-ethereum/core.(*ChainManager).InsertChain(0xc208e6a1e0, 0xc20c534800, 0x100, 0x100, 0x0, 0x0, 0x0)
		/home/martin/workspace/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/chain_manager.go:583 +0x1846
	github.com/ethereum/go-ethereum/eth.(*ProtocolManager).processBlocks(0xc20b55a000, 0x0, 0x0)
		/home/martin/workspace/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:71 +0x374
	github.com/ethereum/go-ethereum/eth.func·005()
		/home/martin/workspace/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:43 +0x33
	created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).update
		/home/martin/workspace/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:45 +0x3ef


As you can see, the block `14238` is processed. It goes into the second leg of the if-block, outputting `inserted forked block`. Thus, it is never actually inserted as in `self.insert(block)` but written as in `self.write(block)`. The next block, `14239`, for some reason goes into the first leg, since the `Td` of that block `10438988748` is larger than `self.td` (`10438439508`). Thus, it tries to perform a `getBlockByNumber` on `14238`. If I understand correctly, however, the `write`-operation only makes it lookuppable by hash, while the `insert`-operation is required for the block to be looked-up by number:

	func (bc *ChainManager) insert(block *types.Block) {
		key := append(blockNumPre, block.Number().Bytes()...)
		bc.blockDb.Put(key, block.Hash().Bytes())

		bc.blockDb.Put([]byte("LastBlock"), block.Hash().Bytes())
		bc.currentBlock = block
		bc.lastBlockHash = block.Hash()
	}

	func (bc *ChainManager) write(block *types.Block) {
		enc, err := rlp.EncodeToBytes((*types.StorageBlock)(block))
		if err != nil	{
			glog.V(logger.Error).Infof("write(block) error for block %v :%v", block,err)	
			glog.V(logger.Error).Infof("enc has value %v ", enc)		
		}

		key := append(blockHashPre, block.Hash().Bytes()...)
		bc.blockDb.Put(key, enc)
		// Push block to cache
		bc.cache.Push(block)
	}


So, from a programming-perspective I know why it fails, but I have no idea how it should be...? (I am a noob at both Go and Ethereum)

**Comment by obscuren** [comment]
Thanks for all the incredible helpful debugging and output. I'll look in to this immediately!

**Comment by obscuren** [comment]
This is the issue in ASCII

```
        O    10
      / |
12   O  O    13
     |  |
13   O  O    14
     |
14   O
     |
15   O <- attemps to refer to block.N - 1 in the canon chain which doesn't exist
```

Creating fix

**Comment by holiman** [comment]
I can confirm that it works now. Thanks!

	I0516 09:44:51.588895    3792 downloader.go:145] Block synchronisation started
	I0516 09:46:02.414755    3792 chain_manager.go:670] Fork detected @ dbb21a9c. Reorganising chain from #14233 8433c6f9 to 5eab10c8
	I0516 09:46:02.757364    3792 chain_manager.go:627] imported 256 block(s) (0 queued 0 ignored) in 1.923743429s. #14336 [647bba9a / 488d4e0b]
