### ISSUE TITLE
Wallet balance is now 10000E20 Ether

### ISSUE THREAD

**Issue by mike80439** [ethereum/go-ethereum#942]
Don't know how this happened, but it's probably a bug.  This happened today 5/12/2015. Previous balance was about 25 Ether.

**Comment by obscuren** [comment]
We've been sending ether around to people. What's your address?

**Comment by mike80439** [comment]
'geth account list' reports 'Fatal: Could not list accounts: no keys in store'

**Comment by obscuren** [comment]
Please see https://github.com/ethereum/go-ethereum/releases/tag/v0.9.20

**Comment by obscuren** [comment]
@mike80439 did you fix your issue?
