### ISSUE TITLE
AlethZero Mining while disconnected

### ISSUE THREAD

**Issue by reignbeau** [ethereum/go-ethereum#943]
Upper Right corner, 0 bars, not connected to internet.
Upper Left corner, Account 1, 9000 Finney.
Bottom, 120 Kilohashes per second.

I assume this means it is generating a fork every time my internet connection drops or lags. Running 
AlethZero/v0.9.18/Release/Linux/g++/int on Ubuntu .

![screenshot from 2015-05-12 18 15 12](https://cloud.githubusercontent.com/assets/12384173/7601981/00dc65d8-f8d3-11e4-8eeb-c7e16f8ca47e.png)

**Comment by tgerring** [comment]
Please file this in the [ethereum/cpp-ethereum](https://github.com/ethereum/cpp-ethereum) repo
