### ISSUE TITLE
Unable to unlock accounts

### ISSUE THREAD

**Issue by arvicco** [ethereum/go-ethereum#945]
Unable to unlock accounts. OSX 10.10.2, homebrewed Geth/v0.9.20/darwin/go1.4.2. Geth creates the accounts, but then always fails to unlock them (naturally, using the very same password). Seems like it looks for a wrong file (dba1d6db83a3cae28beac8850f2e9e5592572cf7 file is in keystore, allright, but it looks for something else entirely):

~ $ geth account new

   Welcome to the
      FRONTIER

Your new account is locked with a password. Please give a password. Do not forget this password.
Passphrase: 
Repeat Passphrase: 
Address: {dba1d6db83a3cae28beac8850f2e9e5592572cf7}
~ $ geth account list

   Welcome to the
      FRONTIER

Primary #0: {104dd1e7839e2ffa8f268a0b0a8340584b32ca87}
Account #1: {77203d4440bfd55ec993beac25bf312cec7757f7}
Account #2: {977bae5f4fc36bd29ef0f62483bf598141ac7eea}
Account #3: {dba1d6db83a3cae28beac8850f2e9e5592572cf7}
~ $ geth --unlock=dba1d6db83a3cae28beac8850f2e9e5592572cf7

   Welcome to the
      FRONTIER

I0512 21:23:57.522643   29697 backend.go:239] Protocol Version: 60, Network Id: 0
I0512 21:23:57.522900   29697 backend.go:249] Blockchain DB Version: 2
I0512 21:23:57.530293   29697 chain_manager.go:235] Last block (#317727) 6528e4dcd1c637c5a491467b5060c7ee4eb6f916dbd5cd7642a922d9dcec2969 TD=25102922718244
I0512 21:23:58.581426   29697 cmd.go:107] Starting  Geth/v0.9.20/darwin/go1.4.2
I0512 21:23:58.583085   29697 server.go:209] Starting Server
I0512 21:23:59.596123   29697 nat.go:94] network port 30303 could not be mapped: no UPnP or NAT-PMP router discovered
I0512 21:23:59.605844   29697 udp.go:189] Listening, enode://0334aad57741893c705c7effb802f5cc60024c068e4f7d2f26dc8c26fd5eda77ef06848e000ba7b0558bdda8d8ca026f75fc2587128c7bba62d68f142275e727@[::]:30303
I0512 21:23:59.606046   29697 backend.go:456] Server started
I0512 21:23:59.606109   29697 nat.go:94] network port 30303 could not be mapped: no UPnP or NAT-PMP router discovered

I0512 21:23:59.606081   29697 server.go:349] Listening on [::]:30303
Passphrase: 
Fatal: Unlock account failed 'open /Users/vb/Library/Ethereum/keystore/6338383530663265396535353932353732636637/6338383530663265396535353932353732636637: no such file or directory'
Fatal: Unlock account failed 'open /Users/vb/Library/Ethereum/keystore/6338383530663265396535353932353732636637/6338383530663265396535353932353732636637: no such file or directory'

**Comment by zelig** [comment]
It looks like it the hex of a hex . What if you prefix your key with 0x

-------- Original message --------

**Comment by Gustav-Simonsson** [comment]
Our mistake, we didn't test this flag after the key store PR merge yestereday. Fix: https://github.com/ethereum/go-ethereum/pull/946

**Comment by debris** [comment]
I also reproduced this issue on OSX 10.10, 6dec90464dc2a263a5bcb72fdbff6c5439fb07dc.

It looks like `Library/Ethereum/keystore` directory do not exist. My previous keys were stored in `Library/Ethereum/keys`. I tried to copy them from old directory to new one, but then i get the following error:

```
> admin.unlock(eth.coinbase, 'super_secret', 10 * 60 * 1000)
Unlock account failed 'encoding/hex: invalid byte: U+0069 'i''
false
```

**Comment by obscuren** [comment]
@debris read "upgrade" section https://github.com/ethereum/go-ethereum/releases/tag/v0.9.20

**Comment by debris** [comment]
Thanks!

**Comment by arvicco** [comment]
Same stuff if I prefix with 0x, doesn't matter:

~ $ geth --unlock=0xdba1d6db83a3cae28beac8850f2e9e5592572cf7

   Welcome to the
      FRONTIER

I0513 09:35:12.179586   30335 backend.go:239] Protocol Version: 60, Network Id: 0
I0513 09:35:12.179647   30335 backend.go:249] Blockchain DB Version: 2
I0513 09:35:12.184328   30335 chain_manager.go:235] Last block (#317727) 6528e4dcd1c637c5a491467b5060c7ee4eb6f916dbd5cd7642a922d9dcec2969 TD=25102922718244
I0513 09:35:13.519335   30335 cmd.go:107] Starting  Geth/v0.9.20/darwin/go1.4.2
I0513 09:35:13.520001   30335 server.go:209] Starting Server
I0513 09:35:14.250244   30335 nat.go:94] network port 30303 could not be mapped: no UPnP or NAT-PMP router discovered
I0513 09:35:14.255580   30335 udp.go:189] Listening, enode://0334aad57741893c705c7effb802f5cc60024c068e4f7d2f26dc8c26fd5eda77ef06848e000ba7b0558bdda8d8ca026f75fc2587128c7bba62d68f142275e727@[::]:30303
I0513 09:35:14.255750   30335 backend.go:456] Server started
I0513 09:35:14.255741   30335 server.go:349] Listening on [::]:30303

I0513 09:35:14.255850   30335 nat.go:94] network port 30303 could not be mapped: no UPnP or NAT-PMP router discovered
Passphrase: 
Fatal: Unlock account failed 'open /Users/vb/Library/Ethereum/keystore/6338383530663265396535353932353732636637/6338383530663265396535353932353732636637: no such file or directory'
Fatal: Unlock account failed 'open /Users/vb/Library/Ethereum/keystore/6338383530663265396535353932353732636637/6338383530663265396535353932353732636637: no such file or directory'

**Comment by arvicco** [comment]
I confirm that the latest --devel version resolved this specific issue on OSX.

**Comment by obscuren** [comment]
Yes, this has been fixed. Sorry about the fuck up!
