### ISSUE TITLE
[RPC] unable to determine address of contract from transaction object

### ISSUE THREAD

**Issue by debris** [ethereum/go-ethereum#956]
Transactions that are contract creation transactions have field `to` set to `null`. I don't know what is the address of the contract that this transaction created. It would be nice to add this to transaction json.

```json
{
  "hash": "0xce1ac5865acc135bb04b0d4e45a5699dff08cdcb7fe056e8c897c8e7bf31e134",
  "nonce": 180,
  "blockHash": "0xae9f7564ddd8bf9a10b5a45274eedabbc7959dde61350db78f0d1d3015b13196",
  "blockNumber": 322440,
  "transactionIndex": 0,
  "from": "0xe30b49f729469c3b8ffef495b31e4d4e790a1a46",
  "to": null,
  "value": "0",
  "gas": 90000,
  "gasPrice": "10000000000000",
  "input": "0x605180600c6000396000f3007c0100000000000000000000000000000000000000000000000000000000600035048063c6888fa114602d57005b60366004356040565b8060005260206000f35b6000600782029050604c565b91905056"
}
```

scenario: 
1. Send contract creation transaction
2. After transaction is mined call `web.eth.getBlock(XXX, true)`

**Comment by obscuren** [comment]
I don't think this is in the spec. Update the RPC spec update this issue.

**Comment by frozeman** [comment]
I had a call with @debris and we should call the property `contractAddress`, which should be `null` (?, or not present?), if its a normal transaction.

**Comment by zelig** [comment]
in order to geth the correct contract  address, you need to monitor the tx hash you got back from `sendTransaction` and use `getTransactionReceipt(txhash)' https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt
