### ISSUE TITLE
[RPC/question] eth_getCode

### ISSUE THREAD

**Issue by debris** [ethereum/go-ethereum#957]
I'm not sure if this question is more related with solidity or rpc. What exactly eth_getCode returns? Is the code 'optimized' after sending transaction?

Scenario:

- i created and submited following contract:
```
contract test {
  function multiply(uint a) constant returns(uint d) {
    return a * 7;
  }
};
```
compiled to:
```
0x605180600c6000396000f3007c0100000000000000000000000000000000000000000000000000000000600035048063c6888fa114602d57005b60366004356040565b8060005260206000f35b6000600782029050604c565b91905056
```

- after being mined, I call `web.eth.getCode(address)` and get following output:
```
'0x7c0100000000000000000000000000000000000000000000000000000000600035048063c6888fa114602d57005b60366004356040565b8060005260206000f35b6000600782029050604c565b91905056'
```

which is 12 bytes shorter contract that i posted. Why? 
Btw. contract works fine.

@chriseth ?

**Comment by chriseth** [comment]
The code that is part of the transaction also contains the init part, e.g. the constructors and the snippet that returns the final code. `eth.getCode` only retrieves the final code that is stored at the given address, e.g. the code that is returned by the init part.

**Comment by debris** [comment]
thanks!
