### ISSUE TITLE
geth crash

### ISSUE THREAD

**Issue by mike80439** [ethereum/go-ethereum#964]
fell over at 10:40am MDT. brew update; brew reinstall ethereum at about 9:00am MDT.

http://pastebin.com/cR6auBeB

>geth version

   Welcome to the
      FRONTIER

Geth
Version: 0.9.20
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.4.2/libexec

**Comment by debris** [comment]
looks like #955. Should be fixed now
