### ISSUE TITLE
Error starting Geth:  listen udp :30303: bind: address already in use

### ISSUE THREAD

**Issue by jmiehau** [ethereum/go-ethereum#977]
//Already I created a peer with my computer last days with Geth 0.9.20, but today I cannot connect. I got this error:

xx-de-xx:~ xx$ Geth

   Welcome to the
      FRONTIER

I0514 16:01:32.966089    1750 backend.go:239] Protocol Version: 60, Network Id: 0
I0514 16:01:32.966124    1750 backend.go:249] Blockchain DB Version: 2
I0514 16:01:32.967288    1750 chain_manager.go:235] Last block (#322030) c32194138b8ec3400a62ba6b3d5436c4f3826de1528648273fa1dd2ef816a36c TD=26863667863678
I0514 16:01:33.441128    1750 cmd.go:107] Starting  Geth/v0.9.20/darwin/go1.4.2
I0514 16:01:33.441232    1750 server.go:209] Starting Server
Fatal: Error starting Ethereum: listen udp :30303: bind: address already in use
Fatal: Error starting Ethereum: listen udp :30303: bind: address already in use
xx-de-xx:~ xx$

**Comment by jmiehau** [comment]
xx-de-xx:~ xx$ Geth --verbosity 5

   Welcome to the
      FRONTIER

I0514 16:06:22.709408    1762 backend.go:239] Protocol Version: 60, Network Id: 0
I0514 16:06:22.709480    1762 backend.go:249] Blockchain DB Version: 2
I0514 16:06:22.724322    1762 statedb.go:232] (+) 0000000000000000000000000000000000000002
I0514 16:06:22.724481    1762 statedb.go:232] (+) 0000000000000000000000000000000000000003
I0514 16:06:22.724527    1762 statedb.go:232] (+) 0000000000000000000000000000000000000004
I0514 16:06:22.724563    1762 statedb.go:232] (+) e4157b34ea9615cfbde6b4fda419828124b70c78
I0514 16:06:22.724610    1762 statedb.go:232] (+) b9c015918bdaba24b4ff057a92a3873d6eb201be
I0514 16:06:22.724664    1762 statedb.go:232] (+) 6c386a4b26f73c802f34673f7248bb118f97424a
I0514 16:06:22.724689    1762 statedb.go:232] (+) e6716f9544a56c530d868e4bfbacb172315bdead
I0514 16:06:22.724736    1762 statedb.go:232] (+) 0000000000000000000000000000000000000001
I0514 16:06:22.724842    1762 statedb.go:232] (+) cd2a3d9f938e13cd947ec05abc7fe734df8dd826
I0514 16:06:22.724913    1762 statedb.go:232] (+) 2ef47100e0787b915105fd5e3f4ff6752079d5cb
I0514 16:06:22.724987    1762 statedb.go:232] (+) 1a26338f0d905e295fccb71fa9ea849ffa12aaf4
I0514 16:06:22.725041    1762 statedb.go:232] (+) dbdbdb2cbd23b783741e8d7fcf51e459b497e4a6
I0514 16:06:22.725497    1762 chain_manager.go:235] Last block (#322030) c32194138b8ec3400a62ba6b3d5436c4f3826de1528648273fa1dd2ef816a36c TD=26863667863678
I0514 16:06:23.944999    1762 state_object.go:241] 0000000000000000000000000000000000000000: gas (+ 3141592)
I0514 16:06:23.945060    1762 state_object.go:197] 0000000000000000000000000000000000000000: #0 1000000000000000000050923695826000000014650 (+ 1500000000000000000)
I0514 16:06:23.967973    1762 cmd.go:107] Starting  Geth/v0.9.20/darwin/go1.4.2
I0514 16:06:23.968079    1762 server.go:209] Starting Server
Fatal: Error starting Ethereum: listen udp :30303: bind: address already in use
Fatal: Error starting Ethereum: listen udp :30303: bind: address already in use
xx-de-xx:~ xx$

**Comment by fjl** [comment]
Do you have the OS X firewall enabled?

**Comment by tgerring** [comment]
Do you get the same error if you start geth with a different port? For example, `--port "30304"`

**Comment by jmiehau** [comment]
@fjl I am not using firewall at mac, it is disable.

@tgerring , adding another port it helps me to connect to the main Chain!

xx-de-xx:~ xx$ geth --port "30304"

   Welcome to the
      FRONTIER

I0515 02:16:00.885143    2778 backend.go:239] Protocol Version: 60, Network Id: 0
I0515 02:16:00.885184    2778 backend.go:249] Blockchain DB Version: 2
I0515 02:16:00.886260    2778 chain_manager.go:235] Last block (#322030) c32194138b8ec3400a62ba6b3d5436c4f3826de1528648273fa1dd2ef816a36c TD=26863667863678
I0515 02:16:06.382992    2778 cmd.go:107] Starting  Geth/v0.9.20/darwin/go1.4.2
I0515 02:16:06.383091    2778 server.go:209] Starting Server
I0515 02:16:06.476895    2778 udp.go:189] Listening, enode://fdc9a2345e5677d3b3db0065450caa864ee2f7044dce18616e6552584f7654b8a1ec9326787217939a84695f72d98f7a29996174aad4c1566a1dad5593b885b1@192.167.1.10:30304
I0515 02:16:06.477033    2778 backend.go:456] Server started
I0515 02:16:06.477049    2778 server.go:349] Listening on [::]:30304
I0515 02:16:32.906817    2778 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 2.924078518s. #322286 [caeef125 / b70c6fb7]
I0515 02:16:34.027605    2778 chain_manager.go:628] imported 128 block(s) (0 queued 0 ignored) in 1.120716565s. #322414 [3c0c1a1a / 236a9a27]
I0515 02:16:36.345342    2778 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 1.852855271s. #322670 [e2a52ef1 / 292a6b69]
I0515 02:16:37.844329    2778 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 1.498925754s. #322926 [5c3886e7 / eeabf61b]
I0515 02:16:39.512527    2778 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 1.668134553s. #323182 [e15556bb / fab6df9b]
I0515 02:16:40.691838    2778 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 1.179237486s. #323438 [d62aaff9 / 438ba4c7]
