### ISSUE TITLE
Synchronisation failed: peer's unknown or unhealthy

### ISSUE THREAD

**Issue by avdoshyn** [ethereum/go-ethereum#978]
http://prntscr.com/754g68

I0514 16:24:51.652331    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:25:03.931033    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:25:10.934434    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:25:16.017725    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:25:25.066242    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:25:26.581329    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:25:30.211536    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:25:38.765026    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:25:39.756082    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:25:43.206280    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:25:54.248911    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:25:59.477210    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:26:14.845089    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:26:18.678309    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:26:22.662536    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:26:22.918551    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy
I0514 16:26:26.873777    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy

**Comment by karalabe** [comment]
Geth version? Number of peers?

**Comment by avdoshyn** [comment]
CPU=4 TOT=6
Geth-Win 0.9.20

>> Does it keep happening if you restart geth?

now is ok

**Comment by karalabe** [comment]
I'm guessing this was only a bad network connection, because of which you tried to pull from the same faulty peer. I'll close this now, but feel free to open a new issue if it reappears. Btw, if it does, please also send the number of peers you have (you can query that if you run the console and type `net` into it).
