### ISSUE TITLE
mining focused on blocks that are too old?

### ISSUE THREAD

**Issue by jpritikin** [ethereum/go-ethereum#981]
I'm not sure if this is what I'm seeing, but it looks like block 333862 was available and geth mined on 333595. What's up with that? That's way too old to be an uncle, isn't it?

````
I0514 12:24:55.692692    7876 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 6.422752ms. #333862 [685fbbaf / 685fbbaf]
I0514 12:24:55.694146    7876 worker.go:342] commit new work on block 333863 with 0 txs & 0 uncles
I0514 12:24:58.972846    7876 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 6.145807ms. #333595 [912153ed / 912153ed]
I0514 12:24:58.972920    7876 worker.go:227] 🔨  Mined block #333595
````

**Comment by jpritikin** [comment]
Mining works sometimes though. Here is an example. I forgot to mention this is geth v0.8.5-2-2128-g7fa7409 on Linux.

````
I0514 12:38:20.594044    7876 worker.go:342] commit new work on block 333974 with 0 txs & 1 uncles
I0514 12:38:25.571179    7876 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 5.928247ms. #333974 [618a93ca / 618a93ca]
I0514 12:38:25.572147    7876 worker.go:342] commit new work on block 333975 with 0 txs & 1 uncles
I0514 12:38:30.994029    7876 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 11.046394ms. #333975 [8dfae93c / 8dfae93c]
I0514 12:38:30.994133    7876 worker.go:227] 🔨  Mined block #333975
````

**Comment by tgerring** [comment]
If you're using 0.8.5, I would highly recommend updating to latest which contains many mining improvements. Current version is [0.9.20](https://github.com/ethereum/go-ethereum/releases/tag/v0.9.20)

**Comment by jpritikin** [comment]
Yeah, I'm already using 7fa740996cf01b = v0.8.5-2-2128-g7fa7409

**Comment by obscuren** [comment]
Did you start mining before it was caught up?

**Comment by karalabe** [comment]
Anyone notice this issue ever since? @jpritikin ?

**Comment by jpritikin** [comment]
It doesn't happen very frequently, in my experience.

**Comment by karalabe** [comment]
I'll close this as hopefully solved by the many fixes since the issue was opened. If you still see something similar, please reopen a new issue with fresh logs.
