### ISSUE TITLE
Synchronisation failed: block downloading cancelled (requested) - no upgradedb issued

### ISSUE THREAD

**Issue by anthony-cros** [ethereum/go-ethereum#991]
Similar to https://github.com/ethereum/go-ethereum/issues/944 alghouth I did not issue any "upgradedb" command:

```
I0515 14:54:38.555122    2220 chain_manager.go:558] INVALID block #337788 (f976a08665d7e2affabda087f3acd5c5be1f954d1bf270d14e8db3766ee72016)
I0515 14:54:38.555165    2220 chain_manager.go:559] invalid merkle root. received=f43bbd679e059ca8fb993ede19d4ca43c826dd9eb42ee461a298fb3262eba3ce got=a1b11a189991f14b0005e611aead449ed2ecf16af4e35afc850f8dbadcaef640
I0515 14:54:38.555226    2220 sync.go:103] Synchronisation failed: block downloading cancelled (requested)
```

See full logs at: https://gist.github.com/anthony-cros/260951f9646df6ba7d87

**Comment by obscuren** [comment]
Remove your DB, upgrade to version `0.9.20`

**Comment by anthony-cros** [comment]
This is happening again, this time on 0.9.20 and on a fresh install (no existing DB). Would 0.9.21 solve it?

```
I0516 01:14:24.170877    6160 chain_manager.go:558] INVALID block #347607 (ca0bf6bb0bdcbc65434715d70c348dfc84088939e608e2eb21ac020128521ddc)
I0516 01:14:24.170964    6160 chain_manager.go:559] invalid merkle root. received=08faa6a061fa3753b9a030aec4c35dcb8efc6d9c5c8b511f9c8ac19edaf15b20 got=7646447e9b321f3dafdab4864970b945c362b888ebbf787c428f872765eef08f
I0516 01:14:24.171032    6160 sync.go:104] Synchronisation failed: block downloading cancelled (requested)
```

**Comment by obscuren** [comment]
Got a full log?

**Comment by anthony-cros** [comment]
https://gist.github.com/anthony-cros/506594a2a8936def162f

I had issued "geth upgradedb" earlier in that session too (not shown in the log though), in case it's relevant. Incidentally, either I don't understand how upgradedb works, or it didn't work! Doesn't it bring you to the most recent block?

**Comment by ligi** [comment]
I also just got this - with another reason though:

I0618 22:44:24.068606   14717 chain_manager.go:801] Bad block #569767 (51454182f6309f991ef8d0d3c6e8ef6d424c1253373bf6b12ec0f175b09b3ffc)
I0618 22:44:24.068643   14717 chain_manager.go:802] gas used error (3118455 / 3141592)
I0618 22:44:24.068728   14717 downloader.go:224] Synchronisation failed: block downloading canceled (requested)
I0618 22:44:49.232976   14717 chain_manager.go:801] Bad block #569767 (51454182f6309f991ef8d0d3c6e8ef6d424c1253373bf6b12ec0f175b09b3ffc)
I0618 22:44:49.233011   14717 chain_manager.go:802] gas used error (3118455 / 3141592)
I0618 22:44:49.233082   14717 downloader.go:224] Synchronisation failed: block downloading canceled (requested)
I0618 22:45:28.171868   14717 chain_manager.go:801] Bad block #569767 (51454182f6309f991ef8d0d3c6e8ef6d424c1253373bf6b12ec0f175b09b3ffc)
I0618 22:45:28.171903   14717 chain_manager.go:802] gas used error (3118455 / 3141592)
I0618 22:45:28.171969   14717 downloader.go:224] Synchronisation failed: block downloading canceled (requested)
I0618 22:46:00.083726   14717 chain_manager.go:801] Bad block #569767 (51454182f6309f991ef8d0d3c6e8ef6d424c1253373bf6b12ec0f175b09b3ffc)
I0618 22:46:00.083780   14717 chain_manager.go:802] gas used error (3118455 / 3141592)
I0618 22:46:00.083935   14717 downloader.go:224] Synchronisation failed: block downloading canceled (requested)
I0618 22:46:52.300857   14717 chain_manager.go:801] Bad block #569767 (51454182f6309f991ef8d0d3c6e8ef6d424c1253373bf6b12ec0f175b09b3ffc)
I0618 22:46:52.300911   14717 chain_manager.go:802] gas used error (3118455 / 3141592)
I0618 22:46:52.301077   14717 downloader.go:224] Synchronisation failed: block downloading canceled (requested)
I0618 22:47:18.150640   14717 chain_manager.go:801] Bad block #569767 (51454182f6309f991ef8d0d3c6e8ef6d424c1253373bf6b12ec0f175b09b3ffc)
I0618 22:47:18.150675   14717 chain_manager.go:802] gas used error (3118455 / 3141592)
I0618 22:47:18.150747   14717 downloader.go:224] Synchronisation failed: block downloading canceled (requested)
I0618 22:49:09.298694   14717 chain_manager.go:801] Bad block #569767 (51454182f6309f991ef8d0d3c6e8ef6d424c1253373bf6b12ec0f175b09b3ffc)
I0618 22:49:09.298897   14717 chain_manager.go:802] gas used error (3118455 / 3141592)
I0618 22:49:09.299223   14717 downloader.go:224] Synchronisation failed: block downloading canceled (requested)

**Comment by reppolice** [comment]
I am getting the same on a brand new installation of Ubuntu 17.04 via the repo
