### ISSUE TITLE
Should the CALL opcode with empty address create a new contract?

### ISSUE THREAD

**Issue by ebuchman** [ethereum/go-ethereum#993]
I have not found a definite answer to this question in the yellow paper, and from inspection of the code it appears that a CALL to an empty address will create a new account for the price of a call (rather than the price of a create), but with no code. Is this expected behaviour? Can someone clarify? Would be nice to add this to https://github.com/ethereum/wiki/wiki/Subtleties

**Comment by obscuren** [comment]
Define empty address. Leaving it out would fail in a stack error

**Comment by ebuchman** [comment]
Ah right. It would be an all zeros address, so that's actually a call to the zero address. So it'll send it the value and I guess do nothing else. Is anything regarding the 0-address defined? Presumably a normal tx to the 0-address isn't a contract creation either, and it doesn't seem to be a native contract.

**Comment by obscuren** [comment]
Indeed! If you look on the current testnet you can actually see people made some mistakes (though we could definitely provide some feedback from out part)
