### ISSUE TITLE
Mist consistently crashes on startup

### ISSUE THREAD

**Issue by mike80439** [ethereum/go-ethereum#999]
http://pastebin.com/n8hYsZdB

Seems to happen when it tries to catchup the block chain. Last block in display is 344737.

[~] $ geth version

   Welcome to the
      FRONTIER

Geth
Version: 0.9.20
Protocol Version: 60
Network Id: 0
Go Version: go1.4.2
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.4.2/libexec
[~] $ 

Updated this morning (Friday) at about 8:00am MDT (GMT-6)

**Comment by tgerring** [comment]
Mist is out of scope right now and badly broken. If you have the same problem with Geth, please re-open this issue.
